### ISSUE TITLE
[$500] Workspace -Assign Task-Random employee can edit/reassign task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:** @

## Action Performed:
Precondition: Prepare 3 accounts:
A workspace admin
A workspace employee A (task creator)
A workspace employee B
Add all accounts to the workspace of the workspace admin
Should be executed after C2661791

1. Log in to a Staging.new.expensify.com
2. Navigate to the workspace #Announce room
3. Click on the task created by the workspace employee A
4. Edit the title of the task
5. Reassign the task
6. Edit the description of the task

## Expected Result:
Employees who are non creators nor assigned should Not have permission to edit and reassign tasks created by other employees of the workspace.

## Actual Result:
Employees who are non creators nor assigned should Have permission to edit and reassign tasks created by other employees of the workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6ea25f1f-9494-49b7-922c-e1ca688cd1a2

![Bug6315478_1702687645640!pas29-3](https://github.com/Expensify/App/assets/115492554/05e02345-f0fe-4749-a142-2cfea52c988c)

![Bug6315478_1702687645632!pas29-1](https://github.com/Expensify/App/assets/115492554/b3e822b0-48ac-42ee-a98f-b1fddb766b4a)

![Bug6315478_1702687645626!pas29-2](https://github.com/Expensify/App/assets/115492554/ccba0864-0aad-4128-b694-5cb3814d38bc)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a704827129d85780</li>
        <li>Upwork Job ID: 1736774593975758848</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by karimiBadr** [comment]
@allroundexperts 
I believe this issue has already been fixed.
https://github.com/Expensify/App/pull/32165

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by michaelhaxhiu** [comment]
no longer reproducible
