### ISSUE TITLE
[$500]  getting “transaction no longer exists” error when trying to edit merchant or category field on an expense on a draft report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702933494162939

## Action Performed:
1. Open a chat
2. Create a expense report by scanning a receipt 
3. edit the merchant name or category field

## Expected Result:
Able to edit merchant and category name

## Actual Result:
getting “transaction no longer exists” error message appears

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2023-12-18 at 4 04 14 PM](https://github.com/Expensify/App/assets/38435837/25e77a71-3cb3-4bb0-b487-f9f98d971b53)

![image (2)](https://github.com/Expensify/App/assets/38435837/3ce70b5c-58dc-4028-9dde-941b475c07ac)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01301701aab67acd7d</li>
        <li>Upwork Job ID: 1738259183335497728</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
I assume we can get someone external to tackle this?

**Comment by hsfranco** [comment]
Can you guys share the code with the request of the API?

**Comment by mumincelal** [comment]
![image](https://github.com/Expensify/App/assets/15386828/432adb77-9c85-4052-b3a0-f1a6a6f64478)

Can not reproduce it.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by kevinksullivan** [comment]
closing out if not reproducible.
