### ISSUE TITLE
New typecheck issue from `AvatarSource`

### ISSUE THREAD

**Issue by lindboe** [Expensify/App#33260]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** `main` branch
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** n/a
**Issue reported by:** @lindboe
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1702943381905719?thread_ts=1702943306.379829&cid=C01GTK53T8Q

This is a developer-only issue. Types introduced in https://github.com/Expensify/App/pull/32731 are causing type failures on other PRs (e.g., https://github.com/Expensify/App/actions/runs/7255185932/job/19765298585?pr=32528)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
Revert PR is here: https://github.com/Expensify/App/pull/33261
