### ISSUE TITLE
[HOLD for payment 2023-12-29] [HOLD for payment 2023-12-28] Desktop - Sign In - Console error Uncaught (in promise) TypeError: Cannot read properties

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33290]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31303

## Action Performed:
1. Sign Out
2. Kill the app
3. Open app
4. Sign In

## Expected Result:
Console errors should not be displayed

## Actual Result:
Console error displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5d61a7c3-0bdc-445c-8184-9c5aeb13ecd2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
I haven't seen this yet, I will be afk for a couple of hours and check it out when I return.

**Comment by marcochavezf** [comment]
Ok I found the cause of the problem, creating a PR to fix it

**Comment by marcochavezf** [comment]
PR up

**Comment by marcochavezf** [comment]
Hi @joekaufmanexpensify, could you pay for the C+ review for @allroundexperts?

**Comment by joekaufmanexpensify** [comment]
Per [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1703082403934039), payment may be delayed a few days here because of the holidays. @allroundexperts if you have time over the next week to handle the BZ checklist too, that'd be great!

**Comment by marcochavezf** [comment]
Not overdue, checklist is still pending

**Comment by MitchExpensify** [comment]
Not sure why I was assigned, looks like @joekaufmanexpensify is on the case

**Comment by joekaufmanexpensify** [comment]
Yep! Just need @allroundexperts to handle BZ checklist and then I'll issue payment.

**Comment by joekaufmanexpensify** [comment]
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1704208634755849)

**Comment by joekaufmanexpensify** [comment]
Still discussing in Slack

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/13997
2. https://github.com/Expensify/App/pull/13997/files#r1440680291
3. N/A
4. I think this is really small and regression test would be an overkill. 

Do we 👍 or 👎 ?

**Comment by joekaufmanexpensify** [comment]
TY! Checklist is done. All set to issue payment.

**Comment by joekaufmanexpensify** [comment]
Only payment needed here is $500 to @allroundexperts for C+ review. Paid via NewDot.

**Comment by joekaufmanexpensify** [comment]
@allroundexperts could you please request $500 and comment here once you've done that?

**Comment by joekaufmanexpensify** [comment]
Chatted with @allroundexperts and confirmed good to close.

**Comment by JmillsExpensify** [comment]
$500 payment to @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/33290#issuecomment-1875949921).
