### ISSUE TITLE
[$500] Compose-Copy link option is not displayed in context menu in gmail accounts.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33307]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with gmail account
3. Tap on a chat
4. Long press any sent message and note context menu options

## Expected Result:
Copy link option must be displayed in context menu in gmail accounts.

## Actual Result:
Copy link option is not displayed in context menu in gmail accounts.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/95a179fb-ef1d-4bc2-8f4d-0aa25aa6c973

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01639bed3a0bc7f5b9</li>
        <li>Upwork Job ID: 1737165774942121984</li>
        <li>Last Price Increase: 2023-12-26</li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Compose-Copy link option is not displayed in context menu in gmail accounts.
### What is the root cause of that problem?
We don't have permission for copy link
### What changes do you think we should make in order to solve the problem?
We need to update backend api for beta.
### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment]
Agreed, this isn't a bug for now. it's behind a beta
