### ISSUE TITLE
LHN - When user enters multiline message, first and last line displayed in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33308]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a chat
3. Enter a multi line message (eg: select a emoji, tap few times enter key, then enter a text)
4. Note the chat message in LHN

## Expected Result:
When user enters multiline message, only first line must be displayed in LHN

## Actual Result:
When user enters multiline message, first and last line both displayed in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7a17b5b5-f0ff-45b8-9b2f-70949a46d60c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
@bernhardoj this is deploy blocker so you mean that regression came from staging backend?

**Comment by neil-marcellini** [comment]
Yep, thanks @bernhardoj!
