### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500]  Theme - Input in Merchant field isn't visible in light mode when select item from suggest list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33318]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: App is setup on Light theme
1. Navigate to staging.new.expensify.com
2. Start Request money> Manual flow
3. On Manual page select Merchant
4. Use Merchant from suggestion link

## Expected Result:
Selected Merchant should be visible in input field

## Actual Result:
Selected Merchant is not visible in input field. Letters are light just like the theme

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eaf6eb7e-9d5f-4479-b1e1-bfc97e1755c4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01704ce5a9ef62e618</li>
        <li>Upwork Job ID: 1737228586984062976</li>
        <li>Last Price Increase: 2023-12-19</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28066426</li>
<li>tienifr | Contributor | 28066427</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Theme - Input in Merchant field isn't visible in light mode when select item from suggest list
### What is the root cause of that problem?
We have custom autofill color.
https://github.com/Expensify/App/blob/aa1d87caddb6831061f3750bd78f77b42603e5e3/web/index.html#L95-L95
### What changes do you think we should make in order to solve the problem?
We need to remove this.

### What alternative solutions did you explore? (Optional)

**Comment by yh-0218** [comment]
Hi @aimane-chnaif Could you check my updated [Proposal](https://github.com/Expensify/App/issues/33318#issuecomment-1863593026)
I think this is good way. Your opinion?

**Comment by thienlnam** [comment]
Assigning you since this is a theme related bug and you have more context on it

**Comment by grgia** [comment]
Thank you for the proposal @tienifr, all yours!

**Comment by bfitzexpensify** [comment]
Agreed @aimane-chnaif. Contracts paid out, we're all done here - thanks everyone!
