### ISSUE TITLE
Request Money – Unexpected error appears when filling fields after scan failure

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Start the Request money flow in a 1:1 conversation with a user you have access to
4. Select the scan option and upload a picture that will fail the scan process
5. Wait for the scan to fail
6. Edit the missing fields Amount and Merchant

## Expected Result:
The error is cleared after the fields are edited

## Actual Result:
Unexpected error appears when filling fields after scan failure

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/643288df-65b6-4892-b752-b996ef9a3813

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
I can repro, this appears to be a backend issue given the error message. It points out to something that was recently deployed to staging.

```
{
    "jsonCode": 0,
    "message": "User_Utils::isValidLength(): Argument #1 ($property) must be of type string, null given, called in \/git\/releases\/expensify.com\/f0f30fb\/lib\/TransactionAPI.php on line 678",
    "requestID": "8382cd6cecbafa5a-SJC",
    "onyxData": []
}
```

**Comment by francoisl** [comment]
Backend fix was deployed to staging, this flow is working now.

https://github.com/Expensify/App/assets/2229301/c92180ac-32a1-490e-b952-177f00a8a931
