### ISSUE TITLE
 Chat - Message sender avatar is missing on applausetester+multiline account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33314]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to [applausetester+multiline@applause.expensifail.com](mailto:applausetester+multiline@applause.expensifail.com)
2. Go through some chat (already pinned)

## Expected Result:
The message sender avatar will be displayed

## Actual Result:
The message sender avatar is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/99403cea-e423-4f7c-be61-6a5cfc9814fd

<img width="1440" alt="Bug6320217_1703015931468!Screenshot_2023-12-20_at_03 58 31" src="https://github.com/Expensify/App/assets/78819774/b8c685cc-e87f-47ef-87ea-64a0e10595c3">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
What is the `multiline` account?

**Comment by AndrewGable** [comment]
While this is weird, how did we get that account into that state? Does it continue to happen after a log in/out?

**Comment by AndrewGable** [comment]
Let's reopen when we get clearer reproduction steps
