### ISSUE TITLE
[$500] IOS - App crashes after entering phone number 2nd or 3rd time in invite member flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33311]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when excuting PR** https://github.com/Expensify/App/pull/31010
## Action Performed:
1. Open the app and log in
2. Create a workspace if there is no one
3. Tap FAB > Start Chat > Room
4. Create a room
5. Open the created room and
6. Tap the header > Members > Invite
7. Enter the phone number and tap "Invite"
8. Enter the same phone number

## Expected Result:
The message "<phone number> is already a member of <room name>" should appear

## Actual Result:
The app crashes after waiting for some time. Sometimes it crashes only after 3rd time entering the same phone number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/88a1bd8e-350a-4853-a874-43229fcd40f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b236fe00f56d57e3</li>
        <li>Upwork Job ID: 1737240068424257536</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by situchan** [comment]
@lanitochka17 do you have crash log?

**Comment by yuwenmemon** [comment]
Not able to reproduce locally on staging on my iPhone.

**Comment by situchan** [comment]
The log file is super long so not able to point out exact crash log 😞

**Comment by yuwenmemon** [comment]
Can't reproduce on a simulated iOS device either. Unfortunately if it's not a reliably reproducible crash I'm not sure how we're going to fix it so I'm going to at least remove the deploy blocker label and put this issue for triage.

**Comment by muttmuure** [comment]
The change to handling phone numbers was reverted
