### ISSUE TITLE
[HOLD for payment 2024-02-01] Add a full screen engagement modal to NewDot

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#33324]
Copied from https://github.com/Expensify/Expensify/issues/335513

### Problem:

Building on top of the engagement problem we're solving in [Wave 9 Collect Sign Ups](https://expensify.slack.com/archives/CC7NECV4L/p1698873625305299), we will be testing what approach to engagement works best in NewDot compared to OldDot using the public domain cohort we are sending as part of [Direct Public signups to NewDot](https://docs.google.com/document/d/19Hpj0eSW_Wff_8ujkJ16CqZbQX5lkfQ_sZdjJlUGYOM/edit). The text-based approach means we need to manually track responses (Intended for V1 but time-consuming long term), build a temporary banner in NewDot, and have to manually remove the classicRedirect NVP from users that shouldn't return to NewDot on their second sign-in (Anyone not a pure submitter),

### Solution:

Introduce an actionable engagement popup that automates:

Redirection to OldDot for non NewDot friendly users (Any Collect / Control users)
classicRedirect NVP from users that shouldn't return to NewDot when signing into expensify.com
Track responses to the question "What are you here to do?"
To begin with, as our MVP, we will simply:

Show the modal immediately in NewDot
Change the modal option copy to:

Track my business expenses to file taxes
Submit expenses to my employer to get paid back
Manage my team's expenses
Chat and split expenses with friends
Change the modal option copy to:
Track my business expenses to file taxes
Submit expenses to my employer to get paid back
Manage my team's expenses
Chat and split expenses with friends and family
Send these messages from Concierge based on the user's selection:
Track my expenses to file taxes:
"Great! To track your expenses, I suggest you create a workspace to keep everything contained:

Press your avatar icon
Choose Workspaces
Choose New Workspace
Name your workspace something meaningful (eg, "My Business Expenses")
Once you have your workspace set up, you can add expenses to it as follows:

Choose My Business Expenses (or whatever you named it) in the list of chat rooms
Choose the + button in the chat compose window
Choose Request money
Choose what kind of expense you'd like to log, whether a manual expense, scanned receipt, or tracked distance.
That'll be stored in your My Business Expenses room for your later access. Thanks for asking, and let me know how it goes!"

Submit expenses to my employer to get paid back
""Hi there, to submit expenses for reimbursement, please:

Press the big green + button
Choose Request money
Indicate how much to request, either manually, by scanning a receipt, or by tracking distance
Enter the email address or phone number of your boss
And we'll take it from there to get you paid back. Please give it a shot and let me know how it goes!"

Manage my team's expenses
"Great! To manage your team's expenses, create a workspace to keep everything contained:

Press your avatar icon
Choose Workspaces
Choose New Workspace
Name your workspace something meaningful (eg, "Galaxy Food Inc.")
Once you have your workspace set up, you can invite your team to it via the Members pane and [connect a business bank account](https://help.expensify.com/articles/new-expensify/bank-accounts/Connect-a-Bank-Account) to reimburse them!"

Chat and split expenses with friends
Hi there, to split an expense such as with a friend, please:

Press the big green + button
Choose Request money
Indicate how much was spent, either manually, by scanning a receipt, or by tracking distance
Enter the email address or phone number of your friend
Press Split next to their name
Repeat as many times as you like for each of your friends
Press Add to split when done adding friends
Press ​Split to split the bill
This will ​send an a money request to each of your friends ​for however much they owe you, and we'll take care of getting you paid back. Thanks for asking, and let me know how it goes!

Change the Concierge intro message to:
":wave: Welcome to Expensify! I'm Concierge, what do you want to use Expensify for? Chat with me now for real-time support and I can help you get started :rocket:"

Store the response in an NVP

Close the modal
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185f4ecad90df3d65</li>
        <li>Upwork Job ID: 1751986081000153088</li>
        <li>Last Price Increase: 2024-01-29</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
Seems like this is a new feature, rather than a bug, so going to unassign myself for now. If anything comes up that requires someone from BZ (like paying a contributor), feel free to reassign me, and I'll handle it!

**Comment by joekaufmanexpensify** [comment]
PR is in review

**Comment by stitesExpensify** [comment]
Still working on this. We got caught in the typescript migration and I had to refactor the majority of the PR. Hopefully it will be merged this week

**Comment by stitesExpensify** [comment]
@joekaufmanexpensify can we double @situchan pay here to $1000? They put in a lot of work and reviewed the PR many times

**Comment by joekaufmanexpensify** [comment]
Sounds good. Yep, we can!

**Comment by joekaufmanexpensify** [comment]
@situchan offer sent for $1,000!

**Comment by joekaufmanexpensify** [comment]
@situchan could you please propose the regression test steps? That's all that's left before we can issue payment later this week.

**Comment by situchan** [comment]
@stitesExpensify can we use Tests Steps in [PR](https://github.com/Expensify/App/pull/32154) as new regression test? Or extract from design doc?

**Comment by stitesExpensify** [comment]
Yes I think we can use the test steps from the PR. We need to add one more though that we missed the first time:

1. Create a new account on OldDot
2. Make sure that you are taken to NewDot
3. Make sure that the modal is shown
4. Select any option
5. Make sure that concierge sends a message

**Comment by joekaufmanexpensify** [comment]
Got it, sounds good. I'll work on creating an issue to add those new regression tests! Payment will be issued tomorrow.

**Comment by joekaufmanexpensify** [comment]
Regression test issue is [here](https://github.com/Expensify/Expensify/issues/365920)

**Comment by joekaufmanexpensify** [comment]
All set to issue payment here!

**Comment by joekaufmanexpensify** [comment]
@situchan $1,000 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
