### ISSUE TITLE
[$500] Distance - Map can not be downloaded immediately when add new stop

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33321]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to a workspace chat with distance request
2. Open distance request details page
3. Click Distance
4. Click Add stop
5. Add a new address
6. Open distance request details page
7. Click on map detail page
8. Click Download

## Expected Result:
When click download map should immediately download to the device

## Actual Result:
Map can not be downloaded immediately when User add new stop on already created Distance request.
It needs to take awhile so the map can be successfully downloaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f6370fa1-ca68-4e3d-9913-f712f43252c3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014769682f69609314</li>
        <li>Upwork Job ID: 1737231317324488704</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by miljakljajic** [comment]
I'll try to reproduce this now!

**Comment by miljakljajic** [comment]
I can't reproduce this and I think it's something of an edge case given that the map can eventually be downloaded, just not right away. I think we'll close out for now.
