### ISSUE TITLE
[Wave 6: Workspace Chats] Ensure the report preview action updates created timestamp when the IOU actions are taken

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#33349]
Coming from [here](https://expensify.slack.com/archives/C02MW39LT9N/p1703006670584199?thread_ts=1702908968.741649&cid=C02MW39LT9N), we want to ensure the report preview report action moves as IOU actions:
- Submit
- Approve
- Paid (already happening)

This will be achieve using the `createOrUpdateReportPreview` method which we should use in submit and approve 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01430a3cf4ecec3f64</li>
        <li>Upwork Job ID: 1737456186709827584</li>
        <li>Last Price Increase: 2023-12-20</li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
Hi @mountiny, are you working on this? Since this is also impacting wave7, I'm happy to give a hand here and take a look if you think it should be fixed internally

**Comment by mountiny** [comment]
Yep I will handle this one

**Comment by mountiny** [comment]
Auth PR is under way, looking into passing the onyx update directly from Auth but this is first time we do this for report preview actions

**Comment by mountiny** [comment]
Not sure why this did not autoclose
