### ISSUE TITLE
[HOLD for payment 2024-01-11] [$50] HelpDot Update - Change the name of a homepage category on New Expensify

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#33376]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Expensify/Expensify Issue URL:** https://help.expensify.com/new-expensify/hubs/get-paid-back/
**Issue reported by:** Margaret Madelyn Lewis
**Slack conversation:** https://expensify.slack.com/archives/C02QSAC6BJ8/p1702999732847589

## Request
Rename `Get Paid Back` to `Payments`
<img width="764" alt="image" src="https://github.com/Expensify/App/assets/38016013/7687aaff-2974-4276-9212-7e5e5f5e6199">

## Steps to complete
Renaming folders is best done on your local machine, or on [github.dev](http://github.dev/).

Instructions on how to do this on [github.dev](http://github.dev/):
#### PART 1/3: Rename folder inside docs/new-expensify/hub
1. Go to https://github.com/Expensify/App
2. Press . (dot) on your keyboard
3. On LHN, you can see folders and can navigate around by clicking the folders
4. Go to docs/new-expensify/hubs/
5. Right click the folder get-paid-back/ and select rename.
6. Rename the folder to payments
<img width="360" alt="image" src="https://github.com/Expensify/App/assets/38016013/e5039d5c-0c2e-4c69-822e-70f761653266">

#### PART 2/3:
1. Rename folder inside docs/articles/new-expensify
2. Go to docs/articles/new-expensify/
3. Right click the folder get-paid-back/ and select rename.
4. Rename the folder to payments

#### PART 3/3:
1. Finally, changes in _routes.yml
2. Open docs/_data/_routes.yml 
3. Rename get-paid-back to payments
4. Change title to Payments
<img width="576" alt="image" src="https://github.com/Expensify/App/assets/38016013/9654d2c8-9e98-46a9-83f1-767eedf517bd">

#### To push the changes -
1. Go to source control. The tree like icon
2. Enter a message
3. Commit & push
4. Create a new PR using your branch and DONE
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012718faf012637de5</li>
        <li>Upwork Job ID: 1737561675116855296</li>
        <li>Last Price Increase: 2023-12-20</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 28067265</li>
<li>neonbhai | Contributor | 28067266</li>
</ul></li>
    </ul>
</details>

**Comment by maddylewis** [comment]
This is a simple change and should be treated as a bug report ($50 payment).

**Comment by maddylewis** [comment]
@neonbhai - yep! please note the price of the job ($50 vs. $500) -- https://github.com/Expensify/App/issues/33376#issuecomment-1865050026

**Comment by marcochavezf** [comment]
Hi @neonbhai, let us know when the PR is ready for review :)

**Comment by maddylewis** [comment]
https://github.com/Expensify/App/issues/33376#issuecomment-1872279131

it's expected they're different rn!

**Comment by mallenexpensify** [comment]
Contributor: @neonbhai paid $50 via Upwork
Contributor+: @ntdiary paid $50 via Upwork.
