### ISSUE TITLE
Feature Request / Polish : Show "member" in the place of "user" for system messages and remove the term for each user added to the workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33379]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703015541706559

## Action Performed:

1. Go to a workskpace
2. Add few members to the workspace
3. Open the #admin room
4. Observe the system messages

## Expected Result:
For all the rows it shows as "user"

## Actual Result:

- Only show "as a [user type]" appended at the end when:
     -  adding a non-normal user (eg, admin)
     - changing someone's user type
- In any other case, we wouldn't want to show "as a [user type]" at the end
- Also, we don't want to use the term "user" at all, it should be "member"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - (17) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/38435837/20e3cc9f-ec27-4a5c-a7ea-9c2a0a066013)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
Rephrasing a bit for clarify:

1. When adding users, we should only include the role for Admins or Auditors, but not basic members:
    - When adding a workspace member as a basic member: `added joe@expensivepie.com`
    - When adding a workspace member as an admin: `added joe@expensivepie.com as an admin`
    - When adding a workspace member as an auditor: `added joe@expensivepie.com as an auditor`
2. When changing someone's role, we should always include the old and new role, but should change `user` to `member`:
    - `updated the role of joe@expensivepie.com from member to admin`
    - `updated the role of joe@expensivepie.com from admin to member`

**Comment by slafortune** [comment]
resolved
