### ISSUE TITLE
[$500] New messages does not show up in the LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703005526338499

## Action Performed:

1. Send message to a user on desktop, ask them to reply
2. Select another chat in LHN
3. Check on another platform to confirm you received a message and check in the desktop

## Expected Result:
Message should appear in the LHN

## Actual Result:
Observe new message doesn't show in LHN on desktop.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (3)](https://github.com/Expensify/App/assets/38435837/7487cd82-79a8-44b8-be51-01e5d6f1eff7)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01382a2c2d0ea34088</li>
        <li>Upwork Job ID: 1737918570011721728</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@jjcoffee added `Internal` to get a C+ assigned for 👀, in case anyone is able to reliably reproduce. I just tried and was unable to for:
- Sent message from User B to User A and chat wasn't the one that was currently opened
- Sent message from User B to User A **when app was backgrounded** and chat wasn't the one that was currently opened
- Sent message from User B to User A when app was **closed** and chat wasn't the one that was currently opened (strangely, when app opened, it opened to the chat I was testing with).

**Comment by iwiznia** [comment]
Did an investigation on this [here](https://expensify.slack.com/archives/C03SDMF9YJ2/p1703867237806219) and am sending a server side PR to address at least part of this bug.
For context:
We set a max number of updates to return and never revised the number, so if you have more than 100, then it does not use the updates and instead reloads everything....
So there's really 2 bugs:
- We should increase this limit, maybe even remove it
- Shit is wrong when we do not use the reliable updates and reload from scratch

Going to fix 1, I will leave 2 to someone else :grimacing:
