### ISSUE TITLE
MEDIUM: Enable video playback from Concierge harpoons

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33385]
**Problem:**
Elsewhere we are working on adding the ability to upload and play videos inside arbitrary chats.  However, Concierge messages aren't sent in a normal fashion.

**Solution:**
Upgrade the harpoon system -- which is generated by code -- with the option to embed a short-form video that is playable both in chat, and *in the `UnreadMessageSummary` email* (via animated GIF).  This overlaps heavily with the project to allow users to upload and play videos, but is a little different as these messages are being sent via Harpoon (and thus, could cut some corners, such as by uploading the videos themselves manually via #infra or custom query).

**Comment by quinthar** [comment]
Demoting to Medium as we have quite a lot to do, and we don't *need* this for VSB release (though the sooner the better)

**Comment by francoisl** [comment]
Been working on wave issues, no update last month.

**Comment by francoisl** [comment]
Still focused on wave-collect issues.

**Comment by francoisl** [comment]
Focused on fast-apis and wave issues at the moment, going to put this back in the pool to avoid hogging it.
