### ISSUE TITLE
CRITICAL: [$500] `UnreadMessageSummary` shouldn't include the author's name in the message body if there is only one author

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33380]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703004970298819

## Action Performed:
1. Send a message from A to B
2. Wait for the email notification
3. Observe the email received

## Expected Result:
`UnreadMessageSummary` shouldn't include the author's name in the message body if there is only one author -- it should just have their name in From:.

## Actual Result:
It appears in the body of the message too.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (9)](https://github.com/Expensify/App/assets/38435837/02a54b92-8101-43f1-81e0-0aad452971a3)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147d93abcf546370c</li>
        <li>Upwork Job ID: 1737579940843003904</li>
        <li>Last Price Increase: 2023-12-27</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
Since it's about email notification it will be a BE issue, perhaps internal label should be added and an internal engineer can take a look at this.

**Comment by garrettmknight** [comment]
Updated to internal since this is is email/BE

**Comment by Gonals** [comment]
I'll get to this in a couple of days 😁

**Comment by quinthar** [comment]
Adding this to #vip-vsb, as it's going to interfere with our outreach

**Comment by Gonals** [comment]
Hopefully getting to this later today!

**Comment by Gonals** [comment]
Removing it from DMs for now, as it makes sense to me to keep it in rooms, but I can update in needed

**Comment by Gonals** [comment]
Aaaand from group chats as discussed [here](https://expensify.slack.com/archives/C0671JDRKQW/p1704178282336669)
