### ISSUE TITLE
MEDIUM: Create video promotion of report/expense chat

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33384]
**Problem:**
From the start OldDot has allowed you to comment on reports.  But most commenting is in reference to a particular expense.  For large reports, this can be confusing as it's unclear to which expense the comment is referring.

**Solution:**
Emphasize the benefit of contextual, expense-level chatting.  We are going to experiment with short videos from Concierge to explain this feature and advantage.

**Comment by quinthar** [comment]
Demoting to Medium as I don't think we *need* this until we do a general release, though obviously it's nice to have as early as possible.

**Comment by zsgreenwald** [comment]
On hold still

**Comment by zsgreenwald** [comment]
On hold still

**Comment by zsgreenwald** [comment]
Still on hold

**Comment by jamesdeanexpensify** [comment]
We have a few [GIFs](https://www.dropbox.com/home/Expensify/Design/Product%20GIFs/02_GIF) already that kind of beat around the bush of expense-level chatting in a contextual sense. I'm trying to think how we make another one that's unique and original. Would it essentially show a trail of a few different expenses in a workspace chat, then the admin clicks into one and asks for more details on what it was for (and the submitter replies back with some clarifying copy)?

**Comment by jamesdeanexpensify** [comment]
Let's see how things land at Xerocon, and maybe we can start adding more GIFs based on what resonated most with the audience. Even though it's mostly accountants, this will give us more direction on what excites people in general.

**Comment by jamesdeanexpensify** [comment]
maybe we can work expense-level commenting into our upcoming earnings CVP

**Comment by jamesdeanexpensify** [comment]
We're going to incorporate this idea into the NewDot explainer video project - I'll close this one out, but let me know if you want to keep it open for some other reason!
