### ISSUE TITLE
[$500] Remove Focus Outline for EngagementModal Backdrop

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#33389]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Pull this PR https://github.com/Expensify/App/pull/32154
2. Create a new account on web
3. See that the backdrop of the engagement modal has a blue border

## Expected Result:
- The backdrop should not be focused

## Actual Result:
- The modal is focused

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
Actual:
<img width="1730" alt="2023-12-20_09-16-50" src="https://github.com/Expensify/App/assets/42391420/76dcd029-87f4-4885-9175-54841a553a50">

Expected:
<img width="1727" alt="2023-12-20_09-16-50" src="https://github.com/Expensify/App/assets/42391420/052962f0-6382-437f-9239-b15b5f9f122e">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01882ae36fcc0be771</li>
        <li>Upwork Job ID: 1737625479257964544</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28066504</li>
<li>tienifr | Contributor | 28128940</li>
</ul></li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
This is an issue for a PR that has not been merged yet but I am currently stuck on. There is a minor visual bug that needs to be fixed, and the accepted proposal will be paid even though I will be the one implementing it. https://github.com/Expensify/App/pull/32154

**Comment by stitesExpensify** [comment]
@situchan is the C+ here, not the contributor

**Comment by situchan** [comment]
@tienifr thanks for the proposal. Can you please checkout [this branch](https://github.com/Expensify/App/pull/32154) and test your fix? Please share code diff so I can test as well

**Comment by stitesExpensify** [comment]
My apologies @abzokhattab here is the correct screenshot. It is a very small accessibility border

<img width="1730" alt="2023-12-20_09-16-50" src="https://github.com/Expensify/App/assets/42391420/565bda48-979f-472b-aa84-ebd1423fa790">

**Comment by stitesExpensify** [comment]
If we are going to make a custom backdrop (as opposed to a modal prop based solution), I think we should first look into how we currently do this for pages like "workspace settings" where we have a RHP with a backdrop that doesn't have this problem

**Comment by augustmuir** [comment]
Hi, I fixed the bug, see video for proof. Please accept my Upwork Proposal (August Kimacovich), and I will create a branch with the fix. Thanks!


https://github.com/Expensify/App/assets/72067396/a9b356e9-5e1b-411f-bb0c-0ed334fffa9f

**Comment by augustmuir** [comment]
Contributor details
Your Expensify account email: august.kimo@icloud.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b8790c09920fd2c7

**Comment by augustmuir** [comment]
@stitesExpensify @situchan Apologies for the bad PR - new here and thought I was in my own forked repo! 🙃

Anyways, see this commit for the fix: https://github.com/augustmuir/ExpensifyApp/commit/88c01af7b1cf7550532fb7c7f6fb00d9a55a9e38

Should be tested on iOS/Android as well to ensure the button is not visible.

Please accept my Upwork proposal as well, hope to start working on some of the issues here. Thanks!

**Comment by situchan** [comment]
> Why do we use a modal instead of a screen?

cc: @stitesExpensify 

I think it's because it's one time show only after sign up. There's no chance of showing that page again.
So it's just replacement for auto FAB display.

**Comment by stitesExpensify** [comment]
> > Why do we use a modal instead of a screen?
> 
> cc: @stitesExpensify
> 
> I think it's because it's one time show only after sign up. There's no chance of showing that page again. So it's just replacement for auto FAB display.

That is correct

**Comment by stitesExpensify** [comment]
@bernhardoj is it possible to prevent that behavior? I would prefer that solution if it is

**Comment by stitesExpensify** [comment]
In that case, I prefer @tienifr solution here since it is using an existing modal prop `customBackdrop`.

@augustmuir solution does appear to work, however creating an invisible button does not seem like the "correct" way to solve this problem.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by stitesExpensify** [comment]
@tienifr yes we're going to proceed with this solution. It will be paid out after the main PR has been merged. That being said, I believe that this is causing a typescript error, do you know why that may be? https://github.com/Expensify/App/actions/runs/7416782811/job/20182296471?pr=32154

**Comment by stitesExpensify** [comment]
@tienifr that failure is happening in the `overlay.tsx` file, and only occurs when this line is present https://github.com/Expensify/App/compare/stites-purposeForExpensify...tienifr:fix/33389?expand=1#diff-c5dd0a065b12f253786ab2916473640a80014957475696db4d97bedc23f47af2R206

**Comment by stitesExpensify** [comment]
This was the fix FYI https://github.com/Expensify/App/pull/32154/commits/4df4d3aaa85d864949854068fc3b63a92ddd4255

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by stitesExpensify** [comment]
The main PR has been merged here!

@bfitzexpensify can you please pay out @situchan and @tienifr ? What happened here is:
I was working on [this pr](https://github.com/Expensify/App/pull/32154) and needed help with a particular part of it. @tienifr came up with a solution that I used in that PR, and @situchan was the C+ that approved it, so we will pay them both out as if the PR was made separately from mine (AKA the normal way).

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Fourth week)

**Comment by situchan** [comment]
Seems like this is out of everyone's radar.
@stitesExpensify can you please remove `Monthly`, `Reviewing` and add `Daily`, `Awaiting Payment`?

**Comment by bfitzexpensify** [comment]
Thanks for the bump @situchan and sorry for the delay. Contracts have now been paid out.
