### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500] New Distance Requests Should Default to the "Default Distance Category"

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#33388]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** yuwen@expensify.com
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @yuwenmemon 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1702928915733459

## Action Performed:
Break down in numbered steps
1. In the OldDot policy editor, navigate to Workspace -> Expenses -> Distance
2. Set a Default Distance Category:
<img width="1018" alt="Screenshot 2023-12-20 at 3 56 53 PM" src="https://github.com/Expensify/App/assets/4741899/0d195b78-7c43-4e2c-bba3-dc72db324ac8">
<img width="990" alt="Screenshot 2023-12-20 at 3 59 55 PM" src="https://github.com/Expensify/App/assets/4741899/01703c95-21b9-4cfd-8458-bd6fcf7be26b">

1(a). Alternatively, if you done have access to your Workspace in OldDot, set a default category for the distance unit via JS on OldDot:
```js
const p = Policy.getByID('<workspace ID>');
p.policy.customUnits[0].defaultCategory = 'Advertising'; // check the index though
p.save();
```

3. As a submitter, Navigate to the Workspace Chat in NewDot
4. Create a new distance request without an explicit category. Follow the steps all the way until the confirmation step:
![Screenshot 2023-12-20 at 3 58 18 PM](https://github.com/Expensify/App/assets/4741899/baaef01f-2b7d-4411-94ba-9471c73ceb59)

## Expected Result:
The distance request should have the default category filled in by default

## Actual Result:
The category field is blank

## Workaround:
The default category will be set in the back end via https://github.com/Expensify/Auth/pull/9488, but we should still have this set for users in the front-end so the setting does not come as a suprise.

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/4741899/5b6ee5c7-bc6d-46b6-8ac4-2387765ccb95

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d091e9e76b7055e0</li>
        <li>Upwork Job ID: 1737625066164363264</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by peterdbarkerUK** [comment]
Not overdue, Yuwen was OoO for holidays

**Comment by yuwenmemon** [comment]
@tienifr's proposal looks good. @peterdbarkerUK can you resolve the issue above?

**Comment by situchan** [comment]
@dylanexpensify I asked question [here](https://github.com/Expensify/App/pull/34012#issuecomment-1914170085) before PR approval

**Comment by dylanexpensify** [comment]
resolved query, let's get this merged!

**Comment by strepanier03** [comment]
@situchan and @tienifr - I've sent you offers via Upwork, please accept when you can. 

@situchan - I know we're a few days off from pay being released but I'll work on the reg test, if applicable, as soon as you post. Feel free to @ mention me when you do!

Chat again in a few days 👋

**Comment by situchan** [comment]
This is new feature

Regression Test Proposal
1. In OD policy editor, go to Workspace >> Expenses >> Distance
2. Set a Default Distance Category
3. Navigate to the workspace chat in ND
4. Create a new distance request without an explicit category, follow the steps until the confirmation screen
5. Verify that the category field is set with the default category from step 2
