### ISSUE TITLE
[$500] Web - Sign in modal - Browser back button takes to previous modal while modal back button closes it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out from ND
2. Navigate to this url: https://staging.new.expensify.com/r/5408450846930023
3. Click on a random email from within the public room
4. Click on Message ...
5. Click on the back button on the sign-in-modal
6. Do step 3 - 4 again
7. Click on the browser back button
8. Compare the results

## Expected Result:
Clicking both the browser back button and clicking the modal back icon should have the same functionality. They both should take user back to previous modal

## Actual Result:
Browser back button takes user to the previous modal whereas the modal back button closes the modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9ca4c4bd-9241-4156-b9f4-6db90176656e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135197050c7e9cb4f</li>
        <li>Upwork Job ID: 1737855322627493888</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28076495</li>
<li>tienifr | Contributor | 28076496</li>
</ul></li>
    </ul>
</details>

**Comment by rajutkarsh07** [comment]
upwork id : https://www.upwork.com/freelancers/~01cfa49ce124da3919?s=1110580755107926016
email : utkarshraj1306@gmail.com

To solve this issue
in the 
```
App/src/pages/signin/SignInModal.js
```
![image](https://github.com/Expensify/App/assets/49344502/26876d0f-658d-4db4-baa4-44620d6ef6fe)
we have to change the function inside the onBackButtonPress event with a new function handleBack
```
 const handleBack = () => {
        navigate(-1); 
    };
 ```
 
 this is solve the issue

**Comment by rajutkarsh07** [comment]
Contributor details
Your Expensify account email: utkarshraj1306@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cfa49ce124da3919?s=1110580755107926016

To solve this issue
in the 
```
App/src/pages/signin/SignInModal.js
```
![image](https://github.com/Expensify/App/assets/49344502/26876d0f-658d-4db4-baa4-44620d6ef6fe)
we have to change the function inside the onBackButtonPress event with a new function handleBack
```
 const handleBack = () => {
        navigate(-1); 
    };
 ```
 
 this will solve the issue

**Comment by s77rt** [comment]
@bernhardoj Thanks for the proposal. Your RCA is correct and the solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/33417#issuecomment-1866475402)

**Comment by s77rt** [comment]
@rajutkarsh07 Thanks for your interest here. Proposals should follow the proposal templete. Please checkout the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).

**Comment by s77rt** [comment]
@tienifr Thanks for the proposal. Your RCA is correct and thanks for brining up the deeplink case. The suggested solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/33417#issuecomment-1866540075)

**Comment by s77rt** [comment]
Not overdue. Waiting for assignment

**Comment by s77rt** [comment]
Same ^

**Comment by s77rt** [comment]
Still waiting for assignment

**Comment by jasperhuangg** [comment]
Sorry for the delay on this, was OOO, let's move forward with @tienifr's proposal, it makes sense to me.

**Comment by s77rt** [comment]
Anyone seen Melvin lately? The PR was deployed to production long ago

**Comment by jasperhuangg** [comment]
There must have been a problem, good ping. @strepanier03 Can we retest to verify that this bug was solved and issue payment if it works?

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/29248
- The offending PR has been commented on: https://github.com/Expensify/App/pull/29248#discussion_r1477610913
- A discussion in #expensify-bugs has been started: I don't think this is needed. This type of bugs can be caught during testing
- Determine if we should create a regression test for this bug: No, the profile page got changed and this bug can no longer be tested

**Comment by strepanier03** [comment]
Was OoO yesterday but missed this because it's still set to monthly. Setting to Daily and will put it on the list to get through.

**Comment by jasperhuangg** [comment]
@strepanier03 friendly bump on this. It seems we still need to pay out the C+ and PR authors for their work on this issue?

@tienifr @s77rt can you confirm?

**Comment by s77rt** [comment]
Yes that's correct

**Comment by strepanier03** [comment]
Will handle this today, I've been out of office all week until now.

**Comment by strepanier03** [comment]
Payment for @tienifr and @s77rt have been completed.
