### ISSUE TITLE
[HOLD #33146] [$500] Workspace - Counter in WS invite member tab is white and hardly visible

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33422]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.14-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspace -> Open any WS -> Members -> Invite
4. Choose more than 8 users -> Next

## Expected Result:
The counter should be black for good visibility

## Actual Result:
Counter is white and hardly .visible
The same behavior with the counter in the group chat details page.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/2435c961-380d-4ad2-99f0-d118b511fbf6)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a90cec2c60d608fb</li>
        <li>Upwork Job ID: 1737862413264674816</li>
        <li>Last Price Increase: 2023-12-21</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Thanks @Krishna2323 , put on hold, removed `Help wanted` and making a `Weekly`

**Comment by mallenexpensify** [comment]
https://github.com/Expensify/App/issues/33146 is still open

**Comment by eVoloshchak** [comment]
This has been resolved
<img width="375" alt="image" src="https://github.com/Expensify/App/assets/9059945/fb0bd98a-91c7-4126-95d5-e9e32d49397b">

**Comment by mallenexpensify** [comment]
Looks like we're fixed! Thanks @eVoloshchak , closing
