### ISSUE TITLE
[$500] Web - Contact list - Scroll wheel slide does not work on contact list but works on chat switcher

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33424]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Click on search icon to open chat switcher
2. While on the contact list hold down the mouse scroll wheel button and slide through the contact list
3. Go back and click on FAB
4. Click on Request money > Enter an amount > Click next
5. While on the contact list hold down the mouse scroll wheel button and slide through the contact list
6. Compare the result of step 5 with step 2

## Expected Result:
Scroll wheel slide should work on both contact lists and on chat switcher

## Actual Result:
Scroll wheel slide does not work on contact list but works on chat switcher list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/dca63717-6807-4398-9a65-435a258d744e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2fb43a4d63fb946</li>
        <li>Upwork Job ID: 1737865619901796352</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by Santhosh-Sellavel** [comment]
Not overdue, waiting for proposals

**Comment by sakluger** [comment]
I don't actually understand the bug report and don't see any issues in the recorded video. I'm going to close the issue, if anyone disagrees and thinks this is something we should solve right now, please raise for discussion in #expensify-open-source in Slack. Thanks!
