### ISSUE TITLE
The report preview for a new request does not show buttons in the workspace chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33427]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703014349876169

## Action Performed:
1. Create a expense report in workspace chat and submit as account A
2. As a approver click on the report to preview the request

## Expected Result:
Expected to see "Approve" button

## Actual Result:
No "Approve" button is seen. When I click into the request, I see the option to approve. And then when I go back to the workspace chat the “approve” button is now there in the report preview. 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (13)](https://github.com/Expensify/App/assets/38435837/d9fa7a0c-e761-4ca3-bc55-d2952d8ac2de)

![image (12)](https://github.com/Expensify/App/assets/38435837/3e28a5f0-db35-4211-8322-09d78033f972)

![image (11)](https://github.com/Expensify/App/assets/38435837/1cf64d39-5fb3-4688-8a18-0f4314d363c0)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
Checking with issue reporter to make sure this is still happening. Lots of changes to Collect workspace money requests.

**Comment by anmurali** [comment]
Seems like this is fixed now. Not reproducible at least.
