### ISSUE TITLE
[$500] IOU - IOU preview remains on listing page for user A when user B deleted the IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33433]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be Signed In with account A on main testing device and account B on secondary device
1. Open app on main testing device
2. On secondary testing device make a three Money Request to account A
3. On main testing device navigate to the IOU details page
4. On secondary testing device delete the opened IOU in previous step
5. On main testing device navigate back on listing page

## Expected Result:
Delete IOU preview should not be displayed

## Actual Result:
Deleted IOU persist on listing page when it was deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/03d2cdd0-3b38-4464-9a5d-a9ad80013b2b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b39e7dab2e8599cb</li>
        <li>Upwork Job ID: 1737883798160662528</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by adriancova** [comment]
Hey guys, new contributor here so pardon in advance if I'm completely misunderstanding something.

But after taking a look it seems to me like this one needs some patch on your backend, the issue appears to be that the API.write('DeleteMoneyRequest') event is not emitting updates for the subscribed clients.

**Comment by adriancova** [comment]
Contributor details
Your Expensify account email: adriancova.95@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e1358031c30351d8

**Comment by NicMendonca** [comment]
> Precondition: user should be Signed In with account A on main testing device and account B on secondary device


I am going to close this. This doesn't seem like a real life user use case.
