### ISSUE TITLE
[Actionable System Messages] [$500] [MEDIUM] Workspace Chats: We’re doubling up on the “submitted” reportAction on the report

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33445]
**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1703187600061979?thread_ts=1703187017.215259&cid=C02MW39LT9N

## Action Performed:

Action steps:

Pre-testing requirement: Collect workspace type with the isPolicyExpenseChatEnabled NVP set ([SO](https://stackoverflowteams.com/c/expensify/questions/17518)).

1. Sign-in for the first time using the member account
• Verify that you land in the workspace chat
3. Go to global create (`+`) > Request money > enter an amount > confirm
4. Tap the report preview component to navigate to the expense report view
• Verify that a banner at the top of the page reads "Waiting for [Admin name] to Approve these expenses
• Verify that a note exists showing that the submitter has submitted the expenses "[Employee Name] submitted [Amount]
• Verify a "You submitted this report to [Admin Name][Admin email]" message at the bottom of the page

NOTE: If you change the Scheduled Submit Frequency the wording mentioned above does not fit. 

1. As the admin, go to OldDot and change the scheduled submit frequency to manually for a workspace
2. Log back into NewDot as the member (or refresh if you already are in another window)
• Verify that the LHN row for the workspace chat includes a GBR green dot for the draft report awaiting submission ✅
4. Tap the workspace chat row to navigate to the workspace chat view
• Verify that the draft report preview component appears in the workspace chat ✅
• Verify that the draft report preview component in the chat:
5. Includes a green Submit button ✅
6. Tap the report preview component of the second draft report to navigate to the expense report view
• Verify that a banner is in the page header with the label Next steps doesn't include a Submit button ❌
• Verify that the next steps text matches the manual submission cadence you set on the paid policy. E.g “Waiting for %displayName% to submit expenses.” ❌
• Verify that a green Submit button is in the page header beneath the “Next steps” banner ❌

## Expected Result:

- We’re doubling up on the “submitted” reportAction on the report - we don't need both notifications that the expense is submitted

## Actual Result:

- multiple indications that a report has been submitted 

## Screenshots/Videos

<img width="897" alt="image" src="https://github.com/Expensify/App/assets/51066321/ee58aaea-a38c-4b61-907f-6e63bde684a3">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cc @cristipaval @garrettmknight 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be4453255ad088f0</li>
        <li>Upwork Job ID: 1742263089109061632</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by rojiphil** [comment]
@fedirjh 
This looks like a BE issue as `submit` can happen from ND or OD. 
I think BE should merge and send a single consolidated `SUBMITTED` action which can be used for display in FE.

**Comment by rojiphil** [comment]
> This looks like a BE issue as `submit` can happen from ND or OD. I think BE should merge and send a single consolidated `SUBMITTED` action which can be used for display in FE.

@mountiny 
What's your take on this issue vis-a-vis the more general optimistic next steps #28771 issue?

**Comment by JmillsExpensify** [comment]
@muttmuure Can we get someone internal to look at this? We've since discovered that it's happening for other actions as well, like payment, so not just submit.

**Comment by youssef-lr** [comment]
No update yet, planning to work on this this week.

**Comment by youssef-lr** [comment]
No update yet.

**Comment by youssef-lr** [comment]
I have a solution ready for the `submitted` action, it turned out the optimistic reportActionID was not being received in the backend which creates one optimistic (stale) action, and a backend action. Fixing this made it that only one action was created, but still displays OldDot's message. I can include a fix for other IOU actions as well that may be displaying OldDot's message. @JmillsExpensify can you let me know please what other actions should the fix be applied to?

**Comment by youssef-lr** [comment]
It seems like this is occurring for the `MARKREIMBURSED` OldDot action as well. I believe that's it? Anyway I'll take into account these two actions for now, if others show up I can apply the fix to them as well.

<img width="492" alt="Screenshot 2024-01-16 at 22 42 21" src="https://github.com/Expensify/App/assets/9680864/8f294eb9-2010-494d-857a-e73acea149d4">

**Comment by youssef-lr** [comment]
This specific issue is fixed, working next on the rest of the report actions affected by this.

**Comment by muttmuure** [comment]
Still being worked on

**Comment by youssef-lr** [comment]
Yeah this issue is fixed, we are not duplicating the submitted message anymore. But there's another issue in the works to solve this holistically for all report actions that are either duplicated, or not displayed at all as they've been supported in OldDot only in the past. I think any issue dealing with this should be put on hold for https://github.com/Expensify/Expensify/issues/347391.

**Comment by youssef-lr** [comment]
Another option is to fix this now for all of the report actions that are supported in both OldDot and NewDot. For example these actions can be fixed now:

* `You submitted this report to <email>` => `submitted <amount>`
* `You marked this report as manually reimbursed`, hide it if duplicated: this is when the report is paid from NewDot. When the report is paid from OldDot it won't be duplicated, but instead we should display its NewDot equivalent which is `Paid elsewhere`.

**Comment by muttmuure** [comment]
Asked about this here: https://expensify.slack.com/archives/C036QM0SLJK/p1707488993291819

**Comment by muttmuure** [comment]
Looks like this is going to be part of the Actionable System Messages project

**Comment by muttmuure** [comment]
Gonna slap weekly on it and keep an eye out on that one

**Comment by youssef-lr** [comment]
Same.

**Comment by trjExpensify** [comment]
Does this need a hold in the title as well, @twisterdotcom?

**Comment by twisterdotcom** [comment]
@youssef-lr - for these duplicated actions, are they actually both [`SUBMITTED`](https://github.com/Expensify/App/blob/98129e60c5268e0a53e0a9937d48e93e416af238/src/CONST.ts#L591) reportActions? And we're just rendering them both because we have some logic in ReportActionItem.js that happens to render them both?

Or are they actually separate reportActions?

Same question for `You marked this report as manually reimbursed` as you stated here: https://github.com/Expensify/App/issues/33445#issuecomment-1922278474

**Comment by muttmuure** [comment]
Not overdue

**Comment by twisterdotcom** [comment]
>the other one is related to NewDot which we add we never pay any report whether it's ACH or paid elsewhere, which is: ACTION_IOU_TYPE_PAY

Getting away from this issue which I guess we can close now then, but... what does this mean sorry? We have a single action which is used for any type of payment in newDot? I'm not sure we should have that, because in oldDot we have many different actions which display a different message based on the type of payment it was:

```
MARKEDREIMBURSED
MARKREIMBURSEDFROMINTEGRATION
PAYPALREIMBURSED
REIMBURSED
REIMBURSEMENTACHBOUNCE
REIMBURSEMENTACHCANCELLED
REIMBURSEMENTACCOUNTCHANGED
REIMBURSEMENTDELAYED
REIMBURSEMENTQUEUED
REIMBURSEMENTDEQUEUED
REIMBURSEMENTREQUESTED
REIMBURSEMENTSETUP
```

**Comment by muttmuure** [comment]
cc @dylanexpensify

**Comment by dylanexpensify** [comment]
TY for the flag @muttmuure!

**Comment by twisterdotcom** [comment]
@youssef-lr still intrigued for your take on IOU_TYPE_PAY vs all of the reimbursement actions above.

I do think we can close now though right, given this is fixed?

**Comment by youssef-lr** [comment]
>I do think we can close now though right, given this is fixed?
Yeah I think we can close this.

>still intrigued for your take on IOU_TYPE_PAY vs all of the reimbursement actions above.

I'm not totally sure but it seems like it is a duplicate action we might be able to remove..cc @mountiny do you think we really need the IOU action of type PAY? I believe it was first created to only handle P2P payments when we first implemented them.

**Comment by mountiny** [comment]
That PAY action is used in the [Send money](https://github.com/Expensify/Auth/blob/6bf3a1eb38ddb6936e5a5df122002259fe7fdbf7/auth/command/SendMoney.cpp#L171-L176) from where there is no other action for the money request so we cannot simply remove this.

For paying the expense report, I can see that this created some duplication, but the marked as reimbursed actio now does nto have the amount and currency in its message I believe, but [Pay action does](https://github.com/Expensify/Auth/blob/6bf3a1eb38ddb6936e5a5df122002259fe7fdbf7/auth/command/PayMoneyRequest.cpp#L379-L380) so for NewDot, if we would want to remove it, its something we need to keep in mind.

In general, I think the Send Money flow keeps need for this action.
