### ISSUE TITLE
[$500] [Wave 6: Workspace Chat] Scheduled Submit set to Manually creates blank report header

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33447]
**Slack conversation:** https://expensify.slack.com/archives/C02MW39LT9N/p1703188880908729?thread_ts=1703187017.215259&cid=C02MW39LT9N

## Action Performed:

Pre-testing requirement: Collect workspace type with the isPolicyExpenseChatEnabled NVP set ([SO](https://stackoverflowteams.com/c/expensify/questions/17518)).

1. As the admin, go to OldDot and change the scheduled submit frequency to `manually` for a workspace
2. Make sure the workspace has at least two members (who's NewDot accounts you'll use)
3. Log back into NewDot as the Member (or refresh if you already are in another window)
4. Create a Request Money to Admin
5. As the Admin > Verify that the LHN row for the workspace chat includes a GBR green dot for the draft report awaiting submission :white_check_mark:
5. As the Member > Tap the workspace chat row to navigate to the workspace chat view
• Verify that the draft report preview component appears in the workspace chat  :white_check_mark:
• Verify that the draft report preview component in the chat:
• Verify the IOU includes a green `Submit` button :white_check_mark:
7. Tap the report preview component of the second `draft` report to navigate to the expense report view
• Verify that a banner is in the page header with the label `Next steps` :x:
• Verify that the next steps text matches the manual submission cadence you set on the paid policy. E.g “Waiting for %displayName% to submit expenses.” :x:
• Verify that a green `Submit` button is in the page header beneath the “Next steps” banner :x:

NOTE: This does eventually update - it's just not immediate 

<img width="903" alt="image" src="https://github.com/Expensify/App/assets/51066321/b5c3e3b4-7118-4e28-b0d0-8d9ca2b4354e">

## Expected Result:

Next Steps should reflect the Manually frequency "waiting for [employee] to submit expenses" 
There should be a Submit button

## Actual Result:

The "next steps" wording doesn't reflect a Manually frequency
There's no Submit button

## Screenshots/Videos

https://github.com/Expensify/App/assets/51066321/376df7e9-6074-4a0b-b749-db8718b5218d

<img width="1388" alt="image" src="https://github.com/Expensify/App/assets/51066321/ed96483f-30cf-444a-a4e7-bee5b3a502ad"></details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c51092024bd72e04</li>
        <li>Upwork Job ID: 1742346576004784128</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I can reproduce this - the issue is that the settings on the Request Money Draft do not match the "Manual" frequency, they still match the "weekly" frequency.

<img width="1388" alt="image" src="https://github.com/Expensify/App/assets/51066321/e4410961-c643-4d76-a4ee-b286e61012ef">

 I think this might need to be internal  and I think this probably should be a high priority - waiting for a buddy check from @greg-schroeder

**Comment by Christinadobrzyn** [comment]
sorry I was ooo - I think this can be external

**Comment by rojiphil** [comment]
> the issue is that the settings on the Request Money Draft do not match the "Manual" frequency, they still match the "weekly" frequency.

@Christinadobrzyn @fedirjh 
I just checked with `Manual` frequency and the message in OD still shows the `Weekly` message (notice attached screenshot) 
I think this needs to be addressed in BE. And, if there is any follow-up work required in FE, we can do it.
Alternatively, if BE sends the `Scheduled Submit` setting to FE, we can do this in FE too. 

![Screenshot 2024-01-03 at 1 32 31 PM](https://github.com/Expensify/App/assets/3004659/0da3afbb-3d50-4d58-acb0-44e0f63bc670)

![Screenshot 2024-01-03 at 1 40 06 PM](https://github.com/Expensify/App/assets/3004659/bf2f19fb-f2e3-4fa3-ba72-5dbc1186d3ac)

**Comment by Christinadobrzyn** [comment]
okay! let's add an `Internal` label and get engineering to review this

**Comment by mountiny** [comment]
I am going to close this one in favour of more general optimistic next steps https://github.com/Expensify/App/issues/28771 issue
