### ISSUE TITLE
Web - Connect bank - Bank account error doesn't clear up dynamically after validating email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33456]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to OldDot (expensify.com) and sign-up for a new account (don't validate it yet)
2. Navigate to Settings > Policies > New Policy > Select Free
3. After being redirected to NewDot > Workspace settings click on Connect Bank Account page
4. Notice the error message stating that you can't add a bank account with an unvalidated Expensify account
5. Go to OD and click the on setting > Account > Validate email
6. Validate the Expensify account with a magic code
7. Navigate back to the Connect Bank Account page on ND
8. Notice the error message

## Expected Result:
The error message should clear up dynamically as soon as the email gets validated

## Actual Result:
The error message doesn't clear up dynamically and when the user manually reloads the page user gets logged out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fd0d9df4-92ff-4968-a936-5d1ee0d84507

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb9db52d854ac552</li>
        <li>Upwork Job ID: 1737942809744629760</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
Waiting for proposals

**Comment by laurenreidexpensify** [comment]
@Expensify/applauseleads pls confirm still reproducible in KI testing thanks

**Comment by laurenreidexpensify** [comment]
Waiting for confirmation this is still reproducible / and for proposals

**Comment by Tony-MK** [comment]
Hey everyone, I have some questions about **unvalidated email addresses**.

a) How can I create unvalidated email addresses? 
b) Do all new accounts send a magic code to the respective email addresses before entering the app, even for the first time? 
c) If question b is false, which type of email addresses are exempted from being validated?

**Note:** I can create unvalidated phone numbers, but connecting to a bank requires an email.

Thank you

**Comment by Tony-MK** [comment]
Seems like a backend error because it returns the response below. Furthermore, once the email address is validated the session becomes invalid.
![Screenshot 2024-01-08 at 11 06 33](https://github.com/Expensify/App/assets/22982173/1e72f076-a48c-4fda-94da-b3d8bd3ac50f)

**Comment by laurenreidexpensify** [comment]
@Tony-MK can you confirm you could reproduce earlier?

**Comment by Tony-MK** [comment]
Yeah @laurenreidexpensify , I was able to reproduce the bug.

**Comment by laurenreidexpensify** [comment]
@sobitneupane can you confirm if this one is BE?

**Comment by sobitneupane** [comment]
@laurenreidexpensify It might be an expected behavior to logout the user after validating the email. I do believe this should be handled internally.

**Comment by laurenreidexpensify** [comment]
Adjusting to internal

**Comment by laurenreidexpensify** [comment]
Waiting for internal engineer to pick up
