### ISSUE TITLE
[$500]  Avatar - Primary and secondary contacts use the same profile Avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
1. User B is secondary contact method to User A
2. Both users have default profile Avatars
Steps:
1. Navigate to staging.new.expensify.com
2. Login as User B
3. Navigate to Settings> Profile> Upload custom photo
4. Navigate to Settings> Profile> Contact Method
5. Set User B as default contact method
6. Change between contact method users and take a note of Avatar

## Expected Result:
Profile Avatar photo should not be the same for both users

## Actual Result:
Both Users (Primary contact and secondary contact) have the same profile Avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8e5786c5-69e5-4762-866a-90e2dfa477eb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188df459b3d097847</li>
        <li>Upwork Job ID: 1737943403119042560</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by Upendrasengar** [comment]
> this doesn't look like a bug, do we consider 2 seperate contact method as 2 seperate accounts? if yes, it'll be weird to receive message sent to primary contact method while secondary contact method is default 😅

Agree, not sure if it's posted on Upwork by a bot Or if they really want someone to fix it.

**Comment by Upendrasengar** [comment]
Contributor details
Your Expensify account email: upendrasengar456@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01877ad79621257dfe

**Comment by Upendrasengar** [comment]
I'm available to work on this.

**Comment by strepanier03** [comment]
I've been OoO, reviewing this now.

**Comment by strepanier03** [comment]
Hmm, I agree this isn't a bug and am in favor of closing this.
