### ISSUE TITLE
[$500] Android - Notifications - Notifications not cleared after opening chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33254
## Action Performed:
1. Open the app and log in
2. Allow notifications
3. Open the concierge chat
4. Send 3 messages to the user logged into the main device
6. Open the chat
7. Background the app
8. Send 3 messages to the user logged into the main device
9. Open the app

## Expected Result:
The notifications are cleared every time the user opens the chat (step 6 and 9)

## Actual Result:
The notifications are not cleared even though messages are read

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/29906683-e534-4b54-ab02-bebe5ff3291d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc6f6adb93b4c53b</li>
        <li>Upwork Job ID: 1737941956691775488</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by LekeMarkaj** [comment]
If the issue is specific to a particular app, clearing its cache may help. Go to your device settings, find the app in question, and clear its cache.
Occasionally, glitches or bugs in the operating system or specific applications can cause delays in processing notifications. Updating your apps and operating system to the latest versions may help resolve such issues.
Ensure that your operating system and all relevant apps are up to date. Developers regularly release updates to fix bugs and improve performance.

**Comment by sobitneupane** [comment]
@kevinksullivan Is this still reproducible? I don't have android device with me now, so I won't be able to test it.

**Comment by kevinksullivan** [comment]
@lanitochka17 are you able to reproduce this?

**Comment by kevinksullivan** [comment]
Hm @sobitneupane catching up here. Should this be marked internal?

**Comment by sobitneupane** [comment]
@kevinksullivan I could not reproduce the issue. I tested it on IOS 17.

**Comment by kevinksullivan** [comment]
Alright, going to close out then.
