### ISSUE TITLE
[Awaiting Test from Applause] [$500] Android - Compose-In edit comment mode, compose box is shown after tapping header and returning back.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Long press any sent message and select edit comment
4. Note, compose box is not visible
5. Tap header
6. Tap back
7. Note compose box is visible
8. Send a message

## Expected Result:
When user in edit comment mode, compose box should not be shown after tapping header and returning back

## Actual Result:
When user in edit comment mode, compose box shown after tapping header and returning back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e0bf3a42-f724-4c3f-8971-39d264beffc8

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019035bbdbdc062b24</li>
        <li>Upwork Job ID: 1737949296231571456</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28094075</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by ikevin127** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue

When user in edit comment mode, the main composer is shown after tapping header and returning back.

## What is the root cause of that problem?

This happens because there's no logic that re-focuses the edit composer input when returning from a different screen. 

When we go to a different screen while the edit composer is focused, the edit composer loses focus which causes the main composer to be rendered. As soon as we manually focus the edit composer, the main composer will be hidden.

## What changes do you think we should make in order to solve the problem?

We should add logic that re-focuses the edit composer input when returning back from another screen while the edit composer is opened (we're in edit mode).

**Comment by allroundexperts** [comment]
Taking over!

**Comment by allroundexperts** [comment]
Hi @tienifr!

> Focusing on the edit composer whenever users back to report screen doesn't make sense if this composer is not focused before

Can you show me a video of this happening?

**Comment by garrettmknight** [comment]
Updating C+

**Comment by garrettmknight** [comment]
@allroundexperts thoughts on video?

**Comment by garrettmknight** [comment]
@allroundexperts can you give this one an update when you get a chance?

**Comment by garrettmknight** [comment]
Bumped in slack.

**Comment by allroundexperts** [comment]
I think having multiple messages in edit state is wrong. For example, in Slack, we can only have a single message in edit state at a time. Reference video:

https://github.com/Expensify/App/assets/30054992/26f54a8c-763b-40ab-8049-138450bd6c22

Given this, @ikevin127's [proposal](https://github.com/Expensify/App/issues/33466#issuecomment-1867013648) looks simple and effective.

However, if having multiple messages in edit state is fine, then @tienifr's [proposal](https://github.com/Expensify/App/issues/33466#issuecomment-1867223195) should be the way to go. 

🎀 👀 🎀 C+ reviewed

**Comment by MonilBhavsar** [comment]
Allowing users to edit multiple messages at once is by design and a feature
Internal thread for reference https://expensify.slack.com/archives/C03U7DCU4/p1702412172994099

**Comment by garrettmknight** [comment]
@allroundexperts with that in mind, can you update your review?

**Comment by allroundexperts** [comment]
Given this, I think @tienifr's [proposal](https://github.com/Expensify/App/issues/33466#issuecomment-1867223195) would work just fine.

**Comment by MonilBhavsar** [comment]
Thanks! Looks good to me. A new hook would be better

**Comment by garrettmknight** [comment]
Working through some questions in the PR.

**Comment by garrettmknight** [comment]
Just seeing this - great question @parasharrajat. I think this is ultimately about consistency since there isn't a super clear winner. Can you point me to the old regression steps for this one?

**Comment by garrettmknight** [comment]
I'll pay out in the meantime since the work was done as we asked.

**Comment by garrettmknight** [comment]
Summary of payments for this issue:
- Contributor: @tienifr $500 paid via Upwork
- Reviewer: @allroundexperts $500

**Comment by garrettmknight** [comment]
Dropping to weekly while we figure it out and @allroundexperts submits for payment

**Comment by MonilBhavsar** [comment]
Looks like we're still waiting on QA steps here @parasharrajat ?

**Comment by MonilBhavsar** [comment]
I checked Testrail but couldn't find exact steps for related `Composer` test. @lanitochka17 can you please link to the regression test suite if this issue is coming from regression run. thank you!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on [this summary](https://github.com/Expensify/App/issues/33466#issuecomment-1932923110).

**Comment by garrettmknight** [comment]
@lanitochka17 I know it's been a while since we opened this one up, but could you point us to the test that triggered this one if you can find it? Thanks!

**Comment by lanitochka17** [comment]
The issue was found while checking this test case https://expensify.testrail.io/index.php?/tests/view/4074970

**Comment by garrettmknight** [comment]
Cool, I think this once is covered in the existing test case.
