### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Web - IOU & Task - User is redirected to previous page when double clicking outside RHP editor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33460]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to request details view of IOU/task report
2. Click on any field to open RHP
3. Double click outside RHP

## Expected Result:
User stays on the same page

## Actual Result:
User is returned to previous page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f3b17a68-aa2b-4920-b5d4-5aa8f3076c91

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b870d525be430c1d</li>
        <li>Upwork Job ID: 1737945433358630912</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28070388</li>
</ul></li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
@thesahindia plz review the proposals above.

**Comment by blimpich** [comment]
Sounds good! @tienifr you are assigned, please feel free to create a PR for us to review 🙂

**Comment by mallenexpensify** [comment]
@thesahindia can you please provide details on why @tienifr 's proposal was selected above others that were posted before? Thx
@blimpich can you please [review the PR](https://github.com/Expensify/App/pull/33640)?

**Comment by mallenexpensify** [comment]
@thesahindia can you please address my question above?
https://github.com/Expensify/App/issues/33460#issuecomment-1874734025

@thesahindia can you also plz complete the regression test steps?

Contributor: @tienifr paid $500 via Upwork
Contributor+: @thesahindia owed $500 via NewDot

**Comment by mallenexpensify** [comment]
Thanks @thesahindia !

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
