### ISSUE TITLE
[$500] Preferences - Language does not change on secondary device logged in with the same user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33462]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify with any account on main Web device
2. Log in to New Expensify with the same account on secondary mWeb device
3. Main device - navigate to Settings > Preferences > Language and change language
4. Verify the language change occurs on the secondary device logged in to the same account

## Expected Result:
Language should be changed on all devices logged in with the same account

## Actual Result:
Language does not change on secondary device

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6fa70fd8-3018-4119-be01-c29672cd0509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161e3f7a3873ccd31</li>
        <li>Upwork Job ID: 1737947013405110272</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by burczu** [comment]
@ZhenjaHorbach I don't think it's the best solution here - as far as I know it was never done this way before. I think adding `PreferredLanguageProvider` to the `ComposeProviders` may result in degraded performance (re-rendering all the components every time we change the language - right now we re-render only those that use translations).

I'm sure this functionality was working correct before, so I think we should focus on finding why it does not work anymore (perhaps some regression?) and fix it.

Let's wait for more proposals here.

**Comment by burczu** [comment]
Hey @adelekennedy! I'll be OOO till January 6th, and right after that I'm leaving the C+ role and joining Waves. Could you assign another C+ engineer to handle this issue from now on? Thanks.

**Comment by situchan** [comment]
I can take over.
However, I think this was temporary BE pusher issue. Not able to reproduce anymore

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment]
not able to reproduce, I think this was fixed elsewhere!
