### ISSUE TITLE
[$500] Threads - Pinned thread is unpinned when leaving the thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33486]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to any thread and join it if not joined yet.
2. Pin the thread.
3. Click three-dot menu > Leave.

## Expected Result:
The pinned thread will remain pinned when leaving the thread.

## Actual Result:
The pinned thread is unpinned when leaving the thread.

Since opening the thread itself does not qualify as "joining the thread", the pinned thread should remain pinned after leaving the thread as it will not affect the join status of the thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3d8b899f-dee0-4b89-9984-ffed1c787c23

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018bad758ad443c76b</li>
        <li>Upwork Job ID: 1738134034842296320</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment]
This is BE, we have no control over this on the FE side

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[$500] Threads - Pinned thread is unpinned when leaving the thread 
### What is the root cause of that problem?
We  reset all object after leaving rom. 
### What changes do you think we should make in order to solve the problem?
We should save keys that don't want to be reset. in this case `isPinned`
### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment]
I don't think this is a bug. It makes sense to me that if you leave a thread it would no longer be pinned. @izarutskaya did these test steps come from a regression test? If so, let's update it.
