### ISSUE TITLE
[$500] IOU - A "-" sign appears in front of the currency in the Distance IOU preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open New Expensify app
2. Log into the HT account
3. Create a WS if you don't already have one.
4. Send a distanсe IOU(with any correct data) to WS
5. Navigate to Report Conversation
6. If the problem does not occur the first time, repeat step №4 several times.

## Expected Result:
No unnecessary characters should appear in the preview of the distance IOU

## Actual Result:
When creating a Remote IOU, before the map is loaded in the preview, a "-" appears in front of the currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/abb59d20-62ef-45d9-b930-ac8820811422

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f65c5024fc15f72</li>
        <li>Upwork Job ID: 1738136877882548224</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by anmurali** [comment]
Closed, cannot reproduce
