### ISSUE TITLE
[$500] Web - Tag - New tag added by Admin is not dynamically displayed on Employee's tag list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
User is an employee of a Collect workspace on OD
1. Navigate to new dot as employee
2. Go to Workspace chat> Start creating IOU> Open tag dropdown
3. Navigate to other browser as Admin on Old Dot
4. Add new tag with custom name

## Expected Result:
Employee should see the added tag in real time

## Actual Result:
New tag added by Admin is not dynamically displayed on Employee's tag list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a3418e22-e975-4945-8f54-834d0356f33e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019cf280780f8678da</li>
        <li>Upwork Job ID: 1738204086232539136</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by carlitose** [comment]
Bug Resolution Proposal:

**Title:** Dynamic Update of Tag List After Admin Adds New Tag

**Description:**
Although I have not directly contributed to Expensify's codebase, my decade-long experience with React applications equips me to propose a generic solution to the described issue. This solution is based on the fundamental principles of React and dynamic web application state management.

**Proposed Steps:**

1. **Data Flow Verification:** Ensure that the new tag added by the Admin is correctly sent to the server and that the server sends back an appropriate response.

2. **State Update:** Use React's state management (via `useState` or Redux if utilized) to track the tag list.

3. **WebSocket or Polling:** Implement a WebSocket system for real-time updates or, as a less efficient alternative, use periodic polling to check for new tags.

4. **Side Effects Management:** Use `useEffect` or Redux middleware to listen for changes and update the tag list state when a new tag is added.

5. **Performance Optimization:** Ensure that the state update does not cause unnecessary re-renders in other parts of the application.

6. **Testing:** Thoroughly test the solution to ensure it works as expected across various scenarios and with different data volumes.

**Conclusion:**
I am excited about the prospect of contributing to Expensify and confident that my experience with React will be valuable in resolving this and future bugs.

Expensify account email: carlog.sergi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b0d12422bbdbf2d3

**Comment by isabelastisser** [comment]
@Ollyws, can you please review the proposal above? Thanks!

**Comment by isabelastisser** [comment]
@Ollyws please provide an update, thanks!

**Comment by isabelastisser** [comment]
Bump @Ollyws

**Comment by isabelastisser** [comment]
@Ollyws, please provide an update on this issue. If you can't review this issue in a timely manner, please let me know, and I will reassign the issue. Thanks!

**Comment by isabelastisser** [comment]
Hey @carlitose, can you please provide an update? Thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment]
@carlitose @mvtglobally what are the next steps here?

**Comment by isabelastisser** [comment]
Thanks @Ollyws!

**Comment by isabelastisser** [comment]
Hey @Ollyws! Is this still not reproducible?

**Comment by isabelastisser** [comment]
Thanks @Ollyws! Closing.
