### ISSUE TITLE
[HOLD for payment 2024-01-26] [HOLD for payment 2024-01-25] Cancel payment - IOU is still marked as paid when payment is canceled unless report is revisited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33509]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32674
## Action Performed:
1. [User A] Request money from User B
2. [User B] Click on IOU preview > Pay elsewhere
3. [User B] Click 3-dot menu > Cancel payment > Cancel payment

## Expected Result:
On User A's end, the IOU preview will no longer be marked as paid when the payment is cancelled

## Actual Result:
On User A's end, the IOU preview is still marked as paid unless the IOU report is revisited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/223b5330-0e62-43dd-8083-5be7ff01f18b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We do not update the `iouReport.isCancelledIOU: true` optimistically when canceling the payment.

### What changes do you think we should make in order to solve the problem?
When canceling the payment, we should optimistically set `iouReport.isCancelledIOU: true`.

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
Reverting the original PR because it has caused numerous deploy blockers and the author is ooo

**Comment by mountiny** [comment]
PR reverted, Assigning @Gonals so you can track this issue and fix it in next iteration

**Comment by Gonals** [comment]
Setting it as monthly, as this is no longer happening (but I want it to keep track)
