### ISSUE TITLE
[HOLD for payment 2024-02-01] MEDIUM: Notification counter has phantom unreads

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703179378879089

## Action Performed:
1. View the thread of a public room created on a private workspace

## Expected Result:
Just looking at a thread shouldn't join it (you need to explicitly join a thread and subscribe to it), and thus shouldn't generate notifications.

## Actual Result:
I think the actions here are that I viewed a thread, but didn't participate in it. As such, whenever that thread got a new message, my notification count went up but I had no unread messages in my LHN.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/15f615e9-c7f7-4228-97b0-5fc872a49121

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197ab62db4a5e9ffd</li>
        <li>Upwork Job ID: 1738248320594354176</li>
        <li>Last Price Increase: 2023-12-29</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Contributor | 28080118</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
Was OoO for the holidays — sorry for the delay here!

@0xmiroslav any thoughts on the proposals above? Thanks!

**Comment by cubuspl42** [comment]
This is indeed a regression; sorry for that.

@allroundexperts said a few days ago that he was working on a PR. Christmas break might've introduced a slight delay, but hopefully the fix will be under review very soon.

**Comment by allroundexperts** [comment]
PR created https://github.com/Expensify/App/pull/34025

**Comment by puneetlath** [comment]
Once that PR is done, I'd love to hear what ideas there are to make sure this regression doesn't happen again. I feel like this issue keeps cropping up over and over. At the minimum, let's make sure we have some good manual regression tests in place. But maybe we could add some automated tests or something too?

**Comment by marcaaron** [comment]
Agree. If we go the automated route... we should be able to do something like this:

```diff
diff --git a/src/libs/UnreadIndicatorUpdater/index.ts b/src/libs/UnreadIndicatorUpdater/index.ts
index 4126f2af4e..9c7fffd52a 100644
--- a/src/libs/UnreadIndicatorUpdater/index.ts
+++ b/src/libs/UnreadIndicatorUpdater/index.ts
@@ -8,13 +8,17 @@ import updateUnread from './updateUnread';

 let allReports: OnyxCollection<Report> = {};

+function getUnreadActionsForUnreadIndicator(currentReportID) {
+    return Object.values(allReports ?? {}).filter(
+        (report) => ReportUtils.isUnread(report) && ReportUtils.shouldReportBeInOptionList(report, currentReportID ?? '', false, [], {}),
+    )
+}
+
 const triggerUnreadUpdate = () => {
     const currentReportID = navigationRef.isReady() ? Navigation.getTopmostReportId() : '';

     // We want to keep notification count consistent with what can be accessed from the LHN list
-    const unreadReports = Object.values(allReports ?? {}).filter(
-        (report) => ReportUtils.isUnread(report) && ReportUtils.shouldReportBeInOptionList(report, currentReportID ?? '', false, [], {}),
-    );
+    const unreadReports = getUnreadActionsForUnreadIndicator(currentReportID);
     updateUnread(unreadReports.length);
 };
```
(obviously do not use the broken logic that is there 😄)

But we can export the `getUnreadActionsForUnreadIndicator()` and then add a unit test for the various cases.

**Comment by puneetlath** [comment]
I love that. @cubuspl42 @allroundexperts what do you think? Shall we include it in the PR? Or perhaps do it as a follow-up?

**Comment by cubuspl42** [comment]
If we're gonna add this, maybe it's easier to include this in the already open PR.

What could also help would be [adding some comment here](https://github.com/Expensify/App/blob/85fee5aeb683729aac48300c71da932a8049b83f/src/CONST.ts#L655), as this is quite a special value with special meaning (unlike the other options which directly corresponds to actual user-picked preference).

**Comment by quinthar** [comment]
Hi!  What's the status of this?  What's the next step, who is doing it, and when will it happen?

**Comment by cubuspl42** [comment]
This time it's on me! The latest comments were resolved before the weekend. I'll do the final testing, and very likely, this will be mergeable today.

**Comment by CortneyOfstad** [comment]
Thanks @cubuspl42!

**Comment by CortneyOfstad** [comment]
Payment is not due until tomorrow 👍

**Comment by situchan** [comment]
I think this can be closed based on https://github.com/Expensify/App/issues/33506#issuecomment-1876203136

**Comment by CortneyOfstad** [comment]
@Gonals does that sound good ^^^?

**Comment by Gonals** [comment]
Yep!
