### ISSUE TITLE
[$500] mWeb - IOU - "1 in scanning" message still shows after a failed scan

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33504]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Navigate to a workspace chat where an IOU was sent already
3. Start making a "Scan" IOU that'll fail
4. Wait for the scan to fail
5. Navigate back to the workspace chat

## Expected Result:
The message should disappear

## Actual Result:
"1 in scanning" message still shows after a failed scan

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/f6586b2f-27d1-4b9c-9c7f-022c298583f8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151e2987d6b5ce23e</li>
        <li>Upwork Job ID: 1748390765087760384</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by kevinksullivan** [comment]
My bad missed this one @fedirjh
