### ISSUE TITLE
[HOLD for payment 2024-01-05] [$500] Android - Request money - Suggested destination displayed instead of new one if entered offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Create a distance expense on the workspace if there are not any
3. Navigate to the workspace chat
4. Disable internet connection
5. Tap "+" > Request money > Distance
6. Select a start waypoint from suggestions
7. Tap the "Start" and enter a new one
8. Repeat steps 6-7 for the finish waypoint
7. Tap "Request"
9. Open the request conversation and return online

## Expected Result:
Newly entered destinations are displayed as start and finish

## Actual Result:
Suggested destinations are displayed for the start and finish even after returning online. On the Distance expense receipt, the new address is shown below the suggested one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8f221a5d-5200-4e2b-ab74-3f5995481dec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a99352e561737912</li>
        <li>Upwork Job ID: 1738247677824786432</li>
        <li>Last Price Increase: 2023-12-22</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28070893</li>
<li>dukenv0307 | Contributor | 28070894</li>
</ul></li>
    </ul>
</details>

**Comment by cubuspl42** [comment]
@dukenv0307 Did you test the proposed changes? Have you confirmed that the changes previously applied to the old flow are suitable for the new flow?

**Comment by cubuspl42** [comment]
I approve the proposal by @dukenv0307 

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  https://github.com/Expensify/App/pull/28618
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - https://github.com/Expensify/App/pull/28618/files#r1442811199
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - Sign in to NewDot
    - Choose any workspace
    - Create a distance request on the workspace if there are not any
    - Navigate to the workspace chat
    - Go offline
    - Tap "+" > Request money > Distance
    - Select any start waypoint from suggestions
    - Tap the "Start" and enter a new name manually
    - Select any finish waypoint from suggestions
    - Tap the "Finish" and enter a new name manually
    - Tap "Request"
    - Open the request details from the chat
    - Verify that manually entered destinations are displayed as "Start" and "Finish"

**Comment by conorpendergrast** [comment]
Paid, and contracts ended. This bug was identified by Applause via testing, so I suspect it's already covered under the existing regression testing. I'll close for now, but reopen if you disagree!
