### ISSUE TITLE
[Wave 6: Workspace Chat] When a report is approved, we’re not displaying the GBR in real-time for the payer

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33503]
**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1703206812515759

Platform: Staging - web/chrome
Version: v1.4.15-4

Action Performed:

1. Create a collect policy in OldDot.
2. Execute the following JS snippet in the OldDot policy to enable workspace chats creation:

`if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }
`

3. Add a member and a non-admin approver.
4. Login in one session as a member, in another session as the approver and in another one as the payer (admin/policy owner).
5. As member, create and submit a money request in the workspace chat.
6. As approver, approve the request
Expected result: The GBR should be shown for the payer
Actual result: There’s no GBR and the payer should refresh the workspace chat (by clicking on another chat and clicking again on the workspace chat) to see the GBR

## Screenshots/Videos

https://github.com/Expensify/App/assets/51066321/87e8df84-9467-4e65-aed2-4a394ea70abb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01538471392b410b05</li>
        <li>Upwork Job ID: 1738294898815836160</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
[PR up](https://github.com/Expensify/Auth/pull/9537)

**Comment by marcochavezf** [comment]
PR was deployed the last week to production but the issue was not autoclosed. Closing it out manually.
