### ISSUE TITLE
[HOLD for payment 2024-01-18] [Card Settings] 🐛 "Physical card number" row is showing when the user has not completed their shipping details yet

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#33510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** kevin+42@expensifail.com

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1703261097098169

## Action Performed:
1. Assigned >$0 expensify card limit to [kevin+42@expensifail.com](mailto:kevin+42@expensifail.com)
2. Logged in to kevin+42@expensifail.com  and navigated to settings

## Expected Result:
Only a "virtual card number" row should be showing until a user activates their physical card

## Actual Result:
The "Physical card number" row is already showing

## Platforms:
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/22508290/af25d278-a87f-44df-b187-3788fd2b22c7)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cecc6a59ed91a8f9</li>
        <li>Upwork Job ID: 1738617571260575744</li>
        <li>Last Price Increase: 2023-12-23</li>
    </ul>
</details>

**Comment by grgia** [comment]
The fix for this one is here https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/settings/Wallet/ExpensifyCardPage.js#L268
We shouldn’t check if the object is empty, we should also check if the card is in the correct state - ACTIVE (3)

**Comment by mallenexpensify** [comment]
@grgia, @sobitneupane should this be internal or external?
I'm off the next week, so please move the issue along if possible without me (not that I'd really do much as BZ...)

**Comment by sobitneupane** [comment]
I believe this can be resolved externally. But I am not sure if it can be tested externally.

**Comment by grgia** [comment]
I can get a PR up for this one today

**Comment by grgia** [comment]
Working on PR

**Comment by mallenexpensify** [comment]
Contributor+: @sobitneupane due $500 via NewDot. 

@sobitneupane can you please propose regression test steps?  Thx

**Comment by mallenexpensify** [comment]
@sobitneupane can you propose the regression steps plz?

**Comment by sobitneupane** [comment]
@mallenexpensify Sorry for the delay. I will be able to work on the checklist only in the weekend. I am working only 50% this week.

**Comment by grgia** [comment]
not overdue, waiting on checklist / payments

**Comment by mallenexpensify** [comment]
@sobitneupane plz update the checklist.

**Comment by sobitneupane** [comment]
I will work on the checklist before weekend.

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/26915
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/26915#issuecomment-1923371735

> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It was a case missed while introducing a new feature.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

No.

**Comment by mallenexpensify** [comment]
@sobitneupane I feel like we should have a regression test for this, unless we're confident it won't ever happen again.  @grgia , what do you think?

**Comment by sobitneupane** [comment]
I did the test by adding some data in onyx in local environment. I will need some help from @grgia to finalize the regression steps for QA.

**Regression Test Proposal:** (QA steps from PR)

1. In Old Dot: Assign >$0 expensify card limit to @expensifail.com account
2. In New Dot: Logged in to @expensifail.com account and navigated to settings
3. Go to Expensify Card Page /settings/wallet/card/expensify.com and verify that virtual card row is displayed, no physical card row is displayed, and button reads "Get physical card" ✅
4. Go through Get Physical Card Flow
5. After completion, ensure that physical card row is displayed ✅

Do we agree 👍 or 👎

**Comment by mallenexpensify** [comment]
Contributor+: @sobitneupane due $500 via Newdot. 

Thanks! Testrail update GH is here https://github.com/Expensify/Expensify/issues/368473

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary above.
