### ISSUE TITLE
Deactivated cards in Marqeta are showing in state 3 in the DB, and continue to show in the UI

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#33515]
Version Number: v1.4.16-3
Reproducible in staging?: Y
Reproducible in production?: Y
Email or phone of affected tester (no customers): kevin@expensify.com, puneet@expensify.com

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1703263312062349?thread_ts=1703036940.153969&cid=C05DWUDHVK7

## Action Performed:
1. Request a new card in app, and thus cancel the current one(both cards were cancelled over a year ago)

## Expected Result:
The previous card should be in the deactivated state, and no longer show in-app.

## Actual Result:
The card is deactivated in Marqeta, but is still in state 3 (active) and shown in the UI on OldDot/NewDot

## Screenshots/Videos

Screen shows the card as if it is active in OldDot (and the same goes for NewDot)

![image](https://github.com/Expensify/App/assets/22508290/3d603dbc-305c-4add-ada3-f1bc9adf7d59)

In Marqeta you can see this card was terminated 

![image](https://github.com/Expensify/App/assets/22508290/72b9513d-3e20-42a2-8fd9-c92335bf2aba)

CC @madmax330 @joelbettner @grgia 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d852862166eb5e3</li>
        <li>Upwork Job ID: 1738255341632757760</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by madmax330** [comment]
@kevinksullivan I'm not sure there's anything we can do with these other than CQ them to closed (state 5) when we find them because they're probably a result of some old bug. Unless you have a more recent instance that we can look at?

**Comment by kevinksullivan** [comment]
@madmax330 we could do that. So far I've only seen internal cards fall into this category. I wonder if we can confirm whether this is more widespread somehow? Would it be possible to query cards that are terminated in marqeta and in state 3? Or do we not have any way to pull the former?

**Comment by sonialiap** [comment]
commenting to bump the overdue label off since conversation is happening

**Comment by madmax330** [comment]
> Would it be possible to query cards that are terminated in marqeta and in state 3? Or do we not have any way to pull the former?

We don't have an automated way to do the former so we have to build one, that's why I don't think it's worth doing.

**Comment by madmax330** [comment]
I'm also pretty sure this is an edge case so I'm not worried that this is widespread
