### ISSUE TITLE
[$500] Web/mWeb - Search - Search screen is in RHP instead of LHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32473
## Action Performed:
1. Log in to the app
2. Press on the search icon at the top of the sidebar
3. Check if the search screen is opened on the left side of the screen

## Expected Result:
Search screen should be displayed on the left side of the screen

## Actual Result:
Search screen is displayed on the right side of the screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/910430a5-90d9-4e85-a5b8-85f3f806bcbd

![Bug6324151_1703264138750!chrome_nbs5g9ISJf](https://github.com/Expensify/App/assets/78819774/2d50a3db-09d4-45b9-85c2-d5063911da8d)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c20e7bcbab30fd4</li>
        <li>Upwork Job ID: 1738251251126804480</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
See https://github.com/Expensify/App/pull/33406

**Comment by sakluger** [comment]
Thanks @shubham1206agra, looks like we reverted the new search component, so this is expected behavior for now.
