### ISSUE TITLE
[$500] Chronos stats for the day don't include current timer

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703269934720569

## Action Performed:
1. Log in as an expensify employee
2. Open the chat with [chronos@expensify.com](mailto:chronos@expensify.com)
3. Send a "start" message
4. Send "stats"

## Expected Result: 
Chronos should respond with stats including a "So Far This Week:" section. Under the current day it should show the time you have already recorded, plus the current timer.

## Actual Result: 
The stats for the day don't include the current timer, although it says they do.
`Friday: 0.4 (3.15 of those hours include the current running timer)`
Also, as a side note. I would like to make a feature request that the times are shown as hours and minutes instead of decimal hours. For example, 4h 12m

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (18)](https://github.com/Expensify/App/assets/38435837/450f6229-7ca2-4ea6-98b2-fda512f491f3)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017546317f3975e804</li>
        <li>Upwork Job ID: 1738289991548985344</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Chronos related so will be internal

**Comment by deetergp** [comment]
This is on production. Nobody needs to be paid out. Closing.
