### ISSUE TITLE
Update style for violations

### ISSUE THREAD

**Issue by cead22** [Expensify/App#33527]
- This is a followup to this PR https://github.com/Expensify/App/pull/32594
- We need to update the styles of the violations messages such that they're aligned in the same wat as error messages in form input fields are aligned, and the hoverable styles match those of the input row when the input row has the cursor over it

@lindboe @trevor-coleman can you comment here for assignment please? 
cc @Expensify/design 

<details><summary>Issue Owner</summary>Current Issue Owner: @cead22</details>

**Comment by cead22** [comment]
I applied the design label for good measure, but I think you've already specified how things need to look in the linked PR

**Comment by JaimisMiyani** [comment]
Hello
I would love to contribute. let me know if there is any issue.

Thanks in advance.

**Comment by JaimisMiyani** [comment]
Contributor details
Your Expensify account email: jaimismiyani12@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010843db372089015a

**Comment by cead22** [comment]
@JaimisMiyani we're working with Infinite Red at the moment to implement these changes for violations

**Comment by cead22** [comment]
Infinite Red is out til 2024, so I made this weekly for now

**Comment by dubielzyk-expensify** [comment]
Any updates on this one?

**Comment by cead22** [comment]
Not yet, Trevor and Lizzi from Infinite Red are handling all the front end issue for violations, and they're working on one at a time, and both have one issue assigned at the moment

**Comment by trevor-coleman** [comment]
@cead22 -- I can pick this up now that ReportUtils is pretty much done.

**Comment by cead22** [comment]
Work in progress

**Comment by cubuspl42** [comment]
I was pulled for the C+ review. Review is in progress.

**Comment by cead22** [comment]
@MitchExpensify can you please handle payment to @cubuspl42 for the review? Thanks!

**Comment by MitchExpensify** [comment]
Invited you for payment here, @cubuspl42 https://www.upwork.com/jobs/~015d4a656c0b6fb3d7

**Comment by cubuspl42** [comment]
Accepted 👍
