### ISSUE TITLE
[$500] IOU - All of the IOU chats disappear when I do the same IOU and turn the connection on

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open New Expensify app
2. Log in with a new account on device A (main)
3. Log in with the same account on device B
4. Disable the internet connection on device A
5. Split a bill with 2 users on device B
6. Split the same bill with 2 users on device A
7. Enable the internet connection on device A
8. Click/tap on the "back" button on device A

## Expected Result:
If you remove the error of creating a duplicate Split Bill, the duplicate conversations should disappear from the LHN and the original conversations should appear instead.

## Actual Result:
When creating a duplicate Split Bill offline and going online, an error appears creating an IOU in a group conversation and the created conversations disappear from LHN, the original conversations do not appear instead.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5c2171df-96d2-42e7-8545-c8120fc2cbd5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01855b88888a62b2b2</li>
        <li>Upwork Job ID: 1738524594676047872</li>
        <li>Last Price Increase: 2023-12-23</li>
    </ul>
</details>

**Comment by c3024** [comment]
Reproducible on production as well.

**Comment by mountiny** [comment]
Agreed this is not a blocker and an edge case, we do not handle the updates between same user devices perfectly but thats not focus right now
