### ISSUE TITLE
Cancel payment - "Auth CancelReimbursement" error shows up when cancelling payment with Expensify

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33540]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/32674

**Version Number:** v1.4.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition:
- User A (Admin)- have Fidelity verified business bank account set up on Old Dot.
- User B (Workspace member) - have Chase deposit bank account set up on Old Dot.

1. [Member] Request money from the workspace chat.
2. [Admin] Open the expense report and click Pay with Expensify.
3. [Admin] Click 3-dot menu > Cancel payment > Cancel payment.

## Expected Result:
Payment cancellation is successful.

## Actual Result:
Cancellation for payment with Expensify fails as "Auth CancelReimbursement returned an error" shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8e943858-de55-4eb9-99ed-4d07d432a60c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0f4ed22cb60b3ca</li>
        <li>Upwork Job ID: 1738517016348860416</li>
        <li>Last Price Increase: 2023-12-23</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Reverting the original PR

**Comment by mountiny** [comment]
PR reverted, Assigning @Gonals so you can track this issue and fix it in next iteration

**Comment by Gonals** [comment]
Setting it as monthly, as this is no longer happening (but I want it to keep track)

**Comment by Gonals** [comment]
@izarutskaya, were these real accounts? The test bank accounts don't work for reimbursement cancellation

**Comment by bfitzexpensify** [comment]
@izarutskaya bump on https://github.com/Expensify/App/issues/33540#issuecomment-1873902501. 

Switching this back to monthly based on @Gonals comment [here](https://github.com/Expensify/App/issues/33540#issuecomment-1870201604)

**Comment by Gonals** [comment]
Closing this, as it got reverted

**Comment by kavimuru** [comment]
@Gonals Our QA team is still able to reproduce when validating this PR #34719. So reopening the issue.

https://github.com/Expensify/App/assets/43996225/7f0cbb8a-7e4d-465d-9b65-6fb04648d568

**Comment by Gonals** [comment]
> @Gonals Our QA team is still able to reproduce when validating this PR #34719. So reopening the issue.
> 
>  Record_2024-02-16-15-47-53.mp4

Can you confirm you are using real bank accounts and NOT the test ones? This fails with test bank accounts 😅

**Comment by Gonals** [comment]
> > @Gonals Our QA team is still able to reproduce when validating this PR #34719. So reopening the issue.
> > Record_2024-02-16-15-47-53.mp4
> 
> Can you confirm you are using real bank accounts and NOT the test ones? This fails with test bank accounts 😅

Logs:

```
855e27c8bc8471e5-JHB | db1.sjc | 2024-02-15 14:14:07 640 | applausetester+kh150201@applause.expensifail.com | Cannot reimburse from Plaid test bank account
-- | -- | -- | -- | --

```

Basically, we don't really pay anyone with a test bank account, so we can't really cancel the payment


[855e27c8bc8471e5-JHB](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22855e27c8bc8471e5-JHB%22)+AND+timestamp:[2024-02-15T13:14:07.640Z+TO+2024-02-15T15:14:07.640Z]&index=logs_expensify-026816)	db1.sjc	2024-02-15 14:14:07 640	[applausetester+kh150201@applause.expensifail.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22applausetester+kh150201@applause.expensifail.com%22)+AND+timestamp:[2024-02-15T13:14:07.640Z+TO+2024-02-15T15:14:07.640Z]&index=logs_expensify-026816)	Cannot reimburse from Plaid test bank account

**Comment by bfitzexpensify** [comment]
Sounds like we're good to re-close this @Gonals?

**Comment by Gonals** [comment]
I think so
