### ISSUE TITLE
[$500] mWeb - Workspace - Tapping inside checkboxes prevents swiping

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33545]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Make a workspace
4. Start adding a fully verified bank account
5. At "Step 3" tap into a textbox like "SSN"
6. Swipe up and down

## Expected Result:
I should be able to fully reach the top and bottom of the page.

## Actual Result:
Tapping inside checkboxes prevents swiping.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cc97639c-4b84-45a3-bdac-3e74adff3733

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d8ade2fc0ea2fe3</li>
        <li>Upwork Job ID: 1738556594850705408</li>
        <li>Last Price Increase: 2023-12-23</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment]
@mountiny I think this will be fixed with VBBA refactor

**Comment by mountiny** [comment]
I agree with @shubham1206agra I think w can close this because:
- its minor
- and it will be soon fixed by the VBBA refactor
