### ISSUE TITLE
Workspace - Sensitive information is visible when deleting a workspace and creating a new

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33557]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check the Plaid connection in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Create a workspace
4. Start adding a bank account (Connect with Plaid)
5. Fill most of the details but don't complete the flow
6. Delete the workspace
7. Create a new workspace
8. Start adding a bank account (Connect with Plaid)

## Expected Result:
Private, sensitive information shouldn't be shared between workspaces

## Actual Result:
Uncomplete bank account details, company and personal information are saved when deleting the workspace and creating a new

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9a3bd525-6641-491d-a8c4-4c15b5aaac60

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
@mountiny This should be fixed with VBBA refactor (not 100% sure)

**Comment by mountiny** [comment]
I agree this does not seem like a blocker. Additionally its the same user who is inserting this data, the problem would be if the data is shared across sessions
