### ISSUE TITLE
[$500]  Expense - Receipts in the expense preview do not update after adding/deleting receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: There are more than 3 requests in the workspace chat and 3 of them have a receipt
1. Navigate to the workspace chat
2. Tap on expense preview
3. Tap on any request
4. Add a receipt to the request
5. Tap back button on the top left twice

## Expected Result:
The receipts in the expense preview in the workspace chat will update and +1 counter will show

## Actual Result:
The receipts in the expense preview in workspace chat does not update. It only shows +1 counter after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/da6c2953-9e6a-4c52-8b94-7b09c3462651

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198c10fd73498b28a</li>
        <li>Upwork Job ID: 1738598664125079552</li>
        <li>Last Price Increase: 2023-12-30</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28102438</li>
<li>bernhardoj | Contributor | 28102439</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
@cubuspl42 sorry to hear that, I have added a profile picture

**Comment by cubuspl42** [comment]
@tienifr 

Can you use `transactionsWithReceipts` inside `onyxSubscribe`'s `callback` anonymous function just like that?

The surrounding `useEffect` has empty deps (`[]`), there's no `useCallback` involved.

**Comment by cubuspl42** [comment]
@tienifr 

Now `transactionsWithReceipts` seems to be unused...

```
const [transactionsWithReceipts, setTransactionsWithReceipts] = useState([]);
```

Have you tested these changes? While I agree that it _might_ be beneficial to give some focus to the performance here, the code must first and foremost work.

Would you share the branch with the code you used for testing that the proposed solution works as expected?

**Comment by cubuspl42** [comment]
Thank you!

I'm still in two minds with this one, though... While it's good that the proposal tries to focus on providing good performance, the exact solution feels somewhat hacky.

We're using **both** a ref and a state property to store `transactionsWithReceipts`. I know that this pattern is sometimes used in the React world, it feels _at least_ workaroundish and I wouldn't apply it unless really necessary.

@bernhardoj 

Do you know what's the performance characteristic of your solution? How often would `setTransactionsWithReceipts` be called? Only once per specific user interaction (like adding/deleting a receipt), or tens/hundreds/thousands of times per second?

**Comment by bernhardoj** [comment]
@cubuspl42 because we subscribe to the whole transaction, `setTransactionsWithReceipts` will be called whenever the collection is updated. It can be updated by:
1. Add/edit/delete a money request
2. Add/replace/remove a receipt
3. etc.

I guess we can do something like this to prevent the re-render if the array contents are the same.
```
setTransactionsWithReceipts((prevTransactions) => {
    const newTransactions = ReportUtils.getTransactionsWithReceipts(props.iouReportID);
    return _.isEqual(prevTransactions, newTransactions) ? prevTransactions : newTransactions;
})
```

Talking about the performance, the current usage of `onyxSubscribe` is not really performant. 
https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/components/ReportActionItem/ReportPreview.js#L214-L226

Even though it doesn't cause a re-render, the four util functions make the same multiple loops to get all or linked transactions.

If we really want to improve the performance here, we can create like a wrapper for report preview like below. The 4 util functions above now only need to accept the transactions collection instead of the iou report ID.
```
function ReportPreviewWrapper(props) {
    const linkedTransactions = useMemo(() => Object.values(props.transactions).filter((transaction) => `${transaction.reportID}` === `${props.iouReportID}`), [props.transactions, props.iouReportID]);
    const transactionsWithReceipts = useMemo(() => linkedTransactions.filter((transaction) => TransactionUtils.hasReceipt(transaction)), [linkedTransactions]);
    const hasMissingSmartscanFields = ...
    const areAllRequestsBeingSmartScanned = ...
    const hasOnlyDistanceRequests = ...
    const hasNonReimbursableTransactions = ...

    return <ReportPreview {...props} transactionsWithReceipts={transactionsWithReceipts} ... />
}

export default withOnyx({
    transactions: {
        key: ONYXKEYS.COLLECTION.TRANSACTION,
    },
})(ReportPreviewWrapper);
```
And then memoized the ReportPreview.

memo(ReportPreview, (prevProps, nextProps) => _.isEqual(prevProps, nextProps))

Many things can be done to improve the performance, theoretically (because I didn't do any measurement).

**Comment by cubuspl42** [comment]
I decided that we should go with the proposal by @bernhardoj.

Thank you for raising the performance concerns, @tienifr. Unfortunately, the provided solution itself has issues, in my opinion, and I believe we should prioritize the simplicity here.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment]
@tienifr I hear you.

Still, this is not an issue related to the performance improvement project.

We _do_ subscribe to the transaction collection inside each `ReportPreview` and it's beyond the scope of this issue to change that.

Every change to the transaction collection _will_ trigger transaction-processing computations inside each `ReportPreview`, and it's beyond the scope of this issue to change that.

We _do_ trigger React state setters inside the Onyx callback, so React _will_ be forced to perform diffing in each `ReportPreview` instance.

You're right, though, that after our changes, the triggered JS computations would be bigger, and the render would propagate.

I think that a relatively low-hanging fruit here is a trick...

We could split `ReportPreview` into two components. An outer one which would exist for performance optimization reasons, and the inner one with the actual, more complex logic.

Inside the outer one, we could destructure the recent `transactionsWithReceipts`.

```ts
const [recentTransaction1, recentTransaction2, recentTransaction3]  = transactionsWithReceipts.slice(-3);
```

And we could cut the re-render based on the identity of these recent transactions. As we know, React prefers primitives and identity-stable objects when it comes to preventing re-renders.

We could experiment with this during the PR phase.

I could suggest a split compensation if the BugZero team agrees:

- $375 for @bernhardoj for his original proposal and implementation efforts
- $250 for @tienifr for investigating the performance issues and raising valid concerns
- $375 for the C+ review (me)

**Comment by Christinadobrzyn** [comment]
@puneetlath could you give your thoughts on this decision? https://github.com/Expensify/App/issues/33550#issuecomment-1873764619 Thank you!

**Comment by cubuspl42** [comment]
I think we've done things like this in the past when a solution included a non-trivial part of a non-selected proposal. The issue budget stays the same. But if this is not fine by the process, we'll have to live with it.

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo next week so assigning a buddy to monitor this. 

status- I think we're reviewing this - https://github.com/Expensify/App/issues/33550#issuecomment-1873764619

**Comment by puneetlath** [comment]
The proposal and the proposed compensation sounds good to me. Good by you @bernhardoj? If so, I'll assign you.

**Comment by bernhardoj** [comment]
@puneetlath I'm good with that

**Comment by puneetlath** [comment]
Assigning @bernhardoj. Agreed payment breakdown here: https://github.com/Expensify/App/issues/33550#issuecomment-1873818960

**Comment by bernhardoj** [comment]
Actually, I wasn't able to reproduce this anymore because in this [PR](https://github.com/Expensify/App/pull/34191), we connect to the whole transactions collection 😅

**Comment by cubuspl42** [comment]
Oh my, so this was one of those that you can wait out...

**Comment by Christinadobrzyn** [comment]
@cubuspl42 can you let us know what you think is fair for the partial payment?

**Comment by Christinadobrzyn** [comment]
Based on this Slack convo - https://expensify.slack.com/archives/C02NK2DQWUX/p1705917174041169

I paid out @cubuspl42 $125 (25% of $500) for the job. The payment is through Upwork. 

Feel free to reach out with any questions!
