### ISSUE TITLE
CRITICAL: Make workspace rooms show up in search before joining

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33571]
**Problem:**
Workspace rooms are available for anyone on the workspace to join.  However, there is no current way to find them as they don't appear in the Search switcher.

**Solution:**
Make all of a user's available workspace rooms appear in the Search switcher *even if* they haven't yet joined them.

**Comment by quinthar** [comment]
Discussing in Slack here: https://expensify.slack.com/archives/C0671JDRKQW/p1703813232587729?thread_ts=1703665406.897219&cid=C0671JDRKQW

**Comment by marcaaron** [comment]
We need to pass an optional param to this method [here](https://github.com/Expensify/Auth/blob/18721f8f412a5fd80cf8cf771a67c7c92e80a25d/auth/lib/Report.cpp#L7185) so that it returns all the reportIDs that have:

- non-empty `report.policyID`
- non-empty `rNVP.chatType`
- requestor is a member of the policy

Then we should be able to search for them by `reportName` (without any additional changes).

If we want to "preload" on sign in then we can modify `GetChats` so it passes the same param [here](https://github.com/Expensify/Auth/blob/18721f8f412a5fd80cf8cf771a67c7c92e80a25d/auth/lib/Report.cpp#L5060).

**Comment by quinthar** [comment]
I think we can skip "pre-loading" for now.

**Comment by marcaaron** [comment]
Thought more about it and there is no precedent for loading reports where you are not a participant in the app. I am not sure if the front end can handle this without additional changes, but will report back soon.

**Comment by marcaaron** [comment]
Query is working. There is some weirdness to work out though. 

When you search for a chat the frontend basically immediately thinks you are a member and:

- Immediately shows it in the LHN as an unread (tested this in focus mode)
- Lies and says you are a member when you haven't become a participant yet 😄 

It also seems like viewing the report is enough to join a public room, but if you look at a workspace room you won't become a member. So, I will have to look into what is happening with that. Probably we need some change in `OpenReport`.

**Comment by quinthar** [comment]
Ya, we need to change how public rooms work to not auto-join on viewing.
That predated the `hidden` notification preference with explicit "Join"
button.

**Comment by marcaaron** [comment]
Quick update here that the Auth PR is in review. However, the query for searching is... slow. Tested against @davidcardoza's account (lots of policies) and [the results](https://github.com/Expensify/Expensify/issues/356338) were a bit disappointing so I am hesitant to pull the trigger.

Will try to get some advice on the query side and repeat the timings.

**Comment by esh-g** [comment]
Just a suggestion:
How about we add a 'workspace rooms' menu item to the workspace initial page? This will help a user to find the workspace rooms from the workspace and this is where one would expect to find all the workspace rooms as well...
<img width="368" alt="Screenshot 2024-01-04 at 8 05 00 AM" src="https://github.com/Expensify/App/assets/77237602/9e2df93a-2816-4519-a805-e7d5b4d81eb1">

**Comment by marcaaron** [comment]
Interesting! Want to bring a proposal [to Slack](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q) @esh-g?

**Comment by esh-g** [comment]
Sure! will do so today

**Comment by marcaaron** [comment]
**Update:** Fixed the query issues. PR is in review and should be close to merging.

**New ETA:** Early next week.

**Comment by quinthar** [comment]
Done!

**Comment by marcaaron** [comment]
Put up a follow up PR in Auth to address the reports erroneously showing in the LHN.

**Comment by marcaaron** [comment]
Stumbled with the first fix, but have a new PR up to close out [the issue we ran into here](https://expensify.slack.com/archives/C066HJM2CAZ/p1704828736291789?thread_ts=1704764507.976049&cid=C066HJM2CAZ). Updated some tests in the process to prevent future regressions and make changes to the notification preferences less error prone.
