### ISSUE TITLE
HIGH: Update the UnreadMessageSummary subject line to emphasize user content

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33579]
**Strategy:**
Our plan to get a billion users involves convincing every business and organization in the world to create a "workspace" for their internal chat.  With luck it'll mean that users will be members of many workspaces, groups, and DMs.  Additionally, to fight the "tyranny of the straggler", all workspace communications fall back to email.

**Problem:**
As you use Expensify more for chat, you get more and more email notifications -- and they all contain Expensify Chat in the subject.  This feels very spammy: it's like, I get it, it's from Expensify Chat.   Consider the following subject lines:

- DM: `Expensify Chat between David and Joel`
- Group: `Expensify Chat between Concierge, David and A Clean`
- Room: `[Midtown Beer Garden] #announce Expensify Chat`
- Thread: `[Midtown Beer Garden] Chat Report Expensify Chat`

Contrast to Github, which devotes the entire subject line to the user's content:

- `[Expensify/react-native-onyx] Fix Prettier diff (PR #442)`

**Solution:** 
Streamline the subject line to focus less on us and more on the user's content by:

* **Non-Threads:** Use the room name (ie, whatever is shown in product in the header) for the subject, 
  - DM: `David and Joel`
  - Group: `Concierge, David, and A Clean`
  - Room: `Midtown Beer Garden / #announce`

* **Threads:** Put the "parent room" in brackets, and the threaded comment after:
  - DM: `[David and Joel] What do you think of blah?`
  - Group: `[Concierge, David, and A Clean] What do you think of blah?`
  - Room: `[Midtown Beer Garden / #announce] What do you think of blah?`
  - Thread in thread: `[What do you think of blah?] Bananas, mostly`

This preserves "threading" where same-subject messages neatly combine in Gmail.  But it prevents the redundant Expensify Chat everywhere.  It also has the benefit of reminding the user that DMs, groups, rooms, and threads are all subtly different.

Realtime Slack conversation happening here: https://expensify.slack.com/archives/C066HJM2CAZ/p1703535720130769

**Comment by iwiznia** [comment]
Part of this change made it so that I can't filter these emails anymore, can we please do something so that I can?
Some context here [staging.new.expensify.com/r/6170818806991248](https://staging.new.expensify.com/r/6170818806991248)

**Comment by mallenexpensify** [comment]
Per the link above, @iwiznia 's concern about filters should be alleviated with this
<img width="1089" alt="image" src="https://github.com/Expensify/App/assets/22508304/fb543eb9-f4ec-4e5e-afc4-17f205b48095">

**Comment by tgolen** [comment]
I've always loved how GH does their email notifications (utilize a no-reply address in the CC field) which also allows them to be filtered based on the action that triggered the notification. I think that would be pretty easy to implement and could work well. Though, we should be careful about spending too much time perfecting these as there could be more valuable work to do elsewhere.

![image](https://github.com/Expensify/App/assets/1228807/01019145-ff45-4d64-8bb8-6533b66951ce)

**Comment by rlinoz** [comment]
Auth PR has been merged, Web-E is in review.

**Comment by rlinoz** [comment]
Web-E is still in review.

**Comment by rlinoz** [comment]
Feature is in staging

**Comment by rlinoz** [comment]
This is deployed to prod, so closing this one

It created a new bug https://github.com/Expensify/App/issues/37568, which I will get to.
