### ISSUE TITLE
HIGH: Verify sending UnreadMessageSummary to unvalidated accounts didn't break notification frequency

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33583]
**Problem:**
I see this is merged, which is great!  However, testing is a little weird.  I have a test room where I mention a new email, and it does get the invite, which is great.  But for some reason that mention was sent out to everyone else in the room instantly — I would expect it to wait for an hourly update.  Additionally, subsequent messages seem to send instantly to everyone. Are you sure you didn’t break something causing messages to email out instantly to all members, or maybe all unvalidated users?  I've tested:

*Testing steps:*
1. Alice creates a workspace
2. Alice creates a workspace room named #test
3. Alice mentions bob@bagels.com in #test
4. Alice posts "Hello Bob!"
5. Alice mentions cathy@croissants.com in #test
6. Alice posts "Hello Cathy!"

*Expected result:*
1. Bob immediately gets a summary with:
    1. Alice invited @bob@bagels.com
2. Cathy immediately gets a summary email with:
    1. Alice invited @cathy@croissants.com
3. An hour later Bob should get a summary email with:
    1. Hello Bob!
    2. Alice invited @cathy@croissants.com
    3. Hello Cathy!
4. An hour later Cathy should get a summary email with:
    1. Hello Cathy!

*Actual result:*
1. Bob immediately gets a summary with:
    1. Alice invited @bob@bagels.com
2. Bob immediately gets a summary with: (this is wrong; it should come an hour later)
    1. Hi Bob!
3. Cathy immediately gets a summary email with:
    1. Alice invited @cathy@croissants.com
4. Bob *also* immediately gets a summary email with: (this is wrong; it should come an hour later)
    1. Alice invited @cathy@croissants.com
5. Bob immediately gets a summary email with: (this is wrong; it should come an hour later)
    1. Hi Cathy!
6. Cathy immediately gets a summary email with: (this is wrong; it should come an hour later)
    1. Hi Cathy!

**Solution:**
Can you do some testing to make sure that the summary notification frequency of newly invited/mentioned unvalidated users is being honored?

**Comment by marcochavezf** [comment]
[PR](https://github.com/Expensify/Web-Expensify/pull/40296) up
