### ISSUE TITLE
HIGH: Overhaul and normalize bulk invite between workspaces, groups, and rooms

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33582]
Trying to pull all these discussions together in one place, see Slack here: https://expensify.slack.com/archives/C01GTK53T8Q/p1703557793897069?thread_ts=1703360093.158969&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment]
Thanks DB, sorry to post the pre-design then immediately 👻 on vacation.  I'm planning to play catchup this week. I do have a higher priority project I need to focus on, search results order, so I won't be making the quickest progress here.

**Comment by quinthar** [comment]
Being handled in #wave8
