### ISSUE TITLE
[HOLD for payment 2024-01-04] [$125] Web - Emoji - Flag emoji category is missing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33593]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat.
2. Open emoji picker.

## Expected Result:
Flag emoji category is present.

## Actual Result:
Flag emoji category is missing. It is present on production.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/8c9f109a-c34f-4b44-b2a4-057538189937)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0b56adc8fc28c3f</li>
        <li>Upwork Job ID: 1739657472856895488</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28070186</li>
<li>mkhutornyi | Contributor | 28070187</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mountiny** [comment]
This is not a blocker and caused by two changes at the same time @TMisiukiewicz will handle this as a follow up to their PR, left a comment here https://github.com/Expensify/App/pull/31479/files#r1436483172

**Comment by mountiny** [comment]
Or given @TMisiukiewicz will be out til new year and given the change should be simple @mkhutornyi are you up for making this PR for $125?

**Comment by mountiny** [comment]
I can handle this review

**Comment by mountiny** [comment]
@mkhutornyi Please feel free to raise a PR following the original one, thanks!

**Comment by shubham1206agra** [comment]
@mountiny Does windows support flags emoji?

**Comment by mountiny** [comment]
I dont know how this looks or works on windows, but I agree we can just go back to what was decided before and any other change would be discussed in slack

**Comment by mountiny** [comment]
this issue stemmed from incorrectly resolved conflicts and th author of the PR has already been notified, I think that is enough as far as the checklist goes here

Payment here is $125 to @mkhutornyi

**Comment by mountiny** [comment]
No regression test required for this either I think

**Comment by JmillsExpensify** [comment]
Payment made based on [this summary](https://github.com/Expensify/App/issues/33593#issuecomment-1884943704)!
