### ISSUE TITLE
Web - A workspace that is deleted from OldDot is not immediately deleted from NewDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the same account on ND and OD
2. Delete a workspace on OD
3. Open the same workspace in ND
4. Click on 'Members'

## Expected Result:
Workspace should be immediately deleted on ND when it is deleted from OD

## Actual Result:
Workspace is not deleted until user interacts with it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4a491ff4-bbbc-463c-849d-347d7932cec7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121f8ebe017046adb</li>
        <li>Upwork Job ID: 1739666854001639424</li>
        <li>Last Price Increase: 2023-12-26</li>
    </ul>
</details>

**Comment by mountiny** [comment]
This is an internal change as we need to make update to backend for this

**Comment by anmurali** [comment]
Rotated for backup when I am OOO
