### ISSUE TITLE
[$500] Web - Admin room - User doesn't land in admin's room of a policy when navigating from oldDot to newD

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33600]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause 
**Slack conversation:**

## Action Performed:
1. Make sure you're logged out of NewDot & make sure your last opened chat is not admins room
2. Navigate to OldDot and log in with an existing account
3. Navigate to Settings > Policies > Group and note the number of free policies (or simply delete all of them)
4. Click on the "New Policy" button
5. Click on the "Free" option
6. Verify you're redirected to NewDot, that you're logged in with the same account as in OldDot
7. Tap on the back button
8. Web/Desktop - Verify the user lands in the #admin room of the policy

## Expected Result:
User should land in admin's room

## Actual Result:
User doesn't land in admin's room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/66732d19-3dcb-4173-a218-5659480d2f63

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2dc89604af58ba3</li>
        <li>Upwork Job ID: 1739670325091950592</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@hoangzinh Test rail: https://expensify.testrail.io/index.php?/runs/view/19458&group_by=cases:section_id&group_order=asc&group_id=229069

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - Admin room - User doesn't land in admin's room of a policy when navigating from oldDot to newD
### What is the root cause of that problem?
- We do not have logic that navigates user to admin report when navigating from oldDot to newDot
https://github.com/Expensify/App/blob/5c5c862a10b75214899da32333a7f3a694e38be3/src/libs/actions/App.ts#L345-L354

### What changes do you think we should make in order to solve the problem?
- We should add an additional param, named ```shouldNavigateToAdminChat```, and update the above function to:
````diff
function createWorkspaceWithPolicyDraftAndNavigateToIt(policyOwnerEmail = '', policyName = '', transitionFromOldDot = false, makeMeAdmin = false, shouldNavigateToAdminChat) {
    const policyID = Policy.generatePolicyID();
    Policy.createDraftInitialWorkspace(policyOwnerEmail, policyName, policyID, makeMeAdmin);
+  const adminsChatReportID = Policy.createWorkspace(policyOwnerEmail, makeMeAdmin, policyName, policyID);
    Navigation.isNavigationReady()
        .then(() => {
            if (transitionFromOldDot) {
                // We must call goBack() to remove the /transition route from history
                Navigation.goBack(ROUTES.HOME);
            }
+            if (shouldNavigateToAdminChat) {
+                Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(adminsChatReportID));
+           }
            Navigation.navigate(ROUTES.WORKSPACE_INITIAL.getRoute(policyID));
        })
        .then(endSignOnTransition);
}
````
### What alternative solutions did you explore? (Optional)
- NA

**Comment by DylanDylann** [comment]
@JmillsExpensify Can you confirm the expected behavior here? Should we navigate the user to the admin report in this case?

**Comment by JmillsExpensify** [comment]
I agree that this isn't a bug.
