### ISSUE TITLE
Whenever we show a relative date, we should add a tooltip on hover/long press to show the full date

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#33609]
# Problem

We have relative dates in some parts of our app (ie: `2 days ago`). Those relative dates hide details from the user, like the exact date and time the event happened and users sometimes want/need that data

# Solution

Ensure that wherever we show a relative date, we add the option to hover/long press to reveal a tooltip with the full actual date.

cc @zanyrenney

**Comment by JmillsExpensify** [comment]
Why is this a wave8 initiative?

**Comment by JmillsExpensify** [comment]
I tend to think this fits best in #vip-vsb

**Comment by JmillsExpensify** [comment]
I think we have higher priorities so closing this issue to whittle down what's on my plate. We can re-open down the road if it comes up again.

**Comment by iwiznia** [comment]
Oh bummer!
Why not add the needs help label and have a contributor work on it? This was never going to get closed as is...
