### ISSUE TITLE
[HOLD for payment 2024-01-04] [HOLD for payment 2024-01-03] [$500] Chat - PDF is not displayed in chat after uploading

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33626]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in.
1. Go to any chat.
2. Tap on the "+" button.
3. Tap on "Add attachment".
4. Tap on "Choose document".
5. Select any PDF.
6. Tap on "Send".
7. Wait for it to upload.

## Expected Result:
PDF preview should be displayed in chat after the uploading.

## Actual Result:
PDF preview is not displayed in chat after the uploading.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/96d73311-480c-46aa-b1fe-64977f66b2d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3278ab046cf0de8</li>
        <li>Upwork Job ID: 1739768322479259648</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 28070768</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by kbecciv** [comment]
Issue is not reproduced on production

https://github.com/Expensify/App/assets/93399543/f4e9fb8b-aa1b-4dba-9049-44c5a1baa806

**Comment by mountiny** [comment]
I think this might be related to the expo image pr https://github.com/Expensify/App/pull/30905 and seems like a true blocker as PDF files cannot be used/ sent in native devices cc @WojtekBoman

**Comment by mountiny** [comment]
The PDF previews are missing even after coming back to the chat so definitely a blocker imho

**Comment by Beamanator** [comment]
holy monkeys that's a big diff 😅 

Would be great if @WojtekBoman could help investigate this 🙏  I'll try to test locally soon, assuming my sims start up nicely

**Comment by Beamanator** [comment]
Hmm @mkhutornyi I like your idea, but i think we need to know why this is now necessary - a.k.a. what's different in prod now & how did things change?

**Comment by mountiny** [comment]
I am afraid the SWM developers will be ooo mostly so we should not wait for them. @mkhutornyi could you pinpoint whats the rootcause of this being different in staging than in production? thanks!

**Comment by kevinpetersson** [comment]
It seems like you are facing an issue where the default size (200, 200) is briefly shown before getting the correct size when using the updateImageSize function. I think the solution is to set an initial state for thumbnailWidth and tumbnailHeight before calculating and updating them. In this way, the
component rendering will have the correct initial values before the asynchronous calculation completes.

Here is my answer.

	const updateImageSize = useCallback(
	  async ({ width, height }: UpdateImageSizeParams) => {
	    // Set initial values to the default size
	    let thumbnailWidth = 200;
	    let thumbnailHeight = 200;

	    // Calculate the thumbnail size asynchronously
	    const { thumbnailWidth: calculatedWidth, thumbnailHeight: calculatedHeight } = await calculateThumbnailImageSize(
	      width,
	      height,
	      windowHeight
	    );

	    // Update the state with the correct size
	    thumbnailWidth = calculatedWidth;
	    thumbnailHeight = calculatedHeight;

	    setCurrentImageWidth(thumbnailWidth);
	    setCurrentImageHeight(thumbnailHeight);
	  },
	  [windowHeight],
	);

In this code, by setting the initial values before the asynchronous calculation, you ensure that the default size is set before the component renders. The await keyword is used to wait for the asynchronous calculation to complete before updating the state with the correct size.

(I have assume that calculate ThumbnailmageSize returns a Promise or is an asynchronous function. If it is a synchronous function, you can remove the async keyword and the await statement.)

if my answer makes any problem or make sense to you plz ping me.

**Comment by kevinpetersson** [comment]
It seems like you are facing an issue where the default size (200, 200) is briefly shown before getting the correct size when using the updateImageSize function. I think the solution is to set an initial state for thumbnailWidth and tumbnailHeight before calculating and updating them. In this way, the
component rendering will have the correct initial values before the asynchronous calculation completes.

Here is my answer.

	const updateImageSize = useCallback(
	  async ({ width, height }: UpdateImageSizeParams) => {
	    // Set initial values to the default size
	    let thumbnailWidth = 200;
	    let thumbnailHeight = 200;

	    // Calculate the thumbnail size asynchronously
	    const { thumbnailWidth: calculatedWidth, thumbnailHeight: calculatedHeight } = await calculateThumbnailImageSize(
	      width,
	      height,
	      windowHeight
	    );

	    // Update the state with the correct size
	    thumbnailWidth = calculatedWidth;
	    thumbnailHeight = calculatedHeight;

	    setCurrentImageWidth(thumbnailWidth);
	    setCurrentImageHeight(thumbnailHeight);
	  },
	  [windowHeight],
	);

In this code, by setting the initial values before the asynchronous calculation, you ensure that the default size is set before the component renders. The await keyword is used to wait for the asynchronous calculation to complete before updating the state with the correct size.

(I have assume that calculate ThumbnailmageSize returns a Promise or is an asynchronous function. If it is a synchronous function, you can remove the async keyword and the await statement.)

if my answer makes any problem or make sense to you plz ping me.

**Comment by c3024** [comment]
With RNFastImage we had this issue only on Android which was fixed with [a patch](https://github.com/Expensify/react-native-fast-image/pull/3).

With Expo Image it is on iOS as well.

I think properly addressing the `falsy` values here https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js#L48-L49
like @mkhutornyi suggested is a good approach.

**Comment by mountiny** [comment]
@mkhutornyi can you raise the pr? I think that showing briefly wrong size is fine for now to unblock deploy

**Comment by mountiny** [comment]
@mkhutornyi yep this is great, we can polish this later with SWM once they are back from holidays!

**Comment by mountiny** [comment]
Fixed in staging
![IMG_2104](https://github.com/Expensify/App/assets/36083550/ddef0f67-6e54-4f04-a70b-b989ffd224a8)

**Comment by peterdbarkerUK** [comment]
Payment summary: 

- [x] $500 to @mkhutornyi paid via upwork for PR
- [ ] $500 to @parasharrajat via newdot (please send a manual request, CC @JmillsExpensify )

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
