### ISSUE TITLE
System message for scheduled submit says Concierge submitted the report, though the system message is from the user

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703613580569359

## Action Performed:
1. Create a Collect policy on OldDot, with daily scheduled submit enabled
2. Invite user A as an employee. Invite user B as a “manager” for submit/approve.
3. Have user A create an expense/report on NewDot (do not submit anything)
4. Log in as user B on NewDot the next day, find the workspace chat for user A
5. Open the workspace chat for user A, click into the report from step 3.

## Expected Result: 
The system message uses the appropriate NewDot syntax, e.g. %displayName% submitted %reportAmount%

## Actual Result: 
The system message contradicts itself, coming from the user but then says that Concierge took the action.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2023-12-26 at 10 40 36](https://github.com/Expensify/App/assets/38435837/bbb92bcb-90c4-4e12-83a5-43e432355848)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by peterdbarkerUK** [comment]
struggling to reproduce this, as I'm only able to split. I'm not sure why, reached out to Greg for an assist.

**Comment by peterdbarkerUK** [comment]
@greg-schroeder I sent you a DM when you were OoO last week. Could you take a look?

**Comment by peterdbarkerUK** [comment]
@greg-schroeder friendly bump here!

**Comment by peterdbarkerUK** [comment]
Struggling to reproduce this, just set another one and waiting for a day.

**Comment by peterdbarkerUK** [comment]
hmmm, I only have the option to split, I can't seem to request money. Chatting with Greg to figure out where I'm going wrong.

**Comment by peterdbarkerUK** [comment]
Ok I figured out to request, but I cannot create an expense/report without submitting it.

**Comment by peterdbarkerUK** [comment]
We thought this was the policy not being on the Collect Workspace Chat beta, but no luck. I'm also not able to submit on my own account to the NewDot test workspace, so maybe the issue is with my account. Reached out to Jenna to check. 

This is a pretty minor issue so will keep pushing it along.
