### ISSUE TITLE
[$500] Unexpected error appears when a new account is mentioned with capitalized letters in a workspace room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcochavezf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703638924382019

## Action Performed:
1. Create a room in a workspace
2. invite a new user with upper case in the email by mentioning (@anyemail+TEST123@gmail.com)

## Expected Result:
No error message displayed

## Actual Result:
 Unexpected error appears 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2023-12-26 at 7 01 27 p m](https://github.com/Expensify/App/assets/38435837/49399aa3-20c8-4dc4-9098-a6f14a65c187)

![Snip - (26) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/f38b9805-ad22-4889-9e1e-faeb291843ac)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9c0d2ed32823d13</li>
        <li>Upwork Job ID: 1740103353508724736</li>
        <li>Last Price Increase: 2023-12-27</li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
Assigning myself and marking it as internal since it's a backend issue

**Comment by marcochavezf** [comment]
PR up

**Comment by marcochavezf** [comment]
Backend changes were deployed to production, tested in a public room, and went well. Closing it out
