### ISSUE TITLE
more than 1 push notification received

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703638626230959

## Action Performed:
1. Have A send a message to account B

## Expected Result:
B receives only one notification

## Actual Result:
B receives double or triple notifications

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (1)](https://github.com/Expensify/App/assets/38435837/68a89218-ef55-4879-bcc2-2083595a3966)

![image](https://github.com/Expensify/App/assets/38435837/1b0e9dad-47ba-41ea-9993-4160225da5e8)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Looking into this. There's at least 2 bugs. I already found one and have a PR ready, but investigating the 2nd one now.

**Comment by iwiznia** [comment]
ok found the other bug. Sending the 2 PRs now

**Comment by iwiznia** [comment]
This was already done AFAIK
