### ISSUE TITLE
[$500] IOU - The red dot displays on add attendee page when making a split bill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33687]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
1. Log in with the same account in the main testing device and a secondary device
2. Disable the internet connection in the main testing device
3. On the secondary device, split a bill with two users with whom you don't have existing conversations
4. In the main testing device (should be offline) create the SAME split bill with the 2 users
5. Enable the internet connection in the main testing device
6. Tap/click the X in the error message
Steps:
1. Tap on FAB
2. Select Request Money
3. Select Manual tab
4. Write any amount and tap on Next button

## Expected Result:
The attendee listing page should be properly displayed

## Actual Result:
The red dot displays on add attendee page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d7074f97-3faa-4eb1-b34f-bcd5d6bd9ea3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101f5b6d9ca416f4a</li>
        <li>Upwork Job ID: 1740193648431738880</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by Mohd-Sadiq-Ameen** [comment]
Currently new to it , can anyone guide how can i contribute anything , i am ready to learn new things even if required.

**Comment by techienaren** [comment]
Contributor details
Your Expensify account email: techienarayanan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01307592ed793cc494

**Comment by bfitzexpensify** [comment]
I'm also not sure that there's a clear expected behaviour here that is different to what we're seeing. 

I'm also struggling to imagine this flow (multiple devices in varying on/offline states trying to create the same split) actually occurring at all in regular use, feels like an extreme edge case. Going to close this one out.

**Comment by ShaheerCH** [comment]
Contributor details
Your Expensify account email: [shaheer.chry@gmail.com](mailto:shaheer.chry@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01dae010e170ced848

**Comment by ShaheerCH** [comment]
Contributor details
Your Expensify account email:  [shaheer.chry@gmail.com](shaheer.chry@gmail.com)
Upwork Profile Link: [https://www.upwork.com/freelancers/~01dae010e170ced848](https://www.upwork.com/freelancers/~01dae010e170ced848)

**Comment by ShaheerCH** [comment]
Contributor details
Your Expensify account email: shaheer.chry@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01dae010e170ced848

**Comment by KamauAlex** [comment]
Contributor details
Your Expensify account email: njugunakamaau@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~019057a705d753c74b
