### ISSUE TITLE
CRITICAL: Inconsistent Summary Notifications for different users in the same room

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#33685]
## Problem

Coming from this [comment](https://github.com/Expensify/Web-Expensify/pull/40167#discussion_r1432164203) in that PR, we're using the rNVP `NVP_LAST_NOTIFIED_REPORT_ACTION_TIMESTAMP` to save the timestamp of the last report action when we either run `NotifyOfflineUsersAboutActivity` or `NotifyReportDailyDigest`. And the problem is that we're using that rNVP value to get the messages after that timestamp [here](https://github.com/Expensify/Web-Expensify/blob/main/lib/ReportUtils.php#L2516-L2524) to send them as notification to the user, but that value is set at report level and not at the user level causing inconsistent summary messages for different users in the same room. i.e. if a comment is marked as read for an userA, the daily summary for userB will be the messages accumulated after the message that userA read or their daily summary was sent.

*Testing steps:*
1. Alice creates a workspace
2. Alice creates a workspace room named #test
3. Alive invites bob@bagels.com and cathy@croissants.com to the #test room
4. Cathy sets the preference to Daily (Click/tap on room avatar > Settings > Notify me about new messages > Daily)
5. Cathy logs out
5. Alice posts "Hello everyone!"
5. Bob opens the room immediately and sees the message

*Expected result:*
1. Bob and Cathy immediately get a summary with:
    1. Alice invited @bob@bagels.com and cathy@croissants.com
2. 1 day later Cathy gets a summary email with (alternatively force run the job `*NotifyReportDailyDigest?reportID=<reportID>*` from BJM):
    2. Hello everyone!

*Actual result:*
1. Bob and Cathy immediately get a summary with:
    1. Alice invited @bob@bagels.com and cathy@croissants.com
2. Cathy never receives the summary email with the subsequent message

**Comment by quinthar** [comment]
For this, didn't Cathy already see her invite message in the first email?  Why would she see it again 10 minutes later?

<img width="535" alt="image" src="https://github.com/Expensify/App/assets/575186/214bc467-3ea2-42cf-a01e-2add982a8f5c">

**Comment by marcochavezf** [comment]
Ah yes, she shouldn't see the invite, just the subsequent message "Hello everyone!". I will update the steps. Also, this happens more consistently with preferences set to `Daily`.

**Comment by marcochavezf** [comment]
Hmm the issue wasn't closed after being deployed to production https://github.com/Expensify/Web-Expensify/pull/40300#issuecomment-1872010221
