### ISSUE TITLE
[$500]  Windows 10 - IOU - "Unexpected error..." appears when add big image (10 mb) on manual expense flow

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Start a manual request
2. Enter the amount and continue
3. On the final review page - Click on the 3 dot menu on the top right
4. Click on the attach a receipt
5. Upload a large receipt (10mb)
6. Finish the request

## Expected Result:
Expense should be created and no errors should be displayed

## Actual Result:
"Unexpected error..." appears when add big image (10mb) on manual expense flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows 10: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d1af7c8e-5c2b-4b3f-a764-2ad47eaee0f0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4fd67c0f291b808</li>
        <li>Upwork Job ID: 1740340653873950720</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by namhihi237** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error appears when add big size image
### What is the root cause of that problem?
We do not limit the size for the manual request
### What changes do you think we should make in order to solve the problem?
I think we should add the validate limit size base on backend.

### What alternative solutions did you explore? (Optional)

**Comment by FlorianWueest** [comment]
Possibly intentional, as it's good practice to limit size of uploaded files? Receipts are almost universally under 10MB imo.

**Comment by peterdbarkerUK** [comment]
I agree, a 10mb receipt seems excessive. In that case though the error isn't unexpected and we should inform the user. Raised internally to establish wave priority.

**Comment by peterdbarkerUK** [comment]
Hangon, if it was the 10mb limit, wouldn't that apply across all platforms, not just Windows 10? I am able to upload an 18mb file easy-peasy on MacOS Chrome.
