### ISSUE TITLE
[$500] Room - The same user can be added multiple times via suggestion list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33706]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.18-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Open any room
3. Click on the room`s avatar -> Members -> Invite
4. Try to invite a user several times (after the second try you receive an error, that you had invited this user before)
5. Using @ try to invite a user several times in the room's chat (you can invite the same user several times using @)

## Expected Result:
The same user can't be added multiple times via the suggestion list, error should be appears on second try

## Actual Result:
The same user can be added multiple times via suggestion list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/542439ba-bd73-4c76-9510-b295a8543482

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01080af286719743f4</li>
        <li>Upwork Job ID: 1740341634845507584</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by FlorianWueest** [comment]
Seems intentional? '@' is not only invitations, but also 'mention' of the room member as well. Based on the video it seems like the group member gets invited only once, but gets mentioned multiple times? Or is there something I'm not seeing?

**Comment by paultsimura** [comment]
This is not an ivitation – that's a plain mention just like in any other chat. Why is this a bug?

**Comment by JmillsExpensify** [comment]
I'm also not clear why this is a bug?

**Comment by mananjadhav** [comment]
@JmillsExpensify Any actions here?

**Comment by JmillsExpensify** [comment]
I don't think so. Im going to close
