### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500] Pay button is shown briefly after approval when the policy has auto-reimbursement enabled

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33716]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a collect policy in OldDot with direct reimbursement
2. Execute the following JS snippet in the OldDot policy to enable workspace chats creation:
if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }
3. Add a member and an approver (the approver can be the policy owner too)
4. Login in one session as a member and in another session as the approver
5. As member, create a money request and submit it in the workspace chat
6. Verify the money request appears in the approver's workspace chat
7. Approve the report

## Expected Result:
Should see the text " waiting for your admin to pay these expenses" in the header as a approver

## Actual Result:
Approver is able to pay the request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b139aceb-6f6c-42be-be4d-28e42b7bd510

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eef76618a7ab320c</li>
        <li>Upwork Job ID: 1740413058975150080</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by shubham1206agra** [comment]
@marcochavezf Didn't we fix this in the approve flow? I remember we fixed this

**Comment by shubham1206agra** [comment]
I am unable to repro this

Ideal behaviour reference

https://github.com/Expensify/App/pull/28976#issuecomment-1834407818

**Comment by marcochavezf** [comment]
>  Didn't we fix this in the approve flow? I remember we fixed this

Ah the issue here is that when a policy has auto-reimbursement enabled, we're showing briefly the `Pay` button after approval, which shouldn't be the case since the backend will pay automatically once the request for approval has been processed.

**Comment by marcochavezf** [comment]
I will assign myself to work on it

**Comment by marcochavezf** [comment]
No update, but it's on my priorities

**Comment by trjExpensify** [comment]
>Ah the issue here is that when a policy has auto-reimbursement enabled, we're showing briefly the Pay button after approval, which shouldn't be the case since the backend will pay automatically once the request for approval has been processed.

Can we update the OP of this issue and the title to reflect the problem at hand here?

**Comment by marcochavezf** [comment]
Sure, updating it

**Comment by marcochavezf** [comment]
Changing it to internal since it requires a backend change.

**Comment by marcochavezf** [comment]
PRs up

**Comment by marcochavezf** [comment]
Not overdue, waiting for payment

**Comment by bfitzexpensify** [comment]
Offer sent @aimane-chnaif

**Comment by bfitzexpensify** [comment]
Payment complete
