### ISSUE TITLE
[HOLD for payment 2024-01-26] [$500] Web - Connect bank - Hmm not there displayed briefly in RHN when clicking on Continue setup in OD

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33713]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of ND
2. Log into OD with an account that has an existing workspace without a bank account
3. Click on "Continue setup" in the inbox task

## Expected Result:
User is redirected to ND and the "Connect Bank Account" page is displayed in RHN

## Actual Result:
After the user is redirected to ND, the "Hmm, not there" is displayed briefly in RHN

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a6947b71-fa66-4896-9323-07c3dc246691

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187028940738967b9</li>
        <li>Upwork Job ID: 1740402128918806528</li>
        <li>Last Price Increase: 2023-12-28</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 28071766</li>
</ul></li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
@neonbhai's [proposal](https://github.com/Expensify/App/issues/33713#issuecomment-1871310417) looks good to me.

🎀 👀 🎀  C+ reviewed

**Comment by mananjadhav** [comment]
@neonbhai Any ETA on the PR?

**Comment by mananjadhav** [comment]
This is ready for payout today @JmillsExpensify. I don't think we have any offending PR here.This occurs from deep link from OldDot to NewDot. I don't think we need a regression test for this one.

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Issue reporter: QA
 - Contributor: @neonbhai $500
 - Contributor+: @mananjadhav $500

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on summary above.

**Comment by JmillsExpensify** [comment]
Everyone paid out!
