### ISSUE TITLE
[HOLD for payment 2024-01-05] E2E tests failing consistently after PR #32367 merged in

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#33719]
If you look at the recent status of the `main` branch for the `Process new code merged to` workflow, it is consistently failing when not doing a version upgrade ([link](https://github.com/Expensify/App/actions/workflows/preDeploy.yml?query=branch%3Amain)). This seems to have started happening consistently after [this PR](https://github.com/Expensify/App/pull/32367) was merged. We should remedy this so that our E2E tests can catch bugs for us.

**Comment by iwiznia** [comment]
Conversation here https://expensify.slack.com/archives/C03TQ48KC/p1703786837284899

**Comment by roryabraham** [comment]
Got a PR that should fix this: https://github.com/Expensify/App/pull/33722

**Comment by roryabraham** [comment]
Closing this out as no payments are due here

**Comment by blimpich** [comment]
^ ignore above link, typo in the new issue that I wrote
