### ISSUE TITLE
[$500] Web - Expensify Classic - Page redirects blinks and then loads different UI

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33739]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to Settings > Go to Expensify Classic

## Expected Result:
User expects to be redirected to the correct page

## Actual Result:
The UI redirects to one page for a couple of seconds, then blinks and redirects to a completely different page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09f0b6f7-727f-4fd2-af18-ede3bdc67807

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188c9b3e1c8e006ce</li>
        <li>Upwork Job ID: 1742266129879453696</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by codeReturn** [comment]
Hello, I think its problem in link set on that part there:
https://www.expensify.com/inbox

Probably correct url should be - https://classic.expensify.com/

**Comment by codeReturn** [comment]
Contributor details
Your Expensify account email: ammarnp@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/amars0

**Comment by FlorianWueest** [comment]
Seems to happen not only on logout, but also when generally loading 'expensify.com'/OldDot.

**Comment by peterdbarkerUK** [comment]
I found the same as @codeReturn [here](https://github.com/Expensify/App/issues/33739#issuecomment-1871679177), it seems to happen if you're not logged into normal old.dot alongside staging newdot, which makes sense and isn't a bug. 

The blank screen on old dot is weird - @fedirjh I can't get your video to show, could you reshare?

**Comment by peterdbarkerUK** [comment]
Well shoot I should have thought that 😅 

My super-speedy eyes it looks like it's throwing the old Left-hand login landing page. Tagging internal and discussing priority internally. Thanks folks!

**Comment by peterdbarkerUK** [comment]
[Slack link](https://expensify.slack.com/archives/C01SKUP7QR0/p1704223809396229)

**Comment by peterdbarkerUK** [comment]
This is intended as a result of [ongoing A/B testing of our landing page](https://expensify.slack.com/archives/C05F77PJ91V/p1704806366131279?thread_ts=1704797231.283989&cid=C05F77PJ91V). This should end in the next week or so, though future A/B tests may have a similar effect.
