### ISSUE TITLE
[$500] Task – Reply remains under the task after deleting the subtask

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33734]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Create a task in 1:1 DM
4. Open the task details page and create a subtask assigned to yourself
5. Go back to the 1:1 DM and verify that Reply appears under the task.
6. Click on Reply link and open Subtask details page
7. Cancel the subtask
8. Go back to the 1:1 DM

## Expected Result:
Reply disappears under the task after deleting the subtask

## Actual Result:
Reply remains under the task after deleting the subtask

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bd58193b-b861-4593-af37-e6f270c8bd68

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f66de9449a2f9b75</li>
        <li>Upwork Job ID: 1740530326136565760</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by jliexpensify** [comment]
Tagged DB in #vip-vsb [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1703813275684939)

**Comment by rushatgabhane** [comment]
gonna bump it on slack. the fix should be simple

**Comment by rushatgabhane** [comment]
@dukenv0307 the proposal looks like a workaround to me.
When a task is deleted, it has a system message. I believe that the task shouldn't be hidden in the first place

**Comment by rojiphil** [comment]
@rushatgabhane 
I think this issue will get addressed in [PR here](https://github.com/Expensify/App/pull/32543). 
Can we put this issue on hold till then?

**Comment by jliexpensify** [comment]
Thanks @rojiphil , can you let us know once that PR is sorted? Cheers.

**Comment by jliexpensify** [comment]
PR was deployed to prod already

**Comment by jliexpensify** [comment]
I believe this is now fixed, the task gets deleted on v1.4.24-3.

However, on Android native v1.4.24-7 (Pixel 3a) and Android Chrome, I get the `Missing transalation` error when trying to assign a task to myself.

@lanitochka17 @rushatgabhane - can you both confirm? Thanks!

**Comment by jliexpensify** [comment]
@tienifr I found out the `Missing translation` is local to anyone on an @expensify.com email - does that help?

**Comment by jliexpensify** [comment]
`Missing Translation` PR being worked on, will retest after it gets deployed

**Comment by jliexpensify** [comment]
Whoops sorry - this slipped my radar. The `Missing Translation` PR was deployed a while back, and I retested: I can't see any instances of that error anymore.

**Comment by jliexpensify** [comment]
@rushatgabhane I re-tested the original issue too, it seems like it's come back, [even after this PR](https://github.com/Expensify/App/issues/33734#issuecomment-1871683589)? 

cc @rojiphil

**Comment by rushatgabhane** [comment]
@jliexpensify bumped it on slack for proposals

**Comment by jliexpensify** [comment]
@quinthar did you want to change the priority, since it seems like this issue is back?

**Comment by jliexpensify** [comment]
DB responded to my ping, we're not changing the priority. Also, [I've re-bumped the Slack post](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1710413391885759) to the entire channel for proposals.

**Comment by jliexpensify** [comment]
Hi @strepanier03 - I am headed OOO from the 21st to 31st March so assigning you as a buddy!

Summary:

- After this issue came off HOLD, I was able to recreate the original bug
- Last update [here](https://github.com/Expensify/App/issues/33734#issuecomment-2006151574)
- Looking for proposals currently!

**Comment by strepanier03** [comment]
@rushatgabhane - Do you agree this is a backend issue? Should we switch this internal?

**Comment by strepanier03** [comment]
Pretty sure we're going to make this internal.

**Comment by rushatgabhane** [comment]
@strepanier03 yes you're right this is backend

**Comment by rushatgabhane** [comment]
🎀 👀 🎀

**Comment by neil-marcellini** [comment]
I will get to this eventually, seems low priority

**Comment by jliexpensify** [comment]
TYSM @strepanier03 - I am back now so unassigning you!

**Comment by jliexpensify** [comment]
@neil-marcellini if this is low priority, want to make it a `Monthly`?

**Comment by neil-marcellini** [comment]
Oh yeah Monthly aka the garbage can? Sure. 😂 🗑️

**Comment by jliexpensify** [comment]
Moreso we're not pinged every week lol

**Comment by neil-marcellini** [comment]
I've hadn't had time or thought about this for a while, but maybe I'll take a shot at it when I have some spare time.

**Comment by jliexpensify** [comment]
Not overdue.

**Comment by neil-marcellini** [comment]
Too much on my plate still, pushing this off again.

**Comment by jliexpensify** [comment]
Not overdue

**Comment by neil-marcellini** [comment]
I'm going to close this because it's #vip-vsb related and that's one pause.
