### ISSUE TITLE
HIGH: Add a system message in the corresponding room when a room description is edited

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33736]
**Problem:**
We are going to be allow anyone to edit the room's description, which is ripe for abuse.

**Solution:**
Post a system message from the editor whenever the the room description is changed.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a15953af69385546</li>
        <li>Upwork Job ID: 1740532798842871808</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by quinthar** [comment]
Oh shit, this actually can't be done externally, nm!!  Call off the cavalry!!

**Comment by quinthar** [comment]
How do I undo the job post?

**Comment by puneetlath** [comment]
Planning to add this next.

**Comment by puneetlath** [comment]
Draft PR is here: https://github.com/Expensify/Auth/pull/9939

**Comment by puneetlath** [comment]
The Auth PR is merged, but not deployed. The Web PR will get merged once the Auth PR is deployed. Will likely be done early next week given the merge freeze.

**Comment by puneetlath** [comment]
This is all done.
