### ISSUE TITLE
[$500] Budget - Missing "for" word in workspace budget message in #admin room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33765]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.19-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of Control workspace.
- The Control workspace has a category that is set up with a budget.
Old Dot
1. Create expenses with category that has a budget and add them to the report until the total amount exceeds the workspace threshold.
2. Submit and final approve the report.
3. Create another report with some expenses with the same category.
4. Submit the report without approving it.
5. Create another report with some expenses with the same category.
6. Leave this report in the open state.
New Dot
1. Navigate to #admin room of the Control workspace.

## Expected Result:
The message in #admin shows "This workspace has a $[individual budget amount] per person per month *for* Advertising..".

## Actual Result:
The message in #admin shows "This workspace has a $[individual budget amount] per person per month Advertising..".
"for" is missing in the sentence.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/055cffa6-5704-4fa0-a55e-5c17293b95c9)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148740b8d18a4ca61</li>
        <li>Upwork Job ID: 1740789105056940032</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by isagoico** [comment]
Closing this issue to move it to the E/E repository.
