### ISSUE TITLE
iOS & Android - Many icons (login, avatars, add receipt, referral) are blank

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33777]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Explore different parts of the app (login, profile, mentions, add receipts, referral)

## Expected Result:
Avatars/icons in different parts of the app display as expected

## Actual Result:
Avatars/icons in different parts of the app (login, profile, mentions, add receipts, referral) are blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6328644_1703875864697!IMG_1521](https://github.com/Expensify/App/assets/78819774/9a5ace7f-9c75-4897-8f9d-8cf5c4741951)

![Bug6328644_1703876007397!IMG_1524](https://github.com/Expensify/App/assets/78819774/1ec68056-e35f-404d-872a-06652da1a04a)

![Bug6328644_1703876007407!IMG_1522](https://github.com/Expensify/App/assets/78819774/ae71dddf-6fc1-45fa-a6a9-56de4c3138a5)

![Bug6328644_1703876007406!IMG_1523](https://github.com/Expensify/App/assets/78819774/ac679347-22bb-4748-a8c2-f20ea5e62a5b)

![Bug6328644_1703877238218!IMG_1525](https://github.com/Expensify/App/assets/78819774/8a3f25d4-b9b2-4e24-8856-6f0e305c24f3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
cc @situchan @rayane-djouah

**Comment by mountiny** [comment]
This is fixed
