### ISSUE TITLE
[HOLD for payment 2024-01-11] [$250]  IOU - System message for merchant edit shows up for each time empty merchant is saved

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a manual request with no merchant as IOU report (between two users)
2. Go to request details page
3. Click Merchant
4. Without entering value, save it

## Expected Result:
No system message for merchant edit will appear because there is no change in Merchant

## Actual Result:
Each time the empty merchant is saved, the system message for merchant edit will show up - changed the merchant to "(none)" (previously "(none)"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/aab63d22-2163-48fb-9568-c27404473bd8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109648360ee115912</li>
        <li>Upwork Job ID: 1740852361151582208</li>
        <li>Last Price Increase: 2023-12-29</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 28073105</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by mountiny** [comment]
@waterim @koko57 this is one usecase we have missed in the PR

**Comment by mountiny** [comment]
@abzokhattab Do you fancy being C+ on the PR for $250? I will put up the fix and you will do testing and review? Its a simple PR but the authors are out

**Comment by mountiny** [comment]
@abzokhattab Can you review and do the reviewer checklist on this PR please? https://github.com/Expensify/App/pull/33785

**Comment by Beamanator** [comment]
@mountiny I'm unassigning myself since you took over and are killing it, thanks so much dude

**Comment by mountiny** [comment]
@kavimuru Can you please retest?

**Comment by kavimuru** [comment]
@mountiny Will retest and update you.

**Comment by kavimuru** [comment]
Issue is fixed. 


https://github.com/Expensify/App/assets/43996225/050b14f3-5e16-46f4-a15d-53838f7f41ca

**Comment by marcaaron** [comment]
Sounds like this one can have the blocker removed then. Gonna check it off. Thanks!

**Comment by mountiny** [comment]
$250 to @abzokhattab for help with review and testing the PR

**Comment by garrettmknight** [comment]
Will update payment on 1/11

**Comment by garrettmknight** [comment]
Paid!
