### ISSUE TITLE
[$500] [HOLD for payment 2024-01-17] Merchant for P2P is showing as empty

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#33789]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.20-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Create money request with another person
2. Set amount
3. Click Show more
4. Click Merchant
5. Click Save with empty merchant

## Expected Result:
Describe what you think should've happened

User should be taken back to the confirmation list

## Actual Result:
Describe what actually happened

The Merchant is showing as required which is not correct for IOU report, the merchant is only required for expense requests (so when the isPolicyExpenseChat is true)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Click back

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/36083550/463b2706-3d30-4090-bd93-0673adefa0f5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6a6202b3a982132</li>
        <li>Upwork Job ID: 1748072366986219520</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by mountiny** [comment]
cc @koko57 @waterim This is one follow up we need to handle from our PR to make the merchant required

**Comment by koko57** [comment]
@mountiny So here the problem was that we were validating if the merchant is empty no matter if it was p2p or workspace IOU. I've added a simple check to make sure to only validate when the merchant is required.

I also found a typo(?) in the route name:
<img width="338" alt="Screenshot 2024-01-02 at 19 58 54" src="https://github.com/Expensify/App/assets/28020445/cdf05945-b592-499f-8724-9603a925a49e">

let me know if I should fix it this PR 🙂

**Comment by mountiny** [comment]
Yep we can fix that in this pr too thbaks

**Comment by koko57** [comment]
ok, thanks! so I will add this fix and open the PR

**Comment by mountiny** [comment]
I can take this on as wave6 and i have worked with the previous iterations of this update

**Comment by mountiny** [comment]
@allroundexperts was this a regression from a PR you have worked on or should there be a request from you on this one? Can I close :D

**Comment by mountiny** [comment]
$500 to @allroundexperts

**Comment by bfitzexpensify** [comment]
Payment summary:

$500 to be paid to @allroundexperts to be paid via manual request.

**Comment by bfitzexpensify** [comment]
Wait, I might have closed this prematurely - @mountiny, do we need to complete the BZ checklist here?

**Comment by mountiny** [comment]
I dont think so it was a part of a bigger feature update, the pr author knows about this 

Regression tests will be covered holistically too i think

**Comment by JmillsExpensify** [comment]
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/33789#issuecomment-1899398872).
