### ISSUE TITLE
[HOLD for payment 2024-01-11] [HOLD for payment 2024-01-09] Expense - Merchant validation error shows "corrent merchant" instead of "correct merchant"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33781]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32486
## Action Performed:
1. Click FAB > Request money > Manual
2. Enter amount > Next
3. Select a workspace
4. Click Request

## Expected Result:
The validation error message shows "Please enter a correct merchant

## Actual Result:
The validation error message shows "Please enter a corrent merchant". It shows "corrent" instead of "correct"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6328704_1703880193535!image](https://github.com/Expensify/App/assets/78819774/30e205bd-002a-4d83-8c03-b4a7f20b694d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Its coming from a PR I have reviewed, going to put up a fix for this

**Comment by mountiny** [comment]
Handling this together with https://github.com/Expensify/App/issues/33780

**Comment by mountiny** [comment]
@abzokhattab is handling the review

**Comment by marcaaron** [comment]
Can remove the blocker here as well from the looks of it.

**Comment by mountiny** [comment]
This can be closed, nobody to pay
