### ISSUE TITLE
CRITICAL: Kill `areChatRoomsEnabled` beta everywhere

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33806]
_Note: Decided [here](https://expensify.slack.com/archives/C0671JDRKQW/p1704257810498329?thread_ts=1703906620.384849&cid=C0671JDRKQW):_

**Strategy:**
Not every feature is ready for a billion people to use. For this reason, we often put works in progress behind "betas" so we can test with some without risking premature exposure to others.

**Problem:**
While building out User Created Rooms (aka "workspace rooms"), we have hidden this functionality behind the `areChatRoomsEnabled` beta.  This flags which specific policies are eligible to have rooms.  Right now this is set as `true` by default for all Free workspaces, but can be set manually for others.  However, at this time there's no reason to limit this to any specific workspaces, all are eligible.

**Solution:**
Find every instance of `areChatRoomsEnabled` and remove.  This means:
1. Don't set it on new `Free` workspaces
2. Don't check it anywhere, on the client or server

**Comment by quinthar** [comment]
I think this is done.

**Comment by jasperhuangg** [comment]
Were the changes for this reverted? After a quick search I still see `areChatRoomsEnabled` in some places in App

https://github.com/Expensify/App/pull/34934

**Comment by jasperhuangg** [comment]
cc @quinthar @iwiznia

**Comment by iwiznia** [comment]
I am so confused. I think someone re-added them for some reason? 
I checked out the commit from my PR and there's no references to `areChatRoomsEnabled` there 😕

**Comment by jasperhuangg** [comment]
@iwiznia it looks like your PR was reverted https://github.com/Expensify/App/pull/34311

**Comment by jasperhuangg** [comment]
Do you want to take over on https://github.com/Expensify/App/pull/34934 since you were assigned to this issue originally?

**Comment by iwiznia** [comment]
Well, first off, if you revert a PR, you should ping the person that created, I could've never known it was reverted otherwise.
But more importantly, I see nowhere the reason why it was reverted.

**Comment by jasperhuangg** [comment]
cc @thienlnam 🙇 do you have any context as to why that PR was reverted?

**Comment by thienlnam** [comment]
https://github.com/Expensify/App/issues/34253#issuecomment-1885201199

I told you here Ioni 😆 
https://github.com/Expensify/App/issues/34253#issuecomment-1886566188

**Comment by iwiznia** [comment]
Ohhh, still, leaving info on the PR is always useful.

Anyway, so can I just send this PR again as is or do we need to do something else?

**Comment by iwiznia** [comment]
ok PR sent

**Comment by quinthar** [comment]
Can we close this?

**Comment by iwiznia** [comment]
No, issues get closed automatically when the corresponding PR gets deployed and the PR above is not even merged.

**Comment by quinthar** [comment]
ah, what remains to be done, who is doing it, and when will it be done?

**Comment by iwiznia** [comment]
Seems the automation did not work since this was already deployed https://github.com/Expensify/App/pull/35576#issuecomment-1931672819 but issue was not closed
