### ISSUE TITLE
[$500] Android – Attachment – Corrupted PDF file is not upload in the app.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. On a conversation, click on the + button in the compose box
4. Click on add attachment
5. Upload the following corrupted PDF
6. Verify that Failed to load PDF file. message appears when previewing a corrupt PDF file
7. Click send

## Expected Result:
Failed to load PDF file message appears in chat after sending a corrupt PDF file

## Actual Result:
Nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/50bbf980-74c5-4dab-8411-8ca6650ef93c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a329fc804a097631</li>
        <li>Upwork Job ID: 1741180286567841792</li>
        <li>Last Price Increase: 2023-12-30</li>
    </ul>
</details>

**Comment by fayzali1** [comment]
.

**Comment by roaugusto** [comment]
I didn't find the attached corrupted file. Could anyone provide the file mentioned in the problem?

**Comment by MitchExpensify** [comment]
Edge case that doesn't fit into a wave, closing
