### ISSUE TITLE
 Scan - No validation error when saving empty merchant in Scan details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33817]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Click FAB > Request money > Scan
2. Create a scan request
3. Navigate to scan details page
4. Click Amount and enter amount manually
5. Click Merchant
6. Save the empty merchant

## Expected Result:
Validation error will appear because merchant is a required field

## Actual Result:
There is no validation error when merchant is a required field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a719a47c-bd67-4959-ac3a-2ea327e683ed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment]
I agree, closing this out, cc @mountiny for a double check since you worked on this PR.
