### ISSUE TITLE
 IOU - Merchant field in editor is empty when the Merchant is manually set to Unknown Merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33818]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click FAB > Request money > Manual
2. Create a manual request with a user with "Unknown Merchant" as the merchant
3. Navigate to request details page
4. Click Merchant
5. Merchant field is empty

## Expected Result:
Merchant field in editor shows "Unknown Merchant"

## Actual Result:
Merchant field in editor is empty, when it shows "Unknown Merchant" in the details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/66a54e70-8eff-44ad-9732-c2e0cca74e31

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DylanDylann** [comment]
@mountiny This issue has the same root cause as [this one](https://github.com/Expensify/App/issues/33798). I think we should create a thread to discuss and confirm the final expect

**Comment by mountiny** [comment]
I can take over sir i was involved in the previous prs.

We don't have a bullet proof way to catch this or avoid it. 

What we could do is to disallow user to use this merchant as some specific i will discuss this in slack

**Comment by mountiny** [comment]
I am actually removing the consideration for the Unknown merchant https://github.com/Expensify/App/pull/34079

**Comment by mountiny** [comment]
This is resolved
