### ISSUE TITLE
`npm install` doesn't work for windows users

### ISSUE THREAD

**Issue by wcardosodev** [Expensify/App#33824]
When following the get started guidelines for local development, running `npm install` fails due to the `shellcheck` package being an outdated version which doesn't support windows os. Bumping this to `^2.2.0` resolves this issue.

Also a side issue is that the `postinstall` script also doesn't work, again windows related, changing the script to be:
```
"postinstall": "sh scripts/postInstall.sh",
```
fixes it.

**Comment by vtjhyn** [comment]
Contributor details
Your Expensify account email: [vtjahyono10@gmail.com](mailto:vtjahyono10@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e798ace6b83708f9
