### ISSUE TITLE
[$500] Delayed text message sent to phone even though the frequency is set to immediately

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33849]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703994911075889

## Action Performed:

1. Send a message to phone account in chat 

## Expected Result:
SMS is received with the message 

## Actual Result:
SMS is only deliver 10min after the message is sent 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![2024-01-17_15-23-39](https://github.com/Expensify/App/assets/62073721/4650b743-bbbd-441a-afee-cd5e6303f415)
![image (4)](https://github.com/Expensify/App/assets/38435837/90448cc1-8b04-4232-a463-3fbee9055c8a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011050c562712f8468</li>
        <li>Upwork Job ID: 1742508696621502464</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
potentially related GH: https://github.com/Expensify/App/issues/33621

**Comment by laurenreidexpensify** [comment]
Still waiting for proposals

**Comment by shubham1206agra** [comment]
@laurenreidexpensify Can you make this internal as message is made from BE only?

**Comment by laurenreidexpensify** [comment]
Waiting for an internal engineer to pick up

**Comment by iwiznia** [comment]
I just tested this and I got the SMS (it was slow, but it got there). Does anyone have reproduction steps? Alternatively a requestID from a comment that was sent but not received by SMS:
![image](https://github.com/Expensify/App/assets/521248/292ae0c8-4e94-4279-8d05-be5b089c21bc)

**Comment by laurenreidexpensify** [comment]
Okay I got around to testing this properly now and similar to Ioni, it did sent eventually (like maybe a 10min lag), will write up proper repro steps now

**Comment by justinpersaud** [comment]
Maybe. I'll check logs and see if I can find out what happen with David's message.

**Comment by justinpersaud** [comment]
I found the entry in Twilio, Message SID `SMf51ac329d7022be54317b0dad3b64764` for reference

Unfortunately, the logs of the messaging flow are already gone. They're only available for 7 days.

Our logs even indicate it was queued up, sent, and delivered within 1 second. I suspect any delays here are from carriers outside of our control and Twilio's.

![image](https://github.com/Expensify/App/assets/2513393/79519c4d-65c7-4564-8cbd-0516f361f1a8)


I can take another look if someone has an example of an issue with one but I'll need the phone number the message should have went to sent to me and the time.

**Comment by justinpersaud** [comment]
Logs for @laurenreidexpensify example that she provided

![image](https://github.com/Expensify/App/assets/2513393/ae8824f2-76eb-48c4-93d6-6f503be8b05b)
![image](https://github.com/Expensify/App/assets/2513393/cd9ae860-c478-4862-ade4-0a3d2e05063f)

So as far as I can see, the messages were sent quickly. I don't know how to troubleshoot end user delays, and their support article is broken https://www.twilio.com/docs/messaging/guides/debugging-common-issues#my-messages-are-delayed

I created a support ticket for more info https://help.twilio.com/tickets/15269844

**Comment by justinpersaud** [comment]
Last update from Twilio.

>Hi Jpersaud,,

> Thanks for reaching out to Twilio Support, and thank you for providing those examples. 
I have reviewed them and will need more feedback from our carrier partner, so I have escalated to them for further investigation. 
 
> I will keep you updated here.

**Comment by laurenreidexpensify** [comment]
Making a weekly while we wait to hear back from Twilio

**Comment by justinpersaud** [comment]
No update from Twilio yet. Bumped the support ticket for an update.

**Comment by iwiznia** [comment]
I am almost sure this is basically due to https://expensify.slack.com/archives/C03SDMF9YJ2/p1705935685709549
Let's close for now
