### ISSUE TITLE
Android notifications appear faster than desktop

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33847]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703990035864769

## Action Performed:
1. Send a message to "urban airship" room

## Expected Result:
Notifications should appear immediately across all devices where logged in

## Actual Result:
Notifications appear faster in android compared to desktop

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image](https://github.com/Expensify/App/assets/38435837/3f9089fb-4198-4f98-98fc-d3a04ed334bf)
![image (1)](https://github.com/Expensify/App/assets/38435837/f205c047-f9b6-4b48-818a-f8a780a2601a)
![image (2)](https://github.com/Expensify/App/assets/38435837/503194e9-0a11-415b-bdf1-8102a1bf2c95)
![image (3)](https://github.com/Expensify/App/assets/38435837/7dba0b17-a4ec-4944-8b17-306babfab28b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Looks like @iwiznia made a recent change to make pusher higher priority. So we'll see if that fixes it.

**Comment by puneetlath** [comment]
Ionatan's fix was deployed today. We'll see how things go now that it has been deployed.

**Comment by puneetlath** [comment]
Seems to be coming around the same time now. Going to close. Feel free to reopen if you experience differently.
