### ISSUE TITLE
HIGH: Promote rooms to all free workspaces

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#33859]
_Realtime discusion here: https://expensify.slack.com/archives/C0671JDRKQW/p1704258926011999?thread_ts=1703913938.716199&cid=C0671JDRKQW_

**Strategy:**
The journey of a billion users starts with a single step.  We are going to methodically release our functionality to larger and larger audiences learn fast, fix bugs, and keep going.

**Problem:**
We have pretty robust chat functionality, but very few customers know that, and basically none are using it.

**Solution:**
This is still being nailed down, but so far consists of:

1. Create a daily campaign of animated GIFs to have Concierge send to all Free workspace members, both in product and via email, each promoting [a specific feature of chat](https://expensify.slack.com/archives/C0671JDRKQW/p1703917438364699?thread_ts=1703913938.716199&cid=C0671JDRKQW) -- held on https://github.com/Expensify/App/issues/33792
2. Create an OldDot modal that uses those same animated GIFs and encourages the Free workspace member to try it out
3. Create a Public chat room named #bleeding-edge on the Expensify Chat workspace (so all EXFY employees have access), and have each of (1) and (2) invite them to participate in the product discussion around all this.  Moderate it closely.
4. Use CrazyEgg to ... what specifically?
5. Maybe we can include [#referral-program](https://expensify.slack.com/archives/CUD4X9HS6) here as one of the messages?
6. ... what else?

**Comment by zsgreenwald** [comment]
Storyboard doc is ready for an early review, and then I'll pass this over to Design

https://docs.google.com/document/d/136srSNf6Kqh9t1HKkR_FzwFQM5dOxjsLWnyYykza6Vk/edit

**Comment by zsgreenwald** [comment]
Storyboard is almost finished (should be done tomorrow), and then we'll hand it off to TCW

**Comment by zsgreenwald** [comment]
Latest discussion is here: https://expensify.slack.com/archives/C066HJM2CAZ/p1706192995311759

**Comment by quinthar** [comment]
It's happening!!  https://expensify.slack.com/archives/C066HJM2CAZ/p1707270567839739

**Comment by zsgreenwald** [comment]
Ran into some issues testing last night

**Comment by zsgreenwald** [comment]
Release 1 is going out today!

**Comment by quinthar** [comment]
Done!
