### ISSUE TITLE
Distance - Header and Amount show TBD when editing distance without saving it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33878]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33334

## Action Performed:
1. Navigate to the details page of a created distance request in the workspace chat.
2. Click Distance.
3. Click any address.
4. Delete one address and save it.
5. Close the distance editor without saving.

## Expected Result:
The amount and header will not show TBD as the distance is not changed.

## Actual Result:
The amount and header in details page show TBD. The same goes for the expense preview in the report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/84960668-dd91-4049-ac78-9bb05e949904

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
@DylanDylann @cubuspl42 @francoisl At first glance, it looks like this could be a regression caused by https://github.com/Expensify/App/pull/33397. Can you please confirm that theory?

**Comment by tgolen** [comment]
Ah, yes. I agree. Thanks for pointing that out! I'll give them a little time to see if they are able to fix it.

**Comment by shubham1206agra** [comment]
```js
function resetMoneyRequestAmount_temporaryForRefactor(transactionID, isDraft) {
    Onyx.merge(`${isDraft ? ONYXKEYS.COLLECTION.TRANSACTION_DRAFT : ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {amount: CONST.IOU.DEFAULT_AMOUNT});
}
```

Just update the function to this, and pass the `isDraft` correctly

**Comment by DylanDylann** [comment]
I am checking again

**Comment by DylanDylann** [comment]
Thanks guys for your recommendation, but It seems it doesn't work completely correctly. I am trying to find another way

**Comment by tgolen** [comment]
Should we just revert the original PR for now?
