### ISSUE TITLE
[$500] iOS - Connect BA - Company information page flash when select State when the keyboard is up

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33883]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Open the app
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Connect bank account
4. Choose Plaid or manually and process until the company information page
5. Open the State tab and enter any data (keyboard is open) -> Save

## Expected Result:
Page not flash

## Actual Result:
Page flash

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ae8250f2-d35c-48c5-b2d2-8a49252e1b8f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aaf54c26bd4cee4d</li>
        <li>Upwork Job ID: 1742594545811595264</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
@c3024 curious to get your input here: this seems like such a minor, low-value issue to me.

**Comment by jliexpensify** [comment]
Discussed here and we won't bother fixing it - https://expensify.slack.com/archives/C01SKUP7QR0/p1704410800429619

@kbecciv I'd recommend you focus on bugs and issues that are related to functionality, rather than these minor, low-value ones as the consensus is that they will be closed.
