### ISSUE TITLE
[$500] IOU - Split scan if merchant not entered, error not displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33884]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on fab --- Request money --- Scan
3. Upload a photo
4. Select 2 participants
5. Select add to split
6. Tap on split
7. Tap on scan request created
8. Enter an amount
9. Tap split
10. Tap on scan split created to open details page

## Expected Result:
When user taps split without entering merchant details error message under merchant section should be displayed and user must not be allowed to create scan split request.

## Actual Result:
When user taps split without entering merchant details, no error message under merchant section displayed and user allowed to create scan split request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ec900b85-fdef-4066-b8b8-3bc774f0f06d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141201e1b299de4ef</li>
        <li>Upwork Job ID: 1742597879398060032</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
As per https://github.com/Expensify/App/issues/33786#issuecomment-1872379010, the merchant is not required on the 1:1 requests with receipts. So I'd say this is an expected behavior.

@mountiny could you please confirm/correct?

**Comment by mountiny** [comment]
Yep this is correct the merchant is not required for non-expense cases
