### ISSUE TITLE
[HOLD for payment 2024-01-28] Remove `isNotEmptyObject` in favor of `!isEmptyObject`

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#33886]
It can be somewhat of an antipattern to create two methods as opposed to having a single method that can be negated. This is sometimes useful in TS when we want to narrow parameters, but we're not really using it that way in our code. 

This was discussed in more detail [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1704300817037659?thread_ts=1704295233.115369&cid=C01GTK53T8Q).

cc @blazejkustra

**Comment by blazejkustra** [comment]
Commenting for assignment 😄

**Comment by blazejkustra** [comment]
I got sick and work half hours, I'll get back to this next week, perhaps next week 🤗

**Comment by blazejkustra** [comment]
@tgolen I was merged already, we can close this issues, thanks!

**Comment by tgolen** [comment]
Sure! That's my favorite job.

**Comment by tgolen** [comment]
Payment Summary:

- @thesahindia needs paid $250 for a C+ review of https://github.com/Expensify/App/pull/34490

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
