### ISSUE TITLE
[$500] mWeb - Workspace - Nothing happens when user tried to upload a workspace avatar from Google Drive

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a workspace
3. Upload a workspace avatar image from Google Drive

## Expected Result:
User should be able to upload  a workspace avatar rom Google Drive

## Actual Result:
Nothing happens when user tried to upload a workspace avatar from Google Drive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/404f8b7f-51bc-416b-b0ea-73ae50eebee8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136cd78f29b78d09a</li>
        <li>Upwork Job ID: 1742608652669427712</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
I don't see this option when I try this on a Google Pixel 6 Pro. I think it's more likely that we just don't support native image upload for workspace avatars from Google Drive on Android Mobile web Chrome. This doesn't really seem like something we need to prioritize, since most people will just upload an avatar from their photos. Closing this.
