### ISSUE TITLE
IOU - In the Distance Request creation, it is not possible to delete an added point.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in as the employee account in NewDot
3. Click on FAB
4. Select "Request Money"
5. Click on the "Distance" tab
6. Click on "Start"
7. Enter a destination - E,g "45n N Beach Rd, FL"
8. Enter the "Finish" address - e.g "Beach Access Path, Sunny Isles Beach, FL"
9. Click on "Add Stop"
10. Enter "Pembroke Pines, FL, USA"
11. Return to map preview in RHP
12. Open the last added waypoints
13. Click on 3 points and delete the waypoint

## Expected Result:
When creating a Distance Request, the user should be able to delete waypoints

## Actual Result:
In the Distance Request creation, it is not possible to delete an added point.

## Workaround:
Unkown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/113ebfbc-6891-4fbd-8873-db55eeef7184

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment]
Looks like a regression from https://github.com/Expensify/App/pull/33397
