### ISSUE TITLE
Chat - Hidden is not shown when starting new chat with a user without previous conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33901]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Search for a public domain user that you have never chatted before
2. Observe the name when the conversation is opened

## Expected Result:
Hidden should be shown as the name and on LHN

## Actual Result:
Hidden is not shown but email is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3c1c0232-dce4-48cb-ae37-f2901cc9f5b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Not reproduced on Production

https://github.com/Expensify/App/assets/93399543/b13ca058-b752-414e-9bdd-f817adcac13a

**Comment by NikkiWines** [comment]
I'm unable to reproduce this on staging v1.4.21-1 in MacOS Chrome. @kbecciv can you confirm this is reproducible on staging? 

https://github.com/Expensify/App/assets/16747822/41108fae-019a-4d5e-b440-a64e4878aed4

**Comment by kbecciv** [comment]
I can reproduce on staging v1.4.21-1

https://github.com/Expensify/App/assets/93399543/2f6bb29b-bce3-4cce-950c-3962a43d1c47

**Comment by NikkiWines** [comment]
Weird, ok! I'll continue to dig into it

**Comment by paultsimura** [comment]
Couldn't reproduce in dev & staging either 🤔

**Comment by NikkiWines** [comment]
Seems like this might be tied to https://github.com/Expensify/App/issues/32613? @puneetlath do you know of anything that went to staging recently that might be causing this?

**Comment by puneetlath** [comment]
I think you're likely able to see that user's personal details because you were the one that invited them @kbecciv.

**Comment by puneetlath** [comment]
We did make some back-end changes, but I don't think this is a bug.

**Comment by NikkiWines** [comment]
Sounds good, removing the blocker label then. Thanks @puneetlath!

**Comment by puneetlath** [comment]
@kbecciv was this bug a result of a regression test? I think we might need to update the test as the scenario here, the user should actually "know" the other user and thus not see "hidden".

**Comment by lanitochka17** [comment]
@puneetlath  Hello
https://expensify.testrail.io/index.php?/tests/view/4151387

**Comment by kbecciv** [comment]
@puneetlath Correct, the bug a result of a regression test -, please attach TR https://expensify.testrail.io/index.php?/tests/view/4151387

**Comment by puneetlath** [comment]
@lanitochka17 @kbecciv can we just remove that test? It's no longer relevant with the changes we're making.

**Comment by puneetlath** [comment]
Bumped Maria bout removing the test here: https://expensify.slack.com/archives/C9YU7BX5M/p1707322780645939

**Comment by isagoico** [comment]
Deleted the TC (https://expensify.testrail.io/index.php?/cases/view/2778068) that covered this flow.

**Comment by puneetlath** [comment]
Thanks @isagoico!
