### ISSUE TITLE
[HOLD for payment 2024-01-25] [$125] Add a new download success message specifically for Settings > Share code > Download

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#33912]
## Summary
I believe the code is [here](https://github.com/Expensify/App/blob/b8b675daf6c8c3bd8d7d21706bf86a028b7b4037/src/languages/en.ts#L1764C17-L1764C17) for this. I don't think we should change the existing fileDownload success message because it might end up being used elsewhere as a generic success message and, more importantly, we want to create a specific message for this scenario. 

So this is what should happen:

1. In the New Expensify mobile app, go to Settings > Share code > tap Download
2. The modal that pops up (if successful) should say something like: 
  - **Downloaded!** 
  - Attachment successfully downloaded! (this is on iOS, at least)
3. We'd like to update it to say:
  - **Downloaded!**
  - Check your photos or downloads folder for a copy of your QR code. Protip: Add it to a presentation for your audience to scan and connect with you directly.

[[Slack thread](https://expensify.slack.com/archives/CUD4X9HS6/p1703100386388269), for internal reference]
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01915b215ea2a7921b</li>
        <li>Upwork Job ID: 1742674427176837120</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 28089531</li>
</ul></li>
    </ul>
</details>

**Comment by samsonmobisa** [comment]
function showSuccessAlert() {
    const successMessage = `Check your photos or downloads folder for a copy of your QR code. Protip: Add it to a presentation for your audience to scan and connect with you directly.`;

    Alert.alert(
        Localize.translateLocal('fileDownload.success.title'),
        Localize.translateLocal('fileDownload.success.message'),
        [
            {
                text: Localize.translateLocal('common.ok'),
                style: 'cancel',
            },
        ],
        { cancelable: false, message: successMessage }
    );
}

**Comment by samsonmobisa** [comment]
function showSuccessAlert() {
    const successMessage = `Check your photos or downloads folder for a copy of your QR code. Protip: Add it to a presentation for your audience to scan and connect with you directly.`;

    Alert.alert(
        Localize.translateLocal('fileDownload.success.title'),
        Localize.translateLocal('fileDownload.success.message'),
        [
            {
                text: Localize.translateLocal('common.ok'),
                style: 'cancel',
            },
        ],
        { cancelable: false, message: successMessage }
    );
}

**Comment by samsonmobisa** [comment]
Contributor details
Your Expensify account email: <samsonmobisa62@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/samsonmobisa>

**Comment by samsonmobisa** [comment]
Contributor details
Your Expensify account email: <samsonmobisa62@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~018e78ebb343f52495>

**Comment by samsonmobisa** [comment]
Contributor details
samsonmobisa62@gmail.com
https://www.upwork.com/freelancers/samsonmobisa

**Comment by samsonmobisa** [comment]
function showSuccessAlert() {
const successMessage = Check your photos or downloads folder for a copy of your QR code. Protip: Add it to a presentation for your audience to scan and connect with you directly.;

Alert.alert(
    Localize.translateLocal('fileDownload.success.title'),
    Localize.translateLocal('fileDownload.success.message'),
    [
        {
            text: Localize.translateLocal('common.ok'),
            style: 'cancel',
        },
    ],
    { cancelable: false, message: successMessage }
);
}

**Comment by jamesdeanexpensify** [comment]
Hi all - I consulted with the team internally and they agreed this particular job is fairly simple, so we've adjusted the price accordingly. Thank you.

**Comment by samsonmobisa** [comment]
Noted

**Comment by samsonmobisa** [comment]
Contributor details
Your Expensify account email: samsonmobisa62@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018e78ebb343f52495

**Comment by marcaaron** [comment]
Tossing the `New Feature` label onto this one to get a non-engineering eyes on it.

**Comment by marcaaron** [comment]
@thesahindia can you please address the comment above so we can close this one out? 🙇

**Comment by michaelhaxhiu** [comment]
@thesahindia friendly bump!

**Comment by strepanier03** [comment]
Missed that this got assigned to me, I'll move to daily and handle tomorrow.

**Comment by strepanier03** [comment]
@abzokhattab - Your contract has already been paid from what I can see so we're good there. 

@thesahindia - Payment summary is below. I'll assign Jmills and close this out for you to handle the manual request.

**Comment by strepanier03** [comment]
### Payment Summary

- Contributor - @abzokhattab  $125 - Paid via Upwork
- C+ - @thesahindia $125 - via Manual Requests

**Comment by JmillsExpensify** [comment]
$125 approved for @thesahindia
