### ISSUE TITLE
[HybridApp] Merge all code from `hybrid` into `main`

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#33915]
### Problem
We have lots of code in the OldApp repo on the `hybrid` branch that is not in `main`.

### Solution
Create a PR to merge it, then close out the tracking issue: https://github.com/Expensify/Expensify/issues/325312

**Comment by Julesssss** [comment]
I resolved a lot after getting responses, but there are maybe 8 left to discuss and either resolve or update. cc @staszekscp

**Comment by Julesssss** [comment]
I just merged the PR, thanks for your patience.
