### ISSUE TITLE
[$250] Payment for #25171

### ISSUE THREAD

**Issue by isabelastisser** [Expensify/App#33910]
[$250] Payment for #[25171](https://github.com/Expensify/App/issues/25171)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1fa3ae6c19d62ec</li>
        <li>Upwork Job ID: 1742658820996448256</li>
        <li>Last Price Increase: 2024-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 28079659</li>
</ul></li>
    </ul>
</details>

**Comment by Fludem** [comment]
> Paid in Upwork!

The job was posted on up work approximately 20 minutes ago with this ID.

Not sure if bug in workflow or something?
