### ISSUE TITLE
Card is showing RBR for suspicious transaction, when no suspicious transaction occurred or is shown in the inbox

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#33923]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** kevin@expensify.com
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1703037018018159

## Action Performed:
No real action performed, I just have an active physical card with no suspicious transactions flagged

## Expected Result:
No RBR in card settings in NewDot suggesting I have a suspicious transaction

## Actual Result:
There is a RBR in NewDot suggesting I have a suspicious transaction, but there is no transaction highlighted in the OldDot inbox. 

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/22508290/f8e22870-7ab1-4978-b325-c3299af53e96)
![image](https://github.com/Expensify/App/assets/22508290/eaa6d325-a604-43d2-a4ee-2a3cecb55479)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113138aebf1dfe448</li>
        <li>Upwork Job ID: 1745191508180258816</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by trjExpensify** [comment]
@grgia I see you got assigned here, does that mean it needs the `internal` label?

**Comment by AndrewGable** [comment]
I am experiencing the same issue

**Comment by grgia** [comment]
There's a handful of internal employees that are affected by a bug where closed cards were never marked as closed in the cards table. We will need to check these against marqeta and update the cards table

**Comment by grgia** [comment]
goal:

we need to find all the Expensify cards where a user has a card in the db that is incorrectly set to state active (3) but is suspended in Marqeta. We can start with internal employees

**Comment by grgia** [comment]
We are discussing here https://expensify.slack.com/archives/C03TQ48KC/p1704929399918409

**Comment by mananjadhav** [comment]
@grgia Do we have any updates on this one? I don't have access to the slack thread.

**Comment by kevinksullivan** [comment]
going to close this out until we see a real user experiencing this. What we've seen is these sorts of issues only pop up for internal folks with older cards (like me).
