### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500]  Android - Workspace - 1:1 DM between workspace members duplicated in LHN when invite again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33921]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open app
2. Create a workspace
3. Invite any members to the workspace
4. Navigate on LHN
5. Navigate to settings and remove the workspace members that were added
6. Navigate to LHN
7. Navigate to settings and add the previously removed members to the workspace again
8. Navigate to LHN

## Expected Result:
Announce, Admins and 1:1 DM conversations with each member should be displayed in LHN

## Actual Result:
The workspace 1:1 DM between members becomes duplicated in LHN when deleted members was invited to the workspace again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8906ba98-e457-4b92-9bcb-84cd1b2c3dca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce876b8941cda7d5</li>
        <li>Upwork Job ID: 1742714691943944192</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28089947</li>
</ul></li>
    </ul>
</details>

**Comment by lschurr** [comment]
@thesahindia could you review?

**Comment by lschurr** [comment]
@thesahindia - Can you work through the checklist on this one?

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @dukenv0307 $500 (paid in Upwork)
- Contributor+: @thesahindia $500 (to be requested in Newdot)

**Comment by lschurr** [comment]
Bump @thesahindia - could you please work through the checklist on this one?

**Comment by lschurr** [comment]
Thanks! Closing this one out.

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
