### ISSUE TITLE
[$500] Android - In room invite, scrolling down quickly, displays a white screen and shows top contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33937]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a room chat
3. Tap header
4. Tap members--- Invite
5. Scroll down quickly the contacts

## Expected Result:
In room page, tap invite and scrolling down quickly, must not display a white screen and must show contacts which are listed after scrolling down and not top first contact.

## Actual Result:
In room page, tap invite and scrolling down quickly, displays a white screen and shows top first contact.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b9d28cc1-fb41-454b-a16d-7aec66466a9d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab7d8c10578f647c</li>
        <li>Upwork Job ID: 1742848939270062080</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by slafortune** [comment]
I am not able to recreate this - are you @akinwale ?

**Comment by slafortune** [comment]
Still not able to reproduce this.
