### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] Storybook - "Page not found.." appears when navigate to Storybook link from chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33934]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33077

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Paste this storybook url to any chat https://staging.new.expensify.com/docs/index.html?path=/story/components-optionrow--default
3. Click on the link

## Expected Result:
User should navigates to Storybook page

## Actual Result:
"Page not found.." appears when navigate to Storybook link from chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8843c14d-e8fd-4a13-a50e-aa2ecce42168

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fbe4578a663e3299</li>
        <li>Upwork Job ID: 1742845470117625856</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28095041</li>
<li>tienifr | Contributor | 28095042</li>
</ul></li>
    </ul>
</details>

**Comment by miljakljajic** [comment]
@aimane-chnaif are you able to reproduce this? The link works fine for me?

**Comment by miljakljajic** [comment]
Got it, thank you. Please review @tienifr 's proposal when you're ready!

**Comment by miljakljajic** [comment]
@aimane-chnaif please accept the offer in upwork when you have a chance!

**Comment by miljakljajic** [comment]
paid and paid, closing.
