### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] Attachment - Attachment download option not available in offline but receipt download available

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a chat with attachments
3. Tap on a attachment
4. Note 3 dots on top with download option displayed
5. Navigate to LHN
6. Tap profile icon
7. Tap preferences-- toggle on forced offline
8. Tap on a chat with attachments
9. Tap on a attachment
10. In offline, note 3dots on top with download option not displayed
11. Navigate to LHN
12. Tap fab --- request money --- scan
13. Upload a image
14. Select a contact
15. Tap request
16. Tap on scan request created
17. Tap on receipt
18. In offline, note 3 dots on top with download option displayed

## Expected Result:
In offline, download option must be available or not available but behaviour must be consistent throughout the app.

## Actual Result:
Attachment download option not available in offline but receipt download available and there is inconsistency in behaviour.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/38580c10-e3e8-40a5-9c87-c8c1c38eb3e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010f6117214034f596</li>
        <li>Upwork Job ID: 1742850933425078272</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28088854</li>
<li>abzokhattab | Contributor | 28088855</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Pinged Dylan here to add to Wave 5 - https://expensify.slack.com/archives/C05DWUDHVK7/p1704411372335989

**Comment by jliexpensify** [comment]
@alitoshmatov bump for reviews please! Essentially, if it's possible to be downloading something whilst offline, we always want to be showing the download icon. Thanks!

**Comment by alitoshmatov** [comment]
@dukenv0307 Can you explain how would you check if file is available locally?

**Comment by alitoshmatov** [comment]
@dukenv0307 They are not working. We also have a case where if receipt is uploaded in offline mode it is downloadable but after refreshing the page the file is not downloadable and it is redirecting to invalid file url.

I think the best approach here is to not to show download button when in offline. 

https://github.com/Expensify/App/assets/59907218/7c3a8c71-8a6e-414f-a66c-5f87041b4b03

**Comment by alitoshmatov** [comment]
We can go with @abzokhattab 's [proposal](https://github.com/Expensify/App/issues/33939#issuecomment-1876846931)

We should not show download option when network is offline.
@abzokhattab also not that when three dot menu is empty we don't want to show it to prevent empty menu:
<img width="417" alt="Screenshot 2024-01-08 at 17 30 29" src="https://github.com/Expensify/App/assets/59907218/7f7e7256-aa76-441e-b5eb-2641373dae4a">

C+ reviewed 🎀 👀 🎀

**Comment by jliexpensify** [comment]
Bump @alitoshmatov to complete the checklist please!

Payment Summary

- Contributor: @abzokhattab $500
- C+: @alitoshmatov $500

[Upwork job](https://www.upwork.com/jobs/~010f6117214034f596)

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28373
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28373/files#r1464781176
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
- Determine if we should create a regression test for this bug. No need, it is very simple logic. It is pretty hard to break it

**Comment by jliexpensify** [comment]
Paid and job closed!
