### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] mWeb - Request – "Only visible to you" does not disappear when edit an amount field of scan IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33940]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Start the request money flow &gt; "Scan" receipt as the employee.
4. Upload a blurry receipt/make a photo.
5. Complete the money request flow.
6. While the receipt is scanning - navigate to the request conversation
7. Manually edit the amount field
8. Navigate back to the workspace chat

## Expected Result:
The “Scan in progress” message is no longer displayed

## Actual Result:
The “Scan in progress” message is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7ccec450-0978-4138-ac07-75de93d5fb11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01474415f07a92aeb4</li>
        <li>Upwork Job ID: 1742851749087182848</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 28093519</li>
<li>tienifr | Contributor | 28093520</li>
</ul></li>
    </ul>
</details>

**Comment by mollfpr** [comment]
The issue is more noticeable when editing the scan money request offline.

I agree with the @tienifr proposal, and the [proposal](https://github.com/Expensify/App/issues/33940#issuecomment-1876846827) looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't find the offending PR. We might forget to update the data optimistically while working on the feature.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Suitable for the regression step.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Start the request money flow > "Scan" receipt as the employee.
2. Upload a blurry receipt/make a photo.
3. Complete the money request flow.
4. While the receipt is scanning - navigate to the request conversation
5. Manually edit the amount field
6. Navigate back to the workspace chat
7. Verify that the “Scan in progress” message is no longer displayed
8. 👍 or 👎 

---

@anmurali Could you give the payment summary? I'll do manual request in NewDot afterward, thank you!

**Comment by mollfpr** [comment]
Friendly bump @anmurali

**Comment by mallenexpensify** [comment]
Contributor: @tienifr paid $500 via Upwork
Contributor+: @mollfpr owed $500 via NewDot

Testrail GH is here https://github.com/Expensify/Expensify/issues/367234

Think we're good to close, comment/reopen if needed.
