### ISSUE TITLE
[HOLD for payment 2024-02-07] Fix version mismatch for Notification Service Extension

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#33961]
cc @Expensify/mobile-deployers 

**Version Number:** v1.4.21-0
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C07J32337/p1704304425942669

## Action Performed:
Deployed to App Store

## Expected Result:
No issues

## Actual Result:
We're getting warnings about version mismatches between our main bundle and the Notification Service Extension:

![image](https://github.com/Expensify/App/assets/6833644/b677c3cb-24db-4e16-b55a-da0296c2f548)

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01625140e14e2c9d88</li>
        <li>Upwork Job ID: 1742939755659780096</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by arosiclair** [comment]
I've also noticed comms notifications have stopped working (no avatars) for me in**v1.4.21-4**. This might be the reason

**Comment by AndrewGable** [comment]
FYI you might need to change the version in the CI/CD build

**Comment by AndrewGable** [comment]
Agree

**Comment by arosiclair** [comment]
No C+ needed since this is just a deploy change

**Comment by arosiclair** [comment]
^ This kind of thing can't be regression tested of course. This should be all set so closing it out

**Comment by arosiclair** [comment]
Actually it looks like the deploy bot never committed the change to the versions. So the [NSE info plist](https://github.com/Expensify/App/blob/2a89886c844373163afebb859cb1c8cdc79df52c/ios/NotificationServiceExtension/Info.plist#L13) and [the main one](https://github.com/Expensify/App/blob/2a89886c844373163afebb859cb1c8cdc79df52c/ios/NewExpensify/Info.plist#L43) are still not matching in git. I should be able to fix that [here](https://github.com/Expensify/App/blob/2a89886c844373163afebb859cb1c8cdc79df52c/.github/workflows/createNewVersion.yml#L85-L93). 

That is a just a git problem though, we should have built and deployed with the correct versions

**Comment by arosiclair** [comment]
Version changes are [working now](https://github.com/Expensify/App/blame/main/ios/NotificationServiceExtension/Info.plist)! Already did the checklist above so this is all set

**Comment by AndrewGable** [comment]
As mentioned on Slack, fix didn't seem to work: 

![Screenshot 2024-01-18 at 8 44 06 AM](https://github.com/Expensify/App/assets/2838819/62e50b66-395e-4d45-a499-d0d9269f294e)

**Comment by arosiclair** [comment]
Okay I can actually reproduce this error in Xcode. It doesn't look like removing the Project Version and Marketing Version from the NSE target settings will fix it. The version just evaluates to `(null)`:

![Screenshot 2024-01-18 at 3 55 23 PM](https://github.com/Expensify/App/assets/6833644/fae752f0-92ee-492c-8705-7dee34fc31f5)

**Comment by arosiclair** [comment]
[This seems to be the root cause](https://stackoverflow.com/a/75578402). The project is auto-generating and replacing our info.plist

**Comment by arosiclair** [comment]
[PR is ready](https://github.com/Expensify/App/pull/34760)

**Comment by arosiclair** [comment]
This should be all done
