### ISSUE TITLE
[$250] [HOLD for payment 2024-02-07] Create centralized types for API params

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#33965]
context: https://github.com/Expensify/App/pull/28695#discussion_r1439869279

### Problem
Currently, we're defining a type for API params before each use of that API endpoint. This could lead to inconsistent application of API params and might make it difficult to know the params (and associated types) accepted by each API endpoint.

### Solution
Create a centralized map mapping API endpoint (string) to the params accepted by that endpoint.

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c2ec18790b398be</li>
        <li>Upwork Job ID: 1754981618246774784</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
While we think this is a good idea in the short-term for its own merits, part of our thinking here is that in the long-term we'll be able to define API params in the API (where they are actually defined), and build some compile-time tool that can generate this map in the front-end so that the front-end is always up-to-date with all of the params accepted by each API endpoint.

**Comment by roryabraham** [comment]
cc @blazejkustra @fabioh8010

**Comment by blazejkustra** [comment]
Commenting for assignment, thanks for creating this one @roryabraham

**Comment by blazejkustra** [comment]
I got sick and work half hours, I'll get back to this next week, perhaps next week 🤗

**Comment by roryabraham** [comment]
@blazejkustra put up a [PR for centralized API params](https://github.com/Expensify/App/pull/34542). Overall it looks good but it's very large and as such things would likely go smoother if we break it up into multiple PRs and migrate one actions file at a time.

Unless I'm mistaken these PRs should be almost 100% compile-time type changes, so I think we could loosen the screenshot and review requirements for each, _unless_ there are _any_ runtime changes introduced, as is often the case when types are found to be incorrect in TS migration PRs.

**Comment by roryabraham** [comment]
Chatted with @blazejkustra, I'm ok with doing a single PR as long as our C+ is thoroughly testing. It's a fair amount of overhead to review such a big PR but ultimately it does look quite safe.

**Comment by blazejkustra** [comment]
PR is up and ready for C+ review. @s77rt was selected, please have a look on comments above.

**Comment by roryabraham** [comment]
@joekaufmanexpensify assigning you back here to help issue C+ payment to @s77rt for their review of https://github.com/Expensify/App/pull/34542

**Comment by joekaufmanexpensify** [comment]
@s77rt offer sent for $250!

**Comment by s77rt** [comment]
@joekaufmanexpensify Accepted! Thanks!

**Comment by joekaufmanexpensify** [comment]
$250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
All set!
