### ISSUE TITLE
[HybridApp] Fix `$BRANCH_TO_COMPARE` TODO 

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#33964]
## Problem
Travis was linting code that wasn't changed on the HybridApp branch so we introduced the `$BRANCH_TO_COMPARE` variable. Once we merge HybridApp into `main` travis will begin to fail as `hybrid` will no longer be a valid branch.

## Solution
Update `$BRANCH_TO_COMPARE` to `main` once https://github.com/Expensify/Mobile-Expensify/pull/12533 is merged

**Comment by AndrewGable** [comment]
HELD on https://github.com/Expensify/Mobile-Expensify/pull/12533

**Comment by AndrewGable** [comment]
Still on hold

**Comment by Beamanator** [comment]
This can probably be off hold now :D

**Comment by Julesssss** [comment]
I had a quick attempt to resolve this: https://github.com/Expensify/Mobile-Expensify/pull/12541
