### ISSUE TITLE
[$500] LHN - Chat is bold in LHN when user viewed message and returned to LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33974]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open app on the main testing device
2. Sign In
3. Open staging.new.expensify.com on the secondary device
4. Sign Up with a new account
5. On the secondary device open the conversation with the main device (do no send any messages)
6. On the main device open the conversation with the secondary device (do not send any messages)
7. Send a message from secondary device on main testing device
8. Tap back button on main testing device to navigate to LHN

## Expected Result:
When user received message & viewed message and returned to LHN the conversation should be displayed as read

## Actual Result:
Conversation displays bold in LHN when user received message while viewing new conversation and navigated to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/91af460f-c176-446b-b8b0-a3b745320abd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
Waiting for proposals here

**Comment by Victor-Nyagudi** [comment]
There's another issue also dealing with a read message still appearing as [bold in the LHN](https://github.com/Expensify/App/issues/33680#issuecomment-1871446463). 

- https://github.com/Expensify/App/issues/33680#issuecomment-1871474470

Should this one be held until that one is fixed?

**Comment by MonilBhavsar** [comment]
Looks related. Let's put it on hold, thanks!

**Comment by sonialiap** [comment]
Still on hold

**Comment by sonialiap** [comment]
Still on hold

**Comment by MonilBhavsar** [comment]
On HOLD

**Comment by sonialiap** [comment]
On hold

**Comment by MonilBhavsar** [comment]
@MelvinBot updated above

**Comment by MonilBhavsar** [comment]
on HOLD

**Comment by MonilBhavsar** [comment]
Still on HOLD. The PR for other issue was reverted as it caused multiple deploy blockers

**Comment by MonilBhavsar** [comment]
on HOLD

**Comment by sonialiap** [comment]
On hold

**Comment by MonilBhavsar** [comment]
on HOLD

**Comment by MonilBhavsar** [comment]
The held issue has got PR in production. may be we can retest as this issue should probably fixed. cc @lanitochka17

**Comment by lanitochka17** [comment]
Issue is not reproducible 


https://github.com/Expensify/App/assets/78819774/a42bda67-ba24-487e-aac2-7e2943c109df

**Comment by MonilBhavsar** [comment]
Thanks for retesting!
Issue was reported by Applause. so no payment required here. Closing.
