### ISSUE TITLE
 Web - Task - Console error when assining task to non-existent user with gmail

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33989]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29730
## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Click on FAB > Assign Task
3. Enter a title
4. Assign the task to a non-existent user with a Gmail account

## Expected Result:
No console error is displayed after assigning a task

## Actual Result:
The console error is displayed after the task is assigned to a non-existent user with Gmail account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/56282bd9-723d-47ff-b753-f07233f87676

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production: 

https://github.com/Expensify/App/assets/78819774/841b3375-6971-44e4-8911-4b05ba47456c

**Comment by marcaaron** [comment]
>The console error is displayed after the task is assigned to a non-existent user with Gmail account

I'm not sure this is actually any problem. I've seen this happen from time to time. And it should not affect the feature we implemented in the PR that was tested.
