### ISSUE TITLE
[$500] Web - Task -Deleted task message & user avatar not greyed out when deleted offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29730
## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Disable internet connection
3. Create a task
4. Add a comment to the task
5. Delete the created task

## Expected Result:
The "Deleted task" message and user avatar are greyed out

## Actual Result:
The "Deleted task" message and user's avatar are not greyed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/72bbe6f1-1bef-49d6-bac1-0758dc64f972

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de665dd153fc50f2</li>
        <li>Upwork Job ID: 1743064675274317824</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28094515</li>
</ul></li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
@rushatgabhane please can you review the proposals?

**Comment by rushatgabhane** [comment]
I like @dukenv0307's proposal https://github.com/Expensify/App/issues/33986#issuecomment-1878145479 because it's more accurate
🎀 👀 🎀

**Comment by zanyrenney** [comment]
Assignging @dukenv0307 to work on this, thanks!

**Comment by marcaaron** [comment]
>Delete task has no offline feedback

Isn't [this](https://github.com/Expensify/App/blob/0f6fdd31fec4e55170b5779483ec353966cfbb4e/src/pages/home/report/ReportActionItem.js#L542-L596) already wrapped though?

https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/pages/home/report/ReportActionItem.js#L723-L724

Maybe I did not understand the proposal.

**Comment by rushatgabhane** [comment]
@dukenv0307 even then, some items aren't wrapped with `OfflineWithFeedback`.

I'm thinking if we could refactor the component so that everything is wrapped with `OfflineWithFeedback`? 

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/pages/home/report/ReportActionItem.js#L632

**Comment by rushatgabhane** [comment]
@dukenv0307 i agree with @marcaaron https://github.com/Expensify/App/issues/33986#issuecomment-1888112682, could you dig deeper into why `OfflineWithFeedback` is required when `renderReportActionItem()` is already wrapped with `OfflineWithFeedback`.

https://github.com/Expensify/App/blob/2d455bfb820b13fc83a5dd4057f19516faf2f238/src/pages/home/report/ReportActionItem.js#L723-L724

**Comment by rushatgabhane** [comment]
payment request here- https://staging.new.expensify.com/r/6779795954208025

**Comment by rushatgabhane** [comment]
@zanyrenney could you please attach payment summary. thanks 🙇

**Comment by JmillsExpensify** [comment]
Awaiting payment summary from @zanyrenney

**Comment by garrettmknight** [comment]
**Payment summary:**
- Contributor: @dukenv0307 $500
- Reviewer: @rushatgabhane $500

Upwork job: https://www.upwork.com/jobs/~01de665dd153fc50f2

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane based on summary.

**Comment by zanyrenney** [comment]
Thank you @garrettmknight I didn't see this bump before my OOO.

**Comment by rushatgabhane** [comment]
Issue can be closed
