### ISSUE TITLE
Incorrect information spacing for expense request preview card

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33980]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704275264210469

## Action Performed:
Create a receipt request on a workspace

## Expected Result: 
The information on the request preview card should match our Figma mockups.

## Actual Result: 
The information on the request preview card does not match our Figma mockups.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-01-03 at 10 51 29@2x](https://github.com/Expensify/App/assets/38435837/97243137-3c89-4546-8181-503f5a26b587)

![CleanShot 2024-01-03 at 10 51 03@2x](https://github.com/Expensify/App/assets/38435837/819fad77-c288-42b8-af1a-738b5f08906a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
I think we might want to make this one internal.

@Gonals I see you are assigned but @grgia perhaps you just want to handle all of the preview card improvements in one go? I will update [this issue here](https://github.com/Expensify/App/issues/33979) with all of the details, so maybe we close this one in favor of https://github.com/Expensify/App/issues/33979

**Comment by Gonals** [comment]
> I think we might want to make this one internal.
> 
> @Gonals I see you are assigned but @grgia perhaps you just want to handle all of the preview card improvements in one go? I will update [this issue here](https://github.com/Expensify/App/issues/33979) with all of the details, so maybe we close this one in favor of #33979

I think it makes sense to group all style updates together, yeah 👍

**Comment by grgia** [comment]
Yep I'll tackle this in https://github.com/Expensify/App/issues/33979#issuecomment-1878440557. Closing!
