### ISSUE TITLE
unclickable Via link appears in the LHN for the reports submitted by Concierge

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33988]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduciton
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703014725041959

## Action Performed:

1. Go to a workspace that has an approver configured
2. Request money
3. Submit the report

## Expected Result:
There should be no "(via LINK)" in the message. 

## Actual Result:
You’ll see the message - Concierge submitted this report (via LINK) to approver name

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (10)](https://github.com/Expensify/App/assets/38435837/0d3c6568-38c9-4644-af6f-7e6cf208822e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f889511aa97f482</li>
        <li>Upwork Job ID: 1744852990862630912</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @amyevans</details>

**Comment by puneetlath** [comment]
@kadiealexander what we need to decide is: 
1. do we just remove that link altogether OR 
2. make NewDot support it

**Comment by kadiealexander** [comment]
I think we should remove it, have posted [here](https://expensify.slack.com/archives/C049HHMV9SM/p1704688887488059?thread_ts=1703014725.041959&cid=C049HHMV9SM) in the original thread so that people can weigh in.

**Comment by kadiealexander** [comment]
Agreed to remove it! I think it needs to be done [here](https://github.com/Expensify/Web-Secure/blob/78286b435837e0118af538f9382174d3952b6bd0/lib/Report/Action/Submit.php).

**Comment by amyevans** [comment]
Will get to this in the next 1-2 days!

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by amyevans** [comment]
No update but should be able to knock out soon

**Comment by amyevans** [comment]
PR up: https://github.com/Expensify/Web-Expensify/pull/40618

**Comment by amyevans** [comment]
PR is deployed to prod, all set!
