### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500] Special characters not correctly escaped in system messages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33996]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704393581910299

## Action Performed:
1. In OldDot, create Collect plan, set as default
1. Set isPolicyExpenseChatEnabled = "true" on the policy by:
    1. Opening the policy settings in OldDot
    1. Open the JS console and run the following commands
    1. `p = Policy.getCurrent();`
    1. `p.policy.isPolicyExpenseChatEnabled = "true";`
    1. `p.save();`
1. In OldDot, create report on ^ policy & add an expense
1. In OldDot, submit the report (to yourself) & approve it
1. Open the report in NewDot, in another tab or device. Make sure that you have the expense report open and the reportID in the url matches. Make sure you can see both OldDot and NewDot at the same time.
1. In OldDot, mark the report as reimbursed (Reimburse -> I'll do it manually). *Important:* Leave a message when you're reimbursing the report saying "I'm manually reimbursing this report"
## Expected Result: 
In the NewDot tab, you should immediately see the new report action text, which should be `You marked this report as manually reimbursed, saying "I'm marking this as manually reimbursed for testing". This report will be reimbursed outside of Expensify`
## Actual Result: 
In the NewDot tab, you immediately see the new report action text, but it says:
`You marked this report as manually reimbursed. This report will be reimbursed outside of Expensify, saying I&#039;m marking this as manually reimbursed for testing`

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/92119e81-cc36-4588-8ff8-9d124df4af1c

![image (13)](https://github.com/Expensify/App/assets/38435837/f76a7073-4860-4984-ad63-63b1774f678a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189452e8b1cef5839</li>
        <li>Upwork Job ID: 1743086166231134208</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28082747</li>
<li>tienifr | Contributor | 28082748</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment]
@tienifr LGTM, let's apply it in [ReportActionItemBasicMessage.tsx](https://github.com/Expensify/App/blob/095161a690e0cea4cf5352b3d03212530a364fea/src/pages/home/report/ReportActionItemBasicMessage.tsx#L15) as you've suggested

**Comment by cubuspl42** [comment]
Great, we're waiting for the PR 👍

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No need for a regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
  - N/A

**Comment by NicMendonca** [comment]
@tienifr @cubuspl42 - you've both been paid!
