### ISSUE TITLE
Incorrect grammar in reports submitted to yourself

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704393820452899

## Action Performed:

1. In OldDot, create Collect plan, set as default
2. Set isPolicyExpenseChatEnabled = "true" on the policy by:
3. Opening the policy settings in OldDot
4. Open the JS console and run the following commands
5. p = Policy.getCurrent();
6. p.policy.isPolicyExpenseChatEnabled = "true";
7. p.save();
8. In OldDot, create report on ^ policy & add an expense
9. In OldDot, submit the report (to yourself) & approve it
10. Open the report in either OldDot or NewDot

## Expected Result: 
There should be a reportAction on the report saying "You submitted this report to yourself".

## Actual Result: 
There is a reportAction on the report saying "You submitted this report to you"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-01-04 at 8 46 34 PM](https://github.com/Expensify/App/assets/38435837/a222aa32-19d2-4d0e-b203-a9d2dd83b740)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c688c4186cba91e</li>
        <li>Upwork Job ID: 1743087792909430784</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
This is a super minor issue and probably not worth fixing externally. Closing.

**Comment by roryabraham** [comment]
lol, harsh @jliexpensify 😂

**Comment by roryabraham** [comment]
It is a bit of a nitpick, but it just drives me crazy every time I see it 😂

**Comment by roryabraham** [comment]
I'm going to go ahead and fix this since it's a really easy back-end fix

**Comment by jliexpensify** [comment]
LOL sorry @roryabraham I should have asked you about this one - I was going off [this post](https://expensify.slack.com/archives/C01SKUP7QR0/p1704412133724729?thread_ts=1704410800.429619&cid=C01SKUP7QR0)

**Comment by roryabraham** [comment]
Yeah, that's totally fair. This probably wasn't the absolute best use of my time, but it didn't take long and is fixed now. Live and learn, probably next time I would just leave it closed.

**Comment by jliexpensify** [comment]
Haha all good, it's probably good it's fixed...it actually does bug me too!

**Comment by roryabraham** [comment]
It's technically not fixed yet, but will be once https://github.com/Expensify/Web-Expensify/pull/40403 is reviewed and merged

**Comment by roryabraham** [comment]
This is done
