### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500] Status - Time input for custom time is not auto focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Profile > Status
2. Click Clear after > Custom > Time

## Expected Result:
The time input is not auto focused

## Actual Result:
The time input is auto focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ff16fdee-2837-409f-91d9-14b7cbc91f95

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FlorianWueest** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue: 
Time picker is not auto-focused after opening the date picker in custom status. 

### What is the root cause of that problem?
There's no auto-focus logic after loading the component. 

https://github.com/Expensify/App/blob/095161a690e0cea4cf5352b3d03212530a364fea/src/components/TimePicker/TimePicker.js#L356-L360

### What changes do you think we should make in order to solve the problem?
I think the simplest solution is to add the following code to the useEffect: 

```
useEffect(() => {
        // we implement this to ensure the hour input focuses on the first character upon initial focus
        // https://github.com/facebook/react-native/issues/20214
        setSelectionHour({start: 0, end: 0});
        
        // Focuses on the hour: 
        if (hourInputRef.current) {
            hourInputRef.current.focus();
        }
    }, []);
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by anmurali** [comment]
@Santhosh-Sellavel - this is blocked on you. Can you review the above proposals?

**Comment by Santhosh-Sellavel** [comment]
Need more time to review this, will update tomorrow!

**Comment by Santhosh-Sellavel** [comment]
Thanks, everyone for the proposals!
@tienifr's [proposal](https://github.com/Expensify/App/issues/34002#issuecomment-1878042761) approach is a straightforward way to set focus on the input, but before we move forward.

Let's get input from the design team on,

Whether we need auto-focus on this page or not?

@Expensify/design can you confirm, please?

cc: @anmurali

**Comment by dubielzyk-expensify** [comment]
I agree with you, Danny 👍

**Comment by dannymcclain** [comment]
@tienifr sounds good!

**Comment by anmurali** [comment]
@tienifr you asked for a design sign off right? Both @dannymcclain and @dubielzyk-expensify have provided input. So you can move forward.

**Comment by Santhosh-Sellavel** [comment]
Yes, I've checked but it's a bit minor thing.

We set to focus all inputs at the end for consistency, based on needs we can use arrow keys (or pointers) to change the cursor position or use backspace to delete or reset the value in this case & type freshly let's not over-engineer and complicate things here.

So @tienifr's [proposal](https://github.com/Expensify/App/issues/34002#issuecomment-1878042761) looks good here!

C+ Reviewed
🎀 👀 🎀

**Comment by anmurali** [comment]
**Payment Summary:**

- Contributor: @tienifr $500 (Waiting on confirmation i[n Slack ](https://expensify.slack.com/archives/C01GTK53T8Q/p1707238289617519)

- Contributor plus: @Santhosh-Sellavel  $500 (ready to pay on ND)

**Comment by anmurali** [comment]
@tienifr - offer is [here](https://www.upwork.com/nx/wm/offer/100825347)

**Comment by Santhosh-Sellavel** [comment]
I think we can skip the checklist, seems as if we intentionally didn't add focus here, now for consistency we add focus here as UX Improvement. Regression tests are also unnecessary as Applause raised this should be part of tests already.

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$500 approved for @Santhosh-Sellavel based on summary above.

**Comment by yuwenmemon** [comment]
@anmurali are we all set here?

**Comment by anmurali** [comment]
Yep. @tienifr is paid as well!
