### ISSUE TITLE
[$500] Web – Chat – The timestamp on the message changes based on the new time zone with delay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as user A and go to open Settings => Profile => Timezone, change the timezone (new)
3. As user B navigate to the conversation with user A
4. Check the timestamp on the message

## Expected Result:
The timestamp on the message changes based on the new timezone (new)

## Actual Result:
The timestamp on the message changes based on the new time zone with delay

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9e99fce5-69cc-4b43-bbcf-ed65bcf916c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bce6ed7ad9461ca</li>
        <li>Upwork Job ID: 1743246877083901952</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
It seems that we purposely don't send this as a proactive update when it changes. So I think everything is working as expected here. Feel free to comment/reopen if you disagree.
