### ISSUE TITLE
[$500] Android - Get 250 link is not working when page is loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34021]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab ---- Send money
3. Enter an amount
4. Tao next
5. Before page loads, tap "Get 250 link"

## Expected Result:
Get 250 link must work when page is loading

## Actual Result:
Get 250 link is not working when page is loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f6abfd13-7ec4-46ad-8f07-b51701af79c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188e4bd370b2e5e03</li>
        <li>Upwork Job ID: 1743246229184364544</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by muas19** [comment]
Unable to reproduce

**Comment by CortneyOfstad** [comment]
@lanitochka17 is this issue still happening? Looks like we're having trouble recreating. Thanks!

**Comment by lanitochka17** [comment]
Issue is not reproducible on the latest build 1.4.24-0


https://github.com/Expensify/App/assets/78819774/8addd0f5-9098-44ef-9006-96acd9f5d586

**Comment by CortneyOfstad** [comment]
Sounds good!
