### ISSUE TITLE
Unable to enable wallet after accepting the terms and conditions

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34033]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction (requires real data)
**Reproducible in production?:** needs reproduction (requires real data)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @arosiclair 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704467136661639

## Action Performed:
1. Open app 
2. Have a IOU split in the account
3. Pay with expensify
4. Add payment 
5. Enable wallet
6. Fill up the details and click after accepting the terms and conditions

## Expected Result:
User should be able to continue and enable wallet

## Actual Result:
Failed to enable the wallet after accepting terms and got an error message in Concierge:

`BankAccountAPI - Unable to activate wallet ExpException - 9db7c8a28ce30304290f0087deb10b60 ~~ message: '400 Missing country field in wallet additionalData' exceptionMessage: 'Auth ActivateWallet returned an error' exceptionFile: '/git/releases/expensify.com/3cf1c64/lib/Auth.php' exceptionLine: '125' exceptionCode: '400'`

Request ID: 840c91a8be1c5e67-EWR

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-01-05 at 9 58 09 AM](https://github.com/Expensify/App/assets/38435837/09314f11-fc6e-40e6-b697-826fab1e5c9c)

![Screenshot 2024-01-05 at 10 04 25 AM](https://github.com/Expensify/App/assets/38435837/4d8ad9da-29f5-47f0-a96f-d888ec95e852)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010480f11674506a6b</li>
        <li>Upwork Job ID: 1747317845325852672</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by peterdbarkerUK** [comment]
Nope, I'm still not able to get it - @arosiclair tagged to you for further investigation

**Comment by arosiclair** [comment]
I probably won't be able to prioritize this until next week. AFAIK, I'm the only one experiencing this so not super critical atm.

**Comment by arosiclair** [comment]
Logs: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22840c91a8be1c5e67-EWR%22)+AND+timestamp:[2024-01-05T13:56:37.537Z+TO+2024-01-05T15:56:37.537Z]&index=logs_expensify-026142

```
Throw ExpException - 9db7c8a28ce30304290f0087deb10b60 ~~ message: '400 Missing country field in wallet additionalData' exceptionMessage: 'Auth ActivateWallet returned an error'
```

**Comment by arosiclair** [comment]
Made another issue to run a CQ to fix my data

**Comment by arosiclair** [comment]
[CQ fixed it!](https://github.com/Expensify/Expensify/issues/363886#issuecomment-1910913001)
