### ISSUE TITLE
 IOU - In scan request, tapping download file shows error pop up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34043]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab--- Request money---Scan
3. Upload a corrupt pdf file
4. Select a contact
5. Tap request
6. Tap on request created and enter amount and merchant field
7. Tap in receipt and note error message can't upload file
8. Navigate back to scan request created and note error message "Receipt didn't upload, download the file. "
9. Tap download the file

## Expected Result:
In scan request uploading corrupt pdf, tapping download file must allow user to download the file and it must show pop up message " Attachment downloaded successfully 

## Actual Result:
In scan request uploading corrupt pdf, tapping download file shows error pop up "Attachment cannot be downloaded"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b7bacd4d-3517-447d-8250-eb8c9abfdef9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
Not able to reproduce on latest main

**Comment by mvtglobally** [comment]
Still repro on build 1.4.22-2 


https://github.com/Expensify/App/assets/43995119/a0cc60f4-b578-4dde-9bab-fba9390c0131

**Comment by thienlnam** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1704699988214449?thread_ts=1704683805.547759&cid=C01GTK53T8Q

**Comment by kbecciv** [comment]
@thienlnam Reopening the issue. We might need a second chance to review it. This PR (https://github.com/Expensify/App/pull/34087) introduced the issue where users can download the invalid file on step 6.

https://github.com/Expensify/App/assets/93399543/f6c31d78-21b9-4c1e-87ff-bcc781d0326d

**Comment by srikarparsi** [comment]
I think this can still be closed since it's around [handling a corrupt PDF](https://expensify.slack.com/archives/C01GTK53T8Q/p1704699988214449?thread_ts=1704683805.547759&cid=C01GTK53T8Q) and the error messages seem to be correct. cc @thienlnam if you feel differently
