### ISSUE TITLE
Reimbursement - Reimbursement message appears above Send money preview in report page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34053]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open 1:1 DM that has long conversation history
2. Scroll to the top
3. Click + > Send money
4. Enter amount and send money
5. Immediately after sending money, click on the Send money preview
(Might need to repeat several times to reproduce this issue)

## Expected Result:
The reimbursement message appears below Send money preview in report page

## Actual Result:
The reimbursement message appears above Send money preview in report page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5277f9ff-66f5-455b-b79e-c85cbec962eb

![Bug6333412_1704479316228!bandicam_2024-01-05_18-49-03-661](https://github.com/Expensify/App/assets/78819774/07415219-d808-438e-aa69-5105262967f7)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment]
Not a deploy blocker, investigating if it should behave differently

**Comment by rlinoz** [comment]
Will look into changing this today.

**Comment by rlinoz** [comment]
This was deployed to production https://github.com/Expensify/Auth/pull/9610#issuecomment-1885429151

Closing as there is no due payment.
