### ISSUE TITLE
 IOU - Tax settings for Foreign Currency Default are not applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34055]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32550

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable categories and add 3 categories, add an employee to the policy.
1. Open New Expensify app
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a group policy room
8. Click on "Show more"
9. In the category section, select the category at the bottom of the list
10. Navigate to the categories section again

## Expected Result:
When changing a currency other than the standard policy, the Tax Foreign Currency Default settings from OldDot should be automatically applied for the selected currency

## Actual Result:
Tax settings for Foreign Currency Default are not applied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/540cc091-1a95-4f78-b32f-71dd46f02cc5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tony-MK** [comment]
I believe this is a regression from https://github.com/Expensify/App/pull/32550.

**Comment by mvtglobally** [comment]
Still repro on build 1.4.22-2 

https://github.com/Expensify/App/assets/43995119/b35f0f83-9dce-4ad0-9793-6e0036565fc5

**Comment by thienlnam** [comment]
Removing the blocker since I don't think we use this feature right now on NewDot - but something we should fix

**Comment by MonilBhavsar** [comment]
Known and already planned in the wave issue and it is WIP https://github.com/Expensify/Expensify/issues/305057
Not a bug
