### ISSUE TITLE
[$500]  IOU - SmartScan accepts ZIP archives for scanning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34061]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Log in to your HT account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Click the Scan tab
6. Drag and drop the Zip archive on the scan modal
7. Select any user or WS
8. Complete the request

## Expected Result:
IOU SmartScan should not accept ZIP archives for scanning

## Actual Result:
IOU SmartScan accepts ZIP archives for scanning

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e4ef08c5-aae5-44d6-8657-7e04e97f8443

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127a303a9dda156f9</li>
        <li>Upwork Job ID: 1743368526458941440</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
This looks like an intentional behavior in https://github.com/Expensify/App/issues/29960

**Comment by shubham1206agra** [comment]
@trjExpensify Can you confirm internally if zip is allowed or not?

**Comment by trjExpensify** [comment]
Yep, just checked the backend on main and zip is still allowed ([internal ref](https://github.com/Expensify/Web-Expensify/blob/1c439322254042820d590b01e528fc8fa188b9eb/lib/Receipt.php#L490-L501)). Closing!
