### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] Android&iOS - Expense - Report submission and approval messages are smaller than other text

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace on Old Dot
- Device font size is set to minimum
1. Go to workspace chat
2. Create a manual request
3. Click on the preview > Submit
4. As admin, approve the report > Pay elsewhere
5. As employee, go to the paid expense report

## Expected Result:
The system message for report submission and approval has the same font size as other text

## Actual Result:
The system message for report submission and approval is smaller than other text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/76ae0c16-6cbc-418d-8880-abe7075c8074

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f27180af7e40074d</li>
        <li>Upwork Job ID: 1743370347796152320</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28092877</li>
<li>dukenv0307 | Contributor | 28092878</li>
</ul></li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Thanks @dukenv0307.  Sounds like we should tackle all these at once, what do you think @jjcoffee ? 
If you agree, I can update the OP to make clear what the deliverable is here

**Comment by jjcoffee** [comment]
Sorry for the delay getting to this! I agree, it looks worth fixing all these in one fell swoop.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by mallenexpensify** [comment]
Contributor: @dukenv0307 paid $500 via Upwork
Contributor+: @jjcoffee paid $500 via Upwork

Thx!
