### ISSUE TITLE
Hybrid app signed me out of new dot

### ISSUE THREAD

**Issue by cead22** [Expensify/App#34102]
- Making this issue per @AndrewGable 's request
- I don't have specific steps to reproduce
- I was testing out hybrid app by switching to new dot from within the old dot app
- I put the app in the background, and when I came back to it, I was signed out
- When I entered my email to try to sign back in, I got an error
- I force quit the app, opened it again, and I was in the old dot app. Switching to new dot worked fine

one | two
---|---
![IMG_4222](https://github.com/Expensify/App/assets/165133/c92b932b-fdb0-4cbd-9ec5-220389d46922)|![IMG_4223 2](https://github.com/Expensify/App/assets/165133/d4d24efc-5f3c-45a5-8803-87c269da7ce1)

**Comment by AndrewGable** [comment]
@puneetlath saw this too, I think @staszekscp said this might be something related to what he is looking into.


https://github.com/Expensify/App/assets/2838819/f4871291-fa25-444f-9fce-b4b59a204866

**Comment by AndrewGable** [comment]
Please reopen if you have this happen on a future version, I think it's fixed.
