### ISSUE TITLE
[$500] Distance - Amount shows 0.00 in the confirmation page when tax is enabled on workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is an employee of a Collect workspace on Old Dot which has tax enabled
1. Go to workspace chat
2. Click + > Request money > Distance
3. Enter addresses and proceed to confirmation page

## Expected Result:
The confirmation page shows the correct Amount

## Actual Result:
Amount shows 0.00 in the confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9dcc2730-006f-418e-990d-1d0705b20cd9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment]
@tienifr Thanks for the proposal. Your RCA makes sense but I'm not sure if that RCA is for this issue. I tried to reproduce this but we seem to always make an API request `OpenDraftWorkspaceRequest` to retrieve the rates where in the OP video the rates didn't update as if we didn't make any request. Were you able to reproduce the bug?


https://github.com/Expensify/App/assets/16493223/52e2caf3-cae4-40f6-bb4f-5bd1751e39c6

**Comment by s77rt** [comment]
@tienifr I agree we should fix the briefly $0.00 but let's also make sure we are not leaving any bug behind

**Comment by s77rt** [comment]
Waiting for reproduction confirmation cc @lanitochka17

**Comment by lanitochka17** [comment]
Issue is not reproducible on the latest build 1.4.25-1


https://github.com/Expensify/App/assets/78819774/a0a2cf0b-91f1-4d8b-b935-3f30afa74d73

**Comment by s77rt** [comment]
Still discussing ^

**Comment by s77rt** [comment]
No replies yet, bumped the slack thread once again

**Comment by s77rt** [comment]
We can close this. The brief $0.00 will be fixed by https://github.com/Expensify/App/pull/34135 cc @NicMendonca
