### ISSUE TITLE
[HOLD for payment 2024-01-24] PR regression causing misalignment of basic chat message styles

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#34152]
Problem:
We introduced a regression recently that causes a misalignment on standard chat messages:
![image](https://github.com/Expensify/App/assets/2319350/44ad877c-6e4b-4119-9150-f0f57ec95d74)

It seems like the line height of the sender is too tall or something. And it seems like this may have been caused by @rezkiy37 's PR here: https://github.com/Expensify/App/pull/32818

@rezkiy37 - are you able to revert your PR so we can get this back to normal? Thanks!

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by mananjadhav** [comment]
@grgia Can you review the [PR](https://github.com/Expensify/App/pull/34155) ?

**Comment by jliexpensify** [comment]
@rezkiy37 bump on completing the checklist please!

**Comment by jliexpensify** [comment]
Also, no Upworks Payment needed as @rezkiy37 will invoice us/this was a regression

**Comment by rezkiy37** [comment]
**BugZero Checklist:**
Determine if we should create a regression test for this bug: No, it is a minor visual bug that doesn’t affect UX.

cc @jliexpensify

**Comment by mananjadhav** [comment]
@jliexpensify But I was assigned this PR for the C+ review.

**Comment by jliexpensify** [comment]
Thanks for the head sup @mananjadhav 

Payment Summary:

- Contributor: @rezkiy37 (invoiced)
- C+: @mananjadhav $500 (request on New.Dot)

Let me know if this is incorrect!

**Comment by mananjadhav** [comment]
This is correct @jliexpensify. Thanks.

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav based on summary above.

**Comment by jliexpensify** [comment]
Great, closing this one - no payments needed.
