### ISSUE TITLE
[$500] Chat - "1 Reply" that leads to a deleted message can't be seen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a new chat
2. Write "1" in the chat
3. Thread the message, write the next number "2"
4. Thread "2" and write "3"
5. Continue until you reach "7"
6. Delete "4" and "3"
7. Navigate to "2"

## Expected Result:
"1 Reply" should be visible.

## Actual Result:
"1 Reply" that leads to a deleted message can't be seen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/495db99c-6a90-4a4a-a35d-ac819319ac94

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d798bc67214359f5</li>
        <li>Upwork Job ID: 1744786603697438720</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
There was a similar issue to this https://github.com/Expensify/App/issues/26012
As you can see https://github.com/Expensify/App/issues/26012#issuecomment-1776598469, we need backend change as well in the issue, but it looks like the backend logic wasn't changed yet

You can verify this by doing the same tests in offline mode

**Comment by puneetlath** [comment]
@s-alves10 did we specifically decide not to do the back-end changes there?

**Comment by s-alves10** [comment]
We decided to do the backend updates, but it looks like the backend was not updated yet

**Comment by cubuspl42** [comment]
We're still waiting for some backend changes if I'm not mistaken

**Comment by cubuspl42** [comment]
@puneetlath Is there some Expensify-Web issue ID we could hold on?

**Comment by puneetlath** [comment]
Closing this out as it looks like the back-end changes are being handled elsewhere.
