### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] IOU-Error message remains on IOU report even same error message is dismissed from 1:1

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with separate accounts in the main testing device and a secondary device
2. In the main testing device create an IOU with a user
3. Disable the internet connection in the main testing device
4. In the main testing device (while offline) cancel the IOU
5. In the secondary device (online) mark the IOU as paid with the option "Settled up elsewhere"
6. Enable the internet connection in the main testing device
7. Verify a red dot appears on the chat in LHN
8. Tap the X from the conversation
9. Go to IOU report

## Expected Result:
Since User dismiss the X error should not appear into IOU report

## Actual Result:
Error message remains on IOU report even same error message is dismissed from 1:1

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/36572323-44bc-4adb-bf1f-35470abbdf78

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c035b355c60f48e</li>
        <li>Upwork Job ID: 1754884327412707328</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kaushiktd** [comment]
Not sure why I received email notification about this issue! Usually if I comment my proposal, I start receiving email notifications after it. Isn't that how it works?

**Comment by kaushiktd** [comment]
I agree with @tienifr and @codebycarlos. I checked his proposal.
The proposal advises that the data structure be normalized. This would eliminate duplicate errors and speed up the resolution process. The solution aims for simplicity and effectiveness by providing consistent error generation with shared microseconds and updating dismissal logic to eliminate errors from both reports at the same time.

**Comment by alexpensify** [comment]
@Santhosh-Sellavel - could you please share feedback here on the proposals and other comments? Thanks!

**Comment by alexpensify** [comment]
@Santhosh-Sellavel - please keep me posted if you are unable to review this one. Thanks!

**Comment by Santhosh-Sellavel** [comment]
> When we generate the errors on the IOU report and chat report, generate them with the same microseconds since they are basically 1 single error.

How you are planning to do that?

**Comment by alexpensify** [comment]
Waiting for @tienifr feedback here.

**Comment by Santhosh-Sellavel** [comment]
@tienifr Always better to add a follow-up instead of always editing the first comment

**Comment by alexpensify** [comment]
@Santhosh-Sellavel - do we need more proposals here or wait for an updated proposal from @tienifr? Thanks for clarifying where we are at for this issue. Thanks!

**Comment by Santhosh-Sellavel** [comment]
Sorry, I forgot to post a review comment. Let's wait for other proposals.

**Comment by alexpensify** [comment]
Sounds like a plan! 

## Open for proposals here

**Comment by Santhosh-Sellavel** [comment]
I'm unavailable next week, Please assign a new C+ Issue here if required while I am away, thanks!

cc: @alexpensify

**Comment by DylanDylann** [comment]
I can take over as C+ contributor

**Comment by alexpensify** [comment]
Alright, @DylanDylann you are the new C+ here. Please keep us posted if one of these proposals will fix this issue. Thanks!

**Comment by alexpensify** [comment]
Also, @Santhosh-Sellavel - thank you for giving me this notice! We will keep moving forward here.

**Comment by DylanDylann** [comment]
@tienifr Why does this bug only happen on android?

**Comment by DylanDylann** [comment]
@tienifr  Small note

> The same approach listed above can be applied to many other scenarios where there's an error that occurs in multiple places but actually are the same error.

This point should be a bonus point in the section `What changes do you think we should make in order to solve the problem?`

It is not a alternative solution

**Comment by DylanDylann** [comment]
Can't reproduce anymore

**Comment by alexpensify** [comment]
@tienifr can you reproduce or do you agree with @DylanDylann? If yes, we will close. Thanks!

**Comment by alexpensify** [comment]
I'll need to test again then.

**Comment by DylanDylann** [comment]
I can reproduce on the latest main. Reviewing proposals

**Comment by alexpensify** [comment]
Thanks, @DylanDylann - I'm going to make this one `external` again.

**Comment by DylanDylann** [comment]
@tienifr Your idea looks good to me but it seems there have been many changes since you proposed. So could you post a branch for your proposal for testing?

> Update [clearReportActionErrors](https://github.com/Expensify/App/blob/b542031ff0fd0cf094f775dd1ad307bb3c86eb90/src/libs/actions/ReportActions.ts#L9) to support dismiss only error with specific key, because currently this function will remove all errors of the action, it's not correct when we just want to dismiss some related errors

For this point, Could you help to point out which case that there are multiple errors in the same reportAction

**Comment by alexpensify** [comment]
No update yet, if we don't get a response by the end of the week. On Monday, we will need to shop around for more proposals.

**Comment by DylanDylann** [comment]
@tienifr How about the second point [here](https://github.com/Expensify/App/issues/34189#issuecomment-1933731556) ?

> For this point, Could you help to point out which case that there are multiple errors in the same reportAction

**Comment by DylanDylann** [comment]
Reviewing

**Comment by DylanDylann** [comment]
@tienifr Please check this case

1. On the main device, create a request
2. On the second device, pay the above request
3. On the main device, create another request
4. Then we see a error in the main chat and IOU chat
5. Dismiss error in main chat
6. See that the error on IOU chat still remain

Required: we need to do step 2 and step 3 quickly

https://github.com/Expensify/App/assets/141406735/d30a7feb-6167-4759-b100-c729b7824590

**Comment by alexpensify** [comment]
Catching up from being OOO, looks like we are waiting for feedback on a proposal.

**Comment by alexpensify** [comment]
@tienifr keep us posted if we need to start looking for other proposals. Thanks!

**Comment by DylanDylann** [comment]
@alexpensify Should we double bounty to get more proposals?

**Comment by alexpensify** [comment]
Good call, let me review with the team.

**Comment by alexpensify** [comment]
Thanks, @tienifr for following up here!

**Comment by DylanDylann** [comment]
Update tomorrow (5/3)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by DylanDylann** [comment]
I still can reproduce on latest main

**Comment by DylanDylann** [comment]
@tienifr Thanks for your update. [Your proposal](https://github.com/Expensify/App/issues/34189#issuecomment-1884033143) looks good to me 

🎀 👀 🎀 C+ reviewed

**Comment by alexpensify** [comment]
PR is under review

**Comment by alexpensify** [comment]
PR is in review and tests

**Comment by alexpensify** [comment]
@DylanDylann and @tienifr - I had to create a new Job in Upwork: 

https://www.upwork.com/jobs/~019a5f69e7fb9d4402

Please apply and I can complete the payment process tomorrow. Thanks!

**Comment by alexpensify** [comment]
@tienifr and @DylanDylann - I've sent offers in Upwork. Please accept and I can continue the process. Thanks!

**Comment by alexpensify** [comment]
I was able to complete the payment process for @tienifr. I'm waiting for @DylanDylann to accept and I can carry on in Upwork.

**Comment by DylanDylann** [comment]
@alexpensify I accepted. Thanks

**Comment by alexpensify** [comment]
Thanks, all set here. Everyone has been paid in Upwork. Here is the payment summary: 

https://github.com/Expensify/App/issues/34189#issuecomment-2040358650

Upwork Link: 

https://www.upwork.com/jobs/~019a5f69e7fb9d4402
