### ISSUE TITLE
Language -  Back button redirects to the same page when modifying link with slashes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34184]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause  - Internal Team
**Slack conversation:**
 
**Issue found when executing PR** https://github.com/Expensify/App/pull/33444
## Action Performed:
1. Go to Settings > Preferences > Language
2. Add a few more slashes to the link like ..settings///preferences/language
3. Navigate to the edited link
4. Click back button on the RHP

## Expected Result:
User is redirected to the previous page (Preferences)

## Actual Result:
User is redirected to the same page (Language)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/557a76f8-9fa7-4f8c-aba0-ff6cfa19d831

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Removing this from the deploy blocker since it is a very specific flow that requires the user to add extra slashes to a link

**Comment by johnmlee101** [comment]
I honestly don't think this is worth fixing, because extra slashes is not part of the typical user flow
