### ISSUE TITLE
[$500] [HOLD for payment 2024-01-18] [HOLD for payment 2024-01-17] LHN - Clicking the (FAB) after opening the modal does not close the modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34185]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1: Sign in to the staging environment of Expensify.
2: Click on the Floating Action Button (FAB) to open the modal.
3: Click on the FAB again; the modal should close

## Expected Result:
After opening the modal, clicking on the FAB again should close the modal

## Actual Result:
The modal does not close after opening, even when clicking on the FAB again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b785f6e6-99e6-4f77-a79b-fca49f5497c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178ff077f70abe686</li>
        <li>Upwork Job ID: 1748053502135980032</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
This is a regression of this PR https://github.com/Expensify/App/pull/33247

**Comment by roryabraham** [comment]
[Fix](https://github.com/Expensify/App/pull/34188) is being CP'd to staging, cheers to @situchan for the quick fix

**Comment by situchan** [comment]
@marcochavezf can you please assign me and add `Bug` label? Thanks

**Comment by marcochavezf** [comment]
Hi @joekaufmanexpensify, could you handle the payment for @situchan for fixing this deploy blocker?

**Comment by joekaufmanexpensify** [comment]
@situchan $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
All set!
