### ISSUE TITLE
[$500] Android – IOU – Unable to download receipt while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34180]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.23-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open app.
2. Log in as the employee and enable offline mode
3. Navigate to a expense request conversation that has a receipt
4. Open the IOU details view.
5. Tap on the receipt > overflow menu > Download.

## Expected Result:
Image downloaded successfully

## Actual Result:
Nothing happens. Image downloads when go back online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/25f665e1-813d-49ff-be65-42d3ba3938e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012db8a8857fafeafb</li>
        <li>Upwork Job ID: 1744796469128253440</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by dragnoir** [comment]
Qhjoudl be fixed here https://github.com/Expensify/App/pull/34118
