### ISSUE TITLE
CRITICAL: Update logic for tryNewDot NVP to only be applied to users submitting to another person on a free plan

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34194]
# Problem

[Slack thread](https://expensify.slack.com/archives/C05DWUDHVK7/p1704833761343029)

We are currently setting tryNewDot NVP on accounts that are submitting to themselves, which is more of a track case and an audience we did not want to engage for wave 5. We correctly targeted audience submitting to others in our [original CQ](https://github.com/Expensify/Expensify/issues/326591), but since then we've been applying the NVP to accounts that are submitting to themselves.

# Solution

Update this logic for both scan and distance so that we're only prompting users on the free plan that are submitting to someone else to try NewDot.

**Comment by luacmartins** [comment]
We [decided](https://expensify.slack.com/archives/C05DWUDHVK7/p1704973844210879?thread_ts=1704833761.343029&cid=C05DWUDHVK7) to not move forward with this and just set the NVP for self-submitters too. Closing this issue since it's no longer necessary.
