### ISSUE TITLE
Distance - Cannot create distance expense with duplicate start/finish + duplicate stop

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. Star a distance request.
2. Input the same address for both the start and finish waypoints, e.g., "45 N Beach Rd, FL."
3. Click on "Add Stop"
4. Enter a different address, e.g., "Beach Access Path, Sunny Isles Beach, FL."
5. Click on "Add Stop" once again
6. Enter the same address as in step 4 to create two duplicate stops
7. Click on ''Next''button

## Expected Result:
User should be able to create a distance expense with a duplicate start/finish with a duplicate stop.

## Actual Result:
Unable to create a distance expense with a duplicate start/finish + duplicate stop.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/c659e858-e864-4a04-a434-0b56cd29c14f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
I am not sure this is a bug - there are two duplicate stops that are right next to each other

**Comment by thienlnam** [comment]
<img width="191" alt="Screenshot 2024-01-10 at 2 32 53 PM" src="https://github.com/Expensify/App/assets/30609178/7c12f840-1998-4c60-bb61-a9534f3a48b2">
Not being able to submit this seems expected - if you removed one of the middle stops it should work

**Comment by thienlnam** [comment]
Verified this works as intended on staging
