### ISSUE TITLE
When closing the Hybrid app switching to New Dot in the hybrid app reopens to the settings page of OldDot.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704498372067299

## Action Performed:

1. Open the Hybrid app
2. Switch to ND and close the app
3. Reopen the app

## Expected Result:
Should open ND 

## Actual Result:
reopens to the settings page of OldDot
 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
Working on repro'ing now.

**Comment by strepanier03** [comment]
Ughh, I have to do some setup to test this so I'll handle it Tuesday next week (OoO Monday)

**Comment by strepanier03** [comment]
Having a hard time testing this one, Google on my phone is being difficult but I'm troubleshooting. Will update tomorrow.

**Comment by strepanier03** [comment]
Haven't been able to test this, I'm struggling to get the Hybrid app on my phone.

**Comment by strepanier03** [comment]
All right, found a second device I can use for testing the Hybrid app. It's charging and then I'll work on getting it set up for testing today. Update coming later today.

**Comment by strepanier03** [comment]
Hmmm, I've been having a hard time repro'ing this.

**Comment by strepanier03** [comment]
@quinthar - Can you still repro this issue?

**Comment by strepanier03** [comment]
Fresh attempt at recreating this and if I still can't I'll close for now.

**Comment by strepanier03** [comment]
Okay, attempted again to repro this and can't. Closing it out for now with needs repro on it.
