### ISSUE TITLE
[HOLD for payment 2024-02-07] App CallStack Audit: Enable ProGuard to optimize APK Size

### ISSUE THREAD

**Issue by hurali97** [Expensify/App#34222]
## Description:

This is a part of implementation phase from **Metric: APK Size in MB**. The parent issue can be found here https://github.com/Expensify/App/issues/33070. 
The idea is to enable minification using ProGuard and remove unused resources.

@Julesssss -- also necessary for code obfuscation

## Proposal

https://github.com/Expensify/App/issues/33070#issuecomment-1875099319

**Comment by hurali97** [comment]
@mountiny Can we assign this issue to me? I don't have rights to assign OR update the labels. Would be cool if you can also update the label to Task ?

**Comment by Julesssss** [comment]
@tgolen feel free to reassign, but I had already reviewed and tested this PR

**Comment by slafortune** [comment]
Contributor: @hurali97 is from an agency-contributor and not due payment
C+:  @shubham1206agra paid $500 via Upwork [(LINK)](https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/36279079) PD!
