### ISSUE TITLE
[$500] Notifications - Notification was not received when IOU creator set the Description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be signed in account A on the main testing device and account B on the secondary device or browser
1. As the secondary user (B) - Request money to the main user (do not write the description)
2. Navigate to the IOU details page and send any message
3. Navigate to other conversation
4. As a secondary user set the Description

## Expected Result:
User should receive the notification on the main testing device

## Actual Result:
Notification was not received

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3f0eece5-d7e1-4de9-90a3-df2b69b66039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116b0958960c2b31e</li>
        <li>Upwork Job ID: 1745077686184640512</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
Hey @lanitochka17, are you receiving notifications when you don't perform step 4?

**Comment by Julesssss** [comment]
Also would you mind testing Android/ or iOS? I have an [issue](https://github.com/Expensify/App/issues/32656) for broken IOU notifications, but I'm not sure whether it is the same as this issue or not.

**Comment by cristipaval** [comment]
@Julesssss, have you done any investigation here?

**Comment by cristipaval** [comment]
I did some investigation, and it is an internal issue.

The problem is that [here](https://github.com/Expensify/Web-Expensify/blob/5431b0af0cce0f6e938150fe0d0b317cf5d9ab08/lib/ReportUtils.php#L2373), the account that should be notified has the notification preference for the transaction thread set to `hidden`.

**Comment by cristipaval** [comment]
@Julesssss, [my PR](https://github.com/Expensify/Web-Expensify/pull/40393) couldn't be QAed because this issue already exists in production. I can also take this over to ensure that my PR works after fixing this.

**Comment by Julesssss** [comment]
Hey @cristipaval yeah feel free to takeover, I think my other issue is related to mobile and Airship specifically. But please let me know if you think that is also working.

**Comment by cristipaval** [comment]
I wonder if this is something related to the [fire](https://expensify.enterprise.slack.com/archives/C06DZPADL2U) that on 10th Jan, this month

**Comment by conorpendergrast** [comment]
@cristipaval Have you tried to reproduce since then, in case it was that fire?

**Comment by cristipaval** [comment]
This is still reproducible. Continuing my investigation.

**Comment by cristipaval** [comment]
it seems that this is intentional, it was implemented as part of wave6, [here](https://github.com/Expensify/Expensify/issues/326093)'s the issue.
So the expense/transaction reports have the `hidden` notification preference by default.
