### ISSUE TITLE
[HOLD for payment 2024-08-02] [Wave Collect] [Ideal Nav] Improve "Hmm... it's not there" being duplicated across two content areas

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#34234]
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1704833741725849).

**Problem**
With the new ideal navigation layout, we'll run into an instance where the "page not found" illustration is duplicated across two content areas on web/desktop. For example, when you try to access a workspace that has been deleted via a URL link to its settings: 

![Screenshot 2024-01-09 at 9 44 53 PM](https://github.com/Expensify/App/assets/16232057/37544c96-8702-4cbe-9556-1667ae3e753e)

**Solution**
Instead of showing it twice, we'll instead: 

- Use a full page instead
- Clicking the back caret brings you back to the screen which you were at when you tried to access the missing workspace.
- If you don’t have a previous screen to return to, we return to the Chats tab of the “All” view.

![image](https://github.com/Expensify/App/assets/2319350/c18c452b-b99e-4bdf-a45a-343e76d1511c)

CC: @hayata-suenaga @mountiny @shawnborton @JmillsExpensify @kosmydel @adamgrzybowski @s77rt 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by hayata-suenaga** [comment]
looking at the discussion in the linked Slack thread

**Comment by shawnborton** [comment]
This is what it looks like at full screen btw:
![image](https://github.com/Expensify/App/assets/2319350/c18c452b-b99e-4bdf-a45a-343e76d1511c)

**Comment by kosmydel** [comment]
Hey, here is a preview of what it looks like.

<img width="1512" alt="Screenshot 2024-01-15 at 10 20 59" src="https://github.com/Expensify/App/assets/104823336/2f3c24b9-1fc6-4873-9923-af234482b49e">

**Comment by shawnborton** [comment]
That seems good to me!

**Comment by trjExpensify** [comment]
Nice! So I think we can take this off planning. @kosmydel, are you taking care of this so I can assign you? Also if so, can you link the PR to this issue? Thanks!

**Comment by shawnborton** [comment]
Not overdue, I think we're still making progress here?

**Comment by hayata-suenaga** [comment]
@kosmydel Please also refer to [this regression](https://github.com/Expensify/App/issues/35623) and check that the issue reported there is also fixed with your PR 🙇

**Comment by kosmydel** [comment]
Hey, I started working on this issue today. I'm trying to find a solution to cover all cases in a clean way. However, it looks like a more complex problem, especially for RHP modals.

**Comment by kosmydel** [comment]
@hayata-suenaga I've prepared a very early draft of the PR. I still have to test it thoroughly.

---

I found a one issue which makes it impossible to test it:
1. Log out
2. Go to some WS link, e.g. `https://staging.new.expensify.com/workspace/adsasddssad/rateandunit` (doesn't matter if policy exist or not)
3. Log in
4. Infinity loading

**Workaround:**
Go to the chat list, wait until all reports are loaded, try to open the link again.

Loading the Onyx state doesn't work from deeplinks at all.

**Comment by kosmydel** [comment]
@hayata-suenaga should I complete the checklist and open the PR anyway? Or should I wait until the reported issue is solved?

**Comment by hayata-suenaga** [comment]
you can open the PR 👍

**Comment by trjExpensify** [comment]
Conflicts [resolved yesterday,](https://github.com/Expensify/App/pull/36409#issuecomment-1964311995) over to @situchan to re-review!

**Comment by trjExpensify** [comment]
Commented in the PR and switched back to weekly.

**Comment by trjExpensify** [comment]
PR merged.

**Comment by kosmydel** [comment]
I see that the PR got reverted. I will prepare a new version, but now I'm focusing on the new architecture issues. We should also probably wait for https://github.com/Expensify/App/pull/40598 to be merged, as it collides a bit with my changes.

FYI: I'm OOO next week.

**Comment by kosmydel** [comment]
This one is being reviewed by @situchan.

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @situchan for the PR review

Offer sent.

**Comment by situchan** [comment]
Can this be 500?

reasoning:
- super old issue (before price change)
- size of PR which fixes multiple issues at once
- required lots of testing as seen in [QA Steps of PR](https://github.com/Expensify/App/pull/41665)

**Comment by trjExpensify** [comment]
>super old issue (before price change)

Fair. Can you accept the offer so I can pay it though?

**Comment by situchan** [comment]
Not overdue

**Comment by trjExpensify** [comment]
Paid, closing!
