### ISSUE TITLE
Expense - "To" field appears with delay in confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Click + > Request money > Distance
3. Enter addresses
4. Proceed to confirmation page

## Expected Result:
Content will not appear with delay

## Actual Result:
"To" field shows up late in confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6cab906f-92e8-46e0-bded-f172480c41fd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment]
@hurali97 just FYI if this is a regression from your changes

**Comment by johnmlee101** [comment]
We reverted this https://github.com/Expensify/App/pull/31354#issuecomment-1885349544

**Comment by situchan** [comment]
The fix reached staging. We can close this after QA pass

**Comment by mountiny** [comment]
This is done
