### ISSUE TITLE
[HOLD for payment 2024-01-22] [HOLD for payment 2024-01-18]  IOU - App does not scroll down to show the latest message when editing expense request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Create a manual request.
3. Open details page.
4. Edit any field.

## Expected Result:
The app scrolls down to show the latest message when editing expense request.

## Actual Result:
The app does not scroll down to show the latest message when editing expense request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f60f84f5-799f-40a5-9a96-6e9713650699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
Alright assigning you guys to handle this

**Comment by arosiclair** [comment]
> confirm that bringing `autoscrollToTopThreshold` back is fixing that issue
> #34244

Please link that PR to this issue!

**Comment by roryabraham** [comment]
Should be fixed in https://github.com/Expensify/App/pull/34244

**Comment by roryabraham** [comment]
This is checked off on the checklist. Going to close this out

**Comment by situchan** [comment]
@roryabraham can I get payment for [PR](https://github.com/Expensify/App/pull/34244) review?

**Comment by roryabraham** [comment]
Yes, it looks like we need to issue a $500 payment to @situchan tor a C+ review here.

**Comment by roryabraham** [comment]
Payment is ready to issue immediately, thanks for commenting @situchan, apologies for missing this.

**Comment by anmurali** [comment]
@situchan - Offer is [here](https://www.upwork.com/nx/wm/offer/100791358)

**Comment by anmurali** [comment]
Paid!
