### ISSUE TITLE
Timezone - App detects incorrect timezone when automatic timezone is enabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Device timezone is set to automatic
- App timezone is set to automatic
- User lives in Malaysia with GMT+8 (Asia/Kuala_Lumpur) timezone
1. Go to Settings > Profile > Timezone

## Expected Result:
The correct timezone is detected

## Actual Result:
The incorrect timezone is detected
User lives in Malaysia with GMT+8 (Asia/Kuala_Lumpur) timezone, while app shows Asia/Singapore as the automatic timezone, where Singapore is a neigbor of Malaysia

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6337781_1704899025363!bandicam_2024-01-10_18-36-36-107__1_](https://github.com/Expensify/App/assets/78819774/4d3da6f6-4a3e-468b-befa-666260623da1)

https://github.com/Expensify/App/assets/78819774/1c4a5268-8917-40f5-96b2-5a23a09b98f0

![Bug6337781_1704899025367!IMG_1583](https://github.com/Expensify/App/assets/78819774/5769f851-bf50-4a6a-9529-b927aa97cb90)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
Not a big deal tbh. Both have same timezone.

**Comment by situchan** [comment]
This is not new bug - https://github.com/Expensify/App/pull/31074#issuecomment-1875290384

**Comment by situchan** [comment]
@tienifr please check this

**Comment by situchan** [comment]
ok I will defer to @marcochavezf whether to treat this as bug or not. At least not deploy blocker

**Comment by marcochavezf** [comment]
Thanks for the investigation @tienifr, I suppose the change is because of the new polyfill, correct? Also, given the reason [here](https://github.com/Expensify/App/issues/34247#issuecomment-1885367056) and the priorities I'm inclined to close it, we can re-open it if there other impacts of the introduced polyfill.
