### ISSUE TITLE
[$500] Regression: SHIFT+ENTER in message composer is NOT adding a new line

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#34249]
# Problem

When you press SHIFT+ENTER in the message composer, a new line should be added to the message, but it is not doing that.

Only happening on staging

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a447f5f0603d050</li>
        <li>Upwork Job ID: 1745109902462763008</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by AndrewGable** [comment]
What client? Works fine for me on staging web?


https://github.com/Expensify/App/assets/2838819/1ff895ca-6072-4e84-a038-109c721d0cde

**Comment by AndrewGable** [comment]
Cannot reproduce on staging desktop either

**Comment by iwiznia** [comment]
> What client? Works fine for me on staging web?

Really? Staging web for me does not work!

**Comment by iwiznia** [comment]
So not sure what's going on but I definitely can reproduce this on web staging

**Comment by iwiznia** [comment]
lol I reloaded and it worked 😂
