### ISSUE TITLE
 IOU - Category page renders slowly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0 
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Workspace report
2. Click on '+' > click on 'Request money' > click on 'Distance' tab
3. Enter start & finish point > click on 'Next' > click on 'Category'

## Expected Result:
Category page should render fast

## Actual Result:
Category page renders slowly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b37026eb-535f-4edd-a406-8870f2f7fb5e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
Weird, pinged 2 people on Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1704902763223599?thread_ts=1704902334.122429&cid=C01GTK53T8Q

**Comment by flodnv** [comment]
It was caused by https://github.com/Expensify/App/pull/31354, we're going to revert it

**Comment by flodnv** [comment]
@mountiny said he's taking over, I would just revert the PR

**Comment by mountiny** [comment]
I have prepared the revert here https://github.com/Expensify/App/pull/34267

**Comment by mountiny** [comment]
Asked QA to re test

**Comment by mountiny** [comment]
fixed  https://expensify.slack.com/archives/C9YU7BX5M/p1704916587672439?thread_ts=1704913316.653949&cid=C9YU7BX5M
