### ISSUE TITLE
Task - Error shows up when creating task via [] @mention <task name> pathway

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34250]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33428
## Action Performed:
1. Go to an empty 1:1 DM
2. Send [] @mention <task name> where @mention is not the DM user

## Expected Result:
The task is created and assigned to the mentioned user.

## Actual Result:
The task is not created. Error shows up - Unexpected error create task, please try again later

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/00b96f67-ad35-4118-86b6-ace461cbbdef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
Assigning @thienlnam since he's been working on this with the contributors on this functionality

But I was not able to simulate this error both on DMs and group chats when inviting people that were not participants, @lanitochka17

**Comment by danieldoglas** [comment]
I'm not sure if this is the desired behavior, but:

- I had a chat with user 1
- created a task using the md syntax for user 2
- The task was created, assigned to user 2, but also shared with user 1
- The task was listed in both 1:1 chats I had with user 1 and user 2

@thienlnam I'll let you chime in from there!

**Comment by iwiznia** [comment]
Following because I was testing with him and I thought the behavior was weird/wrong. IMO the user2 should NOT see the task in the DM report, they should only see it in the LHN.

**Comment by thienlnam** [comment]
> I'm not sure if this is the desired behavior, but:
I had a chat with user 1
created a task using the md syntax for user 2
The task was created, assigned to user 2, but also shared with user 1
The task was listed in both 1:1 chats I had with user 1 and user 2


Yes this is correct behavior - so let's take User A and User B
- You're chatting in the DM with User A
- In that DM, you create a task for User B ([] @UserB task)
- In the DM with User B, you get linked to the task that was created in the DM with User B

**Comment by thienlnam** [comment]
I tested this and this seems to be working fine for me - not able to get the failure as mentioned and neither can Daniel so going to remove the blocker

**Comment by thienlnam** [comment]
It did not, but you're taking an action that requires something of someone else.
I assigned the task to you specifically, and so it will show up in the DM between us even if it was created somewhere else.

Side note - going to be closing this issue since this bug doesn't seem to be happening. Happy to talk this through more in slack if needed
