### ISSUE TITLE
 IOU - User taken to camera view on refreshing page after adding receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**
 
**Issue found when executing PR** https://github.com/Expensify/App/pull/33562
## Action Performed:
1. Login to ND with gmail account
2. Open a chat
3. Create a manual request thought the chat plus icon (not the FAB)
4. Enter an amount and Next
5. Click the three dots on the top, and attach a receipt
6. Refresh the page in this step

## Expected Result:
The page will go back to the first step, auto-filled with the previous amount.

## Actual Result:
User taken back to camera view asking for permissions again on refreshing page after adding receipt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/6c17a4f3-4708-47ce-a31c-140a68d7ab38

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
This seems like new expected behavior after #33562.
@cristipaval can you please confirm?

**Comment by thienlnam** [comment]
This does look intended
