### ISSUE TITLE
[$500] Web - Getting ERR_FILE_NOT_FOUND error messages when refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to a chat
2. From the composers + button start a manual request
3. Attach a receipt from the "three dots" button (don't submit)
4. Refresh the page

## Expected Result:
There shouldn't be any error messages.

## Actual Result:
Getting ERR_FILE_NOT_FOUND error messages when refreshing the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/963d0d18-47a2-4925-904f-35f1d38508b0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb262444834c29d7</li>
        <li>Upwork Job ID: 1745130003957616640</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Getting ERR_FILE_NOT_FOUND error messages when refreshing the page

### What is the root cause of that problem?
We are navigating the user to start step when we can't find the receipt after the page is reloaded 
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/pages/iou/request/step/IOURequestStepConfirmation.js#L148-L149
### What changes do you think we should make in order to solve the problem?

we should only do that if the tranaction amount is 0
```
        if (transaction.amount !== 0) return;

```
### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
I'm not sure if this is a bug

**Comment by BhuvaneshPatil** [comment]
Yes I think that too as well, because of browser's limitations

**Comment by garrettmknight** [comment]
@kbecciv did this come up from an explicit test? I can imagine it's a browser limitation vs. something that worked previously and the specific test would help me check.

**Comment by kbecciv** [comment]
@garrettmknight Issue found when executing PR  https://github.com/Expensify/App/pull/33562

**Comment by garrettmknight** [comment]
Reopening for me to look into the PR
