### ISSUE TITLE
 IOU - There is a delay in displaying the members involved in a split bill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34271]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a group chat
2. Go to the Split bill
3. Enter the amount and proceed next
4. Notice members section displayed after a second

## Expected Result:
There should not be delay in displaying the members involved in a split bill

## Actual Result:
There is a delay in displaying the members involved in a split bill

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3707f294-688b-4286-aa49-89a974a39777

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
fixed in #34267 which is being CP'ed

**Comment by amyevans** [comment]
Perfect, will keep an eye on [the build](https://github.com/Expensify/App/actions/runs/7478912094)

**Comment by amyevans** [comment]
@lanitochka17 could you retest on the latest staging build please? (`1.4.24-1`)

**Comment by amyevans** [comment]
Asked in #qa as well for a retest. I can't repro but would love some additional confirmation 😄

**Comment by mountiny** [comment]
Reverted https://github.com/Expensify/App/issues/33596#issuecomment-1886516193 so we can close now

**Comment by amyevans** [comment]
Thanks! To close the loop QA also confirmed it's fixed after a retest: https://expensify.slack.com/archives/C9YU7BX5M/p1704936138065639?thread_ts=1704924266.002129&cid=C9YU7BX5M
