### ISSUE TITLE
Web - BA - On Test transactions page letters can be entered in value fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to Settings > Workspaces > Select a workspace > Bank account > Connect manually
4. Go trough the add bank account flow using the testing credentials until you reach the Test transactions page
5. Try to enter any letter on the value fields.

## Expected Result:
User should not be able to enter any letters in the value fields

## Actual Result:
User is able to enter letters in value fields

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/844668d3-ccb5-4a64-b4e9-025f48d2feee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Looking at this now

**Comment by luacmartins** [comment]
That's also the behavior on prod and is the expected behavior. We don't restrict users input, but we do validate it. This happens for all inputs really, e.g. routing number, account number, etc and we show the error if the user moves to the next input or tries to submit the form. Gonna close this issue.
