### ISSUE TITLE
[$500] Search - LHN displays search results when searching for contacts in New Chat modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34281]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with HT account (so that it loads slower during login)
2. White the app is loading, open new chat modal via CMD+SHIFT+K
3. Search for a user that has IOU, group chat, other history

## Expected Result:
While the search results appear in New Chat modal, LHN in the background should display the chats

## Actual Result:
White the search results appear in New Chat modal, LHN in the background displays search results too which include IOU reports, group chats etc

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f0afb221-16df-475d-bb91-cf734fb38a8f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d4b0c23b2adb57d</li>
        <li>Upwork Job ID: 1745149847483092992</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Waiting on proposals.

**Comment by lschurr** [comment]
Still waiting on proposals.

**Comment by lschurr** [comment]
@c3024 are you able to reproduce this bug?

**Comment by lschurr** [comment]
Closing.
