### ISSUE TITLE
[$500] Android - Workspace - Workspace created in offline mode can not be deleted in online mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create workspace in offline mode
2. Go back online
3. Delete the created workspace
4. Navigate to LHN
5. Go to Settings> Workspace

## Expected Result:
Deleted Workspace should not be present

## Actual Result:
Workspace created in offline mode can not be deleted in online mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1a2746b0-12e2-4296-a63a-ca4eb76dbf72

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc72f453961ec0d1</li>
        <li>Upwork Job ID: 1745185664474599424</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by codebycarlos** [comment]
Sorry, unable to reproduce on **v1.4.24-2 Develop**.

**Comment by trjExpensify** [comment]
@lanitochka17, the video reproduction shows: 

1. Member goes offline
2. Creates a workspace
3. Goes back online
4. Deletes the workspace
5. The workspace disappears from the list on the `Workspaces` page and thus the empty state is revealed

That's as for as the video goes, but it's what I would expect? Are you saying the deleted workspace reappears somewhere? Can you retest, or add a complete video? Thanks!

**Comment by trjExpensify** [comment]
Feel free to comment and reopen accordingly!
