### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Display Name - User can save Expensify and Concierge as a last name while error is thrown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34304]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Settings > Profile > Display Name
2. Enter either 'Expensify' or 'Concierge' as the last name
3. Click on 'Save' button

## Expected Result:
User shouldn't be able to save the 'Expensify' or 'Concierge' as last name

## Actual Result:
User is able to save the 'Expensify' or 'Concierge' as last name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d00d8e41-df35-42b9-8ffa-1fd94751d558

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afa29712aeb0580b</li>
        <li>Upwork Job ID: 1745234409296494592</li>
        <li>Last Price Increase: 2024-01-18</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28119205</li>
<li>dukenv0307 | Contributor | 28119206</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Display Name - User can save Expensify and Concierge as a last name while error is thrown


### What is the root cause of that problem?
 We dont check if the last name is one of the reserved words similar to first name 
https://github.com/Expensify/App/blob/9208c95e3c9b375897e7133696ffcdb07b67fb74/src/pages/settings/Profile/DisplayNamePage.js#L63-L65

### What changes do you think we should make in order to solve the problem?
 we need to add  a validation here for the last name as well

**Comment by puneetlath** [comment]
Does the API call fail? If not, I don't think it's necessary.

**Comment by puneetlath** [comment]
Ok got it! In that case, yes, I think we should have front-end validation for that.

**Comment by puneetlath** [comment]
Hm, I'm not eager to do anything then if it requires a back-end update. We can solve it if/when it becomes a real problem.

**Comment by zanyrenney** [comment]
That's fair @dukenv0307 - @puneetlath what do you think?

**Comment by zanyrenney** [comment]
bump @puneetlath for your thoughts please?

**Comment by zanyrenney** [comment]
have sent @puneetlath a DM asking him to take a look.

**Comment by zanyrenney** [comment]
After discussing with @puneetlath in DM, he agreed that we should fix this.

I think we should just focus on the front-end fix for now though @dukenv0307 - please keep pressing ahead if @fedirjh agrees your proposal is preferable.

**Comment by Julesssss** [comment]
Sounds good

**Comment by zanyrenney** [comment]
Payment summary

@fedirjh requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28119205) (Reviewer) - AWAITING PAYMENT, HAS NOT ACCEPTED UW OFFER $500
@dukenv0307 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/28119206) (Contributor) PAID $500
