### ISSUE TITLE
[$500] CRITICAL: Unable to join rooms immediately after invited

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#34308]
**Problem:**
The steps to reproduce are:
1. Alice creates a workspace
2. Alice creates a room named #social
3. Alice invites Bob to the workspace
4. Alice gives Bob a direct link to #social
5. Bob clicks the link to #social
6. The link says he doesn't have access
7. Bob signs out and back in
8. Now the link works for Bob

**Solution:**
I bet there's some kind of bug somewhere on the client that assumes Bob doesn't have access because it hasn't been shared with him yet.  I would think that when you try to switch to a room, we call `OpenReport` even if the client doesn't think you have access.

/cc @tylerkaraszewski who experienced this
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f82ef1f866e4cce</li>
        <li>Upwork Job ID: 1745265013381070848</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by c3024** [comment]
> **Problem:** The steps to reproduce are:
> 
> 1. Alice creates a workspace
> 2. Alice creates a room named #social
> 3. Alice invites Bob to the workspace

After this step 3, Bob does not even see the workspace chat or the announce room for the workspace.



https://github.com/Expensify/App/assets/102477862/3e5f48fd-4ffc-43cd-b2fe-d2a3fe59a4c4


Without step 2 as well, the same thing happens.


https://github.com/Expensify/App/assets/102477862/85c64407-82bf-42de-b524-d5ddf5babd1a


I think there is some issue with backend not sending the right workspace data or resetting the sent data.

**Comment by mung4i** [comment]
I tried multiple times to reproduce this issue and I couldn't run into the issue.

Maybe there are some steps missing?

Steps attempted

1. Create a room
2. Invite second user to room
3. Copy share code and paste
4. Paste code in user 2's account... works

Note. In video I tried to paste code before invite but this was my 3rd test. Also announcement visible after invite.


https://github.com/Expensify/App/assets/25161540/c3e8068e-363f-4d5f-ada0-f75c46d3ed4c

**Comment by marcaaron** [comment]
I also can't reproduce this. Maybe it was a blip. 

@c3024 can you try testing again?

**Comment by c3024** [comment]
Yes, It is not reproducible anymore.

**Comment by quinthar** [comment]
@mung4i these are the wrong reproduction steps:

1. Create a room
2. Invite second user to room
3. Copy share code for second user
4. Paste code in user 2's account... works

Please follow the actual steps outlined in the original post:

1. Alice creates a workspace
2. Alice creates a room named #social
3. Alice invites Bob to the workspace
4. Alice gives Bob a direct link to #social
5. Bob clicks the link to #social
6. The link says he doesn't have access
7. Bob signs out and back in
8. Now the link works for Bob

**Comment by c3024** [comment]
>Bob clicks the link to #social
The link says he doesn't have access

Bob gets access on clicking the link. The bug is not reproducible anymore.

https://github.com/Expensify/App/assets/102477862/75067235-7a3d-4d8d-aa8a-8a47a13f0a7f

**Comment by quinthar** [comment]
Huh.  Well, glad it went away, sorry for the inconvenience!!
