### ISSUE TITLE
[$500] Tapping on " Go back to homepage" user directed to conversation page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34318]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Paste the link in compose - https://staging.new.expensify.com/anything

4.Send the message
5.Tap on the link
6.In hhm not here page, tap on " Go back to homepage"

## Expected Result:
In hhm not here page, tapping on " Go back to homepage" user must be directed to home page.

## Actual Result:
In hhm not here page, tapping on " Go back to homepage" user is directed to conversation page instead of home page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/f9968546-52b0-4286-8748-5895a2bbf4ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174a0d1b4d61ad246</li>
        <li>Upwork Job ID: 1745353387875889152</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by getusha** [comment]
I don't think this is worth fixing, looks pretty minor to me.
Pulling internal engineer to confirm whether we should fix this or not
🎀 👀 🎀

**Comment by situchan** [comment]
We can close this. [Dupe issue](https://github.com/Expensify/App/issues/32856) was closed already
