### ISSUE TITLE
New users not receiving responses from Concierge 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#34310]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.23-4
**Reproducible in staging?:** Production 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [michaelconorward+test3344445@googlemail.com](mailto:michaelconorward+test3344445@googlemail.com)
**Issue reported by:** @MitchExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704944178816099

## Action Performed:

1. Sign up on [expensify.com](http://expensify.com/) via a new public domain address
2. Send a message to Concierge (Do not refresh!)
3. Receive a message from Concierge (Confirm via the Concierge Tool)

## Expected Result:
See Concierge's response in NewDot

## Actual Result:
Concierge's response is not visible in NewDot

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/36425901/f575462f-7ca8-496e-89a3-7e0c782cf1df)

![image](https://github.com/Expensify/App/assets/36425901/11a59d18-cb05-4db6-bdb1-7ca72179a858)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f06342163ae43b75</li>
        <li>Upwork Job ID: 1745289546553430016</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
@francoisl or @marcaaron Do you have bandwidth to check this out?

**Comment by marcaaron** [comment]
@MitchExpensify I am 99% this was temporary and caused by yesterday's fire. Gonna re-test though just to be sure there is nothing else happening here.

**Comment by marcaaron** [comment]
Doesn't seem like this is happening anymore. Please reopen if you can still repro!

**Comment by matijaerceg** [comment]
new user; not getting any response from concierge on website nor app
