### ISSUE TITLE
[$500] "Uncaught ReferenceError" error when running given code

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34314]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Issue found when executing #32164
**Version Number:** 1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal
**Slack conversation:** 

## Action Performed:
1. Log in with an expensifail account
2. Navigate to any 1:1 chat
3. Run "Onyx.set('onyxUpdatesFromServer', {INVALID_FORMAT_FROM_LIST_BELOW});" code in the browser console
4. Run the "useEffect" code found under the Card section in the PR

## Expected Result:
Console should give the "[OnyxUpdateManager] Invalid format found for updates, cleaning and unpausing the queue" response.
For the Card part, it should add an Expensify card.

## Actual Result:
"VM27:1 Uncaught ReferenceError: Onyx is not defined at <anonymous>:1:1" console error when running the given "Onyx.set" code.
Expensify card isn't added.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/679c79b9-2e55-458c-b35c-90d3da41d7e9

https://github.com/Expensify/App/assets/43996225/f5eb9a2c-686b-4bdc-8309-e2ebf4f46533

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0157611a16e98882e2</li>
        <li>Upwork Job ID: 1745348370309632000</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
I don't think there is a bug here - you can't set onyx like this on prod
