### ISSUE TITLE
[TS migration] Setup Typescript in react-native-onyx

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#34334]
# Typescript migration (react-native-onyx)
Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

## Files
N/A

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by brunovjk** [comment]
I am happy to work on this issue

**Comment by blazejkustra** [comment]
Starting to work on it today

**Comment by blazejkustra** [comment]
We managed to merge the PR last week, closing.
