### ISSUE TITLE
[TS migration] Migrate remaining utils to Typescript (react-native-onyx)

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#34342]
# Typescript migration (react-native-onyx)
Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

## Files
`lib/batch.js`
`lib/batch.native.js`
`lib/compose.js` (remove)
`lib/createDeferredTask.js`
`lib/fastMerge.js`
`lib/Logger.js`
`lib/Str.js`
`lib/SyncQueue.js`

**Comment by mountiny** [comment]
Will be handled by agencies

**Comment by alexpensify** [comment]
Thank you for the update!

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
WIP [PR](https://github.com/Expensify/react-native-onyx/pull/474) is up!

**Comment by blazejkustra** [comment]
We can close this out, no payment needed.
