### ISSUE TITLE
[$500] Chat - Started & pinned chat via 1st device isn't shown in LHN after getting online with 2nd device

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34345]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisites: Login with same account to 2 different devices ( in example mWeb and web)
1. In the main testing device (mWeb), Navigate to Settings > Preferences
2. Disable the internet connection in the device
3. Change the Priority mode in the device from Most recent to Focus
4. Navigate to LHN
5. In the second device (Web) start a chat with another account and pin the chat
6. In the main testing device (mWeb), enable internet connection
7. Observe Priority now Focus on both devices
8. Verify if the pinned chat by the second device (Web) exists in LHN of the first device (mWeb)

## Expected Result:
Started and pinned chat via first device should be shown in LHN after getting online at least after refreshing the page

## Actual Result:
Only Concierge chat is shown in LHN. Started and pinned chat via first device is not shown (even after refreshing the page) in LHN after getting online with second device unless start the chat again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/4afc5b9f-c36b-40cc-bdb4-72777f7771d1)

![image](https://github.com/Expensify/App/assets/93399543/98009600-14ba-42e4-88f4-862888496b84)

https://github.com/Expensify/App/assets/93399543/a9ba7adc-42d1-411c-9b2f-2c820e833c9c

https://github.com/Expensify/App/assets/93399543/a43065d7-8735-4cc5-852a-fedb3e072f69

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f40cfcafa5fe9ef7</li>
        <li>Upwork Job ID: 1745427651344273408</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
This looks like a backend issue
We have `GetMissingOnyxMessages` API for receiving missed onyx updates, but this API returns data as the below figure
![image](https://github.com/Expensify/App/assets/126839717/4fee5dc5-a1b9-42ab-a9e6-c7dbb987f2b5)

I'm not sure why this type of data is returned. All those data shouldn't be in `onyxData`?

**Comment by michaelhaxhiu** [comment]
I understand the bug report, however I'm not sure if it's `internal` or `external` in terms of the scope of the problem. If it relates to onyx data, that should be `internal` and we should return pinned chats the same between devices like web vs mobile (assuming it's the same account logged into either).

**Comment by michaelhaxhiu** [comment]
@pecanoro do you agree with @s-alves10 in terms of this GH being switched to `internal`? I could use the opinion of someone more familiar with the backend code here!

**Comment by pecanoro** [comment]
It's working fine for me, but I still find it pretty odd we are sending the updates outside onyxData. I am going to check internally in Slack.

![image](https://github.com/Expensify/App/assets/6474442/3799141e-a8ba-4fa0-aa77-545d02d1b21a)

**Comment by pecanoro** [comment]
@MelvinBot I just commented, relax with the Overdue
