### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] iOS - Request money - Capture button overlaps with navigation bar in Add receipt modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34347]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM > + > Request money > Manual.
2. Proceed to confirmation page.
3. Tap 3-dot menu > Add receipt.

## Expected Result:
The capture button does not overlap with the navigation bar.

## Actual Result:
The capture button overlaps slightly with the navigation bar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/02ccd0c7-a70d-4d0a-bac9-f1397e9b7e1a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128bc9905dd912e60</li>
        <li>Upwork Job ID: 1745431054881275904</li>
        <li>Last Price Increase: 2024-01-18</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28118466</li>
<li>mkhutornyi | Contributor | 28118467</li>
</ul></li>
    </ul>
</details>

**Comment by TotheSky0710** [comment]
That is not correct!

**Comment by greg-schroeder** [comment]
bump for @stitesExpensify to confirm C assignment :)

**Comment by greg-schroeder** [comment]
Merged, awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment]
Ready to go for payment tomorrow, as both offers are accepted.

bump @Ollyws for the checklist and then we can close this out!

**Comment by greg-schroeder** [comment]
Paid, added regression test
