### ISSUE TITLE
[TS migration] Migrate ‘metrics’ catalog to Typescript (react-native-onyx)

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#34341]
# Typescript migration (react-native-onyx)
Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

## Files
`lib/metrics`
`lib/MDTable.js`

**Comment by mountiny** [comment]
Will be handled by agencies

**Comment by blazejkustra** [comment]
@RohanSasne This migration will be handled by agencies meaning Callstack or SWM, sorry!

**Comment by blazejkustra** [comment]
Let's make it weekly @mountiny (same [here](https://github.com/Expensify/App/issues/34340) & [here](https://github.com/Expensify/App/issues/34344#issuecomment-1898894491))

**Comment by BartoszGrajdek** [comment]
Hey! I'm Bartosz from Software Mansion and I would like to work on this task.

**Comment by BartoszGrajdek** [comment]
Could you fill me in? What was the last bz post about? 😄 @adelekennedy

**Comment by hayata-suenaga** [comment]
@adelekennedy are you referring to the merge freeze for the earnings call?

**Comment by hayata-suenaga** [comment]
@BartoszGrajdek I think Adele was referring to the merge freeze that was in effect last week. We can move forward to the PR now that the freeze is over 👍
