### ISSUE TITLE
[TS migration] Migrate `withOnyx.js` to Typescript (react-native-onyx)

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#34343]
# Typescript migration (react-native-onyx)
Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

## Files
`lib/withOnyx.js`
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3b37862b8e301f2</li>
        <li>Upwork Job ID: 1755607966741164032</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by brunovjk** [comment]
I am happy to work on this issue

**Comment by twisterdotcom** [comment]
@blazejkustra and @fabioh8010 - you're working on this right?

**Comment by blazejkustra** [comment]
I first have to [setup TS in onyx](https://github.com/Expensify/App/issues/34334), I'm working on it today.

**Comment by twisterdotcom** [comment]
How are we going @blazejkustra?

**Comment by blazejkustra** [comment]
@twisterdotcom [Setup TS in Onyx](https://github.com/Expensify/App/issues/34334) was merged last week, now we have to work on other migrations first and we will come back to this one.

**Comment by fabioh8010** [comment]
We still have to migrate other files before starting this one

**Comment by fabioh8010** [comment]
@mountiny Could you change this to Weekly?

**Comment by twisterdotcom** [comment]
Still in the ts queue

**Comment by twisterdotcom** [comment]
Still in the queue.

**Comment by mountiny** [comment]
@blazejkustra @fabioh8010 what is latest on this  one?

**Comment by mountiny** [comment]
Thanks for the update

**Comment by blazejkustra** [comment]
@fabioh8010 The last Onyx.js PR was just merged, so this is unblocked now! Thank you for your patience 😅

**Comment by fabioh8010** [comment]
WIP Draft PR is up -> https://github.com/Expensify/react-native-onyx/pull/542

**Comment by twisterdotcom** [comment]
Looks like we're holding off on the merge until we're through the slush after site issues.

**Comment by roryabraham** [comment]
This is done, and it looks like it was done without any C+ review, so we can go ahead and close this one out now.
