### ISSUE TITLE
[TS migration] Migrate ‘storage’ catalog to Typescript (react-native-onyx)

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#34340]
# Typescript migration (react-native-onyx)
Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

## Files
`lib/storage/…`
`lib/OnyxCache.js`
`lib/utils.js`

**Comment by mountiny** [comment]
Will be handled by agencies

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
@pecanoro The PR is ready for your review 😄

**Comment by pecanoro** [comment]
Ahh yes, I started yesterday and didn't finish it before the end of the day, I will finish it in the next couple of hours

**Comment by blazejkustra** [comment]
Thank you!

**Comment by pecanoro** [comment]
This is done
