### ISSUE TITLE
[HOLD for payment 2024-01-31] [$500] LHN - Multiline text displayed after a second in the LHN when deleting the last message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34352]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/issues/19539
## Action Performed:
1. Open any chat
2. Send multiline text
3. Send one more message
4. After sending, delete the last message
5. Notice that LHN displays only first text for a second

## Expected Result:
There should not be a delay in displaying the multiline text in LHN

## Actual Result:
Multiline text displayed after a second in the LHN when deleting the last message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dd72c5cc-88cb-4da8-a4ae-b7d22d424977

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018098a3151fcad32f</li>
        <li>Upwork Job ID: 1745444475772952576</li>
        <li>Last Price Increase: 2024-01-11</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28104896</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Over to you @AndrewGable for a secondary review!

**Comment by trjExpensify** [comment]
:wave: checklist time, @thesahindia!

**Comment by trjExpensify** [comment]
Bump, @thesahindia!

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $500 to @dukenv0307 for the fix 
- $500 to @thesahindia for C+ review

**Comment by trjExpensify** [comment]
On the regression test we have this: 

> The following tests require using an account that was already set up. PLEASE do not use the account for any other type of testing.
> 
> 1. Log in with the following account - applausetester+[multiline@applause.expensifail.com](mailto:multiline@applause.expensifail.com) (it's already set up for these tests)
> 2. Once logged in navigate to each of the conversations available (multiline+1 to multiline+9)
> 3. Verify each of the multiline preview messages are displayed correctly in the LHN, only the first line of the message should be visible
> 

I've created [an issue](https://github.com/Expensify/Expensify/issues/367851) for Applause to discuss updating it.

**Comment by trjExpensify** [comment]
@dukenv0307 - paid 

Closing!

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
