### ISSUE TITLE
[$500] Login - After adding an account to a room, the added account cannot log in to ND

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34355]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
You must have a WS in your HT account or create one
1. Open https://staging.new.expensify.com/
2. Log in to the HT account
3. Tap on the green plus button (FAB)
4. Select Start chat
5. Select the Room tab
6. Fill in the required data and create a room in your WS
7. Go to the Members tab in the settings of the created room
8. Click the Invite button
9. Add a @applause.expensifail.com account to the room that has never registered in NewDot or OldDot
10. Open https://staging.new.expensify.com/
in incognito mode
11. Try logging in with the account that was added to the room

## Expected Result:
A user must be able to log in after adding their account to the room

## Actual Result:
When adding a non-existent account to a room and then trying to log in to ND with that login, the error "Cannot get account details, please try again or contact [concierge@expensify.com"](mailto:concierge@expensify.com%22)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4e007174-5c67-4a58-ac06-3f6a0eba253b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a52b53b74a876e6</li>
        <li>Upwork Job ID: 1745447007193206784</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by Senninseyi** [comment]
@lanitochka17 please what exactly are the issues I seem to add a non existing account to my workspace and have been able to login using that same account

**Comment by lanitochka17** [comment]
@Senninseyi Hello
Tried several times and still can't add expensifail account that doesn't exist.


https://github.com/Expensify/App/assets/78819774/c95c6895-b17a-4293-94a9-c3b3e6bf956d

**Comment by waterim** [comment]
Looks like after adding @applause.expensifail.com accounts, they are becoming inactive for some reason
Looks like a backend issue

**Comment by NicMendonca** [comment]
I am going to close as this is very specific to a domain and not a real end-user use case.
