### ISSUE TITLE
previously stored search input is sent to the backend instead of the latest value entered by the user

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34353]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704921995746249

## Action Performed:
1. click on "search" icon beside the avatar
2. Type user 1
3. Check the API
## Expected Result:
Latest entered input should be sent to backend

## Actual Result:
Previously stored result is sent to backend

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0b5b8784-b01c-4a3a-95c9-1187ed3156e4

https://github.com/Expensify/App/assets/38435837/6c78ca09-ad92-4e45-abb6-9958cf261486

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187544a07fd9a4b27</li>
        <li>Upwork Job ID: 1745445129843707904</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by rushatgabhane** [comment]
this can be external (if we want to)

**Comment by youssef-lr** [comment]
I have a fix included in an ongoing draft PR but figured I ship this separately sooner.

**Comment by mallenexpensify** [comment]
@rushatgabhane should be assigned as C+, even if we fix this internally..... right?

**Comment by youssef-lr** [comment]
Actually the PR I was planning to fix this in is almost ready, so I'll include the fix in there instead of fixing this separately.

@rushatgabhane should I assign you for reviewing it? We're adding the possibility to return `personalDetails` from `SearchForReports` so we can display proper avatars/display names of any user we search for.

**Comment by mallenexpensify** [comment]
Do you have a link to the PR @youssef-lr ?  Thx

**Comment by youssef-lr** [comment]
https://github.com/Expensify/App/pull/34400

**Comment by rushatgabhane** [comment]
@youssef-lr yeah sure you can assign it to me

**Comment by mallenexpensify** [comment]
Assigned @rushatgabhane

**Comment by youssef-lr** [comment]
Backend PRs are still under review.

**Comment by youssef-lr** [comment]
remaining PRs still in the works.

**Comment by youssef-lr** [comment]
Same.

**Comment by youssef-lr** [comment]
Bumped the reviewer

**Comment by youssef-lr** [comment]
Looks like this was fixed in this [PR](https://github.com/Expensify/App/pull/35058) unintentionally.
