### ISSUE TITLE
[$500] [HOLD for payment 2024-01-24] [HOLD for payment 2024-01-22]  Web - Request money - The 'Enter' button doesn't work for the confirmation money page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34367]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to FAB -> Request money -> Manual
4. Enter any amount - > Click `Enter`

## Expected Result:
The selection is made and the next page opens

## Actual Result:
The 'Enter' button doesn't work

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7a18d67c-0bbf-4272-9910-5a7f45fad1d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e291ba0a03dee35</li>
        <li>Upwork Job ID: 1752269333524930560</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by situchan** [comment]
@Julesssss can you please reopen this issue? C+ payment for PR review is pending

**Comment by twisterdotcom** [comment]
Sorry for the wait @situchan: https://www.upwork.com/nx/wm/offer/100722406.

Payment Summary: Regression PR review: https://github.com/Expensify/App/pull/34313
- @situchan paid $500 [here](https://www.upwork.com/nx/wm/offer/100722406) C+
