### ISSUE TITLE
LOW: Feature request: Unfurl Soundcloud links and allow the user to play them in NewDot. 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34373]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Problem**
Unable to play soundcloud links in the NewDot 

**Solution**

Unfurl Soundcloud links and allow the user to play them in NewDot. (Both slack and NewDot screenshots attached)

**Context/Examples/Screenshots/Notes:**

![Screenshot 2024-01-10 at 4 43 15 PM](https://github.com/Expensify/App/assets/38435837/93e07bef-78a3-49ad-ab5c-89a2d7555a1c)
![Screenshot 2024-01-10 at 4 43 01 PM](https://github.com/Expensify/App/assets/38435837/5d9203b9-a50a-4839-826a-771f23c4eeaf)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704930238839509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
cc @quinthar

**Comment by sophiepintoraetz** [comment]
@AndrewGable - is this something that can be implemented by a contributor?

**Comment by AndrewGable** [comment]
I haven't looked into it deep enough to know. I thought other link previews were generated on our back end, but I could be wrong.

**Comment by sophiepintoraetz** [comment]
Okay, raising this for discussion [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1705275573745709) because while nice to have, I think there are other things we could be working on.

**Comment by roryabraham** [comment]
I think we have some stuff for link previews in the back-end but they were turned off. cc @marcaaron 

Also – I'd think if we were doing this (setting up inline audio player), we'd want a holistic design that works for uploaded audio clips (such as voice memos) in addition to link previews from Spotify, Soundcloud, Apple Music, etc...

**Comment by marcaaron** [comment]
Briefly looked at whether SoundCloud docs had anything in their oEmbed section for this. And they were surprisingly unhelpful 

![2024-01-16_14-20-18](https://github.com/Expensify/App/assets/32969087/c6a93bf9-1a8c-48f2-84ec-eb14f254e2e6)

Tried the standard curl oembed dance and got this back:

```
curl -X GET "https://soundcloud.com/oembed?url=https://soundcloud.com/dubbeldutch/rare-earth-elements-vol-1-demo&format=json"

{"version":1.0,"type":"rich","provider_name":"SoundCloud","provider_url":"https://soundcloud.com","height":400,"width":"100%","title":"Rare Earth Elements Vol. 1 Demo by dubbel dutch","description":"Get it now at Splice!\n\nhttps://on.splice.com/dubbel-dutch-pack","thumbnail_url":"https://i1.sndcdn.com/artworks-000345743616-or91kn-t500x500.jpg","html":"<iframe width=\"100%\" height=\"400\" scrolling=\"no\" frameborder=\"no\" src=\"https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F441183414&show_artwork=true\"></iframe>","author_name":"dubbel dutch","author_url":"https://soundcloud.com/dubbeldutch"}
```

So, their player embed code is an iframe. Not sure how this will look/behave on mobile.

Agree with @roryabraham here though that a holistic approach would be interesting to explore though we are kind of at the mercy of whatever platform embeds are offered at the end of the day. 

I checked this out and we don't get that embed code back from our metadata proxy (already built but not used yet) so we would at least need a backend change to grab that. Here's the output I did get:

```
{
  "onyxData": [
    {
      "onyxMethod": "merge",
      "key": "reportActions_210960085665009",
      "value": {
        "4103202628908714323": {
          "linkMetadata": [
            {
              "lang": "en",
              "author": null,
              "title": "Rare Earth Elements Vol. 1 Demo",
              "publisher": "SoundCloud",
              "image": {
                "url": ["https://i1.sndcdn.com/artworks-000345743616-or91kn-t500x500.jpg"](https://i1.sndcdn.com/artworks-000345743616-or91kn-t500x500.jpg),
                "type": "jpg",
                "size": 27555,
                "height": null,
                "width": null,
                "size_pretty": "27.6 kB"
              },
              "date": "2024-01-17T00:34:46.000Z",
              "description": "Get it now at Splice! https://on.splice.com/dubbel-dutch-pack",
              "url": ["https://soundcloud.com/dubbeldutch/rare-earth-elements-vol-1-demo"](https://soundcloud.com/dubbeldutch/rare-earth-elements-vol-1-demo),
              "logo": {
                "url": ["https://a-v2.sndcdn.com/assets/images/sc-icons/ios-a62dfc8fe7.png"](https://a-v2.sndcdn.com/assets/images/sc-icons/ios-a62dfc8fe7.png),
                "type": "png",
                "size": 3144,
                "height": 114,
                "width": 114,
                "size_pretty": "3.14 kB"
              }
            }
          ]
        }
      }
    }
  ],
  "jsonCode": 200,
  "requestID": "846a83a95de46a19-HNL"
}
```
