### ISSUE TITLE
[HOLD for payment 2024-01-24] [HOLD for payment 2024-01-22] FAB - Skeleton appears first on Start chat page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33055
## Action Performed:
1. Go to staging.new.expensify.com
2. Click FAB button
3. Select Send message

## Expected Result:
The modal should open smoothly, without showing the skeleton

## Actual Result:
Skeleton appears first when open Start chat page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/8d3976d9-400e-49d5-89d5-843463937ea0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
> Select Send message

@lanitochka17 this should read `Select Start chat`

**Comment by iwiznia** [comment]
Given that the fix was only for desktop, can't we make the fix apply only to desktop @dukenv0307? 

> I think we should only wrap interaction here for native platform

Also, how are you proposing we do this? We would define another file just native, right?

**Comment by iwiznia** [comment]
> If we only want to apply it on desktop we also can do that by checking getPlatform

But our guidelines advice against this, no?

**Comment by iwiznia** [comment]
>  I guess freeze usually happens on native device so I suggest only apply it on native.

By native what do you mean exactly? Desktop?

**Comment by iwiznia** [comment]
Yeah, we do, but either that was a mistake or there was a good reason to skip the guideline, in this case I don't think there's a good reason, so let's follow the guideline.
Can you update the proposal to do this @dukenv0307 ?

**Comment by iwiznia** [comment]
Awesome thanks! Assigned to you

**Comment by mountiny** [comment]
CPed and verified this worked https://expensify.slack.com/archives/C07J32337/p1705314001375409

**Comment by NicMendonca** [comment]
@dukenv0307 can you please accept the job offer I just sent? Thanks!

**Comment by NicMendonca** [comment]
paid! thanks!

**Comment by c3024** [comment]
@NicMendonca I reviewed the PR here #34449. Can you please check and send me an offer?

**Comment by NicMendonca** [comment]
@c3024 can you apply to the job here? https://www.upwork.com/jobs/~010e3553157ff6c282

**Comment by c3024** [comment]
Applied. thanks. @NicMendonca

**Comment by NicMendonca** [comment]
paid!
