### ISSUE TITLE
Start chat - Transition between Room & Chat tab is not smooth

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34377]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB > Start chat > Switch between Room & Chat tab multiple times

## Expected Result:
Transition between tabs should be smooth

## Actual Result:
Transition between tabs is not smooth

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bf034130-5f0e-4e81-b2f4-5903434584d5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shubham1206agra** [comment]
@kacper-mikolajczak Can you check this problem?
Offending PR https://github.com/Expensify/App/pull/33841

**Comment by situchan** [comment]
Seems like bug here is "animation disabled"
But we intentionally disabled animation since it's better than freezing

**Comment by kacper-mikolajczak** [comment]
> Seems like bug here is "no transition animation"
But we intentionally disabled animation since it's better than freezing

As @situchan  mentioned, animations were purposely disabled here https://github.com/Expensify/App/issues/31190

Let me know if the issue raised here involves only animations or something extra - if yes, then I am happy to look into that 👍 

CC @lanitochka17 @shubham1206agra

**Comment by shubham1206agra** [comment]
@kacper-mikolajczak As per video, I can notice some stutter while transitioning. Can you please look into that?

**Comment by kacper-mikolajczak** [comment]
@shubham1206agra Definitely 🔧

**Comment by kacper-mikolajczak** [comment]
Hi! After inspecting here and there, it looks like a nasty race condition caused by the input autofocus. I need more time to establish with certainty what is causing race condition, so if you could assign the issue to me. Thanks! 👍 

Here is the recording that shows the reproduction of the bug whenever I time it right (first transition is too fast). After waiting until autofocus kicks in, the transition seems to start working fine:

https://github.com/Expensify/App/assets/62747088/e1625473-4039-4631-82ed-9ef6f53bf909

And here is the sample with disabled _autofocus_  for _RoomName_ input in `Workspace` screen:

https://github.com/Expensify/App/assets/62747088/b8c9eb09-b347-4043-8b8e-ab710b8a164a

CC: @shubham1206agra @lanitochka17

**Comment by robertjchen** [comment]
Great point, let us know what you find!

**Comment by kacper-mikolajczak** [comment]
Hi everyone! 👋 

While I was investigating the issue from technical side of things, I realised that the autofocus in current form in seems a bit off. Thus, I wanted to discuss with you a reason behind having an autofocus in this case and how we can improve it. Thanks for your insight!

Imho, If user already visited screen (e.g. filled some inputs), then we should not bring back focus to the first input - it should stay where it was. Current behaviour should be preferred only on first visit or when form is still in clean state.

As an example, here is a recording of undesired behaviour where change of the focus breaks UX heavily:

https://private-user-images.githubusercontent.com/62747088/296874714-955223b5-09bd-41a6-b5a4-5de338adf7bf.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNTU0MjUsIm5iZiI6MTcwNTM1NTEyNSwicGF0aCI6Ii82Mjc0NzA4OC8yOTY4NzQ3MTQtOTU1MjIzYjUtMDliZC00MWE2LWI1YTQtNWRlMzM4YWRmN2JmLm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDIxNDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZGMzMzZlMDY0NzA0MDUxOWUyYTA2NmU0Mjc3ZTY5MDIyOGU0OGVlMTM4YjFiOWI5NWI3NjY5MWEzZWY5MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lx6JZCn2nfd9DfBnXSXe3d6lsMmipxdyv0kNUEvEmv4

**Comment by bernhardoj** [comment]
What if we just cancel the focus to happen when the tab is unfocused?

Currently, we only clear the timeout when out of focus,
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/hooks/useAutoFocusInput.ts#L33-L44

but the interaction manager is still firing.
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/hooks/useAutoFocusInput.ts#L26-L29

So, we just need to cancel it too.

```diff
return () => {
+   interactionRef.current?.cancel()
+   setIsScreenTransitionEnded(false);
    if (!focusTimeoutRef.current) {
        return;
    }
    clearTimeout(focusTimeoutRef.current);
};
```
