### ISSUE TITLE
[$500] Olddot app - User isn't redirected to NewDot on mWeb after tapping on "Current Plan" option

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34370]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign Out from NewDot on Mobile Web
2. Open the OldDot mobile app
3. Log in using an Expensifail account that has an existing workspace policy
4. Navigate to Settings
5. Tap on "View all" in the policies section
6. Navigate to Group Tab
7. Tap on the "Edit" button next to a workspace
8. Tap on the "Current Plan" option inside the workspace settings

## Expected Result:
 Redirection to NewDot on mWeb should occur.
- The user is redirected to NewDot on mWeb with the correct workspace settings page open.
- The same user is logged in to NewDot as in the OldDot app.

## Actual Result:
User isn't redirected to NewDot on mWeb after tapping on "Current Plan" option in Classic app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/dd9f3756-3084-4832-ae44-123cce0f802a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efb58f0374bca957</li>
        <li>Upwork Job ID: 1745466603939237888</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Issue found when executing TR https://expensify.testrail.io/index.php?/tests/view/4165557

**Comment by ikevin127** [comment]
This should go internal since in order to fix the issue it will require changes within OD codebase.

**Comment by johncschuster** [comment]
Sorry I missed your comment, @ikevin127. I'll change this to `Internal`.

**Comment by marcochavezf** [comment]
Hi @kbecciv, I see in the video you're tapping on a Control policy, but we don't support Control policies in NewDot yet, do you if this only happens to Control policies or also in other policies?

**Comment by marcochavezf** [comment]
No update, we'd need to confirm if it's happening in collect policies

**Comment by johncschuster** [comment]
@kbecciv can you please test if this happens with a non-Control policy?

**Comment by marcochavezf** [comment]
No update

**Comment by eVoloshchak** [comment]
Not overdue, same as in https://github.com/Expensify/App/issues/34370#issuecomment-1897497687
@kbecciv, could you verify this is happening with a non-Control policy? Thanks!

**Comment by kbecciv** [comment]
It happened on both - Collect and Control Policies. 

https://github.com/Expensify/App/assets/93399543/45556b54-f713-4473-829c-d363311dc6af

**Comment by marcochavezf** [comment]
I wonder if this should be part of a wave

**Comment by marcochavezf** [comment]
Asked [here](https://expensify.slack.com/archives/C02MW39LT9N/p1706750407222289)

**Comment by johncschuster** [comment]
It sounds like this might be related to wave9. Asking in that channel ([here](https://expensify.slack.com/archives/C05NJ4SLBMF/p1707176494465769)).

**Comment by marcochavezf** [comment]
Moving this to wave9 per this [comment](https://expensify.slack.com/archives/C02MW39LT9N/p1706757772304269?thread_ts=1706750407.222289&cid=C02MW39LT9N)

**Comment by marcochavezf** [comment]
No update

**Comment by marcochavezf** [comment]
No update, wrapping up other daily issues

**Comment by marcochavezf** [comment]
Looking to hand it off while I'm working on other wave issues https://expensify.slack.com/archives/CC7NECV4L/p1707927324969599?thread_ts=1707859616.856679&cid=CC7NECV4L

**Comment by marcochavezf** [comment]
Having issues with the ruby env to install the cocoapod dependencies to run OldDot app

**Comment by marcochavezf** [comment]
I fixed the environment to run OldDot locally, and while I was exploring the code and the flow, I had a doubt about when to redirect (since I don't think we want to redirect all the current Collect/Control users to NewDot). [Posted](https://expensify.slack.com/archives/C05NJ4SLBMF/p1708471062887309) in wave9 channel to gut-check
