### ISSUE TITLE
[HOLD for payment 2024-01-24] [HOLD for payment 2024-01-22] Distance - App crashes when creating distance request quickly after changing date

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34375]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: App location access is enabled
1. Go to workspace chat > + > Request money
2. Go to Distance
3. Enter addresses and proceed to confirmation page
4. Click Date and change the date
5. When the map is still rendering from current location tApp does not crash

## Expected Result:
App does not crash.

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

[logs.txt](https://github.com/Expensify/App/files/13905634/logs.txt)

https://github.com/Expensify/App/assets/78819774/289125a9-dde8-4b5d-9b1d-8fa0a0a96ca8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
Regression from https://github.com/Expensify/App/pull/33529
Being fixed in https://github.com/Expensify/App/pull/34336

**Comment by grgia** [comment]
merged https://github.com/Expensify/App/pull/34336

**Comment by mountiny** [comment]
Should be fixed!

**Comment by grgia** [comment]
closing
