### ISSUE TITLE
[HOLD for payment 2024-02-14] Make NewDot referral banners permanently dismissible

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#34387]
## Background
We already plan to make the referral program banners in New Expensify **temporarily** dismissible ([here's the PR for that](https://github.com/Expensify/App/pull/33925)). The banners are in these locations:

1. Click green + button > Start chat > "Start a chat, get $250." at the bottom
2. Click green + button > Request money > once you get to the contacts search field, "Request money, get $250." at the bottom
3. Click green + button > Send money > once you get to the contacts search field, "Send money, get $250." at the bottom
4. Click search/magnifying glass > "Invite a friend, get $250." at the bottom

Now, with [this What's Next post](https://expensify.slack.com/archives/CC7NECV4L/p1704832262099119), we've agreed to make them **permanently** dismissible. 

So once the PR linked above is done, an "x" should show next to all the referral banners that can be temporarily dismissed. With this issue, we'd like to make them **permanently** dismissible. So whenever you "x" out any banner on any platform, we never show that banner to you again. 

Let me know if you need more info, thank you!

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by mountiny** [comment]
Lets get this assigned to a project and then get some engineer from that project, I am now focusing on wave6 and wave8 so would prefer to reassign but without assigned project its hard to know who to ask

**Comment by jamesdeanexpensify** [comment]
Hey @tgolen thanks for picking this one up!

**Comment by tgolen** [comment]
I'm going to start working on the backend changes to control this with a user NVP. The frontend is blocked on https://github.com/Expensify/App/pull/33925 but I am trying to get that one moving and completed soon so that it will unblock this.

**Comment by tgolen** [comment]
- Got the [Auth PR](https://github.com/Expensify/Auth/pull/9697) finished and ready for review
- Got the [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/40603) written but it's not tested
- Created the barebones [App PR](https://github.com/Expensify/App/pull/34842) but functionality hasn't been added yet

Next steps (for Monday):
- Build functionality into NewDot
- Test everything out so that the Web-E PR can be removed from draft and reviewed

**Comment by tgolen** [comment]
I'm hoping to finish up all the dev work on this today, then it's just a matter of getting the stuff reviewed and deployed.

**Comment by tgolen** [comment]
The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/40603) has been approved and will be merged soon.

Once the Web-E PR is on staging, then the [App PR](https://github.com/Expensify/App/pull/34842) will be taken out of draft and begin the review process.

**Comment by tgolen** [comment]
# Daily Update
- The Web E PR is merged and on staging
- The App PR is out of draft and in review now. ETA to have it merged is EOW (if reviews are speedy)

**Comment by jamesdeanexpensify** [comment]
Ah, I think we might need to assign someone from the Bug Zero team for payment. Let me see how that works.

**Comment by tgolen** [comment]
Oh, I thought you were BZ! I can get someone assigned, no sweat.

**Comment by mallenexpensify** [comment]
@hoangzinh can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01cda238518a4e686f

**Comment by strepanier03** [comment]
Working on this now, sorry for the delay.

**Comment by strepanier03** [comment]
All right, paid and contract closed. Thanks @hoangzinh for helping finish this one!
