### ISSUE TITLE
Login - Magic code is sent to wrong email after editing when using ENTER key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34381]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)
2. Enter any email and use Enter button to continue to next page
3. On magic code page select "go back"
4. Edit email and use "Enter" to continue

## Expected Result:
Magic code is sent to new email entered

## Actual Result:
Magic code is sent to initial email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ee3d7836-9468-4a8f-b066-d334cf96f4ce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
Not reproducible on main

**Comment by s-alves10** [comment]
This PR https://github.com/Expensify/App/pull/34313 solved the issue
The root cause is in here
https://github.com/Expensify/App/pull/34313/files#diff-2a0d77decd98a62a279ac9fb139cad79d6d7a20f4c724de3dc811911bc5dd9b1L142-L151

`onPress` wasn't added to the dependency. We can CP this PR

**Comment by amyevans** [comment]
Yep thanks, confirmed not reproducible on `main`:

https://github.com/Expensify/App/assets/7277067/f7f814f6-4151-430e-be47-bcbf2254f2f9

But reproducible on `staging` branch locally:

https://github.com/Expensify/App/assets/7277067/bf444b41-92df-4191-939b-be9527a1303d

I'll check in about the cherry pick, I'm surprised it hasn't been already

**Comment by situchan** [comment]
I think @Julesssss is requesting CP https://github.com/Expensify/App/pull/34313

**Comment by amyevans** [comment]
I think he's off for the night, I'm requesting it now

**Comment by amyevans** [comment]
The CP is complete. I retested on staging to verify it's fixed:

https://github.com/Expensify/App/assets/7277067/e2c3e587-6625-4008-9ff8-c8c33d5bb6c8

**Comment by Julesssss** [comment]
Oh thanks @amyevans I forgot to CP this
