### ISSUE TITLE
[$500] Attachment – App flickering when add attachment and take a photo

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34382]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. On a conversation, click on the + button in the compose box
4. Click on add attachment
5. Click on Take photo
6. Take a picture/ v

## Expected Result:
Preview of the image is displayed

## Actual Result:
App flickering when a preview of the image is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/134ddb4b-3e87-4d05-a3b6-19f52c140028

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101abfb3b480bde35</li>
        <li>Upwork Job ID: 1745488864976412672</li>
        <li>Last Price Increase: 2024-01-27</li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attachment – App flickering when add attachment and take a photo
### What is the root cause of that problem?
TheSwitch component is not disabled in any cases
### What changes do you think we should make in order to solve the problem?
Add disabled={didConfirm} prop to Switch component

### What alternative solutions did you explore? (Optional)

**Comment by waterim** [comment]
Issue is not reproducible on IOS.

**Comment by muttmuure** [comment]
@lanitochka17 please can you clarify which platform you are using (iOS or Android)

**Comment by lanitochka17** [comment]
@muttmuure We are using Android

**Comment by muttmuure** [comment]
Tested in the office, - can't reproduce on 

Pixel 4 
v1.4.32-2

Going to close
