### ISSUE TITLE
Chat - Enter key doesn't work when confirming saving deleted message from keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34397]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Desktop App
2. Login with any account
3. Open any chat
4. Send message
5. Press Arrow Up Key
6. Verify that the last message in the chat enters edit mode
7. Delete all the text while editing the comment and save
8. Verify a modal is displayed for the user to confirm the message deletion
9. Press 'Enter' key to confirm

## Expected Result:
User can press 'Enter' and message was deleted

## Actual Result:
Enter key doesn't work when confirming saving deleted message from keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/46f7dc24-38aa-4ba1-a855-8f83e60102cf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
Can't repro on v1.4.24-5. I don't know if pressing the arrow keys is supposed to do anything regarding focusing/unfocusing the confirmation button, but it doesn't seem to affect anything for me here. Going to ask someone else for a second attempt to repro.


https://github.com/Expensify/App/assets/2229301/898de0d9-1931-4c51-9b94-c8da41a4cf09

**Comment by francoisl** [comment]
https://github.com/Expensify/App/pull/34313 (CP'ed as v1.4.24-5) was a fix for an isue with the Enter key in a different flow, and it most likely also fixed it for this modal.

I think we're good here, also double-checked with @NikkiWines she's not experiencing this.
