### ISSUE TITLE
[$500] mWeb - New user doesn't get Concierge chat after authentication through the magic code link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify
2. Create a new account
3. Copy the magic link and change it to staging
4. Open a new tab and navigate to the staging magic link
5. Verify the abracadabra page is displayed
6. Navigate back to the original tab

## Expected Result:
The Concierge conversation should be displayed immediately after signing up.

## Actual Result:
New user doesn't get Concierge conversation after authentication through the magic code link.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8f3090b9-713b-4838-8a78-b591341a702b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a7b98b78fcaf70a</li>
        <li>Upwork Job ID: 1745533503159492608</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
This has the same issue I explained [here](https://github.com/Expensify/App/issues/34258#issuecomment-1885257982).

I think it should be fixed on the BE by always including the Concierge chat in the report list on #focus mode.

**Comment by s77rt** [comment]
@bernhardoj Per default new users have Concierge chat pinned. This seems to be related to the abracadabra flow

Using the magic code
<img width="465" alt="Screenshot 2024-01-13 at 8 07 29 PM" src="https://github.com/Expensify/App/assets/16493223/f4131121-89b2-4e11-ad4e-a485f6f180be">

Using the magician
![2024-01-13 20 13 45](https://github.com/Expensify/App/assets/16493223/c7abb1ca-7ee7-43a0-bcbf-0e97b45a4b4c)

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by s77rt** [comment]
Still looking for proposals...

**Comment by s77rt** [comment]
Not overdue. Looking for proposals

**Comment by abekkala** [comment]
@kbecciv can you recreate this and provide a new video?
This is quite old and may not even be an issue anymore.

**Comment by abekkala** [comment]
@s77rt are you able to recreate this?

**Comment by s77rt** [comment]
@abekkala Just retested. Working fine!


https://github.com/Expensify/App/assets/16493223/b8b97ed6-6c22-47e2-ab60-82c6469a9b0a
