### ISSUE TITLE
IOU-Showing error in end point as unable to find location when same used for start

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34420]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Launch app
2. Tap on a workspace chat
3. Tap plus icon near compose
4.Tap request money --- Distance
5.Tap start and select " Use your location" and note your location get selected without error
6.Tap finish and select " Use your location" and note error displayed.

## Expected Result:
In distance request, when user uses " Use your location" as waypoints for both start and finish, error "We were unable to find your location." must not be displayed when user selects "use your location" at finish waypoint.

## Actual Result:
In distance request, when user uses " Use your location" as waypoints for both start and finish, error "We were unable to find your location." is displayed when user selects "use your location" at finish waypoint.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/93a2ab4a-a139-4630-9224-880085a7315c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment]
I've tried to reproduce in Browserstack, but that worked fine. I'll ask someone to help test with a physical Android phone. 

<img width="402" alt="image" src="https://github.com/Expensify/App/assets/5802477/65cd9ef1-5e41-460b-a87b-928aaa939a05">

**Comment by conorpendergrast** [comment]
I've [posted to this internal channel](https://expensify.slack.com/archives/C03U7DCU4/p1705504179023279) to ask for help reproducing.

**Comment by strepanier03** [comment]
### Repro notes

**Steps**

- [x] 🟢 Launch app
- [x] 🟢 Tap on a workspace chat
- [x] 🟢 Tap plus icon near compose
- [x] 🟢 Tap request money --- Distance
- [x] 🟢 Tap start and select " Use your location" and note your location get selected without error
- [x] 🔴 Tap finish and select " Use your location" and note error displayed.

At the final step I do not get the error mentioned or shown in the video, however it does load for more than 10 seconds before I see screenshot 1 below. 

I am able to select `Use your location`. I get an error only when clicking the **Next** button, the error is expected to me and is `Please enter at least two different addresses.` screenshot 2 below.

Screenshot 1
![Screenshot_20240117-162414](https://github.com/Expensify/App/assets/10925636/cd74af52-f593-44fe-b201-97f6b3a2d61c)

Screenshot 2
![Screenshot_20240117-162716](https://github.com/Expensify/App/assets/10925636/fc705d46-7d9e-4d30-89d7-9e8408f56605)

**Comment by strepanier03** [comment]
Hope that helps @conorpendergrast

**Comment by conorpendergrast** [comment]
Thank you so much @strepanier03! It looks like this wasn't reproduced, so I'll close out. 

If there's some missing details that will help to reproduce though @kavimuru, please can you add a comment and we'll get those worked through? Thank you!
