### ISSUE TITLE
[$500] Expense rule is not applied for split bill manual request.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34421]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-condition: Have expense rule created with same merchant name for category and tag using old dot
1. Launch app as employee
2. Tap on WS chat of collect policy
3.Tap plus icon near compose
2.Tap request money--- manual request
3.Enter amount and tap next
4.Enter expense rule merchant name and complete flow
5.Open the created expense and note expense rule is applied. ( category and tag section displayed)
6.Navigate back to workspace chat
7. Tap plus icon near compose
8.Tap split bill--- manual request
9.Enter amount and tap next
10.Enter expense rule merchant name and complete flow
11.Open the created expense and note expense rule is not applied. ( category and tag section is empty)

## Expected Result:
Expense rule must be applied for both request money-manual request and split bill--- manual request.

## Actual Result:
Expense rule is applied only for request money-manual request and not working for split bill--- manual request.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/2834f07b-efa4-4b21-8a3f-a6037ca1fc34

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01351d899dfbd36549</li>
        <li>Upwork Job ID: 1745745969876516864</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
This looks like a BE issue: we do not use the expense rules in ND (at least so says the code search), it's only being handled on the server side.

**Comment by cubuspl42** [comment]
🎀 👀 🎀

**Comment by rlinoz** [comment]
Thanks @cubuspl42 , I will investigate if we should be applying rules to split bill and if so, it should be assigned to a wave.

**Comment by rlinoz** [comment]
Since we are not sure what is the future of personal expense rules we will not fix this right now, more details [here](https://expensify.slack.com/archives/C05RECHFBEW/p1705428709164799).
