### ISSUE TITLE
[$500] Request money - Deleted request shows empty details when the details page has messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34425]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Create any request.
3. Go to the details page and send a message.
4. Click 3-dot menu > Delete request.
5. Delete the request.

## Expected Result:
The request details page will be blank except the bottom part where it shows messages (previous behavior).

## Actual Result:
The request details page shows empty details (Amount, date, description etc).

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/072b6473-16da-45c9-87e6-1dd715bf0409

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d86a2dfc9f2be794</li>
        <li>Upwork Job ID: 1745748245116649472</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28142050</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
The temporary code to hide the money request view was cleaned up in https://github.com/Expensify/App/pull/33633

cc: @youssef-lr

**Comment by muttmuure** [comment]
@dukenv0307 are you recommending that this issue is closed and a new bug report created?

**Comment by muttmuure** [comment]
@sobitneupane shall we close this one?

**Comment by sobitneupane** [comment]
@muttmuure I will be able to review the proposals only in weekend. I am working partially and won't be able to prioritize the issue. Please feel free to re-assign the issue in case of higher-priority.

**Comment by muttmuure** [comment]
Hey @allroundexperts! Think you could take a look at [this proposal](https://github.com/Expensify/App/issues/34425#issuecomment-1888806591)?

**Comment by allroundexperts** [comment]
Sorry, missed this completely. Will review today!

**Comment by allroundexperts** [comment]
Reviewing today @MelvinBot!

**Comment by allroundexperts** [comment]
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/34425#issuecomment-1888806591) works good. 
🎀 👀 🎀 C+ reviewed

**Comment by MariaHCD** [comment]
Not overdue, proposal was just accepted.

**Comment by muttmuure** [comment]
Not overdue

**Comment by muttmuure** [comment]
@dukenv0307 are you able to start on your PR?

**Comment by allroundexperts** [comment]
This was deployed to production 2 weeks ago. I think we're just pending the payment here. cc @muttmuure

**Comment by muttmuure** [comment]
$500 - @allroundexperts for C+
$500 - @dukenv0307 paid on Upwork

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
