### ISSUE TITLE
[MEDIUM] Expensify Cards: Wallet - Clicking on Address does nothing after submitting empty phone number

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34426]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in to [applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com)
2. Go to Settings > Wallet > Expensify card.
3. Click Reveal details > Update address > Save.
4. Click Get physical card.
5. Enter invalid phone number > Next.
6. Click Get physical card.
7. Click Address. Note that you can open Address page.
8. Return to previous page.
9. Click Phone number > Clear phone number field > Next.
10. Return to previous page.
11. Click Address.

## Expected Result:
Address page opens.

## Actual Result:
Nothing happens when clicking Address.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/f3cd7235-644d-4fc6-9889-af68942d35a4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010bd5f5e3f107d6c2</li>
        <li>Upwork Job ID: 1755972633038876672</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
@grgia assigning you for initial review, then let's pass this off to a contributor that's been involved.

**Comment by grgia** [comment]
Going to see if the callstack will take this one

**Comment by grgia** [comment]
[asked here](https://expensify.slack.com/archives/C03UK30EA1Z/p1706568074483769?thread_ts=1703268549.160679&cid=C03UK30EA1Z)

**Comment by pac-guerreiro** [comment]
I am Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this job!

**Comment by pac-guerreiro** [comment]
@grgia @kavimuru What's the password for the user [applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com) ?

**Comment by grgia** [comment]
Thanks for the patience @pac-guerreiro, assigning now!

**Comment by grgia** [comment]
> applausetester@applause.expensifail.com

@pac-guerreiro you don't need access to this account (we don't give out expensifail emails), but you should be able to test the form flow bugs in DEV

**Comment by pac-guerreiro** [comment]
@grgia Ok, but I'm not able to replicate the exact behaviour because I don't have a valid card, I can only mock it. Nonetheless, from my tests it seems to work!

**Comment by pac-guerreiro** [comment]
PR ready, have fun! 😄

**Comment by rushatgabhane** [comment]
@kevinksullivan could you please attach payment summary 🙇

**Comment by rushatgabhane** [comment]
payment request here https://staging.new.expensify.com/r/2938310154194899

**Comment by JmillsExpensify** [comment]
Awaiting payment summary from @kevinksullivan

**Comment by kevinksullivan** [comment]
Payment summary:
- @rushatgabhane C+: $500

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
