### ISSUE TITLE
[HIGH] Handle Submit and Close settings in of Collect policy better in NewDot 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#34433]
### Problem

Coming from [this thread](https://expensify.slack.com/archives/C05NJ4SLBMF/p1704387315229399?thread_ts=1704233408.764459&cid=C05NJ4SLBMF) in wave6, when the policy is on Submit and Close settings, the NewDot experience is lacking since the optimistic steps do not cover this case well. 

Additionally the default design/ experience of a Closed report in NewDot is archived, but that should not be the same for expense reports and transaction thread.s

### Solution

Pass the policy settings to the App so we can optimistically decide what happens when user submits and handle this case better.

The expense report should not show as archived either when closed, we still need to discuss this in Slack though cc @JmillsExpensify 

# [DESIGN DOC](https://docs.google.com/document/d/1U4vYiyIy0DQ7MVpcsmrDuE_aVNkuLeSqeUgAvn0Sgrc/edit?usp=sharing)

**Comment by puneetlath** [comment]
@kevinksullivan @grgia is this something we've already designed for non-reimbursable expenses on the free plan? And if so, can we just match that behavior?

**Comment by grgia** [comment]
If I'm remembering correctly, @Gonals worked on the close command. But we briefly punted the "Mark as Closed" action on non-reimbursable transactions as of right now

**Comment by kevinksullivan** [comment]
Sorry for the delay, just checking out the thread now and commenting there

**Comment by adelekennedy** [comment]
still some discussion [here](https://expensify.slack.com/archives/C02MW39LT9N/p1706128245289749?thread_ts=1706104153.164819&cid=C02MW39LT9N)

**Comment by srikarparsi** [comment]
I can work on this one! Left a comment [here](https://expensify.slack.com/archives/C02MW39LT9N/p1706688354169259?thread_ts=1706666293.558869&cid=C02MW39LT9N) and read up on this [slack thread](https://expensify.slack.com/archives/C05NJ4SLBMF/p1704233408764459)

**Comment by adelekennedy** [comment]
@srikarparsi unassigning myself

**Comment by srikarparsi** [comment]
Working on familiarizing myself with the current behavior of closing reports in Old Dot and reading up on docs.

**Comment by srikarparsi** [comment]
In progress, left a comment [here](https://expensify.slack.com/archives/C02MW39LT9N/p1708424739927539?thread_ts=1706666293.558869&cid=C02MW39LT9N)

**Comment by srikarparsi** [comment]
Working on design doc

**Comment by srikarparsi** [comment]
Created a Design Doc tracking issue [here](https://github.com/Expensify/Expensify/issues/373588). Also [finished](https://expensify.slack.com/archives/C02MW39LT9N/p1709108199346869?thread_ts=1706666293.558869&cid=C02MW39LT9N) up the high level with an exception of the marketing considerations section.

**Comment by srikarparsi** [comment]
Closing this out to handle [here](https://github.com/Expensify/Expensify/issues/373588)
