### ISSUE TITLE
[Wave6] Collect policy data is loaded only for primary policy 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#34432]
### Problem

Coming from [this thread](https://expensify.slack.com/archives/C02MW39LT9N/p1704906799616199) cc @joaniew, we have noticed that if user has a lot of workspaces and the Collect policy on which they request money is not their primary policy, we do not load the necessary details about the workspace on App sign in.

This then leads to incorrect Submit button colour and in future incorrect optimistic next steps, because the client does not have information about for example Scheduled submit

### Solution

Ensure that we load this data on demand for policies that require it to correctly render in the App

**Comment by mountiny** [comment]
Trying to figure out the best way to handle this

**Comment by mountiny** [comment]
After this backend change the details of non default policy should be loadede when workspace chat or the expense reports are open so this should be resolved then

**Comment by conorpendergrast** [comment]
@mountiny Did this change already hit production? I see [this PR](https://github.com/Expensify/Web-Expensify/pull/40494#issuecomment-1894488147) is deployed. Anything more to do here?

**Comment by mountiny** [comment]
All done here I believe, thanks for the bump
