### ISSUE TITLE
[HOLD for payment 2024-01-30] [$500] IOU-Receipt missing data remains on employee workspace chat when admin pay expense

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34431]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Start the request money flow > "Scan" receipt
2. Upload a blurry receipt
3. Complete the money request flow
4. While the receipt is scanning - navigate to the request conversation
5. Manually edit the amount field
6. Verify the merchant field shows a error to "Enter a merchant"
7. As the admin - Mark the expense as paid
8. Navigate back to Employee account

## Expected Result:
Receipt missing data should not be present

## Actual Result:
Receipt missing data remains on employee workspace chat when admin pay expense

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/159f43d0-844f-4bbb-99ff-2f242b87bdca

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b87b4141331b3a5</li>
        <li>Upwork Job ID: 1745752013862113280</li>
        <li>Last Price Increase: 2024-01-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28102841</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Receipt missing data still shows after the request is paid.

### What is the root cause of that problem?
The Receipt missing data will be shown when there is a missing required field of the request regardless of the settled status.
https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/components/ReportActionItem/MoneyRequestPreview.js#L232-L235

### What changes do you think we should make in order to solve the problem?

Add `&& !isSettled` so it will show the amount if the request is paid/settled.

or just do nothing

**Comment by garrettmknight** [comment]
@thesahindia can you take a look at this proposal? Looks pretty straightforward.

**Comment by garrettmknight** [comment]
Test case added - @thesahindia request payment when you're ready.

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
