### ISSUE TITLE
[$500] Room -  Room member cannot see thread members when they are not part of the workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30863

## Action Performed:
Precondition: Admin and User B do not share a workspace.
1. [Admin] Invite User B to a room (workspace visibility).
2. [Admin] Send a message to the room and create a thread.
3. [User B] Go to the thread in Step 2 and click on the header.
4. [User B] Send a reply to the thread.
5. [User B] Tap on the header.

## Expected Result:
In Step 3 and 5, Members row will be present to show who are the members of the thread,

## Actual Result:
In Step 3 and 5, there is no "Members" option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cb7f1fc7-0e1e-4f05-9d2c-c10af390176d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d076d18516e66568</li>
        <li>Upwork Job ID: 1745793693860638720</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by mollfpr** [comment]
Based on this PR https://github.com/Expensify/App/pull/32857, it's expected not to show the option for non-workspace users.

@twisterdotcom Could you verify if we now want to show the members option for the non-workspace user?

**Comment by twisterdotcom** [comment]
@MitchExpensify I think you might know this. I assume a guest wouldn't be able to see the members and this is expected?

**Comment by twisterdotcom** [comment]
Asking in BZ: https://expensify.slack.com/archives/C01SKUP7QR0/p1705620779090059

**Comment by MitchExpensify** [comment]
Sorry for the delay @twisterdotcom, responded in the Slack thread: https://expensify.slack.com/archives/C01SKUP7QR0/p1705696338477789?thread_ts=1705620779.090059&cid=C01SKUP7QR0

**Comment by twisterdotcom** [comment]
Okay, we discussed this and this is expected. Workspace members can view all other workspace members contact information, but non-workspace members (ie guests in the chat) cannot.
