### ISSUE TITLE
[$500] IOU - Green dot disappear from LHN chat when switch Most recent > Focus> Most recent

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
IOU report with green dot should be present in LHN
1. Navigate to staging.new.expensify.com
2. Go to Settings> Preferences> change the priority mode from Most recent> Focus> Most recent

## Expected Result:
IOU report in LHN should remain the green dot

## Actual Result:
Green dot disappear from LHN chat when switch Most recent > Focus> Most recent

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec3be75b-1c52-431b-9481-06ed724a827c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shahinyan11** [comment]
Can not reproduce
