### ISSUE TITLE
Hmm its not there error message after uploading an expense receipt in workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1704329850344679

## Action Performed:

1. Create an expense by scanning a receipt in workspace

## Expected Result:
Receipt scanned and expense report created and to be able to click into the preview and see the recipe to image

## Actual Result:
Unexpected error message. When I click on the preview I receive a message that I don’t have access to the chat.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_5652](https://github.com/Expensify/App/assets/38435837/191f8e57-42a3-4e21-a444-d5b6d178e420)
![IMG_5653](https://github.com/Expensify/App/assets/38435837/90c2679c-60f0-4f74-b4d6-8db19d3a68d8)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
Commented on the slack thread but going to close this one out because I'm not sure where to look here. I checked the logs and I just can't see it even hitting our server. (The two expenses for around that date and time are for Safeway and Expedia)
<img width="1204" alt="image" src="https://github.com/Expensify/App/assets/42940078/52eae417-c974-4823-9de9-b12c54733ed9">
