### ISSUE TITLE
Welcome message whisper should come from  room creator not from workspace room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://github.com/Expensify/App/issues/34442

## Action Performed:
1. Create a workspace and invite a member
2. As a member create room
3. Invite someone to the room
4. Log in to the account as invited member

## Expected Result:
Welcome message whisper should come from  room creator 

## Actual Result:
Welcome message whispers comes from the workspace owner
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image-2024-01-11 15_43_29 867](https://github.com/Expensify/App/assets/38435837/e5f1088b-9e06-4031-b113-a87a80589368)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd651f50eafa28c0</li>
        <li>Upwork Job ID: 1746775344275292160</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by DylanDylann** [comment]
This is a BE bug, the OpenReport API return wrong `actorAccountID` for the welcome message

**Comment by neil-marcellini** [comment]
Setting a reminder to triage this tomorrow.

**Comment by neil-marcellini** [comment]
I got a draft PR up, the fix should be pretty easy. I got a little side tracked because there was a really tricky error that came up as part of the flow I need to test, but it's fixed now.

**Comment by neil-marcellini** [comment]
The failing test is done and ready to be fixed. I discovered that we don't store any information about who created the room, because we set the accountID of the created action to 0. I'm pretty sure that's because this action isn't supposed to be associated with an individual in the UI.

The solution will be to store the creatorAccountID somewhere, probably in the message field of the room created action. Then when we [add the welcome message action as a whisper](https://github.com/Expensify/Auth/blob/a1be5e9c73409192ae861a49b3ea4e6901d8f61a/auth/lib/Report.cpp#L1298), we can fetch the creatorAccountID and use it. The solution can't be retroactive because we didn't store this information earlier, but if we want to fix it for existing rooms we could write some custom queries.

**Comment by neil-marcellini** [comment]
May I please have a query timing and the plan for the following query added in this [Auth PR](https://github.com/Expensify/Auth/pull/9727)? The reportID here is the #announce room on the big chat test policy, and it has a ton of messages / report actions.

Query:
```sql
SELECT message FROM reportActions where reportID = 5421294415618529 AND action = 'CREATED';
```

Query plan from dev:
```
sqlite> explain query plan SELECT message FROM reportActions where reportID = 5421294415618529 AND action = 'CREATED';
QUERY PLAN
`--SEARCH reportActions USING INDEX idxReportIDAction (reportID=? AND action=?)
sqlite>
```

**Comment by neil-marcellini** [comment]
Ok, the PR is up for review. I encountered 1 flakey test so I might need to re-run the tests a few times, but it's ready to review regardless.

**Comment by neil-marcellini** [comment]
@kadiealexander the PR was deployed to production so this is done.
