### ISSUE TITLE
[$500] Profile - Infinite loading displayed when click on default avatar in offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34458]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.24-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open app
2. Sign In with account that have multiple conversations, above 20
3. Turn off internet connection
4. Scroll down and click on chat preview where user displayed with default avatar (profile icon)
5. Click on header
6. Click on user avatar

## Expected Result:
Default avatar should be loaded when user offline

## Actual Result:
Infinite loading displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/575f4d28-3589-4e59-96f4-44201c10f668

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d959b0dc67d426a</li>
        <li>Upwork Job ID: 1745867294724395008</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by abhishektrunks** [comment]
Hi , It worked on my MacOS: Chrome and MacOS: Desktop properly.

**Comment by abhishektrunks** [comment]
Contributor details
Your Expensify account email: mick.sharma02@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0189905e038d2f0377

**Comment by slafortune** [comment]
@fedirjh are you able to reproduce this?  it's been deployed to production.

**Comment by slafortune** [comment]
Sure can!  Thanks @fedirjh
