### ISSUE TITLE
[HOLD for payment 2024-02-19] Build additional screens for engagement modal

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#34468]
**E/E Issue:** https://github.com/Expensify/Expensify/issues/356387

**New Feature**

Add a step to the "Manage my team's expenses" flow which lists functionality currently unavailable in NewDot and asks the user if they need any of those features. If they do we push back to OldDot, if they don't we create the NewDot workspace.

Here is the flow we've landed on:

- User chooses "Manage my team's expenses" on the engagement modal
- User sees this screen:

![295784773-795f2bf1-dcff-4aa7-a351-b2d32844960d](https://github.com/Expensify/App/assets/32969087/5012945a-61e5-4a96-a272-63e171b12463)

If they choose "no" they follow the same flow currently in place for users choosing "Manage my team's expenses"
If they choose "yes" we show this screen to set redirect expectations:

![295785177-6dc1e9db-b7d0-4cc3-b2c0-447d0549cbee](https://github.com/Expensify/App/assets/32969087/48fce6e0-9b4b-4b10-aeb2-fff4a083b7e6)

**Comment by Dharani-Eswaramurthi** [comment]
This can be done by using a simple state variable.

**Comment by sainath998** [comment]
This can be done by adding a state variable for storing yes/no from the user. and then accordingly we can redirect to the different routes.

**Comment by sainath998** [comment]
Contributor details
Your Expensify account email: sainathreddy863@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016b509f418e83c65a

**Comment by sainath998** [comment]
This can be done by adding a state variable for storing yes/no from the user. and then accordingly we can redirect to the different routes.

**Comment by sainath998** [comment]
Hi,


Is this task assigned to me?

**Comment by marcaaron** [comment]
Backend PRs in review now. Asking design for the assets. Then we should be ready to go.

**Comment by dubielzyk-expensify** [comment]
Here's the illustration asset. Let me know if there's anything else needed.

[olddot-wireframe.svg.zip](https://github.com/Expensify/App/files/13970171/olddot-wireframe.svg.zip)

**Comment by marcaaron** [comment]
@sainath998 no it's not assigned to you, thanks

**Comment by marcaaron** [comment]
We are waiting for:

- [ ] [This PR](https://github.com/Expensify/App/pull/32154) to get merged
- [ ] [This PR](https://github.com/Expensify/Web-Expensify/pull/40571) to reach staging 

I will give another update when that's all done (since it means there are no more blockers for this issue). 

@teneeto if you want to start working on some of the screens without having those parts at this point I think you could.

**Comment by teneeto** [comment]
Yes @marcaaron, I already started looking for a way out, thanks for the heads-up.

**Comment by marcaaron** [comment]
Still waiting for the Web-E PR to hit production and the App PR to get merged.

@teneeto if you want I think you could start working on this and set the base branch to [the PR](https://github.com/Expensify/App/pull/32154) that is looking close to merge here? I am guessing it will be merged either today or tomorrow.

**Comment by teneeto** [comment]
Yea, this works took too

**Comment by marcaaron** [comment]
@teneeto How's it going with this one? Let me know if I can answer any questions.

**Comment by teneeto** [comment]
Hi @marcaaron, I'm actually done with the checks on the list i shared on slack. except for translations. 

Also, what should be the redirect expectation for the last screen - should we redirect to olddot? and for clarity - what would that link be?

**Comment by marcaaron** [comment]
Thanks @teneeto I think we resolved that last question. 

I have begun testing (code looks great) and left some initial design notes. But maybe @dubielzyk-expensify wants to take another look to make sure everything is 👌.

**Comment by dubielzyk-expensify** [comment]
Just commented. I've added myself as a reviewer just to ensure that the design is correct (though @marcaaron seems to have most things covered 😄 )

**Comment by teneeto** [comment]
Thanks for the brilliant reviews guys. Had a second look too, I have resolved all review comments. Let me Know if i'm still missing something.

**Comment by marcaaron** [comment]
Merged. Great work everyone! 🙇 Thanks for all the help.

**Comment by teneeto** [comment]
I added a [follow-up PR](https://github.com/Expensify/App/pull/36144) approved and merged.

This PR added a few fixes based on these comments:
1. https://github.com/Expensify/App/pull/35019#discussion_r1482393049
2. https://github.com/Expensify/App/pull/36144#issuecomment-1934190940
3. [PR Description](https://github.com/Expensify/App/pull/36144#issue-2125127047)

cc @marcaaron

**Comment by marcaaron** [comment]
This one can be closed. I reviewed and there was no C+.
