### ISSUE TITLE
HelpDot Improvements - Create Tabs on HelpDot for Mobile/Desktop View

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#34462]
Goal/Audience:
The goal is to improve HelpDot for Expensify Classic to make it more readible/make sure desgin elements are up to par. Audience will be users of Expensify Classic and New on both mobile and Desktop.

Deliverables:
Within HelpDot we'll want to create a tab structure for the end user to be able to select the view of whether they are on IOS, Android or Desktop. Please see example [here](https://expensify.slack.com/archives/C02QSAC6BJ8/p1704992900441539?thread_ts=1704731085.925159&cid=C02QSAC6BJ8).

You can see how the page looks now [here](https://help.expensify.com/articles/expensify-classic/getting-started/Employees).

Well work with Design team to make sure this is refined and looks up to par then @rushatgabhane will implement.

To do's:
- [ ]  Design to create mock up/ provide accurate font
- [ ] -Create PR for @rushatgabhane to implement the change

**Comment by Temidayo32** [comment]
> Deliverables:
> Within HelpDot we'll want to create a tab structure for the end user to be able to select the view of whether they are on IOS, Android or Desktop. Please see example [here](https://expensify.slack.com/archives/C02QSAC6BJ8/p1704992900441539?thread_ts=1704731085.925159&cid=C02QSAC6BJ8).

@caitlinwhite1  The Link here isn't working

**Comment by Temidayo32** [comment]
Contributor details
Your Expensify account email: temidayoazeez032@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ca8912577fb1eeed

**Comment by dubielzyk-expensify** [comment]
I started some explorations and further [discussions in Slack](https://expensify.slack.com/archives/C02QSAC6BJ8/p1705381332246159)

**Comment by dubielzyk-expensify** [comment]
Seems like this is being worked on at the moment

**Comment by rushatgabhane** [comment]
This is done and merged. Issue can be closed.
https://help.expensify.com/articles/expensify-classic/getting-started/Join-your-company's-workspace




<img width="1504" alt="image" src="https://github.com/Expensify/App/assets/29673073/0e795711-9155-4804-9d4b-6ff7b5d0bfbc">
