### ISSUE TITLE
[$500] Chat - Composed message still displayed in compose box after Ctrl+K and user select

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to https://staging.new.expensify.com/
2. Type something in the compose box but don't send the message
3. Press on CTRL + K
4. Search for a user and navigate to the conversation

## Expected Result:
The message you were previously composing is not displayed in the compose box

## Actual Result:
The message you were previously composing is still displayed in the compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b2f43eb3-70d3-40a5-8738-ccdac60aa706

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6cae98f12b7b6db</li>
        <li>Upwork Job ID: 1746910171171639296</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
I'm not sure if this is a bug

**Comment by Seroxdesign** [comment]
Hello, 

I am not sure if this is currently being worked on, but regardless I'll leave a response on how I'd fix this, I would set up a listener for a switch in user chats and reset the chatbox message if chat changes, it could also be done on the CTRL + K commands.

**Comment by johnbchron** [comment]
@lanitochka17 Can we get confirmation that this is a bug? The video appears to re-select the same chat, which if that was the intended action, the bug would be regarding the population of the draft comment, which seems like not a bug given the existence of `getDraftComment`, etc.

**Comment by johnbchron** [comment]
Contributor details
Your Expensify account email: expensify@jlewis.sh
Upwork Profile Link: https://www.upwork.com/freelancers/~018db43a7e191535c4

**Comment by MitchExpensify** [comment]
I don't see how this is a bug, it looks like the draft feature that is working as intended

**Comment by lanitochka17** [comment]
@MitchExpensify Hello
Test rail, step 17: https://expensify.testrail.io/index.php?/tests/view/4183257&group_by=cases:section_id&group_order=asc&group_id=229066

**Comment by MitchExpensify** [comment]
Yeah I think this is only a bug if the message you were composing for User A showed in the compose box when navigating to a chat with anyone other than user A. Perhaps we update step 17 to clarify that @lanitochka17 ?

**Comment by lanitochka17** [comment]
@MitchExpensify sounds good. Please will update step.

**Comment by MitchExpensify** [comment]
Thank you!
