### ISSUE TITLE
[HOLD for payment 2024-02-26] Room - Email in Concierge message is not copied when copied to clipboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34504]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a room
2. Go to the room
3. Send a text containing mention of a non-member user
4. Right click on Concierge message > Copy to clipboard
5. Paste the content

## Expected Result:
The email in Concierge message is copied

## Actual Result:
The email in Concierge message is not copied when copied to clipboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fb242f11-9771-4773-b681-77a03c1c8e95

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
Hm, what type of room is this? I created a workspace public room on my build that is before this one to confirm it works in production, and it never asked me if I wanted to invite the user. Then did the same on a private room, and it just invited without confirming. @lanitochka17

**Comment by situchan** [comment]
This is new feature from https://github.com/Expensify/App/pull/33665.
I think this can be fixed as follow-up by original author, not blocking deploy.
cc: @ishpaul777 @rushatgabhane

**Comment by jasperhuangg** [comment]
Contributor has opened a PR, not overdue!

**Comment by jasperhuangg** [comment]
Contributor is working on a draft PR, not overdue!

**Comment by jasperhuangg** [comment]
@ishpaul777 gotcha, sorry if I missed the ping. I've pinged the C+ channel to see if there are any takers for the review

**Comment by jasperhuangg** [comment]
@MitchExpensify Can we pay out @aimane-chnaif for PR review?
