### ISSUE TITLE
[HOLD for payment 2024-01-25] [HOLD for payment 2024-01-24] [$250] Split - Checkmark is not displayed when clicking on Split next to the user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34503]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Manual
2. Enter amount and proceed to participant selection page
3. Search for a user with no chat history
4. Click Split

## Expected Result:
Checkmark is displayed when clicking on Split next to the user

## Actual Result:
Checkmark is not displayed when clicking on Split next to the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec66b399-b6cf-47c6-b894-558646149b86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5d32ee19b7bd5d4</li>
        <li>Upwork Job ID: 1746941516473966592</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 28103739</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lukemorawski** [comment]
@FitseTLT that is weird. I cannot reproduce it on my machine

https://github.com/Expensify/App/assets/134388952/4f3b4d99-9e35-4612-bbf4-8a3267884344

1. are you sure you're on latest main?
2. is it reproducible on other accounts?
3. is it reproducible with other user names?

Any other clues would be very helpful

**Comment by FitseTLT** [comment]
@lukemorawski you are selecting a user from recent section (you should select from Contacts section) 👍

**Comment by lukemorawski** [comment]
@FitseTLT oddly, when searching for something, "Contacts" section vanishes and only "Recents" are available (with users from Contacts showing up in those new recents).
So still can't reproduce this. Though, looks like your proposed solution should do the trick.

**Comment by FitseTLT** [comment]
@mountiny Payment Overdue

**Comment by mountiny** [comment]
$250 to @FitseTLT 

and $250 to @allroundexperts

**Comment by twisterdotcom** [comment]
Payment Summary:

- @FitseTLT paid $250 [here](https://www.upwork.com/nx/wm/offer/new/7547980)
- @allroundexperts paid $250 [here](https://www.upwork.com/nx/wm/offer/new/16506263)

**Comment by allroundexperts** [comment]
@twisterdotcom I get paid through the App. You can cancel my upwork invitation. Thanks

**Comment by twisterdotcom** [comment]
Ah! Of course. Okay. Hang on, will cancel and update the Payment Summary.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts based on [this summary](https://github.com/Expensify/App/issues/34503#issuecomment-1924327879).
