### ISSUE TITLE
[$500]  mWeb/Safari - Chat  - Cursor isn't seen in the input field when triggering edit mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34512]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33365
## Action Performed:
Scenario 1:
1. Navigate to staging.new.expensify.com ? log in
2. Navigate to any chat
3. Send a message and start a thread
4. Send additional messages
5. Long tap on a message within the thread
6. Select "Edit comment"

Scenario 2:
1. Navigate to staging.new.expensify.com > log in
2. Navigate to any chat
3. Send a message
4. Long tap on the sent message
5. Select "Edit comment"

## Expected Result:
Cursor should be visible in the input field as soon as edit mode is triggered

## Actual Result:
Cursor isn't seen in the input field when triggering edit mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/445693eb-9a6c-4b2a-b944-3a6318eb8569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01732e019ea63f840f</li>
        <li>Upwork Job ID: 1746932216922673152</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by itsspriyansh** [comment]
Scenario 1:

Navigate to staging.new.expensify.com ? log in
Navigate to any chat
Send a message and start a thread
Send additional messages
Long tap on a message within the thread
Select "Edit comment"
Scenario 2:

Navigate to staging.new.expensify.com > log in
Navigate to any chat
Send a message
Long tap on the sent message
Select "Edit comment"

**Comment by twisterdotcom** [comment]
Downgrading to Weekly as not that important. It'll be good to fix though.

**Comment by twisterdotcom** [comment]
@Krishna2323 I can reproduce: 

https://github.com/Expensify/App/assets/9133401/39aef470-e417-43fa-9223-a83a72291373

**Comment by twisterdotcom** [comment]
This is still happening now. I'm going to downgrade, but I still think it'd be nice to have a fix here.

**Comment by twisterdotcom** [comment]
Okay, gonna close as we have no proposals and it's a very minor issue.
