### ISSUE TITLE
[HOLD for payment 2024-01-25] [HOLD for payment 2024-01-24] [$500] Task - Unable to add Assignee when creating a task

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33852
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account
3. Tap on the green plus button (FAB)
4. Select Assign task
5. Fill in the Title and Description fields
6. Click next
7. Click on the Assignee field
8. Try adding any member

## Expected Result:
User should be able to add Assignee at the time of task creation

## Actual Result:
Unable to add Assignee when creating a task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fd1b8091-d2c2-4d6a-8b9e-d64821b494d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed3d026d1f4f714a</li>
        <li>Upwork Job ID: 1746959701793779712</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 28102476</li>
<li>mkhutornyi | Contributor | 28102477</li>
</ul></li>
    </ul>
</details>

**Comment by flodnv** [comment]
Can we entirely remove the check for `!props.route.params`?

**Comment by flodnv** [comment]
cc @roryabraham @getusha @rayane-djouah

**Comment by roryabraham** [comment]
> // If there's no route params, we're creating a new task

In general I think it's a very bad practice to have logic hinge on whether or not there are route params ... as evidenced by this issue.

It sounds like @mkhutornyi is saying that what we really should have been checking was whether there's a reportID in the route params. (should we also make sure it's valid?)

**Comment by roryabraham** [comment]
In this case, there's already a local variable `report` that [comes from the reportID in route params](https://github.com/Expensify/App/blob/fb0b1d1c27a3341d49dabdb4cd7975cc4f5c8873/src/pages/tasks/TaskAssigneeSelectorModal.js#L133-L138). So I think we can update that check to use that existing `report` variable:

- Swap out `props.route.params` with `report` in the `selectReport` function
- Wrap `selectReport` with `useCallback`

<details>
<summary>**Full diff**</summary>

```diff
diff --git a/src/pages/tasks/TaskAssigneeSelectorModal.js b/src/pages/tasks/TaskAssigneeSelectorModal.js
index a4fc61910b..cc2bf96432 100644
--- a/src/pages/tasks/TaskAssigneeSelectorModal.js
+++ b/src/pages/tasks/TaskAssigneeSelectorModal.js
@@ -184,29 +184,32 @@ function TaskAssigneeSelectorModal(props) {
         return sectionsList;
     }, [filteredCurrentUserOption, filteredPersonalDetails, filteredRecentReports, filteredUserToInvite, props]);
 
-    const selectReport = (option) => {
-        if (!option) {
-            return;
-        }
+    const selectReport = useCallback(
+        (option) => {
+            if (!option) {
+                return;
+            }
 
-        // Check to see if we're creating a new task
-        // If there's no route params, we're creating a new task
-        if (!props.route.params && option.accountID) {
-            Task.setAssigneeValue(option.login, option.accountID, props.task.shareDestination, OptionsListUtils.isCurrentUser(option));
-            return Navigation.goBack(ROUTES.NEW_TASK);
-        }
+            // Check to see if we're creating a new task
+            // If there's no route params, we're creating a new task
+            if (!report && option.accountID) {
+                Task.setAssigneeValue(option.login, option.accountID, props.task.shareDestination, OptionsListUtils.isCurrentUser(option));
+                return Navigation.goBack(ROUTES.NEW_TASK);
+            }
 
-        // Check to see if we're editing a task and if so, update the assignee
-        if (report) {
-            if (option.accountID !== report.managerID) {
-                const assigneeChatReport = Task.setAssigneeValue(option.login, option.accountID, props.route.params.reportID, OptionsListUtils.isCurrentUser(option));
+            // Check to see if we're editing a task and if so, update the assignee
+            if (report) {
+                if (option.accountID !== report.managerID) {
+                    const assigneeChatReport = Task.setAssigneeValue(option.login, option.accountID, report.reportID, OptionsListUtils.isCurrentUser(option));
 
-                // Pass through the selected assignee
-                Task.editTaskAssignee(report, props.session.accountID, option.login, option.accountID, assigneeChatReport);
+                    // Pass through the selected assignee
+                    Task.editTaskAssignee(report, props.session.accountID, option.login, option.accountID, assigneeChatReport);
+                }
+                return Navigation.dismissModal(report.reportID);
             }
-            return Navigation.dismissModal(report.reportID);
-        }
-    };
+        },
+        [props.session.accountID, props.task.shareDestination, report],
+    );
 
     const isOpen = ReportUtils.isOpenTaskReport(report);
     const canModifyTask = Task.canModifyTask(report, props.currentUserPersonalDetails.accountID, lodashGet(props.rootParentReportPolicy, 'role', ''));
```

</details>

**Comment by roryabraham** [comment]
Actually, hold off for one sec, @mkhutornyi I might've been too quick to assign you.

**Comment by roryabraham** [comment]
No C+ proposal review here.

**Comment by roryabraham** [comment]
@mkhutornyi this is an `Hourly` issue, which means you should update it with your progress _at least_ every hour. When do you estimate you'll have a PR ready for review?

**Comment by mountiny** [comment]
Tested, fixed, thanks!

**Comment by flodnv** [comment]
Regression proposal:

1. Tap on the green plus button on the main screen of the app (FAB)
2. Select Assign task
3. Fill in the Title and Description fields
4. Click next
5. Click on the Assignee field
6. Try adding any member
7. Select 'share somewhere' to someone else
8. Create the task
9. Make sure it is sent and assigned to the member from (6), and shared to the other person from (7).

**Comment by NicMendonca** [comment]
@mkhutornyi you've been paid! all set here
