### ISSUE TITLE
Android - Avatar - Avatar is not grayed out evenly in offline mode or when pressing on it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34521]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34093
## Action Performed:
1. Go offline
2. Go to Settings > Workspaces > any workspace
3. Go to Members > Invite
4. Invite a few users with default avatar

## Expected Result:
The default avatar will appear grayed out evenly

## Actual Result:
The default avatar does not have even opacity. Some appear as if it is not completely grayed out (the avatar is partially grayed out; some area of the avatar is not grayed out)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

<img width="771" alt="Bug6343238_1705339607039!Screenshot_2024-01-16_at_01 14 31" src="https://github.com/Expensify/App/assets/78819774/04f30666-c77c-4010-b3b8-28dc92c728c1">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Hello 
This issue is still reproducible on the latest build v1.4.25-4
This issue is reproducible on only Android phone ( no iPhone)

![tempFileForShare_20240116-043727](https://github.com/Expensify/App/assets/78819774/31d73ea6-6e0b-4612-8f27-bd939bf5d5b5)

**Comment by cead22** [comment]
Actually, let's not block on this. This happens on android devices when offline, so this feels like an edge case that can go through the regular bug process

**Comment by alexpensify** [comment]
Got it, I will run some tests on my android device and figure out the next steps like if this fits in a wave.

**Comment by alexpensify** [comment]
Other GHs and customer tasks have been a higher priority, I will get to this one early next week.

**Comment by alexpensify** [comment]
No update yet.

**Comment by alexpensify** [comment]
No update yet

**Comment by alexpensify** [comment]
Closing - I tested on my android device and am unable to replicate 

![image](https://github.com/Expensify/App/assets/8107070/4ddaeb84-247f-4ac7-b1d7-5c207d138a03)
