### ISSUE TITLE
 IOU - The paid IOU shows a message about the disabled category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34536]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable categories and add 3 categories, add an employee to the policy.

Steps:
1. Open https://staging.new.expensify.com/
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a WS room
8. Click on "Show more"
9. In the "Category" section, select any category
10. Complete the IOU
11. Open https://staging.expensify.com/
12. Log in to the admin account
13. Navigate to the Collect group policy settings
14. In the category tab, disable the employee's selected category from step 9
15. Open https://staging.new.expensify.com/
in incognito mode.
16. Log in as an administrator
17. Go to the employee report and pay the IOU
18. Under the employee's account, open the IOU details

## Expected Result:
The message about the disabled category should disappear after IOU payment

## Actual Result:
The paid IOU shows a message about the disabled category

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5d6871a0-97e9-4528-9e6d-cc65b2b44b4d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment]
> The message about the disabled category should disappear after IOU payment

This is not the expected behavior, so closing. Adding the source of expected behavior can be useful when logging bugs


Violations seem to be working correctly here, and they're behind a beta, so even if this wasn't the expected behavior, we shouldn't block on violations for the time being
