### ISSUE TITLE
Login -When open public room link and sign in incorrect magic code message displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34532]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: create a room with tasks and copy link
1. Navigate to the public room via deeplink, e.g. https://staging.new.expensify.com/r/1898619590844985
2. Tap on any task without an assignee
3. Select Assignee
4. Enter the email of a user who has not joined the room yet
5. Enter a magic code

## Expected Result:
User is returned to the task details page

## Actual Result:
After tapping the "Sign in" button, the spinner is displayed briefly, but the user is still on the login page. After tapping the button the second time, the message about the incorrect magic code is displayed. When the user goes back to the room, they are logged in.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/343ceb1d-f2ab-45d1-a336-9f0355047022

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Issue is not reproducible in production

https://github.com/Expensify/App/assets/93399543/5fa470f3-c579-423f-a9c5-06eb55cdae58

**Comment by marcochavezf** [comment]
It seems this is a regression from https://github.com/Expensify/App/pull/33426

**Comment by marcochavezf** [comment]
Confirmed that's the offended PR and created a straight revert PR https://github.com/Expensify/App/pull/34552

**Comment by mountiny** [comment]
CP done, asking QA to retest

**Comment by kbecciv** [comment]
@marcochavezf @mountiny Issue is no longer reproduced, build 1.4.25-7

https://github.com/Expensify/App/assets/93399543/0fa3e953-83b3-4c1a-b19f-452553337b96

**Comment by mountiny** [comment]
Thanks
