### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] IOU - In BNP, cursor displayed but unable to paste if amount already entered

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34531]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25.1
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab--- request money
3. Enter 2 digit amount
4. Select & copy the amount
5. Note the cursor shown next to 2 digit amount.
6. Try to paste the amount.

## Expected Result:
In BNP, if cursor displayed user should be able to paste even if amount already entered.

## Actual Result:
In BNP, cursor displayed but unable to paste if amount already entered.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/08503bf9-23ea-4b30-8d2b-da3af54783a2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfa5ca43b4c5842c</li>
        <li>Upwork Job ID: 1746995156396044288</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28114560</li>
<li>tienifr | Contributor | 28114561</li>
</ul></li>
    </ul>
</details>

**Comment by Ykumar1415** [comment]
I tried tried to produce the issue in my local dev environment and found the same.

**Comment by Ykumar1415** [comment]
I tried tried to produce the issue in my local dev environment and found the same.

**Comment by conorpendergrast** [comment]
Ok, got it - so if I'm right the problem is that you can tap directly on the existing text to paste over that, but you can't tap after the number to past *after* it. 

I am confirming if this should be part of one of our VIP projects [via an internal channel](https://expensify.slack.com/archives/C05RECHFBEW/p1705678746726999).

@akinwale how does @tienifr's proposal look?

**Comment by akinwale** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/34531#issuecomment-1893216293) correctly identifies the problem and the proposed solution is adequate.

@tienifr You would need to also test with the text field containing the max length of digits (10, iirc) to make sure that the padding does not cut off digits at the edges.

🎀👀🎀 C+ reviewed

**Comment by thienlnam** [comment]
Just assigned - not overdue

**Comment by conorpendergrast** [comment]
Payouts due:

- [x] Contributor: $500 @tienifr - [contract](https://www.upwork.com/nx/wm/workroom/36104984/overview)
- [x] Contributor+: $500 @akinwale - [contract](https://www.upwork.com/nx/wm/workroom/36093353/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01bfa5ca43b4c5842c).

**Comment by conorpendergrast** [comment]
All paid; just the C+ checklist now please @akinwale!

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Just an edge (😁) case with the input area not being wide enough to recognise long presses.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
* Launch the Expensify app on Android
* Open the global create menu and select Request money
* Select the Manual tab if it is not already active
* Enter any amount
* Long-press at the end of the amount
* Verify that the context menu easily shows up

Do we agree 👍 or 👎?
