### ISSUE TITLE
Attachment images not displayed inline in email notifications

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#34558]
**PROBLEM**
Currently, image attachments are not being embedded in-line in our email notifications. Instead, they are attached to the email and we display a blank picture-sized space.

<img width="584" alt="Screenshot 2024-01-16 at 9 32 33 AM" src="https://github.com/Expensify/App/assets/19366280/77baa6e0-e7fe-4f17-9f30-5bbdcebc5431">

This might not be our fault, as users have been seeing this issue in Gmail for the past few months: https://www.googlecloudcommunity.com/gc/Workspace-Q-A/Inline-images-getting-silently-converted-to-attachments-AFTER/td-p/636996

**SOLUTION**
Investigate if this is our fault and fix it if so

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ec38f47a67a83fd</li>
        <li>Upwork Job ID: 1747175655669231616</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by Gonals** [comment]
Removing C+, as this is all backend

**Comment by Gonals** [comment]
This is only happening for multi-people conversations. 1-1 DMs work fine

**Comment by Gonals** [comment]
... And everything works well in Dev

**Comment by joekaufmanexpensify** [comment]
Sounds good! Let me know if anything comes up I can help with.

**Comment by Gonals** [comment]
Found the issue. PR incoming

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by joekaufmanexpensify** [comment]
@Gonals no other PRs are needed here, right? I see the web PR is out on prod.

**Comment by Gonals** [comment]
Yep! I have a follow-up to use thumbnails, but that has its own issue. Closing this

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by lanitochka17** [comment]
Hello 
Issue is still reproducible on the latest build 1.4.44-0

![image (20)](https://github.com/Expensify/App/assets/78819774/1f58ef04-6b6c-4559-9735-1725a2f60703)

Has the issue been fixed or do you need to open a new one?
