### ISSUE TITLE
[$500] Login - Only a portion of the "Sign in with Apple" screen is in the light theme

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34568]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in as any user and set the theme to light
2. Log out
3. Start signing in on the desktop app by clicking on the Apple Sign In icon (or directly navigate to https://staging.new.expensify.com/sign-in-with-apple)

## Expected Result:
The "Sign in with Apple" screen should be completely in light mode when the theme is set accordingly.

## Actual Result:
When the theme is set to light, only a portion of the "Sign in with Apple" screen is in the light theme.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/909b16fe-650b-4ebd-a800-2a8bc66dafed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132d173bc9fbd9f48</li>
        <li>Upwork Job ID: 1747239638950387712</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The left part of the apple sign is shown as light mode.

### What is the root cause of that problem?
The color follows the system mode when logged out. To always keep it dark, on sign-in page, we wrap the component with a theme provider and provide a static mode, that is dark.
https://github.com/Expensify/App/blob/2f1b770016a185d4e9d444f2e8aaa1759ee7e1b3/src/pages/signin/SignInPage.js#L294-L308

But we don't do this for ThirdPartySignInPage.

### What changes do you think we should make in order to solve the problem?

Follow the same pattern as SignInPage in ThirdPartySignInPage.

**Comment by hetrox8** [comment]
There is a small minor change needed and that is the time taken to load the website it take a little bit long and i would suggset try work on this as 50% of clients abandon webpages that take more than 3sec . Below is a test from google speed insight
![Screenshot 2024-01-16 161729](https://github.com/Expensify/App/assets/108791588/3790d695-8a78-40d8-994a-e01e643a1e1c)

**Comment by adelekennedy** [comment]
huh - I get lightmode when I sign in, honestly I think this is a small issue that's not tied to performance

**Comment by bernhardoj** [comment]
@adelekennedy hi, I think it would be nice to fix this visual issue (theme inconsistencies) as it's easily noticeable.
<img width="806" alt="image" src="https://github.com/Expensify/App/assets/50919443/172e4689-afe4-4a8e-937b-cdd7428e6f69">
