### ISSUE TITLE
[HOLD for payment 2024-01-30] [HOLD for payment 2024-01-25] [HOLD for payment 2024-01-24] [$500]  Android  - App crashes when downloading attachments

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34569]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user has a device running Android 14
1. Open the app and log in
2. Navigate to a chat with some attachments
3. Open any attachment
4. Tap the download icon

## Expected Result:
The attachment has been successfully downloaded, the pop-up is displayed

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9e213364-4da9-4665-a5b0-2c28c6baa4e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d74c3eb5115eee4f</li>
        <li>Upwork Job ID: 1747295636132077568</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by Gonals** [comment]
@kbecciv, I can't seem to reproduce this on Staging (Android).

**Comment by mountiny** [comment]
@situchan could repro on android 14 and not in android 11

**Comment by mountiny** [comment]
Discussed in slack, lets do the patch for now and then test updating to latest

**Comment by mountiny** [comment]
Adding appropriate labels here and PR is ready for review.

@mkhutornyi To clarify, I think for a full reward here, we should do the full update of the package as you have mentioned in your solutions to remove the patch, which is just to resolve the deploy blocker. 

Once we handle that deploy blocker, can you raise a PR for an update of the package/ removal of the patch where we can do a full review/ testing?

**Comment by mountiny** [comment]
Removing the label, will ask QA to test the CPed PR

**Comment by mountiny** [comment]
@mkhutornyi you may already start preparing the PR to update the package and remove the patch. Thanks!

**Comment by Psm135** [comment]
I think you download image and this process on main thread that's why its crash

**Comment by kadiealexander** [comment]
@situchan don't forget about the checklist!

**Comment by situchan** [comment]
FYI: I don't need payment here

**Comment by kadiealexander** [comment]
Thanks @situchan

**Comment by situchan** [comment]
https://github.com/Expensify/App/issues/31381
