### ISSUE TITLE
[$500] IOU - In a tax-enabled employee account, after creating a manual request, the tax details are not displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34576]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Interna Team
**Slack conversation:**

## Action Performed:
Pre-condition: Enable tax option in old dot
1. Go to https://staging.new.expensify.com/
2. Login employee account
3. Tap on employee Workspace chat
4. Tap plus icon near compose
5. Tap request money--- Manual
6. Enter an amount and tap next
7. Enter merchant field
8. Tap show more and note tax and tax amount field shown
9. Tap request
10. Tap on IOU created to open IOU details page

## Expected Result:
In a tax-enabled employee account, after creating a manual request, the tax details are displayed

## Actual Result:
In a tax-enabled employee account, after creating a manual request, the tax details are not displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2c71a4c9-02c7-4d84-83bf-3da793f1b20b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7f9e81ebab2f5cf</li>
        <li>Upwork Job ID: 1747246289966477312</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment]
This is not a bug. Feature is work in progress under wave project here https://github.com/Expensify/Expensify/issues/305057#issuecomment-1889237055
