### ISSUE TITLE
[$500] Sign out - Page gets unresponsive after sign out when login with Abracadabra

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34575]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Enter email address and click Continue
3. Navigate to the email and copy the login link
4. Paste it to new tab and change to staging
5. Navigate to the original tab and hit Sign out

## Expected Result:
User should successfully sign out from New expensify page

## Actual Result:
Page gets unresponsive after sign out when login with Abracadabra

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8921a16f-c96b-4e36-9221-58eeae14ae2b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff3aff1986d09d05</li>
        <li>Upwork Job ID: 1747259844652462080</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Can this be retested on the latest staging version please

**Comment by isagoico** [comment]
Still able to reproduce this issue in Web, build v1.4.25-6
![image](https://github.com/Expensify/App/assets/44479856/37f78322-e7fa-4993-b2b7-6bc866f10cb1)

**Comment by isagoico** [comment]
Issue still reproducible in 25-6. 

![image](https://github.com/Expensify/App/assets/44479856/470f34cc-322e-4c3a-8b7e-bb6eae8008ef)

**Comment by situchan** [comment]
@AnshuAgarwal24 can you share console error?

**Comment by ikevin127** [comment]
I cannot reproduce the issue, but there's some weird behaviour on my side like:
- upon login, only 1-2 reports are showing in the LHN + report open avatars are not showing
- upon signing out and being redirected to login page, focus mode gets activated and the modal appears
- post-login loading times and overall fetching is very slow and also the Abracadabra page when link is opened

<details>
<summary>Weird behaviour video</summary>

https://github.com/Expensify/App/assets/56457735/09843204-89bf-4923-bf69-a03ffb3d2d34

</details>

**Comment by mountiny** [comment]
Could we maybe try reverting the onyx bump and see if this behaviour gets better?

**Comment by mountiny** [comment]
I am trying a test build here and we can see if this is any better there https://github.com/Expensify/App/pull/34596

**Comment by situchan** [comment]
I suspect many similar deploy blockers came from Onyx. So worth trying revert

**Comment by mountiny** [comment]
QA confirmed the fix
