### ISSUE TITLE
Scan - Duplicate "receipt scanning failed" messages when the scanning fails

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34579]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.25-6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM.
2. Create a scan request with a receipt that will fail the scanning.
3. When the scanning fails, go to request details page.

## Expected Result:
There will be only one "receipt scanning failed" message.

## Actual Result:
There are two "receipt scanning failed" messages; one from Expensify, another one below the receipt preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/427dccd8-0f7b-43a5-9136-bf8b079473ea

![image](https://github.com/Expensify/App/assets/93399543/2f6c8539-11a9-4a7a-9a5b-acfa3e179212)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abzokhattab** [comment]
which message of the two should be displayed?

**Comment by mountiny** [comment]
this is not a deploy blocker, also touching the violations project cc @cead22 for visibility, added to wave6 project but not sure what to do now, the report action in the chat is correct so we might just want to update the copy of the receipt red warning

This is up for discussion first though

**Comment by iwiznia** [comment]
ok going to put this through the regular assignment flow then

**Comment by cead22** [comment]
> There will be only one "receipt scanning failed" message.

I don't think we've agreed that this is the expected outcome, so we should bring this discussion to slack first. AFAICT this is working as currently designed, so closing for now
