### ISSUE TITLE
Scan split - "Receipt not verified" appears despite successful scanning in group splitting

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34572]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM.
2. Create a scan request with a valid receipt.
3. When the scanning is complete, go to request details page.
4. Note that there is no "Receipt not verified. Please confirm accuracy." message
5. Go to a group chat.
6. Create a scan request with a valid receipt.
7. When the scanning is complete, go to request details page.

## Expected Result:
There is no "Receipt not verified. Please confirm accuracy." message since the scanning is complete.

## Actual Result:
"Receipt not verified. Please confirm accuracy." message shows up below receipt preview, when the scanning is complete without intervention. This issue only occurs with Scan split in group chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/18e7e354-0ba5-4d2a-827e-a934686c7175

![E receipt ](https://github.com/Expensify/App/assets/93399543/7af73253-2d26-4e7a-8a4a-88f11bff52de)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@cead22 this is also related to violations it seems, not a deploy blocker added to the wave6 project in the meantime
