### ISSUE TITLE
Chat - Messages sent with device time in the past make them appears in wrong order

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34578]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30605

## Action Performed:
1. Change device's time to be 30 seconds behind
2. Login to the app
3. Go to any report
4. Send a few messages in a row

## Expected Result:
Messages must be in correct order

## Actual Result:
Messages at first appear in the wrong order. After a second they appear correctly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/340089a0-a454-4173-933c-8963efe1a24f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment]
This is reproducible in production as well. Not a deploy blocker

**Comment by nkuoch** [comment]
I think it's a very edge case and not a priority. Closing.
