### ISSUE TITLE
[$500] mweb - Specific message sent in room created as "public" your message flagged shown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34574]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room created with visibility "Public"
3. Send the specific message @
:dolls: :dolls: :laughing::laughing::laughing::laughing::laughing::innocent::innocent::speech_balloon:
4. Note concierge "your message is flagged" displayed.
5. Navigate to LHN
6. Tap on a room created with visibility "Workspace"
7. Send the specific message @
:dolls: :dolls: :laughing::laughing::laughing::laughing::laughing::innocent::innocent::speech_balloon:
8. Note no concierge "your message is flagged" displayed.

## Expected Result:
When specific message sent in room created as "public" and in "Workspace" room same behaviour must be shown.

## Actual Result:
When specific message sent in room created as "public" your message flagged is shown, same message posted in "Workspace " room no concierge flagged message displayed. Inconsistent behaviour shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e92635d2-0ece-4e91-95b2-1c363c278ff2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5c3a96968162071</li>
        <li>Upwork Job ID: 1747244515478990848</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by s-alves10** [comment]
Not reproducible on the latest main
