### ISSUE TITLE
[$500] mweb - Tapping back after adding a receipt lands on the same request details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.25-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM.
2. Create a manual request.
3. Open request details page.
4. Tap 3-dot menu > Add receipt.
5. Add a receipt.
6. Tap back button on the top left corner.

## Expected Result:
The app returns to IOU report page.

## Actual Result:
The app lands on the same request details page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/904a1796-067a-4c05-beba-256f651b0796

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190b4400e8d64b4de</li>
        <li>Upwork Job ID: 1747242100414537728</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
Same root cause as https://github.com/Expensify/App/issues/34379

**Comment by Ykumar1415** [comment]
I tried the issue and found the same problem.

**Comment by Ykumar1415** [comment]
Contributor details
Your Expensify account email:yogeshsaini1415@gmail.com
Upwork Profile Link:https://www.upwork.com/freelancers/~0162bc67ca990f7095
