### ISSUE TITLE
[$500] Workspace - User redirected to launching expensify screen after selecting free plan on OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log into ND with an existing account
2. Log into OD with a different account
3. In OD navigate to Settings > Workspaces
4. Click on New Workspace and select Free plan

## Expected Result:
User is redirected to ND and lands on new workspace settings

## Actual Result:
User lands on the "Launching Expensify" screen and is not redirected to ND after waiting for a while. On the original ND tab "Something went wrong screen" is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bb7d428e-d1bb-4978-b47f-b19e879bdf67

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01167f01a930e82f63</li>
        <li>Upwork Job ID: 1747326513973366784</li>
        <li>Last Price Increase: 2024-01-16</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/ccc7139e-9161-4c96-91a3-d90b9df7eb9f

**Comment by stitesExpensify** [comment]
@lanitochka17 can you re-test this please? This CP should have fixed this issue https://github.com/Expensify/Web-Expensify/pull/40515

**Comment by lanitochka17** [comment]
Checking with QA team will back to you shortly. Thank you

**Comment by lanitochka17** [comment]
Issue is still reproducible


https://github.com/Expensify/App/assets/78819774/5ef7989e-0d3b-4057-a31e-8e598b1fac25

**Comment by isagoico** [comment]
Issue not reproducible anymore in build 25-10 🎉 
https://github.com/Expensify/App/assets/44479856/c467e157-6a16-40aa-ad43-d1ba606a4396

**Comment by mountiny** [comment]
QA confirmed the fix 🎉
