### ISSUE TITLE
[HOLD for payment 2024-04-25] [$250] Remove IOUCurrencySelection.js and copy any changes since Nov 27 into IOURequestStepCurrency.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#34607]
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

# Problem
The app has two redundant components:

**Old Component**: `IOUCurrencySelection`
**New Component** `IOURequestStepCurrency`

# Solution
Following the examples ([example 1](https://github.com/Expensify/App/pull/33646), [example 2](https://github.com/Expensify/App/pull/32764)), the Old Component needs to be completely removed from the codebase

1. Look at the history of the Old Component
1. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes
1. Replace all uses of the Old Component with the New Component
2. Remove all traces of Old Component
3. Be sure to update all routes and navigation to use the new `:action` param (instead of being hard-coded with `"create"`)
4. Update any logic like `isEditing` to use the new action param from the route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107fbe87259b2ef2c</li>
        <li>Upwork Job ID: 1747632778655997952</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28119949</li>
<li>ZhenjaHorbach | Contributor | 28119950</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by njmulsqb** [comment]
I would love to take this!

**Comment by sakluger** [comment]
@mountiny are we treating this like a TS Migration issue? I.e. do we require proposals or just a volunteer?

**Comment by tgolen** [comment]
We should get a full proposal to ensure that all the paths are covered
properly. The initial instructions give a brief overview, but the code
should really be inspected to clearly understand all the necessary changes.

**Comment by sakluger** [comment]
Thanks @tgolen. @akinwale looks like we got a proposal [here](https://github.com/Expensify/App/issues/34607#issuecomment-1894562054), could you please give it a look to see if it works well?

**Comment by akinwale** [comment]
@ZhenjaHorbach Could you please provide more details about the files and the routes that need to be updated in your proposal? Thanks.

**Comment by akinwale** [comment]
We can move forward with @ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/34607#issuecomment-1894562054).

🎀👀🎀 C+ reviewed.

**Comment by dangrous** [comment]
Works for me! Assigning.

**Comment by dangrous** [comment]
how are we looking on this one @ZhenjaHorbach and @akinwale?

**Comment by dangrous** [comment]
responded in the PR! let me know if that makes sense

**Comment by dangrous** [comment]
Just updating the title to reflect that we're holding on https://github.com/Expensify/App/pull/35833

**Comment by DylanDylann** [comment]
@ZhenjaHorbach @akinwale No longer hold, let's process the next step

**Comment by mountiny** [comment]
$250 to @akinwale and to @ZhenjaHorbach

**Comment by sakluger** [comment]
All paid up! I don't think any new regression steps are needed since this is part of a larger project.
