### ISSUE TITLE
[HOLD for payment 2024-02-14] [$250] Remove MoneyRequestTagPage.js and copy any changes since Nov 27 into IOURequestStepTags.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#34612]
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

# Problem
The app has two redundant components:

**Old Component**: `MoneyRequestTagPage`
**New Component** `IOURequestStepTags`

# Solution
Following the examples ([example 1](https://github.com/Expensify/App/pull/33646), [example 2](https://github.com/Expensify/App/pull/32764)), the Old Component needs to be completely removed from the codebase

1. Look at the history of the Old Component
1. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes
1. Replace all uses of the Old Component with the New Component
2. Remove all traces of Old Component
3. Be sure to update all routes and navigation to use the new `:action` param (instead of being hard-coded with `"create"`)
4. Update any logic like `isEditing` to use the new action param from the route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0c8228cceba8683</li>
        <li>Upwork Job ID: 1747632892276064256</li>
        <li>Last Price Increase: 2024-01-17</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28119689</li>
<li>dukenv0307 | Contributor | 28119690</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
Would love to work on this

**Comment by stephanieelliott** [comment]
Hey @fedirjh looks like we have a few proposals here, could you please review?

**Comment by stephanieelliott** [comment]
Bump @fedirjh  -- are you able to review these proposals for us?

**Comment by stephanieelliott** [comment]
PR was CP'd to staging a few hours ago

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @dukenv0307 $250, paid via Upwokr 
 - Contributor+: @fedirjh $250, paid via Upwokr 
 
 Upwork job is here: https://www.upwork.com/jobs/~01f0c8228cceba8683
