### ISSUE TITLE
[ECARD TRANSACTIONS] transaction is missing an eReceipt and an amount, and showing an inconsistent merchant between NewDot and OldDot

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34623]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**AccountID** 2738970
**ReportID** ID: R008WqZKkDUn (Long ID: 1862398495519001)

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1705357257662249

## Action Performed:
1. Create a free workspace and set it as your default
2. Ensure you don't have any other paid workspace in the account
3. Incur a charge on an Expensify Card using the [paypal link](https://github.com/Expensify/Expensify/files/3974273/payButtons.html.zip)
4. Incur another charge on the Expensify Card using the [paypal link](https://github.com/Expensify/Expensify/files/3974273/payButtons.html.zip)

## Expected Result:
The expense should show an eReceipt and merchant that is consistent on both platforms

## Actual Result:
eReceipt is missing, and the merchant is mismatched between NewDot (says "PAYPAL") and OldDot (says "Expensify). You can see in the screenshots that the same expense is showing different info, and missing info in NewDot

![image](https://github.com/Expensify/App/assets/22508290/7640299f-9586-4d76-8b46-0a95c5f69f68)

![image](https://github.com/Expensify/App/assets/22508290/33bdc8c1-f7b5-424d-924a-c0588b5181e9)

**Update: 1/22/2024**: the amount updated to $0 for "PAYPAL", which is still not correct and inconsistent with OldDot

![image](https://github.com/Expensify/App/assets/22508290/bd77eb4c-865d-4122-a436-0a4d7938ef0e)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d216d9b6d144476</li>
        <li>Upwork Job ID: 1748140410820694016</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Removing hot pick since engineer will be assigned once C+ gives bow of approval

**Comment by dylanexpensify** [comment]
Ah no, let's keep this one internal (right @kevinksullivan?). Will post for volunteers today

**Comment by iwiznia** [comment]
Asked some questions here https://expensify.slack.com/archives/C05DWUDHVK7/p1705952908291029

**Comment by iwiznia** [comment]
For the merchant part, seems like the app is not receiving the modifiedMerchant correctly for some reason.

**Comment by iwiznia** [comment]
I can't reproduce this in dev 😞

**Comment by iwiznia** [comment]
I even tested updating the merchant in order to see if I saw the old merchant like in your screenshot:

<img width="1104" alt="image" src="https://github.com/Expensify/App/assets/521248/33ed494e-0867-4c7a-b32b-94df24af7475">

I think this might be solved already...

**Comment by kevinksullivan** [comment]
going to close this until I see it again
