### ISSUE TITLE
[HOLD for payment 2024-02-05]  Only allow policy owner / report submitter to update report field values 

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#34625]
Report field values can only be modified by policy owner / report submitter.
This is already blocked in the BE, but we will need to add FE handling to remove the ability to edit it in the FE

**Comment by allroundexperts** [comment]
PR: https://github.com/Expensify/App/pull/34889

**Comment by slafortune** [comment]
Reviewer: @allroundexperts owed $500 via NewDot
