### ISSUE TITLE
[HOLD for payment 2024-01-28] [ECARD SETTINGS] Expiration date in card details is using the wrong format

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34629]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1705442308576449

## Action Performed:
1. Set >$0 limit on card
2. Navigate to settings > wallet > virtual card > view details

## Expected Result:
The expiration date should be in the format `MM/YYYY`

## Actual Result:
The expiration date format is in `MMYY`

![image](https://github.com/Expensify/App/assets/22508290/4b0bacad-7486-4560-b0c3-ba601049c7ec)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ff444ac3f126e525</li>
        <li>Upwork Job ID: 1747738873658785792</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by abekkala** [comment]
@kevinksullivan @grgia does this need the external label?

**Comment by grgia** [comment]
@abekkala not yet, I am triaging all the card bugs today/tomorrow first

**Comment by grgia** [comment]
@AnshuAgarwal24 thank you for your proposal. I am taking this internally as there are a few issues on this page with style/formatting that I decided to group together. 

For next time, it's helpful to look for issues labeled with `Help Wanted` as those are actively reviewing proposals. It is also helpful if you post where in the code base you plan on making these changes, as your proposal on this PR repeated the expected result section, but did not go into depth on how you would make those changes. 

Thanks again, let me know if you have any questions or need help finding an issue to work on!

**Comment by mananjadhav** [comment]
@abekkala This is ready for payout. Can you please post a payout summary?

We don't have any offending PR for this one, and this was linked with two issues on design changes. I don't think we need regression steps for this one. @grgia wdyt?

**Comment by abekkala** [comment]
### PAYMENT DUE:

- PR Review: @mananjadhav $500

**Comment by JmillsExpensify** [comment]
$500 payment approved for @mananjadhav based on summary above.

**Comment by abekkala** [comment]
@mananjadhav before I close this out can you confirm that you've requested payment in NewDot?

**Comment by mananjadhav** [comment]
@abekkala Yes I've requested and it is approved.

**Comment by mananjadhav** [comment]
@abekkala I think we can close this one out
