### ISSUE TITLE
[ECARD TRANSACTIONS] Paying a report with pending transactions did not hold the pending transactions back onto a new processing report.

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34630]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1705442308576449

## Action Performed:
1. Create a free workspace and set it as your default
2. Incur a charge on an Expensify Card so that it's pending
3. Add a manual request
4. Tap into the report containing both expenses
5. Tap pay elsewhere while the expensify card transaction is still pending

## Expected Result:
The pending expense should be held back onto a new report

## Actual Result:
The pending expenses are kept on that report

![image](https://github.com/Expensify/App/assets/22508290/93dd2c4d-bb73-497f-a698-bda06d1b7be1)

![image](https://github.com/Expensify/App/assets/22508290/6b064b1e-49c3-43aa-9280-e8395608e74e)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a40b075c336a7dcf</li>
        <li>Upwork Job ID: 1748143271462105088</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by grgia** [comment]
Could this be related to this concept https://expensify.slack.com/archives/C07J32337/p1705531431691619
@mountiny @aldo-expensify

**Comment by dylanexpensify** [comment]
Removing hot pick since engineer will be assigned once C+ gives bow of approval

**Comment by aldo-expensify** [comment]
cc @cristipaval since you have been working on Open report migrations in Free workspaces

**Comment by luacmartins** [comment]
Auth PR in review. Gonna work on App PR tomorrow

**Comment by luacmartins** [comment]
Hmm so I see that the logic to move scanning receipts to a new report is only server side (we don't optimistically do that). I think we might wanna do the same for pending transactions since we need to confirm that they are still pending before moving them to the new report and having to clean up a mess in the frontend. That does mean that the transaction temporarily appears as paid, before being moved to the new report.

**Comment by luacmartins** [comment]
FYI @kevinksullivan ^

**Comment by luacmartins** [comment]
Given the above. We're done here and can close this issue since the Auth PR was merged and deployed today!
