### ISSUE TITLE
Web - Title row in expense report is clickable but does not open any editor

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34643]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Create a manual request.
3. Click on the preview to go to expense report.
4. Click on the title row.

## Expected Result:
The title editor opens because the title row is clickable and has an arrow on the right end.

## Actual Result:
The title editor does not open. Clicking on it does nothing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f6f48c1e-b3ac-4368-ba87-d7ec29eb1569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b6f0beca0fcf52a</li>
        <li>Upwork Job ID: 1747634777580498944</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
The feature is under Beta, and this is planned to be fixed as a follow-up: https://github.com/Expensify/App/pull/33392#issuecomment-1881750044

@allroundexperts, the "Title" here is lowercase, just FYI to not miss it:
<img width="200" alt="image" src="https://github.com/Expensify/App/assets/12595293/055f361f-afc7-4aba-a389-f9c9d38cdaef">

**Comment by rlinoz** [comment]
@paultsimura @allroundexperts humm, shouldn't the title be replaced with the result of the formula?

**Comment by mountiny** [comment]
Demoting, this is behind beta and qa has the beta enabled I think.

@rlinoz I think we can just assing @thienlnam and @allroundexperts to handle this one, it might still be at works

**Comment by mountiny** [comment]
Fat finger

**Comment by allroundexperts** [comment]
This is still in progress and can be closed. We have got it covered!
