### ISSUE TITLE
[$500] Users are randomly signed out of app 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#34653]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Unknown
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705503666408269

## Action Performed:
Unknown reproducible steps atm. 

## Expected Result:
User should not be randomly signed out

## Actual Result:
Users are being randomly signed out of the app. 

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
No visual evidence yet. 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176bfa2f128059e8d</li>
        <li>Upwork Job ID: 1747650096281808896</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by situchan** [comment]
I am signed out on web dev 30 min ago. (latest main branch)

**Comment by johnmlee101** [comment]
This also applied to OD :/

**Comment by isagoico** [comment]
Closing the issue as this was a query triggered here https://github.com/Expensify/Expensify/issues/360016#issuecomment-1892643435
