### ISSUE TITLE
[$500] IOU - Request details link with /edit/receipt opens Not here page with Receipt header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34659]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a manual expense without receipt
3. Navigate to request details page
4. Add /edit/receipt to the end of URL and navigate to it

## Expected Result:
The app should either open receipt upload page, or not here page without the Receipt header

## Actual Result:
The app opens not here page with Receipt header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ed8bfc3b-2bf8-444b-a524-71cdd6923a8a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b2f947836ddc62f</li>
        <li>Upwork Job ID: 1747659798092935168</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by akinwale** [comment]
@strepanier03 This can be closed based on https://github.com/Expensify/App/issues/34659#issuecomment-1896222499.

**Comment by strepanier03** [comment]
Thanks @akinwale - I was just coming to close this anyway lol.
