### ISSUE TITLE
Cancel payment - Inconsistency in amount update in system messages when amount is updated

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34650]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a manual expense
3. Go to expense report
4. Pay elsewhere the report
5. Click 3-dot menu > Cancel payment
6. Edit the requested amount
7. Return to expense report

## Expected Result:
The amount in owe message updates to the latest amount, while the amount in cancellation message should remain as the original amount since user cancels the payment for the initial amount

## Actual Result:
The amount in owe message does not update, but the amount in cancellation message updates to the latest amount, when it should be the other way around

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9c9f441c-a9c9-41b1-8307-42e24d35a435

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d75fd8b772fee381</li>
        <li>Upwork Job ID: 1747650076861669376</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by mountiny** [comment]
cc @Gonals Seems like the cancelled report action is connected to the transaction but it should keep the cancelled request amount/ currency in its message field so it represents the historical datapoint correctly

**Comment by mountiny** [comment]
I know, discussing in [Slack ](https://expensify.slack.com/archives/C01GTK53T8Q/p1705505620179849)

**Comment by mananjadhav** [comment]
@mountiny @Gonals Are we tracking the BE fix here? or elsewhere?

**Comment by Gonals** [comment]
We can track it here, but it'll still take me a couple of days before I get to it

**Comment by Gonals** [comment]
This will be fixed with the new Cancel Payment development

**Comment by Gonals** [comment]
Moving to weekly until then

**Comment by mananjadhav** [comment]
@Gonals Is the PR ready for review? Also I saw that another C+ is assigned for the PR related to this issue where I am assigned.

**Comment by Gonals** [comment]
> @Gonals Is the PR ready for review? Also I saw that another C+ is assigned for the PR related to this issue where I am assigned.

We reverted the original cancel payment PR, so this issue basically stopped existing. I'm keeping it around for tracking purposes (so I don't forget to implement this in the new Cancel Payments PR). 

I think we can actually go ahead and close this one new tht the backend changes merged.
