### ISSUE TITLE
[HOLD for payment 2024-03-18] [TS Migration] Standardize approach to Onyx pendingFields

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#34662]
Slack context: https://expensify.slack.com/archives/C0593T50UHG/p1705346773892779

### Problem

We do not have a consistent pattern for pendingFields in Onyx, resulting in multiple divergent implementations, greater likelihood of bugs, and developer overhead to choose the "correct" one.

### Solution

Standardize our approach to pendingFields in Onyx.

**Comment by roryabraham** [comment]
cc @blazejkustra @fabioh8010

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by roryabraham** [comment]
Sorry @AnshuAgarwal24, this topic was discussed in slack before an issue was created, and we already had an assignment in mind. I would've assigned them right away but because of our GitHub configuration they need to comment first before we can assign them.

**Comment by roryabraham** [comment]
Just answered some questions in the draft PR

**Comment by DylanDylann** [comment]
@roryabraham Could you help to assign a CME to this issue for payment?

**Comment by mountiny** [comment]
@puneetlath assigned you back since you have been previously assigned by the NewFeature label

I believe this is ready to payout to @DylanDylann for $250 for the review

**Comment by puneetlath** [comment]
@DylanDylann can you link me your Upwork profile?

**Comment by DylanDylann** [comment]
@puneetlath https://www.upwork.com/freelancers/~010c6310ab55f3d17d

**Comment by puneetlath** [comment]
@DylanDylann sent you an offer: https://www.upwork.com/nx/wm/offer/101473125

Please ping me on this issue once you've accepted.

**Comment by DylanDylann** [comment]
@puneetlath Accepted. Thanks

**Comment by puneetlath** [comment]
Paid, thanks everyone!
