### ISSUE TITLE
[HOLD for payment 2024-01-26] [HOLD for payment 2024-01-25] Cancel payment - Expense report with payment cancellation system message is not entirely deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34675]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new workspace
2. Go to workspace chat
3. Create a manual request
4. Edit the amount, description etc of the request to invoke system message
5. Delete the request
6. Note that the details page together with the system message is deleted
7. Create another manual request
8. Pay elsewhere the report
9. Go to expense report > 3-dot menu > Cancel payment

## Expected Result:
The report will be entirely deleted since there is no more request in the report

## Actual Result:
The report is not entirely deleted as the system message for payment cancellation still remains

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

Uploading Bug6345737_1705521965443!bandicam_2024-01-18_00-51-03-204.mp4…

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
[#wave7-collect-approvers](https://expensify.enterprise.slack.com/archives/C02NZ2HGJAZ)

**Comment by roryabraham** [comment]
It looks like the video upload failed here. A reproduction video would be helpful for me to understand this better

**Comment by mountiny** [comment]
It feels like the steps are missing last step saying: `Delete the report`

**Comment by roryabraham** [comment]
The offending PR was reverted.
