### ISSUE TITLE
[HOLD for payment 2024-02-26] [HOLD for payment 2024-01-26] [HOLD for payment 2024-01-25] Cancel payment - Inconsistency in reimbursement message after cancelling payment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34676]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a manual request
3. Open expense preview
4. Pay elsewhere the report
5. Refresh the page
6. Note that the reimbursement message is "You marked this report as manually reimbursed. This report will be reimbursed outside of Expensify."
7. Click 3-dot menu > Cancel payment
8. Refresh the page

## Expected Result:
The reimbursement message will remain the same

## Actual Result:
The reimbursement message changes to "You marked this report as reimbursed."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2b4dca78-2c44-456a-935b-57c7cfa015b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by blimpich** [comment]
Not a blocker.

**Comment by blimpich** [comment]
Probably related to https://github.com/Expensify/App/pull/33836. CC: @Gonals

**Comment by blimpich** [comment]
not overdue, waiting for automation to close

**Comment by blimpich** [comment]
not overdue, waiting for PR to close

**Comment by blimpich** [comment]
Closing as the fix for this was deployed.
