### ISSUE TITLE
[HOLD for payment 2024-01-26] [HOLD for payment 2024-01-25] Cancel payment - Title of cancelled expense report shows "Canceled" then back to "owes x"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34681]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [Member] Request money in the workspace chat.
2. [Member] Go to expense report.
3. [Admin] Pay the request.
4. [Admin] Cancel the payment.

## Expected Result:
The expense report title shows "paid amount · Canceled" in LHN and report

## Actual Result:
The expense report title shows "paid amount · Canceled" briefly then back to "owes amount" in LHN and report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bcc4c770-7c98-4b47-b7d6-fbcb374e4801

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Was this connected to some PR testing? I am not really following the video it looks like the tester is tapping a lot of stuff in sequence and not using the app like a real user would. Can they maybe slow down a bit?

**Comment by marcaaron** [comment]
>The expense report title shows "paid amount · Canceled" briefly then back to "owes amount" in LHN and report

Ok, I observed this while following the test steps. Not really sure if it's a blocker considering you'd have to catch this happening in realtime.

The app eventually lands in the correct state. Will check to see if there are any obvious PRs that could have caused this.

**Comment by marcaaron** [comment]
cc @Gonals this is the only PR obviously related to cancelling payments https://github.com/Expensify/App/pull/33836

Still gonna remove the blocker, but maybe you will want to follow up here.

**Comment by isabelastisser** [comment]
Hey, @marcaaron, do I need to process contributor payments here? There's no one assigned. Thanks!

**Comment by marcaaron** [comment]
Hmm I'm not really sure tbh. It looks like maybe the PR causing this was reverted. I'm just going to assume that there's no further action to take here and close this one for now.

**Comment by isabelastisser** [comment]
Thanks, Marc!
