### ISSUE TITLE
[HOLD for payment 2024-01-28] [ECARD SETTINGS] Fix Card Number Styling on Expensify Card Page

### ISSUE THREAD

**Issue by grgia** [Expensify/App#34682]
- Virtual card should be `•••• •••• •••• ••••`
- Physical card should not be bold

![Image](https://github.com/Expensify/App/assets/38015950/8ea5c618-0564-4926-bbbc-d55cfef20340)

**Comment by grgia** [comment]
Taking internally, but combining PR with another issue, so no need for labels / extra C+

**Comment by grgia** [comment]
hey @puneetlath, mind helping out with payment to @mananjadhav 

$500 for C+ review of https://github.com/Expensify/App/pull/34677

**Comment by puneetlath** [comment]
Payment summary: 
- @mananjadhav C+ - $500 

@mananjadhav please request on NewDot. Thanks!

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav based on summary above.
