### ISSUE TITLE
CRITICAL: When creating a new workspace, update the activePolicyID accordingly

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#34688]
### Problem
We have an `activePolicyID` field and logic in OldDot that, when you create your first group policy, will update the `activePolicyID` to be the new group policy instead of your initial default personal policy.

This is not something we are doing consistently with Workspaces created via NewDot. If you aren't a member of a group policy, and your `activePolicyID` refers to your personal policy, then creating a new workspace currently does not update the `activePolicyID`.

### Solution
Make this consistent such that:

**given** you are not a member of a group policy,
**when** you create a new workspace in NewDot,
**then** your `activePolicyID` should update to the be policyID of the new workspace.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012dd6547adec7459a</li>
        <li>Upwork Job ID: 1747743023965315072</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
This is a back-end change so must be internal. We will not need a C+ here

**Comment by quinthar** [comment]
Thank for writing this up!  Any ETA for when it'll be done?  Upgrading to CRITICAL as this feels like a pretty key feature for making sure after you create a workspace that the default workspace selected in the room creator is your new workspace.

**Comment by roryabraham** [comment]
I am going to prioritize [this wave5 issue](https://github.com/Expensify/Expensify/issues/358172) higher than this. But I'll try to have this ready by EOD tomorrow.

**Comment by quinthar** [comment]
Woohoo!

**Comment by roryabraham** [comment]
Got PRs up to fix this:

- [web-e](https://github.com/Expensify/Web-Expensify/pull/40641)
- [auth](https://github.com/Expensify/Auth/pull/9725)

To my surprise, I _think_ I discovered that basically all Onyx updates fetched via `GetMissingOnyxMessages` (i.e: reliable updates) were not being applied 😬

**Comment by quinthar** [comment]
@iwiznia I don't quite understand the comment -- can we close this issue, or is there something else to be done?  If something remains, what exactly, and who is working on it?

**Comment by iwiznia** [comment]
No, we can't close it. We temporarily disabled some tests and we need to re-enable them. 
This issue is assigned to @roryabraham, so I assume he will work on doing that.

**Comment by roryabraham** [comment]
Tests re-enabled, and we don't have to wait for a deploy for that to take effect. So I'm going to close this as completed
