### ISSUE TITLE
[HOLD for payment 2024-01-26] [HOLD for payment 2024-01-25] Request money - System message shows negative amount briefly when paying request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Request money from User B
2. [User B] Navigate to chat with User A
3. [User B] Click on the preview to go to IOU report
4. [User B] Click Pay elsewhere

## Expected Result:
The system message shows the correct amount

## Actual Result:
The system message shows negative amount briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a4471bba-716e-4874-8a94-0a7d78ac5aad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by neil-marcellini** [comment]
Taking a look now 👀

**Comment by neil-marcellini** [comment]
This is a very minor problem, but a new problem nonetheless. None of the PRs we deployed recently stand out to me, so I'll debug it and see if I can figure out what's causing the problem.

**Comment by neil-marcellini** [comment]
I tested this offline so I can inspect the optimistic data. It looks like the html message is right but the `iouMessage` is wrong. 
![image](https://github.com/Expensify/App/assets/26260477/1e1c2f10-9a93-4803-b9a4-8f79158fc339)

**Comment by neil-marcellini** [comment]
Asked for feedback on whether we should revert (again again) in [Slack here](https://expensify.slack.com/archives/C07J32337/p1705532627320149)
