### ISSUE TITLE
[HOLD for Payment 2024-05-29] [HIGH] [Groups] Frontend: Migrate off of `participantAccountIDs` to `participants` format in the front end

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#34692]
This is a sister issue to https://github.com/Expensify/Expensify/issues/341000.

As part of the **Group Chats** design doc we are migrating all `report.participantAccountIDs` to `report.participants` with a new data structure that can be used to show:

- all participants of a report
- whether they are "visible" or not
- what their role in the chat is i.e. `'admin'|'member'`

**Holding on back end changes:**

- [ ] https://github.com/Expensify/Expensify/issues/341000

**The general roll out of this should be as follows:**

- The backend will start by sending both data structures
- The App will be updated to never use the deprecated one
- We will also need an Onyx migration to create the new `participants` object for all reports.
- After merging the App PR and deploying it we will force all production app versions to switch to the latest (Internal engineer will coordinate this once the native apps are deployed to production)
- We can then stop sending the deprecated data structures `report.participants` (old version where it is an array of emails), `report.participantAccountIDs` & `report.visibleChatMemberAccountIDs`

**Comment by marcaaron** [comment]
@arielgreen this one would be good to get a contributor to work on. Perhaps someone with experience working on performance or typescript refactors as the changes will be a little surgical and quite large.

Similar to other issues - we can technically launch without this and the feature will be the same for users (but it should be done).

**Comment by aldo-expensify** [comment]
@marcaaron do you know what is the current progress on the first step: `The backend will start by sending both data structures`? just trying to get a rough idea, and I would be happy to help clearing this up after I finish with other high priority issues.

**Comment by marcaaron** [comment]
Hey thanks @aldo-expensify !

We are pretty close - this issue gives a good idea -> https://github.com/Expensify/Expensify/issues/341000

What's left is to...
 
1. Merge your `OpenReport` changes
2. Add some more updates to Auth and then [merge this PR](https://github.com/Expensify/Web-Expensify/pull/41441).
3. Address the concerns in [this issue](https://github.com/Expensify/Expensify/issues/380687).
4. And some clean up*

**Clean up**

- Investigate moving participants Onyx updates to a "lower level" + write tests. Suggested by @flodnv [here](https://github.com/Expensify/Auth/pull/10274#discussion_r1540027469).
- Remove any places that are returning duplicate `jsonResponse['someOnyxUpdate']` (e.g. [here](https://github.com/Expensify/Auth/blob/648cbf33687447dbb66878a935400225c4c00546/auth/command/CreateReportAction.cpp#L204-L205) and [here](https://github.com/Expensify/Auth/blob/b90a816e250a3a6f796552726c58b726f97d3c22/auth/command/InviteToGroupChat.cpp#L42-L43) - but there are a few more). These are not needed as the updates always get passed to the API caller in the PHP `$response`.

I will work on creating some issues for these tasks if you want to help there. Tbh kind of planned on doing it myself since I'm very invested in cleaning up everything, but appreciate the help for sure ❤️

**Comment by marcaaron** [comment]
@s77rt curious if you'd be interested in picking this one up once we are done with the main feature work. 90% of the backend changes are done we just need to go in and re-wire all the references to `participantAccountIDs` and `visibleChatMemberAccountIDs`. Let me know if so! I think you have some good context on what would need to be tested.

**Comment by s77rt** [comment]
Sure I'd like to work on this

**Comment by marcaaron** [comment]
🦸 We can start after the second front end PR gets merged, but I'll assign you now.

**Comment by s77rt** [comment]
Will look into this today

**Comment by s77rt** [comment]
Update: Raised a Onyx PR fixing a bug that I encountered working on this https://github.com/Expensify/react-native-onyx/pull/537

**Comment by ikevin127** [comment]
⚠️ **Automation failed**: This was deployed to **production** today [here](https://github.com/Expensify/App/pull/40254#issuecomment-2125961033), therefore should be **[HOLD for Payment 2024-05-29]** and have `Awaiting Payment` label. Additionally, it's missing the `Bug` label -> doesn't have a BZ team member assigned.

cc @marcaaron

**Comment by marcaaron** [comment]
Thanks! Assigned you and adding the correct labels to get this sorted. 

@miljakljajic this was a new feature not a `Bug` so I added that label.

**Other details:** 

@s77rt is working with me and @mallenexpensify directly on this one
@ikevin127 worked as the C+ on the review so he needs to get paid for that

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $500 to @ikevin127 for the C+ review

Is that correct?

**Comment by trjExpensify** [comment]
Also, after paying this out we can close the issue? (Sorry, there's a bunch of PRs linked here)

**Comment by ikevin127** [comment]
I think that's correct! The reported deploy blocker from https://github.com/Expensify/App/issues/34692#issuecomment-2113623335 was not related to the participants migration based on https://github.com/Expensify/App/issues/42232#issuecomment-2113709747.

> Also, after paying this out we can close the issue? (Sorry, there's a bunch of PRs linked here)

✅ 

cc @marcaaron @s77rt Please, correct me if I'm wrong on any of the questions!

**Comment by trjExpensify** [comment]
Alright, I've sent an offer in the meantime. I can always amend the price after the hipcheck.

**Comment by ikevin127** [comment]
@trjExpensify Is this enough for payment to be issued today or we're waiting for Marc's confirmation too ?

**Comment by trjExpensify** [comment]
Yeah, the latter. I'm coming in pretty cold on this one. I reached out to Marc earlier and I'll settle this after. 👍

**Comment by trjExpensify** [comment]
Alright, Marc got back to me. Paid!
