### ISSUE TITLE
Request money - "Recent" and "Contacts" does not disappear when there is no relavant results

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34729]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Manual
2. Enter amount > Next
3. Search for an invalid email
4. Search for valid email
5. Select Split

## Expected Result:
In Step 4 and 5, "Recent" and "Contacts" will not appear when there is no relevant results

## Actual Result:
In Step 4 and 5, "Recent" and "Contacts" does not disappear when there is no relevant results. This issue also occurs in Invite workspace members list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/327198b5-5a05-46ce-ba7c-6fedc6718de7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by situchan** [comment]
regression from #34008

**Comment by Pujan92** [comment]
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/components/SelectionList/BaseSelectionList.tsx#L275
https://github.com/Expensify/App/pull/34008/files#diff-750b08e6eebe347cd7ad8d106d3ea0192256cbd6217b8a97618239ee76b3404cR275

Needs to consider the length for `section.data` as it is an array.

**Comment by Julesssss** [comment]
[Reverting a PR](https://github.com/Expensify/App/pull/34733) to resolve this issue

**Comment by Julesssss** [comment]
Resolved with [this revert PR](https://github.com/Expensify/App/pull/34733) which has been CP'd to staging.
