### ISSUE TITLE
[$500] Web - The workspace chat is not appearing for the approver when a new expense report is submitted. 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34728]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705428473219199

## Action Performed:
**Prerequisites/conditions the bug was experienced:**
- Using a collect plan workspace with the isPolicyExpenseChatEnabled beta. 
- Approver on the workspace is NOT an admin
- Submitter on the workspace is also NOT an admin
- No prior history in the workspace chat, nor historical expense reports have been submitted by the member

**Steps:** 
1. Invite someone new to a collect workspace 
2. As the invited member, scan a receipt and wait until it finishes processing
3. Confirm the receipt successfully completes and is no longer a whisper
4. Click the submit button to submit the expense report

## Expected Result:
- The submitter’s workspace chat should appear in the approver’s LHN upon submission of the report.
- The workspace chat should have a green dot for the approver, as there’s an action for them to take to approve the report. 

## Actual Result:
- The approver receives the OldDot email notifying them of a report submitted 
- The submitter's workspace chat does not appear in their LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![5](https://github.com/Expensify/App/assets/93399543/de236158-3bfe-4a27-aac9-dba90cc9a771)
![image 4](https://github.com/Expensify/App/assets/93399543/53d8e54e-62b4-4f83-aa13-183c0f606177)

![image 3](https://github.com/Expensify/App/assets/93399543/6996eb58-43cc-43b8-ade7-f3b02c191b16)

![image 2](https://github.com/Expensify/App/assets/93399543/5540f475-53ad-4429-8fbb-1c6d3e5d420f)

![image](https://github.com/Expensify/App/assets/93399543/82268d50-b0c1-4ad2-8b98-6ac69f278e1c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011aaa387edb47408a</li>
        <li>Upwork Job ID: 1747978916132884480</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@RachCHopkins - #wave7-collect-approvers

**Comment by shumakmanohar** [comment]
Could you show how to reproduce this ? , when I tested it out it worked fine for me . 
Sorry , bit new to this 

Thank You

**Comment by trjExpensify** [comment]
Closing in favour of #34273.
