### ISSUE TITLE
Request money - Contact selection list in Request money page is missing user avatars

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34725]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Manual
2. Enter amount > Next

## Expected Result:
User avatar will appear next to the contact

## Actual Result:
User avatar is missing. The same issue also occurs in Room member list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9c4f3232-b08c-49fe-8500-86368e7be65b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
[#wave6-collect-subt-mitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by situchan** [comment]
confirmed regression from #34008

**Comment by situchan** [comment]
cc: @filip-solecki

**Comment by Julesssss** [comment]
Can reproduce. Found [the PR](https://github.com/Expensify/App/pull/34008)

<img width="346" alt="Screenshot 2024-01-18 at 13 43 31" src="https://github.com/Expensify/App/assets/10736861/80d95676-e8fc-4302-87d4-63b3af29ddcd">

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Contact selection list in Request money page is missing user avatars  
### What is the root cause of that problem?

It is a regression from this PR 
https://github.com/Expensify/App/pull/34008 


https://github.com/Expensify/App/blob/c9970e42eeecdc9db9bfe2496e45b4bf798bd0b4/src/components/SelectionList/BaseListItem.tsx#L32-L33
 
### What changes do you think we should make in order to solve the problem?


change this line to as it was before

```js
    const isRadioItem = !item?.icons?.length > 0;

```

**Comment by Julesssss** [comment]
I'm reverting this PR as it introduced two separate issues.
