### ISSUE TITLE
[HOLD for payment 2024-03-06] [$500] Date of birth - Lower portion of year in the list only appears after some delay

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34763]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.27-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition: User has not set a birth date.
1. Go to Settings > Profile.
2. Go to Personal details.
3. Go to Date of birth.
4. Click Year.

## Expected Result:
The list of years will appear without delay.

## Actual Result:
The lower portion of year in the list only appears after some delay.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/eb087a7e-807f-4bb7-832d-3562333b7a60

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e5606f3817f8af2</li>
        <li>Upwork Job ID: 1748069670930415616</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Awaiting proposal review @sobitneupane 👍

**Comment by sobitneupane** [comment]
I am working partially this week. I will try to review the proposals before weekend.

**Comment by greg-schroeder** [comment]
Let us know if you need help or could use a re-assignment on this one @sobitneupane!

**Comment by DylanDylann** [comment]
I can take over this issue as C+ contributor if @sobitneupane is unavailable

**Comment by sobitneupane** [comment]
I am back and will review the proposal by EOD tomorrow.

**Comment by greg-schroeder** [comment]
Thanks Sobit!

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/34763#issuecomment-1899110618) from @ZhenjaHorbach looks good to me. Dynamic `maxToRenderPerBatch ` was implemented by [this PR](https://github.com/Expensify/App/pull/31737). @ZhenjaHorbach let's look for other component using `SectionList` which has similar problem. 

🎀 👀 🎀 C+ reviewed

**Comment by greg-schroeder** [comment]
Relax Melvin, Tim will confirm the contributor assignment soon

**Comment by sobitneupane** [comment]
> The list should be designed in a way that the most selected items should be on top to minimize user scrolling and unnecessary rendering. This means we need to display the most recent years first, and then the further in the list is further years. We can just reverse the years list to do this (or order from largest to smallest number). We can also add a prop like shouldOrderYearByMostRecent to control this if we want to.

@dukenv0307 I believe we are already doing this. We are showing the latest year at the bottom and scroll to it. User don't need to scroll much to reach their BOD.

**Comment by tgolen** [comment]
I don't have any context into why it was coded this way originally. Maybe we should look at the blame and see who did it and ask them?

From a UX standpoint, I agree with @dukenv0307 that the most recent years should be at the top, not at the bottom.

**Comment by mountiny** [comment]
@dukenv0307 No, I cannot think of a specific reason, I feel like this was just an oversight when checking the design in the PR. Feel free to flip the order and have the latest year first

**Comment by sobitneupane** [comment]
> We should set it to a more reasonable number like 30 to minimize the time users having to scroll (from the default selected year) to get to their correct age. We can set the default selected year in a prop defaultDate of CalendarPicker to do this

@tgolen @mountiny Do we also want to change the default date?

**Comment by tgolen** [comment]
I know that a 5-year-old default is weird, but I also think that any value that isn't the current year is just random. When I use datepickers, I kind of hate it when I have to take a few moments to figure out if I need to scroll up or down to find the right year. So, I would advocate for making the default as the current year.

**Comment by mountiny** [comment]
I agree with Tim, lets make it a current year!

**Comment by tgolen** [comment]
# Daily Update:
- A contributor was selected and it is waiting for a PR to be drafted. @dukenv0307 do you think that will be coming soon?

**Comment by tgolen** [comment]
# Daily Update
- @dukenv0307 Do you have an idea of when you can start on a PR for this?

**Comment by greg-schroeder** [comment]
This was merged and deployed to prod 2/28, payment date would be 3/6

**Comment by greg-schroeder** [comment]
@dukenv0307 - $500 - C
@sobitneupane - $500 - C+

**Comment by greg-schroeder** [comment]
Paid, and Sobit you can make a manual request!

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.
