### ISSUE TITLE
Improve Clearbit integration to prepopulate the First/Last name during onboarding.

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#34781]
Problem: we’re going to ask users their first/last name as step 1 after sign up. We already have a Clearbit integration, but the Clearbit integration currently runs a low priority bedrock job which happens much after sign up. This forces users to have to manually input the information and increases the chance they drop off, even though we have an integration that could populate the information for a good amount of users. 

Solution: Update the Clearbit integration so upon sign up we immediately do an API call to see if we have the Clearbit information (in particular First/Last name) to input for the user (and store it in the `expensify_clearbitEmailInfo`) . If we have it, we’ll input it for the user and allow them to click continue by passing the need to manually input. Not particularly tied to this proposal, but having the company information will also help us with initial company onboarding in later iterations of onboarding. 

For background, SWM is building the front end for [Build Stage 1 of Guided Setup](https://docs.google.com/document/d/1sxG_RV5HTFHgdCsJUDNpqSGs09W_OPLBKbNYQfu3FHw/edit), but they cannot update the Clearbit integration so we need someone from our team to take that piece on. We have input how we'll use Clearbit going forward for onboarding in the design doc with the relevant code for Clearbit, which stemmed from [this conversation](https://expensify.slack.com/archives/C03SSAQ7P/p1705423496080939). 

cc @dubielzyk-expensify @anmurali  @MaciejSWM @MitchExpensify

**Comment by francoisl** [comment]
Grabbing this one.

**Comment by francoisl** [comment]
Yeah, honestly at first I was thinking that a Bedrock job is not the right tool for this if we want the data right away, but it looks like around 60% of `ImportNameFromClearbit` jobs at the moment take over 1 second to complete, so moving this in the synchronous `BeginSignin` flow doesn't sound ideal.

**Comment by flodnv** [comment]
Indeed, because we need to query clearbit for many cases, which will be slow. IIRC sometimes clearbit even tells us to try again later? Maybe if we make it priority 750 and ensure that the data is pushed to NewDot, it'll be fine?

**Comment by francoisl** [comment]
Not overdue, waiting for the design doc to be sent out for review.

**Comment by francoisl** [comment]
Design doc almost has enough reviewers, should be able to get started on this soon.

**Comment by francoisl** [comment]
@danielrvidal does [this](https://expensify.slack.com/archives/C05NJ4SLBMF/p1708444223624189) mean implementation has begun and I should go ahead and start this one too?

**Comment by MitchExpensify** [comment]
Yes implementation has begun @francoisl

**Comment by francoisl** [comment]
This has been done 1+ month ago via https://github.com/Expensify/Web-Expensify/pull/41071, closing.
