### ISSUE TITLE
Task titles are incorrectly taking the enforced report field formula

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#34785]
1. On OldDot - create a collect workspace that has enforced report titles enabled
2. In NewDot, create a task - and try to save a new title
3. Notice that it gets the required report field title

<img width="748" alt="Screenshot_2024-01-18_at_6 36 15_PM-2024-01-19 05_12_58 426" src="https://github.com/Expensify/App/assets/30609178/1476dab0-155b-4687-a932-ce6bf2070f85">

Titles should always retain the reportName value from OpenReport

**Comment by thienlnam** [comment]
This will probably be handled in https://github.com/Expensify/App/pull/34483

**Comment by allroundexperts** [comment]
This has been fixed!
