### ISSUE TITLE
[HOLD for payment 2024-03-26] [HOLD on E/E #347391] System message isn't show for approved reports that have been paid via auto-reimbursement

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34783]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705615462060629

## Action Performed:
1. Create collect workspace'
2. Invite another user
3. Set reimbursement to auto-reimburse up to to the relevant amount (i.e. how much someone will request)
4. Have the other use submit a request for a small $ amount
5. Approve the report

## Expected Result:
There should be a system message that explains the payment is now being made

## Actual Result:
There's no system message, so it looks like someone only approved the report in some areas of the UI, and then it says that the report is being paid elsewhere.

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/22508290/9e9a71f6-406f-47e5-a698-ad7c1998ac17)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment]
Not overdue - this is a tracking issue. Checking in with the above linked bug to see if there's a holistic fix in the works.

**Comment by sophiepintoraetz** [comment]
Contemplating firing this through the BZ process anyways.

**Comment by twisterdotcom** [comment]
Yes, I'm trying to get to all of these this week.

**Comment by twisterdotcom** [comment]
Working on this next week, will try to consolidate these into the main issue OR close them because we're handling more comprehensively.

**Comment by twisterdotcom** [comment]
Holding on the project: https://github.com/Expensify/Expensify/issues/347391

**Comment by twisterdotcom** [comment]
Got so many of these to consolidate. Hopefully do it this week.

**Comment by twisterdotcom** [comment]
Discussion here: https://expensify.slack.com/archives/C036QM0SLJK/p1708705771011849

**Comment by twisterdotcom** [comment]
Making weekly as we establish a path forward for these: https://expensify.slack.com/archives/C036QM0SLJK/p1708705771011849

**Comment by twisterdotcom** [comment]
Still held

**Comment by twisterdotcom** [comment]
No payments or tests required for this one. Handling all in https://github.com/Expensify/App/issues/36023#issuecomment-2008308732
