### ISSUE TITLE
[HOLD for payment 2024-02-07] [Performance] Update the E2E tests to use real API responses

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#34797]
### Problem

The E2E tests currently use hardcoded mocked data, but that does not reflect heavy user usage of the app as the amount of the data is not coming close to it.

### Solution

Lets update the tests so they can authenticate with testing account and get actual data for special account, cache that and reuse it throughout the tests. This will ensure the tests mimic more closely actual user usage

@hannojg 

<details><summary>Issue Owner</summary>Current Issue Owner: @hannojg</details>

**Comment by mountiny** [comment]
@hannojg can you comment so I can assign you

**Comment by hannojg** [comment]
Servus @mountiny 👋

**Comment by hannojg** [comment]
The PR is good for review! @AndrewGable as I think you are internal most familiar with the setup:

- https://github.com/Expensify/App/pull/34792

**Comment by kadiealexander** [comment]
@hannojg please don't forget about the regression test steps.

**Comment by NikkiWines** [comment]
I think this issue should be all good, right? I don't think we need regression steps since this wasn't a regression but rather an adjustment to our existing E2E tests

**Comment by kadiealexander** [comment]
Ah sweet then!
