### ISSUE TITLE
[HOLD] - [$500] Violation - Expense violation message is missing from Employee's view and no amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/31448
## Action Performed:
Precondition:
- Admin and employee are part of Control workspace in Old Dot
- The Control workspace has set up Max Expense Amount violation

1. [Employee] Go to workspace chat
2. [Employee] Create a manual request that exceeds the maximum amount
3. [Employee] Submit the request
4. [Employee] Go to request details page
5. [Employee] Note that there is no "Expense exceeds auto approval limit of" message
6. [Admin] Go to the request details page

## Expected Result:
~In Step 5, "Expense exceeds auto approval limit of" message will be present from Employee's view~
In Step 6, "Expense exceeds auto approval limit of" message will be complete with the maximum amount allowed for the violation

## Actual Result:
✅ In Step 5, "Expense exceeds auto approval limit of" message is not present from Employee's view
In Step 6, "Expense exceeds auto approval limit of" message is missing maximum amount allowed for the violation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3d5b0364-4df1-43e3-b21d-6213f89d93e8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019aaa92dcff420820</li>
        <li>Upwork Job ID: 1748367750109818880</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by cead22** [comment]
I'm taking this one, to check if the fix is on the backend first. 

> In Step 5, "Expense exceeds auto approval limit of" message will be present from Employee's view

For context: we don't show this to the person requesting money because they can't do anything about this violation

**Comment by cead22** [comment]
Planning on triaging this today

**Comment by cead22** [comment]
After testing this while on this branch https://github.com/Expensify/App/pull/34303/files, I think this issue will be fixed by that PR, so putting it on HOLD for now

**Comment by cead22** [comment]
On hold, not overdue

**Comment by JmillsExpensify** [comment]
Linked issue still hasn't merged, though it looks very close.

**Comment by cead22** [comment]
PR got merged but hasn't been deployed yet
