### ISSUE TITLE
Violation - Red dot only appears in expense preview after refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34809]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31448
## Action Performed:
Precondition:
- Admin and employee are part of Control workspace in Old Dot
- The Control workspace has set up Max Expense Amount violation
1. Go to workspace chat
2. Create a manual request that exceeds the maximum amount
3. Submit the request
4. Without opening expense report, refresh the page

## Expected Result:
The red dot will appear in the expense preview in the workspace chat as soon as the request with violation is created

## Actual Result:
The red dot only appears in the expense preview in the workspace chat after refreshing the page, or visiting the request details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0d64e846-0c33-4838-a2e7-2d8a79a8fb15

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)[#wave6-collect-submitters](https://expensify.enterprise.slack.com/archives/C02MW39LT9N)

**Comment by mountiny** [comment]
@cead22 

I dont think this has to be a blocker

**Comment by situchan** [comment]
yup, not blocker. we already discussed about real time change concerns.

**Comment by cead22** [comment]
Agreed. RBR for money request view hasn't been implemented yet, and will be done as part of this issue https://github.com/Expensify/App/issues/32571
