### ISSUE TITLE
[$500]  Contact Method - The profile avatar changes when the default contact email is updated

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34815]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Profile > Contact Method > Add Contact Method
2. Change the contact method to the newly added one and observe the profile avatar; it changes

## Expected Result:
The profile avatar should not change when the default contact email is updated

## Actual Result:
The profile avatar changes when the default contact email is updated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/44ee98fa-9217-445d-b66a-a963532f9b39

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139065cb9535c6083</li>
        <li>Upwork Job ID: 1748378817917579264</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by cjoshi-zeals** [comment]
Agree with @barros001 

I have found out that if the case user does have an image it is not causing the change.

And also there is one more bug if the user does have an image attached to the email and if the other email doesn't have any image.

Removing the email with the image is not removing the image. It will be shown for other email as well

**Comment by cjoshi-zeals** [comment]
Contributor details
Your Expensify account email: joshichandan015@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c8c1ca43cddf7d39

**Comment by cjoshi-zeals** [comment]
Contributor details
Your Expensify account email: [joshichandan015@gmail.com](mailto:joshichandan015@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01c8c1ca43cddf7d39

**Comment by cjoshi-zeals** [comment]
Contributor details
Your Expensify account email: joshichandan015@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c8c1ca43cddf7d39

**Comment by jjcoffee** [comment]
Yeah I agree with @barros001. This is arguably a regression from https://github.com/Expensify/App/pull/32090 where we switched to using the avatar returned by the BE instead of generating it from hashing the accountID. We'd just need to change the BE to generate the avatar from the accountID. 

@sakluger can you apply the `Engineering` tag and make this internal?

**Comment by sakluger** [comment]
Thanks @barros001 and @jjcoffee. We aren't currently using the engineering auto-assigner, but I added to the #vip-vsb project board and will ask for a volunteer.

**Comment by rlinoz** [comment]
I will try to open a PR to fix this today.

**Comment by rlinoz** [comment]
Waiting for a deploy to put the last PR for review.

**Comment by rlinoz** [comment]
Oh this can actually be closed 😄
