### ISSUE TITLE
[$500] Violation - Violation message takes long time to disappear after removing violation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31448
## Action Performed:
Precondition:
- Admin and employee are part of Control workspace in Old Dot
- The Control workspace has set up Max Expense Amount violation

1. [Employee] Create a manual request that exceeds the maximum amount in the workspace chat
2. [Employee] Submit the request
3. [Admin} Navigate to request details page, refresh the page and wait for violation to show up
4. [Admin] Edit the amount to lower than the limit
5. [Admin] Refresh the details page and navigate between main chat and details page several times
6. [Admin] Log out and log in

## Expected Result:
In Step 4 and 5, the violation message will disappear after the violation is removed

## Actual Result:
In Step 4 and 5, the violation message does not disappear after the violation is removed
It will take a long time to disappear or disappear after relogin (Step 6)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f71edaa0-eded-4b37-bf1c-7d732e1f1053

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d7959f2541eff5f</li>
        <li>Upwork Job ID: 1748373270557962240</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6. 
CC @greg-schroeder

**Comment by situchan** [comment]
Discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705616693929099?thread_ts=1705336943.293449&cid=C01GTK53T8Q)
cc: @cead22
