### ISSUE TITLE
[MEDIUM] Violation - Violation for unsubmitted report is visible for Admin after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34810]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31448
## Action Performed:
Precondition:
- Admin and employee are part of Control workspace in Old Dot
- The Control workspace has set up Max Expense Amount violation

1. [Employee] Go to workspace chat
2. [Employee] Create a manual request that exceeds the maximum amount
3. [Employee] Do not submit the request
4. [Admin] Log out and log in

## Expected Result:
Violation message and red dot will not be visible for admin because the report with violation is not submitted

## Actual Result:
Violation message and red dot is visible for admin after relogin when the report with violation is not submitted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6d979e45-842b-441b-82ed-cf807bb33fcd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6. 
CC @greg-schroeder

**Comment by situchan** [comment]
This was also discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705614842989029?thread_ts=1705336943.293449&cid=C01GTK53T8Q). Not deploy blocker

**Comment by mountiny** [comment]
Added to wave 6

**Comment by madmax330** [comment]
Didn't have time to investigate this yet. Any idea what might be happening off the top of your head @cead22 since you worked on violations IIRC?
