### ISSUE TITLE
[$500] Web – Assignee avatar greyed out for a moment when Canceled task with some comments

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34813]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Use low speed Internet if possible
1. Go to https://staging.new.expensify.com/
2. In 1:1 chat clicks on the + button
3. Select Assign Task
4. Enter a title
5. Assign the task to yourself
6. Navigate to the task report
7. Add 2 comments on the task
8. Click on the 3 dot menu
9. Cancel the task

## Expected Result:
Assignee avatar not greyed out when Canceled task with some comments

## Actual Result:
Assignee avatar greyed out for a moment when Canceled task with some comments

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cd3e1be7-9111-4d76-9bd1-be65faf7004e

![Bug6347753_1705678577139!1](https://github.com/Expensify/App/assets/78819774/793ca393-a049-4766-bee4-c993e4b36b82)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015aa3b04c99768479</li>
        <li>Upwork Job ID: 1748376652351643648</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web – Assignee avatar greyed out for a moment when Canceled task with some comments
### What is the root cause of that problem?
In `ReportActionItemSingle` component we use [getAvatar](https://github.com/Expensify/App/blob/52adf77a70819a3a24bd8da34672412f9a0b68fd/src/pages/home/report/ReportActionItemSingle.tsx#L223C90-L223C101)
 function to display avatar . And because of this, every render of the `ReportActionItemSingle` component also renders the avatar.
### What changes do you think we should make in order to solve the problem?
We should wrap the `getAvatar` function in `useCallback` hook
```
const getAvatar = useCallback(() => {
    if (displayAllActors) {
        return (
            <MultipleAvatars
                icons={[icon, secondaryAvatar]}
                isInReportAction
                shouldShowTooltip
                secondAvatarStyle={[StyleUtils.getBackgroundAndBorderStyle(theme.appBG), isHovered ? StyleUtils.getBackgroundAndBorderStyle(theme.hoverComponentBG) : undefined]}
            />
        );
    }
    if (shouldShowSubscriptAvatar) {
        return (
            <SubscriptAvatar
                mainAvatar={icon}
                secondaryAvatar={secondaryAvatar}
                noMargin
            />
        );
    }
    return (
        <UserDetailsTooltip
            accountID={Number(actorAccountID ?? 0)}
            delegateAccountID={Number(action.delegateAccountID ?? 0)}
            icon={icon}
        >
            <View>
                <Avatar
                    containerStyles={[styles.actionAvatar]}
                    source={icon.source}
                    type={icon.type}
                    name={icon.name}
                    fallbackIcon={fallbackIcon}
                />
            </View>
        </UserDetailsTooltip>
    );
}, [icon, fallbackIcon,styles, action, actorAccountID, secondaryAvatar,secondaryAvatar ,isHovered, theme]);
```

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment]
Not able to reproduce on the latest main

**Comment by shahinyan11** [comment]
@hoangzinh Yes, but in a different case. And this can happen anywhere where a new component is rendered with an avatar.

https://github.com/Expensify/App/assets/46921547/7be6ba55-d8f7-41a8-9103-c2838be2e712

**Comment by conorpendergrast** [comment]
Yeah agreed - I think we can leave that for now. Thanks!
