### ISSUE TITLE
[$500] Settings - Sometimes the priority mode changes without clicking on it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34824]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to preferences - priority mode
2. Change the priority modes quickly

## Expected Result:
It should only change if I set it

## Actual Result:
Sometimes the priority mode changes without clicking on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d0b3b4b1-4bb4-4764-8c7a-8a0723577e38

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01860115c8f86a3ff1</li>
        <li>Upwork Job ID: 1748403899051614208</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
Same, let us know if you can do this again @lanitochka17
