### ISSUE TITLE
Chat -"Unavailable workspace" displayed when user navigated to the message notification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34841]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Kill the app and lock the main testing device
2. On the secondary device create a workspace from different account
3. Invite account from main testing device to the workspace
4. Send message to the announce room from secondary device
5. Tap on the message notification from the main testing device

## Expected Result:
User should be navigated to the announce room and chat should be properly displayed

## Actual Result:
"Unavailable workspace" displayed when user navigate to the message notification in announce room and different room avatar displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3cb65a39-edff-46b6-8ac0-d431fa3253d2

https://github.com/Expensify/App/assets/78819774/6dd05775-7808-42d8-b89d-3a72a89c7bac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment]
I believe this is a known bug and unlikely to be some thing that's due to the staging diff - see reports of similar behavior [here](https://expensify.slack.com/archives/C049HHMV9SM/p1705592992532339), [here](https://expensify.slack.com/archives/C049HHMV9SM/p1705589185468339?thread_ts=1705588436.284919&cid=C049HHMV9SM), [here](https://expensify.slack.com/archives/C049HHMV9SM/p1705517566966939), and [here](https://expensify.slack.com/archives/C049HHMV9SM/p1703014430002699).

**Comment by NikkiWines** [comment]
Confirmed after chatting with @francoisl that this is a known bug, not a blocker.
