### ISSUE TITLE
Outdated shellcheck dependency prevents windows from install npm dependencies

### ISSUE THREAD

**Issue by JeremyCroff** [Expensify/App#34845]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

shellcheck dependency is on v1, and requires v2 for windows to be able install the dependency https://github.com/gunar/shellcheck/issues/121

**Comment by jestinjoshi** [comment]
@JeremyCroff were you able to resolve the issue or get someone to work on it? I am trying to run Expensify on Windows

**Comment by jestinjoshi** [comment]
Contributor details
Your Expensify account email: jestinjoshi@gmail.com
Upwork Profile Link: https://upwork.com/freelancers/~01c9eadbbec50b669b

**Comment by jestinjoshi** [comment]
Contributor details
Your Expensify account email: jestinjoshi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c9eadbbec50b669b

**Comment by vtjhyn** [comment]
Contributor details
Your Expensify account email: [vtjahyono10@gmail.com](mailto:vtjahyono10@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e798ace6b83708f9

**Comment by vtjhyn** [comment]
Contributor details
Your Expensify account email: [vtjahyono10@gmail.com](mailto:vtjahyono10@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e798ace6b83708f9

**Comment by vtjhyn** [comment]
Contributor details
Your Expensify account email: [vtjahyono10@gmail.com](mailto:vtjahyono10@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01e798ace6b83708f9
