### ISSUE TITLE
[$500]  Workspace - After BA has been added on OD, it does not appear on ND

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have created a collect workspace and have created a request from an employee account
1. As the admin on OD, go to workspace setting and click on "Reimbursements"
2. Click on Direct
3. Add a fully verified VBA
4. As the admin on ND, navigate to workspace chat with an employee that have submitted a request
5. Click on "Pay with Expensify" button

## Expected Result:
The user should be able to pay the request if the BA was added on OD

## Actual Result:
The add BA modal opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fbdae518-42ac-47a9-9879-2b3535c7fb89

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151fb7e11e7787a66</li>
        <li>Upwork Job ID: 1748762521983385600</li>
        <li>Last Price Increase: 2024-01-20</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave8. 
CC @zanyrenney

**Comment by trjExpensify** [comment]
Hm, @luacmartins @mountiny @JmillsExpensify I can't find the issue, but is this related to how VBBAs were implemented on NewDot and are awaiting a refactor?

**Comment by luacmartins** [comment]
Yes, we're likely not setting the `expensify_freePlanBankAccountID` NVP. This is the [issue](https://github.com/Expensify/Expensify/issues/299712) to fix it.

**Comment by mountiny** [comment]
I think we should make that issue higher priority just to clear this debt out of the way

**Comment by trjExpensify** [comment]
Okay, so we don't need this dupe issue, so I'll close it. Vit, that's probably better discussed over there!
