### ISSUE TITLE
[$500] Web - Expense - Approve button is displayed on the conversation preview, but not on report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have submitted a request to a collect workspace with an employee account.
1. Go to https://staging.new.expensify.com/
2. Log in with the admin account of the workspace.
3. Navigate to the workspace chat of the employee who submitted the report.
4. Click on the arrow of the green button for the dropdown menu to be displayed.
5. Select the "Approve" option.
6. Click on the report preview.

## Expected Result:
The "Approve" button should be displayed also on the report page.

## Actual Result:
The "Approve" button is not displayed on the report page even if already selected on the conversation preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e9c86e31-d4b3-4c53-9e01-ac6d19e85a6f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b6f801c0df1bacc</li>
        <li>Upwork Job ID: 1748733849801924608</li>
        <li>Last Price Increase: 2024-01-20</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 28124176</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave7-collect-approvers
CC @RachCHopkins 
TR related https://expensify.testrail.io/index.php?/tests/view/4208298

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When selecting a preferred payment method on the settlement button, it's not persisted between screens

### What is the root cause of that problem?
When selecting the option, we do not persist the selected preferred payment method in Onyx.
And when choosing, which option to make default, we check the `ONYXKEYS.NVP_LAST_PAYMENT_METHOD` Onyx key.

We persist this key only on performing the actual payment or approval.

### What changes do you think we should make in order to solve the problem?
We need to persist the `ONYXKEYS.NVP_LAST_PAYMENT_METHOD` key for a specific policy when selecting the payment option on the `SettlementButton's` dropdown.

### What alternative solutions did you explore? (Optional)

**Comment by JeremyCroff** [comment]
Can you please include steps on how to send a report that requires approval

**Comment by allroundexperts** [comment]
Thanks for your proposals everyone!

@codinggeek2023 I see that you updated your proposal a lot of time after others proposed.

@abzokhattab I think your proposal is very similar to what @paultsimura proposed earlier. As such, I think we should go with there [proposal](https://github.com/Expensify/App/issues/34853#issuecomment-1902164819).

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment]
> Thank you @allroundexperts, my proposal was few minutes after the second proposal but it contained the implementation specific details unlike the other proposal which doesnt contain the code implementation.

Thank you for the explanation but we don't really require concrete implementation details. I think what @paultsimura has proposed is good enough.

**Comment by marcochavezf** [comment]
Thanks @allroundexperts and agree with your decision, assigning @paultsimura 🚀

**Comment by marcochavezf** [comment]
Hi @paultsimura, let us know when the PR is ready for review :)

**Comment by paultsimura** [comment]
> Hi @paultsimura, let us know when the PR is ready for review :)

Sure, will be ready today 👌

**Comment by paultsimura** [comment]
This was [deployed to prod](https://github.com/Expensify/App/pull/35327#issuecomment-1928451116), the automation didn't work.

**Comment by paultsimura** [comment]
Hey @sonialiap, a friendly bump here – it was due payment on Feb 12. Thanks 😌

**Comment by allroundexperts** [comment]
## Checklist
1. This was kind of a new feature request. We never implemented this since the creation of pay button (https://github.com/Expensify/App/pull/18692)
2. N/A
3. N/A
4. A regression test would be useful here. Again, the steps in the OP are clear enough and should suffice.

**Comment by sonialiap** [comment]
@paultsimura contributor $500 - paid ✔️
@allroundexperts C+ $500 - please request in ND

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary above.
