### ISSUE TITLE
[$500] Chat - Inconsistent behavior for different phone numbers with same country code is shown

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34850]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab ---- Start chat
3. Search +84387025654 and select the contact
4. Note conversation page opened with header text hidden and no error is displayed
5. Navigate back to LHN
6. Tap fab --- start chat
7. Search +84387025656 and select the contact

## Expected Result:
Inconsistent behaviour for different phone numbers with same country code must not be shown.

## Actual Result:
Start chat with this number +84387025654, shown as hidden and no error displayed on opening conversation page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e861810b-6a9c-47f0-bbbb-8c17c8c07ad4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a39fef35a8c97df</li>
        <li>Upwork Job ID: 1748723382413754368</li>
        <li>Last Price Increase: 2024-01-27</li>
    </ul>
</details>

**Comment by JeremyCroff** [comment]
It's the https://www.expensify.com/api?command=OpenReport service returning the error message. But the payload from the UI looks alright to be. I believe this is a service issue. Is there a transaction id Expensify returns so I can share the call for debugging on the back end?

**Comment by brunovjk** [comment]
Look like a backend issue.

**Comment by NicMendonca** [comment]
@kbecciv actually, I don't think I can reproduce this? What specifically is the inconsistent behaviour? 🤔

**Comment by brunovjk** [comment]
I think this is similar: https://github.com/Expensify/App/issues/34839
