### ISSUE TITLE
[$500] The whisper to invite someone to a room is persistent

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34868]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kadiealexander 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705609789474709

## Action Performed:
1. Reply to a comment in a room, tagging someone who isn't in the reply room
2. Click either of the "Invite them" or "Do nothing" buttons.

## Expected Result: 
The whisper disappears and the action you chose is taken.
## Actual Result: 
When clicking the "Invite them" button, the whisper disappears for a moment then reappears. When clicking "Do nothing", nothing happens and the whisper remains.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/5b43c8b1-d31f-43f1-b0b1-f61be1d7eb14

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dde2be0ebbf260bf</li>
        <li>Upwork Job ID: 1749372415518834688</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 28118225</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Hm.. why didn't this get assigned to someone? @jasperhuangg are you working with @ishpaul777 on it?

**Comment by jasperhuangg** [comment]
This was a regression from his earlier PR that I noted in the review after it was merged.

That's why an issue wasn't created initially.

**Comment by trjExpensify** [comment]
Yep, done
