### ISSUE TITLE
[HOLD for payment 2024-02-01] Report fields should not be hoverable/clickable when enforced

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#34865]
1. In Olddot, enforce report titles
2. In NewDot, create an IOU
3. Go into the report, and see that you can still hover / click on the title 

https://github.com/Expensify/App/assets/30609178/beb3945e-9b17-44aa-acbd-4ed4e4235d68

**Comment by allroundexperts** [comment]
PR: https://github.com/Expensify/App/pull/34884

**Comment by thienlnam** [comment]
We're handling as part one sum project payment

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor+: @allroundexperts $500, please request on Newdot

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
