### ISSUE TITLE
[Wave6] Remove links from the next steps message

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#34871]
### Problem

Coming from https://expensify.slack.com/archives/C049HHMV9SM/p1705600357375529

The next steps in the App are exact mirror of what we show in OldDot right now, however, that is not fully compatible with NewDot. Especially there can be buttons or links in the message that do not funciton as intended in NewDot leading to confusing experience.

### Solution

We have already removed the buttons. Lets also make sure we do not hyper link the links in the next steps, leave them as normal text

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010faf9f4e9ae96068</li>
        <li>Upwork Job ID: 1749392983082467328</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by mountiny** [comment]
![image](https://github.com/Expensify/App/assets/36083550/8080075c-e706-4660-99b2-f62b0c5ce24c)

Ha funny @muttmuure

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by waterim** [comment]
Hey @mountiny 
This link is rendering just in <RenderHTML> component which is coming from the backend

Here is a place in "NextStep.php" file where this link is creating.
<img width="1333" alt="image" src="https://github.com/Expensify/App/assets/39777589/b6f52b1e-36cb-45a1-89ac-7ec73f8c47f6">

I think this should be a backend fix.

**Comment by mountiny** [comment]
I could do that too

**Comment by waterim** [comment]
@mountiny in frontend part just <renderHTML> component is rendering with the data from backend

**Comment by mountiny** [comment]
Will look tomorrow

**Comment by mountiny** [comment]
Did not get around at the end of the week

**Comment by mountiny** [comment]
PR is up and in review

**Comment by muttmuure** [comment]
I think this is done and handled by an agency. Closing

**Comment by mountiny** [comment]
Not sure this did not close, this should be completed no cahnges required in the App
