### ISSUE TITLE
[$500] IOU - Scan request created using PNG unsupported format is not showing any error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211767
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Tap plus icon near compose
4. Tap request money --- Scan
5. Upload a PNG image
6. Tap request
7. Tap newly created scan request
8. Enter all details
9. Tap from header link and note IOU preview

## Expected Result:
Scan request created using PNG unsupported format must show error.

## Actual Result:
User allowed to create scan request using PNG unsupported format and is not showing any error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7a3213d9-83c7-4c2e-9f3d-0bfb903e385f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01baa14ec06c6c0cc8</li>
        <li>Upwork Job ID: 1749424534940782592</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by conorpendergrast** [comment]
I may be missing something, but agree that PNG is a **supported receipt format**. I'll close as not a bug, but please share more context if you see something differently @kbecciv!
