### ISSUE TITLE
[HOLD for payment 2024-02-09] [HIGH] Ensure the expense is added to report from which it was requested from

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#34906]
### Problem

Users can go to expense report detail and request money from within that expense report. The correct money request reportID is passed to the backend but its never used actually. We do get the linked money request report as any other time which isn't guaranteed to be the same as we can have multiple open or processing reports

FYI this is being discussed in [this internal slack thread](https://expensify.slack.com/archives/C02MW39LT9N/p1705954353492549?thread_ts=1705942791.826019&cid=C02MW39LT9N)

### Solution

Make sure to use the provided money request report when provided in the `createIOUTransaction` call.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016be31384661b2a09</li>
        <li>Upwork Job ID: 1749503890650640384</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by mountiny** [comment]
Auth change is ready to be reviewed and merged, tests are passing, but I have found out there must have been some changes in the App and we are not necessarily sending the reportID of a report from which we have requested the money from

I will have to handle those changes too

**Comment by mountiny** [comment]
Still need to complete the App PR, will focus on that tomorrow

**Comment by mountiny** [comment]
PR is in review, addressed initial round of feedback

**Comment by mountiny** [comment]
This is done basically

$500 to @eVoloshchak for review and testing please

**Comment by mountiny** [comment]
@eVoloshchak could you please propose a testRail case for this? specifically on Collect policy with bunch of Open reports to the testers can verify the expense is correctly added to that expense report

**Comment by muttmuure** [comment]
$500 - @eVoloshchak

**Comment by muttmuure** [comment]
@eVoloshchak please can you submit a regression test

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

Preconditions:
- Have a Collect policy set up to work with NewDot
- Employee is a member of said policy

Test steps:
1. As the Employee, go to OldDot and create a New Report
2. Create multiple empty draft/open reports
3. Go to any of those expense reports
4. From the Composer + button, request money -> `Manual`
5. Verify that the request was added to the particular report you've requested it from
6. Repeat steps 3-5 for `Scan` and `Distance`

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on [this comment](https://github.com/Expensify/App/issues/34906#issuecomment-1936192606).

**Comment by mountiny** [comment]
Lets add this regression test and we can close this

**Comment by muttmuure** [comment]
Created
