### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Android - Center icon in EReceipt for Expensify transactions is blank

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34907]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to account with Expensify Card transaction [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
2. Go to workspace chat with the transaction https://staging.new.expensify.com/r/4612388815642526
3. Navigate to transaction details page
4. Open Ereceipt

## Expected Result:
The center icon is not blank

## Actual Result:
The center icon is blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b8f07032-b293-4f86-808b-31071ff96cae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df6f886be1e32b04</li>
        <li>Upwork Job ID: 1749504709300957184</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28120700</li>
<li>aswin-s | Contributor | 28120701</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5. 
CC @dylanexpensify

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Center icon in EReceipt for Expensify transactions is black in color on Android

### What is the root cause of that problem?

The icon being used in EReceipt center icon is `eReceiptIcon.svg`. It has fillColor set to `currentColor`

```svg
<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" ... />
```

currentColor prop is not working with expo-image on Android platform 

### What changes do you think we should make in order to solve the problem?

Remove `fill="currentColor"` from the svg element


### What alternative solutions did you explore? (Optional)
None

**Comment by jjcoffee** [comment]
@aswin-s Thanks for the proposal! I think your solution would not solve the issue though, if you look at the [original PR](https://github.com/Expensify/App/pull/29075) that implemented EReceipts, the icon should have a colour.

**Comment by aswin-s** [comment]
@jjcoffee [expo-image was introduced](https://github.com/Expensify/App/pull/30905) after this PR. EReceiptThumbnail uses Icon component to display the image. Icon component now uses`ImageSVG` component to display SVG images. Looks like this is a regression from expo-image integration. I tested it both on web and android and the above change fixes the image on both platforms.

**Comment by jjcoffee** [comment]
@aswin-s Thanks! I agree the fix works, normally we would require details as to why/how it works too (hence my confusion with thinking it would display without any colour). Are you able to update your proposal with that extra detail?

**Comment by aswin-s** [comment]
@jjcoffee [Updated my proposal](https://github.com/Expensify/App/issues/34907#issuecomment-1907272252) with additional details.

**Comment by jjcoffee** [comment]
@aswin-s Sorry, I meant details on why the solution is a good one (how it works, where does the fill come from if we remove it from there).

**Comment by aswin-s** [comment]
@jjcoffee Added more details on how ImageSVG works on both web and native platforms and why currentColor is not required anymore. Let me know if anything needs further clarification.

**Comment by jjcoffee** [comment]
Sweet, thanks for adding that! Happy to go with @aswin-s's [proposal](https://github.com/Expensify/App/issues/34907#issuecomment-1907272252), as essentially we don't need the `fill` in the SVG anymore.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by marcaaron** [comment]
This one looks like it can be closed now?

**Comment by johncschuster** [comment]
Yep! I left it open so I would get the Regression Test steps done, but it is otherwise complete!
