### ISSUE TITLE
[$500] Scan - Workspace chat shows green dot in LHN when request is still scanning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34908]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a workspace
2. Go to the workspace chat
3. Create a scan request
4. Refresh the page

## Expected Result:
The workspace chat will not show green dot in LHN when the request is still scanning and there is no other request

## Actual Result:
The workspace chat shows green dot in LHN when the request is still scanning and there is no other request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6172e2e5-3c59-4a2a-9b9f-3eda722639cd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019502544793e27e88</li>
        <li>Upwork Job ID: 1759594174012764160</li>
        <li>Last Price Increase: 2024-02-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5. 
CC @dylanexpensify

**Comment by paultsimura** [comment]
This is a BE issue: when refreshing the page, an `OpenReport` API call is made, which returns `hasOutstandingChildRequest: true` for the report:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/12595293/7561d3bd-58fd-4887-b00b-6f0f8f8726cf">

**Comment by kevinksullivan** [comment]
checking in wave 5 on this one. @lanitochka17 in the meantime, are you still able to reproduce this?

**Comment by kevinksullivan** [comment]
We're changing the scanning pattern in NewDot so I'm going to close this till then
