### ISSUE TITLE
[$500] Workspace - Collect workspace name change on Old Dot only updates on New Dot after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34911]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace on Old Dot
1. [Employee] Navigate to workspace chat on New Dot
2. [Admin] Change the workspace name on Old Dot
3. [Employee] Refresh the workspace chat
4. [Employee] Log out and log in

## Expected Result:
The workspace name on New Dot will update after refreshing the page

## Actual Result:
The workspace name on New Dot does not update after refreshing the page. It only updates after relogin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2968f605-1a86-4fad-adb2-d40463b56bbb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a0d668378b869cf</li>
        <li>Upwork Job ID: 1749511369246969856</li>
        <li>Last Price Increase: 2024-01-22</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6. 
CC @greg-schroeder

**Comment by stephanieelliott** [comment]
I think this is pretty minor and perhaps even expected behavior.
