### ISSUE TITLE
[$500]  LHN - Web - Offline created chat on LHN disappear and reappear when come back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34918]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4209116
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Disable the internet connection in the device
2. Click on the green + button
3. Click on the "Send Message" option
4. Search for a user with a valid email that you don't have any messages with and open the chat
5. Verify the user is navigated to the conversation
6. Verify the conversation is grayed out indicating is pending to be created
7. Send some messages
8. Navigate to another chat
9. Come back online

## Expected Result:
Chat that was created in offline mode should be stable on LHN

## Actual Result:
Offline created chat on LHN disappear and reappear when come back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01573f4bf2c4908020</li>
        <li>Upwork Job ID: 1749518291837231104</li>
        <li>Last Price Increase: 2024-01-29</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28130631</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by Tony-MK** [comment]
This is expected if the user's priority mode is #Focus.

Could you provide some screenshots or videos?

Thanks 😄

**Comment by allroundexperts** [comment]
Taking over!

**Comment by allroundexperts** [comment]
Hi @tienifr!

Thanks for your [proposal](https://github.com/Expensify/App/issues/34918#issuecomment-1905711174). Do you mind sharing a before and after video of your proposal? 

Thanks

**Comment by TouchstoneTheDev** [comment]
> @allroundexperts Sure!
> 
> Here they are: Before: https://github.com/Expensify/App/assets/113963320/a08f89a9-7245-4544-873c-7109856ec5d9
> 
> After: https://github.com/Expensify/App/assets/113963320/53b200fd-71bc-46e4-80ee-d909e6e67eec

Cool 
Is this issue solved ?
please close it and others also !

**Comment by allroundexperts** [comment]
Thanks for the screen recordings @tienifr. Your [proposal](https://github.com/Expensify/App/issues/34918#issuecomment-1905711174) works good. Let's go for it.
🎀 👀 🎀 C+ reviewed

**Comment by arosiclair** [comment]
No BZ got assigned for some reason. Trying again

**Comment by arosiclair** [comment]
The default `notificationPreference` was set to `hidden` to fix empty chats displaying as "unread" in focus mode. I'm asking about this internally [here](https://expensify.slack.com/archives/C03TQ48KC/p1707148171449579).

**Comment by stephanieelliott** [comment]
Hey @arosiclair what's the latest with this one, did you get the info you needed?

**Comment by arosiclair** [comment]
Yup sorry for the late update. I agree with @marcaaron's assessment:

> A correct solution would be something like combining dependent requests into a single request to handle any side effects. But it’s just not how the offline architecture works right now. So, the behavior is “expected”.

This behavior is somewhat expected since there are intermediary steps between the offline chat being created and the offline messages being added. Moreover, the default `hidden` preference is correct until comments are added.

@tienifr's frontend changes still make sense to me, but it sounds like they do not fix the issue on their own. Is that correct?

**Comment by arosiclair** [comment]
Bump @tienifr ^

**Comment by stephanieelliott** [comment]
Hey @tienifr can you weigh in on Andrew's question above?

**Comment by arosiclair** [comment]
Alright if frontend changes don't fix the issue on their own, then we should just do nothing here. Closing this out.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @tienifr $500 via Upwork (PAID)
 - Contributor+: @allroundexperts $500 via Upwork (offer extended, please accept!)
 
 Upwork job is here: https://www.upwork.com/jobs/~01573f4bf2c4908020

**Comment by stephanieelliott** [comment]
OH, thanks @allroundexperts. All set!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary above.
