### ISSUE TITLE
[$500] iOS - Task - Assignee disappears for a task in a public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34935]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** T
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4210815
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: create a public room with tasks
1. Navigate to the public room link, e.g. https://staging.new.expensify.com/r/1898619590844985
2. Select a task that was not claimed yet
3. Tap Assignee
4. Log in with a user who has not joined the public room
5. Assign the task to yourself
6. Go back to the room

## Expected Result:
The assignee is displayed after assigning a task

## Actual Result:
The assignee disappears and appears after opening the task again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9818214d-cff1-41a4-bdb4-f1d9689e6619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01036f95ac9073041c</li>
        <li>Upwork Job ID: 1749568993607393280</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsb.
CC @quinthar

**Comment by garrettmknight** [comment]
@lanitochka17 I'm seeing something a bit different in the flow. I can't seem to get from the link to the public room in the iOS app without being forced to login first. Is this iOS mweb or something? Thanks for your help!

**Comment by garrettmknight** [comment]
@Ollyws if you can give it a try that'd be great too.

**Comment by garrettmknight** [comment]
@Ollyws did you get a chance to test?
