### ISSUE TITLE
[$500]  Report previews don’t always seem to load automatically when opening a workspace chat for admins/approvers

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34948]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705932839025629

## Action Performed:
1. Create few expense reports
2. Open the workspace chat

## Expected Result:
Report preview should show the full details

## Actual Result:
Not showing the full details. It appears `"workspace name" owes: `
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (1)](https://github.com/Expensify/App/assets/43996225/684d8eb3-519e-4710-9273-58996b20a6bc)

![image](https://github.com/Expensify/App/assets/43996225/ab487c51-fc79-46fc-b399-f1ac1750e8b8)

![image](https://github.com/Expensify/App/assets/38236554/1bf5f699-70d7-4451-95d8-f740e1b641b9)

![image](https://github.com/Expensify/App/assets/38236554/bf5b5a7d-02e5-40a3-a3d4-825ab616b2da)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159a5d39883983e88</li>
        <li>Upwork Job ID: 1750624618026557440</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment]
There are several reports of this - added the other examples to the OP. One specific report we can look at is 6449346585801291. 

I think this fits with #wave-7 - posted in Slack [here](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1706214991668349)

**Comment by marcochavezf** [comment]
I will check it out today

**Comment by marcochavezf** [comment]
Applied the `retest-weekly` label

**Comment by marcochavezf** [comment]
I'm going to unassign myself atm

**Comment by bfitzexpensify** [comment]
Waiting for this to be retested, not overdue

**Comment by bfitzexpensify** [comment]
Same update

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment]
Nice! Let's close this out then.
