### ISSUE TITLE
[HOLD for payment 2024-03-18] [HIGH] [Instant Submit] for Collect: Improve creating expenses on Instant Submit paid plans, from NewDot

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#34955]
~Holding on https://github.com/Expensify/Expensify/issues/360667~

[Instant Submit for Collect Workspaces Design Doc](https://docs.google.com/document/d/1HIPlPKDyJEX73bUGceo354tvU7xqXkhj9j14GoLhMJw/edit)

Tracking GH issue: https://github.com/Expensify/Expensify/issues/334111

Goal for this issue: Make sure these flows work perfectly in NewDot, for Paid plans on Instant Submit
1. In Workspace chat, click report preview of a report to open the expense report
2. Request money (this currently isn't possible for submitted reports, in NewDot)
3. Verify the request / expense gets added to that correct expense report
    - Related to https://github.com/Expensify/App/issues/34906#top
4. Navigate back to the workspace chat & request money there
5. Verify the request / expense gets added to the most recently created expense report
    1. It looks like we currently optimistically try to find an OPEN report in NewDot to add a money request to & if we don't find one, we optimistically create a new Report Preview. We will need to update this to look for Processing as well, only if the policy is Instant Submit!
    2. We're also having a discussion about "do we need this to be added to the most recent expense report or **any**" in slack [here](https://expensify.slack.com/archives/C02MW39LT9N/p1705942791826019).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9e4f88d7ec8247b</li>
        <li>Upwork Job ID: 1749734239297155072</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by Beamanator** [comment]
Technically all backend changes are ready on staging, so I'll take this off hold soon!

**Comment by Beamanator** [comment]
Looking for volunteer via `Hot Pick` label

**Comment by youssef-lr** [comment]
Starting work on this one today.

**Comment by youssef-lr** [comment]
I should have an update by EOD tomorrow. I'm switching focus temporarily to investigate a high priority issue affecting some large customers https://expensify.slack.com/archives/CC7NECV4L/p1706641694016129

**Comment by youssef-lr** [comment]
On it today again.

**Comment by youssef-lr** [comment]
I should have an update in a couple of days.

**Comment by youssef-lr** [comment]
App PR is ready, but held on an Auth PR.

**Comment by trjExpensify** [comment]
App PR merged and on staging!

**Comment by youssef-lr** [comment]
Not yet @trjExpensify :( 

>This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by trjExpensify** [comment]
Huh, is this wrong then? https://github.com/Expensify/App/pull/36388#issuecomment-1984810367

**Comment by youssef-lr** [comment]
oh weird it really wasn't showing for me.

**Comment by garrettmknight** [comment]
Assigning myself to handle BZ stuff.

**Comment by garrettmknight** [comment]
Updating to daily to pay on Monday. @hoangzinh are you getting paid via NewDot these days? Linking [SO](https://stackoverflowteams.com/c/expensify/questions/16949) to for myself update if you are.

**Comment by garrettmknight** [comment]
Bummer - [offer](https://www.upwork.com/nx/wm/offer/101399051) is out to you!

**Comment by garrettmknight** [comment]
Paid, closing
