### ISSUE TITLE
[HOLD ON #313934] [$500] Web - An error is displayed when entering the message section of the contact email

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34960]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Navigate to Settings > Profile > Contact Method and add a new contact method.
2, In any conversation, type "@" followed by selecting your contact email.
3, Return to Settings > Profile > Contact Method to change the default contact method.
4, Go back to the conversation, click on the email, and open the detail page. Click on the message and observe the display of "Author Report Error."

## Expected Result:
The "Author Report Error" should not be displayed when entering the message section of the main email after changing the default email. Alternatively, the message section should not appear in the detail section

## Actual Result:
After changing the default contact email, clicking on the main contact email in the conversation opens the detail section. Clicking on the message displays the "Author Report Error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4965af24-5742-4813-9e39-7d2d5c04161a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01316b4650bb5e8a4d</li>
        <li>Upwork Job ID: 1749777717941891072</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by eVoloshchak** [comment]
I think we can proceed with @tienifr's proposal (https://github.com/Expensify/App/issues/34960#issuecomment-1906033895)
It's a better approach, we would be able to mention a single user using different contact methods (i.e. mention is defined by user ID, not by user login)

🎀👀🎀 C+ reviewed!

**Comment by FitseTLT** [comment]
What if a login didn't belong to the user at the time of the mention and
then it was added as a contact method? we still be facing the current
issue.

**Comment by FitseTLT** [comment]
> > What if a login didn't belong to the user at the time of the mention and then it was added as a contact method?
> 
> @FitseTLT The back-end can update the `accountID` of the `mention-user` once the mentioned user is added as current user's contact method, also for data consistency. We'll have no issue there.

U are talking about updating all the mentions of the login in all the chats. This is not feasible. The selected proposal doesn't fix the current issue but instead will create a regression because now if a mention was linked to one account and later if the user changes the login for that account and instead use the previously mention login to open another account the mention will wrongly link to the wrong user. And the backend update @tienifr is suggesting is not feasible which means the backend should update all mentions of a login (in all chats) whenever the login is newly added to a contact method of a user account (b/c if it wasn't a contact method at the time of the mention it will not be linked to the user account).

**Comment by FitseTLT** [comment]
@AndrewGable @eVoloshchak 
I think the current login-based mention is correct and changing it to account-based mention will create problems I have mentioned in the above comments. Moreover, focusing on this specific issue if we follow the selected proposal with mentions mentioned before the secondary contact method is added this issue will re-occur. Therefore, as the chosen proposal will not fix this issue and recreate other issues instead I suggest you consider my [proposal](https://github.com/Expensify/App/issues/34960#issuecomment-1906028842) which is a simple solution to the current issue and doesn't create other issues. Thanks!

**Comment by eVoloshchak** [comment]
> if a mention was linked to one account and later if the user changes the login for that account and instead use the previously mention login to open another account the mention will wrongly link to the wrong user

@FitseTLT, I would argue this is the expected behavior, other massaging apps do the same. 
Let's take Telegram as an example: 

1. you mention a userA by their username
2. userA changes their username 
3. if username wasn't taken by someone else, the old mention is still linked to userA
4. if username was taken by another account, the old mention is linked to that new account

**Comment by FitseTLT** [comment]
>4. if username was taken by another account, the old mention is linked to that new account

Yep. @eVoloshchak I wasn't denying that but it needs a BE task to link those old mentions with the new account and am not sure it is feasible now to deal with the current minor issue. :+1: But without these BE changes we will definitely be causing regressions.

**Comment by muttmuure** [comment]
I've been reviewing the issue and will summarize shortly, and will chat with Andrew

**Comment by muttmuure** [comment]
Posted about this issue here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707756897713839

**Comment by AndrewGable** [comment]
Sounds like this is now a part of a VIP, should we re-label it to reflect that?

**Comment by muttmuure** [comment]
I just realized that this is being worked on here: https://github.com/Expensify/Expensify/issues/313934

**Comment by muttmuure** [comment]
Held on https://github.com/Expensify/Expensify/issues/379005
