### ISSUE TITLE
[HOLD for payment 2024-03-26] [HOLD on E/E #347391] Revert to Approved due to failed reimbursement action doesn't show in newDot

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34968]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706011919649459

## Action Performed:

1. Add a deposit account that will not accept deposits into it
2. Submit an expense for reimbursement
3. Have an admin pay that report
4. Wait for the reimbursement to fail

## Expected Result:
Revert to Approved due to failed reimbursement action should appear

## Actual Result:
Revert to Approved due to failed reimbursement action doesn't show in newDot
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (2)](https://github.com/Expensify/App/assets/43996225/fa0b3550-87bb-4b3b-95ae-57493066a8e5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
@kavimuru did you try to reproduce this?

**Comment by zanyrenney** [comment]
I saw @twisterdotcom added the additional reproduction steps.

**Comment by twisterdotcom** [comment]
I'm not sure Applause can test this payment flow? Regardless, I think we might already know we need to handle this as part of @sophiepintoraetz's project, so we could HOLD until that's under way.

**Comment by zanyrenney** [comment]
ah okay, thanks @twisterdotcom

**Comment by zanyrenney** [comment]
As this is on HOLD, i'm dwongarding this to weekly.

**Comment by zanyrenney** [comment]
on hold currently

**Comment by zanyrenney** [comment]
I believe this is still on HOLD.

**Comment by twisterdotcom** [comment]
Holding on the project: https://github.com/Expensify/Expensify/issues/347391

**Comment by zanyrenney** [comment]
ON HOLD.

**Comment by zanyrenney** [comment]
https://github.com/Expensify/App/pull/37022 In draft for PR.

**Comment by twisterdotcom** [comment]
No payments or tests required for this one. Handling all in https://github.com/Expensify/App/issues/36023#issuecomment-2008308732
