### ISSUE TITLE
 Physical card number on card details page should not be bold

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706004178145769

## Action Performed:
Go to Wallet and then view a connected Expensify Card
## Expected Result: 
The row for your physical card number should use a regular font weight to match the digital card number above it
## Actual Result: 
Physical card number is incorrectly using bold weight font

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-01-23 at 11 02 05@2x](https://github.com/Expensify/App/assets/43996225/50e0c763-64e1-47cf-9cb7-f6cadc8884f2)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
@RohanSasne - I'm just a little behind on getting this moved forward. I'm assessing now and will have an update soon.

**Comment by strepanier03** [comment]
I actually can't repro this, both card numbers are unbold for me. On Mac/Chrome/Staging

<img width="354" alt="image" src="https://github.com/Expensify/App/assets/10925636/ab8fb711-b3e1-4f73-9138-872181764501">

**Comment by grgia** [comment]
pretty sure this was fixed in https://github.com/Expensify/App/pull/34677

**Comment by shawnborton** [comment]
Oh nice, that could very well be it. I just checked my account again and this seems to be fixed, so I will close!
