### ISSUE TITLE
[$500] Web - Getting an "api?command=Ping" failed network request after coming online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34962]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4205550&group_by=cases:section_id&group_id=229043&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in
2. Disable the network
3. Switch between chats in the LHN
4. Enable the network and open the Chrome console

## Expected Result:
I shouldn't be getting a failed network request

## Actual Result:
Getting an "api?command=Ping" failed network request after coming online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dcad5372-4d46-42f7-b94d-1c79b25f4b3e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a8b74b3dc3378ab</li>
        <li>Upwork Job ID: 1749787294754537472</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by cead22** [comment]
I think this is a non-issue, unless there's repeated failing requests, but if it's one or two, it's expected since this happens when coming online after being offline. @lanitochka17 is that the case? If not, I think we should close this
