### ISSUE TITLE
[$500] Web - Chat - New chat user's profile page accessible in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34979]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4209291&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. Disable the internet connection
3. Search for a user that you have not opened a conversation with
4. Click the header of the conversation (Note: Cursor is enabled & can open profile page)
5. Click on the display of the user in welcome message text ((Note: Cursor is enabled & can open profile page)
6. Create a group chat with the user
7. Click on the header of the group chat
8. Click on the avatar of the user

## Expected Result:
User should not be able to open the profile page of a user that has never had a conversation with while offline. The profile should not be accessible in the different areas were it can be accessed by (1:1 header, welcome message, group participants, etc)

## Actual Result:
New chat user's profile page can be accessed in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/11493b3c-69c2-440a-a2d8-9f1f2f2f9bd2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4b80006f3020fc7</li>
        <li>Upwork Job ID: 1749841957169209344</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @gabrielessner

**Comment by johncschuster** [comment]
Thanks for attempting to reproduce it, @abzokhattab. I've added the `retest-weekly` label to the issue so we can have it run through QA testing.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment]
Not overdue, Melvin. We're waiting on another re-test.

**Comment by johncschuster** [comment]
Still waiting on a retest

**Comment by johncschuster** [comment]
@kbecciv can you retest this behavior to see if it persists?

**Comment by kbecciv** [comment]
@johncschuster Checking

**Comment by kbecciv** [comment]
@johncschuster Issue is still reproducible!

https://github.com/Expensify/App/assets/93399543/0bc6e892-0e5a-4ea1-aaf2-5dc195ef764d

**Comment by srisri332** [comment]
Hello @ntdiary, @johncschuster. Can someone please confirm if my observations are true, 
If you see the attached video below, we can find that when we are offline, and if we search for a user that isn't in the recently searched list (or loaded), we are unable to open user profile. I'm guessing that this is the correct functionality. 

Whereas, if we search for a user that was previously loaded when we were online (even though we might not have had a conversation with the user), we can see that we are able to open the user profile. This is the bug. I'm not sure if this is the expected behavior or if we even want to disable the loading of user profile for users that are already loaded in search. 

https://github.com/Expensify/App/assets/58304531/117c2384-2eb3-4f57-aca5-3b52a777ad8a

**Comment by srisri332** [comment]
Contributor details
Your Expensify account email: srisrireddy.k@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013c4382c91420069f#

**Comment by srisri332** [comment]
> I'm also not sure what the expected behavior is. So far, with two accounts, I got different actual result: 🥲
> 
> 1. If we search for a new user and open the report while offline, we can't access the profile page, but **once we're back online, we can access it**. And then, if we go offline again, search again, and reopen the same report, **we're always allowed to access the profile page.**
>    
>      
>        
>        
>    
>        demo-1.mp4
> 2. We always can't access the profile page while offline.
>    
>      
>        
>        
>    
>        demo-2.mp4

Hello @ntdiary, this is what I've observed. Sometimes it tags the account as hidden and sometimes it behaves the way you showed in the first point. I was rereferring to the behavior shown in the first point but I've observed the second one too. I'll try to see if I can come up with a root-cause-analysis and a satisfactory proposal to fix this. Thank you for sharing the details.

**Comment by johncschuster** [comment]
@srisri332 

> Whereas, if we search for a user that was previously loaded when we were online (even though we might not have had a conversation with the user), we can see that we are able to open the user profile. This is the bug. 

I disagree. I would expect that the profile data is probably stored locally because you recently loaded that profile. I think this behavior is expected.
