### ISSUE TITLE
[Tracking] Metric - Average FPS on LHN Screen (Performance audit by Callstack)

### ISSUE THREAD

**Issue by jbroma** [Expensify/App#34986]
Metric: **Average FPS on LHN Screen** 
Phase: **Measurements** 
Commit hash: [callstack-internal@e6b076](https://github.com/callstack-internal/Expensify-App/commit/e6b07616db3a818574d60acf1d9ebaf1cb26bf02)

### FPS:

Workflow:

- launch app
- wait until fully loaded
- **Start Measurement**
- scroll down 8 times
- scroll up to the top

Measurement duration: **40s**

| Round | FPS |
| ----- | --- |
| 1     | 60  |
| 2     | 60  |
| 3     | 60  |
| 4     | 60  |
| 5     | 60  |
| 6     | 60  |
| 7     | 60  |
| 8     | 60  |
| 9     | 60  |
| 10    | 60  |

**Average FPS: 60**

### Example FPS chart from flashlight measure:
<img width="1450" alt="Screenshot 2024-01-23 at 19 55 50" src="https://github.com/Expensify/App/assets/20626315/6967f3ad-3d75-49b7-8ced-6b3f4aa78b11">

### Additional markers Avg CPU usage, AVG RAM usage:

| Round | Avg CPU usage (%) | AVG RAM usage (MB) |
| ----- | ----------------- | ------------------ |
| 1     | 89.8              | 659.9              |
| 2     | 86.8              | 691.1              |
| 3     | 87.4              | 686.4              |
| 4     | 86.8              | 665.1              |
| 5     | 87.3              | 674.9              |
| 6     | 86.7              | 711.7              |
| 7     | 86.4              | 694.3              |
| 8     | 87.8              | 697.0              |
| 9     | 99.2              | 671.0              |
| 10    | 99.8              | 649.1              |

Avg from all rounds -> CPU usage (%): **89.8**
Avg from all rounds -> RAM usage (MB): **680.1**

### Example charts from flashlight measure:

**Total CPU:**
<img width="1450" alt="Screenshot 2024-01-23 at 19 55 11" src="https://github.com/Expensify/App/assets/20626315/21e9758f-9d45-4f3f-8ff3-f1b61ef503af">

**CPU per Thread:**
<img width="1450" alt="Screenshot 2024-01-23 at 19 54 00" src="https://github.com/Expensify/App/assets/20626315/a2b01509-b84e-4199-aacd-d723e14266e1">

**RAM:**
<img width="1450" alt="Screenshot 2024-01-23 at 19 56 08" src="https://github.com/Expensify/App/assets/20626315/594fd6e5-ad90-465f-b3c9-148566fc713b">

**Comment by jbroma** [comment]
Tracking issue for the `Average FPS on LHN` as part of the Performance audit conducted by Callstack.

Part of https://github.com/Expensify/App/issues/33070

**Comment by jbroma** [comment]
Metric: **Average FPS on LHN Screen** 
Phase: **Analysis** 
Commit hash: [callstack-internal@e6b076](https://github.com/callstack-internal/Expensify-App/commit/e6b07616db3a818574d60acf1d9ebaf1cb26bf02)

## Analysis

- LHN screen is stable without freezing during scrolling. 
- 60 FPS is maintained during all of the runs done during the measurement phase. 
- Thanks to offloading all of the work to the loading phase (resulting in no need for pagination), the list is able to reuse list cells without visible performance penalty, ensuring smooth experience
- Spikes in CPU usage, especially on the native thread are result of rendering new window of virtualized list
- Memory stays almost constant during all of the runs

## Summary

Performance target is reached, therefore there is nothing actionable about this metric.
This issue should be revisited if in the future there is a need for pagination, which might result in overload of the `mqt_js` thread, as it's already almost maxing out during scrolling.

**Comment by adhorodyski** [comment]
@mountiny 
The above also means there's no need to pick actionable items in here. We'll revisit this metric in the Control phase to make sure we're monitoring the current state over time 😊
Please let me know if you're ok with this!

**Comment by mountiny** [comment]
That sounds great! Glad the FlashList helped here too I assume

**Comment by muttmuure** [comment]
We can close this?

**Comment by mountiny** [comment]
I think so
