### ISSUE TITLE
[$500]  Collect approver - Add bank account message only appears for employee after refreshing page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34990]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211927
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are part of Collect workspace on Old Dot
- Admin has a verified bank account set up on Old Dot
- Employee does not have a bank account set up
1. [Employee] Request money from the workspace chat
2. [Employee] Go to expense report and submit the report
3. [Admin] Approve the request
4. [Employee] Refresh the page after "Next step" message is updated on its own

## Expected Result:
"Add bank account" message will appear together with new "Next step" message

## Actual Result:
"Next step" message updates, but "Add bank account" message does not appear until after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d6cf1c66-7711-4eb4-889a-a8a0d82a147d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5409f4e4057f2d0</li>
        <li>Upwork Job ID: 1749876267053379584</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave7. 
CC @RachCHopkins

**Comment by puneetlath** [comment]
This sounds like a back-end issue where we aren't pushing the data.

**Comment by fpearlf** [comment]
Hello , I would love to hack on this. Please assign this  issue to me.

**Comment by fpearlf** [comment]
Contributor details
Your Expensify account email: forchapearl1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0167cc1981d32b23ac

**Comment by puneetlath** [comment]
I believe so yes.

**Comment by alexpensify** [comment]
Cool, I'll work on it early next week.

**Comment by alexpensify** [comment]
I've been dealing with a power outage and I needed to focus on the most urgent GHs. No update yet.

**Comment by alexpensify** [comment]
Rach helped me out and Marco is going to give this one a review after another critical issue. 

Slack Thread: https://expensify.slack.com/archives/C02NZ2HGJAZ/p1707278975708859

**Comment by alexpensify** [comment]
Daily Update: PR is in draft mode.

**Comment by marcochavezf** [comment]
[PR up](https://github.com/Expensify/Web-Expensify/pull/40857)

**Comment by alexpensify** [comment]
Awesome! Thanks for the update @marcochavezf!

**Comment by marcochavezf** [comment]
PR deployed to production, closing out
