### ISSUE TITLE
[$500] Android – Attachment – App flickering when uploading a long image to a conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Log in with the account
3. Open any chat
4. On a conversation, click on the + button in the compose box
5. Upload long image to a conversation

## Expected Result:
Preview of the image is displayed before uploading to the conversation

## Actual Result:
App flickering when uploading a long image to a conversation in preview. Flashes on first boot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6b67556d-5092-4093-a749-5c3ec83a3dd2

![Bug6352453_1706038657893!bigggg](https://github.com/Expensify/App/assets/78819774/fbab31e6-1965-4143-81ae-1b0170819bd4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d877180b69b96f5</li>
        <li>Upwork Job ID: 1749885428346445824</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28132224</li>
<li>ZhenjaHorbach | Contributor | 28132225</li>
</ul></li>
    </ul>
</details>

**Comment by jjcoffee** [comment]
Reviewing tomorrow!

**Comment by jjcoffee** [comment]
@ZhenjaHorbach Thanks for the proposal! The RCA feels a bit underdeveloped; I'm curious why `onLoad` is being called multiple times if it's only supposed to be called once. I also wonder if this is device specific?

@lanitochka17 Could you update/add which platforms this affects?

**Comment by lanitochka17** [comment]
The issue is only reproducible on Android

**Comment by jjcoffee** [comment]
Thanks for the extra detail! Happy to go with @ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/34998#issuecomment-1908332122) here. The RCA seems correct that we're simply calling `onLoad` multiple times on Android (for some reason with different sizes), and the solution makes sense for that.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
@ZhenjaHorbach Thanks for flagging! Did you verify that the issue is fixed?
