### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500] Android - Add bank account - Choose an account hardly visible when light them applied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35008]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, unable to check prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4228288
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: the light mode has been applied
1. Open the app and log in
2. Navigate to any workspace settings > Bank account > Connect online with Plaid or Wallet > Add bank account > Personal bank account
3. Select e.g. Wells Fargo and continue with credentials
4. Select Checking and Savings accounts
5. Finish with the Plaid flow
6. On the Add bank account page open the selector

## Expected Result:
The text in the modal is fully visible

## Actual Result:
"Choose an account" is hardly visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6352533_1706042444637!photo_2024-01-23_13-48-44](https://github.com/Expensify/App/assets/78819774/07471c36-11ab-4bf5-bea5-0af06a0bf23b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d11e22a4c76ac05</li>
        <li>Upwork Job ID: 1750031291554013184</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 28118930</li>
<li>mkhutornyi | Contributor | 28118931</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by thienlnam** [comment]
@mkhutornyi Are you around to handle this?

**Comment by thienlnam** [comment]
Sweet - I'll assign ya!

**Comment by thienlnam** [comment]
Pretty straightforward change and in a rush so I'll take over the C+ role for this PR

**Comment by thienlnam** [comment]
@mkhutornyi Please ping me when you get a PR up and ready to review!

**Comment by thienlnam** [comment]
I'm realizing now that the change that added this was back in December, so it's likely that this is also happening on production which doesn't make this a blocker. In any case, we got it merged so it should be fixed on the next cycle. Thanks for the urgency here @mkhutornyi!

**Comment by muttmuure** [comment]
$500 - @mkhutornyi

**Comment by muttmuure** [comment]
Paid

**Comment by muttmuure** [comment]
@mkhutornyi please can you complete the regression checklist and then we can close

**Comment by muttmuure** [comment]
thank you
