### ISSUE TITLE
[$500] Android - Workspace - Custom Workspace avatar photo disappears after uploading and reappear after a while

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35003]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create Workspace
2. Navigate to Settings page and upload custom image for Workspace

## Expected Result:
Uploaded image should be stable

## Actual Result:
Custom Workspace avatar photo disappears after uploading and reappear after a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/00e04549-d3aa-4e50-88c7-b0a9229954bf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010841358696844191</li>
        <li>Upwork Job ID: 1749894679869579264</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Not a blocker since it's reproducible in staging and production

**Comment by eVoloshchak** [comment]
Not overdue, waiting on proposals

**Comment by cristipaval** [comment]
I wonder if this is still reproducible after the navigation refactor.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by cristipaval** [comment]
Thanks @rezkiy37 , you're good to go 🚀

**Comment by cristipaval** [comment]
Great! Thanks @rezkiy37 for investigating!
