### ISSUE TITLE
Feature request: Merchant field should display the required label in workspace expenses 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35012]
# Feature Request: Add the required label to the merchant field in expenses 

### Problem:
The merchant field is required for all workspace expenses and it's not displaying the `required` label as the categories and tags does. Users might not be aware that the field is required and will have to clear the error after a first attempt on creating an issue. 

### Solution:
Add the `required` label to the merchant field in workspace expenses. This will save users a click since it's _announced_ that the field is required. 

**Context/Examples/Screenshots/Notes:**
This would also solve the inconsistency between the `required` label in the expense fields. In short words, if a single required field has the label, the rest of the required fields should also display it.  

<img src="https://github.com/Expensify/App/assets/44479856/af126893-18bf-4b0b-b546-f58099e3ae80" width="40%">

**Raised by**: @JmillsExpensify 
**Slack conversation**: https://expensify.slack.com/archives/C049HHMV9SM/p1705515336854489

**Related project**: Wave 9 violations

**Comment by cead22** [comment]
I'm taking this one over and will work with IR to implement this, since it's similar to what we just did for violations. More context on this thread https://expensify.slack.com/archives/C049HHMV9SM/p1706050971212759?thread_ts=1705515336.854489&cid=C049HHMV9SM

**Comment by cead22** [comment]
No updates yet, focused on other things including prioritizing other things related to violations

**Comment by cead22** [comment]
I'll try to prioritize this tomorrow and turn it into an issue that can be worked on by contributors

**Comment by cead22** [comment]
@lindboe please comment for assignment, thanks

**Comment by cdanwards** [comment]
Commenting for assignment

**Comment by Christinadobrzyn** [comment]
This could maybe be part of this fix? https://github.com/Expensify/App/issues/36574

**Comment by cead22** [comment]
This issue is already done, since the PR was merged, only thing left is payment. I'll comment on that other issue

**Comment by cead22** [comment]
Oh, now that I see that issue in detail, I think what you're saying is that the fix for this issue caused the one you linked. Looking at the PR for this issue, I don't think it was, but I think it was a PR for a violations issue that I reviewed this week, let me find it

**Comment by cead22** [comment]
I believe it was this one https://github.com/Expensify/App/pull/35641/files
