### ISSUE TITLE
Expense reports were marked as unread after an action was taken in the OD report

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705074066695899

## Action Performed:

1. create a report on NewDot on a workspace that has workspace chats enabled
2. submit it
3. get it approved
4. Go to OldDot
5. Open the same report on OldDot
6. Export it to CSV
7. Go back to NewDot
8. See that the report is unread in the LHN

## Expected Result:
Reports should have a hidden notification preference set so chats are not marked as unread when an action is taken in OD. 

## Actual Result:
Expense reports were marked as unread after an action was taken in the OD report. 
More details from @Puneet-here: 
> I just had a bunch of expense reports become unread in my LHN with no reportAction. I’m guessing this is because some action was taken (e.g. export) that we don’t support in NewDot. But shouldn’t these reports have the “hidden” notification preference?

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/26a147a1-11cf-4de6-b1ca-e96207620826)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011129fa62c9ec5948</li>
        <li>Upwork Job ID: 1749952975078166528</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by isagoico** [comment]
Closing this issue per this discussion - https://expensify.slack.com/archives/C049HHMV9SM/p1706056788392159?thread_ts=1705074066.695899&cid=C049HHMV9SM

**Comment by sophiepintoraetz** [comment]
I think we can close this - we will solve this as a part of https://github.com/Expensify/Expensify/issues/347391
