### ISSUE TITLE
[HOLD #33579] Email - Email notification for thread has weird subject line

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35024]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705630034197589

## Action Performed:
1. Participate in a thread
2. Add a comment
3. Read email as other participant

## Expected Result:
Subject should not use the `reportName` value indiscriminately. `Chat Report` is a special value that doesn't really show up in the UI anymore and probably is not used for anything really.

## Actual Result:
subject line: `[Expensify Chat] Chat Report Expensify Chat`

## Workaround:
N/A
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af7ac854adfac3d8</li>
        <li>Upwork Job ID: 1749958053569523712</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by rlinoz** [comment]
This is happening because when we send a notification about a thread we use the report name, which for threads is `Chat Report` [here](https://github.com/Expensify/Web-Expensify/blob/9ee8634158145251dc55598c10d4bbe3641d99c7/lib/Notification/Report/Comment.php#L99)

This will be fixed when we are done with https://github.com/Expensify/App/issues/33579

**Comment by sakluger** [comment]
Thanks @rlinoz, I put this issue on hold for https://github.com/Expensify/App/issues/33579 and switched to weekly. Although if you are very confident about the other issue solving the issue, we can close this as a duplicate? Let me know, thanks!

**Comment by quinthar** [comment]
I think we can close this as a dupe.
