### ISSUE TITLE
[$500] Copy pasted text in the compose box loads when opening any report 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y (occasionally reproduced)
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706024319438839

## Action Performed:
1. Open any report 
2. Copy paste the text in compose box
3. Log out login or open any other chat 

## Expected Result:
Should not appear the copy pasted text

## Actual Result:
Text appears in some other chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/a93f6556-7b88-4403-a973-d6b211d26f46

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014eb6c8e6cf9fe6eb</li>
        <li>Upwork Job ID: 1750031646824427520</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
Same root cause as https://github.com/Expensify/App/issues/34296 https://github.com/Expensify/App/issues/31705

**Comment by jeremy-croff** [comment]
This seems like desired behaviour - saving draft messages by reportId untill manually cleared.
Other apps like slack do this also.
Prevents progress and data loss

**Comment by subhampanja2** [comment]
Unable to reproduce it.
