### ISSUE TITLE
Awaiting merge with card transaction error shows up for cash transaction

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35020]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @luacmartins 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705808926749559

## Action Performed:
1. Submit a receipt for smartscan
2. Once done change the currency to CAD

## Expected Result:
Error about merging with card should not display and user should be able to change the currency. 

## Actual Result:
Awaiting merge with card transaction error shows up for cash transaction

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/Expensify/App/assets/44479856/8510d994-8d51-4e09-ac89-39776391ed70" width="40%">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174349ad23995a507</li>
        <li>Upwork Job ID: 1749947775480446976</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
@cead22 are you leading this?

**Comment by dylanexpensify** [comment]
bump @cead22 🙇‍♂️

**Comment by cead22** [comment]
Yes? I'm not sure what you mean. 

@luacmartins 
- Is this violation still showing? 
- Does it show on old dot?
- Can you share transactionID/reportID?

**Comment by luacmartins** [comment]
>Is this violation still showing?

No

>Does it show on old dot?

No and I'm not sure if it ever did.

>Can you share transactionID/reportID?

reportID 1213827147775051
transactionID 7341037708387093677

**Comment by cead22** [comment]
I think this is working as expected. This issue was opened --and the violation was showing, on Jan 23, which is 6 days after the transaction created date of Jan 17. We show that violation up to 7 days, which explains why it's no longer showing. I said working as "expected" and not "correctly" because this is a warn, and not a violation, and we have a PR in the works that will filter warns so they don't show. So I'm going to close this since it'll be resolved when that PR gets merged
