### ISSUE TITLE
[$500] EReceipt - Card section in EReceipt for Expensify transaction is blank

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35036]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Wave/Project Suggestion : #wave5-free-submitters

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Log in to account with Expensify Card transaction ([tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
).
2. Go to workspace chat with the transaction (https://staging.new.expensify.com/r/4612388815642526
).
3. Open transaction that has card number in the receipt (identify from Old Dot). (https://staging.new.expensify.com/r/4366841222340859
)
4. Open the receipt.
## Expected Result:
The card section shows the card detail.

## Actual Result:
The card section is blank.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/7f8a24e5-6dab-4133-81db-31904bbb63d0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143ec88c80eec0c3c</li>
        <li>Upwork Job ID: 1750052229901262848</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by AzhanJaved** [comment]
Hi there,
I'm a React Native developer with 5+ years of experience, eager to solve the elusive case of the blank card section in Expensify EReceipts (issue #35036). Having delved into the clues (comments, video evidence), I propose a two-pronged investigation to unveil the culprit and restore card information with aplomb.

My Proposed Solution:
1. Data Detective:
Following the Breadcrumbs: Employing debugging tools, I'll track the data flow, sniffing out any missing information between the backend and the EReceipt. APIs, authentication, and parsing will be under my digital microscope.
Error Trapper: Unit tests will be my secret weapon, capturing any rogue errors or edge cases that might be hiding the card details.
2. Conditional Conundrum:
Logic Lens: I'll scrutinize the component responsible for displaying the card information, dissecting its conditional rendering logic for inconsistencies or missing variables. React DevTools will be my trusty sidekick, visualizing the component hierarchy and state.
Test the Hypothesis: Through comprehensive unit tests, I'll verify that the card information displays correctly under various scenarios, ensuring a permanent fix.

I'm eager to delve deeper into the investigation and discuss my findings in the GitHub issue. Looking forward to your response.

Regards,
Arbaz

**Comment by AzhanJaved** [comment]
Contributor details
Your Expensify account email: muhammadazhanjaved9191@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/~01ffc7b6b8084ce2fd

**Comment by AzhanJaved** [comment]
Hi @olly Thanks for responding back. I’ve applied for the the job on upwork too
Here is the link to my profile:https://www.upwork.com/fl/~01ffc7b6b8084ce2fd

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dragnoir** [comment]
@Ollyws do you think we can have an Expensify Card transaction account for testing?

**Comment by dragnoir** [comment]
I can simulate using this https://expensify.slack.com/archives/C01GTK53T8Q/p1705450786474319?thread_ts=1705450150.383239&cid=C01GTK53T8Q

but I can't reproduce the issue.

**Comment by adelekennedy** [comment]
I can't reproduce this either, going to add the retest weekly label

**Comment by adelekennedy** [comment]
still not reproducing
