### ISSUE TITLE
Strip 'staging.' from all "Tap to respond on..." messages; always use production URL

### ISSUE THREAD

**Issue by arielgreen** [Expensify/App#35030]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @arielgreen 
**Slack conversation:** https://expensify.slack.com/archives/C05RECHFBEW/p1705949013462059

## Action Performed:
I sent a message from staging to a mobile number.
## Expected Result:
It should say "Tap to respond on https://new.expensify.com/r/5756502484063455"
## Actual Result:
It says "Tap to respond on https://staging.new.expensify.com/r/5756502484063455"

## Workaround:
Don't use staging
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![87110](https://github.com/Expensify/App/assets/37308300/938ff74f-d41b-4405-858a-76fbc8f3fc84)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017012367aeff2bafd</li>
        <li>Upwork Job ID: 1750035153222078464</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by iwiznia** [comment]
I disagree with this issue, if you use staging, we run code in staging, if you use prod, we run code in prod. This is important as it allows us to QA things in staging.
