### ISSUE TITLE
Different handling for text_title report fields

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#35043]
The text_title report field are inherently different than the other report fields. They're the only report fields that use formula values and are an actual property on the report itself. We'll need to handle this differently from other report fields.

The policyReportFields_policyID onyx key will tell us if the following parameters about the report title
- Can it be modified? 

When this field exists on a policy, we will show the title report field. However, it's value is derived from the reportName of the report, and when you try to update it - you will have to call the API with these parameters

command: RenameReport
reportID: 6279759066218631
reportName: "Expense Report 2024-01-24 121331"

We'll use the details from the policyReportFields_policyID onyx key to see if we can modify this field.

We will no longer need to pass the text_title to Report_SetFields

You should be able to test this by creating a workspace chat in NewDot with these steps
```
To enable this "beta" for any given policy:

Go to OldDot and open the settings for the Collect/Control policy

In the JS console with the policy open do:

p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = "true";
p.save();
This will make it so that any user you invite to that policy going forward will have a Workspace Chat created in NewDot for that policy. It will not retroactively create a workspace chat for the policy owner or any other user that was already a member of the policy before you enabled the beta.
```

**Comment by thienlnam** [comment]
@allroundexperts Let me know if this makes sense, or if there's anything I can clarify here - the BE is already set up for this command

**Comment by allroundexperts** [comment]
Hi @thienlnam. I'll check this out today and follow up!

**Comment by allroundexperts** [comment]
> We'll use the details from the policyReportFields_policyID onyx key to see if we can modify this field.

@thienlnam Can you please explain what details from the `policyReportFields_policyID` collection would determine if we can edit the title or not?

**Comment by thienlnam** [comment]
If it has the deletable field set, we can modify the report title - if not, we would not be able to

**Comment by allroundexperts** [comment]
Added these changes in https://github.com/Expensify/App/pull/34483
