### ISSUE TITLE
[$500] Smartscan does not read different currencies

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35040]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @thienlnam 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706076013705469

## Action Performed:
1.  Scan a receipt that contains a different currency
2. Notice that smartscan things it is $6900
## Expected Result:
Admittedly, it's not like it shows the currency symbol anywhere, but the rest of the receipt is in Korean

## Actual Result: 
Thought the receipt was in USD

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Snip - (3) New Expensify - Google Chrome (5)](https://github.com/Expensify/App/assets/43996225/c3b69319-1406-4166-95dc-a44a6820385e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f63c7f179ed0824</li>
        <li>Upwork Job ID: 1750220577026203648</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by Tony-MK** [comment]
The backend returns the user's local currency if it fails to recognize the currency. 

Hence, this might need to be handled internally.

**Comment by thienlnam** [comment]
Closing since this is an agent error we'll need to fix through a different flow
