### ISSUE TITLE
Widespread Android Exception: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#35049]
### Problem

@Expensify/mobile-deployers 

There seems to be a new crash in NewDot a recent release. The email mentions version `1001043102`, but this actually started occuring in version `1001042900 ` 1.4.29-0, which was a couple of releases ago... was the Firebase checkist step missed somehow? 

<img width="531" alt="Screenshot 2024-01-24 at 10 43 58" src="https://github.com/Expensify/App/assets/10736861/62007075-ec16-4026-889f-5d8a3f11140c">

[Here's](https://console.firebase.google.com/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/022302da0d55dfb152b0c7d7d51a24a7?time=last-seven-days&types=crash&sessionEventKey=65B0E34600C3000115D533110AE45D89_1906052090420419923) the Firebase exception & stack trace:

```
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'push' of undefined, js engine: hermes, stack:
use@1:2023797
anonymous@1:2064016
loadModuleImplementation@1:162235
guardedLoadModule@1:161468
metroRequire@1:160751
anonymous@1:2061618
```

I'm sick today and just completing chores, so can't spend any more time here. I didn't add the blocker label as this has existed in two prior versions, but we may want to block the next release until this is resolved as it seems pretty bad.

### Solution

Locate the issue that introduced this. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131326c989b3bc942</li>
        <li>Upwork Job ID: 1750109819789500416</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by situchan** [comment]
@Julesssss this is deploy blocker, came from https://github.com/Expensify/App/pull/32326#issuecomment-1907639153

**Comment by situchan** [comment]
reverting [here](https://github.com/Expensify/App/pull/35046)

**Comment by Julesssss** [comment]
Ah thank you

**Comment by Julesssss** [comment]
Okay, so we're all good here. We need to improve our Firebase exception though, as this major regression is currently on prod. I'll leave the issue open for a bit in case anyone has any suggestions.

If we had time, showing all newly occurring exceptions in the checklist would be a nice improvement. We could then require manual review and comment for each new exception.

**Comment by thienlnam** [comment]
> We need to improve our Firebase exception though, as this major regression is currently on prod

I believe this only made it to staging, the [PR](https://github.com/Expensify/App/pull/32326) that introduced the crashes were added to staging - crashing was found and then reverted in this same deploy https://github.com/Expensify/App/issues/35037

I also handled the deploy yesterday, and this specific crash did not show up on firebase

**Comment by Julesssss** [comment]
Okay yeah, we did release this to production. Thankfully only 6 users experienced the crash. I still think we need to prevent this from happening as if it was released on a weekend or post-reunification it would have been much worse. 

<img width="515" alt="Screenshot 2024-01-25 at 10 35 35" src="https://github.com/Expensify/App/assets/10736861/192aa9fc-d1ea-4d02-bfb6-804223034b0d">
<img width="367" alt="Screenshot 2024-01-25 at 10 32 05" src="https://github.com/Expensify/App/assets/10736861/9dd836ae-3095-462e-af96-770389e106b6">

**Comment by mountiny** [comment]
I think thats my bad, when it comes to the first occurrence, sorry! I saw it happening in staging but it was isolated to only OnePlus devices so that one seemed as device specific and i did not want to block deploy for it. 

Since it then disappeared i did not create an issue for it.

The second occurrence was obviously much more critical so thanks for flagging

**Comment by Julesssss** [comment]
There's no blame, I would have done the same if it only occurred on a single device. 

We'll need to be careful once we deploy to 1000* more users. The 7-day rollout will help, but it would still be better to catch these before we release to prod.
