### ISSUE TITLE
Integrate Recently Used Report Fields with BE

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#35042]
We're now passing back recently used report fields to Onyx

These are stored under the key `recentlyUsedReportFields ` and are keyed by the report field ID 
![image](https://github.com/Expensify/App/assets/30609178/bc276481-a6a8-4f4c-98b6-ab6856e4a13a)

Now, when you're editing a report field that uses the same report field ID, show these recently used items.

We can probably skip recently used for date and text, and only show for dropdown for now

Note: These are not keyed by policyID, so a known possible situation is where you often switch between multiple workspaces that use the same report field ID but have different values. The recently used will show up when you're submitting for the other. This is an edge case in how the recently used was designed in the past

**Comment by allroundexperts** [comment]
Added in https://github.com/Expensify/App/pull/34483

**Comment by allroundexperts** [comment]
This can be closed!
