### ISSUE TITLE
Web - The user is unable to scroll to find the appropriate workspace when creating a Room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35055]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** n/a
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704927552653669

## Action Performed:
1. Log in with [dcardoza@Expensify.com](mailto:dcardoza@Expensify.com) account
2. Click on Fab menu and Select Chat
3. Select Room option
4. Select Workspace option
5. Scroll down and search for Expensify Chat

## Expected Result:
User is able to create the room using Expensify Chat Workspace

## Actual Result:
The user is unable to scroll to find the appropriate workspace when creating a Room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/00ec6170-90db-4f4e-b344-fd339f33d1a6

![image (1)](https://github.com/Expensify/App/assets/93399543/6cb34665-a966-46d6-ab8b-59a03b25d19c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Trying to get a member of the Approved team to help me test since I can't repro ([slack](https://expensify.slack.com/archives/C05P8G4A1SP/p1706209189608079))

**Comment by garrettmknight** [comment]
Doza couldn't repro anymore, closing.
