### ISSUE TITLE
[$500]  iOS - Unable to scroll down mention list with bluetooth keyboard

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35052]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal taam
**Slack conversation:**

## Action Performed:
Precondition: Bluetooth keyboard is connected to iPhone.

1. Go to any chat.
2. Type @.
3. Scroll down the list using down key on the bluetooth keyboard.

## Expected Result:
User is able to scroll down mention list with down key on the bluetooth keyboard.

## Actual Result:
User is unable to scroll down the mention list with down key on the bluetooth keyboard.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/68fe4ad2-a09e-4b31-bdbe-e93f6712a9b1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c334686962875ddf</li>
        <li>Upwork Job ID: 1750135282240393216</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by akinwale** [comment]
The cursor keys are current unsupported in React Native. https://github.com/facebook/react-native/issues/36644#issuecomment-1484892629

**Comment by mollfpr** [comment]
Thanks @akinwale! We might be able to close this issue, but I'll test it first on a physical device to make sure.

**Comment by mollfpr** [comment]
Scrolling with the external keyboard on an iPhone on our options list is working. For example on the SearchPage or CurrencyList page.

I'm not sure the issue on RN is not supporting the arrow key listener which limits us from fixing the issue, so maybe keeping this issue open for several days to see if someone has their proposal.

**Comment by mollfpr** [comment]
No proposal yet.

**Comment by puneetlath** [comment]
Posted about whether this is important to support here: https://expensify.slack.com/archives/C01SKUP7QR0/p1706906089776339

**Comment by puneetlath** [comment]
Going to close after discussion, as we are not focused on supporting bluetooth keyboards for our mobile phone apps. Feel free to comment/reopen if you disagree!
