### ISSUE TITLE
[HOLD for payment 2024-02-05] [HOLD for payment 2024-02-01] LHN - The employee's LHN account is displayed instead of the room name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35068]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
Configure the OldDot administrator account and invite the employee to the policy https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0
Steps:
1. Open https://staging.new.expensify.com/
2. Log in with the account of the employee added to the policy
3. Navigate to the group policy chat room

## Expected Result:
The Group Policy chat should display correctly and have its name in the LHN, just as it is displayed in the chat header itself

## Actual Result:
The Group Policy Room chat of an employee is not displayed correctly in the LHN. The employee name is displayed instead of the policy name.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/86966588-9ad6-4783-a64a-33c8aff3aed3

![image](https://github.com/Expensify/App/assets/93399543/0f1e7683-5af9-44a1-8238-c20813d1e3d9)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
<img width="1086" alt="Screenshot 2024-01-25 at 2 28 29 PM" src="https://github.com/Expensify/App/assets/30609178/ed715a15-3c05-4745-b580-2292b96cf722">
Appears to be fixed in one of those issues
