### ISSUE TITLE
 Changing description gives error even though it works

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:**  needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705625258028629

## Action Performed:
1. Go to an expense
2. Change description of the expense
3. Get error saying "Unexpected error editing the money request, please try again later"
4. See that the description has changed even though it threw an error

## Expected Result: 
Expecting no error and the description changes. Or throw error, but the description shouldn't change.

## Actual Result: 
Get error saying "Unexpected error editing the money request, please try again later"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-01-19 at 10 42 42@2x](https://github.com/Expensify/App/assets/43996225/762d3997-46d2-4ea6-86f2-5aba78ac7c8f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment]
@dubielzyk-expensify looks like this was related to an issue that has released a fix. 
Can you try to reproduce and see if this is still happening?

**Comment by dubielzyk-expensify** [comment]
Tested it this morning and it seems to have been fixed
