### ISSUE TITLE
[HOLD for #34988] [$500] Category - Selected category is absent in Recent when split scan is created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34236
## Action Performed:
Precondition: There are 5 items in Recent list for Category
1. Go offline
2. Go to workspace chat
3. Create a split scan with a valid receipt and a category
4. Go online
5. Wait for the scan to complete
6. After the scan split, open request money page and go to Category
7. Refresh the page
8. Repeat Step 6

## Expected Result:
In Step 6, the category selected for the split scan will appear in Recent list

## Actual Result:
In Step 6, the category selected for the split scan does not appear in Recent list. It only appears after refreshing the page in Step 7

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/41cde507-244f-44c0-b6e2-27b2b5f41754

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126c98dc696c7c627</li>
        <li>Upwork Job ID: 1750169212796604416</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave. 
CC @greg-schroeder

**Comment by paultsimura** [comment]
This will be fixed in https://github.com/Expensify/App/issues/34988#issuecomment-1906783247

**Comment by getusha** [comment]
@greg-schroeder i think we should HOLD this for https://github.com/Expensify/App/issues/34988

**Comment by greg-schroeder** [comment]
Held, we'll close this if it's fixed by #34988

**Comment by paultsimura** [comment]
From my side, I can confirm it's fixed:

https://github.com/Expensify/App/assets/12595293/90324d6b-b42d-4006-aee2-6370d52a6bf2

**Comment by greg-schroeder** [comment]
Looks that way. Let's close then.
