### ISSUE TITLE
Getting forced to #focus mode when log in to a new device and account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35069]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @thienlnam 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705998321036669

## Action Performed:
1. login to a new device with a new account

## Expected Result:
Should not forced to #focus mode

## Actual Result:
keep getting forced into #focus mode

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Looking for more information on the actions performed here https://expensify.slack.com/archives/C049HHMV9SM/p1706135398069819?thread_ts=1705998321.036669&cid=C049HHMV9SM

**Comment by thienlnam** [comment]
I think we can go ahead and close until someone else can reproduce
