### ISSUE TITLE
[$500] Room - Member avatar tooltip shows "Hidden" in room member list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35073]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a room
2. Go to the room
3. Click on the room header > Members
4. Hover over member avatar

## Expected Result:
Member avatar shows the correct user name or contact email

## Actual Result:
Member avatar shows "Hidden"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/23d5cb0b-9d16-4c38-945d-e2232ec8a495

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191a6dde0cd6d53c6</li>
        <li>Upwork Job ID: 1755268736264658944</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28149073</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp. 
CC @quinthar

**Comment by thienlnam** [comment]
Removing the blocker since I don't think this needs to block deploy, but something we should definitely fix

**Comment by puneetlath** [comment]
Sorry for the delay here. @thesahindia mind reviewing the existing proposal?

**Comment by puneetlath** [comment]
Payment summary: 
- C - @dukenv0307 - paid via Upwork
- C+ - @thesahindia - to be paid via NewDot. 

@thesahindia please request on NewDot. 

Thanks everyone!

**Comment by JmillsExpensify** [comment]
I need the exact amounts for payment in the summary. Thank ya!

**Comment by puneetlath** [comment]
Whoops, sorry about that @JmillsExpensify. Updated.

**Comment by JmillsExpensify** [comment]
Thank you! $500 approved for @thesahindia
