### ISSUE TITLE
[$500] Desktop - The message appears in LHN with delay roughly 30-45 seconds later after push notification received

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dannymcclain 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706060242505629

## Action Performed:
1. Go to NewDot in Desktop
2. Received push notification from another user

## Expected Result:
The message appears in LHN with NO delay after push notification received

## Actual Result:
The message appears in LHN with delay roughly 30-45 seconds later after push notification received

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d12b830d42bc2a22</li>
        <li>Upwork Job ID: 1750199427776933888</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
@dannymcclain I cannot recreate this, so I'm inclined to close unless you can? If so, could you upload a recording and see if we can find some console logs or logsearch logs?


https://github.com/Expensify/App/assets/9133401/edfbbbda-11ae-4c9d-b47a-35a175cd6fdb

**Comment by dannymcclain** [comment]
I can't repro anymore either. I wonder if it was just something that was going on that particular day? I haven't really noticed it since. Totally fine with closing it. If it comes up again, it will get reported again.
