### ISSUE TITLE
[$500] mweb/Chrome - Expense - App returns to LHN when tapping back button after refreshing request page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34236
## Action Performed:
1. Go to workspace chat
2. Create a manual request
3. Go to request details page
4. Refresh the page
5. Tap on the back button

## Expected Result:
App returns to expense report

## Actual Result:
App returns to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/220acc1e-7a61-4036-ad49-75fa3439efa5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183615511eed125fe</li>
        <li>Upwork Job ID: 1750220362340155392</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - App returns to LHN when tapping back button after refreshing request page

### What is the root cause of that problem?
It is because `HOME` is our fallback here
https://github.com/Expensify/App/blob/74f11635afab513d3c7cf12b70c286b4f3cd4d74/src/components/MoneyRequestHeader.js#L139-L140
### What changes do you think we should make in order to solve the problem?

We should give the parentReport route as a fallback
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
>different ways of navigation 
????

**Comment by FitseTLT** [comment]
1. Directly via URL - It should go back to the parent report
2. On Large screens Web - It doesn't display so no worries here
3. ON smaller screens - It applies to small screens only 👍 
4. Via deeplink ( I assume the link was a message on another report chat) - it should go back to the original report from which the link was clicked.

The only odd case is (4). If we should consider achieving that we need to pass as a fallback route the previous screen/route and if it doesn't exist (in the case of refreshing the page ) we will fallback to the parent report.

**Comment by NicMendonca** [comment]
@parasharrajat have you started that discussion yet? Can you link the thread here? Thanks!

**Comment by NicMendonca** [comment]
bump @parasharrajat!

**Comment by NicMendonca** [comment]
Starting leave so re-assigning!

**Comment by sonialiap** [comment]
I cannot reproduce. I think https://github.com/Expensify/App/pull/36050 may have solved this. Please reopen if you can reproduce
