### ISSUE TITLE
Update code to allow for redirect links from multiple sources

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#35088]
**Problem:**
Currently our code for redirecting links only expects links between community>HelpDot and we'll have to redirect from other sources.

**Solution:**
Update the code to also allow for redirects from HelpDot to UseDot. For example, we'd like  https://help.expensify.com/articles/expensify-classic/expensify-card/Expensify-Card-Perks to redirect to https://use.expensify.com/company-credit-card. Ideally we can have a folder we can easily update at anytime similar to community redirects [here.](https://github.com/Expensify/App/blob/main/docs/redirects.csv)

**Comment by coleaeason** [comment]
@caitlinwhite1 that's also supported with the updated code! The source can be from community or help and the destination can be help or use dot. So you can do any of the below combinations:

sourceURL | destinationURL
-- | --
community.expensify.com | help.expensify.com
community.expensify.com | use.expensify.com
help.expensify.com | help.expensify.com
help.expensify.com | use.expensify.com

Also this is done and merged, so feel free to make your new redirects in the redirects.csv file!
