### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] shipping physical card doesn't appear to work, and I still see the prompt to get physical card

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706120463724819

## Action Performed:

1. issue >$0 limit to a user
2. With that user, go to settings > wallet > expensify card
3. Select get physical card
4. Enter info and select Ship card

## Expected Result:
card should ship, and I should see the button to Activate physical card in card settings

## Actual Result:
I land back in the card settings, and still see Get physical card button ([video](http://g.recordit.co/bKMxpHuzCC.gif) will show that I am stuck in a loop here)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/0e93ac4b-c79b-4975-98e7-b04106841723

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d53011b40230b72</li>
        <li>Upwork Job ID: 1750277395232059392</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28123888</li>
<li>dukenv0307 | Contributor | 28123889</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
This is a core feature so we should get this fixed ASAP!

**Comment by jliexpensify** [comment]
Payment Summary

- Contributor: @dukenv0307 $500
- C+: @Ollyws $500

[Upwork job](https://www.upwork.com/jobs/~019d53011b40230b72)

**Comment by jliexpensify** [comment]
Paid and job closed!
