### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] IOU - Inconsistency seen for regular messages &IOU while interacting with thread options

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35092]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Send a message
3. Long press the message and note context menu displays "leave thread" option
4. Send a IOU
5. Long press the message and note context menu displays "join thread" option
6. Now long press text message, and tap " Leave thread"( note LHN behavior) and then "join thread" ( note LHN behavior)
7. Note, tapping on join thread, a separate conversation is not displayed in LHN
8. Now long press IOU created, and tap " join thread"( note LHN behavior) and then "Leave thread" ( note LHN behavior)
9. Note, tapping on join thread, a separate conversation is displayed in LHN

## Expected Result:
There must be consistent behavior in showing thread option in context menu for regular text messages and IOU. Similarly, consistent behavior must be shown on displaying conversation in LHN for regular text messages and IOU on tapping join thread

## Actual Result:
When we send message, context menu shows leave thread option, but while request money, join thread option is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/866bea81-4dc4-442c-afed-a30d9f7d2c92

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by paultsimura** [comment]
This is intentional. The Expense reports have a "Hidden" notification preference by default, while the messages have "Always". The "join/leave thread" buttons are displayed based on the notification preference.

**Comment by paultsimura** [comment]
> It makes sense to display this option only if the message is linked to a thread.

This was done intentionally to mimic the Slack's "Turn on/off notification for the responses".
Even if your message has no thread created, you automatically will be notified about the replies in the thread once it's created – this is only if you are the author of the message.

<img width="1172" alt="image" src="https://github.com/Expensify/App/assets/12595293/08b7a0e1-2d08-4c32-b310-8a3bac535702">

Same about messages posted by others – there might be a message that has no thread yet, but you want to subscribe to the thread once it's created (let's say, someone posted a question – it has no answers yet, but you want to be notified once they appear).

So by default, if you are the message's author, you will be notified about new replies, but you can unsubscribe (leave thread) manually. And if you are not the author – you can subscribe (join the thread) even if no thread has been created yet.

**Comment by paultsimura** [comment]
I think @srikarparsi can tell more about the expected behavior here as he was the author of the leave/join functionality

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Join/Leave Thread" options appear for Report Preview (Expense & IOU).

### What is the root cause of that problem?
We explicitly allow these options to appear for the `REPORTPREVIEW` actions:

https://github.com/Expensify/App/blob/caf91aefc70e8bb82813a421097fd37b412bb137/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L274-L285

https://github.com/Expensify/App/blob/caf91aefc70e8bb82813a421097fd37b412bb137/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L305-L317

### What changes do you think we should make in order to solve the problem?
If we want to hide the "Join/Leave Thread" options for Report Previews, we should change these conditions to check for `!isReportPreviewAction`:

```js
return !subscribed && !isWhisperAction && !isReportPreviewAction && (isCommentAction || isIOUAction) && ...
```

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
@paultsimura thanks for chiming in here and providing context cuz I was on _Team Fedi_ when thinking about
> Long press the message and note context menu displays "leave thread" option

It _seems_ weird to me that, in a DM, on a chat without a thread, that there'd be an option to 'leave thread' .  The default for receiving notifications in Slack for room for thread comments:
No notification
- User C is Member of room, ie. #expensify-open-source
- User A leaves a comment
- User B replies in thread
- User C will NOT get a notification about User B's comment in thread
If the above is true, what's the purpose of 'leave thread' if you're not going to receive notifications?  Maybe the behaviour is different in Slack DMs for threads?  Also.. if User C was to click 'leave thread' then someone tagged them in the thread, 'we' would still want them to receive that notification, right? (ie. big convo in a thread, you leave thread cuz then later someone tags you asking a question.  You'd want to be notified of that).  

My intention is to open/reopen a can o' worms if this has already been discussed and consensus was reached, just trying to understand the potential _bug_ here more (and typing out my thoughts on a Saturday morn when I need another cup of ☕ , bad)

**Comment by paultsimura** [comment]
@mallenexpensify when talking about "leave thread", I intentionally stressed out that it's true for the messages **you're the author** of. Only for these messages, the notifications are enabled by default.

**Comment by paultsimura** [comment]
> User C is Member of room, ie. #expensify-open-source
User A leaves a comment
User B replies in thread
User C will NOT get a notification about User B's comment in thread

For this scenario, the User C will have an option to "join thread", not "leave".

I'm not sure how the mentions work when you've left the thread though🤔

**Comment by mallenexpensify** [comment]
> clarified that it's true for the messages you're the author of.

ah ha, that makes sense then.  Thanks for the clarification.  Based on all the details we now have, @fedirjh , can you review @paultsimura 's proposal above?

**Comment by paultsimura** [comment]
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/35769

**Comment by mallenexpensify** [comment]
@fedirjh @paultsimura can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01457ddb9bb6fce778

**Comment by paultsimura** [comment]
Accepted, thanks @mallenexpensify

**Comment by mallenexpensify** [comment]
Contributor: @paultsimura paid $500 via Upwork
Contributor+: @fedirjh paid $500 via Upwork  

@fedirjh , will you complete the [BZ Checklist above](https://github.com/Expensify/App/issues/35092#issuecomment-1942139496)? Thx
