### ISSUE TITLE
Offline indicator is missing on Welcome to Expensify page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35110]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account
3. Welcome to Expensify page will appear
4. Go offline

## Expected Result:
Offline indicator should appear on Welcome to Expensify page when user goes offline

## Actual Result:
Offline indicator is missing on Welcome to Expensify page

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7c16d958-aaa0-44c3-8353-3b9319ee0227

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment]
This is new feature from #32154
cc: @stitesExpensify

**Comment by stitesExpensify** [comment]
Yeah, I don't think that this needs to be a blocker. If the user goes offline and chooses an option then everything will work just fine, and then they will see the offline indicator on the main page.

**Comment by rlinoz** [comment]
Hey @dannymcclain!

I want to understand if we really want to add the offline indicator here, since in phone screens this is actually a modal

<img width="434" alt="image" src="https://github.com/Expensify/App/assets/5201282/de451519-4684-457c-81ca-57647dd92327">


Just like our actions modal, which doesn't show an offline indicator

<img width="435" alt="image" src="https://github.com/Expensify/App/assets/5201282/201fdbc6-ed61-4e35-bb49-94c5ba2c60ab">

**Comment by dannymcclain** [comment]
> I want to understand if we really want to add the offline indicator here

I would say no. I agree with you that since this is a modal and not an actual screen/view, it probably should not include the offline indicator. cc @Expensify/design in case anyone disagrees.

**Comment by shawnborton** [comment]
Agree with you!

On a separate note.. is it just me or does the illustration here feel massive? cc @stitesExpensify 
![image](https://github.com/Expensify/App/assets/2319350/7879b541-8a92-4535-a4bb-08a5c82ac941)

**Comment by dannymcclain** [comment]
It does feel quite large.

**Comment by rlinoz** [comment]
I am going to close this one then, but should we do something about the image?

**Comment by shawnborton** [comment]
@stitesExpensify thoughts on following up and cleaning up the image styles?

**Comment by dubielzyk-expensify** [comment]
This was the original mock: 

![image](https://github.com/Expensify/App/assets/145416827/e3a08860-065a-41d7-a591-a10a584fe58d)


We changed the illustration to the animation, but to avoid cutoff it needs to be scaled up. Perhaps we can match it closer to the height of the original mock?

**Comment by shawnborton** [comment]
Yeah, I'm thinking we should ask Augenblick to get us a version of that animation where the hands are way longer so we can make a more wide illustration as opposed to something more square in proportion.

**Comment by shawnborton** [comment]
Though @dubielzyk-expensify before we get too crazy with this one... what's the relationship between this particular page and the Wave 9 work you are doing [here](https://expensify.slack.com/archives/C036QM0SLJK/p1706497192158389?thread_ts=1706054922.964519&cid=C036QM0SLJK)? Basically, will we get rid of this particular page once the Wave 9 stuff is in place?

**Comment by stitesExpensify** [comment]
AFAIK this will be replaced when wave9 comes out
