### ISSUE TITLE
Desktop - missing translation or 500 error in the console

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35133]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706136964852409

## Action Performed:

1. Send a message (I tested this in a channel, not sure if it's the same in a DM)
2. Click reply in thread to view that message in thread view
3. Have somebody else reply in thread while you're viewing it

## Expected Result:
No error should display and should be able to see the thread message
## Actual Result:
One of three things happens:

- No message appears and there's a 500 error in the console for AddComment
- A MISSING TRANSLATION error appears (see first screenshot) and there's a 500 error in the console
- The thread shows as having one reply (second screenshot). If you try to click into it, you a full-page error.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-01-24 at 2 29 26 PM](https://github.com/Expensify/App/assets/43996225/f079b90a-8bd0-4ea6-bee7-ffbf64102625)
![Screenshot 2024-01-24 at 2 32 45 PM](https://github.com/Expensify/App/assets/43996225/f353d787-825d-474d-b273-ef901e7d7385)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hmm, I'm not able to reproduce this. Taking to slack.

**Comment by puneetlath** [comment]
Doesn't seem to be occurring anymore. Reopen if it happens again please!
