### ISSUE TITLE
[$500] mWeb/Chrome-Login-FAB menu is not opened after closing the engagement modal for new account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35148]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Create new account
3. Copy the Magic link and change it to staging
4. Open a new tab and navigate to the staging magic link
5. Verify the abracadabra page is displayed
6. Navigate to the original tab
7. Close the engagement modal
## Expected Result:
FAB menu opened

## Actual Result:
FAB menu is not opened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/9fbcb82b-bcfb-44dd-8668-aed809ed4c26

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a647fcb2d1262265</li>
        <li>Upwork Job ID: 1750503353715163136</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by situchan** [comment]
This is intentional.
cc: @stitesExpensify

**Comment by stitesExpensify** [comment]
Yep that's correct. The FAB is no longer supposed to open automatically
