### ISSUE TITLE
[$500] Chat - Infinite spinner in Concierge chat after several openings

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
Precondition: User is logged in OldDot.
1. Open https://staging.expensify.com/
2. Click Concierge chat bubble (at bottom right)
3. Close NewDot tab
4. Repeat steps 2-3 several times (3-5)
## Expected Result:
NewDot tap opens with Concierge chat every time.

## Actual Result:
NewDot tab opens with infinity spinner in Concierge chat history.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/1cc94e76-4def-41b9-b1fb-a99029b18c83

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015fc2a83a3868ab3c</li>
        <li>Upwork Job ID: 1750501441003393024</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by abekkala** [comment]
to keep urgency and focus on higher priority wave work and fixed I'm going to close this. 
This also doesn't appear to be typical user behavior to keep repeating steps. If they want to chat they will and if not they'll close it once and move on.
