### ISSUE TITLE
[$500] Android-IOU-After submitting report also, "Submit" shown again for an sec in preview&header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35145]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Login as employee
3. Tap plus icon near compose
4. Tap request money--manual
5. Enter an amount and tap next
6. Enter merchant
7. Tap request
8. Tap on newly created request
9. Tap on header submit button and tap back button quickly to view preview
10. Note submit button shown again and quickly tap preview to open report page

## Expected Result:
As employee request money in WS, tap on preview and click submit button on header and quickly navigate back. Submit button must not be shown again.

## Actual Result:
As employee request money in WS, tap on preview and click submit button on header and quickly navigate back. Submit button again shown for an second in preview and on header.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/b623ddcd-e1e1-4063-b9c1-f3e10148f91b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0ccae8b57f79bd7</li>
        <li>Upwork Job ID: 1750500797338894336</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by rojiphil** [comment]
@kavimuru 
In your OP, you get multiple Report Previews (i.e. with amounts $0.43, $3008.23, $107.85, $565.39). 
Should we not get a consolidated Report Preview like shown below?
![Screenshot 2024-01-25 at 8 45 31 PM](https://github.com/Expensify/App/assets/3004659/c6e1983d-6f37-4d7f-b060-10fc1ab07f07)

**Comment by JmillsExpensify** [comment]
Hmm, yeah I'm also not seeing this one.
