### ISSUE TITLE
[$500] [HOLD for payment 2024-02-14] Pare back the parallax animation on empty chats

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#35172]
slack context: https://expensify.slack.com/archives/C03TME82F/p1706131195305379

### Problem

We've received feedback that, while cool, the parallax animation on the empty chat screens is a bit dizzying.

### Solution

Twofold solution:

1. Multiply [this x and y](https://github.com/Expensify/App/blob/ca83b5b270f4427c1ba539395aed16bfcc6c2f05/src/pages/home/report/AnimatedEmptyStateBackground.tsx#L35) by some number between 0 and 1 so that the animation is a bit more subtle. I suggest we start with 0.65, create an AdHoc build, then get feedback.
1. Let's also create a separate PR to turn this animation off entirely if `Reduced Motion` accessibility setting is enabled at the OS level.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01893cf40458362b92</li>
        <li>Upwork Job ID: 1755980203205128192</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
https://github.com/software-mansion/react-native-reanimated/blob/9c6a92d29c224e2c0e0b9834a709101b035302a5/docs/src/examples/UseReducedMotion.jsx

**Comment by roryabraham** [comment]
Put out a call for volunteers: https://expensify.slack.com/archives/C04878MDF34/p1706208017047929

**Comment by staszekscp** [comment]
Hey @roryabraham! I can do that in between of HybridApp builds 😄

**Comment by staszekscp** [comment]
The PR is already available - I've added the `Reduce Motion` logic, because I think it is tightly connected to the general idea of the whole issue. If you prefer to split them anyway, please let me know 😄

**Comment by roryabraham** [comment]
Marking this as a bug just to handle C+ payment to @situchan for his review of https://github.com/Expensify/App/pull/35232

**Comment by sakluger** [comment]
I added the external label to auto-generate the Upwork issue and sent @situchan an [offer](https://www.upwork.com/nx/wm/offer/100840548).

Wetting to weekly while we wait for the payment date.

**Comment by sakluger** [comment]
All paid, thanks!
