### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Task - The assignee ">" arrow is not grayed out when creating tasks offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a chat
2. Navigate to offline mode
3. Go to the assign task, enter the title, and complete the flow
4. Click on the task and hover over the assignee

## Expected Result:
The Assignee and arrow should be grayed out when creating tasks offline

## Actual Result:
The assignee ">" arrow is not grayed out when creating tasks offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f9d4d899-fd01-4d15-ab85-dd922436a9ba

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0e46b804f5e69b6</li>
        <li>Upwork Job ID: 1750639313882955776</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28124121</li>
<li>neonbhai | Contributor | 28124123</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by kevinksullivan** [comment]
@fedirjh can you please complete the checklist above?

**Comment by kevinksullivan** [comment]
Payments made, just waiting on checklist.
