### ISSUE TITLE
Distance - No error message when saving duplicate points

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35193]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34107
## Action Performed:
1. Create a distance request with three waypoints, A, B and C.
2. Navigate to request details page.
3. Click Distance.
4. Change the waypoint C to become waypoint B.
5. Click Save

## Expected Result:
App will throw the error "Please select unique waypoints"

## Actual Result:
No error message is seen when saving duplicate waypoints

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/23d7b0cb-a6ab-40e9-844c-5cede64bcd05

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1a743dc1fab2180</li>
        <li>Upwork Job ID: 1750658279340400640</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6. 
CC @greg-schroeder

**Comment by francoisl** [comment]
Production doesn't let you save the duplicate waypoints either, but at least shows an error message `Please select unique waypoints.`:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/2229301/9238620c-0964-4773-a3c3-1ffd02ac7ff7">

I think that's really the regression here that's not working on staging. That error message is correctly returned by the API to the `UpdateMoneyRequestDistance` request on staging too, e.g.:

```
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "80DA580D-B8AD-4E6E-B23D-7E25E9A8318A",
    "message": "Please select unique waypoints.",
    "title": "",
    "data": [],
    "htmlMessage": "",
    "onyxData": [],
    "requestID": "84b3ea47dbc6270a-SJC"
}
```

https://github.com/Expensify/App/assets/2229301/8a9f8a1f-e6b0-4800-9a25-ddef3f342620

**Comment by francoisl** [comment]
@aldo-expensify reverting https://github.com/Expensify/App/pull/34107 locally fixes the issue - any idea about a quick solution we could apply instead of reverting?

**Comment by francoisl** [comment]
Ok I think I see the issue, it's a backend fix so we'll keep it internal.

**Comment by francoisl** [comment]
A backend fix was merged, we're not going to CP it given that this is a fairly small issue in the end.

**Comment by francoisl** [comment]
This has been fixed and deployed for a while, forgot to close.
