### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Chat - When user goes offline, the download button do not disappear for other file types

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35200]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in and have sent an attachment that is not an image or PDF, such as .mp4 or .doc files
1. Go to the chat where you have sent the attachment (.mp4, .doc, etc.)
2. Go offline

## Expected Result:
The download button for other type of files should disappear, as it does for images and PDF

## Actual Result:
The download button does not disappear when the user goes offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/942a8722-dd74-4bfb-99b4-d3cc0f56b8c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2f068b75b4b0950</li>
        <li>Upwork Job ID: 1750641360532508672</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 28123937</li>
<li>Krishna2323 | Contributor | 28123938</li>
</ul></li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
Paid out, closing.
