### ISSUE TITLE
No option to request a physical card

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35221]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @miljakljajic 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706188966737069
## Action Performed:

1. Assign an Expensify card to an employee on a private domain
2. Log in to that employee’s Expensify account, navigate to Settings > Wallet
3. Click on their Expensify Card under Assigned Cards

## Expected Result:
 Virtual card should be assigned immediately, with the option to request a physical card

## Actual Result:
Virtual and physical card both appear as having been assigned. There is no option to request a physical card, but the physical card shows no actual card number and hasn’t been assigned to the employee in Marqueta

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/43996225/1e8eaf5a-f637-4ebe-b234-9da758f16cd5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
@rafecolton this could be related to the issues you've been running into.

**Comment by rafecolton** [comment]
Hm I'm not sure, I requested mine in OldDot not NewDot

**Comment by kadiealexander** [comment]
Closing as discussed [here](https://expensify.slack.com/archives/C027726KHT4/p1706648019827569?thread_ts=1706632767.408369&cid=C027726KHT4)!
