### ISSUE TITLE
[$500] Web - IOU- "Expense exceeds auto approval limit of" when when Max Expense Amount is disabled

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35237]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Employee creates manual request on collect workspace chat with big amount (82222)
2. Admin pay the IOU request
3. Admin navigates to IOU request details

## Expected Result:
There should be no error message about approval limit since Expense Violations are disabled on Old Dot

## Actual Result:
Error message "Expense exceeds auto approval limit of" appears on detailed IOU report page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3dd53a67-5df5-439e-932e-559d64e04ee2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c94fefacb329b7ff</li>
        <li>Upwork Job ID: 1750852495658668032</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by greg-schroeder** [comment]
i think this is more admin-centric, so potentially wave 8 @zanyrenney

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by miljakljajic** [comment]
@zanyrenney what do you think - does this fit into wave8?

**Comment by s77rt** [comment]
Not overdue. Still looking for proposals...

**Comment by miljakljajic** [comment]
I _think_ we haven't fully worked through violations yet and this is expected - going to close for now
