### ISSUE TITLE
[$500] mWeb - RHP - Close and back buttons unresponsive on touches on "Welcome to Expensify" modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35238]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: app should be fresh installed
1. Navigate on public room deeplink https://staging.new.expensify.com/r/3504895439653267
2. Tap on header
3. Tap on close or back button on 'Welcome to Expensify" modal

## Expected Result:
"Welcome to Expensify" modal should be dismissed

## Actual Result:
Nothing happens. The close and back buttons unresponsive on touches.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b415f0e0-e115-45ba-85ee-ceecefcafbd8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f068dd77dbc82b8</li>
        <li>Upwork Job ID: 1750853562175922176</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by strepanier03** [comment]
I don't have a physical iOS device and browserstack is bugging out right now. I'll circle back Monday.

**Comment by strepanier03** [comment]
Posted for help reproing this [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1706740490969749).

**Comment by twisterdotcom** [comment]
I cannot recreate this

**Comment by twisterdotcom** [comment]
I cannot recreate this on a real iOS device.


https://github.com/Expensify/App/assets/9133401/7bc7208e-27b5-4f9a-a5f7-ffdd2e43dc35

**Comment by twisterdotcom** [comment]
@dukenv0307 or @kbecciv is this still a real issue?

**Comment by twisterdotcom** [comment]
I still cannot recreate, even if I touch the header. @dukenv0307 if you can recreate on a real iOS device, please comment with a video and I'll reopen.
