### ISSUE TITLE
[$500] Expense - Concierge automatically final approves the report after employee submits the report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35248]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Employee are part of the Collect workspace.
- Schedule submit is enabled (Daily).
1. Go to workspace chat.
2. Create a distance request,
3. Go to expense report.
4. Click Submit.
5. Refresh the page.

## Expected Result:
There will be no approval message because admin does not approve the report.

## Actual Result:
After refreshing the page, there is a message saying that "Concierge final approved this report on behalf of admin".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e49ccf89-06be-443a-9153-3f18b3a75dba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165ea78fe475c7913</li>
        <li>Upwork Job ID: 1750883766895304704</li>
        <li>Last Price Increase: 2024-01-26</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by sakluger** [comment]
I supported into the submitter's account and saw that auto-approval is enabled in the Workspace, but there was a violation on the expense (potential duplicate) and the report was not actually auto-approved, it's still Processing.

So the bug is that we're telling the user in NewDot that their report has been final approved, even when we're not final approving it because of violations.

**Comment by sakluger** [comment]
I think this may have to do with the fact that we're not passing violation data to NewDot yet.

**Comment by sakluger** [comment]
I was looking at the wrong report, oops! The real report is this one:

![image](https://github.com/Expensify/App/assets/5997400/c8471e85-f2ae-43fa-97df-f263bf84a66f)

We did auto-approve that report, so there is no bug here!
