### ISSUE TITLE
Sign In - Sign In with google/apple web page not loaded when user click on google/apple icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35250]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user has Signed out
1. Open app
2. Click on google or apple icon

## Expected Result:
Sign In with google web page should be loaded

## Actual Result:
Expensify logo displayed infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/03e014e7-9724-4104-9e2e-9778c061b390

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Hm, I just tried it in Chrome staging and it worked for me. @kbecciv are you able to consistently reproduce this? And also, are you signed into our out of Expensify in the browser?

**Comment by francoisl** [comment]
Can't repro either on staging (`OpenApp` takes like 6 seconds but that's another story 😅). Going to remove the blocker label.
