### ISSUE TITLE
[$500] Desktop - Unread chat becomes unbolded in LHN without opening unread messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35254]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33779

## Action Performed:
Precondition;
- User A is on web.
- User B is on desktop app.
- User A and B windows are next to each other.
1. [User B Desktop] Open any report other than report with User A.
2. [User A web] Send a message to User B.
3 [User B Desktop] Without opening chat with User A, focus the window on the desktop app.

## Expected Result:
For User B, the chat with User A will remain bold because User B has not opened the chat with unread message.

## Actual Result:
The chat with User A is unbold as soon as User B focuses on the desktop app without even opening chat with User A.
On web, the issue is reproducible when the other user switches between tab without even opening the chat with new message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/de975da0-5047-4b84-8ae3-b6685a802fd6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108273261b6247483</li>
        <li>Upwork Job ID: 1750907915767681024</li>
        <li>Last Price Increase: 2024-01-26</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Contributor | 28127559</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by mountiny** [comment]
Making this external none of the PRs in checklist stand out to me. Anyone can find which pr caused this?

**Comment by mountiny** [comment]
I am out for couple hours

**Comment by bernhardoj** [comment]
It's caused by https://github.com/Expensify/App/pull/34537 where we read the newest action on visibility change. I think we should return early if the report screen on the stack isn't focused.

**Comment by arosiclair** [comment]
I also have this blocker which seems like it has the same root cause: https://github.com/Expensify/App/issues/35251

Do we know if the proposed solutions can fix both?

**Comment by abdulrahuman5196** [comment]
https://github.com/Expensify/App/issues/35251 and https://github.com/Expensify/App/issues/35254 are same issue. (We can combine into one issue if required). Since its under the regression period @FitseTLT Should fix this. Kindly assign me as C+ as well. 
On another topic @tienifr 's proposal here https://github.com/Expensify/App/issues/35254#issuecomment-1912292506 works fine.

**Comment by FitseTLT** [comment]
Raised [PR](https://github.com/Expensify/App/pull/35292) for these and linked to the original issue 👍

**Comment by mountiny** [comment]
Reverted the offending PR
