### ISSUE TITLE
[$500] Tag - Not all tag options are available when multil level tags are imported

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35264]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4238366
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace on Old Dot
- The Collect workspace has independent multilevel tags
1. Go to workspace chat
2. Start a manual request
3. On the confirmation page, click Show more

## Expected Result:
The confirmation page will display all tag levels 

## Actual Result:
The confirmation page does not display all tag levels, as only the top level is showing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/433f05b0-c482-4513-a47a-3c892ea50d9a

![default-file-icon (10)](https://github.com/Expensify/App/assets/78819774/b4ca3fbc-616d-4261-b728-47ec0c41ff6c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103bbd6082550c504</li>
        <li>Upwork Job ID: 1750960267014512640</li>
        <li>Last Price Increase: 2024-01-26</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave. 
CC @greg-schroeder

**Comment by greg-schroeder** [comment]
Agreed

**Comment by roryabraham** [comment]
Expected and actual results are the same here?

**Comment by greg-schroeder** [comment]
@roryabraham I think that was a typo, I edited it. The video shows that the "region" tag level is missing

**Comment by amyevans** [comment]
We've only implemented single-level so far, multi-level support is coming in https://github.com/Expensify/App/issues/33983. I'm going to close this, feel free to reopen if I'm missing something though!

**Comment by greg-schroeder** [comment]
Oh, fair enough lol. I probably should have known that

thanks @amyevans
