### ISSUE TITLE
[HOLD] Merchant required is missing translation

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35275]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jmills
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706197140618429

## Action Performed:

1. Choose Request money
2. Enter any amount
3. Choose any workspace
4. Try to request without entering a merchant

## Expected Result: 
No missing translation is shown
## Actual Result: 
Missing translation shown

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2024-01-25 at 09 38 09](https://github.com/Expensify/App/assets/43996225/602b0c75-e303-4ada-bd70-51152cbe8037)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
I can repro with my @expensify.com email. If surfacing `Missing Translation` is the issue, I think it's being worked on [here](https://github.com/Expensify/App/pull/30073). We could probably put this on hold until that PR gets deployed @JmillsExpensify - thoughts?

**Comment by jliexpensify** [comment]
`Missing Translation` PR looks to be merged soon

**Comment by jliexpensify** [comment]
`Missing Translation` PR has been deployed to production and this issue looks to be solved!

![Screenshot_20240214-140843](https://github.com/Expensify/App/assets/30815269/c9ebc7cb-18b4-427f-a62c-95372520fc4f)
