### ISSUE TITLE
No RBR violations appeared on my Request until there was a comment on the Request.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35276]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zsgreenwald 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706199771714359

## Action Performed:

1. From the NewDot Text Workspace, I selected Request Money > Scan
2. Once the Request completed scanning, I submitted the Request manually with no Category or Tag

## Expected Result:
There should be a RBR violation for no category and Tag set.

## Actual Result:
There was no RBR for a few days, until approver commented on the request

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/9fec16b8-c8d0-4425-9495-f71f57c2f60c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
Checking if this should be External on the Slack thread.

**Comment by lschurr** [comment]
Any movement on this one @cead22? Do you need BZ assigned?

**Comment by cead22** [comment]
Thanks for the bump, I've been catching up all day.

> There was no RBR for a few days

We decided on [this thread](https://expensify.slack.com/archives/C02MW39LT9N/p1706732520921959?thread_ts=1706728695.835139&cid=C02MW39LT9N) that we won't show violations while receipts are scanning, which sounds like it was the case here
