### ISSUE TITLE
[New Lib] react-native-keyboard-controller

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#35270]
coming from [this PR](https://github.com/Expensify/App/pull/16356) which Margelo recently dusted off, I wanted to get feedback on the introduction of this new lib

# Name of library: react-native-keyboard-controller

## Details
- Link to package:
    - npm: https://www.npmjs.com/package/react-native-keyboard-controller
    - github: https://github.com/kirillzyusko/react-native-keyboard-controller
    - docs: https://kirillzyusko.github.io/react-native-keyboard-controller/
- Problem solved by using this package

Issue: https://github.com/Expensify/App/issues/10632

High level problem description:

React Native's Keyboard APIs are inherently kind of buggy because they depend on asynchronous communication between JS and native. We currently use a mix of native keyboard avoidance and JS keyboard avoidance, which is pretty confusing, but also limiting in our ability to create consistent and interactive keyboard experiences.

We originally set out to use Reanimated's `useAnimatedKeyboard` hook to solve the problem outlined in the issue, and I [asked the contributor](https://expensify.slack.com/archives/C035J5C9FAP/p1706301396405929?thread_ts=1706286537.716439&cid=C035J5C9FAP) why they decided to use this library instead, to which they replied:

> with REA hook I'm getting invalid frames sometimes (especially when we need to deal with modals and instant keyboard transitions).
So, when keyboard should appear I was getting frames like 0 -> 291 -> 0 -> 336, while valid sequence had to be 0 -> 291 -> 336.
Also react-native-keyboard-controller supports interactive keyboard dismissal (which can be handy in Expensify app and overall used extensively in many chat-like apps) and already has prebuilt components (such as KeyboardAvoidingView)

I think the most important one here is that it already has prebuilt components specifically for handling keyboard interactions. We've talked to the people at Reanimated about building a KeyboardAvoidingView, and they're open to the idea but it's taken a long time.

- Number of stars in GH: 1.1k
- Number of monthly downloads: 24k
- Number of releases in the last year: 32
- Level of activity in the repo: low (only 12 open issues and 5 open PRs) 
- Alternatives:

There's a lot:
    - Reanimated (which we already use)
    - Keyboard API built into React Native
    - native iOS and Android keyboard APIs (which are internally leveraged by all these solutions)
    - all these other ones: https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/components/keyboard-aware-scroll-view#comparison
    
- Are security concerns brought up and addressed in the library's repo?

    Not really, as far as I can tell. But this doesn't really seem like a very risky lib.

- How many dependencies does this lib use that will be brought into our code?

    0 – we've already got all the peerDependencies: https://github.com/kirillzyusko/react-native-keyboard-controller/blob/6d3a9d0c43285777fc25f5e0b86760881a5c0fb5/package.json#L91-L95

- What will the effect be on the bundle size of our code?

    +60kb

**Comment by roryabraham** [comment]
I think maybe someone else is supposed to review this

**Comment by roryabraham** [comment]
I think that the PR itself has a good amount of polish still needed, so this isn't super critical to decide. Mostly I wanted more feedback on whether we're cool with using a new library for keyboard context or if we'd rather invest in improving Reanimated. Not entirely sure if this problem really belongs in the Reanimated space or not, tbh

**Comment by roryabraham** [comment]
I'd encourage a look at the docs before passing judgement, as it does seem like this might be the best keyboard library in the React Native space today

**Comment by kirillzyusko** [comment]
> Looks like 565kb unpacked

Small correction - the impact on JS bundle will be ~60kb.

Below you can see a detailed breakdown of size for each folder. `react-native` projects will consume code only from `src` folder, and `lib` (transformed code from `src`) folder will be ignored.

<img width="788" alt="image" src="https://github.com/Expensify/App/assets/22820318/a6bfa808-2be9-4159-bedc-5c2f7b2414d0">

**Comment by Beamanator** [comment]
> We've talked to the people at Reanimated about building a KeyboardAvoidingView, and they're open to the idea but it's taken a long time.

@roryabraham Quick question, what do you mean here? It's "in progress" but taking too long? Or just the discussion is taking a while?

**Comment by Beamanator** [comment]
> Who maintains the library and how well is it maintained?

I don't quite see `Who maintains the library` answered in the OP, is it just Kirill Zyusko?

**Comment by roryabraham** [comment]
> @roryabraham Quick question, what do you mean here? It's "in progress" but taking too long? Or just the discussion is taking a while?

Just taken a really long time / still not done.

> I don't quite see Who maintains the library answered in the OP, is it just Kirill Zyusko?

Yes, I think @kirillzyusko, who works for Margelo. So has support of Margelo team presumably (maybe would make Expensify team feel better if this repo is transferred to Margelo org, but I don't think that should be a requirement).

**Comment by roryabraham** [comment]
> So maybe you can just clarify the status / progress of "building it ourselves" and then we'll be ready to start this discussion in slack?

There's really no plans to "build it ourselves". There was some discussion with Reanimated maintainers about building it in Reanimated, but I haven't seen any movement on that front in a long time. This library feels like a better bet to me in that it's focused specifically on handling keyboards as best as possible in React Native. It's also maintained by someone we have a close partnership with, and is compatible with Reanimated.

@kirillzyusko can you confirm if this library is New Arch compatible?

**Comment by roryabraham** [comment]
Just had another [scenario](https://github.com/Expensify/Expensify/issues/358172#issuecomment-1925018255) crop up that is making this library look better and better.

**Comment by roryabraham** [comment]
I don't see any reference to web support in the docs, which I think would probably be a requirement for us.

**Comment by kirillzyusko** [comment]
@roryabraham this library is simply mocked on web right now (i. e. app will not crash as soon as you added a library, and all hooks will return default values).

I created a discussion a long time ago - https://github.com/kirillzyusko/react-native-keyboard-controller/discussions/43 but it got too little attention so I didn't prioritize it.

As far as I know browsers on mobile devices automatically avoid keyboard on browser level, and on desktop there is no sense to avoid keyboard because users are using physical keyboard. Is my understanding correct? Or Expensify has a code that handles keyboard appearance on web in specific manner? 👀

**Comment by hannojg** [comment]
Would be interesting to also explore web implementation for expensify in the future!

We are recommending all our clients RNKC for keyboard handling (depends on the use case ofc, but we didn't had any use case yet that the library can't cover), and I think its a good fit for the expensify app as well.
The library is becoming the standard for keyboard handling in react native imo.

**Comment by Beamanator** [comment]
I def like the plans to start using this lib! I just started the discussion in slack here (https://expensify.slack.com/archives/C01GTK53T8Q/p1707467001447909) so please feel free to add input / follow along! 👍

**Comment by Beamanator** [comment]
still discussing in slack

**Comment by Beamanator** [comment]
Seems we got consensus here in slack! Let's move forward with this lib 👍

**Comment by roryabraham** [comment]
moving forward in https://github.com/Expensify/App/issues/37203
