### ISSUE TITLE
[HOLD for #31411 - $500] Can't edit distance request right after creating it

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35280]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aldo-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706234965300829

## Action Performed:
1. Create free workspace
2. Create distance request in expense chat
3. Click the report preview to go to the expense report's chat
4. Click the transaction preview to get to the transaction's chat
5. Click the field `Distance` to edit it
6. Try to change the first waypoint
## Expected Result:
Able to edit the waypoint
## Actual Result:
Modal with `Hmm... it's not here` error shows up
## Workaround:

Refresh the page so the report data reloads before trying to edit the distance request fields.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/7702a68c-2eb8-4a7a-860f-78c140e7bb2b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01018916e036504443</li>
        <li>Upwork Job ID: 1751147227689152512</li>
        <li>Last Price Increase: 2024-01-27</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
This should be fixed after https://github.com/Expensify/App/issues/31411, where we will send the transactionThreadReportID in the money-related API requests.

**Comment by s77rt** [comment]
@peterdbarkerUK Let's hold on https://github.com/Expensify/App/issues/31411

**Comment by peterdbarkerUK** [comment]
On hold for #31411

**Comment by s77rt** [comment]
Still on hold

**Comment by s77rt** [comment]
Same ^

**Comment by s77rt** [comment]
Still on hold

**Comment by strepanier03** [comment]
Still on hold.

**Comment by s77rt** [comment]
Same ^

**Comment by strepanier03** [comment]
Hold GH is still open.

**Comment by s77rt** [comment]
https://github.com/Expensify/App/issues/31411 is resolved. Just tested and the issue seems fixed. This can be closed.

**Comment by s77rt** [comment]
@strepanier03 We can close this one

**Comment by strepanier03** [comment]
Got it, thanks @s77rt - closing now.
