### ISSUE TITLE
[Awaiting payment][$500] HIGH: Add possibility to leave from the workspaces

### ISSUE THREAD

**Issue by waterim** [Expensify/App#35286]
## Problem:
Right now there are no possibilities to leave from the workspace chats or from the workspace itself. The only possible solution its to be removed fully from the workspace. But there should be a possibility for members to remove themself(leave) from the workspaces.

## Solution:
As discussed [in the main issue](https://github.com/Expensify/App/issues/33575#issuecomment-1911267382), we would like to add this possibility to leave workspaces.

1. For all members except `[Admin, Creator]` we need to add a **Leave** button from the workspace chats in the similar way as we are doing Invite/Remove
2. Also all members(also creators) should be able to leave from workspace rooms except: `[#admin, #announce]` rooms.
3. Please follow the rules mentioned in this [issue](https://github.com/Expensify/App/issues/33575#issue-2055910794)

### Additional details for workspace chat:
1. Each member is added automatically to their own workspace chat, which means members cannot be removed from their own worksapce chats
2. Each admin is added automatically to all workspace chats, which means that admins cannot be removed from any workspace chat
3. Anybody else can be freely added to a workspace chat via invite or mention, meaning they can also be freely removed either by themselves, or by admins
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed8483924412de03</li>
        <li>Upwork Job ID: 1777598308702314496</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by waterim** [comment]
I think for this issue we need someone from a design team to find a perfect place for a "Leave" button.
cc: @quinthar

**Comment by quinthar** [comment]
@waterim is this something you could take on?

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
[Discussing in Slack](https://expensify.slack.com/archives/C0671JDRKQW/p1706778944433169?thread_ts=1703547187.140519&cid=C0671JDRKQW).

**Comment by rezkiy37** [comment]
Continuing the discussing in Slack. Waiting on clarification about API (_commands, endpoints and params_).

**Comment by rezkiy37** [comment]
Integrated functionalities for leaving a workspace and a workspace expense chat. Currently, the backend is not ready to handle requests correctly, coming soon. Preparing the PR for review.

https://github.com/Expensify/App/assets/57314631/dbc5c49d-b8cb-4457-b263-0b0654cd29b9

https://github.com/Expensify/App/assets/57314631/ded1b9e0-5640-48b4-9ce4-bb601fe7bed0

**Comment by rezkiy37** [comment]
[The PR](https://github.com/Expensify/App/pull/35671) is being reviewed internally. Logic works on the front-end side. Waiting for the backend to test fully.

**Comment by quinthar** [comment]
What's the next step; who is this blocked on?

**Comment by rezkiy37** [comment]
As we [agreed](https://expensify.slack.com/archives/C0671JDRKQW/p1707350218014859?thread_ts=1703547187.140519&cid=C0671JDRKQW) to wait the backend to test in a pair.

**Comment by quinthar** [comment]
Ok, reassigning to wave8 as it's part of the new workspace page.

**Comment by JmillsExpensify** [comment]
Added to release 1.

**Comment by MonilBhavsar** [comment]
I'll circle back to this

**Comment by MonilBhavsar** [comment]
Same ^. Focussed on wave issue.

**Comment by MonilBhavsar** [comment]
Working on this now

**Comment by MonilBhavsar** [comment]
@rezkiy37 do we have an App PR that can be used to test the backend changes?

**Comment by rezkiy37** [comment]
Yes, this [PR](https://github.com/Expensify/App/pull/35671). Let me sync it up with the `main`.

**Comment by MonilBhavsar** [comment]
Thanks for resolving conflicts!
I am working on PR's. We would need 2. Would try to get them in review before I logout

**Comment by rezkiy37** [comment]
Hey!
I must inform you that I have a vacation next week. I will be back on Monday 25.03. During the vacation, someone from Callstack can take the issue to work. See you soon!

**Comment by MonilBhavsar** [comment]
I have got PR's up!

--- 

@rezkiy37 Enjoy your time off!

**Comment by MonilBhavsar** [comment]
Automated tests on one of my PR are failing because in oldDot, only admins have an option to leave the workspace.
Instead of adding an exception to code, and follow our 1:1:1 ideology, I am going to split up the command, have a new command to leave workspace

**Comment by MonilBhavsar** [comment]
Both backend PR's are merged. A deploy later today will make LeavePolicy command live on staging. cc @rezkiy37

**Comment by MonilBhavsar** [comment]
@rezkiy37 the new API command - `LeavePolicy` is now on staging API!

**Comment by rezkiy37** [comment]
Actively working on the PR - https://github.com/Expensify/App/pull/35671.

**Comment by rezkiy37** [comment]
I've integrated the new `leavePolicy` function - 80caecd. I used pretty much the same flow that the app has for the [removeMembers](https://github.com/Expensify/App/blob/f5512a9dfbd60fa558ebdbe55a8981f0f93967fe/src/libs/actions/Policy.ts#L821) function.

https://github.com/Expensify/App/assets/57314631/e2958ad2-abe9-4a0d-b245-4b13acecb9e0

**Comment by rezkiy37** [comment]
> Looks good! Is the PR ready for review now?

Going to prepare all checklists and open for review today.

**Comment by MonilBhavsar** [comment]
Thank you!

**Comment by rezkiy37** [comment]
@MonilBhavsar, just opened https://github.com/Expensify/App/pull/35671 for review.

**Comment by MonilBhavsar** [comment]
assigning @rayane-djouah as a C+

**Comment by MonilBhavsar** [comment]
Thanks for thorough testing on the PR. I vote for the request 👍

**Comment by mallenexpensify** [comment]
>"HIGH" priority issues are 500$ cc @mallenexpensify tagging you as per [this](https://expensify.slack.com/archives/C02NK2DQWUX/p1712255061795399?thread_ts=1712250884.549319&cid=C02NK2DQWUX)

Thanks @rayane-djouah , I think this _might_ have been because the `Bug` label wasn't applied.  I've manually updated the job to $500.  Please keep tagging me if you see any issues that aren't auto-updating.

**Comment by MitchExpensify** [comment]
Can do

**Comment by MitchExpensify** [comment]
@rayane-djouah offer sent for payment here: https://www.upwork.com/nx/wm/offer/101965429

**Comment by MitchExpensify** [comment]
*Payment summary*

- $500 C+ @rayane-djouah 

Paid and contract ended in Upwork
