### ISSUE TITLE
[$500] Manually entered fields replace by smart scan

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35299]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706287604236959

## Action Performed:
1. Request money
2. Scan a valid receipt
3. Request from a workspace
4. Open the new request and navigate down to the transaction report
5. Edit the amount manually and save
6. Wait for the smart scan details to fill
Note: There may be a slight race condition here. It seems likely that the manually entered amount updated in the UI optimistically, but had not been processed by the server before the smart scan details were saved. We need to ensure that manually entered fields with optimistic values are not replaced.

## Expected Result: 
Smart scan fills in all fields that were not manually entered

## Actual Result: 
Smart scan fills in all fields, replacing the amount I manually entered## Expected Result:
Describe what you think should've happened

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-01-29 at 2 01 51 AM](https://github.com/Expensify/App/assets/38435837/a2d3fc82-85e3-40e7-a51f-89b401dff8e7)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3d084ff93c11990</li>
        <li>Upwork Job ID: 1752553739315617792</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @roryabraham</details>

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by rezkiy37** [comment]
I've investigated the bug. Looks like the backend does not overwrite manually entered fields. Actually, a behaviour seems like the backend stops to smart scan a receipt, once an user sends an update of a current report. So, I tested a case when the same receipt I allowed to smart scan fully, another case is to modify a field like amount, merchant and date. For the second case, if I modify a field during smart scanning, the backend returns a status "OPEN", not a "SCANNING" one.
Can we confirm that the current behaviour is correct?  

https://github.com/Expensify/App/assets/57314631/b776ebfd-a4f9-42c6-8f69-a72e786ff535

<details><summary>Auto scanned</summary>
<p>

<img width="1728" alt="Auto scanned" src="https://github.com/Expensify/App/assets/57314631/6040e862-091f-4424-b26b-5c904cf1f311">

</p>
</details> 

<details><summary>Edited during scanning</summary>
<p>

<img width="1728" alt="Edited during scanning" src="https://github.com/Expensify/App/assets/57314631/836b751b-c171-4229-a3a1-76c03cc2a89a">

<img width="426" alt="Request a scan" src="https://github.com/Expensify/App/assets/57314631/649214e1-0672-47a4-b771-3dbc811bea12">

<img width="737" alt="Edit a scan" src="https://github.com/Expensify/App/assets/57314631/896232d6-11ad-47aa-89eb-a18b3dc5407f">

</p>
</details>

**Comment by rezkiy37** [comment]
Still waiting on some feedback about a comment above.

**Comment by kadiealexander** [comment]
@cubuspl42 bump!!

**Comment by cubuspl42** [comment]
🎀 👀 🎀

**Comment by cubuspl42** [comment]
@roryabraham

First, would you please assign @rezkiy37 from Callstack to this issue, per [this message](https://github.com/Expensify/App/issues/35299#issuecomment-1934285935)?

Second, @rezkiy37 asked some backend-related questions, and I don't know the answer nor have the backend access. Would you help confirm the expected behavior?

**Comment by roryabraham** [comment]
> I've investigated the bug. Looks like the backend does not overwrite manually entered fields. Actually, a behaviour seems like the backend stops to smart scan a receipt, once an user sends an update of a current report. So, I tested a case when the same receipt I allowed to smart scan fully, another case is to modify a field like amount, merchant and date. For the second case, if I modify a field during smart scanning, the backend returns a status "OPEN", not a "SCANNING" one.
Can we confirm that the current behaviour is correct?

I'm actually not sure about this one. Asked in slack [here](https://expensify.slack.com/archives/C03U7DCU4/p1708068400638889)

**Comment by roryabraham** [comment]
This is expected behavior
