### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] Approving a report causes the workspace chat to “flash” in the LHN before disappearing

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35309]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706304456007449

## Action Performed:
Make sure user A (submitter) and user B (approver) on a workspace with scheduled submit (e.g. delayed submission)
Have user A create a request via Request money
Have user A submit the report
As user B, user A’s workspace chat will show unread in the LHN
As user B, tap into user A’s report, approve it
## Expected Result: 
The workspace chat will flash unread, with GBR in the LHN, before disappearing shortly thereafter.
## Actual Result: 
The workspace chat shouldn’t flash unread in the LHN, with GBR applied

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/05f89d40-6d3a-4ad7-8896-79c366c3d6f9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175776c123c4a6522</li>
        <li>Upwork Job ID: 1751945579555020800</li>
        <li>Last Price Increase: 2024-01-29</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28142958</li>
<li>tienifr | Contributor | 28142959</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by situchan** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/35309#issuecomment-1914623922) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by iwiznia** [comment]
Proposal looks good

**Comment by situchan** [comment]
PR is in review

**Comment by muttmuure** [comment]
@situchan @tienifr can you recommend a regression test

**Comment by muttmuure** [comment]
Both are paid up

**Comment by situchan** [comment]
### Regression Test Proposal

Prerequisites: Make sure user A (submitter) and user B (approver) on a workspace with scheduled submit (e.g. delayed submission)
1. Have user A create a request via Request money
2. Have user A submit the report
3. As user B, user A’s workspace chat will show unread in the LHN
4. As user B, tap into user A’s report, approve it
5. Verify that the green dot disappears immediately if there's no more IOU to approve/pay and that row doesn't flash in LHN

**Comment by muttmuure** [comment]
Done
