### ISSUE TITLE
Having multiple receipts Smartscanning results in Missing Translation error.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35312]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706406056867269

## Action Performed:
1. create a report by smartscanning
2. While it is being smartscanned for a day, smartscan another receipt

## Expected Result:
Both receipts should be smartscanning without any issue

## Actual Result:
The one from yesterday showed the error then disappeared completely. The newest receipt now shows this error. 
Update: Both receipts have now completely disappeared from New.Dot.
I also noticed my receipt on the 26th had also disappeared - my assumption was that it followed the same pattern: it was in the process of being SmartScanned.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot_20240128-123755](https://github.com/Expensify/App/assets/38435837/e770583d-9cdd-4a52-b479-93f7f9d478db)

![Screenshot_20240128-122958](https://github.com/Expensify/App/assets/38435837/66835adc-8fd8-4165-a289-ff7ec0b9dedf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a93a3f4386e16a9</li>
        <li>Upwork Job ID: 1762131645763043328</li>
        <li>Last Price Increase: 2024-02-26</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Putting on hold pending the main 'missing translation' GH getting finished. 
- https://github.com/Expensify/App/issues/29712

**Comment by mallenexpensify** [comment]
Still on hold

**Comment by mallenexpensify** [comment]
Off hold, added `retest-weekly`

**Comment by jliexpensify** [comment]
Sure thing, I am certain this will be fixed though, as we seem to have resolved the `Missing Translation` error.

**Comment by jliexpensify** [comment]
Scanned 3 receipts at once into the testing workspace, all scanned fine!

![image](https://github.com/Expensify/App/assets/30815269/cdb51603-16c2-48ac-b6fd-1004f2c71386)

**Comment by jliexpensify** [comment]
@mallenexpensify you can close this!

**Comment by mallenexpensify** [comment]
Thanks!!! happy to see you weren't surfaced the 'missing translation' error.
