### ISSUE TITLE
Room - System message for room name change shows "renamed from #B to #B"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35323]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a room with name A
2. Go to room header
3. Go to Settings
4. Click Room name
5. Change to name B
6. Return to room chat

## Expected Result:
The system message says "You renamed this room from #nameA to #nameB

## Actual Result:
The system message says "You renamed this room from #nameB to #nameB"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9b072b6c-feab-419a-aaf8-d2d1dea49185

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp. 
CC @quinthar

**Comment by s-alves10** [comment]
This isn't reproducible on the latest main

**Comment by lanitochka17** [comment]
Issue is not reproducible on Production 

https://github.com/Expensify/App/assets/78819774/2ab2abd6-00a0-4f94-b813-729813568caf

**Comment by s-alves10** [comment]
This issue is related to the backend. This happens when we use staging backend

**Comment by francoisl** [comment]
Can confirm this is a backend issue, working on a fix.

**Comment by francoisl** [comment]
Anyway, not a deploy blocker for NewDot.

**Comment by hayata-suenaga** [comment]
@s-alves10 does this only happen on staging backend and not production backend?

**Comment by hayata-suenaga** [comment]
PR to fix the backend was merged

**Comment by francoisl** [comment]
Backend fix is deployed to production already.
