### ISSUE TITLE
[HOLD for payment 2024-02-07] [HOLD for payment 2024-02-07] Send Money - Send option doesn't work, can't choose a receiver, an error in the console

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Go to FAB button -> Send money -> Enter an amount -> Next
4. Choose any user

## Expected Result:
The user is selected and you can continue the process

## Actual Result:
Can't choose any user for sending money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/25793aca-d244-4560-9e97-5fa4567ef6fa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by paultsimura** [comment]
This is a regression from https://github.com/Expensify/App/pull/34947
The `ROUTES.MONEY_REQUEST_CONFIRMATION` no longer exists:
https://github.com/Expensify/App/blob/b9ad4c223b80a6e6aa7147d0ced3dd0f2006c617/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L92

**Comment by francoisl** [comment]
Huh yeah weird.

I still see at least 13 occurrences of `ROUTES.MONEY_REQUEST_CONFIRMATION` on `main` at the moment. @DylanDylann @NikkiWines can you confirm if this is on purpose or an oversight?

**Comment by francoisl** [comment]
There might be a new route we can use instead, but we'd need to retest everything, so for now it might be quicker to revert #34947 - just submitted a PR.

**Comment by DylanDylann** [comment]
@francoisl I will raise a quick PR to fix it
