### ISSUE TITLE
HIGH: An emailed response to a group DM from NewDot sent multiple times

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#35332]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N 
**Email or phone of affected tester (no customers):** The message was sent from my Expensify account to [esthermhorowitz@gmail.com](mailto:esthermhorowitz@gmail.com) and [rikkihorowitz9631@gmail.com](mailto:rikkihorowitz9631@gmail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/363627
**Issue reported by:** @GabiHExpensify 
**Slack conversation:**

## Action Performed:
1. I wanted to test out sending a message from NewDot to multiple email addresses, so I sent a message to both of my sisters -- let's call them E and R for the sake of ease. They both have gmail accounts.
2. They both received the email. 
3. R tried replying but was unable to, because of known issue
4. E replied to both of us
5. I received the reply in NewDot. R received the reply in her email inbox. 
6. R then received the same message that E sent three more times overnight.
7. Secondarily, the "sender" is labeled Expensify Concierge, even though it was E who sent the email.

## Expected Result:
Steps 1-5 are good, but step 6 is a bug, and 7 seems like something we could improve.

## Actual Result:
She received 3-4 of the same email

## Workaround:
N/A

## Platform:
I sent the message from NewDot web (staging), I'm not sure if the same bug happens if the message is sent from NewApp.

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web
 
_Leaving the below blank 'cause I don't think it's relevant_
- **Version Number:** (For Cash and Mobile issues only)
- **Logs:** See how to search logs [here](https://stackoverflow.com/c/expensify/questions/4856)
- **Notes/Photos/Videos:** Any addi
<img width="1005" alt="Screenshot 2024-01-24 at 4 48 17 PM" src="https://github.com/Expensify/Expensify/assets/19719519/b87c8547-96fc-44ec-80db-957c36fbd33a">
tional supporting documentation
<img width="319" alt="Screenshot 2024-01-24 at 4 48 43 PM" src="https://github.com/Expensify/Expensify/assets/19719519/057f010b-4429-43ed-be55-8b2e4a3ab0e3">

- **Is this issue reproducible in staging, production or both?**

## Internal only, do not post to External repos

- **Customer affected:** The message was sent from my Expensify account to esthermhorowitz@gmail.com and rikkihorowitz9631@gmail.com
- **Admin email:** any relevant domain or policy admin emails
- **Concierge issue:** link to Concierge chat
- **Policy IDs:** all affected policy IDs
- **Report IDs:** all affected policy IDs

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd596e4c74e8a4da</li>
        <li>Upwork Job ID: 1752068917858910208</li>
        <li>Last Price Increase: 2024-01-29</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I think we're waiting on an internal review?

**Comment by quinthar** [comment]
I'm still a little fuzzy on this one.  Can someone try reproducing this one with me, dbarrett@expensify.com?

**Comment by Christinadobrzyn** [comment]
Good call @quinthar - I just created a group chat with you, c.dobrzyn+78@expensifail.com, and cdobrzyn@gmail.com to see if we can test what these emails look like. If you can reply to the NewDot chat and then we'll keep an eye out for emails from concierge of this chat to see if they duplicate. 

<img width="1353" alt="image" src="https://github.com/Expensify/App/assets/51066321/2f9224be-f9af-4380-b779-b71c6b83fcdd">

**Comment by Christinadobrzyn** [comment]
I haven't received this chat in email yet to either cdobrzyn@gmail.com or [c.dobrzyn+78@expensifail.com](mailto:c.dobrzyn+78@expensifail.com), so I'm not sure what I'm missing here... I tried this before and also didn't get the emails. At this moment, I can't reproduce this issue so I think maybe we should close it. 

@quinthar have you received any emails related to the ^ chat?

**Comment by Christinadobrzyn** [comment]
I think maybe we can close this until we can reproduce it? I still haven't received any emails from the NewDot chat thread so I'm thinking we can close this and come back to it when it can be reproduced.

**Comment by Christinadobrzyn** [comment]
I'm going to keep digging into this one but I agree to keep this closed as it can't be reproduced.

**Comment by Christinadobrzyn** [comment]
I think it's related to https://github.com/Expensify/Expensify/issues/365432 which is being worked on
