### ISSUE TITLE
[Report Fields] Update 'deletable' fields to show as "remove field " vs. "empty" 

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#35331]
The current funtionailty for Report Fields allows the user to set a value as "empty" to delete the field. We'll want to update the UI so it's more apparent to the end user. More contect in [this thread](https://expensify.slack.com/archives/C02MW39LT9N/p1706565750439989), 

If a report field exists within a report but has been removed from the policy, mark the report field as 'deletable' by showing "Remove field" in the overflow menu for each individual report field that becomes deletable. For Example: 

- If a field is called Department, then we’d show RBR next to the right caret for that field(just like shown in the details section in the below mock-up)
- Then when you tap on that row for the report field and we push-to-page, you see the red error message below the field input.

<img width="275" alt="Screenshot 2024-01-30 at 1 38 57 PM" src="https://github.com/Expensify/App/assets/13949826/00e2e697-f173-4312-ab12-560cbcf4a87a">

**Comment by allroundexperts** [comment]
@caitlinwhite1 Can I please get a UI screen of how this `x` would look like? Thanks!

**Comment by caitlinwhite1** [comment]
@allroundexperts Yup! Let me grab something from Figma

**Comment by caitlinwhite1** [comment]
@allroundexperts I updated with the context from that slack thread but let me know if you need any other info!

**Comment by allroundexperts** [comment]
Thanks @caitlinwhite1. I was waiting for my other PR related to backend integration to get merged first. It got in Yesterday so I should be making a PR for this soon!

**Comment by allroundexperts** [comment]
Update: Created a draft PR [here](https://github.com/Expensify/App/pull/36039). Waiting on @thienlnam to provide me with the API endpoint needed to delete the report field.

**Comment by allroundexperts** [comment]
Hi @thienlnam!
Did you get a chance to create the endpoint needed to delete the report field?

**Comment by thienlnam** [comment]
Yup, it's merged pending deploy - should be available on staging tomorrow. Here are those details

Endpoint: RemoveReportField
Parameters: 
- fieldID: field_id_21312

**Comment by allroundexperts** [comment]
Still getting the following:

<img width="605" alt="Screenshot 2024-02-19 at 5 53 22 AM" src="https://github.com/Expensify/App/assets/30054992/5de305ec-7b75-4150-98b6-6f538ce4ac5f">

How do I set the server as staging in the App? I no longer see that option in preferences.

**Comment by thienlnam** [comment]
Not sure, but it's on production now so you should be able to test there.

Also as a note - due to the way these are stored, you'll have to prefix the fieldID with expensify_

So same as the changes I made here https://github.com/Expensify/App/pull/36769

**Comment by JmillsExpensify** [comment]
@allroundexperts quick note that we are trying to wrap up the report fields initiative by the end of this month. Do you think it'll be possible to get this PR merged by then?

**Comment by allroundexperts** [comment]
@JmillsExpensify This is blocked on https://github.com/Expensify/App/issues/36170 which is waiting changes from the backend. I'm not sure how long it will take those changes to get in. This can not be completed until those are done.

**Comment by JmillsExpensify** [comment]
Nice, appreciate the color. I'm also going to go ahead and move this to our `Polish` section on a second read of the description. Ideally we can still get this merged before the end of the month!

**Comment by JmillsExpensify** [comment]
Circling back on this one, with the PR for #36170 now merged, are we good to pick this one back up?

**Comment by allroundexperts** [comment]
Yes. I'll try to resolve the conflicts today and make it ready for review.

**Comment by jjcoffee** [comment]
Hit [production](https://github.com/Expensify/App/pull/36039#issuecomment-2048094936) 2024-04-10, payment should be due tomorrow. cc @JmillsExpensify

**Comment by caitlinwhite1** [comment]
This deployed so i think we're all set to close!

https://github.com/Expensify/App/pull/36039#issuecomment-2048094936

**Comment by jjcoffee** [comment]
@caitlinwhite1 Please can you reopen as payment is due for the PR review? Thanks :pray:

**Comment by caitlinwhite1** [comment]
@dylanexpensify reopening and adding bug label for payrment!

**Comment by dylanexpensify** [comment]
Nice one!

Payment summary:
- Contributor+: @jjcoffee $500

[Please apply](https://www.upwork.com/jobs/~01b64e312ba728f649) or request!

**Comment by jjcoffee** [comment]
Thanks, applied @dylanexpensify!

**Comment by dylanexpensify** [comment]
Yes!

**Comment by dylanexpensify** [comment]
@jjcoffee sent offer! Also @allroundexperts updated original post btw!

**Comment by dylanexpensify** [comment]
Paid @jjcoffee!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
