### ISSUE TITLE
 Room - Room does not disappear from LHN after leaving the room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a room.
2. Go to the room.
3. Leave the room.
4. Click on the room in LHN.
5. Navigate to a different chat.

## Expected Result:
In Step 3, after leaving the room. room will disappear from LHN.

## Actual Result:
In Step 3, after leaving the room. room does not disappear from LHN.
It only disappears after navigating to a different chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ddc7bb7c-76fe-4e1e-9d79-7ec1ac5936e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by francoisl** [comment]
I can't repro on v1.4.33-2, but curious if you could double-check @yuwenmemon as well. Leaving a room should now take you to your last chat, based on https://github.com/Expensify/App/pull/31097.

https://github.com/Expensify/App/assets/2229301/d704f13a-e4ea-401e-a048-85f5eaead4a3

**Comment by yuwenmemon** [comment]
Yeah, seeing the same result when I test on staging. Closing this.
