### ISSUE TITLE
[$500] Web - Expense - Deleted expense on OD is still displayed on report on ND

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35340]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have created a collect workspace and have invited a member as employee.
1. As employee, create an expense on OD.
2. On the same report, create another expense.
3. As the admin on ND, verify the report and the expenses (there should be 2 expenses).
4. As the employee again on OD, delete the first expense you created.
5. As the admin on ND, verify the report again.

## Expected Result:
The expense deleted by the employee should not appear on the report on ND as the admin.

## Actual Result:
The expense deleted by the employee is still displayed on the report on ND as the admin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/16f9866c-55aa-448f-aa30-6ac1a5e38ee5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by greg-schroeder** [comment]
This should be handled here: https://github.com/Expensify/Expensify/issues/350244
