### ISSUE TITLE
[HOLD for payment 2024-02-07] [HOLD for payment 2024-02-07] [$500] Android - Wallet - App crashes on tapping enable wallet.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35344]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Wallet
4. Tap Enable Wallet

## Expected Result:
App must not crash on tapping enable wallet

## Actual Result:
App crashes on tapping enable wallet

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b41b112e-4839-4017-be33-2a547664470d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165d2a9876eb54d92</li>
        <li>Upwork Job ID: 1752165534277464064</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@lanitochka17 can you confirm that this only happens on Android?

**Comment by marcaaron** [comment]
Hmm seems like possibly some issue with Plaid. This is the crash:

https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/e9d92dfee0a1b8347102bfce26614cf7?time=last-seven-days&types=crash&versions=1.4.33-2%20(1001043302)&sessionEventKey=65B841D100750001772CBB1688FCE15D_1908126535333268522

**Comment by marcaaron** [comment]
Possibly related to https://github.com/plaid/react-native-plaid-link-sdk/issues/620

Going to try to bump the Plaid version and see if that helps.

**Comment by marcaaron** [comment]
It works locally for me with the bumped version. I have to roll out now though so if someone can raise the PR and test that would be great. This is what we need to update:

"react-native-plaid-link-sdk": "10.12.0"

**Comment by francoisl** [comment]
Works for me, though regarding this bit specifically:

> What alternative solutions did you explore? (Optional)
> If there's no reason to avoid 11.x Plaid lib version, we can also upgrade to v11.4.0

The potential risk of updating to a new major version would be that there could be breaking changes that we'd need to work out.
In the short/medium, yes we should absolutely update to 11.4, but for this blocker it might be safer to upgrade to 10.12. (Just my 2¢)

**Comment by marcaaron** [comment]
Agree with @francoisl

**Comment by marcaaron** [comment]
Sorry I thought someone would have fixed this by now. But since not I'll raise the PR myself.

**Comment by getusha** [comment]
cc @mountiny @Julesssss @shubham1206agra

**Comment by francoisl** [comment]
Assigning @mkhutornyi since they have a PR ready that we already tested - https://github.com/Expensify/App/pull/35440

**Comment by sakluger** [comment]
@getusha @mkhutornyi I sent offers to both of you via Upwork.

**Comment by getusha** [comment]
@sakluger not able to accept the offer

![Screenshot 2024-02-07 at 8 14 12 PM](https://github.com/Expensify/App/assets/75031127/2b732591-a2e2-4460-8339-fab285de5ccb)

**Comment by sakluger** [comment]
Weird, it says I withdrew the offer. Sorry about that, I sent you a new one @getusha.

**Comment by sakluger** [comment]
@getusha please let me know once you've accepted the offer, thanks 🙇

**Comment by getusha** [comment]
@sakluger accepted thank you! :)

**Comment by sakluger** [comment]
Thanks! All paid 🙇

**Comment by sakluger** [comment]
Sorry @mkhutornyi! I completed your payment now.
