### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] `0` member is formatted weirdly when leaving a room and revisiting room details

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35358]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @blimpich 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706559325923909

## Action Performed:

1. create a workspace
2. create a room with workspace visibility
3. open the details pane and copy the link in the url to your clipboard
4. leave the room
5. paste the link you copied into the URL

## Expected Result:
We should see the members menu item with a correctly formatted zero representing zero members
## Actual Result:
The zero is there but its formatted really strangely

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/decb658a-8ce3-4605-9eca-98b83e54b214

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018691b573ff8ea80e</li>
        <li>Upwork Job ID: 1752221236965654528</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28137708</li>
<li>shubham1206agra | Contributor | 28137709</li>
</ul></li>
    </ul>
</details>

**Comment by jyash97** [comment]
Hey 👋🏻

new to contributing to Expensify, is there any way I can take this issue?

**Comment by jyash97** [comment]
Contributor details
Your Expensify account email: jyash97@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015f3056aaa4d9252e

**Comment by CortneyOfstad** [comment]
> new to contributing to Expensify, is there any way I can take this issue?

@jyash97 welcome! We ask that you provide proposals for the issue, in a similar format to the one [here](https://github.com/Expensify/App/issues/35358#issuecomment-1916198362). Then the C+ will review to see which proposals will best fit the issue 👍

**Comment by CortneyOfstad** [comment]
@shubham1206agra any thoughts on the proposal [here](https://github.com/Expensify/App/issues/35358#issuecomment-1916198362)?

**Comment by shubham1206agra** [comment]
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/35358#issuecomment-1916198362) looks good.

🎀👀🎀 C+ reviewed

**Comment by hayata-suenaga** [comment]
I messed up assignment 😭 

hope it didn't break anything...

**Comment by CortneyOfstad** [comment]
@hayata-suenaga no worries! Everything looks to be okay, and regardless — doesn't take much to make a manual change on the Upwork side! All good!

So to confirm, @dukenv0307 has been hired as the contributor and @shubham1206agra has been hired as the C+? Just want to make sure I have that correct. Thanks!

**Comment by hayata-suenaga** [comment]
yes that's right! thank you!

**Comment by CortneyOfstad** [comment]
Payment is scheduled for next week! 🎉

**Comment by CortneyOfstad** [comment]
@shubham1206agra it looks like we're still waiting for you to accept the proposal in Upwork [here](https://www.upwork.com/jobs/~018691b573ff8ea80e) — can you let me know once you accept!

@dukenv0307 you have been paid via Upwork, so you are all set!

**Comment by CortneyOfstad** [comment]
Perfect! Payment has been made! Once you have completed the checklist @shubham1206agra — we can get this closed. Thank you!

**Comment by CortneyOfstad** [comment]
@shubham1206agra any chance you can have the checklist completed by EOD today?

**Comment by CortneyOfstad** [comment]
Perfect! Thanks so much!
