### ISSUE TITLE
[$500] Deleted request shown in LHN and paying the request resulted in the IOU not being paid, and becoming inaccessible

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35352]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevin
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706556725386659

## Action Performed:

1. User A  requested $1.00
2. User A immediately deleted the request

## Expected behavior:
IOU should be deleted/ and report should not show in our DM.

## Actual behavior:

- Report continued to show in our DM as normal, with the option to pay
- Once I paid it I no longer had access to it

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0b84daa9-f693-450c-a00c-09e6cb74a294

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0e7f1d8a3658b76</li>
        <li>Upwork Job ID: 1752148416513818624</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by rayanetech** [comment]
I would like to work on this

**Comment by rayanetech** [comment]
Contributor details
Your Expensify account email: yassviet10@gmail.com
Upwork Profile Link: https://www.upwork.com/agencies/1687560390880546816/

**Comment by adelekennedy** [comment]
no proposals yet - @allroundexperts do you think we need an internal engineer here, or, do we just need more time for proposals?

**Comment by allroundexperts** [comment]
This is tricky. I feel like there might be something wrong with the optimistic data handling here. Lets bump this in Slack before making it internal?

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue.

**Comment by waterim** [comment]
Im not sure this is an issue because it works as expected.

It can't work immediately because we need to wait for a pusher, it can take some time, sometimes faster sometimes slower.
But no errors I can see, it disappears just in a second, when we are getting data from pusher.

https://github.com/Expensify/App/assets/39777589/0ce1f775-7137-4937-a86e-33452bc85d04

Here is an example how it disappears(sometimes it can be even in 1 sec, sometimes in 5 sec, just depends on pusher latency):

https://github.com/Expensify/App/assets/39777589/69e87641-0064-4d51-bfa6-2a3395599108
