### ISSUE TITLE
[$500] Room-Receiver of room invite has enabled forced offline, but receiving room invite

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2.In mweb, in room chat, from invite members page, invite a user to room
3.Invited user must be already logged in using Android app and must have enabled forced offline
4.In mweb, after inviting member who is already logged in and enabled forced offline, can see a notification on top after invited to room
4.Tap on that notification
## Expected Result:
Receiver of room invite has enabled forced offline, so he must not receive room invitation message.

## Actual Result:
User directed to room page, header showing skeleton and below invited message delivered in offline.

Receiver of room invite has enabled forced offline, but yet he receives room invitation message.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/b0e56f84-2cdb-4f10-a2f2-0586a013d983

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e3f7bcb5ccba474</li>
        <li>Upwork Job ID: 1752279057071841281</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by situchan** [comment]
No proposals yet

**Comment by JmillsExpensify** [comment]
This is also a pretty esoteric bug. I think it's more an issue with our internal tools more than anything.

**Comment by situchan** [comment]
I am not sure this is bug. Should we prevent showing push notification if enabled offline in the app?

🎀 👀 🎀 to confirm with engineer

**Comment by NikkiWines** [comment]
Eeeh, yeah I guess technically it's ab ug but I agree with @JmillsExpensify - this is a pretty obscure bug to come across. I don't think it's really worth the investment to resolve. What do you think @JmillsExpensify?

**Comment by quinthar** [comment]
Ya, force offline is a weird dev features, so if it's a little janky, I don't think it matters.  Let's focus on customer-affecting bugs.  Closing.
