### ISSUE TITLE
[HOLD for payment 2024-02-07] [HOLD for payment 2024-02-07] [$500] Personal details - First item in the list is not highlighted when searching for country

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35374]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Profile > Personal details.
2. Go to Address.
3. Go to Country.
4. Search for any country.
## Expected Result:
The first item in the list is highlighted.

## Actual Result:
The first item in the list is not highlighted.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/d9bca3ec-0810-4f16-a652-9b85e0baaa30

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc6fb38951fd8aeb</li>
        <li>Upwork Job ID: 1752281579575689216</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by Pujan92** [comment]
Seems a regression from https://github.com/Expensify/App/pull/34485

**Comment by lakchote** [comment]
> Seems a regression from #34485

#34485 is indeed the culprit 👍

**Comment by lakchote** [comment]
> @AnshuAgarwal24 Won't that re-create the issue fixed in #34485 ?
> 
> I think this one should probably be dealt with by the PR authors given it's in the regression period. @neonbhai @eVoloshchak

That's my concern too.
I've tagged the PR authors on Slack and I'll revert the changes in the meantime.

**Comment by MitchExpensify** [comment]
> I think this one should probably be dealt with by the PR authors given it's in the regression period.
@neonbhai @eVoloshchak

Agree

**Comment by MitchExpensify** [comment]
No payment due here as this is a regression

**Comment by MitchExpensify** [comment]
Reminder set to pay!

**Comment by MitchExpensify** [comment]
Ah, nice. Thanks for clarifying

**Comment by MitchExpensify** [comment]
What about the [BZ steps](https://github.com/Expensify/App/issues/35374#issuecomment-1920108649) @Ollyws ?
