### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Cursor don't move to next line if return button tapped on keypad after back from referral

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35373]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Tap on FAB button >> Start Chat
2. Click on "Start a Chat, get $250" referral banner
3. Go back to start chat
4. Search or select any user
5. Tap on compose box
6. Enter any message
7. Tap on return button on keypad
## Expected Result:
After back from referral page, cursor in compose box should move to next line on tapping return button on keypad

## Actual Result:
Cursor do not move to next line in compose box on tapping return button on keypad after back from referral page

Note: Issue reproducible on web with SHIFT+Enter & console error shows up (Please check web video attachment)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/350883da-2b54-4b9d-bf82-daf0771cc03a

https://github.com/Expensify/App/assets/43996225/32839fb5-954a-499e-9951-3442919a097b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150278de70234c5a1</li>
        <li>Upwork Job ID: 1752280699709931520</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28130727</li>
<li>bernhardoj | Contributor | 28130728</li>
</ul></li>
    </ul>
</details>

**Comment by bondydaa** [comment]
👍 i don't think we need to wait to refactor to a functional component, fix the lingering event listener (and throw a comment in stating why we are doing it so when we do refactor it we don't re-introduce the bug).

**Comment by bernhardoj** [comment]
PR is ready

cc: @aimane-chnaif

**Comment by mallenexpensify** [comment]
Whoohooo... thanks for figuring out the repro steps, 🤞  it's fixed soon. It happened to me again today, I refreshed the page and it starting working again.

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR FEB. 26

- Issue reported by: Applause internal team
- Fix: @bernhardoj [$500 - if no regressions] [offer](https://www.upwork.com/nx/wm/offer/28130728) 
- PR Review: @aimane-chnaif [$500 - if no regressions] [offer](https://www.upwork.com/nx/wm/offer/28130727)

**Comment by abekkala** [comment]
@bernhardoj and @aimane-chnaif - payment sent and contracts ended, thank you! 🎉
