### ISSUE TITLE
[$500] IOU - Receipt from photo library not replaced with receipt taken from camera

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35376]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open app
2. Tap on FAB
3. Select Manual tab
4. Write any amount an tap on next button
5. Select any attendee
6. Tap on 3 dots button > Add receipt
7. Select Choose from gallery option
8. Select any photo from gallery
9. Tap on 3 dots button > Add receipt
10. Take camera photo
## Expected Result:
Receipt taken from photo library should be replaced with receipt taken from camera

## Actual Result:
The receipt from the photo library was not replaced with the receipt taken from the camera

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/31a31760-5044-4e01-9325-b17182a3eea3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b73cc4cdc457757</li>
        <li>Upwork Job ID: 1752283847162748928</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
Not reproducible on latest staging (v1.4.31-7), the receipt picture is updated currectly with the one captured by the camera.

**Comment by s77rt** [comment]
Not overdue. Still looking for proposals (if this is still reproducible)

**Comment by s77rt** [comment]
Same ^

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by kadiealexander** [comment]
Closing as not reproducible.
