### ISSUE TITLE
[HOLD for payment 2024-03-06] [$500] Copy to clipboard on the system message for paid expense copies negative amount

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35375]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211589
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in under your HT account - A
3. Send an IOU with any amount to Account B that you have access to
4. Log in under account B
5. Navigate to the conversation with account A
6. Open IOU Report Conversation
7. Turn off the internet
8. Pay for the IOU
9. Copy the system payment message "paid {currency} {amount} elsewhere"
10. Paste the copied message into the Compose Box
## Expected Result:
The system message must be copied without the "-" sign in front of the currency

## Actual Result:
Copy to clipboard on the system message for paid expense copies negative amount

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/0d87cd86-e881-471b-9985-a8dfd34575e0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170b576c255476ae4</li>
        <li>Upwork Job ID: 1752283071992983552</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 28145024</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copied "paid" report action contains a negative amount

### What is the root cause of that problem?
Since the Paid action means the user pays money, not receives it, the IOU amount is set with a negative value in the `originalMessage.IOUDetails`. And we do not negate this value when copying the message to clipboard.

### What changes do you think we should make in order to solve the problem?
When building the getIOUReportActionDisplayMessage, use `-amount` instead of `amount`:

```js
const formattedAmount = CurrencyUtils.convertToDisplayString(-amount, currency) ?? '';
```



### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment]
@grgia just waiting on you to confirm

**Comment by grgia** [comment]
@tienifr assigned!

**Comment by twisterdotcom** [comment]
Eugh, no Melvin comments either. 😭 Why do you make me do work Melvin.

**Comment by twisterdotcom** [comment]
Wow, I need to pay this. Sorry for the tardiness.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @tienifr paid $500 [here](https://www.upwork.com/nx/wm/workroom/36274054/overview).
- @parasharrajat paid $500 via newDot payments.

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
