### ISSUE TITLE
[CRITICAL] Backwards Compatibility -  "Unavailable workspace" is displayed in the IOU details header

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35381]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with a new account
3. Add this account as an employee in Group Policy in OldDot
4. Under the employee account in NewDot, navigate to the Group Policy chat room
5. Send a manual IOU to the conversation
6. Navigate to IOU Report Conversation
## Expected Result:
The WS name must be defined correctly in all menus and reports

## Actual Result:
When creating an IOU in a WS room by a newly invited employee in Group Policy, it displays "Unavailable workspace" in Report Conversation

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/4af373be-8932-42e9-9d66-819072c90ff5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146620fb0e6706fd3</li>
        <li>Upwork Job ID: 1752289695969165312</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
Waiting for proposal

**Comment by DylanDylann** [comment]
Still waiting for proposal

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
So, I've investigated the problem. Looks like the app does not have all details about a newly added workspace for some initial period. The app does not have such important properties like: `name` and `isPolicyExpenseChatEnabled`. I think that must be investigated from the backend side to handle this data gap and add/pass all important properties.

<img width="969" alt="Screenshot 2024-02-07 at 16 10 56" src="https://github.com/Expensify/App/assets/57314631/7d03b18c-7437-46a2-920c-98305dbdae6e">



https://github.com/Expensify/App/assets/57314631/ed4c7aa1-8717-4508-b996-ad5bb188d675

**Comment by miljakljajic** [comment]
I'll share this internally @rezkiy37 and get more eyes on your comments/thesis. Thank you for investigating! I think this relates to wave6 - I'll tag you in my comment

**Comment by greg-schroeder** [comment]
Actually maybe this could go in `Critical` as it's a cross-compatibility bug in the end

**Comment by rlinoz** [comment]
This got deployed to prod, I think we can close it.
