### ISSUE TITLE
Split - List does not scroll up after selecting a split participant

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Click FAB > Request money.
2. Enter amount > Next.
3. Scroll down and click Split next to user.
Note that the list does not scroll up.

## Expected Result:
The list will scroll up each time after selecting a split participant.

## Actual Result:
The list does not scroll up after selecting a split participant.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/11ea435e-d63a-4856-8219-d6cd27bda77c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by francoisl** [comment]
Confirmed it's working fine on v1.4.33-4, closing.
