### ISSUE TITLE
IOU - Other currency is highlighted instead of the first after clearing search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35396]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4251352
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM.
2. Click + > Request money.
3. Click Currency.
4. Enter search term that will return results (search "au).
5. Move the selection with keyboard to the middle.
6. Clear the search term.

## Expected Result:
The first currency in the list will be highlighted.

## Actual Result:
The selection is not with the first currency, but the selection still follows the last selection during search.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e29bfa7a-f109-405f-a521-ae6d10009129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
The bug is a little bit niche, so we might be able to remove the blocker label, but I am going to find the PR that caused it

**Comment by pecanoro** [comment]
Not exactly a duplicate but it's the same cause so I am going to close this one since we are reverting the PR to fix the other blocker.
