### ISSUE TITLE
[HOLD for #35290] [$500] Thread - Thread header shows skeleton when deleting parent message in thread in #admin room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35390]
## HOLD for https://github.com/Expensify/App/issues/35290. Re-test when that's fixed, and close if it can't be reproduced.

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to #admin room.
2. Send a message.
3. Right click on the message > Reply in thread.
4. Send a reply in thread.
5. Delete the parent message.

## Expected Result:
The header will show [Deleted message].

## Actual Result:
The header shows skeleton loading.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/86dbf10c-50a2-4f73-8b2c-e2a5b752f308

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01279e154156778a5a</li>
        <li>Upwork Job ID: 1752301953538433024</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment]
So speedy, you two. Ok I'll update the tags and set this on hold for https://github.com/Expensify/App/issues/35290. Then once that is fixed, I'll re-test this to confirm that all is good, then will close

**Comment by garrettmknight** [comment]
Closed the other as an edge case - doing the same here.
