### ISSUE TITLE
Tags - Numbers are not alphabetically ordered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35421]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4252172
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have created a collect workspace
1. As the admin on OD, add some tags named "Tag 1", "Tag 2", "Tag 3", "Tag 10"
2. On ND, go to workspace chat
3. Create a manual money request, enter the amount
4. Tap on "Show more"
5. Tap on the tag field

## Expected Result:
The tags should be ordered alphabetically, from 1 to 10

## Actual Result:
The tags are not correctly ordered, the number 10 follows the number 1

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6361136_1706635329507!IMG_E2714](https://github.com/Expensify/App/assets/78819774/d8d76d76-7676-4a8f-877a-0d5700a5b335)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
I'm seeing the same sorting logic on production

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/2229301/3e04184e-1487-4934-8182-e162c6576727">

and also on OldDot

<img width="933" alt="image" src="https://github.com/Expensify/App/assets/2229301/c03cc090-5722-48b9-9870-196cac5c44cf">


This is because we sort tags like plain strings (we don't take numbers into account), which is fine.
