### ISSUE TITLE
[$500] Create force touch quick actions for New Expensify

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35424]
([Internal issue](https://github.com/Expensify/Expensify/issues/362016)) Let's add the ability to access quick actions via force touching the New Expensify app icon. This will pull from the same format as we use for our Old App. Note: this will be considered polish/Release 5

![IMG_D14BEFD54799-1](https://github.com/Expensify/App/assets/22219519/bff8ed93-6680-4d5e-a7a2-2c544af4588d)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c7b106afbf26eaf</li>
        <li>Upwork Job ID: 1752395510725632000</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Actually, gonna close this one since it'll be internal work given Hybrid App.

**Comment by Jonathan09876** [comment]
Hello iuacmartins!
I think it's possible to add  your requirement.
I have solve the same problem at the past in my company.
That is the video chatting app based on Flutter.
I can provide you my experience in this project.
But at first I want to check your project then decide. thatks.
