### ISSUE TITLE
Room - %baseURL room link in room leaving message in #admin room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35475]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34694
## Action Performed:
1. [User A] Create a private room and invite User B
2. [User B] Leave the room
3. [User A] Go to #admin room of the private workspace
4. [User A] Click on the room link in room leaving message

## Expected Result:
In Step 3, no console error will show up
In Step 4, the room link in the room leaving message is a valid link

## Actual Result:
In Step 3, console errors show up
In Step 4, the room link in the room leaving message is an valid link with %baseURL in it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4c16341b-3be5-4d91-98bf-d193e190dc48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
This is backend bug, no need to block on this. 
cc @blimpich

**Comment by blimpich** [comment]
Source of the issue ended up being frontend actually (internal expensify slack link): https://expensify.slack.com/archives/C03TQ48KC/p1706738879615989

**Comment by blimpich** [comment]
Fix for this was deployed 2 weeks ago, closing this.
