### ISSUE TITLE
Task - Keyboard blinks when the delete task confirmation pop-up appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35481]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32575
## Action Performed:
1. Create or open any task from any chat
2. Tap on the three dots on top right > Delete

## Expected Result:
There's no blinking or pop over of the keyboard when deleting a task

## Actual Result:
The keyboard opens and closed for a moment when tapping to delete task and the transition is not smooth

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/16c502e3-44bf-4f53-8112-b5c73c472f1e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by francoisl** [comment]
Reproducible. Seems to be a known issue with a fix in review already, and it doesn't prevent from deleting the task, so we won't hold the deploy on this.
