### ISSUE TITLE
[HOLD for payment 2024-02-14] Scan- Invalid file is downloaded when uploading invalid file and downloading from receipt view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35482]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34087
## Action Performed:
1. Create a money request with receipt
2. Navigate to request details page
3. Click on the receipt > 3-dot menu > Replace
4. Upload a corrupted file
5. Click on the receipt preview > 3-dot menu > Download
6. Open the downloaded file

## Expected Result:
The downloaded file will be the corrupted file

## Actual Result:
The download receipt name belongs to the previous receipt (png format), but the downloaded file itself is invalid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fb742180-56a5-4b02-a043-4504bbefeddc

[Bug6362441_1706713172960!CORRUPT.pdf](https://github.com/Expensify/App/files/14113505/Bug6362441_1706713172960.CORRUPT.pdf)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5. 
CC @dylanexpensify

**Comment by luacmartins** [comment]
Looking at this now

**Comment by francoisl** [comment]
@luacmartins any luck with this one?

**Comment by luacmartins** [comment]
Demoting to NAB. Gonna leave a comment in the original PR so the contributor can look into it.

**Comment by luacmartins** [comment]
@tienifr could you look into this one? seems like a regression from https://github.com/Expensify/App/pull/34087

**Comment by luacmartins** [comment]
No payment needed here, this was a regression.
