### ISSUE TITLE
[$500] Header of the chat is loading when re-join the thread Offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Navigate to a conversation
3. Start a thread and send some messages
4. Disable the internet connection
5. Click on the three dot menu and hit "Leave thread"
6. Click on the thread link to rejoin the thread
## Expected Result:
Header of the chat is visible when re-join the thread Offline

## Actual Result:
Header of the chat is loading when re-join the thread Offline

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8643e525-1f00-40f4-990b-82f600d8cc59

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01002c1a0e7f6e533a</li>
        <li>Upwork Job ID: 1752729298574336000</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
I think this bug would be related to #vip-vsb.
cc @quinthar

**Comment by paultsimura** [comment]
This is expected. Please see the discussion here: https://github.com/Expensify/App/issues/34820#issuecomment-1904121803
