### ISSUE TITLE
[$500] Chat - The email reply appears as a chat message with Concierge

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in with an expensifail account
2. Create a group chat with 2 new Gmail accounts with "[account+text@gmail.com"](mailto:account+text@gmail.com%22)
format (don't log in with the Gmail accounts anywhere)
3. Write a few messages as the expensifail account
4. Log into the Gmail email client without the +
5. Reply to the unread messages with this:
_hi_
*hi*
6. Log in with any of the group chat Gmail accounts, navigate to the group chat and notice that the messages didn't appear
7. Log in with the main Gmail account without the +
8. Navigate to Concierge chat

## Expected Result:
It shouldn't appear in the Concierge chat.

## Actual Result:
The email reply appears as a chat message with Concierge.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6362588_1706720515171!1](https://github.com/Expensify/App/assets/38435837/a54fefb8-f784-49cb-a13f-2be7c9a8d26b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01193fa9423c09c617</li>
        <li>Upwork Job ID: 1752750826854637568</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We think this bug could be related to #vip-vsb
cc @quinthar

**Comment by slafortune** [comment]
Thanks for the details @fedirjh Yes, I agree that I don't feel it's a valid bug.
