### ISSUE TITLE
Expense preview says "paid" instead of "approved" after approving a report

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-2 
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706664891815749

## Action Performed:
1. Peter submitted a report to me in euros
1. I approved the report

## Expected Result:
 The expense preview and conversation header should say I approved the report, not paid it. 

## Actual Result:
The expense preview and conversation header is marked as paid in the report conversation.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![image](https://github.com/Expensify/App/assets/44479856/e8e62b51-472f-41d6-81cb-8d75fd818940)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017dd2b1d9defd16ab</li>
        <li>Upwork Job ID: 1752746080446013441</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by slafortune** [comment]
Added to #wave7 and Hotpick added

**Comment by alitoshmatov** [comment]
No proposals yet

**Comment by dangrous** [comment]
Caveat to what I'm about to say - I have not looked into this other than reading the description of the bug, but -

This looks like it could be external, right? I'm not sure if this needs to be an internal/backend fix. We might want to open it up, unless there's background/context that I'm missing.

I'm happy to shepherd if we go the external route!
