### ISSUE TITLE
[$500] mweb-Compose-In 1:1 page, concierge with invite not shown but in IOU report page it is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.34
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4259033
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conve1. Go to https://staging.new.expensify.com/

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report with IOU chats
3. Enter @ in compose
4. Select a contact from user suggestions and send it
5. Note no concierge message is displayed
6. Tap on any IOU and open IOU report page
7. Enter @ in compose
8. Select a contact from user suggestions and send it
9. Note concierge message is displayed with invite option
10. Tap on invite
11. Note contact isn't the member of room displayed

## Expected Result:
Both in 1:1 page and IOU report page, if i select a contact from user suggestion and send, concierge message behavior must be same.
If user when taps invite button in IOU report page, invited message must be displayed and isn't the member of this room message must not be displayed

## Actual Result:
In 1:1 page, if i select a contact from user suggestion and send, concierge message with invite option is not shown.
From IOU report page, if i select a contact from user suggestion and send, in that case, concierge message with invite option is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e468d5ef-05a5-43b8-8280-9cb052c042fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01413f5ddf6832318b</li>
        <li>Upwork Job ID: 1752770692457275392</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
Waiting for proposals

**Comment by nebiyuelias1** [comment]
This seems to me like a BE issue and IOU report can have more than two members that's why we're probably seeing the conceirge message.

**Comment by garrettmknight** [comment]
Rereading this one, I don't think it's a bug - users shouldn't be able to invite 3rd parties to 1:1 chats, but should be able to invite into IOU report/transaction threads. Closing
