### ISSUE TITLE
Modify the `UpdateMoneyRequestDistance` API endpoint

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#35503]
# Problem

We need the `UpdateMoneyRequestDistance` endpoint to give the frontend more information in its response in order to complete https://github.com/Expensify/App/issues/34686. 

# Solution 

Three things need to happen:
1. We need the endpoint to calculate the difference between existing and new waypoints
2. We need it to explicitly return waypoints that have been removed as `null` 
3. All non-null waypoints should be moved to the start of the response

i.e.
```
{
  w0: A
  w1: B (remove)
  w2: C
  w3: D (remove)
}
```
Should turn into:
```
{
  w0: A
  w1: C
  w2: null
  w3: null
}
```

Please see [this comment/discussion](https://github.com/Expensify/App/issues/34686#issuecomment-1915354056) for more details.

cc: @paultsimura @tgolen 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6425ace3c091bfc</li>
        <li>Upwork Job ID: 1752762514809204736</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
Waiting for proposals.

**Comment by blimpich** [comment]
Yup internal. Need an expensify engineer to do this. Not waiting on proposals.

**Comment by tgolen** [comment]
I'm going to grab this one and start on it.

**Comment by tgolen** [comment]
@blimpich I was able to create [a PR](https://github.com/Expensify/Web-Expensify/pull/40864) that covers this case and formats the results as expected. I have also made it handle this situation:

The request is created with these waypoints:
```
{
  w0: A
  w1: B
  w2: C
  w3: D
  w4: E
}
```

The request is updated to remove `B` and `D` and adds an `F`. This is the resulting Onyx update.

```
{
  w0: A
  w1: C
  w2: E
  w3: F
  w4: null
}
```

I hope that's expected.

**Comment by tgolen** [comment]
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/40864) was created and is in review

**Comment by tgolen** [comment]
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/40864) has had two reviews and is nearly ready to merge.

**Comment by tgolen** [comment]
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/40864) has been merged and it is on staging.
