### ISSUE TITLE
[$500]  Expense Rules -Tags dropdown options can not be selected in expense rules by Employee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4256154
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisite: Collect policy and Categories&Tags are setup in Olddot by Admin
1. Login OD Expensify via Employee
2. Navigate to Account Settings > Expense Rules
3. Click New Rule
4. Click in Tag field to open the dropdown options

## Expected Result:
Tag options are shown and can be selected while creating expense rules by Employee

## Actual Result:
No Tag option is shown while creating expense rules by Employee. (Requirement for testcase https://expensify.testrail.io/index.php?/cases/view/2761736
)
Note: Admin can select Tags while creating expense rules

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/829361b8-618b-4a6c-b096-2daa3b87b22a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145a2c2f834cc80ea</li>
        <li>Upwork Job ID: 1752774362092625920</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by greg-schroeder** [comment]
Sorry is this just a purely OldDot bug? No changes were made in NewDot to create problems with backwards compatibility?

If that's the case:

- This isn't a Wave 6 issue
- It should be created in Expensify/Expensify instead of E/App (although it'll probably be closed cause it's OldDot specific and isn't really a driver of customer contact)
