### ISSUE TITLE
Expense - LHN preview for request report shows owner name next to request edit system message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35515]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.34-0
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is an employee of Collect workspace on Old Dot.
1. Create a distance request in the workspace chat.
2. Go to distance request details page.
3. Go offline.
4. Click Description.
5. Edit the description and save it.
6. Note that the LHN preview shows the owner name.
7. Go online.

## Expected Result:
In Step 6, LHN preview for the expense details report will not show the owner name (current user) next to the system message.

## Actual Result:
In Step 6, LHN preview for the expense details report shows the owner name next to the system message.
The owner name disappears after returning online in Step 7.
The issue is reproducible without going online. In that case, the owner name appears and disappears quickly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/24c4be89-9e12-425d-becf-3297d3ec3800

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to  #wave6-collect-submitters
CC @dylanexpensify

**Comment by blimpich** [comment]
This isn't a blocker, too niche.

**Comment by blimpich** [comment]
Looks like https://github.com/Expensify/App/pull/34872 might be PR that caused this? @koko57 could you take a look and confirm or deny?

**Comment by blimpich** [comment]
@koko57 sounds good, thank you! Is there already an issue and reviewer for that next PR or do you think I should mark this as external, get a C+ reviewer for it, and assign you to this issue? I'm fine either way.

**Comment by koko57** [comment]
@blimpich I can do this as a part of [LHN follow-ups issue ](https://github.com/Expensify/App/issues/34411) 

cc @mountiny

**Comment by blimpich** [comment]
@mountiny copying it over to the linked PR sounds perfect to me, thank you both!

**Comment by mountiny** [comment]
Added, thanks!
