### ISSUE TITLE
[Wave8] Backwards Compatibility: Tag disabled in OldDot is displayed in tags list during IOU creation in NewDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35516]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
User is Employee of Collect workspace and
1. Navigate to workspace chat as employee
2. Click +> Request money> Manual
3. As Admin navigate to Old dot and disable Tag 1
4. As employee on click on Tag section and check the list

## Expected Result:
Tag 1 should not be present in tags list

## Actual Result:
Tag 1 should is present in tags list

## Workaround:
Unknow

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c236ec4e-2de3-42ba-9de9-c522b3fc78c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dedbcd7acaf45c5a</li>
        <li>Upwork Job ID: 1758284653418659840</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
This might be more Wave 8 as it's related to an admin action and workspace configuration... thoughts @zanyrenney?

**Comment by strepanier03** [comment]
@zanyrenney - I'm going to add to Wave 8, let me know if you want it removed to it fits elsewhere.

**Comment by strepanier03** [comment]
I'm going to assume this is an internal issue but could easily be wrong. Let me know if I should change this!

**Comment by jjcoffee** [comment]
Can't repro on `v1.4.42-1` @kbecciv can you retest?

**Comment by strepanier03** [comment]
All good Melvin.

**Comment by jjcoffee** [comment]
@kbecciv Thanks for retesting! I think what's happening here is that you're opening the tag menu "too fast", so the pusher event hasn't come through yet and it doesn't update the list to remove the disabled tag whilst the tag selection modal is open. 

If you navigate back and reopen the tag should be removed from the list (at least that's what I see). So I guess there _is_ a minor bug there that the item isn't removed from the list whilst it's open, the question is is that worth fixing? cc @strepanier03

**Comment by strepanier03** [comment]
Thank you @jjcoffee - I'm raising it internally so we can chat about it a bit and decide how to move forward.

**Comment by strepanier03** [comment]
Raised [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1708710325245289), will follow up.

**Comment by strepanier03** [comment]
Okay, we're putting this one on hold for https://github.com/Expensify/App/issues/35909 and we'll see if that resolves this one when it closes.

**Comment by strepanier03** [comment]
Hold GH is still open, still holding.

**Comment by strepanier03** [comment]
HOLD GH is now closed, switching to Daily and I'll work on this tomorrow.

**Comment by strepanier03** [comment]
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1710373684687499).

**Comment by kavimuru** [comment]
@strepanier03 Issue is reproduced in real time. If the page is refreshed on employee side then issue is not reproduced.

https://github.com/Expensify/App/assets/43996225/81ddd18a-4dc7-4930-99d4-f43ddd2957c7


https://github.com/Expensify/App/assets/43996225/f529ca41-36ef-4b40-b855-9497173f0c3b

**Comment by strepanier03** [comment]
Thank you Kavi, this is assigned to a project so we'll wait for it to be picked up.

**Comment by strepanier03** [comment]
Labeled ToDo, so likely to be a bit before it's picked up.

**Comment by strepanier03** [comment]
Not set to a priority at this time but held for the future.

**Comment by strepanier03** [comment]
Waiting for prioritization.

**Comment by strepanier03** [comment]
Waiting for prioritization still.

**Comment by strepanier03** [comment]
Hmmm, just noticed this is the only outstanding issue on Wave8, which isn't a project any longer. 

I'm going to close this out and we can reopen if we decide to prioritize and pull it into a new project.
