### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Chat - "Hidden" is not shown on the header of avatar for "Hidden" contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open 1:1 DM with Hidden user ([yonghongkok2+03011@gmail.com](mailto:yonghongkok2+03011@gmail.com)
2. Click on the chat header.
3. Click on the avatar.

## Expected Result:
The header shows "Hidden"

## Actual Result:
The header is blank and missing "Hidden"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/448ff4c3-a7d5-42b1-be4a-830e9863ffc0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010dd17add55a87ae6</li>
        <li>Upwork Job ID: 1752801163354193920</li>
        <li>Last Price Increase: 2024-01-31</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - "Hidden" is not shown on the header of avatar for "Hidden" contact

### What is the root cause of that problem?

In the `ReportAvatar` component, we do not use `hidden` but just an empty string.

### What changes do you think we should make in order to solve the problem?


```
headerTitle={personalDetail?.displayName ?? translate('common.hidden')}
```

**Comment by Tony-MK** [comment]
@RohanSasne, I noticed you changed your Prospal after I posted mine.

**Comment by mollfpr** [comment]
Thank you guys for the proposals! The [proposal](https://github.com/Expensify/App/issues/35514#issuecomment-1919997266) from @ZhenjaHorbach looks the best for the fix in this issue. I agree to use `getDisplayNameOrDefault` to show the modal title.

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
Friendly bump @tylerkaraszewski

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/28999

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/28999/files#r1503614748

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open 1:1 DM with Hidden user ([yonghongkok2+03011@gmail.com](mailto:yonghongkok2+03011@gmail.com))
2. Click on the chat header.
3. Click on the avatar.
4. Verify that Hiden is displayed on the avatar screen
5. 👍 or 👎

**Comment by mollfpr** [comment]
@miljakljajic I'll do the manual request in NewDot, could you give the payment summary? Thank you!

**Comment by miljakljajic** [comment]
@mollfpr is owed 500 USD for their role as reviewer

**Comment by miljakljajic** [comment]
@ZhenjaHorbach are you paid in upwork? I can't access the offer via that link, it throws up an error. I can send another?

**Comment by miljakljajic** [comment]
@ZhenjaHorbach what's your name in upwork? I tried to search for you but it isn't coming up

**Comment by miljakljajic** [comment]
Sent - let me know when you accept

**Comment by miljakljajic** [comment]
Paid!

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr based on summary above.
