### ISSUE TITLE
HIGH: [Public] Make all workspace room members "known" to the admins

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#35539]
**Problem:**
A workspace owner pays for activity in their workspace room.  And anybody can invite anyone to that room.  When you do, it notifies admins that someone has been invited in the #admins room.  However, because the admins have no relationship with the invited person, the invited person shows as "Hidden".

**Solution:**
If Alice invites Bob to a room, and Cathy is the workspace admin, then Cathy should "know" Bob and see Bob's primary login.  After all, Alice could have only invited Bob using Bob's primary login, so by inviting him, she's in effect introduced Bob to Cathy.

**Comment by puneetlath** [comment]
Issue for query timing here: https://github.com/Expensify/Expensify/issues/373736

**Comment by puneetlath** [comment]
Continuing to work on the query.

**Comment by puneetlath** [comment]
Will start working on this again soon.

**Comment by puneetlath** [comment]
Ok PR is in review: https://github.com/Expensify/Auth/pull/10537

**Comment by puneetlath** [comment]
PR was deployed.
