### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500] Wallet - Back button loops the app between Expensify card and Activate card after page refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35530]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35303
## Action Performed:
1. Log in with account that has Expensify card (virtual) ([applausetester@applause.expensifail.com](mailto:applausetester@applause.expensifail.com)
)
2. Go to Settings > Wallet
3. Click Expensify card
4. Click Activate physical card
5. Refresh the page
6. Click on the back button
7. Click on the back button again

## Expected Result:
Back button will navigate to the previous page

## Actual Result:
Back button loops the app between Expensify card and Activate card page after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/7d8cd611-dcf8-4092-b1da-d7d866ef6077

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010098f2976f28fbf7</li>
        <li>Upwork Job ID: 1752867434380029952</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28133789</li>
<li>Ollyws | Contributor | 28133791</li>
<li>dukenv0307 | Contributor | 28135667</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5. 
CC @dylanexpensify

**Comment by jliexpensify** [comment]
@Ollyws @luacmartins 

>Issue found when executing PR https://github.com/Expensify/App/pull/35303

Is this a regression?

**Comment by luacmartins** [comment]
That sounds good to me, reassigning @fedirjh. Thanks @Ollyws!

**Comment by luacmartins** [comment]
I think @dukenv0307's proposal looks good. What do you think @fedirjh?

**Comment by jliexpensify** [comment]
Bump @fedirjh to complete the checklist

**Comment by jliexpensify** [comment]
Paid and job closed!
