### ISSUE TITLE
[$500] Web - VBA - Infinite loading when try to add bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4256249
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
Setup - OldDot
1.Create a new Gmail account in OldDot (must be new)
2. Create a collect workspace
3. Set the workspace policy to USD
4. Set the approval mode to "Submit and Approve"
5. Open the JS console and run the following script in the collect policy settings page:
if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }
Steps:
1. As Admin navigate to the Collect Workspace settings
2. Click on Reimbursements
3. Click on Direct
4. Click on Add Business bank account

## Expected Result:
Modal to add bank account should open

## Actual Result:
Infinite loading when try to add bank account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6427abc7-bdee-4814-8e42-bbb7321ab09e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6d5733571b8f933</li>
        <li>Upwork Job ID: 1752872645337956352</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave7
CC @RachCHopkins

**Comment by joekaufmanexpensify** [comment]
This was a known bug yesterday, and has since been fixed.
