### ISSUE TITLE
[HOLD] [$500] Crash when request category includes '&' instead of '&amp'

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#35543]
### Problem

App crashes when the user clicks on Categories while requesting money on the Contributor+ workspace.

**Steps:** 
- Navigate to the Contributor+ workspace
- Fill amount
- Fill description
- Select Category
- App crashes

<img width="475" alt="Screenshot 2024-02-01 at 09 57 46" src="https://github.com/Expensify/App/assets/10736861/7bd90063-9ebe-4a66-bda9-4d869d6b0858">

https://github.com/Expensify/App/assets/10736861/b172701a-49a1-443a-a73c-00b08d555536

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0145ee5e2d7a0f1e57</li>
        <li>Upwork Job ID: 1752994017262460928</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by Julesssss** [comment]
This might need to be fixed by a contributor, as I can't reproduce in our internal workspace.

**Comment by esh-g** [comment]
we can try using optional chaining here:
https://github.com/Expensify/App/blob/c6758578fb85e9eff6f9ccf5a52f3dd34e6e6383/src/libs/OptionsListUtils.ts#L832

Please let me know if this is still reproducible

**Comment by mananjadhav** [comment]
@aswin-s Are you able to reproduce this? I think the posted root cause is incorrect.

**Comment by rushatgabhane** [comment]
It's not applicable to just C+ workspace.
Any workspace having `&` in its name will have this issue

**Comment by bernhardoj** [comment]
Having `&` in the category name works fine for me, but I can reproduce this on two of my workspaces where it has an `Uncategorized` recently used categories and crashes at this line.
https://github.com/Expensify/App/blob/aeb8638a46bbc50013e263f037a45c7c3b7af8ad/src/libs/OptionsListUtils.ts#L986-L987

<img width="513" alt="image" src="https://github.com/Expensify/App/assets/50919443/0f0e4e7c-122a-493a-918d-7ef54773ebfc">

Creating an expense on OldDot without a category will have an Uncategorized category, but I don't know how it gets added to the recently used categories. I would suggest adding the null-safety to all `categories[categoryName].enabled` usage.

**Comment by Julesssss** [comment]
Thanks all. We're looking into this internally for the minute

**Comment by Julesssss** [comment]
Being handled [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1707133846863739?thread_ts=1706773404.449439&cid=C02NK2DQWUX)

**Comment by Julesssss** [comment]
Re-opening as Jason isn't able to remove and recreate the category. 

@heyjennahay could you please do the following to unblock C+ peyments: 
- Remove the `Contractors - Accounting, Tax, Audit & Compliance` category from the Contributor workspace
- Re-add the same category: `Contractors - Accounting, Tax, Audit & Compliance`

**Comment by heyjennahay** [comment]
I deleted all categories with `&` on the C+ policy

**Comment by mananjadhav** [comment]
This one loads fine now. I can now see `Contractors - External Engineering/Testing (Applause/Upwork)`.


<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/3069065/dac5b89d-92fd-4f68-a38f-3115aaa76881">

**Comment by Julesssss** [comment]
Thanks @heyjennahay 👍
