### ISSUE TITLE
[$500] Room - Workspaces listed in room are not listed in alphabetical order

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35551]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4253850
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition: Must have many workspaces
1. Launch app
2. Tap fab---start chat
3. Tap room
4. Tap Workspace

## Expected Result:
Workspaces listed in room should be listed in alphabetical order

## Actual Result:
Workspaces listed in room are not listed in alphabetical order

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/36a278a9-ca97-42d4-997a-a0bc3ffbc146

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117f5ef3bcc201228</li>
        <li>Upwork Job ID: 1753053930785366016</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspaces listed in room are not listed in alphabetical order

### What is the root cause of that problem?
Workspace options not ordered
### What changes do you think we should make in order to solve the problem?

We need to alphabetically sort workspace options
### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment]
Hey @fedirjh, can you please review the proposals above? Thanks!

**Comment by francoisl** [comment]
Hm yeah weird. Looks like there were no regression so this is ready for payment then? @isabelastisser can you assist with that please?

**Comment by francoisl** [comment]
Internal issue to create regression tests opened [here](https://github.com/Expensify/Expensify/issues/373481), all we have to do is payments now @isabelastisser.

**Comment by isabelastisser** [comment]
The payments are processed in Upwork.

All set!
