### ISSUE TITLE
Chat -  The "Pin" button becomes unresponsive

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35559]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Go to any conversation.
2, Click on the three dots in the right corner.
3, Click on the pin icon and observe that it is unresponsive

## Expected Result:
The "Pin" button should be responsive when clicking on the pin icon from the dropdown in the conversation

## Actual Result:
The "Pin" button is unresponsive when clicking on the pin icon from the dropdown in the conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0ae9e209-d991-4292-82e5-ee1f66a82cf3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pinned report isn't showing unpin option

### What is the root cause of that problem?
It is a regression from https://github.com/Expensify/App/pull/30168 where light weight report object gets created but we aren't setting the `isPinned` field.

### What changes do you think we should make in order to solve the problem?
Add `isPinned` field with the value which we had in the onyx report data.

**Comment by hurali97** [comment]
@aimane-chnaif I can take a look tomorrow morning 👍

**Comment by mountiny** [comment]
CP done!
