### ISSUE TITLE
[$500]  IOU - A disabled category in IOU does not deselect when you click on it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4257599
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
Configure the OldDot administrator account, include a maximum of 7 categories and invite the employee to the policy https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0
Steps:
1. Open https://staging.new.expensify.com/
2. Log in with the account of the employee added to the policy
3. Navigate to the group policy chat room
4. Create a manual request with any category and send it to the WS room
5. Open https://staging.expensify.com/
6. Under the administrator account, disable the category from step 4
7. In NewDot, under the employee's account, go to IOU details
8. Click on the category field
9. Click on the selected category with a green check mark

## Expected Result:
When you click on a disabled category, it should deselect itself

## Actual Result:
A disabled category in IOU does not deselect when you click on it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/af497838-4503-4a31-be07-1807c713ee7f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faafade61edc83ca</li>
        <li>Upwork Job ID: 1753056687790592000</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 28142211</li>
<li>tienifr | Contributor | 28142212</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by DylanDylann** [comment]
The main solution in @tienifr's [proposal](https://github.com/Expensify/App/issues/35553#issuecomment-1921632377) looks good to me
🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment]
@tienifr could you please raise a follow-up? There's a good suggested fix [here](https://github.com/Expensify/App/issues/36912#issuecomment-1957074816) in the linked issue

**Comment by DylanDylann** [comment]
@laurenreidexpensify Please help to move forward with this issue, the PR is deployed to production and there are no regression as confirmed [here](https://github.com/Expensify/App/issues/36912#issuecomment-1964009641)

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor $500 paid in Upwork @tienifr 
C+ $500 paid in Upwork @DylanDylann

**Comment by laurenreidexpensify** [comment]
@DylanDylann pls add checklist and regression step suggestions thank you

**Comment by DylanDylann** [comment]
# Regression Test Step

1. Create a request with category
2. In OD, disable the selected category
3. Go to the transaction detail report
4. Press Category
5. Verify we can deselect the selected category

Do we agree 👍 or 👎

**Comment by Julesssss** [comment]
I'm not sure we need this very specific regression test to be honest. If none already exist maybe we could create a generic one to test the list component with a disabled item to cover many cases
