### ISSUE TITLE
IOU - Pay elsewhere button does nothing and console error shows up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.3.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Request money from User B
2. [User B] Click on IOU preview to go to IOU report
3. [User B] Click Pay elsewhere

## Expected Result:
The request is paid successfully

## Actual Result:
Nothing happens after clicking on Pay elsewhere. Console error shows up. On Android and iOS, app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/813d4d64-cfbf-4edd-b180-4b75f24c215d

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by lakchote** [comment]
> When user requested money from within a specific report, we did not pass the specific reportID to the backend. Instead we always depended on what reportID has been saved in the chatReport.iouReportID key.

Looks like it might be https://github.com/Expensify/App/pull/35246 

cc @mountiny

**Comment by mountiny** [comment]
I dont think its related, this seems as backend issue


The moneyRequestReport is missing chatReportID key

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/36083550/d02e48c7-62fc-46fc-9b5e-6099d2dc1cab">

in here https://github.com/Expensify/App/blob/9ab4fe92dcbac8252998febf6fa24a080a196a70/src/components/MoneyReportHeader.tsx#L203

**Comment by mountiny** [comment]
its in onyx, it will be the same fix as here https://github.com/Expensify/App/pull/35563/files#r1474670646 need to add the chatReportID to the memo

**Comment by lakchote** [comment]
> I am not able to reproduce on main

Hmm, that's odd I can reproduce it on main

https://github.com/Expensify/App/assets/21549771/b16bdbac-3a3a-43be-9aa6-e8e195fcef43

**Comment by lakchote** [comment]
Yes it looks like it's on staging only.

It was stated by @lanitochka17 😄
> **Reproducible in staging?:** Y
> **Reproducible in production?:** N

**Comment by mountiny** [comment]
I can reproduce on main, adding the chatReportID to the memo fixed it

**Comment by mountiny** [comment]
Ideally we can fix this in @rlinoz PR too https://github.com/Expensify/App/pull/35563

**Comment by mountiny** [comment]
fix cped
