### ISSUE TITLE
Expense - Submit button is green in the main chat and gray in the expense report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35569]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- Schedule submit is turned off
1. Go to workspace chat
2. Create a manual expense
3. Note that the submit button is green in the expense preview in the workspace chat
4. Click on the expense preview

## Expected Result:
The submit button in the expense report is green

## Actual Result:
The submit button in the expense report is gray.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/11492fb4-9af7-4c37-bacb-0067d24fdf96

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by luacmartins** [comment]
@Expensify/design can you confirm if they should be all green please?

**Comment by mountiny** [comment]
yeah both should be same colour, green if you are the submitter, gray if scheduled submit is on or you are not the submitter.

**Comment by mountiny** [comment]
I think it might require same fix as here https://github.com/Expensify/App/issues/35562#issuecomment-1921570752

**Comment by mountiny** [comment]
Yep adding chatReportID to the memo should fix this too https://github.com/Expensify/App/pull/35563#discussion_r1474766295

@rlinoz will add it I believe

**Comment by mountiny** [comment]
can be discussed in this thread https://expensify.slack.com/archives/C03TQ48KC/p1706800895520479

**Comment by trjExpensify** [comment]
>yeah both should be same colour, green if you are the submitter, gray if scheduled submit is on or you are not the submitter.

Correct, agreed!

**Comment by luacmartins** [comment]
Nice, thanks for the discussion! So it seems like @rlinoz will be fixing this!

**Comment by mountiny** [comment]
fix cped
