### ISSUE TITLE
[HOLD for payment 2024-02-09] [$500] Task – Unable to change assignee twice when edit a task Offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35574]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4262665
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a task with assignee
4. Open task details page and go Offline
5. Change the assignee to another
6. Change the assignee to another one more time

## Expected Result:
Assignee from the step 6 is displayed

## Actual Result:
Assignee from the step 5 is displayed. Unable to change assignee twice when edit a task Offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f61a3929-ed29-4f88-9055-f4f7656c1804

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8af7391b7bbb42a</li>
        <li>Upwork Job ID: 1753172040869830656</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 28135627</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by grgia** [comment]
@hurali97 it seems your PR https://github.com/Expensify/App/pull/30168 may have caused this regression

Are you able to push a follow up or shall we test the above proposal? 

cc @aimane-chnaif @mountiny

**Comment by mountiny** [comment]
@grgia I can help take over, indeed that is coming from the PR thank you for the heads up!

**Comment by mountiny** [comment]
@mkhutornyi are you able to raise the PR now? is $250 fine with you? The change is simple and same as in couple other fixes so adjusting price given the low complaxity

**Comment by mountiny** [comment]
@mkhutornyi please feel free to raise the PR!

**Comment by mountiny** [comment]
@mkhutornyi please ping me in slack when you have the PR ready!

**Comment by kadiealexander** [comment]
Sorry, was OOO! Payouts due:

- [ ] Contributor: $500 @mkhutornyi
- [ ] Contributor+: $500 @aimane-chnaif 

Upwork job is [here](https://www.upwork.com/ab/applicants/1753172040869830656/hired).
