### ISSUE TITLE
[$500] Home - When banner pop up remains opened, expensify logo and profile icon cannot be seen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4263441
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login using new account in both mweb and app
2. Note, a banner pop up is displayed

## Expected Result:
In mweb, when banner pop up remains opened, expensify logo and profile icon user must be able to see like in Android app

## Actual Result:
In mweb, when banner pop up remains opened, expensify logo and profile icon cannot be seen but in Android app, it can be seen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3fc7f3ea-bf95-495e-a7e7-ff894f04daae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01341c171ea9087168</li>
        <li>Upwork Job ID: 1753150891535253504</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Home - When banner pop up remains opened, expensify logo and profile icon cannot be seen
### What is the root cause of that problem?
Modal container max height set as `windowHeight` here
### What changes do you think we should make in order to solve the problem?
Set max height `windowHeight - variables.contentHeaderHeight`

### What alternative solutions did you explore? (Optional)

**Comment by eVoloshchak** [comment]
> In mweb, when banner pop up remains opened, expensify logo and profile icon cannot be seen but in Android app, it can be seen

@strepanier03, I'm not sure if the expected result is correct here
Shouldn't the banner cover all of the screen instead? (i.e. it should look like it currently looks on mWeb)

**Comment by strepanier03** [comment]
Hmmm, good question. I'll have to repro and then raise internally for a chat about expected behavior.

**Comment by strepanier03** [comment]
Raised [here](https://expensify.slack.com/archives/C03U7DCU4/p1707852448320429), waiting for discussion.

**Comment by strepanier03** [comment]
Per Shawn.

> I don't think this is a bug, I think it depends on screen height. I've mentioned this to 
> [@bstites](https://expensify.slack.com/team/U3KQXBXHP)
>  before but I think in hindsight we probably should have made this a full screen experience. But we have some upcoming onboarding changes on the way so it's probably (not) worth touching this since things are changing anyways.

IN light of the changes coming and the suggestion we don't touch this, I'm going to clos.
