### ISSUE TITLE
Task – Deleted task not appears immediately in user B if the chat with user A is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.35-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4262588
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. As user A create a task in a chat with user B, open it details and sand a message
4. As user B open the chat with user A and verify the task with reply present
5. As user A delete the task

## Expected Result:
Deleted task appears immediately in user B

## Actual Result:
Deleted task not appears immediately in user B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4d4f2173-57ee-46d8-ba21-a55ddf312e92

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment]
The server doesn't send the pusher data to "delete" the task.

**Comment by muttmuure** [comment]
@kbecciv what does "verify the task with reply present"

**Comment by kbecciv** [comment]
@muttmuure "verify the task with reply present" means that user has reply in task.

![image](https://github.com/Expensify/App/assets/93399543/bc8768f7-6c46-4b0a-9f02-c1d1d444eecb)

**Comment by muttmuure** [comment]
I'm not able to reproduce this.
