### ISSUE TITLE
[$500] [MEDIUM] Categories: Some categories are scrolled and not focused when using key arrows and Enter

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35589]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2778101
**Email or phone of affected tester (no customers):** bpopov+usera@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: OD: Admin add to collect WS custom categories with sub-categories. Employee is logged in ND
1. ND: employee navigates to https://staging.new.expensify.com/
2. Request money in WS chat
3. On request details page click 'Categories'
4. Use arrow keys to navigate through the categories list
5. Select a category by pressing Enter

## Expected Result:
Chosen (grey focused) category is displayed in the category field

## Actual Result:
Some categories with sub-categories are not grey focused while navigating.
In the category field wrong category displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/32baa5b6-3371-4f44-96c3-b38705e9fee9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ec9209caac10891</li>
        <li>Upwork Job ID: 1753154161331003392</li>
        <li>Last Price Increase: 2024-02-15</li>
    </ul>
</details>

**Comment by Universe-stack** [comment]
hi guys, Came from upwork to help.

Are you guys using any form of state management to track and store the selected category?

**Comment by conorpendergrast** [comment]
@c3024 any suggestions for improving the write-up to make this more engaging for contributors to add proposals?

**Comment by c3024** [comment]
Could not get time to look into this. Will update in a few hours.

**Comment by c3024** [comment]
@lanitochka17 

Could you check if this is reproducible now?

I have been trying to but could not.

https://github.com/Expensify/App/assets/102477862/f49953c4-b75c-4226-913d-bf52e5647d97



https://github.com/Expensify/App/assets/102477862/c311dd6c-21c1-4239-8b99-ed8385e328dc



https://github.com/Expensify/App/assets/102477862/f187b30d-9ffe-4dd9-b700-dc56cbb0eef1


https://github.com/Expensify/App/assets/102477862/a488c825-04b9-4e05-97ff-c6182ce73eba


If you could reproduce the bug, please add this email `expensifytest729+categorypicker@gmail.com` to the workspace so that I can check the bug with the same workspace you are using. Thanks.

**Comment by lanitochka17** [comment]
Hello Issue is not reproducible in latest build 1.4.40-0

https://github.com/Expensify/App/assets/78819774/bece1447-eb32-4f00-a534-1063d56e6b20

**Comment by greg-schroeder** [comment]
Closing as this is no longer reproducible
