### ISSUE TITLE
[$500]  Login - Magic code is not send after create account from Old dot

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4262884
**Email or phone of affected tester (no customers):** utster29+402@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
Log out of both NewDot and OldDot
1. Navigate to STG OldDot (staging.expensify.com)
2. In the login screen enter a new gmail account
3. Verify you're navigated to staging NewDot
4. Navigate to account Settings > Contact methods
5. Verify the email field has a GBR dot
6. Click on the email
7. Verify you're prompted for the magic code to validate the account

## Expected Result:
Verify the account receives a magic code to their email inbox

## Actual Result:
Magic code is not sent to email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/54f0b2c6-9ca1-4fc5-9b93-8d18380d7160

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015531471a25f11bb5</li>
        <li>Upwork Job ID: 1753151928044457984</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
Waiting for proposals

**Comment by alitoshmatov** [comment]
Waiting for proposals

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
same

**Comment by alitoshmatov** [comment]
As far as I understand this issue involves sending email and old dot which are not accessible by external contributor. So I think this issue cannot be handled by externally

**Comment by dylanexpensify** [comment]
Great point, moving internal

**Comment by dylanexpensify** [comment]
Hmm, @lanitochka17 can you still repro?

**Comment by dylanexpensify** [comment]
Apologies, I've been OOO sick, but am reviewing today!

**Comment by dylanexpensify** [comment]
actioning today
