### ISSUE TITLE
[HOLD for payment 2024-02-09] [$500] IOU – Failed Split bill lost receipt when go offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
User have failed Split bill
Steps:
1. Navigate to the failed Split bill chat
2. Go offline
3. Navigate to other chat
4. Come back to the failed Split bill chat

## Expected Result:
Failed Split bill receipt should be visible on chat and detailed view

## Actual Result:
ailed Split bill receipt is not displayed in offline mode.
Same behavior when open a chat with attachment uploaded and disable the internet connection

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b77ebe6b-30b7-4a27-af7c-351ef196a71f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bec8e5af62cb469a</li>
        <li>Upwork Job ID: 1753183814253965312</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by francoisl** [comment]
Not sure why no one got assigned to this, I'll reapply the label and start looking on the side.

**Comment by francoisl** [comment]
It _might_ be from https://github.com/Expensify/App/issues/35580 but I can't repro locally, I'll start an ad-hoc build to test more.

**Comment by francoisl** [comment]
cc @kidroca if you have any idea how https://github.com/Expensify/App/pull/34505 would cause issues with locally cached images while offline.

**Comment by kidroca** [comment]
> cc @kidroca if you have any idea how https://github.com/Expensify/App/pull/34505 would cause issues with locally cached images while offline.

It might be that the images weren't yet cached 
As with other images we haven't yet seen they would appear as blank when we try to present them with no internet

I'd like to check this out on staging, to exclude any other issues like CORS

**Comment by kidroca** [comment]
Hey @kbecciv can you update the reproduction steps and explain how to get in to this "failed split bill" precondition

I’m trying to reproduce and debug the issue, but I don’t understand the section and the precondition

**Comment by francoisl** [comment]
> Hey kbecciv can you update the reproduction steps and explain how to get in to this "failed split bill" precondition
> I’m trying to reproduce and debug the issue, but I don’t understand the section and the precondition

@kidroca for my test steps, I found that you don't even need a failed split bill specifically - any receipt upload will do. Here are steps you can use:

1. Create a workspace. This will create a workspace expense chat between you and the workspace, open it
2. From the Composer, the `+` option should have a Split Bill option, click that
    <img width="1056" alt="image" src="https://github.com/Expensify/App/assets/2229301/7d913a24-2884-4492-a0fa-a9f4e07c9880">
4. Use the `Scan` option, and upload any image. You should then see a "Scan in progress…" preview in the chat
5. Go offline
6. Switch to any other chat
7. Switch back to the workspace chat with the receipt
    - That's when the receipt image was missing

Hope this helps, let me know if you need any more details.

**Comment by francoisl** [comment]
This was a deploy blocker that was handled internally, I don't believe any payment is due but let me know if that's wrong.
