### ISSUE TITLE
[HOLD for payment 2024-02-09] [$500] Task - Assignee not updated immediately after admin reassigns task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35597]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
precondition: as Admin create a workspace and invite Employee A and Employee B
1. As Employee A create a task in the announce room and assign it to yourself
2. Log in as Employee B and open the task created by Employee A
3. On a different device or in incognito log in as Admin
4. As Admin change the assignee to Employee A

## Expected Result:
The assignee is changed for Employee B immediately and Employee B can modify the task

## Actual Result:
The assignee is not changed if the task report is open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/661129bf-30ea-47cd-9c1b-35fc8cdbeff3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100dc89735d2869ee</li>
        <li>Upwork Job ID: 1753177264991649792</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
Issue is not reproducible in prod 

https://github.com/Expensify/App/assets/93399543/9cff96e4-ff74-44cb-af1e-fb1f0a4e7171

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by neil-marcellini** [comment]
I'll start investigating, but also labeling this external to get help from contributors in finding the root cause.

**Comment by mountiny** [comment]
This could have the same root cause as this DB https://github.com/Expensify/App/issues/35574

**Comment by mountiny** [comment]
yeah I feel like its similar the managerID change is not listened to, the contributor has a PR going soon so I can add this to testing steps to verify!

@mkhutornyi let's check for this scenario too but I think it might be fixed with your change too

**Comment by neil-marcellini** [comment]
Awesome thanks so much Vit!

**Comment by mountiny** [comment]
Contributor confirmed this was also fixed

**Comment by neil-marcellini** [comment]
Cool, I'll close this then
