### ISSUE TITLE
[HOLD ON #34970][$500] iOS - BA - Animation is briefly displayed before Continue with setup page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35592]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4264503
**Email or phone of affected tester (no customers):** applausetester+vd_ios020124@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and have created a workspace
1. Go to Settings > Workspace > Select Workspace > Bank account
2. Start and follow the flow for adding a fully verified bank account until the Beneficial owners step
3. Exit the add BA flow to LHN
4. Go back to Settings > Workspace > Select Workspace > Bank account

## Expected Result:
The loading spinner should remain until the Continue with setup page is displayed

## Actual Result:
Moments before loading the Continue with setup page, an animation is briefly displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/32ca47c5-27a4-4816-94f4-c91b22422b41

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017959270d9dfdc29a</li>
        <li>Upwork Job ID: 1753160144224403456</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by ikevin127** [comment]
Very similar to https://github.com/Expensify/App/issues/34970 which was put on hold for VBBA refactor because as mentioned in https://github.com/Expensify/App/issues/34970#issuecomment-1906802535 as it doesn't block the users from taking actions.

**Comment by jliexpensify** [comment]
@rushatgabhane shall we put this on HOLD then?

**Comment by jliexpensify** [comment]
Bumping @rushatgabhane to answer my question please!

**Comment by rushatgabhane** [comment]
@jliexpensify yes I think it makes sense to hold on the refactor

**Comment by jliexpensify** [comment]
On hold

**Comment by jliexpensify** [comment]
On HOLD

**Comment by jliexpensify** [comment]
Ok, since we need to associate all bugs with a Wave/project now, I'm going to close this based off this [comment](https://github.com/Expensify/App/issues/35592#issuecomment-1922384210)

> it doesn't block users actions.
