### ISSUE TITLE
[HOLD for payment 2024-02-09] [$500] mWEb/Safari - Chat - Header not anchored at top in conversation when compose box is focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35591]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.3.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+1117ck@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Tap on FAB button >> Start Chat option
2. Start 1:1 DM with several messages already between users
3. Send messages (Note: Header section anchored at top)
4. Tap back button to go to LHN
5. Tap FAB button >> Start Chat with same user
6. Click in composer (Note : Header not anchored at top)

## Expected Result:
Header should be anchored at top in conversation when compose box is focused

## Actual Result:
Header not anchored at top in conversation when compose box is focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6480f936-0e14-4bf6-b724-c7069982d0fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd20f281b9038937</li>
        <li>Upwork Job ID: 1753198333098303488</li>
        <li>Last Price Increase: 2024-02-01</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28135933</li>
<li>mkhutornyi | Contributor | 28135934</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:



https://github.com/Expensify/App/assets/78819774/735e2f5f-f59e-453f-b5db-2d8afd309e83

**Comment by francoisl** [comment]
Possibly the same root cause as https://github.com/Expensify/App/issues/35593

**Comment by situchan** [comment]
@mkhutornyi's [proposal](https://github.com/Expensify/App/issues/35591#issuecomment-1922529052) looks good to me
cc: @francoisl 
🎀 👀 🎀 C+ reviewed

**Comment by francoisl** [comment]
Sweet, let's go with that. Are you able to work on a PR now @mkhutornyi

**Comment by CortneyOfstad** [comment]
No regressions listed, so getting this payment completed now 👍 

In the meantime, @situchan does this require a regression test? I don't think so, but wanted to confirm. Thanks!

**Comment by situchan** [comment]
@CortneyOfstad correct, no need. This was deploy blocker (caught during staging regression testing) so this test case already exists

**Comment by CortneyOfstad** [comment]
## Payment Summary

@mkhutornyi (contributor) — paid $500 via Upwork
@situchan (C+) — paid $500 via Upwork
