### ISSUE TITLE
[HOLD for payment 2024-02-09] [$500] mWeb/Safari - Chat - Extra blank space in header on tapping '+' icon in composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35593]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.3.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** kiatest.78+mass@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Tap FAB >> Start Chat
2. Navigate to 1:1 DM conversation
3. Enter a message with more than 2 lines until expand button is displayed in compose box
4. Tap on arrow button to expand composer
5. Tap on '+' icon (Note : blank space appears in header)
6. Dismiss the opened modal (Note : blank space in header)

## Expected Result:
No visual issues show in conversation history page. No blank space appears in header on tapping '+' icon in composer

## Actual Result:
Extra blank space in header on tapping '+' icon in composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/ffb1a501-a217-439a-a7ef-3f6ef5ef2219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c16c18ba938861e</li>
        <li>Upwork Job ID: 1753198356592246784</li>
        <li>Last Price Increase: 2024-02-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:

https://github.com/Expensify/App/assets/78819774/dcba9a78-5050-445c-8065-ed0603a676d5

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by francoisl** [comment]
It's also happening even without typing a message first, just by clicking the `+` button.

https://github.com/Expensify/App/assets/2229301/b247bdd1-697e-4a21-8707-3c8308a325aa

**Comment by francoisl** [comment]
I can't repro in dev on the `1.3.45-2` tag though for some reason, @arosiclair are you able to?

**Comment by francoisl** [comment]
A fix is being worked on as part of https://github.com/Expensify/App/issues/35591 already, no need for new contributions. Thanks!

**Comment by arosiclair** [comment]
Thanks for handling this @francoisl! Closing this out
