### ISSUE TITLE
[Awaiting Payment 20th Feb] [Wave Collect] [Account Settings] Update Profile page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35603]
Coming from [tracking issue for this initiative](https://github.com/Expensify/App/issues/32952).

Using the [Figma](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3125-183278&mode=design&t=XvlzBlUtMgk1sjil-11) final mocks, please update the Account Settings Profile page in the new ideal navigation layout to look like this:

![image](https://github.com/Expensify/App/assets/36083550/5191f7e7-45fa-4bb1-bf0c-2bc3c12eb942)

For help with anything unclear, please, post in wave8 room.

Please tag design team for a review on the PR before merging.

cc @trjExpensify @dannymcclain 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6b2f411bfdad74d</li>
        <li>Upwork Job ID: 1753492818731462656</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by filip-solecki** [comment]
Hi! I am Filip from Software Mansion and I will work on this issue!

**Comment by trjExpensify** [comment]
Awesome, assigning you @filip-solecki!

**Comment by mountiny** [comment]
$500 to @situchan

**Comment by trjExpensify** [comment]
Can this be closed out?

**Comment by JmillsExpensify** [comment]
Good question. I wanted to clarify that only @situchan should be compensated for this issue?

**Comment by mountiny** [comment]
Payment seems to have been done here https://github.com/Expensify/App/issues/36016 so i will close this one
