### ISSUE TITLE
[Wave8] [Account Settings] Update About page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35608]
Coming from [tracking issue for this initiative](https://github.com/Expensify/App/issues/32952).

Using the [Figma](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3125-183278&mode=design&t=XvlzBlUtMgk1sjil-11) final mocks, please update the Account Settings About page in the new ideal navigation layout to look like this:

![image](https://github.com/Expensify/App/assets/36083550/209b2cf4-eda8-446d-a5f3-1de0dd3dedfc)

For help with anything unclear, please, post in wave8 room.

Please tag design team for a review on the PR before merging.

cc @trjExpensify @dannymcclain

**Comment by mountiny** [comment]
Will be handled by SWM

**Comment by MitchExpensify** [comment]
Still on hold? @mountiny

**Comment by mountiny** [comment]
Nope its actually in staging already

**Comment by trjExpensify** [comment]
Consolidating on this issue for payment: https://github.com/Expensify/App/issues/35606
