### ISSUE TITLE
[HOLD for payment 2024-02-19] [Wave8] [Account Settings] Update the HeaderWithBackButton component to work well with the new design

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35609]
Coming from [tracking issue for this initiative](https://github.com/Expensify/App/issues/32952).

Using the [Figma](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3125-183278&mode=design&t=XvlzBlUtMgk1sjil-11) final mocks, please update the `HeaderWithBackButton` component so it can be reused well in the new design

![image](https://github.com/Expensify/App/assets/36083550/5191f7e7-45fa-4bb1-bf0c-2bc3c12eb942)

For help with anything unclear, please, post in wave8 room.

cc @trjExpensify @dannymcclain

**Comment by kosmydel** [comment]
Hey, I'm from SWM, and I will work on this.

**Comment by kosmydel** [comment]
The PR is ready for review. Can someone from the design team have a look at the results to verify padding, sizes, etc.? 

cc @trjExpensify, @shawnborton

**Comment by shawnborton** [comment]
Will take a look at the PR, cc @Expensify/design for visibility too. PR is here: https://github.com/Expensify/App/pull/35564

**Comment by mountiny** [comment]
Payment handled here https://github.com/Expensify/App/issues/35571
