### ISSUE TITLE
[HOLD for payment 2024-02-20] [Wave8] [Account Settings] Update Share Code page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35605]
Coming from [tracking issue for this initiative](https://github.com/Expensify/App/issues/32952).

Using the [Figma](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3125-183278&mode=design&t=XvlzBlUtMgk1sjil-11) final mocks, please update the Account Settings Share Code page in the new ideal navigation layout to look like this:

![image](https://github.com/Expensify/App/assets/16232057/05ef0a4a-0c54-4b11-b7bc-a450f750715e)

For help with anything unclear, please, post in wave8 room.

Please tag design team for a review on the PR before merging.

cc @trjExpensify @dannymcclain 

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by mountiny** [comment]
Will be handled by SWM

**Comment by filip-solecki** [comment]
Note: Won't apply rounded QRCode cause library does not support it.

**Comment by garrettmknight** [comment]
@sonialiap reassigning for payment since I'll be OOO when the date comes. Thanks!

**Comment by mountiny** [comment]
$500 to @situchan and no regression tests required

**Comment by sonialiap** [comment]
@situchan $500 - offer sent

Job https://www.upwork.com/ab/applicants/1759618198049271808/job-details

**Comment by sonialiap** [comment]
Paid ✔️
