### ISSUE TITLE
[Wave8] [Account Settings] Update Security page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35607]
Coming from [tracking issue for this initiative](https://github.com/Expensify/App/issues/32952).

Using the [Figma](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3125-183278&mode=design&t=XvlzBlUtMgk1sjil-11) final mocks, please update the Account Settings Security page in the new ideal navigation layout to look like this:

![image](https://github.com/Expensify/App/assets/16232057/0147eb5c-3c05-42a2-aea7-ec8f2502ada8)

For help with anything unclear, please, post in wave8 room.

Please tag design team for a review on the PR before merging.

cc @trjExpensify @dannymcclain

**Comment by mountiny** [comment]
Will be handled by SWM

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I will work on this issue!

**Comment by trjExpensify** [comment]
Updated the mock in the OP of this issue to replace the placeholder subheader copy!

**Comment by MitchExpensify** [comment]
Can we take this off hold @mountiny ?

**Comment by mountiny** [comment]
On staging

**Comment by trjExpensify** [comment]
Consolidating on this issue for payment: https://github.com/Expensify/App/issues/35606
