### ISSUE TITLE
[Awaiting Payment 20th Feb] [Wave8] [Account Settings] Update Preferences page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35606]
Coming from [tracking issue for this initiative](https://github.com/Expensify/App/issues/32952).

Using the [Figma](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3125-183278&mode=design&t=XvlzBlUtMgk1sjil-11) final mocks, please update the Account Settings Preferences page in the new ideal navigation layout to look like this:

![image](https://github.com/Expensify/App/assets/16232057/4406923a-228b-43bf-809a-b0d8f40a8318)

For help with anything unclear, please, post in wave8 room.

Please tag design team for a review on the PR before merging.

cc @trjExpensify @dannymcclain

**Comment by kosmydel** [comment]
Hey, I'm Kuba from Software Mansion and I will work on this issue.

The draft of the PR is already prepared, but we are waiting for the #35603 to be merged.

**Comment by trjExpensify** [comment]
Assigned you!

**Comment by trjExpensify** [comment]
I'll take the BZ on the main from @garrettmknight, given I'm closer to this.

**Comment by trjExpensify** [comment]
👋 Can we get marketing copy for the subheader intro on these pages where there's filler right now, please? Thanks! 

**Preferences**
![image](https://github.com/Expensify/App/assets/16232057/02311ca8-96fc-4c86-9c0e-9b4c726b39f1)

TRJ suggestion for consideration:
**_Customise your Expensify experience._**

**Security**
![image](https://github.com/Expensify/App/assets/16232057/706dcfe2-acf2-472b-905d-c7a14274e4a8)

TRJ suggestion for consideration: 
**_Enable 2FA to keep your account extra safe, or close your account if you no longer need it._**

**Share code**
![image](https://github.com/Expensify/App/assets/16232057/6ba099a2-827d-4344-8191-1488d31e7e7f)

TRJ's suggestion:
**_Invite people to Expensify by sharing a personalised QR code or link._**

**Comment by NickTooker** [comment]
> **Customize your Expensify account.** 
Is there a reason your suggestions was to use the word "experience"? I'm not sure we use that widely elsewhere so I think account may be better. 

> **Enable two-factor authentication to keep your account safe, or close your account if you no longer need it.**
Let's keep 'two factor authentication' consistent vs 2FA - let's remove extra, it doesn't add to the sentence here IMO. 

>Refer members to Expensify by sharing your personal QR code or referral link. 
I'm using Refer, members, and referral here to be consistent with language we've used elsewhere - please let me know if you disagree. 

@trjExpensify Let me know your thoughts.

**Comment by trjExpensify** [comment]
>**Customize your Expensify account.**
>Is there a reason your suggestions was to use the word "experience"? I'm not sure we use that widely elsewhere so I think account may be better.

No strong reason. I just thought "experience" sounded nicer as they kinda' fell into that for me. I.e your theme, LHN sorting logic, language. Though I guess there's a marketing preference toggle in there, so maybe it doesn't quite wholly fit. Not passionate! 

>**Enable two-factor authentication to keep your account safe, or close your account if you no longer need it.**
>Let's keep 'two factor authentication' consistent vs 2FA - let's remove extra, it doesn't add to the sentence here IMO.

Cool, I think this one is now pretty long -- especially for mobile. Perhaps we just cut the close account part? I.e 

**Enable two-factor authentication to keep your account safe.**

>Refer members to Expensify by sharing your personal QR code or referral link.
>I'm using Refer, members, and referral here to be consistent with language we've used elsewhere - please let me know if you disagree.

Nice edit. Maybe we avoid the "refer/referral" repetition though and switch the first word to "invite"? I.e 

**Invite members to Expensify by sharing your personal QR code or referral link.**

**Comment by NickTooker** [comment]
>Enable two-factor authentication to keep your account safe.
Perfect. Close account button speaks for itself. 

>Invite members to Expensify by sharing your personal QR code or referral link.
Good catch on refer/referral - this looks great to me.

**Comment by dannymcclain** [comment]
Love this! Should I update the mocks?! `:excited:`

Also can we get one more for **Test preferences**? Obviously this one is not _as_ important, but still. Maybe something simple like `Configure your account's test preferences`?

![CleanShot 2024-02-05 at 14 46 04@2x](https://github.com/Expensify/App/assets/7516624/c87fd280-7887-4d28-acb7-cfa8aa32ace4)

**Comment by NickTooker** [comment]
Yes, I'm not sure what else we would say here. I am fine with:

**>Configure your account's test preferences.**

**Comment by trjExpensify** [comment]
>Should I update the mocks?! :excited:

Do it! 

>Also can we get one more for Test preferences? Obviously this one is not as important, but still. Maybe something simple like Configure your account's test preferences?

Ah shit yeah, forgot about that one. These are only displayed on staging, so maybe the below? 🤔 

**Test preferences**
Settings to help debug and test the app on staging.

**Comment by NickTooker** [comment]
>These are only displayed on staging
Good catch! Agreed with your copy suggestion then.

**Comment by trjExpensify** [comment]
Here are all the Spanish translations for those: 

>Preferencias de la aplicación
>Personaliza tu cuenta de Expensify.

>Preferencias para tests
>Ajustes para ayudar a depurar y probar la aplicación en “staging”.

>Opciones de seguridad
>Activa la autenticación de dos factores para mantener tu cuenta segura.

>Tu código
>Invita a miembros a Expensify compartiendo tu código QR personal o enlace de invitación.

**Comment by mountiny** [comment]
On staging

**Comment by trjExpensify** [comment]
Okay, so payment time I think here. @s77rt you were the PR reviewer on this, right? Are these regression pings above bogus?

**Comment by s77rt** [comment]
@trjExpensify Yes I reviewed the PR. There were 2 bugs https://github.com/Expensify/App/issues/36444 and https://github.com/Expensify/App/pull/35672#discussion_r1488674313. 

Can you assign me here?

**Comment by trjExpensify** [comment]
Alright, I'm not going to reduce for those minor bugs given we rolled in a couple of other pages to that PR. So I'll send you an offer for $500 for the C+ review. Does that work for you?

**Comment by s77rt** [comment]
@trjExpensify Sounds great! Thank you!

**Comment by trjExpensify** [comment]
Perfect, offer sent!

**Comment by s77rt** [comment]
Accepted!

**Comment by trjExpensify** [comment]
Settled up!
