### ISSUE TITLE
[Awaiting Payment 21st Feb] [Wave Collect] [Account Settings] Update Wallet page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35604]
Coming from [tracking issue for this initiative](https://github.com/Expensify/App/issues/32952).

Using the [Figma](https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=3125-183278&mode=design&t=XvlzBlUtMgk1sjil-11) final mocks, please update the Account Settings Wallet page in the new ideal navigation layout to look like this:

![image](https://github.com/Expensify/App/assets/36083550/727d82f4-edf5-4ff2-af45-44aa212e5624)

For help with anything unclear, please, post in wave8 room.

Please tag design team for a review on the PR before merging.

cc @trjExpensify @dannymcclain

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by trjExpensify** [comment]
Nice, assigning you Jakub!

**Comment by trjExpensify** [comment]
Can this be closed out, @JmillsExpensify?

**Comment by mountiny** [comment]
Paid here closing https://github.com/Expensify/App/issues/36408
