### ISSUE TITLE
[Wave 8] [Ideal Nav] Incorrect or missing brick road indicators

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35612]
## Action Performed:
GBR (Green brick road) and RBR (Red brick road) are not working with the introduction of [Ideal Navigation](https://github.com/Expensify/App/pull/33280) (the new navigation structure). This is a widespread error. Please check major GBR and RBR flows. They're most likely broken.

Some example of GBR and RBR not working:
- Some GBR and RBR are incorrectly displayed on on Workspace Switcher when there is no report with GBR and RGR in the workspace. https://github.com/Expensify/App/pull/33280#issuecomment-1911253960
- RBR is incorrectly displayed on Profile Avatar https://github.com/Expensify/App/pull/33280#issuecomment-1880199054

## Expected Result:
GBR and RBR should work.

## Actual Result:
GBR and RBR are not working correctly.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

The links to videos are in the Action Performed section above.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
👋 Seems like there might be an issue with rows appearing unread as well: https://expensify.slack.com/archives/C036QM0SLJK/p1706888366992169

**Comment by alexpensify** [comment]
@hayata-suenaga - is this one ready to assign external or should it remain internal?

**Comment by hayata-suenaga** [comment]
I think there is someone from SWM already working on this. [Let me check](https://expensify.slack.com/archives/C036QM0SLJK/p1706916759691199).

**Comment by WojtekBoman** [comment]
Does this issue still occur? I've added many fixes to displaying RBR/GBR since reporting this issue

**Comment by hayata-suenaga** [comment]
On the staging after the feature branch (the big PR) was merged, several issues were reported about RBR/GBR.

@WojtekBoman did you merge any PR after the feature branch was merged?

**Comment by WojtekBoman** [comment]
I haven't merged any PRs since the feature branch was merged, but this issue https://github.com/Expensify/App/pull/33280#issuecomment-1880199054 should no longer appear :) I had fixed it, before the ideal nav was merged to the main. Additionally this PR https://github.com/Expensify/App/pull/35801/files contains the fix for displaying RBR/GBR.

**Comment by hayata-suenaga** [comment]
thank you for letting me know about the work you did 🙇 I apologize I wasn't aware of the previous fixes you worked on.

I had a chance to try reproducing the the issue. When there is an money request that needs fix, I didn't see the RBR on the workspace list item nor on the chat list item.
<img width="883" alt="Screenshot 2024-02-06 at 9 44 51 AM 1" src="https://github.com/Expensify/App/assets/98560306/3ef14518-8e99-40fe-b220-2fc38356bd59">

**Comment by s77rt** [comment]
Tested this just now and it seems working as expected.

**Comment by hayata-suenaga** [comment]
nice! I'll close this issue for now. Let's re-open this if the same issue appears again.
