### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] Android – Image is reduced for a moment when quickly slide forward/back images using arrows

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35615]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4265112
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Log in
3. Navigate to a conversation that has 5 or more image attachments in it's history
4. Click on one of the attachments to open the preview
5. Click on the forward or back arrow to navigate through the conversation attachments quickly

## Expected Result:
The image size is normal when quickly slide forward/back images using the arrows

## Actual Result:
The image is reduced for a moment when quickly slide forward/back images using the arrows

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a99e901f-5fa3-4580-8113-aa288435f338

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019fd6243b644a1821</li>
        <li>Upwork Job ID: 1753212539309678592</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment]
Will work on review today

**Comment by johncschuster** [comment]
Bumping for Melvin

**Comment by abdulrahuman5196** [comment]
Sorry for the delay. Working on review now

**Comment by abdulrahuman5196** [comment]
@tienifr From the proposal here https://github.com/Expensify/App/issues/35615#issuecomment-1922853744,
To summarize, `we show the image before the image size is determined by the system, causing it to show in a fallback size.
The suggestion is to not show the image and show the loading indicator`. 

@johncschuster This expectation seems fine IMO, But I would like to confirm the expectation.

**Comment by abdulrahuman5196** [comment]
Followup question to @tienifr 
Is there a way to re-use the image sizes which we got previously?

**Comment by abdulrahuman5196** [comment]
>Are you suggesting that we shouldn't show an image at all when a user is in image preview mode and swiping through images, and instead show a loading indicator?

Not a suggestion. I would put it as a question instead.

@tienifr proposal here https://github.com/Expensify/App/issues/35615#issuecomment-1922853744 targets to do that. My question would be, `Is it good enough from UX perspective?` or should we try out for more optimized fix(which would be reach out for other proposals)?

**Comment by johncschuster** [comment]
@abdulrahuman5196 

> @tienifr proposal here [#35615 (comment)](https://github.com/Expensify/App/issues/35615#issuecomment-1922853744) targets to do, also explained in detail here [#35615 (comment)](https://github.com/Expensify/App/issues/35615#issuecomment-1946404643). My question would be, **Is it good enough from UX perspective?** or should we try out for more optimized fix(which would be reach out for other proposals)?

Fair question. I think I'd like to get some ideas from our @Expensify/design on the UX of this proposal.

@Expensify/design, we're trying to figure out the best way to address how images load when a user scrolls through a carousel of images in NewDot. There are a few suggestions (starting [here](https://github.com/Expensify/App/issues/35615#issuecomment-1938209223)) on how we can address this, but these might not consider the overall user experience. I'd love your thoughts!

**Comment by dubielzyk-expensify** [comment]
I probably prefer us showing a loading indicator until we can properly display the images. I don't feel very strongly though, but the less "jumpy" we can make the UI, the better.

Unless we can somehow load all the image sizes as a request on the very first image, instead of as you scroll through the carousel?

Keen for rest of @Expensify/design opinions.

**Comment by shawnborton** [comment]
Yup, that makes sense to me. I basically agree with this comment too:

> The suggestion is to not show the small image initially. Instead, it will only show loading indicator while the image is loading (which is brief), then after the image is loaded and the size is known, the full image will be shown with the correct size from the start (rather than showing image with incorrect size first then change to correct size as currently)

**Comment by dannymcclain** [comment]
Yeah that sounds good to me too. Agree with Jon that the less jumpy we can make the UI, the better.

**Comment by johncschuster** [comment]
Awesome. Thanks for your feedback, team!

**Comment by johncschuster** [comment]
@abdulrahuman5196 can you take a look at the comments above? Based on the design team's feedback, it sounds like we would go with @tienifr's proposal. Do you agree?

**Comment by abdulrahuman5196** [comment]
Hi, Reviewing now.

**Comment by abdulrahuman5196** [comment]
@tienifr I noticed that we are getting the contentSize from `cachedImageDimensions` which is basically caching the image dimensions. Then how this issue happening even if we swipe for the second time without exiting the attachment corousel?

https://github.com/Expensify/App/blob/7120be24bbcce3c32ff3e257a2690aa27af00eaa/src/components/Lightbox/index.tsx#L103

**Comment by johncschuster** [comment]
@mvtglobally can you share a video of what you saw instead? Was the image not reduced? Did you see the loading pattern?

**Comment by abdulrahuman5196** [comment]
Nope I still see the issue

**Comment by abdulrahuman5196** [comment]
@tienifr Thanks for the explanation here https://github.com/Expensify/App/issues/35615#issuecomment-1963996981. I think it fine to leave the number of lighboxes to be as it is for now to avoid any performance regressions.

**Comment by abdulrahuman5196** [comment]
Given the design discussions we had. @tienifr 's proposal here https://github.com/Expensify/App/issues/35615#issuecomment-1922853744 to show loading indicator instead of fallbackSize looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by iwiznia** [comment]
Hmmmm but is the proposal from @tienifr making the LoadingIndicator show? I see you said:
> the LoadingIndicator will show [here](https://github.com/Expensify/App/blob/d5eba656251269b238797817df3cf84800b0039a/src/components/Lightbox/index.tsx#L209) so the UX is smooth.

So, maybe how this works is like this?
- Image is loading (loading indicator shows)
- Image loaded, but dimensions not determined yet (loading indicator is not there and image neither)
- Image loaded, dimensions computed (image shows properly)

**Comment by iwiznia** [comment]
@tienifr [bump](https://github.com/Expensify/App/issues/35615#issuecomment-1971295462)

**Comment by abdulrahuman5196** [comment]
> Hmmmm but is the proposal from @tienifr making the LoadingIndicator show? I see you said:
> 
> > the LoadingIndicator will show [here](https://github.com/Expensify/App/blob/d5eba656251269b238797817df3cf84800b0039a/src/components/Lightbox/index.tsx#L209) so the UX is smooth.
> 
> So, maybe how this works is like this?
> 
>     * Image is loading (loading indicator shows)
> 
>     * Image loaded, but dimensions not determined yet (loading indicator is not there and image is neither as its opacity is 0)
> 
>     * Image loaded, dimensions computed (image shows properly)

@iwiznia  I don't exactly understand the question here. But as far as the usecase goes, `we will show the image only after the image is loaded and the dimensions are computed. Until then loader will be shown`.
Hope it clarifies.

**Comment by iwiznia** [comment]
> Currently: loading indicator shows and the image with the wrong size is shown briefly

Ahhh got it!

**Comment by johncschuster** [comment]
Payment has been issued and regression test issue has been created. Closing! 🎉
