### ISSUE TITLE
[Wave Collect] [Ideal Nav] Navigation among different Workspace Settings pages is broken

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35611]
## Action Performed:
1. Test this on a browser
2. Go to Workspace Settings page (make sure that you’re on a workspace in which you’re an admin so that you have enough settings items to navigate through).
3. Click through different setting items (watch the video)
4. Shrink the screen
5. Press the browser back button several times.

## Expected Result:
The back button should take you straight back to the Settings page where the settings items are listed.

## Actual Result:
Clicking through the back button takes you to different settings item page previously visited.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/pull/33280#issuecomment-1880188621

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112c8e18133890b6e</li>
        <li>Upwork Job ID: 1763217867286740992</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
Might be fixed in this GH issue. I'm [confirming this](https://github.com/Expensify/App/issues/35626#issuecomment-1924334704).

**Comment by sakluger** [comment]
@hayata-suenaga I didn't see any response on the other issue. Did you find out if they are related? And if they are, should we add a HOLD on this issue, or just close it out?

**Comment by hayata-suenaga** [comment]
> I didn't see any response on the other issue. Did you find out if they are related?

asking directly on [Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1707179200434319)

> And if they are, should we add a HOLD on this issue, or just close it out?

is the issues turn out to be related, we can close this issue in favor of [this one](https://github.com/Expensify/App/issues/35626).

Let me get back to you once I get a response 👍

**Comment by adamgrzybowski** [comment]
Hey @hayata-suenaga, this one won't be solved by the goback workaround and may be tricky. I'll take a look at it when I have some free time. But maybe in the meantime, we could change it to weekly?

**Comment by hayata-suenaga** [comment]
Adam is going to handle this issue when they have time

**Comment by hayata-suenaga** [comment]
Adam is OOO and they will work on this once they're back. This issue will also take time to fix.

**Comment by sakluger** [comment]
Since it sounds like this will take a bit more time, I'm going to move this to weekly to avoid it going overdue.

**Comment by hayata-suenaga** [comment]
It think it's already weekly 👍

**Comment by hayata-suenaga** [comment]
@adamgrzybowski is going to work on this. because the solution is a little bit tricky, it might take some time. Melvin, please chill 🙇

**Comment by sakluger** [comment]
Switching back to weekly. Let's see if Melvin lets it stay that way. 😂

**Comment by hayata-suenaga** [comment]
@adamgrzybowski is going to on this when they have time

**Comment by hayata-suenaga** [comment]
@WojtekBoman Let me know if https://github.com/Expensify/App/issues/37359 is related

**Comment by hayata-suenaga** [comment]
@adamgrzybowski or @WojtekBoman is going to work on this.

**Comment by WojtekBoman** [comment]
I'm investigating that :)

**Comment by trjExpensify** [comment]
What are the next steps here? Is this on hold for the issue to refactor goBack logic?

**Comment by hayata-suenaga** [comment]
I re-tested this, and I was not able to repro. @WojtekBoman, could you double confirm this? If you can't also repro, we can close this issue.

**Comment by trjExpensify** [comment]
Cool, @WojtekBoman want to confirm and we can close?

**Comment by WojtekBoman** [comment]
Unfortunately, it seems to be still present:

https://github.com/Expensify/App/assets/47774969/53768680-c3a1-492d-b526-fa827c6a6da3

We've spent some time on investigation this issue with @adamgrzybowski and it's a bit complex to fix, because we can't directly modify browser history. Fixing this issue might require many changes in the logic that works fine, and this case shouldn't be common for users. We had to switch to work on the new search tab and I'm wondering what should we do with this task, because as I mentioned it's not a common issue and handling that might require some interference with browser history and I'm not sure if we want to make such deep changes to deal with that.

**Comment by trjExpensify** [comment]
Is this specifically a bug on Web when you're shrinking your screen link that or was that just to replicate a native mobile experience?

**Comment by hayata-suenaga** [comment]
@trjExpensify I believe this is specific to the web.

I believe that we don't have to spend time on fixing this. The fix might also further complicates the navigation logic that is already hard to understand. I'd say let's close this issue, but I'll wait for @trjExpensify's response.

**Comment by trjExpensify** [comment]
Okay, then yeah.. let's close this if it's not simulating mobile!
