### ISSUE TITLE
[$500] IOU - 3-dot menu is not stable when open ( keyboard opens when tap 3-dot menu) detailed chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35616]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Tap FAB> Request money> Manual> Finish the request flow
2. Navigate to detailed IOU page
3. Tap 3-dot menu

## Expected Result:
Dropdown menu should open with no visual issues

## Actual Result:
 3-dot menu is not stable.
When tap on 3-dot menu keyboard opens and push the menu up

## Workaround:
Unknonw

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ce1a4fa1-7c3c-4789-aabf-5646821a9852

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121bcb39044303abb</li>
        <li>Upwork Job ID: 1753213152702603264</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by joekaufmanexpensify** [comment]
This is working fine for me. Closing as this doesn't seem to be reproducible!

https://github.com/Expensify/App/assets/54866469/cd783080-5bd9-44fd-8759-31f60d577519
