### ISSUE TITLE
[HOLD for payment 2024-02-14] [Wave 8] [Ideal Nav] Big New Workspace button doesn't work

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35621]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706831528469869

## Action Performed:
1. Create a new account (to test this, the account cannot have any existing workspace. that's why it's recommended you create a new account).
2. Bottom tab -> 🔧 Settings -> Workspaces
3. Click the big `New Workspace` button that appear middle of the content pane

## Expected Result:
A new workspace should be created.

## Actual Result:
Nothing happens.

## Workaround:
The user can click the small `New workspace` button at the top-right color of the Settings page

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on it!

**Comment by cdOut** [comment]
Hello, I will be looking into this issue.

**Comment by hayata-suenaga** [comment]
hi @cdOut 👋 are you from SWM?

this issue should be fixed with [this PR](https://github.com/Expensify/App/pull/35622) which was merged to main recently 👍

**Comment by cdOut** [comment]
@hayata-suenaga Yes, I am from SWM. Let me know whether this still persists and whether I should still work on this.

**Comment by hayata-suenaga** [comment]
I'll let you know if the issue still persists after deployment

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/33280
- The offending PR has been commented on: https://github.com/Expensify/App/pull/33280#discussion_r1483289903
- A discussion in #expensify-bugs has been started: n/a
- Determine if we should create a regression test for this bug: No

**Comment by s77rt** [comment]
This can be closed
