### ISSUE TITLE
[Wave 8] [Ideal Nav] Three not-found pages appear when a non-existing workspace is accessed with an invite link

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35623]
## Action Performed:
1. On a browser, go to https://dev.new.expensify.com:8082/workspace/0680EF3C70411F57/invite
2. 

## Expected Result:
One single Not-Found page `Hmm... it's not here` should appear

## Actual Result:
Three Not-Found pages appear

![Screenshot 2024-02-01 at 6 44 52 PM](https://github.com/Expensify/App/assets/98560306/7c6c44d6-c65d-4e14-bf4c-22b18d698a7f)

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Attached above

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment]
@Expensify/design could you confirm what the UI should be when a non-existing workspace is accessed?

Please refer to the current UI in the issue description.

**Comment by shawnborton** [comment]
I think the idea here was to just show one "not found" view that spans across the entire app, not three distinct sections. Is that possible? cc @trjExpensify

**Comment by trjExpensify** [comment]
Right, we created an issue here: https://github.com/Expensify/App/issues/34234

@kosmydel are you still needing to work on this one?

**Comment by trjExpensify** [comment]
Light: 

![image](https://github.com/Expensify/App/assets/2319350/c18c452b-b99e-4bdf-a45a-343e76d1511c)

Dark: 

<img width="1512" alt="Screenshot 2024-01-15 at 10 20 59" src="https://github.com/Expensify/App/assets/104823336/2f3c24b9-1fc6-4873-9923-af234482b49e">

**Comment by hayata-suenaga** [comment]
ah I remembered that this was discussed before, but I thought the work is already done and that this is another regression.

In this case, we can combine this one with `[Wave 8] [Ideal Nav] Improve "Hmm... it's not there" being duplicated across two content areas`.

Closing this issue now.
