### ISSUE TITLE
[$500] Chat's received in DM above chat I already sent

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706840985963419

## Action Performed:

1. Send chat in DM
2. Have other person reply promptly

## Expected Result:
Chat that's received to show below the chat you already sent
## Actual Result:
Chat that's received after the one you posted shows above the chat you sent

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/781fc9f2-4f4c-4d9a-997f-a856b382c7e1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163764ffee80f71ee</li>
        <li>Upwork Job ID: 1753258921807683584</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
It could be expected behaviour, I find it a bit annoying though cuz I can't trust that the last message showing is the most recent

At end of vid you can see it between 4 and 5 being displayed

https://github.com/Expensify/App/assets/22508304/a111eac5-e63c-4cef-8e4f-fc29e2763a04

**Comment by c3024** [comment]
Yes, I too think this is expected behaviour. Timestamps are based on the time a user sends a message. So even though the server response is late, the report actions are sorted based on these timestamps.

**Comment by lschurr** [comment]
Cool, sounds like we can close this one.
