### ISSUE TITLE
[$500] [Wave 8] [Ideal Nav] Dependency circle warnings on iOS

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35633]
## Action Performed:
Run the iOS app on emulator and watch the terminal outputs.

## Expected Result:
No warning

## Actual Result:
Bunch of dependency circle errors.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Screenshot -> https://github.com/Expensify/App/pull/33280#issuecomment-1922305985

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

@situchan discovered the error

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d80d497235767d27</li>
        <li>Upwork Job ID: 1753450293276995584</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28137411</li>
</ul></li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
Per [this conversation](https://expensify.slack.com/archives/C036QM0SLJK/p1706888519497419?thread_ts=1706886543.047379&cid=C036QM0SLJK), making this issue external

**Comment by situchan** [comment]
As a reporter, happy to take this as C+

**Comment by hayata-suenaga** [comment]
I apologize for the notification @cubuspl42, but @situchan reported the issue, so I'm assigning this issue to them. 🙇

**Comment by hayata-suenaga** [comment]
[asking for proposals in #open-source-channel](https://expensify.slack.com/archives/C01GTK53T8Q/p1707155785831589)

**Comment by hayata-suenaga** [comment]
still accepting proposals

**Comment by hayata-suenaga** [comment]
I'll ask if any SWM engineer can take on this as we don't have proposals from contributors.

**Comment by hayata-suenaga** [comment]
[closing this issue per this discussion](https://expensify.slack.com/archives/C036QM0SLJK/p1707756580019289?thread_ts=1707756425.083089&cid=C036QM0SLJK)
