### ISSUE TITLE
[Awaiting Payment] [Wave Collect] [Ideal Nav] App crashes when navigating to Settings/Overview page of a non-existent workspace

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35631]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. On a browser, go to the Settings/Overview page of a workspace you don't have access to. You can use [this example URL](https://dev.new.expensify.com:8082/workspace/CFA2F9EEE37B11139C/overview).

## Expected Result:
Not-found page should appear

## Actual Result:
The website crashes
<img width="500" alt="Screenshot 2024-02-01 at 9 05 00 PM" src="https://github.com/Expensify/App/assets/98560306/90b3b835-3745-4092-8cf7-b06463bf240f">

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Screenshot attached above

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
What does "existent" workspace mean? A workspace you don't have access to or literally just a made up URL after `/workspace`?

**Comment by hayata-suenaga** [comment]
@trjExpensify good question! both workspaces you don't have an access to and made-up workspaces

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on it :)

**Comment by trjExpensify** [comment]
Assigned you @WojtekBoman!

**Comment by trjExpensify** [comment]
>@trjExpensify good question! both workspaces you don't have an access to and made-up workspaces

Okay, so I can't reproduce this one on staging when I modify the workspaceID to something that doesn't exist: 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/6df36618-4ab9-48be-b086-2eeaf58d6d62">

**Comment by trjExpensify** [comment]
Are there more conditions required than that? 🤔

**Comment by hayata-suenaga** [comment]
yes I confirmed the issue is no longer present. @WojtekBoman do you think we still need you PR?

![Screenshot 2024-02-05 at 4 40 28 PM](https://github.com/Expensify/App/assets/98560306/4e2efdff-bc83-4a8c-8aff-82037391b4c5)

**Comment by hayata-suenaga** [comment]
@trjExpensify thank you for checking this 🙇 

I have confirmed that the issue doesn't occur when accessing a non-existent report. The crash only happens when you try to access an existing report to which you don't have access.

**Comment by trjExpensify** [comment]
Existing report? I thought we were talking about workspaces here? 🤔

**Comment by hayata-suenaga** [comment]
sorry I meant workspace 😓

**Comment by trjExpensify** [comment]
Got it, okay. Looks like we have a PR up for this.

**Comment by trjExpensify** [comment]
Assigning @ntdiary as the C+

**Comment by trjExpensify** [comment]
@JmillsExpensify this is ready for payment.

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by JmillsExpensify** [comment]
Payment summary: $500 for @ntdiary for pr review and testing.

**Comment by JmillsExpensify** [comment]
Contract sent via upwork.

**Comment by JmillsExpensify** [comment]
Payment made
