### ISSUE TITLE
Help @staszekscp with access to Push Notification configurations

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#35653]
Help @staszekscp with access to Push Notification configurations. 

- [x] Add him to the OldDot apple development team, so I could build the app on physical devices
    - [x] Do the same for OldApp AdHoc 
    - [x] Attempt to resole AdHoc cert issue
- [x] Provide use cases for push notifications in NewDot, and which deep-links are going to be used
- [x] Modify backend so that push notifications from NewDot (triggered eg by chat messages) could also be shown for OldDot Hybrid if the userId matches
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb1d504c4c27249f</li>
        <li>Upwork Job ID: 1753372386828328960</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by Julesssss** [comment]
I used our internal S.O to get @staszekscp onto our internal team. 🤞 everything went well

**Comment by Julesssss** [comment]
Today I shared additional provisioning profiles that should allow Mariusz to build OldDot AdHoc

**Comment by Julesssss** [comment]
Hey @AndrewGable, I'm trying to help @staszekscp build the AdHoc OldDot app to speed up his Hybrid notification testing:

> The worst thing is that right now I cannot get push notifications at all on debug iOS... ...The solution here could be building an adhoc app, but I would need a provisioning profile with my apple developer account

I provided the AdHoc provisioning profile, but I believe his certificate would need to be `Apple Distribution` instead of the current `Apple Development`. But, I assume we shouldn't be giving that permission to external contributors. Even our internal certificates are for development only. 

I'm also unfamiliar with the OldDot AdHoc capability. Is the plan to migrate NewDot AdHoc builds to this Capability, and delegate cert signing to a CI?

**Comment by Julesssss** [comment]
Today I submitted [a PR](https://github.com/Expensify/Web-Expensify/pull/40906) that duplicates NewDot notifications to OldDot for a small list of accounts provided by @staszekscp. 

Here's a[ cleanup issue](https://github.com/Expensify/Expensify/issues/369953) to remind us to remove this code.

**Comment by AndrewGable** [comment]
I think I fixed this, it was a configuration issue.

**Comment by Julesssss** [comment]
> Provide use cases for push notifications in NewDot, and which deep-links are going to be used

Currently we only send Aitship push notifications for report comments. These are mostly basic messages, but there are a couple of addition badly formatted actions that take place: 

I'm sharing them here for reference. I'm creating issues to improve these, but I think they just need to deep link users to the relevant chat.

**IOU Request/Paid**
No notifications

**Invited or removed user from room**
![Screenshot_20240220_144023](https://github.com/Expensify/App/assets/10736861/3bcbba29-3fd9-4e6d-a34a-b80b07850ebf)

**Room name was changed**
![Screenshot_20240220_144228](https://github.com/Expensify/App/assets/10736861/a19ab0ca-2d35-445d-a479-55065c22e761)

**Comment by Julesssss** [comment]
Closing this, access has been provided for both SWM devs, and all requested information has been shared
