### ISSUE TITLE
[$500] Sign In - Open in app pop-up not displayed when user successfully Signed In on public room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be signed out
1. Open public room deeplink https://staging.new.expensify.com/r/5408450846930023
2. Click in Sign In button
3. Sign In with valid email

## Expected Result:
Pop-up "Open in app" should be displayed

## Actual Result:
"Open in app" pop-up not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e46f7224-660b-4adb-9bab-b15947ca4e0e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b45ef5fa722b5aec</li>
        <li>Upwork Job ID: 1753369448122564608</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28144604</li>
<li>dukenv0307 | Contributor | 28144605</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb

**Comment by trjExpensify** [comment]
Yeah, that's a fair point. It's unclear what that relates to unless you're familiar with the app! @izarutskaya can we make sure to keep an eye on making the action steps accessible for everyone to understand? I _think_ what you're referring to here is the desktop app? 

@shahinyan11 if you install our macOS desktop app, when you open a URL on Web, there's usually a centered modal asking if you want to open the (desktop) app instead.  

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/c311b2a8-6e21-4c47-8fe9-afedbf2ccf26">

You can download the macOS desktop app from this page: https://new.expensify.com/settings/about/app-download-links

**Comment by marcochavezf** [comment]
Thanks for the review @Ollyws, I agree with the solution. Assigning @dukenv0307 🚀

**Comment by trjExpensify** [comment]
Nice! Confirming the payment summary as follows: 

- @dukenv0307 $500 for the fix - paid! 
- @Ollyws $500 for the C+ review - you need to [accept the offer](https://www.upwork.com/nx/wm/offer/28144604).

**Comment by trjExpensify** [comment]
Perfect, settled up. Closing!
