### ISSUE TITLE
[$500]  Chat - After leaving thread and going back user redirected to chat instead of LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35669]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35563
## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Send a message
4. Start a thread and then leave it
5. Tap the back icon

## Expected Result:
User is redirected to the LHN

## Actual Result:
User returns to the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a5d3032a-2efc-417d-b10a-466c4165c723

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f91d520c5e7912a6</li>
        <li>Upwork Job ID: 1753421327794864128</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Raised it in [#vip-vsb](https://expensify.slack.com/archives/C066HJM2CAZ/p1706914097206269).

**Comment by hayata-suenaga** [comment]
this issue should be handled in [this issue](https://github.com/Expensify/App/issues/35626)
