### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Expense - "Approved" is not present in Amount in request details page for approved expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.45-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4264387
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are part of Collect workspace
- Admin is also approver in the Collect workspace

1. [Employee] Create a manual request in the workspace chat
2. [Employee] Submit the report
3. [Admin] Go to workspace chat with employee
4. [Admin] Click on the request preview
5. [Admin] Click on the dropdown button next to the green button on the top right > Approve
6. [Admin] Approve the report
7. [Admin] Click on the expense preview

## Expected Result:
"Approved" will be present next to "Amount • Cash" in request details page

## Actual Result:
"Approved" is not present next to "Amount • Cash" in request details page, while it is present next to "Cash" in expense preview in expense report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6afb6b9f-b44c-4ecc-a3f7-4ff66c3707d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afb3d30cf9a1eb24</li>
        <li>Upwork Job ID: 1755300910406561792</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave7
CC @RachCHopkins

**Comment by sakluger** [comment]
Asked in #wave7 if it's connected to that wave.

**Comment by marcochavezf** [comment]
Hi @GandalfGwaihir, thanks for the proposal but the extra conditionals don't solve the issue. I noticed we're getting the status and state from the wrong report (transaction report) instead of the money request.

**Comment by sakluger** [comment]
Sent an offer to @eVoloshchak via Upwork for the PR review.

**Comment by eVoloshchak** [comment]
> Sent an offer to @eVoloshchak via Upwork for the PR review.

@sakluger, no need for Upwork, I get paid via NewDot
I'll request the payment for this on 20th (assuming no regressions arise)

**Comment by sakluger** [comment]
Thanks for clarifying @eVoloshchak. Our spreadsheet said that you didn't do NewDot requests, sorry about that.

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28976
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28976/files#r1495989726
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed here, this is a pretty minor bug

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

Preconditions:

1. Admin and employee are part of a Collect workspace
2. Admin is also approver in the Collect workspace

Test steps:

1. [Employee] Create a manual request in the workspace chat
2. [Employee] Submit the report
3. [Admin] Go to workspace chat with employee
4. [Admin] Click on the request preview
5. [Admin] Click on the dropdown button next to the green button on the top right > Approve
6. [Admin] Approve the report
7. [Admin] Click on the expense preview
8. [Admin] Verify the text "Approved" appears in the description (i.e. `Amount*Cash*Approved`)

**Do we agree 👍 or 👎**

**Comment by sakluger** [comment]
The test steps look good! You're all set to request payment via NewDot.

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary above.
