### ISSUE TITLE
[Awaiting Payment March 4th] [$150] [Wave 8] [Ideal Nav] Change the global create and DM create tooltips to read `Create`

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#35677]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1706889045249449

## Action Performed:
1. Open NewDot on web/desktop
2. Hover over the `+` button in the bottom tab bar
3. Observe the tooltip reads  `New`
4. Click into a chat 
5. Hover over the `+` button to the left of the composer 
6. Observe the tooltip reads `Actions`

## Expected Result:
Standardise on displaying the tooltip in both places as: `Create`

## Actual Result:
As described above, we have an inconsistency where we use `New` and `Actions`.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="371" alt="image" src="https://github.com/Expensify/App/assets/16232057/adb9581b-2dcf-40af-9518-c2900bce5abb">

<img width="823" alt="image" src="https://github.com/Expensify/App/assets/16232057/bb223f37-cc4d-475e-bd1b-4474cf9309c0">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121d4f02863128339</li>
        <li>Upwork Job ID: 1753465553597399040</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28149278</li>
<li>esh-g | Contributor | 28149279</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment]
Is this open for anyone?

**Comment by esh-g** [comment]
I'm available for this

**Comment by trjExpensify** [comment]
Yeah, open to anyone. I dropped the price because it's so simple. :)

**Comment by trjExpensify** [comment]
I've asked internally about the Spanish translation [here](https://expensify.slack.com/archives/C21FRDWCV/p1707139191599949).

**Comment by trjExpensify** [comment]
Spanish translation is confirmed to be: `Crear`

**Comment by trjExpensify** [comment]
@youssef-lr can you give this proposal a secondary look so we can move it on? Thanks!

**Comment by youssef-lr** [comment]
Done @trjExpensify

**Comment by zanyrenney** [comment]
Can't we close this if merged? @trjExpensify

**Comment by zanyrenney** [comment]
Or payouts still needed?

**Comment by trjExpensify** [comment]
PR is only on staging, so next steps:: 

- PR needs to go to production
- 7 day regression period will kick in 
- All being well, we'll pay out on tat day and close the issue.

**Comment by trjExpensify** [comment]
Right, we've had a deploy freeze because of the earnings call.

**Comment by trjExpensify** [comment]
PR is now on production as of yesterday. Adjusting the title to reflect the 7 day hold.

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $150 to @esh-g for the fix 
- $150 to @aimane-chnaif for the C+ review

Paid out both, closing!
