### ISSUE TITLE
Sections - Cards on the right hand page are left aligned instead of centered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal  Team
**Slack conversation:**

## Action Performed:
1. Go to Settings from the top
2. Go to Wallet
3. Go to Share code
4. Go to Settings from the bottom
5. Go to any workspace
6. Go to Bills, Reimbursements etc

## Expected Result:
The cards on the right hand page are centered

## Actual Result:
The cards on the right hand page are left aligned

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/118e4870-75a0-484a-9872-b17a347ddc90

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by bondydaa** [comment]
hmm @Expensify/design anyone familiar with recent changes for these types of elements? Even if not can you help confirm how they should look? I'm guessing centered aligned?

**Comment by bondydaa** [comment]
if I had to guess it might be from this big PR https://github.com/Expensify/App/pull/33280/files#diff-701113bd02bdc9f8c671df93b0a5a0d2dadb520ae378674c8cfa956d1eb2daff but I only say that b/c I see it touches a lot of styles (I haven't looked through all PRs from the deploy checklist either).

**Comment by s77rt** [comment]
I think this is by design not a bug

**Comment by shawnborton** [comment]
Correct, not a bug! This is part of the #ideal-nav design doc
