### ISSUE TITLE
[$500] Assigned cards tile uses cardholderName- lastFourDigits instead of bankName - lastFourDigits

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.36-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @miljakljajic 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706893917890069

## Action Performed:

1. Assign a third party card feed to a test account in OldDot following these steps:
2. Navigate to Settings > Domains > Import Card to add the test card feed
3. Search ‘Discover’
4. Enter the login ‘expensifydemo’ and the password ‘#USD’
5. Assign the single available card to your test account
6. Navigate to NewDot and go to your Wallet > Assigned cards

## Expected result: 
You should see the bank logo of the assigned card labelled bankName - lastFourDigits
## Actual result: 
You will see the bank logo of the assigned card labelled
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-02-02 at 12 40 12 PM](https://github.com/Expensify/App/assets/38435837/fc4de7d4-778e-4284-9f2d-2fd47696f29d)

![image (4)](https://github.com/Expensify/App/assets/38435837/1eab80e1-cd3f-4f9a-8b8a-bb92c261ce26)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cde3f6bc755e7553</li>
        <li>Upwork Job ID: 1753474213344817152</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 28144685</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Krishna2323</details>

**Comment by rushatgabhane** [comment]
🎀👀🎀 

seems like a straightforward fix

**Comment by marcochavezf** [comment]
Assigning @Krishna2323 🚀 , thanks for the review @rushatgabhane

**Comment by rushatgabhane** [comment]
@Krishna2323 let me add some card in my account to test

**Comment by godofoutcasts94** [comment]
Please review this [Proposal](https://github.com/Expensify/App/issues/36869#issuecomment-1957811947) as it fixes the above issue.

**Comment by rushatgabhane** [comment]
discussion here https://expensify.slack.com/archives/C01GTK53T8Q/p1708558924151619

**Comment by rushatgabhane** [comment]
@bfitzexpensify could you please add payment summary, thanks 🙇

**Comment by rushatgabhane** [comment]
money request here - https://staging.new.expensify.com/r/3704912471626768

**Comment by bfitzexpensify** [comment]
Thanks for the heads up @rushatgabhane 

Payment summary:

Contributor: @Krishna2323 to be paid $500 via Upwork ✅ 
C+: @rushatgabhane to be paid $500 via manual request

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane based on summary.
