### ISSUE TITLE
[HOLD for payment 2024-02-26] [$250] Workspace switcher - No tooltip when hovering over + button next to Workspaces

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35683]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open workspace switcher
2. Hover over + button next to Workspaces

## Expected Result:
Tooltip will show up

## Actual Result:
No tooltip when hovering over + button next to Workspaces

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d6703e39-ae74-457b-a153-39ed75971f0d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb8f425174a88fd1</li>
        <li>Upwork Job ID: 1753484365389684736</li>
        <li>Last Price Increase: 2024-02-02</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 28142987</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment]
I don't think this is a blocker. Added to the project board and gonna follow the regular process.

**Comment by rushatgabhane** [comment]
Going with with @neonbhai's proposal because they're first 🎀 👀 🎀 
https://github.com/Expensify/App/issues/35683#issuecomment-1924391714

**Comment by rushatgabhane** [comment]
@slafortune could you please attach payment summary for this issue, thanks  🙇

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment]
money request here - https://staging.new.expensify.com/r/2759990158891514

**Comment by slafortune** [comment]
Waiting on Check list to be complete - 

- @rushatgabhane requires payment through NewDot Manual Requests - $250
- @neonbhai pay $250 via Upworks - PAID

**Comment by slafortune** [comment]
Waiting on @rushatgabhane to complete the checklist

**Comment by luacmartins** [comment]
same as above

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane based on [this summary](https://github.com/Expensify/App/issues/35683#issuecomment-1964598701).

**Comment by slafortune** [comment]
@rushatgabhane will you be able to complete the checklist today?  Seems like it will be pretty straightforward?

**Comment by luacmartins** [comment]
Still waiting on payments

**Comment by slafortune** [comment]
@rushatgabhane needs to complete the checklist -payments have all been made.

**Comment by rushatgabhane** [comment]
checklist updated - https://github.com/Expensify/App/issues/35683#issuecomment-1964577282
