### ISSUE TITLE
[$125] Workspace switcher - Workspace dropdown button is hardly visible when hovering over it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Hover over workspace switcher

## Expected Result:
The dropdown button will be visible

## Actual Result:
The dropdown button is hardly visible when hovering over it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

https://github.com/Expensify/App/assets/78819774/2b8d1507-c02d-4c9d-93e0-caf3601f9ad2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e08e86679fe960fc</li>
        <li>Upwork Job ID: 1753533589875175424</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by esh-g** [comment]
https://github.com/Expensify/App/assets/77237602/c9d20713-935c-43ce-93a4-1211f18ed224

How about we have it lighter instead of darker (for dark theme at least)

**Comment by luacmartins** [comment]
I don't think this is a blocker. Gonna demote it and we can get contributors to work on it.

**Comment by s77rt** [comment]
We already have an issue for that https://github.com/Expensify/App/issues/35618. We can close this cc @greg-schroeder

**Comment by luacmartins** [comment]
Closing in favor of https://github.com/Expensify/App/issues/35618. Thanks for the link @s77rt
