### ISSUE TITLE
[$500] Web - Unable to upload Desktop App from website. Error 1102 displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35684]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** rybkina+007@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging URL
2. Tap on About > App download links
3. Upload macOS link

## Expected Result:
The app should be upload

## Actual Result:
Unable to upload Desktop App from website. Error 1102 displayed.. "Error 1102 Ray ID: 84f425e06ea010df • 2024-02-02 17:28:01 UTC
Worker exceeded resource limits"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/67f672e2-ea56-4395-b732-e7ab39940a94

![Bug6365099_1706894984887!error44](https://github.com/Expensify/App/assets/78819774/a887f5d6-10f8-4b62-81d7-8b6fa8c2a231)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aafeb0eb9f055e87</li>
        <li>Upwork Job ID: 1753473246173622274</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Seems to be fixed: https://expensify.slack.com/archives/C03TQ48KC/p1706896412609599
