### ISSUE TITLE
[$500] Web - Preferences, Security, About, Workspaces animations are missing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35687]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34718
## Action Performed:
1. Log in to New Expensify
2. Navigate to Preferences
3. Navigate to Security
4. Navigate to About
5. Navigate to Workspaces settings

## Expected Result:
Appropriate animation should be displayed in all of the pages

## Actual Result:
Animations for all above mentioned pages are missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3d3d6fe0-dd3d-4041-b0d9-962c29da8a62

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158a6748a5057f6d8</li>
        <li>Upwork Job ID: 1753512421000962048</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by grgia** [comment]
@lanitochka17 sidenote I can't tell from the screenshots, are the fonts correct here?

**Comment by grgia** [comment]
I think your assets may not have loaded @lanitochka17 

<img width="1350" alt="image" src="https://github.com/Expensify/App/assets/38015950/50160d95-0b03-4e37-9d79-6ee1e51b5c6f">

**Comment by francoisl** [comment]
I can repro on web, but only in the Security tab. The Preferences tab works fine. 

The console shows a `Invalid .lottie file, manifest.json is missing` error.

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/2229301/5932f31e-b4e8-4be4-9f5c-ec870456c526">

The fonts are also incorrect but I think that's a separate issue 😄

**Comment by francoisl** [comment]
It works fine on dev though. That page uses the [`Safe.lottie`](https://github.com/Expensify/App/blob/main/assets/animations/Safe.lottie) animation, which hasn't been changed in months. I'll make this external, let's see if anyone can figure it out.

**Comment by grgia** [comment]
@francoisl thanks for looking into this deeper, I'm still unable to reproduce on staging

**Comment by grgia** [comment]
<img width="1223" alt="image" src="https://github.com/Expensify/App/assets/38015950/06c199fe-8df9-4943-be33-3fdab5ad25e2">

**Comment by francoisl** [comment]
Same, I can't repro anymore today. Let's get someone else to test for good measure, and if they can't repro either then let's close this.

**Comment by marcaaron** [comment]
Can't repro either. Gonna close it out.
