### ISSUE TITLE
[Hold #36656] [Wave Collect] [Ideal Nav] Navigate to `Everything/Chats` / `Everything/Settings` when clicking the bottom tab 💬 / 🔧 icons in a filtered view. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#35693]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** `v1.4.36-0`
**Reproducible in staging?:** Y 
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1706890098096469

## Action Performed:
1. Open the workspace switcher (top left icon)
2. Click a workspace in the list to filter to it
3. Click the bottom tab wrench or chats icon 
4. Click either of the icons again

## Expected Result:

When filtered on a workspace i.e

`https://staging.new.expensify.com/w/DE966D72A3A06448/r/7354372963660549` (Chats)
`https://staging.new.expensify.com/workspace/DE966D72A3A06448/overview` (Wrench)

Clicking on the 💬 bubble would navigate to the `Everything/Chats` view, and clicking on the 🔧 would navigate to the `Everything/Settings`  view. I.e 

`https://staging.new.expensify.com/r/7354372963660549` (Chats)
`https://staging.new.expensify.com/settings/workspaces` (Wrench)

## Actual Result:
When filtered to a particular view, clicking the two botom tab icons do nothing. You remain in the filtered view. In practice this has caused people confusion with how to get back to a particular screen.. especially in this scenario: 

>Filtered on Expensify workspace
>Click the :wrench:
>See the workspace list
>Click on a workspace
>Workspace is now filtered and clicking :wrench: does nothing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes, they can open the workspace switcher and choose "Expensify" to get back to the everything view. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/56fc86c3-2f5d-43ca-b8e3-5edaaba14d47

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
CC: @adamgrzybowski @kosmydel I think it might be good if one of the SWM crew could take this?

**Comment by trjExpensify** [comment]
@JmillsExpensify - I might hold this one now on the updates coming. We could perhaps still proceed for the Chats tab, but that wasn't the driver of the confusion here, so I could see us not needing to proceed with it at all. CC: @dannymcclain

**Comment by zanyrenney** [comment]
could you add HOLD to the issue if its on HOLD please @trjExpensify alternatively, label with LOW?

**Comment by trjExpensify** [comment]
Added the hold!

**Comment by trjExpensify** [comment]
Ideal nav v2 changes aren't in yet, so keeping this as is on hold for now.

**Comment by trjExpensify** [comment]
Same, but super close.

**Comment by trjExpensify** [comment]
Alright, the ideal nav v2 changes are baked in. With the workspace settings being the source of confusion, and that UX improved, I'm going to close this out. We can always revisit if necessary.
