### ISSUE TITLE
[Wave 8] [Ideal Nav] Workspace - Workspace avatar switches from one to another when creating a new workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings from the bottom
3. Click New workspace

## Expected Result:
The workspace avatar will be constant

## Actual Result:
The workspace avatar switches from one to another

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/571d971b-4146-4468-8cbe-4b63898c6819

![Bug6365162_1706897723871!Screenshot_2024-02-03_at_00 28 28](https://github.com/Expensify/App/assets/78819774/77bf62d6-f07d-4575-8f85-78bd11ef24c7)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a0963c63b3685ca</li>
        <li>Upwork Job ID: 1753494083453640704</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by arosiclair** [comment]
Asking about this internally [here](https://expensify.slack.com/archives/C036QM0SLJK/p1707142670834189)
