### ISSUE TITLE
[$500] Workspace - Tooltip is at the center instead of above display name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35691]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Open workspace switcher
3. Select a workspace
4. Go to Settings at the bottom
5. Go to Members
6. Hover over member display name

## Expected Result:
Tooltip appeaers above the display name

## Actual Result:
Tooltip is at the center instead of above the display name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8298daf7-7b89-4b82-bc4d-6b7df585fd6e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da161df451d2ec58</li>
        <li>Upwork Job ID: 1753485595100897280</li>
        <li>Last Price Increase: 2024-02-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #5
CC @dylanexpensify

**Comment by hayata-suenaga** [comment]
seems like from the Ideal Navigation PR? Removing the blocker as this is just a UI bug. I'll track this as part of the Ideal Nav regressions

**Comment by shubham1206agra** [comment]
Interesting. But I am not sure if we should treat this as regression from https://github.com/Expensify/App/pull/34197 as they can't test this on Ideal Nav due to PR timings.

**Comment by shubham1206agra** [comment]
Oh. If that's the case, then I will unassign myself from this issue and let @sobitneupane take over.
cc @hayata-suenaga

**Comment by shubham1206agra** [comment]
> ah should I remove this from ideal nav then?

Yes

**Comment by hayata-suenaga** [comment]
cc: @sobitneupane

**Comment by aswin-s** [comment]
I'll raise a fix shortly

**Comment by aswin-s** [comment]
PR is ready: https://github.com/Expensify/App/pull/35735 @sobitneupane

**Comment by roryabraham** [comment]
IDK why, but I'm not able to get tooltips to show up on this view at all 😕

**Comment by roryabraham** [comment]
the only tooltip I see is this one:

<img width="659" alt="image" src="https://github.com/Expensify/App/assets/47436092/57534b0a-4760-4745-bb91-07eb5bd34fd2">

same on main and on @aswin-s' branch

**Comment by mountiny** [comment]
Same as Rory, only that one tooltip 
<img width="1232" alt="image" src="https://github.com/Expensify/App/assets/36083550/b7c6250b-8964-40c7-b390-5c55c6b07633">

**Comment by aswin-s** [comment]
@sobitneupane  @roryabraham  Looks like hiding the tooltip is intentional. Regression is from https://github.com/Expensify/App/pull/35460. As per issue https://github.com/Expensify/App/issues/34961 it shouldn't even show tooltip here as the label and tooltip is same. 

So is this issue valid any more?

**Comment by sobitneupane** [comment]
@aswin-s Going through the [linked PR](https://github.com/Expensify/App/pull/35460), we do show the tooltip, If target.scrollWidth > target.offsetWidth (i.e., if the text overflows).

https://github.com/Expensify/App/assets/25876548/41f25b0b-811b-4d25-8780-6f404bd5b933

But I do believe that in case the text overflows, the tooltip will basically appear at the center. But we should extensively test different cases with larger text and alternate texts.

**Comment by aswin-s** [comment]
@sobitneupane The scenario where text overflows is when the text length reaches the container width. At this point tool tip should be aligned at the center of the container anyways.

**Comment by roryabraham** [comment]
cool, so it sounds like this issue is no longer valid.
