### ISSUE TITLE
[HOLD for payment 2024-03-06][$500] [Simplified Collect][Categories] WorkspaceCategoriesPage: base page implementation, displaying categories and its statuses

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35705]
Implement this section of the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit#bookmark=id.qdiriu8utc5u).

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e6c1796715bbf98</li>
        <li>Upwork Job ID: 1755659477413355521</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@ArekChr

**Comment by ArekChr** [comment]
Sure, please assign me @luacmartins

**Comment by jliexpensify** [comment]
Not overdue

**Comment by ArekChr** [comment]
The draft PR is nearly complete. @luacmartins @jliexpensify, could you please review my latest update in the PR? The issue mentioned in comment is currently a blocker, thanks!

**Comment by trjExpensify** [comment]
Pulled the Q out to [Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1707830814012969?thread_ts=1707768509.167959&cid=C036QM0SLJK)

**Comment by luacmartins** [comment]
Yes, it's done

**Comment by trjExpensify** [comment]
Yeah, we need to switch @parasharrajat for @rushatgabhane for the C+ tracking.

**Comment by sonialiap** [comment]
@jliexpensify @luacmartins I have an [automatic issue](https://github.com/Expensify/App/issues/37135) to issue payment for [the PR](https://github.com/Expensify/App/pull/36324) that's linked to this issue. Do we need to issue one or two payments to Rushat for https://github.com/Expensify/App/pull/36324?

**Comment by luacmartins** [comment]
@sonialiap thanks for checking. We should only issue one payment for @rushatgabhane's PR review. I think we can close the [internal issue](https://github.com/Expensify/App/issues/37135) in favor of this one.

**Comment by sonialiap** [comment]
Thanks! Makes sense to keep it all in one place 👍 Closing out the other issue

**Comment by jliexpensify** [comment]
Payment Summary

- Contributor: @ArekChr (Invoiced)
-C+: @rushatgabhane $500 (New.Dot)

If this is correct, I'll remove the [Upworks job](https://www.upwork.com/jobs/~014e6c1796715bbf98). @rushatgabhane anything need to be done for the checklist?

**Comment by JmillsExpensify** [comment]
$500 payment approved for @rushatgabhane based on summary.

**Comment by jliexpensify** [comment]
Upworks job removed, bump on @rushatgabhane for the checklist (if applicable).

**Comment by rushatgabhane** [comment]
@jliexpensify it's a new feature.

So I recommend that we add the test steps in regression suite.

1. Navigate to the workspace settings as an admin within a paid policy group.
2. Verify that you can access the categories page.
3. Verify that categories are listed.
4. Confirm that you can select all categories by clicking on 'name', and deselect them by clicking on 'name' once more.
5. Access workspace settings as a member with a paid group policy.
6. Replace the sub-path /profile with /categories in the URL.
7. Verify that a 'not found' screen is displayed on the central page.
8. Repeat steps 4 through 6 as both an administrator and a member under a free policy.
9. Confirm that you are unable to access the categories page.

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @ArekChr (Invoiced)
- C+: @rushatgabhane $500 (New.Dot)
