### ISSUE TITLE
[HOLD for Payment April 2nd, 2024][Simplified Collect][Categories] CategorySettingsPage: page init, enable/disable categories, display name, onyx action for enabling/disabling category

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35708]
Implement WorkspaceEditCategoryPage: full implementation, onyx action from the [CategorySettingsPage: page init, enable/disable categories, display name, onyx action for enabling/disabling category](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

**Comment by luacmartins** [comment]
@ArekChr can you please comment here so I can assign you to the issue?

**Comment by ArekChr** [comment]
Sure, please assign me @luacmartins

**Comment by dylanexpensify** [comment]
@ArekChr mind giving an update?

**Comment by ArekChr** [comment]
Hey @dylanexpensify work in progress! I will create a draft PR soon

**Comment by dylanexpensify** [comment]
Nice! Any updates yet?

**Comment by dylanexpensify** [comment]
same

**Comment by ArekChr** [comment]
Hey @dylanexpensify, I've been busy implementing the main page for categories. Today, I almost finished the work there and started working on the category settings

**Comment by dylanexpensify** [comment]
Same ^

**Comment by dylanexpensify** [comment]
hold, @luacmartins shall we put `Weekly`?

**Comment by luacmartins** [comment]
This is no longer on hold and we have a linked draft PR - https://github.com/Expensify/App/pull/37209

**Comment by dylanexpensify** [comment]
beautiful! @ArekChr mind giving eta when PR is ready?

**Comment by ArekChr** [comment]
1-2 days, https://github.com/Expensify/App/issues/37307 is blocker, working on that

**Comment by ArekChr** [comment]
PR is ready for review

**Comment by iwiznia** [comment]
PR has wrong copy https://expensify.slack.com/archives/C01GTK53T8Q/p1709305812229179?thread_ts=1709215749.926399&cid=C01GTK53T8Q

**Comment by luacmartins** [comment]
Yes, I created this issue to fix the copy - https://github.com/Expensify/App/issues/37614

**Comment by trjExpensify** [comment]
Done!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @ArekChr 
- Contributor+: @ishpaul777 $500
Please apply or request!

**Comment by dylanexpensify** [comment]
@ishpaul777 please apply [here](https://www.upwork.com/jobs/~016d3c09908ec24f4a)!

**Comment by dylanexpensify** [comment]
@ishpaul777 sent invite to apply!

**Comment by dylanexpensify** [comment]
Offer sent @ishpaul777!!

**Comment by dylanexpensify** [comment]
Done! Thanks team!
