### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] [Simplified Collect][Categories] WorkspaceCategoriesSettingsPage: full page implementation - toggle require categories policy, onyx action

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35706]
Implement `WorkspaceCategoriesSettingsPage: full page implementation - toggle require categories policy, onyx action` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154080d90e7f3dfba</li>
        <li>Upwork Job ID: 1755659460840173568</li>
        <li>Last Price Increase: 2024-02-08</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@ArekChr can you please comment here so I can assign you to the issue?

**Comment by lschurr** [comment]
Any update here @ArekChr?

**Comment by brunovjk** [comment]
I would like to work on it. Thanks.

**Comment by luacmartins** [comment]
@brunovjk thanks for the interest, but we already have someone working on this.

**Comment by happydev0110** [comment]
Hi
I hope work with you.

**Comment by lschurr** [comment]
What's the latest here? Any update @ArekChr?

**Comment by cubuspl42** [comment]
If @ArekChr is unavailable on next overdue we can consider re-assigning

**Comment by ArekChr** [comment]
Hi @lschurr this issue is blocked by https://github.com/Expensify/App/issues/35705, need to finish categories page first

**Comment by trjExpensify** [comment]
With the PR in review, I'm taking this off hold.

**Comment by lschurr** [comment]
@allroundexperts - Could you review and confirm we don't need a regression test?

**Comment by lschurr** [comment]
I pulled back the contract offered in Upwork to Jakub T. since they didn't end up reviewing the PR - https://github.com/Expensify/App/pull/37133#issuecomment-1965126581

**Comment by lschurr** [comment]
Payment summary is correct. Closing this one out.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary.
