### ISSUE TITLE
[HOLD for payment 2024-03-25] [$500] [Simplified Collect][Categories] WorkspaceEditCategoryPage: full implementation, onyx action

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35707]
Implement `WorkspaceEditCategoryPage: full implementation, onyx action` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a0968914dafaee6</li>
        <li>Upwork Job ID: 1755659442500919296</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
@ArekChr can you please comment here so I can assign you to the issue?

**Comment by ArekChr** [comment]
Sure, please assign me @luacmartins

**Comment by YehualashetGit** [comment]
Hello 
I would like to work on it.

Thanks

**Comment by abekkala** [comment]
@YehualashetGit there is already a contributor assigned to this job. 

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!

**Comment by abekkala** [comment]
still on hold

**Comment by abekkala** [comment]
on hold

**Comment by abekkala** [comment]
not overdue, still on hold. 
Moving to weekly for now

**Comment by trjExpensify** [comment]
Removing the holds.

**Comment by abekkala** [comment]
not overdue

**Comment by abekkala** [comment]
https://expensify.slack.com/archives/C036QM0SLJK/p1708992954920509?thread_ts=1708982499.109229&cid=C036QM0SLJK

> [@Arkadiusz Chrabąszczewski](https://expensify.slack.com/team/U03CC0969FA)
>  is currently working on https://github.com/Expensify/App/issues/35708. We'll tackle this one next

**Comment by luacmartins** [comment]
@ArekChr will get to this one soon

**Comment by luacmartins** [comment]
Update above

**Comment by c3024** [comment]
@luacmartins 

Could you share me access to the doc on kkch3024@gmail.com? I have signed the NDA.

**Comment by luacmartins** [comment]
Done!

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 25

- Fix: @ArekChr - does not require payment
- PR Review: @c3024 [$500, if no regressions] [Offer ](https://www.upwork.com/nx/wm/offer/101489026)

@c3024 please propose a regression test

**Comment by abekkala** [comment]
@slafortune will be handling payment for me while I'm ooo

**Comment by c3024** [comment]
## Regression Test Proposal

>1. As a Collect policy admin, navigate to Settings > Workspace > Categories
>2. Press on any Category
>3. Verify the RHP opens up with name of the category
>4. Press the menu item with category name and edit it
>5. Press Save without any name and verify that you see an error
>6. Enter a category name and press Save
>7. Verify that the category is renamed and you can see the updated name on the category list

**Comment by luacmartins** [comment]
No need to regression steps here. We'll add these to TestRail once we wrap the project.

**Comment by slafortune** [comment]
Fix: @ArekChr - does not require payment
PR Review: @c3024 [$500, if no regressions] PAID
