### ISSUE TITLE
[HOLD for payment 2024-02-22] [Simplified Collect][Members] WorkspaceMembersPage: Header, Invite and Remove buttons redesign

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35711]
Implement `WorkspaceMembersPage: Header, Invite and Remove buttons redesign` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @burczu</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f88d6f60c615f98</li>
        <li>Upwork Job ID: 1755659183269515264</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@burczu can you please comment here so I can assign you to the issue?

**Comment by burczu** [comment]
Hi! I'm Bartek from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by conorpendergrast** [comment]
Assigned!

**Comment by burczu** [comment]
Daily update: the draft PR is ready, I'm waiting for some more internal approvals and I think I'll publish it on Monday morning.

**Comment by burczu** [comment]
The PR is ready for review

**Comment by Santhosh-Sellavel** [comment]
@allroundexperts's took over please assign them!

**Comment by luacmartins** [comment]
It seems like automation didn't kick in here, but this PR was deployed to prod [4 days ago](https://github.com/Expensify/App/pull/36220#issuecomment-1945393856).

**Comment by trjExpensify** [comment]
Sounds good!

**Comment by trjExpensify** [comment]
Alright, we're ready for payments. Summary: 

- $500 to @allroundexperts for the C+ review.

Sibtain, once you confirm you've requested, I'll close this out.

**Comment by trjExpensify** [comment]
Bump, @allroundexperts. :)

**Comment by allroundexperts** [comment]
All good. We can close.

**Comment by trjExpensify** [comment]
Thanks!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on [this summary](https://github.com/Expensify/App/issues/35711#issuecomment-1959200482).
