### ISSUE TITLE
[HOLD for payment 2024-03-06][$500] [Simplified Collect][Members] WorkspaceMembersPage: Members list redesign

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35712]
Implement `WorkspaceMembersPage: Members list redesign` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @burczu</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f11d2f24fdf84777</li>
        <li>Upwork Job ID: 1755659075046100992</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@burczu can you please comment here so I can assign you to the issue?

**Comment by burczu** [comment]
Hi! I'm Bartek from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by burczu** [comment]
Not overdue - I'm working on this issue right now.

**Comment by burczu** [comment]
@shawnborton I have a question about the new design of the Selection List we change in this issue:

![Screenshot 2024-02-14 at 11 44 30](https://github.com/Expensify/App/assets/7771498/1449dd7f-d9aa-468b-9fb9-73295dbd2fc0)

The Selection List is used in many places in the App other than Workspace Members List page - should we preserve its old look for other places or is it ok to just change it for all the places?

**Comment by burczu** [comment]
@trjExpensify Yes, correct.

**Comment by trjExpensify** [comment]
Cool, we haven't planned to update the design of those to the "table list" view we designed to be used for the new Members, Categories, Tags etc pages.

CC: @mountiny as well for vis.

**Comment by burczu** [comment]
@vitHoracek @shawnborton @trjExpensify Ok... So, we presumed in the proposal that we will reuse the existing `SelectionList` only changing its styles. One of the option I've considered is to introduce additional prop like `viewMode = 'list' | 'table'` and keep existing styles if the `viewMode` is set to `list` while adding new styling for `table` view mode. I find it much easier to implement, and I've almost done all the necessary work.

We, of course, can also create completely new component for it - it may be cleaner approach but also much more time consuming.

What option do you prefer then?

**Comment by mountiny** [comment]
Hey @burczu 

> We, of course, can also create completely new component for it - it may be cleaner approach but also much more time consuming.
What option do you prefer then?

What I meant by new component is just a wrapper around the SelectionList with the updated props/ stylings we need for the Members table.

We could call it TableList or something like this, maybe would be good to go to Slack and propose couple names and let people vote about it.

**Comment by trjExpensify** [comment]
I think `TableList` works fine as that's what it is. We need to also use this for the categories table etc too.

**Comment by burczu** [comment]
Or maybe `SelectionTable`? Like `SelectionList` is a list that allows selection, we will have a table we will use for selection...

**Comment by burczu** [comment]
> Hey @burczu
> 
> > We, of course, can also create completely new component for it - it may be cleaner approach but also much more time consuming.
> > What option do you prefer then?
> 
> What I meant by new component is just a wrapper around the SelectionList with the updated props/ stylings we need for the Members table.
> 
> We could call it TableList or something like this, maybe would be good to go to Slack and propose couple names and let people vote about it.

Hmmm... I need to think about it, cause the `SelectioList` is quite complicated and simply wrapping it with props and styles may not be that easy...

**Comment by burczu** [comment]
@mountiny I've spoke to @ArekChr about it and, because the `SelectionList` component is a black box right now and it makes it hard to be extended, we think that the best idea is to refactor it and expose the `renderItem` prop moving the responsibility of deciding how to render the items to the client component. Additionally we can prepare different item components for all the three purposes that could be used by the client components in its `renderItem` implementations. I think this will solve all of our problems with re-usability of the `SelectionList` and will make it easier on other pages like Categories etc. What do you think?

**Comment by mountiny** [comment]
@burczu I think this is a viable option. Can you do it in a separate PR such that the current renderItem behaviour stay default which we can overwrite if we need this to behave differently?

**Comment by burczu** [comment]
@mountiny The thing is there is no renderItem prop in SelectionList therefore it's not very extensible. But I guess you mean you want a separate PR for refactor, and separate for actual members re-design?

**Comment by mountiny** [comment]
@burczu Correct, lets make the refactor of the Selection list so you can pass in customized "cells" in a separate PR

**Comment by shawnborton** [comment]
I don't have strong feelings about whether or not this should be a totally new component or extend an existing one. Part of me thinks its a bit cleaner to keep it as its own component as we've seen what happens when we make design/style changes to the SelectionList and how that cascades into other places. So my OCD brain likes keeping them separate at least. Either way, probably a good discussion to bring to Slack!

**Comment by burczu** [comment]
@shawnborton I think having separate component that wraps the SelectionList is a secondary problem until it's hard to adjust the SelectionList itself.

**Comment by burczu** [comment]
Daily update: I've done most of the refactor of the Selection List now, but I need to test everything etc. I expect the PR to be published tomorrow.

**Comment by burczu** [comment]
@mountiny sure thing! here's the draft PR: https://github.com/Expensify/App/pull/37000

**Comment by burczu** [comment]
The PR is now published and ready for review.

**Comment by burczu** [comment]
The PR with members list is now ready for review: https://github.com/Expensify/App/pull/37074

**Comment by adelekennedy** [comment]
@getusha sent you an offer for the role!

**Comment by getusha** [comment]
accepted @adelekennedy

**Comment by adelekennedy** [comment]
ended contract and remitted payment
