### ISSUE TITLE
[HOLD for payment 2024-03-25] [HOLD for payment 2024-03-22] [$500] [Simplified Collect][Members] WorkspaceInvitePage: Redesign and scrolling to the first invited member

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35717]
Implement `WorkspaceInvitePage: Redesign and scrolling to the first invited member` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4ddf9c90431aacf</li>
        <li>Upwork Job ID: 1755658647575998464</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by luacmartins** [comment]
@burczu can you please comment here so I can assign you to the issue?

**Comment by burczu** [comment]
Hi! I'm Bartek from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by trjExpensify** [comment]
>We could do that, I guess?

Internal folks, I'm looking into that [here](https://expensify.slack.com/archives/C01L6EHSU1F/p1707475860092079).

**Comment by trjExpensify** [comment]
Sent @ishpaul777 the NDA. 👍

**Comment by burczu** [comment]
not overdue - I haven't started the implementation yet

**Comment by strepanier03** [comment]
Thanks for the update @burczu.

**Comment by luacmartins** [comment]
@burczu is this on hold for https://github.com/Expensify/App/issues/35712?

**Comment by strepanier03** [comment]
All good Melvin!

**Comment by strepanier03** [comment]
Okay there we go, not sure what was up with the label. I had to toggle myself as the assignee and then remove it but at least it's gone now.

**Comment by strepanier03** [comment]
Hold GH is still open, updated title.

**Comment by strepanier03** [comment]
HOLD GH is still open, continuing to hold for now.

**Comment by mountiny** [comment]
Removing the HOLD, as that issue is closed already

**Comment by mountiny** [comment]
@shubham1206agra will implement and @ishpaul777 is a C+

**Comment by situchan** [comment]
> @mountiny I think somthing is off with automated offer melvin says "error making the offer" but i do get offer 🤔

@ishpaul777 looks like you skipped https://expensify.slack.com/archives/C02NK2DQWUX/p1709761393644809

**Comment by burczu** [comment]
Hey @shubham1206agra - just to make sure: are you working on redesigning `WorkspaceInvitePage` after merging the scroll feature, right? It's also in the scope of this issue.

**Comment by burczu** [comment]
@shubham1206agra Yeah I've seen this and this is incorrect approach that should not be approved

**Comment by mountiny** [comment]
I think that will be $500 to @shubham1206agra and to @ishpaul777

**Comment by strepanier03** [comment]
@ishpaul777 and @shubham1206agra - I'll send over offers now, but will hold on payment until the BZ checklist is done. If we don't need a reg test then just confirm for me here and I'll skip holding payment until that's done.

**Comment by strepanier03** [comment]
All right, invites sent. I'll check back later today and tomorrow.

**Comment by strepanier03** [comment]
### Payment Summary

- @shubham1206agra - $500 (HOLDING)
- @ishpaul777 - $500 (HOLDING)

Per the comment above and the linked Slack thread, I'm closing this with the above payment summary.

**Comment by strepanier03** [comment]
Both contracts are paid and closed. Cheers everyone!
