### ISSUE TITLE
[HOLD for payment 2024-02-20] [Simplified Collect][Profile] Update name convention from Overview to Profile for all workspace level items like components, functions, routes, etc.

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35718]
Implement `Update name convention from Overview to Profile for all workspace level items like components, functions, routes, etc.` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @narefyev91</details>

**Comment by luacmartins** [comment]
@narefyev91 can you please comment here so I can assign you to the issue?

**Comment by narefyev91** [comment]
Today updates - start working on Refactoring naming convention. Will continue tomorrow as well. No blockers for now!

**Comment by trjExpensify** [comment]
Wahoo! Let's get it!

**Comment by narefyev91** [comment]
@luacmartins @trjExpensify @mallenexpensify PR is ready for review

**Comment by trjExpensify** [comment]
Let's get it!!

**Comment by luacmartins** [comment]
Approved! Just pending C+ review now

**Comment by DylanDylann** [comment]
Regression Test Step

On Web (Laptop) and Desktop App

1. Open any workspace settings
2. Verify that in the left menu first item is Profile
3. Verify that top section has naming Profile as well

On mobile:

1. Open workspace settings
2. Verify that first menu item is Profile
3. Click on Profile
4. Verify that back button is shown with text Profile

Do we agree 👍 or 👎

**Comment by trjExpensify** [comment]
Waiting out the regression period. We'll be adding tests holistically for this project.

**Comment by trjExpensify** [comment]
@DylanDylann - sent you an offer for $500 for the C+ review.

**Comment by trjExpensify** [comment]
Paid!
