### ISSUE TITLE
[HOLD for payment 2024-03-13] [HOLD for payment 2024-03-07] [$500][Simplified Collect][Profile] General implementation of Profile page, Description page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35719]
Implement `General implementation of Profile page, Description page` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @narefyev91</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d2696ece76f1034</li>
        <li>Upwork Job ID: 1755658427757031424</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@narefyev91 can you please comment here so I can assign you to the issue?

**Comment by narefyev91** [comment]
Hey sure!

**Comment by isabelastisser** [comment]
Thanks @narefyev91!

**Comment by narefyev91** [comment]
Daily update - work in progress! Draft PR should be ready Monday/Tuesday. One more note - i will suggest to move away from this GH issue "Share functionality". It should be a separate one issue (to not block refactoring of generic profile page)
cc @luacmartins

**Comment by luacmartins** [comment]
@narefyev91 agreed, created the new issue here https://github.com/Expensify/App/issues/36250

**Comment by narefyev91** [comment]
@luacmartins @isabelastisser @quinthar this PR https://github.com/Expensify/App/pull/36058/files caused a lot of mess for Profile page.
Description page was specified inside Simplified Collect project - why someone else integrate that? Even before document was approved

**Comment by trjExpensify** [comment]
For the breadcrumbs, chatted this one out [here](https://expensify.slack.com/archives/C036QM0SLJK/p1707935085691239).

**Comment by isabelastisser** [comment]
Hey @allroundexperts, is this ready for payment? Please also complete the checklist above. Thanks!

**Comment by isabelastisser** [comment]
I sent the offer in Upwork, please accept it, and I will process the payment. Thanks!

**Comment by isabelastisser** [comment]
Thanks for the reminder! 

Payment summary:

@allroundexperts $500 for C+ review.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary.
