### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] [Simplified Collect][Members] WorkspaceMembersPage: Bulk actions (invite, remove, make admin, make member)

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35713]
Implement `WorkspaceMembersPage: Bulk actions (invite, remove, make admin, make member)` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @burczu</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e777c5185b93bdf5</li>
        <li>Upwork Job ID: 1755659051188183040</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@burczu can you please comment here so I can assign you to the issue?

**Comment by burczu** [comment]
Hi! I'm Bartek from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by laurenreidexpensify** [comment]
@burczu is there a draft PR up for this yet?

**Comment by burczu** [comment]
> @burczu is there a draft PR up for this yet?

@laurenreidexpensify No, I haven't started the implementation yet, the plan is to start working on this after I finish members list re-design (https://github.com/Expensify/App/issues/35712) - I'll let you know once I started working on this one.

**Comment by burczu** [comment]
@laurenreidexpensify @luacmartins Since the Members list redesign PR is under review, I'm starting working on this issue now (I think we can switch to Daily here).

**Comment by burczu** [comment]
Daily updated: I've managed to show the ButtonWithDropdownMenu component when user selects some members on the list - I had to slightly refactor this component because it was designed to use with payments only. It seems it needs some further refactoring to fit our needs - I'll be working on this on Monday.

**Comment by burczu** [comment]
@luacmartins Draft PR added. Today I've extended the ButtonWithDropdownMenu to adjust it to our needs. I've also finished to selected members removal flow and addressed issues regarding removal created while refactoring the SelectionList component. Tomorrow I plan to work on Make admin/Make member flows.

**Comment by burczu** [comment]
@luacmartins Ok, so I think I've finished working on this issue - the PR is still on draft state as I'm waiting for some reviews we usually do at Callstack team before publishing it. Once I receive some internal approvals I'll publish it (most likely tomorrow), but feel free to review it fully right now.

**Comment by luacmartins** [comment]
Cool, I'll do a full review and also ask C+ to review it today so we can speed things up.

**Comment by luacmartins** [comment]
@aimane-chnaif are you available to review this PR today?

**Comment by luacmartins** [comment]
>yes. should I start while it's in draft state?

yes, that's fine. The PR should be ready, it's just in draft while we wait on internal review.

**Comment by burczu** [comment]
@luacmartins @aimane-chnaif Just to inform - the PR is now published.

**Comment by laurenreidexpensify** [comment]
Payment Summary
[Upwork Job](https://www.upwork.com/jobs/~01e777c5185b93bdf5)

Contributor: @burczu is from an agency-contributor and not due payment
ROLE: @aimane-chnaif  $(500) offer sent via Upwork ([LINK)](https://www.upwork.com/jobs/~01425257ff0c136473)

**Comment by laurenreidexpensify** [comment]
Payment Summary
[Upwork Job](https://www.upwork.com/jobs/~01e777c5185b93bdf5)

Contributor: @burczu is from an agency-contributor and not due payment
ROLE: @aimane-chnaif $(500) paid in Upwork

**Comment by laurenreidexpensify** [comment]
@luacmartins no regression test here needed right? if so feel free to close thanks!

**Comment by luacmartins** [comment]
Yea, we'll add these once the feature is fully implemented.

**Comment by shubham1206agra** [comment]
https://github.com/Expensify/App/pull/37199 introduced a wrong failure pattern, which caused https://github.com/Expensify/App/issues/87709
