### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] [Simplified Collect][Members] WorkspaceMembersPage: Making the page read-only for non-admin users

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35714]
Implement `WorkspaceMembersPage: Making the page read-only for non-admin users` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @burczu</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d106646d7dbfa7d</li>
        <li>Upwork Job ID: 1755658926889984000</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@burczu can you please comment here so I can assign you to the issue?

**Comment by burczu** [comment]
Hi! I'm Bartek from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by burczu** [comment]
not overdue - I haven't started the implementation yet

**Comment by luacmartins** [comment]
@burczu is this on hold for another issue?

**Comment by burczu** [comment]
yes, can we switch to weekly maybe? I'll write a comment here once I start the implementation, then we could switch back to daily

**Comment by trjExpensify** [comment]
Taking this off `Help wanted` as @burczu will be working on this.

**Comment by stephanieelliott** [comment]
Hey @burczu do you have a general ETA for when you will have a PR up"

**Comment by stephanieelliott** [comment]
Oh also moving this back to `Weekly` per @burczu's comment [here](https://github.com/Expensify/App/issues/35714#issuecomment-1926514550).

**Comment by luacmartins** [comment]
This is still on hold as @burczu works their way through the other implementation issues

**Comment by luacmartins** [comment]
Same as above

**Comment by luacmartins** [comment]
I created a PR for this one

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @burczu (EC, no payment)
 - Contributor+: @allroundexperts $500, please request via Newdot 
 
 Upwork job is here: https://www.upwork.com/jobs/~010d106646d7dbfa7d

**Comment by stephanieelliott** [comment]
This was a new feature, so no regression test is needed here and we can ignore the BZ checklist.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
