### ISSUE TITLE
[$500] Workspace switcher - Search result is not highlighted when navigating via up and down key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35727]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Infernal team
**Slack conversation:**

## Action Performed:
Precondition:
- There are more than 7 workspaces.
- App is in "Expensify" filter in the workspace switcher.
1. Go to staging.new.expensify.com
2. Open workspace switcher.
3. Click on the search bar.
4. Search for term that will return a few results.
5. Press up or down key on keyboard.

## Expected Result:
The search result will be highlighted.

## Actual Result:
The search result is not highlighted when navigating via up and down key.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/61bf6fc0-2df0-4dbc-bc88-06e44827b78d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e5fbb8f8bcace41</li>
        <li>Upwork Job ID: 1757911779125587968</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by luacmartins** [comment]
I think we can demote this to NAB

**Comment by AndrewGable** [comment]
Demoted and I will let @quinthar find someone from VSB to pick this one up

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace item doesn't gets highlighted when navigating with arrow key.

### What is the root cause of that problem?
We disable the highlight/focus if there is no active workspace selected (Everything is selected).
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/WorkspaceSwitcherPage.tsx#L250

### What changes do you think we should make in order to solve the problem?

If we want to enable the highlight, we can just remove `disableFocusOptions`.

**Comment by AndrewGable** [comment]
@cubuspl42 - Can we verify this still exists? Then otherwise we can evaluate @bernhardoj's proposal

**Comment by cubuspl42** [comment]
I confirm this is reproducible on staging and `main`.

**Comment by cubuspl42** [comment]
@bernhardoj Do you have any idea why `disableFocusOptions={!activeWorkspaceID}` was passed in the first place?

**Comment by dragnoir** [comment]
Just tested on dev and it's not reproducible, it works fine.

**Comment by bernhardoj** [comment]
I can't find any discussion from the PR about disabling the focus option.

This [commit](https://github.com/Expensify/App/commit/f5a0d7b04aa56d3ac7541f277258016e03d7c4d9) is the one that adds `disableFocusOptions`. Then this [commit](https://github.com/Expensify/App/commit/775ba641e953026420b72d23b6fbff946ba76be3) update it to `disableFocusOptions={!activeWorkspaceID}`

**Comment by cubuspl42** [comment]
> Just tested on dev and it's not reproducible, it works fine.

I can still reproduce. Please ensure to follow the steps carefully.

**Comment by cubuspl42** [comment]
C+ reviewed 🎀 👀 🎀

I approve the proposal by @bernhardoj. I applied the suggested change at it enables keyboard navigation as expected.

I'm somewhat confused as to why this was disabled in the first place, though.

**Comment by bernhardoj** [comment]
PR is ready

cc: @cubuspl42

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment]
Interesting, so the fix above wasn't necessary?

**Comment by bernhardoj** [comment]
Still happens on staging (the PR is not deployed to staging yet)

https://github.com/Expensify/App/assets/50919443/b0c091f3-a570-4816-b174-32d01d233853

**Comment by cubuspl42** [comment]
Oh my, I'm out of the loop here. So it looks like we had a regression, but it already got fixed?

**Comment by bernhardoj** [comment]
Oh, I forget about this one too. There is no regression. It was a false alarm. So, this is ready for payment.

**Comment by cubuspl42** [comment]
@iwiznia Friendly bump 🙂

**Comment by cubuspl42** [comment]
@johncschuster Friendly bump 🙂 As I understand it, we're ready for payments

- $500 for @bernhardoj
- $500 for me

**Comment by johncschuster** [comment]
Payment has been issued! 🎉
