### ISSUE TITLE
Web - Login - Animation missing & Welcome message overlapping with menu options in login page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35726]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Observe animation missing
3. Scroll down to Welcome message

## Expected Result:
Animation should be displayed & Welcome message should not overlap with menu options

## Actual Result:
Animation missing & Welcome message overlapping with menu options in login page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fb9319a5-bf23-4c81-a40c-b07321e45e24

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
I am not able to reproduce this, so I am at least removing it as a deploy blocker for now.

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/1228807/c47c4648-d55e-4c3f-bef8-65afcb245f67">

**Comment by luacmartins** [comment]
I'm also unable to reproduce
