### ISSUE TITLE
Bank Account - From Additional details page, tapping back button user directed to home page (LHN)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35723]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre- condition: From Wallet---Enable wallet, add a bank account
1. Go to https://staging.new.expensify.com/home
2. Tap on profile icon
3. Tap wallet --- Enable wallet
4. Tap app back button in Additional details page

## Expected Result:
From Additional details page, tapping back button user must not be directed to home page (LHN) .

## Actual Result:
From Additional details page, tapping back button user directed to home page (LHN) .

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ce7ecd6a-cf98-4342-a452-a6796aa438ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
I believe all the "go back" issues are already tracked and worked on - see https://github.com/Expensify/App/issues/35697#issuecomment-1924488225 for context.
