### ISSUE TITLE
IOU - App resumes in IOU flow when killing app in confirmation page and relaunching app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35730]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-36.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Tap FAB > Request money.
3. Enter amount > Next.
4. Select a participant.
5. Proceed to confirmation page.
6. Kill the app.
7. Relaunch the app.

## Expected Result:
The home page will open.

## Actual Result:
App resumes in IOU confirmation page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1113d32e-c03e-4a90-b516-d93448450b14

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @gabrielessner

**Comment by mountiny** [comment]
Interesting @kbecciv is the user able to normally continue in the flow after this? 

Its a side effect of us saving the last visited route so this is kinda expected and I am not sure if we want to change the behaviour now

**Comment by mountiny** [comment]
Asking in Slack about the expected outcome https://expensify.slack.com/archives/C036QM0SLJK/p1707134955066079

**Comment by mountiny** [comment]
This is expected outcome for now, lets see if this will cause any issues as we use it

**Comment by hayata-suenaga** [comment]
The design change related to this issue will be made. The design change work is done in [this issue](https://github.com/Expensify/App/issues/35927).
