### ISSUE TITLE
 Bank Account - User navigates to LHN when click back from Plaid page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35736]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0507gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings> Wallet> Add bank account> Personal bank account
3. Click Back button

## Expected Result:
User should navigate to Wallet page

## Actual Result:
User navigates to LHN when click back from Plaid page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9db0cb22-63a3-4444-83a3-dc9d4cb0d2fc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
This looks like another issue with "go back" navigation?  Those should be already tracked afaict - see https://github.com/Expensify/App/issues/35697#issuecomment-1924488225

**Comment by hayata-suenaga** [comment]
Yes that's right. This issue can be tracked [here](https://github.com/orgs/Expensify/projects/94/views/2?pane=issue&itemId=51976513). I'm closing this issue now.
