### ISSUE TITLE
Android – Back button redirect to LHN from IOU report preview in WS and unable to open WS chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35738]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app.
2. Log in
3. Request money from your own workspace;
4. Navigate to the workspace chat;
5. On the expense report preview, open the Settlement button's dropdown;
6. Select an option different from the currently selected;
7. Click on the report preview to open the Expense Report view;
8. Tap on the Back button arrow on the header

## Expected Result:
Back button redirects to parent WS chat from expense report preview

## Actual Result:
Back button redirects to LHN from expense report preview in WS and unable to open WS chat again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/b5c3f7e3-0b50-475a-bd0e-14ff72de6ba1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by robertjchen** [comment]
Part of https://github.com/Expensify/App/issues/35626 and being addressed
