### ISSUE TITLE
[$500] Expensify logo doesn't update to workspace name when filtered into a workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** yes
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706913050673359

## Action Performed:
Filter into a workspace using the new workspace switcher.

## Expected Result: 
The Expensify logo on the Chats page should be replaced with the workspace name, the same way it is on the Settings page.

## Actual Result: 
The logo remains as Expensify logo.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/691808fc-e0b0-4188-ac1c-32d3efe26a1b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137184ea043f30675</li>
        <li>Upwork Job ID: 1753607512063062016</li>
        <li>Last Price Increase: 2024-02-03</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28142341</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Active workspace name isn't shown in the sidebar chats breadcrumb

### What is the root cause of that problem?
Currently, we always show the Expensify logo for the Sidebar and do not have logic to show active workspace name.
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/sidebar/SidebarLinks.js#L135-L138

### What changes do you think we should make in order to solve the problem?
- Create utility function to get active workspace name in SidebarUtils.
```js
function getActiveWorkspaceName(policies: OnyxCollection, activeWorkspaceId) {
    if(activeWorkspaceId) {
        const activeWorkspace = policies.[`${ONYXKEYS.COLLECTION.POLICY}${activeWorkspaceId}`];
        return activeWorkspace.name;
    }
    return '';
}
```
- In the `SidebarLinksData` component call the util function and store it in the `activeWorkspaceName`
```js
const activeWorkspaceName = useMemo(() => SidebarUtils.getActiveWorkspaceName(policies, activeWorkspaceID),[policies, activeWorkspaceID])
```

- Pass `activeWorkspaceName` to the dumb component `SidebarLinks` and based on value decide the breadcrumbs.
```js
activeWorkspaceName ? {
    type: CONST.BREADCRUMB_TYPE.STRONG,
    text: activeWorkspaceName,
} : {
    type: CONST.BREADCRUMB_TYPE.ROOT,
},
```

**Comment by rushatgabhane** [comment]
Let's go with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/35743#issuecomment-1925033833) because they were first. 
C+ reviewed 🎀 👀 🎀

**Comment by rushatgabhane** [comment]
@Pujan92 i like your solution but it's too similar to @dukenv0307's

**Comment by Pujan92** [comment]
> @Pujan92 i like your solution but it's too similar to @dukenv0307's only code structure is different. please correct me if im wrong : )

I thought to not subscribe to onyx in `SidebarLinks` and let it be a only presentational component, instead we have all the policies in `SidebarLinksData` to derive the active policy name. I would say structure and implementation difference too. 
Thanks @rushatgabhane

**Comment by rafecolton** [comment]
Reminder to myself to come back to [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1706912362033189) and see if the UX is still confusing once this PR is live. cc @quinthar

**Comment by rushatgabhane** [comment]
IMO, the new UX is much better :)

**Comment by rushatgabhane** [comment]
@miljakljajic could you please attach payment summary, thanks 🙇

**Comment by rushatgabhane** [comment]
Money request here - https://staging.new.expensify.com/r/4753776353945381

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @dukenv0307 $500
- Contributor+: @rushatgabhane $500
Please request/apply!

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane based on summary.

**Comment by dylanexpensify** [comment]
Done!
