### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Login - Blank screen and infinite spinner when logging in using magic link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35745]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Enter the email and tap "Continue"
3. Find the email and use the magic link to log in (change to staging if needed)

## Expected Result:
User is logged in and lands on LHN

## Actual Result:
The blank screen and the infinite spinner displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/60d90526-0b8b-4290-81bb-42dcd0ca635b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3cfffaf993f802b</li>
        <li>Upwork Job ID: 1754481620046606336</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28142697</li>
<li>aswin-s | Contributor | 28142698</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Gonals** [comment]
I have not been able to reproduce this. Is it only happening on staging?

**Comment by mountiny** [comment]
@Gonals You need to use the link from the email, have you tried that. I was able to reproduce, this is a real blocker.

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Infinite spinner when logging in using magic link


### What is the root cause of that problem?

In ValidateLoginPage a useEffect is used to authenticateUser and signIn. When sign-in using deep link `Navigation.isNavigationReady()` return in false when invoked the first time. This results in non action.

### What changes do you think we should make in order to solve the problem?

We should wait till `Navigation.isNavigationReady()` is ready before invoking the effect.

```tsx
    const [isNavReady, setIsNavReady] = useState(false)
    useEffect(() => {
        if (!isNavReady) { return }
        if (session?.authToken) {
            // If already signed in, do not show the validate code if not on web,
            // because we don't want to block the user with the interstitial page.
            Navigation.goBack();
        } else {
            Session.signInWithValidateCodeAndNavigate(Number(accountID), validateCode);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isNavReady]);

   
    useEffect(() => {
        // Wait till navigation becomes available
        Navigation.isNavigationReady().then(() => {
            setIsNavReady(true)
        })
    }, [])
```




### What alternative solutions did you explore? (Optional)

None

**Comment by Gonals** [comment]
> We should wait till `Navigation.isNavigationReady()` is ready before invoking the effect.

Yep. I was able to reproduce this time

**Comment by mountiny** [comment]
@aswin-s Can you also test if this fixed https://github.com/Expensify/App/issues/35782

**Comment by Gonals** [comment]
@aswin-s, the proposal looks good! I'll assign you so we can get it fixed ASAP! Could you check the other issue @mountiny mentioned [here](https://github.com/Expensify/App/issues/35745#issuecomment-1927129733)?

**Comment by adamgrzybowski** [comment]
Nice! I wonder if this solution could be simplified to this form.
```ts
useEffect(() => {
  // Wait till navigation becomes available
  Navigation.isNavigationReady().then(() => {
    if (session?.authToken) {
      // If already signed in, do not show the validate code if not on web,
      // because we don't want to block the user with the interstitial page.
      Navigation.goBack();
    } else {
      Session.signInWithValidateCodeAndNavigate(Number(accountID), validateCode);
    }    
  })
}, [])
```

**Comment by aswin-s** [comment]
Ok raising PR shortly

**Comment by mountiny** [comment]
@situchan @aswin-s please test on the PR if this was fixed too https://github.com/Expensify/App/issues/35782, thank you!

**Comment by aswin-s** [comment]
@mountiny Recording final video 😎

**Comment by mountiny** [comment]
Feel free to make drafts first in these scenarios so C+ can jump in sooner than later.

**Comment by aswin-s** [comment]
Draft PR [here](https://github.com/Expensify/App/pull/35827)

**Comment by aswin-s** [comment]
> @situchan @aswin-s please test on the PR if this was fixed too #35782, thank you!

@mountiny 

Nope. This one looks like a different issue.  However it affects testing of this issue on desktop environment.

https://github.com/Expensify/App/assets/6880914/b5a3d029-b4f2-4667-b1d2-c7f82fea618a

**Comment by situchan** [comment]
yup different issue.
While #35745 is android/iOS bug, https://github.com/Expensify/App/issues/35782 is web bug (wrongly tagged platform)

**Comment by marcaaron** [comment]
Testing well on iOS staging. Gonna remove the blocker here. Thanks for the quick solutions 🙇

**Comment by johncschuster** [comment]
Payment has been issued! 🎉 

@situchan, can you complete the BZ Checklist above? Thank you!

**Comment by situchan** [comment]
I think this regression came from ideal nav.
As this was caught in staging by QA team, we don't need another regression test.

**Comment by johncschuster** [comment]
Sounds great! Thanks for confirming that!
