### ISSUE TITLE
[$250] Profile - No spacing between zoom/rotate toolbar & save button in edit photo page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35749]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+1117ck@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com & login
2. Tap on settings top icon
3. Tap on edit icon in avatar >> Tap on Upload photo
4. Upload photo from device gallery or take photo

## Expected Result:
There should be enough spacing between zoom/rotate toolbar & save button in edit photo page
Though open app banner is displayed, minimal spacing should be provided between zoom/rotate toolbar & save button

## Actual Result:
No spacing between zoom/rotate toolbar & save button in edit photo page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/38840721-ff3a-4f0d-a9ad-42a79b2bb79a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b1c38630383cb3f</li>
        <li>Upwork Job ID: 1754485497559797760</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:

![Bug6365508_1706922990986!PROD](https://github.com/Expensify/App/assets/78819774/d4e22448-804b-4891-a6d3-73af218a54cf)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by mountiny** [comment]
Not a blocker

@shawnborton could you help us align on the design here please so the proposal can be based on that? thank you!

**Comment by shawnborton** [comment]
Hmm well this is because the button floats on top of the content behind it. I'm not sure if we actually need to consider this a spacing bug. cc @Expensify/design for thoughts too. 

But I think my vote is to just close and do nothing.

**Comment by dannymcclain** [comment]
> But I think my vote is to just close and do nothing.

I'm cool with this—it seems kinda like a pretty weird edge case to me, and it looks like the controls are all still functional.

**Comment by dubielzyk-expensify** [comment]
I actually think we should tweak this screen to always just be 100% height. In my opinion every element on this screen should have a set/fixed height except for the profile image that should scale to fill the remaining. This would allow all the controls to be visible without having to scroll down.

Sorta like this:
![CleanShot 2024-02-06 at 09 53 13@2x](https://github.com/Expensify/App/assets/145416827/1dc13746-0726-455e-8266-8de11103b62c)

In above I've also fixed the icon button to be using the `IconButton` component and icon color being `icon color` instead of white which it is now:
![CleanShot 2024-02-06 at 09 53 40@2x](https://github.com/Expensify/App/assets/145416827/07f69d5c-0337-4ab6-bc28-5c577a902a45)

**Comment by shawnborton** [comment]
Hmm, I'm not sure if I agree with that. On a super short screen, how exactly would the square (with the avatar crop) scale down to be fluid? 

I think this should behave like the Profile > Personal Details > Address page where the green button sits at the bottom of the view when there is extra room available but if the content is too tall, we just put the green button below the content. We do this on the profile page, like so:


https://github.com/Expensify/App/assets/2319350/7838c851-269c-497e-b828-8989a474641a



Good catch on the icon color! We should change that.

**Comment by dubielzyk-expensify** [comment]
Fair enough. I guess I just imagined we scale down the profile picture area like this:
![CleanShot 2024-02-06 at 14 00 29@2x](https://github.com/Expensify/App/assets/145416827/8a254f80-c47b-4316-acdf-23efd6972ae5)

If we don't go with that, then I agree fully with the button being on the bottom of the content. I guess in my head if you can't see the control + profile picture in one screen then that would be weird to me.

**Comment by shawnborton** [comment]
Ah I see what you are saying. Either way though, I still feel like we can just close this one out and do nothing because the Save button sits on top of the content, and it seems like this case mostly happens when you are viewing on mWeb with the native banner showing?

**Comment by dubielzyk-expensify** [comment]
Sure thing 👍

**Comment by amyevans** [comment]
Thanks for the discussion! Closing
