### ISSUE TITLE
[$500] [HOLD for payment 2024-02-20] LHN - User navigated on Workspaces listing page when tapped on the settings tab in bottom

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+omm1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be signed in and
1. Open app
2. Tap on settings tab in bottom

## Expected Result:
User should be navigated on the Expeinsfy (app) settings page

## Actual Result:
User navigated on Workspaces listing page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: IPAD
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/24970b6d-ce86-44a3-a6e6-49265081f05b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cfb17922aff5e23</li>
        <li>Upwork Job ID: 1760013389795655680</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by madmax330** [comment]
Asked about this here: https://expensify.slack.com/archives/C03TQ48KC/p1707124667241939?thread_ts=1706899377.429909&cid=C03TQ48KC

I think it's related to the ideal nav changes

**Comment by mountiny** [comment]
@lanitochka17 @kbecciv Is this ipad specific?

**Comment by mountiny** [comment]
cc @adamgrzybowski

**Comment by lanitochka17** [comment]
@mountiny In IOS, the settings page opens and then a list of workspaces. 
Only IPAD

https://github.com/Expensify/App/assets/78819774/5a257283-7365-4954-85e6-56526af2cb44

**Comment by mountiny** [comment]
PR is up

**Comment by mountiny** [comment]
We need to pay $500 to @situchan for the review and testing here

**Comment by abekkala** [comment]
@situchan Upwork Offer was sent: https://www.upwork.com/nx/wm/offer/101020283

**Comment by abekkala** [comment]
@situchan payment sent and contract ended - thank you! 🎉
