### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500]  LHN - Unable to navigate on the account settings page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35758]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4281766&group_by=cases:section_id&group_id=306202&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+omm1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be Signed In
1. Open app
2. Navigate on LHN
3. Tap on account icon on top right corner

## Expected Result:
User should be navigated on the account settings page

## Actual Result:
User navigated on Profile page when tapped on account icon in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: IPAD
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d35693f1-a1c4-40e6-8727-871339ccc170

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f78a2e9f606211ba</li>
        <li>Upwork Job ID: 1754494613216841728</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by mountiny** [comment]
This is large ipad specific bug, SWM is looking into a general solution, it has most likely something to do with logic depending on the screen size because we are forcing ipad to portrait mode even if the screen width exceeds what we would normally display as wide view on desktop.

This breaks the app behaviour on ipad so its high urgency, tracking all the ipad specific issues on slack thread [here](https://expensify.slack.com/archives/C036QM0SLJK/p1707137489876029)

**Comment by mananjadhav** [comment]
@mountiny Are we covering all the linked issues in one PR? Does it need additional testing?

**Comment by mountiny** [comment]
merged

**Comment by dylanexpensify** [comment]
coming up!

**Comment by mountiny** [comment]
We can close this one now, this was handled by agency and Situ reviewed
