### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] LHN - Workspace announce chat opened when selected workspace on "Choose workspace" page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35759]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+omm1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be Signed In
1. Open app on iPad device
2. Tap on Expensify icon on top left corner
3. Tap on any listed workspace

## Expected Result:
User should be navigated to LHN and workspace icon should be displayed on top left corner

## Actual Result:
User navigated to the workspace announce chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: IPAD
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e0b559f4-ae86-4c79-bae4-fd63a468dd3e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141942de109a98fd5</li>
        <li>Upwork Job ID: 1754495988513861632</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Ipad specific issue @adamgrzybowski tracking in thread https://expensify.slack.com/archives/C036QM0SLJK/p1707137489876029

**Comment by joekaufmanexpensify** [comment]
@situchan offer sent for $500 in upwork!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set!
