### ISSUE TITLE
Workspace - Workspace owner is empty when created on one device and viewed on another device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35757]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is logged in to the same account on two devices
1. [Device A] Click Settings from the bottom to open workspace list overview
2. [Device B] Open workspace switcher
3. [Device B] Click + to create a new workspace
4. [Device A] Note the newly created workspace

## Expected Result:
The workspace owner of the new workspace will be displayed on Device A

## Actual Result:
The workspace owner of the new workspace created on Device B is empty when viewed on Device A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/af17ba1f-3395-4523-9d0a-e2f49eb1a11f

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018213f83dc9fc4b3c</li>
        <li>Upwork Job ID: 1754451858135121920</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by mountiny** [comment]
I will have to handle this one internally, seems like we do not push this data correctly to the same client.

**Comment by mountiny** [comment]
Was focusing on other issues

**Comment by mountiny** [comment]
Did not get around to this yet, making it weekly since we got some changes underway with policy sharing

**Comment by mountiny** [comment]
Havent got around to this one

**Comment by mountiny** [comment]
Will try to address this week

**Comment by mountiny** [comment]
Pr is up in review https://github.com/Expensify/Web-Expensify/pull/41355
