### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] LHN - User navigated on the workspace overview page when created workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35755]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4281765&group_by=cases:section_id&group_id=306202&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+omm1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user should be Signed In
1. Open app
2. Tap on "Expensify" icon on top left corner
3. Tap on plus button

## Expected Result:
User should be navigated on workspace settings page

## Actual Result:
User navigated on the workspace overview page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: IPAD
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3c344a16-5eca-4c41-9c8f-4dd60d707d4c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f365ee4965dd88d</li>
        <li>Upwork Job ID: 1754492566143000576</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by mountiny** [comment]
We got couple of these iPad specific bugs cc @adamgrzybowski

**Comment by mountiny** [comment]
SWM is looking into these

**Comment by DylanDylann** [comment]
This issue is fixed by another PR. Could you help to confirm this issue is resolved then we can close this one

**Comment by mountiny** [comment]
Lets consolidate payments on this issue https://github.com/Expensify/App/issues/35752
