### ISSUE TITLE
[HOLD for payment 2024-02-22] [$250] Workspace - Workspace highlighted member blinks when check/uncheck mark

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35761]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Workspace> Members
2. Check mark any member (Admin should not be the first on the list)

## Expected Result:
Selected member should not blink

## Actual Result:
Workspace member blinks when check/uncheck mark

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/cda2fac8-09bb-4fb8-9e3e-c26c03769379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faff94e6cefb944b</li>
        <li>Upwork Job ID: 1754496368396689408</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28150587</li>
<li>Krishna2323 | Contributor | 28150588</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave
CC @greg-schroeder

**Comment by mountiny** [comment]
@Krishna2323 can you please link offending PR

**Comment by mountiny** [comment]
Moving the price down since this seems like easy bug to solve

**Comment by luacmartins** [comment]
Still looking for proposals

**Comment by shubham1206agra** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/35761#issuecomment-1925787163) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by miljakljajic** [comment]
@shubham1206agra I can't pay you until you accept the offer in upwork

**Comment by miljakljajic** [comment]
@Krishna2323 paid, thank you!

**Comment by miljakljajic** [comment]
Paid!
