### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] Chat - App crashes when tapping device back button to return from thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35765]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Navigate to any chat
3. Send a message and start a thread
4. Tap the device's back button on the navigation bar or swipe left (Pixel)
5. After returning to the chat, start typing

## Expected Result:
The text is displayed in the compose box, user can continue to interact with the app

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a46d1b13-7baa-434c-810b-3eafc17b34d4

https://github.com/Expensify/App/assets/115492554/2f09b458-24e2-4981-a358-51188d999965

[Bug6366182_1706984503745!log.txt](https://github.com/Expensify/App/files/14154363/Bug6366182_1706984503745.log.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c33c369e718efc4</li>
        <li>Upwork Job ID: 1753898689311535104</li>
        <li>Last Price Increase: 2024-02-03</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by mountiny** [comment]
@fedirjh are you able to reproduce?

**Comment by tomekzaw** [comment]
@fedirjh Thanks for sharing the error, are you able to share the whole stack trace as well?

**Comment by kbecciv** [comment]
Samsung Galaxy A52s 5G, Android 14 - reproducible

https://github.com/Expensify/App/assets/93399543/9cb104d1-3cfd-4896-979a-83edcfcc5a76

**Comment by tomekzaw** [comment]
Thanks, I'm working on a fix.

**Comment by thienlnam** [comment]
Will take this over as BZ

**Comment by tomekzaw** [comment]
I was able to reproduce this issue on Android emulator (Pixel 6 API 34 virtual device).

**Comment by sakluger** [comment]
Sent an offer to @fedirjh via Upwork. @fedirjh could you please complete the BZ checklist?

**Comment by sakluger** [comment]
@fedirjh confirmed that he is not due any payment on this issue, we're good to close out the issue.
