### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] LHN - Unable to navigate to workspace settings from bottom tab and from Workspace listing page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35764]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition: a few workspaces should be created
1. Open app
2. Tap on the "Expensify" icon on top left corner
3. Tap on any listed workspace
4. Tap on back button
5. Tap on Chat tab on bottom nav panel
6. Tap on Back button
7. Tap on Settings icon in bottom navigation page
8. Tap on back button
9. Tap on Workspace icon on top left corner
10. Tap on "Expensify"
11. Tap on any listed workspace

## Expected Result:
Step 7 and 11: user should be navigated to the workspace

## Actual Result:
Step 7 and 11: user navigated on the workspace overview page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop
- [x] iPad Pro 11" 2020/iPadOS 17.2

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2816ef45-cd9a-48d5-be5a-01ffe8f17c69

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b82db16dc264309</li>
        <li>Upwork Job ID: 1753896928387526656</li>
        <li>Last Price Increase: 2024-02-03</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
@mountiny is @adamgrzybowski working on these iPad issues? Should we remove the `Help Wanted`?

**Comment by mountiny** [comment]
Yep this is addressed, thanks!

**Comment by jliexpensify** [comment]
@allroundexperts does the checklist need to be completed here? Thanks!

**Comment by mountiny** [comment]
No I think we do not need it here

**Comment by mountiny** [comment]
Additionally, there is nothing to pay here actually
