### ISSUE TITLE
[HOLD for payment 2024-02-20] [$250] Profile - Error message when loading User / WS avatar has incorrect dimensions and position

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35777]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+020224dr02@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open iOS/Android App or go to staging.new.expensify.com on mobile Chrome / Safari
2. Login with any account
3. Go to User profile and load user avatar with incorrect size to generate an error message
4. Create existing workspace or go to existing one
5. Go to Overview and load Workspace avatar with incorrect size to generate an error message

## Expected Result:
The error message has the correct dimensions and position

## Actual Result:
User avatar -> Error message overlaps user name
WS avatar -> Error message takes up the entire width of the screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6366478_1707015780141!iOS-WS-Avatar-Error](https://github.com/Expensify/App/assets/78819774/96c066d1-7b55-4374-9eba-5c99f1ef1d73)

![Bug6366478_1707015780153!iOS-User-Avatar-Error](https://github.com/Expensify/App/assets/78819774/0f333364-4543-4192-b1f0-12728f777d04)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bfbb99c962ed2f1</li>
        <li>Upwork Job ID: 1754499172400123904</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28149470</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Profile - Error message when loading User / WS avatar has incorrect dimensions and position

### What is the root cause of that problem?

The `errorStyles` prop is passed in the `AvatarWithImagePicker` component for the `InitialSettingsPage`.

While in the [`WorkspaceOverviewPage`](https://github.com/Expensify/App/blob/0ae07beca171d01640ec6ebb6b4ece08d53147bc/src/pages/workspace/WorkspaceOverviewPage.js#L100-L102), `errorRowStyles ` is left out.

https://github.com/Expensify/App/blob/0ae07beca171d01640ec6ebb6b4ece08d53147bc/src/pages/settings/InitialSettingsPage.js#L314

### What changes do you think we should make in order to solve the problem?


Remove the `errorStyles` prop and match any styles from the `AvatarWithImagePicker` component in `WorkspaceOverviewPage` to `InitialSettingsPage` for consistency.

**Comment by mountiny** [comment]
Lowering the rewards since this is a simple styling change

@dubielzyk-expensify could you please also clarify how this should look like? thank you!

**Comment by CortneyOfstad** [comment]
Payment is scheduled for Tuesday 👍

**Comment by CortneyOfstad** [comment]
Not overdue, as the PR went into staging 3 days ago. Payment is still scheduled for Tuesday, barring any regressions 👍

**Comment by CortneyOfstad** [comment]
Alright payment summary below!

## Payment Summarty

@bernhardoj (Contributor) — **paid $250 via Upwork**
@thesahindia (C+) — **to be paid $250 via NewDot**

**Comment by CortneyOfstad** [comment]
@thesahindia any update on the checklist [here](https://github.com/Expensify/App/issues/35777#issuecomment-1942137463)?

**Comment by CortneyOfstad** [comment]
@thesahindia in regards to the checklist, do you think this could be completed by EOD today? Also, has a request been sent to NewDot for payment? Thanks!

**Comment by CortneyOfstad** [comment]
Thanks @thesahindia!

**Comment by JmillsExpensify** [comment]
$250 for @thesahindia
