### ISSUE TITLE
WS Members - 'Back' leads to invite members page instead of Settings after delete added user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35776]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+020224dr02@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open iOS/Android App or go to staging.new.expensify.com on mobile Chrome / Safari
2. Login with any account
3. Create existing workspace or go to existing one
4. Got to WS > Members > Invite new member
5. Select and invite any members
6. Remove added members
7. Tap 'Back' button on top left corner

## Expected Result:
User goes to the WS Settings page

## Actual Result:
User goes to the 'Invite new members' page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/976b6621-051d-4d2c-bd59-1d6557b05ce4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by mountiny** [comment]
I think this is same generic issue with the goBack we are aware of @adamgrzybowski is working on a fix

**Comment by mountiny** [comment]
@adamgrzybowski is working on the back issues, can you please comment here?

**Comment by mountiny** [comment]
This is not repro anymore after the ideal nav v2 🚀
