### ISSUE TITLE
[$500] [MEDIUM] IOU - Report fields are blank after refresh or leave from report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35772]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** applausetester+01022024_emp@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34483
## Action Performed:
1. In Old dot, create a new Collect / Control policy
2. Go to the settings of this workspace and execute the following in console:
p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = "true";
p.save();
3. Go to the reports section of the settings of the newly create workspace and add some report fields
4. Invite a user to be a member of this new workspace
5. In NewDot, login as the invited user. Make sure canUseReportFields beta is enabled for the user
6. Go to the workspace chat room and request some money
7. Open the created expense report
8. Verify that the custom fields show up
9. Click on each of the field
10. Enter a value and save it

## Expected Result:
Make sure that the field gets saved successfully and you can submit report

## Actual Result:
When leaving and re-entering the report the fields have been cleared, it also happens after refreshing
Report present error after you try to submit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/842003eb-35b0-48f2-a679-89a519135913

https://github.com/Expensify/App/assets/78819774/62527d66-9eeb-47f4-ad63-1a9f32e72ccf

https://github.com/Expensify/App/assets/78819774/c18a6e9d-062f-4a97-a67a-d232613ae4a6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fe95e1509261ee2</li>
        <li>Upwork Job ID: 1754149879851364352</li>
        <li>Last Price Increase: 2024-02-11</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment]
Repro steps are clear and this seems like something that should be fixed. Let's wait for some proposals.

**Comment by getusha** [comment]
Thanks @HezekielT
@stephanieelliott could we get internal engineer on this?

**Comment by stephanieelliott** [comment]
I think this should be tackled as part of Wave 6, posted to get confirmation [here](https://expensify.slack.com/archives/C02MW39LT9N/p1707429072769279) as a first step to try and source an internal engineer.

**Comment by getusha** [comment]
backend issue

**Comment by stephanieelliott** [comment]
Hey @thienlnam I noticed you are working on a bunch of issues related to report fields -- any chance you have the bandwidth to grab this one too?

**Comment by thienlnam** [comment]
Yeah, I thought this was solved but I can take another look

**Comment by stephanieelliott** [comment]
Fix for this is on staging

**Comment by stephanieelliott** [comment]
Solved internally, no C+ review on this one so no payment due
