### ISSUE TITLE
[$500] Send money  -For send money, merchant shown as " Request "

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35784]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4281379
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab----Send money
3. Enter an amount and tap next
4. Select a contact
5. Tap payelsewhere
6. Tap the send money request created to open details page
7. Note the merchant field

## Expected Result:
For send money, merchant must not be shown as " Request "

## Actual Result:
For send money, merchant shown as " Request "

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2e12ba07-b1c8-4392-9a0b-1135e28a4325

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133847fab45efc929</li>
        <li>Upwork Job ID: 1754204504573894656</li>
        <li>Last Price Increase: 2024-02-04</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
It seems this Bug is from BE

**Comment by tgolen** [comment]
What is the expectation, that the merchant line is not shown at all, or that something other than "Request" is shown for the merchant? Also, what makes this a backend issue?

**Comment by deetergp** [comment]
That's a good question… If a user is just sending money to another user, does there need to 
be a merchant line at all? Wouldn't the merchant just be the sender? Maybe we should require the description field for Send Money to be filled out. (Venmo requires this)

**Comment by deetergp** [comment]
The merchant value of `Request` is coming from the back end.
![Screenshot 2024-02-05 at 3 39 42 PM](https://github.com/Expensify/App/assets/766197/5fbdd5f2-e206-4a1a-b4e7-c6ba6699afc7)
![Screenshot 2024-02-05 at 3 37 20 PM](https://github.com/Expensify/App/assets/766197/7b0b534a-386f-406e-98db-c1674dd8c73a)

**Comment by deetergp** [comment]
It's set in `Transaction::createMoneyRequest` in Auth.

**Comment by lisishyn** [comment]
There is already a nail for "Request" (CONST.TRANSACTION.DEFAULT_MERCHANT) in the MoneyRequestPreview.
https://github.com/Expensify/App/blob/500dd0949123ae1cd7b84211c0093f3c832d6775/src/components/ReportActionItem/MoneyRequestPreview.tsx#L163

**Comment by lisishyn** [comment]
Contributor details
Your Expensify account email: lisishyn.v+expensify@proton.me
Upwork Profile Link: https://www.upwork.com/freelancers/~015703306bbdfe0891

**Comment by deetergp** [comment]
Started an internal conversation about this in [#vip-split](https://expensify.slack.com/archives/C05RECHFBEW/p1707244879273649).

**Comment by deetergp** [comment]
Based on the conversation in the above thread, we are ultimately going to only ever show Amount and Description on Send money requests.  Merchant will no longer be display once the work in [this internal GH](https://github.com/Expensify/Expensify/issues/345849) is complete. Closing this one out.
