### ISSUE TITLE
[$500] Partial payment for #31190

### ISSUE THREAD

**Issue by greg-schroeder** [Expensify/App#35793]
Pulled from https://github.com/Expensify/App/issues/31190
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127354caaeddf2978</li>
        <li>Upwork Job ID: 1754395634012393472</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Offer sent @shubham1206agra, accept and I'll pay ASAP

**Comment by shubham1206agra** [comment]
Offer accepted

**Comment by greg-schroeder** [comment]
paid!
