### ISSUE TITLE
[New Lib] heic2any

### ISSUE THREAD

**Issue by BartoszGrajdek** [Expensify/App#35798]
# Name of library: heic2any

## Details
- Link to package:
	- npm: https://www.npmjs.com/package/heic2any
	- github: github.com/alexcorvi/heic2any
	- docs: https://alexcorvi.github.io/heic2any/

- Problem solved by using this package:
Issue: https://github.com/Expensify/App/issues/12531

We want to handle previews of image files, HEIC files included which are not fully supported yet. 

Recently we have added `expo-image` to the project, this allows us to handle HEIC files on Android & iOS, but unfortunately web/desktop is still not supported ([docs](https://docs.expo.dev/versions/latest/sdk/image/)).

Now we have discussed a few possibilities ([here's the Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1705930052644969)), but in the end settled on using `expo-image` we already have in the project for mobile and `heic2any` on web/desktop. This way we won't change the mobile bundle size and have all devices with working previews.

- Number of stars in GH: 519
- Number of monthly downloads: ~370k in the last month
- Number of releases in the last year: 1
- Level of activity in the repo: low - 17 open issues, 0 open PRs
- Alternatives:

The main alternative (it's ~0.4MB bigger) we could consider using is [libheif](https://github.com/strukturag/libheif), but the problem is that it's written in C++ and it's not providing any easy-to-use JS bundle. To utilize it we would need to set up a custom way to include it in our project i.e. using web assembly. 

- Are security concerns brought up and addressed in the library's repo?
Not that I know of, but this is not the type of library that would raise any security concerns.
- How many dependencies does this lib use that will be brought into our code? 
0
- What will the effect be on the bundle size of our code? 
This library would add 1.3MB to web & desktop bundles, but since won't use it on mobile we want to make sure it doesn't affect iOS/android bundle sizes.

**Comment by Julesssss** [comment]
Reading through the discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705930052644969) it looks positive, but I'll need to share a brief overview comment and tag the internal team.

**Comment by BartoszGrajdek** [comment]
@Julesssss done 😄 https://github.com/Expensify/App/issues/12531#issuecomment-1926683973

**Comment by Julesssss** [comment]
[Proposal](https://github.com/Expensify/App/issues/12531#issuecomment-1926683973) for solution

- Are all the answers in the main description filled out properly and make sense?
    - ✅ 
- Who maintains the library and how well is it maintained?
    - A popular Github user: https://github.com/alexcorvi
- How viable are the alternatives?
    - Not viable. We'd have to ignore a major issue where we don't support images on certain platforms. Or we'd have to implement backend logic with unnecessarily complicated logic 
- Should we build it ourselves instead?
    - No. Lets save our time and rely on a widely used existing solution.

**Comment by Julesssss** [comment]
[Here's](https://expensify.slack.com/archives/C01GTK53T8Q/p1707130645906709) the Slack vote

**Comment by Julesssss** [comment]
Tagging @Expensify/mobile-deployers again, as the final vote will be on this issue.

**Comment by Julesssss** [comment]
After a [good discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1707130645906709), we are aligned on not implementing the library and not trying to solve the problem with an alternative solution. 

We'll do nothing for now as this is an edge case with solutions relying on workarounds, large libraries, and non-cross-platform solutions. 

Closing this issue.

**Comment by Beamanator** [comment]
Reopening b/c we have a new request to use this library here: https://github.com/Expensify/App/issues/47078#issuecomment-2275891488

I am working on writing this up in Slack today 🙏

**Comment by Julesssss** [comment]
@Beamanator can you create a new issue for the updated conversation please

**Comment by Beamanator** [comment]
Surrreeeeeeeeeeeee nothingmoreintheworldthati'dratherdoooooooooooo
