### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] IOU - From link in header show "IOU" instead of <User owes $XX> in request page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account
3. Search for user & navigate to 1:1 DM
4. Tap on + icon >> Request money
5. Create IOU request
6. Navigate to IOU request page

## Expected Result:
From link in header should display <User owes $XX> in request page

## Actual Result:
From link in header show "IOU" instead of <User owes $XX> in request page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6367161_1707089818019!PROD](https://github.com/Expensify/App/assets/115492554/42460de1-6ead-4978-b892-df9f51dce36f)

https://github.com/Expensify/App/assets/115492554/dc76f8f1-87bf-4ff1-9195-ef45444a969c

https://github.com/Expensify/App/assets/115492554/964157d2-03a4-44d9-bc3f-afe13529ca3e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144d7b31b30f3c313</li>
        <li>Upwork Job ID: 1754457125768007680</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by Julesssss** [comment]
Raised in Slack [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1707133399675029). I'm going to remove the deploy blocker label as this is relatively minor and doesn't break the app in any way. We have 30/40 other deploy blockers to resolve today 😬. 

I checked the checklist and codebase and couldn't locate an obvious PR that introduced this, so we'll get this resolved as a typical external issue in the meantime.

**Comment by salmannotkhan** [comment]
@izarutskaya cannot reproduce the bug. I am able to see <User owes $XX>.

<img width="1512" alt="Screenshot 2024-02-05 at 5 25 38 PM" src="https://github.com/Expensify/App/assets/26996284/66c5ce23-bb3e-4c05-90ee-c0f54abb76c9">

**Comment by salmannotkhan** [comment]
Contributor details
Your Expensify account email: tony903212@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/salmannotkhan

**Comment by Julesssss** [comment]
Thanks @salmannotkhan .

That's odd, earlier today I could reproduce. But now I'm unable to either 😕

**Comment by Julesssss** [comment]
Okay, with a brand new user, I can reproduce. However, I need to confirm whether this behaviour is actually a desired change. 

**Report Page:** 

<img width="914" alt="Screenshot 2024-02-05 at 12 10 49" src="https://github.com/Expensify/App/assets/10736861/0393ea59-091a-4886-b097-d9e97f28af26">

**Request page:**

<img width="907" alt="Screenshot 2024-02-05 at 12 10 42" src="https://github.com/Expensify/App/assets/10736861/27bbe113-e884-4f83-af55-0e011133013b">

**Comment by salmannotkhan** [comment]
I just created both users and it worked as expected. But there is some delay when new user logs in and the account details are set properly. Maybe that's causing this issue.

**Comment by Julesssss** [comment]
After logging back in I can still see the 'IOU' report name. I'm going to wait for confirmation before continuing further.

**Comment by jcdiprose** [comment]
Contributor details
Your Expensify account email: calumdiprose@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013dde27dcb7ec1563

**Comment by trjExpensify** [comment]
@Julesssss this is a bug, the page header of an IOU shouldn't be `IOU`. I bet it comes from #wave6 and the default report title implementation. CC: @thienlnam @caitlinwhite1

**Comment by trjExpensify** [comment]
In fact, why are we showing report fields and a report title at all for an `iouReport`? Aren't those workspace features? 😕

**Comment by thienlnam** [comment]
Yeah there's a bug where report fields are showing for free workspaces since they seem to come initialized with a text_title report field. Currently working through it here https://github.com/Expensify/App/issues/35694

**Comment by trjExpensify** [comment]
Ah, but this isn't the free plan. These are off-workspace P2P requests between two members on an `iou` type report.

**Comment by JmillsExpensify** [comment]
I agree that we should never show editable titles, whether off workspace or the Free plan. (Equally, the Free plan is being deprecated in the coming months, so ideally the logic is more tied to only showing customizable report titles on paid Group plans (eg Collect and Control).

**Comment by thienlnam** [comment]
Hmm yeah, I guess then we should update this in the FE to not override for IOU reports cc @allroundexperts

**Comment by thienlnam** [comment]
@allroundexperts By the way, I'm going to update the BE so that openReport does not send back reportFields for any report type except expense reports right now. I think that should also solve things so that they do not need to be updated on the FE

**Comment by allroundexperts** [comment]
@thienlnam [PR](https://github.com/Expensify/App/pull/36044) created for enabling this on paid workspaces only.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/34483
- The offending PR has been commented on: Not needed since the author fixed the bug
- A discussion in #expensify-bugs has been started: Not needed (a unique bug)
- Determine if we should create a regression test for this bug: Given that free policies are being deprecated, we won't need a regression test

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR FEB 20

- Issue reported by: Applause-Internal Team
- Fix: @allroundexperts [$500 - pending no regressions] **Request Payment in NewDot** 
- PR Review: @s77rt [$500 - pending no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/100981838)

**Comment by abekkala** [comment]
@s77rt payment was sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
### **NewDot** Payment Summary: 

- Fix: @allroundexperts [$500] **Request Payment in NewDot**

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary above.
