### ISSUE TITLE
[MEDIUM] Feature Request: Make attachments to show immediately like the regular messages

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35819]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707112380464339

## Problem: 
If I post a message like "Hello world", it'll appear exactly as if I had already sent it -- even if in fact it's still uploading it.  It will also show grayed out if I'm offline, to indicate it hasn't sent.  But we treat attachments differently: we show a static Uploading attachment... message, which is replaced with the preview after upload.   I'm not even sure if it works offline, or what it shows while it's queued for offline upload.
## Solution: 
Let's make attachments work like regular posts in that we should show the attachment immediately in its final location, exactly as if it uploaded instantly.  If we are offline and it hasn't yet uploaded, then show the preview grayed out.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Going to close this as a dupe, as we're working on making this a reality already. From the long list of dependencies, there's this one to support image caching: https://github.com/Expensify/App/issues/12603

Unfortunately, the [latest PR](https://github.com/Expensify/App/pull/34505) for it was deployed and then reverted on Friday last week. So we need to revisit that with @kidroca to fix and redeploy.

After which, we can get back to implementing a solution for this feature request [here](https://github.com/Expensify/App/issues/9402). I've put that issue in #vip-vsb as a medium to track. 👍
