### ISSUE TITLE
[HOLD for payment 2024-03-11] [$500] when a user leaves a thread, clicking the back button does not navigate them back to that specific thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35810]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705948892215059

## Action Performed:

1. Join a thread by commenting in it
2. Leave the thread and get taken back to the DM or channel
3. Hit the back button (or three-finger swipe, cmd + [)

## Expected Result:
you are taken back to the thread you were just viewing
## Actual Result:
that thread does not appear in the history, and you are taken back to whatever chat you were viewing before

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166e0dcdf98b9fd23</li>
        <li>Upwork Job ID: 1756011506926768128</li>
        <li>Last Price Increase: 2024-02-16</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by muttmuure** [comment]
Hm, I couldn't reproduce this

**Comment by muttmuure** [comment]
Interesting - I can reproduce this

**Comment by muttmuure** [comment]
I can still see the thread in search

**Comment by muttmuure** [comment]
However the back button indeed doesn't work to navigate back to the thread I just left. It seems like some polish an external contributor could handle

**Comment by FitseTLT** [comment]
This is intentional @muttmuure We remove it from route history. 
https://github.com/Expensify/App/blob/b9aada861c4e740a422a44c4c13c245382b1f082/src/libs/actions/Report.ts#L2277-L2289

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If someone sends a message in a thread and leaves it disappear from their LHN

### What is the root cause of that problem?
We `goBack` in here before navigating to the reports after leaving thread so it will be removed from the route history so navigating back will not navigate to the thread
### What changes do you think we should make in order to solve the problem?

I think this behaviour ^ should only be applied for rooms but for a thread we should n't `goBack` so change it to
```
if (lastAccessedReportID) {
        // We should call Navigation.goBack to pop the current route first before navigating to Concierge.
        if (ReportUtils.isChatRoom(report)) {
            Navigation.goBack(ROUTES.HOME);
        }
        Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(lastAccessedReportID));
    } else {
        const participantAccountIDs = PersonalDetailsUtils.getAccountIDsByLogins([CONST.EMAIL.CONCIERGE]);
        const chat = ReportUtils.getChatByParticipants(participantAccountIDs);
        if (chat?.reportID) {
            // We should call Navigation.goBack to pop the current route first before navigating to Concierge.
            if (ReportUtils.isChatRoom(report)) {
                Navigation.goBack(ROUTES.HOME);
            }
            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(chat.reportID));
        }
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
@muttmuure I had a second thought on https://github.com/Expensify/App/issues/35810#issuecomment-1936343050 I think we should only clear it from history for chat rooms for simple chat threads we shouldn't so I have commented a proposal based on it.

**Comment by muttmuure** [comment]
@akinwale mind reviewing [the proposal](https://github.com/Expensify/App/issues/35810#issuecomment-1936386620) above?

**Comment by muttmuure** [comment]
@FitseTLT can you raise your PR? Thanks!

**Comment by techievivek** [comment]
Gentle bump @FitseTLT for the PR. Thanks.

**Comment by FitseTLT** [comment]
@techievivek we might need to change title based on https://github.com/Expensify/App/issues/35810#issuecomment-1936335886

**Comment by techievivek** [comment]
Done. 👍

**Comment by jjcoffee** [comment]
@FitseTLT The loop starts around 23 seconds in the linked video. I'd expect in this case:

1. Navigate back from report --> thread
2. Navigate back from thread --> report
3. Navigate back from report --> LHN

Anything else is pretty poor UX, I think. It _is_ a bit of an edge case to join/leave the thread multiple times, but I'm a bit unsure if implementing the behaviour in this issue is worth introducing that new issue.

**Comment by FitseTLT** [comment]
Considering the changes we made here the behaviour is similar to what it would behave if we did this 
https://github.com/Expensify/App/assets/38649957/cc94a530-81f1-46e5-9a1b-7ae2352b161e

I don't call that a loop @jjcoffee

**Comment by badeggg** [comment]
Yeah, not a real loop, that's why I put the word in quotation marks

**Comment by techievivek** [comment]
Not overdue, payment is due on 11 March.

**Comment by techievivek** [comment]
Oops, looks like automation didn't work here. @muttmuure Could we issue the payment here.

**Comment by techievivek** [comment]
Gentle bump @muttmuure to look into the payment for this GH. 🙏

**Comment by muttmuure** [comment]
Was out of office, looking now!

**Comment by muttmuure** [comment]
All paid

**Comment by muttmuure** [comment]
@akinwale @FitseTLT please can you recommend if we need a regression test

**Comment by techievivek** [comment]
Gentle bump @akinwale @FitseTLT  for the regression tests here.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not necessarily a regression. The behaviour was intentionally modified.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify.
2. Join a thread by commenting in an existing thread or start a new thread.
3. Leave the thread.
4. Navigate back (using the Back button or a shortcut for navigating back).
5. Verify that the app navigated back to the same thread that was just exited.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@techievivek Done!

**Comment by techievivek** [comment]
Looks good to me, @muttmuure can we add this to testrail? thanks.

**Comment by techievivek** [comment]
Gentle bump @muttmuure for adding the regression test to testRail.

**Comment by muttmuure** [comment]
Done
