### ISSUE TITLE
[$500] New Workspace button does not work

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#35820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v1.4.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Sign up to an account which does not have any workspace yet
2. Click the wrench to go to Settings
3. Go to workspaces
4. Click the `New Workspace` button in the big section block
5. Verify the workspace got created

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019da9053a5e89dbe2</li>
        <li>Upwork Job ID: 1754522202320949248</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 28142786</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
PR in review

**Comment by mountiny** [comment]
This was fixed

**Comment by jliexpensify** [comment]
Upworks job closed

**Comment by mountiny** [comment]
Thanks!
