### ISSUE TITLE
HIGH: remove all room welcome message related code

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#35859]
We replaced the welcome note feature with a room description feature in https://github.com/Expensify/App/issues/32953. Now that the front-end and back-end have been finished, let's remove all welcome message related code.

**Comment by quinthar** [comment]
What's your ETA for this?

**Comment by puneetlath** [comment]
This is on staging.

**Comment by puneetlath** [comment]
Everything here has been merged. Just awaiting Auth deploy which will happen early next week.

**Comment by puneetlath** [comment]
This is done.
