### ISSUE TITLE
[$500] Android - IOU – Amount value appears with a delay when edit amount.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35896]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app.
2. Log in
3. Tap FAB button > Request money
4. Select Manual tab
5. Complete the flow till the confirmation step.
6. Click on Amount ield to edit

## Expected Result:
Amount value appears immediately when edit amount

## Actual Result:
Amount value appears with a delay when edit amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ab55a8a8-0e25-4649-941e-4888cdb9dd3f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4b53b2db033fef5</li>
        <li>Upwork Job ID: 1754834230431821824</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by abekkala** [comment]
@izarutskaya I think this is actually #vip-split
I'm confirming in slack

**Comment by abekkala** [comment]
waiting on proposals

**Comment by abdulrahuman5196** [comment]
No proposals yet

**Comment by abekkala** [comment]
https://expensify.slack.com/archives/C03UK30EA1Z/p1707851163102419

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by abekkala** [comment]
Thanks @rezkiy37

**Comment by rezkiy37** [comment]
So, I've tried to reproduce those performance troubles. On my simulators, it works pretty smooth. I ask my colleagues to test on real Android devices. Will post an update soon.

https://github.com/Expensify/App/assets/57314631/e3df1b12-a24e-43a8-88b0-5edec48e5e77

**Comment by rezkiy37** [comment]
We tested this flow on a real Android device (_Samsung A34 6GB RAM/128GB_) one more time. Looks like it works fine. IOS is still much smoother, but I don't see the bug with a huge delay. So, I would say that it is not replicable.

<details><summary>Recordings</summary>
<p>

https://github.com/Expensify/App/assets/57314631/acc4c811-987e-4547-b92f-c2bc0f7f12ca


https://github.com/Expensify/App/assets/57314631/00593ecd-d1a3-4574-88b8-e62fef6e6697

</p>
</details>

**Comment by abekkala** [comment]
Thank you @rezkiy37
