### ISSUE TITLE
[$500] IOU - Page shows spinner after returning from Amount editor in confirmation page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35893]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-37.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Manual.
3. Enter amount > Next.
4. Proceed to confirmation page.
5. Click Amount.
6. Click Back button.

## Expected Result:
App returns to confirmation page without loading.

## Actual Result:
App loads briefly when returning to confirmation page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3c29b2f9-9d39-455b-a5ad-33d56826a128

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df4afe95e80594cd</li>
        <li>Upwork Job ID: 1754827608947040256</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-bills 
CC @davidcardoza

**Comment by shubham1206agra** [comment]
This is intentional to show the spinner as it might show outdated currency, which might be confusing to the user. See https://expensify.slack.com/archives/C01GTK53T8Q/p1705504483396879?thread_ts=1704818739.022579&cid=C01GTK53T8Q also.

**Comment by luacmartins** [comment]
This was indeed discussed and we landed on the current spinner solution. I'm not sure that this is the best UX, but this is definitely not a blocker. Gonna close the issue. Thanks everyone!
