### ISSUE TITLE
[Pay 2024-03-06][$500] [CRITICAL] Backwards Compatibility: Disabled tag is not displayed in the list as selected

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35909]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition: Employee made an IOU request with a tag in WS chat. Tag is disabled after that by WS admin in OD.

1. Employee in ND: click on IOU request to open request details.
2. Click on the tag field

## Expected Result:
The disabled tag is displayed in the list as selected

## Actual Result:
The disabled tag is not displayed in the list as selected

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Bug6369435_1707232600509!stage](https://github.com/Expensify/App/assets/38435837/8af33810-1a9e-44bc-a0e0-8747f3a53824)

![Bug6369435_1707232600519!prod](https://github.com/Expensify/App/assets/38435837/8b8f31f7-9da7-4948-90f4-f0ba9fb04bb7)

https://github.com/Expensify/App/assets/38435837/211f15a6-7347-4be5-bf60-227b8aa6f16e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d431d3f18048470e</li>
        <li>Upwork Job ID: 1757799767331749888</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by m-natarajan** [comment]
We think that it will be under the wave [#wave6-collect-submitters]
cc @greg-schroeder

**Comment by marcaaron** [comment]
>Reproducible in production?: n

@m-natarajan can you give some more context about why this issue was created and how we deemed it to be a deploy blocker?

**Comment by mallenexpensify** [comment]
Pinged @m-natarajan in Slack with the link since this is time sensitive.

**Comment by marcaaron** [comment]
>Precondition: Employee made an IOU request with a tag in WS chat. Tag is disabled after that by WS admin in OD.

If there are steps required to reproduce the bug please list out exactly what actions were taken. Thanks!

**Comment by marcaaron** [comment]
I can't reproduce this on `main`, `production` or `staging` so I am going to guess it has been fixed. Gonna remove the blocker for now.

**Comment by m-natarajan** [comment]
@marcaaron Regression step https://expensify.testrail.io/index.php?/cases/view/2761738 is failing. I am adding a new video here.

https://github.com/Expensify/App/assets/38435837/ef1a4ba6-6419-4e54-83ba-8116c827125d

**Comment by mallenexpensify** [comment]
Thanks for the vid @m-natarajan 

> The disabled tag is not displayed in the list as selected

I'm unsure of the specifics but, from a common sense level, I would think this would be expected behaviour.  If a tag is disabled, the user/submitter should not see that tag as an option.

**Comment by kbecciv** [comment]
There is an inconsistency between the category and tag, can someone review the issue again? Thanks

https://github.com/Expensify/App/assets/93399543/d924d442-38fd-4284-a28a-94d3aafbe802

**Comment by mallenexpensify** [comment]
Thanks for reopening @kbecciv , 
> Tag - Disabled tag is not displayed in the list as selected #35909

@DylanDylann can you see if you're able to reproduce?  I just added you to `Collect policy Feb 12 2024` policy on the collect plan as a Workspace admin, I used dylandylan....@outlook.com email address, the one from Slack.  

Thx

**Comment by DylanDylann** [comment]
Will check on Feb 15

**Comment by DylanDylann** [comment]
I still can reproduce on the latest main

https://github.com/Expensify/App/assets/141406735/0eab09bf-6a5f-4f75-85e2-db027278d129

**Comment by DylanDylann** [comment]
We have the same bug with category [here](https://github.com/Expensify/App/issues/35553)

**Comment by DylanDylann** [comment]
>  If a tag is disabled, the user/submitter should not see that tag as an option.

@mallenexpensify In this case, this tag is selected before the admin disables it. So I think It makes sense to display the selected tag (even though this tag is disabled). It also be the way that we use in the category list

**Comment by mallenexpensify** [comment]
> It makes sense to display the selected tag (even though this tag is disabled). It also be the way that we use in the category list

@DylanDylann for the category example, when is the category item removed? ie. in your tag example screen vid above, would `Drink` still show, then when `Food` is clicked, is that the timing the `Drink` option would not be shown, cuz it's disabled?

**Comment by DylanDylann** [comment]
> would Drink still show, then when Food is clicked, is that the timing the Drink option would not be shown, cuz it's disabled?

Yes. This is the way that we applied to the category page and I think It also makes sense to apply to tag page

**Comment by greg-schroeder** [comment]
Is this actually `Internal` though, or can it be sent through the `External` flow? It's a backwards compatibility bug related to Tags so definitely a Wave 6 Critical

**Comment by cead22** [comment]
I think this can be external. @DylanDylann if you like the proposed solution, can you put a bow on it and make it official? 🎀

**Comment by greg-schroeder** [comment]
Fair enough - I'll check back tomorrow!

**Comment by DylanDylann** [comment]
@dukenv0307's proposal looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by greg-schroeder** [comment]
Waiting for deploy to prod

**Comment by mallenexpensify** [comment]
[Deployed to product 2 days ago](https://github.com/Expensify/App/pull/36994#issuecomment-1970131161) 🎉 
Updated title to pay on 3/6

**Comment by DylanDylann** [comment]
@mallenexpensify Should we add Daily label to move forward this issue

**Comment by mallenexpensify** [comment]
Contributor: @dukenv0307 paid $500 via Upwork
Contributor+: @DylanDylann paid $500 via Upwork 

Created a TestRail GH, reckon it'll be an edge case one we'll only check monthly.  Thx everyone.
