### ISSUE TITLE
IOU - 'Hmm.. it's not here' page is displayed when opening IOU report details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Apply offline mode
2. Create an IOU with user B
3. Click on the IOU preview component
4. Click again on the IOU preview component of IOU reports page
5. Come back to online mode

## Expected Result:
* IOU details reports page should load when opening in offline mode
* IOU details page should be displayed when coming to online mode

## Actual Result:
* IOU details reports page didn't load when opening in offline mode
* Hmm it's not here page is displayed when coming to online mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/05c5acaf-8115-4091-877a-b5140fc86ce0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to [#vip-bills](https://expensify.enterprise.slack.com/archives/CSL3XBCCR)
CC @davidcardoza

**Comment by youssef-lr** [comment]
Investigating
