### ISSUE TITLE
[$500] Task - Task is not marked as complete in user WS employee B (not task creator, not admin)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4282503
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition
• A workspace admin
• A workspace employee A (task creator)
• A workspace employee B
All accounts should be added to the workspace of the workspace admin
1. Go to https://staging.new.expensify.com/
2. Login as the workspace employee A
3. Navigate to the workspace #Announce room,
4. Create a task
5. Login as the workspace employee B in incognito tab
6. Navigate to the workspace #Announce room
7. As user A complete the task
8. As B observe the task
9. As user A incomplete the task
10. As B observe the task

## Expected Result:
Task is marked as complete in user WS employee B (not task creator, not admin) of the WS #Announce room when it was marked as complete by WS employee A (task creator, not admin)

## Actual Result:
Task is not marked as complete in user WS employee B (not task creator, not admin) of the WS #Announce room when it was marked as complete by WS employee A (task creator, not admin)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/097fa226-bf12-4412-9c33-801ce16eae43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c10fd1b691a5068</li>
        <li>Upwork Job ID: 1754872755617296384</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinter

**Comment by Habtamu-Asefa** [comment]
> We think that this bug might be related to #vip-vsp CC @Quinter

what does #vip-vsp mean?

**Comment by twisterdotcom** [comment]
Maybe we can make this weekly. Still awaiting proposals though!

**Comment by quinthar** [comment]
Demoting to FUTURE as it involves tasks, which we aren't prioritizing (but if we can get a contributor to do it, go for it!)

**Comment by c3024** [comment]
Not reproducible anymore


https://github.com/Expensify/App/assets/102477862/9ca01382-eb9d-4c95-9c0b-e81ad5b3f534
