### ISSUE TITLE
Room - Adding markdown to room description appears and then disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35901]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0507gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34150
## Action Performed:
1. Create a new workspace.
2. Go to 'FAB -> Start Chat> Room
3. Enter room name
4. Add custom description with any markdown> Complete the room creating flow
5. Take a note of the description on chat history, header and edit description

## Expected Result:
Description should be displayed with markdown as user enter it

## Actual Result:
Adding markdown to description when create room is not applied in header and above composer ( appears in flash and than disappears)
It only applies when edit the description and add markdown. In offline mode, it works fine - added markdown in description while creating room remains on header, above the composer and on edit description page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8d0e76e8-171a-4038-bac9-aba2e0fb706a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Gonals** [comment]
Not a blocker. [This is a known issue being worked on](https://github.com/Expensify/App/pull/34150#issuecomment-1930019101). Closing.
