### ISSUE TITLE
[HOLD for payment 2024-02-15] [HOLD for payment 2024-02-14] [$500] 0 is showing up in black small font in split bill preview

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.37-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @alitoshmatov 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707150156382219

## Action Performed:
1. Open group with 2 other accounts
2. Split bill
3. Scan receipt
## Expected Result:
0 shouldn't show up like that for amount
## Actual Result:
In split preview there is a zero showing small black font
## Workaround:
UNknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-02-05 at 21 17 37](https://github.com/Expensify/App/assets/38435837/e4634e20-fd90-4045-a49b-6108f9363e5b)
<img width="1440" alt="Screen Shot 2024-02-06 at 10 37 24 AM" src="https://github.com/Expensify/App/assets/38435837/7b007b3c-d99b-4529-8901-9b19572cc2da">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01071057525b16cfaa</li>
        <li>Upwork Job ID: 1754897944662765568</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28146438</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Cool, confirming @VickyStash we're handling it here right? https://github.com/Expensify/App/pull/35916 

@situchan, shall I assign you both here?

**Comment by situchan** [comment]
yes please

**Comment by VickyStash** [comment]
@trjExpensify yes, mentioned PR should fix the issue

**Comment by trjExpensify** [comment]
Cool, done! Are we tracking the deploy blocker on the OG issue or need it here?

**Comment by situchan** [comment]
May need it here

**Comment by aldo-expensify** [comment]
Merged the fix: https://github.com/Expensify/App/pull/35916

**Comment by aldo-expensify** [comment]
Requested CP here: https://expensify.slack.com/archives/C07J32337/p1707243919696259

**Comment by aldo-expensify** [comment]
Confirmed that it got fixed by https://github.com/Expensify/App/issues/35915#issuecomment-1930521210

<img width="723" alt="image" src="https://github.com/Expensify/App/assets/87341702/fef89cda-6a14-46bf-a043-1a92f4529e91">

**Comment by trjExpensify** [comment]
@situchan confirming there's nothing for us to do on this regression issue, right? We can close it out as the OG issue is where any payment and what not will happen?

**Comment by situchan** [comment]
I am eligible here as I was not involved in offending [PR](https://github.com/Expensify/App/pull/34564)

**Comment by trjExpensify** [comment]
Ah cool, okay. Settled up $500 with you for the review. Closing!
