### ISSUE TITLE
IOS - Tapping Download on “Share code” doesn’t always work

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34580

## Action Performed:
1. Launch the app and tap on the avatar on top right
2. Tap on Share code > Download

## Expected Result:
An image is downloaded with the QR code

## Actual Result:
Most of the times nothing happens. If the Download icon is tapped several times rarely it does work

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/401add3f-cda6-48fd-abd1-de19d54d0acc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by situchan** [comment]
[Commented](https://github.com/Expensify/App/pull/34580/files#r1480245350) with the solution in offending PR

**Comment by marcaaron** [comment]
@thienlnam do we need to CP this one to staging?

**Comment by thienlnam** [comment]
Ah I didn't realize this was linked to a blocker - yeah I can get this CPed sorry

**Comment by thienlnam** [comment]
Closing - this was a regression that was fixed by the original author / reviewers
