### ISSUE TITLE
[$500] Room - Header does not show #room in <workspace> for room with description on web app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35911]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .1.4-37.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35321
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > New chat > Room
3. Create a room with description
4. Go to the room
On Android, the room header shows #room in <workspace> in Android but not on web

## Expected Result:
On web app, the room header will show #room in <workspace>, which is the behavior on Android

## Actual Result:
On web app, the room header shows only #room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b40e63bd-300d-4686-ae62-fa9bf6089498

https://github.com/Expensify/App/assets/78819774/04815990-c3c1-4745-a7fc-1c94979aaba1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac483655847bcd27</li>
        <li>Upwork Job ID: 1754890325915394048</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by muttmuure** [comment]
closing
