### ISSUE TITLE
[$500] Thread - Some of the threads can't be opened from the LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35914]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34640
## Action Performed:
1. Navigate to any chat with a "hidden" user
2. Write 5 text messages and reply in thread for each
3. Go to the LHN and open all of the threads

## Expected Result:
I should be able to open any thread

## Actual Result:
Some of the threads can't be opened from the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/29026ea2-0b24-455a-9dc6-5e23b94ef4e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143ac6740a81b3d9a</li>
        <li>Upwork Job ID: 1754962173583876096</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Issue is not reproducible in Production:

https://github.com/Expensify/App/assets/78819774/a4fbb5c1-d982-4e6d-8333-880dec67932b

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by amyevans** [comment]
Was able to repro on staging iOS on my phone. Still fighting with simulators so that I can get more insight into the error

**Comment by amyevans** [comment]
A few observations:
* It's irrelevant whether the chat is with a "hidden" user or a known user
* The issue only occurs after the initial thread creation, once you navigate around a bit more it is no longer present

**Comment by amyevans** [comment]
Anyway I don't think this needs to be a deploy blocker, going to demote it and open up for external help.

**Comment by lschurr** [comment]
Any update here @cubuspl42?

**Comment by lschurr** [comment]
@amyevans are we just waiting on proposals right now?

**Comment by amyevans** [comment]
Yep seeking proposals

**Comment by cubuspl42** [comment]
I have nothing to say, awaiting proposals 🙂

**Comment by lschurr** [comment]
Still waiting on proposals.

**Comment by Victor-Nyagudi** [comment]
Is this still reproducible? 

Everything's working fine on my end.

**Comment by cubuspl42** [comment]
As this is a recurring aspect of multiple issues, I [confirmed on Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1708419228746899) that this is the responsibility of QA and BZ to verify whether the issue is reproducible when there's doubt.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by amyevans** [comment]
I retested as well and can't repro, let's close!
