### ISSUE TITLE
[HOLD for payment 2024-02-15] [HOLD for payment 2024-02-14] [$500] [Wave8] [Ideal Nav] Hide `Subscriptions` menu item on iOS and Android native 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#35932]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1707240281243759

## Action Performed:
1. Go to new.expensify.com on iOS/Android native 
2. Click the wrench tab 
3. Observe the `Subscriptions` menu item in the LHN

## Expected Result:
Due to restrictions with the App store, we should hide this menu item on iOS and Android native devices. 

## Actual Result:
We don't hide it, and that puts us at risk of being pulled from the app store. 

## Workaround:
Yes, they can go to mWeb or to web/desktop to see the subscription menu item. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native (incl. iPadOS)
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_5651](https://github.com/Expensify/App/assets/16232057/fbf7622c-c09f-4317-a028-49a902d9bff3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @mountiny @hayata-suenaga 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6bee6862397d920</li>
        <li>Upwork Job ID: 1754927211226951680</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28146833</li>
<li>codinggeek2023 | Contributor | 28146834</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
P.S when we raise the PR for this can we request a CP to staging, to minimise the delay in getting this onto production.

**Comment by mountiny** [comment]
We do not allow `Platform.OS ` in our codebase, use platform specific files.

**Comment by sofi-a** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hide Subscriptions menu item on native platforms.

### What is the root cause of that problem?
The menu item was added intentionally.

### What changes do you think we should make in order to solve the problem?
Create a module `getShouldShowSubscriptionsMenu` in `src/libs` that returns a platform-specific value for showing/hiding the subscription menu item.

src/libs/getShouldShowSubscriptionsMenu/index.ts
```js
/**
 * Indicates whether the subscription menu should show in the all settings screen
 */
const getShouldShowSubscriptionsMenu = (): boolean => true;

export default getShouldShowSubscriptionsMenu;
```

src/libs/getShouldShowSubscriptionsMenu
```js
/**
 * Indicates whether the subscription menu should show in the all settings screen
 */
const getShouldShowSubscriptionsMenu = (): boolean => false;

export default getShouldShowSubscriptionsMenu;
```

Import and use the module to conditionally insert the Subscriptions menu item in `src/pages/home/sidebar/AllSettingsScreen.tsx`.

```js
import getShouldShowSubscriptionsMenu from '@libs/getShouldShowSubscriptionsMenu';
...
            },
            ...(getShouldShowSubscriptionsMenu() ? [{
                translationKey: 'allSettingsScreen.subscriptions',
                icon: Expensicons.MoneyBag,
                action: () => {
                    Link.openOldDotLink(CONST.OLDDOT_URLS.ADMIN_POLICIES_URL);
                },
                shouldShowRightIcon: true,
                iconRight: Expensicons.NewWindow,
                link: CONST.OLDDOT_URLS.ADMIN_POLICIES_URL,
            }] : []),
            {
...
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by hayata-suenaga** [comment]
[asking for a quick proposal review](https://expensify.slack.com/archives/C02NK2DQWUX/p1707247840381859).

**Comment by trjExpensify** [comment]
Alright, going to pay this one out. No regression, something we missed in implementation design.

**Comment by trjExpensify** [comment]
Paid! Summary as follows: 

- $500 to @codinggeek2023 for the fix
- $500 to @aimane-chnaif for the review.
