### ISSUE TITLE
[Wave Collect] [Ideal Nav] Refactor `goBack` to simplify the navigation logic

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#35938]
### Issue
The logic and responsibility of the `goBack` function grew too much over time.

### Solution
Split the `goBack` function into different functions to ensure it is easy to use and debug in the future

### Background
Several regressions occurred from the Ideal Navigation PR, particularly concerning the back navigation behavior. The complexity of the `goBack` function may be responsible for some of these regressions. @adamgrzybowski has suggested a refactor of this function to prevent similar issues in the future.

**Comment by hayata-suenaga** [comment]
@adamgrzybowski please comment on this issue so that I can assign you to it. 🙇

**Comment by adamgrzybowski** [comment]
👋

**Comment by hayata-suenaga** [comment]
this is a refactoring issue that is complicated. Adam is going to work on it when they have time.

**Comment by trjExpensify** [comment]
This should minimally be `weekly` priority though, right?

**Comment by hayata-suenaga** [comment]
there is a new project dashboard?

**Comment by trjExpensify** [comment]
Yep, #wave-collect is where the party is at!

**Comment by mountiny** [comment]
@adamgrzybowski how is this one looking? What are the next steps?

**Comment by adamgrzybowski** [comment]
@mountiny I need to fix tests for [this PR](https://github.com/Expensify/App/pull/38161). After that I can focus on the goBack if this is the most urgent thing. 

It would be great to have @WojtekBoman around for some brainstorming though. The go back is used in a lot of places and we don't want to miss any use cases. He will be back on Monday (18.03)

I was asked to help with this issue https://github.com/Expensify/App/issues/36476 so maybe I could work on it in the meantime.

**Comment by jliexpensify** [comment]
Moving back to `Weekly`, how are we going with this one?

**Comment by hayata-suenaga** [comment]
@adamgrzybowski, let me know your availability and when you're planning to work on this refactor. Depending on when you're planning to work on this, we can adjust the priority back to `weekly` 😄

**Comment by adamgrzybowski** [comment]
@hayata-suenaga I think we will take care of that after preparing section for the search tab in the design docs

**Comment by hayata-suenaga** [comment]
Melvin -> `@hayata-suenaga I think we will take care of that after preparing section for the search tab in the design docs`

**Comment by adamgrzybowski** [comment]
Hi! I just got back from vacation, so I'll take a look around and let you know.

**Comment by hayata-suenaga** [comment]
welcome back! 😄

**Comment by jliexpensify** [comment]
Hi @adamgrzybowski is this one going to be worked on by any chance? Juat wondering what the priority is. Thanks!

**Comment by jliexpensify** [comment]
Got it, thanks! @trjExpensify - going off Adam's comment above: did you want to keep this one open, or can I close this issue?

**Comment by trjExpensify** [comment]
The problem in the OP seems suitably vague, and we've fixed the bugs that came up during the rollout, so I'm good with closing this until we get a more concrete problem for refactoring goBack.
