### ISSUE TITLE
[HOLD for payment 2024-03-04] [$500] [MEDIUM] Categories: Selected category not highlighted if other category removed by WS Admin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35945]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4283510
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisites: Collect Policy with enabled Categories, which has < 8 Categories has been created in OD. Employee has been invited to the Policy
1. Log in to New Expensify as Employee from prerequisites
2. Navigate to workspace chat > start manual request
3. Enter an amount > Next > Category > Select any Category
4. Tap Category once more
5. As Workspace Admin in OD - remove any other Category

## Expected Result:
The removed category should disappear from Employee's categories list, and the selected category should remain highlighted

## Actual Result:
The removed category disappears from Employee's category list. However, the first category in the list is highlighted instead of the selected one

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/34dcbe92-b27b-49c1-a675-7e2da8adccfa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1a6471df7b92a86</li>
        <li>Upwork Job ID: 1754942209808277504</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6 
CC @greg-schroeder

**Comment by stephanieelliott** [comment]
Hey @allroundexperts we've got a proposal here, can you please review when you get a sec?

**Comment by allroundexperts** [comment]
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/35945#issuecomment-1931335618) looks good to me. It has the correct RCA and the solution makes sense as well.

🎀 👀 🎀 C+ reviewed

**Comment by stephanieelliott** [comment]
PR is undergoing QA

**Comment by stephanieelliott** [comment]
PR is on staging

**Comment by stephanieelliott** [comment]
This was deployed to prod on 2/28, seems the automation didn't work so am updating manually

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @dukenv0307 $500 PAID via Upwork 
 - Contributor+: @allroundexperts $500 please request via ND
 
 Upwork job is here: https://www.upwork.com/jobs/~1737876297360310272

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary.
