### ISSUE TITLE
[$500]  Web - Avatar - Upload photo modal covers small part of Account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35949]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [gocemate@gmail.com](mailto:gocemate@gmail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings> Click on Avatar
3. Upload photo modal will appear

## Expected Result:
Upload photo modal should not covers Account

## Actual Result:
Upload photo modal covers part of Account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4a06f3b1-7a3f-4d92-89db-8666ed021e05

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fe3456902ef0cd8</li>
        <li>Upwork Job ID: 1754944671872176128</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by dannymcclain** [comment]
I'm really struggling to see the issue here?

Are you talking about the menu that has options for upload/remove/view being positioned over some of the left hand nav? If so, that is absolutely expected behavior.

**Comment by dannymcclain** [comment]
Definitely! Think of that menu like a context menu—it should sit above all other elements so the user can see it/focus on it/interact with it.
