### ISSUE TITLE
Split scan - On creating Split scan in WS, shows 0 in preview in mweb , app crashes in android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34092
## Action Performed:
1. Go to mweb and app
2. Open a Worksoace chat
3. Tap plus icon near compose--- split money
4. Tap scan
5. Using camera upload an image
6. Tap split
7. In mweb, in scan request preview 0 is shown and in android app crashes

## Expected Result:
While making split scan request in Workspace, in mweb, in scan request preview 0 must not be shown and in android app must not crash

## Actual Result:
While making split scan request in Workspace, In mweb, in scan request preview 0 is shown and in android app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/390fe7f5-1b53-4ff3-840f-4e205b31796f

https://github.com/Expensify/App/assets/78819774/c92f44ac-69c3-4a04-85d0-f8ce96ea265d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by rlinoz** [comment]
I think this PR caused it: https://github.com/Expensify/App/pull/34564

But apparently a [fix is being CP'd](https://github.com/Expensify/App/issues/35915#issuecomment-1930521210), which I think will fix this as well, let's see

**Comment by aldo-expensify** [comment]
Confirmed that it got fixed by https://github.com/Expensify/App/issues/35915#issuecomment-1930521210

<img width="723" alt="image" src="https://github.com/Expensify/App/assets/87341702/fef89cda-6a14-46bf-a043-1a92f4529e91">
