### ISSUE TITLE
 Bank account - Form is filled with data entered on previous add BA flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35944]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-2
**Reproducible in staging?:** Y
**Reproducible in production?:** unable to check on prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4283348
**Email or phone of affected tester (no customers):** applausetester+vd_web020624@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged and have created a workspace
1. Go to Workspaces > Select Workspace > Bank account
2. Tap on "Connect online with Plaid"
3. Select Wells Fargo and the account ending in 1111 (use testing credentials)
4. Once you reach de Company information page, enter the Legal business name
5. Tap on the arrow to go back to initial BA page
6. Tap on "Connect online with Plaid"
7. Select Wells Fargo and the account ending in 1111 (use testing credentials)
8. Reach Company information page again

## Expected Result:
The new form should be empty, with no previous data

## Actual Result:
The new form is filled with the data entered on the previous add BA flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3de16d60-f55b-41ad-84b6-8d973e507a27

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
Are you sure this is not expected? @nkuoch do you know for sure or not? Maybe this has recently changed, but to me it kind of seems like having the information saved on the company step and not erasing it each time is a better UX for the user.

**Comment by nkuoch** [comment]
I think it's expected. I agree with Tim it's a better UX this way.

**Comment by tgolen** [comment]
Thank you! I'm going to close this out then.
