### ISSUE TITLE
[$500]  IOS - Workspace - Default currency is ignored

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35956]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a workspace
2. Go offline
3. Create an IOU in a workspace chat with any currency that isn't the workspace default one
4. Open the IOU

## Expected Result:
The total should be 0 until coming online and should be using the workspace default currency

## Actual Result:
The total is displayed in the requested currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ea8ed2ab-76d1-4b4e-a04f-29941d020945

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f233ce8cd32c5963</li>
        <li>Upwork Job ID: 1754967996431261696</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by jacobkim9881** [comment]
It seems related to [this issue](https://github.com/Expensify/App/issues/35209)

**Comment by c3024** [comment]
@alexpensify This is expected behaviour and introduced in #33171 and [discussed on Slack](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1701181431339359) as well. This issue can be closed.

**Comment by alexpensify** [comment]
@c3024 - thanks for flagging! I'm going to close now.
