### ISSUE TITLE
Closing a Missing Translation SmartScan and re-SmartScanning results in duplicates.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction (could not replicate the missing translation error)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707205368678779

## Action Performed:

1. SmartScan a receipt and get the Missing Translation error
2. Click on the X next to the error
3. First SmartScan disappears
4. SmartScan same receipt

## Expected Result:
only one receipt is smartscanned

## Actual Result:
New request appears along with the old (cancelled) request, and is also duplicated.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot_20240206-183856](https://github.com/Expensify/App/assets/38435837/4909cdf3-f93d-4b4f-8548-5f3aaae46ec4)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
Related to [this](https://expensify.slack.com/archives/C049HHMV9SM/p1707250800777729?thread_ts=1707205368.678779&cid=C049HHMV9SM) slack conversation let's test again and see if this can be reliability reproduced.

**Comment by slafortune** [comment]
moving to weekly to retest

**Comment by slafortune** [comment]
I am not able to recreate this - are you @m-natarajan ?

**Comment by slafortune** [comment]
This will be retested this week with a comment added in GH - I've also added that to SO https://expensify.slack.com/archives/C9YU7BX5M/p1708966883170439

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by slafortune** [comment]
Thanks @mvtglobally !  Closing
