### ISSUE TITLE
[$500] Impossible to select text when text composer expanded

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35951]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-1
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707062629670319

## Action Performed:

1. Write a very long message
2. Opt to expand the text input
3. Try to make it to the top of the input or select any text

## Expected Result: 
You can scroll/select within the expanded text input
## Actual Result: 
The text input resets to the bottom and doesn’t allow you to select anything

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/468decce-0838-4c63-b777-84cb83027a4c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195fbdbbcfcd6d823</li>
        <li>Upwork Job ID: 1754951427629330432</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment]
I cannot reproduce this on a 15 max

**Comment by kaushiktd** [comment]
I cannot reproduce this on XR and 13.
