### ISSUE TITLE
[LOW] DeleteWorkspace doesn't use optimistic reportAction data

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#35952]
Coming from https://expensify.slack.com/archives/C035J5C9FAP/p1706800444942609...

### Problem
When we delete a workspace in NewDot, we create an optimistic `CLOSED` reportAction on the policy rooms, policyExpenseChat, etc...

However, that optimistic reportActionID is not used by the back-end.

### Solution

Update `DeleteWorkspace` to follow our offline-first patterns and accept the optimistic reportActionIDs of the `CLOSED` actions and use them when closing reports in the back-end.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116862805e09bb850</li>
        <li>Upwork Job ID: 1754951538014932992</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
@perunt can you help clarify that effect this has on the end-user?

**Comment by perunt** [comment]
Currently, it doesn't impact users as we filter out this type of action. 
It is more important for Comment Linking as we need a proper message chain. But it also isn't a blocker, as the optimistic response can be temporarily removed.

**Comment by CortneyOfstad** [comment]
@roryabraham any update on @perunt's comment above? Thanks!

**Comment by CortneyOfstad** [comment]
Bump @roryabraham ^^^

**Comment by CortneyOfstad** [comment]
@roryabraham can you confirm that you saw @perunt's comment [here](https://github.com/Expensify/App/issues/35952#issuecomment-1931717518)? Thank you!

**Comment by roryabraham** [comment]
Sorry for the delays - I'm not assigned to this issue so it's not in my K2, and I got behind on my email inbox.

It seems like this is a lower priority issue, but still one that we should fix. Going to make this weekly and move it to LOW in Wave 6. It's internal so we'll just need an Expensify engineer with bandwidth to take this on. Hopefully it should be included in the daily/weekly breakdown for wave6 issues in the slack channel and get a volunteer before too long.

**Comment by roryabraham** [comment]
I think I should have time to handle this next week, so I'm picking it up

**Comment by roryabraham** [comment]
Got the front-end code written: https://github.com/Expensify/App/pull/36757

The PR could have been a bit smaller, but I did some cleanup / optimization while I was updating the function and am going to have to test it anyways.

**Comment by CortneyOfstad** [comment]
@roryabraham any update on the PR? Thanks!

**Comment by roryabraham** [comment]
yep, I started working on automated tests, should be able to get the front-end PR ready by tomorrow. Will need two more PRs in Web-E and Auth thereafter. I think this is more appropriate as a weekly as I am still prioritizing [this MEDIUM wave5 issue](https://github.com/Expensify/Expensify/issues/358172) over this.

**Comment by roryabraham** [comment]
Also this is really just an optimization, not really preventing anything from working correctly for now.

**Comment by CortneyOfstad** [comment]
No worries and thanks for the update @roryabraham!

**Comment by CortneyOfstad** [comment]
Adjusted this back to weekly, as Rory indicated that this isn't hindering any other aspects of Expensify, but geared towards optimization. Low priority, so we're still good here 👍

**Comment by CortneyOfstad** [comment]
@roryabraham @allroundexperts I am going to be heading OoO (back March 10th). Going to adjust this to Monthly in the meantime (will adjust when I am back) but if there is anything timely that needs to be adjusted in the meantime, please re-assign the Bug label 👍 Thanks!

**Comment by CortneyOfstad** [comment]
Not overdue. Priority is pretty low (`polish`) 👍 

@roryabraham if the expectations have changed, let me know and I can adjust the status and time label. Thanks!

**Comment by roryabraham** [comment]
Note that we'll need to uncomment [this code](https://github.com/Expensify/App/pull/30269/files#diff-cd0dfd9f8af5bc7cd33ff4f0337ef70574d42424ceecd7692b193348d3d8ecd4R828-R835) when this is done

**Comment by CortneyOfstad** [comment]
@roryabraham any updates? Thanks!

**Comment by CortneyOfstad** [comment]
Bump @roryabraham ^^^

**Comment by roryabraham** [comment]
sorry, I know it has been a few weeks without updates here. In that time we landed comment linking and the new arch, and have had a number of urgent issues/fires that have consumed all my attention. Hopefully in a few days, things will settle down and I'll be able to make my rounds on internal issues where I need to actually complete some PRs. Hopefully I can have something by EOW or next week

**Comment by CortneyOfstad** [comment]
Hi @roryabraham! Just doing a check-in to see if we're still on track to have something by EOW? If not, do you think we should adjust the frequency to `monthly`? Just trying to gauge where we're at — thank you!

**Comment by CortneyOfstad** [comment]
Changing this to monthly. @roryabraham feel free to adjust it if need-be 👍

**Comment by CortneyOfstad** [comment]
Not overdue!

**Comment by CortneyOfstad** [comment]
Still not overdue — low priority at this point!

**Comment by trjExpensify** [comment]
Is this issue needed anymore? 🤔 Just thinking we've moved to archiving reports using the isArchived rNVP, so wonder if this CLOSED action consideration is obsolete. CC: @srikarparsi for a second opinion.

**Comment by srikarparsi** [comment]
We still need the [closed action](https://github.com/Expensify/Auth/blob/fe103f3e2b149aecf97f18ace92bb0eae93d18fe/auth/lib/Report.cpp#L1059) because that contains the archived reason we display in the footer. 

<img width="824" alt="image" src="https://github.com/user-attachments/assets/72974135-253a-42b0-a556-6787e5cbd357">

I'll assign myself and if I have time to look into this next week I will.

**Comment by trjExpensify** [comment]
Gotcha, so what are the next steps here? It's a bit unclear, and what impact this is having, especially as it has been open since Feb.

**Comment by srikarparsi** [comment]
Impact:
Basically nothing I believe? @roryabraham correct me if I'm wrong though. It's just that in most places, we optimistically create a report action in the beginning and then use that in the backend. But for this, I believe we didn't follow that [here](https://github.com/Expensify/App/blob/3e5da7810fdc48ce391db3ed3aa7dab86a59c490/src/libs/actions/Policy/Policy.ts#L340-L348).

Next steps:
We would need App, Web and Auth PRs to push and use the right reportActionIDs for this but it's nothing crazy. I just haven't had time to prioritize it over current issues.

**Comment by trjExpensify** [comment]
Alright, but I think if we follow that git blame trail it leads to this issue of Aldo's to address it, so I think this issue is a dupe and we should close it? https://github.com/Expensify/Expensify/issues/383435

**Comment by roryabraham** [comment]
Agree, this is a dupe of https://github.com/Expensify/Expensify/issues/383435. Or technically that one is a dupe of this one. Happy to close this one and let @aldo-expensify handle
