### ISSUE TITLE
[$500] Android – Login – Long loading when navigate via staging sign-in link as 2FA account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35962]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4284910
**Email or phone of affected tester (no customers):** applausetester+dtjpht@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app.
2. In the log in screen enter an account that has 2FA enabled (may be a high traffic account).
3. Verify you're asked for the magic code
4. Navigate to email and locate the magic link
5. Navigate to the staging link

## Expected Result:
2FA code is asked after navigating to the magic link

## Actual Result:
1. Open New Expensify app.
2. In the log in screen enter an account that has 2FA enabled (may be a high traffic account).
3. Verify you're asked for the magic code
4. Navigate to email and locate the magic link
5. Navigate to the staging link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7384e11b-9004-4e41-a41d-d15d8ec92219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5266c2ada8fef23</li>
        <li>Upwork Job ID: 1754979996666306560</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
I don't think this is a priority given normal users won't be using staging.
