### ISSUE TITLE
Split - Avatar is opened with delay when accessing from split bill confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-37.3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB > Request money > Manual
2. Enter amount > Next
3. Select any two participants > Next
4. On the confirmation page, click on one of the participants' name
5. Click on the avatar

## Expected Result:
The user avatar opens with delay

## Actual Result:
The user avatar opens with delay after clicking on user avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d638dc1a-45f8-4799-a223-028fca85f8b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by neil-marcellini** [comment]
I don't really understand the actual vs expected result here. The only difference I see is that the loading spinner shows much more briefly on production vs staging, and that's not a big problem IMO. I'm going to remove the blocker label, and close this issue because I don't see any real problem worth fixing.


> ## Expected Result:
> The user avatar opens with delay
> 
> ## Actual Result:
> The user avatar opens with delay after clicking on user avatar
