### ISSUE TITLE
[HOLD for payment 2024-03-04] [New architecture] Upgrade `@rnmapbox/maps`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35989]
We need to upgrade `@rnmapbox/maps` in order to [use the new architecture in the App](https://github.com/Expensify/App/pull/13767/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R91).

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293430719889

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by roryabraham** [comment]
This is just an issue for an upgrade of an existing library, not a new one. Going to do some recategorization here.

**Comment by WojtekBoman** [comment]
Hey! I’m Wojtek from Software Mansion, an expert agency, and I’d like to work on this issue.

**Comment by roryabraham** [comment]
hey @puneetlath, @situchan should be paid $500 for this review (assuming no regressions)

**Comment by roryabraham** [comment]
PR was deployed to production on 2024-02-26. Should get paid out on 2024-03-04 if no regressions. Not sure why the relevant automations didn't work

**Comment by roryabraham** [comment]
@puneetlath this is ready to pay out on Monday

**Comment by puneetlath** [comment]
@situchan offer is here: https://www.upwork.com/nx/wm/offer/101205813

Please ping me on this issue once you've accepted.

**Comment by situchan** [comment]
Accepted. Thanks

**Comment by puneetlath** [comment]
Paid. Thanks everyone!
