### ISSUE TITLE
[HOLD for payment 2024-03-26] [$500] [New architecture] Replace `@oguzhnatly/react-native-image-manipulator` with `expo-image-manipulator`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35984]
# Name of library: `expo-image-manipulator`

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293319626329

## Details
- Link to package: https://www.npmjs.com/package/expo-image-manipulator
- Problem solved by using this package: The library we're using now (`@oguzhnatly/react-native-image-manipulator`) is a transitive fork of `expo-image-manipulator`. The original package is more actively maintained and uses `expo-modules-core` so it should support both, the new and the old architecture.
- Number of stars in GH: 26.7k
- Number of monthly downloads: 42,954
- Number of releases in the last year: 9
- Level of activity in the repo: high
- Alternatives: @oguzhnatly/react-native-image-manipulator or any of the other expo-free forks of this library.
- Are security concerns brought up and addressed in the library's repo?
- How many dependencies does this lib use that will be brought into our code?

0 – since we already have the Expo modules core.

- What will the effect be on the bundle size of our code?

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f064b153d795f898</li>
        <li>Upwork Job ID: 1766142757478912000</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by kowczarz** [comment]
Hey! I'm Kamil from Software Mansion and I would like to work on this task.

**Comment by roryabraham** [comment]
@mountiny for some context, we _did_ get New Arch support merged for the fork we're currently using, but it has not yet been published to npm. It took about a year for the PR to be reviewed.

The main reason I support this switch is because we're already using a fork of expo-image-manipulator, so using the original source and the most widely adopted version of this library makes sense.

**Comment by kowczarz** [comment]
> What will the effect be on the bundle size of our code?
According to https://bundlephobia.com we will add ~2kB

**Comment by mountiny** [comment]
I will do this tomorrow

**Comment by mountiny** [comment]
Posted here https://expensify.slack.com/archives/C01GTK53T8Q/p1707496462582779

**Comment by jeremy-croff** [comment]
I traced back the reason for using this fork to help determine my decisions and found it here:
https://github.com/Expensify/App/issues/6301#issuecomment-1100758657

Not having expo at the time was the main reason for using the fork, and because we now have it, it totally makes sense to use the original package.

**Comment by roryabraham** [comment]
Want to clarify with whatever C+ gets assigned to this issue that we'll pay a $250 bounty for the review instead of the standard $500

**Comment by mountiny** [comment]
We have got I believe 6 or 7 👍  from App deployers across GH and Slack and 0 pushback so we can go ahead with the PR @kowczarz

**Comment by mountiny** [comment]
Asked for an update on the PR

**Comment by muttmuure** [comment]
On staging

**Comment by mountiny** [comment]
This will be ready for payment for Manan

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor: @kowczarz no payment, agency contributor
C+ Review: @mananjadhav $500 please request in newdot

**Comment by mananjadhav** [comment]
@laurenreidexpensify this issue is not closed. The earlier PR was reverted, and the new one is under review right now. Can you please remove the payout summary and reopen the issue?

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor: @kowczarz no payment, agency contributor
C+ Review: @mananjadhav $500 please request in newdot

@hungvu193 pls apply for payment in upwork - https://www.upwork.com/jobs/~0155bf7bf36c1319ef

**Comment by hungvu193** [comment]
> Payment Summary:
> 
> 
> 
> Contributor: @kowczarz no payment, agency contributor
> 
> C+ Review: @mananjadhav $500 please request in newdot
> 
> 
> 
> @hungvu193 pls apply for payment in upwork - https://www.upwork.com/jobs/~0155bf7bf36c1319ef

I've just applied!

**Comment by PierreAdel** [comment]
**Upwork Proposal: Upgrading React Native Image Manipulator Package**

Dear Team,

To address the issue with the current library, I propose upgrading to the original package, `expo-image-manipulator`, which is more actively maintained and supports both the new and old architecture. By transitioning to this package, we ensure compatibility with Expo modules core and benefit from ongoing updates and enhancements.

**Implementation Plan:**

1. **Assessment:** Evaluate the current usage of `@oguzhnatly/react-native-image-manipulator` in our application and identify any potential dependencies or conflicts.
2. **Migration:** Replace the existing library with `expo-image-manipulator` in our codebase, ensuring compatibility with both the old and new architecture.
3. **Testing:** Conduct thorough testing to validate the functionality and performance of the image manipulation features with the new library.
4. **Deployment:** Once testing is successful, deploy the updated version of the application to production, ensuring a seamless transition for end-users.

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav based on summary.
