### ISSUE TITLE
[HOLD for payment 2024-02-26] [New architecture] Upgrade `react-native-haptic-feedback`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35993]
We need to upgrade `react-native-haptic-feedback` in order to [use the new architecture in the App](https://github.com/Expensify/App/pull/13767/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R138).

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293483457349

**Comment by roryabraham** [comment]
Just an upgrade, not a new lib. Recategorizing...

**Comment by BartoszGrajdek** [comment]
Hey! I'm Bartosz from Software Mansion and I would like to work on this task.

**Comment by roryabraham** [comment]
@lschurr the only remaining TODO here will be issuing C+ payment for the PR review

**Comment by lschurr** [comment]
Thanks @roryabraham - I'll set a payment date once the PR is merged.

**Comment by aldo-expensify** [comment]
Merged

**Comment by roryabraham** [comment]
@lschurr we can pay @sobitneupane $500 for their review of https://github.com/Expensify/App/pull/36160 (assuming no regressions)

**Comment by lschurr** [comment]
Offer sent to @sobitneupane - https://www.upwork.com/nx/wm/offer/101049459

**Comment by sobitneupane** [comment]
@lschurr I will request payment on newDot.

**Comment by lschurr** [comment]
Summary is correct - @sobitneupane will request in NewDot. Closing this one out.

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.
