### ISSUE TITLE
[New architecture] Upgrade `react-native-svg`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35999]
We need to upgrade `react-native-svg` in order to [use the new architecture in the App](https://github.com/Expensify/App/pull/13767/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R160).

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293558602069

**Comment by BartoszGrajdek** [comment]
Hey! I'm Bartosz from Software Mansion and I would like to work on this task.

**Comment by roryabraham** [comment]
Not a new lib, just an upgrade. Recategorizing...

**Comment by mananjadhav** [comment]
@dylanexpensify Can you please assign this issue to me as I helped with the PR review?

**Comment by dylanexpensify** [comment]
done! thanks Matt!

**Comment by roryabraham** [comment]
@mananjadhav should be paid the standard rate of $500 for this PR review assuming no regressions

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @BartoszGrajdek (SWM)
- Contributor+: @mananjadhav $500
Please request!
