### ISSUE TITLE
[HOLD for payment 2024-02-26] [New architecture] Upgrade `react-native-image-picker`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35994]
We need to upgrade `react-native-image-picker` in order to [use the new architecture in the App](https://github.com/Expensify/App/pull/13767/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R140).

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293489023209

Current version: 5.1.0
Target version: 7.0.3+

**Comment by roryabraham** [comment]
Yep, there were a number of plain upgrades that were given the `AutoAssignerAppLibraryReview` label by mistake. Going to recategorize this one like I did the others.

**Comment by roryabraham** [comment]
@slafortune this task is just forked off of a larger task to enable the new react native architecture in E/App. So no action is needed from you at this time, SWM will handle it.

**Comment by BartoszGrajdek** [comment]
Hey! I'm Bartosz from Software Mansion and I would like to work on this task.

**Comment by hayata-suenaga** [comment]
Payment for @DylanDylann as a C+ who reviewed the PR after the regression period is over
PR was made by an expert agency engineer

**Comment by abekkala** [comment]
thanks @hayata-suenaga 

Is this a $250 PR review payment or $500?

**Comment by hayata-suenaga** [comment]
> Is this a $250 PR review payment or $500?
confirming with Rory

**Comment by roryabraham** [comment]
We didn't specify a reduced bounty for this or related issues, so I think it would be the standard $500

**Comment by abekkala** [comment]
@DylanDylann I sent an [offer here](https://www.upwork.com/nx/wm/offer/100946928). 

I see that the PR: https://github.com/Expensify/App/pull/36158 has not merged to production yet. 
Once it's merged to production and the regression waiting is over, I'll initiate payment

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR FEB 26

Fix: @BartoszGrajdek does not require payment 
PR Review: @DylanDylann [Offer](https://www.upwork.com/nx/wm/offer/101020935)

**Comment by abekkala** [comment]
@DylanDylann payment sent and contract ended - thank you! 🎉
