### ISSUE TITLE
[$500] [HOLD for payment 2024-02-26] [New architecture] Upgrade `react-native-android-location-enabler`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35990]
We need to upgrade `react-native-android-location-enabler` in order to [use the new architecture in the App](https://github.com/Expensify/App/pull/13767/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R127).

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293453541029
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a017903571169f78</li>
        <li>Upwork Job ID: 1760735914776907776</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
Just an upgrade, not a new lib. Recategorizing...

**Comment by WojtekBoman** [comment]
Hey! I’m Wojtek from Software Mansion, an expert agency, and I’d like to work on this issue.

**Comment by roryabraham** [comment]
Hey @kevinksullivan, we should pay @DylanDylann $500 for their review of https://github.com/Expensify/App/pull/36122, assuming no regressions

**Comment by kevinksullivan** [comment]
@DylanDylann offer sent, let me know when you accept!

**Comment by DylanDylann** [comment]
@kevinksullivan Accepted. Thanks

**Comment by kevinksullivan** [comment]
all set
