### ISSUE TITLE
[HOLD for payment 2024-02-26] [New architecture] Upgrade `react-native-safe-area-context`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35998]
We need to upgrade `react-native-safe-area-context` in order to [use the new architecture in the App](https://github.com/Expensify/App/pull/13767/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R158).

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293545278399

**Comment by BartoszGrajdek** [comment]
Hey! I'm Bartosz from Software Mansion and I would like to work on this task.

**Comment by roryabraham** [comment]
Just an upgrade, not a new lib. Recategorizing...

**Comment by abdulrahuman5196** [comment]
@dylanexpensify Could you kindly assign me as C+ here?

**Comment by dylanexpensify** [comment]
you are assigned! thanks Matt!

**Comment by roryabraham** [comment]
@abdulrahuman5196 should be paid at standard rate of $500 for the PR review assuming no regressions

**Comment by dylanexpensify** [comment]
payment coming up!

**Comment by abdulrahuman5196** [comment]
BZ checklist:

>Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.
Link the GH issue for creating/updating the regression test once above steps have been agreed upon.

N/A since we upgraded a package.

cc: @dylanexpensify

**Comment by dylanexpensify** [comment]
Perfect, payment today!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @BartoszGrajdek 
- Contributor+: @abdulrahuman5196 $500

Please apply/request!

**Comment by dylanexpensify** [comment]
@abdulrahuman5196 offer sent!

**Comment by abdulrahuman5196** [comment]
@dylanexpensify accepted the offer. Thank you.

**Comment by dylanexpensify** [comment]
done!
