### ISSUE TITLE
[New architecture] Upgrade `react-native-picker-select`

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#35997]
We need to upgrade `react-native-picker-select` in order to use the new architecture in the App. We use [Expensify's for of the library](https://github.com/Expensify/App/blob/27904d1e7404f10ebfe441e44b6b509ff0e26f7f/package.json#L152), and the PR has already been merged - https://github.com/Expensify/react-native-picker-select/pull/12. It would just be the case of changing the commit hash to this one: https://github.com/Expensify/react-native-picker-select/commit/da50d2c5c54e268499047f9cc98b8df4196c1ddf

More context: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293299589539
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707293531588409

**Comment by roryabraham** [comment]
Just an upgrade, not a new lib. Recategorizing...

**Comment by roryabraham** [comment]
@abekkala unassigning you as this task was just forked off from a greater ongoing initiative to unable the new React Native Architecture in E/App.

**Comment by WojtekBoman** [comment]
Hey! I’m Wojtek from Software Mansion, an expert agency, and I’d like to work this issue.

**Comment by roryabraham** [comment]
Hey @abekkala, @shubham1206agra should be paid $500 for their review of https://github.com/Expensify/App/pull/36117 (assuming no regressions)

**Comment by abekkala** [comment]
@shubham1206agra [offer sent](https://www.upwork.com/nx/wm/offer/100947064)

once the regression waiting period has passed, I'll submit payment

**Comment by abekkala** [comment]
@shubham1206agra payment sent and contract ended - thank you! 🎉
