### ISSUE TITLE
[$500] IOU - Request money disappears in employee WS chat after approving request in admin a/c

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36018]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37.0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition: Bank account added in admin account
1. Launch app
2. Login as employee
3. Tap employee WS chat and request money
4. In admin, keep opened employee WS chat in mweb
5. As employee, Quickly tap submit button.
6. Quickly tap approve button in admin account
7. In employee account, tap plus icon, request money option disappears.
8. Go back to LHN
9. Open the employee WS and tap plus icon, now request money option is shown.

## Expected Result:
Request money option must not disappear in employee WS chat after approving request in admin account.

## Actual Result:
Request money option disappears in employee WS chat after approving request in admin account. User can view request money option again only after revisiting the report from LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9eda75a9-b729-41a4-bcdf-854e28c6722d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ab9619130628272</li>
        <li>Upwork Job ID: 1755218870359019520</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #vip-bills
CC @davidcardoza

**Comment by shafiqueqadri** [comment]
After extensive testing and investigation, using three (3) different email ids, we have tried to replicate the issue on staging environments, but it's asking the bank accounts using PLAID. And as such we are unable to replictae this issue and we need your assistance.

We'd like 2 test accounts to further investigate this issue. One account for employees and one for admin. Please advise.

**Comment by bfitzexpensify** [comment]
This is a very specific flow that I don't know we can expect to be replicated often - it requires taking quick, simultaneous submission/approval actions, and then trying to submit another request immediately. 

Given that, I'm going to close this out.
