### ISSUE TITLE
[$500] Android-Chat-There is extra spacing above the header title

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a 1:1 report
3. Note, there is normal spacing above the header title
4. Background the app
5. Kill the app
6. Relaunch the app
7. Note, there is extra spacing above the header title

## Expected Result:
There must be normal spacing above the header title.

## Actual Result:
There is extra spacing above the header title.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9f9e6ba3-557c-4f79-a501-c561e9d1400f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e2cf96ad1c7272b</li>
        <li>Upwork Job ID: 1755204226498359296</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment]
This is the same issue as https://github.com/Expensify/App/issues/34050

**Comment by s77rt** [comment]
@jliexpensify Dupe. Let's close this
