### ISSUE TITLE
[$500] Task - Extra space between [Deleted task] and message in task thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36017]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-38.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to 1:1 DM.
3. Create a task.
4. Go to task thread.
5. Send a message.
6. Delete the task.

## Expected Result:
There will be no extra space between [Deleted task] and message in task thread.

## Actual Result:
There is extra space between [Deleted task] and message in task thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/140d113f-fdfc-4485-8863-1249877c280c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc95f54b175bf754</li>
        <li>Upwork Job ID: 1755217480049831936</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by paultsimura** [comment]
It was caught by @situchan here: https://github.com/Expensify/App/pull/35232#discussion_r1479211061

Will be handled in https://github.com/Expensify/App/issues/33922 as per https://github.com/Expensify/App/pull/35232#issuecomment-1931585293

**Comment by situchan** [comment]
yes dupe

**Comment by puneetlath** [comment]
Ok thanks y'all. Closing as a dupe.
