### ISSUE TITLE
[$500] The formatiing of the header screws up when opening the app after a while

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36027]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** y (It is reproduced for me occasionally)
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707263290336859

## Action Performed:
1. Open the app after leaving in the background
2. Observe the header

## Expected Result:
formatting of the header does not get distorted
## Actual Result:
header formatting screwed up
NOTE: The header fixes itself when I go back to the LHN

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot_20240206-154553](https://github.com/Expensify/App/assets/38435837/83b45e86-d663-454f-89f8-658a9bb954e9)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01645e26f7ca036fa5</li>
        <li>Upwork Job ID: 1755232425164222464</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Could you take a look at this one @allroundexperts?

**Comment by allroundexperts** [comment]
Sorry, I don't see any proposal ready for review yet. Also, this is not reproducible for me. Is it happening on your end @lschurr?

**Comment by lschurr** [comment]
No, I'm also unable to reproduce. Going to close for now.
