### ISSUE TITLE
[$500] Web - Workspace - Offline deleted workspace is not archived before coming to online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.38-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a workspace if you don't have any
2. Apply offline mode
3. Delete the workspace
4. Navigate to the the workspace's announce & admin room
5. Come back to online mode
6. Navigate to the the workspace's announce & admin room

## Expected Result:
Workspace rooms should be archived while user is in offline mode

## Actual Result:
Workspace rooms are not archived while user is in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ac3700cc-c8c0-4035-88d7-311eeb7c5267

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd1aac566250947f</li>
        <li>Upwork Job ID: 1755224820283158528</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #wave6-collect-submitters
CC @greg-schroeder

**Comment by CortneyOfstad** [comment]
Confirming Wave-6 status [here](https://expensify.enterprise.slack.com/archives/C02MW39LT9N/p1707508600333249).

**Comment by DylanDylann** [comment]
Let's close this one
