### ISSUE TITLE
[$500] Expense - Header shows "Receipt missing details" when request without merchant is paid

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36020]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-38.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are part of Collect workspace.
1. [Employee] Go to workspace chat.
2. [Employee] Create a Scan request.
3. [Employee] While the request is scanning, manually enter the amount and leave Merchant empty.
4. [Employye] Submit the report.
5. [Admin] Pay the report.
6. [Employee + Admin] Go to request details page of the paid request that has no merchant.

## Expected Result:
The header of paid request details view will show the amount because the expense preview in report also shows the amount and not "Receipt missing details".

## Actual Result:
The paid request with empty merchant shows "Receipt missing details" on request details page header.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ed212366-24b8-4924-ab53-eb04a5c7b961

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c05a5ddc5aabdcec</li>
        <li>Upwork Job ID: 1755222482491002880</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @tylerkaraszewski</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The header shows receipt missing details even after the request is paid.

### What is the root cause of that problem?
The header will show receipt missing details if there are any missing fields, in this case the merchant.
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/libs/ReportUtils.ts#L2193-L2195

### What changes do you think we should make in order to solve the problem?

If we don't want to show receipt missing details when the request is paid, we can add `isSettled` check.

```
if (!isSettled(moneyRequestReportID) && TransactionUtils.hasMissingSmartscanFields(transaction)) {
```

The `moneyRequestReportID` will be the second params of `getTransactionReportName` and we will pass it from here https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/libs/ReportUtils.ts#L2425 with a value of `report.parentReportID`

_or we can show the amount title "{amount} request" if the amount exists, this means we will only show receipt missing details if amount is missing_

**Comment by Tony-MK** [comment]
@bernhardoj, Have you considered using `transaction?.reportID` for `isSettled` instead of passing `moneyRequestReportID`?

**Comment by bernhardoj** [comment]
@Tony-MK ah, you're right, nice info. Thanks for the input!

[Proposal](https://github.com/Expensify/App/issues/36020#issuecomment-1932176923) updated

**Comment by mollfpr** [comment]
I think we can show the requested amount on settled. The proposal from @bernhardoj looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
Friendly bump @tylerkaraszewski

**Comment by slafortune** [comment]
Sorry I missed "leaving the merchant blank"!  Typically when SS fails it says Unknown merchant - which is something.  Skipping right over if and not letting SS fail leaves it 100% blank which won't ever work.

**Comment by bernhardoj** [comment]
> Skipping right over if and not letting SS fail leaves it 100% blank which won't ever work.

@slafortune sorry, I don't quite understand this. Do you mean we won't be able to manually input an ongoing scan request in the future, thus we close this issue?

**Comment by slafortune** [comment]
Sorry - no, you can enter the merchant manually as well.  If you stop a SmartScan and don't let it enter the merchant and don't enter it you can't submit that.  If the SmartScan can't read the merchant it will call the merchant Unknown Merchant, which is still something entered.  It isn't expected to be able to submit an expense with a blank merchant field, so we can close this.

**Comment by bernhardoj** [comment]
I see. Thanks for clarifying.
