### ISSUE TITLE
[HOLD for payment 2024-02-26] Simplify native attachment gallery 

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#36034]
Internal tracking issue for cleaning up the native attachment gallery/carousel.

In a recent succession of PRs a lot of work has happened on the native attachment carousel and we need to cleanup the code a bit.

Recent PRs were:

- https://github.com/Expensify/App/pull/33756
- https://github.com/Expensify/App/pull/33755
- https://github.com/Expensify/App/pull/31308
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d28994a18233cccb</li>
        <li>Upwork Job ID: 1755254749373579264</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by hannojg** [comment]
@tgolen I can't submit the labels

> Add the labels engineering, daily, internal, bug

**Comment by pecanoro** [comment]
@hannojg I added the labels!

**Comment by hannojg** [comment]
Big thanks!

**Comment by hannojg** [comment]
@kirillzyusko Can you please comment here so the issue can get assigned to you? Thanks!

**Comment by kirillzyusko** [comment]
@hannojg yes, sure

I can work on this ticket

**Comment by mollfpr** [comment]
@pecanoro Could you assign me to the issue? Thank you!

**Comment by tgolen** [comment]
I've added you 👍

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This is an improvement for the attachment gallery components.

>[@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No need new regression step. We already have the test rail for attachment under [Conversation > Attachments and Downloads](https://expensify.testrail.io/index.php?/suites/view/7722&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=292107).

**Comment by mollfpr** [comment]
@kadiealexander Could you give the payment summary for the manual request in NewDot? Thank you!

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor+: $500 @mollfpr via manual request

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr based on summary above.
