### ISSUE TITLE
[$500] [HOLD for payment 2024-02-19] [HOLD for payment 2024-02-15] Request Money - The close button linked to "Request money. Get $250" is not functioning

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36032]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.38-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Tap on the FAB
2. Select "Request money" manually.
3. Add the desired amount.
4.  Observe that the Close button at the bottom of the modal linked with "Request money, $250" is not working.

## Expected Result:
The Close button should close the associated statement

## Actual Result:
The Close button linked to "Request money. Get $250" is not functioning

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/25e8470b-a212-4c80-b1fa-071450b8b517

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140216d69adafd36d</li>
        <li>Upwork Job ID: 1758233563551039488</li>
        <li>Last Price Increase: 2024-02-15</li>
    </ul>
</details>

**Comment by marcaaron** [comment]
@cristipaval I feel like you would have the most context on this one. Do these proposals sound good?

**Comment by cristipaval** [comment]
looking now

**Comment by cristipaval** [comment]
@ZhenjaHorbach I just assigned you to fix the issue. You quickly found the root cause and it looks good to me. Please open a PR asap given that this is a deploy blocker.

**Comment by cristipaval** [comment]
@puneetlath I took this one over because it's a regression from the PR that I was in charge of.

**Comment by puneetlath** [comment]
Ok thanks @cristipaval

**Comment by lukemorawski** [comment]
will post a patch very soon

**Comment by cristipaval** [comment]
@lukemorawski This has been fixed already in [this PR](https://github.com/Expensify/App/pull/36068)

**Comment by lukemorawski** [comment]
@cristipaval cool, thanks!

**Comment by joekaufmanexpensify** [comment]
@s77rt could you handle the BZ checklist so we can prep to issue payment this week?

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/35058
- The offending PR has been commented on: https://github.com/Expensify/App/pull/35058#discussion_r1486972593
- A discussion in #expensify-bugs has been started: Not needed. Seems like a onetime bug
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Login (preferably with a new account)
2. Click the FAB > Request money
3. Enter any amount and press Next
4. Verify that there is a referral modal that says "Request money, get $250."
5. Click the close button of that modal
6. Verify the modal is closed
7. Repeat steps 2 and 3
8. Verify that the referral modal is not visible

**Comment by joekaufmanexpensify** [comment]
BZ checklist complete, and all set to issue payment!

**Comment by joekaufmanexpensify** [comment]
We need to make the following payments: 

- @s77rt - $500 for C+ review - paid via Upwork. 
- @ZhenjaHorbach - $500 for PR. Paid via upwork.

**Comment by joekaufmanexpensify** [comment]
@s77rt offer sent for $500!

**Comment by joekaufmanexpensify** [comment]
@ZhenjaHorbach offer sent for $500!

**Comment by s77rt** [comment]
@joekaufmanexpensify Accepted! Thanks!

**Comment by joekaufmanexpensify** [comment]
@ZhenjaHorbach $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@s77rt $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
