### ISSUE TITLE
[HOLD for payment 2024-03-11] [$500] [Wave Collect] [Ideal Nav] Navigating back from the Room Description page opens the Room Settings page

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#36054]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.38-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** internal employee
**Slack conversation:** [internal slack](https://expensify.slack.com/archives/C036QM0SLJK/p1707328899580649?thread_ts=1707323984.569099&cid=C036QM0SLJK)

## Action Performed:
1. Open App on a narrow browser or on mobile
2. Create a new room and open to a room report/chart
3. Click the room name at the top
4. Confirm that the Room Description page appears
5. Click the back bottom

## Expected Result:
The app should navigate back to the chat page for the room

## Actual Result:
The app navigates to the Room Settings page

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/98560306/5ef658e7-dca0-4ba0-994f-eb82ce261d61

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102c95bfabb9f4183</li>
        <li>Upwork Job ID: 1755293298126323712</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
@aimane-chnaif Are u sure u are selecting the correct proposal? it looks like a recent change from https://github.com/Expensify/App/pull/34150
it should be reverted to prev state
```
onBackButtonPress={() => Navigation.goBack(ROUTES.REPORT_SETTINGS.getRoute(report.reportID))}
```

**Comment by FitseTLT** [comment]
What about refreshing page while on room description, that's the purpose of fallbackRoutes ? @aimane-chnaif

**Comment by esh-g** [comment]
While implementing the PR, this was known and not considered a bug... I'm not sure if this is a bug because currently I'm implementing the `workspace description` as well and in that case, we have to show the workspace overview before opening the edit page for description, so it would make sense to be consistent.

https://github.com/Expensify/App/assets/77237602/f34e515c-3aa2-40c7-b097-cdf23eee6ed7

**Comment by hayata-suenaga** [comment]
@esh-g thank you for bringing that to our attention.

> we have to show the workspace overview before opening the edit page for description,

could you link the PR or GH Issue?

**Comment by esh-g** [comment]
Here is the issue for workspace: https://github.com/Expensify/App/issues/32955

**Comment by hayata-suenaga** [comment]
> we have to show the workspace overview before opening the edit page for description

@esh-g where was this decided?

**Comment by esh-g** [comment]
@hayata-suenaga Actually the click on the header opening the edit message was decided in the `room` description issue, I figured it would be the same for `workspace` description. So, in order for it to be the same on `workspace` description, we would have to show workspace overview page. But currently, the team is still doubting whether that should be the case. Please follow the discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707407557551759?thread_ts=1706584967.766219&cid=C01GTK53T8Q

**Comment by hayata-suenaga** [comment]
asking shawn a follow up question

**Comment by hayata-suenaga** [comment]
@aimane-chnaif when you have time, could you review [the Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1707407557551759?thread_ts=1706584967.766219&cid=C01GTK53T8Q) and figure out what decision we ended up on for the design?

**Comment by hayata-suenaga** [comment]
> Maybe we can watch how https://github.com/Expensify/App/pull/36058 goes. So hold until that PR is deployed to production.

good idea! I'll hold this issue. Let's circle back when [the PR](https://github.com/Expensify/App/pull/36058) is deployed to production.

**Comment by hayata-suenaga** [comment]
[The PR](https://github.com/Expensify/App/pull/36058) in question was deployed to staging.

**Comment by hayata-suenaga** [comment]
@aimane-chnaif the hold was removed. could you check the design change and select a proposal again when you have time? 🙇

**Comment by hayata-suenaga** [comment]
thank you for confirming 🙇 let's go with @ZhenjaHorbach's proposal 👍

**Comment by hayata-suenaga** [comment]
@aimane-chnaif could you finish the checklist please?

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by hayata-suenaga** [comment]
waiting for payment

**Comment by hayata-suenaga** [comment]
@ZhenjaHorbach is the contributor who authored [the PR](https://github.com/Expensify/App/pull/37440)
@aimane-chnaif is the C+ who reviewed the PR

[The proposal was approved on Feb 28](https://github.com/Expensify/App/issues/36054#issuecomment-1969374665)
The PR was opened on Feb 28
The PR was merged on Feb 29

**Comment by kevinksullivan** [comment]
all set
