### ISSUE TITLE
[$500] chat-After pasting max character limit, type or interact , app gets closed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36051]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Paste a long text again and again until maximum comment length 10k characters shown
4. Now try to type and interact with app
5. Tap phone back button
6. Note new expensify isn't responding" message displayed
## Expected Result:
After pasting max character limit, if user tries to type or interact , app gets struck and tapping phone back button must not show " new expensify isn't responding" message.
## Actual Result:
After pasting max character limit, if user tries to type or interact , app gets struck and tapping phone back button showing " new expensify isn't responding" message.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/909eb698-ec87-4379-9a02-c141fa089f31

[Bug6370698_1707328789938!crolse.txt](https://github.com/Expensify/App/files/14199824/Bug6370698_1707328789938.crolse.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018344047ab31b9164</li>
        <li>Upwork Job ID: 1755291564377370624</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by twisterdotcom** [comment]
Alright I agree this is a bug that would fit in #vip-vsb but it again is very `LOW`.

**Comment by Piotrfj** [comment]
Hello, Im Piotr from Callstack and would like to help with this issue

**Comment by Piotrfj** [comment]
@m-natarajan on what exact emulator did the bug occur?

**Comment by twisterdotcom** [comment]
Bump @m-natarajan

**Comment by Piotrfj** [comment]
@m-natarajan bump

**Comment by twisterdotcom** [comment]
I cannot recreate this on a real android device: https://drive.google.com/file/d/12zxlqA_jRb0iAvChGOaJ5xvnQXia0R9D/view?usp=sharing

**Comment by situchan** [comment]
I think this depends on the content. Won't happen in plain 10k characters. Most likely markdown issue.
@m-natarajan can you please share long text you tested?
