### ISSUE TITLE
[$500] Infinite requests when message image source is an invalid link

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36061]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707250100494229

## Action Performed:
1. Go to any chat
2. Send a message
3. Open react dev tools, components
4. Select the report action item message component for that chat
5. manually edit the action prop, message.html, and set it to this string `<h1>GIF Test 1</h1><br /><img src=\"a%20href=\" alt=\"a href=\" />`
## Expected Result:
No looping requests

## Actual Result:
The browser makes requests in a loop

## Workaround:
ignore

## Platforms:

Which of our officially supported platforms is this issue occurring on?

All
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/6488bf05-6ab1-4e70-83b0-fae1087b39c6

https://github.com/Expensify/App/assets/38435837/fd2bdc7b-3f84-46c5-91ca-ecff3dabadd1

https://github.com/Expensify/App/assets/38435837/fae755a8-4327-4c0d-ab7a-ac2ad1399464

## Notes
For added context, the original problem comes from a message sent by Concierge, where the content comes from the internal [concierge compose](https://www.expensify.com/concierge/#/tools/ComposeMessage) tool. Somehow that tool send a message with an invalid image source. We have no idea how that happened, but it was during testing, and the tool generally seems to work fine now. Regardless, we don't want NewDot making infinite requests to invalid URLs at all, so let's fix that on the frontend.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef9040e3f909dd5c</li>
        <li>Upwork Job ID: 1755362860038602752</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
@roryabraham do you have any ideas about this, since you implemented the concierge compose updates?

**Comment by neil-marcellini** [comment]
We found that this only happens for certain messages sent using the Concierge compose tool. The problematic message is the following. If you manually edit a report action message to contain this under the html key, requests will loop infinitely.
`<h1>GIF Test 1</h1><br /><img src=\"a%20href=\" alt=\"a href=\" />`

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Infinite requests when message image source is an invalid link


### What is the root cause of that problem?

The HTML render for image uses ThumbnailImage component to display images in report actions. ThumnailImage inturn uses ImageWithSizeCalculation component to render the image. The onLoadStart and onLoadEnd props used for Image component are inline functions whose reference changes with each re-render. This causes the image component to re-render which triggers another network request.


### What changes do you think we should make in order to solve the problem?

Memoize onLoadStart & onLoadEnd methods in ImageWithSizeCalculation component.

```tsx

const onLoadStart = useMemo(() => {
        if (isLoadedRef.current ?? isLoading) {
            return;
        }
        setIsLoading(true);
}, [isLoading])

const onLoadEnd = useMemo(() => {
        setIsLoading(false);
        setIsImageCached(true);
}, [])


return (
        <View style={[styles.w100, styles.h100, style]}>
            <Image
                style={[styles.w100, styles.h100]}
                source={{ uri: url }}
                isAuthTokenRequired={isAuthTokenRequired}
                resizeMode={RESIZE_MODES.cover}
                onLoadStart={onLoadStart}
                onLoadEnd={onLoadEnd}
                onError={onError}
                onLoad={imageLoadedSuccessfully}
            />
            {isLoading && !isImageCached && <FullscreenLoadingIndicator style={[styles.opacity1, styles.bgTransparent]} />}
        </View>
    );

```


### What alternative solutions did you explore? (Optional)

None

**Comment by neil-marcellini** [comment]
Ah great thanks so much @paultsimura . I'm going to HOLD this issue on that one, since this one is a bit different I think it would be wise to re-test it after that issue has been fixed.

**Comment by paultsimura** [comment]
@neil-marcellini @quinthar is there a way to use the Concierge Compose tool and force it to send a broken image? I'm trying to test the fix to this issue on native platforms, and they don't support the source modification.

**Comment by quinthar** [comment]
Hm, not really but you could just directly modify a message in Onyx using the Chrome tools I imagine to intentionally break a message.

**Comment by neil-marcellini** [comment]
@paultsimura good point, but I think you can use Flipper dev tools to modify the props of components, and set an invalid message that way.

**Comment by dylanexpensify** [comment]
held still?

**Comment by paultsimura** [comment]
> held still?

The #34601 is in production, so I think we could take this one off hold and retest.

**Comment by roryabraham** [comment]
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1708648765218909

**Comment by neil-marcellini** [comment]
You can only really test on dev like this, but it's enough to verify that it's fixed!


https://github.com/Expensify/App/assets/26260477/7289872c-4e48-419f-b172-f1c71b5730a2
