### ISSUE TITLE
[HOLD for payment 2024-02-19] [HOLD for payment 2024-02-15] [HOLD FOR PAYMENT: 15th Feburary] [$500] IOU - Payment option reverts back to 'Pay with Expensify'

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36066]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create an IOU in workspace chat
2. Change payment option to 'Pay elsewhere'
3. Click on the IOU preview component

## Expected Result:
Payment option on the header should be 'Pay elsewhere'

## Actual Result:
Payment option on the header and IOU preview component of the main report reverts back to 'Pay with Expensify'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/408ebf3b-1eb3-4c22-8c04-559dfec1e563

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153ee13375ff6a485</li>
        <li>Upwork Job ID: 1755559026447237120</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by Julesssss** [comment]
[Fix is in review](https://github.com/Expensify/App/pull/36115)

**Comment by Julesssss** [comment]
I did not mean to remove that blocker label earlier.

**Comment by Julesssss** [comment]
PR merged, awaiting CP to staging before I check this off the checklist.

**Comment by Julesssss** [comment]
Yes. @ZhenjaHorbach is fixing a regression from their own issue. So I believe payment only applies to: 
- @mkhutornyi for providing the [proposal](https://github.com/Expensify/App/issues/36066#issuecomment-1932878862) we ended up using
- @ishpaul777 for C+ review

**Comment by Julesssss** [comment]
Handled. CP'd, [build ](https://github.com/Expensify/App/actions/runs/7830054890)is in progress

**Comment by Julesssss** [comment]
Awaiting payment

**Comment by MitchExpensify** [comment]
Reminder set 

Please apply to this job: https://www.upwork.com/jobs/~0153ee13375ff6a485. @mkhutornyi + @ishpaul777

**Comment by MitchExpensify** [comment]
Invites sent https://www.upwork.com/jobs/~0153ee13375ff6a485. @mkhutornyi + @ishpaul777

**Comment by MitchExpensify** [comment]
Paid and contracts ended - Thanks every one!
