### ISSUE TITLE
[HOLD for payment 2024-03-25] [$500]  Bank account – Able to save a phone number with some spaces before and without +

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36072]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4289031
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app.
2. Log in with a applause.expensifail account (that does not have any bank account already added)
3. Navigate to the add bank account modal
4. Select the Manual method to add a bank account
5. On the "Connect Bank Account" page, enter the routing and account numbers
6. Checkmark the "I accept the Expensify Terms of Service"
7. In the company information
8. Fill out the company information
9. Fill out the phone number information with some spaces before and without +
10. Click Save and continue

## Expected Result:
You’re shown an error on the incorporation date field

## Actual Result:
Able to save a phone number with some spaces before and without +

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/32d3f07d-d1d1-4ca3-b568-9c9ba597c5a6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019136df945e25456b</li>
        <li>Upwork Job ID: 1755331054635565056</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by godofoutcasts94** [comment]
How to make applause.expensifail account for new contributors?

**Comment by FitseTLT** [comment]
This is intentional. It presumes that the phone is US phone so it works without giving it the country code.

**Comment by cubuspl42** [comment]
@GandalfGwaihir How does your solution improve the UX? Does it change a crash for a form validation error, or does the old code just trim the extra whitespace?

**Comment by cubuspl42** [comment]
The issue (or the proposal) don't show any evidence of how a number like `    997567 ` is actually _presented_ to the user (as opposed as just being _accepted_ during input). Could you provide some before/after screenshots?

**Comment by cubuspl42** [comment]
In such a case, I disagree that we should raise an error. We should silently trim the number. It could be copy-pasted from a source, which adds the extra whitespace. It's possibly not the user's fault.

**Comment by cubuspl42** [comment]
What are the up-to-date reproduction steps? Is there a way to get to this point without going through Onfido flow?

**Comment by cubuspl42** [comment]
It was tough, but I reproduced the issue, skipping the Onfido flow. See [this Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1708083763366869?thread_ts=1708082053.969179&cid=C01GTK53T8Q).

I confirm that we present the whitespace-containing telephone number to the user in the confirmation step.

It's a minor thing, but it is a bug indeed.

I approve the proposal by @GandalfGwaihir 

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment]
PR is merged

**Comment by johncschuster** [comment]
Bumping to keep Melvin happy. I will issue payment on March 25 👍

**Comment by cubuspl42** [comment]
- The PR that introduced the bug has been identified. Link to the PR:
    -  This never worked as expected
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - No
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by johncschuster** [comment]
# Payment Summary:
Contributor: @GandalfGwaihir - $500 to be paid via Manual Request

**Comment by cubuspl42** [comment]
This was likely a mistake, so let's wait patiently for John's response for one or two business days, then you can create a thread on Slack (feel free to ping me too in such a case).

**Comment by johncschuster** [comment]
@GandalfGwaihir can you share the link to your Upwork profile? I'm having a hard time finding you in Upwork.

**Comment by johncschuster** [comment]
Thank you! Your offer is [here](https://www.upwork.com/nx/wm/offer/101704877)!

**Comment by johncschuster** [comment]
Payment has been issued! 🎉
