### ISSUE TITLE
[$500] Chat - Message moves when navigate back from error page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36074]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4282338&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):** applausetester+gm22@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open any chat
3. Enter this link with restricted access (https://staging.new.expensify.com/r/6821704960193694
) to the message composer and send
4. Error page will appear
5. Click on Back
6. Hover over the last send message

## Expected Result:
The chat page and message send should be stable

## Actual Result:
Message moves when navigate back from error page (https://staging.new.expensify.com/r/6821704960193694

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/609de170-86e4-4ad5-9c94-d3f6b9802b6c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6152996f68a9b46</li>
        <li>Upwork Job ID: 1755332965827866624</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
This is a super niche bug. I don't think it relates to any of our roadmap priorities. Going to close for now, and we can reassess if any customers actually experience this.
