### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500]  IOU - Destinations used for creating request in offline remains grayed out in online mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0507gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com as Employee
2. Disable the internet connection
3. Go to Workspace chat> +> Money request> Distance> Create request
4. Go back online
5. Go to Workspace chat> +> Money request> Distance
6. Take a note of recent destination results

## Expected Result:
All recent destination should not be grayed out

## Actual Result:
Destinations used for creating request in offline remains grayed out in online mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/376338fc-9449-4f55-96a4-10775e8edc7f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d576261e97da21a3</li>
        <li>Upwork Job ID: 1755338770224349184</li>
        <li>Last Price Increase: 2024-02-28</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>barros001 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by puneetlath** [comment]
Hmmmm, interesting.

>Because some recent waypoints have been saved in offline mode, they do not have a name field so it will only show the description without the bolded name, giving the impression of being greyed out. This is not really grayed out in the sense that it's offline/not available, it's just that it doesn't display the bolded title because it doesn't have one.

Is the only way to not have a "name" to add it via offline mode? Or are there other ways in which you can end up with a recent destination that doesn't have a name?

**Comment by puneetlath** [comment]
Ok got it. In that case, I think displaying the description in bold when there is no name makes sense. What do you think @fedirjh?

**Comment by puneetlath** [comment]
cc @neil-marcellini as well in case you have an opinion.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by neil-marcellini** [comment]
> Though actually, will those destinations created in Offline Mode work? I just tried with the locations "Atlanta" and "New York" and the request ultimately failed to be created. So maybe a better solution is to not add the destination to the recents list unless it is one that actually comes from Google.

Yes if you use an invalid address offline, then it won't work. There isn't a good way to validate addresses while offline, so we optimistically assume that they are valid. I think we should continue to optimistically add to the recent waypoints so that users can make multiple offline requests easily, assuming they actually use valid addresses. It's tricky and I'm still open to other ideas about how it should work.

Displaying the description in bold when there is no name sounds like a good solution here.

**Comment by puneetlath** [comment]
@fedirjh friendly reminder about the checklist so that we can pay tomorrow.

**Comment by puneetlath** [comment]
@barros001 has been paid. @fedirjh still waiting on the checklist for you.
