### ISSUE TITLE
HIGH: [Live Markdown] Tracking Live Markdown Issues

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#36071]
# Tracking issue for all Live Markdown bugs

CRITICAL
- https://github.com/Expensify/App/issues/39267

HIGH
- https://github.com/Expensify/App/issues/39518

MED
- https://github.com/Expensify/App/issues/39301
- https://github.com/Expensify/App/issues/36354
- https://github.com/Expensify/App/issues/39348

LOW
- https://github.com/Expensify/App/issues/39266
- https://github.com/Expensify/App/issues/31633

**Comment by tomekzaw** [comment]
Please assign me for visibility

**Comment by tgolen** [comment]
I'm bumping up the priority of this since several of the reported bugs are deploy blockers. I recommend reverting the LiveMarkdown PR, fixing the bugs that have been reported, and then trying again.

**Comment by tomekzaw** [comment]
Working on it

**Comment by tomekzaw** [comment]
Working on it

**Comment by tomekzaw** [comment]
Working on it

**Comment by tylerkaraszewski** [comment]
@thienlnam - shoudl we move https://github.com/Expensify/App/issues/39275 to `BLOCKING DEPLOY` or should we remove the deploy blocker from that issue?

**Comment by thienlnam** [comment]
I think we can remove the blocker from that issue, seems like that just came out as well

**Comment by tylerkaraszewski** [comment]
Oops, I had linked the wrong issue, I meant https://github.com/Expensify/App/issues/39263, but that's been added to the deploy blocker section. Thanks!

**Comment by tylerkaraszewski** [comment]
@thienlnam I got tagged for another deploy blocker that might be related: https://github.com/Expensify/App/issues/39301

I don't know if this is severe enough to be a deploy blocker. Thoughts?

**Comment by thienlnam** [comment]
Ah yeah definitely doesn't look like it needs to block deploy, I've added it above as part of MED

**Comment by bernhardoj** [comment]
Hi, I found an issue with the live markdown on the web. The `autoFocus` prop of the composer seems not working. I tried setting it to `false` but the composer is still auto-focused.

I can reproduce it with this minimal code:
`<RNMarkdownTextInput autoFocus={false} selection={{start: 0, end: 0}}/>`

If there is a selection prop, the input will always be auto-focused. If I remove this [live markdown source code](https://github.com/Expensify/react-native-live-markdown/blob/d8205aa0bf6d922cbf0aea9eaa210b6375187ddc/src/MarkdownTextInput.web.tsx#L531-L532), then the issue is gone.

**Comment by twisterdotcom** [comment]
One more to add: 
- https://github.com/Expensify/App/issues/31633

**Comment by thienlnam** [comment]
We're still chugging along - almost done with all critical and highs

**Comment by thienlnam** [comment]
SWM is OOO this week, we're still chugging through

**Comment by thienlnam** [comment]
Just cleaned up the tracking issue, the list is dwindling!

**Comment by thienlnam** [comment]
Closing this! We've worked through all the critical issues, I think every issue from here on out can just be addressed independently. We're still working through https://github.com/Expensify/App/issues/39518 but there's no longer a need for this main tracking issue
