### ISSUE TITLE
 Search - When pull the scroll thumb search results are empty

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36082]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0507gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35058
## Action Performed:
1. Navigate to staging..new.expensify.com
2. Click on Search
3. Pull the scroll thumb through search results

## Expected Result:
Search results should be shown

## Actual Result:
Search results are empty when pull the scroll thumb

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3b9f6bab-0234-46d4-ad08-61c541b354fa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9c88738d231ca9d</li>
        <li>Upwork Job ID: 1765452882124140544</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
I can't seem to reproduce this myself

https://github.com/Expensify/App/assets/30609178/f16d61ea-eb0e-4a26-afc4-3c3817e1ec16

**Comment by lukemorawski** [comment]
is there a possibility to get this large contacts base account for testing?

**Comment by thienlnam** [comment]
@lukemorawski I can add one of your accounts to a high traffic account with 10,000 users in the policy. Could you give me an email to add to it? (Should be a test account since it will really make your App slow)

**Comment by lukemorawski** [comment]
@thienlnam yes please `lukasz.morawski+5 [at] callstack . com`

**Comment by thienlnam** [comment]
Added!

**Comment by lukemorawski** [comment]
other bugs are being squashed now

**Comment by thienlnam** [comment]
Asked to be re-tested https://expensify.slack.com/archives/C9YU7BX5M/p1709681685389939

**Comment by thienlnam** [comment]
Looks like this is still reproducible - @lukemorawski do you have the capacity right now to handle this or should we pass it on to another contributor?

**Comment by thienlnam** [comment]
Yup can agree with that, it seems to only impact very high traffic accounts - so not a real priority right now
