### ISSUE TITLE
[$500]  IOU - User have no access to Distance request chat after getting Online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/cases/view/2730099https://expensify.testrail.io/index.php?/cases/view/2730099
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user is logged in ND.
1. Offline: FAB > Request money
2. Select 'Distance' option
3. Enter a vague start location like "SF"
4. Enter a vague finish location like "LA"
5. Finish the request creation flow (in Workspace chat)
6. Enable the internet connection
7. Navigate to the Distance request

## Expected Result:
There's a red dot on the request report in the LHN, on the report preview in the workspace chat, and on the request.
User can open request report

## Actual Result:
An error message shown 'Unexpected error requesting money, please try again later' below request preview.
User has no access to request report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1b60fe22-3fa3-4190-81e1-6aaaa35cb348

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2dfd7d5a8a50696</li>
        <li>Upwork Job ID: 1755356625964285952</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave
CC @dylanexpensify

**Comment by Tony-MK** [comment]
This was discussed here https://github.com/Expensify/App/issues/32405#issuecomment-1900615213.

**Comment by alexpensify** [comment]
Alright, closing based on this feedback: 

https://github.com/Expensify/App/issues/32405#issuecomment-1921489679
