### ISSUE TITLE
MEDIUM: Weird push notification when invited to a room with a bunch of members

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jamesdeanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707336379216449

## Action Performed:
1. create a room
2. Invite a bunch of members to the room
3. Observe the push notification as one of the invited member

## Expected Result:
Should show the invited members list

## Actual Result:
mobile push notification doesn't make sense.  we should update the bottom line to "invited you and [NUMBER] others"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![iPhone](https://github.com/Expensify/App/assets/38435837/c0a49230-b465-4b20-9757-77545cc55b57)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a2b3f9aac2a663b</li>
        <li>Upwork Job ID: 1755356945680076800</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment]
Is this BE?

**Comment by DylanDylann** [comment]
This issue relates to the notification system. So I think It should be handled on the BE side
Send this message to get new eye from internal engineer

🎀 👀 🎀 C+ reviewed

**Comment by isabelastisser** [comment]
Bump @danieldoglas for review.

**Comment by DylanDylann** [comment]
@isabelastisser Because this is a BE bug. Could you add the label `internal` here

**Comment by danieldoglas** [comment]
@isabelastisser I'm unassigning myself, this should be probably a MEDIUM on #vip-vsp

**Comment by isabelastisser** [comment]
Added to VIP, waiting.

**Comment by isabelastisser** [comment]
This issue was included in the VIP project, waiting for an internal engineer assignment.

**Comment by isabelastisser** [comment]
This issue was included in the VIP project, waiting for an internal engineer assignment.

**Comment by Julesssss** [comment]
This MIGHT be solved by [this](https://github.com/Expensify/Web-Expensify/pull/41055) WIP PR.

**Comment by isabelastisser** [comment]
Waiting for this:

>This MIGHT be solved by https://github.com/Expensify/Web-Expensify/pull/41055 WIP PR.

**Comment by isabelastisser** [comment]
Not overdue.

**Comment by Julesssss** [comment]
Hi @isabelastisser, I am pretty sure this has been fixed for iOS/Android [here](https://github.com/Expensify/Web-Expensify/pull/41055#issuecomment-1980665748). But please test and re-open if you can't reproduce the fix
