### ISSUE TITLE
[$500] Android - IOU - Request money with new user, report is displayed in search but not in LHN.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36087]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.38
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4289350
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab --- start chat
3. Select a user with no conversation history
4. Tap plus icon--- Request money and complete the flow
5. Navigate to LHN and note no report shown related to this user or IOU created
6. Tap search
7. In search results note, report related to this displayed

## Expected Result:
Request money with new user, report is displayed in search similarly must be displayed in LHN

## Actual Result:
Request money with new user, report is displayed in search but not in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2fb99129-d339-4471-9816-247ee289c7bc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e73448bf4ab0fb47</li>
        <li>Upwork Job ID: 1755358258143526912</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by Tony-MK** [comment]
I think this is expected. https://github.com/Expensify/App/issues/34757#issuecomment-1916669360

**Comment by DylanDylann** [comment]
@Tony-MK Thanks for your ref. 

Let's close this one because of [here](https://github.com/Expensify/App/issues/34757#issuecomment-1916669360)

**Comment by DylanDylann** [comment]
@kadiealexander Let's close this one because of https://github.com/Expensify/App/issues/34757#issuecomment-1916669360
