### ISSUE TITLE
[MEDIUM] Backwards Compatibility:  Disabled tag can be assigned by Expense Rule

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36083]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4287684
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Prerequisites: Collect WS with Category enabled, and Employee invited.
1. [Employee] Create expense rule in OD with category and tag
2. [WS Admin] Disable category and tag used in Employee's expense rule
3. [Employee] Create IOU in WS chat in ND with merchant set in expense rule
4. [Employee] Verify IOU details

## Expected Result:
Both Category And Tag fields should be empty, since they've been disabled by WS Admin

## Actual Result:
Category is empty, but the Tag gets populated by expense rule even though it is disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/28c9353e-d418-4484-84e7-61b134a2588b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019455f2d5dd513513</li>
        <li>Upwork Job ID: 1755343215247671296</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by adelekennedy** [comment]
adding to wave 6 @ntdiary from the [comment above](https://github.com/Expensify/App/issues/36083#issuecomment-1932984158) do you think this is a BE issue? We're not getting bites for proposals

**Comment by cead22** [comment]
I think we should make this one internal, because this is probably something we can solve in the backend

**Comment by greg-schroeder** [comment]
Moving to Internal and setting as a `Hot Pick` under Wave 6

**Comment by rlinoz** [comment]
This is in production, closing.
