### ISSUE TITLE
[HOLD for payment 2024-03-20] [LOW] Enable pagination on SelectionList

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#36121]
## Problem

As part of [this issue](https://github.com/Expensify/App/issues/11795), we refactored the old gigantic `OptionItem` component into multiple components focused on specific use cases. The refactoring has taken quite a long time, and in the meantime, pagination was added to the App to make the experience smoother on high-traffic accounts.
Currently, the new component `SelectionList` doesn't have pagination, and the Search feature in high-traffic accounts doesn't offer the best experience.

## Solution
Let's enable pagination on the new `SelectionList` component.

cc @mountiny 

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by lukemorawski** [comment]
@cristipaval reporting for duty 🖖

**Comment by cristipaval** [comment]
Do we have an update here, @lukemorawski ?

**Comment by lukemorawski** [comment]
@cristipaval no, sorry, had a more urgent bug fixes. I will be tackling that today

**Comment by cristipaval** [comment]
I know Callstack devs are quite swamped atm, so most probably, @lukemorawski will have an update on Monday.

**Comment by lukemorawski** [comment]
@cristipaval yep, I was ooo on Friday. There are also couple of regressions I need address quickly. This ticket is next up in my queue.

**Comment by abekkala** [comment]
@lukemorawski can you provide an update?

**Comment by abekkala** [comment]
thanks @lukemorawski

**Comment by cristipaval** [comment]
👀

**Comment by abekkala** [comment]
@lukemorawski is there any update on this one?

**Comment by abekkala** [comment]
@lukemorawski do you still have some higher priority PRs that is putting this one off for a bit?

**Comment by lukemorawski** [comment]
Hey. Yes, but I posting one PR today and I'll be waiting for a review, so I should be able to finish this. Fingers crossed 🤞

**Comment by lukemorawski** [comment]
@abekkala PR is open

**Comment by abekkala** [comment]
Great @lukemorawski ! Thanks!

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 20

- FIX: @lukemorawski - no payment required
- PR REVIEW: @fedirjh [$500 - if no regression] [Offer](https://www.upwork.com/nx/wm/offer/101401954)


@lukemorawski can you complete the checklist above?

**Comment by abekkala** [comment]
@fedirjh payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment]
no regression test needed
