### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] Distance - Unable to unselect default category from confirmation page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-38.2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has set up default category for Distance request.

1. Go to workspace chat.
2. Start distance request flow.
3. Proceed to confirmation page.
4. Click Category.
4. Click on the selected default category.
5. Note that user cannot unselect the default category.
6. Create the distance request.
7. Go to details page of the created distance request.
8. Click Category.
9. Click on the selected category.
10. Now user can unselect the category.

## Expected Result:
In Step 4, user should be able to unselect the default distance category.

## Actual Result:
In Step 4, user is unable to unselect the default distance category.
Only after the distance request is created, user can unselect it from the request details page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8510b643-887a-4195-aa15-ef3c40ce9c30

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165ec95398a746481</li>
        <li>Upwork Job ID: 1755567118652162048</li>
        <li>Last Price Increase: 2024-02-08</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28150761</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to  #vip-vsb
CC @quinthar

**Comment by paultsimura** [comment]
This is a regression from https://github.com/Expensify/App/issues/33388
cc: @situchan @tienifr

**Comment by situchan** [comment]
@tienifr can you raise quick PR?

**Comment by situchan** [comment]
[PR](https://github.com/Expensify/App/pull/36150) is up

**Comment by Julesssss** [comment]
Taking over as this is one of 2 remaining blockers. Assigning @aimane-chnaif as the C+ reviewer.

**Comment by Julesssss** [comment]
Cherry picked, no longer a blocker

**Comment by greg-schroeder** [comment]
Okay so reviewing this ... this is a regression from https://github.com/Expensify/App/issues/33388. That PR was implemented by @tienifr and reviewed by @situchan. Both were paid $500 - it doesn't seem like there was a regression penalty applied? Not sure.

This issue resulted in [a PR](https://github.com/Expensify/App/pull/36150) that was CP'd to resolve the regression, which was implemented by @situchan and reviewed by @aimane-chnaif.

@rushatgabhane was assigned to this issue as C+ via automation, but I don't think he participated in the review as this was a deploy blocker that was implemented very quickly.

---

With that said, I think the payments for this issue should just be:

$500 to @aimane-chnaif 

Please let me know if I got any of this incorrect.

**Comment by greg-schroeder** [comment]
Paid. One of the 3 C+ assigned to this can hopefully take care of [the checklist](https://github.com/Expensify/App/issues/36139#issuecomment-1938724584). :)

**Comment by Julesssss** [comment]
Quiet melvin.

I think we're good now, right @greg-schroeder

**Comment by greg-schroeder** [comment]
Oops, sorry, closing and taking care of final steps!
