### ISSUE TITLE
[$500] Expense - No error message when saving empty report title

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36142]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-38.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.

1. Go to workspace chat.
2. Create an expense.
3. Click on the expense preview to go to expense report.
4. Click Title.
5. Empty the title and save it.
6. Return to main chat and revisit expense report.

## Expected Result:
In Step 5, if the report title cannot be empty, app will throw an error.

## Actual Result:
In Step 5, there is no error when saving empty title. After saving empty title, it reverts to the previous title when revisiting expense report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f500853e-6b6e-4e08-9990-458fe56eff31

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017832c36402c96325</li>
        <li>Upwork Job ID: 1755575960140136448</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave6-collect-submitters
@greg-schroeder

**Comment by FitseTLT** [comment]
Whichever way we follow I think this is a BE issue. First it is returning the `title` field as `deletable` of the `policyReportFields` so if it is deletable it should handle setting empty string well but although we are setting on optimistic data correctly the request response is nothing. If we want the field to be required then `deletable` should be false in the `policyReportFields`

**Comment by mallenexpensify** [comment]
Testing to see if, when I add the below, an engineer if assigned.  If not, @hoangzinh can you please add? I'm not an engineer so unsure if this is BE
🎀👀🎀

**Comment by thienlnam** [comment]
Ah, this is being handled as part of report fields. We're working on this here https://github.com/Expensify/App/issues/35331

**Comment by thienlnam** [comment]
Yeah do nothing - there's a merged BE issue that is handling the report field getting saved, and then the linked issue above which handles removing optional fields

**Comment by arosiclair** [comment]
Cool thanks for the help!
