### ISSUE TITLE
[$500] Room - Non-member can add description to room, but forbidden to edit it after inviting member

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36143]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-38.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and member are in the same workspace.

1. [Admin] Create a workspace visibility room.
2. [Member] Copy the room link and navigate to it.
3. [Member] Click on the header > Room description.
4. [Member] Add a room description and save it.
5. [Member] Invite another user to the room.
6. [Member] Refresh the page and click on the room header.

## Expected Result:
In Step 4, non room member should not be able to add room description.

## Actual Result:
In Step 4, non room member is able to add room description.
However, after adding a room description and inviting a member, the room description is no longer editable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7e7fc98f-0a7f-406b-8262-97bc9a725984

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e01272c415c9edec</li>
        <li>Upwork Job ID: 1755577130332930048</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

**Comment by FitseTLT** [comment]
It's BE issue.

**Comment by muttmuure** [comment]
Will post to the vsb room soon

**Comment by DylanDylann** [comment]
This is a BE Bug. When a new user accesses to room by link 

https://github.com/Expensify/App/blob/98a51b3eabde795163a4fbc5b18ecde8029764ad/src/libs/ReportUtils.ts#L4729

This condition returns true because the current user is added to the participant filed

<img width="278" alt="Screenshot 2024-02-15 at 17 06 24" src="https://github.com/Expensify/App/assets/141406735/5bca695b-4693-49c7-b612-a823297c5916">

**Comment by DylanDylann** [comment]
@muttmuure Let's add an internal label to get eyes from the internal engineer

**Comment by muttmuure** [comment]
Hm, I thought about this earlier this week - isn't it expected that the first member of the room can create the description? It's how we allow for user created rooms

**Comment by muttmuure** [comment]
https://expensify.slack.com/archives/C066HJM2CAZ/p1708712351488839

**Comment by muttmuure** [comment]
Posted to the VSB room

**Comment by quinthar** [comment]
This is really wild.  You've reproduced this?

**Comment by quinthar** [comment]
Why are we calling the invited person a non-member -- once they're invited, they are a member, right?  I'm confused what this issue is saying.
