### ISSUE TITLE
[HOLD] [$250] Remove `New Workspace` option from Global Create

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#36153]
As part of our ideal nav release, we have made it super easy to create a workspace, which was not previously the case. This includes an empty state to create a workspace when you tap the "wrench" in the bottom nav, as well as one click access to any workspaces you've previously created. 

As a result, the `New Workspace` option is no longer needed. Let's remove it from Global Create.

![image](https://github.com/Expensify/App/assets/1127863/9260de2d-39b8-456d-8dcd-a94af92d2ba5)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f04217489c09c36e</li>
        <li>Upwork Job ID: 1755604175468281856</li>
        <li>Last Price Increase: 2024-02-08</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>esh-g | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment]
# Proposal

## SOlution
We should remove the menu item here:
```js
...(!props.isLoading && !Policy.hasActiveFreePolicy(props.allPolicies)
                        ? [
                              {
                                  displayInDefaultIconColor: true,
                                  contentFit: 'contain',
                                  icon: Expensicons.NewWorkspace,
                                  iconWidth: 46,
                                  iconHeight: 40,
                                  text: translate('workspace.new.newWorkspace'),
                                  description: translate('workspace.new.getTheExpensifyCardAndMore'),
                                  onSelected: () => interceptAnonymousUser(() => App.createWorkspaceWithPolicyDraftAndNavigateToIt()),
                              },
                          ]
                        : []),
```
in `FloatingActionButtonAndPopover`

**Comment by esh-g** [comment]
> [!NOTE]
> The first comment from @GandalfGwaihir was just 'dibs' and proposal was edited in later.

**Comment by situchan** [comment]
@esh-g was the first to provide complete [proposal](https://github.com/Expensify/App/issues/36153#issuecomment-1934278532).
Code cleanup can be done in PR phase.

🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment]
As this is new feature, this doesn't require specific root cause. They linked the correct code where to implement.
@ZhenjaHorbach I think you already got benefit from other issue today. So let's end up unrelated discussion here.

**Comment by esh-g** [comment]
As to address those concerns:
- The first comment did indeed have a solution that could be understood rather than 'dibs'
- It is allowed to edit proposals and if we compare the last edit time, my solution was still earlier
<img width="460" alt="Screenshot 2024-02-08 at 8 32 52 PM" src="https://github.com/Expensify/App/assets/77237602/1d7b0d4a-99c7-4b91-9a87-e825e7774619">

<img width="351" alt="Screenshot 2024-02-08 at 8 33 37 PM" src="https://github.com/Expensify/App/assets/77237602/9f881cf3-7180-42ab-9350-0dceefcf2d3f">

I hope this clarifies my position, thanks for your understanding

**Comment by mountiny** [comment]
Decreasing the rewards due to relative simplicity of this job.

**Comment by JmillsExpensify** [comment]
Update: Please hold on working on this PR or merging it. We may end up going down a different path, as we are discussing potential re-designs to our Ideal Nav framework. I'll take over the issue and also add a HOLD to the title.

**Comment by flodnv** [comment]
@JmillsExpensify feel free to reassign me whenever it's off hold

**Comment by trjExpensify** [comment]
Are we still doing this?

**Comment by trjExpensify** [comment]
I've put it in `Polish` for the time being.

**Comment by JmillsExpensify** [comment]
I'm not sure if we will, though I think it makes sense to keep open for a little bit longer. Polish sounds right to me.

**Comment by trjExpensify** [comment]
Cool, sounds good!

**Comment by situchan** [comment]
Ideal Nav v2 was deployed to production. Is this still on hold?

**Comment by JmillsExpensify** [comment]
Yes, it is.

**Comment by JmillsExpensify** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Still on hold pending onboarding improvements.

**Comment by JmillsExpensify** [comment]
With no immediate plans to do this, I'm going to go ahead and close this issue. Additionally, since proposals were made and reviewed, I am willing to compensate the following:

 - Contributor: @esh-g $125
 - Contributor+: @situchan $125

**Comment by JmillsExpensify** [comment]
Contributor paid out and C+ offer sent. Going to close this issue, but please comment here when you've accepted the offer and I'll issue payment.

**Comment by situchan** [comment]
@JmillsExpensify accepted offer. Thanks

**Comment by JmillsExpensify** [comment]
C+ paid out, so we're all good here!
