### ISSUE TITLE
Clean up code assuming a money request is P2P when policy isn't set

### ISSUE THREAD

**Issue by cead22** [Expensify/App#36169]
- Coming from this GH comment https://github.com/Expensify/App/pull/34402#issuecomment-1932601301 and this slack thread https://expensify.slack.com/archives/C01GTK53T8Q/p1707341460136359?thread_ts=1707339619.099769&cid=C01GTK53T8Q
- The code we're using to decide whether a money request is a workspace request or a P2P request relies on `policy` being set
- This works when creating money request because the methods we call don't pass a policyID
- But P2P request get put on a report that's on a personal workspace, the the policy/policyID is set in the code used for updating money request
- Let's update the code for updating money requests to use `PolicyUtils.isPaidGroupPolicy` to determine if the request is a workspace request or a P2P request

@lindboe please comment for assignment

**Comment by lindboe** [comment]
Commenting for assignment

**Comment by cead22** [comment]
@cdanwards please comment for assignment

**Comment by cdanwards** [comment]
Commenting for assignment
