### ISSUE TITLE
[Onyx] Move `policyTaxRates_` key back into the `policy_` key

### ISSUE THREAD

**Issue by flodnv** [Expensify/App#36171]
# Problem & Solution

Sister issue: https://github.com/Expensify/App/issues/36170

Discussed internally, summarised [here](https://expensify.slack.com/archives/C03TQ48KC/p1707339183790349?thread_ts=1707328858.869149&cid=C03TQ48KC) and concluded [there](https://expensify.slack.com/archives/C03TQ48KC/p1707402878757569?thread_ts=1707328858.869149&cid=C03TQ48KC)

- We added the onyx keys `policyTaxRates_` and `policyReportFields_` for no good reason. There's no size to optimize for in these collections.
- This makes my life harder in trying to fix an architectural problem of sending policy updates in https://github.com/Expensify/Auth/pull/9773 (see https://expensify.slack.com/archives/C03TQ48KC/p1706285244529629 & https://github.com/Expensify/App/issues/34834)
- This makes code more complex than it needs to be (lots of existing data massaging for really no gain)
- As such, we should kill and fix this unnecessarily complex code that was recently introduced. This means, at a minimum (I might be missing things):
	- Moving this data back into the `policy_` key
	- Removing any data massaging from the backend
	- Have the frontend accept the same data as what's in the database
	- Where we should not display disabled fields, then let's use the `disabled` property to hide them. We will need to display them to admins soon enough
- No need to worry about sending updates to policy members when the policy changes, that will be done as part of https://github.com/Expensify/Auth/pull/9773, which includes doing this for all current and future policy attributes

cc @iwiznia @puneetlath @tgolen @marcaaron @francoisl @dangrous @johnmlee101 @stitesExpensify @thienlnam  @nkuoch @AndrewGable @luacmartins 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f2faa357c786564</li>
        <li>Upwork Job ID: 1755673931208187904</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by flodnv** [comment]
I just realized we also need to fix the location of `isTaxTrackingEnabled` like we did in https://github.com/Expensify/Web-Expensify/pull/40728 for harvesting... 

cc @mountiny

**Comment by mountiny** [comment]
@flodnv Made an issue for this here https://github.com/Expensify/App/issues/36176 and will address it

**Comment by iwiznia** [comment]
> Removing any data massaging from the backend

The data in onyx is an object keyed by fieldID but in the DB is an array, so I think we can't do this

**Comment by MonilBhavsar** [comment]
The plan is to
1. [ ] Have Web-E send tax details in `policy_` onyx along with `policyTaxRates_` key
2. [ ] Update App to use `policy_` key for tax rates
3. [ ] After some time, completely deprecate `policyTaxRates_` from server

**Comment by teneeto** [comment]
Hi, I'm Eto from Callstack - expert contributor group - and I would like to take care of this issue.

**Comment by tgolen** [comment]
Is the plan to use an Onyx migration to ensure the data exists in the
proper key?

**Comment by flodnv** [comment]
Also, is the plan to store tax details in `policy_` in the same place they are in the DB, aka in the `expenseUDFs` key?

**Comment by marcaaron** [comment]
>After some time, completely deprecate policyTaxRates_ from server

Oh also, anytime we force users to upgrade to a new app version would be a good opportunity to remove this code. Then we don't have to consider how much time is "enough" before removing things. Not sure if I'd force an upgrade for this though and we haven't used [this](https://stackoverflowteams.com/c/expensify/questions/18444/18445#18445) yet.

**Comment by MonilBhavsar** [comment]
From this SO https://stackoverflowteams.com/c/expensify/questions/14164 I think we don't require Onyx migration
This case is very similar to 
> The name of a key has changed (because it should get the new data from the server stored on the new key when they open the app)

Where we're moving data from one Onyx key to another and currently client is only reading that data

**Comment by MonilBhavsar** [comment]
> Also, is the plan to store tax details in policy_ in the same place they are in the DB, aka in the expenseUDFs key?

No, under the `taxRates` key and in the form of object. Object only contains required data and in the format that can simply be rendered

**Comment by MonilBhavsar** [comment]
> Oh also, anytime we force users to upgrade to a new app version would be a good opportunity to remove this code. Then we don't have to consider how much time is "enough" before removing things. Not sure if I'd force an upgrade for this though and we haven't used [this](https://stackoverflowteams.com/c/expensify/questions/18444/18445#18445) yet.

Yes correct! We can note an app version where the App PR is deployed to production and once `MINIMUM_APP_VERSION` is updated to greater than the version we can safely remove the code. Will bump priority to Monthly to cleanup the code.

**Comment by teneeto** [comment]
@MonilBhavsar I raised a [draft_PR](https://github.com/Expensify/App/pull/36784) where `taxRates` are been applied from `policy_ ` rather than `policyTaxRates_`.

This is done for the main branch for now. I'm currently updating on [edit fields PR](https://github.com/Expensify/App/pull/33927) as well.

**Comment by MonilBhavsar** [comment]
App PR is merged and deployed to production in version `1.4.44-13`.
Once Minimum App version is set to 1.4.44-13`, we'll deprecate `policyTaxRates_` from Web-E completely

**Comment by luacmartins** [comment]
cc @kosmydel @filip-solecki since you're working on the Simplified Collect: Taxes doc too

**Comment by MonilBhavsar** [comment]
As per this comment https://github.com/Expensify/Auth/pull/9773#discussion_r1516014889
Need to update Onyx keys in auth once that PR is shipped

**Comment by MonilBhavsar** [comment]
All PR's are deployed and `policyTaxRates_` collection is removed. So closing
