### ISSUE TITLE
[HOLD for payment 2024-02-26] [HIGH] Move the policy tax enabled property to tax key 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#36176]
### Problem

Part of https://github.com/Expensify/App/issues/36171

The `policy. isTaxTrackingEnabled ` property does not exist in this shape in our policy data in database. Its saved as `policy.tax.trackingEnabled : boolean`. Given we are updating how the policy changes are being saved and propagated to the clients, its cleaner to keep this structure same in Onyx as well. Having different code and different data schema throughout the stack results in less straightforward, more confusing, and more bug prone code

### Solution

Update the Policy schema and usage of the `policy.isHarvestingEnabled` property to expect this data in `policy.tax.trackingEnabled : boolean` format. Update the backend API to also return the data in this shape.

Steps:
1. Update the App to accept both formats. If `policy.tax.trackingEnabled` is not available, fallback to `policy. isTaxTrackingEnabled ` in the mean time
2. Update Web to send the data as `policy.tax.trackingEnabled`
3. Update Auth to do the same
4. Remove the fallback for `policy.isTaxTrackingEnabled` from the App

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c25bc5a392761ffc</li>
        <li>Upwork Job ID: 1755684468719345664</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by mountiny** [comment]
I am unfortunately ill, doing bare minimum now to unblock peeps. Will look if I can squeeze this one in too

**Comment by mountiny** [comment]
created draft for the app Pr to add the new property

**Comment by mountiny** [comment]
Started with the App PR

**Comment by mountiny** [comment]
Web PR is up too

**Comment by mountiny** [comment]
No need for Auth changes its already there

**Comment by twisterdotcom** [comment]
https://expensify.slack.com/archives/C01SKUP7QR0/p1709049183234189

**Comment by twisterdotcom** [comment]
Ah sorry @ishpaul777 no. I was querying in Slack what the price was here, looks like we're going with $500, so I'll send a contract over in a mo.

**Comment by twisterdotcom** [comment]
Sent and updated the Payment Summary.

**Comment by twisterdotcom** [comment]
Paid!
