### ISSUE TITLE
Comment - Pressing up key doesn't open editing composer on owned message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a report
2. Send a message
3. Press up key

## Expected Result:
Editing composer should be opened on owned message

## Actual Result:
Editing composer is not opened on owned message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/83bd374e-bc76-4166-bd92-5528baf3d9da

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by iwiznia** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1707427624683799 let's assign SWM to this?

**Comment by thienlnam** [comment]
Related to live markdown so taking over

**Comment by amyevans** [comment]
Thanks!

**Comment by Skalakid** [comment]
The bug occurs because the live markdown input ref is missing the `selectionStart` prop that we use to detect key-up action. I will create PR with the fix

**Comment by thienlnam** [comment]
We've reverted the offending PR https://github.com/Expensify/App/pull/35837, so this is no longer a blocker

**Comment by robertKozik** [comment]
Tested on release `0.1.9`. Issue is no longer reproductible - https://github.com/Expensify/react-native-live-markdown/pull/176 seems to solve this
