### ISSUE TITLE
[HOLD https://github.com/Expensify/react-native-live-markdown/pull/175]Web - Composer - Composer is highlighted but there is no Insertion Pointer ( | ) in composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36172]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open ND
2. Navigate between chats

## Expected Result:
Insertion pointer should be displayed in composer

## Actual Result:
Insertion pointer is not displayed in composer

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0afbff48-c55b-43a3-9eeb-d955ef5af8be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by tomekzaw** [comment]
> ig it's a regression from https://github.com/Expensify/App/pull/35837, it changes the RNTextInput to MarkdownTextInput

There's already an existing PR from @robertKozik for same thing but for Android & iOS, we could extend that:
* https://github.com/Expensify/App/pull/35973

**Comment by thienlnam** [comment]
Taking this over since it deals with live markdown

**Comment by thienlnam** [comment]
Doesn't look like it needs to be a blocker, but let's get this resolved soon!

**Comment by robertKozik** [comment]
Now you should be able to assign 😄 . I'm going to work on extending the animated input fix now

**Comment by robertKozik** [comment]
Looks like reintroducing animated component don't solve it. It's for sure problem with/lack of autofocus prop. CC. @Skalakid

**Comment by robertKozik** [comment]
Tested locally on release 0.1.9. Issue is no longer reproductible - https://github.com/Expensify/react-native-live-markdown/pull/175 seems to solve this
