### ISSUE TITLE
[$500] Unable to paste image in the composer with a message text

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36185]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707427504774679

## Action Performed:
Open a chat
Write something (don't send it)
Try pasting an image 
## Expected Result:
Able to paste the image
## Actual Result:
Unable to paste the image
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d33a5dea-5454-4bb9-83b9-0f03b02d0853

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eedbb7f17f1b8080</li>
        <li>Upwork Job ID: 1755723100201070592</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
This is from https://github.com/Expensify/App/pull/35837

**Comment by Skalakid** [comment]
Paste eventListener is returning different targets based on input content. I created the the fix for that: https://github.com/Expensify/react-native-live-markdown/issues/177

**Comment by thienlnam** [comment]
We've reverted the offending PR https://github.com/Expensify/App/pull/35837, so this is no longer a blocker

**Comment by robertKozik** [comment]
Tested on release 0.1.9. Issue is no longer reproductible - https://github.com/Expensify/react-native-live-markdown/pull/178 seems to solve this
