### ISSUE TITLE
[HOLD VBBA] [$500] Cursor remains on previous input field after selecting Incorporation state

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have created a workspace.

1. Go to Workspaces > Select workspace > Bank account.
2. Start and follow the flow to add BA with testing credentials.
3. When you reach the Company information page, tap on any input field (like "Zip code") and enter any data.
4. Without dismissing the keyboard, scroll down and tap on "Incorporation state".
5. Select any state and go back.
## Expected Result:
The cursor should not remain on the previous input field.

## Actual Result:
Cursor remains on previous input field, causing to focus on it after selecting Incorporation state.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/4bfa5cf6-94a8-468e-a9a2-9e0004f49e84

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e72a78079ae804e2</li>
        <li>Upwork Job ID: 1755732348979916800</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by akinwale** [comment]
The BA flow is currently being refactored so we can put this on hold and wait until the [PR](https://github.com/Expensify/App/pull/34498) is merged to check if this issue still exists afterwards.

**Comment by akinwale** [comment]
The BA flow is currently being refactored so we can put this on hold and wait until the [PR](https://github.com/Expensify/App/pull/34498) is merged to check if the issue still exists afterwards.

cc @mountiny

**Comment by akinwale** [comment]
@mountiny We can close this one since this is no longer happening because the affected fields are in separate substeps.

**Comment by mountiny** [comment]
Thank you
