### ISSUE TITLE
[HOLD for payment 2024-03-07] Upgrade Reanimated to 3.7.0+

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#36187]
For context, this task is just a branched-off subtask of enabling the new React Native architecture in E/App.

### Problem
Reanimated 3.6.1 does not work with Fabric in React Native 0.73, preventing us from enabling the new arch.

### Solution
Upgrade to Reanimated 3.7.0

**Comment by roryabraham** [comment]
@garrettmknight someone from SWM will comment soon to assign themselves to this.

**Comment by BartoszGrajdek** [comment]
Hey! I'm Bartosz from Software Mansion and I would like to work on this task.

**Comment by roryabraham** [comment]
Clarifying here that whatever C+ is assigned should be paid $250 for their review of https://github.com/Expensify/App/pull/36404 instead of the standard $500

**Comment by roryabraham** [comment]
Currently waiting on C+ review from @allroundexperts, and it looks like he's [started reviewing](https://github.com/Expensify/App/pull/36404#issuecomment-1965939239)

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @BartoszGrajdek 
- Contributor+: @allroundexperts $500

Please request!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary.
