### ISSUE TITLE
mWeb - Settings – Banner in About, Preference and Security is partly visible when open it Offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36183]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login and go Offline
3. Navigate to Settings
4. Click on About
5. Scroll to view the banner
6. Click on Preferences
7. Scroll to view the banner
8. Click on Security
9. Scroll to view the banner

## Expected Result:
Banner in About, Preference and Security is fully visible when open it Offline

## Actual Result:
Banner in About, Preference and Security is partly visible when open it Offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d01e76de-ec2d-4ca5-9cc5-82c3660be648

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
I don't think this has anything to do with offline. It just seems like the new design we implemented here https://github.com/Expensify/App/pull/35662

can someone confirm @mountiny @shawnborton ?

**Comment by marcaaron** [comment]
Oh I think "partly visible" means we are missing the animation section. Got it now. Yes, reproduced on Android web.

Given that this only affects offline and very specific to this platform I'm not sure we need to make this a deploy blocker, but seems possibly related to that PR linked above.

**Comment by mountiny** [comment]
Interesting, thanks, I think this can be handled by SWM as a follow up @kosmydel @filip-solecki

**Comment by filip-solecki** [comment]
Sure, we will work on this!

**Comment by mountiny** [comment]
All of the images should be in the card now 
![image](https://github.com/Expensify/App/assets/36083550/33e5f699-27ef-43ae-b4e2-b5e89134efd4)
 so I feel like this hsould be not repro anymore

**Comment by mountiny** [comment]
On main

**Comment by filip-solecki** [comment]
Shouldn't it be closed as we moved illustrations on those pages to Card component? (as @mountiny mentioned above)

**Comment by garrettmknight** [comment]
Ah, good call. Closing.
