### ISSUE TITLE
Markdown characters are too faint on the live preview

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/App#36198]
Context https://expensify.slack.com/archives/C03U7DCU4/p1707425947365449

Examples:
![image](https://github.com/Expensify/App/assets/30609178/c33c716e-7f9d-4143-964b-45cc6ce42992)
![image](https://github.com/Expensify/App/assets/30609178/12159c79-4df4-4380-9b70-546a087d278b)

# Problem

Markdown characters are too faint on the live preview

# Solution

Change the color, maybe to our supporting text like so:
![image](https://github.com/Expensify/App/assets/30609178/acbe1c53-5553-48db-ab70-2483d2180905)

**Comment by bfitzexpensify** [comment]
@tomekzaw please comment here so I can assign this issue to you - thanks!

**Comment by tomekzaw** [comment]
commenting

**Comment by thienlnam** [comment]
Updated the image assets

**Comment by tomekzaw** [comment]
Thanks, now I see it, I agree that Markdown syntax characters are too faint indeed.

Currently, we're using `colors.productLight600` / `colors.productDark600` (see [here](https://github.com/Expensify/App/blob/22d36638391540d6f84e1ebe419f7aa8206c6876/src/hooks/useMarkdownStyle.ts#L13), [here](https://github.com/Expensify/App/blob/22d36638391540d6f84e1ebe419f7aa8206c6876/src/styles/theme/themes/light.ts#L24) and [here](https://github.com/Expensify/App/blob/22d36638391540d6f84e1ebe419f7aa8206c6876/src/styles/theme/themes/dark.ts#L24)).

Sounds like an easy fix, will submit a PR with more visible colors.

**Comment by tomekzaw** [comment]
Should be fixed with https://github.com/Expensify/App/pull/36320
