### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] [CRITICAL] [Backwards Compatibility] Update UI for closed expense reports with no expenses

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#36190]
### Problem
When a report is deleted in OldDot, it is currently hard-deleted, along with any comments on the report. As we move to a chat-centric NewDot, it will be more common to have reports with a comment history, and losing that context upon report deletion would be confusing for participants.

### Solution
For reports _with comments_, we will update the backend (internal ref: https://github.com/Expensify/Expensify/issues/350244) to instead soft-delete the report, putting its `statusNum` to `2` (`CLOSED`). _Note that reports without comments will still be hard-deleted._

On the front end, we need to update the UI so that the report preview shows `[Deleted report]` (similar to how we show `[Deleted request]` or `[Deleted message]` in other scenarios) and the report can still be commented on.

So for reference, the three UI states for a closed report, depending on a combo of the report's type and number of expenses, would be:
1. `closed` `chat` report: existing UI of an archived chat room
2. `closed` `expense` report with expenses: existing UI of a completed expense report with no action required
3. `closed` `expense` report with no expenses: (what we're building here) an archived expense report, which only exists to house comment history (and can still be commented on)

### Setup/Reproduction steps
1. Go to OldDot and open the settings for the Collect/Control policy (create one first if needed)
2. In the JS console with the policy open, run:
```js
p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = "true";
p.save();
```
3. Create an open expense report (but do not add expenses to it)
4. Comment on it
5. In NewDot, open the report and grab its reportID from the URL
6. In the console, run:
```js
window.Onyx.merge(`report_<myReportID>`, {
    statusNum: 2,
});
```
(or put this in a `useEffect` hook in a component)

### Feature implementation requirements
* Report preview in the workspace chat should render `[Deleted report]`
* Option row in the LHN should render `[Deleted report]` as appropriate
* The expense report should render according to this mock:
![deleted-report-mock](https://github.com/Expensify/App/assets/7277067/acd6fa3e-4df2-4327-a4a0-aab28044e1b5)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105da3eb4f9af3f30</li>
        <li>Upwork Job ID: 1756061610101006336</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by amyevans** [comment]
@abdulrahuman5196 could you review the above proposal please?

**Comment by greg-schroeder** [comment]
bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
Hi, @greg-schroeder  sorry I haven't looked into this yet. Will work on review today.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
Meanwhile questions on the usecase I have?

>closed expense report with no expenses

Does this mean settled expenses? I am unable to delete a approved report in oldDot also currently. Only able to delete expense report in processing state

Is this usecase only for transition of oldDot to newDot?
In new dot i don't see a way of creating expense report without expense directly. One way to achieve this is to create expense request and add comments and delete the request alone without deleting the report.
But still I don't have a option to delete the total expense report in new dot.

Could you kindly provide information on how this `expense report with no expenses` can be achieved for testing? Kindly do let me know if I had misunderstood something here.


@amyevans

**Comment by abdulrahuman5196** [comment]
Anyways I don't want to block the proposal review phase on the above questions. Since the proposal is to do a straightforward implementation after the `closed expense report with no expenses` state is achieved. 

The proposal by @rayane-djouah here looks good https://github.com/Expensify/App/issues/36190#issuecomment-1936785672 and has good amount of information/cases to implement the feature. We can do through testing in PR phase.

🎀 👀 🎀
C+ Reviewed

cc: @amyevans

**Comment by amyevans** [comment]
> > closed expense report with no expenses
>
> Does this mean settled expenses?

No, not settled expenses, literally no expenses (an empty report).

> I am unable to delete a approved report in oldDot also currently. Only able to delete expense report in processing state

Being unable to delete an approved report in OldDot is expected. You shouldn't be able to delete a report in the processing state either though (you need to retract it first), so I am confused about how you are seeing that. Maybe share a recording and the email(s) you're testing with? Currently when deleting an Open report, this is what happens:

https://github.com/Expensify/App/assets/7277067/bf8c6947-168a-4ddd-b0cd-473c8073e0b0

![now-unreported-expense](https://github.com/Expensify/App/assets/7277067/9a32e5b9-1420-4926-8dd7-b3b6303eabff)

1. any expenses are removed from the report (become unreported) and 2. the report is hard-deleted from the database

I will be updating the backend so that point 2 only happens in the future if the report has no comments, and if the report _does_ have comments, then it will instead become `Closed`. Here's that scenario in action locally for me:

https://github.com/Expensify/App/assets/7277067/d1889ce6-3110-4b9e-8037-f362746994b9

But that backend work is not live yet and may not be for several weeks because it's held up on some other in-progress work. We shouldn't let that block progress here though.

---------

> Is this usecase only for transition of oldDot to newDot?

Yes, since you can't delete a report from NewDot, this only applies to someone taking the action in OldDot.

> In new dot i don't see a way of creating expense report without expense directly. One way to achieve this is to create expense request and add comments and delete the request alone without deleting the report.
> But still I don't have a option to delete the total expense report in new dot.

Yep, all correct.

> Could you kindly provide information on how this expense report with no expenses can be achieved for testing?

1. create expense request
2. add comments
3. delete the request
4. add a useEffect hook containing the following to modify the status of the report to Closed:
```js
useEffect(() => {
    window.Onyx.merge(`report_547026414937073`, {
        statusNum: 2,
    });
});
```

Hope that helps but definitely happy to clarify further if not!

**Comment by greg-schroeder** [comment]
Ready for review @abdulrahuman5196!

**Comment by alexpensify** [comment]
Catching up from being OOO, it looks like the PR is waiting for @abdulrahuman5196's feedback.

**Comment by greg-schroeder** [comment]
Bump @abdulrahuman5196, this is a Critical item so it would be great to get that review started!

**Comment by abdulrahuman5196** [comment]
Sorry for the delay. Will work on review today

**Comment by greg-schroeder** [comment]
Let us know your progress on this @rayane-djouah!

**Comment by alexpensify** [comment]
Update: Making progress in the PR

**Comment by alexpensify** [comment]
Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. @mallenexpensify is stepping in as the BZ member here and will keep an eye that we get the design feedback needed to keep this one moving forward.

**Comment by mallenexpensify** [comment]
@abdulrahuman5196 , can you please provide an update,[ this in the PR ](https://github.com/Expensify/App/pull/36767#issuecomment-1967269718)is from 3 days ago. 
> I checked the working of the PR. Seems to be working fine. Will check on the response for the above question and proceed accordingly.

**Comment by abdulrahuman5196** [comment]
Hi, @mallenexpensify  it is still under discussion https://github.com/Expensify/App/pull/36767#discussion_r1504572340

**Comment by alexpensify** [comment]
@mallenexpensify -- thanks for your help here, I'm taking this one back as the BZ member at this party.

**Comment by alexpensify** [comment]
Ok, I'm caught up here. The PR is now waiting for @amyevans's final review. Let's keep pushing forward here.

**Comment by alexpensify** [comment]
Awesome, this PR is ready to go to staging.

**Comment by alexpensify** [comment]
Looks like we are still waiting for this one to go to staging.

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter N/A 
-  Contributor that fixed the issue @rayane-djouah $500 
-  Contributor+ that helped on the issue and/or PR @abdulrahuman5196 $500 

Upwork Job: https://www.upwork.com/jobs/~0105da3eb4f9af3f30

Extra Notes regarding payment: Everyone has been paid in Upwork.
