### ISSUE TITLE
[$500]  IOU - "Missing Tag" error is not display on Admin's side

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36201]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
User is an employee of Collect workspace on Old Dot which has tags set

Steps:
1. As Employee in workspace chat create a request without selecting any Tag
2. Open the detail page
3. There will be error message under Tag section
4. As Admin navigate to IOU detail page

## Expected Result:
"Missing Tag" error should be displayed on Admin's side

## Actual Result:
"Missing Tag" error is not display on Admin's side

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/9ff3a78a-559e-4fce-a267-ccc437c03b72

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc05eec0f15adadc</li>
        <li>Upwork Job ID: 1755778054936760320</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by cead22** [comment]
> "Missing Tag" error should be displayed on Admin's side

This should display only on the employee side
