### ISSUE TITLE
[$500] Android - Chat - App crashes when pasting text after returning from IOU details page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Copy text with mark down.
4. Create a money request in the chat.
5. Tap on the request preview twice to go to request details page.
6. Return to request report.
7. Paste the text with mark down.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/bf4eaffd-c256-4322-a64f-31533a34c917

[Bug6372883_1707449777394!QA.txt](https://github.com/Expensify/App/files/14220475/Bug6372883_1707449777394.QA.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d48c59f967fba116</li>
        <li>Upwork Job ID: 1755899639129485312</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by tomekzaw** [comment]
Thanks for reporting this. The app crashes due to `java.lang.NullPointerException: mMarkdownStyle is null`. I will investigate that, please assign me.

**Comment by youssef-lr** [comment]
Thanks @tomekzaw!

**Comment by tomekzaw** [comment]
Yeah I think we'll need to revert web support for now

**Comment by marcaaron** [comment]
I believe the blocker can be removed from this one as the revert is on staging now.

**Comment by youssef-lr** [comment]
I think we can close this.
