### ISSUE TITLE
[$500] No "Delete Request" and "Add a receipt" option on workspace expense report as Admin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36215]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/35744

**Version Number:** 1.4.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new expense request on a collect policy
2. Submit the expense
3. Open the expense report
4. Right-click/long-press the expense preview
5. (if employee) Verify there is no Delete Request (if admin) Verify there is a Delete Request option
6. Press the expense preview to open the transaction thread
7. Press the three-dots button
8. (if employee) Verify there is no Delete Request and Add receipt (if admin) Verify there is a Delete Request and Add receipt option

## Expected Result:
There should be Delete Request and Add a receipt option on Admins side

## Actual Result:
No "Delete Request" and "Add a receipt" option on workspace expense report as Admin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/49568d8e-4a30-4c60-8579-7827931caf6e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af6a6540446d9665</li>
        <li>Upwork Job ID: 1755897064588898304</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by Gonals** [comment]
> dupe #36202 ?

Yep. Closing
