### ISSUE TITLE
[HOLD 36196][$500] Task - System message with new task description not updated in LHN until task opened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4295166
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Assign a task with a description to a user
4. Open the task from LHN and change the description to something else
5. Return to the LHN

## Expected Result:
An updated system message with a new description is displayed below the task name in the LHN

## Actual Result:
The system message with a new task description is not updated in LHN until the task is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f1dd0e69-0e63-4ce4-8cf3-6e969713e967

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c62d321957545289</li>
        <li>Upwork Job ID: 1755962329077272576</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by paultsimura** [comment]
I believe this should be resolved in https://github.com/Expensify/App/issues/36196 by adding the optimistic system messages.
cc: @thienlnam

**Comment by thienlnam** [comment]
Yeah correct, this is known and will be fixed in https://github.com/Expensify/App/issues/36196

**Comment by lschurr** [comment]
On hold.

**Comment by lschurr** [comment]
On hold.

**Comment by lschurr** [comment]
On hold.

**Comment by lschurr** [comment]
On hold.

**Comment by lschurr** [comment]
Hold.

**Comment by thienlnam** [comment]
This is resolved now!
