### ISSUE TITLE
[$500] Workspace switcher - Workspace filter is reset after killing app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- There is at least one workspace.
1. Launch New Expensify app.
2. Open workspace switcher.
3. Select a different workspace.
4. Kill the app.
5. Relaunch it.
6. Open workspace switcher.

## Expected Result:
The workspace filter is preserved after closing and relaunching the app.

## Actual Result:
The workspace filter is reset to Expensify.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/12fd8451-cfad-458f-ba32-987ea3da2bbc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef1292b6f671eb4d</li>
        <li>Upwork Job ID: 1755961294892625920</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by getusha** [comment]
Discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1707678505606889

**Comment by hayata-suenaga** [comment]
[also discussing this internally](https://expensify.slack.com/archives/C036QM0SLJK/p1707757460120639)

**Comment by zanyrenney** [comment]
closing as we discussed this as being the desired behaviour in the thread Hayata linked above!
