### ISSUE TITLE
[Hold for payment 2024-03-06] [$500] Tag - Selected tag is missing in Split report when split scan is created offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36237]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35913

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has tags.
1. Go to workspace chat.
2. Go offline.
3. Click + > Split bill > Scan.
4. Create a scan request.
5. Click on the split preview.
6. Enter amount, merchant and select a tag.
7. Click Split.
8. Navigate to split report.

## Expected Result:
The selected tag appears on Tag row.

## Actual Result:
The Tag row is missing the selected tag.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/50c34e58-5fc8-4498-b952-d2b6f2f2c594

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174fb7f86a4edd9a2</li>
        <li>Upwork Job ID: 1755965144915570688</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @gabrielessner

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
When completing the Split Bill, we do not pass the updated category & tag for each individual IOU transaction:

https://github.com/Expensify/App/blob/ad3d78c1ce86c99b3b3e0fb65300a54705e22c77/src/libs/actions/IOU.ts#L2231-L2242

### What changes do you think we should make in order to solve the problem?
When completing the Split Bill, we need to pass the category & tag for each individual IOU transaction as well:

```js
        const oneOnOneTransaction = TransactionUtils.buildOptimisticTransaction(
            isPolicyExpenseChat ? -splitAmount : splitAmount,
            currency ?? '',
            oneOnOneIOUReport?.reportID ?? '',
            updatedTransaction.comment.comment,
            updatedTransaction.modifiedCreated,
            CONST.IOU.TYPE.SPLIT,
            transactionID,
            updatedTransaction.modifiedMerchant,
            {...updatedTransaction.receipt, state: CONST.IOU.RECEIPT_STATE.OPEN},
            updatedTransaction.filename,
            null,
            updatedTransaction.category,
            updatedTransaction.tag,
        );
```


### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When completing the scan split manually, the tag & category are not updated optimistically in the individual transactions.

### What is the root cause of that problem?
When completing the Split Bill, we do not pass the updated category & tag for each individual IOU transaction:

https://github.com/Expensify/App/blob/ad3d78c1ce86c99b3b3e0fb65300a54705e22c77/src/libs/actions/IOU.ts#L2231-L2242

### What changes do you think we should make in order to solve the problem?
When completing the Split Bill, we need to pass the category & tag for each individual IOU transaction as well:

```diff
        const oneOnOneTransaction = TransactionUtils.buildOptimisticTransaction(
            isPolicyExpenseChat ? -splitAmount : splitAmount,
            currency ?? '',
            oneOnOneIOUReport?.reportID ?? '',
            updatedTransaction.comment.comment,
            updatedTransaction.modifiedCreated,
            CONST.IOU.TYPE.SPLIT,
            transactionID,
            updatedTransaction.modifiedMerchant,
            {...updatedTransaction.receipt, state: CONST.IOU.RECEIPT_STATE.OPEN},
            updatedTransaction.filename,
+            undefined,
+            updatedTransaction.category,
+            updatedTransaction.tag,
        );
```

#### Result:

https://github.com/Expensify/App/assets/12595293/cd27e3da-bb83-4460-b12c-9aebc894b39b


### What alternative solutions did you explore? (Optional)

**Comment by johncschuster** [comment]
bumped in Slack

cc @arielgreen as this might be related to #vip-split

**Comment by rushatgabhane** [comment]
@paultsimura's proposal looks good to me 🎀 👀 🎀

**Comment by rushatgabhane** [comment]
On a sidenote, we should consider passing objects instead of 15 func params 😅

**Comment by danieldoglas** [comment]
hm, I think that will make that method different from all the other `buildOptmistic*` methods we have, which I'm not sure it would be ideal. 

@rushatgabhane can you propose that on #expensify-open-source so we can have more opinions on it?

**Comment by paultsimura** [comment]
@danieldoglas if you agree with the proposal review, could you please assign me here so I could start with the recordings? The parameters format can be discussed within the PR IMO.

**Comment by paultsimura** [comment]
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/36759

**Comment by rushatgabhane** [comment]
@johncschuster could you please attach payment summary, thanks 🙇

**Comment by rushatgabhane** [comment]
payment request here https://staging.new.expensify.com/r/1368693063642793

**Comment by johncschuster** [comment]
Sorry for the delay! I'm on the payment summary in just a few minutes

**Comment by johncschuster** [comment]
## Payment Summary:

Contributor: @paultsimura - $500 paid via Upwork
C+ Reviewer: @rushatgabhane - - $500 paid via Manual Request

**Comment by paultsimura** [comment]
I believe it's due payment on March 7, right?
Deployed to prod on [Feb 29](https://github.com/Expensify/App/pull/36759#issuecomment-1970127562).

**Comment by johncschuster** [comment]
I see Feb 28 on my end, so I would pay this out tomorrow.

![Screenshot of Google Chrome at Mar 5, 2024 at 12_32_23 PM](https://github.com/Expensify/App/assets/5579997/cc4aef0a-1931-4198-b80c-312c1b6ca315)

**Comment by johncschuster** [comment]
Payment has been issued to @paultsimura 🎉

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane based on summary.
