### ISSUE TITLE
Wokspace - WS background is now white and shows sharp corners

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36246]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre Cond: User has no WS created
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Click the Expensify Settings menu to access the WS page
4. Observe the modal

## Expected Result:
User expects to see a purple background on the WS modal as in PROD

## Actual Result:
There is just a white on white background, this is the only banner without a colored background. IF this is the case now, the corners of the banner should now be rounded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/1f28500c-2e89-4855-bce7-009fe9b14f6b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Production 
![image](https://github.com/Expensify/App/assets/93399543/8eda1911-2be2-46a5-ad52-35c63980c22e)

**Comment by kosmydel** [comment]
PR https://github.com/Expensify/App/pull/35672#pullrequestreview-1871981797 addresses this issue.

**Comment by marcochavezf** [comment]
> PR https://github.com/Expensify/App/pull/35672 addresses this issue.

Cool I will add it to the `Fixed issues` section in the PR

**Comment by mountiny** [comment]
I think we would not CP that PR @kosmydel so either we separate the fix so it can be CPed or we remove the deploy blocker label from here @marcochavezf

**Comment by marcochavezf** [comment]
Sounds good, given that we're not going to remove the CP I'm going to remove the deploy blocker label

**Comment by marcochavezf** [comment]
PR was deployed a month ago but the issue was not closed automatically.
