### ISSUE TITLE
[HOLD for payment 2024-03-25] [$500] Message action menu - Last option is not selected when pressing up key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36245]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4294106
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Right click on owned message
2. Press on up key till you rich the 'reply in thread' option
3. Press up key once more

## Expected Result:
Focus should be applied on 'Delete comment' option

## Actual Result:
Focus is not applied on 'Delete comment' option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b598ae63-66c1-4136-b769-c7086c3d4c25

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017003c89d832c6ad8</li>
        <li>Upwork Job ID: 1755970808587268096</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Last option is not selected when pressing up key

### What is the root cause of that problem?
Because index '0' is disabled it breaks early herehttps://github.com/Expensify/App/blob/b9aada861c4e740a422a44c4c13c245382b1f082/src/hooks/useArrowKeyFocusManager.ts#L75-L76
### What changes do you think we should make in order to solve the problem?

Change it to
```
if (newFocusedIndex < 0) {
                    newFocusedIndex = disableCyclicTraversal ? -1 : maxIndex
                    break;
                }
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
>@FitseTLT unfortunately your proposal will break re-focusing on the emoji search box using the arrow keys.


@Ollyws Thanks! that was a nice catch 👍 

But I have to point that the selected proposal is principally wrong in two ways

1. The basic principle with the condition `                if (newFocusedIndex < 0) {`  is that we shouldn't normally have negative indexes and it is correct. 
But the condition
`                if (newFocusedIndex === -1) {` will narrow down the exception so when `itemsPerRow` is more than 1 the index could jump to less than -1 and the same issue that we are facing in this current issue will reoccur.
2. ` return disableCyclicTraversal ? actualIndex : maxIndex` returning `maxIndex` when cyclic traversal is allowed assumes `maxIndex` is not disabled which is wrong and on cases where the `maxIndex` is disabled the current issue will re-occur


Now the emoji case is an exception where in `EmojiPickerMenu` we allow and use negative indexes for focusing on the search input here https://github.com/Expensify/App/blob/3a702ce30137d84275dc56a7dd472718672652a9/src/components/EmojiPicker/EmojiPickerMenu/index.js#L95-L96

So the perfect solution is to add to my [proposal](https://github.com/Expensify/App/issues/36245#issuecomment-1936114460) an option in `useFocusManager` where we can allow negative indexes and pass that parameter in emoji's case and other case where we want to allow negative indexes and we will use that additionally in this condition 
https://github.com/Expensify/App/blob/b9aada861c4e740a422a44c4c13c245382b1f082/src/hooks/useArrowKeyFocusManager.ts#L75-L76

**Comment by FitseTLT** [comment]
> @GandalfGwaihir, proposals should also cover every edge case(if any) instead of the just core idea.

I think edge cases can be left for PR phase but this case is not at all about being an edge case. The only reason it didn't break the search input focus was a sheer luck that for emoji we have 8 item per row so when it deducts on the while loop it becomes
8 > 0 > -8 Now if you are on the right-most emoji it disables the focusing as in my original proposal. as it becomes 15 > 7 > -1
https://github.com/Expensify/App/assets/38649957/241349ec-9c4f-45e5-b744-b5f4bf732102

**Comment by FitseTLT** [comment]
> @GandalfGwaihir, proposals should also cover every edge case(if any) instead of the just core idea.

I think edge cases can be left for PR phase but this case is not at all about being an edge case. The only reason it didn't break the search input focus was a sheer luck that for emoji we have 8 item per row so when it deducts on the while loop it becomes
8 > 0 > -8 Now if you are on the right-most emoji it disables the focusing as in my original proposal. as it becomes 15 > 7 > -1

https://github.com/Expensify/App/assets/38649957/162d585a-7005-4ec4-a097-2aee94347171



cc @puneetlath @Ollyws

**Comment by puneetlath** [comment]
@Ollyws mind summarizing the current state of this issue for me?

**Comment by FitseTLT** [comment]
@Ollyws Updated [Proposal](https://github.com/Expensify/App/issues/36245#issuecomment-1936114460)
Main differences with proposal https://github.com/Expensify/App/issues/36245#issuecomment-1937947590:
1. We don't need to create another `while` loop inside the `while` loop, we only need to let the loop continue in the case of cyclic traversal (as the already existing while loop is designed to avoid the selection of disabled indexes).
2. We don't need to create new parameter for `useArrowKeyFocusManager ` we only need to use `break` mechanism which we are using currently that works well special cases of emoji picker (instead of returning `actualIndex`) to avoid the breaking of the search input focusing on emoji picker 👍

**Comment by FitseTLT** [comment]
> @FitseTLT for clarification, the reason to add another while loop is to check if the `maxIndex` is disabled or not, because we may have some special cases in future (like emoji picker) where we do need to disable `maxIndex` or any index, so we need to make sure that we don't return any number without checking `disabledIndexes.includes(newFocusedIndex)`.

That's exactly what I am saying to check `maxIndex` is not disabled you just need to set the `newFocusedIndex` to `maxIndex` and let the loop continue (I am not suggesting returning it) and the loop will check if it is disabled or not and proceed accordingly
```
                    newFocusedIndex = maxIndex;

```

**Comment by puneetlath** [comment]
Have you had a chance to take a look @Ollyws?

**Comment by FitseTLT** [comment]
PR will be ready in 2 days

**Comment by puneetlath** [comment]
@FitseTLT @Ollyws How's this going?

**Comment by puneetlath** [comment]
@Ollyws friendly reminder about the checklist so that we can pay on Monday.

**Comment by puneetlath** [comment]
All paid. Thanks y'all! 

Regression test issue is here: https://github.com/Expensify/Expensify/issues/382048
