### ISSUE TITLE
User who interacts with task is not subscribed to task room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36255]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.39-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707437256050179

## Action Performed:
1.User A creates a task in a public #room
2.User B marks the task as complete
3.Then User A @mentions User B
## Expected Result:
User B should already be a member of the task room, mentioning them should not cause a whisper
## Actual Result:
User B is actually not a member of the task room and we send a whisper to invite them
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-02-08 at 19 07 41@2x](https://github.com/Expensify/App/assets/38435837/cfac1994-27af-4d33-83c1-21c475c101e2)
![Screen Shot 2024-02-09 at 10 55 59 AM](https://github.com/Expensify/App/assets/38435837/af917ac2-0f54-4e4b-95c1-7af3af67cd05)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100df9366cd5953d2</li>
        <li>Upwork Job ID: 1756040705229066240</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
This is a BE update

**Comment by CortneyOfstad** [comment]
@thienlnam Sounds good and to confirm, do you know what wave this best fits under?

**Comment by thienlnam** [comment]
This would go under vip-vsb

**Comment by CortneyOfstad** [comment]
Changed the frequency to medium on this. Definitely is important, but can adjust if needed 👍

**Comment by thienlnam** [comment]
Adjust priority to match

**Comment by CortneyOfstad** [comment]
No bites yet as there are other higher priority issues being tackled first.

**Comment by quinthar** [comment]
All Task work is FUTURE

**Comment by CortneyOfstad** [comment]
Going to keep this weekly in case there are any changes 👍

**Comment by CortneyOfstad** [comment]
I am going to be heading OoO until March 11th, but going to be applying this as monthly so it does not go overdue while I am out. Since this is **Future** priority, I don't see too much movement happening 👍

**Comment by CortneyOfstad** [comment]
Was OoO — this is pretty low priority so adjusting the date label again. Will continue to monitor as there are other higher priority issues that needed to be resolved first 👍

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by CortneyOfstad** [comment]
I'm also not able to recreate this 

@m-natarajan are you able to recreate this on your side?

**Comment by thienlnam** [comment]
Looks like this has been resolved
