### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] [Simplified Collect][Profile] Share page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#36250]
Implement `Share page` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d5878a5923a532a</li>
        <li>Upwork Job ID: 1755978221187821568</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @narefyev91</details>

**Comment by luacmartins** [comment]
@narefyev91 can you comment on this issue so I can assign it to you?

**Comment by narefyev91** [comment]
Hi! I'm Nicolay from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by sakluger** [comment]
For my own reference later, once a PR has been merged, I'll send an Upwork offer to @aimane-chnaif. @narefyev91 does not require Upwork payment since he works with Callstack.

**Comment by trjExpensify** [comment]
@sakluger offer has been sent to @aimane-chnaif automagically, and accessible here when you're ready to pay it out: https://github.com/Expensify/App/issues/36250#issuecomment-1936255916

**Comment by trjExpensify** [comment]
Updated the title to reflect the hold ([relevant discussion](https://expensify.slack.com/archives/C036QM0SLJK/p1707809770092529?thread_ts=1707768612.328849&cid=C036QM0SLJK)).

**Comment by sakluger** [comment]
Nice! I checked the Upwork job right after it was created, and no offers were sent. It's nice to see that our automations are working well.

@trjExpensify, thanks as well for adding the hold 🙇.

**Comment by trjExpensify** [comment]
@narefyev91 as the PR for #35719 has been merged, I'm removing the hold from this issue. 👍

**Comment by luacmartins** [comment]
@narefyev91 do we have a draft PR for the share page yet?

**Comment by narefyev91** [comment]
@luacmartins nope - as I mentioned in slack - Callstack is not working today. Draft page should be ready tomorrow

**Comment by luacmartins** [comment]
Thanks for the ping! Update the title. @sakluger could you assist with the payment please?

**Comment by sakluger** [comment]
Completed payment to @aimane-chnaif, we're good to close!
