### ISSUE TITLE
[$500] Workspace - Navigating to a Free WS shows a blank chat or a skeleton loader

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/1971097
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is logged with the same account in OD and ND. User has existing Free WS
1. OD: Go to Settings > Workspaces > Group and click on any Workspace policy
2. Repeat step 1 a couple of times

## Expected Result:
User is redirected to NewDot, user is still logged in with the same account and the Workspace settings page is displayed

## Actual Result:
User is redirected to NewDot, user is still logged in with the same account and skeleton loader in chat history appears. When user repeat step 1, instead skeleton a blank page may appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a85c3db3-137a-4293-b919-ea1966266e78

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce42cdc4c90a4357</li>
        <li>Upwork Job ID: 1755987748541784064</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by lschurr** [comment]
Asked in Slack - https://expensify.slack.com/archives/C05DWUDHVK7/p1707758039308739

**Comment by lschurr** [comment]
We're closing this one after discussing in Slack.
