### ISSUE TITLE
[$500] Chat - Text is always pasted as plain text when editing messages

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36268]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send message with markdown and copy it
4. Edit another message and paste copied message with markdown
## Expected Result:
Message with markdown should be correctly pasted and include markdown of original message.

## Actual Result:
Messages are pasted as plain text in edit compose box, all markdown is omitted.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/7d061a66-e4df-46f0-94c3-47c20f0dc905

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0151f8c718e0328abd</li>
        <li>Upwork Job ID: 1755994883161890816</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb

**Comment by jeremy-croff** [comment]
Seems related to Markdown preview. Has this been reverted? I dont get markdown preview anymore in staging.new

**Comment by jeremy-croff** [comment]
Can you confirm if you are looking for proposals? Or handled in Live Markdown Issues?

Cannot reproduce without live markdown build

**Comment by thienlnam** [comment]
We've reverted the offending PR https://github.com/Expensify/App/pull/35837, so this is no longer a blocker

**Comment by robertKozik** [comment]
This issue has the same RCA as #36269

**Comment by thienlnam** [comment]
Cool, let's consolidate there
