### ISSUE TITLE
[HOLD for payment 2024-02-20]  Login - Welcome modal is not dismissed after selecting an option

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36265]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account.
3. Select the first item in the welcome modal.
4. Go back using device navigation (not app back button).
## Expected Result:
The welcome modal is closed and user is redirected to LHN.

## Actual Result:
The welcome modal is not closed.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/56634587-918d-4e7e-a8bc-385173a85d0e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb

**Comment by marcaaron** [comment]
@teneeto curious if this could be related to our recent changes 🤔

**Comment by marcaaron** [comment]
Probably it's some problem [here](https://github.com/Expensify/App/blob/2b85bf25d4a4a15ae544c71ade2eb9f860cffc0e/src/pages/OnboardEngagement/PurposeForUsingExpensifyPage.tsx#L87-L94) since the screens are in the nav stack now. We might just want to `goBack()` before we redirect to Concierge. Should be an easy fix.

**Comment by Beamanator** [comment]
NAB b/c https://github.com/Expensify/App/pull/36283 got to prod yesterday!

**Comment by rlinoz** [comment]
You are correct @abekkala 😄

**Comment by marcaaron** [comment]
Yep you got it. I think we can close this one out.
