### ISSUE TITLE
[$500] Theme - "Security" and "Preferences" title is black in dark-colored background in light mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile Settings.
3. Go to Preferences.
4. Go to Security.
## Expected Result:
"Security" and "Preferences" title is white in dark-colored background in light mode.

## Actual Result:
"Security" and "Preferences" title is black in dark-colored background in light mode.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/3215b49b-c59c-4ae2-864b-7d3a3cdace5b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f581fd44ff6f6e08</li>
        <li>Upwork Job ID: 1755992183893385216</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by kosmydel** [comment]
These pages are being redesigned [here](https://github.com/Expensify/App/pull/35672). The issue shouldn't occur after redesign.

**Comment by mountiny** [comment]
Yep, I think we can close as this is about to be fixed, not really need to fix it now
