### ISSUE TITLE
[$500] IOU - After selecting split next to WS, if user search for available WS, no results found

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4293788
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab --- request money
3. Enter an amount and tap next
4. Note the Workspaces in the contact list
5. Tap split next to a workspace
6. Paste and search for any other available workspace

## Expected Result:
After selecting split next to WS, if user search for available WS, no results found message must not be displayed

## Actual Result:
After selecting split next to WS, if user search for available WS, no results found message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/055f8f7c-7b7a-4b3b-9d94-329ff41ab2e2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011da69988e6c51376</li>
        <li>Upwork Job ID: 1755991568491569152</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to [#vip-split-p2p-chat-groups](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by garrettmknight** [comment]
I think this is expected. You can only split between one workspace so searching for another one shouldn't show any workspaces.
