### ISSUE TITLE
Chat - Header markdown has bigger font-size in compose box than in chat history

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36272]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4292602
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Draft message with header markdown
4. Verify header font size
5. Send message
6. Verify header font size in chat history

## Expected Result:
Header font size should be equal in compose box and in chat history, or bigger in chat history as it is in Production

## Actual Result:
Header has bigger font size in compose box (19px), than in chat history (17px)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2aad41cf-f025-4337-82f1-14fddf272fd1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by neil-marcellini** [comment]
This comes from a new feature, [Live Markdown Preview for web](https://github.com/Expensify/App/pull/35837#top). I think we should fix it, but I don't think it should block the deploy. I would rather have live mark down preview deployed now with this small bug, and then fixed later.

**Comment by thienlnam** [comment]
Thanks, adding this to the tracking issue - but since we reverted the PR this no longer exists

**Comment by tomekzaw** [comment]
Should be already fixed with https://github.com/Expensify/App/pull/36319
