### ISSUE TITLE
[HOLD for payment 2024-03-13] [$250] [TS migration] Migrate '[Components Group 1]' component to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#36273]
# Typescript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Issues

https://github.com/Expensify/App/issues/36125
https://github.com/Expensify/App/issues/36126
https://github.com/Expensify/App/issues/36127
https://github.com/Expensify/App/issues/36128
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c98da9b39ab326a</li>
        <li>Upwork Job ID: 1757748780958019584</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by s77rt** [comment]
@mountiny I think this is just a tracking issue? Nothing to migrate here

**Comment by mountiny** [comment]
Correct this is an issue combining couple smaller  simpler files. All should be handled in one PR

**Comment by s77rt** [comment]
No regression test needed since it's not a `NewFeature`

**Comment by zanyrenney** [comment]
It's been a day since payment is due 😅  please be patient.

**Comment by zanyrenney** [comment]
**payment summary**

@s77rt requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer) paid $250
@rayane-djouah requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) paid $250
