### ISSUE TITLE
[HOLD for payment 2024-03-11] [$250] [TS migration] Migrate '[Pages Group 1]' page to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#36274]
# Typescript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Issues

https://github.com/Expensify/App/issues/36131
https://github.com/Expensify/App/issues/36132
https://github.com/Expensify/App/issues/36133
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172da0a79d2e33569</li>
        <li>Upwork Job ID: 1757748860039737344</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by godofoutcasts94** [comment]
I have applied on Upwork. Also, you can expect a PR within a day or two for review.

**Comment by godofoutcasts94** [comment]
I have some quick questions. Can someone please reply? 
- Firstly, `WorkspaceOverviewPage` and `WorkspaceOverviewCurrencyPage` are changed to `WorkspaceProfilePage` and `WorkspaceProfileCurrencyPage`. Right? 
- How to test `LoadingPage` when migrating it from `.js` to `.tsx`?

**Comment by mountiny** [comment]
@godofoutcasts94 yep that sounds about right

**Comment by godofoutcasts94** [comment]
> @godofoutcasts94 yep that sounds about right
Okay then, let me work on those 2 and complete them as well.

**Comment by godofoutcasts94** [comment]
PR will be ready for review by today or latest by tomorrow @ntdiary.

**Comment by trjExpensify** [comment]
Confirming payments here as follows: 

- $250 to @ntdiary for the review
- $250 to @godofoutcasts94 for the fix

@ntdiary - please accept [the offer](https://www.upwork.com/nx/wm/offer/100907168) sent to you.
@godofoutcasts94 please confirm your Upwork profile, thanks!

**Comment by godofoutcasts94** [comment]
> Confirming payments here as follows:
> 
> * $250 to @ntdiary for the review
> * $250 to @godofoutcasts94 for the fix
> 
> @ntdiary - please accept [the offer](https://www.upwork.com/nx/wm/offer/100907168) sent to you. @godofoutcasts94 please confirm your Upwork profile, thanks!

Hello @trjExpensify! This is my upwork profile - https://www.upwork.com/freelancers/~0166de62e4f4b743fd

**Comment by trjExpensify** [comment]
Correct! 

@ntdiary - paid
@godofoutcasts94 - offer sent

**Comment by godofoutcasts94** [comment]
> Correct!
> 
> @ntdiary - paid @godofoutcasts94 - offer sent

Got it thanks

**Comment by trjExpensify** [comment]
Paid, closing!

**Comment by godofoutcasts94** [comment]
Thanks @trjExpensify
