### ISSUE TITLE
[HOLD for Slack discussion][$500] Style for `Next steps` in Spanish is off

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36281]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-2
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @pecanoro 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707497771013079

## Action Performed:
1.Create a money request in a collect policy so it creates a expense report
2.Open the report and observe the next steps in the header
## Expected Result:
Text properly styled inside the pill.
## Actual Result:
If text is longer than its English counterpart, the style is off.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![image](https://github.com/Expensify/App/assets/38435837/f1931cca-c971-44f6-80fe-57ab0491194b)
![Monosnap New Expensify 2024-02-09 11-51-00](https://github.com/Expensify/App/assets/38435837/c154c7d8-c23b-4378-94f4-7517efebc423)

![Screen Shot 2024-02-09 at 2 11 35 PM](https://github.com/Expensify/App/assets/38435837/f1358c65-511e-4910-9865-cbc925addd7e)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164f4425c04d6fbf4</li>
        <li>Upwork Job ID: 1756035382066040832</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by pecanoro** [comment]
We might be removing these pills, so HOLD until @dannymcclain confirms [here](https://expensify.slack.com/archives/C049HHMV9SM/p1707498307592429?thread_ts=1707497771.013079&cid=C049HHMV9SM).

**Comment by sakluger** [comment]
Closing for now since we will eventually be removing those next steps pills.
