### ISSUE TITLE
[HOLD for payment 2024-02-20] [HOLD for payment 2024-02-19] IOU - The chat window is blank after I edit the description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36307]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36287

## Action Performed:
1. Create a money request with a description
2. Navigate to the description edit page
3. Edit the description

## Expected Result:
User should see the IOU details.

## Actual Result:
On web, the chat window is blank after I edit the description. On Android and iOS native and mWeb, I'm taken to the LHN after editing.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2af95ca8-94a4-4f72-a4f6-525793d986ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by godofoutcasts94** [comment]
This issue is on staging but not on dev

**Comment by Beamanator** [comment]
> On Android and iOS native and mWeb, I'm taken to the LHN after editing.

I also see this on iOS Native, v1.4.39-7

**Comment by Beamanator** [comment]
Ok I confirmed this is NOT happening in dev, so it must have been fixed somewhere (as a contrib mentioned [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1707683232742339))

**Comment by Beamanator** [comment]
Fixed by https://github.com/Expensify/App/pull/36329

**Comment by Beamanator** [comment]
no payment needed here
