### ISSUE TITLE
Enhance User Experience: Addressing Multiple Download Clicks in Electron with electron-dl Package

### ISSUE THREAD

**Issue by wildan-m** [Expensify/App#36305]
In order to properly evaluate if a new library can be added to `package.json`, please fill out this request form. It will be automatically assigned someone from our review team that will go through and vet the library.

Note: This is only for production dependencies. While we don't want people to add packages to dev-dependencies willy-nilly, we recognize that there isn't as great of a need there to secure them.

# Name of library:

## Details
- Link to package: https://www.npmjs.com/package/electron-dl
- Problem solved by using this package: https://github.com/Expensify/App/issues/35189?notification_referrer_id=NT_kwDOALTGb7M5MjIwNDQ2MjY1OjExODQ3Mjc5#issuecomment-1928717500 (Desktop Version)
- Number of stars in GH: 1101
- Number of monthly downloads: 139.606 (2024, January)
- Number of releases in the last year: 1
- Level of activity in the repo: The last commits were last week ( Feb 3, 2024)
- Alternatives: -
- Are security concerns brought up and addressed in the library's repo? No
- How many dependencies does this lib use that will be brought into our code? 3
- What will the effect be on the bundle size of our code? It's a small package with 19.6 kB unpacked Size

**Comment by techievivek** [comment]
Not sure why this got closed. Maybe this GH needs to be created by an internal engineer? I will reopen so the App deployers can evaluate the request.

**Comment by wildan-m** [comment]
@techievivek maybe this automation potentially leads to inaccurate judgement? https://github.com/Expensify/App/issues/36305#issuecomment-1937795036

**Comment by AndrewGable** [comment]
Yeah issues need to be opened by an internal member. I will propose this library this week.

**Comment by wildan-m** [comment]
Thanks @AndrewGable

**Comment by wildan-m** [comment]
@AndrewGable any updates?

**Comment by AndrewGable** [comment]
Sorry no updates yet, will hopefully get to it by this week.

**Comment by AndrewGable** [comment]
Ok just posted, I should have some feedback for you soon!

**Comment by techievivek** [comment]
We've decided against adding a new package. Primarily because it's small, poorly maintained, and lacks any secret sauce that would be challenging to implement ourselves. So, let's replicate the logic in our codebase and utilize that instead.
