### ISSUE TITLE
[HOLD for payment 2024-02-20] [HOLD for payment 2024-02-19] Web - IOU - LHN can be seen twice when navigating back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36306]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39.7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36287

## Action Performed:
1. Create a money request with a description
2. Navigate to the description edit page
3. Edit the description
4. Go back using the Chrome arrow button

## Expected Result:
The LHN shouldn't be duplicated.

## Actual Result:
LHN can be seen twice when navigating back.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/60f01955-af36-4321-ac1b-d6abd43199dd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment]
I'm seeing a bug here, but I'm also seeing a blank white Report page after editing the description - because the URL shows https://staging.new.expensify.com/home

**Comment by Beamanator** [comment]
Fixed by https://github.com/Expensify/App/pull/36329

**Comment by Beamanator** [comment]
no payment needed here
