### ISSUE TITLE
[HOLD for payment 2024-02-21] Module not found warning in the console

### ISSUE THREAD

**Issue by kosmydel** [Expensify/App#36316]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** N/A
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1701232130505309

## Action Performed:
Run the development server for web / desktop.

## Expected Result:
There shouldn't be warnings.

## Actual Result:
The warning appear:
```
[web-server] WARNING in ./node_modules/lottie-react-native/lib/module/LottieView/index.web.js 8:11-61
[web-server] Module not found: Error: Can't resolve '@lottiefiles/react-lottie-player' in '/expensify/App/node_modules/lottie-react-native/lib/module/LottieView'
```

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kosmydel** [comment]
I'm closing it, as this one was resolved.

**Comment by situchan** [comment]
@kosmydel can you still keep open for me?

**Comment by kosmydel** [comment]
Right! Sorry @situchan !

**Comment by puneetlath** [comment]
@situchan offer here: https://www.upwork.com/nx/wm/offer/101015058

Please ping me on this issue when you've accepted.

**Comment by situchan** [comment]
> Please ping me on this issue when you've accepted.

Accepted thanks

**Comment by puneetlath** [comment]
Great, all paid. Thanks everyone!
