### ISSUE TITLE
[$500] The message was not posted at correct timestamp in android

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction ( not reproducible for me)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707522928808299

## Action Performed:
1. Post a message 
2. Check for the message posted with timestamp
## Expected Result:
Message is posted immediately with correct timestamp
## Actual Result:
I wrote a message on NewDot on mobile and sent it at 2:28pm, and it didn't actually post until 3:46pm.  My phone was online the whole time (minus a quick reboot in the middle for applying security patch), and I opened the app a couple times in then, so I don't know why it took so long to send. 

In the screenshots:

- Mobile with stop at 2:28pm, and no mention of start, but both responses to start/stop
- Web, showing everything in the correct order of application
- Mobile a bit later, after it had sync'd showing everything in the correct order

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/38435837/f61b3135-a8ac-4643-ae6c-0ea002341ff8)

![image (1)](https://github.com/Expensify/App/assets/38435837/729bddb2-b53d-4340-9be5-d583c6d21466)

![image (2)](https://github.com/Expensify/App/assets/38435837/02c3de71-f9d3-42a4-bd24-b2e94e2606b5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c20112e2b34f793</li>
        <li>Upwork Job ID: 1757798084913463296</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment]
Shared this in the VIP-VSB room [here](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1708117038164539)

**Comment by CortneyOfstad** [comment]
Found a [similar issue](https://github.com/Expensify/App/issues/36891) that was just created. Going to bump the thread to get a status applied 👍

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment]
Thanks @mvtglobally! 

@m-natarajan do you know if the issue is still reproducible? I wasn't able to get this to be reproduced either

**Comment by CortneyOfstad** [comment]
@m-natarajan bump on the comment [here](https://github.com/Expensify/App/issues/36338#issuecomment-1956765101).

**Comment by CortneyOfstad** [comment]
@m-natarajan bump on the comment above ^^^ can you provide an update by EOD please? Thank you!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by CortneyOfstad** [comment]
@mvtglobally thank you! I think that we should close as this is not reproducible. If another case pops up we can re-address 👍
