### ISSUE TITLE
[$500]  IOU Report preview with links are broken

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707600516151779

## Action Performed:
Break down in numbered steps

## Expected Result:
The preview background covers all content or all content displayed within the preview area

## Actual Result:
The description link goes out to the preview background  

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-02-11 at 2 47 04 AM](https://github.com/Expensify/App/assets/38435837/da76b7fe-a568-4a12-90ff-f6618477ac65)
![Screenshot 2024-02-11 at 2 57 09 AM](https://github.com/Expensify/App/assets/38435837/99600383-988a-4993-80b5-402da1fc0b53)
![Screen Shot 2024-02-12 at 9 37 11 AM](https://github.com/Expensify/App/assets/38435837/e060a71f-95f1-4789-b8f6-02aa7b3b39f5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c26b958d064c598</li>
        <li>Upwork Job ID: 1757052575231959040</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>jjcoffee | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jjcoffee** [comment]
@lschurr FYI @ntdiary is [OOO](https://expensify.slack.com/archives/C02NK2DQWUX/p1707475868181899) until 18th Feb. I'd be happy to get take this over in the meantime.

**Comment by lschurr** [comment]
Great, assigned to you @jjcoffee

**Comment by jjcoffee** [comment]
This is a tight one! But it looks like @neonbhai's [proposal](https://github.com/Expensify/App/issues/36339#issuecomment-1938847508) got in there first (based on the edit timestamps) with the idea to wrap with a `View` with the relevant word-break styles to stop overflowing. 

We don't want to switch to using a `Text` component (as suggested in @abzokhattab's [proposal](https://github.com/Expensify/App/issues/36339#issuecomment-1938841231)) instead as we need to support HTML here.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
@mkhutornyi No worries, thanks for flagging! @lschurr looks like we can close this!

**Comment by lschurr** [comment]
Great, thanks!
