### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] Task – User with the custom name is shown as Hidden in task assignee field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36341]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4301190
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login
3. Navigate to a Group Chat
4. Click on the + in the compose box and select "Assign task"
5. Enter a a Title
6. Assign a user from the group that you have access to
7. Create the task

## Expected Result:
The assignee with the custom name is displayed in the assignee field

## Actual Result:
User with the custom name is shown as Hidden in task assignee field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/2ac4422b-11fc-4a12-a48d-e316cfb1fdaa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177663dcf0666e903</li>
        <li>Upwork Job ID: 1757110933025804288</li>
        <li>Last Price Increase: 2024-02-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by bondydaa** [comment]
no PRs from the checklist stand out to me as obvious root causes, there were 2 that touched Tasks but I don't see how they would have caused this:

https://github.com/Expensify/App/pull/35585
https://github.com/Expensify/App/pull/36048

**Comment by situchan** [comment]
https://github.com/Expensify/App/pull/35027 was deployed to production last week but this is deploy blocker

**Comment by bondydaa** [comment]
I tried reverting just https://github.com/Expensify/App/pull/36048 locally and that didn't fix it. 

Also tried reverting https://github.com/Expensify/App/pull/35027 locally and that didn't fix it either:

<img width="1529" alt="image" src="https://github.com/Expensify/App/assets/4073354/2217e7d1-8ec7-4af6-b795-22922a2324f6">

**Comment by bondydaa** [comment]
🎉 

tested that and 👍 seems to work

<img width="1534" alt="image" src="https://github.com/Expensify/App/assets/4073354/ca5936de-160a-4a0f-9ae9-a43ebb31bfcf">

@fedirjh can you get a PR up? will assign now

**Comment by bondydaa** [comment]
@anmurali nothing for you to do right now, just assigning bug for a BZ to handle payments when the time comes.

**Comment by bondydaa** [comment]
we are currently CP'ing this to staging https://expensify.slack.com/archives/C07J32337/p1707768452815609

**Comment by bondydaa** [comment]
okay this should be on staging, version `v1.4.40-1`.

@lanitochka17 can you retest to confirm for us?

**Comment by Beamanator** [comment]
This was tested! NAB!

**Comment by lanitochka17** [comment]
@bondydaa Issue is not reproducible on the latest build 1.4.41-4


https://github.com/Expensify/App/assets/78819774/aae56589-976c-47dd-ab5a-67b2d66a5223

**Comment by bondydaa** [comment]
great thanks!

**Comment by anmurali** [comment]
Payment not due for another 4 days. Rotated the label since I will be OOO till 29th!

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR FEB 20

- Issue reported by: Applause - Internal Team
- Fix: @fedirjh [$500 - pending no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/100982159)
- PR Review: @situchan [$500 - pending no regressions] [Offer Link](https://www.upwork.com/nx/wm/offer/100982071)

**Comment by abekkala** [comment]
@fedirjh and @situchan payments were sent and contracts ended - thank you! 🎉
