### ISSUE TITLE
[HOLD for payment 2024-03-06] [$250] Strikethrough line is white on links and emails

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36349]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Nagivate to any chat
3. Send any email or link with strikethrough markdown

## Expected Result:
Strikethrough line should match the color of links and emails.

## Actual Result:
Strikethrough line is white.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ec4b9868-6549-45a0-873f-c633e2cfa7c7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190109e65c0e5c4d0</li>
        <li>Upwork Job ID: 1757082391060185088</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Contributor | 0</li>
<li>mkhutornyi | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by francoisl** [comment]
Can reproduce, but no need to block on this, I'll demote. Also going to update the price as it's most likely a simple change.

**Comment by situchan** [comment]
@Krishna2323 this was deploy blocker. Are you able to find offending PR?
I suspect this came from expensify-common while working on live markdown regression fixes

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Strikethrough line is white on links and emails.

### What is the root cause of that problem?

This issue we're experiencing is because when the `a` tag is wrapped by the `del` tag (strike-through), the `del` tag will use the `baseFontStyle` color which is the white color text style, this overrides the `textDecorationColor` specified in the `a` tagStyles.

### What changes do you think we should make in order to solve the problem?

Within the already existing `AnchorRenderer`, check if the current anchor tag is a children of 'del' tag and apply the `a` tag's `textDecorationColor` style to the wrapping `del` tag.

### Screenshots

<details>
<summary>MacOS: Chrome / Safari</summary>

| Before | After |
| ------------- | ------------- |
| <img width="537" alt="Screenshot 2024-02-12 at 20 57 07" src="https://github.com/Expensify/App/assets/56457735/19354e8e-364b-4ae5-97e0-8ce8b1c44250"> | <img width="565" alt="Screenshot 2024-02-12 at 20 56 15" src="https://github.com/Expensify/App/assets/56457735/1a4d2040-8dcd-472c-b753-2d4276f9e6c2"> |

</details>

**Comment by situchan** [comment]
I think @mollfpr should handle this as he reviewed offending [PR](https://github.com/Expensify/App/pull/35462)

**Comment by mollfpr** [comment]
Reviewing now 👀 

Thanks for the ping @situchan 👍

**Comment by mollfpr** [comment]
The [proposal](https://github.com/Expensify/App/issues/36349#issuecomment-1939468794) from @mkhutornyi looks good to me!

**Dark**
![Screenshot 2024-02-13 at 18 24 24](https://github.com/Expensify/App/assets/25520267/f961a82c-1f94-43c2-8eb5-846bd53213cf)

**Light**
![Screenshot 2024-02-13 at 18 24 38](https://github.com/Expensify/App/assets/25520267/60747424-0c1e-4c2b-bb75-ebefc61198e7)

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
@mkhutornyi Let me know when the PR is ready, thank you!

**Comment by francoisl** [comment]
(Commenting to remove the Overdue label, see comment just above about the PR)

**Comment by mollfpr** [comment]
@garrettmknight Could you add the payment date? The blocker issue is closed, so there's no regression on the PR (for now).

**Comment by mollfpr** [comment]
@garrettmknight Requested in NewDot! I'll complete the checklist soon.

**Comment by garrettmknight** [comment]
Cool, dropping to weekly.

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/35462

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/35462/files#r1518590135

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think the regression step should be good and we also have a checklist to check the generic component.

> [@mollfpr] Determine if we should create a regression test for this bug.
> [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

We can a case for strikethrough an link/email and verify the strikethrough color match the link color. https://expensify.testrail.io/index.php?/cases/view/2950395

**Comment by garrettmknight** [comment]
TestRail update in - just up to you to submit for payment now!

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr based on summary.
