### ISSUE TITLE
[$500] Web -  Chat – Unable to create a group using keyboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4301035
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with account with a lot of active conversations, click on FAB the home screen
3. Click on "Start Chat"
4. Focus on the search bar and press the down arrow
5. With one of the search results highlighted, press Tab to focus on the "add to group" option, then enter.
6. With second user from the search results highlighted, press Tab to focus on the "add to group" option, then enter.

## Expected Result:
Second user gets checked and move to the top of the list.

## Actual Result:
First selected chat opens. Able add to group only first user.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/17dc57c0-0ccb-4c21-a418-ec6e88febd3b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f2238e5009c0e9b4</li>
        <li>Upwork Job ID: 1757115154327130112</li>
        <li>Last Price Increase: 2024-02-12</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by trjExpensify** [comment]
Cool, so let's close as a dupe then!
