### ISSUE TITLE
[HOLD for payment 2024-03-13] [$750] CRITICAL: [Track Expense] - FE - Handling for the self-DM 

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#36361]
https://docs.google.com/document/d/1gACVXuJS2ojNV_hwQRBLYFK_dR7vXSNlXfTnMOsdd_w/edit#bookmark=id.ff2hjz49hfnt
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186120eae0212c93d</li>
        <li>Upwork Job ID: 1763726014202585088</li>
        <li>Last Price Increase: 2024-03-02</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
We're still working on the back-end changes in parallel so we won't be able to test this until that is done but we should be able to add these changes before that

The only specific thing that would be different about this specific chat is that it has a chatType of "selfDM". I believe you can update one of the reports in onyx in dev to have this chatType that is already of type="chat"

Like this
Onyx.merge('report_900171349196769', {chatType: "selfDM"});

That should allow you to test this change

**Comment by thienlnam** [comment]
cc @techievivek Since you're working on the BE parts of this

**Comment by techievivek** [comment]
Thanks, I will work on the backend changes today.

**Comment by thienlnam** [comment]
@ishpaul777 Are you working on this issue? Have you run into anything that you need help with?

**Comment by thienlnam** [comment]
1. I think this is fine to disable, the self-DM is the spot for private notes
2. Is there a cost of adding this? Mainly thinking that people will use this as a spot to draft up notes / messages. They may want to @here mention and then copy it into a different chat
3. The self-DM will be returned as a regular chat once the BE pieces are complete. There's no plans for a fixed link

**Comment by thienlnam** [comment]
We only need this for the report title, not for every chat you send within the self-DM chat if that makes a difference. Are we able to just use the regular display name, and then only for the report onyx data change it to show displayName + (you)?

Also, feel free to move this into slack so we can do back and fourths quicker if needed

**Comment by thienlnam** [comment]
Yeah that's correct - I am trying to say we don't need to update the display name everywhere to include (you), and just setting the report.reportName to postfix (you) to indicate the report should be okay

**Comment by thienlnam** [comment]
We're close - the PR that adds the handling for the self-DM is almost in final review, but the PR that starts enabling this for existing and new chats can't be merged until we the FE handling is done.

Maybe we can create a beta, and only create the self-DMs for users within that beta so it makes testing easier for the FE?

**Comment by thienlnam** [comment]
I'll spin up an issue for that and work on that on my end

**Comment by thienlnam** [comment]
Thanks, the FE shouldn't actually change anything until the specific chat type is returned so we should be safe from affecting other parts of the app. But this allows us to keep pushing forward this project that is blocking some Wave 6 items

**Comment by thienlnam** [comment]
I did some preliminary testing - on my dev environment. I'm working on getting the beta up, but with the merge freeze we're a little behind - should have something mid week ready for you guys to test.

In the meantime, you should be able to use this to do some basic testing https://github.com/Expensify/App/issues/36361#issuecomment-1939620638

**Comment by quinthar** [comment]
Hi! What's the ETA for this to be on staging?

**Comment by thienlnam** [comment]
cc @ishpaul777 Any update on the items posted here? https://github.com/Expensify/App/pull/37165#issuecomment-1964814815

**Comment by thienlnam** [comment]
We're trying to get this merged by EOW, do you think that's still possible? We'll just have to validate with the chatType right now and then can make additional adjustments after the beta is live

**Comment by thienlnam** [comment]
@paultsimura is taking over the C+ review for this

**Comment by quinthar** [comment]
@thienlnam I see above you said;
> We're trying to get this merged by EOW, do you think that's still possible? We'll just have to validate with the chatType right now and then can make additional adjustments after the beta is live
Can you give a new ETA?

**Comment by quinthar** [comment]
Woohoo!

**Comment by thienlnam** [comment]
What do you feel like is fair for this type of issue?

**Comment by thienlnam** [comment]
Are you alright with $750? I agree it's harder to work off a design doc though it doesn't seem like the required scope changed too much

**Comment by greg-schroeder** [comment]
Offers sent to both @paultsimura and @ishpaul777

**Comment by greg-schroeder** [comment]
Filed regression test, paid both contracts, closing!
