### ISSUE TITLE
[HOLD] CRITICAL: [Track Expense] - FE - Whisper Action: Request someone pay it

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#36364]
https://docs.google.com/document/d/1gACVXuJS2ojNV_hwQRBLYFK_dR7vXSNlXfTnMOsdd_w/edit#bookmark=id.n2vaif1mdehp

For the existing transaction, open up the request flow directly to the participant selector. 
Optimistically move the transaction from the self-DM to the new place

![image](https://github.com/Expensify/App/assets/30609178/27646a02-ac19-483f-9925-1240a408e40c)

**Comment by quinthar** [comment]
Which issue is this holding on?

**Comment by thienlnam** [comment]
Consolidating here: https://github.com/Expensify/App/issues/38533
