### ISSUE TITLE
[$500] Desktop - BA - An endless spinner appears when user connects BA with Plaid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36368]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+021224dr03@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Desktop App
2. Log in with expensifail account
3. Create workspace or go to existing one
4. Go to WS settings > Bank Account
5. Select "Connect online with Plaid"

## Expected Result:
User can continue connecting BA with Plaid

## Actual Result:
An endless spinner appears when user connects BA with Plaid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ab13d541-965d-4419-8169-b5fffb6d28ef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013293255e0be91802</li>
        <li>Upwork Job ID: 1757134957890064384</li>
        <li>Last Price Increase: 2024-02-19</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Does the issue persist in 1.4.40-1?

**Comment by johncschuster** [comment]
Thanks for giving that a try, @hoangzinh! In that case, let's go ahead and close this one.
