### ISSUE TITLE
[$1250] [HOLD for payment 2024-04-03] CRITICAL: [Track Expense] - FE - Add Track Expense Flow

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#36362]
https://docs.google.com/document/d/1gACVXuJS2ojNV_hwQRBLYFK_dR7vXSNlXfTnMOsdd_w/edit#bookmark=id.jw3ehgyt25yl

First, add a beta for 'trackExpense' so this only shows up for those in the beta
Add the Track Expense Button to the FAB
This will open up the standard money request selector
Instead of choosing a participant, it will automatically select the self-DM
This will optimistically create the reportAction to the self-DM 

![image](https://github.com/Expensify/App/assets/30609178/95bd5058-31fe-496a-85b9-46aa79d3416e)

Held on [36361](https://github.com/Expensify/App/issues/36361)
Held on [#368199](https://github.com/Expensify/Expensify/issues/368199)

Note: We will have to hide the Distance option on the selector - this is held on P2P distance requests which is being worked on currently (cc @neil-marcellini )
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115a976392ebf591e</li>
        <li>Upwork Job ID: 1773037718251933696</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thienlnam</details>

**Comment by thienlnam** [comment]
cc @shubham1206agra While Ishpaul is working on the self-DM support, could you get started on this issue? 

This is holding on a few things, but there's a few things that can be done in advance like
1. Adding the beta and Track to the global create
2. Updating the IOU flow to skip the participant selector

The API call is almost done, and it would be nice to test with a draft PR to make sure we're not missing anything from the BE

**Comment by thienlnam** [comment]
@shubham1206agra Has a draft PR up, we're waiting on the self-DM to be merged first https://github.com/Expensify/App/issues/36361

Hopefully we can get something merged sometime late next week / early week after - does that sound like an accurate timeline once we have the self-DM for you to test with @shubham1206agra?

**Comment by quinthar** [comment]
Still on track for 3/8?

**Comment by quinthar** [comment]
3/8 is here!  Is it done?  If no, what is the next step, who is doing it, and when?

**Comment by thienlnam** [comment]
We've found some issues that need to be handled in the BE - I'm testing and coordinating changes with @shubham1206agra. We'll have a better sense of where things stand on Wednesday

**Comment by quinthar** [comment]
Ok, so on Wed you'll have an ETA?

**Comment by thienlnam** [comment]
All accounts should have a selfDM now - we added everyone to the beta. I'll add you to the Track expense beta though

**Comment by laurenreidexpensify** [comment]
@shubham1206agra @ishpaul777 please apply in Upwork thanks - 
[upwork.com/jobs/~017fda999369b97b34](https://www.upwork.com/jobs/~017fda999369b97b34)

**Comment by laurenreidexpensify** [comment]
@shubham1206agra bump to apply in Upwork please
@ishpaul777 offer sent 👍

**Comment by laurenreidexpensify** [comment]
Payment Summary:

$1250 - @shubham1206agra bump to apply in Upwork please
$1250 - @ishpaul777 paid in Upwork

**Comment by laurenreidexpensify** [comment]
@ishpaul777 can you confirm if there are any regression test steps required here?

**Comment by laurenreidexpensify** [comment]
@ishpaul777 can you confirm if there are any regression test steps required here?

**Comment by laurenreidexpensify** [comment]
@thienlnam ^^
