### ISSUE TITLE
[HOLD] CRITICAL: [Track Expense] - FE - Whisper Action: Categorize it / Share it with my accountant

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#36365]
https://docs.google.com/document/d/1gACVXuJS2ojNV_hwQRBLYFK_dR7vXSNlXfTnMOsdd_w/edit#bookmark=id.v32o1plr0ysn

Create a participant selector that only shows workspaces if the user has existing workspaces
Otherwise, create a workspace automatically and move it to the new policy workspace chat
Depending on the flow selected, automatically navigate to the invite page or category page for the transaction

![image](https://github.com/Expensify/App/assets/30609178/1dd7c2bc-d8bc-41ee-9943-09a356f60204)

**Comment by thienlnam** [comment]
Still working on Track and Self-DM

**Comment by quinthar** [comment]
Recognizing you haven't started, how long do you think this will take?  Is EOW realistic?

**Comment by thienlnam** [comment]
This is held on a few other issues: 
- https://github.com/Expensify/Expensify/issues/368251
- https://github.com/Expensify/App/issues/36362

**Comment by jamesdeanexpensify** [comment]
Minor note - is it possible to update this copy to `Choose a category for your expense:`

<img width="246" alt="image" src="https://github.com/Expensify/App/assets/22160301/96c2b90a-5bc5-4430-bb0d-4496d26dba66">

**Comment by thienlnam** [comment]
Consolidating here: https://github.com/Expensify/App/issues/38533

**Comment by thienlnam** [comment]
@jamesdeanexpensify I'll edit the mockup in the consolidated issue to include that new copy
