### ISSUE TITLE
[HOLD for payment 2024-02-20] [$500] The "Enter" key does not work when editing the "Description" and "Merchant" fields

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36370]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Configure the OldDot administrator account, invite an employee and include multiple categories and tags
https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0

Steps:
1. Open https://staging.new.expensify.com/

2. Log in with the employee's login
3. Click on FAB
4. Select "Request money"
5. Deposit any amount
6. Click on the "Next" button
7. Select Group Policy WS
8. Select any category or tag
9. Click the Merchant or Description field
10. Entry any data
11. Press the "Enter" key

## Expected Result:
Pressing the "Enter" key should save the data in the "Description" and "Merchant" fields and return to the IOU menu

## Actual Result:
The Enter key does not work when editing the Description and Merchant fields after selecting a Category or Tag

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/da76f991-62cd-4499-8703-97db0e4f085a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012366b11cbf8f59eb</li>
        <li>Upwork Job ID: 1757144388262604800</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment]
Potentially a regression from https://github.com/Expensify/App/pull/34471, similar to https://github.com/Expensify/App/issues/36363

**Comment by hayata-suenaga** [comment]
> Potentially a regression from https://github.com/Expensify/App/pull/34471, similar to https://github.com/Expensify/App/issues/36363

asking people involved in the original PR if this is actually related to it

**Comment by MonilBhavsar** [comment]
Thanks for explanation @shubham1206agra!
Assigning this issue to you

**Comment by Beamanator** [comment]
@shubham1206agra when can we expect a PR? 🙏  this is blocking deploy so it would be great to get a fix out ASAP please

**Comment by Beamanator** [comment]
PR merged & is being CP'd to staging 🙏

**Comment by Beamanator** [comment]
This also looks fixed on staging! 🚀
