### ISSUE TITLE
[HOLD for payment 2024-02-20] Distance - Distance sequence changes to A-B-B-B when changing the order of distance A-B-A-B

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36375]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4302941
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a distance request with A-B-A-B distance
4. Go to request details page
5. Click Distance
6. Drag the second A waypoint so that it becomes A-A-B-B

## Expected Result:
The new distance sequence is now A-A-B-B

## Actual Result:
The new distance sequence changes to A-B-B-B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/90e0d3bd-051d-4e04-b726-ed5a12faf964

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wav5
CC @dylanexpensify

**Comment by situchan** [comment]
Another regression from https://github.com/Expensify/App/pull/34869

**Comment by Beamanator** [comment]
Revert PR should fix this: https://github.com/Expensify/App/pull/36405

**Comment by Beamanator** [comment]
PR is in staging! time for re-test!

**Comment by Beamanator** [comment]
Looking much better on staging!!

**Comment by robertjchen** [comment]
was reverted
