### ISSUE TITLE
[$500] IOU with user with previous conversation can not be created from FAB

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36387]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
1. Login with user with gmail account

1. Go to FAB> Request money> Manual
2. Add user you have previous conversation with> Finish the flow

## Expected Result:
IOU should be created

## Actual Result:
Infinite loading and red dot when navigate to chat via search

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b48de8b3-c96b-4bd5-9023-df0a3ca1dbbe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010134cf90dc39faa2</li>
        <li>Upwork Job ID: 1757173216145776640</li>
        <li>Last Price Increase: 2024-02-12</li>
    </ul>
</details>

**Comment by jeremy-croff** [comment]
Related: https://github.com/Expensify/App/issues/32076

**Comment by kadiealexander** [comment]
@jliexpensify kindly helped me test this and found it wasn't reproducible.
