### ISSUE TITLE
[$500] Expense - Pay elsewhere button does not show up for admin after approving the report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36398]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-40-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** 

## Action Performed:
Precondition:
- Admin and employee are in the Collect workspace.
- Admin is also the approver.
- Reimbursement is set to "Indirect" on Old Dot.

1. Go to staging.new.expensify.com
2. [Employee] Create a money request in workspace chat.
3. [Employee] Submit the report.
4, [Admin] Approve the report.

## Expected Result:
Pay elsewhere button should show up for admin after approving the report.

## Actual Result:
Pay elsewhere button does not show up for admin after approving the report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/01823408-6eac-4e77-afe4-cd1c87bd9eb7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01639b285c7d4a3b6d</li>
        <li>Upwork Job ID: 1757345839678914560</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave7-collect-approvers
CC @RachCHopkins

**Comment by Beamanator** [comment]
I mentioned this in #wave7, thanks! 👍

**Comment by Beamanator** [comment]
This potentially looks expected, as of this PR: https://github.com/Expensify/App/pull/35347

Which is related to this issue: https://github.com/Expensify/App/issues/34951

And this bug report: https://expensify.slack.com/archives/C049HHMV9SM/p1705978407170839

cc @JmillsExpensify can you confirm?

**Comment by mountiny** [comment]
The PR was reverted
