### ISSUE TITLE
[HOLD for payment 2024-02-26] [HOLD FOR PAYMENT 21-02-2024] [Android] Support 'Hide sensitive notification content' Android OS setting

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#36413]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** me

## Action Performed:
- Disable the Show 'sensitive notifications' preference under Settings > Notifications
- Lock the device
- Receive messages from Expensify and other communication apps

## Expected Result:
- You **shouldn't be able to** read text and see the senders photo

## Actual Result:
- You **can** read text and see the senders photo

![Screenshot_20240213_134649](https://github.com/Expensify/App/assets/10736861/e7d23af6-0709-44f0-b0bd-0eebdb20f5b2)
![Screenshot_20240213_134054](https://github.com/Expensify/App/assets/10736861/3fdf3523-9c8a-4bb4-a4bf-2801429c6d55)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
There's a flag somewhere that lets us mark our app as one that shows messages/sensitive content, probably in the native Android notification classes.

**Comment by Julesssss** [comment]
Hey @dylanexpensify, oh yeah I forgot to add the label. 

But [this](https://developer.android.com/develop/ui/views/notifications/build-notification?_gl=1*1dgv3i1*_up*MQ..*_ga*MTE0NDk1NTUwLjE3MDc5MDU1MTM.*_ga_6HH9YJMN9M*MTcwNzkwNTUxMy4xLjAuMTcwNzkwNTUxMy4wLjAuMA..#lockscreenNotification) will only take 5 minutes so I'll do it myself when I have a spare moment 👍

**Comment by Julesssss** [comment]
PR in review

**Comment by Julesssss** [comment]
Yep done

**Comment by dylanexpensify** [comment]
payment coming up!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @hoangzinh $500

Please request!

**Comment by dylanexpensify** [comment]
Doing today!

**Comment by dylanexpensify** [comment]
sent @hoangzinh!
