### ISSUE TITLE
[$500] IOU-Dropdown menu to select approve is not displayed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app as admin
2. Open Workspace chat
3. Go to https://staging.new.expensify.com/
as employee
4. Open Workspace chat
5. Tap plus icon--- request money
6. Enter an amount and tap next
7. Tap request
8. Tap submit
9. Now note the workspace chat page of employee

## Expected Result:
Dropdown menu to select approve must be displayed along with "pay with expensify"& " Pay elsewhere " options.

## Actual Result:
Dropdown menu to select approve is not displayed. Only approve button shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/00edbe62-a1e1-4412-9f10-d93c3db34b25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01284370d0ca87572b</li>
        <li>Upwork Job ID: 1757387602093957120</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by muttmuure** [comment]
Closing

**Comment by muttmuure** [comment]
Sorry I missed this!
