### ISSUE TITLE
[HOLD for payment 2024-03-07] HIGH: Navigating to a thread in a public room immediately as an anonymous user shows "it's not here" page 

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#36430]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.40-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** Anonymous user
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @muttmuure 
**Slack conversation:**

## Action Performed:

1. Open Incognito browser
2. Navigate to https://new.expensify.com/r/6776919265133947
3. Open a thread within 5 seconds of page loading

## Expected Result:
Describe what you think should've happened

The thread loads

## Actual Result:
Describe what actually happened

You see an "It's not here" message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/46995600/497f51bc-61ea-43c8-8e50-a2912128db0c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
Added to a project and assigned a priority - waiting for a volunteer

**Comment by bfitzexpensify** [comment]
Same status

**Comment by youssef-lr** [comment]
I did some digging and was able to reproduce and find a workaround locally, but not sure if the solution is good or not. I'm discussing this in this [thread](https://expensify.slack.com/archives/C066HJM2CAZ/p1708134160129379).

**Comment by youssef-lr** [comment]
Resumed the discussion in the thread.

**Comment by youssef-lr** [comment]
Making a PR.

**Comment by youssef-lr** [comment]
We're still discussing the PR.

**Comment by marcaaron** [comment]
LGTM (though, I am not sure I had much more context than anyone else)

**Comment by youssef-lr** [comment]
PR is merged.

**Comment by youssef-lr** [comment]
Tested this in staging, working good. @muttmuure please give it another test so we can confirm it's fixed: https://staging.new.expensify.com/r/6776919265133947
