### ISSUE TITLE
Reimbursements - Focus (cursor) is not appearing in amount input field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n (this is new feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open workspace settings page
2. Click on 'Reimbursements'
3. Click on 'Rate'
4. Click on 'Rate' again
## Expected Result:
cursor should be displayed on amount input filed

## Actual Result:
Focus is not applied in amount input field

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/b77a1c22-bb63-487b-913f-4af552dd8017

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Looks like the rate field was changed, this is how it looks in production:

<img width="1362" alt="Screenshot 2024-02-13 at 5 35 37 p m" src="https://github.com/Expensify/App/assets/6829422/e7d34944-91f3-4685-83cd-92493653ac2d">

so probably this is not a deploy blocker

**Comment by marcochavezf** [comment]
Yeah, the MenuItem was introduced in this [PR](https://github.com/Expensify/App/pull/34849) and seems there was a long discussion about it in the related GH issue. I think the TR instructions would need to be updated once the BZ list is completed there cc @tgolen @johncschuster

**Comment by marcochavezf** [comment]
I will close this GH since it's an intended change in the UI, but feel free to re-open it if disagree
