### ISSUE TITLE
[$500] Routing number field is not auto focused.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36448]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** n 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. go to workspace setting
2. Click on connect manually
## Expected Result:
Routing number is autofocussed
## Actual Result:
Not autofocussed
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
https://github.com/Expensify/App/assets/43996225/61cc5edf-5053-40a2-b842-d4f9bc9309da

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2f2f4d15d74aa10</li>
        <li>Upwork Job ID: 1757551499003891712</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by mountiny** [comment]
I think this is not a blocker, @MrMuzyk @barttom can address this as a follow up to the PR @akinwale @shubham1206agra

**Comment by mountiny** [comment]
PR was CPed
