### ISSUE TITLE
[$500] About - Footer text has no bottom margin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile.
3. Go to About.
4. Scroll to the bottom.

## Expected Result:
The footer text will have bottom margin.

## Actual Result:
The footer text has no bottom margin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6378668_1707860652253!Screenshot_2024-02-14_at_03 27 03](https://github.com/Expensify/App/assets/115492554/1ca65bfc-435a-400c-94c2-b7acfd5d7af8)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a30c2684f91e84c5</li>
        <li>Upwork Job ID: 1757533717180780544</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by tgolen** [comment]
@kosmydel It looks like this is a bug from the PR https://github.com/Expensify/App/pull/35672. Can you fix this, please?

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM an expert agency and I will work on this as I was working also on updating Account Settings

**Comment by mountiny** [comment]
I think @s77rt should help with the review as C+ on the PR

**Comment by mountiny** [comment]
this is fixed 
<img width="1224" alt="image" src="https://github.com/Expensify/App/assets/36083550/3b3a6c35-0caa-4bbf-8c5d-97396de03ab6">

**Comment by mountiny** [comment]
Ah thanks for the ping. I do think this was very simple solution so that feels like we could skip the partial reward. I would say we look at that as a form of "how much time it saved us" when fixing the issue. In this case it was quite easy so probably very little.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/35672
- The offending PR has been commented on: Not needed. Since the author fixed the bug
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No
