### ISSUE TITLE
[HOLD for payment 2024-03-14] [Collect approvers] [$500] Offline Pay of an expense will apply even if the submitter edits an expense amount

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707832645778869

## Action Performed:

1. User A invites User B to Free workspace
2. User B submits an expense
3. User A goes offline
4. User A taps ‘Pay’ on the original expense
5. User B edits the expense amount OR adds an additional expense while User A is offline
6. User A comes back online

## Expected Result: 
Payment/Approval is stopped and the admin/approver is notified of the updated amount
## Actual Result: 
The updated expense amount is paid.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01678bf0efdcb7e4a2</li>
        <li>Upwork Job ID: 1757514507892195328</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Asked for clarification here: https://expensify.slack.com/archives/C049HHMV9SM/p1707941200321529?thread_ts=1707832645.778869&cid=C049HHMV9SM

**Comment by puneetlath** [comment]
@Gonals do you know the answer to that ^?

**Comment by Gonals** [comment]
> #36983

Yep. this `should` fix both.

**Comment by trjExpensify** [comment]
What's the next steps here?

**Comment by mananjadhav** [comment]
I've done the C+ review and testing, looking for the internal engineer feedback/merge.

**Comment by trjExpensify** [comment]
Cool, @Gonals looks like we're ready to rock here!

**Comment by puneetlath** [comment]
@mananjadhav friendly reminder about the checklist so that we can pay tomorrow.

**Comment by puneetlath** [comment]
@mananjadhav bump!

**Comment by mananjadhav** [comment]
I'll work on the checklist today.

**Comment by mananjadhav** [comment]
I tried finding the offending PR but couldn't find one. We added another property in the optimistic data, and I am not sure at what point we should've included this along with `Math.abs`.

But I do think we should add a regression test for this one.

Regression test for this one:

1. User A invites User B to Free workspace
2. User B submits an expense
3. User A goes offline
4. User A taps ‘Pay’ on the original expense
5. User B edits the expense amount OR adds an additional expense while User A is offline
6. User A comes back online
7. Confirm the money request is not paid and User A sees an error message: `The requested amount has changed`.

This will serve the linked duplicate issue as well.


@puneetlath Can you confirm the payout summary posted by the bot?

**Comment by puneetlath** [comment]
Issue for regression test: https://github.com/Expensify/Expensify/issues/379640

I am confirming that the payment summary [here](https://github.com/Expensify/App/issues/36440#issuecomment-1998183104) is accurate. @mananjadhav please request on NewDot.

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav based on summary.
