### ISSUE TITLE
[HOLD for payment 2024-03-05] [$250] 2 bottom banners for offline status are displayed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36458]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in and have created a workspace.

1. Go to Workspace > Bank account.
2. Initiate the add BA flow until you reach the Personal info double check page.
3. Disable the internet connection.
## Expected Result:
Only 1 bottom banner for offline status should be displayed.

## Actual Result:
2 bottom banners for offline status are displayed

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6378792_1707870839263!IMG_2949](https://github.com/Expensify/App/assets/38435837/ebd20e7a-4bcb-405b-ba08-86457b6adf25)

![Bug6378792_1707870839278!IMG_E2942](https://github.com/Expensify/App/assets/38435837/253ffb31-6c22-46b0-9dbd-b669ed71b8f1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e92a84369a21d16</li>
        <li>Upwork Job ID: 1757589397607944192</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 0</li>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by mountiny** [comment]
This is minor design bug not a blocker

**Comment by mountiny** [comment]
cc @shubham1206agra too

**Comment by godofoutcasts94** [comment]
Dibs or need to put a proposal ?

**Comment by mountiny** [comment]
@godofoutcasts94 all issues except the TS migration ones require proposals.

**Comment by mountiny** [comment]
@MrMuzyk @akinwale @shubham1206agra what do you think of proposal from @abzokhattab any reason there was the double ScrollView added? anything to look out for if we would remove one?

**Comment by godofoutcasts94** [comment]
> @godofoutcasts94 all issues except the TS migration ones require proposals.

Thanks for letting me know.

**Comment by akinwale** [comment]
> @MrMuzyk @akinwale @shubham1206agra what do you think of proposal from @abzokhattab any reason there was the double ScrollView added? anything to look out for if we would remove one?

@mountiny I am more inclined to go with using the `shouldShowOfflineIndicator` for the other `ScreenWrapper` as that wouldn't require changes to the existing styles or layout.

**Comment by mountiny** [comment]
@akinwale @abzokhattab Well is there any reason we need to use two screen wrappers on this page?

**Comment by MrMuzyk** [comment]
Double check spacing around submit button. If it works then I'm fine with such solution

**Comment by mountiny** [comment]
Yeah lets remove the second wrapper and fix any misalignments if that happens

**Comment by akinwale** [comment]
@abzokhattab Let's go with the solution to remove the second wrapper and check the layout and spacing according to https://github.com/Expensify/App/issues/36458#issuecomment-1946333226.

🎀👀🎀 C+ reviewed.

**Comment by mountiny** [comment]
sorry for the ping @techievivek

**Comment by mountiny** [comment]
Payment for @akinwale will be handled here https://github.com/Expensify/App/issues/22901#issuecomment-1977046291

**Comment by johncschuster** [comment]
Payment has been issued to @abzokhattab via Upwork
Coming from @mountiny's comment [here](https://github.com/Expensify/App/issues/36458#issuecomment-1977197290), it looks like payment for @akinwale will be handled in [#22901 (comment)](https://github.com/Expensify/App/issues/22901#issuecomment-1977046291)
