### ISSUE TITLE
[$500] [MEDIUM] Second and third numbers are filled with green after completing personal info

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36451]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Go to workspace settings from the bottom.
3. Click any workspace.
4. Click Bank account.
5. Click Connect manually.
6. Proceed until "Personal info" is complete.
7. Proceed to Business info.
## Expected Result:
3rd circle shouldn't be filled green
## Actual Result:
2nd and 3rd are filled green
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/ba3db225-47ca-4419-8c06-e61b0c8f5179

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134677950b2ff2b02</li>
        <li>Upwork Job ID: 1757557097541500928</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment]
The step it's skipping is biometric data. are you using any particular account information that bypasses this?

**Comment by mountiny** [comment]
I agree with @jeremy-croff this is skipping the identity verification probably because the account Applause used is  whitelisted

**Comment by MrMuzyk** [comment]
This is intended behaviour. This specific set of data skips onfido step. Try using regular values and you will see that onfido will show after personal info step
