### ISSUE TITLE
[$500] Bank account - Form is auto-submitted after disabling internet and killing app

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36456]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to Workspace > Bank account.
2. Select Connect online with Plaid and go through the add BA flow until you reach the SSN page of Personal info.
3. Disable internet connection.
4. Enter "33".
5. Kill the app.
6. Open the app again.
7. Enter the address info.
8. Verify that the incorrect info for SSN was submitted.
## Expected Result:
The form for SSN should not auto-submit and an error for incorrect data entered should appear.

## Actual Result:
The form for SSN is auto-submitted with the incorrect data.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ed83d9c6-214a-44f5-acf9-4911bb5487a0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01126719388570e4b1</li>
        <li>Upwork Job ID: 1757588631042637824</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
@shubham1206agra @MrMuzyk @barttom This one seems like something we should look at but very small edge case.

**Comment by MrMuzyk** [comment]
@mountiny Assign me and I'll have a look

**Comment by MrMuzyk** [comment]
This will happen more often than described. You could alternatively just fill in 2 digits, close the process and open it again (without disconnecting internet). All values are being saved in draft immediately after being entered. When process is opened again there is a check to see which values has been already filled in (its only checks against empty string) and opens next substep. However when you try to actually submit it (send it to BE) you do get an error explaining what's wrong.

<img width="1920" alt="image" src="https://github.com/Expensify/App/assets/23487612/7c114181-6070-44ee-9b7b-6a7a1b0c8c82">

Potential improvement would be to also validate existing draft values before navigating user to substep. I'm looking into it.

**Comment by mountiny** [comment]
@MrMuzyk thanks for clarifications.

Frankly I think its fine since we get the error from the backend. I think changing the way validation happens is a change which should be discussed more rather than a quick fix.

In that case I would be fine with closing this

**Comment by nkuoch** [comment]
I agree, let's close it and focus on real problems.

**Comment by mountiny** [comment]
Thanks
