### ISSUE TITLE
Profile - Tapping share code link directs to hmm not here page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap profile icon
3. Tap share code ---- copy URL
4. Navigate to LHN
5. Tap on a report
6. Paste the URL in compose box
7. Send the message
8. Tap on the URL link

## Expected Result:
Tapping share code link must direct to profile page

## Actual Result:
Tapping share code link directs to hmm not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3e1feaf9-5edc-48f2-bb1c-95bc7e2a1a3c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by rushatgabhane** [comment]
@lukemorawski would you be able to fix this, please

**Comment by lukemorawski** [comment]
@rushatgabhane sure will have a look

**Comment by mountiny** [comment]
This is fixed

**Comment by mallenexpensify** [comment]
Confirming that the root issue for this regression was addressed, no action needed here as BZ

**Comment by techievivek** [comment]
This was the Offending PR https://github.com/Expensify/App/pull/35841, and the original author only fixed the regression.

**Comment by techievivek** [comment]
Maybe we can add this regression test? @mallenexpensify 

1. Tap profile icon
2. Tap share code ---- copy URL
3. Navigate to LHN
4. Tap on a report
5. Paste the URL in compose box
6. Send the message
7. Tap on the URL link
8. Confirm you can see the copied user's profile
9. Verify that no errors appear in the JS console

**Comment by techievivek** [comment]
@rushatgabhane @cristipaval, this has originated from this PR https://github.com/Expensify/App/pull/35841

Regarding this step
> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Could we have done anything different/better that would have made us catch this bug during the review? Or should we do :nothing: here?

**Comment by mallenexpensify** [comment]
Thanks @techievivek , we're all good.  

TestRail GH created https://github.com/Expensify/Expensify/issues/371221
