### ISSUE TITLE
[$500] Bank account - Beneficial owner step is restarted after coming back online

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in and have created a workspace.

1. Go to Workspace > Bank account.
2. Initiate the add BA flow until you reach the Beneficial owner step.
3. Try to add an additional beneficial owner.
4. In the middle of the process (on the SSN, page for example) disable the internet connection.
5. Verify the bottom banner for offline status appears.
6. Enable the internet connection.
7. Wait until it loads.

## Expected Result:
The same page when the user was offline should be displayed when coming back online.

## Actual Result:
The beneficial owner step is restarted after coming back online.

note: Also, if the user enters the beneficial owner's data without saving it and goes back, when the page is reopened, the data entered previously is not saved.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/564b28a9-4249-405d-b886-c52602423cd6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112558f96658aedef</li>
        <li>Upwork Job ID: 1757590010053427200</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
Possibly related to https://github.com/Expensify/App/pull/34498, noted in slack here: https://expensify.slack.com/archives/C01GTK53T8Q/p1707899310534299?thread_ts=1707829954.739589&cid=C01GTK53T8Q

**Comment by mountiny** [comment]
@anmurali posted here https://expensify.slack.com/archives/C07J32337/p1707880864491329 I agree this is not bug, we save the details in backend once the step is saved so in this case it makes sense its missing after going back 

I think we can close this
