### ISSUE TITLE
[$500] Web - Bank Account -  Infinite loading on bank info page on connecting bank accounts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36479]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** not able to check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4311330&group_by=cases:section_id&group_order=asc&group_id=283225
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in with expensifail account
2. Click bottom right wrench settings icon
3. Select any WS
4. Select Bank account
5. Select Connect with Plaid
6. Go through the Plaid flow using either Chase, Regions or Wells Fargo bank
7. User redirected to ND site

## Expected Result:
No infinite loading display on bank info page. User able to connect BA

## Actual Result:
Infinite loading on bank info page on connecting bank accounts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f7ec00f9-e89a-4cbc-ac0b-1ebda02190a9

https://github.com/Expensify/App/assets/93399543/2fe4c068-e2a2-42e0-a72d-d9fe88e887f9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f35a009ac3da6d6</li>
        <li>Upwork Job ID: 1757770983720157184</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #wave6-collect-submitters
CC @greg-schroeder

**Comment by Beamanator** [comment]
Noted in slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1707919815149159?thread_ts=1707829954.739589&cid=C01GTK53T8Q

**Comment by mountiny** [comment]
cc @shubham1206agra @akinwale @MrMuzyk

**Comment by mountiny** [comment]
@Swor71 is working on this one

**Comment by Swor71** [comment]
hey, I'm Marcin from Callstack - expert contributor group - I'd like to work on this issue

sorry for late comment on this one but yes, I am looking into this at the moment

**Comment by mountiny** [comment]
Might be related to backend PR potentially https://github.com/Expensify/Web-Expensify/pull/40691

Stacktrace from Marcin:

![image](https://github.com/Expensify/App/assets/36083550/065e1772-58b6-40d6-8a4a-ca158df50eda)

**Comment by Swor71** [comment]
this is the onyx update received from the server:
<img width="670" alt="image" src="https://github.com/Expensify/App/assets/32240132/fcca7e5a-6504-46de-861b-67e54b539796">

**Comment by mountiny** [comment]
Ok yes the onyx data is not correct format
<img width="664" alt="image" src="https://github.com/Expensify/App/assets/36083550/0f762262-6138-4282-b631-5297d7f22d60">

**Comment by mountiny** [comment]
Using production API 
<img width="950" alt="image" src="https://github.com/Expensify/App/assets/36083550/b797ac87-6e1f-4a5f-abbb-84868f5ba2f7">

This is a backednd blocker

**Comment by mountiny** [comment]
Ok yes the onyx data is not correct format
<img width="664" alt="image" src="https://github.com/Expensify/App/assets/36083550/0f762262-6138-4282-b631-5297d7f22d60">

**Comment by mountiny** [comment]
Created a backend fix for this https://github.com/Expensify/Web-Expensify/pull/40897
