### ISSUE TITLE
[$500] Workspace - A thread created offline does not disappear after going online in an archived

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4314321
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preparation:
Create a workspace and send some messages to the #announce room

Steps:
1. Open https://staging.new.expensify.com/
2. Navigate to the #announce room
3. Disable the internet connection in the main testing device
4. Create a thread to any message in the room
5. Send a message to the created thread
6. In the secondary device, navigate to the workspace and delete it.
7. Turn on the Internet connection in the main testing device

## Expected Result:
The thread should disappear when it goes online if it was created offline and the room was deleted at that point.

## Actual Result:
A thread created offline does not disappear after going online in an archived room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e9ba64ae-b251-44bf-a4f2-f51a9f2fb6e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related #wave6-collect-submitters
CC @greg-schroeder

**Comment by joekaufmanexpensify** [comment]
Hmm, I'm not convinced this something a real user would ever experience. It feels pretty unlikely to me that someone would be offline in a workspace creating threads at the exact moment that on a different device a workspace admin is deleting the workspace. 

If someone is deleting a workspace that is actively being used, that is likely a mistake. Deleting a workspace is a rare product action, and in most cases when it's used, the workspace is likely no longer in use.

**Comment by joekaufmanexpensify** [comment]
I think we should put this one in the category of wait and see if a real customer ever experiences it before doing anything. Closing for now, but LMK if anyone disagrees.
