### ISSUE TITLE
[$500] mweb -Chat - Copy url to clipboard is shown in more space on long pressing URL with keypad open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4312433
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to mweb & app
2. Tap on a report
3. Send a URL Eg: go.com from compose
4. Long press the URL when keypad is open

## Expected Result:
Like in Android, Copy url to clipboard must be shown without more space when user long press the URL message when keypad is open

## Actual Result:
Copy url to clipboard is shown in more space initially when user long press the URL message when keypad is open in mweb but more space not shown in Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1b644fef-c8f7-48ab-827c-ffa20a3eaa9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01936c68301fac539a</li>
        <li>Upwork Job ID: 1757773090824306688</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by stephanieelliott** [comment]
I think this pretty minor and not worth fixing, gonna close for #focus.
