### ISSUE TITLE
Chat - Emojis sent offline are not rendered in chat history

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36483]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4314401
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Go offline
4. Send message with emoji

## Expected Result:
Emojis sent offline should appear greyed out in chat history to indicate that they are pending.

## Actual Result:
Emojis sent offline are not displayed at all in chat history until user goes online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5bb42b4b-21dc-4d3f-9ea8-208ad30a37da

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by situchan** [comment]
Offending PR is being reverted.
cc: @amyevans

**Comment by marcochavezf** [comment]
Thanks, I will remove the deploy blocker label since the PR to revert the change is in review

**Comment by amyevans** [comment]
Retested on staging after the CP and it looks good! Closing.
