### ISSUE TITLE
[$500]  Bank account - Selected field is not auto-focused when redirected from the confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36499]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to workspace settings from the bottom
3. Go to any workspace > Bank acccount
4. Tap Connect manually
5. Enter both bank account numbers and proceed to confirmation page
6. Tap on any item

## Expected Result:
When redirecting to the selected item, the field will be auto focused

## Actual Result:
When redirecting to the selected item, the field is not auto focused. User has to tap on the same item again in order to bring up the keyboard to edit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7ddf8633-fa5a-41a2-bfd0-9dee7a109588

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c1a4853672c1766</li>
        <li>Upwork Job ID: 1757781225140977664</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by mountiny** [comment]
Actually I dont think this is a bug we need to handle, more like a new feature
