### ISSUE TITLE
[HOLD for payment 2024-03-04] [$250] [MEDIUM] Bank account - "PO boxes and mail drop addresses are not allowed" appears twice in Address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36500]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings from the bottom
3. Go to any workspace > Bank account
4. Click Connect manually
5. Proceed until Business info - Company's address

## Expected Result:
"PO boxes and mail drop addresses are not allowed" will only appear once

## Actual Result:
"PO boxes and mail drop addresses are not allowed" appears twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6379335_1707914862966!bandicam_2024-02-14_13-18-50-570 (1)](https://github.com/Expensify/App/assets/78819774/75a06788-781b-412c-bff6-45bccda9772b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b8183bbc1eecc39</li>
        <li>Upwork Job ID: 1757780866863529984</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Contributor | 0</li>
<li>codinggeek2023 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by mountiny** [comment]
@shubham1206agra @akinwale @MrMuzyk @Swor71 minor design issue

**Comment by akinwale** [comment]
Based on the new BA flow design doc, the message at the top of the page is a part of the design, so we can remove the hint instead. In this case, @codinggeek2023's suggested approach in their [proposal](https://github.com/Expensify/App/issues/36500#issuecomment-1944076754) is the way to go.

🎀👀🎀 C+ reviewed.

**Comment by mountiny** [comment]
I am good to handle this Robert, sorry for the melvin ping

**Comment by mountiny** [comment]
Summary: $250 to @codinggeek2023 please

**Comment by joekaufmanexpensify** [comment]
@mountiny I assume @akinwale is due payment here too? I see they were automatically sent an offer for this job too.

**Comment by joekaufmanexpensify** [comment]
Ah, got it. Thanks for confirming!

**Comment by joekaufmanexpensify** [comment]
@codinggeek2023 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
