### ISSUE TITLE
Android - Bank account - Spinner does not appear instantly when reopening Connect with Plaid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to workspace settings from the bottom
3. Go to any workspace > Bank account
4. Tap Connect online with Plaid
5. Close the Plaid modal
6. Tap Connect online with Plaid again

## Expected Result:
The spinner will appear immediately when tapping on Connect online with Plaid again

## Actual Result:
It takes a while for spinner to appear when tapping on Connect online with Plaid again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/44ad1faa-76f0-4f1c-9d2b-3949326d7c64

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by Julesssss** [comment]
Don't worry though, I can handle making this external 👍

**Comment by Julesssss** [comment]
Actually I think we can just close this. We're transitioning to Plaids library flow and it's working pretty well for me on `1.4.41-3`

**Comment by Julesssss** [comment]
WTF are the bots doing, it is closed

**Comment by mountiny** [comment]
haha all fair, thanks!

**Comment by Julesssss** [comment]
Here's what I see: 


https://github.com/Expensify/App/assets/10736861/45fc1e36-9e11-4918-aece-f37710623277

**Comment by mountiny** [comment]
Ype I think that is all good!
