### ISSUE TITLE
[HOLD for payment 2024-02-26] IOU - Merchant error remains when Admin pay the request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4312656
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. As Employee start the request money flow &gt; "Scan" receipt from Workspace chat
2. Upload a blurry receipt
3. Complete the money request flow
4. Wait for request to fail
5. Manually edit the amount field
6. Note that Merchant have red dot on both sides (Employee and Admin)
6. As Admin pay the request
7. As Admin take a note of Merchant field

## Expected Result:
Red dot should disappear from Merchant field since request is payed

## Actual Result:
Merchant error remains on Admin's side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4849c870-e923-4b1d-88fa-79ed24fc8cb5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related  #wave6-collect-submitters
CC @greg-schroeder

**Comment by AndrewGable** [comment]
Going to look and see if anything changed with violations recently cc @cead22

**Comment by AndrewGable** [comment]
Wondering if this PR introduced this regression: https://github.com/Expensify/App/pull/34303

**Comment by AndrewGable** [comment]
@trevor-coleman confirmed he thinks this is from the PR ([internal Slack](https://expensify.slack.com/archives/C04KQL2HSQ1/p1707952252802539?thread_ts=1707950294.327039&cid=C04KQL2HSQ1)), discussing next steps

**Comment by AndrewGable** [comment]
@allroundexperts is reviewing as C+, so assigning them too

**Comment by mallenexpensify** [comment]
Contributor+: @allroundexperts owed $500 via NewDot.  

@allroundexperts , do we need to create or update a regression test for this? It looks like this issue was a regression so maybe it was caught by QA running an existing test?

**Comment by allroundexperts** [comment]
@mallenexpensify I can't see this test case specifically listed in https://github.com/Expensify/App/pull/34303. Can you check if this exists in test rail? If not, we can create one. The steps in the OP should suffice.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts based on summary above.

**Comment by mallenexpensify** [comment]
Thanks @allroundexperts , I created one and mentioned that I wasn't sure if it was needed, so QA will check
https://github.com/Expensify/Expensify/issues/374976
