### ISSUE TITLE
[$500]  Web - Settings - The language stays on Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36516]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35509
## Action Performed:
1. Web/Chrome: Log in (The language should be English)
2. mWeb/Safari: Change the language to Spanish before logging in
3. mWeb/Safari: Log in with the same account
4. mWeb/Safari: Change the language to English
5. mWeb/Safari: Change the language to Spanish again

## Expected Result:
It should be changing to Spanish on all devices if you switch to it on the login screen and proceed to log in with a secondary device

## Actual Result:
The language only switches to Spanish if you switch to English and back to Spanish

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/60bcfae7-dc95-40ed-a52e-1863498a9734

https://github.com/Expensify/App/assets/78819774/d763e8e6-99d7-4206-a0fe-58877ea92c96

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01074547adb1be45f1</li>
        <li>Upwork Job ID: 1757904101628276736</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by eVoloshchak** [comment]
@twisterdotcom, i agree with @barros001's comment (https://github.com/Expensify/App/issues/36516#issuecomment-1944415543), this does look like a back-end issue, which makes this issue Internal

**Comment by twisterdotcom** [comment]
Yeah, we have the Internal label. We'll get around to this when we can. Going to make it `Monthly` again.

**Comment by twisterdotcom** [comment]
This is Monthly Melv.

**Comment by twisterdotcom** [comment]
Still `Monthly`

**Comment by twisterdotcom** [comment]
VSB stuff is very low on the agenda. Marking this as not a priority and closing.
