### ISSUE TITLE
[HOLD for payment 2024-03-06] [$500] Sounds for receiving message and for being tagged somewhere

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707866137747939

## Action Performed:
1. Send a message mentioning some one else

## Expected Result:
Should not receive sound notification. This should only happen when you are tagged (directly or (at)here)

## Actual Result:
you still receive the sound effect as if you would be mentioned

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/990bf9db-d37e-4ac6-9317-6a0a63b1ec68

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158c6c5402e5ea2cd</li>
        <li>Upwork Job ID: 1757878333789503488</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Thanks! Again cc @kirillzyusko and @hannojg for visibility

**Comment by kirillzyusko** [comment]
@rayane-djouah yes, i think it's a correct solution that you are suggesting 👍

**Comment by stephanieelliott** [comment]
Hey @cubuspl42 proposal for you to review here when you get a sec!

**Comment by cubuspl42** [comment]
🎀 👀 🎀

**Comment by cubuspl42** [comment]
@flodnv Would it be possible to add more metadata to this structure returned from the backend? I know that in another place...

https://github.com/Expensify/App/blob/28bcc8555c81b1c306261d19a77914e0170361e1/src/types/onyx/OriginalMessage.ts#L174

...we have access to the account IDs of the mentions.

**Comment by flodnv** [comment]
Probably, but my plate is full, so either @stephanieelliott or @shawnborton will have to find someone to work on this (it's not clear to me which part of the roadmap this is on)

**Comment by shawnborton** [comment]
cc @Julesssss - we talked about putting this on the VSB project.

**Comment by Julesssss** [comment]
> cc @Julesssss - we talked about putting this on the VSB project.

Ah, I was using[ this issue](https://github.com/Expensify/App/issues/36579) for the native mobile audio bug

**Comment by shawnborton** [comment]
Happy to do whatever you think is best. What do you think about consolidating these issues into just one follow up issue for the couple of bugs that have popped up?

**Comment by shawnborton** [comment]
Sounds like we don't want to consolidate all sound issues. But @kirillzyusko curious if you are planning to handle this as a follow up?

**Comment by Julesssss** [comment]
> What do you think about consolidating these issues into just one follow up issue for the couple of bugs that have popped up?

I said this in Slack, but just to clarify: We'll keep the mobile bugs separate as testing mobile complicates the testing of other issues.

**Comment by Julesssss** [comment]
Thanks, but we're going to solve this internally using a method that changes the implementation.

**Comment by Julesssss** [comment]
Thanks @rayane-djouah, lets go with your solution as we don't have time for any backend changes here.

**Comment by kirillzyusko** [comment]
> Sounds like we don't want to consolidate all sound issues

I wouldn't like to fix all sounds-related issues in a single MR, but I'm not agains the idea of creation kind of `main` issue for sounds, were we will have a references to all bugs (but separate bugs will be tracked separately). I think such approach will give a better understanding of what happens/what is the current status/simplify management.

@Julesssss @shawnborton What do you think? 👀

**Comment by shawnborton** [comment]
I'd be down with that, what do you think @Julesssss ?

**Comment by Julesssss** [comment]
>  wouldn't like to fix all sounds-related issues in a single MR, but I'm not agains the idea of creation kind of main issue for sounds, were we will have a references to all bugs (but separate bugs will be tracked separately)

Yeah, that sounds ideal 👍 

I created [this issue](https://github.com/Expensify/App/issues/36846), please add any issues/bugs you are aware of. Also, @kirillzyusko could please comment on the issue so I can assign you too. thanks

**Comment by stephanieelliott** [comment]
Fix for this issue is on staging, ended up testing it and it's working great 👍

**Comment by stephanieelliott** [comment]
This was deployed to prod on 2/28, seems the automation didn't work so am updating manually

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @rayane-djouah $500 PAID via Upwork 
 - Contributor+: @cubuspl42 $500 PAID via Upwork 
 
 Upwork job is here: https://www.upwork.com/jobs/~0158c6c5402e5ea2cd
