### ISSUE TITLE
[$500] [HOLD for payment 2024-02-26] Cancel payment - Red dot persists in LHN after dismissing payment cancellation error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36599]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and member are in the same free workspace.
- Admin and member have bank account set up.
1. [Member] Go to workspace chat.
2. [Member] Create a manual request.
3. [Admin] Pay the request with Expensify.
4. [Admin] Go to expense report > 3-dot menu > Cancel payment.
5. [Admin] Cancel the payment.
6. [Admin] Dismiss cancellation error message.

## Expected Result:
The red dot in LHN will disappear after dismissing the error.

## Actual Result:
The red dot still persists in LHN after dismissing the error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7ccecb50-f96f-4728-a185-0d86176faed8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fff48c8d19d46bc2</li>
        <li>Upwork Job ID: 1762613556955721728</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related #wave5-free-submitters
CC @dylanexpensify

**Comment by tgolen** [comment]
@Gonals Do you think this relates to https://github.com/Expensify/App/pull/34719?

**Comment by tgolen** [comment]
Alberto confirmed it was caused from that PR. He will be able to fix this tomorrow morning.

**Comment by Gonals** [comment]
@kbecciv, do you know why you are getting the error in the first place?

**Comment by Beamanator** [comment]
Should have been unblocked by https://github.com/Expensify/App/pull/36631

**Comment by Beamanator** [comment]
Adding bugzero team member to help with payment 🙏

**Comment by alexpensify** [comment]
I'll be working on the payment process later today

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - N/A 
-  Contributor+ that helped on the issue and/or PR - @hoangzinh $500 

Upwork Job: https://www.upwork.com/jobs/~01fff48c8d19d46bc2

Extra Notes regarding payment:

@hoangzinh - this is ready for you to accept. Thanks!

**Comment by alexpensify** [comment]
Done, the payment has been completed in Upwork!
