### ISSUE TITLE
Received mobile notification of chat; chat does not appear on web at all

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#36600]
Today I got a notification on my phone of a message from @mountiny. When I looked on web, the message was not there and has not shown up.

I am using Staging web `v1.4.42-1` and ios `v1.4.42.1`.

When I look at the list of chats on mobile, there are actually two unread chats, while web shows no unread chats.

The two reportIDs that are unread on mobile are: `74453077` (chat with Vit) and `895204580289076` (chat with dclarktsp@gmail.com)

<details>
<summary>screenshots</summary>

![IMG_8044](https://github.com/Expensify/App/assets/1228807/7cd18adc-f7ba-4a3c-a21c-a0ad7195026b)
![image](https://github.com/Expensify/App/assets/1228807/881d3d9e-6d15-40d1-8940-96524f6f3b84)
![image](https://github.com/Expensify/App/assets/1228807/82603eca-f112-4dcc-8739-e747ecdb6ca0)

</details>

cc @iwiznia @danieldoglas

**Comment by tgolen** [comment]
After accessing one of these reports on web, I also had a new unread message show up in the LHN on web for another chat. It was a message that was sent two days ago from Bondy. I know I had read this message at the time, so I don't know why it appeared all of a sudden.

![image](https://github.com/Expensify/App/assets/1228807/74aad79b-0924-44dc-9d20-0915c0f26270)

**Comment by zanyrenney** [comment]
Thanks for the detailed explanation @tgolen - let me try to reproduce....

**Comment by zanyrenney** [comment]
I have not been able to reproduce this. Asking in #newdot performance.

**Comment by zanyrenney** [comment]
asking here --https://expensify.slack.com/archives/C05LX9D6E07/p1708355986461849

**Comment by zanyrenney** [comment]
discussed keeping an eye on this behaviour but closing for now.
