### ISSUE TITLE
[Wave8] [Simplified Collect] Remove the free workspace menu items from collect workspace settings in NewDot 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#36606]
👋 We've started working on the PRs (like [here](https://github.com/Expensify/App/pull/36345#issuecomment-1946382917) and [here](https://github.com/Expensify/App/pull/36324#issue-2130028137)) to implement the new workspace settings for `collect`. I noticed that we're showing the old `free` menu items in the LHN of the workspace settings along with the new menu items being added to `collect` workspaces only. 

<img width="1176" alt="image" src="https://github.com/Expensify/App/assets/16232057/2db9c4e8-924c-48a6-b18e-308481b847ee">

Let's remove these menu items from `collect` workspace settings only (leave `free` alone):

`Cards`
`Reimbursements`
`Bills`
`Invoices`
`Travel`
`Bank account`

Immediately then, we'll be left with: 

`Profile`
`Members`

... and as we progress through implementation of release1 of wave8 in the coming weeks we'll see:

`Profile`
`Members`
`Categories`
`Workflows`

![image](https://github.com/Expensify/App/assets/16232057/1ea5efdf-3660-459e-b8f2-e223833a9129)

... ahead of then adding the rest and being conditional on being enabled in `More features`. Thanks! CC: @mountiny @luacmartins @lakchote @JmillsExpensify

**Comment by mountiny** [comment]
cc @ArekChr this is kinda related to your PR too https://github.com/Expensify/App/pull/36324

Would you be interested in handling this as its good to know the context and how it will fit the other pages? cc @rushatgabhane might be interested too

**Comment by ArekChr** [comment]
Sure @mountiny, I'm interested and happy to handle it

**Comment by mountiny** [comment]
Thanks!

**Comment by rushatgabhane** [comment]
@mountiny yes please! happy to help

**Comment by trjExpensify** [comment]
Perfect, will be good for us to clear this hurdle for sure.

**Comment by lakchote** [comment]
The logic to remove the free workspace menu items is already done in my [PR](https://github.com/Expensify/App/pull/36345).

You can see how I've enabled Workflows only for collect workspaces [here](https://github.com/Expensify/App/pull/36345/commits/c594e299cd664dee69ed9e17cb1575746eb3da0f).

**Comment by trjExpensify** [comment]
Oh cool, so @ArekChr's PR is aligning with that for workflows yeah?

**Comment by lakchote** [comment]
> @lakchote confirming we're done here and close this out, right?

Yes!

Closing the issue.

**Comment by rushatgabhane** [comment]
Hi @trjExpensify, could you please attach payment summary for this issue. Thanks 🙇

**Comment by trjExpensify** [comment]
Ah, my bad. 😅 I didn't think there was an "independent" PR for this issue in the end. I see it now: https://github.com/Expensify/App/pull/36672

Payment summary as follows: 

$500 to @rushatgabhane for the C+ review. 

Feel free to go ahead and request on NewDot :)

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane based on summary.
