### ISSUE TITLE
Unable to return to home page when logging in via link with target path

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36603]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36390

## Action Performed:
1. Launch New Expensify app.
2. Log in.
3. Copy the magic link.
4. Change it to staging link and add ?exitTo=/settings/preferences at the end of the link.
5. Paste it on external app.
6. Tap on the modified magic link with target path.
7. After login, return to previous page via device back navigation and also app back button.

## Expected Result:
App returns to Home when returning via back button.

## Actual Result:
The app closes when using device back navigation, and the app back button is not responsive.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6763acbe-5bc2-4fc2-8bc5-f40b7a58efc7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by AndrewGable** [comment]
@allroundexperts @techievivek - Do you think this is related to the PR mentioned here https://github.com/Expensify/App/pull/36390?

**Comment by AndrewGable** [comment]
I don't think this needs to block deploy, but we should look into it

**Comment by AndrewGable** [comment]
Also cc PR author @rayane-djouah for [the same question](https://github.com/Expensify/App/issues/36603#issuecomment-1952920057).

**Comment by techievivek** [comment]
@rayane-djouah Will you be able to push a PR today? As we mentioned this is part of wave9-collect-signups so we are looking to get this fixed ASAP. Thanks.

**Comment by techievivek** [comment]
This is completed and doesn't require any payment since this is an improvement of another feature where the contributor was compensated.
