### ISSUE TITLE
Loading header appears when the sender deletes message and recipient writes in the thread 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36614]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707847433641419

## Action Performed:
1. Open a chat with B as user A
2. User A sends a message
3. User B replies in the thread
4. User A deletes at the same time
## Expected Result:
User B should see "deleted message" in the header when in the thread

## Actual Result:
Skeleton is loading for ever and also User A is showing as "Hidden" in the LHN

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![screenshot_2024-02-12_at_5 49 31___pm__1__480](https://github.com/Expensify/App/assets/38435837/3c7dbc44-b60e-41b7-9782-29cf2a8112ff)
![screenshot_2024-02-12_at_5 48 21___pm_720](https://github.com/Expensify/App/assets/38435837/38b643cf-c5f1-4193-b3cb-4719a8d3eb1d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
I also can't repro this. I stayed on the page and it updated to `[Deleted message]` in the header and the parent comment previewed: 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/724163f1-e6d3-4a31-8d33-e6a7d5eac64c">

**Comment by trjExpensify** [comment]
Discussing [in thread](https://expensify.slack.com/archives/C049HHMV9SM/p1708081291609339?thread_ts=1707847433.641419&cid=C049HHMV9SM).

**Comment by MonilBhavsar** [comment]
Self assigning as I am working on very similar issue https://github.com/Expensify/App/issues/22186 and came across this bug while fixing the former. I had a brief look and will handle this

https://expensify.slack.com/archives/C049HHMV9SM/p1708085284757179?thread_ts=1707847433.641419&cid=C049HHMV9SM

**Comment by MonilBhavsar** [comment]
The error comes from this logic https://github.com/Expensify/App/blob/8907eef1b850dcf0810770a7f85266a2e7d201fe/src/libs/ReportUtils.ts#L2518-L2521

For a parent message deleted in #admins or user created room, we enter the condition and return `title` as empty string
and return early and do not reach the return statement below that returns `[Delete Message]`

**Comment by trjExpensify** [comment]
Nice, so @MonilBhavsar.. confirming this hit prod yesterday and we don't have anyone to pay out for the review, so we can go ahead and close this?

**Comment by MonilBhavsar** [comment]
Yes! Let's close this
