### ISSUE TITLE
[VSB] [$500] Room - Inviting a user to the room does not remove other whisper messages

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36629]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** shussain@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34560
## Action Performed:
1. Create a room
2. Mention a user in the chat
3. Again mention same user in chat
4. Click on "Invite them"
5. Notice other whisper message does not removed

## Expected Result:
Inviting a user to the room other same whisper messages should be removed

## Actual Result:
Inviting a user to the room does not remove other whisper messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7b62d0fc-318c-4cf6-8929-4a97caafa576

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c530387770aef42</li>
        <li>Upwork Job ID: 1758212482614226944</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by brunovjk** [comment]
I believe this problem would be better solved on the backend side. A Pusher or something.

**Comment by brunovjk** [comment]
I believe this problem would be better solved on the backend side.

**Comment by brunovjk** [comment]
I believe this issure would be better solved on the backend side.

**Comment by strepanier03** [comment]
All good Melvin, active discussion ongoing.

**Comment by strepanier03** [comment]
All good Melvin, not overdue.

**Comment by strepanier03** [comment]
All good Melvin.

**Comment by jasperhuangg** [comment]
At worst case we would have to query through all the report actions and search through their targetAccountIDs, but at most there would only be one other report action.

Perhaps this would be better fixed in the back-end. I can see things getting too complicated in the back-end.

I can look into this.

**Comment by jasperhuangg** [comment]
I think this qualifies for #vip-vsb since it involves fixing a flaw in the design of actionable mention whispers, a central part of chat.

**Comment by jasperhuangg** [comment]
I'm assigned and will look into this once I've cleared off my plate a bit

**Comment by strepanier03** [comment]
Thanks @jasperhuangg!

**Comment by jasperhuangg** [comment]
Looking into this this week

**Comment by jasperhuangg** [comment]
Not overdue!

**Comment by jasperhuangg** [comment]
Made some good progress on a PR with this today, looking to get it ready for review before EOW

**Comment by jasperhuangg** [comment]
More progress on tests, I think I should be able to get it out for review today

**Comment by jasperhuangg** [comment]
Ran into some hiccups with the tests, looking into them, but might have to continue investigation tomorrow since I've already worked on this a good amount today.

**Comment by jasperhuangg** [comment]
Still looking into the tests for this–they're a bit complicated since there's a good amount of code to be added for this.

**Comment by jasperhuangg** [comment]
PR is ready for review!

**Comment by jasperhuangg** [comment]
Still under review, not overdue

**Comment by jasperhuangg** [comment]
The Auth PR was deployed, we can close this out!
