### ISSUE TITLE
[Tracking] Video Player Launch

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#36625]
Tracking issue for the Video Player launch bugs and follow-up tasks

### Critical
- https://github.com/Expensify/Expensify/issues/370787 - @francoisl (internal)
- https://github.com/Expensify/Expensify/issues/371232 - @francoisl (internal)
- https://github.com/Expensify/Expensify/issues/370796 - @francoisl  (internal)

## Known issues for polish
- https://github.com/Expensify/App/issues/36627 - @francoisl (internal)
    - Editing the comment causes the video player to no longer render. We should hide the edit option, similar to what we do with images at the moment

### High
- Add support for auto-playing videos

### Low
- Migrate new JS files to TS - see issues linked in [this comment](https://github.com/Expensify/App/issues/36625#issuecomment-1949075806)
We agreed to merge the PR without migrating all new files to TS, let's migrate them when possible. New JS files:
    - `src/components/Attachments/AttachmentView/AttachmentViewVideo/index.js`
    - `src/components/VideoPlayer/BaseVideoPlayer.js`
    - `src/components/VideoPlayer/IconButton.js`
    - `src/components/VideoPlayer/VideoPlayerControls/ProgressBar/index.js`
    - `src/components/VideoPlayer/VideoPlayerControls/VolumeButton/index.js`
    - `src/components/VideoPlayer/VideoPlayerControls/index.js`
    - `src/components/VideoPlayer/index.js`
    - `src/components/VideoPlayer/index.native.js`
    - `src/components/VideoPlayer/propTypes.js`
    - `src/components/VideoPlayerContexts/PlaybackContext.js`
    - `src/components/VideoPlayerContexts/VideoPopoverMenuContext.js`
    - `src/components/VideoPlayerContexts/VolumeContext.js`
    - `src/components/VideoPlayerPreview/VideoPlayerThumbnail.js`
    - `src/components/VideoPlayerPreview/index.js`
    - `src/components/VideoPopoverMenu/index.js`
- Add support for Picture-in-Picture (PiP)

----

cc @Skalakid @kowczarz

**Comment by SzymczakJ** [comment]
@francoisl can we create task for TS migration? VideoPlayer is blocking my [migration task](https://github.com/Expensify/App/issues/25152). I could also start to work on this right away to merge both tasks ASAP.

**Comment by hayata-suenaga** [comment]
ah sorry I'm creating TS migration issues now 🙇

**Comment by hayata-suenaga** [comment]
Created TS migration issues for JS files

- https://github.com/Expensify/App/issues/36722
- https://github.com/Expensify/App/issues/36723
- https://github.com/Expensify/App/issues/36724
- https://github.com/Expensify/App/issues/36725

cc: @francoisl

**Comment by stephanieelliott** [comment]
Noting this video player bug since it doesn't look like it's being tracked on this issue: https://github.com/Expensify/App/issues/36832

Not sure if you are still tracking followup bugs or of those should be distributed out, so I've added it to #vip-vsb!

**Comment by francoisl** [comment]
Going to close this, all the required TS migrations and follow-up tasks are already tracked in issues.
