### ISSUE TITLE
Chat - Pressing the Enter key moves to the next line instead of saving the workspace description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36635]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Go to workspace settings > Profile > Workspace Description
2, In the workspace description, press the Enter key. Notice that instead of saving, it moves to the next line. This behavior differs from Assign Tasks and Request Money descriptions, where pressing Shift + Enter moves to the next line

## Expected Result:
Pressing the Enter key should save the workspace description instead of moving to the next line

## Actual Result:
Pressing the Enter key moves to the next line instead of saving the workspace description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ff02e48e-273d-4fb4-b26c-2368a121c53b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Pujan92** [comment]
@narefyev91 seems while resolving the conflict you missed to consider `shouldSubmitForm`  here https://github.com/Expensify/App/commit/1b943016afab5186cad71ebf7a72f8cf37270b84#diff-82bc41255592bcaed0e50974a86358eba853bd731a1d35873cbd30a3a0e13384L90

**Comment by narefyev91** [comment]
@Pujan92 hey! not really - bug was introduced with this PR https://github.com/Expensify/App/pull/36058/files

**Comment by jjcoffee** [comment]
Thanks for flagging @narefyev91! I'm not sure if I agree with the expected result here. Especially if opening the same modal by tapping on the description on a workspace chat's header, it would be pretty bad UX if pressing enter saves and closes the modal entirely. 

The reason Assign Task and money request descriptions have a different behaviour is because pressing enter dismisses a "sub" modal that returns you to a confirmation/overview screen, rather than closing the modal altogether.

**Comment by bfitzexpensify** [comment]
Agreed @jjcoffee. I think the way this behaves right now is fine, and we don't need to change this. Going to close this out.
