### ISSUE TITLE
[HOLD #140] [$500] Chat - Altering 1st code block removes markdown applied for quote & 2nd code block

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4319035
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Type # 567
4. In next line, type ```|||``` ```|||```
5. Now from 1st pair- remove 5th block tick
6. Note, removing 5th block tick in 1st pair, markdown applied for 2nd pair & for quote message also removed

## Expected Result:
Removing 5th block tick in 1st pair, markdown applied for 2nd pair & for quote message must not be removed

## Actual Result:
A quote message paired with 2 code block message is send. Altering 1st code block changes
quote and 2nd code block message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f310562b-e1a3-465b-b9ef-f91961026763

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194d1ba71ece129a2</li>
        <li>Upwork Job ID: 1758228337378869248</li>
        <li>Last Price Increase: 2024-02-15</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Christinadobrzyn** [comment]
I can reproduce this but I don't think this is a priority unless there is some markdown reason for us to work on this now. 

@hoangzinh what do you think? Should this be prioritised at this time?

**Comment by Christinadobrzyn** [comment]
Okay it sounds like we should hold for https://github.com/Expensify/react-native-live-markdown/pull/140 and if that doesn't resolve it we'll add to https://github.com/Expensify/App/issues/36071 and add another hold.

**Comment by Christinadobrzyn** [comment]
Hold for https://github.com/Expensify/react-native-live-markdown/pull/140

**Comment by Christinadobrzyn** [comment]
This appears to be fixed with https://github.com/Expensify/react-native-live-markdown/pull/140

https://github.com/Expensify/App/assets/51066321/ef4b7584-74ed-4709-bfd0-ff10fa3d8fb0


Closing!
