### ISSUE TITLE
[$500] Android - Room-From display name page, tapping back button directs to LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch
2. Tap fab--start chat
3. Tap room
4. Enter all required details and select visibility as "public" & create a room
5. Note a whisper message is shown with a linked text "here"
6. Tap "here"
7. Tap app back button in display name, profile & account settings page

## Expected Result:
Create a public room and from whisper message, tap "here".Then tapping back button must direct to room page & not LHN

## Actual Result:
Create a public room and from whisper message, tap "here".Then tapping back button directs to LHN and not room page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4dac665a-de7c-4f04-acce-ad97ec1b2fea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f456e31308cefab</li>
        <li>Upwork Job ID: 1758253936428650496</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android - Room-From display name page, tapping back button directs to LHN

### What is the root cause of that problem?

Both `RoomDescriptionPage` and  `DisplayNamePage` don't consider the previous route when navigating away from the page.

https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/pages/RoomDescriptionPage.tsx#L74

Hence, the navigation returns to the specified route.

### What changes do you think we should make to solve the problem?


Introduce a `backTo` parameter in the `route` and capture it in `RoomDescriptionPage` and  `DisplayNamePage`.

If `backTo` is present, we could use it as the `backTo` argument in the `Navigation.goBack` function.

**Comment by situchan** [comment]
Interested in reviewing this as C+

**Comment by twisterdotcom** [comment]
Oh, I thought that would do it. Whatever, adding you @situchan. Please review the proposals soon.

**Comment by twisterdotcom** [comment]
Yes Melvin, that is what I was trying to avoid.

**Comment by twisterdotcom** [comment]
Huh, looking again at this, I wonder... whether this is actually expected. If you've chosen to navigate to Display Name, would we not just take you back through the hierarchy when returning to the LHN?

**Comment by twisterdotcom** [comment]
Checked from @mallenexpensify's message. The behaviour is the same on mobile and web. I'm going to close as this is a fine normal flow.
