### ISSUE TITLE
chat-In edit comment, there is no spacing between emojis added via keypad

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36641]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
. Launch app
2. Tap on a report
3. Send a message
4.Long press the sent message and select edit comment
5.Remove the text
6.Using keypad, add few emojis & send the message
7.Note, there is no spacing between emojis
8.Using keypad, select few emojis and send the message
9.Note there is spacing between emojis

## Expected Result:
In edit comment, there must be spacing between emojis added via keypad.

## Actual Result:
In edit comment, there is no spacing between emojis added via keypad.

Using keypad, select emojis and send the message directly is showing spacing but sending using edit comment is not showing spacing.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/bba1366a-6194-4cbc-a98c-f5c07b48e5a4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this might be related to #vip-vsb
cc @quinthar

**Comment by jacobkim9881** [comment]
Putting emojis on keyboard gives no spacing on other apps normally.

**Comment by alexpensify** [comment]
Still on my testing list

**Comment by alexpensify** [comment]
I didn't get a chance to test over the weekend, but it's on my list for tomorrow.

**Comment by alexpensify** [comment]
I'm going to close-- I don't think this is a bug.
