### ISSUE TITLE
[MEDIUM] Company Card expense shows as Cash in NewDot report. 

### ISSUE THREAD

**Issue by kadiealexander** [Expensify/App#36640]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-12
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** Customer
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 n/a
**Expensify/Expensify Issue URL:** n/a
**Issue reported by:** @kadiealexander / @SofiedeVreese 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1707958713660189

## Action Performed:
Use a company card/Expensify card to make an expense on a Free Plan workspace

## Expected Result:
The NewDot report for that expense should show that the expense is a company card expense.

## Actual Result:
The expense shows as a Cash expense in the NewDot report.

## Workaround:
None at this stage. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![image](https://github.com/Expensify/App/assets/59587260/1a92eb2d-dadc-44ea-8aff-8a4f20ce9e16)

![image](https://github.com/Expensify/App/assets/59587260/4a7c7315-16d0-4554-a313-542dfa9d190d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127a49d004eeba942</li>
        <li>Upwork Job ID: 1760479216127422464</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

**Comment by lschurr** [comment]
Just asking some questions in the Slack thread about where this needs to go.

**Comment by lschurr** [comment]
Tagging @kevinksullivan @grgia based on the Slack thread :)

**Comment by grgia** [comment]
@lschurr do you have the transaction ID handy?

**Comment by lschurr** [comment]
User email: erin@uaa-xa.com
Transaction ID: 2447216785078725321

**Comment by lschurr** [comment]
Just assigning to you for now @grgia - feel free to do something different with it :)

**Comment by grgia** [comment]
I'm going OOO till the end of the week, going to unassign incase someone else wants to take this over while I'm out. Will reassign when Im back if not!

**Comment by grgia** [comment]
If someone takes this over, it's most likely an issue with the reimbursable flag not being sent in OnyxUpdate for some reason

**Comment by lschurr** [comment]
Are you able to grab this back this week @grgia?

**Comment by greg-schroeder** [comment]
Calling this out in the weekly update

**Comment by lschurr** [comment]
Looks like we're waiting for proposals or an internal volunteer to grab this one. Is that right @greg-schroeder @grgia?

**Comment by luacmartins** [comment]
It should have been fixed [here](https://github.com/Expensify/App/pull/35488/files). Can we retest?

**Comment by luacmartins** [comment]
That being said, my fix was deployed on v1.4.36-5 and this issue was reported on v1.4.41-12, so maybe there's something else going on here.

**Comment by SofiedeVreese** [comment]
Looks like they've moved from a free workspace to a paid collect plan now and everything's on OldDot, so I don't think we can test this one anymore.

**Comment by lschurr** [comment]
Hm, ok. Should we close this one @luacmartins @grgia?

**Comment by luacmartins** [comment]
Yea, I think we can close this one and reopen if it happens again.
