### ISSUE TITLE
[HOLD for payment 2024-07-23] [CRITICAL] [P2P] Refactor the wallet enablement flow to be step by step and conform with our new design system

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#36648]
**Problem**:
The existing wallet enablement flow UI does not comply with our new brand design system, particularly our philosophy to take a stey by step approach to getting user input. It also doesn't give the user a sense of progression or context for remaining steps, which could cause drop off.

**Solution**:
Let's refactor the Ui to ask for the info step by step instead of all at once. Let's add a progress bar at the top for the various sections:

**Starting point, no change**
<img width="157" alt="image" src="https://github.com/Expensify/App/assets/14225673/fe2cc21a-0273-4bd4-a46f-26ba2479c65d">

**Current `Add bank account` step**, which loads a blank modal and automatically jumps to Plaid flow. Although the only choice here at the moment, it is cleaner to just show this step and allow the user to explicitly click on `Connect via Plaid`
<img width="441" alt="image" src="https://github.com/Expensify/App/assets/14225673/4f08e16d-2e57-4b33-b06a-829f31e93bbd">

**Current `Additional Details` step**, which is shown as one form, with all these details. We will refactor it to ask for the details step by step here
<img width="731" alt="image" src="https://github.com/Expensify/App/assets/14225673/dbc2dd71-0532-4dbf-9eff-9093daff8c65">

**Current `Verify Identity` step**, which presents some legalese links and then moves into the Onfido SDK flow. But the Onfido SDK flow begins with disclosures that the user needs to accept, so we don't need to show this legalese twice. We will therefore change the copy at the start of this step as well.
<img width="218" alt="image" src="https://github.com/Expensify/App/assets/14225673/963de748-091c-4db1-8c75-6415873b490c">

**The Onfido SDK flow** cannot be further customized to match our branding but, can we try to add the progress bar we're using here at the top of that entire flow, if possible?

**Current `Terms and fees` step**, which is shown as one long blob, with all these details. We will refactor it to show it step by step here
<img width="341" alt="image" src="https://github.com/Expensify/App/assets/14225673/3a57eca8-f299-4f31-a480-6636ceb4c741">
- The first of these screens should be scrollable and the `Next` button should be inactive till they get to the end and then turn active. If they try to click on it when inactive, let's present an error message to scroll to the end and review all of it. 

**Finished step, no change**
<img width="167" alt="image" src="https://github.com/Expensify/App/assets/14225673/f6cdd1de-b474-490f-9ec9-46fda6c7c2c7">

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by shawnborton** [comment]
For the start of the Onfido flow, I guess we should just mirror what we currently have in product (note this whole flow got a face lift recently!) where we basically just have one screen as a primer, then we kick off the Onfido flow?
![CleanShot 2024-02-16 at 08 41 39@2x](https://github.com/Expensify/App/assets/2319350/241069f2-c924-484c-9a6f-95b98528aba5)

**Comment by shawnborton** [comment]
Also just cc'ing @mountiny (sorry for all the tags these days!) for visibility, in case we want to have the same group who worked on the VBA flows take this one as well.

**Comment by mountiny** [comment]
Thanks for the ping! We could ask Callstack due to their experience with this. I am curious though, I am not that familiar with the backend for this flow so curious if there would any changes be required there. @MariaHCD do you think you could chime in? I assume from what I could read the order of the steps is more or less the same. 

We are not moving any checkboxes or any inputs to different steps right? (asking because we had that issue in the bank refactor and had to make changes to the backend slightly)

**Comment by anmurali** [comment]
So far as I can tell, we're not changing any inputs. The only thing worth double clicking on is *Current Verify Identity step*
We currently show 
<img width="292" alt="image" src="https://github.com/Expensify/App/assets/14225673/64ff388d-6401-4e0d-8d65-b96ebe18bba5">

I want to change that to 
![image](https://github.com/Expensify/App/assets/14225673/2b6b35dc-6115-4354-a422-74a415006eb3)

**Comment by mountiny** [comment]
Nice, that sounds like basically just UI change! 

@koko57 I heard you are keen on helping with this :) if so would you like to comment so I can assign you?

**Comment by koko57** [comment]
yes I was typing the message right now! 😃 I'm ready to help

**Comment by MariaHCD** [comment]
> the backend for this flow so curious if there would any changes be required there. @MariaHCD do you think you could chime in? I assume from what I could read the order of the steps is more or less the same.

The order of the steps looks the same to me too:
1. AdditionalDetails step - which calls the [UpdatePersonalDetailsForWallet](https://github.com/Expensify/Web-Expensify/blob/13e2684d3a27f4be7c9a3c2436b08d09be129f41/lib/BankAccountAPI.php#L2483-L2489) API command
2. Onfido step - which calls the [OpenOnfidoFlow](https://github.com/Expensify/Web-Expensify/blob/13e2684d3a27f4be7c9a3c2436b08d09be129f41/lib/BankAccountAPI.php#L2069) API command to initialize the flow, followed by [VerifyIdentity](https://github.com/Expensify/Web-Expensify/blob/13e2684d3a27f4be7c9a3c2436b08d09be129f41/lib/BankAccountAPI.php#L2097-L2104)
3. Terms step - which calls [AcceptWalletTerms](https://github.com/Expensify/Web-Expensify/blob/13e2684d3a27f4be7c9a3c2436b08d09be129f41/lib/BankAccountAPI.php#L2657-L2660)

The KYC flow is outlined in [this SO](https://stackoverflowteams.com/c/expensify/questions/14942) (in case it is helpful)

**Comment by MariaHCD** [comment]
One thing I'd like to add is regarding Knowledge Based Authentication (KBA) questions. @anmurali I'm assuming we still want to have these questions displayed to the user?

**Comment by mountiny** [comment]
🚀 perfect! @shawnborton will we need any more details? Maybe share a Figma file with Agata?

@MariaHCD Thank you, very helpful!

Noting here as well this is to help with testing https://stackoverflowteams.com/c/expensify/questions/10607/11542#11542

**Comment by shawnborton** [comment]
[This is the Figma](https://www.figma.com/file/vBXCQWjQExxcmZjFxbME4C/Add-Bank-Account-Flows?type=design&node-id=49%3A11719&mode=design&t=RtNObryr7IjJfDoa-1) file we have been using.

**Comment by mountiny** [comment]
Thanks, shared with Agata!

**Comment by koko57** [comment]
Yesterday I started working on the first view - the additional step with the "Connect bank account". I'll continue working on this today

**Comment by koko57** [comment]
@mountiny @shawnborton I'm almost finished with the UI (easier) part then I'll work on the logic. But before I close the UI part I just wanted to make sure:
<img width="349" alt="Screenshot 2024-02-22 at 17 37 53" src="https://github.com/Expensify/App/assets/28020445/5d22345d-7ac7-4537-9218-ebf9893d93f1">

- we only want one "Connect bank account" button there?
- if so, do we need this text: "choose an option below"? (afaik we don't display it in VBBA flow)
- should I leave this space below the button?

Can I also ask for the Spanish translations for the title and the description?

**Comment by shawnborton** [comment]
Hmm would love @anmurali 's input on those when she is back from OOO, though maybe @joekaufmanexpensify can help answer that. @joekaufmanexpensify would we ever have a "manual" option for connecting your bank account for the Wallet enablement flow?

> if so, do we need this text: "choose an option below"? (afaik we don't display it in VBBA flow)

Great point, that label could be removed in that case

And yeah, the space below the button should be removed too I think.

**Comment by joekaufmanexpensify** [comment]
>would we ever have a "manual" option for connecting your bank account for the Wallet enablement flow?

Yep, we definitely will at some point. It just hasn't been built yet. Right now you can only add a bank account via Plaid here.

**Comment by shawnborton** [comment]
Sounds good. So @koko57 let's plan to just use the one button which means we can remove the preceding label.

**Comment by shawnborton** [comment]
@koko57 when you have your PR ready for review, can you please tag myself as well as @jamesdeanexpensify who can help out with the correct copy to use? Thanks!

**Comment by koko57** [comment]
@shawnborton 
I'm struggling a little bit with the logic for the first steps (but when I get it right it'll be much easier for the next ones). I'll do my best to open the first PR till the EOW.

I also wanted to let you know that I'll be ooo for the next week (03/03 - 03/11). I'll continue working on this from 03/12.

**Comment by koko57** [comment]
I unfortunately didn't manage to finish the whole step 1 - still need to improve some logic to make it work properly and cleanup the code, so I decided not to open the PR now. All the changes are on the https://github.com/koko57/App/tree/refactor/36648-wallet-enablement-flow branch.

I would be very grateful for Spanish translations of these texts:
- 'Add your bank account'
- 'Send and receive money'
- 'Add your bank account and we’ll connect it to your Expensify Wallet so you can send and receive money right in the app.'
- 'Don’t worry, you’ll be able to withdraw funds from your wallet at any time.'
- 'Choose your bank account'
- 'Make sure that you select the right one.'

As I've mentioned earlier, I'll be ooo for the next week and will be back on 03/12

**Comment by jamesdeanexpensify** [comment]
Before we get to Spanish translations, we've been working on rewriting the copy in the [Figma file](https://www.figma.com/file/vBXCQWjQExxcmZjFxbME4C/Add-Bank-Account-Flows-(VBA%2C-Wallet%2C-Onfido)?type=design&node-id=49-11719&mode=design&t=QOF0E4pQxzXe2SGu-0) and I left a few more comments for @shawnborton @anmurali when they can get to them! If either of you are able to talk through these today, it might go a bit faster.

**Comment by anmurali** [comment]
Addressed all your comments. @jamesdeanexpensify make sure we use the personal info flow that includes the last 4 of SSN

**Comment by jamesdeanexpensify** [comment]
Thanks! I added the SSN screens to the top flow in the [Figma](https://www.figma.com/file/vBXCQWjQExxcmZjFxbME4C/Add-Bank-Account-Flows-(VBA%2C-Wallet%2C-Onfido)?type=design&node-id=49-11719&mode=design&t=htXoWxJqscNYp9Xr-0) and I'll address your comments today!

**Comment by shawnborton** [comment]
What's the latest here? Anything you all need from me on these?

**Comment by mountiny** [comment]
Not sure about the designs, but @koko57 should be back tomorrow or Wednesday to resume work on it

**Comment by jamesdeanexpensify** [comment]
@shawnborton @anmurali some (hopefully) last comments for you both in the [Fig](https://www.figma.com/file/vBXCQWjQExxcmZjFxbME4C/Add-Bank-Account-Flows-(VBA%2C-Wallet%2C-Onfido)?type=design&node-id=49-11719&mode=design&t=tJ0xPJJ7kVxk7F20-0)

**Comment by shawnborton** [comment]
Sounds good, responded to a couple, let me know if anything else is needed specifically from me.

**Comment by jamesdeanexpensify** [comment]
@anmurali just one left for ya [here](https://www.figma.com/file/vBXCQWjQExxcmZjFxbME4C/Add-Bank-Account-Flows-(VBA%2C-Wallet%2C-Onfido)?type=design&node-id=49-11719&mode=design&t=C01XQqzV1gj2wLtU-0)!

**Comment by koko57** [comment]
Sorry for the delay here - I had to take care of my other issue. I'll be able to get back to it and focus mainly on that tomorrow/on Friday. I'm catching up with the comments in Figma

**Comment by koko57** [comment]
I'm almost finished with my other issues, so this week I'll be working mainly on this task. I've updated the copies, now polishing the logic and doing some code cleanup.

**Comment by koko57** [comment]
@shawnborton While working on this task and comparing the flow to the reimbursement VBBA flow I've noticed some differences. I just want to make sure that they are deliberate:

- ‘Ending in 1111’ text is below the bank name in VBBA not the account name
<img width="370" alt="Screenshot 2024-03-20 at 21 24 07" src="https://github.com/Expensify/App/assets/28020445/b91a8614-eca7-4252-ad26-b4da85a91a97">
<img width="512" alt="Screenshot 2024-03-20 at 21 24 52" src="https://github.com/Expensify/App/assets/28020445/c74afafc-6fdd-47fd-a0f2-93324bbdfc1c">

- the steps markers are displayed on the step with choosing connection methods (while in VBBA not)
<img width="405" alt="Screenshot 2024-03-20 at 21 25 00" src="https://github.com/Expensify/App/assets/28020445/41459f5b-c5b1-4510-950c-526e7033f6bf">

- copies for the personalInfo steps are slightly different (‘What’s your address?’ vs ‘E
<img width="374" alt="Screenshot 2024-03-20 at 21 25 13" src="https://github.com/Expensify/App/assets/28020445/43cf7a7c-3d0a-4244-813e-0d39cecb827d">
nter your address’)

**Comment by shawnborton** [comment]
> ‘Ending in 1111’ text is below the bank name in VBBA not the account name

For this one, let's mirror the existing flow in the product

> the steps markers are displayed on the step with choosing connection methods (while in VBBA not)

Same, happy to mirror the existing flow in product

> copies for the personalInfo steps are slightly different (‘What’s your address?’ vs ‘Enter your address’)

I believe we want to use the updated copy form the Figma file, and we want to update the copy on both Wallet and VBBA flows

cc @jamesdeanexpensify @anmurali for a gut check too.

**Comment by koko57** [comment]
@shawnborton thanks for such a quick response! Ok, I will use Figma copies for now, if it would need to be changed later (for either Wallet or VBBA flow), just let me know, I'll take care of it. May I also ask for Spanish translations for the copies? Or are they somehow hidden in Figma?

**Comment by shawnborton** [comment]
@muttmuure or @mountiny - what is the process for getting Spanish translations? Currently we do not have them in Figma.

**Comment by muttmuure** [comment]
This is the process! 

https://stackoverflowteams.com/c/expensify/questions/10316

**Comment by jamesdeanexpensify** [comment]
Yes, I think we should plan to use all copy in Figma!

**Comment by koko57** [comment]
Sorry, it has taken me so long to open the first PR - https://github.com/Expensify/App/pull/39038 - I wanted to do it as similar as in VBBA flow as possible and reuse as much code as possible. It was a bit hard and still I ended up with some code repetition, but I'm planning to improve it in the subsequent PRs.

For now the PR contains the changes for the Add Bank Account step. I'm planning to split the Personal Info and other steps into smaller PR. When I have them working we can replace the old flow with the new one. I will try to make code as clean as possible during the development but if there will be some need for refactor or code improvements after the flow is done I can take care of it in follow-ups after we replace the new flow with the old one.

Now I'm working on test steps and author's checklist to open the PR asap.

cc @mountiny

**Comment by mountiny** [comment]
Thank you, PR is looking great so far, I am asking if the C+ is able to dedicate more time to this or if to look for different one with more capacity

**Comment by mountiny** [comment]
First PR was merged, great job @koko57 https://github.com/Expensify/App/pull/39038

What is the next step now and your ETA for it?

**Comment by koko57** [comment]
@mountiny I've started working on Personal Info step, this one is much easier - I think most of the work here will be done by Wednesday

**Comment by mountiny** [comment]
Thanks

**Comment by koko57** [comment]
Issues to solve in the following PRs:

- [ ] https://github.com/Expensify/App/issues/39847
- [ ] https://github.com/Expensify/App/issues/39900

**Comment by koko57** [comment]
Asking [for this one](https://github.com/Expensify/App/issues/39900), just to confirm: currently ,the offline indicator is not shown on the web (wide screen) for the first step of new VBBA flow, so the same should happen for the Enable Wallet flow? Or the offline indicator should be displayed on the wide screen and the prop should be added like it was suggested [here](https://github.com/Expensify/App/issues/39900#issuecomment-2044401476)?
<img width="820" alt="Screenshot 2024-04-09 at 17 45 32" src="https://github.com/Expensify/App/assets/28020445/ccd33930-dfd4-4733-91be-3abcb6adfbc3">

cc @shawnborton @mountiny

**Comment by koko57** [comment]
@shawnborton @mountiny I've just spotted one inconsistency with the old flow - we don't have an input for the phone number in the new flow. We no longer should send this in the request?

**Comment by shawnborton** [comment]
cc @anmurali as well - if the old flow asked for a phone number, I assume we still need it here as well. 

@koko57 can you share a screenshot of what it looks like in the old flow? Thanks!

**Comment by koko57** [comment]
<img width="394" alt="Screenshot 2024-04-12 at 13 57 42" src="https://github.com/Expensify/App/assets/28020445/c4cd4312-2961-4065-8e2d-ccd2da5b7850">

@shawnborton the last input before Date of Birth

**Comment by shawnborton** [comment]
Okay, I think we should have that in the new flow but based on the screenshots in the original comment, I think we did include that? Or I might be misunderstanding you. 

![CleanShot 2024-04-12 at 14 59 39@2x](https://github.com/Expensify/App/assets/2319350/584f6093-2490-4e79-822c-99968188bb0b)

**Comment by shawnborton** [comment]
Ah I totally missed that - sorry! I think we'd just add it as another screen, perhaps before the SSN screen:
![CleanShot 2024-04-14 at 20 46 02@2x](https://github.com/Expensify/App/assets/2319350/6637c77b-cbf0-46ef-8111-c656bfdca976)

@anmurali - what do you think?

@jamesdeanexpensify - perhaps you can chime in with copy suggestions.

**Comment by mountiny** [comment]
agree with the plan, thank you for the update

**Comment by jamesdeanexpensify** [comment]
@shawnborton do you still want feedback on [this flow](https://github.com/Expensify/App/issues/36648#issuecomment-2054151925)? I think I looked at this previously, but I just noticed a couple minor things:

- The first screen, maybe since we already say "What's your legal name?" at the top, we can just say "First name" and "Last name" in the fields
- Also in the first screen, the "First name" field is some sort of dropdown. That should just be an open text field, right?
- Third screen, maybe we can lower-case "Street address" and "Zip code"
- Fourth screen, maybe we can update the body text under the header a bit to make it a bit more helpful. Like, do you know if they need to enter a country code and/or area code?

**Comment by shawnborton** [comment]
cc @koko57 - I wonder if you can incorporate those changes into your PRs?

@jamesdeanexpensify - did you update the Figma file with your suggestions? If not, feel free to do so!

**Comment by koko57** [comment]
@shawnborton yeah, ofc, will do!

**Comment by jamesdeanexpensify** [comment]
@shawnborton I changed what I could in all three `Personal Info` flows [here](https://www.figma.com/file/vBXCQWjQExxcmZjFxbME4C/Add-Bank-Account-Flows-(VBA%2C-Wallet%2C-Onfido)?type=design&node-id=49-11719&mode=design&t=yFv6vFzcyG8wXmZB-0). @anmurali for the "What's your phone number?" screen, is there a requirement for adding a country code and/or area code, and do we require hyphens/no hyphens? I'd just like to make the body text more helpful, it currently just says "We need this to verify your wallet." and I'd love to make it a bit more informative, if possible. Thanks!

**Comment by koko57** [comment]
After I address all the comments on my PRs I will start working on the logic and connecting all the steps together (I didn't open the PR for Onfido step yet, but I think it would be better to add this step with all the logic). 

I tried to go through the old flow and I keep getting this error:
<img width="1426" alt="Screenshot 2024-04-25 at 13 53 51" src="https://github.com/Expensify/App/assets/28020445/de43bd80-d407-4677-9087-57765043de16">

I wonder if it's because of a phone number I provide or something is broken? I've also tried it on the staging server, but it doesn't work.

**Comment by MariaHCD** [comment]
> I wonder if it's because of a phone number I provide or something is broken? I've also tried it on the staging server, but it doesn't work.

Regarding the request `879de3ea0cc31eb0-EZE` (logs [here](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%22879de3ea0cc31eb0-EZE%22%20AND%20timestamp%3A%5B2024-04-19T00%3A00%20TO%202024-04-27T23%3A59%5D)), one of our backend identity verifications failed. Could you let us know what information you entered in the additional details form?

**Comment by koko57** [comment]
Thanks @MariaHCD!
 
> Regarding the request `879de3ea0cc31eb0-EZE` (logs [here](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%22879de3ea0cc31eb0-EZE%22%20AND%20timestamp%3A%5B2024-04-19T00%3A00%20TO%202024-04-27T23%3A59%5D)), one of our backend identity verifications failed. Could you let us know what information you entered in the additional details form?

My name and surname
Any address from the dropdown,
DOB i.e. 07-04-2006 (or any other date)
phone: +12134561233 or +18503059900 (actually it happens for any number that passes FE validation)
SSN: 123456789

I didn't have a chance to get successfully to the next step - no matter what data I provided I get this error

**Comment by MariaHCD** [comment]
For the additional details form, use the below information:
- first name: Alberta
- last name: Charleson
- SSN: 3333

For the other fields, it can be any data and you should be able to proceed to the next step. Let me know!

**Comment by koko57** [comment]
@MariaHCD thanks! It works! And is there anything I can do to skip Onfido verification? I tried with the DOB like in the VBBA flow (2000-08-08) but it doesn't work

**Comment by MariaHCD** [comment]
> is there anything I can do to skip Onfido verification?

Ah, right now, we do not have a way to skip the Onfido Verification in the wallet enablement flow on staging. You can use any test data for the Onfido verification flow and you should be able to proceed to the next step. Also, we do not currently allow activating wallets on staging, so even if you complete KYC, you will still have a pending wallet.

**Comment by koko57** [comment]
While the PR for the Fees & Terms is waiting to be merged I'm working on connecting all the steps. The step for Verify Identity is done but I decided it would be better not to open a separate PR for Identity but a new PR with all the steps connected including the Onfido.

**Comment by muttmuure** [comment]
@Pujan92 invited to this job: https://www.upwork.com/jobs/~019a77351c41f028f8

**Comment by Pujan92** [comment]
Thanks @muttmuure but to inform this task is not completed fully yet.

**Comment by koko57** [comment]
@shawnborton @anmurali I've got a question on the flow - currently we first add bank account and then we need to fill in the Additional Details form. After we add bank account it si shown in the wallet and if we go back from the Additional Details step we exit the flow the bank account is added. My question is: in this new flow we should be able to get back to the first step (adding bank account) and if we exit the flow the bank account should not be displayed in the wallet (should not be added to the wallet)?

**Comment by anmurali** [comment]
Good question. For BBAs, the add bank account step looks like this:
<img width="618" alt="image" src="https://github.com/Expensify/App/assets/14225673/6d35ed6b-7d38-46da-9f1b-c3bfa258a9d6">

When the user moves on to the next step - adding company details, but say abandons and goes back to bank account step, we do retain the bank account added and assume they want to use it. Although if they want to then change that, they can use the `Connect a different account` to go all the way forward and start over by linking a new bank account. I think we should do the same thing here. @shawnborton do you agree?

**Comment by shawnborton** [comment]
That makes sense to me, but where are you getting those screenshots from? Figma? I think the third screenshot should not use the green card BG style and rather we should just use something more similar to the 2nd screen.

**Comment by anmurali** [comment]
@shawnborton I grabbed em from [the design doc](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit#heading=h.d67gaosm18p0) where we implemented the step by step BBA setup flow a while back.

**Comment by shawnborton** [comment]
Got it, do you know if that exists in the product then? Do we have a real screenshot I could look at?

**Comment by mountiny** [comment]
Merged https://github.com/Expensify/App/issues/36648 @koko57 Could you please list out the planned next steps/ PRs just so we have a better picture of whats left? Thank you!

**Comment by koko57** [comment]
@mountiny 
this is what's left here:
- [ ] connecting all the steps + Verify Identity step - in progress
- [ ] code cleanup + refactor (removing duplicated code etc) after changing to the new flow

**Comment by mountiny** [comment]
Lovely, we are very close then.

Lets keep this one going when there is no higher priority work needed. This week we should be able to start working on the workspace feeds

**Comment by rafecolton** [comment]
There's one more small requirement I'd like to include in this flow if possible. We need to show the user one of two different Wallet Agreements on the Terms and Fees page. Based on their state, we determine what program they're in (Bancorp or MTL), and then link to the appropriate page:
* MTL - https://use.expensify.com/expensify-payments-wallet-terms-of-service
* Bancorp - https://use.expensify.com/bancorp-bank-wallet-terms-of-service

@koko57 @mountiny would that be easy to do as part of this PR or better as a follow up? Issue for it [here](https://github.com/Expensify/Expensify/issues/382704) (it's internal only at the moment I can move it to App if needed).

**Comment by koko57** [comment]
@rafecolton I think I can include it in the last PR for the flow. 🙂 Thanks for the info!

**Comment by rafecolton** [comment]
Great, thank you! Would you mind adding me as a reviewer on that PR so I can test it out? I'm working on getting the issue transferred to the `App` repo so you can get credit for it.

**Comment by mallenexpensify** [comment]
@koko57 can you plz comment on the E/App issue I created for/from the E/E issue so I can assign to you? thx
- https://github.com/Expensify/App/issues/42400

**Comment by mountiny** [comment]
Thanks! I think that should be fine to add in the last PR 🙌

**Comment by koko57** [comment]
I'm testing the whole flow now, making last amendments, draft PR should be ready for tomorrow

**Comment by koko57** [comment]
Draft PR is ready. I need to fix one thing with validation and then I'll be able to open the PR for the review.

**Comment by Pujan92** [comment]
@mountiny I am back and can do the review, can you plz assign [this](https://github.com/Expensify/App/pull/42589) to me?

**Comment by mountiny** [comment]
Thanks, made a build on the PR and requested a review from you

**Comment by koko57** [comment]
@shawnborton @anmurali @mountiny After the comments on my PR I just realized one thing - after adding debit card or after any other action do we redirect the user to the EnablePaymentsPage? (I tried to check it myself but I can't get through adding the card, there is also one occurrence in the code where we do that onSuccessfulKYC). I mean - should we be able to access from these other places the old EnablePayments page with Additional Details form and access the new flow only from Enable Wallet button settings/wallet?

**Comment by mountiny** [comment]
@koko57 I am not sure if I fully follow your question? Could you illustrate maybe with screenshots?

**Comment by koko57** [comment]
@mountiny Maybe to rephrase and simplify a bit: are there any contraindications to have the whole flow on one ENABLE_PAYMENTS route? Is any other flow, apart from adding personal bank account, using old EnablePayemnts steps (Additional Details form and the subsequent ones)?

**Comment by mountiny** [comment]
@koko57 you can jump into that flow from trying to pay with your wallet, but it should go to the start of the flow. I dont think we would need to deeplink to a specific step in the flow.

**Comment by thienlnam** [comment]
We noticed this issue which seems to have been missed from the refactor (to include KBA questions after resubmitting without changing any data). Additionally, there seems to be another bug asking for the full 9 digits of SSN that I've attached below.

Could you please take a look at those as well?



https://github.com/Expensify/App/assets/30609178/f7ec6b39-ec24-4df1-92b3-803d56473689

**Comment by koko57** [comment]
@thienlnam ok I will look into this

**Comment by koko57** [comment]
@thienlnam for the ssn error - it's from the backend and I can only recreate this when I type i.e. "Bobbeth" as the last name (or any other name) instead of Charleson. Just like in the video in [this issue](https://github.com/Expensify/App/issues/44462). I'm not sure why did you get this typing in the correct last name, but it's rather a BE issue. 

For the Idology questions - I'm working on it

**Comment by koko57** [comment]
@shawnborton I just wanted to consult with you the design here, as the screen for Idology questions is not in Figma. Should I leave the current component look as it is (screenshot 1), or make the header look like in the other steps/substeps (screenshot 2). The copies for this screen stays the same?
1.
<img width="374" alt="Screenshot 2024-06-28 at 13 05 44" src="https://github.com/Expensify/App/assets/28020445/b229aac7-ccea-4d17-aad6-c62476c23112">
2.
<img width="376" alt="Screenshot 2024-06-28 at 13 07 27" src="https://github.com/Expensify/App/assets/28020445/802e5aaa-278e-4ad5-b6db-5aec8eb6a5f5">

**Comment by shawnborton** [comment]
I like what you have for 2! Could we also put the blue link below the question and use the smaller style like we do elsewhere?

**Comment by koko57** [comment]
@shawnborton yep, of course! thanks!

**Comment by shawnborton** [comment]
Also, maybe we don't need the question to be in bold either? I think it would match other pages better if it was in regular font weight. Thoughts?

**Comment by koko57** [comment]
<img width="369" alt="Screenshot 2024-06-28 at 14 26 23" src="https://github.com/Expensify/App/assets/28020445/0a0db67e-25f2-4959-b3de-5f6271521bcb">

something like this will be ok?

**Comment by shawnborton** [comment]
Looking good! Small detail, but could we move the checkbox answers up to be about 8px closer to the question above it? And then maybe add those 8px to the bottom of the answers to create a bigger gap between answers and the footer link? Visually I'd like to make it seem like the answers are more connected to the questions than the footer.

**Comment by koko57** [comment]
@thienlnam @shawnborton @mountiny PR opened for review: https://github.com/Expensify/App/pull/44628

**Comment by Pujan92** [comment]
@mountiny @muttmuure Can we process the payment for this issue?

**Comment by mountiny** [comment]
So I can see that @Pujan92 reviewed:
- https://github.com/Expensify/App/pull/42589 also @DylanDylann 
- https://github.com/Expensify/App/pull/39038
- https://github.com/Expensify/App/pull/40357
- https://github.com/Expensify/App/pull/40567

Not sure if I have missed anything. They were large PRs and time-consuming to test so I would say $1500 altogether for @Pujan92 is suitable.

$250 to @DylanDylann for help on  https://github.com/Expensify/App/pull/42589

**Comment by muttmuure** [comment]
$250 @Pujan92 C+
$250 @DylanDylann C+

**Comment by muttmuure** [comment]
Automation failed, invited @DylanDylann to https://www.upwork.com/jobs/~0147a6261f6e47d9e6

**Comment by shah-pujan** [comment]
> $250 @Pujan92 C+ 

@muttmuure Can you plz consider https://github.com/Expensify/App/issues/36648#issuecomment-2243813350

**Comment by Pujan92** [comment]
> $250 @Pujan92 C+

@muttmuure Can you plz consider https://github.com/Expensify/App/issues/36648#issuecomment-2243813350

**Comment by muttmuure** [comment]
I've updated the payment summary

**Comment by shah-pujan** [comment]
Thanks! :)

**Comment by muttmuure** [comment]
Not overdue

**Comment by DylanDylann** [comment]
> Automation failed, invited @DylanDylann to https://www.upwork.com/jobs/~0147a6261f6e47d9e6

Sorry @muttmuure I couldn't open that link, it says "This job is private. Only freelancers invited by client can view this job.". I don't see any new offer either.

**Comment by JmillsExpensify** [comment]
$1,500 approved for @Pujan92

**Comment by muttmuure** [comment]
Sorry @DylanDylann - I've invited you again

**Comment by muttmuure** [comment]
Job is here: https://www.upwork.com/jobs/~0147a6261f6e47d9e6

**Comment by DylanDylann** [comment]
@muttmuure Thanks 🙏 , I applied to the job

**Comment by muttmuure** [comment]
Offer sent

**Comment by muttmuure** [comment]
Waiting for offer to be accepted

**Comment by DylanDylann** [comment]
@muttmuure Offer accepted with thanks!

**Comment by mountiny** [comment]
I believe we can close this one now, right?

**Comment by muttmuure** [comment]
Paid
