### ISSUE TITLE
[HOLD for payment 2024-03-22] [Wave Collect] [Ideal Nav] Ideal Nav v2 changes

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#36656]
## Background
Now that we've lived with Ideal Nav for a week, we've experienced the following issues with the [core design](https://docs.google.com/document/d/1VnEf2ThbbiQj0kx9KnAihF0DWf50s2Bn_MztEyEwtjg/edit):

 - Accessing a workspace via the 🔧 resulted in a "lateral," global switch of someone's workspace. This was confusing because we created one known, obvious way to switch a worked – the workspace switcher – and then one secret, confusing way to "laterally" switch a workspace by choosing it in Settings. 
 - Account settings was accessed via an avatar in the top right, whereas workspace settings was accessed in the 🔧 bottom tab. Though now that we're deprecating "lateral" switching, separating these two types of settings pages is no longer necessary. Let's combine them in one central place.
 - Finally, while we aspire to have feature-rich global search, today our "search" is merely a chat switcher. As a result, it doesn't deserve the prominence that we've given it. 

## Summary of changes
All in all these and other experiences have encouraged us to tweak the core Ideal Nav designs via the following v2 changes:

### Header
 - The workspace switcher, workspace name and page name all share the same line in the header. 
 - Additionally, the search input becomes a magnifying glass icon is only appears the header for the `Chats` tab (as again, the only "search" we have is a chat switcher). 
![image](https://github.com/Expensify/App/assets/1127863/1718048b-1a87-4d5d-8f83-5b5af1bdcd6e)

### Bottom Tab
 - The 🔧 is replaced by a 28x28 user avatar, which reveals a new Settings page that combines account settings as well as workspace settings
![image](https://github.com/Expensify/App/assets/2319350/e61ba730-ae9c-42f5-bf2c-cf1fb469dc90)

 ### Settings
- The new combined Settings page has three main sections: `Account`, `Workspaces` and `General`. 
![image](https://github.com/Expensify/App/assets/2319350/10f3c10b-8e85-4e2f-a381-c7de551a3b56)

- A 100x100 user account avatar appear at the top of the Settings, with a "share code" icon in the top left and a "status" icon in the top right. The "share code" icon replaces the previous push row, while "status" displays a user's status, should one exist. Tapping the "status" icon takes the user to https://new.expensify.com/settings/profile/status. 
  - <img width="448" alt="Screenshot 2024-02-15 at 22 17 38" src="https://github.com/Expensify/App/assets/1127863/4ff469bb-d1c6-43b3-8e8c-5844b657636a">

- `Account` is the first section in Settings, and includes nav items for `Profile`, `Wallet`, `Preferences` and `Security`
  - <img width="450" alt="Screenshot 2024-02-15 at 22 18 05" src="https://github.com/Expensify/App/assets/1127863/e38b1fa6-dd45-4ee0-b7b3-810543289f56">

 - `Workspaces` is the second section in Settings, and includes nav items for `Workspaces`, `Subscription`, and `Cards & Domains`. 
   - <img width="390" alt="Screenshot 2024-02-15 at 22 23 48" src="https://github.com/Expensify/App/assets/1127863/f45ed30c-71bc-4560-a6d0-57169a4d2466">

- `General` is the last section in Settings, and includes nav items for `Switch to Expensify Classic`, `Help`, `About` and `Sign out.
  - <img width="394" alt="Screenshot 2024-02-15 at 22 20 03" src="https://github.com/Expensify/App/assets/1127863/32289f82-fcff-4fc6-8013-321381a1a37b">

### Workspaces
 - The `Workspaces` page has two states, depending on whether a user is a member of a workspace or not. 
![image](https://github.com/Expensify/App/assets/2319350/ed760dc4-d412-40e0-8d3f-f8895ae3d3e7)
 - When viewing a specific workspace's settings, we launch a full screen experience, which pushes the workspace setup pages in the the LHN. No bottom tabs appear in this view. 
![image](https://github.com/Expensify/App/assets/1127863/7cc83d85-0558-4b04-9c80-a1f2a3e3c217)
 - To exit out of the full screen workspace editor, a user would click the back caret in the LHN header, which takes them to https://new.expensify.com/settings/workspaces. 
 - Mobile views shown below for extra clarity. 
![image](https://github.com/Expensify/App/assets/2319350/a36584c7-d249-44d6-9241-200ae75b6ab9)

## Individual Issues
[This space can be used if we opt to break up this initiative into individual issues and corresponding PRs]

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by JmillsExpensify** [comment]
Note: This issue is for internal use and the corresponding implementation to be handled by SWM.

**Comment by trjExpensify** [comment]
Nice!! 

>Bottom Tab
> - The 🔧 is replaced by a 28x28 user avatar, which reveals a new Settings page that combines account settings as well as workspace settings
![image](https://github.com/Expensify/App/assets/1127863/5362d48f-fb51-4b8d-8a37-4f72313d4dd7)

What about the active state of the settings bottom tab. We're giving the avatar a green ring, right @shawnborton?

**Comment by shawnborton** [comment]
That's right, I can update the images above.

**Comment by trjExpensify** [comment]
Perf, thanks!

**Comment by shawnborton** [comment]
Updated. 

Though @Expensify/design one thing I realized - if the default avatar is green, the green active ring is hard to see. Maybe we should create some separation like so?
![image](https://github.com/Expensify/App/assets/2319350/e455d3a6-b25d-4614-bd45-7d29e8446de3)

**Comment by shawnborton** [comment]
Right on, I'll update the shots assuming Jon doesn't have any strong pushback either.

**Comment by shawnborton** [comment]
Okay, updated all the screens.

**Comment by JmillsExpensify** [comment]
Nice work! @mountiny This one is ready for SWM.

**Comment by mountiny** [comment]
Will coordinate with them on Monday, thanks!

**Comment by dubielzyk-expensify** [comment]
Looks great to me @shawnborton . Alternatively we can add a 5% scrim on top of their avatar that won't actually mess too much with their picture, but will allow us to always have the circle be different. Just an alternative, but still think what you have above looks awesome.

**Comment by kosmydel** [comment]
Hey, I'm from SWM and I will work on this.

FYI: I'm going OOO from Wednesday, then @WojtekBoman will take over this issue.

**Comment by trjExpensify** [comment]
Nice, I've assigned you @kosmydel. @WojtekBoman can comment when he's taking over and we can assign him as well. :)

**Comment by shawnborton** [comment]
Try [this file here](https://www.figma.com/file/hMyXUbmDI7ooMq4ygVNaNX/Wave-8%3A-Design-Updates-to-Ideal-Nav-Structure-(%23ideal-nav)?type=design&node-id=73%3A15127&mode=design&t=j6MGMebm7wJd3vAG-1).

**Comment by WojtekBoman** [comment]
Hello! I'm going to work on it today :)

**Comment by WojtekBoman** [comment]
@shawnborton @dannymcclain How do we want to display RBR/GBR on the Profile icon in the bottom tab?

**Comment by shawnborton** [comment]
I think I would expect something like this for consistent placement across the two:
![image](https://github.com/Expensify/App/assets/2319350/e86d20b8-08fd-4c1a-a3cb-0b64f9f56773)

cc @dubielzyk-expensify too

I updated the Figma [here](https://www.figma.com/file/hMyXUbmDI7ooMq4ygVNaNX/Wave-8%3A-Design-Updates-to-Ideal-Nav-Structure-(%23ideal-nav)?type=design&node-id=140%3A8108&mode=design&t=z0E7tC53xE5WDIw5-1) with the screens you'd need.

But the thinking is that we give the bottom tab icon a wrapper of 28x28. The icon size for non-avatar icons is 24x24 yet the avatar goes up to 28x28 to be a little bigger. The chat icon is centered within that 28x28 area. Then the red dot is just anchored to the top-right of that 28x28 bounding box, with a 2px outer border. 

![CleanShot 2024-02-27 at 08 13 14@2x](https://github.com/Expensify/App/assets/2319350/e4e4d647-ee77-4d83-b592-28f70c8cdbd6)

**Comment by dannymcclain** [comment]
@shawnborton that looks good to me.

**Comment by WojtekBoman** [comment]
@shawnborton @dannymcclain I'm curious if we should show a dot when an icon is selected? I'm asking because currently the dot is hidden when we select a specific tab and we don't handle this case. If so, do we want to display a green dot on the 
selected chat tab icon? Both icons will be green in this case

**Comment by shawnborton** [comment]
As in, if there is a green brick road dot somewhere in the chats list, then we should show it on the Chats icon in the bottom tabs? I guess that makes sense, and I think even if the chat icon and dot icon are both green, it would still look okay:
![image](https://github.com/Expensify/App/assets/2319350/d2646ce3-81d6-469e-8f85-da8ce38dd3d4)

**Comment by dannymcclain** [comment]
Agree—I think the dot in the tab would show as long as there is an item in the tab that has a dot.

So if I have a green-dotted-chat, the chat tab would get a green dot. Selecting the chat tab would still show the green dot until I took whatever action was necessary to make the dot go away on the green-dotted-chat.

**Comment by dubielzyk-expensify** [comment]
Sorry if I missed this, but I'm also assuming that `red dot` takes precedence over the `green dot` if both were to appear?

**Comment by trjExpensify** [comment]
>Sorry if I missed this, but I'm also assuming that red dot takes precedence over the green dot if both were to appear?

Yeah, the RBR always takes priority over the GBR. Like we never show both on a chat row for example, so I think that same logic applies here on any given bottom tab for example.

**Comment by WojtekBoman** [comment]
I'd like to confirm one more thing related to the opening the Workspace Settings from the deeplink :) Where should we navigate after pressing the back button in this case? I think we should open the Settings screen, but before I start implementing the logic for that I wanted to confirm it's correct :) 

https://github.com/Expensify/App/assets/47774969/c059ebc7-c09c-4fc2-b2b9-cd150ca658ef

There's only one case where we should be redirected to the Home page from Workspace Settings, when we create a new workspace using the Workspace Switcher, right?

**Comment by WojtekBoman** [comment]
![Screenshot 2024-02-28 at 11 50 55](https://github.com/Expensify/App/assets/47774969/bce146a5-a75f-4cf8-912a-78b32a6e8b34)
Is this the correct design of the bottom tab for anonymous users?

**Comment by shawnborton** [comment]
Hmm I wonder if we should just replace the Search icon in the top right with the Sign In button, and leave a generic avatar in the bottom tabs? I think that might look cleaner.

**Comment by WojtekBoman** [comment]
Ok, sounds good :) So maybe I will ask also about the case when the avatar in the bottom tab is loading. In this case we display a skeleton and it can be selected. Here's what it looks like:  

https://github.com/Expensify/App/assets/47774969/6c1d27ec-b1d5-4bbb-bedd-df62c2f83398

Is it ok for you?

**Comment by shawnborton** [comment]
I think that feels good. The ellipse shape does feel like it has rough edges though - any idea how to fix that?

**Comment by WojtekBoman** [comment]
I'll check it :)

**Comment by dubielzyk-expensify** [comment]
>
Hmm I wonder if we should just replace the Search icon in the top right with the Sign In button, and leave a generic avatar in the bottom tabs? I think that might look cleaner.

100% with you. Feels a bit weird with the `Sign in` button in the bottom nav

**Comment by WojtekBoman** [comment]
@hayata-suenaga Is it possible to create a new workspace in OldDot and open it in NewDot? Some time ago I fixed [this issue](https://github.com/Expensify/App/pull/36498) and I'd like to check if it works with the new navigation, but currently I don't see an option to create a new workspace for free in OldDot. Does this functionality still exist?

**Comment by hayata-suenaga** [comment]
We recently got rid of the free workspace option. I'm checking on this with the internal engineering team. ([internal link](https://expensify.slack.com/archives/C03TQ48KC/p1709227621387609))

**Comment by hayata-suenaga** [comment]
If you enable chat reports in a collect policy in Old Expensify, you can still see a workspace that is created on Old Expensify in New Expensify.

<img width="500" alt="Screenshot 2024-03-01 at 10 48 48 AM" src="https://github.com/Expensify/App/assets/98560306/74e7126e-8ca1-4d4d-af5b-f6d7f82e5507">

**Comment by shawnborton** [comment]
Not overdue, onto payment soon.

**Comment by JmillsExpensify** [comment]
No payments are due here, so what else are we waiting on? Do we have a full set of regression tests added to TestRail? If so, I think we just lack a project wrap up and we're good.

**Comment by JmillsExpensify** [comment]
Ah thanks, that's not captured in the payment summary above. Is there an existing Upwork job for you?

**Comment by JmillsExpensify** [comment]
Looks like we have regressions to account for as well.

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @mkhutornyi for PR review and testing.

**Comment by hayata-suenaga** [comment]
I agree @mkhutornyi [this PR](https://github.com/Expensify/App/pull/37421/files) was quite a huge. we should at least have the standard rate.

@JmillsExpensify I'm sorry I should have provided a note about it before 🙇

**Comment by JmillsExpensify** [comment]
Cool, updated!

**Comment by JmillsExpensify** [comment]
@mkhutornyi I just sent you an offer on Upwork.

**Comment by mountiny** [comment]
I believe @mkhutornyi is out for medical reasons. We cam make this weekly unless you have confirmed its paid up @JmillsExpensify

**Comment by mountiny** [comment]
@JmillsExpensify @mkhutornyi can this be closed?

**Comment by JmillsExpensify** [comment]
Yes!
