### ISSUE TITLE
[$500] Another Login Page is Open view is not shown in the first window/tab

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36651]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #35294 
**Version Number:** 1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:

1. Open the Login page.
2. Open a new Login page in a new window or tab.

## Expected Result:
Another Login Page is Open view is shown in the first window/tab.
## Actual Result:
Another Login Page is Open view is not shown in the first window/tab.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/d43ad336-d40d-40dd-a442-aa6bf6b322a6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b09d99e022838c7</li>
        <li>Upwork Job ID: 1758365903140241408</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
@kavimuru looking!

**Comment by greg-schroeder** [comment]
Hmm. I am not super sure what controls when that `“You’ve opened the login page in a separate tab, please login from that specific tab.”` message is displayed, but it definitely used to be there.

Implemented here: https://github.com/Expensify/App/pull/27385

Might be related to: https://github.com/Expensify/App/issues/34567

**Comment by godofoutcasts94** [comment]
So, will this issue be handled by this [PR](https://github.com/Expensify/App/issues/34567) author or it is a new issue, accepting new proposals?

**Comment by greg-schroeder** [comment]
Ah, no, I think we're just going to close this as it's now intentional behavior per https://github.com/Expensify/App/issues/34567
