### ISSUE TITLE
[New architecture] The app doesn't resize properly when the status bar is translucent

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#36661]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 [here](https://github.com/Expensify/App/pull/13767#issuecomment-1906886539)
**Slack conversation:**

## Action Performed:
Open the app. (reopen after closing on LHN and on different screens, the result may differ depending on which screen is opened first)

## Expected Result:
The status bar should be transparent and there should not be a blank space on the bottom of the screen

## Actual Result:
There is a blank space with the size matching the status bar on the bottom of the screen

## Workaround:
This is a visual bug, should be fixed by https://github.com/Expensify/App/pull/13767/commits/c3679bbd64905b666e827b603ccb5097f83ff25b

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>

![android-statusbar-height1](https://github.com/Expensify/App/assets/21055725/dd2e41fd-aa9a-49c1-a933-540a397a02df)
![android-statusbar-height2](https://github.com/Expensify/App/assets/21055725/529aac62-375b-48c0-9ff2-29c9840439f7)
![statusbar-height3](https://github.com/Expensify/App/assets/21055725/3d3c84ab-6ff4-437a-b5c6-0c7057c02e33)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176beefaf58490faa</li>
        <li>Upwork Job ID: 1768714506853662720</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by mountiny** [comment]
All issues will be tested for the new arch pr in staging so closing this one
