### ISSUE TITLE
[New architecture] The keyboard leaves empty space when dismissed

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#36664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___
**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 [here](https://github.com/Expensify/App/pull/13767#issuecomment-1912514263) and [here](https://github.com/Expensify/App/pull/13767#issuecomment-1930624819)
**Slack conversation:**

## Action Performed:
Tap on any text input to open the keyboard, then navigate back. The flow that allowed to consistently reproduce this issue was:
- open the app
- navigate to a report
- press the ➕ next to the composer
- select `Assign task`
- write a task title
- press `Next` with the keyboard still open

## Expected Result:
The screen being navigated to should be filling the entire screen.

## Actual Result:
There is a blank space where the keyboard has been.

## Workaround:
Unknown, should be fixed by https://github.com/Expensify/App/pull/13767/commits/2894ec08ff66f944dfe18ac79acd7b1ecffa9b98 and https://github.com/Expensify/App/pull/13767/commits/39ef764b76e4bbd55d36eb7cfaadc20de330f9af

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<details>

https://github.com/Expensify/App/assets/21055725/45636cb5-16fd-4d64-a79f-9ee43a20edcd

https://github.com/Expensify/App/assets/21055725/e7eb00cf-e051-46f3-8fb3-69984e88e4e6

https://github.com/Expensify/App/assets/21055725/9f995ae9-2b50-4463-a7cd-9655ce6e54b0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1e03c65b6df0aca</li>
        <li>Upwork Job ID: 1768714492869853184</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Closing this one as the purpose of this issue is mainly for tracking and retest once the fabric PR hits staging
