### ISSUE TITLE
[HOLD PR #13767][$500] [New architecture] Screen flashes when dismissing a popover modal

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#36663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___
**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 [here](https://github.com/Expensify/App/pull/13767#issuecomment-1906886539)
**Slack conversation:**

## Action Performed:
- open any report
- tap on the three dots in the upper right corner
- tap on the `Pin` or `Unpin` option

## Expected Result:
The popover should close with a smooth animation

## Actual Result:
The popover closes causing screen flashing

## Workaround:
Unknown, should be fixed by https://github.com/Expensify/App/pull/13767/commits/27846dd7130c1f68bf808d88d499fd42f968ef9f

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<details>

https://github.com/Expensify/App/assets/21055725/c8428b65-5d28-4d5a-a7f2-4c8e22fbecc8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01229cd35e1df3c9b9</li>
        <li>Upwork Job ID: 1759305165281734656</li>
        <li>Last Price Increase: 2024-02-18</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Assuming, since this issue was created by @j-piasecki and they didn't assign to themselves, that we want this to be a _normal_ bug report. My guess is that it should be External, since the flash is on the front end (I think) so I'm creating a job for this.  Comment if you disagree @j-piasecki , we can add Vit back here for 👀, if needed (but I prefer not to, to not distract them).

**Comment by mallenexpensify** [comment]
Thanks for the context @ishpaul777 , should I put this on hold, pending https://github.com/Expensify/App/pull/13767 ? 

I removed External and Help Wanted labels.

**Comment by mallenexpensify** [comment]
Bumped to week. Assigned myself too for 👀.

**Comment by mallenexpensify** [comment]
Thanks @fedirjh and @ishpaul777 , put on hold.

**Comment by mallenexpensify** [comment]
on hold

**Comment by mallenexpensify** [comment]
- https://github.com/Expensify/App/pull/13767#pullrequestreview-1911523382

Lotta requested changes being worked on

**Comment by j-piasecki** [comment]
All issues will be tested for the new arch pr in staging
