### ISSUE TITLE
[New architecture] Emoji picker header keys are non-functional

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#36666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
- open a report
- tap emoji button in the composer
- tap on any emoji header in the selector

## Expected Result:
The emoji picker should scroll down to the tapped category

## Actual Result:
Nothing happens

## Workaround:
Unknown, should be fixed by https://github.com/Expensify/App/pull/13767/commits/84b6f6732e215c0e90ac1c9e73d29042d6239040

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>

https://github.com/Expensify/App/assets/21055725/e150411e-4a22-4407-93c2-4b8b906b2a33

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013dd0ccab4894c3db</li>
        <li>Upwork Job ID: 1768714480192651264</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
👋 @j-piasecki - I'm a little unclear on what we're expecting as a next step for this issue? @roryabraham are these held on something?

**Comment by roryabraham** [comment]
> not able to repro

All good, I think we should still test it once the New Arch is on staging

**Comment by mountiny** [comment]
discussed in this thread https://expensify.slack.com/archives/C02NK2DQWUX/p1710530036461539 going to close this and we should instruct the QA to retest all the New Architecture issues, opened or closed
