### ISSUE TITLE
[New architecture] Popover modals are not visible when opened

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#36662]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___
**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 [here](https://github.com/Expensify/App/pull/13767#issuecomment-1906886539) and [here](https://github.com/Expensify/App/pull/13767#issuecomment-1906599917)
**Slack conversation:**

## Action Performed:
Open a popover modal
- by clicking the FAB on the LHN
- by clicking the ➕ icon in the composer
- by pressing the photo icon in the Add receipt screen

## Expected Result:
The popover modal should appear

## Actual Result:
The backdrop is visible but the popover itself is not.

## Workaround:
Unknown, should be fixed by https://github.com/Expensify/App/pull/13767/commits/6816b93065f95d11b4c4d6e2a1b1c6d4f9bfb7de

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<details>
![popover1](https://github.com/Expensify/App/assets/21055725/1673a686-f3f0-4513-8c0b-65b4689284a4)

https://github.com/Expensify/App/assets/21055725/95cda1b4-663e-42ec-a965-5348c46f245a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d3bfa0df549c01f</li>
        <li>Upwork Job ID: 1768714498647588864</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
Just to be sure before I close, what "popover" are you referring to in the issue @ishpaul777 ?

**Comment by MitchExpensify** [comment]
> Just to be sure before I close, what "popover" are you referring to in the issue @ishpaul777 ?

bump @ishpaul777

**Comment by MitchExpensify** [comment]
Waiting on[ this PR](https://github.com/Expensify/App/pull/13767) to hit staging to test again

**Comment by MitchExpensify** [comment]
[PR](https://github.com/Expensify/App/pull/13767) hasn't hit staging yet to retest

**Comment by tgolen** [comment]
This issue is unassigned. Who is working on this and taking responsibility for it? @ishpaul777 would that be you or would it be @MitchExpensify ?

**Comment by tgolen** [comment]
Hm, but we don't keep around unassigned issues just for tracking purposes. If the problem has been fixed, and nothing is left to do, then I'm just going to close it. Thanks!
