### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] Scroll bar appears overlapping on the onboarding modal

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36677]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** [kiatest.80+0216@gmail.com](mailto:kiatest.80+0216@gmail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create new account either with Gmail or Expensifail domain
3. Scroll the onboarding modal

## Expected Result:
Scroll should display on the extreme right side of the modal

## Actual Result:
Scroll bar appears overlapping on the onboarding modal

Note : On Prod, scroll bar displayed on the extreme left side of the modal (please check screenshot attached)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e0ece193-5367-4838-a810-4f2d229aa7d9

![Bug6381586_1708067999569!Staging](https://github.com/Expensify/App/assets/115492554/b173f7dd-f9f0-4809-a48e-2b133d0ba5c9)
![Bug6381586_1708067877684!PROD](https://github.com/Expensify/App/assets/115492554/b2ab192b-6771-462d-8179-64493b24f902)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca2148015592295b</li>
        <li>Upwork Job ID: 1760741874670796800</li>
        <li>Last Price Increase: 2024-02-22</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>mkhutornyi | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Pujan92** [comment]
@mkhutornyi's [proposal](https://github.com/Expensify/App/issues/36677#issuecomment-1951350829) has correct RCA and solution. We should go with a general approach as I am also reproducing a similar issue https://github.com/Expensify/App/issues/33526 which gets closed. cc: @bfitzexpensify 

https://github.com/Expensify/App/assets/14358475/cf35b94a-10c9-4224-86af-e4d796a6bfbf

🎀👀🎀 C+ reviewed

**Comment by MariaHCD** [comment]
> We should go with a general approach

Agreed, looks like it's happening on more screens so a more general solution should be better here.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by Pujan92** [comment]
I am still able to reproduce for the Terms page and other similar issue raised [here](https://expensify.slack.com/archives/C049HHMV9SM/p1708699111235949) earlier.

https://github.com/Expensify/App/assets/14358475/e0ad102f-1e5e-4e7e-ac32-e18f8a50ba05

**Comment by MariaHCD** [comment]
Not overdue, pending PR from @mkhutornyi

**Comment by kevinksullivan** [comment]
Made payments, but please complete the checklist. Thanks!

**Comment by Pujan92** [comment]
Agree with @mkhutornyi , @kevinksullivan I think we don't need a checklist here as none of the PR has introduced this bug, and these edge case scenarios were there from the start which couldn't be consistently reproducible.

**Comment by MariaHCD** [comment]
I agree with the reasoning from @mkhutornyi and @Pujan92, there was no PR that caused a regression here and there's no need for a regression test - if this bug were to resurface, it would be noticed on any page that uses the scrollbar.
