### ISSUE TITLE
Login-Signing out & refreshing the login page, user is logged in again

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36675]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Using "G", login as gmail user
3. Tap profile icon
4. Tap sign out
5. Now refresh the login page immediately

## Expected Result:
Signing out and refreshing the login page, user must not be logged in again.

## Actual Result:
Signing out and refreshing the login page, user is logged in again.

The app with infinite loading home page is shown instead of login page on refresh.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b4751d9d-73f4-45f9-9082-cc76678bd4f4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave9-collect-signup
CC @MitchExpensify

**Comment by MitchExpensify** [comment]
Any ideas on this @francoisl ? Happy to loop into Wave 9

**Comment by francoisl** [comment]
Hm at first glance I don't think it's related to wave9. @hayata-suenaga is this the same thing you were looking into already and asking about [here](https://expensify.slack.com/archives/C03TQ48KC/p1707703570216299)?

**Comment by hayata-suenaga** [comment]
No I don't believe this is related to the issue I'm working on

I'm working on an issue where the user is logged out when they're not supposed

The issue described in this issue is happening probably because we're not clearing the auth cookie

**Comment by stephanieelliott** [comment]
Hm, I'm also not able to repro this. Gonna apply the label to have QA include this in the retest rotation, but if we can't repro it and we it's not tied to a wave perhaps we should close.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
