### ISSUE TITLE
[DEV/CI] Existing baseline artifacts not being reused in e2e testing pipeline

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#36685]
In the e2e performance regression testing pipeline we need to have a build of the current released version. The idea is that this build gets created once, gets uploaded as an artifact and later runs re-use the uploaded artifact.

However, this currently doesn't work.

[1. Here is a job that uploaded at 1:41 AM the baseline app:](https://github.com/Expensify/App/actions/runs/7909755479/job/21591431074)

![CleanShot 2024-02-16 at 13 28 34](https://github.com/Expensify/App/assets/16821682/2e8988cf-755e-40b7-acb6-50f172352a96)

2. [Then at 5:04AM, when another workflow runs it says it can't find the uploaded baseline app:](https://github.com/Expensify/App/actions/runs/7911292463/job/21595341093)

![CleanShot 2024-02-16 at 13 27 50](https://github.com/Expensify/App/assets/16821682/110d67a2-d6d1-40c0-bc3f-bfe2245932df)

This is not a single coincidence, but it happens all the time, and thus we need to rebuild the baseline apk for each e2e performance test run. Due to this the pipelines runs longer and GitHub runner resources are used unnecessarily.

The issue is due to the fact that artifacts can only be shared [**within the same workflow run**](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#about-workflow-artifacts) using the download/upload actions:
![CleanShot 2024-02-16 at 13 33 20](https://github.com/Expensify/App/assets/16821682/43e29b71-2477-4a8f-81bc-db252f0980c7)

**Comment by hannojg** [comment]
@mountiny @AndrewGable

**Comment by hannojg** [comment]
PR with a fix is up here:

- https://github.com/Expensify/App/pull/36686

**Comment by hannojg** [comment]
Slack convo here: https://expensify.slack.com/archives/C035J5C9FAP/p1708087576347399

**Comment by mountiny** [comment]
I belive this can be closed now
