### ISSUE TITLE
Android - When adding same emoji repeatedly from keypad, compose box shakens.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36684]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report
3. Using keypad, type same emoji repeatedly

## Expected Result: 
When adding same emoji repeatedly from keypad, compose box must not shaken.

## Actual Result:
When adding same emoji repeatedly from keypad, compose box shakens.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/30a73475-7e33-4077-b8bb-e1b88bbb38bb

https://github.com/Expensify/App/assets/115492554/b7beb0cf-e950-4ad7-a8df-795c9a1272e6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors



We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by slafortune** [comment]
Yep - this also, I think that adding the same emoji multiple times is something we need to account for since that isn't really actions we would expect users to take - and the actually outcome isn't the worst.
