### ISSUE TITLE
[New architecture] Keyboard flicker on money request participant selector when coming back from referral info page

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#36682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 [here](https://github.com/Expensify/App/pull/13767#issuecomment-1912514263)
**Slack conversation:**

## Action Performed:
- press FAB
- select `Send money`
- press the referral banner
- navigate back

## Expected Result:
The input field should be focused and the keyboard should be open.

## Actual Result:
The input field gets focused and blurred immediately, resulting in the keyboard flickering.

## Workaround:
Unknown, should be fixed by https://github.com/Expensify/App/commit/b43e3b8d69d2d980391c51bed01a1c845f6b8301

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
https://github.com/Expensify/App/assets/21055725/6c3bcadc-ff78-431e-af91-9187a1b0c966

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab5d181a0ac1db09</li>
        <li>Upwork Job ID: 1768714431602774016</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
@j-piasecki is this something you plan to fix yourself?

**Comment by j-piasecki** [comment]
@puneetlath Yes, together with @WoLewicki we're going to be working on all the New Architecture issues

**Comment by j-piasecki** [comment]
All issues will be tested for the new arch pr in staging
