### ISSUE TITLE
[New architecture] Bank flow is broken

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#36693]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 [here](https://github.com/Expensify/App/pull/13767#issuecomment-1930624819)
**Slack conversation:**

## Action Performed:
- open a report where money was requested
- tap on `Pay with Expensify`

## Expected Result:
Payment flow should start

## Actual Result:
App crashes

## Workaround:
Unknown, should be fixed by https://github.com/Expensify/App/pull/13767/commits/9d2f0d51b4cb32a83441f144979362cd8cd7cebc

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>

https://github.com/Expensify/App/assets/21055725/688c2b86-ef03-4ef5-a604-2d6ac11653bd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fad1d97b6ada392e</li>
        <li>Upwork Job ID: 1768714411807387648</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by j-piasecki** [comment]
I got the same message when running the App from the `main` branch, could you check whether it's the same case for you?

**Comment by lschurr** [comment]
@mountiny - should this be assigned to someone internally? Looks like I got unassigned maybe accidentally?

**Comment by mountiny** [comment]
@lschurr not for now I think this is related to a specific update being developed

@ishpaul777 @j-piasecki if this is repro in main, can you raise a bug report in expenify-bugs please?

**Comment by j-piasecki** [comment]
All issues will be tested for the new arch pr in staging
