### ISSUE TITLE
[New architecture] Sometimes the first click is being ignored

### ISSUE THREAD

**Issue by j-piasecki** [Expensify/App#36694]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 [here](https://github.com/Expensify/App/pull/13767#issuecomment-1930624819)
**Slack conversation:**

## Action Performed:
Tap on any pressable component

## Expected Result:
A relevant action is performed

## Actual Result:
The first tap is ignored

## Workaround:
Unknown, possibly fixed by https://github.com/Expensify/App/pull/13767/commits/39ef764b76e4bbd55d36eb7cfaadc20de330f9af#diff-126b1e66aaadb5befe3cae2373fcf40185d23c6513041654637b664beb4c5e98R141

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>

https://github.com/Expensify/App/assets/21055725/d7b6d6e8-de9b-44ff-adfc-220c57e8cb6f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d077d6d390741cb</li>
        <li>Upwork Job ID: 1768714403736559616</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Closing this one as the purpose of this issue is mainly for tracking and retest once the fabric PR hits staging
