### ISSUE TITLE
[$500] mWeb - IOU - You have to grant permission every time you open the scan tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36690]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to FAB - Request money (Make sure that the manual tab opens)
2. Tap on the Scan tab
3. Allow access
4. Tap on the Manual tab
5. Close Safari
6. Open Expensify again and navigate to the Scan tab

## Expected Result:
It shouldn't ask if I allowed it once already.

## Actual Result:
You have to grant permission every time you open the scan tab.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/50e6558c-6613-4989-ae6c-42695ad90095

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164a73cce37252564</li>
        <li>Upwork Job ID: 1765505497526599680</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-split-p2p-chat-groups
CC @gabrielessner

**Comment by adelekennedy** [comment]
back from ooo

**Comment by adelekennedy** [comment]
I'v having a separate issue - I open the scan tab and after allowing permission the camera view is blank (just the lighter green background square)

**Comment by izarutskaya** [comment]
This issue is still reproducible. 
Build 1.4.44-0

https://github.com/Expensify/App/assets/115492554/314a8037-0972-4983-a012-0f6595f51861

**Comment by adelekennedy** [comment]
we're in flux with our slack channels so going to post this in the new wave collect room next week - I think this is related to wave 5

**Comment by adelekennedy** [comment]
I think this is a polish but not actually blocking any release - low priority

**Comment by abzokhattab** [comment]
as per [this stackoverflow question](https://stackoverflow.com/questions/48847388/how-to-permanently-allow-usage-of-camera-on-trusted-websites-with-ios-safari)   it seems that Safari does not have an option to permanently save user choice (Cancel | Allow) for camera usage

**Comment by adelekennedy** [comment]
ah -let's close this for now then
