### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Cancel payment - No red dot in expense preview in main chat when payment cancellation fails

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Admin and member are in the same free workspace.
- Admin and member have bank account set up.
1. [Member] Go to workspace chat.
2. [Member] Create a manual request.
3. [Admin] Pay the request with Expensify.
4. [Admin] Go to expense report > 3-dot menu > Cancel payment.
5. [Admin] Cancel the payment.
6. [Admin] Return to the main chat without dismissing the error.

## Expected Result:
The expense preview in the main chat will display red dot.

## Actual Result:
The expense preview in the main chat does not display red dot.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0a8e4e11-ed67-4f90-a1c8-968aa5974820

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a0ba8089a65a1dd</li>
        <li>Upwork Job ID: 1758487283174920192</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by youssef-lr** [comment]
I think this will be fixed [here](https://github.com/Expensify/App/pull/36631) cc @Gonals

**Comment by Gonals** [comment]
> I think this will be fixed [here](https://github.com/Expensify/App/pull/36631) cc @Gonals

Yep. That should fix this. Self-assigning 😁
