### ISSUE TITLE
[HOLD for payment 2024-02-26] [$500] Cancel payment - "Next step" does not update after cancelling payment until page is refreshed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** New Feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are in Collect workspace.

1. [Employee] Go to workspace chat.
2. [Employee] Create a money request and submit it.
3. [Admin] Pay elsewhere the request.
4. [Admin] Go to expense report.
5. [Admin] Cancel the payment.

## Expected Result:
"Next step" message will automatically update after the payment is cancelled.

## Actual Result:
"Next step" message does not update after cancelling the payment until the page is revisited.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/6798d560-11af-4360-8b65-47a66c9f54b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c18b3226de5d7de</li>
        <li>Upwork Job ID: 1758514115060043776</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We think this might be related to #wave5-free-submitters
cc @dylanexpensify

**Comment by shahinyan11** [comment]
@m-natarajan What means the `Collect workspace`.  There is not a submit button in IOU preview ? Please provide more detailed steps

**Comment by amyevans** [comment]
"Cancel" was a new feature implemented in https://github.com/Expensify/App/pull/34719 - @Gonals mind tackling this one please? Looks like `CancelPayment` needs some `reportNextStep` Onyx data

**Comment by Gonals** [comment]
> "Cancel" was a new feature implemented in #34719 - @Gonals mind tackling this one please? Looks like `CancelPayment` needs some `reportNextStep` Onyx data

Seems like it! Taking a look!

**Comment by Gonals** [comment]
> * [CP Staging] Update nextStep on payment cancellation #36798

It was fixed internally [here](https://github.com/Expensify/App/pull/36798), yep

**Comment by isabelastisser** [comment]
Thanks @Gonals! All set, closing.
