### ISSUE TITLE
[Payment Due 18 March] [$500] Cancel payment - Cancellation is not updated in real time when it is not the latest request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #[34719](https://github.com/Expensify/App/pull/34719)
**Version Number:**  1.4.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** New feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. [Member] Request money in workspace chat.
2. [Admin} Pay elsewhere the request.
3. [Admin] Cancel the payment.
4. Note that the payment cancellation is updated in real time for Member.
5. [Admin] Pay the request again.
6. [Member] Create a second request.
7. [Admin} Pay elsewhere the second request.
8. [Admin] Go to the first paid request report in Step 2.
9. [Admin] Cancel the payment.

## Expected Result:
The payment cancellation will be updated for Member in real time.

## Actual Result:
The payment cancellation is not updated in real time for Member when the cancelled payment is not the latest request.
It is only updated when the page is refreshed.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/439e7823-b3c6-4803-b88f-bc585003d744

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e56b494e59933461</li>
        <li>Upwork Job ID: 1758506999222018048</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Gonals</details>

**Comment by m-natarajan** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this might be related to #wave5-free-submitters
cc @dylanexpensify

**Comment by pecanoro** [comment]
Ok, I was able to reproduce. Let me find who implemented this functionality since it's a new feature so we can get some context.

**Comment by pecanoro** [comment]
It's coming from this https://github.com/Expensify/App/pull/34719. It is probably caused because we are forgetting to send some pusher events to the submitter when cancelling the request or sending the wrong one.

**Comment by Gonals** [comment]
> It's coming from this #34719. It is probably caused because we are forgetting to send some pusher events to the submitter when cancelling the request or sending the wrong one.

Yep. That's likely it. I don't think we need to block/revert on this, as it is a backend issue, and not very problematic. I'll work on a fix today, though

**Comment by Beamanator** [comment]
I agree with calling this NAB

**Comment by Gonals** [comment]
I'm actually not able to reproduce this. The message is getting updated in real time for me. @m-natarajan, can you give it another shot?

**Comment by laurenreidexpensify** [comment]
Posted - https://expensify.slack.com/archives/C9YU7BX5M/p1708590138119879

**Comment by kavimuru** [comment]
@laurenreidexpensify @pecanoro 

There is one step is missing in the OP. Edited the OP and updating here too. Issue is still reproducible.

1. [Member] Request money in workspace chat.
2. [Admin} Pay elsewhere the request.
3. [Admin] Cancel the payment.
4. Note that the payment cancellation is updated in real time for Member.
5.` [Admin] Pay the request again.` This step was missing in the OP
6. [Member] Create a second request.
7. [Admin} Pay elsewhere the second request.
8. [Admin] Go to the first paid request report in Step 2.
9. [Admin] Cancel the payment.


https://github.com/Expensify/App/assets/43996225/31ac8586-4b5f-43c9-b42e-bcc5326e33e4

**Comment by Gonals** [comment]
I'll take another look on Monday!

**Comment by Gonals** [comment]
Things got in the way. I'll retest this tomorrow!

**Comment by Gonals** [comment]
Ok, I `think` I have been able to reproduce. Investigating

**Comment by Gonals** [comment]
> Ok, I `think` I have been able to reproduce. Investigating

The reportAction does get updated correctly. It is just the IOU preview that fails to update automatically

**Comment by laurenreidexpensify** [comment]
This is on staging

**Comment by laurenreidexpensify** [comment]
On prod now, let's pay this on 18 March

**Comment by jjcoffee** [comment]
Unassigning as no C+ was required here.
