### ISSUE TITLE
[HOLD for payment 2024-03-07] Bump eslint-config-expensify version in E/App

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#36718]
Following up on https://github.com/Expensify/eslint-config-expensify/pull/85, let's bump the eslint-config-expensify version in E/App to 2.0.44+ and remove any redundant rules.

**Comment by roryabraham** [comment]
self-assigning for tracking purposes

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
[PR](https://github.com/Expensify/App/pull/36849) is ready for C+ review

**Comment by jjcoffee** [comment]
Per [this comment](https://github.com/Expensify/App/issues/36718#issuecomment-1948921323), I guess C+ review isn't required?

**Comment by jjcoffee** [comment]
@roryabraham Friendly bump on [this question](https://github.com/Expensify/App/issues/36718#issuecomment-1954207408). :bow:

**Comment by roryabraham** [comment]
PR merged.

**Comment by roryabraham** [comment]
@jjcoffee to answer your question, yes I think C+ review is needed here. There are enough non-trivial changes that I think it's valuable in this case

**Comment by jjcoffee** [comment]
I am due payment for the PR review on this. :bow:

**Comment by jjcoffee** [comment]
@roryabraham Would you mind adding the `Bug` label so a BZ gets assigned to issue payment? Thanks! :pray:

**Comment by situchan** [comment]
No payment for me. I just pointed out regression in PR.

**Comment by MitchExpensify** [comment]
Fixed, thanks!

**Comment by MitchExpensify** [comment]
Offer here for you @jjcoffee https://www.upwork.com/jobs/~014f452ce3ae379cd2

**Comment by situchan** [comment]
Just for reference: the regression penalty won't be applied in these kinds of issues?

**Comment by MitchExpensify** [comment]
Where were the related regressions @situchan ?

**Comment by situchan** [comment]
> Where were the related regressions @situchan ?

yes, https://github.com/Expensify/App/issues/37465#issuecomment-1970337225

**Comment by jjcoffee** [comment]
@MitchExpensify Accepted, thanks!

**Comment by MitchExpensify** [comment]
Updated the payment summary to $250 because of the regression here https://github.com/Expensify/App/issues/37465#issuecomment-1970337225

**Comment by MitchExpensify** [comment]
Paid and contract ended!
