### ISSUE TITLE
[HOLD for payment 2024-03-22] [$250] [TS migration] Migrate `VideoPlayerContexts ` component files to TypeScript

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#36724]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files related to the `VideoPlayerContexts` component

- [src/components/VideoPlayerContexts/PlaybackContext.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayerContexts/PlaybackContext.js)
- [src/components/VideoPlayerContexts/VideoPopoverMenuContext.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayerContexts/VideoPopoverMenuContext.js)
- [src/components/VideoPlayerContexts/VolumeContext.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayerContexts/VolumeContext.js)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01981a2129abb4828c</li>
        <li>Upwork Job ID: 1758559484183658496</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by MahmudjonToraqulov** [comment]
Would like to work on it.

**Comment by EnderKilledYou** [comment]
## Proposal
Update the Video player component to type script following the style guide.

### Please re-state the problem that we are trying to solve in this issue.

We want uniform language throughout the app.

### What is the root cause of that problem?

Files are not in type script

### What changes do you think we should make in order to solve the problem?

Change them to typescript

### What alternative solutions did you explore? (Optional)
Maybe changing them to blazor.

**Comment by Koustubh-lapate** [comment]
I am Koustubh, a full stack developer. I’d like to work on this job.

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this issue.

**Comment by smelaa** [comment]
Hello! I'm Aleksandra Smela from Software Mansion, the expert agency and I would like to work on this issue.

**Comment by hayata-suenaga** [comment]
@smelaa please mark the PR ready for review once it's ready 🙇

**Comment by hayata-suenaga** [comment]
@bfitzexpensify 

needs payment for @eVoloshchak who is a C+ who reviewed the TypeScript migration PR. The PR author is an expert agency engineer and no need for payment

**Comment by bfitzexpensify** [comment]
Payment summary: 

@eVoloshchak to be paid $250 via manual request
@smelaa does not require payment (contractor)

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak.
