### ISSUE TITLE
[$250] [TS migration] Migrate `VideoPlayerControls` and `VideoPopoverMenu` component files to TypeScript

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#36723]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files related to the `VideoPlayerControls` and `VideoPopoverMenu` components

- [src/components/VideoPlayer/VideoPlayerControls/index.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayer/VideoPlayerControls/index.js)
- [src/components/VideoPlayer/VideoPlayerControls/ProgressBar/index.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayer/VideoPlayerControls/ProgressBar/index.js)
- [src/components/VideoPlayer/VideoPlayerControls/VolumeButton/index.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayer/VideoPlayerControls/VolumeButton/index.js)
- [src/components/VideoPopoverMenu/index.js](https://github.com/Expensify/App/blob/main/src/components/VideoPopoverMenu/index.js)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b85f928413973c4</li>
        <li>Upwork Job ID: 1758559473458262016</li>
        <li>Last Price Increase: 2024-02-16</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by muas19** [comment]
Can work on this

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by Tony-MK** [comment]
Could I work on this migration?

**Comment by Solowave** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Change files to typescript instead of javascript, and add type safety.

### What is the root cause of that problem?

Files were written in javascript, need to change to typescript.

### What changes do you think we should make in order to solve the problem?

Change files to [.ts] and interfaces and types for all necessary variables, functions, and parameters.

**Comment by Solowave** [comment]
Contributor details
Your Expensify account email: tsemeraro05@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01af68b88d54bcd60a

**Comment by Koustubh-lapate** [comment]
I am Koustubh, a full stack developer. I’d like to work on this job.

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this issue.

**Comment by situchan** [comment]
@hayata-suenaga please assign @kowczarz

**Comment by kowczarz** [comment]
Hey, I'm leaving the Expensify-SWM team for now and @smelaa will handle this task.

**Comment by smelaa** [comment]
Hello! I'm Aleksandra Smela from Software Mansion, the expert agency and I would like to work on this issue.

**Comment by hayata-suenaga** [comment]
we don't have to hire smelaa. They're from SWM.

**Comment by hayata-suenaga** [comment]
we don't have to hire smelaa. They're from SWM.

**Comment by daksh4469** [comment]
Hi! I would like to work on this, if this issue is not handled by someone already. Thanks!

**Comment by daksh4469** [comment]
Also, could someone guide me on how to interact with the contributors community? In the Contributing.md doc, it's mentioned that I have to send a mail to [contributors@expensify.com](mailto:contributors@expensify.com) with `Slack Channel Invites` as the subject. I have done so multiple times, but have received no response. 

It would be great if someone could help me out.

Thanks!

**Comment by hayata-suenaga** [comment]
@daksh4469 thank you for your interests in contributing to the Expensify community!

I'll check your email. Meanwhile, please don't post proposals to the issue until you're approved to join the community 🙇 

Also, there are certain formats and rules when posting proposals. Please review the contributor guidelines 🙇

**Comment by daksh4469** [comment]
@hayata-suenaga Got it! Thanks a lot 😄

**Comment by hayata-suenaga** [comment]
@daksh4469 I checked the email. I see you first emailed us last Friday. Please understand that internal employees take weekends. We kindly ask your patience while a person responsible for approving invite requests handle your case 🙇

**Comment by daksh4469** [comment]
Yeah, sincere apologies...

**Comment by daksh4469** [comment]
Hi! I'm now approved in the community. I'd like to work on this issue. 

Can I post a proposal for this now?🙇🏻‍♂️ @hayata-suenaga

**Comment by hayata-suenaga** [comment]
for this particular issue, it's already taken. Please review the contribution guideline and find other open issues 🙇

**Comment by situchan** [comment]
PR is in draft

**Comment by hayata-suenaga** [comment]
PR isin draft

**Comment by situchan** [comment]
Same ^

**Comment by hayata-suenaga** [comment]
The PR has been merged. Please handle payment for @situchan for C+ review work

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor+: $250 @situchan (NewDot)

**Comment by situchan** [comment]
@adelekennedy I am still using upwork
