### ISSUE TITLE
[HOLD for payment 2024-03-22] [HelpDot] Margins for Info box 

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#36720]
Info box looks cramped because it doens't have margin below it.

<img width="1004" alt="image" src="https://github.com/Expensify/App/assets/29673073/391d7afd-427e-4f32-bb84-c77ca89acb00">

**Comment by rushatgabhane** [comment]
just a tracking issue

**Comment by hayata-suenaga** [comment]
@dubielzyk-expensify please see [this comment](https://github.com/Expensify/App/pull/36721#issuecomment-1952858572)

**Comment by dubielzyk-expensify** [comment]
Replied 👍

**Comment by dubielzyk-expensify** [comment]
Anything needed from me on this?

**Comment by rushatgabhane** [comment]
no we can close the issue.
