### ISSUE TITLE
[New architecture] Calendar picker is invisible

### ISSUE THREAD

**Issue by WoLewicki** [Expensify/App#36729]
If you haven't already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This issue is related to the ongoing new architecture adoption. It was reported on the build with new architecture enabled on the [relevant PR](https://github.com/Expensify/App/pull/13767).
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 [here](https://github.com/Expensify/App/pull/13767#issuecomment-1906599917)
**Slack conversation:**

## Action Performed:
Break down in numbered steps

## Expected Result:
Calendar is visible

## Actual Result:
Calendar is not visible

## Workaround:
Fixed by [`c33a4ee` (#13767)](https://github.com/Expensify/App/pull/13767/commits/c33a4eedaa14c9fd3d18f0b661f1e880ef2a4efd)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Available in the linked comment.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Will be tested once the PR is deployed.
