### ISSUE TITLE
[$250] [TS migration] Migrate `VideoPlayerPreview` component files to TypeScript

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#36725]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### File related to the `VideoPlayerPreview` component

- [src/components/VideoPlayerPreview/index.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayerPreview/index.js)
- [src/components/VideoPlayerPreview/VideoPlayerThumbnail.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayerPreview/VideoPlayerThumbnail.js) 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee4768426d2275b1</li>
        <li>Upwork Job ID: 1758559492550733824</li>
        <li>Last Price Increase: 2024-02-16</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>situchan | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by MahmudjonToraqulov** [comment]
Would like to work on it.

**Comment by Koustubh-lapate** [comment]
I am Koustubh, a full stack developer. I’d like to work on this job.

**Comment by aneequeahmad** [comment]
I would like to work on this issue. I'm not being assigned any TS related issues.

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this issue.

**Comment by hkopser99** [comment]
Hi @hayata-suenaga, I just completed my first TS migration for the Expensify project (approved PR [here](https://github.com/Expensify/App/pull/35890)) and am ready to take on another if this is not yet assigned. Please let me know :)

**Comment by hayata-suenaga** [comment]
@ntdiary when you have time, could you confirm that the first person who commented doesn't have any other TS migration assigned and then comment C+ selection message?

**Comment by kowczarz** [comment]
Hey, I'm leaving the Expensify-SWM team for now and @smelaa will handle this task.

**Comment by smelaa** [comment]
Hello! I'm Aleksandra Smela from Software Mansion, the expert agency and I would like to work on this issue.

**Comment by hayata-suenaga** [comment]
> The BZ member will need to manually hire smelaa for the Contributor role. Please store your Upwork details and apply to our Upwork job so this process is automatic in the future!

No need to hire smelaa. They're from Software Mansion, one of the expert agencies.

**Comment by hayata-suenaga** [comment]
Aleksandra is going to open a PR

**Comment by hayata-suenaga** [comment]
melvin, the draft PR is made.

**Comment by hayata-suenaga** [comment]
PR is still draft

**Comment by hayata-suenaga** [comment]
PR is still in draft

**Comment by hayata-suenaga** [comment]
PR is still in draft

**Comment by hayata-suenaga** [comment]
PR is still in draft

**Comment by grgia** [comment]
We only need one C+ for the PR so I am removing C+ here to track payments

**Comment by hayata-suenaga** [comment]
[The PR was been merged a while ago](https://github.com/Expensify/Expensify/issues/290295)

The only thing left to do is for the payment for the C+ review role for @situchan. @situchan is OOO for April, so I'll changing the priority of this issue to monthly

**Comment by blazejkustra** [comment]
What are the next steps here? Should we close this issue?

**Comment by situchan** [comment]
I am back

**Comment by hayata-suenaga** [comment]
@greg-schroeder, please pay @situchan for the C+ review role for [this PR](https://github.com/Expensify/App/pull/37425)

**Comment by greg-schroeder** [comment]
Oops, sorry, missed [this comment](https://github.com/Expensify/App/issues/36725#issuecomment-2125909700) -- looking now

**Comment by greg-schroeder** [comment]
Paid
