### ISSUE TITLE
[hold for payment 2024-04-17] [$250] [TS migration] Migrate `VideoPlayer` component files to TypeScript

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#36722]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files related to `VideoPlayer` component
- [src/components/Attachments/AttachmentView/AttachmentViewVideo/index.js](https://github.com/Expensify/App/blob/main/src/components/Attachments/AttachmentView/AttachmentViewVideo/index.js)
- [src/components/VideoPlayer/propTypes.js](https://github.com/Expensify/App/blob/1f5e0ba30854410e8970d428f30d28a666648896/src/components/VideoPlayer/propTypes.js)
- [src/components/VideoPlayer/index.js](https://github.com/Expensify/App/blob/1f5e0ba30854410e8970d428f30d28a666648896/src/components/VideoPlayer/index.js)
- [src/components/VideoPlayer/index.native.js](https://github.com/Expensify/App/blob/1f5e0ba30854410e8970d428f30d28a666648896/src/components/VideoPlayer/index.native.js)
- [src/components/VideoPlayer/IconButton.js](https://github.com/Expensify/App/blob/main/src/components/VideoPlayer/IconButton.js)
- [src/components/VideoPlayer/BaseVideoPlayer.js](https://github.com/Expensify/App/blob/1f5e0ba30854410e8970d428f30d28a666648896/src/components/VideoPlayer/BaseVideoPlayer.js)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f4d6dc2e2fed5bb</li>
        <li>Upwork Job ID: 1758559462761594880</li>
        <li>Last Price Increase: 2024-02-16</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by muas19** [comment]
Would like to work on it

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by Tony-MK** [comment]
Could I work on this issue?

**Comment by Koustubh-lapate** [comment]
I am Koustubh, a full stack developer. I’d like to work on this job.

**Comment by kowczarz** [comment]
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this issue.

**Comment by jjcoffee** [comment]
@hayata-suenaga Do I need to select a contributor here or are these ones for agencies?

**Comment by hayata-suenaga** [comment]
@jjcoffee @kowczarz is going to work on this 👍

**Comment by kowczarz** [comment]
Hey, I'm leaving the Expensify-SWM team for now and @smelaa will handle this task.

**Comment by smelaa** [comment]
Hello! I'm Aleksandra Smela from Software Mansion, the expert agency and I would like to work on this issue.

**Comment by smelaa** [comment]
Contributor details
Your Expensify account email: aleksandra.smela@swmansion.com

**Comment by hayata-suenaga** [comment]
we don't have to hire smelaa. They're from SWM.

**Comment by hayata-suenaga** [comment]
@smelaa is going to work on this

**Comment by hayata-suenaga** [comment]
melvin, the draft PR is made.

**Comment by hayata-suenaga** [comment]
the PR is still draft

**Comment by hayata-suenaga** [comment]
the PR is still in draft.

**Comment by hayata-suenaga** [comment]
the PR is still in draft.

**Comment by hayata-suenaga** [comment]
the PR is still in draft.

**Comment by joekaufmanexpensify** [comment]
PR deployed to prod. Any payment is due in 2 days (2024-04-17)

**Comment by joekaufmanexpensify** [comment]
Only payment here is $250 to @jjcoffee for C+ review via upwork

**Comment by joekaufmanexpensify** [comment]
All set. Thanks everyone!
