### ISSUE TITLE
[CRITICAL] [Splits] Show `Split bill` in global create, separate out the split and request flows 

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#36748]
# [DESIGN DOC](https://docs.google.com/document/d/1Z0V68fpdUhx21bsmX-DV0zXx0-w-kRIO00Wpblac9AU/edit)

# Problem

As it's been discussed in this [thread](https://expensify.slack.com/archives/C03U7DCU4/p1695951129311129) and elsewhere, our approach to merging both split and request into a single flow is very confusing, for a few reasons:

1. It makes seem like you have to split a request with someone, when in reality the more common flow is requesting money from one person
2. It's not clear that there is a path to requesting "normally", which can be done by tapping the row outside of the split button. This means each row has two very different possible actions, but only one is visible in the UI

We've had 10+ people at our company mention this as a point of confusion when requesting money from friends or while testing the Collect experience as a member requesting repayment from a workspace.

# Solution
Let's address this problem by:
1. Bringing back a dedicated `Split bill` option within global create, under the `Request money` option. This will help us differentiate between the flows, and promote a use case we want users to be aware of.

<img width="378" alt="image" src="https://github.com/Expensify/App/assets/22508290/e4ed9c77-6e90-4c21-836d-21b79a4a61ea">

2. Removing the "split" button from the request money flow

### Outstanding considerations

Going to jot down a few thoughts on this one here, just so I have it written down. 

**How should the split bill flow work for making a single selection v. multi-selection?**

<img width="409" alt="image" src="https://github.com/Expensify/App/assets/22508290/81b5e4b3-aa89-4702-baaa-024fc549a7b4">

We have a few options that I can think of, and likely many others: 

1. Making any selection go straight to the 1:1 confirmation screen,  and then showing a `+` icon on the confirmation screen, as shown [here](https://expensify.slack.com/archives/C03U7DCU4/p1707429457923829?thread_ts=1695951129.311129&cid=C03U7DCU4)). 
2. Keep it similar today, where the button says something like `Add to split` for split, and  and tapping that option supports multi-select, or tapping outside of the button goes straight to the 1:1 confirmation screen (doesn't address the problem of one row two actions)
3. Anytime a user makes a selection, showing `Continue`, before landing them on the confirmation screen, making it clear you can select multiple users. This makes the 1:1 split flow less efficient, but I think that is going to be a pretty rare flow if we have a dedicated request flow. 

**Should the Request money flow allow for adding multiple people to a request?**

Today we don't allow requesting money from multiple people at once. It has to go through the split flow. So, do we want to change that? I'm on the fence. I've long used venmo to send requests to a bunch of people at once. But now, they've essentially baked that into a split flow, and I can see a pretty clear case for not needing it at all. 

### Implementation

Implementation issues created, will be implemented in the following order:
1. External https://github.com/Expensify/App/issues/40070 @shubham1206agra @getusha 
1. External https://github.com/Expensify/App/issues/40071 @getusha @shubham1206agra 
2. Internal https://github.com/Expensify/App/issues/40072 @mountiny 
3. External https://github.com/Expensify/App/issues/40073 @shubham1206agra @getusha 
4. External https://github.com/Expensify/App/issues/40074 @shubham1206agra @getusha 
5. Internal https://github.com/Expensify/App/issues/40075 @mountiny

**Comment by kevinksullivan** [comment]
posted this ^ as a quick pre-design

**Comment by shawnborton** [comment]
@kevinksullivan let me know when and where I can help with this. Maybe we just need to see how the pre-design settles first and then we can create final mocks from there?

**Comment by kevinksullivan** [comment]
pre-design went out [here](https://expensify.slack.com/archives/C05RECHFBEW/p1708127822732439). Next step I think we follow up with an option that show's option 3 from the pre-design in more detail than I presented it, then we can explore a mini-doc or just GH it. @shawnborton what do you think?

**Comment by shawnborton** [comment]
Posted some ideas for ya [here](https://expensify.slack.com/archives/C05RECHFBEW/p1708654516096499?thread_ts=1708653037.513229&cid=C05RECHFBEW).

**Comment by kevinksullivan** [comment]
Working on the doc

**Comment by arielgreen** [comment]
I have read and reviewed this Design Doc!

**Comment by jamesdeanexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by maddylewis** [comment]
I have read and reviewed this Design Doc!

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by MarcFillari** [comment]
I have read and reviewed this Design Doc!

**Comment by shawnborton** [comment]
Not overdue, but what are the next steps here @kevinksullivan ?

**Comment by kevinksullivan** [comment]
Doc was on hold for some broader discussions, but we're back in review mdode!

**Comment by rafecolton** [comment]
I have read and reviewed this Design Doc!

**Comment by danielrvidal** [comment]
I have read and reviewed this Design Doc!

**Comment by saracouto** [comment]
I have read and reviewed this Design Doc!

**Comment by nkuoch** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
I have read and reviewed this Design Doc!

**Comment by shawnborton** [comment]
Not overdue, we're still in review mode.

**Comment by MonilBhavsar** [comment]
I have read and reviewed this Design Doc!

**Comment by isabelastisser** [comment]
I have read and reviewed this Design Doc!

**Comment by nkuoch** [comment]
I have read and reviewed this Design Doc!

**Comment by trjExpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by jliexpensify** [comment]
I have read and reviewed this Design Doc!

**Comment by amyevans** [comment]
I have read and reviewed this Design Doc!

**Comment by quinthar** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
Implementation issues created, will be implemented in the following order:
1. External https://github.com/Expensify/App/issues/40070 @shubham1206agra @getusha 
1. External https://github.com/Expensify/App/issues/40071 @getusha @shubham1206agra 
2. Internal https://github.com/Expensify/App/issues/40072 @mountiny 
3. External https://github.com/Expensify/App/issues/40073 @shubham1206agra @getusha 
4. External https://github.com/Expensify/App/issues/40074 @shubham1206agra @getusha 
5. Internal https://github.com/Expensify/App/issues/40075 @mountiny

**Comment by pecanoro** [comment]
I have read and reviewed this Design Doc!

**Comment by grgia** [comment]
I have read and reviewed this Design Doc!

**Comment by mountiny** [comment]
Daily updates in the vip-split room. We are chugging along well to meet the Release 1 deadline

**Comment by shawnborton** [comment]
I see this one is implemented in the product already, right?

**Comment by kevinksullivan** [comment]
Yes, this is live! I'd say we can close this out. @mountiny lmk if you think differently!
