### ISSUE TITLE
Include build artifacts on GH releases for all deploys

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#36758]
### Problem
Sometimes, such as [for upgrades](https://expensify.slack.com/archives/C9YU7BX5M/p1708109799820299?thread_ts=1708103233.932099&cid=C9YU7BX5M), or when searching for the source of a regression, we want to test a old version(s) of our app, but we currently don't provide an easy way to do that.

### Solution (part 1)
Include build artifacts on all our GitHub releases:

- The `.dmg` for the desktop app
- The APK for the Android app
- The AAP for the iOS app

source code is already included.

### Solution (part 2)
Currently our deploy paradigm is:

    - 1 tag == 1 staging deploy
    - 1 release == 1 production deploy

We should update it such that it's:

    - 1 prerelease == 1 staging deploy
    - 1 release == 1 production deploy
    
That way we have historical artifacts from all our deploys, not just production deploys.

<details><summary>Issue Owner</summary>Current Issue Owner: @roryabraham</details>

**Comment by roryabraham** [comment]
Pretty low priority, but also should be pretty easy (part 1, anyways). Saving this for a rainy day

**Comment by roryabraham** [comment]
Two things are on HOLD for this, so I'm going to bump the priority and try to get it out sometime this week.

**Comment by roryabraham** [comment]
this isn't a product feature but a development/QA testing feature

**Comment by mallenexpensify** [comment]
@roryabraham let me know if I can help 'spread the word' when this is done. ie. SO, post/pin in #expensify-open-source.

**Comment by roryabraham** [comment]
yeah, that'd be helpful

**Comment by roryabraham** [comment]
co-assigning you here but making myself the issue owner for the time being

**Comment by mallenexpensify** [comment]
Not a high priority, Rory will get to soon (curious if my commenting will remove overdue if you're the owner Rory)

**Comment by roryabraham** [comment]
prioritizing a few other things over this

**Comment by mallenexpensify** [comment]
@roryabraham I removed `NewFeature` and added `Improvement` because we're moving all bugs and feature requests to projects and I couldn't think of where this would best fit on our roadmap

**Comment by mallenexpensify** [comment]
Rory has to comment for it to not be overdue

**Comment by roryabraham** [comment]
Yeah, I'm not sure where this fits in the roadmap, but I do think it's an important improvement that will allow us to better test and monitor the app upgrade process

**Comment by roryabraham** [comment]
No update - was focused on more urgent issues.

**Comment by roryabraham** [comment]
Critical reliability issues taking precedence. Mostly https://github.com/Expensify/App/issues/41254

**Comment by roryabraham** [comment]
Put up a PR for part 1: https://github.com/Expensify/App/pull/45364

**Comment by roryabraham** [comment]
First part is done, and I'm actually going to call this done-done. We will now be able get the release artifacts for every deploy (after one more full deploy cycle happens).

To get release artifacts for production deploys, just go to https://github.com/Expensify/App/releases, find the release you want, and look at `Assets`.

To get release artifacts for staging deploys, go to https://github.com/Expensify/App/actions/workflows/platformDeploy.yml, click on the workflow run for the version you're looking for, and the release artifacts will be there at the bottom.

It's worth noting that release artifacts for staging deploys won't be stored forever, but AFAIK release artifacts for production deploys will be. I think that's _probably_ fine, and fixing it by completing the 2nd half of this issue would be an order of magnitude harder than completing the first half was.

**Comment by mallenexpensify** [comment]
oooh, neat!  I created [this SO](https://stackoverflowteams.com/c/expensify/questions/19738) and asked ya.  Seems like something we want documented and I wasn't able to find anything when I searched.  Can you also share deets in #expensify-open-source and pin the post? (or... I'll do so once you've updated the SO).

**Comment by roryabraham** [comment]
answered in SO
