### ISSUE TITLE
[No BZ] Warn developers if they upgrade a dependency but not a patch

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#36776]
Coming from https://github.com/Expensify/App/pull/36775...

### Problem
When upgrading dependencies, it's possible that you may break a patch for that dependency. It's also possible that the patch may no longer be needed. It's easy to forget this, which leaves unused patch files in our repo.

### Solution
Add a simple PR check to our webhook that looks for PRs that upgrade a dependency with a patch without updating the patch and include a PR comment like:

> Heads up! It looks like you updated a dependency without updating the patch. Do you need to update the patch?
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019999ca1782dc1db6</li>
        <li>Upwork Job ID: 1759309916923375616</li>
        <li>Last Price Increase: 2024-02-18</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
I was thinking this should be internal like other similar-style warnings in our webhook. Don't need a C+, not sure why we assign them for issues labelled `Internal`...

**Comment by roryabraham** [comment]
Some notes:

- We should split up `commentIfPatchFileDiffers` into `commentIfPackageJsonUpdated` and `commentIfComposerJsonUpdated`
- We should create constants for `REPOS_WITH_PACKAGE_JSON` and `REPOS_WITH_COMPOSER_JSON`
- We need to do some json parsing of the `package.json` diff to see which dependencies were updated so we can check for patches in that specific dependency

**Comment by roryabraham** [comment]
No near-term plans to push this DX improvement forward. Going to drop for focus

**Comment by mallenexpensify** [comment]
Updated title to denote this `NewFeature` doesn't need a BZ assigned.

**Comment by roryabraham** [comment]
This also isn't really in the roadmap anywhere - it's more of an automation to prevent developer mistakes

**Comment by roryabraham** [comment]
This was quick and easy to implement, and failing to correctly update our patches can lead to headaches. It's all-too-common for patches to be added with limited context and then basically left forever, so hopefully this should help curb that practice.

**Comment by roryabraham** [comment]
oh, this has been done for a while 🙈
