### ISSUE TITLE
[Payment due March 7] [Performance] Remove cache from the getOrderedReportIDs method

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#36799]
Coming from [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1708279217225549) 

### Problem
Whenever we want to calculate order of reports in the LHN, the `getOrderedReportIDs` function is called. Based on our investigations for different metrics ([Report load time](https://github.com/Expensify/App/issues/34494) and [Send a message](https://github.com/Expensify/App/issues/35225)), we can tell that the `getOrderedReportIDs` is a main bottleneck responsible for app's degrading performance.

Details can be found in the Cache part of [this analysis](https://github.com/Expensify/App/issues/35225#issuecomment-1924126277) 

### Solution
In order to fix the underlying issue, we have splitted the implementation into a few atomic PRs that could be easily digested. One of them is presented below.

Followed the analysis, the overhead that stems from cache lookup when generating ordered reports does not match its possible positive outcomes on overall time execution. Analysis, as well as, measurements with possible gains of removing the cache are presented in linked issues.

**Comment by kacper-mikolajczak** [comment]
Hi @mountiny

**Comment by mountiny** [comment]
Merged

**Comment by jjcoffee** [comment]
I am due payment for the PR review on this. Deployed to production [last week](https://github.com/Expensify/App/pull/36565#issuecomment-1970127188) so should be due payment today, I think. :bow:

**Comment by Christinadobrzyn** [comment]
Payouts due:

Contributor+: $500 @jjcoffee (in Upwork - offer sent - https://www.upwork.com/nx/wm/offer/101274490

Upwork job is [here](https://www.upwork.com/jobs/~01e2b29abfbd075fff).

sent you an offer @jjcoffee!

**Comment by jjcoffee** [comment]
@Christinadobrzyn Accepted, thanks! :bow:

**Comment by Christinadobrzyn** [comment]
Awesome! Paid to you @jjcoffee based on this payment summary https://github.com/Expensify/App/issues/36799#issuecomment-1984945703

Closing
