### ISSUE TITLE
[$500] [HOLD for payment 2024-03-07] [Performance] Use Intl Collator instead of the string localeCompare

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#36795]
Coming from [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1708278398824489)

### Problem
Lots of app critical metrics (TTI, input delay etc.) are hindered because of weak performance inside Prototype.string.localeCompare function in Hermes engine.

### Solution
[Based on Hur's investigations](https://github.com/Expensify/App/issues/35234#issuecomment-1926909866), we can improve performance by swapping out localeCompare with Intl.Collator implementation.

More details are available in the[ linked analysis issue](https://github.com/Expensify/App/issues/35234#issuecomment-1926909866).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af6fd0b61753f3bb</li>
        <li>Upwork Job ID: 1765747002690428928</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by kacper-mikolajczak** [comment]
Hi @mountiny 👋

**Comment by mountiny** [comment]
Follow up from the PR:
- create uni tests for the new util libs
- create a plan to remove the string.localeCompare from other parts of the app

@kacper-mikolajczak would look into this tomorrow

**Comment by kacper-mikolajczak** [comment]
> We can wait a bit, we saw that there are performance gains in the tests and your analysis.

If that is enough of evidence, we can swap out other occurrences as well (additionally ensuring that we don't introduce any regressions). I can prepare PR for that 👍

> How do you want to measure that there are some improvements thanks to this?

The next phase of the audit (`Control` phase) will add specific metrics and perf tests to keep the performance at stable level.

**Comment by mountiny** [comment]
> The next phase of the audit (Control phase) will add specific metrics and perf tests to keep the performance at stable level.

Yeha I dont think we would want to wait this long for that

**Comment by adhorodyski** [comment]
@mountiny  Agree, we should integrate this right away. I'm OOO tomorrow but we'll sync up internally on how to address this! It definitely needs to stay in check, this function runs ~250k times during the startup if I recall correctly :)

**Comment by mountiny** [comment]
@zanyrenney this is ready for payment $500 to @hoangzinh

**Comment by zanyrenney** [comment]
sent offer

**Comment by zanyrenney** [comment]
**payment summary**

paid $500 via upwork to @hoangzinh
