### ISSUE TITLE
[HOLD for payment 2024-03-14] [Wave8] [Simplified Collect] Fetch collect workspace data when opening settings

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#36801]
Part of wave8 cc @luacmartins @trjExpensify 

### Problem

At the moment, we load category or tags data for a policy either:
- on app start for your primary policy
- or when workspace chat, expense report or transaction thread are open in OpenReport

This leaves us with with case when user can navigate to settings of a workspace they are admin of after signing i without navigating to any open report that would load the categories or tags. Since opening the category workspace page for example at the moment does not call any API command, we do not load the categories and for the user it looks like as if the workspace had no categories

### Solution

Possible solution:
Create `OpenWorkspaceCategoryPage` and `OpenWorkspaceTagsPage` commands (similarly for other policy pages), that will be READ API commands fetching the workspace categories or tags respectively. These API commands would take policyID as param

**Comment by luacmartins** [comment]
Thanks for creating this! Seems like the proposed solution is the way to go here. Is there any other ongoing discussion?

**Comment by mountiny** [comment]
Not in Slack, but I think it stemmed from this PR https://github.com/Expensify/App/pull/36324 and testing

**Comment by trjExpensify** [comment]
What are the next steps here?

**Comment by trjExpensify** [comment]
@luacmartins can we get going on this with tags out the door?

**Comment by luacmartins** [comment]
Yes, we got the [PR](https://github.com/Expensify/Auth/pull/10036) to do this for tags merged yesterday. I'll get started on the other ones.

**Comment by trjExpensify** [comment]
👋 Confirming we need to pay @s77rt for [this PR review here](https://github.com/Expensify/App/pull/37457) do we?

**Comment by luacmartins** [comment]
Yes! Assigned them to the issue

**Comment by trjExpensify** [comment]
Offer sent!

**Comment by s77rt** [comment]
Accepted! Thanks!

**Comment by trjExpensify** [comment]
Paid!
