### ISSUE TITLE
[$500] [HOLD #33932] Workspace - The contact disappears but red dot shown next to "Members"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36806]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4318764
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap settings
3. Tap Workspaces --- Workspace
4. Tap members
5. Tap invite members
6. Enter VOIP number +18183305290
7. Select & invite the contact to workspace
8. Note, there was a problem adding this workspace member shown
9. Note contact number and error disappear after an second
10. Tap app back button

## Expected Result:
Using Voip number invited contact to WS, the contact disappears, so red dot must not be shown near members

## Actual Result:
Using Voip number invited contact to WS, the contact disappears but red dot shown near members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/52bf86f5-1e3c-4997-b14d-fed6b7fd1c1e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2eeb30b47a86301</li>
        <li>Upwork Job ID: 1767932995867865088</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment]
@slafortune put on hold pending
- https://github.com/Expensify/App/issues/33932

Bumped to weekly

**Comment by slafortune** [comment]
Not overdue, on Hold

**Comment by slafortune** [comment]
I updated the test with the new number and was able to still recreate this issue.  Adding the external tag

**Comment by bernhardoj** [comment]
This is already being handled in https://github.com/Expensify/App/pull/37895

**Comment by slafortune** [comment]
Thanks @bernhardoj - I'll close this 👍
