### ISSUE TITLE
[$500] Changing playback speed is not taking effect when changing playback speed before playing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36827]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Open a chat
2. Click on '+' icon > Add attachment > select a video
3. Click on three dot icon > Playback speed > select 2 or other option
4. Click on play icon

## Expected Result:
Change in playback speed setting should take effect

## Actual Result:
Change in playback seep doesn't take effect

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/c4743e25-6f29-4dfd-a2ee-0e50bb0ae3c9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f68d54c34c3a131</li>
        <li>Upwork Job ID: 1759791176103968768</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb
cc @quinthar

**Comment by MariaHCD** [comment]
Looks like this is also related to https://github.com/Expensify/App/pull/30829

cc: @Skalakid @francoisl @akinwale 

I think @dukenv0307's proposal makes sense. Thoughts, @Santhosh-Sellavel?

**Comment by miljakljajic** [comment]
Waiting for feedback from @Santhosh-Sellavel

**Comment by MariaHCD** [comment]
Thanks, @shubham1206agra!

**Comment by MariaHCD** [comment]
Although perhaps we shouldn't proceed with a fix for this just yet: https://expensify.slack.com/archives/C01GTK53T8Q/p1708443654362909?thread_ts=1708443084.946829&cid=C01GTK53T8Q

**Comment by puneetlath** [comment]
Removing the deploy blocker label. Seems like something we can fix at the normal cadence.

**Comment by miljakljajic** [comment]
is payment due here?

**Comment by miljakljajic** [comment]
@shubham1206agra and @dukenv0307 sent contracts to you both, previous job expired.

**Comment by miljakljajic** [comment]
Thank you @shubham1206agra 

@shubham1206agra - owed 500 USD for their work on this issue.

@dukenv0307 please accept the offer when you can.

**Comment by miljakljajic** [comment]
Paid!
