### ISSUE TITLE
[$500] Hold request - App crashes when saving a reason during hold request flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36831]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applasue internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Create a manual request from any user.
3. Go to request details page.
4. Click 3-dot menu > Hold request.
5. Add a reason and save it.
## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/983c2492-edfb-48b7-92a0-856947cb3052

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126f2cd8c5ade674d</li>
        <li>Upwork Job ID: 1759794310203371520</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>mkhutornyi | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by techievivek** [comment]
@mkhutornyi Assigned, can you please push the PR ASAP, thanks.

**Comment by joekaufmanexpensify** [comment]
PR is out to production as of 2 weeks ago. Automation didn't work. All set to issue payment. we need to pay: 

- @mkhutornyi $500 for PR, paid via Upwork. 
- @shubham1206agra $500 for C+, paid via Upwork.

**Comment by joekaufmanexpensify** [comment]
@mkhutornyi $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@shubham1206agra please accept our offer so we can pay you

**Comment by joekaufmanexpensify** [comment]
@shubham1206agra is payment here still held?

**Comment by joekaufmanexpensify** [comment]
All good! Is there an ETA for resolution?

**Comment by joekaufmanexpensify** [comment]
Discussing further [here.](https://expensify.slack.com/archives/C02NK2DQWUX/p1711376714110609?thread_ts=1710150138.788529&cid=C02NK2DQWUX)

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY! LMK when your Upwork situation is all set, and I'll re-open this and pay you.

**Comment by joekaufmanexpensify** [comment]
Awesome. TY!

**Comment by joekaufmanexpensify** [comment]
OG upwork job is closed, so opened new one: https://www.upwork.com/jobs/~01456ff2950adec042

**Comment by joekaufmanexpensify** [comment]
@shubham1206agra offer sent for $500!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set.
