### ISSUE TITLE
[$500] Hold Request - "Hold/unhold request" text is not translated to Spanish

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36836]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Pre: Cond: Text is set to spanish
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Create a money request with any user
4. Click on 3 dot menu in top right > "Hold/unhold request" > Complete the reason and tap on ENTER

## Expected Result:
User expects this text to be translated to Spanish

## Actual Result:
Text shows in english as "held this money request with the comment: ..." OR "unheld this money request"

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6385263_1708398936764!Text_is_not_translated_to_spanish_](https://github.com/Expensify/App/assets/43996225/daface36-5939-406c-bb20-f28c09993cdc)

https://github.com/Expensify/App/assets/43996225/d1751ce6-d8f9-4a83-92e6-bd2078764607

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117d6adb152825044</li>
        <li>Upwork Job ID: 1759798173522149376</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by BartoszGrajdek** [comment]
@MonilBhavsar already started working on a fix, so I'm not going to create a follow-up PR, let me know if I can help you with anything! 👀

**Comment by c3024** [comment]
This was fixed in the referred PRs. Can you please close this? @bfitzexpensify @MonilBhavsar

**Comment by MonilBhavsar** [comment]
Yes, going to close this. No payment required here
