### ISSUE TITLE
[PAY 5th MARCH][$500] Tapping on Workspace avatar, app crashes

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36834]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on Workspace chat
3. Tap on Workspace avatar

## Expected Result:
Tapping on Workspace avatar, app must not crash.

## Actual Result:
Tapping on Workspace avatar, app crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/c134ff98-8855-4155-8f9a-711597d7f20c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0122621393ead12452</li>
        <li>Upwork Job ID: 1759796779453788160</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb
cc @quinthar

**Comment by jliexpensify** [comment]
I updated my Android app, but am still on .42-5.

My Chrome is .43 but I can't reproduce this.

**Comment by situchan** [comment]
Reproduced. @jliexpensify workspace avatar should be default svg avatar

**Comment by situchan** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/36834#issuecomment-1953472511) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by techievivek** [comment]
@tienifr Can you please push a PR for this ASAP, thanks.

**Comment by jliexpensify** [comment]
Thanks @tienifr - bump on @situchan to complete the checklist, looks like payment is due in 2 days!

**Comment by situchan** [comment]
Offending PR: https://github.com/Expensify/App/pull/30829
Commented there: https://github.com/Expensify/App/pull/30829/files#r1514802751

No need regression test as caught during regression test in staging.

**Comment by jliexpensify** [comment]
Sorry, here is a Payment Summary

- Contributor: @tienifr $500
- C+: @situchan $500

[Upwork job](https://www.upwork.com/jobs/~0122621393ead12452)

**Comment by jliexpensify** [comment]
Closed and paid!
