### ISSUE TITLE
[HOLD #36894] [$500] [Held requests] "Reason" text is copied twice when using "Copy to clipboard"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36837]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Create a money request with any user
4. Click on 3 dot menu in top right > "Hold/unhold request" > Hold the comment and input a reason like "7"
5. On the "held this money request with the comment: 7" text, long press and click on "Copy to clipboard"
6. Paste this text

## Expected Result:
User expects that "held this money request with the comment: 7" is copied in this case

## Actual Result:
The reason is always copied twice, it will be pasted as "held this money request with the comment: 77"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/f48ee4ed-d0ab-486f-9793-0ce000e5962d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01180936b0aa255ca4</li>
        <li>Upwork Job ID: 1759798757126152192</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by MariaHCD** [comment]
Related to https://github.com/Expensify/Expensify/issues/274076

Not super sure that this should block the deploy.

cc: @robertjchen I'm assuming the way that the message is formatted for hold requests in the BE is intentional and we should be fixing this in the FE only?

**Comment by mollfpr** [comment]
>Not super sure that this should block the deploy.

+1 this should not block the deployment.

Also, I think the proposal from @dukenv0307 looks good!

🎀 👀 🎀 C+ reviewed!

**Comment by robertjchen** [comment]
On hold, pending changes in https://github.com/Expensify/App/issues/36979

**Comment by slafortune** [comment]
Still on hold

**Comment by robertjchen** [comment]
On hold, pending changes in https://github.com/Expensify/App/issues/36979

**Comment by slafortune** [comment]
Can this be taken off hold now @robertjchen ?

**Comment by robertjchen** [comment]
This one can actually be closed out, since the comment is now in a dedicated comment moving forward and the issue here no longer applies 👍
