### ISSUE TITLE
[Tracking issue] Implement sound feature tasks and bugs

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#36846]
# Tracking issue for all issues related to the audio/sounds feature

**Current issues:**
- https://github.com/Expensify/App/issues/36714
- https://github.com/Expensify/App/issues/36543
- https://github.com/Expensify/App/issues/36487
- https://github.com/Expensify/App/issues/36455
- https://github.com/Expensify/App/issues/36542
- https://github.com/Expensify/App/issues/36579
- https://github.com/Expensify/App/issues/37011
- https://github.com/Expensify/App/issues/36863
- https://github.com/Expensify/App/issues/37098
- Tasks cause message sound even when 'mute all sounds is enabled' ([link](https://github.com/Expensify/App/pull/37872#issuecomment-1988170430) to discussion)
- Mobile `@here` and `@user` push notifications should use unique audio cue
- Create push notification test cases for Applause

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ace9e31f7b3ab29b</li>
        <li>Upwork Job ID: 1759861492753469440</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by kirillzyusko** [comment]
@Julesssss comment to assign me on this issue 👀

**Comment by kirillzyusko** [comment]
@Julesssss can you add:
- https://github.com/Expensify/App/issues/36714
- https://github.com/Expensify/App/issues/36487
- https://github.com/Expensify/App/issues/36455

I think some of them are duplicates, but let's add all of them for better transparency?

**Comment by Julesssss** [comment]
@hoangzinh I saw you assigned, was this for a specific review?

**Comment by shawnborton** [comment]
@Julesssss thanks for creating this issue and keeping us organized here!

**Comment by kirillzyusko** [comment]
@Julesssss let's add this to the list?

https://github.com/Expensify/App/issues/36543

**Comment by Julesssss** [comment]
Thanks, added. Though that one seems a bit vague. We'll need to try to see if anyone can reproduce

**Comment by shawnborton** [comment]
Adding this issue here: https://github.com/Expensify/App/issues/37098

**Comment by shawnborton** [comment]
Not overdue, looks like we're making some progress on the issues listed in the original comment above.

**Comment by Julesssss** [comment]
Yeah, thanks Shawn. 

I closed one issue today, and I have just asked in Social for an iOS user to check that a 2nd [issue](https://github.com/Expensify/App/issues/37011#issue-2146682208) is still occurring (if not I will close that as fixed)

**Comment by Julesssss** [comment]
When I have a spare moment I'll create the TestRail cases for QA

**Comment by shawnborton** [comment]
Not overdue, looks like just two items left here.

**Comment by Julesssss** [comment]
Yeah, I'll try to finish this up when I have a moment, but I'm working on higher-priority tasks currently 👍

**Comment by shawnborton** [comment]
Same update as before, just one issue to wrap up and then I will send the Project Wrap Up email and call this one done.

**Comment by shawnborton** [comment]
Still waiting to send the wrap up email

**Comment by Julesssss** [comment]
Hey, sorry for the delay here. I have a fire and some important issues to squeeze in before the quarterly release

**Comment by shawnborton** [comment]
Still waiting on the final clean up item.

**Comment by Julesssss** [comment]
@shawnborton please take a look [here](https://github.com/Expensify/App/issues/36863#issuecomment-2134670986) and LMK if you have any additional test suggestions. Then I'll create the testrails cases. I think we might need a test case for when the app is open and the user is reading the chat report (notification shouldn't display, ut sound should?)

**Comment by shawnborton** [comment]
Nice!

> I think we might need a test case for when the app is open and the user is reading the chat report (notification shouldn't display, but sound should?)

That sounds correct to me

**Comment by Julesssss** [comment]
Great. I added three more tests. The only thing remaining is whether we have a shareable folder with the labelled sounds. This should make testing easier, but I can't find the folder I used 😞

**Comment by Julesssss** [comment]
The final issue has now been closed. Marking the project complete 🥳

**Comment by shawnborton** [comment]
Amazing, thanks Jules!
