### ISSUE TITLE
[$500] Distance - App crashes when creating a distance request after creating a new workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR:** https://github.com/Expensify/App/pull/36147

**Version Number:** v1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace chat.
4. Click + > Request money > Distance.
5. Enter addresses.
6. Proceed to confirmation page.
(Step 2-6 must be done quickly.)

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/978a4429-9fbc-4d9b-8c2b-9d4e10c8e318

[Bug6385297_1708401830330!staging.new.expensify.com-1708401721990.txt](https://github.com/Expensify/App/files/14342786/Bug6385297_1708401830330.staging.new.expensify.com-1708401721990.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5db64f304cac8ab</li>
        <li>Upwork Job ID: 1759883217035563008</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
<li>situchan | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by CortneyOfstad** [comment]
PR [here](https://github.com/Expensify/App/pull/36858) and looks as though it was cherry-picked for Staging 5 hours ago 👍

**Comment by cristipaval** [comment]
@CortneyOfstad, FYI: @situchan is the only contributor to pay here. The C+ is the one who reviewed the original PR that introduced the regression (Thanks, @c3024, for quickly jumping into this! 🙏 )

**Comment by situchan** [comment]
@tienifr https://github.com/Expensify/App/pull/35540#discussion_r1491854338 was posted before this issue created and your proposal is posted. And simple enough so not worth considering efforts made to request compensation.
(Just my opinion)

**Comment by CortneyOfstad** [comment]
I agree with @situchan. @cristipaval do you have any thoughts on whether payment is needed based on the comment [here](https://github.com/Expensify/App/issues/36854#issuecomment-1955784413)?

**Comment by cristipaval** [comment]
I get what @tienifr is saying, and that there were similar cases when other proposals were compensated if they were guiding the developer in fixing it, but given that the discussion about the fix for this issue happened a few days before this issue was created, I think @situchan is the only eligible for the payment here.

**Comment by CortneyOfstad** [comment]
Thanks @cristipaval!

## Payment Summary

@situchan — **paid $500 via Upwork**
