### ISSUE TITLE
[$500] [MEDIUM] Tags: Unable to unselect or select a different tag after the request is created

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/35541

**Version Number:** v1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has categories and tags.

1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Create a manual request with tag.
4. Go to request details page.
5. Click Tag.
6. Select a different tag.

## Expected Result:
User should be able to unselect or select a different tag.

## Actual Result:
Nothing happens when selecting a different tag. User is unable to change the tag after the request is created. The same goes for Category.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/895308f6-c90f-4439-8e14-038e1bae8221

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015553cb48198a3559</li>
        <li>Upwork Job ID: 1759890239807922176</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by paultsimura** [comment]
Same root cause as [here](https://github.com/Expensify/App/issues/36857#issuecomment-1953939702)  – it's caused by https://github.com/Expensify/App/pull/35880

**Comment by kadiealexander** [comment]
@mountiny @Pujan92 could you please take a look and see if your PR [here](https://github.com/Expensify/App/issues/36857#issuecomment-1953939702) will resolve this issue as well?

**Comment by mountiny** [comment]
@kadiealexander he PR got Cped to staging so if you can repro in `1.4.43-5` its not solved

**Comment by kadiealexander** [comment]
Not reproducible anymore:

![image](https://github.com/Expensify/App/assets/59587260/0057e8f2-b4d0-4eaa-a58f-e861900be0fc)

Please reopen if it comes back up.
