### ISSUE TITLE
Referral page - Back button redirects to Start chat page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/32329

**Version Number:** v1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** vdargentotest+web021924@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user should be logged in.

1. Click on the "+" button.
2. Select "Start chat".
3. Click on "get $250".
4. Copy the URL and send it to any chat.
5. Click on the link.
6. Verify the referral page appears.
7. Click on the back arrow.

## Expected Result:
The user should be taken to the chat.

## Actual Result:
The Start chat page appears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/984b3373-e128-472e-bf9e-38c03ae6647e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by zanyrenney** [comment]
I don't think this is a bug, i think the bug is something else related to the learn more hyperlink not working. Tht's the behaviour i see as a problem here -- 
![2024-02-21_14-33-07](https://github.com/Expensify/App/assets/56830058/7a3d7562-45c2-493d-80cb-e633d3bdf182)

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C02QSAC6BJ8/p1708458122746919 this is already reported and worked on here.
