### ISSUE TITLE
Create Audio Cue TestRail cases for Applause QA

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#36863]
cc @abekkala @shawnborton 

# Problem

We're getting bug reports that aren't necessarily bugs. Also the expected audio cue requirements aren't clear or documented. 

# Solution

Lets create a list of new Testrail cases.

**Comment by shawnborton** [comment]
Nice, thanks for creating! Let me know what I can do to help.

**Comment by Julesssss** [comment]
I will still do this, but don't have time yet

**Comment by Julesssss** [comment]
Suggested test cases: 

_____________

**1) Chat notifications**
- Open the app in two separate sessions, one for User A and one for User B
- Log in to User A's account and navigate to any report that both user A and user B have access to
- Send a message to User B
- Verify that User B receives an "Attention" notification sound 
- [Android/iOS] Background the app as User B
- Send another message from User A
- Verify that User B receives an "Attention" notification sound for the mention

**2) Mention notifications**
- Open the app in two separate sessions, one for User A and one for User B
- Log in to User A's account and navigate to any report that both user A and user B have access to
- Mention a user who is different than User B in the report
- Verify that User B does not receive an "Attention" notification sound for the mention. They should receive an ordinary "Receive" sound

**3) [Android/iOS] Notificiation sound should not stop device audio**
- Be signed in on an iOS/Android device
- Be listening to music
- The app should be backgrounded
- Send a message to the user from another account
- Expected Result:
- Music/audio should continue after the cue sound is played

**Comment by shawnborton** [comment]
We probably want to add a case for the Success sound, which happens when you complete a task or complete a payment, right?

And maybe we need to add some guidance about when the user has "Mute all sounds from Expensify" enabled?

**Comment by Julesssss** [comment]
**4) Play 'Success' sound when user completes a payment or task**
- As user A open the app, assign a task and request money from user B
- As User B, complete the task
- User A should hear the success sound, instead of the normal notification sound
- As User B, pay the money request
- User A should hear the success sound, instead of the normal notification sound

**5) Don't play sounds when user is reading current**
- As user A open the chat with user B
- Send a message from user B to user A
- You SHOULD/NOT hear the message received sound

**6) Test mute sounds option**
- As User A, Enable the 'Mute all sounds from Expensify' option in app settings
- User A should remain in the app
- As User B, send a message to user A
- User A should see the new message, but should not hear a notification sound
- Native mobile app notifications are excluded from this test

**Comment by shawnborton** [comment]
For 5, I think if you are viewing a chat and someone sends you a message, you should hear the received sound. Same with the send sound. Thoughts?

**Comment by Julesssss** [comment]
That sounds correct. We don't see the native notification but we do hear the sound 👍

**Comment by Julesssss** [comment]
Test cases created: https://github.com/Expensify/Expensify/issues/399791
