### ISSUE TITLE
[$500] Chat - For video uploaded, download option is not shown.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a report with mp4 video and image attachment
3. Long press the mp4 video message and note context menu options
4. Long press the image message and note context menu options

## Expected Result:
For video uploaded, download option must be shown.

## Actual Result:
For video uploaded, download option is not shown but it is shown for image attachment message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e58d60ff-4786-4ba9-9678-513f2153722e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016eea6865de64afb6</li>
        <li>Upwork Job ID: 1759891713374605312</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by DylanDylann** [comment]
Maybe fixed by https://github.com/Expensify/App/pull/36312

**Comment by francoisl** [comment]
Yes this needs backend changes, I'm already working on this. Going to grab this issue and make it internal.

**Comment by francoisl** [comment]
Eh, that solution works but I'm not a big fan of that change in `isReportMessageAttachment`, we wouldn't need that after ensuring the backend returns `[Attachment]` for the `text` prop of the message.

I'll still keep this issue open to track the backend changes.

**Comment by Tony-MK** [comment]
Hi @francoisl, a gentle reminder. 

Should we probably inspect `isAttachment` as well?

Thanks.

**Comment by twisterdotcom** [comment]
Looks like this should be `Reviewing` right @francoisl?

**Comment by twisterdotcom** [comment]
This was merged and deployed. Closing.
