### ISSUE TITLE
Login - Can not login with Apple ID and Google ID

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36871]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify app
2. Select login with Apple ID or Google ID
3. Follow the flow

## Expected Result:
User can successfully login with Apple ID and Google ID

## Actual Result:
User can not login with Apple ID and Google ID

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1a012bdd-bf22-4675-9597-ac03ef67a940

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Fixed internally: https://expensify.slack.com/archives/C06KNCDSSBC/p1708433037553489
