### ISSUE TITLE
Chat - Group with two identical users are created in offline mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36876]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** build 1.4.43.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+20.feb.good@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. login to a user with applause.expensifail.com domain
2. go to offline
3. create a group with two users: first - different domain user (not a gmail, without previously conversation), second user - from the applause.expensifail.com domain.

## Expected Result:
User should be able to create group chats in offline mode without any issues

## Actual Result:
Group is created with two identical applause.expensifail.com users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/36edb86e-4454-4ccf-a777-9f9413fcdeaf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by joekaufmanexpensify** [comment]
I tried to reproduce on my end, but was not able to. Closing as this doesn't appear to be consistently reproducible.
