### ISSUE TITLE
[$500] Fix the next steps when reimbursing using VBBA

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#36878]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rezkiy37 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

**Pre requirements:**
1. Create/have 2 users at least. One of them is a member of workspaces. The 2nd one is an admin.
2. Create/have 2 paid workspaces via **OD**: **Collect** and **Control**. The feature does not work for a free workspace.
3. Use **OD** to manipulate with the workspaces.
1. The member: opens a workspace chat.
2. The member: requests money.
3. The admin/the member: clicks on a **“Submit”** button.
4. The admin: clicks on an **“Approve”** button.
5. The admin: clicks on a **“Pay with Expensify”** button.

## Expected Result:

A next step with a comment: “_**You** have marked these expenses as **paid**._” and label is “Finished!“.

## Actual Result:

A next step with a comment: “_**You** have marked these expenses as **paid** outside of Expensify._” and label is “Finished!“.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd0939c659293965</li>
        <li>Upwork Job ID: 1759917592558845952</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by trjExpensify** [comment]
This was deployed to prod. Closing!
