### ISSUE TITLE
[$500] Workspace-Collect workspace doesn't show up on the employee side unless sign out and sign in

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36877]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nathanmulugetatesting@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-internl Team
**Slack conversation:**

## Action Performed:
1. Sign in with a new account on ND as account B
2. Create a collect workspace on OD
2. Invite account B as an employee to the workspace created on step 2
3. Refresh the page on account B
4. Sign out from account B and then sign in again

## Expected Result:
Workspace should show up on account B's side once user B gets invited as an employee

## Actual Result:
Workspace doesn't show up on account B's side unless user B manually signs out and signs in again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/299fb1a5-fa26-4650-bab3-f9fac1827411

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150c1c74c4df3c641</li>
        <li>Upwork Job ID: 1764832159689936896</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by stephanieelliott** [comment]
This is only affecting one platform and is pretty minor, gonna opt to close

**Comment by kbecciv** [comment]
Reopening the issue, QA team is able to reproduce on two platforms: mWeb/safari and Mac/Safari 

https://github.com/Expensify/App/assets/93399543/fe9b4b06-71fb-450d-9f65-e90b0f37d48f


https://github.com/Expensify/App/assets/93399543/f7391455-5dc0-4d4e-a2d7-5bfc2d404bd6

**Comment by stephanieelliott** [comment]
Hey @DylanDylann can you check me on this one -- I think this may need a BE fix, but I am not 100% sure

**Comment by DylanDylann** [comment]
There is only announce report is displayed in the employee account and the new workspace isn't added to the workspace list 
<img width="1057" alt="Screenshot 2024-03-05 at 11 09 06" src="https://github.com/Expensify/App/assets/141406735/99dddd5e-ccbe-4627-861f-3467c8cb2ff0">

The RCA is the BE return `policy.isPolicyExpenseChatEnabled` is false and the new workspace is hidden by this logic

https://github.com/Expensify/App/blob/a79c119a85b4f71cf902e047f4b73615f0f4f3db/src/libs/PolicyUtils.ts#L92-L96

@stephanieelliott I think it is a BE bug

**Comment by stephanieelliott** [comment]
Cool, thanks for looking at this @DylanDylann!

**Comment by stephanieelliott** [comment]
Adding this to #wave-collect to get a internal eng  on this.

**Comment by DylanDylann** [comment]
Not overdue, we are waiting for an eye from the internal engineer

**Comment by stephanieelliott** [comment]
This is polish, so not critical for launch. Will wait for this to be picked up.

**Comment by stephanieelliott** [comment]
No update, see https://github.com/Expensify/App/issues/36877#issuecomment-1992721126

**Comment by stephanieelliott** [comment]
Still waiting for this to be picked up internally, its been posted in #wave-collect but considering this is polish it is lower priority

**Comment by stephanieelliott** [comment]
I think this is fixed -- I am unable to repro now. @izarutskaya can you retest please?

**Comment by stephanieelliott** [comment]
Still not reproducible, closing
