### ISSUE TITLE
Notifications - User receives audio notifications when a message arrives when Daily sets

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify App
2. Login with any accounts on 2 devices
3. On the 1st device navigate to the 1:1 conversation with the user in the secondary device
4. Click on the header and change the notification settings for Daily'
5. Navigate away from the conversation
6. On the Secondary device navigate to the 1:1 with the user on the 1st device
7. Send some messages to user on 1st device

## Expected Result:
Verify there's no notifications received in the main device

## Actual Result:
No visual notifications were received but the 1st user received an audio notification when messages arrived

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ce84b50d-9089-4c76-a567-0d5550e34522

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by dylanexpensify** [comment]
repro'ing today!

**Comment by dylanexpensify** [comment]
[this one is tackling that](https://github.com/Expensify/App/issues/37098#issuecomment-1963980110)
