### ISSUE TITLE
Web - Chat - Up arrow fails to open edit for initial parent after subsequent deletion

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any conversation and write a comment.
2. Reply within the thread and write another comment.
3. Click the upward arrow to open the edit option.
4. Clear the message and save it to delete.
5. Repeat step 4 to confirm deletion. Observe the "Deleted message" indication.
6. Attempt to press the upward arrow again to open the edit option.

## Expected Result:
The upward arrow should open the edit option for the initial parent thread after deleting a subsequent parent within the thread.

## Actual Result:
The upward arrow fails to open the edit option for the initial parent thread following the deletion of a subsequent parent within the thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/51473c49-3d16-435b-a5de-b588609f8f1d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@slafortune I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by slafortune** [comment]
Ah!  Yeah, that makes sense to me that once part of the thread is deleted that the up arrow would fail.  I don't think this is necessarily a bug
