### ISSUE TITLE
[$500] [Android] Requested for location after creating scan receipt expense

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#36882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** `1.4.43-2`
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** Me

The solution code should be the same for both iOS and Android. There is a bug that is causing the permission prompt to occur after the scan request is made.

## Action Performed:
- Camera permission should be set to 'Ask every time' when the app requests it
- Location permission should be disabled
- Create a Scan receipt expense
- Request it

## Expected Result:
- Request submitted without issue

## Actual Result:
- Request submitted, **and I am prompted for location permission**

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

https://github.com/Expensify/App/assets/10736861/b90ca63e-52a2-4ea2-a45c-21536f684e77

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

**See Above**

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b08f79b2ec6f294</li>
        <li>Upwork Job ID: 1760968841543987200</li>
        <li>Last Price Increase: 2024-03-01</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
@Julesssss does this need to be External?

**Comment by ghure** [comment]
Hi, 

 if location is not mandatory then, add below check in react native code. It will not ask for permission but you can check if permission is granted is true then request device location.

import { PermissionsAndroid } from 'react-native';
const granted = await PermissionsAndroid.check(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
      );

**Comment by eh2077** [comment]
@ghure Thank you for your comment. Can you follow this template https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md to make a proposal for your solution?

**Comment by ShridharGoel** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Location permission is being asked when trying to request money after scanning a receipt.

### What is the root cause of that problem?
GPS coordinates are being fetched and used while using the smart scan feature. If the location permission is not available, then it asks for the permission to fetch the current user position.

### What changes do you think we should make in order to solve the problem?
We can add a check to see if the location permission is available. If it's there, use the latitude and longitude, else proceed with requesting money.

The below code fetches the position which leads to permission dialog showing up. 
https://github.com/Expensify/App/blob/e9fb49d9f41972a04bf07905b228314a3fdce8d4/src/pages/iou/request/step/IOURequestStepConfirmation.js#L318-L337

**Comment by ShridharGoel** [comment]
Contributor details
Your Expensify account email: shridhar.goel@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fac45b9079c75a93

**Comment by ghure** [comment]
Contributor details
Your Expensify account email: mahadevghure@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c05f9c2c9a9ac7bb

**Comment by ShridharGoel** [comment]
This is happening on iOS as well, I have checked it.

**Comment by eh2077** [comment]
> This is happening on iOS as well, I have checked it.

@ShridharGoel I can't reproduce this on iOS. Did you follow reproduction step - `Location permission should be disabled` before scanning a receipt?

Still looking for proposals.

**Comment by ShridharGoel** [comment]
That was a miss.
Here is the update: This is behaving in a different way on iOS because iOS handles permission differently. Once a permission is denied on iOS, the app can't ask for it again, it can only tell the user to go to settings and manually enable the permission. While in Android, the permission can be asked again (though after a few tries the user will get an option to choose "Don't ask again".

**Comment by ShridharGoel** [comment]
## Proposal

[Updated](https://github.com/Expensify/App/issues/36882#issuecomment-1962348760)

**Comment by Julesssss** [comment]
> After the location permission dialog is shown to the user for the first time and the user denied the permission, we can store this info using Onyx with key isLocationPermissionAvailable as false. We can put a check which will ensure that we will use location only if this key doesn't exist.

@ShridharGoel is that a new Onyx key? Also I don't see why we even need to request permission in this flow. I never opened the distance expense tab and this location prompt seems very invasive IMO

**Comment by ShridharGoel** [comment]
@Julesssss Yes, it would be a new key.

Initially, I also thought about completely removing the permissions flow
from here and only using the data is the permission is already available.
If that sounds good, I can update my proposal with this approach since this
would be a better UX.

**Comment by Julesssss** [comment]
> I also thought about completely removing the permissions flow from here

Just for the Scan/Manual request flow, right? I think ideally we only show that prompt for distance, and only before the request is made, never after.

**Comment by ShridharGoel** [comment]
Yes, only for the scan flow.

**Comment by eh2077** [comment]
@ShridharGoel Thanks for the update! Your proposal is promising.

> This is behaving in a different way on iOS because iOS handles permission differently. Once a permission is denied on iOS, the app can't ask for it again, it can only tell the user to go to settings and manually enable the permission. While in Android, the permission can be asked again until the user selects "Don't ask again" option (after a few tries the user will get this option).

I think it'll be better if your RCA can addresses the main inconsistent issue as described first instead of jumping directly into discussing the general differences between the two platforms. 

Can you elaborate on, when `Location permission should be disabled` on both Android and iOS, why does Android still prompt for location permission while iOS doesn't? 

Hope we can start understanding this issue by a narrow use case, `App with location permission disabled/denied` as the 
 precondition, and then lead to a more general case if possible.

**Comment by ShridharGoel** [comment]
> Can you elaborate on, when Location permission should be disabled on both Android and iOS, why does Android still prompt for location permission while iOS doesn’t?
Basically Android seems optimistic that the user would change their opinion and grant the permission. So, even if it is disabled, Android still goes ahead and asks for the permission when getCurrentPosition is called. This can lead to a bad UX for the user. This prompt would show every time unless the user either grants the permission or selects “Don’t show again” option.
In iOS, if the permission is disabled, it will not be asked again. (edited) 

> Is it possible to eliminate the inconsistency of Android in method getCurrentPosition?
For Android, we can use the `shouldShowRequestPermissionRationale` method. This will return true when the permission has been disabled, and in such a scenario we can skip the location info, so no dialog would be shown to the user.

**Comment by ShridharGoel** [comment]
> Can you elaborate on, when Location permission should be disabled on both Android and iOS, why does Android still prompt for location permission while iOS doesn’t?

Basically Android seems optimistic that the user would change their opinion and grant the permission. So, even if it is disabled, Android still goes ahead and asks for the permission when getCurrentPosition is called. This can lead to a bad UX for the user. This prompt would show every time unless the user either grants the permission or selects “Don’t show again” option.
In iOS, if the permission is disabled, it will not be asked again. (edited) 

> Is it possible to eliminate the inconsistency of Android in method getCurrentPosition?

For Android, we can use the `shouldShowRequestPermissionRationale` method. This will return true when the permission has been disabled, and in such a scenario we can skip the location info, so no dialog would be shown to the user.

**Comment by eh2077** [comment]
> > Can you elaborate on, when Location permission should be disabled on both Android and iOS, why does Android still prompt for location permission while iOS doesn’t?
> 
> Basically Android seems optimistic that the user would change their opinion and grant the permission. So, even if it is disabled, Android still goes ahead and asks for the permission when getCurrentPosition is called. This can lead to a bad UX for the user. This prompt would show every time unless the user either grants the permission or selects “Don’t show again” option. In iOS, if the permission is disabled, it will not be asked again.
> 
> > Is it possible to eliminate the inconsistency of Android in method getCurrentPosition?
> 
> For Android, we can use the `shouldShowRequestPermissionRationale` method. This will return true when the permission has been disabled, and in such a scenario we can skip the location info, so no dialog would be shown to the user.

@ShridharGoel Thanks for quick update. It looks good. Can you update them to your proposal? It'll be helpful if you can also share a test branch and demo videos. 

_Note: Usually we don't need code diff and demo videos to evaluate proposal but this platform specific issue could be special and not that straightforward._

**Comment by Julesssss** [comment]
> Note: Usually we don't need code diff and demo videos to evaluate proposal but this platform-specific issue could be special and not that straightforward.

I think it's okay to not do this to be honest. Its a bit unfair to ask someone to spend time on this and then not ending up using their solution.

**Comment by Julesssss** [comment]
> In iOS, if the permission is disabled, it will not be asked again.

Android also blocks us from asking for permission after a few attampts... We need to avoid this at all costs on both platforms. 

The solution code should be the same for both iOS and Android. There is a bug that is causing the permission prompt to occur after the scan request is made.

**Comment by ShridharGoel** [comment]
@Julesssss Yes, Android also stops asking for the permission after a few tries. But I think here we want to completely stop asking after it is denied once.

So we have two options:
- Don't ask after it is denied once. (Needs custom code for Android)
- Remove permission completely from here for both Android and iOS. That would mean the position would be used only if location permission is already available (granted previously).

**Comment by Julesssss** [comment]
The reason I raised this bug is that it makes no sense to prompt for the permission **after** the request has been made. We don't want to touch the existing permission prompt code unless it is necessary. 

> Remove permission completely from here for both Android and iOS. That would mean the position would be used only if location permission is already available (granted previously).

My question is why do we even prompt at this point in the code? I understand needing to be careful with the prompt where it it used, but there is no use for it in my test case.

**Comment by ShridharGoel** [comment]
There's no prompt code. Android system generates the prompt on its own when position is fetched.

**Comment by ShridharGoel** [comment]
@Julesssss Do you mean the request proceeded even before you dismissed the location dialog? That didn't happen with me - the request was sent after I selected "Don't allow" and then got this in the logs as expected:
```
[info] [IOURequestStepConfirmation] getCurrentPosition failed - {"TIMEOUT":3,"POSITION_UNAVAILABLE":2,"PERMISSION_DENIED":1,"message":"Location permission was not granted.","ACTIVITY_NULL":4,"code":1}
```

**Comment by Julesssss** [comment]
> Do you mean the request proceeded even before you dismissed the location dialog?

Yes, I realize now my video doesn't show this but this happens every day when I submit an expense. 

- Location OFF -> App shows 'To continue, turn on device location' modal
- Location ON -> App prompts for location permission

**Comment by eh2077** [comment]
> The reason I raised this bug is that it makes no sense to prompt for the permission **after** the request has been made. We don't want to touch the existing permission prompt code unless it is necessary.

@Julesssss Thanks for your explanation. So the primary issue we want to fix here is to avoid triggering location prompt after pressing the `Request` button and the expected flow will be
1. User select or take a photo to the `Scan` page
2. Popup location related dialog according to device setting (Optional)
3. User reacts to dialog to make location data (or null) is ready for this transaction (Optional)
4. User can click the 'Request' button without encountering subsequent location-related prompts.

Please correct me if I'm wrong.

**Comment by ShridharGoel** [comment]
> *location feature, NOT location permission

I just tried this, and the experience is a bit weird. I think first we should pick this task: Just proceed with the request if location "feature" is turned off. There's no need to even check for permission related stuff if location itself is disabled.

**Comment by ShridharGoel** [comment]
@Julesssss @eh2077 Do you agree that we should skip location data if location feature is off?

**Comment by Julesssss** [comment]
> User reacts to dialog to make location data (or null) ready for this transaction (Optional)

@eh2077 yeah you're correct, but one small change here: 

At this point we only prompt for camera permission for the scan receipt flow, not location.

> Do you agree that we should skip location data if location feature is off?

I agree, but that location dialog is native, and it is only occuring because of our code that is requesting location permission. When we remove the code that is triggering the location permissio, this dialog will also stop showing.

**Comment by ShridharGoel** [comment]
> When we remove the code that is triggering the location permission, this dialog will also stop showing.

We can add a check - if location feature is off, we'll not use `getCurrentLocation` - hence no dialog will be shown.

**Comment by ShridharGoel** [comment]
> When we remove the code that is triggering the location permission, this dialog will also stop showing.

We can add a check - if location feature is off, we'll not use getCurrentLocation - hence no dialog will be shown.

**Comment by Julesssss** [comment]
We shouldn't be calling `getCurrentPosition` at all. We have no need to do this. Removing this code is the solution to this bug.

**Comment by ShridharGoel** [comment]
@Julesssss We can pick the location from Onyx and use it with the help of `userLocation` key and remove `getCurrentPosition()` function call.

**Comment by Julesssss** [comment]
Taking this internal for a moment.

**Comment by ShridharGoel** [comment]
@Julesssss @eh2077 Kindly let me know once a decision a made. It would be great if I can get the chance to work on this.

**Comment by Julesssss** [comment]
I think we'll want to implement pre-permission prompt logic, something reusable that can be reused for our camera and location permissions. When I have a chance I'll create a new issue or update this one and comment here.

**Comment by Julesssss** [comment]
> 📣 It's been a week! Do we have any satisfactory proposals yet? Do we need to adjust the bounty for this issue? 💸

Next week I'll re-work this bug into a feature request

**Comment by Julesssss** [comment]
No time today, potentially tomorrow.

**Comment by Julesssss** [comment]
Closing this as we need a full internal discussion and design review. 

**This bug will be fixed with the implementation of [this feature](https://github.com/Expensify/App/issues/37736)**
