### ISSUE TITLE
[$500] Distance - Total amount in report is not reset to 0.00 when changing distance request offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36892]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a new workspace (so that there is no existing request)
3. Go to workspace chat
4. Create a distance request
5. Go to request details page
6. Go offline
7. Click Distance
8. Add another stop
9. Return to expense report

## Expected Result:
The total amount will change to 0.00 (PROD behavior)

## Actual Result:
The total amount does not change to 0.00

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/163d3697-665a-4083-bbbf-31c76ad501b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed2116286bd18632</li>
        <li>Upwork Job ID: 1759952290692452352</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by paultsimura** [comment]
You're right @ishpaul777 – updated it in the proposal

**Comment by paultsimura** [comment]
> @paultsimura Unfortunately you solution was not working for me, do you mind sharing a working branch if you have it handy? may be i am missing something

Sure, will share within 2-3 hours - I'm afk at the moment

**Comment by paultsimura** [comment]
@ishpaul777 here it is: https://github.com/Expensify/App/pull/36960


https://github.com/Expensify/App/assets/12595293/564fe0a5-ed16-4640-adda-5350255ddc0e

**Comment by neil-marcellini** [comment]
Taking over this issue to get the blocker fixed quickly

**Comment by cubuspl42** [comment]
Thank you!

**Comment by twisterdotcom** [comment]
Payment Summary:

- C+ @ishpaul777 paid $500 [here](https://www.upwork.com/nx/wm/offer/101398956)
