### ISSUE TITLE
[Hold for payment][$500] Chat  - Video leads to not here page after reopening chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36899]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to chat
3. Upload a video
4. Play the video and verify that it plays
5. Go to LHN
6. Reopen the chat in Step 2
7. Play the video

## Expected Result:
The video is played without issue

## Actual Result:
The video leads to not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec1d40ef-ac9f-4b51-a53c-827537794de5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ba9a1f89a9fa057</li>
        <li>Upwork Job ID: 1759956026491719680</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After reopening the chat page that has a video, pressing the video (on small screen) or expanding it will show not found page.

### What is the root cause of that problem?
When the not found page shown, the `reportID` params in the URL is empty. We get the `reportID` from the active route.
https://github.com/Expensify/App/blob/669ac330b4eeaad2238419bdb501811d3e031e13/src/components/HTMLEngineProvider/HTMLRenderers/VideoRenderer.tsx#L25-L29

But the `reportID` could be empty when the page is still transitioning. If the `reportID` is empty, we will see the not found page.
https://github.com/Expensify/App/blob/669ac330b4eeaad2238419bdb501811d3e031e13/src/components/HTMLEngineProvider/HTMLRenderers/VideoRenderer.tsx#L36-L39

### What changes do you think we should make in order to solve the problem?

Get the `reportID` every time we press the video.
```
onShowModalPress={() => {
    const activeRoute = Navigation.getActiveRoute();
    const {reportID} = parseReportRouteParams(activeRoute);

    const route = ROUTES.REPORT_ATTACHMENTS.getRoute(reportID, sourceURL);
    Navigation.navigate(route);
}}
```

**Comment by stitesExpensify** [comment]
This is coming from https://github.com/Expensify/App/pull/30829

@francoisl do you think we should accept the above proposal? Or would you rather wait until next week after the deploy freeze to handle this?

**Comment by francoisl** [comment]
Yep, we should still try to address deploy blockers during the freeze. If the fix works, let's go with it.

**Comment by stitesExpensify** [comment]
Great. @alitoshmatov what do you think of the above proposal?

**Comment by alitoshmatov** [comment]
@bernhardoj 's [proposal](https://github.com/Expensify/App/issues/36899#issuecomment-1954422863) does solve this issue and provide correct RCA

We can go with this proposal

C+ reviewed 🎀 👀 🎀

**Comment by bernhardoj** [comment]
PR is ready

cc: @alitoshmatov

**Comment by alitoshmatov** [comment]
Looks like Melvin failed here and we missed this issue. The PR went to into [production](https://github.com/Expensify/App/pull/37066#issuecomment-1965253296) 3 weeks ago. Can we proceed with next step

@stitesExpensify

**Comment by stitesExpensify** [comment]
Does the issue still exist on production? If so then yes let's proceed!

**Comment by alitoshmatov** [comment]
@stitesExpensify This issue does not exist in production. The payment is not handled yet

**Comment by stitesExpensify** [comment]
Oh, my apologies I misunderstood your question. I will get a bug zero member assigned!

**Comment by stitesExpensify** [comment]
Hi @sonialiap Melvin didn't trigger here, but the issue is already completed. Could you please process the payment for @bernhardoj and @alitoshmatov ?

**Comment by sonialiap** [comment]
Thanks for the note about payment, processing now 

Payment summary:
- @bernhardoj fix $500 - offer sent
- @alitoshmatov reviewer $500 - offer sent

**Comment by alitoshmatov** [comment]
@sonialiap Accepted the offer

**Comment by sonialiap** [comment]
Both payments made ✔️
