### ISSUE TITLE
Attachment-There is noticeable lag before showing limit error modal when uploading attachments

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36908]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4331253
**Email or phone of affected tester (no customers):** nathanmulugetatesting@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a chat
2. Click on the plus icon inside the compose box > click on choose from gallery
3. Click on a video file
4. Wait for the error modal to show up

## Expected Result:
The error modal should show up immediately

## Actual Result:
The error modal takes a while to show up. If the file size is bigger it takes even longer to show up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/93242c20-d811-45c1-8ff1-4cfc0a4260a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
huh - this lag isn't really noticeable for me (but I might be overly patient)

**Comment by adelekennedy** [comment]
I think because this is relatively minor and just affects android we should close for now
