### ISSUE TITLE
Attachment-App crashes when scrubbing through an mp4 file on attachment upload preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36905]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4331252
**Email or phone of affected tester (no customers):** nathanmulugetatesting@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1.  Open a chat on ND
2. Click on plus icon inside the compose box
3. Click on add attachment
4. Click on choose from gallery
5. Select an mp4 video
6. When the preview opens up play the video and manually scrub through the video using the progress bar

## Expected Result:
App should play the video normally

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8073f5ab-57f8-428b-9abb-6fcb29f9d9a7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by rlinoz** [comment]
Related to https://github.com/Expensify/App/pull/30829

**Comment by kowczarz** [comment]
Hey! I'm not sure if I should write proposal since the fix is quite straight forward and we need to fix it as quick as it's possible. Cc. @mountiny

**Comment by mountiny** [comment]
@kowczarz no need for proposals on this

**Comment by chiragsalian** [comment]
Removing blocker label since the PR was CP-d to staging.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by rlinoz** [comment]
This is actually done and @shubham1206agra was the C+ reviewer.

**Comment by isabelastisser** [comment]
Thanks for the heads up @rlinoz!

@shubham1206agra, I've sent you an offer in Upwork now, please accept it and I will process the payment. Thanks!

All set.

**Comment by isabelastisser** [comment]
@rlinoz @shubham1206agra, can you please confirm the payment amount for the C+ review here? Is it the standard $500?

**Comment by rlinoz** [comment]
Yeah, it should be the standard rate

**Comment by isabelastisser** [comment]
Thanks! I updated the payment amount an d processed it in Upwork. All set.
