### ISSUE TITLE
 Description don't update instantly on employee side in WS profile settings page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in as admin & member in incognito & normal browser tabs
2. As Admin - Create WS & inivite member
3. Admin -Go to WS profile settings page & enter text or edit the description field (Note: Changes not applied instantly on employee side)
4. Change WS name or currency (Note: Changes applied instantly on employee side)
5. As Employee, log out & log back in
6. Employee - Go to WS profile settings page (Note : Description field changes not applied)

## Expected Result:
When admin make changes to WS description field, those changes should immediately reflect on employee side

## Actual Result:
Description field changes don't update instantly on employee side when compared to WS name/currency

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f6166eb1-49b8-445f-898b-5d67153479dd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kevinksullivan** [comment]
the member is supposed to see description as well. Asking about the status of this project to see if it's a bug though

https://expensify.slack.com/archives/C036QM0SLJK/p1708627993161419

**Comment by jacobkim9881** [comment]
After changing description from admin, employee can see description changed immediately. But after logging out/in, description disappeared on employee's side.

**Comment by jacobkim9881** [comment]
Seems there was a fix from BE so you can see description changed immediately on employee's side too. But after logging out/in there should be other fix from BE. Below, asked requests for loading profile from employee's side on the browser.

<img width="1440" alt="스크린샷 2024-02-26 오후 7 01 29" src="https://github.com/Expensify/App/assets/46774300/7bc7a225-bf32-4de3-b5bf-83fbf7b27849">

**Comment by jacobkim9881** [comment]
Kindly bump. [This](https://github.com/Expensify/App/issues/36915#issuecomment-1963745104) seems solved too. It seems any issue above doesn't happened.

**Comment by kevinksullivan** [comment]
Yeah I am not seeing this either, so I'm going to close this out.
