### ISSUE TITLE
Workspace - Description field missing in WS profile settings in which user has joined

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36913]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+1117ck@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36426
## Action Performed:
Precondition : Open workspace in which user joined (but not have the role - Admin)
1. Open workspace page
2. Click on profile option
3. Observe description field missing

## Expected Result:
Description field (read only) should be displayed in WS profile settings in which user has joined

## Actual Result:
Description field missing in WS profile settings in which user has joined

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5ca521a5-c3e9-4d9c-92a9-19a905b85b55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment]
I'm not sure this is a bug. I'm asking in [#product](https://expensify.slack.com/archives/C03U7DCU4/p1708640450949539) to see what the expected behavior of the Description field is when a non-admin views the profile page of a WS.

**Comment by johncschuster** [comment]
We had a chat about this in #product and agree this is expected behavior.

Basically, when a non-admin views the Workspace profile page and the description for the workspace is blank, we will how show the description field to the non-admin at all.

Closing!
