### ISSUE TITLE
[$500] [MEDIUM] Tags: Selected parent tag with sub-tag is displayed incorrectly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36916]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4327832
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable tags and add the tag "Child: Tom", add the employee to the policy. Setup OldDot Collect Policy:
https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0
1. Open https://staging.new.expensify.com/
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a group policy room
8. Click on "Show more"
9. In the tag section, select "Child: Tom"

## Expected Result:
The selected sub-tag of the parent tag must be displayed correctly

## Actual Result:
Selected parent tag with sub-tag is displayed incorrectly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/72eecb8d-9086-42fc-a1bb-670fc4b003d0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4732f27aa3c183f</li>
        <li>Upwork Job ID: 1759969701776297984</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment]
I can look into this

**Comment by yuwenmemon** [comment]
Also cc @rezkiy37

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by kbecciv** [comment]
Issue is not reproducible

https://github.com/Expensify/App/assets/93399543/f1fea762-37bd-4be7-9089-f8a23890b102

**Comment by AndrewGable** [comment]
@Ollyws - Oops yes, @muttmuure can you pay @Ollyws for the review? It's been 7+ days with no regression.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Good to close?

**Comment by yuwenmemon** [comment]
Yep!

**Comment by yuwenmemon** [comment]
Oh sure! @muttmuure can you please resolve this?

**Comment by muttmuure** [comment]
Sorry was out of office - doing this now

**Comment by muttmuure** [comment]
Balls, the message references the wrong issue number. Anyway, I've sent an offer @Ollyws!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Fourth week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Fifth week)

**Comment by muttmuure** [comment]
Looking

**Comment by muttmuure** [comment]
Did you get the one I just sent?
