### ISSUE TITLE
[$500] Web - Chat - Blank space below LHN & composer when entering full screen mode in thread conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+cknov@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. Go to 1:1 DM
3. Tap + icon in composer >> Add attachment >> Upload video attachment
4. Hover over video attachment
5. Select Reply in thread option
6. Tap on play button
7. Click on full screen mode (in video controls) to enter full screen mode

## Expected Result:
No visual issues seen . No blank space displayed below LHN& composer when video played in full screen mode in thread conversation

## Actual Result:
Blank space below LHN & composer when entering full screen mode in thread conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b14e3c28-ace9-4ec7-ba37-793dcffccb28

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193294f121c5cce6a</li>
        <li>Upwork Job ID: 1759965667988815872</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
This is a bug from the video player implementation. I'm going to remove the deploy blocker label since on production we don't have the video player:

<img width="1379" alt="Screenshot 2024-02-20 at 1 51 11 p m" src="https://github.com/Expensify/App/assets/6829422/dec463bb-990b-4f7a-bcc7-b235e075ba4f">

**Comment by marcochavezf** [comment]
Sounds good, thank you @barros001 and @ishpaul777 for the analysis! Closing it out
