### ISSUE TITLE
[$500] IOU - Total paid amount instead of individual amount is copied from each paid IOU preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36924]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. User A creates a few money requests with different amount with User B
3. User B pays the requests
4. User A goes to IOU report
5. Right click on any preview > Copy to clipboard
6. Paste the content
7. Repeat Step 5 and 6 with other preview

## Expected Result:
When copying each paid request to clipboard, the amount for each individual request will be copied

## Actual Result:
When copying each individual paid request to clipboard, the total paid amount is copied instead of each individual amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/914ec00e-80ea-40db-a70c-8c9ced72c942

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01563f6a9a33c0c231</li>
        <li>Upwork Job ID: 1759985620065345536</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by flodnv** [comment]
Maybe related: https://github.com/Expensify/App/issues/36917#issuecomment-1954644603

**Comment by shahinyan11** [comment]
My proposal [here](https://github.com/Expensify/App/issues/36911#issuecomment-1954686490) will fix this issue too

**Comment by deetergp** [comment]
I checked out `main` (after the revert for https://github.com/Expensify/App/issues/36917#issuecomment-1954644603 was merged) and went through the testing steps listed in this issue and things seem to be working as expected now. 

@lanitochka17 could we get a re-test on this one?

https://github.com/Expensify/App/assets/766197/a910db6c-13cf-46c4-8e81-90af6ec0fe86

**Comment by kavimuru** [comment]
@deetergp Our QA team will check on this one.

**Comment by deetergp** [comment]
Thank you @kavimuru 👍

**Comment by deetergp** [comment]
Any word on the retests @kavimuru?

**Comment by kavimuru** [comment]
@deetergp Sorry this got missed. I am following up on this one.

**Comment by kavimuru** [comment]
@deetergp Not reproducible in web and android. Waiting for other platform results.


https://github.com/Expensify/App/assets/43996225/e1e7be5a-3c1b-4b98-9f19-96ca0d7f0930


https://github.com/Expensify/App/assets/43996225/0bb5ac62-18bd-417e-8de9-c3f144f0f55a

**Comment by deetergp** [comment]
@kavimuru Any word back on the other platforms?

**Comment by kavimuru** [comment]
@deetergp Not reproducible in other platforms too.
