### ISSUE TITLE
mWeb - Chat - LHN is displayed instead of the opened chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/36637
 
## Action Performed:
1. Open an existing chat with an expensifail account
2. Close the Safari tab
3. Open a new Safari tab and open Expensify

## Expected Result:
The opened chat should be displayed.

## Actual Result:
LHN is displayed instead of the opened chat. On Android, I can see the actual chat but it switches to the LHN quickly after.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f501f111-61d1-4af0-af8b-c2fcee215f5c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@zanyrenney I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related  #wave8-collect-admins
CC @zanyrenney

**Comment by hayata-suenaga** [comment]
@kbecciv [this issue was already known](https://github.com/Expensify/App/pull/36637) before the PR you linked was deployed. However, the QA team determined this is not reproducible.

**Comment by zanyrenney** [comment]
Thanks @hayata-suenaga - given ^^ closing!
