### ISSUE TITLE
[HOLD for payment 2024-04-03] [LOW] [Splits] [$500] Chat - Error "a previously existing chat between these users." is missing when go online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36928]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0507gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36538
## Action Performed:
1. Log into New Dot on two devices, user A and user B
2. As user A, go offline and request money from user B
3. Verify an offline, optimistic request is created
4. As user B, go online and request money from user A
5. Verify the money request is successfully created
6. As user A, go back online

## Expected Result:
When user A come back online error message about "a previously existing chat between these users." should appear

## Actual Result:
"Hmm...It's not here" page appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/138db42f-8246-4ece-8e97-bcc2e24020fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6be5b10ed2e0055</li>
        <li>Upwork Job ID: 1759993160900755457</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by arosiclair** [comment]
Couldn't reproduce on **v1.4.43-5**:

![Screenshot 2024-02-20 at 3 12 28 PM](https://github.com/Expensify/App/assets/6833644/2aae0c2c-9d92-4543-9d1f-d208bfdb826b)

**Comment by arosiclair** [comment]
Okay I was able to reproduce using the "Force offline" toggle. This seems to be caused by the extra navigation back to the report which triggers `OpenReport` for the optimistic report and gets it cleared from Onyx.

This is related but slightly different from the repro steps I fixed. Since this is still an edge case, I'll remove the blocker label and take care of this flow later.

**Comment by sonialiap** [comment]
@arosiclair to confirm, you're picking this up so we can label this as an internal issue?

**Comment by arosiclair** [comment]
Oh yeah we can mark this as internal. I'm going to drop the priority though

**Comment by arosiclair** [comment]
> This seems to be caused by the extra navigation back to the report which triggers OpenReport

Looks like my intuition here was correct. After navigating back to the report from the force offline toggle, we queue a OpenReport call in the ReportScreen [here](https://github.com/Expensify/App/blob/27b1aa81bc7fb1bc426357033f7038a0906e6adf/src/pages/home/ReportScreen.js#L362). So we just need to add another check for `isOptimisticReport`. The pre-fetching checks for reports are kind of all over the place, so I'll unify that logic.

**Comment by arosiclair** [comment]
Alright per that discussion we'll make `OpenReport` set `errorFields.notFound` for reports that are inaccessible instead of deleting the report completely. `errorFields.notFound` will display the "it's not here" page only when there aren't any other helpful errors set.

I'll post a Web-E PR to get those changes out and then continue with the App PR.

**Comment by arosiclair** [comment]
Alright two PRs are updated and out for review. App PR's needs to go first:
- [App PR](https://github.com/Expensify/App/pull/37930)
- [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41296)

**Comment by arosiclair** [comment]
App PR deployed a week ago so this is due for payment @sonialiap

**Comment by sonialiap** [comment]
App PR deployed to prod Mar 27, 7 days makes payment due on Apr 3 (today 💸 )

**Comment by sonialiap** [comment]
@fedirjh $500 - [offer sent](https://www.upwork.com/nx/wm/offer/101717595)

**Comment by sonialiap** [comment]
Paid ✔️
