### ISSUE TITLE
[$500]  IOU - It shows a location permission denied error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36949]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36147
## Action Performed:
1. Start creating a distance request in a workspace chat
2. Tap on the Start
3. Tap on the "Use current location" button

## Expected Result:
It should be showing my location on my map or ask for permission

## Actual Result:
It shows a location permission denied error. Safari location setting can be "Ask" or "Allow"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/47d43b9d-7563-4d3e-a50f-de4edaad8eed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199b0f95a9b2d0ac2</li>
        <li>Upwork Job ID: 1760487636301574144</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
I think this can be external

**Comment by jeremy-croff** [comment]
It looks like it's actually default behavior to require a refresh after changing from allow to disallow or disallow to allow.. I think in this ticket the tester had it as disallow, and is not getting it to be allowed ( unless he would refresh) 
I found some hacky workarounds, such as doing the location fetching in an iframe, so that it doesn't require a refresh, but this is not ideal.

**Comment by aswin-s** [comment]
For me it was never asking for location permission as Safari had location permission set to "never" under Settings> Privacy> Location Services > Safari". I don't remember setting it. After switching it to `Ask next time` or `Allow while using` seems to fix the issue. However there is no indication on the map screen that location permission is denied. I think this needs a UI fix.

**Comment by jeremy-croff** [comment]
> For me it was never asking for location permission as Safari had location permission set to "never" under Settings> Privacy> Location Services > Safari". I don't remember setting it. After switching it to `Ask next time` or `Allow while using` seems to fix the issue. However there is no indication on the map screen that location permission is denied. I think this needs a UI fix.

I observed that Mapview uses default coords instead of showing permission denied, but kept it out of scope of this ticket

**Comment by stephanieelliott** [comment]
Thanks for investigation here! I agree the current behavior is not optimal, but I also think that `location permission denied` is not _terrible_ -- it does get the message across that location permissions need to be allowed (which seems to fix the issue). So given that this doesn't really fit anywhere on our roadmap at the moment I am going to close this, we may fix it later when we get into polishing distance requests but this seems pretty low priority at the moment.
