### ISSUE TITLE
Entering certain diacritics such as à, á, â in the composer is broken (WEB)

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#36942]
Web version of - https://github.com/Expensify/App/issues/36203

Adding for tracking before we re-enable this for web

## Action Performed:

1. Open any chat
2. In the composer, type Option+`, then a

## Expected result: 
 à is entered in the composer
## Actual result: 
`a is entered in the chat
Same goes with Option+e , then letter, e.g. ´a is entered instead of á

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/07a35792-3430-4563-801d-d91184818448

**Comment by thienlnam** [comment]
PR currently in review https://github.com/Expensify/react-native-live-markdown/pull/210

**Comment by BartoszGrajdek** [comment]
> This is still broken in some places 

Can you explain what do you mean? @shubham1206agra

**Comment by BartoszGrajdek** [comment]
Kind bump @shubham1206agra I believe that diacritics were fixed, can you show me what is the problem now? 😄
