### ISSUE TITLE
Chat - Inverse order of messages are copied when messages are copied chronologically

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat
3. Send a few messages (1,2,3,4,5,6 etc)
4. Drag the messages from top to the last message
5. Copy the messages via CMD+C
6. Paste the content in the composer

## Expected Result:
The correct order of messages is copied (1,2,3,4,5,6)

## Actual Result:
The inverse order of messages is copied (6,5,4,3,2,1)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0bb665aa-26f1-4759-b5eb-b33802f4d8fc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@bz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
I can reproduce this, but I don't think this is something that fits into one of our roadmap projects as something we should prioritize. Copying multiple messages at once on any chat app is janky, and not something users really do. The general standard is to copy and paste per message. 

Let's close this for now and see if anyone actually experiences this before deciding to change anything.
