### ISSUE TITLE
[P2P Distance] Define Default P2P Rates

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#36965]
Follow this plan to [Define Default P2P Rates](https://docs.google.com/document/d/1MepSFJHmETFRvT7KVlsKp-e5NlsS0Gn4P6cyVEPxIYg/edit#heading=h.2iayfdgbs75k).

Here are the top 10 most common policy output currencies as of 2/27/24. [Here is the CQ](https://github.com/Expensify/Expensify/issues/372223#issuecomment-1962138892) that was used.
```
outputCurrency,policyCount
USD,10610104
EUR,658901
GBP,622255
CAD,474795
INR,317091
AUD,282833
RUB,116916
BRL,92562
SGD,78368
UAH,72175
```

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f53a654b3f174ce</li>
        <li>Upwork Job ID: 1760072040420114432</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
@twisterdotcom or @trjExpensify would you be interested in doing the research part of this?

**Comment by trjExpensify** [comment]
I'm afraid I can't take this one right now, Neil. Sorry!

**Comment by twisterdotcom** [comment]
@neil-marcellini just to make sure I understand, all you'd need me to do is get the top 10 currencies (which, I'm not sure we need to query, we could estimate USD, CAD, GBP, AUD, NZD, EUR, JPY, CHF... ZAR, MXN? Missing maybe ILS, BRL, DKK, SGD, SEK, KRW, NOK, INR but still.

And then I just need to find what that jurisdiction's default mileage rate and unit is... and then format it into json like this?

```JS
{
    "USD": {
        "rate": 0.655,
        "unit": "mi"
    },
    "GBP": {
        "rate": 0.520,
        "unit": "km"
    },
    "CAD": {
        "rate": 0.890,
        "unit": "km"
    }
}
```

I have a bunch of customers who operate in lots of these jurisdictions so I can kind of just check their policies to get a good idea.

**Comment by neil-marcellini** [comment]
Backend only, so removing C+

**Comment by neil-marcellini** [comment]
@twisterdotcom will you be able to come up with values for the most popular currencies in the next few days? The CQ is waiting to be run in [this issue](https://github.com/Expensify/Expensify/issues/372223).

I'm going to get started on the cli script for generating this data soon.

**Comment by twisterdotcom** [comment]
```JSON
{
    "USD": {
        "rate": 0.67,
        "unit": "mi"
    },
    "CAD": {
        "rate": 0.70,
        "unit": "km"
    },
    "GBP": {
        "rate": 0.45,
        "unit": "mi",
    },
    "AUD": {
        "rate": 0.85,
        "unit": "km"
    },
    "NZD": {
        "rate": 0.95,
        "unit": "km"
    },
    "EUR": {
        "rate": 0.3, // Rate for Germany, other EUR countries differ
        "unit": "varies"
    },
    "CHF": {
        "rate": 0.7,
        "unit": "km",
    },
    "ZAR": {
        "rate": 4.64,
        "unit": "km"
    },
    "MXN": {
        "rate": 0.93,
        "unit": "km"
    },
    "ILS": {
        "rate": 5.400,
        "unit": "km"
    },
    "DKK": {
        "rate": 3.79,
        "unit": "DKK/km"
    },
    "SEK": {
        "rate": 2.5,
        "unit": "km"
    },
    "NOK": {
        "rate": 3.5,
        "unit": "km"
    },
    "PLN": {
        "rate": 0.89,
        "unit": "km"
    },
}
```

@neil-marcellini a lot of these jurisdictions have tiered mileage rates though (as in they have a lower amount after X miles. Can we only load one default with one name for each? A lot of the currencies I named don't have specific mileage rates set by the government, so these are the ones that do.

Also, TIL that Norway a specific mileage rate for snowmobiles.

**Comment by neil-marcellini** [comment]
Awesome thanks so much for creating that! We got the query results too so I'm posting them in the description. I think I have everything I need to define the default rates now.

Would you please write a quick SO about how to update the mileage rates each year? It will be used when we create a chore for this issue [[HOLD 36965][P2P Distance] Create the UpdateMileageRates chore](https://github.com/Expensify/App/issues/36974#top). I'll assign you there. Please include instructions for how to update the existing IRS rate and how to research the new default values for the top 10 most used currencies.

I'll add on to the SO with instructions about how to generate the JSON for the rest of the mapping. I think I might create a simple supportal tool for it rather than a CLI script, so that a non-engineer can generate the full JSON.

**Comment by twisterdotcom** [comment]
Nice, I just tried to check for RUB and UAH and I can't see that they have a standard rate, so the rest should be covered.

**Comment by twisterdotcom** [comment]
>please write a quick SO about how to update the mileage rates each year?

Pfffft, god it's a bit all over the place but I can. I actually got these from a mix of googling and checking Blackberry's workspaces. I wonder if we can just get the same answers from a GPT?

**Comment by twisterdotcom** [comment]
Can we close this and focus on that in https://github.com/Expensify/App/issues/36974#issuecomment-1968870745?

**Comment by neil-marcellini** [comment]
> Can we close this and focus on that in [#36974 (comment)](https://github.com/Expensify/App/issues/36974#issuecomment-1968870745)?

Yeah, your work here is done @twisterdotcom, thanks! I'm going to keep this open until I finish the engineering part of it. Using chatGPT to get the rates could work, but that assumes the AI model is updated each year, which is probably not the case. Googling might be best.

**Comment by neil-marcellini** [comment]
Today I built the supportal tool to generate these rates, and I'm really happy with it. I need to write some test steps in the PR, and then I can easily get it up for review tomorrow.

**Comment by neil-marcellini** [comment]
PR is up for review! Here's a peak of what the supportal tool looks like. I'll paste the JSON into the front end issue, take it off hold, and get it moving.

https://github.com/Expensify/App/assets/26260477/a3a3b9ae-2c1f-4be2-ad92-4eb71d25d7f3

**Comment by neil-marcellini** [comment]
The PR has been merged to production, so this is done!
