### ISSUE TITLE
[P2P Distance] Implement bottom up flow rate updates in Auth

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#36968]
Implement the bottom up flow rate updates in Auth following [this plan](https://docs.google.com/document/d/1MepSFJHmETFRvT7KVlsKp-e5NlsS0Gn4P6cyVEPxIYg/edit#heading=h.7x9qi0uq0pez)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01827ce4ed3e5a3729</li>
        <li>Upwork Job ID: 1760074243121115136</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
Still on hold for a while

**Comment by neil-marcellini** [comment]
We could start working on the backend even if the frontend isn't quite ready yet.

**Comment by neil-marcellini** [comment]
Still focused on higher priorities, this is available for volunteers! @Beamanator this one is all Auth so there shouldn't be any 1:1:1 issues in your way if you would like to pick this up.

**Comment by neil-marcellini** [comment]
No pressure though, I don't want you to feel spread too thin

**Comment by Beamanator** [comment]
Sadly I can't prioritize at the moment, but maaaaaybe next week

**Comment by neil-marcellini** [comment]
Waiting until this becomes more important

**Comment by neil-marcellini** [comment]
Still not a priority

**Comment by neil-marcellini** [comment]
Still haven't had time for this, probably won't for a while 🫤

**Comment by neil-marcellini** [comment]
Still on hold. I plan to finish distance splits for this project, then check if the team is cool with slowly chipping away at the remaining work to finish it or if it should be paused indefinitely.

**Comment by neil-marcellini** [comment]
Distance splits is almost done, going to pick this up next.

**Comment by neil-marcellini** [comment]
I'm still focused on splits, but plan to jump on this right after, hopefully in the next week or two.

**Comment by neil-marcellini** [comment]
I got a little start on this. It's feeling pretty achievable.

**Comment by neil-marcellini** [comment]
I'm going to close this issue since it's for the backend side of things, which are now done. I have created a new issue for the frontend part and assigned it to you [[$250] [P2P Distance] Add RBR logic for the bottom up flow](https://github.com/Expensify/App/issues/46753#top).
