### ISSUE TITLE
[HOLD for payment 2024-03-07] Hold dot separator doesn’t show in the expense preview

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#36977]
## Action Performed:
Go to Expense preview for held request

## Expected Result:
![image](https://github.com/Expensify/App/assets/2438855/5606f2e2-9ccd-4ae5-a3ea-d95a1b9a5b2d)

## Actual Result:
![image](https://github.com/Expensify/App/assets/2438855/0e6fcd91-c688-41f7-8874-fb7c52db7578)

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

See above

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by robertjchen** [comment]
Finalizing PR

**Comment by situchan** [comment]
C+ payment is pending here

**Comment by robertjchen** [comment]
cc: @twisterdotcom for assistance on https://github.com/Expensify/App/issues/36977#issuecomment-1981289085 Thanks! 🙏

**Comment by twisterdotcom** [comment]
Payment Summary:

@situchan paid $500 [here](https://www.upwork.com/nx/wm/offer/101284938) (C+)
