### ISSUE TITLE
[P2P Distance] Remove the beta from the backend

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#36972]
Remove the beta for P2P distance requests, following [this plan](https://docs.google.com/document/d/1MepSFJHmETFRvT7KVlsKp-e5NlsS0Gn4P6cyVEPxIYg/edit#heading=h.u70yecblknw2)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01293d3788466b0946</li>
        <li>Upwork Job ID: 1760076345682821120</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
On hold still

**Comment by neil-marcellini** [comment]
Still holding

**Comment by neil-marcellini** [comment]
holding

**Comment by neil-marcellini** [comment]
ditto

**Comment by neil-marcellini** [comment]
It's going to be a while

**Comment by neil-marcellini** [comment]
Still not done and it's been de-prioritized 😞. I'll still be working on it, but only 1-2 days per week.

**Comment by neil-marcellini** [comment]
Not quite done yet, but we're getting a lot closer.

**Comment by neil-marcellini** [comment]
Still on hold, hoping to be done soon but it's slow and steady.

**Comment by neil-marcellini** [comment]
Still holding. I'm looking over the current bugs to determine if we can remove the beta and launch it.

**Comment by neil-marcellini** [comment]
We're pretty close to having this done. Only one or two more bugs to go.

**Comment by neil-marcellini** [comment]
Off hold. I put up a simple PR to remove it. After that I'll purge the entries from the DB.

**Comment by neil-marcellini** [comment]
May I please have a buddy check to remove the beta entries from the DB?

Read
```sql
SELECT * FROM betaUsers WHERE feature='p2pDistanceRequests';
```

Write
```sql
DELETE FROM betaUsers WHERE feature='p2pDistanceRequests';
```

**Comment by deetergp** [comment]
```
mysql> SELECT COUNT(*) FROM betaUsers WHERE feature='p2pDistanceRequests';
+----------+
| COUNT(*) |
+----------+
|        5 |
+----------+
1 row in set (0.01 sec)
```

👍  CQ looks good

**Comment by deetergp** [comment]
Done!
```
mysql> SELECT COUNT(*) FROM betaUsers WHERE feature='p2pDistanceRequests';
+----------+
| COUNT(*) |
+----------+
|        5 |
+----------+
1 row in set (0.01 sec)

mysql> DELETE FROM betaUsers WHERE feature='p2pDistanceRequests';
Query OK, 5 rows affected (0.01 sec)

mysql> SELECT COUNT(*) FROM betaUsers WHERE feature='p2pDistanceRequests';
+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```
