### ISSUE TITLE
[HOLD 36985][$500] [P2P Distance] Implement bottom up flow violations in App

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#36988]
Implement bottom up flow violations following [this plan](https://docs.google.com/document/d/15GQhipcqOJ69MbFA54KRUcWxjICURHYcfTlAb3eaVEQ/edit#bookmark=id.fmeu9ht0mml2). Please be sure to read and understand the relevant sections of the entire plan as well.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e3e6076dcf3ac3bb</li>
        <li>Upwork Job ID: 1760136030900682752</li>
        <li>Last Price Increase: 2024-03-06</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by koko57** [comment]
Commenting to help with the review.

**Comment by neil-marcellini** [comment]
Thanks for the proposal @dukenv0307, but I'm going to ask @waterim from Callstack to take this one.

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and I would like to help with this one

**Comment by CortneyOfstad** [comment]
Hi @waterim! Sorry for the delay, as I was OoO last week. Assigning you now!

**Comment by waterim** [comment]
Hello @CortneyOfstad, as far as I know this one was on hold for some backend changes, is it off hold now? 
if yes, I will prepare a PR during first half if the next week!

**Comment by CortneyOfstad** [comment]
@neil-marcellini can you confirm if this is the on-hold issue — https://github.com/Expensify/App/issues/36985? This doesn't appear to be BE related, so just wanted to get this clarified 👍

**Comment by neil-marcellini** [comment]
Yes it should be on hold for https://github.com/Expensify/App/issues/36985. I will update the title. @waterim if you want to collaborate with @koko57 to get started early, you could branch off of her draft PR.

**Comment by CortneyOfstad** [comment]
PR was linked in on-hold issue [here](https://github.com/Expensify/App/issues/36985#issuecomment-2027449131) 👍

**Comment by CortneyOfstad** [comment]
PR is still being reviewed, so no update on this side yet 👍

**Comment by CortneyOfstad** [comment]
[PR ](https://github.com/Expensify/App/pull/38543)is still open and being reviewed — will continue to keep an eye on this 👍

**Comment by CortneyOfstad** [comment]
Deployed to production 14 hours ago!

**Comment by CortneyOfstad** [comment]
This can be closed as the on-hold issue finished the 7-day hold for production yesterday! 🎉
