### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] [P2P Distance] Enable P2P/Splits in App

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#36984]
Enable P2P/Splits in App following [this plan](https://docs.google.com/document/d/15GQhipcqOJ69MbFA54KRUcWxjICURHYcfTlAb3eaVEQ/edit)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165a75cb62ec4b3a6</li>
        <li>Upwork Job ID: 1760135587374198784</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by neil-marcellini** [comment]
Fast tracking this because we don't really need proposals given that I trust @tienifr to implement the plan well.

**Comment by koko57** [comment]
Commenting to help with the review.

**Comment by neil-marcellini** [comment]
@tienifr ETA for the PR?

**Comment by koko57** [comment]
@tienifr I think you should revert formattedDistanceAmount to iouMerchant for the distance field for now and open the PR. The distance field value changes were meant to be done in the Phase 3 with the rate field. Now we just want to enable the field to be able to change the distance (it should work with the current logic with the iouMerchant)

cc @neil-marcellini

**Comment by koko57** [comment]
> > Can I take a look at the NVP.LAST_SELECTED_DISTANCE_RATES structure? We need to define the type and new onyx key for it.
> 
> There's one thing blocked. @koko57 Do you have any hint?

Let's store the last selected rate ID here - so the type will be string and the onyx key could be NVP_LAST_SELECTED_DISTANCE_RATE (I believe we want it singular, not plural)

**Comment by neil-marcellini** [comment]
# ❗❗❗ Note to QA/bug reporters ❗❗❗

Please refrain from creating deploy blockers related to this PR/issue. The feature is under a beta that is only available to expensify accounts while we build the feature. It's expected to be incomplete right now.

**Comment by neil-marcellini** [comment]
Pr was merged 🚀

**Comment by neil-marcellini** [comment]
@adelekennedy we don't need to do any payment right now since I implemented the PR and we did not use a C+ for review. I'm going to keep this open until we enable splits. I have only enabled P2P for distance so far.

**Comment by adelekennedy** [comment]
Yep - it looks like payment is due here for @tienifr and @alitoshmatov (checking the PR and the proposal process here)

**Comment by neil-marcellini** [comment]
> @neil-marcellini Seems like you mistook this with another issue 😅 because I and @alitoshmatov worked on this.

Oh woops yes sorry!

**Comment by neil-marcellini** [comment]
Gentle bump @adelekennedy, can we get this closed out please?

**Comment by adelekennedy** [comment]
payments have already been made! Last step outstanding is the regression test 
<img width="1376" alt="Screenshot 2024-03-25 at 9 49 05 AM" src="https://github.com/Expensify/App/assets/60450566/5b39dcc0-3d26-4260-8f1c-bf0463b227cc">

**Comment by adelekennedy** [comment]
<img width="833" alt="Screenshot 2024-03-25 at 9 54 47 AM" src="https://github.com/Expensify/App/assets/60450566/f63c1ed2-2aa2-4e97-9d5d-991a56054706">

**Comment by alitoshmatov** [comment]
I think new regression test from me is not needed since [plan for this feature](https://docs.google.com/document/d/15GQhipcqOJ69MbFA54KRUcWxjICURHYcfTlAb3eaVEQ/edit) contains manual tests and states this: 

> All of the tests should be added to TestRail as new cases. Our QA team can decide where they should go within the test sections.

**Comment by adelekennedy** [comment]
perfect then we are good to close!
