### ISSUE TITLE
[P2P Distance] Update CreateDistanceRequest params in App

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#36986]
Update CreateDistanceRequest params following [this plan](https://docs.google.com/document/d/15GQhipcqOJ69MbFA54KRUcWxjICURHYcfTlAb3eaVEQ/edit#bookmark=id.rir4rob7lh7z). Please be sure to read and understand the relevant sections of the entire plan as well.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b8ff8ae87a467a0</li>
        <li>Upwork Job ID: 1760135519646322688</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by koko57** [comment]
Commenting to help with the review.

**Comment by neil-marcellini** [comment]
I got started on this for a while and I'm finding it to be a little tricky. Specifically it's hard to get the split params and onyxData without creating duplicate optimistic objects. I stashed my changes.

To keep things more simple I will start with only supporting P2P distance, then we can do splits in another PR.

**Comment by neil-marcellini** [comment]
@shubham1206agra does not need payment because we did not require a C+ review. I'll keep this open for the split part coming soon.

**Comment by neil-marcellini** [comment]
It's going to be a while before splits are implemented on the backend. Not overdue.

**Comment by neil-marcellini** [comment]
I'll mark this as on hold, since it is.

**Comment by neil-marcellini** [comment]
Hooooooolding

**Comment by neil-marcellini** [comment]
Same

**Comment by neil-marcellini** [comment]
Still on hold, but the holding issue to enable distance splits is underway now.

**Comment by neil-marcellini** [comment]
I got a very small start on this today. I'm going to use this as the issue to enable splits in App again. I'm currently working on getting the distance request amount to show up in split shares on the confirmation page.

**Comment by neil-marcellini** [comment]
I've been working on splits a lot. Right now I'm working on the automated Auth tests

**Comment by neil-marcellini** [comment]
Still holding, making it a monthly

**Comment by neil-marcellini** [comment]
Still on hold, but will probably be fixed soon by this PR. [Enable distance splits](https://github.com/Expensify/App/pull/42302#top)

**Comment by neil-marcellini** [comment]
Not on hold anymore, will be fixed soon by that PR!

**Comment by neil-marcellini** [comment]
Meh I'm just going to close this since it's essentially a duplicate issue.
