### ISSUE TITLE
[$500] Workspace admins are automatically added to user created rooms on the workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36992]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708463916343489

## Action Performed:
1. Have a workspace created in account A with workspace admins and member
2. As a member of the workspace create a room with workspace visibility

## Expected Result:
Admins are not added to the workspace automatically

## Actual Result:
Admins on workspaces are automatically added to user-created rooms with workspace visibility, even if they haven’t joined or been mentioned.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e86fa39a091e5999</li>
        <li>Upwork Job ID: 1760238867563573248</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
@brandonhenry yes this accepting proposals - do you have one?

**Comment by brunovjk** [comment]
I also couldn't reproduce v1.4.43-18. In account B I create the chat with visibility for the workspace, and the admin does not appear as a member.

**Comment by laurenreidexpensify** [comment]
Let's get confirmation it's still reproducible

**Comment by laurenreidexpensify** [comment]
still waiting for KI test confirmation on reproducibility

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
