### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] [Held Requests] Hold request modal does not dismiss for Employee after admin pays the request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37014]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/33897

**Version Number:** v1.4.43-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team
**Slack conversation:**

## Action Performed:
Precondition:
Admin and employee are in the same workspace.

1. [Employee] Create a manual request from workspace chat.
2. [Employee] Submit the request.
3. [Employee] Go to request details page.
4. [Employee] Click 3-dot menu > Hold request.
5. [Admin] Pay the request.
6. [Employee] After the background shows "paid", add a reason and submit it.

## Expected Result:
In Step 5, Hold Request modal should dismiss for Employee after Admin pays it.

## Actual Result:
In Step 5, Hold Request modal does not dismiss for Employee after Admin pays it. As a result, employee can hold the paid request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0ded42f8-16fd-4fb6-b819-4c952122f8cb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dad4e5f90367adf7</li>
        <li>Upwork Job ID: 1760292458905010176</li>
        <li>Last Price Increase: 2024-02-28</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>WikusKriek | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by robertjchen** [comment]
Yep, not a deploy blocker but great catch here- I think the big UX difference between the two above proposals are:

> We should disable the Hold Request button or show error when pressed if the report is Settled and could not be held.

and

> we will dismiss the hold request page since we cannot hold request. This also can help us to prevent openning the hold request page by deeplink if we cannot do this action.

I'm partial to the latter one (@dukenv0307 's approach), but is there room to combine both approaches? 🤔 What do you think @alitoshmatov 

cc: @Expensify/design for guidance on what would be the most consistent experience.

**Comment by shawnborton** [comment]
Hmm I think I would just block form submission on the hold modal in this case, letting them know that the expense status changed and they can no longer hold it as the form error message. Otherwise it feels a bit strange to automatically close the modal for them if they don't know why that's happening.

**Comment by shawnborton** [comment]
Sure, but I am just suggesting what I think makes the most sense from a UX perspective.

**Comment by dannymcclain** [comment]
I agree that it feels strange to just close a modal on someone without telling them why (in any situation). I also agree with Shawn's suggestion, but think it would be fine to actually let them submit the hold form modal and then show some kind of error (pop up? modal? I don't know) that tells them the expense status changed and they can no longer hold it. Shawn's suggestion feels cleaner. Just my 2 cents.

**Comment by trjExpensify** [comment]
Why do we even show the `Hold request` menu item for an expense that's approved/paid already? Wouldn't we just not show it, like we don't others like `Delete receipt` in those states?

**Comment by dannymcclain** [comment]
>Why do we even show the Hold request menu item for an expense that's approved/paid already? Wouldn't we just not show it, like we don't others like Delete receipt in those states?

@trjExpensify In this situation, someone opened the hold request menu item _before_ the state that would remove that menu item was triggered. I don't expect something like this would happen a lot, but seeing as how it's possible, it seems like we should come up with a graceful solution to handle it.

**Comment by trjExpensify** [comment]
>@trjExpensify In this situation, someone opened the hold request menu item before the state that would remove that menu item was triggered. I don't expect something like this would happen a lot, but seeing as how it's possible, it seems like we should come up with a graceful solution to handle it.

Oh, haha.. yeah, super edge case. Cool, I agree with ya'll on: 

>I would just block form submission on the hold modal in this case, letting them know that the expense status changed and they can no longer hold it as the form error message

**Comment by alitoshmatov** [comment]
So to sum up my understanding based on above interactions, correct me if I am wrong:

_We want to show error when hold button is pressed but report is already paid_

**Comment by alitoshmatov** [comment]
@neonbhai Thank you for your proposal, I think your proposal is closest one to our end goal. Do mind providing with more details on how would implement showing error when hold button is pressed

**Comment by alitoshmatov** [comment]
@dukenv0307 Based on above conclusion I believe your solution does not align with our end goal.

**Comment by alitoshmatov** [comment]
@WikusKriek Thank you for your proposal, your proposal is very similar to @neonbhai 's proposal. Can you also give more details on how exactly would you implement this

**Comment by alitoshmatov** [comment]
Okay, we can go with @WikusKriek 's [proposal](https://github.com/Expensify/App/issues/37014#issuecomment-1960245817). 

@WikusKriek But we should change error text and confirm it with others

C+ reviewed 🎀 👀 🎀

**Comment by robertjchen** [comment]
Agreed with @WikusKriek  proposal 👍  Let's move forward with the PR, and we can finalize the messaging when reviewing it

**Comment by JmillsExpensify** [comment]
@alitoshmatov Do you mind helping with the BZ checklist? In the meantime, payment summary as follows:

 - Contributor: @WikusKriek $500
 - Contributor+: @alitoshmatov $500

**Comment by alitoshmatov** [comment]
@JmillsExpensify Completed the checklist

**Comment by JmillsExpensify** [comment]
Many thanks! All contracts have been paid out.
