### ISSUE TITLE
[iOS] Our custom audio cue sounds stops device music from playing

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#37011]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Be signed in on an iOS device
- Be listening to music 
- The app should be backgrounded
- Send a message to the user from another account

## Expected Result:
- Music/audio should continue after the cue sound is played

## Actual Result:
- Music/audio does not continue after the cue sound is played

## Platforms:

This was only reported for iOS, other platforms haven't been tested.
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106c5e948f3fd9c47</li>
        <li>Upwork Job ID: 1760285630278660096</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Julesssss</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Julesssss</details>

**Comment by kirillzyusko** [comment]
I'm ready to work on this ticket 👍

**Comment by Julesssss** [comment]
Thanks, yeah. I found an alternative way of testing and will get back to you shortly 👍

**Comment by kirillzyusko** [comment]
@Julesssss just a friendly ping, you wrote that 4 days ago 👀 

>  I found an alternative way of testing and will get back to you shortly 👍

Do you have any updates?

**Comment by Julesssss** [comment]
Thanks for the reminder, will test today.

**Comment by Julesssss** [comment]
Here's iOS. It's not perfect, but music does start playing after the notification was received. Closing this, we can improve further later on.

https://github.com/Expensify/App/assets/10736861/56f5508f-0b3a-488e-968a-ed54dc7bad6c
