### ISSUE TITLE
Clear status after page list is empty

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37029]
Coming from [here](https://github.com/Expensify/App/pull/37000#pullrequestreview-1893528574), we updated selection list and need to update the instance of BaseListItem in StatusClearAfterPage.

cc @burczu @getusha

**Comment by dylanexpensify** [comment]
Woot! Let's get it!

**Comment by dylanexpensify** [comment]
payout didn't generate but it's due now, so will work on it!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @getusha $500

Please request/apply!

**Comment by getusha** [comment]
@dylanexpensify oh this was a follow up from https://github.com/Expensify/App/pull/37000, we can close it.
