### ISSUE TITLE
[$500] Hold Request - Approving report that has expenses on hold removes "hold" status

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37020]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/33897

**Version Number:** 1.4.43-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team
**Slack conversation:**

## Action Performed:
precondition: create a workspace, and invite an employee and approver
1. Go to https://staging.new.expensify.com/

2. Log in as an employee
3. Navigate to a workspace chat
4. Create a manual request
5. Submit the report to the approver
6. Navigate to the expense detail page in the submitted report
7. Click on 3 dots > Hold request
8. Enter a reason and hold request
9. In incognito, login in ND as the approver
10. Approve the submitted report

## Expected Result:
The report is approved and the system message is added, the expense is still on hold

## Actual Result:
The expense status "Hold" is removed, and the system message says that the "<approver> unheld this money request"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5611bdd1-f8e6-44eb-b967-02da2099a4c7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e61187168c0a96ba</li>
        <li>Upwork Job ID: 1760303385679118336</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by sakluger** [comment]
This is related to our newly released Hold Requests feature (https://github.com/Expensify/Expensify/issues/274076) which is part of Wave 7.

**Comment by BartoszGrajdek** [comment]
This is the expected behavior right now - it will be handled better after we finish [this issue](https://github.com/Expensify/App/issues/31345)
