### ISSUE TITLE
“Hm… it’s not there” error when opening a specific expense which was "hold request"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @danielrvidal  and @justinpersaud 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708446435991959

## Action Performed:
1. user A sends a $10 expense
2. Approver  went into the expense to hold the expense and it was held
3. Click on the expense to view the details of the expense

## Expected Result:
- User A should get notified about the hold
- Able view the expense details as approver

## Actual Result:
- User A not notified about the hold
- getting  Hmm… its not here in the expense details as approver

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (8)](https://github.com/Expensify/App/assets/38435837/ade9cca8-cb66-446f-874d-29cacf7f3e02)

![image (9)](https://github.com/Expensify/App/assets/38435837/f2ad3cea-5fea-4f30-bd32-7eda9a0d4283)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
I'm going to close this as I'm not able to consistently reproduce and it seems like @justinpersaud is able to open the expense just fine. @danielrvidal feel free to reopen if I've misunderstood or you're able to reproduce.
