### ISSUE TITLE
[$500] HIGH: Web - Workspace - Email invites aren't being sent to users who are invited via rooms

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/App#37067]
Splitting this out from https://github.com/Expensify/App/issues/36378

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a workspace
3. Create a room
4. Invite a few members who don't have existing Expensify accounts
5. Check the email client

## Expected Result:
Invite/welcome emails should be delivered

## Actual Result:
Emails aren't received

## Workaround:
Unknowns

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38236554/19aea739-8e63-45f1-b4cf-f526469c215b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016a8e93511c34c648</li>
        <li>Upwork Job ID: 1757156885762093056</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by Habtamu-Asefa** [comment]
Looks BE to me. Can someone confirm? @bfitzexpensify @aimane-chnaif

**Comment by godofoutcasts94** [comment]
I tried to reproduce it but I am unable to do so as I am getting an email on the test account if I am inviting someone. 

### Video/Screenshot

https://github.com/Expensify/App/assets/158435970/6a8e37e8-5f2f-4f46-b0e2-2321485da586

**Comment by Tony-MK** [comment]
The front end is sending `inviteeEmails` as expected.

Therefore, I suppose the backend is not sending the emails to the list of `inviteeEmails`.

![inviteToRoom](https://github.com/Expensify/App/assets/22982173/99078e59-e4e1-4fab-b580-f348d0b4fbc4)

**Comment by iwiznia** [comment]
I am very confused by this issue... 3 people tried to reproduce and could not? Can someone still reproduce? Moreover, is this only happening on osx? That's even weirder and most probably indicates that this is not a backend issue

**Comment by bfitzexpensify** [comment]
So strange. I can still reliably reproduce across Chrome on MacOSX, Android and Windows 11 (Chrome) via BrowserStack, and iOS using a physical device. I've used two different test accounts (bfitz@expensifail.com and bfitztestinginvite@gmail.com) on all three devices, played around with workspace visibility settings (public, workspace, private) and tried triggering invite emails to both gmail.com accounts and expensifail.com accounts - and in every flow, I never receive an invite. 

@godofoutcasts94 @kaushiktd @Tony-MK what platforms are you testing on?

**Comment by Tony-MK** [comment]
@bfitzexpensify, I tested it with Chrome on MacOSX.

**Comment by godofoutcasts94** [comment]
@bfitzexpensify, I tested it now with Chrome on MacOSX. It is reproducible now.

**Comment by kaushiktd** [comment]
@bfitzexpensify I tested it again and it is reproducible. 
MacOS 14.1 and chrome Version 122.0.6261.57 (Official Build) (arm64)

**Comment by godofoutcasts94** [comment]
Just wanted to tell you that after 2 hours, I got the invite email on my inbox for room invite.

**Comment by Habtamu-Asefa** [comment]
> Just wanted to tell you that after 2 hours, I got the invite email on my inbox for room invite.

got the same thing here

**Comment by iwiznia** [comment]
oh ok, so seems it is working, but slow. Were those tests done against prod or staging? I am suspecting that staging might be slower to send emails

**Comment by bfitzexpensify** [comment]
I've been testing on prod - and 24 hours later, I have no emails at all. 

(I did confirm last week that I'm actually able to receive invite emails to both inboxes by inviting related accounts another way)

**Comment by bfitzexpensify** [comment]
@iwiznia let me know if there's any specific testing you have in mind that would help here - seems like there isn't an obvious pattern to follow so far

**Comment by iwiznia** [comment]
Well I don't know what to do because I am not sure what is broken.
Can you retest and include all the information from your test here please? (accountID/email, date and time of the test, requestIDs, etc)

**Comment by iwiznia** [comment]
No, I don't think so.

**Comment by bfitzexpensify** [comment]
>Can you retest in production and include all the information from your test here please? (accountID/email, date and time of the test, requestIDs, etc)

Yes, can do - if I don't get around to this today, I will do it tomorrow

**Comment by bfitzexpensify** [comment]
OK, I have no idea what's changed, but this is now working for me - I'm getting email invites immediately.

@godofoutcasts94 @Tony-MK @Habtamu-Asefa you were all able to reproduce this - are you still able to reproduce or is this behaving as expected now?

**Comment by Tony-MK** [comment]
@bfitzexpensify, Works flawlessly on staging. 🚀
