### ISSUE TITLE
[HOLD for payment 2024-03-22] [$250] [Simplified Collect] [Profile] Add QRCode icon to share button in Workspace profile page and Trash can icon to workspace delete button

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37089]
Coming from [here](https://github.com/Expensify/App/pull/36907#issuecomment-1959539370), we want to add a QR Code icon to the share button in the Workspace profile page.

Also as follow up to https://github.com/Expensify/App/pull/37528, please add trashcan icon to the workspace delete button https://github.com/Expensify/App/pull/37528

cc @narefyev91  
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1e510102dc2c0f1</li>
        <li>Upwork Job ID: 1760727451269500928</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by shawnborton** [comment]
cc @Expensify/design

**Comment by dannymcclain** [comment]
Alrighty here's what I've got written out for the button specs. @shawnborton & @dubielzyk-expensify, does this all look right to you? Anything you want to change while we're updating the global styles for the buttons?

Showing light mode and dark mode for visual reference, but the variables should be the same across themes.
![image](https://github.com/Expensify/App/assets/7516624/7135d412-242d-4f46-b539-2becfbcd6980)
![image](https://github.com/Expensify/App/assets/7516624/2c4a97d9-e3be-4900-8997-b21152814662)

![image](https://github.com/Expensify/App/assets/7516624/97150e83-49a7-4162-90a0-5e4e8482902c)
![image](https://github.com/Expensify/App/assets/7516624/71282f5a-9fd8-4406-b013-c62a96a09ccd)

**Comment by narefyev91** [comment]
Hi! I'm Nicolay from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by dubielzyk-expensify** [comment]
That looks right to me @dannymcclain

**Comment by shawnborton** [comment]
Looks amazing! We should describe our buttons that way in the Figma design system file. I think we chatted about that previously, but I love how you've laid everything out here.

**Comment by luacmartins** [comment]
This is low priority right now. @narefyev91 will get to it once his higher priority items are done.

**Comment by luacmartins** [comment]
Same as above

**Comment by mountiny** [comment]
this is available for proposals, we need to update two buttons, one of them is in this PR https://github.com/Expensify/App/pull/37528 soon to be merged

**Comment by narefyev91** [comment]
@mountiny @luacmartins i will pick this one - as it was a part of wave - please assign to me

**Comment by luacmartins** [comment]
@narefyev91 done!

**Comment by sobitneupane** [comment]
Rather than a bug, it's addition of some buttons and change in styling. So, I don't think the checklist is relevant here.

**Comment by sobitneupane** [comment]
@kevinksullivan I will need payment summary to request payment.

**Comment by luacmartins** [comment]
PAYMENT SUMMARY
Fix: [@narefyev91 ](https://github.com/tienifr) - invoiced
PR Review: [@sobitneupane](https://github.com/getusha) $250 for PR review

**Comment by luacmartins** [comment]
Just pending payment

**Comment by luacmartins** [comment]
Bump for payment @kevinksullivan

**Comment by sobitneupane** [comment]
I will request payment in newdot.

**Comment by luacmartins** [comment]
Ok, so seems like we can close this issue since the payment summary was posted and @sobitneupane will request payment via NewDot.

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
