### ISSUE TITLE
[Awaiting Payment 7th March] [Simplified Collect] [Members] Update member page translation and subtitle color

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37096]
Coming from [this review](https://github.com/Expensify/App/pull/37074#pullrequestreview-1896383974), we need to update the new Member page subtitle color and translation.

cc @burczu

**Comment by burczu** [comment]
@lschurr Could you please assign me? It's a bug created in my recent change and I already have a PR prepared.

**Comment by luacmartins** [comment]
Done!

**Comment by burczu** [comment]
The PR is ready for review: https://github.com/Expensify/App/pull/37123

**Comment by trjExpensify** [comment]
Updated the title and labels to reflect the payment hold, @lschurr. Coupla' days to go.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @burczu (agency - no payment needed)
- Contributor+: @rushatgabhane $500 (please request payment via newdot)

**Comment by lschurr** [comment]
Sorry for the delay on this one! We're all set.

**Comment by lschurr** [comment]
Ah, sorry about that @parasharrajat - GH autofilled incorrectly. I'm updating the payment summary - https://github.com/Expensify/App/issues/37096#issuecomment-2007974582

**Comment by lschurr** [comment]
You're paid via newdot right @parasharrajat?

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
