### ISSUE TITLE
[HOLD for payment 2024-04-03] [$500] In-app sounds play in the background and message received sounds play while not viewing the chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-12
**Reproducible in staging?:** y
**Reproducible in production?:**y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @arosiclair 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708621869934919

## Action Performed:
1.  Log in
2. Open a chat
3. Minimize the window or switch tabs
4. Receive a message in the chat

## Expected Result: 
No sounds play for the message

## Actual Result: 
The message received sound plays

## Workaround:
unknown

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ab7662a4d0687c6</li>
        <li>Upwork Job ID: 1760735530618884096</li>
        <li>Last Price Increase: 2024-02-29</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment]
Hmm actually on second look, I don't think this is a bug. The messaging sounds are about playing sounds each time a message is received. The notification preference is related to push notifications or email notifications about when emails are received. 

Curious if you agree @Julesssss @kirillzyusko

**Comment by arosiclair** [comment]
Reached a better understanding [here](https://expensify.slack.com/archives/C049HHMV9SM/p1708637780490049?thread_ts=1708621869.934919&cid=C049HHMV9SM):

> I guess in my head there are only
>
> - In-app sounds
> - Notification sounds
>
> These are in-app sounds so the root problem would really be that we're playing in-app sounds while the app is in the background. When they play in the background they act like "notification sounds" and are ignoring my notification preference

So to fix this we should just mute our in-app sounds (like the message sent/received sounds) while the app is in the background. We should be able to check that with [Visibility.isVisible()](https://github.com/Expensify/App/blob/82b76c1a36cf1a01b00c14510a5812a591e7f2fd/src/libs/Visibility/index.ts#L7)

**Comment by kirillzyusko** [comment]
@shawnborton I think you are right. @Julesssss curious about your opinion 👀

**Comment by Julesssss** [comment]
> The notification preference is related to push notifications or email notifications about when emails are received.

Yeah, I agree with this. Currently, it feels very weird on iOS/Android, but we are in the process of removing the in-app sound for mobile and moving the sound to the push notification.

**Comment by shawnborton** [comment]
Also just wanted to note here, I do think that while you are actively viewing a chat message, it makes sense to play the chat sounds even if you have notifications set to Weekly. I think there is a difference between in-app sounds vs when you are notified about new chats.

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by abdulrahuman5196** [comment]
@dukenv0307 I dont see this in the expectation mentioned above (although I see some discussions on slack related to same)

> In foreground, mute in-app sounds in two cases: One case is when "Mute all sounds from Expensify" is set to true and another case is when user is not actively viewing a chat



@arosiclair Could you kindly confirm if below is the only expectation to solve? As mentioned by you here - https://github.com/Expensify/App/issues/37098#issuecomment-1960367899

>So to fix this we should just mute our in-app sounds (like the message sent/received sounds) while the app is in the background

**Comment by arosiclair** [comment]
Yeah sorry for the moving target. We had some more discussion in [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1708621869934919) and came to [this conclusion](https://expensify.slack.com/archives/C049HHMV9SM/p1708697904040859?thread_ts=1708621869.934919&cid=C049HHMV9SM):

> - Muting in-app sounds while the app is in the background
> - Muting in-app message received sounds while not viewing the chat

I'll update the title and description

**Comment by arosiclair** [comment]
> What about when we are in single pane homepage? Shouldn't we need to notify with sound in this case?

Yes this is already handled by push notifications. In-app sounds should not play in this case.

**Comment by zanyrenney** [comment]
has the proposal been updated @arosiclair ?

**Comment by abdulrahuman5196** [comment]
Hi @zanyrenney It on review from my end. Will close it out today.

**Comment by abdulrahuman5196** [comment]
@dukenv0307 's proposal looks good and works well. He was first to cover both the cases mentioned here https://github.com/Expensify/App/issues/37098#issuecomment-1964425592

🎀 👀 🎀
C+ Reviewed

@arosiclair / @Julesssss

**Comment by abdulrahuman5196** [comment]
Hi @rayane-djouah 

> @abdulrahuman5196 the chosen proposal incorrectly plays the sound when we are in single pane homepage, but it should not plays the sound based on this [#37098 (comment)](https://github.com/Expensify/App/issues/37098#issuecomment-1964715762) , my proposal handle that. also, my proposal was first to cover both the cases mentioned here [#37098 (comment)](https://github.com/Expensify/App/issues/37098#issuecomment-1964425592) could you kindly explain why my proposal was not chosen?

IMO, both proposal are relatively similar as far as the Core requirement mentioned here https://github.com/Expensify/App/issues/37098#issuecomment-1964425592 goes.

>The chosen proposal incorrectly plays the sound when we are in single pane homepage, but it should not plays the sound based on this [#37098 (comment)](https://github.com/Expensify/App/issues/37098#issuecomment-1964715762)

I think this is minor case which could be added to the original requirement as I was the one raised this question. I think its like a more of PR level edge which could have been resolved at PR state.


>my proposal was first to cover both the cases mentioned here https://github.com/Expensify/App/issues/37098#issuecomment-1964425592

I did check the dates before approving. @dukenv0307 's proposal had both the requirements by 24th Feb, @rayane-djouah 's proposal had both the requirements by 26th Feb.
So I suggested the proposal which had both the requirements first.

**Comment by abdulrahuman5196** [comment]
@arosiclair / @Julesssss Do let us know if the accepted proposal here https://github.com/Expensify/App/issues/37098#issuecomment-1973600148 looks good.

**Comment by Julesssss** [comment]
Just one small change here @dukenv0307:

> In foreground, mute in-app sounds in two cases: One case is when "Mute all sounds from Expensify" is set to true and another case is when user is not actively viewing a chat

We only want to do this if the message is from the current chat you are viewing. If I am viewing a chat with you:
- **Messages from you:** I should hear the in-app sound, but no notification or notification sound
- **Messages from other people:** I should hear no in-app sound, but I should get the notification and notification sound

**Comment by nkdengineer** [comment]
I am working on the PR

**Comment by Julesssss** [comment]
> My suggestion is, we should consider that the user is viewing the chat in this case

Ah good spot. I think we'll need to handle this differently for Android/iOS, as they aren't going to see the message... We might also need to consider mWeb users

**Comment by arosiclair** [comment]
> > My suggestion is, we should consider that the user is viewing the chat in this case
>
> Ah good spot. I agree, but we'll need to check that isVisible works and if not maybe handle this differently for Android/iOS, as they aren't going to see the message...

Yeah this is a good point. Looking at the profile page is fairly rare though so maybe we can ignore that use case? If a user is looking at it and they're hearing message received sounds below it, they should understand what's happening.

**Comment by arosiclair** [comment]
Push notifications are currently hidden on web and mobile when viewing the profile page (because the report is under it).

**Comment by Julesssss** [comment]
Yeah, I haven't done this yet but I agree.

**Comment by zanyrenney** [comment]
Yep, makes sense to me!

**Comment by zanyrenney** [comment]
payment summary

@abdulrahuman5196 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer) paid $500 via Upwork
@dukenv0307 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) paid $500 via Upwork
