### ISSUE TITLE
Add React-Native-Share to package.json

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#37104]
In order to properly evaluate if a new library can be added to `package.json`, please fill out this request form. It will be automatically assigned someone from our review team that will go through and vet the library.

Note: This is only for production dependencies. While we don't want people to add packages to dev-dependencies willy-nilly, we recognize that there isn't as great of a need there to secure them.

# Name of library:

## Details
- Link to package: https://github.com/react-native-share/react-native-share
- Problem solved by using this package: Helps to correctly share the info files from the release profiler
- Number of stars in GH: 3.5k
- Number of monthly downloads: 1,096,940
- Number of releases in the last year: 18
- Level of activity in the repo: High (Commits yesterday and many three months ago)
- Alternatives: Default share from react-native but it [doesn't support sharing files directly, only text and URLs](https://github.com/Expensify/App/pull/36414#issuecomment-1963769348)
- Are security concerns brought up and addressed in the library's repo? Not in the repo. Since the library is well managed and widely used, I don't think they addressed security.
- How many dependencies does this lib use that will be brought into our code? [0](https://www.npmjs.com/package/react-native-share?activeTab=dependencies)
- What will the effect be on the bundle size of our code? It should be minimal, unpacked size is 314 kb

**Comment by srikarparsi** [comment]
Asked @situchan or @hoangzinh to [help](https://github.com/Expensify/App/pull/36414#issuecomment-1960238810) with the last three questions.

**Comment by perunt** [comment]
> could you please help with the last three questions

Security Concerns: I saw some security issues, which were quickly resolved what says it is properly maintained and updated on time

Dependencies: It has minimal external runtime dependencies and relies on peer dependencies.

Bundle Size Impact: Since the library does not list many direct dependencies and focuses on peer dependencies, its impact on your project's bundle size could be minimal.

**Comment by srikarparsi** [comment]
Thank you!

**Comment by srikarparsi** [comment]
Hey! Just updated the priority of this issue since we're waiting for approval of the node module for this [PR](https://github.com/Expensify/App/pull/36414). @chiragsalian do you think you could take a look at this whenever you get a chance :)

**Comment by srikarparsi** [comment]
Hey @perunt, do you think you could also take a look at these three questions. I put some answers on there, let me know what you think? And after that @chiragsalian said he could post the comment to get a vote.

1. Who maintains the library and how well is it maintained?
2. How viable are the alternatives?
3. Should we build it ourselves instead?

1. I'm not sure exactly who manages it but it seems to be maintained by the react-native community.
2. Native share is not too viable of an option - [Link](https://github.com/Expensify/App/pull/36414#issuecomment-1963769348)
3. I don't believe we should because it's a good amount of functionality and this library's primary purpose is to build and test that functionality.

**Comment by chiragsalian** [comment]
Not overdue melvin, waiting for responses before i can continue.

**Comment by perunt** [comment]
> 1. Who maintains the library and how well is it maintained?

The React Native Share library is pretty popular and well-supported, with thousands of developers pitching in. It's got a lively GitHub community that keeps it updated and fresh. So I wouldn't be afraid that it would be abandoned.

> How viable are the alternatives?

Tbh, there no alternatives with such a community

> Should we build it ourselves instead?

I don't think so. It definitely isn't the right area for us to allocate our resources.

**Comment by chiragsalian** [comment]
Thanks @perunt.

**Comment by chiragsalian** [comment]
@perunt, so i asked my colleagues and they mentioned,
> We just started to maintain/took over this library: https://github.com/Expensify/react-native-share-menu
So I do wonder if we could use this one instead 

Do you think we can use react-native-share-menu instead?

**Comment by srikarparsi** [comment]
Hey! We figured it out [here](https://expensify.slack.com/archives/C03TQ48KC/p1709768084510189?thread_ts=1709765356.128269&cid=C03TQ48KC). Looks like they have different functionalities.

**Comment by perunt** [comment]
I have no access to this chat, but it looks like we can't share multiple files with that lib.

**Comment by chiragsalian** [comment]
We [decided](https://expensify.slack.com/archives/C03TQ48KC/p1709854933062159?thread_ts=1709765356.128269&cid=C03TQ48KC) to proceed and add this library.
