### ISSUE TITLE
[CRITICAL] [VIP-Travel] [HOLD for payment 2024-05-16] Add Terms and Conditions Modal (NewDot)

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#37102]
## VIP-Travel Implementation Issue
Tracking Issue: https://github.com/Expensify/Expensify/issues/333471
Project: https://github.com/orgs/Expensify/projects/112/views/1?layout=board
Relevant Design Doc Section: 

# Feature Description
1. Create a new Right Hand Modal (screen) for our travel Terms and Conditions
2. Create a new action for `AcceptTravelTerms`

<img width="612" alt="2024-02-22_12-58-51" src="https://github.com/Expensify/App/assets/42391420/fb670fc6-ba1b-4f0f-bf9e-861a9c6c141b">
<img width="594" alt="2024-02-22_12-59-00" src="https://github.com/Expensify/App/assets/42391420/b03d80f9-b19c-4927-ab6a-771d3163b7d7">

<details>
<summary>Detailed Instructions</summary>
A new page, TravelTerms.ts will be created in src/pages/Travel: 
If the user is not on the travel beta, we’ll display a [blocking View ](https://github.com/Expensify/App/blob/main/src/components/BlockingViews/FullPageNotFoundView.tsx)instead
It will include a [HeaderWithBackButton](https://github.com/Expensify/App/blob/main/src/components/HeaderWithBackButton/index.tsx) component with “Before we continue…” as the title.
It will include the text displayed above (hyperlinks TBD) and a [checkboxWithLabel](https://github.com/Expensify/App/blob/main/src/components/CheckboxWithLabel.tsx) component for the user to agree with the terms.
Lastly, it will include a <Button> (disabled until the checkbox is checked) as shown above:
 On click, it will call a new command, [AcceptTravelTerms](https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit?pli=1#bookmark=id.1b1k3v847xja), to update NVP.travelSettings.hasAcceptedTerms or provision the workspace, and redirect the user to travel.expensify.com.
If network.isOffline is true, it will be disabled, and the usual “You appear to be offline” message will display below.

</details>

# Manual Test Steps
1. Log in on a new account
2. Create a workspace
3. Go to travel
4. Click the book travel button
5. Make sure the T&C appears
6. Make sure that if you don't check the box you cannot accept t&c
7. Accept the T&C
8. Look at the network request and ensure that we returned new policy and user data for the newly provisioned accounts

# Automated Tests
Test for AcceptTravelTerms action
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a02f3de0cecfaf7</li>
        <li>Upwork Job ID: 1760758341962240000</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

Routes table:
https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.gn6jbl2udlnx

**Comment by stitesExpensify** [comment]
Re-assigning this to Ted since he is curating this implementation. Also temporarily removing c+ since this project has not started yet

**Comment by cdOut** [comment]
Hello, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I'd like to work on this task.

**Comment by twisterdotcom** [comment]
Great! Assigned you @cdOut

**Comment by cdOut** [comment]
As an update, I’ll be creating a draft PR for this feature and also [the main travel page](https://github.com/Expensify/App/issues/37103) today.

**Comment by twisterdotcom** [comment]
Possible we'll hold this and not requie a ToS interstitial: https://expensify.slack.com/archives/C05S5EV2JTX/p1711726076366499

**Comment by twisterdotcom** [comment]
See PR comment here: https://github.com/Expensify/App/pull/38469#issuecomment-2048557477

**Comment by twisterdotcom** [comment]
Can we make this ready for review yet @cdOut? The URL for the travel terms will be use.expensify.com/travelterms

**Comment by cdOut** [comment]
@twisterdotcom We'll prioritize on pushing this through review.

**Comment by rushatgabhane** [comment]
all set. PR merged

**Comment by twisterdotcom** [comment]
This is on Prod right? We just need to pay out @rushatgabhane and @shubham1206agra now I think?

**Comment by twisterdotcom** [comment]
Payment Summary:

- @shubham1206agra paid $500 [here](https://www.upwork.com/nx/wm/offer/102359427) (C+)
- @rushatgabhane paid $500 via newDot requests

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
