### ISSUE TITLE
Disable setting currency for members

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37100]
Currently, workspace members are able to select the Currency row in the Profile page and doing so leads to a not found page. Members shouldn't be able to interact with that row.

cc @narefyev91

**Comment by luacmartins** [comment]
Gonna close this issue

**Comment by luacmartins** [comment]
@JmillsExpensify we closed the PR because there was a dupe issue and that PR got merged first. However, @getusha had already completed the checklist, could you help with payment?

**Comment by JmillsExpensify** [comment]
Payment summary: $500 for PR reviews.

**Comment by JmillsExpensify** [comment]
All paid out, so closing this one.
