### ISSUE TITLE
Add React-Native-Release-Profiler to package.json

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#37105]
In order to properly evaluate if a new library can be added to `package.json`, please fill out this request form. It will be automatically assigned someone from our review team that will go through and vet the library.

Note: This is only for production dependencies. While we don't want people to add packages to dev-dependencies willy-nilly, we recognize that there isn't as great of a need there to secure them.

# Name of library: React-Native-Release-Profiler

## Details
- Link to package: https://github.com/margelo/react-native-release-profiler
- Problem solved by using this package: Helps us profile performance in production builds ([Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1707758148919829))
- Number of stars in GH: 153
- Number of monthly downloads: it's a fresh library, so the download amount per week is about 100+
- Number of releases in the last year: 7 (was released two months ago)
- Level of activity in the repo: Medium (commits [monthly](https://github.com/margelo/react-native-release-profiler/commits/main/?before=07f115437d633369f1bb955cae2e79fd73dfa8bd+35))
- Alternatives: There are no alternatives that let you do profiling in the release
- Are security concerns brought up and addressed in the library's repo? Dependencies like @react-native-community/cli and commander are widely used and maintained, implying regular security updates.
- How many dependencies does this lib use that will be brought into our code? It has two main dependencies, which suggests a lightweight addition to your project without significantly increasing the number of indirect dependencies.
- What will the effect be on the bundle size of our code? Likely negligible for production builds.

**Comment by srikarparsi** [comment]
Asked @situchan or @hoangzinh to [help](https://github.com/Expensify/App/pull/36414#issuecomment-1960238810) with the last three questions.

**Comment by situchan** [comment]
I think you wanted to tag @hannojg

**Comment by hannojg** [comment]
Tagging @perunt and @Szymon20000 as they are working on the integration

**Comment by perunt** [comment]
> could you please help with the last four questions as well as the number of monthly downloads.

Alternatives: There are no alternatives that let you do profiling in the release

Security Concerns: Minimal. Dependencies like @react-native-community/cli and commander are widely used and maintained, implying regular security updates.

Dependencies: It has two main dependencies, which suggests a lightweight addition to your project without significantly increasing the number of indirect dependencies.

Monthly downloads:
it's a fresh library, so the download amount per week is about 100+

Bundle Size Impact: Likely negligible for production builds. The CLI tool is for development use and won't be included in the production bundle. Also, the commander is really small.

**Comment by srikarparsi** [comment]
Awesome thanks! Updated the issue body

**Comment by srikarparsi** [comment]
Hey! Just updated the priority of this issue since we're waiting for approval of the node module for this [PR](https://github.com/Expensify/App/pull/36414). @Beamanator  do you think you could take a look at this whenever you get a chance :)

**Comment by Beamanator** [comment]
Hey hey I'll review today!

**Comment by Beamanator** [comment]
As seen in the slack post ^ we've got 9 out of 14 app deployers with 👍  so far, so let's move forward! @srikarparsi you've got this from here?

**Comment by srikarparsi** [comment]
Yup! Thanks @Beamanator!
