### ISSUE TITLE
[HOLD for payment 2024-03-07] Desktop - App becomes unusable after`clear cache and restart`

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37116]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @mallenexpensify and @muttmuure 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708636284808519

## Action Performed:

1. Go to account settings > about > troubleshoot
2. Click on "clear cache and restart"
3. Send messages after restarted

## Expected Result:
Able to send messages

## Actual Result:

- App isn't useable, likely because of ,\"jsonCode\":407,\"  which (apparently) means  auth token is expired.  
- have to sign out/in, then chats start loading (which takes a while cuz it reloads all chats)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (3)](https://github.com/Expensify/App/assets/38435837/6f39abf3-0ade-43cb-a1ce-c581bdbece99)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Also.. I had to sign out/in twice in order to get all my chats to show properly in LHN.  Pinned chats and tasks weren't all loading, even after 5+ hours and with hard refreshing

**Comment by trjExpensify** [comment]
Reached out to the author of https://github.com/Expensify/App/pull/36337 [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1708694749956519).

**Comment by TMisiukiewicz** [comment]
Hi, I would like to be assigned to this issue

**Comment by trjExpensify** [comment]
Any movement on this one, @TMisiukiewicz?

**Comment by TMisiukiewicz** [comment]
Sorry, I was on a sick leave on Monday and Tuesday, I had a discussion with @techievivek [here](https://expensify.slack.com/archives/C049HHMV9SM/p1708922268823399?thread_ts=1708655148.979099&cid=C049HHMV9SM), I'll verify this solution today and open a PR if it works fine.

**Comment by trjExpensify** [comment]
Dev tool bug and no C+ review of this PR, so I'm closing it.
