### ISSUE TITLE
Chats are all cleared after login to NewDot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37110]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielvida
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708621955044169

## Action Performed:
1. Sign out of the app
2. Try to sign in back

## Expected Result:
Able to sign in and all the chats are showing

## Actual Result:
Not able to login and after few attempts able to login, but all the chats are cleared. 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (1)](https://github.com/Expensify/App/assets/38435837/ccb563ae-c1f5-49fd-8d61-729b4f73c3e0)

![image](https://github.com/Expensify/App/assets/38435837/03d8817c-44b9-4ef3-bd15-b9cc4edb0b16)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Attempted to reproduce on production, web, Chrome, with my mallen@expensify.com account, no luck.  Bumping to `Weekly` to see if anyone else encounters this.

**Comment by mallenexpensify** [comment]
I think this was related to About > Troubleshoot > Clear cache.  If so, that is being addressed below, so I'm closing this
- https://github.com/Expensify/App/issues/37116
