### ISSUE TITLE
[$500] LHN shows the user's email who are in the contacts, in public rooms

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-14
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rushatgabhane 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708644177064729

## Action Performed:
Precondition : User A and B have DM's. C does not have DM with either A and B

1. In a public room, join with all users A,B,C
2. As a user A, mention user B

## Expected Result:
User C should not see the email of mentioned user B

## Actual Result:
User C can see the user B email address eventhough does not have DM before

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-02-23 at 8 44 01 AM](https://github.com/Expensify/App/assets/38435837/545e37b1-5217-4f09-b19e-95075a89d029)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0132291a955edb25ed</li>
        <li>Upwork Job ID: 1761025056680591360</li>
        <li>Last Price Increase: 2024-02-23</li>
    </ul>
</details>

**Comment by c3024** [comment]
@dylanexpensify As per [this discussion here](https://expensify.slack.com/archives/C049HHMV9SM/p1708696404809229?thread_ts=1708644177.064729&cid=C049HHMV9SM) this is being [fixed here](https://expensify.slack.com/archives/C049HHMV9SM/p1708696404809229?thread_ts=1708644177.064729&cid=C049HHMV9SM).

This issue can be closed.
