### ISSUE TITLE
[Wave Collect] [Remove Free Workspace Creation] Remove Free Plan Creation on OldDot

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#37148]
Coming from the design doc section [here](https://docs.google.com/document/d/16ptT3EbBMHCP7TzUBlRADWuBASo3pL12d_Z0wYr38c4/edit#bookmark=id.fbmdhs7mf1h7)

Remove [this option](https://github.com/Expensify/Web-Expensify/blob/5cdb4e325cf432b6372c27d6761f4ac441cef64d/site/app/policyEditor/plan/GroupPlanSelection.jsx#L111) from the GroupPlanSelection component
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ebf74810037aacf</li>
        <li>Upwork Job ID: 1761070206959403008</li>
        <li>Last Price Increase: 2024-02-23</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
This is on prod and an OldDot issue - can we close it?

**Comment by johnmlee101** [comment]
Ah yeah it didn't auto-close!
