### ISSUE TITLE
[Wave Collect] [Remove Free Workspace Creation] - Update Notifications in OldDot

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#37149]
Coming from the design doc section [here](https://docs.google.com/document/d/16ptT3EbBMHCP7TzUBlRADWuBASo3pL12d_Z0wYr38c4/edit#bookmark=id.nevu5cggy369) (further instructions in the doc)

- Update the message that is posted in this #admins room that comes from the guide
- Update the params for Notification_Share_CreateInvitedAccountSharePolicy to include different from and replyTo values
- Update Concierge messages
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cefb307b6a228c34</li>
        <li>Upwork Job ID: 1761070291917881344</li>
        <li>Last Price Increase: 2024-02-23</li>
    </ul>
</details>

**Comment by Gonals** [comment]
I'll grab this for tomorrow 😁

**Comment by Gonals** [comment]
@tgolen, should we also update `_libfop.php SInviteUsers()` to no longer send notifications from newDot or is that covered in a different issue?

**Comment by tgolen** [comment]
Yeah. I did a small update to the design doc (I think yesterday) to include that. I would use the design doc as the source of truth for what to do. I didn't want to copy everything from the design doc into this issue, so the issue description was only meant to be an overview of what needs to happen. Let me know if you have more questions after reading the design doc. I see you in there now.

**Comment by Gonals** [comment]
> Yeah. I did a small update to the design doc (I think yesterday) to include that. I would use the design doc as the source of truth for what to do. I didn't want to copy everything from the design doc into this issue, so the issue description was only meant to be an overview of what needs to happen. Let me know if you have more questions after reading the design doc. I see you in there now.

All good! Thanks!

**Comment by tgolen** [comment]
This is done and deployed
