### ISSUE TITLE
[Remove Free Workspace Creation] Make all Collect Policies Created From NewDot Accessible In NewDot

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#37151]
Coming from the design doc section [here](https://docs.google.com/document/d/16ptT3EbBMHCP7TzUBlRADWuBASo3pL12d_Z0wYr38c4/edit#bookmark=id.k3nkmq89dd6q)

Update api.php to set the `isPolicyExpenseChatEnabled` param to true [here](https://github.com/Expensify/Web-Expensify/blob/1c355c41dc0f10a47e98e30ab8784d14b1942441/api.php#L761-L779)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3d619776771ca87</li>
        <li>Upwork Job ID: 1761070565271715840</li>
        <li>Last Price Increase: 2024-02-23</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
As this was a Web-PR and it hit prod 2 days ago, can we close this issue?

**Comment by tgolen** [comment]
Yep!

**Comment by tgolen** [comment]
@GandalfGwaihir I took a look at that commend. Are you saying that when you create a new workspace in NewDot, it is not being returned with `isPolicyExpenseChat` enabled?

cc @dangrous

**Comment by tgolen** [comment]
OK, that's a shame. I've pinged the backend engineers to have them look into it and see what might be going on. cc @Gonals @dangrous

**Comment by Gonals** [comment]
I didn't work a lot on setting this, but I `think` this may be somewhat expected behavior. If we look at the `isPolicyExpenseChatEnabled` function in PHP, we see it returns true if isPolicyExpenseChatEnabled is set **OR** the workspace  is free. I believe we do not set `isPolicyExpenseChatEnabled` for free workspaces at all.

**Comment by Gonals** [comment]
> Actually we are creating Collect Policy with this [PR](https://github.com/Expensify/App/pull/38191), and we want `isPolicyExpenseChatEnabled` to be true :)

Ah, gotcha! 
Looking at the flow in the backend, we seem to set the `isPolicyExpenseChatEnabled` flag to true... just to pass it back to onyx, but I'm fairly sure we are not correctly storing it in the DB. This would be consistent with the behavior you are seeing (initially set to true, but resets to false shortly afterwards).
I can create a quick PR to try to fix it

**Comment by Gonals** [comment]
> Any updates on the PR @Gonals ?

It is currently in staging
