### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] [Simplified Collect] [Workflows] Workflow submenu is selected after page reload

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37158]
Coming from [here](https://github.com/Expensify/App/pull/36345#pullrequestreview-1898683766), toggling on a option seems to select submenu item content see video below:

https://github.com/Expensify/App/assets/104348397/2df41af3-717b-406b-9a7e-719a00485426

Steps to reproduce:

1. In the Workspace Workflows page, toggle a switch and reload the page
3. Toggle off the switch and toggle it back on, the sub menu item will be selected
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0c4fa5757dac171</li>
        <li>Upwork Job ID: 1761102687235653632</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by adelekennedy** [comment]
payments made!
