### ISSUE TITLE
The footer text is same color as the body of the page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rushatgabhane 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708750080685859

## Action Performed:
1. ir.expensify.com
2. Scroll to the bottom and observe the footer

## Expected Result:
Footer text should be different from body of the text

## Actual Result:
The footer text is same color as the page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/cb14b76d-aedd-4ccb-8c37-3d6fabf463b4

![image (4)](https://github.com/Expensify/App/assets/38435837/1d1b5018-3b8f-412c-ba5a-212b5933c3ba)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment]
internal issue

**Comment by daksh4469** [comment]
Hi! I would love to take up this issue. 
Also, I am looking to contribute to Expensify and have mailed [contributors@expensify.com](mailto:contributors@expensify.com) multiple times to get an invite to the Contributor's slack channel but haven't got one yet. Please look into this.

Thanks!

**Comment by daksh4469** [comment]
Contributor details
Your Expensify account email: ddaksh.2711@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f07a48942ca14fad

**Comment by shawnborton** [comment]
Closing this as @NickTooker will handle in our own internal repos.
