### ISSUE TITLE
[HOLD for payment 2024-03-13] [Wave8] [Simplified Collect] [Workflows] Create Approval page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#37195]
We've recently merged the [main workflows page](https://github.com/Expensify/App/pull/36345).

The task here is to create the Approval page present under the main worfklows page.

It will appear when we click on the `>` icon under the `Add approval` menu item:
![image](https://github.com/Expensify/App/assets/21549771/54225466-83b6-40b6-97e7-d7d5dafd1ec8)

Expected mockup below:
<img width="691" alt="image" src="https://github.com/Expensify/App/assets/21549771/62e2b658-12cc-47bd-bd63-1a13d6519188">

Technical details can be found [here](https://docs.google.com/document/d/1T--VcAaCm-8aq5oEO78_vVXxBpXY1gq7NiJrboGZNcs/edit#bookmark=id.sjkymr1ikk7).

**Comment by lakchote** [comment]
@rushatgabhane will be doing the implementation. 

Assigning @allroundexperts as the reviewer.

 For context please see discussion [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1709017787200969?thread_ts=1709017652.394349&cid=C02NK2DQWUX)

**Comment by trjExpensify** [comment]
Wahoo! Let's do it.

**Comment by rushatgabhane** [comment]
Discussion here for real time - https://expensify.slack.com/archives/C02NK2DQWUX/p1709028046898869?thread_ts=1709017652.394349&cid=C02NK2DQWUX

**Comment by luacmartins** [comment]
PR is in staging

**Comment by allroundexperts** [comment]
I feel like this should have double the bounty since this was a feature that took much more time than what a normal bug would take to fix. What do you think @rushatgabhane?

**Comment by luacmartins** [comment]
Sure, I think that's fair in this case.

**Comment by luacmartins** [comment]
We discussed this internally with the team and we'll keep the bounty at $500 for this one. We understand that there'll inevitably be differences between the level of effort required for each issue, but we think that the current bounty is pretty generous across the board. We appreciate you both working on high value items like this one.

**Comment by trjExpensify** [comment]
Confirming the payment summary is correct. Both of you can go ahead and request on NewDot. Closing!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
