### ISSUE TITLE
Community Redirects for E.org

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#37212]
As part of Community Migration, we need to determine what to do with E.Org community Resources. Next steps below:

**Week of Febraury 26:**

- [ ] Check with Christina on E.org community articles and where each of those articles should be re-directed. Should each article just go directly to expensify.org or is there more specific URL's we want to send old community articles to? 
- [ ] Follow [this SO](https://stackoverflowteams.com/c/expensify/questions/18514) to set up the re-directs for each community link

**Comment by maddylewis** [comment]
consolidating here - https://github.com/Expensify/App/issues/37210 <3
