### ISSUE TITLE
[HOLD on 379005] HIGH: Email - Email addresses aren't displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37233]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.20
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/Web-Expensify/pull/40879

## Action Performed:
1. Create a workspace
2. Create a private room
3. Invite user B and C
4. Check the email for user C

## Expected Result:
Email addresses should be visible.

## Actual Result:
Email addresses aren't displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Capture](https://github.com/Expensify/App/assets/93399543/af0d71f2-710d-416d-8b97-65b15007535d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01748719a18ebba32b</li>
        <li>Upwork Job ID: 1762600721194434560</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by mallenexpensify** [comment]
From the post in Slack, added to #vip-vsb with a status of HIGH.  cc @puneetlath because this might be part of "known/unknown" users.

**Comment by puneetlath** [comment]
This is an internal back-end thing so going to un-assign @allroundexperts. 

I'll look into this as part of getting user mentions fully completed.

**Comment by quinthar** [comment]
This will be fixed by https://github.com/Expensify/Expensify/issues/379005#top; leaving open until it's fixed.

**Comment by puneetlath** [comment]
Working on it in the doc.

**Comment by quinthar** [comment]
Merged into https://github.com/Expensify/Expensify/issues/379005#top
