### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500]  iOS - Video - User needs to tap on play button twice for the video to restart

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4345661
**Email or phone of affected tester (no customers):** vdargentotest+ios022624@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Send a video
3. Tap on the video preview
4. Tap on the full screen button
5. Wait for the video to end
6. Tap on the play button

## Expected Result:
The video should be restarted after tapping on the play button one time

## Actual Result:
The user needs to tap on the play button twice for the video to restart

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d934eab1-364a-457d-b2d9-2c02ae274439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0749f5a1ec15cd0</li>
        <li>Upwork Job ID: 1762300460726202368</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by youssef-lr** [comment]
cc @francoisl

**Comment by mananjadhav** [comment]
Looking at PRs today, will check this tomorrow.

**Comment by ShridharGoel** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User needs to tap on play button twice for the video to restart on iOS.

### What is the root cause of that problem?
iOS logic for checking `shouldReplayVideo` has an issue.

https://github.com/Expensify/App/blob/dcf2e3e1ceebc8e598e6b51b61ebf76e297a2696/src/components/VideoPlayer/shouldReplayVideo.ios.ts#L6-L11

### What changes do you think we should make in order to solve the problem?
Update `shouldReplayVideo` method for iOS and remove the `e.isPlaying` check.

**Comment by mananjadhav** [comment]
yeah I think `e.isPlaying` check is unnecessary. Good to use @ShridharGoel 's [proposal](https://github.com/Expensify/App/issues/37249#issuecomment-1968594898).

But before we formally accept, I want to check with @tienifr @jjcoffee It was added in [this PR](https://github.com/Expensify/App/pull/36914). Do you think it would be break anything if we remove `e.isPlaying` check.

🎀 👀 🎀 C+ reviewed.

**Comment by ShridharGoel** [comment]
@mananjadhav I would like to update my proposal. We should change the implementation to this (tested the below code):

```
export default function shouldReplayVideo(e: AVPlaybackStatusSuccess, isPlaying: boolean, duration: number, position: number): boolean {
    if (!isPlaying && e.isPlaying && duration === position && !e.didJustFinish) {
        return true;
    }
    return false;
}
```

**Comment by mananjadhav** [comment]
@ShridharGoel With the updated version. I am not confident if we've covered the exact root cause. Could you please share some more information related to the documentation/some reference that shows this is the correct solution.

**Comment by mananjadhav** [comment]
Thanks for the bump, I'll check tomorrow.

**Comment by mananjadhav** [comment]
@ShridharGoel I saw your proposal. Few questions:

1. This is only an issue on iOS, then why do need to update the BasePlayer.  How will it impact Android?
2. I am not sure about `false` here. Because even if you don't pass fallback, `e.isPlaying` can be false/undefined, which still ends up being `!e.isPlaying && e.isPlaying`. 
3. I still don't understand the root cause from the proposal on why is it a problem on iOS only and not Android.

**Comment by mananjadhav** [comment]
Thanks for the clarification. That makes sense. The [updated proposal](https://github.com/Expensify/App/issues/37249#issuecomment-1968594898) here looks good to me. Works well as well.

🎀 👀 🎀 C+ reviewed.

**Comment by cead22** [comment]
> I am not sure if there exists any test for video replay. If it doesn't then we don't need to add a new one

Can you ask if we have one in expensify-open-source? If we don't, that's a good reason to add one imo

**Comment by MitchExpensify** [comment]
Invited you for Upwork payment here https://www.upwork.com/jobs/~0184c7f8e7c24fbbc1 @ShridharGoel

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav.

**Comment by cead22** [comment]
On hold for payment, not overdue

**Comment by MitchExpensify** [comment]
Paid and contract ended
