### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] [MEDIUM] Categories: "Parent" that does not have individual category is not grayed out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has Parent: Child category where the Parent does not have individual category.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Request money > Manual.
4. Enter amount > Next.
5. Click Show more > Category.

## Expected Result:
The "Parent" that does not have individual category will appear grayed out.

## Actual Result:
The "Parent" that does not have individual category is not grayed out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4a77a9b3-61f8-448c-a6c9-6cd027aef502

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014760c37372e21c4f</li>
        <li>Upwork Job ID: 1762259713696296960</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by cead22** [comment]
Since this is a minor aesthetic bug, I don't think it should be a blocker, and we can put this through the regular bug process

**Comment by cead22** [comment]
> * We also need to consider the case: category A is the selected category in ND. Then disable it in OD. In this case, selected category A is displayed as the selectable item. And when we click on it, the selected category is gone. It seem to be a bug so I think we also need to fix it by displaying it as the disabled item. We can update [this one](https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/components/CategoryPicker/index.js#L23) to:

If we update like you're saying, will users be able to de-select the selected (and disabled) category?

**Comment by cead22** [comment]
We discussed internally on slack, and we want the disabled category to show disabled and selected, but we want the user to be able to de-select it by tapping on it. Once the users taps on it, the list will close, and if the user taps on the category menu item again, the disabled category won't show up

**Comment by cead22** [comment]
@shubham1206agra does the update proposal look good to you?

**Comment by cead22** [comment]
That makes sense because we're creating a money request so there's no set tag or category, and the only categories and tags you can select are those that are enabled on the workspace. If that's accurate, then that's how it should work

**Comment by cead22** [comment]
On payment stage so not overdue

**Comment by muttmuure** [comment]
Handling

**Comment by muttmuure** [comment]
Original job failed and expired

**Comment by muttmuure** [comment]
https://www.upwork.com/jobs/~013b51541f9de74604

**Comment by muttmuure** [comment]
I've invited you both to a payment issue above

**Comment by muttmuure** [comment]
@shubham1206agra @dukenv0307

**Comment by muttmuure** [comment]
offers sent

**Comment by muttmuure** [comment]
Paying

**Comment by muttmuure** [comment]
Done
