### ISSUE TITLE
Android - Task-Tapping assignee shows infinite loading page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.44
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab-assign task
3. Enter title and tap next
4. Select share somewhere
5. Tap Create task
6. Tap on new task created to open details page
7. Tap assignee

Or
1. Tap settings
2. Tap workspaces----workspace
3. Tap members
4. Tap invite members

## Expected Result:
In task details page, tapping assignee must show contacts page
Tapping Workspace invite members must display contacts and must not load infinitely.

## Actual Result:
In task details page, tapping assignee shows infinite loading page.
Tapping Workspace invite members is also loading infinitely.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9c9c5c7b-3abc-454d-ba73-e187dc930fd9

https://github.com/Expensify/App/assets/115492554/510f1ffb-fc30-4b9c-9bea-c256739d1715

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by s77rt** [comment]
A regression from https://github.com/Expensify/App/pull/29991.

@hannojg @kirillzyusko This is another case of https://github.com/Expensify/App/issues/37156

**Comment by s77rt** [comment]
@dukenv0307 Thanks for the proposal. 

> This transitionEnd has been known to be unreliable

This is not the case. It's not firing only due to a recent navigation change as outlined above ^

**Comment by puneetlath** [comment]
PR that caused it was reverted.
