### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500]  Group - After selecting user in Group chat, the modal is not sliding upwards

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Click on the "+" > "Start chat"
4. Select user to "Add to group"

## Expected Result:
User expects that when a user is selected, the modal is slid upwards to show the selection

## Actual Result:
The modal does not slide upwards. Also, a few selected members are missing after scrolling back upwards.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4b479c2d-7b18-4f47-9891-fc451acddf69

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e254d49afd2fba2</li>
        <li>Upwork Job ID: 1762306611837190144</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:

https://github.com/Expensify/App/assets/78819774/85d60b03-c199-471c-be8c-e5fa5bca3ef9

**Comment by youssef-lr** [comment]
This seems to be coming from [here](https://github.com/Expensify/App/pull/31606), I reverted it locally and I can't reproduce. cc @Piotrfj @allroundexperts.

**Comment by askavyblr** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**

The modal slide upwards when the user selects "Add to group" 

**What is the root cause of that problem?**

https://github.com/Expensify/App/blob/d2a9c6faa9f450c20037a968974844f4f4325198/src/pages/NewChatPage.tsx#L118-L128

**What changes do you think we should make in order to solve the problem?**

To prevent removal from the list, it is require to make sure that certain conditions are met before allowing removal.

need to add a check to ensure that if an option is already on the list, it will only be removed if the number of selected options exceeds the minimum required.

**What alternative solutions did you explore? (Optional)**

**Comment by techievivek** [comment]
@Piotrfj @allroundexperts  Can you please take care of this deployblocker.

**Comment by nagypite** [comment]
There's some scrolling happening, but mostly to the wrong position (just below the selected list).

Additionally the selection logic seems to be faulty as well: the selected options sometimes reset when a new option is selected.

Here is a recording to prove the above points (left side: prod, right side: staging):
[Screencast at: 2024-02-27 11-06-34.webm](https://github.com/Expensify/App/assets/661868/74f2c25a-9ef2-4ee4-ac35-d25742a06536)

**Comment by nagypite** [comment]
Contributor details
Your Expensify account email: nagy.pite@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0161b2e93e88f95be5

**Comment by allroundexperts** [comment]
[This](https://github.com/Expensify/App/issues/37238) might fix this issue as well.

**Comment by allroundexperts** [comment]
Will test and confirm.

**Comment by allroundexperts** [comment]
Okay. @Piotrfj is on it already!

**Comment by askavyblr** [comment]
I update the proposal plz take a look
cc: @allroundexperts

**Comment by mallenexpensify** [comment]
> Okay. @Piotrfj is on it already!

@allroundexperts can you inc. a link next time so we can quickly view? 
For this, I see `Working on the regressions` in the [PR here](https://github.com/Expensify/App/pull/31606#issuecomment-1966620576)

**Comment by allroundexperts** [comment]
> @allroundexperts can you inc. a link next time so we can quickly view? For this, I see `Working on the regressions` in the [PR here](https://github.com/Expensify/App/pull/31606#issuecomment-1966620576)

You're right. Should have included that.

**Comment by Piotrfj** [comment]
Working on it, expecting some stuff done today

**Comment by puneetlath** [comment]
@kevinksullivan FYI @ishpaul777 will need to be paid out for being the C+ on this revert PR: https://github.com/Expensify/App/pull/37454

**Comment by kevinksullivan** [comment]
@ishpaul777 please complete the checklist above so we can wrap up payments.

**Comment by mallenexpensify** [comment]
Contributor+: @ishpaul777 paid $500 via Upwork

@ishpaul777 , I created a TestRail for this because QA does monthly tests for edge cases and design-related issues and they might want to include this. 
https://github.com/Expensify/Expensify/issues/378695

Thx!
