### ISSUE TITLE
 iOS - Chat - Emoji picker flickers when opened

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37264]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** vdargentotest+ios022624@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Pre-requisite: user must be logged in.

1. Go to any chat.
2. Tap and hold on any message.
3. Add an emoji reaction.
4. Tap on the reaction button next to the emoji badge.

## Expected Result:
The emoji picker should appear without any issues.

## Actual Result:
The emoji picker flickers when opened.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8df572bb-80f3-4140-9108-5be1ceb5b9bc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@stephanieelliott I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by stephanieelliott** [comment]
Hm, I'm not able to repro this - iPhone 13, iOS 17.3.1, v 1.4.45

**Comment by stephanieelliott** [comment]
Not reproducible, also does not fit into our current roadmap so closing without action.
