### ISSUE TITLE
[$500] Chat - Address bar color does not match dark theme when using deeplink

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37276]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/34409

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Go to ND and log in
2. Open any report and copy the report link
2. Paste the report link in a new tab
3. Reload the page

## Expected Result:
The address bar color matches the dark theme.

## Actual Result:
The address bar color is the default one and does not match the dark theme.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fb1f4fdb-26b9-4669-a663-d105d75fff02

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b2a30780568c7e7</li>
        <li>Upwork Job ID: 1767254668467286016</li>
        <li>Last Price Increase: 2024-03-11</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by CortneyOfstad** [comment]
I waas able to recreate this myself 👍 Going to post in the room in Slack

**Comment by CortneyOfstad** [comment]
Asked [here](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1709060945770199)

**Comment by CortneyOfstad** [comment]
Was OoO — but working to get eyes on this 👍 

If we do not have any proposals before EOW, will reach out to CS or SM to keep this rolling 👍

**Comment by CortneyOfstad** [comment]
@alitoshmatov thoughts on the proposal [here](https://github.com/Expensify/App/issues/37276#issuecomment-1991195969)? If you can provide feedback by EOD that would be great 👍

**Comment by CortneyOfstad** [comment]
PR was merged yesterday but has not gone to production, so going to keep an eye on this 👍

**Comment by CortneyOfstad** [comment]
@tienifr — sorry for the delay here! Payments have been completed!

## Payment Summary

- @tienifr — paid $500 via Upwork
- @alitoshmatov — paid $500 via Upwork
