### ISSUE TITLE
Android-Chat- Code block with mention is not applied in compose box

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37278]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter ```@[applausete+steril@gmail.com```](mailto:applausete+steril@gmail.com%60%60%60)
4. Note, in compose, markdown is not applied for code block with mention
5. Send the message
6. After sending message, code block is applied.

## Expected Result:
Code block with mention must be applied in compose box.

## Actual Result:
Code block with mention is not applied in compose box but after sending message, markdown is applied.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4c8c8ce1-864d-424b-9ef9-4dc4700e158d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by garrettmknight** [comment]
Thanks @izarutskaya - I actually think that behavior is expected. If someone puts something in a code block, I don't expect it to action. Closing for now.
