### ISSUE TITLE
Android-Chat-Changing email id to url and trying to edit text app not responding

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter a email id eg: [jaihanumanblog+hasd@gmail.com](mailto:jaihanumanblog+hasd@gmail.com)
4. Send the message
5. Long press the message and select edit comment
6. Remove + and @ symbol in email id to convert it into URL
7. Send the message
8. Long press the message and select edit comment again
9. Now, try to remove the URL text from end

## Expected Result:
When user try to remove URL text from end, he must be able to remove and replace new text.

## Actual Result:
When user try to remove URL text from end, only single character ie., "m" able to be removed after that app stopped responding.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3e97c45d-3ac4-4066-86ed-2d24b7d6f03d

[Bug6393656_1709015118809!res.txt](https://github.com/Expensify/App/files/14418459/Bug6393656_1709015118809.res.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by adelekennedy** [comment]
this is pretty edge case to me to be honest - closing!
