### ISSUE TITLE
[HOLD for payment 2024-03-29] [Performance] Reduce Redundant Operations

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#37275]
## Problem

In our `getOrderedReportIDs`  we have loops like forEach and sort. In there, we are invoking many utils functions and some of them have static translations in there. Which translates the same text on each loop iteration. For the lots of data, this becomes an issue for the application. Apart from this, we also have `formatPhoneNumber`  which parses the passed number and this util function leverages `awesome-phone-number` library. With further investigation, it appeared that the number we are trying to parse, might not be a number at all. It can also be an email like [concierge@expensify.com](mailto:concierge@expensify.com)  and it is not ideal to parse an email from a phone number library.

## Solution

For translations, we created a separate file and there we are translating the text that was repeatedly reported in our audit. We also have Onyx connection to locale key, so if locale changes we have all the updated translations.
For phone number, we can early return if the passed number is a string or if it doesn’t contain sms domain.

https://github.com/Expensify/App/pull/37200

**Comment by hurali97** [comment]
Hi @muttmuure 👋  Please assign this to me 👍

**Comment by muttmuure** [comment]
Done!

**Comment by muttmuure** [comment]
@fedirjh invited you to this job: https://www.upwork.com/jobs/~010796b6f68d39c46b

**Comment by muttmuure** [comment]
Offer sent

**Comment by muttmuure** [comment]
Paid. Closing out
