### ISSUE TITLE
[HOLD for payment 2024-03-22] [$500] Category - Selected category is not ticked when it appears in the search result

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37287]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Click + > Request money > Manual.
4. Proceed to confirmation page.
5. Click Category.
6. Select a category.
7. Click Category.
8. Search for the category selected in Step 5.

## Expected Result:
The selected category will be ticked in the search result as it is selected.

## Actual Result:
The selected category is not ticked in the search result.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a6708322-9e2d-4bbb-942f-58399c93bf52

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c5eb5319c889dad</li>
        <li>Upwork Job ID: 1762472753849147392</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by rushatgabhane** [comment]
🎀👀🎀 i like @dukenv0307 's proposal https://github.com/Expensify/App/issues/37287#issuecomment-1966602649

**Comment by puneetlath** [comment]
Removing the label as I don't think this needs to be a deploy blocker.

**Comment by puneetlath** [comment]
Payment summary: 
- C - @dukenv0307 - $500 - paid via Upwork
- C+ - @rushatgabhane - $500 - to be paid via NewDot

@rushatgabhane please request on NewDot. 

Thanks everyone!
