### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] [MEDIUM] Categories: Long category name is displayed in one line instead of two lines

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37297]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- The Collect workspace has a long category name
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Open request money page
4. Create manual request and proceed to confirmation page
5. Click Show more > Category

## Expected Result:
The long category name will be displayed in two lines (production behavior)

## Actual Result:
The long category name is displayed in one line instead of two lines

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6393878_1709033051542!Screenshot_2024-02-27_at_13 45 44](https://github.com/Expensify/App/assets/78819774/078e945e-2fa1-4f46-aa76-4cf750142e45)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192de10778824e989</li>
        <li>Upwork Job ID: 1762483105990975488</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>neonbhai | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Long category name is displayed in one line instead of two lines

### What is the root cause of that problem?
We are missing `isRowMultilineSupported`
### What changes do you think we should make in order to solve the problem?

We should add `isRowMultilineSupported` in category picker
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
> > Caused by #35567 We are missing isRowMultilineSupported here
> 
> @FitseTLT If so then i guess the original PR author needs to address this one 🤔
> 
> c.c. @fedirjh

So why was it `Help Wanted` we know all the blockers are caused by recent pr @codinggeek2023

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
