### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Hold Request - English content is copied to clipboard when hold request message is Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37292]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36851
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Create an IOU
4. Go to IOU details page
5. Click 3-dot menu > Hold request
6. Enter a reason and save it
7. Change app language to Spanish
8. Return to IOU details page
9. Right click on the hold request system message > Copy to clipboard (in Spanish)
10. Paste the content

## Expected Result:
The Spanish content will be copied

## Actual Result:
The English content is copied when the app langauge changes to Spanish after the request is held in English

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bf0a6628-336c-4c6b-8010-d2edebe3e120

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173c841e19bd3a5b9</li>
        <li>Upwork Job ID: 1762478277737205760</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Hold Request - English content is copied to clipboard when hold request message is Spanish

### What is the root cause of that problem?
We are currently copying the `message.text` here
https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L376-L377
### What changes do you think we should make in order to solve the problem?

We should separately use a condition for `reason` to copy the translated content same as here
https://github.com/Expensify/App/blob/cfa0ae37156208ebecdc6b2126464ec462271b76/src/pages/home/report/ReportActionItem.js#L468-L469
### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment]
> The same root cause with #37292.

@dukenv0307 you've referenced this very issue 🙂

**Comment by FitseTLT** [comment]
> From what I see, this is reproducible in Prod as well – not a blocker.

Definitely

**Comment by paultsimura** [comment]
Thanks for the proposals.
They are both essentially the same, so I would go with [the proposal](https://github.com/Expensify/App/issues/37292#issuecomment-1966639369) from @FitseTLT. 

**🎀👀🎀 C+ reviewed**

P.s.: I did compare the edit timestamps, but the changes are minor and did not affect the decision here.

**Comment by paultsimura** [comment]
@johnmlee101 please also remove the `blocker` label here – it's reproducible in Prod, thanks.

**Comment by johnmlee101** [comment]
LGTM

**Comment by paultsimura** [comment]
Hey @FitseTLT, when could we expect a PR?

**Comment by muttmuure** [comment]
Regression test created. Thanks!
