### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] [Simplified Collect][Tags] Create WorkspaceTagsPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37309]
Implement this section of the [Simplified Collect: Tags design doc](https://docs.google.com/document/d/1X0dIhQO4fb4fdZcFGCNFUtzMUSvNHnPKIB9lR_8KDUI/edit#bookmark=kix.zf03vcb9e6kb)

cc @waterim 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01094ffd1a31a41461</li>
        <li>Upwork Job ID: 1762500115117129728</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to take this one

**Comment by Christinadobrzyn** [comment]
@waterim is hired and working on this.

**Comment by waterim** [comment]
Hey, started today, will post a PR soon!

**Comment by luacmartins** [comment]
Thanks for letting us know @waterim. Did you get a chance to create that draft PR yet?

**Comment by luacmartins** [comment]
PR was merged

**Comment by Christinadobrzyn** [comment]
Ah missed that, thanks @luacmartins!

**Comment by Christinadobrzyn** [comment]
payment tomorrow if no regressions

Payouts due:

Contributor+: $500 @abdulrahuman5196 (offer in Upwork - https://www.upwork.com/nx/wm/offer/101352853)

Upwork job is [here](https://www.upwork.com/jobs/~01094ffd1a31a41461).

**Comment by Christinadobrzyn** [comment]
PR is in production so I paid this out based on this payment summary https://github.com/Expensify/App/issues/37309#issuecomment-1993446283

@abdulrahuman5196 do we need a regression test for this?

**Comment by Christinadobrzyn** [comment]
@abdulrahuman5196 do we need a regression test for this?

**Comment by Christinadobrzyn** [comment]
Okay thanks @luacmartins - I think this can be closed since it's [paid out!](https://github.com/Expensify/App/issues/37309#issuecomment-1993446283) Let me know if I missed anything.
