### ISSUE TITLE
[HOLD for payment 2024-03-26] [$500][Simplified Collect][Tags] Create TagSettingsPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37313]
Implement this section of the [Simplified Collect: Tags design doc](https://docs.google.com/document/d/1X0dIhQO4fb4fdZcFGCNFUtzMUSvNHnPKIB9lR_8KDUI/edit#bookmark=id.kz1nnmiwox5p)

cc @waterim
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef8d6d5d785755ce</li>
        <li>Upwork Job ID: 1762500700268445696</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to take this one

**Comment by abekkala** [comment]
@luacmartins was the `External` meant to be removed for this one?

**Comment by luacmartins** [comment]
yea, @waterim is working on this

**Comment by luacmartins** [comment]
Still on hold for the main page

**Comment by abekkala** [comment]
Still on hold

**Comment by luacmartins** [comment]
The main page PR was just merged, this one is next in line. Removing hold

**Comment by luacmartins** [comment]
We'll start working on this next

**Comment by waterim** [comment]
Created draft!

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 26

Fix: @waterim - does not require payment
PR Review: @hoangzinh [$500, if no regressions] [Offer](https://www.upwork.com/nx/wm/offer/101488820)

Please propose a regression test

**Comment by luacmartins** [comment]
We'll add test steps once the feature is fully implemented. No need to do that now.

**Comment by abekkala** [comment]
@slafortune will be handling payment for me while I'm ooo

### PAYMENT SUMMARY FOR MAR 26

Fix: @waterim - does not require payment
PR Review: @hoangzinh [$500, if no regressions] [Offer](https://www.upwork.com/nx/wm/offer/101488820)

**Comment by slafortune** [comment]
Paid ✅
