### ISSUE TITLE
Notification - User didn't receive a notification in the main testing device from the #Admin Room in OldDot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37317]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4343116
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with a new Gmail account in New Expensify in the testing device , validate it and stay logged in
3. Navigate to another tab and leave the New Expensify tab in the background
4. Navigate to OldDot https://staging.expensify.com/
and login with the same Gmail account

## Expected Result:
User receive a notification in the main testing device from the #Admin Room in OldDot

## Actual Result:
User didn't receive a notification in the main testing device from the #Admin Room in OldDot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4d7e771b-e89e-486b-8f75-e007ece5e3c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment]
@kbecciv - I don't understand the issue fully. What specific notification were you expecting from the admins room that you didn't receive?

**Comment by kbecciv** [comment]
@sakluger It should be Guide message when user create a Control or Collect policy in Olddot. 
It was caught during regression testing https://expensify.testrail.io/index.php?/tests/view/4343116

**Comment by sakluger** [comment]
I'm not familiar with this message - I'm going to look into this more on Monday.

**Comment by sakluger** [comment]
Ahh sorry haven't had time to prioritize this, I'll review tomorrow for real.

**Comment by sakluger** [comment]
We are in the process of revamping our system message notifications which will likely change this behavior. For that reason, I'm going to close this for now.
