### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] [Simplified Collect][Tags] Create EditTagPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37312]
Implement this section of the [Simplified Collect: Tags design doc](https://docs.google.com/document/d/1X0dIhQO4fb4fdZcFGCNFUtzMUSvNHnPKIB9lR_8KDUI/edit#bookmark=id.u6yj7j88zkbe)

cc @waterim
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f561f64de82869fc</li>
        <li>Upwork Job ID: 1762500493435072512</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to take this one

**Comment by Louisk3** [comment]
Hi
How are you?
I'd like to solve this issue.
How should I do?

I can't access [Simplified Collect: Tags design doc](https://docs.google.com/document/d/1X0dIhQO4fb4fdZcFGCNFUtzMUSvNHnPKIB9lR_8KDUI/edit#bookmark=id.u6yj7j88zkbe)

Thanks
Mileta

**Comment by Louisk3** [comment]
Contributor details
Your Expensify account email: mile76534@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f6272b3689389b37

**Comment by Louisk3** [comment]
just create an Expensify account.
What's next?

**Comment by Louisk3** [comment]
https://github.com/Expensify/App/issues/37312#issuecomment-1967420121

**Comment by Louisk3** [comment]
Contributor details
Your Expensify account email: mile76534@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f6272b3689389b37

**Comment by Louisk3** [comment]
Hi, @luacmartins

Thanks for your replying.

So how should I do to fix another issue?

**Comment by luacmartins** [comment]
Please refer to our contributing guidelines - https://github.com/Expensify/App/blob/6700a02b297186be9dfc7c9cbd39966805b211ad/contributingGuides/CONTRIBUTING.md

**Comment by Louisk3** [comment]
Thanks.

**Comment by luacmartins** [comment]
Still on hold for the main page

**Comment by JmillsExpensify** [comment]
Still on hold?

**Comment by luacmartins** [comment]
Removed hold since the main page PR was merged.

**Comment by DylanDylann** [comment]
@luacmartins Could you help to add me to [Tags design doc](https://docs.google.com/document/d/1X0dIhQO4fb4fdZcFGCNFUtzMUSvNHnPKIB9lR_8KDUI/edit#bookmark=id.u6yj7j88zkbe)?

This is my email: dylandylan9112@gmail.com

**Comment by luacmartins** [comment]
done!

**Comment by DylanDylann** [comment]
Waiting for PR

**Comment by waterim** [comment]
Created Draft, but this one is going on HOLD for this: https://github.com/Expensify/App/issues/37313
After TagSettings are there, will update this PR and open it!

**Comment by DylanDylann** [comment]
@waterim No longer hold, please update the PR

**Comment by luacmartins** [comment]
just pending payment

**Comment by luacmartins** [comment]
pending payment

**Comment by luacmartins** [comment]
Just pending payment

**Comment by JmillsExpensify** [comment]
Offer sent

**Comment by JmillsExpensify** [comment]
@DylanDylann accept the offer when you get a chance and I'll try to make sure you're paid before Monday.

**Comment by DylanDylann** [comment]
@JmillsExpensify I accepted. Thanks

**Comment by JmillsExpensify** [comment]
Contract paid out, thanks!
