### ISSUE TITLE
[HOLD for payment 2024-03-22] [$500][Simplified Collect][Tags] Create CreateWorkspaceTagPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37311]
Implement this section of the [Simplified Collect: Tags design doc](https://docs.google.com/document/d/1X0dIhQO4fb4fdZcFGCNFUtzMUSvNHnPKIB9lR_8KDUI/edit#bookmark=id.b4uhb593la6q)

cc @waterim
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011399a14d19af6df5</li>
        <li>Upwork Job ID: 1762499866140581888</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to take this one

**Comment by zanyrenney** [comment]
Hey @waterim how are you getting on with this one?

**Comment by zanyrenney** [comment]
On HOLD but @waterim on standby to pick it up

**Comment by luacmartins** [comment]
On hold while we work on the main page

**Comment by luacmartins** [comment]
On hold

**Comment by brunovjk** [comment]
> On hold while we work on the main page

@luacmartins, after that, can external contributors help? Thanks. :D

**Comment by zanyrenney** [comment]
Still on hold

**Comment by waterim** [comment]
Taking this one from tomorrow!

**Comment by luacmartins** [comment]
@waterim actually, could you get started on https://github.com/Expensify/App/issues/37312 instead? We'll get C+ to work on this one since it's a standalone issue.

**Comment by luacmartins** [comment]
Assigning @allroundexperts to implement this issue

**Comment by mountiny** [comment]
@luacmartins can the hold be removed here?

**Comment by luacmartins** [comment]
Yes, we already have a PR up for this 😄

**Comment by zanyrenney** [comment]
Just a note to say, I am OOO now until April 2nd, reassigning BZ team member to just finish this off for the payment.

**Comment by strepanier03** [comment]
@allroundexperts @ishpaul777 - Doesn't look like we need the checklist since this was a new feature, is that right?

I'm posting the payment summary below and once I have confirmation from you about the checklist I'll assign Jason for the manual request.

**Comment by strepanier03** [comment]
### Payment summary

- [ ] $500 @allroundexperts requires payment through NewDot Manual Requests
- [x] $500 @ishpaul777 paid via Upwork

@JmillsExpensify - Payment request incoming shortly.

**Comment by luacmartins** [comment]
Correct!

**Comment by strepanier03** [comment]
Fanastic. Thanks for confirming. 

I'll assign this to Jason and mark it ready for payment. @allroundexperts feel free to submit your request for payment as soon as you can.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
