### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500][Simplified Collect][Tags] Implement DeleteWorkspaceTags

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37314]
Implement this section of the [Simplified Collect: Tags design doc](https://docs.google.com/document/d/1X0dIhQO4fb4fdZcFGCNFUtzMUSvNHnPKIB9lR_8KDUI/edit#bookmark=id.8i3sk5eow576)

cc @waterim
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155b70726d736408f</li>
        <li>Upwork Job ID: 1762500850869534720</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to take this one

**Comment by luacmartins** [comment]
Still on hold for the main page

**Comment by MitchExpensify** [comment]
[PR was merged](https://github.com/Expensify/App/issues/37309#issuecomment-1977502369) so I'm taking this off hold!

**Comment by MitchExpensify** [comment]
Are we good to apply Help Wanted on this now @luacmartins ?

**Comment by luacmartins** [comment]
@MitchExpensify we'll keep this assigned to @waterim for now

**Comment by MitchExpensify** [comment]
@waterim Seeing as we're off hold, what are our next steps here?

**Comment by luacmartins** [comment]
@waterim I've asked @allroundexperts to get started on implementing the delete functionality while you finish settings and edit pages. Hope that's ok!

**Comment by allroundexperts** [comment]
Draft PR created https://github.com/Expensify/App/pull/38453

This has some conflicts because the [PR](https://github.com/Expensify/App/pull/38240) it is based from has conflicts as well.

I will make it it ready for review once the base [PR](https://github.com/Expensify/App/pull/38240) gets merged.

**Comment by allroundexperts** [comment]
Okay. I was mistaken. The main branch already had the tag setting page created. As such, the [PR](https://github.com/Expensify/App/pull/38453) is ready for review.

**Comment by MitchExpensify** [comment]
Reminder set to pay. 

*Payment summary*:

C+ $500 @allroundexperts (NewDot)

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts

**Comment by MitchExpensify** [comment]
Can do, Payment job here https://www.upwork.com/jobs/~011908d15db493b1bf @Ollyws

**Comment by MitchExpensify** [comment]
Done!
