### ISSUE TITLE
IOU - Missing tag with red dot is shown in preview and details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37327]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4344228
**Issue reported by:**

## Action Performed:
Pre- condition: In employee account in old dot, keep merchant name " test" and create a expense rule for category and tag
1. Launch app as employee
2. Tap on employee Workspace chat
3. Tap plus icon --- request money
4. Enter an amount and tap next
5. Enter merchant as "test"
6. Tap request

## Expected Result:
When tag is shown, missing tag with red dot must not be shown in preview and details page

## Actual Result:
In new expense created, in preview, red dot with missing tag is shown in preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f8c3595f-4ac4-4fe1-b61b-d129010fc881

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by miljakljajic** [comment]
Going to close - mostly tied to OldDot.
