### ISSUE TITLE
[HOLD for payment 2024-03-20] [$500][MEDIUM] Categories: Parent that has own category is not ticked in All list when selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37326]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- The Collect workspace has these categories:
- Test
- Test: Test 1
- Test: Test 2
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Click + > Request money > Manual
4. Enter amount and proceed to confirmation page
5. Click Show more
6. Click Category
7. Select the parent category "Test"
8. Click Category
9. Scroll down to find the parent category "Test"

## Expected Result:
The parent category "Test" will be displayed with a tick in the list (production behavior) because it is selected

## Actual Result:
The parent category "Test" is not displayed with a tick in the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3afa4e25-4c51-44c9-9dd1-ac502fbde3c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010569839356f2354c</li>
        <li>Upwork Job ID: 1762533897677324288</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by blimpich** [comment]
Agreed, demoting. Will handle this with the regular bug process.

**Comment by blimpich** [comment]
@hoangzinh it looks like there's [another bug](https://github.com/Expensify/App/issues/37297) caused by the same PR that is going ahead with a fix, so for this case lets go forward with having this be open for external contributors.

I don't think that this should've had `external` immediately applied to it, but I'll ask internally if we had a process change in order to make sure of that. For now lets move forward with this as a normal issue 👍

**Comment by joekaufmanexpensify** [comment]
@hoangzinh have you had a chance to review the proposal on the issue!

**Comment by joekaufmanexpensify** [comment]
@dukenv0307 is there an ETA for a PR here?

**Comment by joekaufmanexpensify** [comment]
@hoangzinh the scope of this issue only impacts sub-categories, correct? If so, I think this is a pretty niche case, and a regression test for every run is probably not needed.

**Comment by joekaufmanexpensify** [comment]
Yep, that's correct. Could you please do the rest of the checklist? And then I'll issue payment.

**Comment by joekaufmanexpensify** [comment]
TY! All set to issue payment. We need to pay: 

- @hoangzinh - $500 for C+ via Upwork. 
- @dukenv0307 - $500 for PR via Upwork.

**Comment by joekaufmanexpensify** [comment]
@hoangzinh $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@dukenv0307 $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
