### ISSUE TITLE
Expense - 3-dot menu in confirmation page is not clickable after returning from avatar view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37331]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Request money > Manual.
4. Proceed to confirmation page.
5. Click the workspace name under "To" destination.
6. Click on the workspace avatar.
7. Return to confirmation page.
8. Click 3-dot menu.

## Expected Result:
The 3-dot menu will be clickable.

## Actual Result:
The 3-dot menu is no longer clickable after returning from avatar view.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a91be8ac-4ae9-40a9-ae6d-1a48c8bc23ac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by joekaufmanexpensify** [comment]
I can reproduce this. But I don't think this is something an actual user will do. This doesn't just require that someone click into the workspace, but it also requires that they go to change the workspace avatar in the middle of doing that. Further, if you click out and back into the request, it works again. 

Doesn't feel likely to me that anyone will ever really do this. Let's close for now, and we can revisit if anyone actually experiences this.
