### ISSUE TITLE
IOU - LHN for IOU report still shows the requested amount when IOU is deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37333]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36557

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM.
3. Create a manual request.
4. Go to request details page.
5. Send a message.
6. Click 3-dot menu > Delete request.
7. Return to IOU report.

## Expected Result:
LHN for IOU report will show [Deleted request].

## Actual Result:
LHN for IOU report still shows the requested amount when IOU is deleted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/bc35c5fa-714a-4f9c-99bb-dde16d9d01d8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@stephanieelliott I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by stephanieelliott** [comment]
I don't really think this is a bug, as long as the `X owes Y 0.00` stays current, it's not unexpected that the LHN shows the most recent request made (even if it was deleted afterward). I'm not sure if it was a conscious UI decision or something that wasn't given consideration, but I don't think we need to prioritize updating this behavior.
