### ISSUE TITLE
[$500]  IOU - Message doesn't contain description when Copy to clipboard on money request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36993
**Issue reported by:** Applause - Internal eam

## Action Performed:
1. Create a workspace and invite some users
2. As employee, create a money request with description in the workspace chat
3. As admin, paid this request
4. As employee hover or long press on money request preview > Copy to clipboard
5. Paste the message to composer

## Expected Result:
Pasted message should contains the description

## Actual Result:
Pasted message doesn't contain description when Copy to clipboard on money request preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/31e3d675-b340-4d52-9ee8-c1ba87c7b086

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e3619582ba70c09</li>
        <li>Upwork Job ID: 1762552015212392448</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by AndrewGable** [comment]
@dukenv0307 @DylanDylann @srikarparsi - Is this a regression from https://github.com/Expensify/App/pull/36993?

**Comment by DylanDylann** [comment]
I will check today

**Comment by DylanDylann** [comment]
@AndrewGable I don't think this is regression from https://github.com/Expensify/App/pull/36993
cc @dukenv0307

**Comment by DylanDylann** [comment]
IMO, this is not a bug. Let's see this case:

https://github.com/Expensify/App/assets/141406735/b984ad0b-4e03-4e3e-8bd6-e5a38feaa2ca

We have 2 requests with different descriptions. Then admin pays both requests. If we want to display a description in the paid message, which description should be displayed

**Comment by AndrewGable** [comment]
@isabelastisser - Can you confirm this is not a bug as proposed by @DylanDylann? I agree with them
