### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] Web - Chat - Infinite spinner in ND when navigating from OD in different ways

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37332]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/1971109
**Issue reported by:** Applause - Internal team

## Action Performed:
Precondition: user is logged in OD with an account that has a existing workspace without a bank account setup
1. Navigate to inbox and Search for the inbox task "Finish setting up..."
2. Click on "Continue Setup"
OR
1. Click the message bubble in the bottom right

## Expected Result:
User redirected to ND and the "Connect Bank Account" page is displayed in the side bar.
OR
A new tab opens and user is brought to the ND concierge chat.

## Actual Result:
User is redirected to ND and see infinite spinner instead of chat history.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a7d31f00-ba52-4635-af47-a65132da927d

https://github.com/Expensify/App/assets/93399543/2e11e8f8-174e-4f90-83fd-204ef99cd530

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01245ae49f9d1205bf</li>
        <li>Upwork Job ID: 1762543109358874624</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by robertjchen** [comment]
Definitely a blocker for sure

**Comment by robertjchen** [comment]
Working on reproducing the issue

**Comment by robertjchen** [comment]
I believe it's related to this change: https://github.com/Expensify/App/pull/36689

This is happening on the `OpenReimbursementAccountPage` and the most recent changes to that flow were related to the above PR.  There's no console error and just the infinite spinner so I'm not too sure how to debug further. @nkuoch @hayata-suenaga do you possibly have more insight into what may be happening here?

**Comment by hayata-suenaga** [comment]
I think there are two parts to this issue:

- The first part is the infinite loading of the chat history
- The second part is that the bank setup RHP is not showing up

The second point might be related to @nkuoch's PR but for the first part, I'm not sure if the PR is directly related 🤔

**Comment by hayata-suenaga** [comment]
@robertjchen seems like the PR is not related. do you have any idea what might be related?

**Comment by robertjchen** [comment]
Got it, thanks for taking a look. I'll dig further!

**Comment by robertjchen** [comment]
Posted in [#wave9-collect-signups](https://expensify.slack.com/archives/C05NJ4SLBMF/p1709156142096779) to get additional insight

**Comment by robertjchen** [comment]
Checking if the issue is still reproducible

**Comment by robertjchen** [comment]
Reproducible here and appears to affect all OldDot -> NewDot transitions: https://expensify.slack.com/archives/CC7NECV4L/p1710532758907999

**Comment by koko57** [comment]
Hi I'm Agata from Callstack! I worked on a similar issue a while ago, I would like to help 🙂

**Comment by mountiny** [comment]
PR is coming from @adamgrzybowski

**Comment by mountiny** [comment]
$500 to @allroundexperts for their review

**Comment by adelekennedy** [comment]
sorry @allroundexperts I'm just back from ooo

**Payouts due:**

- [ ] Contributor+: $500 @allroundexperts (NewDot)

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
