### ISSUE TITLE
Android - Login - Focus remains when dismiss the keyboard on login page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New dot app
2. Tap on email field to open the keyboard if not open
3. Tap on dismiss button on keyboard to close the keyboard

## Expected Result:
Focus is lost

## Actual Result:
Focus remains when dismiss the keyboard on login page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/50f9bff0-c31a-4682-b317-711bed259c7a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
Hmm, this doesn't feel like a bug to me. I think it's fine that the focus remains in the field, especially since it's the only one. Let me know if you disagree!
