### ISSUE TITLE
Android - User has to tap device back button twice to close the app after starting a chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Tap FAB > Start chat
3. Select a user with no prior chat
4. Tap device back button to return to home page
5. Tap device back button to close
6. Tap device back button again

## Expected Result:
In Step 5, the app will close

## Actual Result:
In Step 5, the app returns to Home page, from Home page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/be4dcda4-a169-41dd-8596-a856fc101491

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
Ah!  I was able to recreate that, but also I question how much it will affect anyone with so many other issue that we should allocate resources too.  If it's only someone you've never chatted with, and still don't chat, that isn't going to happen as a typical use case.
