### ISSUE TITLE
iOS - Unable to navigate to Home page when open workspace link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37347]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+gm46@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out
2. Go to some WS link, e.g. https://staging.new.expensify.com/workspace/adsasddssad/rateandunit
(doesn't matter if policy exist or not)
3. Log in
4. Tap Back button or Go back to home page

## Expected Result:
User should navigate to Home page

## Actual Result:
User can not navigate to Home page using Back button or Go back to home page when open workspace link.
It navigate to Workspace page and back to the WS link location every time using Back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fc898da8-b046-4c0a-954c-12fa418c7985

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
I ran out of time today and will have to test it next week. 

## Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by alexpensify** [comment]
I'm catching up from being OOO and will test soon.

**Comment by alexpensify** [comment]
Still on my testing list, I'll review it soon.

**Comment by alexpensify** [comment]
No update yet, I need to test.

**Comment by alexpensify** [comment]
Closing - I've been unable to replicate this experience in both iOS and Android.
