### ISSUE TITLE
[HOLD for payment 2024-03-14] Gesture to hide the search page should be right to left 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37354]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-14
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709024846036369

## Action Performed:
1. Open the search page
2. Use gesture to hide the page swiping left to right
3. Observe the animation

## Expected Result:
The gesture to hide a page that opens from left to right should be a swipe from right to left OR
The search page & workspace switcher use the same direction of the profile page.

## Actual Result:
We use the gesture left to right to close the "search" but the animation is from right to left

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3bccc025-f6a6-461f-ac5c-78edc466eaaa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ac67e098881d1f63</li>
        <li>Upwork Job ID: 1762586657702166528</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
Weird react navigation bug I assume. We should match the animation.

**Comment by youssef-lr** [comment]
I think @kirillzyusko is looking into this

**Comment by Gajendra-Gupta** [comment]
Page should open and close like profile page right?

**Comment by youssef-lr** [comment]
@kirillzyusko nope this is still an issue :(

**Comment by kirillzyusko** [comment]
@youssef-lr okay, I was working on the native-stack migration for the app. While this issue seems related its actually not. But as i am working on the navigation integration anyway i can also have a look at this issue! 😊

**Comment by youssef-lr** [comment]
Thanks a lot @kirillzyusko, appreciate it!

**Comment by twisterdotcom** [comment]
@kirillzyusko should we assign you to this too?

**Comment by kirillzyusko** [comment]
@twisterdotcom yes, please 🙏

**Comment by kirillzyusko** [comment]
@youssef-lr @twisterdotcom the fix is ready for review 👀 

https://github.com/Expensify/App/pull/37601 whom we should ask to review? 🤔

**Comment by youssef-lr** [comment]
I can review @kirillzyusko, thanks a lot!

**Comment by youssef-lr** [comment]
@kirillzyusko was this a regression from a previous PR? If yes then I think the original review must review it

**Comment by kirillzyusko** [comment]
@youssef-lr I don't think it was a regression, because PR with native stack was fully reverted

**Comment by youssef-lr** [comment]
@sobitneupane I took care of reviewing this one as it's pretty simple.

**Comment by twisterdotcom** [comment]
@youssef-lr do we need to assign @kirillzyusko here, or is it not necessary?

**Comment by youssef-lr** [comment]
No need @twisterdotcom, Kiryl is from Margelo.

**Comment by twisterdotcom** [comment]
Okay great, my favourite /app issues are ones like this. We'll just close once it's hit prod.

**Comment by twisterdotcom** [comment]
No payment necessary here. @youssef-lr do we ned a test case at all? Gonna close, but if you think we do, lay out the steps and I'll create one.

**Comment by youssef-lr** [comment]
Nah I don't think we do.
