### ISSUE TITLE
[HOLD for payment 2024-03-07] [Wave Collect] [More Features] Update the Policy.ts policy type with the new policy properties in the App

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37367]
Part of https://github.com/Expensify/Expensify/issues/365143

Implement [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.dl75839ebd5i) of the design doc. 

This will update the policy type to include the new isFeatureEnabled properties

**Comment by mountiny** [comment]
PR up https://github.com/Expensify/App/pull/37455

**Comment by dylanexpensify** [comment]
tomorrow! 🤑

**Comment by mountiny** [comment]
Nothing to pay here and no regression tests required so closing
