### ISSUE TITLE
[Wave Collect] [More Features] Create the new API endpoints for enabling the features

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37364]
Part of https://github.com/Expensify/Expensify/issues/365143

Implement [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.32gfrixai3zb) of the design doc creating new web API commands for the toggles.

This also entails making sure that disabling the features should handle correctly some other values of the policy. These details are written down [here](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.2dmx9nu4161h) (linking to the individual features)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01861f78fadb593f07</li>
        <li>Upwork Job ID: 1762620612728041472</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
This is internal. I can work on it.

**Comment by mountiny** [comment]
This work will benefit from PR done here https://github.com/Expensify/Web-Expensify/pull/41182 as the API commands should use method there
