### ISSUE TITLE
[HOLD for payment 2024-03-22] [Wave Collect] [More Features] Create OpenPolicyMoreFeaturesPage command

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37366]
Held on https://github.com/Expensify/Web-Expensify/pull/41183

Part of https://github.com/Expensify/Expensify/issues/365143

Implement [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.jwu7ajmckz9e) of the design doc. 

We should create a new OpenPolicyMoreFeaturesPage auth command and web API that will return the policy features toggle state.

- [x] Auth command
- [x] API endpoint
- [ ] App Policy action calling this read command
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b794bb558e484d5</li>
        <li>Upwork Job ID: 1762620636882984960</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by cristipaval** [comment]
what release is this one for, @trjExpensify ?

**Comment by luacmartins** [comment]
This is entirely internal. @cristipaval are you available to work on this tomorrow? Otherwise I'll pick it up.

**Comment by cristipaval** [comment]
yes I'll work on it today

**Comment by cristipaval** [comment]
^ Auth and Web-E PRs in progress.

**Comment by luacmartins** [comment]
@cristipaval merged the Web-E PR, can you add that command to the API dashboard?

**Comment by cristipaval** [comment]
Added. Thanks for reviewing!

**Comment by cristipaval** [comment]
I'll open an App PR with the action today.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by cristipaval** [comment]
The command is now in staging

**Comment by mountiny** [comment]
App PR merged, thanks @rezkiy37 and @fabioh8010 for resolving conflicts

**Comment by rezkiy37** [comment]
Regarding the regression test steps - https://github.com/Expensify/App/issues/37373#issuecomment-1998677868. Looks like I need to add them later.

**Comment by mountiny** [comment]
There was no C+ here so we can close now
