### ISSUE TITLE
[Wave Collect] [More Features] Fetch the features enabled properties of the policy to NewDot

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37369]
Part of https://github.com/Expensify/Expensify/issues/365143

Implement [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.d01sp5507rng) of the design doc. 

> Make sure to read through the individual feature sections to get the default values
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2d15d0e3f37a2b2</li>
        <li>Upwork Job ID: 1762620663809720320</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
pending internal - can post a cta

**Comment by luacmartins** [comment]
This issue was mostly implemented [here](https://github.com/Expensify/Auth/pull/10118). We're just missing the correct defaults.

**Comment by mountiny** [comment]
Depployed
