### ISSUE TITLE
[Wave Collect] [More Features] Create the PolicyAPI helper methods to set the new feature enabled properties on a policy

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37368]
Part of https://github.com/Expensify/Expensify/issues/365143

Implement [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.tq56hgmjses3) of the design doc. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c1a785c34254b7a</li>
        <li>Upwork Job ID: 1762620657560207360</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
pending internal - can post a cta

**Comment by mountiny** [comment]
Draft PR is ongoing, I need to add more tests and handle tags and workflows when disabled.

**Comment by mountiny** [comment]
This is done

**Comment by flodnv** [comment]
Reopening, tests need to be redone https://github.com/Expensify/Web-Expensify/pull/41182#issuecomment-1995222736

**Comment by mountiny** [comment]
Tests were re-added
