### ISSUE TITLE
[Wave Collect] [More Features] Update the Tags Add/Update methods in OldDot to enable the tags feature

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37371]
Part of https://github.com/Expensify/Expensify/issues/365143

Implement [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.ipydphgwvbui) of the design doc. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01167c061d0b5f64b9</li>
        <li>Upwork Job ID: 1762620679635009536</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by alexpensify** [comment]
Looks like we have one PR merge here

---

Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by alexpensify** [comment]
I confirmed there is no contributor or C+ activity here that would trigger the payment process. Keeping this one closed.
