### ISSUE TITLE
[Wave Collect] [More Features] Enable Workflows feature whenever Scheduled Submit, Approval mode or reimbursement choice changes in OldDot

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37372]
Part of https://github.com/Expensify/Expensify/issues/365143

Implement [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.98beqyc0ak3f) of the design doc. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a7df7de196b8580</li>
        <li>Upwork Job ID: 1762620686504710144</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by alexpensify** [comment]
Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by alexpensify** [comment]
Weekly Update: Waiting for the PR here.

**Comment by luacmartins** [comment]
I'll work on this one

**Comment by luacmartins** [comment]
PR in review

**Comment by alexpensify** [comment]
Weekly update: The PR has been merged!

**Comment by mountiny** [comment]
Can be closed, nice one
