### ISSUE TITLE
[DUE 4/8][$500] Payment for issue #38152

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#37387]
This is the payment issue for https://github.com/Expensify/App/pull/35837. However, that PR was reverted and so this is the PR that is re-adding the feature https://github.com/Expensify/App/pull/38152

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a014c326bb4005a</li>
        <li>Upwork Job ID: 1762655721836969984</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment]
cc @slafortune This is ready to pay out!

**Comment by thienlnam** [comment]
Ah yeah good point, I forgot we don't payout for reverted PRs. I'll just hold on this for now then so we don't forget.

Follow up PR is hopefully coming later this week. Will assign you both when the time comes

**Comment by yasmoto1995** [comment]
[$250] Payment for issue #35837 #37387 - Expensify

I am very interested.
I saw this post in Upwork.com
So, what can I do?

**Comment by yasmoto1995** [comment]
I can't believe you.

**Comment by c3024** [comment]
@yasmoto1995 

This is an Upwork job for an issue which was already completed by others. You cannot apply for this job. 

You can [read this](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) if you want to contribute to Expensify.

**Comment by slafortune** [comment]
still on hold

**Comment by slafortune** [comment]
@thienlnam can I close this?  I don't see another payment issue created, but am having a hard time following the path.

**Comment by thienlnam** [comment]
This is the current issue that https://github.com/Expensify/App/pull/38152 is being re-added in replacement of the PR in the linked description that we reverted. We can pay this out for https://github.com/Expensify/App/pull/38152 once it's done

**Comment by yasmoto1995** [comment]
Hello!
May I joint the project?
Best Regard

**Comment by slafortune** [comment]
@yasmoto1995 thanks for the interest - this is already underway and assigned out.

**Comment by slafortune** [comment]
This is related to Enabling Live Markdown, but is just the additional payment for that.  Not sure if the project needs to be applied.

https://expensify.slack.com/archives/C01SKUP7QR0/p1711657815434179

**Comment by slafortune** [comment]
@shubham1206agra offer sent - https://www.upwork.com/nx/wm/offer/101799435
@c3024 Paid ✅

**Comment by slafortune** [comment]
I'll be out of the office until 4/22 so will check on this then.

**Comment by slafortune** [comment]
@shubham1206agra If you are not able to select the link, are you able to search for it by using 35837 which is in the title?

<img width="1743" alt="image" src="https://github.com/Expensify/App/assets/11725910/ba08c155-08e6-4d54-a75c-4fef1dc0a44f">

Here is the link to the invite again - https://www.upwork.com/nx/wm/offer/101799435

**Comment by slafortune** [comment]
Ah!  K ~ A 👍

**Comment by slafortune** [comment]
Offer resent - https://www.upwork.com/nx/wm/offer/101994087
