### ISSUE TITLE
[$500]  Settings - The classicRedirect->dismissedReason displays the first response

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37408]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when executing PR :** https://github.com/Expensify/App/pull/34925

**Version Number:** 1.4.44.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N, new feature
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Complete steps 1 to 17 for any option (https://github.com/Expensify/App/pull/34925
)
2. Complete steps 1 to 17 for another option, make sure to choose a different reason

## Expected Result:
It should always display the actual response.

## Actual Result:
The classicRedirect->dismissedReason displays the first response.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6395107_1709099549215!capture](https://github.com/Expensify/App/assets/115492554/2b3cb386-10e9-403d-9135-0e1e0729c112)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0187eb3870fabaaf97</li>
        <li>Upwork Job ID: 1762800266729877504</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave9-collect-signup
CC @MitchExpensify

**Comment by roryabraham** [comment]
Weird. I bet this is actually a problem in Web-E. I'm guessing what happened here is that the response that was sent the 2nd time was rejected by the firewall for some reason. I had seen that but thought I fixed it

**Comment by roryabraham** [comment]
@AndrewGable fixed this in https://github.com/Expensify/Web-Expensify/pull/41146. Cheers!
