### ISSUE TITLE
[$500] Workspace settings - The list of categories is empty after Relogin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37409]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when executing PR :** https://github.com/Expensify/App/pull/36324

**Version Number:** v1.4.44-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N, new feature
**Email or phone of affected tester (no customers):** applausetester+desktop.again@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Navigate to the workspace settings as an admin within a paid policy group.
2. Verify that you can access the categories page.
3. Verify that categories are listed
4. Logout/login and check if you still can see the categories
5. If issue is reproduced: turn off/turn on categories in oldDOT and check again

## Expected Result:
Categories are listed in the Workspace settings

## Actual Result:
Categories are empty after religion.
it's possible to see categories again after re-enable in the oldDOT

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/55597336-7c01-4af2-bc34-1a6f8a5d62de

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01859487fe67eb291e</li>
        <li>Upwork Job ID: 1762801923637030912</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by trjExpensify** [comment]
It's #wave8-collect-admins as that's where we're building out the workspace settings. @ArekChr @luacmartins putting this on your radar.

**Comment by trjExpensify** [comment]
CC: @allroundexperts as well for 👀 as you were reviewing the initial PR too. 👍

**Comment by allroundexperts** [comment]
This seems like a backend issue to me.

**Comment by ArekChr** [comment]
This is a known issue, there was discussion [here](https://callstack-hq.slack.com/archives/C036QM0SLJK/p1707832121603409?thread_ts=1707768509.167959&cid=C036QM0SLJK), We need additional backend endpoint for that

**Comment by trjExpensify** [comment]
Cool, so let's close this as we'll be addressing it in: https://github.com/Expensify/App/issues/36801
