### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Workflows-If the first 2 options are enabled,cannot scroll to see the 3th option

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37403]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :**https://github.com/Expensify/App/pull/36345

**Version Number:** v1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Email or phone of affected tester (no customers):** applausetester+ihchat4_2902_e@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in to account with the Collect policy (Admin or employee)
3. Navigate to Settings > Workspaces. You should see your Collect workspace, click on it
4. Click on Workflows
5. Toggle the first 2 options ( Delay submissions and Add approvals)
6. Try to scroll to the bottom

## Expected Result:
The page can be scrolled to see all options

## Actual Result:
Cannot scroll to see the 3th option (Make or track payments)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4aea4e09-d2b7-47c2-bff6-b7c8994ae58a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111411a72b5209608</li>
        <li>Upwork Job ID: 1762791634831163392</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave7-collect-approvers
CC @RachCHopkins

**Comment by Julesssss** [comment]
cc @lakchote as you'll have more context

**Comment by lakchote** [comment]
> I'm struggling to reproduce as I can't see my collection policy. I'm reasonably sure this [feature](https://github.com/Expensify/App/pull/36345) is locked behind a beta flag (QA and contributors have all betas enabled by default).
> 
> This also is a minor issue for a new feature, so it doesn't need to block the release 👍

Yes Jules, you need to have `isPolicyExpenseChatEnabled` ([source](https://stackoverflowteams.com/c/expensify/questions/17518))

**Comment by lakchote** [comment]
> and we dont need to use a flatlist here becuse we dont use it any page with similar layout for example: [WorkspaceReimburseView](https://github.com/Expensify/App/blob/93c66ce5355ad9ab849faffc95371d53eddae868/src/pages/workspace/reimburse/WorkspaceReimburseView.js)
> 
> ```
>                        {
>                             // map the items to the renderItem function
>                             items.map((item, index) => (
>                                 renderItem(item, index)
>                             ))
>                         }
> ```

Hmm, that's not [what was written](https://docs.google.com/document/d/1T--VcAaCm-8aq5oEO78_vVXxBpXY1gq7NiJrboGZNcs/edit#bookmark=id.1ius9vunutep) in the detailed DD. cc @luacmartins should we keep the `<FlatList>`?

Also @ishpaul777, yes please fix the current scroll issue in your PR if you can. Otherwise I can do it. Thank you

**Comment by luacmartins** [comment]
Yes, let's keep the list for now. We can refactor the page if it becomes an issue

**Comment by lakchote** [comment]
> Yes, let's keep the list for now. We can refactor the page if it becomes an issue

@ishpaul777 pinging you just to make sure you didn't miss @luacmartins's comment about the `<FlatList>`

**Comment by Julesssss** [comment]
Bumping for C+ review @mkhutornyi

**Comment by Julesssss** [comment]
No worries, It's not clear and I forgot about this issue.

**Comment by luacmartins** [comment]
Yes, we can change it to a scrollView

**Comment by Julesssss** [comment]
I'm not sure that such a specific page scrolling test is valuable here

**Comment by Julesssss** [comment]
Ready for payment, I'll be OOO so can't respond

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @mkhutornyi $500
 - Contributor+: @ishpaul777 $500

**Comment by JmillsExpensify** [comment]
Ah thank you! I'll update for clarity and send over the manual Upwork offers within the hour.

**Comment by JmillsExpensify** [comment]
Contributor contract paid out, waiting on C+ to accept and then we can close this out.

**Comment by luacmartins** [comment]
pending payment

**Comment by luacmartins** [comment]
Just pending payment

**Comment by JmillsExpensify** [comment]
Let's close the issue. Still waiting for the offer to be accepted in Upwork.

**Comment by mallenexpensify** [comment]
@mkhutornyi , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01f9e66b4545a1cb70

**Comment by JmillsExpensify** [comment]
All paid out! Closing again.
