### ISSUE TITLE
[HOLD #305057] [Track Tax] Tax rate/amount page is still accessible when it is disabled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37414]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when executing PR :** https://github.com/Expensify/App/pull/36784

**Version Number:**  v1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has tax enabled.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Request money > Manual.
4. Enter amount > Next.
5. Click Show more.
6. Click Tax rate or Tax amount.
7. As admin, disable tax.

## Expected Result:
Tax page will change to not here page.

## Actual Result:
Tax page is still accessible instead of showing not here page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4548ebdc-b63b-422c-9ded-64b38fe5409d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@stephanieelliott I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by ShridharGoel** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tax page is still accessible after tax tracking is disabled.

### What is the root cause of that problem?
`IOURequestStepTaxRatePage` doesn't have any check which can ensure that it changes based on the latest tax enabled/disabled info.

### What changes do you think we should make in order to solve the problem?
Use `isTaxTrackingEnabled` info and navigate back if the tax tracking switches to false state.

```
useEffect(() => {
        if (!isTaxTrackingEnabled) {
            navigateBack();
        }
    }, [isTaxTrackingEnabled]);
```

**Comment by MonilBhavsar** [comment]
Feature is WIP, so we can put this HOLD until we finish the implementation as it is being rolled out in phases https://github.com/Expensify/Expensify/issues/305057

**Comment by stephanieelliott** [comment]
This is not reproducible anymore -- when tax is disabled from the workspace, the field disappears from the in-progress request.
