### ISSUE TITLE
[HOLD 305057] [Track Tax] - Selection highlight remains at previous default tax rate when the default rate changes

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37419]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/36784

**Version Number:** v1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has some tax options.

1. [Employee] Go to workspace chat.
2. [Employee] Open request money page > Manual.
3. [Employee] Enter amount and proceed to confirmation page.
4. [Employee] Click Show more > Tax rate.
5. [Admin] On Old Dot, change the default workspace tax rate.

## Expected Result:
The selection highlight will move when the default tax rate changes.

## Actual Result:
The selection highlight remains at the previous default tax rate when the default rate changes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/bab04821-750a-48cc-84bf-fce741063b5f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@slafortune I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by MonilBhavsar** [comment]
Feature is WIP, so we can put this HOLD until we finish the implementation as it is being rolled out in phases https://github.com/Expensify/Expensify/issues/305057

**Comment by slafortune** [comment]
I'll move this to weekly in the meantime.

**Comment by slafortune** [comment]
PR is being reviewed - [33927](https://github.com/Expensify/App/pull/33927)

**Comment by slafortune** [comment]
Still on hold

**Comment by slafortune** [comment]
Still on hold

**Comment by trjExpensify** [comment]
The likelihood of someone running into this is in practice is so unlikely. You'd have to be creating an expense and pausing on the tax input selector exactly at the time someone on the workspace settings edits the default. @MonilBhavsar if you haven't easily solved this in a PR that's coming for Track Tax, I'd close this.
