### ISSUE TITLE
[HOLD] Tax - Tax amount does not change when the default tax rate changes

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/36784

**Version Number:** v1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has some tax options.

1. [Employee] Go to workspace chat.
2. [Employee] Open request money page > Manual.
3. [Employee] Enter amount and proceed to confirmation page.
4. [Employee] Click Show more.
5. [Admin] On Old Dot, change the default workspace tax rate.

## Expected Result:
The tax amount will change when the default tax rate changes.

## Actual Result:
The tax amount does not change when the default tax rate changes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/47399a5f-edc3-42d8-a227-ed0f4d48c2df

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by MonilBhavsar** [comment]
Feature is WIP, so we can put this HOLD until we finish the implementation as it is being rolled out in phases https://github.com/Expensify/Expensify/issues/305057

**Comment by bfitzexpensify** [comment]
Subscribed to the tracking issue.

**Comment by bfitzexpensify** [comment]
Still held

**Comment by bfitzexpensify** [comment]
Same update

**Comment by bfitzexpensify** [comment]
Still held

**Comment by MonilBhavsar** [comment]
This is going to be fixed by https://github.com/Expensify/Expensify/issues/377575
So closing
