### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] Category - No spacing between long category name and category status

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/36324

**Version Number:** v1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Collect workspace has a long category name.

1. Log in to New Dot as admin.
2. Go to workspace settings > Collect workspace.
3. Go to Categories.

## Expected Result:
There will be spacing between the long category name and category status.

## Actual Result:
There is no spacing between the long category name and category status.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6395224_1709111519336!Screenshot_20240228-130857_New_Expensify__1_](https://github.com/Expensify/App/assets/115492554/7302c17b-f361-4b3b-98dc-12cc3efb2736)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c7dcc9cd5ddc2d3</li>
        <li>Upwork Job ID: 1762812215508320256</li>
        <li>Last Price Increase: 2024-02-28</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by dragnoir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Missing padding left

### What is the root cause of that problem?

On `WorkspaceCategoriesPage`, the rightElement is missing a maring left.

https://github.com/Expensify/App/blob/3389b90e6b2877e8ee0640e67771a63d47391737/src/pages/workspace/categories/WorkspaceCategoriesPage.tsx#L58-L65




### What changes do you think we should make in order to solve the problem?

Add margin left to rightElement:
```diff
rightElement: (
  <View  style={styles.flexRow}>
-  <Text  style={[styles.disabledText, styles.alignSelfCenter]}>
+  <Text  style={[styles.disabledText, styles.alignSelfCenter, styles.pl2]}>
    {value.enabled ? translate('workspace.common.enabled') : translate('workspace.common.disabled')}
  </Text>
 
```

### What alternative solutions did you explore? (Optional)

**Comment by wustwg** [comment]
Maybe this question is stupid. How can I "Log in to New Dot as admin"?
I find every where on Expensify App and web Ui, but find nothing.
I find the source code of categories , but I don't know how can I show it for me.

**Comment by askavyblr** [comment]
> @wustwg no question is stupid :)
> 
> you can login to new dot as an admin by simply being the owner of the workspace. To see categories, you're going to need to go to Old Dot and login to your account (this one will be the "admin" account). Then go to settings -> workspaces -> new workspace. Create a `Collect` workspace. Open the console and enter:
> 
> ```js
> p = Policy.getCurrent();
> p.policy.isPolicyExpenseChatEnabled = "true";
> p.save();
> ```
> 
> And you're done. Now you should start seeing the collect workspace in ND and the categories

@brandonhenry  please tell me more about Old Dot and login, i did not understand

**Comment by dragnoir** [comment]
PR will be ready in just few hours :)

**Comment by dragnoir** [comment]
PR ready https://github.com/Expensify/App/pull/37668

**Comment by puneetlath** [comment]
@Ollyws friendly reminder about the checklist so we can pay in a couple days.

**Comment by puneetlath** [comment]
Thanks. @Ollyws @dragnoir offers to both of you are pending. Please ping on this issue once you've accepted.

**Comment by dragnoir** [comment]
Thank you @puneetlath offer accepted, also pls check here https://github.com/Expensify/App/pull/37668#issuecomment-1979020614

**Comment by puneetlath** [comment]
@dragnoir has been paid. 

@Ollyws ping me here when you've accepted the offer.

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
