### ISSUE TITLE
iOS - Scan Receipt - Unable to download given corrupted file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37428]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4345844
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Start the Request money > "Scan" receipt flow
2. Upload given corrupted file
3. Verify there's a brief modal for "Scan in progress."
4. Verify the upload fails and you see a red error message explaining that the file was not uploaded
5. Verify that the user is provided a link to download the file for backup
6. Click on the link to download
7. Verify the file is downloaded

## Expected Result:
Attachment is downloaded

## Actual Result:
Corrupted file can not be downloaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3c487d0b-eac6-4a00-b4f5-dc7f7b8ace16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by adelekennedy** [comment]
Let me check if this is expected - In my ind I think we _wouldn't_ let people re-download corrupted files but I may be wrong!
