### ISSUE TITLE
Add NewDot image preflight request caching

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#37431]
# Problem

https://github.com/Expensify/App/pull/36560#issuecomment-1948219686

I believe I've identified the issue—the preflight response isn't being cached, resulting in its repeated execution with each image render. While the images themselves are cached, the browser is forced to reinitiate the preflight check due to the absence of caching headers. These headers are crucial as they instruct the browser on whether and how long to cache the preflight request.

- a preflight request is being made even though the actual resource is cached
    <img width="611" alt="image" src="https://github.com/Expensify/App/assets/12156624/a7ed49ff-65d8-4bec-b813-d01ef6842f93">

Consequently, in offline scenarios, the browser is unable to perform the preflight request, leading to a failure in loading all images.

Here are some visuals to illustrate the point:

- **Image caching example** (Notice how the GET response for the image is cached):
![Image caching example](https://github.com/Expensify/App/assets/12156624/d61c4ced-1b90-4f21-8977-e703d86e55d0)

- **Preflight request missing caching headers**:
![Preflight request missing caching headers](https://github.com/Expensify/App/assets/12156624/992e4f4f-c8fc-4a56-a2ca-7e2b6424ce97)

# Solution

To fix the issue in offline usage, and omit doing preflight request for cached items we should add some cache to the preflight response as well (this is a backend task)

cc @trjExpensify since you're helping coordinate this effort as BugZero

cc @kidroca since the above P / S was written by you 🙏 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9de82c0447606ee</li>
        <li>Upwork Job ID: 1762857975561478144</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
I'll self assign to BZ this one as well.

**Comment by justinpersaud** [comment]
PR is up for review.
