### ISSUE TITLE
Put delayed submission setting on a beta so it's not shown to Collect workspaces by default

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#37430]
# Problem

As part of the plan changes we've considered for Collect in Wave 8, we are [aiming to remove delayed submission](https://expensify.slack.com/archives/C036QM0SLJK/p1709068448513809) as a configuration option in Collect. But since this configuration is going live in NewDot in the near future, we run the risk of showing something that we will take away in the near term, which is bound to upset any of our early adopters of NewDot who originally see it as an option.

# Solution

Put the delayed submission configuration within `Workflows` behind a beta while we figure out how we want to tackle the potential transition of Collect being instant-only, so customers are not seeing this option in NewDot in the interim.

**Comment by kevinksullivan** [comment]
CC @lakchote

**Comment by lakchote** [comment]
It's been deployed to production (https://github.com/Expensify/Web-Expensify/pull/41056#issuecomment-1977300280).

Closing the issue.
