### ISSUE TITLE
[$500] Web - Workspace - It's not accepting the SSN for the first time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37442]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29991
## Action Performed:
1. Login with expensify account
2. Go to Settings > Wallet > Enable Wallet
3. Go through Chase plaid verification flow
4. Follow the flow until Additional details
5. Fill the form with following data: First name: Alberta Last name: Bobbeth SSN: 3333 Any other information for the rest of the fields
6. Press Save & continue

## Expected Result:
It should accept it

## Actual Result:
It's not accepting the SSN for the first time. I can continue after clicking on the button again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7bfe9fc6-1d06-441a-9a09-f6a24721cc11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
I talked to @joekaufmanexpensify and we don't think this should block the deploy given it's current usage. But let's definitely get it fixed.

**Comment by damadoko** [comment]
I think the bug came from BE, the error was retrived from `UpdatePersonalDetailsForWallet`.

**Comment by roryabraham** [comment]
@lanitochka17 the email of the account the bug occurred on would be helpful here

**Comment by roryabraham** [comment]
not able to find any logs for that account in a 72 hour period surrounding this issue's creation 😕 https://staging.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=email%3A%22applausetester%2B0227rbt%40applause.expensifail.com%22%20AND%20timestamp%3A%5B2024-02-27T00%3A00%20TO%202024-02-29T23%3A59%5D

**Comment by roryabraham** [comment]
typo, it's +rb2 not +rbt

**Comment by roryabraham** [comment]
[found logs](https://staging.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2285c2847878f0c31a-VIE%22)+AND+timestamp:[2024-02-27T17:33:40.350Z+TO+2024-02-27T19:33:40.350Z]&index=logs_expensify-027007), looks like an Idology error

**Comment by roryabraham** [comment]
> Using mock Idology ExpectID API response

(throws error response)

lol

**Comment by roryabraham** [comment]
this is a fun gotcha. The Idology ExpectID mock is set up to fail if the last name of the user matches the middle name (just because we needed a way to test failure scenarios in the mock).

In this case, you used Bobbeth for the last name on this request, which caused that to fail.

So all this is expected behavior.
