### ISSUE TITLE
[HOLD for payment 2024-03-11] [HOLD for payment 2024-03-07] App crashes when uploading PDF or opening any attachment sent after PDF

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37469]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #32678
**Version Number:** 1.4.45-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Open any chat
3. Tap the "+" > Add attachment > Choose document
4. Select a PDF and send it
5. Navigate to a chat with a sent PDF file before
6. Send an image or a video
7. Open sent attachments

## Expected Result:
PDF file can be sent, attachments can be opened

## Actual Result:
App crashes when uploading a PDF file or opening any attachment sent after the PDF

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
[Bug6396534_1709176781876!log.txt](https://github.com/Expensify/App/files/14442587/Bug6396534_1709176781876.log.txt)

https://github.com/Expensify/App/assets/38435837/98b25fa1-9b29-479e-bc48-f90fc546f44a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
Regression from this PR: https://github.com/Expensify/App/pull/32678

cc @tienifr

**Comment by MonilBhavsar** [comment]
Issue is fixed! Thanks all

**Comment by trjExpensify** [comment]
As this was a regression from the PR linked to https://github.com/Expensify/App/issues/32232 and fixed by the original author and original C+ review, I'm closing it out as no payments are needed.
