### ISSUE TITLE
[$500] [HOLD for payment 2024-03-11] [HOLD for payment 2024-03-07] Workspace - Workspace avatar is missing in Profile page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37465]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Select a workspace.
4. Go to Profie.
5. If there is no workspace, create a new one, navigating between different workspace tabs and then back to Profile until the avatar disappears.

## Expected Result:
Workspace avatar will be visible.

## Actual Result:
Workspace avatar is missing.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/6190d155-fbc1-423e-a113-01b75489b63c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df14be8421063b01</li>
        <li>Upwork Job ID: 1766972826759442432</li>
        <li>Last Price Increase: 2024-03-10</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We (applause) think this bug might be related to #wave5-free-submitters
cc @dylanexpensify

**Comment by m-natarajan** [comment]
@MonilBhavsar FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by hungvu193** [comment]
Regression from https://github.com/Expensify/App/pull/36849

**Comment by godofoutcasts94** [comment]
I think this :
https://github.com/Expensify/App/blob/3e74ddf0d2b408faa270ff243cf333065b177a87/src/pages/workspace/WorkspaceProfilePage.tsx#L69
is the main culprit behind the above issue.

**Comment by situchan** [comment]
Heads up: I first commented [here](https://github.com/Expensify/App/pull/36849#discussion_r1506637212) so not accepting proposals.
Ideally this should be fixed by PR author

**Comment by blazejkustra** [comment]
Draft [PR](https://github.com/Expensify/App/pull/37480) is up!

**Comment by blazejkustra** [comment]
PR is ready for review 😄

**Comment by MonilBhavsar** [comment]
This has been fixed now. Thanks all!

<img width="1725" alt="Screenshot 2024-02-29 at 4 10 19 PM" src="https://github.com/Expensify/App/assets/32012005/c2404609-64b8-454f-a832-e80f74d18d98">

**Comment by mallenexpensify** [comment]
@mkhutornyi , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01df14be8421063b01

**Comment by mallenexpensify** [comment]
Contributor+: @mkhutornyi paid $500 via Upwork.  

@mkhutornyi , can you fill out the BZ checklist above plz? I'm unsure if we'll want to check this on every release or monthly, QA can decide. 

- https://github.com/Expensify/App/issues/37465#issuecomment-1972147671

**Comment by mallenexpensify** [comment]
Thanks @mkhutornyi , closing
