### ISSUE TITLE
[HOLD for payment 2024-03-14] Chat - Console error shows up when sending message with mention or text

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37463]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Send a message with mention or emoji.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b55f3b58-2b4d-42d2-b97c-eaa9e78b7f00

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by m-natarajan** [comment]
We (Applause) this bug might be related to #vip-vsb
cc @quinthar

**Comment by m-natarajan** [comment]
@MonilBhavsar FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MonilBhavsar** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1709208081154149

**Comment by MonilBhavsar** [comment]
Most probably not a blocker.
To fix the issue we have two options - 
1. Degrade `react-native-reanimated` that was updated here https://github.com/Expensify/App/pull/36404
2. Fix the issue in `react-native-reanimated`. If `node.children` is not an array, we break https://github.com/software-mansion/react-native-reanimated/blob/06231465a93e7650f0c4c66035f48dcadbe2467a/src/reanimated2/layoutReanimation/web/domUtils.ts#L170

**Comment by MonilBhavsar** [comment]
Not a blocker, just a console error

**Comment by MonilBhavsar** [comment]
Upstream PR is merged. We can update our version of `react-native-reanimated` once the fix is released

**Comment by tomekzaw** [comment]
The fix has been released in Reanimated 3.7.2, we will submit a PR with the bump.

**Comment by filip-solecki** [comment]
Hi @MonilBhavsar! I am Filip from SWM and I will work on this!

**Comment by MonilBhavsar** [comment]
Thanks Filip! Assigned you to issue

**Comment by MonilBhavsar** [comment]
I think we can close this as no payment is required. Thanks all!

**Comment by MonilBhavsar** [comment]
Ah okay! Given a version bump, I think $125 is a fair amount. Do you agree?

**Comment by anmurali** [comment]
@MonilBhavsar what do you think here? I believe I need to create a manual Upwork offer to pay @mkhutornyi based on the final amount you decide!

**Comment by anmurali** [comment]
https://www.upwork.com/nx/wm/offer/101507041
@mkhutornyi can you accept and then DM me on slack so I can pay it. Gonna close the issue now.
