### ISSUE TITLE
IOU-"Enter a merchant name"error shown for amount in split bill scan.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37473]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Launch app
2. Tal on Workspace chat
3. Tap plus icon near compose
4. Tap split bill--- Scan
5. Using camera upload a photo
6. Tap split
7. Open the newly created split scan expense
8. Note amount field error

## Expected Result:
"Enter an amount"error must be shown for amount in split bill scan.

## Actual Result:
"Enter a merchant name"error shown for amount in split bill scan.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/731771aa-aadb-44fd-ab73-ddcffcbdebb0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-bills

**Comment by izarutskaya** [comment]
@danieldoglas I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by youssef-lr** [comment]
cc @kubabutkiewicz we think this might be coming from your PR https://github.com/Expensify/App/pull/34168

**Comment by kubabutkiewicz** [comment]
taking a look 👀

**Comment by kubabutkiewicz** [comment]
https://github.com/Expensify/App/pull/37515 PR ready @youssef-lr

**Comment by puneetlath** [comment]
FYI, this is likely fixed by [this revert](https://github.com/Expensify/App/pull/37529). Will have QA re-test once it is CP'd.

**Comment by puneetlath** [comment]
Looks like the revert fixed this.
