### ISSUE TITLE
[No payment] Chat-URL link shown in preview but turned to text after sending message.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter J.com in compose box and note URL link is shown
4. Send the message

## Expected Result:
URL link shown in preview and same link format must be shown after sending message.

## Actual Result:
URL link shown in preview but turned to text after sending message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a2ef057a-7103-4c41-b235-51fbcbd68cfb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
Thanks @bernhardoj. cc @aswin-s this is coming from your [PR](https://github.com/Expensify/App/pull/36819)

**Comment by aswin-s** [comment]
Checking. 

Meanwhile the fix should be raised in expensify-commons repo. Wouldn't that impact other in progress PRs? I think we should revert #34324 and https://github.com/Expensify/expensify-common/pull/651 so that it wouldn't block others.

**Comment by youssef-lr** [comment]
@lschurr FYI this was tied to a revert to a revet to fix a blocker so no payment is needed.

**Comment by miljakljajic** [comment]
Sorry - I just realised that myself

**Comment by miljakljajic** [comment]
I am going to be OOO on the 7th so assigned Lauren, but all good here. @lschurr I will unassign you
