### ISSUE TITLE
Android - App does not open profile modal when signing in using magic code link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** nathanmulugetatesting@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37193
## Action Performed:
1. As account A have a conversation with account B
2. Copy share code of account B
3. Sign out from account A on Android and kill the app
4. Paste the share code of account B elsewhere and click on it to open it on Android
5. Input account A's email on Android app and click next
6. When magic code email gets in your email click on the magic link

## Expected Result:
The app should open up and go to the profile modal of account B

## Actual Result:
The app does not open the profile modal of account B but opens the LHN. But when using the magic code to sign in the app takes user to the profile modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/685b11d2-bea5-4e3b-8ffd-9568e323aeaf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
Hmm. After review, it's just such an edge case to even encounter this, and it's only a single platform issue. I'm going to close it so we can focus on our roadmap.

If this does by some chance become an issue for many users in the future we can revisit, I just don't really see that being a thing in the near term. Let me know if you strongly disagree.
