### ISSUE TITLE
IOU - In WS, request scan created with corrupted pdf able to view file.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4331496
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on workspace chat
3. Tap plus icon near compose
4. Tap request money ---- Scan
5. Upload a corrupt file
6. Enter all details
7. Tap request
8. Tap on newly created expense
9. Enter all details
10. Tap on receipt

## Expected Result:
In WS, request scan created with corrupted pdf must not be able to view file

## Actual Result:
In WS, request scan created with corrupted pdf able to view file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/615b00e1-ed45-4b77-9f68-7d6ed47217e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to [#wave5-free-submitters](https://expensify.enterprise.slack.com/archives/C05DWUDHVK7)
CC @dylanexpensify

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
>must not be able to view file

Why is this the expected behaviour? Why would we not show a corrupted file? I think this is fine, it's pretty obvious the file is corrupted.
