### ISSUE TITLE
 Web - Scan - When receipt scan is in progress, admin can see the thumbnail of the receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37499]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4350781
**Email or phone of affected tester (no customers):** stela.utest+29@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. As the employee, navigate to the workspace chat
2. Select Request money &gt; Scan
3. Upload a image of a receipt
4. Complete the money request
5. Login as the workspace admin
6. Navigate to the workspace chat with the employee

## Expected Result:
The expense request is not displayed because the receipt is still in scan process

## Actual Result:
The expense request thumbnail is displayed and states that the receipt is still in scan process

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/3abfed7d-0981-4bde-90f9-ba2125090ebd

![Bug6397055_1709214381932!adminscaninprog](https://github.com/Expensify/App/assets/78819774/5bdd2892-4139-42bd-a1b7-e0fd8fff15bb)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
closing because we are changing this design with this doc

https://docs.google.com/document/d/1hKK7emsQt4iDvP8Ohvk5aCc8gNdRelyxvbxDkXZxNRA/edit
