### ISSUE TITLE
[$500] Android - An extra space is created at the top of the chat list when pinning and unpinning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37497]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/20070&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):** nathanmulugetatesting@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Start a conversation between two accounts, account A (main testing device) account B on another device
2. Send an IOU from account B to account A (to the main testing device)
3. Pay the IOU from account A (on android)
4. Go to the LHN and unpin any other conversation you have and let the conversation you had with account B be at the top
5. Hold on the chat with account B and pin it
6. Hold on the chat with account B again and unpin it right away

## Expected Result:
There should be no extra space between the top chat and the title on the LHN

## Actual Result:
An extra space gets created between the first chat at the top and the title

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110a8f38476d1ad2f</li>
        <li>Upwork Job ID: 1763342127580393472</li>
        <li>Last Price Increase: 2024-03-07</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment]
@dukenv0307 bump on @aimane-chnaif's question above!

**Comment by johncschuster** [comment]
[Bumped in Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1710191927112459)

**Comment by Julesssss** [comment]
Can anyone reproduce? I don't see the issue on Android `1.4.52-0`

**Comment by Julesssss** [comment]
> can you share a video of the behavior if you're unable to reproduce?

Instead, could you please share a video of the reproduction so I can make sure I'm following the steps correctly

**Comment by johncschuster** [comment]
This was just assigned out, Melvin. Chill.

**Comment by johncschuster** [comment]
Thanks for the comment, @aimane-chnaif! I'm having a hard time finding the PRs that fix this issue. Can you point me in the right direction? 

Is it https://github.com/Expensify/App/issues/38670, or is it something else?

I'm specifically looking for the merge date so I can calculate the payment date. Thanks!

**Comment by johncschuster** [comment]
Payment has been issued to @aimane-chnaif and @dukenv0307. Thanks for your contributions! 🎉

**Comment by johncschuster** [comment]
@Julesssss is there a BZ Checklist that needs to be completed?

**Comment by johncschuster** [comment]
Great! It sounds like we can go ahead and close this issue then. Thanks, everyone!
