### ISSUE TITLE
Task – Previous assignee is visible for a moment when change assignee twice Offline and back

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37490]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any Task report
4. Disable the internet connection
5. Update task assignee twic, use accounts with names
6. Enable the internet connection on the device

## Expected Result:
Only last assignee is visible when change assignee twice Offline and back Online.

## Actual Result:
Previous assignee is visible for a moment when change assignee twice Offline and back Online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d047a4b1-5dbf-4ecd-80a5-ad2b1ea94a31

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
@izarutskaya is the previous assignee only viewable to the person creating the task - not the second individual assigned?  If so, I think this is fine to close.

**Comment by slafortune** [comment]
I think we can close this.
