### ISSUE TITLE
Category - App returns to main chat when refreshing Categories Settings page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.45-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is admin of Collect workspace that has categories.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Select the Collect workspace.
4. Click Categories.
5. Click Settings.
6. Refresh the page.
## Expected Result:
App will remain on workspace category page (note the background).
## Actual Result:
App returns to chat on home page with Categories Settings open (note the background).
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/4b7936ef-46b6-40d3-9cd5-033e99a5e289

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave8-collect-admins

**Comment by m-natarajan** [comment]
@youssef-lr FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by luacmartins** [comment]
This is a known issue - https://github.com/Expensify/App/issues/37517. I'll close this one in favor of https://github.com/Expensify/App/issues/37517.
