### ISSUE TITLE
Category - Offline indicator appears below "Members must categorize.." instead of page bottom

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.45-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is admin of Collect workspace that has categories.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Select the Collect workspace.
4. Tap Categories.
5. Tap Settings.
6. Go offline
## Expected Result:
The offline indicator will be displayed at the bottom of the screen.

## Actual Result:
The offline indicator is displayed below "Members must categorize all spend",

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9e24e078-15d7-41ce-8137-627ecfe4195b

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave8-collect-admins
cc @zanyrenney

**Comment by m-natarajan** [comment]
@lakchote FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by lakchote** [comment]
@ArekChr @allroundexperts since you worked on the PR related to categories.

Looks like @shawnborton [comment](https://github.com/Expensify/App/pull/37133#issuecomment-1966501363) about showing offline indicator at the bottom for mobile got overlooked. Please address this issue, thanks.

**Comment by luacmartins** [comment]
We're fixing that here https://github.com/Expensify/App/pull/37209#issuecomment-1971133292

**Comment by luacmartins** [comment]
Gonna close this issue as it's not a blocker
