### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] [Simplified Collect][Categories] - "Categorize all expense" switch is not disabled when all categories are disabled

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37508]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.45-1

**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is admin of Collect workspace that has categories.
- All categories are disabled in the Collect workspace.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Select the Collect workspace.
4. Click Categories.
5. Click Settings.
6. Click on the toggle.

## Expected Result:
"Categorize all expense" switch should be disabled.

## Actual Result:
"Categorize all expense" switch can be toggled on and off. On Old Dot, the switch is disabled when all categories are disabled.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/8e2f43ae-78ed-402a-8db7-e16017cad151

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c2567013c13680f</li>
        <li>Upwork Job ID: 1771256687469146112</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave8-collect-admins
cc @zanyrenney

**Comment by m-natarajan** [comment]
@luacmartins FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by luacmartins** [comment]
I don't think this is a blocker. We're still developing this feature. I'll tag @ArekChr so we can fix this as part of a follow up issue.

**Comment by luacmartins** [comment]
I'm gonna put this on hold for now, since we're introducing a new `areCategoriesEnabled` key and we should be checking that key

**Comment by abekkala** [comment]
Not overdue, on Hold

**Comment by luacmartins** [comment]
on hold

**Comment by abekkala** [comment]
not overdue - on hold

**Comment by luacmartins** [comment]
On hold

**Comment by abekkala** [comment]
@stephanieelliott I'm ooo until April 08 - I'll be taking back any issues still Open once I return

___

### CURRENT STATUS:
This is on HOLD. https://github.com/Expensify/App/issues/37508#issuecomment-1971951489
If it happens to go off Hold while I'm ooo @luacmartins may need to decide if this would be an internal or external fix

**Comment by luacmartins** [comment]
The `Members must categorize all spend` should be turned off if all categories are disabled

**Comment by luacmartins** [comment]
Thanks for the proposal's everyone. A few comments:

@codinggeek2023 and @Krishna2323 your proposals are missing `we should turn the setting off if the last enabled category was disabled`. That means that when the user disables the last category, we need to set `areCategoriesEnabled` to false

@tienifr your proposal is missing `The Members must categorize all spend should be turned off if all categories are disabled`. That means that if all categories are disabled, the switch should be off and disabled.

**Comment by getusha** [comment]
Reviewing proposals.

**Comment by getusha** [comment]
@codinggeek2023 after applying your solution i am unable to toggle the option even if there is Enabled category

https://github.com/Expensify/App/assets/75031127/68785e7b-baa9-4847-ae5f-0b9293cd9dd3

**Comment by luacmartins** [comment]
None that I can think of.

**Comment by luacmartins** [comment]
What @tienifr said makes sense. Let's use `areCategoriesEnabled` if possible.

**Comment by getusha** [comment]
We can proceed with @tienifr's [proposal](https://github.com/Expensify/App/issues/37508#issuecomment-2015782768) the main solution sounds good.
🎀 👀 🎀 C+ Reviewed.

**Comment by luacmartins** [comment]
Nice! @tienifr could you please prioritize working on this PR? When do you think you'd be able to get one ready for review?

**Comment by luacmartins** [comment]
Nice! Please ping me once it's ready!

**Comment by stephanieelliott** [comment]
PR is under active review!

**Comment by stephanieelliott** [comment]
PR is undergoing QA

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR APRIL 15

- Fix: @tienifr [$500, if no regressions] [offer](https://www.upwork.com/nx/wm/offer/0)
- PR Review: @getusha [$500, if no regressions] [offer](https://www.upwork.com/nx/wm/offer/0)

**Comment by abekkala** [comment]
@getusha can you complete the checklist above, please?

**Comment by abekkala** [comment]
@tienifr payment sent and contract ended - thank you! 🎉

**Comment by luacmartins** [comment]
No need to add tests. We already did so as part of the project.

**Comment by abekkala** [comment]
@getusha once you accept the offer I can send payment
[Upwork Offer](https://www.upwork.com/nx/wm/offer/101584296)

**Comment by abekkala** [comment]
@getusha payment sent and contract ended - thank you! 🎉
