### ISSUE TITLE
Category - Checkbox is clickable outside near the right of checkbox

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found while executing #37402
**Version Number:** v1.4.45-1

**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is admin of Collect workspace that has categories.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Select the Collect workspace.
4. Click Categories.
5. Click Settings.
6. Click outside near the right side of checkbox.
## Expected Result:
The checkbox will not be clickable outside the checkbox.
## Actual Result:
The checkbox is clickable outside near the right of checkbox.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/0a74d9df-e76d-40d6-9373-481a39bf60cb

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave8-collect-admins
cc @zanyrenney

**Comment by m-natarajan** [comment]
@bondydaa FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by luacmartins** [comment]
Agreed this is not a blocker and that we can handle this in https://github.com/Expensify/App/issues/37295.
