### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] [Simplified Collect][Distance Rates] Implement PolicyDistanceRatesPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37510]
Implement [PolicyDistanceRatesPage](https://docs.google.com/document/d/1hJlRWUQlOAcDsq23zWWITmC83tuDs8rfI4rPAwpjhc4/edit#bookmark=id.xfubmgp57mbj) following the specifications in the design doc

cc @MrMuzyk 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bc3efd271014d5a</li>
        <li>Upwork Job ID: 1763222628061282304</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by anmurali** [comment]
[MrMuzyk](https://github.com/MrMuzyk) is working on this, not overdue!

**Comment by anmurali** [comment]
@getusha - can you pls complete the BZ checklist and accept [the offer](https://www.upwork.com/nx/wm/offer/101509309)

**Comment by getusha** [comment]
@anmurali i think this doesn't need a regression test since it is a new feature https://github.com/Expensify/App/issues/37311#issuecomment-2015863316

**Comment by luacmartins** [comment]
Correct, we'll add those to testrail when we wrap up the project

**Comment by luacmartins** [comment]
Only pending payment

**Comment by anmurali** [comment]
Waiting on @getusha to accept the offer. Still shows pending on my dashboard on Upwork.

**Comment by anmurali** [comment]
Paid
