### ISSUE TITLE
Scan- Wrong IOU details in the notification email

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0

**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1.Log in in the app
2.Request money to an account that you have access to the email inbox
3.Do not read the message in NewDot to trigger the email notification
## Expected Result:
IOU email subject and body display requestee requested amount

## Actual Result:
IOU subject : Requestee requested amount
IOU body: Reqestee owes amount
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6397103_1709216074740!IOUwrong](https://github.com/Expensify/App/assets/38435837/05a7cc08-4a58-4d4f-93e8-78c421508ca0)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@rlinoz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by sonialiap** [comment]
@m-natarajan can you clarify which account's email you're checking? Also what your account relationships are like. The accounts I tested with both own workspaces that the other is a part of. Account A has issued multiple requests (testing), should there be a clean slate - no outstanding expenses? 

I tried
1. Account A requests from account B
2. Account B checks email (screenshot below) 

<img width="586" alt="image" src="https://github.com/Expensify/App/assets/17131195/26145d8d-764b-4001-ba1e-61fd370d32d0">

**Comment by puneetlath** [comment]
This is a back-end issue, so going to remove the DeployBlockerCash label.

**Comment by rlinoz** [comment]
Related to https://github.com/Expensify/App/issues/35353, will take a look later.

**Comment by rlinoz** [comment]
Done with the other issue, going to take a look at this tomorrow.
