### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] [Simplified Collect][Distance Rates] Implement PolicyDistanceRateSettingsPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37513]
Implement [PolicyDistanceRateSettingsPage](https://docs.google.com/document/d/1hJlRWUQlOAcDsq23zWWITmC83tuDs8rfI4rPAwpjhc4/edit#bookmark=id.8o08z5f979u6) following the specifications in the design doc

cc @MrMuzyk
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010902f2b08cb0564b</li>
        <li>Upwork Job ID: 1763223051466571776</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by hereistopdev** [comment]
I am a freelancer from Upwork, I would like to work on this issue

**Comment by hereistopdev** [comment]
Contributor details
Your Expensify account email: jinbryan000@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d2e2282d627e9a4b

**Comment by hereistopdev** [comment]
I am ready to start work right now

**Comment by luacmartins** [comment]
@hereistopdev thanks for the interest. However, we already assigned someone to work on this issue.

**Comment by hereistopdev** [comment]
ok
You are welcome

**Comment by luacmartins** [comment]
We’re still working on the main page. We’ll get to this once we’re done with that

**Comment by luacmartins** [comment]
We have a draft pr

**Comment by luacmartins** [comment]
@parasharrajat to fix https://github.com/Expensify/App/issues/38662? I think @MrMuzyk is assigned and will work on a fix.

**Comment by luacmartins** [comment]
Just pending payment

**Comment by sakluger** [comment]
Sorry for the delay, I'll handle payment now. Just to confirm, there was a regression on this issue's PR, correct? So the payment would be $250?

**Comment by luacmartins** [comment]
I don't think that was a regression since the feature didn't exist yet. I think the full l$500 still applies in this case.

**Comment by sakluger** [comment]
Got it, thanks for confirming!

@ishpaul777 I've sent you an offer via Upwork: https://www.upwork.com/nx/wm/offer/101802947
