### ISSUE TITLE
[HOLD for payment 2024-04-03][$500] [Simplified Collect][Distance Rates] Implement PolicyEditDistanceRatePage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37514]
Implement [PolicyEditDistanceRatePage](https://docs.google.com/document/d/1hJlRWUQlOAcDsq23zWWITmC83tuDs8rfI4rPAwpjhc4/edit#bookmark=id.9gsmfzgc3l00) following the specifications in the design doc

cc @MrMuzyk
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c789ebaa40de7722</li>
        <li>Upwork Job ID: 1763222934538375168</li>
        <li>Last Price Increase: 2024-02-29</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cubuspl42</details>

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by luacmartins** [comment]
We’re still working o the main page. We’ll get to this one that’s done

**Comment by luacmartins** [comment]
We'll get to this once the other distance rate issues are done

**Comment by luacmartins** [comment]
We have a draft PR

**Comment by cubuspl42** [comment]
> ⚠️ Looks like this issue was linked to a **Deploy Blocker** [here](https://github.com/Expensify/App/issues/38673)

Our issue was mentioned like "PR for that issue may fix this"

**Comment by luacmartins** [comment]
Automation didn't kick in. [PR hit production on Mar 26th](https://github.com/Expensify/App/pull/38237#issuecomment-2021927284).

**Comment by cubuspl42** [comment]
So the next step (payments) is on @muttmuure, right?

**Comment by luacmartins** [comment]
Yes, correct

**Comment by luacmartins** [comment]
Just pending payment

**Comment by luacmartins** [comment]
@getusha @muttmuure has payment been processed for this issue?

**Comment by muttmuure** [comment]
Looking

**Comment by muttmuure** [comment]
Paid
