### ISSUE TITLE
Group Split - Error shows for Merchant and not Amount, while Merchant leads to error page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.45-1

**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat.
3. Click + > Split bill > Scan.
4. Create a scan split bill.
5. Click on the split preview.
6. Click Split.
7. Note that it shows error for Merchant and not amount.
7. Click Merchant.
## Expected Result:
In Step 6, it will show error for Amount only.
In Step 7, Merchant editor page will open without issue.
## Actual Result:
In Step 6, it shows error for Merchant and not Amount.
In Step 7, Merchant leads to not here page.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/82e2b530-52e2-48bd-94ed-5c9ccbc3c03f

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to #vip-split-p2p-chat-groups
cc @arielgreen

**Comment by m-natarajan** [comment]
@deetergp FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by puneetlath** [comment]
Looks like the revert fixed this.
