### ISSUE TITLE
[$500] Tooltips - Bottom menu tooltips from LHN are missing when change Theme

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4350765
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open staging.new.expensify.com
2. Go to Profile> Preference> Theme
3. Change the theme to Dark or Light
4. Go back to LHN
5. Hover over bottom LHN menu (Chats, Create, Settings)

## Expected Result:
Tooltip should appear when hover over Chats, Create and Settings

## Actual Result:
Tooltips does not appear when hover over Chats, Create and Settings options after changing the theme

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/05ee7db6-6c55-4487-a188-0bf88a7b8b05

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d16f910e9adad14</li>
        <li>Upwork Job ID: 1765137186851168256</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment]
This definitely feels like a bug to me. I would expect the on-hover tooltips to appear (in the appropriate theme) after the theme has been switched.

**Comment by allroundexperts** [comment]
Taking over as a C+.

**Comment by allroundexperts** [comment]
I agree with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/37553#issuecomment-1978468141). We should not re-calculate tooltip positions when only the theme is changed.

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment]
Hm... that's a fair point. Let's wait for @iwiznia to weigh in.

**Comment by iwiznia** [comment]
Meh, if it appears in the future we can fix it then
