### ISSUE TITLE
Email mentions as "Pay" even though in the app it says "approve"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709159127049929

## Action Performed:
1. Create an expense report as employee and submit to admin
2. Wait for the email notification
3. Check the email received

## Expected Result:
Email should mention `Approve`

## Actual Result:
It says `Pay`

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (3)](https://github.com/Expensify/App/assets/38435837/1e0aa9c3-d89c-43bf-9347-37d93efcb724)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
This is being handled via https://github.com/Expensify/Expensify/issues/364323#issuecomment-1972039043
