### ISSUE TITLE
[HOLD for payment 2024-03-11] Profile - Date of birth opens Legal page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37597]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings.
3. Go to Profile.
4. Click Date of birth.

## Expected Result:
Date of birth page will open.

## Actual Result:
Legal name page opens instead.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8db45073-3c03-4e8f-9230-091bbd2a851d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01576dd3bd294513f4</li>
        <li>Upwork Job ID: 1763548635401383936</li>
        <li>Last Price Increase: 2024-03-01</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@cristipaval I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by twisterdotcom** [comment]
Surely an external bug yeah. Let's throw it on, but would be good to know what this was introduced in.

https://github.com/Expensify/App/assets/9133401/3f726097-6dc1-4dd2-be3d-578bfcb14870

**Comment by bernhardoj** [comment]
This is being fixed in https://github.com/Expensify/App/pull/37592

**Comment by rushatgabhane** [comment]
@ishpaul777 that looks like [loom](https://www.loom.com/)

**Comment by twisterdotcom** [comment]
haha, I started using https://www.screen.studio @ishpaul777! Glad to know this is being fixed. Just linked these. Gonna stick `Reviewing` on it.
