### ISSUE TITLE
[HOLD for payment 2024-03-13] [HOLD for payment 2024-03-11] Fix `DateOfBirth.tsx`

### ISSUE THREAD

**Issue by grgia** [Expensify/App#37594]
Tracking issue for follow up to https://github.com/Expensify/App/pull/37426/files/daeb2a0ef88166fa05eb2f01d3490863eb82da7c#r1508781465

**Comment by grgia** [comment]
In progress PR here - https://github.com/Expensify/App/pull/37592
cc @kubabutkiewicz 

@situchan I assigned you as C+ as this is a follow up

**Comment by sonialiap** [comment]
Looks like this part of a TS migration, is that correct?

**Comment by sonialiap** [comment]
Thanks for the confirmation 👍
