### ISSUE TITLE
[$500] Web  -Workspace-Highlight for the checkbox goes out of bound on members page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37599]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:**

## Action Performed:
1. Go to workspace settings page > Members
2. Mark one of the members' checkbox
3. Click on down arrow on keyboard
4. Observe the highlight on the checkbox

## Expected Result:
The highlight should not go out of bounds

## Actual Result:
The highlight on the checkbox goes out of bound

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cd61a207-4340-4453-8a25-183b2a866d69

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016007b30fb57512d8</li>
        <li>Upwork Job ID: 1763710609566830592</li>
        <li>Last Price Increase: 2024-03-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@greg-schroeder I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
Probably a low prio #wave8 issue eh @zanyrenney?

**Comment by greg-schroeder** [comment]
all right, so closing then!
