### ISSUE TITLE
Distance - Hitting Enter in waypoint editor does not save the address

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37600]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Distance.
3. Click Start.
4. Enter the address and save it.
5. Click Start again.
6. Hit Enter.

## Expected Result:
Hitting Enter will save the address and return to the distance request page,

## Actual Result:
Hitting Enter only closes the address list and does not save the address.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1bc481a8-037d-40ee-89ae-e95c96c14168

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment]
Closing, since I am seeing this behavior for other addresses, like in the profile.
