### ISSUE TITLE
[$500] [HOLD for payment 2024-03-19] Do not show "member not found" when loading member list

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37605]
Coming from [this comment](https://github.com/Expensify/App/pull/37199#issuecomment-1973366012), we should not show "member not found" while loading the member list

cc @burczu 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5126ce1290525b2</li>
        <li>Upwork Job ID: 1770042366576177152</li>
        <li>Last Price Increase: 2024-03-19</li>
    </ul>
</details>

**Comment by burczu** [comment]
not overdue - I'll work on this today

**Comment by zanyrenney** [comment]
@aimane-chnaif invited you to job on UW - https://www.upwork.com/jobs/~01d5126ce1290525b2 pls accept for payout.

**Comment by zanyrenney** [comment]
accepted proposal.

**Comment by zanyrenney** [comment]
payment summary:
@burczu does not require payment (Contractor)
@aimane-chnaif requires payment (Needs manual offer from BZ) - paid $500 on Upwork.
