### ISSUE TITLE
[Categories] [LOW] Update the categories settings page copy

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37614]
Coming from [this PR](https://github.com/Expensify/App/pull/37209), we merged it without verified Spanish translations to unblock other issues in the pipeline. We should update the revised copy.

Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1709215749926399

cc @ArekChr

**Comment by ArekChr** [comment]
@luacmartins happy to fix that, please assign me

**Comment by luacmartins** [comment]
Assigned to you @ArekChr

**Comment by sakluger** [comment]
I don't think I need to do anything on this issue, let me know if my help is needed.

**Comment by sakluger** [comment]
@ArekChr is Daily the correct priority for this, or is weekly more accurate?

**Comment by luacmartins** [comment]
I think we can move to weekly

**Comment by luacmartins** [comment]
Left a comment on the PR, but I think we might be able to close this.

**Comment by luacmartins** [comment]
Closing this issue since we no longer have generic copy to update!
