### ISSUE TITLE
Sign in - 'Couldn't retrieve account details' error message displayed when trying to sign in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37610]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign out
2. Trying to sign in again
3. Repeat step 1 & 2

## Expected Result:
There should be error

## Actual Result:
'Couldn't retrieve account details, please try to sign in again.' error message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6398348_1709304514984!Screenshot_2024-03-01_at_4 18 01_in_the_afternoon](https://github.com/Expensify/App/assets/78819774/365e7bbd-2e90-4b75-b577-d0f679465132)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave9
CC @MitchExpensify

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment]
Where are you signing out from OldDot or NewDot?

**Comment by anmurali** [comment]
@lanitochka17 - the repro steps are sorta unclear. I can sign out and sign back in just fine! Can you please flesh out the scenario better?

**Comment by anmurali** [comment]
Still cannot reproduce...

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.81-4

https://github.com/Expensify/App/assets/78819774/66f1749a-f6d4-43fe-8b1c-d6651e0fdeca

[staging.new.expensify.com-1718043249736.log](https://github.com/user-attachments/files/15777537/staging.new.expensify.com-1718043249736.log)

**Comment by anmurali** [comment]
I have tried to sign out and sign in multiple times, and I am never able to reproduce this...
