### ISSUE TITLE
IOU - Request money to gmail user, header is loading & in LHN, report title is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37611]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4359588
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login with new expensifail account
3. Tap fab--- request money
4. Enter an amount and tap next
5. Enter and select a gmail user
6. Tap request
7. Note header is loading
8. Tap app back button and navigate to LHN
9. Note the chat report title is missing

## Expected Result:
With new expensifail account, request money to gmail user, header& in LHN, chat report title must be displayed

## Actual Result:
With new expensifail account, request money to gmail user, header is loading & in LHN, chat report title is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/187bdef2-3d43-4822-be62-c6e936c8a266

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@MitchExpensify  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment]
Asking vip split if it fits there https://expensify.slack.com/archives/C05RECHFBEW/p1709346372862959

**Comment by MitchExpensify** [comment]
Closing as this isn't obviously related to a wave or VIP
