### ISSUE TITLE
[$500] [HOLD for payment 2024-03-14] Swiping down the receipt image stucks at the bottom 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709024399388799

## Action Performed:
1. Open any receipt image from the IOU details
2. Swipe down from top to bottom

## Expected Result:
The behavior should be similar to chat attachment image, should go back to the details page

## Actual Result:
Swiping down on the receipt, the view just hangs and have to press back to get back to the report

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7b5ec3b8-678e-4f97-aece-ef26721a1ac4

https://github.com/Expensify/App/assets/38435837/874ca846-3b07-4a4b-b84d-7ff735afed14

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb59e55baa55ef61</li>
        <li>Upwork Job ID: 1768025358979284992</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by kirillzyusko** [comment]
I'm on it 👀 I implemented this feature so will prepare a fix for this problem 😎 

Will open a PR soon 😊

**Comment by joekaufmanexpensify** [comment]
Assigned @Pujan92 as he reviewed here

**Comment by Pujan92** [comment]
@joekaufmanexpensify I think this doesn't require a checklist as this is a follow-up issue for the new feature https://github.com/Expensify/App/pull/37080.

**Comment by joekaufmanexpensify** [comment]
@Pujan92 offer sent for $500!

**Comment by Pujan92** [comment]
Thanks @joekaufmanexpensify, Accepted!

**Comment by joekaufmanexpensify** [comment]
@Pujan92 $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
