### ISSUE TITLE
Workspace settings - Delete Key Fails to Remove Decimal Point After Entering 5-Digit Rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37624]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1: Setting
2: Workspace
3: Workspace Settings
4: Reimbursement
5: Write 5 digits for Rate Amount and save
6: Click on the rate on the preview, the dot appears. Try to clear the dot by clicking on the dot. Observe that the backspace (Windows) or Delete (Mac) doesn't remove the dot

## Expected Result:
The "Delete" key does not remove the dot created after adding a 5-digit amount and saving it

## Actual Result:
The "Delete" key should remove the dot created after adding a 5-digit amount and saving it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f39edb8d-b029-4b79-8d61-119a0d83a6ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave8
CC @zanyrenney

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment]
Apologies, I've been OOO sick, but am reviewing today!

**Comment by dylanexpensify** [comment]
this seems very low priority - moving to close for now
