### ISSUE TITLE
Chat – New chat with a draft disappears in LNH if navigate to another conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37626]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4355984
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Click on the green + button and select the "Start Chat" option.
4. Search for a user that you don't have any messages with and open the chat
5. Draft a message but don't send it
6. Navigate to another conversation

## Expected Result:
The conversation is still displayed in LHN and that it has the draft status

## Actual Result:
Chat with a draft disappears in LNH if navigate to another conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a3fa6471-dd3a-49ed-ac45-8eae5d0c0c39

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by nkdengineer** [comment]
Contributor details
Your Expensify account email: mailto:nkdengineer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0134d0b74faef1a5ac

**Comment by nkdengineer** [comment]
Contributor details
Your Expensify account email: nkdengineer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0134d0b74faef1a5ac

**Comment by nkdengineer** [comment]
Contributor details
Your Expensify account email: [nkdengineer@gmail.com](mailto:nkdengineer@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0134d0b74faef1a5ac

**Comment by nkdengineer** [comment]
Contributor details
Your Expensify account email: nkdengineer@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0134d0b74faef1a5ac

**Comment by stephanieelliott** [comment]
I think this is expected behavior -- a chat shouldn't stick around in the LHN unless there is a history of messages. That history wouldn't exist for a user you haven't chatted with before, so I think it makes sense that it disappears from the LHN (even considering that there is an unsent draft)
