### ISSUE TITLE
 IOU - The report with the newly created IOU does not move to the bottom of the conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37632]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4356077
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with HT account
3. Create WS
4. Navigate to the WS main room
5. Create a manual IOU with any data and send it to the room
6. Send >10 messages to the same room
7. Create another manual IOU with any data and send it to the room
8. Scroll up to the IOU report
9. Create another manual IOU with any data and send it to the room

## Expected Result:
The report with the newly created IOU should move to the bottom of the conversation

## Actual Result:
The report with the newly created IOU does not move to the bottom of the conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/190ca89a-6132-41ac-b292-531902e431c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
We no longer move IOU reports when they get updated, so this is not a bug. Did this come from a regression test? If so, we'll need to update it.
