### ISSUE TITLE
Android - Edit button on profile Avatar is barely visible when upload photo in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37636]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4359334
**Email or phone of affected tester (no customers):** applausetester+0514gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go offline
2. Navigate to Profile> Tap on profile Avatar> Upload photo

## Expected Result:
Edit button should be grayed out

## Actual Result:
Edit button is transparent and barely visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

![Bug6398734_1709323184680!dark](https://github.com/Expensify/App/assets/78819774/16263f4b-0edf-479a-85aa-2ed3887f4ac8)

![Bug6398734_1709323184673!light](https://github.com/Expensify/App/assets/78819774/f43881c7-fb17-44b1-86f1-37859dffe20e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by adelekennedy** [comment]
agree this is vip-vsb, pending an update in the wave-collect room

**Comment by adelekennedy** [comment]
I'm actually going to close this for now
