### ISSUE TITLE
Scan- Reply from Expensify for failed scanning in transaction thread is visible from main chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37637]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Create a Scan request with an invalid receipt
4. Wait for the scanning to fail
5. Go to the request details page
6. Return to main chat
7. Create another Scan request

## Expected Result:
The reply from Expensify for failed scanning will not appear in 1:1 DM, as it only appears in IOU report

## Actual Result:
The reply from Expensify for failed scanning appears in 1:1 DM after the second scan request is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/00ecb66e-c2c1-4a52-a42a-028e0e698371

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
Trying to recreate this: https://expensify.slack.com/archives/C041MSQM7NH/p1709575010386679 (internal)

**Comment by twisterdotcom** [comment]
I cannot recreate this: 

https://github.com/Expensify/App/assets/9133401/14379d27-8518-4b36-8c84-e3982489c88b

**Comment by kbecciv** [comment]
@twisterdotcom The reply for failed scanning appears in your video, you are actually reproduced it.
![Screenshot 2024-03-12 at 10 43 30](https://github.com/Expensify/App/assets/93399543/7c24b0bc-9502-4f41-9086-43821abf1e25)

**Comment by twisterdotcom** [comment]
Ah I see, you're saying the main thread says there is a reply from the Expensify user, but there actually isn't?

I tried this again and I can't replicate it now still though:
<img width="1332" alt="image" src="https://github.com/Expensify/App/assets/9133401/1cdae3e6-f728-4cee-8ca9-550e05721a32">
