### ISSUE TITLE
Android-Required label appears when create request even People must tag expenses is disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37645]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+gmcategory2@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace on Old Dot
- "People must tag expenses" option is disabled by Admin
1. As employee navigate to Workspace chat> +> Request money> Manual
2. Add amount> Click Next
3. Take a note of Final confirmation page

## Expected Result:
Since Admin has disable "People must tag expenses" option - Employee should not see Required label on Tag section

## Actual Result:
"Required" label is present on Tag section when Employee create request, even "People must tag expenses" is disabled by admin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/73fb1d75-74a3-49c4-9624-b5ac675bb7dd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by francoisl** [comment]
I'm unable to repro, I'm thinking it might have been a delayed notification being sent to the Android client after you disabled the tag requirement in the workspace on OldDot. The code for that page also hasn't changed in a while.


https://github.com/Expensify/App/assets/2229301/f4d9afc1-8255-408c-884f-51449adb45c2

**Comment by francoisl** [comment]
Can't repro on v1.4.47-6 either, closing for now.
