### ISSUE TITLE
[HOLD for payment 2024-03-13] [HOLD for payment 2024-03-11] IOU - Multilevel Tags Dependent are not displayed correctly in the created IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37658]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4356155
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable tags and upload dependent tags to the policy - File can be found here https://drive.google.com/file/d/1MZ2-8EC7z632cvpZHXch0MHXZMpFgYWS/view?usp=drive_link,
add the employee to the policy. Setup OldDot Collect Policy:
https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0
1. Open https://staging.new.expensify.com/
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a group policy room
8. Click on "Show more"
9. Enter all required fields
10. Complete the IOU request
11. Navigate to the details of the created IOU
12. Click on the Region or State field

## Expected Result:
Multilevel Tags - Dependent must be displayed correctly in the created IOU

## Actual Result:
Multilevel Tags - Dependent are not displayed correctly in the created IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bcd1dec4-b6cd-4a01-91c1-53a374f0f744

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rlinoz** [comment]
It looks like frontend as we seem to have the correct information
<img width="831" alt="Screenshot 2024-03-04 at 11 21 29" src="https://github.com/Expensify/App/assets/5201282/c8c008fa-2060-4dcf-b61c-bb9f357dc504">
<img width="475" alt="Screenshot 2024-03-04 at 11 22 04" src="https://github.com/Expensify/App/assets/5201282/8f2c2354-4d14-4b5f-9ea8-49b631fc359a">

**Comment by getusha** [comment]
@rlinoz could you assign me here for the C+ role?

**Comment by rlinoz** [comment]
[CP validated](https://expensify.slack.com/archives/C9YU7BX5M/p1709582446594889?thread_ts=1709574905.448549&cid=C9YU7BX5M), removing deploy blocker

**Comment by rlinoz** [comment]
Not overdue, Melvin just assigned @abekkala to handle payment.

**Comment by rlinoz** [comment]
I think it should be the full amount, since this wasn't a regression, just a feature in development.

**Comment by abekkala** [comment]
@getusha I'm having a hard time finding your Upwork profile. Can you link it here?

**Comment by getusha** [comment]
@abekkala here https://www.upwork.com/freelancers/~01460cf774c356f209

**Comment by abekkala** [comment]
@getusha [offer ](https://www.upwork.com/nx/wm/offer/101397980)sent!

**Comment by getusha** [comment]
@abekkala accepted.

**Comment by abekkala** [comment]
@getusha payment sent and contract ended - thank you! 🎉
