### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Room - WS is not shown empty on setting collect WS as default.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37656]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4359738
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition: User A in old dot must have a collect workspace
1. Launch app with user A
2. As same user login old dot
3. Set Collect Workspace as default
4. In new dot, tap fab --- start chat
5. Tap room
6. Note the Workspace field

## Expected Result:
The Workspace you are currently filtering by should be shown as the top suggested option when creating a room. If filtering by all, your default workspace should be shown as the top suggested option when creating a room.

## Actual Result:
Workspace is not shown empty on setting personal Workspace as default

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/2b217925-cf18-4da1-b0d0-228c24b7efac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment]
I'm not sure why we'd want the Workspace field to show be blank here on the room creation screen. I'd expect us to show the Collect default workspace in the workspace field which seems to be what is happening - Rigth @lanitochka17 ?

**Comment by MitchExpensify** [comment]
Yeah this is an interesting question @Krishna2323 - Should the workspace you are filtering by in NewDot be shown as the default workspace when creating a room? I think the answer is "yes" and I'll double-check internally that others agree!

**Comment by MitchExpensify** [comment]
Double checking what the team thinks!

**Comment by MitchExpensify** [comment]
Yes! The expected behavior is to show the Workspace you are currently filtering by as the suggested Workspace when creating a room.  Updated the expected behavior: 

## Expected Result:

The Workspace you are currently filtering by should be shown as the top suggested option when creating a room. If filtering by all, your default workspace should be shown as the top suggested option when creating a room.

**Comment by MitchExpensify** [comment]
Waiting for proposals

**Comment by MitchExpensify** [comment]
How did your reviews go @ishpaul777 ?

**Comment by MitchExpensify** [comment]
Done! Lets get this fixed :)

**Comment by MitchExpensify** [comment]
*Payment summary*:

- C: @Krishna2323 $500 Upwork
- C+: @hoangzinh $500 Upwork

**Comment by MitchExpensify** [comment]
Friendly bump on your regression step suggestion @hoangzinh 🙇 

Offers sent for payment on this Job https://www.upwork.com/jobs/~014b390ee1a3dc9cad

**Comment by MitchExpensify** [comment]
paid, thanks @Krishna2323 !

**Comment by MitchExpensify** [comment]
Done!
