### ISSUE TITLE
[PAYMENT DUE APRIL 3RD][$500] Room - Invited user name is not displayed in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4359689
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab-Start chat
3. Tap room
4. Enter all details
5. Tap Create room
6. Tap room header
7. Tap members-Invite
8. Invite an user
9. Go to https://staging.new.expensify.com/home
10. Login as invited user
11. Note the invited room chat report in LHN

## Expected Result:
Invited user name must be displayed in LHN
Xxx:Invited 1 user must be shown

## Actual Result:
Invited user name is not displayed in LHN
Invited 1 user is shown without user name. Xxx(not shown) :Invited 1 user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/aff3cb7f-150b-4c7d-84ec-79db08d580c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da2b85a3cfbedea6</li>
        <li>Upwork Job ID: 1766155759412510720</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abekkala** [comment]
@sobitneupane please review the proposal that has come in

**Comment by sobitneupane** [comment]
Thanks for the proposal @tienifr

[Proposal](https://github.com/Expensify/App/issues/37654#issuecomment-1976266107) from @tienifr looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by tylerkaraszewski** [comment]
@abekkala - can you fix that error above?

**Comment by abekkala** [comment]
I'm ooo until April 08- I'll be taking back any Open issue when I return 
@slafortune handling payment for me

___

### CURRENT STATUS: 
PR (https://github.com/Expensify/App/pull/38391) not deployed to prod - no payment date has been set yet

- Fix: @tienifr [$500, if no regressions] [Offer](https://www.upwork.com/nx/wm/offer/101530480)
- PR Review: @sobitneupane - [$500] Payment made via NEWDOT

**Comment by slafortune** [comment]
@tienifr [$500, if no regressions] Paid ✅ 
PR Review: @sobitneupane - [$500] Payment made via NEWDOT
