### ISSUE TITLE
[$500] Members - In principal a/c, teacher is not shown as member in teacher's unite policy

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37650]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4359744
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-conditions
1. Launch app
2. Login with a new Expensifail account
3. Tap on the FAB button
4. Tap on "Save the World"
5. Tap on "I know a teacher"
6. Enter first and last name
7. Enter a new Expensifail email id
8. Tap Let's do this
9. Navigate back to LHN
10. Tap on the FAB button
11. Tap on "Save the World"
12. Tap on "I am a teacher"
13. Enter all details and account that referred teacher & complete the flow
1. Launch app
2. Login with the principal account
3. Tap on "Teachers Unite! testing policy" workspace chat
4. Tap on the header
Verify there are 3 members, the principal, the teacher and the expensify.org admin

## Expected Result:
Three members, the principal, the teacher and the expensify.org admin must be shown.

## Actual Result:
In principal a/c, teacher is not shown as member in teacher's unite testing policy.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f0b46dd8-a81b-42c4-b971-b5781192d445

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129dc8aad4d3266be</li>
        <li>Upwork Job ID: 1767505430285189120</li>
        <li>Last Price Increase: 2024-03-19</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@laurenreidexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave7-collect-approvers
@RachCHopkins

**Comment by laurenreidexpensify** [comment]
@RachCHopkins adding you to confirm if this wave7 related - feel free to unassign once you've review thanks

**Comment by RachCHopkins** [comment]
@kbecciv can you please include the link to the workspace? As an admin for the TU workspace (volunteer@expensify.org) I'd like to see what it looks like from my end. We've had a few Teachers end up with only themselves and volunteer as the members, it would be great to compare and see if it's a bug.

**Comment by kbecciv** [comment]
@RachCHopkins Checking

**Comment by kbecciv** [comment]
Link  https://staging.new.expensify.com/r/5301170024886769

**Comment by RachCHopkins** [comment]
Weird, I don't see it at all. @kbecciv Can you please message volunteer@expensify.org in the chat?

**Comment by RachCHopkins** [comment]
I'm wondering if it's this one:
![image](https://github.com/Expensify/App/assets/32854888/dfbe19a7-9704-4a06-bd7d-02ef09a643e7)

In which case I see all 3 Members.

**Comment by kbecciv** [comment]
Seem reproducible in tester side, credential - [applausetester+dain1@applause.expensifail.com](mailto:applausetester+dain1@applause.expensifail.com)
![Screenshot_2024-03-06-22-35-09-047_com expensify chat (1)](https://github.com/Expensify/App/assets/93399543/67ce07ee-b6ab-478a-80bc-0e951a2e20e6)

**Comment by laurenreidexpensify** [comment]
@RachCHopkins are you good for us to move forward with this as a bug? Thanks

**Comment by RachCHopkins** [comment]
Sorry I just finally got https://staging.new.expensify.com/r/5301170024886769 to load. If it is a bug it would be good to fix it. Up til now each time we have seen this, we've assumed it's user error.

**Comment by s77rt** [comment]
Not overdue. Still looking for proposals

**Comment by s77rt** [comment]
No proposals yet

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by laurenreidexpensify** [comment]
Asking internally here https://expensify.slack.com/archives/C01SKUP7QR0/p1711031392680509 about whether we want to fix this

**Comment by laurenreidexpensify** [comment]
After review, this doesn't seem to be preventing anyone from submitting or sharing reports, so am going to close.
