### ISSUE TITLE
"Report no longer exists" error appears when completing a task by a assignee who is not shared in the parent of the task

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37665]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneeth-lath
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709324908936299

## Action Performed:

1. Create a task
2. In the "share somewhere" option, share it to a room
3. In the "assignee" option, assign someone that isn't in that room
4. As the assignee, attempt to complete the task

## Expected Result:
Able to complete task

## Actual Result:
if a task assignee who is not shared on the parent of the task attempts to complete the task, they get a "Report no longer exists" error when attempting to complete it. 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/962589ac-7afa-4a2d-95c9-956f7aa7cfbe

![Screen Shot 2024-03-03 at 7 18 26 PM](https://github.com/Expensify/App/assets/38435837/dcd437be-c60e-49ba-a00f-024a1b5e3010)

![image-2024-03-01 20_27_00 306](https://github.com/Expensify/App/assets/38435837/095f21fe-88aa-4a35-a439-d7fb3d1c26a3)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dragnoir** [comment]
This is a backend issue, when the assignee attempt to complete the task, this is what the BR reply when function `completeTask` runs

![image](https://github.com/Expensify/App/assets/12425932/97d8e766-6234-45df-9e2c-3bfb9952282e)

**Comment by m-natarajan** [comment]
This is a dupe of #36874. Closing this one.
