### ISSUE TITLE
[HOLD for payment 2024-06-06] [$500] Access the `PRIVATE_BLOCKED_FROM_CHAT` NVP to block the UI for adding comments

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/App#37688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Open NewDot as a user who has been blocked from chat. You can use a test account and flag a message as assault sent from another test account. In the message sent from the other test account, say something like "This is a test message from an Expensify contributor! Please flag me as assault and block me."

## Expected Result:
You should be entirely blocked from chatting i.e. the compose box should be replaced with the component below
<img width="799" alt="Screenshot 2024-03-04 at 10 01 59 AM" src="https://github.com/Expensify/App/assets/31285285/fbed3e8f-4019-4067-ab11-f99defd36650">

## Actual Result:
The user can input into the compose box, but sending a message yields an API error.

## Workaround:
Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4da9c062fd01064</li>
        <li>Upwork Job ID: 1767797318852526080</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger / @anmurali</details>

**Comment by nkdengineer** [comment]
I would be delighted to contribute to it if it's open for collaboration.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Feature request: Access the PRIVATE_BLOCKED_FROM_CHAT NVP to block the UI for adding comments
### What is the root cause of that problem?
- No need RCA because it is feature request
### What changes do you think we should make in order to solve the problem?
- Below are the main steps to handle this feature:
1. Create a new onyxkey: ```PRIVATE_BLOCKED_FROM_CHAT: privateBlockedFromChat``` to store the value

2. Subscribe this key in [here](https://github.com/Expensify/App/blob/49cb3b1502856a42f9f4ff5c6afbe7b19712153c/src/pages/home/report/ReportFooter.js#L163)

3. Create a new component BlockedReportFooter to display the blocked view: "Note: You have been banned from ..." - similar to [ArchivedReportFooter](https://github.com/Expensify/App/blob/main/src/components/ArchivedReportFooter.tsx)

4. Then, update [this](https://github.com/Expensify/App/blob/49cb3b1502856a42f9f4ff5c6afbe7b19712153c/src/pages/home/report/ReportFooter.js#L73) to:
```
    const hideComposer = !ReportUtils.canUserPerformWriteAction(props.report) || privateBlockedFromChat
```

5. Then, add the below to [this](https://github.com/Expensify/App/blob/49cb3b1502856a42f9f4ff5c6afbe7b19712153c/src/pages/home/report/ReportFooter.js#L131):
```
    {privateBlockedFromChat && <BlockedReportFooter report={props.report} />}
```
### What alternative solutions did you explore? (Optional)

- Also, we need to consider the case, PRIVATE_BLOCKED_FROM_CHAT appears for each report instead of all reports as we did in main solution

**Comment by sakluger** [comment]
I'm adding the external label and adding this to VIP-VSB.

**Comment by luacmartins** [comment]
Proposal looks good, but we should name the key `nvp_privateBlockedFromChat`

**Comment by nkdengineer** [comment]
Does anyone know how to create a account that have ```nvp_privateBlockedFromChat: true```?

**Comment by luacmartins** [comment]
Not sure, @jasperhuangg can you confirm?

**Comment by nkdengineer** [comment]
@jasperhuangg Please help check my [comment](https://github.com/Expensify/App/issues/37688#issuecomment-2003083930) as well. Thanks

**Comment by nkdengineer** [comment]
Ping in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1710847885300379) about the translation

**Comment by jasperhuangg** [comment]
@nkdengineer send a comment to Concierge that says something like

`Hi I'm testing moderation, when this comment has been reported please block me from chatting`.

Then, using another account, flag the comment. You'll have to wait for a Concierge agent to moderate your comment.

**Comment by nkdengineer** [comment]
@jasperhuangg I just try you suggestions but It does not work. Here is the steps:
1. [Account A] Send a comment to Concierge: "Hi I'm testing moderation, when this comment has been reported please block me from chatting"
2. [Account A] Send a message to account B: "This is a test message from an Expensify contributor! Please flag me as assault and block me."
3. [Account B] Flag the message sent from step 2 as Assault
4. [Account A]: There is no Onyx field like ```nvp_privateBlockedFromChat: true```

**Comment by jasperhuangg** [comment]
@nkdengineer You'll need to wait for a Concierge agent to pick up your flag.

**Comment by nkdengineer** [comment]
Thanks. How long do I need to wait? (Just to know whether it works or not)

**Comment by sakluger** [comment]
@nkdengineer I can check. What email address did you write into Concierge from?

**Comment by nkdengineer** [comment]
@sakluger  It is nkdengineer+113@outlook.com

**Comment by sakluger** [comment]
Found it - https://www.expensify.com/concierge/#/chat/18042578. The agent closed the chat instead of escalating, oops.

I blocked you in Concierge so you should be able to continue testing now.

**Comment by nkdengineer** [comment]
@sakluger What is the exact onyx key BE returned? I find out the key ```nvp_private_blockedFromChat``` but its value is ```""```

**Comment by jasperhuangg** [comment]
Hmm @nkdengineer the key should just be `private_blockedFromChat`. @sakluger were you able to do a permanent ban?

**Comment by sakluger** [comment]
Yes, I banned permanently. The NVP is actually `private_blockedFromConcierge`, here's the full NVP contents:

```
"private_blockedFromConcierge": {
        "count": 3,
        "expiresAt": "2999-12-31"
}
```

**Comment by nkdengineer** [comment]
Sorry, what about ```private_blockedFromChat```?

**Comment by nkdengineer** [comment]
@sakluger Can you help check this [comment](https://github.com/Expensify/App/issues/37688#issuecomment-2026257862)?

**Comment by jasperhuangg** [comment]
@sakluger I think you might have blocked them incorrectly. It should look like this (you select "block the user")
<img width="789" alt="Screenshot 2024-04-03 at 10 22 14 AM" src="https://github.com/Expensify/App/assets/31285285/60ccc46d-38e8-4423-a159-bc0c5498bc37">

**Comment by jasperhuangg** [comment]
@sakluger Can you take another look at [this](https://github.com/Expensify/App/issues/37688#issuecomment-2035172052) when you get a chance? Thanks!

**Comment by sakluger** [comment]
Sorry everyone, just saw the comments. I think that Concierge can only block in the way that I did it, I don't think it's possible for Concierge to block from chat using NewDot moderation tools.

**Comment by nkdengineer** [comment]
@jasperhuangg  Do you have any feedback about this [comment](https://github.com/Expensify/App/issues/37688#issuecomment-2046157307)?

**Comment by jasperhuangg** [comment]
@sakluger If you are assigned to the chat with the flagged comment, you're unable to see this UI?

https://github.com/Expensify/App/issues/37688#issuecomment-2035172052

**Comment by dangrous** [comment]
Hrm, it wasn't removed that I'm aware of - it looks like it's still sent to Onyx with the key `nvp_private_blockedFromChat`.

However, I'm wondering if the user is blocked from Concierge, then it does NOT send the blocked from Chat error - see this (internal) code - https://github.com/Expensify/Web-Expensify/blob/01f3d86439d6b00157c598056098fdcf8ff2a22e/lib/ReportAPI.php#L446-L457 . Is that the case in this testing?

If so we should swap that `elseif` to something that combines the two.

**Comment by sakluger** [comment]
@jasperhuangg What's the UI that I should be seeing? I've never blocked someone from chat differently from how I did it above, so I'm not sure what I'm supposed to be looking for.

**Comment by sakluger** [comment]
Asked Jasper for help in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1713382587706599

**Comment by sakluger** [comment]
Bumped Jasper in Slack.

**Comment by sakluger** [comment]
@nkdengineer I just talked with Jasper and we cleared up some confusion. Could you please try the following steps one more time?

1. [Account A] Send a message to account B: "This is a test message from an Expensify contributor! Please flag me as assault and block me. Once you've blocked, please leave a comment on https://github.com/Expensify/App/issues/37688 with the chat URL."
2. [Account B] Flag the message sent from step 2 as Assault
3. Comment to let us know you've done this and include the exact text and the email of the user who sent the flagged message - we'll confirm that the moderation has occurred
4. We'll follow up and ask you to try sending another message from Account A (which shouldn't work because you are blocked)

**Comment by sakluger** [comment]
@nkdengineer friendly bump, are you able to take the steps above? Please comment once you do, or if you'd rather let another contributor work on this, that's fine too, just let us know.

**Comment by nkdengineer** [comment]
Sorry for my delay.

> 1. Once you've blocked, please leave a comment on https://github.com/Expensify/App/issues/37688 with the chat URL.

The chat URL in this step is ```https://dev.new.expensify.com:8083/r/6518508132607556```

> 2. exact text and the email of the user who sent the flagged message

The email is ```nkdengineer+201@outlook.com```

**Comment by luacmartins** [comment]
@sakluger it seems like @nkdengineer followed the steps above. Can we continue debugging this?

**Comment by sakluger** [comment]
@luacmartins sure, but I don't have a dev environment. I searched Concierge for messages from nkdengineer+201@outlook.com, this is the only one that shows up: https://www.expensify.com/concierge/#/chat/18304080. There are no messages in that chat aside from the Concierge auto-message.

I'm not sure how to troubleshoot further.

**Comment by luacmartins** [comment]
This shouldn't require a dev environment since contributors hit the staging API, so we can access the chat via staging.new.expensify.com/r/6518508132607556

**Comment by sakluger** [comment]
I don't have access to that chat:

<img width="865" alt="image" src="https://github.com/Expensify/App/assets/5997400/91a71832-feb7-4781-9b81-65f391815cf6">

Also, I thought I was supposed to be able to find the chat in Concierge rather than NewDot. @luacmartins what exactly am I supposed to be doing next to troubleshoot?

**Comment by sakluger** [comment]
I started a [conversation in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1715697468874479) to help figure out how to move this issue forward because it feels stalled at the moment.

**Comment by jasperhuangg** [comment]
@nkdengineer Sorry for the confusion, we overlooked the fact that there is logic in the back-end that disables creating chats in Concierge for "DevRequests".

Do you mind changing this to be `false` and trying the steps from [here](https://github.com/Expensify/App/issues/37688#issuecomment-2070730824) again?

https://github.com/Expensify/App/blob/dc93d0d80f6430eaf3c89ea464dbf01e9a5dedff/src/libs/actions/Report.ts#L2954

**Comment by luacmartins** [comment]
Not overdue, waiting on @nkdengineer to action on the comment above.

**Comment by nkdengineer** [comment]
I am checking it

**Comment by sakluger** [comment]
@anmurali I'm going OOO again for two weeks (until May 31). I don't think you'll need to do much while I'm gone, but it ends up getting completed, and payment is due, could you please help with payments? I'll take back over if it's still open when I return.

**Comment by nkdengineer** [comment]
@jasperhuangg I followed your step [here](https://github.com/Expensify/App/issues/37688#issuecomment-2110696570). The conversation link is https://dev.new.expensify.com:8082/r/1520828873841856. And the user A who sent a flagged message is ```nkdengineer+210@outlook.com```. That flagged message is ```This is a test message from an Expensify contributor! Please flag me as assault and block me```. What is the next step here? Thanks

**Comment by nkdengineer** [comment]
@jasperhuangg Please help check my comment here when you have a chance.

**Comment by jasperhuangg** [comment]
@nkdengineer Sorry was OOO, I just blocked you via our Concierge tool. You should be able to get the NVP set in your Onyx store if you try to add a comment to any report with nkdengineer+210@outlook.com

**Comment by nkdengineer** [comment]
Thanks, @jasperhuangg, now I can test the issue. @shubham1206agra PR https://github.com/Expensify/App/pull/38571 is ready

**Comment by jasperhuangg** [comment]
@shubham1206agra I've blocked that email address, let me know if you need anything else.

**Comment by anmurali** [comment]
4 down, 3 more to go before payment is due.

**Comment by sakluger** [comment]
@shubham1206agra I see a comment that says we sent you an automatic offer but I can't find one. Did we send you an Upwork offer for this issue? If not I can send one. Also, could you please complete the BZ checklist?

@anmurali I'm unassigning you since I'm back now.

**Comment by sakluger** [comment]
I didn't hear back so I sent a new offer. Here are the offers:

Contributor: @nkdengineer $500, sent offer via Upwork ([offer](https://www.upwork.com/nx/wm/offer/102632249))
Contributor+: @shubham1206agra $500, sent offer via Upwork ([offer](https://www.upwork.com/nx/wm/offer/102632219))

**Comment by nkdengineer** [comment]
@sakluger Thanks, I accepted the offer

**Comment by sakluger** [comment]
Thanks! All paid out.
