### ISSUE TITLE
Create Mock Up for Displaying Multiple ECards

### ISSUE THREAD

**Issue by grgia** [Expensify/App#37686]
Coming from https://expensify.slack.com/archives/C02MW39LT9N/p1709558687888869

Related to https://github.com/Expensify/App/issues/31771

**Comment by shawnborton** [comment]
I plan to work on this one tomorrow! Apologies, got sidetracked with Money page and Invoice mocks today.

**Comment by grgia** [comment]
Thanks @shawnborton !

**Comment by dubielzyk-expensify** [comment]
I'm a big fan of the first one. While I like the callout for virtual cards I think it's the text label that makes it a tad bit too overwhelming. I think that detail can be pushed to the card detail screen itself. 

If we don't believe the limit is important on the card overview, we could use the badge for the virtual vs physical callout.

Have you changed the pattern here and gone above the title? I thought we normally do it below. Not against it, but just wondering the reasoning or if I'm missing a pattern we have access to.

![CleanShot 2024-03-08 at 16 35 56@2x](https://github.com/Expensify/App/assets/145416827/18d9a129-6e46-4f01-8a56-599647043b09)

**Comment by shawnborton** [comment]
> Have you changed the pattern here and gone above the title?

I guess I was just mirroring what I had from the previous page, but you make a good point about not changing the pattern, so I'm totally down to keep it below the title: 
![CleanShot 2024-03-08 at 08 49 45@2x](https://github.com/Expensify/App/assets/2319350/58e10345-d2ae-42b8-909f-286cf0a7c739)

**Comment by shawnborton** [comment]
Then to your point about moving the "virtual card" label inside of the card view - I like that idea too:
![CleanShot 2024-03-08 at 08 53 43@2x](https://github.com/Expensify/App/assets/2319350/150e995e-6509-4d30-a660-9a4b6d31fc36)

**Comment by shawnborton** [comment]
Oh that's a solid idea too, nice - I like it! 

So maybe let's hear from Kevin and Georgia on how important some of these labels/badges are and we can decide from there, but feeling pretty good about the options we have for how to display them at this point.

**Comment by grgia** [comment]
![image](https://github.com/Expensify/App/assets/38015950/d9ce70a4-93bd-4e28-bc9e-d60edc392577)

Above slack link was incorrect, see here https://expensify.slack.com/archives/C036QM0SLJK/p1710760620755409?thread_ts=1710155978.612219&cid=C036QM0SLJK

**Comment by grgia** [comment]
This is basically done, but I'm going to leave this issue up temporarily until I create the issue implementing this today

**Comment by shawnborton** [comment]
Not overdue, we're all settled on the design and Georgia will implement.

**Comment by grgia** [comment]
Closing! We'll implement here https://github.com/Expensify/App/issues/38468
