### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Internal QA checklist not working for external PRs

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#37691]
### Problem
The deploy checklist has a section for InternalQA and is meant to tag Expensify engineers to complete the QA for each PR. This failed for [this checklist](https://github.com/Expensify/App/issues/37578) and [this PR](https://github.com/Expensify/App/pull/35413).

### Solution
Fix it! make sure that people responsible for internal QA are correctly tagged _and_ assigned to the issue (right now I don't think they're assigned, just tagged)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149b7b8e3e44c57bd</li>
        <li>Upwork Job ID: 1764724130794770432</li>
        <li>Last Price Increase: 2024-03-04</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment]
in a hurry so apologies for the low-quality issue. Going to make this external, and anyone proposing a fix should note that automated tests will be a hard requirement for this issue.

**Comment by roryabraham** [comment]
sounds good @rayane-djouah 👍🏼 

> We should use pr.merged_by.login instead of pr.assignees.login for creating the internalQAPRMap [here](https://github.com/Expensify/App/blob/01025a91c72132b666e712eff3606326704c3e09/.github/libs/GithubUtils.js#L256-L264). and change the naming [here](https://github.com/Expensify/App/blob/01025a91c72132b666e712eff3606326704c3e09/.github/libs/GithubUtils.js#L295-L301).

I think that's fine. It's better than using assignee as the person who merged the PR will always be an internal engineer. we don't need to use both, that's just more complicated.

**Comment by roryabraham** [comment]
@hoangzinh I'm actually going to opt-out of C+ services for this GitHub Actions improvement.

**Comment by roryabraham** [comment]
@slafortune I don't seem to be able to access the [offer link for @hoangzinh](https://github.com/Expensify/App/issues/37691#issuecomment-1977726341). Can you please retract that offer as we don't need C+ here?

**Comment by roryabraham** [comment]
@rayane-djouah any estimate on when the PR will be ready for review? this isn't particularly urgent, so I'm going to change the priority to weekly

**Comment by roryabraham** [comment]
It "deploys" immediately in this case, but let's give it a week to monitor for regressions nonetheless

**Comment by roryabraham** [comment]
PR reverted. @rayane-djouah we'll need a redo

**Comment by roryabraham** [comment]
No BZ checklists yet, not awaiting payment, not on HOLD. The PR was revert

**Comment by slafortune** [comment]
Paid
