### ISSUE TITLE
WS-There is a noticeable lag when typing in search field in invite members page for HT

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/36681

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nathanmulugetatesting@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Precondition: Sign in with a High traffic account
1. Go to WS invite members page
2. Click on search bar
3. Type something

## Expected Result:
There should be no lag that is very noticeable

## Actual Result:
There is a noticeable lag when typing the first letters in the search filed and when typing fast and using backspace to delete letters

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b8836d32-9046-4f12-a6d7-32d9114d9549

https://github.com/Expensify/App/assets/115492554/25dc7094-5bb7-4e12-a30d-9214d7943a62

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by alexpensify** [comment]
Noted, I will add this to my test list.

**Comment by alexpensify** [comment]
Still on my testing list, I'll review it soon.

**Comment by alexpensify** [comment]
No update yet, I need to test.

**Comment by alexpensify** [comment]
I tested today and am unable to replicate the same experience. I think the lag might have been temporary and no issues today to load the emails from the Invite list today.
