### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Chat - PDF is displayed closer to the top

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37724]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** vdargentotest+mweb030424@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Pre-requisite: the user must be logged in.

1. Go to any chat.
2. Send the attached PDF.
3. Tap on the PDF preview to open it.
4. Verify it is displayed closer to the top.

## Expected Result:
The PDF should be displayed in the middle of the viewer section.

## Actual Result:
The PDF is displayed closer to the top.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Bug6402389_1709617684018!pdf.pdf](https://github.com/Expensify/App/files/14493626/Bug6402389_1709617684018.pdf.pdf)
![Bug6402389_1709617667265!IMG_3255](https://github.com/Expensify/App/assets/115492554/6abff785-ac57-44e6-bf4d-494846a60608)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ce46bd1a9c35b0c</li>
        <li>Upwork Job ID: 1767225873928306688</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by sakluger** [comment]
@Expensify/design this is a bug, right? I assume we want images to be vertically center-aligned.

**Comment by shawnborton** [comment]
Hmm I'm not entirely sure... it's a PDF, and I think I would expect viewing a document to be aligned to the top. Curious what others think though.

**Comment by dannymcclain** [comment]
I'm honestly not sure about this one. It looks like if a PDF will fit in the viewport, we center it. If it's too long, we align it to the top and let you scroll to see the whole thing?

**Comment by shawnborton** [comment]
Yeah that's fair... this is also a super tricky PDF because the PDF itself is cropped:
![CleanShot 2024-03-05 at 11 33 57@2x](https://github.com/Expensify/App/assets/2319350/a3b069b0-f279-45ab-894d-b679c09782e6)

**Comment by dannymcclain** [comment]
Here's a screenshot of that attachment from the app. I feel like this is how we'd expect it to display. 

![Screenshot 2024-03-05 at 10 37 27 AM](https://github.com/Expensify/App/assets/7516624/84de88a5-e8f0-423b-aeae-3036a430230d)

**Comment by shawnborton** [comment]
Yeah, that makes sense to me. So it seems like this is just an mWeb thing?

**Comment by dannymcclain** [comment]
Yeah that's what it looks like to me.

**Comment by sakluger** [comment]
@shawnborton @dannymcclain, just to confirm, are you saying that this is an mWeb bug, or that it's expected mWeb behavior?

**Comment by shawnborton** [comment]
Yup, seems like an mWeb bug.

**Comment by sakluger** [comment]
Thanks Shawn! I'll mark as external and add to #vip-vsb. I'm going to set the price at $250 since this is just an alignment issue on a single platform.

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
PDF is aligned to the top in mWeb
### What is the root cause of that problem?
 the `VariableSizeList` component that is provided by the `react-window` library is used in web platforms to display the PDF. 
this component always returns the top padding (`style.top`) as zero here: 

https://github.com/Expensify/App/blob/26ecf688e74f434abcca1973d438872907a61f72/src/components/PDFView/WebPDFPageRenderer.js#L29-L40
### What changes do you think we should make in order to solve the problem?


we need to use the parent container height and the pdf height to decide the top padding because the default offset provided by the library is `0`

to acheive that: 

1. we need to add the `containerHeight` to the `itemData` prop in the `List` component:
https://github.com/Expensify/App/blob/2148716030796eb629bbc4bce9b6d7c6d42b49f7/src/components/PDFView/WebPDFDocument.js#L117
2. then we can access this in the `WebPDFPageRenderer` by extracting it from the [data](https://github.com/Expensify/App/blob/26ecf688e74f434abcca1973d438872907a61f72/src/components/PDFView/WebPDFPageRenderer.js#L31) component:  
```js
        const {pageWidth, calculatePageHeight, getDevicePixelRatio, estimatedItemSize, containerHeight} = data;
```
3. then we modify the [top padding](https://github.com/Expensify/App/blob/26ecf688e74f434abcca1973d438872907a61f72/src/components/PDFView/WebPDFPageRenderer.js#L35-L37) to:
```js
   const topOffset = parseFloat((containerHeight - style.height) / 2);
        return (
            <View style={{...style, top: `${parseFloat(topOffset) + PDFViewConstants.PAGE_BORDER}px`}}>
```

another solution would be to use the `style.top` if its not zero like this:

```js
        const topOffset = parseFloat(style.top || (containerHeight - style.height) / 2);
```

**Comment by sakluger** [comment]
@mollfpr what do you think of the above proposal?

**Comment by mollfpr** [comment]
@abzokhattab Have you checked the result on the multiple pages pdf?

**Comment by mollfpr** [comment]
The [proposal](https://github.com/Expensify/App/issues/37724#issuecomment-1989219526) from @abzokhattab looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment]
Hmm before we hire @abzokhattab can someone please help confirm if the bug is still reproducible? 😅

**Comment by Beamanator** [comment]
Weird, I don't see this happening with normal PDFs, maybe it has to be very specifically weird shaped PDFs or something?

**Comment by sakluger** [comment]
I retested (which was kind of annoying to do - who uploads PDFs from mobile web? 😩) and verified that the bug is still reproducible with single-page PDFs.

@Beamanator I'm going to assign @abzokhattab since I reproduced the issue.

**Comment by Beamanator** [comment]
Looks like payment is due here, yeah? No regressions i believe?

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @abzokhattab $250, paid via Upwork
Contributor+: @mollfpr $250, please request on Newdot

**Comment by sakluger** [comment]
@mollfpr could you also please complete the BZ checklist?

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Go to any chat.
2. Upload two single-page PDFs: one with a long page and another with a short page.
3. Click on the PDF preview to open each document.
4. Ensure that both PDFs are centered properly. Check that the longer PDF displays correctly without the top padding being chopped off.
5. 👍 or 👎

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr

**Comment by sakluger** [comment]
Thanks!
