### ISSUE TITLE
[Hold for #305196] Login - Unable to login with account tester+domaincard@applausecard.expensifail.com

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37728]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** tester+domaincard@applausecard.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Open Expensify App or go to staging.new.expensify.com
2. Login with account [tester+domaincard@applausecard.expensifail.com](mailto:tester+domaincard@applausecard.expensifail.com)

## Expected Result:
User successfully login with account [tester+domaincard@applausecard.expensifail.com](mailto:tester+domaincard@applausecard.expensifail.com)

## Actual Result:
Only the skeleton page is shown after login with account [tester+domaincard@applausecard.expensifail.com](mailto:tester+domaincard@applausecard.expensifail.com)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e72ac350-e561-45e1-bafb-720f0eb139ad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110c94fb7f8a19b56</li>
        <li>Upwork Job ID: 1769770827931406336</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by sonialiap** [comment]
@izarutskaya is this still affecting you? Is it affecting all @applausecard.expensifail.com accounts? I've been able to log into my @expensify.com and @gmail.com accounts without issue today

**Comment by kbecciv** [comment]
@sonialiap It's only affecting one account [tester+domaincard@applausecard.expensifail.com](mailto:tester+domaincard@applausecard.expensifail.com), I checked another one and it works fine!

https://github.com/Expensify/App/assets/93399543/1441ea0e-f4a2-459d-b9e5-7898e93ed5e8

**Comment by sonialiap** [comment]
Thanks for the confirmation!

**Comment by sonialiap** [comment]
@kbecciv how important is this account? Can the applause team use another account instead of this one?

**Comment by kbecciv** [comment]
We have two TCs in TR for testing with tester+[domaincard@applausecard.expensifail.com](mailto:domaincard@applausecard.expensifail.com) https://expensify.testrail.io/index.php?/tests/view/4381180 and https://expensify.testrail.io/index.php?/tests/view/4381265

**Comment by sonialiap** [comment]
Sounds like you need this account, moving to internal

**Comment by sonialiap** [comment]
Posted in engineering to see if we can get a volunteer https://expensify.slack.com/archives/C03SSAQ7P/p1711477606930779

**Comment by sonialiap** [comment]
Adding the hot pick label

**Comment by trjExpensify** [comment]
What's special about this account? Does it have a shit ton of data/chats or something? 

P.S moving to the `Hot picks` section in the project for visibility as well.

**Comment by sonialiap** [comment]
@kbecciv can you help answer Tom's [question](https://github.com/Expensify/App/issues/37728#issuecomment-2035348026)? 

>What's special about this account? Does it have a shit ton of data/chats or something?

**Comment by kbecciv** [comment]
@sonialiap This account was created specifically for a few TCs - https://github.com/Expensify/App/issues/37728#issuecomment-1997631676

**Comment by flodnv** [comment]
OpenApp request: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2287160b85da2e3352-MIA%22)+AND+timestamp:[2024-04-08T22:30:27.223Z+TO+2024-04-09T00:30:27.223Z]&index=logs_expensify-027726

`Got 5069 chat reports`, probably related to needing pagination (cc @marcaaron)

Tail end of request logs (DESC order): https://www.expensify.com/_devportal/tools/logSearch/#sort=desc&size=1000&query=request_id%3A%2287160b85da2e3352-MIA%22%20AND%20timestamp%3A%5B2024-04-08T00%3A00%20TO%202024-04-11T23%3A59%5D

Not sure why it seems like the request dies out of nowhere after ~ 1 minute. 

Anyways, I'm not sure if there's much to look into here until we implement pagination... thoughts @trjExpensify ?

**Comment by flodnv** [comment]
Maybe we should merge https://github.com/Expensify/Auth/pull/10390/files then 😄

**Comment by marcaaron** [comment]
Maybe. It would mainly help identify whether we are doing dumb things faster than it will take to ask someone with ring1 to run the query for us and analyze the returned data (which also has stuff that should be redacted).

I added some way to do this via supportal [here](https://github.com/Expensify/Web-Expensify/blob/8620e7a46a79b8c07022a6a2285dc6f85358c12e/_support/getChats.php#L18-L19). But you still have to analyze what gets returned and if it's 5000 chats the browser tab runs out of memory.

**Comment by sonialiap** [comment]
@marcaaron do we have a tracking issue for pagination that I can keep an eye on for this issue here? I tried searching but didn't find something that is clearly related to it

**Comment by marcaaron** [comment]
https://github.com/Expensify/Expensify/issues/305196

**Comment by sonialiap** [comment]
on hold for https://github.com/Expensify/Expensify/issues/305196

**Comment by sonialiap** [comment]
on hold for https://github.com/Expensify/Expensify/issues/305196
I expect that issue won't be resolved soon so I'm, putting this on weekly

**Comment by sonialiap** [comment]
still on hold for https://github.com/Expensify/Expensify/issues/305196

**Comment by sonialiap** [comment]
Same ☝️

**Comment by sonialiap** [comment]
still on hold for https://github.com/Expensify/Expensify/issues/305196

**Comment by sonialiap** [comment]
still on hold for https://github.com/Expensify/Expensify/issues/305196

**Comment by sonialiap** [comment]
still on hold for https://github.com/Expensify/Expensify/issues/305196. The high level design doc is almost ready to be set for review so this hold will probably take a while

**Comment by sonialiap** [comment]
still on hold for https://github.com/Expensify/Expensify/issues/305196

**Comment by trjExpensify** [comment]
Going to move this to newdot-quality where pagination is.

**Comment by flodnv** [comment]
@marcaaron has improved OpenApp recently, can we get a retest of this please?

**Comment by sonialiap** [comment]
asking for a retest https://expensify.slack.com/archives/C9YU7BX5M/p1723476703912689

**Comment by kavimuru** [comment]
Not reproducible anymore

https://github.com/user-attachments/assets/ea082555-0ce2-41db-ad18-ad5ea1363ec0

**Comment by sonialiap** [comment]
Thanks Kavi! Closing this out

**Comment by flodnv** [comment]
👏 @marcaaron ❤️
