### ISSUE TITLE
BA - User can continue the flow with wrong account number, then error appears on other page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37730]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Not able to test on production
**Email or phone of affected tester (no customers):** applausetestervd_mweb030424@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Pre-requisite: the user must be logged in and have created a Workspace.

1. Go to Workspace > Bank account.
2. Tap on Connect with Plaid.
3. Select Chase bank and use the testing credentials.
4. Select the account ending with 1111.
5. Enter "011401533" as the Routing number.
6. Enter "1111" as Account number.
7. Verify you can continue the add BA flow.
8. Reach the double check Company information page.
9. Tap on "Confirm".
10. Verify you see an error is displayed.
11. Tap on "fix the errors".
12. Verify nothing happens.

## Expected Result:
The user should not be able to continue the flow if the account number entered is incomplete or wrong.

## Actual Result:
The user is able to continue the flow with incomplete account number, then an error appears on the double check Company information page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6229d4e9-3fcf-4782-910b-82848fa95098

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e89faf072ebd1655</li>
        <li>Upwork Job ID: 1765013045602160640</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@cristipaval I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by nkuoch** [comment]
I'll fix it myself

**Comment by cristipaval** [comment]
This is reproducible in production as well. Tested with 1.4.46-2

**Comment by cristipaval** [comment]
Thanks @nkuoch!

**Comment by nkuoch** [comment]
This will be a BE PR, no need for contributor plus

**Comment by trjExpensify** [comment]
@kadiealexander as a bug that doesn't block the release, I'm moving this to `Polish`. That said, is the PR done here?

**Comment by kadiealexander** [comment]
Yeah it is, weird this didn't close. Closing as complete, thanks @trjExpensify!
