### ISSUE TITLE
Chat - Quote in live preview isn't replaced by quote sign but is supplemented by this sign

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37735]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Open iOS or Android App
2. Login with any account
3. Open any chat
4. Type quote " > " and any text after it

## Expected Result:
Quote " > " in live preview replaced by quote sign

## Actual Result:
Quote " > " in live preview isn't replaced by quote sign but is supplemented by this sign

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/45007f31-8f1a-4ba5-866b-cd15885a60ad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by joekaufmanexpensify** [comment]
Looks like this is not a bug. I see this behavior on [the PR](https://github.com/Expensify/App/pull/34292#issuecomment-1921837103)
