### ISSUE TITLE
Search – The created IOU is not visible in the search results

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37741]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4378446
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to a 1:1 conversation
4. Request money to the other user
5. Navigate to search

## Expected Result:
The created IOU is visible in the search results

## Actual Result:
The created IOU is not visible in the search results

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d42388b6-54dd-43c4-92f2-4a9d57f574cd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by puneetlath** [comment]
Hmm. I'm not sure this is a bug. Can you find the report if you search for it @kbecciv?

**Comment by kbecciv** [comment]
@puneetlath Do you think the report should be displayed first in search, as the tester can currently see it, but it's located below.

https://github.com/Expensify/App/assets/93399543/d8330fc6-bbae-4a6d-80e6-df07a8e864cb

**Comment by puneetlath** [comment]
I think it's fine as-is. If they are able to search for it and find it, then I think we're good. Thanks for checking!
