### ISSUE TITLE
Members - 'Make admin' option is not displayed before refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37748]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a workspace if you don't have any
2. Invite a user
3. Before refreshing the members page, select the user
4. Click on 'Selected dropdown' on top-right corner of the page
5. Refresh the page > select the user > click on 'Selected dropdown'

## Expected Result:
'Make admin' option should be displayed

## Actual Result:
'Make admin' option is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e3762750-8a7a-418a-bebc-386c2f83db55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave8-collect-admins
@zanyrenney

**Comment by danieldoglas** [comment]
Agreed this is not external, since it is already known.

**Comment by luacmartins** [comment]
We can demote this, we're still developing this feature.

**Comment by danieldoglas** [comment]
The change that implements this has reached staging and has its own testing steps with original issue. Closing this one.
