### ISSUE TITLE
[HOLD for payment 2024-03-14] Video - Unable to expand video from video preview modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Notes: Step 4 is currently blocked by a crash that is happening when executing step 4
1. Send a video
2. Click on 'Play' icon
3. Click on expand icon on top-left corner of the video
4. Click on full screen icon when video opens with modal

## Expected Result:
Video should be expanded to full screen

## Actual Result:
Video expands to full screen and collapsed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f5c35aba-fa00-4f1c-bb52-8274d9393896

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp 
CC @quinthar

**Comment by lanitochka17** [comment]
@pecanoro  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by pecanoro** [comment]
Hmm, this error could be the cause:

![image](https://github.com/Expensify/App/assets/6474442/64f8dae8-21f4-49ba-8572-c8e297d3129b)

**Comment by pecanoro** [comment]
Identified the PR that caused it: https://github.com/Expensify/App/pull/37202

**Comment by lschurr** [comment]
@aimane-chnaif Can you work through the checklist on this one?

**Comment by lschurr** [comment]
All set.
