### ISSUE TITLE
IOU -  Category is not correctly auto-selected if request has the same merchant which was edited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37751]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4378509
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as Employee of a Collect WS
3. Create an IOU with a category and a unique merchant Schoo
4. Edit category in IOU to School
5. Create a second IOU with the same merchant School but without selecting a category

## Expected Result:
Verify the second IOU has the category auto-selected to the same as the first IOUPriority mode page opens

## Actual Result:
Category is not correctly auto-selected in the second IOU if the request has the same merchant which was edited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8a0818e8-810b-4109-a913-7d4bf9119361

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by slafortune** [comment]
I don't understand the steps list @lanitochka17 

- Create an IOU with a category and a unique merchant Schoo
- Edit category in IOU to School
- Create a second IOU with the same merchant School but without selecting a category

Can you please clarify?

**Comment by slafortune** [comment]
Unable to recreate this.  Auto categorization does not occur immediately, it takes some time to learn and is based on the merchant name.
