### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] [Simplified Collect][Members] - admin badge is not grayed out when making user admin in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37757]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a workspace if you don't have any
2. Invite a user
3. Refresh the members page, select the user
4. Apply offline mode
5. Click on 'Selected dropdown' on top-right corner of the page
6. Click on 'Make admin'

## Expected Result:
'Admin' badge or the row should be grayed out to be consistent with offline behaviour

## Actual Result:
'Admin' badge or the row is not grayed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/f9c9f9ac-2da8-4c15-9ea9-e6a4ed2a0932

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7f28a197717f294</li>
        <li>Upwork Job ID: 1765710957346672640</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by grgia** [comment]
Agree not a blocker

**Comment by grgia** [comment]
@luacmartins do you know who worked on the admin button

**Comment by luacmartins** [comment]
Yes, it came from this PR https://github.com/Expensify/App/pull/37199. It seems like we're just missing the pendingAction

**Comment by grgia** [comment]
hey @burczu are you down to take this one as a follow up?

**Comment by burczu** [comment]
@grgia Yes, please assign this issue to me - I'll take care of it. Thanks!

**Comment by burczu** [comment]
Pull request is ready for review.

**Comment by pavlenkoviktor** [comment]
I can solve this issue. Please assign this issue to me.

**Comment by pavlenkoviktor** [comment]
To make an item grayed out when the user is in offline behavior, you can use JavaScript and CSS to add a visual indication that the item is unavailable. Here's an example of how you can achieve this:

Add CSS Styles: Define a CSS class that will be applied to the item when it's offline. This class will be responsible for graying out the item. For example:
 
.offline-item {
  color: gray;
  /* Add any additional styling to visually indicate the item is unavailable */
}

JavaScript Logic: Add JavaScript code to detect the user's online/offline status and apply the CSS class to the desired item. Here's an example using the navigator.onLine property and the classList API:
 
// Select the item you want to gray out
const item = document.getElementById('your-item-id');

// Function to update the item's availability status
function updateItemAvailability() {
  if (navigator.onLine) {
    // User is online, remove the "offline-item" class
    item.classList.remove('offline-item');
  } else {
    // User is offline, add the "offline-item" class
    item.classList.add('offline-item');
  }
}

// Initially update the item's availability based on the user's online/offline status
updateItemAvailability();

// Add an event listener to update the item's availability when the user's online/offline status changes
window.addEventListener('online', updateItemAvailability);
window.addEventListener('offline', updateItemAvailability);
In the above code, replace 'your-item-id' with the actual ID or selector of the item you want to gray out.

Apply the CSS Class: In your HTML markup, ensure that the item has the class you defined (offline-item) initially. This ensures that when the page loads while the user is offline, the item will already be grayed out. For example:
 
<div id="your-item-id" class="offline-item">
  
</div>
With the above code, when the user is offline, the item will have the offline-item class applied, which will visually gray it out. When the user comes back online, the class will be removed, and the item will appear as normal.



How about this solution. Hope this will be helpful for you.

**Comment by pavlenkoviktor** [comment]
Contributor details
Your Expensify account email: pavlenkoviktor44@outlook.com
Upwork Profile Link: upwork.com/freelancers/~010757be5da859689d

**Comment by luacmartins** [comment]
@pavlenkoviktor thanks for the interest, but we already have someone assigned to the issue and a PR in review!

**Comment by pavlenkoviktor** [comment]
How can I complete the "BugZero Checklist"?
________________________________

**Comment by luacmartins** [comment]
Thanks for the bump. I don't think so. This issue is still part of the scope https://github.com/Expensify/App/pull/37199 and within the regression period, as such it should be solved by the original PR author as part of the same bounty.

**Comment by grgia** [comment]
@stephanieelliott I added the bug label to ensure that $500 C+ payment is made to @aimane-chnaif, thank you! 

https://github.com/Expensify/App/issues/37757#issuecomment-1988060642

**Comment by stephanieelliott** [comment]
I sent you the offer in Upwork @aimane-chnaif, please accept when you get a chance! https://www.upwork.com/jobs/~01d7f28a197717f294

**Comment by stephanieelliott** [comment]
All paid
