### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500]  Category - Recent and All sections appear when selected category is invalid with <8 categories

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37766]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4381056
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- The Collect workspace has 8 categories
1. [Employee] Go to workspace chat
2. [Employee] Create two manual requests, with Merchant A and Merchant B
3. [Admin] On Old Dot. disable Merchant A so that now there is less than 8 categories
4. [Employee] Go to the details page of request that has Merchant A
5. [Employee] Click Category

## Expected Result:
Since there is now less than 8 categories, the category list will not show search field, Recent and All sections

## Actual Result:
Although there is less than 8 categories, the category list still shows Recent and All sections
When employee selects another category and reopens the list, the sections are gone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/063db3e3-62d5-4558-a598-f9d17a54ed1e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c18a41a21d81a420</li>
        <li>Upwork Job ID: 1767300069769654272</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by lanitochka17** [comment]
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment]
I'm unable to reproduce this issue on staging. See video below:

https://github.com/Expensify/App/assets/22219519/d4f9fed4-3e00-4d94-b7c4-13fbf8270563

**Comment by johncschuster** [comment]
Applying the `retest-weekly` label so it can be reproduced. If reproduced, please post your reproduction steps and update the OP if they are different. Thank you!

**Comment by kbecciv** [comment]
@luacmartins Can you please review this issue again, QA team is able to reproduce the issue.

https://github.com/Expensify/App/assets/93399543/337091e7-7f29-4a3f-9ba5-fbfeddba498e

**Comment by luacmartins** [comment]
@johncschuster could you please retest this one?

**Comment by johncschuster** [comment]
It's been added to the retest-weekly list and should be tested tomorrow by Applaus

**Comment by luacmartins** [comment]
I just asked because they confirmed they could reproduce it just now - https://github.com/Expensify/App/issues/37766#issuecomment-1997686971

**Comment by johncschuster** [comment]
@luacmartins I'll retest this one this afternoon.

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests.

Although there is less than 8 categories, the category list still shows Recent and All sections
When employee selects another category and reopens the list, the sections are gone

**Comment by johncschuster** [comment]
# Payment Summary:
C+ Review: @allroundexperts - $500 via Manual Requests
Contributor: @Krishna2323 - $500 via Manual Request

**Comment by johncschuster** [comment]
(Leaving open until the [BZ checklist](https://github.com/Expensify/App/issues/37766#issuecomment-2026477988) is complete)

**Comment by johncschuster** [comment]
I changed the amount owed to $500, as this issue was created prior to the effective date of the new payment structure ([announcement](https://expensify.slack.com/archives/C02NK2DQWUX/p1712250884549319))

**Comment by johncschuster** [comment]
Sorry I missed your ping, @Krishna2323! The note above wasn't meant to say you were already paid – it was meant to mean that the method by which you would be paid is through Upwork. I've just issued payment now! 🎉

**Comment by johncschuster** [comment]
@allroundexperts can you complete the [BZ Checklist](https://github.com/Expensify/App/issues/37766#issuecomment-2026477988) above? Thank you!

**Comment by allroundexperts** [comment]
## Checklist

1. https://github.com/Expensify/App/pull/32902
2. https://github.com/Expensify/App/pull/32902/files#r1565810749
3. N/A
4. A regression test would be helpful here. The steps given in the OP look good enough to me.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
