### ISSUE TITLE
[LOW] [Splits] [$500] Thread - Thread name becomes Hidden in LHN after deleting IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37763]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Navigate to any chat
3. Send a message > start a thread
4. Create a money request
5. Delete the created money request
6. Navigate to the LHN

## Expected Result:
The task name is displayed and the avatar of the user who created the thread

## Actual Result:
The thread name becomes "Hidden, and the avatar becomes a default one. When I open the thread, the parent message is missing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7f968ea5-5783-4d1a-a646-52ed1e082a83

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165504c436946dcfa</li>
        <li>Upwork Job ID: 1772681036581515264</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kevinksullivan** [comment]
thinking this is tied to VIP split. checking [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1710541920155759)

**Comment by kevinksullivan** [comment]
Making external to get proposals.

**Comment by mollfpr** [comment]
No proposals

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by kevinksullivan** [comment]
Closing if no loner reproducible.
