### ISSUE TITLE
Search - The group chat member is also listed on the second line of the search results

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37765]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Testing

## Action Performed:
1. Create group chat
2. Go to search and find the created group chat

## Expected Result:
Group chat members are displayed on the first line of the group chat

## Actual Result:
One of the members email can be seen also on second line when see the group chat on Search list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/93458a76-2e9f-4442-b635-e7139c1c8b89

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@muttmuure 
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by muttmuure** [comment]
I'm not sure this is a bug?
