### ISSUE TITLE
[$250] [HOLD for payment 2024-04-25] [Wave Collect][QBO] Implement Import-related screens

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#37777]
Implement pages related to the import configurations for the QuickBooks Online (QBO) connection project.

QBO is a well-known accounting software that Expensify supports integration with. Once the user establishes a connection to QBO, Expensify exports expense reports, also known as money requests, to QBO. This enables expenses, referred to as transactions in QBO terminology, to appear in the accounting software.

Establishing a connection with QBO also enables the user to import some data from the QBO to be used in expense reports. Your task is to implement pages to configure how and what data is imported from QBO to Expensify. Essentially, users should be able to map entities from QBO to corresponding entities in Expensify. Each page allows the user to configure how an entity on QBO is imported to the QBO.

### QBO specific terminologies
_Each term represents an entity on QBO. These entities help classify and add extra information to each financial transaction recorded on QBO._

- [Classes](https://quickbooks.intuit.com/learn-support/en-us/help-article/class-list/get-started-class-tracking-quickbooks-online/L04INPWiy_US_en_US)
- [Customers](https://quickbooks.intuit.com/learn-support/en-us/help-article/manage-customers/add-manage-customers-quickbooks-online/L0M9mMZmd_US_en_US) / [Projects](https://quickbooks.intuit.com/learn-support/en-us/help-article/manage-projects/set-create-projects-quickbooks-online/L9GAdLMyT_US_en_US) 
- [Locations](https://quickbooks.intuit.com/learn-support/en-us/help-article/track-location/set-use-location-tracking/L2raFkEBC_US_en_US)
- [Tax](https://quickbooks.intuit.com/learn-support/en-us/help-article/sales-taxes/set-sales-tax-quickbooks-online/L2uNuHuYS_US_en_US)

### Expensify specific terminologies
_Each term represents an entity on Expensify. These entities help classify and add extra information to each expense reports (i.e. money requests) created on New Expensify._

- [Categories](https://community.expensify.com/discussion/5732/deep-dive-all-about-policy-categories)
- [Tags](https://community.expensify.com/discussion/4708/how-to-set-up-and-add-single-tags)
- [Difference between categories and tags](https://community.expensify.com/discussion/835/what-is-the-difference-between-a-category-and-a-tag)
- [Report Fields](https://community.expensify.com/discussion/4485/how-to-set-up-and-use-report-and-invoice-fields): This term is mentioned in the feature specification. However, at this point, report fields won't be available on New Expensify.

## Product Specifications
Below are the product/feature specifications for each page. Each page represents an entity from QBO and enables the user to configure how it is imported into Expensify.

<details>
<summary>Import Main Page</summary>

<img width="400" alt="Screenshot 2024-03-05 at 10 17 00 AM" src="https://github.com/Expensify/App/assets/98560306/a0cb4efa-ff4e-4987-886d-ec10e6b31770">
<img width="400" alt="Screenshot 2024-03-05 at 10 17 28 AM" src="https://github.com/Expensify/App/assets/98560306/2a7598ce-233f-4ef0-92e7-656d1c59eb11">
<img width="400" alt="Screenshot 2024-03-05 at 10 17 46 AM" src="https://github.com/Expensify/App/assets/98560306/c77b3f55-9e4c-4546-b15a-7340dcc46526">

</details>

<details>
<summary>Chat of Accounts</summary>

<img width="400" alt="Screenshot 2024-03-05 at 9 53 27 AM" src="https://github.com/Expensify/App/assets/98560306/f61128da-db57-4e93-abaf-0a069c915d5d">

</details>

<details>
<summary>Classes</summary>

<img width="400" alt="Screenshot 2024-03-05 at 9 53 39 AM" src="https://github.com/Expensify/App/assets/98560306/ce8b95e6-61c9-458c-9510-79bff3da8802">

</details>

<details>
<summary>Customers / Projects</summary>

<img width="400" alt="Screenshot 2024-03-05 at 9 53 51 AM" src="https://github.com/Expensify/App/assets/98560306/00b13a00-0a66-4934-951a-0c7acafd2317">

</details>

<details>
<summary>Locations</summary>

<img width="400" alt="Screenshot 2024-03-05 at 9 54 22 AM" src="https://github.com/Expensify/App/assets/98560306/4c39fcbb-66ed-4390-b429-b7f6ae9064dc">
<img width="400" alt="Screenshot 2024-03-05 at 9 54 30 AM" src="https://github.com/Expensify/App/assets/98560306/ab85e5aa-c418-4093-83e6-8b2d940597a3">

</details>

<details>
<summary>Taxes</summary>

<img width="400" alt="Screenshot 2024-03-05 at 9 54 37 AM" src="https://github.com/Expensify/App/assets/98560306/0acff8c0-a8e2-47fc-b1e7-d0c8bb43fa98">

</details>

## Design documentation excerpts

<details>
<summary>Import main page</summary>

<img width="400" alt="Screenshot 2024-03-05 at 10 04 50 AM" src="https://github.com/Expensify/App/assets/98560306/2c270dbb-907f-4685-a1a5-1190fcce0101">
<img width="400" alt="Screenshot 2024-03-05 at 10 05 01 AM" src="https://github.com/Expensify/App/assets/98560306/407a4619-5bad-4095-8aa1-f72a8faeeca0">

</details>

<details>
<summary>Chat of Accounts</summary>

<img width="400" alt="Screenshot 2024-03-05 at 10 03 57 AM" src="https://github.com/Expensify/App/assets/98560306/2d440a64-7338-44b9-b3cf-e2b6ffcc7bbd">

</details>

<details>
<summary>Classes</summary>

<img width="400" alt="Screenshot 2024-03-05 at 10 04 05 AM" src="https://github.com/Expensify/App/assets/98560306/efe3177d-c466-437e-8298-a63745d15b6c">

</details>

<details>
<summary>Customers / Projects</summary>

<img width="400" alt="Screenshot 2024-03-05 at 10 04 12 AM" src="https://github.com/Expensify/App/assets/98560306/d5aaebc0-58cc-4732-9ecb-15c6ba85096f">

</details>

<details>
<summary>Locations</summary>

<img width="400" alt="Screenshot 2024-03-05 at 10 04 18 AM" src="https://github.com/Expensify/App/assets/98560306/12820cd3-ad6f-45d9-84a0-184e2e86f83c">

</details>

<details>
<summary>Taxes</summary>

<img width="400" alt="Screenshot 2024-03-05 at 10 04 25 AM" src="https://github.com/Expensify/App/assets/98560306/e9475e0a-ebe0-455b-8eed-bb0bfa0d6537">

</details>

## Please ask questions
This task comes with a lengthy list of specifications. Please direct any questions you may have to @hayata-suenaga. You most likely will have some. 🙇
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01686216189db35e53</li>
        <li>Upwork Job ID: 1783636150276177920</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by alexpensify** [comment]
@hayata-suenaga any update here? I see you edited the tags.

**Comment by narefyev91** [comment]
Hi! I'm Nicolay from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by hayata-suenaga** [comment]
Tom, sorry for the lack of context

The daily update is [here](https://expensify.slack.com/archives/C036QM0SLJK/p1710204791058019?thread_ts=1710203445.178469&cid=C036QM0SLJK)

CallStack engineers are going to work on the front end issues for the QBO project

**Comment by narefyev91** [comment]
Hey @hayata-suenaga ! Same from my end - let's rock this up! lol
For today - start implementation - probably tomorrow will open draft PR with Main Import Page
For now no blockers

**Comment by narefyev91** [comment]
Daily update - was not able to prepare draft PR - was on resolving some global regressions for big button styling re-writing. Tomorrow draft PR will be parked here 100%

**Comment by hayata-suenaga** [comment]
Thank you for the update!

**Comment by alexpensify** [comment]
Weekly Update: The PR is in review.

**Comment by alexpensify** [comment]
Weekly Update: Still in review but making progress

**Comment by alexpensify** [comment]
Weekly Update: The PR is on staging, making progress here.

**Comment by alexpensify** [comment]
Weekly Update: @hayata-suenaga - I think we have made progress here: https://github.com/Expensify/App/pull/38400. Let me know if there is another GH to track here. Thanks!

**Comment by alexpensify** [comment]
@eVoloshchak - can we confirm if this deploy block notice is valid or not related to this PR? Thanks!

**Comment by hayata-suenaga** [comment]
@alexpensify, the linked bug report in the deploy blocker notice is a mistake on the QA side. We can ignore it 😄

**Comment by alexpensify** [comment]
Thanks for the update! 

## Heads up, I will be offline until Tuesday, April 23, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment]
@eVoloshchak - thanks for flagging. That amount listed is automated but I've audited the GitHub to prepare for the payment process. Please accept the invite here: 

https://www.upwork.com/jobs/~01686216189db35e53

**Comment by eVoloshchak** [comment]
@alexpensify, thank you! 
No need for the Upwork, could you post an updated payment summary here and I'll request the payment via NewDow?

**Comment by alexpensify** [comment]
I missed this note - https://github.com/Expensify/App/issues/37777#issuecomment-2077857729 🙃 

--- 

Payouts due: April 25, 2024

- [ ] Contributor: @narefyev91 is from an agency-contributor and not due payment
- [ ] Contributor+: $500 @eVoloshchak -- please submit a request 

Upwork job is [here](https://www.upwork.com/jobs/~01686216189db35e53)-- not applicable

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak
