### ISSUE TITLE
HOLD for payment 2024-04-05 [$500]  Workspace  - Error message is left and bottom aligned in WS menus

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37770]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into [applausetester+emilio@applause.expensifail.com](mailto:applausetester+emilio@applause.expensifail.com)
account
3. Go to WS settings and turn off internet
4. Remove "[emilio.utest@gmail.com"](mailto:emilio.utest@gmail.com%22)
user and then turn the internet back on
Another way to simulate this error message is by simply turning on "Simulate failing network requests" in Troubleshooting. This will work on any account and is much simpler to reproduce

## Expected Result:
User expects the error message to match the rest of the UI

## Actual Result:
The error message seems too much aligned to the left and also aligned to the bottom

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1440" alt="Bug6402951_1709652827058!Error_message_is_left_and_bottom_aligned" src="https://github.com/Expensify/App/assets/78819774/8b88eeff-b10c-4ca2-903e-d1a65f12fc43">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015595ed66487a0e2e</li>
        <li>Upwork Job ID: 1765366719409008640</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
@Expensify/design can you confirm this is a bug and not expected behaviour? It definitely sounds like an inconsistency

**Comment by shawnborton** [comment]
@lanitochka17 can you elaborate more on your bug report, specifically this part here:

> Expected result: User expects the error message to match the rest of the UI

Just want to clarify what "match the rest of the UI" means, and if this might have failed a certain test, etc?

**Comment by luacmartins** [comment]
This view was introduced as part of ideal nav a few weeks ago and it's past the regression period, so I think we can make it external.

**Comment by shawnborton** [comment]
I think this style makes sense:
![CleanShot 2024-03-06 at 11 43 42@2x](https://github.com/Expensify/App/assets/2319350/26d82445-99e8-4b11-826d-02b16abe2525)

But maybe with slightly more margin below the error message so it feels more attached to the row above. Curious if @Expensify/design has any differing opinions though!

**Comment by shawnborton** [comment]
Not quite - I think the width of the error message in the other proposal might be better. I see where this one aligns with the content a little more, but I feel like we should avoid trying to be too crafty with these messages and just use the same standard style everywhere.

**Comment by laurenreidexpensify** [comment]
Next step: @rushatgabhane to review

**Comment by rushatgabhane** [comment]
@gijoe0295's proposal was first and it looks fine.
@Krishna2323 has given a more detailed solution.

I think we should hire @Krishna2323 because they have a better written proposal  🎀 👀 🎀

**Comment by laurenreidexpensify** [comment]
@Gonals bump for assignment thanks

**Comment by Gonals** [comment]
> @Gonals bump for assignment thanks

On it

**Comment by laurenreidexpensify** [comment]
Payment Summary - 
- C+ @rushatgabhane requires payment through NewDot Manual Requests $500 
- Contributor  @Krishna2323 requires payment https://www.upwork.com/jobs/~011ffc5dbaf530dd5b - please apply in Upwork $500 

@rushatgabhane please confirm if a regression test is required thanks

**Comment by laurenreidexpensify** [comment]
on Hold, not overdue

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane

**Comment by laurenreidexpensify** [comment]
@rushatgabhane @Krishna2323 can you confirm status of regression? Thanks

**Comment by rushatgabhane** [comment]
all resolved!

**Comment by laurenreidexpensify** [comment]
Great - updated payment summary

Payment Summary -

C+ @rushatgabhane requires payment through NewDot Manual Requests $500
Contributor @Krishna2323 requires payment [upwork.com/jobs/~011ffc5dbaf530dd5b](https://www.upwork.com/jobs/~011ffc5dbaf530dd5b) - please apply in Upwork $500
@rushatgabhane please confirm if a regression test is required thanks

**Comment by laurenreidexpensify** [comment]
Payment Summary -

- C+ @rushatgabhane paid through NewDot Manual Requests $500
- Contributor @Krishna2323 paid through upwork $500

@rushatgabhane please confirm if a regression test is required thanks

**Comment by laurenreidexpensify** [comment]
Remaining step to close:

@rushatgabhane please confirm if a regression test is required thanks

**Comment by rushatgabhane** [comment]
No regression tests required
