### ISSUE TITLE
[HOLD #37788][Simplified Collect][Taxes] Create WorkspaceTaxesSettingsCustomTaxName

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37789]
Implement [this section](https://docs.google.com/document/d/12FZycslrIE95QoKM8DZ37H_wLbH9w1jt3uA-a6BCqtc/edit#bookmark=id.wpvryrgcjgc7) of the Simplified Collect: Taxes doc

cc @kosmydel @filip-solecki

**Comment by dylanexpensify** [comment]
held

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this issue!

**Comment by DylanDylann** [comment]
@luacmartins Am I assigned to this issue? Because I reviewed the PR

**Comment by luacmartins** [comment]
Closing this issue to keep it all in https://github.com/Expensify/App/issues/37788
