### ISSUE TITLE
[HOLD for payment 2024-03-22] [$500] [Simplified Collect][Taxes] Create WorkspaceTaxesPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37787]
Implement [this section](https://docs.google.com/document/d/12FZycslrIE95QoKM8DZ37H_wLbH9w1jt3uA-a6BCqtc/edit#bookmark=id.krbk4lakk9k7) of the Simplified Collect: Taxes doc

cc @kosmydel @filip-solecki 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f235a497d678538</li>
        <li>Upwork Job ID: 1765384542491787264</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by filip-solecki** [comment]
Hi!
I am Filip from SWM and I would like to work on this issue!

**Comment by luacmartins** [comment]
Assigned to the issue!

**Comment by luacmartins** [comment]
@filip-solecki did you manage to get started on this issue?

**Comment by DylanDylann** [comment]
@luacmartins Could you help to add me to [Taxes doc](https://docs.google.com/document/d/12FZycslrIE95QoKM8DZ37H_wLbH9w1jt3uA-a6BCqtc/edit#bookmark=id.krbk4lakk9k7) ?

This is my email: dylandylan9112@gmail.com

**Comment by luacmartins** [comment]
@DylanDylann done!

**Comment by DylanDylann** [comment]
@luacmartins @filip-solecki Currently, the checkbox on the tax list page is serving no purpose

https://github.com/Expensify/App/assets/141406735/c2302589-c44a-48c6-a7c1-3f26c8cc07fb

I also don't see any information about this in the docs. It seems we missed it or have we had any plan for it?

**Comment by DylanDylann** [comment]
@luacmartins @mountiny Could you grant me access to [this doc](https://docs.google.com/document/d/1Qv6V4nRqIbZfzQML_saCbrAEqQVIBsiQ3HE1UO7RCxQ/edit#heading=h.cgeusq7xcq2t)? I want to have a deep understanding about tax feature to review related PRs

**Comment by kosmydel** [comment]
> @luacmartins @filip-solecki Currently, the checkbox on the tax list page is serving no purpose
> 
>  Screen.Recording.2024-03-17.at.23.36.59.mov 
> 
> I also don't see any information about this in the docs. It seems we missed it or have we had any plan for it?

It will be included in the bulk actions PR. We will add bulk enabling/disabling etc.

**Comment by mountiny** [comment]
Access granted

> It will be included in the bulk actions PR. We will add bulk enabling/disabling etc.

Sounds good!

**Comment by sakluger** [comment]
Sent an offer for $500 to @DylanDylann via Upwork: https://www.upwork.com/nx/wm/offer/101532660

**Comment by sakluger** [comment]
All paid out 👍
