### ISSUE TITLE
[HOLD for payment 2024-04-03] [$500] [Wave Collect] [More Features] Ensure that disabled feature page cannot be accessed using deeplink

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#37785]
Part of https://github.com/Expensify/Expensify/issues/365143

Follow up to https://github.com/Expensify/App/issues/37373

As described in [this section](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#bookmark=id.pdagmy7dygy) of the design doc, we have created a new More Features page in Collect workspace settings where admins can enable or disable features.

When the Feature is disabled though nobody should be able to access a detailed settings page for that given feature. 

cc @rezkiy37 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c522f27229c4b9e0</li>
        <li>Upwork Job ID: 1767684431368749056</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by trjExpensify** [comment]
Done!

**Comment by rezkiy37** [comment]
I am going to integrate this restriction by creating a wrapper like [AdminPolicyAccessOrNotFoundWrapper](https://github.com/Expensify/App/blob/main/src/pages/workspace/AdminPolicyAccessOrNotFoundWrapper.tsx) or [PaidPolicyAccessOrNotFoundWrapper](https://github.com/Expensify/App/blob/main/src/pages/workspace/PaidPolicyAccessOrNotFoundWrapper.tsx). I can easily integrate the new wrapper into categories and tags pages. The app has a common approach across the pages: 

https://github.com/Expensify/App/blob/9bbe9232579fef7bdac6a3b6037e8965db64d6f1/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L97-L98 

However, I am a little bit confused regarding workspace pages. They use a different approach for showing "Not Found":

https://github.com/Expensify/App/blob/9bbe9232579fef7bdac6a3b6037e8965db64d6f1/src/pages/workspace/workflows/WorkspaceWorkflowsApproverPage.tsx#L168-L173

As we can see they don't use common wrappers as the other pages. So, should I integrate the new wrapper for workspace pages, or extend the current conditions for **FullPageNotFoundView** ? 

cc @mountiny, @trjExpensify

**Comment by trjExpensify** [comment]
Ah, @mountiny, I think this might be down to how we avoid showing the 404 "Hmm.. not found" guy multiple times in one view (i.e LHN workspace settings menu and main pane content).

**Comment by mountiny** [comment]
I think it might be easier to implement a wrapper that will redirect to the More Features page if the user is an admin but the feature is not enabled. That would be instead of showing not found to everyone @rezkiy37 what do you think? 

For normal user, they could be redirected to more-features and there they will see not found page. That is not a problem I think

**Comment by rezkiy37** [comment]
@mountiny, thank you for proposing another flow. I've investigated a solution for how we can implement the flow.

The wrapper (_**FeatureEnabledAccessOrRedirectComponent**_) is going to have an `useEffect` that checks if a feature is enabled or not. If the feature is disabled, it calls `navigate` to the "More Features" page. 

Once I implemented this, I faced an interesting case with a micro/macro tasks queue. How does the flow work:

https://github.com/Expensify/App/assets/57314631/ee0f6c32-7a92-47a2-8505-4694afd5d2ae

1. The user enables a feature.
2. The app prepares `onyxData`.
3. It calls `API.write`, where it calls `Onyx.update` (_a promise, microtask_) for `optimisticData`.
4. It navigates to a feature page.
5. The wrapper gets a feature flag. **Actually**, the value is not updated yet. 
6. The wrapper sees that the flag is `false` and navigates the user to the "More Features" page. 

There is a problem with the queue: the app checks the outdated value before it has been updated. I've found a solution how to fix it. The app needs to set a navigation action to the microtask queue, it guarantees to execute `Onyx.update` first, then the navigation action. The solution can be implemented in 2 ways:
1. Calling `Navigation.navigate(featureRoute)` via `queueMicrotask`. It is a JS method that queues a microtask to be executed at a safe time directly after `Onyx.update`. 
2. Wrapping into a promise, it does the same but uses the promise syntax: 

```js
new Promise<void>((resolve) => {
    resolve();
}).then(() => {
    Navigation.navigate(featureRoute);
});
```

https://github.com/Expensify/App/assets/57314631/90c9275a-c6c7-47de-b82a-7c7ea66fa459

What do you think? Does not it create any concerns with current project patterns?

**Comment by mountiny** [comment]
Makes sense to have such issue. @rezkiy37 are we using the Promise & navigate approach anywhere in the App now? seems quite clean to me, we need to test on slower mobile devices too but I guess that would be fine.

**Comment by rezkiy37** [comment]
> ...are we using the Promise & navigate approach anywhere in the App now?

No, but I found many cases when we use the Promise with **Onyx.connect**. Looks like it is a popular case to wait until a storage update happens. Let me test on some Android emulators. Thank you!

**Comment by rezkiy37** [comment]
The [PR](https://github.com/Expensify/App/pull/37902) is being reviewed internally now.

**Comment by mountiny** [comment]
asking for a c+

**Comment by rezkiy37** [comment]
Hey!
I must inform you that I have a vacation next week. I will be back on Monday 25.03. During the vacation, someone from Callstack can take the issue to work. See you soon!

**Comment by rezkiy37** [comment]
It is not a blocker above - https://github.com/Expensify/App/issues/38896#issuecomment-2017700594.

**Comment by sonialiap** [comment]
@getusha $500 - [offer sent](https://www.upwork.com/nx/wm/offer/101711904)

Please propose regression test steps
