### ISSUE TITLE
[HOLD for payment 2024-04-03] [Simplified Collect][Taxes] Implement deletePolicyTaxes

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37797]
Implement [this section](https://docs.google.com/document/d/12FZycslrIE95QoKM8DZ37H_wLbH9w1jt3uA-a6BCqtc/edit#bookmark=id.rkovtrqndyg5) of the Simplified Collect: Taxes doc

cc @kosmydel @filip-solecki

**Comment by adelekennedy** [comment]
@luacmartins I assume we're still on hold here?

**Comment by luacmartins** [comment]
Yes, we are

**Comment by trjExpensify** [comment]
@luacmartins isn't this done, @luacmartins?

**Comment by luacmartins** [comment]
Yes, my last comment was from 2 weeks ago 😅 This has been implemented and the PR is in staging now.

**Comment by mountiny** [comment]
Lets consolidate on this one https://github.com/Expensify/App/issues/37794 since a single PR resolved 4 issues
