### ISSUE TITLE
[$500] [HOLD for payment 2024-04-03] [Simplified Collect][Taxes] Create WorkspaceEditTaxPage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37794]
Implement [this section](https://docs.google.com/document/d/12FZycslrIE95QoKM8DZ37H_wLbH9w1jt3uA-a6BCqtc/edit#bookmark=id.pkswxrp4zqs5) of the Simplified Collect: Taxes doc

cc @kosmydel @filip-solecki

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e446073ea5b5a4e</li>
        <li>Upwork Job ID: 1775735005542027264</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by kosmydel** [comment]
Hey, I will take care of this issue.

I've prepared a draft PR of it. I will continue work on this when `SetPolicyTaxesEnabled` command will be deployed on backend.

**Comment by garrettmknight** [comment]
Off hold now that the other issue is on prod.

**Comment by DylanDylann** [comment]
@luacmartins Could I take over this one?

**Comment by mountiny** [comment]
@DylanDylann you mean as a C+

**Comment by DylanDylann** [comment]
Yeah, because I have reviewed other pages of tag feature

**Comment by mountiny** [comment]
Thats reasonable, assign you

**Comment by jliexpensify** [comment]
Hello, I am OOO from 21st to 31st March. I won't assign this to another B0 member, as I think during this period, there are likely no actions for me to take, right?

**Comment by mountiny** [comment]
Sounds good

**Comment by mountiny** [comment]
There were 4 pages which were fixed in here, I suggest paying $500 to @DylanDylann for the review cc @luacmartins @trjExpensify of https://github.com/Expensify/App/pull/38208

**Comment by trjExpensify** [comment]
Sounds good to me!

**Comment by jliexpensify** [comment]
Payment Summary

- C+: @DylanDylann $500 [(as per this comment)](https://github.com/Expensify/App/issues/37794#issuecomment-2027814493)

**Comment by jliexpensify** [comment]
@DylanDylann have invited you [here](https://www.upwork.com/jobs/~011e446073ea5b5a4e)

**Comment by jliexpensify** [comment]
Waiting on @DylanDylann to accept. Also, any Regression Tests needed here?

**Comment by luacmartins** [comment]
No regression tests as part of this issue, we're adding it as part of the project instead.

**Comment by jliexpensify** [comment]
Paid and job closed!
