### ISSUE TITLE
[Awaiting Payment 2nd May] [Wave Collect][QBO] Implement Advanced configuration screens

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#37799]
Implement pages related to the import configurations for the QuickBooks Online (QBO) connection project.

QBO is a well-known accounting software that Expensify supports integration with. Once the user establishes a connection to QBO, Expensify exports expense reports, also known as money requests, to QBO. This enables expenses, referred to as transactions in QBO terminology, to appear in the accounting software.

In this issue, your task is to implement pages related to advanced configurations. No accounting knowledge is required for this task. However, if you need additional context, feel free to contact @hayata-suenaga.

## Terminologies

- [Accounts](https://quickbooks.intuit.com/learn-support/en-us/help-article/chart-accounts/learn-chart-accounts-quickbooks-online/L2yc6KBob_US_en_US): categories used to classify transactions on QBO
- Chart of Accounts: A list of available accounts

## Product Specifications

<details>
<summary>Product Specifications</summary>

<img width="400" alt="Screenshot 2024-03-05 at 1 09 55 PM" src="https://github.com/Expensify/App/assets/98560306/da70f62e-afc1-4264-8b44-9a8fa9ca4c2b">
<img width="400" alt="Screenshot 2024-03-05 at 1 18 03 PM" src="https://github.com/Expensify/App/assets/98560306/546fdcf8-e062-48a7-8e48-df3a2710a067">

</details>

<details>
<summary>Design documentation excerpts</summary>

<img width="400" alt="Screenshot 2024-03-05 at 1 06 53 PM" src="https://github.com/Expensify/App/assets/98560306/a13a1a46-c4eb-4f22-9a4c-220a70227982">
<img width="400" alt="Screenshot 2024-03-05 at 1 07 12 PM 1" src="https://github.com/Expensify/App/assets/98560306/9adfcab5-65a3-45d3-acfd-eb7644122014">

</details>

## Please ask questions
This task comes with a lengthy list of specifications. Please direct any questions you may have to @hayata-suenaga. You most likely will have some. 🙇

<details><summary>Issue Owner</summary>Current Issue Owner: @hayata-suenaga</details>

**Comment by hayata-suenaga** [comment]
CallStack engineer will work on this issue

**Comment by hayata-suenaga** [comment]
I gonna change the priority to weekly. A CallStack engineer will work on this.

**Comment by trjExpensify** [comment]
Is there a draft PR for this issue yet? Who from Callstack is taking it on, and can we assign them?

**Comment by hayata-suenaga** [comment]
Either @teneeto or @narefyev91 is going to work after the following PRs are done:

https://github.com/Expensify/App/pull/38283
https://github.com/Expensify/App/pull/38400
https://github.com/Expensify/App/pull/39191

**Comment by trjExpensify** [comment]
Okay, so we don't know who yet and there isn't a draft? Cool, cool!

**Comment by teneeto** [comment]
Hi @hayata-suenaga let me take care of this one.

**Comment by hayata-suenaga** [comment]
The first PR was merged 🎉

**Comment by hayata-suenaga** [comment]
waiting for payment, Melvin

**Comment by s77rt** [comment]
Payment is being handled in https://github.com/Expensify/App/issues/40706. We can close this

**Comment by jliexpensify** [comment]
Paid in the other job!
