### ISSUE TITLE
[HOLD for payment 2024-04-03] [Simplified Collect][Taxes] Create EditTaxNamePage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37795]
Implement [this section](https://docs.google.com/document/d/12FZycslrIE95QoKM8DZ37H_wLbH9w1jt3uA-a6BCqtc/edit#bookmark=id.p6m6gw7oa90k) of the Simplified Collect: Taxes doc

cc @kosmydel @filip-solecki

**Comment by DylanDylann** [comment]
@luacmartins Could I take over this one?

**Comment by luacmartins** [comment]
Seems like we have a draft PR

**Comment by luacmartins** [comment]
@kosmydel could you leave a comment so I can assign you to the issue please?

**Comment by kosmydel** [comment]
:)

**Comment by mountiny** [comment]
Lets consolidate on this one https://github.com/Expensify/App/issues/37794 since a single PR resolved 4 issues
