### ISSUE TITLE
[HOLD #37788][Simplified Collect][Taxes] Create WorkspaceTaxesSettingsForeignCurrency

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37791]
Implement [this section](https://docs.google.com/document/d/12FZycslrIE95QoKM8DZ37H_wLbH9w1jt3uA-a6BCqtc/edit#bookmark=id.jkdqf6agggva) of the Simplified Collect: Taxes doc

cc @kosmydel @filip-solecki

**Comment by DylanDylann** [comment]
The PR is merged

**Comment by DylanDylann** [comment]
@luacmartins Am I assigned to this issue? Because I reviewed the PR

**Comment by luacmartins** [comment]
Yes, just assigned you. Thanks for the ping!

**Comment by luacmartins** [comment]
Hmm actually, I think we can close these issues and keep it all in https://github.com/Expensify/App/issues/37788, since the same PR closed 4 issues.

**Comment by luacmartins** [comment]
Closing this issue to keep it all in https://github.com/Expensify/App/issues/37788
