### ISSUE TITLE
[Pay now][$500] Payment for https://github.com/Expensify/App/pull/30829

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#37798]
- https://github.com/Expensify/App/pull/30829

Which is part of 
- https://github.com/Expensify/App/issues/20471

**Comment by akinwale** [comment]
@mallenexpensify Accepted. Thanks!

**Comment by mallenexpensify** [comment]
@akinwale can you comment on the PR [here](https://github.com/Expensify/App/pull/30829#discussion_r1514802751). I want to know if there's a regression and compensation should be reduce by 50%
> This line caused crash - https://github.com/Expensify/App/issues/36834
source is not always string, i.e. svg

**Comment by akinwale** [comment]
@mallenexpensify It appears that the regression came from the PR, but it's an edge case that we wouldn't have been able to catch over the course of testing the video playback feature.

**Comment by mallenexpensify** [comment]
Thanks @akinwale to close the loop, for 'edge case' you're saying it falls under [this part of the C+ process doc](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit#bookmark=id.qr9c929owwy8)
> *“Should have” = C+ should have caught the bug by fully following the checklist.  If C+ skips a step or completed the checklist incompletely, payment will be cut in half.   

Is that correct? (asking cuz I want to know if we need to consider updating anything)

**Comment by akinwale** [comment]
> Is that correct? (asking cuz I want to know if we need to consider updating anything)

Yes, this seems to be the case. The bug happens when viewing a workspace avatar, not with the video player itself.

**Comment by mallenexpensify** [comment]
Contributor+: @akinwale paid $500 via Upwork.
