### ISSUE TITLE
[HOLD for payment 2024-04-03] [Simplified Collect][Taxes] Create EditTaxValuePage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#37796]
Implement [this section](https://docs.google.com/document/d/12FZycslrIE95QoKM8DZ37H_wLbH9w1jt3uA-a6BCqtc/edit#bookmark=id.ljjhku705spy) of the Simplified Collect: Taxes doc

cc @kosmydel @filip-solecki

**Comment by garrettmknight** [comment]
Still on hold, but the issue that this is held on is no longer on hold so that's progress. 🚀

**Comment by luacmartins** [comment]
We can remove the hold

**Comment by mountiny** [comment]
Lets consolidate on this one https://github.com/Expensify/App/issues/37794 since a single PR resolved 4 issues
