### ISSUE TITLE
iOS - Login - Blank page after using magic code link, returnable to 'enter code' by swiping right

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37815]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4380855
**Email or phone of affected tester (no customers):** almexp2+777@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team
**Slack conversation:** https://applause-ts.slack.com/archives/G01CL838B8T/p1709602542647289

## Action Performed:
1. Open the iOS app
2. Enter an email address > tap 'Continue'
3. Request a magic code
4. Locate the email containing the main code link and click on the link
5. In the app, swipe right when the blank screen appears

## Expected Result:
After using the magic code link, the user should be redirected to the 'Enter Magic Code' screen in the loading state.

## Actual Result:
There's a blank page when using the magic code link, and it's possible to return to the "enter magic code" screen by swiping right.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7ce57456-6f49-4aa2-9481-0f5276095372

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment]
Okay I'll review it.

**Comment by strepanier03** [comment]
Discussing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1709873841897499).

**Comment by strepanier03** [comment]
Closing this because the user is still logged in and making a change here is low value if we want to make a change at all.
