### ISSUE TITLE
[HOLD for payment 2024-07-17] [$500] [CRITICAL] Create Trip Receipt for newDot

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#37824]
## VIP-Travel Implementation Issue
Tracking Issue: https://github.com/Expensify/Expensify/issues/333471
Project: https://github.com/orgs/Expensify/projects/112/
Relevant Design Doc Section: https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.lgcmthyxnpmx

This issue is for creating a special receipt preview for trips:
<img width="923" alt="2024-03-06_07-50-59" src="https://github.com/Expensify/App/assets/42391420/7128849a-9142-4b8b-8f77-d5fa191bea58">

We will update [ReceiptUtils.getThumbnailAndImageURIs](https://github.com/Expensify/App/blob/9ab4fe92dcbac8252998febf6fa24a080a196a70/src/libs/ReceiptUtils.ts#L33) so that, if the transaction is for transport (and doesn’t have an attached receipt), the plane placeholder is displayed, and, if it is for lodging, the bed one is displayed.

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by cdOut** [comment]
Hello, I’m Tymoteusz from Software Mansion, the expert agency, and I’d like to work on this task.

**Comment by twisterdotcom** [comment]
Adding a C+ here for Travel reviews: @shubham1206agra

**Comment by cdOut** [comment]
As an update, I’m currently working on setting up a draft PR by tomorrow.

**Comment by twisterdotcom** [comment]
How is this PR going @cdOut?

**Comment by twisterdotcom** [comment]
Waiting on the backend.

**Comment by twisterdotcom** [comment]
Updates in https://expensify.slack.com/archives/C05S5EV2JTX/p1714085516706139?thread_ts=1713825695.223409&cid=C05S5EV2JTX

**Comment by cdOut** [comment]
Same case as for Trip Details, I've noticed @rushatgabhane has a lot of tasks on him and since I'm back I can take this one back for myself to finish up.

**Comment by cdOut** [comment]
I'm going to be working on this today, I estimate I'll be able to put this up for review by tomorrow or on friday if I face any bigger issues while implementing the backends.

**Comment by twisterdotcom** [comment]
Need any assistance here @cdOut?

**Comment by cdOut** [comment]
Update provided [in the Trip Details](https://github.com/Expensify/App/issues/37823#issuecomment-2144977867) thread.

**Comment by twisterdotcom** [comment]
https://expensify.slack.com/archives/C05S5EV2JTX/p1718412514464099?thread_ts=1718382488.093209&cid=C05S5EV2JTX

**Comment by twisterdotcom** [comment]
Payment Summary:

- @shubham1206agra paid $500 [here](https://www.upwork.com/nx/wm/offer/103170185) (C+)
- @cdOut **does not** require payment (Contractor)
