### ISSUE TITLE
[Performance] Return variable if no keys are changed

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#37822]
# Problem

In OnyxCache.js we have getAllKeys method, which upon invocation generates a new Array from the set and returns it. Below is how it looks as of yet:

```
getAllKeys() {
  return Array.from(this.storageKeys);
}
```

In App Startup cycle, as a result of Onyx.Connect calls we execute this method each time. We roughly have more than 30 connections which happens in App Startup cycle. As a result, each time a new array is created from the set.

# Solution

We can improve this by checking whether the keys have changed and if they have changed, we create a new array and store it to a variable. And then the next time getAllKeys is invoked we will just return this variable if no keys are changed.
Let’s see how it looks like in action:

```
// In OnyxCache.js
constructor() {
	...
 this.keysArray = [];
 this.hasChanged = false;
	...
}

getAllKeys() {
  if (this.hasChanged) {
    this.keysArray = Array.from(this.storageKeys);
  }
  this.hasChanged = false;
  return this.keysArray;
}

addKey(key) {
	 ……
  this.hasChanged =  true;
}

merge(data){
   .....
   this.storageKeys = new Set([...storageKeys, ...mergedKeys]);

// set the flag to indicate that the keys have changed
   this.hasChanged = true;
   .....
}


drop(key) {
		……
  this.hasChanged =  true;
}
```

From @hurali97

**Comment by hurali97** [comment]
Hey @muttmuure, please assign this to me 👍
