### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [MEDIUM] Create new Trip Room

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#37825]
## VIP-Travel Implementation Issue
Tracking Issue: https://github.com/Expensify/Expensify/issues/333471
Project: https://github.com/orgs/Expensify/projects/112/
Relevant Design Doc Section: https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.g77lx534xj1g

<img width="923" alt="2024-03-06_07-50-59" src="https://github.com/Expensify/App/assets/42391420/ef6827f5-b2aa-42bd-ae3a-3017fbb4c175">

A new component, TripDetailsView will be created in src/components/ReportActionItem:
- It will display and behave mimicking [MoneyReportView](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/MoneyReportView.tsx)’s behavior.
- A new chat type, ​​POLICY_TRIP_ROOM, will be added to [CONST.ts](https://github.com/Expensify/App/blob/d5eba656251269b238797817df3cf84800b0039a/src/CONST.ts#L642).
- A new helper function, isTripRoom(report) will be added to [ReportUtils](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts). It will return true if the provided report type is CONST.REPORT.TYPE.CHAT, and the chat type is the new CONST.REPORT.CHAT_TYPE.​​POLICY_TRIP_ROOM
- It will be displayed from [ReportActionItem](https://github.com/Expensify/App/blob/8f5889874f36735a66f55efc7522bd67c2173d3e/src/pages/home/report/ReportActionItem.js#L649) if isTripRoom returns true.
- It will take the associated expense report as parameter and: 
- Use the new [getTripTransactions](https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.pcigx4pdt3a7) function to retrieve all transactions with trip data to display.
- Display them as shown above using the existing MenuItemWithTopDescription [like we do for money reports.](https://github.com/Expensify/App/blob/8f5889874f36735a66f55efc7522bd67c2173d3e/src/components/ReportActionItem/MoneyReportView.tsx#L84)
- On click, it will open [the trip details panel](https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.na43be2cxvs5) via [a new route](https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.gn6jbl2udlnx), ROUTES.TRAVEL_DETAILS

Routes table:
https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.gn6jbl2udlnx

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by WojtekBoman** [comment]
Hey! I’m Wojtek from Software Mansion, the expert agency, and I’d like to work on this issue.

**Comment by twisterdotcom** [comment]
Adding a C+ here for Travel reviews: @shubham1206agra

**Comment by twisterdotcom** [comment]
Only assigned on Friday. We can give them a day here Melvin.

**Comment by twisterdotcom** [comment]
Are we waiting on anything internal here?

**Comment by smelaa** [comment]
Hi! I'm Aleksandra from Software Mansion, the expert agency, and I would like to take it over from Wojtek and work on this issue.

**Comment by twisterdotcom** [comment]
@smelaa only assigned on Friday.

**Comment by WojtekBoman** [comment]
Hi! I have some questions regarding this issue :) I've marked on the screenshot elements related to the questions below.

1. What should the rows with travel details look like when hovering over these elements? I'm specifically asking about the background color of the icon, I'm also attaching a screenshot showing the current hover style of this element.
2. I need to know the logic for displaying date text. Could you please give me similar examples as [here](https://github.com/Expensify/App/issues/37826#issuecomment-2007294768) for different years, months etc?
3. Which field from [this data structure](https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.vt3xra6ecjha) should be used to display this text (record locator)? If it's not known yet, can we adjust it once the backend is ready?
<img width="839" alt="Screenshot 2024-03-25 at 16 28 43" src="https://github.com/Expensify/App/assets/47774969/fa623988-a5ca-4708-aabe-733d391d3220">
<img width="1511" alt="Screenshot 2024-03-25 at 16 55 57" src="https://github.com/Expensify/App/assets/47774969/9bb151fa-922f-4800-9961-a76daf5ae9a5">

**Comment by shawnborton** [comment]
We have a value in our color system for rowHover, which is `product300`. If you use that, we shouldn't get any collisions with the icon BG color:
![CleanShot 2024-03-25 at 12 27 21@2x](https://github.com/Expensify/App/assets/2319350/a9c29cd9-5c8f-4d9b-b1ad-02424db2b34b)

**Comment by WojtekBoman** [comment]
@shawnborton @dannymcclain 

> I need to know the logic for displaying date text. Could you please give me similar examples as [here](https://github.com/Expensify/App/issues/37826#issuecomment-2007294768) for different years, months etc?

Could you take a look at it when you have time? :)

**Comment by dannymcclain** [comment]
I would just use the same? Not sure why they would be different. Will definitely let Shawn weigh in too, but I can't think of a reason for them using different date formatting.

**Comment by shawnborton** [comment]
Yeah that's my thinking too. I think if you are looking at a date that has a year other than the current year we are in, it should show the year. But if you are looking at a date within the current year, no need to show the year.

**Comment by WojtekBoman** [comment]
Ok, I asked because I had noticed on the designs that the date text also includes the day name, flight time, etc. and I was wondering if I could apply the same rules for date text displaying which was used for TripRoomPreview.

**Comment by shawnborton** [comment]
Oh, are you asking about the date here for instance?
![CleanShot 2024-03-26 at 10 29 39@2x](https://github.com/Expensify/App/assets/2319350/848868b3-8c9f-4055-92f3-24840dcb3309)

**Comment by WojtekBoman** [comment]
Exactly :)

**Comment by WojtekBoman** [comment]
Ok, and when years are different, we'll display just: Friday, Dec 29, 2023 to Tuesday, Jan 2, 2024. Am I right?

**Comment by shawnborton** [comment]
I think so, as well as if you are looking at a flight that happened in a previous year.

**Comment by stitesExpensify** [comment]
> Which field from [this data structure](https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.vt3xra6ecjha) should be used to display this text (record locator)? If it's not known yet, can we adjust it once the backend is ready?

This should just be `start.date` and the confirmation number in the bottom left is `confirmations.value`. For the overall trip room there is also a startDate and endDate in the overall report data https://docs.google.com/document/d/122DLLTuCsU4NC3c7rNiy4UF8bZxVlLEWSy3yncqCTcQ/edit#bookmark=id.pa0o1z2qu2nd

**Comment by WojtekBoman** [comment]
Ok, I was thinking about `confirmations`, but I see on the screen attached in the design doc that it's an array. So, I believe that we can just display the value of the first element in this array. Do you think it's ok?
<img width="450" alt="bW_8yW28uqs_8TE23GZqH_Knx1XvET9zqvSl_OsKlzb_3Gt6D5HfXH602oSkyKwD-nv1l9A_hb4yFbBdpv4ccTAI5PePnGoqxOpXPK1F4It0PDZ-9YaNKVRrI1wr" src="https://github.com/Expensify/App/assets/47774969/b3fbf6f7-c5bc-455a-ac7a-65ff44395d87">

**Comment by WojtekBoman** [comment]
I was thinking about the confirmation number (look at the rectangle nr 3). I know which fields I should use to display date text, but I was wondering which one should be used to display the confirmation number.
<img width="839" alt="316571804-fa623988-a5ca-4708-aabe-733d391d3220" src="https://github.com/Expensify/App/assets/47774969/e6715288-f856-49d0-b573-84675f01436f">

**Comment by twisterdotcom** [comment]
Latest comment: https://expensify.slack.com/archives/C05S5EV2JTX/p1712244259890909?thread_ts=1712164287.109189&cid=C05S5EV2JTX

**Comment by twisterdotcom** [comment]
Still waiting on webhooks.

**Comment by twisterdotcom** [comment]
Waiting on the backend.

**Comment by twisterdotcom** [comment]
Waiting on the backend still

**Comment by twisterdotcom** [comment]
Spotnana thread for backend updates here: https://expensify.slack.com/archives/C066REXJ9D3/p1713220956933639

**Comment by twisterdotcom** [comment]
Chatting about getting the data here: https://expensify.slack.com/archives/C05S5EV2JTX/p1713784714491629?thread_ts=1713545844.230119&cid=C05S5EV2JTX

**Comment by twisterdotcom** [comment]
Updates in https://expensify.slack.com/archives/C05S5EV2JTX/p1714085516706139?thread_ts=1713825695.223409&cid=C05S5EV2JTX

**Comment by twisterdotcom** [comment]
Update here: https://expensify.slack.com/archives/C05S5EV2JTX/p1714431147318139. Waiting on Spotnana.

**Comment by twisterdotcom** [comment]
@rushatgabhane has a PR above.

**Comment by rushatgabhane** [comment]
Updates here - https://expensify.slack.com/archives/C05S5EV2JTX/p1716196862504789?thread_ts=1715723531.626149&cid=C05S5EV2JTX

waiting for car details

**Comment by rushatgabhane** [comment]
@shubham1206agra this is ready for your review. There are a few backend issues  [here](https://expensify.slack.com/archives/C05S5EV2JTX/p1716647047009049) and [here](https://expensify.slack.com/archives/C05S5EV2JTX/p1716641603874949?thread_ts=1716570830.369449&cid=C05S5EV2JTX) but it shouldn't block anything.

**Comment by rushatgabhane** [comment]
PR hit production 2 days ago.

**Comment by rushatgabhane** [comment]
@shubham1206agra please complete checklist for this one

**Comment by rushatgabhane** [comment]
@twisterdotcom could you please attach payment summary 🙇

**Comment by twisterdotcom** [comment]
Payment Summary: ($500 as originally this was CRITICAL):

- @rushatgabhane paid $500 via newDot requests
- @shubham1206agra paid $500 [here](https://www.upwork.com/nx/wm/offer/new/1028761871)

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
