### ISSUE TITLE
Wrong report title for expensify card transactions

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction ( don't have expensify card transactions)
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709735584075159

## Action Performed:
1. Go to a workspace chat as employee
2. Create expensify card transaction report and submit to approver
3. Sign in to approver accoun and open the expense report

## Expected Result:
Should be "employee email address spent $x.xx"

## Actual Result:
Shows "approver email address spent $x.xx"
reportID: 2716853747469889

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (4)](https://github.com/Expensify/App/assets/38435837/2497b8c4-7448-4c32-be73-fdc2b5e48b10)

![image (5)](https://github.com/Expensify/App/assets/38435837/8bb8bf53-a5df-4e66-bee0-7b473f267e25)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
@grgia have you had a change to look at this?

**Comment by grgia** [comment]
Closing, should be good now!
