### ISSUE TITLE
[$500] Update en.ts 

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#37833]
Coming from this issue: https://github.com/Expensify/App/pull/33843#issuecomment-1898917047

and this PR https://github.com/Expensify/App/pull/33843

Please complete payment for @situchan 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c14af097d61c86a</li>
        <li>Upwork Job ID: 1765440699830910976</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by situchan** [comment]
Thanks for creating payment GH.
Though it was internal PR, $250 is fine to me based on simplicity.

**Comment by isabelastisser** [comment]
@situchan I sent you the offer in Upwork. Please accept it and I will process the payment. Thanks!

**Comment by situchan** [comment]
@isabelastisser accepted. thanks
