### ISSUE TITLE
HIGH: Fix redundant `GetMissingOnyxUpdates` requests

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#37843]
See: https://expensify.slack.com/archives/C049HHMV9SM/p1709753074184619?thread_ts=1708910410.150829&cid=C049HHMV9SM

**Comment by danieldoglas** [comment]
Ok, we've added 2 separate fixes for this and I think it will solve our issue. Setting it as in review for now, until those fixes reach staging and we can check if it's still happening.

**Comment by danieldoglas** [comment]
Ok, I think this one is done. @quinthar shared that it's not happening anymore, so closing this one.
