### ISSUE TITLE
Profile - Unable to upload profile avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37849]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings.
3. Click on profile avatar > Upload photo.
4. Upload a photo and save it.

## Expected Result:
User is able to save the new avatar.

## Actual Result:
Nothing happens when clicking Save on profile avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/397350b7-df6c-4415-bd95-33cbc313e745

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by tylerkaraszewski** [comment]
Same happens for me.
https://github.com/Expensify/App/assets/705000/739f8d0a-ea8b-4a6a-8f14-835ab3fcaf1a

**Comment by tylerkaraszewski** [comment]
Asked about this here: https://expensify.slack.com/archives/C01GTK53T8Q/p1709842714555209

**Comment by ikevin127** [comment]
Might've been caused by [[New architecture] Replace `@oguzhnatly/react-native-image-manipulator` with `expo-image-manipulator`](https://github.com/Expensify/App/pull/36019) though not 100% sure - CP-ing this and testing will confirm whether this is the offending PR or not ✌

**Comment by roryabraham** [comment]
reopening to verify the fix

**Comment by roryabraham** [comment]
verified this is fixed

![image](https://github.com/Expensify/App/assets/47436092/d65b30d2-6e3b-419f-84c7-74aeb0f2a443)
