### ISSUE TITLE
[HybridApp] Problem #4: Push notifications should open the related experience

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#37857]
## Problem
Users will receive push notifications to HybridApp for both the New and Old experience. The HybridApp should open to the corresponding experience depending on which push notification is sent. Users should only receive one push notification and no duplicated push notifications for actions taken on the New or Old experience.

## Solution
Current implementation is not handling push notifications correctly, because multiple Airship SDK are being used depending on the platform. In order to make push notifications work as expected we will have to tweak the code, and adjust it accordingly.

#### **Android 🤖**<a id="android-"></a>

After [talks with Ryan and Josh from Airship](https://swmansion.slack.com/archives/C01RJ1RCK8D/p1706607484651069) we’re going to follow their suggestions and refactor the **PushNotificationManager** code. We’re going to simplify it in order to make the integration with React Native SDK simpler. After the refactor we’re going to end up with 3 files:

- [**PushNotificationManager.java**](https://urbanairship.slack.com/files/U01NKPP0YUR/F06HP16CX8V/pushnotificationmanager.java) - simplified and refactored by Josh from Airship

- **CustomAirshipExtender.java** - including logic from current React Native extender and [**ExpensifyAutopilot.java**](https://urbanairship.slack.com/files/U01NKPP0YUR/F06HK9EFDBQ/expensifyautopilot.java) written by Josh from Airship.

- **CustomNotificationProvider.java** - including logic from current React Native provider and [**ExpensifyNotificationProvider.java**](https://urbanairship.slack.com/files/U01NKPP0YUR/F06JEMVG17A/expensifynotificationprovider.java) written by Josh from Airship.

There are going to be two additions in the AndroidManifest.xml file also. 

```
<meta-data
    android:name="com.urbanairship.autopilot"
    android:value="com.urbanairship.reactnative.ReactAutopilot"/>
```

```
<meta-data
    android:name="com.urbanairship.reactnative.AIRSHIP_EXTENDER"
android:value="org.me.mobiexpensifyg.CustomAirshipExtender"/>
```

The flow is going to look like this: on startup the app will trigger the **ReactAutopilot** class, which looks for airship extenders. If it finds one, it triggers the extender's **onAirshipReady** method. This is where **CustomNotificationProvider** is going to be set up. 

There is going to be a small addition to the **onCreate** method in **ExpensifyActivityBase**. We have to add **SoLoader.init(this, false),** because we’re going to initialize Airship React Native SDK, before booting NewDot. SoLoader is a library responsible for loading native code in React Native on Android.

#### **iOS 🍎**<a id="ios-"></a>

On iOS the merge is going to be way simpler. We just need to remove the **takeOff** function from **ExpensifyAppDelegate.m**, and invoke the setup method from **ReactNativeManager.swift**.\
The **setup** method is going to initialize some React Native libraries, including **AirshipSDK**, which will call the **takeOff** method for us.

`- [UAirship takeOff:config launchOptions:launchOptions];  + [ReactNativeManager` `setup];`

Another advantage of calling the **setup** method will be a slightly faster boot of NewDot.

**Comment by AndrewGable** [comment]
@staszekscp - Comment here and I will assign you!

**Comment by AndrewGable** [comment]
@staszekscp is working on it!

**Comment by AndrewGable** [comment]
Working on it!

**Comment by AndrewGable** [comment]
@staszekscp is working on it!

**Comment by AndrewGable** [comment]
@staszekscp is working on it! I think also @Julesssss might work on some backend pieces too.

**Comment by AndrewGable** [comment]
@staszekscp is working on it! https://github.com/Expensify/Mobile-Expensify/pull/12610

**Comment by staszekscp** [comment]
Hey! I am working on it! 😅
