### ISSUE TITLE
[HybridApp] Problem #2: Make the “Try New Expensify” button more noticeable

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#37855]
## Problem
During [the pre-design](https://expensify.slack.com/archives/C05DWUDHVK7/p1704751974306629), we decided to move the “Try New Expensify” to the hamburger menu of the Old experience. This will allow users to more easily discover the ability to switch to the new experience and additionally see if they have an unread chat message.

## Solution
The design team will create a 16x16 vector asset for display in the hamburger menu. We’ll export an SVG file for Android, and 3 png assets for iOS (1x, 2x, 3x).

[Here](https://docs.google.com/document/d/1RfKAcH4fdlPKUzHDfKLjSZaMnsOBddHPp2cLq504QQY/edit#bookmark=id.f87srgkb88oi) is the Design Doc section.

**Add the TryNewDot menu item to the Navigation Menu**

_Code changes are limited to the_ [_SlidingMenuController.js_](https://github.com/Expensify/Mobile-Expensify/blob/df9765d51e34a440df726fabc97df036a85b6287/app/Controllers/SlidingMenuController.js) _file:_

- Add a new page to the [PAGES array](https://github.com/Expensify/Mobile-Expensify/blob/df9765d51e34a440df726fabc97df036a85b6287/app/Controllers/SlidingMenuController.js#L48-L54):

```
    SlidingMenuController.PAGES = {
        ...
        SETTINGS: 'settings',
        TRYNEWDOT: 'trynewdot'
    };
```
- Register the icon within [ICONS](https://github.com/Expensify/Mobile-Expensify/blob/df9765d51e34a440df726fabc97df036a85b6287/app/Controllers/SlidingMenuController.js#L60-L81):

    SlidingMenuController.ICONS = {
        ...
        SETTINGS: 'settings',
        TRYNEWDOT: 'newdoticon'
        ...
    };   

- Add the TryNewDot option to the [Navigation item row list](https://github.com/Expensify/Mobile-Expensify/blob/df9765d51e34a440df726fabc97df036a85b6287/app/Controllers/SlidingMenuController.js#L163-L208): 

    ...
    rows.push({
        id: SlidingMenuController.PAGES.TRYNEWDOT,
        type: SlidingMenuController.ROW_TYPES.BASIC,
        icon: SlidingMenuController.ICONS.TRYNEWDOT,
        text: 'Try New Expensify',
        isSelected: false
    });
    ...

**Switch to NewDot when the navigation item is selected** 

- Within SlidingMenuController.js [callback handler](https://github.com/Expensify/Mobile-Expensify/blob/df9765d51e34a440df726fabc97df036a85b6287/app/Controllers/SlidingMenuController.js#L310-L340), register a callback for the TRYNEWDOT page, create the NewDot launch transition URL, and open it:

    ...
    case SlidingMenuController.PAGES.TRYNEWDOT:
        API.GetShortLivedAuthToken().done(function (response) {
            const URL = Expensify.getInstance().buildNewDotTransitionURL(response, '/');
            yaplOpenNewApp(URL);
        });
        break;
    default:
    ...

**Comment by Julesssss** [comment]
Hey Jon, [here's](https://docs.google.com/document/d/1RfKAcH4fdlPKUzHDfKLjSZaMnsOBddHPp2cLq504QQY/edit#bookmark=id.f87srgkb88oi) the section of the design doc describing the icon we'll need.

**Comment by Julesssss** [comment]
[WIP PR](https://github.com/Expensify/Mobile-Expensify/pull/12611)

**Comment by dubielzyk-expensify** [comment]
@Julesssss : I've added the two icons I believe you need in [our good ol' trusty icon doc](https://www.figma.com/file/HY4yoTixNOoffaKXR7pxLH/OldDot-App-Icons?type=design&node-id=488-639&mode=design&t=SXHs1yK2MRLF7LxV-4). One with a unread message icon and one without. I believe we don't need a proper active icon as it'll link out of the app.

Let me know when I can check it out as it might need tweaking or if something is wrong 😄

**Comment by Julesssss** [comment]
I think the code is complete, but I am again unable to build the Android app. I've tried all the [known](https://github.com/Expensify/Expensify/issues/371824#issuecomment-1976828017) instructions, new `rm -rf` cache folders instructions, plus nuking the entire repo. Not sure what else I can do.

**Comment by Julesssss** [comment]
Hey @dubielzyk-expensify, the icon looks very slightly out of sync with the others, do you think maybe the new icon or the Settings icon needs adjustment?

-- | --
-- | --
![Screenshot_20240311_135136](https://github.com/Expensify/App/assets/10736861/74b3a14d-f3ff-4686-b355-157a4017bd02) | ![Screenshot 2024-03-11 at 13 53 09](https://github.com/Expensify/App/assets/10736861/90f37e6c-c1f9-4909-8dd2-9101dd1de024)

**Comment by dubielzyk-expensify** [comment]
I've updated them. Should be good now https://www.figma.com/file/HY4yoTixNOoffaKXR7pxLH/OldDot-App-Icons?type=design&node-id=488-639&mode=design&t=XMIMS5jy5stsfkMc-4

**Comment by Julesssss** [comment]
I have been making slow progress. The holdup is due to slow build/testing and the need to skip our `onInternalPageCreated` logic as we are not creating a page for this Nav item.

**Comment by Julesssss** [comment]
Build issues are over, I have completed the changes and tested both iOS and Android. 

I'm unable to successfully make the OldDot > NewDot switch, but this is already happening for the Settings 'Try NewDot' option. I asked [here](https://expensify.slack.com/archives/C036QM0SLJK/p1710261750099549) to see what I have missed when building to physical devices. 


iOS | Android
 -- | --
![Screenshot 2024-03-12 at 15 38 29](https://github.com/Expensify/App/assets/10736861/1c45737a-1645-442a-97d3-41f12f56fb33) | ![Screenshot 2024-03-12 at 15 38 37](https://github.com/Expensify/App/assets/10736861/ed3ed91f-109e-49cf-a5f0-21b28b530d53)

Videos: 

**iOS**

https://github.com/Expensify/App/assets/10736861/7c2630e8-6928-40dd-b4b1-eddb82a4ffbb 

**Android**
 
https://github.com/Expensify/App/assets/10736861/b7dccee1-f7b2-4283-9af4-0bead04239a8

**Comment by Julesssss** [comment]
PR is ready [here](https://github.com/Expensify/Mobile-Expensify/pull/12611), but due to the authentication issue I'm holding the PR review until this can be fully tested.

**Comment by Julesssss** [comment]
I didn't have a moment to retest with the changes from `main` today due to this, but this is on my list for tomorrow/early next week

**Comment by Julesssss** [comment]
I successfully confirmed the Android changes today, after merging main app switching is working as expected 🎉 

Unfortunately I can't open the PR as iOS is now failing due yo ruby/bundler issues. I have resolved this before, but I'm out of time and will need to resolve this when I'm back on Tuesday. I might open the PR to Andrew in the meantime, as he likely can verify iOS.

**Comment by Julesssss** [comment]
I marked the PR ready for review, but since my ruby issue I haven't verified iOS myself locally. It'll need to be confirmed by a reviewer.
