### ISSUE TITLE
Distance - Error shows up when creating p2p distance request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37851]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM.
3. Go to + > Request money > Distance.
4. Create a distance request.

## Expected Result:
The distance request is created successfully.

## Actual Result:
Error shows up when creating p2p distance request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/182c8297-ceac-4c43-b3f5-883eedf8e9e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave5-free-submitters
@dylanexpensify

**Comment by yuwenmemon** [comment]
Correct - assigning to @neil-marcellini to triage

**Comment by neil-marcellini** [comment]
Yep, not a blocker as [noted here](https://github.com/Expensify/App/pull/37185#issuecomment-1981690080). Thanks @neonbhai!

It will be fixed when the feature is fully implemented @kbecciv
