### ISSUE TITLE
[HOLD for payment 2024-03-25] [$500] Distance confirmation page shows (none) briefly when the map is loading

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37850]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Distance.
3. Enter addresses and select participants.
4. Proceed to confirmation page.

## Expected Result:
The Distance row will not show (none) when the distance data is loading (production behavior).

## Actual Result:
The Distance row shows (none) briefly when the distance data is loading.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/1d09d58d-bd6a-44ec-b29a-55d23f1c4dcf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0113e37a7ba3d78e1d</li>
        <li>Upwork Job ID: 1765826141463461888</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@cead22 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by paultsimura** [comment]
> This isn't a deploy blocker, the PR which made the title to `iouMerchant` was deployed to production 3 weeks back

@GandalfGwaihir to prove that an issue marked as a `blocker` is not a blocker, please attach a recording of the same issue happening in production.

**Comment by paultsimura** [comment]
I could reproduce it neither on dev nor staging 🤔 
Instead, I see "Route pending", which is expected while we're fetching the route or rate:

<img width="821" alt="image" src="https://github.com/Expensify/App/assets/12595293/b2ce8ca8-8f4f-49da-88cb-a736311091f4">

**Comment by cead22** [comment]
I don't think we should block deploys on this, so let's treat it as a regular bug

**Comment by cead22** [comment]
I was able to reproduce on staging wek v1.4.48-0 ![](http://g.recordit.co/GO4mqYLnGz.gif)

**Comment by cead22** [comment]
The good news is that we have plenty of open bugs and work for contributors :) and in the interest of assigning whoever posted first and being consistent with previous assignments I've done, I'm going to assign @usman-ghani564

**Comment by abekkala** [comment]
@usman-ghani564 Can you send me your upwork profile link, I'm having a hard time finding you.

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 25

- Fix: @usman-ghani564 [$500, if no regressions] [Offer](https://www.upwork.com/nx/wm/offer/101488565)
- PR Review: @aimane-chnaif [$500, if no regressions] [Offer](https://www.upwork.com/nx/wm/offer/101488632)

**Comment by abekkala** [comment]
@slafortune will be handling payments for me while I'm ooo

**Comment by slafortune** [comment]
Paid 👍
