### ISSUE TITLE
[HOLD for payment 2024-04-03] [$500] Collect approver - "Waiting for you to pay these expenses" is briefly displayed for approver

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37866]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- The Collect workspace has admin, employee and a non-reimburser approver.
- Workspace has direct reimbursement.

1. [Employee] Go to workspace chat.
2. {Employee] Create a manual request and submit it.
3. [Approver] Go to workspace chat with employee.
4. [Approver] Click on the expense preview to go to expense report.
5. [Approver] Click Approve.
## Expected Result:
The Next step message should only show "Waiting for your admin to pay these expenses".

## Actual Result:
The Next step message briefly shows "Waiting for you to pay these expenses" after approving the report, which is a message meant for reimburser.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a8bb2f83-e0c4-43fd-8922-b2b36ea1ec66

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126815d05bb2e844f</li>
        <li>Upwork Job ID: 1765765668601966592</li>
        <li>Last Price Increase: 2024-03-07</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@mallenexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave6-collect-submitters
cc @greg-schroeder

**Comment by dragnoir** [comment]
@m-natarajan @mallenexpensify any idea how to create a non-reimburser approver account?

**Comment by mallenexpensify** [comment]
@fedirjh this appears that it can be external, do you agree? If so, can you attempt reproduction then review the proposal above? Thx

**Comment by mallenexpensify** [comment]
@fedirjh , 👀 on the proposal above plz. 
Thx

**Comment by Gonals** [comment]
> Thanks everyone for the proposals. I am leaning towards @GandalfGwaihir proposal. It seems like a recent change to nextStep message was done in this PR:
> 
> * [[CP Staging] Update nextStep on payment cancellation #36798](https://github.com/Expensify/App/pull/36798)
> 
> cc @Gonals since you are the author of the PR. Should we proceed with [this proposal](https://github.com/Expensify/App/issues/37866#issuecomment-1986604092) ? The change is as follows:
> 
> ```diff
> diff --git a/src/libs/NextStepUtils.ts b/src/libs/NextStepUtils.ts
> index f03c34b169..13bf581ad8 100644
> --- a/src/libs/NextStepUtils.ts
> +++ b/src/libs/NextStepUtils.ts
> @@ -258,7 +258,7 @@ function buildNextStep(
>                          text: 'Waiting for ',
>                      },
>                      {
> -                        text: managerDisplayName,
> +                        text: 'you',
>                          type: 'strong',
>                      },
>                      {
> @@ -281,7 +281,7 @@ function buildNextStep(
>                          text: 'Waiting for ',
>                      },
>                      {
> -                        text: 'you',
> +                        text: managerDisplayName,
>                          type: 'strong',
>                      },
>                      {
> ```

Looks good to me!

**Comment by Beamanator** [comment]
Huh, @Gonals do youuuu wanna take over since you approved a proposal? 😅

**Comment by mallenexpensify** [comment]
@GandalfGwaihir @fedirjh , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0126815d05bb2e844f

@GandalfGwaihir , I sent you a new offer since you said you had trouble accepting the other. 
Thx

**Comment by mallenexpensify** [comment]
Contributor: @GandalfGwaihir paid $500 via Upwork
Contributor+: @fedirjh owed $500 via Upwork. 

@fedirjh can you please accept the job and reply here once you have?  It still shows the offer hasn't been accepted. 
https://www.upwork.com/jobs/~0126815d05bb2e844f

Testrail GH https://github.com/Expensify/Expensify/issues/385885

**Comment by mallenexpensify** [comment]
I think I just hired you @fedirjh and you need to confirm so I can pay, can you look https://www.upwork.com/jobs/~0126815d05bb2e844f

**Comment by mallenexpensify** [comment]
Paid @fedirjh , updated the payment confirmation above.  Thx
