### ISSUE TITLE
Amount validation is requested on Connect with Plaid after trying to add BA manually

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37865]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** couldn't check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and have created a workspace.

1. Go to Workspace > Bank account.
2. Select Connect manually.
3. Initiate the add bank account flow with the testing credentials until you reach the "Validate your bank account" page.
4. Click on the back arrow.
5. Click on "Start over".
6. Select Connect online with Plaid.
7. Select Regions bank and use the testing credentials.
8. Confirm the account.
9. Verify you land on "Validate your bank account" page.

## Expected Result:
The user should be able to continue with the add BA flow (enter Personal info, Company info, Beneficial owners).

## Actual Result:
The user is taken to "Validate your bank account" page after confirming the account.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/365b89bb-0d90-4b8d-b6b1-01db57d842d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@techievivek FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MitchExpensify** [comment]
Related? https://github.com/Expensify/App/issues/32356

**Comment by nkuoch** [comment]
It's a feature, not a bug.

Disconnecting from a policy when in PENDING or OPEN state doesn't remove it from the account anymore. It just detaches it from the policy. So, when re-entering the same bank account, you don't need to redo it all. It just attaches the existing one.

If you actually delete it from your account from your personal settings, you'll have to redo it all, as before.

**Comment by MitchExpensify** [comment]
@m-natarajan seeing as this is a feature not a bug, do you agree the TR steps need to be updated to avoid this being reported again?
