### ISSUE TITLE
[HOLD for payment 2024-03-25] [$500] [Wave Collect] [Categories] Categories - Not here page shows up when opening Parent/ and Parent/: Child category

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an admin of Collect workspace.
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Collect workspace.
3. Go to Categories.
4. Click Add category.
5. Add category in Parent/ and Parent/: Child format. And other special characters
6. Click on the created category.

## Expected Result:
Category RHP opens without issue.

## Actual Result:
Not here page shows up when opening category with Parent/ and Parent/: Child style.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/45c3f0ef-6569-438b-bdb7-eb4e42c3baf4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01425421b068a188c5</li>
        <li>Upwork Job ID: 1767873021149028352</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by kbecciv** [comment]
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by jliexpensify** [comment]
[Posted here](https://expensify.slack.com/archives/C036QM0SLJK/p1709873190742829)

I have reproduced.

**Comment by jliexpensify** [comment]
@tienifr - I haven't gotten any responses from my Slack post: basically, I'm not sure if we use/are planning to use Parent/Child styles in New Expensify.

**Comment by mountiny** [comment]
@tienifr and others, we would like to make sure this works with various special characters in the name of the category

**Comment by hungvu193** [comment]
Thanks for your proposal.
@tienifr 's proposal looks good to me. I checked other places that we used `encodeURI` inside url, most of them are static value.
There are 2 places that we're using `encodeURI` to encode the `source` but all of these are query param so it won't be a problem.
https://github.com/Expensify/App/blob/37a2dbb9dd5e89d61210feb0eb1de3a80cb6ca6d/src/ROUTES.ts#L207
https://github.com/Expensify/App/blob/37a2dbb9dd5e89d61210feb0eb1de3a80cb6ca6d/src/ROUTES.ts#L159


🎀 👀 🎀  C+ reviewed

**Comment by jliexpensify** [comment]
@hungvu193 @tienifr offers should be ready for you to accept now, cheers!

**Comment by jliexpensify** [comment]
Hi @mallenexpensify - I am OOO from the 21st to 31st March. Here is what needs to be done:

PAYMENT SUMMARY (25TH)

- C: @tienifr $500 (please accept offer)
- C+: @hungvu193 $500  (please accept offer + complete checklist)

[UPWORKS JOB](https://www.upwork.com/jobs/~01425421b068a188c5)

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37209
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37209/files#r1529785049
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.

**Regression test**:
*Precondition:*
*User is an admin of Collect workspace.*
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Collect workspace.
3. Go to Categories.
4. Click Add category.
5. Add category in Parent/ and Parent/: Child format. And other special characters
6. Click on the created category.
7. Verify that Category RHP opens without issue.

Do we 👍 or 👎

**Comment by luacmartins** [comment]
No need for regression tests. We'll add them as part of the design doc once the feature is fully implemented.

**Comment by mallenexpensify** [comment]
@tienifr @hungvu193 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01425421b068a188c5

**Comment by hungvu193** [comment]
> @tienifr @hungvu193 can you please accept the job and reply here once you have? 
> 
> https://www.upwork.com/jobs/~01425421b068a188c5
> 
> 

Accepted! Thank you

**Comment by mallenexpensify** [comment]
Contributor: @tienifr paid $500 via Upwork
Contributor+: @hungvu193 paid $500 via Upwork. 

TestRail GH created - https://github.com/Expensify/Expensify/issues/383897

Thanks!

**Comment by jliexpensify** [comment]
Thanks Matt, appreciate the assist!
