### ISSUE TITLE
IOU – Join button appears in IOU details page header when navigate via link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37884]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4396826
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to unpaid IOU details page.
4. Copy link.
5. Paste in another chat.
6. Log out.
7. Log in.
8. Click on the link.

## Expected Result:
Join button not appears in IOU details page

## Actual Result:
Join button appears in IOU details page header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3b8ca44a-3266-4149-8793-4d944b81c24d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by strepanier03** [comment]
Reviewing now, thank you for the patience 🙌

**Comment by strepanier03** [comment]
I'm not able to recreate this behavior, there is no Join button when following the steps as written and shown in the video. 

I'm also not convinced this is a behavior we would want to look into more or that it would happen frequently. 

I'm going to label as needs repro and close. We can always reopen in the future if we need to.
