### ISSUE TITLE
[HOLD for payment 2024-04-23] [$500] [Performance] Decouple draft state computation from report

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#37880]
## Problem

Whenever a user starts to type a new message in Composer, the hasDraft state inside current Report object needs to be updated. The state is later used in LHN to determine if a draft indicator (pencil icon) should be displayed.

Calculations performed by the app to acquire updated hasDraft state are costly. It is caused by the fact that the hasDraft state is a property of a Report object which is then part of the entire list of reports user has access to (14k on testing account). Change of a single report causes list to be invalidated, making costly calculations of getOrderedReportIDs inside SidebarLinksData (component that resides on top of LHN) to run again.

:exclamation: The getOrderedReportIDs calculations might take a few hundred ms, up to a few seconds depending on device and number of reports passed to the function. It is a severe execution overhead, considering how often user starts typing new message during regular conversation.

## Solution

The hasDraft state can be decoupled from Report object and stored as an individual entry (or list of entries for many reports) under separate Onyx key. Such a solution should help us avoid invalidating the entire list of reports on every new message being typed, thus not triggering costly re-calculation of getOrderedReportIDs.

In Onyx, the REPORT_DRAFT_COMMENT key exists and serves similar purpose as hasDraft. Considering how hasDraft is used (to display draft indicator) it should not be an issue to re-use REPORT_DRAFT_COMMENT key for such functionality. It is mostly an implementation detail, but this way we are reducing app complexity and state redundancy.

From : @kacper-mikolajczak [here](https://expensify.slack.com/archives/C05LX9D6E07/p1709036231433249)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012397339f4d656420</li>
        <li>Upwork Job ID: 1777386978362355712</li>
        <li>Last Price Increase: 2024-04-20</li>
    </ul>
</details>

**Comment by mountiny** [comment]
@kacper-mikolajczak can you comment here?

**Comment by kacper-mikolajczak** [comment]
Yessir!

**Comment by kacper-mikolajczak** [comment]
Melvin, PR was merged already

**Comment by mountiny** [comment]
I am fine with the price as it was complex change and it was made before the price change too.

$500 to @shubham1206agra once ready @dylanexpensify

**Comment by dylanexpensify** [comment]
@shubham1206agra sent invite to apply!

**Comment by dylanexpensify** [comment]
@shubham1206agra offer sent!

**Comment by dylanexpensify** [comment]
Done!
