### ISSUE TITLE
Tag - "Required" shows up regardless of the state of independent tag requirement

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37893]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has independent multilevel tags.
- Some multilevel tags are not set to required.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to FAB > Request money > Manual.
4. Proceed to confirmation page.
## Expected Result:
"Required" will not show up for tags that are not set to required.

## Actual Result:
"Required" shows up for tags that are not set to required.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1238d575

[Bug6405338_1709813668521!uploads_1618929581886-Independent_with_GL_codes_format_-_Sheet1.csv](https://github.com/Expensify/App/files/14524877/Bug6405338_1709813668521.uploads_1618929581886-Independent_with_GL_codes_format_-_Sheet1.csv)
-076a-4f99-b7b4-c20dc7dc0d0d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@twisterdotcom FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by twisterdotcom** [comment]
>The Collect workspace has independent multilevel tags.

We are getting rid of these I think. I don't think this is a bug right now as it's still being implemented. Going to close, but one of the people I tag below can correct me if I'm wrong.

cc @hayata-suenaga, @aldo-expensify and @zanyrenney.

**Comment by hayata-suenaga** [comment]
cc: @luacmartins for confirmation ⬆️ 🙇

**Comment by luacmartins** [comment]
Yea, we won't support manually set multi-level tags on collect anymore.
