### ISSUE TITLE
[$2500] Payment issue for @allroundexpets for Report Fields design doc 

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#37906]
@allroundexperts wrote the [technical section of the design doc for Report Fields](https://docs.google.com/document/d/1LXGXwWsei-Zx2wJMaYBmVe_M8NH7AHJZ5bIqwSec4uo/edit)

@thienlnam and I [in #bug-zero ](https://expensify.slack.com/archives/C01SKUP7QR0/p1708473524634499)what the compensation should be and agreed on $2500.

**Comment by mallenexpensify** [comment]
@allroundexperts can you comment so I can assign to you?

**Comment by allroundexperts** [comment]
Hi!

**Comment by mallenexpensify** [comment]
Thanks @allroundexperts , it might day a day or so to pay due to accounting requirements for the design doc creation.

**Comment by allroundexperts** [comment]
That's fine. Thanks!

**Comment by mallenexpensify** [comment]
Got feedback from the accounting team [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1709832434020199?thread_ts=1708473524.634499&cid=C01SKUP7QR0). Added the `NewFeature` label.  This needs to go through our normal payment process so I'm adding another post below specific to that.

**Comment by mallenexpensify** [comment]
Contributor+: @allroundexperts due $2500 via NewDot

**Comment by JmillsExpensify** [comment]
$2,500 approved for @allroundexperts based on summary.
