### ISSUE TITLE
Self DM - Stacked avatar in thread header from self DM shows "Unavailable workspace"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Search.
3. Search for yourself and open self DM.
4. Send a message in self DM.
5. Right click on the message > Reply in thread.

## Expected Result:
The thread header will not show "Unavailable workspace" since it is not related to workspace chat.

## Actual Result:
The stacked avatar in thread header shows "Unavailable workspace".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8784a9d3-3f8c-47e0-8d1a-4b47de9ca5c2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by thienlnam** [comment]
Yeah, looks like it was related to that - going to close

**Comment by kbecciv** [comment]
QA team is able to reproduce the issue on build 1.4.50.2, reopening!

https://github.com/Expensify/App/assets/93399543/f48072a6-5368-44a6-adf5-385042ae31f5

**Comment by thienlnam** [comment]
The video looks like correct behavior - I don't see "Unavailable workspace" anymore

**Comment by anmurali** [comment]
<img width="1442" alt="image" src="https://github.com/Expensify/App/assets/14225673/a602804d-6e5c-4637-91bc-f7c654274c32">
I can't really even get self DM to open to reproduce this. @thienlnam how did you reproduce this?

**Comment by thienlnam** [comment]
Try searching for your email / name instead in the chat searcher - you can't find your DM by creating a chat with yourself, though we should add that for polish

**Comment by anmurali** [comment]
<img width="1176" alt="image" src="https://github.com/Expensify/App/assets/14225673/f486ddec-ff1d-4d7f-9103-f2252bc6a574">
 Yes, cannot reproduce.
