### ISSUE TITLE
[HOLD for payment 2024-04-05] Support light mode on help.expensify.com and match user's system preferences

### ISSUE THREAD

**Issue by sakluger** [Expensify/App#37911]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Slack conversation:** https://expensify.slack.com/archives/C02QSAC6BJ8/p1709831844030329

## Problem

Our help site (help.expensify.com) contains many large blocks of text. Currently we only support dark mode for the help site, but it's difficult for many people (including me) to read large blocks of light text on a dark background. Here's an example of what this looks like today:

<img width="1334" alt="image" src="https://github.com/Expensify/App/assets/5997400/2ce89572-2891-4626-a23c-148cfabbe27f">

## Proposed solution

Let's support light mode on our help site. Instead of adding a togglable setting, we can just match the user's system preferences for light mode vs dark mode.

@shawnborton gives some suggestions and advice around implementation in the [Slack thread](https://expensify.slack.com/archives/C02QSAC6BJ8/p1709831844030329).

**Comment by rushatgabhane** [comment]
Support for CSS prefers-color-scheme looks good. https://caniuse.com/prefers-color-scheme

<img width="1396" alt="image" src="https://github.com/Expensify/App/assets/29673073/c91b6e65-4283-4c62-a9d4-e231b142d070">

**Comment by sakluger** [comment]
Looks great, thanks again @rushatgabhane! Feel free to request via NewDot using the [payment summary](https://github.com/Expensify/App/issues/37911#issuecomment-2040355560) above.
