### ISSUE TITLE
[$250] [Performance] Limit getReportName to first 5 participants

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#37925]
## Problem:

In some cases, when the number of participants is big, we were needlessly calculating getDisplayNameForParticipant where in the end, we wouldn't be able to display it since the output is trimmed afterwards anyways.

## Solution

The number of participants used to determine the Report name via getReportName is limited to first 5 participants other than current user.

This change allows to cap the performance impact of getReportName  (which is used within getOrderedReportIDs)

from here: https://expensify.slack.com/archives/C05LX9D6E07/p1709831181822099 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bcaa1758a6b23688</li>
        <li>Upwork Job ID: 1766057020696662016</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by deetergp** [comment]
I think we can close this one, since it appears the actual limiting of the names is being done on https://github.com/Expensify/App/issues/38052. A PR for it is currently under review: https://github.com/Expensify/App/pull/38568.

**Comment by deetergp** [comment]
@muttmuure I think we owe @mollfpr for review of https://github.com/Expensify/App/pull/37907 before we can close this out.

**Comment by mollfpr** [comment]
@deetergp I think I'll request the compensation here https://github.com/Expensify/App/issues/38009. We can close this.

**Comment by deetergp** [comment]
Okay @mollfpr, thanks!
