### ISSUE TITLE
Workspace - Grammar error "You\’ve got" in the guide welcome message in #admins room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Create a Collect policy in OD with a new Gmail account
1. Log into ND as the admin of the workspace
2. Open the #admins room

## Expected Result:
It should be "You’ve got".

## Actual Result:
Grammar error "You\’ve got" in the guide welcome message in #admins room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/ac91176b-5a92-4eda-a559-02bfc417fd37)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173a652400f6b043b</li>
        <li>Upwork Job ID: 1767171306650935296</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment]
I'd fix this myself but I'm not seeing what's wrong. The other instances of `\'` are rendering correctly. @kbecciv @shubham1206agra any ideas on what's causing the incorrect render? 

[Code](https://github.com/Expensify/Web-Expensify/blob/a30baabe18b61a90bbc634a9a260e66313ed140d/script/bwm/SendAssignedGuideMessaging.php#L19)
```
private const ASSIGNED_GUIDE_DM_MESSAGE = '<h1>Let\'s get you setup on Expensify</h1>Hi there 👋 , I\'m your dedicated setup specialist. I look forward to helping you explore and configure Expensify. A few important things to mention: <br/><ul><li>You\'re on a 7-day free trial, but I can help extend that if you\'re interested.</li><li>Your workspace has a ton of custom settings, just select your workspace settings to set it up.</li><li>You\’ve got more functionality to enable, like custom categories, tags, etc. Just ask me how. </li></ul>Chat with me here in your #admins room or just reply to this message. You can also schedule a call if you have more in-depth questions. Talk soon!';
```

**Comment by sonialiap** [comment]
cc @Gonals since you were the last to update this line

**Comment by sonialiap** [comment]
The devil's in the details 😆 thanks for pointing that out

**Comment by sonialiap** [comment]
Not overdue, in process

**Comment by sonialiap** [comment]
Fixed
