### ISSUE TITLE
[HOLD - #374470] Thread header and LHN for task assignee system message is missing the assignee

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37939]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** NO - new feature (system message)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Create a task.
4. Go to task report.
5. Click Assignee.
6. Add an assignee (or change assignee).
7. Right click on assignee system message > Reply in thread.

## Expected Result:
The thread header and LHN title will show assignee name.

## Actual Result:
The thread header and LHN title do not show assignee name.

Also, The email in system message is also not copied when copied to clipboard.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/95d8bd56-c3da-4238-b00e-c21193ce2fc8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@marcaaron FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb. cc @quinthar

**Comment by marcaaron** [comment]
I am thinking if this is a new feature then we probably don't need to make this a blocker.

**Comment by roryabraham** [comment]
> I am thinking if this is a new feature then we probably don't need to make this a blocker

I think we should treat this as a blocker, because it's available to any new user and looks pretty obviously broken

**Comment by marcaaron** [comment]
Cool. These are the PRs related to tasks...
 
https://github.com/Expensify/App/pull/37991
https://github.com/Expensify/App/pull/36768 <- this looks like something new
https://github.com/Expensify/App/pull/35484

@thienlnam might know which one this could be related to?

I am still leaning towards non blocker because creating a thread off a system message seems like a weird action for a user to take. And I'm not sure how that should work at all. 🤔

**Comment by strepanier03** [comment]
> I am still leaning towards non blocker because creating a thread off a system message seems like a weird action for a user to take.

I agree with this. I don't think a customer would create a thread off a system message. If they questioned it, they'd like be making a new comment after the system message instead of threading off it. I don't think this is a blocker either.

**Comment by roryabraham** [comment]
Well I don't feel that strongly but it seems to me that a system message is a message so should work just like any other 🤷🏼

**Comment by thienlnam** [comment]
Oh, this looks related to this issue https://github.com/Expensify/App/issues/38000.

This [PR](https://github.com/Expensify/App/pull/36768) added the system messages, so now you have the ability to thread from them.

I also agree this shouldn't block deploy -  it kind of relies on you creating a task, changing the assignee and then deciding to thread off the system message which doesn't seem that common in the first place

**Comment by roryabraham** [comment]
sounds like there's more votes in favor of demoting this. I do think creating a thread off a system message should work, but agree it's an edge case so doesn't necessarily need to block deploy.

**Comment by paultsimura** [comment]
If this is not urgent – I would recommend putting this on hold for https://github.com/Expensify/Expensify/issues/374470 similar to how we did with https://github.com/Expensify/App/issues/37943 – that PR should introduce a more robust `originalMessage` to the `TASKEDITED` report actions, and it will allow building the thread name without workarounds (like parsing the message etc.)

**Comment by mountiny** [comment]
Demoting based on the discussion above.

**Comment by strepanier03** [comment]
On Hold for #374470.

**Comment by strepanier03** [comment]
Hold PR is still open.

**Comment by marcaaron** [comment]
I see this issue is on HOLD and waiting for #374470, but also see that #374470 has not had much progress. Should we continue to leave this open? 🤔

**Comment by marcaaron** [comment]
@thienlnam any chance you can give us an ETA on when those changes might be live? We could adjust the priority here based on that. Thanks!

**Comment by strepanier03** [comment]
@thienlnam - Any chance you have an eta on those changes?

**Comment by thienlnam** [comment]
Ah sorry, didn't see this. I'm not working on those at this time since they're not part of a release. I would throw a monthly on this until we decide to reprioritize

**Comment by strepanier03** [comment]
Sounds good, thanks for the context and advice.

**Comment by marcaaron** [comment]
Going OOO so gonna unassign this one for now. This one has been open for a while and there's not really anything actionable for me to do here.

**Comment by strepanier03** [comment]
Not prioritized right now.

**Comment by strepanier03** [comment]
Not prioritized currently.

**Comment by strepanier03** [comment]
Updating project as VSB was closed.
