### ISSUE TITLE
Workspace member list goes blank briefly after removing workspace member

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37944]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** n/a this is a new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is owner of Collect workspace.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Collect workspace.
3. Go to Member.
4. Click on any member.
5. Click Remove from workspace.
6. Click Remove.

## Expected Result:
Workspace member list will not go blank after removing workspace member.

## Actual Result:
Workspace member list goes blank briefly after removing workspace member.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/253d433e-b834-4300-bd85-c11fb633751a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@adelekennedy FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by dragnoir** [comment]
@GandalfGwaihir the `backTo` is used in `removeUser`  and in `navigationBack`

https://github.com/Expensify/App/blob/86a990428df2c923ed4ebc291c0a3a73653cb7fe/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L50

fixing only `removeUser` will lead the navigation back to the same issue.

Also Navigation.goBack(); is the same as I mentioned 

> we need to fix the backTo to undefined.

You have added nothing here !!!

**Comment by adelekennedy** [comment]
closing this - this is a "blink and you'll miss it" bug and we are focused on our roadmap

**Comment by dragnoir** [comment]
@adelekennedy I agree with you. It's a "blink and you'll miss it" bug but it causes the reload of all the interface causing lots of heavy tasks on the UI.
