### ISSUE TITLE
By clicking on highlighted WS user, the checkbox is not selected or opening the details of the member

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37942]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into an account
3. Create a workspace
4. Go to WS settings and add members
5. Tap on the users highlighted name

## Expected Result:
User expects the checkbox to highlight when the user selects the name, or a redirect

## Actual Result:
The checkbox does not highlight when the user clicks on the members name, clicking on the name "highlights" as if something should happen, but nothing does.
NOTE : In production checkbox getting selected
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/b076c42e-41eb-402d-8b8f-fa9ce8a2b8c7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@marcaaron FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by ahmedGaber93** [comment]
I think it is related to #37715 and will fix in a follow up issue #37927.
to fix this we need to navigate to user profile on item click and keep select by checkbox only by add `Navigation.navigate(ROUTES.PROFILE.getRoute(item.accountID));` before return [here](https://github.com/Expensify/App/blob/9132e058fe27119906e027579ea9b36be5a57400/src/pages/workspace/WorkspaceMembersPage.tsx#L265-L267)

**Comment by marcaaron** [comment]
cc @luacmartins @burczu

**Comment by marcaaron** [comment]
@ahmedGaber93 I don't see this issue in that list so assuming this is a blocker unless @luacmartins says otherwise.

**Comment by ahmedGaber93** [comment]
@marcaaron 
I think it is the No. 1
> Navigate to global profile if not an admin of paid policy. We shouldn't just early return [here](https://github.com/Expensify/App/blob/18d88eff913698bbac32889fa20e3cdb286b4079/src/pages/workspace/WorkspaceMembersPage.tsx#L265-L267), instead let's navigate the admin of a free policy to the global profile, like we do [above](https://github.com/Expensify/App/blob/18d88eff913698bbac32889fa20e3cdb286b4079/src/pages/workspace/WorkspaceMembersPage.tsx#L260-L263).

**Comment by luacmartins** [comment]
Yes, that's the first issue. The policy in the test video is a free policy (we can tell by the pages that are visible), so we just have an early return there. I can work on a quick fix.

**Comment by luacmartins** [comment]
This is done and CPed

**Comment by luacmartins** [comment]
Tested in staging, it's a pass!

**Comment by luacmartins** [comment]
This feature is still a WIP so I don't think we need to worry about the checklist above now. We're addressing all these issues in follow ups.
