### ISSUE TITLE
[HOLD for payment 2024-03-19] [$500] IOS - Workspace-user is not redirected to all workspaces screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37958]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** N
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37525
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
1. Has a workspace (new or existing one)
2. Prepare join url link - use WorkspaceID and admin email for that workspace - ex. https://staging.new.expensify.com:8082/workspace/7DE6960B26D79E36/join?email=tenema5675@bizatop.com
Steps:
As the user:
1. Paste the link in any chats
2. Click on the link

## Expected Result:
User should be redirected to all workspaces screen

## Actual Result:
User is not redirected to all workspaces screen instead is redirected to settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7ea0ec98-1b64-43fd-ac6f-1c335ad5c7da

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a85c55b78271db7</li>
        <li>Upwork Job ID: 1766091385665871872</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by narefyev91** [comment]
will take it

**Comment by mountiny** [comment]
Follow up to @narefyev91 PR assigning, its a new feature so demoting

**Comment by mountiny** [comment]
no further action required here
