### ISSUE TITLE
Workspace-No message to accept or decline is shown on admin room unless relogin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37960]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37525

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Preconditions:
1. Has a workspace (new or existing one)
2. Prepare join url link - use WorkspaceID and admin email for that workspace - ex. https://dev.new.expensify.com:8082/workspace/7DE6960B26D79E36/join?email=tenema5675@bizatop.com

For user:
1. Open link in a new tab (for a new user / or user which already logged in)

For Admin:
1. When user used join link go to admin room and look for a message
2. Sign out and re login again and go to admin room

## Expected Result:
Admin should see a message to accept or decline the joining request without re logging in

## Actual Result:
No message comes through unless admin re logins

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/01a17072-f03a-4b37-b464-11cb121ddfe5

https://github.com/Expensify/App/assets/115492554/19b265c8-9134-45ad-be3f-f2551eb89a8d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@grgia I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by twisterdotcom** [comment]
@izarutskaya I tried this and I can't recreate: 

https://github.com/Expensify/App/assets/9133401/ec3e0410-cb99-4978-a3e1-de4a4b4562c9

**Comment by twisterdotcom** [comment]
Going to close this as it seems to be working fine.
