### ISSUE TITLE
[HOLD for payment 2024-03-19] [HOLD for payment 2024-03-18] IOU - App crashes when navigate to IOU created offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/20153&group_by=cases:section_id&group_order=asc&group_id=229063
**Email or phone of affected tester (no customers):** applausetester+gm88@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Disable the internet connection in the device
2. Click on FAB > Request Money
3. Create a money request with an user you had no previous conversation before
4. Navigate to IOU report

## Expected Result:
App should no crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5538cef0-7439-4c26-8e96-d0b51d5db42c

[Bug6406776_1709895252510!staging.new.expensify.com-1709895198140.txt](https://github.com/Expensify/App/files/14537926/Bug6406776_1709895252510.staging.new.expensify.com-1709895198140.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@flodnv I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by situchan** [comment]
null is added at the end of `policyReportFields`, which makes crash

<img width="608" alt="Screenshot 2024-03-08 at 6 30 14 PM" src="https://github.com/Expensify/App/assets/108292595/355c8196-8785-4b18-a016-1da31e61fbb1">

**Comment by flodnv** [comment]
Thanks @situchan ! cc @kubabutkiewicz https://github.com/Expensify/App/pull/34487#pullrequestreview-1924803948

**Comment by luacmartins** [comment]
PR merged and CP requested

**Comment by luacmartins** [comment]
Tested in staging and it's a pass. Removing blocker label and bumping to daily to process payment

**Comment by situchan** [comment]
BZ Checklist:

Offending PR with comment: https://github.com/Expensify/App/pull/34487#pullrequestreview-1924803948
This came from TestRail - https://expensify.testrail.io/index.php?/runs/view/20153&group_by=cases:section_id&group_order=asc&group_id=229063
No need regression test

**Comment by laurenreidexpensify** [comment]
@situchan - pls apply in upwork https://www.upwork.com/jobs/~014c27873609e6c40b

**Comment by laurenreidexpensify** [comment]
@luacmartins @flodnv can you confirm the C+ fee here, is it just $500 for one PR review?

**Comment by luacmartins** [comment]
@laurenreidexpensify this was a regression from https://github.com/Expensify/App/pull/34487, which was implemented by Callstack and had Rushat as C+. The [fix PR linked to this issue](https://github.com/Expensify/App/pull/37985) was also authored by Callstack, but @situchan reviewed it as C+. I'm not sure how we process payment in this case.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ review https://github.com/Expensify/App/pull/37985 $500 @situchan please apply in Upwork thanks

**Comment by situchan** [comment]
@laurenreidexpensify applied thanks

**Comment by laurenreidexpensify** [comment]
Thanks - once you accept will issue payment 👍

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ Review $500 @situchan paid in Upwork
