### ISSUE TITLE
[HOLD for payment 2024-03-19] Clicking on invite link for the second time via chat does not open All workspaces

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37962]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37525

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Precondition:
- The invite link to workspace is [https://staging.new.expensify.com/workspace/<Workspace_ID>/join?email=<admin_email>](https://staging.new.expensify.com/workspace/%3CWorkspace_ID%3E/join?email=%3Cadmin_email%3E)

1. Go to staging.new.expensify.com as non-member.
2. Paste the invite link in any chat (or have someone share the link via chat).
3. Click on the invite link.
4. Return to chat.
5. Click on the invite link again.

## Expected Result:
User will be redirected to All worksapces page.

## Actual Result:
A different chat opens when clicking on the invite link for the second time.
This issue also occurs when user opens invite link to another workspace after opening the first invite via chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1a3f2c64-4dc9-4327-9629-0613438c6199

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@iwiznia I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by garrettmknight** [comment]
I don't think this needs to be a blocker. This issue is actively being built and not in the hands of users. I'll defer to @iwiznia on whether it needs to be `Internal` or not though.

**Comment by narefyev91** [comment]
Will take it

**Comment by garrettmknight** [comment]
@narefyev91 do you have any tests for this made up or do you think we need to add one?

**Comment by narefyev91** [comment]
> @narefyev91 do you have any tests for this made up or do you think we need to add one?

It was some missing functionality - i will say no other interaction needed here

**Comment by garrettmknight** [comment]
Cool, closing
