### ISSUE TITLE
Setting expense rule for tag is not showing respective tag

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
Pre-condition: As employee, in old dot create expense rule for categories first as - test and for tags second as - test1 ( first, second order is important)
Note: While creating expense rule for category enter "test" in both "when the merchant name contains" and in the "merchant" field under apply these changes to the expense. Similarly for tags enter "test1" in both places.( Image attached below)
1. Go to https://staging.new.expensify.com/

2. Login as employee of collect workspace
3. Click on employee workspace chat
4. Click plus icon -- request money -- manual
5. Enter an amount and tap next
6. Enter merchant - test1
7. Click request
8. Open the newly created expense to view details page

## Expected Result:
Setting expense rule for tags must show respective tag if merchant is set to test1.

## Actual Result:
Setting expense rule for tags is not showing respective tag if merchant is set to test1.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6406340_1709863666562!v](https://github.com/Expensify/App/assets/38435837/3dad2536-8d67-4ae8-8eb4-8e8698e7366c)

https://github.com/Expensify/App/assets/38435837/3422b9cd-548c-4d1c-ba30-04df33f962b1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@anmurali FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave6-collect-submitters

**Comment by anmurali** [comment]
Not sure if we have actually built expense rules into ND. Asking [here](https://expensify.slack.com/archives/C036QM0SLJK/p1710338675239609)

**Comment by anmurali** [comment]
From [thread in Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1710804621029519?thread_ts=1710338675.239609&cid=C036QM0SLJK), we have not decided the fate of personal expense rules on ND yet. So I am closing this bug for now.
