### ISSUE TITLE
Chat – Offline created chat disappear when come back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37988]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+balto807@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to New Dot app
2. Turn off the internet connection
3. Go to FAB> New chat> Enter email address> Finish the new chat flow
4. Enter any text on chat composer and send the message
5. Turn on the internet connection
6. Go to LHN

## Expected Result:
Created chat should be present on LHN

## Actual Result:
Offline created chat disappear from LHN and Search when come back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f372f7b5-7907-466e-8700-8b3590c18e62

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kadiealexander** [comment]
@jliexpensify and I have an agreement to swap android and iOS bugs.

**Comment by jliexpensify** [comment]
Unable to repro on Android app (Pixel 3a) v1.4.51-3 after multiple attempts

Closing
