### ISSUE TITLE
[HOLD 374470]Task - System message does not appear for user B when editing task until page refreshed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37994]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in as the user A
2. Log in as the user B in incognito or another device
3. [user A] Open the chat with user B
4. [user A] Assign a task to user B
5. [user B] Open the assigned task
6. [User A] Change the title, description, or assignee

## Expected Result:
The system message is displayed for user B at the same time as for user A

## Actual Result:
The system message is displayed for user B after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b2e7db7e-782a-4c85-bf13-869942c1bc5f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by roryabraham** [comment]
This smells like a back-end issue to me

**Comment by luacmartins** [comment]
Yea, I agree just wanna confirm since @thienlnam worked on that related App PR

**Comment by paultsimura** [comment]
> @thienlnam is this related to https://github.com/Expensify/App/pull/36768?

This looks like a BE Pusher issue (not 100% sure though and can't verify ATM), there is quite a lot `taskedited`-related BE changes pending, @thienlnam should have a tracking issue for them🤔

**Comment by thienlnam** [comment]
Yes, this looks related to the pusher update not getting sent for the new EditTask reportAction - in any case this is not a blocker
