### ISSUE TITLE
[HOLD for payment 2024-03-22] [HOLD for payment 2024-03-20] Update several hubs on HelpDot

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#37990]
### Instructions - [HERE](https://github.com/Expensify/App/tree/main/docs#welcome-to-the-expensify-help-site)
We need to update the names of several hubs on HelpDot + update the associated descriptions: 
1. `Manage Employees & Report Approvals` to `Copilots & Delegates`
2. `Get Paid Back` to `Expenses`
3. `Expense & Rerpot Features` to `Reports`
4. `Workspace & Domain Settings` to `Workspaces`
5. `Billing & Subscriptions` to `Expensify Billing`
6. And then we need to create a brand new hub for `Domains`

### Copilots & Delegates
New description: Assign Copilots and delegate report approvals.

### Expenses
New description: Learn more about expense tracking and submission. 

### Reports
New description: Set approval workflows and use Expensify’s automated report features.

### Workspaces
New description: Configure rules, settings, and limits for your company’s spending.

### Expensify Billing
New description: Review Expensify's subscription options, plan types, and payment methods.

### Domains
New description: Claim and verify your company’s domain to access additional management and security features.
New icon:

**Comment by allroundexperts** [comment]
I get paid via ND so a payment summary should be enough.

**Comment by dannymcclain** [comment]
Here's the icon for the `Domains` hub (decided [here](https://expensify.slack.com/archives/C02QSAC6BJ8/p1709915463805859)): [simple-illustration__laptop-globe.svg.zip](https://github.com/Expensify/App/files/14541148/simple-illustration__laptop-globe.svg.zip)

And here's a little mock to show it in context:
![CleanShot 2024-03-08 at 11 09 20@2x](https://github.com/Expensify/App/assets/7516624/3f130c90-f90a-4321-ab02-6496051ac954)

> [!NOTE]
> The mock above is for visualizing the domains hub card only. The other content in the mock may very well be wrong.

**Comment by maddylewis** [comment]
@allroundexperts - lmk once you've requested payment via NewDot and i will close this out 👍

**Comment by allroundexperts** [comment]
All done. Free feel to close.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
