### ISSUE TITLE
WS chats are not archived when Offline, delete WS on another device and go back Online

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38003]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4411350
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Login in two devices with the same account
3. In main device go to settings/WS and create New WS
4. Open WS chats and go Offline
5. In a second device delete WS
6. In main device go back Online

## Expected Result:
WS chats are archived.

## Actual Result:
WS chats are not archived when in main device go offline, delete WS on another device and go back online.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b987ed0f-cd4e-426c-8afc-c7f6a678ccd4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@amyevans FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by amyevans** [comment]
I'm not able to repro (v1.4.49-3):

https://github.com/Expensify/App/assets/7277067/0a3be482-e43a-4379-ad33-b7c1179b295f

@adelekennedy mind giving it a shot?

**Comment by adelekennedy** [comment]
same @amyevans

**Comment by mountiny** [comment]
@m-natarajan @kavimuru Can you please check this with your team if this is still repro and what platforms its repro on?

**Comment by amyevans** [comment]
Pinged in QA channel: https://expensify.slack.com/archives/C9YU7BX5M/p1710168447063499

**Comment by amyevans** [comment]
QA [confirmed](https://expensify.slack.com/archives/C9YU7BX5M/p1710169098567929?thread_ts=1710168447.063499&cid=C9YU7BX5M) no longer reproducible, closing


https://github.com/Expensify/App/assets/7277067/f636a5a5-0d05-4817-85bb-81d20235c7da
