### ISSUE TITLE
[Awaiting Payment 15th April] [$250] [Wave Collect][QBO] Implement a new action to update the accounting connection configuration

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#38005]
Implement a new action function that updates the accounting connection configuration.

[Relevant section of the QBO design doc](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit#bookmark=id.w8zxnzjc4wlm).

The requirements for this function has changed since the doc was written.

- Rather than accepting a pair of the setting name and the new value, use a partial configuration object for the updated setting value to handle nested configuration fields.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01882bc59351c6ebce</li>
        <li>Upwork Job ID: 1768351574538891264</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by sakluger** [comment]
@hayata-suenaga it looks like @paultsimura has a question on the [linked PR](https://github.com/Expensify/App/pull/38006). And just to confirm, should we be paying the standard $500 for their PR review?

**Comment by hayata-suenaga** [comment]
> it looks like @paultsimura has a question on the https://github.com/Expensify/App/pull/38006.
Answered the question in the PR 🙇 

@sakluger since there won't be testing, we can do $250

**Comment by hayata-suenaga** [comment]
Changing the priority back to daily

PR review is ongoing. I addresses reviews today

**Comment by hayata-suenaga** [comment]
The PR is still being reviewed

**Comment by trjExpensify** [comment]
Yeah, I think that's reasonable. You weren't to know. @sakluger please proceed with $250 payout. Thanks!

**Comment by sakluger** [comment]
@paultsimura I've sent you an offer here: https://www.upwork.com/nx/wm/offer/101873920. Please let me know once you've accepted the offer.

**Comment by sakluger** [comment]
All paid, thanks!
