### ISSUE TITLE
Task - Task preview in Search shows incorrect message owner when task is assigned to self

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38000]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4410340
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User A and User B are in the same group chat.

1. [User A] Create an unassigned task in the group chat.
2. [User B] Go to the task report.
3. [User B] Click assignee and assign to User B.
4. {User B] Navigate back to group chat.
5. [User B] Reopen the task report.
6. [User B] Click Search.

## Expected Result:
The preview for task report in Search for User B will display "User B: Assign to" since User B assigns the task to themselves.

## Actual Result:
The preview for task report in Search for User B displays "User A: Assign to" when User B assigns the task to themselves.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/422706e3-9b87-46f3-b6ca-6178ed8d1fff

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by francoisl** [comment]
[Discussed](https://expensify.slack.com/archives/C01GTK53T8Q/p1709923474872809) with @thienlnam, this is most likely at least partially backend-related so we're not going to block the deploy on this. Jack has an [internal list](https://github.com/Expensify/Expensify/issues/374470) of backend changes to make for tasks, we'll list this one there too.

**Comment by francoisl** [comment]
Going to close this for now as it's already tracked in the issue linked above.
