### ISSUE TITLE
[Profile] Web - Joined workspace which is pending for approval disappears after relogin

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38008]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49.0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- The invite link to workspace is [https://staging.new.expensify.com/settings/workspaces/<Workspace_ID>/join?email=<admin_email>](https://staging.new.expensify.com/workspace/%3CWorkspace_ID%3E/join?email=%3Cadmin_email%3E)
Example: https://staging.new.expensify.com/settings/workspaces/51C70B8D97474AA5/join?email=applausetester+kh070307@applause.expensifail.com
1. [Employee] Click on the invite to join the workspace.
2. [Employee] After the workspace shows up in All workspaces page, log out.
3. [Employee] Log in again and go to All workspaces page.

## Expected Result:
Joined workspace which is pending for approval should be visible after relogin

## Actual Result:
Joined workspace which is pending for approval disappears after relogin

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5daa81ff-6eca-4acc-ae0f-5ba297bf49f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b6b769a86dd06b0</li>
        <li>Upwork Job ID: 1767247956971724800</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by dragnoir** [comment]
Can't reproduce. I think it's a BE and already fixed.

**Comment by luacmartins** [comment]
This seems like a backend issue too. We're probably not sending the policy data for non-member back to the user on OpenApp.

**Comment by luacmartins** [comment]
I'm gonna add the `Hot Pick` label here. @tgolen feel free to remove it if you wanna take this on.

**Comment by kevinksullivan** [comment]
No update, in hot picks waiitng for a volunteer.

**Comment by luacmartins** [comment]
@amyevans we renamed those routes in [Ideal Nav v2](https://github.com/Expensify/App/pull/37421), so the correct url is `/settings/workspaces/<policyID>/join?email=<inviterEmail>`

**Comment by luacmartins** [comment]
It seems like the issue comes from the API not sending data for the join requests.

**Comment by luacmartins** [comment]
Hmm I think the solution for this one might be a bit involved, since we currently only store the join requests in the policy object, so we'd have to query all policies in the DB to find which ones have a join request from a particular user 😅 I think we'd have to solve this by introducing a new NVP and also storing join requests on the user account level.

**Comment by luacmartins** [comment]
I'll work on this one

**Comment by luacmartins** [comment]
Discussing [here](https://expensify.slack.com/archives/C03TQ48KC/p1711572648545819)

**Comment by luacmartins** [comment]
As discussed in the thread above, we decided to :do-nothing: given that we:

1. Don't display anything to users in OldDot besides the growl
2. Users never asked us for this feature
3. Low usage of this flow
4. We currently show the pending requests, but users would have to log out / in to not see it again

Feel free to reopen if you feel differently.
