### ISSUE TITLE
 Desktop - Login - Expired magic code for a code, inability to exit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38011]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4409253
**Email or phone of affected tester (no customers):** rybkina+030824fish@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a new account on the Expensify desktop app and press Continue
2. Copy the Magic link and change it to staging
3. Open a new tab and navigate to the staging magic link

## Expected Result:
The user is prompted to open the desktop app. Click on the open app option. The user should be logged in with the new account on the Desktop App

## Actual Result:
The user is prompted to open the desktop app. Click on the open app option. The user should be logged in with the new account on the Desktop App

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3aa3b2ec-876f-4dc6-acd7-5f1dc1c59a58

<img width="1196" alt="Bug6407101_1709913249301!Screenshot_2024-03-08_at_09 44 46" src="https://github.com/Expensify/App/assets/78819774/160f2b24-4657-4fe3-92ba-5b55d7b3fded">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lschurr** [comment]
I was able to reproduce this.

**Comment by lschurr** [comment]
It sounds like this bug has only been tested on Staging, is that correct @lanitochka17? Are you able to reproduce in prod?

**Comment by lschurr** [comment]
Closing this as an edge case that doesn't fit with our roadmap projects and likely isn't something a customer will run into.
