### ISSUE TITLE
[HOLD for payment 2024-04-15] [Violations] [$500] Multilevel tags - "no longer valid" violation is shown after selecting all the tags

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspaces that have independent and dependent multilevel tags.
- Tag requirement is toggled on.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request without tags.
4. Go to request details page.
5. Select all the tags.

## Expected Result:
Tag violation will disappear after selecting the tags.

## Actual Result:
After selecting all the tag, the last tag shows "no longer valid".

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/01c2b3a5-b267-49c2-86dd-3e6462759487

[Bug6409633_1710163006169!independant_tag.csv](https://github.com/Expensify/App/files/14559819/Bug6409633_1710163006169.independant_tag.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e30e5ceb96930999</li>
        <li>Upwork Job ID: 1767604738588979200</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@grgia  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #wave6-collect-submitters. cc @greg-schroeder

**Comment by grgia** [comment]
Maybe related to https://github.com/Expensify/App/pull/37461

**Comment by grgia** [comment]
Asked in slack https://expensify.slack.com/archives/C07J32337/p1710167047439949

**Comment by cead22** [comment]
Taking over because this definitely comes from my PR. That said, let's not block deploys on this since violations are in beta

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Multilevel tags - "no longer valid" violation is shown after selecting all the tags

### What is the root cause of that problem?
we're not using the tag lists `orderWeight` to check the tag lists in the right order when getTagViolationsForMultiLevelTag here
https://github.com/Expensify/App/blob/6e42e55c2554c1dd5ab17e274f56ab5c4069eaf1/src/libs/Violations/ViolationsUtils.ts#L58-L59
### What changes do you think we should make in order to solve the problem?

We should update it to 
```
     let orderedTagList = new Array(Object.keys(policyTagList).length);
     for (const tagList in policyTagList) {
         orderedTagList[policyTagList[tagList].orderWeight] = policyTagList[tagList].name;
     }
    const policyTagKeys = orderedTagList;

```
### What alternative solutions did you explore? (Optional)

**Comment by cead22** [comment]
@FitseTLT can you check if we need to update `tests/unit/ViolationUtilsTest.js` to account for this?

**Comment by roryabraham** [comment]
*suggestion:* here's how I would write the code in one line, this feels clearer to me

```ts
const sortedPolicyTagKeys = Object.keys(policyTagList).sort((a, b) => policyTagList[a].orderWeight - policyTagList[b].orderWeight);
```

*suggestion:* There appear to be at least 4 instances of this type of code:

<img width="451" alt="image" src="https://github.com/Expensify/App/assets/47436092/67697f02-1a08-44e4-96cc-c460d343801f">

so let's create `PolicyUtils.getSortedTags` or something to generalize this?

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/38044#issuecomment-1992204894) to add the correct RCA and test for Violation Tests

**Comment by cead22** [comment]
FYI we might update the orderWeight in the tests in this PR https://github.com/Expensify/App/pull/36867#discussion_r1524167753

@aimane-chnaif how do the proposals look?

**Comment by cead22** [comment]
Oh right, I'll retract my suggestion from that other PR. Silly me I thought the logic to use orderWeight was already in place but that's what we're doing here 🤦

**Comment by cead22** [comment]
Waiting for a proposal to be approved

**Comment by laurenreidexpensify** [comment]
@dukenv0307 thanks - ignore false positive adding you as contributor, adding you as C+ - can you review proposals above? Thanls

**Comment by JmillsExpensify** [comment]
PR is on staging, so we'll start the regression period as soon as this hits production.

**Comment by laurenreidexpensify** [comment]
Waiting on @dukenv0307 to complete checklist and confirm regression steps

**Comment by laurenreidexpensify** [comment]
Bump for checklist @dukenv0307
