### ISSUE TITLE
[HOLD - #37623] [$500] IOU hold - Wrong error message is shown when trying to hold a paid IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38047]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team
 
 **Issue found when executing PR** https://github.com/Expensify/App/pull/37477
## Action Performed:
1. [Employee] Create a manual request from workspace chat
2. [Employee] Go to request details page
3. [Employee] Click 3-dot menu > Hold request
4. [Admin] Pay the request
5. [Employee] After the background shows "paid", add a reason and submit it

## Expected Result:
Employee should see a clear message as to why employee can't submit the hold reason

## Actual Result:
Employee can't submit the hold message yet a wrong message is shown. "Fix the errors" message is shown instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/67d0214b-0b18-45fc-a339-0cd70cedcc52

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018199dfef5419180f</li>
        <li>Upwork Job ID: 1767256194862301184</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@iwiznia  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by iwiznia** [comment]
Not a blocker https://expensify.slack.com/archives/C036QM0SLJK/p1710179174439839

**Comment by jayeshmangwani** [comment]
@ShridharGoel I have tested your [Proposal](https://github.com/Expensify/App/issues/38047#issuecomment-1988653384)'s option 1 and option 2, and output does not looking as expected, in both the scenario error message `This request is being modified by another member.` shows under the Reason input instead of the Form bottom, attaching both options videos 


<details>
  <summary>Option 1</summary>
  
https://github.com/Expensify/App/assets/35371050/45cedb07-1f49-4544-b0fa-66702e862fed

</details>

<details>
  <summary>Option 2</summary>
  
https://github.com/Expensify/App/assets/35371050/196e31f8-f092-441d-961c-23c00a4edebc

</details>

**Comment by jayeshmangwani** [comment]
I have checked the [commit](https://github.com/Expensify/App/pull/35307/commits/9e8793528f8a31a260b8fb2a62b626f2f7864c88), where we have added the `typeof errorMessage === 'string'` check, and it looks like it was added for fixing the type warning, and in the latest code if we remove the `typeof errorMessage === 'string'` check ,we are not getting any type warning , i think we can remove this check

<details>
  <summary>Type warning that we were trying to solve
</summary>
  
  <img width="883" alt="Screenshot 2024-03-12 at 5 29 12 PM" src="https://github.com/Expensify/App/assets/35371050/eda3259f-9138-4141-b399-2ae7163c6c5d">
  
  </details>


ccing @kubabutkiewicz , as you were the author of the PR


@Krishna2323 's [proposal](https://github.com/Expensify/App/issues/38047#issuecomment-1988828042) of removing redundant check of the `typeof errorMessage === 'string'` looks good to me


🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
@GandalfGwaihir I have checked the issue that you've mentioned and it looks like there is no proposal yet selected or neither we have any update on the pending proposals yet, @iwiznia what's your thoughts on this, should we proceed with above [proposal](https://github.com/Expensify/App/issues/38047#issuecomment-1988828042)

**Comment by strepanier03** [comment]
Raised this for discussion internally as well.

My thought is that whatever GH makes it to the accepted proposal stage first gets the PR and the other is put on hold. There are many opportunities for bugs and we want to move forward with urgency when possible. This GH has a proposal further along and if the engineer agrees I say we move forward here.

**Comment by strepanier03** [comment]
Should have an update and able to take action tomorrow.

**Comment by situchan** [comment]
@Krishna2323 what is offending PR? This was marked as deploy blocker on Mar 11.
https://github.com/Expensify/App/pull/37426 is definitely not, as this was deployed to production on Mar 5.

**Comment by strepanier03** [comment]
We can put this on HOLD until https://github.com/Expensify/App/issues/37623 is completed. Doing so now.

**Comment by strepanier03** [comment]
On HOLD PR is still open.

**Comment by strepanier03** [comment]
Per this [GH](https://github.com/Expensify/Expensify/issues/381537#top) and this road-map[ doc](https://docs.google.com/document/d/1pghDdrUVhINJH4jFWNbT2w-ecFqYwTvoGxx4EoYA1U8/edit), this on HOLD bug is best suited for this VIP. 

@davidcardoza - If you disagree with this project, let me know. Or, as the curator if you believe this should be closed instead, feel free to do that. 

Current status though is that this is held on #37623.

If we keep it open and assigned, I'll continue to monitor and retest once the hold GH is closed.

**Comment by strepanier03** [comment]
Oops, I had this GH open from yesterday and the comment from @jayeshmangwani didn't update until after I sent my message above. Reviewing that now and likely closing this.
