### ISSUE TITLE
[HOLD for payment 2024-03-29] [QAB] Optimistically update the QAB NVP when taking actions

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#38048]
HELD on https://github.com/Expensify/Expensify/issues/377599

When taking one of the QAB-assignable actions, we want to optimistically set the QAB on the frontend, as described [in this section of the design doc.](https://docs.google.com/document/d/1Fa-sKBcROi1fjpZnHMUZ3J6Q96yXCEfU-ex14e_wdns/edit#bookmark=id.ww9fu816myjq)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010994abf23e96432d</li>
        <li>Upwork Job ID: 1767200034860355584</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by Gonals** [comment]
OFF HOLD

**Comment by CortneyOfstad** [comment]
@eVoloshchak can you clarify whether or not this needs a regression test by EOD today?

**Comment by CortneyOfstad** [comment]
## Payment Summary

@eVoloshchak to be paid $500 via NewDot

**Comment by eVoloshchak** [comment]
Regression Test Proposal

1. Log into newDot
2. Request money from someone and choose manual.
3. Open the Console and go to Application > IndexedDB > OnyxDB > keyValuePairs
4. Confirm `nvp_quickActionGlobalCreate` is set to `requestManual`
5. Repeat steps 1-4, but choosing Scan. Confirm `nvp_quickActionGlobalCreate` is set to `requestScan`
6. Repeat steps 1-4, but choosing Distance. Confirm `nvp_quickActionGlobalCreate` is set to `requestDistance`
7. Repeat steps 1-4, but splitting the request between several people. Confirm `nvp_quickActionGlobalCreate` is set to split `Manual`.

Do we agree 👍 or 👎

**Comment by CortneyOfstad** [comment]
Regression test created here — https://github.com/Expensify/Expensify/issues/384210

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak based on summary.
