### ISSUE TITLE
[HOLD for payment 2024-03-22] Сhat - On selecting skin tone emoji symbol disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4417529
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open a conversation
3. Enter :wave
4. Note suggestions shown
5. Enter colon at end :wave:
6. Note emoji shown
7. Clear the message
8. Enter :wave
9. Tap emoji picker and select different skin tone
10. Tap outside

## Expected Result:
Emoji symbol must not disappear in suggestion list

## Actual Result:
Emoji symbol disappears in suggestion list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09449f34-e32c-4129-bbfb-000556432375

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment]
I'm removing the deploy blocker label as this is not a crucial path and sending emojis still works.

**Comment by rlinoz** [comment]
As @aimane-chnaif pointed out this should be handled by @kubabutkiewicz if possible.

**Comment by kubabutkiewicz** [comment]
I will take a look on this today @rlinoz

**Comment by kubabutkiewicz** [comment]
[PR](https://github.com/Expensify/App/pull/38134) ready @rlinoz

**Comment by rlinoz** [comment]
No payment due, closing.
