### ISSUE TITLE
[Awaiting Payment 30th April] [QAB] Skip confirmation screen when using the QAB

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#38051]
As described [in this section of the design doc](https://docs.google.com/document/d/1Fa-sKBcROi1fjpZnHMUZ3J6Q96yXCEfU-ex14e_wdns/edit#bookmark=id.alllbfpfzq6o), we need to implement some changes to skip the confirmation screen when taking a quick action. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136e9657929b24c62</li>
        <li>Upwork Job ID: 1767203106612834304</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Still held on #38050. It's in review!

**Comment by c3024** [comment]
Could you share me the design document on chaitanya3024@gmail.com? I have signed the NDA. @Gonals

**Comment by c3024** [comment]
Looks like automation failed here.

**Comment by trjExpensify** [comment]
Yeah, it did. Updated the title to reflect the payment hold!

**Comment by trjExpensify** [comment]
Alright, confirming payment summary here: 

- $500 to @c3024 for the C+ review

Offer sent!

**Comment by c3024** [comment]
Thanks. Accepted.

**Comment by trjExpensify** [comment]
Paid!
