### ISSUE TITLE
[HOLD for payment 2024-04-05] [QAB] Create the Quick Action button

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#38050]
As described [in this section of the design doc](https://docs.google.com/document/d/1Fa-sKBcROi1fjpZnHMUZ3J6Q96yXCEfU-ex14e_wdns/edit#bookmark=id.lzqe0ha50u7t), we want to add a Quick Action button to Global Create.

The changes to skip the confirmation screen will be done in a different issue
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01244e26ed86f405a4</li>
        <li>Upwork Job ID: 1767202396900225024</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
Held.

**Comment by Gonals** [comment]
OFF HOLD

**Comment by joekaufmanexpensify** [comment]
@parasharrajat could you please complete your portion of checklist?

**Comment by joekaufmanexpensify** [comment]
Sounds good! I'll work on getting that created.

**Comment by joekaufmanexpensify** [comment]
In the meantime, only payment here is $250 to @parasharrajat via NewDot for C+ review. Could you please request that and confirm here once complete?

**Comment by trjExpensify** [comment]
>Actually, I see we have a detailed [manual testing script](https://docs.google.com/document/d/1AQZ2LqTYfLcG2SLMiMBliOlbl2_3gh12JomJOW05-U4/edit#heading=h.nhtsmauf72jq) here that covers this case (any others) in more detail. @trjExpensify @Gonals I assume the plan is to just pass off that script to applause to make tests for all of the various cases at once after testing?

Yep, that's the plan once we're done with the issues for the project!

**Comment by joekaufmanexpensify** [comment]
Cool. TY!

**Comment by joekaufmanexpensify** [comment]
Bump @parasharrajat for when you have a sec!

**Comment by joekaufmanexpensify** [comment]
Got it. TY! Payment summary is [here. ](https://github.com/Expensify/App/issues/38050#issuecomment-2045413711)

**Comment by joekaufmanexpensify** [comment]
Brought to slack to [discuss](https://expensify.slack.com/archives/C02NK2DQWUX/p1716328555179459?thread_ts=1715190852.677769&cid=C02NK2DQWUX)

**Comment by joekaufmanexpensify** [comment]
Discussed, and confirmed that @parasharrajat is actually due $500 here, since this issue was opened prior to the adjustment of base review price from $500 > $250.

**Comment by joekaufmanexpensify** [comment]
Adjust payment summary to reflect that, which is noted [here](https://github.com/Expensify/App/issues/38050#issuecomment-2045413711).
