### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] [Performance] Memoize SidebarLinksData to reduce the getOrderedReportIDs calls

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38055]
Coming from the [Callstack performance audit](https://github.com/Expensify/App/issues/35234#issuecomment-1926914534)

From the hermes profile trace, we see that `getOrderedReportIDs` from `Sidebarlinks` takes about ~8 seconds and it happens in 3 occurrences. Which means we have `getOrderedReportIDs` being called for roughly 3 times. We can reduce it to 2 times only by adding memoization to `Sidebarlinks` . This reduces the app startup by ~2.5 seconds, which is a huge reduction.
Details for the implementation can be seen in the [commit](https://github.com/callstack-internal/Expensify-App/commit/3b3b8ba88669f15bef34136e13b55c449f50d47e)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e08e65659afcb69</li>
        <li>Upwork Job ID: 1772400240247611392</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by rinej** [comment]
@mountiny sure

**Comment by mountiny** [comment]
Thanks

**Comment by rinej** [comment]
Hello @mountiny, we decided to hold this off until we complete the remaining audit implementations because as of now, we are not yet sure whether we prefer the extra render without memo or increased rendering time with memo. We will evaluate this after all the audit action items are completed.

**Comment by alexpensify** [comment]
Weekly Update: Going through an audit

**Comment by alexpensify** [comment]
Weekly Update: The PR is under review and making progress

**Comment by mountiny** [comment]
$500 to @c3024 only

**Comment by alexpensify** [comment]
@c3024 - please apply to the job below and I can complete the payment process tomorrow: 

https://www.upwork.com/jobs/~011e08e65659afcb69

Thanks!

**Comment by alexpensify** [comment]
@c3024 - please accept in Upwork and I can complete the payment process. Thanks!

**Comment by c3024** [comment]
@alexpensify accepted, thanks.

**Comment by alexpensify** [comment]
Awesome, I've completed the payment process in Upwork.
