### ISSUE TITLE
[HOLD for payment 2024-03-20] [HOLD for payment 2024-03-19] [HOLD for payment 2024-03-11] [$500] Chat - Message sent while offline appears on compose box when user is back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38065]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4413864
**Email or phone of affected tester (no customers):** vdargentotest+mweb031124@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must be logged in with Gmail account (important)
1. Go to any chatThe message should be sent and should not remain on the compose box
2. Disable internet connection
3. Send the message "Testing" (must be this message or something with "Test" on it)
4. Verify it appears grayed out
5. Reload the page
6. Enable internet connection
7. Reload the page again

## Expected Result:
The message should be sent and should not remain on the compose box

## Actual Result:
The message is sent but remains on the compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cef80f27-f2b0-4920-9c39-a7b06b573f70

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116aafb00f186ff86</li>
        <li>Upwork Job ID: 1767240869024415744</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by bondydaa** [comment]
I'm pretty sure this would be something in new dot so a contributor should be able to handle, going to add the external label.

**Comment by mountiny** [comment]
The revert PR fixes this issue

**Comment by bondydaa** [comment]
Thanks @mountiny 🙇

**Comment by bondydaa** [comment]
tested on staging again after the revert was CP'd and looks good.

**Comment by bondydaa** [comment]
@twisterdotcom just need you for payment for @mkhutornyi for reviewing the revert PR.

**Comment by twisterdotcom** [comment]
Payment Summary: WIP

- @mkhutornyi paid $500 here (C+)

**Comment by twisterdotcom** [comment]
Paid: https://github.com/Expensify/App/issues/38065#issuecomment-1989609107
