### ISSUE TITLE
Compose Box - Sent text remains in compose box after pressing return

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#38068]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.50-2
**Reproducible in staging?:** Yes 
**Reproducible in production?:** No

**Issue reported by:** @laurenreidexpensify '
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710165211864299

## Action Performed:
1. Go www.staging.new.expensify.com
2. Open a chat
3. Send a message
4. Navigate to another chat
5. Navigate back to first chat

## Expected Result:
The text editor is blank aside from the flashing cursor

## Actual Result:
The compose box shows the text that has already been sent in the chat in the previous message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![2024-03-11_13-47-04 (1)](https://github.com/Expensify/App/assets/44479856/42298438-9a4d-46de-929e-e0399ea9a7fa)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Made a revert of a sus PR #38071

**Comment by mountiny** [comment]
The revert PR fixes this issue

**Comment by luacmartins** [comment]
Issue fixed in staging! Closing.
