### ISSUE TITLE
[$500] Search - Individual chats appear on Search instead created Group chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gocemate+balto831@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create group chat with User A and User B
3. Click on Search
4. Take a look at search results

## Expected Result:
Group chat should be visible on the top of the searched results

## Actual Result:
Two individual chat (A and B) are present as search results instead of created group chat with those users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/56eb1378-5b71-4717-be4c-7b88e8e92d95

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2fe1ef8492554e6</li>
        <li>Upwork Job ID: 1768040424722677760</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by sakluger** [comment]
This is definitely a bug. I tested a bit with @MitchExpensify and found some very strange behavior with search and group chats. I'll add to VSB.

**Comment by jeremy-croff** [comment]
Cannot reproduce anymore on staging, only on new
<img width="365" alt="Screenshot 2024-03-13 at 11 26 14 PM" src="https://github.com/Expensify/App/assets/157416545/e551d0f9-fca5-4bf8-92e1-7927a46eb078">
<img width="362" alt="Screenshot 2024-03-13 at 11 26 08 PM" src="https://github.com/Expensify/App/assets/157416545/785b457b-fe0c-49fc-bacf-836b5dd44cd6">

**Comment by jjcoffee** [comment]
Yeah I'm also unable to replicate (latest main). @sakluger are you still seeing this behaviour on latest staging?

**Comment by sakluger** [comment]
It's working better for me, too, on Staging. I think we can close!
