### ISSUE TITLE
Approver can see `Hold Request` for the unsubmitted expense report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710183306832819

## Action Performed:
Precondition: Create 3 account with employee approver and admin
1. Create a expense report in the employee account in the workspace chat
2. Sign in to Approver account and open the unsubmitted expense report

## Expected Result:
As a approver shouldn't have the option to delete the report

## Actual Result:
Approver can `hold request` on the unsubmitted report

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-03-11 at 4 07 12 PM](https://github.com/Expensify/App/assets/38435837/b7362231-e488-45b5-982f-cb30645f0d10)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
My bad. Turns out this is allowed behavior.
