### ISSUE TITLE
Attachment - Loader does not appear in the center when uploading a corrupted PDF

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38089]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/20176&group_by=cases:section_id&group_order=asc&group_id=292107
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. On a conversation, click on the + button in the compose box
2. Click on add attachment
3. Upload the following corrupted PDF
4. Verify that Failed to load PDF file. message appears when previewing a corrupt PDF file

## Expected Result:
The loader should be displayed in the center, or if an error occurs, only the error should be displayed without the loader

## Actual Result:
Loader does not appear in the center when uploading a corrupted PDF

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/708d6ae5-fcf3-49da-84eb-e52609408886

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
cc @quinthar

**Comment by joekaufmanexpensify** [comment]
This is a minor visual issue. Given it only impacts corrupted PDFs, I don't think this is something we should optimize for/do anything about. I doubt many/any customers will ever see this, and even if they do it still works. There isn't really any impact to the user experience. Closing.
