### ISSUE TITLE
HIGH: Update GetOlderActions and GetNewerActions to return 50 visible actions

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#38112]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from these #whatsnext posts:

- https://expensify.slack.com/archives/CC7NECV4L/p1709835463864709
- https://expensify.slack.com/archives/CC7NECV4L/p1709835940121859

## Action Performed:
1. Create a chat with >50 invisible actions in a row. These could be whispers directed at other users, or deleted messages.
1. Log out and log back in.
1. Open the chat.
1. Scroll up to load more chats.

## Expected Result:
You should be able to smoothly load more reportActions without flashing.

## Actual Result:
you'll observe some "flashing" skeleton indicators. This is particularly noticeable on mobile, where the skeleton items take up more screen real estate

## Workaround:
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010732183cd968390f</li>
        <li>Upwork Job ID: 1767432825903190016</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
The root cause of this problem is that `GetOlderActions` (and similarly `GetNewerActions`) both return a limit of 50 reportActions at a time. But this does not account for whether those actions will be visible to the current user or not.

So the idea here is that we will update `GetOlderActions` and `GetNewerActions` in Auth such that they return up to 50 _visible_ actions to the current user. Invisible actions still need to be included to maintain a continuous chain of `previousReportActionID`, so in practice this means we could return more than 50 reportActions total from `GetOlderActions` and `GetNewerActions.

**Comment by roryabraham** [comment]
It _might_ be possible to implement this efficiently in pure SQLite, but I'm not sure. You'd need a "dynamic limit" or "filtered" limit of some kind. But you'd need to be careful because the `LIMIT` is part of what makes the query to get pages of reportActions fast.

Probably a more straightforward way to implement this would be to just query pages of reportActions in a while loop, until the total number of _visible_ actions returned reaches or exceeds 50, or you run out of actions.

**Comment by roryabraham** [comment]
must be internal because the solution is in Auth back-end. No C+ needed here.

**Comment by roryabraham** [comment]
thanks for volunteering @deetergp!

**Comment by roryabraham** [comment]
Check out [ReportActionsUtils.shouldReportActionBeVisible](https://github.com/Expensify/App/blob/70bfa9452413f6ac542d2482e78476891674a7a7/src/libs/ReportActionsUtils.ts#L384-L421) for the current business logic on whether a reportAction should be visible or not

**Comment by deetergp** [comment]
Making this a Daily

**Comment by deetergp** [comment]
Oh yeah, it's a thing! Using test user `deetertest+20240312@gmail.com` I made 78 new posts in a DM (typed the alphabet 3 times) then edited the last 52 of them with the following query:
```sql
UPDATE reportActions SET message = JSON_SET(message, '$.edits', JSON_ARRAY(message->>'$.html'), '$.html', '') WHERE reportID = <reportID> AND created >= <created of the A in the 2nd series>;
```

And sure enough, this twitchy guy is the result:

https://github.com/Expensify/App/assets/766197/3b1b5862-46b6-48ba-9f96-643ee9262f4c

**Comment by deetergp** [comment]
I decided to change up my approach after talking through it a bit more with @roryabraham. More details [here](https://github.com/Expensify/Auth/pull/10218#issuecomment-2004644669).

**Comment by deetergp** [comment]
The PR for this was deployed a few hours ago. I think we can close this, but I'm going to leave it open till tomorrow.

**Comment by deetergp** [comment]
I think we're good to close this one.
