### ISSUE TITLE
iOS - LHN - Concierge name changes to concierge@expensify.com after enabling camera access

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38117]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4415591&group_by=cases:section_id&group_order=asc&group_id=306203
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with an expensifail user
2. Navigate to FAB - Request money - Scan
3. Tap on the "Continue" button
4. Tap on the "Settings" button
5. Enable permission in the settings
6. Go back to the Expensify app LHN

## Expected Result:
It should be Expensify Concierge.

## Actual Result:
Concierge name changes to [concierge@expensify.com](mailto:concierge@expensify.com)
after enabling camera access. The change is happening 4-5 seconds after returning to LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/97268ab5-e8e1-4f51-a513-897ec38dfd26

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@slafortune I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by slafortune** [comment]
@izarutskaya Once the camera is enabled and you log in again, what shows?

**Comment by slafortune** [comment]
I think that this is going to be a very limited issue that anyone sees - only if they hadn't enabled their camera to start.  And if they do notice it, it won't affect them.  Logging in again should allow it to populate correctly.
