### ISSUE TITLE
Update OSBotify permissions in react-native-onyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#38113]
### Problem

I am trying to simplify the publishing workflow of react-native-onyx to more closely match what we do in E/App: https://github.com/Expensify/react-native-onyx/pull/500. i.e: allow `OSBotify` to push version-bump commits straight to main, rather than:

- open a PR
- have another bot approve it
- merge the PR

which is substantively the same as OSBotify pushing straight to main.

### Solution

Please update the permissions of OSBotify in react-native-onyx to match his permissions in E/App for the main branch 🙇🏼

**Comment by justinpersaud** [comment]
Added this to react-native-onyx which App already had

![image](https://github.com/Expensify/App/assets/2513393/ecb2afb0-e128-43b6-90bc-3eda547d54f9)

**Comment by roryabraham** [comment]
Got:

```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request.
```

in [this workflow](https://github.com/Expensify/react-native-onyx/actions/runs/8256030244/job/22583804707). I wasn't able to find any way it's different from E/App though...

**Comment by justinpersaud** [comment]
Are you sure it's using the right token to authenticate as OSBotify?

Don't we need something like this in the workflow?

https://github.com/Expensify/App/blob/main/.github/workflows/createNewVersion.yml#L68-L70

**Comment by justinpersaud** [comment]
bump @roryabraham

**Comment by justinpersaud** [comment]
Waiting on @roryabraham

**Comment by roryabraham** [comment]
Sorry, coming back to this after OOO. We were using `OS_BOTIFY_TOKEN` before my [changes](https://github.com/Expensify/react-native-onyx/pull/500/files), and I doubt `OS_BOTIFY_COMMIT_TOKEN` was ever added to the react-native-onyx repo.

As a member of ring0, you should be able to see which secrets are available in the react-native-onyx repo. The secret should be correct, as evidenced by the [last automated pull request](https://github.com/Expensify/react-native-onyx/pull/511) created in react-native-onyx before my changes.

**Comment by justinpersaud** [comment]
@roryabraham it's an organization secret so it can be accessed from any repository

**Comment by justinpersaud** [comment]
Can you try changing the token it's using to the `OS_BOTIFY_COMMIT_TOKEN` instead and see if that works?

**Comment by roryabraham** [comment]
Thanks for the suggestion @justinpersaud and sorry for the delay. I don't know if it's a problem for `OS_BOTIFY_TOKEN` vs `OS_BOTIFY_COMMIT_TOKEN`. The problem I think is just that I didn't pass any token to the checkout action, which is what authenticates the user with GitHub: https://github.com/Expensify/react-native-onyx/pull/522/files

**Comment by roryabraham** [comment]
this is fixed
