### ISSUE TITLE
Tag - Violation in expense preview does not show specific tag next to RBR

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38124]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #37461 
**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** applause internal team

## Action Performed:
Precondition:
- User is an employee of Collect workspaces that have independent and dependent multilevel tags.
- Tag requirement is toggled on.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request without tags.
4. Go to request details page.
5. Select all the tags but leaving one of tags blank.
6. Click on the thread header subtitle to return to expense report.

## Expected Result:
The violation will show "missing <tag name>" next to RBR.

## Actual Result:
The violation shows "missing tag" next to RBR.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/b75a6994-dcb7-4171-8a5e-9abc9a86baef

[Bug6410638_1710217481315!independant_tag.csv](https://github.com/Expensify/App/files/14571449/Bug6410638_1710217481315.independant_tag.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
We think this bug might be related to #wave-control
cc @JmillsExpensify

**Comment by kavimuru** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by trjExpensify** [comment]
@cead22 @JmillsExpensify - I think this is pretty minor if it's a bug, but I'm not sure if we do have the name of the tag missing displayed on the preview component itself in the first place.

**Comment by JmillsExpensify** [comment]
No we don't.

**Comment by JmillsExpensify** [comment]
We could add it, though the nice thing about `Tag` is that we know the message can fit every time. There are some customers with some long names for the tag fields. So this just keep the design more consistent.

**Comment by trjExpensify** [comment]
Cool, if it's expected, I'm fine with it. Let's close!

**Comment by cead22** [comment]
This is actually not expected, and we can make this work such that the violation says "Missing Department" instead of "Missing Tag". If the tag name ends up being too long, our existing logic will show "Review required".

I'm going to reopen to use this issue to clean up some of the code for multi-tag violations and fix this. Let me know if you disagree

**Comment by trjExpensify** [comment]
Oh haha, neat. I agree if it's expected, let's keep it open. 👍

**Comment by kbecciv** [comment]
Reopen by comment https://github.com/Expensify/App/issues/38124#issuecomment-1998286149

**Comment by cead22** [comment]
The fix for this was deployed last week
