### ISSUE TITLE
[$500] Add BA thread is missing Add button, incomplete thread header and "Hidden" user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38126]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exploratory around https://expensify.testrail.io/index.php?/tests/view/4414706
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are in the Collect workspace.
- Admin has bank account account.
- Employee does not have a bank account.

1. [Employee] Go to staging.new.expensify.com.
2. [Employee] Go to workspace chat and create a manual request.
3. [Admin] Pay the request with Expensify.
4. [Employee] Go to expense report.
5. [Employee] Right click on "started settling up," message > Reply in thread.

## Expected Result:
- Add bank account button will appear in thread.
- Thread header will show the complete parent message.
- No "Hidden" will display in parent message in thread.

## Actual Result:
- Add bank account button does not appear in thread.
- Thread header shows admin email address instead of complete parent message.
- "Hidden" is displayed in parent message in thread - "started settling up, payment is held until Hidden adds a bank account"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/eeffa3bb-6ebc-40a0-aea1-aa5f0c80bf17

<img width="1440" alt="Bug6410857_1710235799984!Screenshot_2024-03-12_at_17 22 52" src="https://github.com/Expensify/App/assets/43996225/671a2fa8-7160-409e-a96b-46b4a5b2bccb">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168f850ea211df0b2</li>
        <li>Upwork Job ID: 1767551381908271104</li>
        <li>Last Price Increase: 2024-03-12</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb
cc @quinthar

**Comment by sonialiap** [comment]
The submitter is an employee of a workspace, I believe the admin should be able to see the  email address in this case. We should fix

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add BA thread is missing Add button, incomplete thread header and "Hidden" user

### What is the root cause of that problem?
We don't have a special condition dealing with `REIMBURSEMENTQUEUED` type here
https://github.com/Expensify/App/blob/6e42e55c2554c1dd5ab17e274f56ab5c4069eaf1/src/libs/ReportUtils.ts#L2617-L2621
### What changes do you think we should make in order to solve the problem?

For `REIMBURSEMENTQUEUED` type we should use `ReportUtils.getReimbursementDeQueuedActionMessage` here
https://github.com/Expensify/App/blob/6e42e55c2554c1dd5ab17e274f56ab5c4069eaf1/src/libs/ReportUtils.ts#L2617-L2621

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/38126#issuecomment-1991782435)

**Comment by akinwale** [comment]
We can move forward with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/38126#issuecomment-1991782435) here.

🎀👀🎀 C+ reviewed.

**Comment by chiragsalian** [comment]
Proposal sounds good to me. Feel free to create the PR @FitseTLT.

**Comment by sonialiap** [comment]
@FitseTLT how's the PR going? :) If you've created it, please link it to this issue

**Comment by sonialiap** [comment]
@FitseTLT bumping again. Will you be able to work on this issue? If not, that's ok just let me know so that I we can select a different proposal to get this resolved

**Comment by FitseTLT** [comment]
Sorry @sonialiap PR will be ready for review By EOW

**Comment by sonialiap** [comment]
Thanks!

**Comment by sonialiap** [comment]
Looks like Melvin's automation may be failing here. The PR was deployed to production yesterday. Payment will be due on Apr 29

**Comment by sonialiap** [comment]
Payment summary: 

- @akinwale $500 - paid ✔️ 
- @FitseTLT $500 - paid ✔️
