### ISSUE TITLE
Scan-In scan request confirmation page, preview is not shown for .tiff file

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4414022
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a conversation
3. Tap plus icon --- request money --- Scan
4. Upload a below given .tiff file
5. Note image preview is not shown and only green placeholder is shown
6. Tap request
7. Now note in conversation page, image preview is shown

## Expected Result:
In scan request confirmation page, image preview must be shown and green placeholder must not be shown.

## Actual Result:
In scan request confirmation page, image preview is not shown and only green placeholder is shown.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9be3251f-a31c-4e70-8a6d-10d6ef483865

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@greg-schroeder I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by greg-schroeder** [comment]
closing per team discussion
