### ISSUE TITLE
[Wave Collect] [More Features] Update the NewDot enable tax feature call

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38138]
### Problem

When the taxes are enabled in OldDot, 2 API calls are done, where one sets the taxes as enabled and the other one creates the default tax rates for the policy. 

This is against the 1:1:1 idea for NewDot API calls.

### Solution

Update the NewDot enabled tax API call such that the default tax rates are created if they do not exist yet
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ccf8461ae334ba0</li>
        <li>Upwork Job ID: 1767555727223484416</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Oh I realized [this other issue](https://github.com/Expensify/App/issues/38234) is a duplicate. We already got a contributor working on that one and I also have this [draft PR](https://github.com/Expensify/Web-Expensify/pull/41305). I'm gonna close this one in favor of https://github.com/Expensify/App/issues/38234
