### ISSUE TITLE
Expense - Two transaction threads in LHN when creating expense with violation offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- The Collect workspace has toggled on "People must categorize expenses" for Categories on Old Dot
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go offline
4. Create a manual request without category
5. Go to request details page

## Expected Result:
There will be only one transaction thread in LHN

## Actual Result:
There are two transaction threads in LHN. One is grayed out, the other one is not grayed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/01a78880-0851-4688-b25c-ed747f865628

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to [#wave-collect](https://github.com/orgs/Expensify/projects/129/views/1)
CC @trjExpensify

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
It could well be related to work for #wave-control and violations, though valid in #wave-collect as well. @abekkala will be curious on a reproduction here - we shouldn't be creating two transaction threads when there's a violation. CC: @JmillsExpensify @cead22 to put on your radar as well!

**Comment by bernhardoj** [comment]
I think this is already fixed in https://github.com/Expensify/App/pull/37232

**Comment by trjExpensify** [comment]
Ah perfect, let's close it then! :)
