### ISSUE TITLE
[Wave Collect] [Taxes] Update the CreatePolicyTax to accept an object not an array

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38146]
### Problem

The CreatePolicyTax backend code expects array of objects, but we only allow for one tax object to be created at a time

### Solution

Update the https://github.com/Expensify/Web-Expensify/blob/f66a4e93acaf94d85406dd13cd8898eb937cb012/lib/PolicyAPI.php#L2877-L2902 method to handle one tax object only
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7dfef3b4eaf151f</li>
        <li>Upwork Job ID: 1767578835955789824</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
👋 this was a web PR only, right? Shall we close? It's on prod.

**Comment by mountiny** [comment]
yep the App PR already reflects it and if in review
