### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Scroll position jumps to new data each time new data comes in debug console

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38155]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-5
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710209384799229

## Action Performed:
1. Go to account settings > about > troubleshoot
2. Toggle Client side logging > View debug console
3. Scroll to somewhere in the history
4. Wait for new data to come in

## Expected Result:
Scroll position should be stable

## Actual Result:
Scrolls to the new data postion

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7ebd29c3-fed1-47d4-8643-a288562879c8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b144dad7ad88d8ed</li>
        <li>Upwork Job ID: 1768332727529181184</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by puneetlath** [comment]
Opening up for proposals.

**Comment by getusha** [comment]
@tienifr's [proposal](https://github.com/Expensify/App/issues/38155#issuecomment-1998921955) looks good to me.
It makes sense to use the `InvertedFlatList,`, i don't see the regular FlatList with inverted being used other places.

🎀 👀 🎀 C+ Reviewed.

**Comment by getusha** [comment]
🎀 👀 🎀 C+ reviewed

**Comment by getusha** [comment]
:ribbon::eyes::ribbon: C+ reviewed

**Comment by puneetlath** [comment]
Sounds good to me too 👍🏾

**Comment by puneetlath** [comment]
@getusha bump on the checklist so that we can pay tomorrow.

**Comment by puneetlath** [comment]
Great thanks. @tienifr @getusha sent you both Upwork offers. Please comment here when you've accepted.

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
