### ISSUE TITLE
HIGH: [Public] Thread messages are missing from public room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduciton
**Reproducible in production?:** needs reproduciton
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @quinthar  https://staging.new.expensify.com/r/868417741568295 and https://staging.new.expensify.com/r/6776919265133947
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710204955795119

## Action Performed:
1. Open a public room in which there are already a bunch of threads 

## Expected Result:
User should be able to view all the thread messages

## Actual Result:
Thread messages are disappaeared

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (8)](https://github.com/Expensify/App/assets/38435837/f94a4c7b-0a48-47fc-a017-e5cdfc3cc75d)
![image (7)](https://github.com/Expensify/App/assets/38435837/770d7a73-73d9-47b3-b891-ba293a787787)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe380d1a88aa6cc2</li>
        <li>Upwork Job ID: 1767615415137488896</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Seems like David's OpenReport call is not even getting the [childReportID](https://expensify.slack.com/archives/C049HHMV9SM/p1710267518196099?thread_ts=1710204955.795119&cid=C049HHMV9SM) property and other thread related properties for the report actions which should be added here https://github.com/Expensify/Auth/blob/bfd557749a4f372ad331f74defb7df026fe1037d/auth/lib/Report.cpp#L6984-L7031

**Comment by mountiny** [comment]
My plate is quite full right now focusing on performance and Critical wave collect tasks so sending this to the pool if anyone has spare cycles to dig into it. Given the reproduction steps will be quite tough locally it might take some time.

**Comment by abdulrahuman5196** [comment]
Still haven't picked up

**Comment by anmurali** [comment]
@quinthar do you want to do an open call for volunteers for this bug?

**Comment by jasperhuangg** [comment]
Can look into this

**Comment by quinthar** [comment]
Thanks @jasperhuangg !

**Comment by anmurali** [comment]
@jasperhuangg is working on this now.

**Comment by jasperhuangg** [comment]
I'm going OOO for the rest of this week, so I'm looking to get started on this next week

**Comment by anmurali** [comment]
@jasperhuangg I know you just got back today but can you add an update either here or in Slack so we can keep the issue up to date?

**Comment by quinthar** [comment]
is this still happening for anyone?  This is working fine for me.  I'm going to just close this; reopen if it's happening to you.

**Comment by jasperhuangg** [comment]
Tried to reproduce it as well with the same room and I'm able to load all the threads. Feel free to reopen if we see it crop up again and provide the reportID of the parent report and the thread, thanks!
