### ISSUE TITLE
[HOLD for payment 2024-03-26] [Reassure] Add measureFunction test for getOptions

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38165]
### Problem

The [getOptions](https://github.com/Expensify/App/blob/e953f0e600a44cfda2f4d53ee67fcc957fc5dd52/src/libs/OptionsListUtils.ts#L1335) is a method that is used often in the App and if its performance degrades, it can have considerable impact on the App performance.

### Solution

Let's add a measure function reassure test to cover various cases of getOptions call similarly as we have created such test for [ReportActionUtils](https://github.com/Expensify/App/blob/a3b70bf82102dd5092e840062db9fe4192c4c04c/tests/perf-test/ReportActionsUtils.perf-test.ts#L1-L148) for example.

**Comment by mountiny** [comment]
@OlimpiaZurek is handling this one just for clarity

**Comment by mountiny** [comment]
Pr is up in review

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by mountiny** [comment]
No payment or next steps required here
