### ISSUE TITLE
[HOLD for payment 2024-04-25] [$250] [Reassure] Add measureFunction test for formatSectionsFromSearchTerm

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38166]
### Problem

The [formatSectionsFromSearchTerm](https://github.com/Expensify/App/blob/a3b70bf82102dd5092e840062db9fe4192c4c04c/src/libs/OptionsListUtils.ts#L1979) is a method that is used often in the App and if its performance degrades, it can have considerable impact on the App performance.

### Solution

Let's add a measure function reassure test to cover various cases of this method call similarly as we have created such tests for [ReportActionUtils](https://github.com/Expensify/App/blob/a3b70bf82102dd5092e840062db9fe4192c4c04c/tests/perf-test/ReportActionsUtils.perf-test.ts#L1-L148) methods for example.

____

Please refer to other tests in the repository, here is a [readme](https://github.com/Expensify/App/tree/main/tests/perf-test) for reassure tests which should help you get familiar with the tool.

All new tests should be written in TS.

Please provide a proposal stating, how you could write such test and scenarios for the method such that we test the slowest execution path as well.

cc @OlimpiaZurek 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c574cb1d199b7bd</li>
        <li>Upwork Job ID: 1767635884215123968</li>
        <li>Last Price Increase: 2024-03-12</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>brandonhenry | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment]
@getusha when you get a chance, can you review the proposal here? Thanks!

**Comment by getusha** [comment]
@mountiny The scenarios @brandonhenry provided looks good to me https://github.com/Expensify/App/issues/38166#issuecomment-1992651656

**Comment by mountiny** [comment]
thank you @brandonhenry can you please raise a PR when you get a chance

**Comment by alexpensify** [comment]
Thank you @brandonhenry for the update!

**Comment by mountiny** [comment]
@brandonhenry have you got a chance to start on a draft at least?

**Comment by mountiny** [comment]
> Turns out i just needed to update my mac

Everyone has days like this sometimes

**Comment by mountiny** [comment]
@brandonhenry whats the latest here?

**Comment by mountiny** [comment]
Thanks

**Comment by alexpensify** [comment]
Thanks, Brandon, we will keep an eye out for any update for this one.

**Comment by alexpensify** [comment]
Thanks, the PR is moving forward in the review process.

**Comment by mountiny** [comment]
@brandonhenry changes requested, please try to resolve this soon

**Comment by mallenexpensify** [comment]
@brandonhenry per [CONTRIBUTING.md,](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md?rgh-link-date=2024-04-01T17%3A24%3A34Z#:~:text=New%20contributors%20are%20limited%20to%20working%20on%20one%20job%20at%20a%20time%2C%20however%20experienced%20contributors%20may%20work%20on%20numerous%20jobs%20simultaneously.)

> New contributors are limited to working on one job at a time, however experienced contributors may work on numerous jobs simultaneously.

You currently have [6 issues open](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+assignee%3Abrandonhenry+) with non merged or closed. Please do not submit proposals for new issues until **all** six PRs have been merged.

Also [from CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md?rgh-link-date=2024-04-01T17%3A24%3A34Z#:~:text=Daily%20updates%20on,original%20contract%20terminated.)

> Daily updates on weekdays are highly recommended. If you know you won’t be able to provide updates within 48 hours, please comment on the PR or issue stating how long you plan to be out so that we may plan accordingly. We understand everyone needs a little vacation here and there. Any issue that doesn't receive an update for 5 days (including weekend days) may be considered abandoned and the original contract terminated.

Please keep the issue and PR moving along with urgency, along with all others.

**Comment by mallenexpensify** [comment]
Thanks for the regular updates @brandonhenry .  Please continue to provide them on your assigned issues. When possible, include links.

**Comment by alexpensify** [comment]
Weekly update: I believe we are waiting for this one to go to Production

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, April 23, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by mountiny** [comment]
$250 to @getusha and to @brandonhenry

**Comment by alexpensify** [comment]
@getusha and @brandonhenry - there was an issue with Upwork. I updated the job link and need you to accept it here: 
 
 https://www.upwork.com/jobs/~01ac085e1e841dfb81
 
 After you accept, I can continue with the next steps. Thanks!

**Comment by alexpensify** [comment]
Payouts due: April 25, 2024

- [ ] Contributor: $250 @brandonhenry 
- [ ] Contributor+: $250 @getusha 

Upwork job is [here](https://www.upwork.com/jobs/~01ac085e1e841dfb81).

**Comment by alexpensify** [comment]
Everyone has been paid via Upwork -- closing!
