### ISSUE TITLE
[HOLD for payment 2024-03-26] [$250] [Reassure] Add measureFunction test for getMemberAccountIDsForWorkspace

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38167]
### Problem

The [getMemberAccountIDsForWorkspace](https://github.com/Expensify/App/blob/a3b70bf82102dd5092e840062db9fe4192c4c04c/src/libs/PolicyUtils.ts#L122)is a method that is used often in the App and if its performance degrades, it can have considerable impact on the App performance.

### Solution

Let's add a measure function reassure test to cover various cases of this method call similarly as we have created such tests for [ReportActionUtils](https://github.com/Expensify/App/blob/a3b70bf82102dd5092e840062db9fe4192c4c04c/tests/perf-test/ReportActionsUtils.perf-test.ts#L1-L148) methods for example.

____

Please refer to other tests in the repository, here is a [readme](https://github.com/Expensify/App/tree/main/tests/perf-test) for reassure tests which should help you get familiar with the tool.

All new tests should be written in TS.

Please provide a proposal stating, how you could write such test and scenarios for the method such that we test the slowest execution path as well.

cc @OlimpiaZurek 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f1d655a8cb04a5b</li>
        <li>Upwork Job ID: 1767636294734249984</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by mountiny** [comment]
@ShridharGoel Can you please raise a PR? thanks!

**Comment by kevinksullivan** [comment]
updated job here

https://www.upwork.com/jobs/~018339f69bac8f5267

@ShridharGoel lmk when you accept!

**Comment by mountiny** [comment]
@kevinksullivan @ShridharGoel @paultsimura can this be closed?

**Comment by mountiny** [comment]
Ok thanks!

**Comment by kevinksullivan** [comment]
All set
