### ISSUE TITLE
[$500] Account Settings – Banners in About/ Preferences/ Security are without animation in Offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38172]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Turn off internet on device
4. Navigate to Account Settings
5. Open About/ Preferences/ Security
6. Go back and repeat steps 4-5 if need

## Expected Result:
Banners in About/ Preferences/ Security are with animation in Offline

## Actual Result:
Banners in About/ Preferences/ Security are without animation in Offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4c31b9c1-1ed9-4671-8b74-a934ca4a11c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199c79b8079cceda2</li>
        <li>Upwork Job ID: 1767649903440666624</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:

https://github.com/Expensify/App/assets/78819774/1d9597e7-5e29-49a9-8ec1-38a77fb4caab

**Comment by lanitochka17** [comment]
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcochavezf** [comment]
This is also happening in production when the connection is disabled from the Network tab in the dev tools:

https://github.com/Expensify/App/assets/6829422/ee148753-6d0d-4d7e-9c52-7408a8c2af1b

I don't think it's a blocker, but I'm going to make it external to look for a solution to make the animations work offline consistently.

**Comment by kaushiktd** [comment]
Hey man, @brandonhenry I want to learn more about your proposal if you don't mind. I tried to check the proposal but it seems I am unable to run it in my system. Maybe I am missing something. If it is cool with you, can you please tell where to do the changes in the code exactly?

**Comment by lanitochka17** [comment]
@fedirjh Hello Issue is still reproducible on the latest build v1.4.53


https://github.com/Expensify/App/assets/78819774/0b47a59b-82de-45bb-9988-bacce01a68f5

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.53-1


https://github.com/Expensify/App/assets/78819774/6681cf6e-4642-425e-a799-3999657d184f



https://github.com/Expensify/App/assets/78819774/e8090506-fa27-46b1-9097-3f0646e9803b

**Comment by kaushiktd** [comment]
I have attempted to cache the path and re-render from the cached path when offline. However, this approach is not working because `@dotlottie/react-player` utilizes several JavaScript files to render in the web interface. When users go offline, the JavaScript functionality fails due to CORS (Cross-Origin Resource Sharing) policy restrictions. Consequently, the lottie animation fails to render even from cache.

When in offline, the l`oadFromUrl()` function from the `chunk-RRTNX2SD.js` file is called from here.(App-main/node_modules/@dotlottie/react-player/dist/chunk-RRTNX2SD.js)
This function requires online connectivity to fetch the `bufferArray` from the path in order to load the animation.

As a potential solution for the web interface, when users go offline, you could render a fallback, such as a GIF image resembling the lottie animation, or simply leave it plain with a background color.

**Comment by marcochavezf** [comment]
Thanks @fedirjh for the analysis and review of the proposals. After thinking a bit more about this issue, I agree that there's no consistent way to reproduce it on different devices. Also, given our current priorities, I'm going to lean towards closing it and re-opening it later if we think it's still important to fix.
