### ISSUE TITLE
[HOLD for payment 2024-03-22] [HOLD for payment 2024-03-20] [$500] Thread - Thread header shows "Unavailable workspace"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38171]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Right click on the message > Reply in thread

## Expected Result:
The thread header will not show "Unavailable workspace"

## Actual Result:
The thread header shows "Unavailable workspace"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e80b8089-6bac-41ce-8c04-43dd98394b86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ff42a92e62198ae</li>
        <li>Upwork Job ID: 1767656572824260608</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
Production:

![Screenshot 2024-03-13 at 03 46 17](https://github.com/Expensify/App/assets/78819774/dd48863b-f8f1-4604-9798-73fd9f27b326)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment]
Regression from https://github.com/Expensify/App/pull/37030

**Comment by mananjadhav** [comment]
@luacmartins @srikarparsi Can we assign a BZ member here. We need to payout @Tony-MK.

**Comment by luacmartins** [comment]
@trjExpensify could you please help with payouts?

**Comment by mananjadhav** [comment]
Thanks. There will be a payout for @Tony-MK only. I didn't review the fix.

**Comment by trjExpensify** [comment]
Sure thing! @Tony-MK sent you an offer. Payment summary as follows: 

- $500 to @Tony-MK for the fix.

**Comment by trjExpensify** [comment]
Still awaiting @Tony-MK's acceptance of [the offer](https://www.upwork.com/nx/wm/offer/101524388). Once paid, we can close this out.

**Comment by Tony-MK** [comment]
Accepted the offer, Thanks.

**Comment by trjExpensify** [comment]
Paid!
