### ISSUE TITLE
Start chat - Contact list shows up after some delay with skeleton loading

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: User account has a long list of contacts.
1. Go to staging.new.expensify.com.
2. Go to FAB.
3. Click Start chat.

## Expected Result:
The contact list will show up instantly without skeleton loading (production behavior).

## Actual Result:
The contact list shows up after some delay with skeleton loading.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5af90f0c-edef-47df-806c-09cf34eb590b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is fixed in staging
