### ISSUE TITLE
Start chat - Focus is not applied on the first user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38176]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on 'FAB' > 'Start chat'

## Expected Result:
Focus should be applied to the first user display

## Actual Result:
Focus is not applied to the first user displayed on the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2c00a8c7-df96-4e19-8eb4-ae1420de64c4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by dragnoir** [comment]
I think this is not an issue. This is how it should works, it already fix this issue https://github.com/Expensify/App/issues/37800
The old behavior, 1st item selected, was the issue. Now it's fixed I think.

**Comment by chiragsalian** [comment]
Yup thank you @dragnoir. This is not a blocker nor an issue since its addressing this [issue](https://github.com/Expensify/App/issues/37800). 
The [PR](https://github.com/Expensify/App/pull/34356) that addresses that issue is on staging which is why this change is apparent. 
Either way IMO this is not an issue and it looks like the code is going to be reverted so I'll close out this issue.
