### ISSUE TITLE
 Categories - Toggling on Categories/Tag does not actually enable Categories/Tag

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38178]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37755

## Action Performed:
Precondition:
- User is an owner of Collect workspace.
- The Collect workspace has enabled categories.
1. Go to staging.new.expensify.com.
2. Go to workspace settings > Collect workspace.
3. Go to More features.
4. Toggle off Categories.
5. Toggle on Categories.
6. Go to Old Dot and navigate to Categories page of the Collect workspace.

## Expected Result:
The Categories will be enabled on Old Dot because it is reenabled on New Dot in Step 5.

## Actual Result:
In Step 4, toggling off Categories updates the list on Old Dot.
In Step 5. toggling on Categories does not update the list on Old Dot.
The same issue goes for Tags.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2da147a9-b71e-402c-b62d-2c8e6457c8c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-control
CC @trjExpensify

**Comment by AndrewGable** [comment]
@luacmartins - I see you were the main reviewer of the linked PR https://github.com/Expensify/App/pull/37755. Do you think this is related?

**Comment by luacmartins** [comment]
Yes, but this is not an issue. The more features page turns on the feature (shows the page in the LHN in NewDot), not the requirement to categorize/tag expenses. I think we can close this.
