### ISSUE TITLE
 Start chat - Contact list does not scroll back up after clicking Add to group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Scroll down the list
4. Click Add to group

## Expected Result:
The list will scroll back up after clicking Add to group

## Actual Result:
The list does not scroll back up after clicking Add to group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f9fa9823-5fe3-4334-873e-45db4a80450d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@bondydaa  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
Production: 


https://github.com/Expensify/App/assets/78819774/5e1c6d4d-dea1-44d4-b38b-c55c98e785dc

**Comment by luacmartins** [comment]
Likely coming from https://github.com/Expensify/App/pull/34356

**Comment by bondydaa** [comment]
@lukemorawski @rushatgabhane @cristipaval any thoughts here?

**Comment by bondydaa** [comment]
I'm not sure we need to block deploy on this either, somewhat minor UX to me.

**Comment by dragnoir** [comment]
This is not an issue, PR https://github.com/Expensify/App/pull/34356 replaced OptionsSelector with SelectionsList. And not scrolling to the top when we click "add to group" is the correct UX.

**Comment by bondydaa** [comment]
went ended up revering that PR based on this discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1710277358604919?thread_ts=1710274657.315789&cid=C01GTK53T8Q

**Comment by luacmartins** [comment]
This is fixed in staging. Closing
