### ISSUE TITLE
Start chat - Selected members appear when the search query does not match the selected members

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38181]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**. N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to FAB > Start chat.
3. Select a few members.
4. Search for other members.

## Expected Result:
The selected members will not appear on top since the selected members do not match the search query. (production behavior)

## Actual Result:
The selected members appear on top when the selected members do not match the search query..

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/9c155f5f-3e83-4cd0-bd3f-da1996cb926c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to #vip-vsb
cc @quinthar

**Comment by m-natarajan** [comment]
@hayata-suenaga FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by luacmartins** [comment]
This is fixed on staging. Closing.
