### ISSUE TITLE
[HOLD for payment 2024-03-26] [$250] [Wave Collect] [More Features] WS features - App returns to the same WS settings page after toggling on a feature

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38185]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37441
## Action Performed:
Precondition:
- User is an owner of Collect workspace
- The Collect workspace has enabled categories
1. Go to staging.new.expensify.com
2. Go to workspace settings > Collect workspace
3. Go to More features
4. Toggle on any feature (toggle off first if there is disabled feature)
5. Return to previous page via device back navigation

## Expected Result:
App will not return to the same page. App will return to workspace list

## Actual Result:
App returns to the same workspace settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cf0660ba-cd14-417b-9cbd-2a43560614b1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012238c91ec26d9e5d</li>
        <li>Upwork Job ID: 1768644608825819136</li>
        <li>Last Price Increase: 2024-03-15</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control
CC @Jason

**Comment by lanitochka17** [comment]
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment]
Looks connected to https://github.com/Expensify/App/pull/37441 cc @mountiny @rezkiy37 @luacmartins 

The above proposal looks like it will work. But maybe we are already looking into this?

**Comment by luacmartins** [comment]
This is not a blocker since the feature is still WIP and very few people have access to Collect workspaces on NewDot. cc @rezkiy37 can you work on a fix for this one as well?

**Comment by mountiny** [comment]
Head up, just merged the ideal nav v2 so it might influence the solution a bit regarding routes

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
I've tested the bug. The bug is not replicable after the "Ideal Nav V2" merging. I tested on a real Android Device and macOS Chrome. Can you retest also, please?

cc @lanitochka17


https://github.com/Expensify/App/assets/57314631/6f314f56-5a93-4377-8d6e-5763e1683d94

**Comment by rezkiy37** [comment]
However, I agree that the `goBack` looks better and natural. I would create a PR to use `Navigation.goBack(ROUTES.WORKSPACE_INITIAL.getRoute(policyID));`. When we deep-link to the "More features" page for the 1st time, it calls `navigate` with `CONST.NAVIGATION.TYPE.FORCED_UP`, but after the navigation history has been initiated and `goBack` works smoothly.

WDYT, @mountiny?

https://github.com/Expensify/App/assets/57314631/2c25d9e3-9a11-4f36-b79c-7150b91110be

**Comment by rezkiy37** [comment]
One more thing I see is that the app uses a legacy route for the "More features" page.

<img width="1299" alt="Screenshot 2024-03-14 at 17 06 43" src="https://github.com/Expensify/App/assets/57314631/4b8c8bd3-bb20-4a38-b93b-948e6e927c3b">

**Comment by mountiny** [comment]
@rezkiy37 The proposed changes sound good to me, can you make 2 PRs. Once to address the route and other to address the navigation. 

thank you

**Comment by rezkiy37** [comment]
@mountiny, I've opened PRs: https://github.com/Expensify/App/pull/38398, https://github.com/Expensify/App/pull/38396.

**Comment by mountiny** [comment]
Thanks, merged the route one and @ishpaul777 got autoassigned to the other one, making this $250 as its quite easy change

**Comment by zanyrenney** [comment]
Hi! reapplying the bug label as I will be OOO on the 26th March. I am back on April 2nd.

**Comment by zanyrenney** [comment]
Hi @abekkala Just a note to say, I am OOO now until April 2nd, reassigning BZ team member to help while I am OOO.

**Comment by abekkala** [comment]
@zanyrenney I'm going to be ooo as well. It's best practice to check the ooo calendar and reapply if needed.

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 26

- @rezkiy37 does not require payment (Contractor)
- @ishpaul777 $250 [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor)

**Comment by abekkala** [comment]
@bfitzexpensify - @zanyrenney was the original assignment. She is going ooo. 

I've provided the Payment summary above and reapplied the label. I verified that you were not currently on the ooo calendar for Mar 26

Thansk!

**Comment by luacmartins** [comment]
Just pending payment

**Comment by bfitzexpensify** [comment]
All done!

**Comment by bfitzexpensify** [comment]
Hey @ishpaul777 - looks like payment was issued March 27th for **Expensify GH #38185 - Contributor - [$500] [Wave Collect] [More Features] WS features - App returns to the same WS settings page after toggling on a feature** 

Can you check that on your end?
