### ISSUE TITLE
[Simplified Collect][Tags] - "Members must tag all spend" switch is toggled back on after refreshing page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38188]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

 
**Issue found when executing PR** https://github.com/Expensify/App/pull/37755
## Action Performed:
Precondition:
- User is an owner of Collect workspace
- The Collect workspace has tags
- "People must tag expenses" is enabled on Old Dot
1. Go to staging.new.expensify.com
2. Go to workspace settings > Collect workspace
3. Go to Tags
4. Click Settings
5. Toggle off "Members must tag all spend" switch
6. Close the settings RHP
7. Refresh the page
8. Click Settings

## Expected Result:
"Members must tag all spend" switch will remain toggled off

## Actual Result:
"Members must tag all spend" switch is toggled back on after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0b1efc08-89c4-4bb1-ab6c-e82c216c534f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jasperhuangg  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment]
I agree this is NAB since this is still WIP

**Comment by luacmartins** [comment]
Closing in favor of https://github.com/Expensify/App/issues/38192

**Comment by trjExpensify** [comment]
Why did yah reopen it? Do we have more to go here?

**Comment by luacmartins** [comment]
Yea, it was [this PR](https://github.com/Expensify/Auth/pull/10310), but it has been merged and deployed so we're good to close agian.
