### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] Chat - Nested quote markdown is not displayed on compose box when editing message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38199]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4420995
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in.

1. Go to any chat.
2. Send a nested quote message, like "> > > > testing"
3. Tap and hold on the message.
4. Select "Edit comment".
## Expected Result:
All the nested quote markdowns should be displayed on the compose box.

## Actual Result:
Only one quote markdown is displayed on the compose box. Also, if the message is copied, only one quote markdown is pasted.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/3bb5fc64-3ab8-4e82-9004-ac74c16864fb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f12401e8699bc68</li>
        <li>Upwork Job ID: 1767806805110730752</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by kavimuru** [comment]
@MariaHCD FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb
cc @quinthar

**Comment by MariaHCD** [comment]
I don't think this should block the app deploy.

**Comment by MariaHCD** [comment]
In my opinion, this is a low priority bug so I am reducing the bounty on this to $250.

**Comment by allroundexperts** [comment]
Taking over. @MariaHCD Can you assign this to me please?

**Comment by allroundexperts** [comment]
@shubham1206agra Should we put this on hold?

**Comment by MariaHCD** [comment]
@tomekzaw @robertKozik would appreciate your thoughts on this issue!

**Comment by BartoszGrajdek** [comment]
Tomek and Robert are currently busy, I'm looking into it! 👀

**Comment by BartoszGrajdek** [comment]
@andrey010 proposal seems good and it solves the problem we're having, so that's what I would go for 😄 

cc @MariaHCD

**Comment by MariaHCD** [comment]
Thanks for the input, @BartoszGrajdek!

@allroundexperts what you do think of the existing proposal?

**Comment by allroundexperts** [comment]
Looks good to me as well!

**Comment by andrey010** [comment]
I was applied to job in Upwork. PR will ready in next 1-2 day

**Comment by andrey010** [comment]
@MariaHCD hello, who is a manager in Upwork? I already sent proposal

**Comment by andrey010** [comment]
How many times show wait ?

**Comment by MariaHCD** [comment]
@andrey010 - @strepanier03 will be handling the Upwork side of things here.

**Comment by andrey010** [comment]
@strepanier03 hi, could you assign contract on Upwork? I already sent proposal

**Comment by strepanier03** [comment]
Done. @andrey010 - We also have automation in place to hire you so you might get another offer when the PR is merged and that automation takes place. If you get a second offer please let me know so I can cancel one of them.

**Comment by andrey010** [comment]
Added PR into expensive-common lib, waiting for approval

**Comment by andrey010** [comment]
PR ready https://github.com/Expensify/App/pull/39096

**Comment by andrey010** [comment]
@allroundexperts hello please check PR

**Comment by strepanier03** [comment]
I found the contract already paid in Upwork for @andrey010. 

@allroundexperts - Please finish up the checklist and once you do I'll pass this off to Jason for manual payments. I'll check in again tomorrow.

**Comment by strepanier03** [comment]
@allroundexperts - Set ownership of this GH to you for now so that only your response can take it back out of overdue moving forward. 

Please handle the checklist items and I'll move this forward once you do. Thanks for taking care of this!

**Comment by strepanier03** [comment]
@allroundexperts - Please prioritize the checklist so we can close this out.

**Comment by allroundexperts** [comment]
On it today. Apologies for the delay.

**Comment by allroundexperts** [comment]
## Checklist
1. This was not implemented correctly when we released the live markdown feature ie https://github.com/Expensify/App/issues/36227
2. N/A
3. N/A
4. A regression test would be useful here. The test steps in the OP seem clear enough to me.

**Comment by strepanier03** [comment]
### Payment Summary

- $250 - @allroundexperts via Manual Requests

@JmillsExpensify payment request incoming.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
