### ISSUE TITLE
[Wave Collect] [More Features] Enabled features disappear from side bar and are toggled off when relogin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-1
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an owner of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to workspace settings > Collect workspace.
3. Go to More features.
4. Toggle on all the features.
5. Refresh the page.
6. Log out and log in again.
7. Go to workspace settings > Collect workspace.
8. Go to More features.
## Expected Result:
When relogin, all the enabled features will show up on side bar and are toggled on in More features page.

## Actual Result:
When relogin, all the enabled features disappear from side bar and are toggled off in More features page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/5fa8c8fa-6181-478c-8840-2a8fb5f909e8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d3736e9d0e6eebd</li>
        <li>Upwork Job ID: 1767876275777974272</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@madmax330  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by mountiny** [comment]
This is a new feature so not a blocker, I can look into this seems like it will be internal

**Comment by mountiny** [comment]
@kavimuru can you still reproduce this one?

**Comment by mountiny** [comment]
I cannot repro this, I think it was reported when there was some mismatch with the feature flag names, this is fixed now
