### ISSUE TITLE
[HOLD for payment 2024-05-08] [$500] Public room - Login page shows momentarily before showing public room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38212]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4421788
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
precondition: user created a public room and copied the link
1. Log out of ND if logged in
2. Navigate to a public room via deeplink, e.g. https://staging.new.expensify.com/r/1275927936266854

## Expected Result:
The user is navigated to a public room, and the chat history is displayed

## Actual Result:
The user is navigated to the sign-in page. Only after login, the public room is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/57d887c1-fb40-449b-8919-76a418ae4887

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177518535cd3da4f9</li>
        <li>Upwork Job ID: 1770548324502310912</li>
        <li>Last Price Increase: 2024-03-27</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by izarutskaya** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
This is a BE issue where some onyx data is in array.

<img width="590" alt="image" src="https://github.com/Expensify/App/assets/50919443/91f677fb-8610-42cc-beb8-960823e31f4a">
<img width="816" alt="image" src="https://github.com/Expensify/App/assets/50919443/bd87dcee-d524-4877-9674-87618d35454e">

**Comment by c3024** [comment]
PR #38272 of issue #37999 is awaiting fixing of this issue.

**Comment by puneetlath** [comment]
Hmm, so when I try it shows the login page momentarily but then does show the public room after a second. 

https://github.com/Expensify/App/assets/1371996/a98481b2-0496-488e-85f0-72079c1303e5

So @bernhardoj I feel like maybe something changed and this is indeed a client-side issue. What do you think?

**Comment by kmbcook** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Public room - Login page shows momentarily before showing public room

### What is the root cause of that problem?
Onyx network.isOffline is temporarily set to true, causing the splash screen to be hidden too early.

### What changes do you think we should make in order to solve the problem?
Prevent setOfflineStatus from being called when state.isInternetReachable equals null, in code below.
https://github.com/Expensify/App/blob/729d4758be1ca005113148f1dc0dd3f9694ffa5b/src/libs/NetworkConnection.ts#L109

**Comment by getusha** [comment]
@kmbcook tested your solution and i am still able to reproduce the issue.

**Comment by kmbcook** [comment]
@getusha if the link above is used, then the issue can be reproduced because the link is to staging instead of to development in which code changes have been made. I don't know if that is something you have done, but I have mistakenly done that a few times!

Without any code changes I can reliably reproduce the issue by opening a new incognito window each time I want to reproduce. After code changes I have never been able to reproduce.

**Comment by kmbcook** [comment]
I just realized that there are two places where this same change should be made, so I [updated my proposal](https://github.com/Expensify/App/issues/38212#issuecomment-2016276584).

**Comment by allroundexperts** [comment]
Taking over!

**Comment by getusha** [comment]
Asked for another c+ [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1711550007261499), @puneetlath please assign @allroundexperts

**Comment by allroundexperts** [comment]
Reviewing proposals Melv.

**Comment by allroundexperts** [comment]
@tienifr Can you please provide a link to support the following?

> The "assuming we're offline when network status is not determined" was on purpose to prevent performance issues

**Comment by allroundexperts** [comment]
Thanks @tienifr. I agree with @tienifr's [proposal](https://github.com/Expensify/App/issues/38212#issuecomment-2011104467) and the proposed solution. @kmbcook With your proposal, we'll re-introduce the the redundant `ReconnectApps` calls as mentioned above.

🎀 👀 🎀 C+ reviewed

**Comment by puneetlath** [comment]
I think the proposal sounds good, but I'd like to get a little wider visibility on it. Can you post it in #expensify-open-source please @tienifr?

**Comment by puneetlath** [comment]
Alright, let's do it. When can you have a PR ready @tienifr?

**Comment by puneetlath** [comment]
@tienifr can you raise a fix for the regression above?

**Comment by puneetlath** [comment]
@tienifr has been paid. 

@allroundexperts bump on the checklist for you.

**Comment by allroundexperts** [comment]
## Checklist
1. I was not able to find the exact PR which caused this. It seems like several PRs introduced this issue with time.
2. N/A
3. N/A
4. A regression test would be helpful.

## Regression Test
1. Log out of ND if logged in
2. Navigate to a public room via deeplink, e.g. https://staging.new.expensify.com/r/1275927936266854

Verify that the user is navigated to a public room, and the chat history is displayed

Do we 👍 or 👎 ?

**Comment by puneetlath** [comment]
Issue for regression test is here: https://github.com/Expensify/Expensify/issues/394854

Payment summary: 
- C - $500 - @tienifr - paid via Upwork
- C+ - $500 - @allroundexperts - to be paid via NewDot

@allroundexperts please request on NewDot. Thanks everyone!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
