### ISSUE TITLE
iOS - PDF - User can swipe to another attachment when PDF is zoomed in

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4420934
**Email or phone of affected tester (no customers):** vdargentotest+ios031224@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: the user must be logged in.

1. Go to any chat in which some attachments has been sent
2. Tap on any PDF attachment.
3. Zoom in the PDF.
4. Tap one more time for the forward or backward arrows to be displayed.
5. Try to swipe to another attachment.

## Expected Result:
The user should not be able to swipe to another attachment when the PDF is zoomed in.

## Actual Result:
The user is able to swipe to another attachment when the PDF is zoomed in if the forward and backward arrows are displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/71287969-11ff-4599-8e0f-9d41479e7b40

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by joekaufmanexpensify** [comment]
Why is it a bug that you can't swipe between PDFs when zoomed in? That doesn't seem like a bug to me. Closing for now, but LMK if anyone disagrees.
