### ISSUE TITLE
[Held on #20354] [$500] Chat – Second user is highlighted when create a group using keyboard

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38216]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4417998
**Email or phone of affected tester (no customers):** ponikarchuks+713324@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Сlick on FAB
4. Click on "Start Chat"
5. Use the arrow keys, tab key and Enter to select multiple results from the contact lists (at list 3 accounts)

## Expected Result:
Selected user is highlighted when create a group using keyboard

## Actual Result:
Second user is highlighted when create a group using keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2d9dbb67-ef8b-4414-b9cd-7e6f0409d205

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015834298cf682f992</li>
        <li>Upwork Job ID: 1769865643699728384</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by dragnoir** [comment]
HOLD for https://github.com/Expensify/App/pull/34356

**Comment by s77rt** [comment]
Holding on https://github.com/Expensify/App/issues/20354 since https://github.com/Expensify/App/pull/34356 is reverted

**Comment by anmurali** [comment]
Changed the title accordingly. Still holding as https://github.com/Expensify/App/issues/20354 is in progress

**Comment by s77rt** [comment]
New PR that we are holding on is still open https://github.com/Expensify/App/pull/38610

**Comment by s77rt** [comment]
Holding on https://github.com/Expensify/App/pull/38610
@anmurali Can you change the title to "HOLD" instead of "Held"

**Comment by s77rt** [comment]
https://github.com/Expensify/App/pull/38610 is merged. Bug no longer reproducible. Let's close this @anmurali

**Comment by s77rt** [comment]
We can close this one @anmurali

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by s77rt** [comment]
To be closed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by s77rt** [comment]
@anmurali We can close this

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Forth week)

**Comment by s77rt** [comment]
To be closed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Fifth week)

**Comment by s77rt** [comment]
To be closed

**Comment by s77rt** [comment]
@anmurali Please close this

**Comment by s77rt** [comment]
To be closed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (6th week)

**Comment by s77rt** [comment]
To be closed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (7th week) Are we ok to close this?

**Comment by s77rt** [comment]
@anmurali Can you please close this one

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (8th week) 
Closing as there has been no action on this at all for an extended period. 
@anmurali  pls feel free to reopen.
