### ISSUE TITLE
Payment - Missing Pay elsewhere button when Make or track payments is enabled w/o bank account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an admin of Collect workspace.
- "Make or track payments" is enabled in Workspace settings > Workflows.
- Bank account is not set up in the Collect workspace.

1. Go to staging.new.expensify.com.
2. [Employee] Request money in the workspace chat.
3. [Admin] Go to workspace chat with employee > Expense report.
4. Note that Pay elsewhere button is missing.
5. [Admin] Go to workspace settings > Collect workspace > Workflows.
6. [Admin] Toggle off "Make or track payments".
7. [Admin] Return to expense report in Step 3.

## Expected Result:
Pay elsewhere button should show up because "Make or track payments" is only for payment via Expensify.

## Actual Result:
Pay elsewhere button is missing when "Make or track payments" is enabled without bank account.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b234a341-53ba-4f9d-b092-3de49e1bd518

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@Gonals I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Gonals** [comment]
I'm actually not sure either. @thienlnam, I think you are familiar with the new "track" flows. Is this intended?

**Comment by thienlnam** [comment]
I'm unaware of this new selector - seems unrelated to to the 'Track Expense' features that we're building

**Comment by JmillsExpensify** [comment]
This is a simplified collect initiative. The confusion is understandable though given that it says "track" in the toggle description.

**Comment by luacmartins** [comment]
Ok, discussed this internally and the solution for now is:

- Reimbursement enabled, indirect (no VBBA) -> show Pay elsewhere and Pay with Expensify
- Reimbursement enabled, direct (with VBBA) -> show Pay with Expensify
- Reimbursement disabled -> no pay button

**Comment by luacmartins** [comment]
I'm gonna demote this to NAB since it only affects Collect policies for now and those only show up in NewDot if `isPolicyExpenseChatEnabled = true` which means very few people have this enabled. I'm doing this so we can tackle this issue with a more wholistic approach [here](https://github.com/Expensify/App/issues/38254), since a lot of these buttons are incorrect after we introduced Workflows

**Comment by luacmartins** [comment]
I'm closing this issue in favor of https://github.com/Expensify/App/issues/38254
