### ISSUE TITLE
[LOW] [Splits] IOU – Able to send two same IOUs from separate devices Online and Offline without error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4421614
**Email or phone of affected tester (no customers):** ponikarchuks+1013324@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with 2 separate accounts in the main testing device and a secondary device
2. Disable the internet connection in the main testing device
3. From the main + menu, create a money request with the account logged in the secondary device
4. In the secondary device request money to the main testing device account
5. Enable the internet connection in in the main testing device

## Expected Result:
The money request will be sent and will get a response an error. The chat row in the LHN appears greyed out with a solid red dot icon

## Actual Result:
There is no error message when send two same IOUs from separate devices Online and Offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ebb4b207-0e51-42cc-a651-f06f4f83c387

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by alexpensify** [comment]
No update, on my testing list.

**Comment by alexpensify** [comment]
I started a discussion here: 

https://expensify.slack.com/archives/C066HJM2CAZ/p1710957959208909

**Comment by alexpensify** [comment]
Figured out that the discussion was in the wrong project, I've asked for feedback in the right place here: 

https://expensify.slack.com/archives/C05RECHFBEW/p1711041804518259

**Comment by alexpensify** [comment]
Tomorrow, I'll bump again for feedback.

**Comment by alexpensify** [comment]
After chatting with the curator for this project, this one is an edge case and we decided it's best to close it.
