### ISSUE TITLE
[Clean-up] Unify the logic for getting alternateText for getOptions and getOptionData

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38220]
Stemming from improvements to the LHN previews https://github.com/Expensify/App/issues/34411

The [getOptions](https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/libs/OptionsListUtils.js#L1063) and getOptionData methods get the alternateText differently as highlighted in the PR review here https://github.com/Expensify/App/pull/33966#discussion_r1444808394

To improve the DX it would be great to unify this logic and ideally simplify it if possible.

@koko57

**Comment by mountiny** [comment]
@koko57 are there any next steps for this one?

**Comment by koko57** [comment]
First I would identify how much of the code from here https://github.com/Expensify/App/blob/4a7014b980c6dc50cab671525ba017ceec5a8bdd/src/libs/OptionsListUtils.js#L512-L542 (it's in createOption not getOption now) and here https://github.com/Expensify/App/blob/3ee24ec7868be996c78e1ae8097899ebdf33a709/src/libs/SidebarUtils.ts#L326-L433 can be shared and moved out to shared util function. I started back then with moving the logic for getting last actor displayName to getLastActorDisplayName function. I'm also still thinking that maybe it would be good to create a doc with alternateText examples for each type of the chat for both Sidebar and Search Page. But it's something that I'd definitely leave after all higher-priority issues are done 🙂

**Comment by koko57** [comment]
ok, I agree! I still remember and will remember of this one. We can come back to this one later 🙂
