### ISSUE TITLE
[HOLD #37397] Category - Disabled category does not show up in search result

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- The Collect workspace has categories and tags
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a manual request with category and tag
4. As admin, disabled the category and tag in Step 3
5. As employee, go to request details page
6. Click Tag
7. Search for the disabled tag via search
8. Click Category
9. Search for the disabled category via search

## Expected Result:
The disabled category will show up in the search result, just like disabled tag in Step 7

## Actual Result:
The disabled category does not show up in the search result

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/74ca7b63-833f-455d-8b45-81f9407de492

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment]
Good 👀 @Krishna2323 , put on hold pending
- https://github.com/Expensify/App/pull/37397

**Comment by mallenexpensify** [comment]
- https://github.com/Expensify/App/pull/37397

Above is slowly moving along

**Comment by mallenexpensify** [comment]
Commented on the [issue ](https://github.com/Expensify/App/issues/38226)and [PR](https://github.com/Expensify/App/pull/37397#issuecomment-2026288083) we're holding on.

**Comment by trjExpensify** [comment]
Yeah, I think your currently selected category value should still be shown in the selection list. Once you deselect it, it should disappear.

**Comment by mallenexpensify** [comment]
Thanks @trjExpensify , gonna close this cuz the actual behaviour is what you and I expect.
