### ISSUE TITLE
Workspace - Red dot appears without error message when changing currency to non-USD currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-3
**Reproducible in staging?:** y
**Reproducible in production?:** y

## Action Performed:
Precondition:
- User is an owner of Collect workspace.
- USD is the default currency for the workspace.
- Bank account is not added to the Collect workspace.
1. Go to staging.new.expensify.com.
2. Go to workspace settings > Collect workspace.
3. Go to Workflows.
4. Toggle on "Make or track payments".
5. Go to workspace profile.
6. Click Currency.
7. Change it to a different currency.

## Expected Result:
If there is an error, an error message will show up.

## Actual Result:
Red dot appears next to Profile without error message and there is no way to dismiss it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d2073698-9ca8-4270-a85c-a2b4386c8509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
Closing this in favour of https://github.com/Expensify/App/issues/38206 where we are going to handle other error messages too
