### ISSUE TITLE
[HOLD for payment 2024-04-05] [Simplified Collect][Taxes] Optimistically create default tax rates

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#38234]
Coming from [this PR](https://github.com/Expensify/App/pull/37870) and [this comment](https://github.com/Expensify/App/pull/37870#issuecomment-1994089887), we need to optimistically create default tax rates when enabling the `Tax` feature on the `More features` page. 

This issue has two parts to it.

1. We need to optimistically create the default rates in App when enabling the feature
2. The backend needs to process the created rates and store it in the DB

cc @filip-solecki @kosmydel

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Optimistically create default tax rates
### What is the root cause of that problem?
- We do not have a logic to create the optimistic tax data once when enabling the feature
### What changes do you think we should make in order to solve the problem?
- Generally, when enabling the tax feature, we need to set the ```policy.taxRates``` if it is not set yet:
```
{
    "defaultExternalID": "id_TAX_EXEMPT",
    "defaultValue": "0%",
    "foreignTaxDefault": "id_TAX_EXEMPT",
    "name": "Tax",
    "taxes": {
        "id_TAX_EXEMPT": {
            "name": "Tax exempt",
            "value": "0%"
        },
        "id_TAX_OPTION_1": {
            "name": "Tax option 1",
            "value": "5%"
        }
    }
}
```
- Below is the details steps:
1. Create a ```optimisticTaxRatesData```:
```
    const optimisticTaxRatesData = {
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
        value: {
            tax: {
                trackingEnabled: enabled,
            },
            taxRates: {
                defaultExternalID: 'id_TAX_EXEMPT',
                defaultValue: '0%',
                foreignTaxDefault: 'id_TAX_EXEMPT',
                name: 'Tax',
                taxes: {
                    id_TAX_EXEMPT: {
                        name: 'Tax exempt',
                        value: '0%',
                    },
                    id_TAX_OPTION_1: {
                        name: 'Tax option 1',
                        value: '5%',
                    },
                },
            },
        },
    };
```
2. Used the condition ```isEmpty(policy.taxRates) && enabled``` to decide whether we should use the above optimisticData or not
### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment]
@luacmartins  Can contributor work on this issue?

**Comment by luacmartins** [comment]
Yes, I think that'd be ok if you can prioritize this issue and get a PR up in a day.

**Comment by nkdengineer** [comment]
@luacmartins Sure thanks. I am working on it

**Comment by nkdengineer** [comment]
I am working on it

**Comment by DylanDylann** [comment]
@luacmartins This issue comes from https://github.com/Expensify/App/pull/37870, If we need a C+ to review PR, I am happy to take over as a high-priority

**Comment by nkdengineer** [comment]
@luacmartins The PR https://github.com/Expensify/App/pull/38375 is ready to review

**Comment by rojiphil** [comment]
@MelvinBot @trjExpensify I was a reviewer for the PR as can be seen [here](https://github.com/Expensify/App/pull/38375#issuecomment-2000452846)

**Comment by trjExpensify** [comment]
Assigned you so we track that, @rojiphil. Confirming the number of regressions here. One [false positive](https://github.com/Expensify/App/issues/38234#issuecomment-1997777641), one [legit](https://github.com/Expensify/App/issues/38234#issuecomment-2017696333). Sound right?

**Comment by luacmartins** [comment]
@trjExpensify I this [this one](https://github.com/Expensify/App/issues/38234#issuecomment-2017696333) is also a false positive, since the [comment](https://github.com/Expensify/App/issues/38859#issuecomment-2017696240) in the linked issue mentions that this PR is solving it. So I don't think we had any legit regressions on this one.

**Comment by rojiphil** [comment]
@trjExpensify Offer accepted. Thanks.

**Comment by trjExpensify** [comment]
Settled up with you both!
