### ISSUE TITLE
[$500] Sign out - User has to sign out twice after being redirected to ND from OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38233]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Sign in in OD with a gmail account that already has an expensify account
2. After being redirected to ND on sign in Go to profile > Sign out

## Expected Result:
User should be signed out immediately

## Actual Result:
User has to go to profile and sign out twice inorder to sign out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eaca1a37-b752-44ea-869d-be08a606d84d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f2b22869685881d</li>
        <li>Upwork Job ID: 1772755266778116096</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
Apologies, I was OOO last week. I'll take a look at this shortly

**Comment by greg-schroeder** [comment]
This is technically a backwards compatibility issue so I think it fits best in #wave-collect

**Comment by greg-schroeder** [comment]
Bump @eVoloshchak

**Comment by greg-schroeder** [comment]
Friendly bump @eVoloshchak

**Comment by eVoloshchak** [comment]
The bug isn't reproducible for a newly created account and redirecting from OD to ND doesn't happen for an already existing account. @GandalfGwaihir, @HezekielT, could you please check if this is still reproducible and if the redirect is happening?

https://github.com/Expensify/App/assets/9059945/4e2c1986-9137-4f99-b7eb-490b8011727b

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
