### ISSUE TITLE
Bank account - Workspace default currency becomes accessible after opening bank account RHP

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38230]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace settings > Free workspace > Bank account.
3. Add a bank account.
4. Refresh the page.
5. Go to workspace profile > Currency.
6. Note that Currency is not clickable.
7. Click Bank account.
8. Close the RHP.
9. Go to workspace profile > Currency.

## Expected Result:
The workspace currency list will not be accessible because a US bank account is added.

## Actual Result:
The workspace currency list becomes accessible after reopening bank account when US bank account is added.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/319eb65f-8614-4897-9952-b9bd7efe0552

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
Same issue as https://github.com/Expensify/App/issues/36376

**Comment by MitchExpensify** [comment]
Closing because dupe
