### ISSUE TITLE
App download - Tab does not close after tapping "x" on download popup

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.51-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38032
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Access staging.new.expensify.com on Safari (PR asks for Safari) or on MAC Desktop app
2. Sign into a valid account
3. Go to Settings >> About >> App download links >> macOS
4. Close the download prompt

## Expected Result:
According to the PR, the new tab should close. The tab closes on mweb and on the iOS app

## Actual Result:
The tab does not close after download prompt is closed on mac browser and on mac desktop app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f8f20d9a-75b8-49f8-a335-9966b074060e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by godofoutcasts94** [comment]
That's not the case i.e. the new tab is closing for me. 

https://github.com/Expensify/App/assets/158435970/e4dc3ab1-053f-43aa-89ac-4e578a9818ba

**Comment by kadiealexander** [comment]
Yeah I can't repro this either, closing. 



https://github.com/Expensify/App/assets/59587260/fa01f018-4a4d-4ee7-82e0-177dee793a9a
