### ISSUE TITLE
[$500] Chats with GBR sporadically disappear

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38246]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710272695824649

## Action Performed:
(Not 100% sure how to reproduce this issue, though these steps might work)
1. Make sure that at least two reports awaiting approval appear in your LHN
2. Tap into a row with GBR
3. Tap into another row with GBR

## Expected Result:
Reports with GBR persistently stay in the LHN, show GBR until the required action is taken

## Actual Result:
Reports with GBR completely disappear from the LHN. You have to manually find them and open the report for GBR to re-apply

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01192bb71a0c08940e</li>
        <li>Upwork Job ID: 1772360579500888064</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Have not been able to reproduce this yet.

**Comment by zanyrenney** [comment]
Have asked Jason in the channel if he has a video for behaviour so that we can try and triage it here.

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1710838676038639?thread_ts=1710272695.824649&cid=C049HHMV9SM

**Comment by zanyrenney** [comment]
we're waiting for @JmillsExpensify to provide a screen recording when this next happens.

**Comment by zanyrenney** [comment]
Just a note to say, I am OOO now until April 2nd, reapplying the bug label for someone to watch over whilst I am OOO.

**Comment by johncschuster** [comment]
Jason is still experiencing this but was unable to capture the video. I'm not going to let the lack of video block us from pushing this forward.

**Comment by johncschuster** [comment]
No proposals yet. I'm not able to reproduce this myself. @JmillsExpensify, have you seen this one again?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment]
I still can't reproduce this, and it seems like @mvtglobally also can't, I'm hesitant to keep this open without a video and reproduction. I think we could reopen this if we see it is an issue in future instead. what do you think @johncschuster

**Comment by johncschuster** [comment]
I'm fine with that approach! We can always reopen if we can catch this on video!
