### ISSUE TITLE
[Instant Submit] Customer was part of instant submit migration and now they cannot edit expenses

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#38259]
Customer email: mikebennett.ags@gmail.com

Reproduction steps:
- Go to existing report (ID: `6048529644764805`) which is in the `processing` state
- Attempt to edit an expense
- Get a server error ([logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22863e7f922ad261fd-ORD%22)+AND+timestamp:[2024-03-13T18:40:53.554Z+TO+2024-03-13T20:40:53.554Z]&index=logs_expensify-027282))

When clicking on an expense from the report page (try one from Dec 22, 2023), there is a console error:

```
module-app.59dd24ef.js.gz:54 Uncaught TypeError: Cannot read properties of null (reading 'isFree')
    at T (module-app.59dd24ef.js.gz:54:33677)
    at module-app.59dd24ef.js.gz:54:27461
    at n (module-vendor.d32ee547.js.gz:1:248618)
    at Object.add [as done] (module-vendor.d32ee547.js.gz:1:248923)
    at x (module-app.59dd24ef.js.gz:54:27390)
    at s (module-app.59dd24ef.js.gz:54:12948)
    at n._init (module-app.59dd24ef.js.gz:54:52862)
    at n.construct (module-class.73625164.js.gz:25:910)
    at new n (module-class.73625164.js.gz:25:3133)
    at o._init (module-app.59dd24ef.js.gz:52:1569)
```

I opened up [a thread on Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1710365054392389) about this and it looks like @cristipaval might know what is going on here or how to help the customer.

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by cristipaval** [comment]
Self-assigning this to do some investigation

**Comment by trjExpensify** [comment]
@garrettmknight filing this one under Instant Submit.

**Comment by CortneyOfstad** [comment]
Thanks @trjExpensify!

@cristipaval just checking on an ETA here — if you feel that this is lower priority, I can adjust the time label from `daily` to something else. Thanks!

**Comment by cristipaval** [comment]
I'll look into this one again today.

**Comment by cristipaval** [comment]
I didn't get the chance to look into this one yesterday. I plan to create a CQ to see if we can figure out anything related to the Workspace that the report initially belonged to.

**Comment by CortneyOfstad** [comment]
Sounds good @cristipaval — thank you!

**Comment by CortneyOfstad** [comment]
@cristipaval any updates? Thanks!

**Comment by cristipaval** [comment]
I just supportaled the user again, and they seem to have successfully updated a transaction 2 days ago. They also exported the report and another one is Open now. @tgolen have you got any other news from the user?

**Comment by cristipaval** [comment]
@tgolen is now ooo. I'm making this a `Weekly` until he comes back. I'll keep an eye on the user account and see if they continue having activity with the new report.

**Comment by cristipaval** [comment]
I'm thinking of closing this issue given that the customer managed to export the problematic report. He now has a new report automatically created by Concierge, and everything looks right.

@tgolen @CortneyOfstad feel free to reopen if you think we still need to spend time on this one.
