### ISSUE TITLE
[HOLD for payment 2024-03-29] [Simplified Collect][Profile] Implement default description and invite messages

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#38268]
cc @narefyev91 from the Simplified collect [design doc](https://docs.google.com/document/d/1Qv6V4nRqIbZfzQML_saCbrAEqQVIBsiQ3HE1UO7RCxQ/edit#bookmark=id.es4yw85uhb3t) we need to make updates to the default description and invite messages.

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by narefyev91** [comment]
Hi! I'm Nicolay from Callstack - expert contributor group. I'll work on this issue so please assign me. Thank you.

**Comment by getusha** [comment]
@luacmartins could you assign me here? thanks

**Comment by luacmartins** [comment]
Done

**Comment by luacmartins** [comment]
Just pending payment

**Comment by luacmartins** [comment]
Waiting on payment

**Comment by luacmartins** [comment]
Bump for payment @JmillsExpensify

**Comment by luacmartins** [comment]
Bump for payment @JmillsExpensify

**Comment by JmillsExpensify** [comment]
Payment summary

 - Contributor: No payment necessary
 - Contributor+: @getusha $500

**Comment by JmillsExpensify** [comment]
C+ contract paid and regression test created. Closing this one!
