### ISSUE TITLE
[HOLD for payment 2024-03-25] Profile avatar is not aligned within highlighted circle

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause internal team
**Slack conversation:** 

## Action Performed:
Precondition: Device font size is minimum.

1. Launch New Expensify app.
2. Go to Profile.
## Expected Result:
Profile avatar is aligned within highlighted circle

## Actual Result:
Profile avatar is not aligned within highlighted circle
Reproducible in SG Note 10+ / Android 12 , SG Z Fold 4 / Android 14,iPhone 15 Pro Max / iOS 17.3.1
## Workaround:
visual
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6412856_1710369724081!Screenshot_20240314_042548_New_Expensify](https://github.com/Expensify/App/assets/38435837/3d9e2a77-7ded-4ad1-8e9c-046a1d8089ab)

<img src= “https://github.com/Expensify/App/assets/38435837/3d9e2a77-7ded-4ad1-8e9c-046a1d8089ab” width=“40%” height=“40%“>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e3c16578ce4b6d1</li>
        <li>Upwork Job ID: 1768105574093357056</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by robertjchen** [comment]
Not a deploy blocker. Opening for External Contributors

**Comment by kosmydel** [comment]
Hey, I'm from Software Mansion. I will work on this.

**Comment by kosmydel** [comment]
This one is related to https://github.com/Expensify/App/pull/38463.

**Comment by kosmydel** [comment]
This one is related to https://github.com/Expensify/App/pull/38463.
