### ISSUE TITLE
[$500] Workspace - App does not open WS chat after creating a new workspace and returning to Chats

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Open workspace switcher.
3. Click + icon.
4. Return to Chats via Chat icon.

## Expected Result:
Chats will open the newly created workspace chat (production behavior).

## Actual Result:
Chats open the last chat instead of workspace chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d99085d9-4ee3-47d3-9271-c91f9a70c671

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141b4522dd13095c1</li>
        <li>Upwork Job ID: 1768259210734514176</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@MariaHCD I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chats open the last chat instead of workspace chat.

### What is the root cause of that problem?

After Idea nav2 is complete, workspace setting is moved to `FullScreenNavigator` and when we create a new workspace we don't switch navigate to new policy so after we back to chat, the active policy isn't changed

https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/libs/actions/App.ts#L332
### What changes do you think we should make in order to solve the problem?
We should switch the active `policyID` here before navigating to workspace initial page

```
Navigation.navigateWithSwitchPolicyID({policyID});
Navigation.navigate(ROUTES.WORKSPACE_INITIAL.getRoute(policyID));
```

https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/libs/actions/App.ts#L332
### What alternative solutions did you explore? (Optional)
NA

**Comment by jjcoffee** [comment]
@nkdengineer Since this is a deploy blocker, are you able to identify the PR that caused this?

**Comment by nkdengineer** [comment]
@jjcoffee This PR https://github.com/Expensify/App/pull/37421 cause this.

**Comment by luacmartins** [comment]
@WojtekBoman @mountiny seems like a regression from ideal nav v2

**Comment by mountiny** [comment]
I think this does not have to be a blocker, I will assign myself and discuss if we want to keep this behaviour in the new design

**Comment by mountiny** [comment]
@kosmydel this is not about selecting the workspace or not

When new workspace was created, the user was navigated to the admins room before this change, not to the settings

**Comment by nkdengineer** [comment]
When we create a new workspace, I think we can switch policy before we navigate to the setting workspace so after we click on back button in header of setting page, we can see the releated reports of the new workspace.

**Comment by mountiny** [comment]
After discussing this is now going to be expected, not all workspaces will have admin rooms  https://github.com/Expensify/App/issues/36236 so navigating to settings is the best option.

@kavimuru @izarutskaya @isagoico Could you update testRail about this?

**Comment by isagoico** [comment]
This TC should cover this behavior - [Workspace Creation - Online](https://expensify.testrail.io/index.php?/cases/view/2661771) 

![image](https://github.com/Expensify/App/assets/44479856/d175bcef-3b03-4664-94dc-86ef7057940c)
