### ISSUE TITLE
[HOLD for payment 2024-03-25] [Wave Collect] [Tags] Tag - Tag row is not grayed out when created offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/38158

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an admin of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Tags.
4. Go offline.
5. Click Add tag.
6. Add a tag.

## Expected Result:
Tag row is grayed out when created offline

## Actual Result:
Tag row is not grayed out when created offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3e01a50b-3ca6-4888-9deb-0272fb063b3b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@madmax330 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag row is not grayed out when created offline


### What is the root cause of that problem?


We don't get the pendingAction of tag when get the tag list to display in `WorkspaceTagsPage`

https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L72
### What changes do you think we should make in order to solve the problem?
We should add `pendingAction: value. pendingAction` here.

https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L72
### What alternative solutions did you explore? (Optional)
NA

**Comment by allroundexperts** [comment]
@ikevin127 That is not the offending PR. We just added the form for creating the tag. The list was done as part of another PR. @luacmartins @mountiny I think we discussed the issues with the list itself during the PR review. I can take over these as part of the original issue and raise a PR today if that works.

**Comment by luacmartins** [comment]
Yes, this should be addressed as part of the project. cc @waterim

**Comment by allroundexperts** [comment]
PR created @luacmartins @mountiny 

https://github.com/Expensify/App/pull/38332

**Comment by mallenexpensify** [comment]
I'm a lil confused and looking for help.  I have this issue which came from the [PR test steps for this issue](https://github.com/Expensify/App/pull/38332)
- https://github.com/Expensify/App/issues/38410

Why would y'all be able to follow the steps to pass the tests but QA isn't? 
I can't remember seeing another bug report like this.

**Comment by mountiny** [comment]
You can execute the stuff in console only in dev mode locally, no on actual staging/ production

**Comment by mountiny** [comment]
The first snippet there is in oldDot where you can do it

Onyx snippet cannot be run in staging

**Comment by slafortune** [comment]
@allroundexperts when you get a chance, can you complete the checklist so I can make the payments on Monday?

**Comment by luacmartins** [comment]
No need to regression steps on this one as we'll add it as part of the design doc.

**Comment by slafortune** [comment]
@ishpaul777 invite sent [here](https://www.upwork.com/ab/applicants/1768266101541556224/pending)

**Comment by allroundexperts** [comment]
@slafortune It was decided by @luacmartins and @mountiny that the compensation for https://github.com/Expensify/App/pull/38158 would cover this PR as well. As such, there isn't a payment required here.

**Comment by slafortune** [comment]
AH!  Thanks for those details @allroundexperts, I missed that!  We'll just leave this unit the 25th 👍
