### ISSUE TITLE
[HOLD for payment 2024-03-25] [HOLD for payment 2024-03-22] [$500] Email Replaces Workspace Room Title When Selecting Admin or Announcement in "Share Somewhere"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38294]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Step 1: Click on FAB > Assign Task.
Step 2: Add a title.
Step 3: Click on "Share Somewhere" and select Admin or Announcement.
Step 4: Notice that instead of adding Admin or Announcement as a title, it adds the main email or displayed name.

## Expected Result:
The workspace room title should be displayed instead of the email or displayed name when selecting Admin or Announcement for "Share Somewhere" during task assignment.

## Actual Result:
Email or name is displayed instead of the workspace room title when using Admin or Announcement in "Share Somewhere" during assigned tasks.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5bb1884e-3922-4b37-b892-ef6aa2fbaf08

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01880dea68afc9b014</li>
        <li>Upwork Job ID: 1768297023211061248</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@Gonals I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by mountiny** [comment]
@pasyukevich from Callstack can look into this one

**Comment by Gonals** [comment]
@pasyukevich, are you actively working on this? Note it is a deploy blocker

**Comment by pasyukevich** [comment]
@Gonals Yes, this fix is my main focus now

**Comment by luacmartins** [comment]
Got a draft PR - https://github.com/Expensify/App/pull/38348

**Comment by luacmartins** [comment]
PR ready for review

**Comment by luacmartins** [comment]
Fixed in staging 
![Screenshot 2024-03-14 at 2 21 04 PM](https://github.com/Expensify/App/assets/22219519/951941f5-aa7e-4a1a-8a05-01723ffaf2e4)

**Comment by luacmartins** [comment]
Keeping the issue open to pay @parasharrajat for the review.

**Comment by luacmartins** [comment]
Just pending payment.

**Comment by trjExpensify** [comment]
Yup, back today! Payment summary as follows: 

- $500 to @parasharrajat for the C+ review

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
