### ISSUE TITLE
[HOLD for payment 2024-05-07] [$250] Android - Room-Tapping create room with specific description directs to concierge page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38293]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4426548
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab-- start chat --- Room
3. Enter room name
4. Paste the below text in room description
# we can close this to focus on more urgent issue this is just a minor viewing discrepancy
~*_can close this to focus on more urgent issue this is just a minor viewing discrepancy_*~
```
can close this to focus on more urgent issue this is just a minor viewing discrepancy
```
> *can close this to focus on more urgent issue this is just a minor viewing discrepancy*
5. Tap create room

## Expected Result:
When user taps create room, he must be directed to room page and must not be redirected to concierge page

## Actual Result:
When user taps create room with specific text entered in room description. , he is directed to room page but within seconds redirected to concierge page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3cceba5d-cd92-47c7-bd7c-eb43e0279f33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171e588018217e1f4</li>
        <li>Upwork Job ID: 1772221395416739840</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>rmm-fl | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
Applying `External`

**Comment by greg-schroeder** [comment]
Re-assigning C+ - @shubham1206agra do you mind taking a look at the proposals above? Thanks!

**Comment by greg-schroeder** [comment]
Bump @jasperhuangg on confirming contributor selection above :)

**Comment by jasperhuangg** [comment]
Agree that @rmm-fl's proposal is simpler and less prone to bugs, let's move forward with their proposal.

**Comment by greg-schroeder** [comment]
PR is merged. Awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment]
Payments made.
