### ISSUE TITLE
[Hold for payment 2024-04-29][$500] Chat - Video - Mute status icon is inconsistent between full screen mode and mini player mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38307]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Send a video as an attachment inside of a chat
2. Open the video in full screen mode
3. Mute the video
4. Go out of full screen mode and observe the sound icon

## Expected Result:
The sound icon should turn to mute indicator

## Actual Result:
The sound icon does not show mute icon instead is still in its previous mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f7cd445c-e905-44a9-9d67-b72a333f8733

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01412339609ab3cb7a</li>
        <li>Upwork Job ID: 1768677627492872192</li>
        <li>Last Price Increase: 2024-03-29</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>shahinyan11 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Video - Mute status icon is inconsistent between full screen mode and mini player mode
### What is the root cause of that problem?
Our custom video controller use `updateVolume` and `volume` from [VolumeContextProvider](https://github.com/Expensify/App/blob/d4eaf4e2deabb6c07736b1eaefaa203cc9cf5850/src/components/VideoPlayerContexts/VolumeContext.tsx#L9C10-L9C31)  to update the volume and display the UI. But `fullscreen` displays native video controller, which does not call `updateVolume` when the volume is updated and because of this the volume icon is not updated when we returns back
### What changes do you think we should make in order to solve the problem?
Adding below code [here](https://github.com/Expensify/App/blob/0cbe01f6b6788a3a82a79033130b009daa16cc91/src/components/VideoPlayer/BaseVideoPlayer.js#L124) will fix the error
```
if ( e.fullscreenUpdate === VideoFullscreenUpdate.PLAYER_DID_DISMISS) {
    currentVideoPlayerRef.current.getStatusAsync().then((status) => {
        if(status.volume === 0 || status.isMuted === true){
            updateVolume(0)
        }
    });
}
```

But there is one problem too.  If we mute the video before opening full screen mode, then pressing on the volume icon does not cause any effect. The reason is that the native controller is displayed in full screen mode (as I described above), and it does not unmute  video audio if its volume is set to "0".  But we set default volume to `0` [here](https://github.com/Expensify/App/blob/aca0f8cafb664c16fc10826c466595367d3e7c3b/src/components/VideoPlayerContexts/VolumeContext.tsx#L11C5-L11C38) and  besides it when we press on volume icon to mute the video , we [here](https://github.com/Expensify/App/blob/aca0f8cafb664c16fc10826c466595367d3e7c3b/src/components/VideoPlayerContexts/VolumeContext.tsx#L18C13-L18C105) also set the volume to `0` . We should use two different functions to mute and update volume.

### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment]
Asking for help on which project this belongs to here -https://expensify.slack.com/archives/C01SKUP7QR0/p1710520232153099

**Comment by lschurr** [comment]
@mkhutornyi - could you review the proposal?

**Comment by shahinyan11** [comment]
> @shahinyan11 thanks for the proposal. Does your solution also cover the reversed case?

No. To fix the reversed case, we need to make changes in several places.

**Comment by kaushiktd** [comment]
This issues is not reproducible.

**Comment by shahinyan11** [comment]
@kaushiktd I can reproduce it in the latest version

**Comment by lschurr** [comment]
Where are we at on this one @mkhutornyi?

**Comment by shahinyan11** [comment]
@mkhutornyi don't you have any feedback on my proposal?

**Comment by shahinyan11** [comment]
> You said above and didn't want to update proposal before confirmation. So I asked expected behavior.

Yes but I provide proposal for fixing inconsistent. The root cause of second issue is different and I think it would be better to open new issue for that one

**Comment by lschurr** [comment]
Asking in Slack about expected behavior: https://expensify.slack.com/archives/C01GTK53T8Q/p1711381704207499

**Comment by mallenexpensify** [comment]
@mkhutornyi is unexpectedly going to be OOO for a while, @jayeshmangwani , can you please take over as C+ here? If it doesn't work for you, please post in #contributor-plus

**Comment by jayeshmangwani** [comment]
@mallenexpensify bumped on the slack for more eyes for the expected behaviour of the issue

**Comment by jayeshmangwani** [comment]
@shahinyan11 If we will decided to fix the inconsistency between the fullscreen and mini player mode, then we need to fix the [reversed case](https://github.com/Expensify/App/issues/38307#issuecomment-2004836573) too in this issue, and also need to fix for all the Platforms, IMO we should not create a new issue for the reversed case.

**Comment by shahinyan11** [comment]
@jayeshmangwani  There is not reversed case which cause inconsistence . I want that you understand me correct those are different issues and the bug you call `reversed case` is absolutely different bug. To solve the second problem, we need to change the custom video control logic. Changes should be made in multiple files

**Comment by shahinyan11** [comment]
@jayeshmangwani Ok I will create a PR with all necessary changes

**Comment by shahinyan11** [comment]
[Here](https://github.com/shahinyan11/Expensify/tree/issue/38307) is the branch which covers all errors. 
But there is something left to discuss. I already mentioned above that the native controller does not unmute the volume if it was lowered to 0 through the volume sensor. 
**Here a question arises. How should work our custom video controller in this case ?**

**Comment by jayeshmangwani** [comment]
@shahinyan11 I have tried to add [this code](https://github.com/Expensify/App/issues/38307#issuecomment-1998334705) on `src/components/VideoPlayer/BaseVideoPlayer.js` component to `handleFullscreenUpdate` useCallback function, but this does not solve the initial issue 

https://github.com/Expensify/App/assets/35371050/d78a2190-d208-4b64-af1a-145753a1dbb1

Steps:

1. Open video in mini player with sound On
2. Go to fullscreen mode and sound is On and thats expected
3. Press mute button in fullscreen mode
4. Go to mini player mode > Observe the Mute button
5. Expected is that button is on the Mute if we have Muted in mini player mode

@shahinyan11 Can you please confirm if these steps are working fine on your side, and what results you are getting ?

**Comment by shahinyan11** [comment]
@mallenexpensify Are you added `const {updateVolume} = useVolumeContext();`  in component ?

**Comment by jayeshmangwani** [comment]
We're still evaluating proposal, I have faced few inconsistencies between the Sound icon and the volume slider, making the list of that inconsistencies.

**Comment by shahinyan11** [comment]
> We're still evaluating proposal, I have faced few inconsistencies between the Sound icon and the volume slider, making the list of that inconsistencies.

Could you please check if the inconsistencies you found are still relevant in the branch I shared [here](https://github.com/Expensify/App/issues/38307#issuecomment-2027096692)?

**Comment by jayeshmangwani** [comment]
@shahinyan11 Yes sure I'll compare it  with the mentioned branch , give me some time I need to compare it one by one, and in some time I'll post all the test cases here

**Comment by jayeshmangwani** [comment]
@shahinyan11 Except the original GH description issue, I found the below bugs at the time of testing the Sound between fullscreen player => mini player, mini player => fullscreen player 

please check with your code that does any of the below bugs will be solved in that, as your this [code](https://github.com/Expensify/App/issues/38307#issuecomment-1998334705) only solves the mentioned GH issue, and I also feel that volume value should be synced between 

- Mini player => Fullscreen Player,
- Fullscreen Player => Mini player.

<details>
  <summary>Bug 1</summary>


1. Send a video as an attachment inside of a chat
2. Open the video in full screen mode
3. Use the slider to adjust the sound and set the sound to 0, We can see mute Icon
4. Go out of full screen mode and observe the sound icon
5. The sound icon does not show mute icon instead is still in its previous mode

</details>

<details>
  <summary>Bug 2</summary>


1. Send a video as an attachment inside of a chat
2. Open the video in full screen mode
3. Mute the video, go to any other tab or any other application
4. Go back to fullscreen video tab, observe the sound icon
5. The sound icon does not show mute icon instead is still in its previous mode

</details>
<details>
  <summary>Bug 3</summary>


1. Send a video as an attachment inside of a chat
2. Open the video in full screen mode
3. Mute the video, go to any other tab using the chrome short cut (command + (any other tab number))
4. Go back to tab where app was open
5. Video will displayed in the mini player and observe the sound icon
6. The sound icon does not show mute icon instead is still in its previous mode

</details>

**NOTE: If you feel that any of the above Bug should be handled separately please let us know**

**Comment by shahinyan11** [comment]
@jayeshmangwani Update in [this](https://github.com/shahinyan11/Expensify/tree/issue/38307) branch covers all 3 bugs mentioned in [this comment](https://github.com/Expensify/App/issues/38307#issuecomment-2028912880)

**Comment by jayeshmangwani** [comment]
@shahinyan11 Your [proposal](https://github.com/Expensify/App/issues/38307#issuecomment-1998334705) needs to be updated; please update the proposal on how we are going to handle the volume value and the Mute Icon status and vice-versa. Code changes and minor details can be changed in PR; update the proposal for a high-level overview of the changes.

**Comment by shahinyan11** [comment]
@jayeshmangwani  Sorry, my previous [comment](https://github.com/Expensify/App/issues/38307#issuecomment-2029333666) may have confused you.
My current proposal will fix both the original GH issue and 3 bugs described in this https://github.com/Expensify/App/issues/38307#issuecomment-2028912880 ыo updates to the [branch](https://github.com/shahinyan11/Expensify/tree/issue/38307) are not necessary to fix these. The updates in branch related with the error I described in my7 proposal
> But there is one problem too. If we mute the video before opening full screen mode, then pressing on the volume icon does not cause any effect.

**Comment by jayeshmangwani** [comment]
@shahinyan11 Does this [proposal](https://github.com/Expensify/App/issues/38307#issuecomment-1998334705) will fix the mentioned [bugs](https://github.com/Expensify/App/issues/38307#issuecomment-2028912880)?

**Comment by jayeshmangwani** [comment]
@shahinyan11 Thanks for bearing with me, and I am sorry for the back and forth; your proposal will solve the issue in hand where the Mute icon is not in sync, and in the PR, we can determine and fix anything the internal engineer will decide for the volume value sync between the fullscreen and mini player.

**Comment by jayeshmangwani** [comment]
@shahinyan11 's [proposal](https://github.com/Expensify/App/issues/38307#issuecomment-1998334705) will solve the issue at hand where the Mute icon is not in sync from fullscreen to mini player; in the PR, if we want to fix the volume value sync between the fullscreen and mini player, then we can handle it in PR.

🎀 👀 🎀 C+ reviewed

**Comment by thienlnam** [comment]
Agree on fixing all the inconsistencies for the video mini / full screen player here

**Comment by shahinyan11** [comment]
PR will be created until tomorrow evening

**Comment by shahinyan11** [comment]
@lschurr I think automation doesn't work here. The period of regression should have already begun

**Comment by lschurr** [comment]
You're right @shahinyan11 - Thanks! 

PR was deployed to prod on April 22nd, so the pay date will be April 29th.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @shahinyan11 $500 (to be paid in Upwork on 4/29)
- Contributor+: @jayeshmangwani $500 (to be paid in Upwork on 4/29)

**Comment by lschurr** [comment]
This is complete!
