### ISSUE TITLE
Web – Login – Console error shows up when login and logout in Incognito tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38300]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4423031
**Email or phone of affected tester (no customers):** applausetester+jpcategory@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open an Incognito tab
2. Go to https://staging.new.expensify.com/
3. Log in
4. Press logout

## Expected Result:
User able login and logout without Console error

## Actual Result:
Console error shows up when login and logout in Incognito tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/60989d09-263a-4f59-bb86-cee3e820b4ae

[log.txt](https://github.com/Expensify/App/files/14602139/log.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment]
Reviewing this one now.

**Comment by strepanier03** [comment]
<img width="403" alt="image" src="https://github.com/Expensify/App/assets/10925636/c7fa9c16-2648-4644-9f8b-0165c8fff400">

**Comment by strepanier03** [comment]
https://expensify.slack.com/archives/C01SKUP7QR0/p1710892318882329
