### ISSUE TITLE
[Wave Collect] [Tax] Update the Create, Delete and Rename API for tax codes

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38315]
The Newdot taxes API needs couple of changes as found by @kosmydel working on the UI parts:
- when using `SetPolicyTaxesEnabled` we can have multiple taxes enabled at the same time so the param needs to be JSONARRAY not a single JSONOBJECT
- the `DeletePolicyTaxes` command expects a list of names of taxes and not a list of taxCodes as the param name suggests which is confusing
- When renaming a tax using `RenamePolicyTax`, there is no validation for already existing tax names

Lets fix these items
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d991bde7ae0309e</li>
        <li>Upwork Job ID: 1768285353722294272</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
@mountiny is the only PR here the web PR, meaning there's no contributor's involved?

**Comment by mountiny** [comment]
correct this is done, can close, thank you
