### ISSUE TITLE
[HOLD for payment 2024-04-02] Use deleted timestamp for deleting report comments

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#38310]
## Problem

We created a new pattern for marking any report action as deleted by setting a `deleted` timestamp in the action's `message` in [this issue](https://github.com/Expensify/Expensify/issues/367794). We used the pattern for scenarios where we delete report preview actions, but deleting report comments does not use this pattern yet.

## Why is this important?

We should continue unifying deleting report actions around this pattern

## Solution

Update the `DeleteComment` API to use the `deleted` timestamp
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c0a7916533d0bbf</li>
        <li>Upwork Job ID: 1768276264180318208</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by arosiclair** [comment]
To do this we'll probably need to write a new `MarkActionDeleted` Auth command and use it in our `DeleteComment` API. That will affect both OldDot and NewDot so I'll need to push changes to handle `message.deleted` in Web-E first.

**Comment by arosiclair** [comment]
On second thought, I can just update the `UpdateReportComment` command set `deleted` instead. That will preserve some other logic and permission checks for we have edits.

**Comment by arosiclair** [comment]
Web-E PR is merged and on it's way to staging

**Comment by stephanieelliott** [comment]
PRs deployed to Prod and Auth on the 26th, setting 7 day hold

**Comment by cubuspl42** [comment]
Are there any payments due? We ended up with no frontend PRs, so I had nothing to review.

**Comment by arosiclair** [comment]
> Are there any payments due? We ended up with no frontend PRs, so I had nothing to review.

Yeah this is right. We only pushed backend PRs to address this. This also isn't a regression so no need for new regression tests and etc. Closing this out as done
