### ISSUE TITLE
Android - Attachment – Unable to zoom image in preview when upload it after password protected PDF

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38319]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app.
2. Log in
3. On a conversation, click on the + button in the compose box
4. Click on add attachment
5. Upload a password protected PDF (Attachment 1)
6. Enter a password (Test12345), confirm and send
7. Upload an image (Attachment 2)
8. Verify a preview of the image is displayed before uploading to the conversation
9. Try to zoom the image in a preview

## Expected Result:
Able to zoom image in preview

## Actual Result:
Unable to zoom image in preview when upload it after password protected PDF

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e3c637e8-5909-4212-bde3-3f02fb402224

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@twisterdotcom I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by twisterdotcom** [comment]
I cannot recreate this and it is also very niche: https://drive.google.com/file/d/13hO6rM3yKW7GSq2Qc7YwLAmgAgJI7nr2/view?usp=sharing
