### ISSUE TITLE
[HOLD for payment 2024-03-25] Invite -  Selected contacts with names disappeared from the invite listing page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38324]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+omq1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34993
## Action Performed:
1. Open app
2. Open any DM with other user
3. Write a message
4. Tap and hold on the message in chat
5. Select "Reply in Thread"
6. Write any message
7. Tap on Header > Members > Invite
8. Perform a search using a portion of the email contact, for example, "omd10"
  (applausetester+101321@applause.expensifail.com applausetester+omd10@applause.expensifail.com )
9. Scroll down and select a contact with a first and last name set e.g. "Pes Patron"
10. Select a contact where the first and last name are not set in the profile
11. Scroll up

## Expected Result:
Selected contacts should be displayed on top of the listing page

## Actual Result:
Contacts with first and last names set in the profile disappeared from the listing page when users selected them

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/915711a8-2841-4793-9305-1015f337f06e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rlinoz** [comment]
This is already a bug in prod when inviting someone to a room, so removing the blocker label.

**Comment by trjExpensify** [comment]
👋 checklist time here please, @ishpaul777.

**Comment by trjExpensify** [comment]
Thanks! Applause caught this with those regression steps, so I don't think we need to add a new one. 

Payment summary as follows: 

- $500 to @ishpaul777 for the C+ review. Offer [sent](https://www.upwork.com/nx/wm/offer/101719774)!

**Comment by trjExpensify** [comment]
Paid!
