### ISSUE TITLE
[HOLD for payment 2024-04-02] [$500] IOS- Extra margin below offline indicator in Profile page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38328]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify.
2. Go offline.
3. Go to Profile from the bottom navigation.

## Expected Result:
There is no extra margin below offline indicator.

## Actual Result:
There is extra margin below offline indicator.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/7d518f8e-eac4-4a7a-ac14-8381ab298a58)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199282bcbfa5f2d37</li>
        <li>Upwork Job ID: 1768345821971177472</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1 of 6 tasks
IOS- Extra margin below offline indicator in Profile page
### What is the root cause of that problem?
we not pass style `styles.pb0` in <ScreenWrapper> like other pages
### What changes do you think we should make in order to solve the problem?
pass style `styles.pb0` in <ScreenWrapper> in InitialSettingsPage

### What alternative solutions did you explore? (Optional)

**Comment by yuwenmemon** [comment]
@ahmedGaber93 does that explain why we're only seeing it on iOS though?

**Comment by ahmedGaber93** [comment]
@yuwenmemon 
> does that explain why we're only seeing it on iOS though?

i update the root cause with the explanation.

**Comment by godofoutcasts94** [comment]
I tried @ahmedGaber93 proposal. But is this what we need ? Becoz I think this will make `offline message` to be very small.
<img width="383" alt="Screenshot 2024-03-14 at 11 25 18 PM" src="https://github.com/Expensify/App/assets/158435970/aa136bf0-76c5-42a4-8973-07e0ed51feb1">

**Comment by ahmedGaber93** [comment]
also `offline message` padding bottom and padding top is consistent now.

**Comment by ahmedGaber93** [comment]
@yuwenmemon this all screenshots for all platforms.


### Screenshots/Videos
<details>
<summary>Android: Native</summary>

![Screenshot 2024-03-14 at 8 36 40 PM](https://github.com/Expensify/App/assets/41129870/3484ff3e-7c74-4836-852d-32528f01485a)



</details>

<details>
<summary>Android: mWeb Chrome</summary>

![Screenshot 2024-03-14 at 8 36 18 PM](https://github.com/Expensify/App/assets/41129870/e7de359d-b6d3-41cc-97ea-71a14480d7b5)


</details>

<details>
<summary>iOS: Native</summary>

![Screenshot 2024-03-14 at 8 25 13 PM](https://github.com/Expensify/App/assets/41129870/3ff742aa-b04a-4ef2-b678-6234a2e95642)


</details>

<details>
<summary>iOS: mWeb Safari</summary>

![Screenshot 2024-03-14 at 8 35 24 PM](https://github.com/Expensify/App/assets/41129870/841acbb6-6446-4a6f-a526-faeaf330adce)




</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![Screenshot 2024-03-14 at 8 08 39 PM](https://github.com/Expensify/App/assets/41129870/b7b31f6f-3dd1-478f-a631-87f07a35d832)


</details>

<details>
<summary>MacOS: Desktop</summary>

![Screenshot 2024-03-14 at 8 30 41 PM](https://github.com/Expensify/App/assets/41129870/01994071-34c8-4324-961b-d73333873cfb)


</details>

**Comment by ahmedGaber93** [comment]
@GandalfGwaihir we need this lines for other screen to force safeareapaddingbottom when offline




https://github.com/Expensify/App/assets/41129870/ea760853-670b-4fd6-990c-0847df0a975e

**Comment by alexpensify** [comment]
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @ahmedGaber93 $500 
-  Contributor+ that helped on the issue and/or PR - @ishpaul777 $500 

Upwork Job: https://www.upwork.com/jobs/~0199282bcbfa5f2d37

Extra Notes regarding payment: @ahmedGaber93 and @ishpaul777 can you please accept the offers, and I can complete the required process? Thanks!

**Comment by ahmedGaber93** [comment]
![Screenshot 2024-03-26 at 6 07 38 AM](https://github.com/Expensify/App/assets/41129870/634aec93-d899-42dc-b9d0-11423c9e7a5b)


When I am clicking "Accept offer", it failed with this error.
Other offers work fine with me, and I already accept another offer today without this error.

@alexpensify any idea about this error?

**Comment by alexpensify** [comment]
@ahmedGaber93 - the issue is on the Upwork side, but thank you for sharing. Sorry for the extra step, but I sent over a new offer based on the feedback in the response error. 

@ishpaul777 and @ahmedGaber93 - Please try to accept again and I can complete the payment process in Upwork.

**Comment by ahmedGaber93** [comment]
Offer accepted, thanks @alexpensify

**Comment by alexpensify** [comment]
I've paid @ahmedGaber93 via Upwork. I'll need to keep this one open because I'm waiting for @ishpaul777 to accept the new proposal.

**Comment by alexpensify** [comment]
@ishpaul777 - yes, can you please share a little more context?

**Comment by alexpensify** [comment]
Thanks, I'll set a reminder to check on April 2. Please keep me posted if I need to change this payment date.

**Comment by alexpensify** [comment]
@ishpaul777 - can you please share an update if your Upwork profile is ready for this payment? If yes, I'll work on the required steps tomorrow morning. Thanks!

**Comment by alexpensify** [comment]
All set here, I've paid everyone here via Upwork. Summary: 

https://github.com/Expensify/App/issues/38328#issuecomment-2019000003
