### ISSUE TITLE
mWeb - Room - Opening public URL shows description twice & concierge message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38326]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app (expensifail a/c)
2. Create a WS room with description >45yy
3. Tap header and change it to public visibility
4. Copy share code url
5. Paste the url in mweb (expensifail a/c) and send the message
6. Open the URL

## Expected Result:
Description message need not be shown twice. Concierge message behavior must be same in staging and production.

## Actual Result:
Opening the URL shows description twice and expensify message. 2 only visible to you message is shown.
Description is shown as a message once and as only visible to message once. This description part is same in staging and production.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/28cd0381-9074-45ff-a078-4cabe5610dff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@isabelastisser I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by isabelastisser** [comment]
I'm unsure if this is a bug. I will get a buddy check in Slack.

**Comment by isabelastisser** [comment]
https://expensify.slack.com/archives/C01SKUP7QR0/p1711654592064679 waiting

**Comment by isabelastisser** [comment]
This is the correct behavior, we whisper the description to anyone who newly joins a room. Closing!
