### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Storybook - "Couldn't find a navigation object" error when trying to select a year

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38331]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37820
## Action Performed:
1. Navigate to https://staging.new.expensify.com/docs/index.html
2. Click on the "Form" component
3. Click on the year selector
4. Navigate to https://staging.new.expensify.com/docs/index.html
5. Click on the "Form" component
6. Click on the state selector

## Expected Result:
I should be able to select a year and state

## Actual Result:
"Couldn't find a navigation object. Is your component inside NavigationContainer?" error when trying to select a year or state.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2a260382-aa99-4803-a12e-fa61113902a7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a13cfaecad01b349</li>
        <li>Upwork Job ID: 1769863435571646464</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by tychoprice** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remedy the "Couldn't find a navigation object" error when trying to select a year
### What is the root cause of that problem?
Components like StatePicker and DatePicker require a navigation context; however, in Storybook, this navigation context is not naturally present.
### What changes do you think we should make in order to solve the problem?
Provide navigation context, thus preventing the error when these components try to access navigation-related features.

**Comment by anmurali** [comment]
@dukenv0307 and @tienifr have been paid.
