### ISSUE TITLE
Web - Main Account Email Missing in "Share Somewhere" Section During Task Assignment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.51-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a new Expensify account.
2. Go to FAB > Assign Task.
3. Add a title.
4. Navigate to the "Share Somewhere" section.

## Expected Result:
The main account email should be automatically present in the "Share Somewhere" section by default.

## Actual Result:
The main account email should be automatically present in the "Share Somewhere" section by default.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/380f0922-b572-4653-892a-c033d63e8e3f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by jliexpensify** [comment]
Same, cannot repro on Staging v1.4.52-5.
