### ISSUE TITLE
Private notes- Copy options in context menu when long tapping on code block copy undefined URL

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38341]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Tap on the header > Private notes
4. Enter text in code block and save it
5. Tap Private notes
6. In the preview, long tap on the code block
7. Select Copy link or Copy to clipboard
8. Paste it in the composer

## Expected Result:
In Step 6, there should be no context menu if the context menu options are not working

## Actual Result:
In Step 6, context menu with Mark as unread, Copy link and Copy to clipboard options.
Mark as unread serves no purpose, while the copy options copy undefined URL (Step 7)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4d300833-4e6c-4cc9-ac0a-0fb7541be533

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment]
I'm not able to get the comment action menu showing with a long tap and hold

**Comment by MitchExpensify** [comment]
I am still unable to reproduce on a physical iOS device
