### ISSUE TITLE
Android - Bank - Inconsistency in showing "https" in company website section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38353]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4426492
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Login with gmail
3. Tap on profile --- Workspaces --- Workspace
4. Tap bank ---Update to USD
5. Tap continue with plaid
6. Complete the chase Bank flow with plaid savings ending 1111
7. Enter all required information
8. In Business information page, in company website section, delete the text [https://](https://github.com/Expensify/App/issues/new?assignees=&labels=Bug%2C+Daily&projects=&template=Standard.md)
9. Tap app back button
10. Tap next
11. Note [https://](https://github.com/Expensify/App/issues/new?assignees=&labels=Bug%2C+Daily&projects=&template=Standard.md)
is not shown
12. Tap app back button
13. Tap next
14. On revisiting page, note [https://](https://github.com/Expensify/App/issues/new?assignees=&labels=Bug%2C+Daily&projects=&template=Standard.md)
is shown

## Expected Result:
After clearing https://,
tapping app back button and visiting the company website page for first time [https://](https://github.com/Expensify/App/issues/new?assignees=&labels=Bug%2C+Daily&projects=&template=Standard.md)
must be shown.

## Actual Result:
After clearing https://,
tapping app back button and visiting the company website page for first time [https://](https://github.com/Expensify/App/issues/new?assignees=&labels=Bug%2C+Daily&projects=&template=Standard.md)
is not shown. Only on revisiting, the [https://](https://github.com/Expensify/App/issues/new?assignees=&labels=Bug%2C+Daily&projects=&template=Standard.md)
is shown in company website page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fe9b78c1-fbc9-436e-a549-e8d43b1a062f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@dylanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by dylanexpensify** [comment]
huh this feels like if you're choosing to delete the string, then when you come back having it still deleted sounds right, no? Confirming

**Comment by dylanexpensify** [comment]
asked internally
