### ISSUE TITLE
 Profile - Switch to Expensify Classic is under Account instead of General

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38354]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37421
## Action Performed:
1. NewDot: Login to Account (Web/mWeb/Desktop)
2. Click on 'Profile' at the bottom (user's avatar)

## Expected Result:
'Switch to Expensify Classic' option is under General section

## Actual Result:
'Switch to Expensify Classic' option is under Account section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6414075_1710446632210!Screen_Shot_2024-03-14_at_9 31 29_PM](https://github.com/Expensify/App/assets/78819774/39e92504-07f7-46cf-b0f6-f51866c12a5a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by trjExpensify** [comment]
This is intentional now as part of HybridApp plans, so it's easier for people to find how to switch back. Going to close this out. CC: @AndrewGable @JmillsExpensify for vis
