### ISSUE TITLE
Growl notification is not displayed when clicking Wallet

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38350]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #32942
**Version Number:** 1.4.52-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Wallet
3. Go into the wallet statement page and press a button to download a wallet statement

## Expected Result:
After pressing it a growl notification should appear in the top right corner of the screen

## Actual Result:
The notification is not displayed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/c20ed294-a0f9-4288-baae-06f6374d995b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Clarifying the behaviour with @kavimuru [here](https://expensify.slack.com/archives/C9YU7BX5M/p1710479283216489).
