### ISSUE TITLE
The API command "AddComment" doesn't include "isOldDotConciergeChat"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #37754
**Version Number:** 1.4.52-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. Create a new Gmail account in OD
2. Click on the Concierge chat button in OD
3. Resresh Concierge chat
4. Duplicate Concierge chat by opening it in a new tab
5. Send "MODERATION_TEST" to Concierge
6. Open Chrome console - Network
7. Search for "AddComment"
8. Open the API command
9. Look for "isOldDotConciergeChat" in the Payload tab

## Expected Result:
The API command "AddComment" includes "isOldDotConciergeChat" with a "true" value.

## Actual Result:
The API command "AddComment" doesn't include "isOldDotConciergeChat".

## Workaround:
unknown 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/5a6696c3-e849-4082-b5b2-f03dcc6abac6

https://github.com/Expensify/App/assets/43996225/76eaaf84-df77-40ff-b3bb-245a2d1df9cf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
@trjExpensify I think this belongs under Wave 1

**Comment by trjExpensify** [comment]
#wave-collect you mean? Yup!

Looks like this was created as an issue when executing [this PR](https://github.com/Expensify/App/pull/37754) from @rezkiy37. @cristipaval, @abdulrahuman5196 and @MitchExpensify might have some additional context as a former #wave9 project!

**Comment by cristipaval** [comment]
In step 4, by copy-pasting that URL in a new tab, a new App session is opened, and because it is not open with a redirect from the OldDot (like the initial tab), we don't consider it bound to OldDot. I'm not sure we want to fix this, given that this doesn't sound like common user behavior. Thoughts @sonialiap @trjExpensify ?

**Comment by trjExpensify** [comment]
I don't have a strong opinion. @MitchExpensify might, as he was spearheading this. Why was it included in the [PR testing steps](https://github.com/Expensify/App/pull/37754#issue-2169393787) explicitly if it's not required for the implementation?

**Comment by MitchExpensify** [comment]
I am not seeing the first steps being taken here in the videos:

1. Create a new Gmail account in OD
2. Click on the Concierge chat button in OD

I raise this because any new account joining OD would be redirected to ND and as such I'm not sure why we'd even expect this:

> "isOldDotConciergeChat" with a "true" value.

**Comment by adelekennedy** [comment]
aha! Then this feels like a non-bug to me?

**Comment by MitchExpensify** [comment]
I _think_ so. The user is writing from NewDot so why would we expect the isOldDotConciergeChat" to have a "true" value? 🤷

**Comment by adelekennedy** [comment]
I thought there might be something going on with backwards compatibility (ya know - _beyond my understanding_ ) closing this!
