### ISSUE TITLE
[Awaiting Payment 30th April] [Wave Collect] [More Features] [$500] Feature enabled from `more features` are not highlighted when user taken back to the LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710462111227289

## Action Performed:
1. open app 
2. go to any collect workspace
3. Tap `more features`
4. Enable any option
5. Look at the LHN
## Expected Result:
the row of the enabled option is highlighted when we take the user back to the LHN.
## Actual Result:
the enabled option is not highlighted when we take the user back to the LHN.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/48205bec-bea9-4735-b5bd-3a3b8275feb9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c04b62c76b203710</li>
        <li>Upwork Job ID: 1768687467296501760</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
Should use similar solution to what we have here https://github.com/Expensify/App/pull/38036

**Comment by mountiny** [comment]
Rushat will handle this

**Comment by trjExpensify** [comment]
@luacmartins @mountiny should we do categories and tags here as well?

**Comment by mountiny** [comment]
We could

@rushatgabhane that means we will add the same highlight as with new Member from https://github.com/Expensify/App/pull/38036 for new category and tag

**Comment by rushatgabhane** [comment]
Before we implement this.

Web: Enabling a feature navigates you to the feature.

Mobile: Enabling a feature navigates you to LHN.


Our philosophy is to have same UX across platforms. So shouldn't we make the UX consistent i.e. navigate to the enabled feature directly?


https://github.com/Expensify/App/assets/29673073/3faad870-5279-444d-bca2-50ec1349f146

**Comment by mountiny** [comment]
@rushatgabhane this is by design for this feature, its expected.

We want to show the user where they can find the settings 

But we can change this in future if we find that this is not the best

**Comment by mountiny** [comment]
@rushatgabhane How is this going, do you think you can have a PR up today?

**Comment by rushatgabhane** [comment]
@mountiny yes

**Comment by rushatgabhane** [comment]
@mountiny im facing a problem.

In WorkspaceInitialPage, I'm finding the new items by comparing translation key of previous and current `protectedCollectPolicyMenuItems`. This is the `newItem` list.

To focus items, I added an optional param in `WorkspaceMenuItem`.
This is set to `true` if the item is in `newItem` list.

But I'm having difficulty in **un-focusing** it. This is because the page renders a list of `MenuItem`.
To un-focus, we'd have to calculate the list again with different value for `focused`.



https://github.com/Expensify/App/blob/c9f88619cceb919ed748f97ff57d2168bb871e8d/src/pages/workspace/WorkspaceInitialPage.tsx#L280-L281

**Comment by rushatgabhane** [comment]
I'm not very confident in my approach. I'm going to ask someone else in the room for help because this issue is urgent

**Comment by allroundexperts** [comment]
PR: https://github.com/Expensify/App/pull/38546

**Comment by mountiny** [comment]
@allroundexperts have you got all you need in that PR, seems like design team has weighed in

**Comment by allroundexperts** [comment]
> @allroundexperts have you got all you need in that PR, seems like design team has weighed in

Yes, I'm on it. I'm not sure how the transitions would work, but rest of the feedback should be easy to put in.

**Comment by luacmartins** [comment]
I think the border radius disappeared again:
![Screenshot 2024-04-04 at 1 17 53 PM](https://github.com/Expensify/App/assets/22219519/d1a92ab5-1932-46ea-b6ae-c3eb0bd79a94)

**Comment by allroundexperts** [comment]
Oh, that's weird. I'm checking this.

**Comment by luacmartins** [comment]
I think we need to add the styles [here](https://github.com/Expensify/App/blob/fe8adca615126f55144854f92f1be04a6acbe77d/src/components/MenuItem.tsx#L434-L446)

Another issue, it seems like the height got shorter and now the highlights overlap

Uploading Screen Recording 2024-04-04 at 2.34.17 PM.mov…

**Comment by allroundexperts** [comment]
The amount of overlap looks the same to me.

<img width="1425" alt="Screenshot 2024-04-05 at 1 46 13 AM" src="https://github.com/Expensify/App/assets/30054992/ac5f0023-1600-4457-8786-10b635170c50">

**Comment by allroundexperts** [comment]
Created draft PR https://github.com/Expensify/App/pull/39657. Filling in the checklist now. Feel free to review to make things faster.

**Comment by allroundexperts** [comment]
Ready for review.

**Comment by mountiny** [comment]
Not sure if related but do you see this behaviour when toggling the distance rate feature repeatedly?
https://github.com/Expensify/App/assets/36083550/bcf33aec-37fb-4edb-a766-a24e33b5eb62

**Comment by allroundexperts** [comment]
Doesn't look related to me.

**Comment by trjExpensify** [comment]
What's with all the automation failures as of late man. I think this is ready for payment. @allroundexperts if you want to confirm, and then I'll jump on that.

**Comment by rojiphil** [comment]
> I think this is ready for payment.

@trjExpensify Also please note. I was involved in the review of this issue ([Reference](https://github.com/Expensify/App/pull/38546#issuecomment-2034417608))

**Comment by allroundexperts** [comment]
Yes. This is ready for payment. 

Also, since the issue later on had a scope change and involved adding animations as well, I would request the bounty to be $500. @mountiny can you please weigh in? 

Thanks!

**Comment by trjExpensify** [comment]
Yeah, this one ended up being a tricky one for simplified collect. I think we can keep it at $500

Payment summary as follows:

- $500 to @allroundexperts for the fix
- $500 to @rojiphil for the C+ review

**Comment by trjExpensify** [comment]
- @rojiphil paid
- @allroundexperts - go ahead and submit.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
