### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] [Wave Collect] As we switch between the features of Collect workspace the read api commands are not triggered everytime

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38378]
### Problem

As you can see in the video here https://github.com/Expensify/App/pull/38135#pullrequestreview-1934238734, in Collect workspace (needs to be created from OldDot) settings in NewDot, user has multiple features admin can open in the LHP.

When the feature page is open a read API command should get triggered to make sure all the data are up-to-date. 

But as you can see it does not happen reliably. @fabioh8010 has investigated and left some information here https://github.com/Expensify/App/pull/38135#issuecomment-1994931332

### Solution

Fix this for all the workspace pages so opening the page will always call the appropriate API command.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe46178cda4b28aa</li>
        <li>Upwork Job ID: 1768569366516178944</li>
        <li>Last Price Increase: 2024-03-15</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

As we switch between the features of Collect workspace the read api commands are not triggered everytime

### What is the root cause of that problem?

We only fetch data on mount

### What changes do you think we should make in order to solve the problem?

We can refetch the data when it is refocused. We can combine useFocusEffect with useCallback to optimize it.

Add this to each menu page.
```
    useFocusEffect(
        React.useCallback(() => {
            fetchData();
        }, [])
    );

```

This can be applied to all menu features

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
Waiting for C+ review @eVoloshchak

**Comment by eVoloshchak** [comment]
Thank you all for the proposals!

Ultimately there are two ways to resolve the issue 

1. Using `useIsFocused` to re-fetch data every time the screen is focused (originally proposed by @fabioh8010 in https://github.com/Expensify/App/pull/38135#issuecomment-1994931332, proposed here by @tienifr and @wildan-m(this is ultimately the same approach that was proposed by @fabioh8010 and @tienifr, but extended))

2. Using `shouldPopToTop` to un-mount the page then we're navigating from it to ensure the data is refreshed when we come back to the page (proposed by @ikevin127 in https://github.com/Expensify/App/issues/38378#issuecomment-2000433882)

Both approaches do resolve the issue, however I'm a bit wary of using `Navigation.goBack` for a button that isn't, in fact, a back button. But the main thing is, subscribing to `isFocused` is less expensive from the performance standpoint than re-rendering the whole page. 
Based on that, I think we should proceed with @tienifr's [proposal](https://github.com/Expensify/App/issues/38378#issuecomment-1999292275) 

🎀👀🎀 C+ reviewed!

**Comment by mountiny** [comment]
Thanks @eVoloshchak I agree with your conclussion

**Comment by wildan-m** [comment]
@eVoloshchak, the solution to this issue is straightforward, and I believe a little optimization could make a difference. In this case, useFocusEffect not only provides an efficient and optimized approach to managing side effects in React but also enhances code readability. Would you please reconsider?

**Comment by wildan-m** [comment]
If the decision is final, that's fine.

> the core approach here is "call the API when the page is focused"

@tienifr By the way, that doesn't belong to you either, it's already identified in the original post link. https://github.com/Expensify/App/pull/38135#issuecomment-1994931332.

**Comment by lschurr** [comment]
@eVoloshchak - Do we need a regression test for this one?

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Open the network console (web/Desktop) or Show Element Inspector -> Network (native iOS/Android)
2. Open a collect workspace settings page
3. Try to switch between Taxes and More features pages
4. Verify that every time you switch to a new page, the corresponding Open API is called (OpenPolicyTaxesPage and OpenPolicyMoreFeaturesPage respectively in this case)
5. Verify the above with other all other pages

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
