### ISSUE TITLE
[HOLD for payment 2024-05-02] Avoid anonymous functions

### ISSUE THREAD

**Issue by gedu** [Expensify/App#38394]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Update this part of the [Style.md](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#functions) contribution guide to only accept named functions. 
This will improve our performance debugging and we can track better which part of a big function gives troubles or take more time, understand better the flow of the function, etc

Before
<img width="670" alt="functions_hidden" src="https://github.com/Expensify/App/assets/1676818/88ba760a-6b0f-4441-aee7-14e85d2d75b7"> 

After
<img width="600" alt="functions_exposed" src="https://github.com/Expensify/App/assets/1676818/5c5ab5cb-d0ed-47bf-912c-fee3fbda0dd8">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gedu** [comment]
I am from Callstack - expert contributor group, I wanna work on this issue

**Comment by mountiny** [comment]
@gedu What is the latest on this one?

**Comment by gedu** [comment]
@mountiny There is a PR for this: https://github.com/Expensify/eslint-config-expensify/pull/87

**Comment by mountiny** [comment]
reviewed

**Comment by mountiny** [comment]
@gedu do you want to follow up with App PR to enable this lint rule?

Additionally we need to update the style.md and also I would propose drafting some message for the open source room. what do you think?

**Comment by gedu** [comment]
@mountiny  Hey hey, sounds great! 

I will start working on it

**Comment by gedu** [comment]
it is throwing a bunch of warnings and ESLint doesn't allow to add the rule only for new or modified files, so exploring new alternatives

**Comment by gedu** [comment]
@mountiny Created a PR to Remove the rule from eslint-config-expensify

**Comment by mountiny** [comment]
We have discussed internally [here](https://expensify.slack.com/archives/C03TQ48KC/p1713205938442829), whether to enable this lint rule everywhere or not. We have decided to avoid such general rule and instead focus on more direct approach where we will use the named functions in callbacks etc based on reviewers intuition.

We are going to update the checklist for author and reviewer of a PR to include a line ensuring they have named any callbacks that could be potentially slower from performance perspective linking to the section in style guidelines where we will describe how to decide about this.

@gedu could you please propose such Style.md changes where we can give guidelines to contributors to know when to apply the named function and when its not that necessary? I assume we need to focus on methods that can run slower or can be repeated many times

**Comment by gedu** [comment]
@mountiny PR for this Style.md update: https://github.com/Expensify/App/pull/39942
