### ISSUE TITLE
[HOLD for payment 2024-03-26] [HOLD for payment 2024-03-25] Category - Incorrect app behavior when editing category with / symbol

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38401]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause internal team

## Action Performed:
Precondition:
- User is an admin of Collect workspace.
- The Collect workspace has the following categories:
a/
a/: invalid

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > any workspace.
3. Go to Categories.
4, Click on the category a/.
5. Click Category name.
6. Note that the symbol / is missing.
7. Update the category name and save it.
8. Note that it creates a new category with an error instead of updating the previous category.
9. Create on the category a/: invalid > Category name.
10. Note that it shows not here page.

## Expected Result:
User should be able to edit category with / in the name.

## Actual Result:
For a/ category, when editing the name, the field is missing / symbol. When updating the name, it creates a new category with error instead of updating a new one.
For a/: invalid category, it shows not here page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/c73f0d32-6650-4b9f-909f-57090157be0c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by c3024** [comment]
I think this got to do with this.

https://github.com/Expensify/App/blob/15124d7f01f3c81878a4df2207a0fb704f2b34c3/src/ROUTES.ts#L574

I think we should use `encodeURIComponent` instead of `encodeURI`

cc: @ArekChr @luacmartins

**Comment by luacmartins** [comment]
Yes, I got this one. It's the same solution we have for tags and other pages.

**Comment by luacmartins** [comment]
Fixed in staging. Will keep this issue open to pay C+ for the PR review.

**Comment by luacmartins** [comment]
This is a new feature still in development. I don't think the BZ checklist applies here.

**Comment by Christinadobrzyn** [comment]
Who are the C+ reviewers here that need to be paid? 

@sobitneupane and @c3024 was it both of you? cc @luacmartins?

**Comment by sobitneupane** [comment]
@Christinadobrzyn I didn't review the PR.

**Comment by luacmartins** [comment]
@Christinadobrzyn this was handled internally. We can close this.
