### ISSUE TITLE
transaction data creating when not able to access the report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38406]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tedharris
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710503355607069

## Action Performed:

1. Create a workspace in oldDot.
2. Chat on a report with transactions on that workspace in oldDot
3. Have the other user reject the report on oldDot
4. Delete the workspace

## Expected Result:
The use can still access the report in ND  and openapp works

## Actual Result:
That user can't access 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3edbc764-ef2e-47ca-914a-3d153520bb96

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158cc656968a82b8f</li>
        <li>Upwork Job ID: 1768678427148525568</li>
        <li>Last Price Increase: 2024-03-15</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
Been DM-ing Vit about this one, and I can't repro this - after deleting the Workspace, I see `Unavailable Workspace` at the top of the Report, and when I refresh, I see this:

![image](https://github.com/Expensify/App/assets/30815269/ede48966-9e93-45e5-95e3-93f9de3b8533)

I can search for the #Admin and #Announce rooms (but they are archived):

![image](https://github.com/Expensify/App/assets/30815269/42474b59-6fe0-4295-b7df-3bf948c9181b)

When I log back out and back in, I don't see anything with OpenApp and I now can't search for the rooms:

![image](https://github.com/Expensify/App/assets/30815269/4ba02a25-29cf-4da8-84ab-cc4645cc168f)

![image](https://github.com/Expensify/App/assets/30815269/e28e185d-7457-432c-b2dd-3911ce6136b2)

**Comment by jliexpensify** [comment]
Some discussion [here](https://expensify.slack.com/archives/C049HHMV9SM/p1710755898303709?thread_ts=1710503355.607069&cid=C049HHMV9SM) with a theory this could resolve itself/be fixed shortly. Vit has advised making this `Monthly` and re-testing at a later date.

**Comment by jliexpensify** [comment]
@m-natarajan adding the retest label to see if you can repro (I can't). If not, will close this.

**Comment by mvtglobally** [comment]
We are facing issue with the steps. 
Can you help with these are accurate?

- Created Collect WS, create a report as user A and send it to user B. User B rejected the report to user A.
- User A deletes a WS.
- User B logged to ND but couldn't find a report and deleted WS.

If these steps are incorrect, let us know 

https://github.com/Expensify/App/assets/43995119/d22a320f-efd8-446a-8fb7-0dd54a518341

**Comment by jliexpensify** [comment]
Hi @mvtglobally - this is an odd issue that _might_ only be affecting one or two users under the expensify.com domain.

I also realised that the Actual/Expected Results should be flipped in the GH, so it should be:

>Expected Result:
>That user can't access the reports

>Actual Result:
>The user can still access the report in ND and openapp works

**Comment by jliexpensify** [comment]
@mvtglobally I notice that your Workspace (that you've submitted the expense under) in the video is (not shared) - this usually indicates that it's a personal Workspace.

Can you confirm this? Have you tried submitting. under a Collect or Control one?

**Comment by jliexpensify** [comment]
Going to close this out, it's been a month and we haven't been able to repro.
