### ISSUE TITLE
[$500] [Categories] Android - Category - Keyboard does not pull up after reopening Add category page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38402]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an admin of Collect workspace
- The Collect workspace has categories
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > any workspace
3. Go to Categories
4. Click Add category
5. Click app back button
6. Click Add category again

## Expected Result:
Keyboard should pull up

## Actual Result:
Keyboard does not pull up after reopening Add category page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/650837db-ed1c-45bf-9b48-78eba24223ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bfe3524070ac64d</li>
        <li>Upwork Job ID: 1769781773907210240</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@youssef-lr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect release 1
CC @trjExpensify

**Comment by lanitochka17** [comment]
Production:

https://github.com/Expensify/App/assets/78819774/baba082e-ddda-40ff-81b7-25f95cc89a46

**Comment by situchan** [comment]
Not deploy blocker. Can be handled as folllow-up of https://github.com/Expensify/App/pull/37969.
Maybe @ArekChr can tackle this in any of his next PRs.

**Comment by trjExpensify** [comment]
Yeah, I agree this isn't a deploy blocker. CC: @luacmartins

**Comment by luacmartins** [comment]
Agreed. Removing blocker label, adding it to the project so we can tackle it as polish. cc @ArekChr

**Comment by luacmartins** [comment]
@ArekChr let's address this one now that we're done with the main implementation issues

**Comment by appsrahulgautam** [comment]
Hello. Saw this post on Upwork. Possible causes -
1. Focus issue.
2. Page still in memory and Focus not requested by Add category page.
3. Some weak spots on onRestart, onPause, onStart, onResume.
4. Some view other then EditText is catching focus. 
Testing around these points can fix issue.

**Comment by appsrahulgautam** [comment]
Contributor details
Your Expensify account email: appsrahulgautam@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0122a868aacd64962b

**Comment by ArekChr** [comment]
This issue has been fixed in this [PR](https://github.com/Expensify/App/pull/38379)

**Comment by luacmartins** [comment]
Cool, I think we're good to close this one since we'll process payment for the PR review on https://github.com/Expensify/App/issues/38316
