### ISSUE TITLE
Web - No error is displayed under the tag after executing the command in the consol

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38332
## Action Performed:
1. Create a Control workspace in OD
2. Enter the following in the console, while the workspace is open:
var p = Policy.getActive();
p.policy.areTagsEnabled = true;
p.save();
3. Open ND and go to workspace settings -> tags
4. Go offline
5. Create a new tag named 'Test'
6. Verify that the tag is displayed as greyed out
7. (review [details below](https://github.com/Expensify/App/issues/38410#issuecomment-2004776423) before executing this) Enter the following in the console: Onyx.merge('policyTags_POLICY_ID_HERE', { Tag: { tags: { Test: { errors: { 'test': 'Random error' } } } } })

## Expected Result:
An error is displayed below the tag

## Actual Result:
No error is displayed under the tag after executing the command in the consol

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/33ed0ad5-05d8-404a-a765-e145bf088b6e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdea6ed7743d5caf</li>
        <li>Upwork Job ID: 1780403793249558528</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mallenexpensify** [comment]
Checking on [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1710539851510929)
> Can someone help me understand the importance behind fixing a bug where multiple steps are entering data into the console?

**Comment by mallenexpensify** [comment]
Coming from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1710542827486259?thread_ts=1710539851.510929&cid=C01GTK53T8Q) internally. 

The instructions state the following command:
Onyx.merge('policyTags_POLICY_ID_HERE', { Tag: { tags: { Test: { errors: { 'test': 'Random error' } } } } })

Here, `POLICY_ID_HERE` needs to be replaced by the policy id of the testing persons account.

They're also not creating a tag with the correct name. It should be `Test` and not `test` as stated in the instructions.

Perhaps I should have been more explicit, considering the fact that the QA people aren't devs. I have updated the steps to clarify the above mistakes.
 
I added retest-weekly.

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests.

**Comment by mallenexpensify** [comment]
Thanks @mvtglobally , I commented on the [Slack thread I have going](https://expensify.slack.com/archives/C01GTK53T8Q/p1711752964426489?thread_ts=1710539851.510929&cid=C01GTK53T8Q)
> Lil more help.  What's the reasoning we want to fix an issue where we need to enter code into the console in order to get the bug to happen?  Is the feature in beta?
QA was able to reproduce the issue.

**Comment by mallenexpensify** [comment]
Checking on the slack thread again
https://expensify.slack.com/archives/C01GTK53T8Q/p1712105464362599?thread_ts=1710539851.510929&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment]
Ishpaul helped out in[ the Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1712139826707709?thread_ts=1710539851.510929&cid=C01GTK53T8Q)

Okay so we for the scope of this issue we need to test that the error shows up when anything went wrong while creating a tag, usually this only happens in rare case but we have to show error when this happens, To test this we could either execute that code in console or the easisest way QA can test this is with below steps:

1. Navigate to settings -> About -> troubleshoot -> Enable Simulate Failing requests
2. Open any control/collect workspace -> Create a tag
3. Wait for few seconds until the request fails and verify error message appears.
4. Click on the x icon next to error and verify error is removed.

Was unable to load the vid here.  Need to test again soon.

**Comment by mallenexpensify** [comment]
@jayeshmangwani , can you help me a lil here? I'm a bit at a loss for next steps.  Can you reproduce the issue based on the details in the OP and [above](https://github.com/Expensify/App/issues/38410#issuecomment-2046284848)?
If so, can you snag a vid of the whole process so I can see how it's done? Thx

**Comment by jayeshmangwani** [comment]
@mallenexpensify I think this is not the issue, there is a problem in the testing by QA side

In Issue description, on the 7th step, we are copy/pasting this command `Onyx.merge('policyTags_POLICY_ID_HERE', { Tag: { tags: { Test: { errors: { 'test': 'Random error' } } } } })` in browser's console, and in that command `POLICY_ID_HERE` is workspace id, `POLICY_ID` should be replaced with that workspace ID for where we are testing the tags, so if workspace id is `1`,then `policyTags_POLICY_ID_HERE` will be `policyTags_1`, 


And how to obtain the workspace id? 
If we are at the tags page, then our browser URL will look something like this `https://staging.new.expensify.com/settings/workspaces/B07DBF42A1CB2406/tags`, Here `B07DBF42A1CB2406` is the workspace ID or we can say POLICY_ID and command will be `Onyx.merge('policyTags_B07DBF42A1CB2406', { Tag: { tags: { Test: { errors: { 'test': 'Random error' } } } } })`

I am getting the error below the Tag, so I think there is no issue but merely a problem with how we are testing.


I am attaching a video of how I am testing.

https://github.com/Expensify/App/assets/35371050/293ab2f1-90a1-46f5-96ae-d75bea41e3d1
