### ISSUE TITLE
[Re-test] mweb - Scan - Scan requests made using corrupted files consistently display a spinner in the preview each time they are opened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38429]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a workspace chat
3. Tap plus icon--- request money --- Scan
4. Upload below attached corrupted pdf file
5. Tap request
6. Navigate to LHN
7. Reopen the Workspace chat

Corrupted file: 
[CORRUPT-2024-02-06_11_32_55.302-2024-03-14 19_26_31.015.pdf](https://github.com/Expensify/App/files/14620608/CORRUPT-2024-02-06_11_32_55.302-2024-03-14.19_26_31.015.pdf)

## Expected Result:
Scan requests made using corrupted files should not continuously display a spinner in the preview.

## Actual Result:
Scan requests made using corrupted files consistently display a spinner in the preview each time they are opened

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/543b6421-8366-4705-ae3b-5dea06cd35a7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by strepanier03** [comment]
Thank you @HezekielT - I'll place this on hold. I was going to close it for focus on higher value bugs anyway so holding works for me.

**Comment by strepanier03** [comment]
Polish priority and on hold still.

**Comment by strepanier03** [comment]
HOLD GH is still open, paused for now.

**Comment by strepanier03** [comment]
THe HOLD GH was closed for being unable to repro. Will let this get tested again and close if this isn unrepro as well.

**Comment by strepanier03** [comment]
Closing out, still can't repro.
