### ISSUE TITLE
Attachment – New message button appears when send image and navigate between tabs

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38438]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4429434
**Email or phone of affected tester (no customers):** ponikarchuks+315324@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app.
2. Log in
3. On a conversation, click on the + button in the compose box
4. Click on add attachment
5. Verify the New message button appears on the top when open the attachment selector
6. Upload an image and send
7. Start to navigate between tabs
8. Open New Expensify app again

## Expected Result:
New message button not appears

## Actual Result:
New message button appears in the Step 4
New message button appears when send image and start navigate between tabs and disappears if open app again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4b7b10ce-b242-4d02-884c-4e6dc66dc587

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment]
Yeah I don't think we need to worry about this one right now. I don't understand what the bug is clearly
