### ISSUE TITLE
Background changes to workspace when changing the workspace name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38436]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a workspace from "Choose a workspace"
2. Now click on workspace name
3. Notice background changed

## Expected Result:
The background should not change when RHN open

## Actual Result:
Background changes to workspace when changing the workspace name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/74cdd3a4-c57e-4d93-a1d7-f4fab5dc71ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@miljakljajic I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by godofoutcasts94** [comment]
This is the regression caused by this [PR](https://github.com/Expensify/App/pull/37421/files#diff-431da5317a5ef6f078e6a905c55de8e3387c1c41a3abab9cf749b23d71b45296R185-R192)

**Comment by miljakljajic** [comment]
I agree that we can close in favour of https://github.com/Expensify/App/issues/38420
