### ISSUE TITLE
Workspace - No email for user with no NewDot account after Invite to WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38437]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4428073
**Email or phone of affected tester (no customers):** applausetester+023pronin@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to NewDot and login
2. Go to Workspace\Members
3. Invite a new user (that doesn't have a NewDot account)

## Expected Result:
Invited user should receive email

## Actual Result:
Invited user doesn't get email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec9e3358-34e8-4507-b623-454c8e958ba0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca4c9a14f07edfb9</li>
        <li>Upwork Job ID: 1770182630404644864</li>
        <li>Last Price Increase: 2024-03-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment]
Agreed with project, I think that the email is being generated by the BE so this probably should be internal.

**Comment by muttmuure** [comment]
This seems like it would be CRITICAL

**Comment by muttmuure** [comment]
https://expensify.slack.com/archives/C036QM0SLJK/p1710879332368379

**Comment by muttmuure** [comment]
Adding Internal preemptively to get C+ assigned

**Comment by muttmuure** [comment]
@allroundexperts could you confirm if this needs to be fixed on the BE?

**Comment by muttmuure** [comment]
@allroundexperts will this be fixed by https://github.com/Expensify/Web-Expensify/pull/41335?

**Comment by allroundexperts** [comment]
This is a backend bug. I can confirm that.

**Comment by allroundexperts** [comment]
The link https://github.com/Expensify/Web-Expensify/pull/41335 is for the backend repository which I don't have access to.

**Comment by muttmuure** [comment]
Oops, of course. Sorry!

**Comment by muttmuure** [comment]
So the expected behavior here is that the user receives a chat summary from Concierge after being added to New Expensify. @lanitochka17 do you mind checking that flow instead?
