### ISSUE TITLE
[HOLD for payment 2024-03-29] [$250] [Wave Collect] [Workflows] Clean up the isAutoApprovalEnabled flag 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38445]
### Problem

We use the `isAutoApprovalEnabled` flag to decide if the approval toggle should be on or off in Workflows page https://github.com/Expensify/App/blob/f84219f187f9960df17c584e7c8b10feee77f27f/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L137

We should however use a comparison to the `policy.approvalMode` as we do [here](https://github.com/Expensify/App/blob/f84219f187f9960df17c584e7c8b10feee77f27f/src/libs/actions/Policy.ts#L568) to define if the auto approval is enabled. It is true when the approval mode is set to basic.

The isAutoApprovalEnabled property is not passed from the backend, it should be removed for now. 

This property exists, but its used in different way and we can bring it to the app later.

### Solution

Use the `approvalMode` property to determine the toggle state
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01573ee41af24d66fa</li>
        <li>Upwork Job ID: 1769144226309750784</li>
        <li>Last Price Increase: 2024-03-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by trjExpensify** [comment]
@mountiny confirming we're not looking for volunteers here and we're done?

**Comment by mountiny** [comment]
We are not, @abzokhattab sorry, I marked this as internal as there might be some changes required in the backend, I will handle this one

**Comment by mountiny** [comment]
PR is in review

**Comment by mountiny** [comment]
$250 to @hoangzinh for this this one

**Comment by mountiny** [comment]
No need for the checklist here

**Comment by slafortune** [comment]
Invite sent [here](https://www.upwork.com/nx/wm/offer/101642592) @hoangzinh

**Comment by slafortune** [comment]
Paid
