### ISSUE TITLE
[HOLD for payment 2024-03-26] [Performance] Use Intl API from Hermes where possible

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38447]
Coming from [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1710420224482389) cc @hurali97 please comment so I can assign you

### Problem
We have Intl polyfills in the codebase to provide for the missing JS APIs. While that’s not a bad thing, we can take advantage of Hermes supported Intl APIs and avoid polyfilling them. If we don’t do it, we add ~500 ms to the App Startup time on android on a heavy account.

### Solution
Hermes has a list of Intl supported APIs and we can take advantage of them. On native platforms, we can remove the Intl APIs that are supported by Hermes and only polyfill the ones that are currently not supported/ worked on by Hermes.
We can safely remove the following polyfills from localize/index.native.ts:
- @formatjs/intl-getcanonicallocales/polyfill
- @formatjs/intl-datetimeformat
- @formatjs/intl-numberformat
- @formatjs/intl-pluralrules/polyfill

Below is how things will look like after the removal:
```
import polyfillListFormat from './polyfillListFormat';
import type IntlPolyfill from './types';

/**
 * Polyfill the Intl API, always performed for native devices.
 */
const intlPolyfill: IntlPolyfill = () => {
    // Native devices require extra polyfills which are
    // not yet implemented in hermes.
    // see support: https://hermesengine.dev/docs/intl/

    require('@formatjs/intl-locale/polyfill');

    polyfillListFormat();
};

export default intlPolyfill; 
```

With this, we only polyfill the APIs that are not supported/ worked on by hermes. Doing so, we save ~500 ms in the App Startup. Before and After Hermes trace screenshots are attached in the [PR](https://github.com/Expensify/App/pull/38228) description.
Here’s the PR with the implementation.

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 26

- Fix: @hurali97 - Callstack - no Upwork payment
- PR Review: @rlinoz - Internal - no payment 😉 

@rlinoz do you think this one needs a regression test? otherwise, I can close this one out on Mar 26 after the PR regression period ends.

**Comment by rlinoz** [comment]
This got reverted actually, so let's keep it open.

But I don't think it needs  a regression test

**Comment by abekkala** [comment]
- @slafortune will be handling for me while I'm ooo

PAYMENT SUMMARY FOR MAR 26
Fix: @hurali97 - Callstack - no Upwork payment
PR Review: @rlinoz - Internal - no payment 😉

No regression test needed - this can be closed on Mar 26 after waiting period has ended

**Comment by slafortune** [comment]
Just taking the action here - @abekkala has it all summarized 👍
