### ISSUE TITLE
[Performance] Remove unused dependencies from the project and import only date-fns submodule

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38446]
### Problem

Coming from [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1710450633708089)

Unused dependencies are increasing the bundle size which is making the app slower to start and its not a good practice in general.

### Solution

Remove unused dependencies and for date-fns, only import the submodule we actually need.

Furthermore add an eslint to prevent the later from happening again

**Comment by mountiny** [comment]
@jbroma please comment so I can assign you

**Comment by jbroma** [comment]
👋

**Comment by kacper-mikolajczak** [comment]
@mountiny commenting!

**Comment by mountiny** [comment]
PR merged

**Comment by mountiny** [comment]
I think this was straightforwards, no c+ to pay, we can close now
