### ISSUE TITLE
Tag - 'Error Importing Tags' when editing Budget

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38458]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2778053
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: User is logged in OldDot and added Corporate Workspace. Custom Tag added.

1. Navigate to Corporate workspace settings > Tags.
2. Click on 'Edit Budget' for added tag.
3. Enable 'Edit Tag Budget'.
4. Set 'Total workspace budget', 'Per member budget' and 'Threshold Notification' > Save.
5. Go to main Reports tab > Add New Report.
6. Add Expense to report with a custom tag.
7. Submit report and Final Approve it.
8. Again, navigate to workspace setting > Tags.
9. Edit Total workspace budget' (or 'Per member budget').
10. Click 'Save'.

## Expected Result:
The new value of Total workspace budget' (or 'Per member budget') saved.

## Actual Result:
Popup with an error 'Error importing tags' appears. When user closes it, another popup 'Oops... an error has occurred!' appears. Old value is visible on the preview, but if user opens Edit Budget, new value is viewed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2d8868e0-8bfa-41fd-a1ba-d22cfcfbd643

![Bug6416788_1710690076469!Error_importing_tags](https://github.com/Expensify/App/assets/115492554/d19e8381-dd8f-48c8-b264-2ea0efc195d5)
![Bug6416788_1710690076477!Oops _an_error](https://github.com/Expensify/App/assets/115492554/2d821d40-f5c0-484f-bcac-4738f0aeb548)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This is oldDot blocker
