### ISSUE TITLE
[HOLD for payment 2024-04-15] HIGH: [Reliability] Enable console logging with four-finger tap

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#38456]
Problem:
===
We've gotten very good at fixing bugs that can be reproduced in our dev environments.  However, bugs we can't reproduce in dev are typically ignored -- even if they happen frequently in production.  We have added better diagnostics tools via the `About > Troubleshooting > Client side logging` toggle.  However, currently it takes you out of the context in which the bug is actually happening to enable. This means to use it you must:

1. Experience the bug
2. Leave that context to go to `About > Troubleshooting > Client side logging`
3. Enable client side logging
4. Go back to the original context
5. Try to reproduce the bug
6. Leave that context to go to `About > Troubleshooting > Client side logging`
7. Open the console
8. Save the file
9. Disable client side logging

In that whole process, the logs are filled with tons and tons of extraneous lines, making it very hard to isolate the problem -- assuming you can even reproduce it.

Solution:
====
Margelo recently added a "four finger tap" to enable low-level performance logging:

![Image](https://github.com/Expensify/App/assets/575186/9f211711-6d0a-4739-892c-7e877c71cf28)

This works great because:

1. You can enable and disable right where you experiencing the problem, without needing to leave that context.  This tightens up the focus on the actual problem period, avoiding extraneous sampling.
2. It automatically saves the file to local storage when disabled.

Let's expand that as follows:

1. Allow enabling/disabling the console log directly from the "four finger tap menu"
2. Automatically save the logs to disk when disabled (in either the four-finger menu, or in the `About > Troubleshooting` menu)
3. Show the filename that it was saved to, along with the platform `Share` button to share it (this is already being used for the profile traces, so let's use it for logs as well)

**Comment by quinthar** [comment]
@TMisiukiewicz hoping you can take this?

**Comment by TMisiukiewicz** [comment]
@quinthar sure, I should be able to work on this later this week 👍

**Comment by quinthar** [comment]
Great, so ETA Friday?

**Comment by TMisiukiewicz** [comment]
@quinthar yeah, I am about to start working on that tomorrow 👍 What if the client side logging in Troubleshoot section is enabled while you access the hidden menu, should it be just enabled or both of these features should work independently?

**Comment by TMisiukiewicz** [comment]
Opened a PR

**Comment by quinthar** [comment]
> What if the client side logging in Troubleshoot section is enabled while you access the hidden menu, should it be just enabled or both of these features should work independently?

They should both control the same console, so if it's enabled in one, it should show as enabled in the other.

**Comment by s77rt** [comment]
**Regression Test Proposal**
1. Press anywhere using 4 fingers (four-finger tap)
2. Verify that a debug modal is opened
3. Enable Client side logging
4. Close modal
5. Do any regular activity (e.g. open a report)
6. Open debug modal again (four-finger tap)
7. Disable Client side logging
8. Verify that a file path is displayed and the Share button is visible
9. Press the share button
10. Verify you are able to share the file

(Related https://expensify.testrail.io/index.php?/cases/view/2990265)

**Comment by twisterdotcom** [comment]
Payment Summary:

- @TMisiukiewicz does not require payment (Contractor)
- @s77rt paid $500 [here](LINK) WIP
