### ISSUE TITLE
[$250] LHN - "Hey there, I'm Concierge" message disappears from the Concierge chat preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53.3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4430550
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with a new expensifail account
2. Dismiss the welcome message
3. Open the Concierge chat after the message disappeared from the LHN
4. Navigate back to the LHN

## Expected Result:
"Hey there, I'm Concierge" message should be always visible.

## Actual Result:
"Hey there, I'm Concierge" message disappears from the Concierge chat preview. It appears again if you navigate to the Concierge chat and back.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/481be97f-b05b-4efc-a5bf-be8f6cc36d8c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1cbde38625aca5c</li>
        <li>Upwork Job ID: 1769656950410633216</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Adding this as polish to Wave Collect as its related to the onboarding flow

From the video this just looks like the preview of the message changes, but the message is there and the preview updates correctly when user navigates to the chat. The preview is cut off nonetheless so I think this does not have to be a blocker, but it would be great to have someone look into this

**Comment by hungvu193** [comment]
I think this BE issue, the response returned `lastMessageText`: `Welcome to Expensify`

<img width="975" alt="Screenshot 2024-03-18 at 16 48 31" src="https://github.com/Expensify/App/assets/16502320/8ce88053-ea70-4182-9dc1-eedbe776cef1">

**Comment by CortneyOfstad** [comment]
I agree as well @hungvu193 — going to adjust this accordingly 👍

**Comment by CortneyOfstad** [comment]
Still waiting on an engineer to pick this up 👍

**Comment by CortneyOfstad** [comment]
No overdue — still waiting on engineering 👍

**Comment by CortneyOfstad** [comment]
Still a hot pick 🙃

**Comment by CortneyOfstad** [comment]
@izarutskaya can we confirm if this issue is still taking place? I've not been able to recreate — thanks!

**Comment by CortneyOfstad** [comment]
@izarutskaya bump ^^^ I am still having trouble recreating
