### ISSUE TITLE
[$500] [HOLD for payment 2024-04-03] IOS -  Profile - Avatar loading icon is not aligned properly within the highlighted green circle

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38450]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Device font is minimum.
1. Launch New Expensify app.
2. Log in.
3. While the app is in skeleton loading state, tap on Profile icon.

## Expected Result:
The avatar loading icon has the correct size within the highlighted green circle.

## Actual Result:
The avatar loading icon is small and not aligned properly within the highlighted green circle.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/e1d311f4-e38d-4245-83da-d2a6cfd31df2)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183d1c8e91b21dfe4</li>
        <li>Upwork Job ID: 1775220315708272640</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
This does seem like could have been resolved by https://github.com/Expensify/App/pull/38274 which we wont CP, removing the blocker label. 

Lets retest in next staging release @kavimuru @kbecciv

**Comment by kosmydel** [comment]
> This does seem like could have been resolved by #38274 which we wont CP, removing the blocker label.
> 
> Lets retest in next staging release @kavimuru @kbecciv

I will check it later today. This might not be solved by the above PR, as I don’t remember changing the skeleton dimensions.

**Comment by hayata-suenaga** [comment]
@kosmydel could you test if the issue still exists?

**Comment by lschurr** [comment]
Assigned to @mkhutornyi since you were the C+ reviewer on the PR.

**Comment by lschurr** [comment]
Sorry for the ping @ikevin127 - This bug is already fixed. Removing your assignment :)

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @kosmydel (agency, no payment needed)
- Contributor+: @mkhutornyi $500 ([Offer sent in Upwork](https://www.upwork.com/nx/wm/offer/101702607))

**Comment by lschurr** [comment]
Hi @mkhutornyi - please accept the offer in Upwork :)

**Comment by lschurr** [comment]
Bumped in Slack

**Comment by lschurr** [comment]
Still waiting for @mkhutornyi to accept the offer. Moving to Weekly in the meantime.

**Comment by lschurr** [comment]
The offer still isn't accepted by @mkhutornyi - I've reached out in Slack. Please reopen the GH or send me a message via Slack when you're ready for payment. Closing this GH for now.

**Comment by lschurr** [comment]
New offer sent to @mkhutornyi - https://www.upwork.com/nx/wm/offer/102626632
