### ISSUE TITLE
[HOLD for payment 2024-05-08] [ECard Settings Polish] Update the `Assigned Cards Section` of the Wallet Page + `Card Details` Pages to support multiple expensify cards.

### ISSUE THREAD

**Issue by grgia** [Expensify/App#38468]
## HOLD 
Held on BE changes from https://github.com/Expensify/Expensify/issues/379978

Once those changes are made, I will update this issue

## Background

![image](https://github.com/Expensify/App/assets/38015950/cdb3130e-79c3-4aed-b4ca-02b51ca9d8b7)

New Card App TS data: https://github.com/Expensify/App/pull/38590

Here's the idea:

If you have a ton of cards, we need to group them properly in app. Right now, all the cards link to `/expensify.com` and do not display the correct card. 

We instead need to group cards in this way:

Any card that is `!isAdminIssuedVirtualCard` will be grouped in a row with title `Expensify Card`.  In the case a user has two domains with two expensify cards, we would have two rows with the title `Expensify Card` and clicking on each row will use the domain in the URL to open the card page. In other words,  If `!isAdminIssuedVirtualCard, group by domain`

If for some reason, a user has more than 1 physical or virtual card in their domain, we will display them all on the linked card page and we will show the activate button if ANY of the cards in this group are in the `NOT_ACTIVATED` state.

Any card that is `isAdminIssuedVirtualCard` will have it's own row. Each of these cards should have a `cardTitle`. We can use the title of the card for the URL to open the card page. In other words,  If `isAdminIssuedVirtualCard, each card is it's own group`

### New Copy: 

We also will add a blurb about the limit on the CardDetailsPage. This will be stored in `card.limitType` and there are three descriptions we will need to add to es/en

**monthly:** You can spend up to `formattedLimit` on this card per month. The limit will reset on the 1st day of each calendar month.
**fixed:** You can spend up to `formattedLimit` on this card, and then it will deactivate. 
**limit:** You can spend up to `formattedLimit` on this card, and the limit will reset as your submitted expenses are approved.

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by grgia** [comment]
@LLPeckham could you double check on the copy I mentioned in the description 🙏🥹

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by SzymczakJ** [comment]
@grgia should I create design doc for this or will proposal on PR be sufficient?

**Comment by LLPeckham** [comment]
Thoughts on this? Just so it's clear that it's spending limits?

**monthly:** You can spend up to $300 on this card per month. The limit will reset on the 1st day of each calendar month.
**fixed:** You can spend up to $200 on this card, and then it will deactivate. 
**limit:** You can spend up to $200 on this card, and the limit will reset as your submitted expenses are approved.

**Comment by LLPeckham** [comment]
Also heads up I'm OOO tomorrow - Fri, so if you need more help please re-assign!

**Comment by grgia** [comment]
@LLPeckham looks great, thank you!

**Comment by grgia** [comment]
es translations thread created: https://expensify.slack.com/archives/C21FRDWCV/p1711018443613819

**Comment by grgia** [comment]
> @grgia should I create design doc for this or will proposal in the PR be sufficient?
Apologies I missed this comment @SzymczakJ, but just a proposal is good!

**Comment by grgia** [comment]
Here's our current translations @SzymczakJ 
```
en: You can spend up to <$$$> on this card per month. The limit will reset on the 1st day of each calendar month.
es: Puedes gastar hasta <$$$> en esta tarjeta al mes. El límite se restablecerá el primer día del mes.

en: You can spend up to <$$$> on this card, and then it will deactivate.
es: Puedes gastar hasta <$$$> en esta tarjeta, luego se desactivará.

en: You can spend up to <$$$> on this card, and the limit will reset as your submitted expenses are approved.
es: Puedes gastar hasta <$$$> en esta tarjeta y el límite se restablecerá a medida que se aprueben tus gastos.
```

**Comment by grgia** [comment]
In progress. BE PR in review

**Comment by grgia** [comment]
PR has draft up

**Comment by grgia** [comment]
PR in review

**Comment by grgia** [comment]
Looks like @rojiphil requires payment ($500) for C+ review. Would you mind helping with that and then we can close this out @LLPeckham ?

**Comment by kevinksullivan** [comment]
I think this one is me, or if not I'm happy to take care of it. Automation for upwork failed so I created a job here:

https://www.upwork.com/nx/job-post/?uid=1788273034584907776

@rojiphil can you let me know when you've accepted?

**Comment by rojiphil** [comment]
> can you let me know when you've accepted?

Accepted offer. Thanks

**Comment by rojiphil** [comment]
@grgia The payment step is not yet completed here. Can you please reopen the issue?

**Comment by rojiphil** [comment]
> > can you let me know when you've accepted?
> 
> Accepted offer. Thanks

@kevinksullivan Gentle bump on payment here

**Comment by kevinksullivan** [comment]
On it

**Comment by kevinksullivan** [comment]
All set @rojiphil
