### ISSUE TITLE
LHN - The name of the archived workspace room after merge is "Chat report"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4430652&group_by=cases:section_id&group_id=229067&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Admin: Log in with an expensifail user
2. Admin: Create a workspace
3. Admin: Invite two expensifail users (account A and B)
4. Admin: Write a single message in each of the new members workspace rooms
5. Log in with Account A and log out
6. Log in with Account B and log out
7. Admin: Remove account B from the workspace
8. Account A: Log into OD and merge with account B
9. Account A: Log into ND
10. Account A: Open the archived workspace room

## Expected Result:
It should display it's correct name even if I don't open it.

## Actual Result:
The name of the archived workspace room after merge is "Chat report". It changes to the correct name after opening it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/cd5c3afd-de5c-4b70-a2fe-2062325ff178

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think that this bug might be related to the  #collect project.

**Comment by twisterdotcom** [comment]
I disagree, I couldn't recreate when performing these actions reasonably and normally, and given even in this niche situation, if it does self resolve when clicking on the offending report, I'm not worried about this causing mass confusion to end users. Therefore closing.

https://github.com/Expensify/App/assets/9133401/9c2747ba-624d-44fd-b2a4-9625ecef05d6
