### ISSUE TITLE
[HOLD for payment 2024-06-24] [HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [POLISH][Simplified Collect] Create utils files for each page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#38477]
Policy.ts is a large file and it'll only get larger and larger. We can keep the code more organized by separating each individual Members, Categories, Tags and Distance Rates into its own utils file, like we did for taxes [here](https://github.com/Expensify/App/pull/37967/files#r1528533441), i.e. `/actions/Policy/TaxRates.ts`, etc

**Comment by amyevans** [comment]
Started on this today, I'll split it up into a few PRs to make review a little easier.

Looking at Category to start, 1 clarifying question: `Policy.ts` contains category-related functions that are used by the Simplified Collect Category page (like `openPolicyCategoriesPage`), as well as others used when requesting money (like `buildOptimisticPolicyRecentlyUsedCategories`). I was going to move them all, but wanted to check that matches what you were thinking @luacmartins?

**Comment by luacmartins** [comment]
Yea, that makes sense.

**Comment by amyevans** [comment]
No update - haven't had much time to swing back around to this between some OOO and other commitments the past few days but will prioritize shortly

**Comment by amyevans** [comment]
Have been prioritizing a fast-apis issue and detailed design for the Billing card project. If anyone's interested in knocking this out feel free to take it from me, otherwise I'll work on it once I hit a lull in other work

**Comment by dangrous** [comment]
Discussed with @amyevans, I can take this over! It may still be a bit slow since I'm only in a couple days each week but hopefully will get a good chunk of it going today and Thursday. I like the idea of splitting up the PRs, so I'll aim to get at least one out this week.

**Comment by dangrous** [comment]
not overdue, PRs are in progress. Waiting for merge slush to be less, er, slushy. Since this SHOULDN'T post any problems but a little scary while we're taking a harder look at merges.

**Comment by dangrous** [comment]
Do we think we should include the `Owner` functions in `Member.ts`? Kind of like a member...

**Comment by luacmartins** [comment]
I think so, they are all members of the policy, but with different access levels.

**Comment by dangrous** [comment]
I think once these are all on prod we should be good to close this, unless you can think of some other files we might want to break this up into? I don't see any nice groupings in the remaining functions really.

Oh and let me know what y'all think about https://github.com/Expensify/App/pull/42305#issuecomment-2136157363 too.

**Comment by luacmartins** [comment]
Did the migration solve the issue?

**Comment by dangrous** [comment]
> Did the migration solve the issue?

Unfortunately not. It's three functions that are causing the issue:
* `removePendingFieldsFromCustomUnit` defined in `Policy.ts`, used in `Category.ts` and `DistanceRate.ts`
* `navigateWhenEnableFeature` defined in `Policy.ts`, used in `Policy.ts`, `Tag.ts`, `Category.ts`, and `DistanceRate.ts`
* `buildOptimisticPolicyCategories` currently defined in BOTH `Policy.ts` and `Category.ts`, used in `Policy.ts` and `Category.ts`

Ideally we'd keep the first two where they are (in `Policy.ts`) and move the last one to ONLY `Category.ts` but that's posing the problem.

The last one makes the most sense to move or duplicate, since the top two are shared in multiple files (though the top two are also much shorter).

So maybe we leave it? Unless there's an additional file we could create with those and perhaps other utility methods or something like that.

**Comment by luacmartins** [comment]
Could we move the first 2 to `PolicyUtils`? For the `buildOptimisticPolicyCategories`, how does it create a circular dependency? I don't see `Policy.ts` importing `Category.ts` and vice-versa, so could we define it in `Category.ts` and then import `Category` in `Policy.ts`?

**Comment by dangrous** [comment]
Can't import category into policy (which it's not doing now) because category is already importing policy.

But moving those two into PolicyUtils should work, I can spin that up.

**Comment by luacmartins** [comment]
>Can't import category into policy (which it's not doing now) because category is already importing policy.

Ah I missed the Policy import on Category the first time since it's importing specific functions. But the only imports from Policy are the 2 functions we're moving to PolicyUtils, no? So that means we can remove that Policy import in Category

**Comment by dangrous** [comment]
yep! that PR above should solve our problems

**Comment by dangrous** [comment]
No payment needed here but I'll close this on the 24th. Not expecting any regressions (though when ARE we expecting them?)

**Comment by luacmartins** [comment]
@dangrous I think we can close this issue since it's deployed to prod and was internal. We'll know if there's a regression haha
