### ISSUE TITLE
New message not shown in chat after clicking on notification

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38480]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710524006372329
 
## Action Performed:
1. Log into NewDot mobile with a slow connection on account A
2. Swipe up to go home and close the app, but no need to kill it
3. Send a message from account B to A in a DM
4. As A, click on the notification for the message from B
## Expected Result: 
The chat with account B immediately opens and shows the message from B as the latest chat message
## Actual Result: 
The chat with account B opens, but it does not show the message from the notification for as long as I waited.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
ios <> Android issue swap with Kadie

**Comment by kadiealexander** [comment]
I'm not able to repro this - @neil-marcellini do you have a video or something of this happening?

**Comment by kadiealexander** [comment]
@neil-marcellini bump!

**Comment by kadiealexander** [comment]
Neil is going to try get us some repro steps!

**Comment by kadiealexander** [comment]
Shifting to weekly while Marqeta do the needful.

**Comment by kadiealexander** [comment]
Shifting to weekly while we wait to see if this is reproducible.

**Comment by kadiealexander** [comment]
Closing this one out, please reopen if it comes up again @neil-marcellini!
