### ISSUE TITLE
[HOLD for payment 2024-04-03] [$500] [Simplified Collect][Taxes] - Unable to add custom tax name after clearing the custom tax name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an admin of Collect workspace
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to More features
4. Toggle on Taxes
5. Click Add rate
6. Add a tax rate
7. Click Settings
8. Add a "Custom tax name", "Workspace currency default" and "Foreign currency default"
9. Click Custom tax name
10. Clear the custom name and save it
11. Click Custom tax name again
12. Add a custom tax name and save it

## Expected Result:
The new custom tax name will be saved

## Actual Result:
The new custom tax name is not saved and it reverts to empty state

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a9d7625b-8db9-412d-a702-02b0bf8ce70f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d9ced651589c65d</li>
        <li>Upwork Job ID: 1769782817172688896</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@arosiclair  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment]
This is NAB since most people don't have access to this functionality yet. I can take this since it was introduced in https://github.com/Expensify/App/pull/38373.

**Comment by luacmartins** [comment]
cc @kosmydel @filip-solecki

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on it!

**Comment by trjExpensify** [comment]
Automation didn't run. PR is on prod, needs payment tomorrow.

**Comment by trjExpensify** [comment]
Okay, so payment summary as follows: 

- $500 to @hungvu193 for the C+ review 

Offer sent

**Comment by hungvu193** [comment]
> Okay, so payment summary as follows: 
> 
> 
> 
> - $500 to @hungvu193 for the C+ review 
> 
> 
> 
> Offer sent 
> 
> 
> 
> 

I've just accepted the offer. Thank you

**Comment by trjExpensify** [comment]
Paid!
