### ISSUE TITLE
[HOLD for payment 2024-04-05] [HOLD for payment 2024-04-03] [Simplified Collect][Taxes] Value row shows decimal point with no digit when saving amount with a dot and with no digit after 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38499]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y 
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Taxes.
4. Click Add rate.
5. Click Value.
6. Enter an amount, followed by a dot (decimal).
7. Save the value with empty amount after the decimal.

## Expected Result:
The Value row will not display decimal since there is no value after the dot.

## Actual Result:
The Value row shows decimal with no digit after it.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/736f3662-21b5-4de4-95a2-d4ebcc8f024f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Value row shows decimal point with no digit when saving amount with a dot and with no digit after
### What is the root cause of that problem?
we display and send to backend what user type in amount field without clean it.
### What changes do you think we should make in order to solve the problem?
we can add `parseFloat` to value here to be ```return `${parseFloat(value)}%`;```
https://github.com/Expensify/App/blob/ed6fbbc4ba40990b61fd92f32b95b205422ab904/src/libs/actions/TaxRate.ts#L15-L17

and this method is used in the title and before send tax to backend


### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment]
This was introduced [here](https://github.com/Expensify/Expensify/issues/365157). This is NAB since this feature is only available on Collect policies in NewDot and users don't have access to that yet. I think we can address that as a follow up to the other tax PRs. cc @kosmydel @filip-solecki

**Comment by chiragsalian** [comment]
I leave it to @luacmartins since i belive he's working on this feature. Also @ShridharGoel, i think your proposal might be incorrect since it will block a user from entering a decimal unless they click on the left arrow to go somewhere in between a number and then enter a decimal which is not the best user experience.

**Comment by kosmydel** [comment]
Hey, I am the author of the original PR and I will take care of this one.

Can the value rates be decimal? If so, how many decimal places should we show?
@luacmartins

**Comment by luacmartins** [comment]
Thanks for taking this on @kosmydel! It seems like OldDot accepts 16 decimals 😅 @trjExpensify can you confirm if we should keep the same behavior?

**Comment by luacmartins** [comment]
Confirmed internally that we should support up to 16 decimals!

**Comment by trjExpensify** [comment]
Lol yeah, no idea why it's 16 decimals but let's not introduce a discrepancy across OldDot/NewDot without a good reason to!

**Comment by kosmydel** [comment]
> Lol yeah, no idea why it's 16 decimals but let's not introduce a discrepancy across OldDot/NewDot without a good reason to!

I changed it, but our component (`@/components/AmountForm.tsx`) that we use [has a limit of 10 for the length of the amount](https://github.com/Expensify/App/blob/96716fbf18d7179289eaf59a53928d0727f849ac/src/libs/MoneyRequestUtils.ts#L58). In our case, it means 8 decimals places. Should I modify it, to support 16 decimal places? Or 8 places is enough?

**Comment by kosmydel** [comment]
cc @luacmartins, @trjExpensify do you think the above is fine?

**Comment by luacmartins** [comment]
We discussed this in Slack, we'll update the components to support 16 decimals. Additionally, we'll update the param sent to the API to better align with what's stored both locally and in the DB.

**Comment by trjExpensify** [comment]
Yeah, it makes sense to align the two. I really want to meet the person with 16 decimals in play though, I bet they are the _best_ customer! :)

**Comment by kosmydel** [comment]
The 16 decimals limit leads to the overflow. [Slack thread](https://swmansion.slack.com/archives/C036QM0SLJK/p1711366782758249?thread_ts=1711034001.530799&cid=C036QM0SLJK).

**Comment by trjExpensify** [comment]
Yeah, all good. Are we handling that here or somewhere else?

**Comment by luacmartins** [comment]
I think this was handled in the menuItem, but the BNP still shows it 

https://github.com/Expensify/App/assets/22219519/0e4cb400-c1e0-48b7-8810-798d615d6b1b

**Comment by sonialiap** [comment]
@luacmartins did the linked PR cause a regression?

**Comment by luacmartins** [comment]
This was a new feature and it was under development at the time, so no regressions

**Comment by sonialiap** [comment]
@shubham1206agra $500 - [offer sent](https://www.upwork.com/nx/wm/offer/101776272)

**Comment by sonialiap** [comment]
@shubham1206agra let me know if you didn't receive the offer on Upwork. If you have, it's ready for you to accept and be paid :D

**Comment by sonialiap** [comment]
Shubham asked for payment to be delayed - [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1713176982329049)

**Comment by sonialiap** [comment]
Melvin, not overdue

**Comment by sonialiap** [comment]
Paid
