### ISSUE TITLE
[Simplified Collect][Taxes] iOS - Taxes - App crashes tapping tax value

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an admin of Collect workspace.
1. Open app
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Taxes.
4. Click Add rate.
5. Click Value.

## Expected Result:
Able to add tax value

## Actual Result:
App crashes

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/29ca9cf8-8c29-4c07-87bf-094ce672689f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-control

**Comment by kbecciv** [comment]
@francoisl The app crashes when adding the distance rate, do we need to create a separate GH or the same root cause?

https://github.com/Expensify/App/assets/93399543/dfbbdd2c-f715-4b00-bfae-18ec44726711

**Comment by francoisl** [comment]
I can repro on iOS, this seems to come from https://github.com/Expensify/App/pull/37967.

> The app crashes when adding the distance rate, do we need to create a separate GH or the same root cause

Not sure yet but it might be a different cause, the PR I linked to is specific to tax rates. Maybe it's safer to open a separate issue for now.

**Comment by luacmartins** [comment]
This was introduced https://github.com/Expensify/App/pull/37967. This is NAB since this feature is only available on Collect policies in NewDot and users don't have access to that yet. I think we can address that as a follow up to the other tax PRs. cc @kosmydel @filip-solecki

**Comment by mountiny** [comment]
I am making a revert of that PR, we can just give it another go later knowing these issues

**Comment by luacmartins** [comment]
This has been fixed by the revert. Gonna close.
