### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Investigate and address Image.getSize / react-native-image-size discrepancy

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#38500]
### Problem
We currently have an unused dependency in this project - `react-native-image-size`. This is problematic because it unnecessarily bloats our application, and we've invested time in upgrading it to the New Arch.

Meanwhile, there's a reason we added it in the first place - it solves a [problem with `Image.getSize` and the underlying Fresco image lib](https://github.com/facebook/fresco/issues/2236) where large Android images are downsampled [recent example](https://expensify.slack.com/archives/C04878MDF34/p1710413579991739?thread_ts=1710348441.004189&cid=C04878MDF34), producing incorrect results on Android.

It's unclear the degree to which this affects our end-users, but it seems like we should do _something_.

### Solution
- Remove all uses of `Image.getSize`, replace them with `react-native-image-size`
- Use ESLint rules to prevent further usage of `Image.getSize`, in favor of `react-native-image-size`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017637a44480adad34</li>
        <li>Upwork Job ID: 1775302211863654400</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by bernhardoj** [comment]
There is 1 [open issue here](https://github.com/Expensify/App/issues/37358) where I propose to replace `Image.getSize` with `react-native-image-size` in `AttachmentPicker/index.native.js`.

**Comment by kosmydel** [comment]
Hey, I will be able to take care of this issue later this week/at the beginning of next week.

**Comment by kosmydel** [comment]
Hey @roryabraham, I've prepared two PRs for this issue:
- [one, which adds web support to the `react-native-image-size` library,](https://github.com/Expensify/react-native-image-size/pull/4/files),
- [2nd one, which replaces `getSize` and adds ESLint rules.](https://github.com/Expensify/App/pull/38746)

**Comment by roryabraham** [comment]
@anmurali the [PR](https://github.com/Expensify/App/pull/38746) was deployed to staging 12 hours ago. Assuming no regressions, the only payment due here would be $500 to @ishpaul777 for the C+ review

**Comment by roryabraham** [comment]
only payment should be $500 to @ishpaul777 for their C+ review

**Comment by anmurali** [comment]
Offer is [here](https://www.upwork.com/nx/wm/offer/101898444)

**Comment by anmurali** [comment]
Done
