### ISSUE TITLE
[Simplified Collect][Distance Rates] Distance rates - Enter key does not save distance rate

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38509]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38035
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an admin of Collect workspace.
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Distance rates.
4. Click Add rate.
5. Enter amount.
6. Hit Enter.

## Expected Result:
Enter key will save the rate.

## Actual Result:
Nothing happens when hitting Enter key on Add rate page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4693ea7c-f3c3-4051-8e2e-2f9720f764d5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment]
This was introduced in https://github.com/Expensify/App/pull/38035 and it's not a blocker since it only affects collect policies in NewDot. We can address this in a follow up PR cc @MrMuzyk

**Comment by ArekChr** [comment]
Hey @luacmartins, I'm available to handle this issue, please assign me

**Comment by luacmartins** [comment]
Closing this one since we already merged a fix via another PR.
