### ISSUE TITLE
iOS - Workspace - App crashes when tapping Reimbursements

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:**  n
**Issue reported by:**

## Action Performed:
1. Launch New Expensify app.
2. Go to Profile > Workspaces.
3. Go to any workspace where the default currency is non-USD.
4. Go to Reimbursements.

## Expected Result:
App does not crash.

## Actual Result:
App crashes when tapping Reimbursements

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c2be3a6f-cefa-45c5-81f1-ad267f2fb0fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by roryabraham** [comment]
I'm going to be afk for the rest of the day today and won't be able to address this hourly

**Comment by mountiny** [comment]
fixed in 54-1

https://github.com/Expensify/App/assets/36083550/206c3963-7807-4af8-9bcc-294cb1f40e20
