### ISSUE TITLE
Distance rates - Saving rate by `enter` key redirects to the previous page after rate is saved

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38519]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition: User is an admin of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Distance rates.
4. Click Add rate.
5. Enter any amount.
6. Hit "Tab" to highlight the "Enter" key, then hit "Enter" on keyboard

## Expected Result:
User expects the expense to be saved and stay on the same "Distance Rates" page as that is what happens when the user CLICKS on the "Enter" key with the mouse

## Actual Result:
The Distance rate is saved by the "Enter' key, however the user is redirected to the incorrect "taxes" page (In this case it was the previous page accessed by the user) while the "Distance rates" page continues being highlighted.
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/115595f3-1967-4d17-b3a5-213ab55cd0f0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@tylerkaraszewski  FYI, I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by luacmartins** [comment]
This is NAB since it's not available to users. We can tackle it as a follow up to the distance rates PR cc @MrMuzyk
