### ISSUE TITLE
[Simplified Collect][Taxes] Prevent creating taxes with empty names

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#38514]
## Problem
Coming from [this thread](https://expensify.slack.com/archives/C07J32337/p1710790663425949), the API is throwing an error when users try to create a tax without a name.

## Why is this important
Prevents errors

## Solution
Validate the tax name before sending it to the API and check it in the API

**Comment by trjExpensify** [comment]
Any movement here, guys?

**Comment by luacmartins** [comment]
@marcaaron worked on [this PR](https://github.com/Expensify/App/issues/38514) that's already merged and deployed. We also added validation when creating a new tax [here](https://github.com/Expensify/App/blob/005dba5cdce40a7164ce51cdd262704651f9de58/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L58). So I think we can close this issue!
