### ISSUE TITLE
[Simplified Collect][Taxes] It crashes if you try to add a custom name without having any taxes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38528]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/38373
## Action Performed:
Precondition: With a new expensifail account, create a Collect workspace with workspace chat enabled
1. Navigate to Workspace settings - Taxes - Settings - Custom tax name
2. Type in any name
3. Click on the "Save" button

## Expected Result:
It shouldn't crash

## Actual Result:
It crashes if you try to add a custom name without having any taxes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 
</details> 

https://github.com/Expensify/App/assets/78819774/4ba165f2-b138-41c8-9bad-f136af91107b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jasperhuangg  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
@luacmartins I beelive this should be fixed with adding the default taxes optimistically

**Comment by mountiny** [comment]
I assume we have to fix the crash though

**Comment by luacmartins** [comment]
I don't think this is a blocker since users don't have access to these pages yet. cc @kosmydel @filip-solecki

**Comment by filip-solecki** [comment]
I think it will not happen after merging this [PR](https://github.com/Expensify/App/pull/38375) since there always have to be at least one tax rate

**Comment by kosmydel** [comment]
> I think it will not happen after merging this [PR](https://github.com/Expensify/App/pull/38375) since there always have to be at least one tax rate

We should fix it anyway, just in case the user somehow gets into this state.

**Comment by filip-solecki** [comment]
Ok, I will handle it @luacmartins

**Comment by DylanDylann** [comment]
@filip-solecki I think we should hold this issue until [the PR](https://github.com/Expensify/App/pull/38375) is merged

**Comment by filip-solecki** [comment]
It should not happen after merging mentioned PR but as we mentioned above fixing it in this way helps to avoid crashing app in some edge cases when user somehow gets into this state

**Comment by DylanDylann** [comment]
yeah, but your change still causes some confusion to users (The custom name disappears after entering)
What do you think about displaying the not found page without default tax?

cc @luacmartins

**Comment by luacmartins** [comment]
I think the fix is fine given that the state shouldn't happen after we have default taxes. I think it's better to not crash the App then the user being confused because the tax they just created disappered.

**Comment by trjExpensify** [comment]
As https://github.com/Expensify/App/pull/38375 has merged, should we close this now?

**Comment by luacmartins** [comment]
Yes, we can close this
