### ISSUE TITLE
Workspace - Enabled features are disabled until you click on "More features" tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38529]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: With a new expensifail account, create two Collect workspaces with workspace chat enabled. Rename one of them.
1. Enable Taxes for both of the workspaces at Workspace settings - More features
2. Log out
3. Log in with the same account
4. Navigate to the settings page of both of the workspaces

## Expected Result:
The features should be enabled from the start

## Actual Result:
Enabled features are disabled until you click on "More features" tab. Sometimes only one of the workspace is affected, sometimes both

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/610a562e-e508-4e10-aef3-4a5b60b6a381

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
This seems to be just a display issue -- the tax functionality is still present on the workspace, the toggles just go from disabled > enabled when revealing them in the menu. I think this is something we may tackle later during polish but will opt to close this for now.
