### ISSUE TITLE
[HOLD for payment 2024-03-29] IOS - Workspace - Offline indicator in workspace page overlaps with navigation bar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38520]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Profile > Workspaces.
3. Select any workspace.
4. Go offline.

## Expected Result:
Offline indicator will not overlap with navigation bar.

## Actual Result:
Offline indicator overlaps with navigation bar.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/a8de735b-d47e-439d-9e10-bf827846ebf4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by kbecciv** [comment]
@abekkala I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by WojtekBoman** [comment]
@mkhutornyi Because it's follow-up to ideal-nav-v2, I can look into it :) As far as I know, removing style prop from the ScreenWrapper in `WorkspaceInitialPage.tsx` should solve this issue. I'll prepare a PR :)

**Comment by situchan** [comment]
Please assign me here

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAR 29

- Fix: @WojtekBoman SWM - no payment required 
- PR Review: @situchan [$500, if no regressions] [Offer ](https://www.upwork.com/nx/wm/offer/101526162)

**Comment by abekkala** [comment]
@slafortune will be handling payment for me while I'm ooo

**Comment by slafortune** [comment]
Paid
