### ISSUE TITLE
[HOLD for payment 2024-04-17] [$250] [Simplified Collect][Taxes] Incorrect numpad horizontal padding on the native and mweb devices

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#38523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Have Collect workspace supported in NewDot
2. Go to Settings
3. More feature
4. Turn on Tax feature
5. Go to taxes
6. Add new tax rate
7. Add value

## Expected Result:
Describe what you think should've happened

The numpad should have same styles as amount numpad in money request flow or new distance rate flow

## Actual Result:
Describe what actually happened

the numpad has horizontal padding

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![IMG_A4AE9DE5D565-1](https://github.com/Expensify/App/assets/36083550/87e8e50a-57dd-4d0b-bb53-2379c9d8d923)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a628ba28191722d3</li>
        <li>Upwork Job ID: 1769837087142653952</li>
        <li>Last Price Increase: 2024-03-18</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by mountiny** [comment]
@Krishna2323 thanks, thats looking good, can you please raise a PR and for the screenshots, can you always include screenshot of the tax screen next to the money request flow on the same platform to compare the styles and verify its the same?

**Comment by abdulrahuman5196** [comment]
Reviewing now

**Comment by trjExpensify** [comment]
PR hit staging earlier today.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @Krishna2323 $250 (paid in Upwork)
- Contributor+ @abdulrahuman5196 $250 (paid in Upwork)
