### ISSUE TITLE
[HOLD for payment 2024-04-09] [TS migration] Migrate remaining GitHub actions to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38537]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

| Path | Dependencies |
|---|---|
| [.github/actions/javascript/getGraphiteString/getGraphiteString.js](https://github.com/Expensify/App/blob/main/.github/actions/javascript/getGraphiteString/getGraphiteString.js) | 3 |
| [.github/actions/javascript/getArtifactInfo/getArtifactInfo.js](https://github.com/Expensify/App/blob/main/.github/actions/javascript/getArtifactInfo/getArtifactInfo.js) | 3 |

**Comment by fabioh8010** [comment]
This issue is internal and will be carried out by the TS team.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by JKobrynski** [comment]
The [PR](https://github.com/Expensify/App/pull/38576) is ready for review!
