### ISSUE TITLE
[HOLD for payment 2024-04-05] [TS migration] Migrate remaining Mock and Script files to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38535]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

| Path | Dependencies |
|---|---|
| [scripts/release-profile.js](https://github.com/Expensify/App/blob/main/scripts/release-profile.js) | 2 |
| [__mocks__/react-native-document-picker.js](https://github.com/Expensify/App/blob/main/__mocks__/react-native-document-picker.js) | 0 |
| [__mocks__/@react-native-clipboard/clipboard.js](https://github.com/Expensify/App/blob/main/__mocks__/@react-native-clipboard/clipboard.js) | 1 |

**Comment by fabioh8010** [comment]
This issue is internal and will be carried out by the TS team.

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by joekaufmanexpensify** [comment]
Checklist not needed.
