### ISSUE TITLE
[TS migration] Migrate remaining Test files to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38536]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

| Path | Dependencies |
|---|---|
| [tests/unit/searchCountryOptionsTest.js](https://github.com/Expensify/App/blob/main/tests/unit/searchCountryOptionsTest.js) | 1 |
| [tests/unit/LocaleCompareTest.js](https://github.com/Expensify/App/blob/main/tests/unit/LocaleCompareTest.js) | 5 |
| [tests/e2e/nativeCommands/index.js](https://github.com/Expensify/App/blob/main/tests/e2e/nativeCommands/index.js) | 3 |

**Comment by fabioh8010** [comment]
This issue is internal and will be carried out by the TS team.

**Comment by pasyukevich** [comment]
Hi,
I'm Eugene from Callstack - an expert contributor group
I’d like to work on this issue
