### ISSUE TITLE
CRITICAL: [Actionable Whispers] [$1250] Launch basic actionable whisper foundation

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#38533]
We're adding the 'Track Expense' action in this [PR](https://github.com/Expensify/App/pull/37282). After tracking an expense to your selfDM, there will be a whisper action that provides different options you can take 

![image](https://github.com/Expensify/App/assets/30609178/8d87e561-87cb-4a1d-a3e4-527a5bb36cdb)

Currently after each tracked transaction, there is another reportAction added which is called `ACTIONABLETRACKEXPENSEWHISPER`. This will be the actionable whisper. 

We already have a similar actionable whisper for inviting people [here](https://github.com/Expensify/App/blob/69e621b4a8b00a819ac6a840b83ca800c1aa5a4a/src/pages/home/report/ReportActionItem.tsx#L372-L399)
<img width="1149" alt="Screenshot 2024-03-18 at 3 05 11 PM" src="https://github.com/Expensify/App/assets/30609178/5855a3db-93de-4f48-a4e4-9f34b679b8bc">

There are 4 actions that can be taken

**Request someone to pay it** ([Doc](https://docs.google.com/document/d/1gACVXuJS2ojNV_hwQRBLYFK_dR7vXSNlXfTnMOsdd_w/edit#bookmark=id.n2vaif1mdehp))

This will open up straight to the participant selector for the existing transaction. However, in this case it will move the transaction once the request is created as opposed to creating a new one.

![image](https://github.com/Expensify/App/assets/30609178/3097c19f-d97b-468e-b67b-cc2480c18ebe)

API command: 'ConvertTrackedExpenseToRequest'
Parameters:
- authToken
- payerAccountID
- iouReportID
- chatReportID
- transactionID
- reportActionID
- createdChatReportActionID
- createdIOUReportActionID
- reportPreviewReportActionID

**Categorize it** ([Doc](https://docs.google.com/document/d/1gACVXuJS2ojNV_hwQRBLYFK_dR7vXSNlXfTnMOsdd_w/edit#bookmark=id.v32o1plr0ysn))
This creates a workspace (if necessary), then moves it to the open expense report on the workspace chat, and opens the category editor.

![image](https://github.com/Expensify/App/assets/30609178/49f244ea-f7c7-4ce3-86b1-ea57eb6355c2)

API command: CategorizeTrackedExpense
- authToken
- policyID
- transactionID
- reportID
- reportActionID
- modifiedExpenseReportActionID
- announceChatReportID
- announceCreatedReportActionID
- adminsChatReportID
- adminsCreatedReportActionID
- expenseChatReportID
- expenseCreatedReportActionID

**Share it with my accountant** ([Doc](https://docs.google.com/document/d/1gACVXuJS2ojNV_hwQRBLYFK_dR7vXSNlXfTnMOsdd_w/edit#bookmark=id.v32o1plr0ysn))
This creates a workspace (if necessary), moves it to a report on the workspace chat, and opens the invite flow.

![image](https://github.com/Expensify/App/assets/30609178/d679abc6-d2ac-4def-80a4-b16ebbd6ef01)

API command: ShareTrackedExpense
- authToken
- policyID
- transactionID
- reportID
- reportActionID
- modifiedExpenseReportActionID
- announceChatReportID
- announceCreatedReportActionID
- adminsChatReportID
- adminsCreatedReportActionID
- expenseChatReportID
- expenseCreatedReportActionID

**Nothing for now**

Hides the actionable whisper

API command: DismissActionableWhisper
- authToken
- reportActionID

**Note:** To get started, you will need to branch off this existing [PR](https://github.com/Expensify/App/pull/37282). We haven't done full flow testing of the API commands, so there may be some additional BE changes that are required that you might find through working on this PR that we can work on in parallel. 

We're also trying to launch this ASAP. Please do *NOT* pick this up unless you can spend your full attention on this

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015906865d86966bf9</li>
        <li>Upwork Job ID: 1770146045833195520</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by dannymcclain** [comment]
@ishpaul777 is this what you're looking for?
![CleanShot 2024-03-20 at 09 09 32@2x](https://github.com/Expensify/App/assets/7516624/07350256-d668-4384-8361-53889a196f1b)

In Figma, we're using our medium (default) size buttons—they have `16px` of left/right padding and a fixed height of `40px`.

**Comment by JmillsExpensify** [comment]
Actively working through issue.

**Comment by thienlnam** [comment]
Could you please add what you think is a fair amount and reasoning for it?

**Comment by thienlnam** [comment]
That seems fair to me 👍

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: @ishpaul777 $1,250
 - Contributor+: @shubham1206agra $1,250

**Comment by JmillsExpensify** [comment]
Offers sent out via Upwork. @shubham1206agra given that this is a new feature, please suggest a set of regression tests to ensure we keep quality high and are testing this for every QA run.

**Comment by JmillsExpensify** [comment]
@thienlnam Have all the regression tests in the Track Expense doc been added to TestRail yet?

**Comment by JmillsExpensify** [comment]
All Contributors paid out, just wanted to confirm on regression tests for Track Expense before closing this out.

**Comment by thienlnam** [comment]
> @thienlnam Have all the regression tests in the Track Expense doc been added to TestRail yet?

Yeah, they're being added https://github.com/Expensify/Expensify/issues/399663
