### ISSUE TITLE
[HOLD for payment 2024-06-11] [$500] Auto complete emojis does not pop up if a letter with tilde in spanish

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710785038489889

## Action Performed:
1. Go to staging.expensify.com and sign in 
2. Switch language to Spanish
3. Open any chat
4. Type any emoji name which has tilde like (:corazón:) in the composer or search for emoji in the emoji picker

## Expected Result:
Should auto complete in composer field or show the results in the emoji picker.

## Actual Result:
Does not auto complete in composer and no results found in emoji picker. Not treating `o` and `ó` as same

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-03-18 at 8 02 16 PM](https://github.com/Expensify/App/assets/38435837/2b83599a-337f-4d91-b8a7-27c430116299)

https://github.com/Expensify/App/assets/38435837/bcfdfc7a-7f6f-43b4-9c91-c89d06fd8268

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01191fbf64d1245a9f</li>
        <li>Upwork Job ID: 1771230550663888896</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by iwiznia** [comment]
Not sure why this was not added from my report: 
>  should probably be matching using localeCompare or Intl.Collator to treat o and ó the same (and other accented letters in all languages that have them). 

I think we should do that. We should *not* be implementing our own collator, especially since this needs to support internationalization to any language.

**Comment by johncschuster** [comment]
@thesahindia can you review @tienifr's updated proposal?

**Comment by johncschuster** [comment]
Bumped in Slack!

**Comment by iwiznia** [comment]
> I think we cannot use localeCompare here given the current implementation of Trie and localeCompare only shows us whether two strings are equal but sometimes we want to search for a substring.

@tienifr can you explain this in more detail please?

**Comment by iwiznia** [comment]
Got it, thanks for the explanation! And sorry that I missed that message

**Comment by johncschuster** [comment]
# Payment Summary:
Contributor: @tienifr - $500 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/101721390)
Contributor+: @thesahindia - $500 - paid via Manual request

**Comment by johncschuster** [comment]
# Payment Summary:
Contributor: @tienifr - $500 - paid via [Upwork](https://www.upwork.com/nx/wm/offer/101721390)
Contributor+: @thesahindia - $500 - paid via Manual request

**Comment by johncschuster** [comment]
What do you think of the QA test steps above, @iwiznia?

**Comment by iwiznia** [comment]
They look good, but it's missing the good case: search for `corazo` and check it shows the ❤️ emoji

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia
