### ISSUE TITLE
Scan - Detach receipt message mentions (none) as merchant for scan request with merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38541]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a scan request
4. Go to request details page
5. Manually enter amount and merchant
6. Click on the receipt > 3-dot menu > Delete receipt
7. Delete the receipt
8. Return to expense report

## Expected Result:
The detach receipt message should mention the correct merchant that is entered in Step 5

## Actual Result:
The detach receipt message mentions (none) as merchant instead of the entered merchant

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/47c164f0-81d2-4903-81fe-49d9e79c4c0b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@NikkiWines  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by NikkiWines** [comment]
Definitely comes from that PR, but I don't think this is technically a blocker. Pretty sure it's a byproduct of surfacing these Expensify Classic report actions on New Expensify. I see the same behavior if I repeat the test on Expensify Classic.

cc: @Beamanator (since you were involved in that linked PR) looks like we might have a bug in some of the Web report action code that's not retaining the merchant [here](https://github.com/Expensify/Web-Expensify/blob/ae3c08686fb72664fe69356ba9dacc6313e4e756/lib/Report/Action/ManagerDetachReceipt.php#L10)

**Comment by twisterdotcom** [comment]
I agree this isn't a blocker, especially if it works the same on oldDot. Something for us to fix when we move these messages to native newDot actions. cc @dylanexpensify.

**Comment by dylanexpensify** [comment]
nice, agree!

**Comment by NikkiWines** [comment]
Cool, sounds like we don't have anything actionable here for a bit. Going to put this on hold and unassign myself

**Comment by dylanexpensify** [comment]
same!

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
Same

**Comment by dylanexpensify** [comment]
No update!

**Comment by dylanexpensify** [comment]
Off hold now, cc @NikkiWines !

**Comment by NikkiWines** [comment]
Let's get this retested to confirm the bug is still occurring since it's been a while 🙇

**Comment by dylanexpensify** [comment]
FAIR! :D

**Comment by dylanexpensify** [comment]
Could not repro
