### ISSUE TITLE
Reports out of sync when clicking into workspace chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38544]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710772719870009

## Action Performed:
1. Submit a expense report via workspace chat from account B to account A with whom lots of report history
2. Sign in as user B
3. Click on the row with green dot for user B

## Expected Result:
Any previously paid reports should show correctly as paid

## Actual Result:
 Any previously paid reports incorrectly show as unpaid until you tap into them

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-03-18 at 08 39 27@2x](https://github.com/Expensify/App/assets/38435837/4d9ece89-eb3e-483b-9ebb-bcde92e6df4f)

![CleanShot 2024-03-18 at 08 38 51@2x](https://github.com/Expensify/App/assets/38435837/f465f4c8-e099-4f50-9a7d-970a6c804ac0)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
I can't reproduce this.
