### ISSUE TITLE
[HOLD for payment 2024-03-29] [Wave Collect] [$250] Taxes and Tags pages missing 12px space below page header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38547]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710778990402689

## Action Performed:
1. Open staging.new.expensify.com
2. Go to Workspace Settings 
3. navigate to both Taxes and Tags

## Expected Result: 
Each page should have 12px of padding below the page header and above the page content.

## Actual Result: 
These two pages are missing the 12px gap.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-03-18 at 12 23 45@2x](https://github.com/Expensify/App/assets/38435837/2a12a53b-0891-4ffe-98d6-1ac4772b0310)

![CleanShot 2024-03-18 at 12 21 57@2x](https://github.com/Expensify/App/assets/38435837/a31b02de-c31c-44d2-ab4c-b76a1656a75d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3fba734f748c3c2</li>
        <li>Upwork Job ID: 1769872792516067328</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by mountiny** [comment]
Making a PR for this

**Comment by mountiny** [comment]
I knew you were 😂

**Comment by mountiny** [comment]
wtf 😂 even github does not match the speed of the contributor proposal

**Comment by mountiny** [comment]
$250 to @getusha for their testing and reviewer checklist on the PR

**Comment by mountiny** [comment]
I believe we wont need a regression test for this one, its a minor design issue which should be covered by exploratory testing or I am sure Shawn will post about it in expensify-bugs if this comes again :D

**Comment by shawnborton** [comment]
🦅 👁️

**Comment by mountiny** [comment]
@getusha have you received the payment here?

**Comment by anmurali** [comment]
Paid.
