### ISSUE TITLE
[HOLD for payment 2024-04-05] [HOLD App#38428] [$250] [Workflows] - Page loads infinitely after toggling on Make or track payments

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38566]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an admin of Collect workspace.
- The Collect workspace does not have bank acount set up.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Workflows.
4. Toggle on Make or track payments.

## Expected Result:
Workflow page will not load infinitely.

## Actual Result:
Workflow page loads infinitely.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/68cb268f-eb21-4cc2-98bc-876baee12f1b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c328daffa3085f2a</li>
        <li>Upwork Job ID: 1770034165546430464</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@muttmuure I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #wave-control.

**Comment by mountiny** [comment]
This page is part of the collect workspace settings customers do not have access to yet so not a blocker

**Comment by mountiny** [comment]
@ishpaul777 going to work on resolving this one as he worked on similar pages and we want to fix this asap

**Comment by jjcoffee** [comment]
We're handling this as part of https://github.com/Expensify/App/pull/38428 (follow-up PR for Workflow payer page implementation).

**Comment by mountiny** [comment]
Putting on hold for the linked PR and asked in the PR for update

**Comment by trjExpensify** [comment]
The linked PR has merged. Can we close this?

**Comment by mountiny** [comment]
yeah payments are handled on the original issue that fixed this too https://github.com/Expensify/App/issues/38153
