### ISSUE TITLE
[HOLD for payment 2024-07-24] [$500] Android - Task - Tapping assignee and quickly tapping mark as complete directed to hmm not here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38577]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab --- assign task
3. Enter title
4. Tap next
5. Select share somewhere
6. Confirm task
7. Open task to open task details page
8. Tap assignee and quickly tap mark as complete button on header

## Expected Result:
When user taps assignee and quickly taps mark as complete button on header, user must not be directed to hhm not here page.

## Actual Result:
When user taps assignee and quickly taps mark as complete button on header, user directed to hhm not here page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c4cabeca-6e13-48e8-9aac-ea44c60071c3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efbf5aa31beec5a5</li>
        <li>Upwork Job ID: 1772302127195226112</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by kbecciv** [comment]
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by adelekennedy** [comment]
task related

**Comment by mananjadhav** [comment]
> it should not be possible to click on `Assignee` and mark task as completed at the same time. We can use `singleExecution` to limit this, this is an approach widely used in the app.

🎀 👀 🎀 confirming with engineer if we are okay with the blocking behavior.

**Comment by rlinoz** [comment]
I think we should be good with the blocking behavior

**Comment by mananjadhav** [comment]
Cool. Then @tienifr’s proposal looks good to me.

**Comment by mananjadhav** [comment]
@tienifr this was reverted.

**Comment by mananjadhav** [comment]
@tienifr Any ETA on the PR?

**Comment by mananjadhav** [comment]
@tienifr Quick bump

**Comment by mananjadhav** [comment]
@tienifr Any updates on this one?

**Comment by mananjadhav** [comment]
@tienifr Can you please share updates on this one?

**Comment by mananjadhav** [comment]
@rlinoz Are we okay to ahead without the singleExecution on mWeb?

**Comment by mananjadhav** [comment]
@rlinoz Are we okay to ahead without the singleExecution on mWeb? or is this a big enough issue to be worked on? Should we :donothing: here?

**Comment by mananjadhav** [comment]
Quick bump @rlinoz

**Comment by rlinoz** [comment]
Sorry for the delayed response, I took this to slack and I think we should try to fix it in every platform to keep a good experience everywhere, we can open it up for new proposals if everyone is ok with it @mananjadhav @tienifr

**Comment by mananjadhav** [comment]
@tienifr following up on this, otherwise let's open this for new proposals. It's been open for more than a month now.

**Comment by mananjadhav** [comment]
@tienifr Waiting for an update.

**Comment by rlinoz** [comment]
PR is merged awaiting deploy.

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $500 @tienifr (Newdot)
- [ ] Contributor+: $500 @mananjadhav (NewDot)

**Comment by adelekennedy** [comment]
@mananjadhav I think the final step here is the checklist?

**Comment by adelekennedy** [comment]
bump @mananjadhav

**Comment by mananjadhav** [comment]
@adelekennedy @rlinoz There was a [regression](https://github.com/Expensify/App/issues/38577#issuecomment-2070843696) on this task. But I would like to request if we can pay the full price here. This was a bit weird case, where we use useSingleExecution and couldn't get it working on mobile web. Then @tienifr found an alternative way of solving this.

I don't have an offending PR for this one as this was a part of the navigation issue. I couldn't pinpoint if this came from a specific PR.  I also feel we should add a regression test to this one.


1. Open a task report
2. Tap Assignee then quickly tap Mark as complete.
3. Verify that user is navigated to Assignee page only and task is not marked as completed.
4. Tap Description then quickly tap Mark as complete.
5. Verify that user is navigated to Description page only and task is not marked as completed.
6. Verify during the navigation you don't see `Not found` page.

**Comment by mananjadhav** [comment]
@adelekennedy Did you get a chance to look at my previous comment?

**Comment by adelekennedy** [comment]
hey! I'm back from ooo - that reasoning makes sense to me, I think we should move forward with the full amount.

**Comment by adelekennedy** [comment]
https://github.com/Expensify/Expensify/issues/416801

**Comment by mananjadhav** [comment]
Thanks @adelekennedy. Appreciate it.

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav

**Comment by JmillsExpensify** [comment]
$500 approved for @tienifr
