### ISSUE TITLE
Android - Distance - Location access not asking every time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.54.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: location on, app location access set to ask everytime
1. Launch app
2. Tap fab -- request money -- Distance
3. Note location access permission asked
4. Select only this time
5. Complete the distance request
6. Kill the app
7. Open the app again
8. Tap fab -- request money -- Distance
9. Note map loaded and no location access permission asked

## Expected Result:
When location access is set ever time, after completing a distance request if user kills app and open again to make distance request,permission for location access must be asked.

## Actual Result:
When location access is set ever time, after completing a distance request if user kills app and open again to make distance request,permission for location access is not asked.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/20fe600b-527b-4865-b672-15de3196cfae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect RELEASE 1

**Comment by arosiclair** [comment]
Working on reproducing...

**Comment by arosiclair** [comment]
I reproduced:

https://github.com/Expensify/App/assets/6833644/0b4b15f1-3816-4c15-9826-3ae2697872dd

It seems like we are saving your previously recorded location since selecting "Your location" as an option uses the location from the previous request without re-prompting for location permission.

**Comment by arosiclair** [comment]
Alright I also reproduced on prod **v1.4.53-2** so this is not a blocker

**Comment by ahmedGaber93** [comment]
> Note map loaded and no location access permission asked

But if you try to select a point with current location, you will see you still have the permission, also go to settings and check permission, you will see you still have the permission, but if you wait about 15 min then open the app again, you will see the permission is revoked. 

I think this the behavior in android, but unfortunately the [documentation](https://developer.android.com/training/permissions/requesting#one-time) is very unclear as to exactly when these permissions get revoked.

**Comment by twisterdotcom** [comment]
I reproduced this but I think we are just not really giving the device time to revoke the permissions. It asks again if you switch to another app between opening New Expensify, but if you don't, it doesn't. I think this is totally fine.

https://drive.google.com/file/d/13vQA67TI3zHID1sTbnG3HmEIwueBQzsc/view?usp=sharing
