### ISSUE TITLE
IOS - Workspace - There is no error message for an incorrect account number

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38575]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36495
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Navigate to the Workspace settings - Reimbursements - Connect bank account
4. Tap on the "Connect manually" button
5. Input "011401533" as Routing number
6. Input "1111" as Account number
7. Tap on the "Next" button
8. Tap on the "Confirm" button

## Expected Result:
There should be a message that the entered Account number data is incorrect.

## Actual Result:
There is no error message for an incorrect account number. First, I'm able go move forward with an invalid number, and I'm taken back to the "Manually add" step after tapping "Confirm". There I can see a "fix errors" error message but it's not specific. The page just refreshes if I tap on it.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/67b0f4a5-0e45-4c4a-bbd6-9ced176dc7ea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Piyush-Desai** [comment]
I am facing some error while setup the code into my machine. @kbecciv can you guide me?

**Comment by kbecciv** [comment]
@Piyush-Desai Sorry, I cannot help you with that!

**Comment by MitchExpensify** [comment]
This seems fixed to me on v1.4.56-5

<img width="370" alt="image" src="https://github.com/Expensify/App/assets/36425901/332688dc-9814-4caf-b2a1-1c6baae48f8c">
