### ISSUE TITLE
User is not navigated to Concierge chat after changing their role to Employee

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #35923
**Version Number:** 1.4.54-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Pre-condition: User submitted an expense as an employee to a collect workspace and invited another user as an auditor.

1. In ND, log in as the auditor, go to an expense report submitted by the employee
2. In OD, log in as the admin, change the role of the auditor to employee
3. In ND, verify that app does not crash
4. In OD, as the admin, change the role of the employee to auditor
5. In ND, go to that workspace's policy expense chat
6. In OD, as the admin, change the role of the auditor to employee
## Expected Result:
User is navigated to Concierge chat

## Actual Result:
User is navigated to Concierge chat only after refreshing the page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/9b2d212c-0325-48ae-bdb3-71740fa91f12

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@lschurr FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by lschurr** [comment]
Sounds like this isn't reproducible. Going to close.
