### ISSUE TITLE
[HOLD for payment 2024-03-29] [HOLD for payment 2024-03-26] [$250] Desktop/Web - User Status - Unable to enter a custom time for user status using the keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38595]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4435149
**Email or phone of affected tester (no customers):** applausetester+031824dr001@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com with Safari/Chrome or open Desktop App
2. Login with any account
3. Tap to User > Settings
4. Tap to Status icon and select any emoji and Message
5. Tap to "Clear After"
6. Select "Custom"
7. Select "Time"
8. Enter new custom time using the keyboard

## Expected Result:
User can enter new custom time for user status using the keyboard

## Actual Result:
Unable to enter a custom time for user status using the keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4d64a75e-adfc-4d5c-832f-b28137c15285

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@youssef-lr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by youssef-lr** [comment]
I think we need to find the offending PR first. I'm on it.

**Comment by youssef-lr** [comment]
This is coming from this [PR](https://github.com/Expensify/App/pull/37967/files#diff-32b32e405c55c94c11d9956154b89d1d0bc2e4f80448214f8cbab4bce81a3dddR61) as it started passing all props to `AmountTextInput` when in the past we weren't actually passing `maxLength` to `AmountTextInput`. @tienifr looks good to me.

**Comment by youssef-lr** [comment]
@tienifr are you available to work on the PR now?

**Comment by youssef-lr** [comment]
@tienifr I'll be working on the PR myself to unblock the deploy, you'll still be eligible for the payment here. Thank you!

**Comment by youssef-lr** [comment]
@puneetlath can we issue a $250 payment to @tienifr please?

**Comment by puneetlath** [comment]
Offer is here: https://www.upwork.com/nx/wm/offer/101723112

@tienifr please ping me on the issue when you've accepted.

**Comment by puneetlath** [comment]
Paid. Thanks everyone!
