### ISSUE TITLE
 Workspace - Deleted bank account appears if you add a new after disconnecting

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38598]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54.0
**Reproducible in staging?:** y
**Reproducible in production?:** can not check prod
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36495
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Navigate to the Workspace settings - Reimbursements - Connect bank account
4. Fully add a Plaid Chase bank, stop at the "You're all set" step
5. Tap on the "Disconnect bank account" button
6. Start adding Plaid Regions bank

## Expected Result:
I should be able to add a new bank account

## Actual Result:
Deleted bank account appears after the "Choose an account" step, if you add a new after disconnecting.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e91aed74-74cb-4d30-8557-479ee9731b6a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by amyevans** [comment]
Looks like it's coming from https://github.com/Expensify/App/pull/36495, @mateuuszzzzz could you take a look please? cc @mountiny @aimane-chnaif

**Comment by amyevans** [comment]
Okay yeah good call, thanks. The same is experienced with the PR reverted locally:

https://github.com/Expensify/App/assets/7277067/5a617259-7297-426d-b714-4543f05a1c09

I believe it's just a limitation of our dev/staging credentials setup so I'm going to close this out.
