### ISSUE TITLE
Chat - Video recorded & uploaded is shown in chat preview in horizontal position

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38591]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1. 4. 54
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4434267
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Tap plus icon
4. Use cam recorder and record a video and upload it
5. Note in chat preview video is shown in horizontal position
6. Now compress the same video using any video compressor
7. Upload the same video file as attachment
8. Now note the video is shown in vertical position

## Expected Result:
If record video in vertical position, the uploaded attachment in chat preview must be shown in vertical position

## Actual Result:
If user record video& upload, it's shown in chat preview in horizontal position but same video if compressed and uploaded, then it is shown in vertical position in preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/34434f6e-3a15-4c44-97f9-68b96687943d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f52245343f6b3996</li>
        <li>Upwork Job ID: 1772280650529857536</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
@lanitochka17 does this only happen on mobile web? On all other platforms it works normally?

**Comment by puneetlath** [comment]
cc @francoisl in case you have context.

**Comment by francoisl** [comment]
Hm yes this looks like a backend issue.

@dragnoir were you able to reproduce the issue by uploading a video attachment from web? Any chance you could share that video please? I tried uploading one but the dimensions were computed correctly, I wonder if it has to do with the video file itself. 

Also on Android I can't record a video from the attachment modal, the app directly opens the camera in photo mode, and I can't switch to video.

**Comment by puneetlath** [comment]
@francoisl any thoughts? Will you take this on?

**Comment by puneetlath** [comment]
Removing @situchan since this'll be a back-end fix.

**Comment by francoisl** [comment]
> any thoughts?

We determine the video's dimensions with [this](https://github.com/Expensify/Salt/blob/905dd41105a80753e4566d787d909836ae16e526/pdf/files/processVideoAttachment.sh#L39), so I'd imagine that's where the issue lies.

> Will you take this on?

It's unlikely I can take this on this week, and I'm OOO next week 😬

**Comment by puneetlath** [comment]
My current thinking is that this is enough of an edge-case that it's not worth spending internal time on. Comment or reopen if you disagree!
