### ISSUE TITLE
After marking expense as non reimbursabl in OD, it updates to 'spent' in ND

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38603]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exp around https://expensify.testrail.io/index.php?/tests/view/4418507
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Employee - OldDot
1. Login to OldDot with the employee account
2. Navigate to workspaces and set the collect policy to default if not already set
3. Navigate to reports
4. Create a report
5. Click on add expense
6. Fill the field with any info and unmark the Reimbursable checkbox, and save the expense
Employee - NewDot
1. Log in as the employee in NewDot
2. Navigate to the workspace chat

## Expected Result:
The expense that is marked as non-reimbursable is displayed in the report

## Actual Result:
The report is marked 'spent', expense details don't specify it's non-reimbursable.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6412223_1710334325561!ODnonR](https://github.com/Expensify/App/assets/38435837/6e86e6d2-bf87-4561-962d-4b7106ad723b)

![Bug6412223_1710334325565!NDspent](https://github.com/Expensify/App/assets/38435837/badd7ad3-2181-4b36-94d4-4d8846ed82fe)

https://github.com/Expensify/App/assets/38435837/8dd906ad-18d0-47de-89df-13a2a590fc2c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@anmurali FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this might be related to #wave-collect - Release 1

**Comment by anmurali** [comment]
Showing non reimbursable expense as “spent” in ND is the design. So, not a bug.
