### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [Payment card / Subscription] Implement “Change billing currency” action

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38619]
This covers this section of the doc  @fabioh8010

> Mode: Accessible only on desktop and web
> Onyx keys: ONYXKEYS.COLLECTION.POLICY, ONYXKEYS.FUND_LIST
> API commands: UpdateBillingCardCurrency
> Component path: src/settings/subscription/PaymentCard/ChangeBillingCurrency.tsx
> 
> <img width="299" alt="image" src="https://github.com/Expensify/App/assets/36425901/af66955d-809b-426b-a229-9b320173b954">
> 
> **Create an empty screen with a route**
> 
> **Route for  page** - /settings/subscription/change-billing-currency
> Before building the actual screen content we need to create an empty ChangeBillingCurrency screen and add it to the navigation.
> The screen has to be defined in the SettingsModalStackNavigator and SCREENS.RIGHT_MODAL.SETTINGS and it should be available only for desktop and web.
> 
> **Implement Form wrapper**
> 
> We will define <HeaderWithBackButton/> and  <FormProvider /> with the provided Submit button text and handler.
> 
> To implement the currency selector list modal we will use decoupled before  <CurrencyModal/> and <CurrencyButton /> from the WorkspaceOwnerPaymentCardForm to reuse it here. 
> 
> **Note section**
> <img width="527" alt="image" src="https://github.com/Expensify/App/assets/36425901/2cb9f143-7a87-4023-90bd-7032f977cc5d">
> 
> 
> This is going to be a basic <Text /> component with <TextLink /> for the link([pricing page](https://www.expensify.com/pricing?)).
> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011778e5bbd693de04</li>
        <li>Upwork Job ID: 1770152613632573440</li>
        <li>Last Price Increase: 2024-07-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by MitchExpensify** [comment]
This is not ready for proposals @ShridharGoel, we'll apply the help wanted label again when it is - Thanks!

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.

**Comment by pasyukevich** [comment]
@MitchExpensify The Link in the doc was not proper - the proper task for this part of the work - https://github.com/Expensify/App/issues/38630

This issue is about the gluing of the  "Change billing currency" screen with "Your card section"

**Comment by narefyev91** [comment]
Today updates - start working on implementation for re-usable form (same will be for this one https://github.com/Expensify/App/issues/38630)
WIP

**Comment by narefyev91** [comment]
Today report - build re-usable form to use in both places for change currency. Tomorrow plan to add latest code peaces and open a PR for a review

**Comment by zanyrenney** [comment]
@narefyev91 does not require payment (Contractor)
@situchan requires payment (Needs manual offer from BZ) ~I have sent you an job offer. please accept!

**Comment by zanyrenney** [comment]
@situchan please also propose the regression test!

**Comment by blimpich** [comment]
No regression test proposal needed I think. This is a new feature and we've written a suite of regression tests to be used by applause once the full project/feature is ready.

**Comment by situchan** [comment]
@zanyrenney I accepted invite.

**Comment by zanyrenney** [comment]
waiting on @situchan accepting offer

**Comment by zanyrenney** [comment]
**payment summary**

Contributor: @narefyev91 is from an agency-contributor and not due payment
ROLE: @situchan paid $(250) via Upwork - https://www.upwork.com/nx/wm/workroom/37844612/overview?nav_dir=pop
