### ISSUE TITLE
[HOLD for payment 2024-06-11] [Payment card / Subscription] Implement empty Subscription screen (UI)

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38615]
Complete the [Update an empty screen with a route and needed Onyx keys](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.ugz2lewwgidd) section of the design doc

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
This one didn't have a C+ review so we're good to close
