### ISSUE TITLE
[HOLD for payment 2024-07-02] [Payment card / Subscription] Implement “Edit payment card” action

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38618]
Drafting cc @fabioh8010

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by pasyukevich** [comment]
Today updates - Started working on this
WIP

**Comment by trjExpensify** [comment]
No BZ on this for some reason. 

Payment summary as follows: 

- $250 to @mananjadhav for the C+ review of the PR 

New feature, and regression tests will be added centrally for the project. Feel free to go ahead and request, Manan. Closing!
