### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [Payment card / Subscription] Implement “Payment card” section (UI)

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38616]
Complete the [Implement "Payment card" section (UI)](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.tz76rdtjvy4q) section of the design doc

> "This PR covers the first subset of the "Payment card section" - everything that is described before the "Implement subscription utils to detect exact errors for card"

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
@pasyukevich was OOO yesterday/today. Asked [in Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1717087772726919?thread_ts=1716904586.883309&cid=C036QM0SLJK) to let us know when the draft PR is ready for C+ review

**Comment by MitchExpensify** [comment]
@pasyukevich Does this PR cover the entire "Payment card" section UI from the doc or a subset of it? If the latter what part does it cover specifically? https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.tz76rdtjvy4q

**Comment by amyevans** [comment]
@VictoriaExpensify - @s77rt reviewed the PR so will be due payment as C+

**Comment by pasyukevich** [comment]
@MitchExpensify This PR covers the first subset of the "Payment card section"  - everything that is described before the "Implement subscription utils to detect exact errors for card

**Comment by s77rt** [comment]
Regression test not needed here. This only adds the Payment card section UI without any functionality yet. The regression test should be added after the functionality is implemented.

**Comment by VictoriaExpensify** [comment]
Hi @s77rt - I'm sorry but I'm having trouble with my Upworks access. I'm going to reassign this so you can get paid.

**Comment by OfstadC** [comment]
Created Upwork Job - https://www.upwork.com/jobs/~013005d7d86a200110

**Comment by OfstadC** [comment]
@s77rt I sent you the hiring offer 😃

**Comment by s77rt** [comment]
@OfstadC Accepted! Thanks!

**Comment by OfstadC** [comment]
Payment Summary:

- @s77rt paid $250
- @pasyukevich does not require payment (Contractor)
