### ISSUE TITLE
[Payment card / Subscription] Integrate “Payment card” section with backend data

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38617]
This covers this section of the doc: https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#bookmark=id.bdt8sxite5i

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - an expert agency - and I would like to work on this issue.

**Comment by pasyukevich** [comment]
Today updates - Finalizing and preparing PR for this, checking all  connected with the feature through the doc

**Comment by trjExpensify** [comment]
We didn't end up with a separate PR for this, so just closing the issue out.
