### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [Payment card / Subscription] Implement “Subscription details” section (UI)

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38623]
Complete the [Create “Subscription details” section (UI)](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.ewpu5ggqc6be) section of the design doc

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Per [Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1717157299551369?thread_ts=1716904586.883309&cid=C036QM0SLJK) from @JKobrynski:

> most of the work is done, I've implemented the basic layout, added the new assets, created the new <OptionsPicker />  component, and now I'm working on the ExpensifyApproved variant, as well as the native version, so I might be able to publish a draft later today but more likely on Monday.

**Comment by JKobrynski** [comment]
The [PR](https://github.com/Expensify/App/pull/42975) is ready for review!

**Comment by amyevans** [comment]
@Ollyws reviewed the PR as C+ so will be due payment

**Comment by MitchExpensify** [comment]
Reminder set to pay

**Comment by MitchExpensify** [comment]
*Payment summary*:

- C+ $250 @Ollyws

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
