### ISSUE TITLE
[HOLD for payment 2024-06-28] [Payment card / Subscription] Integrate “Subscription settings” section with backend data

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38627]
Covers this section of the doc: https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.fwc9tpz3pb79

 cc @fabioh8010

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
I think it has been resolved in #42975, the plan is already fetched from API and read from Onyx. The "Changing plan action" will be implemented in #43029 (a draft was internally approved). What do you think? Is there anything else backend related?

CC: @amyevans

**Comment by MitchExpensify** [comment]
@fabioh8010 Can you help me update the body of this issue to reflect exactly which part of the doc it covers please? Thanks

**Comment by fabioh8010** [comment]
@MitchExpensify Is the section you linked in this GH issue -> https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.fwc9tpz3pb79

**Comment by MitchExpensify** [comment]
Cool so the body is linking to the correct section of the doc, just to be sure, right? @fabioh8010

**Comment by JKobrynski** [comment]
I think it makes the most sense to implement [all toggle actions](https://github.com/Expensify/App/issues/38628) as a part of this issue. Backend integration for that section would be a very tiny PR, like 2-3 lines of new code, so I think it would just bring more work for the reviewers to have 2 separate tasks. Wdyt? I'm already working on it and will be posting a PR soon

CC: @amyevans

**Comment by amyevans** [comment]
Yep that sounds great! Thanks @JKobrynski!

**Comment by amyevans** [comment]
Reassigning to @blimpich as I'm headed out on extended leave

**Comment by trjExpensify** [comment]
No BZ on this either. Payment summary as follows: 

- $250 to @DylanDylann for the C+ review

New feature, regression tests are going to be added centrally for the project as we wrap up soon. 

I'll send you an offer on Upwork now.

**Comment by DylanDylann** [comment]
@trjExpensify As this [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1712256409152489), 

> Any issues created before this date will maintain their original stated price.

this issue was created on March 20 when the initial price still was 500$. Should we update the offer to increase the compensation?

**Comment by trjExpensify** [comment]
Ah yeah, fair enough. Missed that. Accept and I'll adjust.

**Comment by DylanDylann** [comment]
@trjExpensify Thanks 🙏 I accepted it
