### ISSUE TITLE
[Hold for payment 2024-06-21] [Payment card / Subscription] Implement changing plan actions

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38622]
Implement this portion of the design doc: https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.ewpu5ggqc6be

Namely the ability to switch between an annual subscription and pay-per-use subscription, calling the `UpdateSubscriptionType` API with param `type`

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
The [PR](https://github.com/Expensify/App/pull/43029) is ready for review!

**Comment by mananjadhav** [comment]
@amyevans Does this need C+ review? I am assigned on the PR.

**Comment by amyevans** [comment]
Discussed in Slack already, but for posterity, yes please! I'll assign you as well

**Comment by amyevans** [comment]
PR merged

**Comment by mananjadhav** [comment]
This is deployed to production, but the payment date is not set.

**Comment by mananjadhav** [comment]
Thanks @blimpich. All I need is a payment summary. I'll request the payout on NewDot.

**Comment by blimpich** [comment]
Ah okay, I'll leave that to @sonialiap just in case there a piece of the process/context that I'm missing. Thank you for clarifying @mananjadhav!

**Comment by sonialiap** [comment]
@blimpich thanks for the bump, I appreciate it since automation didn't run and didn't get auto-flagged in my list 🙏 😊

**Comment by sonialiap** [comment]
Payment summary:
- @mananjadhav c+ $250 - please request in ND

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
