### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [Payment card / Subscription] Implement “Subscription settings” section (UI)

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38626]
Complete the [Implement “Subscription settings” section (UI)](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.5g9anxlvpux4) section of the design doc

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by trjExpensify** [comment]
@fabioh8010 are you going to be working on this one? I know it has been some time since the issue was created and [this message](https://github.com/Expensify/App/issues/38626#issuecomment-2008732821).

**Comment by fabioh8010** [comment]
@trjExpensify This issue will be eventually picked up by my team, as we've started working on Subscriptions development a few days ago.

**Comment by trjExpensify** [comment]
Okay, cool.. it would be good to know who that is , so we can assign it out correctly. Thanks!

**Comment by amyevans** [comment]
@MrMuzyk was OOO yesterday/today; let us know how it's coming when you're back on Monday!

**Comment by MrMuzyk** [comment]
Got a draft PR open that is being checked internally at the moment. Might be moved to c+ review today

**Comment by amyevans** [comment]
@mollfpr is C+ here so will be due payment

**Comment by garrettmknight** [comment]
**Payment summary:**
- Reviewer: @mollfpr $250

**Comment by garrettmknight** [comment]
Dropping to weekly for request.

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr
