### ISSUE TITLE
[HOLD for payment 2024-06-20] [Payment card / Subscription] Implement “Subscription size” action

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38625]
This covers this section of the doc https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.9ugt6qyi6tlt @fabioh8010

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by sonialiap** [comment]
@MitchExpensify I'm not sure what to do with this issue. Are you working with Michał? If you're not, are we ready to implement this? Do we need to share some info with Michał on what we need for implementation?

**Comment by MitchExpensify** [comment]
@fabioh8010 What should the body of this issue be?

**Comment by fabioh8010** [comment]
@sonialiap @MitchExpensify This issue is covering [this section of the Subscriptions doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.9ugt6qyi6tlt).

@MrMuzyk are you working on this, right? Could you provide some update? Thanks!

**Comment by MrMuzyk** [comment]
Yes, this got unblocked recently and I was planning on implementing this today

**Comment by trjExpensify** [comment]
Assigning @allroundexperts for the review. :)

**Comment by MitchExpensify** [comment]
@MrMuzyk can you help me update the body of this issue by pointing to the exact part of the doc that we're covering here? Thanks

**Comment by MrMuzyk** [comment]
@MitchExpensify Yeah, its [this part](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.9ugt6qyi6tlt)

**Comment by sonialiap** [comment]
Payment summary:
- @allroundexperts C+ $250 - please request in ND

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
