### ISSUE TITLE
[Payment card / Subscription] Integrate “Change billing currency” screen with backend data and “Payment card” section

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38629]
Drafting cc @fabioh8010

<details><summary>Issue Owner</summary>Current Issue Owner: @JKobrynski</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by trjExpensify** [comment]
@JKobrynski confirming this one isn't coming with https://github.com/Expensify/App/pull/43572?

**Comment by bfitzexpensify** [comment]
Bump on https://github.com/Expensify/App/issues/38629#issuecomment-2165220748 @JKobrynski

**Comment by trjExpensify** [comment]
I think you can just close this issue out, as https://github.com/Expensify/App/pull/43572 consolidated https://github.com/Expensify/App/issues/38619, https://github.com/Expensify/App/issues/38630, https://github.com/Expensify/App/issues/44118, https://github.com/Expensify/App/issues/38633.
