### ISSUE TITLE
[Payment card / Subscription] Integrate “Subscription details” section with backend data

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38624]
From this section of the doc: https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1&tab=t.0#bookmark=id.3ofmuddf4blc @fabioh8010

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Yes, agreed we can close this! Call to `OpenSubscriptionPage` API command is implemented, https://github.com/Expensify/App/pull/43029 is in review for changing plan type, and we have https://github.com/Expensify/App/issues/38625 for updating the sub size
