### ISSUE TITLE
[HOLD for payment 2024-06-20] [Payment card / Subscription] Integrate “Your plan” section with backend data and related screens

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38621]
This issue covers this section of the doc: https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#bookmark=id.moxmgpnufzzc

> Mode: Read-only for all platforms (also, no “Learn more” button in native apps)
> Onyx keys: ONYXKEYS.COLLECTION.POLICY, ONYXKEYS.USER_LOCATION 
> API commands: N/A (it’s already implemented in New Dot)
> Component path: 	src/settings/subscription/SubscriptionPlan.tsx
> 
> **Prepwork: Create component file**
> 
> Create a SubscriptionPlan.tsx file that will contain the component logic.
> 	
> **Render the wrapping container**
> 	
> <img width="588" alt="image" src="https://github.com/Expensify/App/assets/36425901/859daa55-38ff-437a-9a08-a3b40d5d72d5">
> <img width="575" alt="image" src="https://github.com/Expensify/App/assets/36425901/0912dc93-f9a4-4843-9bf6-8ad34304ddc6">
> 
> 	This box container will be a <Section /> component with title property 
> (“Your plan”). It’s going to have two variants, depending on the plan variant (control/collect).
> 
> **Fetch the data for subscription details section**
> 
> 	The plan type is already stored in Onyx under the policy_<policyID> key.
> The data can be accessed under ONYXKEYS.COLLECTION.POLICY key, in the type field (it can be free/personal/corporate/team).
> 
> **Add the subscription details section**
> 
> This section has to cover two variants (control/collect). The rendered variant depends on the type key of policy_<policyID> onyx key (team - collect, corporate - control)
> 
> <img width="490" alt="image" src="https://github.com/Expensify/App/assets/36425901/9df339da-a55d-4940-bc00-2fe53f922617">
> 
> Most of this content will be the same for all subscription variants, the only part that changes is this line
> It depends on the variant and different scenarios as described in detail in [Point 2b of UI Additions & Changes](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#heading=h.fvluo2r33dar) section of the doc. It’s going to depend on the ONYXKEYS.COLLECTION.POLICY onyx key.
> The list of benefits will be a set of <MenuItem /> components with interactive={false} prop as they are read-only items.
> 
> The exact price ($5/active in the above case) is going to be dynamic based on currency/location. 
> 
> We are going to follow this order to determine the currency (if not applicable, fall back to the next one):
> Use payment card currency (if a payment card is present)
> Geolocation currency (already in Onyx in ONYXKEYS.PERSONAL_DETAILS_LIST.[userAccountID].localCurrencyCode, which is used as the workspace currency upon workspace creation, and supplied by the backend from [UserAPI::getLocalCurrency](https://github.com/Expensify/Web-Expensify/blob/70e76838f371aff09e4aa4becb7d408eccaffd52/lib/UserAPI.php#L3928-L3950))
> Use USD
> For that purpose we are going to create a helper function named getPreferredCurrency so it can be reused.
> 
> There is also an alternative variant, for workspaces on Control plan
> 
> <img width="473" alt="image" src="https://github.com/Expensify/App/assets/36425901/2fd118bd-692d-4c1a-8b47-436c9eb4d837">
> 
> 
> The layout is identical, the difference is in its content. We will use the same components to build it, just with different props.
> 
> **Add the savings calculator section**
> 
> <img width="434" alt="image" src="https://github.com/Expensify/App/assets/36425901/8466f9c5-9f82-451e-9b33-3945755ba207">
> 
> 
> This section does not depend on the Subscription variant, the only variable here is the platform, more specifically the “Learn more” Button that will redirect the user to https://use.expensify.com/savings-calculator on web and desktop, but it will NOT be rendered in the native apps.

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - expert agency - and I would like to work on this issue.

**Comment by trjExpensify** [comment]
Assigned you @pasyukevich!

**Comment by twisterdotcom** [comment]
Do we have a draft PR yet?

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by MitchExpensify** [comment]
@JKobrynski I've updated the body of the issue, does it accurately reflect everything that is covered in the PR?

**Comment by amyevans** [comment]
Assigned @eh2077 as C+ doing the PR review

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases. _**I don't this we'll need a regression test here as this is just a part of the new feature**_

**Comment by twisterdotcom** [comment]
Payment Summary:

- @JKobrynski does not require payment (Contractor)
- @eh2077 paid $250 [here](https://www.upwork.com/nx/wm/offer/new/1021921362) (C+)
