### ISSUE TITLE
[HOLD for payment 2024-06-13] [Payment card / Subscription] Implement “Your plan” section (UI)

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38620]
Complete the [Create "Your plan section" (UI)](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.qqwmfomen6x1) section of the design doc

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Draft PR is up and in internal Callstack review, should be able to get a C+ review today ([Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1716904703533689?thread_ts=1716904586.883309&cid=C036QM0SLJK))

**Comment by JKobrynski** [comment]
The [PR](https://github.com/Expensify/App/pull/42690) is ready for review!

**Comment by amyevans** [comment]
PR merged 🎉

**Comment by amyevans** [comment]
C+ @akinwale reviewed the PR so will be due payment!

**Comment by muttmuure** [comment]
payment date tomorrow

**Comment by akinwale** [comment]
@muttmuure bump for payment. Thanks.

**Comment by muttmuure** [comment]
Invited you here: https://www.upwork.com/jobs/~012e2020d401ab6278

**Comment by muttmuure** [comment]
Paid
