### ISSUE TITLE
[Payment card / Subscription] Implement all toggle actions

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38628]
This covers this section of the doc https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.jtxukca3oa64 cc @fabioh8010

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by MitchExpensify** [comment]
@JKobrynski Can you help me update the body of this issue with what exactly this issue covers from the doc? Thank you

**Comment by JKobrynski** [comment]
I posted a [comment](https://github.com/Expensify/App/issues/38627#issuecomment-2157770527)  on #38627 why I think it would make sense to implement the toggle actions on the same PR, let me know if that sounds good to you, if so we can close this issue!

CC: @MitchExpensify @amyevans

**Comment by amyevans** [comment]
Closing per ^
