### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [Payment card / Subscription] Integrate “Subscription size” screen with backend data and “Subscription details” section

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38631]
This issue covers this section of the doc https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#bookmark=id.mftmseyadzie @fabioh8010

What we are implementing here is:

- the actual API call to update subscription size
- all data on subscription size screens should come from API
- subscription size screen will be displayed in correct state for each of the mentioned conditions

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by trjExpensify** [comment]
@MrMuzyk are you going to work on this now the PR for https://github.com/Expensify/App/issues/38626 has merged?

**Comment by MrMuzyk** [comment]
@trjExpensify Yes, that will be next on my list if BE is ready. You can assign it to me already

**Comment by MitchExpensify** [comment]
@MrMuzyk, Can you point me to the precise section this issue covers in the Detailed, please? I'd like to update the OP accordingly

**Comment by MrMuzyk** [comment]
@MitchExpensify 

This one covers BE integration of Subscription Size part. There is no section that would cover the integration part in detail, we have an overall description of how it should work - https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#bookmark=id.mftmseyadzie

What I will implement here is:
* the actual API call to update subscription size
* all data on subscription size screens should come from API
* subscription size screen will be displayed in correct state for each of the mentioned conditions

**Comment by MrMuzyk** [comment]
I'm waiting for [this PR](https://github.com/Expensify/App/pull/43122) to get merged so I've opened a draft PR against it in order to get correct diff. Once the mentioned PR gets merged (hopefully soon as it's been approved by C+ already) I will make a proper PR with correct destination

**Comment by amyevans** [comment]
@mananjadhav reviewed the PR as C+ so will be due payment for that.

**Comment by joekaufmanexpensify** [comment]
Sounds good! I'm about to go OOO until 2024-06-25, but don't think payment will be due before then, so not adding an additional assignee. If anything comes up before then, please post in Slack, and someone will be able to help.

**Comment by amyevans** [comment]
Heads up that I'm out on extended leave after today. The only thing remaining here though is payment, if there are any questions feel free to ask in #wave-collect

**Comment by joekaufmanexpensify** [comment]
We have a comprehensive set of testing steps in the design doc, so I don't think we need to add an ad-hoc test here.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment later this week!

**Comment by joekaufmanexpensify** [comment]
Only payment here is $250 to @mananjadhav via NewDot for C+.

**Comment by joekaufmanexpensify** [comment]
Going to close this out for now as it's otherwise all set, but @mananjadhav you're good to request payment whenever you're ready

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
