### ISSUE TITLE
[HOLD for payment 2024-06-20][Payment card / Subscription] Implement “Add payment card” screen (UI)

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38634]
This covers this section of the doc https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.xawijngubbyv cc @fabioh8010

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by narefyev91** [comment]
Hey! I'm Nicolay from Callstack - will work on this flow - please assign it for me. Thanks!

**Comment by amyevans** [comment]
Assigning @rushatgabhane as C+ since he reviewed the PR

**Comment by rushatgabhane** [comment]
1. Go to settings/subscription/add-payment-card
                2. Verify that user can see add debit card
                3. Click Add payment card
                4. Verify that user will see errors with required fields
                5. Fill all required fields
                6. Verify that no errors are shown

**Comment by lschurr** [comment]
Payment summary:

- Contributor+: $250 @rushatgabhane (please request payment in NewDot)

**Comment by lschurr** [comment]
Closing :)

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
