### ISSUE TITLE
[Payment card / Subscription] Implement “Change billing currency” screen (UI)

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38630]
Drafting cc @fabioh8010

<details><summary>Issue Owner</summary>Current Issue Owner: @narefyev91</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Reassigning to @blimpich since I'm headed out on extended leave after today

**Comment by trjExpensify** [comment]
I think you can just close this issue out, as https://github.com/Expensify/App/pull/43572 consolidated https://github.com/Expensify/App/issues/38619, https://github.com/Expensify/App/issues/38630, https://github.com/Expensify/App/issues/44118, https://github.com/Expensify/App/issues/38633.

**Comment by MitchExpensify** [comment]
Do you agree we can close this out @blimpich ?

**Comment by blimpich** [comment]
Yes, PR was deployed to production 👍
