### ISSUE TITLE
[Payment card / Subscription] Integrate “Add payment card” screen with backend data and “Payment card” section

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38633]
This covers this section of the doc: https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.sww2rbm0jchn @fabioh8010

<details><summary>Issue Owner</summary>Current Issue Owner: @narefyev91</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.

**Comment by MitchExpensify** [comment]
@narefyev91 Can you help me update the body of the issue with what exactly we're covering from the doc please? Thank you

**Comment by MitchExpensify** [comment]
Friendly bump on the above @narefyev91 🙇

**Comment by narefyev91** [comment]
> Friendly bump on the above @narefyev91 🙇

Oh sorry just missed mention - yeah sure - i will double check what is it - and will send you info here

**Comment by narefyev91** [comment]
@MitchExpensify here you are https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.sww2rbm0jchn

**Comment by fabioh8010** [comment]
@narefyev91 Any updates here?

**Comment by narefyev91** [comment]
> @narefyev91 Any updates here?

WIP today will be a PR

**Comment by narefyev91** [comment]
Changes already located inside this PR https://github.com/Expensify/App/pull/43572 - (it was hard to isolate them)

**Comment by trjExpensify** [comment]
I think you can just close this issue out, as https://github.com/Expensify/App/pull/43572 consolidated https://github.com/Expensify/App/issues/38619, https://github.com/Expensify/App/issues/38630, https://github.com/Expensify/App/issues/44118, https://github.com/Expensify/App/issues/38633.

**Comment by blimpich** [comment]
Closing as this is completed and deployed.
