### ISSUE TITLE
[$250] [HOLD for payment 2024-06-13] [Payment card / Subscription] Implement “Subscription size” screen (UI)

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#38632]
Drafting cc @fabioh8010

[From this section in the Design Doc:](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.eji9uu70jojm)

Route for  page - /settings/subscription/subscription-size
Before we can start building the actual screen content we have to create an empty SubscriptionsSizePage screen and add it to the navigation. The screen needs to be added to the SCREENS.RIGHT_MODAL.SETTINGS object and SettingsModalStackNavigator to be displayed in the correct way. 

**Implement the first step**

<img width="225" alt="image" src="https://github.com/Expensify/App/assets/36425901/72ec7d12-5b6c-4eb7-a1f9-f8738d65b982">

To implement the header we are going to use <HeaderWithBackButton/>. We will also use <FormProvider /> to handle form submitting and render the “Next” button. We will create a new form ID - SUBSCRIPTION_SIZE_FORM in ONYXKEYS.ts and pass it as a prop (formID) to the <FormProvider />.

**Subtitle**

<img width="308" alt="image" src="https://github.com/Expensify/App/assets/36425901/37a165ee-0ebc-49d0-86ff-c1d91824cda3">

To implement this part we will use a basic <Text /> component with some styles.

**“Subscription size” input**

<img width="322" alt="image" src="https://github.com/Expensify/App/assets/36425901/fae15f1b-46a9-435c-8b25-0926a38e4c04">

To build this input field we are going to use <InputWrapper /> component in a similar way to how it’s done in <DisplayNamePage />. 

**Info section**

<img width="298" alt="image" src="https://github.com/Expensify/App/assets/36425901/f8d8bddf-2e6f-49c0-a288-4b47f2f5b56b">

This is going to be a basic <Text /> component.

**“Next” button**

This button is going to be rendered by <FormProvider />, we will pass the text through the submitButtonText property. When this button is clicked, the user will be redirected to the second step.

**Implement the second step (the default variant)**

<img width="223" alt="image" src="https://github.com/Expensify/App/assets/36425901/167d8df4-202e-4a41-95aa-91bcf9eaddc9">

This is called “the default variant” because it describes the scenario where a user either increases the number of members or decreases it and is allowed to do that (replicating [this logic](https://github.com/Expensify/Web-Expensify/blob/466c34a/site/app/settings/billing/yearlyPanel.jsx#L133-L191)). If a user tries to downgrade from an annual subscription, an alternative variant will be shown (described in next section).

**Subtitle**

<img width="355" alt="image" src="https://github.com/Expensify/App/assets/36425901/abea3913-263e-4594-9774-a275dcb62996">

This is going to be a simple <Text /> component with the updated number of members (20 in this case).

**Info section**

<img width="437" alt="image" src="https://github.com/Expensify/App/assets/36425901/eda5b5ed-0072-4bf9-aef8-7ebccb5306c8">

This section is going to be built using disabled 
<MenuItemWithTopDescription /> components with proper subscription details (number of members, price, end date).

**“Save” button**

<img width="516" alt="image" src="https://github.com/Expensify/App/assets/36425901/9297c71d-88fc-400e-b4d2-11e78ddae603">

We are going to use the <Button /> component wrapped in <FixedFooter /> to place it on the bottom, similar to how it’s done in ContactMethodsPage.tsx.

**Implement the second step (the alternative variant)**

<img width="213" alt="image" src="https://github.com/Expensify/App/assets/36425901/1919ddb5-7c58-4cb2-ab20-1dfffc005b6f">

It will be shown if a user is not allowed to make a change to his subscription (workspace owner tries to downgrade from an annual subscription, either by switching to pay-per-use or lowering subscription size).

**Subtitle**

<img width="371" alt="image" src="https://github.com/Expensify/App/assets/36425901/96cf3155-a34f-40f1-8b7d-c5f1a60504f4">

We are going to use a simple <Text /> component to build this.

**Info section**

<img width="414" alt="image" src="https://github.com/Expensify/App/assets/36425901/9130f8ae-1ac3-429a-8ea3-c0fc8a2d994c">

Once again, a simple <Text /> component.

**“Close” button**

<img width="425" alt="image" src="https://github.com/Expensify/App/assets/36425901/f4dbeeec-875a-4b8a-b53f-59141d4b4921">

We are going to use the <Button /> component wrapped in <FixedFooter /> to place it on the bottom, similar to how it’s done in ContactMethodsPage.tsx.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01501e6915435e5aa7</li>
        <li>Upwork Job ID: 1798871381768029421</li>
        <li>Last Price Increase: 2024-06-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by shawnborton** [comment]
When creating these placeholder GH issues, can you include more information @MitchExpensify like linking to the Design Doc, adding Figma mocks, etc? Thanks!

**Comment by amyevans** [comment]
PR merged

**Comment by MitchExpensify** [comment]
> When creating these placeholder GH issues, can you include more information @MitchExpensify like linking to the Design Doc, adding Figma mocks, etc? Thanks!

Sorry about that @shawnborton ; yes, I'll update them all. 

@MrMuzyk I'm not 100% sure how much of the Subscription size section of the detailed portion is covered here. Please let me know what I should cut!

**Comment by MrMuzyk** [comment]
@MitchExpensify whole UI for the subscription size flow was completed here so I think description that was added covers it 👍

**Comment by amyevans** [comment]
@ikevin127 reviewed the PR as C+ so will be due payment

**Comment by jliexpensify** [comment]
Payment Summary

- C+: @ikevin127 $250

[UPWORKS JOB](https://www.upwork.com/jobs/~01501e6915435e5aa7)

Do we need a competed checklist as well?

**Comment by amyevans** [comment]
Nope no checklist needed

**Comment by jliexpensify** [comment]
Paid and job closed!
