### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Clicking on debit card option on the pay with Expensify button does nothing

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38641]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710845227712549

## Action Performed:
1. Open app and request money from workspace chat or from other user
2. Open the IOU report 
3. Click on `pay with expensify` option from the top right corner of the page
4. Select option `debit card`
## Expected Result:
User taken to debit card adding flow
## Actual Result:
Nothing happens clicking on `debit card`
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5ce982d3-4817-45f0-9219-da37b8a49ffd

https://github.com/Expensify/App/assets/38435837/611e8f26-cefd-41b9-b871-c4bc5d7bbf2c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d862972a492e6ec4</li>
        <li>Upwork Job ID: 1770414879181062144</li>
        <li>Last Price Increase: 2024-03-20</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
rock and roll @parasharrajat

**Comment by dylanexpensify** [comment]
Bump @stitesExpensify to final review for merge today if you can! ❤️

**Comment by stitesExpensify** [comment]
Merged!

**Comment by dylanexpensify** [comment]
Payment summary:
- contributor: @abzokhattab $500
- contributor+: @parasharrajat $500

Please apply or request!

**Comment by dylanexpensify** [comment]
Done

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
