### ISSUE TITLE
[HOLD for payment 2024-05-02] [$500] Incorrect styles in transfer balance> choose account page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38643]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710857164874919

## Action Performed:
1. Open app
2. Go to profile
3. Click wallet > transfer balance
4. Observe the space between "which account" and bank account row
5. Click on the bank account and go to "choose account" page

## Expected Result:
There shouldn't much space between the bank account  and "which account" label in step 4
No overflowicon should be present in "choose account" page

## Actual Result:
- the "Which account?" label on the Transfer balance page seems too far above the bank account row below it
- on the Choose account page, we shouldn't be showing the overflow icons. We also need to use our :active BG color for the currently selected bank account row. And there shouldn't be two option rows below for adding a bank account. The first of the two doesn't even work!

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Snip - New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/38435837/e088e50f-b22e-4a55-bfeb-a470dc56cae4)
![Untitled](https://github.com/Expensify/App/assets/38435837/cb22eaba-0438-4bac-82dd-8de3b1355f5a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01678d0c2e92d5a68c</li>
        <li>Upwork Job ID: 1775846772674859008</li>
        <li>Last Price Increase: 2024-04-04</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by shawnborton** [comment]
> Just wanted to ask if you want to add this feature? bg for selected item.

Ah, thanks for explaining that. On second thought, maybe we should not add that because it will look strange when we have multiple users being selected in various flows that also share this component (like starting a chat or splitting something)

**Comment by miljakljajic** [comment]
Are we keeping this page the way it is? Or still removing the overflow icon?

**Comment by miljakljajic** [comment]
Thank you!

**Comment by miljakljajic** [comment]
@shawnborton can this be worked on externally or would we need to put the design label on here?

**Comment by shawnborton** [comment]
I think someone can work on it externally, and then the Design team will help review the PR.

**Comment by miljakljajic** [comment]
thank you!

**Comment by shawnborton** [comment]
The overflow icon is the three dots icon.

**Comment by mvtglobally** [comment]
QA team is not able to confirm if this issue is still reproducible during KI retests as it requires production KYC passed for Wallet accounts. This issue will need to be retested internally

**Comment by roryabraham** [comment]
thanks, let's proceed with https://github.com/Expensify/App/pull/39944

**Comment by mvtglobally** [comment]
QA team is not able to confirm if this issue is still reproducible during KI retests as it requires production KYC passed for Wallet accounts. This issue will need to be retested internally

**Comment by roryabraham** [comment]
PR in review: https://github.com/Expensify/App/pull/39944

**Comment by miljakljajic** [comment]
@hoangzinh paid - waiting for @dragnoir to accept the offer.

**Comment by miljakljajic** [comment]
Paid!
