### ISSUE TITLE
HIGH: [Marketing] Add Chat page to UseDot

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#38654]

**Comment by jamesdeanexpensify** [comment]
Draft shared [here](https://expensify.slack.com/archives/C03SSAQG5/p1710968428645959?thread_ts=1710887337.010399&cid=C03SSAQG5)!

**Comment by jamesdeanexpensify** [comment]
Has been reviewed internally, asking FPS to take a look next for SEO purposes.

**Comment by jamesdeanexpensify** [comment]
Organizing FPS around [this list](https://expensify.slack.com/archives/C054NDCN44T/p1711053597388899?thread_ts=1711048486.206499&cid=C054NDCN44T) of priority items to work on.

**Comment by jamesdeanexpensify** [comment]
We're in a pretty good place here. I think it's [ready for FPS](https://expensify.slack.com/archives/C054NDCN44T/p1711133310292069?thread_ts=1711048486.206499&cid=C054NDCN44T) to do some keyword research, infuse it with some SEO, and then set it live sometime next week (ideally). We'll also need design to provide some imagery.

**Comment by jamesdeanexpensify** [comment]
FPS is doing keyword research for this page.

**Comment by jamesdeanexpensify** [comment]
Proposed page structure [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1711475838287809?thread_ts=1711049120.252599&cid=C066HJM2CAZ), based on DB's.

**Comment by jamesdeanexpensify** [comment]
Since there's not a huge rush on this page (of course, the sooner it's live the better), I thought we could take a more deliberate approach to starting to A/B test page structure with Spiralyze. Post to follow is [here](https://expensify.slack.com/archives/C05F77PJ91V/p1711485218506799).

**Comment by jamesdeanexpensify** [comment]
Related: https://github.com/Expensify/Expensify/issues/383305

**Comment by jamesdeanexpensify** [comment]
Oh, this is done. https://use.expensify.com/expensify-business-chat-app
