### ISSUE TITLE
[HOLD for payment 2024-04-15] Improve the UI when you click into an expense from a one-expense chat

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/App#38655]
Coming from this [Slack discussion](https://expensify.slack.com/archives/C05RECHFBEW/p1701593626885239):
Slack room: #vip-split

## Problem
Currently, the expense shows the same level of detail in the main chat as it does when you click into it. This feels confusing, to offer users the option to click into something (where presumably they're looking for more detail), but then only show the same level of detail that they've already seen. There are also currently two levels of clicking into an expense that you can do, but both show the same level of detail.

Here's the current flow:
<img width="362" alt="Screenshot 2023-12-04 at 10 38 35 AM" src="https://github.com/Expensify/Expensify/assets/19719519/1165a54c-b8b1-44a5-aa39-1b2bcf8382d1">

<img width="345" alt="Screenshot 2023-12-04 at 10 38 47 AM" src="https://github.com/Expensify/Expensify/assets/19719519/2f01e618-22a3-454a-b090-8694e66edc94">

<img width="311" alt="Screenshot 2023-12-04 at 10 39 01 AM" src="https://github.com/Expensify/Expensify/assets/19719519/829f3d2b-cf50-4127-9554-e1ec4b89ba69">

## Why is this important?
It's not polished, it feels like unexpected behavior for an app to show you the same thing twice. 

## Solution
Summary: 
For single-expense reports, we:
- Combine the report and expense view into one mashup view with report actions in the header and expense details in the body
- Comments on ☝️ that view are attached to the specific expense to keep things sensible if in the rare occasion this report transitions to a multi-expense report
- See Shawn's screenshots [here](https://github.com/Expensify/Expensify/issues/342922#issuecomment-1884607170) for the mocks

Corresponding internal issue: https://github.com/Expensify/Expensify/issues/342922
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01793b9557957db267</li>
        <li>Upwork Job ID: 1770260818085232640</li>
        <li>Last Price Increase: 2024-03-20</li>
    </ul>
</details>

**Comment by NikkiWines** [comment]
@adelekennedy fyi this issue is just an external dupe for https://github.com/Expensify/Expensify/issues/342922 - we needed to re-assign the C+ for https://github.com/Expensify/App/pull/36934 since the current C+ is going OOO.

**Comment by NikkiWines** [comment]
Yes yes melvin we know

**Comment by adelekennedy** [comment]
@NikkiWines I think the only payment due here is for @allroundexperts for the PR review please let me know if I'm missing any additional compensation! 

**Payouts due:**

- [ ] Contributor+: $250 @allroundexperts (NewDot)
