### ISSUE TITLE
[HOLD for payment 2024-04-05] [$250] [Simplified Collect][Tags] Workspace settings - Renaming an enabled tag gets it disabled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR :** https://github.com/Expensify/App/pull/38240

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** New feature
**Email or phone of affected tester (no customers):** gatantm+82@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to Workspace settings (Of a collect or Control policy)
2. Enable tags in "more features"
3. Go to tag settings by clicking on tag
4. Enable the tag
5. Go to tag edit page by clicking on tag name
6. Edit tag name and Save

## Expected Result:
The tag is renamed and stays enabled

## Actual Result:
The tag is renamed but becomes disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/770a422d-f2be-4363-9d82-d45c5a817a89

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c36f5b607dcd8cfb</li>
        <li>Upwork Job ID: 1771212654645612544</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by izarutskaya** [comment]
@stephanieelliott I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tag gets disabled when renaming.

### What is the root cause of that problem?
When we rename the tag, we merge the old tag with the new one.
https://github.com/Expensify/App/blob/331106224ba8ca685b2d0f71ce2244b7f7e259df/src/libs/actions/Policy.ts#L3104-L3108

But the old tag is empty because we accessed it incorrectly.
https://github.com/Expensify/App/blob/331106224ba8ca685b2d0f71ce2244b7f7e259df/src/libs/actions/Policy.ts#L3094

### What changes do you think we should make in order to solve the problem?

We should get the tag the same way as `clearPolicyTagErrors`
https://github.com/Expensify/App/blob/331106224ba8ca685b2d0f71ce2244b7f7e259df/src/libs/actions/Policy.ts#L3062-L3064

```
const oldTag = allPolicyTags?.[`${ONYXKEYS.COLLECTION.POLICY_TAGS}${policyID}`]?.[tagListName]?.tags?.[policyTag.oldName] ?? {};
```

**Comment by mountiny** [comment]
This is a new feature, not really a blocker, I can take over @arosiclair

**Comment by DylanDylann** [comment]
@mountiny I have the context of this issue. If we need a C+ here, I would love to take over

**Comment by DylanDylann** [comment]
@luacmartins Could I take over this issue as a follow-up of [this PR](https://github.com/Expensify/App/pull/38240) as I mentioned [above](https://github.com/Expensify/App/issues/38666#issuecomment-2009789227)?

**Comment by luacmartins** [comment]
Assigning @DylanDylann as C+ and @bernhardoj for implementation of his [proposal](https://github.com/Expensify/App/issues/38666#issuecomment-2009456290)

**Comment by bernhardoj** [comment]
PR is ready

cc: @DylanDylann

**Comment by mountiny** [comment]
$250 to @bernhardoj and $250 to @DylanDylann 

all yours when the time comes @stephanieelliott

**Comment by stephanieelliott** [comment]
PR is undergoing QA

**Comment by luacmartins** [comment]
Just pending payment

**Comment by mountiny** [comment]
Summary [here](https://github.com/Expensify/App/issues/38666#issuecomment-2022648545)

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @bernhardoj $250 PAID via Upwork 
 - Contributor+: @DylanDylann $250 PAID via Upwork 
 
 Upwork job is here: https://www.upwork.com/jobs/~01c36f5b607dcd8cfb
