### ISSUE TITLE
[HOLD for payment 2024-04-05] [$250] [Simplified Collect][Tags] - Deleted tag can be clicked on when deleted offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.-55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is admin of Collect workspace.
- The Collect workspace has tags.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Tags.
4. Go offline.
5. Click on any tag.
6. Click 3-dot menu > Delete tag.
7. Delete the tag.
8. Click on the deleted tag and rename the tag.

## Expected Result:
When a tag is deleted offline, app should prevent user from accessing the deleted tag.

## Actual Result:
When a tag is deleted offline, user can access the deleted tag by clicking on it. When renaming a deleted tag, the tag is no longer deleted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1a2e0500-7cc4-4c27-bb18-3c3db6605b14

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137a327ba3211534e</li>
        <li>Upwork Job ID: 1770409096694325248</li>
        <li>Last Price Increase: 2024-03-20</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by izarutskaya** [comment]
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.



We think this issue might be related to the #wave-control.

**Comment by mountiny** [comment]
Its correct, users should not be able to click on the optimistically deleted tag anymore. 

Not a blocker as this is not used by the customers yet. Going to open this to contributors

**Comment by mountiny** [comment]
Its in tags, but this would work for any category, tag, distance and tax same @Krishna2323 please include it in your PR. Thank you!

**Comment by trjExpensify** [comment]
@ntdiary what specifically about the expected behaviour? 

1. If you delete a category offline, it should appear as "pending deleted" in the table which is greyed out with strikethrough. 2. You shouldn't be able to click the row to edit the details of it thereafter.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @Krishna2323 $250 (paid in Upwork)
- Contributor+: @ntdiary $250 (please accept the [offer in Upwork](https://www.upwork.com/nx/wm/offer/101481389))

**Comment by lschurr** [comment]
Great, we're all set!
