### ISSUE TITLE
Members - Hyperlink Not Rendered Correctly in Invitation Message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38672]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.55-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Settings > Workspace.
2. In Workspace Settings, go to Members.
3. Click on "Invite Members" and add an email address.
4. Observe that the hyperlink within the invitation message is not displayed correctly.

## Expected Result:
The hyperlink in the invitation message should be displayed correctly.

## Actual Result:
The hyperlink within the invitation message is not displayed correctly.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b2f92d90-b324-4428-8b27-0affb4022a86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment]
This is expected behavior. We permit markdown in the editor and it renders correctly when the message is sent. I believe we've discussed using the live markdown editor for these types of fields before and decided against it.
