### ISSUE TITLE
[Distance rates] Category - Cannot cancel the category selection in distance rates settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38673]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38060
## Action Performed:
Precondition:
- User is an admin of Collect workspace.
- User has paid policy with distance rates available
1. Go to URL staging.new.expensify.com.
2. Go to Profile > Workspaces -> choose Collect workspace
3. Go to the distance rates screen -> Press on settings -> Default category
4. Choose any category
5. Open the default category again and click on the same category to unselect it

## Expected Result:
User can unselect the category in distance rates settings

## Actual Result:
Cannot cancel the category selection in distance rates settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/84170785-bafc-4697-9d60-be18dde58c7e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@Beamanator  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
Related discussion here: https://expensify.slack.com/archives/C036QM0SLJK/p1710945911418889?thread_ts=1710800247.591739&cid=C036QM0SLJK

This isn't a blocker, demoting it. @MrMuzyk is going to fix it in the follow-up PR.

**Comment by mountiny** [comment]
The PR has been merged and C+ payment is handled elsewhere, I believe we can close this issue now as no further steps are required, thanks @MrMuzyk !
