### ISSUE TITLE
mWeb - Admin - On #admin, when workspace member was invited added as a user message is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on profile --- workspaces --- Workspace
3. Tap members --- invite member
4. Invite a member
5. Navigate to LHN
6. Open the #admin room of the workspace where a user was invited

## Expected Result:
On admin room, when workspace member was invited added as a user message must be shown

## Actual Result:
On admin room, when workspace member was invited added as a user message is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/de9d0551-9b7d-4dea-8629-7df94a4cc777

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by anmurali** [comment]
<img width="1049" alt="image" src="https://github.com/Expensify/App/assets/14225673/54fd2986-eb7c-4f8d-9c5b-9920854f22a9">

Cannot reproduce.
