### ISSUE TITLE
[HOLD for payment 2024-05-22] [Pending/Scanning pattern] Update the UI for Pending and Scanning in Single Transaction ReportPreview / MoneyRequestAction

### ISSUE THREAD

**Issue by grgia** [Expensify/App#38688]
### Design Doc Section
https://docs.google.com/document/d/1hKK7emsQt4iDvP8Ohvk5aCc8gNdRelyxvbxDkXZxNRA/edit#bookmark=id.hpicdhh0ps4f

## Goal

Use new UI pattern for both pending and scanning transactions. 

## Requirements

https://github.com/Expensify/App/issues/38688#issuecomment-2010190801

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db8df296aa6c0d99</li>
        <li>Upwork Job ID: 1770496519810551808</li>
        <li>Last Price Increase: 2024-03-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by shawnborton** [comment]
Gonna give this one to you @dannymcclain

**Comment by dannymcclain** [comment]
Updated mocks. These can all be found [here in Figma](https://www.figma.com/file/vjsoFByAkzNKyJVPwnX252/Wave-5%3A-Update-reporting%2Fpending-expenses-(Copy)?type=design&node-id=1123-14430&mode=design&t=TDVwLxHBFzUfcRgk-11).

#### Pending Transaction
![CleanShot 2024-03-20 at 12 24 41@2x](https://github.com/Expensify/App/assets/7516624/e2b878d4-7860-43a6-b673-0830c8cfe675)

![CleanShot 2024-03-20 at 12 27 05@2x](https://github.com/Expensify/App/assets/7516624/e88515aa-e4bc-4d5c-95f6-2908ea79a580)

#### Receipt Scanning
![CleanShot 2024-03-20 at 12 28 40@2x](https://github.com/Expensify/App/assets/7516624/dc680360-43ba-4eec-8f62-070dbc88af7b)

#### "Report Status" Overview
![image](https://github.com/Expensify/App/assets/7516624/8386444f-e675-4e26-aabe-d600132e92ab)

@grgia let me know if you need anything else!

**Comment by grgia** [comment]
@dannymcclain are we removing the highlight row pattern?

**Comment by dannymcclain** [comment]
Yes, we decided [in this thread](https://expensify.slack.com/archives/C06ML6X0W9L/p1710915121059499) to keep it simple to start and just go with the status pattern (no highlight).

**Comment by grgia** [comment]
Rad, that makes life easy! @dannymcclain. 

cc @kevinksullivan shall we update the HL? I can make a few adjustments to the detailed before I pass off to SWM

**Comment by BrtqKr** [comment]
Hey, I'm an engineer from SWM, I'd like to handle this ticket

**Comment by grgia** [comment]
@BrtqKr let me know if there's anything you need for this one. I updated the design doc section to reflect the final design. 

@dannymcclain I believe we'll need these two new icon assets for this issue:
<img width="80" alt="image" src="https://github.com/Expensify/App/assets/38015950/ab351a52-bd89-4f87-9988-1d2a6f367183">

<img width="90" alt="image" src="https://github.com/Expensify/App/assets/38015950/0f705ce5-a346-4004-9bf3-17dfcdd9277e">

**Comment by grgia** [comment]
@dannymcclain could you also show me a mock with the report previews for this flow?

By that I mean,

- What does it look like on the ReportPreview (parent chat) when a report has 1 scanning, 1 pending, 1 normal request
- What does it look like on the ReportPreview (parent chat) when a report has 1 scanning, 1 normal request
- What does it look like on the ReportPreview (parent chat) when a report has 1 pending, 1 normal request

etc etc. Are there any changes we need to make there? I believe right now it shows copy like `1 request, 1 scanning, 1 pending`. I want to make sure we cover all bases here for QA, thanks!

**Comment by dannymcclain** [comment]
I need Melvin to leave me alone. Any important updates on this one?

**Comment by grgia** [comment]
bump @BrtqKr

**Comment by BrtqKr** [comment]
@dannymcclain, I had some issues with one of the migration PRs, so I'm still working on that. I should be done with that at the beginning of the next week, sorry for the delay 🙏

**Comment by grgia** [comment]
@BrtqKr thank you for the update

**Comment by grgia** [comment]
@kevinksullivan I think we just need C+ payment here

**Comment by kevinksullivan** [comment]
handling

**Comment by kevinksullivan** [comment]
job is expired so I am creating a new one. @ishpaul777 lmk when you accept

https://www.upwork.com/jobs/~011eaca59680ce2d2b

**Comment by kevinksullivan** [comment]
all set
