### ISSUE TITLE
[HOLD for payment 2024-05-02] CRITICAL: [Track Expense] [$500] Unable to edit request

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#38699]
Things to fix from this PR: https://github.com/Expensify/App/pull/37282

https://github.com/Expensify/App/pull/37282#pullrequestreview-1949415677
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01585d11e9c8f2b823</li>
        <li>Upwork Job ID: 1770523464695119872</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
The only API that seems to still be failing is UpdateMoneyRequestAmountAndCurrency
```
{
    "jsonCode": 0,
    "message": "Out of range",
    "onyxData": [],
    "requestID": "86dd74363cb759a6-DEL"
}
```

**Comment by thienlnam** [comment]
@shubham1206agra Are you able to link the draft PR you have here?

**Comment by thienlnam** [comment]
https://github.com/Expensify/App/issues/38699#issuecomment-2040370914

**Comment by thienlnam** [comment]
@shubham1206agra Bump on this - the BE issues are resolved so you should be able to open your PR now

**Comment by thienlnam** [comment]
@shubham1206agra Bump again - what's blocking us from getting this into review?

**Comment by thienlnam** [comment]
@shubham1206agra Could we please get this into review? This is a release 1 item as well

**Comment by thienlnam** [comment]
Increasing amount since we'd like to fit this into the next App deploy

**Comment by skyweb331** [comment]
Is this issue open for Contributors??? I can not find `Help Wanted` label

**Comment by quinthar** [comment]
@skyweb331 I think @shubham1206agra is already on this

**Comment by quinthar** [comment]
Or at the very least, I'm confused by their comment here: https://github.com/Expensify/App/issues/38699#issuecomment-2065339966

**Comment by allroundexperts** [comment]
My payment is pending as well here:

https://github.com/Expensify/App/pull/39956

@thienlnam @twisterdotcom

**Comment by twisterdotcom** [comment]
@shubham1206agra you still need to accept the offer I sent here: https://www.upwork.com/nx/wm/offer/102145720

**Comment by twisterdotcom** [comment]
Nice, okay @allroundexperts I updated the Summary here: https://github.com/Expensify/App/issues/38699#issuecomment-2091186490 to include you and paid out @shubham1206agra.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
