### ISSUE TITLE
Workspace - Workspace name not update in real time for secondary device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38692]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+gm118@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
Login with the same account in the main testing device and a secondary device
1. On the main testing device create New workspace
2. Change the name of the Workspace
3. Notice the secondary device Workspace page

## Expected Result:
Workspace name on the secondary device should be updated in real time

## Actual Result:
Workspace name does not update in real time for secondary device

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/34ede0d4-decc-432a-bfd2-cdaef8bdc4c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
I dont think this has to be a blocker, taking over as its related to the simplified collect

**Comment by mountiny** [comment]
Same cannot repro locally, going to close
https://github.com/Expensify/App/assets/36083550/c0ecb194-be69-485c-8b89-0b54df8360ba
