### ISSUE TITLE
mWeb/Chrome - Scan - Infinite loading instead of placeholder page after denying camera access

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38696]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Camera permission for staging ND on browser is reset
1. Go to staging.new.expensify.com
2. Tap FAB > Request money
3. Go to Scan
4. Deny camera access

## Expected Result:
App will show placeholder screen in Scan page

## Actual Result:
App shows infinite loading in Scan page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bb670f27-4225-4c1c-aac2-bdfeb43aac33

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment]
Asked for cp [here](https://expensify.enterprise.slack.com/archives/C07J32337/p1710974238894419)

**Comment by rlinoz** [comment]
https://github.com/Expensify/App/issues/38651#issuecomment-2013684642 removing deploy blocker label

**Comment by rlinoz** [comment]
oh, yeah, you are right.
