### ISSUE TITLE
Improvement - Typing `@`in the group DM should suggest only the members of the group at the top

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38707]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710878688977429
 
## Action Performed:
1. Open any group chat
2. Type `@` to mention
3. Look at the suggestion list

## Expected Result:
Should suggest the group DM members at the top then unrelevant users
## Actual Result:
Shows unrelevant users
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/2f0899e7-0519-4d93-9e55-f5cb85090b34

![Screen Shot 2024-03-20 at 3 59 59 PM](https://github.com/Expensify/App/assets/38435837/7202968d-9720-4078-941d-7df9378a4950)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
We have an issue for rooms too https://github.com/Expensify/App/issues/24436

**Comment by alexpensify** [comment]
@mallenexpensify should we close this one and focus on https://github.com/Expensify/App/issues/24436?

**Comment by mallenexpensify** [comment]
I don't think so, I'll take this over as BZ.  I'm unsure what the next best steps are right now.

**Comment by mallenexpensify** [comment]
Added to #vip-vsb because the feature request doesn't involve money

**Comment by mallenexpensify** [comment]
Going to wait on status and we might want to deal with this more holistically

**Comment by mallenexpensify** [comment]
Checking on [here](https://expensify.slack.com/archives/C049HHMV9SM/p1713322833240619?thread_ts=1711460237.297499&cid=C049HHMV9SM)

**Comment by mallenexpensify** [comment]
Unsure of status, no action on the [post in #expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1713322833240619?thread_ts=1711460237.297499&cid=C049HHMV9SM) from two weeks ago

**Comment by mallenexpensify** [comment]
Not an immediate priority

**Comment by mallenexpensify** [comment]
I think Search is getting addressed so this might be rolled into that?

**Comment by mallenexpensify** [comment]
Gonna close cuz we just paused all features, will reopen if/when needed.
