### ISSUE TITLE
[$500] BA - "Continue with set up" page is not displayed when coming back to BA page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38701]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4441161
**Email or phone of affected tester (no customers):** applausetester+vd_web032024@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user mist be logged in and have created a workspace
1. Go to Workspace > Bank account
2. Select "Connect manually"
3. Go trough the add BA flow using the testing credentials until you reach the "Validate your bank account" page
4. Exit the add BA modal
5. Click on Bank account again, verify the "Continue with set up" page is displayed and functional
6. Click on "Start over" to restart the add BA flow
7. Select "Connect online with Plaid"
8. Select Regions bank and use the testing credentials
9. Select the bank account number and continue
10. Verify you land on the "Validate your bank account" page, since the previous process remained pending
11. Click on the back arrow
12. Verify the "Continue with set up" page is displayed
13. Exit the add BA modal
14. Click once more on Bank account
15. Verify the "Continue with set up" page is not displayed, add BA initial page is displayed instead

## Expected Result:
"Continue with set up" page should be displayed

## Actual Result:
"Continue with set up" page is not displayed, add BA initial page is displayed instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a160c992-8bd9-4f9c-a4cc-d4a1d6208486

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e50f30754972802</li>
        <li>Upwork Job ID: 1770574581994590208</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by stitesExpensify** [comment]
@MrMuzyk do you know what the API call is? I can check the blame to see when it was last changed

**Comment by MrMuzyk** [comment]
The one that returns no data when it should is called `OpenReimbursementAccountPage`

**Comment by stitesExpensify** [comment]
I haven't had a chance to take a deeper look at this yet.
