### ISSUE TITLE
Close account - User is unable to close account due to an error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38708]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4443318
**Email or phone of affected tester (no customers):** esraa55saad+678@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the testing app
2. Navigate to Profile > Security
3. Click on Close account
4. Enter the default contact method
5. Click on Close Account > Yes

## Expected Result:
Account will be closed successfuly, if there is an error regarding incorrect/missing field entered, the user should be the error on the specified field

## Actual Result:
Account is not closed, there is an error above the Close account button informing user to "Please fix the errors in the form before continuing." although there are no errors appearing inside the form

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/81081b53-7516-40aa-aa40-07e7c84e971f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/37623 issue covers all issues where we are showing common error message including this issue.

**Comment by dylanexpensify** [comment]
@sobitneupane thanks for the link! Going to put this on hold to test once that's on staging!

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
Still in a holding pattern, moving to Weekly until we're out of hold

**Comment by dylanexpensify** [comment]
same

**Comment by dylanexpensify** [comment]
Similar

**Comment by dylanexpensify** [comment]
Held

**Comment by dylanexpensify** [comment]
Off hold, @lanitochka17 can you confirm if reproducible?

**Comment by dylanexpensify** [comment]
Bump @lanitochka17

**Comment by lanitochka17** [comment]
@dylanexpensify  Hello 
Issue is not reproducible with expensifail account

https://github.com/Expensify/App/assets/78819774/eed4b03b-0499-42cf-91e8-0da05b7775a5

Issue is not reproducible with gmail account

https://github.com/Expensify/App/assets/78819774/e27df007-efad-4ee9-be53-df41cc40d645
