### ISSUE TITLE
Chat - New message displayed in preview but not displayed in chat when chat opened offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38706]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2778002
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log into Expensify on the main testing device - On another device, log in to another account
2. Disable your internet connection on the main testing device.
3. On another device (can be any), send a message to the account logged in the main testing device
4. On the main device - Navigate to LHN (mobile) or to another conversation (Desktop/Web)
5. Enable the internet connection.
6. Ensure the message you sent via the other device is received in the main device
7. Verify the conversation is displayed bold in LHN
8. Disable the internet connection in the device
9. Click/tap on the bold chat in LHN

## Expected Result:
New message is displayed in the conversation history.

## Actual Result:
New message is not displayed in the conversation history, but displayed in preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/78cd5f22-a780-409f-b702-f470ed67e9a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mks-h** [comment]
Cannot reproduce on v1.4.55-0 in Firefox on Fedora Linux
[Screencast from 2024-03-21 02-58-56.webm](https://github.com/Expensify/App/assets/51861383/59788f09-56cd-4655-9140-0710947ff753)

**Comment by mks-h** [comment]
Contributor details
Your Expensify account email: mhazevych@proton.me
Upwork Profile Link: https://www.upwork.com/freelancers/~010fa0fee42948413f
