### ISSUE TITLE
No Idology questions were triggered after submitting the credentials.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #35438
**Version Number:** 1.4.55-0
**Reproducible in staging?:** y
**Reproducible in production?:** couldn't check since it requires real data
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new expensify.com and log in
2. Go to Settings > Wallet > Enable Wallet > Add a bank account
3. Use information:
Use Regions Bank
Username: user_good | Password: pass_good
First Name: Alberta
Last Name: Charleson
Last SSN numbers: 3333
4. Click Continue

## Expected Result:
Idology questions were triggered after tap continue.

## Actual Result:
No Idology questions were triggered after tap continue

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/f1d9a1b0-30d1-446f-b3c3-1397f39ec86a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by miljakljajic** [comment]
@neil-marcellini is OOO but I'll remove the deploy blocker label for now.

**Comment by neil-marcellini** [comment]
@kavimuru @miljakljajic I'm not sure that this is a real issue. The test steps don't really make sense to me. In the PR https://github.com/Expensify/App/pull/35438 we needed to merge some data into Onyx to reach the Idology page, so it makes sense that we don't reach it without that. @jayeshmangwani @Gonals @ntdiary do you agree?

**Comment by jayeshmangwani** [comment]
@kavimuru @kbecciv @neil-marcellini Instead of the `Last Name: Charleson` please use `Last Name: Bobbeth` , it works in staging, for prod we can use only by accessing for the backend, Sorry for the confusion [here](https://github.com/Expensify/App/pull/35438#issuecomment-2010376835)

**Comment by neil-marcellini** [comment]
Ok great, so it sounds like we agree this is not an issue. Closing it out.
