### ISSUE TITLE
[HOLD for payment 2024-04-05] HIGH: [Performance] Send less user is typing events

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#38714]
Reported https://expensify.slack.com/archives/C049HHMV9SM/p1710969968937119

We seem to be sending the UserIsTyping message for every keystroke.  This means if I'm in a DM with you, and if I'm typing quickly, I am sending you a continuous stream of messages via Pusher -- which is hammering your client's network stack, Onyx database, and main thread.  I think we should ideally:
- Send the first message the moment you start typing
- Send a new message every second, so long as you are still typing
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014119b0bde30a6fc4</li>
        <li>Upwork Job ID: 1770576924726861824</li>
        <li>Last Price Increase: 2024-03-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by quinthar** [comment]
Incidentally, I *think* we are sending typing indicators even after we leave the room.  Do we explicitly leave the channel of past rooms when leaving the room, or not?

**Comment by iwiznia** [comment]
Yes, we are doing that [here](https://github.com/Expensify/App/blob/b3068864afeaedd448cb59107629fc5cb67fe009/src/libs/actions/Report.ts#L312)

**Comment by quinthar** [comment]
Actually it [looks like we don't reliably unsubscribe from isTyping events](https://expensify.slack.com/archives/C049HHMV9SM/p1711131919203929) -- it could be that we unsubscribe when switching to another room, but we might not unsubscribe when switching to a non-room page (eg, Settings)

**Comment by iwiznia** [comment]
@muttmuure you handling this?

**Comment by muttmuure** [comment]
@eVoloshchak ready for you to submit a request in New Expensify

**Comment by eVoloshchak** [comment]
@muttmuure, not sure if I'm missing something, shouldn't this be $500 since this is
a) HIGH
b) was created before April 5th?

According to https://expensify.slack.com/archives/C02NK2DQWUX/p1712250884549319

**Comment by muttmuure** [comment]
Updated to $500 thanks!

**Comment by JmillsExpensify** [comment]
$500 approved for @eVoloshchak
