### ISSUE TITLE
HIGH: [Mentions] Ensure email/SMS mentions correctly notify the newly invited person

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#38717]
Problem:
====
It seems that mentioning people via email or SMS does add them to the room, but doesn't actually notify them via email/SMS that they were added.

Solution:
====
When mentioning someone it should:
1. Add them to the room
2. Trigger an immediate unread message summary (skipping any notification frequency)
3. Start that summary with the mentioned message (ie, so they can see the context in which they were mentioned)
4. Include the welcome message beneath that
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140434368db967cc3</li>
        <li>Upwork Job ID: 1770579890918490112</li>
        <li>Last Price Increase: 2024-03-20</li>
    </ul>
</details>

**Comment by justinpersaud** [comment]
@puneetlath tagging you here since you worked on mentions. Do you happen to have any ideas why this wouldn't work or if not, maybe point to the code for where this should happen? If not, I'll just try and run through the scenario in dev and try to figure it out.

**Comment by puneetlath** [comment]
Hm, I would think it should work. I believe the logic that determines that they get notified immediately when mentioned is [here](https://github.com/Expensify/Web-Expensify/blob/442beb881dc09e05d20e21a63401ab9b5567461c/lib/ReportUtils.php#L2445). Though maybe it only works for existing accounts and isn't working properly for newly created ones?

**Comment by justinpersaud** [comment]
I submitted a PR for this which I think will solve our issue here

https://github.com/Expensify/Web-Expensify/pull/41453

**Comment by justinpersaud** [comment]
Fix was deployed to production.
