### ISSUE TITLE
New Workspace button shows on Global create when Collect workspaces exist

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#38749]
## Problem
New Workspace button shows on Global create when Collect workspaces exist, but it should only show when there are no available workspaces

## Why is this important?
It is inconsistent behavior

## Solution
Hide it when we have Newdot-enabled Collect workspaces
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe6975faa279e152</li>
        <li>Upwork Job ID: 1770831183603826688</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

**Comment by situchan** [comment]
We're removing this in #36153

**Comment by twisterdotcom** [comment]
@situchan we can close this as a dupe then right?
