### ISSUE TITLE
[HOLD for payment 2024-06-06] [HOLD for payment 2024-05-03] Use Fallback Avatar Pattern for Unknown Users

### ISSUE THREAD

**Issue by grgia** [Expensify/App#38743]
### Background

Slack convo: https://expensify.slack.com/archives/C036QM0SLJK/p1710942820060629

**Colorful / Default Avatars**
<img width="254" alt="image" src="https://github.com/Expensify/App/assets/38015950/797cbf61-1588-498e-94ed-5242aed71ecf">

**Fallback Avatar**

![image](https://github.com/Expensify/App/assets/38015950/a410988d-5a46-4c33-a361-ac6da42f5438)

### Problem

We have a lot of issues surrounding avatar behavior. Some of this is due to how we originally designed the Default Avatar logic, which used a user's login to calculate. This meant that a default avatar could be correctly guessed for any user. However, due to email and privacy concerns, we changed this logic to use the accountID. 

Now, any optimistic account ID that is later replaced results in a mismatch of avatars. This has caused a group of bugs all with the same RCA.

### Solution

Using the color default avatars as a placeholder avatar causes confusion, so let's stop using them as defaults for users we don't know. From now on, let's always use the fall back avatar. We _should_ be storing the default avatars the same way we store a user-uploaded avatar. So we should stop optimistically setting avatars for users that you don't have in ONYX.

### Rules for Avatars

From now on, we want to treat avatars as the following:

- Colorful default avatars are considered assigned avatars and should be treated the same as when a user has a custom uploaded avatar
- Fallback avatars are used whenever a user’s accountID is unknown or when there’s a problem fetching the avatar (isOffline)
- You’ll only see avatars for users you have in ONYX

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by hayes102** [comment]
Hello @grgia is this issue open for proposals ?

**Comment by grgia** [comment]
@hayes102 I'm waiting to hear back from someone at one of our agencies about this. 

https://github.com/Expensify/App/pull/38674

For context, I started working on this in this PR- I have the search bar working with this pattern, but there's some funkiness around money request search options or chatting a new user, so I am planning to take those changes out for now and have this PR only add the theme support and tackle those changes with this issue. That said, we will begin taking proposals by tomorrow if the issue is not taken by SWM.

**Comment by Kicu** [comment]
hey I work for SWM and would like to work on this one

**Comment by grgia** [comment]
@Kicu I removed the fallback changes I made in the PR- https://github.com/Expensify/App/pull/38674/commits/44dc9fcc28508230324dfcacfdf2d12235e36329

see this commit for the search, as well as this thread: 

https://github.com/Expensify/App/pull/38674#discussion_r1536370896

**Comment by Kicu** [comment]
Thank you @grgia I will be working on this today

**Comment by luacmartins** [comment]
Created issue to fork the repo - https://stackoverflowteams.com/c/expensify/questions/10007

**Comment by rlinoz** [comment]
This didn't actually cause the blocker, sorry.

**Comment by puneetlath** [comment]
@s77rt is owed $250 for being C+ here, is that right?

**Comment by s77rt** [comment]
@puneetlath Payment not due yet. This causes a regression and PR is reverted. @Kicu Any ETA on the PR?

**Comment by puneetlath** [comment]
What's left to do here?

**Comment by Kicu** [comment]
Nothing to do, PR is open awaiting on review

**Comment by puneetlath** [comment]
Still being reviewed?

**Comment by s77rt** [comment]
Waiting for the engineer review and for the merge freeze I suppose

**Comment by Kicu** [comment]
yup. Let's ping either @mountiny or @grgia if you could take a look and review?
From what I hear the merge freeze might be off tomorrow.

This PR touches a lot of places in the code and so I would really like to merge it sooner rather than later

**Comment by mountiny** [comment]
Yep just waiting for the merge freeze to be lifted now.

**Comment by puneetlath** [comment]
We're now in merge slush. Can we review?

**Comment by mountiny** [comment]
I have approved and requested a merge

**Comment by mountiny** [comment]
We have cleared that

**Comment by puneetlath** [comment]
I just want to confirm that any regressions have been fixed and we are ready to pay here? And that @s77rt is the only person needing payment?

**Comment by s77rt** [comment]
Yes all has been handled

**Comment by puneetlath** [comment]
Ok offer here: https://www.upwork.com/nx/wm/offer/102641250

**Comment by puneetlath** [comment]
Please ping me on this issue when you've accepted.

**Comment by s77rt** [comment]
Accepted! Please make the payment $62.5 for the initial regression and for this regression https://github.com/Expensify/App/issues/42750

**Comment by puneetlath** [comment]
That was surprisingly hard, but I figured it out. 

All paid, thanks y'all!
