### ISSUE TITLE
[HOLD for payment 2024-05-09]  HIGH: [API Reliability] Prevent simultaneous calls to `GetMissingOnyxMessages` using a `deferredUpdates` queue

### ISSUE THREAD

**Issue by danieldoglas** [Expensify/App#38748]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

### Background:

An onyxUpdate is content we receive through https responses or Pusher that will update the state the local data. They will only bring a smaller piece of the information that was updated, instead of constantly doing full fetches to update everything. 

To guarantee that the data is in a correct state, we need those updates to be applied in order. So every update that will modify local data will have previousUpdateID and lastUpdateID. For every new update we receive, we check the received previousUpdateID with the local lastUpdateID. 

If they are the same, that means that we can apply that update and we'll have a correct state of the data. If they're not, then we need to fetch the missing updates (using GetMissingOnyxMessages with an updateIDFrom with the local lastUpdateID and updateIDTo with the previousUpdateID that was received from the server.

Once we have those updates applied, we can then apply the received update.

We have onyxUpdates being applied both through [http responses](https://github.com/Expensify/App/blob/30b809ca1bf63db2747b7402831bbe6c6d4ee684/src/libs/Middleware/SaveResponseInOnyx.ts#L28-L33) and [Pusher](https://github.com/Expensify/App/blob/30b809ca1bf63db2747b7402831bbe6c6d4ee684/src/libs/actions/OnyxUpdates.ts#L145-L155) (calls [here](https://github.com/Expensify/App/blob/30b809ca1bf63db2747b7402831bbe6c6d4ee684/src/libs/actions/User.ts#L589) and [here](https://github.com/Expensify/App/blob/30b809ca1bf63db2747b7402831bbe6c6d4ee684/src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.ts#L50)). When we call saveUpdateInformation, we we're triggering [this callback function](https://github.com/Expensify/App/blob/30b809ca1bf63db2747b7402831bbe6c6d4ee684/src/libs/actions/OnyxUpdateManager.ts#L35-L94) that will pause the SequentialQueue (so we don't receive more onyxUpdates until this is finished), fetch the missing updates, apply the pending updates, and then unpause the SequentialQueue. But we can't do that with onyxUpdates that comes from pusher.

### Problem:

When we receive onyxUpdates, we'll trigger one `GetMissingOnyxMessages` per update out of order that comes by.

**Scenario:**

1. Alice posts to #big-room to create updateID=10
2. Bob posts to #small-room two times, to create updateID=11 and 12
3. Cathy is part of both rooms, and has a local lastUpdateID=9
4. Cathy receives 11 -- sends GetMissingOnyxUpdates. This call might takes a few seconds.
5. Cathy receives 12 before (4) is finished. So the client sends GetMissingOnyxUpdates again
6. Once (4) finishes and it's applied locally, the response for GetMissingOnyxUpdates on (5) will be discarded.

In this scenario, we did 2 GetMissingOnyxMessages, when 1 would be enough. Please note that this is not limited to 2 calls today: if we had received 10 messages, it would do 10 API calls.

In this scenario, we did 3 GetMissingOnyxMessages.

### Possible solution:

**What I'm proposing is that we implement 3 changes.**

1. Only execute one **GetMissingOnyxMessages** call at a time;
2. Implement a **deferredUpdates** queue that will hold all updates that can't be applied immediately that will arrive while the call on (1) is being executed on an ordered manner. Then apply them if the pre-requisites are filled OR do another GetMissingOnyxMessages if we still find gaps on them
3. Change the way we deal with received updates. If we can apply it immediately, we should trigger a check on the deferredUpdates queue to confirm if any of the held updates can be applied after we apply the received one.

By doing those, the expected behavior for the same scenario is:

1. Alice posts to #big-room to create updateID=10
2. Bob posts to #small-room three times, to create updateID=11, 12 and 13
3. Cathy is part of both rooms, and has a local lastUpdateID=9
4. Cathy receives 11 -- sends GetMissingOnyxUpdates. This call takes a few seconds.
5. Cathy receives 12 and 13 before (4) is finished. So the client stores those updates in the deferredUpdates queue. It's important to note that these updates can arrive unordered. 
6. Once (4) finishes and it's applied locally, we get all updates stored in deferredUpdates and apply them, in order. If we detect any gaps in the received updates, we need to go back to step (4)

In this scenario, we only did 1 GetMissingOnyxUpdates.

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by Szymon20000** [comment]
Comment :)

**Comment by danieldoglas** [comment]
No need for C+ on this one!

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we receive onyxUpdates, we'll trigger one GetMissingOnyxMessages per update out of order that comes by.

### What is the root cause of that problem?

We allow calling `App.getMissingOnyxUpdates` while fetching missing updates is in progress.

### What changes do you think we should make in order to solve the problem?

We can introduce `isFetchingMissingUpdates`, and ensure it will only call another `App.getMissingOnyxUpdates` when `isFetchingMissingUpdates === false`

```
// ...

// Add a new state to track if we are currently fetching missing updates
let isFetchingMissingUpdates = false;

export default () => {
    console.debug('[OnyxUpdateManager] Listening for updates from the server');
    Onyx.connect({
        key: ONYXKEYS.ONYX_UPDATES_FROM_SERVER,
        callback: (value) => {
            if (!value || isFetchingMissingUpdates) {
                return;
            }

            // ...

            // Set isFetchingMissingUpdates to true before we start fetching
            isFetchingMissingUpdates = true;

            canUnpauseQueuePromise.finally(() => {
                OnyxUpdates.apply(updateParams).finally(() => {
                    console.debug('[OnyxUpdateManager] Done applying all updates');
                    Onyx.set(ONYXKEYS.ONYX_UPDATES_FROM_SERVER, null);
                    SequentialQueue.unpause();

                    // Set isFetchingMissingUpdates back to false after we finish fetching
                    isFetchingMissingUpdates = false;
                });
            });
        },
    });
};
```

### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment]
@danieldoglas no worries. Is there any specific tags that determine if an issue already taken or not?

**Comment by danieldoglas** [comment]
@wildan-m you should apply only for issues that have the label `Help wanted`

**Comment by wildan-m** [comment]
> @wildan-m you should apply only for issues that have the label Help wanted

@danieldoglas, this post contains it, Melvin might have mistakenly added it. I think you should remove it.

**Comment by quinthar** [comment]
Sorry bout that @wildan-m !

**Comment by chrispader** [comment]
I'm taking this issue over from @Szymon20000. Going to investigate this now and give an ETA until the end of the day!

**Comment by chrispader** [comment]
@danieldoglas @quinthar started working on an implementation to fix this issue in https://github.com/Expensify/App/pull/38997

I expect to finish this PR tomorrow, if the current implementation approach is what is expected... Tested the PR by manually delaying and deferring Onyx updates, and it works well so far...

**Comment by eh2077** [comment]
@danieldoglas Could you assign me and @hungvu193 here and add the Bug label so BZ team can help take care of eventual payment? Thanks!

**Comment by danieldoglas** [comment]
OK, this was reverted. It caused issue https://github.com/Expensify/App/issues/39650, but also caused crashes in the app as you can see here: https://expensify.slack.com/archives/C049HHMV9SM/p1712264151436019

@chrispader can you investigate those please?

**Comment by chrispader** [comment]
> OK, this was reverted. It caused issue #39650, but also caused crashes in the app as you can see here: https://expensify.slack.com/archives/C049HHMV9SM/p1712264151436019
> 
> @chrispader can you investigate those please?

working on it!

**Comment by danieldoglas** [comment]
That's fake news, we've reverted that PR and we're testing it again.

**Comment by lschurr** [comment]
What's the latest on this one @danieldoglas?

**Comment by danieldoglas** [comment]
Still being tested, it's a tough one to get right :(

**Comment by danieldoglas** [comment]
I mean, it's assigned to someone already @MelvinBot .

**Comment by chrispader** [comment]
@danieldoglas i'm gonna work on the tests today!

**Comment by danieldoglas** [comment]
Hopefully we'll merge this PR again tomorrow, and we won't face any issues this time 🙏🏾

**Comment by lschurr** [comment]
Payment summary:

There were two reviewers on this PR. Both are due $500

- @hungvu193 ([offer in Upwork](https://www.upwork.com/nx/wm/offer/102228448))
- @eh2077 ([offer in Upwork](https://www.upwork.com/nx/wm/offer/102228424))

**Comment by lschurr** [comment]
All paid!
