### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Concierge name shows up differently across users/clients

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38764]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [jpersaud@expensify.com](mailto:jpersaud@expensify.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @justinpersaud 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711045413582239

## Action Performed:
1. Go to desktop and login 
2. Observe how "Concierge" appears
3. Log in to web and check the "concierge" shows up
4. Login to SMS account in web

## Expected Result:
Should show up as "Concierge" everywhere _in product_. It is important that as part of this change we do not revert back to having email notifications come from "Concierge" as the sender. All emails that we currently send from "Expensify Concierge" (concierge@expensify.com) should come from "Expensify" which is being handled [here](https://github.com/Expensify/App/issues/39004) internally and we need to ensure that we don't break any other email logic such as how notifications in rooms or Group DMs are sent.

## Actual Result:
In desktop shows up "Concierge" and web as "Expensify Concierge"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (22)](https://github.com/Expensify/App/assets/38435837/bc765875-354c-4252-b9df-5f56416727cd)

![image (21)](https://github.com/Expensify/App/assets/38435837/1007ada3-4465-442b-aa86-95d72cd5da54)

![image (20)](https://github.com/Expensify/App/assets/38435837/c461c07d-e8cd-4fc8-9f9a-370e6b188a52)

![Screen Shot 2024-03-21 at 2 32 16 PM](https://github.com/Expensify/App/assets/38435837/24282be7-10fb-42d2-bdc0-ff13c7839047)

![Screen Shot 2024-03-21 at 2 29 18 PM](https://github.com/Expensify/App/assets/38435837/44210de8-66a1-4819-9471-e9f3fdf33d3d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01341421c426bb4d52</li>
        <li>Upwork Job ID: 1772648999134048256</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by MitchExpensify** [comment]
Checking what name is expected everywhere here https://expensify.slack.com/archives/C03TQ48KC/p1711404254318999?thread_ts=1699541323.795079&cid=C03TQ48KC

**Comment by MitchExpensify** [comment]
And double checking in #product https://expensify.slack.com/archives/C03U7DCU4/p1711406770617419

**Comment by MitchExpensify** [comment]
Ok update OP to:

> ## Expected Result:
> 
> Should show up as "Concierge" everywhere _in product_. It is important that as part of this change we do not revert back to having emails come from "Concierge" as the sender. Emails should come from "Expensify" and we need to ensure that we don't break any other email logic such as how notifications in rooms or Group DMs are sent.

With regard to which Wave or VIP I think this could fit anywhere as polish and #wave-collect seems like as good a place as any

**Comment by MitchExpensify** [comment]
Can this be handled externally @akinwale ?

**Comment by akinwale** [comment]
@MitchExpensify I believe the frontend changes can be handled externally.

> All emails that we currently send from "Expensify Concierge" should come from "Expensify"

This however, would be a backend change.

**Comment by MitchExpensify** [comment]
Ok cool, maybe its best to split up the issues in that case

**Comment by MitchExpensify** [comment]
Oh good catch @FitseTLT ! Making Internal in that case

**Comment by MitchExpensify** [comment]
This is polish realistically

**Comment by MitchExpensify** [comment]
@akinwale Do you think you'll be able to get to this this week?

**Comment by akinwale** [comment]
@MitchExpensify This was [made internal](https://github.com/Expensify/App/issues/38764#issuecomment-2021882553). Do we want to go ahead with a frontend fix instead?

**Comment by MitchExpensify** [comment]
Ah my mistake, ignore me! @akinwale

**Comment by MitchExpensify** [comment]
Switching to Weekly as this is a polish item

**Comment by MitchExpensify** [comment]
@akinwale checking in here, do you have an ETA on when you might be able to get to this? (It came up recently again [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713384096724079?thread_ts=1713194544.839969&cid=C036QM0SLJK))

**Comment by akinwale** [comment]
> @akinwale checking in here, do you have an ETA on when you might be able to get to this? (It came up recently again [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713384096724079?thread_ts=1713194544.839969&cid=C036QM0SLJK))

@MitchExpensify Referring back to [this comment](https://github.com/Expensify/App/issues/38764#issuecomment-2041998876), but I think we can just go ahead and move forward with a frontend fix if it's urgent instead of having to wait for a backend change. There is already a [proposal](https://github.com/Expensify/App/issues/38764#issuecomment-2020957569) that could work.

**Comment by MitchExpensify** [comment]
Would a backend fix take much longer? Do you have any concerns about going with the frontend option? If backend won't take much longer, and is the better long term solution, I'd lean to that and "doing it right"

**Comment by akinwale** [comment]
> Would a backend fix take much longer @akinwale? Do you have any concerns about going with the frontend option? If backend won't take much longer, and is the better long term solution, I'd lean to that and "doing it right"

@MitchExpensify An internal engineer would be in a better position to provide more insight on this as I am not at all familiar with the backend code.

**Comment by MitchExpensify** [comment]
@akinwale can you please add a  "🎀" to a comment to assign an internal engineer to help us here?

**Comment by akinwale** [comment]
🎀

**Comment by akinwale** [comment]
🎀👀🎀 C+ reviewed.

**Comment by deetergp** [comment]
Will try to dig into this one in the AM.

**Comment by deetergp** [comment]
Have not had a chance to dig into this. Will try looking at it later today,.

**Comment by deetergp** [comment]
Apologies for the lateness on this one. I believe [this issue](https://github.com/Expensify/App/issues/39004) is set to handle the Internal portion of this, and I see that it was picked up by @blimpich yesterday 🎉  It looks like we have [this front end proposal](https://github.com/Expensify/App/issues/38764#issuecomment-2020957569) which @akinwale has approved. Looks like all that's left is to assign @nexarvo and let them get after it.

**Comment by deetergp** [comment]
I will review this PR today.

**Comment by MitchExpensify** [comment]
Reminder set to pay, lets tackle the BZ steps in the meantime @akinwale - Thank you!

**Comment by MitchExpensify** [comment]
**Payment summary:**

- $250 @akinwale requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer)
- $250 @nexarvo requires payment (Needs manual offer from BZ)

**Comment by MitchExpensify** [comment]
Paid and contract ended, thanks @nexarvo! 

@akinwale can you take a look at the BZ steps please?

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
Launch the Expensify app

**Report**
* Open the Expensify Concierge chat.
* Verify that **_Concierge_** is displayed as the name in the report including the header.
* Click on the header.
* In the report details page verify that the display name is shown as **_Concierge_**.

**LHN**
* In the LHN confirm that **_Concierge_** is displayed as the name for the Expensify Concierge chat report.

**Search**
* Click on search icon at top of LHN.
* Search for `Concierge`
* Verify that the display name of the report is **_Concierge_**.

**Composer**
* Open any report
* In the composer, type '@[concierge@expensify.com](mailto:concierge@expensify.com)'
* Verify that the display name for the mention result is **_Concierge_**

Do we agree 👍 or 👎?

**Comment by deetergp** [comment]
Regression steps look good to me.

**Comment by deetergp** [comment]
Regression steps look good to me.

**Comment by MitchExpensify** [comment]
Nice! Issue created to add steps
