### ISSUE TITLE
[Guided Setup Stage 2] Set up the Expensify persona (Phase 2)

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#38769]
## Part of the "wave-collect – Build Stage 2 of Guided Setup" project
Main issue: https://github.com/Expensify/Expensify/issues/356685
Doc section:  https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#heading=h.7w9fxnwcwj0v (and section below)
Project: https://github.com/orgs/Expensify/projects/129

### Feature Description
Set up the new read-only Expensify persona that we'll use for every other guided setup flow.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e1abfe0d6203033</li>
        <li>Upwork Job ID: 1770904783782240256</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

**Comment by francoisl** [comment]
This is all backend work and will be taken care of internally, no need for a C+ here.

**Comment by NikkiWines** [comment]
Draft PR is here - https://github.com/Expensify/App/issues/38769

**Comment by trjExpensify** [comment]
Heads up @NikkiWines, I think you linked this issue! 😅

**Comment by NikkiWines** [comment]
lol, whoops 🙈 Updated

**Comment by trjExpensify** [comment]
Just taking stock of all these issues. This one is still open for this [WebPR](https://github.com/Expensify/Web-Expensify/pull/41728), yeah?

**Comment by NikkiWines** [comment]
Yep, though that's just to follow up with updated tests in web, there's not any new functionality added in that PR

**Comment by trjExpensify** [comment]
Yeah, makes sense. Thanks!

**Comment by NikkiWines** [comment]
I think we can close this out now since https://github.com/Expensify/Web-Expensify/pull/41728 is merged and we're not waiting on any functionality that's dependent on a deploy
