### ISSUE TITLE
[Guided Setup Stage 2] Implement setup tasks auto-completion (Phase 1)

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#38768]
## Part of the "wave-collect – Build Stage 2 of Guided Setup" project
Main issue: https://github.com/Expensify/Expensify/issues/356685
Doc section: https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#heading=h.pq95ck424ina
Project: https://github.com/orgs/Expensify/projects/129

### Feature Description
Make tasks created during guided setup complete themselves based on the corresponding actions the user takes in product.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a40f50141f2aca6</li>
        <li>Upwork Job ID: 1770904769655996416</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

**Comment by francoisl** [comment]
This is all backend work and will be taken care of internally, no need for a C+ here.

**Comment by trjExpensify** [comment]
👋 @NikkiWines @francoisl can we close this issue? The AuthPR hit prod 4 days ago.

**Comment by francoisl** [comment]
The logic is implemented but we still need to create some missing automated tests for this. I have a WIP PR [here](https://github.com/Expensify/Auth/pull/10633), I'll make it resolve this issue when it's merged.

**Comment by francoisl** [comment]
The logic to complete the "Add expense approvals" task was also missing because that feature wasn't released when we wrote the design doc. There's a PR for this in review [here](https://github.com/Expensify/Auth/pull/10647).
We also still need to add the logic to complete the task "Meet your setup specialist" when you schedule a call with Calendly, working on that now.

**Comment by trjExpensify** [comment]
^^ Web PR for that merged, awaiting the next deploy: https://github.com/Expensify/Web-Expensify/pull/41803

**Comment by NikkiWines** [comment]
This can be closed out, as https://github.com/Expensify/Web-Expensify/pull/41803 has been deployed to prod
