### ISSUE TITLE
Receipts submitted on mobile does not appear on web

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38762]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711039730625509

## Action Performed:
1. Submitted receipts on workspace on mobile, requests 
2. Open app in web and look for the receipt submitted on mobile

## Expected Result:
Submitted receipt should appear

## Actual Result:
Receipt does not appear even after deleting local storage and Onyx. On web, there is a gap from 2024-03-18 to today. Whereas on mobile the requests from yesterday (2024-03-20) and 2024-03-19 can be seen.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/38435837/074a5718-5714-46b4-a50b-a561c2abbbdf" width="40%" height="40%">

![image (18)](https://github.com/Expensify/App/assets/38435837/5a96d3ad-9b7e-49ba-b20a-c27c16fc1fff)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
On my testing list

**Comment by alexpensify** [comment]
I sent a team follow-up here: 

https://expensify.slack.com/archives/C049HHMV9SM/p1711567168353479?thread_ts=1711039730.625509&cid=C049HHMV9SM

**Comment by alexpensify** [comment]
## Testing steps: 

1. I scanned a receipt via the mobile application 

![image](https://github.com/Expensify/App/assets/8107070/80409382-f85d-4b77-8666-d67c01a7d817)

2. I went to the website and checked to see if it populated there 

![2024-03-29_09-35-15](https://github.com/Expensify/App/assets/8107070/35a2f453-316e-458c-ba10-edc5fb169575)

3. The scan process completed and it's still populating in the website 

![2024-03-29_09-36-32](https://github.com/Expensify/App/assets/8107070/65028d0f-d600-497e-8eec-73c43614a945)

4. Also, I clicked into the expense to confirm the data is still populating correctly 

![2024-03-29_09-38-24](https://github.com/Expensify/App/assets/8107070/554dac21-c58e-4876-a9e0-001dd384c5dc)

**Comment by alexpensify** [comment]
@joekaufmanexpensify -- I think you are OOO today. I'm going to close for now but happy to chat more next week if I didn't follow the right steps [here](https://github.com/Expensify/App/issues/38762#issuecomment-2027468402). Also, to confirm I was testing on my Android device, so not sure if this might be an iPhone-specific issue but I haven't' seen a widespread issue.
