### ISSUE TITLE
[Guided Setup Stage 2] Create `CompleteGuidedSetup` API command (Phase 1)

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#38767]
## Part of the "wave-collect – Build Stage 2 of Guided Setup" project
Main issue: https://github.com/Expensify/Expensify/issues/356685
Doc section: https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#heading=h.7xvrot9nsoc5
Project: https://github.com/orgs/Expensify/projects/129

### Feature Description
Create a new API command `CompleteGuidedSetup` that will receive the tasks and associated messages from the client, and save them. It will also update the `introSelected` NVP.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01232a523ddcb5e65c</li>
        <li>Upwork Job ID: 1770904754863960064</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

**Comment by francoisl** [comment]
This is all backend work and will be taken care of internally, no need for a C+ here.

**Comment by trjExpensify** [comment]
Looks like this one is done. With all backend PRs, does it need to remain open? CC: @NikkiWines as you might have some context. :)

**Comment by NikkiWines** [comment]
Oops, sorry @trjExpensify, missed your ping. Yes, the CompleteGuidedSetup command logic has been merged so this can be closed.
