### ISSUE TITLE
[HOLD for payment 2024-06-20] [Guided Setup Stage 2] Create Guided Setup messages and tasks from Expensify persona for every other user (Phase 2)

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#38774]
## Part of the "wave-collect – Build Stage 2 of Guided Setup" project
Main issue: https://github.com/Expensify/Expensify/issues/356685
Doc section: https://docs.google.com/document/d/10bhCv6XtzzqEZQ9tzxFwAz4lowgjOhsFqz13BMq6Iu4/edit#bookmark=id.be20bju15zhu
Project: https://github.com/orgs/Expensify/projects/129

### Feature Description
When preparing the tasks and messages for the API command `CompleteGuidedSetup`, alternate between the Concierge account ID and Expensify persona account ID for every other user

cc @barttom 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c10eb14717d5fee</li>
        <li>Upwork Job ID: 1770904841304297472</li>
        <li>Last Price Increase: 2024-03-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by barttom** [comment]
Hello! I'm Bartek from Callstack, an expert contributor group, and I would like to work on this issue.

**Comment by trjExpensify** [comment]
Assigned you!

**Comment by trjExpensify** [comment]
I believe we're prioritising Phase 1 first.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by trjExpensify** [comment]
Assigned you!

**Comment by burczu** [comment]
Hi, I’m Bartek from Callstack and I would like to take over of this issue.

**Comment by trjExpensify** [comment]
Still holding the PR on #38769.

**Comment by trjExpensify** [comment]
Off hold, bumping back to `Daily` priority.

**Comment by burczu** [comment]
@trjExpensify Seems like we need to go back On Hold here in regards to this issue: https://github.com/Expensify/App/issues/41064

**Comment by burczu** [comment]
Just to inform - I'll be ooo the whole next week. Most likely @koko57 will take this issue over from me (she knows all the details etc.).

**Comment by trjExpensify** [comment]
>@trjExpensify Seems like we need to go back On Hold here in regards to this issue: https://github.com/Expensify/App/issues/41064?

Yeah, specifically that's this AuthPR yeah? https://github.com/Expensify/Auth/pull/10675

**Comment by trjExpensify** [comment]
Auth PR is merged and deployed. 👍

**Comment by koko57** [comment]
@trjExpensify I've resolved some conflicts and applied one minor change to the PR. I think the rest is ready to be reviewed after this PR https://github.com/Expensify/Auth/pull/10675 hits the prod. 

I cannot open this PR, but I'm opening a draft from my fork with the same changes, let me know when to open it for the review. 

Me and my team will be OOO tomorrow (05/01), so I will be able to address the comments on Thursday.

**Comment by trjExpensify** [comment]
Thanks! Can you open it for review? I'll add the hold in the title for the AuthPR in the meantime.

**Comment by trjExpensify** [comment]
We're still held here, Melv.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open the app with an entire new user.
2. Complete the onboarding flow.
3. Repeat steps 1-2 a few times (create a few new users).
4. Verify that after onboarding flow you're redirected either to the Concierge chat or Expensify persona

Do we agree 👍 or 👎

**Comment by trjExpensify** [comment]
Confirming payment as follows:

- $250 to @sobitneupane for the C+ review. Feel free to go ahead and request! 

As for the regression tests, we'll add them centrally. I got the ball rolling on that here: https://github.com/Expensify/Expensify/issues/406205

Go ahead and request, Sobit!

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
