### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Skeleton is displayed when navigating to a transaction thread created offline

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#38781]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.55-2
**Reproducible in staging?:** no
**Reproducible in production?:** no
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711054985550349

## Action Performed:
1. Create a chat with someone online
2. Request money from them then navigate to the money report (click on the preview).
3. Go offline and request again from the money report.
4. Try to navigate to the transaction thread of the request created offline.

## Expected Result:
it should display the transaction thread where we can edit the fields

## Actual Result:
It shows an infinite skeleton loader

## Workaround:
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/47436092/bce21db4-e334-40bf-a2db-b37ba73bb573

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01694ea7e3c07bf01d</li>
        <li>Upwork Job ID: 1771247582016843776</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment]
this is reproducible on main but not staging, so will be a deploy blocker once we ship the current checklist. For that reason, I'm not marking it as external, but going to ask @perunt to investigate a fix

**Comment by situchan** [comment]
Happy to review this if C+ is needed

**Comment by roryabraham** [comment]
I found that the optimistic IOU action has a childReportID field, that does point to an optimistic chat report. So that's all as expected

**Comment by roryabraham** [comment]
`shouldShowSkeleton` is getting stuck as `true` [here](https://github.com/Expensify/App/blob/9e0304ef91c4b0634ce21bf742b305e8e61ca4a8/src/pages/home/ReportScreen.tsx#L334)

![image](https://github.com/Expensify/App/assets/47436092/2447ae2b-b740-4f20-88ff-f6b5f6697192)

**Comment by roryabraham** [comment]
ok, it appears that the `reportMetadata` for the report in question is somehow getting deleted, and since `isLoadingInitialReportActions` defaults to `true` in `ReportScreen`, it's getting stuck there

**Comment by roryabraham** [comment]
Did `git checkout b3068864afeaedd448cb59107629fc5cb67fe009~1` and verified this is not reproducible pre-comment-linking

**Comment by roryabraham** [comment]
Interestingly `isLoadingInitialReportActions` was getting stuck on `true` before, it just didn't matter because we weren't relying on it to be correct:

![image](https://github.com/Expensify/App/assets/47436092/315a6068-f916-41bb-89c5-d567605ae223)

**Comment by roryabraham** [comment]
and, I suppose it kind of makes sense that it would get stuck as `true` when we're offline, because `OpenReport` sets it to `true` in its `optimisticData`, then to false in its `successData` + `failureData`. So it's stuck as true, even though we're not really loading anything while we're offline

**Comment by youssef-lr** [comment]
>Interestingly isLoadingInitialReportActions was getting stuck on true before, it just didn't matter because we weren't relying on it to be correct

What has changed now?

**Comment by roryabraham** [comment]
It's used in ReportScreen as part of `shouldShowSkeleton`: https://github.com/Expensify/App/blob/7e4a4383a3b7474a15aaba210711a618cd897cbb/src/pages/home/ReportScreen.tsx#L334-L335

**Comment by nkdengineer** [comment]
@roryabraham What do you think about my proposal?

**Comment by roryabraham** [comment]
thanks @nkdengineer, good investigation. Your proposal LGTM 👍🏼

**Comment by roryabraham** [comment]
I did a bit of extra refactoring to rename some variables and improve some comments in https://github.com/Expensify/App/pull/38825/files. If possible can I request that you include these changes in your PRs as well? 🙇🏼

**Comment by nkdengineer** [comment]
>  If possible can I request that you include these changes in your PRs as well? 🙇🏼

@roryabraham Sure.

**Comment by roryabraham** [comment]
since https://github.com/Expensify/App/pull/30269 is now on staging, I'm marking this as a deploy blocker

**Comment by roryabraham** [comment]
@nkdengineer let me know when I can expect a PR. Thanks!

**Comment by roryabraham** [comment]
marking this as external to generate upwork jobs

**Comment by nkdengineer** [comment]
@roryabraham @situchan the PR is ready for review.

**Comment by roryabraham** [comment]
Verified this is fixed:

https://github.com/Expensify/App/assets/47436092/27ede9aa-a532-4141-bb36-563df9426c3a

so now all that's needed is payment:

- $500 to @nkdengineer for the PR
- $500 to @situchan for the review

**Comment by lschurr** [comment]
Great! PR is here: https://github.com/Expensify/App/pull/38829 - We'll issue payments 7 days after it's deployed to Prod.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @nkdengineer $500
- Contributor+: @situchan $500

**Comment by lschurr** [comment]
@nkdengineer - Can you send me your Upwork profile or apply to the job directly here? https://www.upwork.com/ab/applicants/1771247582016843776

**Comment by nkdengineer** [comment]
@lschurr Below's my Upwork profile!

https://www.upwork.com/freelancers/~0134d0b74faef1a5ac

**Comment by lschurr** [comment]
Great! I sent the offer in Upwork @nkdengineer - https://www.upwork.com/nx/wm/offer/101804520

**Comment by lschurr** [comment]
This is complete.
