### ISSUE TITLE
[HOLD for payment 2024-04-05] [Distance rates] Immediate editing of freshly created rate fails - rates are not being created with correct optimistic name

### ISSUE THREAD

**Issue by MrMuzyk** [Expensify/App#38798]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Create distance rates with same rate value and try to quickly disable last created rate

## Expected Result:
1. User can edit created rate immediately without any issues

## Actual Result:
1. Rate is not being edited and error is thrown

## Workaround:
Wait a few seconds before editing a rate after it's created

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/23487612/b73f056e-df1d-44e2-9d23-76c1d76ae0c7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MrMuzyk** [comment]
As mentioned in one of the previous [PRs](https://github.com/Expensify/App/pull/38237#issuecomment-2012634730) for distance rates this will be a followup that fixes it

**Comment by luacmartins** [comment]
@trjExpensify we need to pay @c3024 for the PR review

**Comment by trjExpensify** [comment]
Cool! Payment summary as follows: 

- $500 to @c3024 for the C+ review - offer sent

**Comment by trjExpensify** [comment]
Paid!
