### ISSUE TITLE
[HOLD on ISSUE #34616] Web - App crashes when open /participants link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38816]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Paste https://staging.new.expensify.com/request/new/participants
into browser address or send it to any report

## Expected Result:
Link should lead to participants page

## Actual Result:
App crashes when open https://staging.new.expensify.com/request/new/participants

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4a40a7f8-fd55-41c0-ba7b-66deea463014

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Held

**Comment by muttmuure** [comment]
Held

**Comment by muttmuure** [comment]
Held

**Comment by muttmuure** [comment]
Great! Thanks
