### ISSUE TITLE
[HOLD for payment 2024-04-05] [Simplified Collect][Distance rates] - Error shows up when disabling and renaming distance rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38815]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is admin of Collect workspace
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to Distance rates
4. Add a distance rate
5. Click on the distance rate added in Step 4
6. Toggle off the Enable rate button
7. Click Rate and edit the rate

## Expected Result:
App will save the new settings made in Step 6 and 7

## Actual Result:
Error shows up when disabling and renaming distance rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3cd2c32c-392e-4f7b-a2b3-c4b910f6b219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by lanitochka17** [comment]
@stitesExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment]
This is not a blocker since this feature is not available to users yet.

**Comment by luacmartins** [comment]
cc @MrMuzyk

**Comment by luacmartins** [comment]
This is the error that I get. This was already fixed [here](https://github.com/Expensify/App/pull/38799)
![Screenshot 2024-03-22 at 4 47 14 PM](https://github.com/Expensify/App/assets/22219519/2126be6a-b948-4637-8707-5dd6ea636db1)

**Comment by luacmartins** [comment]
This is done
