### ISSUE TITLE
Avatar - Profile avatar is broken when open in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38817]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+balto913@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open staging.new.expensify.com
2. Login with any account with custom profile avatar
3. After login turn off internet connection
4. Go to Profile> Click on profile photo> Select View photo

## Expected Result:
Profile avatar should be displayed

## Actual Result:
Profile avatar is broken when open in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/65d33f2f-f686-4eb1-be7e-80b960387e3e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
This is not a bug. On production all one sees is an endless spinner, so the placeholder is an improvement over that.
![Screenshot 2024-03-22 at 2 00 25 PM](https://github.com/Expensify/App/assets/4741899/cbfdbe83-4d90-4ed5-a6e0-f5b2ab9ee3d2)
