### ISSUE TITLE
Track Expense – Description grayed out when create Scan Track Expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Click on FAB Button
3. Select Track Expense
4. Go to Scan tab
5. Upload a receipt
6. Click on Track Expense at the confirmation step

## Expected Result:
Description field not grayed out when create Scan Track Expense at the confirmation step

## Actual Result:
Description field grayed out when create Scan Track Expense at the confirmation step

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c372d44b-e462-4191-a2df-47acdb058317

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@amyevans  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by amyevans** [comment]
This is a minor issue on a new feature still under beta, so NAB.

@shubham1206agra do you want to take this on, or should we open it up externally @thienlnam? Also cc @ishpaul777

**Comment by thienlnam** [comment]
Yeah, if this is also the same for the request money flow then we might not need to do anything here

**Comment by amyevans** [comment]
Ah good catch, thanks! Agreed that we can close.
