### ISSUE TITLE
[HOLD for payment 2024-04-05] [Simplified Collect][Taxes] - Tax value is blank when returning online after editing it offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38827]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is admin of Collect workspace
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to Taxes
4. Go offline
5. Add a tax rate
6. Click on the tax rate
7. Edit both tax name and rate
8. Go online
9. Click on the tax rate

## Expected Result:
The edited tax value in Step 7 will be saved

## Actual Result:
The tax value is blank when returning online after editing it offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e81e40f4-13e3-4668-b322-c6c22d557bf6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment]
Yes, we updated the param name in the API and it'll be updated in App in [this PR](https://github.com/Expensify/App/pull/38733) cc @kosmydel

**Comment by luacmartins** [comment]
Added this issue to the list of fixed issues of https://github.com/Expensify/App/pull/38733

**Comment by luacmartins** [comment]
It seems like we'll handle payment for this one in https://github.com/Expensify/App/issues/38499. So I think we're good to close here
