### ISSUE TITLE
Android - Track expenses - Deleting track expense showing skeleton in preview.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38820]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab--Track expense---manual
3. Enter amount and tap next
4. Tap track expense
5. Open track expense to open details page
6. Delete track expense

## Expected Result:
Deleting track expense must not show skeleton.

## Actual Result:
Deleting track expense showing skeleton in preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3f9f0f7a-6219-47e1-92ab-7cacbee78ba0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Thanks @shubham1206agra! Removing the deploy blocker label since it's a new feature

**Comment by marcochavezf** [comment]
I will put it on hold for https://github.com/Expensify/App/issues/38698

**Comment by marcochavezf** [comment]
https://github.com/Expensify/App/issues/38698 fixed, applying retest-weekly

**Comment by marcochavezf** [comment]
Waiting for testing

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
