### ISSUE TITLE
Sign up - Hmmm its not here page is displayed for a moment on sign up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38826]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to sing up page
2. Sign up with a new account

## Expected Result:
Hmmm its not here page shouldn't be displayed momentarily

## Actual Result:
Hmmm its not here page is displayed momentarily

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e99e61e0-8810-4ed8-9e82-370d0e093bf9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@deetergp  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Members added and deleted offline are grayed out but strikethrough is not applied

### What is the root cause of that problem?
Regression from https://github.com/Expensify/App/pull/30269

After we sign in, `reportIDFromRoute` is `0` string and then the not found page display with this condition.

https://github.com/Expensify/App/blob/08fca15f70a54e339a9c361800f3f85bc43ea8cf/src/pages/home/ReportScreen.tsx#L538
### What changes do you think we should make in order to solve the problem?

We should revert this check to the previous because we need to check reportID from `report` to know that we're getting the report or not

```
const reportIDFromParams = report?.reportID;

// eslint-disable-next-line rulesdir/no-negated-variables
const shouldShowNotFoundPage = useMemo(
    (): boolean =>
        (!wasReportAccessibleRef.current &&
            !firstRenderRef.current &&
            !report.reportID &&
            !isOptimisticDelete &&
            !reportMetadata?.isLoadingInitialReportActions &&
            !isLoading &&
            !userLeavingStatus) ||
        shouldHideReport ||
        (!!reportIDFromParams && !ReportUtils.isValidReportIDFromPath(reportIDFromParams)),
    [report, reportMetadata, isLoading, shouldHideReport, isOptimisticDelete, userLeavingStatus, reportIDFromParams],
);
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by roryabraham** [comment]
> I think we just need to seperate !isloading to a seperate required conditional

Tried this, doesn't appear to work

**Comment by roryabraham** [comment]
exactly, got it. Putting up a PR now. @ishpaul777 you can review as C+ since this was a regression from Comment Linking.

**Comment by roryabraham** [comment]
PR is ready: https://github.com/Expensify/App/pull/38856

**Comment by nkdengineer** [comment]
@roryabraham https://github.com/Expensify/App/pull/38856 a regression of this PR

Infinite loading if we enter a reportID that is one in this array `['', 'null', '0']`. for invalid reportID, `OpenReport` API isn't called and then `isLoading` is always `true`,
```
const isLoading = !ReportUtils.isValidReportIDFromPath(reportIDFromRoute) ||
```

https://github.com/Expensify/App/assets/161821005/282ebcb7-aba8-43ab-b5cb-1e5474fc328d


I think each wrap logic in `shouldShowNotFoundPage` is added for some reason and we shouldn't wrap this with shouldShowSkeleton

As I mentioned in my proposal, the previous logic is added from this PR https://github.com/Expensify/App/pull/33394, and we should bring this logic back. It can fix the current RCA and can prevent from causing other regressions.

**Comment by nkdengineer** [comment]
@roryabraham  There is no new issue for that but it's a known issue here https://github.com/Expensify/App/issues/32651 that is fixed. But after the PR here, it is back.

**Comment by bernhardoj** [comment]
It also causes this infinite loading issue https://github.com/Expensify/App/issues/39090

**Comment by garrettmknight** [comment]
@roryabraham shall we reopen this one to fix the regression?
