### ISSUE TITLE
[HOLD for payment 2024-04-09] [$250] Web - Video - Expand video button isn't highlighted when hovered on

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38841]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36945
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to a conversation
2. Attach a video.
3. Play the video. The expand video button appears alongside the video
4. Hover the mouse icon on the expand button

## Expected Result:
Expand video button is highlighted when hovered on as other buttons like pause, full screen etc.

## Actual Result:
Expand video button is not highlighted when hovered on

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/27f06830-49b7-45c1-af0d-a3cb0604c89c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019dec26faa8f28e37</li>
        <li>Upwork Job ID: 1772265129297416192</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by sonialiap** [comment]
Payment summary
- @sobitneupane $250 - please request in NewDot and [complete the checklist](https://github.com/Expensify/App/issues/38841#issuecomment-2031689614)
- @GandalfGwaihir $250 - paid ✔️

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/36945
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/36945#issuecomment-2049314450
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This should have been caught in the previous PR review. We don't need to add a new checklist.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Propsal**

1. Navigate to a conversation
2. Attach a video.
3. Play the video. The expand video button appears alongside the video
4. Hover the mouse icon on the expand button
5. Verify that the expand video button is highlighted when hovered on as other buttons like pause.

Do we agree 👍 or 👎

**Comment by sonialiap** [comment]
Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
