### ISSUE TITLE
WS invite - Back button from workspace list leads to not here page after tapping invite link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38842]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Copy workspace invite link from another user (https://staging.new.expensify.com/settings/workspaces/0E665F4C2DAE577C/join?email=applausetester+kh210301@applause.expensifail.com)
3. Paste the link in any chat.
4, Tap on the link.
5. Tap on the back button.

## Expected Result:
User will be redirected to chat.

## Actual Result:
User is redirected to not here page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4f173b94-f7b4-4ea9-a9c5-6ab3fbed0ecc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by kadiealexander** [comment]
Closing as this is not a priority bug.
