### ISSUE TITLE
Payment issue for https://github.com/Expensify/react-native-onyx/pull/446

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#38840]
Payment for the below @situchan reviewed. Compensation is $250
- https://github.com/Expensify/react-native-onyx/pull/446

**Comment by mallenexpensify** [comment]
@situchan , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01ea9502881e62b822

**Comment by situchan** [comment]
Accepted thanks

**Comment by mallenexpensify** [comment]
Contributor+: @situchan paid $250 via Upwork
