### ISSUE TITLE
[$500] Distance - Distance editor still shows new waypoint after dismissing the editor without saving

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4444296
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a distance request
4. Go to request details page
5. Click Distance
6. Add another waypoint
7. Click outside the distance editor to dimiss it instead of saving the edit
8. Click Distance

## Expected Result:
The distance editor will not show the new waypoint added in Step 6 because the edit is not saved

## Actual Result:
The distance editor still shows the new waypoint despite not saving the edit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a0238080-eef4-4671-b3f9-672df9b059d5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015105b9d7569afcfa</li>
        <li>Upwork Job ID: 1772360813317861376</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Contributor | 0</li>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment]
I don't think this need to block the deploy.

**Comment by greg-schroeder** [comment]
Checking to see if that's the case, and will close if so as this is already being resolved.

**Comment by greg-schroeder** [comment]
Distance is #wave-collect in case this remains open

**Comment by DylanDylann** [comment]
Fixing [here](https://github.com/Expensify/App/pull/38911)

**Comment by cubuspl42** [comment]
@DylanDylann As https://github.com/Expensify/App/pull/38911 is now closed, would you link the new PR, possibly draft?

**Comment by DylanDylann** [comment]
@cubuspl42 It is a bit complicated, I will raise PR today

**Comment by cubuspl42** [comment]
We have a draft PR, Melvin; there won't be any proposals

**Comment by greg-schroeder** [comment]
Work on linked PR continues

**Comment by greg-schroeder** [comment]
Looks like @cubuspl42 and @puneetlath were involved in the linked PR, so assigning you both

**Comment by greg-schroeder** [comment]
Looks like [this PR](https://github.com/Expensify/App/pull/39144) is fixing 3 separate GHs:

https://github.com/Expensify/App/issues/35173
https://github.com/Expensify/App/issues/38853
https://github.com/Expensify/App/issues/38864

**Comment by greg-schroeder** [comment]
Hmm - how are we handling payments here as there are multiple regressions involved. :/ I'm going to cancel these automatic offers for now so we can get on the same page.

**Comment by cubuspl42** [comment]
@greg-schroeder **This** issue can be closed, from my perspective. The original issue is...

- https://github.com/Expensify/App/issues/34610

**Comment by greg-schroeder** [comment]
Okay got it - yeah, I think this is the regression issue so we'll handle payments in the original. If anyone disagrees, please reopen this.
