### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] [HOLD #38375][Simplified Collect][Taxes] "Custom tax name" does not change the name repeatedly

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38859]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/38732

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Preconditions:
Configure the OldDot new expensifail account, create a Collect workspace with workspace chat enabled https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0

Steps:
1. Open https://staging.new.expensify.com/
2. Log in to the configured account
3. Navigate to Workspace settings - Taxes - Settings - Custom tax name
4. Type in any name
5. Click on the "Save" button
6. Retry steps 3-5

## Expected Result:
"Custom tax name" should change the name when the new name is saved again

## Actual Result:
"Custom tax name" does not change the name repeatedly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/900f4a0b-7c94-4148-8b62-8357a12c643b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1d92fc91f1c59c3</li>
        <li>Upwork Job ID: 1772211059605901312</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@dylanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/2c009ac0-e8cf-4bb3-bb8f-8b116c8c552d

**Comment by dylanexpensify** [comment]
Ah @nkuoch coming from [this](https://expensify.slack.com/archives/C036QM0SLJK/p1711362786361519?thread_ts=1710800286.055929&cid=C036QM0SLJK), looks like we may be good actually.

**Comment by dylanexpensify** [comment]
Removing blocker and waiting to retest once [this PR](https://github.com/Expensify/App/pull/38375#issuecomment-2016012721) is on staging

**Comment by luacmartins** [comment]
I confirmed that this issued is solved on main. Just waiting for the deploy now.

**Comment by luacmartins** [comment]
Just pending payment

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: $500

Please request/apply!

**Comment by c3024** [comment]
@dylanexpensify applied on Upwork. Thanks.

**Comment by c3024** [comment]
accepted!

**Comment by dylanexpensify** [comment]
Done!
