### ISSUE TITLE
[HOLD for payment 2024-04-15] Remove comment linking beta

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#38858]
### Problem

We build comment linking, but the menu item to actual copy links to reportActions is hidden behind a beta.

### Solution

Add all users to the beta, then remove the beta.

**Comment by hayata-suenaga** [comment]
taking over this issue as Rory gave it to me 😄

**Comment by roryabraham** [comment]
app PR merged, once it hits prod we'll need to follow-up with removing the beta from the back-end as well

**Comment by abekkala** [comment]
@hayata-suenaga @roryabraham what is the payment amount for this PR review? $250?

**Comment by roryabraham** [comment]
yep, $250

**Comment by abekkala** [comment]
@getusha [offer sent](https://www.upwork.com/nx/wm/offer/new/1006681983)!

**Comment by abekkala** [comment]
@getusha payment sent and contract ended - thank you! 🎉
