### ISSUE TITLE
[HOLD for payment 2024-05-02] Distance - Map reloads with "Route pending" when clicking Save button without any changes

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Create a distance request.
4. Go to request details page.
5. Click Distance.
6. Click Save button without editing the addresses.

## Expected Result:
Map will not reload. Distance row will not show Route pending (production behavior).

## Actual Result:
Map reloads. Distance row shows Route pending when no edit is made to distance.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4f0e0228-2897-400a-83f2-7f3242840638

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-bills

**Comment by puneetlath** [comment]
Assigning @DylanDylann as they are working on this as a regression from their PR.

**Comment by puneetlath** [comment]
@DylanDylann how's this going?

**Comment by DylanDylann** [comment]
The PR will be ready on April 2, 2024. Sorry for my delay because of a bit complicated

**Comment by mountiny** [comment]
Seems to not have been fixed per this comment https://github.com/Expensify/App/issues/40392#issuecomment-2067106921

**Comment by DylanDylann** [comment]
@mountiny I also see that this bug can be reproduced. But it is the regression from [this PR](https://github.com/Expensify/App/pull/39910)

@kosmydel Could you explain why you update the key from ${ONYXKEYS.COLLECTION.TRANSACTION_BACKUP} to ${ONYXKEYS.COLLECTION.TRANSACTION_DRAFT} 

<img width="1512" alt="Screenshot 2024-04-21 at 11 27 36" src="https://github.com/Expensify/App/assets/141406735/7b81a52c-63e8-4844-a2e1-a5e9b9773d92">

**Comment by DylanDylann** [comment]
@kosmydel @ishpaul777  If it is a mistake, we should create a quick PR to resolve this problem

cc @mountiny

**Comment by mountiny** [comment]
Asked Jakub, thanks

**Comment by kosmydel** [comment]
> @kosmydel @ishpaul777 If it is a mistake, we should create a quick PR to resolve this problem

Hey, thanks for reporting! I noticed that the `_DRAFT` was introduced in [this commit](https://github.com/software-mansion-labs/expensify-app-fork/commit/8a16ce750deae87332084223344482dd724522d1). This appears to be a result of an incorrect conflict merge. I will look into it and prepare a pull request with the necessary changes.

**Comment by puneetlath** [comment]
I believe this is a regression, so no new payments needed, correct?

**Comment by puneetlath** [comment]
Going to close, but @DylanDylann comment if I'm mistaken about the above.
