### ISSUE TITLE
[HOLD for payment 2024-04-05] Expense - Expense preview shows skeleton loading after paying with Expensify

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38869]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** around **Reproducible in production?:**
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Admin and member are in the same workspace
- The workspace has a bank account set up
- Member does not have any bank account
1. Go to staging.new.expensify.com
2. [Member] Request money from the workspace chat
3. [Admin] Go to workspace chat with member
4. [Admin] Click on the expense preview
5. [Admin] Click Pay with Expensify
6. [Admin] Go back to 1:1 DM and return to expense preview to see the skeleton loading if needed

## Expected Result:
In Step 5, after clicking Pay with Expensify, the page will not be blank or show skeleton loading

## Actual Result:
In Step 5, after clicking Pay with Expensify, the page shows skeleton loading above the "settling up" message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6983b3c1-1607-460e-a2d1-099c5e1f1815

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by luacmartins** [comment]
Looking at this one now

**Comment by luacmartins** [comment]
This is caused by calling `GetOlderActions` in a loop

**Comment by luacmartins** [comment]
Discussing here - https://expensify.slack.com/archives/C01GTK53T8Q/p1711394667108379

**Comment by roryabraham** [comment]
I'm not able to reproduce, but for an unrelated reason. I'm not able to get past the Expense report submission in a collect workspace. Going to try with fresh accounts + a free workspace

**Comment by roryabraham** [comment]
I'm still struggling with this one - I reproduced it once but am running into two unrelated issues, reported [here](https://expensify.slack.com/archives/C03TQ48KC/p1711414373521289)

**Comment by perunt** [comment]
I've added a test bank account and was wondering, can we use it to make payments?

I'm pretty sure the issue might be in `getContinuousReportActionChain`. It looks like after making a payment, this action either moves or changes the type of the reportAction. 

@lanitochka17, could you help us out by sharing some logs? If you could add `console.log('allReportActions', JSON.stringify(sortedReportActions))` in the [right spot](https://github.com/Expensify/App/blob/main/src/libs/ReportActionsUtils.ts#L264) and send over the details, that would really help me pinpoint the issue.

**Comment by luacmartins** [comment]
Hmm I was trying to get the logs asked above, but I can't reproduce the issue right now. Gonna keep trying.

**Comment by luacmartins** [comment]
Ok, managed to reproduce again. Here are the logs @perunt 

```
allReportActions [{"actionName":"REIMBURSEMENTQUEUED","actorAccountID":2,"automatic":false,"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_3.png","created":"2024-03-26 15:16:30.139","isAttachment":false,"lastModified":"2024-03-26 15:16:30.139","message":[{"type":"TEXT","style":"strong","text":"You"},{"type":"TEXT","style":"normal","text":" queued this report for reimbursement (paid via bank account). Reimbursement is on hold until "},{"type":"TEXT","style":"strong","text":"cmartins+2@expensifail.com"},{"type":"TEXT","style":"normal","text":" adds a bank account"}],"originalMessage":{"IOUReportID":1214606904707134,"amount":75,"bankAccountID":7,"fundID":0,"lastModified":"2024-03-26 15:16:30.139","originalCaller":"PayMoneyRequest","paymentMethod":"ach_debit","paymentType":"ACH","reimburserID":2,"reportActionID":3459719543132819500},"person":[{"type":"TEXT","style":"strong","text":"cmartins@expensifail.com"}],"previousReportActionID":"1827888261995192039","reportActionID":"6661925061748177534","reportActionTimestamp":1711466190139,"sequenceNumber":5,"shouldShow":true,"timestamp":1711466190,"whisperedToAccountIDs":[],"actorEmail":"cmartins@expensifail.com"},{"actionName":"IOU","actorAccountID":2,"automatic":false,"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_3.png","isAttachment":false,"originalMessage":{"amount":75,"currency":"USD","IOUReportID":"1214606904707134","type":"pay","paymentType":"ACH"},"message":[{"html":"paid $0.75 with Expensify","text":"paid $0.75 with Expensify","isEdited":false,"type":"COMMENT"}],"person":[{"style":"strong","text":"cmartins@expensifail.com","type":"TEXT"}],"reportActionID":"3459719543132819571","shouldShow":true,"created":"2024-03-26 15:16:29.524","whisperedToAccountIDs":[]},{"person":[{"type":"TEXT","style":"strong","text":"Concierge"}],"actorAccountID":2,"message":[{"type":"TEXT","style":"normal","text":"Reimbursement blocked: We're waiting for your company to update their business bank account."}],"originalMessage":{"automaticAction":true,"lastModified":"2024-03-25 20:31:31.595"},"avatar":"","created":"2024-03-25 20:31:31.595","timestamp":1711398691,"reportActionTimestamp":1711398691595,"automatic":true,"actionName":"OUTDATEDBANKACCOUNT","shouldShow":true,"reportActionID":"1827888261995192039","previousReportActionID":"3681167035629397809","lastModified":"2024-03-25 20:31:31.595","whisperedToAccountIDs":[],"actorEmail":"cmartins@expensifail.com"},{"person":[{"type":"TEXT","style":"strong","text":"cmartins@expensifail.com"}],"actorAccountID":2,"message":[{"type":"COMMENT","html":"approved $0.75","text":"approved $0.75","isEdited":false,"whisperedTo":[],"isDeletedParentAction":false,"deleted":"","reactions":[]}],"originalMessage":{"IOUReportID":1214606904707134,"amount":75,"currency":"USD","lastModified":"2024-03-25 20:31:31.487"},"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_3.png","created":"2024-03-25 20:31:31.487","timestamp":1711398691,"reportActionTimestamp":1711398691487,"automatic":false,"actionName":"APPROVED","shouldShow":true,"reportActionID":"3681167035629397809","previousReportActionID":"759212220634693227","lastModified":"2024-03-25 20:31:31.487","whisperedToAccountIDs":[],"actorEmail":"cmartins@expensifail.com"},{"person":[{"type":"TEXT","style":"strong","text":"cmartins+2@expensifail.com"}],"actorAccountID":705,"message":[{"type":"TEXT","style":"strong","text":"cmartins+2@expensifail.com"},{"type":"TEXT","style":"normal","text":" submitted this report"},{"type":"TEXT","style":"normal","text":" to "},{"type":"TEXT","style":"strong","text":"you"}],"originalMessage":{"cc":"","hasExternalComment":false,"lastModified":"2024-03-25 20:05:55.473","message":"","to":"cmartins@expensifail.com","workflow":"BASIC"},"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_10.png","created":"2024-03-25 20:05:55.473","timestamp":1711397155,"reportActionTimestamp":1711397155473,"automatic":false,"actionName":"SUBMITTED","shouldShow":true,"reportActionID":"759212220634693227","previousReportActionID":"4258134669701620864","lastModified":"2024-03-25 20:05:55.473","whisperedToAccountIDs":[],"actorEmail":"cmartins+2@expensifail.com"},{"person":[{"type":"TEXT","style":"strong","text":"cmartins+2@expensifail.com"}],"actorAccountID":705,"message":[{"type":"COMMENT","html":"CA$1.00 request","text":"CA$1.00 request","isEdited":false,"whisperedTo":[],"isDeletedParentAction":false,"deleted":"","reactions":[]}],"originalMessage":{"IOUReportID":1214606904707134,"IOUTransactionID":"7093758477670296768","amount":100,"comment":"","currency":"CAD","lastModified":"2024-03-25 20:05:52.945","participantAccountIDs":[705,0],"type":"create"},"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_10.png","created":"2024-03-25 20:05:52.945","timestamp":1711397152,"reportActionTimestamp":1711397152945,"automatic":false,"actionName":"IOU","shouldShow":true,"reportActionID":"4258134669701620864","previousReportActionID":"4154332254083280327","lastModified":"2024-03-25 20:05:52.945","whisperedToAccountIDs":[],"childReportID":7207016927163148,"childType":"chat","childReportNotificationPreference":"hidden","actorEmail":"cmartins+2@expensifail.com"},{"reportActionID":"4154332254083280327","previousReportActionID":"0","actionName":"CREATED","created":"2024-03-25 20:05:52.942","reportActionTimestamp":1711397152942,"avatar":"https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_10.png","message":[{"type":"TEXT","style":"strong","text":"cmartins+2@expensifail.com"},{"type":"TEXT","style":"normal","text":" created this report"}],"person":[{"type":"TEXT","style":"strong","text":"cmartins+2@expensifail.com"}],"automatic":false,"sequenceNumber":0,"shouldShow":true,"lastModified":"2024-03-25 20:05:52.942"}]
```

**Comment by luacmartins** [comment]
>I've added a test bank account and was wondering, can we use it to make payments?

You could, but you'd have funds debited from it, but as long as you're paying me I'm cool with that 😄 

>I'm pretty sure the issue might be in getContinuousReportActionChain. It looks like after making a payment, this action either moves or changes the type of the reportAction.

Yes, that's where I've traced it down to as well. I'm not too sure what's wrong with it yet, but maybe the logs above might help.

**Comment by luacmartins** [comment]
This is done!
