### ISSUE TITLE
Taxes - Error shows up when disabling tax rate

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38866]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is admin of Collect workspace.
- Tax settings (Tax custom name, default taxes) are blank.
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Taxes.
4. Add a tax rate
5. Click on the tax rate.
6. Toggle off Enable rate.

## Expected Result:
The rate is disabled without issue.

## Actual Result:
Error shows up when disabling tax rate.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0e4b2567-db84-4829-8738-cc71cfec336b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to  #wave-control

**Comment by Gonals** [comment]
Taking a look at this

**Comment by Gonals** [comment]
I think this is fine. We should not be able to remove the tax if there is no default, and, in the current flow, we create a default when enabling taxes, so I think we are fine.
