### ISSUE TITLE
Track expense-Scan track expense shows no option to enter details manually

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38868]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap fab --- track expense---Scan
3. Upload an image
4. Tap track expense
5. Open the track expense to view track expense detail page
6. Note in header mentioned, check back later or enter details now but no option is shown to enter amount and other details

## Expected Result:
Scan track expense must shows options to enter details manually.

## Actual Result:
Scan track expense shows no option to enter details manually.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7c06b7ac-7562-4d7a-a0b5-45ba1d3cd452

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.



We think this issue might be related to the #vip-vsb.

**Comment by srikarparsi** [comment]
Yeah, looks like this is expected for now based on this [PR](https://github.com/Expensify/App/pull/37282). Issue for it is already up [here](https://github.com/Expensify/App/issues/38699). Closing this out but @thienlnam please lmk if I'm missing something
