### ISSUE TITLE
Image MD - Download icon on image view from image mark down opens image in a new tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37566
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send an image from gallery
4. Send a message with image mark down. Example:

An inline image and some text ![off](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
)

5. Click on the image sent from gallery
6. Click Download
7. Note that it shows download destination prompt
8. Click on the image from image mark down
9. Click Download

## Expected Result:
Clicking Download on image view from image mark down will show download destination prompt

## Actual Result:
Clicking Download on image view from image mark down opens the image in another tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6e870e2a-bc75-46db-bbd2-779b7a99bd9e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@pecanoro  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by situchan** [comment]
This is expected behavior.
cc: @kidroca

**Comment by pecanoro** [comment]
I am not sure how to send an inline image with markdown, using this does not seem to work:

```
An inline image and some text ![off](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)
```

**Comment by pecanoro** [comment]
Ok, I checked the original PR and I think I was copying and pasting somehow in a strange way. I also check the original description and yeah, this is expected so closing
