### ISSUE TITLE
[$500] IOU - IOU Detail Scrolls When Opened

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38874]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on FAB > Request Money.
2. Navigate to Distance, add start and end points, then click Next.
3. Select Workspace, then click on Request Money.
4. Go to IOU and observe that the IOU detail is scrolled.

## Expected Result:
The IOU detail should not scroll.

## Actual Result:
The IOU detail is scrolled.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fc61fd20-616c-4d3d-9549-1a1ca99387d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01524a61d25a6420ab</li>
        <li>Upwork Job ID: 1772482477086314496</li>
        <li>Last Price Increase: 2024-03-26</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by stitesExpensify** [comment]
To be clear, the problem isn't that the page is "Scrolling", it's that there is no top margin so the button in the top left can't be clicked, right?

**Comment by stitesExpensify** [comment]
And if that is the case, how does that work on desktop?

**Comment by yuwenmemon** [comment]
As discussed here, no longer considering this a blocker: https://expensify.slack.com/archives/C01GTK53T8Q/p1711394680384129

**Comment by godofoutcasts94** [comment]
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> **Version Number:** v1.4.56-0 **Reproducible in staging?:** y **Reproducible in production?:** n **Issue reported by:** Applause - Internal Team
> 
> ## Action Performed:
> 1. Click on FAB > Request Money.
> 2. Navigate to Distance, add start and end points, then click Next.
> 3. Select Workspace, then click on Request Money.
> 4. Go to IOU and observe that the IOU detail is scrolled.
> 
> ## Expected Result:
> The IOU detail should not scroll.
> 
> ## Actual Result:
> The IOU detail is scrolled.
> 
> ## Workaround:
> n/a
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [ ]  Android: Native
> * [x]  Android: mWeb Chrome
> * [ ]  iOS: Native
> * [x]  iOS: mWeb Safari
> * [x]  MacOS: Chrome / Safari
> * [x]  MacOS: Desktop
> 
> ## Screenshots/Videos
> Add any screenshot/video evidence
> 
>  Bug6423960_1711160389870.video_2024-03-22_22-11-05.mp4 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
> 
> Upwork Automation - Do Not Edit

I think the video attached for this issue, seems to be different from steps to reproduce this issue.

**Comment by sonialiap** [comment]
Agreed, the video is of setting rates, not creating a distance expense

**Comment by sonialiap** [comment]
@kbecciv the video in this issue is about setting rates and doesn't match the steps that talk about creating a distance expense. Could you confirm whether the issue steps or the video needs updating, and update if necessary?

**Comment by kbecciv** [comment]
Checking @sonialiap

**Comment by kbecciv** [comment]
@sonialiap Updated the video, sorry for confusion!

**Comment by sonialiap** [comment]
This does not impact usability so I don't think this is an issue. Please reopen if you disagree 

https://github.com/Expensify/App/assets/17131195/e470b0a8-8ca5-447b-ab07-1eb20593706e
