### ISSUE TITLE
Workspace - Grammar error in "Let's get your company set up!" Concierge message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38872]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y

**Issue found when executing PR** https://github.com/Expensify/App/pull/38318
## Action Performed:
1. Log into OD with a new expensifail account
2. OD: Create a Collect workspace with chat enabled
3. ND: Check Concierge chat

## Expected Result:
It should be "Let's get your company set up! Your dedicated specialist...

## Actual Result:
Grammar error in "Let's get your company set up!" Concierge message: "Let's get your company set up! , your dedicated specialist...". There is an extra comma between sentences

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6424069_1711174268985!Capture](https://github.com/Expensify/App/assets/78819774/58b8bece-88bc-455a-a8be-b295e8d1340d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec26d4467a1a805c</li>
        <li>Upwork Job ID: 1772249919072411648</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
I can find and fix this. Not adding for external.

**Comment by laurenreidexpensify** [comment]
Pretty sure it's this - https://github.com/Expensify/Web-Expensify/blob/b200c54c18a51e8a1b142e8fc9170fe71b5aa14b/script/bwm/SendAssignedGuideMessaging.php#L19

**Comment by laurenreidexpensify** [comment]
Review will be on Expensify / Web so not applicable for C+ review

**Comment by laurenreidexpensify** [comment]
Actually it's this - https://github.com/Expensify/Web-Expensify/blob/423ff9df2a942fdeb3a4ff00ef242ad7fb50ecc4/script/bwm/SendAssignedGuideMessaging.php#L44

**Comment by laurenreidexpensify** [comment]
@lanitochka17 can you confirm the exact expensifail account you used to log in for the repro steps? Thanks

**Comment by laurenreidexpensify** [comment]
![2024-03-26_09-43-20](https://github.com/Expensify/App/assets/62073721/c04f3bb2-5ba8-4d6b-b445-7b8e4b811c17)

Need to clarify if we assign guides to expensifail accounts, cos I think this likely failing cos there is no Guide Name stored in the NVP and isn't a bug

**Comment by lanitochka17** [comment]
@laurenreidexpensify Tester used this account: applausetester+0323rbcollect@applause.expensifail.com

**Comment by laurenreidexpensify** [comment]
@Gonals @cead22 @zsgreenwald see you worked on some of this code before - do you think this is a bug, or expected behaviour cos of the expensifail account being used to test?

**Comment by cead22** [comment]
> Need to clarify if we assign guides to expensifail accounts, cos I think this likely failing cos there is no Guide Name stored in the NVP and isn't a bug

👍 

> @Gonals @cead22 @zsgreenwald see you worked on some of this code before - do you think this is a bug, or expected behaviour cos of the expensifail account being used to test?

Depends on how you look at it. I think the fact that we can send this without a guide name is a bug, and we should probably be checking for that, but it could also be that this test account is in a state that regular accounts wouldn't get to, and thus, it doesn't matter that we're not checking if the name is set

**Comment by laurenreidexpensify** [comment]
thanks for review @cead22 

I lean towards 1 too - I don't think we need to write a code fix for this until we run into it on a non-test account either. Closing
