### ISSUE TITLE
CRITICAL: [Track expense] Receipt leads to not here page when the scanning fails

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38873]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n (new feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause interna team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to FAB > Track expense.
3. Create a scan expense with invalid receipt.
4. When the scanning fails, go to the expense details page.
5. Click on the receipt.

## Expected Result:
The receipt is rendered without issue.

## Actual Result:
Not here page shows up when clicking on the receipt.
Note: To reproduce this bug reliably, please crearte new account 
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/998f7452-c15c-41a7-af9b-9a98e5c79786

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7b85f133e64f453</li>
        <li>Upwork Job ID: 1772330203765047296</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thienlnam</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thienlnam</details>

**Comment by kavimuru** [comment]
@johnmlee101 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by garrettmknight** [comment]
[Flagged in vip-vsb](https://expensify.slack.com/archives/C066HJM2CAZ/p1711385400242019)

**Comment by garrettmknight** [comment]
@thienlnam is gonna investigate.

**Comment by garrettmknight** [comment]
@thienlnam any update on this one?

**Comment by thienlnam** [comment]
Ah yeah, I was looking into this and I think I fixed this as well when working on the edit tracked expense flow
