### ISSUE TITLE
payment due [$500] Image MD - LHN preview shows "Attachment" instead of "Text [Attachment]" after reopening chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38877]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37566
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message with inline image markdown. Example:
An inline image and some text ![off](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
)
4. Go to a different chat
5. Go back to the chat in Step 3

## Expected Result:
LHN preview will show "text [Attachment]" format after returning to the same chat

## Actual Result:
LHN preview shows "Attachment" instead of "text [Attachment]" after returning to the same chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/847a37a2-ef75-4cf2-8750-caf58b014d76

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ccedd73b162426f</li>
        <li>Upwork Job ID: 1774996577371983872</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Image MD - LHN preview shows "Attachment" instead of "Text [Attachment]" after reopening chat
### What is the root cause of that problem?
- In offline mode, the last message is displayed as ```"text (image of ${image-name})"```. It is because the last message text is from [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L2968), where we use [parser.htmlToText](https://github.com/Expensify/expensify-common/blob/4e020cfa13ffabde14313c92b341285aeb919f29/lib/ExpensiMark.js#L487)(htmlForNewComment), that will replace image tag with ```(image of $4)```
### What changes do you think we should make in order to solve the problem?
- We need to update [this](https://github.com/Expensify/expensify-common/blob/4e020cfa13ffabde14313c92b341285aeb919f29/lib/ExpensiMark.js#L487) to:
```
                replacement: '[Attachment]',
```
- Then, BE need to change based on it for consistency

### What alternative solutions did you explore? (Optional)

- NA

**Comment by marcochavezf** [comment]
Looks like inline image markdown is not live on production yet, so it's a new feature:

<img width="1435" alt="Screenshot 2024-03-25 at 10 34 49 a m" src="https://github.com/Expensify/App/assets/6829422/41f851b3-d8de-4b9b-86e8-8ea8f89fb5ca">

**Comment by marcochavezf** [comment]
Ah yes, this is the [PR](https://github.com/Expensify/App/pull/37566) that introduced the new functionality

**Comment by marcochavezf** [comment]
Applying External and Bug labels

**Comment by zanyrenney** [comment]
Seeing as this relates to chat primarily, have added to VIP VSB.

**Comment by Julesssss** [comment]
> Triggered auto assignment to @Julesssss, see https://stackoverflow.com/c/expensify/questions/7972 for more details.

This is broken, @marcochavezf is already assigned.

**Comment by marcochavezf** [comment]
Sounds good, thanks @shubham1206agra for the review, assigning @nkdengineer for the frontend part

**Comment by zanyrenney** [comment]
any updates here @marcochavezf @shubham1206agra @nkdengineer

**Comment by nkdengineer** [comment]
@zanyrenney Opened a PR in `expensify-common` [here](https://github.com/Expensify/expensify-common/pull/679).

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment]
Wait seven days for payout

**Comment by zanyrenney** [comment]
**payment summary**

paid 📣 @shubham1206agra 🎉 $500

@nkdengineer has not applied for the job so cannot be paid, i have asked them to apply in DM.

**Comment by nkdengineer** [comment]
> @nkdengineer has not applied for the job so cannot be paid, i have asked them to apply in DM.

@zanyrenney I just applied for the job, thanks!!

**Comment by zanyrenney** [comment]
this is taking so long :( i've sent the offer again.

**Comment by nkdengineer** [comment]
@zanyrenney I've accepted the offer, sorry for the delay

**Comment by zanyrenney** [comment]
Thank you @nkdengineer !

**Comment by zanyrenney** [comment]
Full payment summary: 

payment summary

paid 📣 @shubham1206agra 🎉 $500 via Upwork

paid 📣 @nkdengineer  🎉 $500 via Upwork.
