### ISSUE TITLE
[HOLD for payment 2024-04-05] [$250] [Simplified Collect][Distance rates] - Back icon not functioning and close to status bar on rate edit screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38871]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38237
**Issue reported by:** Applause - Internal team

## Action Performed:
Precondition: user created a collect policy in OD
1. Open the app and log in as the admin of the collect policy
2. Navigate to the workspace settings > More features
3. Enable Distance rates
4. Open Distance rates
5. Select any distance rate
6. Tap the rate value
7. Tap the back icon

## Expected Result:
The back icon is functioning, user can return to the previous screen

## Actual Result:
The back icon is too close to the status bar and is not functioning

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ae7d4bcb-4196-418b-96bd-4f67ad021ffb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018bf3c7d04bca8505</li>
        <li>Upwork Job ID: 1772188385248808960</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by eh2077** [comment]
@mountiny Can you help add the BZ team here to track the payment?

**Comment by luacmartins** [comment]
Added bug label

**Comment by mountiny** [comment]
Thanks! this will be $250 to @eh2077

**Comment by luacmartins** [comment]
Just pending payment @anmurali

**Comment by mountiny** [comment]
Summary [here](https://github.com/Expensify/App/issues/38871#issuecomment-2027794123)

**Comment by luacmartins** [comment]
Waiting on payment

**Comment by luacmartins** [comment]
Still pending payment

**Comment by anmurali** [comment]
Offer sent to @eh2077 - https://www.upwork.com/nx/wm/offer/101898363

**Comment by eh2077** [comment]
@anmurali Accepted offer, thank you.

**Comment by luacmartins** [comment]
@anmurali @eh2077 are we good to close this one?

**Comment by eh2077** [comment]
> @anmurali @eh2077 are we good to close this one?

Ah, still waiting for the payment.

**Comment by anmurali** [comment]
Paid.
