### ISSUE TITLE
[HOLD for payment 2024-04-05] [$250] [Simplified Collect][Distance rates] No pop-over after bulk-selecting rates and trying to disable/delete them

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38876]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38237
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition: user created a collect policy in OD
1. Go to https://staging.new.expensify.com/
and log in as the admin of the collect policy
2. Navigate to the workspace settings > More features
3. Enable Distance rates
4. Open Distance rates
5. Tap bulk-select
6. In the drop-down select Disable rates"/ "Delete rates"
7. On the pop-over tap “Got it”
8. Delete one distance rate
9. Tap bulk select > Disable rates/Delete rates

## Expected Result:
The same pop-over is displayed in step 6 and 9 notifying that at least one distance rate should be enabled

## Actual Result:
The error message "There must be at least one enabled distance rate' is displayed instead of the pop-over the second time trying to disable the distance rates, the error on the distance rate edit screen is shown.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3d30c29f-e101-4340-a0d4-414f932e752c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da91acddaa976701</li>
        <li>Upwork Job ID: 1772188427745120256</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by mountiny** [comment]
Assigning Michal and taking over since its related to the `wave-collect`, its not a blocker since this feature is not out there for clients yet.

**Comment by MrMuzyk** [comment]
This issue was happening on all platforms as it's related to JS logic

**Comment by mountiny** [comment]
$250 to @hoangzinh unless you have reviewed the offending PR too?

**Comment by sonialiap** [comment]
@hoangzinh $250 - offer sent

**Comment by sonialiap** [comment]
Payment completed ✔️
