### ISSUE TITLE
[Backwards Compatibility] Workspace chat shows skeleton loading when changing report from Invoice to Expense

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36747
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Create a manual request.
4. While leaving workspace chat open, change the report from expense to invoice on Old Dot.
5. Change the report back to expense.

## Expected Result:
The workspace chat will update the expense accordingly.

## Actual Result:
The workspace chat shows skeleton loading when changing the report from invoice to expense.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/282d7f50-1e4a-4a79-bb95-497168f5ab53

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
The issue is actually converting from Invoice to Expense, which is not a supported flow just yet, but probably should be an issue we look into as a part of Wave Collect cc @trjExpensify

**Comment by trjExpensify** [comment]
Yeah, I agree. On OldDot, I'm pretty sure we restrict invoice creation to admins, but nevertheless, we should make sure changing the report type from `invoice` to `expense` works okay. Is this not on the "Backwards compatibility" radar already, @puneetlath? 

In the meantime, I'll put it in polish to make sure we don't lose it.

**Comment by tylerkaraszewski** [comment]
What should I do with this issue in the meantime?

**Comment by trjExpensify** [comment]
I think we can fix it, if it's not being worked on somewhere else! Bumped Puneet on the above.

**Comment by puneetlath** [comment]
raised it here: https://expensify.slack.com/archives/C036QM0SLJK/p1712246437566919?thread_ts=1712061967.333289&cid=C036QM0SLJK

**Comment by puneetlath** [comment]
As discussed in the thread, this isn't covered elsewhere, so we should fix it in this issue.

**Comment by tylerkaraszewski** [comment]
I will fix this soon-ish.

**Comment by tylerkaraszewski** [comment]
Looking at this next.

**Comment by tylerkaraszewski** [comment]
I've got a newsletter to prep that's a higher priority than this.
