### ISSUE TITLE
Desktop - IOU - The Distance IOU is unable to determine the user's coordinates

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38895]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4446001
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Open NewDot app
2. Log in to the employee account
3. Navigate to the WS room
4. Navigate to Request money -> Distance -> Start
5. In the Address field, select the "Use current location" option

## Expected Result:
When using the "Use current location" option in the Distance IOU, the application must determine the user's coordinates.

## Actual Result:
The Distance IOU is unable to determine the user's coordinates.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/941e8e76-9943-4a60-8f0b-1d3e04541975

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by roryabraham** [comment]
not able to reproduce on dev on main. I suspect this may be a back-end issue

**Comment by roryabraham** [comment]
not able to reproduce this on staging web either, though I just noticed this was reported on desktop. I'll check there...

**Comment by roryabraham** [comment]
I got this error on desktop:

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/47436092/1321285a-82e3-4eeb-bbaf-0668e3c91671">

the link just links to Expensify Help and not a specific page, which isn't very helpful

**Comment by roryabraham** [comment]
This may be a regression from https://github.com/Expensify/App/pull/38442

**Comment by roryabraham** [comment]
seeing the same error locally

**Comment by hayata-suenaga** [comment]
> seeing the same error locally

If you haven't manually added the GCP key in your local `.env`, then it's expected that the current location feature won't work on the local desktop app because of the changes I made

**Comment by hayata-suenaga** [comment]
but this shouldn't happen on the staging or production. I'll also gonna investigate it

**Comment by roryabraham** [comment]
Maybe problem is that environment variables set when running `electron-builder` [here](https://github.com/Expensify/App/blob/d22957d292661ef10ea539f49725c388b3237dc9/.github/workflows/platformDeploy.yml#L163-L173) aren't made available to the main process at runtime?

**Comment by roryabraham** [comment]
@hayata-suenaga I'm thinking maybe we can fix this issue with a PR like this: https://github.com/Expensify/App/pull/38953

**Comment by roryabraham** [comment]
the only problem with that is that I think it might make it available to the renderer process as well, which could mean that a determined actor could read it at runtime. The main process is generally more secure, but still I'm not 100% sure if something set in the Electron main `process.env` is secure

**Comment by hayata-suenaga** [comment]
that interesting that webpack doesn't pick up env vars from the runner environment and you have to supply the env file as a command argument 🤔

**Comment by hayata-suenaga** [comment]
> the only problem with that is that I think it might make it available to the renderer process as well, which could mean that a determined actor could read it at runtime. The main process is generally more secure, but still I'm not 100% sure if something set in the Electron main process.env is secure

This issue exists either way because the token needs to be included in the build code.

**Comment by hayata-suenaga** [comment]
[the Secrets should be set correctly in the App repo](https://github.com/Expensify/Expensify/issues/375336#issuecomment-1997878419) 🤔

**Comment by roryabraham** [comment]
> that interesting that webpack doesn't pick up env vars from the runner environment

I think it makes sense. electron-builder doesn't take all your bash environment variables and inject them into the bundled app - only those included in your `.env` file (which is consistent with react-native-config)

**Comment by hayata-suenaga** [comment]
yes that's probably it

[we use `react-native-config` which reads values from the `.env` file](https://www.npmjs.com/package/react-native-config)

**Comment by roryabraham** [comment]
it's actually [react-web-config](https://github.com/Expensify/App/blob/59a71f3d1a34713e6c8213781c423440fb9436f8/config/webpack/webpack.common.js#L206) on web and desktop

**Comment by roryabraham** [comment]
we have a custom version of the webpack plugin to support desktop: https://github.com/Expensify/App/blob/59a71f3d1a34713e6c8213781c423440fb9436f8/config/webpack/webpack.common.js#L122-L130

**Comment by hayata-suenaga** [comment]
ah I see 😄 wow that's deep

**Comment by hayata-suenaga** [comment]
@roryabraham we can go with [your PR](https://github.com/Expensify/App/pull/38953) then

**Comment by roryabraham** [comment]
Put the PR in for review, though I'm still working on local testing steps

**Comment by roryabraham** [comment]
> If you haven't manually added the GCP key in your local .env

Where can I find this key?

**Comment by yuwenmemon** [comment]
Removing the blocker as per the conversation here: https://expensify.slack.com/archives/C01GTK53T8Q/p1711394691005269

**Comment by hayata-suenaga** [comment]
No payment is needed for the PR linked above.

The issue hasn't been solved yet. I'll work on this next week.

**Comment by hayata-suenaga** [comment]
I changed the priority of this task to weekly, but I'll try to get to this this week.

**Comment by hayata-suenaga** [comment]
The issue is still reproducible. will work on this when I have time.

![Screenshot 2024-04-12 at 12 14 04 PM](https://github.com/Expensify/App/assets/98560306/f2e5feb5-4f07-4433-b347-8923e9ab4c2a)

**Comment by roryabraham** [comment]
I'm unassigning myself since we don't both need to be assigned

**Comment by hayata-suenaga** [comment]
I'll work on this after the QBO project is over 🙇

**Comment by hayata-suenaga** [comment]
The request to Google geolocation endpoint from Electron is failing. The geolocation API token is not properly injected during build time.

I'll investigate this when I have time after the initial QBO release.

<img width="400" alt="Screenshot 2024-05-08 at 5 26 42 PM" src="https://github.com/Expensify/App/assets/98560306/cc53087c-6290-4f17-9698-7f91630ca0eb">

**Comment by hayata-suenaga** [comment]
I still don't have a time to get around this issue yet. I'll circle back once QBO finishes.

**Comment by hayata-suenaga** [comment]
still no time to get around this will be back when I have time

**Comment by hayata-suenaga** [comment]
was putting off this for a while. will take a look during this week 🙇

**Comment by hayata-suenaga** [comment]
got sick lasst week. catching up with issues.
