### ISSUE TITLE
Workspace features - App redirects to not here page when the feature is disabled

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38896]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37902
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is admin of Collect workspace.
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to More features.
4. Open the same page in Step 3 in a second tab.
5. In the first tab, go to tab of enabled feature.
6.. From the second tab, disable the feature in Step 5.
7. Copy URL to any feature.
8. Disable the feature in Step 7.
9. Navigate to the URL of disabled feature.

## Expected Result:
In Step 6, the first tab will redirect to More features page.
In Step 9, app will redirect to More features page.

## Actual Result:
In Step 6, the first tab redirects to not here page.
In Step 9, not here page shows up.

## Additional Information:
For Step 1-6, reproducible on web only.
For Step 7-9, reproducible in all environment.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
**Step 1-6**

https://github.com/Expensify/App/assets/93399543/951f8549-2151-42fb-abb4-a5dd8aba3638

**Step 7-9**

https://github.com/Expensify/App/assets/93399543/db0ca4ff-3238-4352-823d-0ddd6ceb2bc0

Add any screenshot/video evidence

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-control

**Comment by getusha** [comment]
That's right this was intentional.

**Comment by rezkiy37** [comment]
It works properly. The app shows the "Not found" when a feature is disabled.
