### ISSUE TITLE
[HOLD for payment 2024-04-09] [Wave Collect][QBO] Allow collect admins to enable the Accounting Connection feature on the More Features page

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#38899]
Add the `Connections` section on the More Features page. This new section allows the admins to toggle on the Accounting Connections feature.

- [Relevant section in the QBO Design Doc](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit#heading=h.nq0dbvzasfcs)
- [Relevant section in the Simplified Collect Design Doc](https://docs.google.com/document/d/1xk-fp5tKM-Es5oBrlWa0oHFUfBJH-XaFWzywzCkRaEY/edit#heading=h.dwmzos72zpcj)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb6b6b32a1e23f36</li>
        <li>Upwork Job ID: 1772048497857794048</li>
        <li>Last Price Increase: 2024-03-24</li>
    </ul>
</details>

**Comment by alexpensify** [comment]
Daily Update: I think this should be weekly but Melvin keeps updating to Daily.

**Comment by hayata-suenaga** [comment]
sorry this should be daily I didn't have time to work on this recently.  will planning to merge by the end of this week 🙇

**Comment by trjExpensify** [comment]
@hayata-suenaga did you implement the locked toggles with this issue? [Doc ref](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit#heading=h.qxw9gudmkrel). 

<img width="280" alt="image" src="https://github.com/Expensify/App/assets/16232057/16307e9c-bec5-4692-8699-1fcad4d15739">

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga did you implement the locked toggles with this issue? [Doc ref](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit#heading=h.qxw9gudmkrel).

[Here is the issue I created](https://github.com/Expensify/App/issues/39724) 😄

**Comment by alexpensify** [comment]
Payouts due: 2024-04-09

- [ ] Contributor: N/A 
- [ ] Contributor+: $ X @allroundexperts 

Upwork job is N/A

**Comment by alexpensify** [comment]
@allroundexperts - closing for now, but please submit the payment request in Chat. Thanks!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
