### ISSUE TITLE
[HOLD for payment 2024-04-09] HIGH: [Performance] [$500] Eliminate 3x re-render on switching to new chat

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#38909]
Problem:
===
It really seems like every time I switch to a chat, it renders the page like 3 times (ie, it shows, and then blinks 2x more looking like it re-renders).  On web it's not that big a deal, but I find my mobile app is extremely sluggish, and I think it's for the accumulation of reasons like this. 

Solution:
===
?? not sure.  [Being discussed in Slack here, along with video.](https://expensify.slack.com/archives/C05LX9D6E07/p1711351117604709)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01574932395779d237</li>
        <li>Upwork Job ID: 1773397513149165568</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

**Comment by perunt** [comment]
I'll take a look at this

**Comment by Christinadobrzyn** [comment]
Payouts due:

- [ ] Contributor+: $500 @paultsimura (Upwork offer - https://www.upwork.com/nx/wm/offer/101774668)

Upwork job is [here](https://www.upwork.com/jobs/~01574932395779d237).

@paultsimura do we need a regression test for this?

**Comment by Christinadobrzyn** [comment]
Thanks @paultsimura! I paid you in Upwork based on this summary - https://github.com/Expensify/App/issues/38909#issuecomment-2041936349

I think this is good to close. Feel free to let me know if I missed anything!
