### ISSUE TITLE
[HOLD for payment 2024-04-25] [TS migration] Migrate IOURequestStepConfirmation and IOURequestStepCategory pages to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38918]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

- src/pages/iou/request/step/IOURequestStepConfirmation.js
- src/pages/iou/request/step/IOURequestStepCategory.js

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by fabioh8010** [comment]
This issue is internal and will be handled by the TS team.

**Comment by BrtqKr** [comment]
Hey, I'm from SWM and I'd like to take over this issue

**Comment by JmillsExpensify** [comment]
Assigned, thanks!

**Comment by aldo-expensify** [comment]
I think we don't need to hold anymore?

**Comment by JmillsExpensify** [comment]
I have filled out the payment summary above. @fedirjh also just sent you an offer via Upwork.

**Comment by JmillsExpensify** [comment]
All set! Thank you.
