### ISSUE TITLE
[HOLD for payment 2024-04-25] [TS migration] Migrate StepScreenWrapper and StepScreenDragAndDropWrapper components to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38913]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

- src/pages/iou/request/step/StepScreenWrapper.js
- src/pages/iou/request/step/StepScreenDragAndDropWrapper.js

**Comment by fabioh8010** [comment]
This issue is internal and will be handled by the TS team.

**Comment by BrtqKr** [comment]
Hey, I'm from SWM, I'd like to take over this issue

**Comment by stephanieelliott** [comment]
Thanks @BrtqKr! You're assigned 😊

**Comment by stephanieelliott** [comment]
Hey @BrtqKr, any update on when this PR will be taken out of draft state?

**Comment by BrtqKr** [comment]
@stephanieelliott Friday morning probably, I've already applied review fixes from the cross-review, so we're close. Sorry for the delay, but I combined it with IOU screens and the second part was a bit more troublesome than I initially expected

**Comment by stephanieelliott** [comment]
No worries @BrtqKr, thanks for the update!

**Comment by stephanieelliott** [comment]
PR is on staging

**Comment by stephanieelliott** [comment]
Reapplying the `Bug` label to get another BZ member on this while I am OOO til May 2. Thanks @CortneyOfstad,  only thing to do here is issue payment on 4/25!

**Comment by CortneyOfstad** [comment]
We're all good! Closing this out!
