### ISSUE TITLE
[$250] [TS migration] Migrate IOURequestStartPage, IOURequestRedirectToStartPage, IOURequestStepDistance and IOURequestStepAmount pages to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38914]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

- src/pages/iou/request/IOURequestStartPage.js
- src/pages/iou/request/IOURequestRedirectToStartPage.js
- src/pages/iou/request/step/IOURequestStepDistance.js
- src/pages/iou/request/step/IOURequestStepAmount.js
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c348bf4c4c3354b</li>
        <li>Upwork Job ID: 1787477553272143872</li>
        <li>Last Price Increase: 2024-05-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by fabioh8010** [comment]
This issue is internal and will be handled by the TS team.

**Comment by joekaufmanexpensify** [comment]
@fabioh8010 are you working on this yourself, or is the assignee TBD?

**Comment by fabioh8010** [comment]
@joekaufmanexpensify Someone from the TS team will pick this issue shortly!

**Comment by joekaufmanexpensify** [comment]
Got it. TY!

**Comment by joekaufmanexpensify** [comment]
@cdOut is there an ETA for when a PR will be up here?

**Comment by cdOut** [comment]
Yes, I should be done with it by today and hopefully we can push with reviews through tomorrow

**Comment by joekaufmanexpensify** [comment]
@cdOut is the PR now in review? If so, mind linking it here?

**Comment by cdOut** [comment]
I've pushed the recent changes into the linked PR, we will review internally and push for cross review ASAP.

**Comment by joekaufmanexpensify** [comment]
PR awaiting deploy to staging

**Comment by joekaufmanexpensify** [comment]
PR on staging

**Comment by joekaufmanexpensify** [comment]
Only payment needed here is $250 to @ishpaul777 for C+ review via upwork

**Comment by joekaufmanexpensify** [comment]
@ishpaul777 offer sent!

**Comment by joekaufmanexpensify** [comment]
@ishpaul777 $250 sent and contract ended

**Comment by joekaufmanexpensify** [comment]
upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set!
