### ISSUE TITLE
[$250] [TS migration] Migrate IOURequestStepTaxRatePage and IOURequestStepTaxAmountPage pages to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38915]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

- src/pages/iou/request/step/IOURequestStepTaxRatePage.js
- src/pages/iou/request/step/IOURequestStepTaxAmountPage.js

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd5245d23e9e6994</li>
        <li>Upwork Job ID: 1783579581713768448</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by fabioh8010** [comment]
This issue is internal and will be handled by the TS team.

**Comment by cdOut** [comment]
Hi! I'm Tymek from Software Mansion, the expert agency, and I'd like to work on this issue.

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by jjcoffee** [comment]
@kevinksullivan When you get a minute, could you assign me to the issue for future payment? I reviewed the linked [PR](https://github.com/Expensify/App/pull/39059).

**Comment by rlinoz** [comment]
This is deployed to prod already.

**Comment by jjcoffee** [comment]
@kevinksullivan Friendly bump for payment! :pray:

**Comment by kevinksullivan** [comment]
Offer sent @jjcoffee lmk when you accept!

**Comment by jjcoffee** [comment]
@kevinksullivan Accepted, thanks!

**Comment by jjcoffee** [comment]
@kevinksullivan Whilst I have you, could you also process payment on https://github.com/Expensify/App/issues/38584? It's been hanging around for a while, I think it's dropped off your radar because the automation failed. Thanks :pray:

**Comment by kevinksullivan** [comment]
yup, will do. All set here as well
