### ISSUE TITLE
[HOLD for payment 2024-04-15] [TS migration] Migrate IOURequestStepDescription, IOURequestStepDate and IOURequestStepCurrency pages to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38917]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

- src/pages/iou/request/step/IOURequestStepDescription.js
- src/pages/iou/request/step/IOURequestStepDate.js
- ~src/pages/iou/request/step/IOURequestStepCurrency.js~ (it will be migrated [here](https://github.com/Expensify/App/issues/31992))

**Comment by fabioh8010** [comment]
This issue is internal and will be handled by the TS team.

**Comment by twisterdotcom** [comment]
When you know who is handling it, let me know, have them comment and I'll assign.

**Comment by bernhardoj** [comment]
We will migrate IOURequestStepCurrency in this [issue](https://github.com/Expensify/App/issues/31992). Currently on hold for this [PR](https://github.com/Expensify/App/pull/35161) which replaces IOUCurrencySelection with IOURequestStepCurrency.

**Comment by fabioh8010** [comment]
Thanks for the info @bernhardoj!, so the update list is this:

- src/pages/iou/request/step/IOURequestStepDescription.js
- src/pages/iou/request/step/IOURequestStepDate.js

**Comment by war-in** [comment]
Hi, I'm Marcin from Software Mansion and I'd like to work on this issue

**Comment by twisterdotcom** [comment]
@getusha did the PR review. Payment Summary:

- @war-in does not require payment (Contractor)
- @getusha paid $250 [here](LINK] WIP

**Comment by twisterdotcom** [comment]
No need for checklist, this was a migration. Closing.
