### ISSUE TITLE
[TS migration] Migrate IOURequestStepTag, IOURequestStepParticipants and IOURequestStepMerchant pages to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38916]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

- src/pages/iou/request/step/IOURequestStepTag.js
- src/pages/iou/request/step/IOURequestStepParticipants.js
- src/pages/iou/request/step/IOURequestStepMerchant.js

**Comment by fabioh8010** [comment]
This issue is internal and will be handled by the TS team.

**Comment by ruben-rebelo** [comment]
I am Ruben Rebelo from Callstack - expert contributor group. I’d like to work on this job.

**Comment by puneetlath** [comment]
It seems like this is done and we just need to pay @mananjadhav out. Is that right?

**Comment by mananjadhav** [comment]
Yes @puneetlath Can you please post the payment summary?

**Comment by puneetlath** [comment]
Payment summary: 
- C+ - @mananjadhav - $250 - to be paid via NewDot

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
