### ISSUE TITLE
[HOLD for payment 2024-04-05] [Simplified Collect][Workflows] "Make or track payments" section is no longer grayed out after updating to USD

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when executing PR :** https://github.com/Expensify/App/pull/38318

**Version Number:** 1.4.56-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is admin of Collect workspace.
- The default currency for Collect workspace is not USD.
- Make or track payments in Workflows are disabled.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Workflows.
4. Go offline.
5. Toggle on "Make or track payments".
6. Click Connect bank account > Update to USD.
7. Close bank account RHP.

## Expected Result:
"Make or track payments" section will remain grayed out.

## Actual Result:
"Make or track payments" section is no longer grayed out after selecting Update to USD.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8875eb43-b723-416b-86b2-ef1247c79af2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012180f5608246c8c6</li>
        <li>Upwork Job ID: 1772232177098358784</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@trjExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #wave-control.

**Comment by izarutskaya** [comment]
Production  different behavior


https://github.com/Expensify/App/assets/115492554/30b01bde-817b-4f6a-89dd-efa3d6250f3f

**Comment by mountiny** [comment]
Nto a blocker, related to Simplified collect so happy to take over from Alex

**Comment by mountiny** [comment]
This can be external, its a simple polish item though so making it $250

**Comment by luacmartins** [comment]
@Krishna2323 I'm not sure how the PR you linked above fixes this issue.

**Comment by luacmartins** [comment]
I like @tienifr's proposal better since it's simpler (doesn't add any new pending fields) and keeps all existing pending fields. Assigning you to the job!

**Comment by luacmartins** [comment]
Ah I see! Thanks for pointing that out! Gonna add this issue to the list of fixed issues of that PR.

**Comment by luacmartins** [comment]
Note: we can close this issue once the PR is deployed, since payment will be handled in https://github.com/Expensify/App/issues/37254

**Comment by mountiny** [comment]
payments will be handled here https://github.com/Expensify/App/issues/37254

We can close this once
