### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Workspace - The user can skip validation of the first name field on the Personal info tab

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38920]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4445017&group_by=cases:section_id&group_id=283225&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Navigate to Workspace settings - Bank account - Connect online with Plaid
4. Choose Regions bank
5. Continue until legal name is asked
6. Leave the first name blank and input "Charleson" to the last name
7. Tap on the "Next" button
8. Tap on the "back" button
9. Tap on the "Next" button
10. Continue the flow until you get the "firstName is invalid or missing" error

## Expected Result:
The field should be validated.

## Actual Result:
The user can skip validation of the first name field on the Personal info tab. "Bank account can't be created, firstName is invalid or missing" error message appears later in the flow.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2b3810e1-5fc4-4253-8ef6-4461a2ecb1a2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8adbf72aee79603</li>
        <li>Upwork Job ID: 1774914745105002496</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user can skip the legal name form after filling the last name, go back and reconfirm the routing number again.

### What is the root cause of that problem?
We have `getInitialSubstepForPersonalInfo` to decide the sub-step index to show to the user.
https://github.com/Expensify/App/blob/4bc6744de9e1f4ea52d57bd84dbac9ce0ffbae7a/src/pages/ReimbursementAccount/utils/getInitialSubstepForPersonalInfo.ts#L9-L16

If the first name and last name are empty, we will show the legal name form. However, if we fill in the last name, it will be saved to the draft and we check for both draft and server value
https://github.com/Expensify/App/blob/4bc6744de9e1f4ea52d57bd84dbac9ce0ffbae7a/src/pages/ReimbursementAccount/PersonalInfo/PersonalInfo.tsx#L47

and the condition will fail because it needs both fields to be empty.

### What changes do you think we should make in order to solve the problem?

Show the legal name form if one of the first or last names is empty.
```
if (data[personalInfoKeys.FIRST_NAME] === '' || data[personalInfoKeys.LAST_NAME] === '') {
    return 0;
}
```

### What alternative solutions did you explore? (Optional)
Don't check for the draft data.
https://github.com/Expensify/App/blob/4bc6744de9e1f4ea52d57bd84dbac9ce0ffbae7a/src/pages/ReimbursementAccount/PersonalInfo/PersonalInfo.tsx#L47

```
const values = useMemo(() => getSubstepValues(PERSONAL_INFO_STEP_KEYS, null, reimbursementAccount), [reimbursementAccount, reimbursementAccountDraft]);
```

**Comment by johncschuster** [comment]
I'm not sure how this fits into any of our existing initiatives, but this feels like either an oversight or a regression if the user can skip ahead of entering their first name in the form.

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/38920#issuecomment-2018323880) @bernhardoj.

Proposal from @bernhardoj looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @sobitneupane

**Comment by johncschuster** [comment]
# Payment Summary:
@sobitneupane - $500 - via NewDot Manual Requests
@bernhardoj - $500 - PAID via [Upwork](https://www.upwork.com/jobs/~01c8adbf72aee79603) (Contributor)

**Comment by johncschuster** [comment]
@sobitneupane, can you complete the BZ Checklist above? Thank you!

**Comment by johncschuster** [comment]
Waiting on the BZ Checklist to be completed 👍

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/31121/
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/31121#issuecomment-2097905881
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open Settings > Workspaces > Select any workspace > Bank account
2. Connect manually
3. Complete the routing and bank account number step
4. Fill the last name but leave first name empty
5. Go back
6. Go next again and confirm the routing and bank account number again
7. Verify you are navigated to the first and last name step

**Comment by sobitneupane** [comment]
Requested payment in newDot.
https://github.com/Expensify/App/issues/38920#issuecomment-2080194723

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane
