### ISSUE TITLE
[HOLD for payment 2024-04-09] [Simplified Collect][Distance rates] - Distance rates disappear when changing default workspace currency offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38928]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is admin of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Distance rates.
4. Add a few distance rates.
5. Go offline.
6. Go to workspace profile > Currency > Change to a different currency.
7. Go to Distance rates.

## Expected Result:
All the available distance rates will still be present after changing workspace default currency offline.

## Actual Result:
Only one distance rate is present after changing workspace default currency offline. The rest reappears after returning online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/59fcbe6a-6c2c-4420-88cd-7d6be225713b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ef3b0c77b5b3ce7</li>
        <li>Upwork Job ID: 1772808192831074304</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave-control.

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by Christinadobrzyn** [comment]
hi! Could you confirm if this job is related ? I think it might be? 

https://github.com/Expensify/App/issues/36680

**Comment by luacmartins** [comment]
@kadiealexander I think https://github.com/Expensify/App/issues/36680 is its own thing.

**Comment by kadiealexander** [comment]
@alitoshmatov please complete the checklist!

**Comment by kadiealexander** [comment]
Bumped @alitoshmatov [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1712812944180559).

**Comment by kadiealexander** [comment]
@alitoshmatov I've sent an Upwork contract, please accept!
