### ISSUE TITLE
Scan - PDF receipt is enlarged in preview before the scan request is created

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38927]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Go to + > Request money > Scan.
4. Upload a PDF receipt.
5. Note that PDF receipt preview in the confirmation page.
6. Create the request.
7. Note that PDF receipt preview on the expense preview while the request is being created.

## Expected Result:
In Step 5 and 7, PDF receipt preview should not appaear enlarged.

## Actual Result:
In Step 5, PDF receipt preview is enlarged in confirmation page.
In Step 7, while the request is being created, the PDF receipt preview on the expense preview also appears enlarged for a while.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9c3bcefd-f9b0-443b-8537-33191bb66819

[Bug6425654_1711354222363!Receipt_Example.pdf](https://github.com/Expensify/App/files/14742862/Bug6425654_1711354222363.Receipt_Example.pdf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think that this bug might be related to #wave-control.

**Comment by sonialiap** [comment]
This seems very minor. I'm going to close this out but feel free to reopen if you disagree
