### ISSUE TITLE
[HOLD for payment 2024-04-05] [TS migration] Migrate react-native.js mock to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#38921]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

- __mocks__/pusher-js/react-native.js

**Comment by fabioh8010** [comment]
This issue is internal and will be handled by the TS team.

**Comment by Christinadobrzyn** [comment]
Thanks @fabioh8010! I'm not super familiar with the TS team - do we pay them through Upwork or elsewhere?

**Comment by fabioh8010** [comment]
@Christinadobrzyn no payment will be needed in this issue, TS team is composed of expert agency employees and, in this case, this issue won't need C+ review (too simple)

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by iwiznia** [comment]
Go home Melvin, you are drunk.
