### ISSUE TITLE
Budget - 3 Notifications are triggered when personal and workspace threshold are surpassed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38933]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2778057
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Preconditions: User has Controlled workspace with Category or Tags Budget enabled (via OldDot).
Navigate to the Category (or Tag) that has a budget.
Edit the personal budget to 50
Edit the workspace budget to 100
Edit the notification threshold to 50%

1. Create a report in the control policy
2. Add some expenses with the category (or tag) that has the budget setup
3. Submit the report but don't approve
4. Create another report
5. Add some expenses with the same tag
6. Leave the report in open status
7. Create another report
8. Add a 30$ expense with the category (or tag) that has a budget selected
9. Mark the report as approved
10. Repeat steps 1-9 with a 60$ expense with the category (or tag) for step 8.
11. Navigate to the #admin chat in NewDot.

## Expected Result:
In #admin chat there is the message formatted in the following way (for a 30$ expense):
"Heads up! This workspace has a $[individual budget amount] per person per month for [category/tag name] tag budget. [[submitter@email.com]](mailto:submitter@email.com])
is currently at $[submitted amount] which is over [budget percentage]% of the budget. There is also $[pending amount] awaiting approval, and $[open report amount] that hasn't been submitted yet, for a total of $[total amount]."

and the message formatted in the following way (for a 60$ expense):
"Heads up! This workspace has a $[workspace budget amount] per month for [category/tag name] category budget. You are currently at $[submitted amount] which is over [over budget percentage]% of the budget. There is also $[pending amount] awaiting approval, and $[open report amount] that hasn't been submitted yet, for a total of $[total amount]."

## Actual Result:
In #admin chat there is the message formatted in the following way (for a 30$ expense):
"Heads up! This workspace has a $[individual budget amount] per person per month for [category/tag name] tag budget. [[submitter@email.com]](mailto:submitter@email.com])
is currently at $[submitted amount] which is over [budget percentage]% of the budget. There is also $[pending amount] awaiting approval, and $[open report amount] that hasn't been submitted yet, for a total of $[total amount]."

the message formatted in the following way (for a 60$ expense):
"Heads up! This workspace has a $[workspace budget amount] per month for [category/tag name] category budget. You are currently at $[submitted amount] which is over [over budget percentage]% of the budget. There is also $[pending amount] awaiting approval, and $[open report amount] that hasn't been submitted yet, for a total of $[total amount]."

AND
the message formatted in the following way (for a 60$ expense):
"Heads up! This workspace has a $[individual budget amount] per person per month for [category/tag name] tag budget. [[submitter@email.com]](mailto:submitter@email.com])
is currently at $[submitted amount] which is over [over budget percentage]% of the budget. There is also $[pending amount] awaiting approval, and $[open report amount] that hasn't been submitted yet, for a total of $[total amount]."

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fdc675b1-8221-46dd-a5bc-2b6aaf19b373

![Bug6424582_1711222452784!image__1_](https://github.com/Expensify/App/assets/115492554/1811c3b6-56ce-4e9d-8ecc-af703f4905f2)
![Bug6424582_1711222452791!image](https://github.com/Expensify/App/assets/115492554/ff1a7169-6f22-420e-acab-12bf90aa494f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb.

**Comment by miljakljajic** [comment]
Let me see if this is expected - it's possible that this is just the result of us not having built backwards compatibility for the budgets feature yet

**Comment by miljakljajic** [comment]
I'm sorry @izarutskaya can you help me understand exactly what the issue is - the notification in the admin chat is not updating to reflect the new budget?
