### ISSUE TITLE
[$250] Payment for Bug Report:  #18891

### ISSUE THREAD

**Issue by laurenreidexpensify** [Expensify/App#38941]
-  #18891
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d23d5c6de6cb52a7</li>
        <li>Upwork Job ID: 1772291027547250688</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
@ayazhussain79 pls apply to job in Upwork thanks

**Comment by ayazhussain79** [comment]
@laurenreidexpensify Applied, Thank you

**Comment by laurenreidexpensify** [comment]
Offer sent, once that's accepted will issue payment 👍

**Comment by ayazhussain79** [comment]
Offer accepted, Thank you

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Bug Reporter Paid $250 in upwork @ayazhussain79 - issue predates closure of bug reporting bonus scheme
