### ISSUE TITLE
[Needs Reproduction] Clicking links does nothing

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @JmillsExpensify @quinthar 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711142201869449
https://expensify.slack.com/archives/C049HHMV9SM/p1711400985997969

## Action Performed:
1. Open a chat as user A
2. Send a message to another user B with link
3. As a user B click on the link

## Expected Result:
Link opens in the new tab

## Actual Result:
Clicking on the link nothing happens

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-03-22 at 15 17 22](https://github.com/Expensify/App/assets/38435837/d95595bc-6556-4258-94a9-55d062417c20)

https://github.com/Expensify/App/assets/38435837/a7a60b73-0149-4322-a9eb-0539942a899d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
SO: https://stackoverflowteams.com/c/expensify/questions/16989

**Comment by twisterdotcom** [comment]
Given I haven't seen this widely reported, I don't think it needs a tonne of focus. My attempt is below:

https://github.com/Expensify/App/assets/9133401/6fe30433-922a-4cda-be0e-ccc3e3ed13f4

**Comment by twisterdotcom** [comment]
Downgrading to Weekly.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment]
Let's give it one more week. I also can't recreate.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by twisterdotcom** [comment]
Okay, let's close.
