### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] `MISSING_TRANSLATION` is shown in pronoun field even without any pronouns set

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @quinthar 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711338168652399

## Action Performed:
1. Login to an account in which no pronouns set
2. Open the profile page

## Expected Result:
Pronoun field is empty

## Actual Result:
Appears as ``Missing Translation" Also there are console logs

[alrt] pronouns.He/him was not found in the en locale - {"stack":"\"Error\\n    at a.alert (https://staging.new.expensify.com/vendors-406b3bb5f059dfb66309.bundle.js:1:3900169)\\n    at Module.B (https://staging.new.expensify.com/main-93cf1b44624c1fe66191.bundle.js:1:2335910)\\n    at https://staging.new.expensify.com/main-93cf1b44624c1fe66191.bundle.js:1:1771873\\n    at R (https://staging.new.expensify.com/main-93cf1b44624c1fe66191.bundle.js:1:3953628)\\n    at Co (https://staging.new.expensify.com/vendors-406b3bb5f059dfb66309.bundle.js:1:5860880)\\n    at Ms (https://staging.new.expensify.com/vendors-406b3bb5f059dfb66309.bundle.js:1:5881792)\\n    at vl (https://staging.new.expensify.com/vendors-406b3bb5f059dfb66309.bundle.js:1:5918898)\\n    at bc (https://staging.new.expensify.com/vendors-406b3bb5f059dfb66309.bundle.js:1:5907143)\\n    at gc (https://staging.new.expensify.com/vendors-406b3bb5f059dfb66309.bundle.js:1:5907071)\\n    at mc (https://staging.new.expensify.com/vendors-406b3bb5f059dfb66309.bundle.js:1:5906934)\""}

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (23)](https://github.com/Expensify/App/assets/38435837/0bf926f7-9efa-48de-ad5f-d2117abb4166)

![image (24)](https://github.com/Expensify/App/assets/38435837/fd1e9566-ea95-44cd-aecc-ef2755f348ea)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e0d665061e60d96</li>
        <li>Upwork Job ID: 1774914293176807424</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by tgolen** [comment]
I like going with solution 2, and I would like to recommend to use an Onyx migration instead of using the profile page to correct the pronouns.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second  week)

**Comment by johncschuster** [comment]
Payment has been issued. @ntdiary, can you please complete the BZ list above?

**Comment by johncschuster** [comment]
I don't feel passionately about creating a regression test. 👍
