### ISSUE TITLE
[Guided Setup Stage 1] Update the workspace invite emails on Expensify Classic 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#38963]
Stemming from [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1711383334618519?thread_ts=1710800350.583749&cid=C036QM0SLJK), we currently do not have standardize messages being sent from workspace invites on NewDot and Classic. Thus, we're looking to update that. 

I'll be updating [this issue to cover the changes on NewDot.](https://github.com/Expensify/App/pull/38023) @Gonals I believe @tgolen said you should be good to make these updates relatively quickly on Classic. This is a wave-collect CRITICAL so hopefully, we can do it soon. Let me know if you think I need to find someone else.  

Here is what the invite should do on Classic:
```
Subject: # [inviterFirstName] [inviterLastName] invited you to [workspaceName]

Body:
[welcomeNote]

Footer: Head over to www.expensify.com to respond on Expensify, or reply here.
```

- This should trigger an email or SMS to the new users. 
- If the inviter does not have a [inviterFirstName] [inviterLastName], it would be their email/SMS.
- In Classic, there is no default welcomeNote in Classic but the inviter can add a personal message to set the welcomeNote.
- If there is no welcomeNote present, we just would show the footer in the email. 
- In the Footer, www.expensify.com would link the individual to the inbox. 
- It should come from [notifications@expensify.com](mailto:notifications@expensify.com) with a reply-to set as replies+<reportID>@expensify.com. 
  - This means if the user replies, the email will go to the workspace chat in NewDot or if the inviter is not on NewDot like in this case, it will be forwarded to them as an unread Message Summary minutes later. 

I'll update the other issue for NewDot now, which is similar to the above but with the following changes:
- This will be sent as a whisper as well using the custom subject line syntax.
- The footer will be: Head over to new.expensify.com to respond on Expensify, or reply here.
  - This just changes the link to new.expensify.com rather than www.expensify.com and links new.expensify.com to the workspace chat rather than the inbox. 

Otherwise, it will be the same.

**Comment by Gonals** [comment]
I'll take a look at this in a day or two

**Comment by Gonals** [comment]
> or if the inviter is not on NewDot like in this case, it will be forwarded to them as an unread Message Summary minutes later.

I'm not sure I follow this part. There's no message summary if there's no report 😕

**Comment by Gonals** [comment]
A few more questions:
> It should come from [notifications@expensify.com](mailto:notifications@expensify.com)
That's what it currently does, but using the name of the inviter (so From: Inviter <notifications@expensify.com>). Is that what we want?

If so, the Subject seems redundant.

> In the Footer, [www.expensify.com](http://www.expensify.com/) would link the individual to the inbox.

They need to validate their account. Shouldn't this link be the validation link?

**Comment by danielrvidal** [comment]
>I'm not sure I follow this part. There's no message summary if there's no report 😕

Aw, good call. I forgot to update for Classic behavior. I believe the best course of action would be to send the email/SMS immediately. 

>If so, the Subject seems redundant.

I think it still would look good to call out the name/email of the individual. It's also how we do requests/etc. still using the name where we can so would just stick with that for now. 

>They need to validate their account. Shouldn't this link be the validation link?

Good call on the validation link. If they have not validated their account, it should be the validation link. Then it would point to the workspace chat after validation.

**Comment by Gonals** [comment]
This should be done, right?

**Comment by danielrvidal** [comment]
Yup, this is done. My bad.
