### ISSUE TITLE
Starting a chat with a new user show as a group chat in the header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38965]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711087497811689

## Action Performed:
Start a chat with a new user
Send a message

## Expected result:
The chat header should display a single user

## Actual result:
The chat header displays the header of a group chat, containing both participants emails

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a6770edf-2660-4de3-ae59-0cd1838f2278

https://github.com/Expensify/App/assets/38435837/13a23730-2979-415d-9bb6-8346c77ecfb9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I think this is an artifact of the on-going group chat migration and implementation. @marcaaron Does that sound right?

**Comment by JmillsExpensify** [comment]
Feel free to close if we already have an existing issue, or this will be resolved following implementation.

**Comment by marcaaron** [comment]
Yep, working on this [here](https://github.com/Expensify/Expensify/issues/382702)
