### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] [Track Expense] Adding Track Expense to Workspace Chats

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#38971]
In this [PR](https://github.com/Expensify/App/pull/37282), we added the ability for you to track expenses from the global create / selfDM. These would go directly to your self-DM.

In the context menu for a workspace chat, we're going to also add the ability to track expenses. This won't go to your self-DM, but these transactions will instead be added to the new / existing money request chat of the workspace chat.

![Screenshot 2024-03-25 at 5 12 22 PM](https://github.com/Expensify/App/assets/30609178/dabd8531-9acb-41b2-853b-1c3a806e7b16)

TrackExpense uses the same parameters as RequestMoney so they should be used in the same way
```
amount
currency,
comment,
created,
merchant,
iouReportID
chatReportID
transactionID,
reportActionID
createdChatReportActionID
createdIOUReportActionID
reportPreviewReportActionID
receipt
category,
tag,
receiptID
transactionThreadReportID
createdReportActionIDForThread
taxCode,
taxAmount
gpsPoints,
```

Something to note here is that for the self-DM, we created IOU reportActions directly on the chat report. However, when we're tracking in a workspace chat - the handling will be very similar to the request money flow where the IOU reportAction is added to the expense report. The only difference is that creating a tracked expense will just add a non-reimbursable expense to the report, so it shouldn't adjust change how much is owed
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118fd1f0c99c73336</li>
        <li>Upwork Job ID: 1772417470222831616</li>
        <li>Last Price Increase: 2024-03-26</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>paultsimura | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment]
@shubham1206agra Having you C+ this one since you did the Track Expense on the self-DM and have the context

**Comment by isabelastisser** [comment]
@paultsimura, your payment has now been processed in Upwork.

@shubham1206agra, please accept the offer, and I will process the payment. Note that the Upwork offer expires tomorrow, April 27th. I will DM you for visibility. Thanks!
