### ISSUE TITLE
#admin room system message shows workspace owner taking action when user joins the team themselves

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38975]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711387319175899

## Action Performed:
1. As a admin of the workspace (Account A) invite an user (Account B) manually from the OldDot
2. Log in to NewDot as workspace admin 
3. Go to` #admin` room of the workspace created in step 1
4. As another existing expensify user (Account C) join the same workspace by clicking the joining link or. "join team" CTA
5. Go to ` #admin` room of the workspace created in step 1

## Expected Result:
The system message should be different

## Actual Result:
This shows the workspace owner as taking the action, regardless of whether it's a manual invite or the user joining themselves

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/512da0a2-6e9f-4505-a9a2-9c15582e6bb9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01abf5832df8eeeda0</li>
        <li>Upwork Job ID: 1772434575924236288</li>
        <li>Last Price Increase: 2024-03-26</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment]
@twisterdotcom yeah I agree, this would be a good consideration! Mind assigning me to this issue?

**Comment by dylanexpensify** [comment]
@deetergp we'll want to tackle this as part of our project! Moving to weekly for now until after we've done the audit

**Comment by deetergp** [comment]
This definitely falls within the scope of our project @dylanexpensify 👍

**Comment by deetergp** [comment]
Settle down, Melvin.

**Comment by dylanexpensify** [comment]
Melvin, we're not ignoring you, just waiting to tackle you once our DD is ready for implementation!

**Comment by dylanexpensify** [comment]
Same

**Comment by dylanexpensify** [comment]
@deetergp for my own thinking, how did we wanna tackle this in the detailed portion?

**Comment by deetergp** [comment]
Okay, so thinking through this, we have as situation where a user on the same domain that has a policy they have not yet joined, decides to click the "join" link , and when they do, the system message we create says that the admin for that policy added that user rather than saying that user elected to join the policy. Is that right? It does seem pretty edge case-y. My guess is that's a situation we never considered and might require a new kind of report action. I'll dig further tomorrow morning.

**Comment by twisterdotcom** [comment]
That is correct yes @deetergp. I included these screenshots in the Slack bug report for how we show it in Expensify:
![image](https://github.com/Expensify/App/assets/9133401/f4e54334-7bba-4563-a16e-4ff153619df4)

vs the logs:
![image](https://github.com/Expensify/App/assets/9133401/67f20801-795d-4c40-881f-78a195ca1e1f)

This was triggered by real user confusion so I think we need to handle it: https://github.com/Expensify/Expensify/issues/380994.

**Comment by dylanexpensify** [comment]
Perfect, thanks!

**Comment by dylanexpensify** [comment]
Will be tackled by our project, and we're in review for detailed atm

**Comment by dylanexpensify** [comment]
Ongoing, project is almost done with detailed review. Then we can get this added to our list of issues to tackle.

**Comment by dylanexpensify** [comment]
@deetergp tying to [here](https://github.com/Expensify/Expensify/issues/347391)

**Comment by dylanexpensify** [comment]
Ongoing

**Comment by dylanexpensify** [comment]
Same as before

**Comment by dylanexpensify** [comment]
@deetergp mind giving an update when you can

**Comment by deetergp** [comment]
This completely fell off my radar since I hadn't self-assigned it.

**Comment by deetergp** [comment]
I was able to recreate this locally after realizing the missing piece was that I needed to use a non-public email address with the following steps:
* As scott@scottdeeter, I created a collect workspace 
* I invited scott+admin@scottdeeter.com to be an admin on the new policy
* In a separate browser session, I logged in as scott+userb@scottdeeter.com and found the Inbox card that asked me if I wanted to join
* I click the "Join the team" button.

This was the result in the `#admins` room, viewed as scott@scottdeeter.com
![Screenshot 2024-07-01 at 10 26 57 AM](https://github.com/Expensify/App/assets/766197/12c08d3d-2f13-4013-b74e-04c88a062836)

Looking at what is in the database for that `#admins` room, I see this:
```
sqlite> SELECT * FROM reportActions WHERE reportID = 5501981237864128 ORDER BY created;
created                  reportID          accountID  action                        message                                                                                                                                 reportActionID
-----------------------  ----------------  ---------  ----------------------------  --------------------------------------------------------------------------------------------------------------------------------------  -------------------
2024-07-01 17:18:19.054  5501981237864128  0          CREATED                                                                                                                                                               3004911851250377445
2024-07-01 17:18:38.431  5501981237864128  160        POLICYCHANGELOG_ADD_EMPLOYEE  {"accountID":0,"email":"scott+admin@scottdeeter.com","lastModified":"2024-07-01 17:18:38.431","name":"","role":"admin"}                 915281286465194525
2024-07-01 17:20:19.382  5501981237864128  160        POLICYCHANGELOG_ADD_EMPLOYEE  {"accountID":"686","email":"scott+userb@scottdeeter.com","lastModified":"2024-07-01 17:20:19.382","name":"Scott Deeter","role":"user"}  637304944292858797
```

We are obviously looking at the `accountID` to decide who took the action and it looks like maybe we should be looking at `message->>'$.accountID'` to determine attribution.

**Comment by deetergp** [comment]
We have somewhat mis-appropriated the `POLICYCHANGELOG_ADD_EMPLOYEE` action for this but we really don't take into account how any of these users were added. We pass the previous list of policy members, then pull a new list of policy member, and for all the new policy member, we log a `POLICYCHANGELOG_ADD_EMPLOYEE` action and attribute it to the policy owner's accountID when we create it. ([link](https://github.com/Expensify/Web-Expensify/blob/e2746fe75ce0d54952caa6f9450b89f5fb3f89dd/lib/Policy/Utils.php#L631-L646))

**Comment by dylanexpensify** [comment]
Got it! Seems like a fairly straightforward fix then?

**Comment by deetergp** [comment]
I've been lost in Doc Land for the last couple days. Hope to get back to this today or Friday.

**Comment by deetergp** [comment]
No progress, hoping to get back into this later today.

**Comment by dylanexpensify** [comment]
Nice, sounds good!

**Comment by dylanexpensify** [comment]
@deetergp any ETA on this one?

**Comment by deetergp** [comment]
I am chasing LHN unreads and firing on all cylinders trying to get Guided Setup Stage 3 out the door, so this isn't my most pressing priority. I'll hopefully have some bandwidth again by Wednesday. 🤞

**Comment by dylanexpensify** [comment]
Sounds good, thanks @deetergp!!

**Comment by dylanexpensify** [comment]
Not forgotten, but not the highest priority. Scott is on it!

**Comment by deetergp** [comment]
> @deetergp any updates on this one?

Got two PRs in review to sort this one out.

**Comment by dylanexpensify** [comment]
herooooo! TY!

**Comment by dylanexpensify** [comment]
Hmmm this should be done, right?

**Comment by deetergp** [comment]
It is… I suspect our automations for the Expensify/Expensify repo don't auto-close issues in the Expensify/App repo. Closing now!
