### ISSUE TITLE
[HOLD for payment 2024-04-25] [$250] HIGH: [Comment linking] Update thread headers / ancestry to deep link back to the original comment

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#38979]
Problem:
===
When you click into a thread, the header says:

* First line: `(the comment that is being threaded)`
* Second line: `From (the room containing the comment being threaded)`

When you click the second line, it does open the parent room.  However, it scrolls to the bottom of that room, losing context.

Solution:
====
Now that we have comment linking, when you click the second line, deep link directly to the comment that this thread is under.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013ec77e7b4b484ddd</li>
        <li>Upwork Job ID: 1775298204363497472</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by quinthar** [comment]
@perunt - Can you take this one?

**Comment by quinthar** [comment]
Actually, nevermind, dupe of this: https://github.com/Expensify/App/pull/38722#issuecomment-2019552569

**Comment by quinthar** [comment]
Reverted, reopening

**Comment by quinthar** [comment]
@rayane-djouah What is your ETA for fixing this?

**Comment by quinthar** [comment]
how about $250 for the bounty?

**Comment by quinthar** [comment]
What's the ETA in this? Is anything blocking it? Can we get this done today?

**Comment by quinthar** [comment]
Great!!

**Comment by puneetlath** [comment]
Looks like @rayane-djouah implemented this and @rushatgabhane was the C+ is that right?

**Comment by puneetlath** [comment]
Payment Summary: 
- C - $250 - @rayane-djouah - to be paid via Upwork
- C+ - $250 - @rushatgabhane - to be paid via NewDot

@rayane-djouah did you get an offer from the automation above?

**Comment by puneetlath** [comment]
I think it's this one: https://www.upwork.com/nx/wm/offer/102047743

Ping me here when you've accepted @rayane-djouah

**Comment by puneetlath** [comment]
Ok great. @rayane-djouah has been paid. @rushatgabhane please request on NewDot. 

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
