### ISSUE TITLE
[$500] Make all emails from concierge@expensify.com come from "Expensify" as the sender 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#39004]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.56-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** NA
**Email or phone of affected tester (no customers):** NA
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 NA 
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MitchExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C03U7DCU4/p1711406770617419

## Context

We changed how emails from Concierge send here https://github.com/Expensify/Expensify/issues/332434#issuecomment-1815410684 because we want "Expensify" to be included in the sender's name. That change made Concierge be called "Expensify Concierge _in product_ which we now want to revert. We are making sure Concierge appears as "Concierge" _in product_ which is being handled externally [here](https://github.com/Expensify/App/issues/38764) but we want emails from concierge@expensify.com to all come from "Expensify" as the sender which is being handled **here** internally. 

## Action Performed:
1. Sign up with an email to NewDot

## Expected Result:
All emails from concierge@expensify.com should come from "Expensify" as the sender, not "Expensify Concierge" 

## Actual Result:
All emails from concierge@expensify.com come from "Expensify Concierge", not "Expensify"

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="994" alt="image" src="https://github.com/Expensify/App/assets/36425901/c5ef967a-0011-481e-85ec-a21d6cec34ba">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a978a41ae7cb5345</li>
        <li>Upwork Job ID: 1772677546821468160</li>
        <li>Last Price Increase: 2024-03-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by justinpersaud** [comment]
This is an internal backend issue

**Comment by adelekennedy** [comment]
internal but still no takers

**Comment by adelekennedy** [comment]
since this is polish I am going to make this a weekly

**Comment by adelekennedy** [comment]
Again - it's a polish so I'm not sure if we really want to push this as an internal issue with all the competing priorities

**Comment by blimpich** [comment]
Picking up, this should be pretty quick.
