### ISSUE TITLE
[HOLD for payment 2024-04-09] [Simplified Collect][Members] Polish items for Transfer owner flow

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39005]
cc @burczu Coming from [this PR](https://github.com/Expensify/App/pull/37869#pullrequestreview-1961050431), there are a few polish items that need to be handled:

1. Wrong error flashes momentarily

https://github.com/Expensify/App/assets/22219519/5aa30edd-7614-4249-9751-5ecfaf636d73

2. We're showing an error screen on success after adding a debit card

https://github.com/Expensify/App/assets/22219519/99212ff8-ddf7-4a47-a45a-3ee3b2e95ebd

3. We're showing three decimals for USD currency

![three_decimals](https://github.com/Expensify/App/assets/22219519/43705f7f-0881-4c27-8d84-cff5f6c5023a)

**Comment by luacmartins** [comment]
cc @burczu

**Comment by burczu** [comment]
Hey @luacmartins, please assign me to this issue as this is a follow up issue for my recently merged feature. Thank you!

**Comment by burczu** [comment]
@luacmartins Offline state is handled from the very beginning of working on this issue: 

https://github.com/Expensify/App/blob/9d9757ffb3dfdad5dbd3dc13cd962faf5e1249d4/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L136

![Screenshot 2024-03-27 at 08 39 13](https://github.com/Expensify/App/assets/7771498/cee77447-0edc-419b-ba16-5db3a376aadf)

Could you provide your steps to reproduce it? Maybe you've found some edge case scenario?

**Comment by luacmartins** [comment]
Oh maybe, the App wasn't actually offline when I checked. Seems like this is already done, so let's move on to the other items in the list!

**Comment by burczu** [comment]
> Oh maybe, the App wasn't actually offline when I checked. Seems like this is already done, so let's move on to the other items in the list!

Yeah - I've actually done all of it today (you can check on the draft PR). Tomorrow morning I'll fill the checklist, add videos and publish it.

**Comment by luacmartins** [comment]
PR merged

**Comment by luacmartins** [comment]
Found another bug on the API level, put up a PR with a fix

**Comment by luacmartins** [comment]
No need for BZ checklist, this was a new feature in implementation.
