### ISSUE TITLE
Live Markdown Composer Issues

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#39006]
Coming from this [PR](https://github.com/Expensify/App/pull/38152), there's a few scrolling / cursor issues that come from how we're handling text & linebreaks 

The main issue that should fix all of those is https://github.com/Expensify/react-native-live-markdown/issues/239

We're just going to keep tracking all the issues that come up in this main tracking issue 
- Pasting text introduces extra line breaks between paragraphs
- The cursor is jumping weirdly when navigating through keyboard on quoted blocks
- When I paste large text with a mention in it the cursor gets placed inside the mention instead of the end of the text
- ~There is unused space in the composer when expanding the composer (The scroll does not extend throughout the composer height when clicked on the expand icon on the top left of the composer)~

**Comment by BartoszGrajdek** [comment]
1st & 2nd are likely related to the issue mentioned, we're not sure about the 3rd bug @Skalakid is investigating that one. I already have a fix ready for the 4th bug, but I'm still testing it - this is a problem with styles in the Expensify App

**Comment by thienlnam** [comment]
Great thanks, I'll go ahead and update the description

**Comment by BartoszGrajdek** [comment]
> There is unused space in the composer when expanding the composer (The scroll does not extend throughout the composer height when clicked on the expand icon on the top left of the composer)

Fixed ✅

**Comment by thienlnam** [comment]
Merging this into the main tracking issue now that this is merged! https://github.com/Expensify/App/issues/36071

**Comment by Skalakid** [comment]
Hi @thienlnam, I prepared the [PR](https://github.com/Expensify/App/pull/39177) that fixes:
- Pasting text introduces extra line breaks between paragraphs
- When I paste large text with a mention in it the cursor gets placed inside the mention instead of the end of the text
