### ISSUE TITLE
Deleted Tasks inside threads are counted in the thread reply count

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39016]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @fedirjh 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711463195704049

## Action Performed:

1. Open a chat and Start a new thread
2. Create a new Task inside the thread
3. Navigate to task and delete it
4. Go back to main chat

## Expected Result: 
The correct number of replies is displayed for every thread

## Actual Result: 
Deleted task is counted in the thread reply count

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e7d4b412-3733-4f17-b250-1baadaf9e2e7

https://github.com/Expensify/App/assets/38435837/cce11ee2-746b-4b5b-b942-42589b5162e3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
I think this is expected and makes sense to me - the task is deleted but its existence is maintained by the deletion text, so I'm going to close this for now to focus on higher prio roadmap items

**Comment by bernhardoj** [comment]
@fedirjh oh, I just found out that we already have an issue for this [here](https://github.com/Expensify/App/issues/33734), so we can keep this closed.
