### ISSUE TITLE
Add support for broken bank connect `warn`

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#39026]
We eventually need to add support for `warn` violations due to broken "530" bank connections. That said, this is an uncommon violation and we don't support managing either personal bank connections in Expensify, and same goes for centrally-managed cards. So for the time being this is a placeholder issue, and we'll circle back to supporting this violation as soon as bank connections can successfully be managed in NewDot. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0196750606d1382d6a</li>
        <li>Upwork Job ID: 1772753205589622784</li>
        <li>Last Price Increase: 2024-03-26</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
This is a tracking issue for now and won't be prioritized for some time, so I'm only assigning myself.

**Comment by JmillsExpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
@joekaufmanexpensify Do you potentially want to take this one on? I think it's related to the project that you're working on. The gist is that we need to add support for two very specific violations, which are only triggered when a third-party card feed breaks.

**Comment by JmillsExpensify** [comment]
![CleanShot 2024-06-19 at 15 50 38@2x](https://github.com/Expensify/App/assets/1127863/f90f069b-078d-4d13-84f8-869e2f630917)

They were out of scope for the original violations doc.

**Comment by joekaufmanexpensify** [comment]
Cool cool, so the first one is a soft warn violation triggered when the card feed is broken that we can't auto-match cash/card transactions? 

For the second one, is that different from what we added in [this project](https://github.com/Expensify/Expensify/issues/372206)?

**Comment by JmillsExpensify** [comment]
Oh yes, sorry for the confusion. I was just referring to the first violation, not the second one.

**Comment by JmillsExpensify** [comment]
We should probably start prioritizing this violation as soon as we get third-party feeds in play.

**Comment by joekaufmanexpensify** [comment]
Agreed, that makes sense to me. Happy to take this one. In fact, I kinda wonder if we shouldn't just fold this into the direct connections design doc, which I'm writing right now. I imagine it would be super quick to spin up a mock for this, and the doc already includes [resolving broken connections](https://expensify.slack.com/archives/C06ML6X0W9L/p1721838637891309), and this is directly related to that.

**Comment by joekaufmanexpensify** [comment]
Researching this. Relevant thread [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1711061161691269?thread_ts=1711049271.540289&cid=C06ML6X0W9L).

**Comment by joekaufmanexpensify** [comment]
Existing relevant figma file is [here. ](https://www.figma.com/design/Y17Cp4mJELHzXiAXJOq5QJ/Wave-7%3A-Collect-Approvers?node-id=1099-12210&node-type=frame&t=aC1wouYHKPSbt8gn-0)

**Comment by joekaufmanexpensify** [comment]
Next steps for me: 

- Put together updated mocks. 
- Run a mini pre-design to outline how this violation will work. 
- Add to the [Third-party workspace card feeds V2 (direct feeds)](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit) design doc (which is currently in detailed drafting).

**Comment by joekaufmanexpensify** [comment]
[Predesign](https://expensify.slack.com/archives/C06ML6X0W9L/p1726857897264549) for this is live!
