### ISSUE TITLE
[Awaiting Payment 23rd April] [$250] Deprecate `policy.role` in favor of `employeeList`

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#39025]
From this internal [conversation](https://expensify.slack.com/archives/C03TQ48KC/p1711487165179649?thread_ts=1711481616.732939&cid=C03TQ48KC), we want to deprecate `policy.role` in favor of `employeeList` to check the current user's role:

```
As a summary, I think ideally what we need to make happen is:
1. Update App so it fetches a policy role in the correct place (using employeeList, not top-level role which does not exist in the database)
2. Undo sending the role top-level policy attribute to Onyx
```
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d08fbf19a9080a89</li>
        <li>Upwork Job ID: 1782708664427339776</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>getusha | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
On hold for https://github.com/Expensify/Auth/pull/10367

**Comment by marcochavezf** [comment]
Still on hold

**Comment by marcochavezf** [comment]
Sounds good, I will work on it tomorrow

**Comment by marcochavezf** [comment]
Ok, we'd need to deprecate `policy.role` first from the frontend in favor of [employeeList](https://github.com/Expensify/App/blob/fb31fb12c8737af9062938de6e462f6a6bcfa93f/src/types/onyx/Policy.ts#L335-L336) and then remove all the `role` instances from Auth. Looking for a contributor to help with the first part

**Comment by marcochavezf** [comment]
Assigning @shubham1206agra to implement the first part. Meanwhile, I will be working on the backend part.

**Comment by marcochavezf** [comment]
Cool, thanks!

**Comment by marcochavezf** [comment]
[PR](https://github.com/Expensify/Auth/pull/10500) for the backend change on hold

**Comment by marcochavezf** [comment]
On hold for https://github.com/Expensify/App/pull/40178

**Comment by trjExpensify** [comment]
>But we should hold this for https://github.com/Expensify/App/pull/39489

@shubham1206agra, we've merged #39489. Can you fix conflicts and put https://github.com/Expensify/App/pull/40178 in review today, please? Thanks!

**Comment by trjExpensify** [comment]
What backend changes, exactly? 

- The backend PR for https://github.com/Expensify/App/pull/39489 is on production:

<img width="1317" alt="image" src="https://github.com/Expensify/App/assets/16232057/cf24926e-e23b-4f11-b07a-3866e2d8f685">

- @marcochavezf's backend PR for this issue is [supposedly held](https://github.com/Expensify/App/issues/39025#issuecomment-2057540488) on your frontend PR. Is that incorrect?

**Comment by trjExpensify** [comment]
@flodnv confirming we need to pay out $250 each to @getusha & @shubham1206agra for the work to date on the PR?

**Comment by flodnv** [comment]
Yes

**Comment by marcochavezf** [comment]
Assigning the bug label to handle the payment

**Comment by trjExpensify** [comment]
[Offers](https://www.upwork.com/ab/applicants/1782708664427339776/offers) have been sent to you both. 

Confirming payment summary as follows:

- $250 to @getusha for partial review of the PR 
- $250 to @shubham1206agra for the partial work on the PR

**Comment by trjExpensify** [comment]
Paid @shubham1206agra. @getusha let me know here when you accept, as this job in Upwork isn't assigned to me so I won't get a notification otherwise. :)

**Comment by trjExpensify** [comment]
paid @getusha, closing!
