### ISSUE TITLE
[$250] [HOLD for payment 2024-04-09] [HOLD for payment 2024-04-05] [Dev] Infinite loop of GetOlderActions calls

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#39028]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** only reproducible on dev at the time of creating - 1.4.56-6 at the time of wriging
**Reproducible in staging?:** no
**Reproducible in production?:** no
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711476371378119?thread_ts=1711147499.521539&cid=C049HHMV9SM

## Action Performed:
1. Open a report
1. Go offline
1. Send a message
1. Delete the message
1. Go online

## Expected Result:
1. The message you sent and deleted offline should be deleted.
1. The skeleton indicator should not appear indefinitely on the report. You should not see an infinite loop of `GetOlderAction` requests in the network tab.

## Actual Result:
Skeleton indicator appears and flashes infinitely, along with an infinite loop of `GetOlderActions` requests.

## Workaround:
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://expensify.slack.com/archives/C049HHMV9SM/p1711476420432379?thread_ts=1711147499.521539&cid=C049HHMV9SM

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017cac9b0408529fb8</li>
        <li>Upwork Job ID: 1778528999840456704</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
sup @kevinksullivan. I already have a WIP PR to fix this [here](https://github.com/Expensify/App/pull/39024). It's an hourly because it's reproducible only on dev. That means that as soon as we deploy staging it will become a deploy blocker

**Comment by roryabraham** [comment]
ok, jumping back into the [PR](https://github.com/Expensify/App/pull/39024)

**Comment by roryabraham** [comment]
Got that PR ready for review: https://github.com/Expensify/App/pull/39024

**Comment by kevinksullivan** [comment]
@ishpaul777 offer sent, lmk when you accept!

**Comment by kevinksullivan** [comment]
ah ok, weird haha. Thanks for letting me know. I will close this out then.
