### ISSUE TITLE
[HOLD for payment 2024-04-09] [HOLD for payment 2024-04-05] [$500]  Shortcut - Error shows up when creating second self-assigned task via Assign task shortcut

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self-DM
3. Create a task and assigned to self
4. Go to FAB
5. Click Assign task shortcut
6. Create another task which is assigned to self

## Expected Result:
The second task is created successfully

## Actual Result:
Error shows up when creating the second task via Assign task shortcut. The current user mention in the task becomes Hidden

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/38a71659-49e7-4ed3-b7e5-b8505fa4b706

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116839472c268c287</li>
        <li>Upwork Job ID: 1773049601832173568</li>
        <li>Last Price Increase: 2024-03-27</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@iwiznia  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by iwiznia** [comment]
Looks good to me

**Comment by sakluger** [comment]
There was a regression from the linked PR. The new PR to fix that regression is here: https://github.com/Expensify/App/pull/39328. We'll wait for that to be deployed before paying this one out.

**Comment by sakluger** [comment]
All paid, thanks everyone
