### ISSUE TITLE
Chat – Action menu opens down when pressing on the top of highlighted message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39044]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Navigate to chat with a long conversation history
4. Send a message
5. Highlight the last message and open action menu right clicking on the top part of it

## Expected Result:
Action menu opens up when pressing on the top of highlighted message

## Actual Result:
Action menu opens down when pressing on the top of highlighted message. The part of opened menu is not visible, unable to scroll it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fc76e887-614c-4778-88e9-db217c20cf90

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think that this bug might be related to #vip-vsb.

**Comment by izarutskaya** [comment]
Production


https://github.com/Expensify/App/assets/115492554/a8edcd6e-769c-4f9f-ad77-ae973bdd714a

**Comment by puneetlath** [comment]
@dukenv0307 thoughts?

**Comment by puneetlath** [comment]
Fix has been CP'd. Since it was fixed the the original PR author, I'm going to go ahead and close this issue.
