### ISSUE TITLE
VisionCamera V4 doesn't display cameraview when first enabling permission

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#39043]
### Problem

As noted [here](https://github.com/Expensify/App/pull/37483#pullrequestreview-1946105881), a bug exists where the camera doesn't render when first enabling the permission. It isn't 100% reproducible, but often occurs for me on a Pixel 6a, Android 14.

- Create a non-scan money request to someone
- Remove camera permissions
- Kill and reopen app
- Tap request money
- Try to scan receipt
- Permission prompt is shown
- Choose 'Just this time'
- Camera view remains black
- Close the page, then reopen it

https://github.com/Expensify/App/assets/10736861/83bf585b-72c3-4084-9089-87fec220a104

### Solution

???
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185191ddae0bea911</li>
        <li>Upwork Job ID: 1772952217490501632</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

**Comment by mrousavy** [comment]
👋

**Comment by mrousavy** [comment]
Isn't this a duplicate of https://github.com/Expensify/App/issues/38796?

**Comment by Julesssss** [comment]
Oh yep, I didn't realise. Closing
