### ISSUE TITLE
[HOLD for payment 2024-05-02] [$500] FEATURE REQUEST: Standardize the hover menu options to always include the same options

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39068]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
Currently, the hover options vary from line to line. Sometimes, it includes "Edit" and moves "Mark as unread" to the overflow menu (in the case of own message). Other times (for other user message), "Mark as unread is in the hover menu". We should standardize them so they are predictable.

## Solution:
Standardize the hover menu options to always include the same options:

- Default emojis (👍  / ❤️  / 😂  )
- Emoji selector (`Add reaction`)
- Reply in thread
- Mark as unread
- Overflow (Three-dots menu)

## Context/Examples/Screenshots/Notes:

![image (27)](https://github.com/Expensify/App/assets/38435837/c97ccd64-46ef-4c4c-88cd-59a1fdd08f39)

![image (28)](https://github.com/Expensify/App/assets/38435837/219541c4-c6b7-4509-b619-8f232774cb10)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @sakluger 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711490365341389

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acda50fccfd5bec3</li>
        <li>Upwork Job ID: 1775891174860582912</li>
        <li>Last Price Increase: 2024-04-04</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by godofoutcasts94** [comment]
Are these all the `ContextMenuOption` that we want  
<img width="1095" alt="Screenshot 2024-03-27 at 10 08 03 PM" src="https://github.com/Expensify/App/assets/158435970/847d85ff-5e1d-4acd-97ed-2475c0f5a102">
or we want more options inside it ? @muttmuure

**Comment by godofoutcasts94** [comment]
Updated [Proposal](https://github.com/Expensify/App/issues/39068#issuecomment-2023227321) with working video.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- FEATURE REQUEST: Standardize the hover menu options to always include the same options
### What is the root cause of that problem?
- Feature request, so do not need RCA
### What changes do you think we should make in order to solve the problem?
- If we just want to fix:
> Sometimes, it includes "Edit" and moves "Mark as unread" to the overflow menu (in the case of own message). Other times (for other user message), "Mark as unread is in the hover menu".

just need to move [this](https://github.com/Expensify/App/blob/e542ba7c2d9e216c2cd401de0de8ed225fff4a7b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L247-L262) to [this](https://github.com/Expensify/App/blob/e542ba7c2d9e216c2cd401de0de8ed225fff4a7b/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L212)

### What alternative solutions did you explore? (Optional)

- NA

**Comment by sakluger** [comment]
There was just the linked Slack thread, others recommend I write it up in #expensify-bugs. I don't think we need to push this through whatsnext since it doesn't require any BE work, I think we can just get a contributor to take it on.

**Comment by muttmuure** [comment]
Here is a thread with more details https://expensify.slack.com/archives/C03U7DCU4/p1711486539079619

**Comment by muttmuure** [comment]
Also going to tag @Expensify/design team for visibility

**Comment by JhainBolar** [comment]
Alright, so currently, when you hover over messages, the options you see can be a bit inconsistent. Sometimes you get "Edit" upfront, and other times "Mark as unread" hides in the overflow menu. It's a bit unpredictable, and we want to fix that.

Here's the plan: We'll tidy things up by creating a consistent hover menu for all message types. We'll dive into the code of our message component and make sure it's smart enough to display the right options based on whether it's your own message or someone else's.

Next up, we'll add some magic to detect when you hover over a message. We'll use React Native's tools to make sure that hover menu pops up exactly when and where it should, no surprises.

Styling-wise, we'll make sure the menu looks good and sits nicely next to the message, regardless of the layout. And of course, we'll put our creation to the test, making sure it behaves just right in all sorts of scenarios.

Once we're done, hovering over messages will feel consistent and intuitive, just like it should be.

**Comment by nkdengineer** [comment]
@shubham1206agra The select proposal does not point out how to refactor. Do you have any feedback about my proposal?

**Comment by godofoutcasts94** [comment]
I don't think the steps of refactoring is necessary as it is basically posting code diffs, is it @shubham1206agra ?

**Comment by nkdengineer** [comment]
Your proposal does not point out how to refactor. And your demo video also does not work. So I think it is not fair if C+ approves your solution just because you commented first

**Comment by godofoutcasts94** [comment]
Why are you even fixated on refactoring steps? As stated by @shubham1206agra it is not at all necessary. If you want to get your proposal selected, then please post first or else do one thing just tell C+ to always select you for all the issues, other folks are here just to play around

**Comment by godofoutcasts94** [comment]
Updated [Proposal](https://github.com/Expensify/App/issues/39068#issuecomment-2023227321) with correct video. Please check before making final decision @shubham1206agra

**Comment by muttmuure** [comment]
Still waiting for payment to process

**Comment by muttmuure** [comment]
Invited @nkdengineer

Paid @shubham1206agra

**Comment by nkdengineer** [comment]
@muttmuure Thank you 🙇 I've applied

**Comment by tylerkaraszewski** [comment]
What's this waiting on?

**Comment by muttmuure** [comment]
Extended contract to @nkdengineer

**Comment by muttmuure** [comment]
I was out for a few days, just waiting to pay @nkdengineer

**Comment by muttmuure** [comment]
@nkdengineer please accept the offer

**Comment by nkdengineer** [comment]
@muttmuure I accepted the offer!

**Comment by muttmuure** [comment]
Paid out
