### ISSUE TITLE
[HOLD for payment 2024-05-08] [HOLD for payment 2024-04-25] lockStagingDeploys workflow is failing

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39066]
After a recent TS migration, the Lock Staging deploy workflow seems to be failing https://github.com/Expensify/App/actions/runs/8450548625/job/23146944915#logs

Lets look into fixing this cc @JKobrynski 

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by mountiny** [comment]
This seems to be still erroring out https://github.com/Expensify/App/actions/runs/8521628536

**Comment by mountiny** [comment]
@JKobrynski failed again https://github.com/Expensify/App/actions/runs/8635295656

**Comment by mountiny** [comment]
This can be closed now

**Comment by mountiny** [comment]
https://github.com/Expensify/App/actions/runs/8786201271

Its still failing 😢

**Comment by mountiny** [comment]
No payments will be required, we just need to remove the debug logs added in the past

**Comment by johncschuster** [comment]
Thanks, @mountiny!

**Comment by johncschuster** [comment]
Bumping for Melvin. No action required at the moment

**Comment by mountiny** [comment]
I believe we are good to close this issue now since there is no regression testing required nor any payments
