### ISSUE TITLE
[HOLD for payment 2024-04-09] The deploy workflows fails to comment on deployed PR

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39067]
### Problem

The comment on issues step when PR is deployed to staging is failing after the recent Ts migration https://github.com/Expensify/App/actions/runs/8450250494/job/23146848625

### Solution

Fix it cc @JKobrynski

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by JKobrynski** [comment]
The [PR](https://github.com/Expensify/App/pull/39069) is ready for review!

**Comment by Christinadobrzyn** [comment]
Awesome! Thanks @JKobrynski cc @mountiny https://github.com/Expensify/App/issues/39067#issuecomment-2022981915

**Comment by mountiny** [comment]
I think this is fixed now and we can close as this is related to deployment pipeline
