### ISSUE TITLE
[HOLD for payment 2024-04-09] Distance rates - App shows the same icon for Enable rate and Disable rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/38799
## Action Performed:
Precondition:
- User is admin of Collect workspace
- The Collect workspace has at least one enabled and one disabled distance rate
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to Distance rates
4. Select the enabled and disabled distance rate
5. Click on the dropdown menu

## Expected Result:
App will show the correct icon for Enable rate

## Actual Result:
App shows the same icon for Enable rate and Disable rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1440" alt="Bug6428888_1711555624615!Screenshot_2024-03-28_at_00 03 10" src="https://github.com/Expensify/App/assets/78819774/389816c4-6ffa-49e3-b93f-9813fd1ce5e8">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by mountiny** [comment]
@dubielzyk-expensify Just want to confirm the Expensicons.Document and Expensicons.DocumentSlash is what we want to use here?

**Comment by mountiny** [comment]
yeah seems straightforward but not going to hurt to get Design eyes on this. I will handle this change internally.

**Comment by dubielzyk-expensify** [comment]
Yeah stick with that for now as that's what's in the intended design. I'll bring it to Slack for further discussion though

**Comment by mountiny** [comment]
Nothing to do here now I think
