### ISSUE TITLE
Distance rates - Empty space between distance rates after deleting and adding distance rate

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39083]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38799
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is admin of Collect workspace.
- There is only one distance rate in the workspace.
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > Collect workspace.
3. Go to Distance rates.
4, Add a distance rate.
5. Delete the distance rate in Step 4.
6. Add another distance rate.

## Expected Result:
There will be no spacing between first and second distance rate.

## Actual Result:
There is spacing between first and second distance rate.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c9aaaeaf-427f-44fe-9d3d-bebc1881b17e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to  #wave-control

**Comment by thienlnam** [comment]
Not a blocker / @Krishna2323 & @rushatgabhane Are you able to spin up a PR for this?

**Comment by rushatgabhane** [comment]
@thienlnam gimme a moment, I'll send a fix

**Comment by rushatgabhane** [comment]
@Krishna2323 yes please go ahead, that'd be great!

**Comment by thienlnam** [comment]
Yeah, not a problem - thanks!
