### ISSUE TITLE
[HOLD for payment 2024-04-09] [Wave Collect][QBO] Make it easy to conditionally add or remove routes/screens in `WorkspaceSettingsModalStackNavigator`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#39087]
As part of the QBO project, we're adding screens where workspace admins can configure accounting software integration. It's important that only admin users can access these screens.

The current code pattern doesn't allow for conditional access to screens/routes. Therefore, we need to refactor the code associated with the creation of navigators to facilitate the implementation of conditional or protected routes.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01959c603423a2c060</li>
        <li>Upwork Job ID: 1773049719285043200</li>
        <li>Last Price Increase: 2024-03-27</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
If we decide to not to use the pattern of conditional rendering the routes, we might want to undo changes made in this PR.

**Comment by twisterdotcom** [comment]
Okay, just going to pay @situchan $250 here.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @situchan paid $250 [here](https://www.upwork.com/nx/wm/offer/new/1017320902) (C+)

**Comment by situchan** [comment]
@twisterdotcom I haven't received payment yet. Can you please check?

**Comment by twisterdotcom** [comment]
Whoah you're right, I've no idea where this offer went. Try this now: https://www.upwork.com/nx/wm/offer/102382148

**Comment by situchan** [comment]
> And work was done before price drop announcement.

@twisterdotcom can you please check this?

**Comment by twisterdotcom** [comment]
I just added a bonus to that payment: https://www.upwork.com/nx/wm/workroom/37321844/overview
