### ISSUE TITLE
[TEST MONDAY] Chat - When navigation to an IOU link with no access, page keeps loading

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4455035
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in in the app
2. As account A, create an IOU with account B
3. Navigate to the IOU details page and copy the URL
4. Log out of Account A
5. Log in to another account C (can be any)
6. Paste and navigate to the IOU link from the previously copied

## Expected Result:
The IOU modal shows an error that the payment details cannot be found/Or a message that you have no access to this chat

## Actual Result:
The page keeps loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3413382d-0a5f-477a-bb8a-caf2db792414

![Bug6428977_1711559906663!IOUnoaccessloadsforever](https://github.com/Expensify/App/assets/78819774/34775335-35c5-43da-8353-ba7c42f24cdc)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #35132

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
My proposal here https://github.com/Expensify/App/issues/38826#issuecomment-2015716951 can fix this issue.

**Comment by garrettmknight** [comment]
Will likely fix in https://github.com/Expensify/App/issues/38826 - popping on hold while we investigate.

**Comment by garrettmknight** [comment]
Cool, will test Monday!

**Comment by garrettmknight** [comment]
Still on me to test.

**Comment by garrettmknight** [comment]
Tested, works!
