### ISSUE TITLE
Distance - Multiline description is rendered to a single line and editor field is shortened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a distance request with multiline description
4. Go to request details page
5. Note the description
6. Click Description

## Expected Result:
In Step 5 and 6, the description will remain in multiline format

## Actual Result:
In Step 5, the multiline description becomes a single line
In Step 6, the composer is shortened and user cannot scroll down to see the rest of content
This issue only exists for distance request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5227c0af-fdf0-4e0a-be15-1d8d3c50d031

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment]
Hm, I can reproduce this, but I am not convinced that anyone will really be trying to line-break a description on a distance request. This doesn't feel like a critical release 1 bug IMO. Going to close this for now so we can see if anyone actually experiences this. 

If they do, should be an easy fix.
