### ISSUE TITLE
[$250] "Route pending" does not update before hitting "Request" when recording distance 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#39104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** mitch@expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @MitchExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C03U7DCU4/p1711572307166239

## Action Performed:
1. "+"
2. "Request money"
3. Chose "Distance"
4. Enter start and stop points > "Next" 

## Expected Result:
You should be able to see the distance that was calculated before hitting "Request"

## Actual Result:
"Route pending" never updates 

## Workaround:
See distance after saving 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_4457 2](https://github.com/Expensify/App/assets/36425901/01c5c393-c127-4ebb-b52d-07b2265e2834)

Uploading RPReplay_Final1711572848 2.MP4…

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165a7992a3162105c</li>
        <li>Upwork Job ID: 1773359101650743296</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

**Comment by nkdengineer** [comment]
@MitchExpensify Seem like the video isn't uploaded completely, can you please upload this again?

**Comment by twisterdotcom** [comment]
I got a vid downgraded to potato qualify for GitHub, don't worry:

https://github.com/Expensify/App/assets/9133401/f258ad6f-ff52-4a47-be0f-0c49b5e349ab

💯 agree, it is odd not to see the distance until you create the expense.

**Comment by twisterdotcom** [comment]
@trjExpensify I think this belongs in Wave Collect.

**Comment by neil-marcellini** [comment]
I don't think this is a bug since it only happens for P2P distance. Discussing internally in Slack here https://expensify.slack.com/archives/C03U7DCU4/p1711572307166239.

**Comment by MitchExpensify** [comment]
Thanks for your context @neil-marcellini ! Closing as we already have plans in motion to fix this
