### ISSUE TITLE
[HOLD for payment 2024-05-02] [Wave Collect][QBO] Create a HOC to call `OpenAccountingPage` and then pass the `report.connections`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#39108]
Based on [the discussion](https://expensify.slack.com/archives/C03TQ48KC/p1711387863433689), implement a Higher-Order Component (HOC) that uses `useOnyx` to subscribe to policy data, then passes this data to the component it wraps. The HOC should inspect the `connections` field of the policy. If this field lacks a value in the policy data, the HOC should call `OpenAccountingPage`.

The HOC also should render the loading indicator or offline screen if necessary.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f138fc4382cdf6a</li>
        <li>Upwork Job ID: 1773765815925579776</li>
        <li>Last Price Increase: 2024-03-29</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
changing priority back to daily as this has the high priority

**Comment by strepanier03** [comment]
@hayata-suenaga - I am holding off labeling this Internal unless you give the go-ahead. I don't want to assign a C+ to do PR review when it's not needed.

**Comment by hayata-suenaga** [comment]
I decided to have a C+ review the PR just in case 😄

**Comment by hayata-suenaga** [comment]
I realized that a C+ is already assigned to the PR. I'll assign them to this issue.

**Comment by strepanier03** [comment]
Thank you @hayata-suenaga 🙌

**Comment by trjExpensify** [comment]
Is the PR for this now on hold for #39652, @hayata-suenaga? If so, let's have that reflected in the title.

**Comment by strepanier03** [comment]
PR is deployed to staging.

**Comment by hayata-suenaga** [comment]
The PR is actually still being worked on 🙇

**Comment by strepanier03** [comment]
@hayata-suenaga - sorry for the confusion, I meant the PR that this was on hold for is deployed to staging, not the PR for the fix for this issue 🤦‍♀️

**Comment by hayata-suenaga** [comment]
ah haha sorry for my misunderstanding 🙇 🙈

**Comment by strepanier03** [comment]
@hayata-suenaga - I was having a hard time figuring out the price here based on the PR that's linked. Is this a $500 payment or a $250 PR review payment?

**Comment by strepanier03** [comment]
nvm, @hayata-suenaga - payment summary finally posted and I got my answer.

**Comment by strepanier03** [comment]
### Payment summary

- $250 to @mollfpr via Manual Request in Newdot

@JmillsExpensify - Payment request incoming!

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr
