### ISSUE TITLE
Bank account - Entering date of birth while offline leads to empty fields on the double check page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39105]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4455008
**Email or phone of affected tester (no customers):**  applausetester+vd_web032724@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in and have created a workspace
1. Go to Workspace > Bank account
2. Click on "Connect online with Plaid"
3. Select Regions bank and enter the testing credentials
4. Enter the first and last name and continue
5. On the date of birth page, disable the internet connection
6. Select any date
7. Refresh the page
8. Enable internet connection
9. If the page do not auto-refresh, refresh the page manually
10. Verify the SSN page is displayed
11. Follow the flow until you reach the double check Personal info page
12. Verify there are some empty fields (previously filled)
13. Click on "Confirm"
14. Verify an error message appears

## Expected Result:
All the fields should be filled with the data previously entered

## Actual Result:
Some fields are empty on double check page and error message appears on confirmation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8fdece61-0345-40e1-8e2d-6b28d9abbdd9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01feebbe2887445d40</li>
        <li>Upwork Job ID: 1775369980205019136</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
BE issue, `OpenReimbursementAccountPage` request clears the draft.

<img width="363" alt="image" src="https://github.com/Expensify/App/assets/50919443/40f74dc9-49fa-4a0a-9fab-08e625e57fdd">

**Comment by JmillsExpensify** [comment]
Agree that this is a backend issue, adding the internal label.

**Comment by JmillsExpensify** [comment]
Going to add this to #wave-collect, though I'll note that the workspace editor in the testing steps is being deprecated (not the bank connect page though).

**Comment by JmillsExpensify** [comment]
Waiting to be picked up.

**Comment by JmillsExpensify** [comment]
Still waiting to be picked up.

**Comment by JmillsExpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
This isn't being prioritized internally, so I'm going to close and this can be re-opened when an Expensify engineer can take it on.
