### ISSUE TITLE
[TS Migration] Improve ref types across code base

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39116]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Work on improving ref types across the codebase

cc Could you share more details here please? @blazejkustra @fabioh8010

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by mountiny** [comment]
Assigned

**Comment by blazejkustra** [comment]
What are the next steps here? Should we close this issue?

**Comment by mallenexpensify** [comment]
PR was merged a couple weeks ago. @rushatgabhane , you reviewed and are due $250, right? 
- https://github.com/Expensify/App/pull/40698#issuecomment-2101802366

**Comment by mountiny** [comment]
Yes I think thats right @mallenexpensify

**Comment by rushatgabhane** [comment]
yes, thank you!

**Comment by mallenexpensify** [comment]
Contributor+: @rushatgabhane due $250 via Newdot

Guessingi we don't need a TestRail GH here, comment/reopen if ya disagree.

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
