### ISSUE TITLE
 [TS Migration] add declaration file for react-native-web

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39115]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Create a PR to react-native-web with declaration file (or at least post it somewhere so people can use it!)

Needs investigation still @blazejkustra @fabioh8010

**Comment by fabioh8010** [comment]
I'm Fábio from Callstack, an expert agency, and I’d like to work on this issue!

**Comment by mountiny** [comment]
Assigned

**Comment by roryabraham** [comment]
@fabioh8010 is this just about [this file](https://github.com/Expensify/App/blob/dfc7be9bd67acee2ba2253ab4afa41170e065bd9/src/types/modules/react-native-web.d.ts) ?

**Comment by hayata-suenaga** [comment]
react native web works by module aliasing `react-native` to `react-native-web`, right? why do we need a type file for `react-native-web`?

**Comment by fabioh8010** [comment]
@roryabraham @hayata-suenaga Our idea is to make [this augmentation here](https://github.com/Expensify/App/blob/main/src/types/modules/react-native.d.ts#L15) available to the community e.g. making a PR to `react-native-web` with those types OR a separate package.

**Comment by hayata-suenaga** [comment]
ahhhh i remember this from last year! We had to add some web specific prop/API type declarations!

Yes, let's make a PR to `react-native-web`. I think many people will appreciate it 🎉

**Comment by fabioh8010** [comment]
**Update:** Still focused on other TS / Wave stuff, will go back to this one when I have more time.

**Comment by fabioh8010** [comment]
Just FYI I'm going to be OOO next week and will return on May 6th. Will go back to it after vacations.

**Comment by fabioh8010** [comment]
**Update:** Still on hold

**Comment by hayata-suenaga** [comment]
This is not a priority issue

**Comment by fabioh8010** [comment]
*Update:* I will start working on this next week

**Comment by fabioh8010** [comment]
So first we'll have [this PR](https://github.com/Expensify/App/pull/45592) to clean up and update our RNW typings with the latest version. Then, I will proceed to suggest integrating this into RNW repo.

**Comment by mountiny** [comment]
So far no payments required

**Comment by roryabraham** [comment]
Rejected by RNW maintainer. Closing this w/ plan to :donothing:
