### ISSUE TITLE
[HOLD for payment 2024-05-22] [TS Migration] Adjust guidelines, both TS and JS markdown files

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39118]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Adjust guidelines, both TS and JS markdown files

cc @blazejkustra @fabioh8010 

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by mountiny** [comment]
On hold

**Comment by fabioh8010** [comment]
I'm Fábio from Callstack, an expert agency, and I’d like to work on this issue!

**Comment by mountiny** [comment]
Assigned, what are the next steps here?

**Comment by fabioh8010** [comment]
@mountiny I'm still focused on other TS / Wave stuff, let's wait this one a little more.

**Comment by JKobrynski** [comment]
I'm Julian from Callstack, an expert agency, and I’d like to work on this issue!

**Comment by JKobrynski** [comment]
The [PR](https://github.com/Expensify/App/pull/41212) is ready for review!

**Comment by mountiny** [comment]
This was merged

**Comment by alexpensify** [comment]
Thank you, @mountiny, for the update!

**Comment by laurenreidexpensify** [comment]
Payment summary:

- @fabioh8010 does not require payment (Contractor)

**Comment by alexpensify** [comment]
Thanks, @laurenreidexpensify, for your help here!
