### ISSUE TITLE
[HOLD for payment 2024-04-15] [$125] Feature Request: Update the `@here` text to change "room" to "chat"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39113]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

# Problem:
Use of the term "room" is confusing to users when they want to @here in a thread, since it's not obvious if it will tag only people in the thread or everybody in the whole channel. 

## Solution:
 Update the @here text to change "room" to "chat". 

## Context/Examples/Screenshots/Notes:

![Screen Shot 2024-03-27 at 6 25 10 PM](https://github.com/Expensify/App/assets/38435837/3325bfca-7495-494f-8c54-d9a192983601)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711567928507609

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f60e1f0a5d015f5</li>
        <li>Upwork Job ID: 1773464003280478208</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

**Comment by rafecolton** [comment]
Please hold 🙏 we are still discussing the exact text of this message and may want to edit it further

**Comment by rafecolton** [comment]
Latest [here](https://expensify.slack.com/archives/C03U7DCU4/p1711648276427779?thread_ts=1711564875.548399&cid=C03U7DCU4) (internal only) - cc @JmillsExpensify

**Comment by godofoutcasts94** [comment]
I think then you should put this issue on hold @rafecolton

**Comment by rafecolton** [comment]
Ok, off hold, we are changing it to `@here Notify everyone in this conversation` - note the removal of "online" and changing "chat" to "conversation"

**Comment by rafecolton** [comment]
@sakluger I think this can easily be done by a contributor. Both proposals are nearly identical and @GandalfGwaihir's came in about one minute before. I looked at the edit history and they did originally mention the Spanish translation as well. So I think we should go with their proposal.

**Comment by sakluger** [comment]
Thanks @rafecolton. Given how simple this change is, I'm going to set the price at $125. Let me know if you disagree.

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @GandalfGwaihir $125, sent offer via Upwork (https://www.upwork.com/nx/wm/offer/101873661/)
Contributor+: @allroundexperts $125, please request on Newdot

**Comment by JmillsExpensify** [comment]
$125 approved for @allroundexperts
