### ISSUE TITLE
[HOLD for payment 2024-07-17] [HOLD for payment 2024-07-10] [$500] [TS Migration] Adjust eslint config, TS config

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39119]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Błażej: Remove JS specific rules, merge some of them, disallow JS in TS Config, needs investigation

Also adjust https://typescript-eslint.io/rules/no-unused-vars/ Eslint rule to allow unused arguments starting with underscore

cc @blazejkustra @fabioh8010 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify / @bfitzexpensify</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify / @bfitzexpensify</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
Update: I was sick last week, I'm aiming to have a PR ready for review tomorrow.

**Comment by blazejkustra** [comment]
[Draft PR](https://github.com/Expensify/App/pull/40778) is up! cc @fabioh8010

**Comment by war-in** [comment]
We've decided to remove eslint rules in separate PR because of a huge amount of TS errors (check @blazejkustra's [comment](https://github.com/Expensify/App/pull/40778#discussion_r1577921318)). I'll take care of it

**Comment by bgawkuc** [comment]
Hi, as @blazejkustra and @war-in mentioned we'd like to split it into smaller PRs. I'd like to work on enabling `no-unsafe-call` eslint rule

**Comment by mountiny** [comment]
Thanks, please go ahead

**Comment by blazejkustra** [comment]
Update: We are still working on removal of these rules:
```ts
        '@typescript-eslint/no-unsafe-call': 'off',
        '@typescript-eslint/no-unsafe-member-access': 'off',
        '@typescript-eslint/no-unsafe-assignment': 'off',
```

@bgawkuc will post a draft PR today for the `no-unsafe-call` rule

**Comment by bfitzexpensify** [comment]
Adding a BZ buddy - I will be OOO until June 11th

**Comment by trjExpensify** [comment]
Alright, so just confirming the payment summary is as follows: 

$250 to @parasharrajat for the C+ review. 

Let me know if that's correct, and then I'll close and Rajat can submit an expense!

**Comment by blazejkustra** [comment]
@bgawkuc is working on enabling three more ESLint rules as part of this issue ([here](https://github.com/Expensify/App/pull/42743) is one ongoing PR). For some reason @parasharrajat wasn't assigned to it :/

**Comment by trjExpensify** [comment]
Oh okay.

**Comment by bgawkuc** [comment]
Update:
- [PR](https://github.com/Expensify/App/pull/42743) with enabling `no-unsafe-call` rule was merged
- I've just posted [draft PR](https://github.com/Expensify/App/pull/43557) with enabling `no-unsafe-member-access` rule
- one last rule left: `no-unsafe-assignment`

**Comment by bfitzexpensify** [comment]
How's this one looking @bgawkuc?

**Comment by mountiny** [comment]
Merged

**Comment by mountiny** [comment]
Yes I think $500 is deserved compensation for this issue

**Comment by trjExpensify** [comment]
Cool, put $500 in the title to not forget. Payout due on the 10th.

**Comment by trjExpensify** [comment]
I think this one is due. 

Payment summary as follows: 

- $500 to @parasharrajat for the review. 

Closing!

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat
