### ISSUE TITLE
[HOLD for payment 2024-05-02] [$250] [TS Migration] Remove underscore completely

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39121]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Remove underscore completely

Should be straightforward once ready, needs to be tested well

cc @blazejkustra @fabioh8010 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014598e5194edc8278</li>
        <li>Upwork Job ID: 1780195244607991808</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by blazejkustra** [comment]
**Details:**

Simply remove `underscore` package along with all the usage in the codebase, instead use  native methods or `lodash` as a last resort.

**Comment by mountiny** [comment]
Looking for proposlas on how to tackle this deprecation holistically, one or many PRs, how to divide them?

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by godofoutcasts94** [comment]
Do we need to post a formal proposal for it?

**Comment by aneequeahmad** [comment]
I can take up this issue

**Comment by mountiny** [comment]
Yes, please post how you want to approach this

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove the use of underscore

### What is the root cause of that problem?
None

### What changes do you think we should make in order to solve the problem?
All files that are using `underscore` now are `js` file. We can remove `underscore` belong with migrate these files to typescript.


<img width="259" alt="Screenshot 2024-04-16 at 18 30 21" src="https://github.com/Expensify/App/assets/161821005/f5c9001b-6319-4e65-b251-c5a792be132e">


### What alternative solutions did you explore? (Optional)
NA

**Comment by blazejkustra** [comment]
@hungvu193 TS migration is over, there are no more js files that need to be migrated (apart from prop types that will be removed soon) 🎉

**Comment by hungvu193** [comment]
Thanks @blazejkustra.

**Comment by hungvu193** [comment]
@bernhardoj's [proposal here](https://github.com/Expensify/App/issues/39121#issuecomment-2058887964) LGTM.
Just a suggestion, I think 1 PR is enough for removing `underscore` usages. The second PR should remove the `underscore` dependency, such as eslint config, webpack config,..

🎀 👀 🎀  C+ reviewed

**Comment by bernhardoj** [comment]
PR is [here](https://github.com/Expensify/App/pull/40346)

**Comment by blazejkustra** [comment]
> Just a suggestion, I think 1 PR is enough for removing underscore usages. The second PR should remove the underscore dependency, such as eslint config, webpack config,..

Why not just one PR that removes underscore completely?

**Comment by hungvu193** [comment]
> > Just a suggestion, I think 1 PR is enough for removing underscore usages. The second PR should remove the underscore dependency, such as eslint config, webpack config,..
> 
> 
> 
> Why not just one PR that removes underscore completely?

Oh I thought that will be a lots of changes if we include everything in a PR. But now I'm seeing that you're also reviewing it so I think that's fine with me.

**Comment by MitchExpensify** [comment]
Reminder set to Pay.

Payment summary:

$250 @hungvu193 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer)
$250 @bernhardoj requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor)

**Comment by MitchExpensify** [comment]
Paid and contracts ended
