### ISSUE TITLE
[TS Migration] Improve how Routes are validated

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39122]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Improve how Routes are validated (use AssertTypesEqual util)

cc Any more details to share here? @blazejkustra @fabioh8010

**Comment by smelaa** [comment]
Hi! I am Aleksandra Smela from SWM, an expert agency and I'd like to work on this issue.

**Comment by mountiny** [comment]
Seems like this is done
