### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [TS Migration] Add comments for remaining properties in Onyx types

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39129]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Add comments for remaining properties in Onyx types

Any more details for this one cc @blazejkustra @fabioh8010

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by fabioh8010** [comment]
This issue will be handled internally - we are deciding who is going to pick

**Comment by pac-guerreiro** [comment]
@fabioh8010 @mountiny 

I can work on this! 😄

**Comment by fabioh8010** [comment]
@pac-guerreiro Any updates here? What is the ETA for a Draft PR?

**Comment by fabioh8010** [comment]
A WIP Draft PR was created here -> https://github.com/Expensify/App/pull/41956

**Comment by mountiny** [comment]
@pac-guerreiro, can you please address the follow-ups I have mentioned in the PR? thanks!

**Comment by pac-guerreiro** [comment]
@mountiny I just opened a PR with the addressed follow-ups -> https://github.com/Expensify/App/pull/43499 😄

**Comment by mountiny** [comment]
No payments required here
