### ISSUE TITLE
[HOLD for payment 2024-05-06] [TS Migration] Migrate any leftover JS files 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39127]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Migrate any leftover JS files we have (styles/libs/components/pages)

Any more details for this one cc @blazejkustra @fabioh8010

**Comment by fabioh8010** [comment]
@ShridharGoel this one is going to be taken internally 🙂 

@mountiny Please assign it to me!

**Comment by fabioh8010** [comment]
**Update:** PR is under review and will hopefully be merged today. Just FYI I'm going to be OOO next week and will return on May 6th.

**Comment by laurenreidexpensify** [comment]
PR was deployed to staging on Fri

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- Contributor - no payment, agency @fabioh8010 
- C+ - $250 C+ review @s77rt - payment to be issued in Upwork

**Comment by laurenreidexpensify** [comment]
@s77rt pls accept offer in upwork thanks

**Comment by s77rt** [comment]
@laurenreidexpensify Accepted! Thanks!

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor - no payment, agency @fabioh8010
C+ - $250 C+ review @s77rt - payment issued in Upwork

No regression test required, Ts migration
