### ISSUE TITLE
[TS Migration] Investigate TS performance in the project 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39128]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Investigate TS performance in the project

Any more details for this one cc @blazejkustra @fabioh8010

**Comment by kubabutkiewicz** [comment]
Hi, I'm Jakub from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by mountiny** [comment]
@kubabutkiewicz what is the plan for this one? We would like to make sure we are not spending too much time on diminishing returns here so if you could lay out some plan for this to start with that would be great! thanks!

**Comment by fabioh8010** [comment]
@mountiny Let's close this issue, Jakub was assigned to work on a Wave feature so we won't have time for this anymore, and is not something we need to worry about right now.
