### ISSUE TITLE
[TS Migration] Update github action to disallow new JS files completely

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39123]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Update github action to disallow new JS files completely

cc @blazejkustra @fabioh8010

**Comment by mountiny** [comment]
On hold

**Comment by blazejkustra** [comment]
@fabioh8010 I think `.github/workflows/typecheck.yml` file is already adjusted, do we need this issue?

**Comment by fabioh8010** [comment]
The current action is only checking for new JS files under `src/`, we should check for other folders too:

- `__mocks__/`
- `.github/`
- `.storybook/`
- `assets/`
- `config/`
- `desktop/`
- `jest/`
- `scripts/`
- `tests/`
- `web/`
- `workflow_tests/`

**Comment by mountiny** [comment]
Created a Pr here https://github.com/Expensify/App/pull/40291

**Comment by blazejkustra** [comment]
Let's close this one @mountiny 🎉
