### ISSUE TITLE
[TS Migration] Remove all prop types 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39120]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Remove all prop types

Should be straightforward once ready

cc @blazejkustra @fabioh8010

**Comment by blazejkustra** [comment]
@mountiny Can we close this one, we chatted with FAbio and decided it would make more sense to do it as part of https://github.com/Expensify/App/issues/39127

**Comment by mountiny** [comment]
Closing in favour of https://github.com/Expensify/App/issues/39127
