### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] [Performance] Reduce the amount of expensive getOptions calls in Request Money flow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39133]
### Problem

When using Request Money flow, the getOptions function is called multiple times, doing heavy operations and slowing down the app. Based on a provided trace, a single execution of this function takes ~2.5s, and it is called when the following actions are performed:
- entering the Request Money participants list
- typing in the search input (each keystroke)
- pressing the option from the list
- pressing “split” on the option item

Additionally, the server search to get reports is also called on each keystroke.

All of this is making the app unresponsive for a long time, making it difficult to reach the next step of the money request process. The total amount of getOptions execution time in a provided trace was 29.7s.

### Solution
To address this problem, we should reduce the amount of getOptions calls to minimum. We can achieve this by:
- using debounced state instead of calling the function on each keystroke - this way we call getOptions and server search only when user is not typing in the input anymore
- properly memoizing the participants selector component - selecting the user from the list is updating the transaction, which triggers the heavy operation even if the participants list hasn’t changed

There is still need of calling the function when pressing “Split”, but there is a possibility we would be able to replace it with filtering once it’s implemented in the list (this is one of the efforts from the performance audit).
Considering the following scenario:
1. User requests money and goes to participants list
1. User types “workspace” in the search
1. User presses the selected option item

Before changes the getOptions was called 16 times, and after it is called 2 times.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e025ca125dedd18</li>
        <li>Upwork Job ID: 1773283266133659648</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by TMisiukiewicz** [comment]
Hey, I'm Tomasz from Callstack and I want to work on this issue

**Comment by mountiny** [comment]
$500 to @akinwale

**Comment by slafortune** [comment]
@mountiny @akinwale I believe that no regression test will be needed for this, can you confirm?

**Comment by mountiny** [comment]
No regression tests required here

**Comment by slafortune** [comment]
@akinwale please the offer sent [here](https://www.upwork.com/nx/wm/offer/101799683) $500
@TMisiukiewicz is from an agency-contributor and not due payment

**Comment by akinwale** [comment]
@slafortune Accepted. Thanks!
