### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] [TS Migration] Check and remove unnecessary @ts-expect-error suppressions

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39130]
Follow up issue for TS migration project. Coming from [this spreadsheet](https://docs.google.com/spreadsheets/d/1GVp81ixTZ3TIspkTsgfhSA72KZGHDJlwRa4J8TtCQU4/edit#gid=1579985166)

> Check and remove unnecessary @ts-expect-error suppressions

Any more details for this one cc @blazejkustra @fabioh8010
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa6db9b8ad4c4c3a</li>
        <li>Upwork Job ID: 1780318477113909248</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger / @MitchExpensify</details>

**Comment by Piyush-Desai** [comment]
Hey @blazejkustra 

Can you please share more details about it? I would like to have a look at this.

**Comment by blazejkustra** [comment]
**Details:**

We are aiming to get rid of all `@ts-expect-error` in the codebase, apart from these related to `REIMBURSEMENT_ACCOUNT` that has to stay for now:
```ts
    // @ts-expect-error: ONYXKEYS.REIMBURSEMENT_ACCOUNT is conflicting with ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM
```

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by florabtw** [comment]
# Proposal

Submitting my proposal here prior to submitting through Upwork.

## Solution

1. Pull local dev environment and follow [instructions ](https://github.com/Expensify/App?tab=readme-ov-file#local-development)to get set up
2. Search compiler warnings for `Unused '@ts-expect-error' directive`
3. Remove unnecessary instances of `@ts-expect-error`, double-checking compiler output

**Comment by florabtw** [comment]
Contributor details
Your Expensify account email: freelance@flora.cool
Upwork Profile Link: https://www.upwork.com/freelancers/flora

**Comment by c3024** [comment]
This is a TS migration issue and @ZhenjaHorbach called dibs first after adding `Help Wanted` tag. 

We can assign them.

🎀 👀 🎀 C+ Reviewed

**Comment by grgia** [comment]
All yours @ZhenjaHorbach

**Comment by sakluger** [comment]
PR is still in progress.

**Comment by Julesssss** [comment]
Am I mistaken, or did the wrong C+ and internal employee get assigned to the [PR](https://github.com/Expensify/App/pull/40627)? 

@grgia should you and @c3024 be assigned?

**Comment by sakluger** [comment]
Doesn't that mean that @c3024 should be added as a reviewer on the PR?

**Comment by sakluger** [comment]
[PR](https://github.com/Expensify/App/pull/40627) is still in review.

**Comment by sakluger** [comment]
Still in review.

**Comment by sakluger** [comment]
@MitchExpensify assigning you to help watch this issue while I'm OOO through May 31. Please handle payment if needed. I'll take back over if it's still open when I return.

For the latest update, https://github.com/Expensify/App/pull/40627 and https://github.com/Expensify/App/pull/42256 (which both fixed this issue) were both merged today.

**Comment by MitchExpensify** [comment]
Reminder set to pay on the 3rd

**Comment by MitchExpensify** [comment]
- $250 @ZhenjaHorbach requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor)
- $250 @c3024 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Reviewer)

Paid and contracts ended!
