### ISSUE TITLE
[New Feature] Add a "Request to join" flow for chats you do not have access to

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#39142]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/324451
**Issue reported by:** @MitchExpensify 

## Action Performed:

**A** - Requesting to join perspective:
1. Try to access a chat you do not have access to (E.g. A user trying to view a "Private" user created room)
2. See an "Ask to join" option on the "This chat is private" / "You don't have access to this chat" screen
3. Click "[Ask to join]" button
4. See "[Ask to join]" button change to greyed "[Request sent]"

**B** Chat perspective:
1. As any member of a private room or group view the room used in **A**
2. See an actionable system message "User name has asked to join this room/group name with the options to "[Accept]" or "[Ignore]"

## Workaround:
None

### `RequestToJoinChat` command
1. In `peek`:
    - Check if the report is a chat report. If not then we throw. If the chat report is a DM and not a thread, we throw.
    - If the chat report has already been shared with the user, return early.
    - If the `PENDING_JOIN_REQUEST_<ACCOUNTID>` rNVP has already been set, return early.
2. In `process`, we'll create a new report action called `JOIN_REQUEST` that will get sent into the chat report. This will prompt all members of the chat report to add the requester to the room. This will contain the following fields in the `message`:
    - requesterAccountID
    - reportID
3. We'll return the created report action in the jsonResponse to PHP. We'll allow PHP to handle notifying room participants of the report action.
4. Finally, we'll set the `PENDING_JOIN_REQUEST_<ACCOUNTID>` rNVP (create a new const for this). Its value will be the reportActionID of the `JOIN_REQUEST` action we created above.
5. Include logic in `ReportAction::buildLastMessageItem` that constructs the text last message for a join request.

### `ResolveJoinRequest` command
This will be very similar to the [`ResolveActionableMentionWhisper` command](https://github.com/Expensify/Auth/blob/main/auth/command/ResolveActionableMentionWhisper.cpp). We'll add a "resolution" field to the message of the JoinRequest with either RESOLUTION_ACCEPTED or RESOLUTION_DECLINED. If the resolution was "accepted", we'll invite the user and send out any necessary Onyx data. We'll also remove the `PENDING_JOIN_REQUEST_<ACCOUNTID>` rNVP.

## PHP
1. Create a new report action class for the `JOIN_REQUEST` action ([ex](https://github.com/Expensify/Web-Expensify/blob/main/lib/Report/Action/RoomChangeLog/JoinRoom.php)). Include it in `buildAction` [here](https://github.com/Expensify/Web-Expensify/blob/330f5fb3ff21e9afe1ae835bf45c3dc0c7149bb5/lib/Report/Action/Collection.php#L420).
2. Send back the `pendingJoinRequest<AccountID` rNVP to the requesting user in `structureReportForOnyx` in both Auth and PHP. We'll use this decide whether to display "Request sent".

### `RequestToJoinChat` command
1. Call the `RequestToJoinChat` Auth command.
3. if the Auth command returns a report action, send it to the room by calling [`buildActionAndNotifyParticipants`](https://github.com/Expensify/Web-Expensify/blame/330f5fb3ff21e9afe1ae835bf45c3dc0c7149bb5/lib/ReportUtils.php#L3539-L3546).

### `ResolveJoinRequest` command
This will be very similar to the [`ResolveActionableMentionWhisper` command](https://github.com/Expensify/Web-Expensify/blob/817b050e0856ec18437497b80fab5d1f3ebd2972/lib/ReportAPI.php#L5789). We'll call the Auth command and handle sending out the roomChangeLogData, and the participants and personalDetails Onyx updates.

## Screenshots/Videos

![CleanShot 2023-12-20 at 23 21 29](https://github.com/Expensify/Expensify/assets/145416827/09d6310a-a4b2-4b48-92c5-59ed90f4ff8f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2b2399b0ccf07b0</li>
        <li>Upwork Job ID: 1776363472659742720</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
Before I label "Bug", Does this look like sufficient information to you @jasperhuangg ?

**Comment by jasperhuangg** [comment]
@MitchExpensify took another and it makes sense to me. Should we add `Bug` or `NewFeature`?

**Comment by jasperhuangg** [comment]
@greg-schroeder we'll need an internal engineer to work on the back-end for this specified in the OP before an external contributor can handle the front-end portion.

**Comment by MitchExpensify** [comment]
NewFeature makes sense to me @jasperhuangg

**Comment by greg-schroeder** [comment]
Okay, set `Internal` and `Hot Pick`

**Comment by jasperhuangg** [comment]
To the internal engineer that takes up the back-end for this, I've posted a quick outline of how I imagine the back-end changes to look based on existing flows in our codebase [here](https://github.com/Expensify/Expensify/issues/324451#issuecomment-2019294153).

**Comment by greg-schroeder** [comment]
Thanks @jasperhuangg

**Comment by greg-schroeder** [comment]
No update here, not overdue

**Comment by greg-schroeder** [comment]
Any thoughts on who might be able to work on this @jasperhuangg? Or is it just sorta on hold indefinitely?

**Comment by jasperhuangg** [comment]
@greg-schroeder Not entirely sure of who would be a good candidate–just whoever has the space on their plate to look into things.

To clarify, this is not on HOLD and ready to be worked on!

**Comment by greg-schroeder** [comment]
Not sure, perhaps @trjExpensify can say, not sure where this fits

**Comment by trjExpensify** [comment]
VIP-VSB seems right as that's where launching user created rooms was built.

**Comment by greg-schroeder** [comment]
Still waiting for an engineer to grab this one!

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
Seems this is low priority, leaving Weekly for now

**Comment by greg-schroeder** [comment]
Same

**Comment by greg-schroeder** [comment]
Same

**Comment by greg-schroeder** [comment]
I'm going to close this, as it hasn't received attention in 6 months.

**Comment by jasperhuangg** [comment]
This is still a valuable feature to have for rounding out #vip-vsb for user-created rooms. I think we should probably keep it open.

**Comment by greg-schroeder** [comment]
All right, leaving open, but just waiting for someone to take it then.

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
#vip-vsb is now fully paused/closed, so I'm going to close this per: https://expensify.slack.com/archives/C066HJM2CAZ/p1727455774700809
