### ISSUE TITLE
Chat - Chat header hidden below app banner after dismissing the device keypad

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39156]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+cknov@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open ND staging & log in
2. Select any chat from LHN - admins, Concierge chat or 1:1 DM
3. Tap Done button on device keypad to dismiss the keypad
4. Scroll the conversation page & observe the chat header gets hidden below app banner

## Expected Result:
User able to access the chat header (back button, 3 dot menu & user's profile name) after dismissing the device keypad

## Actual Result:
Chat header hidden below app banner after dismissing the device keypad

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/78dd04d4-a952-4318-bda9-7b061d1c78df

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@miljakljajic I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the vip-vsb.

**Comment by miljakljajic** [comment]
@madmax330 do you think this can be worked on externally, and is it truly a DB?

**Comment by yuwenmemon** [comment]
Thanks @suneox 

Agreed @miljakljajic this isn't a deploy blocker.

**Comment by yuwenmemon** [comment]
Closing in favor of https://github.com/Expensify/App/issues/39061
