### ISSUE TITLE
[Simplified Collect][Taxes] - "Hmm it's not here" error appears briefly when opening taxes tab again

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39154]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57.2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/38375
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. OD: Log in with a new expensifail account
2. OD: Create a collect workspace with chat enabled
3. ND: Log in with the same admin account
4. ND: Go offline
5. ND: Navigate to Workspace settings - More features
6. ND: Enable taxes
7. ND: Navigate to Workspace settings - More features - Taxes
8. ND: Go online and wait for the taxes to turn white
9. ND: Naviate tack to Workspace settings
10. ND: Open taxes again

## Expected Result:
There shouldn't be any errors.

## Actual Result:
"Hmm it's not here" error appears briefly when opening taxes tab again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1aabc084-4933-46b6-82bc-be8982e0ab5d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/9d36107b-7dd3-402d-b90e-8760818fd442

**Comment by MonilBhavsar** [comment]
Commented on the offending PR

**Comment by luacmartins** [comment]
I'm unable to reproduce this

https://github.com/Expensify/App/assets/22219519/dbb33096-99fb-4d3c-b812-16427dbbe25d

**Comment by luacmartins** [comment]
Either way, I dont think this is a blocker since the functionality still works.

**Comment by rojiphil** [comment]
I also tried reproducing this issue but could not. Here is an attached test video.
Also, the BE is saving the default rates. Further, the default tax rates can be seen in OD also. So, the functionality works. 
Considering that we are unable to reproduce, I think it may be better to ask QA to reproduce this again. 

https://github.com/Expensify/App/assets/3004659/847d4418-3f7c-4b95-8cc9-3747a022c986

**Comment by trjExpensify** [comment]
@izarutskaya are you able to reproduce this?
