### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Expense - LHN preview does not show request description for request with description

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39158]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat that has no unsettled request.
3. Create a manual request with description.

## Expected Result:
In LHN, the workspace chat preview will show the request with description (production behavior).

## Actual Result:
In LHN, the workspace chat preview does not show the request description.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f96a75fd-d36a-422c-b712-01ed11356427

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5e205ddbd6e0a25</li>
        <li>Upwork Job ID: 1773353810716704768</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by Gonals** [comment]
> @MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

Adding external, as we seem to be setting the values correctly. We are just not displaying them

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In LHN, the workspace chat preview does not show the request description.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/libs/ReportUtils.ts#L2634), we didn't put the `comment` param

### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/4fbd2184458a9cbfee0380b571fc95bff042c0af/src/libs/ReportUtils.ts#L2634), put the `comment` param

### What alternative solutions did you explore? (Optional)
NA

**Comment by FitseTLT** [comment]
regression from  https://github.com/Expensify/App/pull/37773 it removed `comment`

**Comment by Gonals** [comment]
While this is a new bug, it is small enough (and quickly/easily fixable) that I don't think we need to block deploy on it

**Comment by Pujan92** [comment]
As it is a regression from https://github.com/Expensify/App/pull/37773, I think @mollfpr should handle this. In case they are not available then we can proceed with the proposal https://github.com/Expensify/App/issues/39158#issuecomment-2025376099. cc: @Gonals

**Comment by mollfpr** [comment]
I'll raise the PR shortly!

**Comment by MitchExpensify** [comment]
*Payment summary:*

- $500 @Pujan92 Upwork

**Comment by nkdengineer** [comment]
@MitchExpensify I think I'm also eligible for compensation here since the issue was External and [my proposal](https://github.com/Expensify/App/issues/39158#issuecomment-2025376099) was used to [fix the blocker](https://github.com/Expensify/App/pull/39208)

We had many similar cases like in [here](https://github.com/Expensify/App/issues/28417#issuecomment-1742008867).

What do you think?

**Comment by MitchExpensify** [comment]
@Gonals were the solutions [like](https://github.com/Expensify/App/issues/39158#issuecomment-2025376099) for [like](https://github.com/Expensify/App/pull/39208)?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by nkdengineer** [comment]
> @Gonals were the solutions https://github.com/Expensify/App/issues/39158#issuecomment-2025376099 for https://github.com/Expensify/App/pull/39208?

@Gonals Bump on [this](https://github.com/Expensify/App/issues/39158#issuecomment-2046094308), do you agree the solution used in the PR is the same as in the proposal?

Thanks 🙏

**Comment by MitchExpensify** [comment]
Offer sent to you here @Pujan92 https://www.upwork.com/jobs/~01f5e205ddbd6e0a25

Holding on buddy check on payment due to @nkdengineer

**Comment by Pujan92** [comment]
> Offer sent to you here @Pujan92 https://www.upwork.com/jobs/~01f5e205ddbd6e0a25

@MitchExpensify Thanks, Accepted!

**Comment by nkdengineer** [comment]
> Holding on buddy check on payment due to @nkdengineer

@MitchExpensify Could you help reopen the issue to handle this?

Thanks

**Comment by MitchExpensify** [comment]
Offer sent here @nkdengineer https://www.upwork.com/nx/wm/offer/102043113

Thanks for your patience, payment will be issued asap 🙇

**Comment by nkdengineer** [comment]
@MitchExpensify I accepted the offer, thanks 🙏

**Comment by MitchExpensify** [comment]
Great! Payment made and contract ended
