### ISSUE TITLE
[Performance] Setup reassure in react native onyx

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39164]
### Problem

React native onyx is the core of NewDot and as such any performance regressions in this low level code can have major impact on the performance of the app. There is no performance testing in this repository as of now.

### Why is it important?

We can introduce performance regressions in onyx code which might not be noticed until very late or hard to debug.

### Solution

Set up the reassure testing suite in the react-native-onyx repository so we can use the `measureFunction` methods to test the core methods in Onyx and ensure they do not regress

@rinej 

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by mountiny** [comment]
@rinej thank you! Can you share a plan on how to set this up and what tests we would add? 

I think ideally you can handle the set up and then we can export all the tests to the community, I assume they should be straightforwards given its quite low level code

**Comment by mountiny** [comment]
@rinej yeah that makes sense. Is that not the case in the App?

**Comment by rinej** [comment]
@mountiny Yes thats right, I added the setup and output validation here -> https://github.com/Expensify/react-native-onyx/pull/525

I couldn't run the workflows even on the PR cause it its to be approved before, please have a look, thanks!

**Comment by mountiny** [comment]
done

**Comment by mountiny** [comment]
PRs have been merged, anything else you would like to add in  scope of this issue @rinej ?

**Comment by rinej** [comment]
@mountiny after merging that fix -> https://github.com/Expensify/react-native-onyx/pull/538 we should be good with the scope of the setup and an example tests. 

Do you think we need a new gh issue for implementing new tests?

**Comment by mountiny** [comment]
I think this is now looking good
