### ISSUE TITLE
IOU-IOU is shown with a new message green line on top for few seconds

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39161]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home

2. Tap fab ---request money
3. Enter an amount
4. Select user with whom you have no conversation
5. Tap request
6. Tap on newly created IOU to open details page
7. Tap 3 dots on top and delete the IOU
8. Navigate back to LHN
9. Tap fab ---request money
10. Enter an amount
11. Select same user with whom money requested previously
12. Tap request

## Expected Result:
In 1:1 page, newly created IOU must not be shown with a new message green line on top for few seconds also.

## Actual Result:
In 1:1 page, newly created IOU is shown with a new message green line on top for few seconds and then it disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/45b63942-c62a-4a59-8a83-c73ea569020d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by dylanexpensify** [comment]
Sorry, was OOO for easter, will test today!

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
Not valuable at the moment
