### ISSUE TITLE
Scan - Header in 1:1 DM turns to skeleton after creating Scan request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39163]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to chat with user that has no chat history.
3. Create a scan request.
4. Immediately after requesting, tap on the IOU preview twice to go to transaction thread.
5. Wait until the receipt is uploaded, which is when the receipt preview reloads.
6. Swipe right (iOS app) to return to 1:1 DM.

## Expected Result:
The header in 1:1 DM will show the user name and avatar.

## Actual Result:
The header in 1:1 DM turns to skeleton loading.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/83d5286b-4f6c-401d-9f86-3549aeb79abc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@muttmuure I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-bills.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/8b3fd802-81a7-4856-98d0-8009c73742fc

**Comment by yuwenmemon** [comment]
Hmmm... not able to reproduce so far in staging

**Comment by yuwenmemon** [comment]
https://github.com/Expensify/App/assets/4741899/b8af43c9-2315-490f-91e3-81050a31ba47




Can't reproduce on staging on iOS. Gonna remove the blocker label.

**Comment by Julesssss** [comment]
Hey @muttmuure, I can't repro this on the staging Android app. Could you please check iOS?

**Comment by Julesssss** [comment]
Bump on [this](https://github.com/Expensify/App/issues/39163#issuecomment-2031358825) @muttmuure
