### ISSUE TITLE
[HOLD for payment 2024-04-25] Android & iOS - Workspace - Workspace is not crossed out when deleted offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39178]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
Precondition:
- User has at least two workspaces.

1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces.
3. Go offline.
4. Delete any workspace.

## Expected Result:
The deleted workspace will appear crossed out.

## Actual Result:
The deleted workspace is only grayed out and not crossed out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/61a7815d-86e4-4dcb-9b7f-722ef6b80ed0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/f7025fa6-fdc9-4990-a8ca-ad73aef6f9ca

**Comment by grgia** [comment]
maybe related to 
https://github.com/Expensify/App/pull/38454
https://github.com/Expensify/App/pull/38249/files

@Krishna2323

**Comment by joekaufmanexpensify** [comment]
PR on staging

**Comment by joekaufmanexpensify** [comment]
This is a regression fix, so IDT we need to do the checklist, nor is any payment due. Closing for now, but LMK if anyone disagrees with that.
