### ISSUE TITLE
LHN- Message in LHN changes only after reopening the chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab --- start chat
3. Select user with no previous conversation
4. Tap plus icon --- request money
5. Enter amount
6. Tap request
7. Open newly created IOU to open IOU report page
8. Invite an user using mention
9. Tap invite in whisper message
10. Navigate to LHN using app back button
11. Note chat report shows IOU details
12. Tap on report
13. Now navigate back to LHN
14. Note expensify message is displayed

## Expected Result:
After inviting user, navigating back to LHN must show expensify message,

## Actual Result:
The message in LHN changes only after reopening it. After inviting user, navigating back to LHN doesn't show expensify message, only after reopening user can see it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7f52f6b0-2c13-442b-9424-4a43b9f6aeea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by stephanieelliott** [comment]
This feels pretty edge case and I don't think we'll prioritize fixing this. Gonna close for now
