### ISSUE TITLE
Android - Infinite skeleton flickering when open report with deleted expense

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39185]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4459012&group_by=cases:section_id&group_order=asc&group_id=296773
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: User is employee 1 of Collect workspace
Steps:
1. Login to OldDot with the employee 1 account
2. Navigate to workspaces and set the collect policy to default if not already set
3. Navigate to reports
4. Create a report
5. Add expense to the report
6. As employee on new dot verify that report is visible
7. Go to Old Dot> Delete the expense from the report
8. As employee on new dot open the same report

## Expected Result:
The report conversation doesn't display the expense that was removed

## Actual Result:
The report conversation page on new dot shows Infinite skeleton flickering when delete the expense from old dot

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1567014e-fa4b-40fc-967a-71b065c37cf6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by JmillsExpensify** [comment]
@trjExpensify You're closer to this than me. Will this be fixed as part of our backward compatibility initiatives?

**Comment by trjExpensify** [comment]
Strange that it's Android specific, is that right? Anyway, I think unreporting and deleting expenses is being worked on here: https://github.com/Expensify/Expensify/issues/364642

CC: @madmax330

**Comment by JmillsExpensify** [comment]
Agreed. I'm going to close for now and let's re-assess when backward compatibility is addressed.
