### ISSUE TITLE
[HOLD for Payment 4/29][$250] Implement Live Markdown for task descriptions

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#39189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1711641837108169

## Action Performed:
1. Press on the global create button
1. Click on `Assign Task`
1. Enter markdown in the task description field

## Expected Result:
The markdown styling should render in real-time, as it does for the main chat composer.

## Actual Result:
No live markdown formatting.

## Workaround:
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fca642f1cb0ae8d</li>
        <li>Upwork Job ID: 1773387024042512384</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Skalakid** [comment]
Hi, I'm Michał from Software Mansion and I would like to work on this issue

**Comment by Skalakid** [comment]
Hi @roryabraham, I created [draft PR](https://github.com/Expensify/App/pull/39519) that extends form text input functionality and enables live markdown inside it. Now we can enable live markdown inside any `InputWrapper` by simply passing `liveMarkdown` prop. Also, my PR added markdown support on the following pages: 
- `New Task Page`
- `New Task Description Page`
- `Task Description Page`

Let me know what you think about it. Also, since with these changes migrating text inputs into live markdown ones is pretty straight forward (adding one prop), should I cover other issues as well?

**Comment by Skalakid** [comment]
@roryabraham bump

**Comment by alitoshmatov** [comment]
https://github.com/Expensify/App/issues/39192 - We have the same feature request for money request description. Wouldn't it be better to apply live markdown in all descriptions on a single PR?

**Comment by CortneyOfstad** [comment]
Sounds good @alitoshmatov — putting it on-hold now!

**Comment by jjcoffee** [comment]
@CortneyOfstad I think @alitoshmatov meant the other way 'round; that https://github.com/Expensify/App/issues/39192 should be held on the issue here :wink:

**Comment by CortneyOfstad** [comment]
Oh goodness — thanks @jjcoffee! Fixing that now!

**Comment by CortneyOfstad** [comment]
@roryabraham I see you moved this to done — any additional action needed here?

**Comment by roryabraham** [comment]
it's actually only gone to staging yesterday, we had a long delay between deploys, see #fireroom-2024-04-17 for details

**Comment by CortneyOfstad** [comment]
Deployed to production 2 days ago, so going to get this sorted for payment

**Comment by CortneyOfstad** [comment]
- @Skalakid does not require payment (SM)
- @jjcoffee to be paid $250 [via Upwork ](https://www.upwork.com/ab/applicants/1773387024042512384/hired)

 I am assuming no regression test for this?

**Comment by CortneyOfstad** [comment]
@jjcoffee Unfortunately the original job post expired so I had to send you a manual offer. Please let me know once you accept and I can get that paid ASAP. Thanks!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@jjcoffee — paid $250 via Upwork
