### ISSUE TITLE
Chat - Emoji tab opens at lower level, Change default skin tone not accessible for an attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39195]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kia1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat - 1:1 DM, #admins room
3. Tap on + icon in composer >> select add attachment >> upload attachment
4. Hover over attachment & select add reaction option from action menu
5. Scroll down the emoji panel

## Expected Result:
Emoji tab should open at the top level, so that "Change default skin tone" option in emoji panel should be accessible in 100% zoom for an attachment when selecting the add reaction option from action menu

## Actual Result:
1. Emoji tab opens at the same level as the attachment message & hence "Change default skin tone" option in emoji panel not accessible in 100% zoom for an attachment when selecting the add reaction option from action menu
Also, some of the flag emojis not accessible as well
2. Issue happens for an attachment saved just above the composer field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/20b7e9fc-0c67-4566-89a2-f6da78ac6690

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/4e430143-3bc3-4585-b078-3744374f85fd

**Comment by francoisl** [comment]
I can repro on staging but not in dev, I think this is already fixed. I see 2 new PRs that modified the emoji popover got merged but are not on staging yet, figuring out which one fixes it and will request a CP.

**Comment by francoisl** [comment]
Ok yeah, pretty sure https://github.com/Expensify/App/pull/39143 fixes this. There's already a CP running for it, I'll test again when it's deployed.

**Comment by francoisl** [comment]
Confirmed fixed on staging now.
