### ISSUE TITLE
[$250] Live markdown for workspace description

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#39193]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1711641837108169

## Action Performed:
1. Create a workspace if you don't already have one
1. Open workspace settings
1. Click on the input for workspace description and start typing markdown in there

![image](https://github.com/Expensify/App/assets/47436092/39c07ef7-cf78-4a8a-9c90-862e74da590b)

## Expected Result:
The markdown styling should render in real-time, as it does for the main chat composer.

## Actual Result:
No live markdown formatting.

## Workaround:
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01feb88466d128ac03</li>
        <li>Upwork Job ID: 1773388688826933248</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by nkdengineer** [comment]
dibs

**Comment by roryabraham** [comment]
@nkdengineer please take the time you need to add a bit of detail to the proposal. The practice of "speedrun" proposals where you post quickly then edit it isn't something I like to see

**Comment by roryabraham** [comment]
Also note that we should wait for live markdown web to land on production before merging a PR here

**Comment by nkdengineer** [comment]
@roryabraham Thanks for the feedback! I'll take note of it 🙏

**Comment by mananjadhav** [comment]
I can see the proposal was already accepted and @nkdengineer was assigned. @roryabraham Do we want to hold the issue by linking the live markdown issue here?

**Comment by nkdengineer** [comment]
@mananjadhav The PR is here https://github.com/Expensify/App/pull/39686.

**Comment by mananjadhav** [comment]
@twisterdotcom This is ready for payout. This is a feature request and hence doesn't have an offending PR.

But I think we should copy the Test steps from the PR as regression steps?

**Comment by blimpich** [comment]
Sorry it seems the automation didn't work. Payment should be out shortly. 👍

cc: @twisterdotcom

**Comment by twisterdotcom** [comment]
Okay, payouts just $250 for @mananjadhav and @nkdengineer right?

**Comment by mananjadhav** [comment]
Yes @twisterdotcom

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by twisterdotcom** [comment]
Payment Summary:

- @mananjadhav paid $250 via NewDot requests (C+)
- @nkdengineer paid $2500 via Upwork [here](https://www.upwork.com/nx/wm/offer/102146999) (Contributor)

**Comment by mananjadhav** [comment]
@twisterdotcom Not fair!! $250 for me and $2500 for @nkdengineer  ? 🤣 🤣

**Comment by blimpich** [comment]
💰🤑💸

**Comment by twisterdotcom** [comment]
😂 wooops. Just had to check the contract too make sure I didn't mess that one up too. Just a typo!

**Comment by nkdengineer** [comment]
@twisterdotcom Offer accepted 🙏
