### ISSUE TITLE
[$250] Live markdown for private notes

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#39194]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1711641837108169

## Action Performed:
1. Open any DM
1. click on the header
1. Click on `Private Notes`
1. Enter markdown text in the text input

## Expected Result:
The markdown styling should render in real-time, as it does for the main chat composer.

## Actual Result:
No live markdown formatting.

## Workaround:
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea926bc5d1af45b0</li>
        <li>Upwork Job ID: 1773389834867847168</li>
        <li>Last Price Increase: 2024-03-28</li>
    </ul>
</details>

**Comment by allroundexperts** [comment]
I can review this since @situchan is OoO for a month.

**Comment by puneetlath** [comment]
Sounds good.

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone. I think we can move forward with @nexarvo's [proposal](https://github.com/Expensify/App/issues/39194#issuecomment-2025665612). Since this was a super simple issue, I don't feel like adding the link to the component adds a lot of value to the proposal.

🎀 👀 🎀 C+ reviewed

**Comment by puneetlath** [comment]
How's it going @nexarvo?

**Comment by puneetlath** [comment]
Sounds good. I updated this to be on hold for that.

**Comment by roryabraham** [comment]
taking this off HOLD

**Comment by puneetlath** [comment]
Looks like you're right and this is ready to pay. Looks like the Upwork job has expired. Can you send me a link to your upwork profile so I can send you an offer?

**Comment by puneetlath** [comment]
Offer here: https://www.upwork.com/nx/wm/offer/102135211

@nexarvo please ping me on this issue when you've accepted.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
