### ISSUE TITLE
[Retest] on IOU - The TAG from a new IOU created is not displayed in the Recent list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4455292
**Issue reported by:** Applause - Internal Team

## Action Performed:
Steps:
1. Open https://staging.new.expensify.com/
2. Log in to the employee account
3. Navigate to the WS room
4. Navigate to Request money -> Manual
5. Enter any amount, go next
6. Select any Tag that is not in the Recent list
7. Complete the IOU
8. Navigate to Request money -> Manual -> Tag

## Expected Result:
Tag from created IOUs should be displayed in the Recent list

## Actual Result:
The Tag from a new IOU created is not displayed in the Recent list until you refresh the app.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f6aa2726-0176-4794-a364-74d9e1acc16b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by FitseTLT** [comment]
This will be fixed in https://github.com/Expensify/App/pull/38881

**Comment by stephanieelliott** [comment]
Oops sorry @strepanier03 I thought this one was mine -- seems likely that this will be fixed via the PR linked above, but feel definitely adjust if you disagree!

**Comment by strepanier03** [comment]
No worries @stephanieelliott - I checked and agree so I'll wait for it to close and then retest.

**Comment by strepanier03** [comment]
It's on staging atm.

**Comment by strepanier03** [comment]
Been OoO but seeing this was deployed to Prod 4 days ago we can retest.

**Comment by kavimuru** [comment]
Bug is fixed now.

https://github.com/Expensify/App/assets/43996225/d1484f4a-784c-4218-be0a-2cc2f1436f5b

**Comment by strepanier03** [comment]
Great, closing this out now!
