### ISSUE TITLE
HelpDot Improvements - Round 3!

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#39202]
### Overview
- We'll continue to assign all helpdot-related PRs to @rushatgabhane for review
- @rushatgabhane works with the Design Team to make design changes to helpdot

### Payment details
$4k for the entire job (March 1 - June 1)

**Comment by rushatgabhane** [comment]
not overdue

**Comment by maddylewis** [comment]
added `BUG` label to process payment:
- $4k for entire project
- @rushatgabhane is paid via NewDot 👍

**Comment by greg-schroeder** [comment]
Okay so - just post a payment summary and then he does a manual request?

**Comment by JmillsExpensify** [comment]
$4,000 approved for @rushatgabhane

**Comment by rushatgabhane** [comment]
issue can be closed
