### ISSUE TITLE
[QBO] Navigate to the Accounting page when the accounting feature is enabled

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#39214]
When the accounting feature is enabled, navigate to the Accounting screen inside the `enablePolicyConnections` action function.

We're waiting for the PR to the accounting page to be merged.

**Comment by johncschuster** [comment]
@hayata-suenaga do you need anything from me on this at the moment?

**Comment by hayata-suenaga** [comment]
The PRs that were holding this issue were merged. I'll work on this when I have time

**Comment by johncschuster** [comment]
Bumping to keep Melvin at bay 👍

**Comment by trjExpensify** [comment]
Can this not be external like the other pages in the workspace settings? CC: @allroundexperts who worked on a lot of this stuff. :)

**Comment by allroundexperts** [comment]
Yep. This can be external.

**Comment by hayata-suenaga** [comment]
because this change is simple, I just opened a PR [here](https://github.com/Expensify/App/pull/41428)

**Comment by hayata-suenaga** [comment]
This issue will be fixed in the PR linked above ⬆️ 

This PR doesn't need payment as the payment will be handled in a different issue.

I'm closing this issue for now.
