### ISSUE TITLE
[HOLD for payment 2024-05-03] [$250] Chat - Text in the composer is highlighted after adding an emoji to text with mark down

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39237]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go to any chat.
3. Enter a text in bold mark down.
4. Create a new line.
5. Open emoji picker.
6. Select an emoji.

## Expected Result:
The text in the composer will not be highlighted.

## Actual Result:
The entire text in the composer is highlighted after adding an emoji to text with mark down.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cf583c77-2ef4-4575-8192-c5e267e660bd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f7f1b9abead474c</li>
        <li>Upwork Job ID: 1776300079521869824</li>
        <li>Last Price Increase: 2024-04-12</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by thienlnam** [comment]
Not a blocker - added to the tracking issue

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment]
@kbecciv Hey, can you try to reproduce this again? I wasn't able to do that.

https://github.com/Expensify/App/assets/23487612/bf0246b5-3e09-44bf-becf-f45fb7c0ca35

**Comment by kbecciv** [comment]
@MrMuzyk Checking

**Comment by thienlnam** [comment]
@kbecciv Were you able to figure this out?

**Comment by eh2077** [comment]
@kbecciv Friendly bump ^

**Comment by kbecciv** [comment]
@thienlnam @eh2077 Checking, will update you shortly!

**Comment by kbecciv** [comment]
Able to reproduce on Windows/Chrome - build v1.4.62-4

https://github.com/Expensify/App/assets/93399543/0dd4ba21-78f1-4447-af7b-8396134f1ca4

**Comment by MrMuzyk** [comment]
Might be an oversight or mistake on my end as I was convinced this was only happening on desktop app. I've retested it on web and I was able to reproduce this issue. I will get back to it next week.

**Comment by thienlnam** [comment]
cc @tomekzaw Is this an issue you'd want to take internally or have a contributor handle it within the library?

**Comment by tomekzaw** [comment]
I believe @Skalakid has a draft PR that should fix some of the issues related to selection:
* https://github.com/Expensify/react-native-live-markdown/pull/313

So we'd like take that internally for now.

**Comment by Skalakid** [comment]
Hi, to confirm my https://github.com/Expensify/react-native-live-markdown/pull/313 in `react-native-live-markdown` library, fixes this issue. I will create the PR that bumps the version of the library in our App

**Comment by Skalakid** [comment]
Here is the [PR with the fix](https://github.com/Expensify/App/pull/40923)

**Comment by MrMuzyk** [comment]
I've checked on latest main and issue is no longer reproducible. @kbecciv Can you confirm that?

https://github.com/Expensify/App/assets/23487612/df7f12e2-1f34-44af-a0cb-e6b3ea35f449

**Comment by kavimuru** [comment]
@MrMuzyk Issue is fixed now.
![image](https://github.com/Expensify/App/assets/43996225/6aa4427d-0e16-43d0-b3b2-8771b0d46d62)

**Comment by eh2077** [comment]
> Hi, to confirm my [Expensify/react-native-live-markdown#313](https://github.com/Expensify/react-native-live-markdown/pull/313) in `react-native-live-markdown` library, fixes this issue. I will create the PR that bumps the version of the library in our App

Yes, this is fixed by @Skalakid 's PR https://github.com/Expensify/App/pull/40923 which was merged yesterday

**Comment by laurenreidexpensify** [comment]
Payment Summary:

Contributor: @tomekzaw agency worker - no payment
C+: @eh2077 $250 paid in Upwork 

@eh2077 pls confirm if a regression test is required

**Comment by eh2077** [comment]
@laurenreidexpensify This is an edge case, so I don't think it's necessary to add a regression test for it.
