### ISSUE TITLE
 Mark down - App crashes when entering an emoji inside three backticks code block

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Enter three backticks code block.
4. Enter an emoji inside the code block.

## Expected Result:
App does not crash.

## Actual Result:
App crashes.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c20bedf1-ea9b-42d5-ab9c-911a0699b4c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by flodnv** [comment]
@Skalakid @thienlnam I suspect this is caused by https://github.com/Expensify/App/pull/38152, can you take a look?

**Comment by BartoszGrajdek** [comment]
Fix in review 👀
