### ISSUE TITLE
Chat - Three empty lines are pasted when pasting a text with an empty line

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Enter a text.
4. Create an empty line.
5. Copy the text with the empty line.
6. Clear the composer.
7. Paste the content.

## Expected Result:
Only one empty line will be pasted.

## Expected Result:
Three empty lines are pasted when pasting a text with an empty line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f8259887-e5e5-40c8-9407-9129e88ea237

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production


https://github.com/Expensify/App/assets/115492554/fd58d9c7-bebe-40e4-a32f-b3aee256f891

**Comment by BartoszGrajdek** [comment]
We're aware of this bug, there's already an issue https://github.com/Expensify/App/issues/36071 created for it and a PR https://github.com/Expensify/App/pull/39177 in in review 😄

**Comment by BartoszGrajdek** [comment]
This is not a blocker

**Comment by amyevans** [comment]
Awesome, appreciate the proactive tracking @BartoszGrajdek! I'll close this out.
