### ISSUE TITLE
[HOLD #39982] Thread - Gray "Replies" does not disappear together with reply when reply is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39246]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Right click on the message > Reply in thread
5. Note that "Replies" is not present when there is no reply
6. Send a reply
7. Delete the reply

## Expected Result:
When the reply is deleted, the gray "Replies" should disappear together with the deleted reply

## Actual Result:
When the reply is deleted, the gray "Replies" only disappears after a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2b774d83-6bec-4e32-8ba0-8f27c6c426b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
Seems like a regression introduced in https://github.com/Expensify/App/pull/38722

@chiragsalian @dannymcclain @allroundexperts @rayane-djouah - Would you like to block on this?

Seems like maybe we should be clearing the "Replies" optimistically as well, not just when the API replies?

**Comment by dannymcclain** [comment]
I personally don't think this should be a blocker. I think we should fix it, but it doesn't break anything or really cause any harm, so I don't think it needs to be a blocker.

**Comment by mallenexpensify** [comment]
We're on hold here pending 
- https://github.com/Expensify/App/issues/39982#issuecomment-2077674067 

@rayane-djouah just proposed a solution there today.

**Comment by mallenexpensify** [comment]
Thanks @rayane-djouah , also confirmed it's not reproducible.
