### ISSUE TITLE
[HOLD for payment 2024-04-15] [HOLD for payment 2024-04-09] Thread - Group chat thread header shows unavailable workspace icon

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Create a group chat.
4. Send a message in group chat.
5. Right click on message > Reply in thread.

## Expected Result:
Group chat thread header will not show unavailable workspace icon.

## Actual Result:
Group chat thread header shows unavailable workspace icon.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b7c7783b-534e-4a73-ba15-c50ee3d43548

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by NikkiWines** [comment]
Hmm, I'm not able to reproduce this on staging but I also see a different group icon to begin with 🤔 

https://github.com/Expensify/App/assets/16747822/9c87a98e-3a4f-4748-9e6c-572ab53b1dec

**Comment by dylanexpensify** [comment]
@NikkiWines I don't think this is a deploy blocker, but what do you think? Attempting reproduction now

**Comment by dylanexpensify** [comment]
Could reproduce 👍

**Comment by NikkiWines** [comment]
I still can't reproduce it 😢 @dylanexpensify @ZhenjaHorbach are either of you able to reproduce the bug on prod? If not, let's identify what PR introduced the changes and whether or not it's a regression or just a mishandled edge case.

**Comment by marcaaron** [comment]
Thanks @NikkiWines. Gonna jump in here.

**Comment by kavimuru** [comment]
This issue is fixed 

https://github.com/Expensify/App/assets/43996225/3b56fb41-f294-4ff4-863e-7980058c7497

**Comment by dylanexpensify** [comment]
Hmm, @marcaaron is there anyone we need to pay here?

**Comment by s77rt** [comment]
No payment is due here. This can be closed
