### ISSUE TITLE
[$250] Thread - New message does not appear in main chat after returning from thread and sending text

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39242]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Right click on the message > Reply in thread
5. Send a reply
6. Click on the link in header subtitle to return to main chat
7. Send a message in the main chat

## Expected Result:
The new message in Step 7 will appear in the chat view

## Actual Result:
The new message in Step 7 does not appear in the chat view, but it shows in LHN. It only appears in the main chat after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5c082f7c-edfd-43cd-b86c-f4e82f1095ea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc9654e48d69e950</li>
        <li>Upwork Job ID: 1773825288715214848</li>
        <li>Last Price Increase: 2024-03-29</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@mountiny  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
This seems odd and External to me. Curious if anyone can spot what introduced this

**Comment by mountiny** [comment]
Made a revert of https://github.com/Expensify/App/pull/38722 and confirmed the issue is resolved.
