### ISSUE TITLE
[HOLD for payment 2024-04-15] [HOLD for payment 2024-04-09] Task - Not here page shows up when opening room link under header subtitle in deleted task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39251]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a room.
3. Create a task.
4. Leave the room.
5. Go to task report.
6. Click room link under header subtitle.
7. Note that the room opens without issue.
8. Delete the task.
9. Click room link under header subtitle.

## Expected Result:
The room will open without issue.

## Actual Result:
Not here page shows up when opening room link under header subtitle in deleted task report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d14dcc79-eaeb-422f-89d9-778fb0fb2cf6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by sakluger** [comment]
I started a discussion in the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1711727227326029).

**Comment by deetergp** [comment]
We appear to be appending the reportActionID of the deleted task to the URL for the room name link in the header.
<img width="1716" alt="Screenshot 2024-03-29 at 10 49 03 AM" src="https://github.com/Expensify/App/assets/766197/5b2692a1-6205-404b-9e6b-f972afebc117">
<img width="1675" alt="Screenshot 2024-03-29 at 10 50 10 AM" src="https://github.com/Expensify/App/assets/766197/635f11b9-a7ef-473f-9fd3-f0e3399e1c7c">

**Comment by sakluger** [comment]
Part of the issue with the regression was reverted the rest is being fixed. I'll test this behavior again in a day or two.

**Comment by marcaaron** [comment]
Since the PR was reverted I think we can remove the blocker though yes?

**Comment by sakluger** [comment]
No payment needed since it was just a revert.
