### ISSUE TITLE
[$500] Workspaces - Tapping on any workspace does not lead to ws settings

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4465764
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Prerequisites: Existing account with at least one workspace
1. Log in to New Expensify with account from prerequisites
2. Navigate to Workspaces
3. Tap on any workspace

## Expected Result:
User should be redirected to workspace settings.

## Actual Result:
Nothing happens when tapping on any workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ae3a8791-0a14-4407-b143-75362c316b86

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad5871d614b5d635</li>
        <li>Upwork Job ID: 1773770639233683456</li>
        <li>Last Price Increase: 2024-03-29</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@greg-schroeder I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production


https://github.com/Expensify/App/assets/115492554/2128c49c-9e83-41b2-be50-68be01d8f3d6

**Comment by neil-marcellini** [comment]
I'm able to re-produce the problem on staging iOS. If the fix is on main, then we need to find whatever PR fixed it and CP it to staging.

**Comment by neil-marcellini** [comment]
Adding external since I would certainly appreciate any help spotting the fix

**Comment by neil-marcellini** [comment]
[Fix opening workspace settings on small screen](https://github.com/Expensify/App/pull/39150#top)

**Comment by neil-marcellini** [comment]
I have requested it to be CPed to staging [here](https://expensify.slack.com/archives/C07J32337/p1711735428044169)

**Comment by mountiny** [comment]
I cannot repro so this is fixed
