### ISSUE TITLE
[PAID] [HOLD for payment 2024-06-18] [$500] Unable to undo copy and pasted text

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39255]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Request money from any user.
3. In 1:1 DM, right click on the IOU preview > Copy to clipboard.
4. Paste the content in the composer.
5. Undo the paste via CTRL and Z.

## Expected Result:
The content in the composer will be removed.

## Actual Result:
The content in the composer is not removed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/be5434a3-18f1-4f90-b8ba-3f9792a8bb76

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad87b8428e3aa6d9</li>
        <li>Upwork Job ID: 1775086854091751424</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment]
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production

https://github.com/Expensify/App/assets/115492554/e4ea7d14-c5d8-4533-b88b-3b750ced268a

**Comment by srikarparsi** [comment]
I believe this issue is with undoing copy and pasting itself. I don't think it's related to IOUs. Could be something to do with markdown, taking a look

**Comment by srikarparsi** [comment]
On each of these, I'm alternating between command+v and command+z but some of the command+z's aren't registering on staging.

Production:
https://github.com/Expensify/App/assets/48188732/d1794d35-24ca-4e41-81bf-311f713876b1

Staging:
https://github.com/Expensify/App/assets/48188732/ae52e882-566d-40c3-b905-b49a240a8a3b

**Comment by thienlnam** [comment]
Not a blocker - added to the tracking issue

**Comment by BartoszGrajdek** [comment]
I'm already working on it @thienlnam you can assign me here 👍🏻

**Comment by jdumont0201** [comment]
The issue also happens in dev environments after the first paste/undo. 
In dev, you can copy, paste then undo, but if you paste again you cannot undo anymore.

Setup: MacOS Ventura + Chrome Version 123.0.6312.87 Node 20.10.0

**Comment by srikarparsi** [comment]
Removing the external label as @BartoszGrajdek is working on it.

**Comment by bfitzexpensify** [comment]
How's this one going @BartoszGrajdek?

**Comment by BartoszGrajdek** [comment]
Working on it - we already have a PR with fix in review added to the `react-native-live-markdown` repo

**Comment by BartoszGrajdek** [comment]
FYI we should be able to test this throughout once we get a PR with `react-native-live-markdown` batch version upgrade going, which includes fixes related to this issue - I'll update you on that

**Comment by BartoszGrajdek** [comment]
@thienlnam this shouldn't be an issue anymore - can we get someone to test it? 👀

**Comment by bfitzexpensify** [comment]
Getting this re-tested by QA - https://expensify.slack.com/archives/C9YU7BX5M/p1713791035520399

**Comment by kavimuru** [comment]
Issue is still reproducible.

https://github.com/Expensify/App/assets/43996225/0278bec2-def8-4486-ad1a-bf504a8a14c1

**Comment by BartoszGrajdek** [comment]
That's weird because I don't have this problem anymore 🤔 

https://github.com/Expensify/App/assets/41169160/97f1c616-4cb1-4f8c-b96d-a71acba35055

**Comment by BartoszGrajdek** [comment]
@Skalakid is working on some additional refactors for InputHistory, so we'll test it once again in his PR 🙌🏻

**Comment by quinthar** [comment]
hi!  What's the latest ETA on this?

**Comment by Skalakid** [comment]
@quinthar Sorry I prioritized fixing other critical live markdown bugs, working on it right now. The PR will be ready by tomorrow

**Comment by Skalakid** [comment]
I created the [PR](https://github.com/Expensify/react-native-live-markdown/pull/342) in the `react-native-live-markdown` library with the fix and waiting for the review. After merging this I will create another PR that bumps the version of the library in E/App

**Comment by bfitzexpensify** [comment]
Adding a BZ buddy - I will be OOO until June 11th

**Comment by strepanier03** [comment]
Thanks for getting the checklist done, handling the rest now.

**Comment by strepanier03** [comment]
All right, payment completed and contract closed. Thanks everyone!
