### ISSUE TITLE
Taxes - App does not allow user to enter any digit after dot when there are 6 zeros before it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace
3. Go to Taxes
4. Click Add rate > Value
5. Enter 6 zeros
6. Add a dot
7. Add any number

## Expected Result:
App will allow user to enter any digit since there are only 6 digits in the input

## Actual Result:
App does not allow user to enter any digit after the dot when there are 6 zeros before it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1d7b32b0-d9fc-4fb2-83e0-66eeb0a7de5c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by rlinoz** [comment]
Since every other input works fine, I don't we should hold this as a blocker, so removing demoting it.

**Comment by rlinoz** [comment]
Also, I think the bug is that we allow more than four 0s since we limit the field for every other input to 4 characters.

**Comment by rlinoz** [comment]
I don't think this is worth fixing, the field only has a problem if we add more than 4 leading zeroes before the decimal symbol, so I am closing it.
