### ISSUE TITLE
Android- Chat - Text inside compose box is not centered when using header MD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a chat
2. Start typing # followed by any letter

## Expected Result:
Text inside the compose box should be centered as is in other platforms

## Actual Result:
Text inside the compose box does not get centered which is different from behavior in other platforms

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cf05b9a9-95ae-4048-81e3-b1ed93b4f489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by joekaufmanexpensify** [comment]
I don't think this is really a bug. This is related to our new native markdown formatting. Closing.
