### ISSUE TITLE
Web - Chat - Console error shows up when creating a new line on italic mark down

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39265]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1.Go to staging.new.expensify.com/
2.Go to any chat
3.Enter _ text _ (without space)
4.Move the cursor to before the second _
5.Create a new line
## Expected Result:
No console error

## Actual Result:
The cursor moves to the beginning of the text. The new line is only revealed when pressing down key on keyboard. Console error also shows up
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3f713460-6c6a-4f7a-ac4d-03fb9c1dde97

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by m-natarajan** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by thienlnam** [comment]
Not a deploy blocker - added to the main tracking issue

**Comment by anmurali** [comment]
This is the exception. @thienlnam is this something a contributor can fix or do we need to take it internal? I am not totally sure. 
```
cursorUtils.js:54 Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at c (cursorUtils.js:54:19)
    at p (parserUtils.js:156:5)
    at m (parserUtils.js:183:9)
    at MarkdownTextInput.web.js:147:24
    at MarkdownTextInput.web.js:236:16
    at Object.De (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Fr (react-dom.production.min.js:105:68)
    at qr (react-dom.production.min.js:106:380)
    ```

**Comment by thienlnam** [comment]
This can be fixed externally, but might require changes in react-native-live-markdown repository. @BartoszGrajdek Is this something you're interested in taking, or do you want us to take it external here?

**Comment by thienlnam** [comment]
Bump on this https://github.com/Expensify/App/issues/39265#issuecomment-2045648514 @BartoszGrajdek

**Comment by anmurali** [comment]
Brought this to slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1714503046838459)

**Comment by thienlnam** [comment]
This appears to be resolved, I can't reproduce it anymore

https://github.com/Expensify/App/assets/30609178/4c3063a1-ffac-4c06-aadb-4fafc49e0dfb
