### ISSUE TITLE
[HOLD for payment 2024-04-09] Thread - App shows skeleton loading when clicking on parent/ancestor message offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39264]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38722
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Go offline.
4. Send a message.
5. Create several threads in the parent message.
6. Click on any parent or ancestor message.

## Expected Result:
App will redirect to the relevant thread without skeleton loading.

## Actual Result:
App shows infinite skeleton loading when clicking on parent/ancestor message offline.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0646d05b-3b92-4197-a6fc-11690872d6c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by arosiclair** [comment]
I reproduced. It seems like navigation back to the parent does not work while offline. @rayane-djouah @allroundexperts @chiragsalian can any of you guys take a look?

**Comment by arosiclair** [comment]
Seems like it's due to `reportMetadata.isLoadingInitialReportActions` being stuck to `true`

**Comment by marcaaron** [comment]
Gonna remove the blocker because the revert PR above appears to have fixed this and was CP'd.

**Comment by arosiclair** [comment]
Handled in another issue.
