### ISSUE TITLE
[HOLD 10414]mWeb - Chat - Device keyboard does not auto appear when editing a message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4464317
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send a message
4. Tap and hold the message
5. Tap on edit comment

## Expected Result:
Message should enter edit mode and device keyboard should be displayed

## Actual Result:
Message enters edit mode but keyboard does not appear

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/84846ff9-6cf1-46cb-8bcd-0ee70e8ec0ee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by tylerkaraszewski** [comment]
I cannot reproduce this on safari on ios. I don't have an android device to try it. I'll reach out for assistance.

**Comment by thienlnam** [comment]
This _may_ be related to live markdown web

**Comment by tylerkaraszewski** [comment]
@francoisl reproduced this on a real android device.

**Comment by BartoszGrajdek** [comment]
I'll add a PR in a moment 👀

**Comment by thienlnam** [comment]
Fix is currently being reviewed by @jayeshmangwani

**Comment by thienlnam** [comment]
Turns out this also happens on production so it's not a blocker - but something we should still fix

**Comment by thienlnam** [comment]
Held on https://github.com/Expensify/App/issues/10414

**Comment by jayeshmangwani** [comment]
Held on https://github.com/Expensify/App/issues/10414

**Comment by jayeshmangwani** [comment]
Held on https://github.com/Expensify/App/issues/10414

**Comment by thienlnam** [comment]
Still held

**Comment by tylerkaraszewski** [comment]
Do we still care about this?

**Comment by thienlnam** [comment]
Looks like we closed the issue this was holding on, so probably not
