### ISSUE TITLE
 Mark down - Different colour of strikethrough on email depending on bold mark down position

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** around https://github.com/Expensify/App/pull/38152
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Type the following text with mark down (with no space):

* ~ hello.com ~ *
~ * hello.com * ~

## Expected Result:
The color of strikethrough in the preview should be consistent

## Actual Result:
The color of strikethrough in the preview is different depending on the position of bold mark down.
When the mark down is in this order * ~ hello.com ~ *, the strikethrough is blue
When the mark down is in this order ~ * hello.com * ~, the strikethrough is white

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1c885fe6-3eda-4442-88fb-d0618a6b0edc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@flodnv  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by thienlnam** [comment]
Not a deploy blocker - added to the main tracking issue

**Comment by thienlnam** [comment]
This is pretty low on the priority list of other live markdown issues, so going to put this on a monthly

**Comment by thienlnam** [comment]
Closing, looking at this again I'm not sure there is really a problem here
