### ISSUE TITLE
[HOLD for payment 2024-05-08] Web - Chat - Composer jumps when entering first emoji

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39267]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:

1.Go to staging.new.expensify.com/
2.Go to any chat
3.Enter an emoji

## Expected Result:
The composer will not jump

## Actual Result:
The composer jumps when entering the first emoji

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/cf2af7a6-d2f3-4502-8343-343c9cca37c6

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by m-natarajan** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by francoisl** [comment]
I can repro, this comes from the Live Markdown preview https://github.com/Expensify/App/pull/38152. Not sure if it's worth being a blocker though. Looks like there are other open blockers due to the markdown preview anyway, let's see if we end up reverting it.


cc @thienlnam for visibility.

**Comment by thienlnam** [comment]
Not a blocker, I've added it to the main tracking list with a high priority

**Comment by BartoszGrajdek** [comment]
Hi! I'm Bartosz from SWM / `react-native-live-markdown` team - I'll be taking a look into what's happening here later today! 👀

**Comment by slafortune** [comment]
@BartoszGrajdek I've assigned you 👍

**Comment by slafortune** [comment]
@BartoszGrajdek do you have an update on this?

**Comment by thienlnam** [comment]
Here's the latest update - @Skalakid is looking into this

**Comment by chrispader** [comment]
Just noticed the jumping also happens when you add new lines and there is Live markdown in the composer already.

https://github.com/Expensify/App/assets/20173411/53068757-f506-4206-a03d-5a74cfe0a1a6

**Comment by Skalakid** [comment]
@chrispader For now I have a fix in my mind and I'm creating the PR, but thank you :D I will ping you in case of any questions

**Comment by Skalakid** [comment]
Yes, the idea is to simplify the Composer component on the web and make it work the same as its' native version. By setting maxHeight there won't be a problem with jumping composer since UI calculates itself automatically

**Comment by Skalakid** [comment]
I opened [PR](https://github.com/Expensify/App/pull/40128#event-12472656932) with the fix for review :D

**Comment by slafortune** [comment]
@thienlnam @Skalakid @BartoszGrajdek I'll be out until 4/22, not assigning another BZ since this is in a good place with you all to keep it moving forward 👍

**Comment by slafortune** [comment]
@BartoszGrajdek Can you complete the checklist above?

**Comment by slafortune** [comment]
@BartoszGrajdek does not require payment (Contractor)

**Comment by BartoszGrajdek** [comment]
> @BartoszGrajdek Can you complete the checklist above?

I believe @Skalakid was the one who actually fixed this

**Comment by slafortune** [comment]
Shoot!  I am sorry about that @fedirjh ! Offer sent here - https://www.upwork.com/nx/wm/offer/102318459

**Comment by slafortune** [comment]
Paid
