### ISSUE TITLE
Mark down - Position of text with header and line changes after collapsing the composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39271]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38152
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Type # header.
4. Hit Enter to create a new line.
5. Note the position of text in the composer.
6. Expand the composer.
7. Collapse the composer.

## Expected Result:
The position of text in the composer after expanding and collapsing the composer should be the same as the position before expanding the composer.

## Actual Result:
After expanding and collapsing the composer, the text in the composer becomes top-aligned.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f792c8fb-90a0-4e3e-9596-1725b2f6581a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by hayata-suenaga** [comment]
I don't believe this is a bug 😄  The added header is the first line of the text. It should remain so even when the composer is expanded.
