### ISSUE TITLE
[$500] Chat - The cursor appears before the last letter in the compose box when pasting

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39272]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Send a multiline message in any chat
2. Hover over the message
3. Click on the "..." button
4. Click on "Copy to clipboard"
5. Paste it inside the compose box
## Expected Result:
The cursor should appear after the last letter

## Actual Result:
The cursor appears before the last letter in the compose box when copy/pasting multiline text

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c6b3811e-6c42-4a1b-b856-a08a61dd1d98

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01500831e0ec092b01</li>
        <li>Upwork Job ID: 1774859672126918656</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by m-natarajan** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by thienlnam** [comment]
Not a blocker - added to the main tracking issue

**Comment by BartoszGrajdek** [comment]
This issue is already being handled in a PR by @Skalakid https://github.com/Expensify/App/pull/39177#issuecomment-2028785298 @thienlnam please assign him to this task

**Comment by MitchExpensify** [comment]
I think @skalakid needs to comment here for us to assign them

**Comment by Skalakid** [comment]
Hi, I'm Michał from SWM, an expert agency. Please assign me to this task

**Comment by BartoszGrajdek** [comment]
We should be able to close this one @thienlnam
