### ISSUE TITLE
iOS - Chat - Emojis are cut off at the top in compose box

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39270]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1.Navigate to any chat
2.Enter emojis in compose box

## Expected Result:
Emojis should be fully visible to the user

## Actual Result:
The top of the emojis is cut off in compose box

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/2eb75ac1-8775-4b15-94d9-007370543198

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by thienlnam** [comment]
Not a blocker - added to main tracking issue

**Comment by alexpensify** [comment]
On my testing list and I'll test tomorrow.

**Comment by BartoszGrajdek** [comment]
Hi! I'm Bartosz from SWM / `react-native-live-markdown` team - I'll be taking a look into what's happening here later today! 👀

**Comment by alexpensify** [comment]
I confirmed the emojis are cut off. I'm going to double-check there isn't a duplicate. 

![2024-04-03_14-25-26](https://github.com/Expensify/App/assets/8107070/54003bdf-4b5d-4a1f-b4ef-6d884e4c9434)

**Comment by alexpensify** [comment]
Closing - there are two issues that are being worked on and should fix this issue: 

https://github.com/Expensify/App/issues/14676
https://github.com/Expensify/App/issues/15734
