### ISSUE TITLE
[HOLD for Payment] HIGH: [Live Markdown] [$500] Fix inline image syntax in live markdown

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#39275]
Problem:
=====
We recently added the ability for "live markdown preview" meaning that we would preview the HTML formatting that the markdown generates.  However, simultaneously we added a new markdown format: inline images (https://github.com/Expensify/App/issues/37246).  Right now there is a conflict where if you write the inline image format, it throws an exception:

![Image](https://github.com/Expensify/App/assets/575186/74523587-f3c2-40ee-8cbd-6d6275c6db1f)

Solution:
====
Fix the live markdown previewer to show the inline image.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e2d18591b5166e5</li>
        <li>Upwork Job ID: 1773774252438794240</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

**Comment by tomekzaw** [comment]
I would like to work on it

**Comment by tomekzaw** [comment]
Adding support for parsing inline images in Live Markdown: https://github.com/Expensify/react-native-live-markdown/pull/256

**Comment by sakluger** [comment]
Hey @tomekzaw - what is the status here? Still blocked?

**Comment by quinthar** [comment]
Yep, curious for an ETA.

**Comment by tomekzaw** [comment]
We're still discussing the changes on the ExpensiMark side here: https://github.com/Expensify/expensify-common/pull/661#discussion_r1548464870

We should be able to add support for inline image syntax highlighting by EOW.

As for rendering an actual image underneath the text, we'll need some more time (we will track its progress in a separate issue) cc @thienlnam

**Comment by thienlnam** [comment]
> As for rendering an actual image underneath the text, we'll need some more time (we will track its progress in a separate issue) cc @thienlnam

Yeah this would be a new feature - I'll create a new issue so we can track that

**Comment by tomekzaw** [comment]
I've asked @robertKozik to take over this task as it requires some small changes in ExpensiMark (already discussed that with @kidroca).

ETA: early next week

**Comment by thienlnam** [comment]
We ended up bumping the version in a different PR, but @shubham1206agra went through a complete review so we should pay them for that

**Comment by tomekzaw** [comment]
@shubham1206agra I confirm that inline image syntax is already working as expected on current main so there's nothing left to do for this issue.

Thanks @kidroca for your changes in expensify-common and @robertKozik for your changes in Live Markdown!

FYI Inline image preview is tracked separately as a new feature in https://github.com/Expensify/App/issues/40181.

**Comment by quinthar** [comment]
Great, can we close this?

**Comment by sakluger** [comment]
Handling payment now.

**Comment by sakluger** [comment]
I'm having a hard time following the GH issue. @shubham1206agra  where is the PR that you reviewed? And was there a deploy blocker caused by this issue's PR?

**Comment by sakluger** [comment]
Okay, sounds like only @shubham1206agra is due payment. I've summarized it below. @shubham1206agra please let me know once you've accepted the offer.

Summarizing payment on this issue:

Contributor+: @shubham1206agra $500, sent offer via Upwork (https://www.upwork.com/nx/wm/offer/102102445)

**Comment by sakluger** [comment]
Paid, thanks!
