### ISSUE TITLE
Web - Mark down - Send button is disabled and console error when pasting text with MD image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Copy text with markdown image from this PR https://github.com/Expensify/App/pull/37566
4. Paste the content in the composer.

## Expected Result:
There will be no issue with pasting the text with markdown image

## Actual Result:
When pasting text with markdown image, the composer does not automatically expand and the send button is disabled. Console error also shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/71566d3c-46bf-4615-ad19-52b6a8bf2a43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Ah this is known - https://github.com/Expensify/App/issues/39275 closing since this is a dupe
