### ISSUE TITLE
[New Expensify] Rename categories / simplify descriptions

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#39283]
## Category name changes
- `Bank Accounts` to `Bank Accounts & Payments`
- `Payments` to `Expenses`
- `Chat` - stays the same
- `Expensify Card` - stays the same
- `Billing & Plan Types` to `Workspaces`
- `Account Settings` to `Settings`

## Additional category changes
- Update icon from `Billing & Plan Types` to `Workspaces` icon 
- Create a brand new category `Getting Started` (may have to hold on this until there's a resource ready to publish under this newly created category)

### Getting Started
Set up your account to optimize Expensify's features.
### Bank Accounts & Payments (formerly Bank Accounts)
Send direct reimbursements, pay invoices, and receive payment.
### Chat
Use Expensify's chat feature to split bills, chat with employees, and manage payments. 
### Expensify Card
Explore the perks and benefits of the Expensify Card.
### Expenses
Learn more about expense tracking and submission.
### Workspaces
Configure rules, settings, and limits for your company’s spending.
### Settings
Manage profile settings and notifications.

## Reconfigure homepage
Reconfigure categories so they're in the following order:
- Getting Started
- Chat
- Workspaces
- Expenses
- Bank Accounts & Payments
- Expensify Card
- Settings

**Comment by maddylewis** [comment]
Once the category names are updated, i will create a redirect link PR

### Original links to update
WIP

**Comment by rushatgabhane** [comment]
Getting started hub doesn't exist for new expensify. Not sure when it was deleted but it looks intentional

**Comment by rushatgabhane** [comment]
I'll create the Getting started hub but it won't have any articles in it

**Comment by maddylewis** [comment]
> I'll create the Getting started hub but it won't have any articles in it

@rushatgabhane -- want to do a `Coming Soon!` file for that category?

**Comment by maddylewis** [comment]
@rushatgabhane - anything left on this one? are we good to close?

**Comment by rushatgabhane** [comment]
we're good to close!

**Comment by maddylewis** [comment]
heya @adelekennedy 👋 

all that's required on this issue is sending @paultsimura payment for reviewing this PR https://github.com/Expensify/App/pull/39574#issuecomment-2036469896

lmk if you have any Qs!

**Comment by adelekennedy** [comment]
@paultsimura sent you an offer on Upwork! https://www.upwork.com/nx/wm/offer/101831239
