### ISSUE TITLE
IOS - Chat - Chat does not scroll down to bottom when error appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39287]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4466121
**Email or phone of affected tester (no customers):** vdargentotest+ios032924@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Send a corrupted PDF file (there is one attached to this report)
3. Wait for the uploading message to be grayed out
4. Scroll down
5. Verify that an error is displayed

## Expected Result:
The chat should auto-scroll to the bottom when the error message appears

## Actual Result:
The error appears but the chat does not auto-scroll to the bottom

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cfea9d6a-b9d1-4702-8ccd-4824cea13747

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by stephanieelliott** [comment]
I don't think we need to optimize for corrupted PDF files since since that should be pretty uncommon. Gonna close for now.
