### ISSUE TITLE
CRITICAL: [Track expense] [$250] Remove beta flag for everyone

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#39309]
Problem:
===
This feature is ready for everyone, let's ship it!

Solution:
===
Let's:
1. [x] Enable everyone for the beta
2. [x] Rip out all the beta code everywhere
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ddf8901aeb1c9cc</li>
        <li>Upwork Job ID: 1787975091637518336</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by quinthar** [comment]
taking off hold!

**Comment by thienlnam** [comment]
Looking for someone to remove all the TrackExpense beta related code in the FE

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/39309#issuecomment-2099687653) from @tienifr  looks good to me. They have explained the possible scenarios with the solution.

🎀 👀 🎀 C+ reviewed

**Comment by quinthar** [comment]
@tienifr what's your ETA on this?

**Comment by thienlnam** [comment]
Just merged the App PR, now pending deploy

**Comment by thienlnam** [comment]
This is done

**Comment by thienlnam** [comment]
Ah, re-opening so we can handle payment here

**Comment by thienlnam** [comment]
This is ready to be paid out cc @mallenexpensify - there were no regressions, the linked issue is from a different cause

**Comment by mallenexpensify** [comment]
@tienifr can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~014aedec8d9684b35c

For price, I [commented on that last week](https://expensify.slack.com/archives/C01GTK53T8Q/p1717451725980889?thread_ts=1712256409.152489&cid=C01GTK53T8Q)
> There have been questions about what constitutes a job being auto-increased to $500. These jobs are only the ones that have the High Priority label added to them (ie. issue with HIGH or CRITICAL in the title or project status/priority are not auto-increased to $500).

**Comment by mallenexpensify** [comment]
Contributor: @tienifr paid $250 via Upwork
Contributor+: @sobitneupane due $250 via NewDot

Def don't think we need a regression test here

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
