### ISSUE TITLE
Web - Request Money - Category Not Automatically Added When Requesting Money in Distance Mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39304]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.58.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1, Open the FAB menu and select "Request Money."
2, Choose the distance mode option.
3, Enter start and end points, then click "Next."
4, Select workspace chat.
5, Observe that the Category field remains empty and is not automatically filled.

## Expected Result:
The Category, labeled as "Car," should be automatically added when requesting money in distance mode.

## Actual Result:
The Category field is not automatically populated when requesting money in distance mode.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5ebb7110-1a5f-4a70-9d0c-2fa05dfac24e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01495c58bc9b570f5d</li>
        <li>Upwork Job ID: 1773872837983576064</li>
        <li>Last Price Increase: 2024-03-30</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-split

**Comment by francoisl** [comment]
I can reproduce the issue, using the same workspace on staging and prod, and the category is being prefilled correctly in production.

**Comment by francoisl** [comment]
This will be a backend fix, going to remove the label for now.

**Comment by francoisl** [comment]
It will be handled internally, no need for a C+ here.
