### ISSUE TITLE
[$500] Invites to employees on NewDot leading to "Hm, it's not there" when first signing up/in. 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#39308]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** It's only on staging right now. 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @danielrvidal has confirmed with multiple tests/users
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://staging.new.expensify.com/r/8948347462112886
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1711735098951439

## Action Performed:
1. Created a collect workspace using Danrvidal+killfreeplantest6@gmail.com on NewDot
2. Invited danrvidal+killfreeplantest7@gmail.com
3. Got the email on danrvidal+killfreeplantest7@gmail.com, signed into incognito, used the code to sign in
4. It correctly takes me to the workspace chat, but shows me this
![image](https://github.com/Expensify/App/assets/2364487/8e8c56a2-2078-46ef-b714-db3ac2d32f5d)
5. If I refresh the page, the correct text is there:
![image](https://github.com/Expensify/App/assets/2364487/dac522c8-460e-4142-85fd-9fd2b5e17798)

## Expected Result:
The correct page should have been there in the first place. 

## Actual Result:
It shows "hm, it's not there."

## Workaround:
Refreshing works, but is not ideal for a first-time user. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
Covered above and it is reproducible. 

Add any screenshot/video evidence
I did this multiple times to confirm on both Safari and Chrome. 

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f697029a12be02e</li>
        <li>Upwork Job ID: 1774799885032435712</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment]
I would think that this is important for release 1 as a core flow breaking, thoughts @trjExpensify ?

**Comment by danielrvidal** [comment]
I'm not TRJ but I would say this is very important as we're already creating the workspaces for people so it leads to a confusing first time experience.

**Comment by trjExpensify** [comment]
Yeah, I agree. Let's put this in the onboarding project to keep track of progress on it, maybs?

**Comment by trjExpensify** [comment]
>Got the email on [danrvidal+killfreeplantest7@gmail.com](mailto:danrvidal+killfreeplantest7@gmail.com), signed into incognito, used the code to sign in

@danielrvidal can you be more specific on this step. Do you have the email and what URL you clicked within it? Thanks! I think that URL we're generating for the email might be the root cause.

**Comment by danielrvidal** [comment]
This was the email: [danrvidal+killfreeplantest7@gmail.com](mailto:danrvidal+killfreeplantest7@gmail.com) 

Here is the URL I was clicking into:
> Expensify/Expensify Issue URL: https://staging.new.expensify.com/r/8948347462112886

Let me know if you need to test again. But as the new user, here is the flow that takes me to the link above.
1. Get the invite email. 
2. Click new.expensify.com (which is the link above)
3. Get taken to sign in, input my email, generate the code
5. Get the code from email, input into sign in screen
6. Get taken to the link above, which shows hm... it's not here. 

You can see the link below. 

<img width="907" alt="image" src="https://github.com/Expensify/App/assets/2364487/4398bd87-7cbd-4b49-9748-77178fdc23d4">

**Comment by trjExpensify** [comment]
Nice, thanks! Following those steps, I can't reproduce this when trying both of these scenarios: 

- Invited a public & private domain email to an existing collect workspace
- Invited a public & private domain email to a newly created collect workspace by a newly signed up account
- Invited a public & private domain email to a newly created collect workspace by an existing account

Any chance you could retest?

**Comment by danielrvidal** [comment]
Just tried on Chrome and Safari and could not reproduce anymore. So closing it out.
