### ISSUE TITLE
[HOLD for payment 2024-04-15] [HOLD for payment 2024-04-09]  IOU - Split btn for single contact became inactive when returned from final review

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39320]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+omci10@applause.expensifail.com
**Issue reported by:** Applause -Internal Team

## Action Performed:
Precondition: user should be Signed In
1. Open https://staging.new.expensify.com/
2. Click on FAB > Request money
3. Select Manual tab
4. Write any amount and click on Next button
5. Click on a single contact
6. Click on back button
7. Click on the "Split" button for the same contact from step 5

## Expected Result:
Selected contact should stick to the top and marked with a green checkmark when user clicked on a "Split" button for a single contact

## Actual Result:
Nothing happened when user clicked on "Split" button. The split button for the single contact unresponsive on clicks

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/42317d46-8b16-4de5-a741-d10ff7c2b062

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Do you know what PR caused the regression @nexarvo?

**Comment by iwiznia** [comment]
Discussing alternatives [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1711990260779989)

**Comment by mountiny** [comment]
I cannot repro this anymore

**Comment by sakluger** [comment]
I'm a little confused and have a few questions regarding this issue:

1. Was there a regression from this issue, or is this issue fixing a regression?
2. There's no price mentioned in the issue title - Are we paying out the standard $500?
3. Shouldn't this be ready for payment today instead of next week since it was deployed to prod on Apr 2?

**Comment by sakluger** [comment]
Asked those questions in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1712951143397419

**Comment by alitoshmatov** [comment]
This was handled without my involvement, so no payment for me

**Comment by sakluger** [comment]
Thank you @nexarvo! I've sent you an offer via Upwork here: https://www.upwork.com/nx/wm/offer/101873610.

**Comment by sakluger** [comment]
All paid, thanks everyone!
