### ISSUE TITLE
[MEDIUM] [Group Chats] Thread - Invited thread member can click on "Thread" when they are not a member of main chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39331]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat with User B and C
4. Send a message in group chat
5. Right click on the message > Reply in thread
6. Mention User D and invite User D from Concierge whisper
7. As User D, navigate to the thread
8. As User D, click on the blue "Thread" above the parent message

## Expected Result:
Since User D is not in the group chat, the blue "Thread" should be disabled

## Actual Result:
The blue "Thread" is not disabled and it is clickable, which leads to not here page.
When returning to thread after clicking on the Thread button, the header subtitle shows "From" with empty destination

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/01b22045-2974-46e5-9040-74d02c904c11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@pecanoro  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by pecanoro** [comment]
Posted here https://github.com/Expensify/App/pull/39343 since I think we are fixing it there.

**Comment by marcaaron** [comment]
I'm a little confused about this bug report. It seems similar to https://github.com/Expensify/App/issues/39333 in that:

- We created a DM or Group Chat
- We are expecting that this should work
- Did we intentionally design this feature to work at all?
- Or are people able to invite users to these threads in error?

**Comment by marcaaron** [comment]
Posted [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1712005980413999)

**Comment by marcaaron** [comment]
The outcome seems to be that we can remove the blocker for now and plan how this will work.

**Comment by marcaaron** [comment]
I think it's ok to keep fixing this, but heads up I created an issue [here](https://github.com/Expensify/Expensify/issues/384761) for some backend changes to make this work correctly.

**Comment by pecanoro** [comment]
@marcaaron Did you mean to add the `Reviewing` label or only the `Planning` one?

**Comment by marcaaron** [comment]
Oh it was already on, sorry. I accidentally removed it then put it back. And meant to add only the `Planning` label and remove `DeployBlocker` labels.

**Comment by pecanoro** [comment]
I can't reproduce this one anymore so I am going to close
