### ISSUE TITLE
[$500] [Held requests] Expense preview turns to skeleton after approving & paying request offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and employee are in the Collect workspace.

1. [Employee] Request money from the workspace chat.
2. [Employee] Create two money requests.
3. [Employee] Hold one of the requests and leave the other one unheld.
4. [Admin] Go to expense report.
5. [Admin] Go offline.
6. [Admin] Click Approve button.
7. [Admin] Approve the unheld request only and pay with expensify for the unheld request.
8. [Admin] Go online.
9. [Admin] Return to the paid expense report.
## Expected Result:
When returning online, the expense preview will not show skeleton loading.

## Actual Result:
When returning online, the expense previews disappear and turn to skeleton loading.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/4425da13-4cb7-4d6d-8ebc-4e074ad07991

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2d44a97bebec012</li>
        <li>Upwork Job ID: 1774828581241303040</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by cead22** [comment]
This is a pretty involved flow, so I don't think we should block on it. @greg-schroeder let's take this through the normal bug process

**Comment by greg-schroeder** [comment]
Okay, pending proposals and added to #wave-collect

**Comment by mollfpr** [comment]
No proposals

**Comment by greg-schroeder** [comment]
Still pending proposals

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
Waiting for porposals

**Comment by skyweb331** [comment]
@MelvinBot I am investigating the issue. Will submit proposal soon.

**Comment by cead22** [comment]
No overdue. Proposal coming soon

**Comment by skyweb331** [comment]
This is unable to reproduce.

**Comment by greg-schroeder** [comment]
Seems CS is going to take this

**Comment by rezkiy37** [comment]
I've tried to reproduce the bug. I was not able to do it. Looks like it works properly. Can you try on your end?

<details><summary>Video</summary>
<p>


https://github.com/Expensify/App/assets/57314631/2a43268a-8055-4015-b764-ff9e1ebd2f89



</p>
</details>

**Comment by greg-schroeder** [comment]
Hmm, I think it may have been fixed at some point. I'll close for now, but reopen if you disagree or are able to reproduce this.
