### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] Scan - Download is initiated when "Download the file" link is not clicked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39330]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4463698
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a scan request with corrupted file
4. Click on the expense preview
5. Click anywhere along the line of the error message except "Download the file" link

## Expected Result:
Download will not be initiated if "Download the file" link is not clicked

## Actual Result:
Download is initiated when clicking anywhere along the error message except "Download the file" link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/506f384d-7395-4a69-bbec-dbe8265c1e00

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d119d649f3cd351</li>
        <li>Upwork Job ID: 1775263987724267520</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment]
Will be paying this out tomorrow.

**Comment by johncschuster** [comment]
# Payment summary
@hoangzinh PAID [via Upwork](https://www.upwork.com/nx/wm/workroom/36887320/overview) (Reviewer)
@dragnoir requires payment of $500 via Manual Request

**Comment by jamesdeanexpensify** [comment]
@dragnoir did you mean to tag @johncschuster? Sorry, I just want to be sure we're not missing anything.

**Comment by johncschuster** [comment]
Sorry for missing this notification, @dragnoir! I've just issued payment!
