### ISSUE TITLE
[$500] [Members] The page for adding a payment card does not open during transfer owner flow

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39349]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR:** https://github.com/Expensify/App/pull/39035
**Email or phone of affected tester (no customers):** applausetester+a3101@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in to the App
2. Open paid workspace where you are an admin but not an owner
3. Go to the members screen
4. Press on the owner member
5. Press the Transfer owner button

## Expected Result:
The page for adding a payment card opens during transfer owner flow

## Actual Result:
The page for adding a payment card does not open during transfer owner flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2056edc1-1407-430c-8c44-ccb873f1919c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017852f04ab7d12650</li>
        <li>Upwork Job ID: 1775223579538042880</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by trjExpensify** [comment]
CC: @burczu @luacmartins

**Comment by luacmartins** [comment]
Hmm did this user have a credit card on file already?

**Comment by luacmartins** [comment]
Bump @izarutskaya

**Comment by luacmartins** [comment]
I can see that the admin email is on the `[applause.expensifail.com](http://applause.expensifail.com/)` which is not billed, so won't trigger that flow and this is expected. @isagoico is working on the correct test steps [here](https://github.com/Expensify/Expensify/issues/383378#issuecomment-2043407609). Gonna close this one.
