### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] IOU Scan - In dark mode, the damaged PDF - file is barely visible

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39356]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4467055
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition:use dark mode
1. Go to https://staging.new.expensify.com/home
2. Tap on workspace chat
3. Tap plus icon -- request money -- scan
4. Upload corrupt pdf attached below

## Expected Result:
In dark mode, failed to load pdf message must be clearly visible while uploading corrupt pdf

## Actual Result:
In dark mode, failed to load pdf message is barely visible while uploading corrupt pdf

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6ccf5ed4-278a-43e4-ad10-ea2b7a7d4346

![Bug6434200_1711975504736!IMG_20240401_181455](https://github.com/Expensify/App/assets/78819774/a70cb44f-cab2-47fd-8676-13c8e37a7407)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01caa5c1b848d17f6b</li>
        <li>Upwork Job ID: 1778050286258974720</li>
        <li>Last Price Increase: 2024-04-10</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
I think this is a good one to tackle as part of #wave-collect so I'm adding to that project.

**Comment by jayeshmangwani** [comment]
@hayata-suenaga What's your opinion on the [proposal](https://github.com/Expensify/App/issues/39356#issuecomment-2029731489) ?

**Comment by hayata-suenaga** [comment]
Apologizes for the late response. Please add the design team label in the PR to get the design review once the PR is done

**Comment by jayeshmangwani** [comment]
@Krishna2323 What is your ETA for the PR ? and[ please design team label in the PR](https://github.com/Expensify/App/issues/39356#issuecomment-2059404159)

**Comment by shawnborton** [comment]
@hayata-suenaga next time, I think we should get the @Expensify/design team's opinion before awarding a proposal. I'll leave further comments/suggestions in the PR that was opened.

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga next time, I think we should get the @Expensify/design team's opinion before awarding a proposal. I'll leave further comments/suggestions in the PR that was opened.

sure. I'll do so next time. thank you for the advice 😄

**Comment by JmillsExpensify** [comment]
Still working through the PR

**Comment by jayeshmangwani** [comment]
@JmillsExpensify Is it possible to get paid through NewDot for this job instead of Upwork?
since the issue was created before I was getting paid through ND and I received an Upwork offer. If not, no problem—we can go through Upwork.

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: $250 @Krishna2323 
 - Contributor+: $250 @jayeshmangwani

**Comment by JmillsExpensify** [comment]
Updated above since this was created a couple of days before the price change. @jayeshmangwani I canceled your Upwork contract. Please submit a request via NewDot.

**Comment by jayeshmangwani** [comment]
Requested on NewDot

**Comment by mallenexpensify** [comment]
Contributor: @Krishna2323 paid $500 via Upwork
Contributor+: @jayeshmangwani due $500 via NewDot

**Comment by JmillsExpensify** [comment]
$500 approved for @jayeshmangwani
