### ISSUE TITLE
[$500] Receipt - Tapping "Get out here" redirects to OldDot

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39353]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4467075
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-condition: Keep admin account by adding an employee in workspace
1. Go to https://staging.new.expensify.com/home
2. Login as employee in one device
3. Tap Workspace
4. Tap plus icon -- request money --- scan
5. Upload a photo using camera
6. Tap request
7. Tap the newly created scan request to open detail
8. Enter amount and merchant
9. Tap receipt
10. Login as admin in other device
11. Open the newly created scan receipt page
12. Keep download option opened
13. From employee account, delete the receipt
14. In admin account, tap download button before receipt disappears
15. Note it direct to 404
16. Tap get out here link

## Expected Result:
Tapping "get out here" directs to https://new.expensify.com/not-found

## Actual Result:
Tapping "get out here" directs to old dot.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c4359858-8e32-4ef8-8b4b-c5efd8ce6537

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188da300f74a64a40</li>
        <li>Upwork Job ID: 1775336384586199040</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by kadiealexander** [comment]
I am inclined to agree, I feel like we'll change this whenever image hosting is moved to newdot.
