### ISSUE TITLE
[Pay meow][$250] Make the app splash screen look the same on all platforms

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#39369]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** [Link](https://expensify.slack.com/archives/C049HHMV9SM/p1705601141119089)

## Action Performed:
1. Open up the app on mWeb, Web, or Desktop
2. Notice that the splash screen is dark
3. However on native mobile apps, notice that the splash screen is green

## Expected Result:
1. Let's make the app splash screen green on all platforms
2. This means that we don't need to adjust anything about the mobile apps, but we need to modify web, mWeb, and desktop to use a green splash.  

This is what the splash **should** look like:
![CleanShot 2024-04-09 at 09 59 49@2x](https://github.com/Expensify/App/assets/2319350/62f26b3f-5355-4b6e-b28c-3a51b8ed28f6)

![CleanShot 2024-04-09 at 10 00 28@2x](https://github.com/Expensify/App/assets/2319350/95149c66-60f6-4fe3-9390-1258aa449d34)

![CleanShot 2024-04-09 at 10 00 44@2x](https://github.com/Expensify/App/assets/2319350/1a3d8dde-c90b-43df-a816-7c070e918083)

![CleanShot 2024-04-09 at 10 00 57@2x](https://github.com/Expensify/App/assets/2319350/f626e724-1804-45a8-9d26-e5979123b858)

## Actual Result:
1. The app splash screen is not green on all platforms

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-04-01 at 18 32 30@2x](https://github.com/Expensify/App/assets/2319350/366619f1-0d65-47e6-950b-b5696a60c1a7)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cc @grgia - we talked about this one in Slack, sorry for the delay in creating the issue. Any details you want to add? 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105d7830f9d724cc5</li>
        <li>Upwork Job ID: 1775314488272797696</li>
        <li>Last Price Increase: 2024-04-03</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shawnborton** [comment]
cc @Expensify/design for vis too

**Comment by mallenexpensify** [comment]
@grgia I made this `External` but then realized you self-assigned.  Do you not want a contributor to help with this?  Thx

**Comment by grgia** [comment]
Yeah let's make it external @mallenexpensify !

**Comment by rushatgabhane** [comment]
@ShridharGoel on native, could you please make sure that the notification status bar is also theme dependent?

**Comment by rushatgabhane** [comment]
oh awesome!

**Comment by rushatgabhane** [comment]
@ShridharGoel's [proposal](https://github.com/Expensify/App/issues/39369#issuecomment-2030188782) LGTM 🎀 👀 🎀

**Comment by dannymcclain** [comment]
@ShridharGoel I believe this should help:
![image](https://github.com/Expensify/App/assets/7516624/c5a0c955-d3cf-457b-b64b-259293b4f297)

But @shawnborton can double-check me!

**Comment by shawnborton** [comment]
Perfect, thanks Danny!

**Comment by rushatgabhane** [comment]
that's not ideal. we need to fix the flickering

**Comment by dubielzyk-expensify** [comment]
Agree. We don't want any flicker

**Comment by shawnborton** [comment]
I think for the native mobile apps, we should keep the splash screen the same as it currently is with the green BG because it creates the effect of the app icon morphing into the splash BG. 

For the non-native platforms, I'm curious what @grgia thinks about this:

> There doesn't seem to be any way to get the theme data from Onyx before the splash screen shows

**Comment by grgia** [comment]
> Should we implement splash colours based on the device theme instead of app theme?

Hmm, you can hard set your theme, which may differ from your device theme. I think it's somewhat the same as the problem we have now, where the splash is always dark and may mismatch the theme.

This does allow for a light splash theme but may still result in a mismatch of the theme, which may be preferable but still doesn't quite solve the problem. We could leave as is and it would be the same experience for probably 50% of users (dark splash, to whichever theme)

> There doesn't seem to be any way to get the theme data from Onyx before the splash screen shows

This was the original problem that we encountered while working on the theme project and we decided not to research further, so I can't say if there's a better solution. Do we have access to ONYX at all during this time @ShridharGoel ? 

> For web, there's a flicker issue because again we don't have the Onyx data at the very start.

Could you show me what you mean by flicker issue?

**Comment by grgia** [comment]
> I think for the native mobile apps, we should keep the splash screen the same as it currently is with the green BG because it creates the effect of the app icon morphing into the splash BG.

Whoops missed this comment. 

So yeah I guess if it is deemed impossible to match to the theme, we would leave as is @shawnborton ?

**Comment by shawnborton** [comment]
> So yeah I guess if it is deemed impossible to match to the theme, we would leave as is

If we deem this as impossible, I suppose our options could be:
- just match the system theme
- use green BG with dark iconmark like mobile does
- do nothing

Curious if @Expensify/design has a strong opinion, but let's also figure out if this is impossible or not too.

**Comment by dannymcclain** [comment]
>use green BG with dark iconmark like mobile does

I think this is probably the best choice if we really can't get the theming to work properly. At least this way it will be consistent and look nice regardless of which theme you're using.

**Comment by shawnborton** [comment]
Cool, I could definitely get down with green as the best option here.

**Comment by shawnborton** [comment]
Probably? I guess we need to decide if we want to keep the staging and dev subscript text on these during start up... mobile currently does not have them, but all other platforms do. So if that's the case, the design team can help create new assets with the correct colors there given that the green we use for "STG" is quite similar to the green we'd be using for the background.

**Comment by shawnborton** [comment]
> Makes sense, so how can we decide whether "DEV" and "STG" are needed?

We currently do this on web/mWeb.

**Comment by shawnborton** [comment]
Let's get confirmation from the entire @Expensify/design that we want to move forward with a green BG, and if so, I'll update this issue so we can get proposals based on our new solution. From here, the design team can provide the correct assets needed.

**Comment by shawnborton** [comment]
Okay I've updated the title and description of the bug. 

The replacement assets to use are here: [SplashAssets.zip](https://github.com/Expensify/App/files/14915338/SplashAssets.zip)

**Comment by rushatgabhane** [comment]
PR on production last week - https://github.com/Expensify/App/pull/39997#issuecomment-2069780196

**Comment by rushatgabhane** [comment]
Manual request here - https://staging.new.expensify.com/r/7309992663381871

**Comment by JmillsExpensify** [comment]
@mallenexpensify can I get a payment summary?

**Comment by mallenexpensify** [comment]
[PR hit production on 4/22](https://github.com/Expensify/App/pull/39997#issuecomment-2069780196). 

Contributor: @ShridharGoel due $250 via Upwork
Contributor+: @rushatgabhane due $250 via NewDot

@ShridharGoel can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0105d7830f9d724cc5

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by mallenexpensify** [comment]
@ShridharGoel paid, main payment post updated [above](https://github.com/Expensify/App/issues/39369#issuecomment-2087728017)

Thx
