### ISSUE TITLE
Web - IOU - When opening the IOU report offline, an infinite skeleton appears

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36657
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create two money requests in a chat
2. Open the IOU report and send some messages
3. Open another report and send a message
4. Logout and login again with the same account
5. Without opening any other report, go offline
6. Open IOU report that we created above

## Expected Result:
The total amount is displayed, and at least one money request is visible.

## Actual Result:
When opening the IOU report offline, an infinite skeleton appears

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ef6bc751-7d0d-4c50-91f3-4e7610a35055

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@greg-schroeder I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by greg-schroeder** [comment]
This is expected behavior I think. I'm going to close this, but please reopen if you disagree.
