### ISSUE TITLE
Check server logs for `getIOUReportActionDisplayMessage` to see if transaction param is used

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#39408]
A log was added in [this PR](https://github.com/Expensify/App/pull/38882/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b9a30d2aecd8811dbR5223) to conclusively determine if the `transaction` param is necessary or used. 

Sometime after April 15, check the server logs for `blob="Transaction Param Used when getIOUReportActionDisplayMessage was called from ReportActionItemMessage"` and:

- If the log has NOT happened, then the transaction param is safe to remove and @FitseTLT will remove it
- If the log has happened, then the log can be removed by @FitseTLT

**Comment by tgolen** [comment]
@FitseTLT It looks like that log is happening quite regularly:

![image](https://github.com/Expensify/App/assets/1228807/1104364e-dc6b-4100-a4ad-c5a422a7b876)

**Comment by FitseTLT** [comment]
Thx. Will raise a PR to remove the log tomorrow.
