### ISSUE TITLE
IOU - No option to delete IOU request when there is only one request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39405]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money.
3. Create a manual request from any user that has no unsettled IOU.
4. In 1:1 DM, click on the IOU preview.
5. Click 3-dot menu.

## Expected Result:
There will be option to delete IOU request when there is only one request.

## Actual Result:
There is no option to delete IOU request when there is only one request.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ac6d9fde-a7cb-4fd8-a5ac-e464b91ae8db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
cc @NikkiWines 

I think this is coming from the one transaction view PR which hit staging https://github.com/Expensify/App/pull/36934

**Comment by NikkiWines** [comment]
Oh yeah, I don't think we considered this case actually 🤔 - this and holding requests won't be visible because we're displaying the `MoneyReportHeader` not the `MoneyRequestHeader` at this level. I'll spin up a fix

**Comment by mountiny** [comment]
Nikki is handling ❤️ so unassigning

**Comment by NikkiWines** [comment]
Works on staging now! 🚀 

https://github.com/Expensify/App/assets/16747822/254c9c7a-e463-49aa-aef1-e0e3a8ac75ce
