### ISSUE TITLE
IOU - Skeleton IOU preview appears in IOU details page when there is one request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39403]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money.
3. Create a manual request from any user.
4. In 1:1 DM, click on the IOU preview.

## Expected Result:
There will no be preview in transaction thread.

## Actual Result:
A skeleton preview is shown in transaction thread.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/18cb9759-559d-493f-a37e-9e35e82ffc29

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by NikkiWines** [comment]
Oh, yep - definitely introduced by https://github.com/Expensify/App/pull/36934. We should be using `combinedReportActions` there and also if we've passed a `transactionThreadReport` we know that the report is a one-transaction report and should skip the optimistic preview.

**Comment by NikkiWines** [comment]
@puneetlath I'll spin up a PR to handle the couple blockers that https://github.com/Expensify/App/pull/36934 introduced, so i can take this over if you'd like

**Comment by NikkiWines** [comment]
No skeleton on staging 🎊 

https://github.com/Expensify/App/assets/16747822/69407463-1d46-4c26-9f9c-5f8682695935
