### ISSUE TITLE
[$250] Status – App redirects to Profile page when cleared status without saving

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39409]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38797
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to /settings/profile/status
4. Add status
5. Clear the status and press nothing

## Expected Result:
App redirects to Profile page when cleared status and press save

## Actual Result:
App redirects to Profile page when cleared status without saving. Status reappears for a moment when clear it only on Web

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/268638e7-8525-48c3-8905-7eff44b13f7a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01802fb0f898a8a8e6</li>
        <li>Upwork Job ID: 1777701841723547648</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by miljakljajic** [comment]
reviewing proposals

**Comment by FitseTLT** [comment]
Intentional behaviour not a bug

**Comment by c3024** [comment]
>Actual Result:
App redirects to Profile page when cleared status without saving. Status reappears for a moment when clear it only on Web

I don't see status reappearing on `main`. This is intentional behaviour and not a bug.

**Comment by miljakljajic** [comment]
I agree that this is expected - going to close out.
