### ISSUE TITLE
Web - Scan receipt - Banner in header with Scanning and prompt are missing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39414]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4468880
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the App
2. Navigate to the workspace chat as the employee
3. Select the option to Request money &gt; Scan receipt
4. Select the option to upload a receipt
5. Upload a receipt file
6. Click on Request

## Expected Result:
When opening request details, there's a banner in the header indicating the scan is in progress and "Only you can see this receipt when it's scanning. Check back later or enter the details now."

## Actual Result:
When opening the request details, "NextStep" These expenses are scheduled to automatically submit on Sunday! No further action required! This report may be selected at random for manual approval. is displayed.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0a2ad9da-1b16-4495-b36e-23e663c7ef9a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Not reproducible in Production 

![image](https://github.com/Expensify/App/assets/93399543/16d84cf9-a5ef-4b64-a766-d84800b8d6ac)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by NikkiWines** [comment]
This is tied to https://github.com/Expensify/App/pull/36934 and we'll need to have a larger discussion on how to handle the combined status header for the moneyReuqest and moneyReport for a one-transaction view 

cc: @shawnborton

**Comment by NikkiWines** [comment]
I don't think we should block on this personally but it'll definitely need to be updated.

**Comment by NikkiWines** [comment]
Yep, currently fixing the blockers that can be resolved more quickly but will raise it afterwards

**Comment by NikkiWines** [comment]
Posted [here](https://expensify.slack.com/archives/C05RECHFBEW/p1712113334732779)

**Comment by NikkiWines** [comment]
Discussion is underway

**Comment by NikkiWines** [comment]
Discussion is still ongoing, dropping to weekly until we get a consensus

**Comment by NikkiWines** [comment]
Going to close this out in favour of https://github.com/Expensify/App/issues/39989 that arose as part of the aforementioned slack discussion.
