### ISSUE TITLE
IOU - Combined report appears briefly when navigating to IOU report from transaction thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Request money from a user that has no unsettled request.
3. Create another IOU with the same user.
4. Go to transaction details of one of the requests.
5. Add some comments.
6. Click on the header subtitle to return to IOU report.

## Expected Result:
Combined report will not appear since there are more than one requests.

## Actual Result:
Combined report appears briefly when navigating to IOU report from transaction thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3f59ba46-6c70-4843-80c7-a7dbc27432cf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@isabelastisser I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/69053138-e944-42da-97e2-c4c9aac5028e

**Comment by NikkiWines** [comment]
Pretty sure this is tied to https://github.com/Expensify/App/issues/39403 - seems like a similar bug. I'll work on a fix now 👍

**Comment by NikkiWines** [comment]
This is at least improved on staging where it's a much shorter loading period but will still look into resolving this fully 🤔 

https://github.com/Expensify/App/assets/16747822/d8e19591-bd3b-451d-91a2-fe141405de21

**Comment by NikkiWines** [comment]
However, I think this can be a polish since it requires someone going through some niche steps to experience and won't be super easily found by users going through a normal flow

**Comment by NikkiWines** [comment]
I'm not seeing this behavior on staging any more - let's close this out and if it pops up again it's a good external issue:


https://github.com/Expensify/App/assets/16747822/502e804c-9b5e-44a6-b593-03cc62ff2aff


https://github.com/Expensify/App/assets/16747822/7aeb7c46-a779-43c5-a6f4-fe728e8f89e4
