### ISSUE TITLE
 IOU - Add receipt thumbnail is grayed out in combined report but not in transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39427]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Request money from user that has no unsettled IOU
4. Go to combined IOU report
5. Note that the add receipt thumbnail is grayed out
6. Create another IOU request
7. Go to transaction thread
8. Note that the add receipt thumbnail is not grayed out

## Expected Result:
There should be consistency in whether to gray out add receipt thumbnail in combined report and transaction thread when request is created offline

## Actual Result:
Add receipt thumbnail in combined report (Steo 4) is grayed out, but it is not grayed out in transaction thread (Step 7)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/36e5a22b-6820-4dc7-b3ad-0848254b1d30

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stitesExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by NikkiWines** [comment]
I think this is resolved by https://github.com/Expensify/App/pull/39433

**Comment by NikkiWines** [comment]
Ok, it isn't but it's a pretty minor bug and probably doesn't need to be a blocker. The PR to resolve this is [here](https://github.com/Expensify/App/pull/39465)

**Comment by stitesExpensify** [comment]
> Ok, it isn't but it's a pretty minor bug and probably doesn't need to be a blocker. The PR to resolve this is [here](https://github.com/Expensify/App/pull/39465)

@NikkiWines since that was merged is this fixed now?

**Comment by NikkiWines** [comment]
Yes, I believe this is resolved - though not by that PR in the end (see [here](https://github.com/Expensify/App/pull/39465#discussion_r1557381185) for more context) But this can be closed out
