### ISSUE TITLE
Hold request - App crashes after closing education modal when holding request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39428]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Create two IOU requests from user with no unsettled request.
3. Go to the transaction thread of second request.
4. Click 3-dot menu > Hold request.
5. Enter a reason and save it.
6. Click Got it.
## Expected Result:
App does not crash.

## Actual Result:
App crashes after closing education modal when holding request.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
[Bug6435802_1712077056478!staging.new.expensify.com-1712076948572.txt](https://github.com/Expensify/App/files/14842112/Bug6435802_1712077056478.staging.new.expensify.com-1712076948572.txt)

https://github.com/Expensify/App/assets/38435837/924412c7-6444-41ad-b1b9-51d524d13399

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179897753ac25371c</li>
        <li>Upwork Job ID: 1775801257981403136</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@kevinksullivan YI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this might be related to #wave-collect - Release 1

**Comment by robertjchen** [comment]
Yes, the frontend needs to be updated here as a result of some backend changes 👍 Since this the backend part is already live, it wouldn't be a deploy blocker.

**Comment by robertjchen** [comment]
Actually, thinking about it some more- the hold reason should still go through the moderation flow. So this may still need t be a backend change.

**Comment by robertjchen** [comment]
Backend fix was merged, should be going out shortly!
