### ISSUE TITLE
[HOLD for payment 2024-04-15] Return the approverAccountID and reimburserAccountID to Onyx

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39423]
## Problem
Coming from https://github.com/Expensify/App/pull/37391#pullrequestreview-1907116728, we key personalDetails by accountID, but policy.approver and poliyc.reimburserEmail sends the approver email data back to Onyx, which leads to an inefficient lookup for personal details.

## Why is this important
Affects performance

## Solution
Send the approverAccountID and reimburserAccountID to Onyx so we can use that to lookup personal details instead of the approver email. Once that's done, we should remove [getPersonalDetailByEmail](https://github.com/Expensify/App/pull/37391/files#diff-ff1a0c0087f151243c758ae7346cbf8f25b22de7c61370102de747a06bb94cedR59)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01781c07caff758274</li>
        <li>Upwork Job ID: 1775199977020665856</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment]
I got this [payment GH ](https://github.com/Expensify/App/issues/39551)but I think it's for this job? 

Should we just pay @s77rt in here?

**Comment by s77rt** [comment]
Yes. We should close the other one

**Comment by stephanieelliott** [comment]
PR is undergoing QA

**Comment by s77rt** [comment]
Not a bug. Performance improvement. Checklist does not apply ^

**Comment by stephanieelliott** [comment]
Hey @s77rt I extended the offer to you in Upwork, can you please accept when you get a chance? https://www.upwork.com/jobs/~01781c07caff758274

**Comment by stephanieelliott** [comment]
All paid! See summary here: https://github.com/Expensify/App/issues/39423#issuecomment-2057507494
