### ISSUE TITLE
IOU-Comment from a deleted IOU disappears until a third IOU is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39438]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/36934
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open workspace chat
3. Click on + icon from the compose box
4. Click on request money
5. Enter an amount and click on next
6. Enter a merchant and confirm the request
7. Repeat step 3 - 6 once again
8. Open the transaction thread for the IOU created on step 7
9. Add a comment
10. Open the transaction thread of the first IOU created at step 6
11. Click on Merchant and update it to something else
12. Go back to the expense report page and delete the second IOU created on step 7
13. Go to workspace chat page
14. Repeat step 3 - 6 once again
15. Open the expense report page

## Expected Result:
The deleted IOU with the comment in thread should be present while in the expense report page

## Actual Result:
The deleted IOU with the comment in thread disappears when the second IOU is deleted but re appears when a third IOU is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1ad45498-bd02-4f85-bca1-6254d2b88c9d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
This looks related to https://github.com/Expensify/App/pull/36934. I can't tell if it's by design or if it was an oversight, but it's not clear to me why we're showing the `[Deleted request]` that have child comments. We don't show deleted as `[Deleted request]` if they don't have any child actions. cc @NikkiWines 

<img width="934" alt="image" src="https://github.com/Expensify/App/assets/2229301/d1525bae-8499-4800-aa00-b8d4372871d2">

**Comment by NikkiWines** [comment]
I'm not sure if I'm doing something incorrectly but this looks the same to me on staging and production right now: 

**Prod**

| 2 IOUs (1 Deleted) | 3 IOUs (1 deleted - middle) |
| ------------- | ------------- |
| ![image](https://github.com/Expensify/App/assets/16747822/ea0fa20d-3c51-4fb3-a7a5-af1bd063d588) | ![image](https://github.com/Expensify/App/assets/16747822/1f1dbc1b-aa5c-40d1-89a1-22a4938df838) |

**Staging**

| 2 IOUs (1 Deleted) | 3 IOUs (1 deleted - middle) |
| ------------- | ------------- |
| ![image](https://github.com/Expensify/App/assets/16747822/b830bd5d-5997-41cd-8c04-971194fd9712) | ![image](https://github.com/Expensify/App/assets/16747822/ee957612-6862-4d3c-8610-f8f7af758cc5)|

**Comment by francoisl** [comment]
Ok yeah that makes sense, thanks for checking. I see the same thing in production, sounds like this is something that we can polish later if we want to change the behavior. Going to demote for now.
