### ISSUE TITLE
Feature Request: Make URL clickable if the merchant name is a URL

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39430]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
If the merchant name is URL , it is not clickable

## Solution:
Make the URL clickable 

## Context/Examples/Screenshots/Notes:

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711992147684789

**Comment by trjExpensify** [comment]
Asking in thread about [this](https://expensify.slack.com/archives/C049HHMV9SM/p1711992147684789).
