### ISSUE TITLE
Workspace -"Make or track payments" is disabled after toggling off and on Workflows

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4468674&group_by=cases:section_id&group_order=asc&group_id=283225
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Navigate to Workspace settings - More features
4. Enable workflows
5. Disable workflows
6. Enable workflows again

## Expected Result:
"Make or track payments" should be enabled.

## Actual Result:
"Make or track payments" is disabled after toggling off and on Workflows.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f59d750f-f61b-470d-bddf-7318c288bf11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment]
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by abzokhattab** [comment]
seems to be the intended behaviour: https://github.com/Expensify/App/pull/38432

> Details
Optimistically set defaults for Workflows if feature is disabled

**Comment by JmillsExpensify** [comment]
Agree that this should be the intended behavior.
