### ISSUE TITLE
[Awaiting Payment 23rd April] [$500] Web-Workspace -Number of announce room members does not update when remove workspace members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4468627&group_by=cases:section_id&group_order=asc&group_id=229065
**Email or phone of affected tester (no customers):** applausetester+gm156@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in as a Expensifail account
2. Create a workspace
3. Navigate to the Invite members page in workspace> Invite few accounts
4. Select the invited members and remove them
4. Send some messages in the #Announce room
5. Click on header of the room to open Details
6. Take a note of number of room members

## Expected Result:
Number of announce room members should update when user remove workspace users

## Actual Result:
Number of announce room members does not update when remove workspace members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5213ffd5-da5f-466c-8f0a-694dc9b7ad3a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01758a9e58b1dd4c58</li>
        <li>Upwork Job ID: 1776307639554646016</li>
        <li>Last Price Increase: 2024-04-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@jasperhuangg  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jasperhuangg** [comment]
I can reproduce this issue, the only reason it's happening is because the `DeleteMembersFromWorkspace` command hasn't completed. Once it does, the number correctly updates.

I don't think this needs to be a blocker, but we should update the front-end in this case to optimistically add/remove people from a workspace's default rooms when they are added/removed from the workspace.

**Comment by jasperhuangg** [comment]
@GandalfGwaihir Thanks for pointing that out, agree that it was created before the new payment structure was announced. @trjExpensify I'm gonna go ahead and update the price to $500, feel free to change it back if you disagree.

**Comment by trjExpensify** [comment]
Confirming payment summary as follows: 

- $500 to @GandalfGwaihir for the fix - offer sent
- $500 to @rayane-djouah for the C+ review - offer sent

**Comment by trjExpensify** [comment]
@GandalfGwaihir paid!

**Comment by trjExpensify** [comment]
Paid!
