### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] The `inline code` format isn't previewing correctly 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39458]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712094742944359

## Action Performed:
1. Open any chat
2. Type a message with bold , italics and inline codes
## Expected Result:
Should use the same font and background style
## Actual Result:
Not showing with correct font and background style
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7eb2a147-f08e-405f-84f1-0c7b4257d8a6

![image (8)](https://github.com/Expensify/App/assets/38435837/499241b5-8b58-47c0-b904-5490297505c1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f04fc983fdd1696</li>
        <li>Upwork Job ID: 1775529008351977472</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by tomekzaw** [comment]
Working on a fix

**Comment by trjExpensify** [comment]
Cool, @thienlnam let me know if you want to be added as the internal engineer to assist on it. 👍

**Comment by trjExpensify** [comment]
👋 checklist time @shubham1206agra!

**Comment by trjExpensify** [comment]
Offer sent! Confirming payment summary as $500 to @shubham1206agra for the C+ review.

**Comment by trjExpensify** [comment]
Paid!
