### ISSUE TITLE
New line is added when the composer expanded with an emoji in the message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39456]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712079806486669

## Action Performed:
1. Open app
2. Go to any chat
3. add an emoji and type message for 2 lines
4. Click on the expander and collapse it
## Expected Result:
No extra line added in the composer
## Actual Result:
A new line is added
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b5dbf131-0869-4446-bc8c-6433039ee5d6

https://github.com/Expensify/App/assets/38435837/6a9860d8-7115-45a8-867e-d7cbdaf86acb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
In the end I re-used a similar [GH issue](https://github.com/Expensify/App/issues/39361) and changed the title and test steps. I will close it in favor of that one
