### ISSUE TITLE
Add better testing coverage for comment linking

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#39460]
@perunt this issue is a placeholder to implement a bunch of UI tests to cover comment linking functionality

**Comment by perunt** [comment]
Currently, we have one end-to-end test for opening a link in another chat. I have a few ideas for these tests:

1. Open a link from Chat A to Chat B if messages are preloaded in Onyx.
2-3. Open a link from Chat A to Chat B if messages are preloaded in Onyx and located on the edge of preloading. This will help us know if we properly trigger fetch more and if the focus on the linked message is preserved. Also, do the same for the opposite side.
4. Open a link from Chat A to Chat B for an image message.
5. Open a link from Chat A to Chat B for a thread.
6. Open a link from Chat A to Chat B for a message with a reaction

**Comment by roryabraham** [comment]
@perunt any update here?

**Comment by roryabraham** [comment]
@perunt is OOO, definitely hoping that we complete this before he jumps into anything else though

**Comment by roryabraham** [comment]
@perunt I'm looking at doing a significant refactor of comment linking - this is a very important issue to work on to provide better stability for this core feature

**Comment by roryabraham** [comment]
Saw some partial updates here from @janicduplessis last week: https://expensify.slack.com/archives/C05LX9D6E07/p1715895921197829?thread_ts=1714656403.682529&cid=C05LX9D6E07

**Comment by janicduplessis** [comment]
I have some extra unit tests for `getContinuousReportActionChain` to cover some edge cases around inserting random actions. I have a few more cases in mind too that I want to add.

After that it would be great to add some UI tests to have more complete test coverage of comment linking flows.

**Comment by perunt** [comment]
Not overdue, I just started working on it. I'ill push some tests soon

**Comment by roryabraham** [comment]
@janicduplessis has been working on UI tests in the new client-side gap detection PR

**Comment by perunt** [comment]
Is it still needed in the E2E tests?
Also, do we have a list of issues related to comment linking? I just want to check if my finding has already been captured

**Comment by roryabraham** [comment]
This is done
