### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Kill ReconnectToReport

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#39464]
In the context of optimizing `ReconnectToReport`, we are [proposing](https://expensify.slack.com/archives/C05CBC62HGW/p1703084287653689?thread_ts=1702997957.573009&cid=C05CBC62HGW) to just get rid of it since it became redundant after `reliable updates` was implemented.

`ReconnectToReport` command was introduced to get the missing `reportActions` after coming back online. This was necessary because `ReconnectApp` didn't get `reportActions`, but now that we have "reliable updates", we are able to fetch and retrieve the missed Onyx updates which contain the missing report Actions (The missed updates are returned by `ReconnectApp`).

___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
With a report open, go offline and the online again

## Expected Result:
Looking at the network requests, we should only see a `ReconnectApp` request and not a `ReconnectToReport` request

## Actual Result:

`ReconnectToReport` is there, is sometimes slow and is useless.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
Adding @c3024 in the role of C+ to review the PR https://github.com/Expensify/App/pull/34902

**Comment by c3024** [comment]
@aldo-expensify 

Backend sends a 'deprecated version' error. Clicking on update or refreshing the page does not fix it. 🤔 

https://github.com/Expensify/App/assets/102477862/f9456413-ed9f-4a86-9dde-291f79ac6a12

**Comment by lschurr** [comment]
It looks like the linked PR was merged but isn't deployed to prod yet. Once it is, the payment date will be set.

**Comment by lschurr** [comment]
Offer sent to @c3024 in Upwork - https://www.upwork.com/nx/wm/offer/101841684

**Comment by c3024** [comment]
@lschurr accepted. Thanks.

**Comment by lschurr** [comment]
Payment summary:

- $500 to @c3024 (paid in Upwork)
