### ISSUE TITLE
[HOLD for payment 2024-05-02] Split the performance test workflow to two github workflows

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39481]
### Problem

We cannot use the performance test workflow triggered on PR merge with main as that leads to Emergency label being applied since the github action is queued when we merge it.

### Solution

Split the [reassure perf tests](https://github.com/Expensify/App/blob/ab09e28ce6437fc31c48cb8963f8e5dc5828bf10/.github/workflows/reassurePerformanceTests.yml#L1-L78) workflow into two workflows, such that we wont run the workflow on the PR when merged to avoid the false Emergency label applied

cc @johnmlee101 @rinej

**Comment by mountiny** [comment]
@rinej is looking into this

**Comment by mountiny** [comment]
Reviewed the PR and discussing in [slack](https://expensify.slack.com/archives/C05LX9D6E07/p1712313905066499?thread_ts=1711994603.751489&cid=C05LX9D6E07)

**Comment by mountiny** [comment]
So I think this is now up and running and we can close this issue

**Comment by mountiny** [comment]
Seems like something broke the reassure dashboard data 😢 but it was before these changes I think #39293 PR was the last one we got data from https://github.com/Expensify/App/pull/39293 🤔 so possibly the PR after that broke it, but not sure

@rinej could you please have a look to see if there is any change about the data?

**Comment by rinej** [comment]
Sure @mountiny, I checked it and it looks like we send empty data to the graphite server: 
<img width="478" alt="Screenshot 2024-04-22 at 15 26 44" src="https://github.com/Expensify/App/assets/2650904/01abe4c7-7198-4400-a9ba-6a46b204e265">

There was issue with parsing timestamp.

Here is the PR with the fix -> https://github.com/Expensify/App/pull/40687

**Comment by mountiny** [comment]
Merged, lets see if this will help

**Comment by alexpensify** [comment]
@mountiny to confirm, to prepare the payment process, I see the following: 

@rinej was the contributor 
@ikevin127 was the C+ 

--- 

Does everyone agree with this breakdown? After, I can start the next steps. Thanks!

**Comment by ikevin127** [comment]
> Skipping the payment summary for this issue since all the assignees are employees or vendors. If this is incorrect, please manually add the payment summary [SO](https://stackoverflowteams.com/c/expensify/questions/17778).

Nope, wrong!

@alexpensify I require payment as external reviewer (C+).

**Comment by alexpensify** [comment]
Heads up, I'm going to be OOO until Tuesday, @strepanier03 is going to step in to help with the payment process. We are currently waiting for @mountiny's confirmation and then can carry one with the next steps.

**Comment by strepanier03** [comment]
Looks like @ikevin127 was a no QA reviewer of the PR so they'd be eligible for the $250 payment for a PR review. I'll let @mountiny confirm but that's my plan if we don't hear anything.
