### ISSUE TITLE
Tag - Tag selection cleared if selected before missing tag violation appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38881
## Action Performed:
precondition: user is an employee of the collect policy in OD, as an admin upload a set of independent tags in OD
1. Go to https://staging.new.expensify.com/
and log in as an employee
2. Open the workspace chat and request money
3. In OD change the order of tags
4. In ND create another money request
5. Open the transaction chat
6. Before the "Missing tag" violation appears, select tags

## Expected Result:
The "Missing tag" violation is not displayed for tags that have already been selected

## Actual Result:
After the "Missing tag" violation appears, the previous tag selection gets cleared out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ce27e627-fb6b-483f-bb51-05b7a8d912c4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment]
This only happens if you both change the order of the tags in OldDot AND very quickly after doing that try and create a report in NewDot on the policy. If you wait like ~1 minute after changing the order of the tags, i can't reproduce. That said, this is very niche, and doesn't seem like worth prioritizing. Let's see if this impacts anyone before deciding to fix.
