### ISSUE TITLE
Workspace - The page scrolls to the top when Account Number field is tapped

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38318
## Action Performed:
1. Log in with an expensifail account
2. Create a new workspace
3. Enable Workflows
4. Add bank account manually
5. Input "011401533" as Routing Number
6. Tap inside the Account Number field

## Expected Result:
The page shouldn't scroll by itself

## Actual Result:
The page scrolls to the top when the keyboard is visible and the "Account Number" field is tapped. Sometimes it happens when the user swipes to the bottom of the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a0cddef4-cd3e-4d2d-bb8d-f75ac86287a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
could not repro on latest
