### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] Send money - IOU preview appears in one transaction report view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39490]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM.
3. Click + > Send money.
4. Send money to the user.
5. Click on the IOU preview.

## Expected Result:
There will not be IOU preview in the one transaction report view (combined report).

## Actual Result:
There is an IOU preview in the one transaction report view (combined report), which opens the same transaction thread.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/715de719-939d-4c20-80eb-8ba835b130f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139f0b6a0758d561f</li>
        <li>Upwork Job ID: 1775551164535427072</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by mountiny** [comment]
I can help with this one

**Comment by mountiny** [comment]
cc @NikkiWines

**Comment by mountiny** [comment]
PR is here https://github.com/Expensify/App/pull/39499

**Comment by mountiny** [comment]
This will be $250 to @parasharrajat for review once all is wrapped up

**Comment by stephanieelliott** [comment]
This is ready for payment via ND, see summary: https://github.com/Expensify/App/issues/39490#issuecomment-2057506539

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
