### ISSUE TITLE
[$250] Task - Task details become blank after changing title or description several times

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39500]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Open any chat and create a tasking, 
3. Open the task details
4. Change the title or description several times

## Expected Result:
The task details with the updated title or description are displayed every time the changes are made

## Actual Result:
After updating the task title or description the task details become blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1696fa18-75a4-4f46-b4c5-d2c9997e0511

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0169f40ad10a6d41aa</li>
        <li>Upwork Job ID: 1776386993875103744</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment]
Well... that's strange.  I was able to reproduce on staging.new.expensify.com in Chrome.  I was not able to reproduce on desktop. @dukenv0307 , please comment if you don't think this can be external. 


https://github.com/Expensify/App/assets/22508304/09e66a12-8769-47b8-8921-5180d8b3092c

**Comment by mallenexpensify** [comment]
Thanks @dukenv0307 , Added `retest weekly`

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment]
Gonna close as not reproducible. Comment/reopen if needed.
