### ISSUE TITLE
[Mentions v2] Send reportName and reportID for mentionedReportIDs on CreateReportAction

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#39513]
When calling `CreateReportAction` with a room mention we need to start sending back the `reportName`s and `reportID`s as onyx updates so everyone in the room have what is needed to show the message properly, details can be found [here](https://docs.google.com/document/d/1g_1xLGO29EV6hbOtiYqX53oof_gr8jbnbkSRPjuA4RI/edit#bookmark=id.wbt3p7zeryzi).

**Comment by puneetlath** [comment]
This is done and deployed.
