### ISSUE TITLE
Status - The status erase before the time setted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39527]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** alexzamora1487@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Account settings > Profile
2. Click on Status
3. Set an emoji and a message
4. In the "Clear after" select custom
5. Set the time so it finish al 6:29 pm
6. Wait for the time to hit the setup time

## Expected Result:
The status clear on the time setted

## Actual Result:
The status is clear before the time exactly 6:27pm

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/01696d00-ef91-4f64-bace-c331b01dfd3a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by kadiealexander** [comment]
I can't replicate this in the most recent build, it's not blocking a core flow and I don't think it's actually affecting real users. Closing but please reopen if you disagree!
