### ISSUE TITLE
 mWeb - Account Settings / Profile - Error when I introduce a second contact method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39524]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to account settings > Profile
2. Click on "Contact Method"
3. Enter a email with uppercase and lowercase letters but with a correct format
4. Click on the button "Add"

## Expected Result:
1. I'm redirected to the "Contact methods" page
2. There's a green dot next to the newly added email along with a message to verify the contact method

## Actual Result:
There is a red dot net to the newly email added

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ca05957b-fdd4-4c62-887f-257e1ed17d68

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
Cannot reproduce -- 
<img width="339" alt="2024-04-10_13-52-58" src="https://github.com/Expensify/App/assets/56830058/34b3f038-e3c5-45cc-89ab-93cc533ad607">

I just tried it.
