### ISSUE TITLE
[HOLD for payment 2024-06-03] [Violations - Pending Receipts] Display the `rter` Violation with the Pending Pattern

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#39533]
Design Doc: https://docs.google.com/document/d/1zJqlTe_RajuBtfQYvbMx8PpXgA9CEnUGVyuqZihQ-ok/edit
Tracking GH: https://github.com/Expensify/Expensify/issues/372206

HOLD ON https://github.com/Expensify/Expensify/issues/384996

---

Similar to how we have [TransactionUtils.isPending](https://github.com/Expensify/App/blob/723b0503ee7b97cf95e1555c2c4a0a6357714f04/src/libs/TransactionUtils.ts#L446-L454) and [TransactionUtils.isReceiptBeingScanned](https://github.com/Expensify/App/blob/723b0503ee7b97cf95e1555c2c4a0a6357714f04/src/libs/TransactionUtils.ts#L466-L468) in NewDot to help us with other pending UI flows, we'll add a new method: `TransactionUtils.hasPendingRTERViolation`:

### TransactionUtils.hasPendingRTERViolation

This will have a similar structure to the current TransactionUtils [methods](https://github.com/Expensify/App/blob/723b0503ee7b97cf95e1555c2c4a0a6357714f04/src/libs/TransactionUtils.ts#L561-L570) that check for / retrieve violations.
- Params:
    - `transactionID`: `string`
    - `transactionViolations`: `TransactionViolation[]` - the set of violations for that specific transaction. For components where we are subscribing to _all_ violations we can use the output of [TransactionUtils.getTransactionViolations](https://github.com/Expensify/App/blob/723b0503ee7b97cf95e1555c2c4a0a6357714f04/src/libs/TransactionUtils.ts#L568-L570)
- Returns:
    - A boolean: If any of the violations for that `transactionID` in Onyx are the `rter` violation, with `pendingPattern` set to `true`

Additionally, because this will be called frequently with [TransactionUtils.isPending](https://github.com/Expensify/App/blob/723b0503ee7b97cf95e1555c2c4a0a6357714f04/src/libs/TransactionUtils.ts#L446-L454) and [TransactionUtils.isReceiptBeingScanned](https://github.com/Expensify/App/blob/723b0503ee7b97cf95e1555c2c4a0a6357714f04/src/libs/TransactionUtils.ts#L466-L468) let's also make and utilize a method that returns `true` if any of those return `true`: `hasPendingUI()`

We'll outline this in further detail below, but we'll call this method in:
1. [MoneyRequestPreviewContent.tsx](https://github.com/Expensify/App/blob/e5382720d1f3b9d8086ca174f90e27d575253938/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx)
2. [ReportPreview.tsx](https://github.com/Expensify/App/blob/f2e4f5589bce3a3871404f47361f0372ffdd62a4/src/components/ReportActionItem/ReportPreview.tsx)
3. [MoneyRequestHeader.tsx](https://github.com/Expensify/App/blob/b9e115dd9d0ca737a4d4f394ac590381298e483f/src/components/MoneyRequestHeader.tsx)

The first two already have access to the transactionViolations onyx collection key. However, we will need to add it to `MoneyRequestHeader.tsx`.

## Updates to `ReportActionItems: MoneyRequestPreview` /  `ReportPreview`
Now that we know if our transaction has the "7-Day Hold" `rter` violation, we can adjust the UI to reflect that it's "Pending". For [ReportActionItem](https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/pages/home/report/ReportActionItem.tsx) rows, we will do the same thing that was outlined for pending transactions and scanning receipts in the [Update how we display / report expenses](https://docs.google.com/document/d/1hKK7emsQt4iDvP8Ohvk5aCc8gNdRelyxvbxDkXZxNRA/edit#bookmark=id.hpicdhh0ps4f) doc.
![Screenshot 2024-04-03 at 11 27 42 AM](https://github.com/Expensify/App/assets/4741899/9bdb8b35-f440-4584-85b0-ec916ce8e108)

We will show the "pending" [hover](https://github.com/Expensify/App/blob/9e1ce5c7c72180ebe870b0e1d54c112073a870e2/src/pages/home/report/ReportActionItem.js#L739)/[message/icon](https://github.com/Expensify/App/blob/27271d566ec42815e6c34d61e43ccb39840e3ce0/src/pages/home/report/ReportActionItem.js#L742-L764) UI for these two cases:
- [if the action is a Money Request Action](https://github.com/Expensify/App/blob/518aec7699543bbc2988916a0be366829eb79f09/src/libs/ReportActionsUtils.ts#L102) and the linked Transaction has the rter violation (`hasPendingRTERViolation` - in addition to possibly being `isScanning || isPending` as outlined in that doc).
   - We'll also get the proper preview header text as part of [getPreviewHeaderText](https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L132-L184) in the [MoneyRequestPreviewContent](https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx) component.
- [if the action is a Report Preview](https://github.com/Expensify/App/blob/518aec7699543bbc2988916a0be366829eb79f09/src/libs/ReportActionsUtils.ts#L106) containing a single transaction with the rter violation (`hasPendingRTERViolation` or similarly, `isScanning || isPending`).
    - We'll also get the proper message "Receipt pending match with credit card", with the [hourglass icon](https://github.com/Expensify/App/blob/main/assets/images/hourglass.svg) as well, as part of the [logic](https://github.com/Expensify/App/blob/52740f49f7b9d4a34ea091c039c9869d0cba456c/src/components/ReportActionItem/ReportPreview.tsx#L131-L152) in the ReportPreview component:
        <img width="267" alt="e7a8_Cmf6aSHV9sz-7o618SJ4usOxqSyHCvx4aN1DIYdgvnGdZdmSPDMG-C_x9XK58Zau7W6lTi0UNWlcH2YLSsGMhc6Heg6lW1c__rRoYcxdkOyWx8t8RoiLAqP" src="https://github.com/Expensify/App/assets/4741899/16a0830c-80b2-4264-8604-51f7fcb056e5">
    - Additionally, we'll set [shouldShowSubmitButton](https://github.com/Expensify/App/blob/52740f49f7b9d4a34ea091c039c9869d0cba456c/src/components/ReportActionItem/ReportPreview.tsx#L154) to `false` in this case.

## Updates to MoneyReportHeader
Similar to what we're doing for the Report Preview above, if the report contains only transactions with the `rter` violation (which again, we'll alias as `hasPendingRTERViolation`) we'll show the Next Steps banner indicating that the receipts are pending match with a credit card.

We'll also hide the Submit/Approve/Pay [buttons](https://github.com/Expensify/App/blob/26ab4aa0c21352f5b2917bd59df5daf460b36f33/src/components/MoneyReportHeader.tsx#L111-L140) in this case as well (i.e. all transactions are pending).

In the case of the ["One-Expense" Chat](https://github.com/Expensify/Expensify/issues/342922), we'll use the same pattern as the `MoneyRequestHeader` as described below.

## Updates to MoneyRequestHeader
If `hasPendingRTERViolation` is `true`, we'll show a [`MoneyRequestHeaderStatusBar`](https://github.com/Expensify/App/blob/dc656800cb57bf5f6286975f20964b535eaba1eb/src/components/MoneyRequestHeaderStatusBar.tsx) in the [`MoneyRequestHeader`](https://github.com/Expensify/App/blob/26ab4aa0c21352f5b2917bd59df5daf460b36f33/src/components/MoneyRequestHeader.tsx) [here](https://github.com/Expensify/App/blob/26ab4aa0c21352f5b2917bd59df5daf460b36f33/src/components/MoneyRequestHeader.tsx#L177-L190). This will be similar to what we already do for `isPending` and `isScanning`. The message will utilize the same hourglass icon and have the copy as seen below.

Let's also refactor this to be a bit less repetitive. We can create a `getPendingType()` method that checks if the transaction is `RTER` vs `SCANNING` vs `PENDING` and returns the translations keyed by that type.

![Screenshot 2024-04-03 at 11 34 09 AM](https://github.com/Expensify/App/assets/4741899/6ff7c6b9-5d55-45df-9261-e444047bd35a)

### "Mark as cash" Button
This will be covered in a [separate issue](https://github.com/Expensify/App/issues/39541)

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by yuwenmemon** [comment]
Removing the HOLD on this

**Comment by BrtqKr** [comment]
Hey, I'd like to take over this issue

**Comment by grgia** [comment]
in progress

**Comment by grgia** [comment]
cc @smelaa are you working on this? If so, please comment so I can switch assignments

**Comment by smelaa** [comment]
Hi, I am Aleksandra Smela from Software Mansion, an expert agency, and I would like to work on this issue

**Comment by smelaa** [comment]
Hi, as I am diving into the code I have a question to the design. 

> We will show the "pending" [hover](https://github.com/Expensify/App/blob/9e1ce5c7c72180ebe870b0e1d54c112073a870e2/src/pages/home/report/ReportActionItem.js#L739)/[message/icon](https://github.com/Expensify/App/blob/27271d566ec42815e6c34d61e43ccb39840e3ce0/src/pages/home/report/ReportActionItem.js#L742-L764) UI for these two cases:
> [if the action is a Money Request Action](https://github.com/Expensify/App/blob/518aec7699543bbc2988916a0be366829eb79f09/src/libs/ReportActionsUtils.ts#L102) and the linked Transaction has the rter violation…
> [if the action is a Report Preview](https://github.com/Expensify/App/blob/518aec7699543bbc2988916a0be366829eb79f09/src/libs/ReportActionsUtils.ts#L106) containing a single transaction with the rter violation…

From what I understand we need to show „pending” hover/message/icon from the level of `ReportActionItem`. I was thinking to just add an additional condition [here](https://github.com/Expensify/App/blob/27271d566ec42815e6c34d61e43ccb39840e3ce0/src/pages/home/report/ReportActionItem.js#L742-L764). The problem is that we do not have an access to transaction violations in `ReportActionItem`. 
The solution might be to add `Onyx.connect` in `TransactionUtils` for transaction violations [as we do for `allTransactions`](https://github.com/Expensify/App/blob/c75c85f69d46a50258b0cb2870b7b5a4d04702cc/src/libs/TransactionUtils.ts#L20) and then just filter proper violations by transactionID. 
Please let me know if that would be okay or I should find a different approach.

**Comment by grgia** [comment]
Hi @smelaa, I think that approach could work- can we ensure that any pattern added for handling the pending pattern at the reportActionItem level works for the plan laid out in this [doc](https://docs.google.com/document/d/1hKK7emsQt4iDvP8Ohvk5aCc8gNdRelyxvbxDkXZxNRA/edit#bookmark=id.hpicdhh0ps4f) (see linked issue) as well

**Comment by grgia** [comment]
Actually on that note, do we need to add it to the ReportActionItem level? 

We are removing the hover pattern @smelaa

**Comment by smelaa** [comment]
If the hover pattern is no longer needed, I think we don't need access to `transactionViolations` from `ReportActionItem`. Thank you!

**Comment by smelaa** [comment]
Hi, I still have a few questions as I couldn’t find answers in the design docs on my own.

> [if the action is a Report Preview](https://github.com/Expensify/App/blob/518aec7699543bbc2988916a0be366829eb79f09/src/libs/ReportActionsUtils.ts#L106) containing a single transaction with the rter violation (hasPendingRTERViolation or similarly, isScanning || isPending).
> - We'll also get the proper preview header text as part of [getPreviewHeaderText](https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L132-L184) in the [MoneyRequestPreviewContent](https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx) component.

What exactly does 'proper header message' mean?

> Similar to what we're doing for the Report Preview above, if the report contains only transactions with the rter violation […] we'll show the Next Steps banner indicating that the receipts are pending match with a credit card.

I am not sure what is the 'Next Steps banner’ - I think I haven't seen any details regarding this in the design doc?

> We'll also hide the Submit/Approve/Pay [buttons](https://github.com/Expensify/App/blob/26ab4aa0c21352f5b2917bd59df5daf460b36f33/src/components/MoneyReportHeader.tsx#L111-L140) in this case as well (i.e. all transactions are pending).
> In the case of the ["One-Expense" Chat](https://github.com/Expensify/Expensify/issues/342922), we'll use the same pattern as the MoneyRequestHeader as described below.

The link here does not work - could you provide me with more details regarding what exactly you mean by „One-Expense” Chat? (

**Comment by yuwenmemon** [comment]
> What exactly does 'proper header message' mean?

Good question! This refers to the return value of [getPreviewHeaderText](https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L132-L184) here. Specifically, in the case of the RTER violation we'd show the ` ⌛ Receipt pending match with credit card.` message (and relevant translation)

> I am not sure what is the 'Next Steps banner’ - I think I haven't seen any details regarding this in the design doc?

Ah yes, this is because it should already be handled by the Next Steps with the current code in place. No need to worry on your end. This is handled in the API layer with this issue: https://github.com/Expensify/Expensify/issues/381372

> The link here does not work - could you provide me with more details regarding what exactly you mean by „One-Expense” Chat? (

Apologies, that links to an internal issue. Check out this PR: https://github.com/Expensify/App/pull/36934 - It's essentially a special UI we reserve for when a report has only one expense on it. (cc @NikkiWines)

**Comment by smelaa** [comment]
Hi, thank you for all the information! 
The PR is in draft but I still need to:
- handle "One-Expense" Chat case,
- mock the data and test whether the implemented logic is correct,
- and finally once everything work as intended I will need to refactor the code a bit. 

I will be back on Tuesday so in case you need something before that date please ping @BrtqKr, as he is familiar with this issue as well.

**Comment by mallenexpensify** [comment]
@smelaa please provide an update. Thx

**Comment by smelaa** [comment]
Yesterday I worked on something else but today I will continue with [this](https://github.com/Expensify/App/issues/39533#issuecomment-2064015274).

**Comment by smelaa** [comment]
Hi @yuwenmemon @grgia, 
I have added screenshots in the comment to the [PR](https://github.com/Expensify/App/pull/40354) draft  under _MacOS: Chrome / Safari_. Please let me know if it looks okay so I can move on with refactoring and code review.
Also, in my draft for testing purposes I have added some data directly to Onyx (this is what code added in `ReportActionsList` does). If you have some tips how can I test it on a real life data please let me know.

**Comment by yuwenmemon** [comment]
<img width="596" alt="325190456-935438d3-b1e9-4fe8-8158-f1db148743d3" src="https://github.com/Expensify/App/assets/4741899/ca0293ab-ce48-4c95-ba33-7bcadfb0f900">

I think we can move this down to a new line to avoid having the text run over the margin on the right in here.

**Comment by yuwenmemon** [comment]
<img width="596" alt="325195442-7dccd9d5-7501-4fb9-8640-a35f10f8adf6" src="https://github.com/Expensify/App/assets/4741899/d83d4857-f1ee-460c-8d3a-1cba55d7d9b0">

I think the Pending receipt message should show in the bottom of the preview like in the first screenshot of your PR

**Comment by yuwenmemon** [comment]
Commented on the screenshots above. A few small comments from me but overall looks good! I'll also tag in @dannymcclain to give you some feedback as well!

> Also, in my draft for testing purposes I have added some data directly to Onyx (this is what code added in ReportActionsList does). If you have some tips how can I test it on a real life data please let me know.

Mocking the data is probably the best route as it's a relatively complex set up to be able to reproduce with real-life data. I can test on my end with real life data when I review the PR!

**Comment by smelaa** [comment]
@yuwenmemon thank you! Here are some follow up questions.
> I think we can move this down to a new line to avoid having the text run over the margin on the right in here.

Oh, I'm sorry I think I might have cropped the screenshot, here the right margin is the most narrow it can get:
![image](https://github.com/Expensify/App/assets/115273836/e51c4ee0-1bc2-4175-bd20-8d2decff946d)
Also it goes to another line if the window is not wide enough to display the text in one line:
![image](https://github.com/Expensify/App/assets/115273836/9b5be998-98d6-4fa8-8fc9-2338a04f1e83)

In this case, do you think it is okay or still needs some modifications?

> I think the Pending receipt message should show in the bottom of the preview like in the first screenshot of your PR

So just to confirm. It is in the top part of the component because it is where the text from getPreviewHeaderText is displayed. Would you like me to instead of this approach:

> We'll also get the proper preview header text as part of [getPreviewHeaderText](https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L132-L184) in the [MoneyRequestPreviewContent](https://github.com/Expensify/App/blob/59c98ced051b6dd49ae9d56c2eb94c3f4ea23f05/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx) component.

leave getPreviewHeaderText as it is right now and add the text in the bottom? Of course I am okay with that, just want a confirmation.

**Comment by dannymcclain** [comment]
Thanks Yuwen!

Yeah we definitely want the little pending status at the bottom of the report preview. (I can't speak to how we should accomplish that from a technical standpoint.)

And can we double check the sizes and spacings of the little statuses? It looks like maybe some of them are not quite right.

Here's a mockup to check out:
![image](https://github.com/Expensify/App/assets/7516624/867ee990-4cf2-4f42-9234-a03c0697776e)

And here are the specs for that little status:
![image](https://github.com/Expensify/App/assets/7516624/afc72bf9-6b6d-4d11-86a3-1704d7e59008)

**Comment by grgia** [comment]
Thanks @dannymcclain @yuwenmemon, let me know if there's anything else I can help with

**Comment by yuwenmemon** [comment]
> leave getPreviewHeaderText as it is right now and add the text in the bottom? Of course I am okay with that, just want a confirmation.

Yeah apologies - that was a slight oversight on my part. Maybe it should be a separate function like `getPreviewFooterText`

**Comment by yuwenmemon** [comment]
@smelaa How are things going? When can we expect to take the PR out of draft?

**Comment by JmillsExpensify** [comment]
Curious for an update on Yuwen's comment from yesterday? Are we tracking to open up this PR for reviews?

**Comment by smelaa** [comment]
We are OOO till Monday due to a national holiday. The PR is almost ready, it just needs to be checked whether everything is in line with the design. I will do this first thing on Monday, is it okay?

**Comment by JmillsExpensify** [comment]
Yes, thanks!

**Comment by smelaa** [comment]
Hi, just wanted to post an update here: I am now waiting for [this PR](https://github.com/Expensify/App/pull/40020) to be approved as I need to merge it with mine. Once it's done my PR will be ready for review.

**Comment by yuwenmemon** [comment]
@ishpaul777 Since you have context from https://github.com/Expensify/App/pull/40020 would you be able to prioritize a review of https://github.com/Expensify/App/pull/40354?

**Comment by yuwenmemon** [comment]
Legend. Thanks mate!

**Comment by JmillsExpensify** [comment]
Nice, I must have checked it right before. Thank you!

**Comment by mallenexpensify** [comment]
@ishpaul777 can you propose regression test steps plz?
Also... how much are you due here? If this is due more than the standard $250, please provide reasoning.

**Comment by yuwenmemon** [comment]
Yeah, that's accurate @ishpaul777 :+1:

**Comment by mallenexpensify** [comment]
> Yeah, that's accurate @ishpaul777 👍

I'm assuming this is related to us *not* needing regression steps here cuz it'll be covered in testing steps as part of the design doc. 

@ishpaul777 , I [posted this in #expensify-open-source yesterday](https://expensify.slack.com/archives/C01GTK53T8Q/p1717451725980889?thread_ts=1712256409.152489&cid=C01GTK53T8Q)
> There have been questions about what constitutes a job being auto-increased to $500. These jobs are only the ones that have the High Priority label added to them (ie. issue with HIGH or CRITICAL in the title or project status/priority are not auto-increased to $500).

So the default amount here would be $250. if you believe compensation should be higher, follow the process [here](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit#bookmark=id.25bt9k50o02o)

**Comment by mallenexpensify** [comment]
Thanks for the link @ishpaul777 , for this instance, you are correct.  I [commented on that thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1717630819236859?thread_ts=1715190852.677769&cid=C02NK2DQWUX) to state this shouldn't be the practice for any future price updates. 
> In the future, when we have price changes or, if there are other instances where we're deciding what the price should be, we shouldn't always default to the created date. We have closed issues from when we paid $2k for a job, if we reopened one today, we'd want the default price to be $250.  Same goes for old issues where we haven't marked external yet, also for one's that needed reliable reproduction steps before making external.

**Comment by mallenexpensify** [comment]
@ishpaul777 can you please accept the job and reply here once you have? 
https://www.upwork.com/ab/applicants/1798501240605888788/job-details

**Comment by mallenexpensify** [comment]
Contributor+: @ishpaul777 paid $500 via Upwork.  

Thanks all!
