### ISSUE TITLE
[Mentions v2] Add new rule in ExpensiMarks for room mentions

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#39538]
Room mentions need a new html tag to work, which will be `<mention-report>`, we need to update our [ExpensiMarks](https://github.com/Expensify/expensify-common/blob/8dd2cb43ee29a369ccc459e6ad59bcdeaf579e6f/lib/ExpensiMark.js#L12) rules to find room mentions and replace them with the new tag.

Things to keep in mind:
- A message can have more than 1 room mention
- Room names consist of text connected with one or more hyphens and no spaces at all

Details and regex can be found [here](https://docs.google.com/document/d/1g_1xLGO29EV6hbOtiYqX53oof_gr8jbnbkSRPjuA4RI/edit#bookmark=id.fyscrrfotsl8) in the Mentions v2 design doc.

**Comment by robertKozik** [comment]
Hi! Please assign me to this one - PR will be ready EOD
