### ISSUE TITLE
Chat - New message icon not show when receive message when user not at LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39531]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**nhut.nguyenminh.it+1@gmail.com   nhut.nguyenminh.it+333@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: 2 account with conversation
0. Openn app in 2 accounts
1. Account A, please open another page ( Eg, Profile)
2. Account B, send message to A
3. Observe at account A

## Expected Result:
Show "new message" icon, notify for user about new message

## Actual Result:
New message icon not show when receiving message when the user is not at LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ad50c2ce-bebe-4b48-bf47-6cc5b2615c48

<img width="1920" alt="Bug6435066_1712023962443!Screenshot_2024-04-02_at_09 11 55" src="https://github.com/Expensify/App/assets/78819774/a456c91d-0f7c-4e89-86d8-f5c94c5e2f10">

<img width="1920" alt="Bug6435066_1712020645548!Screenshot_2024-04-02_at_08 15 47" src="https://github.com/Expensify/App/assets/78819774/10d20d6c-abd2-4908-a69d-c96486ea1566">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shawnborton** [comment]
Yeah I agree with that, the dot on the icon should match any red or green brick road dots found in the chats list.
