### ISSUE TITLE
[HOLD for payment 2024-05-22] [Violations - Pending Receipts] Add `Transaction.markAsCash` Action

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#39536]
Design Doc: https://docs.google.com/document/d/1zJqlTe_RajuBtfQYvbMx8PpXgA9CEnUGVyuqZihQ-ok/edit
Tracking GH: https://github.com/Expensify/Expensify/issues/372206

HOLD ON https://github.com/Expensify/Expensify/issues/385017

---

Similar to the `dismissViolation` action [described in the Dupe Detection doc](https://docs.google.com/document/d/1Ji-0e3ZTksIrvvbRxw1_0xdKwfyMk7FZbN3RveE6lE8/edit#heading=h.teuzer7jytf1), we'll optimistically update the `transactionViolations_*` Onyx key to include `dismissed` with the email of the user that dismissed it.

It'll also optimistically build and add a `DISMISSEDVIOLATION` report action, [similar to what we've done with previous report actions](https://github.com/Expensify/App/blob/defc91c6b8654e64d046128e9026b04c6047924f/src/libs/ReportUtils.ts#L3733-L3875) (more on the `DISMISSEDVIOLATION` report action [below](https://docs.google.com/document/d/1zJqlTe_RajuBtfQYvbMx8PpXgA9CEnUGVyuqZihQ-ok/edit#heading=h.zeynw27ddsog)).

It will then provide the onyx updates as part of the `optimisticData` in a corresponding API.write call to `DismissViolation`.
```
     optimisticData: [
         // Optimistically dismissing the violation
         {
             onyxMethod: Onyx.METHOD.MERGE,
             key: `ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS${transactionID}`,
             value: [{
                     "type": "violation",
                     "name": "rter",
                     "data": {
                         "dismissed": {
                             <email>: <timestamp>,
                         },
                     }
                 }
                 // Other existing violations
             ]
         },
         // Optimistically adding the system message indicating we dismissed the violation
         {
             onyxMethod: Onyx.METHOD.MERGE,
             key: `ONYXKEYS.COLLECTION.REPORT_ACTIONS${transactionThreadReportID}`,
             value: optimisticReportActions as ReportActions
         },
     ],


     failureData: [
         // Rolling back the dismissal of the violation
         {
             onyxMethod: Onyx.METHOD.MERGE,
             key: `ONYXKEYS.COLLECTION.TRANSACTION_VIOLATIONS${transactionID}`,
             value: [
                 // Previous other existing violations. (AKA removing the system message)
             ]
         },
         {
             onyxMethod: Onyx.METHOD.MERGE,
             key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
             value: failureReportActions as ReportActions,
         },

     ]
 }
 ```
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ed7a61e7c4bd3b3</li>
        <li>Upwork Job ID: 1789008757447643136</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by miljakljajic** [comment]
Holding

**Comment by smelaa** [comment]
Hi, I am Aleksandra Smela from Software Mansion, an expert agency, and I would like to work on this issue.

**Comment by grgia** [comment]
Not overdue, in progress

**Comment by JmillsExpensify** [comment]
Out of curiosity, where's the associated PR for this issue?

**Comment by yuwenmemon** [comment]
Has anyone started on this one? I can pick it up to work on if not. I should be able to get started later today.

**Comment by yuwenmemon** [comment]
Picking this one up!

**Comment by yuwenmemon** [comment]
@miljakljajic only thing needed here is paying @c3024 for their review!

**Comment by miljakljajic** [comment]
sorry for the hold up here - sent @c3024 a message in slack and an offer in Upwork. Will pay as soon as you approve!

**Comment by miljakljajic** [comment]
Paid!
