### ISSUE TITLE
[Mentions v2] Replace email and report name based mentions with ID-based mentions in the edit comment flow

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#39549]
We need to update the edit comment flow on the back-end to recognize email and report name based mentions and replace them with accountID and reportID based mentions before saving the reportAction in the database. This is covered in the design doc [here](https://docs.google.com/document/d/1g_1xLGO29EV6hbOtiYqX53oof_gr8jbnbkSRPjuA4RI/edit#heading=h.7hyj9alhb23q).

**Comment by puneetlath** [comment]
Not quite ready to add this yet. Will be very soon.

**Comment by puneetlath** [comment]
Not quite ready to implement. Still finishing up the addComment flow.

**Comment by puneetlath** [comment]
Starting on this now.

**Comment by puneetlath** [comment]
Unassigning myself since @rlinoz took this on. Looks like the Auth PR is done. Is there a web component as well?

**Comment by rlinoz** [comment]
Oh not really, I missed the deploy, we can close this.
