### ISSUE TITLE
[On Hold Payment 4/29] [$500] [Mentions v2] Parse <mention-report> when displaying reportAction

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#39545]
ReportActions that contains room mentions can have it in two different ways:
1. `<mention-report>#room-name</mention-report>` for optimistic mentions
2. `<mention-report reportID="1234"/>`

For the first case we want to display the #room-name, and if we can find the report in onyx based on the reportName and policyID we will make it clickable and make it redirect the user to the report, otherwise the tag won't be clickable.

For the second case we will look for the reportName using the reportID in the tag, display the report name and make the click event redirect the user to the report.

Details can be found [here](https://docs.google.com/document/d/1g_1xLGO29EV6hbOtiYqX53oof_gr8jbnbkSRPjuA4RI/edit#bookmark=id.i8lqohciqjin) in the Mentions v2 design doc.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ad216abc2940394</li>
        <li>Upwork Job ID: 1783160417124728832</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by war-in** [comment]
Hi, I'm Marcin from Software Mansion and I would like to work on this issue :)

**Comment by rlinoz** [comment]
Hey @war-in do you have an ETA of when the PR will be available for review?

**Comment by robertKozik** [comment]
Hi! We were in the internal review process, but the PR is already available for review 🚀

**Comment by thienlnam** [comment]
@rlinoz Do you want to review this?

**Comment by rlinoz** [comment]
Yeah, I can take this

**Comment by rlinoz** [comment]
Deployed to prod

**Comment by CortneyOfstad** [comment]
@Ollyws sent you an offer in Upwork since the job link was not posted originally. Let me know once you accept and I can make sure it gets paid ASAP on 4/29 👍 

Also, if you think any regression tests are needed, please make sure to have that completed before 4/29

**Comment by rlinoz** [comment]
Awaiting payment

**Comment by CortneyOfstad** [comment]
## Payment Summary

@Ollyws paid $500 via Upwork
