### ISSUE TITLE
[Mentions v2] Support accountID-based mentions in email notifications

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#39547]
We are migrating all user mentions to be accountID-based. We need to update our email notifications to support accountID-based mentions so that email notifications are properly rendered when the include user mentions. This is covered in the mentions v2 design doc [here](https://docs.google.com/document/d/1g_1xLGO29EV6hbOtiYqX53oof_gr8jbnbkSRPjuA4RI/edit#heading=h.ovwfgviqomry).

**Comment by rlinoz** [comment]
Will open the Web-E PR soon
