### ISSUE TITLE
[Violations - Pending Receipts] Create a ReportActionItemBasicMessage component for the DISMISSEDVIOLATION and MERGEDWITHCASHTRANSACTION actions

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#39540]
Design Doc: https://docs.google.com/document/d/1zJqlTe_RajuBtfQYvbMx8PpXgA9CEnUGVyuqZihQ-ok/edit
Tracking GH: https://github.com/Expensify/Expensify/issues/372206

HOLD ON https://github.com/Expensify/Expensify/issues/385026

---

We'll create a `ReportActionItemBasicMessage` component for the `DISMISSEDVIOLATION` and `MERGEDWITHCASHTRANSACTION` messages in [`renderItemContent`](https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/pages/home/report/ReportActionItem.tsx#L402-L627) in [`ReportActionItem.tsx`](https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/pages/home/report/ReportActionItem.tsx). This is so that we can properly render the system message in the front end.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb054d6db46b169e</li>
        <li>Upwork Job ID: 1783663567300743168</li>
        <li>Last Price Increase: 2024-04-26</li>
    </ul>
</details>

**Comment by muttmuure** [comment]
@yuwenmemon is there an order of priority for this? Is it going to be picked up in the next week or two?

**Comment by yuwenmemon** [comment]
Yeah it's held on https://github.com/Expensify/Expensify/issues/385026 which will probably only be ready in a week or two.

**Comment by yuwenmemon** [comment]
Handling this internally.

**Comment by JmillsExpensify** [comment]
PR up for re-review

**Comment by muttmuure** [comment]
Looks like we're good to close?

**Comment by yuwenmemon** [comment]
Yep!
