### ISSUE TITLE
[Mentions v2] Apply style to <mention-report> tag in the Composer

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#39542]
~HOLD https://github.com/Expensify/App/issues/39538~

When typing in the composer we need to be able to highlight room mentions, the same way we do for user mentions, so we need to update the `react-native-live-markdown` library to understand the `<mention-report>` tag.

After updating the library we need to use the change in App and style the mention accordingly. The style will be the same we use for user mentions.

Details can be found [here](https://docs.google.com/document/d/1g_1xLGO29EV6hbOtiYqX53oof_gr8jbnbkSRPjuA4RI/edit#bookmark=id.wjr4hgdbjz53) in the Mentions V2 design doc.

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by robertKozik** [comment]
Hi @rlinoz, this will be next in line for me. Can you assign me to this?

**Comment by rlinoz** [comment]
Hey @robertKozik what is the ETA on this one?

**Comment by dylanexpensify** [comment]
Wahooo!

**Comment by robertKozik** [comment]
A little delay 🫣 Here is PR inside `react-native-live-markdown` library https://github.com/Expensify/react-native-live-markdown/pull/310. Once merged I'll open PR inside E/App repo

**Comment by dylanexpensify** [comment]
Nice one!

**Comment by robertKozik** [comment]
Posted draft PR - currently working on recording videos, should be ready for review today

**Comment by rlinoz** [comment]
Deployed to prod

**Comment by dylanexpensify** [comment]
Wahoo! Waiting for regression period

**Comment by dylanexpensify** [comment]
Same

**Comment by c3024** [comment]
@dylanexpensify Regression period completed, right? PR deployed to prod 9 days ago. : 🤔

**Comment by rlinoz** [comment]
Friendly bump @dylanexpensify

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @c3024 $500

Please request or [apply here](https://www.upwork.com/jobs/~012d6860e24125f51a)!

**Comment by c3024** [comment]
@dylanexpensify thanks, applied. Here is my Upwork profile link as well for reference.
https://www.upwork.com/freelancers/~0105555e2f227dbf47

**Comment by dylanexpensify** [comment]
@c3024 sent offer!

**Comment by c3024** [comment]
@dylanexpensify accepted, thanks!

**Comment by dylanexpensify** [comment]
Done!
