### ISSUE TITLE
[Payment due 2024-03-15][$250] [Mentions v2] Handle the new action type ACTIONABLEREPORTMENTIONWHISPER

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#39546]
~HOLD https://github.com/Expensify/App/issues/39508~

When a user that is member of the policy tries to mention a room that doesn't exist we will send a whisper back asking if they want to create the room they just mentioned, this whisper type will be `ACTIONABLEREPORTMENTIONWHISPER `.

Resolving the whisper will call the `ResolveActionableReportMentionWhisper` command with a `reportActionID` and a `resolution`, which can be `yes` or `no`. The `reportActionID` is the one of the whisper.

If the whisper is resolved it should not be displayed to the user.

The whisper message will be:
- For a single room: "Heads up, `reportNames[0]` doesn't exist yet. Do you want to create it?"
- For two rooms: "Heads up, `reportNames[0]` and `reportNames[1]` don't exist yet. Do you want to create them?"
- For three or more: "Heads up, `reportNames[0]`, `reportNames[1]` and `reportNames[2]` don't exist yet. Do you want to create them?"

Details can be found [here](https://docs.google.com/document/d/1g_1xLGO29EV6hbOtiYqX53oof_gr8jbnbkSRPjuA4RI/edit#bookmark=id.9j56k4tc2i0k) in the Mentions V2 design doc.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e95bf52a9e340f42</li>
        <li>Upwork Job ID: 1789790273655398400</li>
        <li>Last Price Increase: 2024-05-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by robertKozik** [comment]
@rlinoz Do we have any specific ETA which we are aiming for with this one?

**Comment by rlinoz** [comment]
I didn't start the backend changes for this one yet, but ideally we would get this done before May 1st.

**Comment by rlinoz** [comment]
Hey @robertKozik do you think you can start on this? I started the backend already and as we were talking [here](https://expensify.slack.com/archives/C0671JDRKQW/p1714418347653299?thread_ts=1710631103.644249&cid=C0671JDRKQW) this is the order we want to get this deployed to avoid any trouble:

1. Deploy the front-end to support showing the whisper
2. Deploy the front-end to support resolving the whisper
3. Deploy the back-end to support sending the whisper and handling its resolution

It will be a little harder to test, but I think we can manage.

**Comment by rlinoz** [comment]
Also updated the action to be `ACTIONABLEREPORTMENTIONWHISPER`

**Comment by dubielzyk-expensify** [comment]
Looks like there's mocks in the doc, but happy to help. Is there anything needed from a design side on this? 😄

**Comment by rlinoz** [comment]
Oh I don't think so, it is just the new feature label I guess

**Comment by rlinoz** [comment]
Hey @kadiealexander this is in prod already, but I don't know how we create the Upwork job in new feature issues, can you help please?

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @fedirjh 
- [ ] Contributor+: $250 @ishpaul777

Upwork job is [here](https://www.upwork.com/ab/applicants/1789790273655398400/suggested).
