### ISSUE TITLE
HIGH: [API Reliability] Android: `GetMissingOnyxMessages` is not called in the background

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#39544]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:**
**Issue reported by:** @arosiclair 
**Slack conversation:** N/A

## Action Performed:

1. Add yourself as a workspace member
2. Kill the app
3. Remove yourself from the workspace (this creates some missed onyx updates)
5. Send yourself a DM
6. Push notification received
7. The app wakes up in the background 
8. A gap is detected and `ONYX_UPDATES_FROM_SERVER` gets set in Onyx to fill the gap

## Expected Result:
[The callback for `ONYX_UPDATES_FROM_SERVER`](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/libs/actions/OnyxUpdateManager.ts#L34) runs and calls the `GetMissingOnyxMessages` API in the background

## Actual Result:
The callback does NOT run until the app is reopened

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011415a3700cdef632</li>
        <li>Upwork Job ID: 1775605339418427392</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by arosiclair** [comment]
As mentioned, the root problem is that `Onyx.connect` callbacks do not seem to run in our background process for Android ([via headless js](https://reactnative.dev/docs/headless-js-android)) and instead run once the app is re-opened. That is blocking these two critical callbacks for filling update gaps in the background:

- [ONYX_UPDATES_FROM_SERVER](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/libs/actions/OnyxUpdateManager.ts#L34)
- [ONYX_UPDATES_LAST_UPDATE_ID_APPLIED_TO_CLIENT](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/libs/actions/OnyxUpdateManager.ts#L27)

I started discussing this [here](https://expensify.slack.com/archives/C03SDMF9YJ2/p1712602656160389).

One workaround is to optionally run the `ONYX_UPDATES_FROM_SERVER` code synchronously. However, that still leaves `ONYX_UPDATES_LAST_UPDATE_ID_APPLIED_TO_CLIENT` as an empty value. I'm not sure if there is a way to synchronously retrieve that value from Onyx atm.

**Comment by arosiclair** [comment]
Okay I've dug a bit further and found this part of [the docs](https://reactnative.dev/docs/headless-js-android) is crucial:

> You can do anything in your task such as network requests, timers and so on, as long as it doesn't touch UI. Once your task completes **(i.e. the promise is resolved)**, React Native will go into "paused" mode (unless there are other tasks running, or there is a foreground app).

Currently our `PushNotification.onReceived` callback does not return any promise so the background task stops immediately after the function finishes. So to fix this issue, we need to return a promise that resolves after we get `lastUpdateIDAppliedToClient` from Onyx and run `GetMissingOnyxMessages`. I drafted these changes and it fixed the issue! I'll clean it up and post a PR soon.

**Comment by arosiclair** [comment]
PR is prepped and testing well however there are some conflicts that are gonna come in from [#fireroom-2024-04-01-chats-do-not-load](https://expensify.enterprise.slack.com/archives/C06SCNUBB28). Once those are in, I'll fix them and post the PR for review. ETA is end of next week.

**Comment by arosiclair** [comment]
Out for review!

**Comment by quinthar** [comment]
Woohoo!

**Comment by quinthar** [comment]
Can we close this?

**Comment by quinthar** [comment]
Closing, reopen if you disagree.

**Comment by rushatgabhane** [comment]
@laurenreidexpensify could you please attach payment summary for C+ review - https://github.com/Expensify/App/pull/40022#issuecomment-2059285253

**Comment by rushatgabhane** [comment]
created a manual request here - https://staging.new.expensify.com/r/6707043287393435

**Comment by JmillsExpensify** [comment]
Re-opening for payment summary so I can pay this one out.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ review @rushatgabhane $500 requested in newdot

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
