### ISSUE TITLE
[$250] Focus mode -  A chat that was not on the chat list is displayed when changing to focus mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39558]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sarahhailu1268+new123232@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Settings
2. Click on Preference
3. Click on Priority mode
4. Select Focus
5. Return to chat list

## Expected Result:
There shouldn't be a new chat in the chat list that hasn't been there

## Actual Result:
New chat is displayed on chat list. The chat has (you) at the end

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/af2941e8-57da-420f-9c87-af5d95b9da2b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162b87158542554a9</li>
        <li>Upwork Job ID: 1777359358326181888</li>
        <li>Last Price Increase: 2024-04-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by thienlnam** [comment]
Ah yes that's correct

**Comment by adelekennedy** [comment]
made external
