### ISSUE TITLE
[HOLD for payment 2024-04-17] [$250] Incorrect font in Distance rates table

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39556]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712175981976759

## Action Performed:
Break down in numbered steps

Go to Workspace Settings > Distance rates and view the rates table

## Expected Result:
Describe what you think should've happened

The enabled/disabled text should match other parts of the workspace editor where we use our label font size (13px) and our textSupporting color

## Actual Result:
Describe what actually happened

Different font

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01195bf27980258b6e</li>
        <li>Upwork Job ID: 1775630709603196928</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by arjun-dureja** [comment]
I'm unable to repro in staging. I think it was fixed by #39557

**Comment by mountiny** [comment]
Correct, this one is done as the PR is linked, we are only holding this as open to pay @eh2077 for their testing and review.

**Comment by mountiny** [comment]
Updated with the hold for payment

**Comment by dylanexpensify** [comment]
@eh2077 sent invite to apply!

**Comment by dylanexpensify** [comment]
Done!
