### ISSUE TITLE
Group Chat - Second created group chat, doesn´t appear in the chats list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.59
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** bellicoignacio@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisite: Have an already created group chat.
1. Open the https://staging.new.expensify.com/
website.
2. Tap on the "+" button
3. Tap on "Start Chat"
4. Add at least two members to the new group chat
5. Tap on "Next"
6. Tap on "Start Group"
7. Tap on the arrow on the top left corner
8. Search the created chat on the chats list

## Expected Result:
User should be able to find the new created group chat on the chats list

## Actual Result:
Second created group chat is not displayed in the chats list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/82b887d6-b4ce-4670-9fa4-0bd7c9e66d3d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/2efb24f5-c838-423e-85fc-ff9a6548b07e

**Comment by lanitochka17** [comment]
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcochavezf** [comment]
Heading out in a few mins, post it [here](https://expensify.slack.com/archives/C03TQ48KC/p1712184287315839) to look for a volunteer

**Comment by aldo-expensify** [comment]
I don't know if this is really a bug, I see the same behaviour with DM chats. If you open the chat, say nothing, navigate away, the chat is removed from the LHN

**Comment by marcaaron** [comment]
This is expected behavior. Since nobody left a comment the report notification preferences are in a "hidden" state.
