### ISSUE TITLE
[HOLD for payment 2024-04-15] BNP - Unable to enter number on BNP unless the number 0.00 is erased first

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39599]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Manual.
3. Enter any number.

## Expected Result:
User should be able to enter number without erasing the number first on BNP.

## Actual Result:
User is unable to enter number on BNP unless the number 0.00 is erased first.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9c0b5ccd-3ca4-4c55-9501-bb24804201ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by iwiznia** [comment]
Going to revert the offending PR

**Comment by iwiznia** [comment]
Not a blocker anymore since we reverted the PR here https://github.com/Expensify/App/pull/39610

**Comment by iwiznia** [comment]
Just realized I removed the blocker without re-test, @kbecciv can you please retest this?
Once we confirm is good, we can remove the blocker

**Comment by m-natarajan** [comment]
@iwiznia Issue is fixed now.


https://github.com/Expensify/App/assets/38435837/48b4645a-4aa2-4c51-bf29-1c1426bce0d2

**Comment by iwiznia** [comment]
Thank you!
