### ISSUE TITLE
Taxes - System message for tax amount edit shows USD first, then changes to correct currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39605]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- The Collect workspace has taxes.
- The default workspace currency is not USD.
1. Go to staging.new.expensify.com
2. Go to Collect workspace chat.
3. Create a manual request with tax in non-USD currency.
4. Go to transaction thread.
5. Click Tax amount.
6. Edit the amount and save it.

## Expected Result:
The system message for tax amount edit will show the correct tax currency.

## Actual Result:
The system message for tax amount edit shows the tax in USD first, then changes to the correct currency.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a98dff0f-5a98-4bc9-9a16-95b9db5a86fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177cce5def94cedf6</li>
        <li>Upwork Job ID: 1775991223827992576</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by MonilBhavsar** [comment]
This can be demoted from deploy blocker. Not a major issue. Feel free to assign it to me. Happy to handle it.
We can handle as a regression from https://github.com/Expensify/App/pull/33927

**Comment by MonilBhavsar** [comment]
PR is merged! No further action required here
