### ISSUE TITLE
 Taxes - Missing tax rates in currency default list & app crashes when clicking on foreign rate

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39602]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2.Create a new (Collect) workspace.
3. Go to Collect workspace settings > More features
4. Toggle on Taxes.
5. Go to Taxes tab.
6. Click Settings > Workspace currency default.
7. Go to Foreign currency default.
8. Click on the selected default tax.

## Expected Result:
In Step 6 and 7, all other available taxes will show up in the list.
In Step 8, app will not crash.

## Actual Result:
In Step 6 and 7, only the selected default tax shows up in the list.
In Step 8, app crashes

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/87864ce3-7a11-4c6e-82fd-3201dcdbbf71

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by pecanoro** [comment]
Guys don't add proposals until the `Help Wanted` is applied. Since this a deploy blocker, I am looking for this to get fixed by whoever broke it

**Comment by pecanoro** [comment]
I am confident this deploy blocker is coming from https://github.com/Expensify/App/pull/33927

**Comment by MonilBhavsar** [comment]
Looking...

**Comment by teneeto** [comment]
Hi, I'm Eto from Callstack - expert contributor group - and I would like to take care of this issue.

**Comment by pecanoro** [comment]
@teneeto Any updates on this? It's a deploy blocker so we either need to fix it asap or revert the original PR

**Comment by MonilBhavsar** [comment]
latest from slack https://expensify.slack.com/archives/C03UK30EA1Z/p1712258281600879?thread_ts=1700633473.392829&cid=C03UK30EA1Z

**Comment by MonilBhavsar** [comment]
PR is up https://github.com/Expensify/App/pull/39646

**Comment by MonilBhavsar** [comment]
PR is merged. Requested CP

**Comment by MonilBhavsar** [comment]
Works well, no action required here 


https://github.com/Expensify/App/assets/32012005/c0c82803-271a-4e29-a963-68059d03a5bc

**Comment by pecanoro** [comment]
All done, closing!
