### ISSUE TITLE
[$500] Taxes - App crashes when changing tax rate to 0% on native apps and it shows 00 on web

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39600]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace that has taxes.
- One of the tax rates is 0%.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request with tax that is not 0%.
4. Go to transaction thread.
5. Click Tax.
6. Select the 0% tax rate.

## Expected Result:
App does not crash

## Actual Result:
App crashes. On web and desktop app, it shows 00 instead of crashing

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5bd71410-7e72-4da4-bfc6-25115767fab3

https://github.com/Expensify/App/assets/93399543/ef01879f-8d7f-436e-b2e8-64512be740dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01738457c70add314d</li>
        <li>Upwork Job ID: 1776310057649451008</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by MonilBhavsar** [comment]
Looking

**Comment by jasperhuangg** [comment]
PR merged ^ CPing now

**Comment by srikarparsi** [comment]
Hey @johncschuster, do you think you can help with paying @allroundexperts for reviewing this [PR](https://github.com/Expensify/App/pull/39638)?

**Comment by jasperhuangg** [comment]
CP request [here](https://expensify.slack.com/archives/C07J32337/p1712265058646039)

**Comment by jasperhuangg** [comment]
CP running

**Comment by jasperhuangg** [comment]
Confirmed the crash was fixed on staging, nice work @MonilBhavsar!

**Comment by MonilBhavsar** [comment]
Thanks Jasper! Removing blocker label

**Comment by johncschuster** [comment]
@allroundexperts I've invited you to the job, [here](https://www.upwork.com/nx/wm/offer/101751056). Can you accept that and ping me when you've done it so I can issue payment? Thank you!

**Comment by allroundexperts** [comment]
Thanks @johncschuster, but I get paid through NewDot. Can you please write a payment summary instead? Thanks!

**Comment by johncschuster** [comment]
# Payment Summary

C+ Reviewer - @allroundexperts - $500 to be paid via Manual Request

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts

**Comment by srikarparsi** [comment]
Is this good to close out @johncschuster?
