### ISSUE TITLE
[$250] Chat - Selected members disappear from search result after returning from confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39612]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat > Chat
3. Search for a term that will return two users
4. Click Add to group for these two users
5. Click Next without clearing the search field
6. Return to previous page

## Expected Result:
The chat page will display the selected members because the search field is not cleared

## Actual Result:
The chat page displays "No results found" instead of showing the selected members after returning from group confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f61914b1-5dec-4073-96a2-e6858ca1cb3b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013254e490a0ba9b6d</li>
        <li>Upwork Job ID: 1779812903951724544</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by muttmuure** [comment]
I think it makes sense to fix this since we're giving more focus to groups and search is an important part of that

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the proposal. Searching for the email should also return the selected user (same as in the split flow)


https://github.com/Expensify/App/assets/16493223/2d464046-3454-4fe2-b16a-c20765053479

**Comment by s77rt** [comment]
@Krishna2323 Try search for a user that does not exist (type random email)

**Comment by s77rt** [comment]
@abzokhattab Thanks for the proposal. Your RCA makes sense. It seems we may face more issues like that (missing option fields). Do you think we can reconstruct all the missing fields without saving them to draft? or find a better way to save selected participants?

**Comment by s77rt** [comment]
@tienifr Thanks for the proposal. Your RCA is correct. I like the approach of the solution. Can you please test if this works on deep link? e.g. when you arrive to the confirmation page refresh the page then try go back, this way the options list is constructed after the selection list

PS: When selecting users on the initial page select users from different cases e.g. from recent and a new random user (type their email), etc.

**Comment by s77rt** [comment]
@tienifr Thanks for checking that. Let's get this fixed

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/39612#issuecomment-2061893571)

**Comment by s77rt** [comment]
Not overdue. @neil-marcellini ^

**Comment by s77rt** [comment]
Not overdue. @tienifr got assigned recently

**Comment by muttmuure** [comment]
PR still in progress

**Comment by neil-marcellini** [comment]
I never got a chance to review the proposal, so before I review the PR I will do that.

**Comment by neil-marcellini** [comment]
> @tienifr Thanks for checking that. Let's get this fixed
> 
> 🎀 👀 🎀 C+ reviewed [Link to proposal](https://github.com/Expensify/App/issues/39612#issuecomment-2061893571)

I agree it's a good proposal. I'll review the PR now.

**Comment by s77rt** [comment]
PR made it to production 2 weeks ago

**Comment by muttmuure** [comment]
$250 for @tienifr for C+ 
$250 for @s77rt for C

**Comment by JmillsExpensify** [comment]
$250 approved for @tienifr
