### ISSUE TITLE
[HOLD for payment 2024-04-25] [$250] Taxes - Not here page shows up when clicking on tax rate with / symbol

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39614]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Collect workspace settings
3. Go to Taxes
4. Click Add rate
5. Create a tax rate with / symbol in the name
6. Click on the tax rate

## Expected Result:
Tax rate editor opens without issue

## Actual Result:
Not here page shows up when clicking on tax rate with / symbol

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4f68c2b6-75c6-4ccd-ac67-aceacca30a78

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b3c5959006e7d8f</li>
        <li>Upwork Job ID: 1776218862688116736</li>
        <li>Last Price Increase: 2024-04-05</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by twisterdotcom** [comment]
I recreated this. It's clearly to do with it affecting the URL yes.

**Comment by s77rt** [comment]
@gijoe0295 Thanks for the proposal. Your RCA is correct. The solution looks good to me 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/39614#issuecomment-2037457811)

**Comment by s77rt** [comment]
@stitesExpensify can you please review https://github.com/Expensify/App/issues/39614#issuecomment-2040795180

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/38208
- The offending PR has been commented on: https://github.com/Expensify/App/pull/38208#discussion_r1573025302
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No, not a bug that could easily resurface
