### ISSUE TITLE
BNP - Inconsistency in pointer position on android native and mWeb

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39611]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on 'FAB'
2. Click on 'Request money'

## Expected Result:
Pointer position should be consistent across platform. Pointer at end would good to clear zeros first before putting number.

## Actual Result:
Android pointer position is start and mWeb and Web pointer position is at end

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/5dac106d-af20-42f2-886d-37da0aec38a6)

https://github.com/Expensify/App/assets/93399543/bd66595b-db7f-4110-ba40-f992d1201831

https://github.com/Expensify/App/assets/93399543/a7060846-e69b-41d6-a430-a7e06ae86dfb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@mountiny issue is fixed now.


https://github.com/Expensify/App/assets/43996225/574831ea-de32-4de1-8ee4-dbc7c5bf73e3


https://github.com/Expensify/App/assets/43996225/2ebd936c-7f18-4ef5-8602-41f9e0295119

**Comment by mountiny** [comment]
Thanks!
