### ISSUE TITLE
[HOLD for Payment 2024-05-30][$500] mWeb - Chat - @ here highlight is removed if you also @phone number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39620]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4479302
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Enter @ and select here from suggestion box
4. Note here is highlighted
5. In next line, enter @ and select an email
6. Note here is highlighted after selecting an email id
7. Clear the message
8. Enter @ and select here from suggestion box
9. In next line, enter @ and type +1 and select a phone number from suggestion list

## Expected Result:
Here highlighted must not be removed after selecting an phone number

## Actual Result:
Here highlighted is removed after selecting an phone number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d85b7732-0612-4e68-b682-56199d743e54

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01875c053a0be9f2e8</li>
        <li>Upwork Job ID: 1776196507726311424</li>
        <li>Last Price Increase: 2024-05-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by adriancova** [comment]
I took a look at this one, not 100% sure if my findings are correct. But I don't think this should be solved in App project since it seems to be caused by internal logic of @expensify/react-native-live-markdown library 

specifically the parser is utilizing a version from 2 weeks ago for ExpensiMark (expensify-common)
https://github.com/Expensify/react-native-live-markdown/blob/main/parser/package.json

and there's a version from yesterday that included a fix for phone regex and is being used in this project, which could explain why there's a difference between mentions inside the input vs a comment.
https://github.com/Expensify/expensify-common/commit/13de5b0606662df33fa1392ad82cc11daadff52e

hope this helps

**Comment by laurenreidexpensify** [comment]
@mollfpr what do you think ^

**Comment by mollfpr** [comment]
@adriancova I can't verify your found, but if you're sure then you can write a proposal to update the package in `@expensify/react-native-live-markdown` using the latest library `expensify-common`.

**Comment by adriancova** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

attempting to tag a user via phone `+{number}{number}` is breaking the handling of special html elements such as <mention-user> and <mention-here>

### What is the root cause of that problem?

After debugging the react-native-live-markdown library I've noticed that the parseExpensiMarkToRanges fuction adds `@expensify.sms` whenever a phone Regex is found.

And afterwards there's a condition that checks that the original text remains the same after being parsed into ranges. since the condition is not met, we default to returning back an empty array of ranges resulting in vanilla text being shown in the input.

this logic comes from ExpensiMark for userMentions:
```
{
                name: 'userMentions',
                regex: new RegExp(`(@here|[a-zA-Z0-9.!$%&+=?^\`{|}-]?)(@${Constants.CONST.REG_EXP.EMAIL_PART}|@${Constants.CONST.REG_EXP.PHONE_PART})(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))`, 'gim'),
                replacement: (match, g1, g2) => {
                    if (!Str.isValidMention(match)) {
                        return match;
                    }
                    const phoneRegex = new RegExp(`^@${Constants.CONST.REG_EXP.PHONE_PART}$`);
                    return `${g1}<mention-user>${g2}${phoneRegex.test(g2) ? `@${Constants.CONST.SMS.DOMAIN}` : ''}</mention-user>`;
                },
            },
```

### What changes do you think we should make in order to solve the problem?

We can use patch-package to manually change the ExpensiMark being used inside of react-native-live-markdown library as it has already been done before. We just need to remove the check for phoneRegex that adds the `@expensify.sms` and instead keep the text as it is.

```
{
                // ...
                    if (!Str.isValidMention(match)) {
                        return match;
                    }
                    return `${g1}<mention-user>${g2}</mention-user>`;
                },
            },
```

### What alternative solutions did you explore? (Optional)

1- Another alternative could be to apply this change directly in the expensify-commons library, but I'm unsure if it would end up breaking some logic/functionality in another place.

**Comment by laurenreidexpensify** [comment]
@mollfpr ^^

**Comment by laurenreidexpensify** [comment]
@mollfpr bump for review thanks

**Comment by mollfpr** [comment]
Sorry for the delay 🙏

@adriancova I'm not too onboard patching the `expensify-common` inside the package. If we use the latest `expensify-common`, the issue will arise again.

**Comment by adriancova** [comment]
hey @mollfpr here's an alternative solution which I think you'll like, let me know if you need to modify my original proposal or this message, first time I'm re-proposing.

### What alternative solutions did you explore? (Optional)

2- Let's modify the `expensify-commons` library to add a `rawInputReplacement` method to userMentions.

This is the current logic for parseMarkdownToHTML inside of the react-native-live-markdown parser.

```
function parseMarkdownToHTML(markdown: string): string {
  const parser = ExpensiMark;
  const html = parser.replace(markdown, {
    shouldKeepRawInput: true,
  });
  return html as string;
}
```

The options object includes `shouldKeepRawInput: true` which translates to the ExpensiMark rules using the rawInputReplacement over the replacement method (if available).

so I suggest we add this method to the userMentions rule like this:

```
{
                name: 'userMentions',
                regex: new RegExp(`(@here|[a-zA-Z0-9.!$%&+=?^\`{|}-]?)(@${Constants.CONST.REG_EXP.EMAIL_PART}|@${Constants.CONST.REG_EXP.PHONE_PART})(?!((?:(?!<a).)+)?<\\/a>|[^<]*(<\\/pre>|<\\/code>))`, 'gim'),
                replacement: (match, g1, g2) => {
                    if (!Str.isValidMention(match)) {
                        return match;
                    }
                    const phoneRegex = new RegExp(`^@${Constants.CONST.REG_EXP.PHONE_PART}$`);
                    return `${g1}<mention-user>${g2}${phoneRegex.test(g2) ? `@${Constants.CONST.SMS.DOMAIN}` : ''}</mention-user>`;
                },
                rawInputReplacement: (match, g1, g2) => {
                    if (!Str.isValidMention(match)) {
                        return match;
                    }
                    return `${g1}<mention-user>${g2}</mention-user>`;
                },
            },
 ```
 
 This way the sms domain won't be added and the text content before and after parsing will remain the same, resulting on the ranges being passed back successfully (and therefore the mentions properly rendered).
 
 This proposal would require 2 prs. 1st one to add the rawInputReplacement method into the expensify-commons repo and 2nd to update the version of expensify-commons used inside of the react-native-live-markdown repo.

**Comment by laurenreidexpensify** [comment]
@mollfpr for review ^^

**Comment by mollfpr** [comment]
@adriancova The alternative proposal makes sense to me, but I need to test it by myself. Could you help me with setting up the `react-native-live-markdown` locally and make the changes apply to the library?

**Comment by adriancova** [comment]
@mollfpr of course, here you go:
https://github.com/adriancova/react-native-live-markdown

I updated the expensify-common library to now include the ExpensiMark change:
https://github.com/adriancova/expensify-common/commit/135816a1abddc69cb52e75ee66e1d1305d91239a

rebuilt the parser, and added a new test for phone number, we should be able to add whatever new tests necessary.

Let me know if I can help with anything else

**Comment by laurenreidexpensify** [comment]
@mollfpr bump thanks

**Comment by mollfpr** [comment]
Checking the lib now 👀

**Comment by laurenreidexpensify** [comment]
@mollfpr bump for update thanks

**Comment by mollfpr** [comment]
I think the [alternative proposal](https://github.com/Expensify/App/issues/39620#issuecomment-2064713852) looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by laurenreidexpensify** [comment]
@adriancova is there an ETA on a PR yet? Thanks

**Comment by adriancova** [comment]
Hey @laurenreidexpensify sorry I was out the past couple of days. I'll send the first pr later today.

**Comment by laurenreidexpensify** [comment]
bump @adriancova

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Couldn't find the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think the regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open a chat
2. Type mention "@here"
3. Verify it highlighted
4. Type mention a user with the phone number
5. Verify that the mention "@here" and the phone number is highlighted
6. 👍 or 👎 


@laurenreidexpensify I'll do manual request in NewDot, thank you!

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- C+ @mollfpr $500 will submit a manual request in newdot 
- Contributor @adriancova $500 paid in upwork

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr
