### ISSUE TITLE
[HOLD - EApp #20354] Start chat - No hover effect on Add to group button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Manual
3. Enter amount and proceed to contact list
4. Hover over split button
5. Go to FAB > Start chat > Chat
6. Hover over Add to group button

## Expected Result:
There will be hover effect on Add to group button

## Actual Result:
There is no hover effect on Add to group button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f2400f09-057d-43b3-b50c-74beb6a824ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment]
It should be held for https://github.com/Expensify/App/pull/38610

**Comment by alexpensify** [comment]
Thanks for flagging @nkdengineer. @rushatgabhane I see you are the C+ for the issue mentioned here. Do you agree with this hold? Thanks!

**Comment by alexpensify** [comment]
No update yet, waiting for confirmation if we should move this to Weekly and keep it on hold.

**Comment by alexpensify** [comment]
Still waiting for feedback here.

**Comment by rushatgabhane** [comment]
@alexpensify yes i think it's fine to hold here

**Comment by trjExpensify** [comment]
Why did this get put into #wave-collect? It's a bug in `Start Chat`.

**Comment by alexpensify** [comment]
My mistake @trjExpensify

**Comment by alexpensify** [comment]
Thank you for that update, I'm going to close this GH then.
