### ISSUE TITLE
Taxes - Currency in tax amount error message does not update after changing currency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39628]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace that has taxes.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Start manual request flow.
4. Enter amount and select a tax rate.
5. Click Tax amount.
6. Enter amount that exceeds the maximum allowed amount and save it.
7. Click on the currency.
8. Change to a different currency.

## Expected Result:
The currency in the error message will update to show the newly selected currency.

## Actual Result:
The currency in the error message still shows the previously selected currency.
It only updates after saving the invalid amount again.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/59a42ba0-a7a7-41b0-a8a9-6353c736e8e6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@stephanieelliott FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by stephanieelliott** [comment]
Hm, I'm not able to repro this. But it also seems pretty minor -- I'm not sure many people would even notice or care about the currency not refreshing. Gonna close as I don't think this is worth prioritizing
