### ISSUE TITLE
[Distance Rates] Default category selector shows empty list when all categories are disabled

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Navigate to `/settings/workspaces/<policyID>/categories`
2. Disable all categories
3. Navigate to `/settings/workspaces/<policyID>/distance-rates`
4. Select `Settings`
5. Press `Default category`
6. Note that you see an empty list

## Expected Result:
Default category option shouldn't show

## Actual Result:
Empty list is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/22219519/d92fd148-fe12-4654-9fd1-6a0527cab8ee

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8a57f3a4651f164</li>
        <li>Upwork Job ID: 1775970859700166656</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
@luacmartins The PR is merged. Should we close this one?

**Comment by luacmartins** [comment]
Yup, thanks for the ping!
