### ISSUE TITLE
Request - "." is incorrect for BRL (Reais) currency, should be "',"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39641]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to Request money > Manual > Change currency to BRL (Reais)
4. Input a value and attempt to insert a " , " as the decimal separator

## Expected Result:
User expects that the format should show as R$ 0,00 for BRL

## Actual Result:
Format is shown as R$ 0.00 for BRL which is incorrect for Brazils decimal system. User is unable to input a " , " as the decimal separator

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e1e2f534-3a88-4e74-b41c-d3c9835be2ab

<img width="1440" alt="Bug6438239_1712251717307!Currency_decimal_system_is_not_correct_for_BRL" src="https://github.com/Expensify/App/assets/78819774/038f2835-b612-479d-8fdc-cf7779b2b037">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
[Discussing ](https://expensify.slack.com/archives/C03U7DCU4/p1712262713599569)

**Comment by joekaufmanexpensify** [comment]
Confirmed this is not a bug. The decimal operator used is decided by language, not currency.
