### ISSUE TITLE
[$250] mWeb - Group - After creating group, members name under group avatar is not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4475700
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap start chat
3. Select few contacts and tap " Add to group"
4. Tap next & start group
5. Tap header

## Expected Result:
After creating group, members name under group avatar must be displayed

## Actual Result:
After creating group, members name under group avatar is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ffd3e482-4f07-4f9a-8cc1-9c9520d10919

![Bug6438339_1712256919044!Screenshot_2024-04-05-00-19-57-113_com android chrome-edit](https://github.com/Expensify/App/assets/78819774/22b9046f-d3e9-417a-9987-c8f50fa62c15)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108ce3dfb9a3851f5</li>
        <li>Upwork Job ID: 1777728073541976064</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by slafortune** [comment]
Able to recreate - vip-vsp it is!

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by s77rt** [comment]
Tested this against https://github.com/Expensify/App/pull/39757 and it's fixed. Let's hold on that PR cc @slafortune

**Comment by pac-guerreiro** [comment]
> Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

Nvm, thanks for the info @s77rt 😄
