### ISSUE TITLE
[payment DUE] [$250] Don't show GBR to AM/guides for managed customer employee invitations

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#39659]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @joekaufmanexpensify / @greg-schroeder 
**Slack conversation:** https://expensify.slack.com/archives/C03U7DCU4/p1709891758477419

## Action Performed:

1. Expensify account manager/guide is added to customer's workspace to assist them. 
2. Employee requests to join workspace. 

## Expected Result:
Account manager/guide should not have the workspace join request pinned to their LHN, since they are not a part of the company, and should not action it on their behalf. 

## Actual Result:
Account manager/guide has the workspace join request pinned to their LHN as GBR. 

<img width="1510" alt="image" src="https://github.com/Expensify/App/assets/54866469/ed8a560f-f908-4f15-8a76-892b82332d70">

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0c3b670623a55c2</li>
        <li>Upwork Job ID: 1775996355860926464</li>
        <li>Last Price Increase: 2024-04-11</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
Another proposal [here](https://expensify.slack.com/archives/C03U7DCU4/p1711465448874639?thread_ts=1711404193.218849&cid=C03U7DCU4) is to make an explicit AM/guide an explicit workspace role. Which could be the better long term solution

**Comment by twisterdotcom** [comment]
I am a huge fan of doing whatever needs to be done to fix this quickly and for now. This is just causing super high annoyance and noise for me and every single person on our Sales and Account Management team.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Account manager/guide has the workspace join request pinned to their LHN as GBR.

### What is the root cause of that problem?
We already have a method `isJoinRequestInAdminRoom` to check whether to show GBR [here](https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/libs/ReportUtils.ts#L2059), but currently don't prevent Expensify AM/guides from seeing the GBR from customer workspace's employee invitations.

### What changes do you think we should make in order to solve the problem?

In `isJoinRequestInAdminRoom` [here](https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/libs/ReportUtils.ts#L1151), if we check that the `currentUserPersonalDetails` belongs to an Expensify team member, and the policy is not created by an Expensify team member (meaning the policy belongs to the customer). Then we can early return `false` to avoid distractions to Expensify team member.
```
if (report.policyID) {
    const policy = getPolicy(report.policyID);
    if (!PolicyUtils.isExpensifyTeam(policy.owner) && PolicyUtils.isExpensifyTeam(currentUserPersonalDetails?.login ?? currentUserPersonalDetails?.displayName)) {
        return false;
    }
}
```
In [here](https://github.com/Expensify/App/blob/2995f2c79751d5096919eb98a26e0bd7b8533658/src/libs/SidebarUtils.ts#L390), we can also change to use the `isJoinRequestInAdminRoom` for consistency
```
if (ReportUtils.isJoinRequestInAdminRoom(report)) {
```

The earlier suggested proposal won't work because the LHN GBR logic is not there.

### What alternative solutions did you explore? (Optional)
NA

**Comment by Pujan92** [comment]
@joekaufmanexpensify @greg-schroeder I think this should be internal as we can't reproduce/test this because it requires AM/guide or expensify account.

**Comment by Pujan92** [comment]
At the moment I am facing an issue with inviting a user with the workspace join link and seems to be a regression from [here](https://github.com/Expensify/App/issues/38959#issuecomment-2039913163).

**Comment by Pujan92** [comment]
> But yeah, we'll need to login to test. Is there any test ID with expensify domain?

I don't think so but let @joekaufmanexpensify confirm.

**Comment by joekaufmanexpensify** [comment]
>I am a huge fan of doing whatever needs to be done to fix this quickly and for now. This is just causing super high annoyance and noise for me and every single person on our Sales and Account Management team.

@twisterdotcom Totally fair. I think the better long term solution is to create a new user role on workspaces for guides/AMs. Not sure how much additional work it is relative to just changing the behavior of these messages (though I assume it is some). If it's a lot more work, perhaps we could just change this now, and then open a follow up issue to explore the new user-role more holistically.

**Comment by joekaufmanexpensify** [comment]
>But yeah, we'll need to login to test. Is there any test ID with expensify domain?

@Pujan92 @ShridharGoel could you clarify what test ID is referring to here?

**Comment by joekaufmanexpensify** [comment]
Got it. Hmm, yeah I don't think we have a test expensify.com account that you could test with at this time.

**Comment by twisterdotcom** [comment]
Can we just push it and have somebody test on staging?

**Comment by Pujan92** [comment]
> Can we just push it and have somebody test on staging?

Yes, that is doable.

**Comment by Pujan92** [comment]
@ShridharGoel Your solution won't work here as we also need to consider `isJoinRequestInAdminRoom` inside the `requiresAttentionFromCurrentUser` for not showing the GBR which is correctly proposed by @nkdengineer. 
We can proceed with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/39659#issuecomment-2039752189) where they suggested applying the condition on both places with `isJoinRequestInAdminRoom` updation.

🎀👀🎀 C+ reviewed

**Comment by Pujan92** [comment]
Currently, the invite flow is broken which is the [regression](https://github.com/Expensify/App/issues/38959#issuecomment-2039913163) from @nkdengineer's [PR](https://github.com/Expensify/App/pull/39344). Could you plz check and fix that ASAP?

**Comment by Pujan92** [comment]
@ShridharGoel We are also having condition in `OptionRowLHN` which relies on `requiresAttentionFromCurrentUser`, if we can't validate for this too then it will still show the GBR.

https://github.com/Expensify/App/blob/455dce42bb99bb1c0987249de341d9319316bbfe/src/components/LHNOptionsList/OptionRowLHN.tsx#L56

**Comment by nkdengineer** [comment]
> Currently, the join workspace flow is broken which is the https://github.com/Expensify/App/issues/38959#issuecomment-2039913163 from @nkdengineer's https://github.com/Expensify/App/pull/39344. Could you plz check and fix that ASAP?

@Pujan92 Created a PR here to fix this https://github.com/Expensify/App/pull/39991.

**Comment by zanyrenney** [comment]
how is the PR review going @nkdengineer @Pujan92

**Comment by Pujan92** [comment]
Waiting for @marcochavezf to review the comment https://github.com/Expensify/App/issues/39659#issuecomment-2045651755

**Comment by marcochavezf** [comment]
Thanks for the review @Pujan92, assigning @nkdengineer

**Comment by nkdengineer** [comment]
@Pujan92 The PR is [here](https://github.com/Expensify/App/pull/40160).

**Comment by Pujan92** [comment]
@zanyrenney Seems automation is broken here, payment is due now.

**Comment by Pujan92** [comment]
Bump @zanyrenney :)

**Comment by zanyrenney** [comment]
Seems liks there might be an issue here - When I click the offer link in the GH issue, it seems like it doesn't exist.
![2024-05-14_12-24-09](https://github.com/Expensify/App/assets/56830058/18f4ee88-a44d-40ef-a916-313e3375a0a4)

**Comment by Pujan92** [comment]
@zanyrenney The Offer has already been accepted, Plz check this Upwork job [link](https://www.upwork.com/jobs/~01b0c3b670623a55c2)

**Comment by zanyrenney** [comment]
I know - It's paid for you @Pujan92 
<img width="418" alt="2024-05-16_14-15-49" src="https://github.com/Expensify/App/assets/56830058/978f56f1-cf64-419c-b738-40b6810b77e3">

I am waiting for @nkdengineer to accept.

**Comment by zanyrenney** [comment]
bump @nkdengineer

**Comment by nkdengineer** [comment]
@zanyrenney Invitation accepted! Sorry for the delay 🙏

**Comment by zanyrenney** [comment]
Dm @nkdengineer need him to accept offer.

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1716203310396389

**Comment by nkdengineer** [comment]
@zanyrenney Offer accepted!

**Comment by zanyrenney** [comment]
**payment summary**

paid @nkdengineer $250 via upwork 
paid @Pujan92 $250 via upwork
