### ISSUE TITLE
Track expense - Error occur when add user to TE, and these assign task another

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** [nhut.nguyenminh.it+2@gmail.com](mailto:nhut.nguyenminh.it+2@gmail.com)
/ [nhut.nguyenminh.it+333@gmail.com](mailto:nhut.nguyenminh.it+333@gmail.com)
/ [nhut.nguyenminh.it+10@gmail.com](mailto:nhut.nguyenminh.it+10@gmail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-condition: 3 Accounts available (we call A, B, C)
1. Open the app on A
2. Create Track expense
3. Go to self-conversation
4. Go to details of Track expense
5. Mention B and invite B to this Track expense
6. Switch to B account
7. Go to Track expense conversation
8. Assign a task for C

## Expected Result:
Error not occurred, and can create task normal.

## Actual Result:
The error "Unexpected error create task, please try again later." occurs when adding a user to Track expense, and these assign tasks to another, but user A still can see the assign created.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e2236efc-93c6-4ebe-97b2-bc25f4b4455a

<img width="1920" alt="Bug6437595_1712209835155!Screenshot_2024-04-04_at_12 39 12" src="https://github.com/Expensify/App/assets/115492554/a2fd76b3-bdeb-47cb-b1f9-5f351783ee6c">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
<img width="949" alt="image" src="https://github.com/Expensify/App/assets/36425901/6b9eb48c-a341-40a2-b392-9667fed5102b">

We should say something other than "room" in the prompt

**Comment by MitchExpensify** [comment]
@thienlnam should you be able to invite someone to a tracked expense at all?

**Comment by MitchExpensify** [comment]
I think the bug here, if any, is more to do with assiging a task to someone in a report they have not been given access to. That is expected - I shouldn't be able to assign someone a task in a private room if they are not a member of the private room
