### ISSUE TITLE
Workspace - Invited member becomes hidden if the email address contains "+"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39658]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with an expensifail account
2. Create a workspace
3. Invite a few members with "+" in the email address

## Expected Result:
I should be able to see the email address

## Actual Result:
Invited member becomes hidden if the email address contains "+"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/605147b3-8d65-4b6d-8ef7-f7aaabf64c18

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af9d008b533b0fbd</li>
        <li>Upwork Job ID: 1776352298075328512</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by puneetlath** [comment]
Seems like it's most likely a back-end issue. I'll investigate next week.

**Comment by puneetlath** [comment]
I'm not able to reproduce this. I'm going to close, but @lanitochka17 please reopen if you're still able to reproduce. 

<img width="469" alt="image" src="https://github.com/Expensify/App/assets/1371996/16e04502-5751-45ec-90da-90fa788c9594">
