### ISSUE TITLE
[Ideal Nav][$250] Wrong tooltip shown for account avatar tab

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39678]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jmills
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712260419807649

## Action Performed:
1. Open app
2. Hover on account avatar at the bottom

## Expected Result:
Tooltip should be "Settings"

## Actual Result:
Tooltip showing as "Profile"

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-04-04 at 10 35 45 PM](https://github.com/Expensify/App/assets/38435837/d4128d30-4a10-4d8e-b53f-771c48bc3f61)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01474575f0efe96faf</li>
        <li>Upwork Job ID: 1776193861064302592</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by laurenreidexpensify** [comment]
Confirmed on v1.4.60-8

![2024-04-05_11-17-22](https://github.com/Expensify/App/assets/62073721/bd2744e5-04d7-4629-b46c-0a7e77690a90)

**Comment by laurenreidexpensify** [comment]
confirming internally if this is a bug or intentional - https://expensify.slack.com/archives/C036QM0SLJK/p1712312493693709

**Comment by laurenreidexpensify** [comment]
Will get a PR up shortly

**Comment by laurenreidexpensify** [comment]
@grgia is gonna do the review for me, unassigning C+

**Comment by trjExpensify** [comment]
PR merged, nice!
