### ISSUE TITLE
[$250] Distance - Only map displayed in distance receipt if only one expense in report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39679]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
precondition: user a member of a workspace, there are no open reports
1. Open the app and log in
2. Tap the FAB > Request money > Distance
3. Enter the start and end points
4. Select the workspace chat and request money
5. Open the report
6. Tap the distance receipt thumbnail

## Expected Result:
The map and the expense details including amount, miles, start and end point, and date are displayed

## Actual Result:
Only a map is displayed in the receipt when only one transaction is in the report.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3a68ad12-0111-4ab9-80f0-f4bff6ed2625

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@robertjchen FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by Christinadobrzyn** [comment]
I don't think this is happening anymore. After reproducing the issue once, the distance receipt now shows the receipt details (see video)

https://github.com/Expensify/App/assets/51066321/14dc3266-e501-454d-b535-16d7886cda2b

Also to note: the distance receipt is different from the SmartScan receipt, is that expected? 

I'll ask QA to test again.

**Comment by mountiny** [comment]
I could reproduce in staging 
<img width="826" alt="image" src="https://github.com/Expensify/App/assets/36083550/1d79e63f-2089-4dc3-8fc4-c400a5e5f4a6">

**Comment by nkdengineer** [comment]
@mountiny This will be fixed here.

**Comment by mountiny** [comment]
@nkdengineer Nice, thanks I have linked the PR to this issue too, can you update the steps to also test for this?

**Comment by kavimuru** [comment]
@Christinadobrzyn The issue reproducible in 1.4.60-10

https://github.com/Expensify/App/assets/43996225/45026711-ef6a-4f1f-8ae9-60db399b0e31

**Comment by mountiny** [comment]
fix is being CPed

**Comment by mountiny** [comment]
<img width="1473" alt="image" src="https://github.com/Expensify/App/assets/36083550/31194e1a-44f6-4b55-8fee-4ee85ddf695f">

Fixed I think we can close as the PR was handled for another issue
