### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] IOU - RBR is present in LHN but no error msg in combined report when deleting paid IOU offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39689]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4476117
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User A and have no unsettled IOU.

1. Go to staging.new.expensify.com
2. [User A] Request money from User B.
3. [User A] Go offline.
4. [User B] Pay the request.
5. [User A] Delete the request while offline.
6. [User A] Go online.
7. [User A] Go to transaction thread (one report view).

## Expected Result:
The error "Unexpected error deleting the money request, please try again later" should be present in one transaction report view.

## Actual Result:
There is RBR for one transaction report in LHN, but there is no error in the report itself.
This issue happens when there is only one request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/60b740d3-c949-4693-bcb7-20b1a4201b18

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebfa7c151ee18ff6</li>
        <li>Upwork Job ID: 1776224622646538240</li>
        <li>Last Price Increase: 2024-04-12</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by izarutskaya** [comment]
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 

https://github.com/Expensify/App/assets/115492554/337c352e-d4ad-4b8c-a074-406a7deca616

**Comment by mountiny** [comment]
This is a specific and rare flow so I dont think we have to hold the deploy on this one.

This is related to the combined view cc @NikkiWines 

I think we can make this external

**Comment by alexpensify** [comment]
@abdulrahuman5196 when you get a chance, can you review the proposals here? Thanks!

**Comment by abdulrahuman5196** [comment]
Checking no2

**Comment by abdulrahuman5196** [comment]
On first glance, the proposal here https://github.com/Expensify/App/issues/39689#issuecomment-2040156570 makes sense. I will do further testing and comeback with updates

**Comment by alexpensify** [comment]
Thank you @abdulrahuman5196, keep us posted.

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@kaushiktd I tested your proposed changes


But it is adding some image frame above the error. I think its from OfflineFeedback, kindly take a look into it.


<img width="1510" alt="Screenshot 2024-04-13 at 1 07 07 AM" src="https://github.com/Expensify/App/assets/46707890/09c96244-ed18-4923-b3a0-e6f11bae7de5">




Code I used for reference

```diff
--- a/src/components/ReportActionItem/MoneyRequestView.tsx
+++ b/src/components/ReportActionItem/MoneyRequestView.tsx
@@ -255,15 +255,23 @@ function MoneyRequestView({
         [transactionAmount, isSettled, isCancelled, isPolicyExpenseChat, isEmptyMerchant, transactionDate, hasErrors, canUseViolations, hasViolations, translate, getViolationsForField],
     );
 
+    let errors = transaction?.errors ?? {};
+if (parentReportAction?.errors) {
+    errors = {
+        ...errors,
+        ...parentReportAction?.errors
+    }
+}
+
     return (
         <View style={[StyleUtils.getReportWelcomeContainerStyle(isSmallScreenWidth, true, shouldShowAnimatedBackground)]}>
             {shouldShowAnimatedBackground && <AnimatedEmptyStateBackground />}
             <View style={shouldShowAnimatedBackground && [StyleUtils.getReportWelcomeTopMarginStyle(isSmallScreenWidth, true)]}>
                 {/* eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing */}
-                {(showMapAsImage || hasReceipt) && (
+                {(showMapAsImage || hasReceipt) || errors && (
                     <OfflineWithFeedback
                         pendingAction={pendingAction}
-                        errors={transaction?.errors}
+                        errors={errors}
                         errorRowStyles={[styles.ml4]}
                         onClose={() => {
```

**Comment by kaushiktd** [comment]
@abdulrahuman5196 You need to enclose View component inside `OfflineWithFeedback` on below mentioned condition here,

```
src/components/ReportActionItem/MoneyRequestView.tsx#L275

{(showMapAsImage || hasReceipt) &&
 <View>
</View>
}
```

This will prevent rendering an empty image box on the report thread.

**Comment by abdulrahuman5196** [comment]
@kaushiktd 's proposal here https://github.com/Expensify/App/issues/39689#issuecomment-2040156570 looks good and works well. 

🎀 👀 🎀
C+ Reviewed

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, April 23, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by kaushiktd** [comment]
@abdulrahuman5196 any update so far?

**Comment by abdulrahuman5196** [comment]
Bump for @madmax330  to review.

**Comment by kaushiktd** [comment]
@abdulrahuman5196 PR submitted

**Comment by alexpensify** [comment]
Weekly Update: The PR is going through a recent round of reviews.

**Comment by alexpensify** [comment]
Weekly Update: The PR is under the last reviews

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment]
@madmax330 we need a review in this PR: https://github.com/Expensify/App/pull/40460#issuecomment-2135823497

@abdulrahuman5196 - I'm going to lean on engineering feedback here. 

Thanks!

**Comment by alexpensify** [comment]
@kaushiktd - you didn't get an offer since the automation failed here: https://github.com/Expensify/App/issues/39689#issuecomment-2152286560

I'll need to manually create a new request in Upwork before the payment due date. When it's ready, I'll reply here.

**Comment by kaushiktd** [comment]
Thank you @alexpensify. Earlier I was able to receive an offer on my Upwork from Melvin but it stopped for the last couple of months. Do you have any idea what can be an issue?

**Comment by alexpensify** [comment]
I don't know about a couple of months ago, the issue that I'm describing today is a recent one. Either way, it's on my radar and I'll deal with it manually. I'll have an update early next week because the payment date is 2024-06-13.

**Comment by alexpensify** [comment]
Ok, ready for the payment process in Upwork. @kaushiktd - I've created a new Upwork job, please accept here: 

https://www.upwork.com/jobs/~01bce135ee5dd897fc

Thanks!

**Comment by kaushiktd** [comment]
Offer accepted on Upwork @alexpensify

**Comment by alexpensify** [comment]
### Paid via Upwork! 

Payouts due: 2024-06-13

- [x] Contributor: $250 @kaushiktd 
- [x] Contributor+: $250 @abdulrahuman5196 

Upwork job is [here](https://www.upwork.com/jobs/~01ebfa7c151ee18ff6)
