### ISSUE TITLE
[Pay 4/29][$250] [Track Tax] Error on Amount and Merchant field after changing tax rate when scanning is ongoing

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39699]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has several tax rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a scan request and include a tax rate.
4. When scanning is in progress, go to transaction thread.
5. Click Tax rate and change to a different tax rate.

## Expected Result:
No error on Amount and Merchant field will show up after changing the tax rate.

## Actual Result:
Error on Amount and Merchant field shows up briefly after changing the tax rate when scnaning is ongoing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9b05f0c7-596e-4c6d-9366-50eb570af25f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d90b50207f85d2f</li>
        <li>Upwork Job ID: 1777350902764363776</li>
        <li>Last Price Increase: 2024-04-08</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by MonilBhavsar** [comment]
This is not a deploy blocker, as only error appears momentarily and not breaking anything. I'm taking a look if it is a quick fix...

**Comment by cubuspl42** [comment]
@tienifr Thanks for this explanation!

I approve [the proposal](https://github.com/Expensify/App/issues/39699#issuecomment-2043043755) by @tienifr 

C+ reviewed 🎀 👀 🎀

**Comment by lakchote** [comment]
@tienifr's proposal LGTM 👍

**Comment by mallenexpensify** [comment]
@ahmedGaber93 reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks. Please review the PR
- https://github.com/Expensify/App/pull/40229

**Comment by mallenexpensify** [comment]
Sorry, didn't realize [the PR](https://github.com/Expensify/App/pull/40229#issuecomment-2069789809) hit production yesterday,

**Comment by adelekennedy** [comment]
@mallenexpensify confirming you've already taken care of @cubuspl42 payment in the linked issue above?

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @tienifr (Upwork)

Upwork job is [here](https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/36975634).

**Comment by mallenexpensify** [comment]
@adelekennedy , thanks for double checking.  This was an edge case (and/or a mistake on my part), I've paid @cubuspl42 for this outside of this issue.  I checked to box above, 

@lakchote , @adelekennedy @tienifr do we want a regression test for this?

**Comment by lakchote** [comment]
> @lakchote , @adelekennedy @tienifr do we want a regression test for this?

I think a regression test can't hurt to prevent this from happening in the future and ensuring a smooth user experience.

**Comment by adelekennedy** [comment]
Then to close this out @tienifr will you suggest a regression test and I can create an issue for it?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment]
bump @tienifr for the test steps!
