### ISSUE TITLE
[Payment due] Android - Skeleton and arrow appears when login via concierge deep link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39698]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4472211&group_by=cases:section_id&group_order=asc&group_id=229066
**Issue reported by:** Applause - Internal Testing                                         

## Action Performed:
1. Navigate to https://staging.new.expensify.com/concierge
from external app
2. Sign-up with a new account when app opens

## Expected Result:
User should navigate to the concierge chat

## Actual Result:
Before Concierge page open skeleton and arrow appears on the center of the screen when login via concierge deep link. Also, when keyboard overlaps Welcome to Expensify modal

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/01d6ecbe-5c75-45f5-9390-041727d19127

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by kbecciv** [comment]
@dylanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
Browserstack was being funny for me, trying again today!

**Comment by dylanexpensify** [comment]
Unable to repro - @kbecciv can you confirm you can't repro on latest?

**Comment by dylanexpensify** [comment]
Bump @kbecciv 🙇‍♂️

**Comment by kbecciv** [comment]
Issue is no longer reproduced

https://github.com/Expensify/App/assets/93399543/74908b42-0950-4894-81b3-fc3179207697

**Comment by lanitochka17** [comment]
Issue is still reproducible 


https://github.com/Expensify/App/assets/78819774/78213f7b-f046-4398-93b8-ac756fe6c2d5

**Comment by dylanexpensify** [comment]
made external!

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Before Concierge page open skeleton and arrow appears on the center of the screen when login via concierge deep link. Also, when keyboard overlaps Welcome to Expensify modal

### What is the root cause of that problem?
The wrapper view [here](https://github.com/Expensify/App/blob/1b9e1ccd7e23c19b253a284fd39660a58ddfc281/src/pages/ConciergePage.tsx#L59) does not have proper style, so the HeaderView in that ConciergePage will cover the full screen and there's no space for the `ReportActionsSkeletonView`.

### What changes do you think we should make in order to solve the problem?

Add `styles.appContentHeader` [here](https://github.com/Expensify/App/blob/1b9e1ccd7e23c19b253a284fd39660a58ddfc281/src/pages/ConciergePage.tsx#L59)

### What alternative solutions did you explore? (Optional)
NA

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/39698#issuecomment-2205488693) from @nkdengineer looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment]
Yuwen to confirm!

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/39698#issuecomment-2216983658

**Comment by nkdengineer** [comment]
@yuwenmemon Friendly bump for assignment https://github.com/Expensify/App/issues/39698#issuecomment-2216983658

Thanks 🙇

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by dylanexpensify** [comment]
@nkdengineer can we get an update please?

**Comment by nkdengineer** [comment]
https://github.com/user-attachments/assets/35b55b29-2849-4a1a-8233-882ccf6b3cc1

@dylanexpensify this bug still reproduce, and PR is under reviewing

**Comment by sobitneupane** [comment]
The PR is being reviewed.

**Comment by sobitneupane** [comment]
@dylanexpensify PR deployed to production two weeks back. https://github.com/Expensify/App/pull/45460#issuecomment-2296963596

**Comment by nkdengineer** [comment]
@dylanexpensify Gentle bump for payment, TIA

**Comment by dylanexpensify** [comment]
Whoops - automation failed!

**Comment by dylanexpensify** [comment]
@nkdengineer apply [here](https://www.upwork.com/jobs/~021843270492378183001)! I sent invite too!

**Comment by dylanexpensify** [comment]
pending!

**Comment by nkdengineer** [comment]
@dylanexpensify I applied

**Comment by dylanexpensify** [comment]
@nkdengineer offer sent!

**Comment by nkdengineer** [comment]
@dylanexpensify I accepted it

**Comment by dylanexpensify** [comment]
Done!

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
