### ISSUE TITLE
[HOLD for payment 2024-04-15] [$125] Tax - App crashes when changing tax rate offline, options not clickable on web&console error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39691]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Found when executing PR:** https://github.com/Expensify/App/pull/33927
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: user is an employee of a collect policy, and tax is enabled OD
1. Open the app and log in as an employee
2. Open the workspace chat
3. Disable internet connection
4. Tap "+" > Request money > Manual
5. Enter the amount and tap next
6. Tap Show more and select a tax rate
7. Request money
8. Open the expense
9. Tap the tax and select a tax rate

## Expected Result:
The tax is displayed in the tax field, and the user can select a different one.

## Actual Result:
The app crashes after opening the tax rate and selecting a different one. The tax options are not responsive on the web, and there are console errors.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4906793a-3d72-45e2-8812-6c8c180bf319

https://github.com/Expensify/App/assets/115492554/a00a3da3-2830-4008-828f-32a62d3efc67

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bd787d14b4b4b3e</li>
        <li>Upwork Job ID: 1776216138504876032</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by mountiny** [comment]
I can help here

**Comment by mountiny** [comment]
@dukenv0307 can you please raise the PR promptly? Thank you!

**Comment by mountiny** [comment]
The fix is also being covered in this PR https://github.com/Expensify/App/pull/39707 I suggest $125 to @dukenv0307 for help identifying the issue

**Comment by MonilBhavsar** [comment]
This issue should be fixed!

**Comment by mountiny** [comment]
Awaiting payment @stephanieelliott $125 to @dukenv0307

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: $125 @dukenv0307 PAID via Upwork 
 - Contributor+: N/A
 
 Upwork job is here:  https://www.upwork.com/jobs/~013bd787d14b4b4b3e
