### ISSUE TITLE
deprecate card.isVirtual references

### ISSUE THREAD

**Issue by grgia** [Expensify/App#39692]
We can stop referencing card.isVirtual and instead do a check for card.nameValuePairs?.isVirtual 

BE deprecation issue -  https://github.com/Expensify/Expensify/issues/382554

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by grgia** [comment]
PR in review

**Comment by webbdays** [comment]
@grgia 
What are the pending things for this issue? I would like to work on this.

**Comment by grgia** [comment]
@SzymczakJ did you remove all references in the PR?

**Comment by SzymczakJ** [comment]
yep, double checked it now, everything is removed
