### ISSUE TITLE
Search - Created task not displayed in search results until page refreshed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4478317
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Open any chat
3. Create a task with a unique name
4. Click on the search icon
5. Search for the task

## Expected Result:
The task is displayed in the search results

## Actual Result:
The task is not displayed in the search results until the page is refreshed

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cb20c9f6-b092-46e4-a6f2-a699a5bfdebf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
I dont think this has to be a blocker as its a quite specific flow

I believe its coming from https://github.com/Expensify/App/pull/38207 cc @TMisiukiewicz can you have a look please

**Comment by TMisiukiewicz** [comment]
I already found what is causing the issue - the cached list is updated when a single reports updates, but it does not have a mechanism of creating a new option when a new item is created. I need some more time to figure out how to implement it and not downgrade the performance, going to continue working on that Monday morning

**Comment by TMisiukiewicz** [comment]
Opened a draft PR, however reassure test was failing - I'm looking into that before opening

**Comment by TMisiukiewicz** [comment]
Found one more related issue when requesting/sending money from non-existing account, gonna fix it with the same PR

**Comment by TMisiukiewicz** [comment]
@mountiny I just opened the PR - the issue I had with non-existing account seem to not be related to my recent changes. I was trying to figure out if invited accounts are displayed on the search (the answer is yes), but I have encountered a weird behavior. After requesting money from non-existing account, the report opens with an e-mail address visible. After getting a response from API it changes to "Hidden". After refreshing the app, the email is visible again. I tried to track which change caused it, and noticed on version 1.4.60 it still works fine, but it happens on 1.4.61. Is this a known issue?

**Comment by mountiny** [comment]
> . I tried to track which change caused it, and noticed on version 1.4.60 it still works fine, but it happens on 1.4.61. Is this a known issue?

I am not aware of this issue, could you report it in the open source channel please 🙏

**Comment by TMisiukiewicz** [comment]
@mountiny posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1712736509774009)

**Comment by JmillsExpensify** [comment]
What's the latest on this issue?

**Comment by TMisiukiewicz** [comment]
@JmillsExpensify it was fixed in #39811

**Comment by JmillsExpensify** [comment]
Ah perfect. So all that is left is a payment summary: $250 to @thesahindia for PR review and testing. I'm closing this issue as C+ is paid out via New Expensify. @thesahindia make sure to comment on whether a regression test is needed when you request payment. Thanks!

**Comment by laurenreidexpensify** [comment]
Payment Summary

C+ @thesahindia $250 please request in newdot 
Contributor @TMisiukiewicz agency worker, no payment required

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
