### ISSUE TITLE
[HOLD for payment 2024-04-25] [Performance] Use shrinkMode strict to decrease APK size and remove unused locales

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39700]
Coming from [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1712316043451949)  and [here](https://expensify.slack.com/archives/C05LX9D6E07/p1712316063728219) cc @hurali97 

### Problem
As part of the android build process, images that are included in the dependencies are also made part of our APK, which we don’t need. As a result, we see an increase in the APK size for the assets which are not relevant and required.

We have dependencies in the application which supports multiple locales and brings translations strings with them. Expensify only supports en  and es languages so there’s no point bringing in other translations strings from those dependencies. For example, libraries like google-play-services-core etc have multiple locales supported. This takes our resources.arsc file size to 3.4MB and with the solution below we can reduce it to 1MB.

### Solution
To fix this we can use shrinkMode=strict in our keep.xml and explicitly add what assets we want. It’s fairly simple to achieve this and it brings good gains. Below is the results that we achieve with this change:

Before:
APK size: 105.4 MB
Download size: 101.5 MB

After:
APK size: 103.1 MB
Download size: 99.3 MB

We achieve ~2.3 MB of reduction in the APK size and ~2.2 MB of reduction in Download size. Here’s the [PR](https://github.com/Expensify/App/pull/39592) with the implementation. We look forward to your feedback :thank-you-:

Additionally for the locale:

To fix this we can explicitly set en and es as the supported locales in resConfig in app/build.gradle . It’s rather straightforward to achieve this. Below is the result that we achieve with this change. We benchmark on the previous proposal’s output:

Before:
APK size: 103.1 MB
Download size: 99.3 MB

After:
APK size: 100.8 MB
Download size: 98.7 MB

We achieve ~2.3 MB of reduction in the APK size and ~0.6 MB of reduction in Download size. Here’s the [PR](https://github.com/Expensify/App/pull/39688) with the implementation. We look forward to your feedback :thank-you-:

**Comment by hurali97** [comment]
@mountiny  👋  Please assign this to me

**Comment by puneetlath** [comment]
Does anyone need to be paid here? Maybe @allroundexperts?

**Comment by puneetlath** [comment]
@allroundexperts bump on the question above.

**Comment by allroundexperts** [comment]
Sorry, Yes, my payment is pending here. Can you write a payment summary and close this? Thanks!

**Comment by puneetlath** [comment]
Payment Summary: 
- C+ - @allroundexperts - $250 - to be paid via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
