### ISSUE TITLE
[HOLD for payment July 19th] Implement italics HTML to markdown conversion

### ISSUE THREAD

**Issue by Jag96** [Expensify/App#3970]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This is one of the conversions from the [HTML to Markdown Tracking Issue](https://github.com/Expensify/Expensify.cash/issues/3047), and it will help us confirm the E.cash changes for [this issue](https://github.com/Expensify/Expensify.cash/issues/3790#issuecomment-877466629). cc @parasharrajat 

## Action Performed:
1. Copy and paste italics from an e.cash message into the compose box on web

## Expected Result:
The pasted text should be converted to the markdown text for italics

## Actual Result:
The pasted text is not styled

## Workaround:
Apply the markdown in the compose box after pasting

## Platform:
Where is this issue occurring?

 Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by parasharrajat** [comment]
All Good. I will take it from here. Thanks.

**Comment by Jag96** [comment]
Paid!
