### ISSUE TITLE
iOS - Login - Offline indicator briefly appears on the login page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Build 1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4477138
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app.
2. Kill the app and reopen it

## Expected Result:
The offline indicator should only appear on the login page when the user is experiencing network issues.

## Actual Result:
The offline indicator briefly appears on the login page, despite having a stable network connection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/987ebac4-ff41-43b1-a73c-301d3c8b9ae0

https://github.com/Expensify/App/assets/93399543/4ae90d97-4d82-4f2a-8cb1-99dcb525bb0f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@tienifr do you think the offline PR you're working on will solve this?

**Comment by ahmedGaber93** [comment]
@puneetlath This is a known issue https://github.com/react-native-netinfo/react-native-netinfo/issues/572.
We use `isInternetReachable` to determine offline [here](https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/libs/NetworkConnection.ts#L103), but the listener will get `isInternetReachable = null` for the first two times then after milliseconds return `isInternetReachable = true/false`.
If we can accept a workaround, I can add a workaround proposal to ignore null on the first 2 time or the first x second

**Comment by puneetlath** [comment]
Great, thanks!

**Comment by puneetlath** [comment]
Still on hold.

**Comment by puneetlath** [comment]
Asking for a re-test: https://expensify.slack.com/archives/C9YU7BX5M/p1714579679005269

**Comment by kavimuru** [comment]
Issue is fixed now. 

https://github.com/Expensify/App/assets/43996225/f9cb9781-8724-48ce-ab3e-15beeae0ce8f

**Comment by puneetlath** [comment]
Great, thanks! Closing.
