### ISSUE TITLE
Conversation - Jumps to the top when editing second message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39718]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nhut.nguyenminh.it+2@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
 Open the app
2. Go to any conversation (have a long message)
3. Edit this message

## Expected Result:
App keeps a position

## Actual Result:
Jumps to the top when editing second message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6e2fc513-7a21-4dfd-9117-2fd30873f52d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment]
Still cannot repro: 
![2024-04-15_17-34-05 (1)](https://github.com/Expensify/App/assets/56830058/dc57e1af-d1a8-43e5-98e7-ff662863f3a1)

Going to close this out.
