### ISSUE TITLE
[Awaiting Payment 15th April] Payment issue for E/App PR#39181

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39719]
Issue created to compensate the Contributor+ member for their work on https://github.com/Expensify/App/pull/39181
E/E issue linked to the PR - no internal issue.
Contributor+ member who reviewed the PR - @hungvu193 .

Wait 7 days after the PR is deployed to production before issuing payment in case there are regressions.

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Deployed to prod 3 hours ago. Updated the title!

**Comment by trjExpensify** [comment]
👋 @mountiny can you confirm the payout amount for this issue type? Thanks!

**Comment by mountiny** [comment]
it was a simple PR test, $250

**Comment by trjExpensify** [comment]
Cool, payment summary as follows: 

- $250 to @hungvu193 for the PR review

Offer sent!

**Comment by hungvu193** [comment]
> Cool, payment summary as follows:
> 
> * $250 to @hungvu193 for the PR review
> 
> Offer sent!

I've accepted! Thank you

**Comment by trjExpensify** [comment]
Paid!
