### ISSUE TITLE
[Awaiting Payment 29th April] [Wave Collect][QBO] Disabled toggle for Categories, Tags, and  Taxes accordingly depending on the accounting software connected

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#39724]
When the user connects to accounting software:

- optimistically clear all existing categories, tags and taxes
- prevent the user from turning off categories, tags and taxes features
- prevent the user from deleting categories, tags and taxes imported from connecting accounting software
- prevent the user from adding new categories, tags and taxes

**Comment by hayata-suenaga** [comment]
I'll work on this during this week

**Comment by hayata-suenaga** [comment]
Several PRs are needed to implement this. Removed the `Reviewing` and `Daily` labels.

**Comment by trjExpensify** [comment]
Both PRs linked to this issue are deployed! 🎉

**Comment by trjExpensify** [comment]
Added the bug label to get a BZ assigned.

**Comment by puneetlath** [comment]
Who needs paying here? Just @shubham1206agra for https://github.com/Expensify/App/pull/39874?

**Comment by trjExpensify** [comment]
Yep!

**Comment by puneetlath** [comment]
@shubham1206agra offer is here: https://www.upwork.com/nx/wm/offer/102114555

Ping me on this issue once you've accepted.

**Comment by puneetlath** [comment]
Ah cool, thanks for letting me know. I went ahead and paid out $500. Thanks everyone!
