### ISSUE TITLE
[Wave Collect] [Xero] [Import Flow] Create the Organization page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39728]
You need to build the screen for selecting the Xero organization to import (if the user has multiple ones), following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.1ed71y1fpoj9).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by alexpensify** [comment]
@lakchote - Can you please confirm who the `You` is here? Thanks!

**Comment by lakchote** [comment]
> @lakchote - Can you please confirm who the `You` is here? Thanks!

I've updated details in the issue's body. Thanks for the heads up!

**Comment by alexpensify** [comment]
Thank you!

**Comment by lakchote** [comment]
Double-checking with internal engineers, some might be interested to work on this.

**Comment by alexpensify** [comment]
@lakchote catching up from being OOO, any luck to recruit help? Thanks!

**Comment by mountiny** [comment]
PR in review

**Comment by alexpensify** [comment]
Awesome, thanks for the update @mountiny!

**Comment by alexpensify** [comment]
Weekly Update: Waiting for the PR to be merged to production

**Comment by trjExpensify** [comment]
This got taken care of in this PR, so shall we close this issue and consolidate on the import page issue for payments https://github.com/Expensify/App/pull/40984

**Comment by mountiny** [comment]
Yep, lets do that, closing in favour of https://github.com/Expensify/App/issues/39727
