### ISSUE TITLE
[HOLD for payment 2024-05-13] [Wave Collect] [Xero] [Import Flow] Create the main screen (XeroImportPage)

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39727]
You need to build the main screen for Xero which is called XeroImportPage, following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=kix.3xizmosher7q).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment]
Reviewing now!

**Comment by dylanexpensify** [comment]
Wahoo thanks @filip-solecki!

**Comment by dylanexpensify** [comment]
Same status

**Comment by mountiny** [comment]
Rushat will handle the C+ work here

**Comment by dylanexpensify** [comment]
Nice one!

**Comment by trjExpensify** [comment]
Deployed to prod two days ago.

**Comment by mountiny** [comment]
@rushatgabhane can you help with the payment summary here for Dylan please?

**Comment by rushatgabhane** [comment]
uno reverse? 😂

**Comment by trjExpensify** [comment]
Dylan, can you upload your Upwork profile please?

**Comment by mountiny** [comment]
I was being serious 🤠 you know the best whet should be paid for on this issue 😂

**Comment by rushatgabhane** [comment]
I think 500 would be great!

**Comment by rushatgabhane** [comment]
Actually wait, I'm asking for a flat price for all issues combined for @hungvu193 @mananjadhav and me.

**Comment by trjExpensify** [comment]
So with that, I think we can close this out right?

**Comment by rushatgabhane** [comment]
yes, good to close
