### ISSUE TITLE
[HOLD for payment 2024-05-10] [Wave Collect] [Xero] Build the Authorization flow

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39725]
You need to build the Xero authorization flow, following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.9zeu402cpvhf).

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by johncschuster** [comment]
@lakchote I'm not familiar with whether or not this can be built by an external contributor. Can you help me understand to whom I should triage this?

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by johncschuster** [comment]
@lakchote bump! Can I assign this one out to @SzymczakJ?

**Comment by lakchote** [comment]
> @lakchote bump! Can I assign this one out to @SzymczakJ?

Sorry @johncschuster I've just seen your message!  Yes, this can be built by an external contributor, you can assign the issue to @SzymczakJ. [Here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839) is the Slack discussion for context, thank you!

**Comment by lakchote** [comment]
Assigned @SzymczakJ as this PR is a critical one, since it's a requirement of the follow-up PRs for the different flows (Import, Export, Advanced). 

Thank you for choosing to work on this.

**Comment by johncschuster** [comment]
Thanks, @lakchote! I'll keep an eye on this daily.

**Comment by johncschuster** [comment]
@SzymczakJ can we get a status on this one?

**Comment by SzymczakJ** [comment]
@johncschuster me and @lakchote are trying to figure out why is 'ConnectPolicyToXero' api command not working. When we manage to debug it I'll put out a PR

**Comment by lakchote** [comment]
> @johncschuster me and @lakchote are trying to figure out why is 'ConnectPolicyToXero' api command not working. When we manage to debug it I'll put out a PR

Turns out it was a deploy problem ([discussion](https://expensify.slack.com/archives/C03TQ48KC/p1713268929923789)).

**Comment by johncschuster** [comment]
Bumping for Melvin. Looks like this one is being worked on above.

**Comment by mountiny** [comment]
PR merged

**Comment by lakchote** [comment]
It has been deployed to staging and production, closing the issue.

**Comment by lakchote** [comment]
> It has been deployed to staging and production, closing the issue.

I realised my mistake after, and asked for confirmation with my mentor. Reopening the issue, that `overdue` label messed with me!

**Comment by mananjadhav** [comment]
@johncschuster This is ready for payout for C+ review.

**Comment by mountiny** [comment]
This was a large PR and @mananjadhav helped to get this done urgently, I think we should pay them $500 for their thorough review @johncschuster

**Comment by mananjadhav** [comment]
Thanks @mountiny. Appreciate it. Quick question, this was deployed on production on May 01. Shouldn't it be ready for payout by now?

**Comment by mananjadhav** [comment]
Looks like we are at May 10 anyway. @johncschuster quick bump.

**Comment by johncschuster** [comment]
Payment summary has been updated (Thanks for the incredible work, @mananjadhav and @SzymczakJ!). Please request $500 in NewDot, @mananjadhav!

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav
