### ISSUE TITLE
[Awaiting payment May 14th] [Wave Collect] [Xero] [Import Flow] Create the ConnectionLayoutComponent

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39730]
You need to build the ConnectionLayoutComponent which will be reused across the Import flow, following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.78l4x5c96fry).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by kevinksullivan** [comment]
@lakchote should someone from SWM be assigned here, and do you need me assigned?

**Comment by lakchote** [comment]
> [@lakchote](https://github.com/lakchote) should someone from SWM be assigned here, and do you need me assigned?

Double-checking with internal engineers, some might be interested to work on this.

**Comment by kevinksullivan** [comment]
@lakchote 👋 just checking in on this.

**Comment by lakchote** [comment]
> [@lakchote](https://github.com/lakchote) 👋 just checking in on this.

Was done in this [PR](https://github.com/Expensify/App/pull/41377) by @hungvu193

**Comment by trjExpensify** [comment]
Deployed to prod two days ago.

**Comment by kevinksullivan** [comment]
Cool, pending payment next week

**Comment by trjExpensify** [comment]
Payments for the C+ guys on this will be handled centrally when we wrap the project, we can close this now the regression period is over.
