### ISSUE TITLE
[Awaiting Payment 14th May] [Wave Collect] [Xero] [Import Flow] Create the Taxes page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39734]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.j8rbv4xoabm7).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by trjExpensify** [comment]
Issue on hold for #39727, Melv. Chiiiil.

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this issue!

**Comment by trjExpensify** [comment]
Issue still in a line of dependencies!

**Comment by rushatgabhane** [comment]
I'm working on this

**Comment by rushatgabhane** [comment]
PR merged

**Comment by trjExpensify** [comment]
Deployed to production 2 days ago.
