### ISSUE TITLE
[HOLD for Payment 2024-05-29][Wave Collect] [Xero] [Import Flow] Create the Chart of Accounts page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39731]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.1c3zdo8shvug).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**EDIT**: You'll need to implement the latest design changes [here](https://github.com/Expensify/App/pull/41547), just like in QBO.

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by slafortune** [comment]
Still on hold

**Comment by slafortune** [comment]
pr merged

**Comment by lakchote** [comment]
> pr merged

Hmm, there's no PR for it it seems. Did you think about the QBO one?

**Comment by trjExpensify** [comment]
Making you guys aware of [this update](https://github.com/Expensify/App/pull/41547) coming with QBO. We should align here for Xero as well. That would give us this: 

![Image](https://github.com/Expensify/App/assets/16232057/005d27ca-b443-4002-9e09-f0a8a4f63cf9)

**Comment by trjExpensify** [comment]
Deployed to staging yesterday. Assigning @s77rt as he'll need to be paid for the C+ review of the linked PR once this hits production and the 7 day regression period passes.

**Comment by slafortune** [comment]
This went to production on May 22 - 
<img width="646" alt="image" src="https://github.com/Expensify/App/assets/11725910/119af713-befe-4ee2-97c4-686b89ee91f4">
That would make the payment due on May 29th - no automation - I'll update the GH title
I'll be on vacation until June 4th - so adding another BZ for payment

@s77rt will be due 500 via upworks - offer sent [here](https://www.upwork.com/nx/wm/offer/102442247)

**Comment by s77rt** [comment]
@slafortune Accepted! Please note the amount due here is $250

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

@s77rt $150 via Upwork C+ Role - offer sent [here](https://www.upwork.com/nx/wm/offer/102442247)
@SzymczakJ Contributor role is an expert contributor and not due payment here.

**Comment by laurenreidexpensify** [comment]
@s77rt I was on autopilot and paid $500 by mistake but requested a partial refund in Upwork for the overpayment - apols!

**Comment by laurenreidexpensify** [comment]
This is a new feature but doesn't require regression testing. Closing.

**Comment by s77rt** [comment]
@laurenreidexpensify Refunded! Thank you!
