### ISSUE TITLE
[HOLD #39735] [Wave Collect] [Xero] [Export Flow] Create the XeroPreferredExporterSelectPage

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39738]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.u9ibcrjup6n6).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by garrettmknight** [comment]
No update, awaiting SWM.

**Comment by lakchote** [comment]
Double-checking with internal engineers, some might be interested to work on this.

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/issues/39725

**Comment by lakchote** [comment]
Oops, @garrettmknight looks like I've create this issue twice. [Here](https://github.com/Expensify/App/issues/39742) is the link to the other PR, where an engineer is assigned to it.

Should we close the issue?

**Comment by garrettmknight** [comment]
Yep!
