### ISSUE TITLE
[HOLD for payment 2024-05-20] [Wave Collect] [Xero] [Import Flow] Create the Tracking Categories Page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39732]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.tfir0mo6t731).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by jliexpensify** [comment]
Hi @lakchote - would this need to go to `Internal` for an engineer to work on, or are you happy for Contributors to tackle it? Thanks!

**Comment by lakchote** [comment]
> Hi @lakchote - would this need to go to `Internal` for an engineer to work on, or are you happy for Contributors to tackle it? Thanks!

Hi Jason! I've updated detail in the issue's body. Thanks!

**Comment by jliexpensify** [comment]
Awesome, thanks Lucien - have left a message for SWM.

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this issue!

**Comment by jliexpensify** [comment]
Not overdue! Any updates @filip-solecki?

**Comment by filip-solecki** [comment]
I will be working on this today or tomorrow as I had to jump to new Onboarding flow

**Comment by mananjadhav** [comment]
I am working on the PR and I have some open questions [here](https://expensify.slack.com/archives/C036QM0SLJK/p1714589279564489?thread_ts=1713799302.291019&cid=C036QM0SLJK) and [here](https://expensify.slack.com/archives/C036QM0SLJK/p1714585862739199?thread_ts=1713799302.291019&cid=C036QM0SLJK) ?

**Comment by lakchote** [comment]
> I am working on the PR and I have some open questions [here](https://expensify.slack.com/archives/C036QM0SLJK/p1714589279564489?thread_ts=1713799302.291019&cid=C036QM0SLJK) and [here](https://expensify.slack.com/archives/C036QM0SLJK/p1714585862739199?thread_ts=1713799302.291019&cid=C036QM0SLJK) ?

Answered you on Slack [here](https://expensify.slack.com/archives/C036QM0SLJK/p1714625508724419?thread_ts=1713799302.291019&cid=C036QM0SLJK)

**Comment by trjExpensify** [comment]
Looks like the PR deployed to staging 9 hours ago. There shouldn't be a hold in the title of this issue, right? Removing that.

**Comment by lakchote** [comment]
> Looks like the PR deployed to staging 9 hours ago. There shouldn't be a hold in the title of this issue, right? Removing that.

Yes, you're right. I've explained why this was merged [here](https://github.com/Expensify/App/pull/41441#issuecomment-2099942881).

**Comment by jliexpensify** [comment]
@lakchote can I confirm that no payment is needed here?

- @filip-solecki is from an agency
- I see @fedirjh assigned to the PR but I don't see a review
- @mananjadhav mentioned in a previous GH that this project is being billed all together

Is that correct?

**Comment by lakchote** [comment]
> @lakchote can I confirm that no payment is needed here?
> 
> * @filip-solecki is from an agency
> * I see @fedirjh assigned to the PR but I don't see a review
> * @mananjadhav mentioned in a previous GH that this project is being billed all together
> 
> Is that correct?

Exactly, no payment needed here for @filip-solecki and @fedirjh.

As Filip was OOO, Manan took the lead on it to finish it in time.
For Fedirjh, no review was done.

I'm going to assign @mananjadhav for this issue, to reflect that, thanks!

**Comment by jliexpensify** [comment]
Ok great, thanks! In that case - I think @mananjadhav is requesting one payment for the entirety of this project, is that correct?

Let me know if you need a Payment Summary - otherwise I'll close this out when I get online tomorrow.

**Comment by jliexpensify** [comment]
I believe Manan is including this as part of a larger invoice, so I'm going to close this out. There was no Upworks job.
