### ISSUE TITLE
[Wave Collect] [Xero] [Export Flow] Create the XeroPurchaseBillDateConfigurationPage

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39739]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.u9ibcrjup6n6).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by adelekennedy** [comment]
@lakchote this can be built by external contributors?

**Comment by lakchote** [comment]
> @lakchote this can be built by external contributors? The instructions are very short in the SO - I'm assuming that this can be built by external contributors and I'll manage payment?

Yes, this will be worked on by SWM engineers. I've added details to the issue's body. Thanks!

**Comment by adelekennedy** [comment]
still on hold!

**Comment by lakchote** [comment]
Double-checking with internal engineers, some might be interested to work on this.

**Comment by adelekennedy** [comment]
@lakchote any takers or are we still on hold?

**Comment by lakchote** [comment]
> @lakchote any takers or are we still on hold?

Yes, we were on hold for https://github.com/Expensify/App/issues/39725 to be merged.

It was merged yesterday. Technically we are able to work on this now.

I'm going to focus today on [fixing the remaining bugs](https://expensify.slack.com/archives/C01GTK53T8Q/p1714468527496189?thread_ts=1714119216.357459&cid=C01GTK53T8Q) for the Xero authorization flow before working on it.

**Comment by lakchote** [comment]
Actually @adelekennedy, it's a duplicate of https://github.com/Expensify/App/issues/39743, should we close the issue?

**Comment by adelekennedy** [comment]
Yeah let's close this one
