### ISSUE TITLE
[HOLD #39725] [Wave Collect] [Xero] [Export Flow] Create the XeroPreferredExporterConfigurationPage

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39736]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.2f6mcdaoxbsr).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by anmurali** [comment]
Not overdue, assigned to SWM engineers yesterday.

**Comment by anmurali** [comment]
https://github.com/Expensify/App/issues/39725 has just been merged today, so we can start working on this now.

**Comment by lakchote** [comment]
It's actually a duplicate of https://github.com/Expensify/App/issues/39742, should we close it?

**Comment by trjExpensify** [comment]
Yep, let's close it!
