### ISSUE TITLE
[$250] [Awaiting Payment 14th May] [Wave Collect] [Xero] [Import Flow] Create the Customers page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39733]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.y3ohacu9junw).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a5564502643da83</li>
        <li>Upwork Job ID: 1790330441151033344</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
As is stated in the Xero authorization flow needs to be complete first.

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this issue!

**Comment by zanyrenney** [comment]
Woo great @filip-solecki how are you getting on with this one?

**Comment by hungvu193** [comment]
I can take this over as discussion here: https://expensify.slack.com/archives/C036QM0SLJK/p1714382043481879?thread_ts=1713799302.291019&cid=C036QM0SLJK

Here's the draft PR:
https://github.com/Expensify/App/pull/41377

**Comment by hungvu193** [comment]
PR is merged.

**Comment by trjExpensify** [comment]
Deployed to production 2 days ago.

**Comment by hungvu193** [comment]
Hey @zanyrenney, Xero project will be paid as flat price (when it's done), so no payment needed here
cc @trjExpensify

**Comment by zanyrenney** [comment]
Nice, thanks so much @hungvu193 

 @trjExpensify how come you added the "awaiting payment [due date] to the title?

**Comment by trjExpensify** [comment]
Automation would usually do that, but it failed in this instance. The awaiting payment date still tells us when the regression period ends, and when we should close out this issue.
