### ISSUE TITLE
[HOLD for payment 2024-05-20] [Wave Collect] [Xero] [Export Flow] Create the main XeroExportConfigurationPage

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39735]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.2f6mcdaoxbsr).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by lakchote** [comment]
Double-checking with internal engineers, some might be interested to work on this.

@kadiealexander why did you unassign yourself?

**Comment by rushatgabhane** [comment]
I'm working on this

**Comment by lakchote** [comment]
Assigning you @trjExpensify as kadie unassigned herself?

**Comment by lakchote** [comment]
> Assigning you [@trjExpensify](https://github.com/trjExpensify) as @kadiealexander  unassigned herself?

**Comment by trjExpensify** [comment]
Lol, all good. I'll be your BZ man!

**Comment by trjExpensify** [comment]
Deployed to staging 9 hours ago

**Comment by trjExpensify** [comment]
Regression period over, payment and regression tests for the new feature will be handled centrally. Closing!
