### ISSUE TITLE
[$250] Threads - Hmm... it's not here page is shown when using the link of a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39737]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife+adf41@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Start a chat/Go to any chat
2. Send a message
3. Write click on the message body and click on copy ink
4. Create a thread on the message sent
5. Paste the Link copied on the thread created
6. Click on the link pasted
Notice that when clicking the link it takes you back to the Parent Conversation highlighting the parent message
7. Now go to the same thread, right-click on the Parent message that is in the thread, and Copy link
8. Paste the copied link to the composer and send it
9. Click on the link pasted. Notice that Hmm... it's not here page is shown
Note: Using the link of the Parent message that is in the thread anywhere results in Hmm... it's not here page, being displayed

## Expected Result:
Able to use the link of the Parent message that is in the thread

## Actual Result:
Using the link of the Parent message, that is in the thread, anywhere results in Hmm... it's not here page, being displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/92445a5b-fd59-49fe-8064-9d8e159d7aa1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100f8db9a0c05cca8</li>
        <li>Upwork Job ID: 1779873465345101824</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Threads - Hmm... it's not here page is shown when using the link of a message
### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L419), the ```reportID``` is point to the current thread report ID, not a parent reportID, that leads to the report action link is not correct, so the "It's not here" is displayed in this case.
### What changes do you think we should make in order to solve the problem?
- We can update [this](https://github.com/Expensify/App/blob/f1502291a14d4e15e04249b241109f146bdb512f/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L419) to:
```
          const report = ReportUtils.getReport(reportID);
            const parentReportActionID = report.parentReportActionID
            let targetReportID = reportID
            if(parentReportActionID){
                targetReportID = report.parentReportID
            }
            Environment.getEnvironmentURL().then((environmentURL) => {
                const reportActionID = reportAction?.reportActionID;
                Clipboard.setString(`${environmentURL}/r/${reportID}/${reportActionID}`);
            });
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by muttmuure** [comment]
Handling tomorrow

**Comment by FitseTLT** [comment]
This is [dupe](https://github.com/Expensify/App/issues/36057)

**Comment by nkdengineer** [comment]
@muttmuure I do not think it is a dupe of https://github.com/Expensify/App/issues/36057 because currently, I cannot reproduce this [bug](https://github.com/Expensify/App/issues/36057)

**Comment by FitseTLT** [comment]
> @muttmuure I do not think it is a dupe of #36057 because currently, I cannot reproduce that [bug](https://github.com/Expensify/App/issues/36057)

If you can't reproduce that bug then you can't reproduce this one. Both are the same issues and hence reproducible.

**Comment by nkdengineer** [comment]
I can reproduce this one in staging. Please correct me if I miss any step:

https://github.com/Expensify/App/assets/161821005/ba1bc859-0f27-42dd-b4d8-e7c484cdda86

**Comment by FitseTLT** [comment]
@nkdengineer It is the `Actual Result` that is confusing you, it is because of the time difference between the creation of the two issues but the expected behaviour is same for both; the parent message highlighted on the current thread same as comment linking behaves in all other cases.

**Comment by nkdengineer** [comment]
@FitseTLT Thanks for your information
