### ISSUE TITLE
[Wave Collect] [Xero] [Export Flow] Create the XeroBankAccountConfigurationPage

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39741]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.u9ibcrjup6n6).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by bfitzexpensify** [comment]
Still held.

**Comment by lakchote** [comment]
Double-checking with internal engineers, some might be interested to work on this.

**Comment by bfitzexpensify** [comment]
Still held.

**Comment by lakchote** [comment]
Will be done by @mananjadhav

**Comment by mananjadhav** [comment]
Started on this, PR will be ready by tomorrow.

**Comment by lakchote** [comment]
Actually, this is a duplicate of https://github.com/Expensify/App/issues/39745, closing this issue.
