### ISSUE TITLE
[Wave Collect] [Xero] [Advanced] Create the Purchase Bill Status Selector Page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39748]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.31z6szcoxxeq).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114d834a9c20463ee</li>
        <li>Upwork Job ID: 1777087957833936896</li>
        <li>Last Price Increase: 2024-04-07</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment]
Checking on in #bug-zero https://expensify.slack.com/archives/C01SKUP7QR0/p1712525687667159
Bumping to daily cuz it's #wave-collect and Release 1.  

@jjcoffee would you be interested in building this?

**Comment by jjcoffee** [comment]
@mallenexpensify In principle yes, but I have requested access to [the doc](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.31z6szcoxxeq) so I can see the full scope.

**Comment by mallenexpensify** [comment]
@jjcoffee , hold for a moment. I think @lakchote is checking with some agency engineers who might be working on this.

**Comment by lakchote** [comment]
Yes, agency engineers will work on this.

I've put this as a weekly first, since <ins>we won't be able to work on this until the [Xero authorization flow](https://github.com/Expensify/App/issues/39725) is done</ins>. 

It entails NewDot, Web-E, and IS changes (see DD details [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=kix.avhl99i2qwh0)). 

Once this whole block is done, we'll be able to make progress here.

**Comment by mallenexpensify** [comment]
Thanks @lakchote , going to leave 'as is' ,  just avoid adding `External` or else `Help Wanted` will get added and the job with _open up_ to contributors

**Comment by lakchote** [comment]
Unassigning you @jjcoffee as this will be handled by internal or SWM engineers.

**Comment by mallenexpensify** [comment]
Still holding

**Comment by rushatgabhane** [comment]
I'm working on this

**Comment by trjExpensify** [comment]
Draft PR is up.

**Comment by lakchote** [comment]
Assigning @mananjadhav as he'll need to be paid for the C+ review of the linked PR once this hits production and the 7 day regression period passes.

**Comment by lakchote** [comment]
Assigning @pecanoro as she has helped with reviewing the PR and providing translations.

**Comment by rushatgabhane** [comment]
Xero issues are paid "centrally". We'll get a flat fee after all Xero related issues are closed. 
No per issue pay required here.

**Comment by pecanoro** [comment]
@rushatgabhane Including the C+?

**Comment by rushatgabhane** [comment]
@pecanoro yes - @mananjadhav @hungvu193 and me
