### ISSUE TITLE
[Wave Collect] [Xero] [Export Flow] Create the Purchase bill date select page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39743]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.u04wbyypbbtz).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by lschurr** [comment]
Heya @lakchote - Should this be open externally for contributors or is there someone internally working on this?

**Comment by lschurr** [comment]
SWM will be working on this: https://expensify.slack.com/archives/C036QM0SLJK/p1712343689924329

**Comment by lschurr** [comment]
This is on hold.

**Comment by lakchote** [comment]
Double-checking with internal engineers, some might be interested to work on this.

**Comment by lschurr** [comment]
Any update here @lakchote? Still on hold?

**Comment by lakchote** [comment]
> Any update here @lakchote? Still on hold?

Yes, we were on hold for https://github.com/Expensify/App/issues/39725 to be merged.

It was merged yesterday. Technically we are able to work on this now.

I'm going to focus today on [fixing the remaining bugs](https://expensify.slack.com/archives/C01GTK53T8Q/p1714468527496189?thread_ts=1714119216.357459&cid=C01GTK53T8Q) for the Xero authorization flow before working on it.

**Comment by trjExpensify** [comment]
Merged into the Xero feature branch

**Comment by lakchote** [comment]
Assigning @rushatgabhane  as he'll need to be paid for the C+ review of the linked PR once this hits production and the 7 day regression period passes.

**Comment by trjExpensify** [comment]
Aren't we handling that centrally when wrapping up the project? I agree we should keep this open for the regression period before we close it out though.

**Comment by trjExpensify** [comment]
Closing, on prod.
