### ISSUE TITLE
[Wave Collect] [Xero] [Export Flow] Create the Bank account select page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39745]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.11b6laq66dmk).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by greg-schroeder** [comment]
Is this gonna be `Internal` @lakchote?

**Comment by lakchote** [comment]
> Is this gonna be `Internal` @lakchote?

Hi Greg - this is going to be handled externally by SWM. I've added details to the issue's body. Thanks!

**Comment by greg-schroeder** [comment]
Once you know who is going to work on it, let me know so I can assign them and make sure there are updates on the linked POR

**Comment by lakchote** [comment]
Double-checking with internal engineers, some might be interested to work on this.

**Comment by greg-schroeder** [comment]
Seems like this is still held, not overdue

**Comment by lakchote** [comment]
Yes, we were on hold for https://github.com/Expensify/App/issues/39725 to be merged.

It was merged yesterday. Technically we are able to work on this now.

I'm going to focus today on [fixing the remaining bugs](https://expensify.slack.com/archives/C01GTK53T8Q/p1714468527496189?thread_ts=1714119216.357459&cid=C01GTK53T8Q) for the Xero authorization flow before working on it.

**Comment by mananjadhav** [comment]
I will be picking this up.

**Comment by greg-schroeder** [comment]
Thanks @mananjadhav!

**Comment by mananjadhav** [comment]
The draft PR will be posted within 2 hours.

**Comment by mananjadhav** [comment]
@lakchote I added the PR for Bank Account Select. I had some issues with the commit history. Hence I copied all the changes in one commit.

**Comment by lakchote** [comment]
> Hey 👋 , Can i be assigned here for PR review #39745

Hey Ishpaul, I've added you.

**Comment by trjExpensify** [comment]
Deployed to staging yesterday!

**Comment by lakchote** [comment]
Assigning @pecanoro as she has helped with reviewing the PR and providing translations.

**Comment by greg-schroeder** [comment]
Awaiting deploy from staging -> prod

**Comment by mananjadhav** [comment]
We can close this one. This has been deployed to production and the payout will be a flat fee.

**Comment by trjExpensify** [comment]
Yep, agreed. Closing!

**Comment by trjExpensify** [comment]
Mind linking the PR?

**Comment by trjExpensify** [comment]
Got it. Cool, offer sent. 

$250 to @ishpaul777 for the C+ review

**Comment by trjExpensify** [comment]
Paid.
