### ISSUE TITLE
 Workspace - Show error when user accesses workspace url after inviting them

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39754]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nhut.nguyenminh.it+333@gmail.com nhut.nguyenminh.it+333@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open app
2. Go to workspace conversation
3. Invited a new user to Workspace
4. Give new user a workspace URL
5. A new user try to access this URL

## Expected Result:
Show workspace conversation or clearly error message if error occured

## Actual Result:
Show error when the user accesses workspace url after inviting them

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a5c28e2e-fe87-4db8-9176-9118840f34c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
Having trouble recreating

**Comment by twisterdotcom** [comment]
I can't recreate this. Closing.

https://github.com/Expensify/App/assets/9133401/8a244edf-97fb-4e9f-8877-59cbde8769d9
