### ISSUE TITLE
[Wave Collect] [Xero] [Advanced] Create the Bill Payment Account Selector Page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39751]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=kix.m1q9dza82941).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

**Comment by miljakljajic** [comment]
Commented in SWM: https://expensify.slack.com/archives/C04878MDF34/p1713189922506479?thread_ts=1712333484.848839&cid=C04878MDF34

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by miljakljajic** [comment]
Thank you @SzymczakJ :)

**Comment by miljakljajic** [comment]
How we doing on this @SzymczakJ

**Comment by SzymczakJ** [comment]
I'm implementing Advanced settings page along with this Bill Payment Account Selector Page. I'll be OOO next week but I will try to put out a draft PR for this today 😃

**Comment by rushatgabhane** [comment]
I'm working on this

**Comment by mananjadhav** [comment]
I am working on this one. ([slack thread](https://expensify.slack.com/archives/C036QM0SLJK/p1714645347410429?thread_ts=1713799302.291019&cid=C036QM0SLJK))

**Comment by trjExpensify** [comment]
Deployed to staging yesterday.

**Comment by pecanoro** [comment]
Do we need to pay @mananjadhav here before closing?

**Comment by hungvu193** [comment]
I think No. We will be paid centrally when Xero project's done
