### ISSUE TITLE
[Awaiting Payment 16th May] [Wave Collect] [Xero] [Advanced] Create the Invoice Collection Account Selector Page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#39752]
You need to build the page following the steps outlined [here](https://docs.google.com/document/d/1VEIzxwNzedLNestAFVT5InGvD4N6FHb0922xjMGOkko/edit#bookmark=id.f8axd4jurje9).

This will be worked on by SWM engineers, see Slack discussion [here](https://expensify.slack.com/archives/C04878MDF34/p1712333484848839). 

Until the Xero authorization flow ([NewDot issue](https://github.com/Expensify/App/issues/39725))  is done (which entails NewDot, Web-E and IS changes), we won't be able to work on this yet.

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by muttmuure** [comment]
@lakchote do I need to get a SWM volunteer at this point?

**Comment by lakchote** [comment]
> [@lakchote](https://github.com/lakchote) do I need to get a SWM volunteer at this point?

Some internal engineers are interested on working on this. I'm going to confirm, and otherwise we'll assign a SWM engineer.

**Comment by muttmuure** [comment]
Still held

**Comment by hungvu193** [comment]
I'm gonna work on this.

**Comment by trjExpensify** [comment]
Deployed to production 9 hours ago

**Comment by trjExpensify** [comment]
Payment will be handled centrally when we wrap the project, we can close this as the regression period is over.
