### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [Dupe Detection] Merge Duplicates - Review Page

### ISSUE THREAD

**Issue by pecanoro** [Expensify/App#39756]
# Part of the Merge Duplicates project
Main issue: https://github.com/Expensify/Expensify/issues/307591
Doc section: Surfacing Potential Duplicates
Project: [Wave: Collect Approvers] Dupe Detection

Part of a series of issues:

- https://github.com/Expensify/App/issues/39756
- https://github.com/Expensify/App/issues/39808
- https://github.com/Expensify/App/issues/39810

# Feature Description

### Context for ReviewDuplicates

- Review page - /r/:threadReportID/duplicates/review
- Merchant - /r/:threadReportID/duplicates/review/merchant
- Category - /r/:threadReportID/duplicates/review/category
- Tag - /r/:threadReportID/duplicates/review/tag
- Description - /r/:threadReportID/duplicates/review/description
- Confirm page - /r/:threadReportID/duplicates/confirm

![image](https://github.com/Expensify/App/assets/6474442/702a370d-19dc-4f7a-ab86-fa883d0398ff)

All of these screens will exist in their own navigator so they can be pushed (and later popped off once complete) as a group.

All of this will use an Onyx form key of `ONYXKEYS.FORMS.REVIEW_DUPLICATES_FORM` so we can store the data selected by the user so far when resolving the duplicates. It also lets us keep track of which transaction to keep and which ones are duplicates when the user clicks on Keep this one.

This key will follow a structure like this:

```
{
  "review_duplicates_form_<transactionID>": [
    {
        "duplicates": {
<transactionID>: <transactionID>,
	...
  },
        "merchant": "...",
        "tag": ...",
	  "description": ...",
			…
    }
  ]
}
```

### Review Page

On top of the page, we will add a button to “Keep All” duplicates. When calling onPress, we will call a new API endpoint called `DismissViolation` and navigate back. On oldDot, we use UpdateTransaction (which does a lot of stuff) but since we only have `EditMoneyRequest` here, it seems more appropriate to create a new endpoint to avoid breaking 1:1:1.

- `DismissViolation` will receive a list of transactionIDs since we will have to update each one and the type of violation we are dismissing.

     - As optimistic data, it will update the `transactions_*` Onyx key to include `dismissedViolations` with the accountID of the person that dismissed it in the comment field.
    - As an example:

![image-2024-04-08 10_51_27 803](https://github.com/Expensify/App/assets/6474442/aa9e0992-091a-4846-86d9-ad68bb4db5a0)

    - On failure, we will just remove the same data we added to the optimistic data.

In order to be able to get the duplicates and display them, we will:

- Using Onyx, we can get the transaction for the threadReportID the same way as we do it for the EditRequestPage [here](https://github.com/Expensify/App/blob/d8858c9223025e7af6509e00c58f04eb2eb5ba67/src/pages/EditRequestPage.js#L306-L311). 
- Once we have that, we can get the transaction IDs of the duplicates using this transaction and listening to the `transactions_*` Onyx key. 
- Using Onyx we can fetch the transactions and with each one of those reports we can get the parentReportAction using the `reportActions_` key.

To display the different duplicates on the page, we can make use of [ReportActionItem](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/home/report/ReportActionItem.js) which needs each one of the reportActionIDs so we can iterate and display them using the component.

Each one of [ReportActionItem](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/pages/home/report/ReportActionItem.js) will generate a [MoneyRequestAction](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/ReportActionItem/MoneyRequestAction.js#L1-L0) and each one of this will make use [MoneyRequestPreview](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/ReportActionItem/MoneyRequestPreview.js) to render the request. To show the button “Keep this one”:

- MoneyRequestPreview will add a new button component at the end of the childContainer, similar to what we do in ReportPreview [here](https://github.com/Expensify/App/blob/a1815b355f472d65dbcfd35e3366b62803ef09a7/src/components/ReportActionItem/ReportPreview.js#L268-L275) to submit the report.

    - We can use the page's route prop to determine whether we need to show the button or hide it.
    - `onButtonPressed`: it should store the iouReport we want to keep in `ONYXKEYS.FORMS.REVIEW_DUPLICATES_FORM` and navigate to the page to start reviewing fields. 

- Preview should be navigable the same way as it is defined in `MoneyRequestAction`.

# Manual Test Steps

TODO

# Automated Tests

TODO

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by pecanoro** [comment]
Callstack will be taking these series of tasks

**Comment by kubabutkiewicz** [comment]
Hi, just wanted to inform that I will be OOO from 29.04 to 05.05.

**Comment by pecanoro** [comment]
In progress!

**Comment by pecanoro** [comment]
In progress!

**Comment by pecanoro** [comment]
WIP!

**Comment by pecanoro** [comment]
WIP!

**Comment by pecanoro** [comment]
Yeah, it's because I did a screenshot from the design doc. Any specific reason why you need a bigger resolution?

**Comment by pecanoro** [comment]
@parasharrajat I think so yes, since all C+ signed NDAs but let me double check

**Comment by pecanoro** [comment]
@parasharrajat Shared!

**Comment by pecanoro** [comment]
@JmillsExpensify Can you handle payment for this issue for @parasharrajat since he reviewed the PR?

**Comment by pecanoro** [comment]
@JmillsExpensify Friendly bump on the above 🤗

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @parasharrajat for PR review. We have a testing script being handed off to Applause now, so no need as part of this issue. @parasharrajat please submit a request via NewDot. Thanks!

**Comment by JmillsExpensify** [comment]
@mallenexpensify do you mind confirming my payment summary so that I can approve payment?

**Comment by mallenexpensify** [comment]
Contributor+: @parasharrajat due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
