### ISSUE TITLE
 IOU - User able to start Money Request flow on IOU details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39763]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user should be singed in
1. Open app
2. Open any chat with another user where there has been no money request in the past
3. Make a Money Request
4. Tap on the IOU preview
5. Tap on Plus button next to composer
6. Select "Request Money"
7. Write any amount and tap on continue
8. Navigate back to 1:1 DM chat with user
9. Tap on IOU preview
10. Make a Money Request
11. Tap on iOU preview
12. Tap on Plus button next to composer

## Expected Result:
User should not be ablte to start the Money Request flow from the IOU details page

## Actual Result:
User able to start Money Request flow on IOU details page when first IOU was made. When user made the second IOU, the Money Request option is no more available on IOU details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9a09d7e7-9395-4e59-b88f-d3d195c1c7e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment]
Agreed! We changed the layout of the chat reports, so this is expected now. Closing. @lanitochka17 please note that the new Expense report layout is now the same as the Expense thread if the Expense report has only one expense.
