### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Dupe Detection] Merge Duplicates - Review Fields Page

### ISSUE THREAD

**Issue by pecanoro** [Expensify/App#39808]
# Part of the <Project Name> project
Main issue: https://github.com/Expensify/Expensify/issues/307591
Doc section: Surfacing Potential Duplicates
Project: [Wave: Collect Approvers] Dupe Detection

Part of a series of issues:

- https://github.com/Expensify/App/issues/39756
- https://github.com/Expensify/App/issues/39808
- https://github.com/Expensify/App/issues/39810

# Feature Description

### Context for ReviewDuplicates

- Review page - /r/:threadReportID/duplicates/review
- Merchant - /r/:threadReportID/duplicates/review/merchant
- Category - /r/:threadReportID/duplicates/review/category
- Tag - /r/:threadReportID/duplicates/review/tag
- Description - /r/:threadReportID/duplicates/review/description
- Confirm page - /r/:threadReportID/duplicates/confirm

![image](https://github.com/Expensify/App/assets/6474442/702a370d-19dc-4f7a-ab86-fa883d0398ff)

All of these screens will exist in their own navigator so they can be pushed (and later popped off once complete) as a group.

All of this will use an Onyx form key of ONYXKEYS.FORMS.REVIEW_DUPLICATES_FORM so we can store the data selected by the user so far when resolving the duplicates. It also lets us keep track of which transaction to keep and which ones are duplicates when the user clicks on Keep this one.

This key will follow a structure like this:

```
{
  "review_duplicates_form_<transactionID>": [
    {
        "duplicates": {
<transactionID>: <transactionID>,
	...
  },
        "merchant": "...",
        "tag": ...",
	  "description": ...",
			…
    }
  ]
}
```

### Review Fields Page

It will make use of the new [InteractiveStepSubHeader](https://docs.google.com/document/d/1t8_Fn93LSSU4gG4z7WRt8IFcpSGK4TIe4QamdcTXjxE/edit) to show the progress in which step we are currently in. As a reminder this component:

- Receive an array of navigation names, the position will match where it should go when the current step is completed
- Completed steps will be counted based on the length of the navigation names array

For each of the pages to resolve category, merchant, etc, will have a Title element and a SelectionList element to display the different options. 

- To display the options, we stored the duplicates in `ONYXKEYS.FORMS.REVIEW_DUPLICATES_FORM` at the beginning of the flow so we can search for the transaction data to display the corresponding fields. 
- `onSelectRow` we store the selected field in the Onyx key and move to the next field until we have gone through all of them.

# Manual Test Steps

TODO

# Automated Tests

TODO

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by pecanoro** [comment]
Callstack will be taking these series of tasks

**Comment by kubabutkiewicz** [comment]
Hi, I'm Jakub from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by kubabutkiewicz** [comment]
Hi, just wanted to inform that I will be OOO from 29.04 to 05.05.

**Comment by pecanoro** [comment]
In progress!

**Comment by pecanoro** [comment]
In progress!

**Comment by pecanoro** [comment]
WIP!

**Comment by pecanoro** [comment]
WIP!

**Comment by pecanoro** [comment]
@parasharrajat It didn't create a payment issue when you reviewed the PR, right? So I can assign you here instead

**Comment by bfitzexpensify** [comment]
Payment summary is correct:

@parasharrajat owed $250 via manual request

**Comment by pecanoro** [comment]
@bfitzexpensify When do we close the issue when it's via manual request?

**Comment by bfitzexpensify** [comment]
Sounds good to me - proposed those steps be added via https://github.com/Expensify/Expensify/issues/414629.

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
