### ISSUE TITLE
[Hold for payment 2024-07-31] [Dupe Detection] Merge Duplicates - Confirm Page

### ISSUE THREAD

**Issue by pecanoro** [Expensify/App#39810]
# Part of the Merge Duplicates project
Main issue: https://github.com/Expensify/Expensify/issues/307591
Doc section: Surfacing Potential Duplicates
Project: [Wave: Collect Approvers] Dupe Detection

Part of a series of issues:

- https://github.com/Expensify/App/issues/39756
- https://github.com/Expensify/App/issues/39808
- https://github.com/Expensify/App/issues/39810

# Feature Description

### Context for ReviewDuplicates

- Review page - /r/:threadReportID/duplicates/review
- Merchant - /r/:threadReportID/duplicates/review/merchant
- Category - /r/:threadReportID/duplicates/review/category
- Tag - /r/:threadReportID/duplicates/review/tag
- Description - /r/:threadReportID/duplicates/review/description
- Confirm page - /r/:threadReportID/duplicates/confirm

![image](https://github.com/Expensify/App/assets/6474442/702a370d-19dc-4f7a-ab86-fa883d0398ff)

All of these screens will exist in their own navigator so they can be pushed (and later popped off once complete) as a group.

All of this will use an Onyx form key of ONYXKEYS.FORMS.REVIEW_DUPLICATES_FORM so we can store the data selected by the user so far when resolving the duplicates. It also lets us keep track of which transaction to keep and which ones are duplicates when the user clicks on Keep this one.

This key will follow a structure like this:

```
{
  "review_duplicates_form_<transactionID>": [
    {
        "duplicates": {
<transactionID>: <transactionID>,
	...
  },
        "merchant": "...",
        "tag": ...",
	  "description": ...",
			…
    }
  ]
}
```

### Confirm Page

Our last confirm page will show a similar non-editable version of [MoneyRequestView](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/ReportActionItem/MoneyRequestView.js#L80):

- Enable shouldShowOfflineIndicator for the screenwrapper as the command only works online.
- This view is also a form component but features a green “Confirm” button.
- onPress, we call an action in actions/IOU.js called mergeDuplicates which calls:

```
API.write('MergeDuplicates',
{
	transactionID,  // transaction to keep
	transactionIDs, // transactions to delete
       created,
       merchant,
       ...
}:
```

Some notes about the above request:

- Since we are using pattern B, we need to set the optimistic and failure data. When we merge two or more transactions, we basically need to get rid of the ones that we don’t want to keep and update the one that we want to keep.
    
    - Removing the ones that we don’t want to keep works similarly to when we delete a money request, so we will update Onyx data really similarly to what we do [here](https://github.com/Expensify/App/blob/3e59d001bfe7ef605e6ce3779bd62d4b6a669cda/src/libs/actions/IOU.js#L2007-L2196).
     - Additionally, we need to update the  `transactions_` key in Onyx with the updated fields (merchant, tags, category…) for the transactionID.
    - We also need to update the comment in the `transactions_` key in Onyx to remove the duplicate violation violation within the comment. 
    - We also need to update the `transactionViolations_` key in Onyx to remove the duplicate violation. We’ll update the `ViolationUtils.getViolationsOnyxData` method that calculates the new transaction violations (by adding/removing those that have been addressed with the current user changes), and returns an object that we can save into Onyx, to work with duplicate violations as well.

- We will navigate the user directly back to the [MoneyRequestView](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/ReportActionItem/MoneyRequestView.js#L80) of the expenseReport we were keeping.

<details><summary>Issue Owner</summary>Current Issue Owner: @kubabutkiewicz</details>

**Comment by pecanoro** [comment]
Callstack will be taking these series of tasks

**Comment by kubabutkiewicz** [comment]
Hi, I'm Jakub from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by kubabutkiewicz** [comment]
Hi, just wanted to inform that I will be OOO from 29.04 to 05.05.

**Comment by pecanoro** [comment]
In progress!

**Comment by pecanoro** [comment]
In progress!

**Comment by pecanoro** [comment]
WIP!

**Comment by pecanoro** [comment]
WIP!

**Comment by pecanoro** [comment]
Still WIP!

**Comment by kubabutkiewicz** [comment]
@parasharrajat @pecanoro @JmillsExpensify PR is ready to review 😄

**Comment by trjExpensify** [comment]
Did the automation not run here? Seems like it hit prod 3 days ago: https://github.com/Expensify/App/pull/42571#issuecomment-2244525280

**Comment by pecanoro** [comment]
Hmm, yes, I think it failed

**Comment by JmillsExpensify** [comment]
cc @sakluger this is ready for payment soon.

**Comment by sakluger** [comment]
Sorry, everyone, I just noticed that this issue slipped through the cracks.

Summarizing payment on this issue:

Contributor: @kubabutkiewicz $250 - contractor, no payment required
Contributor+: @parasharrajat $250, please request on Newdot 

@parasharrajat do we need any regression tests for this one? Maybe something similar to the tests laid out in the [PR](https://github.com/Expensify/App/pull/42571)?

**Comment by sakluger** [comment]
Thanks! Those steps are pretty good, I edited them to be a bit more specific.

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
