### ISSUE TITLE
 Onboarding - Onboarding video loads infinitely with console error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com/onboarding
2. Enter name > Next
3. Select an option > Next

## Expected Result:
Video will start playing in the pop-up

## Actual Result:
Video loads infinitely in the pop-up. Console error also shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/87de840a-28c8-4629-85ff-bc5dd01b0010

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ab23a1bffd59dff</li>
        <li>Upwork Job ID: 1777356837380399104</li>
        <li>Last Price Increase: 2024-04-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@arosiclair  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
I can take over @arosiclair related to wave-collect

**Comment by mountiny** [comment]
This seems like we need a cloudflare fix

**Comment by mountiny** [comment]
As that its not an App blocker

**Comment by mountiny** [comment]
This was deployed for staging now

**Comment by mountiny** [comment]
Fixed

https://github.com/Expensify/App/assets/36083550/f3d7cc26-5751-49bd-af3f-39ec68937da4

**Comment by mountiny** [comment]
Closing
