### ISSUE TITLE
Web - Draft - Chat with draft takes some time to move up in LHN with pencil icon

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39821]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat that is not at the top of LHN.
3. Type a draft.

## Expected Result:
The chat will move up to the top with a pencil icon immediately when the draft is typed (producition behavior).

## Actual Result:
It takes some time for the chat to move up to the top with a pencil icon when the draft is typed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7d9071e9-2ca1-44ec-bafc-8344f8aa5c7e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by mountiny** [comment]
This is a new baseline, its a performance improvement as computing the draft can lead to slowdown on big accounts with lots of reports, now the draft is decoupled from reports objects but it can also show up a bit later after user types

The draft status is computed after user stops typing so it can take a bit to show up
