### ISSUE TITLE
[$250] [Awaiting Payment 30th April] [Guided Setup] Onboarding - Modal can bn be dismissed by ESC key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39834]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/37733
## Action Performed:
1. Go to staging.new.expensify.com/onboarding
2. Press ESC key on the keyboard

## Expected Result:
The modal cannot be dismissed by any other method (PR step 6)

## Actual Result:
The modal can be dismissed by ESC key on the keyboard (PR step 6 fails)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6784b7cc-aee1-402a-909f-443328a12be4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7cb0b309be5d303</li>
        <li>Upwork Job ID: 1783275074523254784</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@flodnv  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
I can take over for wave-collect, been helping out Frank with this project and he is ooo

**Comment by mountiny** [comment]
There is a second PR coming which will actually enable this flow and we need to incorporate this into that pull request, unless its already implemented

I am demoting it from being a blocker, added it to the project and I will follow up to make sure the PR which enabled this onboarding has the correct behaviour

cc @cdOut @filip-solecki

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM expert agency and I would like to work on this!

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz from Software Mansion, the expert agency, and I'd like to take over this issue from Filip.

**Comment by trjExpensify** [comment]
Hit prod two days ago. Assigning a BZ for @hoangzinh's payout.

**Comment by miljakljajic** [comment]
@hoangzinh please accept the offer and we'll get you paid!

**Comment by miljakljajic** [comment]
Paid!
