### ISSUE TITLE
LHN - LHN displayed blank for a 1-2  second when user rapidly scrolled up

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39849]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user should be signed in
1. Open app
2. Scroll down to the very bottom
3. Rapidly scroll up to the very top

## Expected Result:
LHN should be properly displayed during scrolling

## Actual Result:
LHN displayed blank for a 1-2 second when user rapidly scrolled up

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6d14c99a-6832-42cd-a2ce-9425a07e21f3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I dont think this is a blocker, this has been happening for a while, it just might be more visible on some devices than others

**Comment by mountiny** [comment]
Its just a nature of the FlashList, only some of the rows are rendered for performance reasons so when user scrolls so fast the top rows will not be rendered yet.

**Comment by mountiny** [comment]
I believe we can close this

**Comment by roryabraham** [comment]
yeah, this is just a performance issue. Let's close this for now, but in the next performance audit maybe we can try to introduce a "scroll drop" metric
