### ISSUE TITLE
Wallet - Back button in Wallet loops between Wallet and Add bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39847]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39038
## Action Performed:
1. Launch New Expensify app
2. Paste the link https://staging.new.expensify.com/settings/wallet/add-bank-account-refactor
in chat
3. Tap on the link
4. Tap on the back button
5. Tap on the back button again

## Expected Result:
After tapping on the back button in Wallet page, app will redirect to settings page

## Actual Result:
Back button in Wallet page loops between Wallet and Add bank account page after navigating to [https://staging.new.expensify.com/settings/wallet/add-bank-account-refactor](https://staging.new.expensify.com/settings/wallet/add-bank-account-refactor.)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5d862996-ec7c-404d-947b-9e81b119d0e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by AndrewGable** [comment]
Tagging those involved in https://github.com/Expensify/App/pull/39038: @koko57 @barttom @ArekChr @rezkiy37 @shawnborton @Pujan92 @mountiny

Can you see if this regression is related? Thanks

**Comment by Pujan92** [comment]
Yes, it is related to linked PR. @koko57 I think we should not pass any fallback route for `goBack` as that pattern I am seeing at other places.

https://github.com/Expensify/App/blob/6ec5811c57c67a3373ed11284e60509c2a1e4d16/src/pages/EnablePayments/AddBankAccount/AddBankAccount.tsx#L67

As this flow is not open to user yet, we can remove deploy blocker for this.

**Comment by AndrewGable** [comment]
Just to confirm @Pujan92 - It's under a beta? Or what do you mean by "As this flow is not open to user yet"?

**Comment by Pujan92** [comment]
Actually, this wallet refactor is still under process and at the moment the users are navigated to the old flow only(where this issue doesn't persist). New flow navigation will be replaced with the old one once all the steps of refactoring are completed.

**Comment by koko57** [comment]
@AndrewGable the refactor is still work in progress and all the issues will be resolved in the following PRs.

**Comment by mountiny** [comment]
I can take over and monitor with @koko57 its part of https://github.com/Expensify/App/issues/36648 and the flow is behind specific route, we will address this in the follow up PRs before we enable the flow for actual users

**Comment by mountiny** [comment]
Making this monthly as the refactor is ongoing

**Comment by mountiny** [comment]
The refactor should be done soon, last PR remaining

**Comment by mountiny** [comment]
the refactor is done. @lanitochka17 could you please retest if this issue is still repro?

**Comment by kavimuru** [comment]
@mountiny Bug is fixed.

https://github.com/Expensify/App/assets/43996225/762153d6-75e8-42d7-91be-3e29b9728d53

**Comment by mountiny** [comment]
🎉
