### ISSUE TITLE
[READY FOR PAYMENT][$500] Payment issue for PR Review #35973

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#39842]
Payment issue for reviewing PR https://github.com/Expensify/App/pull/35973
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01565eb8ea35eb30fa</li>
        <li>Upwork Job ID: 1777376562929033216</li>
        <li>Last Price Increase: 2024-04-08</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Adjusted the payment since this was before the new changes

**Comment by thienlnam** [comment]
This is ready for payment cc @laurenreidexpensify. The PR was deployed on Feb 26 https://github.com/Expensify/App/pull/35973#issuecomment-1965247666

**Comment by JmillsExpensify** [comment]
$500 approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/39842#issuecomment-2043213270) and the one immediately above.
