### ISSUE TITLE
[HOLD for payment 2024-06-06] [HOLD for payment 2024-05-06] Web - Features - Feature row in left side bar appears with delay after the page opens on the right

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39841]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38546

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > Collect workspace.
3. Go to More features.
4. Toggle on any feature.

## Expected Result:
The feature row in the left side bar will appear simultaneously with the feature page on the right.

## Actual Result:
The feature row in the left side bar appears with delay after the feature page opens on the right.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/eefa4ea0-7bb4-4b5e-9bb2-2a3bd7e2a80e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
Related to more features page, taking over

**Comment by mountiny** [comment]
Do we have been back and forth on this one when developing https://github.com/Expensify/App/pull/38546 

This is just how the animation works at the moment. I think its fine, curious for more opinions from @Expensify/design if we want to make any changes to this.

I would give this some time in the app, so we can feel it out before we make any further changes. cc @allroundexperts @rojiphil @allroundexperts

**Comment by shawnborton** [comment]
Yeah, that's fair. That being said, seeing it in this context makes me think we should try to make the whole thing feel slightly more "snappy" - right now it feels so slow and delayed that the difference between the row animating and the content pane already being there feels odd. So yeah, perhaps we just speed up some timing and breathe a little life into it?

**Comment by allroundexperts** [comment]
That'd require your (design teams) back and forth input. As far as dev work is concerned, It's just switching / fine tuning the timing till we have an agreement.

**Comment by dannymcclain** [comment]
>So yeah, perhaps we just speed up some timing and breathe a little life into it?

@shawnborton Totally game for that—do you wanna do some timing prototypes or something like that in Slack so we can just report back with the final timing?

**Comment by allroundexperts** [comment]
Can you guys do this for all platforms?

**Comment by dubielzyk-expensify** [comment]
> do you wanna do some timing prototypes or something like that in Slack so we can just report back with the final timing?

Let's do it. I got a prototype for this interaction. I think there's a big difference in how this feels on mobile vs desktop. I'll start a thread

**Comment by mountiny** [comment]
Thank, making this weekly and assigned @allroundexperts to polish this once we decide the exact behaviour

**Comment by dubielzyk-expensify** [comment]
We've had a chat and here's where we ended up:

### 1. On desktop, turning a toggle ON should not navigate to the page, but play the left-hand navigation animation:

https://github.com/Expensify/App/assets/145416827/a73a3511-565b-4596-acdb-e352454512fc

### 2. On mobile, We should remove or drastically reduce the delay 

https://github.com/Expensify/App/assets/145416827/a87d0284-116d-441c-a7c9-ba9d2c427a20

### 3. Tweak all animations:
Here are the timings I'm working with to ensure the above results you see in the video (which is basically what we want):
- Delay on navigating on mobile after turning toggle ON: `100ms`
- Below you can see an illustration of how the animation works:
![CleanShot 2024-04-11 at 15 48 32@2x](https://github.com/Expensify/App/assets/145416827/4a36e763-7511-433f-8157-7f918fdd12d0)

Hopefully that makes it clear, but let me know if you got any questions 😄 


(Worth noting that when we say desktop we refer to the screensizes where you have the navigation showing on the left hand side. Mobile refers to where things collapses in showing one view at a time.)

**Comment by shawnborton** [comment]
Love it, thanks for laying this out so clearly Jon!

**Comment by mountiny** [comment]
@allroundexperts will you be able to tackle these?

**Comment by allroundexperts** [comment]
Yep. Will have a PR up tomorrow.

**Comment by mountiny** [comment]
Perfect, thanks!

**Comment by allroundexperts** [comment]
PR: https://github.com/Expensify/App/pull/40369

**Comment by allroundexperts** [comment]
This got reverted https://github.com/Expensify/App/pull/41176. There was an issue on native iOS that we were unable to catch. I'll create a new PR soon.

**Comment by sobitneupane** [comment]
@mountiny I reviewed the [PR](https://github.com/Expensify/App/pull/40369). Can you please assign me?

**Comment by allroundexperts** [comment]
@sobitneupane Please review the new PR.

https://github.com/Expensify/App/pull/42026

**Comment by MitchExpensify** [comment]
Closing as

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
