### ISSUE TITLE
[$250] Web - IOU - Report fields are not auto focused

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39845]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36039
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
- A collect WS created in OD with chat enabled
- A few report fields are added
1. Navigate to staging.new.expensify.com
2. Open WS chat and create a money request
3. Open the expense conversation of the IOU created on step 2
4. Click on a report field

## Expected Result:
The input field should be auto focused when RHP opens

## Actual Result:
The input field does not get auto focused

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/66e0906d-f369-4039-8a48-d53e6360338c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170f515ec872826bb</li>
        <li>Upwork Job ID: 1777440709498458112</li>
        <li>Last Price Increase: 2024-04-08</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by mountiny** [comment]
This is a minor UX issue which we do not have to hold deploy for

cc @allroundexperts @thienlnam

**Comment by allroundexperts** [comment]
Agreed. I can be the C+ here if this needs to go external.

**Comment by marcochavezf** [comment]
Assigning you @allroundexperts as C+ and making it external

**Comment by marcochavezf** [comment]
Thanks for the review @allroundexperts, assigning @GandalfGwaihir 🚀

**Comment by kevinksullivan** [comment]
Payment summary:
- @GandalfGwaihir $250
- @allroundexperts $250

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
