### ISSUE TITLE
Distance Expense - Inconsistency in preview between the main chat and the expense report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39843]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4480566
**Issue reported by:**  Applause - Internal Team

## Action Performed:
1.On an account that is an employee of a workspace (not the admin)
2.Click on FAB
3.Select "Request Money"
4.Click on the "Distance" tab
5.Click on "Start"
6.Enter as destination your current location by selecting the "Use current location" option
7.Set other 2 waypoints to places near your location to generate a "real" trip
8.Navigate to the expense details
9.Click on the generated receipt

## Expected Result:
The WS chat displays an expense thumbnail with a map, when clicking it, the report preview includes a view of the map and trip

## Actual Result:
The thumbnail shows no map in the main chat, the report preview generates the map and trip with a delay. The map in the preview in the main chat generates after a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f833a230-1b6e-41d5-a4dd-3f540882e53f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by FitseTLT** [comment]
handled in https://github.com/Expensify/App/pull/39243

**Comment by abekkala** [comment]
closing as a fix for this is already being released
