### ISSUE TITLE
[$250] mWeb - Chat - The keypad lagging, making it difficult to type or delete characters accurately in Redmi phones

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter any text ( randomly try to type all letters, use number keypad, symbols, try to type using everything randomly.
4. Try to remove entered text by tapping delete button

## Expected Result:
Users should be able to enter and delete text seamlessly without experiencing any lag or issues with the keypad.

## Actual Result:
The keypad lagging, making it difficult to type or delete characters accurately in Redmi phones

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0edad024-dc6a-4f2f-9421-1250d2e1245f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3feefbbbfd76990</li>
        <li>Upwork Job ID: 1777444404446453760</li>
        <li>Last Price Increase: 2024-04-22</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
I am not sure if I follow exactly what is happening in the video

@kbecciv @isagoico @kavimuru Is this reliably repro on all android native and not on other platforms? 

cc @tomekzaw @Skalakid @BartoszGrajdek as ti might be related to the markdown

**Comment by jasperhuangg** [comment]
@mountiny It seems like there's a pretty large delay between when a key is tapped and when the input shows up in the composer.

**Comment by jasperhuangg** [comment]
At first glance, the changes from https://github.com/Expensify/App/pull/37281 seem like a good candidate for this issue.

**Comment by jasperhuangg** [comment]
@mountiny 

> related to the markdown

Do you have any specific markdown related PRs that you are thinking of?

**Comment by jasperhuangg** [comment]
> @kbecciv @isagoico @kavimuru Is this reliably repro on all android native and not on other platforms?

@mountiny seems like this is happening on Android mWeb, does this also happen on native though?

**Comment by jasperhuangg** [comment]
@kbecciv This only happens on Redmi phones? Do you have any other Android devices that you can test this with?

**Comment by kbecciv** [comment]
@jasperhuangg
I'm going to request a test with a few different devices., will update you shortly!

**Comment by mountiny** [comment]
@jasperhuangg I believe that draft PR mainly changed how/ where we store whether a report has a draft but it should not have affected the actual typing experience of the content of the draft being saved.

It would be great to specify on what platforms/ devices this can be reliably repro-ed but if its platform specific ti feels more related to the markdown feature, rather than the draft PR.

cc @shubham1206agra @TMisiukiewicz for visibility

**Comment by kbecciv** [comment]
Issue isn't not reproduced on Pixel 6 / Chrome and SG21/Chrome, nor on any other devices. 
I think this is specific issue for Redmi phones, which we have two testers reproduced!  

https://github.com/Expensify/App/assets/93399543/898ce135-6511-4457-9833-7f24f5714812

I believe this issue is specific to Redmi phones, as we've had two testers reproduce it.

**Comment by mountiny** [comment]
@jasperhuangg I suggest removing the DB label and expoerting this issue if that is the case

**Comment by jasperhuangg** [comment]
Removing blocker label because this only happens on very specific Android devices and doesn't appear to be linked to any of the PRs that are currently on staging.

**Comment by jasperhuangg** [comment]
Still waiting on proposals on this one

**Comment by jasperhuangg** [comment]
Still waiting for proposals

**Comment by jasperhuangg** [comment]
Same ^

**Comment by twisterdotcom** [comment]
Is this bug specific to certain devices? If so, I'm going to close. Like there is no way this is a stock keyboard right?
<img width="367" alt="image" src="https://github.com/Expensify/App/assets/9133401/2d25a80b-78cc-4ab2-8bc3-a91c6a78cdbc">
