### ISSUE TITLE
Room chat – Task in a room appears with a delay for user B

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39859]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Go to any room chat as user A
4. In incognito tab log in as user B (group member)
5. As user A create a task
6. As user B observe the room chat

## Expected Result:
Task in a room appears immediately for user B

## Actual Result:
Task in a room appears with a delay for user B

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b1d281e9-9c14-490f-a170-5afb6d99d9f1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by puneetlath** [comment]
Hmm, interesting. So maybe we aren't sending a pusher event for this. I'll try to reproduce.

**Comment by puneetlath** [comment]
I'm going to close this for now. Doesn't seem worth prioritizing.
