### ISSUE TITLE
[HOLD for payment 2024-04-25] [Guided Setup] [$250] Android - Onboarding video can be scrubbed through on iOS app, but not on Android app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39855]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37733
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com/onboarding.
2. Enter name > Next.
3. Select an option > Next.
4. When the video plays, scrub through the video.

## Expected Result:
The onboarding video can be scrubbed through on Android app, as it is possible to do so on iOS app.

## Actual Result:
The onboarding video cannot be scrubbed through on Android app.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2a26898a-50ae-4743-be04-37ac78965508

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010886f419f3cf3d95</li>
        <li>Upwork Job ID: 1777809491124957184</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
Gonna take over as this is related to the onboarding project where I am helping. Francois is ooo.

@filip-solecki @cdOut can one of you comment here so we can assign you to follow up

**Comment by mountiny** [comment]
Demoting as this is still not active for the users, they need to enter a deeplink flow with specific path to see this

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM an expert agency and I'll like to work on this issue!

**Comment by Skalakid** [comment]
Hi, I'm Michał from SWM an expert agency and I prepared a fix for the this issue. We are using a gesture handler inside the video progress bar and on Android it have problems with detecting gestures inside modals . Actually the [problem](https://github.com/software-mansion/react-native-gesture-handler/issues/139) is well known and to fix it we have to wrap the ProgressBar component with `GestureHandlerRootView`

**Comment by Skalakid** [comment]
@mountiny @filip-solecki Here is a [PR](https://github.com/Expensify/App/pull/39964) with the fix

**Comment by trjExpensify** [comment]
Deployed to staging 5 days ago.

**Comment by mountiny** [comment]
@allroundexperts $250 for their testing and a review.

I think the tests will be handled at the end of the onboarding projects

**Comment by muttmuure** [comment]
@allroundexperts sounds like you just need to submit your request through New Expensify

**Comment by allroundexperts** [comment]
All done. Feel free to close.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
