### ISSUE TITLE
[$250] Add support for viewing full screen Group Chat custom avatars

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#39850]
## Problem

When we added support for custom Group Chat avatars there are some places left where we cannot yet view the full screen avatar.

## Solution

Navigate to the correct page like we do here when user taps on the avatar: https://github.com/Expensify/App/blob/ddb83f2493c3d08b3b3febcfd9dc93729f38e3c2/src/components/RoomHeaderAvatars.tsx#L19-L28
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c10e84b6d429f37d</li>
        <li>Upwork Job ID: 1785082381325901824</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>tsa321 | Contributor | 103805311</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by s77rt** [comment]
No progress yet. Focused on QBO

**Comment by dannymcclain** [comment]
I think ideally we'd follow the same pattern that we use for custom workspace avatars.

![CleanShot 2024-04-29 at 13 32 55](https://github.com/Expensify/App/assets/7516624/00498310-d56e-4efe-a082-c51385052efa)

cc @Expensify/design - I actually think the order of these should be Upload, View, Remove. But that's not a super pressing concern.

**Comment by marcaaron** [comment]
Hey @s77rt, let us know if you have started working on this. I can make it external, but would love if you could be the C+ still.

**Comment by shawnborton** [comment]
I agree with the proposed solution from Danny.

**Comment by s77rt** [comment]
@marcaaron Making this `External` sounds good to me. I'd love to be the C+ still

**Comment by s77rt** [comment]
@nexarvo Thanks for the proposal. Your RCA is correct. The solution looks overall good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/39850#issuecomment-2083897742)

**Comment by marcaaron** [comment]
Thanks everyone 🚀

**Comment by s77rt** [comment]
@nexarvo The PR has been reverted. Can you raise a PR with fixes for the found regressions?

**Comment by s77rt** [comment]
@nexarvo Are you still able to work on this?

**Comment by s77rt** [comment]
@marcaaron Let's reopen this for proposals

**Comment by s77rt** [comment]
@tsa321 I haven't read the code fully but let's not use base64 uri. Dealing with long strings can be slow. If you want to pick up this issue please use the proposal template addressing the regressions from the previous PR

**Comment by s77rt** [comment]
@marcaaron Can you readd `Help Wanted` label

**Comment by marcaaron** [comment]
summarizing the status of this one... seems like @nexarvo has bailed on this issue and needs to be unassigned here? 

@tsa321 do you have some proposal for us?

**Comment by s77rt** [comment]
@tsa321 Looking forward for the proposal. (code-diffs, branches, PRs, should be avoided)

**Comment by s77rt** [comment]
@tsa321 Can you continue from https://github.com/Expensify/App/pull/41586 and just state the changes needed to fix each regression independently

**Comment by s77rt** [comment]
@tsa321 Your proposal only covered adding support for viewing the group chat avatar while in the creation flow and didn't include a solution for doing so from the report screen (report details page).

**Comment by s77rt** [comment]
@tsa321 

> I believe we don't really need to store the avatarFilename in optimistic data when creating a group chat

This is still needed, otherwise if you create a group chat offline and try to view the avatar in the report details page it won't work and we shouldn't use a fake file name either as we can't predict the extension

**Comment by s77rt** [comment]
@tsa321 

> the navigation is smooth because we return a null element instead of the AttachmentModal

Let's try another approach, let's keep the modal displayed but display the default avatar instead (same as in the confirmation page)

> I am just moving the condition into `isPolicyRelatedReport` to determine whether it is a policy-related report.

`isPolicyRelatedReport = policyName !== unavailableTranslation` looks like a hack. Can we find a better solution e.g. use `report.policyID`?

**Comment by s77rt** [comment]
@tsa321 Can you update your proposal based on the two above points?

**Comment by zanyrenney** [comment]
Just a heads up, I am going OOO until August 30th. I won't reapply the bug label as we're far from payout, but please can you keep this issue updated daily with your progress @tsa321 @s77rt 
Thanks!

**Comment by s77rt** [comment]
@tsa321 

> We could displays default avatar after user refresh the report avatar page

Can you explain how will you do that?

**Comment by s77rt** [comment]
@tsa321 

> they will see a different default avatar for the group

Why would they see a different default avatar? They should get the same default avatar that was shown in the modal. They should see the avatar as highlighted in the video below


https://github.com/user-attachments/assets/27983a08-eece-4ce2-baa2-240b184e8aa6

**Comment by s77rt** [comment]
@tsa321 Please do not post code diffs, PRs, etc. I think we should discuss the details in the PR.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/39850#issuecomment-2302580304)

**Comment by dubielzyk-expensify** [comment]
Not overdue

**Comment by s77rt** [comment]
Waiting on @marcaaron to review and assign @tsa321 for his proposal based on https://github.com/Expensify/App/issues/39850#issuecomment-2308761598

**Comment by marcaaron** [comment]
Just assigned Melv.

**Comment by s77rt** [comment]
PR was deployed to production 2 weeks ago. This is ready for payment cc @zanyrenney

**Comment by zanyrenney** [comment]
**payment summary**

paid @s77rt $250 via upwork
paid @tsa321 $250 via upwork. 

Thanks 👋🏼

**Comment by s77rt** [comment]
I have refunded 50% for the regressions (there were 2 but both found at same period and one of them was due to a "feature" that we just removed)
