### ISSUE TITLE
Android/iOS - Shortcut - Tapping shortcut track manual does not trigger any action

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39863]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap fab--- track expense---manual
3. Enter an amount and tap next
4. Tap track expense
5. Navigate back to LHN
6. Tap fab
7. Tap shortcut track manual

## Expected Result:
Tapping shortcut track manual must direct to track manual page

## Actual Result:
Tapping shortcut track manual does not trigger any action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bff54d01-bcf5-4e64-8d52-5629afd88fff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by muttmuure** [comment]
cc @thienlnam

**Comment by muttmuure** [comment]
@Gonals what's the plan with these?

https://github.com/Expensify/Expensify/issues/378892

**Comment by Gonals** [comment]
This was expected, as track functionality wasn't implemented yet. [This PR](https://github.com/Expensify/App/pull/39640)should fix this, so I'm going to close 😁
