### ISSUE TITLE
[Awaiting Payment][$250] PDF - "Send" button is missing on password protected PDF preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4481584
**Email or phone of affected tester (no customers):** vdargentotest+mweb040824@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in
1. Go to any chat
2. Try to send a password protected PDF (there is one attached to this report, password: "Test12345")
3. On the preview before sending, tap on "enter the password"
4. Enter the password and tap on "Confirm"
5. Verify the PDF is displayed but there is no "Send" button at the bottom

## Expected Result:
"Send" button should be displayed below de PDF

## Actual Result:
The "Send" button is missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/961e809d-745d-4840-a972-7697c82dec97

![default-file-icon](https://github.com/Expensify/App/assets/78819774/5982fee0-40a2-47e6-93a5-f73197aa7ad2)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01addbe94fe205e652</li>
        <li>Upwork Job ID: 1777461049030750208</li>
        <li>Last Price Increase: 2024-04-08</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@thienlnam  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by thienlnam** [comment]
Looks like the keyboard is coming up and covering the send button - this looks like it could be external

**Comment by thienlnam** [comment]
Seems the automation didn't work here, but this is ready for payment cc @strepanier03

**Comment by strepanier03** [comment]
Thanks @thienlnam I appreciate you changing the priority for this 🙌

**Comment by strepanier03** [comment]
@dukenv0307 - Paid via Upwork.
@nkdengineer - Offer sent via Upwork. Will check this Monday.

**Comment by nkdengineer** [comment]
@strepanier03 I accepted the offer 🙏

**Comment by strepanier03** [comment]
Thanks @nkdengineer - Paid and contract closed 🎉
