### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250][Search v1] Create TransactionListItem

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39877]
Section from [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.4eaepp72f3xr)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011106ccde6345e3fb</li>
        <li>Upwork Job ID: 1780007627945009152</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on that :)

**Comment by luacmartins** [comment]
@WojtekBoman is still working on this

**Comment by luacmartins** [comment]
@WojtekBoman please note that we renamed this component to `TransactionListItem`

**Comment by Kicu** [comment]
@luacmartins I have a question (or perhaps you can bring in some designers to help):
In the transaction list there is an icon (image?) for the receipt. It seems to sometimes be some kind of fallback/default icon or an image.

Could someone describe the logic that goes into choosing what image to show in column Receipt?

<img width="700" alt="Screenshot 2024-04-26 at 15 02 23" src="https://github.com/Expensify/App/assets/3929868/26c8dc8d-1032-4dca-9586-6d886e3463f8">

☝️ here is the design that Im referring to

**Comment by luacmartins** [comment]
Those are called eReceipts. We don't have to worry about it for now, since we're hard coding that to false in the API while we migrate some logic for them.

Later on, the API will eventually return the `hasEReceipt` key and we'd be able to do something [like this](https://github.com/Expensify/App/blob/bb4195b29f1217baa617b0c4a49779e5b71b8a40/src/components/Attachments/AttachmentView/index.tsx#L133-L145) to show them.

**Comment by luacmartins** [comment]
Phase 1 won't have the results affected by it, but phase 2 will implement a policyID filter on the search queries

**Comment by jliexpensify** [comment]
**Payment Summary**

- C+ @rayane-djouah: $250 (can you also do the checklist please, if applicable?)

I see that @dukenv0307 is also hired but he was unassigned from this GH so I assume he's not being paid? cc @luacmartins

**Comment by jliexpensify** [comment]
Confirming with @luacmartins  that @dukenv0307 shouldn't be paid.

**Comment by luacmartins** [comment]
>Confirming with @luacmartins that @dukenv0307 shouldn't be paid.

Correct, I asked for an expedited review and assigned @rayane-djouah to review the PR instead

**Comment by luacmartins** [comment]
No need to add tests now, we'll do so once we conclude the project using the manual test script from the design doc.

**Comment by jliexpensify** [comment]
Thanks Carlos for confirming! I'll pay and close this today.

**Comment by jliexpensify** [comment]
Paid and job closed.
