### ISSUE TITLE
[HOLD for payment 2024-05-06] [$250] [Search v1] Create Search widget

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39879]
Section from [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=kix.ndabi93vuj44)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bed533d17650a06</li>
        <li>Upwork Job ID: 1781315585886089216</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@Kicu please comment on this issue so I can assign it to you :)

**Comment by Kicu** [comment]
hey, I confirm I will be working on this :)

**Comment by Zarrrii08** [comment]
https://www.upwork.com/freelancers/zaryabhayatkhan

**Comment by luacmartins** [comment]
@Kicu is still working on this

**Comment by mallenexpensify** [comment]
@Kicu , @dukenv0307 can you please submit a proposal or accept the job and reply here once you have? 
https://www.upwork.com/jobs/~013bed533d17650a06

**Comment by Kicu** [comment]
@mallenexpensify Unsure what you mean, this issue was already done and PR for it is merged.

**Comment by luacmartins** [comment]
The PR has been in prod for 7 days now. @Kicu is from SWM and worked on the implementation.

**Comment by mallenexpensify** [comment]
@dukenv0307 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~013bed533d17650a06

**Comment by mallenexpensify** [comment]
Contributor+: @dukenv0307 paid $250 via Upwork

@dukenv0307 can you propose the steps for the TestRail update? We def want one for the new feature. Thx

**Comment by Kicu** [comment]
The search feature is not yet fully complete so Im not sure how useful it is to write these test steps. Perhaps we should do these later?
For example:
> Go to Settings > Troubleshoot > New Search Page

This is not how the actual navigation will work, this is temporary for developing the feature.

**Comment by luacmartins** [comment]
As @Kicu said, no tests needed at this time. We'll add them as part of the project wrap-up.

**Comment by mallenexpensify** [comment]
Groovy, closing out then. Thx y'all.
