### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] [Search v1] Create SearchTableHeader 

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39876]
Section from [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.x0rjtlngp32a)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e5d2a642d33771a</li>
        <li>Upwork Job ID: 1780985200188256256</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on that :)

**Comment by luacmartins** [comment]
@WojtekBoman is still working on this

**Comment by luacmartins** [comment]
Still in dev

**Comment by luacmartins** [comment]
I'm merging the PR above since SWM will be ooo for the rest of the week and the functionality is not yet available to users. I'll continue to work on it myself in the meantime.

**Comment by hungvu193** [comment]
@luacmartins  Oh I saw you already find some C+ to review the PR, so I'm unassigning my self.

**Comment by anmurali** [comment]
I don't think there's any payment that needs to be issued here. Closing.
