### ISSUE TITLE
[Search v1] Implement Search API

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39884]
Section from [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.4jkab5ctnpqo)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f16884376f8d8a3a</li>
        <li>Upwork Job ID: 1780007317363838976</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
@danieldoglas I remember that you were interested in helping with the implementation for search. Would you like to work on this issue?

**Comment by grgia** [comment]
@luacmartins I could give this a go

**Comment by grgia** [comment]
@danieldoglas let me know if you wanted to take this or would want to collaborate- I want to improve my API commands and thought this could be a good one for that

**Comment by danieldoglas** [comment]
@grgia I've messaged Carlos 1:1 that I probably wouldn't be able to address this in the next 2 weeks. If you can tackle it before that, I can probably help if you need anything!

**Comment by grgia** [comment]
Sounds good @danieldoglas

**Comment by luacmartins** [comment]
PR in review

**Comment by ahmedGaber93** [comment]
I will unassign me here, as I do not think this issue needs C+

**Comment by luacmartins** [comment]
This is done and deployed.
