### ISSUE TITLE
[PAID] [Search v1] Create SearchFilters

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39881]
Section from [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.yz9gstkboxbh)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc6368382519c324</li>
        <li>Upwork Job ID: 1780007594458136576</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Kicu** [comment]
Hey, I'd like to work on this one :)

**Comment by strepanier03** [comment]
@dukenv0307 - I'll check tomorrow for the checklist item.

**Comment by strepanier03** [comment]
Thanks @dukenv0307 - handling the payment now.

**Comment by strepanier03** [comment]
Payment completed, contract ended, and title updated. 

Thanks everyone, closing out as complete now.
