### ISSUE TITLE
[$250] [HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Search v1] Add bulk actions

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39887]
Section from design doc - https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=kix.y89s328fm3hg

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b3d97d0f736da83</li>
        <li>Upwork Job ID: 1816074583769791992</li>
        <li>Last Price Increase: 2024-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103250608</li>
</ul></li>
    </ul>
</details>

**Comment by luacmartins** [comment]
On hold

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on it :)

**Comment by luacmartins** [comment]
@WojtekBoman this is still on hold since we're migrating some code in the API. Let's focus on other off-hold items for now.

**Comment by luacmartins** [comment]
Gonna move to monthly since this requires violations in Auth

**Comment by luacmartins** [comment]
@WojtekBoman we can get started with `Delete` here. We already send `canDelete` key to transactions.

**Comment by luacmartins** [comment]
I think we can also implement `Hold` and `Unhold` too. So the full list of actions to be implemented now are `Delete`, `Hold`, `Unhold`

**Comment by WojtekBoman** [comment]
![image](https://github.com/Expensify/App/assets/47774969/a4f473f8-a773-4ab2-8177-59d0dfc1e8c5)
@shawnborton Which icon should be displayed in the popover menu for the `Unhold` action?

**Comment by shawnborton** [comment]
It looks like we use the same icon for unhold. cc @Expensify/design for a gut check there though.

**Comment by dannymcclain** [comment]
>It looks like we use the same icon for unhold. cc @Expensify/design for a gut check there though.

Yeah that sounds right to me. Kinda like how we use the same icon for `Pin/Unpin`. We could revisit that in the future, but for now, I think it's fine to use the same icon.

**Comment by zanyrenney** [comment]
thanks @luacmartins

**Comment by zanyrenney** [comment]
Hm, "hired" leads nowhere and the upwork job link above links to this GH issue 🫠 
![2024-07-24_12-33-25](https://github.com/user-attachments/assets/60ddfedf-7a4a-449b-bead-113aece8f1f0)

**Comment by zanyrenney** [comment]
Hi @rayane-djouah please accept job invite: https://www.upwork.com/jobs/~010b3d97d0f736da83

**Comment by zanyrenney** [comment]
there you go!

**Comment by zanyrenney** [comment]
cc @rayane-djouah

**Comment by luacmartins** [comment]
Seems like this is paid out? Closing the issue. Please reopen if we're still missing something.

**Comment by zanyrenney** [comment]
hey @luacmartins this shouldn't have been closed until the payment summary is added and payment complete. the discussion above was about the job offer, not payout.

**Comment by zanyrenney** [comment]
**payment summary**

paid @rayane-djouah $250 via Upwork.
@WojtekBoman is a contractor so no payment is due.

**Comment by luacmartins** [comment]
Oops, my bad! 😓 We can reopen the issue if needed.
