### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] [Search v1] Implement sorting

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#39892]
Implement this section of the design doc - https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=kix.sjzpozsidr9q
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df1764b96ba68f02</li>
        <li>Upwork Job ID: 1791073930935115776</li>
        <li>Last Price Increase: 2024-05-16</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 102482315</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by luacmartins** [comment]
On hold

**Comment by luacmartins** [comment]
Taking off hold, we'll start implementation shortly.

**Comment by Kicu** [comment]
Hey I will be starting to work on this.

**Comment by Kicu** [comment]
Currently working on it

**Comment by Kicu** [comment]
asked a question about sorting here: https://github.com/Expensify/App/pull/42248#issuecomment-2117547853

**Comment by luacmartins** [comment]
The [current API PR](https://github.com/Expensify/Auth/pull/10916) is sorting the `from` and `to` columns by accountID, but we ultimately want to sort by `displayName` or `login` since that's what users would expect. I'll work on a follow up to add the additional logic for those columns, since that requires a change in the query.

Also, it seems like we need to support sorting by `type` and `action` too, which I'll handle in the follow up as well.

**Comment by Kicu** [comment]
how do you sort `Total` by?

**Comment by luacmartins** [comment]
We're coalescing the amounts, i.e. `COALESCE(t.modifiedAmount, t.amount)`

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JUNE 11

- Fix: @Kicu - no payment required
- PR Review: @c3024 [$250, if no regressions] [offer link](https://www.upwork.com/nx/wm/offer/102482315)

**Comment by abekkala** [comment]
@c3024 payment sent and contract ended - thank you! 🎉
