### ISSUE TITLE
Wallet - Offline indicator appears below the card and not the bottom of page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Paste the link https://staging.new.expensify.com/settings/wallet/add-bank-account-refactor

in chat.
3. Tap on the link.
4. Go offline.

## Expected Result:
The offline indicator will appear at the bottom of the page.

## Actual Result:
The offline indicator appears below the card instead of the bottom of the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6442665_1712601496986!IMG_3064](https://github.com/Expensify/App/assets/115492554/d728c8e8-df73-4cea-8c3d-02772b26e3a1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-bills.

**Comment by izarutskaya** [comment]
Production 

![Screenshot_20240409_104646_New Expensify](https://github.com/Expensify/App/assets/115492554/5dba4bf6-cd11-4bb1-8d96-33b7c05a37eb)

**Comment by Gonals** [comment]
Since this is a known issue being worked on on the follow-up, I'm going to close it for now.
