### ISSUE TITLE
Workspace - Page scrolls to top when you swipe up in the member invite "add message" page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4474741&group_by=cases:section_id&group_id=229065&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with an expensifail account
2. Create a workspace
3. Start inviting a member
4. Tap inside the "Message" textbox on the "Add message" tab
5. Swipe up

## Expected Result:
The page shouldn't scroll by itself.

## Actual Result:
Page scrolls to the top when you swipe up in the member invite "add message" page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6c1e0584-a019-44cc-b2dd-90b51fd4c820

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Android <> iOS swap with Kadie

**Comment by kadiealexander** [comment]
I actually don't think this is a bug, and it's certainly not a big enough bug to fix. Users can click "Done" to drop the keyboard and proceed.
