### ISSUE TITLE
Expense - Report field is not removed when deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36039
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has some report fields.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request.
4. Go to expense report.
5. Click on the report field > Add value > Save it.
6. On Old Dot, as admin, delete the report field in Step 5.
7. As employee, go to main chat and back to expense report (to receive update).
8. Click on the deleted report field.
9. Click 3-dot menu > Delete > Delete the field.

## Expected Result:
The report field will be removed

## Actual Result:
The report field is not removed. It is only removed after clearing cache and restart from Troubleshooting section.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6fc94f57-4eca-46e4-89bb-1b414fdc4512

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc85d44bb737c556</li>
        <li>Upwork Job ID: 1777733234423984128</li>
        <li>Last Price Increase: 2024-04-09</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
cc @allroundexperts @thie

**Comment by mountiny** [comment]
This is not a deploy blocker as report fields are not really used in NewDot by customers yet its a new feature for Newdot 

@allroundexperts @thienlnam could you help with this one?

**Comment by thienlnam** [comment]
I believe this has to do with the pusher updates from oldDot not getting prefixed with expensify_ . I can take this

**Comment by thienlnam** [comment]
The fix PR should be live now - need to retest
