### ISSUE TITLE
[HOLD for payment 2024-05-02] [Guided Setup] [Hold #39687] Web - Onboarding - highlight shows up around onboarding video when clicking volume button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39925]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Navigate to settings > About > Troubleshoot
3. Click on "Navigate" on "Onboarding Flow"
4. Input first name and last name
5. Click on "Continue"
6. Select a purpose and click on "Continue"
7. Click on the video to pause it and click on it again to play the video
8. Press on volume up and down buttons on keyboard

## Expected Result:
No highlight should be visible around the video

## Actual Result:
A highlight around the video becomes visible

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0861d4ad-aa27-4b03-b39d-b1605ecd288f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by godofoutcasts94** [comment]
This issue is not available until `esc` key is pressed.


https://github.com/Expensify/App/assets/158435970/98607ecd-7a78-442d-b717-e9b63d107f47

cc - @youssef-lr @kbecciv

**Comment by mountiny** [comment]
Not a blocker as this is not accessible for the new users, I am helping with this project now so taking over

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz from Software Mansion, the expert agency, and I will work on this issue.

**Comment by cdOut** [comment]
@mountiny  First of all this is not an issue with Onboarding itself, this exact bug also happens for every video attachment. I have fixed this styling issue in [this onboarding enable PR](https://github.com/Expensify/App/pull/39687).

**Comment by trjExpensify** [comment]
Put this on hold for that PR, once deployed the fix can be verified and then this issue closed.

**Comment by laurenreidexpensify** [comment]
Payment Summary

No external contractors engaged so no payments necessary
