### ISSUE TITLE
LHN - Public room disappears from LHN after opening a thread and navigating away

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39935]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4481714
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to a public room, e. g. https://staging.new.expensify.com/r/2652281908731856
3. Navigate to any other chat, note that the public room remains in LHN
4. Return to the public room
5. Open any thread
6. Navigate to any other chat

## Expected Result:
Public room should remain in LHN

## Actual Result:
Public room disappears from the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8982f5ec-7649-4b94-8e73-b39f0dcfbfb3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be0cfb5ce7163400</li>
        <li>Upwork Job ID: 1780589449496879104</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment]
Still waiting for proposals

**Comment by muttmuure** [comment]
https://expensify.slack.com/archives/C066HJM2CAZ/p1714127987228399

**Comment by muttmuure** [comment]
Still waiting for internal proposals

**Comment by muttmuure** [comment]
waiting for proposals

**Comment by muttmuure** [comment]
bumped VSB room: https://expensify.slack.com/archives/C066HJM2CAZ/p1715086192645379

**Comment by muttmuure** [comment]
Making this low

**Comment by muttmuure** [comment]
Waiting for proposals

**Comment by muttmuure** [comment]
Waiting for proposals

**Comment by muttmuure** [comment]
Seems like this isn't important enough to pick up
