### ISSUE TITLE
[HOLD for payment 2024-05-08] [Wave Collect] [Xero] Add Other Integrations and Xero section in the `WorkspaceAccountingPage`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#39955]
When adding support for Xero on the `WorkspaceAccountingPage`, do the following:

- Add back the Xero section
![Screenshot 2024-04-09 at 9 04 54 AM](https://github.com/Expensify/App/assets/98560306/2e903924-a490-4ee1-b57e-24e44cd987c9)

- [Add back the Other Integrations section](https://github.com/Expensify/App/pull/39652/commits/816bf44975d32918f79e03c7e4fa68c7b3412dc8)
![Screenshot 2024-04-09 at 9 03 53 AM](https://github.com/Expensify/App/assets/98560306/dfb40877-6bd6-4b91-a65b-6fd24b60e5d6)

**Comment by hayata-suenaga** [comment]
We're just creating this issue so we don't forget this task when adding Xero support to New Expensify.

**Comment by lakchote** [comment]
cc @SzymczakJ since you'll work on the Authorization flow

**Comment by lakchote** [comment]
@hayata-suenaga should we close this?

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga should we close this?

seems like the payment was handled in [this issue](https://github.com/expensify/app/issues/39725). closing this now 👍
