### ISSUE TITLE
Threads - a skeleton loader is not displayed when the user is offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39957]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** dave0123seife+adf54@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any conversation
2. Start a thread and send some messages
3. Disable the internet connection
4. Click on the three-dot menu and hit "Leave thread"
5. Click on the thread link to rejoin the thread
6. Notice that a skeleton loader is not displayed even if the user is offline

## Expected Result:
A skeleton loader is displayed when the user is offline

## Actual Result:
a skeleton loader is not displayed even if the user is offline. The thread messages are displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9228df82-65ab-4b39-b84a-9d95581d51b3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by abekkala** [comment]
vsb is on hold
