### ISSUE TITLE
[$250] [HOLD for payment 2024-05-02] [Guided Setup] Implement the Stage 1 onboarding flow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#39969]
Implementation issue for [the Onboarding Stage 1 project](https://github.com/Expensify/Expensify/issues/351581)

The design doc is here https://docs.google.com/document/d/1sxG_RV5HTFHgdCsJUDNpqSGs09W_OPLBKbNYQfu3FHw/edit. For more details on the implementation, please read the detailed section of the document.

<img width="1093" alt="image" src="https://github.com/Expensify/App/assets/36083550/cc429af6-17cd-409e-9dec-705bc4d3929b">

This is implemented by SWM.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbadd33848f9de2a</li>
        <li>Upwork Job ID: 1786398252777099264</li>
        <li>Last Price Increase: 2024-05-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by Julesssss** [comment]
Hey @francoisl @mountiny. FYI deploying this before the Auth PR caused [this issue](https://expensify.slack.com/archives/C049HHMV9SM/p1714470238207479) on prod and staging. It looked pretty bad for new users.

![Screenshot 2024-04-30 at 10 40 41](https://github.com/Expensify/App/assets/10736861/1170518f-3d56-4c94-9ca5-020f49af045b)

**Comment by joekaufmanexpensify** [comment]
@mountiny @francoisl @hoangzinh I see [this comment](https://github.com/Expensify/App/issues/39969#issuecomment-2075136654), was there a regression from this issue?

**Comment by joekaufmanexpensify** [comment]
Got it, thanks for confirming! In that case, only payment needed here is $250 to @hoangzinh for C+ review via upwork.

**Comment by joekaufmanexpensify** [comment]
@hoangzinh offer for $250 sent!

**Comment by joekaufmanexpensify** [comment]
For regression test, I don't think we need to add that here piecemeal. I see a whole suite of manual tests in the design doc for us to pass to applause.

**Comment by joekaufmanexpensify** [comment]
@hoangzinh $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
