### ISSUE TITLE
[HOLD for payment] [$250] Implement offline behavior and error handling for `UpdateGroupChatAvatar`

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#39983]
We are now able to add a custom Group chat avatar. However, we do not handle the failure case yet.

Let's take whatever we are doing for the Profile + Workspace pages and apply the same error handling here.

In the backend, we currently send exceptions like this:

```php
Onyx::handleException($e, 'AD9240FD-A780-425D-B98D-96DD6E4251C1', OnyxKeys::COLLECTION_REPORT.$reportID, ['errorFields', 'avatar']);
```

Which will put an error field on the report if updating the avatar fails.

We need that error to lead the user back to the avatar and display an error message back to the user.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015da074a9479d6afc</li>
        <li>Upwork Job ID: 1778152731149742080</li>
        <li>Last Price Increase: 2024-04-17</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by s77rt** [comment]
I'd like to work on this

**Comment by s77rt** [comment]
No longer on hold. https://github.com/Expensify/App/pull/39757 is merged. Will look into this asap

**Comment by marcaaron** [comment]
Thanks, removed HOLD here.

**Comment by s77rt** [comment]
Not overdue. Focused on QBO. Didn't get a chance to work on this yet

**Comment by marcaaron** [comment]
Sounds good! Thanks everyone. Let's goooo 🙇

**Comment by s77rt** [comment]
Not overdue. We have a draft PR

**Comment by s77rt** [comment]
Melvin, you were supposed to update the issue, didn't you used to say that issues have feeling too.

**Comment by nexarvo** [comment]
Hi @sonialiap, this was deployed to production a while ago. Can we proceed with payments here ?

**Comment by sonialiap** [comment]
@nexarvo thanks for the ping! Looks like automation didn't run here, sorry for the delay 🤖 

Payment summary:
- @s77rt review $250 - please request in ND (or do I need to pay in upwork because you were hired before 2024-05-24?)
- @nexarvo contributor $250 - offer sent in upwork

**Comment by s77rt** [comment]
@sonialiap This one is still via Upwork

**Comment by sonialiap** [comment]
@s77rt offer sent in upwork

**Comment by s77rt** [comment]
@sonialiap Accepted! Thanks!

**Comment by sonialiap** [comment]
Paid
