### ISSUE TITLE
[HOLD for payment 2024-04-25] GetMissinOnyxMessages being executed several times

### ISSUE THREAD

**Issue by danieldoglas** [Expensify/App#39992]
### Problem

When we have multiple tabs open on new dot, all of them receive pusher updates. That's causing confusion because we're trying to apply them all, so depending on the tab you are, you'll see that they were applied, or that we've skipped them because they were already applied (in another tab).
This is also a problem when you receive an update that you are not up to date. If that happens, we will trigger N calls to GetMissingOnyxMessages.
1. Alice's local lastUpdateID is 10, and she has 3 tabs open (A, B and C)
2. Alice receives updateID 11, with previousUpdateID 10
    a. Tab A receives it first, so it applied the update
    b. Tab B and Tab C will log Update received was older than or the same as current state, returning without applying the updates other than successData and failureData
3. Alice then receives update 15, with previousUpdateID 14
    a. All 3 tabs will receive that update
    b. All 3 tabs will call saveUpdateInformation after checking that the previousUpdateID do not match
    c. Because we execute the call for GetMissingOnyxUpdate on a [callback](https://github.com/Expensify/App/blob/1894dce37f80598288aa3b5a4d5950e5a2f7a2c2/src/libs/actions/OnyxUpdateManager.ts#L35-L103) of updates on the key ONYX_UPDATES_FROM_SERVER, and we updated that key 3 times on 3.b, each tab will call GetMissingOnyxUpdates 3 times (for a total of 9 calls to our servers)

We've solved issue 3.c on PR https://github.com/Expensify/App/pull/39943, but we were still doing 3 requests (because we triggered the call back 3 times).

### Solution

Only apply onyx updates from the main active client
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101c143b6e4d4468d</li>
        <li>Upwork Job ID: 1777976022050316288</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by allroundexperts** [comment]
Taking over!

**Comment by CortneyOfstad** [comment]
PR on staging as of last week — continuing to keep an eye on this!

**Comment by CortneyOfstad** [comment]
Not overdue — payment is set for tomorrow. 

@allroundexperts can you have the check list completed by EOD? Thanks!

**Comment by allroundexperts** [comment]
I don't think a checklist is needed here.

**Comment by CortneyOfstad** [comment]
This is set to be paid via NewDot 👍 

## Payment Summary

@allroundexperts — to be paid $250 via NewDot 👍

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
