### ISSUE TITLE
[HOLD for payment 2024-05-08] CRITICAL: [Invoice Rooms] Implement Invoice rooms with individual receivers in the App

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#40013]
# Part of the **Invoicing V0.1** project
Main issue: https://github.com/Expensify/Expensify/issues/341717
Doc section: [Invoicing V1 - Invoice Rooms](https://docs.google.com/document/d/1HhnjCVUVN8gw3vfxRA4jCXXQvuIfm1puMhzHoOKe5jY/edit#bookmark=id.e04jx95ffa8k)
Project: [#vip-billpay](https://join.slack.com/share/enQtNjkzNDU4NTI3OTY4Ni03M2RlY2IwNzhjMDEzMGE1NjZmYmM5MGJmZDZmNTc4NjRhYmRlOWM4NzMzYmJmOGUyZDAzNWFiNTgyNjQ0YTg0)

# Feature Description
Invoice rooms with individual receivers.

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
**Updates:**
1. Looks like I have finished with the invoice room UI. The app renders all the information in order with the doc.
2. Once the backend is ready, we probably have some frontend issues. Right now I use only optimistic data from https://github.com/Expensify/App/pull/40015.

**To do:**
1. Get done with nested pages.


<details><summary>Screenshot</summary>
<p>

<img width="1728" alt="Screenshot 2024-04-15 at 16 32 03" src="https://github.com/Expensify/App/assets/57314631/9ceb2050-d0b9-41f9-b7a7-2e92cb2cc8a2">


</p>
</details>

**Comment by cristipaval** [comment]
@rezkiy37 Could you please post an update here?

**Comment by rezkiy37** [comment]
**Updates:**

1. Updated title and subtitle logic to render accordingly with the doc.
2. Refactor changes.
3. Other monir changes.

**To do:**

1. Test with the backend.
2. Polish.

**Comment by rezkiy37** [comment]
Also, we are waiting for the backend fixes.

**Comment by cristipaval** [comment]
WIP. waiting for the next Auth deploy

**Comment by rezkiy37** [comment]
The [PR](https://github.com/Expensify/App/pull/40303) has been opened for review.

**Comment by rezkiy37** [comment]
Hey!
I just wanted to let you know about my vacation for next week. I will be back on 06.05.2024. Meanwhile, I asked @waterim to take over this issue. 
See you soon!

**Comment by danielrvidal** [comment]
@waterim what is the plan for this one? I was not sure if this one should be getting worked on or not.

**Comment by danielrvidal** [comment]
Aw, actually is this just a holding issue for the whole project? So there are a lot of things still being done so this is open.

**Comment by davidcardoza** [comment]
@cristipaval What is this issue being used for?

**Comment by cristipaval** [comment]
This was part of the implementation phase of the project. The work has been merged but it is still open for the C+ payment.

**Comment by davidcardoza** [comment]
Ah okay, thanks that's helpful.

**Comment by rezkiy37** [comment]
I am proposing regression test steps today.

**Comment by rezkiy37** [comment]
**Regression Test Proposal**

1. Send an invoice.
2. Open an invoice report room.
3. Verify that the room and its actions look properly.
4. Click on an invoice report preview.
5. Verify that the invoice report looks properly.

Do we agree 👍 or 👎

**Comment by cristipaval** [comment]
Assigned @rushatgabhane as the C+ who reviewed [the PR](https://github.com/Expensify/App/pull/40303)

**Comment by rushatgabhane** [comment]
@kevinksullivan could you please attach payment summary 🙇

**Comment by cristipaval** [comment]
@kevinksullivan, @rushatgabhane is the only contributor to pay here, for the C+ review

**Comment by kevinksullivan** [comment]
Payment summary: 
- @rushatgabhane $250

**Comment by rushatgabhane** [comment]
@kevinksullivan should this be $500 because critical?

**Comment by kevinksullivan** [comment]
ah yes, sorry about that. Updated

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
