### ISSUE TITLE
[$500] [HOLD for payment 2024-05-08] CRITICAL: [Send invoice] Implement Send Invoice flow from Global Create

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#40012]
# Part of the **Invoicing V0.1** project
Main issue: https://github.com/Expensify/Expensify/issues/341717
Doc section: [Invoicing V1](https://docs.google.com/document/d/1HhnjCVUVN8gw3vfxRA4jCXXQvuIfm1puMhzHoOKe5jY/edit#bookmark=id.vt7p1qu0fowf)
Project: [#vip-billpay](https://join.slack.com/share/enQtNjkzNDU4NTI3OTY4Ni03M2RlY2IwNzhjMDEzMGE1NjZmYmM5MGJmZDZmNTc4NjRhYmRlOWM4NzMzYmJmOGUyZDAzNWFiNTgyNjQ0YTg0)

# Feature Description
Send Invoice from Global Create

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e31d2e6653cca734</li>
        <li>Upwork Job ID: 1788335672367525888</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
**Updates:**
- Updated IOU steps to support invoices flow: start, participants, confirmation.
- Implemented a new `Send from` screen to support invoice sender updates.
- Implemented building of optimistic data for `SendInvoice` api request, as well as preparing params/onyx updates, but it's not tested yet

**TODOs:**
- Resolve some left TODOs
- Fix lint and TS issues
- Improve invoice room chat creation (still need a final decision regarding receiver info storage)
- Do UI improvements
- Test the flow in different scenarios on different platforms and make improvements where necessary

<details>
<summary>Screenshots/recordings</summary>

https://github.com/Expensify/App/assets/23176449/d98a04cd-f9cd-4ddb-87c5-5f3a00f05bd2


</details>

**Comment by VickyStash** [comment]
**Updates:**
- resolved TS-related issues
- fixed invoice creation from global create in case invoice room report for sender/receiver already exists
- implemented function for invite report action optimistic building
- resolved left TODOs for send invoice functionality
- tested functionality on web using offline mode

**TODOs:**
- confirm all Spanish translations
- fix lint issues
- do UI improvements
- test the flow in different scenarios on mobile platforms and make improvements where necessary
- check the implementation using staging API endpoints (can be done when API is deployed)

**Comment by VickyStash** [comment]
**Updates:**
- Enabled receipt file attachment
- Conflicts resolution / ts fixes/ lint fixes
- UI improvements
- Confirmed and fixed Spanish translations internally
- Fix report preview message
- Started to prepare PR for review

**TODOs:**
- Fix `canSendInvoice` check
- Test the flow in different scenarios on mobile platforms and make improvements where necessary
- Check the implementation using staging API endpoints (can be done when API is deployed)
- Prepare PR for review

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, April 23, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by VickyStash** [comment]
**Updates:**
- Fixed the invoice creation if there is no chat with the receiver
- Updated optimistic invoice room creation to include the current user as a member
- TS fixes and code improvements

**TODOs:**

- Test the flow in different scenarios on mobile platforms and make improvements where necessary
- Check the implementation using staging API endpoints _(can be done when API is deployed)_
- Open PR for review

**Comment by VickyStash** [comment]
**Updates:**

- Updated param invoiceRoomID -> invoiceRoomReportID
- Resolved conflicts and did updates to follow main branch changes (MoneyTemporaryForRefactorRequestConfirmationList.tsx got removed, and participants logic changed a little )
- Tested API updates

**TODOs:**

- Waiting for API fixes to be able to progress PR

**Comment by danielrvidal** [comment]
Are we still waiting on API fixed for this one? If so, could we link them here? I saw the PR linked above was merged, woo!

**Comment by cristipaval** [comment]
> Are we still waiting on API fixed for this one? If so, could we link them here? I saw the PR linked above was merged, woo!

This issue will be closed when the PR hits production. We have different issues for API fixes we need.

**Comment by alexpensify** [comment]
@shubham1206agra - please accept the Upwork invite and I can complete the payment process. Thanks!

**Comment by alexpensify** [comment]
Thanks! I've completed the payment process in Upwork and am going to close this GH now.

**Comment by Krishna2323** [comment]
Heads up: the send-invoice flow implemented here caused #97203. `receiverEmail` was sent as a raw phone number, never normalized with `addSMSDomainIfPhoneNumber()` like every sibling flow does, so the backend rejected it with `Invalid invoice receiver` and the invoice room got stuck on a skeleton loader. Fixed in #100892.
