### ISSUE TITLE
[HOLD for payment 2024-04-25] Chat - Not here page shows up when deleting message after returning from thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40027]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Send a message
4. Right click on the message > Reply in thread
5. Click on the header subtitle link
6. Delete the message

## Expected Result:
App will not show not here page

## Actual Result:
App shows not here page. (until it returns to the same chat with the comment undeleted because of another known issue)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a67f1e46-88fb-48c1-a258-c30e04223ea1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@blimpich  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Not here page shows up when deleting message after returning from thread
### What is the root cause of that problem?
After deleting `reportAction` we stay on a  URL which contains deleted reportAction ID
### What changes do you think we should make in order to solve the problem?
Add `Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(reportID))` after deleting comment


### What alternative solutions did you explore? (Optional)

**Comment by blimpich** [comment]
Not a deploy blocker. This seems to be an unhandled edge case from https://github.com/Expensify/App/pull/39454. When I revert that PR it isn't an issue. @rushatgabhane @rayane-djouah @jasperhuangg can you handle this as part of your work on https://github.com/Expensify/App/issues/38979?
