### ISSUE TITLE
Track expense - Track distance expense does not show up in self DM

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39190
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Self DM has no previous track expenses.
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Go to + > Track expense.
4. Go to Distance tab.
5. Create track distance expense.

## Expected Result:
The track distance expense will show up in self DM.

## Actual Result:
The track distance expense does not show up in self DM, but it shows preview in LHN.
This issue only happens when there is no track expense in the self DM. The missing distance request reappears after creating the second request.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f6a7bfa5-2f3a-48be-b917-1a619cf187b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment]
cc: @neil-marcellini since it looks like this is a result of https://github.com/Expensify/App/pull/39190

**Comment by NikkiWines** [comment]
Looks like adding a second track expenses results in both track expenses showing in the self-DM. Regardless this looks like it's currently behind a beta, so going to remove the blocker label.

**Comment by neil-marcellini** [comment]
I'll take this over since it _might_ be related to my PR. It sounds like that PR above fixed this. I'll test on staging now.

**Comment by neil-marcellini** [comment]
Yep, fixed. Thanks @paultsimura! 

https://github.com/Expensify/App/assets/26260477/6e868654-4274-4bd1-a092-4237bd76bfee
