### ISSUE TITLE
[$500] Workspace room should be discoverable to all workspace members via Search, regardless of individual room membership

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40031]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712672898210429

## Action Performed:

1. Open mobile app
2. Click FAB
3. Click Start chat
4. Click Room
5. Create a new room under a policy others have access to
6. On web, login to [staging.new.expensify.com](http://staging.new.expensify.com/) as another workspace member
7. Click Search
8. Type in new room you created in step 5
9. Verify it doesn’t show as a result

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2024-04-09 at 3 34 02 PM](https://github.com/Expensify/App/assets/38435837/17253430-e4bf-4d4c-a2db-986d3c78aa23)

![Screen Shot 2024-04-09 at 9 19 35 PM](https://github.com/Expensify/App/assets/38435837/d0aeae2e-0431-47ad-886f-216fc573f8d5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd8f31492681e749</li>
        <li>Upwork Job ID: 1778400415914618880</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by twisterdotcom** [comment]
https://github.com/Expensify/App/assets/9133401/5e62fca4-abd9-4356-b415-05c7a33a2b1d

**Comment by twisterdotcom** [comment]
Still awaiting proposals. No status given yet from the project, so we'll leave this without a bump for now.

**Comment by eVoloshchak** [comment]
Not overdue, this is still awaiting proposals

**Comment by twisterdotcom** [comment]
Still waiting on proposals. Gonna double as this is a real useful thing.

**Comment by kmbcook** [comment]
SearchForReports API call doesn't return the report.

**Comment by twisterdotcom** [comment]
Hi @kmbcook - if you have a solution please complete the proposal template mentioned here: https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by kmbcook** [comment]
@twisterdotcom I was just trying to say that the backend isn't returning the required information.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by twisterdotcom** [comment]
@eVoloshchak could I have your opinion to back up @kmbcook here please, and if so, I'll set this as `internal`.

**Comment by twisterdotcom** [comment]
Ah, whatever, it does work now.
<img width="678" alt="image" src="https://github.com/Expensify/App/assets/9133401/b4873fbf-a016-4a95-b449-febdbc0ba89e">
