### ISSUE TITLE
[$500] Thread - Message sent after returning from thread is not shown after refreshing the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39454
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Send a message.
4. Right click on the message > Reply in thread.
5. Click on the header subtitle.
6. Send a message back in the main chat.
7. Refresh the page.

## Expected Result:
The message sent in Step 6 will appear in the chat history.

## Actual Result:
The message sent in Step 6 does not appear in the chat history after refreshing the page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/07c73f75-3713-4295-adb7-1f1ba3999d43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019444184000784869</li>
        <li>Upwork Job ID: 1780314828568719360</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Julesssss** [comment]
Possibly introduced by [this PR](https://github.com/Expensify/App/issues/40041)

**Comment by kbecciv** [comment]
Issue is still reproducible on Windows/Chrome, build 1.4.64.11

https://github.com/Expensify/App/assets/93399543/1ec64736-ec07-491f-9dcc-4fcb7489cdbd

**Comment by thienlnam** [comment]
We still are having trouble reproducing this in this thread - going to go ahead and close https://expensify.slack.com/archives/C01GTK53T8Q/p1713295362543849. We can address if we run into this again
