### ISSUE TITLE
Web - Accounting - Multiple functions in the Accounting page are non responsive

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40035]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to Collect Workspace > Click on it > More Features > Enable Accounting
4. Toggle the 3 dot menus on the Accounting page and interact with the functions

## Expected Result:
All functions should be available

## Actual Result:
Multiple functions do not respond to clicks

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a192828e-3efb-492f-8126-1d1202a37651

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by deetergp** [comment]
Confirmed that this is behind a beta, so removing the blocker label.

**Comment by narefyev91** [comment]
> I'm pretty sure this is related to #38400. I suspect it's still probably behind a beta and have reached out to @hayata-suenaga to inquire.

Hey @deetergp ! This issue is not related to 38400. 38400 Introduced sub pages for accounting and not the main page

**Comment by hayata-suenaga** [comment]
checking if the accounting screens are accessible to users who are NOT on the beta list.

**Comment by hayata-suenaga** [comment]
I confirmed that the accounting pages are not accessible to users NOT on the beta list.

I have [instructed](https://expensify.slack.com/archives/C9YU7BX5M/p1712854702433059) Applause to avoid testing features on the accounting pages until test cases are added to TailRail.
