### ISSUE TITLE
[$250] Track expense -Track distance preview in self DM does not show green thumbnail in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40039]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go offline
4. Create a distance request
5. Note that the preview in the main chat shows a green thumbnail
6. Go to self DM
7. Create a track distance request

## Expected Result:
The track distance request preview in the main self DM chat will show green thumbnail, same as workspace chat

## Actual Result:
The track distance request preview in the main self DM chat shows map unavailable icon instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/89e06be8-9157-4ccb-ae40-d847645ac118

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e46a156341b3749</li>
        <li>Upwork Job ID: 1778179488045215744</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by marcochavezf** [comment]
This is a new feature since track expense in self DM doesn't exist in production

<img width="1433" alt="Screenshot 2024-04-10 at 3 51 21 p m" src="https://github.com/Expensify/App/assets/6829422/ed38547b-245a-49ae-b2d2-e586126b6027">

**Comment by thienlnam** [comment]
Not sure if we need to change anything here - @neil-marcellini Do you happen to know why the thumbnails are different?

**Comment by thienlnam** [comment]
Cool, will close then
