### ISSUE TITLE
[Mentions v2] Refactor GetPersonalDetailsByAccountIDs

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#40032]
While working on https://github.com/Expensify/Auth/pull/10459 I noticed that [GetPersonalDetailsByAccountIDs](1ff7/auth/lib/Account.cpp#L2589) has gotten a little confusing. 

Specifically, I think the report logic is confusing in there. I think we should split this function up into: 
- GetPersonalDetailsForReportParticipants
    - This will have the report logic and be used specifically when you want to get personal details of report participants 
- GetPersonalDetailsByAccountIDs
    - This will be more general purpose and will just have the logic to get the details about the requested people

**Comment by nkdengineer** [comment]
Can this task be open for contributors?

**Comment by puneetlath** [comment]
Haven't gotten to this yet.

**Comment by puneetlath** [comment]
Not yet. Still working on base implementation.

**Comment by puneetlath** [comment]
There is no hurry on this. Will try to get to it this week.

**Comment by puneetlath** [comment]
I don't think this is really necessary, so going to close this out.
