### ISSUE TITLE
CRITICAL: [Actionable Whispers] Incorrect amount in paid message in LHN when there is tracking and request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40042]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** no  new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat with no request history.
3. Create a track manual expense ($10) with merchant A.
4. Create a $5 manual request (not track expense) with merchant B.
5. Go to expense report.
6. Submit and approve the report
7. Pay elsewhere the report.

## Expected Result:
In Step 6, the approval message should show the correct amount.
In Step 7, the system message for payment should show the correct amount in LHN preview.

## Actual Result:
In Step 6, the approval message shows the total amount first ($15), then changes to the correct amount ($5).
In Step 7, the system message for payment should $15 in LHN, while it shows $5 in the expense report.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/6fe3716d-4f86-4cce-8865-00d3ad3d01ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014206f890a94df05c</li>
        <li>Upwork Job ID: 1778171219909632000</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thienlnam</details>

**Comment by m-natarajan** [comment]
@cead22 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by thienlnam** [comment]
Not a blocker, requires a BE change to ensure we send back the total not just the reimbursable total

**Comment by trjExpensify** [comment]
`Track expense` is a #vip-vsb project, moving it over.

**Comment by laurenreidexpensify** [comment]
@thienlnam are you taking on this issue as the BE engineer?

**Comment by thienlnam** [comment]
Yup, taking this on

**Comment by thienlnam** [comment]
Tying together with https://github.com/Expensify/App/issues/40266

**Comment by thienlnam** [comment]
Held on https://github.com/Expensify/App/issues/40266

**Comment by thienlnam** [comment]
Still held on https://github.com/Expensify/App/issues/40266 - if we could find an internal engineer to take that, that would be great

**Comment by quinthar** [comment]
is this still held if #40266 is no longer reproducible?

**Comment by thienlnam** [comment]
Should be resolved now
