### ISSUE TITLE
Android - Chat - Composer is not responsive after tapping on the composer

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40040]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to chat.
3. Tap on the composer.

## Expected Result:
The text cursor in the composer will blink and typing anything on it will be responsive.

## Actual Result:
The text cursor in the composer does not blink and typing anything on it does not show response.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fc095b91-8e72-496a-91e2-f7f143a172b0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by AndrewGable** [comment]
I tried reproducing on this same version on my Pixel 3 and could not reproduce. Does it happen every time for this user and across all Android devices?

**Comment by kbecciv** [comment]
Tester device is Samsung Galaxy z fold 4, Android 14

**Comment by AndrewGable** [comment]
@kbecciv Does it happen every time for this user and across all Android devices?

**Comment by kbecciv** [comment]
@AndrewGable Checking

**Comment by roryabraham** [comment]
I was able to reproduce this on dev with a Pixel 4a

**Comment by AndrewGable** [comment]
Can't reproduce on my Pixel 7a either 🤔 


https://github.com/Expensify/App/assets/2838819/be5d6c52-9938-4e55-ab11-734ef4a5e08c

**Comment by roryabraham** [comment]
https://github.com/Expensify/App/assets/47436092/4d26293f-620d-4892-8d34-e63e890cadc0

**Comment by roryabraham** [comment]
not much of a hint but I notice that when this happens (which is 100% of the time for me), the cursor doesn't blink like it normally does

**Comment by jnowakow** [comment]
Hello, I’m from Software Mansion, I’d like to work on this job

**Comment by kbecciv** [comment]
Issue is still reproducible

https://github.com/Expensify/App/assets/93399543/620990c8-7a4a-4e72-ba1f-90e12ee15704

**Comment by AndrewGable** [comment]
Seems like this could be related to New Arch + gyroscope animations, we are investigating here: https://expensify.slack.com/archives/C05LX9D6E07/p1713283087444259?thread_ts=1713050865.385749&cid=C05LX9D6E07

**Comment by WoLewicki** [comment]
Could you check if https://github.com/Expensify/App/pull/40302 solves the problem?

**Comment by AndrewGable** [comment]
@roryabraham confirmed https://github.com/Expensify/App/pull/40302 fixed this
