### ISSUE TITLE
[HOLD #40266] Track - LHN and expense preview show incorrect info when there is tracking and request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40043]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #39239
**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat with no request history. 
3. Create a track manual expense ($10) with merchant A > click Track Expense (to create the expense)
4. Create a $5 manual request (not track expense) with merchant B > click the Request button (to create the expense)
5. Create a second track manual expense ($5) with merchant C > click Track Expense (to create the expense)
6. Click on the expense preview.
7. Return to the main workspace chat.

## Expected Result:
In Step 5, after creating the second track manual expense, the LHN preview will show the total amount of the report.
In Step 7, the expense preview will show "3 requests".

## Actual Result:
In Step 5, after creating the second track manual expense, the LHN preview only shows the amount of second track expense.
In Step 7. the expense preview shows the merchant of the first request.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/eaea8533-7c7a-4b7c-8802-90f3460c91d4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017264c636107b6770</li>
        <li>Upwork Job ID: 1778474804893405184</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Not a blocker as this is a new feature related to track

**Comment by m-natarajan** [comment]
@thienlnam FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by Christinadobrzyn** [comment]
I can recreate with the steps in the OP. @neil-marcellini can you check to see if this needs to be Interal or External?

**Comment by thienlnam** [comment]
I'm fixing some other report total calculations in https://github.com/Expensify/Auth/pull/10494, which may actually also end up fixing this bug

**Comment by neil-marcellini** [comment]
Cool thanks Jack. I'm going to mark it internal and assign it over to you for now. We might need frontend changes too but I'll wait until you determine that after the backend PRs.

If you need to and there are more changes required, you can re-assign me.

**Comment by trjExpensify** [comment]
Why was this one put in #wave-collect? `Track expense` is a #vip-vsb initiative.

**Comment by Christinadobrzyn** [comment]
Ah sorry @trjExpensify I though this was wave collect since it deals with expenses and not just chat. I'll review the initiatives again to make sure I'm on the right page. thanks for moving it over.

**Comment by thienlnam** [comment]
Tying together with https://github.com/Expensify/App/issues/40266

**Comment by thienlnam** [comment]
Held on https://github.com/Expensify/App/issues/40266

**Comment by Christinadobrzyn** [comment]
I'm going to move this to weekly since it will be combined with https://github.com/Expensify/App/issues/40266

Let me know if you think this should stay daily - @thienlnam

**Comment by thienlnam** [comment]
Should be resolved now
