### ISSUE TITLE
Task - When returning from task, yellow highlight is visible

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to any chat, create a task, click on the task
4. Return to the main chat from the task header
## Expected Result:
User expects the task to be highlighted in a light grey as occurs in other areas of the app, for example when inviting a new member to the workspace
## Actual Result:
There is a strong yellow highlight on the Task

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a3a85846-719e-42f1-b520-0be1fd1c5333

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
I think this is intentional, since you linked back to the task. Seeing this I'm more convinced that the yellow highlight should be temporary, not permanent though.
