### ISSUE TITLE
[$250] Android - Sign out - App flickers when signing out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40056]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: device theme is set to light
1. Open the app and log in
2. Navigate to account settings
3. Sign out

## Expected Result:
There is no flickering after signing out

## Actual Result:
The app flickers when user signs out and lands on the login page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/99bf5ff0-8cc3-4581-be24-9c43124fc04b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192055c374c786daf</li>
        <li>Upwork Job ID: 1778236549191127040</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@robertjchen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by robertjchen** [comment]
Not a deploy blocker, but definitely something UI-related that we could fix. Opening for `External` contributors 🙏

**Comment by robertjchen** [comment]
Pending proposals

**Comment by robertjchen** [comment]
Closing this out for now, not sure if it's worth to address at the moment.
