### ISSUE TITLE
Chat-In compose box, emojis displayed are cut off in top.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40053]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:*(https://expensify.testrail.io/index.php?/tests/view/4489664)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Tap emoji picker and select an emoji(any simileys round shaped select it so issue will be visible easily)

## Expected Result:
In compose box, emojis displayed must not cut off in top

## Actual Result:
In compose box, emojis displayed are cut off in top

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/81eac5a8-4819-4b6c-85bb-d69beef5e59b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Julesssss** [comment]
Likely live markdown related, and relatively minor. I'm going to demote from a deploy blocker while we fix this.

**Comment by thienlnam** [comment]
This is known - we have an existing issue here https://github.com/Expensify/App/issues/39274
