### ISSUE TITLE
Android - The error message "Hmm... it's not here" appeared twice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40052]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** shussain+accoun1@applausemail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39788
## Action Performed:
1. Open Expensify app
2. Open that link "staging.new.expensify.com/a/asd" from other app (Whatsapp/Slack)
3. Press back
4. Verify LHN is shown instead of report screen

## Expected Result:
Error should be displayed only once

## Actual Result:
The error message "Hmm... it's not here" appeared twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2a01060f-5043-4a55-a0ef-0e8646dc9e54

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Julesssss** [comment]
Given that valid deep links work as expected, I'm demoting this from a blocker.

**Comment by marcaaron** [comment]
I'm gonna close this as it is not really a "normal" action for a user to take and not worth prioritizing right now.
