### ISSUE TITLE
[HOLD for payment 2024-04-25] Chat - Previous messages jump continuously when opening the native emoji keyboard

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40076]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4490682
**Email or phone of affected tester (no customers):** gatantm@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open any chat
2. Tap on the composer to open the keyboard
3. Tap on the emoji keyboard on the native iOS keyboard (If issue is not reproducible change the iOS settings > Screen > Text Size to another value and repeat. Seems to affect different text sizes on different screen sizes)

## Expected Result:
The native emoji keyboard appears without issues for the chat screen

## Actual Result:
The native emoji keyboard appears and the previous messages jump up and down until the keyboard is dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7b88e078-a861-4699-99d6-616d090f1278

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@slafortune I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/5ea7e6b9-f49e-40c5-b193-6579c4c018f9

**Comment by Julesssss** [comment]
I can't reproduce on Android mWeb on native, but if reproducible on typical iPhones we should keep the blocker label.

**Comment by madmax330** [comment]
@suneox were you able to find an offending PR?

**Comment by madmax330** [comment]
Ah ok perfect, thanks. Ok you can make the fix, I assigned you the issue

**Comment by slafortune** [comment]
@madmax330 @suneox I will be out until 4/22, not assigning another BZ since this is in a good place for you all to keep it moving forward 👍

**Comment by thienlnam** [comment]
CPed this PR, waiting for it to deploy

**Comment by ikevin127** [comment]
@slafortune I also require payment here as C+ for reviewing PR https://github.com/Expensify/App/pull/40201, see https://github.com/Expensify/App/pull/40201#pullrequestreview-2002181808.

**Comment by slafortune** [comment]
@ikevin127 please accept the offer sent here - https://www.upwork.com/nx/wm/offer/102036690

@suneox Can you please complete the checklist as well as share your Upworks profile here?

**Comment by ikevin127** [comment]
> @ikevin127 please accept the offer sent here - https://www.upwork.com/nx/wm/offer/102036690

@slafortune Offer accepted, thank you!

**Comment by madmax330** [comment]
Not overdue

**Comment by ikevin127** [comment]
> @slafortune Offer accepted, thank you!

Bump on this, when you get the chance. Thanks again!

**Comment by slafortune** [comment]
Thanks @suneox  - offer sent

**Comment by slafortune** [comment]
@ikevin127 Paid

**Comment by slafortune** [comment]
@suneox - Paid ✅
