### ISSUE TITLE
[ON HOLD PAYMENT 4/29][$250] BA - Missing "Routing number" and "Account number" title after revisiting Bank info page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40082]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > any workspace.
3. Go to Workflows.
4. Go to Connect bank account.
5. Enter both routing and account number > Next.
6. Tap Next on confirmation page.
7. Tap Back button on the top left.

## Expected Result:
"Routing number" and "Account number" title will not disappear.

## Actual Result:
"Routing number" and "Account number" title disappears after revisiting Bank info page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/aa7ffdcc-0a77-4e99-be37-90374950eae8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190119f6b1d854619</li>
        <li>Upwork Job ID: 1778353045189038080</li>
        <li>Last Price Increase: 2024-04-11</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 

https://github.com/Expensify/App/assets/115492554/58f28fd9-b302-4edf-9a63-ebd9059897a5

**Comment by Julesssss** [comment]
Not a blocker. Solution sounds good to me. But I'm going OOO. Will be back Monday 22nd to review

**Comment by Julesssss** [comment]
> And its bg color hide the label so we don't see the label

@tienifr if the colours are set correctly, I don't see why the text is hidden beneath the inputText (in the z axis). Or is the input component built up of multiple components?

**Comment by CortneyOfstad** [comment]
PR is still being reviewed — will continue to keep an eye on this!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@paultsimura — paid $250 via Upwork
@tienifr — paid $250 via Upwork
