### ISSUE TITLE
[TS migration] Migrate `ProfileAvatarWithIndicator.js` component to TypeScript

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#40089]
# TypeScript migration

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files

- src/pages/home/sidebar/ProfileAvatarWithIndicator.js

**Comment by fabioh8010** [comment]
This issue is internal and will be handled by TS migration team.

**Comment by kubabutkiewicz** [comment]
Hi, I'm Jakub from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by MahmudjonToraqulov** [comment]
Let me work on it

**Comment by roryabraham** [comment]
PR was merged - C+ review by @allroundexperts

**Comment by blazejkustra** [comment]
We can close this issue, PR was merged a while ago.

**Comment by blazejkustra** [comment]
Actually I think @allroundexperts is awaiting payment on this one.

**Comment by miljakljajic** [comment]
Posting a payment summary:

@allroundexperts is owed 250 USD for their work reviewing. They'll request payment in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
