### ISSUE TITLE
Save the world - Back button opens Save the world page with chat LHN instead of menu list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile > Save the world > I know a teacher.
3. With RHP open, refresh the page.
4. Dismiss the RHP.
5. Click browser back button.

## Expected Result:
App will reopen Save the world page with menu items on the left side bar.

## Actual Result:
App reopens Save the world page with LHN instead of menu items from Settings.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/df863b4e-190e-4137-aba1-c8740ef0f700

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by puneetlath** [comment]
Marking as not a blocker as it seems like a very, very niche flow.

**Comment by puneetlath** [comment]
I don't think this is worth worrying about right now, so going to close. Feel free to comment or reopen if you disagree.
