### ISSUE TITLE
[HOLD for #39198] Chat - Chat does not scroll to the latest messages when new message sent

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4488827&group_by=cases:section_id&group_order=asc&group_id=306202
**Email or phone of affected tester (no customers):** applausetester+omq1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: User should be Signed Out
1. Open app
2. Sign In with account where at least one chat with long history
3. Tap on the chat with a long history (Chat should be Uncached)
4. Scroll to the very top
5. Send a message to the chat
6. Return to LHN
7. Tap on the same chat from step 3 again
8. Repeat steps 4-5

## Expected Result:
Chat should be scrolled to latest messages when user sent a new message

## Actual Result:
The chat does not scroll to the bottom when the user sends a message in step 5. However, when the user navigates to the LHN and then returns in step7-8, the chat scrolls to the bottom after the message is sent. This issue occurs when the user navigates to an uncached chat after signing in.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5f772ee0-393c-43d0-9541-314d13cdffef

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment]
This issue maybe fixed in this PR https://github.com/Expensify/App/pull/39685.

**Comment by greg-schroeder** [comment]
Agreed, I'll hold this until then and this may be resolved

**Comment by greg-schroeder** [comment]
PR was deployed to prod, will ask QA to retest

**Comment by greg-schroeder** [comment]
Pinged QA

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by greg-schroeder** [comment]
closing per QA review
