### ISSUE TITLE
[$250] iOS - Chat - Inconsistency in sending attachments offline when you come back online.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40093]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4488629
**Email or phone of affected tester (no customers):** vdargentotest+ios041024@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
Pre-requisite: the user must be logged in.

1. Go to any chat.
2. Disable the internet connection.
3. Send an image.
4. Verify "Uploading attachment..." message appears and is grayed out.
5. Kill the app.
6. Enable the internet connection.
7. Open the app and go to the same chat.
8. Verify "Uploading attachment..." message is no longer grayed out, but the attachment is never sent.
9. Send another attachment.
10. Verify the last attachment is sent but the rest of the chat is replaced by a loading skeleton and is no longer accessible.

## Expected Result:
When coming back online and reopening the app, the attachment should be sent.

## Actual Result:
The attachment sent while offline is not sent after re-opening app when back online. Also, if another attachment is sent, the rest of the chat is replaced by a loading skeleton.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/03eb3c26-c8bd-4350-9b5b-abb0994fea12

[Bug6445168_1712826823391!Profile_trace_for_1.4.62-0.cpuprofile](https://github.com/Expensify/App/files/14944127/Bug6445168_1712826823391.Profile_trace_for_1.4.62-0.cpuprofile)

[Bug6445168_1712826851957!logs-2024-04-11_09_10_59.286.txt](https://github.com/Expensify/App/files/14944138/Bug6445168_1712826851957.logs-2024-04-11_09_10_59.286.txt)
[Bug6445168_1712826841139!App_Info_1.4.62-0.json](https://github.com/Expensify/App/files/14944139/Bug6445168_1712826841139.App_Info_1.4.62-0.json)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013405544bf82d5dde</li>
        <li>Upwork Job ID: 1781363043681558528</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@twisterdotcom I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/8e39a886-9fec-4d37-bf39-f4bf1c2f4782

**Comment by twisterdotcom** [comment]
I don't think this is an issue right? Here's my recreation where it did upload when I came back online:

https://github.com/Expensify/App/assets/9133401/95e29401-0fcb-4b96-b77f-1432465935e4

Going to remove as a blocker and close.

**Comment by kbecciv** [comment]
Reopening the issue for second chance, QA team is able to reproduce it on build 1.4.63.0

https://github.com/Expensify/App/assets/93399543/e77ba989-1100-45fb-8cea-313d3a062826

**Comment by twisterdotcom** [comment]
Okay I see this now. I think we basically need to have better error messaging around when a file is completely dropped from uploading or fails uploading.

https://github.com/Expensify/App/assets/9133401/7b0ced9a-42d1-4e46-9e86-e75e73bc0917

**Comment by twisterdotcom** [comment]
Slack is really good at this actually:

https://github.com/Expensify/App/assets/9133401/31d68f3a-6bd4-4318-bfaf-9e79f0211bed

**Comment by twisterdotcom** [comment]
Gonna go external, but maybe this could be internal.

**Comment by twisterdotcom** [comment]
@MonilBhavsar or @shubham1206agra at the least, I'd be intrigued for your take on `External` or `Internal` here.

**Comment by MonilBhavsar** [comment]
Curious then why it only happens for iOS

**Comment by twisterdotcom** [comment]
Okay, gonna make it Internal and VSB for now. But, pretty low stakes atm.

**Comment by twisterdotcom** [comment]
Still very low. Not even assigned a status yet.

**Comment by twisterdotcom** [comment]
At this point, I think we can punt.
