### ISSUE TITLE
[HOLD] Local notifications on mobile devices

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#4010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Receive a message on a iOS or Android device while Pusher is connected.

## Expected Result:
- If the app is in the foreground, but the message is for a chat other than the one the user is looking at, display a notification.
- If the app is in the background, display a notification.
- If the app reconnects to pusher and finds new messages, _do not_ display notifications for all the messages that were missed while Pusher was disconnected.

## Actual Result:
No notification displays.

## Workaround:
None.

## Platform:
iOS
Android

**Version Number:** `1.0.77-2`

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by roryabraham** [comment]
On hold for now

**Comment by roryabraham** [comment]
Not overdue, still on HOLD

**Comment by roryabraham** [comment]
Will take this off hold starting next week.

**Comment by roryabraham** [comment]
No update, but taking this off hold.

**Comment by roryabraham** [comment]
No update, unfortunately other issues have been taking priority. Would love to spend some time to further this one, _maybe_ this week.

**Comment by roryabraham** [comment]
No update – still not a priority

**Comment by roryabraham** [comment]
May have renewed priority soon, with the E/App calling project, cc @francoisl

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
No update

**Comment by roryabraham** [comment]
Punting again

**Comment by roryabraham** [comment]
No update 😞

**Comment by roryabraham** [comment]
No update, and again unclear if there's going to be much need. I think the E/App calling project will use VoIP and not a local notification library. Going to close this out for now.

**Comment by Julesssss** [comment]
Keeping this as a low priority improvement

**Comment by Julesssss** [comment]
Leaving a link here to Rory's progress: 

> I had a draft implementation in 
[this PR](https://github.com/Expensify/App/pull/3024), in case it's useful. 
[These testing charts](https://github.com/Expensify/App/pull/3024#issuecomment-864299640) may be. The react-native-push-notification library used in that draft was abandoned, so I think we'll want to use 
[Notfiee](https://notifee.app/react-native/docs/displaying-a-notification)
 instead

**Comment by roryabraham** [comment]
Going to unassign myself here since the library used in my draft was abandoned and I think we should start with a P/S here before diving into implementation. I think it's a good idea but warrants a wider conversation.

**Comment by Julesssss** [comment]
I combined this and other issues into a Notification rework tracking issue, which I'll take on after manual requests

**Comment by Julesssss** [comment]
No change, Manual Request takes priority but I have started working on the notification project P/S

**Comment by trjExpensify** [comment]
👋 @Julesssss - https://github.com/Expensify/App/issues/4010#issuecomment-1216912428 as per this comment, does this issue still need to be open?

**Comment by JmillsExpensify** [comment]
Related Q: Should this be linked to a larger tracking issue?

**Comment by Julesssss** [comment]
> 👋 @Julesssss - [#4010 (comment)](https://github.com/Expensify/App/issues/4010#issuecomment-1216912428) as per this comment, does this issue still need to be open?

By that comment, I meant that I'm combining multiple issues into one place, rather than merging them into a single issue. So I'll keep them open for now while the doc is written.

**Comment by Julesssss** [comment]
@JmillsExpensify if I understand you correctly, I'm already using the Reqork Notifications tracking issue to group these issues. 

Or are you suggesting that we instead link them to WhatsApp Quality?

**Comment by Julesssss** [comment]
Doc in progress

**Comment by JmillsExpensify** [comment]
@Julesssss sorry for the confusion. I didn't realize that this issue is already linked to the tracking issue in the OP. Related question though: Should all the issues linked in the tracking issue, including this one, be on hold until the design doc comes out?

**Comment by Julesssss** [comment]
Yeah, I think so. Will update them today.

**Comment by JmillsExpensify** [comment]
Nice, thanks!

**Comment by Julesssss** [comment]
Okay, I'm going to close out this issue as we will likely be implementing local notifications via Pusher, instead of Pusher. We discussed this a bit in the [Reliable notifications project](https://docs.google.com/document/d/1pT6pPHc42XfqskZXDp1LcFa-jx2okFKy6GFEyD8a42M/edit?usp=sharing), and the bulk of this work/solution will be defined in the follow-up Notification Polish project as one of the major tasks.
