### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Android - Distance - Waypoint does not change position correctly by dragging

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40105]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Request money > Distance.
3. Add three waypoints (A, B and C)
4. Drag the waypoint C over waypoint A.

## Expected Result:
The waypoint sequence will now be C, A, B.

## Actual Result:
The waypoint sequence is B, C, A. The "Start" waypoint is in the middle instead of at the top after dragging the distance.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b6e69471-bcc6-4053-afd5-8be0cfe2590e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010257ce95cba77cc8</li>
        <li>Upwork Job ID: 1778535041816735744</li>
        <li>Last Price Increase: 2024-04-25</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment]
Starting an android build to check what is happening

**Comment by rlinoz** [comment]
Having a really hard time building it, the build is getting fixed here https://github.com/Expensify/App/pull/40102

**Comment by rlinoz** [comment]
Latest app is crashing when opening distance request page

**Comment by rlinoz** [comment]
Can reproduce though, not sure what broke it yet

**Comment by rlinoz** [comment]
It is almost EOD for my, I am opening this for help.

**Comment by rlinoz** [comment]
Thinking more about this, I don't think it needs to be a blocker, the functionality still works (the start/stop are swapped and the map preview is updated) and it is working as intended in all other platforms.

Gonna go ahead and remove the label.

**Comment by rlinoz** [comment]
Waiting for proposals

**Comment by lokesh-singhania** [comment]
@rlinoz, I am observing the expected behavior on following the steps given in [comment](https://github.com/Expensify/App/issues/40105#issue-2237645114).
Is there anything else required to reproduce the issue, like additional steps or specific devices?

https://github.com/Expensify/App/assets/13049969/c4112ae1-98b1-4332-a95f-1a4c79556ea4

**Comment by lokesh-singhania** [comment]
Contributor details
Your Expensify account email: singhania7lokesh@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0112431b6b9ac3e7be

**Comment by rlinoz** [comment]
I didn't have to do anything different, @lokesh-singhania what app version are you on?

**Comment by lokesh-singhania** [comment]
My bad. Used the production version.

**Comment by jliexpensify** [comment]
Posted for proposals - https://expensify.slack.com/archives/C01GTK53T8Q/p1713329137791109

**Comment by rlinoz** [comment]
Waiting for proposals

**Comment by rlinoz** [comment]
Waiting for proposals

**Comment by rlinoz** [comment]
@ishpaul777 what do you think about the proposal above?

**Comment by rlinoz** [comment]
Cool, can you help me understand why it only doesn't work on Android though? @Krishna2323 @ishpaul777

**Comment by rlinoz** [comment]
Thanks, I still find that a little weird, but let's fix this thing!

**Comment by jliexpensify** [comment]
Payment Summary

- C: @Krishna2323 $250
- C+: @ishpaul777 $250

[Upwork job](https://www.upwork.com/jobs/~010257ce95cba77cc8)

**Comment by jliexpensify** [comment]
Bumping @ishpaul777 for the checklist!

**Comment by jliexpensify** [comment]
[Here's a new Upworks job](https://www.upwork.com/jobs/~01df1e79a647812ec3) because the previous one was closed automatically. Please accept invites @ishpaul777 and @Krishna2323

**Comment by jliexpensify** [comment]
Bump @ishpaul777 to accept offer + complete checklist

**Comment by jliexpensify** [comment]
Awesome, cheers - all paid and job closed.
