### ISSUE TITLE
Autofocus mark (white ring) does not appear after tapping on the screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40106]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/39589
**Email or phone of affected tester (no customers):** applausetester+cknov@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to a report
3. Press on "+" in the composer and "Request money"
4. In the "Scan" tab, with your camera go close to an object (like the screen)
5. Tap on the screen manually

## Expected Result:
Autofocus mark (white ring) should appear after tapping on the screen as it appears on iOS app

## Actual Result:
Autofocus mark (white ring) does not appear after tapping on the screen on mweb/safari & chrome browsers

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1af4e4c4-ab84-46e9-b01b-fc480e3bffc6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by Christinadobrzyn** [comment]
Asking QA one clarifying question - https://expensify.slack.com/archives/C9YU7BX5M/p1712907913545049

**Comment by mountiny** [comment]
Yeah just think this would be a new feature and we dont have to focus on this right now. Cc @mrousavy @janicduplessis is v4 fully supporting mWeb too? 

Closing for now

**Comment by janicduplessis** [comment]
When I implemented it it seemed to be impossible with the available web apis to control camera focus.
