### ISSUE TITLE
Web - Email - Notification email for new message overlaps user email with message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40114]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4488527
**Email or phone of affected tester (no customers):** vdargentotest@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must be logged in
1. Go to a new chat with a user which email inbox you have access
2. Send a message (like "Hello") but do not read it as the receiver
3. On Web, go to the receiver email inbox and wait for the email notification for the new message to arrive
4. Open the email

## Expected Result:
The conversation preview should be fully visible with no issues

## Actual Result:
The email of the sender overlaps with the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6445190_1712788078203!Screenshot_1](https://github.com/Expensify/App/assets/78819774/8a2abe51-cdcc-4863-90c7-6107964e96a8)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Nice, will test Monday because I tried now but taking too long for email to come through!

**Comment by dylanexpensify** [comment]
Ok, testing!

**Comment by dylanexpensify** [comment]
@lanitochka17 can I get a repro from you? I haven't been able to repro

**Comment by dylanexpensify** [comment]
Could not repro, @lanitochka17 can you confirm?

**Comment by lanitochka17** [comment]
Issue is not reproducible 

![image (9)](https://github.com/Expensify/App/assets/78819774/dbaca163-0a16-4a60-8790-fd2f63cbe41d)
