### ISSUE TITLE
Android - Workspace- App crashes when change workspace Avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4489531&group_by=cases:section_id&group_order=asc&group_id=229065
**Email or phone of affected tester (no customers):** gocemate+balto963@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New dot app
2. Login with gmail account
3. Create Workspace
4. Go to workspace profile> Upload photo
5. Select any photo from device

## Expected Result:
Avatar should be successfully uploaded

## Actual Result:
App crashes when change workspace Avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/779f9563-e8b3-4540-887c-51b05ef8ac20

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
@ShridharGoel Hello
[log1.txt](https://github.com/Expensify/App/files/14961204/log1.txt)

**Comment by adelekennedy** [comment]
I can't replicate on BrowserStack v.1.4.62-4, I think this has been fixed
