### ISSUE TITLE
 Tag – Tag name updated after page reloading if edit it on another device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .4.62-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as WS admin to ND on two devices
3. Go to WS setting and open tag on both devices
4. Change tag name on secondary device and observe tag name on main device

## Expected Result:
Tag name updated immediately if edit it on another device

## Actual Result:
Tag name updated after page reloading if edit it on another device, but it’s visible for Employee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6f29300d-22a0-4f77-b14f-2c5a28dd16d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abekkala** [comment]
> but it’s visible for Employee

I feel that would be normal for the employee or any other account to immediately see the change and only when the 2nd device logged into the _same_ account that made the change would see it after reload
