### ISSUE TITLE
Web - Removing distance default category "Updated" message displayed Instead of "removed"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40112]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39643
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to /settings/workspaces/<policyID>/distance-rates
2. Tap Settings
3. Change the default category
4. Now uncheck the selected category
5. Navigate to #admin report of collect Workspace
6. Note the policy change log message says updated the Distance default category from "..." to "..." instead of "removed distance default category"

## Expected Result:
Message "removed distance default category" should be displayed after removing distance default category

## Actual Result:
Removing distance default category "Updated" message displayed Instead of "removed"

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fcaea6b2-b7a1-41e7-93ee-6eeffff4ac0c

![Screenshot 2024-04-11 at 1 21 31 AM](https://github.com/Expensify/App/assets/93399543/4da407e3-a802-47fd-9fcd-f66a1947ceed)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-control

**Comment by kbecciv** [comment]
@stephanieelliott FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by stephanieelliott** [comment]
I think this behavior makes sense, I know the `" "` could seem off but in this context I think it communicates a null value (which it is). So I don't think this is a bug per se and since it's affecting only one platform I don't think it is worth changing.
