### ISSUE TITLE
mWeb - Room - Admin room doesn't show messages about members invited to public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab--- start chat --- room
3. Create a room with public visibility
4. Tap header --- members
5. Invite a member
6. Navigate to admin room and note invited message not shown
7. Navigate to public room created
8. Using suggestions, invite user to room
9. Navigate to admin room and note invited message is not shown

## Expected Result:
From room created with public visibility, if users are invited, then invited message must be displayed in admin room

## Actual Result:
From room created with public visibility, if users are invited, then invited message is not displayed in admin room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f4ec0bea-71b8-439a-a743-c56a8043e556

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by joekaufmanexpensify** [comment]
Don't think this is a bug. [Discussing. ](https://expensify.slack.com/archives/C03U7DCU4/p1712869830342279)
