### ISSUE TITLE
Workspace - Hmm... it's not here displayed when owner delete the workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40135]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4479110&group_by=cases:section_id&group_order=asc&group_id=306202
**Email or phone of affected tester (no customers):** shussain@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a paid Collect workspace with Employee
2. As a employe of the workspace navigate to the #announce room
3. Disable the internet connection in the main testing device(Employee)
4. Send a message and a image to the conversation
5. In the secondary/admin device, navigate to the workspace and delete it

## Expected Result:
Hmm... it's not here should not be displayed when owner delete the workspace. This chat is no longer active should be displayed

## Actual Result:
Hmm... it's not here displayed when owner delete the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a3ada798-00f7-46a1-a715-c0bbd680cbbf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by JmillsExpensify** [comment]
Agree that this is a backend issue. Adding to #wave-collect.

**Comment by JmillsExpensify** [comment]
Still waiting to be picked up.

**Comment by JmillsExpensify** [comment]
Unclear when backend issues will be picked up so adding a monthly.

**Comment by JmillsExpensify** [comment]
Still waiting on internal engineer

**Comment by JmillsExpensify** [comment]
No internal engineer has yet picked this up so I'm closing and we can re-open when an Expensify engineer is able to take this on.
