### ISSUE TITLE
[$250] Update report actions in CONST.ts to use underscores for readability

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40188]
cc @roryabraham This is not really related to Group Chats, but came about in a PR review so creating a ticket to have it cleaned up.

**Problem:**

In App we have report action strings in `CONST.ts` that are not using underscores. This makes readability difficult and is inconsistent with the backend code where the same report actions exist and include underscores.

**Solution:**

Update the consts from [here](https://github.com/Expensify/App/blob/f5970a952d91ed2c40f820572058aa72f3119442/src/CONST.ts#L635-L636) and all references to use underscores to break up the words e.g.

ACTIONABLEMENTIONWHISPER -> ACTIONABLE_MENTION_WHISPER
ADDCOMMENT -> ADD_COMMENT

etc.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01610cbc887eeeda07</li>
        <li>Upwork Job ID: 1778880452173856768</li>
        <li>Last Price Increase: 2024-04-12</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>shahinyan11 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by shahinyan11** [comment]
Dibs

**Comment by shahinyan11** [comment]
Is need there to make proposal ?

**Comment by marcaaron** [comment]
Nope you're in 😄
