### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Add automated tests for `getGroupChatName()`

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40189]
cc @roryabraham coming from https://github.com/Expensify/App/pull/39757

Let's perform the following checks and add automated testing in this manner:

- [ ] Verify that the routes for Group participants invites, participant details, and role selection works as expected. Test corner cases like deep link, etc.
- [ ] Add UI test to confirm that `getGroupChatName()` appears correctly in the appropriate places (minimally the LHN and/or Report header)
- [ ] Add unit test to confirm that `getGroupChatName()` works correctly
- [ ] Verify that the performance of the options list in `InviteReportParticipantsPage` is adequate. Apply debounce suggestion from here if necessary: https://github.com/Expensify/App/pull/39757/files#r1561332638
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f0f59dd6db6b8bd</li>
        <li>Upwork Job ID: 1780003511636029440</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by roryabraham** [comment]
love it - once https://github.com/Expensify/App/pull/39757 is merged will you make this external then?

**Comment by marcaaron** [comment]
Gonna give first licks to @s77rt since they have a ton of context at this point. But if they don't want to work on it we can make it `External`.

**Comment by s77rt** [comment]
To not block on this let's make it external for now (I will be C+ if C+ is needed here). I will pick this up if no one took it (once I get more work done)

**Comment by marcaaron** [comment]
Thanks very much for your proposal @ShridharGoel 🙇 

>Does this mean manual verification or via tests only?

@ShridharGoel manual verification is sufficient. As far as I can tell we don't have automated tests for complex navigation flows.

Rest of the proposal looks 💎

**Comment by marcaaron** [comment]
Thanks @ShridharGoel, but they're not bugs.

>This shouldn’t be allowed, either leave button shouldn’t show in this case, or we can ask the user about whom to make the admin when leave button is clicked.

This is allowed. An admin gets promoted automatically.

>Clicking on the leave button doesn’t show any confirmation dialog.

Because there's nothing to confirm.

**Comment by s77rt** [comment]
Bumped the PR

**Comment by s77rt** [comment]
No regression test needed. We only adds tests.

**Comment by miljakljajic** [comment]
@s77rt paid - @ShridharGoel please accept the new offer, it seems there was an error with the original one.

**Comment by marcaaron** [comment]
Not overdue. Seems like we're almost done with this one.

**Comment by miljakljajic** [comment]
@ShridharGoel bump

**Comment by miljakljajic** [comment]
Paid and ready to close

**Comment by s77rt** [comment]
I just realized that we got paid for unfinished work. https://github.com/Expensify/App/pull/40658 got reverted and we had https://github.com/Expensify/App/pull/46661 as a replacement but that PR is not merged yet.

@ShridharGoel Will you be able to prioritise this one?

**Comment by s77rt** [comment]
No regression test needed as we only added tests. Payment has been handled already.
