### ISSUE TITLE
Selecting members on the participants page then removing a member leaves button selector in a weird state

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40194]
Coming from https://github.com/Expensify/App/pull/39757#issuecomment-2052597656

This is maybe not a really typical action to take, but we should do something about it.

1. Create a Group Chat
2. Navigate to participants
3. Select several participants
4. Tap a participant 
5. Remove from group
6. Participants selector has wrong count.

>Possible solution: On workspace tags we clear the selection when clicking on a tag, we can do similar thing here

**Comment by s77rt** [comment]
This is being fixed in https://github.com/Expensify/App/pull/40136
