### ISSUE TITLE
[Wave Collect][QBO] Fix the type mistakes made in the Import main page PR

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#40195]
Fix the type mistakes made in [this PR](https://github.com/Expensify/App/pull/38400)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4b1d75427bcd4d6</li>
        <li>Upwork Job ID: 1778904418909917184</li>
        <li>Last Price Increase: 2024-04-12</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Doesn't look like @parasharrajat reviewed this, so unassigning. @hayata-suenaga feel free to close it when it's deployed.

**Comment by trjExpensify** [comment]
#40196 deployed to staging. Once it hits prod, we'll close. 👍

**Comment by hayata-suenaga** [comment]
waiting for prod deployment
