### ISSUE TITLE
[HIGH] Ensure that Group Chat "invited" and "removed" system messages show correctly in the LHN

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40192]
## Problem 

Coming from @s77rt's comment [here](https://github.com/Expensify/App/pull/39757#issuecomment-2049195200). These messages look strange in the LHN. 

## Solution

Workspace rooms do not have this problem. So presumably there is some issue in the backend we need to fix, but it might be a frontend issue as well. Actually, @jasperhuangg probably knows why and can answer this question faster than us.

**Comment by jasperhuangg** [comment]
@marcaaron this is expected. We don't show the email address of users since for some reports, we don't know whether or not the users are allowed to view them (like in public rooms)

We could distinguish between the public/non public rooms, but this isn't something that needs to be addressed now.

**Comment by marcaaron** [comment]
If you look at the link the LHN messages are broken so I think we need to apply the same change we did for rooms to group chats or something. This is what they look like for Group Chats:

<img width="377" alt="321556576-d4d2d8dd-8fc8-478d-ad69-e281f37bfe1e" src="https://github.com/Expensify/App/assets/32969087/a9e2e22b-4ad9-4484-9a87-424a4d352516">

So, feels like we missed a detail somewhere - but I haven't looked into where yet.

**Comment by marcaaron** [comment]
Looking at this one today.

**Comment by marcaaron** [comment]
Waiting for deploy.

**Comment by marcaaron** [comment]
This is done now.
