### ISSUE TITLE
New Lib: fast-json-stable-stringify

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#40190]
*In order to add any new production dependency, it must be approved by the App Deployer team. They will evaluate the library and decide if it's something we want to move forward with or if other alternatives should be explored.*

# Name of library: fast-json-stable-stringify

## Details
- Link to package: https://www.npmjs.com/package/fast-json-stable-stringify
- Problem solved by using this package:

During a performance audit, @janicduplessis noticed that we're spending a significant amount of time in the `NumberFormat` constructor when chat switching - when opening 5 different chats on Android, it was observed that about 3 seconds were spent in the `NumberFormat` constructor.

The proposed solution was to cache `NumberFormat` instances so we aren't re-running the constructor needlessly. In order to do that, we need to serialize the options passed to the constructor so that they can be used in a cache key. `JSON.stringify` isn't ideal for the purpose of creating cache keys, because the order in JSON objects is not deterministic. i.e: `JSON.stringify({a: 'a', b: 'b'})` may produce either `{"a": "a", "b": "b"}` or `{"b": "b", "a": "a"}` on two successive calls, which would change the cache key.

This is where fast-json-stable-stringify comes into play - `stableStringify({a: 'a', b: 'b'})` and `stableStringify({b: 'b', a: 'a'})` will both reliably produce `{"a": "a", "b": "b"}`. This is what the authors mean when they say it's deterministic.

- Number of stars in GH: 273
- Number of monthly downloads: >38,000,000 (looking at GH stars vs downloads, everyone uses it without knowing, which - spoiler alert - also includes us!)
- Number of releases in the last year: 0 - don't fix it if it ain't broke
- Level of activity in the repo: none really, but it still works
- Alternatives:
    - roll-your-own (deep sort the object, then use JSON.stringify)
    - https://github.com/ljharb/json-stable-stringify. This lib is allegedly the same thing but slower
- Are security concerns brought up and addressed in the library's repo? no, not really
- How many dependencies does this lib use that will be brought into our code? 0
- What will the effect be on the bundle size of our code?

no change - we already use this lib indirectly. It's a transitive dependency so already included in the app bundle. I only created this because we want to add it to package.json and use it directly.

**Comment by roryabraham** [comment]
extra context for you @marcaaron:

- https://github.com/Expensify/App/pull/40158
- https://expensify.slack.com/archives/C035J5C9FAP/p1712894837849989

**Comment by marcaaron** [comment]
Looks fine to me I guess - it's like 50 lines of code... do we still have to have a conversation about it?

**Comment by marcaaron** [comment]
>everyone uses it without knowing, which - spoiler alert - also includes us

so we use it already?

**Comment by marcaaron** [comment]
>no change - we already use this lib indirectly. It's a transitive dependency so already included in the app bundle. I only created this because we want to add it to package.json and use it directly.

I think you can just go ahead and include this as a dependency since it's a tiny library. But lmk if you still want to talk about it. And I will post this on Monday. Doesn't look like anyone would say no IMO.

**Comment by janicduplessis** [comment]
Looks like it is currently a transitive dependency of jest and webpack, it might not actually be included in the app bundle currently since those are dev dependencies, but as mentionned it is tiny.

**Comment by roryabraham** [comment]
I agree it's unlikely we'll get pushback, I'm just following the process rather than making a unilateral decision to skip it.

**Comment by marcaaron** [comment]
Posted [here](https://expensify.slack.com/archives/C03TQ48KC/p1713230838173229)

**Comment by marcaaron** [comment]
Closing this. LMK if we need to reopen.
