### ISSUE TITLE
[$250] [HOLD for payment 2024-06-11] Uploading a Group Chat custom avatar that is too large shows badly formatted error message

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40199]
Coming from https://github.com/Expensify/App/pull/39757#issuecomment-2052653886

**Reproduction:**

1. Create a Group Chat
2. Navigate to report details page
3. Upload a custom avatar that is too large

**Expected:**

The error message displayed is taking up the normal width of the screen.

**Actual:**

![Image](https://github.com/Expensify/App/assets/32969087/57273848-94ee-4f47-957f-f4ab36a7f610)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013621cec02e1951b1</li>
        <li>Upwork Job ID: 1800948188003727972</li>
        <li>Last Price Increase: 2024-06-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by s77rt** [comment]
@Expensify/design I found this inconsistency in the avatar error message, which one is the correct one?

<img width="865" alt="Screenshot 2024-05-13 at 11 36 55 AM" src="https://github.com/Expensify/App/assets/16493223/ea15d793-4d15-4f61-afe8-bd14cd7dd252">

**Comment by shawnborton** [comment]
Hmm I think I lean towards the right version being more correct. Thoughts @Expensify/design?

**Comment by dannymcclain** [comment]
Yeah I think so too. I think it makes more sense with the rest of our app for it to span the full width.

**Comment by s77rt** [comment]
Working on a similar issue on https://github.com/Expensify/App/pull/42088#issuecomment-2109806472. Checking if we can fix that issue there too

**Comment by s77rt** [comment]
Just raised a [PR](https://github.com/Expensify/App/pull/42735)

**Comment by c3024** [comment]
@marcaaron Can you please assign me this issue as C+ as I reviewed the PR?

**Comment by laurenreidexpensify** [comment]
@s77rt @c3024 pls apply in upwork thanks - https://www.upwork.com/jobs/~013621cec02e1951b1

**Comment by s77rt** [comment]
@laurenreidexpensify Accepted! Thanks!

**Comment by c3024** [comment]
@laurenreidexpensify applied, thank you.

**Comment by laurenreidexpensify** [comment]
Summary:
 
- C+ @s77rt paid $250 via Upwork 
- Contributor @c3024 paid $250 via Upwork 

@s77rt regression step recommendations for this?

**Comment by s77rt** [comment]
@laurenreidexpensify The bug was found during PR review and not entirely a regression. I don't think this is worth adding a test for
