### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Group Chat custom avatar not saved when navigating back to invite members page

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40198]
Coming from https://github.com/Expensify/App/pull/39757#issuecomment-2052659550

1. Create a new group chat
2. Choose a picture for custom avatar
3. Go back to member invite page 
4. Proceed again 
5. Create chat 

**Expected:**

Avatar image should be saved.

**Actual** 

Picture is not taken into consideration.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f246ab8eb2607ee</li>
        <li>Upwork Job ID: 1785758481083801600</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 102700850</li>
<li>wildan-m | Contributor | 102700854</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by marcaaron** [comment]
I am guessing this is because the file ref needs to be cached outside the component lifecycle or some other strategy to achieve it. Feels like a minor issue that can be easily solved.

**Comment by s77rt** [comment]
No progress yet. Focused on QBO

**Comment by marcaaron** [comment]
Gonna take this one `External` so we can make some progress.

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group Chat custom avatar not saved when navigating back to invite members page

### What is the root cause of that problem?
When creating the group, we use the outdated `fileRef.current` which is undefined when coming back.

https://github.com/Expensify/App/blob/406139cf2120b25c28643f1e728d531fd8848a60/src/pages/NewChatConfirmPage.tsx#L96

### What changes do you think we should make in order to solve the problem?
We should use `stashedLocalAvatarImage` which saves the chosen picture as param when creating the groupChat

**Comment by s77rt** [comment]
@neonbhai Thanks for the proposal. Your RCA makes sense but the solution won't work. In onyx we only store the url and we want to pass the whole image.

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by adelekennedy** [comment]
still waiting for proposals - @marcaaron @s77rt is this a more complex issue than originally thought?

**Comment by s77rt** [comment]
@adelekennedy I didn't check in depth but it shouldn't be that hard, no need to adjust the bounty yet

**Comment by marcaaron** [comment]
Agree, I think we just haven't found the obvious solution yet - but let's see.

**Comment by adelekennedy** [comment]
still waiting

**Comment by adelekennedy** [comment]
gonna just keep waiting on this as it's pretty edge-casey. Going to move this to weekly so we don't keep getting dinged

**Comment by s77rt** [comment]
Still looking for proposals...

**Comment by adelekennedy** [comment]
still pending proposals @neonbhai can you update your proposal with @s77rt feedback?

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Group Chat custom avatar not saved when navigating back to invite members page

### What is the root cause of that problem?

The screen remounts every time we navigate, causing the fileRef to be re-initialized upon returning.

### What changes do you think we should make in order to solve the problem?

We can move fileRef to a context to make it persist while navigate.

Create `src/hooks/useFileRef.tsx`

<details><summary>useFileRef.tsx</summary>

```
import React, { createContext, useContext, useRef, ReactNode } from 'react';
import type {CustomRNImageManipulatorResult} from '@libs/cropOrRotateImage/types';

// Define the type for the context
type FileRefContextType = React.MutableRefObject<File | CustomRNImageManipulatorResult | undefined> | null;

// Create the context
const FileRefContext = createContext<FileRefContextType>(null);

// Custom hook to access the context
const useFileRef = (): FileRefContextType => useContext(FileRefContext);

// Define the type for the provider props
type FileRefProviderProps = {
    children: ReactNode;
};

// Provider component to manage the fileRef value
const FileRefProvider = ({ children }: FileRefProviderProps) => {
    const fileRef = useRef<File | CustomRNImageManipulatorResult | undefined>(null);

    return (
        <FileRefContext.Provider value={fileRef}>
            {children}
        </FileRefContext.Provider>
    );
};

export { FileRefProvider, useFileRef }
```

</details>

Wrap RHP stack navigator with `FileRefProvider`

```
            <View style={styles.RHPNavigatorContainer(isSmallScreenWidth)}>
                <FileRefProvider>
                    <Stack.Navigator
 .....
```

`fileRef` in `NewChatConfirmPage` will use `useFileRef`
```
function NewChatConfirmPage({newGroupDraft, allPersonalDetails}: NewChatConfirmPageProps) {
    const optimisticReportID = useRef<string>(ReportUtils.generateReportID());
    const fileRef = useFileRef();

```

Clean up

```
    const createGroup = useCallback(() => {
        if (!newGroupDraft) {
            return;
        }

        const logins: string[] = (newGroupDraft.participants ?? []).map((participant) => participant.login);
        Report.navigateToAndOpenReport(logins, true, newGroupDraft.reportName ?? '', newGroupDraft.avatarUri ?? '', fileRef &&fileRef.current, optimisticReportID.current, true);
        if (fileRef) {
            fileRef.current = undefined;
        }
```

[Branch to test](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/40198-uploaded-avatar-missing-when-remounted?expand=1).

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment]
@wildan-m Thanks for the proposal. Your RCA makes sense but the solution is over-engineered. We already have this flow working well with receipts. Let's follow the same approach.

**Comment by wildan-m** [comment]
@s77rt receipt has different case, perform back navigation from image preview will force the user to re-upload the scanned receipt, but group chat will expect we re-visit the image preview page without re-uploading the image.

**Comment by s77rt** [comment]
@wildan-m If you start the money request process from the FAB you can go back to the participants page

**Comment by wildan-m** [comment]
@s77rt thanks for the hints. I've updated [my propsal](https://github.com/Expensify/App/issues/40198#issuecomment-2155822841).

Change log: Move prev solution to alternative, add new main solution that mimic receipt upload behavior.

**Comment by s77rt** [comment]
@wildan-m Thanks for looking into this. The solution looks good to me 👍.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/40198#issuecomment-2155822841)

**Comment by wildan-m** [comment]
@MonilBhavsar, do we need to consider anything else before we proceed?

**Comment by MonilBhavsar** [comment]
No thanks! looks good to me. Thanks for keeping it consistent with receipt scan flow

**Comment by wildan-m** [comment]
@s77rt The [PR is ready for review](https://github.com/Expensify/App/pull/43584).

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/39757#issuecomment-2052659550
- The offending PR has been commented on : https://github.com/Expensify/App/pull/39757#issuecomment-2052659550
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**
1. Click FAB > Start chat
2. Select multiple users (group) and press Next
3. Upload a group avatar
4. Go back
5. Click Next
6. Click Start group
7. Verify that the group is created and the custom avatar is used

**Comment by marcaaron** [comment]
LGTM

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @wildan-m 
- [ ] Contributor+: $250 @s77rt

**Comment by adelekennedy** [comment]
https://github.com/Expensify/Expensify/issues/409492
