### ISSUE TITLE
[HOLD for payment 2024-05-08] [$250] Update icons in global create and money request flows 

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#40225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @shawnborton 
**Slack conversation:** [Link](https://expensify.slack.com/archives/C036QM0SLJK/p1712634855894179) [Internal]

## Feature Request
We want to update some of the icons found in our global create menu as well as the money request flows:
![CleanShot 2024-04-15 at 13 09 22@2x](https://github.com/Expensify/App/assets/2319350/cdceae38-eb3c-423a-ab76-67b630b613be)

Notes:
- For `Track expense`, we want to use the coins icon
- For `Request money`, we want to use the receipt icon
- For `Send money`, we want to use the money/cash icon
- For `Scan` in the money request flows, we want to use the scan receipt icon
- The updates made in the global create menu and segmented control should also be reflected in the `Quick action` row found in global create

Note that all of these icons already exist in the App repo, we just need to use them in the places mentioned above. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Note four our internal team: given that this is just very small file name changes, we should drop the bounty down to $125. 

cc @Expensify/design @kevinksullivan @mountiny @quinthar 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162b090372a61cda0</li>
        <li>Upwork Job ID: 1779768720839634944</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by godofoutcasts94** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Update icons in global create and money request flows 
### What is the root cause of that problem?
Feature Request
### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment]
updated [proposal](https://github.com/Expensify/App/issues/40225#issuecomment-2055763167)

**Comment by shawnborton** [comment]
@shubham1206agra that is a separate issue with a separate problem/solution. This issue does not touch the Split bill icon at all.

**Comment by trjExpensify** [comment]
Just to confirm after reading the OP, we aren't changing the names of the global create option rows with this issue, right? We're going to wait for the doc Kevin is working on for that, so we do it in tandem with all the other places we reference "request money" / "request" for example?

**Comment by brkdavis** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update icons as per clear instructions and wireframes in the description

### What is the root cause of that problem?
New feature

- For Track expense, we want to use the coins icon
- For Submit expense, we want to use the receipt icon
- For Pay someone, we want to use the money/cash icon
- For Scan in the money request flows, we want to use the scan receipt icon
- The updates made in the global create menu and segmented control should also be reflected in the Quick action row found in global create

### What changes do you think we should make in order to solve the problem?
As all these are existing icons, no new assets are required. Update references to existing icons from the menu.

Update the icon name in quick actions in `FloatingActionButtonAndPopoverOnyxProps.tsx`
```
const getQuickActionIcon = (action: QuickActionName): React.FC<SvgProps> => {
    switch (action) {
        case CONST.QUICK_ACTIONS.REQUEST_MANUAL:
            return Expensicons.MoneyCircle;
        case CONST.QUICK_ACTIONS.REQUEST_SCAN:
            return Expensicons.Receipt;
        case CONST.QUICK_ACTIONS.REQUEST_DISTANCE:
            return Expensicons.Car;
        case CONST.QUICK_ACTIONS.SPLIT_MANUAL:
        case CONST.QUICK_ACTIONS.SPLIT_SCAN:
        case CONST.QUICK_ACTIONS.SPLIT_DISTANCE:
            return Expensicons.Transfer;
        case CONST.QUICK_ACTIONS.SEND_MONEY:
            return Expensicons.Send;
        case CONST.QUICK_ACTIONS.ASSIGN_TASK:
            return Expensicons.Task;
        default:
            return Expensicons.MoneyCircle;
    }
};
```

Update the icons in the react View that will be rendered.
```
<View style={styles.flexGrow1}>
            <PopoverMenu
                onClose={hideCreateMenu}
                isVisible={isCreateMenuActive && (!isSmallScreenWidth || isFocused)}
                anchorPosition={styles.createMenuPositionSidebar(windowHeight)}
                onItemSelected={hideCreateMenu}
                fromSidebarMediumScreen={!isSmallScreenWidth}
                menuItems={[
                    {
                        icon: Expensicons.ChatBubble,
                        text: translate('sidebarScreen.fabNewChat'),
                        onSelected: () => interceptAnonymousUser(Report.startNewChat),
                    },
                    ...(canUseTrackExpense
                        ? [
                              {
                                  icon: Expensicons.DocumentPlus,
                                  text: translate('iou.trackExpense'),
                                  onSelected: () =>
                                      interceptAnonymousUser(() =>
                                          IOU.startMoneyRequest(
                                              CONST.IOU.TYPE.TRACK_EXPENSE,
                                              // When starting to create a track expense from the global FAB, we need to retrieve selfDM reportID.
                                              // If it doesn't exist, we generate a random optimistic reportID and use it for all of the routes in the creation flow.
                                              // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
                                              ReportUtils.findSelfDMReportID() || ReportUtils.generateReportID(),
                                          ),
                                      ),
                              },
                          ]
                        : []),
                    {
                        icon: Expensicons.MoneyCircle,
                        text: translate('iou.requestMoney'),
                        onSelected: () =>
                            interceptAnonymousUser(() =>
                                IOU.startMoneyRequest(
                                    CONST.IOU.TYPE.REQUEST,
                                    // When starting to create a money request from the global FAB, there is not an existing report yet. A random optimistic reportID is generated and used
                                    // for all of the routes in the creation flow.
                                    ReportUtils.generateReportID(),
                                ),
                            ),
                    },
                    {
                        icon: Expensicons.Send,
                        text: translate('iou.sendMoney'),
                        onSelected: () =>
                            interceptAnonymousUser(() =>
                                IOU.startMoneyRequest(
                                    CONST.IOU.TYPE.SEND,
                                    // When starting to create a send money request from the global FAB, there is not an existing report yet. A random optimistic reportID is generated and used
                                    // for all of the routes in the creation flow.
                                    ReportUtils.generateReportID(),
                                ),
                            ),
                    },
                    {
                        icon: Expensicons.Task,
                        text: translate('newTaskPage.assignTask'),
                        onSelected: () => interceptAnonymousUser(() => Task.clearOutTaskInfoAndNavigate()),
                    },
                    ...(!isLoading && !Policy.hasActiveChatEnabledPolicies(allPolicies)
                        ? [
                              {
                                  displayInDefaultIconColor: true,
                                  contentFit: 'contain' as ImageContentFit,
                                  icon: Expensicons.NewWorkspace,
                                  iconWidth: 46,
                                  iconHeight: 40,
                                  text: translate('workspace.new.newWorkspace'),
                                  description: translate('workspace.new.getTheExpensifyCardAndMore'),
                                  onSelected: () => interceptAnonymousUser(() => App.createWorkspaceWithPolicyDraftAndNavigateToIt()),
                              },
                          ]
                        : []),
                    ...(quickAction?.action
                        ? [
                              {
                                  icon: getQuickActionIcon(quickAction?.action),
                                  text: quickActionTitle,
                                  label: translate('quickAction.shortcut'),
                                  isLabelHoverable: false,
                                  floatRightAvatars: quickActionAvatars,
                                  floatRightAvatarSize: CONST.AVATAR_SIZE.SMALL,
                                  description: !isEmptyObject(quickActionReport) ? ReportUtils.getReportName(quickActionReport) : '',
                                  numberOfLinesDescription: 1,
                                  onSelected: () => interceptAnonymousUser(() => navigateToQuickAction()),
                                  shouldShowSubscriptRightAvatar: ReportUtils.isPolicyExpenseChat(quickActionReport),
                              },
                          ]
                        : []),
                ]}
                withoutOverlay
                anchorRef={fabRef}
            />
            <FloatingActionButton
                accessibilityLabel={translate('sidebarScreen.fabNewChatExplained')}
                role={CONST.ROLE.BUTTON}
                isActive={isCreateMenuActive}
                ref={fabRef}
                onPress={toggleCreateMenu}
            />
        </View>
```

### What alternative solutions did you explore? (Optional)
N.A.

**Comment by shawnborton** [comment]
Ah, I wasn't thinking we'd change the names but that's a good point about @kevinksullivan's doc. Do we want to wait for that doc to update the icons here too?

**Comment by shawnborton** [comment]
If we didn't do any name changes but just changed out some icons, I think we'd get this as the correct image for the original comment here: 
![CleanShot 2024-04-15 at 13 08 03@2x](https://github.com/Expensify/App/assets/2319350/fb8f3095-ab26-4c26-a558-24a43b714080)

**Comment by godofoutcasts94** [comment]
Updated [Proposal](https://github.com/Expensify/App/issues/40225#issuecomment-2055763167) as per [comment](https://github.com/Expensify/App/issues/40225#issuecomment-2056567649)

**Comment by mountiny** [comment]
Lets do this change after we update the copy. @eVoloshchak could you please triage the proposal for updating the icons only? the copy changes will be done in separate issue

**Comment by trjExpensify** [comment]
Yeah, I think doing icons right away now is fine. I was just hesitant on the menu item names as that has more implications throughout the flows in a number of places.

**Comment by eVoloshchak** [comment]
> Use the new method to get the icon for the actions in the Composer "Plus" context menu [here](https://github.com/Expensify/App/blob/b5fdc877accaa7aea216291c249051acb481ad08/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.tsx#L124) (t was also not mentioned in the OP, but it needs to be updated to be consistent)

This is an important detail, good catch, @tienifr. 
It isn't mentioned in the OP, but I think we definitely should update it for consistency. 
@shawnborton, could you please confirm the icons in the Composer "Plus" context menu also need to be updated?
<img width="532" alt="Screenshot 2024-04-16 at 12 15 21" src="https://github.com/Expensify/App/assets/9059945/be6f127c-3328-46e3-b26d-0c465213895e">

**Comment by mountiny** [comment]
@eVoloshchak what are the next steps here?

**Comment by eVoloshchak** [comment]
In that case, I think we should proceed with @tienifr's [proposal](https://github.com/Expensify/App/issues/40225#issuecomment-2055888031) since it's the only proposal that covers all of the cases

🎀👀🎀 C+ reviewed!

**Comment by dannymcclain** [comment]
>For the coins, looks like we have it as "tax.svg" - I think renaming it to coins makes more sense personally.

Let's please rename it to `coins.svg` if possible. And if we do, we should check and see where it's referenced to make sure we don't bork anything!

**Comment by puneetlath** [comment]
@tienifr has been paid. 

@eVoloshchak bump on the checklist for you.

**Comment by eVoloshchak** [comment]
@puneetlath, not sure if checklist is applicable here, this isn't a bug, we just needed to update the icons
There is no PR that has caused this, no discussion needed and no regression test

**Comment by puneetlath** [comment]
Ah ok, that makes sense. 

Payment summary: 
- $250 - C - paid via Upwork
- $250 - C+ - @eVoloshchak - to be paid via NewDot

@eVoloshchak please request on NewDot. Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
