### ISSUE TITLE
[HOLD for payment 2024-04-30][$250] [Search v1] Implement Search navigation logic

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#40245]
Section from [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.l7zs7ubp0bp8)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd86e6916eff3437</li>
        <li>Upwork Job ID: 1780007564904620032</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by luacmartins** [comment]
@adamgrzybowski @WojtekBoman could you please comment on this issue so I can get it assigned to you

**Comment by luacmartins** [comment]
PR was deployed to prod 2 days ago

**Comment by rushatgabhane** [comment]
Made a manual request - https://staging.new.expensify.com/r/894137542780233

**Comment by garrettmknight** [comment]
**Payment summary:**
- Reviewer: @rushatgabhane @$250

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by shawnborton** [comment]
Not overdue, holding for payment

**Comment by garrettmknight** [comment]
All paid up.
