### ISSUE TITLE
[$100] Remove "Include domain rooms with Partner Managers" from "canSeeDefaultRoom"

### ISSUE THREAD

**Issue by flodnv** [Expensify/App#40249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

*Problem:* domain rooms are confusing partners. 

*Solution:* disable them.

Looks like we need to remove these lines: https://github.com/Expensify/App/blob/3d7f0b7f025e86eea1fe6b541acec0d6673a5b15/src/libs/ReportUtils.ts#L4329-L4332, and properly test the other cases. 

I would also recommend testing the whole `isDomainRoom(report) && doesDomainHaveApprovedAccountant && hasExpensifyEmails(report?.participantAccountIDs ?? [])` case by hardcoding some stuff in these variables / methods.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fa8e12807c70f8c</li>
        <li>Upwork Job ID: 1779945920543899648</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

**Comment by flodnv** [comment]
Go for it @ShridharGoel, thanks

**Comment by flodnv** [comment]
@ShridharGoel will you have a PR up today? 🙏

**Comment by flodnv** [comment]
Sounds good, I will test the adhoc build 👍

**Comment by flodnv** [comment]
LOL! I did not know that. @miljakljajic please issue a $100 payment to @ShridharGoel and close this issue.

**Comment by miljakljajic** [comment]
@ShridharGoel when you accept the upwork offer we can pay you can close this out

**Comment by flodnv** [comment]
bump @miljakljajic can we finish the payment and close this?

**Comment by miljakljajic** [comment]
very sorry! it's all paid now
