### ISSUE TITLE
[HOLD for payment 2024-05-20] [$250] Skeleton loader uses lighter color for page header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40244]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713166267469379

## Action Performed:
1. Open a chat which will show a skeleton loader
2. Look at the header of the chat report

## Expected Result:
The skeleton loader for the top page/chat header should use the same color background as the skeleton loader for the chat messages in the main content screen.

## Actual Result:
 The skeleton loader used in the top page/chat header is using slightly lighter colors

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-04-15 at 09 29 33@2x](https://github.com/Expensify/App/assets/38435837/b69dd5ac-1a58-4fd5-a287-f0e59238756f)
![Untitled](https://github.com/Expensify/App/assets/38435837/c5ab1ba8-1b08-42ef-92f8-0b422ff88f5d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0199d049e1997c5cb7</li>
        <li>Upwork Job ID: 1779899140122308608</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by twisterdotcom** [comment]
Ahh:

>Issue reported by: @shawnborton

Gonna make external.

**Comment by mananjadhav** [comment]
I was too slow in posting a proposal. 🐌

**Comment by AbrarAlHasan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent Color in Skeleton Loader header between the header and Main Content Screen

### What is the root cause of that problem?
The Root cause of this Problem is due to the wrong Color used in the SkeltonViewContentLoader

### What changes do you think we should make in order to solve the problem?
Changing the Color in the Skeleton Header to the color used in the Main content Screen will Solve this Problem.

### What alternative solutions did you explore? (Optional)

**Comment by AbrarAlHasan** [comment]
Contributor details
Your Expensify account email: abraralhasan111@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d42425e0d283e140

**Comment by shawnborton** [comment]
> I noticed a bad alignment (more padding on the left) on the header skeleton on web

@dragnoir this was on desktop. I agree, we should fix the alignment too. cc @twisterdotcom - I like @dragnoir 's proposal to fix both the colors and alignment.

**Comment by twisterdotcom** [comment]
We could split this then @dragnoir? Given you're doing the work, how do we feel about 70/30?

- @dragnoir = $175
- @GandalfGwaihir = $75

**Comment by shawnborton** [comment]
If the bug pointed out doesn't exist, then let's ignore it and just address the original bug report from this issue.

**Comment by twisterdotcom** [comment]
Let's wait for @dragnoir - it sounds like they did think it exists for some reason. If they confirm it doesn't and we all agree, then of course, I think we can switch it out for you @GandalfGwaihir.

**Comment by shawnborton** [comment]
I think this place should also be fixed:
![CleanShot 2024-04-17 at 19 20 00@2x](https://github.com/Expensify/App/assets/2319350/44bf5fc1-202e-44fa-a11f-1fe43f12891d)

But the money request preview component should not be changed.

**Comment by shawnborton** [comment]
@twisterdotcom is managing the issue on our end, so I will let him take care of that. I'm just here for design guidance :)

**Comment by twisterdotcom** [comment]
Yes, happy to assign you. I know we've sort of circumvented @abdulrahuman5196 a bit but happy with Shawn's take from Design over an `Internal` engineer.

**Comment by abdulrahuman5196** [comment]
Hi, Thank you. Will work on review.

**Comment by abdulrahuman5196** [comment]
Hi, Checking the PR now.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @abdulrahuman5196 paid $250 [here](https://www.upwork.com/nx/wm/workroom/37088686/overview) (Reviewer)
- @GandalfGwaihir paid $250 [here](https://www.upwork.com/nx/wm/workroom/37014500/overview) (Contributor)

I dont' think this was actually an _introduced_ bug right, but it was actually a `new feature`. It never looked this way before right? We just got our greys wrong originally.
