### ISSUE TITLE
Android - 'Here' link in Concierge chat re-opens Bank Account flow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal

## Action Performed:
Precondition: User is logged in Android native application.
1. Open Settings > Workspace > Select any workspace > Bank account
2. Connect a bank account and complete it until the validation step (use Regions bank and First Last name)
3. Press "Yes, let's chat" button.
4. After navigated to the concierge chat, find a message with a "here" link text
5. Press 'here' link

## Expected Result:
A not-found page is shown

## Actual Result:
'Business info' tab opened again. If user tries to return to Concierge chat (tap device Back button), he is navigated to Bank account tab again.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8e897451-fb35-4c93-8229-207a3d793777

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@laurenreidexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
linking TC update issue https://github.com/Expensify/Expensify/issues/369684

**Comment by laurenreidexpensify** [comment]
@kbecciv I am following the reproduction Steps and a few comments:

1. prerequisite is that the workspace default currency needs to be USD for this 
2. Can you confirm if this is a connect online with Plaid or connect manually flow 
3. Can you confirm why the expected flow is "A not-found page is shown" / the source for that?

**Comment by kbecciv** [comment]
@laurenreidexpensify 
1. Yes, the workspace default currency needs to be USD
2. Connect online with Plaid
3. We have an edge case issue documented here: https://github.com/Expensify/Expensify/issues/369684. It specifies that on step 5, we should wait until a not-found page is shown.

**Comment by laurenreidexpensify** [comment]
Asking internally - https://expensify.slack.com/archives/C03U7DCU4/p1713360069740219

**Comment by laurenreidexpensify** [comment]
I still think this is a weird flow, that the expected result is a "A not-found page is shown" - this issue isn't an urgent bug so will continue to investigate internally as to whether we've introduced something weird in the original design that this was picked up in the regression test of.

**Comment by laurenreidexpensify** [comment]
Still considering this one, as per note above

**Comment by laurenreidexpensify** [comment]
Continuing to discuss internally

**Comment by laurenreidexpensify** [comment]
After some discussion internally, we've realised this this regression test is just kinda wrong and should be removed, so this bug report is a false positive and am gonna close.
