### ISSUE TITLE
[Awaiting Payment April 30th] [$250] [Guided Setup] Update custom messages in the onboarding flow

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#40261]
Coming from this [design doc](https://docs.google.com/document/d/1sxG_RV5HTFHgdCsJUDNpqSGs09W_OPLBKbNYQfu3FHw/edit), in testing we found we were finding two welcome emails. One introing Concierge, and then one giving more info on the use case ([details here](https://expensify.slack.com/archives/C036QM0SLJK/p1713224028604409?thread_ts=1713194544.839969&cid=C036QM0SLJK)). 

![image](https://github.com/Expensify/App/assets/2364487/4c480e1a-571d-4bc0-80a5-41130331f27b)

As such, we'd like to update the message being triggered (the second message above) from the onboarding selection to remove the welcome portion of the subject line AND the concierge introduction currently in the message. As such, the messages that are based on use case selection are as follows:

**If the user never makes a use case selection**
We do not need to send anything, as we've already sent the intro. 

**If the user selects “I am just looking around”** 
We do not need to send anything, as we've already sent the intro and don't need more. 

**If the user selects “Chat and split expenses with friends”**
```
# Splitting the bill is as easy as a conversation! 

To split an expense:
1. From the home screen, click the green + button > Request money.
2. Enter an amount or scan a receipt, then choose who you want to split it with.

We'll send a request to each person so they can pay you back. Let me know if you have any questions! 
```

**If the user selects “Submit expenses to my employer to get paid back”**
```
# Expensify is the fastest way to get paid back! 

To submit expenses for reimbursement:
1. From the home screen, click the green + button > Request money.
2. Enter an amount or scan a receipt, then input your boss's email.

That’ll send a request to get you paid back. Let me know if you have any questions! 
```

**If the user selects “Track my business expenses to file taxes”** 
```
# Let’s start tracking your expenses! 

To track your expenses, create a workspace to keep everything in one place. Here’s how:
1. From the home screen, click the green + button > New Workspace
2. Give your workspace a name (e.g. "My business expenses”).

Then, add expenses to your workspace:
1. Find your workspace using the search field.
2. Click the gray + button next to the message field.
3. Click Request money, then add your expense type.

We’ll store all expenses in your new workspace for easy access. Let me know if you have any questions!
```

**If the user selects “Manage my team’s expenses”**
```
# Let’s start managing your team’s expenses! 

To manage your team's expenses, create a workspace to keep everything in one place. Here’s how:
1. From the home screen, click the green + button > New Workspace
2. Give your workspace a name (e.g. “Sales team expenses”).

Then, invite your team to your workspace via the Members pane and [connect a business bank account](https://help.expensify.com/articles/new-expensify/bank-accounts/Connect-a-Bank-Account) to reimburse them. Let me know if you have any questions!
```

**If the user selects “Track and budget personal spend”**

```
# Let’s start tracking your expenses! 

To track your expenses, create a workspace to keep everything in one place. Here’s how:
1. From the home screen, click the green + button > New Workspace
2. Give your workspace a name (e.g. "My expenses”).

Then, add expenses to your workspace:
1. Find your workspace using the search field.
2. Click the gray + button next to the message field.
3. Click Request money, then add your expense type.

We’ll store all expenses in your new workspace for easy access. Let me know if you have any questions!
```

Notes for completion:
- The # is just denoting using the custom subject line as already implemented. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119f0ea9acc1824fb</li>
        <li>Upwork Job ID: 1780067887070625792</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment]
@GandalfGwaihir @tienifr Hey, I am carefully reviewing proposals, line by line. Please wait for a few minutes 🙏

**Comment by jayeshmangwani** [comment]
@GandalfGwaihir Question for you from your [proposal](https://github.com/Expensify/App/issues/40261#issuecomment-2058018827), 

> So for example the above onboardingChoices.EMPLOYER will now be

```
[onboardingChoices.EMPLOYER]:
        'To submit expenses for reimbursement:\n' +
        '1. From the home screen, click the green + button > Request money.\n' +
        "2. Enter an amount or scan a receipt, then input your boss's email.\n" +
        '\n' +
        "That'll send a request to get you paid back. Let me know if you have any questions!",
```

You mentioned that onboardingChoices.EMPLOYER will now be like above, but this is missing the header part.

It should be below, right?
     
```
'# Expensify is the fastest way to get paid back! \n' +
'\n' +
'To submit expenses for reimbursement:\n' +
'1. From the home screen, click the green + button > Request money.\n' +
"2. Enter an amount or scan a receipt, then input your boss's email.\n" +
'\n' +
"That'll send a request to get you paid back. Let me know if you have any questions!",
```

**Comment by jayeshmangwani** [comment]
@GandalfGwaihir This is a pretty straightforward issue. There is a small missing detail in your proposal, though, that can be done on the PR process; for transparency, I find that @tienifr has a more accurate and detailed [Proposal](https://github.com/Expensify/App/issues/40261#issuecomment-2058302264); we can go with them.

🎀 👀 🎀 C+ reviewed

It's kind of a little hard for me to decide, but let's see what internal engineer think of:

**Comment by danielrvidal** [comment]
@tienifr given this is pretty straight forward, do you think your PR could be done today? This is just a high-priority issue, so I want to make sure to get a timeline with urgency. Thank you!

**Comment by danielrvidal** [comment]
Thank you @GandalfGwaihir, @tienifr if you can get the PR up by tomorrow, that would be great.

**Comment by jayeshmangwani** [comment]
Thanks for the PR, starting PR review

**Comment by trjExpensify** [comment]
PR hit production a couple of days ago. Updating the title to reflect the payment hold and adding the bug label to assign a BZ... that happens to be me. :)

**Comment by MariaHCD** [comment]
Not overdue; on payment hold.

**Comment by trjExpensify** [comment]
Alright.. payment summary as follows: 

- $250 to @tienifr for the bug fix
- $250 to @jayeshmangwani for the C+ review

Settled up with you both, closing!
