### ISSUE TITLE
[Wave Collect] New Resources to Publish: Invoicing 

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#40269]
### Publish Date - May 1st

Related External Resource GH: https://github.com/Expensify/Expensify/issues/383907
Draft of HelpSite article - https://docs.google.com/document/d/1s2X1h-1QkLDtXPcIHr6MOH1nKN4ZJTr9jeqcgeG7-r0/edit

**Comment by Christinadobrzyn** [comment]
Following this SO - https://stackoverflowteams.com/c/expensify/questions/17951

Posted for Ren in expensifyhelp - https://expensify.slack.com/archives/C02QSAC6BJ8/p1713245636574859

**Comment by Christinadobrzyn** [comment]
ooo sick - I'll be back on Monday (APAC) to check on this

**Comment by Christinadobrzyn** [comment]
working through the draft - https://docs.google.com/document/d/1s2X1h-1QkLDtXPcIHr6MOH1nKN4ZJTr9jeqcgeG7-r0/edit

**Comment by Christinadobrzyn** [comment]
Hi Ren! Thank you!! Sorry I'm not quite sure what to do next, can you guide me?

**Comment by ren-jones** [comment]
Article is complete and has been pushed

**Comment by Christinadobrzyn** [comment]
Amazing! thank you so much Ren! 🎉

**Comment by Christinadobrzyn** [comment]
It looks like the article is live - https://help.expensify.com/articles/new-expensify/expenses/Send-an-invoice

Thank you Ren! I think this can be closed but let me know if it needs to remain open.
