### ISSUE TITLE
[Track Expense] Investigate Tracked SmartScan

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C03U7DCU4/p1713069054612919

## Action Performed:
1. Track Expense from global create
2. Choose Scan Receipt and smartscan a receipt

## Expected Result:
The receipt in NewDot should be done scanning and updated

## Actual Result:
Describe what actually happened
<img width="354" alt="Screenshot 2024-04-15 at 7 17 24 PM" src="https://github.com/Expensify/App/assets/30609178/0b3bd4b7-ba90-4ef2-82e6-aa9d3a532563">

The receipt still shows as 'Scan in progress...'

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b712948f76c6c821</li>
        <li>Upwork Job ID: 1780058239099588608</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by quinthar** [comment]
I think this self resolved; just worked for me.  Closing until we experience it again.
