### ISSUE TITLE
CRITICAL: [Actionable Whispers] The report total is negative when converting a tracked expense to request

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

Note: This occurs as part of a feature from this [PR](https://github.com/Expensify/App/pull/38709)

Break down in numbered steps
1. Track an expense to the self-DM
2. Convert it to a request on an IOU that already has an existing IOU

## Expected Result:
The reportPreview should show correct amount owed

## Actual Result:
The reportPreview shows negative amount owed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebe41f88ebb9d14a</li>
        <li>Upwork Job ID: 1780061708144013312</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thienlnam</details>

**Comment by thienlnam** [comment]
Seems like a BE issue

**Comment by thienlnam** [comment]
I am seeing that this is also fixed in https://github.com/Expensify/Auth/pull/10564 as well

**Comment by quinthar** [comment]
Great, can we close this?

**Comment by thienlnam** [comment]
Yup, this is on production now

**Comment by thienlnam** [comment]
This is still happening when converting tracked expenses to requests on an IOU with existing requests - https://expensify.slack.com/archives/C03U7DCU4/p1715000997219589
cc @shawnborton / @dannymcclain

**Comment by thienlnam** [comment]
Found the issue - it relies with how we handle the amount negative values for IOUs depending on who is the owner of the IOU. Working on it here https://github.com/Expensify/Auth/pull/10798

**Comment by thienlnam** [comment]
Fix is in review

**Comment by thienlnam** [comment]
Merged - pending deploy

**Comment by thienlnam** [comment]
We're done here!
