### ISSUE TITLE
[HOLD for payment 2024-05-02] [QAB] [Follow-up] Skip confirmation screen for track expenses

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#40282]
HELD on https://github.com/Expensify/Expensify/issues/378892 and https://github.com/Expensify/App/issues/38051

Since Track functionality was added later, we are currently not skipping the confirmation screen in track flows. As a follow up to [this issue](https://github.com/Expensify/App/issues/38051), we want to do so.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163a5f58b3ed495c7</li>
        <li>Upwork Job ID: 1780188713666760704</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Alright, payment summary as follows:

- $250 to @hoangzinh for the C+ review 

Regression tests for this new feature are being added centrally. Offer sent!

**Comment by trjExpensify** [comment]
Paid!
