### ISSUE TITLE
[$250] [Groups] Allow users to "share" Group Chats via share code.

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#40299]
While we de-scope share codes for the initial Group chats implementation, we're now in the polish phase and also in the process of re-designing the details pages throughout the app, so we'd like to add `Share` functionality now. The basic design looks like so. 

![Image](https://github.com/Expensify/App/assets/1127863/8445ed0e-7a1a-4503-9293-bb0f2d96dd25)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015064b59f1a49ec6e</li>
        <li>Upwork Job ID: 1780260742659428352</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
@JmillsExpensify It seems this is dupe https://github.com/Expensify/App/issues/40256

**Comment by JmillsExpensify** [comment]
Oh whoops. Ok yeah, I missed that share is part of that one. Thanks! I'll close this one.
