### ISSUE TITLE
HIGH: [Debugability] [$250] Add logs for network queue length

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#40297]
### Problem
It's difficult to recognize when there is an issue with the App's network queue especially in production. If the queue gets stuck and fails to process any new requests, it's difficult to recognize when this is happening without logging. This is a critical problem because all reads are blocked on the write queue.

### Solution
Add the current length of the network queue to the log whenever another API command is queued. This should make it easy to recognize when the app is failing to clear the queue just by viewing logs.

Specifically, we should 

- log the length of [persistedRequests](https://github.com/Expensify/App/blob/b99fe401ef3152af8d043b02fa22771be0cb6f98/src/libs/actions/PersistedRequests.ts#L6) when requests get [added to the SequentialQueue](https://github.com/Expensify/App/blob/6e1895a5e8eb1b84bcac047ed6cb484f7beb06de/src/libs/Network/SequentialQueue.ts#L162)
- log when a read is being blocked by queued writes [here](https://github.com/Expensify/App/blob/dcc089fdf46f731fb78f79dc82cf87f327e63e79/src/libs/API/index.ts#L162)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c1fa89f2e72f914</li>
        <li>Upwork Job ID: 1780254517492736000</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
While I understand the job is straight forward, @gijoe0295 @tienifr let's have a basic content on the proposal. Let's not copy-paste GH issue description.

**Comment by mananjadhav** [comment]
@tienifr's proposal looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by dharmeshsavaliya** [comment]
https://www.upwork.com/freelancers/~01c904f03c8c8d30d0

**Comment by dharmeshsavaliya** [comment]
Contributor details
Your Expensify account email: dharmesh1809@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c904f03c8c8d30d0

**Comment by dharmeshsavaliya** [comment]
Contributor details
Your Expensify account email: dharmesh1809@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c904f03c8c8d30d0

**Comment by arosiclair** [comment]
@tienifr's proposal looks good let's just modify the logs slightly:

```javascript
Log.info(`[SequentialQueue] '${commandName}' command queued. Queue length is ${PersistedRequests.getLength()}`);
```

```javascript
if (PersistedRequests.getLength() > 0) {
    Log.info(`[API] '${commandName}' is waiting on ${PersistedRequests.getLength()} write commands`);
}
```

**Comment by mananjadhav** [comment]
@strepanier03 This is ready for payout and did you get a chance to look at the previous comment by @tienifr.

**Comment by mananjadhav** [comment]
Quick bump @strepanier03

**Comment by strepanier03** [comment]
@tienifr - Can you accept the offer so I can pay it at $500? Or I can cancel the offer entirely and make a new one, your choice.

**Comment by mananjadhav** [comment]
@strepanier03 I'll need a payout summary on the issue to raise it on NewDot. Could you add that as well please?

**Comment by strepanier03** [comment]
### Payment Summary

- @mananjadhav - $500 via Manual Requests
- @tienifr - $500 paid via Upwork

@JmillsExpensify - Payment request incoming.

**Comment by strepanier03** [comment]
Go ahead @mananjadhav - I'll close this and let you handle the manual request now. 

Thanks again everyone 🙌

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav
