### ISSUE TITLE
CRITICAL: [Actionable Whispers] [$250] All actionable whisper actions are resolved with 'None'

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40306]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Currently on dev
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

Note: This occurs as part of a feature from this [PR](https://github.com/Expensify/App/pull/38709)

Break down in numbered steps
1. Track an expense
2. Notice you see an actionable whisper
3. Select any / all of the options

## Expected Result:
If you check the reportAction data, it should show as the resolution of whatever option was selected

## Actual Result:
They all show as resolved as none

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e41c6321097b3ff7</li>
        <li>Upwork Job ID: 1780290981003022336</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
This is a BE fix

**Comment by tgolen** [comment]
I think I can take this one. I see where the resolution is always set to "nothing" in the [FE](https://github.com/Expensify/App/blob/5e3cca2f8b661e56d7245be8844bd4df7b2dccec/src/libs/actions/IOU.ts#L2542) and the [BE](https://github.com/Expensify/Auth/blob/603ea5ae5b0c499702a79100efb3077b47fb4536/auth/lib/ReportAction.cpp#L1474).

I assume the actions needing done here are:
1. Update the backend to specify a different resolution depending on the API command that is called (corresponding to: share, categorize, and move)
2. Update the frontend to specify the resolution in a similar fashion

It sounds like those can be done in any order.

**Comment by thienlnam** [comment]
Yup that's correct - the FE just checks whether or not anything is present in the resolution key, so we can do this in either order

**Comment by tgolen** [comment]
While looking into the code more in depth, it's a little more complex and there will need to be a Web-E change as well. In Web-E, the `share` and `categorize` actions both call the same Auth command `AddTrackedExpenseToPolicy`. This means that I will need to introduce a parameter to the `AddTrackedExpenseToPolicy` Auth command for `action` which will specify the exact resolution the user wanted. This can be passed straight to `ReportAction::dismissActionableWhisper()` as a third parameter called "resolution".

**Comment by tgolen** [comment]
# Daily Update
- I created an [Auth PR](https://github.com/Expensify/Auth/pull/10563) to add the resolution parameter to the `AddTrackedExpenseToPolicy` command

### Next Steps
- Create a Web-E PR that implements the new Auth parameter
- Create an App PR that modifies the optimistic data to contain the proper resolution data

#### ETA
- Auth PR merged tomorrow, April 16
- Web-E PR merged Thursday, April 18
- App PR merged Thursday, April 18

**Comment by tgolen** [comment]
# Daily Update
- I created a [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41699) to implement the new param which has already been merged
- I created a [draft App PR](https://github.com/Expensify/App/pull/40358/) with the necessary changes

### Next Steps
- @tgolen get the [Auth PR](https://github.com/Expensify/Auth/pull/10563) merged (needs a review from @techievivek)
- @tgolen once the Web-E and Auth PRs are deployed, get the App PR tested, reviewed, and merged

#### ETA
- Auth PR merged today, April 16
- App PR merged Monday, April 22 (to account for deploys)

**Comment by quinthar** [comment]
Wow, this is a gnarly one!

**Comment by quinthar** [comment]
Can we close this?

**Comment by tgolen** [comment]
Yes. Sorry, it fell off my radar being marked as reviewing. Everything is deployed and this is finished!
