### ISSUE TITLE
CRITICAL: [Actionable Whispers] Changes Error converting tracked expense to a user with an existing IOU

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

Note: This occurs as part of a feature from this [PR](https://github.com/Expensify/App/pull/38709)

Break down in numbered steps
1. Create 2 accounts A and B
2. Logged into B, request money from A
3. Logged into A, created a tracked expense
4. Using the actionable whisper, convert it into a request for B
5. 

## Expected Result:
It should be converted and work as expected

## Actual Result:
We see an API error

```
{
    "jsonCode": 401,
    "message": "401 Target report doesn't belong to the transaction owner.",
    "onyxData": [],
    "requestID": "8743de65b8d654d7-DEL"
} 
```

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e41c6321097b3ff7</li>
        <li>Upwork Job ID: 1780290981003022336</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
This is a BE API issue

**Comment by thienlnam** [comment]
Able to reliably reproduce - there are a couple of issues here one is the IOU seems to not be getting shared with the participant, and the other is the owner is not switching correctly

**Comment by quinthar** [comment]
@thienlnam can you give an ETA on this?

**Comment by thienlnam** [comment]
Should have something into review by EOD

**Comment by thienlnam** [comment]
Live!
