### ISSUE TITLE
CRITICAL: [Actionable Whispers] Changes when categorizing / sharing a tracked expense are not saved

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40304]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

Note: This occurs as part of a feature from this [PR](https://github.com/Expensify/App/pull/38709)

Break down in numbered steps
1. Create a workspace
2. Create a tracked expense
3. Choose to categorize it 
4. Update the transaction details in the final confirmation page

## Expected Result:
The new shared/categorized transaction details should be saved

## Actual Result:
They are not

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015eae82d8e6ef3565</li>
        <li>Upwork Job ID: 1780290065653587968</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
This is something that will need to be fixed in the BE

**Comment by thienlnam** [comment]
Changes are merged- pending deploy

**Comment by garrettmknight** [comment]
Just tested and this looks like the tracked expense info is being saved.

**Comment by thienlnam** [comment]
Noice!
