### ISSUE TITLE
Add support for Descriptions in Group Chats

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40312]
Coming from https://expensify.slack.com/archives/C05RECHFBEW/p1712957571237659

## Problem 

When we implemented Group Chats we did not give the ability to add a Description. This is largely do to the fact that we undertook a large migration of Group DMs over to Group Chats and are now harmonizing these two similar designs (Rooms & Groups).

## Solution

When this ticket is done we should have the ability to add a Description to a "Group Chat" at creation and also update that description from the "Report Details" page.

![Image](https://github.com/Expensify/App/assets/32969087/3a6725b9-0994-4a4f-838c-6a6bd6c7f02c)

Additionally, we should have the ability to create a description at the time when a Group Chat is created.

And lastly, we should ensure that: 

- The CREATE action message + invitee "whisper" message includes the room description. Here's how it works for rooms:

![Image](https://github.com/Expensify/App/assets/32969087/dc826893-23d8-453d-bd11-db5ab98b748b)

![Image](https://github.com/Expensify/App/assets/32969087/8a15d1fb-3a62-4f8e-aa60-e7e0b7f4c806)

- The email sent when inviting a user should display like this: 

**Subject:** `# [inviter] invited you to [RoomTitle]`
**Body:** `[RoomDescription]`

**Backend changes:**

I'd suggest we follow the existing pattern of reusing any possible code from Auth related to Rooms. In this case, the commands would be:

`CreatePolicyRoom` and `UpdateRoomDescription`. We create Group chats when calling `OpenReport` so reusing `CreatePolicyRoom` directly would be incorrect here.

**Frontend changes:**

Once we can support Group chat descriptions in the backend we can open this up to a contributor to wire up the UI changes and API. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01472e1c18fbc629f5</li>
        <li>Upwork Job ID: 1780332023202934784</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by isabelastisser** [comment]
Waiting for engineering assignment.

**Comment by isabelastisser** [comment]
Not overdue.

**Comment by JmillsExpensify** [comment]
@isabelastisser I'm going to take this one on, if you don't mind. Trying to get a handle on what remains for the group chat implementation.

**Comment by JmillsExpensify** [comment]
Still in the queue for group chats.

**Comment by JmillsExpensify** [comment]
Still in the queue.

**Comment by JmillsExpensify** [comment]
Same.

**Comment by JmillsExpensify** [comment]
Not a priority

**Comment by JmillsExpensify** [comment]
Not a priority.

**Comment by JmillsExpensify** [comment]
Still not a priority

**Comment by marcaaron** [comment]
This might be a good one for Back End Contributors to tackle if we closed it because it wasn't a priority.
