### ISSUE TITLE
Fix Quick Button track expenses names

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#40324]
**Problem**
In Track flows, the quick button states "Track manual" and "Track scan" when it should say "Track expense" and "Track receipt"

**Solution**
Fix it

**Comment by Gonals** [comment]
No need for c+ on this one, since it is just a very small copy change

**Comment by zanyrenney** [comment]
@Gonals, please can you ensure you update this issue with the ksv2 cadence? It's half me to know what's going on here and what my action is. It sounds like this contributor is working on this and you will potentially review the change? Is that the plan?

**Comment by Gonals** [comment]
Nope. I worked on it myself and it is already merged (with no contributors involved), so nothing more to do here. You can probably unassign yourself 😁
