### ISSUE TITLE
[HOLD for payment 2024-05-22] [Wave Collect] New Resources to Publish - Drafts and Tags

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#40331]
Publish Date: May 1st 2024
Tracking GHs [Tags]: https://github.com/Expensify/Expensify/issues/309856
Tracking GH [Drafts]: https://github.com/Expensify/Expensify/issues/320029
Following the steps in: https://stackoverflowteams.com/c/expensify/questions/17951

Draft and Tags on expenses - [draft](https://docs.google.com/document/d/1RhdgMXYwRSUWPed07fW0u17kie9OGrj4qu71kh4F6jg/edit#heading=h.wjp0outacth8)

Tags overview - [draft](https://docs.google.com/document/d/1-p3GdWQNN2nDorgS5ptKYyPEIxLd2FDp0ffdipYQXYE/edit)

cc @ren-jones 

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by Christinadobrzyn** [comment]
reached out to Ren in slack for a review - https://expensify.slack.com/archives/C02QSAC6BJ8/p1713751151196269

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by Christinadobrzyn** [comment]
yay! Thank you @ren-jones! I [shared the draft](https://docs.google.com/document/d/1RhdgMXYwRSUWPed07fW0u17kie9OGrj4qu71kh4F6jg/edit?pli=1#heading=h.wjp0outacth8) with you and have you on this GH. 

Can you tell me if there's something else that needs to happen to assign this to you? Thanks!

**Comment by Christinadobrzyn** [comment]
[Discussing with](https://expensify.slack.com/archives/C02QSAC6BJ8/p1714250106180459) @maddylewis where this update should live in the Help Site. I'm thinking on the [Request Money page](https://help.expensify.com/articles/new-expensify/expenses/Request-Money)

**Comment by Christinadobrzyn** [comment]
Hi @ren-jones - I [updated some of the draft based on your questions](https://docs.google.com/document/d/1RhdgMXYwRSUWPed07fW0u17kie9OGrj4qu71kh4F6jg/edit), feel free to take a peek and let me know what else might be helpful. thanks!

**Comment by Christinadobrzyn** [comment]
this is ready to be published - https://docs.google.com/document/d/1RhdgMXYwRSUWPed07fW0u17kie9OGrj4qu71kh4F6jg/edit

**Comment by Christinadobrzyn** [comment]
@ren-jones per my ping in Slack - https://expensify.slack.com/archives/C02QSAC6BJ8/p1714535381876289?thread_ts=1714416938.388449&cid=C02QSAC6BJ8

 I think I missed the mark on my Tag article and should have created an 'overview' article similar to our [Category article](https://docs.google.com/document/d/1VKLlZDK2GJtdbpsfKmSbBOySbpeViL11TiUSY9h1Sjo/edit). 

I created the article here - https://docs.google.com/document/d/1-p3GdWQNN2nDorgS5ptKYyPEIxLd2FDp0ffdipYQXYE/edit and shared it with you. Let me know your thoughts!

**Comment by ren-jones** [comment]
I believe tags is now the final article for this grouping, and I'll start working on that one soon!

**Comment by Christinadobrzyn** [comment]
Hi @ren-jones! I reviewed the new Tags resource and it's ready for you! Thank you!

https://docs.google.com/document/d/1-p3GdWQNN2nDorgS5ptKYyPEIxLd2FDp0ffdipYQXYE/edit

**Comment by Christinadobrzyn** [comment]
working on some final comments in the doc https://docs.google.com/document/d/1-p3GdWQNN2nDorgS5ptKYyPEIxLd2FDp0ffdipYQXYE/edit

**Comment by Christinadobrzyn** [comment]
watching PRs!

**Comment by Christinadobrzyn** [comment]
@ren-jones are we paying you through Upwork for each job or all at once?

**Comment by Christinadobrzyn** [comment]
asking about payment method - https://expensify.slack.com/archives/C02QSAC6BJ8/p1716357419129409
