### ISSUE TITLE
Android - Chat - Composer is not focused

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40347]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the App
2. Login with any account
3. Open any chat

## Expected Results:
Composer is focused

## Actual Result:
Composer is not focused

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/8b7ae1fa-70eb-4e41-80a1-d3db21270ff0)

https://github.com/Expensify/App/assets/93399543/fee543b6-ce3a-4797-94a6-e2f0f00434e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@muttmuure FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by FitseTLT** [comment]
@muttmuure We are intentionally disabling auto-focus on mobile unless the report is empty because the keyboard opening is bad for UX but if the report is empty chat, it would make sense as the user has nothing to see and most probably opened to write some txt 👍

**Comment by muttmuure** [comment]
Sounds like this isn't a bug. Closing.
