### ISSUE TITLE
[Awaiting checklist completion][$250] LHN - HTML "<h1>" tag can be seen on the #admins room LHN preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40348]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61.8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/Expensify/issues/380529
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with a new Gmail account
2. Create a workspace
3. Navigate to the LHN

## Expected Result:
HTML tags shouldn't be visible.

## Actual Result:
HTML "<h1>" tag can be seen on the #admins room LHN preview. It's not visible in the room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6451424_1713287386029!Capture (1)](https://github.com/Expensify/App/assets/115492554/d26c4242-7058-4c94-8330-1bfde418d968)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3428578236ce20d</li>
        <li>Upwork Job ID: 1780883160992833536</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by izarutskaya** [comment]
@twisterdotcom I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by twisterdotcom** [comment]
Pretty sure this is a dupe

**Comment by twisterdotcom** [comment]
Yes, sorry, being pulled into something else but will look again in a bit. I opened this tab, said that, searched and immediately got distracted, my bad.

**Comment by twisterdotcom** [comment]
So, here are the issues I think I was thinking about:

https://github.com/Expensify/Web-Expensify/pull/37784
https://github.com/Expensify/App/issues/20590

Basically, I think that we show HTML in the LHN is expected, given @puneetlath closed the last issue I see for this above.

Going to get a C+ involved for their take too, because I agree this would be nice to clean up though if you can do it.

**Comment by tylerkaraszewski** [comment]
@allroundexperts ?

**Comment by tylerkaraszewski** [comment]
melvin, I told you to go away.

**Comment by twisterdotcom** [comment]
Thanks so much for the patience here folks. Always crazy coming back from a week out.

Payment Summary:

- @allroundexperts paid $250 via NewDot Manual Requests (C+)
- @GandalfGwaihir paid $250 [here](https://www.upwork.com/nx/wm/workroom/37049424/overview) (Contributor)

**Comment by twisterdotcom** [comment]
@allroundexperts we just need the regression steps here.

**Comment by allroundexperts** [comment]
## Checklist
1. I was not able to find the exact PR. I think that something changed on the backend which caused this.
2. N/A
3. N/A
4. A regression test would be helpful. The test steps given in the OP look good enough to me.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
