### ISSUE TITLE
[HOLD for payment 2024-04-25] Workspace - Deleting a message on "Announce" room takes user to another report page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-13
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/Expensify/issues/365980
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a new workspace
3. Go to the "#announce" room of the same workspace
4. Send a message
5. Delete the sent message

## Expected Result:
Page should be in announce room after deleting the message

## Actual Result:
Page redirects to another page after deleting the message e.g page navigates to workspace chat page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6836d8de-c88a-4fd5-a086-dbad19db83f9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@trjExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by hungvu193** [comment]
Regression from this one: https://github.com/Expensify/App/pull/40155
This line: https://github.com/Expensify/App/blob/967f9b00db5e4bfddc9efd2550ddba0783a9c9bc/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx#L277-L279

cc @rayane-djouah

**Comment by youssef-lr** [comment]
Thanks @hungvu193! @rayane-djouah @rushatgabhane can you guys take a look please?

**Comment by roryabraham** [comment]
this was a regression fixed on staging by the author of the PR that caused it, so we can close this out without payment
