### ISSUE TITLE
[TS migration] Migrate tests to Typescript (react-native-onyx)

### ISSUE THREAD

**Issue by smelaa** [Expensify/App#40355]
# Typescript migration (react-native-onyx)

Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/TS_STYLE.md), [cheatsheet](https://github.com/Expensify/App/blob/main/contributingGuides/TS_CHEATSHEET.md) and [PropTypes conversion table](https://github.com/Expensify/App/blob/main/contributingGuides/PROPTYPES_CONVERSION_TABLE.md) before you start working on this migration issue.

### Files
`components/ViewWithCollections.js`
`components/ViewWithObject.js`
`components/ViewWithText.js`
`unit/storage/providers/IDBKeyvalProviderTest.js`
`unit/storage/providers/StorageProviderTest.js`
`unit/DevToolsTest.js`
`unit/cacheEvictionTest.js`
`unit/fastMergeTest.js`
`unit/onyxCacheTest.js`
`unit/onyxClearNativeStorageTest.js`
`unit/onyxClearWebStorageTest.js`
`unit/onyxMultiMergeWebStorageTest.js `
`unit/onyxTest.js`
`unit/subscribeToPropertiesTest.js `
`unit/useOnyxTest.ts `
`unit/withOnyxTest.js `
`utils/waitForPromisesToResolve.js`

**Comment by MahmudjonToraqulov** [comment]
I'd like to work on it.

**Comment by mountiny** [comment]
@smelaa from SWM will handle this one

**Comment by sonialiap** [comment]
Hi Błażej, thanks for taking over :) I'm assigning you to this issue

**Comment by sonialiap** [comment]
👋 @blazejkustra any updates on this issue?

**Comment by blazejkustra** [comment]
I migrated all files yesterday, today it should be ready for internal review 👌

**Comment by blazejkustra** [comment]
PR was merged! We can close this issue now. Thanks for your patience @sonialiap 😄

**Comment by sonialiap** [comment]
Handled by SWM, no payment needed
