### ISSUE TITLE
Merge conflicts in CP PRs are not handled well

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#4036]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a PR with changes in a given file.
1. Give the PR the `CP Staging` label.
1. Merge the PR.
1. Create another PR with changes in the same file (to ensure that there will be conflicts on staging).
1. Give the PR the `CP Staging` label.
1. Merge the PR.
1. The CP PR created for the second PR will be created but not automerged, due to conflicts. 

## Expected Result:
1. The CP PR should be auto-assigned to the author of the original (second) PR.
1. PR checks (lint, test, etc...) should run on the CP PR.

## Actual Result:
1. The PR was not auto-assigned.
1. PR checks did not run on the CP PR, even after manually pushing new code to the PR.

## Workaround:
n/a

## Platform:
GitHub only

**Version Number:** `1.0.77-2`

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by iwiznia** [comment]
@parasharrajat this is a test, please ignore this message

**Comment by HorusGoul** [comment]
Will work on this next week

**Comment by HorusGoul** [comment]
I haven't been able to work on this. I'll return this to the pool as I'm going to be OOO for a few days. I'll gladly pick it after that again as I'll have less workload.

**Comment by HorusGoul** [comment]
It's still free so I'll pick it again 😄

**Comment by HorusGoul** [comment]
I've been looking through the marketplace of actions to see if there was one to assign people to PRs. All I've found is related to self-assigning when a user creates a PR. Unless someone knows an action to assign someone to a PR, I'll take a look at the API tomorrow, it's probably easier to build our own, and we already have everything set up for that.

**Comment by roryabraham** [comment]
We use other `actions-ecosystem` actions and they seem to be pretty good. The maintainer is responsive and has merged a couple of my PRs.

**Comment by HorusGoul** [comment]
Oh! That looks to be the one, great 😄

**Comment by HorusGoul** [comment]
I'm not sure about this `PR checks (lint, test, etc...) should run on the CP PR.`. I think there's no way to trigger the PR checks from a GitHub Action. More info: https://github.community/t/manually-triggering-checks-for-a-pr/134054

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1197747761) to staging by @pecanoro in version: 1.0.92-6 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1199734951) to production by @roryabraham in version: 1.0.93-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅
