### ISSUE TITLE
[HOLD for payment 2024-05-09] [Desktop] Create a page to show when we fail to close the window during the QBO Authentication flow

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#40365]
This is a follow up to this comment: https://github.com/Expensify/App/pull/39219#issuecomment-2060202899

When the QBO flow finishes, the backend sends `<script>window.close();</script>` to close the tab we opened. The problem is this fails for Desktop and we get the following message in the console:

![image](https://github.com/Expensify/App/assets/87341702/1c5ded3c-94aa-4ac5-bcd9-17ce738a87ba)

and we end up with a white screen.

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by aldo-expensify** [comment]
Added `Design` label so we can work on what we want as a solution. I see two improvements we can do:

1. Create page for the end of the authentication flow that will only be visible if the javascript snippet to close the window fails. This page should have some message like "Close this window and continue in the Expensify App", and
2. Try to redirect the user to the Desktop app using a deep link

<img width="1171" alt="image" src="https://github.com/Expensify/App/assets/87341702/5c0908c1-0ff3-4f70-afb7-bc1a7b1b3cdf">

**Comment by aldo-expensify** [comment]
cc @s77rt @hayata-suenaga 

Created separate issue to decide how we want to handle the Desktop case

**Comment by shawnborton** [comment]
How about something like this?
![image](https://github.com/Expensify/App/assets/2319350/53bf7c13-7854-4be6-9ecd-79c6e0d72254)

We already have this kind of page template for the passwordless flows, so it should be easy to implement (famous last words). 

cc @Expensify/design for thoughts too

**Comment by aldo-expensify** [comment]
@shawnborton that looks great to me!

**Comment by dannymcclain** [comment]
I love it!

>so it should be easy to implement (famous last words)

😂

**Comment by shawnborton** [comment]
I think they already exist. Take a look at [this PR here](https://github.com/Expensify/App/pull/40337) - it's adding animations to the pages that already exist, in case that is helpful at all.

**Comment by aldo-expensify** [comment]
Thanks, that helps

**Comment by aldo-expensify** [comment]
do you know if there is a version of the laptop image that is animated? and if there is, where is the right place to get this?

**Comment by dubielzyk-expensify** [comment]
Uploaded the static one in the Slack thread here https://expensify.slack.com/archives/C03TME82F/p1713407507785619?thread_ts=1713403069.080199&cid=C03TME82F

If it's not already checked in. No idea if we have an animated version. I tried looking in Dropbox, but couldn't find anything. Maybe @shawnborton and @dannymcclain know.

**Comment by shawnborton** [comment]
Replied to the thread but also sharing here - let's use this updated version that has better spacing around the illustration content: [emptystate__connectioncomplete.svg.zip](https://github.com/Expensify/App/files/15023065/emptystate__connectioncomplete.svg.zip)

We unfortunately don't have an animated version of this, but I think that's okay.

**Comment by isabelastisser** [comment]
No payment is needed. @aldo-expensify, can I close this? Thanks!

**Comment by aldo-expensify** [comment]
> No payment is needed. @aldo-expensify, can I close this? Thanks!

Yep!
