### ISSUE TITLE
[$250]  iOS - Chat - Emojis are not displayed properly in the emoji picker

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40360]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-14
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Open emoji picker

## Expected Result:
The emojis are displayed properly in the emoji picker

## Actual Result:
The emojis are not displayed properly in the emoji picker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7512f006-14f2-46cf-9c37-485708139daa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f12625c61a6be308</li>
        <li>Upwork Job ID: 1780702679365181440</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rlinoz** [comment]
Not being able to repro, gonna ask for help on slack

**Comment by dylanexpensify** [comment]
Can repro @rlinoz!

**Comment by rlinoz** [comment]
Hmmm maybe this is related to `FlashList` as well.

https://github.com/Expensify/App/blob/51bebd5c1e5a438ac1299424917d5a6311cbdfe1/src/components/EmojiPicker/EmojiPickerMenu/BaseEmojiPickerMenu.tsx#L103

**Comment by rlinoz** [comment]
Ok, after cleaning node modules and starting over it is reproducible in the emulator.

**Comment by rlinoz** [comment]
I'm not sure how to solve this and I gotta go, so I will open up for proposals.

**Comment by strepanier03** [comment]
This was repro'd by an Expensify employee with a physical device. I don't have an iPhone and my browserstack isn't working right now, the app crashes. 

----

I don't necessarily think this should block deploy though. The emoji picker still works, you can search for an emoji to narrow down results, and it's working elsewhere. 

I'm in no way an expert on deploying so I'll wait for more knowledgeable individuals to weigh in.

**Comment by roryabraham** [comment]
I do think this should be a deploy blocker, the emoji picker looks very broken

**Comment by rlinoz** [comment]
This is fixed, thanks!

<img width="430" alt="image" src="https://github.com/Expensify/App/assets/5201282/003fc895-bf3c-44f0-b50a-73a181e1bf7b">
