### ISSUE TITLE
Login - "Hmm it"s not here" error when navigating the IOU confirmation URL and logging in

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62.14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/Expensify/issues/328822
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with an expensifail account
2. Navigate to FAB - Request money - Manual
3. Start the request and stop at the confirmation page
4. Copy the URL
5. Log out
6. Navigate to the copied URL
7. Log in

## Expected Result:
I should be navigated to the conformation page.

## Actual Result:
"Hmm it"s not here" error when navigating the IOU confirmation URL and logging in.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b1ffa029-448c-49c9-be7e-3844ef0f0411

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
I think this is edge case and not worth fixing, to reach the request people are going to navigate to it within newdot, I don't think there is a case where someone will save the URL and try to navigate back to it.
