### ISSUE TITLE
"Set up" button flashes after QBO authentication finishes

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#40377]
Reported here: https://github.com/Expensify/App/pull/39219#issuecomment-2060197992

https://github.com/Expensify/App/assets/16493223/bf4ff7de-e38f-412c-aa1d-e4ec20a11c98

___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01727b7169ced1ccbf</li>
        <li>Upwork Job ID: 1782479954581876736</li>
        <li>Last Price Increase: 2024-04-22</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment]
Not sure how to go about this yet.

**Comment by abekkala** [comment]
@aldo-expensify, do you want this internal or external?

**Comment by aldo-expensify** [comment]
I'm planning on working on this myself when I get some time.

> @aldo-expensify , the condition && connectionSyncProgress.stageInProgress !== CONST.POLICY.CONNECTIONS.SYNC_STAGE_NAME.JOB_DONE;  shouldn't be used here:

Thanks @GandalfGwaihir , I know why this is happening, but I haven't thought yet how I'm going to fix it. The problem is that the stage goes to `jobDone` before receiving the `policy.connections` data, so for a brief moment we are neither syncing nor have connection data.

**Comment by abekkala** [comment]
not overdue - @aldo-expensify will be working on this, labeling internal

**Comment by aldo-expensify** [comment]
I'm working on fixing the WebView crash for IOS first, I'll get to this after that

**Comment by abekkala** [comment]
not overdue, Aldo has this job up next

**Comment by aldo-expensify** [comment]
This is fixed in staging thanks to:

https://github.com/Expensify/Integration-Server/pull/7884
https://github.com/Expensify/Web-Expensify/pull/41838
