### ISSUE TITLE
[HOLD for payment 2024-05-02] [$750] [CRITICAL] Create a reusable and stylable `MoneyRequestAmountInput` 

### ISSUE THREAD

**Issue by youssef-lr** [Expensify/App#40382]
## Problem

the `MoneyRequestAmountForm` is currently designed to be used from the Amount pages where it is displayed in a view that takes up the whole page, and has specific style for that. We'd like to reuse this input without any extra style and be able to re-style it with ease.

## Solution

Decouple the logic that handles accepting and formatting amounts from `MoneyRequestAmountForm`, by creating a new `MoneyRequestAmountInput` that doesn't have any custom styles and looks like a basic input.

1. Move all the logic for handling input from `MoneyRequestAmountForm` into the new input.
2. The `MoneyRequestAmountForm` should only keep navigation and form logic.
3. The input should have a new callback `onAmountChange` that can be used by parent components.
4. Display currency as part of the input as in the mocks. For this we can simply use the `prefixCharacter` that should be prop drilled into the underlying `TextInput` used in this component. We will need to configure the padding of the prefix text to accomodate for both single character currencies and 3 characters currencies. (e.g. `$` and `AED`). Since the prefix is absolutely positioned, this is necessary.
5. The new input should accept styles so that it can be reused from the Amount full pages, e.g. no borders, increased font, etc.

Here's a mock of how the input should look like when used from the Splits page:

<img width="186" alt="Screenshot 2024-04-17 at 22 13 15" src="https://github.com/Expensify/App/assets/9680864/e23f8e7e-9f9b-4d3a-bb5a-4db777b0dc5d">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6b340c95c53b510</li>
        <li>Upwork Job ID: 1780706666038550528</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by youssef-lr** [comment]
@ZhenjaHorbach Are you able to give this your top priority? The deadline is very tight for this one, if yes, I'm happy to assign you!

**Comment by youssef-lr** [comment]
That sounds good!

**Comment by hungvu193** [comment]
This new feature so I don't think we need regression test for this one.

**Comment by youssef-lr** [comment]
@jliexpensify increasing bounty here as @ZhenjaHorbach has been very kind to help out with styling the input further for my specific use case.

**Comment by jliexpensify** [comment]
No worries, here's an updated Summary (I assume C+ gets the same?):

- C: @ZhenjaHorbach $750
- C+: @hungvu193 $750

[Upwork job](https://www.upwork.com/jobs/~01f6b340c95c53b510)

**Comment by jliexpensify** [comment]
Ah, thanks for clarifying - fixed!

**Comment by youssef-lr** [comment]
Thanks!

**Comment by jliexpensify** [comment]
All paid and job removed! @ZhenjaHorbach I've given you a $250 bonus, so you'll get $750 all up.
