### ISSUE TITLE
[Guided Setup Stage 2] [Hold for introducing videos] Fix the order of messages 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#40387]
Coming from [this convo](https://expensify.slack.com/archives/C036QM0SLJK/p1713360992240979). Creating this issue as a placeholder so we don't forget about it. 

When Michael was pushing forward with including videos in the onboarding tasks, he noticed the ordering of the messages was wrong. 

_"The app sets the `created` date properly. However, once the app gets data from the backend, the video is the last message. It happens because the backends sets the `created` property a little bit incorrectly."_

Vit thinks this is because don't set the `create` timestamps optimistically, so we need to ensure the correct order somehow. 

![Optimistic view](https://github.com/Expensify/App/assets/16232057/9f6a2b83-c9f6-4dff-9ccc-2f4988eab6fc)

![OpenReport](https://github.com/Expensify/App/assets/16232057/9b10454b-ecf9-482e-98a1-3a0a1ebd4359)

![Online view](https://github.com/Expensify/App/assets/16232057/9fc27cda-a7b8-4849-a02d-d390527ccce8)

CC: @mountiny @anmurali

**Comment by mountiny** [comment]
No updates for now, focusing on more urgent tasks

**Comment by mountiny** [comment]
Still focusing on getting the frontend PRs out

**Comment by mountiny** [comment]
Will look into this tomorrow or on wdnesday

**Comment by mountiny** [comment]
I did not see this happening yet in the real flow @trjExpensify @dukenv0307 have you?

**Comment by mountiny** [comment]
bump on the above, in my testing the order seemed correct

**Comment by trjExpensify** [comment]
Order is fine for me as well. I thought this issue was for when/if we move the videos into each task. Looks like we're not going to do that anymore, so I think we're good here. :)
