### ISSUE TITLE
[Awaiting payment]Workspace members - Missing Make admin and Make member button in the dropdown menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40411]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Profile > Workspaces > any workspace.
3. Go to Members tab.
4. Add a few members and promote some to admin.
5. Check non-admin member > Click dropdown menu.
6. Check admin member > Click dropdown menu.

## Expected Result:
In Step 5, Make admin option will be present in the dropdown menu (production behavior).
In Step 6, Make member option will be present in the dropdown menu (production behavior).

## Actual Result:
In Step 5 and 6, only Remove member option is present in the dropdown menu.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/dc5f4e36-bc86-4d8b-b634-86fa07e84361

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@muttmuure I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by MonilBhavsar** [comment]
Looking...

**Comment by MonilBhavsar** [comment]
I think I found the issue, almost there, so working on a fix. Seems to be coming from https://github.com/Expensify/App/pull/39489

**Comment by MonilBhavsar** [comment]
Thanks! I have a draft PR up that fixes this issue https://github.com/Expensify/App/pull/40428/files
I'm checking the file if it caused any other issues and ensuring the workflow is working fine
Feel free to checkout/review

**Comment by MonilBhavsar** [comment]
@ZhenjaHorbach as you can see in my draft PR, I am using an additional find function to get email from the selected user's accountID. Can you think of more optimistic solution?

**Comment by MonilBhavsar** [comment]
Assigning @allroundexperts for reviewing and testing the PR

**Comment by muttmuure** [comment]
Not overdue

**Comment by MonilBhavsar** [comment]
PR was deployed to production https://github.com/Expensify/App/pull/40428
@muttmuure, we can pay @allroundexperts for reviewing PR and close this

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
