### ISSUE TITLE
Task – Long string appears instead of assignee in system message when assigning task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40413]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4494366
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Navigate to any chat
4. Create a task without assignee
5. Open task report and assign task to me

## Expected Result:
System message appears with user name, when assign task without assignee to me

## Actual Result:
System message appears - Assigned to <mention-user accountID=16027147></mention-user>, but not a user name, when assign task without assignee to me

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/76dd7d34-33f5-4d52-9f88-78877912d2f7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@greg-schroeder I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by nkuoch** [comment]
cc @jasperhuangg or @rlinoz you might know?

**Comment by rlinoz** [comment]
I'm checking, but maybe this is also related to the `expensi-common` update @robertKozik ?

cc: @puneetlath

**Comment by robertKozik** [comment]
@rlinoz  ExpensiMark is still unaware of application data (accountIDs as well) so I think it won't replace the name in such a way. 
Can we check `EditTaskAssignee` command? It returns html with a mention:
``` json
            "key": "reportActions_4663769334777431",
            "onyxMethod": "merge",
            "value": {
                "8945435353820593844": {
                    "actionName": "TASKEDITED",
                    "actorAccountID": 14342127,
                    "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/75097e10b068c4e37ad6e6134c6305bb1f828938_128.jpeg",
                    "created": "2024-04-18 13:58:25.830",
                    "lastModified": "2024-04-18 13:58:25.830",
                    "message": [
                        {
                            "html": "assigned to <mention-user accountID=14342127><\/mention-user>",
                            "text": "assigned to @Robert ROBERT robert Kozik KOZIK kozik",
                            "type": "COMMENT"
                        }
                    ],
                    "originalMessage": {
                        "assignee": "",
                        "html": "assigned to <mention-user accountID=14342127><\/mention-user>",
                        "lastModified": "2024-04-18 13:58:25.830"
                    },
                    "person": [
                        {
                            "text": "Robert ROBERT robert Kozik KOZIK kozik",
                            "type": "TEXT"
                        }
                    ],
                    "previousReportActionID": "9001584629617700205",
                    "reportActionID": "8945435353820593844",
                    "shouldShow": false
                }
            }
```

Form data doesn't have any html tag or mention inside:
<img width="328" alt="image" src="https://github.com/Expensify/App/assets/61146594/e2d6024b-2a82-4ed9-9a3f-ab3f026e8e6b">

**Comment by rlinoz** [comment]
Yeah, git bisect led me to this PR: https://github.com/Expensify/App/pull/40200

cc: @bernhardoj @abdulrahuman5196

**Comment by thienlnam** [comment]
I created a revert PR [here](https://github.com/Expensify/App/pull/40525)
