### ISSUE TITLE
Group - Offline added avatar is not showing with reduced opacity

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40427]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Crate a group chat
2. Navigate to the group chat
3. Apply offline mode
4. Click on chat header > click on upload avatar icon
5. Upload avatar

## Expected Result:
Avatar should be grayed out

## Actual Result:
Avatar is not grayed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fc9b6a94-d510-442f-8415-eff2b9060d05

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@abekkala I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by flodnv** [comment]
This is from https://github.com/Expensify/App/pull/39757 @marcaaron 🙃

**Comment by marcaaron** [comment]
Definitely not a Deploy Blocker.

>Avatar should be grayed out

@shawnborton What do you think about this?

We could use a greyscale filter on the image. There's a library here that can do it: https://github.com/iyegoroff/react-native-color-matrix-image-filters

**Comment by marcaaron** [comment]
@nexarvo I think it would have a default avatar, but not match the user uploaded avatar or default avatars for Group Chats. Or what else would it look like?

**Comment by shawnborton** [comment]
Ah, for offline pending patterns, we don't use grayscale filters - we just reduce opacity to something like 50%. Gut check from @trjExpensify & @Expensify/design please!

**Comment by trjExpensify** [comment]
Yeah, 50% opacity for pending create. The account profile avatar should have a good example to follow.

**Comment by marcaaron** [comment]
Ok cool, thanks for the memory refresh @trjExpensify 🙇  

@nexarvo There's a small detail though that this already has an open issue [here](https://github.com/Expensify/App/issues/39983). And @s77rt is assigned. @s77rt have you made progress on that or would you like to work with @nexarvo on this one as the C+?

If so, I will close this and mark that other issue as `External` and keep you both assigned.

**Comment by dannymcclain** [comment]
Also quick note: I don't think the button should be 50% opacity, just the image, right? The button isn't disabled, so it should still be full opacity.

![CleanShot 2024-04-18 at 15 45 12@2x](https://github.com/Expensify/App/assets/7516624/76a6a07f-e6b8-41cc-a81b-f024212a88ef)

**Comment by s77rt** [comment]
@marcaaron Working with @nexarvo sounds great!

@nexarvo Please comment on the other issue so you can be assigned. For the PR let's add the errors logic too, it's pretty straightforward, add `errorFields.avatar`

**Comment by shawnborton** [comment]
I think fading the icon is a bug and we should fix that so that only the picture is faded out and not the pencil icon. Can we fix that everywhere?

**Comment by dannymcclain** [comment]
>I think fading the icon is a bug and we should fix that so that only the picture is faded out and not the pencil icon. Can we fix that everywhere?

Agree. If we can fix that everywhere that'd be awesome.

**Comment by marcaaron** [comment]
Closing in favor of https://github.com/Expensify/App/issues/39983
