### ISSUE TITLE
[HOLD for payment 2024-05-08] VIP-Split - Resource Update Request: Groups

### ISSUE THREAD

**Issue by laurenreidexpensify** [Expensify/App#40423]
Publish Date - May 1

[DRAFT](https://docs.google.com/document/d/1mgfoc789TCVcWQR7JzEY8EGBCrN6_vAjmW-XmK3lG6k/edit#heading=h.u97jpdsaibmx)

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by ren-jones** [comment]
Ready to assign to me!

**Comment by ren-jones** [comment]
Contributor details
Your Expensify account email: ren@rennovateit.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01798d670f81f66952

**Comment by laurenreidexpensify** [comment]
Thanks Ren - will review your draft updates in the next few hours

**Comment by ren-jones** [comment]
All chat articles are added/updated

**Comment by laurenreidexpensify** [comment]
Rad thanks Ren - just waiting for this to be merged and deployed 👍

**Comment by laurenreidexpensify** [comment]
This ended up moving to https://docs.google.com/document/d/16_4LS7Gye10Qxab0nYtEL7qmqD6MdDIZewROSOzlvEg/edit#heading=h.fxfq71w1ipe3

**Comment by laurenreidexpensify** [comment]
These are all on staging

**Comment by laurenreidexpensify** [comment]
This is deployed - closing out as we manage Ren's payments separately to the BZ flow
