### ISSUE TITLE
Search - Searched results on the list are not filtered correctly

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40424]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/37909
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open Search Page
2. Type something in the search input ( any user name and surname)
3. Check the search results

## Expected Result:
Results on the list should be filtered to match the searched phase

## Actual Result:
Searched results on the list are not filtered correctly
Announce room appear when search for the user name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d24eb127-a9fc-472d-8952-ca1d97e7845e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/ea023a10-7f91-4afb-a1f1-f6f4a92b6f77

**Comment by MariaHCD** [comment]
I'm not sure this is a frontend issue. I wonder if it's something in the backend logic for report search that is resulting in the #announce room showing in the search results.

cc: @marcaaron @youssef-lr if you have any ideas here?

**Comment by thienlnam** [comment]
Seems to be expected from this discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1713546999765829

We're guessing that there is either a chat or a member in that announce room. However, the odd thing is that this is not on production so we're unsure if this was an intended change or not

**Comment by MariaHCD** [comment]
@izarutskaya Would you be able to confirm if the user email you searched for is part of the #announce room that displays in the search results?

**Comment by bfitzexpensify** [comment]
[Asked in #qa](https://expensify.slack.com/archives/C9YU7BX5M/p1713883335768919) for an answer to https://github.com/Expensify/App/issues/40424#issuecomment-2069648304

**Comment by MariaHCD** [comment]
Not overdue, we just need to retest again if this behavior occurs when the user is not part of the #announce room

**Comment by bfitzexpensify** [comment]
Bumped the thread in Slack for Irina to confirm.

**Comment by izarutskaya** [comment]
@MariaHCD No, I cannot reproduce this issue if the user is not part of the #announce room


https://github.com/Expensify/App/assets/115492554/7120c287-fb72-45ad-8159-0863c579c1f9

**Comment by MariaHCD** [comment]
Thanks for confirming! Then I think this isn't a bug and we should be good to close this one out.
