### ISSUE TITLE
[$250] Group - ‘Make member’ option is displayed when selecting a member

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40422]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Click on ‘FAB’ > Start chat
2. Select multiple users > Click on ‘Next’ button > Click on ‘Start group’ button
3. Click on chat header > Members > select one of the members > click selected dropdown menu

## Expected Result:
There shouldn’t be ‘Make member’ option on the list

## Actual Result:
There is ‘Make member’ option on the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7753b171-872f-4424-9030-d3b9f0aa9fe2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136b9de7bfa3b057f</li>
        <li>Upwork Job ID: 1780995867481071616</li>
        <li>Last Price Increase: 2024-04-25</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group - ‘Make member’ option is displayed when selecting a member
### What is the root cause of that problem?
We are adding make member option here
https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/ReportParticipantsPage.tsx#L240-L245
### What changes do you think we should make in order to solve the problem?

We can remove this from here
https://github.com/Expensify/App/blob/3ec8f2f9473ee1ccee7b8fc74b60cf608ee590f5/src/pages/ReportParticipantsPage.tsx#L240-L245
### What alternative solutions did you explore? (Optional)

**Comment by rlinoz** [comment]
Nothing weird happens if we click on make member, so I agree this is not a blocker, thanks @adelekennedy !

**Comment by adelekennedy** [comment]
anotha one for you @rlinoz I think this can be worked on externally - do you need to investigate this first before I do that, or can I move forward with adding the `external` label

**Comment by rlinoz** [comment]
Yep, we can make it external

**Comment by rlinoz** [comment]
Just to be clear, from the design doc:
```
The bulk actions popover menu reveals options to:
- `Remove members`
- `Make admin` when at least one member is selected
- `Make member` when at least one admin is selected

```

**Comment by rlinoz** [comment]
@thesahindia what do you think about @ShridharGoel's proposal?

https://github.com/Expensify/App/issues/40422#issuecomment-2063666634

**Comment by rlinoz** [comment]
Friendly bump @thesahindia

**Comment by rlinoz** [comment]
Hey @ShridharGoel can you give us an ETA on the PR?

**Comment by adelekennedy** [comment]
Payment due in 3 days

**Comment by adelekennedy** [comment]
@ShridharGoel and @shubham1206agra it looks like the offers in [Upwork](https://www.upwork.com/jobs/~0136b9de7bfa3b057f) are still pending but I believe payment is due (the automation failed) will you accept and then I can pay you out?

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @ShridharGoel Upwork
- [ ] Contributor+: $250 @shubham1206agra Upwork

Upwork job is [here](https://www.upwork.com/jobs/~0136b9de7bfa3b057f).
