### ISSUE TITLE
[$250]  iOS - Profile - Missing circle at the center of avatar preview when uploading new avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40441]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to Account settings
3. Tap on the profile avatar
4. Tap Upload photo
5. Select a photo or snap a photo

## Expected Result:
There will be circle at the center of the avatar preview with the area outside the circle grayed out

## Actual Result:
There is no circle at the center of the avatar preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6453329_1713427380139!IMG_BE2EE3053E6D-1](https://github.com/Expensify/App/assets/78819774/a83356c1-a914-45d7-8c5e-a67fda8b2ba9)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df76874f57e852a3</li>
        <li>Upwork Job ID: 1781336721828134912</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Beamanator** [comment]
I can reproduce this on the last staging version, on iOS native! I would say probably a blocker, though this is just a profile upload flow which isn't mission critical

**Comment by twisterdotcom** [comment]
Depends how close we are to deploying. This is something we want fixed before we send the next newsletter for sure, but we don't have to hold a deploy on it right?

**Comment by twisterdotcom** [comment]
What's the regression here anyway? Where did we lose this? Seems very specific.

**Comment by Beamanator** [comment]
> This is something we want fixed before we send the next newsletter for sure, but we don't have to hold a deploy on it right?

Totally fair - we're currently NOT close to deploying at all haha. And ya very specific! I'm looking through the PRs on staging to see if anything looks sus

**Comment by Beamanator** [comment]
Can't find any obvious PRs... This file seems to be what we're missing in iOS: https://github.com/Expensify/App/blob/main/assets/images/image-crop-circle-mask.svg

**Comment by Beamanator** [comment]
The square around the image when uploading for workspaces works on iOS Native 🤔

**Comment by Beamanator** [comment]
Hmm in dev this is potentially fixed 😅

**Comment by twisterdotcom** [comment]
https://github.com/Expensify/App/assets/9133401/c35fc79b-2d7c-4643-91df-c7be70b0ef7d

iPhone 15 staging is broken

**Comment by twisterdotcom** [comment]
Okay, but shall we agree it's not a blocker for now? You can still save it. So I think External and Daily is fine.

**Comment by Beamanator** [comment]
Makes sense to me @twisterdotcom 👍

**Comment by Beamanator** [comment]
still open for proposals

**Comment by rojiphil** [comment]
Solution 1 in @Krishna2323 [proposal](https://github.com/Expensify/App/issues/40441#issuecomment-2069186456) LGTM
🎀👀🎀 C+ reviewed

**Comment by Beamanator** [comment]
Thanks for the proposals @Krishna2323 ! So far i like your ideas, but I see in the video there might be some kind of flash when the crop view opens, is it easy to get rid of that?

**Comment by rojiphil** [comment]
This was deployed to production on May 9th as mentioned [here](https://github.com/Expensify/App/pull/40972#issuecomment-2101802636). 
Now this is due payment.

**Comment by Beamanator** [comment]
Agreed! Automation must have broke down somewhere, oops - @twisterdotcom this is ready for payout!

**Comment by twisterdotcom** [comment]
Payment Summary:

- @Krishna2323 paid $250 [here](https://www.upwork.com/nx/wm/workroom/37055899/overview) (Contributor)
- @rojiphil paid $250 [here](https://www.upwork.com/nx/wm/workroom/37100359/overview) (C+)
