### ISSUE TITLE
[$250] Submit Expense - Error message about corrupted file when dragging and dropping image receipt

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36314
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch staging.new.expensify.com
2. Tap on the fab button and Submit Expense
3. Tap on Scan tab
4. From the Finder drag and drop and type image receipt to the scan tab

## Expected Result:
The receipt can be added by dragging and dropping on the app/web app to add a scan

## Actual Result:
An error message is shown when dragging an image receipt to the app. The same file can be added using the Choose File CTA. PDF receipts work fine on both flows

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e7d2b7d5-7455-4b46-ba1c-540de3fe58fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186f6d797362b5fa7</li>
        <li>Upwork Job ID: 1780956919483195392</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Cped to staging
