### ISSUE TITLE
[HOLD for payment 2024-04-29] "Share Somewhere" Option Disabled Despite Task Assignment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40452]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1,FAB > Start Chat > Add more than two members.
2,Click on the plus sign > Assign Task > Add title > Add assignee > Confirm task.
3, Click on the header > Click "Leave".
5,Return to FAB > Quick Action > Add title.
6, Notice that the "Share Somewhere" option is disabled, but the confirm button is active. Clicking on it makes it disappear.

## Expected Result:
When leaving the thread, the assigned task should disappear from Quick Tasks, or the "Share Somewhere" option should remain enabled.

## Actual Result:
When creating a group and assigning a task, then leaving the group and accessing the assigned task through Quick Tasks, the "Share Somewhere" option is disabled.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/cd1a4945-4110-4e40-b3a7-38dd4c2e5552

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d2979b31f75f5ae</li>
        <li>Upwork Job ID: 1785138266843213824</li>
        <li>Last Price Increase: 2024-04-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by izarutskaya** [comment]
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by luacmartins** [comment]
I like the alternate solution better. @suneox are you available to work on a PR?

**Comment by luacmartins** [comment]
I can reproduce this in staging, but not in dev anymore. The flow just automatically shares the task, but then I see a not found page.

**Comment by luacmartins** [comment]
PR up. We should still compensate @suneox since the solution I used was pretty close to theirs.

**Comment by luacmartins** [comment]
What flows would lead to a missing report? Just trying to understand how much of an edge case this is

**Comment by luacmartins** [comment]
Ah I think that should be ok then. I don't think we wanna introduce code to handle outdated data.

**Comment by thienlnam** [comment]
This has been CPed to staging

**Comment by kadiealexander** [comment]
@suneox please let me know when you've accepted the Upwork contract, thanks!
