### ISSUE TITLE
[$250] Workspace - mweb - Invited members disappears from workspace members list

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:

1. Create a workspace
2. Create a public room
3. Invite a new member (without an Expensify account)
4. Observe the member appearing momentarily and then disappearing
5. Refresh the page and observe the newly invited member on the member list

## Expected Result:
Members list should show invited workspace members

## Actual Result:
Invited members disappears from workspace members list

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/45d3975b-eaa0-4a79-9dc6-ee14ef534c0f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae90bdc30dbfece7</li>
        <li>Upwork Job ID: 1781241687789658112</li>
        <li>Last Price Increase: 2024-09-06</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@CortneyOfstad FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by youssef-lr** [comment]
Investigating

**Comment by mountiny** [comment]
Making this external to get proposals in

**Comment by youssef-lr** [comment]
@ZhenjaHorbach have you managed to reproduce this? I can't seem to be able to on mWeb iOS nor web, will test in an hour in Android

**Comment by youssef-lr** [comment]
Same, I reproduced this only once but never again

**Comment by thienlnam** [comment]
Going to demote since we're having trouble reproducing this

**Comment by bfitzexpensify** [comment]
Just noting here - this has been an issue for a while, and was first reported in https://github.com/Expensify/App/issues/36378. 

There are details in https://github.com/Expensify/App/issues/36378#issuecomment-1965357368 as to the cause. I'll close https://github.com/Expensify/App/issues/36378 in favour of this since this has been assigned internally.

**Comment by brunovjk** [comment]
https://github.com/Expensify/App/issues/40301

**Comment by mallenexpensify** [comment]
@mollfpr reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by CortneyOfstad** [comment]
Thanks @mallenexpensify 👍 

Any questions, just let me know @mollfpr!

**Comment by brunovjk** [comment]
I can no longer reproduce on the latest main 🙂 **v1.4.65-5 (04/25)**
Can we check please? Thanks.

https://github.com/Expensify/App/issues/40301#issuecomment-2075543273: _"I think this should have been fixed in https://github.com/Expensify/Web-Expensify/pull/41771"_

**Comment by brunovjk** [comment]
I can no longer reproduce.

_"I think this should have been fixed in https://github.com/Expensify/Web-Expensify/pull/41771"_

**Comment by mollfpr** [comment]
Sorry for the delay 🙏

I also can't reproduce the issue. I think we can ask QA to test again and close this.

**Comment by CortneyOfstad** [comment]
Sounds good @mollfpr!

**Comment by CortneyOfstad** [comment]
Not overdue — waiting for this to be tested 👍

**Comment by brunovjk** [comment]
@CortneyOfstad I can still reproduce by following these steps #36378

**Comment by CortneyOfstad** [comment]
Okay, thanks @brunovjk! Will continue to wait for proposals 👍

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment]
@mvtglobally — can you confirm you're following the steps outlined [here](https://github.com/Expensify/App/issues/36378)?

**Comment by CortneyOfstad** [comment]
Bump @mvtglobally on the comment above ^^^ 

Thanks!

**Comment by CortneyOfstad** [comment]
@brunovjk are you still able to recreate this? I am not able to recreate this, and neither is @mvtglobally.

**Comment by brunovjk** [comment]
@CortneyOfstad Unfortunately yes. For `unknown user` on `public rooms` only:
<details>
<summary>Version: v1.4.73-1; Date: 05/13;</summary>



https://github.com/Expensify/App/assets/95647348/b90cf35e-ca12-438a-a51e-f7de1476957c

</details>

**Comment by youssef-lr** [comment]
Hmm seems like we only applied the fix to workspace members page? The recording above seems to be happening in rooms. We can probably apply the same fix here.

**Comment by CortneyOfstad** [comment]
Not overdue, still waiting on proposals

**Comment by CortneyOfstad** [comment]
Posted in Open Source to get some eyes on this ([link](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1716386831931949))

**Comment by b4s36t4** [comment]
I think this issue is related to BE, after `inviting` the user to room BE is not sending the `personalDetailsList` Onyx value where it does sending for `workspace`.

<img width="789" alt="Screenshot 2024-05-22 at 8 31 47 PM" src="https://github.com/Expensify/App/assets/59088937/f3a39e37-b276-4117-8ad4-577466425d8b">

**Comment by CortneyOfstad** [comment]
@youssef-lr bump on the question [here](https://github.com/Expensify/App/issues/40459#issuecomment-2135456868). Thanks!

**Comment by youssef-lr** [comment]
Will take a look, I'm guessing that yes this is probably BE related.

**Comment by CortneyOfstad** [comment]
Thanks @youssef-lr — any update?

**Comment by CortneyOfstad** [comment]
@youssef-lr bump ^^^ thanks!

**Comment by youssef-lr** [comment]
Haven't had the chance to get to this, on it tomorrow!

**Comment by youssef-lr** [comment]
No update yet

**Comment by CortneyOfstad** [comment]
@youssef-lr any updates? Thanks!

**Comment by youssef-lr** [comment]
I will get to this today @CortneyOfstad

**Comment by youssef-lr** [comment]
can we test again? I can't reproduce locally and we do seem to return personal details from the backend

<img width="703" alt="Screenshot 2024-06-27 at 17 59 43" src="https://github.com/Expensify/App/assets/9680864/dbdd6ed3-02ed-4278-ab42-db8c262e84f2">

**Comment by CortneyOfstad** [comment]
I was not able to reproduce either! Will put `reproduce weekly` to see if QA can retest as well and if not, we will close it 👍

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests. 

https://github.com/Expensify/App/assets/43995119/fbcc52dc-f705-4ea4-9e80-4fd717cf954d

**Comment by CortneyOfstad** [comment]
Sorry, was OoO. Since this has been recreated, going to keep this open for proposals!

However, since VIP-VSB is paused, going to adjust the frequency

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment]
I can't reproduce it too. @CortneyOfstad I think we can close this.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by youssef-lr** [comment]
Closing as this is not reproducible anymore.
