### ISSUE TITLE
[$250] Workspace switcher - Selected filter is not highlighted

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Open workspace switcher.
## Expected Result:
The selected filter will be highlighted (production behavior).

## Actual Result:
The selected filter is not highlighted.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/20556936-c426-48dc-8d86-a6e0edf994aa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cffadd881b76c8f7</li>
        <li>Upwork Job ID: 1781065373142794240</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by marcochavezf** [comment]
Looks like the bug was introduced in this [PR](https://github.com/Expensify/App/pull/40179)

**Comment by marcochavezf** [comment]
I can't create a straight revert from the offending PR, but yeah seems something's up with the new `SelectionList` component and the `isSelected` cc @lukemorawski @rushatgabhane @cristipaval

**Comment by marcochavezf** [comment]
Making it external in case someone can spot the error

**Comment by marcochavezf** [comment]
Thanks for the proposals. @gijoe0295's solution looks good, I also agree that looks better without the loading effect. I think `didScreenTransitionEnd` was copied from another page component but is not required for the workspace switcher. 

I'm going to create a quick PR to fix this deploy blocker since I already made the changes while I was testing the proposals, but I'm going to assign you for the compensation

**Comment by thienlnam** [comment]
This has been CPed to staging

**Comment by MitchExpensify** [comment]
**Payment summary:**

$250 C+ @DylanDylann 
$250 C @gijoe0295

**Comment by MitchExpensify** [comment]
Paid and contract ended
