### ISSUE TITLE
Android - Onboarding - Tapping the Onboarding link does not open the Onboarding menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40456]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - internal Team

## Action Performed:
1. Open New Expensify app
2. Navigate to any conversation
3. Send the link to the conversation to https://staging.new.expensify.com/onboarding
4. Click on the link

## Expected Result:
Tapping on the Onboarding link should open the Onboarding menu.

## Actual Result:
Tapping the Onboarding link does not open the Onboarding menu, buttons in Compose Box stop working, to get the Onboarding menu, you have to tap on the user profile link and go back.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/681c2b2f-ff1c-443e-9a2b-7ed0b38b0b05

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
Asked [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713513686706839)

**Comment by mountiny** [comment]
We should not be allowing people to go through the flow multiple times so this should be fine
