### ISSUE TITLE
[HOLD for payment 2024-05-02] [$250] Group chat - No tooltip when hovering over group member name in the chat header

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40457]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/40134
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Create a group chat.
4. Hover over group member name in the header.

## Expected Result:
Tooltip will display.

## Actual Result:
No tooltip when hovering over group member name in the group chat header.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3f1b3bee-f4a8-4cd1-a45c-c8e8185f0b61

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4e26e9f3b200297</li>
        <li>Upwork Job ID: 1781107500795551744</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 0</li>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@zanyrenney I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No tooltip when hovering over group member name in the chat header
### What is the root cause of that problem?
It's because of the shouldUseFullTitle
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/pages/home/HeaderView.tsx#L267
### What changes do you think we should make in order to solve the problem?

We should remove the `||isGroupChat` from here
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/pages/home/HeaderView.tsx#L267
### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment]
Thanks, yep adding external

**Comment by zanyrenney** [comment]
and adding to wave collect.

**Comment by zanyrenney** [comment]
@trjExpensify what release? I think May 1.

**Comment by trjExpensify** [comment]
> @trjExpensify what release? I think May 1.

@zanyrenney Group Chats is #vip-split.

**Comment by marcaaron** [comment]
Removing the blocker.

**Comment by marcaaron** [comment]
@bondydaa let me know if you want me to take this off your hands as it's related to Group Chats.

**Comment by Nodebrute** [comment]
[**PROPSAL UPDATED**](https://github.com/Expensify/App/issues/40457#issuecomment-2064047201)

**Comment by Nodebrute** [comment]
[**PROPOSAL UPDATED**](https://github.com/Expensify/App/issues/40457#issuecomment-2064047201)

**Comment by marcaaron** [comment]
@Nodebrute solution LGTM let's go with that.

**Comment by marcaaron** [comment]
The bots got confused here

**C+:** @s77rt 
**Contributor:** @Nodebrute

**Comment by marcaaron** [comment]
Sorry, assigned you [to this one](https://github.com/Expensify/App/issues/40512). Let's get it!

**Comment by marcaaron** [comment]
If you feel like you have a valid claim then email `contributors@expensify.com`. Based on the complexity of the issue I selected the first proposal. We also have this in the guidelines:

![2024-04-18_14-01-06](https://github.com/Expensify/App/assets/32969087/5d137c1f-a432-419d-b168-7c1095fd0a73)

**Comment by Nodebrute** [comment]
@marcaaron  Hey, I've thoroughly tested my proposal multiple times to ensure it covers all cases. My proposal is distinct, and I've outlined the reasons why.My solution is functional. Please take another look at the decision.

**Comment by Nodebrute** [comment]
Hey, I've thoroughly tested my proposal multiple times to ensure it covers all cases. My proposal is distinct, and I've outlined the reasons why? Thank you for accepting the proposal. The PR will be ready soon.

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/39757
- The offending PR has been commented on: Not needed. Both author and reviewer are assigned here
- A discussion in #expensify-bugs has been started: Not needed, unique bug
- Determine if we should create a regression test for this bug: No

**Comment by zanyrenney** [comment]
**Payment Summary**

@s77rt paid $250 via ND.
@Nodebrute requires payment [automatic offer] paid $250 via ND.

**Comment by s77rt** [comment]
Payment due here is $125 for a regression. I have refunded 50%
