### ISSUE TITLE
[PAID] [$250] Group chat - Members RHP shows offline indicator

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to FAB > Start chat.
4. Create a group chat.
5. Click on the chat header in the group chat.
6. Click Members.

## Expected Result:
Members RHP will not show offline indicator (production behavior).

## Actual Result:
Members RHP shows offline indicator.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/16b890f4-6213-4b2d-85c2-71862e429365

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016859f51dea712595</li>
        <li>Upwork Job ID: 1780980589354110976</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group chat - Members RHP shows offline indicator
### What is the root cause of that problem?
It's because of this 
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/pages/ReportParticipantsPage.tsx#L312
### What changes do you think we should make in order to solve the problem?

We should remove this 
https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/pages/ReportParticipantsPage.tsx#L312
### What alternative solutions did you explore? (Optional)

**Comment by neil-marcellini** [comment]
@Nodebrute thanks for the proposal. Can you provide some more insight into why that prop was set and if any other pages or areas of the app need to display the offline indicator on the members page?

I imagine that some pages display the members in the main pain vs the RHP, so those pages need to show the offline indicator.

After looking more carefully, I see that the ReportParticipantsPage is only displayed in the RHP, so it should be fine for this to  never show the offline indicator in wide screen.

Proposal looks good, assigning @Nodebrute

**Comment by neil-marcellini** [comment]
@Nodebrute please let me know when you can have the PR ready

**Comment by Nodebrute** [comment]
@neil-marcellini Thank you. I am working on it.

**Comment by marcaaron** [comment]
Removing the blocker for this one for now. I don't think it's urgent enough to block the next release.

**Comment by Nodebrute** [comment]
@neil-marcellini The PR was deployed to production on the 24th. Could you please release the payment for this issue?

**Comment by Nodebrute** [comment]
@neil-marcellini gentle bump

**Comment by Nodebrute** [comment]
@neil-marcellini @marcaaron gentle reminder regarding payment.

**Comment by Nodebrute** [comment]
@strepanier03 gentle bump

**Comment by strepanier03** [comment]
Payment is completed on Upwork and contract closed. 

Sorry for missing this, the failed automation meant it fell through the cracks.
