### ISSUE TITLE
[HOLD for payment 2024-05-03] [$250] [Report fields] Hmm its not here page displayed when clicking on expense title

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40464]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+gm174@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. As Admin open Workspace chat with expense
2. Go to expense detail page
3. Click on Title

## Expected Result:
Title edit page should open

## Actual Result:
Hmm its not here error page displayed when clicking on expense title and nothing happens when click on Go back to home page button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fb20e58d-76c0-4492-8ec5-0f41b2394bc2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01522b79f04da5c437</li>
        <li>Upwork Job ID: 1780977183106654208</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by trjExpensify** [comment]
Hm, report fields aren't supported on `collect`, so this seems more so related to #wave-control. CC: @thienlnam @youssef-lr @JmillsExpensify

**Comment by thienlnam** [comment]
Yup that's correct - just the title is stored under text_title, all the other report field keys are stored under expensify_field_id.

**Comment by ahmedGaber93** [comment]
Reviewing now.

**Comment by ahmedGaber93** [comment]
Thanks @GandalfGwaihir for the proposal.
Your RCA and fix is correct 👍. Just small change, move the condition inside `getReportFieldKey` to apply this fix globally in the app.

```javascript
function getReportFieldKey(reportFieldId: string) {
  if (reportFieldId === CONST.REPORT_FIELD_TITLE_FIELD_ID){
      return CONST.REPORT_FIELD_TITLE_FIELD_ID;
  }

  return `expensify_${reportFieldId}`;
}
```

@GandalfGwaihir's [proposal](https://github.com/Expensify/App/issues/40464#issuecomment-2064441681) LGTM.
🎀 👀 🎀 C+ reviewed.

**Comment by ahmedGaber93** [comment]
> but yeah i will check where else getReportFieldKey is being used

Yes, please do that, I just notice `fieldKey` it used in [clearReportFieldErrors](https://github.com/Expensify/App/blob/9a115b64a4fc7d167d87ece406044aaa0cb4ab87/src/libs/actions/Report.ts#L1634), so I assume it should fix globally in the app.

Also, I think the [condition](https://github.com/Expensify/App/issues/40464#issuecomment-2066458867) is safe as the fieldID `'text_title'` is a unique fieldID, and other fields has different format `field_id_FIELDNAME` so if we create custom field with name `title` the fieldID will be `"fieldID": "field_id_TITLE"`

**Comment by thienlnam** [comment]
Yeah, agree with fixing this globally so we don't have some places trying to call expensify_text_title as opposed to text_title. It's a unique report field

**Comment by ahmedGaber93** [comment]
- [x] [@ahmedGaber93] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/36553
- [x] [@ahmedGaber93] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/36553/files#r1592310890
- [x] [@ahmedGaber93] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@ahmedGaber93] Determine if we should create a regression test for this bug.
- [x] [@ahmedGaber93] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

#### Regression Test Proposal:
Preconditions: your account have beta 'reportFields'
1. Open paid workspace with 'admin' role
2. Click icon (+) > Submit expense > fill fields, then submit the expense
3. Go to the expense detail page
4. Click on Title
5. Verify that edit title page is opened correctly, and no NotFoundPage displayed.

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @ahmedGaber93 for the C+ review (waiting for you to accept [the offer](https://www.upwork.com/offer/101943120))
- $250 to @GandalfGwaihir for the fix (paid)

As for the regression test, @thienlnam @caitlinwhite1 will you guys be adding a suite of these test cases for report field flows centrally as part of the project? Seems like this one here will end up doubling up.

**Comment by thienlnam** [comment]
Good question, I don't think we've created a set of standard regression tests for this project yet. 

There's probably a few piece meal QA tests added for this, but would be a good idea to get some proper ones set up in testrail. @caitlinwhite1 Would you be able to get this set up? Happy to help if needed

**Comment by caitlinwhite1** [comment]
@thienlnam Yes! On it today. Thanks Jack

**Comment by trjExpensify** [comment]
Awesome, thanks! @ahmedGaber93 still waiting for you to accept the offer to pay this one out.

**Comment by ahmedGaber93** [comment]
@trjExpensify Offer accepted.

**Comment by trjExpensify** [comment]
Thanks. Paid, closing!
