### ISSUE TITLE
[$250] Group chat - Implement offline behavior for `UpdateGroupChatMemberRole`

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40465]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces > any workspace.
3. Go to Members.
4. Add members if not yet.
5. Go offline.
6. Click on the member > Change the role.
7. Note that the member row is grayed out.
8. Go to FAB > Start chat > Create a group chat.
9. Click on the header > Members.
10. Go offline.
11. Click on the member > Change the role.

## Expected Result:
The member row will be grayed out.

## Actual Result:
The member row is not grayed out.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e41d5db3-7674-48be-8443-c5b63a008012

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d46118164c08a83</li>
        <li>Upwork Job ID: 1781053379706904576</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by amyevans** [comment]
This is a minor issue so no need to block deploy.

I do think it's worth making consistent with the offline behavior of updating member roles on a workspace though. Do you want to work on polish items @marcaaron or should I make it external?

**Comment by marcaaron** [comment]
Yeah I agree. I can take this off your hands as well if you want since it's related to the Group Chats project.

**Comment by amyevans** [comment]
Wfm, thanks!

**Comment by marcaaron** [comment]
That looks good to me. Ideally, we can also try to handle any potential errors related to this request failing while offline as well. Either in this ticket or a follow up. Are you interested in working with us on that as well @nexarvo ?

**Comment by marcaaron** [comment]
There's some backend change that would need to happen first so no need worry about it for now. But maybe you can try to find some ways to break the API call while testing. 😈

**Comment by s77rt** [comment]
Not overdue. We have a draft PR

**Comment by s77rt** [comment]
PR was deployed to production last week

**Comment by nexarvo** [comment]
Hi @marcaaron, the payments are pending here. Can you please take a look. Thanks

**Comment by marcaaron** [comment]
@bfitzexpensify Any chance you can help us out? Thanks!

**Comment by bfitzexpensify** [comment]
Payment summary:

@nexarvo to be paid $250 - offer sent via Upwork
@s77rt to be paid $250 via manual request

**Comment by s77rt** [comment]
@bfitzexpensify This one should be paid via Upwork (I was assigned this issue before I moved to ND)

**Comment by bfitzexpensify** [comment]
Gotcha - offer sent

**Comment by s77rt** [comment]
Accepted! Thanks!

**Comment by bfitzexpensify** [comment]
Great, all payments complete, thanks everyone.
