### ISSUE TITLE
Android - Login - When entering the magic code and signing in, a gray and black screen appears.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40462]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Dot app
2. Enter any email> Continue
3. Enter magic code> Sign in
4. Check the screen before skeleton appears

## Expected Result:
When entering the magic code and clicking the "Sign in" button, the LHN skeleton should appear.

## Actual Result:
When entering the magic code and signing in, a gray and black screen appears.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/07fbf2f3-3121-4e4f-a59d-84bdcc441ad0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
This seems minor and not really a blocker

**Comment by stephanieelliott** [comment]
I see the black screen, IMO it is barely noticeable. Seeing at it is only affecting one platform I am going to close
