### ISSUE TITLE
[$250] [HOLD for payment 2024-05-06] Group - Wrong number of members seen on group details page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40463]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB > Start chat
3. Search for 2 non-existing users and click on add to group
4. Create the group
5. Open the group details page and observe the number besides "Members" button
## Expected Result:
Correct number of members is visible, in this case 3

## Actual Result:
Incorrect number of members is seen, in this case 5

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/71395108-f30e-427e-922e-c002e17fc1f1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014cb2f3679812b245</li>
        <li>Upwork Job ID: 1790118403758641152</li>
        <li>Last Price Increase: 2024-05-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by m-natarajan** [comment]
@johncschuster FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by rlinoz** [comment]
Hmm I can
https://github.com/Expensify/App/assets/5201282/8daaa62b-654e-4795-8b3b-5e7934a7ed73


I think we are not clearing the optimistic created `accountIDs`?
<img width="354" alt="image" src="https://github.com/Expensify/App/assets/5201282/298c58d4-bb0f-427b-abbc-8327a796efb0">

**Comment by rlinoz** [comment]
Ooh I think this is part of moving away from `participantAccountIDs` to `participants`. The `participantAccountIDs` has only 3 members.

**Comment by rlinoz** [comment]
Anyway, this happens only for accounts that are created on this flow, so I don't think this should be a blocker. Removing the label.

**Comment by rlinoz** [comment]
>Should we use report?.participantAccountIDs instead then ?

No, that is being deprecated here https://github.com/Expensify/App/issues/34692.

**Comment by marcaaron** [comment]
We should be clearing the optimistic accountIDs after inviting here:

https://github.com/Expensify/Web-Expensify/blob/6fe504f9aa17f8a3945bd4e2ba1fe2b155f5011a/lib/ReportAPI.php#L5949-L5967

We could check the logs though to make sure the params are correct and nothing happened to the Auth request

**Comment by rlinoz** [comment]
Seems like we are not sending the optimistic accountID list, will finish the PR tomorrow.

**Comment by rlinoz** [comment]
@johncschuster @ahmedGaber93 reviewed the PR.

**Comment by johncschuster** [comment]
Thanks, @rlinoz!

**Comment by johncschuster** [comment]
Summary:
Contributor+: @ahmedGaber93  $250 - [Upwork Offer](https://www.upwork.com/nx/wm/offer/102292917)
