### ISSUE TITLE
mWeb - Chat - Enter multiline name for an URL by tapping enter key cursor moves to top left

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40468]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4495375
**Email or phone of affected tester (no customers):** 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Paste the link https://applause-ts.slack.com/archives/G01CL838B8T/p1713429021883169
4. Send the message
5. Long press the sent message and select edit comment
6. Try to remove url name and enter a multiline name by tapping enter key

## Expected Result:
Trying to enter multiline name for an URL by tapping enter key cursor must not move to top left first character

## Actual Result:
Trying to enter multiline name for an URL by tapping enter key cursor moves to top left first character

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/850d437d-3b7d-4c4c-9def-708e5525e420

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by muttmuure** [comment]
I don't think this bug is worth fixing right now
