### ISSUE TITLE
[$250] Chat - Mention/here is not filled from the suggestion when only one suggestion is shown

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40479]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch new Expensify
2. Navigate to any chat
3. Type @here (or part of an email that will only show one result)
4. Tap on the single result

## Expected Result:
The mention is applied from the suggestions with any amount of results

## Actual Result:
The mention is not applied from the suggestions when there's only one

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b0c3efdf-f4bc-4bf4-a282-c2d6ec3a39d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ea06003a9b4d0a5</li>
        <li>Upwork Job ID: 1781028291653857280</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

**Comment by chiragsalian** [comment]
Definitely not an hourly since it's not a blocker. Demoting to daily. Adding external label since the issue seems purely front end related.

**Comment by skmanoj322** [comment]
https://github.com/Expensify/App/assets/86718126/f5b5a1b6-554b-408e-8df9-94efdff17ca6

@m-natarajan when i press on here it applied to typing area am i missing something?

**Comment by skmanoj322** [comment]
Contributor details
Your Expensify account email: sk.manoj322@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016dddddac7ac687d5

**Comment by adelekennedy** [comment]
I can't replicate this now - on version v1.4.63-20, the video above is also not working for me - I think we can safely close this one
