### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] ExpensifyHelp resource updates for VIP-Travel

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/App#40478]
ExpensifyHelp article - 'Approving travel ' - New Expensify version

There are 8 articles in total, all in [this Google Doc](https://docs.google.com/document/d/1VeMlMPMAoIkhLEUAdVPFy43knYA8Z4Ed2fyYOYUTak8/edit) 

Article breakdown:

New Expensify

- What is Expensify Travel?
- Booking and managing travel
- Configuring travel preferences
- Approving travel 

etc

Expensify Classic
- What is Expensify Travel?
- Booking and managing travel
- Configuring travel preferences
- Approving travel 

Publish date: May 1st

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by bfitzexpensify** [comment]
Waiting for Ren's review!

**Comment by bfitzexpensify** [comment]
Still waiting on Ren

**Comment by bfitzexpensify** [comment]
OK, current state - need this to hit staging to grab screenies of the ND flow, then will update the doc, have Ren re-review, and then set this all live.

**Comment by ren-jones** [comment]
Oops—I was working on the article before I was even assigned. Ha! I'm ready to be assigned!

**Comment by bfitzexpensify** [comment]
These are all ready for review again, Ren!

**Comment by bfitzexpensify** [comment]
Waiting for the deploy today so I can get back into our demo environment and then I'll address the remaining comments.

**Comment by bfitzexpensify** [comment]
Still waiting on that deploy

**Comment by bfitzexpensify** [comment]
Merge freeze in place until at least Thursday morning.

**Comment by bfitzexpensify** [comment]
We're [deploying](https://expensify.slack.com/archives/C05S5EV2JTX/p1716418092711289?thread_ts=1716242660.491669&cid=C05S5EV2JTX) travel-related things, so hope to be able to get back in tomorrow morning and get this all wrapped up

**Comment by bfitzexpensify** [comment]
Good to go, except for one clarifier on exactly how the 'Get Support' button should look in the emailed itinerary. Checking with Spotnana, will update if needed, then we'll be ready to set these live.

**Comment by bfitzexpensify** [comment]
That button isn't working, but it should be there, so these are fine to publish as is

**Comment by bfitzexpensify** [comment]
Payment due on Thursday

**Comment by bfitzexpensify** [comment]
Actually, this can be closed.
