### ISSUE TITLE
 Submit Expense - 'No PDF file specified' shown on confirmation page after adding PDF receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40476]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/36314
## Action Performed:
1. Launch staging.new.expensify.com
2. Tap on the fab button and Submit Expense
3. Tap on Scan tab
4. Tap on image icon and Choose document
5. Add a PDF file and select any user/channel

## Expected Result:
The PDF preview is shown on the confirmation page

## Actual Result:
'No PDF file specified' shown instead of the PDF preview on confirmation page after adding PDF receipt. The receipt is then passed correctly to the expense if confirming

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2f2c19ec-7e26-4ec6-b5c7-8708d43075fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@aldo-expensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by aldo-expensify** [comment]
Merged fix and requested CP to staging
