### ISSUE TITLE
CRITICAL: [Actionable Whispers] Track scan expense is duplicated when it is submitted to someone

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40485]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/38709
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Track expense
3. Create a track scan expense
4. From the whisper, select Submit it to someone
5. Select a user to submit to
6. In 1:1 DM with the user from Step 5, click on the expense preview
7. Click on the header subtitle to return to main chat
8. Click on the same chat in LHN

## Expected Result:
he track scan expense will not be duplicated

## Actual Result:
The track scan expense is duplicated when it is submitted to someone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/0dbbb74e-fe98-4b07-98ae-9ec2a4bf7064

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a279eb4ea7ee1906</li>
        <li>Upwork Job ID: 1781106389210488832</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

**Comment by dangrous** [comment]
Notes from DM with @thienlnam 
> Inside the money request report, there should be IOU reportActions (which we've renamed to MoneyRequestPreviews).
>
> And then when you click on that, you are taken to the money request reportIn the DM, there should be a REPORTPREVIEW reportAction added or updated
>
> But basically I think what needs to happen is we need to start accepting a new parameter in the BE called report reportPreviewReportActionID, and ensure that we use that reportID for the REPORTPREVIEW reportAction

**Comment by quinthar** [comment]
What's the next step here -- is @thienlnam taking this, or @dangrous ?

**Comment by thienlnam** [comment]
I'm still taking this since @dangrous will be out this week

**Comment by thienlnam** [comment]
Done! Changes are live
