### ISSUE TITLE
Bottom button on transfer balance, Merchant and status pages are missing padding

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713434632519999

## Action Performed:
1. Go to Settings > Wallet > transfer balance
2. Click Fab + > submit expense > Merchant
3. Go to profile > status 
4. Observe the buttons at the bottom

## Expected Result:
The bottom button should have 20px of padding around it
## Actual Result:
The bottom button does not have any padding around it
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Snip - (3) New Expensify](https://github.com/Expensify/App/assets/38435837/b4740a92-19bb-4759-99b0-234457fc327e)
![CleanShot 2024-04-18 at 08 41 26@2x](https://github.com/Expensify/App/assets/38435837/20b3fe5f-ffd3-430d-a090-0d6b5d375a2b)
![CleanShot 2024-04-18 at 08 41 40@2x](https://github.com/Expensify/App/assets/38435837/c6485b41-8b12-479a-af00-b213af8893cd)
![CleanShot 2024-04-18 at 08 42 42@2x](https://github.com/Expensify/App/assets/38435837/bd9bd2b9-da13-4595-8844-cc9dfa7d8455)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
I think we already found the offending PR and it's being handled: https://github.com/Expensify/App/pull/38039

**Comment by joekaufmanexpensify** [comment]
Cool cool, we can close this then?

**Comment by shawnborton** [comment]
I think so?

**Comment by joekaufmanexpensify** [comment]
Cool cool, closing then!
