### ISSUE TITLE
[$250] mWeb - Chat - Changing skin tone send a emoji and immediately entering : moves cursor to left

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40482]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4499508
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter :+1
4. Change skin tone and tap outside
5. Select the emoji
6. Send the message
7. Enter : immediately in compose, note cursor moves to left

## Expected Result:
Changing skin tone send an emoji and immediately entering : must not move cursor to left

## Actual Result:
Changing skin tone send an emoji and immediately entering : moves cursor to left

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2b9c80ac-a96e-49f8-97b6-24c246cfcdf2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181c01cbec4129982</li>
        <li>Upwork Job ID: 1782464676482981888</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by sakluger** [comment]
That's a weird one. The bug feels pretty small and not super critical, but we can look into it.

**Comment by sakluger** [comment]
Waiting for proposals.

**Comment by sakluger** [comment]
This is a major edge case, I'm going to close for now.
