### ISSUE TITLE
Submit Expense - PDF files can not be added to scan expense on mobile apps

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40486]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36314
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch new expensify
2. Tap on the fab button and Submit Expense
3. Tap on Scan tab
4. Tap on image icon and Choose document
5. Add a PDF file

## Expected Result:
The PDF file can be added to the scan receipt and the next part of the flow appears without issues

## Actual Result:
An error message appears blocking the user from adding a PDF file for scanning

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8aeabf04-0878-4010-a05a-d96395371022

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by blimpich** [comment]
Not a blocker, since its likely already fixed by a PR that hasn't been deployed to staging yet, and is also not a huge bug.

I will retest this once https://github.com/Expensify/App/pull/40351 has been deployed to staging and confirm that it is fixed.

**Comment by blimpich** [comment]
Not overdue, still waiting for that PR to be deployed to staging and ideally production before retesting this and closing.
