### ISSUE TITLE
[HOLD for payment 2024-05-09] Stop sending <mention-report> when not in a policy room

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#40480]
When we add a comment to a report we parse it before sending to the backend with `ExpensiMark` [here](https://github.com/Expensify/App/blob/9b839f4f18d724dba1ed17ed5967f7e033781428/src/libs/ReportUtils.ts#L3183).

We added the logic to parse `#room-name` to `<mention-report>#room-name</mention-report>` [here](https://github.com/Expensify/expensify-common/pull/680), but since we only allow report mentions to happen inside policy rooms, we should prevent the parsing from happening for messages sent outside of a policy room.

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f795318d2531edc</li>
        <li>Upwork Job ID: 1787964711355367424</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by robertKozik** [comment]
Hi, can you assign me to this issue?

**Comment by robertKozik** [comment]
PR for parser is ready

**Comment by rlinoz** [comment]
@greg-schroeder @ahmedGaber93 was the PR reviewer.

**Comment by greg-schroeder** [comment]
Okay got it - set for payment on 5/9

**Comment by greg-schroeder** [comment]
Going to add `Internal` label just to create an upwork job

**Comment by greg-schroeder** [comment]
Offer sent to @ahmedGaber93 ahead of 5/9 payment date

**Comment by ahmedGaber93** [comment]
@greg-schroeder offer is accepted, Thanks!

**Comment by greg-schroeder** [comment]
paid
