### ISSUE TITLE
[HOLD for payment 2024-05-08] [$250] Task - "From" subtitle is present in group task report after user has left the group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40499]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat
3. Create a task
4. Click on the chat header > Leave
5. Go to task report
6. Click on "From" link

## Expected Result:
There should not be "From" link because the group chat is no longer accessible

## Actual Result:
There is "From" link in the task report when user has left the group chat. Clicking on "From" subtitle leads to skeleton report.
The same issue also happens for group thread after user leaves the group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0bca3ad5-3113-462a-a44d-3db91f84230b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c5bacf8c885bcc7</li>
        <li>Upwork Job ID: 1781098555062116352</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment]
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by luacmartins** [comment]
Looking

**Comment by luacmartins** [comment]
I'm gonna demote this since it doesn't break any functionality

**Comment by DylanDylann** [comment]
Can't reproduce

**Comment by luacmartins** [comment]
Put up a PR in review - https://github.com/Expensify/App/pull/40726

**Comment by miljakljajic** [comment]
@eVoloshchak are you owed payment for reviewing the PR? I'll submit a manual request for you tomorrow.

**Comment by eVoloshchak** [comment]
>  are you owed payment for reviewing the PR?

@miljakljajic, yes, for the review of https://github.com/Expensify/App/pull/40726

**Comment by miljakljajic** [comment]
@eVoloshchak is owed 250 USD for their work reviewing https://github.com/Expensify/App/pull/40726

Thank you!

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
