### ISSUE TITLE
mWeb - Thread - Thread for changed amount shows empty thread avatar& revisiting shows hmm page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1,4.63
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Tap plus icon -- submit expense
4. Enter an amount and tap next
5. Tap submit
6. Open the expense and in details page change the amount and save it
7. Open reply thread by long pressing system message displayed for changed amount
8. Note header keeps loading and empty thread avatar displayed below
9. Tap header link and again try to visit thread page

## Expected Result:
Thread page for changed amount must not show empty thread avatar and revisiting page must not show hhm not here

## Actual Result:
Thread page for changed amount shows empty thread avatar and revisiting page shows hhm not here

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/25ae5f68-d24a-4fe4-94bc-1dfadd5675df

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
Working properly on Android staging v63-5.
