### ISSUE TITLE
Chat - File types MP4, PDF, DOC etc other than images can not be attached to a report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4498814
**Email or phone of affected tester (no customers):** [gatantm@gmail.com](mailto:gatantm@gmail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch new Expensify
2. Navigate to any chat
3. Tap on the plus icon > Add attachment > Choose Document
4. Select any file other than an image (e.g, PDF, Word, Zip, MP4)

## Expected Result:
Supported file types can be attached to the chat and sent without issues

## Actual Result:
Only image file types can be sent. PDF, Word, Zip, MP4 files throw an error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3678df2e-d5db-41c2-b623-371148e21a66

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production:


https://github.com/Expensify/App/assets/78819774/d246a945-a08b-447c-bcfa-7aa16bc9ac18

**Comment by lanitochka17** [comment]
@AndrewGable  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by AndrewGable** [comment]
Not 100% but this PR looks like it could be suspect: https://github.com/Expensify/App/pull/39334

**Comment by AndrewGable** [comment]
Confirm revert fixes, going to CP the revert
