### ISSUE TITLE
Magic code not received when SAML enabled and `Required for sign in` disabled

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** No new feature (Production UI is different)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @johnmlee101 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713457220310039

## Action Performed:

1. Enter an email with SAML optionally enabled (not required on domain) on the sign in page
2. See page for entering magic code or selecting SAML

## Expected Result:
Receive a magic code email
## Actual Result:
No magic code received, user has to wait for 30 seconds to show `Didn't receive code` and 2nd request works
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1c54c844-46a0-4d8d-b6b8-ae7f9f1e5020

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This is a new feature per the OP and there is a straightforward workaround to resolve this so I am removing the deploy blocker label, but we should handle the fix with urgency

**Comment by johnmlee101** [comment]
Is this SAML flow enabled for all users? Or is it behind a beta flag?

**Comment by mountiny** [comment]
@samilabud @allroundexperts @madmax330 this is coming from your PR https://github.com/Expensify/App/pull/30849 would you be able to look into this urgently? I think that there is clear workaround so demoted, however, if you feel otherwise, please add add the deploy blocker label. 

I dont think this is behind beta, I probably misinterpreted the PR description, its not a new feature. Currently it seems like users with SAML get two magic codes at once. I think having to click on the `didnt receive code` button is better than receiving two codes and not knowing which to use

**Comment by samilabud** [comment]
> @samilabud @allroundexperts @madmax330 this is coming from your PR #30849 would you be able to look into this urgently? I think that there is clear workaround so demoted, however, if you feel otherwise, please add add the deploy blocker label.
> 
> I dont think this is behind beta, I probably misinterpreted the PR description, its not a new feature. Currently it seems like users with SAML get two magic codes at once. I think having to click on the `didnt receive code` button is better than receiving two codes and not knowing which to use

Hi @mountiny, from what I see the magic code is coming, check the time in the email (03:23pm):
<img width="642" alt="image" src="https://github.com/Expensify/App/assets/5216036/d7c2c0a4-c8cd-45e4-a55e-bedf8c8f7dc5">
And later in the minute 0:21 of the video, the email hour change to 3:24pm (the magic code is received):
<img width="328" alt="image" src="https://github.com/Expensify/App/assets/5216036/b37ed6fe-ae1e-4635-8520-fa0977dc9263">
It seems to be grouped by gmail:
<img width="487" alt="image" src="https://github.com/Expensify/App/assets/5216036/faaa0afb-f57b-4fce-9407-2b77674f7c3e">

I have also tested on the web and it is working, if there is a specific scenario when this happens please share it with me to check.

**Comment by mountiny** [comment]
@samilabud I have just tested with my expensifail email and indeed I havent received the email until I  have clicked on the `didnt receive` button 40 seconds later. Only received one email.

So I thin I could repro

**Comment by samilabud** [comment]
> @samilabud I have just tested with my expensifail email and indeed I havent received the email until I have clicked on the `didnt receive` button 40 seconds later. Only received one email.
> 
> So I thin I could repro

I see, it seems that the "bug" was fixed in the backend, context: before when you got to the "SSO or Magic Code" screen you received a code but to put that one you had to click on the "use magic code" button and it sent the other code, this doesn't happen anymore now please watch the video:

https://github.com/Expensify/App/assets/5216036/a30cd086-52e0-4243-bb7d-4bbf81496cdb


Since this is no longer happening after a backend correction, I suggest a rollback of this implementation @allroundexperts.

**Comment by pecanoro** [comment]
I am adding a deploy blocker because this is not broken on production even if the UI is slightly different. Since it's blocking signing in, it is not great, it's not a minor bug.

**Comment by mountiny** [comment]
Going to revert to the previous behaviour then https://github.com/Expensify/App/pull/40690

**Comment by pecanoro** [comment]
@mountiny After reverting, now I am getting this error even after getting rid of Onyx data, are we missing something? https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228785f326fdad2177-MAD%22)+AND+timestamp:[2024-04-22T12:27:11.309Z+TO+2024-04-22T14:27:11.309Z]&index=logs_expensify-027957

**Comment by mountiny** [comment]
It works as expected for me 
Uploading Screen Recording 2024-04-22 at 15.42.00.mov…

**Comment by pecanoro** [comment]
Hmm, yes, it only happens for one of my accounts, super weird. All good then, I will look into it later

**Comment by mountiny** [comment]
the recording was too big 

https://github.com/Expensify/App/assets/36083550/67e2b193-0e1d-40e5-8f8f-f5752e05cfff
