### ISSUE TITLE
[$250] Tagging someone in the group Chat invites the user automatically

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40503]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713375835423579

## Action Performed:
1. Open any chat report
2. Mention someone who is not in the chat members list
3. "Do nothing" if prompted by an actionable whisper (sometimes it does not prompt)
4. Create a thread on the message in step 2
## Expected Result:
Tagged person is not invited to the group automatically

## Actual Result:
Tagged user is invited
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8353e01a-9bb8-41eb-ae38-5291c73942d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010459ddfa9dc85ebd</li>
        <li>Upwork Job ID: 1782306614845566976</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
Reproduced:

![image](https://github.com/Expensify/App/assets/59587260/8cf8257d-bedd-4275-8f83-62aee259f6e9)

**Comment by kadiealexander** [comment]
@hoangzinh would you agree this is related to the backend?

**Comment by kadiealexander** [comment]
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1714963718398899).

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by flodnv** [comment]
I also think this is fixed
