### ISSUE TITLE
[HOLD on 359760] Can't delete/reject instant submit Processing report in OldDot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40500]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713465529687719

## Action Performed:
1. Set up a workspace in OD with an option scheduled frequency to "instant"
2. Create a card expense report
3. Look for an option to delete report or reject the expense 
## Expected Result:
User should be able to delete the report or reject the expense
## Actual Result:
Unable to delete report or reject the expense

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Snip - Expense Report 2024-04-18 - Expensify - Report](https://github.com/Expensify/App/assets/38435837/70cd7f59-7990-4c8b-b090-8238b006ae52)

https://github.com/Expensify/App/assets/38435837/9c501eed-46aa-4d3b-b5c0-1873e6fe16ba

![image (4)](https://github.com/Expensify/App/assets/38435837/4930e106-15b7-46af-b861-b2aad1ef4f24)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Taking this one over to monitor the fix in https://github.com/Expensify/App/issues/40500

**Comment by garrettmknight** [comment]
Fixed
