### ISSUE TITLE
[$250] Android - Not found page closes prematurely when navigating to invalid WS links

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40509]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/36409
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open Android app
2. Create a workspace
3. Go to workspace settings page
4. From another app deep link to any of these links:
- https://staging.new.expensify.com/settings/workspaces/kjashdjkashdaks/rateandunit
- https://staging.new.expensify.com/settings/workspaces/kjashdjkashdaks/rateandunit/unit
- https://staging.new.expensify.com/settings/workspaces/kjashdjkashdaks/invite
- https://staging.new.expensify.com/settings/workspaces/kjashdjkashdaks/invite-message

## Expected Result:
Not found view should be visible

## Actual Result:
Not found view is seen for a second and then closes prematurely navigating to workspace settings page

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/16520eb9-4732-42cc-b280-77c90e1965bc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb3ea96da0ce5340</li>
        <li>Upwork Job ID: 1781079172553498624</li>
        <li>Last Price Increase: 2024-04-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by neil-marcellini** [comment]
I was away for a little bit but I'll start looking more closely now

**Comment by neil-marcellini** [comment]
Let's see if reverting https://github.com/Expensify/App/pull/36409 fixes the issue. I asked @fedirjh if he can test that since I'm busy with some backend stuff right now. I'll check back in 30 minutes.

**Comment by neil-marcellini** [comment]
@kbecciv or @fedirjh would you please test on Android staging to confirm that the issue is fixed?

**Comment by kbecciv** [comment]
Checking

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by neil-marcellini** [comment]
Ah yes thanks for the reminder

**Comment by twisterdotcom** [comment]
Payment Summary:

- @fedirjh paid $250 [here](https://www.upwork.com/nx/wm/offer/102427127)
