### ISSUE TITLE
[$250]  Web - Scan - Selecting tag via Enter key directly returns to first step of Scan request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40507]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- There is only one tag in the Collect workspace
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Submit expense > Scan
4. Upload a receipt
5. Click Tag
6. Press down arrow key (if tag is not auto-selected), then hit Enter

## Expected Result:
App will redirect to Scan confirmation page

## Actual Result:
App returns to the first page of Scan expense flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/45b9aa1c-458f-489a-b102-bcb48c2daec8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1670496416bc0ac</li>
        <li>Upwork Job ID: 1781244576274833408</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@tylerkaraszewski  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
Making this external to get more eyes on this

**Comment by combatmaestro** [comment]
The state is getting reset on enter making the user to land on the initial screen , we can look after the function getting triggered on enter keypress and resolve the issue

**Comment by Makosai** [comment]
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/EditRequestTagPage.js#L50 that's where it's located.

I'd actually make sure that selectTags is being called properly. If at all. And then see what changes afterwards to narrow down the source of the issue. One of the quickest things I'd do? Just check if the focus is being changed for some odd reason at the last minute. Weirder things have happened.

Contributor details
Your Expensify account email: kristopher.ali.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/makosai

**Comment by thienlnam** [comment]
Closing in favor of https://github.com/Expensify/App/issues/40551
