### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Group chat - Inconsistency in limitation when adding members via FAB and group details page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40512]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Click Add to group until the max amount of members is reached.
4. Note that only 8 participants can be selected.
5. Create the group chat with 8 participants.
6. Click on the chat header.
7. Go to Members > Invite member.
8. Invite a few more members.
## Expected Result:
There should be consistency whether more than 9 members (including the creator) is allowed in the group chat when adding members via FAB and group details page.

## Actual Result:
In Step 3, when creating group chat via FAB, not more than 8 members can be selected.
In Step 8. when adding members from group details page, there is no limitation at all.
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/b15b55be-3aac-48a9-afed-1a21eeff1cbe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cde40901114ff34c</li>
        <li>Upwork Job ID: 1781091286528417792</li>
        <li>Last Price Increase: 2024-04-18</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by kavimuru** [comment]
@jasperhuangg FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by jasperhuangg** [comment]
This appears to be a new feature that isn't on production yet (I think), so not worth blocking deploy on it. Plus it's a pretty minor bug. assigning @marcaaron since it looks like it was added in https://github.com/Expensify/App/pull/39757

**Comment by jasperhuangg** [comment]
Gonna assign external label since this can definitely be fixed by a contributor, @marcaaron if you wanna fix it yourself go ahead.

**Comment by marcaaron** [comment]
We can remove the limit when creating a chat. There is no limit anymore.

**Comment by mallenexpensify** [comment]
@ahmedGaber93 reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks. Plz review the PR
- https://github.com/Expensify/App/pull/40537

**Comment by ahmedGaber93** [comment]
Reviewing tomorrow.

**Comment by zanyrenney** [comment]
will you be able to review this today @ahmedGaber93 thanks!

**Comment by ahmedGaber93** [comment]
@zanyrenney sorry for the delay, reviewing today.

**Comment by zanyrenney** [comment]
Did you manage to review this? @ahmedGaber93

**Comment by ahmedGaber93** [comment]
@zanyrenney PR was reviewed 4 days ago. 
and there is a new commits today that I will review in the next few hours.

**Comment by zanyrenney** [comment]
payout due tomorrow.

**Comment by zanyrenney** [comment]
![2024-05-09_11-06-15](https://github.com/Expensify/App/assets/56830058/9494c365-d4a2-47fe-b753-3b004008d6e2)

**Comment by zanyrenney** [comment]
**payment summary**

@ahmedGaber93 requires payment (Needs manual offer from BZ) - owed $250 from ND.
@GandalfGwaihir requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) - paid $250 via upwork.

**Comment by ahmedGaber93** [comment]
@zanyrenney I get paid via upwork, not ND

**Comment by ahmedGaber93** [comment]
@zanyrenney bump for https://github.com/Expensify/App/issues/40512#issuecomment-2102420944

**Comment by ahmedGaber93** [comment]
@zanyrenney friendly bump https://github.com/Expensify/App/issues/40512#issuecomment-2102420944

**Comment by zanyrenney** [comment]
sure thing!

**Comment by zanyrenney** [comment]
paid @ahmedGaber93 $250 via upwork. closing!
