### ISSUE TITLE
[HOLD for payment July 22] Update line break regex for HTML->Markdown to support break tags with styles

### ISSUE THREAD

**Issue by Jag96** [Expensify/App#4052]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

More context in https://github.com/Expensify/Expensify.cash/pull/4009#issuecomment-879577943, this is part of https://github.com/Expensify/Expensify.cash/issues/3047, @parasharrajat will handle as a follow-up

## Action Performed:
1. Copy the following text: 

**Bold text**
_italic text_
~Strikethrough text~

2. Paste the text in e.cash

## Expected Result:
Line breaks should be included in the pasted message

## Actual Result:
Line breaks aren't included in the pasted message

![image](https://user-images.githubusercontent.com/3981102/125560806-81512d58-b062-4530-b195-2e400a7c3995.png)

## Workaround:
The user has to manually insert line breaks

## Platform:
Web

**Version Number:** 1.0.77-6

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by parasharrajat** [comment]
1. It is straightforward like we did for Italic.
`<br(?:"[^"]*"|'[^']*'|[^'">])*>(?![^<]*(<\/pre>|<\/code>))\n?`

We need to exclude pre and code tags and Allow any attribute between start tags, with one exception there is no end tag here.

**Comment by isagoico** [comment]
Let us know when https://github.com/Expensify/Expensify.cash/issues/3047 is fixed so we can retest this PR :)

**Comment by Jag96** [comment]
We're going to be doing https://github.com/Expensify/Expensify.cash/issues/3047 in pieces, so https://github.com/Expensify/Expensify.cash/pull/4009 is the latest PR (on staging) to test for this!

**Comment by Jag96** [comment]
Paid!
