### ISSUE TITLE
Track expense - Categorize it - Email result shows up and it leads to not here page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/38709
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Track expense.
3. Create a track manual expense.
4. Select Categorize it from the whisper.
5. Enter email in the search field.
6. Click on the email result.

## Expected Result:
No result should show up when searching via email because this is only limited to workspace chat.

## Actual Result:
Email result shows up and it leads to not here page when user clicks on it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7b4c8b46-78e6-4e84-a7ea-4de5c3ead3b5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by mountiny** [comment]
@ishpaul777 @shubham1206agra @thienlnam Are you able to look into this one?

**Comment by jliexpensify** [comment]
I think this is #vsb, as it deals with tracking expenses.

**Comment by thienlnam** [comment]
I also have a fix up that should fix this as well, it's the reportPreview to use the passed parameters
