### ISSUE TITLE
[$250] Hold request - Duplicate expense info shown if partially approving report with on hold expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40542]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/40065
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
recondition: user is an admin of collect workspace and invites an employee
1. Go to https://staging.new.expensify.com/
and log in as employee
2. Open the workspace chat and create 2 expense
3. Submit the report
4. Log in to ND as admin
5. Navigate the workspace chat
6. Open the submitted report and put on hold one of the expenses
7. Partially approve report (only the expense that is not on hold)
8. After the expense that is on hold is moved to a new report, open it

## Expected Result:
The expense is still on hold, no duplicated info is shown

## Actual Result:
The "On hold" badge is removed, the duplicated expense info is displayed for both admin and employee. Also, the "Hmm, not here.." screen is displayed after partially approving the report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4d09d38d-fa6b-460c-9564-9d4ccf0a9c44

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c7c1c7bfdf30f7a</li>
        <li>Upwork Job ID: 1781783652002193408</li>
        <li>Last Price Increase: 2024-04-20</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@abekkala I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/5fba61c9-11f4-47f5-8049-4528a811f925

**Comment by thienlnam** [comment]
cc @robertjchen Related to hold

**Comment by mountiny** [comment]
cc @marcochavezf from the PR

**Comment by marcochavezf** [comment]
Yeah, seems this is the same issue from this internal [convo](https://expensify.slack.com/archives/C036QM0SLJK/p1713385110931629?thread_ts=1713194504.295999&cid=C036QM0SLJK)

**Comment by mountiny** [comment]
If that is the case, I believe this is a backend issue and we can remove the blocker label, thanks

**Comment by abekkala** [comment]
@mountiny does this need a backend fix completely? If so, I can adjust the labels accordingly.
OR, does this first need a backend (internal fix) then move onto an external

**Comment by marcochavezf** [comment]
The fix needed was backend completely and has been deployed to production. Closing it
