### ISSUE TITLE
Fix E2E tests that are failing on merge on branches

### ISSUE THREAD

**Issue by danieldoglas** [Expensify/App#40544]
## Action Performed:
Tried to run the E2E tests action. Test here https://github.com/Expensify/App/actions/runs/8742174719

## Expected Result:
It should run successfully.

## Actual Result:
It failed.

## Workaround:
No workaround.

**Comment by staszekscp** [comment]
Hey! I'm Mariusz from SWM, and I have worked on this issue

**Comment by danieldoglas** [comment]
Fixed on https://github.com/Expensify/App/pull/40540!

**Comment by danieldoglas** [comment]
This is done!
