### ISSUE TITLE
[$250] IOU - "Approve" changes to "Review" for admin after submitting on behalf of employee

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40558]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisites:

- Create a collect WS on OD
- Enable chat for ND
- Invite an Employee to the WS
- Set scheduled submit to "Manually"

1. [Employee] Sign into OD and create a report and add an expense to it
2. [Employee] Confirm no violations or notes are associated with the expense on the report
3. [Admin] Sign into ND and Open the workspace chat
4. [Admin] Click on the preview component to open the report conversation
5. [Admin] Click on Submit on the header
6. [Admin] Observe the next steps on the header
7. [Admin] Go back to the workspace chat and click on the IOU preview to open the report conversation again and observe the next steps header

## Expected Result:
The next steps should persist in saying "...waiting for you to approve..."

## Actual Result:
The next steps first shows "...waiting for you to approve..." then after going to WS chat and back to expense conversation it changes to "...waiting for you to review..."

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/616a41cf-8c2e-41cc-91e3-b7cd7c396bd3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01703457fc2d10eaa6</li>
        <li>Upwork Job ID: 1783182554739961856</li>
        <li>Last Price Increase: 2024-05-29</li>
    </ul>
</details>

**Comment by kavimuru** [comment]
@CortneyOfstad FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by CortneyOfstad** [comment]
I don't think this is a bug, a we have tweaked the phrasing with the report submission flow. Going to test this and follow up

**Comment by CortneyOfstad** [comment]
Reviewing this and traditionally we referencing "reviewing" instead of "approving" when there are violations or notes listed on the report that require the attention of the admin/approver. 

However, reviewing the video again, I cannot see any violations or notes, and either way – the message should stay consistent. Going to get eyes on this 👍

**Comment by CortneyOfstad** [comment]
Still waiting on someone to pick this up 👍

**Comment by CortneyOfstad** [comment]
Following up with Tom on #wave-collect. What is odd is that the "review" option is strictly for violations/notes on reports, and in my testing, my report did not have any notes or violations.

**Comment by CortneyOfstad** [comment]
I just tested again and I am not able to get it to recreate. Reviewing the video again, there is a notation, which would trigger the **Review** prompt instead of _Approve_.

I am going to see if this can be retested, and I updated the initial prompt/steps to indicate no notes or violations listed on the report in OldDot 👍

**Comment by CortneyOfstad** [comment]
Updated the original steps 👍

**Comment by CortneyOfstad** [comment]
Waiting for this to be tested by QA before applying the project. I have not been able to recreate 👍

**Comment by CortneyOfstad** [comment]
Still has not been tested yet, so once that is tested and confirmed it can be recreated, then we will apply it to a project 👍

**Comment by CortneyOfstad** [comment]
Avoiding this going overdue to share that again — still waiting for it to be tested before applying to a project 👍

**Comment by CortneyOfstad** [comment]
still waiting for this to be tested melvin!

**Comment by CortneyOfstad** [comment]
Same as before – waiting for this to be tested before applying a project!

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests.
https://github.com/Expensify/App/assets/43995119/4fa6950b-65a6-4930-906a-0d50f73c1791

**Comment by mvtglobally** [comment]
https://github.com/Expensify/App/assets/43995119/3101021b-e410-4c86-b4e2-726f462ce1d4

**Comment by CortneyOfstad** [comment]
Thanks @mvtglobally for confirming!

**Comment by CortneyOfstad** [comment]
Still waiting on proposals — will post in the room to get some eyes on this

**Comment by CortneyOfstad** [comment]
Posted in Open-Source [here](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1716387556307749)

**Comment by CortneyOfstad** [comment]
No bites on the post — going to bump again 👍

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment]
Just tested and was not able to recreate either. Going to close 👍
