### ISSUE TITLE
[HOLD for payment 2024-05-22] [$250] Onboarding- By pulling vertically, user is able to dismiss iOS Onboarding

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40555]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Access New Expensify iOS app
2. Sign into a valid account
3. Go to Settings > Troubleshoot > Onboarding flow to open the modal
4. Pull down vertically (Right under the status bar)
## Expected Result:
User expects two thing:

1. If the user SHOULD be able to dismiss this modal, they should be able to do so via swiping horizontally as in all other parts of the app (Not vertically)

2. According to the[ PR](https://github.com/Expensify/App/pull/37733), this modal should NOT be able to be closed at all , therefore pulling or swiping horizontally or vertically should not toggle any action

## Actual Result:
The modal can be dismissed by pulling down vertically, while the modal on screen slides off the screen horizontally. To be able to dismiss the modal, user should pull down directly under the status bar on the top of the device screen.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/ddec0fb0-0c44-4b47-bd78-cb2c43829e61

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c66b77d9e4afbb5b</li>
        <li>Upwork Job ID: 1785060015292096512</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by mountiny** [comment]
@cdOut @filip-solecki can you please comment here so I can assign you, you have been looking into this one before

**Comment by cdOut** [comment]
Hi, I’m Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I’d like to work on this task.

**Comment by MitchExpensify** [comment]
How is the PR coming along @cdOut ?

**Comment by cdOut** [comment]
I was testing my solutions on native devices and web today, I should have the PR up early next week and push it fast through the review process.

**Comment by MitchExpensify** [comment]
Checking in on the PR @cdOut 🙇

**Comment by cdOut** [comment]
I had to reprioritize due to Filip and Jakub both being OOO and I had to overtake some more important tasks from the Xero flow, I will try to work on this one tomorrow.

**Comment by mountiny** [comment]
Lets make this external

**Comment by cdOut** [comment]
@mountiny agreed, I won't be able to work on this before being out of office due to the xero and travel tasks. Thank you!

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
Seems like the bug was introduced in this [PR](https://github.com/Expensify/App/pull/40688). I am an author. So I am fixing the bug like a regression.

**Comment by MitchExpensify** [comment]
https://github.com/Expensify/Expensify/issues/399532

Thanks, @parasharrajat

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
