### ISSUE TITLE
QAB - Shortcut for manual request show as "Track expense" instead of "Track manual"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40554]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #39640
**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. Open the self-DM chat or WS chat
3. Click + > Track Expense and follow the process to add a manual track expense
4. Click + FAB icon & observe shortcut shown as "Track expense" instead of "Track manual"

## Expected Result:
Shortcut for manual track expense should show as "Track manual" instead of "Track expense"

## Actual Result:
Shortcut for manual track request show as "Track expense" instead of "Track manual"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6454407_1713491834074!Screenshot__186_](https://github.com/Expensify/App/assets/43996225/faa07d20-2369-44e7-9ef0-aa5d7f313664)

https://github.com/Expensify/App/assets/43996225/df6d6236-80f6-488f-959f-1a8632994635

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@mallenexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Shortcut for manual request show as "Track expense" instead of "Track manual"

### What is the root cause of that problem?
Wrong text here
https://github.com/Expense/App/blob/9b2c5187e2203d83bba50bfa66936691788cbd18/src/languages/en.ts#L601-L602
### What changes do you think we should make in order to solve the problem?

Change it to 
```
        trackManual: 'Track manual',

```
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment]
Thanks @GandalfGwaihir , I've def been a lil tripped up this week with some of the updated around 'request money' to 'submit expense' and also 'track expense'.
