### ISSUE TITLE
[HOLD for payment 2024-05-13] [$250] Web - Pressing on keyboard enter key on notification option of a room takes back two steps

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40551]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** EXP around https://expensify.testrail.io/index.php?/tests/view/4494233
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a room
3. Open the room page
4. Click on header
5. Click on settings
6. Click on Notify me about new messages
7. Select a notification preference option by using the keyboard arrow keys
8. Press enter on one of the options

## Expected Result:
App should navigate to Settings page

## Actual Result:
App navigates to Room details page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/6b79c3b3-8794-4848-8108-5a5b282cf797

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01889a2544214bb02d</li>
        <li>Upwork Job ID: 1781342777391833088</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by kavimuru** [comment]
@mountiny FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb

**Comment by allroundexperts** [comment]
Since we have a better proposal here, we can close the other.

**Comment by allroundexperts** [comment]
@suneox Were you able to figure out the PR which caused this issue?

**Comment by mountiny** [comment]
@suneox can you prepare a PR with the fix and make sure you test properly all the keyboard selection shortcuts in various places of the app? Thanks

**Comment by mountiny** [comment]
Please either @suneox or @allroundexperts try to raise a PR for this one when you get a chance, thanks

**Comment by allroundexperts** [comment]
I'll be home in about 2 hours. Will raise one right away.

**Comment by allroundexperts** [comment]
Started working on it.

**Comment by mountiny** [comment]
@suneox you can test the PR as a C+ role

**Comment by allroundexperts** [comment]
PR: https://github.com/Expensify/App/pull/40642

**Comment by allroundexperts** [comment]
Checking 👀

**Comment by allroundexperts** [comment]
> > Hi @allroundexperts could you please check [my commit](https://github.com/Expensify/App/compare/main...suneox:ExpensifyApp:40551-double-event-when-enter) your PR was missing set `shouldPreventEnterKeySubmit=true` for the BaseSelectionList so the result still not fix
> 
> https://github.com/Expensify/App/blob/4dc0d91dbf2dbc41ee62032ae6b11b41b0c53d48/src/pages/settings/Report/NotificationPreferencePage.tsx#L41-L45
> 
> I'd like to explain for [my commit](https://github.com/Expensify/App/compare/main...suneox:ExpensifyApp:40551-double-event-when-enter) change
> 
> At page `NotificationPreferencePage` SelectionList using `ListItem={RadioListItem}` so we have to forward `shouldPreventEnterKeySubmit` props inside `RadioListItem`
> 
> And we can use CONST.KEYBOARD_SHORTCUTS.ENTER.shortcutKey instead of string 'Enter'

Is this limited to `RadioListItem` only? I feel like we should do this for all list items.

**Comment by allroundexperts** [comment]
@suneox Makes sense. Let's fix the radio item list first. Updated the PR.

**Comment by allroundexperts** [comment]
Will update the screen recordings in the next few mins as well.

**Comment by allroundexperts** [comment]
@suneox Updated and added screen recordings. Let's take this convo to the PR.

**Comment by mountiny** [comment]
@suneox I believe you cannot review a you are not C+, but you can leave comments with the checklist and approve by comment

**Comment by kevinksullivan** [comment]
Payment summary:
- @suneox $250
- @allroundexperts $250 (NewDot)

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
