### ISSUE TITLE
[Wave Collect] [Guided Setup Stage 2] Add the split expense task type

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#40573]
### Problem

As part  of the stage 2 onboarding flow, the user will be able to choose an intent saying they want to chat and split expense with friends.

This task is missing in backend right now

### Solution

Add the new task to the guided setup flow and ensure its autocompleted when user splits their bill with someone.

**Comment by mountiny** [comment]
Pr is up but I need to add more tests there

**Comment by trjExpensify** [comment]
@mountiny this can be closed, right?

**Comment by trjExpensify** [comment]
Going to close this!
