### ISSUE TITLE
[$250]  Group chat - Custom avatar reverts to default avatar after promoting member to Admin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Go to FAB > Start chat
3. {User A] Create a group chat with User B
4. {User A] Send a message to chat
5. [User A] Upload a group chat avatar
6. [User B] Open the group chat
7. [User A] Promote User B to Admin
8. [User B] Wait for a while to receive the update

## Expected Result:
Group avatar will not revert to default avatar after promoting User B to admin

## Actual Result:
Group avatar reverts to default avatar after promoting User B to admin. However, it changes back to custom avatar after a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d590b410-a1e6-4df5-893e-82cc04cc2cb2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee2daa5a2c3e8900</li>
        <li>Upwork Job ID: 1781378609184792576</li>
        <li>Last Price Increase: 2024-04-26</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by blimpich** [comment]
Demoting as I don't think this is an actual blocker. Fairly minor. Also wasn't able to reproduce it.

**Comment by blimpich** [comment]
@marcaaron unless you feel like this should be handled as part of group chats I'd say we open this open to contributors and see if anyone else can reproduce and figure out the issue

**Comment by marcaaron** [comment]
Yeah it could be - I'll add it to the GH Project I have set up to track these. Definitely, agree not a blocker.

>Group avatar reverts to default avatar after promoting User B to admin. However, it changes back to custom avatar after a while

Seems like we could possibly be removing it in the optimistic data somewhere.

**Comment by marcaaron** [comment]
@blimpich lmk if you want me to take this one off your hands.

**Comment by blimpich** [comment]
Will do, I'm good to be the CME for this I think 👍

**Comment by laurenreidexpensify** [comment]
WAiting for weekly retesting to confirm if we want to close

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
