### ISSUE TITLE
Pay someone - Letter "s" in "Pay someone" banner is capitalised

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40581]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Pay someone
3. Enter amount > Next
4. Click on "Pay Someone" bottom banner

## Expected Result:
Letter "s" in "Pay someone" should not be capitalised

## Actual Result:
Letter "s" in "Pay someone" is capitalised

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="1440" alt="Bug6454977_1713537354594!Screenshot_2024-04-19_at_22 31 51" src="https://github.com/Expensify/App/assets/78819774/46f8cf36-768f-486a-9f45-b12468074a99">

<img width="1440" alt="Bug6454977_1713537354595!Screenshot_2024-04-19_at_22 32 04" src="https://github.com/Expensify/App/assets/78819774/321e6167-c9c5-425a-9bd8-46e4157bf1dd">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by francoisl** [comment]
That seems like a simple copy change, no need to block on this. All these came from https://github.com/Expensify/App/pull/39483/files#diff-2a9066512656fa29b1565e362127de5cc11ba95b28f143a9db26f76dc3750785, I'll double-check all the changes there to make sure they look correct. We'll also need to check changes to `es.ts`.

**Comment by francoisl** [comment]
> We need to double check to make sure capitalization is consistent. For example:

Thanks for linking those, but they all seem like they haven't been changed in a while, and most of them are used as titles, which we do usually capitalize. I'll just update the "Pay Someone, get $250" for now.
