### ISSUE TITLE
[Help Wanted] Clicking on a workspace chat is not 1:1:1

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#40580]
Conversation https://expensify.slack.com/archives/C03TQ48KC/p1713540323130089

I clicked on a workspace chat and got all this requests:
![image](https://github.com/Expensify/Expensify/assets/521248/d3ac9186-0f3f-4e24-82a7-973897f1367b)

That's not 1:1:1, so we should look into why we are calling GetOlderActions and GetNewerActions (we can ignore SendPerformanceTiming and Log).

This is related to comment linking project.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a174d992f29870e0</li>
        <li>Upwork Job ID: 1783291294058426368</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by strepanier03** [comment]
Following along to play BZ but for the time being. Posted in the conversation to see if we want to set this external or internal.

**Comment by strepanier03** [comment]
Setting Internal for now because a similar issue from the thread was also set internal. We can update as needed.

**Comment by strepanier03** [comment]
Needs internal work, not prioritized in the Wave currently.

**Comment by strepanier03** [comment]
Slated for polish so could be a little bit before it's picked up.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment]
Thanks @mvtglobally!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by strepanier03** [comment]
Appreciate the update.

**Comment by jayeshmangwani** [comment]
@strepanier03 The issue is set internal; what is the next step here?

**Comment by strepanier03** [comment]
@jayeshmangwani - The next step is to wait for someone internally to pick it up. It's tied to Wave-Collect and set with a Polish priority so it could potentially be a bit before it's picked up because other more important things are waiting.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

https://github.com/Expensify/App/assets/43995119/d6c52715-7ded-4541-b6e3-71b1c93e4ea2

**Comment by strepanier03** [comment]
This isn't repro'd for a third week so I'm going to close it out. It's not a priority either so we can open this in the future if it crops up again or we're looking into old polish issues.
