### ISSUE TITLE
Chat - Mention containing valid report ID is not clickable and invalid # is not styled

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39906
**Reported:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Send text containing the following mention with # :
- valid report ID
- invalid report ID
- invalid room name

## Expected Result:
![image](https://github.com/Expensify/App/assets/93399543/8f6fe550-d675-4388-adf5-eb6b3e14fee4)

## Actual Result:
![image](https://github.com/Expensify/App/assets/93399543/9908552a-c555-4e40-91a6-4f2e3ad2fe0b)

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2129cdcd-7ed1-4aff-9f4f-880329340f34

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@jliexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by mountiny** [comment]
cc @robertKozik @puneetlath

**Comment by jliexpensify** [comment]
Can't assign @robertKozik until he comments, but have assigned Puneet for this regression.

**Comment by robertKozik** [comment]
Hi! Looking into it, thanks for pinging me here!

**Comment by robertKozik** [comment]
I think we have a little misunderstanding there. User is able to mention rooms only by their names. ReportID values are embedded into HTML attributes of mention tag, and are done on the backend side.
While trying to type mention by id, parser will correctly recognise it as proper mention (as numbers are valid room name), but the typed value would be assume as room name.

But I think we can be. more consistent while we are working on optimistic version of the message, as we will want to remove as much as possible jumping between highlighted -> non-highlighted states when getting the response from the backend.

**Comment by puneetlath** [comment]
Yes, I think we can close. This is just a misunderstanding.
