### ISSUE TITLE
No space between text and attachment when sending both within same message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40606]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-11
**Reproducible in staging?:** y
**Reproducible in production?:** Different uI
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713539843203629

## Action Performed:
Send a message that has an attachment inside of it

## Expected Result: 
I would expect there to be a small margin between the text and the image, basically the same space we might use between two messages

## Actual Result: 
The message and the attachment are too close together

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-04-19 at 11 17 59@2x](https://github.com/Expensify/App/assets/38435837/2edebaf7-46a2-4fed-a4f1-4eaa6a993cb3)

![CleanShot 2024-04-19 at 11 17 34@2x](https://github.com/Expensify/App/assets/38435837/37b75999-e7c9-4ece-8277-c22b946423ae)
![Snip - (25) New Expensify](https://github.com/Expensify/App/assets/38435837/acac5551-07ba-40bc-9ae3-7c5e6167f43d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec4deb839d6f3c2a</li>
        <li>Upwork Job ID: 1781406798961565696</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by roryabraham** [comment]
from @tgolen in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1713548294452049?thread_ts=1713539843.203629&cid=C049HHMV9SM):

> I know what this is. I can fix it on Monday. If there is a GH you can assign it to me

**Comment by tgolen** [comment]
I've submitted a PR for this on the backend which has been merged already. It should deploy to staging by tomorrow and then this can be closed.

**Comment by tgolen** [comment]
This is done and can be closed.
