### ISSUE TITLE
IOU - Workspace owes instead admin cancelled the payment shows on member LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39963
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. [Member] Request money in workspace chat.
2. [Admin} Pay elsewhere the request.
3. [Member] Note that the LHN preview shows "Admin: paid $ elsewhere" format.
4. [Admin] Cancel the payment.

## Expected Result:
For both users (Admin and member) the action should show on LHN "cancelled the $ payment" format.

## Actual Result:
For Member, the LHN preview for payment cancellation is showing "Workspace owes $"

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/10b2320f-9165-4f28-84f9-8e3d77186cea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bfitzexpensify** [comment]
Linked to https://github.com/Expensify/App/issues/36704, commented over there.

**Comment by kavimuru** [comment]
Issue is not reproducible anymore. 
![Capture](https://github.com/Expensify/App/assets/43996225/3662057b-609a-4dea-934a-1609bcb68c42)

**Comment by bfitzexpensify** [comment]
Thanks! Closing this one out.
