### ISSUE TITLE
Web - Login page - Stack with 'E' logo under specific Mac/Safari versions

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40603]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Try to login

## Expected Result:
The user should be able to login without any issues

## Actual Result:
Stuck with 'E' logo under Specific Safari versions:
Safari 16.1 Released October 24, 2022 / macOS 13.0
Safari 15.6.1 Released August 17, 2022 / macOS 12.5

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/347721d6-460e-487a-8060-4e8b0b2c3cf6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I tested in staging and I can open the App just fine. If the issue only happens in those specific version, I'm just gonna close this issue since those are really outdated Safari versions from over 2y ago.
