### ISSUE TITLE
[$250] [HOLD for payment 2024-07-17] Clicks are interrupted on iOS

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#40613]
HOLD on https://github.com/software-mansion/react-native-screens/pull/2107

---

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-11
**Reproducible in staging?:** yes
**Reproducible in production?:** not sure, but we think probably yes
**Slack conversation:** https://expensify.slack.com/archives/C06UTGZBWCA/p1713542919463249

## Action Performed:
1. Open the app
1. Scroll down
1. Tap on some report that was not in view before you scrolled down. When you do this, slide your finger to the left of right, making sure to keep it over the report.

## Expected Result:
The report should be opened

## Actual Result:
Nothing happens

## Workaround:
Don't slide your finger at all when tapping on the report.

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d2b3beed0f9d8ce</li>
        <li>Upwork Job ID: 1814432666103182597</li>
        <li>Last Price Increase: 2024-07-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by roryabraham** [comment]
note that this is very similar to https://github.com/Expensify/App/issues/40048, but on iOS instead of Android. We think that this will be fixed by https://github.com/Expensify/App/pull/40560, which is iOS-specific. For that reason, we think that this is a different bug with a similar symptom

**Comment by roryabraham** [comment]
verified that this was fixed by https://github.com/Expensify/App/pull/40560. No payments are due. I'm keeping this open for the sake of tracking the [upstream PR](https://github.com/software-mansion/react-native-screens/pull/2107) and making sure that we upgrade react-native-screens and remove this patch when it's released upstream.

Making this a weekly in the meantime

**Comment by roryabraham** [comment]
https://github.com/software-mansion/react-native-screens/pull/2107 was merged but not released yet. Awaiting another release of react-native-screens

**Comment by roryabraham** [comment]
Still on HOLD pending another release of react-native-screens

**Comment by roryabraham** [comment]
Still awaiting another release

**Comment by roryabraham** [comment]
Still awaiting [another release after 3.31.1](https://github.com/software-mansion/react-native-screens/releases)

**Comment by roryabraham** [comment]
same ^

**Comment by roryabraham** [comment]
This is ready to come off HOLD

**Comment by roryabraham** [comment]
Created https://github.com/Expensify/App/pull/44427, just need screenshots on iOS but for the sake of efficiency I kicked off an AdHoc build there

**Comment by roryabraham** [comment]
kk, $250 due to @ahmedGaber93 for the review of https://github.com/Expensify/App/pull/44427

**Comment by roryabraham** [comment]
@lschurr this is ready to pay out whenever you come through this issue. Thanks!

**Comment by lschurr** [comment]
[Offer](https://www.upwork.com/nx/wm/offer/103217113) sent to @ahmedGaber93

**Comment by ahmedGaber93** [comment]
@lschurr offer accepted
