### ISSUE TITLE
[Payment due][$500] Implement Uneven Splits

### ISSUE THREAD

**Issue by youssef-lr** [Expensify/App#40616]
Implement this [section](https://docs.google.com/document/d/1wOB61kuktAKbvMsg8dAm9FaO_bhZepXe8agQtvvpgk4/edit#bookmark=id.vwzu855dle59) of the design doc. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b261d8e3721b659</li>
        <li>Upwork Job ID: 1794886821581795328</li>
        <li>Last Price Increase: 2024-05-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by youssef-lr** [comment]
PR should be ready for review first thing Monday morning.

**Comment by youssef-lr** [comment]
More progress is done in the PR, I'm resolving one final issue [here](https://expensify.slack.com/archives/C03TQ48KC/p1713819487655579)

**Comment by youssef-lr** [comment]
Heads up: C+ payout for this one should be $500.

**Comment by c3024** [comment]
@youssef-lr I was the C+ for the PR and reviewed and tested it. Could you reopen this?

**Comment by c3024** [comment]
@youssef-lr I was the C+ for the PR and reviewed and tested it. Could you please reopen this?

**Comment by youssef-lr** [comment]
Done, sorry!

**Comment by c3024** [comment]
Thanks. I think Bug and Daily labels need to be added for assigning a BZ member for payment.

**Comment by youssef-lr** [comment]
Will do on Monday.

**Comment by c3024** [comment]
@youssef-lr gentle bump on this

**Comment by youssef-lr** [comment]
@kadiealexander can we please issue payment for @c3024? Thanks!

**Comment by kadiealexander** [comment]
@c3024 could you please apply in Upwork [here](https://www.upwork.com/jobs/~012b261d8e3721b659)? Thanks!

**Comment by c3024** [comment]
@kadiealexander applied, thanks. But the Upwork job price is shown as only $250. This is a $500 issue.

**Comment by kadiealexander** [comment]
Fixed.

**Comment by c3024** [comment]
Applied!

**Comment by c3024** [comment]
Thanks, accepted the offer!
