### ISSUE TITLE
Update the header name in Track expense, Submit expense, and Split expense

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#40615]
As part of the Add split to global create doc, and specifically [this section](https://docs.google.com/document/d/1Z0V68fpdUhx21bsmX-DV0zXx0-w-kRIO00Wpblac9AU/edit#bookmark=id.pbm897776vhd), we are updating the header for the `Track expense`, `Submit expense`, and `Split expense` flows, to keep that title in the header for the whole flow instead of updating the header to show the "type" of track/request/split the person is creating (like `manual`).

Here is an example from Split, where you'll see the header is `Split expense` throughout.

![image](https://github.com/Expensify/App/assets/22508290/09f9532b-789f-404a-81ee-7df6533d6a13)

Let's make this update to each of the mentioned flows.

**Comment by getusha** [comment]
deployed to production last week

**Comment by getusha** [comment]
We can close this @mountiny
