### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] improve failureNotifier.yml to catch more failures

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#40612]
## Problem

This is a follow up to [this issue](https://github.com/Expensify/App/pull/34262). Its possible for breakages in `main` to go undetected still if issues created by previous breakages aren't closed out properly. See [relevant slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1713554811796439).

## Solution

Improve the workflow to catch these failures.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aebc028b3ff06629</li>
        <li>Upwork Job ID: 1781420349384224768</li>
        <li>Last Price Increase: 2024-04-19</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by blimpich** [comment]
I would like @jjcoffee and @rayane-djouah to work on this since they did the original ticket and have context.

**Comment by blimpich** [comment]
@rayane-djouah @jjcoffee are you both available to work on this this week?

**Comment by jjcoffee** [comment]
I'm available. Do you need anything from me @rayane-djouah?

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR MAY 09

- Fix: @rayane-djouah [$250, if no regressions] [offer link](https://www.upwork.com/nx/wm/workroom/37043431/overview)
- PR Review: @jjcoffee [$250, if no regressions] [offer link](https://www.upwork.com/nx/wm/workroom/37043777/overview)

**Comment by abekkala** [comment]
This isn't overdue - payment is set for tomorrow!

**Comment by abekkala** [comment]
@rayane-djouah and @jjcoffee payments sent and contracts ended - thank you!
