### ISSUE TITLE
 [$250]  IOU - Unable to change currency in transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40631]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-13
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40605
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Create a manual request
4. Go to transaction thread
5. Click Amount
6. Click Currency
7. Change the currency

## Expected Result:
The currency is changed

## Actual Result:
The currency is not changed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d01d3457-a405-4cdd-a4c3-3e0abf96c365

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f76111d172d99485</li>
        <li>Upwork Job ID: 1781769508041547776</li>
        <li>Last Price Increase: 2024-04-20</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment]
@tgolen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
Taking this over and making it external

**Comment by mountiny** [comment]
Looking for proposals

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Unable to change currency in transaction thread
### What is the root cause of that problem?
When we update currency we set it in draft transaction here  but in amount screen we get it from backup transaction here
### What changes do you think we should make in order to solve the problem?
Use `draftTransaction` here 
 
### What alternative solutions did you explore? (Optional)
Set in backup transaction here

**Comment by mountiny** [comment]
Can you please also point to the regression PR? thank you

**Comment by shahinyan11** [comment]
> Can you please also point to the regression PR? thank you

https://github.com/Expensify/App/pull/40605

**Comment by mountiny** [comment]
Assigning @allroundexperts as c+ here because of the regression

@shahinyan11 Can you please raise the PR with a fix? thanks!

**Comment by shahinyan11** [comment]
@mountiny Just one clarification, should I implement my main solution?

**Comment by s77rt** [comment]
@shahinyan11 This will reintroduce https://github.com/Expensify/App/issues/40543

**Comment by mountiny** [comment]
^^ that

**Comment by allroundexperts** [comment]
@mountiny I don't have full context of this either. I just reviewed a deploy blocker. I'll try to dig into this.

**Comment by shahinyan11** [comment]
Watching to [this](https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/libs/actions/TransactionEdit.ts#L6C1-L8C4)  I understand that we can modify original transaction during editing . And when the user undoes editing of a transaction, we can update the original transaction based on the backup transaction.

**Comment by s77rt** [comment]
https://github.com/Expensify/App/pull/38892 is also related. It's probably the one that caused https://github.com/Expensify/App/issues/40543 and not https://github.com/Expensify/App/pull/39144

**Comment by shahinyan11** [comment]
I want bring  your attention to [this](https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/iou/request/step/IOURequestStepAmount.tsx#L111C1-L113C104) comment

**Comment by s77rt** [comment]
I think it's best to revert https://github.com/Expensify/App/pull/39144 (and it's follow up https://github.com/Expensify/App/pull/40605). The new backup collection is adding more complexity and that PR [apparently](https://github.com/Expensify/App/pull/39144#issuecomment-2067781505) didn't fix the linked issue

**Comment by shahinyan11** [comment]
@ishpaul777 In my option the backup transaction never should be modified modified . And the alternative solution in my proposal is not correct

**Comment by shahinyan11** [comment]
Updating [this](https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/iou/request/step/IOURequestStepAmount.tsx#L82C76-L82C119) check like below will solve also https://github.com/Expensify/App/issues/40543
```
const {currency: originalCurrency} = ReportUtils.getTransactionDetails(isEditing && !draftTransaction ? transaction : draftTransaction ) ?? {currency: CONST.CURRENCY.USD};
```

**Comment by shahinyan11** [comment]
@ishpaul777 what's wrong there?

**Comment by shahinyan11** [comment]
As I understand a backup transaction was created for transactions whose editing has several steps and the data is saved at the last step.

**Comment by shahinyan11** [comment]
> Isn't the amount one of that field, user can edit the amount as well as currency

Sorry, but I don't understand what you mean with this

**Comment by shahinyan11** [comment]
Yes user can update amount filed. And what problem do you see in this?

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/40631#issuecomment-2067772590)

**Comment by shahinyan11** [comment]
> but you suggest that we should use the draft transaction for currecnt, isn't that looks confusing and a hacky workaround
> We create a Backup transaction here specifically for editing
> https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/iou/request/step/IOURequestStepAmount.tsx#L107C1-L123C12
> 
> but you suggest that we should use the draft transaction for currecnt, isn't that looks confusing and a hacky workaround

This implementation has several disadvantages.
1. Update [.TRANSACTION_DRAFT](https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/libs/actions/IOU.ts#L362C39-L362C56) to `.TRANSACTION`
2. Update [draftTransaction](https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/iou/request/step/IOURequestStepCurrency.tsx#L48C81-L48C97) to `transaction`
3. Update [this](https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/iou/request/step/IOURequestStepAmount.tsx#L82C76-L82C119) condition to just `transaction`
```
ReportUtils.getTransactionDetails( transaction) ?? {currency: CONST.CURRENCY.USD}
```

**Comment by shahinyan11** [comment]
> We create a Backup transaction here specifically for editing
> 
> https://github.com/Expensify/App/blob/8616678cef4af714c63abf7147853e34fb40f4ce/src/pages/iou/request/step/IOURequestStepAmount.tsx#L107C1-L123C12
> 
> but you suggest that we should use the draft transaction for currecnt, isn't that looks confusing and a hacky workaround

We should remove this implementation or use my alternative solution https://github.com/Expensify/App/issues/40631#issuecomment-2067772590

**Comment by shahinyan11** [comment]
@ishpaul777  backup meaning is that it should not be modified.  If we have a backup saved, we can directly edit the original transaction and reverse it based on the backup when we undo the edit.

**Comment by shahinyan11** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/40631#issuecomment-2067772590). Added new solution as main.

@ishpaul777 @s77rt @allroundexperts I believe that my new solution will solve both the current problem and https://github.com/Expensify/App/issues/40543. Please take a look

**Comment by DylanDylann** [comment]
@mountiny From my point of view, we should revert [the PR](https://github.com/Expensify/App/pull/40605) to fix this issue

**Comment by shahinyan11** [comment]
@DylanDylann Can't we use [this](https://github.com/Expensify/App/issues/40631#issuecomment-2067801170) solution instead crated new `createDraftTransaction` function in you [PR](https://github.com/Expensify/App/pull/40655)

**Comment by DylanDylann** [comment]
@shahinyan11 The idea of my change in [this PR](https://github.com/Expensify/App/pull/40655) is trying to hold the old logic and don't update any thing

**Comment by mountiny** [comment]
Its a bit confusing for sure, I think that reverting would be best but also I can see that this PR https://github.com/Expensify/App/pull/39144 actually seems to have fixed 2 issues (one remained) so I dont think we can simply revert it

**Comment by mountiny** [comment]
Upon the discussion, I agree that the solution from @shahinyan11 is not ideal to be CPed. We will not have a full regression done and there is a risk that if we are going to switch to the draft transaction, we will introduce regressions in some other parts of the flow.

I am not fully sure why we have both backup and draft transactions or whether its necessary, but for sure its not easy to follow.

I have assigned @DylanDylann so they can revert the previous CP that caused this issue and fix the original regression since they are the author of the offending PR and they were available.

@shahinyan11 I am sorry for the outcome and I appreciate the help and effort here, but this time we had to move with safer approach as its one of the last deploy blockers to be CPed and if there would be some regression caused elsewhere, we might not be able to catch it. I hope you understand. Thanks

**Comment by mountiny** [comment]
I have assigned @DylanDylann so they can revert the previous CP that caused this issue and fix the original regression since they are the author of the offending PR and they were available.

If solution provided from @shahinyan11 has been used, we will provide partial compensation

**Comment by shahinyan11** [comment]
> If solution provided from @shahinyan11 has been used, we will provide partial compensation

@ikevin127  For information - my solution has been usef

**Comment by mountiny** [comment]
Lets pay out 50% to @shahinyan11 

So the payment summary is $125 to @shahinyan11 and $250 to @ikevin127 for testing and review

**Comment by ikevin127** [comment]
⚠️ Automation failed here -> this should be on **Hold for payment [2024-04-29]** according to 2days ago's production deploy from https://github.com/Expensify/App/pull/40655#issuecomment-2069797349.

**Comment by ikevin127** [comment]
@mountiny Payment is due today on this issue based on https://github.com/Expensify/App/issues/40631#issuecomment-2076258778.

Can you please assign somebody from `Bug` to handle this today ? Thank you!

**Comment by mallenexpensify** [comment]
@mountiny can you help here with the payment breakdown?

@shahinyan11 is due $125 ( can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~01f76111d172d99485
@ikevin127 is due $250 (already paid will update final breakdown at end)
@DylanDylann , what are they owed? I knee-jerk paid them $250 in Upwork

**Comment by shahinyan11** [comment]
@mallenexpensify I have apllied to the job

**Comment by mallenexpensify** [comment]
@mountiny is back on Monday, gonna pause here til then.

**Comment by mountiny** [comment]
@mallenexpensify I believe that breakdown is good

**Comment by ShaheFS** [comment]
@mallenexpensify I have applied to the job but you weren't accepted

**Comment by shahinyan11** [comment]
@mallenexpensify I applied but you didn't accept

**Comment by mallenexpensify** [comment]
Correct @shahinyan11 , can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~01f76111d172d99485

**Comment by shahinyan11** [comment]
> Correct @shahinyan11 , can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~01f76111d172d99485

@mallenexpensify I have accepted

**Comment by mallenexpensify** [comment]
Since this came from a regression I don't _think_ we need a new TestCase, comment/reopen if you disagree.
