### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Does not show the chat room in the results  when searching for the rooms user is a part of

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713480493902799
 
## Action Performed:
1. Join any public room
2. Search for the room using search icon 
## Expected Result:
Search results should display the result in which the user is a part of
## Actual Result:
No results found error message appears
For @davidcardoza Shows the results for any room which are pinned
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/902b3f7a-be62-4070-9e52-08d360b60744

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b0a0277b5ad4344</li>
        <li>Upwork Job ID: 1782705413299757056</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by saifelance** [comment]
@m-natarajan The current  behaviour looks ok

**Comment by saifelance** [comment]
@dragnoir 

 This issue stems from a condition in the createOptionList and getOptions functions in OptionsListUtils.ts.

To address this issue, you proposed modifying the condition to also check if the report is a chat room before returning if accountIDs.length === 0. Here's how you could implement this change:

`if ((!accountIDs || accountIDs.length === 0) && !isChatRoom) {
  return;
}
`

**Comment by saifelance** [comment]
@dragnoir Correct 
 users should indeed be able to search for and find public chat rooms that they have joined. 
 
You can modify the condition to ensure that public chat rooms are included in the search results. 
 
`if ((!accountIDs || accountIDs.length === 0) && !isChatRoom && !isPublic) {
  return;
}
`

By adding !isPublic to the condition, you ensure that public chat rooms are not excluded from the search results. This change allows users to search for and find public chat rooms they have joined.

**Comment by saifelance** [comment]
@ Right
@dragnoir Correct
 users should indeed be able to search for and find public chat rooms that
they have joined.

You can modify the condition to ensure that public chat rooms are included
in the search results.

`if ((!accountIDs || accountIDs.length === 0) && !isChatRoom && !isPublic) {
  return;
}
`

By adding !isPublic to the condition, you ensure that public chat rooms are
not excluded from the search results. This change allows users to search
for and find public chat rooms they have joined.

**Comment by anmurali** [comment]
@akinwale have you had a chance to review proposals above?

**Comment by davidcardoza** [comment]
@anmurali should we find someone else to review proposals? It's been over a week now since there has been activity in this GH.

**Comment by akinwale** [comment]
I missed the notifications on this one. Reviewing the proposal now.

**Comment by akinwale** [comment]
We can move forward with @dragnoir's [proposal](https://github.com/Expensify/App/issues/40654#issuecomment-2068206288) here.

@dragnoir You need to add another condition to check that the chat room is a public room, otherwise, the workspace rooms like `#announce` and `#admins` will show up in the search results, which I reckon we don't want.

🎀👀🎀 C+ reviewed.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the Expensify App.
2. Join a new public chat room.
3. Click or tap on the search icon and try to search for the chat room.
4. Verify that the chat room appears in the search results.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@anmurali bump for payment. Thanks.

**Comment by anmurali** [comment]
@akinwale is paid
@dragnoir - offer is [here](https://www.upwork.com/nx/wm/offer/102818906)

**Comment by anmurali** [comment]
Everyone is paid!
