### ISSUE TITLE
[HOLD for payment 2024-05-02] [Wave Collect][QBO] Add the explanatory text on the categories page with Hyperlink when the accounting software is connected

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#40660]
Add the explanatory test on the Categories page to describe that the categories are imported from QBO when acccounting connection exists.
<img width="400" alt="Screenshot 2024-04-21 at 1 39 53 PM" src="https://github.com/Expensify/App/assets/98560306/7e08e4f0-0f9c-49c7-8238-268912283bca">

**Comment by MitchExpensify** [comment]
Reminder set to pay.

Payment summary:

$250 @s77rt requires payment (Needs manual offer from BZ)

Are you on the NewDot Pilot out of curiosity @s77rt ? I'll update the internal SO if so!

**Comment by MitchExpensify** [comment]
Got it! Offer sent here https://www.upwork.com/nx/wm/offer/102068993

**Comment by s77rt** [comment]
@MitchExpensify Accepted! Please issue a payment of $125 since the PR caused a regression

**Comment by MitchExpensify** [comment]
Will do, thanks for the heads up

**Comment by MitchExpensify** [comment]
Paid via bonus and contract ended. Thanks, @s77rt !
