### ISSUE TITLE
Please add regression test for #34307

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#40677]
Please add regression test for: https://github.com/Expensify/App/issues/34307

**Regression Test Proposal**

```
1. Open App and select a chat.
2. Send a message containing emojis
3. Hover over the emoji and verify that a tooltip appears 
4. Verify tooltip displays an enlarged emoji and the emoji name
```

**Comment by zanyrenney** [comment]
cc @applausebot @isagoico

**Comment by saifelance** [comment]
@zanyrenney Correct 
<img width="332" alt="Screenshot 2024-04-22 at 2 17 33 PM" src="https://github.com/Expensify/App/assets/5357289/64dd86d9-41a6-4524-b278-a9be92fbc023">

**Comment by isagoico** [comment]
Apologies I added the incorrect label by mistake 🫠 
This TC has been updated to include this validation: 
- [Key Navigation - Emoji Picker](https://expensify.testrail.io/index.php?/cases/view/2644133)

Closing the issue, please reopen if needed.
