### ISSUE TITLE
[HOLD for payment 2024-05-29] [Wave Collect] [Ideal nav] Simplify the navigator structure

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#40681]
Follow up to the ideal navigation project, we have one task to simplify the structure now.

### Problem

Currently, central pane screens in FullScreenNavigator are wrapped with the central pane navigator. A similar pattern can be seen in LHP where single screens are wrapped with navigators.
This may be problematic for two reasons:
- Getting information about the actual screen requires more code. It has become visible especially after we migrated to typescript. Instead of just getting the route name we have to extract the route from the state or params of the parent navigator.
- More nested navigators means worse performance.

### Solution

In the early implementation of navigation, we used the custom component ThreePaneView. That was the main reason to encapsulate screens with central pane navigators. Now we use StackView for both narrow and wide layouts and the wide layout is achieved using styles.

This allows us to flatten the navigation structure. Now screens in FullScreenNavigator and LHP will be mounted directly
This way developing and maintaining navigation should be easier and we should get a slight performance boost.

cc @adamgrzybowski @WojtekBoman

**Comment by WojtekBoman** [comment]
Hi! I'm working on that :)

**Comment by stephanieelliott** [comment]
Reapplying the `New Feature` label to get another BZ member on this while I am OOO til May 2. Thanks @strepanier03,  I'll grab this back from you when I return!

**Comment by stephanieelliott** [comment]
I'm back from OOO, thanks for watching this while I was out @strepanier03! 

Hey @WojtekBoman, any update on when this PR will be taken out of the `Draft` state?

**Comment by stephanieelliott** [comment]
> Hey @WojtekBoman, any update on when this PR will be taken out of the Draft state?

Bump on this @WojtekBoman, how is the PR coming?

**Comment by WojtekBoman** [comment]
Hi @stephanieelliott, 

I'm currently working on the new search tab as it has higher priority. I think I'll have some time to release a PR this/next week.

**Comment by stephanieelliott** [comment]
Makes sense, thanks for the update @WojtekBoman!

**Comment by stephanieelliott** [comment]
Hey @WojtekBoman, any update on this?

**Comment by mountiny** [comment]
This was merged and deployed to staging, awaiting production deploy

**Comment by stephanieelliott** [comment]
This was deployed to prod on May 22! Will be ready for payment on May 29

**Comment by mountiny** [comment]
@ahmedGaber93 is the only person required payment of $250 on this issue

No regression testing required

**Comment by stephanieelliott** [comment]
I had to manually create a job on Upwork for this

 - [Upwork Job](https://www.upwork.com/jobs/~01aa5d7e85aa17b84e)
 - Offer for @ahmedGaber93: https://www.upwork.com/nx/wm/offer/102533846

@ahmedGaber93 please let me know when you've accepted the offer so I can issue payment!

**Comment by ahmedGaber93** [comment]
@stephanieelliott Offer accepted. Thanks!

**Comment by stephanieelliott** [comment]
Thanks @ahmedGaber93, all paid!
