### ISSUE TITLE
Web - IOU - Page opens up waypoint RHP while URL is invalid

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB > Submit expense> Distance tab
3. Click on start
4. Copy the URL
5. Open any chat and paste the URL and add anything at the end to make the URL invalid (e.g of the invalid URL: https://staging.new.expensify.com/create/request/waypoint/1/undefined/0?backTo=%2Fcreate%2Frequest%2Fstart%2F1%2F1557579756269441%2Fdistance/anything
)
6. Click on the sent URL
7. Input any valid address and click on the suggestion

## Expected Result:
Not here page should load right away when user clicks on the invalid URL

## Actual Result:
Waypoint editor RHP first opens up and after user inserts an address and clicks on the suggestion the not here view loads

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6859d8b5-101b-472e-8c4a-fbe876d96173

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by sakluger** [comment]
Manually changing the URL is not expected user behavior so I don't think this is worth fixing right now.
