### ISSUE TITLE
[$250] [Wave Collect][QBO] Refactor the error text style

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#40697]
From [this convo](https://github.com/Expensify/App/pull/39191#discussion_r1570455699) in another App PR.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab49e87b72a1e37d</li>
        <li>Upwork Job ID: 1795779159359643648</li>
        <li>Last Price Increase: 2024-05-29</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 102509287</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by narefyev91** [comment]
@shawnborton can you please clarify - are we expecting Error Text position like this one?
<img width="378" alt="Screenshot 2024-04-29 at 13 49 56" src="https://github.com/Expensify/App/assets/28352309/d9a30f2d-9d82-4844-8446-beb728c05dbc">

**Comment by shawnborton** [comment]
While we are at it, I wonder if we should take a look at the hint text too to make sure the hint text works the same way - same distance below the push row, and is included in the hoverable interacation.

**Comment by narefyev91** [comment]
@shawnborton hover:
<img width="370" alt="Screenshot 2024-04-29 at 17 44 04" src="https://github.com/Expensify/App/assets/28352309/7af59968-6f9e-4925-8b12-a4ae8d3bc79b">

**Comment by narefyev91** [comment]
Yeah for sure - i will also include hint issue to this PR fix

**Comment by shawnborton** [comment]
Okay cool, as it stands now, it seems like maybe there is too much padding below the error text? Notice how the bottom portion of the hover is larger than the top.

**Comment by narefyev91** [comment]
> Okay cool, as it stands now, it seems like maybe there is too much padding below the error text? Notice how the bottom portion of the hover is larger than the top.

Yeah - this coming from standard menu item component. - should we also change paddings which we already have?
<img width="410" alt="Screenshot 2024-04-29 at 17 46 28" src="https://github.com/Expensify/App/assets/28352309/2aa19f8a-6183-40c0-a5de-62c8061f7699">

**Comment by shawnborton** [comment]
Yeah, I would expect that vertical padding to be equal. So if we're doing 12px on top, why not 12px on the bottom? Or maybe we just do 16px vertically so we split the difference?

**Comment by narefyev91** [comment]
> Yeah, I would expect that vertical padding to be equal. So if we're doing 12px on top, why not 12px on the bottom? Or maybe we just do 16px vertically so we split the difference?

Good point - but i do not see any vertical logic to make a difference.
In any case - it should be 12px below - based on all other menu items. I will update that for sure! Thanks!

**Comment by dannymcclain** [comment]
Just popping in to say I agree with everything going on in this convo.

**Comment by narefyev91** [comment]
@shawnborton this one with hint text below:
<img width="380" alt="Screenshot 2024-04-30 at 11 16 37" src="https://github.com/Expensify/App/assets/28352309/e3710e19-7493-44a6-b981-46b278a0c8c5">

**Comment by shawnborton** [comment]
Nice, and can you show us that same scenario but with no error text?

Also, in the error case, is it possible to move the red dot closer to the right arrow? They feel a little far away right now, cc @Expensify/design for a gut check on that one. Perhaps we can try 8px and 12px gaps, respectively, for comparison?

**Comment by narefyev91** [comment]
@shawnborton here you are:
<img width="375" alt="Screenshot 2024-04-30 at 15 49 16" src="https://github.com/Expensify/App/assets/28352309/f724aa3a-b884-46a8-a79c-d02dd3ebf6e9">

**Comment by narefyev91** [comment]
And closer red dot as well:
<img width="375" alt="Screenshot 2024-04-30 at 15 50 41" src="https://github.com/Expensify/App/assets/28352309/7577d104-72e0-4470-b407-69fd5e0486c3">

**Comment by narefyev91** [comment]
> Yes please! Not sure how 18px ever got introduced as a line height, I don't think we should be using it anywhere?

Nice - sure will update that!

**Comment by laurenreidexpensify** [comment]
@s77rt please accept role in Upwork and will issue payment thanks

**Comment by s77rt** [comment]
@laurenreidexpensify Accepted! Please note this is due $125 as there was a regression

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ Review $125 @s77rt paid in upwork
