### ISSUE TITLE
 Workspace - Default workspace rooms aren't visible for the new member

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40691]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63.13
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Admin: Log in with a new expensifail account
2. Admin: Create a workspace
3. Member: Log in with a new Gmail account
4. Admin: Invite the new Gmail account to the workspace
5. Member: Navigate to the LHN

## Expected Result:
Default workspace rooms should be visible for the member.

## Actual Result:
Default workspace rooms aren't visible for the new member. Rooms are missing from the LHN and search too even after refreshing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6742976d-55ac-4060-88f2-dfb03eab9f48

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by adelekennedy** [comment]
I cannot reproduce this, I think this was solved!
