### ISSUE TITLE
[HOLD for payment 2024-05-02] Split scan - Missing Split button in the split menu RHP

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40709]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a split scan expense.
4. When the expense is still scanning, click on the split preview.
5. Enter amount and merchant.

## Expected Result:
There will be a Split button in the split menu RHP.

## Actual Result:
There is no Split button in the split menu RHP.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/83058603-ecf3-4123-977c-5ef35471d992

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-split

**Comment by mountiny** [comment]
Removing the label, the PR will be QAed on the checklist for confirmation

**Comment by brunovjk** [comment]
Issue generated through my/our refactoring [PR](https://github.com/Expensify/App/pull/40176), and fixed by my/our [PR](https://github.com/Expensify/App/pull/40659) mentioned above.
I believe that **no payment will be necessary here**.

**Comment by brunovjk** [comment]
> Issue generated through my/our refactoring [PR](https://github.com/Expensify/App/pull/40176), and fixed by my/our [PR](https://github.com/Expensify/App/pull/40659) mentioned above. I believe that **no payment will be necessary here**.

I think we can close this one. It's been 7+ days since the PR has been in production
