### ISSUE TITLE
Onboarding - Missing attachment, not here page and skeleton in concierge task page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Troubleshooting > Onboarding flow.
3. Select "Chat and split expenses with friends" > Next.
4. Enter name > Next.
5. Go to Concierge chat.
6. Click on any task.
7. Select an assignee.

## Expected Result:
In Step 5, the attachment will show up in Concierge chat.
In Step 6, in task page, there will not be "Not here" page.
In Step 7, task report will not show skeleton loading after assigning an assignee.

## Actual Result:
In Step 5, the attachment is displayed as [Attachmnt] in Concierge chat.
In Step 6, in task page, "Not here" page flickers briefly.
In Step 7, task report shows skeleton loading after assigning an assignee.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d3c87f41-a3e4-40d4-809a-789065d90ff4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
Taking this over cc @rezkiy37 @filip-solecki @cdOut @hoangzinh @rayane-djouah @francoisl from the onboarding initiative

**Comment by mountiny** [comment]
Just merged a backend Pr for this

**Comment by mountiny** [comment]
https://github.com/Expensify/Auth/pull/10606

**Comment by kevinksullivan** [comment]
Auth PR is merged / depoyed. I think we are done here @mountiny ?

**Comment by mountiny** [comment]
Yep I think this is done
