### ISSUE TITLE
Submit Expense - Header Remains as "Submit Expense" Instead of "Manual"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40717]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.64.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/35822
**Issue reported by:** Applause - Internal Team

## Action Performed:
1, Tap on the FAB > "Submit Expense."
2, Choose the "Manual" option and input the amount.
3, Click "Next." Observe that the header continues to display "Submit Expense" instead of changing to "Manual."

## Expected Result:
The header should change to "Manual" after entering the amount and clicking "Next."

## Actual Result:
The header remains as "Submit Expense" instead of changing to "Manual" during the expense submission process.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ea496d83-d1fc-4e34-add9-8b3a22a33c6e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-split

**Comment by francoisl** [comment]
Looks like this is expected based on [this thread](https://expensify.slack.com/archives/C05RECHFBEW/p1713203395106859?thread_ts=1712786178.162249&cid=C05RECHFBEW).

There's going to be a follow-up issue to update the headers for all money request flows later (it will also not go back to saying "Manual")

**Comment by mountiny** [comment]
Correct this is no expected behaviour, thanks ❤️
