### ISSUE TITLE
Distance - Distance row shows "0.00 miles" instead of "Pending" after changing distance

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a distance expense.
4. Go to transaction thread.
5. Click Distance.
6. Change the distance and save it.

## Expected Result:
Distance row will show "Pending" while the expense is being updated.

## Actual Result:
Distance row shows "0.00 miles" while the expense is being updated.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/db2d9b29-9a3d-449f-9be0-09ddd8442000

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
@koko57 @neil-marcellini this might be related to this PR, can you please have a look? https://github.com/Expensify/App/pull/38543

**Comment by koko57** [comment]
I can fix this in my next PR

**Comment by mountiny** [comment]
@koko57 are you able to expedite that Pr so it can be merged and CPed tomorrow?

**Comment by koko57** [comment]
yes, of course - the draft is already ready (https://github.com/Expensify/App/pull/40711), let me just add this fix

**Comment by amyevans** [comment]
Perfect, thanks!

**Comment by koko57** [comment]
@neil-marcellini @mountiny changes pushed, test steps updated

**Comment by amyevans** [comment]
This got CPed, closing!
