### ISSUE TITLE
[HOLD for payment 2024-05-02] Distance - Selected distance rate is not highlighted in rate list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38543
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Submit expense > Distance.
4. Proceed to confirmation page.
5. Click Rate below Distance.

## Expected Result:
The selected distance rate will be highlighted.

## Actual Result:
The selected distance rate is not highlighted.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f5f330f1-8193-428b-8562-a79efcf7b142

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
This is minor so demoting, the checkmark is there

**Comment by koko57** [comment]
@mountiny please assignt this one to me

**Comment by mountiny** [comment]
I believe this can be closed
