### ISSUE TITLE
[HOLD for payment 2024-05-03] [$250] [QAB]  "Pay elsewhere" button is small when paying someone via Quick action

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40721]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Pay someone.
3. Enter amount.
4. Select a user and pay them.
5. Go to FAB.
6. Click Pay someone under Quick action.

## Expected Result:
"Pay elsewhere" button will have the same shape and size as other green CTA buttons across the app.

## Actual Result:
"Pay elsewhere" button is small.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/12b19a1a-8d31-4085-93c5-9420d0e5a462

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc0683310300cbba</li>
        <li>Upwork Job ID: 1782500044140408832</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
looking fro proposals

**Comment by akinwale** [comment]
@Krishna2323 Can you determine if this is a regression and what the source is?

**Comment by akinwale** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/40721#issuecomment-2070871872) works here.

🎀👀🎀 C+ reviewed.

**Comment by blimpich** [comment]
@Krishna2323 please feel free to raise a PR 👍

**Comment by blimpich** [comment]
I don't consider this a blocker for the deploy. Going to remove the `DeployBlockerCash` label.

**Comment by trjExpensify** [comment]
CC: @Gonals 👀

**Comment by trjExpensify** [comment]
Alright, ready for payments here. 

- @akinwale $125 for the initial proposal review - paid
- @Krishna2323 $250 for the bug fix - paid 
-  @c3024 no payment necessary here for this PR review, as it was a regression follow-up.

As for the checklist:

- no regression test will be necessary, we're adding them centrally for QAB already.
- we know the offending PR and the author/reviewer was involved in the follow-up here

Thanks everyone, closing!
