### ISSUE TITLE
[HOLD for payment 2024-05-03] Onboarding - Message received in Concierge DM does not include correct and bold text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40725]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/40393
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open app
2. Go to /onboarding
3. Enter first name and last name go, click "Continue" on the onboarding modal
4. Click any option apart from "I'm just looking around"

## Expected Result:
The message you receive in your Concierge DM should include some bold text

## Actual Result:
Message received in Concierge DM does not include expected and bold text

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/eb58bf28-b8c5-43ed-89c1-9e8c585f1974

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
I believe @rezkiy37 is handling this, its not a blocker as this flow is not yet shown to the users

**Comment by rezkiy37** [comment]
I am fixing this problem in this [PR](https://github.com/Expensify/App/pull/40688) of the scope of this [issue](https://github.com/Expensify/App/issues/38771).

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by muttmuure** [comment]
Waiting

**Comment by muttmuure** [comment]
Chatted with @joekaufmanexpensify and we're going to use this issue to pay @rushatgabhane for this PR: https://github.com/Expensify/App/pull/40688

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
