### ISSUE TITLE
[$500] Android - Report - Attempting to save an edited post freezes the app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40723]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/40547
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app
2. Navigate the conversation with a large message history
3. Scroll up the message history
4. Select any message and go to the thread
5. Navigate back to the conversation
6. Scroll up the message history
7. Select any message and edit it
8. Send the edited message

## Expected Result:
The message modification should be applied immediately when the send button is pressed

## Actual Result:
Attempting to save an edited post freezes the app

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1b2e85a3-e3af-44fb-8855-ad70305ba0a0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114ce3629e3c33f49</li>
        <li>Upwork Job ID: 1782501943628816384</li>
        <li>Last Price Increase: 2024-04-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
cc @roryabraham @kosmydel Seems like coming from testing the inverted flatlist issue

**Comment by AndrewGable** [comment]
Discussing here: https://expensify.slack.com/archives/C01GTK53T8Q/p1713867912363639

Seems new arch related so we might remove blocker as it seems to be Android only.

**Comment by mountiny** [comment]
based on the discussion, it seems like the same root cause of the other new arch android issue so removing the blocker

**Comment by roryabraham** [comment]
Requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1714331841052739

**Comment by kavimuru** [comment]
Reproduced and freeze can be observed at timeline 2:00

https://github.com/Expensify/App/assets/43996225/765fbe01-036a-480d-90c2-7fd98e1d7ac1

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Good to close?

**Comment by AndrewGable** [comment]
Yep, good to close.

**Comment by mallenexpensify** [comment]
Reopening per [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1717603618188529)
@akinwale , please comment and link to PR you reviewed.  Thx

**Comment by akinwale** [comment]
@mallenexpensify Here's the PR: https://github.com/Expensify/App/pull/41101

Thanks.

**Comment by akinwale** [comment]
@mallenexpensify Offer accepted. Thanks!

**Comment by mallenexpensify** [comment]
Contributor+: @akinwale paid $500 via Upwork
