### ISSUE TITLE
Task - "Mark as complete' button grays out briefly when selecting Delete/Pin

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Create a task.
3. Go to task report.
4. Tap 3-dot menu.
5. Select Delete or Pin.

## Expected Result:
"Mark as complete' button will not gray out briefly.

## Actual Result:
"Mark as complete' button grays out briefly.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5afe02a6-e677-4b0b-b0f0-9d182be09c25

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
@tienifr @rlinoz @mananjadhav can you please address this?

**Comment by mountiny** [comment]
@cead22 if you have time, could yo please check if reverting https://github.com/Expensify/App/pull/39397 fixes the issue?

**Comment by rlinoz** [comment]
Not sure how to fix this, the button is gray while if you click on it there will be no action. That comes from us not wanting to allow tapping on something and tapping on `Mark as complete` at the same time.

I think there is the option to not gray it out, but if you click on it nothing will happen.

**Comment by rlinoz** [comment]
Running a build to check if a revert fixes this.

**Comment by rlinoz** [comment]
Yeah, I was going for something similar, but there will be the problem of not being clear that you can't perform the action at that exact moment. With that said, I think it should be fine since it is such a brief moment and it is better than having the button blinking gray.

**Comment by rlinoz** [comment]
Reverting here https://github.com/Expensify/App/pull/40729 since it was reported that it did not fix the main issue https://github.com/Expensify/App/pull/39397#issuecomment-2070921187

**Comment by rlinoz** [comment]
Asked for CP: https://expensify.slack.com/archives/C07J32337/p1713821522369469

**Comment by mountiny** [comment]
Thanks!

**Comment by rlinoz** [comment]
I believe we can close this one
