### ISSUE TITLE
[$250] [HOLD for payment 2024-05-06] Group split scan - Error appears for Merchant when clicking Split expense for the second time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40749]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense > Scan.
3. Create split scan expense with a few users.
4. In group chat, click on the split preview.
5. Click Split expense.
6. Click Split expense again.

## Expected Result:
There will be no error under Merchant field because Merchant is not a requirement for non-workspace expense.

## Actual Result:
Error shows up under Merchant field when clicking Split expense for the second time.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/d77d2a68-3f03-4eb1-aed1-5d43f837c459

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013158f9aa7567f244</li>
        <li>Upwork Job ID: 1790113061570207744</li>
        <li>Last Price Increase: 2024-05-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by kavimuru** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-split

**Comment by saifelance** [comment]
@GandalfGwaihir 
 We should modify the condition to ensure that the error is set to true only if the merchant is required. So, an additional && check for isMerchantRequired needs to be added. This adjustment ensures that the error is set only when the merchant is both required and empty:
 
`diff --git a/src/components/MoneyRequestConfirmationList.tsx b/src/components/MoneyRequestConfirmationList.tsx
index 99901dd261..87d605a7a5 100755
@@ -577,7 +577,7 @@ function MoneyRequestConfirmationList({
             if (selectedParticipants.length === 0) {
                 return;
             }
-            if ((isMerchantRequired && isMerchantEmpty) || (shouldDisplayFieldError && TransactionUtils.isMerchantMissing(transaction ?? null))) {
+            if ((isMerchantRequired && isMerchantEmpty) || (isMerchantRequired && shouldDisplayFieldError && TransactionUtils.isMerchantMissing(transaction ?? null))) {
                 setMerchantError(true);
                 return;
             }
`

**Comment by mountiny** [comment]
This is minor UX issue, demoting @koko57 seems like its coming from your PR

**Comment by koko57** [comment]
@mountiny As the follow-up PR wasn't merged yet I can fix it there

**Comment by koko57** [comment]
@mountiny PR opened: https://github.com/Expensify/App/pull/40868

**Comment by johncschuster** [comment]
Reviewing payment now

**Comment by mountiny** [comment]
I think the only payment here is to pay $250 to @Ollyws for their review and testing

**Comment by johncschuster** [comment]
Applying the `External` label to create the job. @Ollyws, Upwork isn't returning you when I search for you because... Upwork 🙄 . Can you apply to the job and ping me? I'll get payment issued ASAP!

**Comment by johncschuster** [comment]
@Ollyws Aha! I found you. Your offer is [here](https://www.upwork.com/offer/102305381). Can you accept that?

**Comment by johncschuster** [comment]
@Ollyws, I see you've _just_ been added to the list of contributors who can accept payment via NewDot. I'll go ahead and post a payment summary instead so you can be paid via that method.

**Comment by johncschuster** [comment]
# Payment Summary
Contributor+: @Ollyws - $250 via Manual Request

**Comment by johncschuster** [comment]
@robertjchen can you complete the [BZ checklist](https://github.com/Expensify/App/issues/40749#issuecomment-2083834152) above?

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws

**Comment by robertjchen** [comment]
Working through checklist

**Comment by johncschuster** [comment]
Bumping this for Melvin. How's the checklist going, Robert?

**Comment by robertjchen** [comment]
@johncschuster Made my assessment, and left the last item for you 👍

**Comment by johncschuster** [comment]
Thanks @robertjchen! Looks like we can close this up!
