### ISSUE TITLE
2FA - Web - Infinite loading spinner on 2FA authentication page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40742]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4500402&group_by=cases:section_id&group_order=asc&group_id=229043
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to New dot and enter expensifail account with 2FA enabled
2. Navigate to email and locate the magic link - change to staging
3. Open an new tab and navigate to the staging link
## Expected Result:
2FA required page should be displayed and no loading spinner should appear

## Actual Result:
Infinite loading spinner when user navigates to 2FA authentication page

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/13c37703-397d-46bd-8220-e71e6764ae77

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@MonilBhavsar  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MonilBhavsar** [comment]
Commented on the suspected PR https://github.com/Expensify/App/pull/40177

**Comment by mountiny** [comment]
@MonilBhavsar Cn you please try to revert that PR and test on it? We should CP the revert if that is the case, thanks!

**Comment by MonilBhavsar** [comment]
Okay thanks! I'll put revert PR on hold then

**Comment by mountiny** [comment]
Thanks for help Monil

**Comment by bernhardoj** [comment]
PR is up

cc: @parasharrajat

**Comment by MonilBhavsar** [comment]
Fixed on staging 

<img width="1723" alt="Screenshot 2024-04-23 at 9 32 48 PM" src="https://github.com/Expensify/App/assets/32012005/26225474-476e-4b26-b8ba-0a1abd398e74">
