### ISSUE TITLE
Split - Search field is refocused and the list scrolls up every time a member is selected

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40747]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense > Manual.
3. Enter amount > Next.
4. Enter a term in the search field.
5. Scroll down.
6. Select any member.

## Expected Result:
The search field will not refocus and the list will not scroll up every time a member is selected (production behavior).

## Actual Result:
The search field is refocused (web, desktop) and the list scrolls up every time a member is selected.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/f5c7cb8f-2b76-4830-82a7-fcb17759fcae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
Demoting as this is minor UX change

**Comment by MonilBhavsar** [comment]
Commented on the suspected PR https://github.com/Expensify/App/pull/40370#issuecomment-2071931622

**Comment by MonilBhavsar** [comment]
We're looking to add QA steps and close this

**Comment by MitchExpensify** [comment]
What QA steps @MonilBhavsar ? Do these look good?

1. Go to FAB > Split expense > Manual.
2. Enter amount > Next.
3. Enter a term in the search field.
4. Scroll down.
5. Select any member.
6. Verify the search field will not refocus and the list will not scroll up every time a member is selected

**Comment by MonilBhavsar** [comment]
For step 6, I would expect it to be "Verify the search field is refocussed and input is cleared"
Though looks like we're creating a new issue for this, so may be we add tests in the new issue once we implement it. What do you think @mountiny

**Comment by mountiny** [comment]
Can be handled here https://github.com/Expensify/App/issues/41049
