### ISSUE TITLE
[$750] [Awaiting Payment May 2nd] [Wave Collect][QBO] Fetch `connections` data in import, export and advanced pages

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#40744]
<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by trjExpensify** [comment]
PRs are here: 

Export pages: https://github.com/Expensify/App/pull/40713 
Import pages: https://github.com/Expensify/App/pull/40716
Advanced pages: https://github.com/Expensify/App/pull/40718

**Comment by hayata-suenaga** [comment]
https://github.com/Expensify/App/pull/40716 this one was merged
we're working on the last remaining PR, which is this one -> https://github.com/Expensify/App/pull/40718

**Comment by trjExpensify** [comment]
All of the PRs are merged/deployed here.

**Comment by alexpensify** [comment]
@trjExpensify - are we good to close this one?

**Comment by trjExpensify** [comment]
We're going to need to pay @s77rt for the reviews here, I believe.

**Comment by alexpensify** [comment]
Noted, we will need for the 7-day window to close, and then I can begin the payment process. Thanks!

**Comment by alexpensify** [comment]
@trjExpensify and @hayata-suenaga to confirm, should this be $250 x 3 (so $250 for each PR) or was there another price agreed to here? Thanks!

**Comment by trjExpensify** [comment]
Per PR is fine! 👍

**Comment by alexpensify** [comment]
@s77rt - Please accept the Upwork invite here: 

https://www.upwork.com/jobs/~01b94d0a49094e3e0e

After, I can carry on with the payment process. Thanks!

**Comment by s77rt** [comment]
@alexpensify The payment due here is $250. The other issues are being handled separately

**Comment by alexpensify** [comment]
Thanks for the heads up, @s77rt. I've completed the payment in Upwork for $250.

**Comment by alexpensify** [comment]
Payouts due: May 2, 2024

- [ ] Contributor: N/A
- [ ] Contributor+: $250 @s77rt 

Upwork job is [here](https://www.upwork.com/jobs/~01b94d0a49094e3e0e).
