### ISSUE TITLE
Track expense - Track expense option is not displayed in fab.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4501563
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login as new expensifail user
3. Tap fab

## Expected Result:
Track expense option must be displayed in fab.

## Actual Result:
Track expense option is not displayed in fab.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6e871e90-005a-4e8d-b21b-6d36d11257e0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dedd0ac1251499f9</li>
        <li>Upwork Job ID: 1782875414268760064</li>
        <li>Last Price Increase: 2024-04-23</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by jliexpensify** [comment]
cc @thienlnam and @hungvu193 - you worked on that PR.

**Comment by hungvu193** [comment]
This is BE issue, when self DM is not added to `allReports`. We already mentioned it here while working on that PR
https://github.com/Expensify/App/pull/40409#discussion_r1572659123

cc @thienlnam

**Comment by mountiny** [comment]
Based on this comment it seems like https://github.com/Expensify/App/pull/40409#discussion_r1572659123 this is expected and it will be handled in BE, assigning Jack

**Comment by thienlnam** [comment]
Yup, this is anticipated. We'll need to make a change to always return the self-DM on OpenApp

**Comment by jliexpensify** [comment]
Not overdue. @thienlnam want to keep this as `Daily` or change the priority?

**Comment by thienlnam** [comment]
This should be resolved with https://github.com/Expensify/Auth/pull/10668, but we're running into some performance problems so we may need to revert it
