### ISSUE TITLE
[HOLD for payment 2024-05-02] [$250] Android - Workspace list - Workspace name and email address are truncated

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40754]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User has long email address and also workspaces with medium long name.

1. Launch New Expensify.
2. Go to Account settings.
3. Go to Workspaces.
4. Compare the truncation of workspaces with long name and long email address between staging and production.

## Expected Result:
App will show complete workspace name and email address if it fits the screen.

## Actual Result:
Workspace name and email address are truncated when the app could display it without truncation.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Production
![Bug6458349_1713847764855!production](https://github.com/Expensify/App/assets/115492554/9885f327-456d-4e0e-b055-f59a9ae48adf)

Staging
![Bug6458349_1713847764854!staging](https://github.com/Expensify/App/assets/115492554/845d3c1a-cf68-40d8-b8f0-5e9da55601ec)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae7f4f24d827fbac</li>
        <li>Upwork Job ID: 1782704515639697408</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by izarutskaya** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by mountiny** [comment]
Making this external, it should hopefully be easy fix

**Comment by shawnborton** [comment]
So I think this is a good example of a regression from @dragnoir 's PR. Perhaps we should have Rachid submit a follow up rather than awarding a new bounty for this?

**Comment by shawnborton** [comment]
This was the offending PR: https://github.com/Expensify/App/pull/40599/files

**Comment by shawnborton** [comment]
Let's see what @mountiny thinks.

**Comment by mountiny** [comment]
cherry picking the PR

**Comment by mountiny** [comment]
Noting that https://github.com/Expensify/App/pull/40599 Pr has been deployed to production already so it cannot be the offending PR of this deploy blocker.

**Comment by kevinksullivan** [comment]
@getusha can you accept the offer in upwork?

**Comment by kevinksullivan** [comment]
Paid @tienifr

**Comment by mountiny** [comment]
@getusha has this been paid?

**Comment by kevinksullivan** [comment]
Still waiting on @getusha to accept. Will slack them

**Comment by kevinksullivan** [comment]
alright, all set!
