### ISSUE TITLE
[HOLD for payment 2024-05-06] Split scan - No error for missing amount when clicking Split expense for workspace split scan

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40756]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a split scan expense.
4. When the expense is scanning, click on the split preview.
5. Click Split expense.

## Expected Result:
An error will show up for the missing amount.

## Actual Result:
No error shows up for the missing amount when clicking Split expense.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b31e3df5-3b1d-4915-8d82-920b0475cfbd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@dylanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by mountiny** [comment]
Seems like a minor thing, it shows up unreliably @koko57 might be related to your PR?

**Comment by koko57** [comment]
@mountiny I will check it

**Comment by koko57** [comment]
@mountiny PR opened: https://github.com/Expensify/App/pull/40868

**Comment by dylanexpensify** [comment]
Pending prod -> regression period -> pay

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
No payment needed
