### ISSUE TITLE
[$250] Distance - Gap displayed between start&finish after moving stops and deleting one

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40753]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4504672
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: user is a member of a workspace

1. Open the app and log in
2. Tap FAB > Submit expense > Distance
3. Enter 3 waypoints
4. Drag and drop the middle stop to make it the finish location
5. Delete one of the waypoints

## Expected Result:
There is no gap between the start and finish waypoints

## Actual Result:
Gap is displayed between the start and finish points

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4555e4f1-8b34-40f9-8e53-3a4e192b245b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010136e7715586d143</li>
        <li>Upwork Job ID: 1782700920406261760</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by izarutskaya** [comment]
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by garrettmknight** [comment]
I don't think we need to block the deploy for this, but I've reproduced. Opening it up.

**Comment by garrettmknight** [comment]
Still waiting on proposals

**Comment by garrettmknight** [comment]
Still waiting on proposals

**Comment by garrettmknight** [comment]
Still waiting on proposals

**Comment by garrettmknight** [comment]
Thanks @Krishna2323 - will hold on https://github.com/Expensify/Expensify/issues/373964#issuecomment-2101162329

**Comment by garrettmknight** [comment]
Still holding

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/issues/40105

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/issues/40105

**Comment by garrettmknight** [comment]
We're off hold - updating to daily to test tomorrow.

**Comment by garrettmknight** [comment]
Confirmed this is fixed. Closing.
