### ISSUE TITLE
Distance - Mileage Rate changes from previous value when editing waypoints

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40762]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Found when validating PR :** https://github.com/Expensify/App/pull/38543
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: User should be an employee of a collect workspace which has a custom mileage rate

1. Navigate to staging.new.expensify.com
2. Click on FAB > Submit expense > Distance
3. Insert start and finish points
4. Select the collect workspace
5. Select the custom rate and create the request
6. Open the expense report of the created distance request
7. Click on distance
8. Invert the order of the waypoints

## Expected Result:
Rate should not change but retain its selected custom rate

## Actual Result:
Mileage rate changes to default rate after editing waypoints

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3cf83ed9-cd81-464c-80a6-ba809ef22ae7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01572c3a6ba1c412f4</li>
        <li>Upwork Job ID: 1782796238303707136</li>
        <li>Last Price Increase: 2024-04-23</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by koko57** [comment]
Looks like something from the New Rate Field PR

cc @mountiny

**Comment by mountiny** [comment]
Assigning, its a new feature, I dont think we have to block deploy on this

**Comment by koko57** [comment]
@neil-marcellini shouldn't it be fixed on the backend? I'm not sending the rate ID for UpdateMoneyRequestDistance, yet I get the default rate ID instead of the previous one in the response
<img width="620" alt="Screenshot 2024-04-23 at 14 43 22" src="https://github.com/Expensify/App/assets/28020445/58d3b1ce-e281-46c2-9708-3d0461a0da6e">

**Comment by arielgreen** [comment]
@kadiealexander removing this from the split project as it's re workspaces (split is only off-workspace)

**Comment by neil-marcellini** [comment]
Wow this issue got kind of buried. Let's see what the status is.

**Comment by neil-marcellini** [comment]
This was fixed a long time ago with this PR, and was marked as passing QA 2 weeks ago in [this comment](https://github.com/Expensify/Web-Expensify/pull/41785#issuecomment-2083900582)
