### ISSUE TITLE
[$250] Android – Attachment – Lage image disappears when zoom it out several times (pinching)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40765]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4504715
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the App
2. Log in.
3. Navigate to any chat
4. Tap on + Add attachment
5. Chose the large image
6. In image preview zoom it and zoom it out several times (pinching)

## Expected Result:
Large image reduced to minimum size

## Actual Result:
Lage image disappears from image preview when zoom it out several times (pinching)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5bdd6b0c-1f6e-481c-98f6-9b899904217f

Long file 
![Bug6457841_1713812568729!long_image](https://github.com/Expensify/App/assets/115492554/173aa4ce-d9b8-4c82-ba1f-f1029836326a)

Logs
[Bug6457841_1713868218673!Profile_trace_for_1.4.64-2.cpuprofile](https://github.com/Expensify/App/files/15075375/Bug6457841_1713868218673.Profile_trace_for_1.4.64-2.cpuprofile)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017025ca6482cb411d</li>
        <li>Upwork Job ID: 1785525329439453184</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by JmillsExpensify** [comment]
Adding this as a LOW for vip-vsb and opening up to the community.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment]
Not reproducible twice so closing this one.
