### ISSUE TITLE
mWeb - Chat - User suggestion list shows full email id in gmail account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40779]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1.Go to https://staging.new.expensify.com/
( login as gmail user)
2. Tap on a report
3. Enter @ and search for an user

## Expected Result:
User suggestion list must not show full email id in gmail account.

## Actual Result:
User suggestion list shows full email id in gmail account.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4a7373c0-a828-4bf9-8a7a-8d1446acb465

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@alexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
This one is on my testing list, I should have an update by EOW.

**Comment by alexpensify** [comment]
No update yet, I've been focused on other GHs.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience
