### ISSUE TITLE
[HOLD for payment 2024-05-06] [$250] [Held requests] 404 when approving an unheld amount on a report after navigating UP from the expense thread

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#40774]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.64-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcochavezf 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1713838305248069?thread_ts=1713799180.851229&cid=C036QM0SLJK

## Action Performed:
1. Add two expenses to an expense report
2. Click into one of the expenses 
3. Hold the expense
4. Click the hyperlink to the parent expense report in the header of the held expense 
5. Approve the unheld amount on the report 
6. Observe the 404 full page blocking screen

## Expected Result:
Remove the reportActionID in the URL when taking the action to approve a partial amount (i.e the unheld total). That way, the user remains on expenseReportID1 where they are and doesn’t run into a 404 because the expense has moved. I.e `</r/expenseReport1ID>`

## Actual Result:
The held request moves to expenseReport2 so the reportActionID is no longer associated with expenseReportID1 making the URL in the address bar invalid leading to the 404. 

Example of what we think is happening with the URL at each stage:

1. Tom adds two expenses to expenseReport1 and navigates to it: `<r/expenseReportID>`
2. Vit clicks into the one expense and has the URL: `<r/transactionThreadReportID>`
3. Vit holds the expense
4. Vit navigates UP to the expense report (using the hyperlink at the top of the expense thread) and has the URL: `</r/expenseReport1ID/reportActionID>`
5. Vit approves the unheld expense total on the expense report
6. The held request moves to expenseReport2 so the reportActionID is no longer associated with expenseReportID1 making the URL in the address bar now invalid: `</r/expenseReport1ID/reportActionID>`

## Workaround:
Yes, remove the reportActionID portion of the URL manually to return to the expense report screen.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/d1f9319b-522a-428e-97bc-560bc9a65bd3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Adding myself and @mountiny for BZ and CME. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0a0e0fdb6586938</li>
        <li>Upwork Job ID: 1782736806998323200</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by mananjadhav** [comment]
Reviewing this now.

**Comment by trjExpensify** [comment]
Thanks, @mananjadhav! We're trying to slip this one into the May 1st release, so getting it through the deploy cycle to production this week is the aim!

**Comment by mananjadhav** [comment]
@gijoe0295's proposal looks promising and I tested it works. I wonder if we should use `goBack` or navigate. But I don't think we should be adding navigation inside `IOU.approveMoneyRequest`.

🎀 👀 🎀 C+ reviewed.

**Comment by trjExpensify** [comment]
Nice! @gijoe0295, please raise the PR today. Thanks!

**Comment by trjExpensify** [comment]
👋 checklist time, @mananjadhav!

**Comment by mananjadhav** [comment]
I couldn't find any offending PR but I do feel we should add regression test for this one.

Here's the regression test proposal.

1. [Employee] Add two expenses to an expense report, put one of them on Hold
2. [Admin] Open that expense report
3. Click the hold expense
4. Click the hyperlink to the parent expense report in the header
5. Approve only the unheld amount on the report
6. Verify not found page does not show
7. [Web] Verify the URL only contains the reportID without reportActionID (i.e. /r/reportID)
8. Verify after a while, the expense report only contains approved transaction
9. [Mobile] Click Back
10. [Mobile] Verify app navigates to the previous screen

**Comment by trjExpensify** [comment]
Yeah, it was likely one of the comment linking PRs. 

Regression test here: https://github.com/Expensify/Expensify/issues/394223

Confirming payments as follows: 

- $250 to @mananjadhav for the C+ review (feel free to request via NewDot)
- $250 to @gijoe0295 for the bug fix (paid)

Closing!

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
