### ISSUE TITLE
IOU - Extra space between user name and "owes" in LHN after the expense is submitted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40787]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Submit a manual expense to a user that only has first name.

## Expected Result:
There will be no extra space between user name and "owes" in LHN after the expense is submitted.

## Actual Result:
There is an extra space between user name and "owes" in LHN after the expense is submitted. After opening transaction thread, the space disappears.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5dff63ae-6656-4487-b9b6-caffbc4d489d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@zanyrenney FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by zanyrenney** [comment]
This feels like extreme polish. I don't think we should be prioritising this right now. Going to close for now!
