### ISSUE TITLE
[HOLD for payment 2024-06-05][$250] Add Fullstory lib

### ISSUE THREAD

**Issue by danieldoglas** [Expensify/App#40784]
[Parent tracking issue](https://github.com/Expensify/Expensify/issues/335526)

Placeholder app issue so we can assign open source contributors/reviewers on Implementing Fullstory
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a2954cbe99d41e6</li>
        <li>Upwork Job ID: 1782752092104155136</li>
        <li>Last Price Increase: 2024-04-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by LCOleksii** [comment]
Support of the Fullstory was implemented by:
- Adding integration of Fullstory React-Native plugin (IOS, Android)
- Adding Fullstory's Annotate React plugin (Mobile, Web)

Separate library activation for Web, Desktop(Hybrid Web) 
should be done by applying related GTM changes:
https://help.fullstory.com/hc/en-us/articles/360020828293-Google-Tag-Manager-GTM

**Comment by danieldoglas** [comment]
Removing help wanted, this was already worked on.

**Comment by mananjadhav** [comment]
As per [this message](https://expensify.slack.com/archives/C02NK2DQWUX/p1713966135996579?thread_ts=1713960904.618239&cid=C02NK2DQWUX), uploading the crash log.  Reverting PRs for this issue fixes [this issue](https://github.com/Expensify/App/issues/40874) (App crash on video upload).

[fullstory-video-crash.txt](https://github.com/Expensify/App/files/15095766/fullstory-video-crash.txt)

**Comment by danieldoglas** [comment]
This PR was reverted - WIP on fixing the issues found.

**Comment by danieldoglas** [comment]
This was reverted @LCOleksii is working in a new branch again!

**Comment by danieldoglas** [comment]
@ishpaul777 assigned you to the new PR today!

**Comment by mallenexpensify** [comment]
PR is actively being worked on (as of 2 hours ago)
- https://github.com/Expensify/App/pull/42046#issuecomment-2123580321

**Comment by mallenexpensify** [comment]
Payment due tomorrow

**Comment by mallenexpensify** [comment]
Thanks @ishpaul777 , def a strange one with their being two parent issues for the PR.  
@LCOleksii are you due payment here?

**Comment by danieldoglas** [comment]
@LCOleksii is not due payment on this one @mallenexpensify !

**Comment by mallenexpensify** [comment]
K, sounds like this can be close then.  Thx all
