### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Pronouns - Default Priority Mode Not Highlighted and marked, Causing Inconsistency

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40789]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a new account and navigate to Account Settings > Preferences > Priority Mode
2. Note that "Most Recent" is the default selection but is not highlighted or marked, leading to inconsistency with other default selections such as Language and Timezone

## Expected Result:
The "Most Recent" default selection should be automatically highlighted and marked, aligning with other default sections like Language and Timezone

## Actual Result:
The default priority mode is not highlighted or marked, causing inconsistency with other sections like Language and Timezone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9fcd1ed0-a30e-4012-bb5c-0dd1d152a485

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e981393fc9a3ead</li>
        <li>Upwork Job ID: 1782798557003403264</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by lanitochka17** [comment]
@puneetlath  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
We don't store anything if the priority mode isn't gsd, so I think it's easier to have the front-end handle the default in this scenario.

**Comment by puneetlath** [comment]
Great, assigned @ZhenjaHorbach.

**Comment by puneetlath** [comment]
@ZhenjaHorbach has been paid. 

@fedirjh bump on the checklist.

**Comment by puneetlath** [comment]
Issue for regression tests: https://github.com/Expensify/Expensify/issues/395853

Everyone has been paid. Thanks y'all!
