### ISSUE TITLE
Android - Avatar - App crashes when user takes photo using camera and saves

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4504463
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap avatar
4. Take a photo using camera and save it

## Expected Result:
App must not crash when user takes photo using camera and save as avatar.

## Actual Result:
App crashes when user takes photo using camera and save as avatar.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d6155584-f581-42ad-9439-fb38e60fe99c

**Crash logs**

[crash logges.docx](https://github.com/Expensify/App/files/15076847/crash.logges.docx)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@MitchExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MitchExpensify** [comment]
I am reassigning as I'm about to go OOO tomorrow and don't have access to a Android device in the interim. My usual virtual device won't work to reproduce this

**Comment by MitchExpensify** [comment]
Keeping myself assigned to take back up when I return on the 7th 🚀

**Comment by abekkala** [comment]
I'm not able to test Android either - I'll have to look at this again later today.

**Comment by abekkala** [comment]
applying the retest lable

**Comment by MitchExpensify** [comment]
Not overdue, waiting on retest

**Comment by abekkala** [comment]
retesting this - not overdue

**Comment by MitchExpensify** [comment]
Back from OOO, I can snag this back. Thanks @abekkala !

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment]
Adding an avatar without crashing the app is needed for all waves but I have to choose 1. Adding to wave collect without status to see if @mvtglobally is able to reproduce or not. We'll close or a assign a status if reproducible 👁️

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)
