### ISSUE TITLE
[HOLD for payment 2024-05-06] [Wave Collect][QBO] Add the explanatory text on the Tags Screen with Hyperlink when the accounting software is connected

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#40798]
Add the explanatory test on the Tags page to describe that the tags are imported from QBO when an acccounting connection exists.

<img width="400" alt="Screenshot 2024-04-23 at 9 44 45 AM" src="https://github.com/Expensify/App/assets/98560306/a74aa8c3-9e6b-4ce2-967a-1b198a92b2c4">
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018de6a9c10cc926ed</li>
        <li>Upwork Job ID: 1788781434745339904</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Are we done here? Can [#40811](https://github.com/Expensify/App/pull/40811) be closed?

**Comment by s77rt** [comment]
Can you assign me here?

**Comment by sakluger** [comment]
I'm OOO today and Monday so I'll handle on Tuesday if necessary.

**Comment by hayata-suenaga** [comment]
ah nice so we gonna combine `[NO QA] Fix withPolicyConnections` and this issue.

will that be $250, @s77rt?

**Comment by s77rt** [comment]
@hayata-suenaga Yes Thanks!

**Comment by sakluger** [comment]
@s77rt sorry for the delay. I sent you an offer here: https://www.upwork.com/nx/wm/offer/102246727

**Comment by s77rt** [comment]
@sakluger Accepted! Thanks!

**Comment by sakluger** [comment]
Thanks! All paid now.
