### ISSUE TITLE
[Hold on #40708] Web - Composer - Navigating to an invalid merchant edit URL makes composer active while RHP is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40795]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39413
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create an expense request
3. Open the expense report
4. Click on Merchant to open the merchant edit RHP
5. Change the URL to an invalid one by replacing the ID to text and navigate to it (e.g https://staging.new.expensify.com/edit/submit/merchant/INVALID_TEXT/3276255813405397)
6. Press any key on the keyboard

## Expected Result:
Compose box should not be active while not found RHP is open

## Actual Result:
Compose box is active and user can type anything while not found RHP is open

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/90a29da9-0e72-49d4-a04d-a75e1e2ca0fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment]
@laurenreidexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
Should be fixed in this [PR](https://github.com/Expensify/App/pull/40708). It's a live markdown issue where the auto focus doesn't work even when we set it to `false`.

**Comment by laurenreidexpensify** [comment]
https://github.com/Expensify/App/pull/40708 is on staging, so adding to weekly KI resting

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
