### ISSUE TITLE
[HOLD for payment 2024-05-03] [Wave Collect][QBO] Update Export Pages for Company Cards to include amendments

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#40792]
[As part of QBO](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit#heading=h.dp3j73pj1980), related to this PR: https://github.com/Expensify/App/pull/40713

Please amend the pages for

### Export Company Cards: Debit Card

![image](https://github.com/Expensify/App/assets/56830058/9f811c6c-94ff-4da4-953f-b0d856166bb2)

**Notes for completeness:**

- Add a new page for `Export Company Card expenses as` which is navigated to by clicking the `Export Company Cards as’ form menu item on the Export page. 
- Show the subtext for the page ”Set how company card purchases export to QuickBooks Online.”
- Add a form menu item for `Export as` with the right caret which opens to a new page Titled `Export as`.
- Display the selected export method in the `Export as` Form Menu item.
- On the `Export as` page, show the export methods in the select list pattern, with the selected export method row highlighted with a green checkmark. The options are:
   - Credit card
   - Debit card
   - Vendor bill
- When Debit card is selected display the subtext on the `Export Company Card expenses as` page: 
    - “We'll automatically match the merchant name on the debit card transaction to any corresponding vendors in QuickBooks. If no vendors exist, we'll create a "Debit Card Misc." vendor for association.”
- Add an additional `Account` menu item to choose an applicable account from QBO. The default selected is the first alphabetically in the list of available accounts imported. 
- Create a new page for `Account` which is clicked to through the form menu item on the `Export company cards` page.
- Display the subtext “Debit card transactions will export to the bank account below.””
- Display the available accounts in the select list pattern, with the selected account row highlighted with a green checkmark.

### Export Company Cards: Credit Card

![image](https://github.com/Expensify/App/assets/56830058/aa247d88-2432-4710-a2a2-bb28deb337e7)

- The default export method for company card expenses upon initializing a connection to QBO is `Credit Card`
- When Credit card is selected display the subtext: 
   - “We'll automatically match the merchant name on the credit card transaction to any corresponding vendors in QuickBooks. If no vendors exist, we'll create a "Credit Card Misc." vendor for association..”
- Display the selected Account in the form menu item. The default selected is the first alphabetically in the list of available accounts imported.
- Create a new page for `Credit card account` which is clicked to through the form menu item on the `Export company cards` page and show the available accounts in a select list.

### Export Company Cards: Vendor Bill

![image](https://github.com/Expensify/App/assets/56830058/4eb5d4dd-f277-4490-9306-f3a4b6e80f97)

- When Vendor bill is selected display the subtext: 
   - “We'll create a single itemized vendor bill for each Expensify report, carrying the date of the last expense on the report. If this period is closed, we'll post to the 1st of the next open period. You can add the vendor bill to your A/P account of choice (below).”
- Display the available Accounts payable accounts from the QBO integration. The default selected is the default AP account set in QBO.
- Display the subtext “Set a default vendor that will apply to all credit card transactions upon export.” with a toggle for enabled/disabled (disabled by default).
- Under the toggle, display a `Vendor` push row with the selected vendor account as the value. The first vendor account in QBO alphabetically is selected by default when enabled. 
- Create a new page for `Accounts payable` which is clicked to through the form menu item on the `Export company cards` page.
- Display the subtext “This is your chosen credit card account”
- Display the accounts in the select list pattern, with the selected account row highlighted with a green checkmark.
- Create a new page for “Vendor”
- Add the subtext “Select the vendor applied to all credit card transactions.”

**Comment by narefyev91** [comment]
I will pick this up, can you please assign me

**Comment by hayata-suenaga** [comment]
> Skipping the payment summary for this issue since all the assignees are employees or vendors. If this is incorrect, please manually add the payment summary [SO](https://stackoverflowteams.com/c/expensify/questions/17778).

Tom, @s77rt did a C+ review for [this PR](https://github.com/Expensify/App/pull/40902) associated with this issue.

**Comment by trjExpensify** [comment]
Confirming payment summary as follows: 

- $250 to @s77rt for the C+ review

Offer sent!

**Comment by s77rt** [comment]
@trjExpensify Accepted! Can you please make this $125 as I didn't review the full PR (PR got merged before I make another review)

**Comment by trjExpensify** [comment]
Done!
