### ISSUE TITLE
#Rooms - #announce room with messages shows skeleton loading after workspace is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40802]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4503512
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisites:
Create workspace and send at least 3 messages in the #announce room

1. Open New Expensify app
2. Login to the HT account
3. Navigate to the #announce room
4. Disable the internet connection in the main testing device
5. Edit the first message
6. Delete the second message
7. Send the image to the room
8. In the secondary device, navigate to the workspace and delete it

## Expected Result:
After deleting the #announce room and going online, an error message should appear under the deleted, edited messages, and the message ""This chat room has been deleted"" should appear at the end of the room

## Actual Result:
#announce room with messages shows skeleton loading after workspace is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/32c9ae22-6cc0-4317-9433-5eef3abe0614

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
@lanitochka17 I'm a little confused by this bug.

So the issue you're seeing is this skeleton?

![image](https://github.com/Expensify/App/assets/30815269/4ec453e5-b7b3-41f0-addf-02fa673e706d)

When it should be this?

![image](https://github.com/Expensify/App/assets/30815269/7d4d6427-0c7f-4d24-89f1-ad412cadadda)

If so, I think that's just the nature of New.Expensify - there's a delay.

>an error message should appear under the deleted, edited messages, and the message ""This chat room has been deleted""

Can you share a screenshot of how this should look? I had a look at a deleted room and I'm not seeing this.

**Comment by jliexpensify** [comment]
Ok, I think this is just a general delay in New.Dot. I see the skeleton when I initially open the app, it hangs for a second or two. Going to close this as I don't think it's an actual bug.
