### ISSUE TITLE
[Wave Collect] New Resources to Publish - Free > Collect migration

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#40808]
Publish Date: May 1st 2024
Tracking GH: https://github.com/Expensify/Expensify/issues/386666
Draft: https://docs.google.com/document/d/1eobOg2Cva1SNJwZesn6FWNFJDSF-wHED0xgkasYR0rg/edit#heading=h.9ua5yvwzrmcv

cc @ren-jones

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by joekaufmanexpensify** [comment]
Pending review

**Comment by joekaufmanexpensify** [comment]
Draft in review.

**Comment by joekaufmanexpensify** [comment]
Ren rewrote the article, and I just left one suggestion. Otherwise good to proceed with PR!

**Comment by joekaufmanexpensify** [comment]
And then [the latest](https://expensify.slack.com/archives/C02QSAC6BJ8/p1713447784062889?thread_ts=1713270523.619509&cid=C02QSAC6BJ8) was that this article should be published under `Getting started` in the nav structure.

**Comment by joekaufmanexpensify** [comment]
Looks like copy is finalized, and next step is PR!

**Comment by joekaufmanexpensify** [comment]
PR in review.

**Comment by joekaufmanexpensify** [comment]
All set. TY!
