### ISSUE TITLE
[HOLD for payment 2024-06-24] New tax rate empty state has incorrect label sizes

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#40813]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Navigate to `Workspace > Taxes > Add rate`
2. Verify that the input labels have incorrect font size of 13px

## Expected Result:
Input labels should have font size of 15px

## Actual Result:
Input labels should have font size of 13px

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![IMG_9563](https://github.com/Expensify/App/assets/22219519/e1562a33-895f-4655-a255-05ad3f22924c)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165be538517a8973a</li>
        <li>Upwork Job ID: 1782835092067209216</li>
        <li>Last Price Increase: 2024-04-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by MahmudjonToraqulov** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
New tax rate empty state has incorrect label sizes

### What is the root cause of that problem?
We should change font-size [here](https://github.com/Expensify/App/blob/f6e4b2c8587365f6a61aa700e310b51c714f2f51/src/styles/variables.ts#L55)

### What changes do you think we should make in order to solve the problem? 
We should change font-size [here](https://github.com/Expensify/App/blob/f6e4b2c8587365f6a61aa700e310b51c714f2f51/src/styles/variables.ts#L55)


### What alternative solutions did you explore? (Optional)
N/A


### Result

**Comment by luacmartins** [comment]
Thanks for the proposal @MahmudjonToraqulov, but we're handling this issue internally!

**Comment by MahmudjonToraqulov** [comment]
Ok, sorry.

**Comment by luacmartins** [comment]
@shawnborton did you get a chance to look into this one?

**Comment by shawnborton** [comment]
Not yet!

**Comment by shawnborton** [comment]
Not overdue, hoping to look at it this week!

**Comment by luacmartins** [comment]
Shawn will be working on this one!

**Comment by shawnborton** [comment]
Sorry! Still on my plate, just haven't looked into it yet

**Comment by shawnborton** [comment]
Still on my plate

**Comment by shawnborton** [comment]
@luacmartins I think I'm going to need some help with this one! 

It looks like we have a component called `MenuItemWithTopDescription` which seems to have the correct label behavior. But for tax rates, it's using `InputWrapper` which has some different styles. Anyways, let's plan to look at this during our next mentor sync.

**Comment by luacmartins** [comment]
@shawnborton you're close! If you look into `InputWrapper`, we pass an `InputComponent` prop to it, which is ultimately the input component we render. For the `Name` field, we are passing [TextPicker](https://github.com/Expensify/App/blob/19f81b5c9f4db131bf9e9d08c62e3f535a376c09/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L88). Perhaps we can take a look at the styles [TextPicker](https://github.com/Expensify/App/blob/19f81b5c9f4db131bf9e9d08c62e3f535a376c09/src/components/TextPicker/index.tsx#L12) is using?

**Comment by shawnborton** [comment]
Not overdue, still on my plate :)

**Comment by shawnborton** [comment]
No update

**Comment by shawnborton** [comment]
Maybe today is the day

**Comment by shawnborton** [comment]
Not overdue, still on my plate

**Comment by shawnborton** [comment]
PR here: https://github.com/Expensify/App/pull/43595

**Comment by shawnborton** [comment]
Not overdue, holding for payment

**Comment by luacmartins** [comment]
Not sure why we have two payment dates but this PR was deployed to prod on the 17th, so that makes the payment due date the 24th. @johncschuster could you assist>

**Comment by johncschuster** [comment]
# Payment Summary:
Contributor+: @rushatgabhane - $250 paid via Manual Requests

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
