### ISSUE TITLE
[$250] [Held requests] Held expenses don’t appropriately show the “dot separator” pattern

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713889734677819

## Action Performed:
1. Go to any report with submitted expenses
2. Click on an individual expense
3. In the three dot overflow menu (top right), choose Hold request
## Expected Result: 
The expense preview should show Cash * Hold
## Actual Result: 
The expense preview shows only Cash

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/eeb1e235-3128-4b77-b687-da1ff2b79e3e

![CleanShot 2024-04-23 at 10 34 24@2x](https://github.com/Expensify/App/assets/38435837/439cdcfb-4d5c-4e72-a7e2-446038a9f5d7)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a7a1fb593ebaad4</li>
        <li>Upwork Job ID: 1783180217881948160</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by imadarif** [comment]
didn't understand the actual problem.

**Comment by abekkala** [comment]
Looks like this one will require a backend fix

**Comment by trjExpensify** [comment]
👋 @abekkala tag it with `Hot picks` in the status of the project to get it into that section more quickly. :)

**Comment by marcochavezf** [comment]
Trying to reproduce this one, but I'm getting the message `Review required` instead:

<img width="875" alt="Screenshot 2024-05-03 at 8 07 47 p m" src="https://github.com/Expensify/App/assets/6829422/ec5a9d0e-77c0-495f-9217-f06942f6b562">

**Comment by trjExpensify** [comment]
Yeah, @marcochavezf you need to not have violations. :)

**Comment by abekkala** [comment]
@marcochavezf is this one that you're taking on or are we still needing someone to pick it up?

**Comment by abekkala** [comment]
@marcochavezf looks like this one is not reproducible during the retest, this week

**Comment by JmillsExpensify** [comment]
I'm pretty sure this has been fixed. I'm not able to reproduce this one anymore, so I'll go ahead and close.
