### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] Create automated tests for Workspace Profile, Members and Categories pages

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#40835]
# Problem
New API commands introduced as part of the Simplified Collect project don't have automated tests, which can lead to bugs and unexpected behavior when these commands are updated.

# Solution
Add automated tests for the commands below:

- [ ] Test UpdateWorkspaceDescription
- [ ] Test AcceptJoinRequest
- [ ] Test UpdateWorkspaceMembersRole
- [ ] Test RequestWorkspaceOwnerChange
- [ ] Test AddBillingCardAndRequestPolicyOwnerChange
- [ ] Test SetWorkspaceRequiresCategory
- [ ] Test CreateWorkspaceCategories
- [ ] Test RenameWorkspaceCategory
- [ ] Test SetWorkspaceCategoriesEnabled
- [ ] Test DeleteWorkspaceCategories

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011452b1c44ee7036a</li>
        <li>Upwork Job ID: 1782893496746893312</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by luacmartins** [comment]
I think @tienifr's proposal looks good. Gonna assign them to this issue.

**Comment by mallenexpensify** [comment]
Thanks @hoangzinh , seems like, with the deploy freezer, we're going to have a LOT of issue come due for payment at/around the same time

**Comment by mallenexpensify** [comment]
Contributor: @tienifr  paid $250 via Upwork
Contributor+: @hoangzinh paid $250 via Upwork.  
 
I don't think we need a regression test here. @luacmartins , comment and reopen if you disagree.

**Comment by luacmartins** [comment]
No requession test needed
