### ISSUE TITLE
[HOLD for payment 2024-05-20] [$250] Create automated tests for Workspace Taxes page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#40837]
# Problem
New API commands introduced as part of the Simplified Collect project don't have automated tests, which can lead to bugs and unexpected behavior when these commands are updated.

# Solution
Add automated tests for the commands below:

- [ ] Test OpenPolicyTaxesPage
- [ ] Test SetPolicyCustomTaxName
- [ ] Test SetPolicyCurrencyDefaultTax
- [ ] Test SetPolicyForeignCurrencyDefaultTax
- [ ] Test CreatePolicyTax
- [ ] Test SetPolicyTaxesEnabled
- [ ] Test RenamePolicyTax
- [ ] Test UpdatePolicyTaxValue
- [ ] Test DeletePolicyTaxes
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aabb7c33e3cc9759</li>
        <li>Upwork Job ID: 1783143315135184896</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by zanyrenney** [comment]
@dukenv0307 please complete the steps above, feel free to DM me when that is complete for the payout/ close out of th issue.

**Comment by zanyrenney** [comment]
@dukenv0307 @tienifr i have invited you to the job

**Comment by zanyrenney** [comment]
resent @dukenv0307 please can you check again!

**Comment by zanyrenney** [comment]
bump @dukenv0307

**Comment by zanyrenney** [comment]
![2024-05-23_17-29-02](https://github.com/Expensify/App/assets/56830058/bd0a82dd-5975-4a48-88df-0da2de8f6a2a)

**Comment by zanyrenney** [comment]
**payment summary**

paid @dukenv0307 $250 via upwork
paid @tienifr $250 via upwork.

**Comment by zanyrenney** [comment]
Hey @tienifr we can do this moving forward but as you've already been paid for this one via Upwork, we'll need to keep that as the payment method here to avoid additional work / audit in refunding and reissuing payments. thanks for your understanding!

**Comment by zanyrenney** [comment]
I paid you via upwork instead! @tienifr feel free to DM me any issues.
