### ISSUE TITLE
Held expenses show a permanently highlighted row

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40830]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713889780388119

## Action Performed:
1. Go to any report with submitted expenses
2. Click on an individual expense
3. In the three dot overflow menu (top right), choose Hold request

## Expected Result:
The expense preview row is permanently highlighted
## Actual Result:
The expense preview row shouldn’t be highlighted at all
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-04-23 at 10 22 50@2x](https://github.com/Expensify/App/assets/38435837/e4348d7c-f2ca-4f25-976b-b3c248025f84)

https://github.com/Expensify/App/assets/38435837/99184e70-7f2b-4e35-bf63-bc3aaa66b2b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
Thanks @gijoe0295 , Yes - I agree with you!
