### ISSUE TITLE
[$250] Chat - Room highlight is preserved for non existing room after an edit

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40857]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a room
3. Open the room report
4. Type "#" followed by something random (e.g "#Random") and send the message
5. Observe the highlight disappears after a few seconds
6. Right click on the message sent on step 4 and click on edit comment
7. Append some additional characters to the message without a whitespace in between (e.g "#RandomThings") and click on the tick mark

## Expected Result:
The highlight should disappear after a few seconds

## Actual Result:
The highlight is retained on the comment after editing the non existent room mention

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c8d43b27-49f5-4827-9727-abc781b7929c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5afa01739ea945f</li>
        <li>Upwork Job ID: 1785431677040029696</li>
        <li>Last Price Increase: 2024-06-04</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by johncschuster** [comment]
It looks like "rooms" are related to #vip-vsb. Parking this in that project.

**Comment by johncschuster** [comment]
I note @gijoe0295 believes this is a `BackEnd` issue 👍

**Comment by johncschuster** [comment]
Thanks for that suggestion @rayane-djouah!

**Comment by johncschuster** [comment]
Ok, I'm unsure the priority of this issue in the grander scheme (and thus, how aggressive I should be to get a volunteer). Raising the question [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1715720430820059)

**Comment by johncschuster** [comment]
Looks like this should be resolved [here](https://github.com/Expensify/App/issues/39549)

**Comment by johncschuster** [comment]
Bumping for Melvin (I will check in on the linked issue each day)

**Comment by johncschuster** [comment]
Looks like the PR for the linked issue has been merged. Now we just need to wait for it to be deployed.

**Comment by johncschuster** [comment]
I think we're still waiting on the deploy. I will check again tomorrow.

**Comment by johncschuster** [comment]
Looks like the PR above has been deployed to Auth.

**Comment by johncschuster** [comment]
@izarutskaya I believe this issue should now be resolved now that [this PR](https://github.com/Expensify/Auth/pull/10902) has been deployed. Can you please re-test the behavior to see if it persists?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment]
Great! Let's retest one more week. If it's no longer reproducible, let's close the issue.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
