### ISSUE TITLE
Chat - Unable to dismiss comment edit with ESC key

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Send a message.
4. Right click on the message > Edit comment.
5. Hit ESC key.

## Expected Result:
Comment edit will be dismissed.

## Actual Result:
Unable to dismiss comment edit with ESC key.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/da422b7f-0196-4547-ac13-3f84852dd843

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@twisterdotcom I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/895e395b-225d-42e4-a601-95862caac9bb

**Comment by mountiny** [comment]
@dukenv0307 Might be related to this https://github.com/Expensify/App/pull/35226 PR

**Comment by twisterdotcom** [comment]
Easily recreatable. Will wait for @dukenv0307 to chime in before we slap External on this.

**Comment by mountiny** [comment]
I can repro on main

**Comment by mountiny** [comment]
Confirmed the revert fixed this issue https://github.com/Expensify/App/pull/40865 I prefer to proceed with the re vert as it seems like that PR has been linked to couple other blockers

**Comment by mountiny** [comment]
@dukenv0307 I can see there is multiple regressions linked, in order to move deploy forwards, I prefer revert and you can add these fixes and test it thoroughly in second try. Its not a critical feature we need out in release 1

**Comment by mountiny** [comment]
revert PR being CPed, closing as we will validate the PR
