### ISSUE TITLE
[HOLD for payment 2024-05-03] [HOLD for payment 2024-05-02] [$250]  Android - Chat - Mention suggestion gets behind other UI components while in edit mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open new expensify app
2. Open a report
3. Send a message
4. Edit the message
5. Type "@" to open the suggestion pop up

## Expected Result:
The suggestion pop up should be on top of other UI components in the report page

## Actual Result:
The suggestion pop up gets behind other UI components from the report page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f67dc02c-80fe-4bf3-8d90-9280326ce74b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c924587ad4f6a8f</li>
        <li>Upwork Job ID: 1783066631827873792</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/c9aa74db-d434-40c3-a6ee-e2c7500d9d75

**Comment by Julesssss** [comment]
[This issue](https://github.com/Expensify/App/pull/35226) sounds like a possible cause.

**Comment by izarutskaya** [comment]
Suggestion list cannot be selected in iOS, but is not hidden behind content like Android.
Check please this video. Thanks

https://github.com/Expensify/App/assets/115492554/767d1749-ecfd-4afa-a8a3-670c39ddbdd2

**Comment by mountiny** [comment]
I am reverting the PR which most likely contributed to this bug https://github.com/Expensify/App/pull/40865 @dukenv0307 please note this issue so you can test for it in v2. thanks

**Comment by mountiny** [comment]
Lets retest this after the CP of the revert is done and if this is not repro anymore on 65-2 lets assign @dukenv0307 so they can handle it in the next PR

**Comment by isabelastisser** [comment]
Bump @abdulrahuman5196 to complete the BZ list. Thanks!

**Comment by abdulrahuman5196** [comment]
@isabelastisser I think we can close this issue. No payment required here. Seems this was a regression issue and the original PR was reverted.

**Comment by isabelastisser** [comment]
Thanks for the update, @abdulrahuman5196! Closing.
