### ISSUE TITLE
Track Expense - Amount is not shown when going through QAB track flow

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40863]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR:** https://github.com/Expensify/App/pull/40574
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB > Track expense > Enter an amount and create the expense
3. Click on FAB > Click on Track expense QAB
4. Enter an amount

## Expected Result:
The green confirmation button should show the amount, it should show us "Track <Amount>"

## Actual Result:
The amount is not reflected on the green confirmation button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/874ba4cb-df71-4e25-abe7-2c4a36a92d95

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Prod has another behavior

![image (11)](https://github.com/Expensify/App/assets/115492554/cbd9c633-69f3-4ba4-bb86-9e91470e06a8)

**Comment by mountiny** [comment]
This is not a blocker as its a new feature and its not blocking user from using the app.

@Gonals assigning you to handle this one

**Comment by Gonals** [comment]
Huh. Weird. This ws working correctly before. Taking a look

**Comment by Gonals** [comment]
I don't think this is a bug. In the normal track flow, the button also states "Track Expense", so this mimics that behavior. Closing.
