### ISSUE TITLE
iOS - Chat - Suggestion list in edit composer is easily dismissed when scrolling down the list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40866]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR ** https://github.com/Expensify/App/pull/35226
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to chat.
3. Send a message.
4. Right click on the message > Reply in thread.
5. Right click on the parent message in thread > Edit comment.
6. Type @.
7. Scroll down the suggestion list slowly, while keeping the finger within the list.

## Expected Result:
The list will not dismiss when scrolling down the list.

## Actual Result:
Suggestion list is easily dismissed when scrolling down the list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f597764c-d6fc-4069-a007-76df2ee4089a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by mountiny** [comment]
Seems like expected behaviour
