### ISSUE TITLE
Chat - User mention is not highlighted as mention when mentioning someone in edited comment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Send a message.
4. Right click on the message > Edit comment.
6. Type @.
7. Select a user from the suggestion list.
8. Save the edit.

## Expected Result:
The user mention in the edited message will be highlighted as mention.

## Actual Result:
The user mention in the edited message is not highlighted as mention.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/65ba9e54-2158-4f57-90ea-f5708aa63bd8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@adelekennedy I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 
![image (10)](https://github.com/Expensify/App/assets/115492554/5eefea24-6958-4f20-9696-2d53722cdb01)

**Comment by mountiny** [comment]
This is technically not in production so its not a blocker but I agree this should be addressed in the PR

**Comment by mountiny** [comment]
We are going to revert this PR https://github.com/Expensify/App/pull/35226 and @dukenv0307 can you please work on implementing this in there too as I think it should be part of the initial implementation (it looks weird when you choose the mention and its not saved that way)

**Comment by mountiny** [comment]
I see the new Pr links this issue so I think we can close it for now
