### ISSUE TITLE
Chat – Chat scrolled down when go back from the thread with deleted task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40869]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4506315
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to any 1:1 chat
4. Tap on + and create a task
5. Open task details and send a comment
6. Delete task
7. Open thread again and go back via header link

## Expected Result:
Thread with deleted task is visible in the bottom of the chat

## Actual Result:
Chat scrolled down when go back from the thread and thread with deleted task (last message in the chat) is not visible.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/82db46ee-33d7-4809-bd5a-e4edd0040f2e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by QichenZhu** [comment]
This might be related to #40085 and #40206.

**Comment by strepanier03** [comment]
Hmm, struggling with reproduction of this. 

@izarutskaya can you confirm that after you go back and the delete task thread is no longer visible, is it truly gone or is the page scrolled back up and if you scroll down it's still actually there??

**Comment by strepanier03** [comment]
Closing this until we have reproduction.
