### ISSUE TITLE
Chat - Suggestion list does not appear below composer when it is near chat header

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/35226
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the App
2. Go to chat.
3. Send a long list of messages.
4. Right click on the message near the chat header > Edit comment.
5. Type @.

## Expected Result:
The mention suggestion list will appear under the edit compoer (mweb behavior).

## Actual Result:
The mention suggestion list appears above the edit compoer which now appears behind the header.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d9309dd4-1ba0-4645-a3a1-fd9dd82dcaff

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 

![Screenshot_2024-04-24-13-47-14-41_4f9154176b47c00da84e32064abf1c48](https://github.com/Expensify/App/assets/115492554/f4e58e73-7bba-4af4-b14a-93ea7276923d)

**Comment by mountiny** [comment]
@dukenv0307 @eVoloshchak @stitesExpensify can you please check this out

**Comment by mountiny** [comment]
Since there was couple other things raised for this PR, in order to have smooth deploys ahead of Release 1 period, I will revert, please add this to the scope of you version2 PR

**Comment by mountiny** [comment]
Adding @dukenv0307 so we dont forget to fix this in the new PR

**Comment by Beamanator** [comment]
So if I'm clear here, we're planning to kinda "not do anything" with this issue, but @dukenv0307 is working on fixing this bug in https://github.com/Expensify/App/pull/41071?

**Comment by joekaufmanexpensify** [comment]
Sounds good! This one is listed as a fixed issue in the PR, and I [commented](https://github.com/Expensify/App/issues/34442) on the other issue just now.

**Comment by joekaufmanexpensify** [comment]
Closing since this is being tracked elsewhere!
