### ISSUE TITLE
[HOLD for payment 2024-05-03] [HOLD for payment 2024-05-02] [$250] iOS - App crashes when trying to upload a video

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#40874]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Not sure yet
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Go to chat
2. Try to upload video as attachment

## Expected Result:
Describe what you think should've happened

The video is uploaded and the app does not crash

## Actual Result:
Describe what actually happened

The app crashed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/36083550/83644456-9e03-4003-9617-b55618895ba8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010901c1d6fd07774a</li>
        <li>Upwork Job ID: 1783184024436666368</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by mountiny** [comment]
$250 to @mananjadhav for help

**Comment by dylanexpensify** [comment]
payment upcoming!

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
Same

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @mananjadhav $250

Please apply/request!
