### ISSUE TITLE
[$250] Track expense - Distance is not editable after expense tracking is created

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40879]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39956
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Self DM.
3. Track a distance expense.
4. Go to expense thread.

## Expected Result:
Distance should be editable.

## Actual Result:
Distance is not editable.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/aa26212c-bf34-424c-ba7c-3dc196169967

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa26b2aab67f7bd8</li>
        <li>Upwork Job ID: 1784826184446623744</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@kadiealexander FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Santhosh-Sellavel** [comment]
@kadiealexander Please reassign a new C+ Here. Unassigning due to low availability.

**Comment by Santhosh-Sellavel** [comment]
@allroundexperts Will take over this as C+!

**Comment by kadiealexander** [comment]
@allroundexperts could you please review the existing proposals? Thanks!

**Comment by neil-marcellini** [comment]
This is intentional and will be fixed by this PR, and handled by the related issue [[App] [HOLD Web-E 41549] Allow editing distance for tracked expenses](https://github.com/Expensify/App/pull/41633)
