### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] [Guided Setup] Redirect where user was when they try to deeplink to the onboarding flow after completion

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40876]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/App/pull/40667

## Action Performed:
1. Open expensify staging app
2. Open any chat
3. Send this url https://staging.new.expensify.com/onboarding
4. Tap on the sent URL to start the onboarding flow
5. Tap on any one of the purpose options more than one time

## Expected Result:

When the user already completed the  guided setup flow, we should make sure we re-navigate them to the main page after they attempt to deeplink to the flow

## Actual Result:
Users can go through the onboarding flow as many times as they want

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5538576a-840c-4367-8c8d-ee14a5f55f0b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5d3f767fe2611e7</li>
        <li>Upwork Job ID: 1783996337884426240</li>
        <li>Last Price Increase: 2024-04-26</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
Taking over

**Comment by trjExpensify** [comment]
>I think we discussed before if we should even allow the deeplink once user completed the flow @trjExpensify

I don't recall that, but it kinda' makes sense. If they've completed onboarding and in-product natively we don't show it again -- then getting there via deeplink shouldn't work either.

**Comment by mountiny** [comment]
Updated the instructions

**Comment by skyweb331** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Do not allow user repeat the onboarding steps when already completed the onboarding steps

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?
Backend sends `{nvp_onboarding:  {hasCompletedGuidedSetupFlow: true}` and using this value, Two solutions.
1. Remove the Onboarding Route in `AuthScreens.tsx`, thus user will remain on the current report if he/she clicks the onboarding link, or will go to the last report if he/she comes from outside via direct link
2. On OnboardingModalNavigator, redirects the user to `Concierge` page, thus user will be redirected to his/her `Concierge` page if he/she clicks the link.

### What alternative solutions did you explore? (Optional)
n/a

**Comment by c3024** [comment]
Checking. Will update in a while.

**Comment by skyweb331** [comment]
I am testing the code on Android and IOS.

**Comment by skyweb331** [comment]
@c3024 I failed android installation, so I could not submit the PR. I tested my code on all environments except Android.
I tried android on both Mac and Linux, but stopped at the last step.
![image](https://github.com/Expensify/App/assets/25519849/81b4dbb0-7411-4e1e-87e2-42710e1e8abe)

**Comment by c3024** [comment]
Bump @youssef-lr. This is waiting for assignment. Thanks.

**Comment by mountiny** [comment]
I am going to ai am back from ooo (thats why Youssef got assigned) so taking this over again, thank you!

**Comment by mountiny** [comment]
@skyweb331 can you raise the pr please even without the android videos, add the rest please

**Comment by skyweb331** [comment]
@mountiny OK. I will upload my PR soon.

**Comment by skyweb331** [comment]
@mountiny PR is submitted.

**Comment by trjExpensify** [comment]
Looks like we're ready for a re-review here, @c3024. Thanks!

**Comment by joekaufmanexpensify** [comment]
We need to pay: 

- @skyweb331 $250 for PR via Upwork. 
- @c3024 $250 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment]
@skyweb331 please share your upwork profile here so we can hire you

**Comment by joekaufmanexpensify** [comment]
@c3024 $250 sent and contract ended!

**Comment by skyweb331** [comment]
@joekaufmanexpensify My profile link is https://www.upwork.com/freelancers/~019e5171478d2a22f7

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by joekaufmanexpensify** [comment]
OG upwork job closed, so opened a new one: https://www.upwork.com/jobs/~013da32781154e6433

**Comment by joekaufmanexpensify** [comment]
@skyweb331 offer sent for $250!

**Comment by skyweb331** [comment]
@joekaufmanexpensify Thank you. Just accepted it.

**Comment by joekaufmanexpensify** [comment]
@skyweb331 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
