### ISSUE TITLE
mWeb - Onboarding - App doesn't navigate user to Concierge after finishing the flow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/40667
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new account
3. Navigate to this https://staging.new.expensify.com/onboarding
4. Finish the onboarding flow

## Expected Result:
App navigates to Concierge chat after user finishes the onboarding flow (Same as the behavior on Web)

## Actual Result:
App navigates to LHN which is different from the behavior on web

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/85f220ae-30f4-4ecb-95b3-a8fdf5037828

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment]
@miljakljajic FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by miljakljajic** [comment]
Just confirming the expected behaviour

**Comment by miljakljajic** [comment]
@anmurali - just checking this the behaviour we'd expect, going back to Concierge at the end of the onboarding flow?

**Comment by miljakljajic** [comment]
This is expected behaviour - landing in the LHN. Closing!
