### ISSUE TITLE
Room - Scrolling the conversation history doesn't closes the room suggestion list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a room with long conversation history
3. Enter #
4. Note available rooms suggestion list opened
5. When room suggestion list is opened, scroll the conversation history

## Expected Result:
When room suggestion list is opened, scrolling the conversation history must close the room suggestion list

## Actual Result:
When room suggestion list is opened, scrolling the conversation history doesn't closes the room suggestion list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/239bb7c7-cfc6-42f7-9ed6-9e9e5eb679f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by trjExpensify** [comment]
That's the same behaviour on iOS and web/desktop when there's a # in the composer. It's also the same behaviour as the @ mentions auto-complete menu as well. I don't think we intend to close the auto-complete menu here when you have the "trigger" in the composer. 

Happy for a second opinion from @puneetlath as this is mentions v2 related. If he agrees this is expected @lanitochka17, can you update whatever test case suggested it should close? Thanks!

**Comment by puneetlath** [comment]
Agreed, doesn't seem like a bug to me.

**Comment by trjExpensify** [comment]
Cool, thanks for confirming!
