### ISSUE TITLE
IOU - User can bypass to confirmation page of a split between member and WS by deeplinking

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40895]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Click on FAB > Split bill
4. Enter an amount and click Next
5. Select a single user and click Next
6. Copy the URL of the current page
7. Go back to member selection page
8. Click on a workspace to include it in the split
9. Navigate to the URL copied on step 6

## Expected Result:
App does not navigate user to the split confirmation page of workspace and member

## Actual Result:
App navigates user to the confirmation page of the split of the workspace with a member

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/91562d3d-34bb-43d2-9822-72307bc87336

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment]
@slafortune FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by slafortune** [comment]
I really think that this isn't an action that will actually be taken by customers.
