### ISSUE TITLE
[$250] Members - Deleted members in offline mode return after re-logging

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40898]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/40758
## Action Performed:
Prerequisites:
Create workspace, create a room with 3 members, create a group conversation with 3 members
1. Open https://staging.new.expensify.com/
2. Login to the HT account
3. Navigate to the created group
4. Click on the header > Members
5. Go offline
6. Delete any member
7. Navigate to the created room
8. Click on the header > Members
9. Delete any member
10. Refresh the page
11. Switch on the internet
12. Verify group members and rooms
13. Re-login to your account
14. Verify group members and rooms

## Expected Result:
Deleted offline members must be deleted irrevocably

## Actual Result:
Deleted members in offline mode return after re-logging

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/01a42665-66b6-47fb-af64-8698bb06c9f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013de8ecf9253d513b</li>
        <li>Upwork Job ID: 1785793505580089344</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by oscarguinane** [comment]
Are staging creds available to fix it?

**Comment by oscarguinane** [comment]
Happy to jump into staging, fix it and then apply to the Upwork job with a PR ready

**Comment by jayeshmangwani** [comment]
@oscarguinane Please go through our [contributing guidelines](https://github.com/Expensify/App/blob/db86427b3836a212b6fd456620907ff55baa00da/contributingGuides/CONTRIBUTING.md) to familiarize yourself with the process.

**Comment by oscarguinane** [comment]
Ok

**Comment by oscarguinane** [comment]
(got it - it's in the guidelines)

**Comment by oscarguinane** [comment]
Ok I'm setup - requested Slack access

**Comment by jayeshmangwani** [comment]
Waiting for proposals

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment]
Closing as not reproducible, but please reopen if you disagree
