### ISSUE TITLE
[HOLD for payment 2024-05-03] [HOLD for payment 2024-05-02] [$250] Chat - Black Video Preview Issue in Concierge Welcome Message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40907]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.65-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature 
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39687
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in with a new account and complete the onboarding flow.
2. Navigate to the Expensify Concierge welcome message.
3. Move to another chat and then return to the Concierge message.

## Expected Result:
The black preview of the Concierge video should not be displayed. Instead, a live preview should be shown.

## Actual Result:
A black preview of the Concierge video is shown in the Expensify Concierge welcome message.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/867042bc-a260-420d-aad9-f703091dccc2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f89966fcb2b8f2a8</li>
        <li>Upwork Job ID: 1783161751164862464</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by mountiny** [comment]
It seems like this is happening with any video preview, discussing in [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1713971649588369?thread_ts=1713921662.625269&cid=C036QM0SLJK)

**Comment by NJ-2020** [comment]
Contributor details
Your Expensify account email: ntt.london@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ff73ff788ecf5f2e

**Comment by tgolen** [comment]
@francoisl I think you were looking into this one, so I'm going to assign it to you.

**Comment by francoisl** [comment]
This was handled and reviewed internally.
