### ISSUE TITLE
[$250] Split - Chat header shows split creator and split user avatar briefly when splitting expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense
3. Split expense with one user that has no chat history
4. Note the avatar in chat header

## Expected Result:
The chat header will show the split user avatar

## Actual Result:
The chat header shows split creator and split user avatar briefly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a566e944-92ed-4a12-88ad-03e61451361e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019386f7d8c4cc34c1</li>
        <li>Upwork Job ID: 1785372503599595520</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by Pujan92** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/40904#issuecomment-2075286998) looks good which is suggested to pass `participantAccountIDs` instead of `allParticipantsAccountIDs`(contains currentUserID) for 1:1 case.

🎀👀🎀 C+ reviewed

**Comment by anmurali** [comment]
@madmax330 do you agree with [this](https://github.com/Expensify/App/issues/40904#issuecomment-2089746908)? Can I assign the issue to @bernhardoj

**Comment by bernhardoj** [comment]
PR is ready

cc: @Pujan92

**Comment by bernhardoj** [comment]
The PR is merged. I think it's ready for payment @anmurali.

**Comment by Pujan92** [comment]
Bump @anmurali for the payment!

**Comment by anmurali** [comment]
Paid everyone.
