### ISSUE TITLE
[QBO] Error shows up when selecting any option under "Export company cards as"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40914]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40713
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces > any workspace
3. Go to Accounting
4. Connect to QBO
5. Click Export > Export company cards as
6. Select any option
7. Return to the previous page

## Expected Result:
No error will show up

## Actual Result:
Error "something went wrong and your request could not be completed" shows up
404 Not found also appears in console when fetching data
This issue happens with all the options under "Export company cards as"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3b590f90-d152-4964-ba51-5371a68afab3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bccb20058565122</li>
        <li>Upwork Job ID: 1783579229700677632</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
cc @hayata-suenaga @teneeto @aldo-expensify for vis

**Comment by aldo-expensify** [comment]
Preparing a PR to add the missing connection setting names: https://github.com/Expensify/Auth/blob/e93860891ed5d66f560bce44a7847c7a19fec753/auth/lib/Policy.h#L124-L140

**Comment by trjExpensify** [comment]
Linking [the thread](https://expensify.slack.com/archives/C036QM0SLJK/p1714072867274109?thread_ts=1714057353.559839&cid=C036QM0SLJK) for posterity.

**Comment by zanyrenney** [comment]
PR is merged for this above, and deployed to Prod.
