### ISSUE TITLE
 iOS - Onboarding - App crashes during "Track business spend for taxes" onboarding flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4509316
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Enter a new email address ( new account)
3. Go to your inbox and find the email with the magic code > Tap on the magic code link (please use the link)
4. On the engagement modal > choose ''Track business spend for taxes''
5. Enter both first and last names > Tap continue
6. Enter business name > Tap continue

## Expected Result:
App should not crash during onboarding flow

## Actual Result:
App crashes during "Track business spend for taxes" onboarding flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ce26c1fe-f6ba-4e8f-a247-8ef3ab1e339a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production:

https://github.com/Expensify/App/assets/78819774/4def2f97-0a06-4525-8680-960ec1de38d0

**Comment by mountiny** [comment]
@rezkiy37 @filip-solecki @cdOut this might be related to the full story

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I can take care of this issue!

**Comment by mountiny** [comment]
I have tested on this revert build https://github.com/Expensify/App/pull/40894 and I could not repro

**Comment by mountiny** [comment]
I was able to repro on staging and I was not able to repro on the adhoc build with the full story reverted
https://github.com/Expensify/App/assets/36083550/9de6c6b1-cb78-496b-aad1-3b4909d075f3


https://github.com/Expensify/App/assets/36083550/c2f509c7-a4bb-455b-98f4-42e5f83b17f9

**Comment by mountiny** [comment]
CPing the full story revert

**Comment by kbecciv** [comment]
QA team is unable to reproduce on the adhoc build

https://github.com/Expensify/App/assets/93399543/e008b3b1-1f1c-46db-b5ab-44acad315c97
