### ISSUE TITLE
Onboarding - Onboarding modal doesn't get shown for expensifail accounts

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**Issue found when executing PR:** https://github.com/Expensify/App/pull/39687
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new Expensifail account

## Expected Result:
Onboarding modal shows up

## Actual Result:
Onboarding modal doesn't show up for Expensifail accounts (Works fine for Gmail accounts)

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1d4850b3-c408-484f-9d45-dbb92b030cc2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
Thanks!

**Comment by mountiny** [comment]
We are not going to show this to domain controlled accounts.
