### ISSUE TITLE
[HOLD for payment 2024-05-22] [Wave Collect] New Resources to Publish for Help Site: QBO

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#40920]
## Publish Date - May 1
[DRAFT](https://docs.google.com/document/d/1xJ0fiWjvqHIh-C3tmlHGh0Hs1YM8kxBwPGQSOPfsd9M/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by ren-jones** [comment]
Thank you! I'm ready to be assigned!

**Comment by zanyrenney** [comment]
We are team-working on this in the doc!

**Comment by zanyrenney** [comment]
Ren finished his review and will publish this today / tomorrow!

**Comment by zanyrenney** [comment]
no payment, ren is paid separately.
