### ISSUE TITLE
LHN - Last archived WS appears in LHN after new WS added (#focus)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40921]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2644118
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Priority mode set to #focus
1. User delete workspace
2. Unpin every archived chat to let it disappeared
3. Add new workspace
4. Navigate to LHN

## Expected Result:
New workspace related chat appears

## Actual Result:
New workspace related chat appears. After a while, the last deleted workspace chats (archived) appear and marked bold

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8e1c2f31-21f4-4da1-8c6b-0903a5be37a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by puneetlath** [comment]
I just tried and wasn't able to reproduce this. Closing out, but feel free to reopen if you're able to reproduce!
