### ISSUE TITLE
[Wave collect] [Guided Setup] Ensure the onboarding NVP is set only for new organic sign-ups

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#40927]
### Problem

For the onboarding flow, we need to set the `nvp_onboarding` for new sign ups. At the moment, we add it to any account created (except domain controlled), but we want to make sure accounts created by other users (inviting to a workspace, starting a chat/ requesting money) will not have this NVP set, or they will have the `hasCompletedGuidedSetupFlow` property said to `true`, so they are not presented with the onboarding flow.

This way only people who organically signed up in OldDot or NewDot would get this NVP.

### Solution

Pass params from the API commands when users are signing up so we know when we should set this NVP only for users who do not have any account yet.

**Comment by muttmuure** [comment]
Fully internal and now merged. Closing!
