### ISSUE TITLE
[$250] mWeb - LHN - Self DM is auto pinned in new gmail a/c in LHN but in expensifail a/c it doesn't

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40932]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Login with new gmail account
3. Note LHN displays self DM auto pinned
4. Go to staging.new.expensify.com in mweb
5. Login with new expensifail account
6. Note LHN

## Expected Result:
In both gmail and expensifail new account, self DM behaviour in LHN must be consistent

## Actual Result:
When user opens new gmail a/c, self DM is auto pinned in LHN but in expensifail a/c it doesn't

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/21edfdbe-6298-4527-a6fa-aaff56b6b95b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01616317ace3ceca39</li>
        <li>Upwork Job ID: 1785432840279183360</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by hungvu193** [comment]
@lanitochka17 is this still producible? If Yes, can you please provide an expensifail account?

**Comment by lanitochka17** [comment]
@hungvu193 Issue is not reproducible on the expensifail account


https://github.com/Expensify/App/assets/78819774/0d3914a3-1b3a-49e6-886d-b0c0361eb01e

**Comment by hungvu193** [comment]
So I think we can close this issue

**Comment by hungvu193** [comment]
> @hungvu193 Issue is not reproducible on the expensifail account
> 
>  cf.mp4

Bump @johncschuster for the comment above
