### ISSUE TITLE
[$250] IOU - Unable to hold request as requestee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40935]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-3
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B.
3. [User B] Go to transaction thread of one of the requests.
4. [User B] Click 3-dot menu.
5. [User B] Click Hold request.

## Expected Result:
The requestee should be able to hold the request.

## Actual Result:
The requestee is unable to hold the request.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0bb9b795-a29d-4b2f-8d87-42505bcbe2fd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105f7d7fccafab4d0</li>
        <li>Upwork Job ID: 1783534892479332352</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
@adelekennedy FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by adelekennedy** [comment]
This is reproducible for me - moving to project
