### ISSUE TITLE
[HOLD for Payment 5-16][$250] Distance rate - Value ending with decimal point in distance rate editor is not accepted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40946]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual
3. Enter amount ending with decimal point (eg, 8.) > Next
4. Note that app proceeds to next step
5. Go to taxes section in Collect workspace
6. Click Add rate > Value
7. Enter amount ending with decimal point (eg, 8.) > Save
8. Note that the value is accepted
9. Go to Distance rates section > Add rate
10. Enter amount ending with decimal point (eg, 8.) > Save

## Expected Result:
The value ending with decimal point in distance rate editor should be accepted

## Actual Result:
The value ending with decimal point in distance rate editor is not accepted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/72fdbd96-8ee4-4862-9921-57d9b5f6d0bf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c566adc64c516d8</li>
        <li>Upwork Job ID: 1783752626404245504</li>
        <li>Last Price Increase: 2024-04-26</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment]
I think this might be vsb-split (as I see other BZ Distance GHs linked to that project). Let's see if this can be external

**Comment by Christinadobrzyn** [comment]
However, I'm also wondering if we want to fix this as explained in the OP or if we want to throw an error. Do we want users to be able to enter a "3." value?

**Comment by ikevin127** [comment]
♻️ Reviewing [proposal](https://github.com/Expensify/App/issues/40946#issuecomment-2076016410).

@Christinadobrzyn Please let me know what the team decided based on https://github.com/Expensify/App/issues/40946#issuecomment-2078751702.

**Comment by ikevin127** [comment]
@GandalfGwaihir's proposal looks good to me. The RCA was correctly identified and the proposed solution fixes the issue accordingly.

🎀👀🎀 C+ reviewed

**Comment by Christinadobrzyn** [comment]
nudging the team for some thoughts - https://expensify.slack.com/archives/C05RECHFBEW/p1714384313394889

**Comment by Christinadobrzyn** [comment]
Thanks @lakchote - yes that's my understanding. A user should be able to enter a number ending with a decimal. Thank you!

**Comment by lakchote** [comment]
> I guess we're good to [proceed](https://github.com/Expensify/App/issues/40946#issuecomment-2080271299) with the PR @lakchote ?

Yes, your proposal LGTM.

**Comment by Christinadobrzyn** [comment]
reviewing PR - https://github.com/Expensify/App/pull/41503

**Comment by ikevin127** [comment]
⚠️ Automation failed -> this should be on **[HOLD for Payment [2024-05-15]]** according to today's production deploy from [#41503 (comment)](https://github.com/Expensify/App/pull/41503#issuecomment-2101804253).

cc @Christinadobrzyn

**Comment by Christinadobrzyn** [comment]
Payouts due:

- [ ] Contributor: $250 @GandalfGwaihir (Upwork offer here - https://www.upwork.com/nx/wm/workroom/37146800/overview)
- [ ] Contributor+: $250 @ikevin127 (Upwork offer here - https://www.upwork.com/nx/wm/workroom/37146801/overview)

Upwork job is [here](https://www.upwork.com/jobs/~010c566adc64c516d8).

We'll pay this in a few days!

**Comment by Christinadobrzyn** [comment]
Paid out based on this [payment summary](https://github.com/Expensify/App/issues/40946#issuecomment-2109608974). 

I assume we'll create a regression test for this at the end of the polish process? @lakchote?

**Comment by ikevin127** [comment]
## Regression Test Proposal

**Preconditions:**

We need to have a Collect workspace with **Distance rates** enabled.

1. Navigate to https://staging.new.expensify.com.
2. Go to **Distance rates** section in Collect workspace.
3. Click on **[+ Add rate]** and enter amount ending with decimal point eg. `8.` then Save.
5. Verify that you are able to Save the value ending with decimal point.

Do we agree 👍 or 👎.

**Comment by Christinadobrzyn** [comment]
Regression test - https://github.com/Expensify/Expensify/issues/397047

Payment summary here - https://github.com/Expensify/App/issues/40946#issuecomment-2109608974

Closing as complete!
