### ISSUE TITLE
[Hold App PR #39875] Android - App crashes after disabling location access if it was previously enabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40948]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4510553
**Issue reported by:** Applause - Internal Team
*

## Action Performed:
Precondition: user is a member of a workspace, the app is freshly installed
1. Open the app and log in
2. Navigate to the workspace
3. Tap the + button > Submit expense > Distance
4. On the location access pop-up select "Don't allow"
5. Create a distance expense
6. Start creating another distance expense
7. If the location access pop-up appears, select "While using app" or "Only this time" or navigate to the app setting and allow location access
8. Complete distance expense
9. Navigate to the app settings and disable location access
10. Open the workspace chat > + > Submit expense

## Expected Result:
User is able to proceed to create a distance expense

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/39e20418-3926-423d-bc7a-47d4d16afc5c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by JmillsExpensify** [comment]
Given that we ask for location services, I agree with adding to wave-collect. Adding as a polish item and opening up to the community.

**Comment by trjExpensify** [comment]
@Julesssss @allroundexperts FYI. Is this being addressed in https://github.com/Expensify/App/pull/39875?

**Comment by allroundexperts** [comment]
It's not related to changes there. But I think since we're doing a major refactor, it will be handled there. Let's put this on hold for that.

**Comment by Julesssss** [comment]
@trjExpensify I agree with @allroundexperts

We'll get this handled as part of our changes.

**Comment by trjExpensify** [comment]
Sounds good!

**Comment by JmillsExpensify** [comment]
Nice, thanks ya'll!

**Comment by JmillsExpensify** [comment]
Still held on linked issue.

**Comment by Julesssss** [comment]
The linked PR is awaiting fixes based on our feedback

**Comment by Julesssss** [comment]
The linked PR is in review again.

**Comment by Julesssss** [comment]
Answering some questions on the PR today. We're getting closer and have split some work into a follow-up task to speed up the process.

**Comment by JmillsExpensify** [comment]
Still actively working through the linked PR.

**Comment by Julesssss** [comment]
The blocking PR is very close now

**Comment by Julesssss** [comment]
PR has had translations approved and is undergoing more testing

**Comment by Julesssss** [comment]
Lets retest now that the linked PR is completed.

**Comment by Julesssss** [comment]
Requested retest

**Comment by m-natarajan** [comment]
Bug is fixed 

Uploading az_recorder_20240730_211124.mp4…

**Comment by Julesssss** [comment]
Excellent, thank you
