### ISSUE TITLE
Distance rates - Deleted distance rates appear in the rate list in confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Collect workspace settings
3. Go to Distance rates
4. Click Add rate
5. Add a few rates
6. Delete some rates
7. Go to workspace chat
8. Start submit distance flow
9. In confirmation page, click Rate

## Expected Result:
Deleted distance rates will not appear in the list.

## Actual Result:
Deleted distance rates still appear in the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/31f96368-2276-46d5-8b20-dfda84359291

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by dylanexpensify** [comment]
reviewing now! Was ooo

**Comment by dylanexpensify** [comment]
Could not reproduce. @lanitochka17 can you confirm?

**Comment by dylanexpensify** [comment]
Bump @lanitochka17

**Comment by lanitochka17** [comment]
@dylanexpensify Issue is not reproducible on the latest build 1.4.69-0


https://github.com/Expensify/App/assets/78819774/504b5b4b-ffc2-41a6-98dc-9a3749d3db13
