### ISSUE TITLE
LOW: [HOLD] Prep for removal of `originalMessage`

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#40952]
Being discussed here: https://expensify.slack.com/archives/C05LX9D6E07/p1714011537859119?thread_ts=1712335077.999829&cid=C05LX9D6E07

**Comment by muttmuure** [comment]
Doing a cleanup of LOW issues. I think we figured this out over here https://github.com/Expensify/App/issues/39797#top - please reopen if there is more to do here!
