### ISSUE TITLE
`New Message` does not disappear even scrolling down to the bottom message of the chat report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40954]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zsgreenwald 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713981387980809

## Action Performed:

1. Go into a room with existing messages ([here's one you can join](https://new.expensify.com/r/6776919265133947))
2. Scroll down to the bottom
3. Click new messages if it appears

## Expected Result:
 It should only show once if I wasn't at the most recent chat, and if I was "all caught up" it shouldn't present itself at all.

## Actual Result:
Notice that keeps presenting `New message`

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/64c123bd-7778-44c6-b4b9-ad77159d397e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
This one is on my testing list, I should have an update soon.

**Comment by alexpensify** [comment]
No update yet, I've been focused on other GHs.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience


![2024-05-02_13-11-45](https://github.com/Expensify/App/assets/8107070/c6b64aec-94d2-4e11-af4c-0f46f8c381ce)
