### ISSUE TITLE
[$250] Login - User is redirected to an unknown chat with infinite loading on new login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account.

## Expected Result:
User is redirected to Concierge page on new login.

## Actual Result:
User is redirected to an unknown chat with infinite loading on new login.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/22d62d51-b0b1-4e3e-8be2-86b0fcd0b3f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01546d32eac1f93b1e</li>
        <li>Upwork Job ID: 1785704889380818944</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@CortneyOfstad FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by CortneyOfstad** [comment]
I just signed up a new account today to test another issue and did not experience this. @kbecciv can we confirm if this is still happening?

**Comment by CortneyOfstad** [comment]
Going to have this retested, as I cannot recreate on my side

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment]
Closing this as we could not recreated. Thanks @mvtglobally!
