### ISSUE TITLE
HOLD for Payment [2024-05-16] [$250] Room - Room name character limit is 79 characters instead of 100

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40968]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4506180
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Go to Room tab.
4. Try to enter more than 79 characters.

## Expected Result:
The room name character limit is 100 characters.

## Actual Result:
The room name character limit is 79 characters.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f50a3d83-c19c-40bf-ba91-ae30a60b4858

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d41cf935d9bcfd5</li>
        <li>Upwork Job ID: 1783512147519520768</li>
        <li>Last Price Increase: 2024-04-25</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by eh2077** [comment]
@GandalfGwaihir 's [proposal](https://github.com/Expensify/App/issues/40968#issuecomment-2077054600) looks good to me. The root cause is clear. We can use this constant for the length limit
https://github.com/Expensify/App/blob/0b9665445c41fe5e080edd739583426087ccab79/src/CONST.ts#L1913
We can discuss the detail implementation in PR.

🎀👀🎀 C+ reviewed

**Comment by dangrous** [comment]
That proposal works for me as well! We might want to keep a separate constant for the 99 / 100 issue, but yes can discuss.

**Comment by isabelastisser** [comment]
@GandalfGwaihir is this ready for payment? Please provide an update. Thanks!

**Comment by eh2077** [comment]
> @GandalfGwaihir is this ready for payment? Please provide an update. Thanks!

@isabelastisser It's not ready yet.

> ✋ This PR was not deployed to staging yet because QA is ongoing.

**Comment by dangrous** [comment]
ready for payment!

**Comment by isabelastisser** [comment]
Reviewing!

**Comment by isabelastisser** [comment]
The payments were processed in Upwork. This should be all set!
