### ISSUE TITLE
[$250] mWeb - Scan - As employee deleted scan receipt when opened as admin receipt page displays error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4510561
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app and login as employee
2. Tap plus icon -- submit expense -- scan
3. Upload an image using camera
4. Tap scan
5. Open the scan expense and enter all details
6. Tap receipt and tapping 3 dots on top, delete the receipt
7. Login mweb as admin
8. Open Workspace chat and note receipt deleted expense is shown with green label
9. Tap on green label

## Expected Result:
As employee deleted scan receipt when opened as admin receipt page must not display 403 forbidden error

## Actual Result:
As employee deleted scan receipt when opened as admin receipt page displays 403 forbidden error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ba39a0bb-4c02-4a29-a0f8-23ccb277baaf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c381ba0b987166a</li>
        <li>Upwork Job ID: 1783861900893196288</li>
        <li>Last Price Increase: 2024-05-03</li>
    </ul>
</details>

**Comment by jjcoffee** [comment]
Waiting for proposals!

**Comment by bfitzexpensify** [comment]
Still waiting on proposals

**Comment by jjcoffee** [comment]
Just a heads up I'll be OOO 6-13th (I may have some time on the 6th), so feel free to re-assign if proposals start rolling in before I'm back!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment]
>Issue not reproducible during KI retests. (First week)

Great! Let's close this out then, it can be reopened if further reports occur.
