### ISSUE TITLE
 Room - Unable to log in as invited room user (Expensifail account)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40975]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat > Room.
3. Create a room.
4. Go to chat header > Members.
5. Invite a new Expensifail account (not registered to New Dot yet).
6. Log in as the invited account.

## Expected Result:
The invited user is able to log in.

## Actual Result:
The invited user is unable to log in. Error "Couldn't retrieve account details, please try to sign in again." shows up.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/baa85549-1a9c-44e4-bf2f-7063893641ba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@adelekennedy FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by adelekennedy** [comment]
as the new user I'm invited to set up an account once I log in for the first time - I think this has been fixed in the later staging version
