### ISSUE TITLE
[No payment] Workspace - Not here page shows up when opening profile of invited user in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40989]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces > any workspace
3. Go to Members section
4. Go offline
5. Invite a new user
6. Click on the new user in member list
7. Click Profile

## Expected Result:
The profile for newly invited user will open without issue

## Actual Result:
Not here page shows up
The same issue also happens online, but briefly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ba49cdcf-af8f-4c75-af9f-e3a3e4d17dc7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Kicu</details>

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by strepanier03** [comment]
Looking at this now.

**Comment by NikkiWines** [comment]
There's a number off offline related issues (as well as fallback avatars not loading) in the blockers for this round that I suspect are all linked

**Comment by mountiny** [comment]
Testing if the revert of https://github.com/Expensify/App/pull/41087 will fix this

**Comment by grgia** [comment]
cc @Kicu

**Comment by mountiny** [comment]
@Kicu can you please comment here so we can assign you so this is tracked and can be fixed in the follow up PR? thank you!

**Comment by mountiny** [comment]
Appreciated!

**Comment by strepanier03** [comment]
Will close once the checklist is done.

**Comment by mountiny** [comment]
We have reverted the offending Pr so I think we can close this one without further waiting for a checklist as there is nothing to add here
