### ISSUE TITLE
[$250] Workspace – Hmm it’s not here appears briefly in LHN when delete WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40993]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a New Workspase.
4. Open WS Profile and press delete WS

## Expected Result:
Hmm it’s not here not appears briefly in LHN when delete WS

## Actual Result:
Hmm it’s not here appears briefly in LHN when delete WS

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/de1a3515-5791-4a34-b562-1d7f7e22f231

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166340b87e3ba9a3e</li>
        <li>Upwork Job ID: 1783819946610835456</li>
        <li>Last Price Increase: 2024-05-03</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment]
@mountiny any thoughts on @tienifr's proposal?

**Comment by hayata-suenaga** [comment]
I'm hesitant to introduce another `ref` just to check if the policy was accessible before or not.

This is a tradeoff between achieving the best UX vs. introducing additional logic to the code.

Logically, it makes sense to display the not found page because for a brief moment, we deletion is indeed pending.

I also think this is not worth fixing. Let me know what you think @mountiny

**Comment by hayata-suenaga** [comment]
@getusha, could you share your thoughts, please? 😄

**Comment by hayata-suenaga** [comment]
bump @getusha 😄

**Comment by getusha** [comment]
@hayata-suenaga we can fix it like we fixed it on other places but still feels a very minor bug, i actually doubt if it affects a user.

**Comment by hayata-suenaga** [comment]
I agree we probably don't have to fix this as we're now focusing on most critical bugs 👍 

I'll close this issue
