### ISSUE TITLE
[HOLD for payment 2024-05-30] HIGH: Fix extraneous `ReconnectApp` on refresh

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#40995]
Being discussed here: https://expensify.slack.com/archives/C049HHMV9SM/p1714059210537139

Often occurs in conjunction with [HIGH: [Reliability] [$500] Multiple calls to GetNewerActions on report open](https://github.com/Expensify/App/issues/39674) and [HIGH: [API Reliability] [$250] Multiple calls to OpenReport on signin](https://github.com/Expensify/App/issues/39673#top), but seems to be a different root cause.

## Actions Performed:

1. Go to staging.new.expensify.com and login
2. Open any report 
3. Refresh the page
4. Observe the API calls for the `OpenApp` `ReconnectApp` and `OpenReport`

# Expected Result:
There should be only one `ReconnectApp` `OpenReport` `OpenApp` calls 

# Actual Result:
Multiple calls for `ReconnectApp` `OpenReport` 

## Platforms:
Mac OS: Chrome/Safari

## Screenshots/Videos:

![image (15)](https://github.com/Expensify/App/assets/38435837/4f58c4f5-f0cd-41b8-b079-e41d8d5448d2)

![image (14)](https://github.com/Expensify/App/assets/38435837/644def53-0e83-4859-ac37-9c99346de8dd)
![image (13)](https://github.com/Expensify/App/assets/38435837/c2b819e1-7509-4ed1-9983-a4a98a26a86e)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01008cff119674ebe1</li>
        <li>Upwork Job ID: 1787505314359492608</li>
        <li>Last Price Increase: 2024-05-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by gedu** [comment]
Hey Edu here from Callstack

**Comment by gedu** [comment]
Updates on the `OpenReport` call case

### Problems
There are 2 cases that I’m trying to prevent:

1. Multiple calls given different scenarios, happy path (opening the report) and multiple ReportScreen creation (navigating to the report, maybe a refresh) all happening at the same time

2. Updates on the multiple created ReportScreen, changing to another Report all reports gets updated

### Solution
1. I’m storing a set of the ReportsID calling the openReport so if the reportID is already fetching no need to call it again -> it gets removed when the response comes back

2. I’m checking if the url reportID matches the active reportID (there always 1 report active), if it is active I can call the openReport

At least for now seems to be working, I'm testing and soon I can make a formal proposal or a PR if you want

**Comment by quinthar** [comment]
I don't think that's the right solution -- we don't want to suppress multiple calls, we want to figure out why the code is even attempting to make multiple calls, and stop it.

**Comment by quinthar** [comment]
actually, is this a dupe of: https://github.com/Expensify/App/issues/39673?

**Comment by quinthar** [comment]
Actually, the `OpenReport` portion of this seems like a dupe; let's reduce the scope of this issue to just be fixing the extraneous calls to `ReconnectApp`, ok @gedu ?

**Comment by gedu** [comment]
@quinthar ok, The "suppress" is mainly because we create multiple ReportScreen, and even when you switch a report I saw `OpenReport` being called multiple times.  
I will take a look at `ReconnectApp`

**Comment by gedu** [comment]
@quinthar 
Looking at the code, when the site gets refreshed first it does the normal walk through, checking if the user was logged in already, which is true so it does a `reconnectApp`

### Problem
On the other hand, the app register to the Network status, when it is registered it receives updates
NetwokrConnection.ts file subscribeToNetInfo function
```
NetInfo.addEventListener((state) => {
   // code
   setOfflineStatus((state.isInternetReachable ?? false) === false);
   });
```
Given that `isInternetReachable` is null for a couple of calls before getting the right value, it triggers the reconnection.
<img width="849" alt="Screenshot 2024-04-29 at 12 11 31" src="https://github.com/Expensify/App/assets/1676818/f970d62b-183e-4b43-8da6-0e64c105447a">


### Solution
Given that the Lib for web is still experimental and in the description for isInternetReachable [if it is unknown is null](https://github.com/react-native-netinfo/react-native-netinfo?tab=readme-ov-file#types). Also checking the code for web they send basic information until they collect the real
```
 const baseState = {
    isInternetReachable: null,
  };

  // If we don't have a connection object, we return minimal information
  ```
I suggest to remove the `?? false` because we only care when the isInternetReachable  has a value and the Lib has created a connection object with the data in it.

**Comment by jjcoffee** [comment]
Getting an engineer auto-assigned.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment]
I'm temporarily out of the C+ team as I'm about to go OOO, so the auto-assigning isn't working here. Tagging @tgolen on the PR to give it a quick review, otherwise once the BZ is assigned maybe they can find someone?

**Comment by mallenexpensify** [comment]
Sorry @s77rt , needed to assign to BZ and @jjcoffee as C+ , @jjcoffee is OOO soon so he's off the GH C+ team.

**Comment by dylanexpensify** [comment]
Hiya! @mallenexpensify mind confirming what's needed here?

**Comment by jjcoffee** [comment]
@dylanexpensify The PR hasn't hit staging yet, but eventually payment will be due for C+ review.

**Comment by muttmuure** [comment]
What's the next step here? Who's doing it? What is the ETA?

**Comment by muttmuure** [comment]
So we just need to pay this out?

**Comment by mountiny** [comment]
Yep this was only deployed to staging so far though

**Comment by dylanexpensify** [comment]
Hit prod on 23rd, tomorrow will pay out!

**Comment by jjcoffee** [comment]
@dylanexpensify Friendly bump for payment :bow:

**Comment by dylanexpensify** [comment]
Invited to apply!

**Comment by jjcoffee** [comment]
@dylanexpensify Thank you, I've applied! :pray:

**Comment by jjcoffee** [comment]
@dylanexpensify Friendly bump :bow:

**Comment by jjcoffee** [comment]
@dylanexpensify No worries! I've accepted the offer now.

**Comment by dylanexpensify** [comment]
done!
