### ISSUE TITLE
Onboarding - Onboarding video does not have an audio

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41000]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40688
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new Gmail account
3. On the Onboarding select "Track business spend for taxes" as a purpose and click on continue
4. Input first name and last name and click on continue
5. Input a business name and click on continue
6. When the Welcome to Expensify modal opens up click on the unmute button to check the audio and notice it works fine
7. Open Concierge chat and wait for the backend to send attachment
8. Once the attachment loads play the video and unmute it

## Expected Result:
Audio works fine and can be heard

## Actual Result:
There is no audio for the video

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9aafbf48-375b-40ce-ad72-7feea2d65985

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jasperhuangg  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
This is a new feature so not a blocker, discussing here if the videos should [have sounds](https://expensify.slack.com/archives/C036QM0SLJK/p1714129581468229), I did not have the sounds when testing it before

**Comment by mountiny** [comment]
this is expected now, not a problem with the videos

**Comment by mountiny** [comment]
I believe @dubielzyk-expensify Will handle this one, assigning and making weekly

**Comment by dubielzyk-expensify** [comment]
I'll get this done. Basically just need TCW to export new videos with songs. It's not a huge priority, but I'll update once I've done it

**Comment by dubielzyk-expensify** [comment]
Update: Asked TCW for them but mentioned it was low priority, but will let y'all know when we get the final files

**Comment by dubielzyk-expensify** [comment]
We have [the final videos here](https://www.dropbox.com/home/Expensify/Design/Product%20GIFs/01_MP4) now with video, but I would require help in compressing and replacing them. Last time we got @francoisl 's help, so I'd love to get his help again 😇

**Comment by francoisl** [comment]
Yeah I can help. Can you double-check that Dropbox URL and make sure I have read access to it please? I'm getting a `The folder ‘Expensify/Design/Product GIFs/01_MP4’ doesn’t exist.` error.

**Comment by dubielzyk-expensify** [comment]
No idea why this happens. Thought everyone had access to it. Shared with you directly regardless 😄

**Comment by francoisl** [comment]
Sorry @dubielzyk-expensify the link https://www.dropbox.com/home/Expensify/Design/Product%20GIFs/01_MP4 still doesn't work, however I can access https://www.dropbox.com/home/01_MP4. To confirm, the new videos we need to compress are the ones whose name ends with `-sound.mp4`, right?

**Comment by dubielzyk-expensify** [comment]
> To confirm, the new videos we need to compress are the ones whose name ends with -sound.mp4, right?
Correct.

No idea why this happens. cc @Expensify/design

**Comment by dannymcclain** [comment]
Dang no idea on that either. The permissions for that folder (and all the ones above it) look correct? That's odd.

**Comment by shawnborton** [comment]
But yeah, in the meantime, maybe we put these on Drive for Francois or something.

**Comment by francoisl** [comment]
No worries, I'm still able to see the new videos. Thanks guys!

I'll send a PR shortly to use the new videos. I also wrote the command I use to rescale videos in Stackoverflow https://stackoverflowteams.com/c/expensify/questions/19224/19225#19225

**Comment by mountiny** [comment]
PR approved, waiting for design feedback about the default sound settings

**Comment by dubielzyk-expensify** [comment]
We've left sound off by default, but I believe that PR has been merged, so are we good to close this one?

**Comment by mountiny** [comment]
yeah, nothing to pay
