### ISSUE TITLE
[HOLD for payment 2024-05-06] [QBO] Tax toggle should be locked to disabled for QBO entities with country set to USA

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#41008]
**New feature missed in Design Doc:**

Tax toggle should be locked to disabled for QBO entities with country set to USA.

Secondly --  the country is set to USA, we should not show the taxes row in the import page
<img width="1048" alt="2024-04-25_18-47-24" src="https://github.com/Expensify/App/assets/56830058/4dea52ca-e1a5-457b-9b78-f1964de38ab8">

**Comment by zanyrenney** [comment]
Lmk when you want me to retest @hayata-suenaga @aldo-expensify @dangrous

**Comment by dangrous** [comment]
Just to clarify your description above - do we want to disable it, or fully remove it?

**Comment by hayata-suenaga** [comment]
@zanyrenney, the PR was [deployed to staging](https://github.com/Expensify/App/pull/41006#issuecomment-2080227963). We can test it now 😄

**Comment by hayata-suenaga** [comment]
> Or are you talking about two different things (the toggle vs. the import menu)?

@dangrous, we're talking about two different screens.

One is about the toggle button for enabling tax tracking feature on the More Features screen. We want to lock this feature when the workspace is connected to QBO whose entity is US

The other one is about the toggle import menu on the import page. We don't want to display this menu under the same condition I described above.

**Comment by hayata-suenaga** [comment]
Note: there was no C+ review of [the PR](https://github.com/Expensify/App/pull/41006) for this issue. No payment is needed.

**Comment by zanyrenney** [comment]
Closing as no C+ review / payment due.
