### ISSUE TITLE
[$250] Chat - Chat Time removed for a second when mention the user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41003]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**(https://expensify.testrail.io/index.php?/runs/view/20868&group_by=cases:section_id&group_order=asc&group_id=306201)
**Email or phone of affected tester (no customers):**  shussain+accoun1@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a user chat
2. Mentioned the same user
3. Notice the time removed for a second

## Expected Result:
Chat time should not removed for a second when mention the chat user

## Actual Result:
Chat time removed for a second when mention the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c61357cc-d318-42de-9296-a3517e1a300c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db77afd13eb74152</li>
        <li>Upwork Job ID: 1784183096937213952</li>
        <li>Last Price Increase: 2024-04-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
Yep, I can reproduce this one. Adding it to #vip-vsb as a pure chat bug. 

https://github.com/Expensify/App/assets/16232057/afad7ce4-0779-4c40-baa3-16e47cb59a49

**Comment by trjExpensify** [comment]
> I think this is a BE issue, `AddComment` API resets the participant's personal details `validated` to empty.
> 
> <img alt="Screenshot 2024-04-27 at 18 51 45" width="898" src="https://private-user-images.githubusercontent.com/153004152/326176131-5320dee0-15fd-4658-b505-4e6e2d8c7c3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODMwMjgsIm5iZiI6MTcxNDQ4MjcyOCwicGF0aCI6Ii8xNTMwMDQxNTIvMzI2MTc2MTMxLTUzMjBkZWUwLTE1ZmQtNDY1OC1iNTA1LTRlNmUyZDhjN2MzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzEyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjEzOGQ1ODBjMDg4NDk5NzJlMjVkMDMxZTcxY2RiMWViZGZhNmJmMTA5YTg2MDI5NmQwNzkwMWE3MjU4YjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J-UhfYnPHO0MVBe8v13t9DK9KRhDJCuhqY8F05qt3nk">
> causing the check [here](https://github.com/Expensify/App/blob/10fc359d9fdd1e05e03a4769e2a73f95e703be51/src/libs/ReportUtils.ts#L1571) to fail.

Gotcha. Moved it internal.

**Comment by trjExpensify** [comment]
Needs an internal volunteer.

**Comment by rlinoz** [comment]
Let me take this as an afternoon Friday issue.

**Comment by rlinoz** [comment]
Deployed to prod https://github.com/Expensify/Auth/pull/10858#issuecomment-2109004264

**Comment by rlinoz** [comment]
I think we can close this.
