### ISSUE TITLE
[HOLD for payment 2024-07-22][$125] mWeb - IOU - Clicking back from expense title edit page after a refresh takes to LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41017]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40704
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with an expensifail account
3. Create a workspace
4. Open workspace chat page
5. Create 2 IOUs
6. Open expense report page
7. Click on "Title"
8. Refresh the page
9. Click on the back icon at the top left corner

## Expected Result:
App takes user back to the expense report page

## Actual Result:
App takes user to the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8347b976-0ae3-42c4-98a2-b848dc8d025c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011da57b8f26d630ba</li>
        <li>Upwork Job ID: 1783627161453916160</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 102842730</li>
<li>dominictb | Contributor | 102842731</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by lanitochka17** [comment]
@roryabraham  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by CK-codemax** [comment]
Refreshing the page on expense title exit page and pressing back leads to LHN

The Navigation.dismissModalWithReport solution seems really good as it goes indepth .
The report parameter suggests that it might be expecting an object that contains information about the modal or the report that the modal is associated with. This could include details about the modal's state, the data it's displaying, or any other relevant information that might be needed to properly dismiss the modal.

The Navigation.dismissModal dismisses the modal by identifying the modal to be dismissed using a reportID. This suggests a simpler approach where the modal's identity is determined solely by its ID, without the need for additional context or information.

The choice between Navigation.dismissModalWithReport(report) and Navigation.dismissModal(reportID) depends on the specific requirements of this application. If you need to perform additional actions or checks before dismissing the modal, dismissModalWithReport(report) might be the better choice. If your dismissal logic is straightforward and only requires the modal's ID, dismissModal(reportID) could be more suitable.

I also explored other options like using a Global Modal State Management to manage the visibility of modals globally. This approach allows you to control the modal's visibility from anywhere in your application, making it easier to dismiss the modal in response to various events, not just the back button press.

**Comment by CK-codemax** [comment]
Contributor details
Your Expensify account email: whoroochuko@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01598dca7cc455581b

**Comment by CK-codemax** [comment]
> 📣 It's been a week! Do we have any satisfactory proposals yet? Do we need to adjust the bounty for this issue? 💸

Hi

I dropped this about 7 days back

I didn't get a response 
Here's it again

Refreshing the page on expense title exit page and pressing back leads to LHN

The Navigation.dismissModalWithReport solution seems really good as it goes indepth .
The report parameter suggests that it might be expecting an object that contains information about the modal or the report that the modal is associated with. This could include details about the modal's state, the data it's displaying, or any other relevant information that might be needed to properly dismiss the modal.

The Navigation.dismissModal dismisses the modal by identifying the modal to be dismissed using a reportID. This suggests a simpler approach where the modal's identity is determined solely by its ID, without the need for additional context or information.

The choice between Navigation.dismissModalWithReport(report) and Navigation.dismissModal(reportID) depends on the specific requirements of this application. If you need to perform additional actions or checks before dismissing the modal, dismissModalWithReport(report) might be the better choice. If your dismissal logic is straightforward and only requires the modal's ID, dismissModal(reportID) could be more suitable.

I also explored other options like using a Global Modal State Management to manage the visibility of modals globally. This approach allows you to control the modal's visibility from anywhere in your application, making it easier to dismiss the modal in response to various events, not just the back button press.

**Comment by roryabraham** [comment]
I agree we should revert https://github.com/Expensify/App/pull/39788 and then solve https://github.com/Expensify/App/pull/39788 in a different way. Rather than not pushing the report screen on the stack, we should make sure that pressing `Go to home screen` shows the LHN. Feels like we need a "home" route that's separate from the "report route", but only on mobile. Which gets pretty tricky to get right.

**Comment by roryabraham** [comment]
Still awaiting proposals here. Because of the low impact of this issue I'm going to make it a weekly

**Comment by roryabraham** [comment]
Great, @dominictb we look forward to reviewing your PR!

**Comment by roryabraham** [comment]
Yep, sorry about that.

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @dominictb $125
- Contributor+: @ishpaul777 $125

Please apply/request!

**Comment by dylanexpensify** [comment]
Done!
