### ISSUE TITLE
[HOLD][Track Expense] Add a visual distinction to tracked expenses

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#41012]
Problem
===
Currently, tracked expenses look identical to regular requests. This is fine, but when you have a policy expense chat with a mix of tracked and regular expenses - it is impossible to tell which ones are tracked from the money request preview. This lack of differentiation complicates the user experience, as users cannot easily identify which expenses are tracked. You can't tell in the preview / or even in the detailed view. The only indication is the title of the detailed expense view which says 'Tracking $amount for X'. This limitation hinders efficient monitoring and management of expenses

![Screenshot 2024-04-25 at 10 58 49 AM](https://github.com/Expensify/App/assets/30609178/e2e75d7b-e2a5-4d50-8972-744f6d9d9970)

![Screenshot 2024-04-25 at 11 02 21 AM](https://github.com/Expensify/App/assets/30609178/626a6368-f9ee-40f2-b148-de11a90c32eb)

Solution
===

Add some kind of indicator that this is a tracked expense on the money request preview, as well as within the detailed expense view. Some ideas might be:

Adding `* Tracked` next to Cash on the money request preview

![Screenshot 2024-04-25 at 11 08 05 AM](https://github.com/Expensify/App/assets/30609178/04c9f292-f254-4004-af6c-efcb2ef750a4)

Adding another non-editable field on the detailed transaction that just shows 'Tracked' or non-reimbursable

![Screenshot 2024-04-25 at 11 08 42 AM](https://github.com/Expensify/App/assets/30609178/6cdac09f-ebc3-48b8-a853-cfa0bc9a1136)

**Comment by thienlnam** [comment]
Discussing this here: https://expensify.slack.com/archives/C066HJM2CAZ/p1714058344133709

**Comment by isabelastisser** [comment]
On hold.

**Comment by thienlnam** [comment]
@shawnborton https://expensify.slack.com/archives/C066HJM2CAZ/p1714069351117049?thread_ts=1714058344.133709&cid=C066HJM2CAZ

Now that we've had some time to sit with this, how do we feel about adding this small indicator at the eyebrow level to distinguish between reimbursable, non-reimbursable expenses?

**Comment by shawnborton** [comment]
I still like the idea, but do you mind resurfacing this conversation in Slack for greater visibility? cc @Expensify/design (Jason, Tom) & @kevinksullivan

**Comment by shawnborton** [comment]
Any update on this one?

**Comment by thienlnam** [comment]
Closing based on the results of this conversation https://expensify.slack.com/archives/C066HJM2CAZ/p1717093147314179?thread_ts=1717091331.848439&cid=C066HJM2CAZ
