### ISSUE TITLE
 IOU - When two identical IOUs merge, a skeleton begins to flicker in the conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41013]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with 2 separate accounts in the main testing device and a secondary device
3. Send a message to the secondary device
4 Disable the internet connection in the main testing device
5. Send a manual request to the secondary device
6. From the secondary device, send the same manual request to the main device
7. Switch on the internet on the main device

## Expected Result:
When merging two identical IOUs, the skeleton in the conversation should not flicker and should disappear after merging

## Actual Result:
When two counter identical IOU's merge, a skeleton begins to flicker into the conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/010e266e-eda9-491e-84cd-a7532caf1722

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
No update yet, I've been focused on other GHs.

**Comment by alexpensify** [comment]
I'm trying to identify if this will be a common bug or if we should pause this one.

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, May 7, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

--- 

When I'm back online, I'll continue reviewing this one.

**Comment by alexpensify** [comment]
Moving back to Daily, I'll test this one later this week.

**Comment by alexpensify** [comment]
I'll test soon.

**Comment by alexpensify** [comment]
I wasn't able to get to this one over the weekend, still on my radar.

**Comment by alexpensify** [comment]
Closing - we can review this one later but this is not a common experience.
