### ISSUE TITLE
[Wave Collect][QBO] Chart of Accounts (Categories) not importing on initial connection

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41018]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714057854803539?thread_ts=1714057353.559839&cid=C036QM0SLJK

## Action Performed:
1. Connect to QBO 
2. Click Import 
3. Observe `Not imported` on the Chart of Accounts row
4. Go to the Categories page in the LHN
5. Observe the list of default categories
6. Go back to the Import page
7. Click on the Chart of Accounts row 
8. Click the toggle to "Enable newly imported Chart of Accounts"
9. Observe `Imported, displayed as tags` on the Chart of Accounts row

## Expected Result:
1. The QBO chart of accounts should be imported as categories upon establishing the connection
2. The default set of categories on the workspace should be replaced by the chart of accounts imported from QBO
3. The Chart of Accounts row in the import settings should be displayed as imported, and the push input should read: `Imported, displayed as categories`

## Actual Result:
1. The QBO Chart of Accounts aren't imported when the integration is established
2. The Categories import setting reads: "Not imported"
3. When you enable a different feature ("Enable newly imported Chart of Accounts)", the push row reads "Imported, displayed as tags"

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/5f01f4d0-f049-4b12-bec4-0f5b3652069b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @hayata-suenaga @aldo-expensify @s77rt @zanyrenney @teneeto @narefyev91 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011dbfa3b69ed9c461</li>
        <li>Upwork Job ID: 1783572498360819712</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Added internal until we determine who's going to take this one.

**Comment by trjExpensify** [comment]
@hayata-suenaga @aldo-expensify remind me which of yah are looking into this one?

**Comment by aldo-expensify** [comment]
@trjExpensify I am, and I think I know why now. There are two jobs: `sync` and `import`, right now we are only triggering `import`. I'm understanding this:

- `import`: read QBO data and put it in the `connections.quickbooksOnline.data`. This data is useful to be able to configure the connection.
- `sync`: reads the configuration of the connection, pulls data from QBO and populates the policy's Category and others.

Is this correct @francoisl 

This is an oversight in the design doc. I remember @francoisl mentioned these two jobs, but I guess I didn't understand fully the consequences until now that we are working on it.


I think we need the following:

Authentication flow:
- Authenticate with QBO ✅ 
- Run the `import` job to be able to show the configurations ✅ 
- Choose some default settings ❌ 
- Run the `sync` job to populate the policy fields used by Expensify ❌ 


Sync button flow:
- Run the `import` job (is this necessary? I see OldDot doing it) ✅ 
- Run the `sync` job ❌ 

❌ : need to implement, we are missing it
✅ : current implementation has it

@francoisl does that make sense to you?

About calling the `sync` job after the `import`, I'll see if I can trigger that follow up call directly from the IS.

**Comment by francoisl** [comment]
Yes, what you said about `import` vs `sync` is correct, you need to do a `sync` after an import.

> Are there cases where we could only want to call the `import` alone?

No. You could go the other way around but you don't need to (for example if you change the account to post your Vendor Bills to, then technically you don't need to do a pull (import), but it's fine if you do)



> About calling the `sync` job after the `import`, I'll see if I can trigger that follow up call directly from the IS.

Yes that's an option too. We do that with auto-sync, check how we do it [here](https://github.com/Expensify/Integration-Server/blob/fd0c7d89a313443/src/expensify/quickbooksonline/QuickbooksOnlineAutoSync.java#L84-L103). We can try to reuse some of that logic but it will need some changes (it throws if it's not being run in auto-sync mode, and has push notifications disabled since auto-sync typically happens in the backend)

**Comment by aldo-expensify** [comment]
I have a draft here for some changes in the IS server to reuse the autoSync job: https://github.com/Expensify/Integration-Server/pull/7880

**Comment by aldo-expensify** [comment]
Created draft PR to handle the initial load of data (sync) inside the first import when importing from QBO: https://github.com/Expensify/Integration-Server/pull/7882

**Comment by trjExpensify** [comment]
These were all backend PRs are we've merged them, can we close?

**Comment by hayata-suenaga** [comment]
I re tested and the chart of accounts are imported as categories after the initial connection. I'll close this issue now
