### ISSUE TITLE
[QBO] "Sync Now" button doesn't resync the connection

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41015]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-0
**Reproducible in staging?:** Y 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714057429194069?thread_ts=1714057353.559839&cid=C036QM0SLJK

## Action Performed:
1. Connect to QBO 
2. Click the three dots
3. Click sync now 

## Expected Result:
Clicking the `Sync now` button should re-sync the connection. 

## Actual Result:
It does nothing. 

## Workaround:
N/A 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/8f24dc1e-1770-424a-a65b-95ffc194af8d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afdbe61d2dd0f488</li>
        <li>Upwork Job ID: 1783566021470216192</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by aldo-expensify** [comment]
Removed @jjcoffee because I merged without the C+ review

**Comment by aldo-expensify** [comment]
I messed up the initial implementation, it is calling `import` when it should have been `sync`, draft PRs with the fixed implementation:



IS Draft to reuse the autoSync job: https://github.com/Expensify/Integration-Server/pull/7880
Web-E changes: https://github.com/Expensify/Web-Expensify/pull/41827
App changes: https://github.com/Expensify/App/pull/41060

I'll wait for Francois opinion before making the ready for review

**Comment by aldo-expensify** [comment]
This is fixed in staging
