### ISSUE TITLE
Sign up - An error appears in Concierge chat when pass onboarding modal with spaces

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41024]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:*(https://expensify.testrail.io/index.php?/cases/view/2616817)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign up new Gmail account
2. On onboarding modal click on the "Chat and split bills with friends" option (or another non-ws option)
3. Enter space in First and Last name fields and click Continue
4. Dismiss video

## Expected Result:
No errors in Concierge chat

## Actual Result:
There are errors in Concierge chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ce22b31d-6314-4904-8794-10d7cc7c5a8c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by marcaaron** [comment]
@francoisl maybe somehow related to https://github.com/Expensify/App/issues/38414?

We should ask QA what account they used.

I tried to repro on staging and could not.

However, I did see `OpenReport` getting called over and over again - super weird...

https://github.com/Expensify/App/assets/32969087/62fb484a-5955-4445-a591-4e38ebcc8372

**Comment by marcaaron** [comment]
Asking for re-test [here](https://expensify.slack.com/archives/C9YU7BX5M/p1714085301490139). So far, I am not sure I would block the deploy on it unless it's reliably reproducible. But also looks like a server issue.

**Comment by francoisl** [comment]
I'm able to reproduce on dev, the backend is returning `402 Missing firstName`. I'm not 100% sure anymore about the requirement to enter a first and last name, bringing it to discussion in Slack [here](https://expensify.slack.com/archives/C036QM0SLJK/p1714091848698239?thread_ts=1713799232.088539&cid=C036QM0SLJK).

**Comment by francoisl** [comment]
@marcaaron check out https://github.com/Expensify/App/pull/41047. We'll need a backend change to allow blank last names, I'll send you a PR shortly as well but then we won't need to block the deploy on that.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by kavimuru** [comment]
Error message is still reproducible. But now first name is required and throws error if not entered. 

https://github.com/Expensify/App/assets/43996225/ffa16963-56fc-4385-ab12-05c143e421d8

**Comment by francoisl** [comment]
This is normal for now, see this note in the PR (it's easy to miss it I guess)

> Note: at the moment, if you don't enter a last name, you will get an error. This will require a backend change but we don't need to block on this.

We already have a backend change in review to fix this, but for now we can mark this as passing.
