### ISSUE TITLE
[HOLD for payment 2024-05-22] [VIP VSB] New Resources to Publish - Track Expenses

### ISSUE THREAD

**Issue by CortneyOfstad** [Expensify/App#41028]
Publish Date: May 1st 2024
Tracking GHs [Track Expenses]: https://github.com/Expensify/Expensify/issues/385521
Following the steps in: https://stackoverflowteams.com/c/expensify/questions/17951

Article draft is [here](https://docs.google.com/document/d/1EdovOCPiRA5oki1R-y_9Dx6Cu0IU67bXcMRLk1X2MUI/edit?usp=sharing)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by CortneyOfstad** [comment]
Not overdue, bumping Ren today 👍

**Comment by ren-jones** [comment]
Sorry for the delay—I'm ready to be assigned!

**Comment by CortneyOfstad** [comment]
No worries — thanks @ren-jones!

**Comment by CortneyOfstad** [comment]
Hi @ren-jones! Just checking to see where we're at the PR on this. Thanks!

**Comment by CortneyOfstad** [comment]
@ren-jones bump on this as this is part of the May 1st release. Thanks!

**Comment by CortneyOfstad** [comment]
PR is ready, just waiting for merge freeze to be completed (Monday) 👍

**Comment by CortneyOfstad** [comment]
Deployed to staging 🎉

**Comment by CortneyOfstad** [comment]
Payment is handled outside of BZ, so this can be closed!
