### ISSUE TITLE
Chat - Large font size when replacing emoji with text in compose box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41026]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Enter emoji in compose box
4. Highlight the emoji and replace it with any text

## Expected Result:
Regular text font size should be displayed

## Actual Result:
Text is displayed with large font size

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2ff0e945-efa4-4e52-8d29-056be0c44353

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment]
This seems like polish. I

**Comment by zanyrenney** [comment]
These aren't even the correct emojis? I've just tried to reproduce this and I can't. These look like some kind of weird stickers?

![2024-05-01_21-13-59](https://github.com/Expensify/App/assets/56830058/c6f7e329-8c37-4193-8d7a-62a8333996cb)
