### ISSUE TITLE
Chat - Message in compose box gets highlighted when sending emojis consecutively on gmail a/c

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#41022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exp around https://expensify.testrail.io/index.php?/tests/view/4517034
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in to New Expensify with any Gmail account
2. Navigate to any chat
3. Send a message with an emoji
4. Open emoji picker and select any emoji

## Expected Result:
Emoji should be entered in compose box and it should not be highlighted

## Actual Result:
Emoji is entered in compose box but whole message is highlighted

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/ca936e50-a9ce-43e9-824e-bb5da60acb40

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb

**Comment by kavimuru** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MitchExpensify** [comment]
I am about to go OOO and will keep myself assigned to lick this back up upon return 🙇

**Comment by twisterdotcom** [comment]
I cannot recreate this, and I do not think it is worth solving unless a customer reports it.
