### ISSUE TITLE
Android - Chat - New message text is hidden under the green line when mark as unread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41025]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4516072
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Create 2 expense by using "submit expense"
4. Tap on the expense created and tap on the last created expense from IOU report page
5. In details page, hold the request
6. Unhold the request
7. Delete the request
8. Long press the hold request reason message and mark as unread

## Expected Result:
New message text must not be hidden under the green line when mark as unread the hold request reason message

## Actual Result:
New message text is hidden under the green line when mark as unread the hold request reason message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/820b118b-6979-49fe-8645-cf13ba92b0ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@arosiclair  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by arosiclair** [comment]
Can't reproduce on Android **v1.4.66-1**

<img src="https://github.com/Expensify/App/assets/6833644/ad026b74-e1cd-4481-b8d6-9ea59f273884" width="400" />
