### ISSUE TITLE
 iOS - Onboarding - Blank space between reports displayed in LHN after finishing onboarding

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41021]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in with a new account
2. After the onboarding modal appears select an option that will create a workspace
3. Complete the onboarding

## Expected Result:
There is no blank space between reports in the LHN

## Actual Result:
There is blank space between the reports in the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f95212bc-4f6b-449a-bc56-df1294bc334d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by mallenexpensify** [comment]
Unable to repro on v1.4.66-2 iOS native
Throwing `retest-weekly` on this

https://github.com/Expensify/App/assets/22508304/82cdab5c-59e5-46a0-98eb-462ce4580fab

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment]
I can't repro and neither was @mvtglobally able to, so closing
