### ISSUE TITLE
[Wave Collect][QBO] The `Vendor` push row appears before enabling `Default vendor`

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41032]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-1
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:**https://expensify.slack.com/archives/C036QM0SLJK/p1714060347910849?thread_ts=1714057353.559839&cid=C036QM0SLJK

## Action Performed:
1. Connect to QBO
2. Go to `Export` > `Export company cards as`
3. Choose `Vendor bill` for export
4. Observe the `Vendor` row appears 

## Expected Result:
The `Vendor` row should only show if the admin enables the `Default vendor` toggle. 

## Actual Result:
The `Vendor` row appears despite the toggle being disabled. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

NewDot:

https://github.com/Expensify/App/assets/16232057/0b00e668-1d2b-4278-bdd6-0e56fb8be752

P.S ignore the errors, we're working on them elsewhere. 

OldDot for reference as comparison:

https://github.com/Expensify/App/assets/16232057/17591250-0299-4ac4-94a7-fc1eb7f9a2ff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
CC: @narefyev91 can you comment and take this one as follow-up? Thanks!

**Comment by narefyev91** [comment]
Yes will take it

**Comment by trjExpensify** [comment]
Thanks!

**Comment by trjExpensify** [comment]
@narefyev91 I just spotted this one as well: 

`Account >` is showing before `Credit card` or `Debit card` is selected as well. Can you take that here at the same time? 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/859020ed-00ec-48ec-9d86-e7762ff3759c">

**Comment by tgolen** [comment]
# Weekly Update
- [The PR](https://github.com/Expensify/App/pull/41079) was put on HOLD until https://github.com/Expensify/Expensify/issues/390731 is finished to make the API 1:1:1

### Next Steps
- @hayata-suenaga and @aldo-expensify will work on https://github.com/Expensify/Expensify/issues/390731 and get that merged
- Then https://github.com/Expensify/App/pull/41079 can be taken off HOLD and continue to be reviewed

#### ETA
- Everything merged by Friday, May 10

**Comment by aldo-expensify** [comment]
While working on https://github.com/Expensify/Expensify/issues/390731, I fixed the inputs in the page "Export company card as" as they were very wrong and buggy, so this issue may be solved by https://github.com/Expensify/App/pull/41627

**Comment by trjExpensify** [comment]
Makes sense.

**Comment by tgolen** [comment]
# Weekly Update
- The [previous App PR](https://github.com/Expensify/App/pull/41079) from the contributor was closed.
- The API is still being worked on to provide multi-option support
- This [new App PR](https://github.com/Expensify/App/pull/41627) will implement the new API changes

### Next Steps
- @aldo-expensify and @hayata-suenaga continue working to get [the API changes](https://github.com/Expensify/Expensify/issues/390731) merged
- @aldo-expensify implement the front-end changes

### ETA
- Everything merged by May 17th.

@aldo-expensify do you think this ETA is doable or do you have a better estimate?

**Comment by hayata-suenaga** [comment]
@tgolen, I believe we're just waiting for this final [App PR](https://github.com/Expensify/App/pull/41627) to be deployed to staging 😄

**Comment by trjExpensify** [comment]
This has been fixed elsewhere, so I think we can close this issue now.
