### ISSUE TITLE
Android - Workspace-Closing the error message "unable to add members to WS", deletes the WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab -- create a new workspace
3. Tap members invite
4. Invite a VOIP number +916541237890
5. Note user not added
6. Tap invite button again, note the red dot below and invite the user again
7. Note user is not added
8. Tap back button and note 2 error message "unable to add members to Workspace"
9. Tap cross button and close the error message

## Expected Result:
Closing the error message "unable to add members to Workspace", must not delete the workspace

## Actual Result:
Closing the error message "unable to add members to Workspace", deletes the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4ca18dff-85e3-48f8-988a-4d6de25c5812

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by muttmuure** [comment]
Closing in favor of the other issue
