### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] [QBO] "Last synced just now" text doesn't update

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41045]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714057390428649?thread_ts=1714057353.559839&cid=C036QM0SLJK

## Action Performed:
1. Connect to QBO 
2. Observe the "Last synced just now" text
3. Go have a coffee for 10mins
4. Come back 
5. Observe the text still reads "Last synced just now" 

## Expected Result:
On OldDot the way we handle it is by checking the `lastSync` timestamp from the policy on page load, and then compute a human-friendly time difference with it. Every time you/auto-sync syncs the connection it's updated [here](https://github.com/Expensify/Integration-Server/blob/9b919b9cb21c05d20927b6c6037a85baf7d38a9b/src/expensify/quickbooksonline/QuickbooksOnlineImporter.java#L198). 

## Actual Result:
Despite hours elapsing the text still reads: "Last synced just now" even after a page refresh, suggesting this is just a static value currently. 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/f7861ae3-702c-4ccd-9c76-978b6d27496d">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @hayata-suenaga @aldo-expensify @teneeto @narefyev91 @zanyrenney
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f30631fa560635c</li>
        <li>Upwork Job ID: 1783647518731452416</li>
        <li>Last Price Increase: 2024-04-26</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Haven't moved this on, as I think we might need to hold on: 

https://github.com/Expensify/Web-Expensify/pull/41822
https://github.com/Expensify/App/pull/41044

**Comment by trjExpensify** [comment]
Confirmed we don't need a hold on those PRs, moving it on.

**Comment by aldo-expensify** [comment]
> BE should return new value to indicate the lastSync timestamp (SyncPolicyToQuickbooksOnline command). We need to update it optimistically too

@tienifr you can get the value from `policy.connections.quickbooksOnline.lastSync.successfulDate`

<img width="1242" alt="image" src="https://github.com/Expensify/App/assets/87341702/117442ef-456a-4dda-8f07-b8685cb5dbc9">

**Comment by teneeto** [comment]
Hi, I'm Eto from Callstack - expert contributor group - and I would like to take care of this issue.

**Comment by trjExpensify** [comment]
@tienifr, can we use `DateUtils.datetimeToRelative( )` (like [here](https://github.com/Expensify/App/blob/e28047876767a404d845390ad670058894e6cbe6/src/components/LocaleContextProvider.tsx#L90)) and add "Last synced" before that string for the human readable message to display?

**Comment by trjExpensify** [comment]
Let's have the proposal reviewed. 

CC: @mountiny for vis as I was just talking to yah about this one

**Comment by trjExpensify** [comment]
@mountiny you happy with this proposal? Let's get a PR up for it.

**Comment by mountiny** [comment]
@tienifr please go ahead and raise the PR

**Comment by trjExpensify** [comment]
Commented in the PR that's held, I think we can switch the base and merge it into the QBO branch

**Comment by mountiny** [comment]
Done

**Comment by trjExpensify** [comment]
Solid, thank yah!

**Comment by trjExpensify** [comment]
We won't need a regression test for this, as they'll be added centrally with the QBO project. 

Payment summary as follows: 

- $250 to @tienifr for the fix
- $250 to @Ollyws for the C+ review

@Ollyws feel free to send a request, @tienifr I've paid you in Upwork. Closing!

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
