### ISSUE TITLE
[$250] [hold for payment 2024-05-29] Description is not shown on the invoice report preview

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#41061]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Start Send invoice flow from the Global Create
2. Add a description to the invoice transaction
3. Confirm the invoice and send it

## Expected Result:
You should land in the invoice room with the invoice preview containing the transaction description

## Actual Result:
Transaction description is missing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
The description highlighted below is not shown

<img width="456" alt="Screenshot 2024-04-26 at 10 09 24" src="https://github.com/Expensify/App/assets/18078393/ede6385b-44d5-452b-9441-cc8ae69c9ef9">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166b297f81fb8e2a7</li>
        <li>Upwork Job ID: 1795490195010527232</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by cristipaval** [comment]
I need to address some change requests on the fix PR

**Comment by joekaufmanexpensify** [comment]
Sounds good!

**Comment by cristipaval** [comment]
@danielrvidal could you please help prioritise? 🙏

**Comment by danielrvidal** [comment]
Yup, this is a Critical, so let's prioritize please.

**Comment by joekaufmanexpensify** [comment]
Per [this thread](https://expensify.slack.com/archives/CSL3XBCCR/p1714501900777179?thread_ts=1714442965.405579&cid=CSL3XBCCR), this one is internal and @cristipaval has a PR up for it. 

LMK if there's anything I can help with though!

**Comment by danielrvidal** [comment]
Yup, @cristipaval is working on this one and hopefully will have a PR to review tomorrow.

**Comment by joekaufmanexpensify** [comment]
Sweet, I see PR is in review!

**Comment by joekaufmanexpensify** [comment]
Looks like last PR will be unheld after today's auth deploy

**Comment by cristipaval** [comment]
> Looks like last PR will be unheld after today's auth deploy

correct

**Comment by cristipaval** [comment]
Web-E deploy did not happen yesterday. Let's hope it will happen today.

**Comment by cristipaval** [comment]
Web-E PR has been deployed. [App PR](https://github.com/Expensify/App/pull/41538) is ready for review

**Comment by joekaufmanexpensify** [comment]
App PR still in review

**Comment by joekaufmanexpensify** [comment]
PR is approved and pending merge after merge freeze. Moving to weekly for now, since this should be merged on Monday!

**Comment by joekaufmanexpensify** [comment]
Last PR merged today!

**Comment by joekaufmanexpensify** [comment]
PR on staging

**Comment by cristipaval** [comment]
Everything is into prod.

**Comment by joekaufmanexpensify** [comment]
Payment is due tomorrow. Automation did not work

**Comment by joekaufmanexpensify** [comment]
Only payment here is $250 to @ishpaul777 for C+ review via upwork.

**Comment by joekaufmanexpensify** [comment]
@ishpaul777 offer sent for $250!

**Comment by joekaufmanexpensify** [comment]
Course!

**Comment by joekaufmanexpensify** [comment]
@ishpaul777 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
