### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] IOU - User is stuck on the same page after navigating to IOU preview link twice offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go offline.
3. Submit two expenses to a user.
4. Go to expense report.
5. Right click on any expense preview > Copy link.
6. Paste the link and send it.
7. Click on the same link twice.
8. Attempt to go back via back button on the top left.

## Expected Result:
User is able to go back to previous page.

## Actual Result:
User is stuck on the same page after navigating to IOU preview link twice in offline mode.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ea57dd33-7a64-4df5-a91a-00b4579759cd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016d14b52b4d7afaf4</li>
        <li>Upwork Job ID: 1785888211431084032</li>
        <li>Last Price Increase: 2024-05-09</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by strepanier03** [comment]
I can't repro with Mac OS/Chrome. Gonna try with Android:Native.

**Comment by strepanier03** [comment]
Okay, able to repro on Android.

**Comment by strepanier03** [comment]
Urgency is polish and this is unlikely to be worked on for a week or so at best.

**Comment by narefyev91** [comment]
Hey! I'm Nicolay from Callstack - will check this issue - please assign to me

**Comment by strepanier03** [comment]
Thank you @narefyev91 - Assigned.

**Comment by narefyev91** [comment]
Found a root case of the issue - will provide fix PR today

**Comment by strepanier03** [comment]
@dukenv0307 - I've paid you and closed the contract, thanks!

Closing this out now.
