### ISSUE TITLE
[Wave Collect] [Guided Setup] The system chat report is missing participants 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#41064]
### Problem

For the Guided setup onboarding flow in the App, we are creating a new type of read-only system chat report. This report should include 2 participants. You as a user and special notification@expensify.com account, it acts as a DM between these two users.

The report is returned in the OpenApp call, however, it shows as if it has no participants. @burczu pointed out in this [internal thread](https://expensify.slack.com/archives/C036QM0SLJK/p1714053982341529?thread_ts=1713799253.669479&cid=C036QM0SLJK).

### Why is it important

As there are no `participants`, the chat does not show in the LHN and also other logic which relies on the fact the chat report has correct `participants` field.

### Solution

Update the GetChats command to return the list of participants correctly.

**Comment by mountiny** [comment]
PR is up, but holding if for now to decide how to handle the system chat report in App until its polished

**Comment by trjExpensify** [comment]
I think we're done here, right. Can we close it? CC: @flodnv

**Comment by flodnv** [comment]
I think so
