### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] Task - Deleted #admins room displayed in share somewhere when creating task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4516164
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in
2. Create a workspace
3. Add some message to #admins room
4. Tap FAB > Assign task
5. Create a task and share in the #admins room
6. Delete the workspace
7. Tap FAB > Assign task
8. Open Share somewhere on the task confirmation screen

## Expected Result:
#Admins room from the deleted workspace is not displayed

## Actual Result:
#Admins room from the deleted workspace is displayed and can be selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c6509d83-2b77-4774-936f-4399e5494085

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190dd051f8a814833</li>
        <li>Upwork Job ID: 1784888107450617856</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by c3024** [comment]
@parasharrajat I can take this if you are OOO and have limited capacity. [(context)](https://expensify.slack.com/archives/C02NK2DQWUX/p1714570416313749)

**Comment by garrettmknight** [comment]
@c3024 you're up!

**Comment by c3024** [comment]
@tienifr 's [proposal here](https://github.com/Expensify/App/issues/41062#issuecomment-2079040625) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @tienifr $250 paid via upwork
- Reviewer: @c3024 $250 paid via upwork

**Comment by garrettmknight** [comment]
@c3024 can you complete the checklist when you get a minute?

**Comment by garrettmknight** [comment]
Done!
