### ISSUE TITLE
Room - Flickering it's not here error when opening a room mention without access

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41073]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/40506
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Account A: Log in with an expensifail account
2. Account A: Create a workspace
3. Account A: Create a room with the default settings
4. Account A: Invite a new Gmail account to the room
5. Account A: Mention #announce in the created room
6. Account B: Log in and open the room
7. Account B: Tap on the announce mention

## Expected Result:
The page with the error shouldn't flicker.

## Actual Result:
Flickering Hmm it's not here error when opening a room mention without access.
It always happens for the first tap, but you have to navigate back and to the mention again to repro the error for the second try. It also happens when you navigate to the announce room through a link.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/daa109b8-a0db-4521-92ef-b0c6b2c3f794

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment]
This is the same as https://github.com/Expensify/App/issues/40629, I think we can close it
