### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] Taxes - Tax exceeding limit is saved instead of showing error in tax input editor

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41075]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Collect workspace has enabled tax.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Submit expense > Manual.
4. Click 'Show more' at bottom to show tax enabling option. 
5. Select a non-zero tax rate.
6. Click Tax amount in confirmation page.
8. Enter amount exceeding the limit.
9. Note that error shows up in the tax input editor.
10. Click back arrow at top. 
11. Create the expense.
12. Go to transaction thread.
13. Click Tax amount.
14. Enter amount exceeding the limit and save it.

## Expected Result:
Error will show up in the tax input editor.

## Actual Result:
The exceeding tax amount is saved, and error shows up in transaction thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f233e941-5b5d-4422-8dbf-c5a0081bed67

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c9f037136424e8d</li>
        <li>Upwork Job ID: 1783999186300325889</li>
        <li>Last Price Increase: 2024-04-26</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by mallenexpensify** [comment]
Updated steps in OP for clarity. Was able to reproduce. 
@Ollyws please review the proposal above.   
Added to #wave-collect.

**Comment by mallenexpensify** [comment]
Contributor: @Krishna2323 paid $250 via Upwork
Contributor+: @Ollyws owed $250 via Upwork

@Ollyws can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~010c9f037136424e8d

Can you please fill out the BZ checklist too?  Thx

**Comment by mallenexpensify** [comment]
@Ollyws paid, payment comment updated above.  
Thanks @Krishna2323 for the PR link.  Can you post the BZ checklist when you have a min @Ollyws

**Comment by mallenexpensify** [comment]
Thanks @Ollyws , TR GH created
https://github.com/Expensify/Expensify/issues/397353
