### ISSUE TITLE
Taxes - Error when saving 0 tax amount and it is saved when hitting Save button again

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41072]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Collect workspace has tax enabled.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense with tax.
4. Go to transaction thread.
5. Click Tax amount.
6. Change the tax amount to 0.
7. Click Save.
8. Click Save again.

## Expected Result:
App will save 0 as tax amount when saving it for the first time.

## Actual Result:
App shows error when saving 0 tax amount for the first time, and it is saved when hitting Save button again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/49659a6c-a029-483b-8b22-c4dbae0448fd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by alexpensify** [comment]
No update yet, I've been focused on other GHs.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience and was able to save without an error 
![2024-05-02_11-05-30](https://github.com/Expensify/App/assets/8107070/5ac6b1ae-5c97-4b28-98b2-7f53b02357c4)
