### ISSUE TITLE
Chat - Composer field is cut off if user edit the last message in the chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41070]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4517267
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Login with any account in staging.new.expensify.com or Desktop App
2. Open any chat
3. Edit last message

## Expected Result:
Composer field is shown in full in edit mode

## Actual Result:
Composer field is cut off at the bottom if user edit the last message in the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/377c070c-2627-4191-81b8-4f2088a8e3df

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by CortneyOfstad** [comment]
Couldn't recreate under staging on browser:

https://github.com/Expensify/App/assets/10926327/ce2d9cdb-39f0-4dcb-9c57-1e6db4c4d354

Couldn't recreate in the app either:

https://github.com/Expensify/App/assets/10926327/a07bf6fd-94a1-49ba-9f4f-feafd32c1ea5

**Comment by slafortune** [comment]
Couldn't recreate in production either
