### ISSUE TITLE
[$250] Expense - Combined report in LHN is always bolded after modifying transaction

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat with no unsettled expense.
3. Create an expense.
4. Go to combined report.
4. Pin the report to LHN.
5. Note that the report in LHN is not bolded.
6. Go to combined report and modifying any field.
7. Note that LHN is bolded.
8. Go back and forth between other chat and the combined report.
9. Note that the combined report in LHN is still bolded.

## Expected Result:
In Step 8, since there is no unread messages in the combined report, the combined report in LHN will not be bolded.

## Actual Result:
After modifying transaction details, the combined report in LHN is always bolded.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a13b7995-2ecd-4397-8dc2-201b3209eff1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01471012e33a8b1fcb</li>
        <li>Upwork Job ID: 1783842500724846592</li>
        <li>Last Price Increase: 2024-04-26</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
This seems like the culprit https://github.com/Expensify/App/pull/40676

**Comment by mountiny** [comment]
testing a revert

**Comment by mountiny** [comment]
@tienifr could we instead in the frontend consider only the report actions for the expense report when comparing the timestamps? 

So when we compare the `lastReadTime` to know if we should show the report as bold/ unread, we will only consider the expense report actions?

**Comment by mountiny** [comment]
Alright, I am going to revert that PR as I have confirmed it fixes this issue and then @nkdengineer please consider this regression in your follow up issue 
<img width="1207" alt="image" src="https://github.com/Expensify/App/assets/36083550/10db6d7a-07b2-47c4-b27a-1f16227fe61a">

**Comment by mountiny** [comment]
Yeah, I assume we need to look into this from the backend perspective too cc @NikkiWines for visibility

Here is a straight revert https://github.com/Expensify/App/pull/41099

**Comment by iwiznia** [comment]
This is not fixed yet, seems the PR is being worked on still

**Comment by NikkiWines** [comment]
Sorry for the delay - I'll look into implementing a fix for updating the `lastReadTime` for the transactionThreadReport when we open a one-expense report. Shouldn't be too tricky 🍀

**Comment by CortneyOfstad** [comment]
Thanks @NikkiWines!

**Comment by NikkiWines** [comment]
Took a look at this with https://github.com/Expensify/App/pull/42005 checked out as well, since that modifies the LHN view for one-transaction reports and I'm not able to reproduce the bug. 

https://github.com/Expensify/App/assets/16747822/7516549c-ea5b-450d-b6db-90631f4ac2b0

However, I did experience a separate bug involving the unread indicator not consistently working for the one-transaction view (particularly for system messages). I'll see if there's a separate bug report for that.

I guess let's wait for https://github.com/Expensify/App/pull/42005 to be deployed and confirm if the bug still exists on staging / prod and we can go from there

**Comment by CortneyOfstad** [comment]
Sounds good — thanks @NikkiWines!

**Comment by iwiznia** [comment]
@kbecciv can you check if this bug is still present please?

**Comment by CortneyOfstad** [comment]
Bump @kbecciv ^^^ thanks!

**Comment by kbecciv** [comment]
@iwiznia @CortneyOfstad Checking

**Comment by kbecciv** [comment]
Not reproducible

https://github.com/Expensify/App/assets/93399543/4eaa654d-0c96-484c-9e5c-6d080930bd31

**Comment by CortneyOfstad** [comment]
Thanks @kbecciv! Going to close!
