### ISSUE TITLE
[$250] Approve - "Waiting for you to pay" message appears briefly for approver after approving report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41081]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR:** https://github.com/Expensify/App/pull/40532
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Collect workspace has another user as approver.

1. Go to staging.new.expensify.com
2. [Admin] Go to workspace chat.
3. [Admin] Create an expense and submit the report.
4. [Approver] Go to transaction thread.
5. [Approver] Click Approve button.

## Expected Result:
Approver will not be presented with this Next step message "Waiting for you to pay these expenses".

## Actual Result:
"Waiting for you to pay these expenses" message appears briefly for approver after approving the report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d2aad5cf-cfb5-4538-8c2c-9dd65c6080e1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e61cf7fb38074ac</li>
        <li>Upwork Job ID: 1785010427319132160</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by eh2077** [comment]
Commented in the related PR to confirm if this is a legit regression

**Comment by eh2077** [comment]
reviewing proposals

**Comment by eh2077** [comment]
When owner and approver are the same person, the behaviour is same as described in this issue (owner and approver are different) after clicking the `Approve` button - Show `Waiting for you to pay these expenses.` and then `No further action required!`


https://github.com/Expensify/App/assets/117511920/0987915b-3a16-4ef2-bb4c-4373aa1872b8

@muttmuure Can you help to clarity the expected behaviours here?

- Case 1: If the owner and approver are different, what should be the next message?
- Case 2: if the owner and approver are same person, what should be the next message?

Note: currently both cases show `Waiting for you to pay these expenses.` briefly and then show `No further action required!`

**Comment by muttmuure** [comment]
Will chat with Tom

**Comment by muttmuure** [comment]
The owner isn't a factor here, the owner is the person who owns billing

**Comment by muttmuure** [comment]
https://expensify.slack.com/archives/C036QM0SLJK/p1714555601945619

**Comment by eh2077** [comment]
@muttmuure So in both cases the next step message will be `No further action required!` right?

**Comment by muttmuure** [comment]
Make or track payments is enabled, so there should be an action to pay, it just depends who it is - I will revert back soon

**Comment by eh2077** [comment]
> Make or track payments is enabled, so there should be an action to pay, it just depends who it is - I will revert back soon

@muttmuure Sorry,  the expected results are still not clear to me. Looking forward to your update, thanks.

**Comment by eh2077** [comment]
Waiting for update from @muttmuure

**Comment by muttmuure** [comment]
If Make and track payments **is** enabled but no bank account is connected, the message `Waiting for you to pay these expenses` should be showing for all admins.

So the unexpected behavior here is that `No further action required` is showing at all. It should be `Waiting for you to pay these expenses`

**Comment by eh2077** [comment]
@muttmuure Thank you for making that clear. 

@GandalfGwaihir Can you update your proposal based on @muttmuure 's comment ^?

**Comment by eh2077** [comment]
@GandalfGwaihir Friendly bump!

**Comment by eh2077** [comment]
> The bug here is for approver (The person who is an approver but not the admin/owner of the workspace). In this case we optimistically set the message to Waiting for you to pay these expenses and then the BE returns no actions needed (which is right as the approver doesn't have the authority to pay the expense as he is neither the admin nor owner).

This makes sense to me if we only want to fix this specific use case.

But I think it'll be better to fix https://github.com/Expensify/App/issues/41081#issuecomment-2098033539 together as they're relevant. 

@GandalfGwaihir What do you think?

cc @muttmuure

**Comment by eh2077** [comment]
@GandalfGwaihir Thanks for the update!

I think we can go with @GandalfGwaihir 's [proposal](https://github.com/Expensify/App/issues/41081#issuecomment-2080206220) to move this issue forward. 

Apart from fixing the specific case as described by this issue, I think we can also fix similar [cases](https://github.com/Expensify/App/issues/41081#issuecomment-2098033539) together. Yes, these [cases](https://github.com/Expensify/App/issues/41081#issuecomment-2098033539) also need backend fix.


🎀👀🎀 C+ reviewed

**Comment by yuwenmemon** [comment]
As mentioned [here](https://github.com/Expensify/App/pull/42389#issuecomment-2143023244), this issue was fixed by another PR while this one was on hold for the merge freeze. We'll still pay @GandalfGwaihir and @eh2077 for their fix though cc @muttmuure (https://stackoverflowteams.com/c/expensify/questions/8719)

**Comment by muttmuure** [comment]
All paid up
