### ISSUE TITLE
[hold for payment 2024-05-15] [Polish][QAB] Add GPS data to Scan requests started in the QAB flow.

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#41098]
**Problem**
When creating a Scan Request through the QAB flow, we often skip the final confirmation. In these cases, we do not retrieve/store GPS details in the transaction, like we do for non-QAB cases

**Solution**
Fix it
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6583547201ea2ae</li>
        <li>Upwork Job ID: 1783850550147932160</li>
        <li>Last Price Increase: 2024-04-26</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by joekaufmanexpensify** [comment]
Automation did not work here. PR went to prod last week. Payment due on 2024-05-15

**Comment by joekaufmanexpensify** [comment]
All set to issue payment! Only payment here is $250 to @Pujan92 for C+ review via Upwork

**Comment by joekaufmanexpensify** [comment]
@Pujan92 offer sent for $250!

**Comment by Pujan92** [comment]
Accepted, Thanks @joekaufmanexpensify

**Comment by joekaufmanexpensify** [comment]
@Pujan92 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set. TY everyone!
