### ISSUE TITLE
Hover Effect Lost in Notification Preferences

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause-Internal team

## Action Performed:
1, Navigate to any chat and click the header.
2, Go to Notification Preferences.
3, Scroll up or down to the end.
4, Observe the blue border appearing and the hover effect being lost.
5, Note that clicking Enter selects without highlighting.

## Expected Result:
No blue border should be displayed when scrolling to the end. and The hover effect should remain intact.

## Actual Result:
The blue border appears when scrolling to the end, the hover effect is lost, and clicking Enter selects without the hover effect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/809a019a-abfd-457f-b549-45f0bd4471de

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by sakluger** [comment]
I also cannot reproduce in Staging. When I use the down arrow and get to the last row, it loops around to the top, and the same happens when I use the up arrow and reach the top (it loops around do the bottom).
