### ISSUE TITLE
[$250] [Live Markdown] Does not recognize blank quoted lines

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#41107]
Live markdown does not recognize blank quoted lines
Actual
![image](https://github.com/Expensify/App/assets/30609178/37f81cf6-d999-4cce-bfe7-32b5af3ba8ec)

Expected
![image](https://github.com/Expensify/App/assets/30609178/bee87cbb-e829-436a-acca-01f231756955)

cc @tomekzaw 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad3446a3440e57ed</li>
        <li>Upwork Job ID: 1783911251734421504</li>
        <li>Last Price Increase: 2024-05-10</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by skyweb331** [comment]
Duplicated issue https://github.com/Expensify/App/issues/40571

**Comment by hungvu193** [comment]
@jjcoffee Can you confirm the [above comment](https://github.com/Expensify/App/issues/41107#issuecomment-2080030698)?

**Comment by jjcoffee** [comment]
@hungvu193 This is not a duplicate as far as I can tell, the other issue doesn't relate to Live Markdown.

**Comment by skyweb331** [comment]
@hungvu193 I am sorry. https://github.com/Expensify/App/issues/40571 is to parse HTML to MarkDown correctly.
This issue is parsing Markdown to HTML.
I will submit the proposal soon.

**Comment by skyweb331** [comment]
As far as I investigated, this is related to https://github.com/Expensify/react-native-live-markdown

**Comment by KartikeyNamdev** [comment]
To fix this, you can try inserting an invisible character in place of the empty line.

**Comment by hungvu193** [comment]
> To fix this, you can try inserting an invisible character in place of the empty line.

Thank you. Please post a proposal following our [contributing guides](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) here

**Comment by trjExpensify** [comment]
@thienlnam are you expecting someone from SWM to pick this up?

**Comment by thienlnam** [comment]
@robertKozik Any interest in this one or should we just leave it as external?

**Comment by robertKozik** [comment]
Hi @thienlnam , I need to get past the finish line with other quote related task, so until then we can keep it as external. If no proper proposal would came up until then, I'll take this one as well.  What do you think about such solution?

**Comment by thienlnam** [comment]
Sure, that sounds good - we're still open for proposals then!

**Comment by trjExpensify** [comment]
Awaiting proposals!

**Comment by trjExpensify** [comment]
@robertKozik any chance you're through the quote related task to pick up this one now?

**Comment by robertKozik** [comment]
I should be able to pick it by the end of the week

**Comment by trjExpensify** [comment]
Thanks, @robertKozik. Let us know here and we'll assign you.

**Comment by trjExpensify** [comment]
SOLD! 😄

**Comment by trjExpensify** [comment]
Awaiting a PR now, Melvin.

**Comment by trjExpensify** [comment]
@BrtqKr do you have a PR for this one yet?

**Comment by BrtqKr** [comment]
@trjExpensify turns out it requires changes to the blockquote regex in ExpensiMark, someone from our team will take a look and we'll pass it to further if everything is fine https://github.com/Expensify/expensify-common/pull/706

**Comment by thienlnam** [comment]
I can't find the conversation where it was discussed, but I think we landed on a spot where it is intentional that we don't limit the amount of nested quotes in the input

However, the styling of block quotes can be addressed in a separate ticket

**Comment by thienlnam** [comment]
We've merged the [PR](https://github.com/Expensify/expensify-common/pull/706) for this issue, we'll need to have another PR that bumps the expensify-common version in App to complete this issue.

I'll create another App issue to address the padding in nested block quotes

**Comment by trjExpensify** [comment]
Second PR in review.

**Comment by trjExpensify** [comment]
Oh wait.. that's a different issue. Do we have the PR for bumping expensify-common, @thienlnam?

**Comment by trjExpensify** [comment]
Meaning.. we close this issue or something else? The first PR didn't have a C+, so I think we can close if there's nothing more to do.

**Comment by BartoszGrajdek** [comment]
> Meaning.. we close this issue or something else?

I believe so, the fix is already on staging (on prod too I think), you can try testing it out yourself 🙌🏻

**Comment by thienlnam** [comment]
We can close here - looks like everything was handled by expert contributors or internal reviewers
