### ISSUE TITLE
[PAY TODAY] [$250] Can't drag mouse to select text in input

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#41104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Prod

## Action Performed:
- Start to create a group chat
- Type the name of someone to filter results
- Click 'Add to group'
- Try to drag the cursor across the text input

## Expected Result:
- The page starts to swipe away 

## Actual Result:
- The page should remain static when dragging in the input field 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/10736861/a31c7844-df63-4f48-92fc-dd7ae97282e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f4130ede9fb97f6</li>
        <li>Upwork Job ID: 1784836362659282944</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment]
@Krishna2323, thanks for the proposal.

I think we just need to pass `shouldInterceptSwipe` only if it is part of top tab navigator rather than pass it by default, and this what we do in [OptionsSelector](https://github.com/Expensify/App/blob/f88ad1b932d418e543590d475c26d62acadbbc6f/src/components/OptionsSelector/BaseOptionsSelector.js#L532).

@Krishna2323's alternative proposal https://github.com/Expensify/App/issues/41104#issuecomment-2079752142 looks good.

🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment]
> I think we just need to pass shouldInterceptSwipe only if it is part of top tab navigator rather than pass it by default, and this what we do in [OptionsSelector](https://github.com/Expensify/App/blob/f88ad1b932d418e543590d475c26d62acadbbc6f/src/components/OptionsSelector/BaseOptionsSelector.js#L532).

Sounds good to me 👍

**Comment by ahmedGaber93** [comment]
@strepanier03 This issue is ready for payment

**Comment by strepanier03** [comment]
Sure thing, I was ooo last week and the failed automation really made this fall through the cracks. 

Will finish today.

**Comment by strepanier03** [comment]
Okay, both jobs are paid and contracts closed. Thanks again for the ping in Slack, always good idea to do that when the automation fails. So sorry for the delay as well, not fair to you two.
