### ISSUE TITLE
Task - No bottom padding for Confirm task button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41100]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Click on the FAB > Assign task
3. Enter the name of the task and proceed to the next screen

## Expected Result:
The bottom padding is present for the Confirm task button as for other buttons

## Actual Result:
There is no bottom padding for the Confirm task button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7eb045a8-2b0d-4124-b6bf-685ab6e83bba

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by garrettmknight** [comment]
Holding for a fix in https://github.com/Expensify/App/issues/36038

**Comment by garrettmknight** [comment]
Adding https://github.com/Expensify/App/issues/40827 to the HOLD

**Comment by garrettmknight** [comment]
Still holding

**Comment by luacmartins** [comment]
PR has been merged and I think this should be fixed.

**Comment by garrettmknight** [comment]
All fixed!
