### ISSUE TITLE
[HOLD for payment 2024-05-31] [HIGH] [VIP Travel] Add Workspace Address context - newDot

### ISSUE THREAD

**Issue by twisterdotcom** [Expensify/App#41119]
We added `Workspace Address` for Spotnana (because it is a required field for provisioning an `Organization` and it's member travellers and admins).

NewDot: (Mock)
![image](https://github.com/Expensify/Expensify/assets/9133401/07f6b085-1c8a-44ed-a648-ceb15fed1ab0).

We did this here: https://github.com/Expensify/App/pull/38381

We want to add some subtext, already agreed upon internally here: https://github.com/Expensify/Expensify/issues/390977

>A Workspace Address is required to enable Expensify Travel. Please enter an address associated with your business.

@pecanoro how is this?
>Se requiere una dirección para habilitar Expensify Travel. Por favor, introduce una dirección asociada con tu negocio.

![image](https://github.com/Expensify/App/assets/9133401/ed4331d4-afa6-44f6-ae57-3b73dc7688d9)

**Comment by twisterdotcom** [comment]
Why do we need Puneet here?

**Comment by puneetlath** [comment]
I think it auto-adds a BZ to NewFeature GH issues in the App repo.

**Comment by smelaa** [comment]
Hi, my name is Aleksandra Smela, I am from Software Mansion and I would like to work on this issue.

**Comment by pecanoro** [comment]
> Se requiere una dirección para habilitar Expensify Travel. Por favor, introduce una dirección asociada con tu negocio.

**Comment by twisterdotcom** [comment]
@smelaa just to make sure you saw that. I updated the OP too with it. Thanks @pecanoro!

**Comment by marcochavezf** [comment]
Assigning @ikevin127 as C+ reviewer

**Comment by twisterdotcom** [comment]
Payment Summary: 
- @ikevin127 paid $500 [here](https://www.upwork.com/nx/wm/offer/102541903) - (C+)
- @smelaa does not require payment (Contractor) - (Contributor)

**Comment by ikevin127** [comment]
@twisterdotcom Offer accepted!

**Comment by twisterdotcom** [comment]
Paid!
