### ISSUE TITLE
[$250] Crash: CameraDeviceDetails.getFormats

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#41114]
Version 1.4.61-8 

https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/ac356c1f04f50921493d0fd059b6b27b?time=last-seven-days&types=crash&sessionEventKey=662569CB0118000144FF188BE7D3E709_1938851122119613957

```
Fatal Exception: java.lang.IllegalArgumentException
lower must be less than or equal to upper
android.util.Range.<init> (Range.java:59)
com.mrousavy.camera.core.CameraDeviceDetails.getFormats (CameraDeviceDetails.java:125)
com.mrousavy.camera.core.CameraDeviceDetails.toMap (CameraDeviceDetails.java:79)
com.mrousavy.camera.CameraDevicesManager.getDevicesJson (CameraDevicesManager.kt:87)
com.mrousavy.camera.CameraDevicesManager.sendAvailableDevicesChangedEvent (CameraDevicesManager.kt:94)
com.mrousavy.camera.CameraDevicesManager$initialize$1.invokeSuspend (CameraDevicesManager.kt:71)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
```
Galaxy Tab4 10.1 | android 5.0.2
Galaxy J3(2016) | android 5.1.1

https://expensify.slack.com/archives/C035J5C9FAP/p1714158787326989
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a05a47ea7774fcf</li>
        <li>Upwork Job ID: 1783939673638330368</li>
        <li>Last Price Increase: 2024-04-26</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by thienlnam** [comment]
Posted to the Margelo room to see if they are interested https://expensify.slack.com/archives/C035J5C9FAP/p1714158787326989

**Comment by mananjadhav** [comment]
I think we should use the latest beta. cc - @mrousavy Considering you've upgraded this lib in one of the recent PRs.

🎀 👀 🎀 C+ reviewed.

**Comment by mrousavy** [comment]
Yup - I fixed this in latest VisionCamera V4! :)

**Comment by mananjadhav** [comment]
Thanks for confirming. All yours @aldo-expensify

**Comment by aldo-expensify** [comment]
> latest beta

Why do we prefer the latests beta? isn't that more risky?

**Comment by mrousavy** [comment]
Latest V4 stable (4.0.1), not beta

**Comment by mananjadhav** [comment]
> Why do we prefer the latests beta?

We don't always but we had some fixes on the latest beta for one of the previous PRs. But it looks like we can update to latest stable 4.0.1 here.

**Comment by mrousavy** [comment]
No we don't. I fixed this in V4 stable already.

**Comment by mrousavy** [comment]
Hm seems like that patch contains a bunch of other stuff as well, not only the Formats Range issue.

**Comment by mrousavy** [comment]
This is the fix in VisionCamera: https://github.com/mrousavy/react-native-vision-camera/blob/af2707e407a941331199664a6d55dc8c7000ae8d/package/android/src/main/java/com/mrousavy/camera/core/CameraDeviceDetails.kt#L127 released in 4.0.1

**Comment by mananjadhav** [comment]
@ShridharGoel Quick bump if you got a chance to create a fresh PR.

**Comment by mananjadhav** [comment]
@aldo-expensify Looks like the new PR also has all the checks failing. Are you aware what's wrong here? I haven't seen this earlier.

**Comment by mananjadhav** [comment]
@aldo-expensify quick bump

**Comment by mananjadhav** [comment]
I think we're stuck at the builds here. But I want to quickly check. Has this been reported recently? Do we want to continue with the upgrade if there's no crash in last few weeks?

**Comment by mananjadhav** [comment]
@aldo-expensify The PR is moving very slow, and I am not sure if we have experienced any recent crashes. I am inclined towards closing this one out, until we see a strong reason to upgrade. Let me know your thoughts.

**Comment by mrousavy** [comment]
Anything I can help with? I fixed this in upstream VisionCamera already.

**Comment by aldo-expensify** [comment]
> @aldo-expensify The PR is moving very slow, and I am not sure if we have experienced any recent crashes. I am inclined towards closing this one out, until we see a strong reason to upgrade. Let me know your thoughts.

I think the last crash was on Apr 26, so I'm fine with just closing this until we a stronger reason to upgrade.

**Comment by mananjadhav** [comment]
> > @aldo-expensify The PR is moving very slow, and I am not sure if we have experienced any recent crashes. I am inclined towards closing this one out, until we see a strong reason to upgrade. Let me know your thoughts.
> 
> I think the last crash was on Apr 26, so I'm fine with just closing this until we a stronger reason to upgrade.

Agreed.

**Comment by mananjadhav** [comment]
@aldo-expensify Bump ^

**Comment by mananjadhav** [comment]
@aldo-expensify Can you please check this today. Also DMed.

**Comment by aldo-expensify** [comment]
There was 3 crashes in June 26:

<img width="1348" alt="image" src="https://github.com/user-attachments/assets/73e21ed2-cd2a-426a-a67a-ba46cd7352ff">
<img width="926" alt="image" src="https://github.com/user-attachments/assets/7aec0f2f-62e6-4279-95f0-b1468bc103df">

The dependency version for this newdot version is the same as now:

```
    "node_modules/react-native-vision-camera": {
      "version": "4.0.0-beta.13",
```

I guess we should still update?

**Comment by mananjadhav** [comment]
Okay got it. Thanks for confirming.

@ShridharGoel Are you still up for the PR? The last PR didn't work for me on native.

**Comment by mananjadhav** [comment]
@ShridharGoel Can you please update on the progress? I think this is taking unexpectedly longer. It is okay if you're tied up with other issues, we can reassign this one.

**Comment by aldo-expensify** [comment]
No new crashes since June 26, I think we should just close this. It feels little relevant and has not happened in almost 2 months
