### ISSUE TITLE
[HOLD for payment 2024-06-05] [Wave Collect] New Resources to Publish

### ISSUE THREAD

**Issue by lschurr** [Expensify/App#41118]
## Publish Date - May 1
[DRAFT](https://docs.google.com/document/d/11Bt7rTlgU4z1m5WqmUvAHf4EsEJgxOoOlTs7TB1KPn8/edit#heading=h.czu9bo2qywvv)

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by lschurr** [comment]
Not overdue - Ren is still reviewing.

**Comment by lschurr** [comment]
Ren reviewed and will make a PR to publish the article :)

**Comment by lschurr** [comment]
Latest: https://expensify.slack.com/archives/C02QSAC6BJ8/p1714552803826909

**Comment by lschurr** [comment]
We're holding on this since Xero will be released mid-June

**Comment by lschurr** [comment]
Still holding I believe.

**Comment by lschurr** [comment]
Looking to get this one published soon to be ready for June release. I bumped the Slack thread here: https://expensify.slack.com/archives/C02QSAC6BJ8/p1716216142826579?thread_ts=1714162087.253239&cid=C02QSAC6BJ8
