### ISSUE TITLE
[HOLD for payment 2024-05-08]  Accounting - App crashes when opening More features page after disconnecting QBO

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces.
3. Create a new workspace.
4. Go to Accounting (enable it in More features first).
5. Set up with QBO account.
6. After QBO is connected, click 3-dot menu > Disconnect.
7. Go to More features page.

## Expected Result:
App will not crash.

## Actual Result:
App crashes.
Sometimes it also crashes when disconnecting QBO.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ba41febf-22f3-4529-9c57-b68851b6ae5f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by izarutskaya** [comment]
Not reproduced in production


https://github.com/Expensify/App/assets/115492554/5f2c00bb-4836-4bd2-8a08-9591f12e5b75

**Comment by izarutskaya** [comment]
@zanyrenney I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by thienlnam** [comment]
cc @aldo-expensify / @hayata-suenaga Seems to be from https://github.com/Expensify/App/pull/41044

**Comment by francoisl** [comment]
The QBO stuff is still behind a beta I believe, so does this need to be a blocker?

**Comment by zanyrenney** [comment]
yeah it is behind a beta @francoisl

**Comment by zanyrenney** [comment]
you're probably right it doesn't need to be a deploy blocker in that case!

**Comment by mountiny** [comment]
Aldo's PR should fix this too https://github.com/Expensify/App/pull/41060

**Comment by zanyrenney** [comment]
No payment due - Aldo is an internal Expensify employee.
