### ISSUE TITLE
Payment issue for @cubuspl42 

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#41121]
@cubuspl42 can you please comment so I can assign you then pay?
Upwork job is  https://www.upwork.com/jobs/~0150d4cbdcd2e1aadd , can you please accept the job and reply here once you have? 

Total pay is $2125 for jobs, from this [internal sheet ](https://docs.google.com/document/d/1i2k7JAz1-lv-IUgp7J6HifhdiCc-dxDqr2CaqJqEaMM/edit?usp=sharing)and below
Internal GH is [here.](https://github.com/Expensify/Expensify/issues/390290) 

[[$250] iOS - Scan - Receipt preview in confirmation page has sharp instead of round corners](https://github.com/Expensify/App/issues/40436#top)
Proposal review, due $125
$125

[[$250] LHN - LHN disappears upon leaving a public room / back button isn't redirecting to LHN](https://github.com/Expensify/App/issues/40680#top)
Partial pay for initial review on PR? 
$0

[[$250] Group chat - Inconsistency in limitation when adding members via FAB and group details page](https://github.com/Expensify/App/issues/40512#top)
Partial for PR review? No issue proposal review. 
$0

[HIGH: [Reliability] [$250] Stop using reportAction.originalMessage or reportAction.message.text](https://github.com/Expensify/App/issues/39797#top)
100% pay for Proposal review and initial PR review
$250

[[$250] [Track Tax] Error on Amount and Merchant field after changing tax rate when scanning is ongoing](https://github.com/Expensify/App/issues/39699#top)
100% pay for proposal and partial PR review
$250

[[$500] [QAB] Add a tooltip to the Quick Action Button if it is being displayed for the first time.](https://github.com/Expensify/App/issues/38054#top)
100%
$250

[[$500] Wrong message appears when the Expensify site is going down](https://github.com/Expensify/App/issues/37565#top)
100%
$500

[[$500] Empty state image has too much overlap with message in attachment thread](https://github.com/Expensify/App/issues/36166#top)
100%
$500

Grey area
[[$500] Android - Taxes - Cursor is placed before the value when reopening saved value](https://github.com/Expensify/App/issues/39081#top)
no accepted proposal 
$0

[[$250] Task - Link in system message is not underlined and no "Copy URL to clipboard" menu for link](https://github.com/Expensify/App/issues/40467#top)
Couldn’t easily find linked PR
$0

[[$250] Remove NewDistanceRequestPage.js and copy any changes since Nov 27 into IOURequestStepDistance.js](https://github.com/Expensify/App/issues/34610#top)
¯\_(ツ)_/¯
$0

[[HOLD] [$500] [MEDIUM] Smartscan: Receipt thumbnail should show the top of the receipt](https://github.com/Expensify/App/issues/34120#top)
Unsure, regression? 
$250 (?)

Total: $2125 (?)

**Comment by cubuspl42** [comment]
👍

**Comment by mallenexpensify** [comment]
Contributor+: @cubuspl42 paid $2,125 via Upwork. 
 
https://www.upwork.com/jobs/~0150d4cbdcd2e1aadd
Job title - Payment issue for @cubuspl42 #41121 - Expensify
