### ISSUE TITLE
Task – Recents missing in the list of assignees in a task creation flow

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41138]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4518332
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in as a user that had previously created tasks.
3. Click on FAB and select Assign task
4. Enter title and click next button
5. Click on Assignee

## Expected Result:
Recents present in the list of assignees in a task creation flow

## Actual Result:
Recents missing in the list of assignees in a task creation flow

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/123752a1-2203-4400-a250-b6b91b4dba05

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@rlinoz FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by thienlnam** [comment]
Doesn't look like this needs to be a blocker

**Comment by rlinoz** [comment]
I think this is caused by https://github.com/Expensify/App/pull/40271, explained what I think is happening here https://github.com/Expensify/App/pull/40271#discussion_r1583266287

cc: @bernhardoj @mananjadhav

**Comment by bernhardoj** [comment]
That makes sense, here is the [PR](https://github.com/Expensify/App/pull/41232) that fixes it.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
