### ISSUE TITLE
[$250] Track expense- Unable to close Track expense RHP with ESC key after dismissing education modal

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41134]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #40675
**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB.
3. Select Track Expense.
4. Press ESC to dismiss the education modal.
5. Press ESC again.

## Expected Result:
Track expense RHP will be dismissed.

## Actual Result:
Unable to dismiss Track expense RHP with ESC key after dismissing the education modal.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/faf59377-3518-477f-a222-b260c66830e6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2861236b6929afb</li>
        <li>Upwork Job ID: 1784977082974711808</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by m-natarajan** [comment]
@lschurr FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by thienlnam** [comment]
Doesn't seem like it needs to be a blocker

**Comment by thienlnam** [comment]
Also added from https://github.com/Expensify/App/pull/40675
cc @tienifr @rushatgabhane @srikarparsi

**Comment by lschurr** [comment]
I think we're waiting on proposals for this one

**Comment by allroundexperts** [comment]
@dragnoir's [proposal](https://github.com/Expensify/App/issues/41134#issuecomment-2090402621) makes sense and is consistent with how we're handling this at other places. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by jasperhuangg** [comment]
@dragnoir please provide an update if you can work on this issue

**Comment by rushatgabhane** [comment]
PR on staging last week

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @dragnoir ([Upwork offer](https://www.upwork.com/nx/wm/offer/102722818))
- Contributor+: $250 @rushatgabhane (please manually request in Newdot)

**Comment by lschurr** [comment]
All set!

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by allroundexperts** [comment]
Hm... I was actually assigned this issue and reviewed the proposal as well. Does someone know why I wasn't assigned the PR?

**Comment by jasperhuangg** [comment]
Based on the history in this issue it looks like this issue was never linked in the PR which is probably why the automation failed? @rushatgabhane @dragnoir Do you guys mind updating the PR to link this issue please?

cc @thienlnam

**Comment by jasperhuangg** [comment]
Not overdue just sorting out some payment/automation weirdness

**Comment by lschurr** [comment]
Just a bump on this @jasperhuangg @thienlnam

**Comment by jasperhuangg** [comment]
@lschurr I think we just need to pay out @allroundexperts and close this out. They reviewed proposals for this issue. Since something went wrong with the Github automation then they couldn't have done anything differently.

**Comment by mallenexpensify** [comment]
I think 50% for payment to @allroundexperts makes sense, since they only reviewed the initial proposals and didn't have to work on and test the PR.

**Comment by allroundexperts** [comment]
Agreed with Matt!

**Comment by lschurr** [comment]
Great, I updated the payment summary here: https://github.com/Expensify/App/issues/41134#issuecomment-2166100938

**Comment by lschurr** [comment]
Closing since the payment summary is complete.

**Comment by JmillsExpensify** [comment]
$125 approved for @allroundexperts
