### ISSUE TITLE
[HOLD for payment 2024-05-06] [$500] Login - Not able to login on desktop when clicking "Allow" on web

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41132]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open app on chrome/safari in Mac
2. Refresh the page
3. Click "Allow" open New Expensify

## Expected Result:
When clicking on "Allow" Desktop should be open with logged in account

## Actual Result:
Not able to login on desktop when clicking "Allow" on web

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e855ab2b-32f8-42ed-a3ff-c8a119f25cb6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184a20b659241d5fd</li>
        <li>Upwork Job ID: 1785052552483287040</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@grgia FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment]
@mallenexpensify @grgia  Is the ND issue of not auto-logging in when redirected from OD related to the same root cause as this issue? Or should we create a separate ticket for this issue?

https://github.com/Expensify/App/assets/93399543/3ff795ae-2d12-4bf9-9af2-56879fbd77c9

**Comment by mallenexpensify** [comment]
Checking in #expensify-open-source to try to get more deets 
https://expensify.slack.com/archives/C01GTK53T8Q/p1714411031321589?thread_ts=1714223455.070879&cid=C01GTK53T8Q

**Comment by grgia** [comment]
I think it was caused by https://github.com/Expensify/App/pull/41241

@MonilBhavsar

**Comment by grgia** [comment]
tested via adhoc here https://github.com/Expensify/App/pull/41241

**Comment by francoisl** [comment]
The ad-hoc build [above](https://github.com/Expensify/App/issues/41132#issuecomment-2083530589) didn't solve the issue for me unfortunately. Let's see if someone can figure out the cause.
