### ISSUE TITLE
Room - Incorrect number of members is shown when the invite error is not manually dismissed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41133]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found validating #40272
**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a room.
3. Click on chat header > Members.
4. Invite VOIP number +18183305299.
5. Without dismissing the error, go back to previous page.
6. Return to Members page.
7. Go back to room details page.

## Expected Result:
The room details page should display the correct number of room members.

## Actual Result:
The room details page displays the incorrect number of room members, which include the VOIP user, because the error is not manually dismissed and disappears on its own after closing Members page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/4662a91c-ed84-4083-a124-d4b1a862a0c5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@johnmlee101 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
@nkdengineer @akinwale seems like this is stemming from your PR https://github.com/Expensify/App/pull/40272 can you please raise a fix?

**Comment by puneetlath** [comment]
Requested the CP for the revert.

**Comment by puneetlath** [comment]
This has been reverted.
