### ISSUE TITLE
[$250] App Crashes When Exiting and Re-entering Thread in Offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41130]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1, sign in with your Gmail account> Navigate to any chat and set the status to offline.
2, Send a message and enter the thread.
3, Click on the three dots menu and select "Leave thread."
4, Re-enter the thread.
5, Switch status to online.

## Expected Result:
App functions normally without crashing

## Actual Result:
App crashes upon transitioning from offline to online after leaving and re-entering the thread.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5e30bff2-ad6e-4378-9e3a-f0f3f86dd2de

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd50bce934ebc9f8</li>
        <li>Upwork Job ID: 1784870016982994944</li>
        <li>Last Price Increase: 2024-04-29</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@arosiclair FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by arosiclair** [comment]
I reproduced on web **v1.4.67-0**

**Comment by arosiclair** [comment]
@gijoe0295 I think your proposal is on the right track. When `report` and `defaultAvatar` are empty objects in `ReportUtils.getIcons`, the `fallbackIcon.source` will be set to an empty object [here](https://github.com/Expensify/App/blob/c6f599adc86585b505a355b00916d0826876f0c5/src/libs/ReportUtils.ts#L1855) which causes the crash. 

Removing `?? {}` for the `defaultAvatar` fixes the issue. However, I think it is probably better to just check for when `defaultAvatar` is an empty object to prevent this in the future. Can you submit a PR for this @gijoe0295?

**Comment by MonilBhavsar** [comment]
Should be fixed by https://github.com/Expensify/App/pull/41219

**Comment by thienlnam** [comment]
Yup, appears to be resolved for me on staging now - thanks Monil!
