### ISSUE TITLE
Android - Chat - With specific url, adding emoji in edit compose box url disappears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4522386
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter Lhh.com and send the message
4. Long press and select edit comment
5. Tap emoji picker in edit box and select an emoji
6. Note both url and emoji is displayed in edit compose box
7. Enter Ghh.com and send the message
8. Long press and select edit comment
9. Tap emoji picker in edit box and select an emoji
10. Note url disappeared and emoji only displayed in edit compose box
11. Enter Ahh.com and send the message
12. Long press and select edit comment
13. Tap emoji picker in edit box and select an emoji
14. Note url disappeared and emoji only displayed in edit compose box

## Expected Result:
With specific url, adding emoji in edit compose box url must not disappear

## Actual Result:
With specific url, adding emoji in edit compose box url disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9c082910-a0cf-44ab-acbe-1d6f86ca23fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by adelekennedy** [comment]
I can't reproduce this in browserstack and it's an edge case enough issue (off the roadmap) I'm going to close
