### ISSUE TITLE
[$250] IOS - More features - Enabled feature is not showing in workspace page after enabling it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41142]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to Account settings > Workspaces
3. Create a new workspace
4. Go to More features
5. Enable any feature

## Expected Result:
App will redirect to the previous page with the enabled feature

## Actual Result:
The enabled feature is not showing in workspace page after enabling it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e6867546-b84e-4c84-bbd3-af33a6b048ac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cc719021a75da07</li>
        <li>Upwork Job ID: 1784283404020502528</li>
        <li>Last Price Increase: 2024-04-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@roryabraham  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by roryabraham** [comment]
Kicked off an AdHoc build for a revert of https://github.com/Expensify/App/pull/40369 to see if that fixes this problem.

**Comment by mollfpr** [comment]
As mentioned in the @Krishna2323 proposal, `didScreenTransitionEnd` is bugging for iOS and probably added to avoid the animation starting while the transition is happening. Removing it from the check is to fix this issue, but I'm not sure the case for the check where is needed.

**Comment by kavimuru** [comment]
Two testers tried to reproduce. One wasn't able to while the other was able to.

https://github.com/Expensify/App/assets/43996225/f197959d-6766-4427-9201-ed19273d904f


https://github.com/Expensify/App/assets/43996225/d1dba7b6-3a04-45b6-bdc7-3670b4d39442

![IMG_3229](https://github.com/Expensify/App/assets/43996225/97630538-9b6a-4279-a6d6-5d56a4587b68)

**Comment by francoisl** [comment]
> Kicked off an AdHoc build for a revert of https://github.com/Expensify/App/pull/40369 to see if that fixes this problem.

@roryabraham did that AdHoc build fix the issue? Should we go ahead with a revert or with @Krishna2323's proposal in this case?

**Comment by thienlnam** [comment]
I was testing the adhoc, and it seemed to work fine after this [revert](https://github.com/Expensify/App/pull/41176)

**Comment by thienlnam** [comment]
We're having the revert CPed
