### ISSUE TITLE
[$250] Track - Categorize it - Not here page opens when selecting a workspace with no category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41143]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Go to Account settings > Workspaces > workspace in Step 2
4. Go to Categories page
5. Delete all the categories
6. Return to Chat
7. Click FAB > Track expense > Manual
8. Track a manual expense
9. Click Categorize it from the whisper
10. Select the workspace where all categories are deleted

## Expected Result:
There should be some error indicating that the workspace has no category other than just a "Not here" page

## Actual Result:
Not here page opens when selecting a workspace with no category

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6b1952bd-10b6-42bf-a2a5-61ba65c49256

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e69ed8db299bc4fe</li>
        <li>Upwork Job ID: 1784791676082184192</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by jliexpensify** [comment]
Thanks @ZhenjaHorbach - going to assign @mananjadhav as he's the C+ on the other one. Would you like to fold these issues together into one fix?

**Comment by mananjadhav** [comment]
Yeah we can use the same issue to fix both.

**Comment by jliexpensify** [comment]
Ah actually - @mananjadhav what's the best way to handle this? Close this one, and pay in the other issue?

**Comment by mananjadhav** [comment]
Yes let's close this one and pay in the other issue.
