### ISSUE TITLE
[HOLD on #40845] LHN - HTML displayed in LHN when sending markdown message with attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41141]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in in Gmail account
3. Go to chat and write a message with markdown
4. Click the plus sign and select attachment
5. Send the attachment with the message. Notice in the LHN, the HTML is displayed

## Expected Result:
When sending a markdown message with an attachment, the LHN should not display the message with HTML

## Actual Result:
When sending a markdown message with an attachment, the LHN displays the message with HTML

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/91ddd1dd-e707-4cd2-8f83-40a08d32df61

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by sakluger** [comment]
Thanks @GandalfGwaihir!

**Comment by sakluger** [comment]
I tested myself and this seems to be fixed! 🎉
