### ISSUE TITLE
Push notifications to a group is  using the participants name instead of group's name

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41151]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714153790846589

## Action Performed:
1. Create a group DM
2. Send a message to the group as a member of the group
3. Get notification in iOS
## Expected Result:
Should show the group name
## Actual Result:
Showing the user who sent the message
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/38435837/53114080-ea17-4746-a0b2-2becf3aa4cab" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/adf1c557-27f8-48da-be97-437c32772d6f" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152f1ef37a9408859</li>
        <li>Upwork Job ID: 1785736553217708032</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
@Julesssss @miljakljajic @puneetlath do we want to fix this now or with the notifications project?

**Comment by Julesssss** [comment]
This is definitely a separate issue. We chose to use participants as the notification title back before group names were a thing.

The expected/current behaviour suggests we'd show the group name instead of sender, but I believe instead we should be showing sender and group name: 

> Andrew Gable
> [Group Name]
> Message

**Comment by miljakljajic** [comment]
Yeah, we've tightened up the initial problem statement to focus on duplicate notifications so this should be handled separately.

**Comment by Julesssss** [comment]
For whoever picks this up, we just need to update the `roomName` passed to [sendReportCommentNotifications](https://github.com/Expensify/Web-Expensify/blob/836b1e5b59fa8e692025c8d45dbd4eeb72f5d74c/lib/MobilePushNotifications.php#L40). 

@arosiclair has been improving these functions for moneyRequests, so its usage might have changed a little bit.

**Comment by trjExpensify** [comment]
PR merged, awaiting a deploy.

**Comment by trjExpensify** [comment]
Deployed to prod two days ago. @marcaaron that was a Web-E PR, can we close this?

**Comment by marcaaron** [comment]
Thanks, closing it out.
