### ISSUE TITLE
Feature Request : Add system message when creating a smart scanned receipt that no manual `submit` available after smartscanning

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41175]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Problem:
For the smart scanned  receipt submitters does not have proper message that it will be auto submitted and does not have `submit` button

## Solution:
Some clear message should be displayed to the submitter that receipt will get auto submitted once scanned the receipt and can't manually submit the receipt after smart scanned

## Context/Examples/Screenshots/Notes:

![image (15)](https://github.com/Expensify/App/assets/38435837/c6657a2b-57bb-43c1-8af1-b823147120da)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712718536151639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dannymcclain** [comment]
@johncschuster Is anything design-specific needed here? I think I'm a little unsure of what the next steps for this are.

**Comment by jliexpensify** [comment]
Hrrm @dannymcclain I'm not sure why this GH was created. We can close it if you like!

**Comment by dannymcclain** [comment]
@jliexpensify I'm going to go ahead and close, but if you think we should do something like this, absolutely feel free to keep it open/run it through WN, etc.
