### ISSUE TITLE
CRITICAL: [Track expense] Render anonymous emails as `Guest` everywhere, but specifically in SelfDM (both LHN and chat itself)

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#41180]
Problem:
===
When you visit a public room (such as [#exfy-roadmap](new.expensify.com/r/868417741568295)), we create an "anonymous" account for you (ie, asdfadfadfadf@expensify.anon).  This is necessary to keep track of what you've done and support your browsing of the app, even before you claim the account with a real email address.  However, sometimes we show it, and it looks super weird, such as here:

Solution:
===
Never render the anonymous email in its full glory.  Rather, show it as `Guest`.  This could maybe be as easy as just:

1. Create all new anonymous accounts with the `Guest` first name
2. Erase the `Guest` first name upon claiming the address, such that we start showing the original email/SMS (or their actual display name).
3. Verify that we populate the display name using Clearbit even when claiming an anonymous account.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164fe76dfe5a0c301</li>
        <li>Upwork Job ID: 1784704646611320832</li>
        <li>Last Price Increase: 2024-04-28</li>
    </ul>
</details>

**Comment by marcochavezf** [comment]
PRs ready for review:
- https://github.com/Expensify/Auth/pull/10727
- https://github.com/Expensify/App/pull/41288

**Comment by quinthar** [comment]
Is this done?  Can we close this?

**Comment by marcochavezf** [comment]
Yup, closing it out
