### ISSUE TITLE
[CRITICAL] [VIP Travel] Handle tripName updates to display Trip Title and dates in newDot

### ISSUE THREAD

**Issue by twisterdotcom** [Expensify/App#41207]
We need to display a Trip Title on newDot, but we weren't getting it with just PNR updates (which we decided to get [here](https://expensify.slack.com/archives/C05S5EV2JTX/p1712332031935189)).

We asked Spotnana to send us both the trip_v3 webhooks and PNR webhooks. We'll be receiving the PNR data with the trip_v3 webhooks, which we should ignore. We'll take the trip data and always update the trip title:

<img width="357" alt="image" src="https://github.com/Expensify/App/assets/9133401/61c3f9c7-2a24-4048-8766-a6721f7197d4">

...from the data returned via the trip_v3 web hook:

```JSON
{
"tripId": "6926658168",
"tripName": "JFK SFO Trip",
"tripDescription": "JFK SFO Business Trip",
"applicationId": "97ab27fa-30e2-43e3-92a3-160e80f4c0d5",
"startDate": {
"iso8601": "2017-07-21"
},
"endDate": {
"iso8601": "2017-07-21"
}
}
```

**Comment by danieldoglas** [comment]
will deal with this during the weekend probably

**Comment by danieldoglas** [comment]
This should be ready to review

**Comment by danieldoglas** [comment]
should go with the next deploy
