### ISSUE TITLE
Join workspace - App crashes when accepting workspace join request in thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- "Pre-approve join requests" for the workplace is disabled on Old Dot.
1. Go to staging.new.expensify.com
2. [User A] Go to Collect workspace settings > Profile.
3. {User A] Click Share > Copy URL.
4. [User B] Navigate to the Copy URL to accept the workspace invitation.
5. [User A] Go to #admin from the workspace in Step 2.
6. {User A] Right click on the invite request > Reply in thread.
7. [User A] Click Accept.

## Expected Result:
App will not crash.

## Actual Result:
App crashes when accepting workspace join request in thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2ce16a16-202c-4bcd-bc7a-10ce455365d3

[crash logs.docx](https://github.com/Expensify/App/files/15149395/crash.logs.docx)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01167df0c75dd488a0</li>
        <li>Upwork Job ID: 1785311727140585472</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment]
@slafortune FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
@rushatgabhane do you have an update on this?

**Comment by rushatgabhane** [comment]
If the backend isn't returning an array we need to fix it in backend. 

https://github.com/Expensify/App/issues/41205#issuecomment-2086439840

🎀👀🎀

**Comment by grgia** [comment]
@suneox yes, but are the params we're sending correct?

**Comment by grgia** [comment]
cc @danieldoglas as you worked on this command

**Comment by danieldoglas** [comment]
hm, this was fixed before, maybe we changed something in the backend related to this again? @luacmartins do you know of anything recent?

**Comment by luacmartins** [comment]
Not that I know of, sorry.

**Comment by grgia** [comment]
@arosiclair would you want to take this as a follow up to your PR?

**Comment by grgia** [comment]
thank you @danieldoglas!

**Comment by arosiclair** [comment]
> @arosiclair would you want to take this as a follow up to your PR?

Yeah I'll post something soon. It looks like we didn't verified the `originalMessage` in tests but not the `message` so I'll update that too.

**Comment by arosiclair** [comment]
PR posted

**Comment by arosiclair** [comment]
[Fix is on prod](https://github.com/Expensify/Auth/pull/10900#issuecomment-2122279073). No contributor or C+ work done so this should be all set

**Comment by arosiclair** [comment]
Appreciate the effort @suneox but we do not issue payments just for identifying backend issues.
