### ISSUE TITLE
[External Resource]Join Your Company's Workspace

### ISSUE THREAD

**Issue by slafortune** [Expensify/App#41213]
Publish Date: May 1st 2024
This will be published under Getting Started for New Expensify
Tracking GH: https://github.com/Expensify/Expensify/issues/391470
Draft: https://docs.google.com/document/d/1Q5EjAJvzFX6O-H0cMgIeR_S0gEamr5llHtb0b1FIuLM/edit
cc @ren-jones

**Comment by slafortune** [comment]
https://docs.google.com/document/d/1Q5EjAJvzFX6O-H0cMgIeR_S0gEamr5llHtb0b1FIuLM/edit

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by ren-jones** [comment]
Draft pushed!
