### ISSUE TITLE
[Wave Collect] Categories help page

### ISSUE THREAD

**Issue by sonialiap** [Expensify/App#41217]
Publish Date - May 1

[Draft](https://docs.google.com/document/d/1VKLlZDK2GJtdbpsfKmSbBOySbpeViL11TiUSY9h1Sjo/edit)

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by sonialiap** [comment]
Draft shared with you, Ren :)

**Comment by sonialiap** [comment]
@ren-jones Love your edits, it looks great! Let me know if I can help with publishing or anything else

**Comment by sonialiap** [comment]
This is [published and live on the site](https://help.expensify.com/articles/new-expensify/workspaces/Create-expense-categories). @ren-jones we can close this, right?
