### ISSUE TITLE
[Wave Collect] Settings > Profile

### ISSUE THREAD

**Issue by alexpensify** [Expensify/App#41229]
Publish Date: May 1, 2024
Priority 4: https://expensify.slack.com/archives/C02QSAC6BJ8/p1714250035618949
Tracking GH: https://github.com/Expensify/Expensify/issues/381571
Draft: https://docs.google.com/document/d/1h8m0K6BNG5HfBlKe4uAU7Z9O1Phqtcb24b2c9UF-piY/edit

cc @ren-jones

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by alexpensify** [comment]
Done, thanks!

**Comment by alexpensify** [comment]
I followed up in the Google Doc with replies to the comments. All set here.

**Comment by alexpensify** [comment]
Closing this was deployed to production
