### ISSUE TITLE
[External Resource] Create a Company Workspace New Expensify

### ISSUE THREAD

**Issue by slafortune** [Expensify/App#41224]
Publish Date: May 1st 2024
This will be published under Getting Started for New Expensify
Tracking GH: https://github.com/Expensify/Expensify/issues/391469
Draft: https://docs.google.com/document/d/16MpMko56R_A_QaaiG7weNaPaLcmtRoLHMwbMfjpA6WU/edit
cc @ren-jones

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by ren-jones** [comment]
Article pushed
