### ISSUE TITLE
[PAY] 2 copies of react-pdf are included in the web js bundle

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#41237]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Latest
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @janicduplessis 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1714407724836209?thread_ts=1714247539.428689&cid=C05LX9D6E07

## Action Performed:

- Inspect js bundle using the analyze-packages script
- See that there are 2 copies of react-pdf

## Expected Result:
There should only be 1 copy of react-pdf

## Actual Result:
There are 2 copies of react-pdf

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/2677334/ddd61561-cf44-447e-8c26-bfb9055eb392)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Assigned to @ahmedGaber93 as they're reviewing the PR.

**Comment by roryabraham** [comment]
Reviewed and merged the PR

**Comment by janicduplessis** [comment]
This has been merge already, can we close it?

**Comment by mallenexpensify** [comment]
Thanks for the ping @janicduplessis .  @ahmedGaber93 , you're due $250 here, right? Assuming so, can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~012eb7ba95c3bdb089
I

**Comment by ahmedGaber93** [comment]
Yes, right. Offer accepted thanks @mallenexpensify

**Comment by mallenexpensify** [comment]
Contributor+: @ahmedGaber93 paid $250 via Upwork. 

Thanks!
