### ISSUE TITLE
HIGH: [Marketing] New Resources to Publish - Markdown Syntax

### ISSUE THREAD

**Issue by CortneyOfstad** [Expensify/App#41245]
Publish Date: May 1st 2024
Tracking GHs [Track Expenses]: https://github.com/Expensify/Expensify/issues/385521
Following the steps in: https://stackoverflowteams.com/c/expensify/questions/17951

Article Draft is [here](https://docs.google.com/document/d/1UcoH95ro8k9XRf8w_n5jQRs_P8PWp5RAGR3CamVSCDU/edit?usp=sharing)

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by ren-jones** [comment]
We previously covered this topic in the following article, so I updated that article to include 2 markdown items that weren't not previously included. Cortney and I agreed that we no longer need a separate resource so this one should be good to go!

**Comment by CortneyOfstad** [comment]
This has been published on the Send and Format Chat page, so this can be closed!
