### ISSUE TITLE
[Awaiting checklist] [$250] Can't view receipt from Split Expense details view

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714397575860519

## Action Performed:
1.Create a split expense by using scan receipt option
2. Click on split expense preview
3. Click on the receipt in the detail page

## Expected Result:
When you tap into the details view of the split, you should be able to tap into the receipt to view the entire thing

## Actual Result:
The receipt thumbnail is not tappable
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-04-29 at 09 32 38@2x](https://github.com/Expensify/App/assets/38435837/df8c43d5-bd82-42ad-bf1d-ea1b7e4a40ec)

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1fc2a02d-a015-417d-97b3-358ed2ebce69

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc257ab37da4f84c</li>
        <li>Upwork Job ID: 1785408514916585472</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can't view receipt from Split Expense details view

### What is the root cause of that problem?
Split Details is rendered with `MoneyRequestConfirmationList`. Here we don't allow the receipt to be clickable.

https://github.com/Expensify/App/blob/49db1492b770adc57301c78026dd4790d4e6bb01/src/components/MoneyRequestConfirmationList.tsx#L963-L965

### What changes do you think we should make in order to solve the problem?
We will wrap the Receipt with a Pressable, if are viewing details, just like we do here:
https://github.com/Expensify/App/blob/49db1492b770adc57301c78026dd4790d4e6bb01/src/components/ReportActionItem/ReportActionItemImage.tsx#L102-L109

Passing `reportID` and `transactionID`:

```jsx
  <PressableWithoutFocus
      style={[styles.noOutline as ViewStyle]}
      onPress={() => {
          Navigation.navigate(ROUTES.TRANSACTION_RECEIPT.getRoute(reportID ?? '', transactionID ?? ''))
      }}
      accessibilityLabel={translate('accessibilityHints.viewAttachment')}
      accessibilityRole={CONST.ROLE.BUTTON}
  >
    ...
  <PressableWithoutFocus>
```

**Comment by mollfpr** [comment]
Reviewing 👀

**Comment by mollfpr** [comment]
@neonbhai Why do we only wrap the `ReceiptImage` and not with the `PDFThumbnail`? Also, the attachment is not shown on the modal.

![Screenshot 2024-05-02 at 11 40 59](https://github.com/Expensify/App/assets/25520267/5bd3195e-c6bb-45dc-8acc-a836f3040076)

---

>Wrap PDFThumbnail & PDFThumbnail with PressableWithoutFocus and when PressableWithoutFocus is pressed, first we need to we need to navigate Navigation.navigate(ROUTES.TRANSACTION_RECEIPT.getRoute(reportID ?? '', transactionID ?? '')).

@ Krishna2323 Does this mean we can only preview the PDF file? I'm not sure if I understand your changes correctly, but it seems the attachment will not clickable after it scanned.

>We need to pass disabled={!isEditingSplitBill} to PressableWithoutFocus to make sure that we only navigate when we are at the receipt details page,

Is there any case that we don't want to make the attachment previewable?

**Comment by mollfpr** [comment]
> We need to pass disabled={!isEditingSplitBill}

@Krishna2323 This will make the attachment press disabled on the detail page.

**Comment by mollfpr** [comment]
@Krishna2323 Sounds right!

Let's get this done! The [proposal](https://github.com/Expensify/App/issues/41249#issuecomment-2084322741) from @Krishna2323 looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by twisterdotcom** [comment]
@AndrewGable can we assign @Krishna2323?

**Comment by mollfpr** [comment]
Friendly bump @AndrewGable

**Comment by twisterdotcom** [comment]
Payment Summary:

- @mollfpr paid $250 via NewDot Manual Request
- @Krishna2323 paid $250 [here](https://www.upwork.com/nx/wm/workroom/37288031/overview) (Contributor)

**Comment by mollfpr** [comment]
Sorry for the delay 🙏 

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

No need for this, the regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open a workspace
2. Start a split expense > scan
3. Upload an image/pdf receipt > confirm
4. Open newly created split expense from the report preview
5. Click on the receipt image/pdf
6. **Verify** the attachment opens in modal
7. 👍 or 👎

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr
