### ISSUE TITLE
Incorrect Error is displayed when creating conversation with invalid number

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#41257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.67-3
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on FAB > Start Chat
2. Start a chat with the following number - +79585702746
3. Click on the "Search" icon

## Expected Result:
An error should display indicating the user there was an error creating the chat. 
Header should display the user details. In this case the phone number "+79585702746"
When clicking in search, the conversation with the error should not display. 

## Actual Result:
An error is displayed indicating the user that "The provided phone number does not match the country you are currently located at, please use your email address instead."
There's a skeleton loader in the header of the conversation. 
The conversation with the error is displayed in search. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/44479856/05287a87-bc1f-4703-ad19-1419210ac914)

![image](https://github.com/Expensify/App/assets/44479856/8e2cc4cd-b2c3-402b-b70d-c78f81af81ac)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c028e1ef30e9a46</li>
        <li>Upwork Job ID: 1785768462241026048</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by isagoico** [comment]
This was found while reviewing the regression tests for this issue - https://github.com/Expensify/Expensify/issues/390645

This issue https://github.com/Expensify/App/issues/38879 had 2 PRs that fixed the following: 
- Skeleton loader - Not fixed - https://github.com/Expensify/App/pull/39585
- Invalid account is displayed in search - Not fixed - https://github.com/Expensify/App/pull/22612

**Comment by neonbhai** [comment]
The error message is sent from the backend:

<img width="1146" alt="Screenshot 2024-04-30 at 5 20 34 AM" src="https://github.com/Expensify/App/assets/64629613/13d3c7a1-7671-4344-aa9e-a0cc0699890f">

We can add the `Internal` label here

**Comment by sakluger** [comment]
Bsed on the discussion, the error from the backend is correct, but we could handle the situation more clearly.

That being said, this is a vary unlikely edge case, I am going to close so we can focus on higher value bugs.
