### ISSUE TITLE
[HOLD][$250] No option to delete a split expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714397840298949

## Action Performed:
1. Open NewDot app
2. Click Fab > create a split expense in a group
3. Right click on the preview or open the details page
## Expected Result:
There should be an option to delete the expense
## Actual Result:
There is no way to delete the split expense
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-04-29 at 09 35 06@2x](https://github.com/Expensify/App/assets/38435837/24202ab2-f5c5-482b-b976-46cca7526b48)
![no option to delete split expense](https://github.com/Expensify/App/assets/38435837/6e8f0876-da7f-43f1-91fa-e35b9b5e2066)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c905ff4169e0f091</li>
        <li>Upwork Job ID: 1785078215944183808</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by shawnborton** [comment]
cc @arielgreen @rafecolton @saracouto so you have visibility on this one - not sure if the possibility to split is coming at a later date or not. It might intersect with being able to edit one, too. 

In the case I reported above, the split was in a SmartScanning state so it hadn't actually been created yet, and I would think you should be able to delete the split in that state in case it was done by accident.

**Comment by rafecolton** [comment]
Editing and deleting splits is something I'd like to build, yeah, but we haven't scoped it yet. I suggest we wait until we do before implementing this. I do think editing or deleting a split before it finishes scanning is a valid use case.

**Comment by rafecolton** [comment]
We can leave it on hold for now. I added it to the project so we don't forget about it.

**Comment by jliexpensify** [comment]
Ha, I was too trigger happy. Removed the `External` and 1`Help Wanted` labels, and will remove the Upworks job.

**Comment by jliexpensify** [comment]
Ah yes, apologies @ishpaul777 - I should have unassigned you since there's no `External` label.

**Comment by jliexpensify** [comment]
This is paused. Not overdue. @saracouto could we close this, or did you want to keep it open?

**Comment by jliexpensify** [comment]
Going to close this one, since it's on pause.
