### ISSUE TITLE
[$250] [HOLD for payment 2024-05-05] Payment issue for Add Split expense to Global Create

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#41255]
This issue is a summary payment issue for @getusha and @shubham1206agra for their work on the [Add Split Expense to Global create](https://github.com/Expensify/App/issues/36748). They have done:

- [Cleanup all instances of "request" and "send money" in App](https://github.com/Expensify/App/pull/39483) by Shubham
- [Implement route changes in NewDot for updated Global Create](https://github.com/Expensify/App/pull/40576) by Shubham
- [Refactor Participant Selector](https://github.com/Expensify/App/pull/40370) by Me
- Writing the detailed section of the [Add Split Expense to Global create](https://github.com/Expensify/App/issues/36748) 

The last PR has also been merged and deployed to staging on Monday 22nd April and that was well before the deadline of 1st May. There were no major regressions and it seems like we are in a good spot now. I have offered the team a bonus of $1000 for completing this project urgently once week before the official deadline which would be Tuesday 23rd April and they have met this deadline so they deserver the bonus too.

The total rewards for each are $3500 where $2500 was a base and $1000 bonus for completion. There were also basically no regressions.

I believe that is a reasonable reward given the urgency, proactive approach, starting discussions in the vip-split room, writing the design doc, helping to resolve the threads from the doc so we could start the implementation, implementing all the frontend changes, cross testing and reviewing the PRs.

$3500 to @shubham1206agra and $3500 to @getusha for the completion of this entire project
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5df74a98073dc25</li>
        <li>Upwork Job ID: 1785169824242520064</li>
        <li>Last Price Increase: 2024-04-30</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment]
done
