### ISSUE TITLE
Skeleton appears to User B when User A deletes the submitted IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4518579
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with two new HT accounts A and B at the same time
3. Send any message to user A->B
4. Send any message to user B->A
5. Send a manual IOU to A->B
6. Delete the IOU immediately before it registers with user B
7. Wait until the conversation between user B and user A is updated
8. Repeat steps 5-7 several times.

## Expected Result:
The application should not appears skeleton on user B when user A deletes the sent IOU

## Actual Result:
Skeleton appears to User B when User A deletes the submitted IOU

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/57f7ff8d-8599-4ba1-ac5f-3e6ecdc111ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
Hmm, I don't think this really feels like something worth prioritizing now IMO. Having to repeat the steps several times (including sending IOUs and then deleting them before they register in the other user's account) does not feel like something many/any customers are likely to do. 

Let's see if anyone actually experiences this before doing anything.
