### ISSUE TITLE
[HOLD for payment 2024-05-09] CRITICAL [Invoice Rooms]: Update invoice rooms to use correct avatars 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#41261]
As highlighted on [this issue](https://github.com/Expensify/App/pull/40015#issuecomment-2083199494), we need to update the invoice rooms to use the correct Avatars. 

@shawnborton highlighted the intent well in the above and I've included the direction below. But pretty much they should mirror how workspace chats work. For the large avatar, we should use the senders workspace avatar. Then, if the invoice room is shared with another workspace, we'd use that workspace avatar for the smaller avatar. If the invoice room is shared with an individual, it would show the individuals avatar. Examples below. 

Workspace to Workspace:
![image](https://github.com/Expensify/App/assets/2364487/ab25b22d-f004-41a7-93bc-e932761fb17b)

Workspace to Individual:
![image](https://github.com/Expensify/App/assets/2364487/5891c19e-398a-4d5a-80d8-4d2eb79f8097)

cc @cristipaval can you work with the team to make sure this gets picked up? 

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.
cc @cristipaval

**Comment by VickyStash** [comment]
The PR has been opened - https://github.com/Expensify/App/pull/41316

**Comment by VickyStash** [comment]
NOTE: I'll be OOO 1-8th of May 🌴

**Comment by danielrvidal** [comment]
Yup, I tested this one and it looks good!

**Comment by rushatgabhane** [comment]
@cristipaval could you please attach payment summary for this issue

**Comment by cristipaval** [comment]
@isabelastisser Please help with the payment when it gets due

Payment summary:

@rushatgabhane for the C+ review

Note: This is not a regression. I merged the offending PR even if the design's approval was not final. We wanted to move fast and we agreed on follow-up PRs if the design requested changes

**Comment by isabelastisser** [comment]
@rushatgabhane, can you confirm that your payment needs to be processed via NewDot?

**Comment by isabelastisser** [comment]
Missed this:

> @rushatgabhane requires payment through NewDot Manual Requests

**Payment summary**:

@rushatgabhane for the C+ review $500.

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by JmillsExpensify** [comment]
Ah actually, @rushatgabhane is requesting $500 and that seems correct given that this is a CRITICAL issue. @isabelastisser can you please update the payment summary with that in mind?

**Comment by isabelastisser** [comment]
@JmillsExpensify, yes. I have already highlighted it above: https://github.com/Expensify/App/issues/41261#issuecomment-2102793406

Payment summary:

Contributor: @VickyStash is from an agency-contributor and not due payment
Reviewer: @rushatgabhane owed $500 via NewDot

**Comment by isabelastisser** [comment]
Bump @JmillsExpensify

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane
