### ISSUE TITLE
[HOLD for payment 2024-06-11] [HOLD for payment 2024-06-05] [#card-program-manager] - [May 1] New resource to publish 

### ISSUE THREAD

**Issue by shmaxey** [Expensify/App#41263]
### **Publish date: May 1**

[DRAFT](https://docs.google.com/document/d/1q2sBJ-r4LWq70paWoFmXv1KVigBCfLN5LnZjNlPj8YE/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by maddylewis** [comment]
unassigned myself after chatting this one through!

**Comment by shmaxey** [comment]
Ok, I reworked this a bit. There are so few steps to actually upgrading, but a bit of information otherwise. @joekaufmanexpensify I left some comments, if you could take a look! Thanks!

**Comment by joekaufmanexpensify** [comment]
Went through and left some suggestions/comments. LMK what you think!

**Comment by shmaxey** [comment]
Ok @ren-jones this is ready for another review!

**Comment by joekaufmanexpensify** [comment]
Not overdue. I think still pending @ren-jones review

**Comment by joekaufmanexpensify** [comment]
Still pending

**Comment by shmaxey** [comment]
This is live! 🎉 

But @ren-jones, noticing a couple things: 

1) This should be under `Expensify Classic` rather than New Expensify, since this is only relevant to domains who enabled the card program on Classic

2) 
<img width="959" alt="image" src="https://github.com/Expensify/App/assets/24882110/5a07eff9-809e-46cf-aeec-8a4cd28fd54e">

I don't think those two bullet points are supposed to be in that box?

**Comment by joekaufmanexpensify** [comment]
No per-PR payment needed here

**Comment by shmaxey** [comment]
This is still in the wrong place w/ bad formatting. @rushatgabhane do you know how to fix this formatting? Then we can delete the article under the New Expensify section and move it to Expensify Classic..

<img width="842" alt="image" src="https://github.com/Expensify/App/assets/24882110/d695f233-09ac-4d88-8d4b-dad915fff789">

**Comment by shmaxey** [comment]
[This](https://github.com/Expensify/App/issues/42852) issue should fix the weird formatting, and then we can move that article to the `Expensify Classic` section.

**Comment by kevinksullivan** [comment]
checking if I need to pay this or if the process is outdated
