### ISSUE TITLE
[Awaiting Payment May 16th] [QBO] Ensure the actions to `Add` or `Delete` are not allowed on all imported coding pages

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714438462878199?thread_ts=1714400674.229349&cid=C036QM0SLJK

## Action Performed:
1. Create a workspace on NewDot
2. Go to More Features > Tags > Enable (you need this step for now because otherwise `Tags` won't show in the LHN after you connect to QBO to see the imported coding, apparently that's going to be worked on [here](https://github.com/Expensify/Expensify/issues/387834#issuecomment-2083773292))
3. Enable `Accounting` in More Features as well
4. Go to `Accounting` in the workspace settings LHN
5. Connect to QBO
6. Go to Categories
7. Select a couple of category in the table 
8. Click the `[2 selected v]` button in the page header
9. Observe the `Delete categories` button that shouldn't be there
10. Close the RHP modal
11. Click on a category in the table 
12. Observe the three dot overflow menu in the category settings page in the RHP that shouldn't be there
13. Click the overflow menu
14. Observe the `Delete category` menu item that shouldn't be there. 
15. Close the modal
16. Go to the `Tags` page
17. Observe the `Add tag` button in the page header that shouldn't be there
18. Repeat steps 7-14 above and observe that the admin can also delete imported tag values

## Expected Result:
When coding features (`Categories`, `Tags`, `Taxes`) are imported from QBO, you shouldn't be able to `Add` or `Delete` the imported values. As such:

- The green `Add X` button should be hidden in the page header
- The `Delete X` menu item should be hidden in the bulk selection menu, only `Disable X` || `Enable X` should be shown.
- The overflow menu in the category setting page should be hidden as the only menu item within it is to `Delete x` which shouldn't be allowed

Note: Untested but likely true given the above so please check on dev, and make sure we apply the same fix to `Taxes` imported to the workspace as well.

## Actual Result:
Admins can `Add` and `Delete` imported coding values when connected to QBO

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/1e086d82-7aa1-49ef-a2a7-6af94534750b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
CC: @aldo-expensify @hayata-suenaga @zanyrenney @narefyev91 @teneeto

**Comment by hayata-suenaga** [comment]
we need to fetch connections data on those pages. Let me create a custom hook to do that. We cannot use the existing HOC as that is going to break the offline pattern on those pages.

**Comment by trjExpensify** [comment]
>we need to fetch connections data on those pages. Let me create a custom hook to do that. We cannot use the existing HOC as that is going to break the offline pattern on those pages.

Out of curiosity, how are we hiding the `Add category` button already when connected to QBO? 🤔 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/ccfd421d-cc9a-4781-8264-53331ad0c668">
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/9452adec-4ceb-41d7-abc5-ceb5515b79dd">

**Comment by hayata-suenaga** [comment]
> Out of curiosity, how are we hiding the Add category button already when connected to QBO? 🤔

because we're already fetching the `connections` data with HOC. But we decided to remove this HOC as it breaks the offline pattern on Categories and Tags pages.

I'm creating [the custom hook](https://github.com/Expensify/App/pull/41278) so that we don't have to block the screen when the user is offline.

anyway, I can work on this issue while waiting for that PR to be merged.

**Comment by trjExpensify** [comment]
Sounds good!

**Comment by trjExpensify** [comment]
@hayata-suenaga did your PR also take care of imported tax rates as well?

**Comment by hayata-suenaga** [comment]
My PR doesn't prevent the user form deleting taxes

@SzymczakJ is working on the PR linked above. @SzymczakJ can you handle the prevention of tax deletion when there is QBO connection (QBO connection and the country is not US)

**Comment by trjExpensify** [comment]
>My PR doesn't prevent the user form deleting taxes

What about adding tax values manually as well?

**Comment by hayata-suenaga** [comment]
> > My PR doesn't prevent the user form deleting taxes
> 
> What about adding tax values manually as well?

That's also something we have to do. Thank you for reminding me of that 🙇

**Comment by trjExpensify** [comment]
Couple of things to close this out, Melv:

- This PR for taxes: https://github.com/Expensify/App/pull/41785
- A PR follow-up from Hayata for removing `Add tags` when connected to an accounting solution

**Comment by hayata-suenaga** [comment]
> A PR follow-up from Hayata for removing Add tags when connected to an accounting solution

@trjExpensify, hiding `Add tags` button when there is an accounting connection is going to be handled in [this PR](https://github.com/Expensify/App/pull/41785)

**Comment by trjExpensify** [comment]
Hm, oh really? @SzymczakJ can you confirm?

**Comment by hayata-suenaga** [comment]
@trjExpensify, the following change from the linked PR makes the `Add tags` button hidden when there is an accounting connection 😄 

![Screenshot 2024-05-13 at 1 00 49 PM](https://github.com/Expensify/App/assets/98560306/92c7574c-ba3c-4435-a605-62297a369e73)

@SzymczakJ can double confirm

**Comment by SzymczakJ** [comment]
> @SzymczakJ can you confirm?

I'm confirming 😃. I'll reopen that PR tomorrow morning

**Comment by hayata-suenaga** [comment]
> > @SzymczakJ can you confirm?
> 
> I'm confirming 😃. I'll reopen that PR tomorrow morning

@SzymczakJ, do you mean [this PR](https://github.com/Expensify/App/issues/41274#issuecomment-2110483118) that was closed? I took the [screenshots](https://github.com/Expensify/App/issues/41274#issuecomment-2108695434) above from the PR.

**Comment by trjExpensify** [comment]
Yep, we're working through this PR now: https://github.com/Expensify/App/pull/42192

The merge free branch getting merged closed the original one.

**Comment by trjExpensify** [comment]
The PR for this issue was deployed and the taxes follow-up is being taken care of in Xero, so we're good to pay this tomorrow and close it out.

**Comment by trjExpensify** [comment]
Alright, so payment summary: 

- $250 to @s77rt for the C+ review of [this PR](https://github.com/Expensify/App/pull/41517). 

I've sent an offer.

**Comment by s77rt** [comment]
@trjExpensify Accepted! Thanks!

**Comment by trjExpensify** [comment]
Paid!
