### ISSUE TITLE
[HOLD for payment 2024-05-22] [HOLD for payment 2024-05-20] [Wave Collect] New Resources to Publish

### ISSUE THREAD

**Issue by VictoriaExpensify** [Expensify/App#41272]
## Publish Date - May 1
[[DRAFT]](https://docs.google.com/document/d/1m8fPDCkCOH6v0BQFjdbfTZ_MJ5tlweN594UltrJKK2c/edit)

**Comment by ren-jones** [comment]
I'm ready to be assigned! I also requested access to the doc.

**Comment by VictoriaExpensify** [comment]
Thanks @ren-jones - I've shared the doc 😄

**Comment by VictoriaExpensify** [comment]
Ren's finished reviewing and I've replied to his comments. Looking good!

**Comment by VictoriaExpensify** [comment]
Not OD

**Comment by VictoriaExpensify** [comment]
@ren-jones and @kevinksullivan - just checking to see what this is waiting on. Do you need me to do anything?

**Comment by VictoriaExpensify** [comment]
I'm unassigning myself because I'm not part of bugzero at the moment and I don't think I can complete the next steps here. Feel free to ping me if you need something from me

**Comment by kevinksullivan** [comment]
Checking with Maddy on this one
