### ISSUE TITLE
[HOLD for payment 2024-05-09] [HOLD for payment 2024-05-08] [$250] Troubleshoot - App crashes when clicking Reset and refresh after inviting user to the room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41275]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a room
3. Invite a member to the room
4. Go to Account settings > Troubleshoot
5. Click Clear cache and restart
6. Click Reset and refresh

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/540b0c16-6ddd-4905-bc1a-5fc8f700354a

[logs.txt](https://github.com/Expensify/App/files/15156567/logs.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a66317be07c94f84</li>
        <li>Upwork Job ID: 1785195026765955072</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>suneox | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@robertjchen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by godofoutcasts94** [comment]
I think this is the regression caused by this [PR](https://github.com/Expensify/App/pull/39230)

**Comment by francoisl** [comment]
Ah ok, makes more sense. Let's go with your proposal then @suneox.  Can you double-check if we also need to make the same change in [this other effect](https://github.com/Expensify/App/blob/942c851a6bcdb4d41df61a97bc097e14424f1017/src/components/OptionListContextProvider.tsx#L90), it also uses `personalDetails`.

**Comment by sonialiap** [comment]
Payment summary
- @suneox requires contributor $250 - paid ✔️ 
- @alitoshmatov reviewer $250 - offer pending ⏳

**Comment by alitoshmatov** [comment]
@sonialiap I was not involved in reviewing. So no payment needed for me

**Comment by sonialiap** [comment]
Thanks for letting me know
