### ISSUE TITLE
[HOLD for payment 2024-05-22] [QBO] Implement support for importing more than one of `Classes`, `Customers/Projects` or `Locations` on the tags page

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41279]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.68-0
**Reproducible in staging?:** Y 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714438462878199?thread_ts=1714400674.229349&cid=C036QM0SLJK

## Action Performed:
1. Create a workspace on NewDot
2. Go to More Features > Tags > Enable (you need this step for now because otherwise Tags won't show in the LHN after you connect to QBO to see the imported coding, apparently that's going to be worked on https://github.com/Expensify/Expensify/issues/387834#issuecomment-2083773292)
3. Connect to QBO
4. Go to `Import` 
5. Check both `Classes` and `Customers/Projects` are `Imported, displayed as tags` (should be the default like OldDot for now)
6. Go to the `Tags` page in the LHN
7. Observe only the values for `Classes` are shown on the page

## Expected Result:
1. When more than one of `Classes`, `Customers/Projects`or `Locations` are selected for import, the Tags page table will represent each distinct tag level imported from QBO
2. If the tag level is required, `Required` will be added to the status column in the table instead of `Enabled || `Disabled`

<img width="831" alt="image" src="https://github.com/Expensify/App/assets/16232057/fcf54c34-7b4c-4238-a2d7-40362238c0b4">

3. Behind the "Settings" button on the `Tags` page header in the RHP:
   3a. the toggle for "Members must tag all spend" will remain, allowing users to bulk toggle on/off making all tag levels mandatory. 
   3b. the `Custom tag name` field will be removed; users will be able to set the `Custom tag name` a level deeper for each of the tag levels (see 4b. below)

![image](https://github.com/Expensify/App/assets/16232057/cf07ecd0-20ff-4032-adb0-1346e16d97bd)

4. Clicking on a tag level name in the table will open the RHP, which will contain:
  4a. A `required` toggle, when enabled it makes the tag level required coding on the workspace and sets `Required` in the main `Tags` page table
  4b. A `Custom tag name >` push input row, that opens a simple "Custom tag name" page with a text input to rename the tag level. 

<img width="533" alt="image" src="https://github.com/Expensify/App/assets/16232057/fcf9ec92-e7c6-4ffc-877d-1af719e64dab">

  4c. A list of all of the tag values for that tag level (that opens up the individual tag value edit page with the same permissions and logic that exists today).

<img width="900" alt="image" src="https://github.com/Expensify/App/assets/16232057/ce01fbb8-524b-4392-8d01-713d40f14e4e">

  4d. checkboxes right-aligned each of the tag values to facilitate bulk select capabilities via the `[Selected X v]` button with the same permissions and logic that exists today.
<img width="658" alt="image" src="https://github.com/Expensify/App/assets/16232057/7a3f3cba-8b6b-4c91-ab0f-285198da965f">

## Actual Result:
Only the first level of tag is shown in the `Tags` page table, additional levels imported are ignored. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
See expected results for the intended solution. Below is today:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/cec07a01-9089-4de3-8b94-3ea4e8cba53f">

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/46f0b089-3fb9-464a-9ef9-1f8bfe2abaee">
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @hayata-suenaga @aldo-expensify @zanyrenney @narefyev91 @teneeto

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by narefyev91** [comment]
Will start working on this one

**Comment by hayata-suenaga** [comment]
Are there two PRs going on?

https://github.com/Expensify/App/pull/41337
https://github.com/Expensify/App/pull/41351

**Comment by trjExpensify** [comment]
We can close #41337. Nikolay is OoO now and @s77rt took over and had to create a new PR in #41351. 👍

**Comment by s77rt** [comment]
Checklist ^ not applicable. Not a bug but a new feature

**Comment by trjExpensify** [comment]
Yep, sounds good. Sitting out the regression period. 👍

**Comment by ikevin127** [comment]
@trjExpensify I reviewed PR https://github.com/Expensify/App/pull/41351 as C+. There were some regressions. Is there any payment due here given the facts ?

**Comment by trjExpensify** [comment]
Yeah, just the one from my perspective, so I've sent offers for $250. 👍

**Comment by trjExpensify** [comment]
@ikevin127 - paid!

**Comment by trjExpensify** [comment]
@s77rt - paid!
