### ISSUE TITLE
 Troubleshoot - App does not go offline when "Force offline" is toggled on

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41276]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Troubleshoot
3. Toggle on "Force offline"
4. Send a message in any chat

## Expected Result:
App will go offline when "Force offline" is toggled on

## Actual Result:
App does not go offline when "Force offline" is toggled on

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e816d6ac-170d-4f1c-b585-73c2f286cf32

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nodebrute** [comment]
@tienifr I think this might be a regression caused by your [PR](https://github.com/Expensify/App/pull/39595).

**Comment by puneetlath** [comment]
@tienifr are you able to look into that one? Otherwise, let's revert it.

**Comment by francoisl** [comment]
Removing the blocker label on this one based on Marc's note [here](https://github.com/Expensify/App/issues/41266#issuecomment-2084208373) and [here](https://expensify.slack.com/archives/C9YU7BX5M/p1714443722767329).
