### ISSUE TITLE
[HOLD for payment 2024-05-08] Send invoice - App returns to member list when selecting a workspace via keyboard

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41271]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (New feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- There are at least two workspaces.

1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount and select a participant.
4. Click on the workspace under "Send from".
5. Use keyboard to navigate and select a different workspace.
6. Repeat Step 2 to 5 but using mouse instead of keyboard.
## Expected Result:
When selecting a workspace using keyboard, app will return to confirmation page (Step 6 behavior).

## Actual Result:
When selecting a workspace using keyboard, app returns to participant selection page.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/2a355dae-444b-4839-99e2-acc4e7f245c3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by m-natarajan** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by marcaaron** [comment]
Haven't got a chance to look at this yet, but @cristipaval seems related to https://github.com/Expensify/App/pull/40015

It looks like something we could fix as a follow up.

**Comment by cristipaval** [comment]
Thanks @marcaaron! yes, we're on it

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to take this one
Cc @cristipaval

**Comment by cristipaval** [comment]
CP requested already

**Comment by cristipaval** [comment]
[PR](https://github.com/Expensify/App/pull/41332) merged and deployed to staging
