### ISSUE TITLE
[HOLD for payment 2024-05-22] Send invoice - Right caret disappears after editing and saving details several times

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41287]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (New Feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount and select a participant.
4. In the workspace chat, click on the preview.
5. Edit and save any row several times (scroll down the page to show the latest messages too).
## Expected Result:
Right caret on each row will not disappear.

## Actual Result:
Right caret on each row disappears after editing and saving the details several times.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/5072594c-e14a-4d54-89ee-497abb21d1af

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by m-natarajan** [comment]
@MonilBhavsar FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MonilBhavsar** [comment]
Demoting from blocker as it is a non blocking minor UI issue for a new feature
Have asked PR authors if they want to take a look https://github.com/Expensify/App/pull/40015#issuecomment-2084428617

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue 
cc @cristipaval

**Comment by cristipaval** [comment]
#vip-billpay related. @danielrvidal

**Comment by danielrvidal** [comment]
I updated to low as I don't think this is a normal flow but I do think itis a good clean up.

**Comment by slafortune** [comment]
@waterim do you have an update?

**Comment by waterim** [comment]
Hello @slafortune @MonilBhavsar 
I was OOO as we had public holidays in Poland
I'm continuing now!

**Comment by MonilBhavsar** [comment]
Thanks for update! 👍

**Comment by rushatgabhane** [comment]
@slafortune could you please add payment summary for review of https://github.com/Expensify/App/pull/41768#issuecomment-2104315990

**Comment by rushatgabhane** [comment]
1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by MonilBhavsar** [comment]
Closing this as it was a regression and was fixed by original PR authors. Thanks all!

**Comment by JmillsExpensify** [comment]
I received a payment request for this PR, so I'm re-opening the issue to get a pament summary

**Comment by MonilBhavsar** [comment]
Ah, I see Rushat was not a review in the original PR.

Payment Summary: Pay $250 to Rushat for reviewing and testing PR

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
