### ISSUE TITLE
[HOLD for payment 2024-05-09] [QBO] Updating syncTax causes validation error in the backend

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#41282]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Create workspace
2. Enable "Accounting" in "More Features"
3. Connect QBO
4. Go to "Import"
5. Open chrome dev console / network tab
6. Toggle "Import" in Taxes

## Expected Result:
The backend shouldn't throw an error

## Actual Result:
The validation here throws and error:

<img width="851" alt="image" src="https://github.com/Expensify/Auth/assets/87341702/15c27527-5bd1-4621-849c-e25aca4467ca">
<img width="1023" alt="image" src="https://github.com/Expensify/Auth/assets/87341702/83187b3f-601a-4302-aa72-5773cc97595b">

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010a0373ee0247c987</li>
        <li>Upwork Job ID: 1785129617320554496</li>
        <li>Last Price Increase: 2024-04-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by aldo-expensify** [comment]
cc @hayata-suenaga @trjExpensify 

Found while fixing taxes here: https://github.com/Expensify/App/pull/41283

**Comment by rushatgabhane** [comment]
requested payment here - https://staging.new.expensify.com/r/4001258192044328

**Comment by rushatgabhane** [comment]
not sure if i can point to the offending PR because it's a backend validation bug

**Comment by hayata-suenaga** [comment]
> requested payment here - https://staging.new.expensify.com/r/4001258192044328

@rushatgabhane, which PR did you review? 😄

**Comment by rushatgabhane** [comment]
hahaha my bad, no pr reviewed here

**Comment by trjExpensify** [comment]
Cool, closing!
