### ISSUE TITLE
[HOLD for payment 2024-06-20][$250] Send invoice - Inconsistency in merchant requirement during and after invoice creation

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (New feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount and select a participant.
4. Create the invoice without merchant.
5. Click on the invoice preview in the workspace chat.
6. Click Merchant.
7. Save it without entering a merchant.
## Expected Result:
There should be consistency whether Merchant is required in confirmation page and invoice details page.

## Actual Result:
In confirmation page (Step 4), invoice can be created without Merchant.
In invoice details page (Step 7), error shows up when saving empty merchant.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/95c79e93-cb02-40f5-be47-e1c70dacd6d5

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d9923b61ac021d5</li>
        <li>Upwork Job ID: 1785194578665390080</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 102525791</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by m-natarajan** [comment]
@miljakljajic FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by robertjchen** [comment]
Does not appear to be a serious deploy blocker to me and can be addressable by external contributors 👍

**Comment by robertjchen** [comment]
Agreed, I think we should keep it consistent and have it as a required field as you described: "any IOU in a workspace a merchant is required"

**Comment by danielrvidal** [comment]
Yup, marking this as low. Solid clean up but not necessary to release so we should clean it up after we finish other high priority items.

**Comment by mollfpr** [comment]
Sorry for the delay! I'll finish the review today!

**Comment by miljakljajic** [comment]
@mollfpr @GandalfGwaihir is this still waiting for review?

**Comment by robertjchen** [comment]
Agreed- let's proceed with @GandalfGwaihir 's proposal 👍

**Comment by robertjchen** [comment]
remaining steps above ^

**Comment by miljakljajic** [comment]
@mollfpr is owed 250 USD for their work on this issue.

@allgandalf has been paid via upwork

**Comment by mollfpr** [comment]
>[@mollfpr / @allgandalf] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr / @allgandalf] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr / @allgandalf] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 [@mollfpr / @allgandalf] Determine if we should create a regression test for this bug.

The regression step should be enough.

> [@mollfpr / @allgandalf] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Go to FAB > Send invoice.
2. Enter the amount and select a participant.
3. Click on send invoice button
4. Verify that you get an error immediately when trying to save without entering the merchant
5. Click on the merchant
6. Try saving merchant without entering any value
7. **Verify** that you get an error when trying to save an empty merchant name
8. 👍 or 👎

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr. Also, re-opening for the regression test.

**Comment by miljakljajic** [comment]
created an issue for the regression test
