### ISSUE TITLE
[$250] Send invoice - Chat shows skeleton briefly after the invoice is created

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41286]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (New Feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount and select participant.
4. Create the invoice.
## Expected Result:
Workspace chat will not show skeleton after the invoice is created.

## Actual Result:
Workspace chat shows skeleton briefly after the invoice is created.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [X] Android: mWeb Chrome
- [ ] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/9f36f112-4562-40c8-a451-ec3c761465b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f373288cc7fa0358</li>
        <li>Upwork Job ID: 1785187180184702976</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by m-natarajan** [comment]
@abekkala FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by techievivek** [comment]
Not a blocker, going to pass it to contributors.

**Comment by cristipaval** [comment]
#vip-billpay related. @danielrvidal could you please help prioritize?

**Comment by danielrvidal** [comment]
Seems like good clean up, but I would not say CRITICAL to launching for earnings. Marking it as medium. But yea, this would be great to have someone look into and clean up.

**Comment by cristipaval** [comment]
Taking this one on me as a cleanup issue of my project. It should be fixed by [my PR](https://github.com/Expensify/Auth/pull/10684), which improves the Onyx updates sent after the SendInvoice command.

**Comment by abekkala** [comment]
removed the external and help wanted labels and added Internal as @cristipaval is taking this one

**Comment by cristipaval** [comment]
@alitoshmatov could you please verify if this is still reproducible when you have a minute?

**Comment by abekkala** [comment]
@alitoshmatov just bumping the comment from Cristi for you!

**Comment by alitoshmatov** [comment]
Not reproducible
 
https://github.com/Expensify/App/assets/59907218/a5e82b1d-6dba-4f64-9e56-3dbc35ea7e8e

**Comment by cristipaval** [comment]
Thanks a lot for retesting. I'll close it.
