### ISSUE TITLE
[$250] Task - Blank page on going back from task report & Hmmm... not here on refreshing page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41308]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/40726
**Email or phone of affected tester (no customers):** applausetester+1117ck@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Start a group chat
2. Assign task in group chat
3. Select the task created
4. Tap on header to go back to original group chat page
5. Tap on header
6. Select leave option (Note: Concierge chat opens)
7. Tap on back button on task report details page (Note: Blank page opens)
8. Refresh the page (Note: Hmm...not here page opens)

## Expected Result:
Step 7 - Original group chat page should open on tapping back button on task report details page

## Actual Result:
Blank page on going back from task report & Hmmm... not here on refreshing page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6466144_1714444854245!IMG_3611](https://github.com/Expensify/App/assets/115492554/8b902f3f-fb3b-43d3-ae52-daff93a1f53a)
![Bug6466144_1714444854280!IMG_3610](https://github.com/Expensify/App/assets/115492554/c43c848f-8c20-4a0b-80e1-5fc76216419b)

https://github.com/Expensify/App/assets/115492554/6523fc3d-fb4e-4ac7-b1e1-fca1a7e31d64

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015219731b4ca417f8</li>
        <li>Upwork Job ID: 1786382361631195136</li>
        <li>Last Price Increase: 2024-05-17</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by twisterdotcom** [comment]
Still looking for some proposals here!

**Comment by twisterdotcom** [comment]
Still looking for proposals here.

**Comment by twisterdotcom** [comment]
Thanks @dominictb and @fedirjh.
