### ISSUE TITLE
[HOLD for payment 2024-05-22] [$250] [QBO]  Accounting - "Set up" button is top aligned in respective to "QBO" wording

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41301]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings > Workspaces > any workspace.
3. Go to Accounting.

## Expected Result:
"Set up" button should be centered in respective to "QBO" wording (like the button with Xero).

## Actual Result:
"Set up" button is top aligned in respective to "QBO" wording.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6466194_1714450631386!IMG_68C97308C675-1](https://github.com/Expensify/App/assets/115492554/7fcfedfa-0fde-474f-a2ae-e66a59ac2f5e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018936c575f9a5757c</li>
        <li>Upwork Job ID: 1785460764337295360</li>
        <li>Last Price Increase: 2024-05-01</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by izarutskaya** [comment]
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production
![Screenshot_20240430_105819_New Expensify](https://github.com/Expensify/App/assets/115492554/cfb2345f-7eea-4e6c-835c-04789caf8cf2)

**Comment by trjExpensify** [comment]
Moving this to polish, we wouldn't block the release on it 👍

**Comment by danieldoglas** [comment]
@Santhosh-Sellavel what do you think of the proposal above?

**Comment by Santhosh-Sellavel** [comment]
@neonbhai proposal LGTM!
Straight forward change!

C+ Reviewed
🎀 👀 🎀

**Comment by neonbhai** [comment]
Raising PR soon!

**Comment by CortneyOfstad** [comment]
@neonbhai can you provide an update on the PR by end of day today? Thanks!

**Comment by neonbhai** [comment]
[PR](https://github.com/Expensify/App/pull/41721) ready for review!

**Comment by CortneyOfstad** [comment]
Wasn't deployed the staging yet 👍

**Comment by CortneyOfstad** [comment]
@Santhosh-Sellavel can you have the checklist above completed as soon as you can? This will help avoid any delays in payment — thank you!

**Comment by Santhosh-Sellavel** [comment]
@neonbhai Can you help me with where this got broken? This implementation [PR](https://github.com/Expensify/App/pull/39652) and it was right, somewhere it got broken. Can you give a look?

**Comment by neonbhai** [comment]
@Santhosh-Sellavel hi, the style got deleted as part of this [this commit](https://github.com/neonbhai/Expensify/commit/a880061f4209fed1cbe9beda0d8e5b9d93925b4c#diff-092571817eef32a80193d637b77c77eee6579aa8e45f2ba7fb53d49f5ae4f852L53) in #40277

**Comment by Santhosh-Sellavel** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40277
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40277/commits/a880061f4209fed1cbe9beda0d8e5b9d93925b4c#r1608696318
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A Should be caught while testing
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A Simple UI Polish
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@CortneyOfstad] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by CortneyOfstad** [comment]
## Payment Summary

@neonbhai — paid $250 via Upwork
@Santhosh-Sellavel — to be paid $250 via NewDot

**Comment by Santhosh-Sellavel** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$250 approved for @Santhosh-Sellavel
