### ISSUE TITLE
[HOLD for payment 2024-06-11] Send invoice - App crashes when sending invoice via link when there's no workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User has no workspace.

1. Launch New Expensify app.
2. Copy send invoice link from web (https://staging.new.expensify.com/create/invoice/start/1/7783051691252045).
3. Paste the link on mobile app.
4. Click on the link.
5. Enter amount > Next.
6. Select participant.

## Expected Result:
In Step 4, app should display not here link.

## Actual Result:
In Step 4, user is able to proceed with send invoice flow.
After selecting participant in Step 6, app crashes. On web, it shows console error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/53c44d85-a16e-43db-944f-8553ea1dd964

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by izarutskaya** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-bills.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/b2e64c7b-d990-4817-a2e5-24f9e54739f8

**Comment by puneetlath** [comment]
I don't think this needs to be a deploy blocker, but @VickyStash do you want to look into it?

**Comment by VickyStash** [comment]
@puneetlath I'll take a look in a bit 👌  But I'm not sure if I can deal with it today (I'm going to be OOO 1st-8th of May)

**Comment by danielrvidal** [comment]
This feels like a good cleanup issue so marking it as Low. I can't imagine a user actually pasting in the send invoice URL in a real flow. So I think if you have other urgent work, I'd prioritize that @VickyStash. But I agree we should clean this up.

**Comment by VickyStash** [comment]
NOTE: I'll be OOO 1-8th of May 🌴

**Comment by davidcardoza** [comment]
@cristipaval can we source another contributor to lead this?

**Comment by cristipaval** [comment]
I think we want to completely hide this link now that we support invoices on NewDot. @davidcardoza could you please confirm?

**Comment by cristipaval** [comment]
> > I think we want to completely hide this link now that we support invoices on NewDot. @davidcardoza could you please confirm?
> 
> I thought beta is referred to by this. If not, @cristipaval @shubham1206agra Can you clarify what it means by that comment?

I am sorry for the confusion that I created with that comment. I misunderstood the repro steps.

**Comment by cristipaval** [comment]
I like the @tienifr solution to expand the `AccessOrNotFoundWrapper` and make it work for our current use case. I agree that it is cleaner and handles all pages of the flow automatically. Also, if we add a new page to the flow, it will be automatically handled, making the solution more scalable.

**Comment by lschurr** [comment]
@shubham1206agra @tienifr - please accept the offers sent today so that we can pay and close :)

**Comment by lschurr** [comment]
All set!
