### ISSUE TITLE
Taxes - Taxes dropdown button has lesser width compared to tags/categories/distance rates

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41311]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/40278
**Email or phone of affected tester (no customers):** kiatest.80+81@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:**  Applause-internal team

## Action Performed:
Precondition : Workspace enabled with all features - Categories, tags, distance rates & taxes
1. Go to Workspace settings
2. Select Taxes option
3. Select rows of data using the check boxes on the left side of the row (Note: Dropdown button has lesser width, not displayed for full width)
4. Go back to settings page
5. Select either Categories, Tags or Distance rates option
6. Select rows of data using the check boxes on the left side of the row (Note: Dropdown button display for full width)

## Expected Result:
Taxes dropdown buttons should have full width as similar to categories, tags & distance rates options

## Actual Result:
Taxes dropdown button has lesser width when compared to tags/categories/distance rates

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5df962a7-b578-4772-be33-3a31900e6e01

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by laurenreidexpensify** [comment]
@Expensify/design any thoughts here?

**Comment by shawnborton** [comment]
Yeah, that should be full width like the other pages. cc @luacmartins should we treat this as some kind of regression?

**Comment by luacmartins** [comment]
No, I noticed that this button was using a different style. Put up a PR with a fix - https://github.com/Expensify/App/pull/41421

**Comment by shawnborton** [comment]
Awesome, thanks Carlos!

**Comment by laurenreidexpensify** [comment]
This is deployed to prod = thanks @luacmartins. Closing.
