### ISSUE TITLE
Workspace - Workspace members do not trigger notification after being invited to the room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Version 1.4.68-0 (1.4.68-0)
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/39313
**Email or phone of affected tester (no customers):** applausetester+yuriy.28.apr.new.admin@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1 . Create a workspace room
2. Invite a workspace member to the room
3. Invite a non-workspace member to the room
4. Check chat and LHN preview for the notifications

## Expected Result:
The user should be able to see all notifications about members invited to the room
Expected to see 2 users in the LHN and 2 notifications in the chat

## Actual Result:
Only Non-worksacpe members are counted in the LHN panel preview and are indicated in the chat notification after invitation.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a76e6f4c-d952-40da-94fe-fd42a6abd72c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by francoisl** [comment]
cc @dukenv0307 @DylanDylann if you could take a look please, this was noticed when testing https://github.com/Expensify/App/pull/39313.

**Comment by nkdengineer** [comment]
i'm working in this issue

**Comment by jasperhuangg** [comment]
@dukenv0307 yes, that is expected. We do nothing if you try to invite a user already in the room.

**Comment by jasperhuangg** [comment]
@dukenv0307 Ah sorry for misunderstanding. This behavior is currently expected based on what we have in the back-end. When someone is in a workspace, they can join the workspace room of their own free will, so we don't notify when they are invited to the room.
