### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] [Xero] Xero appears under "Other integrations" when it is manually synced

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41320]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings.
3. Go to Workspaces > any workspace.
4. Go to Accounting.
5. Set up Xero.
6. Expand "Other integrations" section.
7. Click 3-dot menu next to Xer.
8. Click Sync now.

## Expected Result:
Xero will not appear under "Other integrations" when it is manually synced

## Actual Result:
Xero appears under "Other integrations" when it is manually synced

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ed5b24bc-c736-4d62-a765-b24fb236c737

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174cf9740ce3f5618</li>
        <li>Upwork Job ID: 1785320209758396416</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mananjadhav** [comment]
I don't think this is a deploy blocker. @mountiny can chime in on this one.

**Comment by mananjadhav** [comment]
@ShridharGoel's proposal looks good. @mountiny @amyevans Should we be making this external?

**Comment by lakchote** [comment]
> Agreed it doesn't need to be a deploy blocker. I'm not sure what the plan is for Xero polish and @mountiny is OOO. @lakchote do you know? Should we make this external or do y'all have alternate plans for handling follow up issues?

Let's make this external, as it doesn't need to be internal only. 

We'll still need to make backend changes and create a new API command `SyncPolicyToXero`.

@ShridharGoel's proposal LGTM.

**Comment by lakchote** [comment]
Assigning @mananjadhav as he has the context on the issue.

**Comment by amyevans** [comment]
@ShridharGoel let us know when you expect to have the PR ready, thanks!

**Comment by trjExpensify** [comment]
PR merged into the freeze branch!

**Comment by lschurr** [comment]
Payment summary:

Contributor+: $250 @mananjadhav (requires payment through NewDot Manual Requests)
@ShridharGoel $250 (Sent new [offer in Upwork](https://www.upwork.com/nx/wm/offer/102692222))

**Comment by mananjadhav** [comment]
@trjExpensify quick check, if we this should be included centrally? or separately for me.

**Comment by trjExpensify** [comment]
Centrally yeah, this was part of the Xero imp!

**Comment by mananjadhav** [comment]
@lschurr There won't be any payout for me. Just @ShridharGoel.

**Comment by lschurr** [comment]
Great, thanks! I've updated the payment summary.

**Comment by lschurr** [comment]
@ShridharGoel please accept the offer in Upwork so that we can pay and close.

**Comment by lschurr** [comment]
Closing this one. @ShridharGoel please comment here when you've accepted the offer so that we can pay.

**Comment by lschurr** [comment]
Paid!
