### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Workflows - Offline indicator is present below the last option instead of page bottom

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41326]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go offline.
3. Go to Account settings > Workspaces > any workspace.
4. Go to Workflows.
5. Tap Submission frequency.

## Expected Result:
Offline indicator will be present in the bottom of the page.

## Actual Result:
Offline indicator is present below the last option.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/4fe1b669-f509-44e7-93f7-2703662f8acc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b48de547df48461b</li>
        <li>Upwork Job ID: 1787886904799145984</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath / @muttmuure</details>

**Comment by m-natarajan** [comment]
@muttmuure FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by muttmuure** [comment]
@hoangzinh there are some proposals to take a look at

**Comment by puneetlath** [comment]
@muttmuure is the BZ here. He'll handle payment.

**Comment by muttmuure** [comment]
Paid
