### ISSUE TITLE
Invoice - Room name displays the wrong name

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41321]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** yes
**Reproducible in production?:**  no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Create a workspace
2. Click on 'FAB' > Send Invoice > Enter amount > Click 'Next'
3. Select user > select workspace > click 'Send invoice'
4. Click on report header > Settings > Room name

## Expected Result:
Room name should display 'chat-report'

## Actual Result:
Room name displays '#hat report'

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b1ae2383-7636-4fb6-9e1e-2176ce9d4918

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by cristipaval** [comment]
I'll take this one, it is #vip-billpay related

**Comment by cristipaval** [comment]
demoting as it is a minor UI thing

**Comment by cristipaval** [comment]
#vip-billpay related. cc @danielrvidal

**Comment by cristipaval** [comment]
you're right, we should close this one
