### ISSUE TITLE
Send invoice - Merchant is not displayed in the invoice preview in the main chat for receiver

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41323]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No (New Feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Go to FAB > Send invoice.
3. [User A] Create an invoice with merchant and send it to User B.
4. [User A] Note that merchant is displayed in invoice preview in the main chat.
5. [User B] Navigate to the invoice workspace chat.
## Expected Result:
Merchant will be displayed in the invoice preview in the main chat for User B.

## Actual Result:
Merchant is not displayed in the invoice preview in the main chat for User B.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a053aaa7-41e3-4220-bb93-417637678a40

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01522edd8c168d9599</li>
        <li>Upwork Job ID: 1785603668502433792</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@jliexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by cristipaval** [comment]
demoting

**Comment by jliexpensify** [comment]
@cristipaval this should be `Internal` right?

**Comment by cristipaval** [comment]
yes, internal for now
