### ISSUE TITLE
[HOLD for payment 2024-06-03] VIP Split: Resource Update Request - Referral Programme 

### ISSUE THREAD

**Issue by laurenreidexpensify** [Expensify/App#41346]
Publish Date 1 May

Draft [here](https://docs.google.com/document/d/1NSvJfd14TS2-q4btO_zQrLecVt0fyqVbWu4NPJ5ntM4/edit)

To note these are three tiny changes to an existing doc, should take less than a minute to review hopefully! 

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by laurenreidexpensify** [comment]
Bumped Ren in Slack, this one is ready for review / implementation

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by laurenreidexpensify** [comment]
Perfect @ren-jones 👍 all yours

**Comment by laurenreidexpensify** [comment]
NB - we're in a deploy freeze now, so any PRs on this won't be merged until next week

**Comment by laurenreidexpensify** [comment]
Ren pointed out this is currently on Expensify Classic site rather than NewDot - I missed that detail, so we need to migrate this over to the correct hub.

**Comment by laurenreidexpensify** [comment]
thinking more about this, while I agree this should live on newdot, it's fine for us to push the simple changes now. I think the whole partner programme section will need to be migrated, but we can do that at a later point and this doesn't need to be blocked on that.
