### ISSUE TITLE
[HOLD for payment 2024-06-28] [$500] Android - LHN - Magic glass icon overlaps text

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41349]
Version Number: 1.4.68-0
Reproducible in staging?: Y
Reproducible in production?: Y
If this was caught during regression testing, add the test name, ID and link from TestRail: [expensify.testrail.io/index.php?/cases/view/2990351](https://expensify.testrail.io/index.php?/cases/view/2990351)
Issue reported by: Applause - Internal Team

Action Performed:
Precondition: User is logged in Android mobile application. Preferences - #focus

Unpin all chats in LHN
Mark all chats in LHN as read
Expected Result:
"All caught up.." UI is displayed. No visual issues with text

Actual Result:
"All caught up.." UI is displayed. Magic glass icon is overlaps the text annotation
![image](https://github.com/Expensify/App/assets/22508304/afc7bff1-37a8-47f8-ba61-800b168469e0)

Workaround:
Unknown

Platforms:
Which of our officially supported platforms is this issue occurring on?

 Android: Native
 Android: mWeb Chrome
 iOS: Native
 iOS: mWeb Safari
 MacOS: Chrome / Safari
 MacOS: Desktop
Screenshots/Videos
Add any screenshot/video evidence

Bug6466750_1714490725789!1714490435348

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+sort%3Aupdated-desc)

<details><summary>Issue Owner</summary>Current Issue Owner: @ShridharGoel</details>

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
I can replicate the experience, but I'm not sure if this issue is device-specific because my `+` icon is overlapping with the copy. 
![image](https://github.com/Expensify/App/assets/8107070/46337a49-55d6-4a2b-ab63-ebf9d4911219)

**Comment by alexpensify** [comment]
@Santhosh-Sellavel - when you get a chance, can you please review if this proposal will fix the issue? Thanks!

**Comment by Santhosh-Sellavel** [comment]
AFAIK We can use Icon inline in other places as well. So waiting for other proposals.

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, May 7, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel My proposal doesn't change the functionality of inline icons at other places.

Yes, I am aware of that. Let's wait for other proposals.

**Comment by Santhosh-Sellavel** [comment]
Still waiting for other proposals.

**Comment by alexpensify** [comment]
@dubielzyk-expensify, we need Design feedback here; see the test examples: https://github.com/Expensify/App/issues/41349#issuecomment-2091508356. Thanks!

**Comment by dubielzyk-expensify** [comment]
I don't think we'd wanna go specific with left aligning on Android here. We'd want all platforms to behave and look the same. Are the icons actually put inline with the text or are they absolutely positioned?

Can I get a screenshot of how this looks on all platforms?

**Comment by dubielzyk-expensify** [comment]
cc @Expensify/design for visibility

**Comment by shawnborton** [comment]
> I don't think we'd wanna go specific with left aligning on Android here. We'd want all platforms to behave and look the same. Are the icons actually put inline with the text or are they absolutely positioned?

Yup, big agree with that

**Comment by dannymcclain** [comment]
>I don't think we'd wanna go specific with left aligning on Android here. We'd want all platforms to behave and look the same. Are the icons actually put inline with the text or are they absolutely positioned?
>
>Yup, big agree with that

Same. I would rather get rid of the icons and replace them with text rather than create custom styles for different platforms.

i.e. `Find a chat using the search button above, or create something using the plus button below.`

**Comment by alexpensify** [comment]
Thank you, Design team, for the feedback. @Santhosh-Sellavel can you please review the updated proposal based on the recent feedback? Thanks!

**Comment by alexpensify** [comment]
@Santhosh-Sellavel - any update here? Thanks!

**Comment by Santhosh-Sellavel** [comment]
@alexpensify Not sure what's expected here?

Do we want icons in the text and Show a different alignment for android alone?

Or Just get rid of icons and replace them with Text? Like @dannymcclain said [here](https://github.com/Expensify/App/issues/41349#issuecomment-2107635752)

cc: @Expensify/design

**Comment by shawnborton** [comment]
Ideally we would just solve this on Android to look identical to other platforms. Is that an option?

**Comment by Santhosh-Sellavel** [comment]
Yes, we don't have a proposal for that yet.

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

@mallenexpensify - I need help here to ensure that we get proposals and they are reviewed. I'm trying to avoid this one going stale. Thanks!

**Comment by mallenexpensify** [comment]
Updated OP and raised price to $500

**Comment by mallenexpensify** [comment]
@Santhosh-Sellavel 👀 plz on the updated proposal above from @ShridharGoel .  Thx

**Comment by Santhosh-Sellavel** [comment]
Can you reassign this @mallenexpensify, while I'm away. 

cc: @Expensify/contributor-plus Any volunteers please take, thanks!

**Comment by allroundexperts** [comment]
I can take over!

**Comment by iwiznia** [comment]
Assigned @ShridharGoel. Not sure how to trigger a new reassignment for C+ though... @mallenexpensify or @alexpensify do you know?

**Comment by mallenexpensify** [comment]
Removed @Santhosh-Sellavel and assigned @parasharrajat .  Should be all set.

**Comment by alexpensify** [comment]
Thanks, @mallenexpensify, for the help here. I'm back online and taking over again as the BZ member.

**Comment by alexpensify** [comment]
Weekly Update: The PR is going through the review process.

**Comment by alexpensify** [comment]
Weekly Update: The PR is moving along in the review process.

**Comment by alexpensify** [comment]
Flagging that the payment day is on June 20

**Comment by MitchExpensify** [comment]
Added QA tests before realizing you were assigned here @alexpensify 😆

**Comment by alexpensify** [comment]
I appreciate you @MitchExpensify 😄

**Comment by alexpensify** [comment]
Easy Melvin, the payment date is set for June 28.

**Comment by alexpensify** [comment]
I will complete the payment process tomorrow, but @ShridharGoel please access the Upwork invite for this Job: https://www.upwork.com/jobs/~0180fc9a6de0dbe388

It looks like automation didn't kick in here and I needed to create a manual job because the last one closed.

**Comment by alexpensify** [comment]
Payouts due: 2024-06-28

- [ ] Contributor: $500 @ShridharGoel 
- [ ] Contributor+: $500 @parasharrajat 

Upwork job is [here](https://www.upwork.com/jobs/~0180fc9a6de0dbe388).

Status: Waiting for @ShridharGoel to accept the Upwork job. @parasharrajat please submit a request in Chat. Thanks!

**Comment by alexpensify** [comment]
There is no update yet. The offer is pending in Upwork and needs to be approved by @ShridharGoel. Heads up, I'm OOO this week, but I'm trying to check in sporadically to help finish the required process here. I'll try to check again on Wednesday morning to see if I can complete the next steps for this GH.

**Comment by JmillsExpensify** [comment]
$500 approved for @parasharrajat

**Comment by mallenexpensify** [comment]
@ShridharGoel can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0180fc9a6de0dbe388

**Comment by alexpensify** [comment]
Closing - I've completed the payment process in Upwork.

https://github.com/Expensify/App/issues/41349#issuecomment-2197323366
