### ISSUE TITLE
[HOLD for payment 2024-05-22] [Wave Collect] Settings > Security  > Close Account 

### ISSUE THREAD

**Issue by alexpensify** [Expensify/App#41348]
Publish Date: May 1, 2024
Priority 4: https://expensify.slack.com/archives/C02QSAC6BJ8/p1714250035618949
Tracking GH: https://github.com/Expensify/Expensify/issues/381571
Draft: https://docs.google.com/document/d/1ji5f5Wsa1lguTyh2jb34LhHMESQNhtu3alou1oReBVQ/edit?usp=sharing

cc @ren-jones

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by alexpensify** [comment]
Closing this was deployed to production and payment will be handled elsewhere.
