### ISSUE TITLE
[HOLD for payment 2024-05-09] [$250] [Guided Setup Stage 2] Rename the Track and budget personal spend to Track and budget expenses

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#41350]
Problem: We’re embracing Track as being a critical flow for new users to Try New Expensify, both for the earnings call and in general. Pushing someone down the Submit flow too early forces them to share the product before they have tried it themselves. Currently, Track is either promoting a sole proprietor case OR personal use, which means employees likely will not choose it. Additionally, if people select Track for business, we automatically create a workspace for them to use with their account. This is problematic if an employee selects that and then doesn’t undergo the bottom-up like submitting to an employer.

Solution: Update the onboarding options to make Track the most logical thing for both sole props and Employees to select. @zsgreenwald is already planning on making similar updates, but we need to fast-track these updates to support our release. Thus we need to do the following asap: 
1. Rename the `Track and budget personal spend` in the onboarding flow to `Track and budget expenses`
  - Expensify DM/tasks already work for this case. Bottom-up already works.
2. Remove `Track business spend for taxes` as an option. 
  - This removes us from creating a workspace in any Track flows.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d70e701d2c9b48d8</li>
        <li>Upwork Job ID: 1785366415813079040</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by s77rt** [comment]
Thanks for the proposals. This should be straightforward work so going with the first proposal @ShridharGoel 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/41350#issuecomment-2086196462)

**Comment by mountiny** [comment]
Happy to take this over as i have worked on this feature

**Comment by mountiny** [comment]
Thanks @ShridharGoel can you please raise the pr? I will create a clean up for backend tomorrow

**Comment by danielrvidal** [comment]
@ShridharGoel, I apologize for the late request. Could we make one more small update that I forgot after seeing your screenshot: 

Could you have the order be:
- Track and budget expenses
- Manage my team's expenses
- Get paid back by my employer
- Chat and split expenses with friends 
- Something else

**Comment by tgolen** [comment]
Thanks for taking this one, Vit!

**Comment by mountiny** [comment]
@ShridharGoel can you please raise a follow up pr with the updated order? What is your eta?

**Comment by mountiny** [comment]
$250 to @ShridharGoel and to @s77rt

**Comment by johncschuster** [comment]
On i!

**Comment by johncschuster** [comment]
I've issued payment to @s77rt. Thanks for your hard work! 🎉 

@ShridharGoel I see your offer is [here](https://www.upwork.com/nx/wm/offer/102102791), can you accept that? Once accepted I can issue payment to you as well. Thank you!

**Comment by johncschuster** [comment]
Bumped @ShridharGoel in Slack to accept the offer 👍

**Comment by johncschuster** [comment]
Bumped again in Slack

**Comment by johncschuster** [comment]
Payment has been issued! 🎉
