### ISSUE TITLE
Testing for overdue label adding

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#41353]
Testing to see when this issue goes overdue for @rushatgabhane as the issue owner. 

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by mallenexpensify** [comment]
@rushatgabhane how does this show in your K2?

**Comment by rushatgabhane** [comment]
@mallenexpensify it shows as overdue in my K2

<img width="1076" alt="image" src="https://github.com/Expensify/App/assets/29673073/a6d85afc-44ef-4ef4-8985-c741d584b751">

**Comment by mallenexpensify** [comment]
Thanks Rushat, I'm going to leave it open to see when it goes overdue again.

**Comment by rushatgabhane** [comment]
overdue

**Comment by mallenexpensify** [comment]
Thanks for playing along @rushatgabhane , will close this out before we implement any sort of _tracking_ for overdue issues (which is TBD, along with many other improvements)
