### ISSUE TITLE
[$250] Unable to send or receive money 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41365]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** @mallenexpensify  and @deetergp 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714498536508719
 
## Action Performed:
Report, if someone internal wants to look at the logs: https://staging.new.expensify.com/r/64247315 

1. Created split request via Desktop for lunch
2. Noticed it didn't go through
3. Attempted to send/receive money between us and it's not working. Scott added me to a new split with multiple people and the transaction doesn't show he and I

## Expected Result:
To be able to transfer funds
## Actual Result:
Unable to transfer funds
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by mallenexpensify** [comment]
This might be helpful? I just filtered my console by `splitb` cuz Marc rsaid "the command should be SplitBill or SplitBillAndOpenReport"

<img width="450" alt="image" src="https://github.com/Expensify/App/assets/22508304/c4a0da72-ce70-4c81-b44a-b287a2805957">

**Comment by deetergp** [comment]
Interesting… It looks like the JSON inside the `"splits":[]` array is not JSON encoded — all of the double quotes are escaped with backslashes which I think would make them unreadable to NewDot.

**Comment by mallenexpensify** [comment]
Unsure what's up, looks like my $1 test to Scott might have gone through.  
<img width="275" alt="image" src="https://github.com/Expensify/App/assets/22508304/73e4aa26-c36f-45cf-abe9-9470a426439b">

<img width="840" alt="image" src="https://github.com/Expensify/App/assets/22508304/c6a2ff55-2753-4149-80aa-6367aad1a684">


<img width="535" alt="image" src="https://github.com/Expensify/App/assets/22508304/cfee5d8b-d9b4-4746-9bf3-a012bf1d981b">

**Comment by deetergp** [comment]
I think I got it…
<img width="612" alt="Screenshot 2024-05-13 at 9 55 05 AM" src="https://github.com/Expensify/App/assets/766197/6e4f7403-9d12-41a4-8680-a3f58f0bf16f">

**Comment by mallenexpensify** [comment]
Closing for now, the $1 thing seems to work, I'm unsure what happened to splits we might have lost, hopefully it was mostly a wash.
