### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$500] Deeplinking to a whisper results in "hmm it is not here " page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41370]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714415566362469

## Action Performed:
1. Copy a link to a whisper in a chat
2. Send it to someone else who doesn't have access to that whisper, but who does have access to the chat.
3. Have that other person click the link

## Expected Result:
They should be taken to the report as if they just opened it, and no comment should be linked.

## Actual Result:
hmm it's not here page is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/06b650a8-2853-4240-8c07-a297558ccf94

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012634f8ccbb4f7594</li>
        <li>Upwork Job ID: 1790412850565140480</li>
        <li>Last Price Increase: 2024-05-22</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102448221</li>
</ul></li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment]
@roryabraham which roadmap project do you think this is linked to?

**Comment by laurenreidexpensify** [comment]
@roryabraham I haven't made this external yet - can you confirm if you think this is connected to a roadmap project? thanks

**Comment by laurenreidexpensify** [comment]
@roryabraham bump thanks

**Comment by roryabraham** [comment]
Whoops, sorry for not seeing this earlier. Yes, this is front-end and can be external.

**Comment by laurenreidexpensify** [comment]
Waiting for proposals

**Comment by laurenreidexpensify** [comment]
Increased bounty

**Comment by MonilBhavsar** [comment]
Looks good 👍

**Comment by laurenreidexpensify** [comment]
QA ongoing

**Comment by MonilBhavsar** [comment]
@allroundexperts mind doing the checklist when you have a moment, please

**Comment by laurenreidexpensify** [comment]
Payment Summary: 

- C+ $500 @allroundexperts requires payment through NewDot Manual Requests
- Contributor $5000 @tienifr paid via Upwork

**Comment by laurenreidexpensify** [comment]
@MonilBhavsar can you do a me a favour, when @allroundexperts confirms checklist can you please close out and write the regression test (if needed) using this template - https://github.com/Expensify/Expensify/issues/new?assignees=applausebot&labels=QA%2C+Daily%2C+qa-test&projects=&template=AddOrUpdateQATests_TEMPLATE.md&title=QA+-+Add%2FUpdate+test+to+TestRail. I am going parental leave for rest of year tomorrow and seems a bit unnecessary to assign a BZ for that outstanding step. Thanks!

**Comment by MonilBhavsar** [comment]
Yes of course!

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/30269
2. https://github.com/Expensify/App/pull/30269/files#r1650198707
3. N/A
4. A regression test would be helpful. The test steps given in the OP should be sufficient.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
