### ISSUE TITLE
[Awaiting Payment 25th June] [QBO] Implement the `Required` toggle in the RHP with multiLevel tags.

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41374]
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1714503891769479?thread_ts=1714400674.229349&cid=C036QM0SLJK) and a follow-up to [this PR](https://github.com/Expensify/App/pull/41351).

1. We need to implement a new command to allow making an individual tag level required (i.e Customers required, Classes not required)
2. Add the `Required` toggle in the RHP of each tag level when multiTags are enabled with QBO, like so:

<img width="533" alt="image" src="https://github.com/Expensify/App/assets/16232057/efaf7526-4eed-423f-b595-29f81c37df73">

CC: @luacmartins @s77rt @hayata-suenaga @aldo-expensify @zanyrenney

**Comment by trjExpensify** [comment]
That PR is still in review.

**Comment by trjExpensify** [comment]
That PR has merged. @hayata-suenaga this is backend right to implement that command?

**Comment by hayata-suenaga** [comment]
@trjExpensify, yes it involves the backend change.

Currently, we have [`SetPolicyRequiresTag`](https://github.com/Expensify/Web-Expensify/blob/7e624947ee5c04d8039ec12c8471e07dae71272f/lib/PolicyAPI.php#L6576-L6584).

[That code is just enabling all tags in the tags list if there is a tags list](https://github.com/Expensify/Web-Expensify/blob/7e624947ee5c04d8039ec12c8471e07dae71272f/lib/Policy.php#L3974-L3986) (I assume this means that the parent level tags or multi level tags).

We either need to create a new Web-E command or modify the existing command to accomodate the multi level tag situation.

I'll try to work on this but might need some help from @aldo-expensify. I'll open a draft PR today and assign @aldo-expensify so that we can work together.

**Comment by trjExpensify** [comment]
Cool, I was looking at this on OldDot early to see what we call when we set one of the levels as required:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/47c2b4c4-4049-46dd-8bf3-b91299ca76d1">

.. and equally, enable/disable one of the imported tag list's tag values:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/3f40f20f-fba7-41d6-99fb-f165082e79d2">

Not sure if you looked at that, or if it's helpful here.

**Comment by hayata-suenaga** [comment]
### Memo for myself

[`Policy_Taglist_Set_Required`](https://github.com/Expensify/Web-Expensify/blob/dea645c4ef67e77476ab52d3062caa4e7da7dd05/api.php#L2295-L2303)

`tagListIndex` -> index of the tag list? each tag list doesn't have an ID?
`requireTagList` -> boolean indicating if each tag list is required

[`PolicyAPI::setTaglistRequired`](https://github.com/Expensify/Web-Expensify/blob/dea645c4ef67e77476ab52d3062caa4e7da7dd05/lib/PolicyAPI.php#L2354-L2374)

**Comment by hayata-suenaga** [comment]
Is there something that needs additionally done for the command meant for New Expensify?

**Comment by hayata-suenaga** [comment]
Reopened an[ App PR](https://github.com/Expensify/App/pull/42972) here for this issue (the previous one has issues with merge conflicts) 🙇

**Comment by aldo-expensify** [comment]
Fixed lint issue with PR https://github.com/Expensify/App/pull/42972

**Comment by hayata-suenaga** [comment]
With Aldo's final help, [the PR](https://github.com/Expensify/App/pull/42972) has been deployed. removing the `reviewing` label

**Comment by hayata-suenaga** [comment]
Payment for @s77rt for the reviewer role after the regression period.

**Comment by hayata-suenaga** [comment]
Checked the above deploy blocker and commented there

**Comment by trjExpensify** [comment]
Looks like we're working on a follow-up here.

**Comment by hayata-suenaga** [comment]
Yes, Rodrigo is working on a regression fix in [this PR](https://github.com/Expensify/App/pull/43769)

**Comment by hayata-suenaga** [comment]
[The fix](https://github.com/Expensify/App/pull/43769#issuecomment-2183480326) for the regression was deployed to production.

The payment is handled in [this issue](https://github.com/Expensify/App/issues/43758). Closing this issue now. Thank you everyone!

**Comment by trjExpensify** [comment]
Alright, but doesn't that mean @s77rt is required payment of $125 for the [initial PR](https://github.com/Expensify/App/pull/42972)?

**Comment by hayata-suenaga** [comment]
that's right! Good thing I didn't close this issue 😓

**Comment by hayata-suenaga** [comment]
@trjExpensify, if you could handle that payment, I'd appreciate it 🙇

**Comment by trjExpensify** [comment]
Cool, @s77rt sent you an offer! Payment summary as follows: 

- $125 for the C+ review of the PR 

Thanks!

**Comment by s77rt** [comment]
@trjExpensify Accepted! Thanks!

**Comment by trjExpensify** [comment]
Paid!
