### ISSUE TITLE
[QBO] Features in `More features` remain locked after disconnecting the QBO integration 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.68-3
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714512653698929?thread_ts=1714400674.229349&cid=C036QM0SLJK

## Action Performed:
1. Connect a workspace to QBO 
4. Go to More Features 
5. Observe the locked toggles on the `Categories`, `Tags` and `Taxes` menu items
6. Go back to Accounting > three dot menu > Disconnect QBO > confirm
7. Go back to More features
8. Observe the locked toggles remain on the menu items
9. Toggle off Accounting 
10. Observe the locked toggles are removed from the menu items

## Expected Result:
When you disconnect a workspace from QBO, the coding menu items for `Categories`, `Tags` and `Taxes` should not be locked anymore. 

## Actual Result:
They remain locked until you disable `Accounting`. 

## Workaround:
Yes, disable `Accounting`. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/00e17987-d512-4516-a211-91c5ee7478d0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @hayata-suenaga @aldo-expensify @zanyrenney  @s77rt @narefyev91 @teneeto

**Comment by hayata-suenaga** [comment]
We're relying on the `hasAccountingConnection` variable to decided if these toggle buttons should be locked or not.

The value of the variable is set [here](https://github.com/Expensify/App/blob/e665d5c17b48f1103ddc3e025ce0974cd4c410c3/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L50).

`const hasAccountingConnection = !!policy?.areConnectionsEnabled && !!policy?.connections;`

**Comment by s77rt** [comment]
This has been fixed in https://github.com/Expensify/App/pull/40984. We can close this

**Comment by trjExpensify** [comment]
Got it, maybe let's verify that once it hit staging.

**Comment by hayata-suenaga** [comment]
removed the hold

**Comment by s77rt** [comment]
Just retested, the issue is fixed 🎉 

https://github.com/Expensify/App/assets/16493223/3c3e033f-836d-406c-9213-e7bbd808bb77

**Comment by trjExpensify** [comment]
Niceeeeee! Closing!
