### ISSUE TITLE
[$250] [Violations] Expense - RBR appears in report preview but no violation message in transaction thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Submit an expense to any user.
4. Submit another expense to the same user again.
5. Click on the expense preview in the main chat.
6. Click on the preview that has red dot.

## Expected Result:
There should be violation message in transaction thread for expense that has a red dot.

## Actual Result:
Red dot appears in expense preview in the report, but there is no violation message in the transaction thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f404a62d-2a68-41cf-8a3f-bba9c5bd54f8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2a023aff3cd4279</li>
        <li>Upwork Job ID: 1785642421475364864</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by MariaHCD** [comment]
Able to reproduce on dev:

https://github.com/Expensify/App/assets/12268372/7f7d5e0a-f172-489a-9cc3-44a9c387c19f

There doesn't seem to be an error with the creation of the money requests themselves and I don't see any recent changes to the `shouldShowRBR` logic in ReportPreview component that might've caused this. Adding External to get more eyes on this.

**Comment by MariaHCD** [comment]
Seems like there's a `cashExpenseWithNoReceipt` violation on those transactions.

![Screenshot 2024-05-01 at 5 51 21 PM](https://github.com/Expensify/App/assets/12268372/8008c8ff-f62e-44b5-987a-2fd6ed3322f2)

I'm not super sure if these transactions should be flagged with this violation...

**Comment by MariaHCD** [comment]
Need to get some more eyes on this, raising in #wave-control: https://expensify.slack.com/archives/C06ML6X0W9L/p1714572168631129

And expensify-open-source: https://expensify.slack.com/archives/C01GTK53T8Q/p1714571039687799?thread_ts=1714565359.644339&cid=C01GTK53T8Q

**Comment by francoisl** [comment]
Discussed internally ([link 1](https://expensify.slack.com/archives/C06ML6X0W9L/p1714572168631129), [link 2](https://expensify.slack.com/archives/C03U7DCU4/p1714567681539279?thread_ts=1712769915.660199&cid=C03U7DCU4)), this can be fixed from the backend and violations are still under a beta, so we're not going to block the NewDot deploy on this.

**Comment by robertjchen** [comment]
With regards to `Hold`- it is a reportAction, but we do have some [violation logic in place](https://github.com/Expensify/Web-Expensify/pull/40146/files) at the transaction level. We could make an exception there to avoid flagging held requests as a violation if it happens to be on an IOU report.

**Comment by cead22** [comment]
If I'm understanding Jason correctly, we want to return HOLD violations on IOUs. Is that right?

**Comment by JmillsExpensify** [comment]
Yes, that's correct. Hold is a feature of all report types.

**Comment by cead22** [comment]
I submitted a PR to stop returning `cashExpenseWithNoReceipt` for new dot, which should fix this

**Comment by JmillsExpensify** [comment]
@cead22 Can we close this issue out now?

**Comment by cead22** [comment]
Yup
