### ISSUE TITLE
[Awaiting Payment May 16th] [Wave Collect] [Xero] Put Xero display logic under a specific beta

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#41394]
We need to put Xero under a specific beta since QBO will be released sooner and they share the same accounting menu.

**Comment by lakchote** [comment]
@ShridharGoel since I've assigned myself already, no need to submit proposals. Thank you.

**Comment by trjExpensify** [comment]
Deployed to prod 9 hours ago. Assigning Rushat for the PR review.

**Comment by trjExpensify** [comment]
Payment summary as follows: 

$250 to @rushatgabhane for the C+ review of the PR

**Comment by trjExpensify** [comment]
Payment will be handled centrally when we wrap the project, we can close this as the regression period is over.
