### ISSUE TITLE
[$250] Thread – Reply is present when create a second level thread and delete comment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41399]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4530392
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Go to any chat and send a message.
4. Create a thread and send a comment.
5. Create a second level thread and don’t send messages
6. Go back and delete the comment from step 4
7. Observe that there are no comments in the thread
8. Go back to parent chat

## Expected Result:
There is no reply under the message when create a second level thread and delete comment

## Actual Result:
Reply is present under the message when create a second level thread and delete comment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/86d8412b-d4a4-4614-846f-81b82c5f4297

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011780584d68800980</li>
        <li>Upwork Job ID: 1785737118212800512</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by ikevin127** [comment]
This looks BE related based on findings from [proposal](https://github.com/Expensify/App/issues/41399#issuecomment-2088265483) and https://github.com/Expensify/App/issues/41399#issuecomment-2088430676 -> therefore I think it should be fixed internally.

**Comment by garrettmknight** [comment]
Thanks @ikevin127 - moving to `Internal`.

**Comment by garrettmknight** [comment]
Waiting for volunteer.

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by garrettmknight** [comment]
Still waiting for a volunteer

**Comment by ikevin127** [comment]
@garrettmknight Should I unassign myself as C+ reviewer since this is going to be handled internally ?

**Comment by garrettmknight** [comment]
@ikevin127 We'll still use you for review when we get a volunteer.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by ikevin127** [comment]
Still awaiting a volunteer.

**Comment by ikevin127** [comment]
Looking for a volunteer!

**Comment by garrettmknight** [comment]
Still looking for a volunteer!

**Comment by garrettmknight** [comment]
Still looking for a volunteer!

**Comment by garrettmknight** [comment]
Still looking for a volunteer!

**Comment by garrettmknight** [comment]
Still looking for a volunteer!

**Comment by garrettmknight** [comment]
Still looking for a volunteer!

**Comment by garrettmknight** [comment]
Still looking for a volunteer!

**Comment by garrettmknight** [comment]
Still looking for a volunteer!

**Comment by garrettmknight** [comment]
Still looking for a volunteer!

**Comment by ikevin127** [comment]
Looking for a volunteer 🎲

**Comment by ikevin127** [comment]
Looking for a volunteer 🎲

**Comment by garrettmknight** [comment]
Still waiting for a volunteer.

**Comment by garrettmknight** [comment]
Still waiting for a volunteer.

**Comment by garrettmknight** [comment]
Still waiting for a volunteer.

**Comment by garrettmknight** [comment]
Still waiting for a volunteer.

**Comment by garrettmknight** [comment]
Still waiting for a volunteer.

**Comment by garrettmknight** [comment]
Still waiting for a volunteer.

**Comment by garrettmknight** [comment]
Still waiting for a volunteer.

**Comment by garrettmknight** [comment]
Closing since VSB is closed, will wait on real reporting to reopen.
