### ISSUE TITLE
[HOLD App PR 40443][Track Tax] After the IOU is created, the Tax rate changes to 0%

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41408]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/41264
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in to your HT account
3. Create a WS
4. Enable "Taxes"
5. Set "Tax Rate 1" as Workspace currency default
6. Navigate to the WS room
7. Create a manual IOU with default currency and Tax Rate 1
8. Navigate to the details of the created IOU

## Expected Result:
After the IOU is created, the Tax rate must remain the same as when the IOU was created

## Actual Result:
After the IOU is created, the Tax rate changes to 0%

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/666c613e-a334-4107-ae30-0ff6a03f61ad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by trjExpensify** [comment]
CC: @MonilBhavsar is this on your radar?

**Comment by MonilBhavsar** [comment]
Yes, we're already working on this issue in this PR https://github.com/Expensify/App/pull/40443
Let's put this on HOLD

**Comment by trjExpensify** [comment]
Sounds good! Bumping down to `Weekly`.

**Comment by MonilBhavsar** [comment]
We've merged the PR. This is fixed on main branch
