### ISSUE TITLE
[Wave Collect] [Xero] Organization page -  UX inconsistencies

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#41403]
Coming from - https://github.com/Expensify/App/pull/40984#pullrequestreview-2033355487

Bug 1: when opening the org page for the first time, no org is shown as selected.

<img width="261" alt="image" src="https://github.com/Expensify/App/assets/29673073/5462f36a-5fcc-4643-9f35-1643657e3d2e">

Expected: 
<img width="348" alt="image" src="https://github.com/Expensify/App/assets/29673073/54f7c21f-b52e-43bb-905a-7c523a84e799">

Bug 2: selecting an org should close the RHP.

https://github.com/Expensify/App/assets/29673073/d09f5215-a099-4259-8ef5-2e714bbd1dd5

**Comment by trjExpensify** [comment]
Hit production 2 weeks ago. Payment for Rushat will be central, we can close.
