### ISSUE TITLE
 IOU - Description is displayed while receipt is being uploaded

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41407]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2777980
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Start a manual request
2. Enter the amount and continue
3. On the final review page - Click on the 3 dot menu on the top right
4. Verify there's an option to attach a receipt
5. Click on the attach a receipt
6. Upload a large receipt
7. Enter a description of the request
8. Finish the request

## Expected Result:
The expense preview has a thumbnail preview of the receipt.
The description is NOT displayed while the receipt is being uploaded

## Actual Result:
The expense preview has a thumbnail preview of the receipt.
The description is displayed while the receipt is being uploaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b3d77fb0-63b0-4988-9de2-f8f603eb07ad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-split

**Comment by JmillsExpensify** [comment]
On second though, I don't think this is a bug so closing.
