### ISSUE TITLE
[$250] Tags settings – Unable to change disabled tag with “0” name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41414]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4531402
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as Collect WS Admin
3. Navigate to WS settings
4. Open tags settings
5. Add a tag with name “0”
6. Disable this tag
7. Edit the tag name and save

## Expected Result:
Tag name is changed

## Actual Result:
Error message appears, the tag name is changed to "0"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0b869c31-512c-405c-b1db-d77a447ccfd9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01637f46b432d71e05</li>
        <li>Upwork Job ID: 1785661684153110528</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by slafortune** [comment]
I am able to recreate this - 
https://github.com/Expensify/App/assets/11725910/5b06d68b-9453-425e-8672-193ba8423ab1

**Comment by slafortune** [comment]
Internal issue not picked up yet

**Comment by slafortune** [comment]
no update

**Comment by slafortune** [comment]
I will be on vacation until June 4th - this is still an issue and needs an internal engineer, but probably pretty low priority.

Adding another BZ in the meantime, will take back on the 4th.

**Comment by Christinadobrzyn** [comment]
I am still able to reproduce this issue 

<img width="1640" alt="image" src="https://github.com/Expensify/App/assets/51066321/845bd300-e9e0-4ed6-b0ba-165a8d467363">

waiting for this to get picked up.

**Comment by Christinadobrzyn** [comment]
asking tom if he can buddy check my thinking on the release timeframe - https://expensify.slack.com/archives/C036QM0SLJK/p1716884563004939

**Comment by Christinadobrzyn** [comment]
looking for a volunteer

**Comment by Christinadobrzyn** [comment]
Internal issue so I'm working on finding someone to pick this up

**Comment by Christinadobrzyn** [comment]
still trying to find a volunteer

**Comment by mvtglobally** [comment]
Still reproducible 

https://github.com/Expensify/App/assets/43995119/c922f117-2b6d-488c-9d51-b243eb2eeea1

**Comment by Christinadobrzyn** [comment]
Ah yes, this is still reproducible on the Android and Safari - bummer

**Comment by slafortune** [comment]
Checking for a volunteer here - https://expensify.slack.com/archives/C03UK30EA1Z/p1718046706608739

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
I've checked the data. I can confirm:
1. The app can change a tag name offline. 
2. The tag can be enabled. The bug is still replicable.
3. The error comes from the backend. 

<details><summary>Details</summary>
<p>

<img width="1728" alt="Screenshot 2024-06-11 at 13 46 48" src="https://github.com/Expensify/App/assets/57314631/45d8761a-ac35-4efd-9ba5-3615990c4973">
<img width="1728" alt="Screenshot 2024-06-11 at 13 47 06" src="https://github.com/Expensify/App/assets/57314631/d1757e42-66d8-4a8a-a3df-dfccf7c03bd9">


</p>
</details> 

We need an internal engineer to take a look at the issue 🙂

**Comment by Gonals** [comment]
Taking a look!

**Comment by Gonals** [comment]
It seems that we also can't change a tag's name to `0`. This also happens in OldDot

**Comment by rezkiy37** [comment]
So are we going to fix it on the backend side?

**Comment by slafortune** [comment]
Looks like this is fixed - I was able to change the disabled tag name that was named 0
