### ISSUE TITLE
[Wave Collect] [Xero] Import page - The app crashes when navigating to Xero Import Page for the first time.

### ISSUE THREAD

**Issue by hungvu193** [Expensify/App#41411]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Go to Workspace => Accounting
2. Choose `Setup` button next to Xero.
3. Continue with Xero setup
4. Notice that App crashes right after user finished the setup.

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/16502320/c93ce660-dee1-44f4-9fd5-54311ffc1bee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
cc @lakchote

**Comment by rushatgabhane** [comment]
Looks like the bug is fixed. We can close this issue

https://github.com/Expensify/App/assets/29673073/00f2db22-1ea6-480c-a52b-7e532f3ea721

**Comment by lakchote** [comment]
I've experienced some issues that prevent me from connecting to the IS server right now

> Looks like the bug is fixed. We can close this issue

I had trouble with my android environment so to save time, I've asked @rushatgabhane to double check (thank you).

Looks like everything is fine, @hungvu193 could you test it again please?

**Comment by hungvu193** [comment]
I'm afk but will test it ASAP

**Comment by hungvu193** [comment]
Confirmed it's fixed 🎉. Closing

https://github.com/Expensify/App/assets/16502320/1a9fd6d6-57db-475a-9aaa-23121e400d30
