### ISSUE TITLE
[QBO] Fix the `&amp;` encoding issue to avoid a crash when accessing the tag value edit screen

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41413]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.68-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://github.com/Expensify/App/pull/41351#issuecomment-2088234372

## Action Performed:
1. Create a workspace
2. Enable `Accounting` in `More features` (you need the `accountingOnNewExpensify` beta if you don't have it already)
3. Enable `Tags` in More Features as well before step 4. (this is necessary until another bug is fixed)
4. Connect to QBO 
5. Go to `Import` > ensure `Classes` are imported (as those contain tag values with encoding problems)
6. Go to `Tags` in the LHN of the workspace settings
7. Click on the `Classes` row to see the tag values in the RHP
8. Observe the encoding display issue 

## Expected Result:
1. The tag value should be displayed with the `&`
2. Accessing the tag's value edit page shouldn't result in a 404. 

## Actual Result:

QBO value is `G&A`
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/074b1d8a-26cc-4125-aac0-0ee32bd88688">

Displayed in Classic as `G&A`, stored in the database as `G&amp;A`
<img width="1448" alt="image" src="https://github.com/Expensify/App/assets/16232057/0dda4dd7-d687-4509-85e8-6ab41445a913">

Displayed in NewDot as `G&amp;A`, stored in Onyx as `G&amp;A`
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/9e521317-5ae1-4f96-a6bc-944e58cae2ca">

Clicking on a tag value with an encoding issue results in a 404 page not found with the URL path `/settings/workspaces/49F212315A5E269A/tag/G%26amp%3BA`

![image](https://github.com/Expensify/App/assets/16232057/878301bc-a98d-4210-8d42-e85003e042e6)

## Workaround:
Rename the tag value to `G&A`

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/1569ebdc-2b47-4019-abf6-c817f662603e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @hayata-suenaga @aldo-expensify @zanyrenney @roryabraham @s77rt @ikevin127
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017816fb16ca08ca42</li>
        <li>Upwork Job ID: 1785653594291445760</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment]
I walked through the sync process and this is the line where we're encoding the name https://github.com/Expensify/Web-Expensify/blob/40e18ca5d87f6b8a1bad2848d50123c96958fac7/lib/Policy.php#L3587
I'll take a look and see if we can skip this for newDot

**Comment by MonilBhavsar** [comment]
Also shared thoughts here https://expensify.slack.com/archives/C03TQ48KC/p1714576924994139?thread_ts=1707467669.800489&cid=C03TQ48KC

**Comment by trjExpensify** [comment]
Niceee! What's our next step?

**Comment by MonilBhavsar** [comment]
Will be making a PR and testing oldDot for regression

**Comment by trjExpensify** [comment]
Wahoo, nice one Monil!

**Comment by MonilBhavsar** [comment]
PR is in review 🙏

**Comment by MonilBhavsar** [comment]
Web-E PR is deployed to production and this issue is fixed
