### ISSUE TITLE
[$250] Task title becomes top aligned after navigating to unauthorized group URL

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41419]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4534139
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. [User A] Create a group with 2 or 2+ members
3. [User A] Create a task and assign it to user C (User C must not be a member of the created group)
4. [User C] Sign in and open the assigned task by User A
5. [User A] Copy the URL of the group
6. [User C] Navigate to the copied URL on step 5
7. [User C] Open the assigned task again

## Expected Result:
The title of the assigned task is centered

## Actual Result:
The title of the assigned task becomes top aligned after trying to navigate to the unauthorized group

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0494cd1f-63d9-459e-82fe-1d8a8d5fdd8f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144f9cdfd8e1a0d86</li>
        <li>Upwork Job ID: 1787780238439182336</li>
        <li>Last Price Increase: 2024-05-21</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@greg-schroeder FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-vsb

**Comment by greg-schroeder** [comment]
Sorry, adding `External` -- next up is proposal review from C+

**Comment by greg-schroeder** [comment]
Bump @ishpaul777

**Comment by greg-schroeder** [comment]
Go away Melvin

**Comment by greg-schroeder** [comment]
Bump on proposal review <3

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment]
Yup, sorry, doing!

**Comment by greg-schroeder** [comment]
I'm closing this as resolved as we weren't able to reproduce - I believe it was fixed elsewhere. If anyone disagrees, please comment and we can reopen.
