### ISSUE TITLE
Assign task -  Text color changes to secondary while typing over a highlighted mark down description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41425]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a task with a description using a "Quote" markdown (e.g "> test")
3. Open the task report page
4. Click on description
5. Press CTRL + A to select all the text
6. Start typing anything (Don't use backspace before typing)

## Expected Result:
Text color uses primary color that is bold and white

## Actual Result:
Text color changes to secondary color that is grey and not bold

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4873227a-716d-4ef1-9184-6ae110f1d75b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment]
I think this is extreme polish. considering [this](https://expensify.slack.com/archives/C03SC9DVD/p1714689152448009)

> [we should prioritise bugs that]  happen in the real world while using NewDot for real work, versus conveniently in a lab under a microscope.

going to close this out.
