### ISSUE TITLE
[HOLD for Payment: 2024-05-15] Expense Report - Top and bottom borders of "Next step" are cut off when the text has one line

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41424]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Launch New Expensify app.
2. Create a new workspace.
3. Go to workspace settings > Workflows.
4. Tap Submission frequency.
5. Tap Manually.
6. Go to workspace chat.
7. Create a manual request.
8. Go to expense report.

## Expected Result:
The "Next step" top and bottom borders will not be cut off.

## Actual Result:
The "Next step" top and bottom borders are cut off. This only happens when "Next step" message has only one line.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c217da9a-b4f4-485a-a320-118474ce8253

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@dylanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by francoisl** [comment]
At the moment I'm unable to even set up a workspace with the "Manually" frequency, it just disables the option altogether. Tested on web but I don't think the platform matters. It could also be a backend issue, going to take a look.

https://github.com/Expensify/App/assets/2229301/2a1c0a14-5eca-443b-a4b5-be043e2903b8

**Comment by francoisl** [comment]
Ok, this sounds like a polishing issue and not a real blocker.

cc @dragnoir if you could take  a look please.

**Comment by ikevin127** [comment]
⚠️ Automation failed -> this should be on **[HOLD for Payment [2024-05-15]]** according to today's production deploy from [#41643 (comment)](https://github.com/Expensify/App/pull/41643#issuecomment-2101805137).

cc @dylanexpensify

**Comment by dylanexpensify** [comment]
@ikevin127 thanks, will update!

**Comment by ikevin127** [comment]
@dylanexpensify Is anything else needed from my side in order for the payment to be issued today ?

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @ikevin127 $250
- Contributor+: @dragnoir $250

[Please apply!](https://www.upwork.com/jobs/~01f13377227dc75c9a)

**Comment by ikevin127** [comment]
@dylanexpensify Applied: https://www.upwork.com/ab/proposals/1791197920848183297. Thank you!

**Comment by dylanexpensify** [comment]
All done!
