### ISSUE TITLE
[HOLD App PR 40443] [Track Tax] Tax applied during submission is not reflected in transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41449]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- There is a workspace with tax enabled
1. Go to staging.new.expensify.com
2. Go to FAB > Track expense
3. Track a manual expense
4. In 1:1 DM, click Categorize it from the whisper
5. Select a workspace and category
6. On confirmation page, fill in all details and add tax rate
7. Submit the expense
8. Go to transaction thread

## Expected Result:
Tax applied in Step 6 will be reflected in the transaction thread

## Actual Result:
Tax applied in Step 6 is not reflected in the transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/65d19c86-f98e-4bd1-8070-6f8608cf6574

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by jliexpensify** [comment]
Hi @MonilBhavsar - you're working on all Tax issues right? Have assigned you to take a look at this one. Thaaks!

**Comment by jliexpensify** [comment]
@MonilBhavsar can we close this issue, or would you prefer to keep it open until the PR is deployed?

**Comment by MonilBhavsar** [comment]
We can close this and reopen if required.
