### ISSUE TITLE
Markdowns - Text remains bold when use non-Latin letter after markdown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41452]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a25@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any chat
3. Enter text with markdowns (* bold for example)
4. Start typing Latin letter after markdown
5. Notice that the text is not bold any more
6. Delete the letter from Step 4 and add non-Latin letter or number

## Expected Result:
Text should not be bold after adding non-Latin letter or number after markdown

## Actual Result:
Text remains bold when use non-Latin letter after markdown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/297ba512-ef54-4e16-90f4-1ff258a32b00

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Christinadobrzyn** [comment]
Following our [SO](https://stackoverflowteams.com/c/expensify/questions/14418/14456#14456) - I think this is an edge case, won't affect many users and isn't a priority for ROI. Closing without action - we can reevaluate at a later date.
