### ISSUE TITLE
[HOLD for payment 2024-05-20] [QAB] Update the QAB for `Pay someone` to be `Pay %firstName%` instead

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41468]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.69-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714588923919309?thread_ts=1714400587.768059&cid=C036QM0SLJK

## Action Performed:
1. Go to global create > `Pay someone` > enter an amount > confirm 
2. Reopen global create
3. Observe the quick action reads `Pay someone`

## Expected Result:
Since we’ve updated `Send money` to `Pay someone`, one thing we've done in the DM create menu is change the label name to `Pay %firstName%`. Let's do the same in the quick action button, like so. 

If a displayName has been set:

>**Pay %firstName%**
>%primaryLogin%

<img width="319" alt="image" src="https://github.com/Expensify/App/assets/16232057/fa6880a9-6ddc-4bb0-86f6-7569ca1bc41b">

If a displayName hasn't been set, then: 

>**Pay %primaryLogin%**

<img width="316" alt="image" src="https://github.com/Expensify/App/assets/16232057/9b86be02-d938-4c6d-9e8e-f75fddcbb8e9">

## Actual Result:
The quick action button reads `Pay someone`, which was intended initially. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
N/A, design improvement. 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/e1887e5a-5015-4090-9d8e-e9d83e7b75e9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update the QAB for Pay someone to be Pay %firstName% instead

### What is the root cause of that problem?
We don't pass a custom name when rendering the FAB option: 
https://github.com/Expensify/App/blob/8b3def3121a5de9e28245382a5e0503da26733a8/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L371

### What changes do you think we should make in order to solve the problem?
We will pass the name using `ReportUtils.getPayeeName(quickActionReport)` here:

https://github.com/Expensify/App/blob/8b3def3121a5de9e28245382a5e0503da26733a8/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L371

```jsx
text: translate('iou.paySomeone', {name: ReportUtils.getPayeeName(quickActionReport)})
```

**Comment by Gonals** [comment]
@trjExpensify, I think we made a wrong assumption here. The subtitle is not the primary login of the user, but the report name, which is the primary login when there is no name set, and the full name when it is. I think it makes sense to hide it in all cases for this flow, as it will always either match the `someone` in `Pay someone` or be something like:

**Pay Alberto**
Alberto Cela

**Comment by trjExpensify** [comment]
Cool, so the two variations I would say are: 

<img width="770" alt="image" src="https://github.com/Expensify/App/assets/16232057/b854ef6a-03ee-45eb-8aca-d549ec8bf1e1">

**Comment by Gonals** [comment]
> Cool, so the two variations I would say are:
> 
> <img alt="image" width="770" src="https://private-user-images.githubusercontent.com/16232057/327456059-b854ef6a-03ee-45eb-8aca-d549ec8bf1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MTY3MzYsIm5iZiI6MTcxNDcxNjQzNiwicGF0aCI6Ii8xNjIzMjA1Ny8zMjc0NTYwNTktYjg1NGVmNmEtMDNlZS00NWViLThhY2EtZDU0OWVjOGJmMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA2MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkODQ5YmU5YmY3MzBhNDA2YzAyNjhjMjkyMDFmYjdlNmE4ZTJlY2E0ZDgzZDU0OGE2YzZmOTRlNGYzOGNmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JymtYrwXpTDg9eFb6K7brxoyaoDi5UAEQ0RfzRVAzJc">

I'm fine with this, but why not omit the Subtitle in both cases and just have either:

**Pay Sara Couto**
or
**Pay scv@expensify.com**
?

**Comment by trjExpensify** [comment]
Because the left is more standard in the pattern I would say. The exception we use then being when someone doesn't set a displayName, which we hope to be more rare in NewDot.

**Comment by trjExpensify** [comment]
Deployed to prod, no regression test needed as we've added one already. We also don't need to pay anyone eternal out. Closing!
