### ISSUE TITLE
[Awaiting Payment 23rd May] [QAB] 404 when clicked if your quick action button is set to a workspace that’s since been deleted

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41467]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.69-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714588862011939?thread_ts=1714400587.768059&cid=C036QM0SLJK

## Action Performed:
1. Go to global create > `Submit expense` > choose a workspace > confirm 
2. Reopen global create 
3. Verify you have the quick action button set to that workspace
4. Switch over to OldDot and delete the workspace (there's an unrelated bug preventing this action in NewDot natively right now)
5. Switch back to NewDot (maybe refresh if it's taking a hot minute to reflect that action)
6. Reopen global create
7. Click the quick action button
8. Observe the 404 page in the RHP

## Expected Result:
1. The quick action button should be able to be clicked 
2. After taking the first page action (BNP, receipt scan, enter distance) a participant selector should appear
3. At the top of the participant selector there should be text that reads: "You no longer have access to %reportName%. Pick a new destination for your quick action.”

<img width="282" alt="image" src="https://github.com/Expensify/App/assets/16232057/43318977-b8dd-470a-b154-bfa5a6167901">

## Actual Result:
Clicking the quick action button results in a 404 not found page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
No, a workspace can't be undeleted. They can "reset" their quick action button choice by using one of the main options in global create. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/dc576f8c-dd63-479b-87ef-4ca2cc1511bb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Talking to Alberto about this, there's a case where the user logs out and the QAB report isn't loaded anymore. So in that case, we'll: 

1. Show `Update destination` in the subtext as we don't have the report name anymore
2. Don't use copy in the participant selector that includes the report name because we might not have it. 

![image](https://github.com/Expensify/App/assets/16232057/c8e1bf6c-78c3-44cb-8246-2381c880aaf9)

**Comment by trjExpensify** [comment]
Merged, awaiting a deploy!

**Comment by rojiphil** [comment]
Automation got missed here too. 
This was deployed to production on [09 May](https://github.com/Expensify/App/pull/41474#issuecomment-2101803958).
@trjExpensify Please note. This is pending payment to me as [C+ reviewer.](https://github.com/Expensify/App/pull/41474#issuecomment-2089895029)

**Comment by trjExpensify** [comment]
Nice! Payment summary as follows: 

- $250 to @rojiphil for the C+ review of the PR 

Regression tests for QAB have been added centrally. Thanks, offer sent!

**Comment by trjExpensify** [comment]
Paid!
