### ISSUE TITLE
[Invoice Rooms] Avatar not matching from InvoiceRoom header to InvoiceRoom invoice preview

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#41473]
If you look at the header on this invoice room and then the avatar on report preview, you can see the C is green in the header and then blue on the invoice preview. I have reproduced this. 

![image](https://github.com/Expensify/App/assets/2364487/72a6b57b-a879-4c4d-bc08-aaf7f2f634e3)

**Comment by danielrvidal** [comment]
Just for reference, it might have something to do with this: https://github.com/Expensify/App/pull/41316

**Comment by Nodebrute** [comment]
Regression from https://github.com/Expensify/App/pull/39637

**Comment by nkdengineer** [comment]
@thesahindia This will be fixed in this PR https://github.com/Expensify/App/pull/41485.

**Comment by grgia** [comment]
PR still in review

**Comment by rushatgabhane** [comment]
PR merged but not on staging yet

**Comment by davidcardoza** [comment]
I believe this was deployed to production here - https://github.com/Expensify/App/pull/41485 can someone confirm?

**Comment by rushatgabhane** [comment]
Yepp this is in production

**Comment by davidcardoza** [comment]
Closing this issue out, feel free to reopen if needed @cristipaval
