### ISSUE TITLE
[Wave Collect] [Xero] Add translations for sync stages

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#41486]
**Problem**

Right now, we're displaying confusing Xero sync keys for the sync stages.

It is confusing to the end user.

**Solution**

Let's translate the Xero sync keys to meaningful sync stages messages.

**Comment by trjExpensify** [comment]
PR in review

**Comment by trjExpensify** [comment]
(Make sure to assign the C+ that ends up reviewing this PR)

**Comment by trjExpensify** [comment]
PR hit staging yesterday.

**Comment by lakchote** [comment]
Assigning @pecanoro as she has helped with reviewing the PR and providing translations.

**Comment by pecanoro** [comment]
Closing since this has hit production now and I think we are handling payment separately?
