### ISSUE TITLE
Workspace - Unable to resolve host error after tapping on Choose in the Onfido page offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4534457&group_by=cases:section_id&group_id=283225&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with an expensifail account
2. Create a workspace
3. Enable Workflows from the workspace settings
4. Start adding a Plaid Regions bank with Onfido data
5. Stop at the Onfido page and go offline
6. Tap on the "Choose document" button
7. Tap on the "OK" button

## Expected Result:
"Content failed to load" page should be showing like on iOS.

## Actual Result:
"Unable to resolve host" error message appears after tapping on "Choose document" in the Onfido page offline. The screen is blank after tapping on "OK".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8e29a076-42a6-4247-b528-ba0a05a3b0d0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by stephanieelliott** [comment]
I think this is not worth solving -- the page shows an error indicative of being offline, I don't think it necessarily needs to match 1:1 with iOS.
