### ISSUE TITLE
Android - The new message marker gets half hidden behind the highlight indicator

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41491]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open Expensify staging app
2. Open a report
3. Send a message
4. Hold the message and click on reply in thread of the message
5. Send a reply inside the thread
6. Click on the subtitle to go back to the chat report
7. Send a new message
8. Mark the new message as unread

## Expected Result:
The word "New" doesn't get behind the highlight indicator

## Actual Result:
The word "New" gets half hidden behind the highlight indicator

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ba381488-86aa-4b42-8cf9-0beb688e1ae4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by miljakljajic** [comment]
@izarutskaya can you reshare the reproduction video? It's not opening for me and I can't reproduce
