### ISSUE TITLE
[$250] Send invoice - App crashes after creating invoice

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41504]
<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by m-natarajan** [comment]
@CortneyOfstad FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by grgia** [comment]
@dragnoir @DylanDylann could you confirm https://github.com/Expensify/App/issues/41504#issuecomment-2090774104

**Comment by grgia** [comment]
@DylanDylann @dragnoir assigning as a regression follow up

**Comment by francoisl** [comment]
@dragnoir Hi, just checking in - do you think you will you be able to submit a PR for this today?

**Comment by CortneyOfstad** [comment]
PR CPd for staging. Will continue to keep an eye on this 👍

**Comment by CortneyOfstad** [comment]
Was deployed to production 4 days ago!

**Comment by CortneyOfstad** [comment]
PR was deployed to production on May 6th — payment is being handled via the main GH [here](https://github.com/Expensify/App/issues/30360), so this can be closed 👍
