### ISSUE TITLE
Workspace - "Company address" shows up for employee when it is not set up

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a workspace.
- Company address is not set up for that workspace,

1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces.
3. Go to the invited workspace.

## Expected Result:
"Company address" will not show up for employee if it is not set up.

## Actual Result:
"Company address" shows up for employee when it is not set up.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0bfdf040-48e4-4797-b320-e277233515c4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@mallenexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by smelaa** [comment]
Hi, I am Aleksandra Smela from Software Mansion, an expert agency and I can work on this issue. I am also the author of https://github.com/Expensify/App/pull/38381

**Comment by francoisl** [comment]
The PR was deployed to production 3 days ago, all done here.
