### ISSUE TITLE
[HOLD for payment 2024-05-22] [CRITICAL] [VIP-Travel] Workspace - Unable to select country in Company address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Click Company address
4. Without entering address first, click Country
5. Select a country

## Expected Result:
The country is selected

## Actual Result:
The country is not selected. It shows the error "This field is required"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/50652516-0596-4565-9f2c-7d9bf292ca02

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment]
This is related to a new feature coming from this PR https://github.com/Expensify/App/pull/38381

cc: @smelaa @shubham1206agra

**Comment by rlinoz** [comment]
Oh this is a new feature and behind a beta, so no need to be a deploy blocker.

**Comment by anmurali** [comment]
I will post this bug to the PR https://github.com/Expensify/App/pull/38381 and they can look into it.

**Comment by smelaa** [comment]
Hi! I am Aleksandra Smela from Software Mansion, an expert agency and I am the author of https://github.com/Expensify/App/pull/38381. I can work on this issue.

**Comment by anmurali** [comment]
@s77rt - offer is [here](https://www.upwork.com/nx/wm/offer/102583301)

**Comment by s77rt** [comment]
@anmurali Accepted! Thanks!
