### ISSUE TITLE
Thread - App fails to highlight the parent message when returning to parent the first time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a report
3. Submit an expense
4. Open the expense report page
5. Send a message
6. Hover over the message and click on reply in thread
7. Send a message inside the thread
8. Click on the subtitle to return to the parent report (i.e the expense report page)

## Expected Result:
The originating parent message gets highlighted

## Actual Result:
The originating parent message doesn't get highlighted and app flickers once or twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ba171b65-c9b4-459c-8f2d-6afafa54cc06

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment]
I don't follow how this is a bug @lanitochka17 - can you confirm? This looks like acting as normal to me.

**Comment by zanyrenney** [comment]
bump @lanitochka17 if you can't clarify this for me, shall I close this? It doesn't seem like a bug.

**Comment by lanitochka17** [comment]
@zanyrenney The message was not highlighted in brown the first time, but was highlighted only after clicking on the subheading.

**Comment by zanyrenney** [comment]
This doesn't impact the user experience, nor does it relate to the app's performance or usage—it seems like polish. Seeing as it's not a user-reported bug, I am going to close this based on the guidance [here](https://expensify.slack.com/archives/C03SC9DVD/p1715094716671279)
