### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] BNP - Delay in showing new currency when selecting a new currency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41515]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Issue reported by:** Applause internal team

## Action Performed:

1. Launch New Expensify app.
2. Go to FAB.
3. Tap Submit expense.
4. Tap on the currency.
5. Select a different currency.
6. Expected Result:
7. When navigating back to BNP, the new currency will appear instantly in BNP.

## Actual Result:
When navigating back to BNP, the old currency is still seen in BNP for a while before it changes to the new currency.

## Workaround:
unknown

## Platforms:
Which of our officially supported platforms is this issue occurring on?

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
Add any screenshot/video evidence
Attaching both staging and production behavior videos

https://github.com/Expensify/App/assets/38435837/60777e80-39f1-4346-bf30-9949741f47cf

https://github.com/Expensify/App/assets/38435837/dd8e674e-3522-4a89-8653-9ceac0612d89

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192c095a5bdaf7ab7</li>
        <li>Upwork Job ID: 1787480317266833408</li>
        <li>Last Price Increase: 2024-05-06</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@amyevans FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by amyevans** [comment]
I can repro (tried on staging iOS native), but honestly it's barely noticeable, not worth blocking deploy over.

**Comment by jjcoffee** [comment]
Unassigning as I'm going OOO cc @laurenreidexpensify

**Comment by amyevans** [comment]
@rojiphil could you review the existing proposal please?

**Comment by laurenreidexpensify** [comment]
@rojiphil bump for review pls thanks

**Comment by rojiphil** [comment]
Apologies for the delayed response here. 
The alternate solution in @ZhenjaHorbach [proposal](https://github.com/Expensify/App/issues/41515#issuecomment-2091494688) using the promise and navigate approach LGTM. 
Also, as mentioned, we already follow this pattern in a similar situation elsewhere.
🎀👀🎀 C+ reviewed

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by amyevans** [comment]
I reproed on `main` on an Android emulator as well just to confirm. Will assign @ZhenjaHorbach, let us know when we can expect a PR. Thanks!

**Comment by laurenreidexpensify** [comment]
@amyevans can you confirm which Wave / VIP this fits under?

**Comment by amyevans** [comment]
Hmm I guess I'd call it #wave-collect polish since it relates to submitting an expense?

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ $250 @rojiphil pls accept offer in upwork + confirm regression steps thanks 
Contributor $250 @ZhenjaHorbach paid via upwork

**Comment by rojiphil** [comment]
> pls accept offer in upwork + confirm regression steps thanks

@laurenreidexpensify Accepted offer and completed BZ checklist. Thanks.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

- C+ $250 @rojiphil paid in upwork
- Contributor $250 @ZhenjaHorbach paid in upwork
