### ISSUE TITLE
[Awaiting Checklist Completion] Workspace - Unsupported browser notification appears on the Xero setup page (Android)

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41512]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #[41415](https://github.com/Expensify/App/pull/41415)
**Version Number:** 1.4.70-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal
**Slack conversation:** 
 
## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Enable "Accounting" on the WS settings page
4. Navigate to "Accounting"
5. Tap on the "Set up" button next to Xero

## Expected Result:
The browser should be switched to a supported one or if it's not possible, the notification shouldn't appear for users.

## Actual Result:
Unsupported browser notification appears on the Xero setup page.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6468935_1714661231507!Screenshot_20240502_164159_New_Expensify](https://github.com/Expensify/App/assets/38435837/264eeb85-1921-4dfe-9b2e-0294caca7f37)

https://github.com/Expensify/App/assets/38435837/39942580-3d51-48f4-a9f8-37c0dc22cda6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01609688787adfdcff</li>
        <li>Upwork Job ID: 1786384710813405184</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by m-natarajan** [comment]
@twisterdotcom FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by twisterdotcom** [comment]
Trying to recreate on iOS, my Android phone is at home. Added my test domain to the xero beta

**Comment by twisterdotcom** [comment]
Hmm, not an issue on iOS: 
![IMG_1383](https://github.com/Expensify/App/assets/9133401/0f8bdf6e-5a79-459b-a240-b0083b87190d)

**Comment by twisterdotcom** [comment]
Confirmed: https://expensify.slack.com/archives/C01SKUP7QR0/p1714742239560959?thread_ts=1714741936.915729&cid=C01SKUP7QR0

**Comment by jjcoffee** [comment]
I'm going OOO so unsassigning cc @twisterdotcom

**Comment by mananjadhav** [comment]
@gijoe0295 ’s  proposal looks good. 

🎀 👀 🎀 C+ reviewed

**Comment by lakchote** [comment]
@gijoe0295's proposal LGTM.

**Comment by mananjadhav** [comment]
@gijoe0295 Any updates on when the PR would be ready?

**Comment by twisterdotcom** [comment]
Hello, I'm back! Thanks @lakchote for assigning a new C+.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @mananjadhav paid $250 through NewDot Manual Requests (C+)
- @gijoe0295 paid $250 [here](https://www.upwork.com/nx/wm/workroom/37203933/] (Contributor)

**Comment by twisterdotcom** [comment]
Waiting on you @mananjadhav for the checklist.

**Comment by mananjadhav** [comment]
There is no offending PR for this one. We're using WebView and we added this as a follow up. Additionally we don't need a regression test for this one.

@twisterdotcom Payout for me will be after the whole Xero as a flat fee.
