### ISSUE TITLE
[HOLD for payment 2024-06-18] [$250] [Guided Setup Stage 2] "Meet your specialist" setup task not using proper Guide's calendar link

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#41522]
Version Number: N/A (v1.4.70-0)
Reproducible in staging?: Yes
Reproducible in production?: Yes
Email or phone of affected tester (no customers): Any new account
Logs: https://stackoverflow.com/c/expensify/questions/4856
Expensify/Expensify Issue URL:
Issue reported by: @francoisl 
Slack conversation:

**Action Performed:**

1. Create a new account
2. During the onboarding flow, pick the option "manage my team's expenses"
3. After completing the onboarding modal steps, open the task "Meet your setup specialist"
4. Look at the "schedule a call" link

**Expected Result:**
The link should point to the assigned guide's calendly link.

As discussed in [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1715643738395449?thread_ts=1714400621.865599&cid=C036QM0SLJK), we need to remove the guide link from the message if not present at the time of flow completion.

If the guide link is present in NewDot in time, no changes to the current flow.

If not, the message will omit the link and as the task is created in the backend, we need to recreate the message correctly with the link. This is the internal task in this case

**Actual Result:**

The link points to the fallback new.expensify.com value, despite having a value in Onyx
https://github.com/Expensify/App/blob/c5a1f96e7772592c0e1e2449b67dbc14afb35e02/src/libs/actions/Report.ts#L3055

<img width="1512" alt="327536868-2941f2bf-ce8d-4b7f-baff-81d96c8d2cce" src="https://github.com/Expensify/App/assets/16232057/c220688f-e028-4845-abf7-fca4c816bdc9">

**Platforms:**

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018008e7f232e1b5aa</li>
        <li>Upwork Job ID: 1788750602254168064</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
No idea why Melvin did that, will look at it [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1714678065776379). 

<img width="923" alt="image" src="https://github.com/Expensify/App/assets/16232057/401a2777-cacb-44fd-b931-5ca03273bc8a">

I've tried to restore Franc's wonderful words in the OP!

**Comment by Christinadobrzyn** [comment]
@rayane-djouah can you check out the above proposal when you have a moment? TY!

**Comment by trjExpensify** [comment]
Discussing next steps in [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1714739281192879?thread_ts=1714400621.865599&cid=C036QM0SLJK).

**Comment by Christinadobrzyn** [comment]
Just checking in here @rayane-djouah do you have everything you need to plan the next steps for this? Do you need anything from the team on what this should look like/how this should behave?

**Comment by Christinadobrzyn** [comment]
Just checking in here @rayane-djouah do you have everything you need to plan the next steps for this? Do you need anything from the team on what this should look like/how this should behave?

**Comment by Christinadobrzyn** [comment]
Awesome thank you @rayane-djouah - I'll add a HOLD for https://github.com/Expensify/App/issues/41589 while we retest

**Comment by Christinadobrzyn** [comment]
looks like this isn't fixed  

https://github.com/Expensify/App/assets/51066321/6eea9202-7ad8-4ba7-a1ae-ead4a2da92c2

Monitoring - https://github.com/Expensify/App/issues/41589

**Comment by Christinadobrzyn** [comment]
Thanks for checking @rayane-djouah - reached out in the [wave-collect convo ](https://expensify.slack.com/archives/C036QM0SLJK/p1715306520605489?thread_ts=1714400621.865599&cid=C036QM0SLJK)to see if we can get a volunteer.

**Comment by Christinadobrzyn** [comment]
following slack convo - https://expensify.slack.com/archives/C036QM0SLJK/p1715306520605489?thread_ts=1714400621.865599&cid=C036QM0SLJK

**Comment by Christinadobrzyn** [comment]
Still monitoring - https://expensify.slack.com/archives/C036QM0SLJK/p1715674089171819?thread_ts=1714400621.865599&cid=C036QM0SLJK

**Comment by Christinadobrzyn** [comment]
Still monitoring - https://expensify.slack.com/archives/C036QM0SLJK/p1715674089171819?thread_ts=1714400621.865599&cid=C036QM0SLJK

**Comment by Christinadobrzyn** [comment]
Awesome, @mountiny updated the OP so it's relevant. This is ready to be picked up internally.

**Comment by Christinadobrzyn** [comment]
Asking for a volunteer - https://expensify.slack.com/archives/C036QM0SLJK/p1715922344462719

**Comment by Christinadobrzyn** [comment]
Looks like @NikkiWines might be taking this?

**Comment by trjExpensify** [comment]
https://expensify.slack.com/archives/C036QM0SLJK/p1715922344462719 - Ah, I think you linked the wrong issue in the Slack post. 

@mountiny is likely going to look at this one next, but it's available for the time being.

**Comment by mountiny** [comment]
Yes, we discussed this one and we should make sure the copy is updated in case of the link missing so we do not lead user to wrong place. Then backend change will queue onyx update with the correct link.

At the moment focusing on performance related tasks I am assigned, keeping this on my radar for once those are done

**Comment by Christinadobrzyn** [comment]
Awesome! Thanks for the update!

**Comment by Christinadobrzyn** [comment]
I think this is on the internal engieneer radar when they have the bandwidth to pick it up. 

@rayane-djouah - My understanding is yes, we want to update this based on these expectations - https://github.com/Expensify/App/issues/41522#issuecomment-2123338936

**Comment by mountiny** [comment]
I think this will be easier handled internally

**Comment by Christinadobrzyn** [comment]
Just checking @mountiny do you think you'll be able to pick this up once your other assignments are done or do you think it would be better for me to search for another volunteer?

**Comment by Christinadobrzyn** [comment]
Awesome! That's great @mountiny! Thank you!

**Comment by Christinadobrzyn** [comment]
This is on @mountiny's radar so we'll keep this as is for now. Let me know if you'd prefer I seek another volunteer @mountiny!

**Comment by Christinadobrzyn** [comment]
Ah good reminder @rayane-djouah - don't we need a C+ on this?

**Comment by mountiny** [comment]
PR is in its final stretch now

**Comment by Christinadobrzyn** [comment]
Just a heads up - I'm going to be ooo until June 24th. 

@mountiny Are there any contributors that need to be paid for this? Doesn't look like it?

**Comment by mountiny** [comment]
Yeah I think we can close this now
