### ISSUE TITLE
[Android] Inline code shouldn't extend beneath the ReportActionItem component

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#41565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-1 
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

## Action Performed:

_Android Pixel 6a_

- Open any chat
- Send a couple of messages like this one: Nah, `Cash` is just not `Card` or `Distance`.`
- Try to scroll down

## Expected Result:
- A) There code should not extend beneath the height of the component
- B) You should be able to scroll down and read all of the message

## Actual Result:
- A) Both messages seem to overlap
- B) You can't scroll down to read `Distance` on the bottom-most message

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native (Pixel 6a)
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

A) <img width="426" alt="Screenshot 2024-05-03 at 10 52 03" src="https://github.com/Expensify/App/assets/10736861/f0062746-740e-4543-8e58-b25ef191ce5c">
B) ![1000030910-2024-05-03 10_03_44 755](https://github.com/Expensify/App/assets/10736861/f5728521-7085-4564-a952-866dc6e6cc3b)

_There is a chance this is related to comment [linking](https://github.com/Expensify/App/issues/40644), but I think it is more likely to be live markdown._

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Not overdue, still seeking proposals!

**Comment by eh2077** [comment]
Not overdue, still seeking proposals!

**Comment by eh2077** [comment]
Not overdue, still seeking proposals!

**Comment by kadiealexander** [comment]
@Julesssss could you please try reproducing this again to confirm it's still a bug?

**Comment by QichenZhu** [comment]
I can still reproduce this on **Pixel 6a**.

![Screenshot_20240520_204650](https://github.com/Expensify/App/assets/57348009/c4adb566-d2be-4e53-ba14-29b0a98105fe)
