### ISSUE TITLE
[$250] IOU - Green dot on LHN remains when cancel request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41566]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4536087&group_by=cases:section_id&group_order=asc&group_id=229063
**Email or phone of affected tester (no customers):** applausetester+gm196@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. User A crates 3 manual money request with User B
2. User B pay the requests
3. User A creates new manual request with User B
4. User A delete the request
5. Take a note of green dot on User B LHN when deleted request disappear

## Expected Result:
Green dot should disappear

## Actual Result:
Green dot on LHN remains when request is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3a3f1f93-81d5-472a-ae2b-cf8e59192ee1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013596a2fc8e8f656e</li>
        <li>Upwork Job ID: 1787797094777081856</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by dylanexpensify** [comment]
reproduced!

**Comment by mananjadhav** [comment]
@dylanexpensify Can we assign an internal engineer here? Looks like we'll need a BE fix.

**Comment by dylanexpensify** [comment]
@quinthar mind seeing if anyone is available for this on vip-vsb team?

**Comment by mananjadhav** [comment]
@dylanexpensify This is marked Internal and not picked yet. Do we need to assign someone? or mark it Weekly?

**Comment by dylanexpensify** [comment]
Waiting for someone with bandwidth. Cc @quinthar

**Comment by dylanexpensify** [comment]
Same

**Comment by dylanexpensify** [comment]
Similar

**Comment by dylanexpensify** [comment]
Mel, look!

**Comment by dylanexpensify** [comment]
Oh, it's on Manan, my B

**Comment by mananjadhav** [comment]
> Waiting for someone with bandwidth. Cc @quinthar

@dylanexpensify  I thought this was marked internal and hence I asked [here](https://github.com/Expensify/App/issues/41566#issuecomment-2119308207). Waiting for someone to pick this.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mananjadhav** [comment]
@dylanexpensify are you able to reproduce this?

**Comment by mananjadhav** [comment]
@dylanexpensify quick bump.
