### ISSUE TITLE
[Wave Collect] [Xero] Fix the ConnectionLayout component

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#41560]
**Problem**

The ConnectionLayout component has some extra padding issues which prevent other PRs from reusing it.

Please see discussion [here](https://github.com/Expensify/App/pull/41554#discussion_r1588837027). 

**Solution**

Let's fix the component and refactor the other Xero PRs to use it.

**Comment by hungvu193** [comment]
Taking a look 👀

**Comment by carlosmiceli** [comment]
Hey @lakchote, sorry to bother you, but do I need to do something here?It seems reviewed and merged, right?

**Comment by lakchote** [comment]
> Hey @lakchote, sorry to bother you, but do I need to do something here?It seems reviewed and merged, right?

Hi @carlosmiceli, yes nothing to do on your part here! You shouldn't have been assigned, I'm correcting the assignees list.

Also, not a blocker https://github.com/Expensify/App/issues/41754#issuecomment-2099225842

**Comment by trjExpensify** [comment]
https://github.com/Expensify/App/pull/41561 - deployed to prod 9 hours ago
https://github.com/Expensify/App/pull/41660 - deployed to prod 9 hours ago
https://github.com/Expensify/App/pull/41664 - deployed to staging 9 hours ago

Are payments going to be due here or is this just a regression clean-up issue from the original?

**Comment by lakchote** [comment]
> #41561 - deployed to prod 9 hours ago #41660 - deployed to prod 9 hours ago #41664 - deployed to staging 9 hours ago
> 
> Are payments going to be due here or is this just a regression clean-up issue from the original?

These are just follow-up clean ups/regressions fixes. No payments due here, in my opinion.

**Comment by abekkala** [comment]
@lakchote 
I'm assuming Melvin is wrong, and payments are not actually due for anyone?

[comment:](https://github.com/Expensify/App/issues/41560#issuecomment-2102610943)
> These are just follow-up clean ups/regressions fixes. No payments due here, in my opinion.

**Comment by hungvu193** [comment]
Yeah, no payment needed here

> @lakchote I'm assuming Melvin is wrong, and payments are not actually due for anyone?
> 
> [comment:](https://github.com/Expensify/App/issues/41560#issuecomment-2102610943)
> 
> > These are just follow-up clean ups/regressions fixes. No payments due here, in my opinion.

**Comment by lakchote** [comment]
> @lakchote I'm assuming Melvin is wrong, and payments are not actually due for anyone?
> 

Yes, as @hungvu193 just said above, no payment is due here. Thank you!

**Comment by lakchote** [comment]
Closing the issue, no payment due.
