### ISSUE TITLE
[Payment Due 08/23][$250] [Track Tax] Add the ability to configure tax rates on distance rates in NewDot

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41574]
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1713811670223649). 
Figma [here](https://www.figma.com/file/O2SBnfaTdx4OBpFQMf9JIt/Wave-8%3A-Collect-Admins?type=design&node-id=5028-30913&mode=design). 

## Problem 
International customers tracking tax on distance expenses are forced to use OldDot to configure their settings. This leads to them not being suitable to migrate to NewDot. In turn, prevents us from achieving full reunification for all collect workspaces.

## Why is this important? 
We can't migrate these workspaces otherwise. We're already building the ability to see tax rates applied to distance expenses in NewDot, so we need to ensure that's configurable in the workspace settings as well for complete feature parity. 

## Solution

**1. Add a `Track Tax` toggle to the Workspace > Distance rates > Settings page**

![image](https://github.com/Expensify/App/assets/16232057/e4aa4b23-f34e-416b-be1c-7f37177ef332)

- The toggle should be greyed out and locked if the `Taxes` feature isn't enabled. 
- If `Taxes` are enabled the `Track Tax` toggled it's greyed out by default, but can freely be enabled at that point. 
- If an admin disables `Taxes` on the workspace, `Track tax` on `Distance rates` should get disabled as well. 

**2. When the `Track Tax` toggle is enabled, add two push rows for `Tax rate` and `Tax reclaimable on` within the RHP page of each individual distance rate in the `Distance rates` table.**

![image](https://github.com/Expensify/App/assets/16232057/d80fa54f-3af4-4fe2-b1f7-fb9a5013901d)

- The two push rows should be hidden when `Track Tax` is disabled
- When revealed, the values should be blank by default 
- If an admin configures a rate/reclaimable portion, and then disables `Track Tax` or `Taxes` on the workspace, the two rows should be hidden. 
- If an admin configures a rate/reclaimable portion > disables `Track Tax` > re-enables `Track Tax` the rate selection/reclaimable portion values should be remembered when revealed again. (Similar to how we don't blow away your categories or tags lists if you toggle `Categories` / `Tags` off/on).  

**3. The `Tax rate` push row should push to a page that uses the standard SelectList component and contains a list of all the tax rates added to the workspace (this should basically be the same list as seen on an expense).**

![image](https://github.com/Expensify/App/assets/16232057/34c4ccf0-fb40-4b8b-8021-98767b1e5c46)

**4. The `Tax reclaimable on` push row should push to a page that uses the BNP to enter the reclaimable portion** 

![image](https://github.com/Expensify/App/assets/16232057/d5019248-ce24-4878-a4b2-996239187e7f)

- There should be no currency selector on the BNP here though. The currency matches the workspace's reportOutputCurrency. 
- The maximum amount that can be entered is the value of the distance rate. E.g distance rate = £0.30, reclaimable portion maxLimit = £0.30. If an admin enters a value higher than that, we'll show an error message onPress of the `Save` confirmation button:

![image](https://github.com/Expensify/App/assets/16232057/c4d12c71-1ce2-4e1a-b452-4437c3732053)

CC: @Expensify/design 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ad19bb3a1a1f8d8</li>
        <li>Upwork Job ID: 1788904084959670272</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by shawnborton** [comment]
Looks good! Only minor comment - do we want to get rid of these right carets on the table rows? Not sure if that is already being handled or not, but if so, let's update the mocks.

**Comment by shawnborton** [comment]
I assume most people who use this feature know what "Tax reclaimable on" means? I don't quite know what it should mean, but I assume it just means you can claim tax up to a certain amount or something like that? All that's to say is, this one might benefit from some hint/explainer text.

**Comment by dannymcclain** [comment]
>Looks good! Only minor comment - do we want to get rid of these right carets on the table rows? Not sure if that is already being handled or not, but if so, let's update the mocks.

Was just about to say the same thing! I think we're moving towards getting rid of the carets in all of these tables, so we might as well start here. I'm happy to jump in and update the mocks if need be.

**Comment by trjExpensify** [comment]
>Looks good! Only minor comment - do we want to get rid of these right carets on the table rows? Not sure if that is already being handled or not, but if so, let's update the mocks.
>Was just about to say the same thing! I think we're moving towards getting rid of the carets in all of these tables, so we might as well start here. I'm happy to jump in and update the mocks if need be.

Yeah, cool. I don't think we have an issue for that yet. So we should probably spin one up!  

>I assume most people who use this feature know what "Tax reclaimable on" means? I don't quite know what it should mean, but I assume it just means you can claim tax up to a certain amount or something like that? All that's to say is, this one might benefit from some hint/explainer text.

Yeah, they will haha. It's the same label name as OldDot for this feature as well, I kept it consistent. But yeah, this is the portion of the distance rate amount that is eligible to have tax reclaimed on. The TL;DR 

- You pay back an employee a mileage rate set by HMRC which covers both fuel and wear and tear. I.e £0.45 / mile
- As a business, you can only reclaim the VAT on the portion of that rate that covers fuel i.e £0.13 / mile
- The reclaimable portion pertaining to fuel differs based on things like engine size, fuel type, miles travelled per annum and other bollocks set by HMRC and reviewed (I think) quarterly.
- So we can't just apply X% tax rate to the whole mileage expense amount like a "normal" expense and call it a day. We have to let the business enter the amount of the rate that is eligible to reclaim tax on, and then do the calculation based on that.

**Comment by MonilBhavsar** [comment]
Looking into this

**Comment by MonilBhavsar** [comment]
Whoever works on this issue can reuse MoneyRequestAmountForm and TaxPicker components and should be fairly straightforward.

For API's, 
1. For Track Tax toggle we're adding in bullet 1, we'll add an API command - `EnableDistanceRequestTax`. I'll add it, we don't need to HOLD on it

Example `customUnit` param -
```js
{"customUnitName":"Distance","customUnitID":"658abfcfc1c96","attributes":{"unit":"mi","taxEnabled":true}}
```


2. For tax rate and tax reclaimable that we're adding in bullets 3. and 4., we need to call `UPDATE_POLICY_DISTANCE_RATE_VALUE` 

Example `customUnitRate` param - 

```js
{"customUnitRateID":"658abfcfc2519","name":"Default Rate","currency":"USD","enabled":true,"rate":65.1,"attributes":{"taxRateExternalID":"id_TAX_RATE_1","taxClaimablePercentage":0.49155145929339483},"subRates":[]}
```

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Track Tax] Add the ability to configure tax rates on distance rates in NewDot

### What is the root cause of that problem?
This is a new feature

### What changes do you think we should make in order to solve the problem?

We just need to follow the steps listed out in [here](https://github.com/Expensify/App/issues/41574#issue-2277669665) and [here](https://github.com/Expensify/App/issues/41574#issuecomment-2104496814). It's quite straight forward UI changes

### What alternative solutions did you explore? (Optional)
NA

**Comment by MonilBhavsar** [comment]
Okay cool! Let's get started then 👍

**Comment by MonilBhavsar** [comment]
@nkdengineer let us know if you have any questions and when you'll have a draft PR up. I would like to test new API `EnableDistanceRequestTax` against frontend changes before submitting it for review

**Comment by nkdengineer** [comment]
@MonilBhavsar Please let me know: Which field in the policy to know if `Track Tax` is `enable` in bullet 1

**Comment by MonilBhavsar** [comment]
`policy_<>` onxy key and inside it `customUnits` > a unique custom unit ID > `attributes` > `taxEnabled`

**Comment by nkdengineer** [comment]
@MonilBhavsar @trjExpensify 
I have completed the UI part and have some questions as follows:
1. What is params of the `EnableDistanceRequestTax API`?
2. What fields are tax rate vs reclaimable on it, and what `API` will be called when saving those fields?

**Comment by MonilBhavsar** [comment]
Nice, do you have a draft PR?
I think https://github.com/Expensify/App/issues/41574#issuecomment-2104496814 answers both questions! 😄

**Comment by nkdengineer** [comment]
@MonilBhavsar we have a draft PR [here](https://github.com/Expensify/App/pull/42141)

I have a question:

Is the `EnableDistanceRequestTax` api active? I try using params
```
{
     "customUnitName": "Distance",
     "customUnitID": "97E633FEF2869",
     "attributes": {
         "taxEnabled": true,
         "unit": "mi"
     }
}

```
and it is returning `status = 404`, check the following video:

https://github.com/Expensify/App/assets/161821005/7a19d81a-ec91-4937-aeab-b781d5a2f67b

**Comment by MonilBhavsar** [comment]
Thanks for the draft PR!

> Is the EnableDistanceRequestTax api active?

it's not. I'll test it against draft PR and let you know once it is live

**Comment by MonilBhavsar** [comment]
@nkdengineer I'm testing the PR
The API takes customUnit as a param of type `CustomUnit`
You can refer to parameters of API command `setPolicyDistanceRatesUnit`. `EnableDistanceRequestTax` takes same parameters

`Example: {"customUnitName":"Distance","customUnitID":"658abfcfc1c96","attributes":{"unit":"mi","taxEnabled":true}}`

**Comment by nkdengineer** [comment]
@MonilBhavsar Have you finished `EnableDistanceRequestTax` api?

**Comment by MonilBhavsar** [comment]
It's not deployed because of freeze we're having. I'll let you know once it is deployed

**Comment by MonilBhavsar** [comment]
@nkdengineer API is live on staging and we can proceed with PR here

**Comment by nkdengineer** [comment]
I tried to call `EnableDistanceRequestTax ` with params 
```
{
     "customUnitName": "Distance",
     "customUnitID": "97E633FEF2869",
     "attributes": {
         "taxEnabled": true,
         "unit": "mi"
     }
}
```

and i got the error

```
{
  "jsonCode": 0,
  "message": "PolicyAPI::updateCustomUnit(): Argument #3 ($customUnitData) must be of type array, null given, called in /git/releases/expensify.com/3ae6535/api.php on line 2468",
  "requestID": "8883b9164a661108-HKG",
  "onyxData": []
}
```

@MonilBhavsar Was I wrong somewhere? Please check again 🙏

**Comment by nkdengineer** [comment]
@MonilBhavsar oh sorry, I tried again and called the API with refer to parameters of API command setPolicyDistanceRatesUnit 😅

**Comment by MonilBhavsar** [comment]
Yeah, I was about to say parameter of type `CustomUnit` was not passed. You can refer to `setPolicyDistanceRatesUnit` command. Let me know if you need any help

**Comment by nkdengineer** [comment]
@MonilBhavsar Currently, I have completed bullet 1 and bullet 2. However, I encountered issues when integrating APIs in bullet 3 and 4. 
Has  `UPDATE_POLICY_DISTANCE_RATE_VALUE` API been completed and integrated for use in bullet 3 and bullet 4 yet?

Here is my params when i try to call `UPDATE_POLICY_DISTANCE_RATE_VALUE` API

<img width="1057" alt="params" src="https://github.com/Expensify/App/assets/161821005/4f8eb274-be4a-4f67-bca2-bbbe0621fd4e">

And i get error

<img width="1055" alt="response" src="https://github.com/Expensify/App/assets/161821005/a410ad3a-4306-4e6b-9af0-f7dbb3727401">

The API is returning an error due to incorrect custom unit rate ID being passed, but I believe I've passed the correct one.


<img width="622" alt="in application" src="https://github.com/Expensify/App/assets/161821005/d88cd1ec-d1d4-4509-bcd0-4bcec20d9396">

**Comment by MonilBhavsar** [comment]
`customUnitRateArray` was rejected by server because it is not in a way as expected by it. It takes a stringified JSON array. You can refer to API command - `SetPolicyDistanceRatesEnabled`

**Comment by MonilBhavsar** [comment]
@nkdengineer do you think we can get PR ready for review by EOD today?

**Comment by nkdengineer** [comment]
@MonilBhavsar I will try my best to open PR at the EOD today

**Comment by MonilBhavsar** [comment]
Thanks!

**Comment by nkdengineer** [comment]
@MonilBhavsar @trjExpensify  this [PR](https://github.com/Expensify/App/pull/42141) is ready for preview

**Comment by MonilBhavsar** [comment]
@nkdengineer has got a PR up to fix few bugs coming out of it!

**Comment by trjExpensify** [comment]
Checklist time!

**Comment by trjExpensify** [comment]
Still awaiting the checklist.

**Comment by trjExpensify** [comment]
@eVoloshchak can you get to this checklist?

**Comment by eVoloshchak** [comment]
@trjExpensify, apologies for the delay.  This isn't ready for payment yet, there are a couple of regressions, we're tackling the last of them in https://github.com/Expensify/App/pull/43347

**Comment by trjExpensify** [comment]
Oh, I see. I'll take off the payment hold then.

**Comment by trjExpensify** [comment]
Clean-up PR in progress.

**Comment by trjExpensify** [comment]
Same, Melv.

**Comment by trjExpensify** [comment]
Clean-up PR in progress.

**Comment by trjExpensify** [comment]
No change.

**Comment by trjExpensify** [comment]
Bumped in the PR.

**Comment by trjExpensify** [comment]
Same again.

**Comment by trjExpensify** [comment]
Great, let's get it over the line. :)

**Comment by trjExpensify** [comment]
@nkdengineer can you address [the comments](https://github.com/Expensify/App/pull/43347#issuecomment-2249762225), please? Thanks!

**Comment by trjExpensify** [comment]
PR ongoing.

**Comment by trjExpensify** [comment]
PR ongoing!

**Comment by trjExpensify** [comment]
@nkdengineer @MonilBhavsar @eVoloshchak can we get an update please?

**Comment by nkdengineer** [comment]
PR is reviewing and just confirmed the behavior. Will investigate the update tomorrow.

**Comment by trjExpensify** [comment]
Any update?

**Comment by nkdengineer** [comment]
I'm investigating and testing locally before pushing an update. Will give an update in the PR soon.

**Comment by nkdengineer** [comment]
@trjExpensify i updated this [PR](https://github.com/Expensify/App/pull/43347), waiting C+ review

**Comment by trjExpensify** [comment]
Great, let's get it done!

**Comment by trjExpensify** [comment]
All yours for the secondary, @MonilBhavsar!

**Comment by MonilBhavsar** [comment]
PR was merged!

**Comment by MonilBhavsar** [comment]
PR was deployed to production 5 days ago. We can process the payment on payment on Monday once tom is back

**Comment by trjExpensify** [comment]
Confirming payment summary as follows: 

- $250 to @eVoloshchak for the C+ review
- $250 to @nkdengineer for the fix 

@nkdengineer paid, @eVoloshchak go ahead and request!

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
