### ISSUE TITLE
[Awaiting Payment 20th May] [Guided Setup Stage 1] Ask for business name before asking for display name

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41589]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.70-1
**Reproducible in staging?:** Y 
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1714746065450189?thread_ts=1714400621.865599&cid=C036QM0SLJK

## Action Performed:
1. Sign up with a new account
2. Click `Manage my team's Expenses` in the onboarding modal
3. Observe the next question you're asked is for your display name 
5. Enter your display name 
6. Observe the next question you're asked is for your business name

## Expected Result:
When a new user selects the `Manage my team's expenses` onboarding intent:

1. The next question we ask should be for their `Business name` 
2. Upon clicking the confirmation button on the business name page we should trigger the `CreateWorkspace` API command immediately

## Actual Result:
We ask for business name last, so as a result, we trigger the `CreateWorkspace` command at the end of the onboarding flow. 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/8e019b05-7013-45dc-bb49-49e8480ce6cb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @anmurali @francoisl @NikkiWines @mountiny @danielrvidal 

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by trjExpensify** [comment]
Yes, just that option. None of the other options ask for a business name. 👍

**Comment by trjExpensify** [comment]
Yeah, I see the commit to not do that 😅

**Comment by DylanDylann** [comment]
@trjExpensify The PR was deployed to production 2 weeks ago. Could you help to move forward with this issue

**Comment by trjExpensify** [comment]
@ishpaul777, paid!

**Comment by trjExpensify** [comment]
@DylanDylann paid! Closing!
