### ISSUE TITLE
[$250] Distance rates - Distance rate row is disabled after selecting an invalid rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41595]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- The workspace has a distance rate with $0.000 value on Old Dot (impossible to create this on New Dot)
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Distance
3. Enter waypoints
4. Select the workspace from the precondition
5. Select Rate
6. Select "New rate", which is the distance rate with $0.000 on Old Dot

## Expected Result:
App should allow user to reselect another distance rate when the distance rate is invalid

## Actual Result:
The distance rate caret is gone after selecting an invalid rate, which means user cannot reselect another rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ce173f06-937c-4a17-8ee9-6c07f06694b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01602fdea81c088caa</li>
        <li>Upwork Job ID: 1787777798786043904</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance Rate row shows "pending..." after selecting 
### What is the root cause of that problem?
 
we check `!rate` which resolves to true in case the rate is `0`
https://github.com/Expensify/App/blob/895d37e6c51b5ca07873d1ebfc3d7417903ef9ac/src/libs/DistanceRequestUtils.ts#L120-L122
### What changes do you think we should make in order to solve the problem?

instead we should check for if its not null and or undefined (rate !== null && rate !== undefined)

**Comment by dylanexpensify** [comment]
Could repro

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@dylanexpensify I am unable to repro the issue.


https://github.com/Expensify/App/assets/46707890/d00caf03-43aa-4e7d-bec8-7112e11d2d6d
