### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Distance rate can be deleted from 3-dot menu when there is only one rate

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41594]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- There is only one default distance rate in the workspace.

1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces > any workspace.
3. Go to Distance rates.
4. Go offline.
5. Add a distance rate,
6. Delete the default workspace rate (not the newly-added rate).
7. Click on the checkbox of the newly added distance rate.
8. Select Delete option from the dropdown.
9. Note that the distance rate cannot be deleted because there must be at least one distance rate.
10. Click on the distance rate row.
11. Delete it from the three-dot menu.

## Expected Result:
App will show the same pop-up in Step 9 that the distance rate cannot be deleted as there is only one distance rate.

## Actual Result:
Distance rate can be deleted from 3-dot menu when there is only one distance rate.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/97c23378-1afb-4eeb-8441-f0f0a33dbb8a

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144c3fd2f5960b3c2</li>
        <li>Upwork Job ID: 1786441064248098816</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane / @kevinksullivan</details>

**Comment by m-natarajan** [comment]
@slafortune FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by sobitneupane** [comment]
Will review the proposals shortly.

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone. 

All the proposals are almost same. @Krishna2323 Your proposal needs few refinement. Can you please separate all the options as different solutions in your proposal. You can take[ this proposal](https://github.com/Expensify/App/issues/41594#issuecomment-2094095905) as an example. 

Why should we remove pending action `add` as well? Regarding`!rate.enabled`, I believe if the rate is disabled there is already an enabled rate (as there is always at least one enabled rate). So, we can safely remove it.

**Comment by sobitneupane** [comment]
Thanks for the proposal @cretadn22 

Your proposal looks good to be. Instead of `canDisableOrDeleteSelectedRates`, let's name the variable `canDisableorDeleteRate` and I believe simply adding `rate.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE` condition in the following should be enough. 
https://github.com/Expensify/App/blob/387ab0edd9d2c01c2a0be72950490c94b1b7d9d9/src/pages/workspace/distanceRates/PolicyDistanceRateDetailsPage.tsx#L50

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment]
@Krishna2323 I would say your proposal is very unclear. You have added multiple things in a place. Most of which are not required.

**Comment by tgolen** [comment]
I have read through all the proposals today and I agree with @sobitneupane that the proposal from @cretadn22 is preferrable.

**Comment by slafortune** [comment]
Still working on PRs - I will be on vacation until June 4th, so adding another BZ in the meantime

**Comment by slafortune** [comment]
@sobitneupane can you please complete the checklist?

**Comment by tgolen** [comment]
bump @sobitneupane to complete the checklist, please.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

-Precondition: There is only one default distance rate in the workspace.

1. Go to Settings > Workspaces > any workspace.
2. Go to Distance rates.
3. Go offline.
4. Add a distance rate,
5. Delete the default workspace rate (not the newly-added rate).
6. Click on the checkbox of the newly added distance rate.
7. Select Delete option from the dropdown.
8. Verify that the distance rate cannot be deleted because there must be at least one distance rate.
9. Click on the distance rate row.
10. Delete it from the three-dot menu.
11. Verify that the distance rate cannot be deleted because there must be at least one distance rate.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/38237
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/38237#issuecomment-2180236140

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

yes
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

https://github.com/Expensify/App/issues/41594#issuecomment-2180230658

**Comment by slafortune** [comment]
@sobitneupane C+ is due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
