### ISSUE TITLE
Wallet - "Debit card setup not allowed" error appears when adding a card

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:**https://expensify.testrail.io/index.php?/tests/view/4538717&group_by=cases:section_id&group_order=asc&group_id=229064
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with an expensifail account
2. Navigate to Profile - Wallet - Add bank account - Debit card
3. Add "4000056655665556" as the Debit card number and fill the rest with random data
4. Tap on the "Save" button
5. Fill the fields with random data
6. Tap on the "Save & continue" button

## Expected Result:
I should be able to add a card without errors

## Actual Result:
"Debit card setup not allowed" error appears when adding a card. The card is actually added and visible if you navigate back to the Wallet tab

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/63ff7f63-6aac-4273-b4d4-0cebbce61fc2

![Bug6470083_1714743835478!IMG_2049](https://github.com/Expensify/App/assets/78819774/8bccf2a7-fbe3-4331-b7e0-fd259c0e7aa3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@thienlnam  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by francoisl** [comment]
This error is coming from the backend, and the code doesn't seem to have changed in a while. According to the code [here](https://github.com/Expensify/Web-Expensify/blob/bb86d29aea322c40/lib/BankAccountAPI.php#L2565-L2566) we don't support setting up wallets with debit cards on purpose, so it's surprising that this test would have ever passed. It's not even a new test too, it was [added in April 2023](https://github.com/Expensify/Expensify/issues/226985#issuecomment-1502234382)(?)

**Comment by thienlnam** [comment]
Sounds like this isn't a blocker then? We should actually change the error message here though

**Comment by francoisl** [comment]
I'm not sure... Maybe it is?

> Reproducible in production?: Unable to check

Curious why, is this a new flow that was just added on a PR that's on staging now?

**Comment by thienlnam** [comment]
Asked about this here https://expensify.slack.com/archives/C9YU7BX5M/p1714763098629059 

Turns out this was probably happening on prod but wasn't tested there since it would require a real debit card
