### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Workspace - RBR is aligned to top of WS bar

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#41609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-1
**Reproducible in staging?:** y
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition: Sign up new account.

1. Add workspace
2. Go to Workspace > Workflows
3. Enable 'Make or track payments'
4. Add VBA (Regions bank)
5. Go to Workspaces tab

## Expected Result:
RBR is aligned to center of WS bar

## Actual Result:
RBR is aligned to top of WS bar

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6469815_1714726545108!RBR](https://github.com/Expensify/App/assets/43996225/8d6fc9da-21fd-4bf7-bbf2-d47ecbb36f55)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e565fa0b66eb131c</li>
        <li>Upwork Job ID: 1787654855430000640</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by kavimuru** [comment]
@isabelastisser FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Isaac017** [comment]
Here's a proposal for the Expensify project:

Title: Unifying Front-end with React Native Migration

Proposal:

I understand that Expensify is seeking to unify its front-end across platforms using React Native. The GitHub issue outlines the requirements for this migration. My proposal focuses on addressing the key challenges and providing a technical explanation of the changes I will make.

Objectives:

1. Migrate the existing front-end to React Native, ensuring a seamless user experience across platforms.
2. Implement a consistent design language and component library.
3. Ensure compatibility with existing APIs and backend infrastructure.
4. Conduct thorough testing on multiple platforms (iOS, Android, and Web).

Technical Approach:

1. Set up a new React Native project, integrating it with the existing Expensify codebase.
2. Develop a custom component library, utilizing React Native elements and Expensify's design guidelines.
3. Implement platform-specific optimizations for performance and user experience.
4. Utilize React Native's built-in navigation and routing features for a cohesive user flow.
5. Conduct thorough testing, including unit tests, integration tests, and UI tests.

Deliverables:

1. A detailed report outlining the migration process and technical decisions.
2. A fork of the Expensify/App repository with the implemented changes.
3. A pull request for merging the changes into the main codebase.
4. Screenshots and confirmation of successful testing on all platforms.

Timeline:

1. Initial setup and planning: 2 days
2. Component library development: 5 days
3. Platform-specific optimizations: 3 days
4. Testing and debugging: 5 days
5. Documentation and reporting: 2 days

Total estimated time: 17 days

Please review my proposal, and if accepted, I will post it on Upwork and begin working on the project. I will then submit the code for review and merge into the Expensify codebase.

**Comment by Isaac017** [comment]
Contributor details
Your Expensify account email: <isaacochagwu001@gmail.com>
Upwork Profile Link: <Contributor details Your Expensify account email: <https://www.upwork.com/freelancers/~01ecb4ea889e2c3a93>
Here's a proposal for the Expensify project:

Title: Unifying Front-end with React Native Migration

Proposal:

I understand that Expensify is seeking to unify its front-end across platforms using React Native. The GitHub issue outlines the requirements for this migration. My proposal focuses on addressing the key challenges and providing a technical explanation of the changes I will make.

Objectives:

1. Migrate the existing front-end to React Native, ensuring a seamless user experience across platforms.
2. Implement a consistent design language and component library.
3. Ensure compatibility with existing APIs and backend infrastructure.
4. Conduct thorough testing on multiple platforms (iOS, Android, and Web).

Technical Approach:

1. Set up a new React Native project, integrating it with the existing Expensify codebase.
2. Develop a custom component library, utilizing React Native elements and Expensify's design guidelines.
3. Implement platform-specific optimizations for performance and user experience.
4. Utilize React Native's built-in navigation and routing features for a cohesive user flow.
5. Conduct thorough testing, including unit tests, integration tests, and UI tests.

Deliverables:

1. A detailed report outlining the migration process and technical decisions.
2. A fork of the Expensify/App repository with the implemented changes.
3. A pull request for merging the changes into the main codebase.
4. Screenshots and confirmation of successful testing on all platforms.

Timeline:

1. Initial setup and planning: 2 days
2. Component library development: 5 days
3. Platform-specific optimizations: 3 days
4. Testing and debugging: 5 days
5. Documentation and reporting: 2 days

Total estimated time: 17 days

Please review my proposal, and if accepted, I will post it on Upwork and begin working on the project. I will then submit the code for review and merge into the Expensify codebase.

**Comment by Isaac017** [comment]
Contributor  isaacochagwu001@expensify.com

 https://www.upwork.com/freelancers/~01ecb4ea889e2c3a93
Here's a proposal for the Expensify project:

Title: Unifying Front-end with React Native Migration

Proposal:

I understand that Expensify is seeking to unify its front-end across platforms using React Native. The GitHub issue outlines the requirements for this migration. My proposal focuses on addressing the key challenges and providing a technical explanation of the changes I will make.

Objectives:

Migrate the existing front-end to React Native, ensuring a seamless user experience across platforms.

Implement a consistent design language and component library.

Ensure compatibility with existing APIs and backend infrastructure.

Conduct thorough testing on multiple platforms (iOS, Android, and Web).

Technical Approach:

Set up a new React Native project, integrating it with the existing Expensify codebase.

Develop a custom component library, utilizing React Native elements and Expensify's design guidelines.

Implement platform-specific optimizations for performance and user experience.

Utilize React Native's built-in navigation and routing features for a cohesive user flow.

Conduct thorough testing, including unit tests, integration tests, and UI tests.

Deliverables:

A detailed report outlining the migration process and technical decisions.

A fork of the Expensify/App repository with the implemented changes.

A pull request for merging the changes into the main codebase.

Screenshots and confirmation of successful testing on all platforms.

Timeline:

Initial setup and planning: 2 days

Component library development: 5 days

Platform-specific optimizations: 3 days

Testing and debugging: 5 days

Documentation and reporting: 2 days

Total estimated time: 17 days

Please review my proposal, and if accepted, I will post it on Upwork and begin working on the project. I will then submit the code for review and merge into the Expensify codebase.

**Comment by isabelastisser** [comment]
@MonilBhavsar, please review the proposals. Thanks!

**Comment by MonilBhavsar** [comment]
Looks good to me

**Comment by isabelastisser** [comment]
@thesahindia, please complete the checklist before payment is due. Thanks!

**Comment by isabelastisser** [comment]
Payment summary:

@thesahindia requires payment through NewDot Manual Requests - C+ review $250 `PENDING`
@Krishna2323 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/0) (Contributor) $250

**Comment by isabelastisser** [comment]
All set!

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
