### ISSUE TITLE
[HOLD for payment 2024-05-29][Search v1] Implement policy filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#41618]
Implement this section of the design doc - https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=kix.qynv3hskwp7v

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by WojtekBoman** [comment]
Hi! I'll take a look at this one :)

**Comment by luacmartins** [comment]
Gonna work on the backend part of this

**Comment by trjExpensify** [comment]
Looks like this is being worked on, moving out of Hot Picks and into the Summer release.

**Comment by luacmartins** [comment]
PR was deployed to prod [last week](https://github.com/Expensify/App/pull/41769#issuecomment-2125962355). Updating to process payment.

**Comment by luacmartins** [comment]
Hmm actually no C+ was involved in this, so we're good to close.

**Comment by ahmedGaber93** [comment]
@adelekennedy offer accepted. Thanks!

**Comment by adelekennedy** [comment]
done - I think that's everyone who needs payment via Upwork, please reopen if I missed something!
