### ISSUE TITLE
[$250] [HOLD for payment 2024-06-13] [QBO] Prevent the admin from making misconfiguration related to `Locations` and `Vendor Bills` / `Checks`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#41621]
Prevent the admin from making configurations that result in the loss of Location information when expenses are exported to QBO. We will do that in the following two ways:

- When the Location import is enabled, don't display the `Vendor Bill` or `Check` on the list of account type options for both reimbursable and non-reimbursable expense types.

- When the `Vendor Bill` or `Check` is selected as the export option for either or both of the reimbursable and non-reimbursable expense types, lock the switch button for the Locations import configuration.

Refer to the following sections of the QBO design doc:
- [Don't display `Vendor Bill` or `Check` on the Reimbursable or Company Card export configuration pages when Location import is enabled.](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit#bookmark=id.vkrdc5yqhi7)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a7e95204bed8567</li>
        <li>Upwork Job ID: 1801201513249071105</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment]
working on the PR

**Comment by jliexpensify** [comment]
Bump @rojiphil - is a checklist needed?

Payment Summary

- C+: @rojiphil $250

**Comment by rojiphil** [comment]
@jliexpensify As this was an improvement, I think no checklist is required.
Accepted Offer. Thanks.

**Comment by jliexpensify** [comment]
Paid and job closed!
