### ISSUE TITLE
[Search v1] Create Shared canned search

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#41620]
Section from design doc - https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=kix.lhhcxbd5fj0k

**Comment by luacmartins** [comment]
Taking off hold, we'll start implementation shortly.

**Comment by trjExpensify** [comment]
Looks like this is being worked on, moving out of Hot Picks and into the Summer release.

**Comment by luacmartins** [comment]
We don't have someone working on it yet. I'll apply the `hot picks` label again

**Comment by joekaufmanexpensify** [comment]
@luacmartins should I stay assigned here for now/is there anything I can help with for this one? Happy to help find someone, if needed

**Comment by luacmartins** [comment]
Thanks for asking @joekaufmanexpensify! Not yet, this is looking for an internal engineer

**Comment by chiragsalian** [comment]
Discussed with @luacmartins, i'll take over here. I don't see a reason for joe to be assigned here so clearing his assignment to clean up his K2.

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY! LMK if anything comes up that i can help with

**Comment by jnowakow** [comment]
I'm from SoftwareMansion and I'll work on this issue

**Comment by trjExpensify** [comment]
Remove the `Hot pick` from this as @chiragsalian is assigned for the back-end. @jnowakow, to confirm, [this](https://github.com/Expensify/App/issues/41625) is the front-end issue for adding the canned searches right?
