### ISSUE TITLE
[HOLD for payment 2024-06-06] [Search v1] Implement receipt thumbnails

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#41629]
We need to introduce receipt thumbnails in the search page as part of this section of the [design doc](https://docs.google.com/document/d/1u6tBxmoKAEc70jvyZHaKykcfyC5iyEaewfgYXUSSbBc/edit#bookmark=id.4eaepp72f3xr)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b315a218e715b66</li>
        <li>Upwork Job ID: 1788997846845743104</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by luacmartins** [comment]
Holding PR is still in review

**Comment by trjExpensify** [comment]
You going to take this one?

**Comment by luacmartins** [comment]
Yes, I can work on it now that the holding PR is merged.

**Comment by luacmartins** [comment]
@Expensify/design could I get the new ReceiptPlus icon exported from Figma? Just wanna make sure I'm using the correct asset

**Comment by dubielzyk-expensify** [comment]
Here ya go

[receipt-plus.svg.zip](https://github.com/Expensify/App/files/15270180/receipt-plus.svg.zip)

**Comment by dannymcclain** [comment]
@luacmartins the steps are fairly convoluted for such a simple thing. Honestly it will likely be best to just ask a member of the design team to do it. But I will outline them anyways!

- From the [Icons page](https://www.figma.com/file/qQIIaxVUdtggrh8eg8bI5B/Brand-Guidelines-%26-Product-UI?type=design&node-id=4515-13203&mode=design&t=x4l7V0iETTtscHFW-11) in our Brand Guidelines & Product UI file, select the icon component you want to export
- Duplicate it to create an instance of the icon
- Set the fill color to `#000000`
- Export that frame as an SVG
- Open the exported SVG in Adobe Illustrator
- Save As from Illustrator and **replace** the SVG exported from Figma
- In the SVG Options window that opens, make sure that under Advanced Options, the Decimal Places field is set to 3 (it defaults to 1)
- Compress your newly updated SVG file to zip it up, and then it's ready for upload to GH. (This step is optional and really only needed if you're uploading/sending the file somewhere.)

I know this seems pretty wacky for simply exporting a small UI icon, but we've found that Figma's exports aren't always reliable. We've found this process to consistently produce the best results. Design team, feel free to add any of your thoughts too! This is the way I do it though.

**Comment by luacmartins** [comment]
Thanks for listing out the steps. I think I'll keep asking you guys for icons haha

**Comment by puneetlath** [comment]
Will this be handled internally or externally?

**Comment by luacmartins** [comment]
I'm handling it and have PRs in review

**Comment by dubielzyk-expensify** [comment]
Yep. Pretty much exactly what Danny said, but feel free to ping us and we'll whip it up for you @luacmartins

**Comment by puneetlath** [comment]
It looks like maybe @rojiphil needs payment here. Is that right @luacmartins?

**Comment by rojiphil** [comment]
> It looks like maybe @rojiphil needs payment here

Yea. I also think so. Thanks for bringing this up.
Please note the reference to the completed review checklist [here](https://github.com/Expensify/App/pull/41957#issuecomment-2117652398)

**Comment by luacmartins** [comment]
>It looks like maybe @rojiphil needs payment here. Is that right @luacmartins?

Yes, assigned @rojiphil to the issue. Thanks for noticing this!

**Comment by puneetlath** [comment]
@rojiphil offer here: https://www.upwork.com/nx/wm/offer/102642553

Please ping me on this issue when you've accepted

**Comment by puneetlath** [comment]
Great, all paid. Thanks everyone!
