### ISSUE TITLE
[Search v1] Create Finished canned search

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#41624]
Section from design doc - https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=kix.wqeob2z58zqn
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cdb0e0c8bbdb964</li>
        <li>Upwork Job ID: 1790718775554523136</li>
        <li>Last Price Increase: 2024-05-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @chiragsalian</details>

**Comment by sakluger** [comment]
@luacmartins this isn't overdue, right?

Also, I'm guessing I'll mainly be here to pay out the C+ who reviews the PR, right? Let me know if there's anything else I can do to help.

**Comment by luacmartins** [comment]
Not overdue. Correct, we'll just need to pay out C+ once the PR is reviewed.

**Comment by jnowakow** [comment]
I'm from SoftwareMansion and I'll work on this issue.

**Comment by trjExpensify** [comment]
@chiragsalian is taking this on as a follow-up to the Shared filter: https://expensify.slack.com/archives/C036QM0SLJK/p1715802092498399?thread_ts=1715336686.106629&cid=C036QM0SLJK

**Comment by sakluger** [comment]
I'm going OOO through May 31, @CortneyOfstad please watch over this while I'm gone. Thanks!

**Comment by CortneyOfstad** [comment]
Sounds good @sakluger!

**Comment by sakluger** [comment]
Unassigning @CortneyOfstad since I'm back from OOO.

**Comment by sakluger** [comment]
Looks like the latest is that there is a draft PR: https://github.com/Expensify/Auth/pull/11115

**Comment by luacmartins** [comment]
The [original PR](https://github.com/Expensify/Auth/pull/11104) was approved/merged into our merge slush branch. We'll request a merge of the Slush branch once the queries are timed.

**Comment by luacmartins** [comment]
PR deployed to prod. This is done!
