### ISSUE TITLE
Notifications - Notification shows "New Expensify" as sender when sender has no display name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41632]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4532040
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User A has no display name
- User A is on web
- User B is on desktop app
1. Go to staging.new.expensify.com
2. [User B] Background desktop app
3. [User A] On web, send a message to User B
4. [User B] Check the app notification

## Expected Result:
App notification will show User A's email as display name

## Actual Result:
App notification shows only "New Expensify" instead of User A's email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/808e7ec9-6530-4145-8876-e4fd2172df16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105129a47d0b5f423</li>
        <li>Upwork Job ID: 1787504579384856576</li>
        <li>Last Price Increase: 2024-05-06</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by joekaufmanexpensify** [comment]
Going to review this morning

**Comment by joekaufmanexpensify** [comment]
This is reproducible on any platform. We're not showing the primary login in the notification if no display name is set.

**Comment by joekaufmanexpensify** [comment]
@dukenv0307 LMK if you agree that BE fix is needed here?

**Comment by joekaufmanexpensify** [comment]
Interesting. I'll try and reproduce again today

**Comment by joekaufmanexpensify** [comment]
Hmm yeah it's working for me now too. Perhaps it was an issue related to our site instability yesterday. Going to close for now since this seems to be resolved!
