### ISSUE TITLE
Status Bar color not matching the page background

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41648]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714736677676559

## Action Performed:
1. Open app on mweb Safari, Reload the page.
## Expected Result:
Status Bar color matching the page background
## Actual Result:
Status Bar color not matching the page background
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [X] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![IMG_4974](https://github.com/Expensify/App/assets/38435837/8dffc87c-d028-4a2f-9483-5464953ee29f)
![IMG_B207AB1C9DA2-1](https://github.com/Expensify/App/assets/38435837/653ff47f-3e85-4756-b65a-ef2e8200f95e)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
Looks similar to https://github.com/Expensify/App/issues/40683

**Comment by abekkala** [comment]
I agree - the issue already reported 
closing

**Comment by bernhardoj** [comment]
@abekkala hi sorry, https://github.com/Expensify/App/issues/40683 doesn't fully fix the issue here. The status bar color still won't match the SIGN IN page (the 2nd image in the OP).
