### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [DRAFT REVIEW] Set up your wallet

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#41674]
[DRAFT](https://docs.google.com/document/d/1GtffbrSCu4Wfe8SuihmhHjrEVZKBIEMUIoTFDVSdgZ8/edit#heading=h.1dfeb1kwzl6s)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by strepanier03** [comment]
Thanks for the review and updates @ren-jones. I commented on that final piece in the google doc and in Slack. 

Anything more you need from me?

**Comment by strepanier03** [comment]
@ren-jones - Want me to put the PR up for this?

**Comment by strepanier03** [comment]
Ren is paid differently so closing this out.
