### ISSUE TITLE
[$250] Table headers are misaligned when external mouse is connected

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#41693]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Coming from [this comment](https://github.com/Expensify/App/pull/41347#issuecomment-2093643727), table headers are misaligned with the table content when an external mouse is connected:

1. [large screens only] Connect an external mouse to your computer
2. Navigate to the Search page `Profile > Troubleshoot > New search page`
3. Note that the table header and table content are misaligned

<img width="1275" alt="Screenshot 2024-05-06 at 12 25 30 PM" src="https://github.com/Expensify/App/assets/22219519/b1725011-6959-4fef-80ec-3d5b168511be">

Note: this also happens in other views, e.g. Workspace categories, tags, etc

## Expected Result:
Table header should be aligned with content

## Actual Result:
Table header is not aligned with content

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01352e7296a9a4fe1c</li>
        <li>Upwork Job ID: 1787872804772577280</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dragnoir</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The list header is misaligned when a scrollbar is added to the list.

### What is the root cause of that problem?
The header isn't part of the list component, so when the list width is reduced because of the scrollbar, the header becomes misaligned.

### What changes do you think we should make in order to solve the problem?

Wrap the header with a view and set the max width to the list width or 100%.
https://github.com/Expensify/App/blob/84118d84da7415bf1ee71fbfcc304bffb75a5530/src/components/SelectionList/BaseSelectionList.tsx#L570-L597

`<View style={{maxWidth: listWidth || '100%'}}`

We get the listWidth (state) from the section list onLayout.
https://github.com/Expensify/App/blob/84118d84da7415bf1ee71fbfcc304bffb75a5530/src/components/SelectionList/BaseSelectionList.tsx#L385-L387

**Comment by luacmartins** [comment]
@dragnoir your proposal looks good. I actually think we can go with the alternate solution here, since it's simpler.

**Comment by CortneyOfstad** [comment]
@dragnoir I know we're on a merge freeze, but do you have any update on the draft PR? Thanks!

**Comment by CortneyOfstad** [comment]
PR was deployed to staging 8 hours ago 🎉

**Comment by CortneyOfstad** [comment]
We're in a merge freeze until Wednesday so being pushed to production will take some time 👍

**Comment by CortneyOfstad** [comment]
Merge freeze is planned to end today 🤞

**Comment by luacmartins** [comment]
Here's the [latest on the merge freeze](https://expensify.slack.com/archives/C05S5EV2JTX/p1716386374928849?thread_ts=1716385815.212889&cid=C05S5EV2JTX). I don't think it'll end today.

**Comment by ahmedGaber93** [comment]
@CortneyOfstad this issue is ready for payment. It deployed to production 23-5-2024 https://github.com/Expensify/App/pull/41986#issuecomment-2125963188

**Comment by CortneyOfstad** [comment]
Sorry about that @ahmedGaber93! I'm not sure why the `awaiting payment` label was not automatically applied, but getting this sorted now!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@ahmedGaber93 — paid $250 via Upwork
@dragnoir — paid $250 via Upwork
