### ISSUE TITLE
[HOLD for payment 2024-06-05] [Wave Collect] New Resources to Publish: Approve & Pay

### ISSUE THREAD

**Issue by RachCHopkins** [Expensify/App#41703]
## Publish Date May 9 (or prior)

Related External Resource GH: https://github.com/Expensify/Expensify/issues/361145
Draft of HelpSite article: https://docs.google.com/document/d/1OzXcDpaZGsP3o07H_a5HUOuxdBTVp3kQXI4gnKbZwn8/edit?usp=sharing

#### Publish under `Expenses & Payments` category
- [ ] Approve & Pay Expenses

<details><summary>Issue Owner</summary>Current Issue Owner: @ren-jones</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ren-jones</details>

**Comment by ren-jones** [comment]
I'm ready to be assigned!

**Comment by RachCHopkins** [comment]
Still finalising the draft!
