### ISSUE TITLE
Processing deferred updates for push notifications causes an infinite loop

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#41704]
- Coming from https://expensify.slack.com/archives/C0714QF3A1Z/p1715025547496549?thread_ts=1715021761.016969&cid=C0714QF3A1Z

Repro steps:

1. Run iOS/Android
2. Join and mute a room
3. Kill the app
4. Send messages in the room to create missed updates
5. Send a DM to trigger a push notification
6. Open the app
7. Infinite loop of GetMissingOnyxMessages

**Comment by arosiclair** [comment]
Fix is merged here: https://github.com/Expensify/App/pull/41702. Going to CP

**Comment by luacmartins** [comment]
CP done! I think we can check this off.

**Comment by arosiclair** [comment]
Yup [on staging now](https://github.com/Expensify/App/pull/41702#issuecomment-2097055585). Closing this out
