### ISSUE TITLE
[HOLD for payment 2024-07-10] `GitUtils.getValidMergedPRs()` returns false positives when PRs are merged into feature branches

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#41718]
cc @roryabraham coming from https://expensify.slack.com/archives/C07J32337/p1715047410791299

## Problem

When we merged a PR from Rushat it broke the `markPullRequestsAsDeployed()` part of the staging deploy.

The PR in question had some commits that merged in PRs from other contributors into a feature branch e.g. `Merge pull request #12 from software-mansion-labs/travel/terms-and-conditions`.

AFAICT we:

1. Get all the commits then pass them to `getValidMergedPRs()` [here](https://github.com/Expensify/App/blob/2d96b8a36c0facf4bc9fb398030b92cebc5679fb/.github/libs/GitUtils.ts#L99-L100)
2. Parse the PR # out using a regex

However, in the case where this failed the PR doesn't exist... so we hit a 404 in the next step. I think around here:

https://github.com/Expensify/App/blob/2d96b8a36c0facf4bc9fb398030b92cebc5679fb/.github/actions/javascript/markPullRequestsAsDeployed/markPullRequestsAsDeployed.ts#L116-L120

## Solution

- We could just skip any `RequestError` with a 404 status...?
- Or figure out how to filter out the PRs that are not merged by Expensify?

**Comment by roryabraham** [comment]
Thanks for the detailed report. It's been a while since I worked on this code, but I always use TDD in `CIGitLogicTests.sh`

**Comment by roryabraham** [comment]
Probably just ignoring 404s is easier to implement. Seems fine

**Comment by marcaaron** [comment]
>I always use TDD in CIGitLogicTests.sh

Not sure if I followed what you mean there. Gonna raise a PR to catch the `RequestError` and log, but throw other errors.

**Comment by roryabraham** [comment]
I think this is done and no payments are due, closing it out
