### ISSUE TITLE
[HOLD for payment Aug 4] [P2P in E.cash] Add the Balance Badge to the Payments Settings Option

### ISSUE THREAD

**Issue by Jag96** [Expensify/App#4171]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

Upwork link: https://www.upwork.com/jobs/~017a88221b02e85314

## New Feature

[Master Issue](https://github.com/Expensify/Expensify/issues/154278)
[Doc Section](https://docs.google.com/document/d/1AcnLAohHQb2jKhUpt9ZCkIh-w1G_9AHe9aogOf2nSF0/edit?ts=6088ccae#bookmark=id.iqahnb2h7c8l)

![2021-06-04_18-18-39](https://user-images.githubusercontent.com/42391420/120873926-70ce4d00-c561-11eb-902e-a08ce3d7dfa7.png)

###
Solution:
1. Refactor the `<EnvironmentBadge>` component to just be called `Badge`
2. Add a `BadgeText` prop to the `MenuItem` component
3. Add a `Badge` component to `MenuItem` [here](https://github.com/Expensify/Expensify.cash/blob/93cbab222c1efdf10beae857cee540f155cd13fc/src/components/MenuItem.js#L60-L61).
3. If the `BadgeText` prop exists, show the `Badge` component
4. When [rendering the settings page](https://github.com/Expensify/Expensify.cash/blob/25dc6a1e26f1280867f8448fef505cc018087aaa/src/pages/settings/InitialPage.js#L80) add a `badgeText` prop with a value equal to the ONYX.USER_WALLET.balance

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by parasharrajat** [comment]
This is StraightForward.
1. I will update the MenuItem Component to Show an optional `Badge` near the arrow based on the prop `badgeText`.
2. We will get the balance from the `ONYX.USER_WALLET.balance`.
3. In the MenuItem Array we will check if the payments item is rendered show the balance.
https://github.com/Expensify/App/blob/7e395c50834631b9f5e918c168256f27837c24b2/src/pages/settings/InitialPage.js#L177
4. We will show the formatted balance in the component with currency Sign.
`Number(props.userWallet.balance).toFixed(2);`

#Question:
1. Do we need to show only $ or we have to get the user's default currency from somewhere?

**Comment by haseebb** [comment]
- **Yes** Firstly I will create a badge view in Side Menu 
- Then I will check if we have value in “ONYX.USER_WALLET.balance” if yes then show it if not then simply hide the view
 - I will show balance in a formatted way. Like 

function currencyFormat(num) {
   return '$' + num.toFixed(2).replace(/(\d)(?=(\d{3})+(?!\d))/g, '$1,')
}

OutPut will be  = **$2,665.00**

**Comment by Jag96** [comment]
@parasharrajat your proposal looks good, I've invited you to the Upwork job. Going to tag @stitesExpensify to confirm what the currency symbol should be set to here.

**Comment by arpitdeveloper** [comment]
1. I will create a Badge in MenuItem component near by right arrow
2. We will get the user current wallet balance(from CurrentWalletBalance.js)
3. Print the user current wallet balance in created badge with currency and formate

**Comment by stitesExpensify** [comment]
Hmm @kevinksullivan Is the wallet balance always in USD? Or should we localize it?

**Comment by kevinksullivan** [comment]
It should always be in USD, since users without a US bank account/SSN do not qualify for the Wallet. Pulling from the doc, we also limit who sees the badge in the first place:

>All users with a USD personal policy currency will see the badge. Users with a non-USD personal policy currency will not see the balance badge unless they have upgraded to an Active wallet (i.e. international user that also has a SSN, and thus qualifies for an Active wallet)

**Comment by parasharrajat** [comment]
Great @kevinksullivan. that's what I assumed initially. PR is ready for review now.

**Comment by Jag96** [comment]
Paid!
