### ISSUE TITLE
[HOLD for payment 2024-06-11] [Xero] Provide access to Xero related screens only if the integration connected is Xero

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#41726]
**Problem**

Right now, components that use `<SelectionScreen>` do not check if the current integration connected is Xero.

**Solution**

As discussed [here](https://github.com/Expensify/App/pull/41690/files#r1591961328), we'll need to add the corresponding checks and modify `shouldBeBlocked` in the components that use `<SelectionScreen>`, to make sure we can only access the related screens if we have the Xero integration connected.

**Comment by mananjadhav** [comment]
@lakchote I can take this up for development.

**Comment by hungvu193** [comment]
I believe we should also update the logic of `ConnectionLayout` as well not only `SelectionScreen`

**Comment by mananjadhav** [comment]
I'll take care of both in all screens.

**Comment by mananjadhav** [comment]
I raised one of the last PRs on the Xero screen. Once I receive feedback on that I'll start working on this one.

**Comment by mananjadhav** [comment]
Waiting for this large PR to get merged https://github.com/Expensify/App/pull/42043. Will start this tomorrow.

**Comment by lakchote** [comment]
@mananjadhav any update?

**Comment by mananjadhav** [comment]
I priotized other fixes in the last week. I'll raise the PR for this one by tomorrow.

**Comment by mananjadhav** [comment]
@MitchExpensify There won't be any payout for this one. This is handled centrally as a flat fee.

**Comment by mananjadhav** [comment]
We're good to close this one out.
