### ISSUE TITLE
Taxes - Tapping on Save button does not save the tax name when keyboard is up

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41755]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Taxes.
4. Tap Add rate.
5. Tap Name.
6. Enter a name.
7. With keyboard still up, tap Save button.

## Expected Result:
The name is saved.

## Actual Result:
The keyboard is dismissed but app remains on the same page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/c0ca1195-e2d9-4d7e-a904-e9e3b2898927

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by iwiznia** [comment]
It seems like that PR was not implemented right, since it should be saving the data when tapping on the save button, even with the keyboard open, otherwise the PR is kind of useless if you still need to tap twice.

I agree though that this does not need to be a blocker.

**Comment by iwiznia** [comment]
Closing in favor of the OG issue https://github.com/Expensify/App/issues/38497
