### ISSUE TITLE
[HOLD for payment 2024-05-20] Split scan - Split preview does not show individual split amount under "Split amounts" list

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41758]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat.
3. Go to + > Split expense.
4. Go to Scan.
5. Upload a receipt.
6. Split the expense.
7. Click on the split preview.
8. Enter amount.
9. Split the expense.
10. Click on the split preview.

## Expected Result:
The split preview will show individual split amount under "Split amounts" list.

## Actual Result:
The split preview does not show individual split amount under "Split amounts" list.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/dd60e293-f6d8-46b7-b066-dbd4c3b16ea2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019be40158dc575160</li>
        <li>Upwork Job ID: 1787967813100097536</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by m-natarajan** [comment]
@miljakljajic FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-split

**Comment by marcaaron** [comment]
cc @youssef-lr

**Comment by youssef-lr** [comment]
This is fixed.

**Comment by JmillsExpensify** [comment]
Re-opening for payment summary for @allroundexperts

**Comment by miljakljajic** [comment]
@allroundexperts is owed 250 USD for their work on this issue

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
