### ISSUE TITLE
Task – Task details is bold in LHN when reassign task to me

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4541528
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Click on FAB and select Assign task
4. Create a task and assign to another user
5. Open task details and reassign task to me
6. Find task in LHN

## Expected Result:
Task details is not bold in LHN when reassign task to me, as this page is open

## Actual Result:
Task details is bold in LHN when reassign task to me

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3b7d23a5-26a6-4aea-975c-6e799da1cd59

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it'a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by alexpensify** [comment]
I'll test soon.

**Comment by alexpensify** [comment]
I wasn't able to get to this one over the weekend, still on my radar.

**Comment by alexpensify** [comment]
Closing - when I reassign to back to me, then I see bold in LHN. 

![2024-05-14_11-07-03](https://github.com/Expensify/App/assets/8107070/a0631dca-eef0-48f9-9627-cec98c1800c9)
