### ISSUE TITLE
[HOLD for payment 2024-05-20] Split - Split amount does not automatically recalculate afte reselecting split members

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41761]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense.
3. Enter amount > Next.
4. Select a few participants > Next.
5. Click on the back button.
6. Unselect one user.
7. Click Next.

## Expected Result:
The individual split amount will automatically recalculate because user returns to the previous page.

## Actual Result:
The individual split amount does not automatically recalculate.
As a result, error "The sum of splits must equal the total amount." shows up after user unselects one user and returns to confirmation page.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/94d597da-7390-4c3b-aba7-bfa7bfc94c83

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by m-natarajan** [comment]
@greg-schroeder FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by m-natarajan** [comment]
We think this bug might be related to #vip-split

**Comment by marcaaron** [comment]
cc @youssef-lr This one is also pretty annoying if you happen to run into it. Maybe there's an obvious fix.

**Comment by youssef-lr** [comment]
@marcaaron fixed here https://github.com/Expensify/App/pull/41717/commits/5b4415ca90c7fdc973a438ddbe76e1db86d51950

**Comment by kavimuru** [comment]
Issue not reproduced 

https://github.com/Expensify/App/assets/43996225/17703c22-fb85-4be5-ac82-cad3055ee776

**Comment by greg-schroeder** [comment]
I think this is fixed per https://github.com/Expensify/App/issues/41761#issuecomment-2099141286 - closing, but reopen if I'm misunderstanding this.

**Comment by JmillsExpensify** [comment]
Re-opening for payment summary for @allroundexperts

**Comment by greg-schroeder** [comment]
Oh. I think @allroundexperts was the reviewer but this issue has no price. I'm assuming $250 would make sense given the timing here as this was created after changes in April.

So, @allroundexperts can make a manual request for $250 

cc @JmillsExpensify

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
