### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] mweb - Split - Split amount input is partially input and scrollable horizontally

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41766]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** no, new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense.
3. Enter amount > Next.
4. Select a few users > Next.

## Expected Result:
Describe what you think should've happened

## Actual Result:
Split amount input will be displayed properly.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e3d59f32-e009-48b6-af9f-16c26a8c45c4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b38edb075b82c5d5</li>
        <li>Upwork Job ID: 1787915699943428096</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>QichenZhu | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by m-natarajan** [comment]
@amyevans FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by amyevans** [comment]
Reproduced on Android. It's not worth blocking deploy over, so I'll remove the label. @youssef-lr I see you have a follow up PR open for uneven splits (https://github.com/Expensify/App/pull/41717), is this issue something you want to address there? Or do you prefer we make this external?

**Comment by amyevans** [comment]
Going off https://github.com/Expensify/App/issues/41763#issuecomment-2099048264 I'm opening this up for external contributors 😄

**Comment by youssef-lr** [comment]
Something strange must be going on on mWeb Android, I can't reproduce this in iOS

![IMG_6861](https://github.com/Expensify/App/assets/9680864/d3b382fd-863f-48d0-8aba-8aa1850ca356)

**Comment by laurenreidexpensify** [comment]
@hoangzinh fresh one for review ^^

**Comment by laurenreidexpensify** [comment]
@hoangzinh bump for review pls

**Comment by QichenZhu** [comment]
@hoangzinh I suggest adding it to [`App/src/components/TextInput/BaseTextInput/index.tsx`](https://github.com/Expensify/App/blob/f443efa9bf82077deedf88fd0466e896af621d8f/src/components/TextInput/BaseTextInput/index.tsx#L374) like below. Since different box sizing in mobile Chrome is causing the problem, it makes sense to resolve it in the same place. Let me know if you have any better ideas!

```TypeScript
!isMultiline && Browser.isMobileChrome() && {boxSizing: 'content-box', height: undefined, overflow: 'auto'},
```

**Comment by QichenZhu** [comment]
Thanks for the offer. Aiming to submit the PR by Monday.

**Comment by laurenreidexpensify** [comment]
Payment Summary:

C+ $250 - @hoangzinh paid in upwork
Contibutor $250 - @QichenZhu paid in upwork

**Comment by laurenreidexpensify** [comment]
@hoangzinh please complete the checklist so we can close thank you
