### ISSUE TITLE
[HOLD for payment 2024-05-20] [$250] Expense - Console error shows up when opening date editor in transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41760]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Go to transaction thread
5. Click Date

## Expected Result:
No console error will show up

## Actual Result:
Console error shows up when opening date editor in transaction thread.
The same issue also happens when opening date picker in confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/064bb73f-9199-4dff-b2bd-a51d54e7ebb8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01947b8d6b6d6db97d</li>
        <li>Upwork Job ID: 1787870484752039936</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment]
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by hayata-suenaga** [comment]
[The error is thrown in this method from Onyx](https://github.com/Expensify/react-native-onyx/blob/2704488296482930e52941217b21ebb77fd7ee48/lib/OnyxUtils.ts#L788-L804)

**Comment by hayata-suenaga** [comment]
@Krishna2323 I assigned you. please let me know when you open a PR to fix it 🙇

**Comment by Christinadobrzyn** [comment]
Payouts due:

- [X] Contributor: $250 @Krishna2323 (paid in Upwork - https://www.upwork.com/nx/wm/workroom/37198593/overview)
- [X] Contributor+: $250 @fedirjh (paid in Upwork - https://www.upwork.com/nx/wm/workroom/37274679/overview)

Upwork job is [here](https://www.upwork.com/jobs/~01947b8d6b6d6db97d). No regression test so closing this.

**Comment by Christinadobrzyn** [comment]
ah thank you @fedirjh, I wasn't sure about that. Thanks for issuing the refund.
