### ISSUE TITLE
Web - Wrong emoji icons for arrows clockwise & counterclockwise in emoji suggestions list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41782]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+1117ck@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com & log in
2. Navigate to any chat
3. Type " :arr "
4. Scroll down & observe emoji icons for :arrows_clockwise: & :arrows_counterclockwise: in suggestions list
5. Select the :arrows_clockwise: & :arrows_counterclockwise: suggestion

## Expected Result:
Correct emoji icons should be displayed for :arrows_clockwise: & :arrows_counterclockwise: in suggestions list

## Actual Result:
Wrong emoji icons for arrows clockwise & counterclockwise in emoji suggestions list. shown
"Back" & "End" icons are displayed for "arrows clockwise" & "arrows counterclockwise"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6473890_1715096057543!Screenshot__193_](https://github.com/Expensify/App/assets/78819774/531bdcc5-fb14-4851-85ec-30fcfd2b9c2d)

https://github.com/Expensify/App/assets/78819774/1f9d46ad-f4a9-4766-8c28-8f09d6d10c6e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
couldn't repro
