### ISSUE TITLE
[$250] Chat-When there is no conversation, LHN shows report.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41781]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4542417
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- start chat
3. Enter specific number +44 161 353 2462
4. Select the user from suggestions
5. From conversation page navigate to LHN

## Expected Result:
When there is no conversation, LHN must not show the report.

## Actual Result:
When there is no conversation, LHN shows report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/75ff22a9-71d0-4726-b79a-499178d35f32

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0181a28cf5eb02442f</li>
        <li>Upwork Job ID: 1788066785217994752</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by kadiealexander** [comment]
Still open for proposals!

**Comment by kadiealexander** [comment]
Still open for proposals!

**Comment by kadiealexander** [comment]
Adding the weekly retest flag to see if this is still reproducible.

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment]
I was able to reproduce that but I wanted to ask what exactly the expected behaviour here should be. Atm it seems like app was designed to behave this way. Report is opened and corresponding item on the LHN is focused and highlighted. 

<img width="1920" alt="image" src="https://github.com/Expensify/App/assets/23487612/abbc3f87-6d40-4d57-9a03-b30aa5aebb5e">

How exactly should it work in order to be accepted solution for this issue?
1. No item would be focused on LHN? 
2. What should be displayed on top of the screen in the report's title? 
3. Should the message say 'This is the beginning of your chat with **Hidden**'?

**Comment by kadiealexander** [comment]
@MrMuzyk this is mobile-specific behaviour, where when you navigate back to the LHN after opening the chat, the chat shouldn't appear in the LHN.

**Comment by MrMuzyk** [comment]
>@MrMuzyk this is mobile-specific behaviour, where when you navigate back to the LHN after opening the chat, the chat shouldn't appear in the LHN. 

ah, ok I think I got this now 😅 I'm looking into the root cause then

**Comment by MrMuzyk** [comment]
I've tried to reproduce that on latest main on mobile view but I couldn't get the same result on ios/android. It works fine for me 🤔 


https://github.com/Expensify/App/assets/23487612/9f90bcb2-47bd-421e-b517-d6dec3d2647c

**Comment by kadiealexander** [comment]
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1716511889892099).

**Comment by kavimuru** [comment]
Issue is not reproducible. 

https://github.com/Expensify/App/assets/43996225/75a839ca-e35c-4ddf-b34d-211470e0e0c5
