### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Track expense - App returns to confirmation page when tapping back button on category page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41783]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/41465
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Account has no workspace.

1. Launch New Expensify app.
2. Go to FAB > Track expense.
3. Track a manual expense.
4. In self DM, tap Categorize it.
5. Select a category.
6. On confirmation page, tap on the back button.
7. On category list page, tap on the back button again.

## Expected Result:
App will return to self DM.

## Actual Result:
App returns to confirmation page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f686b437-8347-4bce-a700-2be2741f4642

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01824a5f82b4736dcc</li>
        <li>Upwork Job ID: 1792915953607385088</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102600461</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-split.

**Comment by anmurali** [comment]
I can't reproduce this. 

https://github.com/Expensify/App/assets/14225673/f2796596-2f2c-4b51-bc09-b7cac59b95e8

**Comment by anmurali** [comment]
Thank you for the clarification @gijoe0295 - I am able to reproduce it.

**Comment by anmurali** [comment]
Thanks @gijoe0295 -I am able to reproduce it now.

**Comment by sobitneupane** [comment]
Thanks for the proposal @gijoe0295 and @tienifr 

I cannot reproduce the issue mentioned in the OP as well as the issue in `Share it with my accountant`. The only issue I can reproduce is 1. Categorize it > 2. Select workspace> 3. Select a Category > 4. Press on Category in Confirmation Page > Instead of opening a new Category Page, you will be send back to the Category Page from Step 3. I am not sure if it's an issue or intended behavior.

Can any of you reproduce any other issues? If yes, Can you please share reproductions steps and on which platform it can be reproduced?

**Comment by sobitneupane** [comment]
Thank you @gijoe0295 and @tienifr 

I can reproduce the issue now.

> I think you might have missed the pre-condition in the OP.

Yup. I missed the pre-condition.

**Comment by sobitneupane** [comment]
Thanks for your [proposal](https://github.com/Expensify/App/issues/41783#issuecomment-2098932814) @gijoe0295 

> FYI We cannot set the participantsAutoAssigned in getTrackExpenseInformation as https://github.com/Expensify/App/issues/41783#issuecomment-2098932814 because participantsAutoAssigned is a client-side only properly, once the user logged out and logged back in, it will not be available and the issue will happen again.

I agree with @tienifr that 2nd part of your proposal might not work once user  log out and log back in.

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/41783#issuecomment-2122831274) @tienifr

Can you please add more details to the first alternative solution in your proposal.  I want to see how it works.

**Comment by sobitneupane** [comment]
Thanks for the update @tienifr 

Alternative solution 1 from @tienifr's [propsoal](https://github.com/Expensify/App/issues/41783#issuecomment-2122831274) looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by anmurali** [comment]
@srikarparsi - do you agree with https://github.com/Expensify/App/issues/41783#issuecomment-2141466185

**Comment by srikarparsi** [comment]
Sorry for missing this, was OOO last week. @tienifr's alternative looks good to me as well :)

**Comment by srikarparsi** [comment]
@sobitneupane can you complete the [checklist](https://github.com/Expensify/App/issues/41783#issuecomment-2274411256) whenever you have a chance please

**Comment by anmurali** [comment]
@tienifr the offer extended expired. So I resent a new one - https://www.upwork.com/nx/wm/offer/103712326

**Comment by sobitneupane** [comment]
**Regression Test Proposal:**

1. Log in with an account with no workspace
2. Create a track expense
3. Press Categorize it
4. Press Back
5. Verify app dismisses the RHP
6. Press Share it with my accountant
7. Press Back
8. Verify app dismisses the RHP

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

This issue was probably present with the addition of the feature to categorize the tracked expense.

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

https://github.com/Expensify/App/issues/41783#issuecomment-2324103115

**Comment by garrettmknight** [comment]
@anmurali please post a payment summary for @tienifr when you get a chance.

**Comment by anmurali** [comment]
### Payment Summary

- [ ] $250 to @tienifr approved, please request on ND

**Comment by sobitneupane** [comment]
@anmurali I will also require the payment summary to request money in newdot.

**Comment by garrettmknight** [comment]
$250 approved for @tienifr

**Comment by sobitneupane** [comment]
@anmurali Bump for the payment summary.

**Comment by sobitneupane** [comment]
Bump @anmurali

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @sobitneupane $250 via NewDot

Please apply/request!

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
