### ISSUE TITLE
[Search v1] "__fake__" is displayed at From and To fields for split expenses

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41615
## Action Performed:
1. Log in with an expensifail account with at one split expense
2. Navigate to Profile - Troubleshoot - New Search page

## Expected Result:
Fields should be populated with valid data

## Actual Result:
"__fake__" is displayed at From and To fields for split expenses

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6474019_1715104138805!Capture](https://github.com/Expensify/App/assets/78819774/34474b03-a1f7-4b1a-9121-feb34dc4c3dc)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@roryabraham  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by roryabraham** [comment]
not a blocker - hidden feature

**Comment by luacmartins** [comment]
I can take this one @roryabraham, since it's related to Search

**Comment by roryabraham** [comment]
cool

**Comment by luacmartins** [comment]
Still happening in some instances. I have another PR in review to filter report types and I need to work on another issue for tracked expenses too.

**Comment by luacmartins** [comment]
I think this should be solved by https://github.com/Expensify/Auth/pull/10927 too, since the reportID used for these split transactions is [-2](https://github.com/Expensify/Auth/blob/ebec4f739b25fba810b6e06a250f3f0458fa8742/auth/lib/Transaction.h#L50) and we'll filter these out, showing only the 1:1 transactions created from the split.

**Comment by luacmartins** [comment]
Hmm so that PR didn't solve this issue. Gonna work on a separate fix.

**Comment by luacmartins** [comment]
I think we can close this one for now since the PR was merged. Maybe we'll have another edge case of this issue, but we can reopen it then.
