### ISSUE TITLE
Expense - Share code option is missing in expense report and transaction thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Submit expense to user with no unsettled expense.
4. Click on the expense preview.
5. Click on the header in combined report.
6. Note that Share code option is missing.
7. Submit another expense.
8. Click on the header in expense report.
9. Note that Share code option is also missing.

## Expected Result:
Share code option will be present in expense report and transaction thread.

## Actual Result:
Share code option is missing in expense report and transaction thread.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

https://github.com/Expensify/App/assets/38435837/47395fd0-731c-41f3-b99c-cddc3d48579e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@abekkala FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment]
Seems related to https://github.com/Expensify/App/pull/40979 cc @DylanDylann @ZhenjaHorbach

**Comment by marcaaron** [comment]
@zhenjahorbach please comment here so I can assign you

**Comment by marcaaron** [comment]
Ah, sorry we can't really wait I will have to revert the PR.

**Comment by marcaaron** [comment]
This is fixed now. Gonna check it off.
