### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250]  App crashes when adding `/` at the end of URL

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41806]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715030970069889

## Action Performed:
1.sign out if already signed in
2. add a extra `/` in end of url "https://staging.new.expensify.com//"

## Expected Result:
App shouldn't crash
## Actual Result:
App crashes
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/62a2e31c-53e7-4ed3-af0b-c23670ef9807

https://github.com/Expensify/App/assets/38435837/282382af-bfe3-49f4-a71d-84fd199daf55

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6865a1fa1e14235</li>
        <li>Upwork Job ID: 1790449044293632000</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment]
On my testing list, I'll get to it soon.

**Comment by alexpensify** [comment]
I wasn't able to get to this one over the weekend, still on my radar.

**Comment by alexpensify** [comment]
Actually, after testing this again. I see the failure if you input https://staging.new.expensify.com// but it does not fail when you go to new.expensify.com// or https://new.expensify.com//. I'm actually going to close this since users don't access staging, only engineers, contributors, and BugZero team.

**Comment by alexpensify** [comment]
Reopening again since this does appear to be an issue on mobile browsers when trying to access https://new.expensify.com//

**Comment by alexpensify** [comment]
Tomorrow, I'll create a new Upwork job.

**Comment by alexpensify** [comment]
@Santhosh-Sellavel - can you please confirm if this proposal will fix this issue? Thanks!

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment]
@ishpaul777 - I've assigned you here, and please keep us posted on if one of these proposals will fix this issue. Thanks!

**Comment by alexpensify** [comment]
Looking at the PR, @ishpaul777 is offline until tomorrow and will review then.

**Comment by alexpensify** [comment]
Update: It looks like this PR is moving along. We're waiting for the final approval from someone who will be offline until Monday.

**Comment by alexpensify** [comment]
Weekly Update: The PR got the needed review, so we are moving forward.

**Comment by alexpensify** [comment]
Okay, we're all set for the payment date. @dominictb, I've sent a new request in Upwork. Please accept, and I'll complete the payment process. Thanks!

**Comment by alexpensify** [comment]
### Paid via Upwork! 

Payouts due: 2024-06-13

- [x] Contributor: $250 @dominictb 
- [x] Contributor+: $250 @ishpaul777 

Upwork job is [here](https://www.upwork.com/jobs/~01d6865a1fa1e14235).
