### ISSUE TITLE
Feature Request :  option to add `amount` and `merchant` in scan flow

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41808]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem:
No option to enter amount and merchant when adding scan receipt. So people can't edit if the reimbursement amount has to be less than the actual receipt

## Solution:
These would not be required fields but would help in the case when people go over budget and want to set the amount reimbursed to be less than the cost on the actual receipt

## Context/Examples/Screenshots/Notes:
![Snip - (2) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/87789410-fe5b-4cd6-b882-a03ed36902c8)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @srikarparsi 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1714956235660959
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
That makes sense to me, but curious what @srikarparsi thinks too.

**Comment by JmillsExpensify** [comment]
Closing this issue until we're able to align internally that we want this feature.
