### ISSUE TITLE
Sourcemaps do not load on staging or production

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#41815]
Coming from [slack](https://expensify.slack.com/archives/C05LX9D6E07/p1715108553088599?thread_ts=1714768240.955059&cid=C05LX9D6E07):

> When it comes to builds, we'd need to change webpack's mode from production to development for staging to produce un-minified bundles, which enable as to easily explore the stack trace

### Problem

On staging and production, sourcemaps are not loading in the Chrome Dev Console on web. This is a problem because it makes it harder to:

1. Debug code on staging
1. Read stack traces
1. Read performance traces

Because all we have access to is minified bundle code, which is much, much harder to read and analyze.

### Solution

Fix sourcemaps!

**Comment by roryabraham** [comment]
Ok, after some experimentation I've found that the `sourceMappingURL` comment is being correctly added to the minified output files, and both those and the sourcemaps are being uploaded to S3. I was able to see the `sourceMappingURL` in my browser in a direct request to the minified bundle in S3. However, after a few seconds I refreshed the page, and it was gone!

S3 isn't likely to change the files it's serving, so that lead me to Cloudflare as the next likely culprit. Coming from [this issue](https://github.com/getsentry/sentry-javascript/issues/9352):

> The issue was the auto minify feature from CloudFlare that removed those comments

Upon researching Cloudflare's auto-minify, it's actually [deprecated](https://developers.cloudflare.com/speed/optimization/content/auto-minify/).

So I think we should disable it for NewDot (which is already minified anyways).

I tried to do this using the Cloudflare token that's available in 1P, using this CLI command:

```bash
CF_API_KEY="REDACTED" cli4 --verbose --patch value='{"css": "off", "html": "off", "js": "off"}' hosts='["staging.new.expensify.com"]' /zones/:9ee042e6cfc7fd45e74aa7d2f78d617b/settings/minify
```

However, I got a 403 response. I was able to use that same token successfully to purge the cache:

```bash
CF_API_KEY="REDACTED" cli4 --verbose --delete hosts='["staging.new.expensify.com"]' /zones/:9ee042e6cfc7fd45e74aa7d2f78d617b/purge_cache
```

So it seems the token lacks permissions to adjust the autoMinify setting. Pulling in ring0 for helo

**Comment by roryabraham** [comment]
So @fukawi2, the TL;DR here is to please follow the instructions [here](https://developers.cloudflare.com/speed/optimization/content/auto-minify/) to disable auto-minification of NewDot files in Cloudflare.

**Comment by fukawi2** [comment]
I'm obliged to ask.... We're in the middle of a performance nightmare and battle to improve... Is disabling minification really a great action?

I could see doing it on staging, but I'm really not sure about doing it on production being a good idea ™️

**Comment by roryabraham** [comment]
Fair question, but all of our code is already minified by webpack during the local build. Cloudflare's minification is done on top of already-minified code, and as such the only thing it's removing is a single comment at the end of the file that's needed link sourcemaps correctly, and which looks like this:

```
//# sourceMappingURL=script.min.js.map
```

From the [deprecation notice for Cloudflare's AutoMinify feature](https://developers.cloudflare.com/speed/optimization/content/auto-minify/):

> Auto Minify is deprecated and will be removed on 2024-08-05 ... We recommend that you minify at the origin during the build phase. Minification is included in most modern web development frameworks

and that's exactly what we're doing 👍🏼

**Comment by fukawi2** [comment]
Great, thanks for clarifying :)
I'll get it done shortly.

**Comment by fukawi2** [comment]
Bad news for you, it's already off... And has been for 8 years :/

![image](https://github.com/Expensify/App/assets/139959/22ff4dbd-035c-4c4e-b151-934a8cd2527d)

**Comment by fukawi2** [comment]
Ohhh, found this while looking at something totally different....

![image](https://github.com/Expensify/App/assets/139959/b2af7de5-6ef2-44c6-b276-4d9594a7bb1a)

Seems we can specific auto-minify as rules...

**Comment by roryabraham** [comment]
Ah, looking at [the docs](https://developers.cloudflare.com/rules/configuration-rules/settings/#auto-minify) it appears that it would have to be turned off globally in order for it to take effect in a rule. Can we please try to remove `Auto Minify` from the rules for both staging and production?

**Comment by fukawi2** [comment]
Disabled on staging. Doesn't look like there is the same for production though.

**Comment by roryabraham** [comment]
Woohoo, sourcemaps are being correctly loaded on staging for the main bundle 🎉 

<img width="942" alt="image" src="https://github.com/Expensify/App/assets/47436092/c0b85fff-a7cb-49e8-9468-68504a23abcb">

Still not seeing them for the vendor bundle, so I'm going to try investigating that further

**Comment by roryabraham** [comment]
I see all sourcemaps are being correctly loaded in production though:

<img width="636" alt="image" src="https://github.com/Expensify/App/assets/47436092/fdb50a79-719a-47db-9e63-a9ad5c76b05a">

**Comment by roryabraham** [comment]
I bet what's happening is that this is fixed but the vendor bundle hasn't changed, so Cloudflare is caching the auto-minified version of the vendor bundle. We've purged caches since this config change happened though, so that's a bit :suspect:

**Comment by roryabraham** [comment]
purged caches again with the CLI, retesting...

**Comment by roryabraham** [comment]
All sourcemaps are being correctly loaded on staging. Thanks @fukawi2 for the assist 🙇🏼
