### ISSUE TITLE
Two pinned concierge chats with one of those flashing for ever

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715078807193699

## Action Performed:
NOTE : I don't have any clue to reproduce. 
1. Log in to applausetester+mn2704@applause.expensifail.com
2. Observe the LHN
3. Click one of the Concierge chat

## Expected Result:
Step 2 : Only one Concierge chat should be seen
Step 3 : Able to access both the concierge chats
## Actual Result:
Step 2 : There are 2 Concierge chat seen
Step 3 : One of them is not loading and flashing for ever
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8c49881b-4fcc-432f-b12d-627f3c84c519

https://github.com/Expensify/App/assets/38435837/096d98bc-ffb7-4e44-aefb-ebfe5af42a9d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
struggling to reproduce this one: 
![2024-05-09_15-00-31 (1)](https://github.com/Expensify/App/assets/56830058/b4c37aab-c1b9-4bc6-8a78-41c74bf4b3c0)

but will try again and also ask @dylanexpensify about the exact reproduction steps.

**Comment by zanyrenney** [comment]
Open tab for [staging.new.expensify.com](http://staging.new.expensify.com/)
Sign in with expensifail email
Open another incognito tab and head to [staging.new.expensify.com](http://staging.new.expensify.com/)
Sign in with a different expensifail email from step 2
Observe dual conci chats?

More repro steps to keep trying ^ not working for me so far.

**Comment by muttmuure** [comment]
I think that the solution to this will need to be part of this: https://github.com/Expensify/App/issues/41542

We are only passing part of the report object, I imagine the contact details and the "pinned" status

**Comment by zanyrenney** [comment]
Oh thanks @muttmuure 

should I close this one out and link it in that other issue then?

**Comment by zanyrenney** [comment]
bump @muttmuure just checking what you were intending with your comment above and if we should amalgamate thee 2 issues?

**Comment by muttmuure** [comment]
let's close this one in favor of https://github.com/Expensify/App/issues/41542
