### ISSUE TITLE
[$250] Android - Send invoice - In conversation page, transaction preview shown briefly and disappeared

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41839]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap fab --- send invoice
3. Enter an amount and tap next
4. Select a contact
5. Tap send invoice

## Expected Result:
In send invoice conversation page, transaction preview must not be shown briefly and disappeared

## Actual Result:
In send invoice conversation page, transaction preview shown briefly and disappeared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f060fa77-cfb8-4ab6-a9eb-5aa3726a8326

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e2c68306bbf442b</li>
        <li>Upwork Job ID: 1788235320335278080</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by james-tindal** [comment]
### Root cause
In the server's response to SendInvoice, the disappearing ReportAction has an empty message.

### Solution
#### Server
reportAction.message[0].html and reportAction.message[0].text should be non-empty strings.

#### Front-end
This can be worked-around by adding the message to the successData on the front-end.

**Comment by cristipaval** [comment]
We knew about this issue and we're working internally on it

**Comment by lschurr** [comment]
Any update @cristipaval?

**Comment by cristipaval** [comment]
^fix PR up

**Comment by cristipaval** [comment]
The fix PR hit production. No payments due for this issue.
