### ISSUE TITLE
Chat - Mention whisper returns, incorrect mention buttons

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41833]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/41406
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with a nexpensifail user
2. Create a room
3. Write any message
4. Thread the message and write any text
5. Tag a non-existing user in the thread
6. Copy the code from the PR
7. Paste it into Chrome console and replace "id" in the last row with the thread ID from the URL
8. Click on "Yes"

## Expected Result:
The buttons should be "Create it" and "Do nothing".
The whisper message shouldn't return.

## Actual Result:
The whisper buttons turned to "Yes" and "No".
The whisper message returns after 10-80 seconds.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fbfc06e1-0eef-4851-b0ca-a4feb3e0f7cd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/1bdf9a37-f5d5-455d-8398-b580308ed842

**Comment by dylanexpensify** [comment]
@izarutskaya is this only occurring with Expensifail accounts?

**Comment by dylanexpensify** [comment]
Confirmed reproduction, though not sure if this is a deploy blocker if only impacting expensifail accounts. cc @pecanoro

**Comment by pecanoro** [comment]
> Copy the code from the PR

Which PR? Is this coming from QAing something in particular?

**Comment by rlinoz** [comment]
We changed this so the buttons should be Yes and No, but also I think we can mark this PR as NO QA and close this issue, there is still a pending Auth PR https://github.com/Expensify/Auth/pull/10734 to make everything work and the end user won't be able to see the report mention whisper until we merge the Auth PR.
