### ISSUE TITLE
mWeb - send invoice - System message in admin's page displays " Invited xx user to chat report"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab --- send invoice
3. Enter an amount and tap next
4. Select a contact
5. Tap send invoice
6. Navigate back to LHN
7. Tap admin report
8. Note system message for send invoice

## Expected Result:
For send invoice, system message in admin's page must not display " Invited xx user to chat report"

## Actual Result:
For send invoice, system message in admin's page displays " Invited xx user to chat report"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a8bdfda4-9779-4252-a56a-f01a7e82e610

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
@lanitochka17 I can't seem to repro this on web or the webapp - is this an android only issue?

**Comment by lanitochka17** [comment]
@adelekennedy I can repro this one on Web/Chrome too

https://github.com/Expensify/App/assets/78819774/30abc672-f9c0-46a4-9c1b-85d3e5068f35

**Comment by adelekennedy** [comment]
ah - finally I was able to repro on browserstack, but I think in this case we should close and reopen in the future!
