### ISSUE TITLE
[Wave Collect][Xero] Display error messages for Xero Import page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#41843]
**Problem**

We do not display meaningful error messages to the user for the Xero import page.

We only display the RBR indicator.

**Solution**

Display meaningful error messages to the user, just like we did in `XeroExportConfigurationPage`.

Note: you'll need to use the `errorText` property, please see https://github.com/Expensify/App/pull/41670/files#diff-e66a522b9cabb71f5418bb119bae86d49f12cc8f7da039acc4ff3c42991cd25fR29

**Comment by lakchote** [comment]
cc @SzymczakJ

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by lakchote** [comment]
Not overdue, progress is still happening. Draft PR to display error messages related to it is [here](https://github.com/Expensify/App/pull/41917).

**Comment by trjExpensify** [comment]
PR hit staging 3 days ago.

**Comment by lakchote** [comment]
Assigning @fedirjh as he'll need to be paid for the C+ review of the linked PR once this hits production and the 7 day regression period passes.

**Comment by bfitzexpensify** [comment]
Invited you to an Upwork job @fedirjh
