### ISSUE TITLE
[PAYMENT REQUESTED] [$250] Critical: Duplicated invite messages for newly created invoice room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rezkiy37 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715183447375399

## Action Performed:
1.  Go to app
2. Send Invoice to User B
3. Open a newly created invoice room.
4. Scroll up.

## Expected Result:
There is not the skeleton view and the duplicated invite message at the very top.
## Actual Result:
There is one more invited message and the skeleton view presents at the very top.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/b368bb4d-6e1f-44c5-a85f-889ab6874e30

https://github.com/Expensify/App/assets/38435837/0bfec95e-34c9-4b94-86b1-2ab623004902

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01082bb3930cb21660</li>
        <li>Upwork Job ID: 1788527406887723008</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by cristipaval** [comment]
@rezkiy37, I'm assigning you to this one

**Comment by strepanier03** [comment]
@cristipaval - I don't think your assignment for @rezkiy37 took, I'll try again now.

**Comment by strepanier03** [comment]
Actually I think it's that weird thing where @rezkiy37 needs to comment on this GH before we can assign them because I can't do it either.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by cristipaval** [comment]
^Auth PR up

**Comment by strepanier03** [comment]
Retesting.

**Comment by cristipaval** [comment]
@strepanier03, @thesahindia is the only one who needs to be paid, for the C+ review.

**Comment by cristipaval** [comment]
I just pinged @strepanier03 internally about this one.

**Comment by strepanier03** [comment]
Ughh, dang automation. Taking care of this now.

**Comment by strepanier03** [comment]
@thesahindia - When automation is failing on a payment GH, please don't hesitate to ping me in Slack 🙌. Payment summary incoming.

**Comment by strepanier03** [comment]
### Payment Summary

- $250 for @thesahindia via Manual Requests in New Expensify

@JmillsExpensify - Payment request incoming.

**Comment by cristipaval** [comment]
Not overdue, Melvin

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
