### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Connect Bank account - Background is slightly touching "Numbers" in Onfido Flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41851]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41234
## Action Performed:
1. Open the New Expensify app or go to staging.new.expensify.com
2. Sign into a valid account
3. Go to Workspace > Enable Workflow > Connect Bank account
4. Select "Connect manually" and use the testing routing number and account number
5. On Personal info page, enter "First" and "Last" for first name and last name
6. Enter any other information on the rest of the Personal info pages and confirm
7. Observe the page when the user is redirected to the "Terms" page

## Expected Result:
User expects correct distancing in between elements

## Actual Result:
The Terms "Frame" is slightly touching with the "numbers" in the header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dd354c4a-6ce8-443f-9602-38c2a5dc5503

![Bug6474960_1715182296601!Loading_Terms_is_touching_the_numbers](https://github.com/Expensify/App/assets/78819774/1b352b4a-87d7-423f-bed8-3e33622e80d8)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc1107f6a76f2e7b</li>
        <li>Upwork Job ID: 1788283293391118336</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by lanitochka17** [comment]
@carlosmiceli  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by carlosmiceli** [comment]
Looking at it @lanitochka17, will let you know asap!

**Comment by shawnborton** [comment]
Can we confirm how much bottom margin the other views have? Ideally they should all be consistent. I see these for example:
![CleanShot 2024-05-10 at 09 20 03@2x](https://github.com/Expensify/App/assets/2319350/9a0ea85b-a266-45fd-9384-c8132d4bbbc4)

![CleanShot 2024-05-10 at 09 20 33@2x](https://github.com/Expensify/App/assets/2319350/ebe1e9f3-dc98-48f8-8ef2-05f5e7c11b8f)

![CleanShot 2024-05-10 at 09 20 58@2x](https://github.com/Expensify/App/assets/2319350/a9659622-78bc-4d6a-8923-f5339838684a)

So I would expect to just reuse that for all pages?

**Comment by shawnborton** [comment]
> So, on the consent page, you'll see extra spacing on the top. The spacing is present now as well, but it will increase when we change the bottom margin to 20. I think that should be fine because it will help us gain consistency on other pages at least.

Is it just the consent page that will be negatively affected by this? Can you share a few screenshots? But in general my thinking is yes, that's probably fine so that we gain the consistency with other pages.

**Comment by shawnborton** [comment]
Got it, I think the padding there is okay.

**Comment by carlosmiceli** [comment]
Commenting to remove overdue label, waiting for confirmation to proceed :)

**Comment by carlosmiceli** [comment]
@thesahindia To confirm, are we waiting for an updated proposal from @ShridharGoel?

**Comment by carlosmiceli** [comment]
@ShridharGoel @thesahindia What's the status of this?

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
