### ISSUE TITLE
[HOLD for payment 2024-05-29][$250] [VIP] Send an invoice from an invoice room

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#41878]
# Part of the <Project Name> project
Main issue: https://github.com/Expensify/Expensify/issues/341717
Doc section: [Here](https://docs.google.com/document/d/1HhnjCVUVN8gw3vfxRA4jCXXQvuIfm1puMhzHoOKe5jY)
Project: [#vip-billpay](https://github.com/orgs/Expensify/projects/114)

# Feature Description
### Problem:
In NewDot, users are limited to sending invoices from Global Create.  Without the ability to create and send invoices from within these dedicated rooms, the process can become disjointed. This setup forces users to navigate away from the conversation context to send invoices, disrupting workflow continuity.

### Solution
Implement Send invoice from the invoice room in NewDot allowing users to send invoices directly from a pre-existing invoices room. 

# Manual Test Steps

# Automated Tests

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c3a6ec6a19ed908</li>
        <li>Upwork Job ID: 1788475765271580672</li>
        <li>Last Price Increase: 2024-05-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by devhardikbeladiya** [comment]
Hello,

I would like to work on this issue.

**Comment by devhardikbeladiya** [comment]
I would like to work on this issue.

Your Expensify account email: devhardikbeladiya@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015078816783129fe4

**Comment by dannymcclain** [comment]
Just so I'm super clear on this: the `Send invoice` option only shows up in Global create and already-created invoice rooms (that would've been created from the global create option), is that correct? That's what I'm gathering from the doc, I just want to fully make sure I understand the expected behavior/implementation.

**Comment by VickyStash** [comment]
@dannymcclain This issue is more about creating an invoice from the existing invoice room. So you have already send one invoice to the receiver, and you want to send another one. Doing it from Global create adds extra step of selecting receiver. By doing it right from the room this step can be skipped. What do you think?
![image](https://github.com/Expensify/App/assets/23176449/16e57091-7bbd-43b7-ab10-a15df75362f1)

**Comment by dannymcclain** [comment]
@VickyStash ok that's what I thought this issue was for, just wanted to make sure! Thanks.

**Comment by VickyStash** [comment]
@shawnborton Which way the receiver should look if the user sends an invoice from the existing invoice room. I have two options:
1) 
![image](https://github.com/Expensify/App/assets/23176449/5d3b7ca0-72f0-498a-8c34-7775785f09a0)
2)
![image](https://github.com/Expensify/App/assets/23176449/701b06bc-29d3-4c41-b8f5-da23ee9b0d63)

**Comment by shawnborton** [comment]
Hmm I think it makes sense to reuse the same room avatar, so your first option. Curious what @davidcardoza and @puneetlath think though!

**Comment by VickyStash** [comment]
_Updates:_ I've enabled send invoice functionality from the invoice room, just need to do some UI fixes. I think I'll open the PR for review tomorrow.

**Comment by puneetlath** [comment]
I like using the room avatar here as well.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/41902) is opened for the review

**Comment by davidcardoza** [comment]
+1 to room avatar.

**Comment by davidcardoza** [comment]
Following through this slack conversation - https://expensify.slack.com/archives/CSL3XBCCR/p1715782572275539

Disabling invoicing at the workspace level will not affect existing invoices and invoice rooms; they will still be accessible. Although this wasn't explicitly stated in the workspace settings section of the payments design docu, I've added a bullet point to the HL overview of the document to clarify this. It's important to note that the invoice rooms will be impacted in that the "Send Invoice" option will no longer appear in the invoice room create button when invoicing is disabled in workspace settings of the invoice sender workspace.

**Comment by davidcardoza** [comment]
^ @cristipaval Let me know if you think that should be it's own GH.

**Comment by cristipaval** [comment]
> ^ @cristipaval Let me know if you think that should be it's own GH.

I think we're good with [this issue](https://github.com/Expensify/Expensify/issues/394553)

**Comment by garrettmknight** [comment]
Note that this has gone to staging. When it deploys I'll test and update the payment if necessary.

**Comment by garrettmknight** [comment]
On prod, updating to awaiting payment.

**Comment by akinwale** [comment]
@garrettmknight bump for payment. Thanks.

**Comment by garrettmknight** [comment]
Sorry @akinwale - offer is out to you in Upwork.

**Comment by garrettmknight** [comment]
All paid out - can you complete the checklist?
