### ISSUE TITLE
[HOLD #38702] Update avatars depending on the number of requestors on the report  

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/App#41873]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:* v1.4.70-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @shawnborton 
**Slack conversation:** N/A discussion [here](https://github.com/Expensify/App/issues/38702#issuecomment-2092863036)

Coming from [this issue](https://github.com/Expensify/App/issues/38702). Align our icon usage (and ensure that the icon and personal details are loading correctly) for the report preview, report, and transaction thread. 

## Action Performed:
**1:1 IOU with requests from a single user**

1. Create a chat with another user
2. Make one (or multiple) money requests to the user from your current account 

**1:1 IOU with requests from both users**

1. Create a chat with another user
2. Request money from them 
3. Have them request money from you 

**Workspace chat**
1. Log into an Expensify account 
2. Create a new workspace
3. Navigate to the workspace chat and make one (or multiple) money request 

## Expected Result:

**1:1 IOU with requests from a single user**
1. We use a single-user avatar for the report preview on the chat, the report header, and the transaction thread header 
![CleanShot 2024-05-03 at 07 57 21@2x](https://github.com/Expensify/App/assets/2319350/d7ba70ca-80a5-492f-a9f6-4893478c9e85)

**1:1 IOU with requests from multiple user**
1. We use a dual-diagonal-user avatar for the report preview on the chat, the report header, and the transaction thread header 
![CleanShot 2024-05-03 at 07 58 12@2x](https://github.com/Expensify/App/assets/2319350/3e0bab71-b05e-4445-a294-34f7599f0503)

**Workspace Chat**
1. We use a large-user-small-workspace avatar for the report preview on the chat, the report header, and the transaction thread header 
![CleanShot 2024-05-03 at 08 05 28@2x](https://github.com/Expensify/App/assets/2319350/4d6bb35a-bf73-4b11-90ff-395a79815f67)

## Actual Result:
**1:1 IOU with requests from a single user** and **1:1 IOU with requests from multiple user**
1. We occasionally show default avatars without personal details for the report preview. When personal details do load, we display the diagonal-dual-user avatar.
<img width="422" alt="image" src="https://github.com/Expensify/App/assets/16747822/74dc3d2c-ed34-4955-af1c-1ad26694e4d8">
<img width="419" alt="image" src="https://github.com/Expensify/App/assets/16747822/317f4c96-5687-4a6a-8b61-b45497795acd">

For the report itself, we display either the diagonal-dual-user or single-user avatar on the report level depending on whether or not the expense has multiple expenses or only one expense. 
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/16747822/a05332e6-5dda-42b7-b73c-c521bb4a8fe6">
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/16747822/35d123b8-4f37-4358-95db-b13739f9997c">

**Workspace Chat**
1. We occasionally show default avatars without personal details for the report preview. When personal details do load, we display the diagonal-dual-user avatar.
<img width="465" alt="image" src="https://github.com/Expensify/App/assets/16747822/74ba9759-f89f-4a6f-bd20-9b8fd2dc5609">
<img width="419" alt="image" src="https://github.com/Expensify/App/assets/16747822/95a1829b-5d38-4f6f-b60a-3aaad523d7c6">

For the report itself, we correctly display the large-user-small-workspace avatar
<img width="769" alt="image" src="https://github.com/Expensify/App/assets/16747822/e8612deb-c550-4235-aa52-ddb0f8b2daf7">

## Workaround:
N/A this doesn't impact the ability to use the app

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Still holding

**Comment by garrettmknight** [comment]
And vip-split is paused so I'm gonna close this until we refocus on it.
