### ISSUE TITLE
Add focus-trap-react library

### ISSUE THREAD

**Issue by jnowakow** [Expensify/App#41877]
# Name of library: focus-trap-react

## Details
- Link to package: https://github.com/focus-trap/focus-trap-react
- Problem solved by using this package: It helps correctly handle focus & tab navigation in modals, RHP and LHP.
- Number of stars in GH: 697
- Number of monthly downloads:  about 2 milion
- Number of releases in the last year: 7
- Level of activity in the repo: low, library is simple and only maintain
- Alternatives: none
- Are security concerns brought up and addressed in the library's repo?
No security concerns
- How many dependencies does this lib use that will be brought into our code? 
2
- What will the effect be on the bundle size of our code? 
91.8kb

[Link to PR adding the library](https://github.com/Expensify/App/pull/39520)

**Comment by mountiny** [comment]
@jnowakow There seems to be only one person maintaining this and the library seems to be one file. Is there a specific reason to use this library instead of just creating our own lib function that could do the same given its not that complex code?

**Comment by jnowakow** [comment]
For me the reason is that it's ready to use and doesn't introduce any security concerns. It's also tested as it's quite popular. So, I don't see a point in rewriting it as it would require us to spend time on the rewrite. We can make a mistake when rewriting. And then we need to maintain the lib. In summary I don't see reason why we would need to copy it instead of using ready package

**Comment by mountiny** [comment]
@jnowakow I believe we are good to go here with the PR, we got couple 👍 and no 👎 from deployers

**Comment by mountiny** [comment]
@jnowakow this is ready to move ahead
