### ISSUE TITLE
Split expense - Merchant field is shown as required while making split expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41886]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on announce room
3. Tap plus icon --- split expense
4. Enter an amount and tap next

## Expected Result:
Merchant field must not be shown as required while making split expense in announce room

## Actual Result:
Merchant field is shown as required while making split expense in announce room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8c616228-2770-41de-b2ae-05ad632c54e6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-split.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/9d9e8803-3a47-4ca6-8934-004cfaa8027f

**Comment by techievivek** [comment]
It seems that the merchant field is only mandatory in workspace chats. For non-workspace chats, it's only required when we explicitly scan a receipt and the scan is successful. However, for manual requests in non-workspace chats, it doesn't appear to be mandatory. I'll wait for confirmation from @JmillsExpensify. In any case, this issue doesn't seem to be a blocker, so I'll remove the label. Once Jason confirms, we can look into it further.

**Comment by youssef-lr** [comment]
This is fixed in this PR https://github.com/Expensify/App/pull/41945

**Comment by youssef-lr** [comment]
This is fixed.
