### ISSUE TITLE
[Wave Collect] [Xero] Fix the Organization name placements

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#41897]
**Problem 1**: The Xero organization name is missing from the page header of `Advanced`. 

![image](https://github.com/Expensify/App/assets/21549771/666f525d-640e-4d31-af99-e2b23c412c36)

Take a look at Import by comparison:

![image](https://github.com/Expensify/App/assets/21549771/bb1b1491-f853-4303-8bd4-4b05d7805ee3)

**Problem 2**: With the NetSuite connection design, we’re adding the organization to each of the next sub-pages. Example from NetSuite below:
![image](https://github.com/Expensify/App/assets/21549771/6d4fde80-27d5-45fa-9782-8459b5eebef4)

Context link: https://expensify.slack.com/archives/C036QM0SLJK/p1715159992727079?thread_ts=1713799302.291019&cid=C036QM0SLJK

**Comment by mananjadhav** [comment]
I can help with the review once this is ready.

**Comment by trjExpensify** [comment]
PR hit staging yesterday.

**Comment by lakchote** [comment]
Assigning @mananjadhav as he'll need to be paid for the C+ review of the linked PR once this hits production and the 7 day regression period passes.

**Comment by rushatgabhane** [comment]
no separate pay required. payment will be handled centrally

**Comment by jliexpensify** [comment]
Does anyone need a payment summary specifically written for this GH? @rushatgabhane @mananjadhav

**Comment by trjExpensify** [comment]
Nope, it just needs to sit out the regression period and then we can close it.

**Comment by mananjadhav** [comment]
@jliexpensify This one is good to close now.
