### ISSUE TITLE
[$250] [HOLD for payment 2024-05-22] Category - Unable to select disabled category with keyboard

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense with category to the workspace chat.
3. Disable the category used in Step 2 in workspace settings
4. Return to transaction thread.
5. Click Category.
6. Navigate through the list with keyboard arrow.

## Expected Result:
User should be able to select the disabled category with keyboard since the disabled category is still interactable with cursor.

## Actual Result:
User is unable to select the disabled category with keyboard when the disabled category is still interactable with cursor.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ad19875a-d01b-439f-b88d-396b75303713

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f6e63bca303a149</li>
        <li>Upwork Job ID: 1793342428448505856</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by izarutskaya** [comment]
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by mallenexpensify** [comment]
Interesting, it's possible that an Upwork job can't be created if the `Awaiting Payment` label is added (or... there was just a glitch earlier with creating a job and it then it worked a few mins later. 

@Krishna2323 @alitoshmatov , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~015f6e63bca303a149

**Comment by mallenexpensify** [comment]
ah... thanks @Krishna2323 (I got a ping payment was due and wanted to be usre I wasn't late, should have read/reviewed the details). Closing then
