### ISSUE TITLE
Android - App jumps when changing language on the login page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#41899]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.72-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app
2. Open login screen
3. Scroll to the bottom
4. Change language several times

## Expected Result:
App doesn't jump when changing language on the login page

## Actual Result:
App jumps when changing language on the login page

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2cc5c4e7-84cb-4df7-bf26-15c6ccd48539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@joekaufmanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by joekaufmanexpensify** [comment]
I don't think adjusting this behavior should be a priority. In an ideal world, the app would not move when this happens, but this has no customer impact. I also expect few customers ever adjust the language from this page. Closing for now.
