### ISSUE TITLE
[HOLD for payment 2024-05-22] New Expensify is using too much memory

### ISSUE THREAD

**Issue by danieldoglas** [Expensify/App#41903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

While executing new Expensify on Web and desktop, the application was using up to 6gb in memory. We need to fix that

## Action Performed:
Just use the app normally 

## Expected Result:
Use normal amount of memory - something like slack uses.

## Actual Result:
Using too much memory

## Workaround:
N/A

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/5818999/fda1a73d-e7dd-4c04-8708-96521813e888)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hurali97** [comment]
@danieldoglas Please assign this to me 👋

**Comment by danieldoglas** [comment]
This was deployed to staging, it's looking much better now. 
![image](https://github.com/Expensify/App/assets/5818999/427b95c2-9ee1-4b9d-a81e-bfaef57950ef)

**Comment by adelekennedy** [comment]
@DylanDylann sent you a manual offer!

**Comment by DylanDylann** [comment]
@adelekennedy I accepted. Thanks
