### ISSUE TITLE
Chat - "hidden" user that is already a member of the group chat can be invited again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41907]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4548098&group_by=cases:section_id&group_id=296760&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with an expensifail account
2. Create a group chat with a few members
3. Invite a unique Gmail account (without the + alias) that you had to contact before
4. Invite the same email again

## Expected Result:
"is already a member of" message should appear on the Invite members page

## Actual Result:
A "hidden" user that is already a member of the group chat can be invited again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/56a18db7-a3da-476e-8e22-758b1bc5130f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment]
Great! Thanks for calling that out! In that case, I think we're ok to close this.
