### ISSUE TITLE
[HOLD for payment 2024-05-20] CRITICAL: SequentialQueue not getting cleared causing the app to get stuck

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#41918]
### Problem

The sequentialQueue seems to get stuck with the write requests which do not get cleared up from the queue. As a result, new requests are not executed which leads to App which is silent, new messages are not processed and opening a report does not actually call the OpenRepor as the request is only added to the queue

```
"[info] [SequentialQueue] 'OpenReport' command queued. Queue length is 10 - \"\""
```

### Solution

This seems like recent problem, we have not noticed this last week but this week multiple people got stuck with this issue.

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by mananjadhav** [comment]
I didn’t work on this PR.

**Comment by mountiny** [comment]
I think we can close it now, its been discussed in Slack what PR this bug stemmed from so I think we dont have to fill the checklist anymore
