### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] mWeb -Room - Inconsistency while pasting highlighted mention in room and expense description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4548719)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1.Go to https://staging.new.expensify.com/
2. Tap FAB > Start a Chat > create a new room
3. Copy the following text in chat
 
@applausetester++0411km
@[jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
(notice: first mention selected from list, second mention is highlighted)

4. Tap header
5. Paste text in room description
6. Note second mention is not highlighted

7. Navigate to LHN
8. Tap fab -- track expense
9. Enter amount and tap next
10. Paste the same above text in track expense description
11. Note now second mention is highlighted and displayed

## Expected Result:
There should not be inconsistency while pasting highlighted mention in room and expense description

## Actual Result:
Inconsistency while pasting highlighted mention in room and expense description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/019b0b29-175f-4a31-bcb2-8f1a1fc95d48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4a08b3d6f351b65</li>
        <li>Upwork Job ID: 1790309855227322368</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight / @Christinadobrzyn</details>

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Christinadobrzyn** [comment]
I don't think this is a bug, 

From what I can test, the only time the 
`@jaihanumanblog@gmail.com` isn't highlighted is after it's copied and pasted but before it's 'saved' in the room/expense/description. Once saved it turns into a mention and is highlighted. 

@bernhardoj let me know if you feel otherwise but I'm going to close this as an edge case, small incident.

**Comment by bernhardoj** [comment]
> From what I can test, the only time the
@jaihanumanblog@gmail.com isn't highlighted is after it's copied and pasted but before it's 'saved' in the room/expense/description. Once saved it turns into a mention and is highlighted.

@Christinadobrzyn That's true. To simplify it, the room description page currently doesn't enable the live markdown preview, while the expense/task description enables it. So, if we want to enable the live markdown preview for room description too, then we can reopen this.

Btw, there is a previous discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1711641837108169) to enable the live markdown preview on some inputs, but looks like the room description page is missing from the list.

**Comment by bernhardoj** [comment]
@Christinadobrzyn bump

**Comment by Christinadobrzyn** [comment]
Ah sorry @bernhardoj this GH was closed so I didn't see this. Ah yes, we should work on this based on this convo - https://expensify.slack.com/archives/C01GTK53T8Q/p1711641837108169

**Comment by Christinadobrzyn** [comment]
I assume this can be external?

**Comment by Christinadobrzyn** [comment]
Hi @shubham1206agra can you check out these proposals when you have a moment?

**Comment by bernhardoj** [comment]
I think we are handling the short mention live markdown preview [here](https://github.com/Expensify/App/issues/38025).

**Comment by francoisl** [comment]
Ok yeah, considering that @tienifr already put some time into this, splitting the bounty and using @bernhardoj's proposal sounds good to me.

**Comment by francoisl** [comment]
(Co-assigning @bernhardoj for the payment later.)

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/42361

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/42361

**Comment by Christinadobrzyn** [comment]
[PR](https://github.com/Expensify/App/pull/42361) - is in staging. 

Just a heads up - I'm going to be ooo until June 24th so going to assign a teammate to watch this while I'm away

**Comment by Christinadobrzyn** [comment]
@garrettmknight this might need to be paid before I'm back - can you watch it while I'm away? TY!

**Comment by garrettmknight** [comment]
@bernhardoj @tienifr updated offers sent to you to split the bounty.

**Comment by bernhardoj** [comment]
Accepted

**Comment by garrettmknight** [comment]
All paid out - @shubham1206agra can you complete the checklist when you get a chance?

**Comment by Christinadobrzyn** [comment]
@shubham1206agra can you check again? I think I just paid you through Upwork. @bernhardoj and @tienifr did you receive payment?

**Comment by bernhardoj** [comment]
@Christinadobrzyn yes, I get the payment

**Comment by Christinadobrzyn** [comment]
okay I think this can be closed - payment summary here - https://github.com/Expensify/App/issues/41919#issuecomment-2166044223
