### ISSUE TITLE
2FA–Unable to press “Got it” button with Enter key on “Disable two-factor authentication” RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** [ponikarchuks+49524@gmail.com](mailto:ponikarchuks+49524@gmail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as a user with 2FA
3. Click on Account settings/Security/ Two-factor authentication
4. Click on Disable Two-factor authentication
5. Verify that “Disable two-factor authentication” RHP opens with “Got it” button
6. Press Enter key on the keyboard

## Expected Result:
Nothing happened

## Actual Result:
Unable to press “Got it” button with Enter key on “Disable two-factor authentication” RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/608392a8-25ef-4397-a4ae-39c7498e61d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to press “Got it” button with Enter key on “Disable two-factor authentication” RHP

### What is the root cause of that problem?
We are missing the `pressOnEnter` prop in the Button Component in DisabledStep.tsx

### What changes do you think we should make in order to solve the problem?
We will pass pressOnEnter to the Got It Button

**Comment by garrettmknight** [comment]
This seems like pretty extreme polish - I'm going to close.
