### ISSUE TITLE
[HOLD for payment 2024-06-28] Clean up workspace avatars display logic

### ISSUE THREAD

**Issue by grgia** [Expensify/App#41912]
Follow up issue for tracking @Kicu

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by grgia** [comment]
Mind linking the original PR when you comment so I can assign @Kicu

**Comment by Kicu** [comment]
After quickfix is merged then I will do some improvement on the avatars code.

this was the PR that caused the original bugs: https://github.com/Expensify/App/pull/39637
this is the quickfix (not yet merged): https://github.com/Expensify/App/pull/41485

**Comment by grgia** [comment]
@Kicu mind sending an update on this?

**Comment by Kicu** [comment]
Well there is no updated on this since I haven't started to work on this yet.]
First this: https://github.com/Expensify/App/pull/41485 and https://github.com/Expensify/App/pull/41846 need to be merged (and in that order).

After both are merged I can work on this task.

**Comment by Kicu** [comment]
This is dragging on because of the merge freeze and still awaiting on https://github.com/Expensify/App/pull/41846

This is also mostly cleaning up avatar logic and making the code easier to work with in future. So I think there is no rush. I will keep tabs on this

**Comment by Kicu** [comment]
Still awaiting merge of https://github.com/Expensify/App/pull/41846

**Comment by grgia** [comment]
@abekkala could you help with $250 C+ review payment to @Pujan92?

**Comment by abekkala** [comment]
@grgia which PR is this payment for?

**Comment by Kicu** [comment]
I will take care of this task this week.

It took a long time because merge-freeze was holding another PR pre-requisite for this task, and then we had 2-day Holidays where I live.

**Comment by abekkala** [comment]
@grgia now I'm confused 😅. Is payment not needed yet? is there not a PR deployed?

You only mentioned a payment for C+ Review. Does Kicu require a payment too??

**Comment by Pujan92** [comment]
> @grgia now I'm confused 😅. Is payment not needed yet? is there not a PR deployed?

@abekkala no payment at the moment as this issue PR hasn't been raised yet bcoz we are waiting for other dependable PRs to merge.

**Comment by abekkala** [comment]
> @abekkala no payment at the moment as this issue PR hasn't been raised yet bcoz we are waiting for other dependable PRs to merge.

@Pujan92 correct, what I was looking for as the new assignee is information on who was hired for the fix and who is the PR reviewer? and why @grgia only mentioned paying for PR review. Is the person who is creating the fix not meant to be paid? is this a $250 job?

**Comment by Kicu** [comment]
>  what I was looking for as the new assignee is information on who was hired for the fix and who is the PR reviewer? 

I'm not sure exactly what @grgia meant, however to my knowledge there was no PR for this yet and no fix done. Since the beginning I was assigned to this task.

It took me a while because we had a merge freeze and then after it ended I was waiting for a different PR to be merged and that was merged about a week ago.
I will start working on this today and expect to have a PR ready next week for review.

Btw. this is not a straight fix for some UI bug, but rather cleaning up the code after several avatar-related changes that we did in the past couple of weeks.
I hope this clears things up 😄

**Comment by abekkala** [comment]
@grgia can you help clear this up here? 
You assigned me to send payment to @Pujan92 (as PR Review) - is there payment for the fixer? 
You created this issue last month - what project do you need this attached to?

**Comment by grgia** [comment]
@abekkala I mistook the linked PR for this issue, @Kicu and @Pujan92 are correct that theres no issue linked to this. This is a bug issue follow up, not linked to a project.

**Comment by Kicu** [comment]
PR will be ready later today

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JUNE 24

- Fix: @Kicu - SWM - no payment required
- PR Review: @s77rt [$250, pending no regressions] payment via NewDot

**Comment by s77rt** [comment]
@abekkala This is a cleanup issue only. No checklist is needed and no payment is due (payment is handled in parent issue). We can close this one

**Comment by s77rt** [comment]
Checklist https://github.com/Expensify/App/issues/41912#issuecomment-2181137406

**Comment by abekkala** [comment]
No overdue MELVIN! payment is set for Jun 28

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JUNE 28

- Fix: @Kicu - SWM - no payment required
- PR Review: @s77rt [$250] payment via NewDot

**Comment by s77rt** [comment]
Payment is handled on the parent issue since this is a clean up issue only.
