### ISSUE TITLE
Tags - Unable to disable ""Members must tag all spend" after renaming multilevel tag

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41927]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has multilevel dependant tags (csv file below)
- "Are these independent tags?" is unchecked when setting up dependant tags on OD (important)
1. Go to staging.new.expensify.com
2. Go to workspace settings (workspace with multilevel dependant tags)
3. Go to Tags
4. Click Settings
5. Enable "Members must tag all spend"
6. Click on the tag
7. Rename the tag and save it
8. Click Settings
9. Disable "Members must tag all spend"
10. Refresh the page
11. Click Settings

## Expected Result:
"Members must tag all spend" will remain disabled

## Actual Result:
"Members must tag all spend" is enabled again after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9db62108-7037-4d34-a205-abb14fe47475

[Bug6475924_1715260443757!Dependent_-_Multi_Level_tags_NEW.csv](https://github.com/Expensify/App/files/15264645/Bug6475924_1715260443757.Dependent_-_Multi_Level_tags_NEW.csv)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by trjExpensify** [comment]
@lanitochka17, why are they testing manually uploaded multiTags on Collect in NewDot? We don't intend to support that in NewDot, only via an accounting integration and the PR for that is in development. 

It looks like you're seeing some flakiness around that. Going to close this.
