### ISSUE TITLE
 Approved expenses opened as unreads in LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41921]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** 
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @LLPeckham 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715245144277879

## Action Performed:
Prerequisite: Have few expenses submitted and approved
1. Open the app
2. Login as a user who have approved expense report
3. Observe the LHN
4. Read the report and refresh the browser

## Expected Result:
Messages not reopen as unread messages in the LHN as they are already submitted/approved/read
## Actual Result:
Messages displayed as unread/unviewed expense in the LHN.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-05-09 at 9 59 17 AM](https://github.com/Expensify/App/assets/38435837/e5d89c64-9883-4346-b514-cfc210781ebf)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by LLPeckham** [comment]
@kevinksullivan - you might be able to close this out, I think this is a known bug that Scott is working on per this convo: https://expensify.slack.com/archives/C036QM0SLJK/p1715265761121379?thread_ts=1715252849.812579&cid=C036QM0SLJK
