### ISSUE TITLE
[Held on 39520] IOU - Pressing on the space bar while date picker RHP is open scrolls the details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41928]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-conditions:
- The screen size of your monitor/laptop should be small so that there is a scrollable space while in the expense details page
1. Navigate to staging.new.expensify.com
2. Create an expense and navigate to the expense details page
3. Open the Date picker RHP
4. Press on the space bar on your keyboard

## Expected Result:
Nothing happens

## Actual Result:
The app scrolls up the expense details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7e2f34d3-c2ce-47bd-9d11-821dece6040f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
I believe it's gonna be fixed by the focus trap [PR](https://github.com/Expensify/App/pull/39520). There was an [old issue](https://github.com/Expensify/App/issues/15631) similar to this before but closed.

cc: @roryabraham

**Comment by anmurali** [comment]
Let's test once that PR is shipped in that case.

**Comment by anmurali** [comment]
https://github.com/Expensify/App/pull/39520 is still being worked on

**Comment by anmurali** [comment]
There was a regression and that's being fixed, so still on hold.

**Comment by anmurali** [comment]
Same status as ^^

**Comment by anmurali** [comment]
Fixed.
