### ISSUE TITLE
Tag & tax rate - Tag and tax rate can be checked when deleted offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has categories, tags and tax rates
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Categories
4. Go offline
5. Delete one category
6. Click select all checkbox
7. Note that the deleted category is not checked
8. Repeat Step 4 to 7 with tags and tax rates

## Expected Result:
Tag and tax rate cannot be checked when deleted offline

## Actual Result:
Tag and tax rate can be checked when deleted offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/13d7887d-12ef-4f03-9fd6-a7bf658d2df7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by stephanieelliott** [comment]
This seems pretty minor and akin to a display issue, i don't think it's a priority to fix at the moment.
