### ISSUE TITLE
Email - The email preview of the attached long image is of low quality / resolution

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41930]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4550900&group_by=cases:section_id&group_id=292107&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a Gmail account
2. Open a chat with a Gmail account where you have access to it's email
3. Upload the attached long image
4. Check the Gmail client of the recipient

## Expected Result:
The preview should be of higher quality

## Actual Result:
The email preview of the attached long image is of low quality / resolution. Other types of images aren't affected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5ec31aa5-af2d-4933-be14-23788a684d07

![Bug6476047_1715266870108!bigggg](https://github.com/Expensify/App/assets/78819774/ed1a321c-e3d7-422a-9691-b7b85610aa92)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by puneetlath** [comment]
I think this probably isn't worth our time to try and figure out right now. Going to close, but feel free to comment or reopen if you disagree.
