### ISSUE TITLE
[HOLD for payment 2024-05-22] Split - Unable to perform uneven split in room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41931]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to #announce room which has at least another member.
3. Go to + > Split expense.
4. Enter amount > Next.
## Expected Result:
User is able to perform uneven split in room (production behavior).
## Actual Result:
User is unable to perform uneven split in room.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/267cf36d-6b1b-4b7a-b5a1-9515def5b4a2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@francoisl FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #vip-split

**Comment by mountiny** [comment]
cc @youssef-lr

**Comment by youssef-lr** [comment]
Working on a fix now

**Comment by youssef-lr** [comment]
`isPolicyExpenseChat` was wrongly being set to `true` when splitting from a policy room. PR is ready.

**Comment by youssef-lr** [comment]
@mountiny would you like to give it a quick review? changes are pretty simple

**Comment by youssef-lr** [comment]
Demoting this one, not a crucial flow and will be deployed soon in the regular cycle.

**Comment by youssef-lr** [comment]
will get to the checklist soon

**Comment by youssef-lr** [comment]
Still held.

**Comment by youssef-lr** [comment]
This was fixed.
