### ISSUE TITLE
IOU – Expense Report title field is missing in IOU for Gmail account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41937]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**https://expensify.testrail.io/index.php?/tests/view/4549008
**Email or phone of affected tester (no customers):** ponikarchuks+109524@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log is with Gmail account
3. Open Workspace chat
4. Create 2 IOUs
5. Open IOU from the chat
6. Verify that there is no Expense Report title field

## Expected Result:
Expense Report title field is present in IOU for Gmail account

## Actual Result:
Expense Report title field is missing in IOU for Gmail account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3317c2b8-5008-4756-9951-cc9d7769aa2f

![Bug6476093_1715269051458!report](https://github.com/Expensify/App/assets/78819774/0efb43af-7dd5-4f0a-b0f4-d9b3473be9b0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment]
Hmmm I feel like I should tag in @Expensify/design to review this one: I don't ever recall seeing a Report title like the ones in the above proposal. But Design should also weigh in on how/where we show it, if we want to show it.

**Comment by trjExpensify** [comment]
Pretty sure this is 1) behind a beta still 2) only going to be made available on `control` workspaces. @caitlinwhite1 can hipcheck me on that, but I think this is expected that a rando Gmail account on a `collect` workspace doesn't see report fields.

**Comment by trjExpensify** [comment]
Potentially, but I'll defer to @thienlnam & @caitlinwhite1 on the rollout consideration of that project. At some point we're going to move everyone using report fields on Collect to Control with @kevinksullivan's project.

**Comment by caitlinwhite1** [comment]
1) behind a beta still  - Correct, the beta has not yet been removed
2) only going to be made available on control workspaces - Correct, so we're currently on HOLD until we upgrade Collect users to Control this summer. At this point, we also plan to prevent Collect users from adding report fields in OldDot. Then we can remove the beta.

@trjExpensify

**Comment by trjExpensify** [comment]
Okay, so I don't think this issue is a bug then. @thienlnam can perhaps confirm if we're going to do this elsewhere before we close it out: 

>update the util function to only show those field when we have a control policy

**Comment by thienlnam** [comment]
Yeah this isn't a bug, let's update this test rail https://expensify.testrail.io/index.php?/tests/view/4549008 to indicate that it should only happen for control workspaces

**Comment by jliexpensify** [comment]
Awesome, thanks everyone. Closing this out!
