### ISSUE TITLE
[$500] [HOLD for payment 2024-05-29] Anonymous session not created on deep-linking to specific comments in public rooms

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#41948]
When you deep-link to a specific comment in a public room, it asks you to sign in (ie, it doesn't show you the public room with an anonymous account).

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013caae7ec700ad741</li>
        <li>Upwork Job ID: 1795943315996286976</li>
        <li>Last Price Increase: 2024-05-29</li>
    </ul>
</details>

**Comment by alexpensify** [comment]
@marcochavezf - should we assign this one as internal? Also, what Wave is this associated with? Thanks!

**Comment by marcochavezf** [comment]
This bug was reported from an [internal channel](https://expensify.slack.com/archives/C03U7DCU4/p1715278178114499) and I think vip-vsb should be the correct associated project.

**Comment by marcochavezf** [comment]
Update: PR merged and deployed to staging https://github.com/Expensify/App/pull/41949#issuecomment-2112118394

**Comment by marcochavezf** [comment]
Assigning @ishpaul777 for C+ review payment once the PR is deployed to production + 7 days

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

@strepanier03 - While I'm offline, I need help here completing the payment process after this one clears the 7-day period. Thanks!

**Comment by strepanier03** [comment]
Still on staging so waiting for hold to start.

**Comment by strepanier03** [comment]
Deployed to production 2024-05-22, 7-day hold begins. Hold ends on 2024-05-29, I'll update the title.

**Comment by alexpensify** [comment]
@strepanier03 - was everyone paid here? I'm back online and seeing if I need to take over. Thanks!

**Comment by alexpensify** [comment]
I'm taking over as the BZ member here again. I realized that I mixed up my days and thought the 29th was Monday. I'm back on track now and I'll complete the next steps.

**Comment by alexpensify** [comment]
@ishpaul777 - please accept the invite in Upwork and I can complete the payment process. Thanks!

**Comment by alexpensify** [comment]
Closing - I've completed the payment process in Upwork. Sorry, @ishpaul777, I missed the note to add a comment, but I typically leave the highest stars. Noted for the next time!
