### ISSUE TITLE
BUG: Signed up as a new user in a UCR. The display name in my selfDM say’s guest.

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#41960]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715275292465829

## Action Performed:
1. I went to https://new.expensify.com/r/6879144773653084 on web incognito as a new user
2. I viewed the room
3. I signed up [danrvidal+exfytest1@gmail.com](mailto:danrvidal+exfytest1@gmail.com)

## Expected Result:
self DM shouldn't show up as Guest

## Actual Result:
self DM is showing up as Guest even though I input my email upon sign up

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (15)](https://github.com/Expensify/App/assets/6829422/abef9e3c-a07c-48f2-96bb-13f637ec29e8)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
Update, the auth PR isnt deployed yet ([context](https://github.com/Expensify/Auth/pull/10848#issuecomment-2116233233))

**Comment by jayeshmangwani** [comment]
Not overdue; Issue is being handled internal

**Comment by marcochavezf** [comment]
Not overdue, same [update](https://github.com/Expensify/App/issues/41960#issuecomment-2116234990) applies here

**Comment by marcochavezf** [comment]
Moving it to weekly per this comment https://github.com/Expensify/Auth/pull/10848#issuecomment-2116233233
