### ISSUE TITLE
[$500] Android - Split - Input shows the content briefly when pasting word in split amount field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41961]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has copied words to clipboard
1. Launch New Expensify app
2. Go to group chat
3. Go to + > Split expense
4. Enter amount > Next
5. Tap on the split amount field
6. Clear the field
7. Paste the text from clipboard

## Expected Result:
The input will remain static when pasting text because it only supports numbers

## Actual Result:
The input shows the content briefly when pasting word in split amount field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec8162b6-65d2-4b8e-8bd2-7defcc75c048

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec930cc674fea0dd</li>
        <li>Upwork Job ID: 1789994615970213888</li>
        <li>Last Price Increase: 2024-07-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by greg-schroeder** [comment]
Sending to `external`

**Comment by rojiphil** [comment]
Awaiting Proposals

**Comment by greg-schroeder** [comment]
Same as above, go away Melvin!

**Comment by greg-schroeder** [comment]
Hmm, still not a ton of movement on this one. Perhaps we can try another route ... let me check w/ the team

**Comment by greg-schroeder** [comment]
Go away Melvin

**Comment by greg-schroeder** [comment]
I've asked if we need to raise the bounty, stand by

**Comment by greg-schroeder** [comment]
Asked Matt to see if he thinks we could double this

**Comment by greg-schroeder** [comment]
Doubled!

**Comment by samilabud** [comment]
I think this cannot be handled unless we develop a whole TextInput component (maybe called NumberInput) from scratch and not using the one that comes with React Native. Please see this comment:

Please see this comment:
https://stackoverflow.com/a/32956836/7543637

**Comment by QichenZhu** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Amount input accepts and shows illegal characters briefly.

### What is the root cause of that problem?
`react-native` disables key filtering for text inputs in Android on purpose.

This is explained in the [code](https://github.com/facebook/react-native/blob/42299499d8cac0b3e6ae7814ca375005ecfa05f0/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L536-L544):

> We override the KeyListener so that all keys on the soft input keyboard as well as hardware keyboards work. Some KeyListeners like DigitsKeyListener will display the keyboard but not accept all input from it

and in [this commit message](https://github.com/facebook/react-native/commit/fa4a5afe35af4e93059b089c3107af916a5b21ab):

> Makes it so that when a keyboard is displayed, all keys in that keyboard actually can be set as text.  Previously you could display a Numeric keyboard and it would only allow entering numbers despite the keyboard having other keys like comma, plus, space, etc.

Related issues: https://github.com/facebook/react-native/issues/38155, https://github.com/facebook/react-native/issues/24585.

### What changes do you think we should make in order to solve the problem?
We can patch `react-native` locally by removing [this line](https://github.com/facebook/react-native/blob/42299499d8cac0b3e6ae7814ca375005ecfa05f0/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L544), and also create a PR to `react-native` to add an option to enable/disable key filtering.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by greg-schroeder** [comment]
@rojiphil what do you think of this comment? https://github.com/Expensify/App/issues/41961#issuecomment-2148474894

**Comment by greg-schroeder** [comment]
Bump @rojiphil on this if you can take a look! https://github.com/Expensify/App/issues/41961#issuecomment-2153523917

**Comment by rojiphil** [comment]
> Bump @rojiphil on this if you can take a look!

@greg-schroeder Sorry for the delay in response here.

**Comment by rojiphil** [comment]
@QichenZhu Thanks for the proposal

> react-native disables key filtering for text inputs in Android on purpose.

Since we are talking about clipboard `paste` here, would enabling key filtering work when we `paste` via clipboard?

> We can patch react-native locally by removing [this line](https://github.com/facebook/react-native/blob/42299499d8cac0b3e6ae7814ca375005ecfa05f0/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L544), 

Can you please share the details of how the patch will look like? Also, please share a test video of how it will look once we apply the patch.

**Comment by QichenZhu** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/41961#issuecomment-2150285581)

**Comment by QichenZhu** [comment]
@rojiphil Thank you for considering my proposal!

> Since we are talking about clipboard paste here, would enabling key filtering work when we paste via clipboard?

Yes, it works when pasting.

> Can you please share the details of how the patch will look like? Also, please share a test video of how it will look once we apply the patch.

Please find my updated [proposal](https://github.com/Expensify/App/issues/41961#issuecomment-2150285581) and the below recording.

https://github.com/Expensify/App/assets/57348009/68c9e920-905d-4dfd-8717-69a47dcfef91

**Comment by greg-schroeder** [comment]
Proposal review continues

**Comment by greg-schroeder** [comment]
Bump @rojiphil as the proposal was updated above

**Comment by rojiphil** [comment]
> `-    setKeyListener(mKeyListener);`

@QichenZhu  Thanks for sharing the details of the patch [here](https://github.com/Expensify/App/issues/41961#issuecomment-2150285581)
As you mentioned, this change has been intentionally introduced in `react-native`. In fact, it has been added a good 8+ years back. And I am not that sure if Meta would find our reasoning convincing enough to make the change. Also, wondering if this could introduce any regressions with respect to key inputs.
Let me take some advice from internal members on this.

@vit I need expert help in the review here as the proposed changes are in `react-native` TextInput. Can you please help unblock?

**Comment by QichenZhu** [comment]
Thanks for the comment. The problem with `react-native` is that it changed the default behavior of Android text inputs, causing our issue and several upstream issues (https://github.com/facebook/react-native/issues/38155, https://github.com/facebook/react-native/issues/24585). So I propose reverting to the default behavior or, maybe even better, providing an option to enable/disable it.

**Comment by greg-schroeder** [comment]
Discussion is ongoing

**Comment by greg-schroeder** [comment]
What do you think of the above @rojiphil?

**Comment by greg-schroeder** [comment]
Bump!

**Comment by rojiphil** [comment]
Looks like the fix may require upstream changes to `react-native` code and I am still on the fence about this.

Also, comment [here](https://github.com/Expensify/App/issues/41961#issuecomment-2185828487) and follow-up comment [here](https://github.com/Expensify/App/issues/41961#issuecomment-2187903724) need to be reviewed. Overall, I think providing an option to enable/disable key filtering seem to be a good way forward. But I also think an expert feedback from someone who has handled upstream changes to `react-native` text input would come in handy here. 

Let me involve an internal engineer to weigh in first and take this from there.
🎀👀🎀
