### ISSUE TITLE
[Instant Submit] New workspace created from NewDot defaults to `Weekly` instead of `Instantly` 

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#41978]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.71-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C02QSAC6BJ8/p1714748406271909?thread_ts=1714747562.593329&cid=C02QSAC6BJ8

## Action Performed:
1. Sign up for NewDot
2. Create a new workspace
3. Switch to Expensify Classic
4. Open workspace settings > Reports

## Expected Result:
Scheduled Submit should be defaulted to `Instantly`

## Actual Result:
Scheduled Submit is defaulted to `Weekly`

## Workaround:
N/A

## Platforms:
All platforms

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c57018715f9f463</li>
        <li>Upwork Job ID: 1788903601306804224</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

**Comment by Beamanator** [comment]
More ways this can happen, in OldDot: `https://www.expensify.com.dev/admin_policies?param={"createPolicy","team"}`

**Comment by Beamanator** [comment]
I believe i figured out why this happens... Has to do with `withInboxPolicySettings` -> We don't pass that to `PolicyAPI::create` in NewDot, only in Old - and not ALWAYS, but "most of the time" - I'm trying to figure out what it's actually needed for so I can implement similar logic in NewDot

**Comment by Beamanator** [comment]
Working on deploy blockers day, probs won't get to this yet

**Comment by Beamanator** [comment]
Same, maaaaaaaybe tomorrow

**Comment by Beamanator** [comment]
Ok will work on this early next week!

**Comment by Beamanator** [comment]
Draft PR up, will get it ready for review tomorrow 🙏

**Comment by Beamanator** [comment]
PR in review (though i believe we're still on merge freeze)

**Comment by slafortune** [comment]
I'll be on vacation until June 4th, so adding another BZ in the meantime.

**Comment by Beamanator** [comment]
Focusing on api optimization issues today, planning to get to this wednesday

**Comment by Beamanator** [comment]
Updated PR, back in review!

**Comment by Beamanator** [comment]
Should be working in prod, BUT probably not while offline in NewDot - that should be a quick fix

**Comment by Beamanator** [comment]
App PR (for optimistic instant submit policy) created ^, should be last for this issue

**Comment by slafortune** [comment]
looks like this was sent to production last week - are we good to close this now @Beamanator ?

**Comment by mallenexpensify** [comment]
Looks like @aimane-chnaif reviewed the last PR, they're likely due compensation
https://github.com/Expensify/App/pull/43273

**Comment by Beamanator** [comment]
Mmmm fair, though it was a very tiny & simple PR 🤷  is it fair to pay out half since it was only tested on 1 platform & was a very small App PR?

**Comment by Beamanator** [comment]
Oh that's nifty, I didn't know that! 😅

**Comment by slafortune** [comment]
@aimane-chnaif offer sent [here](https://www.upwork.com/nx/wm/offer/102857095)

**Comment by Beamanator** [comment]
Bump @aimane-chnaif , did you accept? 😅

**Comment by slafortune** [comment]
Paid @aimane-chnaif ✅
