### ISSUE TITLE
[Guided Setup Stage 2] Auto-completed task reverts to incompleted

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#41988]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%22881a6306dadc4164-LHR%22%20AND%20timestamp%3A%5B2024-05-10T00%3A00%20TO%202024-05-11T23%3A59%5D

requestID: `881a6306dadc4164-LHR`
**Expensify/Expensify Issue URL:**
**Issue reported by:** @anmurali 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1715349235994939?thread_ts=1715336603.190319&cid=C036QM0SLJK

## Action Performed:
1. Sign-up as a new user on NewDot 
2. Choose "Manage my team's expenses" as the onboarding intent 
3. Complete the rest of the flow 
4. Observe the "create workspace" task appears completed (it's strike'd through)
5. Wait a couple of seconds
6. Observe the "Create workspace" task now appears incomplete (the strikethrough is reverted)

## Expected Result:
We create a workspace when you choose the "Manage my team's expenses" intent, so the "Create workspace" task should remain completed. 

## Actual Result:
The task completes and then reverts. If you sign out and back in, it appears completed again. 

Note: The `CompleteTask` command that's triggered after `CompleteGuidedSetup` looks good in the logs, so the working theory is that it's something to do with a pusher event reverting it.

## Workaround:
Yes, you can sign-out and sign-in again to see the task completed again. It defeats the point though with infinite sessions

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/16232057/242eb752-a5a2-4015-b6f0-18e587430e26

![image](https://github.com/Expensify/App/assets/16232057/d09c83b9-0b9d-4cac-99b9-ccc6bc38bb29)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115549a3f259c426f</li>
        <li>Upwork Job ID: 1788974714370433024</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

**Comment by mountiny** [comment]
PR is up, still needs more testing

**Comment by mountiny** [comment]
PR is ready for a review

**Comment by DylanDylann** [comment]
@mountiny Do we need a C+ review for this issue?

**Comment by mountiny** [comment]
@DylanDylann This is a backend issue so no, I will remove your assignment
