### ISSUE TITLE
[TS migration] Create a `prefer-type-fest` ESLint rule

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#41991]
# Summary

Create a prefer-type-fest TS lint rule that identifies places where code can be made more readable by using type-fest utility types.

Context: https://expensify.slack.com/archives/C0593T50UHG/p1715356357600679

# Details

Example:

```tsx
/** Example: TupleToUnion */
const STUFF = ['a', 'b', 'c'] as const;

// BAD
type Bad = (typeof STUFF)[number];

// GOOD
type Good = TupleToUnion<typeof STUFF>;

/** Example: ValueOf */
const COLORS = {
    GREEN: 'green',
    BLUE: 'blue',
} as const;

// BAD
type Bad = (typeof COLORS)[keyof COLORS];

// GOOD
type Good = ValueOf<typeof COLORS>;
```

Let's brainstorm and check which patterns are most used in the App and could be replaced with `type-fest` types, and then create the rule covering those situations. @roryabraham @blazejkustra

**Comment by roryabraham** [comment]
Making this a monthly as it's lower-priority. It's also not a bug but a new feature

**Comment by roryabraham** [comment]
For now I'd propose just starting with these two:

- `ValueOf` because it's by far the most common one we use
- `TupleToUnion` because the vanilla TS syntax with `(typeof myArray)[number]` is just confusing (imo)

**Comment by roryabraham** [comment]
@fabioh8010 you've got a few other things on your plate. Do you want to drop this one and open it up for the community?

**Comment by blazejkustra** [comment]
I briefly discussed it with Fabio, and we would prefer to handle this internally so we can complete it quicker. Past TS follow-ups have shown that issues like this typically take longer when left to external contributors.

I should have some availability this week. @roryabraham please reassign the issue to me, and I'll begin working on it tomorrow.

**Comment by blazejkustra** [comment]
Update: Today I had to wrap up my other PRs, I'm going to start this tomorrow.

**Comment by blazejkustra** [comment]
Update: Rule is almost finished - [here](https://github.com/Expensify/eslint-config-expensify/pull/100) is a draft PR. There is one last edge case that I need to cover, should be ready tomorrow.

**Comment by blazejkustra** [comment]
@roryabraham @fabioh8010 PR is ready for review

**Comment by roryabraham** [comment]
reviewed, requested that we cover 1 missing case

**Comment by roryabraham** [comment]
This is done. Thanks all!
