### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250] Order Suggested Mentions according to relevancy when in a Group Chat

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#42009]
# Feature Description
Right now, when you hit `@` to tag someone without starting to type any letters, we show you a list of everyone you have a "connection" to in alphabetical order:
![IMG_4340 (1)](https://github.com/Expensify/App/assets/4741899/999d8188-f45b-4f74-863e-e55c78def908)

However, when in a group chat or a chat connected to a workspace, there's a high chance you're looking to tag someone within that group/workspace. In fact, seeing "random" users as suggestions when presented in alphabetical order is even a bit disorienting.

So, let's re-prioritize the list shown in [`MentionSuggestions`](https://github.com/Expensify/App/blob/1044bad394543fde51d2e89b6f935444b5fd3779/src/components/MentionSuggestions.tsx) so that they are always in the following order:
1. People within the chat (members of the Report)
2.  People within the Workspace
3. Other Contacts (the current way we do it)

# Manual Test Steps
1. Type in `@` in a group chat with several participants
2. Make sure that the list of participants is shown first to you as suggestions, in alphabetical order, then the list of the rest of your contacts, in alphabetical order.
3. Type in a letter, and make sure the list is filtered to the individuals containing that letter with the same hierarchy preserved as described above.

---

1. Type in `@` in a Workspace room, where only a fraction of the workspace members are in the room.
2. Make sure that the list of participants is shown first to you as suggestions, in alphabetical order, then the list of workspace members, in alphabetical order, the the rest of your contacts, in alphabetical order.
3. Type in a letter, and make sure the list is filtered to the individuals containing that letter with the same hierarchy preserved as described above.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186b4970c1baed84a</li>
        <li>Upwork Job ID: 1789048257508220928</li>
        <li>Last Price Increase: 2024-05-17</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by johncschuster** [comment]
@alitoshmatov can you review the above proposals when you get a moment?

**Comment by alitoshmatov** [comment]
@gijoe0295 Thank you for your proposal. Your solution does make sense. But I am worried if iterating over each account is efficient considering that every time user types the mentions should update. But it looks as a potential solution.

**Comment by alitoshmatov** [comment]
Let's take some time if @gijoe0295 's proposal is efficient enough. Would be great if you could test it @gijoe0295.

Meanwhile we are open to new and better proposals

**Comment by johncschuster** [comment]
@alitoshmatov can you review the comment above?

**Comment by johncschuster** [comment]
@alitoshmatov can you review the comment above?

**Comment by mallenexpensify** [comment]
@alitoshmatov 👀 on the [comment above](https://github.com/Expensify/App/issues/42009#issuecomment-2116552994) plz.

**Comment by alitoshmatov** [comment]
Sorry missed this one.

I see thank you @gijoe0295. 

We can go with @gijoe0295 's [proposal](https://github.com/Expensify/App/issues/42009#issuecomment-2105413569). Where they suggest to implement weighted grouping for mention items

**Comment by alitoshmatov** [comment]
Forgot to add

C+ reviewed 🎀 👀 🎀

**Comment by johncschuster** [comment]
Looks like this was deployed on the 14th, which is 7 days ago. @yuwenmemon, am I missing a deploy? If not, I should issue payment today.

**Comment by johncschuster** [comment]
Discussing in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1719241991045089) to make sure I'm understanding the correct payment date

**Comment by johncschuster** [comment]
Payment has been issued! Thanks for your contributions! 🎉 

@yuwenmemon, do you know if we need a regression test for this?

**Comment by johncschuster** [comment]
Bump on the above!

**Comment by yuwenmemon** [comment]
I think we should have one yeah.

**Comment by johncschuster** [comment]
@alitoshmatov / @gijoe0295, can one of you put together a regression test checklist for this one?

**Comment by alitoshmatov** [comment]
I think testing steps provided in [PR](https://github.com/Expensify/App/pull/42553) fits perfectly

**Regression Test Proposal**
A
1. Type @ in a group chat with several participants
2. Verify the order of suggestions: group members >> other contacts, both in alphabetical order
3. Type in a letter
4. Verify the list is filtered to the individuals containing that letter with the same hierarchy preserved as described above
B
1. Type @ in a Workspace room, where only a fraction of the workspace members are in the room
2. Verify the order of suggestions: room members >> workspace members >> other contacts, all in alphabetical order
3. Type in a letter
4. Verify the list is filtered to the individuals containing that letter with the same hierarchy preserved as described above


Do we agree 👍 or 👎

**Comment by johncschuster** [comment]
Looks great! Thanks, @alitoshmatov!
