### ISSUE TITLE
Don't return `paycheck` reports in Search results

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#42028]
I just did a test run of the `Search` v1 page and noticed that we are returning `paycheck` reports. At this juncture, we should only be returning `iou` and `expense` reports. Going to keep this one internal. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca08bf5c5aba5990</li>
        <li>Upwork Job ID: 1789757359643729920</li>
        <li>Last Price Increase: 2024-05-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
PR in review

**Comment by luacmartins** [comment]
Back from ooo today. Gonna resolve conflicts on the PR and get it merged/

**Comment by luacmartins** [comment]
This is done
