### ISSUE TITLE
[Search v1] Duplicate Expensify Card charge

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#42029]
Not sure what's going on here, though we should look into this one. I'm seeing a duplicate for a recent Expensify Card transaction on a recent trip. 

![CleanShot 2024-05-12 at 15 12 37@2x](https://github.com/Expensify/App/assets/1127863/de7e713b-6d13-41be-af86-786cbc6ec4d6)

Clicking on the `__fake__` report gives me the "hmm it's not here" not found error. In contrast, the expense which correctly shows the Expensify workspace appears in the RHP without issue. 

Assigning internally as part of this release. 

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
@JmillsExpensify is this duplicate charge still visible for you? Could you get the transactionID of both transactions? You could do this by:

1. Opening browser console: `cmd + option + i`
2. Navigate to the `Application` tab
3. Select `Storage > IndexedDB > OnyxDB > keyvaluepairs`
4. Search for `snapshot`
5. Click on the result and expanding `data`
6. Look for the transactions with the amount above (note amounts are in cents)
7. Expand the transaction once you find it and take a screenshot of the data stored

<img width="1036" alt="Screenshot 2024-05-15 at 9 42 54 AM" src="https://github.com/Expensify/App/assets/22219519/d1919bf2-da8a-4533-bea0-4c24e1006e67">

I wanna compare the data to see what's going on with them.

**Comment by JmillsExpensify** [comment]
Yes, I still see the duplicates. I can only find data for one of the transactions though in the Onyx DB. 

![CleanShot 2024-05-15 at 09 34 42@2x](https://github.com/Expensify/App/assets/1127863/86246f90-5267-4df0-831c-23b63240bfec)

**Comment by JmillsExpensify** [comment]
Here's what I'm seeing for those transactions. 
![CleanShot 2024-05-15 at 09 40 29@2x](https://github.com/Expensify/App/assets/1127863/948cdc84-5b3e-4c18-bf97-3308ac8ea776)

**Comment by JmillsExpensify** [comment]
Clicking on the `__fake__` row gives me a "Hmm, it's not here" error in the RHP.

**Comment by luacmartins** [comment]
PR up

**Comment by luacmartins** [comment]
PR is merged and deployed. Closing this one.
