### ISSUE TITLE
Split: IOU's from the splits are not shown in the LHN for the individuals

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42021]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @yuwenmemon 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715364896808069

## Action Performed:
1. Create a split expense using SmartScan with a group of people including someone you have not interacted with before and would not be in your "known" network
2. Wait for the IOUs to be created
## Expected Result:
The IOUs for everyone shows up in your DM with them
## Actual Result:
The IOUs for people you had not interacted with before and not in your "network" don't show up in the DM. They only show up after logging in and out.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3acec410-d358-4271-8cec-a62ba8346114
![Screenshot 2024-05-09 at 9 21 47 PM](https://github.com/Expensify/App/assets/38435837/a707a998-0421-45cf-a469-e44397450ba5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Reproing today

**Comment by dylanexpensify** [comment]
Couldn't repro - @yuwenmemon you still seeing this?

**Comment by yuwenmemon** [comment]
I believe @youssef-lr was working on a fix for it yeah.

**Comment by saracouto** [comment]
@dylanexpensify - @youssef-lr tried to reproduce the bug today and he couldn't.

**Comment by youssef-lr** [comment]
@saracouto trying on a completely fresh account I was able to reproduce. I will investigate today.

**Comment by youssef-lr** [comment]
I haven't had the chance to investigate this yet, planning to do it tomorrow

**Comment by dylanexpensify** [comment]
@youssef-lr mind giving a rough ETA?

**Comment by youssef-lr** [comment]
I just got done with this [issue](https://github.com/Expensify/Expensify/issues/395703) which took time, I'm investigating this today and will post an update today

**Comment by youssef-lr** [comment]
Still on it, no update yet

**Comment by dylanexpensify** [comment]
sounds good!

**Comment by youssef-lr** [comment]
I think I'm going to pause working on this based on this https://expensify.slack.com/archives/CC7NECV4L/p1717525527830119

**Comment by dylanexpensify** [comment]
Yeah, that sounds good to me cc @saracouto for good measure. If we do, let's add [HOLD]

**Comment by saracouto** [comment]
Yeah I have updated this to reflect the new status

**Comment by dylanexpensify** [comment]
NOICE!

**Comment by dylanexpensify** [comment]
Waiting

**Comment by dylanexpensify** [comment]
Waiting

**Comment by dylanexpensify** [comment]
Same

**Comment by dylanexpensify** [comment]
Closing for focus
