### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Task- User avatar when opening from task preview mention is not the same as chat header avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42027]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Assign task
3. Enter title > Next
4. Click Assignee
5. Enter a random email address that does not have Expensify account
6. Create the task
7. After a while, click on the user mention in the task preview in the main chat

## Expected Result:
User avatar when opening from task preview mention will be the same as chat header avatar

## Actual Result:
User avatar when opening from task preview mention is not the same as chat header avatar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c062f6a0-85fe-4f87-baa5-d31d71569c45

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5ef607fad2434e6</li>
        <li>Upwork Job ID: 1789924778097631232</li>
        <li>Last Price Increase: 2024-05-27</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102496803</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment]
@jasperhuangg  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Beamanator** [comment]
Interesting, so the first time I click on the mention, I see the accountID is 17146630 with avatar https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_23.png - in the profile page, which is correct according to onyx

But in the Report Screen header, in MultipleAvatars we're passing an accountID of 1024805772, which seems to be the optimistic accountID - which is in Onyx, and has a default avatar of https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_13.png

**Comment by Beamanator** [comment]
In `HeaderView`, I'm seeing that the report has `participantAccountIDs` as `[1024805772]`

So it looks like the NEW accountID is returned in the `CreateTask` network request, but it looooks like the optimistic account ID isn't being removed, AND it's still being linked to in some places (the report screen header & the "This is the beginning of your chat" intro text avatar

**Comment by Beamanator** [comment]
I did, however, just reproduce in production so this shouldn't be a blocker - i'm going to test again on another platform

**Comment by Beamanator** [comment]
I'm marking this `External` because it loooks like the API response is correct, we're just not getting the updated data in the report screen where we need it, so i think this can be external

**Comment by CortneyOfstad** [comment]
@allroundexperts there is a proposal [here](https://github.com/Expensify/App/issues/42027#issuecomment-2107178694) that is waiting on review — thanks!

**Comment by Beamanator** [comment]
Since this proposal involves some interesting Onyx updates, I wonder if we should bring this to a wider audience / into Slack?

**Comment by allroundexperts** [comment]
Agreed. I reviewed the proposal yesterday but wasn't sure about the Onyx changes.

**Comment by allroundexperts** [comment]
@tienifr can you raise a thread in Slack regarding these Onyx changes? Thanks!

**Comment by CortneyOfstad** [comment]
@tienifr any update on the Slack link? Thanks!

**Comment by CortneyOfstad** [comment]
@tienifr please provide an update by EOD please. Thanks!

**Comment by Beamanator** [comment]
Thanks @tienifr !

**Comment by Beamanator** [comment]
Thanks @tienifr ! @allroundexperts please review the updated proposal when you have a chance 🙏

**Comment by allroundexperts** [comment]
@Beamanator I'm still not sure if `sanitizing` the onyx updates is a concrete solution. It seems like more of a workaround to me. Are you onboard with the sanitization approach?

**Comment by allroundexperts** [comment]
@Beamanator Are you onboard with the sanitisation approach? I feel like its better to fix on the backend.

**Comment by allroundexperts** [comment]
Melv. Calm down. We're in discussion mode!

**Comment by Beamanator** [comment]
Sorry for the delay! OK I just read through the updated proposal... That's quite an interesting idea about sanitizing... I think it would be better to alert instead of quietly sanitizing, and making sure the onyx updates are fixed... But I think again this should be brought to a bigger convo since this would affect many developers.

For now I think it's best to just fix the currently affected endpoint & bring up the sanitizing comment in slack to see what others think

**Comment by Beamanator** [comment]
So it sounds like there's some front-end & some back-end changes required for this specific fix, right? I think we can assign @tienifr for at least the front-end and I can fix the back-end

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by allroundexperts** [comment]
@tienifr Any update on where you are with the frontend changes?

**Comment by CortneyOfstad** [comment]
Sounds good — thanks @tienifr!

**Comment by CortneyOfstad** [comment]
@allroundexperts can you please complete the checklist by EOD so there is no delay in payment tomorrow? Thanks!

**Comment by CortneyOfstad** [comment]
@allroundexperts bump on the checklist above ^^^

**Comment by allroundexperts** [comment]
On it today!

**Comment by allroundexperts** [comment]
## Checklist
1. There isn't any PR which caused this issue. It seems like we had an inconsistency in the way that backend was sending a `merge` before `set`.
2. N/A
3. N/A
4. A regression test would be useful here. The test steps given in the OP seem easy to follow.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
