### ISSUE TITLE
Scan - the message preview in LHN does not show "Receipt Scan in progress.."

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42055]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v1.4.73-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to a workspace chat as the employee with no previous history
2. Submit Expense
3. Notice in the LHN of the workspace chat shows Receipt Scanning.
4. Go to the request conversation
5. The request conversation message preview in LHN shows as "$0.00 Expense"

## Expected Result:
LHN shows as "Receipt Scan in progress.."
## Actual Result:
LHN shows as "$0.00 Expense"
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/02f7ef8d-3af4-4a16-95cb-5e18aa0b86b4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d67326726a076361</li>
        <li>Upwork Job ID: 1790110030784376832</li>
        <li>Last Price Increase: 2024-05-13</li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@kadiealexander FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by arosiclair** [comment]
Site is very slow atm so I'm having trouble testing this

**Comment by arosiclair** [comment]
Reproduced on staging **v1.4.73-1**. Looks like `OpenReport` for the expense report is sending the incorrect `lastMessageText`:

<img width="1624" alt="Screenshot 2024-05-13 at 12 37 54 PM" src="https://github.com/Expensify/App/assets/6833644/6ecb403a-94e9-4187-b145-77eba17b640a">

**Comment by arosiclair** [comment]
Did NOT reproduce in prod **v1.4.72-1**. `OpenReport` also still returns the same `lastMessageText` on prod so that doesn't seem to be the problem actually.

**Comment by arosiclair** [comment]
I reproduced on staging **v1.4.73-1** even while using the prod API so this isn't an API blocker

**Comment by kadiealexander** [comment]
Not overdue, waiting for an engineer to pick this up.

**Comment by kadiealexander** [comment]
Not overdue!

**Comment by kadiealexander** [comment]
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1716425872632919).

**Comment by kbecciv** [comment]
Issue is reproducible on build 1.4.75.0

https://github.com/Expensify/App/assets/93399543/83e86370-4687-4068-8d12-4bdcb984e492

**Comment by kadiealexander** [comment]
Not overdue, very minor bug.

**Comment by kadiealexander** [comment]
Not overdue

**Comment by kadiealexander** [comment]
Still reproducible:

https://github.com/Expensify/App/assets/59587260/8c65e680-c896-4db5-a13c-86114ea4d991

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
Still not overdue

**Comment by kadiealexander** [comment]
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1718333301155199).

**Comment by kavimuru** [comment]
Reproducible by the tester

https://github.com/Expensify/App/assets/43996225/5f9bfdd7-6222-4624-a626-d847128ec7b2

**Comment by kadiealexander** [comment]
Still not overdue!

**Comment by kadiealexander** [comment]
Still not overdue

**Comment by kadiealexander** [comment]
Not overdue.
