### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250]  Login - "The email entered is invalid" error isn't appearing when you tap away

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42054]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.72.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log out
2. Tap inside the email field
3. Enter an invalid email
4. Tap away so the field loses focus

## Expected Result:
The message should appear as shown in mWeb and Web.

## Actual Result:
"The email entered is invalid" error isn't appearing when you tap away from the email field that contains an invalid email address

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/df2796a0-09a0-4030-8046-5e982f351d90

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e7c19b20c3fa187</li>
        <li>Upwork Job ID: 1790156414947115008</li>
        <li>Last Price Increase: 2024-05-27</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102514414</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- "The email entered is invalid" error isn't appearing when you tap away from the email field that contains an invalid email address
 
### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/ff2b4403464518d7b4ac77d9651238e511adad1c/src/pages/signin/LoginForm/BaseLoginForm.tsx#L240), we only call ```validate``` if ```willBlurTextInputOnTapOutside: true```, that leads to the bug.

- With native device, we assumed that ```As we have only two signin buttons (Apple/Google) other than the text input, for natives onBlur is called only when the buttons are pressed and we don't need to validate in those case as the user has opted for other signin flow.```

- But, ```onBlur``` is also called if we click outside the input like mentioned in OP.
### What changes do you think we should make in order to solve the problem?
- We need to create the global variable, named ```didPressGoogleOrIOSButton``` to know whether the input is blurred because user clicked on Google or IOS buttons or not. It will be set once we press on Google or IOS button.

- Then, update [this](https://github.com/Expensify/App/blob/ff2b4403464518d7b4ac77d9651238e511adad1c/src/pages/signin/LoginForm/BaseLoginForm.tsx#L240) to:
```
                        !didPressGoogleOrIOSButton
```

- Then we need to clean-up the ```didPressGoogleOrIOSButton``` 
### What alternative solutions did you explore? (Optional)
- NA

**Comment by sonialiap** [comment]
@mollfpr what do you think of the updated proposal?

**Comment by sonialiap** [comment]
@mollfpr gentle bump for reviewing the proposal

**Comment by mollfpr** [comment]
@Krishna2323 Removing `willBlurTextInputOnTapOutside` check will work on native but not on web. The error will appear on pressing the google/apple sign in.

**Comment by mollfpr** [comment]
> We need to create the global variable, named didPressGoogleOrIOSButton to know whether the input is blurred because user clicked on Google or IOS buttons or not.

@nkdengineer Why do we need a global variable for that? Could the local state be enough?

> Then we need to clean-up the didPressGoogleOrIOSButton

What does this step mean?

Also, you have 23 open PRs right now. Do you have the bandwidth for another issue?

**Comment by nkdengineer** [comment]
> Could the local state be enough?

Yes, I think so. 


> What does this step mean?

This step is redundant so I removed it from my proposal

**Comment by nkdengineer** [comment]
> Also, you have 23 open PRs right now. Do you have the bandwidth for another issue?

There are a lot of PRs that are pending actions from the internal team, on hold, ... Also, I always try to update all the PRs before posting proposals for other issues.

**Comment by mollfpr** [comment]
@Krishna2323 We still need the check or we will repro the issue again https://github.com/Expensify/App/pull/34863.

I think the [proposal](https://github.com/Expensify/App/issues/42054#issuecomment-2107692244) from @nkdengineer looks good! We should make sure not to introduce the old bug.

🎀 👀 🎀 C+ reviewed!

**Comment by nkdengineer** [comment]
@mollfpr PR https://github.com/Expensify/App/pull/42830 can be reviewed

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/34863

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/34863/files#r1653356984

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

Test case 1:
1. Go to sign-in page
2. Tap inside the email field
3. Enter an invalid email
4. Tap away so the field loses focus
5. **Verify** that the validate error is appear


Test case 2:
1. Go to sign-in page
2. Focus on the text input
3. Click on the Google sign-in button
4. **Verify** that the validate error doesn't appear

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr
