### ISSUE TITLE
[HOLD for payment 2024-05-22] Login - 'Another login page is open' briefly displayed when refresh the page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Enter the email on the email field and continue
2. Click on "Go Back"
3. Refresh the page

## Expected Result:
No 'Another login page is open' is displayed

## Actual Result:
'Another login page is open' briefly displayed

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/193d271a-bf6e-41f5-97a2-02c0deeada31

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by m-natarajan** [comment]
@miljakljajic FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by amyevans** [comment]
I confirmed that the bug is coming from https://github.com/Expensify/App/pull/40997 by commenting out this line locally:
https://github.com/Expensify/App/blob/21e69b3b81beb3fababfe3a921c4489d4881c576/src/libs/ActiveClientManager/index.ts#L62

I'll leave it to you @tgolen though to decide if it's better to revert the PR or just handle this bug as a follow up. Thanks!

**Comment by tgolen** [comment]
Thanks for the initial investigation! I don't think this needs to be a blocker.

**Comment by Skakruk** [comment]
@tgolen I guess, we can add a flag, that client is in progress of cleaning its ID from active clients list and return `true` for `isClientTheLeader` in this case.

**Comment by bondydaa** [comment]
@tgolen can you also make sure to remove the Web `DeployBlocker` as well (I guess we've started add 2 blocker labels)

**Comment by tgolen** [comment]
@Skakruk OK, that sounds like a good idea.

**Comment by Skakruk** [comment]
@tgolen should I create a new PR, following the whole flow?

**Comment by tgolen** [comment]
Yes, please.

**Comment by Skakruk** [comment]
@tgolen here is the PR https://github.com/Expensify/App/pull/42095

**Comment by miljakljajic** [comment]
Can we close?
