### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [Details Revamp] Update Policy Expense Report/Requests Name Display Logic

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42076]
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.47hdcwyvv08k

Held on https://github.com/Expensify/App/issues/42071

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Still held.

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I'm working on this issue. The PromotedActionsBar has been merged so as far as I know this should be unheld.

**Comment by trjExpensify** [comment]
Excellent!

**Comment by trjExpensify** [comment]
[Draft PR](https://github.com/Expensify/App/pull/43251) is up.

**Comment by ikevin127** [comment]
@trjExpensify @grgia I require payment as C+ reviewer of PR: https://github.com/Expensify/App/pull/43251#issuecomment-2177380414.

##

**Notes:**
1. The PR had some regressions, Georgia should be able to confirm this.
2. There are 2 other issues as part of this PR ([42074](https://github.com/Expensify/App/issues/42074), [42075](https://github.com/Expensify/App/issues/42075)) where the hold for payment was added as well.

**Comment by trjExpensify** [comment]
>The PR had some regressions, Georgia should be able to confirm this.

@grgia, can you confirm on the regressions so we can move to paying Kevin what's due here?

**Comment by ikevin127** [comment]
This PR covered multiple app flows and required extensive testing & back-n-forth with the PR author, design team and engineers (see https://github.com/Expensify/App/pull/43251).

Given this I propose a **$500 bounty** for reviewing this, minus regression penalty if we think that better testing on my part could've prevented all regressions.

##

🎉 Good work everyone, I think this PR was successful in terms of achieving the requirements while having a farely low regression count given the changes!

**Comment by ikevin127** [comment]
> **grgia**, can you confirm on the regressions so we can move to paying Kevin what's due here?

Bumped on Slack @ https://expensify.slack.com/archives/C01GTK53T8Q/p1720029343489579

##

I think it's safe to assume there was at least 1 regression here, not sure if more than 1 regressions would factor into the final payment amount. If that's true then we should wait for input, otherwise I think we can move forward with this given that we can't seem to be able to reach **grgia** on any channel.

**Comment by trjExpensify** [comment]
>I think it's safe to assume there was at least 1 regression here, not sure if more than 1 regressions would factor into the final payment amount.

Yeah, each regression counts ([guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#regressions)). That said, I'm happy to move on at $250 with this. 

Payment summary above has been updated, and I've sent an offer.

**Comment by ikevin127** [comment]
That's fine with me! Offer accepted, thank you!

**Comment by trjExpensify** [comment]
Paid, closing!
