### ISSUE TITLE
[HOLD for payment 2024-06-20][Details Revamp] Remove Delete Action from Collect Workspace Settings Pages

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42072]
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.pgcqougeeqsp

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz from Software Mansion, the expert agency, and I'll be working on this issue.

**Comment by lschurr** [comment]
Any update @cdOut?

**Comment by trjExpensify** [comment]
PR is merged!

**Comment by lschurr** [comment]
Payment summary for 6/20:

- Contributor: @cdOut (contractor - no payment)
- Contributor+: @hoangzinh $250 (to be paid via Upwork)

**Comment by lschurr** [comment]
[Offer sent in Upwork](https://www.upwork.com/nx/wm/offer/102801883) @hoangzinh :)

**Comment by lschurr** [comment]
All set.
