### ISSUE TITLE
[HOLD for payment 2024-06-13] [Details Revamp] Add Down Caret to Report Titles

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42073]
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.i3cbu3cyu5m5

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by kosmydel** [comment]
Hey, I'm Jakub from SWM. I will work on this.

**Comment by ikevin127** [comment]
@grgia Requested access to OP doc with kevin.bader96@gmail.com as I was requested to review the PR https://github.com/Expensify/App/pull/42154.

**Comment by kosmydel** [comment]
The PR solving this issue got merged today :)

**Comment by ikevin127** [comment]
> Skipping the payment summary for this issue since all the assignees are employees or vendors. If this is incorrect, please manually add the payment summary [SO](https://stackoverflowteams.com/c/expensify/questions/17778).

Incorrect, I require payment here as C+ reviewer of PR https://github.com/Expensify/App/pull/42154.

cc @twisterdotcom

**Comment by twisterdotcom** [comment]
Hello folks, sorry I've been having a bit of trouble with Upwork all day: 
<img width="738" alt="image" src="https://github.com/Expensify/App/assets/9133401/b825900f-1de2-4759-b069-2e8270e5fbab">

I will try to get this done tomorrow maybe from a different network.

**Comment by twisterdotcom** [comment]
https://www.upwork.com/nx/wm/offer/102732832
