### ISSUE TITLE
[HOLD for payment 2024-07-02] [Details Revamp] Update ReportDetailsPage for Rooms and Groups

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42074]
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.hexzxly74ri6

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz from Software Mansion, the expert agency, and I'd like to work on this issue.

**Comment by sonialiap** [comment]
@grgia what do we need here? Are you building this or do we we want to find a contributor to work on this?

**Comment by cdOut** [comment]
I am currently working on it, will put up a PR for it tomorrow.

**Comment by grgia** [comment]
@cdOut what PR is linked to this one?

**Comment by ikevin127** [comment]
@sonialiap @grgia I require payment as C+ reviewer of PR: https://github.com/Expensify/App/pull/43251#issuecomment-2177380414.

##

**Notes:**
1. The PR had some regressions, Georgia should be able to confirm this.
2. There are 2 other issues as part of this PR ([42075](https://github.com/Expensify/App/issues/42075), [42076](https://github.com/Expensify/App/issues/42076)) where the hold for payment was added as well.

**Comment by trjExpensify** [comment]
Let's consolidate to one issue to handle payment for the PR that took care of these issues. As the regression period is over, I'm closing this issue and centralising on the one I'm assigned to: https://github.com/Expensify/App/issues/42076
