### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] IOU - Password-protected PDF not handled correctly when added to IOU as recipient

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. FAB > Submit expense > Manual > add amount
2. Select workspace > add merchant > submit the expense
3. Go to IOU > add password-protected PDF as a recipient

## Expected Result:
During the expense submission process (FAB > Submit expense > add amount > choose workspace), when attempting to add a password-protected PDF, an error occurs stating "password-protected PDF is not supported." This error handling should also be applied when adding a password-protected PDF as the recipient in the IOU

## Actual Result:
Password-protected PDF added to IOU is not handled properly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ad042931-0493-4874-85d5-4388b68cfbeb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126fd5d796dca6c8e</li>
        <li>Upwork Job ID: 1793041772527243264</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by kevinksullivan** [comment]
Hmm I think because it is IOU related we'd make a low priority split item. @saracouto curious if you agree!

**Comment by Julesssss** [comment]
The draft PR is in progress

**Comment by Julesssss** [comment]
Not overdue

**Comment by Julesssss** [comment]
Hey @dannymcclain, we have a choice to make for this PR. We display two different UI views when the user uploads a password-protected PDF file (which we don't support). You can view them in greater detail [here](https://github.com/Expensify/App/pull/42572#issuecomment-2138207557), but this is what we are deciding between: 

**Center modal:** 
<img width="299" alt="Screenshot 2024-05-30 at 10 45 57" src="https://github.com/Expensify/App/assets/10736861/3af87734-53da-4fe9-9078-92f6b3e273e7">

**Bottom Modal:** 
<img width="303" alt="Screenshot 2024-05-30 at 10 45 52" src="https://github.com/Expensify/App/assets/10736861/971add44-fa90-4cfd-b831-2dd3bac640ab">

**Comment by dannymcclain** [comment]
I think the standard bottom modal/sheet/drawer is what we show when you try to upload a corrupted image/file, so I'd say let's go with that one instead of the system modal. Note that while this is a bottom modal/sheet/drawer on mobile, it would be a small centered modal on desktop.

**Comment by dannymcclain** [comment]
Ohhhhh, thanks for that @tienifr! In that case I think it makes the most sense to keep them on the upload page. It doesn't really make a whole lot of sense to me to take them back to the participant selector just because the file they chose can't be uploaded.

**Comment by Julesssss** [comment]
Ah thanks @tienifr.

**Comment by kevinksullivan** [comment]
@dukenv0307 what does this mean?

>Go to IOU > add password-protected PDF as a recipient

How would you add a PDF as a recipient?

**Comment by kevinksullivan** [comment]
Looks good @dukenv0307

**Comment by kevinksullivan** [comment]
all set on payments

**Comment by JmillsExpensify** [comment]
Re-opening for the payment summary.

**Comment by kevinksullivan** [comment]
Payment summary
- @tienifr $250 (NewDot)
- @dukenv0307 $250

**Comment by JmillsExpensify** [comment]
$250 approved for @tienifr
