### ISSUE TITLE
[$250] Chat - Self DM is automatically pinned and doesn't disappear in #focus mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42070]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40336
## Action Performed:
1. Open app
2. Log out
3. Log in with a new account
4. Go to setting page and switch to focus mode
5. Return to chat list

## Expected Result:
The self DM is not displayed

## Actual Result:
The self DM is automatically pinned, and is displayed in focus mode in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c1565812-33b6-4347-af2a-53d104cba0cb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f93577661d3c2dad</li>
        <li>Upwork Job ID: 1790310124806053888</li>
        <li>Last Price Increase: 2024-05-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment]
@laurenreidexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by abzokhattab** [comment]
should the self DM be unpinned?

**Comment by laurenreidexpensify** [comment]
@trjExpensify can you confirm?

**Comment by trjExpensify** [comment]
Yeah, the selfDM is intentionally pinned to the LHN upon account creation. Pinned chats show in the #focus mode LHN.
