### ISSUE TITLE
[HOLD for payment 2024-06-11] [Details Revamp] Update/Create PromotedActionsBar

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42071]
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.blbc2di8aqdp

- Add component to storybook

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by kosmydel** [comment]
Hey, I'm Jakub from SWM. I will work on this.

**Comment by dylanexpensify** [comment]
Fantastic! Thanks @kosmydel!

**Comment by dylanexpensify** [comment]
Ongoing! @kosmydel mind giving an ETA?

**Comment by kosmydel** [comment]
> Ongoing! @kosmydel mind giving an ETA?

This one got approval yesterday from both C+ and internal :) Today I made one minor adjustment. It is waiting for the merge freeze to end.

**Comment by dylanexpensify** [comment]
merge freeze ending for all but Auth!

**Comment by kosmydel** [comment]
The PR solving this issue got merged last week :)

**Comment by dylanexpensify** [comment]
coming up!

**Comment by dylanexpensify** [comment]
No payment needed

**Comment by rojiphil** [comment]
> No payment needed

@dylanexpensify Oh sorry. This just slipped out of my radar. 
I was C+ here and here is the [reference](https://github.com/Expensify/App/pull/41972#issuecomment-2111562588) to the reviewer checklist. This is due payment to me.

**Comment by dylanexpensify** [comment]
Ah @rojiphil, thanks for ping, please apply [here](https://www.upwork.com/jobs/~012510080d70234c53)!

**Comment by rojiphil** [comment]
> Ah @rojiphil, thanks for ping, please apply [here](https://www.upwork.com/jobs/~012510080d70234c53)!

Thanks @dylanexpensify. Applied to the upwork job.

**Comment by dylanexpensify** [comment]
Done! Thanks @rojiphil!
