### ISSUE TITLE
[$250] [HOLD for payment 2024-06-13] [Details Revamp] Update ProfilePage

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42077]
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.k681an84656p

Held on https://github.com/Expensify/App/issues/42071

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01621b7ae67842d92a</li>
        <li>Upwork Job ID: 1801131122718918182</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by kosmydel** [comment]
Hey, I'm from SWM and I will work on this.

**Comment by kosmydel** [comment]
The PR is actively in review. The code was accepted, and we are waiting for a review from the design team.

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor+: $250 @akinwale 

Upwork job is [here](https://www.upwork.com/jobs/~01621b7ae67842d92a).

**Comment by akinwale** [comment]
@kadiealexander Upwork offer accepted. Thanks!

**Comment by kadiealexander** [comment]
@grgia could you please share the regression test steps mentioned [here](https://github.com/Expensify/App/issues/42077#issuecomment-2152296272)?

**Comment by grgia** [comment]
@JmillsExpensify do you have regression steps written out somewhere already for this project?

**Comment by grgia** [comment]
bump @JmillsExpensify

**Comment by grgia** [comment]
Waiting on confirmation of regression steps from @JmillsExpensify

**Comment by grgia** [comment]
not overdue

**Comment by grgia** [comment]
I'm actually going to close this one as complete, since this is part of the details revamp project, the regression steps will be covered by the manual tests. cc @JmillsExpensify do you have a link to the manual tests for the doc?
