### ISSUE TITLE
[HOLD for payment 2024-07-17] [Details Revamp] Remove the Three Dot Menu on Affected Reports

### ISSUE THREAD

**Issue by grgia** [Expensify/App#42080]
https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit#bookmark=id.qn5rgvv8le7q

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by adelekennedy** [comment]
still on hold

**Comment by adelekennedy** [comment]
@grgia @dannymcclain I assume we're still holding here?

**Comment by dannymcclain** [comment]
I think that's right. @grgia can confirm!

**Comment by grgia** [comment]
@cdOut

**Comment by cdOut** [comment]
This is the final issue and will be on hold until we get [this PR](https://github.com/Expensify/App/pull/43251#issuecomment-2162665131) merged.

**Comment by adelekennedy** [comment]
Still waiting for the linked PR to be merged

**Comment by trjExpensify** [comment]
Can we remove the hold here?

**Comment by grgia** [comment]
Yep done, @trjExpensify

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor+: $250 @parasharrajat (NewDot)

**Comment by adelekennedy** [comment]
@parasharrajat I think the only additional step is the checklist and then we can close this one out?

**Comment by adelekennedy** [comment]
@grgia for your thoughts on the above but that makes sense to me!

**Comment by adelekennedy** [comment]
https://github.com/Expensify/Expensify/issues/415258

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
