### ISSUE TITLE
Room shows up in the LHN when someone posts new message after leaving the room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715285568339749

## Action Performed:
1. Leave a public room https://staging.new.expensify.com/r/868417741568295 as user A
2. Have someone posts a new message in the room
## Expected Result:
Room should not show in the LHN for user A
## Actual Result:
Rooms shows up when new message is posted 
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Snip - (3) New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/38435837/ce20bce4-066d-4a10-8245-20b63fb02350)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Nice! Will work to repro today

**Comment by dylanexpensify** [comment]
couldn't repro
