### ISSUE TITLE
[HOLD for payment 2024-06-05] [UX Reliability] [$250] Expense - LHN shows blank row when opening transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42096]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com, go offline
2. Submit two expenses to a user with no chat history
3. Click on the IOU preview in the main chat
4. Click on the first expense

## Expected Result:
LHN will display the transaction thread of the first expense

## Actual Result:
LHN displays a blank row for the transaction thread of the first expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1821da92-4517-4a6a-87ec-c91852058201

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a437d649825676f1</li>
        <li>Upwork Job ID: 1790367877808570368</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by thienlnam** [comment]
I can still reproduce with #40336 so it isn't that one either

**Comment by Beamanator** [comment]
I believe this can be external, since this pretty much is only happening when offline 🤔

**Comment by Beamanator** [comment]
@ishpaul777 can you please explain why you think so? :D :pray

**Comment by thienlnam** [comment]
Removing the blocker for this reasoning 
1. It only happens if you try to create multiple submits and open one offline, but doesn’t actually prevent you from doing anything
2. The reduction in memory is a more important PR

That being said, we should aim to fix this soon but not a blocker since it's a specific offline flow

**Comment by hurali97** [comment]
I will take a look at this issue tomorrow, thanks for flagging this 👍

**Comment by hurali97** [comment]
@thienlnam  I have created a draft PR with the fix [here](https://github.com/Expensify/App/pull/42276). Change is minimal, keeping the benefits from previous PR and fix this issue as well 👍 

<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/47336142/ce2cbd10-ce79-468b-a2bc-112bb554bf14

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/47336142/2cdf39df-0a8b-4c03-ab45-c796ad45c9c6


</details>

**Comment by hurali97** [comment]
@thienlnam  I have created a draft PR with the fix [here](https://github.com/Expensify/App/pull/42276). Change is minimal, keeping the benefits from previous PR and fix this issue as well 👍 

<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/47336142/ce2cbd10-ce79-468b-a2bc-112bb554bf14

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/47336142/2cdf39df-0a8b-4c03-ab45-c796ad45c9c6


</details>

**Comment by thienlnam** [comment]
Great thanks, @DylanDylann since this is from the previous PR you reviewed, can you take a look at this new fix as well? https://github.com/Expensify/App/pull/42276

**Comment by mountiny** [comment]
I believe this will be $250 to @DylanDylann as the only payment on this issue

**Comment by twisterdotcom** [comment]
Offer sent. Will pay out on Wednesday.
