### ISSUE TITLE
Remove "using Expensify" and "elsewhere" from the end of payment message subject lines in New Expensify

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#42108]
Right now, when you pay someone via New Expensify, you get a message like this where the subject line says "using Expensify" at the end: 

<img width="617" alt="image" src="https://github.com/Expensify/Expensify/assets/22160301/40931340-0301-46b3-9c08-3e996f292412">

There's a second scenario (which I don't have available) where the subject line says "elsewhere" at the end (if you paid them outside of New Expensify). 

Coming from [this conversation](https://expensify.slack.com/archives/C05RECHFBEW/p1715374708393469), we'd like to remove both of those phrases completely from the end of the subject lines to simplify things. It looks like at least some of the code is [here](https://github.com/Expensify/Web-Expensify/blob/7fde6fe72a8e2c87d3889751897c31f34eedd81d/lib/ReportUtils.php#L2458). 

Let me know if you need anything else!

cc @yuwenmemon

**Comment by jamesdeanexpensify** [comment]
@quinthar to confirm - are you ok removing both cases as mentioned above? They'll still be able to click into the body of the message to see how/where it was paid (see screenshot above).

**Comment by carlosmiceli** [comment]
Thinking about it a bit more, removing both from the subject but also implementing @quinthar's suggestion in the body of the message feels like the best of both worlds.

**Comment by carlosmiceli** [comment]
On second thought, if the button says "pay elsewhere", we should probably stick to that wording for consistency, right?

**Comment by carlosmiceli** [comment]
This kept getting pushed but is finally priority first thing on Monday 🙏

**Comment by carlosmiceli** [comment]
This has been merged into production already.
