### ISSUE TITLE
[$250] "user isn't a member of this room " message when mentioning the user in their workspace chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715594393314809

## Action Performed:

1. Create a workspace in NewDot as User A
2. Invite User B to the workspace
3. Navigate to User B’s workspace chat
4. @ mention the user

## Expected Result:
Concierge shouldn’t offer to invite them because they’re already in the room
## Actual Result:
Concierge says they aren’t in the room and asks if I want to invite them
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-05-13 at 11 00 59 AM](https://github.com/Expensify/App/assets/38435837/b34d2fbf-9e9a-4b1d-9a02-960d7ffe75a2)

![Snip - (41) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/8950a912-0920-4a26-9259-4e008ce7610a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121f0d4e844b26e4e</li>
        <li>Upwork Job ID: 1790143101529964544</li>
        <li>Last Price Increase: 2024-05-20</li>
    </ul>
</details>

**Comment by getusha** [comment]
@lschurr lets add internal label to get 👀 from an internal engineer.

**Comment by lschurr** [comment]
I've added Internal per this comment: https://github.com/Expensify/App/issues/42101#issuecomment-2109691611

**Comment by lschurr** [comment]
No update here. Will post in the Slack room this week.

**Comment by lschurr** [comment]
Bumped the original Slack thread.

**Comment by lschurr** [comment]
Not overdue - @rlinoz just picked this up.
