### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Video previews aren't showing in Chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42111]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** No
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zsgreenwald 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715628266876699

## Action Performed:
1. Log into [new.expensify.com](http://new.expensify.com/) in an incognito window using a new test account
2. Join this public room - https://new.expensify.com/r/6879144773653084
3. Scroll up to any of the videos posted above, and confirm 

 ## Expected Result:
Video preview is showing

## Actual Result:
No video preview is showing
Console log : ReportActionItemParentAction.tsx:89 Refused to connect to 'https://staging.expensify.com/chat-attachments/4636818444356617466/w_af6e0c71ddb0b6f594b3c410b2e20eb74235b764.jpg' because it violates the document's Content Security Policy.
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![image (2)](https://github.com/Expensify/App/assets/38435837/281c0c49-b1f5-44a7-8b01-dd40cd6819b7)

https://github.com/Expensify/App/assets/38435837/2257eaf8-de24-49f0-b14c-96a1034f6547

![Snip - New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/38435837/d07763f2-b5fd-45d4-8053-8d06e3d05a1a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f0c3af56df70306</li>
        <li>Upwork Job ID: 1791541183992836096</li>
        <li>Last Price Increase: 2024-05-17</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 102436262</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment]
On my testing list, I'll review soon.

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

@slafortune - I need help here to ensure that we get proposals and they are reviewed. I'm trying to avoid this one going stale. Thanks!

**Comment by situchan** [comment]
From my testing, video preview shows on staging (https://staging.new.expensify.com/) but not on prod (https://new.expensify.com/).
@dominictb do you experience the same?

**Comment by situchan** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/42111#issuecomment-2118834009) looks good to me.
🎀👀🎀 C+ reviewed

**Comment by slafortune** [comment]
@alexpensify I will be out until June 4th, but with you being back on the 28th, this BZ report is in a good spot with a proposal accepted, I'm just going to unassign myself.

**Comment by alexpensify** [comment]
Thanks @slafortune! It looks like we are moving forward here.

**Comment by alexpensify** [comment]
Ok, all set here in Upwork and I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment]
Payouts due: 2024-06-06

- [ ] Contributor: $250 @dominictb - Waiting for you to approve the offer in Upwork 
- [ ] Contributor+: $250 @situchan - Paid via Upwork 

Upwork job is [here](https://www.upwork.com/jobs/~016f0c3af56df70306).

Note: The automation is wrong here: https://github.com/Expensify/App/issues/42111#issuecomment-2140882713

**Comment by alexpensify** [comment]
I checked again, and we are still waiting for @dominictb to accept the proposal in Upwork. Setting a reminder to check on Monday.

**Comment by alexpensify** [comment]
Awesome, thanks. Closing, I've completed the payment process in Upwork.
