### ISSUE TITLE
[HOLD for payment 2024-06-06] Tax - Delete tag option is shown in the dropdown when selecting tag via checkbox

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42113]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/App/pull/41552

## Action Performed:
Precondition:
- Multi tags are uploaded to the workspace (attached below).
1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Tags.
4. Click on any tag
5. Click on any subtag.
6. Note that delete option is hidden.
7. Return to previous page.
8. Select a tag via checkbox.
9. Click three-dot menu.

## Expected Result:
There will be no Delete tag option.

## Actual Result:
Delete tag option is shown in the dropdown when selecting tag via checkbox.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d03a53c4-a37d-4160-b1c3-71baa840e93d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by jasperhuangg** [comment]
This is a front-end regression that is a result of bad tests in https://github.com/Expensify/App/pull/41552

**Comment by jasperhuangg** [comment]
@gijoe0295 Please do, I can review, let me know when it's ready, sorry for the confusion!

**Comment by jasperhuangg** [comment]
I don't think this necessarily needs to be a blocker because multi-level tags aren't even supported on production yet. The contributor who raised the offending PR is pushing a fix in the meantime.
