### ISSUE TITLE
[$500]  Workspaces - Created Collect or Control workspace in OD not displayed in ND

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42122]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4554147&group_by=cases:section_id&group_order=asc&group_id=229069
**Email or phone of affected tester (no customers):** applausetester+omq184@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.expensify.com/

2. Sign Up with a new Expensifail account
3. Navigate to Setings > Workspaces > Group
4. Create a new Collect or Control workspace
5. Navigate to https://staging.new.expensify.com/
6. Sign In with the same Expensifail account from step 2
7. Navigate on Account Settings (Account profile on bottom right)
8. Click on "Workspaces"
9. Sign Out and Sign In back
10. Navigate on Account Settings > Workspaces
11. Reload the page

## Expected Result:
Created workspace in OD should be displayed on Workspaces listing page in ND

## Actual Result:
Created workspace in OD not displayed on Workspaces listing page in ND

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5aa7adac-310c-4758-a55a-437c481f04fd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a59432e27ad9ab4</li>
        <li>Upwork Job ID: 1795667646416199680</li>
        <li>Last Price Increase: 2024-06-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
@lanitochka17 sorry can you explain to me what the bug is? Here are 2 screenshots from your video.

This is Step 8:

![image](https://github.com/Expensify/App/assets/30815269/34439625-7b20-4c8e-ad5c-8feb89122358)

This is Step 10:

![image](https://github.com/Expensify/App/assets/30815269/0be97f8d-7d9d-47db-ad24-7cf632712209)

They look identical to me?

**Comment by lanitochka17** [comment]
@jliexpensify The tester creates a workspace in OldDot, but in NewDot this workspace is not displayed in the same account.

**Comment by jliexpensify** [comment]
@lanitochka17 got it, but from my screenshots - there doesn't appear to be a Workspace in either (both show `Create a Workspace`)? Can you share screenshots and an explanation of what you're referring to?

**Comment by jliexpensify** [comment]
Going to close this, I can't repro and can't see any issues between the screenshots.

**Comment by jliexpensify** [comment]
Re-opening as I can now repro this.

**Comment by jliexpensify** [comment]
Going to increase the price.

**Comment by jliexpensify** [comment]
Not overdue, waiting on proposals

**Comment by jliexpensify** [comment]
Going to close this one out since we have no proposals - I've tested on a non-Expensifail account and it's working fine. Expenifail is an internal testing account so...it's not really going to affect anyone but internal testers.
