### ISSUE TITLE
[HOLD for payment 2024-06-28] Participants Migration Front End Polish

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#42121]
Had some more comments for @s77rt to address and we agreed to do in a follow up issue.

https://github.com/Expensify/App/pull/40254#pullrequestreview-2053852168

**Comment by s77rt** [comment]
[PR](https://github.com/Expensify/App/pull/43610)

**Comment by sonialiap** [comment]
Payment summary:
- @s77rt reviewer $250 - please request in ND

**Comment by sonialiap** [comment]
Noted :) offer sent in upwork ([link](https://www.upwork.com/nx/wm/offer/102945899))

**Comment by s77rt** [comment]
@sonialiap Accepted! Thank you!

**Comment by sonialiap** [comment]
Paid ✔️
