### ISSUE TITLE
Hold expense - "hold" label next to dot separator in expense report (p2p) is not capitalised

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42137]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM.
3. Create two expenses (if there is no other expense).
4. Hold one of the expenses.
5. Go to expense report.
6. Note that "hold" next to dot separator is not capitalised.
7. Submit two expenses to workspace chat.
8. Hold one of the expenses.
9. Go to expense report.
10. Note that "hold" next to dot separator is capitalised.

## Expected Result:
In Step 6, "hold" label next to dot separator in expense report (p2p) should be capitalised.

## Actual Result:
In Step 6, "hold" label next to dot separator in expense report (p2p) is not capitalised.
This is inconsistent with the expense report in workspace chat (Step 10).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d00b674e-8097-446a-81bc-809d7bf0f37e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by slafortune** [comment]
Not sure this is something to focus on right now, but I was not able to reproduce either.

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.76-2

https://github.com/Expensify/App/assets/78819774/79a5fe98-423a-4b53-8dab-179bdb9ac81c

**Comment by slafortune** [comment]
Ah!  Yep, I see it. This is still not something big enough to focus our attention on at this point.
