### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] Hold request - "Missing merchant" appears in the held expense preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42138]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM.
3. Submit two expenses without merchant (if there is no unsettled expenses).
4. Go to transaction thread of one of the expenses.
5. Go to 3-dot menu > Hold expense > Enter reason > Save.
6. Return to expense report.

## Expected Result:
There will be no "Missing merchant" in the preview of held expense because merchant is not a requirement in p2p expense.

## Actual Result:
"Missing merchant" appears in the preview of held expense when merchant is not a requirement in p2p expense.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c70d8d20-980b-47e2-b814-ae7053676c66

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01572bf249279344c7</li>
        <li>Upwork Job ID: 1803020390914982970</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102939738</li>
<li>allgandalf | Contributor | 102939740</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by miljakljajic** [comment]
This is expected behaviour - under "submit" for a collect workspace, we'd require a merchant.

**Comment by lanitochka17** [comment]
Issue is still reproducible 

![IMG_0487](https://github.com/Expensify/App/assets/78819774/e5e138d6-0664-4aca-9f7a-c6dfa3e0d1c2)

None of the steps had anything to do with a workspace. This happens in a 1:1 chat.

**Comment by tJonPope727** [comment]
Hi, Everyone.
I can help you with this project.
please contact me in skype.
live:.cid.338ac9dd67d9a167
Thanks

**Comment by miljakljajic** [comment]
@nkuoch @shubham1206agra are we moving forward with @allgandalf's proposal or reviewing further proposals?

**Comment by dannymcclain** [comment]
>@Expensify/design I am not sure about it here. Should we show RBR next to the expense that is put on hold?

I am pretty sure held expenses always get an RBR. @JmillsExpensify or @trjExpensify, can you confirm?

**Comment by trjExpensify** [comment]
Yeah, we RBR a held expense on and off workspace. The bug here is showing `Missing merchant` on an off-workspace expense within a DM. Adding a `Merchant` isn't required for P2P expenses, so we shouldn't be showing that message in the expense preview component.

**Comment by miljakljajic** [comment]
How is this one doing? @allgandalf

**Comment by miljakljajic** [comment]
@shubham1206agra please accept the offer in order to be paid on the deadline

**Comment by miljakljajic** [comment]
both contributors paid - closing out!
