### ISSUE TITLE
[UX Reliability] HIGH: Investigate and fix using multiple `GetMissingOnyxMessages` and `ReconnectApp` calls to load all Onyx data 

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#42136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
e.g. memory consumption, storage read/write times, React native bridge concerns, inefficient React component rendering, etc.

When you haven't visited a chat for a while, we run `GetMissingOnyxMessages` (twice) then `ReconnectApp` twice. We are loading all Onyx data multiple times before showing it to the end user.   

When you have not used the app in a while (I just switched from staging to prod and had not used prod in a while)  this happens:

1. We call one API command, which returns Your session has expired. Please sign in again (makes sense since I have not used it in a while)
2. We call Authenticate
3. We call UpdateAutomaticTimezone (I assume since I am on a different timezone than list time)
4. It detects I have lots of missing onyx messages and calls GetMissingOnyxMessages this internally triggers a full load, since we don't have that many onyx messages saved
5. (this is the problem I think) It calls ReconnectApp which returns again the same full response as the previous call)

## What is the impact of this on end-users?
List specific user experiences that will be improved by solving this problem e.g. app boot time, time to for some interaction to complete, etc.

This series of operations creates additional work for the client, when all the end user wants is for the app to: 

- Load all messages efficiently 
- Render them

Whereas right now the additional "loading" operations mean that there is a delay to these events taking place. 

## List any benchmarks that show the severity of the issue
Please also provide exact steps taken to collect metrics above if any so we can independently verify the results.

I've started a discussion in #newdot-quality [here](https://expensify.slack.com/archives/C05LX9D6E07/p1715611536548199)

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

We need to investigate why there are these redundant `ReconnectApp` and `GetMissingOnyxMessages` calls, and make sure that we can load all missing data in one performant call. 

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:** v1.4.73-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1715611536548199

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by MitchExpensify** [comment]
@muttmuure is there an SO for how to process these from a BZ standpoint? I'm not seeing one 👀

**Comment by muttmuure** [comment]
There's actually already an issue for this: https://github.com/Expensify/App/issues/40995 

Apologies - closing

**Comment by muttmuure** [comment]
@gedu since you fixed ReconnectApp in that issue I linked above, could you investigate this one and tidy up these redundant ReconnectApp calls when you've not visited the site in a while?

**Comment by MitchExpensify** [comment]
Friendly bump on the above @gedu

**Comment by gedu** [comment]
> @gedu since you fixed ReconnectApp in that issue I linked above, could you investigate this one and tidy up these redundant ReconnectApp calls when you've not visited the site in a while?

Sorry, it seems I missed this message, yes, I can take a look, @muttmuure do you have any reproduction steps? what does "not visited in a while" mean? (how long)

**Comment by gedu** [comment]
I think I could reproduce it, seems that it keeps to make some requests, and because it isn't connected to internet, it enqueues the requests and when you get back online it starts sending them.

Looking into it, but could be Pusher, it tries to connect to some channel and it has a callback that it is reconnect `onPusherResubscribeToPrivateUserChannel` trying to confirm this and think on a solution

<img width="906" alt="Screenshot 2024-05-28 at 09 00 15" src="https://github.com/Expensify/App/assets/1676818/465e9232-cd92-4305-8357-d6f0eb6886b5">

**Comment by gedu** [comment]
It is getting hard to reproduce it, I'm trying different ways to reproduce it. Would be really helpful if someone can help me on getting some steps, so if I find the fix I can make sure it is solved. 
Can we move it to weekly?

**Comment by MitchExpensify** [comment]
> @muttmuure do you have any reproduction steps?

Any help here is appreciated, @muttmuure 🙇

**Comment by gedu** [comment]
No news here, trying to reproduce, I think the bugs is related with SequenceQueue process not running. NetInfo is trying to reconnect when it "detects" there is an internet connection so is trying to do fetch ReconnectApp with Policies but the request never fired, so it get into the queue

**Comment by MitchExpensify** [comment]
I'm a little lost on this one @muttmuure, do you have any recs on how to move it along?

**Comment by gedu** [comment]
I'm looking into other Critical bugs, I will keep trying to look into this soon

**Comment by gedu** [comment]
Seems to come from this commit: https://github.com/Expensify/App/commit/cd7ba79935aed99bfbf998e0567bbf8cfa1a868f

and PR: https://github.com/Expensify/App/pull/32548

so we have to use `.website` or make the changes I mention

**Comment by MitchExpensify** [comment]
Just to be sure, do you have a proposal for a fix @gedu ?

**Comment by gedu** [comment]
Sorry my previous comment was for another issues, I'm looking into 2 critical ones, and as soon as I finish them I will keep looking here. Is this still a thing? is still happening?

**Comment by MitchExpensify** [comment]
@muttmuure, Sorry, I'm a bit lost on this one. Do we still need this fixed?

**Comment by muttmuure** [comment]
Damn I keep missing this. I think this is resolved

**Comment by muttmuure** [comment]
Sorry!

**Comment by MitchExpensify** [comment]
hah no worries, I'll close based on that!
