### ISSUE TITLE
[$250] Expense that has been approved and paid says “Only visible to you”

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42169]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715703163807979

## Action Performed:
1. Submit a scanned receipt expense report to approver through iOS app
2. As approver approve and pay the submitted expense
3. Open the report as employee and observe the preview
## Expected Result:
Only visible you should disappear since the report is approved and paid

## Actual Result:
“Only visible to you” displayed as if it was still scanning.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/eaf1a1e7-a3b9-4c64-a177-ffd84f582ba8

[logs-2024-05-14_16_01_00.537-2024-05-14 16_12_54.331.txt](https://github.com/Expensify/App/files/15313261/logs-2024-05-14_16_01_00.537-2024-05-14.16_12_54.331.txt)

<img src="https://github.com/Expensify/App/assets/38435837/6587aada-1d8f-40ea-894f-b3fc5b9c5d25" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5ffb37c2677a636</li>
        <li>Upwork Job ID: 1791214432620130304</li>
        <li>Last Price Increase: 2024-06-06</li>
    </ul>
</details>

**Comment by sakluger** [comment]
@slafortune I'll be OOO through May 31, can you please manage this issue until then? Thanks!

**Comment by slafortune** [comment]
I will be on Vacation until June 4th, so adding another BZ until @sakluger is back 👍

**Comment by CortneyOfstad** [comment]
Not overdue as we're still waiting for proposals!

**Comment by CortneyOfstad** [comment]
@sakluger I see you're back so sending it back your way! Thanks!

**Comment by sakluger** [comment]
@dukenv0307 any ideas why we haven't gotten any proposals yet on this one? Is it hard to reproduce?

**Comment by sakluger** [comment]
No volunteers yet.

**Comment by sakluger** [comment]
No update

**Comment by trjExpensify** [comment]
I _think_ this one should go away with removing whispers on scanning receipts. @youssef-lr's backend PR for that was reverted today, but when we have a new PR up, let's link it here and then retest thereafter.

**Comment by sakluger** [comment]
@trjExpensify is there a new PR yet for removing whispers on scanning receipts?

**Comment by trjExpensify** [comment]
Yep: https://github.com/Expensify/Auth/pull/11354

**Comment by trjExpensify** [comment]
So we good here?

**Comment by sakluger** [comment]
Yep, we're good.
