### ISSUE TITLE
App crashes after pressing R in metro bundler on iOS simulator

### ISSUE THREAD

**Issue by adamgrzybowski** [Expensify/App#42160]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-4
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @adamgrzybowski 
**Slack conversation:**

## Action Performed:
This crash only affects developers

- Run the app on the iOS with metro running
- Press R in the metro console to reload
 
## Expected Result:
App reloads

## Actual Result:
App crashes

## Workaround:
Don't reload the app 🤷 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/67908363/1a309f89-c244-4142-8155-a9d9cfc07c41

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adamgrzybowski** [comment]
@WoLewicki is going to fix that

**Comment by joekaufmanexpensify** [comment]
Is the next step here to raise a PR?

**Comment by joekaufmanexpensify** [comment]
@WoLewicki @adamgrzybowski mind confirming if there is an ETA for a PR here?

**Comment by WoLewicki** [comment]
I'll try to get it ready today 🚀

**Comment by mananjadhav** [comment]
@mountiny @joekaufmanexpensify Does this need C+ review?

**Comment by WoLewicki** [comment]
Here is the PR: https://github.com/Expensify/App/pull/42343. Here is also a PR to markdown repository: https://github.com/Expensify/react-native-live-markdown/pull/349.

**Comment by joekaufmanexpensify** [comment]
>@mountiny @joekaufmanexpensify Does this need C+ review?

I am not sure. Going to defer to Vit on this

**Comment by joekaufmanexpensify** [comment]
PR is in review. @mountiny I assume this needs C+ review, but interested if you agree before Manan goes ahead?

**Comment by mountiny** [comment]
I am not sure if we need to merge the patch, but instead we can wait for the fix from the https://github.com/Expensify/react-native-live-markdown/pull/349 imho

**Comment by mananjadhav** [comment]
Agreed makes sense. I am assuming it's not blocking anyone. It'll only slow done the dev and we can get the PR merged asap.

**Comment by WoLewicki** [comment]
I think we can close this one since the changes are already on main and working (see https://github.com/Expensify/App/pull/42343#issuecomment-2136586671)

**Comment by mountiny** [comment]
Ok perfect, thanks!
