### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] [Search v1] Remove multiple API calls and clean up const

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#42177]
## Problem
Clean up items from [this PR](https://github.com/Expensify/App/pull/41769)

- [Remove multiple API calls made when changing policyID filter](https://github.com/Expensify/App/pull/41769#pullrequestreview-2050573677)
- [Clean up const value](https://github.com/Expensify/App/pull/41769#discussion_r1595881133)

cc @WojtekBoman 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014700a68531e38ed9</li>
        <li>Upwork Job ID: 1790511609139613696</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by mallenexpensify** [comment]
> Clean up items from https://github.com/Expensify/App/pull/41769
@luacmartins , I'm assuming this is a new job and @ahmedGaber93 should be compensated $250 as C+, let me know if that's not accurate. Thx

**Comment by ahmedGaber93** [comment]
**BugZero Checklist**: The PR adding this new feature has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@ahmedGaber93] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

Regression Test Proposal

1. Open the app
2. Go to Search tab from the bottom tab
3. Open the browser DevTools on Network monitor.
3. Click on switch-workspace button and switch current workspace
4. Verify that the `/Search` request is sent only once


https://github.com/Expensify/App/assets/41129870/10c4bb89-26a0-4998-bfca-fcde56378bc1



Do we agree 👍 or 👎

**Comment by mallenexpensify** [comment]
@ahmedGaber93 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~014700a68531e38ed9

Thx for the test steps, added below
- https://github.com/Expensify/Expensify/issues/404097

**Comment by ahmedGaber93** [comment]
@mallenexpensify Offer accepted, thanks!

**Comment by ahmedGaber93** [comment]
@mallenexpensify bump for payment.

**Comment by mallenexpensify** [comment]
Contributor+: @ahmedGaber93 paid $250 via Upwork. 

Thx!
