### ISSUE TITLE
Undefined auto-approval violation showing up under receipt

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715262867366499

## Action Performed:
Prerequisite: In olddot configure auto approval limit for a policy
1. As an employee submit an expense above the auto-approval limit on the policy
2. As approver open the report (Might take few minutes to see the error)

## Expected Result:
The violation correctly states what the auto-approval limit is. This violation should also appear in the amount field.

## Actual Result:
The violation incorrectly states an undefined auto-approval limit. The violation is showing under the receipt.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-05-09 at 05 47 23@2x](https://github.com/Expensify/App/assets/38435837/411300ec-0cce-4e1c-86e1-1f8d0ad2f4b3)

![Exceeds auto approval](https://github.com/Expensify/App/assets/38435837/ebbce1f5-59fa-43a3-9022-7b5cfb1d0a42)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment]
Thanks for flagging this as a dupe! I'm going to close this issue in favor of keeping the other one open.
