### ISSUE TITLE
Workspace switcher - Workspace icon is displayed when Expensify filter is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- There is at least 1 workspace
1. Go to staging.new.expensify.com
2. Open workspace switcher
3. Select a workspace
4. Open workspace switcher again
5. Select Expensify

## Expected Result:
Expensify logo will display next to the breadcrumbs

## Actual Result:
A workspace icon is displayed next to the breadcrumbs after switching from workspace back to Expensify

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/50f1b31f-b4f8-47c5-bea3-6a4646595919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@iwiznia  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Workspace icon is displayed when Expensify filter is selected
### What is the root cause of that problem?
We are passing an empty string here. It should be undefined.
https://github.com/Expensify/App/blob/1ee5d03fc9c7530b2e1729a1a6feb8172115d1cf/src/pages/WorkspaceSwitcherPage/index.tsx#L148
### What changes do you think we should make in order to solve the problem?

We can remove PolicyID from here or set it to undefined.

**Comment by iwiznia** [comment]
I think the bug is coming from https://github.com/Expensify/App/pull/41769 testing that theory now

**Comment by iwiznia** [comment]
Nope

**Comment by iwiznia** [comment]
ok @Nodebrute your fix works. I think we need to change this https://github.com/Expensify/App/blob/6dfa9425c74986da3248e6b67b5ded79bf45989c/src/pages/WorkspaceSwitcherPage/index.tsx#L26 to `policyID?` too. 
Though I am a bit confused on what PR caused this though...

**Comment by Nodebrute** [comment]
@iwiznia 

> ok @Nodebrute your fix works. I think we need to change this
> 
> https://github.com/Expensify/App/blob/6dfa9425c74986da3248e6b67b5ded79bf45989c/src/pages/WorkspaceSwitcherPage/index.tsx#L26
> 
> to `policyID?` too.
> Correct.

**Comment by Nodebrute** [comment]
@iwiznia I also struggle to find it, but I believe this is the correct RCA. This bug has always been present, but it's only now coming to light due to some recent PR. The workspace switcher policyID should always be undefined.

**Comment by Nodebrute** [comment]
@iwiznia Could you assign me to work on the fix?"

**Comment by iwiznia** [comment]
Yep, assigned you, thanks!

**Comment by iwiznia** [comment]
That's correct, thanks @GandalfGwaihir!

**Comment by Nodebrute** [comment]
@iwiznia https://github.com/Expensify/App/pull/42223 You can merge this PR in case you decide to go with this fix.

**Comment by iwiznia** [comment]
This is working now, just tested on staging
