### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Web - Accounting - Xero - Console error shows up when opening Preferred exporter

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42195]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #41641
**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace is connected to Xero.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Accounting.
4. Go to Export.
5. Click Preferred exporter.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

[Bug6481656_1715779259909!staging.new.expensify.com-1715778677003.txt](https://github.com/Expensify/App/files/15322264/Bug6481656_1715779259909.staging.new.expensify.com-1715778677003.txt)

https://github.com/Expensify/App/assets/38435837/d4b7676f-f9c2-4173-b7ca-1ddd29cb3ca6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f939b9bc571e795d</li>
        <li>Upwork Job ID: 1791257784808251392</li>
        <li>Last Price Increase: 2024-05-17</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by Beamanator** [comment]
@twisterdotcom this can probably be external, but it's probably a super quick fix from whoever is working on Xero stuff (@hayata-suenaga or @lakchote maybe?)

**Comment by twisterdotcom** [comment]
Agree, we should assign whoever worked on this last. Will wait for @hayata-suenaga and @lakchote to chime in.

**Comment by hayata-suenaga** [comment]
@lakchote, might be related around [this line](https://github.com/Expensify/App/blob/f16005f751cf4b3481036cf326050fac88ccddc7/src/pages/workspace/accounting/xero/export/XeroExportConfigurationPage.tsx#L38) where we navigate to the preferred exporter page?

**Comment by twisterdotcom** [comment]
Okay, we can make it external.

**Comment by lakchote** [comment]
I do agree with @Beamanator, we've probably could have waited I woke up to handle this, as the fix is really simple and it's just a console error 😅

Anyway let's wait for @ahmedGaber93 review of @tienifr's proposal, but it looks good to me.

**Comment by ahmedGaber93** [comment]
@tienifr Thanks for the proposal.

I agree with @lakchote. @tienifr's [proposal](https://github.com/Expensify/App/issues/42195#issuecomment-2116966023) looks good, the react-navigation read the route path that starting with `/` as `absolute URL` not relative URL which cause error is the browser history and URL.

![Screenshot 2024-05-17 at 2 11 38 PM](https://github.com/Expensify/App/assets/41129870/337727a6-9795-4541-a65f-057122aa0837)

🎀 👀 🎀 C+ reviewed

**Comment by lakchote** [comment]
@tienifr's proposal LGTM

**Comment by ahmedGaber93** [comment]
@tienifr please let me know when PR is ready.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @ahmedGaber93 paid $250 [here](https://www.upwork.com/nx/wm/workroom/37328239/overview) (Reviewer)
- @tienifr paid $250 [here](https://www.upwork.com/nx/wm/workroom/37297859/overview) (Contributor)

I don't think we need a test case for a console error here.
