### ISSUE TITLE
Book Travel - Book Travel - Links lead to 404 error page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42203]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the New Expensify App
2. Sign into a valid account (That will show Book Travel option in the FAB menu)
3. Click on Book Travel > Book Travel Again in the popup modal
4. Click on the Terms & Cond Button on the top or bottom

## Expected Result:
User expects the Terms page to open and load

## Actual Result:
User is taken to a 404 error page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d8b0af2f-1e5e-4142-96b5-c86f9b5d89ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kadiealexander** [comment]
I think this is expected because we haven't deployed the T&Cs yet, checking [here](https://expensify.slack.com/archives/C05S5EV2JTX/p1715826951691429?thread_ts=1714656593.605399&cid=C05S5EV2JTX).

**Comment by kadiealexander** [comment]
This is expected, and will self-resolve once the Travel Terms page is launched.
