### ISSUE TITLE
[HOLD for payment 2024-06-13] [HOLD for payment 2024-06-11] [$250] Tags settings – Unable to add Custom tag name in a new workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4561965
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Create new workspace
4. Click on More features and enable tags
5. Add 2 tags
6. Click on Settings and select Custom tag name
7. Enter Custom tag name and press Save

## Expected Result:
Custom tag name in added

## Actual Result:
Tag name is change and “Hmm… it’s not here” RHP appears when open it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f91c22a7-088c-4108-9cbf-6ee9b085ff8a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e9f676195ac29b7</li>
        <li>Upwork Job ID: 1791187130986975232</li>
        <li>Last Price Increase: 2024-05-23</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102497235</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag name is change and “Hmm… it’s not here” RHP appears when open it

### What is the root cause of that problem?
When we enable policy tag, we don't create the optimistic data for policy tag so when we enable tag and open setting, custom tag name is empty and we can't edit this.


https://github.com/Expensify/App/blob/5bfa295ac83c58465756614d4478cc49b2c921c4/src/libs/actions/Policy.ts#L4206

### What changes do you think we should make in order to solve the problem?
When we enable the tags feature, if the policyTagList doesn't exist we should create optimistic data for it the same as the image below

```
const policyTagList = allPolicyTags?.[policyID];
if (!policyTagList) {
    const defaultTagList: PolicyTagList = {
        Tag: {
            name: 'Tag',
            orderWeight: 0,
            required: false,
            tags: {}
        }
    }
    onyxData.optimisticData?.push({
        onyxMethod: Onyx.METHOD.SET,
        key: `${ONYXKEYS.COLLECTION.POLICY_TAGS}${policyID}`,
        value: defaultTagList,
    })
    onyxData.failureData?.push({
        onyxMethod: Onyx.METHOD.SET,
        key: `${ONYXKEYS.COLLECTION.POLICY_TAGS}${policyID}`,
        value: null
    })
}
```

<img width="1110" alt="Screenshot 2024-05-16 at 15 36 32" src="https://github.com/Expensify/App/assets/161821005/4053f852-cec0-4b12-8df5-b6a93211a314">


https://github.com/Expensify/App/blob/5bfa295ac83c58465756614d4478cc49b2c921c4/src/libs/actions/Policy.ts#L4206

### What alternative solutions did you explore? (Optional)
NA

**Comment by garrettmknight** [comment]
Reproduced and opened up. @mananjadhav what do you think of this first proposal?

**Comment by mananjadhav** [comment]
I just tested @nkdengineer's proposal it does seem to work. I was able to reproduce the error in the latest main, but when I was in a different branch the error didn't exist. I don't see any changes in `enablePolicyTags`. So I am not sure if we've got the correct root cause.

**Comment by nkdengineer** [comment]
@mananjadhav Can you share what is the result when you test in a different branch.

**Comment by mananjadhav** [comment]
I tested in this [PR branch](https://github.com/Expensify/App/pull/41559).

**Comment by nkdengineer** [comment]
@mananjadhav I still can reproduce this bug in this branch https://github.com/Expensify/App/pull/41559 without merging main.

https://github.com/Expensify/App/assets/161821005/7b713116-15ec-41df-9155-919e0718d5f2

**Comment by mananjadhav** [comment]
@nkdengineer This is when I tested on `xero-merge-freeze` branch.


https://github.com/Expensify/App/assets/3069065/20e8acfa-4c1d-480b-9551-d8e1cddfa35a

**Comment by nkdengineer** [comment]
@mananjadhav To reproduce this bug, we should add the tag immediately after we enable the tag and then when we open the setting we can see the custom tag name is empty as my video above https://github.com/Expensify/App/issues/42205#issuecomment-2119747939

**Comment by mananjadhav** [comment]
That was an accidental click during recording. I tried without that as well.

**Comment by nkdengineer** [comment]
@mananjadhav Please try to inspect network element, if you create a tag before `EnablePolicyTag` API is complete you can reproduce this bug.

**Comment by garrettmknight** [comment]
@mananjadhav can you try to reproduce with the update?

**Comment by nkdengineer** [comment]
@mananjadhav The PR is [here](https://github.com/Expensify/App/pull/42734).

**Comment by mananjadhav** [comment]
Done with the PR review and the checklist.

**Comment by garrettmknight** [comment]
Going with the first date and paying today:
**Payment Summary**
- Contributor: @nkdengineer $250 paid via upwork
- Reviewer: @mananjadhav $250

@mananjadhav can you complete the checklist when you get a chance and then submit for payment?

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by mananjadhav** [comment]
I don't have a specific offending PR for this one. @nkdengineer do you have an idea about this?

I also don't think we need a regression test for this one.
