### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Tags - When deleting all tags, blank UI is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the New Expensify App
2. Sign into a valid account
3. Click on WS > More features > Enable Tags (Notice that there will be an UI there since you have no tags yet)
4. Create any tag then delete this tag

## Expected Result:
User expects the initial "No Tag" UI to show up again and immediately

## Actual Result:
No UI is shown, just a blank space. Even after exiting and returning or refreshing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f64051cd-b733-43c8-bcb5-4f11b0c7ce32

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015255d5c42b2d8ce7</li>
        <li>Upwork Job ID: 1793173724031148032</li>
        <li>Last Price Increase: 2024-05-22</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102491218</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by JmillsExpensify** [comment]
Opening this up to the community.

**Comment by wkarim86** [comment]
**Proposal.**
As watched the video the problem in tags condition where showing the no tags UI. It can be a very quick fix within an hour and in less than you cost you posted on Upwork. I am available right now and work on it immediately.

Thanks,
Waqas K.

**Comment by allroundexperts** [comment]
Reviewing today!

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone. @tienifr's [proposal](https://github.com/Expensify/App/issues/42220#issuecomment-2124305407) handles all the cases correctly and as such, we should go with them.

🎀 👀 🎀 C+ reviewed

**Comment by wkarim86** [comment]
Contributor details
Your Expensify account email: wkarim86@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a5e7655ce154e085

**Comment by wkarim86** [comment]
@tienifr I haven't got the offer yet on Upwork.

**Comment by wkarim86** [comment]
> @wkarim86 Please read the contributing guides [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) to understand how contribution works in this project.

I have read the contribution document as well as the code of conduct. Could you tell me what the next step will be? Would you like me to start working on the issue or first I have to accept the offer from Upwork? If this is the case, I can create PR within 3 days, because setting up the application may take more time than usual. I hope you can understand.

**Comment by Beamanator** [comment]
@wkarim86 sorry but you were not hired for this job. As you can see in [this comment](https://github.com/Expensify/App/issues/42220#issuecomment-2134069012), our assigned Contributor-plus team member recommended hiring `tienifr` , and I agreed so I hired them.

As you probably read in the contributor guidelines, once the `Help Wanted` label is removed from an issue, the job is no longer open b/c someone else was already hired. If you have any questions about that process, please ask in slack - in the #expensify-open-source channel

**Comment by wkarim86** [comment]
@Beamanator Ok no problem. I missed that comment.

**Comment by Beamanator** [comment]
@JmillsExpensify looks like we're ready for payment here 🙏

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: $250 @tienifr 
 - Contributor+: $250 @allroundexperts

**Comment by JmillsExpensify** [comment]
Contributor paid out. C+ needs to fill out the checklist and is paid via New Expensify, so I'll circle back on this issue for payment approval.

**Comment by allroundexperts** [comment]
## Checklist

1. https://github.com/Expensify/App/pull/37755
2. https://github.com/Expensify/App/pull/37755/files#r1650184022
3. N/A
4. A regression test would be helpful. The steps given in the OP look good enough to me.

**Comment by JmillsExpensify** [comment]
@mallenexpensify can you confirm the payment summary above?

**Comment by mallenexpensify** [comment]
Contributor: @tienifr due $250 via NewDot
Contributor+: @allroundexperts due $250 via NewDot

TestRail Gh https://github.com/Expensify/Expensify/issues/414355
