### ISSUE TITLE
[HOLD for payment 2024-08-27] [$500] [CVP] Add an Illustration and simple directions to the the Submits to screen if there are no contacts

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#42227]
Problem: Expensify is supposed to make money more efficient and fun. For an organic new user, the first time they send an expense to anyone they do not have any contacts. Thus, they see an empty screen which feels off brand. Especially for such a critical first time experience. It currently looks like this:
![image](https://github.com/Expensify/App/assets/2364487/f99e1c38-1556-4c0e-b7d1-6810e56d3be7)

Solution: Add a fun illustration (with short and clear directions) to the empty state “Submits to” screen if the user does not have any recent contacts. If there are any recents in the list, we would not show the illustration. It could look like like this:
![image](https://github.com/Expensify/App/assets/22508290/f0441ea8-e837-48f8-9965-ba8733afec56)

Current proposed text: 
- **Get paid back**
- Submit your expense to any email or phone number.

This is being discussed here. @shawnborton can get the final image and @kevinksullivan can help with the  https://expensify.slack.com/archives/C03TBKRSB/p1715809342220239?thread_ts=1714766113.560229&cid=C03TBKRSB

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01632280a607ac1c81</li>
        <li>Upwork Job ID: 1791150727815004160</li>
        <li>Last Price Increase: 2024-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by shawnborton** [comment]
Here is the file you need: [emptystate__toddwithphones.svg.zip](https://github.com/Expensify/App/files/15328053/emptystate__toddwithphones.svg.zip)

It should be displayed at 176px wide by 178px tall.

We should also have marketing review the copy here as well.

**Comment by shawnborton** [comment]
I think the same is fine

**Comment by mountiny** [comment]
The other options we need copy and translations for are:
- Split Expense
- Start Chat
- Track Expense
- Pay Someone
- Send Invoice
- Assign task

**Comment by danielrvidal** [comment]
So I think the only ones we need it for are actually Submit Expense, Split Expense, and Pay someone. In all other cases, there is someone already in your recent. @shawnborton @mountiny do you agree we just need those cases? I'll get the copy and translation tomorrow for them. 

Start chat
![image](https://github.com/Expensify/App/assets/2364487/42da086a-38db-47f4-9f7d-226ba14c1e92)

Track Expense
No selector 

Submit expense
![image](https://github.com/Expensify/App/assets/2364487/15114784-88e7-4a31-96ce-8c31204d6a98)

Split expense
![image](https://github.com/Expensify/App/assets/2364487/f00b81b4-7925-48fc-8833-a9cdcee1c14f)

Pay someone
![image](https://github.com/Expensify/App/assets/2364487/9ac11b7b-c543-482e-b1b2-32033c918772)

Assign a task:
![image](https://github.com/Expensify/App/assets/2364487/e92b553a-d8da-49bf-8242-0609076e9811)

Send Invoice
![image](https://github.com/Expensify/App/assets/2364487/40d982d9-a222-441b-b1d8-f93ce0d6e549)

**Comment by shawnborton** [comment]
That makes sense to me!

**Comment by shawnborton** [comment]
Yeah we might want to do feature-specific copy for each of those flows Daniel mentioned.

**Comment by danielrvidal** [comment]
I'm working on finalizing the copy today, I should have it done by EOD.

**Comment by danielrvidal** [comment]
@allroundexperts any update on this one? Could you review @tienifr proposal and see if it could apply to how we build this including the updates?

**Comment by mountiny** [comment]
@danielrvidal I think the last piece is to agree on the copy here https://github.com/Expensify/App/pull/42413#issuecomment-2135699949 can you please check out the discussion in the PR?

Thank @allroundexperts can complete the review

**Comment by danielrvidal** [comment]
Updated in the other comment, let me know if there is anything else outstanding!

**Comment by danielrvidal** [comment]
@tienifr is still working on this here: https://github.com/Expensify/App/pull/42413#issuecomment-2135699949

So we're still all good.

**Comment by mountiny** [comment]
@tienifr updating the price as this is proving more complex and tedious with the back and forth on the mocks, lets get this over the finish line though

**Comment by quinthar** [comment]
Love this idea!

**Comment by danielrvidal** [comment]
@tienifr @allroundexperts any update here? I just removed the waiting for copy label as I don't think we're waiting for copy anymore.

**Comment by mountiny** [comment]
@tienifr is trying to address the last pr comments. I hope to merge it this week

**Comment by danielrvidal** [comment]
This was just deployed to staging, I just tested it and it's looking good!

**Comment by mountiny** [comment]
This is ready for payment now; it was a new feature; I am not sure if we need regression tests for this, as it would most likely be caught during random testing.

$500 to @tienifr and to @allroundexperts

**Comment by mallenexpensify** [comment]
Contributor: @tienifr owed $500 via NewDot.  
Contributor+: @allroundexperts owed $500 via NewDot.  

QA has monthly regression tests where they check for design-related bugs and edge cases.  What about creating the TestRail GH, mentioning that as an option and letting QA make the call?

**Comment by mallenexpensify** [comment]
Should be all set!  Test case GH
- https://github.com/Expensify/Expensify/issues/423804

**Comment by garrettmknight** [comment]
$500 approved for @tienifr

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
