### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] Task - Users avatars change to default in share somewhere after assigning task from FAB

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42232]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Tap FAB > Assign task
3. Create a task and share it somewhere
4. Return to LHN
5. Tap FAB > Assign task
6. Enter title and proceed to the confirmation screen
7. Tap Share somewhere

## Expected Result:
Users' avatar are displayed next to reports

## Actual Result:
Users' avatars change to default ones in Share somewhere after creating a task the first time

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/bb3cd6a0-50b1-4f33-8f0d-d3ba07ea1629

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc2420bf539eea63</li>
        <li>Upwork Job ID: 1790878589287768064</li>
        <li>Last Price Increase: 2024-05-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by m-natarajan** [comment]
@NikkiWines FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by NikkiWines** [comment]
This can definitely be external, I'll check the deploy diff to see if we modified something related to tasks or avatars in the latest deploy.

**Comment by NikkiWines** [comment]
Seems like something that _miiight_ be tied to the recent participants migration (https://github.com/Expensify/App/pull/40254), thoughts @s77rt @marcaaron?

**Comment by marcaaron** [comment]
Oh, I thought we deployed that already haha _::puts on game face::_ 😅

**Comment by marcaaron** [comment]
It definitely _could be_ related - hard to say without digging into the code.

**Comment by s77rt** [comment]
I'm checking that atm

**Comment by s77rt** [comment]
Not related to the participants migration. Offending PR: https://github.com/Expensify/App/pull/41636/files#r1602409674

cc @tienifr @c3024

**Comment by Beamanator** [comment]
Fix is in staging and works well!
