### ISSUE TITLE
FAB - Track expense button is missing from the FAB for new expensifail accounts

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4561895&group_by=cases:section_id&group_order=asc&group_id=295815
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Sign up for a new expensifail account
2. Click on the FAB

## Expected Result:
Track expense button should be available from the start.

## Actual Result:
Track expense button is missing from the FAB for new expensifail accounts. 
It returns if you refresh the page on web and mWeb. 
You have to restart the app on iOS and Android for the button to return. 
Doesn't affect Gmail accounts.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d89543ed-b9f4-4c3d-8bbf-9abe6917c359

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
>Doesn't affect Gmail accounts.

This sounds suspect to me. Is this behind a beta or something?

>It returns if you refresh the page on web and mWeb.

also _sounds like_ a BE problem.

**Comment by marcaaron** [comment]
Seems potentially related to https://github.com/Expensify/App/pull/41892 cc @thienlnam

**Comment by thienlnam** [comment]
This just happens for expensifail accounts?? 😕

**Comment by thienlnam** [comment]
I wonder if this is because the accounts are getting created in a different flow than the typical CreateAccount where the shouldCreateSelfDM flag is added. This should be resolved [here](https://github.com/Expensify/Expensify/issues/395534). Additionally if this is just for expensifail accounts we can demote this

**Comment by marcaaron** [comment]
Ah yeah that seems like a good guess. Gonna let you figure this out 🏃‍♂️

**Comment by thienlnam** [comment]
Not a daily, going to be resolved as part of this issue https://github.com/Expensify/Expensify/issues/395534

**Comment by thienlnam** [comment]
Still pending on the above, running into a runtime core dump that I haven't figured out yet

**Comment by thienlnam** [comment]
Same, no progress

**Comment by thienlnam** [comment]
Held PR is merged and deployed - asking for a retest

**Comment by mvtglobally** [comment]
Not repro https://github.com/user-attachments/assets/be4fe40f-a238-4d77-8b2c-dd5db51a8f66

**Comment by thienlnam** [comment]
Sweet - all good then
