### ISSUE TITLE
[WAITING ON FEDI - CHECKLIST] Distance Expense - Map is not centered over San Francisco when location settings are turned off

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42236]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4561935
**Email or phone of affected tester (no customers):** applausetester+azadmin@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Disable the location settings for New Expensify in Chrome
2. Navigate to Request Money > Distance expense

## Expected Result:
The map is centered over San Francisco

## Actual Result:
The map is shown over my current city

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eae942a7-4eca-453b-b30b-15db9576fd11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015240613a85d23a6c</li>
        <li>Upwork Job ID: 1790944314356584448</li>
        <li>Last Price Increase: 2024-05-16</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by luacmartins** [comment]
This is pretty small and NAB.

**Comment by shlommo** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The map is shown over my current city when user geolocation settings are disabled 

### What is the root cause of that problem?
setCurrentPositionToInitialState callback returns when user location is already cached in Onyx
https://github.com/Expensify/App/blob/0d45c5564188fa63bf1eada357b11e8e3c7e60d9/src/components/MapView/MapView.website.tsx#L67-L69

### What changes do you think we should make in order to solve the problem?
We should check for an error code returned from the `getCurrentPosition` callback and set a default location when `error.code` equals `GeolocationErrorCode.PERMISSION_DENIED`
```ts
if (error.code !== GeolocationErrorCode.PERMISSION_DENIED && (cachedUserLocation || !initialState)) {
  return;
}
```

### What alternative solutions did you explore? (Optional)

**Comment by slafortune** [comment]
There is a PR in review.  I'll be out until June 4th - so adding another BZ in the meantime.  I'll take this back on the 4th if needed.

**Comment by jliexpensify** [comment]
@fedirjh any regressions here?

**Comment by jliexpensify** [comment]
Ok, is this a correct Summary?

- C: @tienifr $250
- C+: @fedirjh $250 - please accept the offer!

[Upwork job](https://www.upwork.com/jobs/~015240613a85d23a6c)

Just waiting on the checklist (if applicable)

**Comment by jliexpensify** [comment]
Not overdue. Bump @fedirjh for the checklist.

**Comment by jliexpensify** [comment]
Paid and job closed. Bump @fedirjh for the checklist!

**Comment by luacmartins** [comment]
Agreed. I think we're all good to close here. Please reopen if needed.
