### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$125] [TS migration] Configure TS & Migrate `CONST`, `fastMerge`, `Device`, `Logger` to Typescript (expensify-common)

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#42245]
# Typescript migration (expensify-common)
Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md) before you start working on this migration issue.

## Files
`lib/CONST.jsx`
`lib/fastMerge.js`
`lib/Device.jsx`
`lib/Logger.jsx`
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5172255327c6e67</li>
        <li>Upwork Job ID: 1791118677164871680</li>
        <li>Last Price Increase: 2024-05-16</li>
    </ul>
</details>

**Comment by blazejkustra** [comment]
I got approval from @roryabraham to create this issue on `#typescript-new-expensify` channel [here](https://swmansion.slack.com/archives/C0593T50UHG/p1715785111971079?thread_ts=1715700692.009169&cid=C0593T50UHG). Let's add it to Typescript project and change labels as this is not a bug, thanks!

**Comment by blazejkustra** [comment]
I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue 😄

**Comment by joekaufmanexpensify** [comment]
@blazejkustra sounds good! Is the next step for you to raise a PR here?

**Comment by roryabraham** [comment]
yes, I think so

**Comment by godofoutcasts94** [comment]
Dibs

**Comment by joekaufmanexpensify** [comment]
@godofoutcasts94 this issue is already assigned. Only issues with the `help wanted` label are available. LMK if you have questions.

**Comment by godofoutcasts94** [comment]
Oh sorry! My bad!

**Comment by s-no1ukno** [comment]
Hey there - saw this issue on Upwork, but after reviewing some of these comments I can't figure out if it's open to proposals or not.  I have started looking into the migration, but don't want to waste anyone's time...can someone let me know if this is available to work on or not?  Thanks in advance!

**Comment by s-no1ukno** [comment]
Contributor details 
Your Expensify account email: jsnow@snowdev.co
Upwork Profile Link: https://www.upwork.com/freelancers/~0133925c6cb76728cc

**Comment by blazejkustra** [comment]
@s-no1ukno Issue is assigned already and being worked on, see [this](https://github.com/Expensify/App/issues/42245#issuecomment-2115507930) comment.

**Comment by roryabraham** [comment]
>  Does that mean this doesn't need to be deployed?

The code change was made in expensify-common (a set of javascript libs shared between OldDot and NewDot). It won't take effect until we [upgrade expensify-common in E/App](https://github.com/Expensify/App/pull/42387), and that PR is deployed.

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY!

**Comment by blazejkustra** [comment]
Update: https://github.com/Expensify/App/pull/42387 was just merged 🚀

**Comment by roryabraham** [comment]
woohoo 🚀

**Comment by joekaufmanexpensify** [comment]
PR is on staging

**Comment by joekaufmanexpensify** [comment]
No regression test needed for TS migration

**Comment by joekaufmanexpensify** [comment]
Only payment here is $125 to @abdulrahuman5196 for C+ review via Upwork.

**Comment by joekaufmanexpensify** [comment]
@abdulrahuman5196 just sent you an offer for $125!

**Comment by joekaufmanexpensify** [comment]
There may be a [possible regression here](https://github.com/Expensify/App/issues/42245#issuecomment-2153222045) too. @roryabraham @abdulrahuman5196 could you please confirm if this was indeed a regression?

**Comment by joekaufmanexpensify** [comment]
I'm about to go OOO until 2024-06-25. Adding another BZ assignee to handle payment next week. We just need to:

- Determine whether [this](https://github.com/Expensify/App/issues/42245#issuecomment-2168648439) was a regression.
- Issue payment after the waiting period. 

I'll take this back once I return (if it's still open)!

**Comment by bfitzexpensify** [comment]
Bump on https://github.com/Expensify/App/issues/42245#issuecomment-2168648439 @roryabraham @abdulrahuman5196 - thank you!

**Comment by abdulrahuman5196** [comment]
@bfitzexpensify I don't think this is a direct regression but a combined issue due to efforts from different PR. 
But feel free to correct me if wrong.

**Comment by bfitzexpensify** [comment]
Thanks for confirming @abdulrahuman5196. Paid out, we're all done here.
