### ISSUE TITLE
[$125] [TS migration] Migrate `ExpensiMark` to Typescript (expensify-common)

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#42247]
# Typescript migration (expensify-common)
Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md) before you start working on this migration issue.

## Files
`lib/ExpensiMark.js`
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014925282fa7b2a6db</li>
        <li>Upwork Job ID: 1791121920495669248</li>
        <li>Last Price Increase: 2024-05-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by blazejkustra** [comment]
I got approval from @roryabraham to create this issue on `#typescript-new-expensify` channel [here](https://swmansion.slack.com/archives/C0593T50UHG/p1715785111971079?thread_ts=1715700692.009169&cid=C0593T50UHG). Let's add it to Typescript project and change labels as this is not a bug, thanks!

**Comment by blazejkustra** [comment]
Update: I'm going to work on this one tomorrow

**Comment by blazejkustra** [comment]
Update: [PR](https://github.com/Expensify/expensify-common/pull/721) is up, it's on hold for now as it's based from [another PR](https://github.com/Expensify/expensify-common/pull/718). In case you want to review it, here is a link to [my changes](https://github.com/Expensify/expensify-common/pull/721/files/ba69e50a266c4daa439f47fd39c602809b819cb7..3ae1936c5ac14e443614ad7bf187359cf29d0f07).

**Comment by roryabraham** [comment]
This is on main now, went to staging 5 hours ago in https://github.com/Expensify/App/pull/44021.

**Comment by roryabraham** [comment]
Any payments due?

**Comment by srikarparsi** [comment]
I don't think so, I think this is good to close @roryabraham

[Migration PR](https://github.com/Expensify/expensify-common/pull/721): SWM handled
[expensify-common bump](https://github.com/Expensify/react-native-live-markdown/pull/390): I created and SWM reviewed
[App bump](https://github.com/Expensify/Expensify/issues/406072): I created and C+ reviewed but payment is being taken care of [here](https://github.com/Expensify/App/issues/44147)
