### ISSUE TITLE
[$125] [TS migration] Migrate `str` to Typescript (expensify-common)

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#42246]
# Typescript migration (expensify-common)
Make sure you read through our TypeScript's [style guide](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md) before you start working on this migration issue.

## Files
`lib/str.js`
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eab386dd14c7df3a</li>
        <li>Upwork Job ID: 1791121961019691008</li>
        <li>Last Price Increase: 2024-05-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by blazejkustra** [comment]
I got approval from @roryabraham to create this issue on `#typescript-new-expensify` channel [here](https://swmansion.slack.com/archives/C0593T50UHG/p1715785111971079?thread_ts=1715700692.009169&cid=C0593T50UHG). Let's add it to Typescript project and change labels as this is not a bug, thanks!

**Comment by blazejkustra** [comment]
> I would like to pick this.

@ShridharGoel I think we'll handle this one internally/by agency.

**Comment by nkdengineer** [comment]
dibs

**Comment by blazejkustra** [comment]
Blocked by https://github.com/Expensify/App/issues/42245 for now.

**Comment by blazejkustra** [comment]
I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue 😄

**Comment by blazejkustra** [comment]
Update: PR is ready for internal and cross review

**Comment by MitchExpensify** [comment]
Not overdue

**Comment by sobitneupane** [comment]
Any update @blazejkustra ?

**Comment by roryabraham** [comment]
This is done, looks like it was merged w/o any C+ review, so we can close this out.
