### ISSUE TITLE
[HOLD for payment 2024-06-06] Split - Tab key highlights the next user instead of focusing the next split amount input

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42258]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat.
3. Go to + > Split expense > Manual.
4. Enter amount > Next.
5. On confirmation page, click on the split amount input.
6. Use Tab key to switch to the next input.

## Expected Result:
When the split amount input is in focus, one press on Tab key will switch to the next input (production behavior).

## Actual Result:
When the split amount input is in focus, one press on Tab key highlights the next user. Only the second press switches to the next input.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/599dae1a-50ca-42a9-85c2-b61b62cb73e1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by izarutskaya** [comment]
@lschurr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-split.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/94cec178-e245-4238-a1bf-3450997d2447

**Comment by MonilBhavsar** [comment]
Going through deploy checklist to find offending PR

**Comment by MonilBhavsar** [comment]
Looks this PR https://github.com/Expensify/App/pull/40785
Minor issue so removing deploy blocker label

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

I'm also the author of the big PR that introduced this bug and have an idea on how to fix this - tabIndex is not being passed via props to children thus the focusing issue

**Comment by MrMuzyk** [comment]
PR is up (TS checks are failing due to unrelated errors in main). Ready to be reviewed. Hope it's ok that I've skipped proposal part - in the past it wasn't needed in a case when I was fixing regression from my previous PR

**Comment by MrMuzyk** [comment]
Rebased with latest main and all checks are green now

**Comment by rushatgabhane** [comment]
PR approved

**Comment by MonilBhavsar** [comment]
Thanks!

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @MrMuzyk (does not require payment)
- Contributor+: $250 @rushatgabhane (requires payment through NewDot Manual Requests)

**Comment by MonilBhavsar** [comment]
This was fixed as regression, so no payment is due here @lschurr

**Comment by lschurr** [comment]
Ah, great! I deleted the payment summary. Thanks!
