### ISSUE TITLE
Task - Mark down is not applied to task description

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Go to + > Assign task.
4. Enter title and add description containing mark down.
5. Create the task.
6. Go to task report.
7. Click on the description.
8. Edit the description while maintaining the mark down.

## Expected Result:
In Step 6, mark down should apply to the description in task report.

## Actual Result:
In Step 6, mark down is not applied to the description in task report.
It only applies mark down when the description is edited in Step 8.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1da91720-c176-4165-a4e6-55296a8db0ac

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@johncschuster I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Beamanator** [comment]
@bernhardoj is working on fixing this in https://github.com/Expensify/App/pull/42244 👍 🙏

**Comment by Beamanator** [comment]
Fixed in staging 👍
