### ISSUE TITLE
mWeb - Workspace -Clicking back from workspace profile page behaves inconsistently

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue found when executing PR:** https://github.com/Expensify/App/pull/40342
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace > Go to workspace profile page and copy the URL
3. Paste the URL in any chat and tap on it
4. Tap on the system back button
5. Tap on the URL again and tap on the back icon at the top left
6. Execute steps 2 - 5 on Android for comparison

## Expected Result:
The behavior on mWeb is similar to the behavior in Android. Tapping on the system back button should take user to the workspace settings page instead of navigating to the chat page

## Actual Result:
App takes user to the chat page when tapping on the system back button which is different from the behavior on Android. Android takes user back to the workspace settings page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/68af4f98-17cf-45fa-8d67-7698521e0141

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment]
@mallenexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by mallenexpensify** [comment]
Futz around a bit trying to retest in Browserstack but was running into issues. 
Gonna close as expected behaviour cuz I would expect the below. 

1. Navigate to then copy profile page link - https://new.expensify.com/settings/workspaces/3CB85620FE2B6ACC/profile
2. Go to chat  - https://new.expensify.com/r/599461364970047
3. Send profile link in chat
4. Click profile link to go to profile page
5. Click back

Expected - Return to https://new.expensify.com/r/599461364970047
