### ISSUE TITLE
[HOLD for payment 2024-06-06] [QBO] Fix style regression for the text in `ToggleSettingOptionRow`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#42309]
https://github.com/Expensify/App/pull/41917 caused style regressions in which several places that use `ToggleSettingOptionRow` ended up having the text bolded. Fix these bolded text back to the normal style.

Slack convo: https://expensify.slack.com/archives/C01SKUP7QR0/p1715875595366199

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by CortneyOfstad** [comment]
Still waiting on a response to [this question](https://github.com/Expensify/App/pull/41917#issuecomment-2115758100) in the original PR

**Comment by hayata-suenaga** [comment]
I don't necessarily need an answer for that question. I'll continue with my PR when I have time 🙇

**Comment by CortneyOfstad** [comment]
No worries and thanks @hayata-suenaga!

**Comment by trjExpensify** [comment]
If this is an /app PR @hayata-suenaga why not have someone else take it while you work on others? Perhaps, @s77rt?

**Comment by s77rt** [comment]
I can take this but I don't have access to the Slack conversion linked above.

**Comment by trjExpensify** [comment]
Here's the short convo: 

<img width="699" alt="image" src="https://github.com/Expensify/App/assets/16232057/0fe51bf8-1d40-4634-b91a-a5ec08d90952">
<img width="691" alt="image" src="https://github.com/Expensify/App/assets/16232057/ce74aa60-17fd-4ce4-86e6-537ed2d0bd22">

The PR Hayata references is: https://github.com/Expensify/App/pull/41917

**Comment by s77rt** [comment]
Got it. On it...

**Comment by s77rt** [comment]
Raised [PR](https://github.com/Expensify/App/pull/42596)

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/41917
- The offending PR has been commented on: https://github.com/Expensify/App/pull/41917#discussion_r1603693595
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by CortneyOfstad** [comment]
@s77rt I sent you an offer via Upwork [here](https://www.upwork.com/jobs/~01d61f6001055a040a). Let me know once you accept and I'll get that paid ASAP. Thanks!

**Comment by s77rt** [comment]
@CortneyOfstad Accepted! This needs to be $125 for the regression https://github.com/Expensify/App/issues/42998

**Comment by CortneyOfstad** [comment]
Good catch, adjusted the payment and completed payment!

## Payment Summary

@s77rt — paid $125 via Upwork
