### ISSUE TITLE
[HOLD for payment 2024-06-24] [QBO] Consolidate the Spanish translation of "Journal Entry" to use a single translation

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#42350]
Currently, we use different variations of Spanish translation for "Journal Entry".

- Asiento Contable
- Asiento de diario
- Anotación en el diario

Use a single variation of Spanish translation.

[Slack convo](https://expensify.slack.com/archives/C21FRDWCV/p1715968043426509?thread_ts=1715794113.473229&cid=C21FRDWCV)

**Comment by hayata-suenaga** [comment]
Changing this to weekly as this is a translation refactoring issue

**Comment by hayata-suenaga** [comment]
thank you for the offer of help. But we just have to confirm internally what the translation should be.

The change itself is small so I can do it.

**Comment by hayata-suenaga** [comment]
not a high priority now. will get back to this when I have time.

**Comment by dangrous** [comment]
@hayata-suenaga I can grab this from you while you're out (and so I can actually code for the QBO project haha)! Looks like we settled on `asiento contable` is that right? I'll make a quick PR and tag you for review.

**Comment by hayata-suenaga** [comment]
thank you Daniel!

**Comment by dangrous** [comment]
No payment is required on this issue, and it's copy only so shouldn't cause any regressions. Closing it - feel free to reopen if you disagree.

**Comment by hayata-suenaga** [comment]
Thank you for handling this Daniel! 😄
