### ISSUE TITLE
[$250] [HOLD for payment 2024-06-11] [Wave Collect] [Xero] When you click “Sync now” you see the Quickbooks Online text very briefly:

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42376]
When you click “Sync now” you see the Quickbooks Online text very briefly.

![image](https://github.com/Expensify/App/assets/21549771/446f5868-e4a7-4089-8c5b-38351eb3e574)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116910bc2a2e655fa</li>
        <li>Upwork Job ID: 1800589815293109964</li>
        <li>Last Price Increase: 2024-06-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by hungvu193** [comment]
Taking a look 👀

**Comment by trjExpensify** [comment]
Testing well on the freeze branch, nice. 👍

**Comment by garrettmknight** [comment]
@hungvu193 offer out to you!

[Link for me](https://www.upwork.com/ab/applicants/1800589815293109964/hires?filter=hung&page=1&nav_dir=pop)

**Comment by hungvu193** [comment]
Xero project have flat price and I already got paid so we can close this one 😄

**Comment by 282159468** [comment]
This bug was not reproduced

**Comment by 282159468** [comment]
Contributor details
Your Expensify account email: fhqdgvwqvb@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/zhaow2
