### ISSUE TITLE
[HOLD for payment 2024-06-11] [Wave Collect] [Xero] The first bank account in the list is not selected by default

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42378]
The first bank account in the list is not selected by default (that’s how it works with the QBO integration).

![image](https://github.com/Expensify/App/assets/21549771/4bc35fc4-7830-4c79-8210-0103226e8297)

**Comment by rushatgabhane** [comment]
working on it

**Comment by mananjadhav** [comment]
@rushatgabhane Sorry I missed this. I already have the PR for this.

**Comment by rushatgabhane** [comment]
that's great! I'll review it then : )

**Comment by rushatgabhane** [comment]
PR merged.

**Comment by trjExpensify** [comment]
Testing well on the adhoc build of the merge freeze branch, nice. 👍

**Comment by hayata-suenaga** [comment]
@lakchote did the review. I don't know why Melvin assigned me 🤔 Unassigning myself and assigning @lakchote

**Comment by lakchote** [comment]
Not overdue.

**Comment by mananjadhav** [comment]
There won't be any payout for this. This is centrally handled as a flat fee.

**Comment by rushatgabhane** [comment]
We can close this issue
