### ISSUE TITLE
[Wave Collect] [Xero] Auto-sync should be enabled by default for all integrations

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42375]
BUG: Auto-sync should be enabled by default for all integrations.

![image](https://github.com/Expensify/App/assets/21549771/722fa283-e440-4e25-95f1-ae671981cbec)

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by SzymczakJ** [comment]
@trjExpensify are there any specific reproduction steps? When I connect to Xero from any account the auto-sync is always toggled on

**Comment by trjExpensify** [comment]
Nothing specific, I'm afraid. I simply: 

1. Created a new account (that has access to the Xero & Accounting betas)
2. Choose "Manage my team's expenses" in the onboarding modal to create a workspace
3. Enabled `Accounting` in `More features` on that workspace
4. Connected to Xero 
5. Went to the `Advanced` page 
6. Observed auto sync was disabled

I did these steps on the adhoc build of the merge freeze branch. @lakchote, if we spin up a fresh build with the latest from the Xero merge freeze branch, I'm happy to re-test this again?

**Comment by lakchote** [comment]
@SzymczakJ I just tried to reproduce following your steps, and auto sync is enabled even If I choose the option `Manage my team's expenses` in the onboarding modal.

I'm going to trigger a new build, and see if @trjExpensify can reproduce again.

**Comment by SzymczakJ** [comment]
Wasn't able to reproduce it with the same reproduction steps 😒

**Comment by lakchote** [comment]
@trjExpensify could you retest please?

The new ad hoc build has been deployed to Web.

**Comment by trjExpensify** [comment]
Nice! Retested and `Auto-sync` was enabled by default this time: 

https://github.com/Expensify/App/assets/16232057/40bb2c7e-e227-47bf-a6ac-ff3a40e5e155

**Comment by lakchote** [comment]
Great, closing this issue then. If it happens again, I'll reopen it.
