### ISSUE TITLE
[HELD ON OpenApp 1:1:1] HIGH: [API Reliability] Add better error handling to OpenApp

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#42382]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
e.g. memory consumption, storage read/write times, React native bridge concerns, inefficient React component rendering, etc.

OpenApp is our most important API call, but when things go wrong, the error messages generated by the server are threadbare which makes debugging harder.

## What is the impact of this on end-users?
List specific user experiences that will be improved by solving this problem e.g. app boot time, time to for some interaction to complete, etc.

A more understandable API means more reliable outcomes in the app for end users

## List any benchmarks that show the severity of the issue
Please also provide exact steps taken to collect metrics above if any so we can independently verify the results.

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

Cc @tgolen if I'm misunderstanding anything here:

Let's add more detailed and context rich error handling to OpenApp, and give more information on the specific part of the call that is having problems

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by tgolen** [comment]
I'm going to be OOO for the next week and a half so I am unable to take this right now.

**Comment by muttmuure** [comment]
Going to close in favor of delivering OpenApp 1:1:1, which is a fast-apis initiative
