### ISSUE TITLE
[$250] [HOLD for payment 2024-06-13] HIGH: [API Reliability] Add cancel function when you select an option in search and navigate away from the optionList

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#42384]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
e.g. memory consumption, storage read/write times, React native bridge concerns, inefficient React component rendering, etc.

Currently, when you use search in New Expensify, we show results progressively and put the "best result" at the top. However a query for the full optionList always finishes after you've started it, even if you navigate away from the page that is performing the command. 

## What is the impact of this on end-users?
List specific user experiences that will be improved by solving this problem e.g. app boot time, time to for some interaction to complete, etc.

When you have navigated to the page you actually want, that page is a little slow because there is an expensive operation still running in the background.

## List any benchmarks that show the severity of the issue
Please also provide exact steps taken to collect metrics above if any so we can independently verify the results.

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

Create a new "cancel" API command that ceases the operation of querying search when you navigate to the report you've selected from the optionList. 

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164d3f1e9ba4d7d59</li>
        <li>Upwork Job ID: 1801734919193659319</li>
        <li>Last Price Increase: 2024-06-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by muttmuure** [comment]
Ah, yeah probably. Apologies as I didn't fully understand this one, you might be right

**Comment by muttmuure** [comment]
Would you be interested in taking it on?

**Comment by adhorodyski** [comment]
sure, let's do it - you can assign this to me

**Comment by adhorodyski** [comment]
@muttmuure I won't be available in the next few days, sharing my findings from today. I'm looping in the Callstack team to take over in our morning :) 

---

**Research**

Each `API.read` command like [searchForReports](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/actions/Report.ts#L3525) can be manually aborted when having a `canCancel` data parameter, but this relies on a [single AbortController instance](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/HttpUtils.ts#L52) for all the requests. This means we can manually trigger cancellation [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/pages/ChatFinderPage/index.tsx#L141) like this:

```diff
const selectReport = (option: OptionData) => {
        console.log('Navigating to a report', option);
        if (!option) {
            return;
        }

+      HttpUtils.cancelPendingRequests();

        if (option.reportID) {
            setSearchValue('');
            Navigation.dismissModal(option.reportID);
        } else {
            Report.navigateToAndOpenReport(option.login ? [option.login] : []);
        }
    };
```

...but it'd cancel everything that is currently running, **potentially not only our Search queries** (which we have multiple when typing even slightly slower).

---

**Options**

1) Test the above solution on a build, it may be that it's totally safe to run a regular full cancellation there.
2) Add per-query cancellation, which will require using a separate abort controller for this API command we can call `.abort()` on when selecting a report.

**Comment by rinej** [comment]
@muttmuure hello I am Tomek from Callstack, I will take it over from Adam

**Comment by muttmuure** [comment]
Thanks!

**Comment by mountiny** [comment]
$250 to @shubham1206agra for their review

**Comment by kadiealexander** [comment]
@shubham1206agra I have sent you an Upwork contract on behalf of @VictoriaExpensify, could you please let us know here when it's been accepted and we'll issue payment? Thanks!

**Comment by VictoriaExpensify** [comment]
Thanks @shubham1206agra ! I'm just having a few Upwork issues but I'll get this sorted and get you paid ASAP

**Comment by kadiealexander** [comment]
I've paid out @shubham1206agra while Vic sorts her access.
