### ISSUE TITLE
HIGH: [API Reliability] Receiving a message calls ReadNewestAction twice, then GetMissingOnyxUpdates

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#42388]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v1.4.74-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1715970211315929

## Action Performed:
Break down in numbered steps

1. Open the Network queue in browser dev tools for the account that will be the message receiver (user 2)
2. Send message from user 1 to user 2
3. Observe the Network queue for user 2
4. Observe the payload of the API calls

## Expected Result:
Describe what you think should've happened

There is a single ReadNewestAction call and no GetMissingOnyxUpdates call

The onyx data is only received using one API call

## Actual Result:
Describe what actually happened

There are two identical ReadNewestAction calls and a redundant GetMissingOnyxUpdates call, all of them doing the same thing (getting the new message) 

All APIs return the same onyx updates

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment]
I've managed to reproduce that issue. I'm looking into the cause and possible solution

https://github.com/Expensify/App/assets/23487612/dacae7b5-bdce-4193-b431-409d9598dd1b

**Comment by MrMuzyk** [comment]
@muttmuure 

I'm looking at the code and I think that `readNewestAction` doesn't get the new message. It marks it as `read` by a user. This is an API.write call. 

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/actions/Report.ts#L1141-L1163

`GetMissingOnyxUpdates` does something else and it's being called because there is a difference between `lastUpdateIDFromClient` and `previousUpdateIDFromServer`

https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/libs/actions/OnyxUpdateManager/index.ts#L136-L147

I might be wrong because I've just started investigating this but neither of this calls seem to directly get latest messages for a user

**Comment by muttmuure** [comment]
Did you get the duplicated calls the first time you tried to reproduce it?

**Comment by muttmuure** [comment]
@MrMuzyk the issue is that the `lastReadTime` is being returned twice, can you look into that? 

More discussion here: https://expensify.slack.com/archives/C05R2V5GM1S/p1716404672474459?thread_ts=1716202725.599559&cid=C05R2V5GM1S

**Comment by iwiznia** [comment]
>  the issue is that the lastReadTime is being returned twice, can you look into that?

@muttmuure thinking about this I think it's better to open a separate issue for it, since it's something the server returns and thus needs to be internal.

**Comment by MrMuzyk** [comment]
>Did you get the duplicated calls the first time you tried to reproduce it?

No, it was acting fine yesterday as well. Not sure why it was happening for a brief period of time.

>the issue is that the lastReadTime is being returned twice, can you look into that?

Yes, I've debugged it a bit more yesterday and came to the conclusion that the fact that same object is returned twice in the response is weird and should be looked into. It might be related to similar issue that Edu is investigating - gap in between onyx updates. It might give us some answers why is that the case that `GetMissingOnyxUpdates` is always called right after ReadNewestAction.

The cause of the duplicated object inside the response is however on the BE side. Would you be so kind and look into this method on your end and check if everything is fine over there? This might lead us somewhere as there is something weird going on here but I can't put my finger on it looking only at the FE part.

**Comment by muttmuure** [comment]
Can't we just make this one internal?

**Comment by iwiznia** [comment]
Going to take a look at this today (probably)

**Comment by muttmuure** [comment]
This is merged. Great job Ioni!
