### ISSUE TITLE
Whisper message notification sent to other members when a new member joins

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715964357862879

## Action Performed:

Prerequisite: Set room push notifications to immediate

1. User A creates a public room in a workspace chat
2. User B (iOS) joins the room
3. User C joins the room

## Expected Result:
No whisper notification for user A and B

## Actual Result:
Push notification received for user A and B
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/Expensify/App/assets/38435837/bf568152-dbe1-46fe-b2a3-a23842f38029" width="40%" height="40%">
<img src="https://github.com/Expensify/App/assets/38435837/a9b16a30-ba03-40b1-b3c8-bd9392d70664" width="40%" height="40%">
<img src="https://github.com/Expensify/App/assets/38435837/55b14017-42bb-418d-b50b-76edc5773ece" width="40%" height="40%">
Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0be0badd692dcec</li>
        <li>Upwork Job ID: 1792575924894093312</li>
        <li>Last Price Increase: 2024-05-20</li>
    </ul>
</details>

**Comment by arosiclair** [comment]
I have some changes prepped but they're held on a refactor for https://github.com/Expensify/Expensify/issues/381189 and also the merge freeze

**Comment by zanyrenney** [comment]
I think the merge freeze is over right, @arosiclair ?

**Comment by arosiclair** [comment]
Doesn't look like it to me 😕

**Comment by zanyrenney** [comment]
You're right, sorry that was wrong from me! @arosiclair

**Comment by zanyrenney** [comment]
Hey there! I am going OOO until the 9th of June. Please can you handle this and I will take it back once I return? Thanks!

**Comment by arosiclair** [comment]
Web-E PR is off hold and out for review. Unassigning the C+ since none is needed for this.

**Comment by arosiclair** [comment]
This hit [prod](https://github.com/Expensify/Web-Expensify/pull/42075#issuecomment-2137800439) so we're all done here
