### ISSUE TITLE
[$250] [CRITICAL] [P2P] Dynamically link the relevant agreement in the Wallet KYC based on user's card program

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#42400]
We need to show the user one of two different Wallet Agreements on the Terms and Fees page. Based on their state, we determine what program they're in (Bancorp or MTL), and then link to the appropriate page:
* MTL - https://use.expensify.com/expensify-payments-wallet-terms-of-service
* Bancorp - https://use.expensify.com/bancorp-bank-wallet-terms-of-service

----

Coming from [here in E/E](https://github.com/Expensify/Expensify/issues/382704) which came from [here in E/E](https://github.com/Expensify/App/issues/36648#issuecomment-2119846425)

@rafecolton , few bits:

1. Can you update the OP with whatever's needed? 
2. Is there just one final PR that @koko57 is going to work on? 
3. `NewFeature` adds a C+ to review, please unassign if not needed.  (I've assigned myself as the BZ)

@koko57 , can you plz comment so I can assign to you?  Thx

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7072f85ba721b58</li>
        <li>Upwork Job ID: 1792625841464729600</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by rafecolton** [comment]
Added some detail to the OP. I don't know if there's going to be more than one "final PR" but this change is small so I doubt it will span multiple PRs. 

> `NewFeature` adds a C+ to review

We'll need somebody to review the PR but we don't need somebody to review the feature request itself. Not sure if that means it needs to the label or not, so LMK.

**Comment by koko57** [comment]
Commenting for being assigned

**Comment by mallenexpensify** [comment]
Thx @koko57 , assigned. 
@rafecolton , I added `External` to assign a C+ to review the PR.  👋 @shubham1206agra 

We should be all set here.

**Comment by dannymcclain** [comment]
Sorry for the potentially silly question, but where does this link show up? I see in the issue description it says "on the Terms and Fees page" but the PR screenshots are of a few different screens (that do not mention terms or fees at all).

**Comment by mountiny** [comment]
Pujan is handling the PR review

**Comment by rafecolton** [comment]
PR is under review still. Marking this reviewing so it does not go overdue

**Comment by koko57** [comment]
PR still under review

**Comment by rafecolton** [comment]
Looks like the PR was merged and deployed to production. What remains to close this issue?

**Comment by mallenexpensify** [comment]
I'm a lil confused here. 
- https://github.com/Expensify/App/pull/42589

the above PR appears to be the one for here but it links to https://github.com/Expensify/App/issues/36648 for the Linked Issue. And in that issue I posted
> @koko57 can you plz comment on the E/App issue I created for/from the E/E issue so I can assign to you? thx

@Pujan92 are you due compensation here? If so, can you link to the PR?  Thx

**Comment by rafecolton** [comment]
> No, I think the payment will be handled within this [issue](https://github.com/Expensify/App/issues/36648).

I can confirm as well. This issue (https://github.com/Expensify/App/issues/42400) is very minor, so it was trivial to incorporate into the work for https://github.com/Expensify/App/issues/36648. The PR you linked @mallenexpensify should cover both.

**Comment by rafecolton** [comment]
Not overdue. @mallenexpensify forgive my ignorance, what steps remain to close this issue? I see the PR was deployed to production two weeks ago

**Comment by mallenexpensify** [comment]
We can close. This issue was a bit wonky, wanted to make sure contributor's weren't due payment.
