### ISSUE TITLE
[HOLD for payment 2024-06-13] [LOW] [Performance] Add no-spread-in-reduce to avoid recreating array in reduce method

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42414]
### Problem
When you use the spread operator in an array reduce, it often leads to a partial object being copied over and over again in a loop.
```
// BAD
const reducedObject = myArray.reduce(
    (acc, key) => ({
        ...acc,
        [key]: someOtherObject[key],
    }),
    {},
);
```

Especially with large objects, this is very inefficient because ...acc will unnecessarily copy the full object on each iteration, rather than just adding the single key we want to add.

### Solution
Prohibit this pattern with a new ESLint rule - no-spread-in-reduce. The above example would result in a lint error, and you might fix it with something more simple and efficient, like this:

```
GOOD
const reducedObject = myArray.reduce(
    (acc, key) => {
        acc[key] = someOtherObject[key];
        return acc;
    },
    {},
)
```
@kacper-mikolajczak 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011102640f041d624c</li>
        <li>Upwork Job ID: 1792878366584131584</li>
        <li>Last Price Increase: 2024-05-21</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by kacper-mikolajczak** [comment]
Hi @mountiny

**Comment by lirbank** [comment]
Just to double check, is task to create a ESLint rule to catch spread in reducers?

**Comment by mountiny** [comment]
@lirbank Hello! The task will be handled by @kacper-mikolajczak (no `Help Wanted` label on the issue)

However, the scope is to add the lint rule and fix all the places where its currently broken

**Comment by DylanDylann** [comment]
Not overdue, we are waiting for PR to be ready for review

**Comment by garrettmknight** [comment]
@DylanDylann you've been paid out - no regression test for this one.
