### ISSUE TITLE
Load the feature flags when visiting any page in the workspace settings

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42419]
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1716272473676819).

### Problem

If user visits a workspace settings for a policy:
- that was created before we started to add the feature flags
- this policy is not their default policy

We treat all the feature flags as not defined (as they are not set for this policy in the database).

### Solution

Make sure we are loading the flags based on their defaults as we do in the [Policy::getAsOnyxUpdate](https://github.com/Expensify/Auth/blob/a0c442c789267d5f6dca7ddc5fd69aaca5e7d4ca/auth/lib/Policy.cpp#L3503-L3597) when user visits any of the workspace settings pages.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01daa96864aabb5c08</li>
        <li>Upwork Job ID: 1792905820505821184</li>
        <li>Last Price Increase: 2024-05-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by mountiny** [comment]
did not get around to this

**Comment by mountiny** [comment]
Still on my list for this week

**Comment by mountiny** [comment]
Will work on this tomorrow

**Comment by laurenreidexpensify** [comment]
@mountiny bump - is this one still being worked on this week?

**Comment by laurenreidexpensify** [comment]
@mountiny looks like automation failed on this - are we waiting on any outstanding payments here or was this all internal? thanks

**Comment by laurenreidexpensify** [comment]
I don't see any external contributors on https://github.com/Expensify/Auth/pull/11083 so am closing. If this needs payemnt please reopen and re-add Bug label. Thanks

**Comment by mountiny** [comment]
There is also this issue actually which ended up having same solution so we can close this https://github.com/Expensify/App/issues/41914
