### ISSUE TITLE
[HIGH] Report not found error when the individual receiver opens the invoice room after the sender workspace deletion

### ISSUE THREAD

**Issue by cristipaval** [Expensify/App#42412]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. [user A] Send an invoice to user B
2. [user B] Open the invoice room
3. [user A] Deletes a workspace that has been used for the invoice
4. [user B] Refresh the page to invoke the “Open Report” command
5. [user B] Gets the error

## Expected Result:
The invoice rooms should be shown as archived to the user B

## Actual Result:
- no Onyx update is sent to user B to update the room
- the `OpenReport` command fails for user B

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a9888f9671d55e0</li>
        <li>Upwork Job ID: 1792854552424927232</li>
        <li>Last Price Increase: 2024-05-21</li>
    </ul>
</details>

**Comment by cristipaval** [comment]
Dealing with the criticals first

**Comment by cristipaval** [comment]
I'm still dealing with criticals

**Comment by greg-schroeder** [comment]
Thanks @cristipaval! Will leave at `Weekly` for now then

**Comment by greg-schroeder** [comment]
Any thoughts on a timeline here @cristipaval?

**Comment by cristipaval** [comment]
I'm ooo until next week

**Comment by greg-schroeder** [comment]
Got it, thanks for the update

**Comment by cristipaval** [comment]
Still working on critical issues. Also got auto-assigned to a #newdot-quality issue that has priority over anything else in my K2

**Comment by cristipaval** [comment]
I'm still working on higher priority issues.

**Comment by cristipaval** [comment]
Haven't had time for this one

**Comment by cristipaval** [comment]
I managed to investigate this one a bit, but then I had to jump again into other issues with higher priority. What I found out so far is that the `OpenReport` command does not return the `reportSummary` from Auth, and thus Web-E throws [here](https://github.com/Expensify/Web-Expensify/blob/221cb9688d07010ffbff7129eedc9fbde05cacf3/lib/ReportAPI.php#L5650-L5653).

**Comment by greg-schroeder** [comment]
Thanks for the update @cristipaval - seems we're still in the same general spot here

**Comment by cristipaval** [comment]
I hope I'll be able to work on this before EOW

**Comment by cristipaval** [comment]
I'll investigate this one later today.

**Comment by cristipaval** [comment]
Ok, so it seems that the invoice room shows as archived in the last App version. The issue now is that the receiver gets **Report Not Found** error when trying to access it.

**Comment by cristipaval** [comment]
^Auth PR up for review. The issue will be fixed once the PR hits production.

**Comment by cristipaval** [comment]
This should be fixed now
