### ISSUE TITLE
Tag - RBR isn't showing if the same tag is added online and offline with a different account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42428]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions: Be the owner of a Collect workspace with expensifail account (A). Invite another expensifail abbount (B) and make it an admin
1. Account A: Log in
2. Account A: Enable tags from the workspace settings
3. Account B: Log in on a different device
4. Account B: Navigate to workspace settings - Tags
5. Account B: Go offline
6. Account B: Add a new tag
7. Account A: Add the tag account B added offline
8. Account B: Go online
9. Account B: Navigate to workspace settings - Tags

## Expected Result:
Workspace Tags tab and the tag added offline should have an RBR for account B

## Actual Result:
Workspace Tags tab and the tag added offline isn't displaying an RBR

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fd93f8d5-b07a-466c-9a4f-32ed9a23b3cf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by anmurali** [comment]
Are we sure there should be an RBR in this case? Wouldn't Account B just try to commit the tag and see that it exists and just fail elegantly? @luacmartins - can you take a look and tell me what you think?

**Comment by luacmartins** [comment]
I agree that we don't need RBR in this case. The 2nd call to create the tag succeeds because the tag already exists in the policy. Gonna close this issue.
