### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Payment card / Subscription] Integrate failed billing scenarios banner with backend data

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42431]
[Design doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#heading=h.mnjguil21u0a)

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Not overdue

**Comment by pasyukevich** [comment]
Today's updates - WIP,  implementing utils file to  handle all  predefined error cases

**Comment by pasyukevich** [comment]
Today's updates - WIP, implementing utils file to handle all predefined error cases

**Comment by pasyukevich** [comment]
Today's updates - WIP, still implementing utils file to handle all predefined error cases

**Comment by amyevans** [comment]
Just cross-posting from [here](https://github.com/Expensify/App/pull/43029#issuecomment-2151988687) so that the message does not get lost: let's ensure to include the RBR implementation for when switching between plans is disallowed (failed `UpdateSubscriptionType` API command) in this PR

**Comment by pasyukevich** [comment]
Today's updates - WIP, Utils file is mostly  done, remained - to glue logic with buttons, add error cases from  failed API commands

**Comment by pasyukevich** [comment]
For the next two weeks I will be OOO, on Monday will be decided who will continue to work on this task

**Comment by amyevans** [comment]
Reassigning to @blimpich since I'm headed out on extended leave after today

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by neil-marcellini** [comment]
Coming from the PR review and without reading the whole doc, it's really hard to know what the P/S is of this issue. What does it mean to integrate with backend data @blimpich?

**Comment by blimpich** [comment]
Basically there's a bunch of different failure states that can happen with the payment card and there is a decision-tree-like logic to how the UI should look based on the combination of data from the backend.

We parallelized the work for this project so that the frontend didn't have to wait for the backend apis to exist before getting merged, but that left us with the cleanup work of gluing the frontend to the backend once both were in place.

Though I'm confused as to why you got pullerBear-ed, I think we should have a C+ review this before any Expensify engineer gets into it.

**Comment by blimpich** [comment]
Adding @mananjadhav as they'll be the C+ reviewing the PR

**Comment by MrMuzyk** [comment]
>Coming from the PR review and without reading the whole doc, it's really hard to know what the P/S is of this issue. What does it mean to integrate with backend data @blimpich?

The title is also a bit misleading, it's not only integrating with backend (making actual API call). Scope also includes adding this `Retry payment` button as it's not present yet

**Comment by mananjadhav** [comment]
Reviewed the PR again sometime back.

**Comment by trjExpensify** [comment]
PR merged yesterday, adding labels to get a BZ assigned.

**Comment by miljakljajic** [comment]
We pay you in ND right @mananjadhav ? So just a payment summary be due for this one on the 17th?

**Comment by mananjadhav** [comment]
Yes @miljakljajic that's right.

**Comment by miljakljajic** [comment]
Thank you!

**Comment by miljakljajic** [comment]
I'm going to submit the payment summary today as I'm OOO tomorrow - please don't request payment until tomorrow:

@mananjadhav is owed 250 USD for their work reviewing this issue

**Comment by mananjadhav** [comment]
This is supposed to be paid out today, hence I am going to request based on this [comment](https://github.com/Expensify/App/issues/42431#issuecomment-2227925225).

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by mananjadhav** [comment]
This is already paid out, should be closed.

**Comment by trjExpensify** [comment]
I'll go ahead and close it. Regression tests should be handled centrally for the project.
