### ISSUE TITLE
Subject line is wrong in the email when paying an IOU

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dannymcclain 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716242366636859

## Action Performed:
1. User A request money from user B
2. User B paying the IOU request
3. Observe the email received for user A

## Expected Result:
Subject line should say "user B paid you $x.xx elsewhere (depending on method of payment)

## Actual Result:
Subject line says "You paid user A $x.xx elsewhere (depending on method of payment)
NOTE: The content inside the email looks correct
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Frame 2242](https://github.com/Expensify/App/assets/38435837/4c1132ac-84bc-47c1-bd73-eeae921be770)

![Snip - You paid +- Admin CA$50 00 elsewhere - applausetester@applause expensifail com - Expensif](https://github.com/Expensify/App/assets/38435837/3efcec54-3600-45d7-8391-ba1b19c3cd32)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by blimpich** [comment]
Dupe: https://github.com/Expensify/Expensify/issues/399463
