### ISSUE TITLE
[HOLD for payment 2024-06-20] [Payment card / Subscription] Implement billing banner (UI)

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42430]
[Design doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#heading=h.mnjguil21u0a)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Not overdue

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JUNE 20

- Fix: @pasyukevich - Callstack - no payment required
- PR Review: @mananjadhav [$250] payment via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
