### ISSUE TITLE
[HOLD for payment 2024-06-06] Hold is incorrectly lowercase in the dot separator pattern

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42437]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716249633077769

## Action Performed:
1. Submit an expense from user A to user B
2. As user B put the expense on hold
3. As user A open the expense which was put on hold 

## Expected Result:
The dot separator pattern should say Cash * Hold
## Actual Result:
The dot separator pattern should say Cash * hold
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-05-20 at 17 58 22@2x](https://github.com/Expensify/App/assets/38435837/4bd37fc7-a947-403f-ac59-0858035798d4)

![Snip - (24) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/1ad26070-2d3e-45c6-ad92-0c10c5f2b252)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by rlinoz** [comment]
Not a blocker, will take a look shortly though.

**Comment by rlinoz** [comment]
Opening a PR today.

**Comment by bfitzexpensify** [comment]
Adding a BZ buddy for payment - I will be OOO until June 11th

**Comment by bfitzexpensify** [comment]
Wait, actually, this was all internal, so we can just close this out.
