### ISSUE TITLE
Profile - Address dropdown returns 'No results found' after language switch

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42436]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing issue** https://github.com/Expensify/Expensify/issues/299728
Preconditions: user is logged to app on two devices.

1. Go to Profile > Private > Address
2. In the Address Line 1, type any initial search say (123, Polar) and wait for the results to appear
3. Keep the dropdown/form open in the current device
4. On a second device, change the language (Preferences > Language)

## Expected Result:
On the first device, the list of addresses gets updated with the newly selected language

## Actual Result:
On the first device, the list of addresses gets 'No results found'.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0be4e71f-312e-4ac9-8949-594ff704403e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment]
This seems pretty edge case to me - I can only reproduce if I make a language switch from a different while I'm mid action
