### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] [Payment card / Subscription] Integrate Retry billing button with backend data

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42434]
[Design doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit)

<details><summary>Issue Owner</summary>Current Issue Owner: @MrMuzyk</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011654f2b733a74a09</li>
        <li>Upwork Job ID: 1805295362253827219</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

**Comment by web-cloudy** [comment]
Hi
Could you give me access?

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - an expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Not overdue

**Comment by amyevans** [comment]
Reassigning to @blimpich since I'm headed out on extended leave after today

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by trjExpensify** [comment]
Bumped this to `Daily` priority as we can work on it. :)

**Comment by MrMuzyk** [comment]
I'm still implementing it. It is somewhat blocked by https://github.com/Expensify/App/issues/42431 (need some utils, translations, updated components from there) but I've rebased with WIP that Julian is working on atm and Im doing what I can for now.

Tomorrow Im OOO and I will get back to it on friday. Hopefully by then #42431 will get merged and I will be fully unblocked

**Comment by MrMuzyk** [comment]
I've implemented what I can for now and left some questions on slack regarding the server response and happy path. PR will most likely be up on monday/tuesday

**Comment by blimpich** [comment]
[Brought discussion to slack](https://expensify.slack.com/archives/C036QM0SLJK/p1718993689192489).

**Comment by MrMuzyk** [comment]
Draft is up. Diff is much bigger than it will be once PR that is blocking me gets merged.

**Comment by blimpich** [comment]
Marking this as external so that the GH automations work correctly when the PR is opened for review.

**Comment by MrMuzyk** [comment]
Still blocked but I've made same progress. I'm also making sure that PR that blocks me has everything I need and I'm ready for these changes on my end

**Comment by MrMuzyk** [comment]
Still blocked but keeping my draft up to date with dependant PR

**Comment by MrMuzyk** [comment]
Still blocked, tomorrow Im OOO so I will get back to it on monday. Hopefully I will be unblocked by then

**Comment by MrMuzyk** [comment]
Rebased draft PR. Still blocked

**Comment by zanyrenney** [comment]
### Payment Summary
[Upwork Job](https://www.upwork.com/jobs/~011654f2b733a74a09)
- Contributor: @MrMuzyk is from an agency-contributor and not due payment
- Reviewer: @allroundexperts owed $250 via NewDot - please request via ND.

**Comment by mananjadhav** [comment]
@zanyrenney I think we wrongly tagged @allroundexperts here for the payout. This needs to be paid out to me, as I reviewed the PR.

**Comment by zanyrenney** [comment]
Contributor: @MrMuzyk is from an agency-contributor and not due payment
Reviewer: @mananjadhav owed $250 via NewDot - please request via ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
