### ISSUE TITLE
[Payment card / Subscription] Implement - Integrate 3ds flow with Backend data

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42433]
[Design doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#heading=h.mnjguil21u0a)

<details><summary>Issue Owner</summary>Current Issue Owner: @waterim</details>

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - an expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Not yet ready for work

**Comment by amyevans** [comment]
Reassigning to @blimpich since I'm headed out on extended leave after today

**Comment by trjExpensify** [comment]
@waterim you're combining this issue with https://github.com/Expensify/App/issues/42432 right? Can you comment so we can assign you here to track.

**Comment by waterim** [comment]
Hello, yes, Im combining this issue with UI issue!

**Comment by blimpich** [comment]
Add @Pujan92 as they are reviewing the PR

**Comment by trjExpensify** [comment]
Shall we just close this issue, as we're building it in one PR and we can use this issue: https://github.com/Expensify/App/issues/42432

**Comment by blimpich** [comment]
Yes, lets do that for sake of simplicity.
