### ISSUE TITLE
[HOLD for payment 2024-08-02] [Payment card / Subscription] Implement 3ds flow (UI)

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42432]
[Design doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#heading=h.mnjguil21u0a)

<details><summary>Issue Owner</summary>Current Issue Owner: @waterim</details>

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - an expert agency - and I would like to work on this issue.

**Comment by amyevans** [comment]
Not overdue

**Comment by trjExpensify** [comment]
Artem is taking this one on. We'll assign him when he comments: https://expensify.slack.com/archives/C036QM0SLJK/p1717771976371449?thread_ts=1717422320.931359&cid=C036QM0SLJK

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by waterim** [comment]
Hello guys!
I have one question regarding the 3ds flow, do I need to add in this PR only the UI part or its better to wait for a backend API command "AddPaymentCardGBP" as its already under the review and handle here both UI and API connection?

**Comment by amyevans** [comment]
I think it's fine to combine the UI and API integration into 1 PR, def makes the most sense.

Just to set expectations on the AddPaymentCardGBP command, the PR is still under review, so I'd anticipate it being available for consumption on staging not until early next week. Although if you want to stay unblocked you can develop against the `User_SetupBillingCard` API command of the _secure_ API (`secure.expensify.com`; I think you can use the `shouldUseSecure` param on the request) or against AddPaymentCardGBP in my local backend via ngrok.

**Comment by waterim** [comment]
My update:
Created new function for a new API command, created modal, didn't test it well as Im waiting for a backend real stripe link
if backend will be pushed as planned on Monday/Thuesday my ETA for open PR will be 1 working day (if no issues will come up)

**Comment by amyevans** [comment]
Reassigning to @blimpich since I'm headed out on extended leave after today

**Comment by blimpich** [comment]
Not overdue, backend PRs are still in review, waiting on those.

**Comment by blimpich** [comment]
Backend Auth PR is merged, waiting on Web PR, once both of those are merged and deployed we'll be able to do the frontend work for this and test it end to end. I think this'll happen sometime either tomorrow or Thursday.

**Comment by Pujan92** [comment]
@amyevans Plz provide access to the [design doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit#heading=h.mnjguil21u0a), I just requested.

**Comment by blimpich** [comment]
@Pujan92 just shared it with you, @amyevans is on maternity leave, I'm internal Expensify engineer leading the project now. Feel free to ask me any questions about it 🙂

**Comment by blimpich** [comment]
Add @Pujan92 as they are reviewing the PR

**Comment by blimpich** [comment]
Quiet melvin, we are working on it.

**Comment by JmillsExpensify** [comment]
$250 approved for @Pujan92 based on confirmed summary above.
