### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250] LHN - Thread chat with violation is not removed from LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/Expensify/issues/298967
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: User B sends a message to User A
The below step is for User A

1. Press "Reply in thread" of the message sent by B
2. Send any message in the thread
3. New thread on LHN appears
4. Go back to the chat with B
5. Flag B's message as Harassment/Assault

## Expected Result:
The message is removed
The thread chat on LHN is removed

## Actual Result:
The message is removed
The thread chat on LHN is not removed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7872efa8-5b43-461f-97f3-bcf08f82ee80

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01075ae0b1e467403c</li>
        <li>Upwork Job ID: 1794837297031409664</li>
        <li>Last Price Increase: 2024-05-26</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102499543</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by MitchExpensify** [comment]
Reminder set to pay - Do we need BZ steps here @thesahindia ?

**Comment by MitchExpensify** [comment]
*Payment summary*:

- $250 @thesahindia requires payment through NewDot Manual Requests
- $250 @tienifr requires payment through NewDot Manual Requests

Bump on BZ steps @thesahindia 🙇

**Comment by MitchExpensify** [comment]
Cool, we can close this as its all via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @tienifr

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
