### ISSUE TITLE
[CRITICAL] workspace rooms title appear as `hidden`

### ISSUE THREAD

**Issue by davidcardoza** [Expensify/App#42448]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:** https://expensify.slack.com/archives/CSL3XBCCR/p1716319598170419

## Action Performed:
1. Send an invoice to user
2. Open the invoice room
3. Review the LHN for the room title
4. Room title shows as hidden

## Expected Result:
The invoice room should show the invoiceReceiver's display name. 

## Actual Result:
The room is titled as `hidden`

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/6643649/cf9d11c9-e00b-49f3-ac56-359974447f5b

![image](https://github.com/Expensify/App/assets/6643649/92ff400c-59b0-41a9-b8a3-93ccc5a0b893)

![image](https://github.com/Expensify/App/assets/6643649/4917b11e-3170-4c74-8c06-85f9f2703268)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013db2030a903ab4f2</li>
        <li>Upwork Job ID: 1793123274155372544</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

**Comment by cristipaval** [comment]
I'll look into this one on Monday.

**Comment by cristipaval** [comment]
I'll start on this one today

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by cristipaval** [comment]
^Fix PR up, ready for review

**Comment by cristipaval** [comment]
This is in prod now. No payment needed here.
