### ISSUE TITLE
[HIGH] Emails not delivering to invoice receivers

### ISSUE THREAD

**Issue by davidcardoza** [Expensify/App#42451]
Held on https://github.com/Expensify/App/issues/34167

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Login to demo account jagwarma1@gmail.com 
2. send invoice to darnellwilkins51@gmail.com
3. Wait for email to darnellwilkins51@gmail.com inbox, never login to newdot using the account
4. No email is delivered

## Expected Result:
An email should deliver with the invoice request

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<img width="1495" alt="image" src="https://github.com/Expensify/App/assets/6643649/ff97767b-d0f9-4ca7-b2dc-ea55d1cc0a9c">
<img width="1495" alt="image" src="https://github.com/Expensify/App/assets/6643649/2f9a339b-2fad-489f-9461-3d23fb4f43bd">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b97b9a9d867b8b4</li>
        <li>Upwork Job ID: 1793269140957732864</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

**Comment by davidcardoza** [comment]
@robertjchen and @techievivek fixed this overnight I believe, but let's reopen if it's still happening.

**Comment by cristipaval** [comment]
Reopening, this is still happening for the invoice reports sent via NewDot.

**Comment by davidcardoza** [comment]
Yes, thank you.

**Comment by cristipaval** [comment]
Phew, I finally have something:

![Image 25 05 2024 at 00 01](https://github.com/Expensify/App/assets/18078393/61f765c8-4a61-4e5a-9e5f-4f863ce1389c)

**Comment by cristipaval** [comment]
It was a challenge because, with the 1:1:1 initiative, I had to queue this notification from Auth. As you can see in the above screenshot, I still have to make tiny improvements. The PRs will be ready by Monday.

**Comment by cristipaval** [comment]
it will be ready for review today

**Comment by cristipaval** [comment]
[Web-E PR](https://github.com/Expensify/Web-Expensify/pull/42161) ready for review.
[Auth PR](https://github.com/Expensify/Auth/pull/11012) is held on the Web-E PR

**Comment by CortneyOfstad** [comment]
Not overdue as the PR is ready for review!

CC @mollfpr

**Comment by cristipaval** [comment]
The PRs are actually on hold.

I'm trying to get [here](https://expensify.slack.com/archives/C03U7DCU4/p1717074942694999) a consensus on how the email notifications should work for expense and invoice reports linked to workspace chats/invoice rooms.

**Comment by cristipaval** [comment]
Held on https://github.com/Expensify/App/issues/34167

**Comment by CortneyOfstad** [comment]
Thanks @cristipaval!

**Comment by CortneyOfstad** [comment]
Updated this to weekly to match the on-hold issue!

**Comment by cristipaval** [comment]
Still held

**Comment by CortneyOfstad** [comment]
[PR](https://github.com/Expensify/Web-Expensify/pull/42416) is up!

**Comment by davidcardoza** [comment]
I am very excited for this!

**Comment by davidcardoza** [comment]
Any update on this issue?

**Comment by CortneyOfstad** [comment]
PR was deployed to staging 9 hours ago 🎉

**Comment by cristipaval** [comment]
That is the PR that this issue was held on. I've been busy getting a #wave-control urgent design doc out the door. I hope I'll get back to this issue tomorrow in the afternoon 🤞

**Comment by CortneyOfstad** [comment]
@cristipaval any update on this? Thanks!

**Comment by cristipaval** [comment]
Aiming to have the PRs ready for review at the end of today

**Comment by CortneyOfstad** [comment]
Thank you @cristipaval!

**Comment by cristipaval** [comment]
The PRs are ready for review. BUT the intro is not yet added to the email when the first invoice is sent. I need some time to implement it the right way, and I don't have that time now unfortunately.

**Comment by CortneyOfstad** [comment]
No worries and thank you @cristipaval! Just a heads up, I am OoO until Tuesday (July 9th) but if anything pops up in the meantime, feel free to add the **bug** label so there is no delay. Thanks!

**Comment by cristipaval** [comment]
PR is still in review.

**Comment by CortneyOfstad** [comment]
Thanks Cristi!

**Comment by cristipaval** [comment]
I got some change requests on the Web-E PR. I'll do my best to address them asap.

**Comment by CortneyOfstad** [comment]
@cristipaval any update? Thank you!

**Comment by cristipaval** [comment]
I just addressed the feedback on the Web-E PR and made it ready for review again

**Comment by cristipaval** [comment]
I addressed the feedback on the PR. Waiting for the review.

**Comment by cristipaval** [comment]
I just resolved the conflicts on the PR. Waiting for the reviewer

**Comment by cristipaval** [comment]
The PR is finally merged.

**Comment by cristipaval** [comment]
[The PR](https://github.com/Expensify/Web-Expensify/pull/42161) is in staging

**Comment by cristipaval** [comment]
The PR is in staging. There are some UI/UX improvements needed, but that might be more of a MEDIUM/LOW follow-up issue.

**Comment by cristipaval** [comment]
Closing because it hit production. I'll put in [this issue](https://github.com/Expensify/App/issues/46731) the UI/UX improvements that need to be done.
