### ISSUE TITLE
[Wave Collect] [Xero] Make the toggle for requiring categories enabled when connected

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42457]
Xero is connected but the toggle for requiring categories is disabled. It should be enabled (QBO is correct).
 
 Video:

https://github.com/Expensify/App/assets/21549771/6f149e53-6d1a-40c8-ba27-a3bb66c9c7e3

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01380d59e6dd1ba354</li>
        <li>Upwork Job ID: 1793283201669287936</li>
        <li>Last Price Increase: 2024-05-22</li>
    </ul>
</details>

**Comment by hungvu193** [comment]
I'll work on this one 😄

**Comment by hungvu193** [comment]
@trjExpensify Can you reproduce this one?

**Comment by trjExpensify** [comment]
I can give it a go, we can chat here: https://expensify.slack.com/archives/C036QM0SLJK/p1716374148109909?thread_ts=1716238514.357639&cid=C036QM0SLJK

**Comment by trjExpensify** [comment]
Same result, commented in the thread.

**Comment by lakchote** [comment]
Unassigning @hungvu193 as this needs BE changes.

Will raise a PR.

**Comment by lakchote** [comment]
Closing, dupe of https://github.com/Expensify/Expensify/issues/397238.
