### ISSUE TITLE
[HOLD for payment 2024-06-11] [Wave Collect] [Xero] Clean-up the educational messages when connected to QBO/Xero

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42456]
1. The `Categories`, `Tags` and `Taxes` pages should all have a message that links to `Accounting` page to manage the integration settings atop the page.
a. Xero: All three are incorrect: `Categories` displays the `QBO` message, `Tags` and `Taxes` are missing.
b. QBO: The message is there for `Categories` and `Tags` pages, but missing from the `Taxes` page.

![image](https://github.com/Expensify/App/assets/21549771/697b62be-b74b-4677-8b34-1821abf550d9)

2. The `Organize` card in `More features` should contain a message at the bottom explaining that these features are managed via the integration when connected to an accounting solution and link to `Accounting`. This is missing when connected to both QBO and Xero.

<img width="304" alt="image" src="https://github.com/Expensify/App/assets/16232057/2939b1fd-f489-4c9e-b722-aec3c9371fce">

**Comment by mananjadhav** [comment]
I'll pick this.

**Comment by trjExpensify** [comment]
This part of 1a will be taken care of here: https://github.com/Expensify/App/issues/42458

>Categories displays the QBO message

**Comment by mananjadhav** [comment]
Raised a few questions. https://expensify.slack.com/archives/C036QM0SLJK/p1716399648958649?thread_ts=1716238514.357639&cid=C036QM0SLJK

**Comment by trjExpensify** [comment]
Responded!

**Comment by abekkala** [comment]
@lakchote Can you gut check me that _only_ @mananjadhav requires payment for this one? (according to Melvin)

I'm not sure why melvin only notes them. If I'm looking at the correct PR for this it seems like s77rt was the Reviewer (not mananjadhav) and they are actually the contributor who created the fix?!

Can I confirm that the payments are actually: 

**FIX:** @mananjadhav [$250]
**PR Review:** s77rt [$250] (I don't know why they are not assigned to this issue as they would _appear_ to be the PR Reviewer) 🤷🏼‍♀️

**Comment by mananjadhav** [comment]
@abekkala No payout for me and @hungvu193. Ours is handled centrally as a flat fee.

There would be a payout for @s77rt for reviewing the PR.

**Comment by abekkala** [comment]
### PAYMENT SUMMARY: 

- **Fix:** @mananjadhav , @hungvu193 - no Upwork payment required. 
- **PR Review:** @s77rt [$250]

**Comment by s77rt** [comment]
@abekkala Accepted! Thanks!

**Comment by abekkala** [comment]
@s77rt payment sent and contract ended - thank you! 🎉
