### ISSUE TITLE
[HOLD for payment 2024-06-11] [Wave Collect] [Xero] Make the integration name in Categories dynamic

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42458]
Right now, in the `Categories` menu item of the LHN, on a policy connected to Xero it says this:

![image](https://github.com/Expensify/App/assets/21549771/2fc51a4d-4b6e-4aa2-a6ef-9953558250e2)

It should instead say:
`The categories below are imported from your Xero settings`. 

(make the integration name dynamic, use the current connected integration).

**Comment by hungvu193** [comment]
I got paid already. No payment needed here.
