### ISSUE TITLE
[HelpDot] Enforce redirects in PR

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#42460]
### Problem: 
Given the helpDot search is just a Google Search and we are kind of constantly moving links around, we are always going to have dead links.

### Solution: 
When an article or hub is moved/renamed/deleted, we should add a PR check to detect it and enforce that a redirect URL is added for the new links.

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by rushatgabhane** [comment]
Not overdue

**Comment by muttmuure** [comment]
Waiting for PR review
