### ISSUE TITLE
[HOLD for payment 2024-06-11] [Wave Collect] [Xero] Disable Taxes when connecting to QBO that doesn't enable Taxes by default

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42466]
We need to remove `Taxes` from the LHN when we're disconnecting from Xero and we had taxes sync enabled.

**Comment by mountiny** [comment]
@trjExpensify based on the comment this was not fully fixed, I think we need to find someone to look into this / retest and fix if its not done yet https://github.com/Expensify/App/pull/42467#issuecomment-2142992295

**Comment by trjExpensify** [comment]
Cool, I can retest after the next deploy.

**Comment by trjExpensify** [comment]
Can't repro this. Asking for a retest.

**Comment by trjExpensify** [comment]
Still waiting for a retest. CC: @mvtglobally @m-natarajan

**Comment by lakchote** [comment]
@mvtglobally @m-natarajan can you please retest as per @trjExpensify's [comment](https://github.com/Expensify/App/issues/42466#issuecomment-2175617512) above ?

**Comment by kbecciv** [comment]
By following steps from https://github.com/Expensify/App/issues/42466#issuecomment-2147590323 - Taxes are enabled when connecting to QBO

https://github.com/Expensify/App/assets/93399543/09dedcc9-f6b0-4217-8646-1bf2f9eb12ce

**Comment by lakchote** [comment]
> #42466 (comment)

I found the culprit, and pushed a PR to fix it [here](https://github.com/Expensify/App/pull/44736)

cc @trjExpensify once you'll see why we weren't seeing the bug... ah 😄

**Comment by trjExpensify** [comment]
Dang, nice sleuthing!

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests.

**Comment by lakchote** [comment]
> Fix disconnect QBO on native devices #44952

[PR](https://github.com/Expensify/App/pull/44952) to fix this is up for review.

**Comment by allroundexperts** [comment]
Comment for assignment

**Comment by bondydaa** [comment]
assigned @allroundexperts since they're helping to test the PR https://github.com/Expensify/App/pull/44952

**Comment by trjExpensify** [comment]
The regression period is over on this. Confirming payment summary as follows:

- $250 to @allroundexperts for the C+ review

Go ahead and request! Closing.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
