### ISSUE TITLE
[HOLD for payment 2024-07-24] [Payment card / Subscription] [HOLD all] Rollout feature: replace Subscriptions menu item

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42473]
The `Subscriptions` menu item in the LHN of settings currently links out to OldDot.

Once the [Payment card and subscription management in NewDot](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8) design doc engineering work is complete, we need to update the menu item to link to the new NewDot route instead of OldDot.

**Comment by amyevans** [comment]
Not ready to launch yet

**Comment by JKobrynski** [comment]
I created a [related section](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.4e2ufrh4e609) in the doc! 

CC: @amyevans

**Comment by amyevans** [comment]
Nice, LGTM!

**Comment by blimpich** [comment]
@JKobrynski could you put up a PR for this? We're not quite ready but there's no reason to not have the PR ready to go when we finally do want it to be launched.

**Comment by trjExpensify** [comment]
I think we're only waiting on a prod deploy for the GBP PR from Friday to hit, looking at the latest deploy checklist on staging. I'd say let's put this on `Daily` priority at this point, we should aim to get it up and merged tomorrow. 👍

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @rayane-djouah for the C+ review 

Offer sent!

**Comment by trjExpensify** [comment]
Paid, closing!
