### ISSUE TITLE
[Payment card / Subscription] Implement UpdateSubscriptionAutoRenew API command

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42479]
Complete this backend section of the design doc: [Implement UpdateSubscriptionAutoRenew API command](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.xp21oj152xyb)

**Comment by rlinoz** [comment]
Picking it up, hopefully opening PRs by tomorrow.

**Comment by dangrous** [comment]
Oh shoot, you got here just before I clicked the button! Let me know if you need any help (or want to split up the PRs!)

**Comment by trjExpensify** [comment]
@dangrous what about this one maybs? [[Payment card / Subscription] Implement AddPaymentCardGBP API command](https://github.com/Expensify/App/issues/42478)?

**Comment by rlinoz** [comment]
PRs are up

**Comment by amyevans** [comment]
[Auth PR deployed to prod](https://github.com/Expensify/Auth/pull/11053#issuecomment-2144943268)

**Comment by amyevans** [comment]
[Web PR on staging](https://github.com/Expensify/Web-Expensify/pull/42189#issuecomment-2145826653)

**Comment by amyevans** [comment]
[Auth PR got reverted](https://github.com/Expensify/Auth/pull/11053#issuecomment-2147772422) when we rolled back, and we cherry-picked a revert of the web PR to fix failing integration tests

**Comment by rlinoz** [comment]
Unrevert PRs are up

**Comment by rlinoz** [comment]
Merged all the unreverts.

**Comment by rlinoz** [comment]
Deployed to prod: https://github.com/Expensify/Web-Expensify/pull/42266#issuecomment-2158969374
