### ISSUE TITLE
[HOLD #45289] [$250] Upgrade Expo and necessary packages

### ISSUE THREAD

**Issue by bondydaa** [Expensify/App#42475]
Coming from this PR https://github.com/Expensify/App/pull/42357

# Problem
There is a critical security fix released in Expo v`51.0.8`, we should update to this but need to do so in a way that doesn't break the entire app.

# Solution
Create a new PR / update https://github.com/Expensify/App/pull/42357 and test all flows using expo with the help of contributors and testers to ensure no breaking changes render the app unusable. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019dda01bf3f9b4520</li>
        <li>Upwork Job ID: 1793760958218575872</li>
        <li>Last Price Increase: 2024-05-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by bgawkuc** [comment]
@bondydaa Hi! I’m Barbara Gaweł-Kucab from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by bondydaa** [comment]
@ShridharGoel thanks for the note, we'll let you know if we need more testers to jump in. For now we're going to rely on SWM to help us with the majority of the lifting for now.

**Comment by bgawkuc** [comment]
After research, it turned out that `Expo` upgrade involves bumping up RN to 0.74. The [RN upgrade](https://github.com/Expensify/App/pull/40548) has started (draft PR [here](https://github.com/Expensify/App/pull/40548)), so the `Expo` issue is blocked - @bondydaa @hoangzinh @mountiny

**Comment by mountiny** [comment]
Alright, thanks, I will update the title to reflect that

**Comment by CortneyOfstad** [comment]
PR  [here](https://github.com/Expensify/App/pull/40548) is being actively worked on 👍

**Comment by CortneyOfstad** [comment]
PR is still being worked on!

**Comment by CortneyOfstad** [comment]
So the PR was closed in favor of the 0.75 update — @mountiny and @bondydaa (tagging you both since you commented on this GH). Do I keep this open for 0.75 and if so, is there something I can link to this for reference/tracking? The PR closure did not have anything and didn't want to close this without getting some additional context — thank you!

**Comment by bondydaa** [comment]
hm @roryabraham can you share any context on https://github.com/Expensify/App/pull/40548#issuecomment-2299302325?

**Comment by roryabraham** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1724060685267159?thread_ts=1721115769.712559&cid=C01GTK53T8Q

**Comment by CortneyOfstad** [comment]
On-hold issue is still on staging, so will continue to monitor!

**Comment by CortneyOfstad** [comment]
@roryabraham can you confirm if RN 0.75 has been deployed into production? From what I can see in https://github.com/Expensify/App/pull/45289 it appears to have been on staging for nearly a month, which may be normal, but wanted confirmation from a professional 😂 Thank you!

**Comment by roryabraham** [comment]
yep! Sorry we've had issues with release comments and other automations recently, but those should be fixed now. RN 0.75 has been on prod since 2024-08-28

**Comment by roryabraham** [comment]
agree
