### ISSUE TITLE
[Payment card / Subscription] Implement AddPaymentCardGBP API command

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42478]
Complete this backend section of the design doc: [Implement AddPaymentCardGBP API command](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.avnpevrmulmv)

**Comment by dangrous** [comment]
I can grab this! I will start now but likely won't finish until next Tue or Wed (I'm out Thu-Mon on parental leave still). If someone needs to take over for timing reasons, so be it! I'll try to keep my PRs in a good position

**Comment by amyevans** [comment]
Pushed some progress to the PR, will continue more tomorrow!

**Comment by amyevans** [comment]
Pushed progress to the Auth PR + a draft web PR. Will try to make some additional progress later tonight as well 🤞

**Comment by amyevans** [comment]
Left to do:
* Auth::createSetupIntent portion
* Auth::clearOutstandingBalance
* Automated test for SCA flow
* Clean up web PR

**Comment by amyevans** [comment]
Whew okay this one is definitely testing me 😅. Got the `Auth::createSetupIntent` portion done today, I found a bug in the existing 3DS setup logic so that threw me for a bit of a loop but figured it out.

It works locally end-to-end now for a user without a balance owed. But still need to handle these 3 pieces, hopefully all tomorrow:

- Auth::clearOutstandingBalance portion
- Automated test for SCA flow
- Clean up web PR

**Comment by amyevans** [comment]
`Auth::clearOutstandingBalance` portion is all set now I believe, so that leaves for tomorrow:
* Automated test for SCA flow (may take a few hours)
* Clean up web PR (should only take a few minutes)

I've been manually testing as I go and things look good but may want to do a little more there as well

**Comment by amyevans** [comment]
Got the Auth PR into review 🎉 

I also cleaned up the Web PR but still need to address error handling so it's still in a draft state, will handle that tomorrow

**Comment by amyevans** [comment]
Feedback addressed on Auth PR, still need to get back to Web PR tomorrow

**Comment by amyevans** [comment]
2 more rounds of feedback addressed on the Auth PR, and I got the Web PR in review. If there are any additional changes requested on either, @dangrous and @blimpich can fight over who gets to implement the changes 😄 Godspeed 🫡

**Comment by blimpich** [comment]
Auth PR and Web PR are merged, waiting deploy.

**Comment by dangrous** [comment]
Auth is deployed, Web is on staging

**Comment by dangrous** [comment]
Web is on prod as well! This should autoclose shortly, if not I can close it out tomorrow
