### ISSUE TITLE
[Payment card / Subscription] Implement UpdateSubscriptionType API command

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42481]
Complete this backend section of the design doc: [Implement UpdateSubscriptionType API command](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.3ofmuddf4blc)

**Comment by rlinoz** [comment]
Opening PRs today.

**Comment by amyevans** [comment]
Auth is on prod, web PR is on staging

**Comment by amyevans** [comment]
Web PR deployed to prod 🎉
