### ISSUE TITLE
[Payment card / Subscription] Implement UpdateBillingCardCurrency API command

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42484]
Complete this backend section of the design doc: [Implement UpdateBillingCardCurrency API command](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.if1b0g4l89mp)

**Comment by web-cloudy** [comment]
Hi,
I'm Pavlo
I’d like to work on this issue

**Comment by amyevans** [comment]
[Deployed to Web-Expensify/staging by neil](https://github.com/Expensify/Web-Expensify/pull/42203#issuecomment-2145826721)

**Comment by trjExpensify** [comment]
this is on prod now, can we close?

**Comment by amyevans** [comment]
Yup! 🙌
