### ISSUE TITLE
[Payment card / Subscription] Implement ClearOutstandingBalance API command

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42485]
Complete this backend section of the design doc: [Implement ClearOutstandingBalance API command](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.bdt8sxite5i)

**Comment by web-cloudy** [comment]
Hi, @amyevans 
How to read doc. Could you give me access?

**Comment by web-cloudy** [comment]
Contributor details
Your Expensify account email: nativedev124@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/pavlok48

**Comment by web-cloudy** [comment]
Hi, @amyevans
How to read doc. Could you give me access?

**Comment by amyevans** [comment]
The issues in this project aren't open for proposals, sorry @web-cloudy! You can take a look at available issues to work on in this repo by filtering to the `Help Wanted` label.

**Comment by arosiclair** [comment]
This looks pretty straight forward. I'll work on it!

**Comment by arosiclair** [comment]
I was going to add `Onyx::handleException` logic as described in the doc but I don't think this is necessary since we can just use success/failure data on the frontend.

Took a look at the [success](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.ha6pkejex3ep) and [failure](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.87foroxnj98j) handling for retry billing on the frontend and the design seems off to me. I don't think we need entirely new Onyx keys just to set a success/fail flag.

**Comment by amyevans** [comment]
> I was going to add Onyx::handleException logic as described in the doc but I don't think this is necessary since we can just use success/failure data on the frontend.

Hmm I think the errors being thrown though in this case do not get stored in an NVP for use, for example [this](https://github.com/Expensify/Auth/blob/main/auth/command/ClearOutstandingBalance.cpp#L80), right?

> Took a look at the [success](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.ha6pkejex3ep) and [failure](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.87foroxnj98j) handling for retry billing on the frontend and the design seems off to me. I don't think we need entirely new Onyx keys just to set a success/fail flag.

Yeah I think this was a late addition to the doc in response to feedback that success/failure should be stored in Onyx instead of just using the response from `ClearOutstandingBalance` 🤔 Do you have a suggestion of how best to implement it?

**Comment by arosiclair** [comment]
> Hmm I think the errors being thrown though in this case do not get stored in an NVP for use, for example [this](https://github.com/Expensify/Auth/blob/main/auth/command/ClearOutstandingBalance.cpp#L80), right?

Yeah that's true, but from the mockups it doesn't look like we actually use those error messages. We just show the same generic message on failure.

> Yeah I think this was a late addition to the doc in response to feedback that success/failure should be stored in Onyx instead of just using the response from ClearOutstandingBalance 🤔 Do you have a suggestion of how best to implement it?

Normally we would just set `errors` on the relevant Onyx key, but I'm not sure what it would be. Do we have a pattern for setting "success"? I can ask in `#engi-chat`

**Comment by arosiclair** [comment]
Asked about success/error handling Asked [here](https://expensify.slack.com/archives/C03TQ48KC/p1717080719341809). In the meantime, everything else for Web-E is done and no Auth changes are needed.

**Comment by arosiclair** [comment]
PR is in review

**Comment by amyevans** [comment]
Deployed
