### ISSUE TITLE
[Payment card / Subscription] Implement UpdateSubscriptionSize API command

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#42482]
Complete this backend section of the design doc: [Implement UpdateSubscriptionSize API command](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#bookmark=id.onobqhmloxac)

**Comment by blimpich** [comment]
Picking up

**Comment by blimpich** [comment]
**Updates:** 
- Put up draft PR of current progress with Auth changes.
- Commented [here](https://github.com/Expensify/Expensify/issues/367445#issuecomment-2138357944) on an ongoing issue related to subscription size, trying to get a better idea why the current `UpdateBillingSubscription` command is modifying the subscription type in certain circumstances.

**Comment by blimpich** [comment]
Asked in #engineering-chat about subscription size related question: https://expensify.slack.com/archives/C03TQ48KC/p1717091224831329

**Comment by blimpich** [comment]
**Daily Update:**
- got answer to question about modifying subscription type when updating subscription size ([link](https://expensify.slack.com/archives/C03TQ48KC/p1717096790664299?thread_ts=1717091224.831329&cid=C03TQ48KC))
- worked on tests for Auth PR, not quite ready for review, made good progress, think I'll get it up for review tomorrow

**Comment by blimpich** [comment]
**Daily Update:** [PR](https://github.com/Expensify/Auth/pull/11059) is up for review

**Comment by blimpich** [comment]
both PRs merged 🎉

**Comment by trjExpensify** [comment]
Web PR deployed to staging.

**Comment by amyevans** [comment]
Web PR deployed to prod, all set here 🎉
