### ISSUE TITLE
[HOLD for payment 2024-06-05] Existing policy expense chats are not being correctly found when inviting users to policies

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#42499]
## Action Performed:
1. Create a worspace
2. Create a room in that workspace
3. Invite a user that is not in the workspace to the room
4. Invite the user to the workspace

## Expected Result:
The user is correctly invited to the workspace and a workspace expense chat is created for them

## Actual Result:
The user is not invited to the workspace

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by eVoloshchak** [comment]
@miljakljajic, apologies for this being so late, I'm owed payment for reviewing https://github.com/Expensify/App/pull/42500

**Comment by mallenexpensify** [comment]
Contributor+: @eVoloshchak due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
