### ISSUE TITLE
Remove lodash/underscore/Jquery from ExpensiMark

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#42494]
In order to support https://github.com/Expensify/react-native-live-markdown/issues/317 we need to remove external libs from ExpensiMark. This was discussed in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1716235671381059).

**Comment by puneetlath** [comment]
We don't need you here @dannymcclain 😄

**Comment by Skalakid** [comment]
Hi I’m Michał from Software Mansion, an expert agency, and I’d like to work on this issue

**Comment by hungvu193** [comment]
Since I reviewed the linked PR, can you please assign me to this issue? @puneetlath 
Thank you 😄

**Comment by tomekzaw** [comment]
Glad to announce that https://github.com/Expensify/expensify-common/pull/718 has been merged and released in 2.0.15

Also, react-native-live-markdown uses `expensify-common@2.0.19` ([link](https://github.com/Expensify/react-native-live-markdown/blob/874c3a4dd6f28e4493236239eb68ba845500ed63/parser/package.json#L25)).

Looks like we can mark this issue as complete.

**Comment by puneetlath** [comment]
Ok great. Do we need to update the App in any way? 

Looks like the only thing left then will be to pay out @hungvu193.

**Comment by hungvu193** [comment]
@puneetlath Can you add BZ member so they can handle payment here? Thank you 😄

**Comment by puneetlath** [comment]
Payment summary: 
- $250 - @hungvu193 - C+ 

Please request on NewDot. Thanks everyone!

**Comment by hungvu193** [comment]
Requested via NewDot 😄

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
