### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Simplify the RootNavigator structure

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42507]
Follow up to the ideal navigation project, we have one task to simplify the structure now.

### Problem

The problem is the same as described in this [issue](https://github.com/Expensify/App/issues/40681) but for the `RootNavigator`.
Currently, central pane screens in `RootNavigator` are wrapped with the central pane navigator. This may be problematic for two reasons:
- Getting information about the actual screen requires more code. It has become visible especially after we migrated to typescript, instead of just getting the route name we have to extract the route from the state or params of the parent navigator.
- More nested navigators mean worse performance.

### Solution

In the early implementation of navigation, we used the custom component `ThreePaneView`. That was the main reason to encapsulate screens with central pane navigators. Now we use StackView for both narrow and wide layouts and the wide layout is achieved using styles.

This allows us to flatten the navigation structure. Now screens from `CentralPaneNavigator` will be mounted directly in the `RootNavigator`

This way developing and maintaining navigation should be easier and we should get a slight performance boost.
cc [@adamgrzybowski](https://github.com/adamgrzybowski) [@WojtekBoman](https://github.com/WojtekBoman)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e857cb7b9e57642a</li>
        <li>Upwork Job ID: 1793573481726357504</li>
        <li>Last Price Increase: 2024-05-23</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 102432432</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by adamgrzybowski** [comment]
@WojtekBoman, @Kicu or I will take care of it

**Comment by WojtekBoman** [comment]
Hi! I'm working on it :)

**Comment by mountiny** [comment]
The PR is still in draft

**Comment by JmillsExpensify** [comment]
Same as above.

**Comment by mountiny** [comment]
This will be ready to be paid soon

**Comment by JmillsExpensify** [comment]
@hoangzinh do you mind filling out the BZ checklist?

**Comment by mountiny** [comment]
@JmillsExpensify this was a new feature/ follow up so no other PR to flag this on.

$250 to @hoangzinh for their review and testing.

**Comment by mountiny** [comment]
Also no regression test required

**Comment by JmillsExpensify** [comment]
@hoangzinh the old offer expired so I just sent you a new one.

**Comment by JmillsExpensify** [comment]
Awesome thanks! All paid out.
