### ISSUE TITLE
[$250] [HOLD for payment 2024-06-13] [QBO] Amend the account type available to configure on reimbursable exports to be relevant to the selected export option

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#42520]
### Problem:
The copy used for reimbursable exports inconsistently refers to all selections as choosing an A/P account, instead of showing the QBO accounts that should be shown per export choice.

Additionally, the page's copy always mentions vendor bills, regardless of whether a check or journal entry is selected for export. 
Lastly, we're only showing explainer text for vendor bills, meaning there is not consitency in the design as there are no similar explanations for checks or journal entries (this is different from oldDot where we use the full explainers on the export page.

### Solution: Update the QBO accounts available to chosen depending on the export choice to:

**Vendor Bill:**
![image](https://github.com/Expensify/App/assets/56830058/73441ddb-37a7-491c-af94-f2cfefe7e426)

Notes for completeness:
- Update copy on screen 1: Export out-of-pocket expenses as page copy should read `We'll create a single itemized vendor bill for each Expensify report. If the period of the bill is closed, we'll post to the 1st of the next open period. You can add the vendor bill to your A/P account of choice (below).`
- Update the push input label depending on the export selection (in this case, `Accounts Payable`)
Update copy on screen 2:
Copy should read: "This is your chosen A/P account, against which vendor bills for each report are created."

**Journal Entry:**
![image](https://github.com/Expensify/App/assets/56830058/847c36eb-c2ee-4fad-a994-90923f7b0d09)

Notes for completeness:
 - Update copy on screen 1: Export out-of-pocket expenses as page copy should read `We'll create a single itemized journal entry for each Expensify report. You can post the offset entry to your account of choice (below).`
 - Update the push input label depending on the export selection (in this case, `Account`)
 - Screen 2: Copy should read: "This is your chosen account to post the journal entry offset for each report."

**Check:**
![image](https://github.com/Expensify/App/assets/56830058/6364b1db-2fcc-4ac5-924b-2f8ed92195d3)

Notes for completeness:
 - Update copy on screen 1: Export out-of-pocket expenses as page copy should read `We'll create a single itemized check for each Expensify report. You can write the check from your bank account of choice (below).`
 - Update the push input label depending on the export selection (in this case, `Bank account`)
 - Copy should read: "This is your chosen bank account to write checks from."

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014665d08c6cbedbca</li>
        <li>Upwork Job ID: 1801670785370229018</li>
        <li>Last Price Increase: 2024-06-14</li>
    </ul>
</details>

**Comment by zanyrenney** [comment]
Conversation: https://expensify.slack.com/archives/C036QM0SLJK/p1716465257860679?thread_ts=1716238564.568549&cid=C036QM0SLJK

**Comment by trjExpensify** [comment]
>Solution: Update the QBO accounts available to chosen depending on the export choice to:
>Vendor bill = accountPayableAccounts only
>Check = bankAccounts
>Journal Entry = (a few different QBO accountTypes are available here)

@zanyrenney the account types being made available for selection are correct for each export type chosen, it's the copy, labelling and so on which is incorrect. The purpose of this was to illustrate why it's incorrect to always be referring to vendor bills and AP account selection.

**Comment by zanyrenney** [comment]
I think the rest of the issue is correct though right? I'll just remove that bit, I was trying to add more context!!

**Comment by s77rt** [comment]
Raised a PR. Need translation https://github.com/Expensify/App/pull/42524#issuecomment-2127259074

**Comment by trjExpensify** [comment]
>I think the rest of the issue is correct though right? I'll just remove that bit, I was trying to add more context from the slack thread, but let me get that cleaned up @trjExpensify

Yeah sorry, it's just this title gave the impression that the proposed solution was to change the accounts being made available to choose, which is the one thing that's actually not being changed. 😅  Rest is good! 

**Solution: Update the QBO accounts available to chosen depending on the export choice to:**

**Comment by s77rt** [comment]
Checklist does not apply. Not a bug, more like a feature request / add missed implementation

**Comment by zanyrenney** [comment]
please apply to job @s77rt https://www.upwork.com/jobs/~014665d08c6cbedbca

**Comment by s77rt** [comment]
@zanyrenney Applied!

**Comment by zanyrenney** [comment]
hired you - with offer <3

**Comment by s77rt** [comment]
@zanyrenney  Accepted! Thanks!

**Comment by zanyrenney** [comment]
### Payment Summary
https://www.upwork.com/jobs/~014665d08c6cbedbca
- ROLE: @s77rt paid $250 via Upwork 

#### BugZero Checklist (@zanyrenney)
- [ ] I have verified the correct assignees and roles are listed above and updated the neccesary manual offers
- [ ] I have verified that there are no duplicate or incorrect contracts on Upwork for this job (https://www.upwork.com/ab/applicants//hired)
- [ ] I have paid out the Upwork contracts or cancelled the ones that are incorrect
- [ ] I have verified the payment summary above is correct

**Comment by zanyrenney** [comment]
all done here, thanks @s77rt
