### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] QBO - Default vendor toggle switch activation is delayed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42534]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when validating #41627
**Version Number:** 1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition: Have a Collect workspace with Quickbooks enabled

1. Log in with an expensifail account
2. Navigate to Workspace settings - Accounting - Export - Export company cards as
3. Click on "Export company cards as"
4. Click on "Vendor bill"
5. Click on the "Default vendor" toggle switch
6. Click on it again
## Expected Result:
It should be instant.
## Actual Result:
Default vendor toggle switch takes 1-2 seconds to activate after interacting with it.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/0eab2e38-02ae-4839-b019-9fde9d36996e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149d7ffc050a52133</li>
        <li>Upwork Job ID: 1794065232279744512</li>
        <li>Last Price Increase: 2024-05-24</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102499228</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by m-natarajan** [comment]
@hayata-suenaga FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by hayata-suenaga** [comment]
I thought this resulted from the backend issue we're temporarily experiencing, but we should have an optimistic update, so this might be a bug. Let's investigate!

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default vendor toggle switch takes 1-2 seconds to activate after interacting with it.

### What is the root cause of that problem?
The optimistic data here is wrong, `configUpdate` is an object that should be spread instead of merging it as a field of `config` object

https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/actions/connections/index.ts#L132

https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/actions/connections/index.ts#L150
### What changes do you think we should make in order to solve the problem?
We should spread the `configUpdate` here

```
... configUpdate
```
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/actions/connections/index.ts#L132


and `configCurrentData` here

```
... configCurrentData
```
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/libs/actions/connections/index.ts#L150
### What alternative solutions did you explore? (Optional)
NA

**Comment by hayata-suenaga** [comment]
[bumped on the Slack channel](https://expensify.slack.com/archives/C01GTK53T8Q/p1716592761585909)

**Comment by nkdengineer** [comment]
@hayata-suenaga I had a proposal here https://github.com/Expensify/App/issues/42534#issuecomment-2129089965

**Comment by nkdengineer** [comment]
When we call `updateManyPolicyConnectionConfigs` we only need to update `[CONST.QUICK_BOOKS_CONFIG.AUTO_CREATE_VENDOR]` and `[CONST.QUICK_BOOKS_CONFIG.NON_REIMBURSABLE_BILL_DEFAULT_VENDOR]` in config so we don't need to pass `policy?.connections?.quickbooksOnline?.config`

**Comment by nkdengineer** [comment]
> But why not just use the config to have complete data?

We use `merge` method so in `failureData` so we only need to reset the field that is changed in optimistic data.

**Comment by nkdengineer** [comment]
@thesahindia this [PR](https://github.com/Expensify/App/pull/42732) is ready for preview

**Comment by CortneyOfstad** [comment]
@thesahindia can you please have the checklist completed at your earliest convenience? This will help avoid any delays in payment early next week. Thanks!

**Comment by hayata-suenaga** [comment]
I'll be OOO from June 10th to June 13th and will return on Friday. I think I'm not needed anymore, but I just wanted to inform you of my upcoming absence. 😄

**Comment by CortneyOfstad** [comment]
## Payment Summary

@nkdengineer — paid $250 via Upwork
@thesahindia — to be paid $250 via NewDot

Thanks all!

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
