### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Edit Message - Emoji’s are cut in half when in Edit message mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42530]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+emilio@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41027
## Action Performed:
1. Open the New Expensify App
2. Sign into a valid account
3. Go to any chat
4. Send an emoji (Only an Emoji so that the Emoji is larger than normal)
5. Tap on "Edit Message" option

## Expected Result:
User expects the Edit message composer to open and the emoji to be fully visible as before

## Actual Result:
The Emoji is cut in half

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/df17d70b-9fad-48c4-8f24-abf1c6b7697d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba75049d57ad65eb</li>
        <li>Upwork Job ID: 1794204477867704320</li>
        <li>Last Price Increase: 2024-05-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment]
Can repro, going to assign @Ollyws as he was C+ on the PR.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emojis are cut when in large size in edit composer.

### What is the root cause of that problem?
When the composer only contains emoji, we set the size to be bigger, but the line height is still small. We use this line height.
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/styles/index.ts#L2090

We then fix this in https://github.com/Expensify/App/pull/41027 by applying a bigger line height if the composer only contains emoji, but we only apply the fix to the main composer.

### What changes do you think we should make in order to solve the problem?

We can move the fix to Composer/index.tsx and Composer/index.native.tsx and append it to RNMarkdownTextInput style.
https://github.com/Expensify/App/blob/8375abea3a377e7416404addde255b6ac8530a9b/src/components/Composer/index.native.tsx#L82

**Comment by bernhardoj** [comment]
PR is ready

cc: @Ollyws

**Comment by charmer1025** [comment]
I think it is related to CSS position problem.
I can fix it right now.

**Comment by bernhardoj** [comment]
I know it's a native issue only, but https://github.com/Expensify/App/pull/40692 only applies the line-height fix on the native.

The current condition is:
The line-height fix is applied for all platforms, but only in the main composer (ComposerWithSuggestions)

https://github.com/Expensify/App/pull/40692:
The line-height fix from the current condition stays the same. In addition, the line-height fix is applied to both the main and edit composer (Composer), but only on the native

My PR:
The line-height fix is moved from ComposerWithSuggestions to Composer/index.tsx and Composer/index.native.tsx, so it's applied for both the main and edit composer on all platforms.

We can either complete my PR first or you can incorporate the changes to https://github.com/Expensify/App/pull/40692.

**Comment by rlinoz** [comment]
PR is in staging, just waiting a prod deploy.

**Comment by jliexpensify** [comment]
@Ollyws is a checklist needed here?

Payment Summary

- C: @bernhardoj $250 
- C+: @Ollyws $250

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws

**Comment by jliexpensify** [comment]
Paid @bernhardoj and job removed. Thanks everyone!
