### ISSUE TITLE
Sign In - App closes after 1 - 5 min of inactivity on Sign In page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42545]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user should be Signed Out
1. Open app
2. Wait for about 1 - 5 min (device should not been locked during this period)

## Expected Result:
Sign In page should be displayed during inactivity period

## Actual Result:
App closes after 1 - 5 min of inactivity on Sign In page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e522ef22-e68e-412c-83df-d63d1b2a3a23

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by strepanier03** [comment]
Testing now on Pixel 6 Pro, will update soon.

**Comment by strepanier03** [comment]
I've been open for 10 minutes now and can't repro this behavior. Going to close out.
