### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [LOW] Use static .svg for Travel terms & conditions page, not a .lottie file

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#42560]
Coming from this comment [here](https://github.com/Expensify/App/pull/41493#discussion_r1611772834):

Problem:
The image used in the Travel terms & conditions RHP modal is just a static .svg image, yet it was implemented as a .lottie file because that component only accepts .lottie files for the illustration portion

Solution::
Fix the component so that it can accept a static .svg file to use as the image. 

This issue should be assigned to @WojtekBoman

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by shawnborton** [comment]
cc @twisterdotcom @bfitzexpensify

**Comment by twisterdotcom** [comment]
@WojtekBoman please comment on this issue!

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on that :)

**Comment by sobitneupane** [comment]
@twisterdotcom I reviewed the associated [PR](https://github.com/Expensify/App/pull/42625). Can you please assign me the issue. I will require payment summary to request payment on newDot.

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
