### ISSUE TITLE
Android - Distance unit - Tapping on Kilometers unit doesn't select it right away

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42578]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4573054
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open New Expensify app
2. Create a workspace
3. Enable distance rate
4. Open distance rate settings > Settings > Unit
5. Tap on Kilometers

## Expected Result:
The kilometers unit gets selected

## Actual Result:
The kilometers unit does not get selected, user has to tap on it multiple of times to select it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b570a6ed-3bd7-4d53-90e3-305cd1abea9c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by kadiealexander** [comment]
Android <> iOS bug swap.

**Comment by jliexpensify** [comment]
Created 3 Workspaces, all allowed me to select `Kilometers` easily on v75-1 (Pixel 7).

I also notice on occasion, the Android app doesn't select things but it's always temporary. Closing.
