### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Distance - Page is not scrollable after adding multiple stops

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42577]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4572868
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Click on FAB > Submit expense > Distance tab
2. Add a start waypoint, a finish waypoint, and multiple stops
3. Try to Scroll the page
4. Do step 1 - 3 on mWeb

## Expected Result:
Page becomes scrollable to view the whole content after adding multiple waypoints (Same behavior as in mWeb)

## Actual Result:
Page is not scrollable to view the whole content after adding multiple waypoints which is a different behavior compared to mWeb.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/de96b11b-7ef9-48a3-8e63-50690e0f4ea8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d91998739178ee2</li>
        <li>Upwork Job ID: 1795722148596056064</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102695130</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by stephanieelliott** [comment]
Hey @mollfpr, a few proposals here to review when you get a chance!

**Comment by mollfpr** [comment]
>Wrap the content in a ScrollView and remove the View.

@Krishna2323 What's the difference between your main and the alternative solution? Also, I tried the above step but it did not work. In the alternative solution, wrapping the `DraggableList` with `<ScrollView style={styles.flex1}>` seems to fix the issue, so I don't understand the purpose of the second step.

@GandalfGwaihir As mentioned before in the @Krishna2323 proposal, we can't use the `ListFooterComponent` to avoid the issue https://github.com/Expensify/App/issues/40211 arising again.

**Comment by mollfpr** [comment]
@Krishna2323 The result looks good, but I think the expected result is similar to what we have in iOS where the scroll can be used above the waypoint list instead of just space beside the add stop button.

https://github.com/Expensify/App/assets/25520267/114974c0-98b2-495e-a974-679e68f42348

**Comment by mollfpr** [comment]
@allgandalf I can do it for you. We still don't have selected proposal yet, and I still don't know the reason we can't pass the component to footer props.

**Comment by mollfpr** [comment]
@allgandalf It seems the issue occurs again.

https://github.com/Expensify/App/assets/25520267/2b1e100c-b4a1-4fb2-91bd-fc00fa609eb5

@Krishna2323 I'm not sure if using `NestableScrollContainer ` and `NestableDraggableFlatList` is the correct way, because `NestableScrollContainer` is used to wrap multiple `NestableDraggableFlatList`. Meanwhile, we only have one draggable flat list component.

**Comment by mollfpr** [comment]
@Krishna2323 Okay, I'll try to play around and see if there's a regression from using the `NestableScrollContainer`.

**Comment by stitesExpensify** [comment]
PR is being worked on

**Comment by stitesExpensify** [comment]
Not overdue Melvin

**Comment by stephanieelliott** [comment]
Little bump @mollfpr, can you review the PR when you get a chance?

**Comment by stephanieelliott** [comment]
PR is under active review

**Comment by stephanieelliott** [comment]
Applying the New Feature label to get another BZ member on this while I am OOO til July 10. To catch you up on where we are @lschurr, we have a PR and it's being actively reviewed: https://github.com/Expensify/App/pull/43810


Thanks for watching over this, I'll grab it back from you when I return!

**Comment by stephanieelliott** [comment]
This is held on an upstream fix https://github.com/Expensify/App/pull/43810#issuecomment-2215401234

**Comment by stephanieelliott** [comment]
Upstream issue we are blocked on is here: https://github.com/computerjazz/react-native-draggable-flatlist/issues/543

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @Krishna2323 $250 - PAID via Upwork 
 - Contributor+: @mollfpr $250 - please request via ND 
 
 Upwork job is here: https://www.upwork.com/jobs/~1737876297360310272

**Comment by stephanieelliott** [comment]
@mollfpr can you please complete the BZ checklist for this issue?

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't find the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Click on FAB > Submit expense > Distance tab
2. Add a start waypoint, a finish waypoint, and multiple stops
3. Verify page is scrollable after the content overflows
4. 👍 or 👎

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr

**Comment by stephanieelliott** [comment]
Test case issue created: https://github.com/Expensify/Expensify/issues/420216

All done here, thanks!
