### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Explore option to show Control policies in the workspace settings

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42580]
Coming from https://expensify.slack.com/archives/C06ML6X0W9L/p1716243538260799

Show Control policies in the workspace list in Newdot and hence allow them to be edited from Newdot as well.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd6bd5c2c884b9c7</li>
        <li>Upwork Job ID: 1800539681381245430</li>
        <li>Last Price Increase: 2024-06-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by dubielzyk-expensify** [comment]
I assume this is the whole Workflows & Rules I've been working with @JmillsExpensify on?  Getting closer on the designs there.

If this is something else as well, then let me know how I can lend a hand 😄

**Comment by mountiny** [comment]
@dubielzyk-expensify this is just to explore how the control workspace settings looks like/ works in Newdot now so I think there is nothing actionable for you on this GH, sorry it was just an autoassigner

**Comment by mountiny** [comment]
PR in final review

**Comment by rushatgabhane** [comment]
[@rushatgabhane] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

1. Login to an account that has personal workspaces and collect workspace
2. Go to settings > workspaces
3. Verify that collect and control workspaces show in the list.
4. Verify that personal workspaces do not show in the list.

**Comment by abekkala** [comment]
Not overdue melvin! Payment is tomorrow!

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JUNE 20

- Fix: `Internal` Vit
- PR Review: @rushatgabhane - [$250] payment via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
