### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Workspace's default currency isn't showing when submitting a request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42597]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716540568640839

## Action Performed:
1. Create a new WS
2. Change the currency of the workspace
3. Go to the WS chat
4. Tapping on the plus icon > Submit expense
5. Notice the currency in amount step
## Expected Result:
The default currency in the amount step should be the WS currency if we submit an expense in the WS chat.

## Actual Result:
The default currency in the amount step isn't the WS currency

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/000c5a7a-dd10-4462-9f3a-5d01a5546771

https://github.com/Expensify/App/assets/38435837/06623ac6-8635-48dc-bf96-d91576719974

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce85c0267e9bbc85</li>
        <li>Upwork Job ID: 1795970316320600064</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 102671509</li>
<li>ShridharGoel | Contributor | 102671511</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The default currency in the amount step isn't the WS currency

### What is the root cause of that problem?
When we init money request, we always set the default currency as the local currency of the user

https://github.com/Expensify/App/blob/8d73db3b6521c33637cd91a14fe942b6b0741acd/src/libs/actions/IOU.ts#L320
### What changes do you think we should make in order to solve the problem?
We should prioritize the policy's currency first instead of user's local currency

```
currency: policy?.outputCurrency ?? currentUserPersonalDetails.localCurrencyCode ?? CONST.CURRENCY.USD,

```


https://github.com/Expensify/App/blob/8d73db3b6521c33637cd91a14fe942b6b0741acd/src/libs/actions/IOU.ts#L320

### What alternative solutions did you explore? (Optional)
NA

**Comment by puneetlath** [comment]
What's the status of this issue?

**Comment by nkdengineer** [comment]
@fedirjh 

Two additional cases in the selected proposal aren't bugs.

For both case `TeachersUnite.ts` and `buildOptimisticCustomUnits`, we're creating a new policy so it's expected that the default currency will be the `localCurrencyCode` of user.

**Comment by puneetlath** [comment]
Payment summary: 
- @ShridharGoel - $250 - paid in Upwork
- @fedirjh - $250 - to be paid in NewDot

Regression test: https://github.com/Expensify/Expensify/issues/412084

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @fedirjh
