### ISSUE TITLE
[HelpDot] LHN clicking navigates to different location 

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#42598]
Coming from: 
https://expensify.enterprise.slack.com/archives/C02QSAC6BJ8/p1716512776382679

Clicking LHN links navigates instead of collapsing /expanding the LHN

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by maddylewis** [comment]
asking for update here - https://expensify.slack.com/archives/C02QSAC6BJ8/p1716906559944779

**Comment by maddylewis** [comment]
will ask for update tomorrow 👍

**Comment by rushatgabhane** [comment]
same update as above ^

**Comment by maddylewis** [comment]
not a priority rn as the changes require internal engineering resources -- closing
