### ISSUE TITLE
Q2 2024 Estimated Executive SPMP Bonus Filings

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#42605]
We've estimated the number of shares our executives will sell in our upcoming SPMP Bonus release [here](https://docs.google.com/spreadsheets/d/1mHZa_nrxMo5_AunEbNvlWIhD85FOWqO0S8iB0TR5hgo/edit#gid=0).

**Comment by coleaeason** [comment]
Will put Form 144s together tomorrow.
