### ISSUE TITLE
[HOLD for payment 2024-06-13] [HOLD for payment 2024-06-11] [Wave Collect] [Xero] Implement the More Features change

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42644]
Related to https://github.com/Expensify/App/pull/42487#issuecomment-2126835757

Implement the `More Features` change

**Comment by mananjadhav** [comment]
I'll create a separate PR for this in a few hours.

**Comment by mananjadhav** [comment]
No payout here.

**Comment by twisterdotcom** [comment]
https://github.com/Expensify/App/issues/42073#issuecomment-2166943047

**Comment by mananjadhav** [comment]
@twisterdotcom There won’t be any payout for this issue. This was already handled centrally as flat fee.  I think we can close this one out.

**Comment by twisterdotcom** [comment]
Oh nice!
