### ISSUE TITLE
Tax - Split scan - Unable to save tax amount when the tax amount does not exceed limit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40240
## Action Performed:
Precondition:
- Workspace is tax-enabled.
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Create a split scan expense
4. While the receipt is scanning, click on the split preview
5. Click Amount and enter amount
6. Click Tax rate and select a non-zero tax rate
7. Click Tax amount
8. Click Save without modifying the current value

## Expected Result:
Tax amount will be saved without issue

## Actual Result:
User is unable to save the tax amount. It says "Maximum tax amount is 0.00", when the tax amount is updated according to the selected rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/65c0e484-5735-4b73-90df-6a84807b4c2f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by bondydaa** [comment]
the revert https://github.com/Expensify/App/pull/42670 has been deployed, please retest and confirm this is no longer reproducible.

**Comment by kavimuru** [comment]
This bug is not reproduced because of https://github.com/Expensify/App/issues/40755

https://github.com/Expensify/App/assets/43996225/4f66dceb-09f6-4f7b-b44b-3309c6904335

**Comment by MonilBhavsar** [comment]
PR was reverted
