### ISSUE TITLE
[$250] mWeb - Chat - Letter sent with emoji is not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4575388
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Tap emoji picker
4. Select an emoji and enter a letter
5. Send the message

## Expected Result:
Emoji with a letter sent must be displayed

## Actual Result:
Emoji with a letter is sent but letter is not displayed, only emoji can be seen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/99e34ccc-7f8e-4386-8d38-f198bdd8ac4f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe9b72a4d46f8613</li>
        <li>Upwork Job ID: 1796545237013188608</li>
        <li>Last Price Increase: 2024-06-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf </details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
We also observed an issue with a lost letter in another situation:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3.Enter
H
> h
H


https://github.com/Expensify/App/assets/78819774/b43be59f-904a-4971-87f7-7c64332c64ef

Is this the same issue or a new one?

**Comment by sonialiap** [comment]
Odd! Adding External

**Comment by ashuvssut** [comment]
I tested in Edge browser (a Chromium based browser) in my Android device and found that its not reproducible
- the webapp was served by webpack dev server (main branch)

**Comment by lanitochka17** [comment]
Issue is still reproducible on the Redmi note 10s/Chrome

https://github.com/Expensify/App/assets/78819774/b80f9377-6bd8-4f75-aa51-e5668936bfd8

**Comment by sonialiap** [comment]
Thanks Svetlana

**Comment by sonialiap** [comment]
@allgandalf I think GH automatically made the update

<img width="322" alt="image" src="https://github.com/Expensify/App/assets/17131195/62ff1e71-e4e0-4cde-bbb5-ab5a96599abf">

**Comment by sonialiap** [comment]
😄 updated

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sonialiap** [comment]
No longer reproducible


https://github.com/Expensify/App/assets/17131195/690612ac-daab-41ee-aa09-e8b4abab3b50

**Comment by sonialiap** [comment]
@allgandalf I can't reproduce it on Android web Chrome either. The letter comes through after the emoji both when there's a space after the emoji or when I delete the space and add the letter directly after

https://github.com/Expensify/App/assets/17131195/a2ac25fb-7871-4eae-bd2e-70b33b605433
