### ISSUE TITLE
[HOLD for payment 2024-08-19] [HOLD for payment 2024-08-09] [$250] Associate crashes with specific logins

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#42651]
### Problem

When users report that their staging or production app crashed, it can be difficult to find the stacktrace for that crash after-the-fact. This makes it harder to identify and fix real-world crashes, leading to a poorer UX in terms of app quality and the level of support we can provide to users who do experience crashes.

### Solution
Upon login, associate the user login with [crashlytics user ID](https://rnfirebase.io/crashlytics/usage#crash-attributes). That way, if the app crashes, the crash report will be logged along with the login for the user. Then we'll be able to search for crashes by user in the Crashlytics console, and maybe find out more.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019268795ed9fe7be1</li>
        <li>Upwork Job ID: 1795144470205255680</li>
        <li>Last Price Increase: 2024-05-27</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 102519677</li>
<li>ShridharGoel | Contributor | 102519678</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by roryabraham** [comment]
FWIW I think the code for this is the easy part - testing is the harder part. Not sure what's needed to test crashlytics locally

**Comment by getusha** [comment]
@ShridharGoel anyway to test it locally?

**Comment by roryabraham** [comment]
I think we'd definitely want to set the userID as soon as we login, because the error boundary will only catch JS-level errors, not native crashes

**Comment by dylanexpensify** [comment]
@getusha to review

**Comment by getusha** [comment]
@roryabraham does this need a c+?

**Comment by roryabraham** [comment]
I think a C+ could be helpful for the review. Feel free to drop if you're not interested though and we can find another volunteer

**Comment by roryabraham** [comment]
@ShridharGoel why are there two PRs?

- https://github.com/Expensify/App/pull/43061
- https://github.com/Expensify/App/pull/43063

**Comment by dylanexpensify** [comment]
@getusha you sticking around? Just confirming!

**Comment by getusha** [comment]
> @getusha you sticking around? Just confirming!

Yes, hopefully we'll get this merged today or tomorrow.

**Comment by roryabraham** [comment]
Reminder to everyone on the issue, once it's done we'll want to create a follow-up to upgrade react-native-firebase to take advantage of the fix in https://github.com/invertase/react-native-firebase/issues/6226

**Comment by dylanexpensify** [comment]
@getusha mind giving an update?

**Comment by roryabraham** [comment]
bumped in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1722282113203869

**Comment by dylanexpensify** [comment]
Coming up this week!

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by JmillsExpensify** [comment]
$250 approved for @getusha
