### ISSUE TITLE
Expense - Unable to select a different currency in transaction thread

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42655]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4574596
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit expense to any user.
3. Go to transaction thread.
4. Click Amount.
5. Click on the currency.
6. Select a different currency.
## Expected Result:
The new currency is saved.
## Actual Result:
The new currency is not saved.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

https://github.com/Expensify/App/assets/38435837/a81d796b-1c47-4e00-9ec7-89a64f3720db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@bondydaa FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by bondydaa** [comment]
this PR seems suspicious to me https://github.com/Expensify/App/pull/40240/  cc @jasperhuangg @MonilBhavsar @dukenv0307 can you take a look?

**Comment by bondydaa** [comment]
we've reverted https://github.com/Expensify/App/pull/40240 and are deploying that to staging now. once it's ready i'll confirm so we can retest.

**Comment by bondydaa** [comment]
the revert https://github.com/Expensify/App/pull/42670 has been deployed, please retest and confirm this is no longer reproducible.

**Comment by kavimuru** [comment]
Issue is fixed 

https://github.com/Expensify/App/assets/43996225/bd14f6a4-1f96-45d2-a506-5f02783ee6c8

**Comment by puneetlath** [comment]
Great, thanks!
