### ISSUE TITLE
[$250] App performance - Laggy transition when switching from one report to another

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open a report from LHN
3. Open another report from LHN
4. Note that transition when switching from one report to another

## Expected Result:
The transition when switching from one report to another will not be laggy (production behavior)

## Actual Result:
The transition when switching from one report to another is laggy
The entire app on all platforms is slow. The reproduction steps are just one of the ways to show the lagginess

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0fd191c6-83fe-4f8b-9d7d-5562edc188e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183ab1dc4a4be8fe5</li>
        <li>Upwork Job ID: 1795451622908186624</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment]
Making this external but also asked the agencies to look into this one closely https://expensify.slack.com/archives/C05LX9D6E07/p1716902910273389

**Comment by kavimuru** [comment]
Retested in https://42725.pr-testing.expensify.com/r (web / mweb) and in the android adhoc build https://ad-hoc-expensify-cash.s3.amazonaws.com/android/42725/index.html . It was a pass. Tester does not have access to iOS ad hoc build

https://github.com/Expensify/App/assets/43996225/2da8f165-1847-4d4a-b784-db30b83f3722


https://github.com/Expensify/App/assets/43996225/7386b5b1-9fdc-443b-b20d-f680ae62a627

**Comment by Beamanator** [comment]
PR CP'd and working well in staging, not a blocker anymore 👍

**Comment by mountiny** [comment]
I think this can be closed now
