### ISSUE TITLE
[HOLD for payment 2024-06-06] [HOLD for payment 2024-06-05] iOS- Launch - App crashes at launch on IOS 14

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42656]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76.1
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** [gatantm@gmail.com](mailto:gatantm@gmail.com)
**Logs:** 
[Bug6493185_1716832351739!New_Expensify-2024-05-27-204355.ips.beta.txt](https://github.com/Expensify/App/files/15459153/Bug6493185_1716832351739.New_Expensify-2024-05-27-204355.ips.beta.txt)
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Install the 1.4.76.1 build to iOS 14
2. Launch the app

## Expected Result:
The app launches on all compatible devices

## Actual Result:
The app crashes at launch on iOS 14.7 Build 1.4.76.0 works without issues
Comment: Can not reproduce this on the same model running iOS 16.7 nor the iPhone 15 Pro Max, iOS 17.4.1 or the iPhone 8 running iOS 15 so seems iOS 14 specific.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/671619c3-4d32-46bf-ab86-c6b3baa069be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment]
cc @danieldoglas seems like this is coming from the Full story https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/ios:com.chat.expensify.chat/issues/4adc1d894670d34d211593149c632aad?time=last-seven-days&types=crash&sessionEventKey=8277d1bcf278472cbdbc03de18fe257c_1952208087522792385 

Is it supposed to support ios 14?

**Comment by danieldoglas** [comment]
Can we raise that minimum version for our App?

```
All devices that supported iOS 13, iPadOS 13, iOS 14, and iPadOS 14 also support iOS 15 and iPadOS 15.
```

**Comment by mountiny** [comment]
> Can we raise that minimum version for our App?

We can, but I think we should make a post to discuss it in Slack to get broader agreement

**Comment by danieldoglas** [comment]
Yeah, I'll do that. I've also asked Fullstory to investigate that crash.
