### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] [LOW] [Performance] Make switching pages in full screen navigator instant

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42669]
### Problem

When changing the pages in the full-screen navigator, there is a slight but noticeable delay. The video does not make it super clear, but try it out yourself to feel the delay.

You can see the URL changes and only after a split of a second the UI updates.

https://github.com/Expensify/App/assets/67908363/62d68b5b-75ec-481a-8ce5-38ba47b2a3c1

### Solution

Find the root cause of this delay and try to fix it.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01014b904a78fe1b10</li>
        <li>Upwork Job ID: 1795197179077103616</li>
        <li>Last Price Increase: 2024-05-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by adamgrzybowski** [comment]
Hi! I have solution for that

**Comment by dylanexpensify** [comment]
Nice!

**Comment by mountiny** [comment]
In staging

**Comment by dylanexpensify** [comment]
tomorrow!

**Comment by mountiny** [comment]
$250 this is ready for payment to @thesahindia

**Comment by dylanexpensify** [comment]
Payment summary:
- contributor: @adamgrzybowski 
- contributor+: @thesahindia $250

Please request!

**Comment by JmillsExpensify** [comment]
$250 approved for @thesahindia
