### ISSUE TITLE
Tax - Tax amount is not updated when changing Tax rate

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42682]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.76-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/40240
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Tax should be enabled
1. Navigate to a workspace chat
2. Click '+' icon > Split expense > Enter amount > Select a tax rate
3. Change the previously selected tax rate with a new rate

## Expected Result:
Tax amount should be updated with the new tax rate

## Actual Result:
Previously calculated tax rate is persisting

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/27281230-c546-4adf-bec4-1ff3cc431560

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@isabelastisser I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
Production

https://github.com/Expensify/App/assets/115492554/681726a5-985e-4356-be6d-0ea25639fff8

**Comment by Julesssss** [comment]
Hey @izarutskaya. We reverted the PR this is related to.

**Comment by Julesssss** [comment]
@MonilBhavsar I think we can just close this. But c=please could you confirm, I'm getting a bit confused with the linked issue and revert 😄

**Comment by MonilBhavsar** [comment]
Yes, we can remove the labels and close this. I'll address this in a followup PR
