### ISSUE TITLE
[$250] WS - Admin is unable to approve report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42688]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990395
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: For the test cases that require Holding a expense in a workspace we need to setup some accounts. These account can be reused for future executions of the slot. The accounts we'll be using are:

Workspace owner
Approver
Employee
To setup these accounts follow these steps:

Login as the owner of the workspace
Create a workspace
Invite the approver and employee
Navigate to more features
Enable "workflows"
On the "Workflow" editor - enable "Add Approvals"
Set the Approver account as the Approver

Employee
1. Submit a report with 2 expenses to the workspace
2. Hold 1 of the expenses.

Admin
1. Login as the admin/owner of the workspace
2. Navigate to the report
3. Verify you can approve the report as the admin
4. Approve the report

## Expected Result:
'Approve' button is available for Owner/Admin

## Actual Result:
'Approve' button is not available for Owner/Admin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/dc40f108-b2c2-43d0-957b-5d35dabb9888

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6fd07f535a9dd21</li>
        <li>Upwork Job ID: 1795512042815188992</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by CortneyOfstad** [comment]
@getusha we have a couple of proposals above to review when you have a moment. Thank you!

**Comment by getusha** [comment]
@CortneyOfstad we can choose the owner/admin as an approver. The owner/admin should always be the approver, even when not explicitly selected?

**Comment by CortneyOfstad** [comment]
@getusha the owner/admin is the default but there can be other approvers selected. However, the admin has the ability to "take control" of a report from the other approver and approve the report themselves. Does that make sense?

**Comment by getusha** [comment]
> @getusha the owner/admin is the default but there can be other approvers selected. However, the admin has the ability to "take control" of a report from the other approver and approve the report themselves. Does that make sense?

This means we can remove the owner/admin option from the approver selection, right?

**Comment by getusha** [comment]
![Screenshot 2024-05-31 at 2 05 29 in the afternoon](https://github.com/Expensify/App/assets/75031127/da83d527-8d95-43db-b309-4e991aff38ae)

This probably needs some BE change. for the FE @Nodebrute's proposal (alternative) lgtm
🎀 👀 🎀 Getting internal engineer to confirm this.

**Comment by rlinoz** [comment]
You can't approve a report if you are not the report's manager. We would need to implement the take control functionality, I am checking [in Slack](https://expensify.slack.com/archives/C03U7DCU4/p1717163453001379) if that is the case.

**Comment by rlinoz** [comment]
Per the slack thread this is not supported in NewDot yet, so we can close the issue.
