### ISSUE TITLE
[HOLD for payment 2024-06-28] Disabling Delayed Submission in NewDot turns off Scheduled Submit instead of setting Instant Submit

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#42685]
## Action Performed:
1. Create new workspace in NewDot
2. Disable Delayed Submission

## Expected Result:
Workspace has Scheduled Submit enabled and 'Instantly' selected.

## Actual Result:
Workspace has Scheduled Submit disabled.

## Workaround:
Set 'Instantly' in OldDot, no workaround in NewDot.

## Platform:
All
 
- **Version Number:** v1.4.76-3
- **Logs:** See how to search logs [here](https://stackoverflow.com/c/expensify/questions/4856)
- **Notes/Photos/Videos:** Any additional supporting documentation
- **Is this issue reproducible in staging, production or both?** both

cc @lakchote @Beamanator 

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by trjExpensify** [comment]
Can the App PR come off hold here?

**Comment by adelekennedy** [comment]
payment summary is correct, payments due:

$250 @parasharrajat (NewDot)

**Comment by adelekennedy** [comment]
https://github.com/Expensify/Expensify/issues/409494

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
