### ISSUE TITLE
The app generates an error in the console when text with an empty line at the end is pasted

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42695]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kosmydel 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716892302390049

## Action Performed:
1. Open report in the New Expensify.
2. Copy text with an empty line at the end.
3. Paste it into the composer.
## Expected Result:
 No errors in the console.
## Actual Result:
Error in the console.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f29f4e75-b8ac-4546-ad31-04626f91a86c

![Snip - (52) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/1248c0c6-2e91-4878-b343-4080ddc1fd63)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by moonstar-95515** [comment]
It seems we already have same issue [here](https://github.com/Expensify/App/issues/42216).

**Comment by MitchExpensify** [comment]
Just to be sure, are you saying https://github.com/Expensify/App/issues/42216 will solve this bug @moonstar-95515 ?

**Comment by moonstar-95515** [comment]
@MitchExpensify 
Yes, solving #42216 will also solve this issue. These are exactly same issue.

**Comment by MitchExpensify** [comment]
Cool, closing
