### ISSUE TITLE
GBR is removed from workspace chat when opening a transaction thread.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42691]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716832039752299

## Action Performed:
1. Go to staging.new.expensify.com
2. Set the preference to focus mode
3. open a workspace chat that has a GBR
4. click into the outstanding expense report (it needs to have at least two expenses on it)
5. click into one of the transaction threads

## Expected Result:
The workspace chat displayed in LHN with a GBR
## Actual Result:
The workspace chat is no longer in the LHN with a GBR
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/10967c05-03bc-4d17-ac94-d4b38a4ff437

![image (1)](https://github.com/Expensify/App/assets/38435837/ea72cb20-3654-482f-bab6-a7bb202ee42c)

![image (2)](https://github.com/Expensify/App/assets/38435837/699a4ff2-ec3a-4a4c-b9c8-e7f1778eb696)

From @puneetlath 
Two ways to handle this:
1. Somehow don't set isSearchingForReports in this flow
2. Don't default hasOutstandingChildRequest to false when it isn't present [when structuring reports](https://github.com/Expensify/Auth/blob/106a36d4c459cc25e6b530f77d7d47576f9e0435/auth/lib/Report.cpp#L8591) and instead just leave it empty so that it'll retain its existing value if it has one
3. Another option would be to pass the argument` isSearchingForReports` explicitly in the search flow. Rather that inferring it
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
This is an internal issue. I'll take it.

**Comment by puneetlath** [comment]
This has been deployed.
