### ISSUE TITLE
 IOU - User is not navigated to first step of submit expense after refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a chat
2. Create a manual request thought the chat plus icon (not the FAB)
3. Enter an amount and click Next
4. Click the three dots on the top, and attach a receipt
5. Refresh the page

## Expected Result:
The page should go back to the first step, autofilled with the previous amount

## Actual Result:
The page is not go back to the first step, autofilled with the previous amount. The page is a second step (request details)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bc894cea-a998-4fb2-9d2d-7447e478d166

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@lanitochka17 I don't understand what the expected outcome is. In my opinion, this is working as intended - when you refresh the page, the receipt should disappear (as it's not uploaded) so it should go back to the request details page.
