### ISSUE TITLE
[$125] [Search v1] PDF thumbnails are not shown in search page results

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#42721]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Request money and add a PDF receipt
2. Navigate to the search page `Profile > Troubleshoot > New search page`
3. Verify that the receipt thumbnail is not shown for PDF receipts

## Expected Result:
PDF receipt thumbnail should be shown

## Actual Result:
PDF receipt thumbnail is not shown

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
Coming from [this comment](https://github.com/Expensify/App/pull/41957#issuecomment-2135991310)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191147ccff9c86ca2</li>
        <li>Upwork Job ID: 1795548762126381056</li>
        <li>Last Price Increase: 2024-06-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
Thanks for the proposals so far. A couple of comments:

1. I don't think we need to use `getThumbnailAndImageURIs` since that takes in a full transaction object, which is not available from search. It also has logic to check for local files, which is not the use case on search.
2. We cannot connect this component to Onyx to retrieve the transaction, since users might not have that available to them given the search result can return results not available locally in Onyx.

That being said, the backend doesn't seem to be sending the correct thumbnail receipt URL. So we need to update that. We should also pass the `isPDFThumbnail ` prop like the proposals above suggested.

**Comment by luacmartins** [comment]
My point is that the API should be returning the correct URL already.

**Comment by luacmartins** [comment]
Both

**Comment by sobitneupane** [comment]
I am being blocked by https://github.com/Expensify/App/issues/42889 regression to test the issue.

**Comment by luacmartins** [comment]
@sobitneupane you can temporarily fix that issue by changing [this value](https://github.com/Expensify/App/blob/fe32d949481dc0a81ad2ead6dc08bb01a177fe6a/src/CONST.ts#L4782) to `transactions`

**Comment by anmurali** [comment]
Not overdue, actively discussing the solution.

**Comment by sobitneupane** [comment]
@luacmartins Will it require any change in frontend? If yes, is it open for contributors?

**Comment by luacmartins** [comment]
I don't think so, I tested with the API changes and the PDF thumbnails are showing correctly now.

**Comment by luacmartins** [comment]
This is done. Backend only fix, so I think we're good to close.
