### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [Search v1] Improve performance of ReportListItem

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#42720]
Coming from [this PR](https://github.com/Expensify/App/pull/42410), let's apply [these performance improvements](https://github.com/Expensify/App/pull/42170) to `ReportListItem`.

Additionally, we should also address these comments:

- [ ] https://github.com/Expensify/App/pull/42410#discussion_r1618381238
- [ ] https://github.com/Expensify/App/pull/42410#discussion_r1618399150
- [ ] https://github.com/Expensify/App/pull/42410#discussion_r1618409353
- [ ] https://github.com/Expensify/App/pull/42410#discussion_r1618420504
- [ ] https://github.com/Expensify/App/pull/42410#discussion_r1618451153
- [ ] https://github.com/Expensify/App/pull/42410#discussion_r1618454074

cc @WojtekBoman 

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment]
I believe that this one has a few PRs in the works, but there was one moved to production yesterday. For now, adding the `Reviewing` label.

**Comment by luacmartins** [comment]
We haven't started work on this one yet. @WojtekBoman can you comment here so I can assign this to you please?

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on that :)

**Comment by alexpensify** [comment]
@luacmartins - one of the PR has merged, are we waiting for more actions here? Thanks!

**Comment by luacmartins** [comment]
No, I think we're good for now just need to get this deploy.

**Comment by DylanDylann** [comment]
No need payment here

**Comment by luacmartins** [comment]
We're good to close this one then!

**Comment by alexpensify** [comment]
Keeping closed and there is no Upwork job. No action on this payment date per this note: 


https://github.com/Expensify/App/issues/42720#issuecomment-2166075734
