### ISSUE TITLE
Update SPMP Bonus file formats 

### ISSUE THREAD

**Issue by caitlinwhite1** [Expensify/App#42726]
[SO Link](https://stackoverflowteams.com/c/expensify/questions/17861)

For the following (as part of the step MORNING OF THE SPMP BONUS - STEP 1 preparer), we need to update the Alteryx file outputs. 

- Files outputs to update: **Shareworks Umbrella Grant and Shareworks Employee Grant Allocation**
- The date format should be: **DD-MMM-YYYY** for these columns : **Vest Date | Service Date | Expiry Date**
- The Vesting Rule column needs to be updated to I**MMEDIATE** only the **Shareworks Employee Grant Allocation** has this column

Separate from the file, we should also update any of the shareworks emails that mention David!

**Comment by saracouto** [comment]
@caitlinwhite1 I have made these changes, but lmk if it shouldn't be that way:
- Updated the vesting rule from `Immediate` to `IMMEDIATE`
- All the dates are populated as YYYY-MM-DD. You specify a different format, but is that correct?
- I changed the shareworks outputs to be excel, instead of CSV!

**Comment by caitlinwhite1** [comment]
Thank you! This looks good.

The only thing we're not 100% sure of is if the excel format is what's causing the file error on their side. I'll close this issue out if that works today though!

**Comment by saracouto** [comment]
Great! I think bc of excel, the date format will be picked up by their system regardless, but let's see! 🤞 

It'll take me 2 minutes to update anything needed, so keep me posted!

**Comment by caitlinwhite1** [comment]
@saracouto Looks like a couple more adjustments still

Dates = DD-MMM-YYYY
Correct award type = RSU - Expensify, Inc.


Then included their files in the email chain for comparison but leaving those out of GH

<img width="740" alt="Screenshot 2024-05-29 at 3 13 45 PM" src="https://github.com/Expensify/App/assets/13949826/585bcf3f-82b6-4aa0-9218-f9914a990e37">

**Comment by saracouto** [comment]
Thanks Caitlin! I have no idea why this is required now, but I'll update tomorrow!

**Comment by caitlinwhite1** [comment]
Yes, something new every time, lol. Thanks Sara!

**Comment by saracouto** [comment]
Updated the grant name to add the `.` at the end and updated the 5 date fields to show as SWs wants them:


<img width="129" alt="image" src="https://github.com/Expensify/App/assets/20526257/995d60ff-d604-44ea-8347-4a5b5482aae7">
<img width="263" alt="image" src="https://github.com/Expensify/App/assets/20526257/f4a8896a-c24f-40f6-a444-ea94eb015019">
<img width="326" alt="image" src="https://github.com/Expensify/App/assets/20526257/8b498d32-48b9-4247-af81-d6a69a9d5258">

**Comment by saracouto** [comment]
Closing, @caitlinwhite1 feel free to reopen it if more things are needed!

**Comment by caitlinwhite1** [comment]
For the draft paycheck upload(discussed [here](https://expensify.slack.com/archives/C01TF865XTL/p1717021039750089?thread_ts=1716890114.930929&cid=C01TF865XTL)), we need to add in the headers!

Feel free to just grab them from [here](https://docs.google.com/spreadsheets/d/1kg9OL3uTEVsyFIamtF9mUpw4GinNV0BpQMs_xRwb30M/edit#gid=970106905)

**Comment by saracouto** [comment]
Updated now, I just had to click the ✅ 
<img width="1443" alt="image" src="https://github.com/Expensify/App/assets/20526257/e66fc364-6adb-45a9-a1c5-539ad0b42158">
