### ISSUE TITLE
[HOLD for payment 2024-06-13] [LOW] [Performance] Improve AppNavigator Performance

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42744]
Coming from [here](https://expensify.slack.com/archives/C05LX9D6E07/p1716915477598019). @rezkiy37 

### Problem
There is a core component of the app - [AppNavigator](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/index.tsx). Basically, it renders AuthScreens or PublicScreens based on a prop - authenticated. Currently, the component takes around 250ms to render. Also, it re-renders several times.

1. The component uses require to import children. I have a concern regarding this approach. Because require is a function in Node.js for importing modules. It’s synchronous and will halt execution until the module is loaded. It’s not typically used in the front-end code of a React application, as it doesn’t support code splitting or lazy loading. require might be used in certain scenarios, such as server-side rendering or when working with Node.js back-end code.
1. The component re-render several times, because the parent component re-renders. However, the property is not changed. Also, PublicScreens re-renders 3 times.

### Solution
I propose to decrease the render duration and avoid redundant re-renders.
1. React.lazy is a function that lets you render a dynamic import as a regular component. It makes it easy to code split a React application and lazily load components as they are needed, which can significantly improve the load time of your application. The idea is still the same as with require, but it takes much less time around 17ms for AppNavigator and Suspense together. The time 1. savings is great. Also it is a common practice for React apps.
Wrap the component in React.memo to get a memoized version of that component. And, as a result, AppNavigator renders once and does not re-render anymore until the user logins/logouts (authenticated changed). PublicScreens renders once as well.

T[here](https://github.com/Expensify/App/pull/42532/commits/00bc3407017f8cbdd8d6a2fc14a7f118560810dd) is a commit here. I am attaching screenshots with the legacy (the 1st) and updated (the 2nd) versions.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec3bf0fc8d2fa2f1</li>
        <li>Upwork Job ID: 1795785815695171584</li>
        <li>Last Price Increase: 2024-05-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by Julesssss** [comment]
Hey @rezkiy37, great work so far

**Comment by rezkiy37** [comment]
Measuring on IOS and Android Production-Release builds.

**Comment by c3024** [comment]
[Working on it](https://github.com/Expensify/App/issues/42744#issuecomment-2142534025)

**Comment by Julesssss** [comment]
PR is in draft, I'll generate testable builds soon

**Comment by alexpensify** [comment]
To prepare for the payment date, @c3024 please accept the invite here: https://www.upwork.com/jobs/~01ec3bf0fc8d2fa2f1. Tomorrow, I'll complete the payment process in Upwork. Thanks!

**Comment by c3024** [comment]
@alexpensify Thanks, accepted the invite.

**Comment by alexpensify** [comment]
Payouts due: 2024-06-13

- [x] Contributor: $250 @rezkiy37 - is from an agency-contributor and not due payment
- [x] Contributor+: $250 @c3024 - Paid via Upwork! 

Upwork job is [here](https://www.upwork.com/ab/applicants/1795785815695171584/hired).
