### ISSUE TITLE
[HOLD for payment 2024-06-13] User profile - App shows Hidden profile instead of not here page when profile link is invalid

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/42464
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Send a link of an invalid profile (https://staging.new.expensify.com/a/hellodsdsdsdsdsd
).
4. Click on the link.

## Expected Result:
App will show not here page.

## Actual Result:
App shows profile of a Hidden user.
When clicking on Message Hidden, the report shows error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a5ddc474-d2bc-461f-bdbc-d81f7aad867d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by izarutskaya** [comment]
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment]
Production 


https://github.com/Expensify/App/assets/115492554/ea39e6a6-f628-4d2f-8dd5-fefa654af196

**Comment by Kicu** [comment]
hey I did the PR that broke this, but I was originally tried to fix this problem: https://github.com/Expensify/App/issues/40989 which was exactly the reverse - that in offline mode we showed not found page.

However I see the underlying problem - in offline mode, when api is not available how can the App tell whether an email is valid or not?
This simple solution suggested above by @Tony-MK, that is adding `!isEmptyObject(details.avatar)` to the check will bring back this bug:  https://github.com/Expensify/App/issues/40989

I'm happy to provide a fix but Im not sure what behavior we want re: invalid profile/profile in offline mode?

**Comment by Kicu** [comment]
oh thanks for extra info 👍
But that seems weird that `accountID` is a string. Usually ids of workspaces/policies are strings, whereas if it's a user the `id` was always a `number`. The line responsible for parsing (`in ProfilePage`):
```
    const accountID = Number(route.params?.accountID ?? 0);
```
is not something I added - that was already there.

I will be monitoring this task if any further changes are needed but at this moment I'm unsure what I could fix/change.

**Comment by mountiny** [comment]
I will take this over as i am reviewer on that pr

**Comment by joekaufmanexpensify** [comment]
Thanks Vit!

**Comment by Kicu** [comment]
Okey great suggestion, thanks.
I will test this locally, do you want me to provide the PR @mountiny ?

**Comment by joekaufmanexpensify** [comment]
@Kicu yeah if you could raise a PR that would be great. Is there an ETA for when you could have one up?

**Comment by joekaufmanexpensify** [comment]
@Tony-MK generally we try have the same person who introduced a deploy blocker fix it, if they're available. We appreciate your enthusiasm though!

**Comment by Kicu** [comment]
I will do it

**Comment by mountiny** [comment]
Thanks for the discussion, I think that this is very specific flow that user will not really get into.

And if they will, the App works fine, and does not crash or anything so I think @Kicu @s77rt should fix this as the authors of the original PR with urgency, but I will remove the deploy blocker label

**Comment by Kicu** [comment]
PR with fix is here: https://github.com/Expensify/App/pull/42769

I hope there is no more edge cases for this view that I missed, but what I did should be equivalent to the code that was handling this previously

**Comment by joekaufmanexpensify** [comment]
PR awaiting deploy

**Comment by joekaufmanexpensify** [comment]
This was fixing a deploy blocker introduced from another PR that @Kicu and @s77rt worked on, so no payment is due here.

**Comment by joekaufmanexpensify** [comment]
Closing as this is on production, thanks everyone!
