### ISSUE TITLE
[HOLD for payment 2024-06-11] [HOLD for payment 2024-06-06]  Distance - Map preview shows "Map pending" instead of map on confirmation page and editor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- App location permission is disabled
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Distance
3. Enter waypoints > Next
4. Select a workspace > Next
5. Submit the expense
6. Click on the preview
7. Click on the preview again
8. Click Distance

## Expected Result:
In Step 4, map preview will appear on confirmation page
In Step 6, "Map pending" element will not appear outside the expense preview
In Step 8, map preview will appear on distance editor

## Actual Result:
In Step 4, map preview shows "Map pending" on confirmation page
In Step 6, "Map pending" element appears outside the expense preview
In Step 8, map preview shows "Map pending" on distance editor

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bfd03b75-035e-4b99-a93a-d8a952fe2af1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@grgia  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by grgia** [comment]
Hmm I think there's an issue with creating distance requests I noticed some tests were failing on a PR I was working on

**Comment by grgia** [comment]
<img width="754" alt="image" src="https://github.com/Expensify/App/assets/38015950/68189099-46f6-4dc9-934a-4e91967bc42b">

Im unable to replicate, thanks for jumping in @tienifr - let me know if you find anything
