### ISSUE TITLE
[HOLD for payment 2024-06-11] [HOLD for payment 2024-06-06] [$250] Chat - Display Name Appears Black and Members Not Ticked in Group Preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42751]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1, Navigate to FAB > Start Chat > Click on the "Add to Group" button associated with the email.
2, Notice that the display name appears black and the selected members are not ticked; the "Add to Group" button remains available.

## Expected Result:
Upon creating a group and clicking the "Add to Group" button, the display name should not appear black, and the "Add to Group" button should change to a tick.

## Actual Result:
Clicking the "Add to Group" button results in the display name appearing black, and the "Add to Group" button remains available without changing to a tick, contacts are hidden on the confirmation page and an error appears if you click Start group

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6eff3a05-f5c4-4fb6-b390-9b50416b6c30

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4959f53301769e3</li>
        <li>Upwork Job ID: 1795854006851895296</li>
        <li>Last Price Increase: 2024-05-29</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 102517509</li>
<li>Krishna2323 | Contributor | 102517511</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by izarutskaya** [comment]
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb.

**Comment by izarutskaya** [comment]
Production 

https://github.com/Expensify/App/assets/115492554/9f5c9d2d-f2dc-4ebf-91bc-211d3cbf81fd

**Comment by luacmartins** [comment]
@Krishna2323 are you available to work on a fix?

**Comment by luacmartins** [comment]
Cool, assigned you to the issue

**Comment by CortneyOfstad** [comment]
Not overdue!

@abdulrahuman5196 can you complete the checklist at your earliest convenience so there is not a delay in issuing payment? Thanks!

**Comment by CortneyOfstad** [comment]
Friendly bump @abdulrahuman5196 as payment is set for tomorrow. Thanks!

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/42170/files#r1633446096

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Navigate to FAB > Start Chat > Click on the "Add to Group" button associated with the email.
2) Verify that the display name appears correctly and the selected members are ticked.


@CortneyOfstad
