### ISSUE TITLE
[$250] Concierge chat is not rendering correctly in LHN when receiving pusher update from the migration script

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42759]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1716958715006149

## Action Performed:
Break down in numbered steps

1. Have an account with free policy that is going ot be migrated
2. Sign in to the admin account of the free policy
3. Turn on the focus mode and unpin the concierge chat if it was pinned
4. Sign out and sign back in
5. Log in as the admin again
6. run the migration script

## Expected Result:
Describe what you think should've happened

the concierge chat is correctly shown in the LHN with the avatar, report name and preview of the last message

## Actual Result:
Describe what actually happened

<img width="254" alt="image" src="https://github.com/Expensify/App/assets/36083550/5a18d334-f573-4cdc-84ad-a071475fd121">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015080d0a545598224</li>
        <li>Upwork Job ID: 1797360826457743360</li>
        <li>Last Price Increase: 2024-06-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by allroundexperts** [comment]
Looking for proposals

**Comment by jeremy-croff** [comment]
Is this external? Do we need the migration script to reproduce?

**Comment by MitchExpensify** [comment]
Can you share the migration script please @mountiny ? 🙇

**Comment by allroundexperts** [comment]
Still looking for proposals

**Comment by MitchExpensify** [comment]
[Bump](Can you share the migration script please @mountiny ? 🙇) @mountiny

**Comment by mountiny** [comment]
This has to be internal and the migration script is completed

So I guess free contribution for you Mitch. Closing :D
