### ISSUE TITLE
Distance - Missing tax rate and tax amount rows on confirmation page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42763]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/42342
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is tax-enabled.
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Distance.
3. Enter waypoints > Next.
4. Select a workspace > Next.

## Expected Result:
Tax rate and tax amount rows will be present on confirmation page (production behavior).

## Actual Result:
Tax rate and tax amount rows are missing on confirmation page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1cbb9fe7-b8d3-42ff-982d-2996d11df762

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #vip-vsb

**Comment by trjExpensify** [comment]
@kbecciv I can't tell from the video, did they enable **track tax on distance** on the workspace in OldDot or not?

**Comment by MonilBhavsar** [comment]
This is not a Web-E blocker at least, so removing label

**Comment by kbecciv** [comment]
It's working if user enabled the track tax on distance on the workspace in OldDot.

https://github.com/Expensify/App/assets/93399543/7dd60e84-7f41-446d-a630-72b10d70cbc5
