### ISSUE TITLE
Web - Bank account - Account number is not clickable after submitting empty info

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42768]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/21519&group_by=cases:section_id&group_order=asc&group_id=306204
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Workflows.
4. Click Connect bank account.
5. Click Connect manually.
6. Click Next button without entering anything.
7. Click Account number.

## Expected Result:
Account number is clickable.

## Actual Result:
Account number is not clickable.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/480ea585-24e8-44b3-8fd5-9613ef0b1511

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@kadiealexander FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment]
Solving this issue here - https://github.com/Expensify/App/issues/42767

**Comment by rlinoz** [comment]
This is fixed after this revert https://github.com/Expensify/App/pull/42777
