### ISSUE TITLE
[HOLD for payment 2024-06-13] [Search v1] Update memo functions in TransactionListItem

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#42774]
Coming from [here](https://github.com/Expensify/react-native-onyx/pull/552#issuecomment-2137489416), we need to update the memo functions in TransactionListItem to support live updates.

cc @jnowakow 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by allroundexperts** [comment]
@luacmartins Can I be added as a reviewer here?

**Comment by allroundexperts** [comment]
Do we have a PR for this? Who's working on it?

**Comment by luacmartins** [comment]
No PRs yet. I think @jnowakow will work on it once he's back from ooo on Monday

**Comment by jnowakow** [comment]
@luacmartins yeah, I'm working on it

**Comment by puneetlath** [comment]
The payment summary is correct. @allroundexperts please request on NewDot.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
