### ISSUE TITLE
Distance rates - Unable to enter the third decimal place value for distance rate

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42778]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace has enabled Distance rates.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Distance rates.
4. Click on any rate.
5. Click Rate.
6. Clear the amount.
7. Enter any amount with 3 decimal places.
## Expected Result:
User should be allowed to enter distance rate with 3 decimal places (production behavior), also, because the distance rate is always shown in three decimal places.

## Actual Result:
User is only able to enter at most two decimal places for distance rate.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [X] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e52df624-f261-414f-8d5c-af7f815982a0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@dylanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by jasperhuangg** [comment]
This PR seems to be the culprit: https://github.com/Expensify/App/pull/42426/files

**Comment by jasperhuangg** [comment]
@bernhardoj can you take a look and possibly get a fix up for this if it checks out?
