### ISSUE TITLE
[HOLD for payment 2024-06-13] [MEDIUM] Add "Schedule a demo" link to the Travel landing page

### ISSUE THREAD

**Issue by bfitzexpensify** [Expensify/App#42776]
We need to add a `Schedule a demo` link to the Travel landing page:

![image](https://github.com/Expensify/App/assets/38236554/ce93f87d-c762-4caf-81d7-a1924dc11ca5)

This is how it should look:

![image](https://github.com/Expensify/App/assets/38236554/8014ab32-6a8f-4210-b650-887b8a163dc2)

I _think_ [this](https://github.com/Expensify/App/blob/db7fa86907d8b41065aa299d3d0b5192a7baf71b/src/pages/Travel/ManageTrips.tsx#L1) is where the code lives, but I am not 100% certain. 

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by twisterdotcom** [comment]
@rushatgabhane or @smelaa - would you like to take this one?

**Comment by rushatgabhane** [comment]
@twisterdotcom i can pick this

**Comment by twisterdotcom** [comment]
Assigning @shubham1206agra to review too then.

**Comment by dannymcclain** [comment]
I tossed the `design` label on here just to get eyes on the implementation. @dubielzyk-expensify nothing too wild going on here from a design standpoint, just want to make sure that button stack looks right. Feel free to reassign to me if ya wanna.

**Comment by rushatgabhane** [comment]
@dannymcclain is there a figma link? would be helpful for me to verify the spacing

**Comment by rushatgabhane** [comment]
PR ready here - https://github.com/Expensify/App/pull/42864

**Comment by dubielzyk-expensify** [comment]
Approved the PR 👍  Looking good

**Comment by twisterdotcom** [comment]
https://github.com/Expensify/App/issues/42073#issuecomment-2166943047

**Comment by JmillsExpensify** [comment]
@twisterdotcom mind confirming the payment summary above?

**Comment by twisterdotcom** [comment]
### Payment Summary
[Upwork Job](https://www.upwork.com/nx/wm/offer/102735169)
- Contributor: @rushatgabhane paid $250 via NewDot
- C+: @shubham1206agra paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/102735169)

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
