### ISSUE TITLE
[HOLD for payment 2024-07-17] Distance - Amount shows 0.03 instead of being blank when removing a waypoint offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42784]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a distance expense with three waypoints.
3. Go to transaction thread.
4. Go offline.
5. Click Distance.
6. Remove the last stop.
7. Save the new distance.

## Expected Result:
The Amount field should be empty while it is still pending (production behavior).

## Actual Result:
The Amount field shows 0.03.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/dbf59832-7f01-445d-a249-d1c36acc1da1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by m-natarajan** [comment]
@greg-schroeder FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
@nkdengineer @neil-marcellini @akinwale thoughts on https://github.com/Expensify/App/issues/42784#issuecomment-2138052077?

**Comment by nkdengineer** [comment]
It's late for me now. I'll create a PR to fix this bug in the morning.

**Comment by deetergp** [comment]
Should this continue to be a blocker till @nkdengineer comes back online and fixes it?

**Comment by greg-schroeder** [comment]
Let's remove it from the list of deploy blockers (requires being offline to reproduce, making it pretty low prio), but have @nkdengineer get a fix up tomorrow

**Comment by nkdengineer** [comment]
@akinwale The PR to fix regression here https://github.com/Expensify/App/pull/42833.

**Comment by deetergp** [comment]
Thanks for being on top of it. @fedirjh, it looks like you're the lucky reviwer.

**Comment by greg-schroeder** [comment]
Nice thanks @nkdengineer!

**Comment by luacmartins** [comment]
This happens offline, so not a web deploy blocker.

**Comment by akinwale** [comment]
I will review the PR.

**Comment by greg-schroeder** [comment]
Bump I think @akinwale and also @deetergp on this PR review: https://github.com/Expensify/App/pull/42833

**Comment by deetergp** [comment]
I ended up having nothing to do with that PR. Should @akinwale & @neil-marcellini be on this one?

**Comment by greg-schroeder** [comment]
This was a regression from https://github.com/Expensify/App/issues/41817
