### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Distance rates - Default distance rate is Disabled instead of Enabled after creating new WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42788]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces
3. Create a new workspace
4. Go to More features
5. Enable Distance rates
6. Go to Distance rates
7. Might need to go offline and repeat Step 3 to 6 if the actual result is not seen.

## Expected Result:
The default distance rate will appear Enabled in the list (should exhibit the same behavior with tax rates when enabling Taxes feature)

## Actual Result:
The default distance rate appears Disabled initially, then it changes to Enabled after a while

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/86724e4d-f356-449f-87e0-41b3029e02ee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190b7357307a90634</li>
        <li>Upwork Job ID: 1796304968558452736</li>
        <li>Last Price Increase: 2024-05-30</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102575239</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by puneetlath** [comment]
@trjExpensify or @mountiny mind confirming the expected behavior here?

**Comment by mountiny** [comment]
Yeah I think it should be enabled when the feature is turned on, this will probs be optimistic data fix

**Comment by trjExpensify** [comment]
> Yeah I think it should be enabled when the feature is turned on, this will probs be optimistic data fix

Yep, agreed. `Enabled` by default. 👍

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone.

I think we can just go with the [first proposal](https://github.com/Expensify/App/issues/42788#issuecomment-2138111442) from @Krishna2323 as it specifies the correct root cause and the fix.

@Nodebrute The incorrect optimistic value for distance rate is a legit point, but I think that's a nice to have addition instead of the actual issue on hand. I think we can handle it in the PR.

@cretadn22 I'd much rather specify the `enablement` explicitly rather than relying on default interpretation.

🎀 👀 🎀 C+ reviewed

**Comment by puneetlath** [comment]
I've paid @Krishna2323. 

@allroundexperts bump on the checklist for you.

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/23600
2. https://github.com/Expensify/App/pull/23600/files#r1650201035
3. N/A
4. A regression test would be helpful. The steps given in the OP look good to me!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
