### ISSUE TITLE
Android - Login - Tapping magic link shows incorrect error message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42794]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Enter an email id
3. Tap continue
4. From gmail, tap magic link

## Expected Result:
Tapping magic link must not show incorrect error message

## Actual Result:
Tapping magic link shows incorrect error message " The given email id is not valid."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/571fe810-557f-4c41-8f7a-ae49f5794100

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
Production:

https://github.com/Expensify/App/assets/78819774/ced47bf6-b814-4a86-85cc-b0fa68e7e760

**Comment by alexpensify** [comment]
I have a Pixel device and am unable to replicate this experience. I was able to exit the application, request a new magic link, click the magic link, and sign in.

**Comment by alexpensify** [comment]
@lanitochka17 - can you please confirm if this email should be one that's not associated with an Expensify account? That's not clear in the steps.

**Comment by marcochavezf** [comment]
I also tested with a OnePluse and didn't experience the issue. I will close it out, but feel free to re-open it if you're still experiencing
