### ISSUE TITLE
Chat - Android - First line blinks when go to second line on chat composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a98@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New dot app
2. Open any chat
3. Type first line text
4. Go to second line

## Expected Result:
No text should blink

## Actual Result:
First line blinks when go to second line on chat composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3ee34804-65f2-43fa-aef9-cddb35d29a66

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment]
going to close as I think we have a more pressing things to work on at the mo - will reopen once we're able to focus more on polish
