### ISSUE TITLE
Sign in - Unable to Google/Apple sign in

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2661814
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition: user has google and apple id accounts.

1. Open desktop app
2. Click on the Apple (or Google) button
3. Enter or select Apple (or Google) account
4. When redirected to a browser tab, click on pop-up to open desktop app

## Expected Result:
User is signed in with an Apple (or Google) account.

## Actual Result:
Sign in page opens again.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/29da53e8-0fb7-4389-967e-6301b3ff3ec5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
This was a backend blocker and its now resolved.

**Comment by mountiny** [comment]
Coming from this thread https://expensify.slack.com/archives/C049HHMV9SM/p1717069114614249?thread_ts=1717054355.084129&cid=C049HHMV9SM this seems to be broken for desktop

QA is verifying if this is repro in production too

**Comment by joekaufmanexpensify** [comment]
Discussing in the slack thread

**Comment by roryabraham** [comment]
Closing this as it's fixed
