### ISSUE TITLE
[HOLD for payment 2024-06-13] Distance tax - Tax rate and amount rows are not updated when changing distance rate offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42800]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42342
## Action Performed:
Precondition:
- Track Tax distance is enabled on Old Dot.
- Workspace has a few distance rates and tax rates
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Open submit distance expense flow
4. Proceed to distance expense confirmation page
5. Click Distance rate
6. Change distance rate
7. Note that Tax rate and tax amount rows are updated
8. Go offline
9. Repeat Step 3 to 7

## Expected Result:
Tax rate and tax amount rows will be updated when selecting a distance rate in offline mode

## Actual Result:
Tax rate and tax amount rows are not updated when selecting a distance rate in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9e0103fe-e45f-44c0-be32-58722f639b94

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

**Comment by lanitochka17** [comment]
@tylerkaraszewski  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by MonilBhavsar** [comment]
cc @narefyev91

**Comment by luacmartins** [comment]
This happens offline, so not related to Web deploy. Removing `DeployBlocker` label for web.

**Comment by MonilBhavsar** [comment]
Happens offline so we're demoting from blocker

**Comment by MonilBhavsar** [comment]
PR is deployed. No action is required here
