### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] [MEDIUM] Add "View Trip Details" row to newDot trip expenses

### ISSUE THREAD

**Issue by twisterdotcom** [Expensify/App#42814]
Add a link out to https://www.travel.expensify.com/trips/$tripID/ on each trip expense booked with Expensify Travel

![image](https://github.com/Expensify/App/assets/9133401/7d7b18bf-e7f9-41d3-b341-855a239d7e91)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by twisterdotcom** [comment]
I will do a manual contract for this

**Comment by rushatgabhane** [comment]
PR ready but asked a question - https://expensify.slack.com/archives/C05S5EV2JTX/p1717541642620689?thread_ts=1717456351.988119&cid=C05S5EV2JTX

**Comment by twisterdotcom** [comment]
How is this going now @rushatgabhane? Latest update from yesterday here: https://github.com/Expensify/App/pull/43081#issuecomment-2164125525

**Comment by rushatgabhane** [comment]
We had some TS issues in `main`, all resolved and ready to merge.

**Comment by twisterdotcom** [comment]
No need for regression steps here. Will pay out on 28th.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @rushatgabhane paid $250 through NewDot Manual Requests (Contributor)
- @shubham1206agra paid $250 [here](https://www.upwork.com/nx/wm/offer/102912029) (C+)

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
