### ISSUE TITLE
[HOLD for payment 2024-06-06] Concierge - User not getting logged in to ND when clicking on concierge button in OD

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4585786
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log out
2. Log in to OD and log out of ND if you get redirected
3. Click on the concierge bubble

## Expected Result:
User gets redirected to ND and logged in, concierge chat is opened

## Actual Result:
User redirected to the ND login page. The same behavior is observed when clicking on the "Reply in thread" link in the expense report in OD.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5c8332f8-d6d1-4989-be24-befa6b1fd50b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by izarutskaya** [comment]
@CortneyOfstad I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by izarutskaya** [comment]
Production 

https://github.com/Expensify/App/assets/115492554/8c1c8cd9-8fc5-47aa-9917-45ce50246a83

**Comment by CortneyOfstad** [comment]
Thanks @techievivek!

**Comment by techievivek** [comment]
I am seeing a logout call everytime we authenticate use with shortlived token. I am taking a look at deployed PRs to see if I can find anything but for now I am clueless why this would be happening.

**Comment by luacmartins** [comment]
Seems to be App related since we're making a LogOut call

**Comment by techievivek** [comment]
Seems like it is related to https://github.com/Expensify/App/pull/41764

**Comment by techievivek** [comment]
Fixed here: https://github.com/Expensify/App/issues/42822

**Comment by techievivek** [comment]
Closing since it's fixed and cherry-picked. No payment is due here.
