### ISSUE TITLE
Category-Inconsistency in display of long category in mweb&Android

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42825]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4585727
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app/mweb
2. Tap profile --- workspaces -- workspace
3. Tap more feature -- enable category
4. Tap category -- add category
5. Enter [Tinka@1246yyuuiiiiohagnlllkmmmmmmhgfgccnbbbbbbbbbbvgvvvcffddsssddfghjjjujbbbbggvcccc46u](mailto:Tinka@1246yyuuiiiiohagnlllkmmmmmmhgfgccnbbbbbbbbbbvgvvvcffddsssddfghjjjujbbbbggvcccc46u)
dryyhhvvcfdascvhhiiiu
6. Tap save

## Expected Result:
There should not be inconsistency in display of long category in mweb and Android

## Actual Result:
Inconsistency in display of long category name in mweb and Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7142861f-a1e0-40bc-9e76-28cb84024e0d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by abzokhattab** [comment]
The issue is not reproducible on the latest main on my emulator
<img width="383" alt="image" src="https://github.com/Expensify/App/assets/59809993/90ab1c70-7cfa-45b8-bd70-17c4e6534153">

**Comment by abekkala** [comment]
given this wasn't reproducible along with the fact that this seems like an extremely rare edge case I'm going to close

**Comment by abekkala** [comment]
Is the issue being reported that the style is incorrect when a new category name is added containing 100+ characters with no spaces? If so, I'm not sure that would be a typical issue we'd run into
