### ISSUE TITLE
Chat - Low application performance

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42838]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Low performance of application in different actions:
1. Login  (spinner after entering MC)
2. Closing account
3. Adding Bank account

## Expected Result:
Actions are performed in normal speed

## Actual Result:
Actions are taking a long time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5596ec69-075f-425f-b2e6-a39720f0935c

![Bug6495264_1717000372340!Screen_Shot_2024-05-29_at_7 26 30_PM](https://github.com/Expensify/App/assets/78819774/a2b0dde3-e5f6-4b17-bfae-0ea1dc63fad3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment]
Is this still happening @lanitochka17 - or was this just due to site slows earlier today?

**Comment by lschurr** [comment]
Going to close since I think this was just due to site slows last week.
