### ISSUE TITLE
[HOLD for payment 2024-06-13] [Wave Collect] [Xero] The error text shows while syncing

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#42837]
The error text shows briefly while syncing to Xero - whereas there is no error:

https://github.com/Expensify/App/assets/21549771/3e7b24c1-55ac-4f43-8816-1d0938f2c59f

**Comment by trjExpensify** [comment]
PR for this is merged awaiting the next deploy. https://github.com/Expensify/App/pull/42899

**Comment by trjExpensify** [comment]
@hungvu193 was paid centrally for this, closing.
