### ISSUE TITLE
[Awaiting Payment 22nd June] [$250] [Pending/Scanning] Card transactions show `Cash` in the expense preview instead of `Card`

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42832]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717026809436129

## Action Performed:

1. Incur a card transaction on an expensify card
2. Add a manual request to that same report

## Expected Result:
The expense preview should say Card for card transactions.

## Actual Result:
The card transactions show as Cash

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (2)](https://github.com/Expensify/App/assets/38435837/29abc3c8-e3c5-489d-bb46-f89b922b72b1)

![Snip - (72) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/239d0173-2783-4991-9f2f-f1c5efaa6721)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc32ffbea0b1bdc5</li>
        <li>Upwork Job ID: 1796170573012758528</li>
        <li>Last Price Increase: 2024-05-30</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 102573646</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by trjExpensify** [comment]
Oh hm, according to @kevinksullivan we'd implemented this one already with the original implementation, so this was a regression. Is that not the case? 

We show Expensify Card transactions in NewDot now, but the expense preview component reads `Cash` not `Card`. 

>If we only want to use Card for expensify card transactions then we can use check isExpensifyCardTransaction

If we did this, it wouldn't be future proof for when we show third-party card transactions, so I think a isCardTransaction check is better than isExpensifyCardTransaction check personally.

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- @parasharrajat $250 for the C+ review (feel free to request!) 
- @Nodebrute $250 for the fix (paid!)

Regression tests for the project will be added centrally. Closing!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
