### ISSUE TITLE
Workspace - Members, Distance rates, Categories, Tags and Taxes pages do not have a scroll bar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has long list of items in Members, Distance rates, Categories, Tags and Taxes
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Members
4. Scroll down
5. Repeat Step 3 and 4 with Distance rates, Categories, Tags and Taxes

## Expected Result:
Members, Distance rates, Categories, Tags and Taxes pages should have a scroll bar

## Actual Result:
Members, Distance rates, Categories, Tags and Taxes pages do not have a scroll bar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec454069-ded0-44b6-bc04-307bd483cc16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment]
In an ideal world, I agree there would be a scroll bar on all these pages. But the pages themselves do scroll fine. So I'm not sure we really need to prioritize going out of our way to add this, it doesn't feel super noticeable IMO. 

I think we should see if any actual customers flag feedback about this and revisit then.

**Comment by joekaufmanexpensify** [comment]
Closing for now, but LMK if anyone disagrees
