### ISSUE TITLE
Workspace - Sometimes double tapping on the member role isn't selecting it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42866]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with an expensifail account
2. Create a workspace
3. Invite a member
4. Navigate to the members list
5. Tap on the new member
6. Tap on "Role"
7. Double tap the currently unselected role
8. Repeat steps 7 and 8 until it happens

## Expected Result:
The role should be selected

## Actual Result:
Sometimes double tapping on the member role isn't selecting it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cc7bdad0-96e5-4eed-a9b6-14c13c553589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by trjExpensify** [comment]
I'm going to close this issue for #focus, as the likelihood of someone changing a workspace role repeatedly like that is incredibly small.
