### ISSUE TITLE
[Search v1] Filter Chronos transactions from Search results

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#42876]
Chronos transactions are returned as results in the Search page. We decided to filter these out [here](https://expensify.slack.com/archives/C036QM0SLJK/p1717103771461409?thread_ts=1716904547.165129&cid=C036QM0SLJK).

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by stephanieelliott** [comment]
Hey @luacmartins you're working on this, yeah? Any update?

**Comment by luacmartins** [comment]
Haven't started working on this yet, given it's low priority since it only affects internal accounts.

**Comment by luacmartins** [comment]
@JmillsExpensify are you still able to see Chronos transactions on the Search page? They seem to be gone for me, although I can still see them in OldDot

**Comment by luacmartins** [comment]
This is fixed. Closing!

**Comment by luacmartins** [comment]
This is happening again. Gonna reopen the issue to filter them out

**Comment by stephanieelliott** [comment]
This was deployed to Auth (production/authrock), seems like we are done here since it was all handled internally

**Comment by flodnv** [comment]
I can confirm they are gone after signing back in 👍
