### ISSUE TITLE
Tags - Delete pop-up briefly appears expanded at the bottom after deleting tag

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42886]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4587700&group_by=cases:section_id&group_id=296081&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Tags,
4. Add a tag.
5. Delete the tag.

## Expected Result:
Delete pop-up will disappear after deleting the tag.

## Actual Result:
Delete pop-up briefly appears expanded at the bottom after deleting the tag.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/88087f07-4136-4eea-8eab-35058b774e23

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@Christinadobrzyn FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by Christinadobrzyn** [comment]
hey @roryabraham and @getusha can you check out this to see if it's a regression from https://github.com/Expensify/App/pull/36292

**Comment by Christinadobrzyn** [comment]
Dmd @getusha and @roryabraham to check on this

**Comment by getusha** [comment]
https://github.com/Expensify/App/assets/75031127/d4793efd-cb17-4923-abf7-2df82e06e7ca

@Christinadobrzyn I am unable to reproduce this on `staging`

**Comment by Christinadobrzyn** [comment]
Thanks for retesting @getusha! I'm also not able to reproduce this. I'm going to see if QA can test.

**Comment by kavimuru** [comment]
@Christinadobrzyn not able to reproduce. 

https://github.com/Expensify/App/assets/43996225/c6f64e44-ffc9-4b4e-95b3-69b9e236dff1

**Comment by Christinadobrzyn** [comment]
Awesome! Let's close!
