### ISSUE TITLE
[Search v1] New Search Page - Page shows blank UI

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** n (test preference is not in production)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Access new.staging.expensify.com
2. Sign into a valid account
3. Go to Account Settings > Troubleshoot > New search page

## Expected Result:
User expects the new search page to show and display all IOUS

## Actual Result:
A blank UI is shown

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@alexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by alexpensify** [comment]
Moving this to Daily since help is on the way

**Comment by alexpensify** [comment]
@luacmartins It looks like the PR was rolled back, what's the plan for this one? Thanks for the update!

**Comment by luacmartins** [comment]
Correct, we reverted this PR along with many others due to the fire. However, we already merged the [re-revert PR](https://github.com/Expensify/Auth/pull/11139) and it should go out with the next Auth deploy

**Comment by luacmartins** [comment]
This is now fixed. We're done here
