### ISSUE TITLE
Android - Room mention - App crashes when copying #announce to clipboard

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #42176
**Version Number:** 1.4.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to #announce room.
3. Mention #announce and send it.
4. Wait until the message is really sent (if it is not actually sent, for example the sent message becomes grayed out when going offline, this issue is not reproducible).
5. Long press on the message > Copy to clipboard.

## Expected Result:
App will not crash.

## Actual Result:
App crashes.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/e9aa2463-7d53-44a6-9023-096195d7d4b9

[Bug6496937_1717132683457!QA.txt](https://github.com/user-attachments/files/15512710/Bug6496937_1717132683457.QA.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@luacmartins FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb

**Comment by MonilBhavsar** [comment]
Might be fixed by https://github.com/Expensify/App/pull/42914

**Comment by Beamanator** [comment]
being retestsed here: https://expensify.slack.com/archives/C9YU7BX5M/p1717168576319639

**Comment by kavimuru** [comment]
Bug is fixed 

https://github.com/Expensify/App/assets/43996225/aa3271e0-08bb-4697-898d-e3fd106d3b53
