### ISSUE TITLE
Emoji - When editing an emoji only message, the "Composer" is expanded

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42891]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #43615
**Version Number:** 1.4.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com and sign into a valid account
2. Open any chat
3. Send an emoji only message
4. Long-press/right-click on the message and choose Edit message
5. Observe the position of the green check mark and all other elements within the composer

## Expected Result:
User expects it to be centered

## Actual Result:
The composer is much "larger" than on Prod, leading certain elements to appear to be misaligned to the bottom margins.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/38042580-8c5b-490a-b95a-74c62192853f

<img width="1440" alt="Bug6496936_1717117919145!Button_is_misaligned_" src="https://github.com/Expensify/App/assets/43996225/7563a933-f816-4c4c-8ea3-41cb7ef9ab40">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment]
It's an expected change from this [PR](https://www.github.com/Expensify/App/pull/42615). We had a [discussion](https://www.github.com/Expensify/App/pull/42615#issuecomment-2136552715) there too.

**Comment by rlinoz** [comment]
@bernhardoj is right, so I will go ahead and close this one.
