### ISSUE TITLE
[HOLD for payment 2024-07-10] [Xero] Kill the XeroOnNewExpensify & AccountingOnNewExpensify betas

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#42904]
👋 I've added `*` to the `XeroOnNewExpensify` beta in prep to do the same with `AccountingOnNewExpensify` to reveal the `Accounting` page for access to both Xero and QBO when everything is deployed in the next couple of days. 

I'm creating this issue to just remind us to kill these betas at some point next week when the dust settles and everything is released. 👍 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Xero was released to all yesterday, so I'm going to settle up with the C+ team that worked on this project. Payment summary as follows:

@mananjadhav @hungvu193 @rushatgabhane  - $5k each for both contributor and contributor plus duties across all issues for the Xero project. Hans, I've sent an offer on Upwork. Manan and Rushat, you can request.

**Comment by mananjadhav** [comment]
Thanks, I've requested the payout.

**Comment by hungvu193** [comment]
Accepted the offer. Thank you 🙏

**Comment by rushatgabhane** [comment]
Created a manual request. Thank you!!

**Comment by JmillsExpensify** [comment]
$5,000 approved for @mananjadhav

**Comment by JmillsExpensify** [comment]
$5,000 approved for @rushatgabhane

**Comment by trjExpensify** [comment]
@mountiny I reckon we can move forward and kill these betas this week. You still up for helping on that?

**Comment by mountiny** [comment]
@trjExpensify sure 

@mananjadhav or @rushatgabhane or @hungvu193 either of you like to create an App PR to remove these betas from App? I can remove it from the backend after they are gone from App for couple of releases

**Comment by rushatgabhane** [comment]
hey yeah should be simple

**Comment by hungvu193** [comment]
I created a PR here @mountiny

**Comment by mountiny** [comment]
App PR merged and Web PR created https://github.com/Expensify/Web-Expensify/pull/42479

I am going to get that merged only once the App changes are in production

**Comment by trjExpensify** [comment]
That's on prod now, right? So can we get the Web PR merged?

**Comment by mountiny** [comment]
> That's on prod now, right? So can we get the Web PR merged?

It is, but I would like to wait a bit to make sure users have time to update the app. If the beta is removed and user has an old client, the connection would not show up for them. 

I know many real customers still not using this but just to be safe do not want to rush it

**Comment by trjExpensify** [comment]
Cool, sounds good!

**Comment by trjExpensify** [comment]
Payment won't be due here, right? But we're still holding on this WebPR of Vit's before closing this out.

**Comment by rushatgabhane** [comment]
yep

**Comment by mountiny** [comment]
Yeah I think we can merge it tomorrow

**Comment by trjExpensify** [comment]
Cool, let's get it merged today then. 👍

**Comment by trjExpensify** [comment]
Web PR hit staging 4 hours ago, hopefully we auto-close after tomorrow's deploy.

**Comment by trjExpensify** [comment]
Didn't auto-close, but closing.
