### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] [HIGH] [API] OpenWorkspaceView API call is made on pages that do not need it

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#42900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Go to settings
2. Navigate to workspaces
3. Select a workspace
4. Notice that `OpenWorkspaceView` API command is called

## Expected Result:
Describe what you think should've happened

this command is used to load bank account data and it should be called in Workflows page and/ or some other pages where we might need the bank account information for the policy, paid or free (still since migration is not complete)

## Actual Result:
Describe what actually happened

This is being called on pages where the bank account details are not needed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3a5ef10ba51590e</li>
        <li>Upwork Job ID: 1796465195576598528</li>
        <li>Last Price Increase: 2024-05-31</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 102543634</li>
<li>abzokhattab | Contributor | 102543638</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by mountiny** [comment]
either we need to refactor this code so the API call is not in the `WorkspacePageWithSections` component as then people will forget to pass the shouldSkipVBBA call - that would be ideal, or we make that param required and pass it everywhere

**Comment by abzokhattab** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The problem we are trying to solve is that the `OpenWorkspaceView` API call is being made on pages that do not require it. This results in unnecessary API calls, which can lead to performance issues and inefficient use of resources.

### What is the root cause of that problem?
The root cause of the problem is that the `OpenWorkspaceView` API call is embedded within the WorkspacePageWithSections component. This leads to the API call being executed regardless of whether the page actually requires bank account information, as the component does not conditionally skip the API call when it is not needed.

### What changes do you think we should make in order to solve the problem?
To solve this problem, we propose the following changes:
- Refactor the WorkspacePageWithSections component to remove the OpenWorkspaceView API call.
- Introduce a conditional parameter (e.g., shouldSkipVBBA) that determines whether the OpenWorkspaceView API call should be made.
- Ensure that the parameter shouldSkipVBBA is required and passed explicitly wherever the WorkspacePageWithSections component is used.
- Update all relevant pages and components to correctly utilize the shouldSkipVBBA parameter, making sure that the OpenWorkspaceView API call is only made on pages where bank account details are actually needed.
These changes will prevent unnecessary API calls, improving overall performance and resource utilization.

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Describe what actually happened

### What is the root cause of that problem?
The `OpenWorkspaceView` is in the `WorkspacePageWithSections` component, we already have `shouldSkipVBBACall` to control whether API call is needed, but we forgot to pass it in some cases

### What changes do you think we should make in order to solve the problem?

- Makes `shouldSkipVBBACall` a required param, so we never forget it
- Review all usages of `WorkspacePageWithSections` to see which really needs the VBBA data, and pass `shouldSkipVBBACall` as `true` or `false` as needed

### What alternative solutions did you explore? (Optional)
NA

**Comment by truph01** [comment]
> people will forget to pass the shouldSkipVBBA call - that would be ideal, or we make that param required and pass it everywhere

@mountiny I think we can make `shouldSkipVBBACall` true by default, so people won't be able to "forget" it. If they want the call to happen, they will need to explicitly pass `shouldSkipVBBACall` as false

**Comment by truph01** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/42900#issuecomment-2141549569) to add [the above suggestion](https://github.com/Expensify/App/issues/42900#issuecomment-2141552585) as alternative solution

**Comment by truph01** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/42900#issuecomment-2141549569) to mention the specific case of Workflows page and what we should do with it.

@mountiny I see you mentioned in the OP 
> this command is used to load bank account data and it should be called in Workflows page

But I think:
> the better solution here is to add the VBBA data to the OpenPolicyWorkflowsPage API response (if not already) which the Workflows page already called. This will help us maintain 1:1:1 rule.

@mountiny What do you think?

**Comment by abzokhattab** [comment]
### [Proposal Updated](https://github.com/Expensify/App/issues/42900#issuecomment-2141539867) 

added an optional improvement and an alternative solution

**Comment by truph01** [comment]
@hoangzinh @mountiny Just so there's no confusion when viewing proposals, @abzokhattab's proposal was posted before me but have these 2 points which are incorrect:
- Refactor the WorkspacePageWithSections component to remove the OpenWorkspaceView API call. (The API call is important and should stay)
- Introduce a conditional parameter (e.g., shouldSkipVBBA) that determines whether the OpenWorkspaceView API call should be made. (the prop already exists so there's no need to add a new one)

Which were later updated after I posted mine

**Comment by jasperhuangg** [comment]
Thanks for the investigation. Agree that @abzokhattab's alternative proposal is the only one that follows the pattern prescribed by Vit. Assigned!

**Comment by truph01** [comment]
Hi @jasperhuangg @hoangzinh I think having different components/hooks with small little variations from each other is a discouraged pattern in the app.

That was why when there're variations, we made it props of `TextInput` component instead of creating different components/hooks to provide the feature.

**Comment by truph01** [comment]
> either we need to refactor this code so the API call is not in the WorkspacePageWithSections component as then people will forget to pass the shouldSkipVBBA call

Regarding @mountiny's suggestion, the goal is to avoid `as then people will forget to pass the shouldSkipVBBA call`, I believe not specifically to move the API call outside.

There're other simpler and good-pattern approaches to achieve the same goal without doing the small-variation component/hook
> @mountiny I think we can make shouldSkipVBBACall true by default, so people won't be able to "forget" it. If they want the call to happen, they will need to explicitly pass shouldSkipVBBACall as false, if it's omited, the API call will not happen.

**Comment by truph01** [comment]
@jasperhuangg @hoangzinh Here's the issue where we decided to merge many types of inputs with small variations
(`ExpensiTextInput`, `TextInputAutoWidth`, `TextInputFocusable`, ...) into one and use props to enable the feature, for your reference 👍

**Comment by truph01** [comment]
@jasperhuangg @hoangzinh Do you have any feedback on [the concern above](https://github.com/Expensify/App/issues/42900#issuecomment-2142628086)?

Thank you!

**Comment by mountiny** [comment]
> making shouldSkipVBBACall by default true will solve the main issue and the API will not be called again. It may be better than creating a clone component with a simple adjustment!!

I think that is also a valid approach; the default should be that we do not call the API command and specify the param only if we need it.

I think that we should go with this path instead of a new hook. I did not mean to suggest that refactoring the code is a must, we also need to be aware of the growing number of wrappers and HOCs. This was still up for discussion 

I think we should go with the proposal from @truph01 as that was the first proposal stating this path.

@jasperhuangg @hoangzinh how does that sound?

**Comment by jasperhuangg** [comment]
I agree, I think we should modify the things we send to the API command itself as opposed to adding new code that could complicate things.

**Comment by jasperhuangg** [comment]
@dragnoir Agree, after checking it seems you would be right, let's move forward with your proposal.

**Comment by truph01** [comment]
> @hoangzinh: Hold on, based on Github history, it appears that @truph01 updated his alternative solution before @dragnoir's first proposal around > 10 mins.

@jasperhuangg Hey that's right, my alternative solution was already there 20 minutes **before** @dragnoir posted his first proposal. I even added that suggestion as [a comment](https://github.com/Expensify/App/issues/42900#issuecomment-2141552585) before I added it to my proposal

![Screenshot (5)](https://github.com/Expensify/App/assets/170341821/5e486593-f58b-4a3f-a95c-33a83fc20833)

**Comment by truph01** [comment]
@dragnoir Isn't [this my proposal updated comment](https://github.com/Expensify/App/issues/42900#issuecomment-2141557240) 😅? I did right after I updated the proposal

> @truph01 also posted a proposal update here https://github.com/Expensify/App/issues/42900#issuecomment-2141557240

**Comment by truph01** [comment]
@dragnoir You can see it's right there above your proposal

<img width="829" alt="Screenshot 2024-06-01 at 1 19 11 PM" src="https://github.com/Expensify/App/assets/170341821/75bc9991-0508-4503-b715-3a9fb6e60fbd">

**Comment by truph01** [comment]
@hoangzinh Based on https://github.com/Expensify/App/issues/42900#issuecomment-2143212772, would you mind giving the "🎀👀🎀" comment again go @jasperhuangg is confident about who to assign?

TIA!

**Comment by mountiny** [comment]
To get this going, I am assigning @truph01, as they have posted this idea first, lets get the PR going as soon as possible please as its HIGH task to improve unnecessary API calls

**Comment by truph01** [comment]
Asked internal team in the [PR](https://github.com/Expensify/App/pull/42979#issuecomment-2148615000)

**Comment by jasperhuangg** [comment]
Seems like @mountiny has a handle on things so I'm going to unassign myself to look for something else to work on in #newdot-quality.

**Comment by greg-schroeder** [comment]
PR in review

**Comment by mountiny** [comment]
App PR merged, I think that ultimately though, we should update the API calls and return the necessary data in the OpenPolicyProfilePage

**Comment by greg-schroeder** [comment]
Processing today

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @truph01 - $250 - Upwork
C+: @hoangzinh - $250 - Upwork

**Comment by greg-schroeder** [comment]
@truph01 can you apply to the job in Upwork so I can pay you?

https://github.com/Expensify/App/issues/42900#issuecomment-2144010494

**Comment by greg-schroeder** [comment]
Bump @truph01

**Comment by greg-schroeder** [comment]
Bump again @truph01

**Comment by truph01** [comment]
@greg-schroeder Sorry for the delay, this is a HIGH issue so could you help to apply the `High Priority` issue that was missed out here, as also done in [this issue](https://github.com/Expensify/App/issues/40213#issuecomment-2093879555)

TIA!

**Comment by mountiny** [comment]
I have opened a backend Pr to add the bank account information to the auth call, but seems like the OpenPolicyProfilePage call was reverted so we need to bring that back first

**Comment by greg-schroeder** [comment]
@mountiny sorry so does that mean this wasn't implemented as expected, or just an addendum to the original PR?

**Comment by greg-schroeder** [comment]
@truph01 I'll handle the `High` thing but I really need you to apply to the job

**Comment by truph01** [comment]
> apply to the job

@greg-schroeder Done!

**Comment by greg-schroeder** [comment]
sent an offer

**Comment by truph01** [comment]
@greg-schroeder Accepted, thanks

**Comment by mountiny** [comment]
This was a required backend change to make it even better. We can soon proceed with the auth change as we have re-reverted the app pr

**Comment by mountiny** [comment]
The Auth PR was merged

**Comment by greg-schroeder** [comment]
On staging

**Comment by greg-schroeder** [comment]
This is for the backend PR, no contributors were involved in that one
