### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250]  Tags - Enable tag option is no longer grayed out after renaming tag offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42917]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4587701
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Go to workspace settings
4. Go to Tags
5. Click on any tag
6. Disable or enable the tag
7. Note that the option grays out
8. Click on the tag name
9. Rename the tag

## Expected Result:
Enable tag option will remain grayed out after renaming tag offline

## Actual Result:
Enable tag option is no longer grayed out after renaming tag offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/757caa8b-1c7d-4ca3-8f92-ae521d85e43f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014348229109c8ccb2</li>
        <li>Upwork Job ID: 1798333089478942720</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102678138</li>
<li>allgandalf | Contributor | 102763005</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment]
I couldn't get the tag to disable offline when testing. @Krishna2323 are you getting a different result on Step 6?

**Comment by garrettmknight** [comment]
Cool - just replicated, opening up.

**Comment by garrettmknight** [comment]
@thesahindia looks like we've got a proposal here!

**Comment by garrettmknight** [comment]
@marcochavezf can you give this one a look?

**Comment by marcochavezf** [comment]
Thanks for the review @thesahindia, the proposal also looks good to me, assigning @Krishna2323  🚀

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @Krishna2323 $250 paid via upwork
- Reviewer: @allgandalf $250 paid via upwork

@allgandalf can you complete the checklist when you get a chance?

**Comment by garrettmknight** [comment]
Shouldn't be overdue?

**Comment by garrettmknight** [comment]
Done!
