### ISSUE TITLE
[$250] IOS - Security - Unable to open Security after closing the page quickly before it fully opens

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to Account settings
3. Tap Security
4. Quickly close the Security page by swiping right (not the back button) before it completely opens
5. Repeat Step 3 and 4 several pages

## Expected Result:
Security page can be opened without issue

## Actual Result:
Security page cannot be opened after closing the page quickly before it completely opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fefb15fe-5e5c-4193-925d-68d9edaf6d90

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0111e6da162358a7fc</li>
        <li>Upwork Job ID: 1798196089337692160</li>
        <li>Last Price Increase: 2024-06-26</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment]
ios <> android bug swap

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1718584335201769).

**Comment by kavimuru** [comment]
Tester is able to reproduce 

https://github.com/Expensify/App/assets/43996225/b4654256-9fb2-46df-b0ab-915ca62f99ca

**Comment by kadiealexander** [comment]
Not overdue

**Comment by kadiealexander** [comment]
Same as above.

**Comment by kadiealexander** [comment]
Still low priority, not worth increasing.

**Comment by kadiealexander** [comment]
Looking at this, it's a low impact issue that isn't affecting real world users, so I'm going to close it. Please reopen if you disagree.
