### ISSUE TITLE
Accounting - Error shows up while connecting to Xero for the first time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42913]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** **1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
Pre-requisite:
- Account should never had a connection with Xero before
- Test should be executed in a new browser which didn't create a xero connection before

1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Go to more features and enable accounting
4. Open accounting and set up a new Xero connection

## Expected Result:
No error message should show up while Xero is finishing up the setup

## Actual Result:
"Couldn't connect to Xero" error appears while Xero is setting up the connection and the error message disappears after the connection is established

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/55210ccd-e2e5-41a2-bea8-f3b0025635d8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@twisterdotcom I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 

https://github.com/Expensify/App/assets/115492554/80733615-3e7b-4ba8-85bc-fe02ed6dfe73

**Comment by twisterdotcom** [comment]
Asking @lakchote or @hayata-suenaga if they want this: https://expensify.slack.com/archives/C036QM0SLJK/p1717152579841329

**Comment by twisterdotcom** [comment]
Given Xero isn't live for customers and you can just choose to sync it and resolve the error, I don't think this is a blocker though. Going to leave it as a Daily bug.

**Comment by trjExpensify** [comment]
We've fixed it here already: https://github.com/Expensify/App/issues/42837. PR for it [has merged](https://github.com/Expensify/App/pull/42899).

**Comment by twisterdotcom** [comment]
PAPOW

**Comment by trjExpensify** [comment]
PEWPEW
