### ISSUE TITLE
[$250] IOS - Chat - Show error when access start chat 2nd time in off-mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42916]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** crowdtest.expensify+test002@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42679
## Action Performed:
1. Go offline
2. Create a new room from FAB
3. Open the new room page again from FAB

## Expected Result:
Can start a new chat

## Actual Result:
Show error when access starts to chat 2nd time in off-mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/03e19876-7cfe-4951-9d7a-42ce47e9a989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136e2911a526a72fe</li>
        <li>Upwork Job ID: 1797891905991876608</li>
        <li>Last Price Increase: 2024-06-18</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by badeggg** [comment]
@dominictb Hi, do you know why `setIsInputInitialized(true);` is called many times in iOS when offline? I can not find out

**Comment by bernhardoj** [comment]
Same crash root cause as https://github.com/Expensify/App/issues/42824

<img width="416" alt="image" src="https://github.com/Expensify/App/assets/50919443/925c8e8e-9d07-44fa-91da-c94d66bff9d7">

**Comment by badeggg** [comment]
## [Proposal](https://github.com/Expensify/App/issues/42824#issuecomment-2149636667)

Same root cause with https://github.com/Expensify/App/issues/42824, same proposal

**Comment by kadiealexander** [comment]
@abdulrahuman5196 bump!

**Comment by kadiealexander** [comment]
Hey @ishpaul777 could you please review the proposals here? Thank you!

**Comment by kadiealexander** [comment]
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1718692179619699)

**Comment by kbecciv** [comment]
Issue is no longer reproduce!

https://github.com/Expensify/App/assets/93399543/2d499b9f-4083-41d8-8987-9a55d6c2c62c
