### ISSUE TITLE
 Chat - Messages does not arrive until open the chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42922]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4587255&group_by=cases:section_id&group_order=asc&group_id=295000
**Email or phone of affected tester (no customers):** gocemate+a113@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
1. Open user A and user B in different tabs
1. As user A send a message to user B
2. As user B open chat with user C
3. As user B take a note of the chat with user A

## Expected Result:
Latest sent message should be present on LHN

## Actual Result:
Messages does not arrive until user open the chat or refresh the page, no matter if there is a previous conversation between users or not

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1c14506e-d5c5-4d8d-b41e-a7d5157e605c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
This is a backend issue. I've seen it discussed internally in #newdot-quality. I actually think we already have an issue for it?

**Comment by JmillsExpensify** [comment]
We're working on this in #newdotquality so I'm going to close.

**Comment by izarutskaya** [comment]
This issue is still reproducible
Build v9.0.11-3

https://github.com/user-attachments/assets/760cc974-bcf7-42dc-8548-13f7ebaaf0fd

**Comment by m-natarajan** [comment]
This bug is reproducible in staging only. Should we create new GH?

**Comment by mallenexpensify** [comment]
Closing again, let's centralize to the below GH and[ this long-ass discussion in #newdot-quality  ](https://expensify.slack.com/archives/C05LX9D6E07/p1721919593110619?thread_ts=1721217121.843389&cid=C05LX9D6E07)
https://github.com/Expensify/App/issues/45356#issuecomment-2245838082
