### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$250] Taxes - User is able to add new tax rate using deep link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42925]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42192
## Action Performed:
Pre-requisite:
- Account should be integrated with a xero account which already had configured some taxes
(Use these guides to do that: https://central.xero.com/s/article/Add-or-edit-tax-rates-GL#:~:text=a%20tax%20rate-,In%20the%20Accounting%20menu%2C%20select%20Advanced%2C%20then%20click%20Tax%20rates,Click%20Save.
)
1. Navigate to staging.new.expensify.com
2. Import taxes on Accounted page if not already imported
3. Go to taxes page and deep link to add new tax rate page (i.e change the url to look like this: [https://staging.new.expensify.com/settings/workspaces/<WORKSPACE_ID>/taxes/new](https://staging.new.expensify.com/settings/workspaces/%3CWORKSPACE_ID%3E/taxes/new)

## Expected Result:
Not found page shows up

## Actual Result:
User is able to add a new tax rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e57a333f-e84a-4057-b8c8-131deb3fd256

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012da44be2618c21c5</li>
        <li>Upwork Job ID: 1797644044811587584</li>
        <li>Last Price Increase: 2024-06-03</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102596329</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by puneetlath** [comment]
@Ollyws do you want to take a look?

**Comment by JmillsExpensify** [comment]
Will approve the payment once I have the payment summary!

**Comment by puneetlath** [comment]
Payment summary: 
- C - @tienifr - $250 - paid via Upwork
- C+ - @Ollyws - $250 - to be paid via NewDot

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
