### ISSUE TITLE
Workspace - "Add" and "Delete" options aren't visible after disconnecting Xero

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42920]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #[42620](https://github.com/Expensify/App/pull/42620)
**Version Number:** 1.4.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Enable Accounting, Tags, and Taxes from the workspace settings
4. Connect to Xero
5. Disconnect from Xero
6. Navigate to the "Taxes" tab
7. Select a tax
8. Click on the "1 selected" button

## Expected Result:
"Add" and "Delete" options should be available.

## Actual Result:
"Add" and "Delete" options for Categories, Tags and Taxes are removed when connecting to an accounting integration. The options aren't visible when disconnecting the integration.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/367a6c3d-8747-4b74-83fb-1046b62e171f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
We think this bug might be related to #wave-collect - Release 2

**Comment by puneetlath** [comment]
Since the Xero integration isn't live yet, I don't think we need to treat as a deploy blocker. Let's handle as a normal bug.

**Comment by trjExpensify** [comment]
This is fixed in this PR which is merged awaiting a deploy to staging: https://github.com/Expensify/App/pull/42613
