### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Accounting - Tapping back from workspace settings page takes user back to Organizations page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42924]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Enable accounting in more features
4. Connect to Xero with two organizations
5. Open accounting page
6. Open Xero organization page
7. Select another organization
8. Tap on back icon at the top left from accounting page
9. Tap on back icon at the top left from Workspace settings page

## Expected Result:
App should navigate user to workspaces list page after tapping back from workspace settings page

## Actual Result:
App navigates user back to Xero organization selection page from Workspace settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/646ba4f5-efe5-48ae-86fa-90d36f7fcf75

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d365096f3f3bce65</li>
        <li>Upwork Job ID: 1800594530685488123</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 102732992</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by anmurali** [comment]
Hmm I cannot even get past step 4

https://github.com/Expensify/App/assets/14225673/e700f766-1c0e-4096-825a-1e8c333e5edb

**Comment by anmurali** [comment]
Gotcha. Going to slap a help wanted label on this.

**Comment by rushatgabhane** [comment]
is this issue only on organization page? @tienifr

**Comment by rushatgabhane** [comment]
let's fix it for all pages. 🎀👀🎀
https://github.com/Expensify/App/issues/42924#issuecomment-2144208297

**Comment by Julesssss** [comment]
@tienifr looks good. Let's remember to test with the Android back button, too. It should have the same expected behaviour.

**Comment by rushatgabhane** [comment]
Please assign me this issue, so that I don't lose track of it

**Comment by Julesssss** [comment]
Hey @tienifr is the a WIP PR?

**Comment by rushatgabhane** [comment]
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/41417


2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/41417/files#r1669152823


3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. - No. Pretty edge case

6. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by rushatgabhane** [comment]
@anmurali could you please attach a payment summary, thanks!

**Comment by anmurali** [comment]
Payment summary

- [ ] C+ @rushatgabhane $250 approved for New Dot
- [X] C @tienifr $250 approved via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved to @rushatgabhane

**Comment by JmillsExpensify** [comment]
$250 approved for @tienifr
