### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Category - No hover effect when hovering over selected parent category in the list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42936]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4587402
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has parent and child categories.
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Submit expenses > Manual
4. Proceed to confirmation page
5. Click Category
6. Select the Parent category
7. Click Category
8. Hover over Parent category in the list (not the parent category that is on the top, it is the category in the list with the child categories)

## Expected Result:
There will be hover effect when hovering over the selected parent category in the list, since the selected parent category is clickable

## Actual Result:
There is no hover effect when hovering over the selected parent category in the list when the selected parent category is clickable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dd2d67a0-9e9a-477d-b592-ef8cc6a0de76

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ca350329115f395</li>
        <li>Upwork Job ID: 1797858191261601792</li>
        <li>Last Price Increase: 2024-06-18</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 102784539</li>
<li>Krishna2323 | Contributor | 102860407</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by adelekennedy** [comment]
site's slow - pausing this for now

**Comment by adelekennedy** [comment]
Whoops - too fast, I'm not positive that we want to use a hover effect over the parent category. I'm not sure that we have another pattern like this we would be copying

**Comment by adelekennedy** [comment]
adding design label here!

**Comment by adelekennedy** [comment]
@dannymcclain gut check here on [this pattern?](https://github.com/Expensify/App/issues/42936#issuecomment-2148363174)

**Comment by dannymcclain** [comment]
Truthfully I don't even understand what is happening in that video. Why are there two `color` list items when you go in after selecting `color` the first time?

I think generally I agree with this statement though:
>disabled styles should only be applied to the options that can't be selected/deselected

**Comment by adelekennedy** [comment]
@thesahindia do any of the proposals above work in your opinion or, do you need more design input here?

**Comment by dannymcclain** [comment]
I mean honestly it looks super confusing to me. I feel like to actually fix this problem we need to figure out a better way of displaying parent and child categories, but that's likely out of scope for this right now. @Expensify/design any ideas here?

**Comment by shawnborton** [comment]
Yeah, I'm actually very confused about what I am even looking at. In the most recent screenshot, is the Category called "Color" selected? If so, why does it have indented children?

**Comment by dubielzyk-expensify** [comment]
Agree with you @dannymcclain that we need to figure out multi-level select lists. I'll put it on the list for this week to explore some options. I feel like we've done it already, but think it's smart to revisit this one

**Comment by adelekennedy** [comment]
I think that's correct @ishpaul777, I think the design bug still needs to be discussed and we should move forward with a fix now if we can

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @Krishna2323 - Upwork
- [ ] Contributor+: $250 @ishpaul777  - Upwork

just pending the checklist

**Comment by adelekennedy** [comment]
https://github.com/Expensify/Expensify/issues/414455
