### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [Search v1] Expense report totals are negative in Shared search page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#42935]
Expense report totals are negative in the new Shared search page. Additionally, the total is not aligned with the table header

![Screenshot 2024-05-31 at 9 19 10 AM](https://github.com/Expensify/App/assets/22219519/ff699b47-d0be-4a33-8cfc-774e57dab2d5)

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment]
Things are movin

**Comment by dylanexpensify** [comment]
Coming up

**Comment by dylanexpensify** [comment]
today!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @allroundexperts $250

Please apply or request!

**Comment by dylanexpensify** [comment]
waiting for request

**Comment by allroundexperts** [comment]
@dylanexpensify I have noted it down. Feel free to close.

**Comment by luacmartins** [comment]
Closing as per the comment above

**Comment by JmillsExpensify** [comment]
Ah it's there, I just missed it! $250 approved for @allroundexperts
