### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] BUG: Failed distance request isn't cleaned up properly

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#42950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** main
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [applausetester+kh300501@applause.expensifail.com](https://www.expensify.com/_devportal/tools/logSearch/#query=email:(%22applausetester+kh300501@applause.expensifail.com%22)+AND+timestamp:[2024-05-31T04:07:52.416Z+TO+2024-05-31T06:07:52.416Z]&index=logs_expensify-028693)
**Logs:** [88c4715bea025f6f-SIN](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id%3A%2288c4715bea025f6f-SIN%22)
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/400806#top
**Issue reported by:** @neil-marcellini 
**Slack conversation:**

## Action Performed:

1. Log into NewDot
2. Create a workspace if needed
3. Go offline in the Network tab of dev tools, or using the force offline switch
4. Create a distance request on that workspace
5. Log into the same account on OldDot (expensify.com.dev)
6. Go to your group workspaces
7. Delete the workspace
8. Go back to NewDot, and go online
9. Verify the request fails to create
10. Click on the request
11. Verify there is an error message that says "Unexpected error submitting this expense. Please try again later. The workspace is no longer accessible. Please try again on a different workspace."
12. Click the X to dismiss the error

## Expected Result:
The failed request should disappear completely after the error is dismissed. The transaction report should be deleted and the request should be removed from the workspace chat. Everything needs to be cleaned up. The user can get navigated back the the archived workspace chat, or something like that.

We should also probably improve the error message, and have it translated vs only in English from the backend. Requesting copy now.

## Actual Result:
The transaction report remains with a RBR indicator, and the request is also still visible in the archived workspace chat

## Workaround:
Sign out and back in to clear all optimistic/failure data

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/26260477/6d951f2d-7b9f-4911-9d5a-12d7a561e075

![image](https://github.com/Expensify/App/assets/26260477/514dd2d0-6172-4f86-863b-aed44daddf8e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6ac9eda43aba0be</li>
        <li>Upwork Job ID: 1796631286961946624</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 102768394</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by goldenbear101** [comment]
could I take the job please

**Comment by mallenexpensify** [comment]
@CherylWalsh 👀 on [the above plz](https://github.com/Expensify/App/issues/42950#issuecomment-2142899326).
> Hi @CherylWalsh, could we please have your expertise in coming up with a helpful error message for the user to see in this case. It's likely to happen if they create a distance request while offline, and then before they go back online an admin deletes the policy, or removes them from it.

@sobitneupane 👀 on @dominictb 's proposal above. 

@goldenbear101 , plz review [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) if you'd like to contribute to the program.  Thx

**Comment by goldenbear101** [comment]
**Proposal**

Please re-state the problem that we are trying to solve in this issue.

The issue at hand is that the transaction report remains with a Retryable Blocked Request (RBR) indicator, and the request is still visible in the archived workspace chat after an error is dismissed.

**Root Cause**
When clearing the transaction error in `App/src/components/ReportActionItem/MoneyRequestView.tsx (line 349 in commit 0cb2dc0)`, the application only clears the transaction error. However, the transaction itself, the parent report action, transaction thread, IOU report, and report preview (if it is the only transaction in the IOU) still remain. Additionally, the application displays a generic backend error message, which should be updated to be more user-friendly and helpful.

**Proposed Changes**
To solve the problem, the following changes are recommended:

1. Enhanced Error Handling and Cleanup
When clearing the transaction error, check if the transaction has an error while pending creation (e.g., by verifying that the transaction has errors and the transaction thread report has` errorFields.createChat).`

```
onClose={() => { 
    // Check if the transaction has errors and the transaction thread report has errorFields.createChat
    if (transaction.hasErrors && transactionThreadReport.errorFields.createChat) {
        // Call the deleteMoneyRequest method to cleanly delete the transaction/money request
        deleteErroredTransaction(transactionID, reportAction);
    } else {
        // Clear only the transaction error
        clearTransactionError(transactionID);
    }
}}
```
2. Specific Steps for Cleanup
Implement the deleteErroredTransaction method:

```
function deleteErroredTransaction(transactionID, reportAction) {
    // Delete the transaction itself
    deleteTransaction(transactionID);

    // Delete the transaction thread report
    deleteTransactionThreadReport(transactionID);

    // Delete the IOU report and the IOU report preview report action in the chat report, if the transaction is the only one in the IOU report
    if (isOnlyTransactionInIOUReport(transactionID)) {
        deleteIOUReport(transactionID);
        deleteIOUReportPreview(transactionID);
    } else {
        // Delete the transaction report action in the IOU report, if there are other transactions in the IOU report
        deleteTransactionReportAction(transactionID);
    }

    // Navigate to the correct report after the deletion (either IOU report or chat report depending on if IOU report was deleted)
    navigateToCorrectReport(transactionID);
}
```
3. Method Implementation
Create a new method deleteErroredTransaction or modify deleteMoneyRequest to handle deletion for transactions with pendingAction: add without calling the API endpoint to delete.

javascript
Copy code
```
function deleteMoneyRequest(transactionID, reportAction, isSingleTransactionView = false) {
    if (transaction.pendingAction === 'add') {
        // Handle the deletion but do not call the API endpoint to delete
        deleteErroredTransaction(transactionID, reportAction);
    } else {
        // Existing delete logic
    }
}
```
4. Improved Error Messaging
Update the backend to provide clearer and translated error messages, or provide a translation key for error messages to enable translation in the frontend.

Backend:
```
app.post('/create-distance-request', (req, res) => {
    const { workspaceId } = req.body;

    // Check if the workspace exists
    const workspace = getWorkspaceById(workspaceId);
    if (!workspace) {
        return res.status(400).json({
            error: 'WorkspaceDeleted',
            message: 'The workspace is no longer accessible.',
            translationKey: 'workspace_deleted',
        });
    }

    // Handle the request creation logic
    // ...
});
```
FRONTEND:

// Display the translated error message
const errorMessage = translateErrorMessage(error.translationKey || 'genericCreateFailureMessage');
showError(errorMessage);

Alternative Solutions
As an alternative to using deleteMoneyRequest or an equivalent method, ReportActions.clearAllRelatedReportActionErrors for the linked report action in the IOU report of the transaction (as done previously) could also be a viable solution.

By implementing these changes, the failed transaction requests will be properly cleaned up, improving the user experience and ensuring the application state is correctly maintained.

**Comment by mallenexpensify** [comment]
@sobitneupane , 👀 on the proposals above plz

**Comment by goldenbear101** [comment]
I hope it's okay that I used AI to confirm my synopsis. I'm asking because I am new, If anything is needed to be cleared I would be more than happy to elaborate.

**Comment by sobitneupane** [comment]
Thanks for the proposal @dominictb 

> And a few other caveats/conditions and implementation details for the different deletion, we can look into the deleteMoneyRequest method above and make sure the transaction is cleanly deleted similar to in there. We can either create a new method deleteErroredTransaction, or in deleteMoneyRequest, if the transaction is pendingAction add, handle the deletion but do not call the API endpoint to delete, then we can use deleteMoneyRequest when the user closes the error.

I believe we can add a new parameter to determine whether to make api request or not.

> For the back-end error message, the back-end can provide a clearer translated message, or provide a translation key for the message which will enable translation in the front-end. 

How are we handling other server returned error/messages in the app? Do we return translation key?

Could you please provide more details about alternative solutions?

**Comment by neil-marcellini** [comment]
I don't think we should use the `deleteMoneyRequest` action for this, since that's not really what we're doing. We can re-use the code which sets up the optimistic data for it, and extract it into a separate function called `cleanUpMoneyRequest` or something similar.

For the errors, the backend is currently returning a descriptive error message. Maybe we could check for the exact error message, and then swap it out for a translation key on the frontend somehow? Would that work? That would be easiest and fastest. The error thrown from the backend is deep in a tree of functions so it would be kind of tricky to return a translation key. I could make it work, but would prefer not to.

**Comment by sobitneupane** [comment]
Waiting for update.
https://github.com/Expensify/App/issues/42950#issuecomment-2149311714
https://github.com/Expensify/App/issues/42950#issuecomment-2155536073

**Comment by CherylWalsh** [comment]
Ah missed this, I was OOO last week. 

Copy suggestion for error message
**The workspace you selected is no longer accessible, possibly because it has been deleted or you no longer have access to it.**

I don't think we want to include more details than that.

**Comment by mallenexpensify** [comment]
> I hope it's okay that I used AI to confirm my synopsis.

@goldenbear101 , sorry for the delayed reply.  I think many contributors us AI, often because English is a second language.  We don't have documentation for when or how to use AI, what I personally do is type out everything, reread it (and edit) then run it through AI to see if there are **parts** of my proposal/post that I can update.  That way it sounds like my voice.   I've also used https://hemingwayapp.com/ to help with long sentences.  (and... google docs for spell check can be helpful too)

**Comment by sobitneupane** [comment]
Thanks for the update @dominictb 

[The proposal](https://github.com/Expensify/App/issues/42950#issuecomment-2143339327) from @dominictb looks good to me. I am looking forward to the implementation.

🎀 👀 🎀 C+ reviewed

**Comment by mallenexpensify** [comment]
Thanks @sobitneupane , @neil-marcellini , 👀 on the accepted proposal above plz.

**Comment by neil-marcellini** [comment]
I think we'll have a lot of specifics to iron out in the PR, but I'm happy with the overall approach. Assigning now.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by neil-marcellini** [comment]
Still waiting for the PR, not overdue

**Comment by neil-marcellini** [comment]
We had a delay because I suggested using a new pattern in an attempt to improve the error message, but that had to get reviewed by the team and it was not approved. Now I'm requesting that @dominictb removes the error message swapping from the PR and we merge the rest of it.

**Comment by mallenexpensify** [comment]
Contributor: @dominictb paid $250 via Upwork
Contributor+: @sobitneupane due $250 via NewDot

@sobitneupane plz complete the BZ checklist above.

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/34087
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

Comment for similar issue : https://github.com/Expensify/App/pull/34087#discussion_r1690876725
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not required.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Log into NewDot
2. Create a workspace if needed
3. Go offline
4. Create a distance request on that workspace
5. Log into the same account, but in another device and delete the workspace on which distance request is created.
6. Go back to previous device, and go online
7. Verify the request fails to create
8. Click on the request
9. Verify there is an error message. 
10. Click the X to dismiss the error.
11. Verify that the transaction, transaction thread(if it is only transaction) and the request is removed from the app.

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane

**Comment by mallenexpensify** [comment]
Thanks @sobitneupane. Test case created

- https://github.com/Expensify/Expensify/issues/416543
