### ISSUE TITLE
Track - Chat header turns skeleton after submitting track expense to user with no chat history

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42960]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com 
2. Go to self DM.
3. Track a manual expense.
4. Click Submit it from the actionable whisper.
5. Select a user with no chat history (gmail user).

## Expected Result:
Track expense can be submitted to the user without issue.

## Actual Result:
After submitting the track expense to user without chat history,
- the chat header turns skeleton
- report title in LHN is blank
- the expense is missing in the chat.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/33a63a8c-2f2b-476b-ab85-ad996ddb9f24

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
Dupe, closing
