### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] Fix the style regression that removed the bold styling from the Switch component on cards

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#42998]
This [App PR](https://github.com/Expensify/App/pull/42596) caused a styling regression.

https://github.com/Expensify/App/pull/42596#issuecomment-2139064433

Bring the bold styling back to the Switch component.

**Comment by adelekennedy** [comment]
I think we're good to close here @hayata-suenaga - please reopen if I missed something!
