### ISSUE TITLE
[$250] [LOW] [Performance] Composer icons render after a delay in ios native 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43003]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.78-3
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Using a heavy account on iOS native
2. Open a report

## Expected Result:
Describe what you think should've happened

The chat report will load header and composer instantly while the report actions are loading (if not loaded before)

## Actual Result:
Describe what actually happened

The composer button ( + , emoji, send) are rendered with visible delay

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/36083550/e3a7faf3-6272-4509-b513-3f5ad64cf5d8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f9cab774d3c0b0b9</li>
        <li>Upwork Job ID: 1797672545084260352</li>
        <li>Last Price Increase: 2024-06-03</li>
    </ul>
</details>

**Comment by mountiny** [comment]
Called this out in the newdot-quality room

**Comment by ashuvssut** [comment]
> Using a heavy account on iOS native
What is a heavy account? Do you mean an account with lots of chats? 

Its not reproducible on my iOS Simulator

https://github.com/Expensify/App/assets/60546840/61fbe3ad-9f66-4e93-acee-6b0903228265

**Comment by Christinadobrzyn** [comment]
Hi @ashuvssut! Yes a heavy account would be an account that has lots of activity. 

- I don't see the issue in the video in the OP - but I can reproduce on iOS 13 V16.4. NewExpensify V1.4.78-3. 
- The composer is delayed when opening reports. 


https://github.com/Expensify/App/assets/51066321/7b2315a4-f205-4323-ac5e-149990353131

**Comment by war-in** [comment]
I can't reproduce it too. 

I wonder if @mountiny experienced it on a real device with the app installed or maybe on a simulator from a local build (main branch).

**Comment by mountiny** [comment]
This was on a real device with real account

I cannot reproduce anymore either

@burczu @war-in are you able to see anything from the provided logs and cpu profile?

**Comment by Christinadobrzyn** [comment]
Testing again - I think I'm still getting this on iOS 13 - I tested by: 

1. Send a bunch of reports to a test recipient account
2. Make sure the recipient account is not signed in
3. Sign in to the recipient account and click on the reports
4. Notice the reports take a while to initially load - once they've loaded once they load quick. 
5. Nothing is showing in the Browsertack console (but I'm not sure if I'm using it right). 


https://github.com/Expensify/App/assets/51066321/5d9e4d84-c0e9-4b80-8935-729a87c03a2e

**Comment by burczu** [comment]
> @burczu @war-in are you able to see anything from the provided logs and cpu profile?

@mountiny What logs are referring to? If you mean here: https://stackoverflow.com/c/expensify/questions/4856 - I don't have access to this page.

**Comment by mountiny** [comment]
@burczu Sorry, I think I have not gotten the logs for this flow, mixed it up with some other flow

I have noticed this happens on my device when I turn on the low energy mode, then it was very noticeable. Can that be tested in emulator?

**Comment by burczu** [comment]
> Can that be tested in emulator?

@mountiny unfortunately not, as far as I know

**Comment by mountiny** [comment]
Alright, I think I will close this as its not really that easy to debug for you and it would not be a good ROI
