### ISSUE TITLE
[Detailed Portion] Add GL/Payroll/Tax Codes to NewDot

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#43028]
# DESIGN DOC:  [Here](https://docs.google.com/document/d/1dkS0mceibjUCMErQ1mWgUHjdHH0Ti_39DvgntRG-sws/edit#heading=h.xbz08btaavfp)

Deadline: August 1st, 2024

Assignee: @rushatgabhane 

Price: $500

Coming from [this internal GH](https://github.com/Expensify/Expensify/issues/396303), we need a C+ to:
- [ ] Build new pages for adding GL Code and Payroll code to Categories/GL code to Tags/Tax code to Taxes 
- [ ] Build the menu items for Categories, Tags and Taxes
- [ ] Complete the onyx pieces (for offline first) for showing & modifying all the new data, etc.
- [ ] Fill these sections out in the above Design Doc

**Comment by dylanexpensify** [comment]
@rushatgabhane @Gonals is going to be our internal engineer on this!

**Comment by dylanexpensify** [comment]
Rushat killed it, waiting for implementation

**Comment by dylanexpensify** [comment]
@rushatgabhane mind giving us a breakdown of where we're at?

**Comment by rushatgabhane** [comment]
### Policy category - Add GL Code 
PR approved - https://github.com/Expensify/App/pull/43149
Backend merged

### Policy category - Add Payroll Code
Awaiting C+ review by @hoangzinh - https://github.com/Expensify/App/pull/43151
Backend merged


### Tags - Add GL Code 
Awaiting C+ review and backend is not deployed yet. - https://github.com/Expensify/App/pull/43155

### Taxes - Add tax code
Awaiting backend PR and deployment so I'm holding on that - https://github.com/Expensify/App/pull/43156

**Comment by dylanexpensify** [comment]
Ongoing! Mind giving an update here, @rushatgabhane ?

**Comment by rushatgabhane** [comment]
@dylanexpensify same as above.

Only thing is, the frontend is ready for Tax Code page - https://github.com/Expensify/App/pull/43156

**Comment by dylanexpensify** [comment]
Nice, thank you!

**Comment by rushatgabhane** [comment]
Update: All PRs except Tax code on production. 

Tax code - https://github.com/Expensify/App/pull/43156

**Comment by dylanexpensify** [comment]
NICE! Looks like Tax code is on prod as of 3 days ago 🎉 What's left for us to close this out and get you paid @rushatgabhane?

**Comment by rushatgabhane** [comment]
@dylanexpensify no all set!

**Comment by rushatgabhane** [comment]
@dylanexpensify i guess we're paying per issue? https://github.com/Expensify/App/issues/44255#issuecomment-2246108882

So $250 x 4 tasks. Does this sound right?

**Comment by dylanexpensify** [comment]
@rushatgabhane ah yeah, we can do by issue! Have they all had the payment summaries added?

**Comment by rushatgabhane** [comment]
@dylanexpensify yes they have. Thank you : )

**Comment by dylanexpensify** [comment]
nice! Great work here man!
