### ISSUE TITLE
[HOLD for payment 2024-06-13] Central pane padding changes when RHP is opened

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43031]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Go to some page that has a central pane from which you can open RHP so go to Settings > About
2. Click on the `App download links`
3. Notice how the central pane content shifts

## Expected Result:
Describe what you think should've happened

No shift in styles in the central pane

## Actual Result:
Describe what actually happened

Its alive, it moves

![CleanShot 2024-06-04 at 09 41 52](https://github.com/Expensify/App/assets/36083550/4d04afc3-3440-404d-a893-858c43c9d1b9)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by mountiny** [comment]
@rayane-djouah @getusha this is most likely a regression from https://github.com/Expensify/App/pull/36292 can you please confirm and handle this issue as such?

**Comment by roryabraham** [comment]
Sorry about that! I think I understand the problem. [useResponsiveLayout](https://github.com/Expensify/App/blob/2ebe8dae504bed7f5f0da8e4ebb925c199c10700/src/hooks/useResponsiveLayout.ts#L42) is correctly checking if there's a modal active, but it's not correctly checking that the current component is a child of that active modal. I will work on a fix for this ASAP

**Comment by roryabraham** [comment]
Here's my solution: https://github.com/Expensify/App/pull/43074

**Comment by roryabraham** [comment]
Put PR in for review: https://github.com/Expensify/App/pull/43074

**Comment by kevinksullivan** [comment]
@hoangzinh @getusha can you finish out the steps above?

**Comment by kevinksullivan** [comment]
It seems like only @hoangzinh requires payment for the PR review. Is that right?

**Comment by kevinksullivan** [comment]
hey @CortneyOfstad I am OOO the rest of the week so tapping you in here. Baed on the response to my question above I think we'll need to spin up a job and pay @hoangzinh this week. Thank you!

**Comment by CortneyOfstad** [comment]
@getusha or @hoangzinh — can you complete the checklist before EOD today so there is not a delay in payment tomorrow?

Per the SO [here](https://stackoverflowteams.com/c/expensify/questions/16949) @getusha gets paid via NewDot, but @hoangzinh I sent you an offer via Upwork [here](https://www.upwork.com/ab/applicants/1803430320121027611/job-details). Please let me know once you accept so I can get this paid ASAP tomorrow. 

Thanks!

**Comment by getusha** [comment]
@CortneyOfstad only @hoangzinh need to get paid. i wasn't involved thanks!

**Comment by CortneyOfstad** [comment]
No worries and thank you for confirming @getusha!

**Comment by CortneyOfstad** [comment]
Thanks @hoangzinh! Withdrew the proposal in Upwork and closing!
