### ISSUE TITLE
[HOLD for payment 2024-06-20] Group chat - Member amount is 0 when creating group chat offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43042]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-79-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Go to FAB > Start chat
4. Create a group chat with a few users
5. Tap on the chat header

## Expected Result:
Members will show the correct number of group members

## Actual Result:
Members show 0 when there are some group members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/905ae008-8945-4a61-b682-6cb6b778462c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @ShridharGoel</details>

**Comment by lanitochka17** [comment]
@aldo-expensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by aldo-expensify** [comment]
@francoisl I agree with @ShridharGoel on that this seems to have been cause by this change:

https://github.com/Expensify/App/pull/41290/files#diff-409b0e2fb439856e9897b808014031ce244a427d116ed30f37a2e0117599adc4R95-R97

What do you think of the proposed solution:

https://github.com/Expensify/App/issues/43042#issuecomment-2147926240

**Comment by aldo-expensify** [comment]
cc @NikkiWines ^

**Comment by aldo-expensify** [comment]
@ShridharGoel 

I don't think we should change to use `getVisibleChatMemberAccountIDs` for group chats since this exception was introduced by Marc here: https://github.com/Expensify/App/pull/39757/files#diff-409b0e2fb439856e9897b808014031ce244a427d116ed30f37a2e0117599adc4R84-R88, and I guess he had a reason for it.

**Comment by aldo-expensify** [comment]
Yep, that sounds like the easiest best fix. About the alternative solution, it does make sense to me, but I'm not 100% that there won't be regressions since the `participants` variable is used in multiple places below and I'm not familiar with the code.

**Comment by aldo-expensify** [comment]
Created PR here: https://github.com/Expensify/App/pull/43054

About assigning the issue, my thoughts are:

- @ShridharGoel found the root cause which saved a bunch of time. There is a detail in their proposed solution which made me not implement it exactly as it was proposed.
- @Nodebrute Proposed a very similar solution to the one proposed by @ShridharGoel, but without the problematic detail, so this is the one used in the end in this PR: https://github.com/Expensify/App/pull/43054

Would you accept sharing the reward?

**Comment by aldo-expensify** [comment]
> Anyways, let's end this here. I'm only interested in healthy discussions.

Thanks @ShridharGoel , I agree with that we should always aim to keep the discussion constructive

> However, I can point out multiple instances where you made minor adjustments to initial proposals and presented them as new proposals.

hmm presenting them as new proposals and getting them accepted as new proposals are two different things.

Maybe my suggestion on sharing the reward was not the best and the minor adjustments aren't really enough to share.
Sorry, for going back on my words, but I'll ask internally what do here.

**Comment by aldo-expensify** [comment]
> @aldo-expensify, @ShridharGoel first RCA was wrong.

This is @ShridharGoel first RCA:

<img width="628" alt="image" src="https://github.com/Expensify/App/assets/87341702/1fa1f45d-e0d0-42ba-a91e-42d7e649c447">

That RCA looks correct to me. @Nodebrute please don't add misleading information, it wastes time.

**Comment by aldo-expensify** [comment]
> @aldo-expensify his RCA was incomplete. @ShridharGoel failed to mention in Initial RCA that we're also excluding the current user from the group participants page.

Ah, I see what you mean now, but I consider that a minor detail.

**Comment by aldo-expensify** [comment]
I think strictly speaking @ShridharGoel is correct about that not being part of the issue reported.. but it is a good finding anyway.

So, summary:

1. @ShridharGoel posted first the correct RCA for the issue and proposed solution that has a potential flaw
2. @Nodebrute added more content to the RCA showing another problem and did a minor correction on the proposed solution
3. @ShridharGoel agreed to share
4. @Nodebrute didn't agree to share

I'm opinion, @ShridharGoel 's work was the most valuable contribution, with their initial RCA was enough for me to do the PR.

**Comment by aldo-expensify** [comment]
> @aldo-expensify Note: Only proposals with the right solution are selected. No one shares the reward for just identifying the RCA. It's draining my energy. It's up to you to decide, whatever you choose.

I'll get a second opinion on how to proceed.

**Comment by aldo-expensify** [comment]
Maybe, but I think we won't get much from continuing to point out these details. So I would suggest to stop discussing, I think there is enough information, and I'll just try to get a second pair of eyes.

**Comment by aldo-expensify** [comment]
Chatted about here: https://expensify.slack.com/archives/C02NK2DQWUX/p1717529970168019

Result: assigning @ShridharGoel since their first proposal / solution is enough. The detail that needed to be fixed about their proposed solution could have been adjusted during the PR phase.

**Comment by aldo-expensify** [comment]
@sonialiap summary:

- Assigned @ShridharGoel for compensation for the proposed solution / RCA
- There was no C+ review.

**Comment by roryabraham** [comment]
no longer a deploy blocker, has been fixed.

**Comment by sonialiap** [comment]
Payment summary:
- @ShridharGoel contributor $250 - offer sent

**Comment by sonialiap** [comment]
@ShridharGoel please accept the offer https://www.upwork.com/nx/wm/offer/102808386

**Comment by sonialiap** [comment]
@ShridharGoel please accept the offer. I've also sent you a message in Upwork in case you see that first

**Comment by sonialiap** [comment]
@ShridharGoel please complete the [checklist](https://github.com/Expensify/App/issues/43042#issuecomment-2165998110)

**Comment by sonialiap** [comment]
@ShridharGoel melvin assigned you to the regression part of the checklist
