### ISSUE TITLE
[HOLD for payment 2024-08-07] [QBO Export] Implement offline pattern B for manual report exports

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#43040]
- HELD on https://github.com/Expensify/App/issues/44022

# Part of [QBO Export and Error Handling in NewDot](https://github.com/Expensify/Expensify/issues/350150)
Doc section: https://docs.google.com/document/d/1aQl-AK_F6IqszWYG2aEllTsD5x3h4b8Zu0XEG0LuQ08/edit#heading=h.xw0s9oqvo44s
Project: https://github.com/orgs/Expensify/projects/129

# Feature Description
During review for the detailed design, we decided we should support offline pattern B when manually exporting reports [here](https://docs.google.com/document/d/1aQl-AK_F6IqszWYG2aEllTsD5x3h4b8Zu0XEG0LuQ08/edit?disco=AAABO4Akx_Y). To implement that we need to

- Create an optimistic `EXPORTINTEGRATION` action in our `Report.exportToIntegration` and `Report.markAsManuallyExported` actions
  - The text should say `started exporting this report to {integration}...`
- Pass the `optimisticReportActionID` to both `Report_Export` and `MarkAsExported` APIs
- Use the ID to create the action in Auth
  - Auth will queue updates for the report action with the final text: `exported this report to {integration}. [View out-of-pocket expenses].`
- On failure
  - create the `INTEGRATIONSMESSAGE` action with the error message like normal (using a different ID)
  - delete the optimistic action on the frontend using `failureData`

# Manual Test Steps

**Sucessful offline export**
1. Submit an expense report
2. Log in as the workspace admin
3. Approve the report
4. Go offline
5. 3-dot menu > Export > Quickbooks Online
6. Verify a semi-transparent `started exporting this report to QuickBooks Online...` message shows
7. Go online
8. Verify the action becomes fully opaque
9. Wait a few seconds
10. Verify the action updates to `exported this report to QuickBooks Online. [View out-of-pocket expenses].`

**Failed offline export**

Prerequisites
- Add a chart of account (category) to QBO that you can delete later

Steps

1. Create a report with an expense
2. Categorize the expense using the new QBO category
3. Submit it
4. Log in as the workspace admin and approve the report
5. Log into QBO and deactivate the chart of account for the category (Menu > Transactions > Chart of accounts > {account} menu > Make inactive)
6. Go offline in NewDot
7. Export the report to QBO (3-dot menu > Export > Quickbooks Online)
8. Verify a semi-transparent `started exporting this report to QuickBooks Online...` message shows
9. Go online
10. Verify the action becomes fully opaque 
11. Wait a few seconds
12. Verify a report export error message is added the report

# Automated Tests

- Verify optimisticData for the `INTEGRATIONSMESSAGE` is merged for both `Report.exportToIntegration` and `Report.markAsManuallyExported` actions
- Verify failureData removes the action

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by arosiclair** [comment]
cc @trjExpensify @lakchote @sakluger

**Comment by trjExpensify** [comment]
Sounds good, moved it into the release. 👍

**Comment by dylanexpensify** [comment]
Held!

**Comment by arosiclair** [comment]
Pointed the hold to https://github.com/Expensify/App/issues/44022

**Comment by trjExpensify** [comment]
^^ updated the title to reflect that.

**Comment by dylanexpensify** [comment]
held

**Comment by kosmydel** [comment]
Hey, I'm from SWM and I would like to work on this issue :)

**Comment by trjExpensify** [comment]
Assigned you! Going to remove the `Reviewing` label as there isn't a PR for this yet right?

**Comment by kosmydel** [comment]
> Assigned you! Going to remove the `Reviewing` label as there isn't a PR for this yet right?

Yep, we don’t have a PR for this yet.

**Comment by dylanexpensify** [comment]
Held

**Comment by arosiclair** [comment]
We had a discussion a few weeks ago about how the optimistic action should work [here](https://expensify.slack.com/archives/C036QM0SLJK/p1718037138317309?thread_ts=1717504451.168099&cid=C036QM0SLJK). TL;DR: this is mostly the same however the optimistic action should display a "starting..." text and the backend will update the text when it's completed:

```diff
  - Create an optimistic `EXPORTINTEGRATION` action in our `Report.exportToIntegration` and `Report.markAsManuallyExported` actions
+    - The text should say `started exporting this report to {integration}...`
  - Pass the `optimisticReportActionID` to both `Report_Export` and `MarkAsExported` APIs
  - Use the ID to create the action in Auth
+    - Auth will queue updates for the report action with the final text: `exported this report to {integration}. [View out-of-pocket expenses].`
  - On failure
    - create the `INTEGRATIONSMESSAGE` action with the error message like normal (using a different ID)
    - delete the optimistic action on the frontend using `failureData`
```

cc @kosmydel

**Comment by arosiclair** [comment]
> We had a discussion a few weeks ago about how the optimistic action should work [here](https://expensify.slack.com/archives/C036QM0SLJK/p1718037138317309?thread_ts=1717504451.168099&cid=C036QM0SLJK). TL;DR: this is mostly the same however the optimistic action should display a "starting..." text and the backend will update the text when it's completed:
> 
> ```diff
>   - Create an optimistic `EXPORTINTEGRATION` action in our `Report.exportToIntegration` and `Report.markAsManuallyExported` actions
> +    - The text should say `started exporting this report to {integration}...`
>   - Pass the `optimisticReportActionID` to both `Report_Export` and `MarkAsExported` APIs
>   - Use the ID to create the action in Auth
> +    - Auth will queue updates for the report action with the final text: `exported this report to {integration}. [View out-of-pocket expenses].`
>   - On failure
>     - create the `INTEGRATIONSMESSAGE` action with the error message like normal (using a different ID)
>     - delete the optimistic action on the frontend using `failureData`
> ```
> 
> cc @kosmydel

I ended up including updates for this in my PR for `EXPORTINTEGRATION` actions [here](https://github.com/Expensify/App/pull/44930)

**Comment by dylanexpensify** [comment]
Held

**Comment by dylanexpensify** [comment]
Still holding

**Comment by arosiclair** [comment]
Posted these PRs to support `optimisticReportActionID`:
- https://github.com/Expensify/Auth/pull/11663
- https://github.com/Expensify/Integration-Server/pull/7998
- https://github.com/Expensify/Web-Expensify/pull/42762

Should be able to get those deployed next week.

**Comment by dylanexpensify** [comment]
@arosiclair looks like 44022 is now in regression period - we good to take this off hold?

**Comment by arosiclair** [comment]
https://github.com/Expensify/Web-Expensify/pull/42762 still needs to get reviewed and merged and then we can finalize and merge https://github.com/Expensify/App/pull/44733

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @kosmydel 
- Contributor+: @hungvu193 $250

Please apply/request!

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
