### ISSUE TITLE
Room - When creating a room duplicate room displayed on search result

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** shussain+safari4@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a room
2. Click on search icon
3. Notice duplicate room displayed

## Expected Result:
Only one room should be displayed

## Actual Result:
When creating a room duplicate room displayed on search result

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8a6e82b9-8fc0-4251-b377-cfdcf8a2284c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Beamanator** [comment]
I'll close this in favor of https://github.com/Expensify/App/issues/43094 & we have an accepted proposal there
