### ISSUE TITLE
[HOLD for payment 2024-06-28] Push notification Onyx updates are not applied when there is no gap detected

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#43047]
**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** N/A
**Expensify/Expensify Issue URL:**
**Issue reported by:** @arosiclair 
**Slack conversation:** N/A

## Action Performed:

1. Log in
2. Accept push notification prompt
3. Kill the app
4. Send yourself a message
5. Verify a push notification appears
6. Enable airplane mode
7. Click the push notification

## Expected Result:
The app opens, you're navigated to the chat and the message displays

## Actual Result:
The app opens, you're navigated to the chat and the message does NOT display

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by arosiclair** [comment]
I described the root of this problem [here](https://github.com/Expensify/App/issues/40227#issuecomment-2147975047). I'll open a PR to fix it.

**Comment by alitoshmatov** [comment]
Removing my assignment since @c3024 reviewed the PR

**Comment by MitchExpensify** [comment]
*Payment summary*:

- $250 C+ @c3024 (Upwork offer here: https://www.upwork.com/nx/wm/offer/102848904)

**Comment by c3024** [comment]
@MitchExpensify accepted, thanks!

**Comment by c3024** [comment]
@arosiclair 

This was not paid out yet. Please keep this open. Thanks!

cc: @MitchExpensify

**Comment by c3024** [comment]
@MitchExpensify 

Bump for payment please!

**Comment by arosiclair** [comment]
Looks like they're OOO until next week

**Comment by arosiclair** [comment]
Looks like they're OOO until next week

**Comment by MitchExpensify** [comment]
Paid! Sorry for the delay
