### ISSUE TITLE
[HelpDot] Miscellaneous Bugs 

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#43044]
## BUGS
- [x] The `Back` button doesn't work on this article - [Automatically submit employee reports](https://help.expensify.com/articles/expensify-classic/reports/Automatically-submit-employee-reports)
- [ ] `i` is misplaced in text box here --> [Automatically submit employee reports](https://help.expensify.com/articles/expensify-classic/reports/Automatically-submit-employee-reports)
- [ ] `i` is misplaced in text box here --> [Xero](https://help.expensify.com/articles/new-expensify/connections/Set-up-Xero-connection)
- [ ] `i` is misplaced in text box here --> [Upgrade to the new Expensify Card from Visa](Upgrade to the new Expensify Card from Visa)
- [x] The `Back` button doesn't work on all resources under this hub --> https://help.expensify.com/new-expensify/hubs/expenses/

**Comment by rushatgabhane** [comment]
> The Back button doesn't work on this articl

This has been fixed. Can verify by doing a hard refresh on the article

**Comment by lschurr** [comment]
Any update on the other bugs listed here @rushatgabhane?

**Comment by rushatgabhane** [comment]
yes, i have a PR incoming

**Comment by lschurr** [comment]
Any update @rushatgabhane?

**Comment by rushatgabhane** [comment]
PR here - https://github.com/Expensify/App/pull/43811

**Comment by rushatgabhane** [comment]
PR merged.

Fixed for all current and future articles. 

<img width="677" alt="image" src="https://github.com/Expensify/App/assets/29673073/2e824b92-9ea3-45a4-9364-182e1a330f23">

**Comment by rushatgabhane** [comment]
@lschurr  please close the issue

**Comment by lschurr** [comment]
Great, thanks!
