### ISSUE TITLE
Profile - 2 options instead of 4 to pick in Troubleshoot > New search page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43051]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42184
## Action Performed:
1. Go to Search Page, Profile > Troubleshoot > New search page

## Expected Result:
There should be 4 options to pick

## Actual Result:
There are 2 options to pick instead of 4. (Drafts and Finished are missing)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0dcfb96c-037a-4a8b-8753-0a31fffc1039

![Bug6501851_1717522667059!screenshot_02](https://github.com/Expensify/App/assets/78819774/300e8412-e2e7-4a62-8461-93f514859557)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stitesExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neil-marcellini** [comment]
Thanks @Nodebrute, sounds like a non-issue so I'm closing it.
