### ISSUE TITLE
Android & iOS - Profile - Default avatar is small when viewed in full screen

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Tap on the chat header.
4. Tap on the user avatar.

## Expected Result:
User avatar will not appear small when viewed in full screen.

## Actual Result:
User avatar is small when viewed in full screen.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9e7fc7f5-a395-46cc-8457-9b1b388f5c7a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@bondydaa FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by neil-marcellini** [comment]
I'm 90% sure this is not a backend deploy blocker

**Comment by bernhardoj** [comment]
It's from https://github.com/Expensify/App/pull/42174 where we don't scale the image to fit the screen anymore (except bigger image than the screen).

**Comment by bondydaa** [comment]
cc @samilabud @arosiclair @eVoloshchak can you take a look and confirm if this was from your PR?

**Comment by samilabud** [comment]
> cc @samilabud @arosiclair @eVoloshchak can you take a look and confirm if this was from your PR?

Confirmed!

what should the expected behavior? most of the time images that are smaller than the container are pixelated, hence the origin of the change.

**Comment by arosiclair** [comment]
This should be expected behavior now. We're no longer scaling up small images automatically (you can still pinch to zoom though).

**Comment by bondydaa** [comment]
ah coolio @m-natarajan please make a note this is now expected behavior.
