### ISSUE TITLE
Distance tax - Tax amount is zero when selecting a distance rate on confirmation page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43111]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #42909
**Version Number:** 1.4.79-6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Track Tax distance is enabled on Old Dot.
- Workspace has a few distance rates and the distance rates are associated with tax rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Submit expense > Distance.
4. Enter waypoints > Next.
5. Click Rate.
6. Select a distance that has non-zero tax rate.

## Expected Result:
The tax amount will update accordingly.

## Actual Result:
The tax amount is zero on confirmation page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/45339b08-bea2-4cb6-92e7-01964b5f5058

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@mallenexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by MonilBhavsar** [comment]
Will look as it is coming from my PR

**Comment by MonilBhavsar** [comment]
Not a Web-E blocker

**Comment by trjExpensify** [comment]
@MonilBhavsar Tax reclaimable portion in the tester's video is $0.00 for all rates:

<img width="822" alt="image" src="https://github.com/Expensify/App/assets/16232057/0a425942-8437-49dc-accf-4464e83f6c51">

... so it doesn't matter whatever rate they select. The amount of tax reclaimable on it is `$0.00`, so therefore the `Tax amount` is `$0.00` on the expense:

<img width="811" alt="image" src="https://github.com/Expensify/App/assets/16232057/6d1c1110-d73a-4eb8-9d23-2219a70ad8e6">

**Comment by MonilBhavsar** [comment]
@m-natarajan this is not a bug and feature - 

Here - 

<img width="1726" alt="Screenshot 2024-06-05 at 7 40 32 PM" src="https://github.com/Expensify/App/assets/32012005/82636dd7-a3d5-406e-900e-9a1044f5da96">

The field `Tax reclaimable on` should not be `0.00`. If you update it to non zero, you should be able to see non zero tax amount. Could you please help to recheck. Thanks!

**Comment by MonilBhavsar** [comment]
Lol 😄

**Comment by trjExpensify** [comment]
Hahahahah

**Comment by carlosmiceli** [comment]
Just getting here, not sure I understood if this is a bug or not 😅

**Comment by trjExpensify** [comment]
Not a bug.

**Comment by trjExpensify** [comment]
Yup!
