### ISSUE TITLE
QBO - Location switch button hint text is not as expected

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43119]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when verifying #41638
**Version Number:** 1.4.79-6
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Create a new workspace
2. Go to the More Feature page and enable the accounting feature
3. Connect to QBO
4. Go to the Export page. Check that Vendor Bill is selected for Export out-of-pocket expenses as by default
5. Go to the Import page. Check the Location configuration. Check that the Switch is toggled off and locked.

## Expected Result:
There should be a hint text under the Switch button. Use the screenshot attached as a reference.

## Actual Result:
A hint text under the Switch button is different (screenshot attached)
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
Expected text hint

![Bug6502548_1717580957810!expected](https://github.com/Expensify/App/assets/38435837/350e79da-2027-427d-84ea-85e9c228e18d)

Actual text hint
![Bug6502548_1717580957811!actual](https://github.com/Expensify/App/assets/38435837/0cde2f77-58ac-4009-a448-1236f741404c)

https://github.com/Expensify/App/assets/38435837/e8cb1aaf-02e0-4178-b3e7-1387ffdf845d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @hayata-suenaga</details>

**Comment by m-natarajan** [comment]
@kadiealexander FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bondydaa** [comment]
I don't think this is a blocker, the copy was changed here https://github.com/Expensify/App/commit/bcecadabba073db7227dcf393f6a9c47cca0b62b

cc @hayata-suenaga can you confirm. We probably just need to update the QA test steps with the latest copy.

**Comment by trjExpensify** [comment]
Yep, this was an intentional change. I'd close this issue 👍
