### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250]  Group chat thread - Inconsistency when leaving thread via 3-dot menu and group details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43126]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to group chat.
3. Send a message and send a reply in thread.
4. Go to the thread.
5. Leave the thread via 3-dot menu > Leave.
6. Go to the same thread again.
7. Note that when leaving thread via 3-dot menu, there is no "Heads up" warning and thread does not load when reopening the thread after leaving.
8. Send a message and send a reply in thread.
9. Go to the thread.
10. Leave the thread via chat header > Leave.
11. Go to the same thread again.
12. Note that when leaving thread via group menu, there is "Heads up" warning and thread loads when reopening the thread after leaving.

## Expected Result:
There should be consistency when leaving thread and reopening thread after leaving via 3-dot menu (Step 7) and group details page (Step 12)

## Actual Result:
In Step 7. when leaving thread via 3-dot menu and reopening thread, there is no "Heads up" warning and thread does not load when reopening the thread after leaving
In Step 12, when leaving thread via group menu, there is "Heads up" warning and thread loads when reopening the thread after leaving

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/190ae0e0-b62c-4b9f-beb0-b3d23ac47717

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166b95168c5d28cbd</li>
        <li>Upwork Job ID: 1798387156425131546</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102676476</li>
<li>bernhardoj | Contributor | 102676480</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by akinwale** [comment]
We can move forward with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/43126#issuecomment-2150371173) here since it's the best approach to solving the issue.

🎀👀🎀 C+ reviewed.

**Comment by bernhardoj** [comment]
PR is ready

cc: @akinwale

**Comment by puneetlath** [comment]
@akinwale bump on the checklist so we can pay.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:'

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch the Expensify app.
2. Create a group chat or open an existing group chat.
3. Send a message.
4. Reply in the thread of the new message.
5. Click or tap on the thread header.
6. Verify that there is no leave button on the details page.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@puneetlath Done.

**Comment by puneetlath** [comment]
Regression issue here: 

All paid. Thanks y'all!
