### ISSUE TITLE
Workspace- Invitation email is not received by a user without NewDot account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43123]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**https://expensify.testrail.io/index.php?/cases/view/1971139
**Email or phone of affected tester (no customers):** applausetester+53pronin@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to NewDot
2. Create a workspace
3. Invite a new user (that doesn't have a NewDot account)

## Expected Result:
Email with an invitation to the Workspace should be received

## Actual Result:
Invitation to the workspace email is not received by a user without NewDot account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7a57f027-07b5-4afb-bcc8-1285c419640c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by sonialiap** [comment]
I cannot reproduce, the email came through when I invited xelere2474@kernuo.com (temp email) to a new workspace

<img width="708" alt="image" src="https://github.com/Expensify/App/assets/17131195/4167a639-6966-4094-a03a-bd9cce997981">

We had outages in the first week of June, maybe this was caught during that time which would explain why it didn't work for the QA team.
