### ISSUE TITLE
Past history of messages are removed when sending a message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43121]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-4
**Reproducible in staging?:** need reproduction
**Reproducible in production?:**  needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Beamanator 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717500120046479

## Action Performed:
1. Open app
2. Open a DM report with bunch of history messages
3. Send a message
## Expected Result:
Comment added to the bottom of the history, everything still shown
## Actual Result:
History removed, only the new comment was added
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2024-06-04 at 2 23 15 PM](https://github.com/Expensify/App/assets/38435837/1476269e-95c6-4843-aab1-a00d710e8ee9)

![Screenshot 2024-06-04 at 2 20 43 PM](https://github.com/Expensify/App/assets/38435837/09100fda-831f-4b65-9eed-2971784a499c)

https://github.com/Expensify/App/assets/38435837/0c9243f3-91b2-40a9-b474-9663f5124e9d

![image (12)](https://github.com/Expensify/App/assets/38435837/ef58d4c4-2f1c-4006-bc73-1381616b0d0e)

[logs-2024-06-04 23_36_48.395.txt](https://github.com/user-attachments/files/15587066/logs-2024-06-04.23_36_48.395.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Unable to repro on latest staging,  Version 1.4.79-8  Desktop, adding `Needs Reproduction`

**Comment by mallenexpensify** [comment]
Haven't seen it happen recently but want to leave it open another week to be sure.

**Comment by mallenexpensify** [comment]
Unable to repro, gonna close for now, PLEASE reopen if it happens again and we get get a vid, logs, whatever.
