### ISSUE TITLE
Hold-Full report gets approved automatically even if there is an expense on hold

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43138]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4593480
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions: Create A WS and add an Employee and a Approver
As the Employee, submit couple of expenses
1. Open the App
2. Log in as the Approver
3. Open the WS chat and put an expense on hold
4. Navigate back to the expense report that now has a held expense and a pending expense and click approve

## Expected Result:
A modal is displayed to approve the full report amount or just the pending expense

## Actual Result:
The report is automatically fully approved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/657a3e47-05ae-43cc-9164-0438de0c1355

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
Will be fixed here https://github.com/Expensify/App/pull/42896.
