### ISSUE TITLE
[Payment card / Subscription] Fix fundList Onyx data shape in `OpenSubscriptionPage.cpp`

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#43136]
# Problem

Coming from [this slack thread](https://expensify.slack.com/archives/C036QM0SLJK/p1717608307962959). The new `OpenSubscriptionPage` command populates the Onyx key `FUND_LIST` using the `Fund::getJSONFundList` method ([link](https://github.com/Expensify/Auth/blob/3fd2ae4a65ab5e5b43b31253de1190378584d3fb/auth/command/OpenSubscriptionPage.cpp#L54)). This is bad because the data that `getJSONFundList` returns corresponds in the frontend to the [AccountData type](https://github.com/Expensify/App/blob/263e2e462162228b46701ca2ecd0be81e7fbad22/src/types/onyx/Fund.ts#L10), not the [Fund type](https://github.com/Expensify/App/blob/263e2e462162228b46701ca2ecd0be81e7fbad22/src/types/onyx/Fund.ts#L28). We need the data to correspond to the Fund type.

# Solution
Create a new method in Auth that creates JSON that matches the correct FundList Onyx key as [defined in the frontend](https://github.com/Expensify/App/blob/263e2e462162228b46701ca2ecd0be81e7fbad22/src/types/onyx/Fund.ts#L39). Then update `OpenSubscriptionPage.cpp` to use this new method.

**Note:** You can see how we format the data returned by `getJSONFundList` into the correct shape in the [BankAccountAPI::openPaymentsPage method in Web](https://github.com/Expensify/Web-Expensify/blob/75d27d6facd7eed4b25d6da591e3c0b4f521508c/lib/BankAccountAPI.php#L2007). Be careful though, because that method uses the SET method, and only includes P2P cards, not billing cards, which means we could overwrite important data if we just simply port over exactly what that method is doing into Auth.

**Comment by NikkiWines** [comment]
Was focused on the TOS Update and Unvalidated Sign Ups today but will focus on this Friday & onwards.

**Comment by NikkiWines** [comment]
Started on this today, will continue on Monday!

**Comment by NikkiWines** [comment]
Actively working on this!

**Comment by NikkiWines** [comment]
Oops, this was fixed last already, closing!
