### ISSUE TITLE
[$250] Mention - User profile shows the old UI when clicking on user mention after sending it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43131]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Mention a user and send it
4. Click on the mention
5. Note that the user profile is the old UI
6. Dismiss the user profile
7. After a while, click on the mention again

## Expected Result:
In Step 4, user profile from mention should show the new UI

## Actual Result:
In Step 4, user profile from mention should show the old UI
It shows the new UI after a while when reopening the user profile (Step 7)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5f162a15-78bd-404f-984a-1d40498883b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d3f9640b9f8d604</li>
        <li>Upwork Job ID: 1798394573273215917</li>
        <li>Last Price Increase: 2024-06-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment]
@tgolen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by neil-marcellini** [comment]
I'm pretty sure this problem comes from the frontend.

**Comment by roryabraham** [comment]
> This is not a deploy blocker, it's the same behavior on production too

This new UI is on staging only, so it's not the same behavior on production.

I'm on the fence about whether or not this is a true blocker or not.

**Comment by kosmydel** [comment]
Hey I’m only for a moment, but https://github.com/Expensify/App/pull/42385 might solve this issue.

**Comment by kosmydel** [comment]
Hey, I didn't have time yesterday to investigate deeply.

I think that this behavior is expected. In the design doc, we planned two separate issues for updating the `ProfilePage` and then removing `DetailsPage`. The testing plan in this issue mentions the second case (DetailsPage) which changes hasn't been merged yet ([PR](https://github.com/Expensify/App/pull/42385)).

**Comment by Julesssss** [comment]
I'm removing the blocker label as this is an edge case with proposals in place, is potentially expected, and so we can speed up QA. More context [here](https://expensify.slack.com/archives/C07J32337/p1717671190816029?thread_ts=1717648387.742439&cid=C07J32337) (internal comment)

**Comment by Julesssss** [comment]
I have asked QA to retest 👍

**Comment by Julesssss** [comment]
Thank you!
