### ISSUE TITLE
[HybridApp] `Switch to Expensify Classic` values are not cleared out

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#43142]
### Problem
1. Clicking `Switch to Expensify Classic` twice does not have the values cleared
2. When the values are not cleared when opening the survey again

### Solution
Always clear the "Please tell us why you are leaving" data when switching from NewDot to OldApp

<details><summary>Issue Owner</summary>Current Issue Owner: @staszekscp</details>

**Comment by AndrewGable** [comment]
cc @staszekscp

**Comment by AndrewGable** [comment]
Posted a discussion for my proposed solution: https://expensify.slack.com/archives/C03TQ48KC/p1717622781938369

tl;dr we should move to `API.makeRequestWithSideEffects` instead of `write` to let the request finish before closing react native.

**Comment by staszekscp** [comment]
Hey! I'll post a PR for this today :)

**Comment by AndrewGable** [comment]
BTW we got agreement that we can use `makeRequestWithSideEffects` here if needed 👍

**Comment by staszekscp** [comment]
Thanks! The code is ready, I just need to record videos, and I’m going to finish that tomorrow 😅

**Comment by AndrewGable** [comment]
Merged the PR, making a TestFlight now

**Comment by AndrewGable** [comment]
@cead22 is having this issue again, I think I saw it happen again once too. Mind double checking it @staszekscp?

![IMG_7533](https://github.com/user-attachments/assets/990af96a-bd80-4870-8ca2-be230b89918b)

https://github.com/user-attachments/assets/132e91e5-a7a5-4e65-a4b5-14ce9f19581d

**Comment by staszekscp** [comment]
Sure! Do we have any logs that would indicate if the request failed or hanged?

**Comment by AndrewGable** [comment]
I believe that it's the same front end issue that happened in the past where the request isn't even started because the values are there before the user entered them.
