### ISSUE TITLE
Workspace - No errors when adding/deleting same member by admin and owner simultaneously

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4593415
**Email or phone of affected tester (no customers):** applausetester+53pronin@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Main Device
1. Make sure there are 3 users in the workspace, yourself, the admin (used in the secondary device) and a employee
2. Disable the internet connection in the device
Secondary device
3. Log in as a admin of the workspace in the secondary device
4. Navigate to members
5. Invite a user to the workspace
6. Edit the role of the member to "Admin"
Main device
7. While offline - Invite the SAME user to the workspace as in step 3 before
8. Click on the "Member" to edit it
9. Delete the "Member" that the admin in the secondary device promoted to admin
10. Enable the internet connection

## Expected Result:
Multiple errors and red dots are expected in Workspace settings and member list

## Actual Result:
Errors and red dots are missing after adding\upgrading\deleting the same member by admin and owner simultaneously

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ecebbd91-e3bb-497e-9fa3-db5c1a22ed90

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by miljakljajic** [comment]
This one feels like extreme polish given that the reproduction steps are very unlikely to be taken by a real user. Going to close to focus on more critical issues.
