### ISSUE TITLE
[$250]  Notification - Sound does not play when a notification is received

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43152]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.79-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4595535&group_by=cases:section_id&group_order=asc&group_id=295000
**Email or phone of affected tester (no customers):** applausetester+omq290@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open desktop app
2. Navigate to conversation with concierge
3. Send a message from another account to the user logged into the desktop app

## Expected Result:
A notification should be received, and the notification sound should play

## Actual Result:
The notification was received, but the notification sound did not play

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f68551bd-aa75-4a6b-aad2-a221b4bd728d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012cb3a62e103764d0</li>
        <li>Upwork Job ID: 1800481601169563814</li>
        <li>Last Price Increase: 2024-06-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment]
confirmed

**Comment by dylanexpensify** [comment]
low priority
