### ISSUE TITLE
Update to React Native 0.75

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#43177]
## Problem
We would like to stay up to date on the latest React Native version, but updating is hard! Commonly it requires updates of dependencies and additionally rigorous testing.

## Solution
Update to the latest React Native 0.75 when:
1. It has released a stable version
2. We have [finished the version update to 0.74](https://github.com/Expensify/App/issues/37374) and allowed it a few release cycles to determine there are no deploy blockers

cc @staszekscp - Can you have whoever is going to work on this comment here so we can assign them and start getting updates? Thanks!

**Comment by WoLewicki** [comment]
Commenting as I would like to work on it 🚀

**Comment by mountiny** [comment]
Still not on 0.74 on main

**Comment by mountiny** [comment]
Assigning me and Rory as we have been helping with the 0.74 upgrade

**Comment by mountiny** [comment]
payment still required

**Comment by roryabraham** [comment]
cc @shubham1206agra for C+ payment

**Comment by mountiny** [comment]
Ah yeah, I guess we can close this one now, feel free to reopen if you disagree
