### ISSUE TITLE
Track tax - Track tax rate is disabled when changing unit

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43173]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition: Enable 'Distance rate' and 'Taxes'
1. Workspace Settings page > Distance Rate > Settings
2. Enable Track tax
3. Change Unit and wait in the screens for few seconds

## Expected Result:
Track tax should remain enabled

## Actual Result:
Track tax is disabled

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/1e96c44a-447a-4d19-a977-c55b37848dfa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@trjExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment]
Checking.

**Comment by rlinoz** [comment]
Hmm we are returning null for `taxEnabled` when changing the unit, so not a blocker for the App.
<img width="417" alt="image" src="https://github.com/Expensify/App/assets/5201282/37fdf463-de64-4536-933a-5bb93a08772e">

**Comment by rlinoz** [comment]
Oh, actually it seems that we should send the `taxEnabled` attribute when updating the distance rate unit.

**Comment by MonilBhavsar** [comment]
cc @nkdengineer @eVoloshchak

**Comment by rlinoz** [comment]
Was just looking for the original PR, thanks!

Anyway, I don't think this needs to be a blocker, do you agree @MonilBhavsar ?

**Comment by rlinoz** [comment]
Removing the blocker from Web-E as this has to be solved in the FE.

**Comment by MonilBhavsar** [comment]
This is going to be demoed at Xerocon, and app looks buggy with this. So I think we should fix it cc @trjExpensify

**Comment by rlinoz** [comment]
Asked for CP here https://expensify.slack.com/archives/C07J32337/p1717688056480579

**Comment by MonilBhavsar** [comment]
Thanks @rlinoz 🙇 ⚡ !

**Comment by rlinoz** [comment]
Tested the CP and it worked, so closing.
