### ISSUE TITLE
[Track Tax] Vague system messages are displayed when changing Track tax, and Tax rate

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.80-3
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**Issue reported by:**

## Action Performed:
Precondition: Enable 'Distance rate' and 'Taxes'
1. Workspace Settings page > Distance Rate > Settings
2. Enable Track tax
3. Open a distance rate
4. Change Tax rate and Tax reclaim
5. Navigate to admins room of the workspace

## Expected Result:
System action messages should be clear for user, copy [here](https://github.com/Expensify/App/issues/43179#issuecomment-2197391083). 

## Actual Result:
System action messages include coding terms

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/8be89ecc-0bd6-437c-a9a0-2cd598cafad9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by etCoderDysto** [comment]
This looks like a BE issue. 

![image](https://github.com/Expensify/App/assets/171434916/f5334cf4-b9cf-423a-a135-affc2df7b37b)

**Comment by jasperhuangg** [comment]
Looks like @hayata-suenaga implemented this in Web-E [here](https://github.com/Expensify/Web-Expensify/blob/main/lib/Report/Action/PolicyChangeLog/UpdateCustomUnit.php#L1-L26), gonna assign him to investigate this.

**Comment by trjExpensify** [comment]
Oh yeah, interesting.. 

So looking at the [workspace change history](https://docs.google.com/document/d/1hldiqwchK2f40K-a_6QPRqqjJxJ5KQAEbW6YXCunUYo/edit) project from when these were introduced, tax rate changes on the workspace and distance tax tracking weren't included in the high level. So I think the first question here is whether we should start include these now? 

If so, what copy do we want to use. I agree what we see here looks janky, so we either need to improve them or not show them at all:

![image](https://github.com/Expensify/App/assets/16232057/5baea873-a73a-4a50-b9f9-4a210ebf7f1f)

CC: @sakluger

**Comment by jamesdeanexpensify** [comment]
Chatting in [thread](https://expensify.slack.com/archives/C036QM0SLJK/p1717691342987989?thread_ts=1717422185.401229&cid=C036QM0SLJK), @sakluger has some great suggestions!

**Comment by trjExpensify** [comment]
@sakluger can you bring the final copy into this issue when it's ready, so Hayata has it for reference? Thanks!

**Comment by hayata-suenaga** [comment]
Memo for myself:

wait for the copy to be decided and change [the custom unit code](https://github.com/Expensify/Web-Expensify/blob/main/lib/Report/Action/PolicyChangeLog/UpdateCustomUnit.php#L1-L26)

**Comment by MonilBhavsar** [comment]
We also need to update in Auth here https://github.com/Expensify/Auth/blob/ea5029e73fab43130bc3db91f748e662ddfe6436/auth/lib/ReportAction.cpp#L504

**Comment by hayata-suenaga** [comment]
waiting for the final confirmation of the UI text change

**Comment by hayata-suenaga** [comment]
changing the priority to weekly

**Comment by MonilBhavsar** [comment]
@hayata-suenaga as discussed here, we can make a PR and iron out minor details in PR review. So making it daily. What do you think?
https://expensify.slack.com/archives/C036QM0SLJK/p1718345428022229?thread_ts=1717422185.401229&cid=C036QM0SLJK

**Comment by hayata-suenaga** [comment]
agree! I'll open a PR tomorrow

**Comment by hayata-suenaga** [comment]
didn't have time last week to work on this as I got sick. Will resume working on this today

**Comment by hayata-suenaga** [comment]
Where the function to generate the report action message is callled: https://github.com/Expensify/Auth/blob/3c1e1b425e787f5d268b8e12891cf43e12c5bdb7/auth/lib/ReportAction.cpp#L699

**Comment by hayata-suenaga** [comment]
The function to generate new policy change logs seems to have been moved from Web-E to Auth.

The Auth command used might be just the Policy:save command -> https://github.com/Expensify/Web-Expensify/blob/4841f4524a462da978527912faf1397f14c54fa2/lib/PolicyStore.php#L94

**Comment by jamesdeanexpensify** [comment]
Heads up, trying to finalize copy [here](https://expensify.slack.com/archives/C036QM0SLJK/p1719521063409479?thread_ts=1717422185.401229&cid=C036QM0SLJK).

**Comment by jamesdeanexpensify** [comment]
final copy @hayata-suenaga (cc @sakluger):

**Admin added a tax rate to a distance rate:**
> added the tax rate "[rate name ([rate percentage])]" to the distance rate "[rate name]"

**Admin updated a tax rate on a distance rate:**
> changed the tax rate from "[old rate name ([old rate percentage])]" to "[new rate name ([new rate percentage])]" on the distance rate "[rate name]"

**Admin removed a tax rate from a distance rate:**
> removed the tax rate "[rate name ([rate percentage])]" from the distance rate "[rate name]"

**Admin added a tax reclaimable portion to a distance rate:**
> added the tax reclaimable portion "[reclaimable portion]" to the distance rate "[rate name]"

**Admin updated a tax reclaimable on a distance rate:**
> changed the tax reclaimable portion from "[old reclaimable portion]" to "[new reclaimable portion]" on the distance rate "[rate name]"

**Admin removed a tax reclaimable portion from a distance rate:**
> removed the tax reclaimable portion from the distance rate "[rate name]"

**Comment by hayata-suenaga** [comment]
thank you! I'll finish the PR with the updated copy this week 😄

**Comment by hayata-suenaga** [comment]
sorry! I have been down with sickness. catching up with issues this week, including this one!

**Comment by hayata-suenaga** [comment]
will work on this this week

**Comment by hayata-suenaga** [comment]
will work on this soon

**Comment by hayata-suenaga** [comment]
will work on it

**Comment by trjExpensify** [comment]
@MonilBhavsar perhaps you'd be willing to finish this off now?

**Comment by MonilBhavsar** [comment]
Yes, assigned

**Comment by trjExpensify** [comment]
Thanks!

**Comment by trjExpensify** [comment]
Heads up that I've moved this into the Sept release as it's pretty janky that some of our workspace change logs read like code.

**Comment by MonilBhavsar** [comment]
Sounds good 👍 
I have started working on it. Should have PRs up by today

**Comment by trjExpensify** [comment]
Love it!

**Comment by MonilBhavsar** [comment]
Web-E PR is in review https://github.com/Expensify/App/issues/43179#issuecomment-2197391083
Working on Auth PR now. 

We were not storing tax percentages in the changeLog array. As they are now required in the copy message, we are storing them

**Comment by MonilBhavsar** [comment]
All PR's were deployed and issue is fixed. Closing
