### ISSUE TITLE
mWeb - Chat - 3 backtick code block is not applied correctly

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43176]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter ```gaj id```
4. Send the message

## Expected Result:
3 backtick code block must be applied correctly

## Actual Result:
3 backtick code block is not applied correctly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e7adb0a8-3c02-43f2-99d7-5038fd1641ac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by puneetlath** [comment]
Based on [this test](https://github.com/software-mansion-labs/expensify-common/blob/6c07092648afd712251e25d05d54fcb303fda618/__tests__/ExpensiMark-HTML-test.js#L457-L460), it seems like this is actually the expected behavior. 

So I'm going to remove this as a blocker and close it out.
