### ISSUE TITLE
[HOLD for payment 2024-06-28] [Payment card / Subscription] [$250] Subscription - Keyboard opens when neither of the fields are in focus after selecting currency

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43181]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.80-3
**Reproducible in staging?:** y 
**Reproducible in production?:** new feature
**Issue found when executing PR:** https://github.com/Expensify/App/pull/42771
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Paste staging.new.expensify.com/settings/subscription/add-payment-card in any chat.
3. Tap on the link.
4. Enter all the details.
5. Tap Currency.
6. Select a currency.

## Expected Result:
Keyboard will not open.

## Actual Result:
Keyboard opens when neither of the fields are in focus after selecting currency.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/df6599d6-ca29-431a-afdd-92db59f14576

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017794b8ac770cfc92</li>
        <li>Upwork Job ID: 1798795318782491823</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 102630012</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by kbecciv** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by neil-marcellini** [comment]
Not a backend bug

**Comment by mananjadhav** [comment]
I can see it's open for External contributors.

Looks like @ShridharGoel's proposal would work.

🎀 👀 🎀 C+ reviewed.

**Comment by hayata-suenaga** [comment]
@stephanieelliott, please handle [the payment for this issue](https://github.com/Expensify/App/issues/43181#issuecomment-2195708671), please 🙇 

@mananjadhav is the C+ who reviewed the PR
@ShridharGoel is the contributor who authored [the PR](https://github.com/Expensify/App/pull/43317)

**Comment by mananjadhav** [comment]
@stephanieelliott Can you please add the payout summary?

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @ShridharGoel $250 via Upwork -  PAID 
 - Contributor+: @mananjadhav $250 please request via ND 
 
 Upwork job is here: https://www.upwork.com/jobs/~017794b8ac770cfc92

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by mananjadhav** [comment]
@stephanieelliott We're good to close this issue.
