### ISSUE TITLE
[HOLD for payment 2024-07-10] [HybridApp] Improve transitions between Classic <> New Expensify

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#43186]
## Problem
The transition between Classic and New Expensify is not the smoothest. Let's apply some design magic and improve the transition to make it look seamless ✨ 

## Solution
Keep riffing on the transition animations between the two pages and smooth the animations out so they look better.

https://github.com/Expensify/App/assets/2838819/1a65e8ae-32f8-4006-bbd6-2cd465d4e3e8

cc @staszekscp

**Comment by AndrewGable** [comment]
Going to get some help with this one soon

**Comment by AndrewGable** [comment]
@mateuuszzzzz - Can you comment here so I can assign you? Thanks!

**Comment by mateuuszzzzz** [comment]
.

**Comment by AndrewGable** [comment]
This is done!

**Comment by AndrewGable** [comment]
@mateuuszzzzz is working on this
