### ISSUE TITLE
mWeb - Workspace - Error shown while inviting workspace member

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43188]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging
2. Tap profile -- workspaces - workspace
3. Tap invite member
4. Enter a new expensifail account
5. Semd invite

## Expected Result:
Error must not be shown while inviting workspace member

## Actual Result:
Error shown while inviting workspace member

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3827ee2a-8554-47a9-ac1c-e83440f2aadc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment]
@Julesssss Would you happen to know about this error by any chance?

I found [the logs for the failed AddMembersToWorkspace request](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2288f960f3ff8d8ef1-BOM%22)+AND+timestamp:[2024-06-06T14:19:15.359Z+TO+2024-06-06T16:19:15.359Z]&index=logs_expensify-028804).

Auth is returning the error `404 Account not found` when a restrictedAuthToken is being fetched as part of `shouldClassicRedirectBeAppliedOnPolicyInvite()`.

Doesn't really make much sense, but I don't really see any recent changes in this area either.

![image](https://github.com/Expensify/App/assets/1228807/6396a8f8-2449-4651-9b0f-735422377bae)

**Comment by neil-marcellini** [comment]
It looks like this is specific to the applause domain, so I'm going to mark it as not a blocker

It works with an existing account

https://github.com/Expensify/App/assets/26260477/4beb081c-2f3a-4ef5-b016-f5cb2dae6346


I think it might be important to invite a brand new account, but that still works

https://github.com/Expensify/App/assets/26260477/8d5cbd29-cf2e-4f03-a9e1-cce424feee00


It fails with the applause domain

https://github.com/Expensify/App/assets/26260477/f3b65955-e569-4c35-907a-91bb5f2fca43

**Comment by tgolen** [comment]
I've looked through the code paths for `GetRestrictedAuthToken` and I can't find any recent changes.

@iwiznia @flodnv Any ideas on why this seems to only happen for users on the `@applause.expensifail.com` domain?

There isn't a whole lot more info in the logs.
![image](https://github.com/Expensify/App/assets/1228807/b54fb143-c237-48e0-929a-2e70838540ae)

These are some things I'd like to know, but don't have the answer to (@Julesssss I hope you would know these)
- Should PHP be using a try/catch [here](https://github.com/Expensify/Web-Expensify/blob/a1a6f284af911487d5241a95f24119ceb2ebe9d1/lib/User/Utils.php#L1636) when calling Auth to account for an account that doesn't exist yet?
- Why does this error only happen to the applause domain and work for other "brand new" accounts?

**Comment by Julesssss** [comment]
@tgolen 

> Should PHP be using a try/catch [here](https://github.com/Expensify/Web-Expensify/blob/a1a6f284af911487d5241a95f24119ceb2ebe9d1/lib/User/Utils.php#L1636) when calling Auth to account for an account that doesn't exist yet?

Perhaps as a safety measure, but I don't think there are valid reasons for this failing (under normal circumstances), and this might hide deeper errors.

> Why does this error only happen to the applause domain and work for other "brand new" accounts?

I assume you mean other non-expensify domain invitations? If so perhaps there is a race condition or some delay with invitations from large domains?

**Comment by flodnv** [comment]
>Perhaps as a safety measure, but I don't think there are valid reasons for this failing (under normal circumstances), and this might hide deeper errors.

I agree

---

I started debugging this, but actually I would suggest to move [this code](https://github.com/Expensify/Web-Expensify/blob/15e0ffcfab7666930e7b7d8305a27c269232ee72/lib/PolicyAPI.php#L6160-L6170) into Auth to make this 1:1 (especially important given this is doing a write and thus renders the command non-atomic)

**Comment by tgolen** [comment]
@lanitochka17 Can you please help verify what the scope of this error is? Is it indeed only accounts on the Applause test domain that are affected? How does this impact Applause's testing? What priority does this need to be?

**Comment by lanitochka17** [comment]
Issue reproducible only for expensifail account, but isn't repro for gmail account.
The priority of this issue is medium as users usually add existing accounts.

https://github.com/Expensify/App/assets/78819774/a92eb5d0-4496-4f4b-a374-a8769de7060a


https://github.com/Expensify/App/assets/78819774/fbc8f3f0-6734-48bf-bc05-e6d7def70f95

**Comment by hayata-suenaga** [comment]
The Web-E PR was merged!

**Comment by tgolen** [comment]
Turns out my try/catch [did not fix the error](https://github.com/Expensify/Web-Expensify/pull/42376#issuecomment-2176376282)... which is perplexing. Maybe I didn't put it in the correct place. I'm not really sure what else to try, but I'll think of something and put this issue back on my weekly radar.

**Comment by tgolen** [comment]
I have no updates or any leads or suggestion on a possible fix... I'm all out of ideas. I will unassign this and add the hot-pick label to see if anyone can move this forward.
