### ISSUE TITLE
Pay someone - Replies sent to paid system message appear again in transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43183]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42894
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Pay someone
3. Enter amount, select a user and pay them
4. Go to the transaction thread
5. Right click on the system message > Reply in thread
6. Send a reply
7. Click on the header subtitle to return to transaction thread

## Expected Result:
In Step 5, the paid system message will appear in the thread
In Step 7, reply sent in Step 6 will not appear in the transaction thread

## Actual Result:
In Step 5, the paid system message does not appear in the thread. The entire transaction details appear instead
In Step 7, reply sent to paid system message in Step 6 appears in the transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1bf781ff-80db-412e-b3ee-83293ccefb55

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@francoisl  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neil-marcellini** [comment]
This is not a blocker for the backend deploy. The issue was found when testing this PR, which is the cause [Display send money action as paid system message in combine report](https://github.com/Expensify/App/pull/42894#top). Looking at the [proposal](https://github.com/Expensify/App/issues/41645#issuecomment-2124381544) and related issue, only frontend changes where made. I'll put up a revert PR.

**Comment by roryabraham** [comment]
no payments due here

**Comment by kavimuru** [comment]
Issue is fixed.

https://github.com/Expensify/App/assets/43996225/bee2bdcf-a1c5-48ad-bab9-9199c8160f09
