### ISSUE TITLE
Track Expense-App crashes when clicking on "share it with my accountant"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43197]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1 
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Sign in with a new Gmail account. (Occurs only with Gmail account)
2. Open self DM and click on track expense
3. Submit a manual expense
4. Click on "Share it with my accountant"

## Expected Result:
"Share" modal opens.

## Actual Result:
App crashes

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/37bb5822-21a7-424c-a0a6-41cec4cb214a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@arosiclair FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neil-marcellini** [comment]
Hmm, I'm not able to reproduce on main, so are we sure that PR caused it?

**Comment by neil-marcellini** [comment]
Anyways, I really doubt this is a backend problem

**Comment by roryabraham** [comment]
Easy to reproduce on staging. Error is `TypeError: Cannot read properties of undefined (reading 'customUnitRateID')`

**Comment by roryabraham** [comment]
Coming from [here]()https://github.com/Expensify/App/blob/fad70bfe13765685b1a20c15603fcce090631349/src/libs/DistanceRequestUtils.ts#L95)

**Comment by roryabraham** [comment]
co-assigning, going to try and fix this one

**Comment by roryabraham** [comment]
easy to reproduce on main as well

**Comment by roryabraham** [comment]
more specifically coming from [here](https://github.com/Expensify/App/blob/ca986a7be86ee7602f1711b164d5e7f2d9959fa3/src/components/MoneyRequestConfirmationList.tsx#L2600

**Comment by roryabraham** [comment]
This is another bug that would've been avoided by https://github.com/Expensify/App/issues/43055

**Comment by luacmartins** [comment]
Fixed in staging. Closing.

https://github.com/Expensify/App/assets/22219519/50f9a7be-d5ba-4ce7-bb8c-fb6ca8054a1e
