### ISSUE TITLE
mWeb - Chat - Empty lines get doubled when pasting message via keyboard clipboard suggestion

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43191]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .4.80-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4602092
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send a message with empty lines, and copy it
4. Paste the message via keyboard clipboard suggestion
5. Send the message

## Expected Result:
The amount of line breaks should remain the same after the copy and paste process

## Actual Result:
Line breaks/empty lines get doubled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/767c4298-1706-4954-b05e-c5ac965ab881

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by stephanieelliott** [comment]
This is a pretty minor display issue, gonna close as it's low priority.
