### ISSUE TITLE
[Live Markdown] Styling for empty nested block quotes

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#43199]
Corresponds with https://github.com/Expensify/App/issues/41107

Inserting a nested empty block quote breaks the styling

> The paddings for the nested blockquotes are causing height differences between the containers, and the min-height of the container isn't set, so when we try to insert empty blockquotes, we end up with the situation presented below.

![image](https://github.com/Expensify/App/assets/30609178/948bcb7f-0865-4ce9-8c6a-9f48f0df78a5)

cc @BrtqKr

**Comment by thienlnam** [comment]
@BrtqKr Is this something you'd like to handle or shall we make it external?

**Comment by BrtqKr** [comment]
@thienlnam I can take over this, thanks for letting me know!

**Comment by BrtqKr** [comment]
Update for today:
I've got most of the changes, but the empty lines are a bit tricky to handle, so I'm trying to fix it at the moment.

**Comment by BrtqKr** [comment]
Update for today: 
Draft is ready for the review from someone from SWM and we'll be passing it further soon. Also, there are some styling changes in the core app, but since getting rid of the margins completely is probably out of question I'm looking for a workaround

**Comment by anmurali** [comment]
Asked for an update on Slack - https://expensify.slack.com/archives/C04878MDF34/p1721174878190149

**Comment by BrtqKr** [comment]
@thienlnam 
Moving the discussion from slack, I've commented on the other ticket related to that as well. 
 
To sum up - there have been a lot of issues related to the behavior of blockquotes, describing different, sometimes conflicting results as desired. We've been discussing it internally and we think we should take a different approach in this case. Can we please:

Pass [this document ](https://docs.google.com/document/d/18YEgGIZSLuGrOsfVJkQ7Q1i1wUi23KGQGy0ZWlQYlKg/edit?usp=sharing)further inside the Expensify team.
Make the decisions regarding cases described in the document.
Create a single ticket to adjust those behaviors on both sides - the input and the parser. And redirect all blockquotes-related reports to that place
We think that we're lacking a single source of truth with an appropriate description for the parser and the general approach to fixing those things seems a bit chaotic and blindly adjusting regexes without a broad context might not be the best workflow.

**Comment by thienlnam** [comment]
Thanks, I agree it can get confusing with the different issues with conflicting expected results. 

One thing we'll also want to have done is just make sure the regression tests for Live Markdown are cleaned up so they're always testing and know what correct behaviors are.

I'll take a look through this week and create a single issue to address all of those things

**Comment by anmurali** [comment]
@thienlnam what are we gonna do here?

**Comment by thienlnam** [comment]
Forgot to follow back here, but looked through the document and a lot of them are edge cases with blockquotes and unless there's an issue we're trying to solve specifically it doesn't seem like we need to keep going with this
