### ISSUE TITLE
[HOLD for payment 2024-06-24] [$125] [Search v1] Search page: Show dates for prior year transactions

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#43209]
## Problem
We're on the cusp of launching a v1 `Search` page, which means it's possible to see transactions from prior years. What I mean by this is that we are now in 2024, and I have a transaction I can find on the `Search` from back in 2017. The issue is that I have no idea looking at the transaction that it's from that far back.

Here's the New Expensify transaction. 
![CleanShot 2024-06-06 at 12 16 38@2x](https://github.com/Expensify/App/assets/1127863/34c7ae3a-e98c-4f8a-beee-d6669d990223)

Here's the Expensify Classic transaction
![CleanShot 2024-06-06 at 12 17 06@2x](https://github.com/Expensify/App/assets/1127863/e19e46b0-88ea-4bdb-b798-a02f2624fe0a)

## Solution
When looking at a prior year transaction, show the year, in addition to the month and date. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017440ce6c14aca464</li>
        <li>Upwork Job ID: 1798793329608614800</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102671230</li>
<li>ShridharGoel | Contributor | 102671233</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by JmillsExpensify** [comment]
P.S. We're going to need web and mobile mocks from the design team. I reached out to them.

**Comment by luacmartins** [comment]
@Expensify/design would love your ideas on how to display this

**Comment by shawnborton** [comment]
I'm thinking it might be best to just make the column wider:
![image](https://github.com/Expensify/App/assets/2319350/596e8a3b-84ba-4da5-8fcb-5438630e4e41)

Because it doesn't look nearly as good if we stack like OldDot:
![image](https://github.com/Expensify/App/assets/2319350/a1e35059-1152-4e22-af5c-aced46503e5d)

Mobile seems pretty straight forward:
![CleanShot 2024-06-06 at 20 26 37@2x](https://github.com/Expensify/App/assets/2319350/f1a9b38a-ba09-49fc-b870-1369c22ea3c1)

**Comment by JmillsExpensify** [comment]
Looks dope! I'll go ahead and take this so we can open up to community. cc @luacmartins

**Comment by dannymcclain** [comment]
I agree we should just keep it simple and make the column wider.

**Comment by shawnborton** [comment]
@ShridharGoel why use 96 for the column width? In the mockup we're using 80.

**Comment by shawnborton** [comment]
Perfect, 80 is all you need so you should be good there.

**Comment by trjExpensify** [comment]
@mountiny can you keep this moving? We might be able to get it today. :)

**Comment by mountiny** [comment]
Cool taking over, I think Carlos will have enough of other tasks

**Comment by greg-schroeder** [comment]
PR is up/in review

**Comment by luacmartins** [comment]
@ShridharGoel I'm not sure that I understand how the scope increased. We still just added the year to the date column if there are transactions from previous years which was the OP, no?

**Comment by luacmartins** [comment]
I think the OP was to add the year, which is where the logic change came from and definitely in scope. I think we would just keep the existing bounty as is.

**Comment by luacmartins** [comment]
This was a simple change, so I think the current bounty of $125 is applicable here.

**Comment by luacmartins** [comment]
PR was deployed to prod on the 17th, so the payment due date is actually the 24th. cc @greg-schroeder

**Comment by greg-schroeder** [comment]
Oh. Okay. I'll process this now then

**Comment by greg-schroeder** [comment]
@ShridharGoel please accept the offer in Upwork so I can pay you, thanks!

**Comment by greg-schroeder** [comment]
bump @ShridharGoel

**Comment by greg-schroeder** [comment]
Bump @ShridharGoel - moving this to `Monthly` given no response.

**Comment by luacmartins** [comment]
@greg-schroeder seems like the offer was accepted. Can we close this now?

**Comment by greg-schroeder** [comment]
Yes it does appear it was finally accepted! I'll close it after I confirm payment!

**Comment by greg-schroeder** [comment]
Paid
