### ISSUE TITLE
Hold expense - Inconsistency in showing Submit button in main chat vs report for held expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43203]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #42374
**Version Number:** 1.4.80-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Submission frequency (Delayed submissions) is set to Manually on the workspace.
- Workspace chat has no unsettled expense.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual expense.
4. Go to the transaction thread.
5. Click 3-dot menu > Hold.
6. Enter reason and save it.
7. Return to the main chat.

## Expected Result:
There should be consistency in displaying (or not) the Submit button in the main chat preview and transaction thread.

## Actual Result:
The main chat preview is showing Submit button, but the Submit button is missing in the transaction thread (combined report)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9a6e9c52-615d-4611-8ca3-23cd1d8ed42b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by blimpich** [comment]
Should be hourly I'm pretty sure.

**Comment by srikarparsi** [comment]
This might also be related to [this](https://github.com/Expensify/App/pull/42374)

**Comment by blimpich** [comment]
Yeah this seems like something that was overlooked in https://github.com/Expensify/App/pull/42374.

I'm on the fence if we should revert or just make this follow up work.

**Comment by blimpich** [comment]
@tienifr @dukenv0307 can you take a look into this as part of your work on https://github.com/Expensify/App/pull/42374? I can assign you if that helps keep track of it.

cc: @NikkiWines

**Comment by kavimuru** [comment]
Issue is fixed. 

https://github.com/Expensify/App/assets/43996225/80b41a68-c0e0-4ecf-876e-b33237f4930a

**Comment by kavimuru** [comment]
There is no payment due, [reference](https://expensify.slack.com/archives/C01GTK53T8Q/p1717784667742159?thread_ts=1717780790.948359&cid=C01GTK53T8Q)
