### ISSUE TITLE
Hmm.. it is not here message when an approver is updated in the workspace and opening the submitter expense report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43219]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcochavezf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717617417289669

## Action Performed:

1. Admin: create a workspace, add a member
2. Admin: Enable workflows, enabled Add approvals and add admin as approver
3. Member: Submit a few expenses in the workspace chat
4. Admin: Add a new member and make them approver
5. Approver: Open the workspace chat and open an expense report submitted by other member in step 3

## Expected Result:
The expense should be displayed
## Actual Result:
“Hmm… it’s not here” is displayed
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/f26f817d-bca5-4a31-b2be-940bb97c3ef2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment]
Working on it

**Comment by isabelastisser** [comment]
Hey @marcochavezf, any updates?

**Comment by marcochavezf** [comment]
I pushed more changes to the PR, I'm still working on it

**Comment by isabelastisser** [comment]
Thanks for the update, Marco! :)

**Comment by isabelastisser** [comment]
Not overdue, Melvin.

**Comment by isabelastisser** [comment]
@marcochavezf, can you please confirm that these ^^ are the correct labels?

**Comment by marcochavezf** [comment]
Yeah, I think those are the accurate labels, thanks!

**Comment by marcochavezf** [comment]
Continuing with it today, and it's also needed for [Additional Approvals](https://expensify.slack.com/archives/C06ML6X0W9L/p1718810768968269?thread_ts=1718807524.584819&cid=C06ML6X0W9L)

**Comment by marcochavezf** [comment]
[PR](https://github.com/Expensify/Auth/pull/11196/files#diff-71e5dfb89f61488924fbd1778e402bfe798b419a31c368f1ca7dd3d2aa0a5387R1958-R1959) in review

**Comment by marcochavezf** [comment]
Still working on the PR

**Comment by marcochavezf** [comment]
PR updated, latest update [here](https://github.com/Expensify/Auth/pull/11196#issuecomment-2210080844).

**Comment by marcochavezf** [comment]
One PR was merged, the other one will be addressed in this [issue](https://github.com/Expensify/Expensify/issues/413812)

**Comment by marcochavezf** [comment]
The other PR is in review (more details [here](https://github.com/Expensify/Expensify/issues/413812#issuecomment-2274667546)). I will move it to weekly meanwhile

**Comment by trjExpensify** [comment]
Is this attached to the `[Simple AA]` approvals project in #wave-control? Judging by this PR title, I think it is: [Share expenses non-admin approvers on AA Expensify/Auth#11975](https://github.com/Expensify/Auth/pull/11975)

**Comment by marcochavezf** [comment]
This one was already fixed with Aldo's PR, which was deployed a few weeks ago. I'm going to close it out
