### ISSUE TITLE
Expense - Inconsistency in showing last digits as 0 when spliting, submitting and paying

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4600954
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Click + > Split expense > Manual
4. Enter amount without digits after decimal point
5. Tap Next
6. Return to previous page via back button
7. Note that xx.00 is not shown in the amount input
8. Repeat Step 3 to 7 with Submit expense and Pay <user>

## Expected Result:
There should be consistency in displaying last digits as 0 when returning from confirmation page to amount input page when splitting, submitting and paying someone

## Actual Result:
When spliting and submitting expense, amount is not auto-filled with .00 when returning to amount input page
When paying someone, amount is auto-filled with .00 when returning to amount input page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e8d962b8-2329-4ced-ada4-08564d1c7bdc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dangrous** [comment]
This is likely coming from https://github.com/Expensify/App/pull/40062 - we decided that we should keep user input as is, even if it shows differently in the summary page, so IMO no bug - just new expected behavior.

But if you disagree let us know and we can discuss!

**Comment by luacmartins** [comment]
I couldn't reproduce the issue and I also don't think this is a problem.
