### ISSUE TITLE
iOS - PDF - Password entered is completely deleted when trying to delete only 1 character

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4604357
**Email or phone of affected tester (no customers):** applausetester+vd_ios060624@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat
2. Send a password protected PDF
3. Tap on the password protected PDF preview
4. Tap on "enter the password"
5. Enter some characters
6. Tap on the eye icon to reveal the password
7. Tap on the eye icon again to hide the password
8. Tap on the delete key
9. Verify the whole password is deleted

## Expected Result:
Only the last character should be deleted

## Actual Result:
The whole password is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f3d060e7-4350-4727-9eb0-a88c5095d06a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
Same issue as https://github.com/Expensify/App/issues/21730 and was [closed because it's the native behavior of iOS](https://github.com/Expensify/App/issues/21730#issuecomment-1671390842).

**Comment by Christinadobrzyn** [comment]
Thanks @bernhardoj! Closing based on https://github.com/Expensify/App/issues/43210#issuecomment-2153890040
