### ISSUE TITLE
Card padding changes when RHP is opened

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43235]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717646276509929

## Action Performed:
1. Go to "Profile" (Avatar in the bottom navigation)
2. Click "Preferences"
3. Click "Language"

## Expected Result:
RHP (right hand panel) should slide out
## Actual Result:
RHP slides out, but the card under the scrim (overlay) changes its padding. 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/95152228-60e4-4937-b0cb-df128b92b926

![CleanShot 2024-06-06 at 14 02 34](https://github.com/Expensify/App/assets/38435837/6d931a4b-96f5-42b3-81b2-cd43f10cf0c8)

https://github.com/Expensify/App/assets/38435837/a2cf1ed1-c4dc-40a7-9d86-41447f579765

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dubielzyk-expensify** [comment]
Looks like it's already reported here https://github.com/Expensify/App/issues/43031

**Comment by dubielzyk-expensify** [comment]
Seems like it's been fixed already
