### ISSUE TITLE
[HOLD for payment 2024-07-17] Expense - Header subtitle from report with RBR in LHN leads to the same transaction view 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43238]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has no unsettled expense.
3. Create an expense that will induce RBR (make category in expense a requirement and submit an expense without category).
4. Click on the report with RBR on LHN.
5. Click on the header subtitle.

## Expected Result:
App will return to the workspace main chat.

## Actual Result:
App returns to the same transaction view.
This issue only happens when there is one expense in the workspace chat.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/44ab3c9e-914f-4530-b79c-b69dfa4a3740

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by kavimuru** [comment]
@marcaaron FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by marcaaron** [comment]
I am not really convinced this needs to be a blocker.

**Comment by marcaaron** [comment]
@roryabraham lmk if you agree. I'm heading OOO so a volunteer will need to give this another look tomorrow.

**Comment by bernhardoj** [comment]
The transaction thread shouldn't be shown in the LHN because we hide it if it's a one transaction thread.
https://github.com/Expensify/App/blob/1426c4e4c3c8182d1f69cffb4ff6b2bb9e55f449/src/libs/ReportUtils.ts#L5320-L5323

But https://github.com/Expensify/App/pull/41507 changes the behavior that every report that has error is shown.

**Comment by jjcoffee** [comment]
Hmm #41507 hasn't hit staging yet though.

**Comment by bernhardoj** [comment]
Oh, you're right. The reportID comparison here fails because `reportID` is a string but `transactionThreadReportID` is a number. `transactionThreadReportID` is from the money request action `childReportID` which supposed to be a string, so it's a BE problem.
https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/libs/ReportUtils.ts#L1444-L1447
https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/types/onyx/ReportAction.ts#L161

But even after we fix it, one transaction thread will still show because of this code.
https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/libs/SidebarUtils.ts#L97-L103

**Comment by trjExpensify** [comment]
@jjcoffee do you agree with that assessment that there's a BE error here?

**Comment by luacmartins** [comment]
@jjcoffee I do see https://github.com/Expensify/App/pull/41507 in the [staging checklist](https://github.com/Expensify/App/issues/43168) and I also see that PR's code on the staging branch.

**Comment by luacmartins** [comment]
TBH I think this is expected? When we have a single transaction report, the view for the thread and the expense report are the same? @trjExpensify can you confirm?

**Comment by jjcoffee** [comment]
@luacmartins Oh my bad, I was going by the `QA ongoing` [comment](https://github.com/Expensify/App/pull/41507#issuecomment-2150274363) on the PR! There must be something wrong with the automation.

But yeah I agree that this is expected, the header link being tapped is to the `Expense Report`, so the expected result of being navigated to the workspace is incorrect.

![image](https://github.com/Expensify/App/assets/27287420/0dee31a6-091a-404f-9972-0022e3685307)

**Comment by luacmartins** [comment]
@trjExpensify and I discussed this internally, and we think the behavior introduced in https://github.com/Expensify/App/pull/41507 might be slightly incorrect. For the one expense report, we should be pinning the expense report, not the thread for that expense.

**Comment by luacmartins** [comment]
I'm gonna demote this to NAB since nothing is broken, but we should fix the expected behavior here. cc @tienifr @jjcoffee @AndrewGable @cead22

**Comment by trjExpensify** [comment]
Yeah, it seems like in this case we've "leaked" a view of the transaction thread and not the one expense report view. Agreed it's not a blocker though, just we need to clean up the UX.

**Comment by jjcoffee** [comment]
Hmm still confused about this one, are we saying that tapping `Expense Report` should lead us straight to the workspace? Or should `Expense Report` not be there in the first place?

**Comment by luacmartins** [comment]
@jjcoffee we should be showing the expense report in this case, so the header should show the workspace chat and tapping it would lead the user to the workspace chat, instead of showing/navigating to the expense report like we're doing. So we have:

Workspace chat > Expense report > Transaction thread (we're showing this now)
Workspace chat > Expense report (we should show this instead) > Transaction thread (not accessible for 1 expense report)

**Comment by jjcoffee** [comment]
Thanks! cc @tienifr on [the above](https://github.com/Expensify/App/issues/43238#issuecomment-2158612919).

**Comment by jjcoffee** [comment]
@luacmartins Do you think we should fix the BE issue mentioned [here](https://github.com/Expensify/App/issues/43238#issuecomment-2154472783) first? @tienifr is currently looking at converting to string in the comparison here:

https://github.com/Expensify/App/blob/4fcc5a9fbef90114ab4f38a1be698c471e3e75d1/src/libs/ReportUtils.ts#L1444-L1447

i.e.: `reportID?.toString() === transactionThreadReportID?.toString();`

**Comment by luacmartins** [comment]
Yea, we should also fix this in the backend. Do we know which API command is returning it as an int instead of string?

**Comment by luacmartins** [comment]
Yes, the RBR should be shown for the expense report in that case.

**Comment by luacmartins** [comment]
Also, bump on [this comment](https://github.com/Expensify/App/issues/43238#issuecomment-2163235957)

**Comment by luacmartins** [comment]
Thanks! I put up a PR to fix that and return `childReportID` as a string.

**Comment by jjcoffee** [comment]
Note that payment is not required here, it will be handled on https://github.com/Expensify/App/issues/36778.

**Comment by luacmartins** [comment]
Thanks for pointing that out. I think we're good to close then!
