### ISSUE TITLE
[$250] Distance - Downloaded distance receipt only shows the map

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43231]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ikevin127 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1717629970008689

## Action Performed:
1. Go to https://staging.new.expensify.com./
2. Go to workspace chat.
3. Submit a distance expense
4. Go to transaction thread
5. Click on the receipt
6. Click on the 3-dot menu (top right) and Download receipt.

## Expected Result:
The downloaded distance receipt should look exactly like the receipt seen in the attachment modal, containing the map and expense details wrapped by the `Expensify - Guaranteed eReceipt` frame.
## Actual Result:
The downloaded distance receipt only shows the map.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-06-05 at 16 15 13](https://github.com/Expensify/App/assets/38435837/c38087dd-bc10-4a67-9e88-ff9966fcfd6f)

https://github.com/Expensify/App/assets/38435837/dacc9a5e-8a53-4289-bdb0-726400ee5c87

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164e65864d7614b77</li>
        <li>Upwork Job ID: 1800966571830495524</li>
        <li>Last Price Increase: 2024-06-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by b4s36t4** [comment]
I think this is related to backend, backend is not attaching correct `source` paramter for transaction when creating.  The download link is just getting image from server.

**Comment by abekkala** [comment]
not overdue - internal, hotpick

**Comment by abekkala** [comment]
waiting for an internal volunteer to pick up

**Comment by c3024** [comment]
@abekkala This does not seem to be priority. Can this issue be closed? Thanks!
