### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] Track tax - App crashes after assigning deleted tax rate to distance rate offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found around explortary of [42141](https://github.com/Expensify/App/pull/42141)
**Version Number:** 1.4.80-9
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Distance rates and Taxes are enabled.
- Track tax is enabled.

1. Go to staging.new.expensify.com
2. Go offline.
3. Go to Taxes.
4. Delete a tax.
5. Go to Distance rates.
6. Tap on any rate.
7. Tap Tax rate.
8. Select the deleted tax rate in Step 4.
9. Go online.
10. Open the Tax rate RHP while online.
## Expected Result:
In Step 8, the deleted tax rate should be crossed out so that it cannot be assigned to distance rate after it is deleted offline.
## Actual Result:
In Step 8. the deleted tax rate can be assigned to the distance rate.
As a result, app crashes after going online when opening distance rate RHP.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
[Bug6504472_1717718817546!staging.new.expensify.com-1717718558471.txt](https://github.com/user-attachments/files/15689079/Bug6504472_1717718817546.staging.new.expensify.com-1717718558471.txt)

https://github.com/Expensify/App/assets/43996225/a3491022-b73e-410a-a636-1cc15f64ffc3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b6d815717d1c289</li>
        <li>Upwork Job ID: 1799120175681501137</li>
        <li>Last Price Increase: 2024-06-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by kavimuru** [comment]
@mallenexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment]
I'll raise PR soon to fix this regression

**Comment by robertjchen** [comment]
Thanks for handling!

**Comment by kavimuru** [comment]
Issue fixed 

https://github.com/Expensify/App/assets/43996225/6592d4f6-b80b-4a34-8b1a-af4eebd95bd4

**Comment by luacmartins** [comment]
This was fixed - https://expensify.slack.com/archives/C9YU7BX5M/p1717779801507499

**Comment by mallenexpensify** [comment]
@nkdengineer , thanks for the quick opst and for raising the PR to fix this regression (and others). 
I'm assuming payment isn't due here cuz of the regression, comment if anyone disagrees. 

We also shouldn't need a TestRail if this came from a regression.

**Comment by allroundexperts** [comment]
@mallenexpensify I reviewed the PR here as this was a deploy blocker. I think I'm eligible for the review payment.

**Comment by mallenexpensify** [comment]
@nkdengineer @allroundexperts can one of you link the offending PR here?  Is there an easy way for me to find it? I did a quick search on this issue and the PR but didn't see anything. Thx

**Comment by mallenexpensify** [comment]
Looks like this was a regression. @allroundexperts @nkdengineer what was the offending PR that this came from?
Is any payment due here?  Thx

**Comment by nkdengineer** [comment]
I think we only need to process payment for @allroundexperts as the reviewer of the PR fix my regression.

**Comment by allroundexperts** [comment]
## Checklist

1. This was a regression from https://github.com/Expensify/App/issues/41574
2. The author is aware of the regression and fixed it proactively.
3. N/A
4. Steps given in the OP look good enough for the regression test, if one is considered necessary.

**Comment by mallenexpensify** [comment]
Contributor+: @allroundexperts owed $250 via NewDot

TestRail Gh is below. Thanks! 
https://github.com/Expensify/Expensify/issues/406711

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
