### ISSUE TITLE
Sign out - App crashes when signing out offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43258]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.80-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** berhanesarah.testing+@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Sign in to staging
2. Close the tab and reopen staging
3. Go offline
4. Go to settings and sign out

## Expected Result:
User is able to sign out

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8e44fd90-0e00-4aee-a9e7-43e97a058c18

</details>

[Bug6504674_1717746497790!staging.new.expensify.com-1717745501994.txt](https://github.com/user-attachments/files/15738312/Bug6504674_1717746497790.staging.new.expensify.com-1717745501994.txt)

![Bug6504674_1717742902142!Capture](https://github.com/Expensify/App/assets/115492554/0b7da1fa-952b-49e0-b4bb-fc78c6f9e3a2)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by stephanieelliott** [comment]
I'm not sure that this is expected behavior per se, but it doesn't feel buggy either. It makes sense that you wouldn't be able to sign out while offline. I'm inclined to just leave this as-is, since in order to accomplish the action you would need to go back online
