### ISSUE TITLE
Split - App closes split details RHP when saving existing amount without editing it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4604385
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Go to + > Split expense > Scan.
4. Upload a receipt.
5. While the receipt is scanning, click on the split preview.
6. Click Amount.
7. Enter an amount and save it (do not split).
8. Click Amount again.
9. Without editing the amount, click Save.

## Expected Result:
App will return to split details RHP (production behavior).

## Actual Result:
App closes the split details RHP.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a9cffead-a8bb-49b6-ae15-6e81268b917d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@kadiealexander I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-split

**Comment by rlinoz** [comment]
I think this is coming from https://github.com/Expensify/App/pull/42737

**Comment by rlinoz** [comment]
Asked for CP https://expensify.slack.com/archives/C07J32337/p1717769381903089

**Comment by rlinoz** [comment]
Tested CP and this is now fixed, removing the label.
