### ISSUE TITLE
Track Expense - Track Expense option is missing on Self DM page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43257]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4601595&group_by=cases:section_id&group_order=asc&group_id=309130
**Email or phone of affected tester (no customers):** gocemate+a167@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open Global Create (FAB)
2. Choose Track expense
3. Create a manual expense for $1
4. Create the expense
5. Verify it's created in the self DM
6. Navigate to the Self DM
7. Click on the + on compose box ( maybe this should be done couple times)

## Expected Result:
Track expense option should be present

## Actual Result:
Track Expense option is missing on Self DM page after user creates the first Track expense from FAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/971277a5-c0f3-4165-81d0-51224d6ab848

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@twisterdotcom I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment]
I think it's a BE problem, after tracking an expense, the response adds concierge as the participant.
<img width="540" alt="image" src="https://github.com/Expensify/App/assets/50919443/702bb3f0-b84e-4755-879b-d72f0f9086cb">

Refreshing fixes the problem

**Comment by twisterdotcom** [comment]
Okay, adding `Internal`

**Comment by twisterdotcom** [comment]
Will probably just close this for now: https://expensify.slack.com/archives/C066HJM2CAZ/p1721055590330089

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
