### ISSUE TITLE
 Scan IOU - There is a "Enter an amount." error message on receiver side

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43268]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gocemate+a171@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. As User A Create a scan money request with User B
2. As User B while scanning change the merchant of the money request
3. User B interact with the notification
4. Take a look at Amount section

## Expected Result:
There should be no "Enter an amount." error message on receiver side

## Actual Result:
There is a "Enter an amount." error message on receiver side. This option is irresponsible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7797c093-ac91-4431-8504-16c234daaf20

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by anmurali** [comment]
What happens here is the scan continues and eventually completes and overwrites the user's input. 
While it is still scanning, you have manually entered the merchant name, date defaults to current date and what's left is amount, which is shown with an RBR.

On Classic, this works a little differently. You have to abort the job in order to manually enter. And if you do, then you have to enter all 3 fields, date, merchant name and amount. 
<img width="724" alt="image" src="https://github.com/Expensify/App/assets/14225673/e644b3ed-c276-415d-97e2-5bf0964b3f77">

<img width="723" alt="image" src="https://github.com/Expensify/App/assets/14225673/7f749f43-1bae-4378-9090-e06041c8c86c">

I think we want a fix that mimics Classic behavior cause if we allow you to manually enter but keep scanning, we will just end up overwriting the details. Or, we have to abort just that specific field's child SS job but that's a more complex fix as the parent scan job expects results from each of the child jobs. 

Thoughts on how to handle this? @kevinksullivan @puneetlath @JmillsExpensify @trjExpensify

**Comment by trjExpensify** [comment]
On NewDot, entering any of the `merchant`, `date` or `amount` fields manually stops the scanning process. So there's a bug somewhere if that's not happening. If I was to guess, it's probably something to do with the bug report stating that userB took the action and not the person who scanned the receipt.  

>As User A Create a scan money request with User B
>As User B while scanning change the merchant of the money request

@Gonals has some good experience with this logic, having worked on the implementation of scan receipts.

**Comment by anmurali** [comment]
@trjExpensify - when I tested it though, I scanned a receipt and then manually entered the merchant name. So it can't be cause a user that is NOT the scanner changed it manually. It continued to scan even in the case where I, as the scanner, added merchant name manually.

**Comment by trjExpensify** [comment]
>@trjExpensify - when I tested it though, I scanned a receipt and then manually entered the merchant name. So it can't be cause a user that is NOT the scanner changed it manually. It continued to scan even in the case where I, as the scanner, added merchant name manually.

Got it, so still a bug then. We shouldn't override your manually entered merchant name either, that should "stop" the scanning process and you should see errors . Though on paid plans it continues in the background for Concierge DoubleCheck. 

In this case, what I'm seeing is strange insofar as; 

1. The fields scanning appear as `Scanning...` as expected
2. I manually enter a `merchant` it stops the scanning process for me and asks me to manually enter the `amount` field manually, as expected. 
3. Those fields revert to `Scanning...`, not expected. 
4. Once SS'ing completes for DoubleCheck, my manually entered `merchant` and `amount` values are added back.

So the bug I see there is that we're somewhere reverting to `Scanning...` when we shouldn't be after step #2. 

https://github.com/Expensify/App/assets/16232057/2e3efb24-d0c8-4ce2-b012-e200ecaeebe5

**Comment by anmurali** [comment]
<img width="1122" alt="image" src="https://github.com/Expensify/App/assets/14225673/1eec73a6-9509-4962-aa52-0ae6aec4fbdc">

<img width="1112" alt="image" src="https://github.com/Expensify/App/assets/14225673/91c1bc60-5e1a-4d45-a382-5227a5dbe480">

**Comment by anmurali** [comment]
This is intended behavior. 
If you interrupt the scan to manually add one of the details, it aborts the scan itself. Then you have to manually add all of the required details or you will see an RBR. Note: Date is defaulted to the date the request is created unless the scan produces a different result.
