### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Track expenses - Unavailable workspace shown &app crashes if select share it with my accountant

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43260]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4605669
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in with a new account
2. Tap FAB > Track Expenses
3. Enter the amount and complete the expense creation
4. Navigate to self DM
5. Select "Share it with my accountant" in actionable whisper
6. On confirmation page tap Submit

## Expected Result:
The new workspace name displayed in on the confirmation page and user is able to proceed to the participant page

## Actual Result:
The Unavailable workspace is displayed on the confirmation page and the app crashes after tapping "Submit"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/17054e6b-1b4a-46a0-bf77-8360c8522071

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f7ddb2eef36b28f</li>
        <li>Upwork Job ID: 1799111618417504843</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102686818</li>
<li>dominictb | Contributor | 102686821</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by garrettmknight** [comment]
@akinwale mind giving this proposal a review?

**Comment by akinwale** [comment]
We can move forward with @dominictb's [proposal](https://github.com/Expensify/App/issues/43260#issuecomment-2155226880) here.

🎀👀🎀 C+ reviewed.

**Comment by amyevans** [comment]
I'm unassigning since I'm headed out on extended leave after today. When the PR is approved Melvin _should_ auto-assign a new internal engineer to review it.

**Comment by garrettmknight** [comment]
**Payment summary:**
- Contributor: @dominictb $250 paid via Upwork
- Reviewer: @akinwale $250 paid via Upwork

@akinwale can you complete the checklist when you get a chance?

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify.
2. Login with a brand new account.
3. Open the global create menu and select Track Expenses.
4. Enter an amount and finish creating the expense.
5. Navigate to the self-DM report.
6. Select "Share it with my accountant" from the list of actions in the self-DM.
7. Verify that the name of the new workspace (not **Unavailable workspace**) is displayed on the confirmation page.
8. On the confirmation page, click or tap Submit.
9. Verify that the app does not crash.

Do we agree 👍 or 👎?

**Comment by garrettmknight** [comment]
All set
