### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Hold expenses - "iou.genericHoldExpenseFailureMessage" error when holding a paid expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43279]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4605660
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit expense to User B
3. [User A] Go to transaction thread
4. [User A] Go to 3-dot menu > Hold
5. [User A] Leave the Hold RHP open
6. [User B] Pay the expense
7. [User A] After the expense is paid on their end, enter a reason and save it

## Expected Result:
User A will receive an error that the expense cannot be held/edited

## Actual Result:
User A receives the error "iou.genericHoldExpenseFailureMessage"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/095978c0-8514-4ab2-90d0-02758203154d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015aa1fc4dd1f5a60d</li>
        <li>Upwork Job ID: 1800577247384003062</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102706048</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment]
This one slipped my radar; I will test it tomorrow.

**Comment by alexpensify** [comment]
I didn't get a generic error but I was able to save the Hold action. 

![2024-06-11_10-11-52](https://github.com/Expensify/App/assets/8107070/562f61a4-0581-4f1e-a15f-f037ff89c015)

**Comment by alexpensify** [comment]
@parasharrajat can you please review if this proposal will fix the issue and flag when an expense can't be put on Hold? Thanks!

**Comment by bernhardoj** [comment]
PR is ready

cc: @parasharrajat

**Comment by alexpensify** [comment]
Update the PR is going through the review process.

**Comment by Julesssss** [comment]
Test steps are fine, but I don't think we need a full regression test for this simple text issue tbh.

**Comment by alexpensify** [comment]
Automation worked here, I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment]
Payouts due: 2024-06-28

- [ ] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @parasharrajat 

Upwork job is [here](https://www.upwork.com/jobs/~015aa1fc4dd1f5a60d).

Status: @parasharrajat please submit a request in Chat. @bernhardoj has been paid in Upwork. I now need to create the regression test.
