### ISSUE TITLE
[HOLD for payment 2024-07-15] [Payment card / Subscription] Localize subscription prices to appropriate currency

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#43277]
Coming from [this thread in the "Subscription settings" UI implementation PR](https://github.com/Expensify/App/pull/42990#discussion_r1629726307), we should display all prices in the Subscription section of the app localized to the user's currency.

For example, the text
```
saveUpTo: 'Save up to $10/month per active member',
```
would show GBP if that is your billing currency.

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by trjExpensify** [comment]
@blimpich assigning you for vis.

**Comment by MrMuzyk** [comment]
I won't be able to update the PR today with one more change that was pointed out to me. Tomorrow Im OOO so I will get back to it on monday morning

**Comment by trjExpensify** [comment]
Moving this into being a release blocker, as it's important we show accurate and localised billing amounts. 👍

**Comment by trjExpensify** [comment]
PR merged yesterday. Assigning @allgandalf as the C+ reviewer.

**Comment by trjExpensify** [comment]
Changed to 15th!

**Comment by trjExpensify** [comment]
Yep! Payment summary as follows: 

- $250 to @allgandalf for the C+ review 

Sent you an offer. We don't need a regression test here, they'll be added centrally for the project as we wrap it up.

**Comment by trjExpensify** [comment]
Paid, closing!
