### ISSUE TITLE
Android - Receipt - After uploading image user directed to search page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A

## Action Performed:
Pre-condition: open account which has expense with no receipt
1. Launch app
2. Tap profile icon-- troubleshoot- search
3. Open expense
4. Tap receipt
5. Upload an image

## Expected Result:
After uploading image user must be directed to IOU details page

## Actual Result:
After uploading image user directed to search page instead of IOU details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b771ff2c-15cc-4e21-83d5-824634bdc704

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@hayata-suenaga  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by luacmartins** [comment]
This is the new expected behavior. @lanitochka17 do we need to update any TC to reflect this?

**Comment by JmillsExpensify** [comment]
Agree that this is expected behavior.

**Comment by hayata-suenaga** [comment]
Thank you for confirming that this is the expected behavior. Closing the issue.

**Comment by lanitochka17** [comment]
@luacmartins The issue was not found by TC

**Comment by luacmartins** [comment]
OK, so it seems like we dont need to update anything
