### ISSUE TITLE
[Payment history] create new `CancelBillingSubscriptionNewDot` command

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#43285]
Complete the backend portion of this part of the design doc: [add "Request early cancelation" menu item](https://docs.google.com/document/d/1_FunWUV6BMh1qN4BSWBmHSfcafVvY08ZVlBjw6zksj4/edit#heading=h.vqk3oirc8okh).

**Comment by blimpich** [comment]
Note: Probably want to update [USED_NVPS](https://github.com/Expensify/Auth/blob/790d5402f9637e5d11c6554f900f6e737f63ba31/auth/lib/OnyxUpdates.h#L49) as part of this. Anything in there should get updated in Onyx when the NVP is updated in Auth (I think).

**Comment by blimpich** [comment]
Yay 🎉 Thank you @rlinoz! I will review the Auth PR today.

**Comment by rlinoz** [comment]
Everything is merged, waiting for the Web-E deploy.

**Comment by rlinoz** [comment]
Web-E was deployed to prod: https://github.com/Expensify/Web-Expensify/pull/42377#issuecomment-2187981522
