### ISSUE TITLE
[Payment history] update `notifications/RefundReceipt.html` to new design

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#43288]
Complete this portion of the design doc: [Notifications – Refunds](https://docs.google.com/document/d/1_FunWUV6BMh1qN4BSWBmHSfcafVvY08ZVlBjw6zksj4/edit#heading=h.o2egac27p8xq).

**Comment by blimpich** [comment]
@carlosmiceli just confirming, you're picking this up? If so lets remove the `Hot Pick` label 🔥. Thank you for working on this!

**Comment by carlosmiceli** [comment]
Yes! I'll do my best to make daily progress on it, it was `Monthly` when I picked it up :P
But it feels like something I could take on 💪

**Comment by carlosmiceli** [comment]
Will have to start tomorrow.

**Comment by carlosmiceli** [comment]
I'm on it Melv...

**Comment by blimpich** [comment]
Deployed to production so I closed it.
