### ISSUE TITLE
[HOLD for payment 2024-08-02] [Payment history] add "Request early cancelation" menu item to the Subscription page (UI)

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#43282]
Complete the frontend portion of this part of the design doc: [add "Request early cancelation" menu item](https://docs.google.com/document/d/1_FunWUV6BMh1qN4BSWBmHSfcafVvY08ZVlBjw6zksj4/edit#heading=h.6s798ua7qome).

Dependent on https://github.com/Expensify/App/issues/43285 for backend data/endpoint.

<details><summary>Issue Owner</summary>Current Issue Owner: @JKobrynski</details>

**Comment by blimpich** [comment]
Not overdue, waiting for hold to release.

**Comment by trjExpensify** [comment]
WebPR is deployed to prod, this can come off hold.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by blimpich** [comment]
Backend is deployed and ready to go.

**Comment by blimpich** [comment]
Adding @mananjadhav since they are reviewing the associated PR

**Comment by blimpich** [comment]
@JKobrynski @mananjadhav any update here? Where are we at with the PR?

**Comment by mananjadhav** [comment]
I saw one commit from @JKobrynski that they started with the backend integration. Once they mark it ready, I'll start with the review.

**Comment by blimpich** [comment]
Looks like I forgot to assign a bug zero to this issue. @alexpensify we had C+ @mananjadhav review the PR from @JKobrynski who is a callstack engineer. Can you handle payment for this? Should be the standard $250 for a review. Both of the "deploy blockers" linked to this are extraordinarily minor and not real blockers, so I say no regression penalty for this.

**Comment by alexpensify** [comment]
Noted, I'll prepare for Friday! Thanks for the notes.

**Comment by alexpensify** [comment]
Payouts due: 2024-08-02

- [ ] Contributor: N/A @JKobrynski - payment will be handled via partner 
- [ ] Contributor+: $250 @mananjadhav - please submit a request in Chat, thanks! 

Upwork job is N/A. The payment for @mananjadhav will be handled via Chat.

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
