### ISSUE TITLE
[HOLD for payment 2024-07-10] [Payment history] add "View payment history" menu item to the Subscription page (UI)

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#43281]
Complete the frontend portion of this part of the design doc: [Add "View payment history" menu item](https://docs.google.com/document/d/1_FunWUV6BMh1qN4BSWBmHSfcafVvY08ZVlBjw6zksj4/edit#heading=h.2bmu5o66ldns).

Depends on https://github.com/Expensify/App/issues/43284 for backend data. Also dependent on search page being available.

**Comment by blimpich** [comment]
Backend changes were deployed. We're ready to have this be worked on.

**Comment by trjExpensify** [comment]
Discussed [here](https://expensify.slack.com/archives/C036QM0SLJK/p1718882028239549?thread_ts=1718719209.103989&cid=C036QM0SLJK), @mananjadhav is going to implement this.

**Comment by blimpich** [comment]
I think we should hold this issue still till search is more well-featured. We still need the ability to query by merchant in order to implement this.

**Comment by blimpich** [comment]
Ugh I forgot to assign myself to this, feel free to ignore @pecanoro

**Comment by lschurr** [comment]
It looks like @rushatgabhane reviewed the PR as well - Should he be added to the payment summary as well @blimpich @mananjadhav?

**Comment by mananjadhav** [comment]
Yes @lschurr. I wrote the PR, and @rushatgabhane reviewed it. He should've been added to the payment summary.

We both would raise it on NewDot.

**Comment by lschurr** [comment]
Updated Payment Summary:

- Contributor: $250 @mananjadhav (via NewDot)
- Reviewer: $250 @rushatgabhane (via NewDot)

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by lschurr** [comment]
Closing since these will be paid in ND

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
