### ISSUE TITLE
[Payment history] update Balance Transfer receipts to new design

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#43289]
Complete this portion of the design doc: [Notifications – Balance Transfers](https://docs.google.com/document/d/1_FunWUV6BMh1qN4BSWBmHSfcafVvY08ZVlBjw6zksj4/edit#heading=h.fxejy5helupv).

**Comment by dangrous** [comment]
not really overdue, synced with @blimpich when I grabbed it and we determined Tuesday was fine! I'm back now from parental leave so will be working on this today.

**Comment by dangrous** [comment]
eyyy finally figured out how to send one of these in dev. PR should be pretty quick now!

**Comment by dangrous** [comment]
This has been merged, should be closed shortly!

**Comment by dangrous** [comment]
still confirming our Prod QA for this - trickier than expected!

**Comment by dangrous** [comment]
okay just waiting for "billing" to [run](https://github.com/Expensify/Expensify/issues/409975), then should be able to finish this out in 5 min or so.

**Comment by dangrous** [comment]
Finally did it. It works!
<img width="1138" alt="Screenshot 2024-07-08 at 09 54 44" src="https://github.com/Expensify/App/assets/5487802/f31e2eca-435c-48da-a6d1-e523ac3b505d">
