### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Payment history] add "Request refund" menu item to the Subscription page (UI)

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#43283]
Complete the frontend portion of this part of the design doc: [add "Request refund" menu item](https://docs.google.com/document/d/1_FunWUV6BMh1qN4BSWBmHSfcafVvY08ZVlBjw6zksj4/edit#heading=h.8vw1opt57ioz).

Dependent on https://github.com/Expensify/App/issues/43286 for backend data.

<details><summary>Issue Owner</summary>Current Issue Owner: @kubabutkiewicz</details>

**Comment by kubabutkiewicz** [comment]
Hi, I'm Jakub from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by blimpich** [comment]
Assigning @mananjadhav since they reviewed the PR as C+

**Comment by mananjadhav** [comment]
@blimpich Can you assign a BZ or post the payment summary for this one. This is supposed to be ready for payout today.

**Comment by blimpich** [comment]
My bad @mananjadhav! I should have assigned this earlier to a bug zero member.

@anmurali can you handle payment for this? @mananjadhav needs to be paid for reviewing [this PR](https://github.com/Expensify/App/pull/44138)

**Comment by mananjadhav** [comment]
Quick bump @anmurali for the payout summary.

**Comment by anmurali** [comment]
**Payment summary (ready to be paid)**
- [ ] Reviewer: @mananjadhav owed $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
