### ISSUE TITLE
Android - Split - Hitting check/Done button on split input does not dismiss the keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43291]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4605116
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to group chat
3. Go to + > Split expense > Manual
4. Enter amount > Next
5. Tap on the split input
6. Enter amount
7. Hit check button (gboard) or Done button (Samsung keyboard)

## Expected Result:
Hitting check/Done button on split input will dismiss the keyboard (mweb behavior)

## Actual Result:
Hitting check/Done button on split input does not dismiss the keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3f677aeb-8ac2-41bf-b0c5-e8b79b51021f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
Reproducible. This project is being paused, so I'm not sure if I should leave this open. [Discussing ](https://expensify.slack.com/archives/C05RECHFBEW/p1717772247644229?thread_ts=1717762303.332349&cid=C05RECHFBEW)

**Comment by joekaufmanexpensify** [comment]
Discussed in Slack and decided we should close this.
