### ISSUE TITLE
[$250] Android - Login - Sometimes the magic code isn't auto focused, the keypad isn't active

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43292]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/42387
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Tap on the "Continue" button after filling email address
3. Tap on "Go back"

## Expected Result:
Magic code should be focused.

## Actual Result:
Sometimes the magic code isn't auto focused, the keypad isn't active.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0bb1c510-2983-4730-a7af-61adb6d23a7e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd9a0d353a5a06e3</li>
        <li>Upwork Job ID: 1800346129602261560</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by hungvu193** [comment]
This looks so déjà vu to me 🤔 . Checking

**Comment by hungvu193** [comment]
I couldn't find related issue or PR linked to this one.
Waiting for proposals 👀

**Comment by hungvu193** [comment]
Still waiting for proposals.

**Comment by hungvu193** [comment]
Same here. Still waiting for proposals

**Comment by muttmuure** [comment]
ngl, I'm not sure this is a big deal. Maybe you disagree, but I would prefer to use the NewDot Quality auto-assigner to fix higher value bugs

**Comment by hungvu193** [comment]
Bumped on slack

https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1718675218718809

**Comment by jp928** [comment]
@izarutskaya I am knee to help on this. Would you mind to advise the android version as well? I couldn't replicate this on Android 14. Sometime I could trigger it if I do multiple click on the Continue button, is it the way to trigger it?

**Comment by hungvu193** [comment]
I also can't reproduce this

**Comment by hungvu193** [comment]
Asking BZ team to reproduce this one

**Comment by hungvu193** [comment]
Would you mind to confirm if you still can reproduce this one? @greg-schroeder

**Comment by hungvu193** [comment]
Little bump question on the above question 🙋‍♂️

**Comment by hungvu193** [comment]
little bump @greg-schroeder

**Comment by hungvu193** [comment]
Same

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests. 

https://github.com/Expensify/App/assets/43995119/278e53ad-a165-4853-afbd-78196a942527

**Comment by jp928** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Sometimes the magic code isn't auto focused, the keypad isn't active on Login page.

### What is the root cause of that problem?

The navigation transition has conflicts with keyboard popup. And it seems like a known issue with react-navigation.
https://github.com/react-navigation/react-navigation/issues/10619

### What changes do you think we should make in order to solve the problem?
update following line
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/components/MagicCodeInput.tsx#L374

to 
```
autoFocus={autoFocus && Platform.OS !== 'android'}
```

Add
```
useFocusEffect(
    useCallback(() => {
      setTimeout(() => {
        ref.current?.focus();
      }, 250);
    }, [])
  );
```
250 is the time react-navigation transition time between screens.




### What alternative solutions did you explore? (Optional)
NA

**Comment by hungvu193** [comment]
@jp928 I don't think your RCA is correct, if `The navigation transition has conflicts with keyboard popup` then why it only happened in login screen? We have other screens that used MagicCodeInput as well. (ie: `ContactMethodDetailsPage` or `VerifyStep`).

**Comment by hungvu193** [comment]
Still waiting for proposals

**Comment by greg-schroeder** [comment]
Proposal review underway

**Comment by hungvu193** [comment]
Still waiting for proposals

**Comment by hungvu193** [comment]
@greg-schroeder Do you think we should raise the bounty to get more 👀 here?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by hungvu193** [comment]
I'll prioritize this on this weekend.

**Comment by hungvu193** [comment]
I got some troubles to reproduce this one on my android simulator

**Comment by hungvu193** [comment]
Can you reproduce this one? @greg-schroeder

**Comment by greg-schroeder** [comment]
I am also not able to reproduce using an android sim, so i'm going to close as it must have been solved elsewhere? Please reopen if you disagree or can repro
