### ISSUE TITLE
[Payment card / Subscription] Polish "Subscription details" section with `useThemeIllustrations`

### ISSUE THREAD

**Issue by amyevans** [Expensify/App#43306]
Per [this comment](https://github.com/Expensify/App/pull/42975#pullrequestreview-2102786996) on the PR for https://github.com/Expensify/App/issues/38623, we should refactor to use themed illustrations and the `useThemeIllustrations` hook for the `ExpensifyApproved` logo. See https://github.com/Expensify/App/tree/32f176fe7734c27ee0b8e0256e8a8fd5a6ac237d/src/styles/theme/illustrations.

**Comment by JKobrynski** [comment]
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by JKobrynski** [comment]
The [PR](https://github.com/Expensify/App/pull/43370) is ready for review!

**Comment by roryabraham** [comment]
PR merged, no C+ services used. Closing this out.
