### ISSUE TITLE
Expense report - System message that report was paid not displayed in ND when admin pays in OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43311]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4397017
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition: user is a member of a collect workspace
1. Log in to ND as a member of a collect workspace
2. Navigate to the workspace report
3. Submit a manual expense
4. Log into OD as an admin
5. Open the submitted report
6. Approve the report
7. Paid the report either by marking as paid outside Expensify or via Direct Deposit if it was set up
8. Open the paid report in ND as the member

## Expected Result:
The system messages that the report was approved and paid is displayed

## Actual Result:
Only the system message that the report was approved is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/008c3815-a2c1-4b3a-858a-da2159c13c36

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment]
Onyx is disabled in OldDot right now, so this is expected and will require a wider fix beyond the scope of this issue
