### ISSUE TITLE
[HOLD for payment 2024-06-20] Change icon of the hub connections.

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#43314]
Slack: https://expensify.slack.com/archives/C02QSAC6BJ8/p1717772156939879

Following these steps: https://github.com/Expensify/App/tree/main/docs#how-to-change-icon-of-a-hub

We have to change the illustration of connections hub for both platforms - Expensify Classic and New Expensify

**Comment by dannymcclain** [comment]
Hey @dylanexpensify, this isn't _really_ a bug, just a quick design update, so I unassigned you and assigned myself.

@rushatgabhane thanks for the guidance!

**Comment by dannymcclain** [comment]
cc @maddylewis just so you have eyes on this. I should be able to get to it Monday.

**Comment by dannymcclain** [comment]
PR open ☝️

**Comment by rushatgabhane** [comment]
checklist / payment not applicable
