### ISSUE TITLE
[HOLD for payment 2024-06-20] [$250] LHN - Most recent priority mode displayed as #focus and the other way around on secondary device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43315]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4605078
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify with the same account on two devices/two separate browsers
2. [Device 1] Navigate to Account Settings > Preferences
3. [Device 1] Change Priority mode to "#focus"
4. Verify the change on [Device 2]
5. [Device 1] Change Priority mode to "Most recent"
6. Verify the change on [Device 2]

## Expected Result:
Priority mode should change on secondary device and the LHN should be displayed in the same style on both devices

## Actual Result:
Priority mode changes on the secondary device accordingly to the changes made on the [Device 1] but it is displayed in the style of the other priority mode in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7ca5a4ec-3895-4202-aac7-bf45f3cf5ddd

https://github.com/Expensify/App/assets/78819774/36cf899f-c876-4439-bd6d-155d1f78bdce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01761ff40a6e4283bd</li>
        <li>Upwork Job ID: 1799172422521172555</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102666669</li>
<li>bernhardoj | Contributor | 102666670</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
The most recent/focus mode view doesn't update correctly when it's updated from secondary device.

### What is the root cause of that problem?
The most recent/focus mode view depends on `optionMode`.
https://github.com/Expensify/App/blob/4176e95f4fa0867a56092af23193c6e2c8f4e23e/src/components/LHNOptionsList/LHNOptionsList.tsx#L139

However, the list doesn't re-render correctly when `optionMode` is updated because it's missing from the `extraData`.
https://github.com/Expensify/App/blob/4176e95f4fa0867a56092af23193c6e2c8f4e23e/src/components/LHNOptionsList/LHNOptionsList.tsx#L167-L170

Any external dependency should be included on the `extraData`.

### What changes do you think we should make in order to solve the problem?

Add `optionMode` to the `extraData`.

_and any other data if needed_

**Comment by c3024** [comment]
Does `optionMode` need to be added in the `extraData` array as well or only in the dependencies?

**Comment by c3024** [comment]
Apparently `FlashList` [rerenders only](https://github.com/Shopify/flash-list/issues/585#issuecomment-1250020456) if both `data` and `renderItem` change. It is suggested to force the rerender using `extraData` [here](https://github.com/Shopify/flash-list/issues/699#issuecomment-1383450927). 

So, creating a new reference for the `extraData` adding `viewMode` as dependency makes sense.

@bernhardoj 's proposal [here](https://github.com/Expensify/App/issues/43315#issuecomment-2155788727) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @c3024

**Comment by slafortune** [comment]
@bernhardoj Paid via Upworks ✅ 
@c3024 Paid via Upworks ✅
