### ISSUE TITLE
 Track tax - App crashes when opening distance rate after deleting a tax rate associated to it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-14
**Reproducible in staging?:** yes
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Distance rates and Taxes are enabled.
- Track tax is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Distance rates.
4. Click on any rate.
5. Apply a tax rate.
6. Go to Taxes and delete the tax rate selected in Step 5.
7. Go back to Distance rates.
8. Click on the same distance rate with tax rate.
9. Click Tax rate.
10. Wait for the app to crash.
## Expected Result:
App should not crash
## Actual Result:
App crashes

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/994e883b-53d0-4571-81fc-6ebbd0b235e5

[Bug6505492_1717787207941!staging.new.expensify.com-1717786709620.txt](https://github.com/user-attachments/files/15744055/Bug6505492_1717787207941.staging.new.expensify.com-1717786709620.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@abekkala FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by luacmartins** [comment]
Confirmed this is fixed on staging!
