### ISSUE TITLE
[$250] IOS - Request money - Duplicate results in the search when submit an expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43329]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80.15
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4599552
**Email or phone of affected tester (no customers):** monitozb87+admin2305@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the new expensify app
2. Navigate to a 1:1 conversation
3. Request money to the other user
4. Navigate to search

## Expected Result:
Verify that the message preview displays the IOU information - [User] owes [amount]

## Actual Result:
There are a duplicated results with [User] owes [amount]

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/14111a52-62c6-4d5a-ad6a-06898ef2e0fc

![Bug6505574_1717792637688!Imagen_de_WhatsApp_2024-06-07_a_las_15 32 38_aacd20b9](https://github.com/Expensify/App/assets/78819774/17813b7d-45b3-471e-a34b-ad86ceedcb12)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01674a7c958c16265b</li>
        <li>Upwork Job ID: 1800307216998791308</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment]
Working on testing now.

**Comment by strepanier03** [comment]
Able to repro using Browserstack on and iPhone 15. 

<img width="371" alt="image" src="https://github.com/Expensify/App/assets/10925636/6ef6ccf2-ab90-4d81-a8c8-b4d1c7ab54b3">

[New Expensify.ipa_2024_6_10_16_19_45.log](https://github.com/user-attachments/files/15780090/New.Expensify.ipa_2024_6_10_16_19_45.log)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment]
Looks like KI tests couldn't repro either. I will give it another week of testing and then close if we still can't reproduce it.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)
