### ISSUE TITLE
Feature request: Implement to use emojis as group chat images

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43333]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Problem:
We don't have the option to use emojis as group chat images
## Solution:
 It would be nice to use emojis as group chat images, instead of a  photo to use.

## Context/Examples/Screenshots/Notes:

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1717707180105419
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
This does seem like a cool idea, but in light of our prioritization, I feel like we should punt any group chat enhancements right now? Curious if others agree, cc @puneetlath @Expensify/design

**Comment by dubielzyk-expensify** [comment]
Yeah, I'm inclined to agree. I love the idea though :)

**Comment by dannymcclain** [comment]
Totally agree. I 100% want and would use this feature 😂 but this doesn't feel like something we should prioritize right now.

**Comment by trjExpensify** [comment]
:bigagree:

**Comment by zanyrenney** [comment]
Cool, works for me. I'll close this out for now.
