### ISSUE TITLE
[$250] [HOLD for payment 2024-07-10] [HybridApp] Do not allow logout in NewDot HybridApp

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#43336]
### Problem
If a user logs out of HybridApp via NewDot, many weird things can happen including crashes.

### Solution
Do not allow HybridApp users to logout via NewDot

cc @staszekscp 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01970b1b535b50d220</li>
        <li>Upwork Job ID: 1810704730661899086</li>
        <li>Last Price Increase: 2024-07-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by AndrewGable** [comment]
Hopefully will get to this tomorrow

**Comment by AndrewGable** [comment]
Ok so I think we need to actually expand the scope of this one a bit:
1. Do not show the logout button on NewDot
2. Anytime we are going to log out of NewDot, we should go back to OldApp and then log the user out there (if we have to)

The reason is we cannot support the NewDot sign in page for HybridApp, since OldApp contains all the authentication logic for HybridApp.

**Comment by AndrewGable** [comment]
@shawnborton is still having issues with an automatic log out:



https://github.com/Expensify/App/assets/2838819/ed37f0fb-c8b9-406f-904c-d9a561dd0a37




We should look for logs to determine why he is being kicked out.

**Comment by AndrewGable** [comment]
Going to look into this one soon

**Comment by AndrewGable** [comment]
cc @wojtus7 - I was thinking this could be a good issue to look into.

Basically we do not want to ever go to the NewDot login page on HybridApp. 

1. We want to hide the Sign out button if we are on HybridApp
2. When the user should be signed out automatically (due to an authentication error), we want to exit NewDot instead of showing them the login page on NewDot.

**Comment by WoLewicki** [comment]
Commenting :rocket:

**Comment by WoLewicki** [comment]
PR fixing this: https://github.com/Expensify/App/pull/44092

**Comment by AndrewGable** [comment]
This is done!

**Comment by mallenexpensify** [comment]
@akinwale can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01970b1b535b50d220

@abekkala , please pay tomorrow, [PR hit production July 3](https://github.com/Expensify/App/pull/44092#issuecomment-2207062543).  Thx

**Comment by akinwale** [comment]
@mallenexpensify I did not receive an offer for the job. Do I just go ahead to submit a proposal on Upwork?

**Comment by mallenexpensify** [comment]
Strange, I probably messed something up.  You should be able to accept the job now. 
https://www.upwork.com/jobs/~01970b1b535b50d220

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JULY 10

- Fix: @WoLewicki - SWM, no payment needed
- PR Review: [$250] payment sent and contract ended - thank you! 🎉
