### ISSUE TITLE
[$250] [Search v1] Android - Search - Not here page shows up when returning to Search from Account settings

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43358]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to Search.
3. Go to Account settings.
4. Tap device back button until app returns to Search page.

## Expected Result:
App will return to Search page without issue.

## Actual Result:
Search page shows not here when returning to Search from Account settings.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/69461feb-aa47-4573-9c2a-6bc2f937a598

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddce9cae8b4d807e</li>
        <li>Upwork Job ID: 1800216134777572189</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adamgrzybowski</details>

**Comment by izarutskaya** [comment]
@laurenreidexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by adamgrzybowski** [comment]
Hi! I will take a look at it with @WojtekBoman

**Comment by luacmartins** [comment]
I see `[info] Navigating to route - {"path":"/Search_Bottom_Tab"}` in the logs

**Comment by roryabraham** [comment]
I _feel_ like I've seen a similar bug report when a screen is placed in the wrong navigator.

**Comment by luacmartins** [comment]
This was fixed by the CP. No payments to contributors are needed here, since the fix was done by SWM and they will invoice us for it. Gonna close this issue.
