### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [MEDIUM] Debugability: Add username/accountID to the Ping command so we can diagnose problems with it better 

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#43354]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
e.g. memory consumption, storage read/write times, React native bridge concerns, inefficient React component rendering, etc.

We use PING to track responsiveness between client, server and db. Currently, we do not log the user's username when the PING command is executed, so when reviewing the server-side logs, it's hard to find the logline for a PING. 

## What is the impact of this on end-users?
List specific user experiences that will be improved by solving this problem e.g. app boot time, time to for some interaction to complete, etc.

This is a debugging issue, where this will help us triage connectivity issues with clients. 

## List any benchmarks that show the severity of the issue
Please also provide exact steps taken to collect metrics above if any so we can independently verify the results.

N/A

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

Add the user's accountID to PING so we can easily trace them in the server side logs. 

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** 

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by tgolen** [comment]
I'll take this one and work on it.

**Comment by tgolen** [comment]
# Daily Update
- I've created an [App PR](https://github.com/Expensify/App/pull/43385) to implement this

### Next Steps
- Wait for PR to be reviewed and merged

#### ETA
- Deployed by tomorrow, June 11

**Comment by alitoshmatov** [comment]
Commenting here, I reviewed the PR as C+

**Comment by tgolen** [comment]
@sakluger I'm adding you here because @alitoshmatov needs to be paid $250 for a C+ review of my PR.

**Comment by sakluger** [comment]
Sounds good! I added the internal label hoping it would create an Upwork job, not sure why it didn't. Once the PR is deployed to prod, I'll manually create an Upwork job and send an offer to @alitoshmatov.

**Comment by sakluger** [comment]
The PR is currently on staging. Changing to weekly since payment is at least 1 week out.

**Comment by alitoshmatov** [comment]
No checklist needed since it wasn't a bug nor a feature. It was a small change in debugging, specifically adding additional data to `ping` api

**Comment by alitoshmatov** [comment]
Automation is having some hiccup, PR was deployed on june 18 and payment is due today. Checklist is not needed as I mentioned [here](https://github.com/Expensify/App/issues/43354#issuecomment-2175732217).

**Comment by sakluger** [comment]
Thanks for the comment @alitoshmatov, and sorry for the delayed payment!

Summarizing payment on this issue:

Contributor+: @alitoshmatov $250, sent offer via Upwork (https://www.upwork.com/nx/wm/offer/102892849)

**Comment by sakluger** [comment]
@alitoshmatov let me know once you've accepted the offer. Thanks!

**Comment by alitoshmatov** [comment]
@sakluger Accepted the offer
