### ISSUE TITLE
[HOLD for payment 2024-06-20] Remove unnecessary WorkspaceSwitcherButton component renders

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#43352]
### Problem

Mykhailo located a performance improvement within WorkspaceSwitcherButton where we can remove some unnecessary re-renders.

Discussed [here ](https://expensify.slack.com/archives/C05LX9D6E07/p1718016435622369)in Slack

### Solution

As explained by Mykhailo: 

> Use React.memo for the component to rerender only when necessary. Do not destruct object and use it directly.

<details><summary>Issue Owner</summary>Current Issue Owner: @Julesssss</details>

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
I've opened the [PR](https://github.com/Expensify/App/pull/43365) for review.

**Comment by allroundexperts** [comment]
Can I get assigned here since I reviewed @Julesssss?

**Comment by Julesssss** [comment]
Yeah, my bad

**Comment by anmurali** [comment]
**Payment Summary**
- [ ] $250 to @allroundexperts is approved whenever requested via ND

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
