### ISSUE TITLE
[HOLD for payment 2024-07-17] report.errorFields.notFound is being cleared incorrectly

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#43357]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Latest
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @arosiclair 
**Slack conversation:** https://github.com/Expensify/App/pull/35671#discussion_r1630277598

## Action Performed:

1. Create a workspace
2. Create a workspace room
3. Copy the URL
4. Log in as a non-workspace member
5. Visit the room URL
6. Verify a not found page displays
7. Invite the user to the workspace

## Expected Result:
The not found error is cleared by an update from the backend

## Actual Result:
We're clearing the error using a side effect in ReportScreen [here](https://github.com/Expensify/App/blob/66cd70716217b91c927d5267f7672b1d080ac17f/src/pages/home/ReportScreen.tsx#L404-L412).

## Workaround:
N/A

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

N/A

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by arosiclair** [comment]
`errorFields.notFound` gets set by `OpenReport` when the report doesn't exist or you don't have access to it. It gets cleared on success [here](https://github.com/Expensify/App/blob/c3ab92d2d8c506fdff0bf6a261b885a340be003c/src/libs/actions/Report.ts#L778-L786) but we should also clear it when the report gets shared to the user and we push it with an Onyx update. We can do that by updating [Report::structureReportForOnyx](https://github.com/Expensify/Auth/blob/5110e614fe472804988dbb845536a3565e138016/auth/lib/Report.cpp#L8632). Once that's done we can remove [this side effect](https://github.com/Expensify/App/blob/66cd70716217b91c927d5267f7672b1d080ac17f/src/pages/home/ReportScreen.tsx#L404-L412).

**Comment by puneetlath** [comment]
Makes sense @arosiclair. Will you raise a PR?

**Comment by arosiclair** [comment]
Yup this is just low priority for me atm. I'll get to it soon

**Comment by arosiclair** [comment]
PR's are ready just have to wait for the [Auth PR](https://github.com/Expensify/Auth/pull/11333) to be deployed before posting the App PR. ETA is end of next week.

**Comment by puneetlath** [comment]
Is there any App aspect to this? Or it's al back-end?

**Comment by arosiclair** [comment]
Already part of #newdot-quality [here](https://expensify.slack.com/archives/C05R2V5GM1S/p1718914426107489)

**Comment by puneetlath** [comment]
@shubham1206agra friendly reminder about the checklist so we can pay tomorrow.

**Comment by puneetlath** [comment]
@shubham1206agra bump on the checklist.

**Comment by puneetlath** [comment]
@shubham1206agra I sent you an offer: https://www.upwork.com/nx/wm/offer/103254802

Please ping me here when you've accepted.

**Comment by puneetlath** [comment]
Regression test update: https://github.com/Expensify/Expensify/issues/415177
