### ISSUE TITLE
[$125] [Search v1] - Search opens and loads infinitely when opening as logged out user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43360]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log out of staging.new.expensify.com
2. Navigate to a public room.
3. Click Search.

## Expected Result:
Login modal will show up.

## Actual Result:
Search - Expenses opens and loads infinitely.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1be3e917-afe4-46fa-b4fb-199253d6b044

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b9424090f49ccd4</li>
        <li>Upwork Job ID: 1800181442306969972</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by izarutskaya** [comment]
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by mountiny** [comment]
I can help here too

**Comment by Kicu** [comment]
I have a working fix and I will handle this

**Comment by luacmartins** [comment]
@Kicu will work on a fix

**Comment by Kicu** [comment]
it seems an easy fix - I created a PR

**Comment by luacmartins** [comment]
Fixed on staging 

https://github.com/Expensify/App/assets/22219519/0aebf329-4f06-409d-b2c5-69efb6ca81fc

**Comment by kbecciv** [comment]
Issue is fixed after CPed

https://github.com/Expensify/App/assets/93399543/bce785f5-1c4b-4415-9382-42ca3ab9b5ca

**Comment by alexpensify** [comment]
Keeping closed and will close the Upwork job. The summary here is accurate: 

https://github.com/Expensify/App/issues/43360#issuecomment-2161787411
