### ISSUE TITLE
[HOLD for payment 2024-06-20] Send invoice - Invoice chat still appears in member list when workspace is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43361]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has at least two workspaces
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount, select a user & workspace and send the invoice
4. Delete the workspace in Step 3
5. Go to FAB > Send invoice
6. Enter invoice > Next

## Expected Result:
The invoice chat for the deleted workspace will not appear in the list

## Actual Result:
The invoice chat for the deleted workspace appears in the list, which leads to not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/95ff22ff-921d-4736-bbec-6d8e2e2dc608

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills

**Comment by rlinoz** [comment]
The original PR is here https://github.com/Expensify/App/pull/42714, we should be we should be filtering out archived rooms:

https://github.com/Expensify/App/pull/42714/files#diff-7d43f3c3e4decdb0057928e895f456d51c0f4081837edd5e2c4ed7ddd570e274R1950

cc: @cristipaval @rezkiy37 @jayeshmangwani

**Comment by rlinoz** [comment]
Not a blocker from Web-E, so removed the label.

**Comment by rlinoz** [comment]
Also, some discussion happened [here in slack](https://expensify.slack.com/archives/CSL3XBCCR/p1718025897788849)

**Comment by rlinoz** [comment]
I don't think this needs to be a blocker though, so demoting.

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by jayeshmangwani** [comment]
@rezkiy37 [PR](https://github.com/Expensify/App/pull/43406) has already been raised by @rlinoz. You can take a look at that PR.

**Comment by rezkiy37** [comment]
@jayeshmangwani, I see. However, I would like to improve the newly added condition instead of [ReportUtils.isArchivedRoom()](https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/libs/ReportUtils.ts#L1228) and [ReportUtils.isClosedReport()](https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/libs/ReportUtils.ts#L1239) instead of `report.isArchivedRoom`. I think it is safer and better.

cc @rlinoz

**Comment by jayeshmangwani** [comment]
The other PR was merged an hour ago.
@cristipaval @rlinoz Whats your thought for this [comment](https://github.com/Expensify/App/issues/43361#issuecomment-2160539320) of improving the isArchivedRoom condition?

**Comment by rlinoz** [comment]
I think that if we don't trust the `isArchivedRoom`  property for some reason we should talk about either fixing it or removing it entirely, unless that is just not trustworthy in some cases?

**Comment by rezkiy37** [comment]
An invoice room is a report. I have a concern because [types/onyx/Report.ts](https://github.com/Expensify/App/blob/main/src/types/onyx/Report.ts) does not include this property - `isArchivedRoom`.

**Comment by rlinoz** [comment]
Huum, I was looking into this and if I understand it correctly we use the `ReportUtils.isArchivedRoom` function when creating the option https://github.com/Expensify/App/blob/f701c3e0302b3e1eadf7767433277fea9eac0d6e/src/libs/OptionsListUtils.ts#L724

So we should be good?

**Comment by rezkiy37** [comment]
Ah, I see. Looks good to me 🙂

**Comment by rlinoz** [comment]
No payment due, closing.
