### ISSUE TITLE
[$250] IOU - An expense report opens with minimal details when clicking on a combined IOU

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://42772.pr-testing.expensify.com/

2. Admin: Log in as a new expensifail account
3. Admin: Create a workspace
4. Admin: Invite a Gmail member
5. Member: Submit two Scan IOUs with different, valid receipts to the workspace chat
6. Member: Submit two more after the previous ones finished scanning
7. Admin: Open the workspace chat with the member
8. Admin: Click on the combined IOU

## Expected Result:
Clicking on the combined IOU should take me to the combined IOU report where I can select individual IOUs.

## Actual Result:
Can't open individual scan IOUs in a combined report. An expense report opens with minimal details. It's only affecting the admin, it works on the members side.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/00577f4b-e856-4f50-8458-54cc74351fe4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e4df31bb9c6257f</li>
        <li>Upwork Job ID: 1800418823672771128</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by m-natarajan** [comment]
@VictoriaExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors


We think that this bug might be related to #wave-collect - Release 1

**Comment by VictoriaExpensify** [comment]
Thanks @m-natarajan!  I agree this seems like a bug and it is probably best suited to Wave-Collect.

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by VictoriaExpensify** [comment]
Still waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by ahmedGaber93** [comment]
Waiting on proposals

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by ahmedGaber93** [comment]
I think we can close this as it is not reproducible

**Comment by VictoriaExpensify** [comment]
This issue is no longer reproducable. Closing
