### ISSUE TITLE
iOS Deploy is failing

### ISSUE THREAD

**Issue by Jag96** [Expensify/App#4337]
## Problem
The `Build and Deploy iOS` workflow is failing with the following error:
```
❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.28_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.28)' for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This failed for the following runs so far:
- https://github.com/Expensify/App/runs/3205175704
- https://github.com/Expensify/App/runs/3205382335

Internal Slack link: https://expensify.slack.com/archives/C03V9A4TB/p1627675747007800

cc @Expensify/mobile-deployers

**Comment by Jag96** [comment]
Looks like this is related to Xcode versions: https://stackoverflow.com/questions/63802570/invalid-bitcode-version-for-archiving-ios-app, version info is here: https://trac.macports.org/wiki/XcodeVersionInfo

**Comment by AndrewGable** [comment]
What version of XCode are we on now?

**Comment by Jag96** [comment]
Looks like 12.3: https://github.com/Expensify/App/blob/a1b717aeaa073af27335e5104246b0ff6bc018c5/.github/workflows/platformDeploy.yml#L13

Going to bump that and the other usage, rebuild, and see if I can archive without errors

**Comment by AndrewGable** [comment]
Weird that e2e is passing 🤔 

https://github.com/Expensify/App/actions/runs/1083497070/workflow#L8-L9

**Comment by Jag96** [comment]
So I _think_ that'll pass fine since the fastlane linker command isn't called there

**Comment by Jag96** [comment]
Ongoing notes/discussion on the PR linked above ^

**Comment by Jag96** [comment]
The fix worked! https://github.com/Expensify/App/runs/3223732358?check_suite_focus=true
