### ISSUE TITLE
[HOLD for payment 2024-06-28] Default line height is 21 instead of 20

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#43371]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.81-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** @shawnborton @Expensify/design 
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @shawnborton 
**Slack conversation:** [Link](https://expensify.slack.com/archives/C04878MDF34/p1718022848778229)

## Action Performed:
View any default font size in the app

## Expected Result:
The default line height should be 20

## Actual Result:
The default line height is 21. This is caused by a commit introduced [here](https://github.com/bernhardoj/Expensify/commit/aa708ef0037718b4db8c677e77507468a11ec7f7) by @j-piasecki 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by shawnborton** [comment]
Also just noting that we do not want to accept external proposals for this, as @j-piasecki plans to create a fix for this.

**Comment by jliexpensify** [comment]
@j-piasecki hello, do you mind commenting on this issue so I can assign you? Cheers.

**Comment by j-piasecki** [comment]
@jliexpensify Ah, sorry for the delay, I didn't see the notification

**Comment by j-piasecki** [comment]
Update: The problem with emojis being cut off from the top looks to be somewhat related to the font being used - it's broken when using Expensify Neue and Arial but looks ok when using Segoe. I've found that on the new arch, the baseline is moved by [this code fragment](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L342-L344). After removing it, the emojis are displayed whole.

I'm a bit confused as the exact same code [exists on the old architecture](https://github.com/facebook/react-native/blob/18be49e7bbd3e52637b589705c6314d38d02b3cd/packages/react-native/Libraries/Text/Text/RCTTextShadowView.mm#L165-L167). I'll try to figure out what's causing the difference in behavior tomorrow.

**Comment by shawnborton** [comment]
Amazing, thanks for doing that!

**Comment by mananjadhav** [comment]
@jliexpensify Can you assign me this issue. I helped with the PR review on this one.

**Comment by jliexpensify** [comment]
Guessing this is the payment summary?

- C+: @mananjadhav $250 (ND payment)

Any checklist needed?

**Comment by mananjadhav** [comment]
That's all @jliexpensify. There's no checklist / regression test needed here. I am going to use the previous comment for the payment summary.

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by jliexpensify** [comment]
Great, thanks! Closing this out.
