### ISSUE TITLE
[Search v1] Search - "Nothing to show" label is missing if you create an empty report in OD

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43389]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #43192 
**Version Number:** 1.4.81-1
**Reproducible in staging?:** y
**Reproducible in production?:** no , new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. ND: Log in with a new expensifail account
3. ND: Create a workspace
4. Navigate to https://staging.expensify.com/

5. OD: Log in with the same expensifail account
6. OD: Create an empty report
7. ND: Navigate to Search - Shared

## Expected Result:
The label should be visible.

## Actual Result:
"Nothing to show" label is missing if you create an empty report in OD. It's visible in all of the other tabs under Search.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/b17b9f59-e2c9-4a1d-ac4a-87140012b825

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@yuwenmemon FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment]
In this case we're still returning the empty report to App. Confirming if we want to display the empty report or the empty state component
![Screenshot 2024-06-10 at 10 40 27 AM](https://github.com/Expensify/App/assets/22219519/b7a18009-43e8-4cfb-a70e-ce8606534cd5)

**Comment by luacmartins** [comment]
This should be fixed. Closing.
