### ISSUE TITLE
[Search v1] Expenses moved to a new report are not updated on Search page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#43382]
Coming from [this comment](https://expensify.slack.com/archives/C036QM0SLJK/p1718031217651339?thread_ts=1718018655.610629&cid=C036QM0SLJK). Actions taken:

1. Moved a card transaction from one report to the next on OldDot
2. Hard refreshed the Search page. Also toggled between a couple different filters
3. The expense that is no longer on a report still appears on that report.

This seems to happen because we're sending updates via Onyx.merge, which won't remove data once it's set in Onyx (unless we explicitly send `undefined`).

Additionally, any data being removed will also not be removed from the Search page.

**Comment by muttmuure** [comment]
Not overdue

**Comment by luacmartins** [comment]
I suspect this will be solved by https://github.com/Expensify/react-native-onyx/pull/552

**Comment by luacmartins** [comment]
We merged the Onyx PR today, gonna wait until that's deployed to prod to see if the issue is fixed. Maybe the fact that we disabled Onyx updates from OldDot means that the live update PR will not fix this 🤔

**Comment by luacmartins** [comment]
This is not live updating since we removed the Onyx updates from OldDot, but I do see the expenses updating to the new report after a hard refresh of the page. @JmillsExpensify can you still reproduce this one?

**Comment by luacmartins** [comment]
https://github.com/Expensify/App/assets/22219519/12b02794-956f-4cfd-a1df-c0983a2732fe

**Comment by muttmuure** [comment]
I think this is resolved
