### ISSUE TITLE
[$250] Account settings - Left hand pane scrolls up when opening tab from the bottom

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings (make sure the current tab is Profile, or else refresh the page and go to Account settings)
3. Scroll down
4. Click Troubleshoot

## Expected Result:
The left hand pane will not scroll back up

## Actual Result:
The left hand pane scrolls back up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e3f43503-1b66-4c16-96b9-96e16dfcf691

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013bad1327b70b0b29</li>
        <li>Upwork Job ID: 1800965843804473661</li>
        <li>Last Price Increase: 2024-06-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by abekkala** [comment]
@jjcoffee can you take a look at the proposal above?

**Comment by jjcoffee** [comment]
@abekkala I can't replicate on latest staging. Can you replicate it, or should we ask for a retest?

**Comment by bernhardoj** [comment]
This is fixed in https://github.com/Expensify/App/pull/43500
