### ISSUE TITLE
Search - Unable to sort expenses by "Type", and "Receipt"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43388]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43206
## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an account that has a few expenses
3. Open Search
4. Sort by "Type", and "Receipt"

## Expected Result:
I should be able to sort the columns

## Actual Result:
Unable to sort expenses by "Type", and "Receipt"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/daefcaef-463e-4c8d-afdb-a2b2b3d1f64e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jasperhuangg  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Kicu** [comment]
Sorting by these 2 columns was explicitly disabled by us. When I implemented sorting @luacmartins said that for now we are not able to support sorting by these values.

I leave it to others to verify if this should be treated as a bug or something to keep for now.

**Comment by luacmartins** [comment]
Correct, this is not available yet. Closing.
