### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Android - Chat - Emoji with markdown on edit cut off on top

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43394]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4613726
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter _☺_
4. Send the message
5. Long press and tap edit comment
6. Enter _😄😃_
7. Save it

## Expected Result:
Emoji with markdown on edit must not cut off on top

## Actual Result:
Emoji with markdown on edit cut off on top

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4476b30d-d034-41f1-80d5-5a674bd0f61d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3f0154fe463e8cd</li>
        <li>Upwork Job ID: 1800920165195401508</li>
        <li>Last Price Increase: 2024-06-12</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102710191</li>
<li>bernhardoj | Contributor | 102710194</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by akinwale** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/43394#issuecomment-2160067002) makes sense here.

> Or I think the better way is to set a font size for the empty space to be the same as the (edited) text

Let's go with this approach.

🎀👀🎀 C+ reviewed.

**Comment by bernhardoj** [comment]
PR is ready

cc: @akinwale

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @akinwale $250, paid via Upwork
Contributor+: @bernhardoj $250, paid via Upwork


@akinwale could you please complete the BZ checklist?

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify.
2. Open any report.
3. Send a message with only emoji (😄).
4. Edit the previously sent message and wrap the emoji in markdown, eg italics (_😄_).
5. Verify that the emoji is not cut off at the top.

Do we agree 👍 or 👎?

**Comment by sakluger** [comment]
Thanks! I created the GH issue to update regression test steps.
