### ISSUE TITLE
Chat -  No "Rechecking network connection" server log when simulaton offline connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43398]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43090
## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an account
3. Open Chrome network tab
4. Simulate "Offline" with the throttle option

## Expected Result:
There should be a "Rechecking network connection" server log appearing every 60s

## Actual Result:
No "Rechecking network connection" server log when simulaton offline connection. I can only see a "(failed)net::ERR_INTERNET_DISCONNECTED" log entry that appears often

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/83687b1f-ec24-4bff-b5b1-f16d072d9245

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment]
I'm not sure this is worth solving right now, closing
