### ISSUE TITLE
Room - When clicking "Start Chat" in Safari, a room name error is displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43391]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41199
## Action Performed:
1. Click on FAB > Start chat > Room
2. Close the Right Hand Pane (RHP) and again click on FAB > Start chat

## Expected Result:
Error should not displayed when clicking on start chat in safari

## Actual Result:
When clicking "Start Chat" in Safari, a room name error is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4221c26c-7d44-4631-9c34-2e0f7d6d4d82

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment]
Was able to reproduce in Safari and **not** on Desktop. 
Added this to [[Tracking] Safari-only bugs in NewDot](https://github.com/Expensify/App/issues/23088#top)
Going to close for now, with the hope that we holistically address safari-only bugs at some point in the future.
