### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [Search v1] Implement mobile specific loading skeleton

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#43395]
Coming from [this comment](https://expensify.slack.com/archives/C049HHMV9SM/p1718033548241659?thread_ts=1718032675.442129&cid=C049HHMV9SM), we should implement a small screen specific loading skeleton for the Search page:

![CleanShot 2024-06-10 at 19 27 19@2x](https://github.com/Expensify/App/assets/2319350/723cef12-b0d8-471a-bda5-365e78923158)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0173dda4c7482d049f</li>
        <li>Upwork Job ID: 1800568455133984908</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102704758</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by shawnborton** [comment]
Added a screenshot to the original comment, cc @Expensify/design for vis

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
- New feature
### What changes do you think we should make in order to solve the problem?
- We already have a logic to display the skeleton:
https://github.com/Expensify/App/blob/1d7ed051629b9f0dd593e8337578689bb65e14fb/src/components/Search.tsx#L72-L74
but it does not match the design.
- We should create a new ```TableListItemSkeletonSmallScreen``` that matches the design, to display in case of mobile device.
- Then update:
https://github.com/Expensify/App/blob/1d7ed051629b9f0dd593e8337578689bb65e14fb/src/components/Search.tsx#L72-L74
to:
```
    if (isLoadingItems) {
        return isSmallScreenWidth <TableListItemSkeletonSmallScreen TableListItemSkeletonSmallScreen /> ?  <TableListItemSkeleton shouldAnimate />;
    }
```

### What alternative solutions did you explore? (Optional)

**Comment by akinwale** [comment]
@truph01 Could you share a video of your solution?

**Comment by truph01** [comment]
@akinwale I added the video. The details about height, width, and color should be defined when implementing PR.

**Comment by akinwale** [comment]
@truph01's [proposal](https://github.com/Expensify/App/issues/43395#issuecomment-2161427175) works here.

🎀👀🎀 C+ reviewed.

**Comment by truph01** [comment]
PR https://github.com/Expensify/App/pull/43652 is ready to review

**Comment by shawnborton** [comment]
Nice! Will review today, thanks.

**Comment by zanyrenney** [comment]
@akinwale please propose/check off regression test before i can proceed with payment.

**Comment by akinwale** [comment]
> * [x]  [@akinwale] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure  the new feature will work correctly on production in further releases.

**Regression Test Steps**
1. Launch Expensify
2. Navigate to the expense search page (`/search/all?sortBy=date&sortOrder=desc`).
3. While the data is loading, verify that the skeleton is displayed similar to the design.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@zanyrenney Done.

**Comment by luacmartins** [comment]
I think we can skip the tests for now. We'll add those as part of the project wrap up.

**Comment by luacmartins** [comment]
Just missing payment here

**Comment by zanyrenney** [comment]
@akinwale requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102704758) (Reviewer) - paid $250

@truph01 requires payment (Needs manual offer from BZ) - can't see your upwork profile / name for payout. please can you confirm it here?

**Comment by truph01** [comment]
@zanyrenney Sure here's my Upwork link https://www.upwork.com/freelancers/~01c880ca813fdd85ec

**Comment by zanyrenney** [comment]
hey thanks @truph01 - i have sent you a new offeR: https://www.upwork.com/nx/wm/offer/103170834

**Comment by truph01** [comment]
@zanyrenney Accepted!

**Comment by zanyrenney** [comment]
full payment summary

@akinwale requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102704758) (Reviewer) - paid $250 via upwork

@truph01 requires payment (Needs manual offer from BZ) -  paid $250 via upwork
