### ISSUE TITLE
[HybridApp] White screen with no UI

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#43400]
## Problem
@cead22 experienced a white screen where NewDot UI did not load on a fresh install.

1. Fresh install HybridApp
2. Log in with an account that is set to show NewDot UI
3. No UI is shown until app is killed

https://github.com/Expensify/App/assets/2838819/d12f142c-9c43-4bf6-81e2-aa99d0c631c2

## Solution
Fix it!

cc @staszekscp @mateuuszzzzz

**Comment by staszekscp** [comment]
The PR to fix this issue is [here](https://github.com/Expensify/Mobile-Expensify/pull/12733)
