### ISSUE TITLE
Public room - Unable to see deleted messages and reactions in real time with anon user in public room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43402]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4599840
**Issue reported by:** Applause - Internal Team

## Action Performed:
Setup - Secondary device
1. In a incognito tab - Login and navigate to this link https://staging.new.expensify.com/r/2652281908731856
Steps
2. Log out of New Expensify
3. Navigate to this link as anon user- https://staging.new.expensify.com/r/2652281908731856
4. Keep view in the conversation in the main testing device
5. As the secondary user - Send some messages in the public room
6. As the secondary user - Delete a message
7. As the secondary user - React to a message

## Expected Result:
Do not view user deleted messages and view user generated reactions in my room

## Actual Result:
I can see messages that have been deleted as they are not deleted from my room and I cannot see user reactions in my room in real time. More than 15 minutes have passed and is not updated
New messages and a thread response were sent from the secondary user after delete some messages and I can see these updates

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

![df8](https://github.com/Expensify/App/assets/78819774/33a83e9b-6bfc-4feb-a437-3e1910c13a56)

![0b3](https://github.com/Expensify/App/assets/78819774/d0b62787-4698-4022-9ad1-8a043827f244)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
I think this probably is worth looking at in the long term, but public rooms are not in scope for any of our current VIPs or Waves. With that in mind I am gonna close.
