### ISSUE TITLE
[$250] Login – Black page opens for a moment when navigate via magic code link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43408]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4609134 
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open login screen
3. Enter email
4. Open link from email in another tab and change to staging

## Expected Result:
Abracadabra page opens

## Actual Result:
Black page opens for a moment before Abracadabra page appears when navigate via magic code link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dfcaeb2b-bb4b-4dae-9c31-9fbf74fccb32

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b08bc05f18f16878</li>
        <li>Upwork Job ID: 1800535763514083527</li>
        <li>Last Price Increase: 2024-07-02</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment]
Looks like we've had [something similar here](https://github.com/Expensify/App/issues/35906) so maybe we can make a similar fix, or expand the scope to cover the blank page across all instances

**Comment by rushatgabhane** [comment]
waiting for proposals

**Comment by sonialiap** [comment]
Looking for proposals

**Comment by rushatgabhane** [comment]
waiting for proposals

**Comment by sonialiap** [comment]
looking for proposals, posted in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1719926653710529)

**Comment by sonialiap** [comment]
I think https://github.com/Expensify/App/issues/35906 might have fixed this because I cannot reproduce
