### ISSUE TITLE
[$125] [Search v1] Receipt thumbnail background doesn't change back to correct color after hover

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#43412]
Coming from [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1718041249353349), the hover styles are not being applied when the mouse exists the row item.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014338cee918b85ec5</li>
        <li>Upwork Job ID: 1800226670096480396</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by eh2077** [comment]
@luacmartins I think this has been fixed in https://github.com/Expensify/App/pull/43424 right?

**Comment by luacmartins** [comment]
Yes, it was. Closing!

**Comment by luacmartins** [comment]
Do you have an example of an existing issue?
