### ISSUE TITLE
Violations for report fields

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#43414]
We discovered that violations were never implemented for report fields, so we need to close that gap since report field violations were part of the design cc @thienlnam @allroundexperts. Let's use this issue to align on next steps. We need this in place for the August release, since these are common for NetSuite and Intacct integraitons.

**Comment by JmillsExpensify** [comment]
Here's the relevant context from the HL doc. 

![CleanShot 2024-06-10 at 12 01 58@2x](https://github.com/Expensify/App/assets/1127863/7c7e38bb-1ca4-411d-b60b-8a5fb996e9c9)

**Comment by thienlnam** [comment]
Project has been split into implementation issues
https://expensify.slack.com/archives/C06ML6X0W9L/p1718668782907229?thread_ts=1718663647.887519&cid=C06ML6X0W9L

**Comment by slafortune** [comment]
Looks good - I'll close this 👍
