### ISSUE TITLE
[Search v1] Breadcrumbs text overflows for Search page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#43426]
Coming from [this comment](https://expensify.slack.com/archives/C036QM0SLJK/p1718047775259319?thread_ts=1718018655.610629&cid=C036QM0SLJK), the breadcrumbs text overflows for the Spanish copy of the Search page

**Comment by joekaufmanexpensify** [comment]
@luacmartins should I make this external, or are you planning to take this one?

**Comment by luacmartins** [comment]
@joekaufmanexpensify I have a fix up already

**Comment by joekaufmanexpensify** [comment]
🫡

**Comment by luacmartins** [comment]
Fixed on staging. Closing.

**Comment by joekaufmanexpensify** [comment]
TY!
