### ISSUE TITLE
Chat – Chat is scrolled up when go back from the thread twice via header link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43421]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat with a history and send a message
4. Create a thread and send a message in thread
5. Navigate to the chat via header link
6. Click on reply link to open thread again
7. Navigate to the chat via header link again

## Expected Result:
Last message with a thread is visible

## Actual Result:
Chat is scrolled up and last message with a thread is not visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eafb2274-7cc2-4145-be0c-b3431aebc0ac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by alexpensify** [comment]
I'll add this to my review list and get to it soon.

**Comment by alexpensify** [comment]
No update yet, I'm still reviewing this one.

**Comment by alexpensify** [comment]
I'm going to test more tomorrow.

**Comment by alexpensify** [comment]
Looks like the PR fixed the issue, I'm going to close since I can't replicate this experience again: 

![2024-06-18_11-30-09](https://github.com/Expensify/App/assets/8107070/a44e6b41-a10c-4b5c-8432-4160695f8596)
