### ISSUE TITLE
Cash · Duplicate · Hold doesn't appeared for duplicates expenses

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43428]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** rybkina+061024a@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40153
## Action Performed:
Precondition:
- The Collect workspace has Expenses >> Expense Violations enabled
1. Log in with Collect workspace's member account
2. Create 2 expenses with same AMOUNT, CURRENCY, MERCHANT and DATE to the Collect workspace
3. Go to the transaction report
4. Go to the policy expense report

## Expected Result:
Verify in the policy expense report, the report preview has a red dot indicator
Verify each expense preview has a red dot indicator and Cash · Duplicate · Hold on top
Verify the HOLD banner is added with the following copy This expense has the same details as another one. Review the duplicates to remove the hold

## Actual Result:
Hold doesn't appeared for duplicates expenses

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9bab7abf-a8dc-4358-aaa9-3f6ebff5927a

https://github.com/Expensify/App/assets/78819774/2397830b-42f2-4c91-a948-3d29fa995fd3

<img width="413" alt="05 27" src="https://github.com/Expensify/App/assets/78819774/6cbe61ff-e4d2-46c4-9d01-d49cbce9f4c6">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment]
Okay is this the result of an actual bug or missing beta functionality?

**Comment by pecanoro** [comment]
@lanitochka17 Do you know if the tester was added to the beta? If not, I suggest testing with a `applause.expensifail.com` email since that domain should have all betas enabled

**Comment by akinwale** [comment]
@pecanoro Also, a reminder that while we were testing, we had to use a Control workspace since the `Expense Violations` switch for Collect workspaces wasn't working as expected.

**Comment by greg-schroeder** [comment]
Bump @lanitochka17 on https://github.com/Expensify/App/issues/43428#issuecomment-2160932709

**Comment by greg-schroeder** [comment]
Bump @lanitochka17 <3

**Comment by pecanoro** [comment]
This is under a new beta so I don't think anyone can see it unless they gets added

**Comment by lanitochka17** [comment]
Issue isn't reproducible with expensifail account 

https://github.com/Expensify/App/assets/78819774/c7d3b28c-d3d4-49b3-a97a-ac4e260e57ce

**Comment by greg-schroeder** [comment]
Closing for now as I think it was a not-being-on-the-beta issue
