### ISSUE TITLE
`Open report` is called after the report is approved

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43432]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718048918572609

## Action Performed:
1. Submit a report to a workspace chat
2. As an approver approve the report and wait until it gets completed
3. Check the API calls
## Expected Result:
 ApproveMoneyRequest API > GetMissingOnyxUpdates >ReadNewestAction only should be called
## Actual Result:
 ApproveMoneyRequest API > GetMissingOnyxUpdates >ReadNewestAction  then `OpenReport` is called eventhough not navigated away
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/5aefc812-c3ea-420c-bb5e-2f320268d2cb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Posted here: https://expensify.slack.com/archives/C05LX9D6E07/p1718084444328599?thread_ts=1718033923.840189&cid=C05LX9D6E07

**Comment by carlosmiceli** [comment]
Haven't been able to reproduce, will try with @puneetlath live later this week.

**Comment by carlosmiceli** [comment]
Still being tested.

**Comment by puneetlath** [comment]
I tried approving a few different reports today and I'm no longer seeing this, so I think we can go ahead and close this out. Thanks for looking into it @carlosmiceli
