### ISSUE TITLE
[HOLD for payment 2024-07-10] [#Wave-Control: Add NetSuite] Settings Configuration in NewDot: Top-Level Subsidiary Selector

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#43435]
Tracking Issue: https://github.com/Expensify/Expensify/issues/377671

Design Doc Section: https://docs.google.com/document/d/1WubNv_VAv78IxG4FKsi9aS0pWESfWvUYbqBAAy5b4bc/edit#heading=h.ursdzd4yhqi0

---

([High-Level Section](https://docs.google.com/document/d/1WubNv_VAv78IxG4FKsi9aS0pWESfWvUYbqBAAy5b4bc/edit#heading=h.12ncvrmo0icg))

### Route

- Route: `/settings/workspaces/{policyID}/accounting/netsuite/subsidiary`
- PageComponent: `NetSuiteSubsidiarySelector`
- Calls `UpdateNetSuiteSubsidiary`
    - `subsidiaryName`: name of the selected subsidiary from `options.data.subsidiaryList` array.
    - The pendingAction for the OfflineWithFeedback component will be `policy.pendingFields.subsidiary`

---

![AD_4nXcY-wNB2ht40Cb61Cn42fRiPYRnM-dx6O8_P5Qvr00KKpFEnPQ2My0nMzymympXv3tKR1IXeS0G8H6X9hhW1pIR6KNWXBvtpe75f-DI_gg2aSVlYy-58GY2](https://github.com/Expensify/App/assets/4741899/99171d92-5355-47f6-8d66-d4995bc56475)

We’ll have a NetSuiteSubsidiarySelectorPage, which will populate the list of subsidiaries from the `data.subsidiaryList`. The sample data shows the list of subsidiaries [here](https://docs.google.com/document/d/1WubNv_VAv78IxG4FKsi9aS0pWESfWvUYbqBAAy5b4bc/edit#heading=h.8aibixbdi0w0).

The basic code for the page will look as follows:
```JS
function NetSuiteNetSuiteSubsidiarySelectorPage({policy}: WithPolicyConnectionsProps) {
    const policyID = policy?.id ?? '';

    const { subsidiary } = policy?.connections?.netsuite?.config ?? {};  
    const subsidiaryOptions = useMemo<SelectorType[]>(() => {
        const subsidiaryList = policy?.connections?.netsuite?.options?.data.subsidiaryList ?? {} ?? [];
        const isMatchFound = subsidiaryList?.some(({subsidiaryObj}) => subsidiaryObj === subsidiary); // toLowerCase() ?

        return (subsidiaryList ?? []).map(({id, name}, index) => ({
            value: name,
            text: name,
            keyForList: id,
            isSelected: isMatchFound ? subsidiary === id : index === 0,
        }));
    });

    const listHeaderComponent = useMemo( // Move this to another file as a standalone component.
        () => (
            <View style={[styles.pb2, styles.ph5]}>
                <Text style={[styles.pb5, styles.textNormal]}>{translate('workspace.netsuite.subsidiary.description')}</Text>
            </View>
        ),
        [translate, styles.pb2, styles.ph5, styles.pb5, styles.textNormal],
    );

    const initiallyFocusedOptionKey = useMemo(() => subsidiaryList?.find((subsidiary) => subsidiary.isSelected)?.keyForList, [subsidiaryOptions]);

    const updateSubsidiary = useCallback(
        ({value}: SelectorType) => {
            Connections.updateNetSuiteSubsidiary(policyID, CONST.POLICY.CONNECTIONS.NAME.NET_SUITE, CONST.NET_SUITE_CONFIG, {
                subsidiary: value,
                subsidiaryID: //
            });
            Navigation.goBack(ROUTES.POLICY_ACCOUNTING.getRoute(policyID));
        },
        [policyID],
    );

    return (
        <SelectionScreen
            policyID={policyID}
            accessVariants={[CONST.POLICY.ACCESS_VARIANTS.ADMIN, CONST.POLICY.ACCESS_VARIANTS.PAID]}
            featureName={CONST.POLICY.MORE_FEATURES.ARE_CONNECTIONS_ENABLED}
            displayName={NetSuiteNetSuiteSubsidiarySelectorPage.displayName}
            sections={[{data: subsidiaryOptions}]}
            listItem={RadioListItem}
            onSelectRow={updateSubsidiary}
            initiallyFocusedOptionKey={initiallyFocusedOptionKey}
            headerContent={listHeaderComponent}
            onBackButtonPress={() => Navigation.goBack(ROUTES.POLICY_ACCOUNTING.getRoute(policyID))}
            title="workspace.netsuite.subsidiary.title"
        />
    );
}

NetSuiteNetSuiteSubsidiarySelectorPage.displayName = 'NetSuiteNetSuiteSubsidiarySelectorPage';

export default withPolicyConnections(NetSuiteNetSuiteSubsidiarySelectorPage);
```

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d62f33ad0e1e9fe6</li>
        <li>Upwork Job ID: 1800281430610989476</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by yuwenmemon** [comment]
Sample NetSuite connection data JSON:
[sampleNetSuiteJSON.json](https://github.com/user-attachments/files/15783370/sampleNetSuiteJSON.json)

This would go under `connections.netsuite` in your policy object in Onyx, just like for `quickbooksOnline`

**Comment by mananjadhav** [comment]
Starting with this issue first. I'll have the first PR ready by weekend. Might be away on Friday.

**Comment by yuwenmemon** [comment]
Great! I'll try to prioritize getting the subsidiary selection API out for you in a separate PR then.

**Comment by JmillsExpensify** [comment]
@mananjadhav has been sick but we'll be coming back to this one soon.

**Comment by mananjadhav** [comment]
@yuwenmemon I'll need:

1. To confirm if the API is ready?
2. Can you share the Netsuite Icon?
3. Spanish translation for `Subsidiary` and `Choose the subsidiary in NetSuite that you\'d like to import data from.`

**Comment by mananjadhav** [comment]
Demo video of the list:

https://github.com/Expensify/App/assets/3069065/17b2d985-7174-4cc3-9e45-14663e22162b

**Comment by yuwenmemon** [comment]
> To confirm if the API is ready?

The API to select a subsidiary is live as of an hour ago!
```PHP
    } elseif ($command === 'UpdateNetSuiteSubsidiary') {
        NetSuite::updateSubsidiary($authToken, $policyID, $_REQUEST['subsidiary'] ?? '');
```

**Comment by yuwenmemon** [comment]
> Can you share the Netsuite Icon?

Asking this for you here: https://expensify.slack.com/archives/C06ML6X0W9L/p1718836882604659

**Comment by yuwenmemon** [comment]
> Spanish translation for Subsidiary and Choose the subsidiary in NetSuite that you\'d like to import data from.

Asking this for you here: https://expensify.slack.com/archives/C21FRDWCV/p1718837580539369

**Comment by yuwenmemon** [comment]
> Name of the beta behind which the Netsuite should be. Because during active development we don't want to show NetSuite right?

Asked this for you here: https://expensify.slack.com/archives/C06ML6X0W9L/p1718837727812639

**Comment by yuwenmemon** [comment]
Spanish:
`Subsidiaria`
`Elige la subsidiaria de NetSuite de la que deseas importar datos`

**Comment by mananjadhav** [comment]
Payout for this will be centrally paid, no further action here.
