### ISSUE TITLE
OS - Chat - Images taken in HEIC with the device are not displayed on chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43441]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: go to iPhone Settings > Camera > Formats, select "High Efficiency" and take a photo with the camera app.

1. Go to any chat.
2. Tap on the "+" menu and select "Add attachment".
3. Select "Choose from gallery" and send the photo that was taken with the device.
4. Verify that after "Uploading attachment..." message, a loading spinner appears.
5. Verify the photo is not displayed on the chat.

## Expected Result:
The images should be displayed on chat after being sent.

## Actual Result:
The images are not displayed on chat after being sent.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/d9b30913-8fd9-45d4-8114-bb29943fd93b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@thienlnam FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by thienlnam** [comment]
I can upload .heic files on web - so this seems to be isolated to native client. This looks slightly suspicious https://github.com/Expensify/App/pull/42739

**Comment by thienlnam** [comment]
Confirmed that the revert of that PR in https://github.com/Expensify/App/pull/43447 fixes the iOS heic upload issue

**Comment by thienlnam** [comment]
PR is getting CPed - should be good now
