### ISSUE TITLE
Account - Welcome message not displayed when Sign Up with Expensifail domain

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43468]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4611060&group_by=cases:section_id&group_order=asc&group_id=229043
**Email or phone of affected tester (no customers):** applausetester+omq505@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: user should be Signed Out
1. Open app
2. Write any email with public domain that has not been used for registration before
3. Click on Continue button
4. Observe Welcome message
5. Click on "Go back"
6. Write any email with Expensifail domain that has not been used for registration before
7. Click on Continue button
8. Observe Welcome message

## Expected Result:
The message "It's always great to see a new face around here!" should be displayed when a new user signs up regardless of the email domain used.

## Actual Result:
The message "It's always great to see a new face around here!" is displayed when signing up with a public domain (step 4), but it is not displayed when signing up with the Expensifail domain (step 8).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9edfca5f-f32c-489c-b95c-88e272ce7018

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I think this is expected. We have [this comment](https://github.com/Expensify/App/blob/6b6937338c39e4a29a28c34081fdbade4a4ebf83/src/pages/signin/SignInPage.tsx#L115) saying that we only show this welcome message for new accounts on **uncontrolled** domains. Since `expensifail.com` is domain controlled, we wouldn't see the message. 

Closing this issue.
