### ISSUE TITLE
[$250] Chat – New green line disappears when open chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43469]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a204@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. In the main testing device (as account A) navigate away from the conversation with account B.
2. As account B send some messages to Account A
3. As account A enter the conversation

## Expected Result:
There should be a green line indicating the New Messages

## Actual Result:
When user navigate to unread message chat new green line disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d87d2b21-6664-4d41-8d05-791ae1b02fb4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01737616cb3d6389c3</li>
        <li>Upwork Job ID: 1801382637392349501</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue
Chat – New green line disappears when open chat

## What is the root cause of that problem?
UnreadActionIndicator disappears instantly on Android because the updateUnread function on Android https://github.com/Expensify/App/blob/9912ae84c841672ee0f4ec921ad5dfc649cfa856/src/libs/UnreadIndicatorUpdater/updateUnread/index.android.ts#L4C1-L4C45 is not counting any Unread message, thus the effect on Unread Message is not implemented.

## What changes do you think we should make in order to solve the problem?
Use UnreadIndicatorUpdater function on updateUnread Android so it'll update it automatically
```
import type UpdateUnread from './types';
import UnreadIndicatorUpdater from '../UnreadIndicatorUpdater';

const updateUnread: UpdateUnread = (unreadCount) => {
  UnreadIndicatorUpdater.setUnreadCount(unreadCount);
};

export default updateUnread;
``

## What alternative solutions did you explore? (Optional)
None

**Comment by MitchExpensify** [comment]
@alitoshmatov Does the proposal above look good to you?

**Comment by alitoshmatov** [comment]
@studentofcoding Thank you for your proposal, I think you are confusing the root cause, the code you provided is to update favicon, icons of the app to indicate unread messages not to show unread line in the chat

**Comment by alitoshmatov** [comment]
Waiting for proposals

**Comment by MitchExpensify** [comment]
Still waiting on proposals

**Comment by MitchExpensify** [comment]
Not overdue, Melvin

**Comment by alitoshmatov** [comment]
Waiting for proposals

**Comment by MitchExpensify** [comment]
Bumped for proposals here https://expensify.slack.com/archives/C01GTK53T8Q/p1719869034225129

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by MitchExpensify** [comment]
Is this reproducibe @mvtglobally? Please reopen if so, otherwise lets leave closed
