### ISSUE TITLE
[HOLD for payment 2024-06-20] [Search v1] - Skeleton appears under expenses when sorting expenses when there is no more expenses

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43476]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.81-8
**Reproducible in staging?:** Y
**Reproducible in production?:** New feature
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User has a few expenses (two expenses would be enough).

1. Go to staging.new.expensify.com
2. Go to Search.
3. Click on the header to sort.

## Expected Result:
Skeleton will not appear under the expenses since there is no hidden expenses.

## Actual Result:
Skeleton appears under the expenses when sorting expenses, even when there is no expense to load.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/249e176e-02bc-4518-86bd-c46b788bebd8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by izarutskaya** [comment]
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search - Skeleton appears under expenses when sorting expenses when there is no more expenses

### What is the root cause of that problem?

In here: 

https://github.com/Expensify/App/blob/6eea419b2da2e61a075037b5f2ad479575642004/src/components/Search.tsx#L69

IsLoadingMoreItems value doesn't check on offset of the search result.

### What changes do you think we should make in order to solve the problem?

We should add more check on that by adding && `searchResults?.search.offset > 0`

**Comment by luacmartins** [comment]
I don't think this is a blocker since the feature is not broken. I agree that we can check for the offset. @tsa321 are you available to work on the PR?

**Comment by tsa321** [comment]
Yes @luacmartins

**Comment by tsa321** [comment]
@luacmartins  The PR is ready

**Comment by JmillsExpensify** [comment]
I've filled out the payment summary above for @tsa321 for $250. It doesn't look like an Upwork job was created, so I created one. @tsa321 what's your Upwork profile so I can invite you?

**Comment by mollfpr** [comment]
Sorry forgot to comment here that I reviewed the PR.

**Comment by JmillsExpensify** [comment]
Thanks, I've confirmed that's correct. Payment summary is updated above.

**Comment by tsa321** [comment]
@JmillsExpensify my upwork profile: https://www.upwork.com/freelancers/~01bfc26d267bade652

**Comment by JmillsExpensify** [comment]
Offer sent

**Comment by tsa321** [comment]
@JmillsExpensify I have accepted the offer

**Comment by JmillsExpensify** [comment]
All paid out! @mollfpr please complete the checklist and request payment in NewDot!

**Comment by mollfpr** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
>The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't trace the original offending PR.

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Create 3 iou requests to any user
2. Open the transaction search page
3. Reorder the transaction list search result by clicking on the list header
4. **Verify** skeleton transaction items don't appear
5. 👍 or 👎

**Comment by mallenexpensify** [comment]
Contributor: @tsa321 paid $250 via Upwork
Contributor+: @mollfpr due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr

**Comment by JmillsExpensify** [comment]
Regression test created!
