### ISSUE TITLE
[Search v1] iOS -  Search - Composer is hidden behind keyboard when composer in transaction thread is focused

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43477]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-8
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to Search.
3. Tap on any expense.
4. Tap on the composer.

## Expected Result:
The transaction thread will scroll up and the composer will be revealed when the keyboard is up.

## Actual Result:
The transaction thread does not scroll up and the composer is hidden when the keyboard is up.
Composer is hidden behind keyboard when composer in transaction thread is focused

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/a51670c2-286e-4a26-85ab-e5327241c223

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
Got a PR up to fix this

**Comment by luacmartins** [comment]
This is fixed
