### ISSUE TITLE
Duplicates - Edited duplicate show "Review required" when there is no error or violation

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43487]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Bug was found when validating #40153
**Version Number:** 1.4.81-8
**Reproducible in staging?:** y
**Reproducible in production?:**  no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two scan expenses with the same receipt (so that they will be flagged as duplicate).
4. Wait for both scanning to complete.
5. Go to expense report (make sure both expenses have the "Duplicate" label)
6. Go to transaction thread of one of the expenses.
7. Change the amount so that both expenses are no longer duplicate.
8. Return to expense report.

## Expected Result:
The edited expense will not have "Review required" label, if there is no error message or violation in the transaction thread.

## Actual Result:
The edited expense shows "Review required" label, but there is no error message or violation in the transaction thread.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6509423_1718114254688!E_receipt_ (1)](https://github.com/Expensify/App/assets/38435837/e4d6c06d-7b52-4176-8989-83159caa6640)

https://github.com/Expensify/App/assets/38435837/82e9cc12-cbc7-4594-b9e0-6e4b03b6bf57

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by luacmartins** [comment]
I don't think we need to block the deploy on this, since clicking into the request shows no errors. I agree that it needs to be solved though. Maybe @cead22 has more context on this one.

**Comment by cead22** [comment]
@m-natarajan please always include the reportIDs/transactionIDs so we're not transcribing them from videos. It looks like the transactionID in the video is 4360400970679580180. Can you share the onyx data in the `transactionViolations_4360400970679580180` please, or for the other transaction showing RBR? 

cc @pecanoro since you know more about duplicates

**Comment by pecanoro** [comment]
This is totally expected. The violation is clearly stated in the `HOLD` section of the transaction; it says there is a violation that needs to be fixed. The `Review Duplicates` part is being implemented. This is all under a beta so it should be fine, closing!
