### ISSUE TITLE
[HOLD for payment 2024-07-05] [$250] [LOW] [Performance] Memoize the bottom tab component

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43491]
Coming from Slack [here](https://expensify.slack.com/archives/C05LX9D6E07/p1718096802275589)

### Problem
[BottomTabBar](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx) re-renders a few times because of the parent component. It takes pretty much a time to update around 60ms on each re-render.

### Solution
Use `React.memo` for the component to re-render only when necessary.
Before: 253ms (all rerenders, 5) / After: 105ms around 141% of improvement.
A commit is [here](https://github.com/rezkiy37/Expensify/commit/f4e3b128454ae763788478de44ea6345b7e6cd98). I am attaching screenshots with the legacy (the 1st) and updated (the 2nd) versions.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c88d87fb5aadb399</li>
        <li>Upwork Job ID: 1800546469089470578</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102689897</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by mountiny** [comment]
@rezkiy37 will handle it

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
I've opened a PR - https://github.com/Expensify/App/pull/43495.

**Comment by mountiny** [comment]
@jliexpensify this is ready for payment 

$250 to @akinwale 

No regression tests required

**Comment by jliexpensify** [comment]
Cheers Vit, paid and job closed.
