### ISSUE TITLE
[HOLD for payment 2024-07-02] [Search v1] Implement dynamic column logic server side

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#43494]
Implement this section of the [design doc](https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=kix.2ceasox5wdtw)

**Comment by JmillsExpensify** [comment]
Feel free to add me for payment if needed.

**Comment by luacmartins** [comment]
This is done and deployed.

**Comment by ikevin127** [comment]
@luacmartins When you get a change, can you please assign a BZ team member for payment here ? Thank you!

**Comment by Christinadobrzyn** [comment]
Prepping for payouts due:

- [ ] Contributor+: $250 @ikevin127 - are you paid in Upwork?

Even though this is internal, do we want a regression test for this?

**Comment by ikevin127** [comment]
@Christinadobrzyn Yes, I'm currently using Upwork for payments.

Not sure if regression test is needed here but here it is anyway:

### Regression Test Proposal

**Pre-requisite:**
- An account with a money request and no policy (workspace).

1. Open the new Search page.
2. Verify that you can see the money request and the `Category`, `Tag` and `Tax` columns are **not shown**.
3. Create a new policy.
4. Verify that `Categories` feature is **enabled**.
5. Open the new Search page.
6. Verify that the `Category` column is **shown**.
7. Enable `Tags` in the policy.
8. Verify that both `Category` and `Tag` columns are now **shown** in the new Search page.
9. Enable `Taxes` in the policy.
10. Verify that `Category`, `Tag` and `Tax` columns are now **shown** in the new Search page.


Do we agree 👍 or 👎.

**Comment by luacmartins** [comment]
No need for regression tests, we'll add those as part of the project wrap up

**Comment by Christinadobrzyn** [comment]
Thanks @ikevin127 - can you please accept this Upwork offer? https://github.com/Expensify/App/issues/43494#issuecomment-2197552024

**Comment by ikevin127** [comment]
@Christinadobrzyn Accepted, thank you!

**Comment by Christinadobrzyn** [comment]
Awesome paid out @ikevin127 through Upwork based on this payment summary https://github.com/Expensify/App/issues/43494#issuecomment-2197552024

I think we're good to close this!
