### ISSUE TITLE
Contact Method - User is logged out after adding a secondary contact method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-9
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** berhanesarah.testing+hsadjw2d@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login to staging as a new user
2. Go to profile settings-->Contact Methods
3. Verify the contact method
4. Click on new contact method
5. Add a new email account

## Expected Result:
User is able to add a second contact method

## Actual Result:
User is immediately signed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5ece359b-1be4-4c60-95c6-84fab19b45db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@yuwenmemon  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment]
Gonna demote this since the fix is in Auth and this is a new feature in App.

**Comment by luacmartins** [comment]
This is done.
