### ISSUE TITLE
[HybridApp] Android white screen issues

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#43510]
## Problem

There are multiple scenarios in which you can cause the Android HybridApp to just display a white screen.

#### Home Button
1. Open HybridApp when `tryNewDot.classicRedirect.dismissed == true`
2. Hit home button
3. Reopen app 💥 

#### Back Button
1. Open HybridApp when `tryNewDot.classicRedirect.dismissed == true`
2. Hit back button 💥 

## Solution
1. For the home button, we should reopen the NewDot UI when HybridApp is just backgrounded
2. For the back button, we should close the entire HybridApp when we hit the back button and NewDot is the "root" UI

cc @staszekscp @mateuuszzzzz

**Comment by staszekscp** [comment]
Hey! PRs with all fixes are linked above 😄
