### ISSUE TITLE
[HybridApp] Fix dark mode and themes

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#43511]
## Problem
NewDot has the functionality to look at the phone's settings to determine whether to use light mode or dark mode for the theme. However, HybridApp is not doing this.

## Solution
Fix it!

cc @staszekscp @mateuuszzzzz

**Comment by staszekscp** [comment]
I've just opened a PR with a [fix](https://github.com/Expensify/Mobile-Expensify/pull/12734)
