### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [#Wave-Control - Add Sage Intacct] Add the Connection option and Connection button in NewDot

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#43532]
Tracking GH: https://github.com/Expensify/Expensify/issues/388780

Design doc section: https://docs.google.com/document/d/1k3ZFw8KB55yPUSCG6KYZlwpwEtmRt3eUshwxs7bZq5I/edit#heading=h.w7qju91gpvcq

---

Before diving into it, let’s add it to the list of the available connections options.

```JS
// src/CONST.ts       
 
const CONNECTIONS = {
    NAME: {
        // Here we will add other connections names when we add support for them
        QBO: 'quickbooksOnline',
        XERO: 'xero',
        // …
        SAGE_INTACCT: 'intacct',
    },
};
```

Next, we’re going to show it in the Accounting page. To do this, modify `PolicyAccountingPage.tsx`:
```js
// src/pages/workspace/accounting/PolicyAccountingPage.tsx


switch (connectionName) {
// ...
case CONST.POLICY.CONNECTIONS.NAME.SAGE_INTACCT:
                return {
                    title: translate('workspace.accounting.sageIntacct'),
                    icon: Expensicons.SageIntacctSquare,
                    setupConnectionButton: (
                        <ConnectToSageIntacctButton
                            policyID={policyID}
                            shouldDisconnectIntegrationBeforeConnecting={isConnectedToIntegration}
                            integrationToDisconnect={integrationToDisconnect}
                        />
                    ),
                    onImportPagePress: () => Navigation.navigate(ROUTES.POLICY_ACCOUNTING_SAGE_INTACCT_IMPORT.getRoute(policyID)),
                    onExportPagePress: () => Navigation.navigate(ROUTES.POLICY_ACCOUNTING_SAGE_INTACCT_EXPORT.getRoute(policyID)),
                    onAdvancedPagePress: () => Navigation.navigate(ROUTES.POLICY_ACCOUNTING_SAGE_INTACCT_ADVANCED.getRoute(policyID)),
                };     
```

### Creating the connection button

The code for the `ConnectToSageIntacctButton.tsx` component would look like something like this:
```JS
// src/components/ConnectToSageIntacctButton/index.tsx

function ConnectToSageIntacctButton({policyID, shouldDisconnectIntegrationBeforeConnecting, integrationToDisconnect}: ConnectToSageIntacctButtonProps) {
    return (
        <>
            <Button
                onPress={() => {
                    if (shouldDisconnectIntegrationBeforeConnecting && integrationToDisconnect) {
                        setIsDisconnectModalOpen(true);
                        return;
                    }
			// 3 conditions need to be done here (screenshots in the "Connection Process" section)
			// These are:
                    // 1. show prerequisites modal if necessary i.e credentials not present in policy's intacct connection data
			// 2. if secondary workspace with Intacct sync, show a menu with options "Create new connection" and "Reuse existing connection" 
			// 3. otherwise sync by calling the SyncPolicyToSageIntacct command
                }}
                text={translate('workspace.accounting.setup')}
                style={styles.justifyContentCenter}
                small
                isDisabled={isOffline}
            />
            {shouldDisconnectIntegrationBeforeConnecting && isDisconnectModalOpen && integrationToDisconnect && (
                <ConfirmModal
                    title={translate('workspace.accounting.disconnectTitle', CONST.POLICY.CONNECTIONS.NAME.SAGE_INTACCT)}
                    isVisible
                    onConfirm={() => {
                        removePolicyConnection(policyID, integrationToDisconnect);
                        Link.openLink(getSageIntacctSetupLink(policyID), environmentURL);
                        setIsDisconnectModalOpen(false);
                    }}
                    onCancel={() => setIsDisconnectModalOpen(false)}
                    prompt={translate('workspace.accounting.disconnectPrompt', CONST.POLICY.CONNECTIONS.NAME.SAGE_INTACCT)}
                    confirmText={translate('workspace.accounting.disconnect')}
                    cancelText={translate('common.cancel')}
                    danger
                />
            )}
        </>
    );
}

export default React.memo(ConnectToSageIntacctButton);
```
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a8c2faf283b52e8</li>
        <li>Upwork Job ID: 1800756578326323366</li>
        <li>Last Price Increase: 2024-06-12</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 102709182</li>
<li>hungvu193 | Contributor | 102767547</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by alexpensify** [comment]
Thanks, I've assigned to @SzymczakJ

**Comment by SzymczakJ** [comment]
Update:
Even though we are still waiting for API command to be implemented on BE I'll put up a PR with mocked backend interaction. It should be ready tomorrow or on Monday.

**Comment by hungvu193** [comment]
@yuwenmemon Can you assign me this one?

**Comment by yuwenmemon** [comment]
Yeah @ishpaul777 - @hungvu193 is working on the whole project and reviewing all PRs underneath since they have broad context.

**Comment by SzymczakJ** [comment]
PR on this should be ready to review tomorrow(of course we're still waiting for BE but this code could use some checking 😄 ). Btw how is BE work going @yuwenmemon?

**Comment by alexpensify** [comment]
Thanks for the update @SzymczakJ!

**Comment by yuwenmemon** [comment]
@SzymczakJ I think we should have the BE done and deployed sometime this week. @NikkiWines said she'll have a PR ready by EOD today! 🎉

**Comment by SzymczakJ** [comment]
@hungvu193 PR is ready for review. Please keep in mind that I'm gonna add some API calls/error handling when backend is ready but these should be pretty small changes 😄

**Comment by hungvu193** [comment]
Awesome. I'll take a look in a while 👀

**Comment by hungvu193** [comment]
> Backend PR is up https://github.com/Expensify/Web-Expensify/pull/42400

Please let us know once this is deployed so @SzymczakJ can continue to integrate the API to current PR 😄

**Comment by SzymczakJ** [comment]
What's status of your BE PR @NikkiWines? 😺

**Comment by NikkiWines** [comment]
It's on staging currently, should be deployed to production on Monday

**Comment by SzymczakJ** [comment]
@NikkiWines how to execute this command properly from FE, doc is missing information on that part. I tried something like 
<img width="895" alt="image" src="https://github.com/Expensify/App/assets/88395093/aa832167-fd97-4692-89f4-d4dc36cb23ed">
with the credentials with which I logged into Sage Intacct on Old Dot and it's not working 😭. I also tried many other variations of this command usage and all of them fail. Can you give me and example how to invoke `ConnectPolicyToSageIntacct` command?

**Comment by NikkiWines** [comment]
@SzymczakJ the parameter names are slightly different - they're all prepended with `intacct` (i.e. `intacctCompanyID`, `intacctUserID`, `intacctPassword`). Also, looks like it should be `const parameters: ConnectPolicyToSageIntacct` 

Other than those two things what you have above should work!

**Comment by SzymczakJ** [comment]
It works! One more question @NikkiWines: what about reusing existing Sage Intacct connection? I have credentials data in intacct config but sage intacct password is encrypted. Using this encrypted password with ConnectPolicyToSageIntacct doesn't work.

**Comment by SzymczakJ** [comment]
I have some problems:
1. `connectionSyncProgress` is not updated when connecting to Sage Intacct. I can connect properly, but I cannot update connection progress because `connectionSyncProgress` is undefined all the time
2. what to do when user gives wrong Sage Intacct credentials, should we show some kind of error?

**Comment by NikkiWines** [comment]
@SzymczakJ sounds like you got these answered q's in [this slack thread](https://expensify.slack.com/archives/C06ML6X0W9L/p1719331875931449?thread_ts=1719271507.184899&cid=C06ML6X0W9L), is that correct?

**Comment by alexpensify** [comment]
It looks like the Slack thread has a plan. Keep us posted if you need anything else @SzymczakJ to keep moving forward here. Thanks!

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Monday, July 8, 2024, and will not actively watch over this GitHub during that period. 

I'll try to check in a few times. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by SzymczakJ** [comment]
As we planned to create a follow-up PR, can we create a separate issue for it? @yuwenmemon

**Comment by hungvu193** [comment]
Thanks for pointing that out @SzymczakJ, let's me create an issue for it 🙏

**Comment by alexpensify** [comment]
@hungvu193 and @SzymczakJ - can we confirm if this deploy blocker notice is accurate or an error? Thanks!

**Comment by SzymczakJ** [comment]
Like @lakchote said [here](https://github.com/Expensify/App/issues/44813#issuecomment-2208962936) it's not a deploy blocker and I agree with him. I can fix this bug right away because the fix is changing one line, but I would rather do it in this [PR](https://github.com/Expensify/App/pull/44850), since I'm spinning up a follow-up PR anyway. WDYT

**Comment by SzymczakJ** [comment]
I've included the fix in the [PR](https://github.com/Expensify/App/pull/44850) that I was talking about.

**Comment by alexpensify** [comment]
Thank you for this update and swift action.

**Comment by alexpensify** [comment]
I believe the payment date has been moved to 7/22, and will prepare accordingly.

**Comment by hungvu193** [comment]
No payment needed for me. I will be paid later after SageIntacct project is completed

**Comment by alexpensify** [comment]
@hungvu193 - thank you for that update. Here is the payment breakdown for the records: 

Payouts due: N/A 

- [ ] Contributor: N/A @SzymczakJ - payment will be handled via agency 
- [ ] Contributor+: N/A @hungvu193 - payment will be addressed when the full project is complete in another GH 

Upwork job is https://www.upwork.com/jobs/~017a8c2faf283b52e8
