### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$250]  Web - Subscription - No offline indicator on subscription page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43558]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/43370
## Action Performed:
1. Go to https://staging.new.expensify.com/settings/subscription
2. Go offline

## Expected Result:
Offline indicator will appear at the bottom of the page

## Actual Result:
Offline indicator does not appear at the bottom of the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/65d84216-e194-4ebc-911a-fe448aa81854

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b0cd5636fae177d</li>
        <li>Upwork Job ID: 1802802935888037908</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102781798</li>
<li>cretadn22 | Contributor | 102781799</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by lanitochka17** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment]
Putting into collect as this is focused on subscription page.

**Comment by kevinksullivan** [comment]
@akinwale please review the proposal above when you get a chance. Thanks!

**Comment by akinwale** [comment]
We can move forward with @cretadn22's [proposal](https://github.com/Expensify/App/issues/43558#issuecomment-2162952731) here.

🎀👀🎀 C+ reviewed.

**Comment by pecanoro** [comment]
Sounds good, assigning @cretadn22

**Comment by kevinksullivan** [comment]
@akinwale please complete the checklist above

**Comment by kevinksullivan** [comment]
Paid @cretadn22 , waiting on checklist to pay @akinwale

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify
2. Navigate to the subscriptions settings screen - https://staging.new.expensify.com/settings/subscription
3. Go offline
4. Verify that the offline indicator is displayed at the bottom of the page

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
> Paid @cretadn22 , waiting on checklist to pay @akinwale

@kevinksullivan Done!

**Comment by kevinksullivan** [comment]
waiting on checklist, asked about it here

https://expensify.slack.com/archives/C02NK2DQWUX/p1721067253383449?thread_ts=1720555683.892599&cid=C02NK2DQWUX

**Comment by akinwale** [comment]
> waiting on checklist, asked about it here
> 
> https://expensify.slack.com/archives/C02NK2DQWUX/p1721067253383449?thread_ts=1720555683.892599&cid=C02NK2DQWUX

Completed the checklist here: https://github.com/Expensify/App/issues/43558#issuecomment-2206347683

**Comment by kevinksullivan** [comment]
All set
