### ISSUE TITLE
[Simple AA in NewDot] Make sure optimistic Next Steps & report action are set for Control mid-level "Approvals" in NewDot

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#43567]
Tracking issue: https://github.com/Expensify/Expensify/issues/393839

Design doc section: [Make sure optimistic Next Steps & report action are set correctly, for “Approve” (old term “Forward”) in NewDot](https://docs.google.com/document/d/1CSRVEBmiOL1s0hk7qqZvXoiUuHoL0m_DnTKRXy4txYI/edit#bookmark=id.7pum9aftuifo)

Goals:
1. Set optimistic next steps for approvals, when policy is Control and on Advanced Approval mode
    - Specifically new for mid-level approvers
2. Need to build basic approval chain from policy `employeeList` in order to be able to figure out who should optimistically be the next approval
3. Also needs to optimistically add `Approved <total>` report action to workspace chat

## Background:

We currently generate optimistic Next Steps when approving a report in NewDot [here](https://github.com/Expensify/App/blob/486c070a555f803955c0e971ce43a77fcd91afdc/src/libs/NextStepUtils.ts#L272-L318). The current possible next steps are:
1. “Finished! No further action required”
2. “Next steps: Waiting for you to pay the expenses”

## Problem:

There are now more possible cases when a report is getting approved!

When a Control policy has "Advanced Approvals" enabled, there can be multiple "mid-level" approvers. When these members approve the policy, we actually call this "forwarding" - because we "forward" the report to the next person in line. The **final approver** actually does the "approving".

## Solution:

1. Build the report's approval chain any time someone approves a report on a Control workspace with advanced approvals enabled
    - Note: For v1 we will only consider `submitsTo`, `forwardsTo`, and `overLimitForwardsTo`. Later, we'll add in rule approvers (tag & category)
2. Optimistically add a report action saying `approved <total>` even when forwarding the report

### Approval Chain Logic:

When building out the approval chain logic, logic should look like this:
1. Get policy's `employeeList`
2. Get report submitter, get their policy data with `employeeList[submitterEmail]`
3. The first member of the approval chain is the employee's `submitsTo` - like `submitsToEmail = employeeList[submitterEmail]?.submitsTo ?? policyOwnerEmail`
4. Next, get the submitsTo person's policy data with `submitsToEmployeeData = employeeList[submitsToEmail]`
5. From here on, we get the next approver by looking at `forwardsTo`, `overLimitForwardsTo`, and `approvalLimit`
    1. If `submitsToEmployeeData` has an `approvalLimit` and `overLimitForwardsTo`, do this:
        1. Get the report total
        2. If the report total is > `approvalLimit`, then the next approver in line is the email address in `submitsToEmployeeData?.overLimitForwardsTo`
        3. If the report is <= `approvalLimit`, then the next approver in line is `submitsToEmployeeData?.forwardsTo`
    2. If `submitsToEmployeeData` doesn't have either `approvalLimit` or doesn't have `overLimitForwardsTo`, the next approver in line is `submitsToEmployeeData?.forwardsTo`
    3. Note: If we ever run into a missing approver here (a.k.a. if `submitsToEmployeeData` doesn't have a `forwardsTo`), we're done!
6. Now we get the `forwardsTo` or `overLimitForwardsTo`'s policy data with `forwardsEmployeeData = employeeList[forwardsToEmail]`
7. Repeat steps 5 & 6 until you either:
    1. End up with an email address you already added to the approval chain
    2. Run into some employee's data that doesn't have a `forwardsTo`

This looks something like this:

![Screenshot 2024-07-01 at 3 35 41 PM](https://github.com/Expensify/App/assets/3885503/7c47a5d4-1a09-4e95-a9c1-9b634e2fa62b)

Where `$policy->getForwardsTo` looks like this:

![Screenshot 2024-07-01 at 3 36 52 PM](https://github.com/Expensify/App/assets/3885503/1ab44eb4-5653-43f1-8643-65e4bbec4508)

### Examples:

Say, for example, we have this Control `employeeList` policy setup (with advanced approvals enabled):

| Member Email | policy role | `submitsTo` | `forwardsTo` | `overLimitForwardsTo` | `approvalLimit` |
|---|---|---|---|---|---|
| boss_owner@gmail.com | admin | mini_owner@gmail.com | | | |
| mini_owner@gmail.com | admin | boss_owner@gmail.com | | | |
| manager@gmail.com | employee | mini_owner@gmail.com | mini_owner@gmail.com | boss_owner@gmail.com | 10000 |
| employee1@gmail.com | employee | manager@gmail.com | | | |
| employee2@gmail.com | employee | manager@gmail.com | | | |

Each member's approval chain looks like this:

| Policy Member | Approval Chain (if report total <= approvalLimit) | Approval Chain (if report total > approvalLimit) |
|---|---|---|
| boss_owner@gmail.com | mini_owner@gmail.com | same |
| mini_owner@gmail.com | boss_owner@gmail.com | same |
| manager@gmail.com | mini_owner@gmail.com | same |
| employee1@gmail.com | manager@gmail.com, **mini_owner@gmail.com** | manager@gmail.com, **boss_owner@gmail.com** |
| employee2@gmail.com | manager@gmail.com, **mini_owner@gmail.com** | manager@gmail.com, **boss_owner@gmail.com** |

**Comment by Beamanator** [comment]
Keeping internal for now, will make this external soon once all details are added here

**Comment by Beamanator** [comment]
Gotta get the held issue done, then will open this up!

**Comment by garrettmknight** [comment]
I think we're off hold! cc @Beamanator yeah?

**Comment by Beamanator** [comment]
Hmm yes this is off hold, @youssef-lr I don't think we need you on this one since it can be worked externally (see my messages above) - I'm planning to finish writing up the necessary details & assigning this one out today or tomorrow!

**Comment by Beamanator** [comment]
Asked @rushatgabhane for a review of the requirements to make sure it makes sense 🙏

**Comment by rushatgabhane** [comment]
Okay so I was able to build the approval chain and it tests well for employee, manager, and both owners - 

<img width="777" alt="image" src="https://github.com/Expensify/App/assets/29673073/8577f9d6-a798-44b9-a175-7e62ca7a0da2">

**Comment by rushatgabhane** [comment]
@Beamanator it is okay to always make the `reportTotal` a positive number, right?

**Comment by rushatgabhane** [comment]
The accounts owed money, so the report total was `-X`

**Comment by rushatgabhane** [comment]
@Beamanator I've added optimistic steps in the [PR](https://github.com/Expensify/App/pull/44940), but I'm facing a backend issue.


When a manger approves the report, im getting a 400 error for `ApproveMoneyRequest`.
 
<img width="577" alt="image" src="https://github.com/Expensify/App/assets/29673073/6d54ef4c-97b3-40a4-a57c-b76b5e738ad9">


https://github.com/Expensify/App/assets/29673073/ff581cb8-93f8-4e05-9387-ec29767c6323

**Comment by Beamanator** [comment]
@rushatgabhane it looks like that is thrown when our backend thinks you're trying to "Forward" the report, but you SHOULD be trying to "Approve"

This is actually expected for right now, since @marcochavezf is working on adding changes so that mid-level approvers can always "Approve" OR "Forward" a report from NewDot. So you probably can't actually test out the full "Submitter -> submitsTo -> forwardsTo" approval flow YET (with the backend working) but you can test that it optimistically works probably?

**Comment by rushatgabhane** [comment]
@Beamanator yeah optimistic is no problem :)

It works offline

**Comment by Beamanator** [comment]
Groovy - but ya probably sadly we can't get your PR merged till the backend stuff is done. sorry for that, thanks for getting this done quick!

**Comment by rushatgabhane** [comment]
> working on adding changes so that mid-level approvers can always "Approve" OR "Forward" a report from NewDot

makes sensee, thank you for digging into it : )


> Groovy - but ya probably sadly we can't get your PR merged till the backend stuff is done. sorry for that, thanks for getting this done quick!

No worries

**Comment by trjExpensify** [comment]
Can we state what issue/PR this is on hold for in the title, so that's clear?

**Comment by trjExpensify** [comment]
^^ bump on the above! :)

**Comment by Beamanator** [comment]
Sorry for the delay! We're basically holding on https://github.com/Expensify/Expensify/issues/404206, where @marcochavezf will be enable clicking Approve (no matter if it's approving or forwarding) in NewDot

**Comment by trjExpensify** [comment]
Still held.

**Comment by Beamanator** [comment]
Still held, but getting close!

**Comment by JmillsExpensify** [comment]
Can we remove the hold based on Marco's most recent merged PRs?

**Comment by trjExpensify** [comment]
https://expensify.slack.com/archives/C06ML6X0W9L/p1722354497413689?thread_ts=1722319732.404769&cid=C06ML6X0W9L - according to @Beamanator not quite, but Marco's Web PR in the linked issue is [on staging](https://github.com/Expensify/Web-Expensify/pull/42557#issuecomment-2257076213), so I think we're pretty much there.

**Comment by Beamanator** [comment]
Ooh yes even the [App PR](https://github.com/Expensify/App/pull/46465) is on staging! I think it's time to take this off hold!

**Comment by Beamanator** [comment]
@rushatgabhane can you pull `main` & start testing on staging? 🙏  there may be a few bugs which @marcochavezf and I can work out, but as long as this optimistic stuff can be tested now, that would be amazing 🙏

**Comment by Beamanator** [comment]
Boom this is completely off hold as the ApproveMoneyRequest stuff should be on prod!

**Comment by Beamanator** [comment]
PR was most likely deployed to prod yesterday

**Comment by Beamanator** [comment]
I thinkkkk payment is due here 🚀

**Comment by trjExpensify** [comment]
Okay, so this is the PR: https://github.com/Expensify/App/pull/44940

- What happened here with the review, it was merged before @mananjadhav's C+ review, but completed after, hence no checkmark? 🤔 
- Was this [considered a regression](https://github.com/Expensify/App/pull/44940#issuecomment-2284943045)?

**Comment by Beamanator** [comment]
> What happened here with the review, it was merged before @mananjadhav's C+ review, but completed after, hence no checkmark? 🤔

Yep exactly 👍 

> Was this [considered a regression](https://github.com/Expensify/App/pull/44940#issuecomment-2284943045)?

Hmm seems like ifffff it was, we didn't consider it a big deal since it hasn't been worked on yet, so i would say we don't need to consider that a payment slashing regression, what you think?

**Comment by trjExpensify** [comment]
Alright, so payment summary as follows: 

- $250 to @rushatgabhane for the fix
- $250 to @mananjadhav for the C+ review

Closing it out!

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
