### ISSUE TITLE
[$250] Chats - User remains on LHN page after onboarding flow completed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/41343
**Email or phone of affected tester (no customers):** Hohovemgo+oma20@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41343
## Action Performed:
Precondition: user should be Signed Out
1. Open app
2. Write any email with public domain which was not user for registration before
3. Click on Continue button
4. Click on Join button
5. Select any onboarding option
6. Complete the onboarding flow

## Expected Result:
User should be redirected either to the Concierge chat or Expensify persona

## Actual Result:
User remains on LHN page after onboarding flow completed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1ad90af5-9dd3-439c-b39e-46499a23ae44

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170226485ccb489be</li>
        <li>Upwork Job ID: 1802805545916133888</li>
        <li>Last Price Increase: 2024-06-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by mountiny** [comment]
It seems like you should be redirected to the chat https://github.com/Expensify/App/issues/38774#issuecomment-2180250134

**Comment by mountiny** [comment]
asked https://expensify.slack.com/archives/C036QM0SLJK/p1718885687316199

**Comment by mountiny** [comment]
This seems to be by design on narrow devices https://expensify.slack.com/archives/C036QM0SLJK/p1718898938705079?thread_ts=1718885687.316199&cid=C036QM0SLJK


@slafortune would you be able to please update any testrail cases related to this to make sure they say that on mobile/ narrow screens the users are navigated to LHN after completing the flow? thank you!

**Comment by slafortune** [comment]
Added to the regression test - close since this is expected.
