### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$500] [Guided Setup] Refreshing the page with the onboarding flow closes it and never shows it again 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @yuwenmemon 
**Slack conversation:** internal https://expensify.slack.com/archives/C036QM0SLJK/p1718140438433339

## Action Performed:
Break down in numbered steps

1. Sign up with fresh new account
2. Verify you can see the onboarding modal
3. Refresh the browser tab

## Expected Result:
Describe what you think should've happened

The onboarding modal is shown until you complete it, you cannot skip it

## Actual Result:
Describe what actually happened

The onboarding modal was closed and does not show up again

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/36083550/d1721783-e801-4f3c-bab5-b12d1fc8b9be

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7cc757137685065</li>
        <li>Upwork Job ID: 1800874213746714078</li>
        <li>Last Price Increase: 2024-06-12</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102710630</li>
<li>ishpaul777 | Contributor | 102710631</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by hungvu193** [comment]
We can go with @ishpaul777 's proposal

🎀👀🎀 C+ reviewed

**Comment by mountiny** [comment]
@ishpaul777 if we do your changes, the onboarding flow will show up for old accounts or accounts created in Olddot. They do not have the `onboarding?.hasCompletedGuidedSetupFlow` defined and we should not show them the onboarding flow

**Comment by hungvu193** [comment]
What's its default value for new account? If it's false then we can add an extra condition to handle that case.

**Comment by hungvu193** [comment]
I'm having trouble while testing account that was created from old dot. I'll try again in a while...

https://github.com/Expensify/App/assets/16502320/9f699faf-4687-4096-95b3-e20a167b75cd

**Comment by hungvu193** [comment]
With old account, !Array.isArray(onboarding) is true and onboarding?.hasCompletedGuideSetupFlow will be false if we remove ?? true.
So it will make **hasCompletedGuideSetupFlow** return false and popup will open.

**Comment by mountiny** [comment]
@ishpaul777 alright, I think that works, please raise the pr when you can, thanks

**Comment by hungvu193** [comment]
Cool. I'll review it today

**Comment by johncschuster** [comment]
@hungvu193 / @ishpaul777 can you address the BZ Checklist when you get a moment? Thank you!

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42087/files
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42087/files#r1651206632
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: Yes


**Regression test**:
1. Sign up with fresh new account.
2. Verify you can see the onboarding modal.
3. Refresh the browser tab.
4. Verify that on boarding modal will show up.

Do we 👍 or 👎  ?

**Comment by johncschuster** [comment]
Payment has been issued. Thanks for your contributions! 🎉
