### ISSUE TITLE
Send invoice - Members list does not display Admin badge next to admin for invoice receiver

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43576]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Go to FAB > Send invoice
3. [User A] Send invoice to User B
4. [User B] Go to invoice chat
5. [User A and B] Go to invoice chat header > Members

## Expected Result:
Members list will display Admin badge next to admin on both sides

## Actual Result:
Members list does not display Admin badge next to admin for the invoice receiver

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cd5bb82b-6939-4e3e-a3c8-7f9bbdc2b977

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-bills

**Comment by Tony-MK** [comment]
This issue is a backend issue because the policy is not synced with the front end.

Hence, the admin role is not found with invoice reports, since the policy is unavailable in the onyx.

![Screenshot 2024-06-13 at 10 17 10](https://github.com/Expensify/App/assets/22982173/960ded58-0426-4278-b6e7-273b568eb7c8)


Additionally, since there are two participants and an Expensify member, we can check the `isAdmin` role by adding another condition by checking if the participant is the `invoiceRevecier` and doesn't have an Expensify email.

**Comment by stephanieelliott** [comment]
Interesting, thanks @Tony-MK! Given that this is a pretty minor issue that doesn't doesn't affect functionality, is not on our near-term roadmap and will need to be worked on internally, I am going to close this one for now.
