### ISSUE TITLE
QAB - Duplicate headers become visible and background image appears on top of the header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4625336
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Click on FAB and click on assign task
4. Choose the workspace created on step 2 to share somewhere
5. Choose an assignee and create the task
6. Click on FAB - QAB and create the task

## Expected Result:
The second task gets created and no visual defects is seen

## Actual Result:
Duplicate headers become visible and the first header becomes overlapped with the background image

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/ab018b9c-d120-4126-800c-db66cfdee24a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by MitchExpensify** [comment]
Unable to reproduce on first attempt

**Comment by MitchExpensify** [comment]
Still unable to reproduce 

<img width="955" alt="image" src="https://github.com/Expensify/App/assets/36425901/d8f0915e-2d69-42ad-86d4-e268aefcdec5">

**Comment by MitchExpensify** [comment]
Still unable to reproduce 

<img width="634" alt="image" src="https://github.com/Expensify/App/assets/36425901/cfe952b6-0f88-456b-be3c-8bebe26a7f0e">
