### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$250] Send invoice - Two unread markers when marking message unread in invoice thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43575]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount, select participant and send the invoice
4. Go to invoice thread
5. Send a message
6. Right click on the message > Mark as unread

## Expected Result:
There will be one unread marker above the message

## Actual Result:
There are two unread markers above the message
If the invoice currency is foreign currency, three unread markers will show up - another one is below Total row

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/af715cb2-0c7d-42f7-a426-f8245a44fa5c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172ef4f418ef0c267</li>
        <li>Upwork Job ID: 1801658282966992916</li>
        <li>Last Price Increase: 2024-06-14</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 102768842</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
Hello folks, sorry I was OOO last week. I have a bunch to do, I will get them all done today. Thanks for your patience.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @suneox paid $250 [here](https://www.upwork.com/nx/wm/offer/102768842) (Reviewer)
- @daledah paid $250 [here](https://www.upwork.com/nx/wm/offer/103159135) (Contributor)

**Comment by twisterdotcom** [comment]
`
