### ISSUE TITLE
[$250] Tag - Dependent tag violation message isn't changing to "all tags required"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43574]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #40741
**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition: Import the attached dependent_tags.csv in OD for a workspace. Enable multi level tags.

1. Navigate to https://staging.new.expensify.com/

2. Log in with an expensifail account
3. Navigate to the workspace chat
4. Start submitting a manual expense
5. Only input the "Merchant" field on the confirmation page
6. Submit the expense
7. Open the expense
8. Click on any of the three missing tags
9. Choose any of the options

## Expected Result:
The message should change to "all tags required" for the reported missing tags.

## Actual Result:
Dependent tag violation message isn't changing to "all tags required" for the rest of the tags when there are multiple missing tags and one is selected.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[Bug6510487_1718181753132!dependent_tags.csv](https://github.com/user-attachments/files/15806341/Bug6510487_1718181753132.dependent_tags.csv)

https://github.com/Expensify/App/assets/43996225/91868197-e7a8-4279-8500-0294663a5fb3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b410860cea8f950</li>
        <li>Upwork Job ID: 1801658425666734007</li>
        <li>Last Price Increase: 2024-08-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @yuwenmemon</details>

**Comment by kavimuru** [comment]
We think this bug might be related to #wave-collect - Release 1

**Comment by twisterdotcom** [comment]
Also got this: https://github.com/Expensify/App/issues/38682.

**Comment by sobitneupane** [comment]
Waiting on proposal

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by twisterdotcom** [comment]
Still waiting on proposals. May be addressed eventually with Control functionality.

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by twisterdotcom** [comment]
Still waiting

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by twisterdotcom** [comment]
Still waiting. Gonna make this weekly.

**Comment by twisterdotcom** [comment]
Still waiting for proposals

**Comment by mvtglobally** [comment]
Issue is reproducible during KI retests.

https://github.com/user-attachments/assets/116a9f8a-41a7-4eed-a210-61d7815b494b

**Comment by teneeto** [comment]
Hey! I'm Eto Olei from Callstack. I will like to look into this issue. Please assign it to me. Thanks!

**Comment by teneeto** [comment]
Hi All!, 
One little concern here; in trying to reproduce this issue, I'm wondering what expensify account gives the extra tags, as state, region and city after submitting a manual expense. 

After submitting an expense with my account, I'm not getting those fields. what am I missing?

**Comment by twisterdotcom** [comment]
Hold that thought for now @teneeto. I think we may have somebody internally working on Dependent tags soon.

**Comment by teneeto** [comment]
Alright @twisterdotcom, I'll be glad if you Keep me posted on this. Also, I'm still keeping this on the watch, let me know in any way I can assist. Thanks

**Comment by yuwenmemon** [comment]
Will look at this as a part of the tags project soon.

**Comment by teneeto** [comment]
Cool, @yuwenmemon, I'm still here; please let me know if I can come in for any help.

**Comment by twisterdotcom** [comment]
This is going through the motions internally now.

**Comment by yuwenmemon** [comment]
I don't get it.... this happens for independent tags too. Are we sure we need this to say "all tags required"? cc @cead22 

https://github.com/user-attachments/assets/78735c72-be68-4210-bce5-941ffb24dedc

**Comment by twisterdotcom** [comment]
Hmm good point, I think given we say "Missing tagName" for each level, this is fine now.

**Comment by yuwenmemon** [comment]
Sweet - closing!
