### ISSUE TITLE
Distance-Blue dot replaces start point on confirmation screen and preview when location denied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: location access is denied, user is a member of a workspace
1. Open the app and log in as a member of a workspace
2. Navigate to the workspace chat
3. Tap + > Submit expense > Distance
4. If the location access pop-up is displayed, deny it
5. Enter the start and finish waypoints and proceed to the confirmation screen
6. Finish creating a distance expense
7. Open the created distance expense

## Expected Result:
The blue dot is not displayed since the location access is denied

## Actual Result:
The blue dot replaces the start point on the confirmation screen and on the expense preview in the report until the expense is opened or the distance is done calculating
When the location access is allowed, the blue dot does not replace the start point if it is not current location

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6e7a1dc6-ab49-45ca-9a2c-a47cbe90e6dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment]
I see [we originally](https://expensify.slack.com/archives/C049HHMV9SM/p1712974874670609) added this blue dot in the #vip-vsb project fairly recently. I can reproduce the behavior above, but this is negligibly noticeable. I am not convinced any customer would actually notice this. 

Additionally, we have recently deprioritized the #vip-vsb project altogether.

**Comment by joekaufmanexpensify** [comment]
The combination of both of those makes me think we should close for now. If we get any actual feedback from customers on this, we can revisit then.
