### ISSUE TITLE
 Android - Attachments - Image preview displayed briefly after sending attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43583]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4625195
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Open any report
3. Tap + > Add attachment
4. Take a photo or select an image from gallery
5. Send the image to the chat

## Expected Result:
The image preview closes and does not display again

## Actual Result:
The image preview is displayed briefly again after sending

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/29585833-d0a0-4a5f-b915-af92be587926

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by anmurali** [comment]
Cannot reproduce.
