### ISSUE TITLE
[$250]  Send invoice - Invoice thread name can renamed when created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43582]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go FAB > Send invoice.
4. Send invoice to a user.
5. Go to transaction thread.
6. Click report header > Settings.
7. Click Room name.
8. Go online.
9. Repeat Step 6 and 7.

## Expected Result:
Invoice thread name cannot be renamed when created offline, because it can't be renamed online

## Actual Result:
Invoice thread name can renamed when created offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/abc81dae-e1c3-4499-bdbc-3fb793282445

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189569ee60be7065e</li>
        <li>Upwork Job ID: 1803295776701776707</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102975673</li>
<li>cretadn22 | Contributor | 102975676</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Send invoice - Invoice thread name can renamed when created offline

### What is the root cause of that problem?

The problem is that the `FormProvider` in `RoomNamePage` is always enabled when offline for every type of report.

https://github.com/Expensify/App/blob/a20c99ab501568ef2e9c03bd1c3c0e11de3174f6/src/pages/settings/Report/RoomNamePage.tsx#L86-L92

### What changes do you think we should make in order to solve the problem?


We need to check if the report is an invoice to disable it when it is offline.

```
enabledWhenOffline={!Report.isInvoiceReport(report)}
```

**Comment by Tony-MK** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/43582#issuecomment-2163348092)

**Comment by JmillsExpensify** [comment]
Added to vip invoicing and went ahead and opened up to the community.

**Comment by JmillsExpensify** [comment]
Awaiting proposal review.

**Comment by JmillsExpensify** [comment]
Not clear why this is overdue.

**Comment by Tony-MK** [comment]
@shubham1206agra, Can you please give me feedback on my [proposal](https://github.com/Expensify/App/issues/43582#issuecomment-2163348092)

**Comment by JmillsExpensify** [comment]
I agree with that. Let's fix that issue here as well.

**Comment by JmillsExpensify** [comment]
Payment Summary:

 - Contributor: @cretadn22 $250
 - Reviewer: @shubham1206agra $250

**Comment by JmillsExpensify** [comment]
Contributor Upwork contract paid out.
