### ISSUE TITLE
[$250] mweb-task-User assigning secondary contact&creating task directs to hmm not here page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43593]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login with a new account
3. Tap fab -- assign task
4. Enter title and tap next
5. Select assignee as a secondary contact- [Jaihanumanblog+1111@gmail.com](mailto:Jaihanumanblog+1111@gmail.com)
6. Confirm task
7. Navigate to LHN
8. Perform step 3 - step 6 again

## Expected Result:
User must be directed to primary contact page showing task created

## Actual Result:
User assigning secondary contact&creating task directs to hmm not here page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/1967d438-d4b7-4942-b727-8141fb5d9d12

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010975818a83afe598</li>
        <li>Upwork Job ID: 1805943519786778762</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by m-natarajan** [comment]
@muttmuure FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment]
Not overdue

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by sobitneupane** [comment]
Waiting for proposal

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/43593#issuecomment-2221966015

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sobitneupane** [comment]
https://github.com/Expensify/App/issues/43593#issuecomment-2306951056
