### ISSUE TITLE
The `Expensify`  user profile picture has black negative space around it.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43607]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718200066253569

## Action Performed:
1. Open app 
2. Search for `Expensify user`
3. Click on the image to see in the larger view
## Expected Result:
The image should be square image like all other profile picture
## Actual Result:
Has a black negative space around it
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Snip - (7) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/f7176ae2-8457-487d-9158-8e076eaa8862)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
Can't update via supportal, we'll need to run a CQ to set the new avatar.

#### Buddy-check and run:

```sql
update nameValuePairs set value = json_replace(value, '$.avatar', 'https://d2k5nsl2zxldvw.cloudfront.net/images/expensify-iconmark-avatar-square.png') where accountID = 11665625 and name = 'expensify_personalDetails';
```

**Comment by NikkiWines** [comment]
![image](https://github.com/Expensify/App/assets/16747822/37efafc4-dcce-44ac-850a-fab0582fa366)

Query looks good 👍

**Comment by francoisl** [comment]
Would you be able to run it too please?

**Comment by NikkiWines** [comment]
Sure, done! 

```
CustomQuery
query: update nameValuePairs set value = json_replace(value, '$.avatar', 'https://d2k5nsl2zxldvw.cloudfront.net/images/expensify-iconmark-avatar-square.png') where accountID = 11665625 and name = 'expensify_personalDetails';
password: XXXXXXXX
reason: https://github.com/Expensify/App/issues/43607
connection: close
Execute? (ctrl-c to cancel)
200 OK
commitCount: 23694110961
Connection: close
nodeName: auth.db1.sjc
peekTime: 21
processTime: 634
requestID: mmkaxT
totalTime: 1114
unaccountedTime: 317
Content-Length: 2
```

**Comment by NikkiWines** [comment]
This is [fixed](https://expensify.slack.com/archives/C049HHMV9SM/p1718231561743089?thread_ts=1718200066.253569&cid=C049HHMV9SM)!

**Comment by shawnborton** [comment]
Awesome, thanks everyone!
