### ISSUE TITLE
Subscription - ExpensifyApproved! logo is missing for new expensifail accounts

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #43370
**Version Number:** 1.4.82-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Log in with a new expensifail account (applausetester+0612rbmwebnew@applause.expensifail.com)
3. Create a workspace
4. Navigate to https://staging.new.expensify.com/settings/subscription

## Expected Result:
The logo should be visible.

## Actual Result:
ExpensifyApproved! logo is missing for new expensifail accounts,

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/e0bf8fc7-426c-4e71-b037-47a9f5149271

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@sonialiap FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
@sonialiap Got it, we are not sure how to make an account as ExpensifyApproved. Could you help us?

**Comment by sonialiap** [comment]
@kavimuru the steps in [this SO](https://stackoverflowteams.com/c/expensify/questions/15562) should do the trick. If you can't access the tool, let me know which account you'd like to have the EA! applied to and I get set it for you

**Comment by kavimuru** [comment]
@sonialiap I don't have access to the tool. Could you make it "ExpensifyApproved" this account applausetester+0612rbmwebnew@applause.expensifail.com?

**Comment by sonialiap** [comment]
@kavimuru added 🎉  I can see it's labeled as AE! in supportal now. Let me know if you're not seeing the logo in ND as expected 

<img width="822" alt="image" src="https://github.com/Expensify/App/assets/17131195/32c4be39-668a-438f-a1db-5007726d6182">

**Comment by kavimuru** [comment]
@sonialiap Tester can see the logo now.
![Capture](https://github.com/Expensify/App/assets/43996225/9921fd34-c4d9-433e-a45e-632058864cb8)

**Comment by sonialiap** [comment]
Great, thanks for re-testing. Closing issue since it seems to be working as expected
