### ISSUE TITLE
[HOLD #44269] HIGH: [API] Multiple redundant ReconnectApp calls upon waking client

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#43639]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.82-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1718128174597309

## Action Performed:
Break down in numbered steps

1. Open NewDot in a chat or in a room
2. Open the Network console
3. Close your laptop lid
4. Wait for 10-15 seconds
5. Open the lid

## Expected Result:
> Describe what you think should've happened

There should be one ReconnectApp call upon waking the client

## Actual Result:
> Describe what actually happened

The client queues multiple, successive ReconnectApp calls 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Image](https://github.com/Expensify/App/assets/46995600/7f5e4d41-f0df-4a82-a29a-b2ff029d2078)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jjcoffee** [comment]
I believe this will be handled in https://github.com/Expensify/App/issues/43089

**Comment by thienlnam** [comment]
Will be able to start investigating next week - I have a suspicious this is related to the useNetwork hook. When I open my laptop lid from sleep, I consistently see the offline indicator for a moment and and then will see that it resolves

**Comment by adelekennedy** [comment]
I've experienced this as well @thienlnam!

**Comment by thienlnam** [comment]
Been testing a few things that haven't been successful - I still think the issue is around how waking up after sleep the network is temporarily unstable and we shoot off the duplicated call in the beginning

**Comment by adelekennedy** [comment]
@thienlnam is there anything that external contributors can help with here? I'm guessing `no` at the moment

**Comment by thienlnam** [comment]
This is actually likely a problem that can be solved externally. 

We call ReconnectApp because the network on wake is unstable, but it doesn't seem like we have a mechanism to prevent calling this again even if the passed initialLastUpdateIDAppliedToClient is the same. 

I'm not too familiar with the SequentialQueue, so this is perhaps something we could get a contributor to look into in #newdot-quality

**Comment by thienlnam** [comment]
Discussion [here](https://expensify.slack.com/archives/C05LX9D6E07/p1718128174597309), this likely has the same root cause as [this](https://github.com/Expensify/App/issues/44269) so we'll hold for that

**Comment by adelekennedy** [comment]
Still on hold!

**Comment by adelekennedy** [comment]
https://github.com/Expensify/App/issues/44269 is still in progress

**Comment by thienlnam** [comment]
https://github.com/Expensify/App/issues/44269 is still in progress

**Comment by muttmuure** [comment]
I think let's close this for focus as the linked issue is the stated root cause.
