### ISSUE TITLE
[HOLD] Have GL/Payroll/Tax Code fetures redirtect to the upgrade flow for Collect customers

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#43640]
Per our new strategy, Control features will be visible for Collect customers. On click, this features will redirect them to the upgrade flow, so they can upgrade to Control and enable them.

Currently, we are hiding this features, as the upgrade flow is in the works. We need to update them once the flow is available.

Upgrade flow tracking issue [here](https://github.com/Expensify/Expensify/issues/391954)

**Comment by lschurr** [comment]
On hold

**Comment by lschurr** [comment]
Hold

**Comment by lschurr** [comment]
Hold

**Comment by lschurr** [comment]
On hold

**Comment by JmillsExpensify** [comment]
@garrettmknight can't we remove the hold on this issue?

**Comment by garrettmknight** [comment]
Just confirmed that this is already live on staging and prod.
