### ISSUE TITLE
[HOLD for payment 2024-07-02] [HOLD for payment 2024-06-28] [HOLD for payment 2024-06-28] MEDIUM: Enable Function Symbolication for Detailed Performance Tracing

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#43649]
# Problem

Without symbols in our profile traces we can only guess which functions took so much time, based on the bottom-up stack (and try to manually map the amount of loops & internals to what we have in code).

# Solution

Properly symbolicate the data in the performance profile feature into human-readable function names, line numbers, and file names so our team can identify the cause of slows in app.

**Comment by muttmuure** [comment]
@grgia I think this is likely one that an agency contributor will need to take the lead on.

@Szymon20000 @adhorodyski can you give us a path forward on achieving symbolication in our current profile tracing?

**Comment by adhorodyski** [comment]
@Szymon20000 as far as I remember the ones we used to receive with different bug reports were already symbolicated correctly. 

Do you think anything could have changed in this regard lately for the [`react-native-release-profiler`](https://github.com/margelo/react-native-release-profiler)?

Here's one from 1 day ago that I couldn't symbolicate myself against latest `main` (same on @hurali97's end):
[Profile_trace_for_1.4.81-9.cpuprofile](https://github.com/user-attachments/files/15820240/Profile_trace_for_1.4.81-9.cpuprofile)

And that's the same one after matching it against this branch:
![image](https://github.com/Expensify/App/assets/42047036/9d1e20eb-4826-4357-b38f-ad3c1ddd5727)

**Comment by hannojg** [comment]
The traces we record on the device are unsymbolicated. We need a way to symbolicate them. The flow would be:

1. A user shares a profile trace
2. A developer receives the trace
3. The developer runs a script to symbolicate it

We already have a script for symbolication in place. The issue however is that the profile the user created is specific to an app version. And the script only symbolicates for the current commit we are on.
Additionally, switching versions as developer just to symbolicate the trace is quite the overhead (as a new release build needs to be created).

So a better solution would be to:

1. Add a GitHub action that runs when we create a new release version and uploads it as artefact to the GitHub action workflow run.
2. Update our script to:
 1. Get the app version from the file name of the trace
 2. Download the artefact from the GitHub action runs for that version

I can help with implementing that.

**Comment by grgia** [comment]
@hannojg, thanks for looking into this. Shall I assign you this one?

**Comment by hannojg** [comment]
Yes please, I'd go ahead and create two PRs, that will:

1. Upload a source map when we make a new release version
2. Update our scripts (and documentation) for symbolicating a trace using the uploaded source maps

**Comment by hannojg** [comment]
Update for step 1 uploading the source maps:

- I found that we already upload source maps, support was added in 
  - https://github.com/Expensify/App/pull/9641
- However, its broken and not uploading for android and iOS
- Additionally it would be nice if we can link the assets with the tag (have to see if that works)

So I will fix the existing system first

![Screenshot 2024-06-17 at 10 18 41](https://github.com/Expensify/App/assets/16821682/85d658ed-8392-4e0e-a8dc-6b82b0f04c2a)

**Comment by hannojg** [comment]
@grgia First PR for fixing the upload of source maps is up, can you help me get it merged? Thanks! 😊 

- https://github.com/Expensify/App/pull/43823

**Comment by hannojg** [comment]
@grgia The next PR is ready:

- https://github.com/Expensify/App/pull/43894

A script was added that can be used to easily symbolicate cpu profiles

**Comment by hannojg** [comment]
Two things:

- The first PR was reverted as it seemed to have cause build issues on iOS, will create a new one
- For the second PR that introduces the symbolicate script: I found a better way to get the source map artifact from GitHub. Will mark the PR as ready once I incorporated these changes

**Comment by hannojg** [comment]
PR for uploading source maps is good again:

- https://github.com/Expensify/App/pull/43999

**Comment by hannojg** [comment]
Second one is ready as well:
- https://github.com/Expensify/App/pull/43894
