### ISSUE TITLE
Task - "EditTaskAssignee" error displayed when reassigned task offline and returned online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43643]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4622931&group_by=cases:section_id&group_order=asc&group_id=291935
**Email or phone of affected tester (no customers):** applausetester+omci51@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. [Account B] Open app
2. [Account B] Navigate to conversation with account A
3. [Account B] Create A task and assign it to yourself
4. [Account A] Open app
5. [Account A] Navigate to conversation with account B
6. [Account A] Open task report
7. [Account A] Disable internet connection
8. [Account A] Change the title, description and assignee
9. [Account A] Enable internet connection
10. [Account A] Wait for about 10-20 sec

## Expected Result:
Title, Description and Assignee should be changed

## Actual Result:
"Auth EditTaskAssignee returned an error" error message displayed and new assignee not applied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6406a93d-3542-4bd7-95dc-f31e9bfa69f2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@izarutskaya I don't have access to TestRail, but was this associated with a regression?

**Comment by jliexpensify** [comment]
Unable to repro this, closing.
