### ISSUE TITLE
Android - Notification - User receives a notification with wrong attention sound

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43653]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to a conversation that is not the one with the secondary user
2. Secondary device - Send a message to the user in the main testing device
3. Verify the user receives a notification with the attention sound (https://www.dropbox.com/scl/fo/t3j9sstsml5yofsrf26od/AIUtqgtjunDRLz8ebrbJGmc/Attention?e=1&preview=Expensify_SB_SecretHandshake_UI_Attention_Mono_240109.mp3&rlkey=dpvqt7h5xjzdsafj4ent564ne&subfolder_nav_tracking=1&dl=0
)

## Expected Result:
The user should receive a notification with the attention sound when receiving a message with the app open.
## Actual Result:
User receives a notification with wrong attention sound and sometimes no notification sound received
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/96903737-90d4-4857-bb1b-9d00ff66d5cd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by OfstadC** [comment]
Thanks for reporting! We've determined [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1718296872704419?thread_ts=1718285670.599889&cid=C01SKUP7QR0) this is likely not a priority at this time so closing this out.
