### ISSUE TITLE
Chat - First menu item in the composer is highlighted

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43659]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Tap +.

## Expected Result:
The menu item will not be highlighted by default.

## Actual Result:
The first menu item is highlighted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ca81be0b-80ed-4d4b-ab6e-d19933cf2c9f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@muttmuure I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by luacmartins** [comment]
Seems like a regression from focus trap https://github.com/Expensify/App/pull/39520

**Comment by amyevans** [comment]
Pinged in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1718285290170059

**Comment by luacmartins** [comment]
I'm gonna demote this since it doesn't break any functionality.

**Comment by jnowakow** [comment]
[PR is ready](https://github.com/Expensify/App/pull/43743)

**Comment by amyevans** [comment]
Looks like the PR with a fix was cherry-picked and @mountiny requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1718400589905769)

**Comment by amyevans** [comment]
Confirmed this is fixed on staging, closing!

**Comment by luacmartins** [comment]
@muttmuure all yours to handle payment

**Comment by mallenexpensify** [comment]
Contributor+: @parasharrajat due $250 via NewDot

 TestRail 
- https://github.com/Expensify/Expensify/issues/413146

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
