### ISSUE TITLE
[HOLD for payment 2024-06-28] [Free trial] Implement all Free Trials utility functions

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43668]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [ReportUtils.getChatUserForOnboarding()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.ey3mg1o08gwf)
- [ReportUtils.isChatUsedForOnboarding()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.c6woq05j7zkg)
- [ReportUtils.requiresAttentionFromCurrentUser()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.nd837u457bd5)
- [SubscriptionUtils.calculateRemainingFreeTrialDays()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.hjr7jhxh75hh)
- [SubscriptionUtils.isUserOnFreeTrial()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.bh4x8dprf7d8)
- [SubscriptionUtils.hasUserFreeTrialEnded()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.htqt5kxcrs3d)
- [SubscriptionUtils.doesUserHavePaymentCardAdded()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.ffl93ra26663)
- [SubscriptionUtils.shouldRestrictUserBillableActions()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.h9x8t8t11eoq)
- [ReportUtils.findPolicyExpenseChatByPolicyID()](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.hk0l2buborah)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by MitchExpensify** [comment]
cc @fabioh8010 @pac-guerreiro as you'll be picking this up

**Comment by fabioh8010** [comment]
Hi, I'm Fábio - expert agency contributor - and I would like to work on this issue.

**Comment by fabioh8010** [comment]
PR is up -> https://github.com/Expensify/App/pull/43844

**Comment by fabioh8010** [comment]
@hoangzinh That is correct, should be `ReportUtils.getChatUsedForOnboarding()`

**Comment by trjExpensify** [comment]
This is a top priority for the Summer release, putting the issue on `Daily`.

**Comment by trjExpensify** [comment]
Deployed to staging, nice!

**Comment by bfitzexpensify** [comment]
Switching this to daily to action on Friday

**Comment by bfitzexpensify** [comment]
Offers sent @hoangzinh @rojiphil

**Comment by bfitzexpensify** [comment]
Thanks for the quick action - payments all complete, closing this out.
