### ISSUE TITLE
[HOLD for payment 2024-07-10] [Free trial] Implement Restricted Action screen

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43673]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [Implement Restricted Action screen](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.t75pqb78akln) ([GH](https://github.com/Expensify/Expensify/issues/400484))

cc @fabioh8010 @pac-guerreiro as you'll be picking this up

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by pac-guerreiro** [comment]
@chiragsalian @MitchExpensify 
The PR is ready to be reviewed 😄

**Comment by MitchExpensify** [comment]
**Payment summary:**

- $250 @hoangzinh requires payment (Needs manual offer from BZ)
- $250 @pac-guerreiro does not require payment (Contractor)

Does this look correct to you @hoangzinh ?

**Comment by MitchExpensify** [comment]
Offer sent here https://www.upwork.com/jobs/~017106bd9a841cc837 @hoangzinh
