### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$250] [Report Fields] [External] Add Report fields to the More features page and add support for disabling the feature

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43678]
[Main tracking issue].(https://github.com/Expensify/Expensify/issues/365155)

[Design doc link](https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit). 

Implement the following section of the design doc: https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit#bookmark=id.tx48k1sjd9mh

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01317dc8ca55728b5c</li>
        <li>Upwork Job ID: 1801290533705828644</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102737559</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
I've opened the PR for review.

**Comment by rushatgabhane** [comment]
PR reviewed

**Comment by rushatgabhane** [comment]
@mountiny should i add regression steps? Or is it handled in some other process for new features?

**Comment by sonialiap** [comment]
@rushatgabhane not sure what's up with the automation but if you could add the regression steps, that would be super!

**Comment by mountiny** [comment]
@rushatgabhane I think we are going to handle adding the regression steps in later phase all in one go

**Comment by sonialiap** [comment]
@rushatgabhane reviewer $250 - please request in ND
@shubham1206agra reviewer $250 - [offer](https://www.upwork.com/nx/wm/offer/102737559) in Upwork, please accept

**Comment by rushatgabhane** [comment]
@shubham1206agra it's one issue at a time because it's just PR review

**Comment by rushatgabhane** [comment]
@shubham1206agra there was one only reviewer for this issue (me)  :)

@sonialiap @shubham1206agra doesn't require payment for this issue

**Comment by rushatgabhane** [comment]
@shubham1206agra no we had talked about this when assigned. one issue each

**Comment by rushatgabhane** [comment]
anyway, please correct me if im wrong

**Comment by rushatgabhane** [comment]
ohhh im so sorry

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by rushatgabhane** [comment]
sorry for the confusion here

**Comment by sonialiap** [comment]
Postponing payments until end of project https://github.com/Expensify/App/issues/43678#issuecomment-2206093065
Payment summary edited https://github.com/Expensify/App/issues/43678#issuecomment-2205949197

@mountiny fyi, Rushat has already been paid for this review

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/137586a2-e89b-4a19-ac96-cf218fbe45c5">
