### ISSUE TITLE
 Login – Long loading indicator appears when login from public room via magic link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43675]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A 
**Email or phone of affected tester (no customers):** ponikarchuks+12@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out
3. Navigate via public room link (My room URL: https://staging.new.expensify.com/r/8661824749067368
)
4. Click on sign in button
5. Enter email
6. Open link from email in another tab and change to staging

## Expected Result:
Abracadabra page appears

## Actual Result:
Abracadabra page appears briefly and long loading indicator appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/25be39a3-191b-44c7-a9a4-01d49e305891

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
Closing this for now as it's a minor annoyance and doesn't directly relate to anything on our roadmap
