### ISSUE TITLE
[PAID] [Free trial] Implement and show Free Trial banner and badges in the App after Free Trial starts

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43672]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [Implement and show Free Trial banner and badges in the App after Free Trial starts](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.bjo9d2xw12n3) 
- [Notify the user that the Free Trial has started in Expensify DM or Concierge DM chat](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.a16z6zt9oetv)
- [Show Free Trial banner in Subscription's Payments Card](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.70ubavlt8ei8)
- [Show Free Trial badge in Expensify DM or Concierge DM's chat row](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.cg73p3apod9l)
- [Show Free Trial badge in Expensify DM or Concierge DM's chat header](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.z7d920rjlk7u)
- [Show Free Trial badge in Subscription's menu item](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.in5b2nz2x1t3)

cc @fabioh8010 @pac-guerreiro as you'll be picking this up

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by trjExpensify** [comment]
Assigned you @pac-guerreiro, also taking the issue off hold as the PR for #43668 is deployed to staging.

**Comment by pac-guerreiro** [comment]
@trjExpensify @hoangzinh PR is ready now - https://github.com/Expensify/App/pull/44371 😄

**Comment by trjExpensify** [comment]
Wahoo, let's go!

**Comment by strepanier03** [comment]
Offers were sent out and once they're accepted and the reg test step above is complete I can pay them out and close the contracts. Will check again tomorrow.

**Comment by rojiphil** [comment]
@strepanier03 No payment to me as I did not get involved here.

**Comment by strepanier03** [comment]
I've paid @hoangzinh and canceled the contract I mistakenly sent to @rojiphil.
