### ISSUE TITLE
[HOLD for payment 2024-07-02][Free trial] Implement and show Pre-Trial banner in the App during Pre-Trial

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43670]
This covers this section of the doc:

- [Implement and show Pre-Trial banner in the App during Pre-Trial](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.evbbtr5aze3p) 
- [Show Pre-Trial banner in Subscription's Payments Card](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.lldyzai9bgtt)

cc @fabioh8010 @pac-guerreiro as you'll be picking this up

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio - expert agency contributor - and I would like to work on this issue.

**Comment by rojiphil** [comment]
@MitchExpensify @mallenexpensify I can pick this up for review when PR is up

**Comment by luacmartins** [comment]
PR was deployed to prod 2 days ago. Updated the title to include the payment due date.

**Comment by sakluger** [comment]
@mallenexpensify I have a payment issue ([GH](https://github.com/Expensify/App/issues/44110)) for the same PR. Should I handle payment there or will you be handling it here?

**Comment by mallenexpensify** [comment]
I wonder if that was created because this one doesn't have `External`? ¯\_(ツ)_/¯
I think you can close yours and I'll take care of here.  Coincidentally, @rojiphil and I are talking about compensation for the `free trial` issues, we'll use this as an example.

**Comment by sakluger** [comment]
Cool, thanks @mallenexpensify! I'll close mine.

**Comment by mallenexpensify** [comment]
@rojiphil can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~018397fa4a91e2bc9b

**Comment by rojiphil** [comment]
> can you please accept the job and reply here once you have?

@mallenexpensify Accepted. Thanks.

**Comment by mallenexpensify** [comment]
Contributor+: @rojiphil paid $250 via Upwork. 

I'm assuming that the test cases for this new feature will all be added as part of the project process.
