### ISSUE TITLE
[Free trial] [Hold for #43697] Update the message sent after workspace creation and Guide assignment, in #admins

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43676]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.o46nxm34vyoq

**Comment by trjExpensify** [comment]
Issue is now off hold, will discuss in thread who's picking it up.

**Comment by trjExpensify** [comment]
Comment [here](https://expensify.slack.com/archives/C036QM0SLJK/p1718966632431869?thread_ts=1718718942.325429&cid=C036QM0SLJK), I think this is probably internal.

**Comment by MitchExpensify** [comment]
I agree we should hold on https://github.com/Expensify/App/issues/43697

I can create the Web-E PR for this change

**Comment by MitchExpensify** [comment]
Not overdue, Melvin

**Comment by MitchExpensify** [comment]
New copy:

> **Let's get you set up on Expensify**
> 
> Hi there 👋, I'm your dedicated setup specialist. I look forward to helping you explore and configure Expensify during a free trial! A few important things to mention:
> 
> - Your workspace has a ton of custom settings, just select your workspace settings to set it up.
> - You’ve got more functionality to enable, like custom categories, tags, etc. Just ask me how. 
> 
> Chat with me here in your #admins room or just reply to this message. You can also [schedule a call ](https://calendly.com/expensify-paige-smith)if you have more in-depth questions. Talk soon!


The current copy lives here I believe: https://github.com/Expensify/Web-Expensify/blob/ec2f1a5b3340984a3763cd6703715eda6b7b9864/lib/Policy/Utils.php

**Comment by MitchExpensify** [comment]
https://github.com/Expensify/Web-Expensify/blob/main/script/bwm/SendAssignedGuideMessaging.php

**Comment by MitchExpensify** [comment]
Merged, not overdue

**Comment by MitchExpensify** [comment]
On prod, closing
