### ISSUE TITLE
[HOLD for payment 2024-07-17] [$750] [Free trial] Restrict actions throughout the App of "past due" billing owner

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43674]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

-  [Restrict actions throughout the App of "past due" billing owner](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.rxn60kqi4ywm) 

cc @fabioh8010 @pac-guerreiro as you'll be picking this up

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio - expert agency contributor - and I would like to work on this issue.

**Comment by twisterdotcom** [comment]
@MitchExpensify right now we have @rojiphil and @hoangzinh - is one of them the Contributor, or are they both C+ and we can assign @fabioh8010?

**Comment by rojiphil** [comment]
Me and @hoangzinh are both C+ assigned to this project. But one of us has to take this up. 
Callstack is implementing this project as mentioned [here](https://github.com/Expensify/App/issues/43674#issue-2351496438). So we can assign @fabioh8010

**Comment by rojiphil** [comment]
@fabioh8010 Don't we have to wait until #43672 is done to work on this? Or are we taking this up for implementation now?

**Comment by fabioh8010** [comment]
Actually this one would be HOLD on https://github.com/Expensify/App/issues/43668 and https://github.com/Expensify/App/issues/43673, since the first one is merged and [Restricted Action is close to be merged](https://github.com/Expensify/App/pull/43855) I will start my work on top of it, so I think this GH issue title was wrong.

**Comment by rojiphil** [comment]
> Actually this one would be HOLD on https://github.com/Expensify/App/issues/43668 and https://github.com/Expensify/App/issues/43673, since the first one is merged and https://github.com/Expensify/App/pull/43855 I will start my work on top of it

Cool. That make sense. 
@MitchExpensify I can take this up as C+ here.

**Comment by trjExpensify** [comment]
Updating the title to reflect the hold on https://github.com/Expensify/App/issues/43673

**Comment by trjExpensify** [comment]
The PR for https://github.com/Expensify/App/issues/43673 has been deployed, removed the hold.

**Comment by rojiphil** [comment]
@twisterdotcom I think the work in this issue deserves an increase in compensation:

Reasonings:
1. The PR took more time than the usual one or two rounds of testing as the scope involved too many tests (as described [here](https://github.com/Expensify/App/pull/44393#issue-2372782816))
2. Though not directly related to this issue, we addressed a related navigation issue on navigating back/away from the restricted actions view as mentioned [here](https://github.com/Expensify/App/pull/44393#discussion_r1659254359)
3. Identified and supported an additional case [here](https://github.com/Expensify/App/pull/44393#issuecomment-2197503754) which was not identified yet in the design document

$750 is reasonable here. What do you think?

**Comment by twisterdotcom** [comment]
I'm happy with that, sure.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @fabioh8010 **does not** require payment (Contractor)

**Comment by twisterdotcom** [comment]
Payment Summary:

- @rojiphil paid $750 [here](https://www.upwork.com/nx/wm/offer/103170243) (C+)
- @fabioh8010 **does not** require payment (Contractor)
