### ISSUE TITLE
[HOLD for payment 2024-07-24] [Free trial] Implement and show Trial Ended banner, Expensify DM GBR and custom Expensify DM chat item in the App after Free Trial ends

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43671]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [Implement and show Trial Ended banner, Expensify DM GBR and custom Expensify DM chat item in the App after Free Trial ends](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.o7pj57n5s3a) 
- [Notify the user that the Free Trial has ended in Expensify DM or Concierge DM’s chat](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.5cqwme9fymce)
- [Show Trial Ended banner to Payments card](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.f9pr5ggcqcu6)
- [Hide Free Trial badges throughout the App](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.g5cglc3he9pq)
- [Show GBR in Expensify DM or Concierge DM’s chat row](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#heading=h.ktrpf2406rqi)

cc @fabioh8010 @pac-guerreiro as you'll be picking this up

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by sakluger** [comment]
Sounds like this will be handled internally - I asked @MitchExpensify to confirm.

**Comment by trjExpensify** [comment]
Hm, this is a frontend issue isn't it?

**Comment by fabioh8010** [comment]
@trjExpensify Yes, it's frontend issue

**Comment by sakluger** [comment]
Ah sorry, @fabioh8010 and @pac-guerreiro are both from Callstack and will be working on all Free Trial related projects.

@fabioh8010 and @pac-guerreiro, will both of you be working on this GH issue or just one of you? And will there be one or multiple PRs?

Thanks!

**Comment by fabioh8010** [comment]
@sakluger  Just one of us, and will probably be one PR.

**Comment by trjExpensify** [comment]
Put this on hold for https://github.com/Expensify/App/issues/43672 where we'll first tackle the logic for when a free trial starts, before here and when a free trial ends.

**Comment by sakluger** [comment]
Thanks for clarifying, @fabioh8010. Let me know once you are ready for one of you to take it so that I can reassign the issue if needed.

**Comment by sakluger** [comment]
I'm going to move this to weekly while we wait for the hold issue to be completed.

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by rojiphil** [comment]
@trjExpensify @sakluger And I can pick this up for review as C+

**Comment by trjExpensify** [comment]
Awesome!

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @pac-guerreiro - no payment required (Contractor)
Contributor+: @rojiphil $250, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/103240375

**Comment by rojiphil** [comment]
> sent offer via Upwork: https://www.upwork.com/nx/wm/offer/103240375

@sakluger Accepted the offer. Thanks.

**Comment by sakluger** [comment]
Great, thanks! Payment is complete.
