### ISSUE TITLE
[$250] [Report Fields] [External] Implement support for bulk operations on the policy report fields 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43687]
[Main tracking issue].(https://github.com/Expensify/Expensify/issues/365155)

[Design doc link](https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit). 

Implement the following section of the design doc: https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit#bookmark=kix.8i58qd8al9b1

On hold for all the creation/ edit flows
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018997f193e40c0a99</li>
        <li>Upwork Job ID: 1801290913505042433</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 102737561</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by adelekennedy** [comment]
@mountiny we're still on hold here? I saw that you've moved into implementation

**Comment by mountiny** [comment]
Still on hold for this one

**Comment by mountiny** [comment]
This is off hold and Artem is working on it

**Comment by rushatgabhane** [comment]
PR on production
