### ISSUE TITLE
[Report Fields] [External] Disable changes to report fields when accounting integration is connected

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43683]
[Main tracking issue].(https://github.com/Expensify/Expensify/issues/365155)

[Design doc link](https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit). 

Implement the following section of the design doc: https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit#bookmark=id.dbhzh2rxut3y

This might be intertwined with the other sections too

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by mountiny** [comment]
@rezkiy37 will work on this one this week

**Comment by mountiny** [comment]
WIP PR is raised

**Comment by rezkiy37** [comment]
Working on the issue.

**Comment by rezkiy37** [comment]
I've opened the PR (https://github.com/Expensify/App/pull/44672) for review 🙂

**Comment by mountiny** [comment]
I believe this is done now too
