### ISSUE TITLE
[Report Fields] [Clean-up] Remove the reportFieldsFeature beta when this is released

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43688]
[Main tracking issue].(https://github.com/Expensify/Expensify/issues/365155)

[Design doc link](https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit). 

Remove the canUseReportFieldsFeature beta once the feature is implemented in the app

**Comment by mountiny** [comment]
Getting closer

**Comment by JmillsExpensify** [comment]
Let's remove the beta when you get a chance.

**Comment by mountiny** [comment]
Discussing if we are happy to remove it

**Comment by mountiny** [comment]
Merged and done
