### ISSUE TITLE
[Report Fields] Ensure we use correct default for the areReportFieldsEnabled when the flag is not defined in getAsOnyxUpdate

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43681]
[Main tracking issue].(https://github.com/Expensify/Expensify/issues/365155)

[Design doc link](https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit). 

Implement the following section of the design doc: https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit#bookmark=id.wdwsqekhx2rr

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by mountiny** [comment]
Looking into this one today

**Comment by mountiny** [comment]
PR is up in a review

**Comment by mountiny** [comment]
Merged

**Comment by JmillsExpensify** [comment]
Should this issue be closed?

**Comment by mountiny** [comment]
Yes this can be closed
