### ISSUE TITLE
[Report Fields] Create alias commands for changing the report fields

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43682]
[Main tracking issue].(https://github.com/Expensify/Expensify/issues/365155)

[Design doc link](https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit). 

Implement the following section of the design doc: https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit#bookmark=id.7hidf5lbeld3

As part of this issue, let's also handle this section https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit#bookmark=id.w1062ktz9pbp

<details><summary>Issue Owner</summary>Current Issue Owner: @mountiny</details>

**Comment by mountiny** [comment]
Looking into this one today

**Comment by mountiny** [comment]
Got a draft going for this one

**Comment by JmillsExpensify** [comment]
Any remaining PRs for this doc?

**Comment by mountiny** [comment]
All aliases are created, last pending piece is to make sure the report fields are deleted and or disabled based on its type when the feature is turned off

**Comment by mountiny** [comment]
One change still pending for deleting the report fields when the feature is disabled

**Comment by mountiny** [comment]
Still need to handle this one, focusing on the workspace feeds

**Comment by mountiny** [comment]
I was ooo, will tackle this one
