### ISSUE TITLE
[Free trial] [BE] Inform workspace owner when free trial has begun via onyxUpdates

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43695]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [[BE] Inform workspace owner when free trial has begun via onyxUpdates](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.mam2d5ggmi2i)

**Comment by chiragsalian** [comment]
Just tested after making backend changes and this is not needed since the relevant changes for workspace owner are addressed in this issue - https://github.com/Expensify/App/issues/43703.
