### ISSUE TITLE
[Free trial] [BE] Send a message when free trial has ended

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43694]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [[BE] Send a message when free trial has ended](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.2mq3tmhgmq8l)

**Comment by muttmuure** [comment]
@MitchExpensify Is this ready to get assigned out yet? Seems like it might be?

**Comment by MitchExpensify** [comment]
Yes this is ready @muttmuure!

**Comment by muttmuure** [comment]
PR is open

**Comment by trjExpensify** [comment]
I don't think it is, we're waiting on a Web PR for this I believe.
