### ISSUE TITLE
[Free trial] [BE] Update free trial to begin on billable action - Submitting a request

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43698]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [BE] Update free trial to begin on billable action - Submitting a request](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.kyce1ujo0rxj)

**Comment by chiragsalian** [comment]
Closing, we only need this [one](https://github.com/Expensify/App/issues/43697)
