### ISSUE TITLE
[Free trial] [BE] Update free trial to begin on billable action

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43697]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=kix.voevm28ra7yb):

- [[BE] Update free trial to begin on billable action](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=kix.voevm28ra7yb)

<details><summary>Issue Owner</summary>Current Issue Owner: @chiragsalian</details>

**Comment by trjExpensify** [comment]
Ah nice job, consolidating @chiragsalian! :)

**Comment by VictoriaExpensify** [comment]
Waiting for an engineer

**Comment by chiragsalian** [comment]
Not overdue, I'm currently working on this.

**Comment by chiragsalian** [comment]
Done
