### ISSUE TITLE
[Free trial] [BE] Update free trial to begin on billable action - Paying a report

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43701]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [[BE] Update free trial to begin on billable action - Paying a report](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.kyce1ujo0rxj)

**Comment by trjExpensify** [comment]
Commented [here](https://expensify.slack.com/archives/C036QM0SLJK/p1718966632431869?thread_ts=1718718942.325429&cid=C036QM0SLJK), I'm wondering if this should be consolidated with #43697. CC: @chiragsalian @MitchExpensify

**Comment by chiragsalian** [comment]
Yup this can be closed and consolidated into this one https://github.com/Expensify/App/issues/43697. Closing.
