### ISSUE TITLE
[Free trial] [BE] Remove setting free trial when policy is created

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43704]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [[BE] [HOLD until others are done] Remove setting free trial when policy is created](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.4o9puouqyofz)

**Comment by CortneyOfstad** [comment]
@MitchExpensify — anything needed from me at this stage?

**Comment by MitchExpensify** [comment]
Not right now! Once the PR is deployed we'll need help issuing payment

**Comment by CortneyOfstad** [comment]
Not overdue!

**Comment by CortneyOfstad** [comment]
@MitchExpensify is [this the PR](https://github.com/Expensify/Auth/pull/11438) I should be focusing on? Or is there another PR?

Thanks!

**Comment by trjExpensify** [comment]
Another PR will come for this, right @chiragsalian? It'll be the last one to roll this out. I think only backend as well, so there likely won't be any payouts you need to make -- but we'll see.

**Comment by chiragsalian** [comment]
Yeah just one backend PR for this. I'll assign it to myself to prevent any noise. Basically once we test the feature then I'll work on this.

**Comment by chiragsalian** [comment]
We tested the feature today and so this is off hold now.

**Comment by chiragsalian** [comment]
oh this isn't live yet

**Comment by trjExpensify** [comment]
Can't you close this, Chirag?

**Comment by chiragsalian** [comment]
Yup this is done.
