### ISSUE TITLE
[Free trial] [BE] Send free trial NVP for NewDot

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#43703]
This covers this section of the [design doc](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit):

- [[BE] Send free trial NVP for NewDot](https://docs.google.com/document/d/1skGyubv96LtirPTiCQC41jT6b65UCh0M6y_J3acqVAY/edit#bookmark=id.p11ywrnfnz4m)

**Comment by laurenreidexpensify** [comment]
@greg-schroeder adding you as the BZ here for parental leave sub, assuming there is payment required at some point. @MitchExpensify will be able to add more context. Thanks

**Comment by chiragsalian** [comment]
This is live. Closing.
