### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] mWeb – Chat – Workspace switcher is with blue border after login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43713]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out
3. Log in
4. Observe Workspace switcher in the left top part

## Expected Result:
Workspace switcher is without blue border after login

## Actual Result:
Workspace switcher is with blue border after login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/239dba7c-f1c6-433a-9880-d323a0beac12

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140196526c3a485da</li>
        <li>Upwork Job ID: 1803111339129290564</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103161579</li>
<li>tsa321 | Contributor | 103161581</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment]
@tylerkaraszewski  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by tylerkaraszewski** [comment]
I can't reproduce this.


https://github.com/Expensify/App/assets/705000/9698abed-9a88-44d8-a622-b7b36532bf3a

**Comment by luacmartins** [comment]
This is likely coming from https://github.com/Expensify/App/pull/39520. It's really minor though

**Comment by luacmartins** [comment]
@lanitochka17 can you ask for a re-test? In the meantime, I'll demote this to NAB since it doesn't break any features.

**Comment by tsa321** [comment]
Same root cause of this issue https://github.com/Expensify/App/issues/43662

We need to add the coresponding screen (maybe SCREENS.HOME in this issue) in SCREENS_WITH_AUTOFOCUS.
Cross posting my [proposal](https://github.com/Expensify/App/issues/43662#issuecomment-2167042250) from the other issue.

**Comment by lanitochka17** [comment]
Issue is still reproducible on the mWeb/Chrome

https://github.com/Expensify/App/assets/78819774/0a2c0760-26a0-4fb2-8ca6-ac8f45fcde1a

**Comment by tylerkaraszewski** [comment]
I am going to mark this external and get a C+ for it.

**Comment by tsa321** [comment]
@hoangzinh I believe the way the `FocusTrap` works to determine whether should  focus first element on new screen or not is: 
By checking last event from previous screen: if the last event is keyboard keypress/down event the FocusTrap will focus first (tabable) element, if last event of previous screen is mouse click then FocusTrap won't focus the first element.

You can confirm this by removing `initalFocus` property in here:

https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L51-L56

Then press `+` FAB button -> click `Split expense` -> press any keyboard key for example `a` or `b`, etc.
Notice the blue rectangle appears shortly before the focus move to amount text input.

But if you don't press keyboard key the blue rectangle border won't show up.

In case of sign in, if you enter 1 wrong code then click on sign in button the blue border of workspace switcher won't show  up.
But if you entering the 6 magic code correctly and don't click sign in button the blue border will show up.

**Comment by tylerkaraszewski** [comment]
Thoughts @hoangzinh ?

**Comment by tsa321** [comment]
@hoangzinh Edit: it is not SCREEN HOME but it is NAVIGATORS.BOTTOM_TAB_NAVIGATOR

**Comment by tsa321** [comment]
@hoangzinh How about disabling tabbed navigation for users with small screens, as their keyboards lack a tab key? Another solution could be checking if the last key pressed was the Enter key or not.

**Comment by tsa321** [comment]
> It's exclusively, in case if we want focusTrap on other screens elsewhere

@hoangzinh Would there be any issues with disabling the focus trap for users with small screens, given that their keyboards lack a tab key?

**Comment by tylerkaraszewski** [comment]
Still no good proposals for this I guess.

**Comment by tylerkaraszewski** [comment]
It's not overdue, it's been commented on.

**Comment by tsa321** [comment]
@hoangzinh because the `WorkspaceSwitcherButton` is in here:

https://github.com/Expensify/App/blob/15e67a0d8e2b689f244274cc2a7e4b012ca07ba0/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx#L46

in the BottomTabNavigator region. I have tried screen home and it doesn't work.

**Comment by tsa321** [comment]
@hoangzinh the initialRouteName is NAVIGATORS.BOTTOM_TAB_NAVIGATOR as shown in the linkingConfig:

https://github.com/Expensify/App/blob/c973e622ac7bf94a537b01e75408aff782123db3/src/libs/Navigation/linkingConfig/config.ts#L10

**Comment by tsa321** [comment]
@hoangzinh Essentially, I am console logging the route name in the focus trap for the screen. The route names displayed are "navigators bottom tab" and "screen home." However, "screen home" doesn't prevent initial focus on that page. Therefore, the correct route name should be "navigators bottom tab."

**Comment by tsa321** [comment]
@hoangzinh, no, it's not a bug with navigation.

If the route is home:

https://github.com/Expensify/App/blob/4ae133db275f32b59592e40a54ef6727c8f4891e/src/libs/Navigation/AppNavigator/Navigators/BottomTabNavigator.tsx#L41-L43

the SidebarScreen is displayed. The SidebarScreen is a component of `Tab.Screen` with the name `SCREENS.HOME` in `bottomTabNavigator`. The `Tab` is inside the `createCustomBottomTabNavigator` function:

https://github.com/Expensify/App/blob/4ae133db275f32b59592e40a54ef6727c8f4891e/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/index.tsx#L49-L54

which includes `ScreenWrapper`.

So, when the route is Home, there are two screens: one from `createCustomBottomTabNavigator` and one from `SidebarScreen`, which is the component of the `Tab.Screen` for Home.

The focus trap is attached to `ScreenWrapper`, resulting in two focus traps. To disable the initial focus on the Workspace switcher, we must disable the initial focus for both of these screens. 

The focus trap for Home is already disabled here:

https://github.com/Expensify/App/blob/4ae133db275f32b59592e40a54ef6727c8f4891e/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L22-L25

However, the `trapFocus` for `BottomTabNavigator` is not yet disabled.

Therefore, the solution is the same as my proposal or you could include the `BottomTabNavigator` inside `BOTTOM_TAB_SCREENS`.

**Comment by tsa321** [comment]
@hoangzinh yes, we can do that.

**Comment by tsa321** [comment]
## Proposal

[updated](https://github.com/Expensify/App/issues/43713#issuecomment-2167047109)

@hoangzinh I have updated my proposal.

**Comment by srikarparsi** [comment]
Assigning @tsa321

**Comment by twisterdotcom** [comment]
Payment Summary:

- @hoangzinh paid $250 [here](https://www.upwork.com/nx/wm/offer/103161579) (Reviewer)
- @tsa321 paid $250 [here](https://www.upwork.com/nx/wm/offer/103161581) (Contributor)
