### ISSUE TITLE
Pusher updates are noticebley slow

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43715]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1718138311153829

## Action Performed:
1. Go to a report as a user A
2. Send a message to user B
## Expected Result:
User B receives message without significant delay
## Actual Result:
Message received with noticeable delay
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/34dfea90-8385-4991-a2ae-bd18d43c56f9

https://github.com/Expensify/App/assets/38435837/f6d61312-6ea1-4d25-8ac8-2134ce353e80

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
Only an issue on staging and it's expected.
