### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] mWeb - Login – Animation appears with delay when navigate via magic link in incognino tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43718]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.83-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4626832
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out.
3. Click on sign in button
4. Enter email.
5. Open link from email in Incognito tab and change to staging.

## Expected Result:
Here is your magic code page opens with animation

## Actual Result:
Here is your magic code page opens, but animation appears with delay

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e0ba7d26-e6ba-4d9c-b38d-e9d9cae6bcef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
Not reproducible in prod


https://github.com/Expensify/App/assets/93399543/11ce7cd9-8e56-4f52-bca9-c472c115266f

**Comment by srikarparsi** [comment]
Verified that it's reproducible on staging and not prod. Also seems to occur on safari web.

**Comment by srikarparsi** [comment]
Pretty sure it's related to this [PR](https://github.com/Expensify/App/pull/40337) @eVoloshchak @tienifr @grgia do you have any thoughts?

**Comment by shawnborton** [comment]
Yeah, I think this isn't a deploy blocker and it's fine as-is.

**Comment by srikarparsi** [comment]
We are removing the animation as per this [conversation](https://expensify.slack.com/archives/C07J32337/p1718309863929149?thread_ts=1718304026.519189&cid=C07J32337)

**Comment by srikarparsi** [comment]
No payment needed for this and it has been deployed to production. Closing this out.
