### ISSUE TITLE
Wrong attachment downloaded from report page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43729]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.83-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718299144272639

## Action Performed:
Prerequisite: Send two attachments from user A to B
1. Go to staging.new.expensify.com and login as B
2. Open the report page
3. Click on the 2nd attachment and download the file
4. Open the downloaded file
## Expected Result:
Corresponding attachment downloaded and able to view
## Actual Result:
1st attachment downloaded and displayed
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/75d941d6-b8e7-4a80-b247-159b9a92c5cc

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Not overdue

**Comment by muttmuure** [comment]
Fixed elsewhere
