### ISSUE TITLE
Categories - Categories header jumps when clicking Select after selecting categories

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43736]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories
3. Select all the categories via checkbox
4. Click Select
5. Unselect all the categories
6. Select all the categories
7. Click Select

## Expected Result:
The Categories header will not jump when clicking Select

## Actual Result:
The Categories header jumps when clicking Select

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c75b6be9-9300-407c-93d3-a24f200d7645

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@iwiznia  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM an expert agency and I'd like to work on this issue!
Btw looks like the issue is reproducible on other screens too (Tags, Members etc.)

**Comment by filip-solecki** [comment]
I am coming back with solution. [This PR](https://github.com/Expensify/App/pull/43743) solves this issue

**Comment by mountiny** [comment]
Happy to take over

**Comment by mountiny** [comment]
I have linked the PR to this task. I think we will have to be careful not to introduce other regressions with this

**Comment by mountiny** [comment]
CP is running

**Comment by mountiny** [comment]
The QA will test the PR in staging
