### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-10] [LOW] [Performance] Improve the TTI for native apps

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43746]
Coming from [here](https://expensify.slack.com/archives/C05R2V5GM1S/p1718349352473159?thread_ts=1716851858.053749&cid=C05R2V5GM1S)

### Problem

The TTI time for Android app using the heavy account is 60s. For iOS App its 16s. This would deter any user from using the App as they would not wait that long for it to start being usable

### Solution

Investigate how we can speed up the start up time for native devices

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by hurali97** [comment]
@mountiny Please assign this to me 👋

**Comment by mountiny** [comment]
@hurali97 what are the next steps?

**Comment by JmillsExpensify** [comment]
Still waiting for clarity on next steps

**Comment by mountiny** [comment]
@hurali97 is working on this one

**Comment by abdulrahuman5196** [comment]
Hi Team, I have limited availability to work on issues currently, so unassigning myself to avoid further delays and reproritize. Kindly add another C+.
@mountiny

**Comment by hungvu193** [comment]
False alert. We haven't merged our PR yet

**Comment by mountiny** [comment]
@hoangzinh @hungvu193 what is the payment summary on this one?

**Comment by JmillsExpensify** [comment]
@mountiny Can you provide a payment summary confirming that you agree?

**Comment by mountiny** [comment]
Yes that sounds good to me, thank you for you quick help on this tricky task

@hungvu193 $500 
@hoangzinh $500

**Comment by JmillsExpensify** [comment]
@hoangzinh offer sent via Upwork. @hungvu193 feel free to submit a request via NewDot.

**Comment by hungvu193** [comment]
Thanks. I'll request on NewDot later.

**Comment by JmillsExpensify** [comment]
Awesome. I've paid out the Upwork contract so we can circle back on your payment when I process in New Expensify.

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
