### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Create empty state component for list view pages

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#43747]
Right now, our empty states for certain list views look pretty underwhelming:
![image](https://github.com/Expensify/App/assets/2319350/350f7741-3fdc-41c2-9aaf-03dcc881a82d)

We want to make these empty states feel nicer by using a subtle hint that the page will eventually contain data by using a faded row pattern, while also creating space for the middle of the page to show an informative or educational modal. The component we want to build is something like this: 
![image](https://github.com/Expensify/App/assets/2319350/f0097069-7707-467b-9474-cbbebbc1060c)

![image](https://github.com/Expensify/App/assets/2319350/5ab6f26a-0532-4899-b8c6-27e0170b18d0)

Here is a video of the component in action, and you can find it in our [brand guidelines](https://www.figma.com/design/qQIIaxVUdtggrh8eg8bI5B/Brand-Guidelines-%26-Product-UI?node-id=5734-2774&t=7MK6zAAF1V7kiTjp-11) as well:

https://github.com/Expensify/App/assets/2319350/a355dafe-d97e-414d-bf37-cc57ac5caed7

The idea is this:
- the empty state can have a variety of different row styles in the background
    - table rows to match Search on desktop
    - compact rows to match Search on mobile
    - other generic row styles that our app supports elsewhere
- we should be able to decide if we want to show a static illustrated header, or if we want to pass in a video or looping GIF
- we should optionally be able to choose if we want to include a button in the empty state card or not
- we should make sure we have a good minimum and maximum height for the empty state rows so we don't get any wild, unexpected results on extreme viewport cases

Once this component is in a robust state, we'll plan to implement it on the Search page as well as some other upcoming projects like Workspace feeds. 

cc @mountiny @filip-solecki @Expensify/design  

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01809e49334f961ddd</li>
        <li>Upwork Job ID: 1801589500078964548</li>
        <li>Last Price Increase: 2024-06-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM an expert agency and I'd like to work on this issue!

**Comment by shawnborton** [comment]
@filip-solecki these are the possible skeletons that might be included in the empty state component:
![image](https://github.com/Expensify/App/assets/2319350/e79c402d-e829-4b17-ba61-09d655b8bf77)


The Search Desktop skeleton row already exists, though I am proposing that we slightly update it to have a background color as part of this [PR](https://github.com/Expensify/App/pull/43652). In that same PR, we are making the Search Mobile skeleton rows which don't exist yet. Chat rows already exist. But generic table rows do not exist to my knowledge, so we'll need to make those skeletons as part of this.

**Comment by filip-solecki** [comment]
Is there a confirmed design for any page where we can implement the new empty state component? I almost completed my work, but currently, there's no place to implement it for testing.

**Comment by filip-solecki** [comment]
cc @shawnborton @mountiny

**Comment by mountiny** [comment]
I believe we can add this to the Search page, right? @shawnborton

**Comment by filip-solecki** [comment]
So I just need confirmed design with illustration/animation/video whatever will be used there

**Comment by shawnborton** [comment]
Yup, search page will be a great place to test it out. You can start implementing it with a generic illustration (pick any existing one) and I'll follow up soon with a good one to use.

**Comment by shawnborton** [comment]
In the workspace editor, when you enable Tags or Taxes, we can use this component here too:

![CleanShot 2024-06-24 at 17 41 22@2x](https://github.com/Expensify/App/assets/2319350/89cae283-a675-49a2-beaa-b3fd2b5129db)

**Comment by filip-solecki** [comment]
Taxes cannot be empty, while enabling we are creating two default tax rates and one has to always be set as default and cannot be deleted, but Categories may be empty so I'll add it also on Tags and Categories. 
Just send me all illustrations or whatever has to be in header there.

**Comment by shawnborton** [comment]
@Expensify/design thoughts on doing something generic for these pages, like the folder illustration we currently use there?
![CleanShot 2024-06-25 at 09 29 25@2x](https://github.com/Expensify/App/assets/2319350/b814bc58-1873-49d7-8d49-55b834e32ad4)

**Comment by shawnborton** [comment]
If that works, the illustration is here: [empty-state__folder_ice.svg.zip](https://github.com/user-attachments/files/15966947/empty-state__folder_ice.svg.zip)

It should be shown at 184x112, and the background should use our yellow600 color (`#D18000`)

**Comment by filip-solecki** [comment]
PR is ready for review!

**Comment by dannymcclain** [comment]
>@Expensify/design thoughts on doing something generic for these pages, like the folder illustration we currently use there?

Yup I like that. I think that folder illustration works well as a generic empty state image for these table views.

**Comment by dubielzyk-expensify** [comment]
Dig it!

**Comment by JmillsExpensify** [comment]
Payment summary above is filled out and correct. @eVoloshchak please propose a regression test and we can get your payment approved once I receive it in NewDot. Thanks!

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Log in to the app
2. Go to Account Settings -> Workspaces
3. Select any workspace
4. Go to More Features
5. Enable Tags and Categories
6. Open Categories page and remove all categories
7. Verify there is an empty page placeholder with the following text "You haven't created any categories"
8. Go to tags, remove all tags if there are any
9. Verify there is an empty page placeholder with the following text "You haven't created any tags"

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment]
Reopening for regression test and payment summary from someone else.

**Comment by mallenexpensify** [comment]
Contributor+: @eVoloshchak owed $250 via NewDot

Test Case GH
- https://github.com/Expensify/Expensify/issues/418337

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
