### ISSUE TITLE
[HOLD for payment 2024-07-31] [$250] Billable - Billable toggle should have a locked icon in split details view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43756]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4631196
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Billable option is set to default to billable on Old Dot
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Split a manual expense with billable toggled enabled
4. Click on the split preview
5. Click on the toggle

## Expected Result:
Billable toggle should appear with a locked icon if billable toggle cannot be edited after splitting the bill

## Actual Result:
The billable toggle does not have a locked icon, is clickable but not responsive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ec4cc55d-8a87-4aa8-807f-5018a0119fc1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015cebf7a04f37f63d</li>
        <li>Upwork Job ID: 1801675898344474551</li>
        <li>Last Price Increase: 2024-06-14</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 102769577</li>
<li>Krishna2323 | Contributor | 102769579</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
@ishpaul777 please complete the checklist ASAP. I'd like to close this issue out.

**Comment by puneetlath** [comment]
Paid!
