### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] mWeb-Distance rate-From more features page tapping back directed to distance rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43755]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1. 4.83
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- Workspaces -- Workspace
3. Tap more features
4. Toggle on distance rate
5. Tap settings
6. Tap more features link
7. Tap app back button

## Expected Result:
From more features page tapping back user must be directed to settings page

## Actual Result:
From more features page tapping back user directed to distance rate instead settings

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/992778dd-b05c-43c4-b23e-a91bed2b75d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbdf127f2f018440</li>
        <li>Upwork Job ID: 1803050291810403386</li>
        <li>Last Price Increase: 2024-06-18</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 102856221</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by mananjadhav** [comment]
Will review this today. Will need to check the current navigation screens.

**Comment by mananjadhav** [comment]
I think @dominictb's solution would work using `goBack`.

🎀 👀 🎀 C+ reviewed

**Comment by mananjadhav** [comment]
This is ready for payout today @sonialiap. I checked and `goBack` logic was more like an edge case. I don't think we need a regression test for this one.

**Comment by sonialiap** [comment]
Payment summary:
- @mananjadhav $250 - please request in ND
- @dominictb $250 - paid in upwork ✔️

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav
