### ISSUE TITLE
Split bill - The split group DM disappears from LHN when user navigates away from the conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43762]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4627162
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in the App
2. Click on the + button > Split expense
3. On the scan option, upload a digital receipt that will not fail the scan
4. On the participant selection list, select 2 other participants that you don't have a group created already
5. Continue to the final review page
6. Click on the split button

## Expected Result:
When the user scans a receipt that is split with 2 or more people, a group DM should be created

## Actual Result:
The group DM disappears from LHN when user navigates away from the conversation. It appears again after log out/log in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/39d4a38e-f9fd-4a50-833b-9ab4f9d17ade

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by jliexpensify** [comment]
I cannot repro this one:

1. Original split expense with created DM

![image](https://github.com/Expensify/App/assets/30815269/cb8249da-0c95-4fe2-94b5-fc7403c8355b)

2. Search bar:

![image](https://github.com/Expensify/App/assets/30815269/374e5e02-6807-489e-ac30-1a807afb8341)
