### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] [One expense reports] Red dot on LHN does not appear for participant when create 1:1 hold expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43760]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4627347&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+a271@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Submitter
1. Create an IOU with several expenses in a 1:1 with another user you have access to
Participant
1. Log in as the other user
2. Navigate to a expense, click the three dots in the header, and choose Hold
3. Leave a hold comment and confirm

## Expected Result:
There should be a red dot on LHN on participant side

## Actual Result:
Red dot on LHN does not appear for participant when create 1:1 hold expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0c523891-6226-4fa1-bc72-ae40c2ff62f9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161264d9154f7a521</li>
        <li>Upwork Job ID: 1802728525946815546</li>
        <li>Last Price Increase: 2024-07-01</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 103017602</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Red dot on LHN does not appear for participant when create 1:1 hold expense

### What is the root cause of that problem?
- We early return ```false``` in this logic:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/ReportUtils.ts#L5278-L5280
if the current user is not submitter, that leads to there is no RBR displays for participant when creating 1:1 hold expense.

### What changes do you think we should make in order to solve the problem?
- We can update this logic:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/ReportUtils.ts#L5278-L5280
to:
```
    const transaction = allTransactions?.[`${ONYXKEYS.COLLECTION.TRANSACTION}${IOUTransactionID}`] ?? {};
    const isOnHold = TransactionUtils.isOnHold(transaction);
    if (!isCurrentUserSubmitter(IOUReportID) && !isOnHold) {
        return false;
    }
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by Pujan92** [comment]
@lschurr Based on [this comment](https://github.com/Expensify/App/issues/31095#issuecomment-1832758593) it seems only for the submitter we are showing Red dot(RBR) in LHN. Would like to confirm the expected result here.
cc: @cead22

**Comment by cead22** [comment]
I don't know about HOLD, so tagging @JmillsExpensify

**Comment by lschurr** [comment]
@JmillsExpensify will you take a peek at this one?

**Comment by trjExpensify** [comment]
We were discussing this in [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1719524659211529?thread_ts=1719314019.658989&cid=C036QM0SLJK). 

It seems like we're broadly not adding the RBR to the LHN and pinning the "combined" one expense report when it contains violations, one of which is a held request. 

<img width="1508" alt="image" src="https://github.com/Expensify/App/assets/16232057/5c80a090-ec9e-40d6-889b-0278ddcf4dd3">

<img width="1510" alt="image" src="https://github.com/Expensify/App/assets/16232057/59a13ba0-86fd-4820-af98-f82caa6bfbb3">

So we want to fix that. When an expense report contains just one expense, the RBR for the violation (incl. hold) should be added to the report row in the LHN and it should be pinned - because that is the "lowest" context chat in this scenario.

**Comment by lschurr** [comment]
Thanks @trjExpensify - @Pujan92 are you able to review?

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/43760#issuecomment-2168858196)

- I updated proposal to match the [new feature](https://github.com/Expensify/App/issues/43760#issuecomment-2196655455).

**Comment by Pujan92** [comment]
Thanks @trjExpensify

> The logic for who the RBR should be displayed to in the one expense report case should be exactly the same as the multi-expense report case.

At the moment the RBR in LHN is only displayed on the submitter side for the multi-expense specific report case, So I believe this task is all about showing the RBR in the LHN for one expense report case. @trjExpensify could you plz confirm once?

<details>
<summary>Mutli Expense(current behaviour of submitter side and then payer side)</summary>

https://github.com/Expensify/App/assets/14358475/5b012f99-ceb7-4f29-9ad6-0022c79941a6

</details>

<details>
<summary>One Expense(current behaviour of submitter side and then payer side)</summary>

https://github.com/Expensify/App/assets/14358475/a772d563-038d-4d6c-a613-dd6d21bef516

</details>

**Comment by trjExpensify** [comment]
>So I believe this task is all about showing the RBR in the LHN for one expense report case. @trjExpensify could you plz confirm once?

Correct. See below! 

>So we want to fix that. When an expense report contains just one expense, the RBR for the violation (incl. hold) should be added to the report row in the LHN and it should be pinned - because that is the "lowest" context chat in this scenario.

**Comment by Pujan92** [comment]
> 2. Change the getOptionData function to make sure the RBR is displayed in oneTransactionReport in LHN if its transaction has violations.

@truph01 Plz provide the draft branch for this as I am not sure whether the hold/unhold change rerenders the one expense report in the sidebar or not.

I also wonder, can't we do the same somewhere at a higher level([where we derive shouldDisplayViolations](https://github.com/Expensify/App/blob/9fbbbfb01a64c8bc7214fc6d04ab71e61d15bda6/src/components/LHNOptionsList/OptionRowLHNData.tsx#L38))?

**Comment by trjExpensify** [comment]
@truph01 bump on the question above. We'd really like to keep this moving. Thanks!

**Comment by truph01** [comment]
@Pujan92 I created a draft [PR](https://github.com/Expensify/App/pull/44810)

**Comment by Pujan92** [comment]
@truph01 The Issue I see - on updating the hold/unhold status for one expense report isn't getting rerenders in the sidebar.

https://github.com/Expensify/App/assets/14358475/cd3433ce-d67a-4f17-bdb7-1d71920184b3

I have some other doubts in the implementation but that can be discussed and rectified in the PR. Could you plz check and update on the above issue?

**Comment by truph01** [comment]
> on updating the hold/unhold status for one expense report isn't getting rerenders in the sidebar.

I am still investigating it. But FYI, this bug also appears in the latest main.

**Comment by truph01** [comment]
> on updating the hold/unhold status for one expense report isn't getting rerenders in the sidebar.

@Pujan92 Maybe it is a BE bug. When we hold any expense, there is no ```transactionViolations_``` data returned from BE side.

**Comment by Pujan92** [comment]
> But FYI, this bug also appears in the latest main.

Yes @truph01, it exists on main too.

**Comment by Pujan92** [comment]
We can proceed with point 2 of @truph01's [proposal](https://github.com/Expensify/App/issues/43760#issuecomment-2168858196) which is to check violation for the child report if it is a one-expense report.

🎀👀🎀 C+ reviewed

**Comment by robertjchen** [comment]
Thanks for the discussions and review, let's move forward with the @truph01 's proposal 👍

**Comment by truph01** [comment]
@Pujan92 PR https://github.com/Expensify/App/pull/44810 is ready.

**Comment by Pujan92** [comment]
We don't have an offending PR here as it is kind of a new thing for the one expense report.

### Regression Test Steps

1. Submit a first expense for any of the participant
2. Hold that expense / Violate it by skipping required fields(category/tag..) if it is the policy expense chat
3. Verify the one expense report in the LHN has the RBR and is pinned.

 Do you agree 👍 or 👎 ?

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @truph01 $250 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/37764796/overview))
- Reviewer: @Pujan92 $250 (please request via NewDot)

**Comment by JmillsExpensify** [comment]
$250 approved for @Pujan92
