### ISSUE TITLE
Bank account - Year not always highlighted in year picker for DOB and incorporation year

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43771]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4631294
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Create a workspace if you do not have any
3. Navigate to workplace settings
4. Enable Workflows from More features
5. Toggle on Make or track payments
6. Click on Connect Bank account and select any option
7. Start adding a bank account until reach Personal Info - Enter your date of Birth
8. Click on the year field and try entering exact years, e.g. 1999, 2001
9. Proceed to Incorporation year step
10. Repeat step 8, but enter years, e.g. 2019, 2022

## Expected Result:
The only search result in the year is always highlighted

## Actual Result:
Not all years get highlighted in the year picker when searching for the exact year. It seems like for DOB only years before 2000 are highlighted, and for incorporation date - years before 2020

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6c9d742c-9e53-4fe1-a640-26388a4cc460

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by muttmuure** [comment]
Not overdue

**Comment by muttmuure** [comment]
Dupe
