### ISSUE TITLE
[PAID] [VIP][Travel] handle errors when spotnana token isn't created

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#43780]
Coming from https://github.com/Expensify/App/pull/43081#discussion_r1633984988

We should handle errors by showing a RBR when spotnana token can't be generated.
Do a pre-design for how errors should be handled, and then implement it.

### 2 - Make sure to do the same for AcceptSpotnanaTerms command

src/libs/actions/Travel.ts

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by rushatgabhane** [comment]
@strepanier03 please assign this issue to me

**Comment by strepanier03** [comment]
Assigned!

**Comment by rushatgabhane** [comment]
no updates yet

**Comment by rushatgabhane** [comment]
PR hit staging

**Comment by rushatgabhane** [comment]
PR above ^

**Comment by rushatgabhane** [comment]
PR on staging and tests well

**Comment by strepanier03** [comment]
@rushatgabhane - I'll check in later for the checklist.

**Comment by strepanier03** [comment]
Friendly bump on the [checklist](https://github.com/Expensify/App/issues/43780#issuecomment-2274413781) so we can wrap this one up.

**Comment by rushatgabhane** [comment]
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by strepanier03** [comment]
REg test created and request is paid, closing now.
