### ISSUE TITLE
[Awaiting payment a while ago] BUG: Recent waypoints aren't loaded after sign in

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#43786]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.83-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718391073226239

## Action Performed:
1. Create a distance expense with some waypoints A, B
2. Sign out
3. Sign back in
4. Create a distance expense and pause when entering the first waypoint

## Expected Result:
A and B should be shown as recent waypoints

## Actual Result:
No recent waypoints are shown because they are only fetched from the backend when a distance expense is created.

## Workaround:
Yes, ignore or create another distance expense

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/26260477/8539da2c-02ad-4d6b-a8bc-266e7e0c906a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by anmurali** [comment]
Yea, I would agree that this seems like extreme polish.

**Comment by neil-marcellini** [comment]
I just noticed the Web-E PR is on prod so I took the App PR off hold and it will be reviewed by C+ soon.

**Comment by anmurali** [comment]
Offer created [here](https://www.upwork.com/nx/wm/offer/103901301)

**Comment by anmurali** [comment]
Paid.
