### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250]  Subscription size - Decimal point can be inserted and not removed on the confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43328
## Action Performed:
1. Go to staging.new.expensify.com/settings/subscription/subscription-size
2. Enter a digit and a decimal point
3. Click Next

## Expected Result:
Decimal point will be removed on the next page

## Actual Result:
Decimal point can be inserted and not removed on the confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1dc1b351-8c0f-4425-b027-2135a53f6180

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8c409a169a06c82</li>
        <li>Upwork Job ID: 1803448780086879493</li>
        <li>Last Price Increase: 2024-06-19</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 102862371</li>
<li>Krishna2323 | Contributor | 102862372</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by miljakljajic** [comment]
@Krishna2323 you've been paid in upwork, thank you!

@fedirjh your original offer expired as you didn't accept it in upwork in time. Please accept the new offer.

**Comment by miljakljajic** [comment]
actually @fedirjh do we pay you in NewDot? I noticed you're listed for manual payments. Let me know and I'll provide a payment summary instead.

**Comment by miljakljajic** [comment]
Of course, apologies.

@fedirjh is owed 250 for their work reviewing this issue.
