### ISSUE TITLE
CRITICAL [UX Reliability] Whisper messages for 0.00 appears when submitting a report to the workspace chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43792]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1718266777408749

## Action Performed:
1. Go to the workspace chat
2. submit a report
## Expected Result:
Able to submit with no issues
## Actual Result:
several whispers for amount of 0.00
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![IMG_3604](https://github.com/Expensify/App/assets/38435837/57896d10-e4d4-49bc-9a18-7c24c4ccd5d5)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Adding another assignee as I am OOO until 2024-06-25. I'll take this back when I return if it's still open!

**Comment by MonilBhavsar** [comment]
Might be because of some recent change 
Need to follow this thread https://expensify.slack.com/archives/C036QM0SLJK/p1718365251978559

**Comment by muttmuure** [comment]
Added the hold to the title

**Comment by MonilBhavsar** [comment]
on HOLD, bumping to weekly

**Comment by muttmuure** [comment]
Held

**Comment by muttmuure** [comment]
Looks like this was merged - https://github.com/Expensify/Auth/pull/11354

**Comment by MonilBhavsar** [comment]
Yes, adding retest-weekly label to check if issue is fixed
