### ISSUE TITLE
Markdown – Send button is not active when paste text with markdown and Enter from Word

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43808]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4635472
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Open Word document and wright: _Text_ and press Enter on the keyboard. Copy all this text with Enter in the end
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Paste text with markdown and Enter in the end

## Expected Result:
Send button is active

## Actual Result:
Unable to send message, send button is not active

## Workaround:
Unknwon

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1b9aa91e-fca3-4b90-b812-f29f5ea2c323

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by kpadmanabhan** [comment]
@lanitochka17 : this will be fixed with the solution mentioned in [this proposal](https://github.com/Expensify/App/issues/43331#issuecomment-2167821876).
