### ISSUE TITLE
[Xero][QBO][Wave-Collect] Require 2FA for accounting integration.

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#43812]
Context: https://expensify.slack.com/archives/C036QM0SLJK/p1718145354671749?thread_ts=1717422173.269869&cid=C036QM0SLJK

Require 2FA for connecting to accounting integration

**Comment by rushatgabhane** [comment]
@bfitzexpensify please assign me this issue

**Comment by bfitzexpensify** [comment]
How's this one going @rushatgabhane?

**Comment by rushatgabhane** [comment]
@bfitzexpensify the PR is being actively worked on. Sorry I created a dupe issue.

Closing in favor of - https://github.com/Expensify/App/issues/43015

**Comment by bfitzexpensify** [comment]
All good!
