### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Workspace - Unable to proceed to the next tab from "Invite new members" with Enter key

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43821]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4635357&group_by=cases:section_id&group_id=229065&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any account that has a workspace
3. Navigate to the workspace Members page
4. Select a few members
5. Focus the empty input field
6. Press the Enter key

## Expected Result:
I should be taken to the "Add message" page.

## Actual Result:
Unable to proceed to the next tab from "Invite new members" with Enter key.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e0c3668e-535f-4cd9-ac26-cd31cb7771b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150ec85dec4b39a10</li>
        <li>Upwork Job ID: 1802772880999647514</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102873717</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by sakluger** [comment]
Agree that this is a bug related to wave-collect.

**Comment by sakluger** [comment]
Hey @abdulrahuman5196, could you please review Krishna's proposal?

**Comment by sakluger** [comment]
I'm going to assign a new C+ to keep this issue moving.

**Comment by sakluger** [comment]
Hey @Ollyws - could you please review the open proposal (https://github.com/Expensify/App/issues/43821#issuecomment-2173532473) when you have a chance? Thanks!

**Comment by blimpich** [comment]
@Krishna2323 @Ollyws please be careful with this one, I feel like this change has a high possibility of causing regressions since we added that prop a long time ago and have probably forgotten a lot of context. Please be extra thorough when you are testing your changes 👍

**Comment by sakluger** [comment]
I'm not sure why this switched to Daily so early - it just deployed to prod yesterday. I'm switching it back to weekly.

@Ollyws can you please complete the BZ checklist by July 22? Thanks!

**Comment by sakluger** [comment]
My bad - payment is due on 7/17. Switching back to daily!

**Comment by JmillsExpensify** [comment]
@sakluger can I get a payment summary please?

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @Krishna2323 $250, paid via Upwork
Contributor+: @Ollyws $250, please request on Newdot

**Comment by JmillsExpensify** [comment]
@250 approved for @Ollyws
