### ISSUE TITLE
Workspace - Workspace chat reappears in LHN after leaving the chat and relogin

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is invited to a workspace.

1. Go to staging.new.expensify.com
2. Go to workspace chat as workspace member.
3. Click on the chat header.
4. Click Leave.
5. Log out.
6. Log in.

## Expected Result:
The workspace chat will not appear in LHN because user left the workspace chat.

## Actual Result:
The workspace chat reappears in LHN after leaving the chat and relogin.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/fffafe2d-62cf-49cd-b6fb-af477e3e97cc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@nkuoch FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by johnmlee101** [comment]
I don't see a cause from Web-E https://github.com/Expensify/Web-Expensify/compare/b7840b36...52842eef so I'm going to remove the DeployBlocker label

**Comment by AndrewGable** [comment]
Pretty sure this is the PR https://github.com/Expensify/App/pull/43065 that started allowing users to leave workspace chats, so we can try to revert that PR and try again

**Comment by brunovjk** [comment]
thank you for the prompt fix @jasperhuangg
