### ISSUE TITLE
[$250] Workspace - "ERR_ABORTED 403" console error when starting the Plaid bank account flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43829]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4635397&group_by=cases:section_id&group_id=283225&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new expensifail account
2. Create a new workspace
3. Enable "Workflows"
4. Navigate to Workspace settings - Workflows - Connect bank account
5. Click on the "Connect online with Plaid" button
6. Close the modal
7. Click on the "Connect online with Plaid" button again

## Expected Result:
There shouldn't be any console errors

## Actual Result:
"ERR_ABORTED 403" console error when starting the Plaid bank account flow. It can occur at the first or second opening of Plaid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5466ea83-2b1e-48f6-b0fa-b671c2d39d9a

[logs (2).txt](https://github.com/user-attachments/files/15871691/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016463341dfa038042</li>
        <li>Upwork Job ID: 1803922033721163630</li>
        <li>Last Price Increase: 2024-06-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
Waiting on proposals.

**Comment by stephanieelliott** [comment]
Giving this a bit more time for proposals...

**Comment by stephanieelliott** [comment]
Posted to see if SWM can pick this up: https://expensify.slack.com/archives/C04878MDF34/p1719858196586979

**Comment by jnowakow** [comment]
Hello, it seems we can't do anything about it. This error is caused because for some reason the font can't be downloaded from CDN. We are showing iframe with Plaid's code so we can't fix that problem. I think the only thing we can do about it is to report it to them 

<img width="1820" alt="image" src="https://github.com/Expensify/App/assets/56261019/341d2b78-ced1-45a9-a23d-d4f8b104f8dc">

**Comment by stephanieelliott** [comment]
Got it, thanks @jnowakow! That makes sense, sounds like this is not our error and not much we can do fix it. With that being the case I am going to close, appreciate you looking into it!
