### ISSUE TITLE
[HOLD for payment 2024-07-02] [HOLD for payment 2024-06-28] [HOLD for payment 2024-06-28] [Fullstory] [$250] Update Fullstory version to work with React-Native-Web annotations

### ISSUE THREAD

**Issue by danieldoglas** [Expensify/App#43827]
Fullstory has released a new version with annotations for react-native-web. Let's update it.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014868e2119053451c</li>
        <li>Upwork Job ID: 1802690523185613082</li>
        <li>Last Price Increase: 2024-06-17</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102800397</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by danieldoglas** [comment]
Placeholder issue so we can assign a C+ to be paid once they test it

**Comment by danieldoglas** [comment]
No help wanted since PR is ready

**Comment by strepanier03** [comment]
PR is deployed to staging. 

Do I hold payment for 7 days still @danieldoglas?

**Comment by srikarparsi** [comment]
Hey! This [PR](https://github.com/Expensify/App/pull/43785) caused this [deploy blocker](https://github.com/Expensify/App/issues/43898) so we had to revert it [here](https://github.com/Expensify/App/pull/43971). I think we might need to redo the change if we need it.

**Comment by danieldoglas** [comment]
Adding the deploy blocker because we want to wait on this before deploying.

**Comment by AndrewGable** [comment]
Report header is working for me after CPing the fix 👍

**Comment by c3024** [comment]
>The PR that introduced the bug has been identified. Link to the PR: 

This is not a bug fix PR. This PR enables third party scripts for `staging` as well. 
> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 

NA
>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 

NA
>Determine if we should create a regression test for this bug. 

No
>If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md?rgh-link-date=2023-06-22T16%3A41%3A44Z) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

NA

**Comment by strepanier03** [comment]
### Payment Summary

- [ ] $250 - @parasharrajat via Manual Request
- [x] @c3024 Paid via Upwork [automatic offer](https://www.upwork.com/nx/wm/offer/102800397)

@JmillsExpensify - Payment request incoming.

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
