### ISSUE TITLE
Save the world - #teachers-unite room only appears for the teacher after a relog

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43831]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4635819&group_by=cases:section_id&group_id=229065&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Principal: Navigate to https://staging.new.expensify.com/
2. Principal: Log in with an expensifail account
3. Principal: Navigate to Account settings - Save the world - I know a teacher
4. Principal: Input anything for the name fields, and an expensifail email address to the email field
5. Teacher: Log in with another device
6. Principal: Click on the "Let's do this!" button
7. Teacher: Navigate to the LHN
8. Teacher: Refresh the page

## Expected Result:
#teachers-unite room should be visible in a few seconds after adding the teacher

## Actual Result:
#teachers-unite room only appears for the teacher after a relog if it is logged in at the moment of beign added by the principal. It appears in the LHN for half a second but disappears after

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e1d36d5b-4b7c-4fc0-9d96-05ef9656cac0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
Same as above.

**Comment by kadiealexander** [comment]
Still not overdue

**Comment by kadiealexander** [comment]
Still not a top priority

**Comment by kadiealexander** [comment]
Getting a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1720133915334679).

**Comment by kavimuru** [comment]
Tester is still able to reproduce. 

https://github.com/Expensify/App/assets/43996225/4367ef1b-f378-40eb-ad1a-3d3b7a2d896d

**Comment by kadiealexander** [comment]
Not overdue

**Comment by kadiealexander** [comment]
Still not overdue.

**Comment by kadiealexander** [comment]
Same as above, low priority.

**Comment by kadiealexander** [comment]
I think this is a super minor bug, and we haven't had any real-world people report it. Closing for now, please reopen if it becomes a real-world issue.
