### ISSUE TITLE
[$500] Track expense - Expense preview isn't displayed for request next to failed one

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43836]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990404
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user has no workspace.
1. FAB: Submit a track expense (Manual) in the self DM
2. On the actionable whisper options of a track expense click on 'Share it with my accountant'
3. Enter a merchant and create the expense
4. Dismiss errors on failed request
5. Submit another track expense in the self DM

## Expected Result:
Expense preview is displayed for request next, to failed one. Actionable whisper options are displayed below expense preview

## Actual Result:
Expense preview isn't displayed for request next to failed one. Only actionable whisper options are displayed below expense preview

## Workaround:
Unknown

Logs:
`Throw ExpException - dd4a10403dbc820ca439c9ebd34bf623 ~~ message: '401 Trying to convert a non-tracked (i.e. reported) expense to a request' exceptionMessage: 'Auth ConvertTrackedExpenseToRequest returned an error' exceptionFile: '/git/releases/expensify.com/7c6ba03/lib/Auth.php' exceptionLine: '126' exceptionCode: '401'`

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ee373d61-baae-48c1-ab17-0f2ef3547288

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013679e46158ff2345</li>
        <li>Upwork Job ID: 1802729732420437943</li>
        <li>Last Price Increase: 2024-07-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by lanitochka17** [comment]
@Julesssss  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by Julesssss** [comment]
Given that the pre-requesite errors need to be fixed first, and might resolve this issue I am removing the blocker label. I don't see many potential causes of the other bug, but will check again tomorrow. Presumably there is an existing issue for that failure.

**Comment by Julesssss** [comment]
Added logs

**Comment by c3024** [comment]
>Enter a merchant and create the expense
Dismiss errors on failed request

Are there specific steps for making the request fail?

**Comment by c3024** [comment]
Must have been fixed somewhere.


https://github.com/Expensify/App/assets/102477862/045bbd43-64e5-4c76-9899-f2312c2297e8

Cannot reproduce on `main`.
