### ISSUE TITLE
 Track expense - Receipt scanning is stuck

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43834]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990407
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Tap on the FAB (Floating Action Button) and select 'Track Expense'
2. Select the scan option
3. Upload a receipt that will be successful
4. Access the scan request you just created

## Expected Result:
The header shows 'Scan in progress...'
The 'Amount' and 'Merchant' fields display 'Scanning...'

Wait a <30 min for the scan to finish

## Actual Result:
The header shows 'Scan in progress...'
The 'Amount' and 'Merchant' fields display 'Scanning...'

Receipt scanning is stuck for hours

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/38aad55d-ac63-4d18-baf4-ebc59735d0fb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by anmurali** [comment]
Cannot reproduce. I suspect we had a lag with agents manually scanning when this was tested but that backlog probably cleared out shortly after.
