### ISSUE TITLE
[HOLD for payment 2024-07-24] [$125] iOS - Distance - Top left corner of the distance receipt is sharp instead of rounded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4638881
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace chat
3. Submit a distance expense
4. Go to transaction thread
5. Tap on the distance receipt

## Expected Result:
The receipt corner on all ends should be rounded

## Actual Result:
The top left corner of the distance receipt is sharp and not rounded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![IMG_4383](https://github.com/Expensify/App/assets/78819774/2a6e3ab6-0738-491c-a625-4ea2e97bc649)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e67d7fccfba02aee</li>
        <li>Upwork Job ID: 1803175323249438423</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103076547</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by dylanexpensify** [comment]
reproing today!

**Comment by dylanexpensify** [comment]
Made external

**Comment by dylanexpensify** [comment]
updated price given the ease of this

**Comment by dylanexpensify** [comment]
@roryabraham to review and confirm!

**Comment by dylanexpensify** [comment]
Will bump @roryabraham

**Comment by Beamanator** [comment]
Agreed, looks straightforward

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @Krishna2323 $125
- Contributor+: @parasharrajat $125

Please apply/request!

**Comment by dylanexpensify** [comment]
Done!

**Comment by JmillsExpensify** [comment]
$125 approved for @parasharrajat
