### ISSUE TITLE
[$250]  Track expense - Placeholder instead request preview in ND for report created in OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43847]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990417
**Email or phone of affected tester (no customers):** applausetester+bp1606w@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user is logged in OD and ND
1. OD: Go to Expenses tab > click New Expense
2. Fill out Merchant, Amount fields
3. For Report field choose (none) > Save
4. Go to ND > self-DM

## Expected Result:
Unreported expense shows up on the self-DM (ND)

## Actual Result:
Placeholder (skeleton loader) shows up on the self-DM (ND)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/98580edf-808f-4a98-8ab8-a9542892097c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be3c07f2dde8fedc</li>
        <li>Upwork Job ID: 1805655776545544434</li>
        <li>Last Price Increase: 2024-07-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by miljakljajic** [comment]
waiting for proposals

**Comment by miljakljajic** [comment]
waiting

**Comment by miljakljajic** [comment]
posted in open source: https://expensify.slack.com/archives/C01GTK53T8Q/p1720715510745289

**Comment by miljakljajic** [comment]
Going to check if this is still reproducible and then increase the bounty

**Comment by miljakljajic** [comment]
https://expensify.slack.com/archives/C9YU7BX5M/p1722420947738539

**Comment by m-natarajan** [comment]
Bug is not reproduced

https://github.com/user-attachments/assets/6cf5dbad-30cb-425b-ad6c-6aa2053d61c8

**Comment by miljakljajic** [comment]
Thank you @m-natarajan - closing!
