### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] QBO - Confirmation page still shows tag field when all subtags are disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43851]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account is connected to QBO
- "Classes" subtags are all disabled
- "Customers/Projects" subtags are enabled
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Submit expense > Manual
4. Proceed to confirmation page
5. Click Classes

## Expected Result:
"Classes" field should not be on the confirmation page since all subtags are enabled

## Actual Result:
"Classes" field is present on the confirmation page and it leads to an empty list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/def71c4e-e986-4145-82f9-c92133ba5a09

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129a30066b9faaee2</li>
        <li>Upwork Job ID: 1803818756862614555</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 102822657</li>
<li>Krishna2323 | Contributor | 102822659</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment]
related to QBO!

**Comment by zanyrenney** [comment]
Triaged!

**Comment by situchan** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/43851#issuecomment-2173927886) looks good to me.
🎀👀🎀 C+ reviewed

**Comment by zanyrenney** [comment]
we don't need a regression test here, this is fixing a bug. the desired flow is already in the QBO testing steps.
