### ISSUE TITLE
[$250] Web - Messages - Messages are not displayed in real-time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43863]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** test.iris.santos+17062024@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
- Navigate to https://staging.new.expensify.com/
in any browser
- Log in with an account
- Log in with a secondary account in another device or incognito tab.
1. Open a 1:1 conversation with a user you have access with.
2. Send a message to the other user

## Expected Result:
Messages are displayed in real-time

## Actual Result:
Messages are NOT displayed in real-time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9ee906ed-0c29-4ee6-a349-1616ba392420

![44 06](https://github.com/Expensify/App/assets/78819774/0402adf0-8838-4b6c-ba39-42a047b8d7f7)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01058dfafe3e05a383</li>
        <li>Upwork Job ID: 1804121224282097550</li>
        <li>Last Price Increase: 2024-06-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by tsa321** [comment]
I believe this is back end issue.

**Comment by abekkala** [comment]
This will most likely require a back end fix

**Comment by abekkala** [comment]
not overdue MELVIN - waiting on internal to pick up!

**Comment by abekkala** [comment]
not overdue - waiting on internal to pick up!

**Comment by abekkala** [comment]
waiting on internal volunteer to grab this one

**Comment by abekkala** [comment]
still waiting on internal volunteer to grab this one

**Comment by abekkala** [comment]
waiting on internal volunteer to grab this one

**Comment by abekkala** [comment]
waiting on internal volunteer to grab this one
