### ISSUE TITLE
[$250]  Expenses - Old amount shown in overview until entering another section and going back

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43862]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** [bellicoignacio@gmail.com](mailto:bellicoignacio@gmail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the https://staging.new.expensify.com/
website
2. Tap on the search icon on the bottom of the page
3. Open any expense
4. Tap on the amount
5. Edit the amount
6. Tap on the arrow on the top left corner
7. Tap on the arrow on the top left corner again
8. Check if the amount was changed in the expense overview
9. Tap on another section
10. Go back to search section
11. Check if the amount was changed after this action

## Expected Result:
Expense amount should be automatically updated in the overview, after being edited by the user

## Actual Result:
Expense overview displays the previous amount until the user enters another section and goes back to the search section again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/59ce22a2-bc77-4071-b022-47968898a439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cadbae38ca9c8306</li>
        <li>Upwork Job ID: 1805944749423663346</li>
        <li>Last Price Increase: 2024-07-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
