### ISSUE TITLE
[HybridApp] Crash when changing reimbursement account

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#43866]
## Problem
Crash occurs on iOS when changing reimbursement account

1. Go to Settings on OldApp in HybridApp
2. Select a different reimbursement account
3. 💥 

## Solution
Fix it

<details><summary>Issue Owner</summary>Current Issue Owner: @NikkiWines</details>

**Comment by AndrewGable** [comment]
Seems like it's missing an API param?

`Parameter password is required`

Crash here: https://github.com/Expensify/Expensify/issues/335548

**Comment by AndrewGable** [comment]
Looks like this broke here: https://github.com/Expensify/Mobile-Expensify/commit/ea4ad9b188952a44a71396352c24cf772a689103

**Comment by AndrewGable** [comment]
@NikkiWines @johnmlee101 - Can you see if we can remove the `password` as a [required parameter here](https://github.com/Expensify/Mobile-Expensify/blob/main/app/libs/api.js#L668)? Seems like it's still required by the API, so not sure how it should work with passwordless.

**Comment by NikkiWines** [comment]
Sorry for the delay, on my radar to take a look at this tomorrow

**Comment by AndrewGable** [comment]
Bump @NikkiWines or @johnmlee101 for your thoughts here! Thanks

**Comment by AndrewGable** [comment]
@NikkiWines said she would look into this one soon!

**Comment by AndrewGable** [comment]
Seems like on web we allow switching reimbursement accounts without a password, so we should do the same here

**Comment by AndrewGable** [comment]
I think we send email notifications now instead of prompting for a password

![Google Chrome 2024-06-27 at 11 02 09](https://github.com/Expensify/App/assets/2838819/4d308e5b-bffc-4f2d-a460-c5069c9f9197)

**Comment by NikkiWines** [comment]
Yeah on web, all password prompts have been replaced with either 

a. Prompting the user to validate their account in advance of the action being taken 
b. Allowing the action w/o a password because the user is already authenticated at this stage.
