### ISSUE TITLE
[HOLD for payment 2024-07-10] [$500] [CRITICAL] Open travelDot after accepting terms and conditions 

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#43867]
Booking travel via new dot should take you to travelDot page and authenticate the user

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by twisterdotcom** [comment]
Moving this to `CRITICAL` for GBTA

**Comment by rushatgabhane** [comment]
PR is here https://github.com/Expensify/App/pull/43966

It fixes quite a few issues

**Comment by twisterdotcom** [comment]
Even though I'm downgrading, I'm happy to keep it at $500. It solves a lot of issues.

**Comment by rushatgabhane** [comment]
Appreciate it! :)

**Comment by rushatgabhane** [comment]
PR on staging. It tests well

**Comment by twisterdotcom** [comment]
Hello folks, sorry I was OOO last week. I have a bunch to do, I will get them all done today. Thanks for your patience.

**Comment by rushatgabhane** [comment]
@twisterdotcom could you please confirm payment summary when you can. Thank you : )

**Comment by JmillsExpensify** [comment]
Reached out via DM

**Comment by twisterdotcom** [comment]
Payment Summary:

Reviewer: @rushatgabhane paid $500 via NewDot Requests (Contributor)
ROLE: @shubham1206agra paid $500 via Upwork [here](https://www.upwork.com/nx/wm/offer/new/1028761871) (C+)

**Comment by JmillsExpensify** [comment]
$500 approved for @rushatgabhane

**Comment by twisterdotcom** [comment]
Paid out.
