### ISSUE TITLE
[HOLD for payment 2024-08-02] [$500] [Report Field Violations] Add RBR for report level violations

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#43880]
As part of supporting report field violations in NewDot, we need to update the FE to support report level red brick roads.

Similar to expense level transactions, we're going to be adding a new onyx key that is keyed with `reportViolations_<reportID>`. We currently only have one type of error which is 'fieldRequired'. Below is an example of what this key will look like

```
reportViolations_<reportID> : {
    fieldRequired: {
        field_id_uno: {},
        field_id_dos: {}
    }
}
```

Criteria:
- Violations are highlighted in the member’s LHN
- Violations are not highlighted in the admin’s LHN
    -  While admins can fix violations on behalf of members while processing an expense report, this is not the expectation. It’s merely optional.
- Members, approvers and admins equally see violations as a line item on the required report field

![image](https://github.com/Expensify/App/assets/30609178/f2a823b2-8d58-404e-a6e9-d7432d8ebc8a)

A few things need to be completed in this issue
- Add the RBR on reports that have violations from the onyx key
- Optimistically generate the report violations based on the existing onyx data
- Update / clear the key when the field is updated

> [!NOTE]  
> Report violations are not implemented in the BE yet. That is being worked on concurrently, so to test this you will need to set the report violation in onyx manually, or add the method to optimistically set report violations based on the current policy onyx data

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150569a530b6396da</li>
        <li>Upwork Job ID: 1803111077232754500</li>
        <li>Last Price Increase: 2024-06-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by jnowakow** [comment]
Hello @thienlnam, I'm from Software Mansion, an expert agency and I would like to work on this.

**Comment by jingp-ofload** [comment]
@thienlnam I'd like to make a proposal on this. It seem like following the structure of transaction validation. But I need to know how to navigation to NewDot.

**Comment by jp928** [comment]
[@thienlnam](https://github.com/thienlnam) I'd like to make a proposal on this. It seem like following the structure of transaction validation. But I need to know how to navigation to NewDot.

**Comment by jnowakow** [comment]
BTW @thienlnam are `violations` something different than `errors`? There's already field on `Report` called `errorFields`:
 
<img width="728" alt="image" src="https://github.com/Expensify/App/assets/56261019/5f8bf7a4-8154-44a8-bf22-fac0d8e7447b">

Although it's not extensively used across the app. I also had a problem to generate a report such as on your screenshot. Can you explain how to achieve that? Fields on report are coming from the policies right?

**Comment by thienlnam** [comment]
@jnowakow They're similar, but violations are different than errors. The error fields of these data types are currently used to add errors from the BE when making failed API calls related to a report, but violations are more like things that are preventing the report from being submitted. Right now, the only report violations we have are report fields.


> I also had a problem to generate a report such as on your screenshot. Can you explain how to achieve that? Fields on report are coming from the policies right?

Yes this is correct - I added this note in the description but the BE functionality is not added yet, so out the onyx key you'll have to manually add the onyx error, or create a method to optimistically calculate the errors.

To set up report fields on NewDot - You have to currently go into OldDot -> Settings -> Workspaces -> Report Fields and add a bunch of required / non required fields. Then, add the beta on that policy by following these steps

```
Right now, workspace chats are only created for Free policies. However, we have a "beta" that allows you to opt specific Collect or Control policies into having workspace chats created.

To enable this "beta" for any given policy:

Go to OldDot and open the settings for the Collect/Control policy

In the JS console with the policy open do:

p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = true;
p.save();
This will make it so that any user you invite to that policy going forward will have a Workspace Chat created in NewDot for that policy. It will not retroactively create a workspace chat for the policy owner or any other user that was already a member of the policy before you enabled the beta.

```

Then, invite a member to that policy. Now, when you log into the invited member's account and submit an expense in the workspace chat you should see the report fields in onyx in the policy key

**Comment by jnowakow** [comment]
@thienlnam thanks for explanation!

**Comment by jnowakow** [comment]
@thienlnam Onyx entry shouldn't allow multiple fields id to be specified? Something more like:
```
"reportViolations_7982982524495632123": {
     "fieldRequired": {fieldIDS: ['field_id_FIELD_1', 'field_id_FIELD_2']}
  }
```

**Comment by thienlnam** [comment]
Good question, it's possible that multiple report fields will be required but asking [internally](https://expensify.slack.com/archives/C06ML6X0W9L/p1718921331799549?thread_ts=1718152897.804869&cid=C06ML6X0W9L) how we should handle this

**Comment by jnowakow** [comment]
@thienlnam I think we don't give user a chance to edit report fields. We don't display them in expense creation form:

<img width="373" alt="image" src="https://github.com/Expensify/App/assets/56261019/19df557e-694b-4ac1-ab54-682675946bb7">


I don't see much usages in code either. I'm only able to see those fields on reports when there are more than one expenses:

<img width="1906" alt="image" src="https://github.com/Expensify/App/assets/56261019/139f9160-230a-4219-b454-558e982b310c">

**Comment by thienlnam** [comment]
The screen you're seeing is for updating the transaction fields, report fields are separate - like in your second screenshot and you should be able to update them there.

> I'm only able to see those fields on reports when there are more than one expenses:

That shouldn't be the case - but they only show up on reports that are tied to the policy that have report fields set up. So it's not like all reports will have report fields if that makes sense

**Comment by thienlnam** [comment]
@jnowakow Here's the new format for the report violations
```
reportViolations_<reportID> : {
    fieldRequired: {
        field_id_uno: {},
        field_id_dos: {}
    }
}
```

For this specific type of violation, there isn't any field_id specific data so they will just be empty objects

**Comment by jnowakow** [comment]
@thienlnam I have question about this requirement:

> Optimistically generate the report violations based on the existing onyx data

Should this work only for new reports? I mean that when new report with policy is created then we should optimistically set report violations. Or should it work also backwards, so it should be able to calculate violations for already existing reports and put them in onyx?

**Comment by jnowakow** [comment]
@thienlnam I went first way. I found that there's method `addPolicyReport` so I implemented add `reportViolations` there. This leads to the situation where for example you create room conversation and get RBR in LHP without ability to see and update report fields: 
<img width="1906" alt="image" src="https://github.com/Expensify/App/assets/56261019/8f073f8d-47ac-48ce-80aa-5feccbe8758a">


Are there requirements which reports should have validation?

**Comment by thienlnam** [comment]
This should only work for new reports - we wouldn't be able to calculate violations for old reports this way since the required fields might have changed.

> This leads to the situation where for example you create room conversation and get RBR in LHP without ability to see and update report fields:

Yeah that is fine for now, you'll have to go into the report to update them there at this time

**Comment by jnowakow** [comment]
Then I think I'm close to finish line. But I don't see option to edit those fields on room report. I have also question about field `text_title` it seems to be a default one but it isn't present in report's fieldList.

**Comment by thienlnam** [comment]
In this [screenshot](https://private-user-images.githubusercontent.com/56261019/341716331-139f9160-230a-4219-b454-558e982b310c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzc5MzksIm5iZiI6MTcxOTMzNzYzOSwicGF0aCI6Ii81NjI2MTAxOS8zNDE3MTYzMzEtMTM5ZjkxNjAtMjMwYS00MjE5LWI0NTQtNTU4ZTk4MmIzMTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE3NDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWIyYjY0MTZkNGVjOWZkODgzNmJiMjhiMWZmOWVjNGMxOWI5NWE3MmFjMzU1ZWU1YjM2NWI2YTU0MTMwMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NgwL_92wxbH8TI51tKVYi2n4PVSNu6bU2Z-a-ZkfbJ0) you posted earlier - clicking on the row should take you to edit them (pole 1, pole 2, etc)

> I have also question about field text_title it seems to be a default one but it isn't present in report's fieldList.

text_title is just the reportName as part of the report onyx key

**Comment by jnowakow** [comment]
I don't think editing report fields is implemented on this type of reports:

https://github.com/Expensify/App/assets/56261019/327ce0a0-e56b-4874-8e3f-169d5581a14a

Yeah, I expected that `text_title` is just report name but the there's problem that it is present in policy `fieldList` and it's not present in report's `fieldList`. Should it be excluded from report violations checks?

**Comment by thienlnam** [comment]
> I don't think editing report fields is implemented on this type of reports:

The way to test this would be submitting expenses to the policy expense chat of the policy you added report fields for. I forgot that you can only see the report fields if you have multiple transactions on a report. I've started a [thread](https://expensify.slack.com/archives/C06ML6X0W9L/p1719412818138079) here about how we should handle it for single transaction reports since we show a transaction view in those cases 

https://github.com/Expensify/App/assets/30609178/a24285be-5796-4cb5-9b31-2581a0baa2ea

> Should it be excluded from report violations checks?

I believe it's fine to exclude because I don't think there will ever be a violation for text_title. It's either set to a fixed value by default, or always has a value

**Comment by jnowakow** [comment]
Okey but rooms are also policy reports so they will have RBR without possibility to remove them:
<img width="1910" alt="image" src="https://github.com/Expensify/App/assets/56261019/afa5fecf-0ff2-422a-9823-39f8867a9fbb">

**Comment by thienlnam** [comment]
Rooms are chat reports which don't have report fields - these are just for expense reports and invoice / paycheck reports (which are not in NewDot yet, so just expense)

**Comment by war-in** [comment]
Update:

- PR is ready for C+ review (all comments addressed) :)
- I'll be OOO till Monday so if you would like to iterate faster you can always tag @blazejkustra. Otherwise, see you next week 👋

**Comment by war-in** [comment]
@thienlnam The PR was merged so we should be able to close this issue :)

**Comment by miljakljajic** [comment]
@allroundexperts is owed 500 USD for their work reviewing this issue.

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
