### ISSUE TITLE
Search - Tax and total value text are different heights

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43909]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43764
## Action Performed:
Precondition: Have at least one submitted expense with tax in a workspace chat.
1. Navigate to https://staging.new.expensify.com/
2. Open Search

## Expected Result:
The values should be in line

## Actual Result:
Tax and Total value text isn't line with each other in the row

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/df890a42-655e-4013-970f-85a296887bfe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment]
Double checking with the design team [here](https://expensify.enterprise.slack.com/archives/C03TME82F/p1718817117474369), as this may be on purpose. Will follow up as soon as I have confirmation!

**Comment by CortneyOfstad** [comment]
A PR is already in place for this [here](https://github.com/Expensify/App/pull/43733), so this can be closed!
