### ISSUE TITLE
Thread – Chat reloads and Join button appears briefly when join thread offline & back online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4641697
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Send a message
5. Create a thread and send a comment
6. Go offline
7. Click on 3 dot menu and leave the thread
8. Open thread again ang click on Join button
9. Go online and wait 1-2 minutes

## Expected Result:
Thread chat present

## Actual Result:
Chat reloads twice and Join button appear briefly when join thread offline and go back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/95b561a1-4b05-4c6e-b0f2-899dbf376020

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment]
@lanitochka17 hmm I wasn't able to reproduce this reliably on v85-3. Can you please re-test?

**Comment by jliexpensify** [comment]
Tried again on Staging v1.4.86-0. I can reproduce half one part of this: basically the "Join" button flashes for 1 second when you come back online, but that's it - it doesn't actually remain at the top:

![image](https://github.com/Expensify/App/assets/30815269/424002b1-578e-4290-8eb0-17b3d39dc0f4)

Since this isn't a major issue, I don't think this is worth fixing.
