### ISSUE TITLE
Task – Hidden appears as assignee when create task with existing name user you have no chat with

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ponikarchuks+315324@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Click on FAB and select Assign task
4. Enter task title and click next
5. Click on Assignee and enter user email with existing name you have no chat with
6. Click on Confirm task

## Expected Result:
Task with assignee name appears in the chat

## Actual Result:
Hidden appears as assignee of the task in the chat. Assignee name appears when open task details and back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a3164a24-d564-47f8-b800-0d40a54dcec6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @lanitochka17</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
Will review this in the morning

**Comment by VictoriaExpensify** [comment]
Hi @lanitochka17 - I haven't been able to recreate this issue:

![2024-06-24_09-59-01 (1)](https://github.com/Expensify/App/assets/54568958/3d308bba-b6ec-4596-85f4-923f760b92fe)


I do not have an existing chat with @a_member5000+1622

Please let me know if there is anything missing from the steps I have used to recreate this

**Comment by lanitochka17** [comment]
@VictoriaExpensify Hello, your steps were correct.
Now I can't reproducible this issue either

https://github.com/Expensify/App/assets/78819774/a76987ca-31ed-4547-b649-5f85efa5a872

**Comment by VictoriaExpensify** [comment]
Awesome, it looks like this one got magically resolved 🪄 

Closing!
