### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Upgrades] Create Upgrade RHN Panel, Confirmation Panel and connect to upgradeToCorporate action + apply to Report Fields

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#43916]
Part of https://github.com/Expensify/Expensify/issues/391954

**Individual steps to complete:**
- Create generic workspace upgrade page with dynamic title / description & icon
- Create upgrade confirmation page
- Connect the workspace upgrade page with the upgradeToCorporate policy action
- Create flow for Report Fields as a feature

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by garrettmknight** [comment]
Now that Sibtain is back we're back on it here. Currently testing the FE with the BE locally.

**Comment by garrettmknight** [comment]
@allroundexperts assigned you a small bug in the flow [here](https://github.com/Expensify/App/issues/44971)

**Comment by garrettmknight** [comment]
**Payment summary:**

**Contributor:** @allroundexperts $250
**Reviewer:** @ishpaul777 $250

@ishpaul777 offer out to you here: https://www.upwork.com/ab/applicants/1813979251771429535/hires?filter=ish&page=1

**Comment by allroundexperts** [comment]
@garrettmknight Can we hold my payment as well till we are done with this feature? The first iteration went to staging and we have a few minor bugs to squash. Once everything is good, we can handle the payment.

**Comment by garrettmknight** [comment]
Works for me @allroundexperts

**Comment by garrettmknight** [comment]
No prob, dropping to weekly. Lemme know when you're ready.

**Comment by garrettmknight** [comment]
Still waiting for payment - @ishpaul777 any update?

**Comment by garrettmknight** [comment]
Yep - paid!
