### ISSUE TITLE
[HOLD for payment 2024-07-02] [Search v1] Report screen in RHP is removed from navigation history after navigating to the chat in CentralPane

### ISSUE THREAD

**Issue by WojtekBoman** [Expensify/App#43918]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @WojtekBoman 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Open Search page.
2. Open any report in RHP.
3. Navigate to the chat in CentralPane.
4. Go back.

## Expected Result:

Report screen in RHP should be opened, it shouldn't be removed from the navigation history

## Actual Result:

Search page is opened, report screen in RHP is removed from the navigation history

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/47774969/e12de519-c874-474f-81fb-f21980cda73d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by bfitzexpensify** [comment]
Payment summary:

@parasharrajat to be paid $250 for C+ review

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
