### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Workspace - Bank account personal info isn't accepting characters with umlaut as name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43929]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Enable Workflows
4. Navigate to workspace settings - Workflows
5. Click on "Connect bank account"
6. Choose the manual option
7. Input "011401533" for Routing Number
8. Input "1111222233331111" for Account Number
9. Input "Ádám" for first name
10. Input "Horváth for last name

## Expected Result:
Characters with umlaut should be accepted

## Actual Result:
Bank account personal info isn't accepting characters with umlaut as name. Please enter a valid name error appears. These characters are accepted in the Save the world - teacher and principal flows

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1962573b-b68d-4a66-9efd-b0db7326e78a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01000955591143b611</li>
        <li>Upwork Job ID: 1805814229750460922</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 102945796</li>
<li>eucool | Contributor | 102945799</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
Opening up to community

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: @eucool $250
 - Reviewer: @suneox $250

**Comment by JmillsExpensify** [comment]
All contributors paid via Upwork and checklist complete. Closing this one!
