### ISSUE TITLE
Troubleshoot - There is no 'Client side logging' option

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to Settings > Troubleshoot

## Expected Result:
'Client side logging' option should be available

## Actual Result:
'Client side logging' option is not available

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6517401_1718725346258!photo1718725285](https://github.com/Expensify/App/assets/38435837/ff7558b2-a852-447e-96c8-192be21af5d8)

![Bug6517401_1718725346258!photo1718725284](https://github.com/Expensify/App/assets/38435837/1bcaf632-d021-4058-bd0a-5282e8f0886f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@yuwenmemon FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jayeshmangwani** [comment]
This isn't an issue; this was intentionally removed. more [here](https://github.com/Expensify/App/issues/43256#issuecomment-2154610196).

cc: @muttmuure

**Comment by muttmuure** [comment]
hang on a minute - I think there has been some confusion, which I apologize if I caused with my comment.

The linked comment is highlighting that desktop should show whatever is available from the troubleshoot menu on desktop, not to remove the options from Android.

**Comment by muttmuure** [comment]
Android should still have all of the troubleshoot options

**Comment by yuwenmemon** [comment]
@jayeshmangwani can you handle a revert?

**Comment by yuwenmemon** [comment]
Oh wow what a coincidence 😅

**Comment by jayeshmangwani** [comment]
I was going to tag you once PR pass the check 😃

**Comment by jayeshmangwani** [comment]
@yuwenmemon PR is ready to be merge please check it

**Comment by johnmlee101** [comment]
this is a newdot issue, not api so removing the label

**Comment by yuwenmemon** [comment]
@jayeshmangwani Can you retest on Android on staging and report back?

**Comment by yuwenmemon** [comment]
@jayeshmangwani Was the C+ reviewer of the PR that caused this regression and thus he fixed it as part of his responsibility to that PR.

Closing as this has now been resolved.

**Comment by jayeshmangwani** [comment]
>  @jayeshmangwani Can you retest on Android on staging and report back?

I am not able to access Android staging, but I can confirm that on the dev environment for Android,Now we can see the Client Side logging option

<details>
  <summary>Staging - No access</summary>
  
  
<img width="1100" alt="Screenshot 2024-06-19 at 12 29 28 PM" src="https://github.com/Expensify/App/assets/35371050/fd5f404f-c44d-47aa-be04-56c80bdaee25">

</details>

<details>
  <summary>Android - Client side logging</summary>
  
  https://github.com/Expensify/App/assets/35371050/92af31b9-4b65-48a4-8443-ee051532caf4

  
</details>
