### ISSUE TITLE
Taxes settings – Esabled tax rate in OldDot is not displayed in NewDot after page reload

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43932]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: log in to NewDot and OldDot with the same account.
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a WS and open it settings
4. Click on More features and enable taxes
5. Navigate to taxes
6. Open taxes page in Old Dot
7. Disable tax rate in OldDot
8. Reload the taxes page in NewDot and verify the tax rate is disabled
9. Open taxes page in Old Dot again and enable the same tax rate
10. Reload the taxes page in NewDot

## Expected Result:
Tax rate is esabled

## Actual Result:
Tax rate is disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/80a74206-20a4-446a-add0-a38c6075fe1c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by anmurali** [comment]
Cannot reproduce. It did require a page refresh to show that it was in fact enabled.
