### ISSUE TITLE
[$250] Incorrect behavior after reload page while creating an personal chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43937]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ZhenjaHorbach 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1718197565424019
 
## Action Performed:

1. Open App
2. Go to FAB > Start chat
3. Enter a non-existing email
4. Select the user
5. Reload the page

## Expected Result:
Should show DM with that user

## Actual Result:
After reloading and receiving a response from the server, the personal chat behaves like a group chat. Specifically, multiple avatars are displayed instead of just the user's avatar. Additionally, clicking on the header navigates to the Details page instead of the Profile page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/91abfacc-50cc-4280-b38b-0411032234e5

https://github.com/Expensify/App/assets/38435837/1b31817d-cee1-4ad4-9fc5-4b2687b11fb8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e1dfa4a8cbf88a3</li>
        <li>Upwork Job ID: 1804095874873388642</li>
        <li>Last Price Increase: 2024-08-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by sonialiap** [comment]
Thanks, Zhenja 👍  adding you as the C+

**Comment by sonialiap** [comment]
[bumped for proposals](https://expensify.slack.com/archives/C01GTK53T8Q/p1719926544674749)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by sonialiap** [comment]
Will close this if it's not reproducible during next week's retest

**Comment by sonialiap** [comment]
waiting for retest

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week) Good to close?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Fourth week)

**Comment by sonialiap** [comment]
Closing as non-reproducible
