### ISSUE TITLE
[$500] Payment issue for Aneeque for bug reporting

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#43946]
@aneequeahmad posted many bug reports when we were paying for them. Some didn't get paid, we're compensating $500 to wrap this up and close it out.  They will no be do anymore compensation for old bug reports. [Sheet with details here](https://docs.google.com/spreadsheets/d/15dkelL72wlUA417WeSfnQFz-OSPO_CDsv0_9BkG8Jio/edit?usp=sharing), I have reviewed it.

**Comment by aneequeahmad** [comment]
I have accepted the offer.

**Comment by mallenexpensify** [comment]
Contributor: @aneequeahmad paid $500 via Upwork

Thanks!
