### ISSUE TITLE
Android - Categorizing - Error after submitting expense to workspace via actionable whisper

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4646137
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to self DM
3. Track a manual expense
4. Select Categorize it from actionable whisper
5. Select a workspace and a category
6. Enter merchant and submit it
7. Go to transaction thread
8. Wait till it shows errors (might take a while)

## Expected Result:
Error will not show up after submitting the expense to workspace via actionable whisper.

## Actual Result:
Error shows up after submitting the expense to workspace via actionable whisper

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c6c442b0-4030-4d92-b1ff-e73e4bcb9275

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
reviewing

**Comment by dylanexpensify** [comment]
Based on @thienlnam's comments in linked GH< let's close
