### ISSUE TITLE
Track expense - Expense details briefly disappear when opening it after categorization

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43953]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Log in with a new expensifail account
3. Create a workspace
4. Tap on FAB - Track expense
5. Track an expense
6. Select "Categorize it" from the whisper message
7. Select any workspace
8. Select any category
9. Quickly open the tracked expense

## Expected Result:
Details should remain visible.

## Actual Result:
Expense details briefly disappear when quickly opening it after categorization.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/b4bd9883-d45b-4427-859d-3096a30720b2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@zanyrenney FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by zanyrenney** [comment]
No, I can't repro this. Nothing disappears and it functions as expected:

**Comment by zanyrenney** [comment]
![2024-06-24_17-30-39](https://github.com/Expensify/App/assets/56830058/eafe8adb-029f-4549-862d-b97453146a13)

I did the whole flow but its too long

**Comment by zanyrenney** [comment]
Closing as not reproducible. Working as expected.
