### ISSUE TITLE
[Payment card / Subscription] refactor ADD_DEBIT_CARD_FORM Onyx key to be agnostic of debit vs credit in subscription context

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#43963]
Right now we're using the Onyx key `ADD_DEBIT_CARD_FORM` in the add-payment-card page for the new subscription page. This is a misnomer because the card can be either a debit or credit card. https://github.com/Expensify/App/pull/43572 fixed this in the frontend, now we need to fix it in the backend.

**Extra Context:**
PR where it was introduced and discussion that initiated all this: https://github.com/Expensify/App/pull/42771#discussion_r1627855273
relevant slack thread: https://expensify.slack.com/archives/C036QM0SLJK/p1717606582669759
where we probably need to address it in web: https://github.com/Expensify/Web-Expensify/pull/42245/files#r1642211354
where App TODO is: https://github.com/Expensify/App/blob/c4482aae4e769cfd50975b8566de9d0ea25d3738/src/pages/settings/Subscription/PaymentCard/AddPaymentCard.tsx#L32
Slack thread keeping track of Callstack engineer who is working on the frontend portion of this: https://expensify.slack.com/archives/C036QM0SLJK/p1718659002462059

**Comment by blimpich** [comment]
Waiting on https://github.com/Expensify/App/pull/43572 to be merged I think before I can do this

**Comment by blimpich** [comment]
still waiting

**Comment by blimpich** [comment]
unblocked, will work on this today

**Comment by trjExpensify** [comment]
PR for this is on staging, will be closed once it hits prod!

**Comment by blimpich** [comment]
on production now
