### ISSUE TITLE
[$125] [Search v1] Colon symbol is displayed before tag if the previous tag level is not selected

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43980]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4641874
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Account is connected to QBO.
- Tags are enabled.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense with only "Customers/Projects" tag and leave "Classes" without tag.
4. Go to Search.
5. Look for the tag field.

## Expected Result:
The tag field will not display a colon symbol before "Customers/Projects" tag when "Classes" tag is not selected.

## Actual Result:
The tag field displays a colon symbol before "Customers/Projects" tag when "Classes" tag is not selected.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f8e586a2-8a9f-4e34-b1e7-dbcc73fb61b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da835f33410434f3</li>
        <li>Upwork Job ID: 1805690327359625458</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102915242</li>
<li>Nodebrute | Contributor | 103588771</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by CortneyOfstad** [comment]
Sorry — was OoO!

Asking about this in Slack [here](https://expensify.enterprise.slack.com/archives/C036QM0SLJK/p1719340930762839), as I am not 100% sure this is a bug

**Comment by luacmartins** [comment]
@akinwale did you get a chance to review the proposal above?

**Comment by akinwale** [comment]
@devguest07's [proposal](https://github.com/Expensify/App/issues/43980#issuecomment-2178964271) works here.

🎀👀🎀 C+ reviewed.

**Comment by CortneyOfstad** [comment]
PR draft is [here](https://github.com/Expensify/App/pull/44688) and is continuing to be worked on by @devguest07 👍

**Comment by luacmartins** [comment]
We haven't had any movement on the PR in a while, so I closed it and we should select a new contributor to work on this.

**Comment by luacmartins** [comment]
@Nodebrute go ahead

**Comment by CortneyOfstad** [comment]
@Nodebrute — just checking to see if you had any update? If you have a draft PR, please link here for tracking — thank you!

**Comment by CortneyOfstad** [comment]
I was not able to recreate either. The colon did not appear for me either. Going to close this and if the issue pops up again, we can re-address. Thanks!

**Comment by akinwale** [comment]
@CortneyOfstad Could you confirm if this would still be eligible for C+ payment [based on this thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1723512095867539) since an review was completed on the previous [PR](https://github.com/Expensify/App/pull/44688)?

Thanks.

**Comment by CortneyOfstad** [comment]
Based on the conversation [here](https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1724958371176519) — going to provide 50% payment to @akinwale for his work on reviewing the previous PR that was not completed. 

@akinwale a new offer was sent [here](https://www.upwork.com/nx/wm/offer/104003732) via Upwork. Let me know once you accept and I can get that paid ASAP. Thanks!

**Comment by akinwale** [comment]
> Based on the conversation [here](https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1724958371176519) — going to provide 50% payment to @akinwale for his work on reviewing the previous PR that was not completed.
> 
> @akinwale a new offer was sent [here](https://www.upwork.com/nx/wm/offer/104003732) via Upwork. Let me know once you accept and I can get that paid ASAP. Thanks!

Payment received on the initial auto-offer, thanks.

**Comment by luacmartins** [comment]
Seems like payment was handled. Closing.
