### ISSUE TITLE
[HOLD for Payment] [$125]  Settings - Wrong index when pressing Tab button in the Save the world section

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43991]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** crowdtest.expensify+test002@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Go to Account Settings
3. Tap on Save the World
4. Press the Tab on the keyboard

## Expected Result:
"I am a teacher" should selected when pressing a first Tab

## Actual Result:
Wrong index when tapping the Tab button in the Save the world section, "I am a teacher" first selected instead "I know a teacher"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/295897c6-41b9-4fe9-b93c-b954582dba2b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e452205241cde504</li>
        <li>Upwork Job ID: 1804295779857100557</li>
        <li>Last Price Increase: 2024-06-21</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 102862296</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by sakluger** [comment]
We should probably fix this for accessibility consistency, but it's such a small issue so I'm going to reduce the payout to $125.

**Comment by s77rt** [comment]
@devguest07 Your RCA makes sense and the solution works but can we add all the settings routes at once instead of adding each manually? (This is missing `SCREENS.SETTINGS.TROUBLESHOOT` as well)

**Comment by s77rt** [comment]
This is not a blocker. We can proceed with your solution.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/43991#issuecomment-2178785596)

**Comment by s77rt** [comment]
Looks like this was fixed by another PR https://github.com/Expensify/App/pull/43832

**Comment by cead22** [comment]
Bump @sakluger

**Comment by s77rt** [comment]
Should we close this one? The bug has been fixed by another PR

**Comment by sakluger** [comment]
Sorry for the delay, I missed this one entirely.

I'm going to check with my team to see if we should compensate for the work done here.

**Comment by sakluger** [comment]
We will pay out the full amount for this issue. @devguest07 could you please apply to the [Upwork job](https://www.upwork.com/jobs/~01e452205241cde504) or share your Upwork profile so that I can send you an offer? Thanks!

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @devguest07 $125, payable via Upwork (No offer yet)
Contributor+: @s77rt $125, please request on Newdot

**Comment by JmillsExpensify** [comment]
$125 approved for @s77rt

**Comment by sakluger** [comment]
Found @devguest07's Upwork profile and sent an offer: https://www.upwork.com/nx/wm/offer/103264866.

@devguest07 please let me know once you've accepted the offer so I can complete the payment and close the GH issue. Thank you!

**Comment by sakluger** [comment]
Thanks! All paid 👍
