### ISSUE TITLE
Android - Chat - Code block message fully not visible&for spaces boxes not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43996]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a chat
3. Enter `the cat is lot of`
4. Send the message

## Expected Result:
Entering short sentence in Code block with single backtick, must be fully visible and for spaces boxes must be shown

## Actual Result:
Entering short sentence in Code block with single backtick, fully not visible and for spaces boxes are not shown in Samsung device. Issue exists only in android app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7fe4ff40-ddfa-4f5a-b847-0a6e6ccfb2d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #Live Markdown

**Comment by jacobkim9881** [comment]
Is it reproducible? From my end, it's not. My machine is Galaxy A51, Android version 13.

https://github.com/Expensify/App/assets/46774300/9d5e2a00-8214-4a68-8b78-d920752b71dd

**Comment by stephanieelliott** [comment]
I think this is an edge case and doesn't fit into our roadmap at the moment. Gonna close
