### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [LOW] fast-equal lib Imported dependency is not listed in the package.json

### ISSUE THREAD

**Issue by gedu** [Expensify/App#43997]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** -
**Email or phone of affected tester (no customers):** -
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kacper-mikolajczak 
**Slack conversation:** https://callstack-hq.slack.com/archives/C01GTK53T8Q/p1718732844064939

## Action Performed:
Break down in numbered steps

The crash happens when you try to use Onyx using the build:watch function:

1. In one terminal tab, open the `react-native-onyx` directory and run `npm run build:watch`
2. In another terminal tab, open your React Native project and run `npx link publish <path_to_onyx_directory_on_your_machine>`
3. Then run your React Native project as normal!

## Expected Result:
Describe what you think should've happened

The App should run successfully 

## Actual Result:
Describe what actually happened

The app Crash because it can't find the `fast-equals` module

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes, you can keep using it 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2024-06-19 at 13 17 53](https://github.com/Expensify/App/assets/1676818/389aa9d3-adfd-43e0-9f32-727c9e847941)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183ec865fba64bd1b</li>
        <li>Upwork Job ID: 1803424421263671850</li>
        <li>Last Price Increase: 2024-06-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by gedu** [comment]
Hey, I'm Edu from callstack, I want to work on this issue

**Comment by mountiny** [comment]
@JmillsExpensify $250 to @rayane-djouah and we can close this

**Comment by JmillsExpensify** [comment]
Payment summary above is correct! $250 to @rayane-djouah. I just sent you an Upwork offer.

**Comment by JmillsExpensify** [comment]
All paid out!
