### ISSUE TITLE
mWeb/Chrome- Chat - After adding expense, previous part of chat, flashes but it´s never displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44005]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.85.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** bellicoignacio@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the https://staging.new.expensify.com/
website
2. Tap on the "+" button
3. Tap on "Submit Expense"
4. Complete the total amount of the expense
5. Tap on "Next"
6. Select a person
7. Tap on "Submit"
8. Check in the chat, the behaviour of the previous part of the conversation
9. Tap on the arrow on the top left corner
10. Open the same chat again and check if the conversation is still flashing

## Expected Result:
When adding an expense, the previous part of the chat, should still be visible for the user

## Actual Result:
When adding an expense, the user can only see that expense on the chat. Previous part of the conversation, flashes on the screen but never appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8d356e06-d3cd-4f1a-a6ba-0a67be68aba0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@lanitochka17 is this something you're able to consistently reproduce?

**Comment by lanitochka17** [comment]
@puneetlath I can't reproduce it now.

**Comment by puneetlath** [comment]
Ok, closing!
