### ISSUE TITLE
[Search v1] Implement DeleteMoneyRequestOnSearch command

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#44014]
We've unblocked Delete as a bulk action on the Search page, so we need to go ahead and implement [this section](https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=id.kt71e0n7yfsm) and of the doc for the Delete command only

**Comment by luacmartins** [comment]
Just assigned so I can keep track of the issue, but we're looking for internal volunteers here.

**Comment by alexpensify** [comment]
Noted, thanks!

**Comment by alexpensify** [comment]
It's not overdue; we need an engineer here, and it's a hot pick.

**Comment by luacmartins** [comment]
I started working on this one

**Comment by alexpensify** [comment]
@luacmartins thanks for the update! Looks like we have an internal reviewer here, so no label changes here.

**Comment by luacmartins** [comment]
PR is merged and deployed to prod. This is done.

**Comment by alexpensify** [comment]
There is no payment process needed here; it was handled by an all-internal team.
