### ISSUE TITLE
[HOLD for payment 2024-08-29] [QBO Export] [$250] Display QBO auto-sync errors and RBRs in NewDot

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#44016]
- HELD on https://github.com/Expensify/App/issues/44015

# Part of QBO Export and Error Handling in NewDot
Main issue: https://github.com/Expensify/Expensify/issues/350150
Doc section: https://docs.google.com/document/d/1aQl-AK_F6IqszWYG2aEllTsD5x3h4b8Zu0XEG0LuQ08/edit#heading=h.pmmx5zp5s75j
Project: [#wave-collect](https://github.com/orgs/Expensify/projects/129)

# Feature Description

As described in the doc, we need to display a RBR when there are errors in a policy connection’s last sync.

The RBR will show on the path to the integration connection settings (Avatar > Workspaces > [Workspace name] > Accounting > Connections):

- LHN Avatar: check if policy.connection.lastSync.isSuccessful is false in the [Indicator](https://github.com/Expensify/App/blob/d3d480545fdea6d51ded5866dd407881857bb04a/src/components/Indicator.tsx#L51)
- InitialSettingsPage: add the same check to [hasGlobalWorkspaceSettingsRBR](https://github.com/Expensify/App/blob/406139cf2120b25c28643f1e728d531fd8848a60/src/pages/settings/InitialSettingsPage.tsx#L189)
- WorkspaceInitialPage: add the same check to the connections menu item [here](https://github.com/Expensify/App/blob/18e2f09bdf5a250aabfa4cb40805b34b714d3420/src/pages/workspace/WorkspaceInitialPage.tsx#L260)
- PolicyAccountingPage: use policy.connection.lastSync.errorMessage to populate the errorText option for the QBO menu item [here](https://github.com/Expensify/App/blob/21abc8957a4127985317444c0fbaff27e6f7de1d/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L165-L196)

When the error is a credentials error (policy.connection.lastSync.isAuthenticationError is true), we’ll replace the ‘Sync now’ option in the connection’s 3-dot menu with a ‘Reconnect’ option [here](https://github.com/Expensify/App/blob/21abc8957a4127985317444c0fbaff27e6f7de1d/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L128-L133). The option will restart the Quickbooks Auth flow [as described in our initial QBO doc](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit#heading=h.41k48nficw63).

# Manual Test Steps

**Prerequisites**

- Collect workspace with an admin and member
- Setup QBO integration connection

**Steps**
1. Log into QBO and disconnect the Expensify app (Menu > Apps > Overview > Expensify 3-dot menu > Disconnect)
2. Log into NewDot as the admin
3. Verify there's a RBR on the path: Avatar > Workspaces > [Workspace name] > Accounting > QBO
4. Verify a red error message appears on the connection explaining the issue
5. Select QBO’s 3-dot menu
6. Verify there’s a “Enter credentials” option
7. Select “Enter credentials”
8. Verify a new window opens to log into QBO

# Automated Tests

- Add a test to IS verifying `errorMessage` and `isAuthenticationError` are set on the IntegrationLastSync
- Add an Auth test for `SavePolicy` verifying that an `INTEGRATIONSMESSAGE` action gets posted to the #admins room when the last sync is a failure

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc92666d46e99569</li>
        <li>Upwork Job ID: 1803462924011290436</li>
        <li>Last Price Increase: 2024-06-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lakchote** [comment]
Not held on https://github.com/Expensify/App/issues/44015 anymore.

**Comment by arosiclair** [comment]
Everything's deployed so this should be all set

**Comment by arosiclair** [comment]
Woops wrong issue 😅

**Comment by arosiclair** [comment]
I posted https://github.com/Expensify/Integration-Server/pull/8040 to fix the issue with connection sync errors in manual sync jobs not getting pushed to NewDot. I also noticed another issue with successful sync data not getting pushed and posted https://github.com/Expensify/Auth/pull/11925 to fix it. Hopefully we can get these out in the next couple days.

**Comment by arosiclair** [comment]
https://github.com/Expensify/App/pull/45251 is merged and on its way to staging.

**Comment by arosiclair** [comment]
I believe this will only need payment for @hungvu193's C+ reviews on these two PRs:

- https://github.com/Expensify/App/pull/46671
- https://github.com/Expensify/App/pull/45251

but that's after deploy and the regression period.

**Comment by hungvu193** [comment]
**Regression test:**

**Prerequisites**:

- Collect workspace with an admin and member
- Setup QBO (Xero) integration connection

**Steps:**

1. Log into QBO (Xero) and disconnect the Expensify app: Menu > Apps > Overview > Expensify 3-dot menu > Disconnect (Xero: 9 dots menu > Manage app connections -> Disconnect)
2. Log into NewDot as the admin
3. Verify there's an RBR on the path: Avatar > Workspaces > [Workspace name] > Accounting > QBO (Xero)
4. Verify a red error message appears on the connection explaining the issue
5. Select QBO's (Xero's) 3-dot menu
6. Verify there’s a “Enter credentials” option
7. Select “Enter credentials”
8. Verify a new window opens to log into QBO (Xero)
9. Enter the credentials and verify that you can connect to QBO (Xero) successfully.


**Change integration**:

1. Go to Accounting settings.
2. Open Other integrations.
3. Press connect.
4. Verify there is a confirmation modal.
5. Verify the flow is running correctly after pressing Confirm.
6. Verify new integration connection
7. All Connect buttons and integration flows were refactored. Verify that it is possible to add each integration:

- quickbooksOnline,
- xero,
- netsuite 
- intact

**Comment by hungvu193** [comment]
Based on the scope that was added to https://github.com/Expensify/App/pull/45251, Can I request a raise for the bounty of this issue 😄 ?

**Comment by muttmuure** [comment]
reviewing this tomorrow

**Comment by muttmuure** [comment]
How many PRs did you review in total?

**Comment by hungvu193** [comment]
We have 2 PRs:
- https://github.com/Expensify/App/pull/45251
- https://github.com/Expensify/App/pull/46671

The first one (https://github.com/Expensify/App/pull/45251) is a big PR, and we also added a lot of reactors to reuse the code.

**Comment by muttmuure** [comment]
Would $750 be about right?

**Comment by hungvu193** [comment]
Yes. Lovely 💪

**Comment by muttmuure** [comment]
Added regression test. Please go ahead and request payment through ND

**Comment by garrettmknight** [comment]
$750 approved for @hungvu193
