### ISSUE TITLE
[QBO Export] Push QBO auto-sync errors to NewDot

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#44015]
# Part of QBO Export and Error Handling in NewDot
Main issue: https://github.com/Expensify/Expensify/issues/350150
Doc section: https://docs.google.com/document/d/1aQl-AK_F6IqszWYG2aEllTsD5x3h4b8Zu0XEG0LuQ08/edit#heading=h.1anhpggeh7wm
Project: [#wave-collect](https://github.com/orgs/Expensify/projects/129)

# Feature Description

As described in the doc, we need to 

- add `errorMessage` and `isAuthenticationError` properties to the IntegrationLastSync data in IS when the [QuickBooksOnlineAutoSync job](https://github.com/Expensify/Integration-Server/blob/43469666ec188d2f151033ce57ddcb83eb841f0e/src/expensify/quickbooksonline/QuickbooksOnlineAutoSync.java#L56) fails.
- add an `INTEGRATIONSMESSAGE` action to the `#admins` room for the policy with the error message

# Manual Test Steps

None this will get tested with the frontend issue

# Automated Tests

- Add a test to IS verifying `errorMessage` and `isAuthenticationError` are set on the IntegrationLastSync
- Add an Auth test for `SavePolicy` verifying that an `INTEGRATIONSMESSAGE` action gets posted to the #admins room when the last sync is a failure

**Comment by lakchote** [comment]
I've assigned myself the issue, I've been back today after parental leave.

I'm finishing catching up and updating my vm and will look to solve this.

**Comment by lakchote** [comment]
Not overdue, PRs have been merged and deployed.

**Comment by arosiclair** [comment]
Everything's deployed so this should be all set
