### ISSUE TITLE
Keep all accounts visible, rather than hidden, for all accounts with *expensify.com

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#44013]
Problem: While at conferences we chat users 1:1 to follow up with them. If we chat a user from our demo.expensify.com or team.expensify.com account, users who have not signed up show up as hidden. This looks like a bug while you are trying to show the user the UI.

Solution: Make it so all accounts are visible to anyone using an *expensify.com account which will include Expensify.com (already done), demo.expensify.com, teams.expensify.com. 

Discussed in this thread: https://expensify.slack.com/archives/C03TBKRSB/p1718800785390349?thread_ts=1718689663.288659&cid=C03TBKRSB

**Comment by puneetlath** [comment]
Sorry @shawnborton @sakluger. Y'all can ignore this.

**Comment by puneetlath** [comment]
This is live.

**Comment by danielrvidal** [comment]
Thank you!
