### ISSUE TITLE
Add E2E tests for Live-Markdown

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#44028]
Problem:
Testing all markdown scenarios manually after any changes to the library is challenging and time-consuming. This often leads to regressions that are not immediately detected, negatively impacting the functionality and reliability of the markdown library.

Solution:
Implementing end-to-end (E2E) tests for live markdown ensures comprehensive coverage of all possible markdown scenarios. Automated E2E tests can quickly identify regressions and validate that recent changes do not break existing functionality. This approach enhances the robustness of the markdown library, ensuring consistent and reliable performance across all use cases.

**Comment by thienlnam** [comment]
Currently being worked on here https://github.com/Expensify/react-native-live-markdown/pull/337 by @BrtqKr

**Comment by tomekzaw** [comment]
I think we can close this issue because https://github.com/Expensify/react-native-live-markdown/pull/337 has been merged.
