### ISSUE TITLE
[HOLD for payment 2024-07-25] [QBO Export] [$250] Implement manual report exports

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#44022]
# Part of QBO Export and Error Handling in NewDot
Main issue: https://github.com/Expensify/Expensify/issues/350150
Doc section: https://docs.google.com/document/d/1aQl-AK_F6IqszWYG2aEllTsD5x3h4b8Zu0XEG0LuQ08/edit#heading=h.xw0s9oqvo44s
Project: [#wave-collect](https://github.com/orgs/Expensify/projects/129)

# Feature Description

As described in the doc, we need to 

- Add new `exportToIntegration` and `markAsManuallyExported` actions
- Add a new Export menu item to the report details page
- Create a new `ReportDetailsExportPage` with "Export" and "Mark as exported" options
- Update `ReportPreview` actions to show export options
- Update the `MoneyReportHeader` to show export options

# Manual Test Steps

**Prerequisites**

- Collect workspace with an admin and member
- Setup QBO integration connection

**Steps**
1. Log into QBO and disconnect the Expensify app (Menu > Apps > Overview > Expensify 3-dot menu > Disconnect)
2. Log into NewDot as the admin
3. Verify there's a RBR on the path: Avatar > Workspaces > [Workspace name] > Accounting > QBO
4. Verify a red error message appears on the connection explaining the issue
5. Select QBO’s 3-dot menu
6. Verify there’s a “Enter credentials” option
7. Select “Enter credentials”
8. Verify a new window opens to log into QBO

# Automated Tests

**Prerequisites**

- Collect workspace with an admin and member
- Setup QBO integration connection
- An approved expense report that failed to export

**QBO**

1. Open the 3-dot menu on the failed report
2. Verify there’s an “Export” Item
3. Select it
4. Verify there are “Quickbooks Online” and “Mark as manually entered” options
5. Select Quickbooks Online
6. Verify 
7. A system message “exported to QuickBooks Online” is added to the report
8. The red dot on the report in the LHN is removed

**Mark as exported**

1. Open the 3-dot menu on the failed report
2. Verify there’s an “Export” Item
3. Select it
4. Verify there’s a “Mark as manually entered” option and select it
5. Verify 
6. A system message “marked this report as manually exported to QuickBooks Online” is added to the report
7. The red dot on the report in the LHN is removed
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f33d4c08ab8cd9c</li>
        <li>Upwork Job ID: 1803471658259345111</li>
        <li>Last Price Increase: 2024-06-19</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 102807841</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by trjExpensify** [comment]
Hans is taking the C+ on this as part of the QBO export project. I believe @kosmydel will be implementing this one as well.

**Comment by kosmydel** [comment]
Commenting for assignment :)

**Comment by trjExpensify** [comment]
Donezo!

**Comment by hungvu193** [comment]
**Regression Test**:

***Prerequisites***:
- Collect workspace with an admin and member
- Setup QBO integration connection


**Test 1**

1. Open the report details (click the carret in the header) on the failed report (See https://github.com/Expensify/App/pull/44170#issuecomment-2233466914 to make a failed report).
2. Verify there’s an “Export” Item button.
3. Select it
4. Verify there’s a “Mark as manually entered” option and select it
5. Verify A system message “marked this report as manually exported to QuickBooks Online” is added to the report and the red dot on the report in the LHN is removed
6. Click on the "Export" item and "Mark as manually entered" again, verify the "reports have already been exported" modal is displayed.

**Tests 2:**
1. Turn off auto sync in Workspace -> Accounting -> Advanced.
2. Create a new expense in the policy.
3. Pay expense elsewhere.
4. A Export button should appear in the report preview and report header.
5. Click on the "Export" button in the report preview
6. Verify everything works as expected.

Do we 👍  or 👎  ?

**Comment by hungvu193** [comment]
Feel free to close this one. I'll request on ND later

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @kosmydel (no payment needed)
- Reviewer: @hungvu193 $250 (via newdot requests)

**Comment by hungvu193** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
