### ISSUE TITLE
mWeb - Chat - Choosing any offence after Refreashing page takes you to home page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to 1:1 chat
2. Long press on a message sent from the other user to bring the action menu
3. Click on the flag as offensive
4. Refresh page
5. Click on any offence

## Expected Result:
You are taken to the opened Chat

## Actual Result:
You are taken to the main(Home) page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/04b6287e-e239-484a-aeec-d66cf43181c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@lanitochka17 this isn't filled out properly, is this Mobile only? Android? Ios?

**Comment by jliexpensify** [comment]
I tried on Chrome (Android, Pixel 7) and couldn't reproduce. When I refresh, I get taken back to the `Flag as offensive` page.
