### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] IOU - Members page is blank

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44040]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log into staging.new.expensify.com
2. Navigate to a conversation
3. Create an IOU
4. Click on the header of the IOU to access the members

## Expected Result:
A members page/ modal should open listing all the members

## Actual Result:
The modal is empty (blank)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cf7c5f36-dae9-46fb-a2d1-7cd0fb6db1f9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fcedc031d85e839</li>
        <li>Upwork Job ID: 1805044099624774803</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103086318</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Member list page is empty/blank when pressing the multiple display name of a report preview action.

### What is the root cause of that problem?
In this [old PR](https://github.com/Expensify/App/pull/24624), we navigate the user to the report participants page if it's an IOU report (which it is in our case). We do this for both AvatarWithDisplayName (used in the IOU report header) and ReportActionItemSingle display name.

However, all participants are `hidden`, so when we get the member list, we get an empty list.
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/pages/ReportParticipantsPage.tsx#L72-L73
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/libs/ReportUtils.ts#L1850-L1856

If we see the AvatarWithDisplayName case, we now update it so that for the IOU report, we navigate to the report detail instead of the participants page.
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/components/MoneyReportHeader.tsx#L209-L211
https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/components/AvatarWithDisplayName.tsx#L78-L82

Also, the IOU report detail page doesn't have a members section.
<img width="388" alt="image" src="https://github.com/Expensify/App/assets/50919443/7e564361-3875-4c58-9447-6875317052f3">

### What changes do you think we should make in order to solve the problem?

I suggest changing the navigation to the report details page too for the IOU report.
```
Navigation.navigate(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(iouReportID));
```

**Comment by VictoriaExpensify** [comment]
I agree this looks buggy and have been able to reproduce the issue:

![image](https://github.com/Expensify/App/assets/54568958/efdeb1cf-a2f6-45f6-ae20-bc8e1ddf5c04)

I believe this belongs to Project VSB

**Comment by VictoriaExpensify** [comment]
So sorry, I was OoO for a few days and am catching up. 

Oh hmm this is a really good question. I initially thought that should show members but perhaps that "members" heading is a bit of a red herring. I'm going to get some input from others - I'll get back to you

**Comment by VictoriaExpensify** [comment]
Posted in Slack for some more eyes - https://expensify.slack.com/archives/C02NK2DQWUX/p1719985125522659

**Comment by mallenexpensify** [comment]
From Isabella with QA
> So, in my case, I would expect that the members participating in the IOU are displayed since you're clicking in the participants mention.
If I would want to see the IOU details, then I would click the preview.
I don't think that we have a test to specifically validate this in TestRail so searching there would not return anything.

**Comment by bernhardoj** [comment]
Hmm, the members page only shows the non-hidden member (except for group chat). When we create a new IOU, all of the participants are hidden. The IOU report details page also doesn't show the Members field. It only shows once we add a comment to the report.

Maybe we can show the detail page when all the members are hidden OR make an exception for the IOU report too so it shows all members, even the hidden one.

**Comment by mallenexpensify** [comment]
>  When we create a new IOU, all of the participants are hidden. 

@bernhardoj do you know we do this?  Are there other examples of when/where we handle it like this?

For whatever we end up choosing to do here, I'd love for there to be precedence for the choice vs a one-off _fix_

**Comment by bernhardoj** [comment]
> do you know we do this? Are there other examples of when/where we handle it like this?

I'm not 100% sure why we do that, but I think a hidden participant is a participant who is in the chat but hasn't participated in a chat yet, which explains that they become non-hidden after adding a message. The other examples are group chat and new 1:1 DM, but for group chat, we always shows all members, including the hidden one.
https://github.com/Expensify/App/blob/7b558ef7fb9908223d899b54ad3d0156bc8fcb81/src/pages/ReportDetailsPage.tsx#L144-L147

**Comment by mallenexpensify** [comment]
Thanks @bernhardoj, those details are helpful. I don't understand the logic or reasoning behind the decision of when to show and not show. Here are a couple examples. 
- I can see updates in LHN/search for #big-rig but I'm not a member. 
- When I visit a thread in #big-rig, where I haven't commented, when I click on members, it briefly shows me then I'm _removed_.  I understand why I'm not a member there but why does it show/remove quickly?

https://github.com/Expensify/App/assets/22508304/1d2600f4-9aac-4bf9-9f8a-f64ce995c72c

For this specific issue, it _makes sense_ to me that we'd want to show the _members_ involved in an IOU.  I'm asking in #expensify-open-source to get more 👀 before moving forward. 
https://expensify.slack.com/archives/C01GTK53T8Q/p1720568142568069

**Comment by mallenexpensify** [comment]
[Also posted in #vip-vsb. 
](https://expensify.slack.com/archives/C066HJM2CAZ/p1720645698277469)

Let's move forward with what's currently stated in the OP for expected behaviour
> A members page/ modal should open listing all the members

**Comment by bernhardoj** [comment]
Updated my [proposal](https://github.com/Expensify/App/issues/44040#issuecomment-2179881186) to include a solution to show all IOU report members.

**Comment by mallenexpensify** [comment]
If this involves the report.participants key at all, will you please comment here? We have other bugs related to that.

**Comment by bernhardoj** [comment]
> If this involves the report.participants key at all, will you please comment here?

@mallenexpensify We won't touch the `report.participants` key.

PR is ready

cc: @allgandalf

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by stephanieelliott** [comment]
Hey @VictoriaExpensify a heads up I've issued the payment for @allgandalf per this [Slack conversation]([45232](https://github.com/Expensify/App/issues/45232)), will let you post the payment summary though!

**Comment by jasperhuangg** [comment]
Not overdue just sorting out payment details

**Comment by VictoriaExpensify** [comment]
Contributor: @bernhardoj owed $250 via NewDot
Contributor+: @allgandalf paid $250 via Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
