### ISSUE TITLE
[$250] Workspace - Hidden  Appears in members when clicking "Invite Members" button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44041]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in with a new account > Account Settings
2. Navigate to Workspace > Create Workspace > Go to Members > Click "Invite Members" button

## Expected Result:
No hidden text should appear when clicking the "Invite Members" button

## Actual Result:
Notice that the text "Hidden" briefly appears inside the Members section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/36959114-4f27-4041-8d85-ddf9ac452004

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf54cdd699edddd6</li>
        <li>Upwork Job ID: 1803821385140635715</li>
        <li>Last Price Increase: 2024-06-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by lanitochka17** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by OfstadC** [comment]
I'm not able to reproduce

![2024-06-20_09-09-07 (1)](https://github.com/Expensify/App/assets/11722379/c17b3b19-fd2b-402f-b6cc-bcaf76f62911)

**Comment by OfstadC** [comment]
Ope! After I navigated away from the page, and came back, "Hidden" was listed and stuck 😬 
<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/11722379/1b0cac44-bac2-4068-9d7e-bdda54109c37">

**Comment by OfstadC** [comment]
>Simplified Collect (new Workspace settings pages e.g categories, members  taxes, workflows etc)

Based on this, I believe this is #wave-collect

**Comment by nyomanjyotisa** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is text "Hidden" appears on Member section after click "Invite Members" button

### What is the root cause of that problem?
There is another user with accountId 0 after click "Invite Members" button
![Screenshot 2024-06-21 at 23 22 11](https://github.com/Expensify/App/assets/73281575/e4be8aa2-5754-456a-97da-69f1e7213998)

### What changes do you think we should make in order to solve the problem?
Don't add the data to member list data if accountId equals to 0
![image](https://github.com/Expensify/App/assets/73281575/77ca8f05-5949-464a-a1ed-f88d2a3660a5)

### What alternative solutions did you explore? (Optional)
Filter member list data to exclude member with name == 'Hidden'
![image](https://github.com/Expensify/App/assets/73281575/043a7f9f-eaa4-4420-8997-21cddea42df2)

**Comment by Pujan92** [comment]
Thanks for the proposal @nyomanjyotisa. Your RCA seems to be incomplete where we also have to find out why the other user has been assigned the accountId 0. 
Regarding your solution I don't think we need to filter out accountID with the value 0 specifically.

**Comment by OfstadC** [comment]
Any updates here? 😃

**Comment by Pujan92** [comment]
Looking for more proposals as I am not yet fully convinced with @nyomanjyotisa's proposal.

**Comment by OfstadC** [comment]
Since this isn't critical, I don't think we need to raise the bounty ...

**Comment by abzokhattab** [comment]
Cannot reproduce it.

**Comment by OfstadC** [comment]
I'm also not able to reproduce anymore 🤔

**Comment by OfstadC** [comment]
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1719849246671609)

**Comment by kavimuru** [comment]
I am not able to reproduce 

https://github.com/Expensify/App/assets/43996225/9839b3de-2eca-47ff-985b-9ef98d10664d
