### ISSUE TITLE
`hermesc` fails on ~50% of Android builds

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#44050]
## Problem
Our Android CI/CD builds fail ~50% of the time when building Android since enabling New Architecture.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createBundleProductionReleaseJsAndAssets'.
> A problem occurred starting process 'command '/home/runner/work/App/App/node_modules/react-native/ReactAndroid/hermes-engine/build/hermes/bin/hermesc''
```

Latest build failure: https://github.com/Expensify/App/actions/runs/9588292696/job/26440031076

Raw Logs: [10_Run Fastlane beta.txt](https://github.com/user-attachments/files/15906251/10_Run.Fastlane.beta.txt)

We think we've confirmed that this can still happen without any caches enabled, but we are open to trying removing caching or any intermediate steps to try to reduce the number of failures. We usually are able to get it to build successfully on the second or third build try.

## Solution
Fix it!

cc @WoLewicki @j-piasecki

**Comment by WoLewicki** [comment]
Commenting

**Comment by j-piasecki** [comment]
Commenting too

**Comment by AndrewGable** [comment]
We CP-ed this and it's working, we will reopen if there are any further issues.
