### ISSUE TITLE
[$250] [Payment card / Subscription] No forward slash in the `add-payment-card` form field for expiration date

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#44051]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue reported by:** @blimpich

## Action Performed:
Break down in numbered steps
1. create a new account
2. create a workspace on that account
3. go to `https://staging.new.expensify.com/settings/subscription/add-payment-card`
4. look at the expiration date field and verify that the placeholder value is `MMYY`
5. type `0424` into the field

## Expected Result:
Describe what you think should've happened

The placeholder should be `MM/YY` and I should be able to type `0424` and have it be formatted as `04/24`

Additionally, the user should not be able to type characters that aren't digits.

## Actual Result:
Describe what actually happened

It shows up without the forward slash `/`

## Screenshots/Videos

![Screenshot 2024-06-19 at 11 29 32 AM](https://github.com/Expensify/App/assets/17171674/3738d476-3a09-4e52-91f7-f80821b744b8)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cf3d8d608f1cea2</li>
        <li>Upwork Job ID: 1803928352567993588</li>
        <li>Last Price Increase: 2024-06-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by blimpich** [comment]
Not prioritizing this now because I think we can make this available to contributors, but I want to wait till the end to end flow for this is finished so that we can make sure we don't break it by updating this field.

**Comment by mwmetcalf1** [comment]
Proposal

  Modify the screen template to be MM/YY  not MMYY.  The validation for that format is exists so no other changes are needed.

**Comment by mananjadhav** [comment]
@puneetlath @blimpich Is this a reported as a bug or a feature request? 

We had removed `/` logic from the `Add a debit card` page in this [issue](https://github.com/Expensify/App/issues/13133). I also remember discussing this long back that we shouldn't format the user input (can't find the slack/thread). So do we really need to work on this? or :donothing:

**Comment by blimpich** [comment]
Hmm, I assumed it was a bug because in Expensify Classic we have a `/` in the expiration field for when we add a card. I thought we missed it here. Maybe I'm missing context. I'll discuss internally and get back to you.

**Comment by blimpich** [comment]
Brought discussion to slack in #wave-collect channel [here](https://expensify.slack.com/archives/C036QM0SLJK/p1719008642331639)

**Comment by blimpich** [comment]
Apologies for everyone who has investigated this issue, we've decided internally that we don't want this feature at this time. Closing.
