### ISSUE TITLE
[FT] Update "Start a call" prompt in kebab menu AND update "schedule a call" in meet your setup specialist copy 

### ISSUE THREAD

**Issue by LLPeckham** [Expensify/App#44076]
Hello there! As proposed in [this Slack post](https://expensify.slack.com/archives/C036QM0SLJK/p1718278089862859) stemming from the onboarding full throttle (Manage my team's expenses intent), we would like to streamline the call to action for when a new user is prompted to book a call with their Setup Specialist. 

We would like to change the copy in two places so that it is the same. 

**Current copy:**
- Place 1: Kebab menu > `Start a call`
- Place 2: `Meet your Set up Specialist` task in onboarding flow task body copy > `schedule a call` hyperlink

**New copy for both:**
`Book a call`

Both of these will link out to the same place (the setup specialists calendly). 

![Screenshot 2024-06-20 at 2 14 22 PM](https://github.com/Expensify/App/assets/6799061/34a27a60-e020-4578-83f4-db5199f68a60)

**Comment by mountiny** [comment]
Both PRs up and just waiting for a review

**Comment by trjExpensify** [comment]
We done here?

**Comment by mountiny** [comment]
Yes
