### ISSUE TITLE
[HOLD for payment 2024-07-10] Android - Composer - Suggestion list appears amid report view after sending multiline text

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44077]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Open any chat.
3. Tap on the composer.
4. Create many new lines until the composer is scrollable.
5. Enter @ and select a user from the list.
6. Send the message.
7. Enter @.

## Expected Result:
The mention list will appear above the cursor.

## Actual Result:
The mention list appears in the middle of the report view.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/0ca6d03b-b28e-469e-b8d5-2ce96068f428

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by m-natarajan** [comment]
@grgia FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by mountiny** [comment]
This also seems related to https://github.com/Expensify/App/pull/42630 @perunt @puneetlath

**Comment by mountiny** [comment]
Doming from here https://expensify.slack.com/archives/C035J5C9FAP/p1718916284226989 demoting and @perunt can handle this once online

**Comment by perunt** [comment]
fixed
will add screen records in a couple of minutes

**Comment by grgia** [comment]
Thank you @perunt !

**Comment by MitchExpensify** [comment]
*Payment summary*:

- $250 @perunt C (Upwork)
- $250 @sobitneupane C+ (NewDot)

Does this look alright to you?

**Comment by perunt** [comment]
I'm from the Margelo agency, and we get our payments separately, so all good

**Comment by MitchExpensify** [comment]
Cool, closing as the only payment needed is via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
