### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Feature Request: When uploading, automatically reduce the size of receipt image if greater than 24mb

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718830152208309

## Problem:
Unable to upload an image taken from the camera because it’s larger than 24MB

## Solution:
~~Option to reduce the size on device before uploading~~

>  When uploading, automatically reduce the size of receipt image if greater than 24mb
> This would mean there would be no change in the UI. The user likely wouldn't even know we did it—but their receipt image would be uploaded smoothly with no issues.
> 
> Note
> 
> I think this would only apply to receipt image uploads—NOT images uploaded as attachments in chats

## Context/Examples/Screenshots/Notes:

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b098d2eb27081851</li>
        <li>Upwork Job ID: 1805353003843890323</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103127270</li>
<li>nkdengineer | Contributor | 103127271</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by dannymcclain** [comment]
Is this a suggestion to implement a feature where our app reduces the file size of a local image before uploading? 🤔 

Either way, I don't think we should do this. File size limits are SUPER common amongst all the apps I use daily, and I've never once seen any of them try to reduce a file's size for me (also, 24mb is a pretty generous size limit). I think we should leave this responsibility on the user personally. cc @Expensify/design for thoughts.

**Comment by AndrewGable** [comment]
Just for reference- This is step backwards from what OldApp does. I can upload a picture from my camera no problem on OldApp, I have to resize it myself on NewDot. 

I thought as a user this is a UX oddity.

**Comment by dannymcclain** [comment]
@AndrewGable are the normal photos your phone takes more than 24mb? I only ask because that seems _reaaaaally_ big. Most of the photos on my phone (that I've taken) are around 1–3mb.

**Comment by AndrewGable** [comment]
Yes, new iPhones take really big pictures 😄 Looks like this receipt was ~30MB

![IMG_71FD4D44B4C9-1](https://github.com/Expensify/App/assets/2838819/f1eb3737-62a1-4852-8c7c-70ed5ce1ae6a)

**Comment by shawnborton** [comment]
How does OldDot handle this? Does it automatically resize the photo?

**Comment by AndrewGable** [comment]
> I'd like to avoid this becoming like a whole user-flow centered around resizing an image before upload

Agree!

I just think we should support cases that we did in the past, uploading a receipt from my phone's camera is one of those cases.

**Comment by dannymcclain** [comment]
Nice, that sounds good to me. Thanks for talking it out!

**Comment by dubielzyk-expensify** [comment]
Yeah. I actually think resizing the image automatically would be super neat cause just a warning is a blocking action. This isn't one of those scenarios where they'd want fine controls on image quality etc, they just wanna upload a receipt. 

I also don't like the idea of having the user having to resize or do it themselves through a UI, so I'm all for automatically doing this.

**Comment by dannymcclain** [comment]
100% agree Jon!

**Comment by dannymcclain** [comment]
So based on this conversation, @Expensify/design @AndrewGable would you all be comfortable updating this feature request to:

`Feature Request: when uploading, automatically reduce the size of receipt image if greater than 24mb`

This would mean there would be _no_ change in the UI. The user likely wouldn't even know we did it—but their receipt image would be uploaded smoothly with no issues.

> [!NOTE]  
> I think this would **only** apply to receipt image uploads—NOT images uploaded as attachments in chats

**Comment by AndrewGable** [comment]
Yes - That sounds great!

**Comment by OfstadC** [comment]
Thanks team! 😃 - Added to Wave Collect and posted in Slack

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Feature Request: When uploading, automatically reduce the size of receipt image if greater than 24mb

### What is the root cause of that problem?
This a feature request

### What changes do you think we should make in order to solve the problem?

The problem at hand is, we have an image larger than 24mb, we want to resize it to less than 24mb.

For an image size to be reduced, there're 2 main ways:
- Reducing the image width and height
- Reducing the image quality (aka increase compression)

I think the first one is preferrable here, because the image quality will remain and it will not be blurry, just the excessive size will be reduced. And for first method, we're reasonably sure what the image size will be after we resize it, because the image size will roughly be proportional to its dimensions (if same quality). Meanwhile the quality is not directly proportional to the size.

The steps:
- First we need to add a method that takes in width, height, size, targetSize and return the new width and height that the image should be resized to
```
const calculateResizedDimensions = (width, height, currentSizeBytes, targetSizeBytes) => {
  // Ensure input values are valid
  if (width <= 0 || height <= 0 || currentSizeBytes <= 0 || targetSizeBytes <= 0) {
    throw new Error('Invalid input values');
  }

  // Calculate the scaling factor based on the target size in bytes
  const scaleFactor = Math.sqrt(targetSizeBytes / currentSizeBytes);

  // Calculate the new dimensions
  const newWidth = Math.round(width * scaleFactor);
  const newHeight = Math.round(height * scaleFactor);

  return { newWidth, newHeight };
};
```
- We could also add a margin of safely like 10%, we can multiply the `scaleFactor` with 0.9, to avoid a case that the after-resized image will still be larger than the `targetSizeBytes`. So we can expect that the resized image will be roughly 20mb in size
- Now we need a library that will allow us to resize the image, it should provide a function that takes in an image and target width and height, and it will resize the image to that width and height. This looks like a good one for `react-native` https://github.com/bamlab/react-native-image-resizer, similar libs should be found for `react`/web
- Now, after the user selects the image (could apply only to receipt), if the image is more than max size (24MB), we use the above library, image path, target width and height from `calculateResizedDimensions`, to get the new image file. Then continue to use it in validations and uploads to back-end. We can remove the client-side max size validation for receipt now, because the receipt image will never exceed that size.

### What alternative solutions did you explore? (Optional)
None

**Comment by nkdengineer** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/44084#issuecomment-2188022852) in case we decided to reduce image quality to reduce the size

**Comment by AndrewGable** [comment]
Just for reference, on OldApp we reduce the size of the image to a max of 2400x2400px (keeping aspect ratio the same). I think we could choose a round number of 2MB for the file size?

**Comment by OfstadC** [comment]
@shubham1206agra Can you provide an update on the [updated proposal ](https://github.com/Expensify/App/issues/44084#issuecomment-2188654094) by EOD tomorrow 😃 Thanks!

**Comment by AndrewGable** [comment]
I would suggest reducing the quality and the size, but do not crop or mess with aspect ratio.

**Comment by OfstadC** [comment]
Since this is a Polish, I don't think we need to adjust the bounty. I'm OoO for starting tomorrow until next week - but i'll be popping in to check on issues 😃

**Comment by nkdengineer** [comment]
> @nkdengineer We should not use any new library.

Sure @shubham1206agra, I updated [the proposal](https://github.com/Expensify/App/issues/44084#issuecomment-2188022852) to suggest to use the existing `expo-image-manipulator` library's `resize` action to do this.

**Comment by nkdengineer** [comment]
> @nkdengineer Can you create a test branch please?

I'll create this tomorrow, thanks for the patience!

**Comment by OfstadC** [comment]
Sorry folks was OoO for the Holiday. Looks like we can expect an updated from @nkdengineer today 😃

**Comment by nkdengineer** [comment]
Sorry I haven't been able to finish this earlier, I'll provide an update soon

**Comment by OfstadC** [comment]
@nkdengineer Could you we have an update by EOD tomorrow? Thank youuu 😃

**Comment by nkdengineer** [comment]
Pushing test branch now!

**Comment by nkdengineer** [comment]
> @nkdengineer Can you create a test branch please?

@shubham1206agra Here's the test branch for your review! https://github.com/nkdengineer/App/tree/fix/44084

Polish needed in PR phase:
- It works well on Web, similar changes can be done in Native
- The utils methods will be extracted to its own file
- `manipulateAsync` logic is taking reference from https://github.com/Expensify/App/blob/b9cb411afa315e6bf82d68187ca535be405c4902/src/libs/cropOrRotateImage/index.ts#L8, we might need to allow customizing some params while resizing, like in there

**Comment by luacmartins** [comment]
I like @nkdengineer's proposal too. Let's go with it and set 2MB as the target file zie.

**Comment by nkdengineer** [comment]
I'm investigating the PR.

**Comment by nkdengineer** [comment]
@shubham1206agra we have a open PR [here](https://github.com/Expensify/App/pull/45448)

**Comment by OfstadC** [comment]
Hey team! I had to send you new offers in Upwork. Please accept your relevant offer below so I can issue payment. Thank you 😃 

@shubham1206agra [Offer](https://www.upwork.com/nx/wm/offer/103530569)
@nkdengineer [Offer](https://www.upwork.com/nx/wm/offer/103530582)

**Comment by OfstadC** [comment]
### Payment Summary 

@shubham1206agra paid $250 via Upwork
@nkdengineer Offer pending

**Comment by nkdengineer** [comment]
@OfstadC Thanks 🙇  I have accepted the offer

**Comment by OfstadC** [comment]
Updated payment summary. 

This is just waiting on [@shubham1206agra] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

@shubham1206agra can we get an update by EOD? Thanks!
