### ISSUE TITLE
Simplify unread functionality in ReportActionsList

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#44088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @arosiclair 
**Slack conversation:** N/A

## Details

To fix [this bug](https://github.com/Expensify/App/issues/41935), we added more complexity to the `ReportActionsList`. I realized this shouldn't be necessary but requires a refactor to simplify the ReportActionsList and its unread functionality. This should make that component easier to maintain and less prone to future bugs. Specifically, we should

- Remove `lastReadTimeRef` and `markerLastReadTimeRef`
- Add a new `markerTime` state variable
  - Set to the `report.lastReadTime` when the `reportID` changes
  - Set to the `reportAction.created` when a manual unread event is received [here](https://github.com/Expensify/App/blob/df5e65f6344862ba3ae2473acfe44e3b365587d6/src/pages/home/report/ReportActionsList.tsx#L307-L323)
- Replace `currentUnreadMarker` with `unreadMarkerReportActionID`
  - this should be a memoized value that should evaluate to the same result of [calculateUnreadMarker](https://github.com/Expensify/App/blob/f618a94c486b80aebab584c52288a7013ffad64a/src/pages/home/report/ReportActionsList.tsx#L502-L526) and only re-evaluates when `markerTime` changes.
- Investigate if `cacheUnreadMarkers` is necessary and remove it if it isn't

This should remove the need to track timestamps in two different refs and remove a few confusing effects we have written in that component.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

N/A

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
No progress on this yet

**Comment by jliexpensify** [comment]
@arosiclair want to move this to Monthly, or is Weekly still appropriate?

**Comment by arosiclair** [comment]
Yeah that sounds fair. I think it's unlikely I can get to this next week.

**Comment by arosiclair** [comment]
Took over the original issue and I'm going to address this there.
