### ISSUE TITLE
Chat - Group chat appear when secondary login transfer to primary login email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** gocemate+a348@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43633
## Action Performed:
1. Login with new email address
2. Press FAB > Start chat
3. Search for a secondary login of a user and choose it

## Expected Result:
User should navigate to the primary login email

## Actual Result:
In transferring process from secondary to primary login Group chat with both primary and secondary contact appears shortly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/efce366f-b016-4da1-8651-3c27902f9567

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by OfstadC** [comment]
Hmmm i'm not sure I understand this exactly. Was the email you're searching for a secondary login for [gocemate+a348@gmail.com](mailto:gocemate+a348@gmail.com)?

**Comment by OfstadC** [comment]
Going to try testing this again today 🤔

**Comment by kavimuru** [comment]
@OfstadC tester is still able to reproduce

https://github.com/Expensify/App/assets/43996225/0b800d62-a4f1-4c1a-bb17-3bce0826b6bf

**Comment by OfstadC** [comment]
Okay - was able to reproduce - My wires were crossed and I was trying to chat with a Copilot instead or a Secondary Login 🤦‍♀️ 

Okay - so not only did I experience this, but the primary changed to "Hidden"
testcorinne74secondary@gmail.com is the Secondary login on testcorinne74@gmail.com

![2024-06-26_10-41-37 (1)](https://github.com/Expensify/App/assets/11722379/dfbbe36d-1f23-48ff-8c75-03427c6daeda)

**Comment by OfstadC** [comment]
Raised a Slack thread, but I'm not sure this is worth fixing. Will update soon

**Comment by OfstadC** [comment]
I don't believe this is a priority as both emails are tied to the account. This level of polish doesn't feel like a high priority to me. Raised [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1719849367801949?thread_ts=1719418903.881799&cid=C01SKUP7QR0) incase someone disagrees
