### ISSUE TITLE
[HOLD for payment 2024-09-26] [Search v2.1] Update `View payment history` redirect to "Expensify, Inc" merchant filter. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#44105]
When we have merchant filtering, we want to update the redirect of the `View payment history >` menu item on the subscription page to navigate to Search with a filtered list of results for `merchant: Expensify, Inc.`

This issue is on hold until we complete that part of the Search v2 rollout, which is currently in detailed planning.

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by trjExpensify** [comment]
Still holding on Search v2 introducing search querying for this. @luacmartins, do you have a more specific issue I can point to for this hold? 

Basically, we want to be able to filter the search page when they click this button to see all their billing receipts.

**Comment by luacmartins** [comment]
This would be the issue https://github.com/Expensify/App/issues/45026

**Comment by trjExpensify** [comment]
Thanks! Title updated.

**Comment by luacmartins** [comment]
Yes, draft PR [here](https://github.com/Expensify/App/pull/48026)

**Comment by luacmartins** [comment]
Just a heads up, the PR is still in draft because we discovered an issue with the parser grammar that was splitting `Expensify, Inc.` into `Expensify` and `Inc.`. We need to make some changes to the grammar, but that has bigger implications, so I'm discussing it with SWM.

**Comment by trjExpensify** [comment]
Nice, thanks for the update. Just realised you're not assigned here either, so I'm adding yah to the issue.

**Comment by luacmartins** [comment]
Still on hold for https://github.com/Expensify/App/pull/47789

**Comment by luacmartins** [comment]
@trjExpensify we're getting close to merging https://github.com/Expensify/App/pull/47789, but I noticed that purchases don't have an associated entry in the transactions table so they won't show up in the Search page. That also seems to be the case in OldDot. Are we supposed to change this behavior?

**Comment by trjExpensify** [comment]
> but I noticed that purchases don't have an associated entry in the transactions table so they won't show up in the Search page.

Hm, but when we bill someone we put the billing receipt in their Expensify account which creates an expense doesn't it?

**Comment by luacmartins** [comment]
Hmm maybe it was the way I created the expense locally then 🤔 I just ran a script to run billing for a user, maybe there are more steps to it

**Comment by trjExpensify** [comment]
Yeah maybe, I'm not sure.

**Comment by luacmartins** [comment]
PR in staging

**Comment by trjExpensify** [comment]
On prod, updated the title to reflect the payment date.

**Comment by trjExpensify** [comment]
Offer sent!

**Comment by trjExpensify** [comment]
Done, paid. Closing!
