### ISSUE TITLE
[HOLD for payment 2024-11-20] Fix List Spacing in Expensify Help

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#44107]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
cc @rushatgabhane and @Expensify/design 

Two possibly helpful comments - https://github.com/Expensify/App/pull/42272#discussion_r1617380413 and https://github.com/Expensify/App/pull/42280#discussion_r1617376063

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps
1. Go to a help document with a list inside a selector block, such as [this](https://help.expensify.com/articles/new-expensify/expensify-card/Add-Expensify-Card-to-Apple-or-Google-Pay)
2. Go to a help document with nested lists such as [this](https://help.expensify.com/articles/new-expensify/expensify-card/Dispute-Expensify-Card-transaction)

## Expected Result:
Spacing should be even and not crowded

## Actual Result:
Lists inside selector blocks do not have bottom padding applied (ex: no spacing above `Google Pay`):
<img width="1035" alt="Screenshot 2024-06-20 at 14 25 18" src="https://github.com/Expensify/App/assets/5487802/152e5712-50a2-428c-b0c9-20e6c9a0e210">

Nested lists still include padding so look odd next to normal list items (ex: spacing between 1 and 2 is much different than between 2 and 3)
<img width="1051" alt="Screenshot 2024-06-20 at 14 25 11" src="https://github.com/Expensify/App/assets/5487802/68905c8e-5e92-4510-8245-c68f8f919976">
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

see above

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by shawnborton** [comment]
Makes sense to me. Is this something we should ask @rushatgabhane to work on?

**Comment by dangrous** [comment]
I think so! If you're free, @rushatgabhane

**Comment by bfitzexpensify** [comment]
Bump @rushatgabhane - are you able to take this one on?

**Comment by rushatgabhane** [comment]
hey 👋 
happy to fix this

**Comment by rushatgabhane** [comment]
didn't get time yet

**Comment by rushatgabhane** [comment]
not overdue

**Comment by rushatgabhane** [comment]
oh god. gotta fix this

**Comment by dangrous** [comment]
i can grab this actually since it was my issue to begin with haha

**Comment by dangrous** [comment]
@rushatgabhane we figured out what happened with that "merge" on the other PR, we think you (presumably by mistake) based #46333 on that branch and GH saw that those commits were merged into main so there was nothing to do. Does that sound right to you? I know you reverted them, though, so we should reopen a new one for this.

**Comment by rushatgabhane** [comment]
ohh makes sense! im so sorry about that. it must have happened by mistake because i was working on multiple tasks 

good thing is nothing unintended is merged 😁

**Comment by rushatgabhane** [comment]
I'll create a new PR

**Comment by rushatgabhane** [comment]
next time I'll do git reset if something like this happens

**Comment by dangrous** [comment]
No worries! it turned out to be more confusing than it was dangerous haha - but yeah will be good to fix if we notice it in the future.

**Comment by dangrous** [comment]
Let us know when the new PR is up @rushatgabhane

**Comment by dangrous** [comment]
@rushatgabhane's been focusing on copilot but hopefully we can knock out the last requested update from design on that PR and get this merged soon!

**Comment by dangrous** [comment]
I think we have just a small change left on this and can merge shortly!

**Comment by dangrous** [comment]
bumping this @rushatgabhane so we can get this wrapped up!

**Comment by dangrous** [comment]
Reopening - we're almost there, just had some trouble building. @rushatgabhane let me know if the tip I left on the PR works, and we can close this out!

**Comment by dangrous** [comment]
Stop doing that melvin
