### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] Chat - Suggestion list appears above composer when selecting all text with @ via CMD+A

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44100]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Enter long paragraph until the composer is scrollable
4. Type @ at the end of the paragraph
5. Press CTRL + A

## Expected Result:
The suggestion list should appear above the @

## Actual Result:
The suggestion list appears above the composer. Sometimes it appears slightly above the composer (with space between the composer and the list)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/98899f88-397b-4870-8205-2db631aaf793

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@aldo-expensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by aldo-expensify** [comment]
I think this change came from this PR: https://github.com/Expensify/App/pull/42630

**Comment by aldo-expensify** [comment]
Maybe the we should close the autocomplete if the user selects text?

**Comment by aldo-expensify** [comment]
PR up: https://github.com/Expensify/App/pull/44113

**Comment by mountiny** [comment]
Per https://expensify.slack.com/archives/C035J5C9FAP/p1718916284226989 we can demote this one, seems minor and Aldo already fixed it but we probably do not need to CP. Thank you!

**Comment by aldo-expensify** [comment]
No payment needed (No C+ review or contributor hired)
