### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] VBA - VBA Link does not sign user in when redirected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44102]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** emilio.utest@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Access the New Expensify Beta app
2. Sign into a valid account
3. Go to Workspace > Workflow > Connect Bank account
4. Click on the Link

## Expected Result:
User expects to be redirected to the Safari browser and logged into the same account that was signed in on Desktop

## Actual Result:
User is taken to the sign in page in Safari, only after inputting their details that they are redirected to the VBA flow again
 On Prod this link does not redirect at all

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9b4732cc-118e-466c-ba52-05f2ad81e288

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01904662f1f13af1b5</li>
        <li>Upwork Job ID: 1803853930096753983</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102890303</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment]
@francoisl  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by francoisl** [comment]
I don't think it works on production either, the link currently just opens the website in a browser - it's not an auto-authenticating link.

https://github.com/Expensify/App/blob/42851094638fd86649c73dbb03da1d4c51a7fe04/src/pages/EnablePayments/AddBankAccount/SetupMethod.tsx#L31

Going to remove the blocker label and treat as a regular improvement.

**Comment by francoisl** [comment]
Ah, what I identified was the wrong place, the link is the one from `src/pages/ReimbursementAccount/BankAccountStep.tsx`, which we modified in https://github.com/Expensify/App/pull/43541. Not sure off the top of my head if we have a way to generate an authenticated link for NewDot (basically the equivalent of `Link.openOldDotLink()` but for `new.expensify`), going to open for proposals.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User is taken to the sign in page in Safari, only after inputting their details that they are redirected to the VBA flow again
On Prod this link does not redirect at all

### What is the root cause of that problem?
When we click on VBA link on desktop, we only open the external link without authen token so the user isn't signed in if we've already signed out.

https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/pages/ReimbursementAccount/BankAccountStep.tsx#L138
### What changes do you think we should make in order to solve the problem?
We should set the link as the transition on old dot link with authen token. To do that we can create a util to build the url with token like this

```
function buildURLWithAuthenToken(url: string, shortLivedAuthToken?: string) {
    console.log(shortLivedAuthToken);
    const authTokenParam = shortLivedAuthToken ? `shortLivedAuthToken=${shortLivedAuthToken}` : '';
    const emailParam = `email=${encodeURIComponent(currentUserEmail)}`;
    const exitTo = `exitTo=${url}`;
    const accountID = `accountID=${currentUserAccountID}`;
    const paramsArray = [accountID, emailParam, authTokenParam, exitTo];
    const params = paramsArray.filter(Boolean).join('&');

    return `${CONFIG.EXPENSIFY.NEW_EXPENSIFY_URL}transition?${params}`;
}

/**
 * @param shouldSkipCustomSafariLogic When true, we will use `Linking.openURL` even if the browser is Safari.
 */
function openExternalLinkWithToken(url: string, shouldSkipCustomSafariLogic = false) {
    asyncOpenURL(
        API.makeRequestWithSideEffects(SIDE_EFFECT_REQUEST_COMMANDS.OPEN_OLD_DOT_LINK, {}, {})
            .then((response) => (response ? buildURLWithAuthenToken(url, response.shortLivedAuthToken) : buildURLWithAuthenToken(url)))
            .catch(() => buildURLWithAuthenToken(url)),
        (url) => url, 
        shouldSkipCustomSafariLogic
    );
}
```

And then chang the `bankAccountRoute` here to the route of bank account step

```
const bankAccountRoute = `${ROUTES.BANK_ACCOUNT_WITH_STEP_TO_OPEN.getRoute('new', policyID, ROUTES.WORKSPACE_INITIAL.getRoute(policyID))}`;
```

https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/pages/ReimbursementAccount/BankAccountStep.tsx#L89
### What alternative solutions did you explore? (Optional)
NA


### Result

https://github.com/Expensify/App/assets/161821005/81332f44-497b-45fc-be23-7922d4ee10ec

**Comment by francoisl** [comment]
@Pujan92 can you review the proposal above please?

**Comment by Pujan92** [comment]
@nkdengineer's [proposal](https://github.com/Expensify/App/issues/44102#issuecomment-2182016698) looks good to me which suggested using `shortLivedAuthToken` to make the transition URL which sign-in the user on redirection.

🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment]
@Pujan92 this [PR](https://github.com/Expensify/App/pull/44517) is ready for review

**Comment by Pujan92** [comment]
There isn't any offending PR for this bug and more like a new feature.

### Regression Test Steps

1. Sign into a valid account in the desktop app
2. Go to Workspace > Workflow > Connect Bank account
3. In the connect bank account page click on the link please click here to complete this process in a browser.
4. Verify that: User expects to be redirected to the Safari browser and logged into the same account that was signed in on Desktop

**Comment by jliexpensify** [comment]
Payment Summary

- C: @nkdengineer $250
- C+_: @Pujan92 $250 (paid via New.Dot)

[Upwork job](https://www.upwork.com/jobs/~01904662f1f13af1b5)

**Comment by JmillsExpensify** [comment]
$250 approved for @Pujan92

**Comment by jliexpensify** [comment]
Was actually deployed 7 days ago so paying now.

**Comment by jliexpensify** [comment]
Paid and job closed!
