### ISSUE TITLE
 Taxes settings – “Hmm…” page appears shortly when edit Custom tax name in a new workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44116]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4649040
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new workspace
4. Navigate to the workspace editor
5. Navigate to "More Features"
6. Enable the taxes toggle
7. Open Taxes and tap on Settings
8. Tap on Custom tax name
9. Edit Custom tax name and wait a minute, don’t tap on Save

## Expected Result:
“Hmm…” page isn’t appears

## Actual Result:
“Hmm…” page appears shortly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/896626ca-a3b9-4cbb-babb-72d1221028ca

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@twisterdotcom FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by twisterdotcom** [comment]
I cannot recreate this: 
<img width="391" alt="image" src="https://github.com/Expensify/App/assets/9133401/97281df1-76bf-4743-83ec-a792fbe5cd79">

**Comment by lanitochka17** [comment]
Issue is still reproducible 

![Screenshot 2024-06-26 at 16 45 48](https://github.com/Expensify/App/assets/78819774/44476d11-4490-4071-a2fb-355b7cd9c6cb)

**Comment by twisterdotcom** [comment]
@lanitochka17 could you do a video recreating this on `MacOS: Chrome / Safari` for me on the next retest please? I'm still unable to reproduce and I must be missing a simple step.

I do think it's weird that the URL shows the workspace ID twice

**Comment by lanitochka17** [comment]
Issue is not reproducible on Web now 

https://github.com/Expensify/App/assets/78819774/d70d0d47-32a7-40e1-abd8-5fe314565b4a

**Comment by twisterdotcom** [comment]
Yeah, agreed I cannot recreate on web. Charging my Android device to test this then.

**Comment by twisterdotcom** [comment]
Also can't recreate on android: https://drive.google.com/file/d/1AqdKYLtQz9TX8aVQRgXouxW1sTM-ESrA/view?usp=sharing
