### ISSUE TITLE
[Payment Card / Subscription] iOS - "Add Payment Card" button is blinking when changing currency in app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44118]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** emilio.utest@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR**  https://github.com/Expensify/App/pull/43317
## Action Performed:
1. Access the New Expensify Beta app
2. Sign into a valid account
3. Go to staging.new.expensify.com/settings/subscription/add-payment-card (You may need a beta access account to locate this page)
4. Change the currency and observe the bottom green button

## Expected Result:
User expects the button to stay normal when changing currency

## Actual Result:
The button is flashing when the currency is changed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fc65333f-2d66-4401-85c5-455a721775fd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @narefyev91</details>

**Comment by mountiny** [comment]
@fabioh8010 this is still behind beta so not a blocker but should be handled

**Comment by mountiny** [comment]
Raised in [Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1718915960604899)

**Comment by trjExpensify** [comment]
>@fabioh8010 this is still behind beta so not a blocker but should be handled

FYI, there's no beta for this. It's only accessible if you know the URL though, so effectively hidden. :)

**Comment by narefyev91** [comment]
Hey! I'm Nicolay from Callstack - will work on this flow - please assign it for me. Thanks!

**Comment by trjExpensify** [comment]
Assigned!

**Comment by blimpich** [comment]
Picking this up as I'm managing the other issues that are being addressed by [this PR](https://github.com/Expensify/App/pull/43572), figured I should pick this up too.

**Comment by blimpich** [comment]
not overdue, PR was merged, waiting auto-close

**Comment by blimpich** [comment]
Closing as this reached production.
