### ISSUE TITLE
[Hold #368528] [FT] Add a ‘add a payment card’ as a next step in the 'manage my team expenses' onboarding flow when all tasks are complete 

### ISSUE THREAD

**Issue by CherylWalsh** [Expensify/App#44144]
**Problem:** Once all the tasks in the onboarding flow are complete, there is no obvious next step for the user to take. 

**Solution:** Create a "Add a payment card" as the next step once all tasks are complete. 

Context: 
Initial slack conversation https://expensify.slack.com/archives/C036QM0SLJK/p1717780619463079 
https://expensify.slack.com/archives/C036QM0SLJK/p1718277987047539 

Why is this on hold:

The add payment card and subscription project is quite done yet. Until that is completed, we cannot add that step here.

**Comment by CherylWalsh** [comment]
The copy is already designed

**Comment by trjExpensify** [comment]
I mentioned it [last week](https://expensify.slack.com/archives/C036QM0SLJK/p1720006149331729?thread_ts=1719848162.761009&cid=C036QM0SLJK), but I think we don't need this given we will be posting that message in the Conci/Expensify DM when the trial expires and they need to add a payment card. That's coming in this issue: https://github.com/Expensify/App/issues/43694  

So I think we can close this, personally.

**Comment by CherylWalsh** [comment]
Closing as advised by Tom. No point staying open if this is already in the planning. Closing.
