### ISSUE TITLE
[Awaiting Payment Sept 9th] [$250] Xero - "Can't connect to Xero." error message appears briefly before connecting

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44148]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4653112&group_by=cases:section_id&group_id=309134&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new expensifail account
3. Create a workspace
4. Enable Accounting
5. Navigate to Workspace settings - Accounting
6. Connect to Xero

## Expected Result:
I should be able to connect without any error messages

## Actual Result:
"Can't connect to Xero." error message appears briefly before connecting. Affects Gmail and expensifail accounts too.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/943516af-d8e7-4e96-90d1-e5d13ecbba40

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4b2bfe4b91b5ac9</li>
        <li>Upwork Job ID: 1805137190641025234</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103274174</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by alitoshmatov** [comment]
Waiting for proposals

**Comment by alitoshmatov** [comment]
Still waiting for proposals

**Comment by kadiealexander** [comment]
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1720501879247349).

**Comment by kbecciv** [comment]
Reproducible on build 9.0.5-7.

https://github.com/Expensify/App/assets/93399543/cc9b16b6-0d33-4832-8295-21dcd9f1b343

**Comment by kadiealexander** [comment]
Still not overdue.

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by kadiealexander** [comment]
I can still reproduce:

https://github.com/user-attachments/assets/fd0fd920-6ddf-4004-a70e-9bcf04d60277

@alitoshmatov do you think this can be fixed entirely on the front end?

**Comment by kadiealexander** [comment]
@alitoshmatov bump on my question above.

**Comment by kubabutkiewicz** [comment]
Hi! I am Jakub from Callstack - expert contributor group. I’d like to work on this issue.

@kadiealexander Can I get some credentials to connect to Xero?
And are there any other requirements to reproduce that issue?

**Comment by kadiealexander** [comment]
Hi Jakub! That's all that is needed to reproduce. Do you have access to our 1password environment?

**Comment by kubabutkiewicz** [comment]
@kadiealexander no, I dont have

**Comment by trjExpensify** [comment]
@kubabutkiewicz try to connect to Xero and then choose the Xero demo company option.

**Comment by trjExpensify** [comment]
Also, @nkdengineer @brunovjk as you guys worked on this PR very recently, I'm curious for your thoughts here as well: https://github.com/Expensify/App/pull/45041

**Comment by kubabutkiewicz** [comment]
Hi ! @trjExpensify thanks for that I was able to reproduce that. For me this seems to be a problem with syncing with backend. So the logic for showing red brick road indicator is that we finished syncing and policy connection `isSuccessful` is `false` so it look like that `!isSyncInProgress && policy?.connections?.[connectionName]?.lastSync?.isSuccessful === false`. And for `isSyncInProgress` we are checking that `POLICY_CONNECTION_SYNC_PROGRESS` onyx key have `stageInProgress` property different than `jobDone` value. The problem is happening when `stageInProgress` is `jobDone` but in policy looks like that 
```
{
    connections: {
        xero: {
            lastSync: {
                isSuccessful: false
            }
        }
    }
}
```
So `stageInProgress` is changing quicker to `jobDone` than changing `isSuccessful` to true. So there is somewhere reace condition I guess. Do we have any other indicator that syncing is still in progress? and do we know what is this key `isConnected` in `xero.lasySync` object ? As its always set to `false` 
<img width="371" alt="image" src="https://github.com/user-attachments/assets/3c5e1e8e-01ae-44ee-8c82-3bfe8168ceb1">

**Comment by trjExpensify** [comment]
@lakchote is out, but I think this might be related: https://github.com/Expensify/App/issues/46445#issuecomment-2257209333

CC: @yuwenmemon @NikkiWines (@aldo-expensify as well for vis).

**Comment by kubabutkiewicz** [comment]
Hey hey, during debugging I noticed different bug. When I was redirected to Xero page and clicked Allow access I got 500 error during redirect back to Expenify which looked like that 
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/7323c291-b687-4f7a-82a0-eb50a5b22590">

But on Connections page it looks like I am connected but the Onyx data looks like I shouldn't be connected
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/830edf0c-38e8-4a8d-81a7-f55bcb46e817">

**Comment by kubabutkiewicz** [comment]
The problem here is that backend sometimes sending pusher events in different order. At the first screenshot we see that first pusher event is for `policyConnectionSyncProgress` which says that its `jobDone` is sent before `policy` object which says `isSuccessful: true` but on the second screenshot that the order of those two messages is opposite, and this is making this issue. So in my opinion we should make that backend will sent those messages always in the same order. Because  `policyConnectionSyncProgress` is our indicator that syncing is still in progress or no.
<img width="797" alt="image" src="https://github.com/user-attachments/assets/288bf783-0dbe-484e-a218-d264295c1a49">
![order1](https://github.com/user-attachments/assets/88080eec-f614-47c4-880d-e61da2388b9b)

**Comment by trjExpensify** [comment]
Is the bug still reproducible now @NikkiWines's IS PR is on prod?

**Comment by kadiealexander** [comment]
Requested a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1722835596039949)

**Comment by kavimuru** [comment]
Bug is still reproducible.

https://github.com/user-attachments/assets/2b7cae6b-b854-4a7f-812d-77a91888ad57

**Comment by trjExpensify** [comment]
Interesting, @kubabutkiewicz did you get this TypeError like QA did? 

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/488840da-d497-416a-ac30-5ff28249fb04">

**Comment by kubabutkiewicz** [comment]
I will check it @trjExpensify but did you saw my message before ?https://github.com/Expensify/App/issues/44148#issuecomment-2260056390

**Comment by trjExpensify** [comment]
Right, but I don't recall you mentioning the TypeError for `target` and I'm wondering if that's an "evolution" of the bug, since @NikkiWines's IS changes.

**Comment by kubabutkiewicz** [comment]
@trjExpensify Right now for me connecting to Xero is not working at all 🤔 is it a known issue? 


https://github.com/user-attachments/assets/cc01a1f2-e25c-4e71-95b0-f4be1e7848bc

**Comment by trjExpensify** [comment]
Ah, @hungvu193 you've run into this 500 before right?

**Comment by hungvu193** [comment]
> Ah, @hungvu193 you've run into this 500 before right?

Yep, but I can't reproduce it now

**Comment by trjExpensify** [comment]
IIRC, you resolved it by disconnecting or something?

**Comment by hungvu193** [comment]
Yeah, I disconnected and reconnected again. Also this bug `Xero - "Can't connect to Xero." error message appears briefly before connecting ` also happened on SageIntacct. I faced it while testing https://github.com/Expensify/App/pull/45251
I mentioned it [here](https://github.com/Expensify/App/pull/45251#issuecomment-2285242494)

**Comment by hungvu193** [comment]
> You mean also happened with QBO, right?

Ah yes. My bad

**Comment by hungvu193** [comment]
I agree with @kubabutkiewicz 's [comment](https://github.com/Expensify/App/issues/44148#issuecomment-2260056390), we should fix this from BE. cc @arosiclair

**Comment by arosiclair** [comment]
So the issue is that with a brand new account and policy, we briefly display a "Can't connect to Xero/QBO" error message when making the initial connection?

The error message should only display when `lastSync.isSuccessful` is set to `false`. It looks like we actually only check if `lastSync.isSuccessful` is truthy [here](https://github.com/Expensify/App/blob/d8622863739197affbcf5d3400f6964761608309/src/libs/actions/connections/index.ts#L382-L384). So we should probably update that to do a strict `lastSync.isSuccessful === false` check before returning any error message. Otherwise an undefined `lastSync` would trigger an error message.

**Comment by trjExpensify** [comment]
>So the issue is that with a brand new account and policy, we briefly display a "Can't connect to Xero/QBO" error message when making the initial connection?

Good question, I don't think you strictly need a brand new account or policy to run into this.

**Comment by kadiealexander** [comment]
Not overdue. @arosiclair would you like to take this on?

**Comment by arosiclair** [comment]
Yeah I can manage this. It can still be fixed externally. @war-in can you take a look when you can? I'm pretty sure this is the root problem:

> The error message should only display when lastSync.isSuccessful is set to false. It looks like we actually only check if lastSync.isSuccessful is truthy [here](https://github.com/Expensify/App/blob/d8622863739197affbcf5d3400f6964761608309/src/libs/actions/connections/index.ts#L382-L384). So we should probably update that to do a strict lastSync.isSuccessful === false check before returning any error message. Otherwise an undefined lastSync would trigger an error message.

**Comment by war-in** [comment]
> Yeah I can manage this. It can still be fixed externally. @war-in can you take a look when you can? I'm pretty sure this is the root problem:
> 
> > The error message should only display when lastSync.isSuccessful is set to false. It looks like we actually only check if lastSync.isSuccessful is truthy [here](https://github.com/Expensify/App/blob/d8622863739197affbcf5d3400f6964761608309/src/libs/actions/connections/index.ts#L382-L384). So we should probably update that to do a strict lastSync.isSuccessful === false check before returning any error message. Otherwise an undefined lastSync would trigger an error message.

@arosiclair Yeah agree. Do you want me to fix it or just asking for confirmation?

**Comment by arosiclair** [comment]
> @arosiclair Yeah agree. Do you want me to fix it or just asking for confirmation?

To fix it please 🙏

**Comment by war-in** [comment]
@arosiclair Sure! I'll handle this on Monday due to the holidays in Poland 😅

**Comment by hungvu193** [comment]
@arosiclair Are we OK with the RBR still appearing while syncing? It will only disappear (update) when syncing is completed.

https://github.com/user-attachments/assets/cefb8da5-a448-4c58-a638-ba14b24bee4a

The RBR of `WorkspaceInitialPage` and `Indicator` is based on `policy`. However, we updated the progress based on `connectionSyncProgress`  and  `policy` didn't change so it won't trigger re-rerender.

**Comment by arosiclair** [comment]
> @arosiclair Are we OK with the RBR still appearing while syncing? It will only disappear (update) when syncing is completed.

No the RBR should only display at the same time as the error message. So if we clear the error message while the sync is in progress, the RBR should be cleared as well.

> The RBR of WorkspaceInitialPage and Indicator is based on policy. However, we updated the progress based on connectionSyncProgress and policy didn't change so it won't trigger re-rerender.
>
> I tried to pass isSyncInProgress to hasSyncError. However, I don't think that's a good idea since we will need to loop over the policies to get the connectionSyncProgress of each policy.

We should connect each of the components to all of the policies and connection sync progress with `useOnyx`/`withOnyx`. Looping over policies and the sync progress object shouldn't be a problem.

**Comment by trjExpensify** [comment]
>No the RBR should only display at the same time as the error message. So if we clear the error message while the sync is in progress, the RBR should be cleared as well.

Totally agree, looks weird. 👍

**Comment by hungvu193** [comment]
> We should connect each of the components to all of the policies and connection sync progress with `useOnyx`/`withOnyx`. Looping over policies and the sync progress object shouldn't be a problem.

How can I get a Onyx value inside a loop? I've never done it before :(

**Comment by hungvu193** [comment]
I figured it our with @war-in 's help 🌟  I'll update the PR shortly.

**Comment by garrettmknight** [comment]
@hungvu193 when do you think we'll be ready for a re-review?

**Comment by hungvu193** [comment]
> @hungvu193 when do you think we'll be ready for a re-review?

It's ready already. Waiting for @getusha to review ỉ

**Comment by arosiclair** [comment]
Waiting for a C+ review on https://github.com/Expensify/App/pull/47483

**Comment by hungvu193** [comment]
This will be ready for Payment on 9th Sept

**Comment by trjExpensify** [comment]
Edited the labels for you.

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @hungvu193 via manual requests
- [ ] Reviewer: $250 @war-in (please apply in Upwork)

Upwork job is [here](https://www.upwork.com/jobs/~021833299867919890279).

**Comment by hungvu193** [comment]
requested on ND

**Comment by getusha** [comment]
@arosiclair @kadiealexander could you assign me as well? thanks!

**Comment by arosiclair** [comment]
@kadiealexander @getusha is also owed a payment for his C+ review

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193

**Comment by kadiealexander** [comment]
Added @getusha to the payment summary, please request payment via NewDot :)

**Comment by war-in** [comment]
>  Reviewer: $250 @war-in (please apply in Upwork)

@kadiealexander I'm an agency developer (SWM) so I don't require payment here :)

**Comment by kadiealexander** [comment]
Thanks @war-in! In that case, everyone is paid.
