### ISSUE TITLE
[$250] [HOLD for payment] [Details Revamp] Allow Editing Report Title from Details Page

### ISSUE THREAD

**Issue by grgia** [Expensify/App#44149]
## Problem

![image](https://github.com/Expensify/App/assets/38015950/28634350-8a58-4d29-857f-a591f4c66c24)

We currently display the report title as shown above. This is now inconsistent with our new details revamp project.

## Solution

![image](https://github.com/Expensify/App/assets/1127863/c9328c54-059f-46d7-8146-30aebdbaa065)

Make the report title editor available from the details page for those with correct permissions. Remove it from the report body as shown in the previous screenshot.

> So for example, members, approvers and admins can change the report title. Anyone added to the room, not part of the approval workfllow, should not be able to change the report title.

We will use our typical push to page pattern for this change.

## Slack thread

https://expensify.slack.com/archives/C036QM0SLJK/p1718830874704809?thread_ts=1718719187.256049&cid=C036QM0SLJK

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc27f37e79795306</li>
        <li>Upwork Job ID: 1813753312852314259</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by cdOut** [comment]
Hi, I’m Tymoteusz from Software Mansion, the expert agency, and I’ll be working on this issue.

**Comment by trjExpensify** [comment]
Assigning @ishpaul777 for C+.

**Comment by kadiealexander** [comment]
@ishpaul777 please propose the regression test steps [here](https://github.com/Expensify/App/issues/44149#issuecomment-2220211710).

**Comment by kadiealexander** [comment]
@ishpaul777 please accept the upwork offer.

**Comment by kadiealexander** [comment]
No worries!
