### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250]  Accounting - Workspace admins aren't lised as a "Preferred exporter"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44150]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4653117&group_by=cases:section_id&group_id=309134&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Create a workspace
4. Enable Accounting
5. Connect to Xero
6. Add an expensifail member as an admin
7. Navigate to Workspace settings - Accounting - Export - Preferred exporter
 repro only if i add admin after i connect to Xero. Not repro when i manually sync it

## Expected Result:
Workspace admins should be listed

## Actual Result:
Workspace admins aren't lised as a "Preferred exporter"
Reproducible  only if  add admin after  connected to Xero. Not repro when manually sync it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2431dcda-517e-472d-8674-448aa4934b43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b398eb305ddcbb3e</li>
        <li>Upwork Job ID: 1805402957868224386</li>
        <li>Last Price Increase: 2024-07-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by greg-schroeder** [comment]
Sending through for proposals

**Comment by greg-schroeder** [comment]
Bump @alitoshmatov for proposal review!

**Comment by greg-schroeder** [comment]
Go away Melvin

**Comment by allroundexperts** [comment]
Taking over. I'll review the proposals today.

**Comment by allroundexperts** [comment]
@shubham1206agra Can you guide us on what other integrations we should look after? The proposed solution works well for Xero.

**Comment by allroundexperts** [comment]
Thanks for your proposal @daledah. Your RCA is correct and the solution proposed works as well. When raising a PR, please make sure that it works for the following integrations as well in addition to Xero:
1. NetSuite
2. QuickBooks

Let's go with @daledah's [proposal](https://github.com/Expensify/App/issues/44150#issuecomment-2187822757).

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment]
@jasperhuangg FYI, @daledah's proposal fixed this for offline case only. Can you please check if we're sending the email from the backend once the request succeeds?

**Comment by greg-schroeder** [comment]
bump @jasperhuangg on confirming the contributor assignment!

**Comment by jasperhuangg** [comment]
Agree with @daledah's proposal, sorry for the delay, was OOO!

**Comment by greg-schroeder** [comment]
No sweat, thanks!

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @daledah - $250 - Offer sent via Upwork
C+: @allroundexperts - $250 - You can make a manual request via ND

**Comment by greg-schroeder** [comment]
@daledah can you apply to the upwork job or link your upwork profile here so I can send you an offer/pay you?

https://www.upwork.com/jobs/~01b398eb305ddcbb3e

**Comment by greg-schroeder** [comment]
@daledah it says your Upwork profile is no longer available. so you're going to create a valid upwork account and apply to this job in order for me to pay you.

**Comment by greg-schroeder** [comment]
bump @daledah

**Comment by greg-schroeder** [comment]
Sent @daledah

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/44150#issuecomment-2247811667).
