### ISSUE TITLE
[$250] Distance - Default category is selected after submitting when it is unselected on confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4652158
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has default category configured in Distance rates settings
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Submit expense >Distance
4. Enter addresses > Next
5. Click Category and unselect the default category
6. Submit the expense
7. Go to transaction thread

## Expected Result:
The default category will not be selected in the transaction thread after submitting the expense because it is unselected on confirmation page

## Actual Result:
The default category is selected in the transaction thread after submitting the expense when it is unselected on confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f2d39c17-d903-4e53-b294-650496b44ecc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d7ef3a11d9cfad2</li>
        <li>Upwork Job ID: 1805946979018031242</li>
        <li>Last Price Increase: 2024-08-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jp928** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Open a distance expense without any category has default category `Car`

### What is the root cause of that problem?

Backend seems like returns the `transaction_` with a default category if there is no category data while creating a distance expense. See attached:

![Screenshot 2024-06-28 at 10 15 01 AM](https://github.com/Expensify/App/assets/659612/3383d1c9-d279-4ab3-925b-80d62d200d94)


### What changes do you think we should make in order to solve the problem?
Backend returns empty string or null if the category is empty string or null when create a distance expense.

### What alternative solutions did you explore? (Optional)
NA

**Comment by abdulrahuman5196** [comment]
Hi, Will check on this today.

**Comment by muttmuure** [comment]
@abdulrahuman5196 please review this proposal when you get chance: https://github.com/Expensify/App/issues/44157#issuecomment-2195868950

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by muttmuure** [comment]
Not overdue

**Comment by trjExpensify** [comment]
Matt, if we need an internal volunteer we should put it in Hot Picks for visibility. 👍

**Comment by tgolen** [comment]
I'll look into this.

**Comment by tgolen** [comment]
This is by design and functioning as expected. If a distance request is submitted with an empty category, the server will add the default category of "Car" to it.

You can change the default category by going to:
> Workspaces > Workspace > Distance Rates > Settings
