### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Distance - Start and Stop labels do not change when dragging one over another

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44153]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4652117
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Submit expense > Distance.
3. Drag empty Stop row over empty Start row.
4. Note that the Stop label does not change to Start and Start label does not change to stop.
5. Tap on the Stop row.
6. Select a waypoint.
7. Now Stop and Start rows overlap with one another.

## Expected Result:
In Step 4, Stop label will change to Start and Start label will change to stop.

## Actual Result:
In Step 4, Stop label does not change to Start and Start label does not change to stop.
In Step 7, when selecting a waypoint, Stop and Start rows overlap with one another.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/b9a0db36-9560-4b52-8fca-209262ff8b25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b23211c128469d40</li>
        <li>Upwork Job ID: 1805046118243790605</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 102892776</li>
<li>Krishna2323 | Contributor | 102911936</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by jliexpensify** [comment]
I can reproduce, but also have asked the team [here](https://expensify.slack.com/archives/C036QM0SLJK/p1719191461009709) if we want to lock down those points, so they can't be dragged.

**Comment by jliexpensify** [comment]
Ok we are good to look at proposals @abdulrahuman5196 , thanks!

**Comment by jliexpensify** [comment]
Bump @abdulrahuman5196 for a review please

**Comment by jliexpensify** [comment]
All yours @hoangzinh

**Comment by jliexpensify** [comment]
Payment Summary

- C: @Krishna2323 
- C+: @hoangzinh $250 - waiting on checklist!

[Upwork job](https://www.upwork.com/jobs/~01b23211c128469d40)

**Comment by jliexpensify** [comment]
Paid and job closed.
