### ISSUE TITLE
IOU - A still image is briefly displayed before receiving the camera feed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44151]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exp around https://expensify.testrail.io/index.php?/tests/view/4650940&group_by=cases:section_id&group_id=229063&group_order=asc
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Navigate to an existing manual IOU without a receipt
3. Tap on the "Add receipt" button

## Expected Result:
The camera feed should be displayed.

## Actual Result:
A still image is briefly displayed before receiving the camera feed.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/be4a2b95-5487-4971-a7f1-d6656e9dd474

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by dylanexpensify** [comment]
Will review today!

**Comment by dylanexpensify** [comment]
Cannot reproduce
