### ISSUE TITLE
User is able to submit expense without category even when `Members must categorize all expenses` is enabled

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44169]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718918167781269

## Action Performed:
Precondition:
"Members must categorize all expenses" in Categories is enabled.

1. Go to [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Go to workspace chat.
3. Submit an expense without category.

## Expected Result:
This action should not be allowed and we should display error message like we do for missing merchant

## Actual Result:
User is able to submit expense without category even when `Members must categorize all expenses` is enabled
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/158d1310-bb57-464c-8a9c-3dd82733f17d

https://github.com/Expensify/App/assets/38435837/e24e2bbc-2cf0-4b9a-92d3-dcb5a5cf8057

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
I don't think this is a bug. Categories can be made required for coding, but we don't prevent submission of the expense without one, we just flag a violation. In a lot of cases, we auto-categorize expenses based on the merchant entered, card transaction's MCC and other things - so forcing the submitter to enter one manually is contrary to those nice automation pieces. This is unlike merchant, date and amount which are the minimum amount of coding required to actually create an expense.

Commented [here](https://expensify.slack.com/archives/C049HHMV9SM/p1718986236937149?thread_ts=1718918167.781269&cid=C049HHMV9SM), but I'm going to close.
