### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Header is not displayed after reloading page on waypoint screen

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44165]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ZhenjaHorbach 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718901200855539

## Action Performed:

1. Open App
2. Tap the FAB -> Submit expense -> Distance
3. Open any waypoint
4. Reload the page
5. Press go back

## Expected Result:
Header shouldn't disappear
## Actual Result:
after reloading and pressing go back button, the header is not displayed
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/4a24910b-8219-4033-8c78-bce8c466dc2a

https://github.com/Expensify/App/assets/38435837/fb1b4a87-0e77-4c26-8253-89f636060083

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7345d06d12d9654</li>
        <li>Upwork Job ID: 1805372602824719078</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The page header isn't displayed when reloading waypoint screen and go back.

### What is the root cause of that problem?
In waypoint screen, going back will call go back with a fallback to the distance request screen.
https://github.com/Expensify/App/blob/7512346c2fd5c03882e3f9951b03530d8cbf7972/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L168-L170

The `MONEY_REQUEST_STEP_DISTANCE` route will navigate user to the IOURequestStepDistance. The header doesn't show because `isCreatingNewRequest` is true.
https://github.com/Expensify/App/blob/7512346c2fd5c03882e3f9951b03530d8cbf7972/src/pages/iou/request/step/IOURequestStepDistance.tsx#L434

But this isn't the problem. The problem is, the user should be navigated to the IOURequestStartPage where there will be 3 tab, Manual, Scan, and Distance and the route for the Distance tab is `MONEY_REQUEST_CREATE_TAB_DISTANCE`, so the route being used here for create case is wrong.

### What changes do you think we should make in order to solve the problem?

We can use the same back login when selecting a waypoint (selectWaypoint) by using the backTo param and fallback to the distance tab.
https://github.com/Expensify/App/blob/7512346c2fd5c03882e3f9951b03530d8cbf7972/src/pages/iou/request/step/IOURequestStepWaypoint.tsx#L150-L154

We can create a new function for go back so it's reusable.

**Comment by strepanier03** [comment]
Confirmed reproducible using browserstack. 

<img width="297" alt="image" src="https://github.com/Expensify/App/assets/10925636/940baa72-8b59-4155-8be6-8163b03a7811">

**Comment by mananjadhav** [comment]
@bernhardoj Your proposal looks promising can you explain what do we mean by passing two backTo params? `encode(waypoint?backTo=distance?backTo=confirmation)`

**Comment by bernhardoj** [comment]
So, when we open the distance page from the confirmation page, the distance page route will have a backTo param
`/create/submit/distance/1/1579314117131792?backTo={confirmationPage}`

Then, when we open the waypoint page, the backTo is currently `/create/submit/distance/1/1579314117131792`.
`/create/submit/waypoint/1/1579314117131792/0?backTo=%2Fcreate%2Fsubmit%2Fdistance%2F1%2F1579314117131792`

The backTo of `backTo={confirmationPage}` is lost. So, when we go back from the waypoint page, we arrive at the distance page without the backTo param.
`/create/submit/distance/1/1579314117131792`

So, we need to keep the backTo by using getActiveRoute.
```
/create/submit/waypoint/1/1579314117131792/0?backTo=${encode(/create/submit/distance/1/1579314117131792?backTo={confirmationPage})}`
```

**Comment by strepanier03** [comment]
Thank you @ZhenjaHorbach - I appreciate the understanding. In most cases we should allow the label to assign so that C+ are given as equal access to jobs as possible. In special cases we will do a manual assignment but that's generally discussed in Slack beforehand and the assignment happens before any automated assignment kicks in.

**Comment by mananjadhav** [comment]
Thanks for clarification @strepanier03.

Thanks for posting the explanation @bernhardoj. Your proposal looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by bernhardoj** [comment]
PR is ready

cc: @mananjadhav

**Comment by strepanier03** [comment]
Payment hold expires tomorrow, will revisit then.

**Comment by strepanier03** [comment]
@mananjadhav - Feel free to do the checklist tomorrow and I'll post the full payment summary. @ZhenjaHorbach - I sent you an offer via Upwork as well.

**Comment by CH-RAFAY** [comment]
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> **Version Number:** 9.0.0-0 **Reproducible in staging?:** y **Reproducible in production?:** y **If this was caught during regression testing, add the test name, ID and link from TestRail:** **Email or phone of affected tester (no customers):** **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Expensify/Expensify Issue URL:** **Issue reported by:** @ZhenjaHorbach **Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718901200855539
> 
> ## Action Performed:
> 1. Open App
> 2. Tap the FAB -> Submit expense -> Distance
> 3. Open any waypoint
> 4. Reload the page
> 5. Press go back
> 
> ## Expected Result:
> Header shouldn't disappear
> 
> ## Actual Result:
> after reloading and pressing go back button, the header is not displayed
> 
> ## Workaround:
> unknown
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [ ]  Android: Native
> * [ ]  Android: mWeb Chrome
> * [ ]  iOS: Native
> * [x]  iOS: mWeb Safari
> * [ ]  MacOS: Chrome / Safari
> * [ ]  MacOS: Desktop
> 
> ## Screenshots/Videos
>  2024-06-20.18.31.35.mov 
>  GBSA4059.1.MP4 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
> 
> Upwork Automation - Do Not Edit
> Issue Owner



Dear Expensify Team,

I am Abdul Rafay Chaudhry, an expert in web and mobile development with extensive experience in React Native. I have successfully executed complex projects requiring both frontend and backend development, ensuring high reliability and security standards.

Possible Issues

1. Compatibility Issues
2. Performance Optimization
3. Security Vulnerabilities
4. State Management Challenges
5. UI/UX Consistency
6. Third-Party Library Integration
7. Testing and Quality Assurance


Example Code Implementation

```jsx
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

const ExpenseItem = ({ expense }) => {
    return (
        <View style={styles.expenseItem}>
            <Text style={styles.title}>{expense.title}</Text>
            <Text style={styles.amount}>{expense.amount}</Text>
            <Text style={styles.date}>{expense.date}</Text>
        </View>
    );
};

const styles = StyleSheet.create({
    expenseItem: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc'
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold'
    },
    amount: {
        fontSize: 16,
        color: 'green'
    },
    date: {
        fontSize: 14,
        color: '#888'
    }
});

export default ExpenseItem;

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by strepanier03** [comment]
@ZhenjaHorbach - Okay, thank you for the heads up. Melvin has been a bit off their game lately 🤔 it feels like.

I'll cancel that in Upwork right away.

**Comment by strepanier03** [comment]
### Payment Summary

- $250 - @mananjadhav via New Expensify request
- $250 - @bernhardoj via New Expensify request

@JmillsExpensify - Requests incoming.

**Comment by mananjadhav** [comment]
Requested on ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
