### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] Able to save empty display first name

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44167]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718910421583419

## Action Performed:
Precondition: Have an existing Profile display name

1. Go to settings -> Profile
2. Click on display name
3. Remove the text in first and last name
4. Hit save

## Expected Result:
We should not be able to save empty first name (This will be similar to the onboarding flow, we allow the user to keep last name empty but they have to fill the first name)
## Actual Result:
Able to save empty display first name
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/62b2db91-9103-44c0-a0b9-257d994e2082

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e9e958a4df5e3121</li>
        <li>Upwork Job ID: 1805257830229126291</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102859067</li>
<li>eucool | Contributor | 102859068</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by isabelastisser** [comment]
@allgandalf can you please review the proposals above? Thanks!

**Comment by bondydaa** [comment]
assigning @eucool b/c the proposal is more complete to me. 

I agree we should probably create new error messages in the `personalDetails.error` object that are more tailored to this setting page, something like `First name cannot be empty` instead of the `Please input your first name to continue.` from `requiredFirstName`.

**Comment by isabelastisser** [comment]
Thanks for the heads up, @allgandalf!

@bondydaa, can you please review the regression test above? Thanks!

**Comment by isabelastisser** [comment]
The payments were processed in Upwork!

**Comment by bondydaa** [comment]
regression steps look good

**Comment by isabelastisser** [comment]
Hi @eucool, it was paid on July 16:

<img width="554" alt="image" src="https://github.com/user-attachments/assets/73c7a2c5-a3a3-48e6-a7fc-ef928e5bae7f">

**Comment by isabelastisser** [comment]
All set!
