### ISSUE TITLE
Improve manual CP workflow

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#44177]
### Problem

When we cherry-pick PRs, we have `OSBotify` attempt to automatically cherry-pick the code (and resolve certain conflicts automatically). When he can successfully do that, it works great because he can push that code straight to staging without the need for a pull request.

However, in cases where we need to manually resolve conflicts, `OSBotify` will commit the conflict markers (weird, right?) then open a PR, and assign it to the person who triggered the CP to resolve the conflicts and get the PR reviewed and merged.

However, PRs created by `OSBotify`, `imgbot`, and other bots have tests and lint skipped, so we lose that bit of security on manual CPs.

### Solution
Two parts:

1. First, update the cherry pick workflow such that, if there are conflicts, the PR is automatically opened not by `OSBotify` but by the Expensify employee who triggered the CP. That way, tests and lint run as normal.
1. if possible, find a way to open the PR without committing conflict markers, such that the PR appears with the conflicts as a normal PR would if it was created normally and then conflicts occurred after-the-fact.

**Comment by roryabraham** [comment]
cc @francoisl since we talked about this yesterday

**Comment by johnmlee101** [comment]
> the PR is automatically opened not by OSBotify but by the Expensify employee who triggered the CP. That way, tests and lint run as normal.

I dealt with this on GH Actions, basically if you create a PR in a GH Action, it will _not_ run tests.
