### ISSUE TITLE
[$150] Web - Workspace - Invite new members" field is not focused

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44182]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to an account
2. Go to workspace(Or create one) > Members
3. Click on the "Invite member" button at the top. Notice the field is focused
4. On the Invite members page click on the Question mark button to go to the "Get assistance"
5. Click back to return to the Invite Members page

## Expected Result:
Invite members page field is focused

## Actual Result:
The invite members page field is not focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f1c864c8-e283-4738-ba75-83cf8967f78a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bda364df69d71d2a</li>
        <li>Upwork Job ID: 1805292410395622118</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>tsa321 | Contributor | 102885241</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Web - Workspace - Invite new members" field is not focused

### What is the root cause of that problem?

Because of the newly added focusTrap and the Workspace_Invite screen isnot included in, SCREENS_WITH_AUTOFOCUS

https://github.com/Expensify/App/blob/b021195b864211efbaaefe188226b2830b91b7d8/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L51-L55

### What changes do you think we should make in order to solve the problem?

We should add the `Workspace_Invite` screen in SCREENS_WITH_AUTOFOCUS

**Comment by adelekennedy** [comment]
I can reproduce, and while this is a small bug I think it's worth it to fix

**Comment by adelekennedy** [comment]
@rushatgabhane already three proposals above to review

**Comment by tsa321** [comment]
@rushatgabhane PR is ready

**Comment by adelekennedy** [comment]
It looks like this was deployed to [prod](https://github.com/Expensify/App/pull/44511) on the 15th and payment is due!

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $150 @tsa321 (Upwork)
- [ ] Contributor+: $150 @rushatgabhane (NewDot)

**Comment by adelekennedy** [comment]
Do we need a regression test here @rushatgabhane?

**Comment by rushatgabhane** [comment]
@adelekennedy this was caught by QA so I don't think we do. And it's a very minor edge case bug.

**Comment by JmillsExpensify** [comment]
$150 approved for @rushatgabhane
