### ISSUE TITLE
[HOLD for payment 2024-07-10] [HOLD for payment 2024-07-02] [$250] Scan - "Unhold" option appears in report details page of scanning expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44195]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two scan expenses
4. Go to transaction thread of either one of the scan expenses
5. Click on the chat header

## Expected Result:
"Unhold" option should not appear in report details page of scanning expense

## Actual Result:
"Unhold" option appears in report details page of scanning expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4bb8127d-3330-4ec7-8589-031d75352103

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183882a32ebd33716</li>
        <li>Upwork Job ID: 1805164343050042330</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment]
@Beamanator  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
@Krishna2323 Are you available to raise the PR for this quickly?

**Comment by Beamanator** [comment]
Hey @mountiny i'm planning to test this out & figure out the PR that caused the regression (probably https://github.com/Expensify/App/pull/43251)

**Comment by mountiny** [comment]
@Beamanator thanks!

**Comment by Beamanator** [comment]
@Krishna2323 I don't really like adding `(canHoldUnholdReportAction.canHoldRequest || canHoldUnholdReportAction.canUnholdRequest)` to the if condition before `result.push(PromotedActions.hold`, mainly because I feel like `.canHoldRequest` and `.canUnholdRequest` should always relate to `shouldShowHoldAction` - a.k.a. why not add `(canHoldUnholdReportAction.canHoldRequest || canHoldUnholdReportAction.canUnholdRequest)` into the calculation of `shouldShowHoldAction`?

**Comment by Beamanator** [comment]
I ping'd @grgia and @cdOut in internal slack thread ([here](https://expensify.slack.com/archives/C036QM0SLJK/p1719221430701059)) so will wait for their thoughts

**Comment by Beamanator** [comment]
Ok @cdOut will make the PR to fix, @Krishna2323 we should still pay you something for finding the correct root cause & providing the best solution (assuming we end up going with your solution in the end, which i think we will)

**Comment by Beamanator** [comment]
Working well in staging!! @sonialiap i believe we're ready for payment!

@Krishna2323 provided the correct regression which helped @cdOut complete the PR (since it was a regression)

Also @hoangzinh was C+ for the PR 👍

**Comment by sonialiap** [comment]
Payment summary
@hoangzinh $250 - offer sent in Upwork

**Comment by sonialiap** [comment]
@Krishna2323 sorry I missed that! Offer sent

**Comment by sonialiap** [comment]
@hoangzinh please complete the [checklist](https://github.com/Expensify/App/issues/44195#issuecomment-2207047188)
