### ISSUE TITLE
[HOLD for payment 2024-07-02] [$250] Room - Room chat LHN preview displays "removed 0 user" after editing room description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44194]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any room chat
3. Click on the chat header
4. Click Room description
5. Edit room description and save it
6. Wait for the room description system message to show up in the chat
7. Look at the room chat LHN preview

## Expected Result:
Room chat LHN preview will display room description edit system message

## Actual Result:
Room chat LHN preview displays "removed 0 user" after editing room description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/66d6fd0f-562a-423f-8a0f-f102f063df0c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7a4ab1b5544c43f</li>
        <li>Upwork Job ID: 1805307133943402370</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102859753</li>
<li>ishpaul777 | Contributor | 102859756</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment]
@cristipaval  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment]
@ishpaul777 What PR cause this regression?

**Comment by cristipaval** [comment]
@nkdengineer, do you have time to look at this one?

**Comment by miljakljajic** [comment]
both contributors paid. Thank you!
