### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250]  Review duplicate - "Resolved duplicate" system message cannot be copied and thread grays out

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44197]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1.0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two distance expenses with the same waypoints.
4. Go to transaction thread of either one of the expenses.
5. Click Review duplicate.
6. Click Keep all.
7. Right click on the resolved duplicate system message > Copy to clipboard.
8. Paste the content.
9. Right click on the resolved duplicate system message > Reply in thread.

## Expected Result:
In Step 8, the resolved duplicate system message will be copied.
In Step 9, the thread view for resolved duplicate system message will not gray out.
## Actual Result:
In Step 8, the resolved duplicate system message is not copied.
In Step 9, the thread view for resolved duplicate system message grays out.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/78d143b9-99ad-44f6-b0b7-a0c6c08998b6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013549acc3e506155c</li>
        <li>Upwork Job ID: 1805250468730678419</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102911451</li>
<li>dominictb | Contributor | 102911453</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by m-natarajan** [comment]
@Gonals FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by Gonals** [comment]
I don't think we need to block deploy on this. Setting as external

**Comment by Christinadobrzyn** [comment]
I can reproduce this with the steps in the OP - waiting on proposals.

**Comment by Christinadobrzyn** [comment]
hi @Gonals can you take peek at the proposal review when you have a moment? https://github.com/Expensify/App/issues/44197#issuecomment-2189251745

**Comment by Christinadobrzyn** [comment]
Awesome! thanks @dominictb we'll keep an eye out for the PR. Thanks!

**Comment by Christinadobrzyn** [comment]
Update for Melvin - PR is in the works!

**Comment by Christinadobrzyn** [comment]
Sorry for all the labels... 

@Gonals - can you provide some insights into what we should do next based on @dominictb findings here - https://github.com/Expensify/App/issues/44197#issuecomment-2217020472

would you be able to take a look into this or should I get another volunteer?

**Comment by Gonals** [comment]
I'll be ble to get to this in a couple of days, but I'm pretty swamped right now 😅

**Comment by Christinadobrzyn** [comment]
Prepping for payment... 

Payouts due:

- [ ] Contributor: $250 @dukenv0307 (offer in Upwork - https://www.upwork.com/nx/wm/offer/102911451)
- [ ] Contributor+: $250 @dominictb (offer in Upwork - https://www.upwork.com/nx/wm/offer/102911453)

@dukenv0307 do we need a regression test for this?

**Comment by Christinadobrzyn** [comment]
Update for Melvin- This is in a holding pattern until the payment date

**Comment by Christinadobrzyn** [comment]
PR in production - paying this out based on this [payment summary](https://github.com/Expensify/App/issues/44197#issuecomment-2233829733).
