### ISSUE TITLE
[$250] Chat - New green line remains above last message when user switch chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44204]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 issue found when validating #42742 
**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** 

## Action Performed:
1. User A have open chat with User B
2. User C send a message to User A
3. User A opens the chat with User C
4. Verify there is a New green line above the received message
5. User A navigates to chat with User B
6. User A navigates back to the chat with User C

## Expected Result:
New green line should not be present since user have read the message and switch the chat

## Actual Result:
New green line remains above last message when user switch chat
New green line disappears only when refresh page
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/711b6206-336b-4ef0-a40c-1519250dad33

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2a88ee67b261c60</li>
        <li>Upwork Job ID: 1811345021260741348</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103076271</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment]
@Julesssss FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by Julesssss** [comment]
I was OOO at this time on Friday. 

We have a brand new checklist with 20 blockers so I won't yet revert, but I'll need to see some progress on the fix in the meantime. [This PR](https://github.com/Expensify/App/pull/42742#issuecomment-2185925581) was the likely cause.

**Comment by Julesssss** [comment]
The new message line remains until the user comments or signs out.

I'm going to revert the PR now as this is serious enough to block deploy, and seems like the assigned contributors won't be online until tomorrow.

**Comment by Julesssss** [comment]
Fixed and CPd, removing blocker label

**Comment by garrettmknight** [comment]
Moving this to daily to handle it tomo - @Julesssss who's getting paid here? This issue is kind of a mess.

**Comment by Julesssss** [comment]
My bad, this shouldn't have had the ready for payment title...

I resolved this issue by reverting the original PR. So this issue should be closed, and further changes should be discussed [here](https://github.com/Expensify/App/issues/41935).

**Comment by Julesssss** [comment]
Oh I see, sorry. One sec.

**Comment by Julesssss** [comment]
So @garrettmknight, we just need a single C+ review payment for @ishpaul777. The 7 day hold has already passed. Thanks!

**Comment by garrettmknight** [comment]
@ishpaul777 offer is out to you. Let me know when you've accepted and I'll pay.

**Comment by garrettmknight** [comment]
Still waiting on offer acceptance

**Comment by garrettmknight** [comment]
All paid up, closing.
