### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Android - Workspaces - "Workspaces" title is shown in two lines

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Device font size must be large
- Or use a narrow screen device like Samsung Galaxy Z Fold (front display) and use minimum font size in this case
1. Launch New Expensify app
2. Go to Account settings
3. Go to Workspaces

## Expected Result:
"Workspaces" title will not be shown in two lines

## Actual Result:
"Workspaces" title is shown in two lines

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Samsung_Notes](https://github.com/Expensify/App/assets/78819774/567b0754-32f2-438b-af20-ca9f98161c54)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db4b9a25dfd3bca7</li>
        <li>Upwork Job ID: 1804562341394542349</li>
        <li>Last Price Increase: 2024-06-22</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102838388</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment]
@tgolen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by tgolen** [comment]
Thanks for the proposal @Krishna2323  

It looks good to me! Can you please do a PR?

**Comment by mountiny** [comment]
I agree this does not have to be a blocker given the preconditions of narrow screen and increased base font size

**Comment by MitchExpensify** [comment]
*Payment summary*:

- $250 @parasharrajat requires payment through NewDot Manual Requests
- $250 @Krishna2323 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102838388) (Contributor)

**Comment by MitchExpensify** [comment]
Paid and contract ended @Krishna2323

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
