### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Track expense - LHN of self-DM still shows actionable whisper after submitted to someone

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990401
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: on self-DM click '+' > Track Expense
1. On the actionable whisper options click on 'Submit it to someone'
2. Choose another user and Submit

## Expected Result:
The transaction is moved to that new chat.
Tracked expense is not displayed in the self DM anymore.
LHN of self-DM no longer shows "What would you like to do with this expense?"

## Actual Result:
The transaction is moved to that new chat.
Tracked expense is not displayed in the self DM anymore.
LHN of self-DM still shows "What would you like to do with this expense?"

## Workaround:
Unnkown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dcb2cd9a-56bd-40dc-8d66-141eee0f955a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01112f075346c9b0f8</li>
        <li>Upwork Job ID: 1805265765671190738</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 102920804</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
@allroundexperts are you able to get to the review of the proposal here?

**Comment by allroundexperts** [comment]
On it today.

**Comment by allroundexperts** [comment]
@dominictb Can you please explain what the `getOriginalMessage` function is doing?

**Comment by allroundexperts** [comment]
Got it. Thanks for the explanation.

**Comment by allroundexperts** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/44217#issuecomment-2184410545) looks good to me. It has the correct RCA and the solution seems to work as well.

🎀 👀 🎀 C+ reviewed

**Comment by slafortune** [comment]
@allroundexperts can you please complete the checklist?

**Comment by allroundexperts** [comment]
## Checklist
1. I was not able to find the exact PR that caused this issue.
2. N/A
3. N/A
4. A regression test would be good to have.

### Regression test

1. Open the chat with self, and click '+' > Track Expense
2. On the actionable whisper options click on 'Submit it to someone'
3. Choose another user and Submit

Verify that the transaction is moved to that new chat and tracked expense is not displayed in the self DM anymore.
Also verify that the LHN of self-DM no longer shows "What would you like to do with this expense?"

Do we 👍 or 👎 ?
