### ISSUE TITLE
[HOLD for payment 2024-07-02] [$250] Search - RHP loads infinitely when deleting expense from report details page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44212]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  exp around vhttps://expensify.testrail.io/index.php?/tests/view/4662005 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Submit an expense to the user.
4. Go to Search.
5. Click on the expense submitted in Step 3.
6. Click on the report header.
7. Click Delete expense.
8. Delete the expense.

## Expected Result:
RHP will close because the transaction is deleted.

## Actual Result:
RHP loads infinitely.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/007fcf9f-dbc4-4644-8197-49c5f742d449

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d8ed6a1d54a3505</li>
        <li>Upwork Job ID: 1805219999552454866</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>tsa321 | Contributor | 102864301</li>
<li>c3024 | Contributor | 102869949</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by m-natarajan** [comment]
@jasperhuangg FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search - RHP loads infinitely when deleting expense from RHP

### What is the root cause of that problem?

New feature: delete from report details. The logic when user deletes expense report from report details  will go back to  previous screen. I think the correct navigation is to goback to transaction search page.

### What changes do you think we should make in order to solve the problem?



We could make a library function to get previous screen name, something like:
```javascript
const state = navigationRef.getState();
const previousScreenName = state.routes.at(-1)?.state?.routes?.at(-2)?.name;
// for further details we must check on the routes length; 
// this is used for illustration
```

In ReportDetailsPage, we can use this library function as `getPreviosScreenName`.

In here:

https://github.com/Expensify/App/blob/017605269c9f3a351522784aec04dd12644ec564/src/pages/ReportDetailsPage.tsx#L633-L637

Modify the code into:

```diff
if (!navigateBackToAfterDelete.current) {
    return;
}

+if (previousScreenName === SCREENS.RIGHT_MODAL.SEARCH_REPORT) {
+    navigateBackToAfterDelete.current = undefined;
+    Navigation.dismissModal();
+    return;
+}
Navigation.goBack(navigateBackToAfterDelete.current);

```

So we check on previous screen, if it is `SCREENS.RIGHT_MODAL.SEARCH_REPORT`, we dismiss the modal.

**Comment by mountiny** [comment]
@tsa321 do you have a link to the PR that caused this issue?

**Comment by tsa321** [comment]
@mountiny I believe It is new feature. The delete expense button is displayed in report details.
Here is from dev/staging:
![Screenshot 2024-06-24 at 18 14 40](https://github.com/Expensify/App/assets/114975543/e6e36010-e134-4aaf-9bc9-ba421d9a1992)



Here is from production
![Screenshot 2024-06-24 at 18 14 17](https://github.com/Expensify/App/assets/114975543/cb88090a-f03b-4b62-a1ee-5ec2882d99d9)

**Comment by mountiny** [comment]
Yeah I think the RHP should close and we should remove the expense from the search too cc @luacmartins

**Comment by luacmartins** [comment]
Sorry, didn't get to this one today. @tsa321 @WojtekBoman could you work on a PR to solve this once you get online? @WojtekBoman's solution [here](https://github.com/Expensify/App/issues/44212#issuecomment-2186584194) LGTM.

**Comment by tsa321** [comment]
@luacmartins  I am online now

**Comment by luacmartins** [comment]
Awesome! Please put up a PR!

**Comment by luacmartins** [comment]
Confirmed this fixed the bug in staging.

**Comment by jliexpensify** [comment]
Hi @c3024 - any checklist needed?

**Comment by c3024** [comment]
This is a new feature and the bug was caught in Staging itself so there is no regression test needed as well. I think there is no need for a checklist here.

**Comment by luacmartins** [comment]
Correct, we'll add test steps as part of the project wrap up.

**Comment by jliexpensify** [comment]
Payment Summary:

- Contributor: @tsa321 $250
- C+: @c3024 $250

[Upwork job](https://www.upwork.com/jobs/~012d8ed6a1d54a3505)

**Comment by jliexpensify** [comment]
Paid and job closed!
