### ISSUE TITLE
[Unapprove] Add unapprove to approved report on newDot

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#44228]
Design doc: https://docs.google.com/document/d/1SMogmfaVdQAQSx92I8vwEh9qFD8PbSEsKS9yK-trHmg

This is the frontend part only.

1. [Show “Unapprove” button in NewDot](https://docs.google.com/document/d/1SMogmfaVdQAQSx92I8vwEh9qFD8PbSEsKS9yK-trHmg/edit#bookmark=id.d5nx172ovq2y)
2. [Add new use of component ConfirmModal](https://docs.google.com/document/d/1SMogmfaVdQAQSx92I8vwEh9qFD8PbSEsKS9yK-trHmg/edit#bookmark=id.5lgk3xc3bv9s)
3. [Create function unapproveExpenseReport in NewDot](https://docs.google.com/document/d/1SMogmfaVdQAQSx92I8vwEh9qFD8PbSEsKS9yK-trHmg/edit#bookmark=id.hwig0bkijqs8)

**Comment by rushatgabhane** [comment]
@strepanier03 please assign this bug to me

**Comment by Beamanator** [comment]
Ummmmm why aren't we using https://github.com/Expensify/App/issues/44066 for this, where you're already assigned @rushatgabhane ?

**Comment by Beamanator** [comment]
Closing this one in favor of the other - feel free to reopen if I'm missing anything!
