### ISSUE TITLE
[Pay meow][$250]  "you haven't created any categories" appear for a moment when opening categories in workspace settings

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44224]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ZhenjaHorbach 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718993745779499

## Action Performed:

1. Open App (It's better to open app with an account that we haven’t used for a long time to be sure that we don't have cache )
2. Tap Account settings -> Workspaces
3. Choose any collect workspace
4. Tap Categories

## Expected Result:
List of categories appear
## Actual Result:
after opening the workspace categories, an empty state (You haven't created any categories) is displayed instead of a loading state
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/8c7859e7-58e4-483e-b2df-8c8b3e174b3b

https://github.com/Expensify/App/assets/38435837/2adfb2c8-f35d-4ddb-92f4-0f7ca749ab08

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad610832f3c79921</li>
        <li>Upwork Job ID: 1805471883229818637</li>
        <li>Last Price Increase: 2024-06-25</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 102866325</li>
<li>ZhenjaHorbach | Contributor | 102866327</li>
<li>dominictb | Contributor | 102961804</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by VictoriaExpensify** [comment]
I was able to recreate this, agree it's not great but it is a pretty low priority.

**Comment by VictoriaExpensify** [comment]
So sorry for the delay here! Automation didn't work and I hadn't been made the owner, so I missed it. Everything's paid up now:

**Payment Summary**
- Contributor: @dominictb paid via Upwork
- Contributor+: @ZhenjaHorbach via Upwork
[Upwork job](https://www.upwork.com/jobs/~01ad610832f3c79921)

Thanks for your work, everyone!
