### ISSUE TITLE
 Language Change Not Reflected After Signing In

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44248]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. If already signed in, sign out from the app and change the language.
2. Add a new Gmail account and sign in.
3. Notice that the language inside the app does not reflect the changed language.

## Expected Result:
When the language is changed and the user signs in, the app should display the new language.

## Actual Result:
When the language is changed and the user signs in, the app does not display the changed language.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/433bb2bf-02d8-436f-808c-7e3f12aecc47

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by kevinksullivan** [comment]
asking about this here

https://expensify.slack.com/archives/C01SKUP7QR0/p1719419321011069
