### ISSUE TITLE
Chat - Emoji reaction is shifted down from the center of the bubble

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44244]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4664804
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open iOS / iPad App
2. Login with any account
3. Open any chat
4. Select or send any message
5. Tap on "Add reaction" button for this message
6. Select any emoji
7. Check the emoji location in the bubble

## Expected Result:
Еmoji reaction is located in the horizontal center of the bubble

## Actual Result:
Emoji reaction is shifted down from the center of the bubble

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native/iPad
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e5d764ca-81fa-4a6d-973b-28bcc76de9b1

<img width="461" alt="Bug6521816_1719095101011!iPhone-Emoji-reactions-shifted-down-zoom" src="https://github.com/Expensify/App/assets/115492554/f126ac49-1921-42bc-9022-e7a0073fe3d1">

![Bug6521816_1719095101017!iPad-Emoji-reactions-shifted-down](https://github.com/Expensify/App/assets/115492554/a864755d-3c17-4dd7-b348-62268effcb03)

![Bug6521816_1719095101032!iPhone-Emoji-reactions-shifted-down](https://github.com/Expensify/App/assets/115492554/1d914b36-7021-4383-b9e7-c8f8e5ce7d5b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
This was so hard for me to tell the issue that I think we can close for now
