### ISSUE TITLE
Android - Attachment - Inconsistency in image size preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44250]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4666155&group_by=cases:section_id&group_order=asc&group_id=292107
**Email or phone of affected tester (no customers):** gocemate+workspaceemployee6@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. On a conversation, click on the + button in the compose box
2. Click on add attachment
3. Upload few images ( one of them should be a screenshot)
4. Open the screenshot
5. Verify that the screenshot image is fully previewed
6. Use the arrows to open other images and go back to the screenshot image
7. Take a look at size of the image preview

## Expected Result:
Image preview should be on full screen

## Actual Result:
Inconsistency in image size preview. When open first time image can be fully seen, and when open other images this image is smaller

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/74ce4178-c3ad-4498-a06c-4180b31b7a1a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by CortneyOfstad** [comment]
@slafortune and I tested this and we both agreed this is not a bug. The image size will be based on a few factors (file type — i.e. PNG will be different than a JPG and screenshots default to PNG; the physical size of the photo, etc). 

It will display the photos based on the best visibility as lower quality photos will be smaller to preserve the image as much as possible.
