### ISSUE TITLE
[CHECKLIST][HOLD for payment 2024-07-26] Tax - Add tax code

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#44258]
From the [design doc](https://docs.google.com/document/d/1dkS0mceibjUCMErQ1mWgUHjdHH0Ti_39DvgntRG-sws/edit#bookmark=id.3e61g1rtsjwd):

```
settings/workspaces/{policyID}/tax/{taxID}/tax-code -> TaxCodePage
- Parameter: taxID, the ID of the tax rate for which we are updating the tax code.
- Calls UpdateTaxCode
policyID
oldTaxCode - the old tax code for the tax rate.
newTaxCode - the updated tax code for the tax rate.
The pendingAction for the OfflineWithFeedback component will be currentTaxRate.pendingFields?.taxCode

```

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by jliexpensify** [comment]
Not overdue

**Comment by dangrous** [comment]
(adding myself due to review)

**Comment by jliexpensify** [comment]
Payment summary

- C+: @rushatgabhane (New.Dot Payment)

Is a checklist needed?

**Comment by mollfpr** [comment]
@jliexpensify Sorry, I forget to comment here that I'm reviewers the PR.

**Comment by rushatgabhane** [comment]
> Is a checklist needed

yep

**Comment by jliexpensify** [comment]
Hi @mollfpr -no problems, I can add you in. So did @rushatgabhane also review? I'm only seeing your name with the PR.

**Comment by jliexpensify** [comment]
It looks like @rushatgabhane worked on the issue and @mollfpr reviewed the final PR, right?

**Comment by rushatgabhane** [comment]
yep

**Comment by jliexpensify** [comment]
Awesome, just waiting on the checklist from @mollfpr - [payment summary is here.](https://github.com/Expensify/App/issues/44258#issuecomment-2249244886)

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr

**Comment by jliexpensify** [comment]
Bumping @mollfpr for the checklist

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good!

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Go to a control policy
2. Go to taxes page
3. Tap a tax rate
3. Verify that you can see tax code
4. Edit the tax code and save
5. Verify that the tax code is edited and saved
6. 👍 or 👎
