### ISSUE TITLE
Workspace  - Workspace template still shows as old model instead of updated template

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44254]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** emilio.utest+99@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43669
## Action Performed:
PreCondition: User has no Workspaces created prior
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to Profile > Workspace > Observe the template

## Expected Result:
User expects to see the new Workspace template with the "E" icon

## Actual Result:
User still sees the old WS template that shows the "Padlock" and "Alien Spaceship"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/075b339d-7830-45b4-9965-0c9edf9ca049

![according_to_the_PR_](https://github.com/Expensify/App/assets/78819774/b03cb233-5245-44f9-960e-b71d1b1ad955)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shawnborton** [comment]
This isn't a bug, we can close.
