### ISSUE TITLE
[HOLD for payment 2024-07-24] Policy category - Add Payroll Code

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#44256]
From the [design doc](https://docs.google.com/document/d/1dkS0mceibjUCMErQ1mWgUHjdHH0Ti_39DvgntRG-sws/edit#bookmark=id.qyclhfsfwutq):

```
settings/workspaces/{policyID}/categories/{categoryName}/payroll-code -> CategoryPayrollCodePage
- Parameter: categoryName, the name of the category for which we are updating the payroll code.
- Calls UpdateCategoryPayrollCode
policyID
categoryName - the name of the category for which we are updating the payroll code.
payrollCode - the updated payroll code for the category.
The pendingAction for the OfflineWithFeedback component will be policyCategory.pendingFields?.payrollCode

```

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by Gonals** [comment]
@rushatgabhane will be working on this

**Comment by rushatgabhane** [comment]
PR ready : https://github.com/Expensify/App/pull/43151

Can be merged once backend changes has been deployed

**Comment by kevinksullivan** [comment]
@rushatgabhane please complete the checklist

**Comment by kevinksullivan** [comment]
Payment summary:
- @rushatgabhane $250 (ND)
- @hoangzinh $250 (Upwork)

**Comment by rushatgabhane** [comment]
@hoangzinh is the c+ reviewer so they should complete the checklist

**Comment by kevinksullivan** [comment]
Thanks for clarifying @rushatgabhane

**Comment by kevinksullivan** [comment]
@hoangzinh please fill out checklist, accept [this job](https://www.upwork.com/jobs/~01e114258a94abf340), and lmk when you've done so!

**Comment by rushatgabhane** [comment]
@hoangzinh for C+
@rushatgabhane for PR author

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane

**Comment by kevinksullivan** [comment]
all set
