### ISSUE TITLE
[HybridApp] NewDot app is not loading with chats 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719022224303489

## Action Performed:
1. Launch the NewDot app

## Expected Result:
App should be loading without any issue

## Actual Result:
Not opening at all 
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/107b0df4-1b16-41fc-a2bd-795ec5216dcb

https://github.com/Expensify/App/assets/38435837/7be4175d-9012-48d2-b9a2-fbd274b7cb80

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
This issue has been resolved

**Comment by quinthar** [comment]
Happening again.

**Comment by quinthar** [comment]
Posted updated video in thread here: https://expensify.slack.com/archives/C05LX9D6E07/p1719861112788059?thread_ts=1719022224.303489&cid=C05LX9D6E07

**Comment by quinthar** [comment]
Still not working.

**Comment by quinthar** [comment]
Still happening

**Comment by AndrewGable** [comment]
We are working on this @MelvinBot

**Comment by quinthar** [comment]
Still working on it!

**Comment by AndrewGable** [comment]
Can you try this again @quinthar ?

**Comment by quinthar** [comment]
Tested, still happening; discussing in Slack

**Comment by puneetlath** [comment]
Seems to no longer be happening. Closing out for now. Reopen if it re-occurs!
