### ISSUE TITLE
Add payment card - Unable to add payment card to account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44267]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** rybkina+062424@gmail.com

**Issue found when executing PR** https://github.com/Expensify/App/pull/43473
## Action Performed:
1. Sign up for gmail account and create collect policy in OD
2. Navigate to https://staging.new.expensify.com/settings/subscription
3. Add credit card details from the 1password
4. Tap on 'Add payment card"

Case 2:
Try to add CC card:
cardNumber: '1234',
cardYear: 2026, cardMonth: 11
currency: 'USD', addressName: 'John Doe',

## Expected Result:
Payment card should be add and now have next billing date info and card data

## Actual Result:
Unable to add payment card to account. Popup is close Payment card doesn't added

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5cddb770-c090-4592-a414-4704b6d3b18e

https://github.com/Expensify/App/assets/78819774/a615d0c9-f4d2-44c8-beaa-91fae1a940b2

<img width="1147" alt="08 22 30" src="https://github.com/Expensify/App/assets/78819774/b014ac0a-72a5-4d65-a6c7-4c6beeab3e6e">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@youssef-lr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jacobkim9881** [comment]
Is okay to put credit card details for testing from the repro video?

**Comment by blimpich** [comment]
Not a deploy blocker because its not available to users yet. You have to know that the link exists and type it in manually to get to it.

**Comment by blimpich** [comment]
Picking up because it relates to subscription page stuff which I'm managing.

[Brought discussion to slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1719258468874079), I think this can be closed as expected but waiting to confirm.

**Comment by jacobkim9881** [comment]
@blimpich Thanks. I understood 😄

**Comment by blimpich** [comment]
Closing in favor of this issue: https://github.com/Expensify/App/issues/44362
