### ISSUE TITLE
[$125] Accounting - Empty space below Connections list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces
3. Go to Accounting

## Expected Result:
There will be no empty space below Connections list

## Actual Result:
There is empty space below Connections list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/442e6709-b16c-4fe0-ac22-31b974e93a32

![16-153](https://github.com/Expensify/App/assets/78819774/afbbbc45-17ac-484e-bcb9-7d0d102ba1eb)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f549cf0e732751ea</li>
        <li>Upwork Job ID: 1805357544136702694</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by neonbhai** [comment]
Not reproducible on latest main:

<img width="1680" alt="Screenshot 2024-06-24 at 6 54 19 PM" src="https://github.com/Expensify/App/assets/64629613/44529f70-92bc-48de-8f33-8d150be7ed86">

**Comment by mountiny** [comment]
I think this does not have to be a blocker, its very minor UI bug

**Comment by dixitparkhiya** [comment]
Not reproducible on latest main:
![image](https://github.com/Expensify/App/assets/31212922/e964b0a1-b522-4cd2-a1c3-d6bc6aa20520)

**Comment by johnmlee101** [comment]
👍 closing!
