### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Payments - Enable payments modal is dismissed by onboarding modal when new user login via link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44260]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4661829&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** gocemate+a407@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log out of NewDot
2. Navigate to staging.new.expensify.com/enable-payments
3. Sign in with new gmail account
4. Verify that Onboarding modal appears> Finish the flow

## Expected Result:
After completing the onboarding requests user should land on enable-payments page

## Actual Result:
Enable payments modal is dismissed by onboarding modal when new user login via link. User navigates to Concierge chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ce974f60-fa44-40ad-aa9c-86c436a93fa1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c600605bb01f4797</li>
        <li>Upwork Job ID: 1805389773516765926</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
Adding this to #wave-collect since it involves the payment process and onboarding

**Comment by rushatgabhane** [comment]
@daledah's [proposal](https://github.com/Expensify/App/issues/44260#issuecomment-2187873726) LGTM

🎀 👀 🎀

**Comment by stephanieelliott** [comment]
Hey @Gonals just waiting on your go-ahead for the proposal!

**Comment by stephanieelliott** [comment]
commenting again to remove label

**Comment by stephanieelliott** [comment]
Hey @daledah looks like the PR is waiting on you to resolve conflicts

**Comment by stephanieelliott** [comment]
PR is actively being reviewed.

**Comment by stephanieelliott** [comment]
PR is awaiting review from @rushatgabhane

**Comment by rushatgabhane** [comment]
PR on staging

**Comment by stephanieelliott** [comment]
Hey @daledah I extended an offer to you in Upwork -- can you please accept when you have a sec? https://www.upwork.com/nx/wm/offer/103443368

@rushatgabhane can you please complete the BZ checklist?

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @daledah $250 via Upwork -- PAID 
 - Contributor+: @rushatgabhane $250 via ND -- please request
 
 Upwork job is here: https://www.upwork.com/jobs/~01c5ddb8f6ccb0f8e7

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
