### ISSUE TITLE
Chat - messages sent while the conversation is loading in offline are not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44280]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** dawitseife9@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login to an account
2. Disable the internet connection in the device
3. Navigate to a chat with history that you have not opened
4. Notice that the chat opens and the loading animation is shown
5. Sent a message

## Expected Result:
Message is shown with 50% opacity

## Actual Result:
Sent Message is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2f2e1448-91e4-47a7-be94-c7dc2709e9d0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@dangrous  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by dangrous** [comment]
Looks like https://github.com/Expensify/App/pull/43970#issuecomment-2187250943 - looking into it now. Not backend.

**Comment by dangrous** [comment]
it's something with the definition of `shouldShowSkeleton`; if I hardcode that to false there's other weird behavior but the messages show.

Specifically, if I remove the `        (reportActions.length < paginationSize && !doesCreatedActionExists && !!reportMetadata?.isLoadingInitialReportActions) ||
` part, it also works correctly, so it's somewhere in that line.

**Comment by dangrous** [comment]
update: it's specifically the change from `reportActions.length === 0` to `reportActions.length < paginationSize`. The pending messages come back if you swap that code OR if you add 50 pending messages (in which case they all show back up).

Not sure what's the best way to fix without side effects

**Comment by dangrous** [comment]
reverting, to unblock

**Comment by dangrous** [comment]
oh labels got weird here, will fix after i confirm we're good to go

**Comment by dangrous** [comment]
Okay this has indeed been fixed on staging! Copied test steps to original issue so they can ensure it's fixed in the next round.
