### ISSUE TITLE
Web - Security - "<" button on the "Two-factor authentication" page is selected after entering 2FA

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#44288]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an account without 2FA
3. Navigate to Account settings - Security - Two-factor authentication
4. Copy the codes
5. Click on the "Next" button
6. Scan the QR code on mobile
7. Enter the verification code
8. Click on the "Next" button

## Expected Result:
The button shouldn't be selected.

## Actual Result:
"<" button on the "Two-factor authentication" page is selected after entering the verification 2FA code.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3d70d5b9-34cc-4917-8e84-6b2c208e7995

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment]
@OfstadC FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MonilBhavsar** [comment]
A note - This is a minor design issue so can be started at $125

**Comment by OfstadC** [comment]
Added to Live Markdown based on [this post](https://expensify.slack.com/archives/C01SKUP7QR0/p1718735202154699) 😄

**Comment by BartoszGrajdek** [comment]
Hi! I'm Bartosz from SWM `react-native-live-markdown` team. I don't think this issue is related to live markdown. I'm guessing you've added it because of "<" in the title, but in this case, it's not a markdown quote, so we can remove it from the project. 😄 

Thank you for taking immediate action! 🙏

**Comment by OfstadC** [comment]
Thanks for confirming @BartoszGrajdek 😄

**Comment by OfstadC** [comment]
Ah okay - I misunderstood this lol - Sorry folks! 

So once you enter the code it's auto selecting the button - I feel like that's fine, no? Going to raise in Slack

**Comment by OfstadC** [comment]
Confirmed in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1719424545666299) this is a feature not a bug - so closing for now. Thanks for reporting! 😃
