### ISSUE TITLE
[HOLD for payment 2024-08-07] [Workspace Feeds] [External] Create UI and logic for Steps 1-6 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44309]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.pe5bvqlu432w).

@koko57 @VickyStash @allgandalf @DylanDylann 

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by koko57** [comment]
taking this one 😃

**Comment by koko57** [comment]
update: UI for steps 2-6 is almost done. The Assignee step is a bit harder as it requires some mocking for now, I will tackle it tomorrow.

**Comment by koko57** [comment]
Still working on the members list, I should be able to open the PR on Monday

**Comment by DylanDylann** [comment]
@koko57 Could you give an ETA for the PR? Thanks

**Comment by koko57** [comment]
@DylanDylann working on it - probably today I will be able to open the PR

**Comment by koko57** [comment]
@DylanDylann @mountiny @MariaHCD - I'm opening a draft for now, I need to fill in the checklist and test on all devices, but if you want you can take a look at the code. There are still some TODOs, but I would rather do that in another PR, ideally when the BE is ready

**Comment by koko57** [comment]
I'm still fighting a bit with AmountForm for limit step styles and the icon not being displayed in android native, but opening this PR for the review: https://github.com/Expensify/App/pull/44741

**Comment by koko57** [comment]
TODO:

- [ ] StartIssueNewCardFlow
- [ ] style fixes: https://github.com/Expensify/App/pull/44770#issuecomment-2237052455

**Comment by koko57** [comment]
Starting to work on the integration with StartIssueNewCardFlow

**Comment by koko57** [comment]
I drafted the PR for integration with the BE - @mountiny does it make sense to test it on all of the devices or web is just sufficient?

**Comment by mountiny** [comment]
Web and one native platform will be good for you, c+ can test all platforms

**Comment by koko57** [comment]
@MariaHCD why is the employee list sent like this (pic below), not in the onyxData like in OpenWorkspaceMemberPage?
<img width="490" alt="Screenshot 2024-07-23 at 08 51 35" src="https://github.com/user-attachments/assets/cd6095cd-319c-4314-9b73-7dd157b345fa"><img width="483" alt="Screenshot 2024-07-23 at 08 52 09" src="https://github.com/user-attachments/assets/85c565d5-534c-4b6d-b31e-1948ec23d1cc">

**Comment by MariaHCD** [comment]
> why is the employee list sent like this (pic below), not in the onyxData like in OpenWorkspaceMemberPage?

The way that StartIssueNewCardFlow structures the data is a bit different from OpenWorkspaceMemberPage. 

@mountiny @nkuoch Perhaps we should just have StartIssueNewCardFlow done the same way as [these](https://github.com/Expensify/Web-Expensify/blob/bca153a62d2d2e06f2015ea5dcdd637bb204ec9d/api.php#L4007-L4016) API endpoints?

**Comment by mountiny** [comment]
Yeah we need to update that to match the policy formatting

**Comment by mountiny** [comment]
I can try ot make a PR for this

**Comment by koko57** [comment]
@mountiny could you please ping me in this issue when it'll be on staging?

**Comment by mountiny** [comment]
@koko57 Will do!

**Comment by mountiny** [comment]
Tested locally and works well, added info [here](https://github.com/Expensify/App/pull/45912#issuecomment-2244707891)

**Comment by bfitzexpensify** [comment]
Offer sent @DylanDylann

**Comment by DylanDylann** [comment]
@bfitzexpensify This belongs to the Workspace Feed project. No need for payment here

**Comment by bfitzexpensify** [comment]
Gotcha. Closing this out then
