### ISSUE TITLE
[Workspace Feeds] [External] Add logic for the disabled toggle

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44302]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement [the following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.g2nf4jcnzsph).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.
