### ISSUE TITLE
[Workspace Feeds] [External] Add new toggle to the More Features page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44301]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.7vymuw7ozkps).

@koko57 @VickyStash @allgandalf @DylanDylann 

<details><summary>Issue Owner</summary>Current Issue Owner: @narefyev91</details>

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.

**Comment by narefyev91** [comment]
Today PR will be raised
