### ISSUE TITLE
[Workspace Feeds] [External] Add Enable Cards item in the WorkspaceInitialPage

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44303]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.gs3z6852enyh).

@koko57 @VickyStash @allgandalf @DylanDylann 

<details><summary>Issue Owner</summary>Current Issue Owner: @narefyev91</details>

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.

**Comment by koko57** [comment]
@allgandalf I think we should have it opened - we will need to integrate it with the BE when it's ready

**Comment by mountiny** [comment]
I can see thi sis connected to the backend so yeah I think we can close
