### ISSUE TITLE
[$250]  [Workspace Feeds] [External] Create Issue new card logic - existing bank accounts

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44305]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.bn5eecz3qkao).

@koko57 @VickyStash @allgandalf @DylanDylann 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158e10f660e37eba9</li>
        <li>Upwork Job ID: 1829663320180822484</li>
        <li>Last Price Increase: 2024-08-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by koko57** [comment]
I'd like to work on this issue 🙂

**Comment by koko57** [comment]
not overdue, will be done later this week

**Comment by koko57** [comment]
I think we should wait for https://github.com/Expensify/App/pull/44770 to be merged, then I can start working on this

**Comment by mountiny** [comment]
https://github.com/Expensify/App/pull/44770 was merged so this can be worked on

**Comment by koko57** [comment]
started working on it

**Comment by koko57** [comment]
for now drafting the PR: https://github.com/Expensify/App/pull/45069

**Comment by koko57** [comment]
@mountiny I'm having a problem with opening it on simulator to record the video. I've tested it on android/web/desktop. Can I open the PR anyway?

**Comment by koko57** [comment]
PR opened: https://github.com/Expensify/App/pull/45069

**Comment by DylanDylann** [comment]
No need payment here

**Comment by mountiny** [comment]
@koko57 should we keep this opened to connect be?

**Comment by koko57** [comment]
yes

**Comment by mountiny** [comment]
Not overdue

**Comment by koko57** [comment]
Drafting a PR for now -  the endpoint is not ready yet, but feel free to check the code https://github.com/Expensify/App/pull/46564

**Comment by mallenexpensify** [comment]
@DylanDylann can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0158e10f660e37eba9

Apologies for the delay,  automation failed (and I might have figured out a fix for it).

**Comment by DylanDylann** [comment]
It belongs to our project. No need payment

**Comment by mountiny** [comment]
This can be closed now I think
