### ISSUE TITLE
[HOLD for payment 2024-07-17] [Workspace Feeds] [External] Logic for saving the data and navigating between steps

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44308]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.v4nq1md2zi2o).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by koko57** [comment]
taking this issue 🙂

**Comment by DylanDylann** [comment]
I will take this one

**Comment by koko57** [comment]
@DylanDylann @mountiny PR ready for review

**Comment by DylanDylann** [comment]
@koko57  I just glanced at the design doc for this project. Why do we start this project on this issue? Should we implement these features followed by the order in the design doc? I think It will be easy to test and control the process of this project

cc @MariaHCD @mountiny @allgandalf @VickyStash

**Comment by mountiny** [comment]
I agree, we still need to work on the backend so at this point we are focusing on creating the frontend flows and getting as much of the UI done as possible so we are in a good spot once we get the backend into a ready state

**Comment by trjExpensify** [comment]
Did this issue get covered by this PR https://github.com/Expensify/App/pull/44376?

**Comment by koko57** [comment]
@trjExpensify yes

**Comment by koko57** [comment]
@mountiny we can close this. There will be no follow-up PR for this one.

**Comment by mountiny** [comment]
Ok thank you!
