### ISSUE TITLE
[HOLD for payment 2024-08-01]  [Workspace Feeds] [External] Create a modal for Expensify Card Enabled empty state

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44306]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.vl58w57nurgw).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by DylanDylann** [comment]
I will take over this one

**Comment by koko57** [comment]
Taking this issue 😊

**Comment by mountiny** [comment]
This is off hold now

**Comment by koko57** [comment]
@shawnborton I see that the component created in #44137 accepts either a lottie animation, video or an svg. How should be this asset exported? 
<img width="565" alt="Screenshot 2024-07-16 at 16 25 04" src="https://github.com/user-attachments/assets/dc7ee83b-1f5a-47b3-80d9-35cb130f73cf">

**Comment by shawnborton** [comment]
Fairly certain this one is just static, so just an .svg would do? Let me try to export something for you...

**Comment by shawnborton** [comment]
Let's try this and see if it works? [emptystate__expensifycard.svg.zip](https://github.com/user-attachments/files/16252885/emptystate__expensifycard.svg.zip)

cc @Expensify/design - tried to make this an actual svg with no pngs embedded or anything, let's see how it goes!

**Comment by koko57** [comment]
@shawnborton I've just noticed that the screenshot element in the svg you exported doesn't have rounded corners
<img width="356" alt="Screenshot 2024-07-18 at 10 18 06" src="https://github.com/user-attachments/assets/0223ce0f-686f-42a2-99d8-c03ea3e83f76">

Could you check why they're not rounded and export a new version please?🙏🏻

**Comment by shawnborton** [comment]
Ah good catch! Here is an updated version: [emptystate__expensifycard.svg.zip](https://github.com/user-attachments/files/16280747/emptystate__expensifycard.svg.zip)

**Comment by koko57** [comment]
Fighting a bit with svg size on mobile, but it's almost ready (PR in draft)

**Comment by mountiny** [comment]
This was merged 🎉

**Comment by JmillsExpensify** [comment]
$250 for @DylanDylann for PR review and testing.

**Comment by DylanDylann** [comment]
@JmillsExpensify No need for payment here. This belongs to project

**Comment by JmillsExpensify** [comment]
Oh ok cool thanks! Closing then.
