### ISSUE TITLE
[HOLD for payment 2024-07-17] [Workspace Feeds] [External] Create a new Expensify Card workspace page - empty state

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44304]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.dd7fzkdi4jte).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by DylanDylann** [comment]
I will take over this one

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.
