### ISSUE TITLE
[HOLD for payment 2024-08-09] [Workspace Feeds] [External] Add a support for new system messages

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44307]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.f10kmfvd6kvp).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by mountiny** [comment]
@koko57 will work on this one

**Comment by mountiny** [comment]
Will be picked up soon

**Comment by koko57** [comment]
@mountiny [same](https://github.com/Expensify/App/issues/44317#issuecomment-2238881587) here- should we wait for the backend?

**Comment by mountiny** [comment]
yes

**Comment by trjExpensify** [comment]
Updated the title to reflect the hold on #407836

**Comment by koko57** [comment]
@trjExpensify this one should be on hold 😃 https://github.com/Expensify/App/issues/44317 - @mountiny has already updated the title. This one - I can start working on it

**Comment by mountiny** [comment]
Yeah I think there is actually not many changes for this one and they do not have to be on hold, will update the title

**Comment by trjExpensify** [comment]
Great, let's do it then!

**Comment by koko57** [comment]
@mountiny @shawnborton these messages will appear in the Workspace chat or in a chat with the user we're assigning the card? I've noticed one thing:
for the CARDISSUED and CARDMISSINGADDRESS we're showing the assignee name, whereas for the CARDISSUEDVIRTUAL we're showing "You" instead of the user's name.
<img width="376" alt="Screenshot 2024-07-25 at 11 56 16" src="https://github.com/user-attachments/assets/3710b03d-5d54-4f1e-8490-13556c79fe8f">
<img width="388" alt="Screenshot 2024-07-25 at 11 55 51" src="https://github.com/user-attachments/assets/020bd881-b319-43bc-b8f8-609155b0e950">
<img width="306" alt="Screenshot 2024-07-25 at 11 55 36" src="https://github.com/user-attachments/assets/dc96e59d-2a1a-4d19-9e9d-389480176434">
I think we should stick to the one pattern, if it's a direct message to the user assigned maybe it would be better to go with "You" (no logic for user name and pronouns would be required). If it would be a workspace message visible to other users we have to go with the name though.

**Comment by trjExpensify** [comment]
I agree they should be consistent. I _think_ we wanted to use a mention to GBR the chat for the user being issued a card for added awareness. 

I totally agree with not using "You" or including gender specific copy that needs to be "pronoun aware". CC: @kevinksullivan not sure why we did that really.

**Comment by trjExpensify** [comment]
>these messages will appear in the Workspace chat or in a chat with the user we're assigning the card?

Oh, and yes, these messages are posted in the workspace chat of the member being assigned a card. 👍

**Comment by koko57** [comment]
@trjExpensify thanks! So we're going with pattern:
a 
<img width="376" alt="Screenshot 2024-07-25 at 11 56 16" src="https://github.com/user-attachments/assets/acd56a52-1c06-4c87-904e-91b07dde3878">
or b
<img width="306" alt="Screenshot 2024-07-25 at 11 55 36" src="https://github.com/user-attachments/assets/987dc281-3d24-479e-ac9b-34de52dbcdf7">

**Comment by trjExpensify** [comment]
A! There can me other people in the workspace chat.

**Comment by kevinksullivan** [comment]
Agree with the cionsistency, I think that was an oversight on my part. Here is alternative copy we can use to avoid pronouns/"you", while keeping the mention:

> Issued @kevin an Expensify Card! The card will be shipped once a mailing address is added.

> Issued @kevin an Expensify Card! The card will arrive in 2-3 business days.

> Issued @kevin a virtual %Expensify Card%! The card can be used right away.

**Comment by trjExpensify** [comment]
Love it!

**Comment by mountiny** [comment]
This is better also because we can send the same message to everyone

**Comment by koko57** [comment]
@kevinksullivan great! Thanks!

**Comment by koko57** [comment]
@MariaHCD will there be the card assignee accountID in the report action item?

**Comment by mountiny** [comment]
@koko57 yes, it will be in message.assigneeAccountID as int

**Comment by koko57** [comment]
opening the PR for review although typecheck fails strangely

**Comment by mountiny** [comment]
This is non-core issue so focusing elsewhere

**Comment by mountiny** [comment]
Keeping this open until we get this tested in full stack

**Comment by mountiny** [comment]
Focusing on getting the core issues in and then tacking this

**Comment by mountiny** [comment]
This is being tackled on this week

**Comment by mountiny** [comment]
We are working on cleaning up these messages

**Comment by mountiny** [comment]
We need to still update slightly the message in BE so not closing

**Comment by mountiny** [comment]
I wonder what is left to do here, we have tested the report actions already so maybe we can close this one 🤔 @MariaHCD @trjExpensify

**Comment by trjExpensify** [comment]
Yeah, what did you mean by this though?

> We need to still update slightly the message in BE so not closing

**Comment by mountiny** [comment]
Right, sometimes I do mean things I write, the auth messages do not have the mentions in them.

Gonna make a PR for it

**Comment by mountiny** [comment]
PR is ready and we can close it after https://github.com/Expensify/Auth/pull/12579

**Comment by trjExpensify** [comment]
Dope, deployed, closing!
