### ISSUE TITLE
[Workspace Feeds] [External] Disable card reconciliation when auto-sync not enabled

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44318]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.8zi2rj8zs2vy).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by VickyStash** [comment]
It looks like implementing of this issue should be much easier when [Card Reconciliation page PR](https://github.com/Expensify/App/pull/44968) is merged, so I'll continue to work on it after that.

**Comment by mountiny** [comment]
@VickyStash this should be off hold now

**Comment by VickyStash** [comment]
**Updates:** 
I have added the Continuous Reconciliation toggle and its logic. There are just a couple of minor updates and PR preparations left.
I'll open it for review tomorrow.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/45452) has been opened for the review 👀

**Comment by DylanDylann** [comment]
Reviewing PR

**Comment by mountiny** [comment]
we can close this one now I thinks
