### ISSUE TITLE
[HOLD for payment 2024-08-01] [Workspace Feeds] [External] Create new Settlement Account page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44313]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.2n8vl1uozxb5).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by koko57** [comment]
Taking this one 😃

**Comment by koko57** [comment]
WIP - changes are on this branch https://github.com/koko57/App/tree/feature/44311-card-settings-page. Tomorrow I'm ooo, I will continue on Monday.

**Comment by koko57** [comment]
Will get back to it tomorrow

**Comment by koko57** [comment]
Left the update here: https://github.com/Expensify/App/issues/44311#issuecomment-2222831433

**Comment by mountiny** [comment]
Handling the above mentioned bug and added it to the project
