### ISSUE TITLE
[HOLD for payment 2024-08-05] [Workspace Feeds] [External] A new section in the workspace member’s details

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44319]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.4feakltfl9p0).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by mountiny** [comment]
Will be worked on soon

**Comment by waterim** [comment]
Hello Im Artem from Callstack and would like to work on this issue

**Comment by trjExpensify** [comment]
Assigned you, @waterim!

**Comment by trjExpensify** [comment]
I shared the doc with you, but then realised.. @DylanDylann & @allgandalf are C+ on this project. So who's taking it?

**Comment by johncschuster** [comment]
@mountiny is payment being handled in this issue, or is this part of a larger project?

**Comment by johncschuster** [comment]
# Payment Summary
@allgandalf - $amountUnknown - requires payment via Manual Request

**Comment by mountiny** [comment]
@johncschuster sorry for late reply, i was ooo. We do not have to handle the payments here as this is a project work and both Gandalf and DylanDylann will be paid in one go after the project completion

**Comment by johncschuster** [comment]
Oh perfect! Thank you for clarifying that!
