### ISSUE TITLE
[HOLD for payment 2024-07-24] [Workspace Feeds] [External] Create new Reconciliation Account Settings page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44316]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.72zjnpc8k7ub).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by VickyStash** [comment]
**Updates**: WIP on the page functionality, I think it should be possible to open a PR tomorrow.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/45047) has been opened for the review

**Comment by DylanDylann** [comment]
@allgandalf  Feel free to rest and get better soon, I'll take care this PR

**Comment by DylanDylann** [comment]
No need for payment here
