### ISSUE TITLE
[Workspace Feeds] [External] Create new Card List page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44310]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.xiimuxjsjy32).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
**Updates for today:**
- Added a new route and component for `WorkspaceCardPageFree` page
- Implemented Card List display using CardListHeader and CardListRow components

**Comment by VickyStash** [comment]
**Updates for today:**
- Implemented Current Balance, Remaining Limit, and Cash Back display with modals.
- Added function for OpenPolicyExpensifyCardsPage API call and ONYX keys/type to easily get the data in the future.

**Plans for tomorrow:**
- Add `Request limit increase` button functionality
- Check the UI on the different platforms
- Prepare the PR for review

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/44469) is ready for the review.

**Comment by VickyStash** [comment]
Note: I'm going to be OOO Jul 1- Jul 7 🌴

**Comment by koko57** [comment]
@allgandalf I think we should have it opened - we will need to integrate it with the BE when it's ready

**Comment by dylanexpensify** [comment]
Nice one, thanks Gandalf!

**Comment by johncschuster** [comment]
Payment Summary:

Contributor+: @allgandalf paid $250 via [Upwork](https://www.upwork.com/jobs/~01da5badf0fabc16c3)

**Comment by Travis452** [comment]
Hello, could I contribute to this project?

**Comment by johncschuster** [comment]
How's this one going?

**Comment by VickyStash** [comment]
Since [OpenPolicyExpensifyCardsPage](https://github.com/Expensify/Expensify/issues/407503) API endpoint was implemented I'm going to finalize BE integration tomorrow.
I'll keep you updated about it.

**Comment by VickyStash** [comment]
Update: waiting for [this PR](https://github.com/Expensify/App/pull/46564) to be merged to continue

**Comment by VickyStash** [comment]
**Updates:**
- Enabled OpenPolicyExpensifyCardsPage API call, tested the received data on different screens
- Use workspaceAccountID instead of policyID inside Onyx keys to receive the correct data
- Updated the code to use unapprovedExpenseLimit as a card limit
- Working on the correct card list page loading

The PR will be opened to the review only when next PR's are merged: https://github.com/Expensify/App/pull/46570, https://github.com/Expensify/App/pull/46564

**Comment by mountiny** [comment]
Thanks!

**Comment by VickyStash** [comment]
**Updates:**
- Implemented card list page loading indication
- Fixed console error
- Waiting for blocking PR's https://github.com/Expensify/App/pull/46570, https://github.com/Expensify/App/pull/46564 to be merged

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/47064) with **OpenPolicyExpensifyCardsPage** API call integration is open for the review!

**Comment by mountiny** [comment]
I believe this is all merged and we can close it
