### ISSUE TITLE
[HOLD for payment 2024-08-01] [Workspace Feeds] [External] Create new Card Settings page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44311]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.1xr2oqvvql8y).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by koko57** [comment]
I can start working on this issue

**Comment by trjExpensify** [comment]
Assigned you!

**Comment by koko57** [comment]
WIP - changes are on this branch https://github.com/koko57/App/tree/feature/44311-card-settings-page. Tomorrow I'm ooo, I will continue on Monday.

**Comment by koko57** [comment]
@allgandalf working on it, but now prioritizing last tasks from phase 1

**Comment by koko57** [comment]
Last 2 days I was mainly focused on #44305 and taken over the PR for #44315. Tomorrow I'm ooo, I will get back to it next week.

**Comment by koko57** [comment]
Drafted PR for now - I need to rethink one thing and probably work on a solution with Maria and I also need to test it out on all the platforms.

**Comment by koko57** [comment]
@allgandalf will be open today 😃

**Comment by koko57** [comment]
@allgandalf PR opened: https://github.com/Expensify/App/pull/45415

**Comment by trjExpensify** [comment]
I don't think it squarely fits, but the monthly settlement requirements are on this page: https://help.expensify.com/articles/expensify-classic/expensify-card/Admin-Card-Settings-and-Features

That said:

1. It's an article in the Expensify Classic collection
2. It talks about domains etc

So I think ideally, we need to link to a New Expensify article, which is tailored to workspace feeds. @joekaufmanexpensify is leading that here (internal link): https://github.com/Expensify/Expensify/issues/408330

**Comment by joekaufmanexpensify** [comment]
Yep, the new help article I'm writing will include a section about the card settings page.

**Comment by sonialiap** [comment]
Since[ no payment is needed](https://github.com/Expensify/App/issues/44311#issuecomment-2254944617), closing
