### ISSUE TITLE
[Workspace Feeds] [External] Add a new object to connectionsMenuItems

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44314]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.a1fvowl84thj).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by sakluger** [comment]
@DylanDylann I updated the payment summary above with the correct Upwork offer link. Please let me know once you've accepted the offer. Thanks!

**Comment by DylanDylann** [comment]
This belongs to the project. No need payment

**Comment by sakluger** [comment]
Got it, thanks for clarifying! In that case we can close out the issue.
