### ISSUE TITLE
[Workspace Feeds] [External] Create new Edit Card Limit page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44326]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.dpyvfflqgte0).

@koko57 @VickyStash @allgandalf @DylanDylann 

<details><summary>Issue Owner</summary>Current Issue Owner: @VickyStash</details>

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by mountiny** [comment]
Thanks

**Comment by VickyStash** [comment]
**Updates:** 
WIP, I've implemented a new screen and route, just need to add a confirmation modal and prepare a PR. The PR should be ready on Monday. Branch with updates: [feature/44326-edit-card-limit](https://github.com/VickyStash/Expensify/tree/feature/44326-edit-card-limit)

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/45397) has been opened for the review 👀

**Comment by mountiny** [comment]
Leaving this open to integrate the BE

**Comment by JmillsExpensify** [comment]
$250 summary above is correct for @DylanDylann

**Comment by JmillsExpensify** [comment]
Also remind me, are you paid via Upwork or New Expensify?

**Comment by DylanDylann** [comment]
This issue belongs to our project, There no need for payment

**Comment by VickyStash** [comment]
Since **UpdateExpensifyCardLimit** API endpoint is ready I'm going to work on BE integration

**Comment by mountiny** [comment]
@VickyStash thanks, hit us up in Slack if you have any questions

**Comment by JmillsExpensify** [comment]
Can I close this issue or should I keep it open?

**Comment by mountiny** [comment]
We are still connecting it to the backend so lets keep it open but you do not have to be assigned

**Comment by VickyStash** [comment]
The API call was [implemented](https://github.com/Expensify/App/blob/98124799a639606573877bf6eb38554ee2939a22/src/libs/actions/Card.ts#L316-L374) during the page implementation. There are some minor fixes/updates to make the card limit update work as expected in the [PR](https://github.com/Expensify/App/pull/47064) related to OpenPolicyExpensifyCardsPage API call integration.

I've tested how **UpdateExpensifyCardLimit** API call works, and the result looks as expected:
![image](https://github.com/user-attachments/assets/b1759407-9e67-4788-b7bf-e94900ad2796)

So we can just wait till the mentioned PR is merged and it should work as expected.

**Comment by mountiny** [comment]
Perfect, thanks!

**Comment by mountiny** [comment]
Not overdue, we are actively working on this one

**Comment by mountiny** [comment]
This can be closed now I think
