### ISSUE TITLE
[Workspace Feeds] [External] Integrate Deactivate_Card API

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44320]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.k9tp52aaxcml).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by mountiny** [comment]
Will be worked on soon

**Comment by waterim** [comment]
Hello Im Artem from Callstack and would like to work on this issue

**Comment by trjExpensify** [comment]
Assigned you, @waterim!

**Comment by DylanDylann** [comment]
There is no need for payment. Let's close as completed

**Comment by koko57** [comment]
maybe let's not close it as the BE is not integrated yet

**Comment by mountiny** [comment]
I think this can be worked on soon, the API commands should exist for this now

**Comment by mountiny** [comment]
We will bump this in the next update for the project

**Comment by mountiny** [comment]
We still need to integrate this with the API

**Comment by MariaHCD** [comment]
We're working on the BE: https://github.com/Expensify/Auth/pull/12150

**Comment by MariaHCD** [comment]
@koko57 The BE is ready!

As a note, the initial approach we had in the design doc is now outdated

> For physical cards, we will call Card_Deactivate command with cardID, for virtual - Card_EditAdminIssuedVirtualCard with a cardLimit of 0. This will lead to the card being deactivated. 

We will be using a single API command: `Card_Deactivate` that accepts a string `authToken` and int `cardID` for both physical cards and virtual cards.

**Comment by koko57** [comment]
@MariaHCD ok, thanks! Me or someone from our team will take care of it

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on `Card_Deactivate` integration.

**Comment by trjExpensify** [comment]
Assigned you, @VickyStash!

**Comment by VickyStash** [comment]
**Updates:** I've implemented the `Card_Deactivate` API call and working on the UI updates to support deactivated cards. I think the PR should be ready on Monday.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/47986) is ready for the review!

**Comment by mountiny** [comment]
PR is actively being worked on

**Comment by kevinksullivan** [comment]
unassigning myself as I am going OOO. If we end up needing a payment (I don't believe we do) just put the bug label back on this!

**Comment by mountiny** [comment]
This is done
