### ISSUE TITLE
[Workspace Feeds] [External] Create Deactivate card logic

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44324]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.7ibar03wy6f7).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by DylanDylann** [comment]
@mountiny Dupe https://github.com/Expensify/App/issues/44320
