### ISSUE TITLE
[Workspace Feeds] [External] Create new Edit Card Name page

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44327]
Part of the [Workspace feeds](https://github.com/Expensify/Expensify/issues/380605) project.

Implement the [following part of the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.4sixqivbhuf8).

@koko57 @VickyStash @allgandalf @DylanDylann

**Comment by mountiny** [comment]
Later phase of implementation

**Comment by mountiny** [comment]
@VickyStash will work on this one

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
@shawnborton Is it how the Edit Card Name page should look like?
![image](https://github.com/user-attachments/assets/2aa78aba-138a-4f56-9152-b45b06ca74b1)
![image](https://github.com/user-attachments/assets/786a4094-5ad0-494a-855a-f15179c38538)

**Comment by shawnborton** [comment]
cc @dubielzyk-expensify who worked on the UI/UX for this project. But at first glance this seems correct to me? cc @Expensify/design

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/45473) has been opened for the review

**Comment by dubielzyk-expensify** [comment]
Yep that looks good to me 👍

**Comment by jayeshmangwani** [comment]
@mountiny Melvin auto-assigned me to review the PR, but I think the Workspace feeds project's PRs will be reviewed by @allgandalf  and @DylanDylann right?

**Comment by mountiny** [comment]
Lets keep this open for the integration

**Comment by mountiny** [comment]
We should be able to integrate this one this week

**Comment by mountiny** [comment]
`UpdateExpensifyCardTitle`

Params:
- string authToken
- number cardID
- string cardName

**Comment by VickyStash** [comment]
Hi! I'm going to work on BE integration of **UpdateExpensifyCardTitle** here

**Comment by VickyStash** [comment]
> `UpdateExpensifyCardTitle`
> 
> Params:
> 
> * string authToken
> * number cardID
> * string cardName

@mountiny it looks like `cardTitle` not `cardName` should be passed
With `cardTitle` the API call works as expected.
![image](https://github.com/user-attachments/assets/07c17db4-2865-4280-8e81-9dde2c15574a)

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/47394) with `UpdateExpensifyCardTitle` API call integration is ready for the review

**Comment by trjExpensify** [comment]
Any reason this issue is still open?

**Comment by koko57** [comment]
it's already integrated with the BE, so we can close it
