### ISSUE TITLE
Search page expenses showing Personal in `To` field and "not found" message when opening

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44339]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.1-12
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719219088507519

## Action Performed:
1. Open app
2. Click search
3. verify the `TO` field
4. Open the expense
## Expected Result:
Personal shouldn't be displayed and clicking on it should show the expense
## Actual Result:
Hmm not there page appears
## Workaround:
unknown 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-06-24 at 10 50 54@2x](https://github.com/Expensify/App/assets/38435837/949cd297-4c29-4528-854f-e9fcb47b2e88)

https://github.com/Expensify/App/assets/38435837/cb8fbf2b-b662-4ea2-b087-9d96096d9470

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
I think we can close this one. These were old test expenses. We already have another issue to work on the deleted/moved transactions.

**Comment by shawnborton** [comment]
Makes sense to me.
