### ISSUE TITLE
[HOLD for payment 2024-07-02] [$250] Search - Transaction RHP dismisses when holding/unholding expense from report details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-10
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit two expenses to any user
3. Go to Search
4. Open the transaction RHP of any of the submitted expenses
5. Hold and unhold the expense from 3-dot menu
5. Note that the transaction RHP does not dismiss when holding and unholding expense from the 3-dot menu
6. Open the same transaction RHP again
7. Click on the report header
8. Hold and unhold the expense from the report details page
9. Note that the transaction RHP dismisses each time the expense is held and unheld

## Expected Result:
When holding and unholding expense in Search via report details RHP, the transaction RHP will not dismiss

## Actual Result:
When holding and unholding expense in Search via report details RHP, the transaction RHP dismisses

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2de0c3e6-2c56-4cdf-983e-e13eb9a1ad04

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b190e03e676aa45</li>
        <li>Upwork Job ID: 1805348998427340557</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102862197</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment]
@neil-marcellini  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neil-marcellini** [comment]
👀 taking a look now

**Comment by neil-marcellini** [comment]
Thanks @Krishna2323! That sounds good, hired. Please get started right away.

**Comment by neil-marcellini** [comment]
@Krishna2323 how's it going. When do you expect to have the PR up for review?

**Comment by neil-marcellini** [comment]
Ah ok, thanks for the update. If you end up implementing something much different than your proposal it would be a good idea to update it.

**Comment by neil-marcellini** [comment]
Yeah I think that all sounds good. I'll review the PR now.

**Comment by mountiny** [comment]
THe PR will be validated after being CPed

**Comment by OfstadC** [comment]
Payment Summary:

Contributor: @Krishna2323 paid $250 via Upwork
Contributor+: @sobitneupane is **due** $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
