### ISSUE TITLE
[$250] Wrong color is used for the active LHN item

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44355]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1719240834164559

## Action Performed:
1. Open app
2.  Check the background color of the LHN active item
3. Click search
4. Observe the background color of the active item
## Expected Result:
Should be matching product color
## Actual Result:
LHN is too dark color
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-06-24 at 16 54 13@2x](https://github.com/Expensify/App/assets/38435837/952fa1e8-9afb-45ed-9873-7042488f6fca)
![CleanShot 2024-06-24 at 16 53 11@2x](https://github.com/Expensify/App/assets/38435837/445dfe2a-9f4d-4bec-8022-c332e095d733)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f381017700feec87</li>
        <li>Upwork Job ID: 1810386505822534382</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by shawnborton** [comment]
Ah I do think that linked PR will fix things, so perhaps we can close this out.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
