### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Payment card / Subscription] fix card data not showing up in the new subscription page

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#44362]
# Problem

Right now if you add a card to your existing subscription via `https://dev.new.expensify.com:8082/settings/subscription/add-payment-card` it'll not show anything. There are multiple issues here causing this, but they are small enough to be combined into this one use case.

The first problem is explained in [this slack thread](https://expensify.slack.com/archives/C03TQ48KC/p1719266461741339). Basically we are not properly initializing the `fundList` in the Onyx db on the client. We need to fix that.

The second problem is that after [this](https://github.com/Expensify/App/issues/43136) was completed we never updated [App's code](https://github.com/Expensify/App/blob/d7d7739f3b3e6862411f29dc6c8c4b0362b459ff/src/pages/settings/Subscription/CardSection/CardSection.tsx#L26) to make use of the new format of the data, which means it doesn't show the default card.

# Solution

Fix both of the described problems above and make a newly added payment card show up in the UI.

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by blimpich** [comment]
Web-PR is in review, App PR is on hold until Web-PR is merged and deployed

**Comment by blimpich** [comment]
Web PR is merged, waiting deploy.

App PR is in review, waiting approval and also waiting web changes to be deployed.

**Comment by blimpich** [comment]
Web PR was [deployed to staging](https://github.com/Expensify/Web-Expensify/pull/42493#issuecomment-2190014388), waiting deploy to production

**Comment by trjExpensify** [comment]
App PR has merged: https://github.com/Expensify/App/pull/44361

Adding labels to get a BZ assigned, and @brunovjk as the C+ reviewer.

**Comment by blimpich** [comment]
This is done.

**Comment by pac-guerreiro** [comment]
Hey, this line of code was missed on the @blimpich PR - https://github.com/Expensify/App/blob/main/src/libs/SubscriptionUtils.ts#L206

Not his fault, this one was sneaky 😅 

The specific line of code doesn't cause the error reported in this issue but it will not trigger card expired related UI.

I can create a PR for this if you want 😄

**Comment by blimpich** [comment]
Ah, thank you for catching that @pac-guerreiro! I'll make a quick issue/PR for it right now 👍

**Comment by blimpich** [comment]
Also no regression tests should be needed for this issue. @abekkala I think we need to pay @brunovjk for reviewing this PR?

**Comment by blimpich** [comment]
Yes $250

**Comment by abekkala** [comment]
@brunovjk [offer](https://www.upwork.com/nx/wm/offer/103236481) sent!

**Comment by brunovjk** [comment]
thank you all :D

**Comment by abekkala** [comment]
@brunovjk payment sent and contract ended - thank you! 🎉
