### ISSUE TITLE
Workspace - Does not detect the expense category after turning on and off in the policy

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44377]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.0.8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/43869
**Email or phone of affected tester (no customers):** applausetester+az090524@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Prerequsites:
1. A workspace created
2. Expenses submited in the workspace

Steps:
1. Open the new Search page
2. Verify the information of the expenses in the workspace
3. Open the workspace
4. Enable Taxes and Tags options
5. Verify that the information of the expenses are correct
6. Go back to the workspace
7. Disable Categories, Taxes and Tags options
8. Go back to the information of the expense and verify that is an error message in the "Category"
9. Go to the workspace, enable "Categories"
10. Tap on the Categories, select all the categories and with the menu in the header Enable all
11. Go back to the expense in the new Search page

## Expected Result:
The error of the Category should not longer be presented

## Actual Result:
The error is still present even though the categories are already active

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0460de11-26af-457c-a6e2-be6dbfc48e30

https://github.com/Expensify/App/assets/115492554/ca2a0f4e-160d-4837-b1f9-891fb554c188

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by adelekennedy** [comment]
I somehow missed this one 😮‍💨

**Comment by adelekennedy** [comment]
i can't reproduce this one - and we're on such a later version that I think we're safe to close for now
