### ISSUE TITLE
[HOLD for payment 2024-08-19] Investigate improvements of the react-compiler 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44384]
We recently added react-compiler to the codebase; however, a healthcheck shows that only 937 out of 1235 files are actually compiled.

We need to understand why other ~300 components can not be compiled. At the moment we think that it could be:
- because they are very complex for the compiler
- break rules of the React
- already optimized very well, so compiler can skip them

To figure out an exact reason we need to have verbose logging in the healthcheck. There is several PRs:
- https://github.com/facebook/react/pull/29080
- https://github.com/facebook/react/pull/29851
We can apply the patch package locally or wait until one of these PRs is merged and a new version is published.

**Comment by kirillzyusko** [comment]
I can work on this 👀

**Comment by mountiny** [comment]
@kirillzyusko Any updates on this one?

**Comment by kirillzyusko** [comment]
@mountiny I think it can be closed because https://github.com/Expensify/App/pull/44460 was merged 👀

**Comment by mountiny** [comment]
Thanks! gonna keep it open now for a bit as we got the second pr

**Comment by mountiny** [comment]
@kirillzyusko anything else to explore for this task?

**Comment by kirillzyusko** [comment]
@mountiny I think no 🙂

**Comment by mountiny** [comment]
thank you
