### ISSUE TITLE
[HOLD for payment 2024-07-10] [BUG] Staging web fails to load, shows 'TypeError: Cannot use 'in' operator to search for 'whisperedTo' in []' error

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#44392]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**  
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719242232563149

## Action Performed:
Break down in numbered steps 

Open staging.new.expensify.com 
Load screen shows

## Expected Result:
Describe what you think should've happened

The UI loads after the load screen

## Actual Result:
Describe what actually happened

The load screen never disappears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

No

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad / @muttmuure</details>

**Comment by roryabraham** [comment]
We were discussing in slack that only @muttmuure seems to be able to reproduce, so maybe NAB. Next step: I think we really need to figure out which action has originalMessage as an array

**Comment by CortneyOfstad** [comment]
No payment is needed so going to close 👍
