### ISSUE TITLE
[Report Fields] Create OpenPolicyReportFieldsPage read command

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44408]
[Main tracking issue].(https://github.com/Expensify/Expensify/issues/365155)

[Design doc link](https://docs.google.com/document/d/10b7pTVvgpB6_O8sRTKaCzZEVM3Ba6hxnIwyyQSSXCLY/edit).

Implement a new read command `OpenPolicyReportFieldsPage` that will load the up-to-date report fields information.

**Comment by RachCHopkins** [comment]
@mountiny I see this is already added to Wave Control and has the Internal label. Is there anything that I need to do here?

**Comment by mountiny** [comment]
No and this is already completed so closing, thank you!
