### ISSUE TITLE
[$250] [HOLD payment 2024-08-09] [CRITICAL] [Guided setup] The onboarding flow can be dismissed by navigating to different route

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44401]
### Problem

When new users sign up, they are presented with an onboarding flow. This flow is crucial in the user's onboarding journey and aims to set them up for success using the app. It also provides useful information for us. We need to ensure that every new user completes the onboarding flow.

However, the user is able to navigate to a different route in the app, either by going back into the browser or changing the URL directly to any other in-app URL and the modal is not shown again.  

### Solution

Find a generic navigation solution that will check the user's onboarding NVP value and whether the `hasCompletedGuidedSetupFlow` property is set to false, in which case we should present them with the modal.

Note that if its existing user is coming from oldDot, the onboarding NVP will be an empty array. So we only want to show the modal when the `onboarding.hasCompletedGuidedSetupFlow === false`

That is, however, true for any URL or deep link; if they go back in the browser, they should be re-navigated to the onboarding flow until it is completed. It's technically a blocking pattern for them.

cc @adamgrzybowski @WojtekBoman @kosmydel 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174de33b05a0967f8</li>
        <li>Upwork Job ID: 1821685945045066052</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by mountiny** [comment]
Not looking for proposals really, would like to get the navigation team to find the best, performant and intuitive solution for this

**Comment by Kicu** [comment]
FYI update: This is being worked on by @adamgrzybowski and @filip-solecki and I have also chimed in a bit.
However for the past 2 days we had an unusual amount of navigation related bugs and regressions so its taking more time.

**Comment by Kicu** [comment]
@allgandalf can you please share a link to which PR, so we can understand what's been done there?

**Comment by Kicu** [comment]
@allgandalf Im not sure we're talking about the same issue. No we're not facing a problem with tab navigation. This is an issue related to onboarding and that it can be dismissed.
Neither of the tow PRs seem to be related to this issue? Also focus trap is quite old at this point

**Comment by Kicu** [comment]
Sorry I don't really understand what want from me. Let's keep the discussion on this issue relevant to this issue I just gave a brief update that we're working on it.

**Comment by adamgrzybowski** [comment]
@mountiny we should have a draft today

**Comment by adamgrzybowski** [comment]
It's a bit tricky, but our solution seems to work so far

**Comment by adamgrzybowski** [comment]
@mountiny we have a draft PR [here](https://github.com/Expensify/App/pull/44536). We have some issue with redirecting when the user types RHP route in the URL bar but besides that it works quite well. We will work on that tomorrow. BTW We "hacked" the browser back button so the user have to complete the flow but maybe it is worth to display some kind a message to explain why the back button is blocked? What do you think?

**Comment by mountiny** [comment]
@adamgrzybowski great! thank you! 

Yeah there should be an error on the modal shown. When you click outside of the modal now, we show it:
<img width="1664" alt="image" src="https://github.com/Expensify/App/assets/36083550/cb90d32c-1d07-4212-aedf-9bea6e92508a">

Can we show that too in this case?

**Comment by filip-solecki** [comment]
@mountiny I don't know if this is proper message cause user can select something and then click back button. We cannot easily check if user select something. What do you think about some generic message like: `Finish onboarding so you can use the app` or similar?

**Comment by adamgrzybowski** [comment]
@mountiny I haven't found a fix for the broken routes today. I will continue on Monday.

**Comment by adamgrzybowski** [comment]
Hey, @mountiny @allgandalf it looks like the alternative solution I found is finally working well 😄 I updated the draft PR. It would be great if you could test it and see if it meets the expectations. 

BTW There is still a question about the translation of the message and the actual message.

**Comment by mountiny** [comment]
Asked in [Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1719948260782919) for confirmation

**Comment by mountiny** [comment]
Seems like there was another edge case found https://github.com/Expensify/App/pull/45327#issuecomment-2243108553 and @WojtekBoman is looking into it

**Comment by mountiny** [comment]
This is ready for payment $250 to @allgandalf

**Comment by mountiny** [comment]
@anmurali ready to be paid

**Comment by anmurali** [comment]
@allgandalf - https://www.upwork.com/nx/wm/offer/103712472

**Comment by anmurali** [comment]
Paid.
