### ISSUE TITLE
[Payment card / Subscription] Correct amounts  not showing on "Add payment card"

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#44417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.2-0
**Reproducible in staging?:** Staging
**Reproducible in production?:** No - You must navigate to https://staging.new.expensify.com/settings/subscription
**If this was caught during regression testing, add the test name, ID and link from TestRail:** NA
**Email or phone of affected tester (no customers):** wardmi@tcd.ie
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** mitch@expensify.com
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1719350462833819

## Action Performed:

As a workspace owner with Pay-per-use and/or a Control plan that also has no payment card saved;

1. Go to https://staging.new.expensify.com/settings/subscription
2. Click "Add payment card"

## Expected Result:

Depending on whether you have Annual or Pay-per-use and whether you are on Collect or Control we will show this message above the “Add payment card” button:

- If an Annual subscription is enabled, which it is by default, we show this for Collect: “From $5/active member with the Expensify Card, $10/active member without the Expensify Card.”
- If Pay-per-use is enabled we show this for Collect: “From $10/active member with the Expensify Card, $20/active member without the Expensify Card.”
- If an Annual subscription is enabled, which it is by default, we show this for Control: “From $9/active member with the Expensify Card, $18/active member without the Expensify Card.”
- If Pay-per-use is enabled we show this for Control: “From $18/active member with the Expensify Card, $36/active member without the Expensify Card.”

## Actual Result:

The user is on pay-per-use on Control but the text above "Add payment card" reads "From $5/active member with the Expensify Card, $10/active member without the Expensify Card." when it should read “From $18/active member with the Expensify Card, $36/active member without the Expensify Card.”

## Workaround:

Ignore

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/36425901/7475b8f1-61c7-4da7-a4ab-421cd60a6cef)

![image](https://github.com/Expensify/App/assets/36425901/957ae6d5-f2d7-47b1-8fee-806a796f6d6e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by trjExpensify** [comment]
@MitchExpensify apparently this will be fixed here: https://github.com/Expensify/App/pull/43572/files#diff-d33a8833443831664318c3ec9ea300090935e1aed9ace8b7642ee38a65b026d7R102

**Comment by MitchExpensify** [comment]
Oh nice! Lets be safe and keep this open as a reminder to test once that's on staging

**Comment by trjExpensify** [comment]
https://github.com/Expensify/App/pull/43572 is on staging, so you can retest this.

**Comment by trjExpensify** [comment]
Bump @MitchExpensify for the retest before closing this issue.

**Comment by MitchExpensify** [comment]
Tested and this is working
