### ISSUE TITLE
iOS - Search - App redirects to the report several times when tapping on header subtitle

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44422]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Submit a manual expense to any user with no unsettled expense.
3. Go to Search.
4. Open the transaction thread created in Step 2.
5. Tap on the header subtitle.

## Expected Result:
App will redirect to the report once.

## Actual Result:
App redirects to the report several times when tapping on header subtitle.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/68fd4a32-37fe-4995-b68e-24296950d61b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@sakluger FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by sakluger** [comment]
Yes, this is wave-collect. I'm not ready to remove the Deploy Blocker label yet, I'll raise in Slack.

**Comment by sakluger** [comment]
Raised in #wave-collect: https://expensify.slack.com/archives/C036QM0SLJK/p1719417413800179

**Comment by yuwenmemon** [comment]
Fixed with https://github.com/Expensify/App/pull/44444

**Comment by sakluger** [comment]
I think that payment is being handled in https://github.com/Expensify/App/issues/44423 or https://github.com/Expensify/App/issues/44433, so no additional payment is required here. We can close the issue once the PR is deployed to prod. Moving to daily.

**Comment by sakluger** [comment]
The PR is still on staging, so it will likely be deployed to prod on Monday.

**Comment by sakluger** [comment]
Still on staging.

**Comment by sakluger** [comment]
Still on staging.

**Comment by sakluger** [comment]
On prod! All done here.
