### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [Search v1] - Workspace switcher on Search is not synchronized with workspace switcher in Inbox

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44433]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Account has at least one workspace.

1. Go to staging.new.expensify.com
2. Open workspace switcher.
3. Select any workspace other than Expensify.
4. Go to Search.
5. Open the workspace switcher on Search.

## Expected Result:
The workspace switcher on Search should be synchronized with that on Inbox.

## Actual Result:
The workspace switcher on Search shows "Expensify", but when opened, it shows the same selected workspace in Inbox.

Also, on Search page, the breadcrumbs always reset to Expensify when selecting a different Search category.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7cc29c1c-2fce-4208-b704-a6365b764771

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01555554fcd588e68c</li>
        <li>Upwork Job ID: 1805912913347680498</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 102886879</li>
<li>allgandalf | Contributor | 102905430</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by izarutskaya** [comment]
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by nyomanjyotisa** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace switcher on Search is not synchronized with workspace switcher in Inbox

### What is the root cause of that problem?
We pass `policyIDs` to the `activeWorkspaceID`, and in this case policyIDs is undefined
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/pages/Search/SearchPageBottomTab.tsx#L63

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/pages/Search/SearchPageBottomTab.tsx#L62-L66
Change the code above to use activeWorkspaceID from useActiveWorkspaceFromNavigationState() if policyIDs is undefined
```
               <TopBar
                    activeWorkspaceID={policyIDs ?? activeWorkspaceID}
                    breadcrumbLabel='woi1'
                    shouldDisplaySearch={false}
                />
```

### What alternative solutions did you explore? (Optional)
Change the policyIDs with activeWorkspaceID from useActiveWorkspaceFromNavigationState()
```
               <TopBar
                    activeWorkspaceID={activeWorkspaceID}
                    breadcrumbLabel='woi1'
                    shouldDisplaySearch={false}
                />
```

**Comment by grgia** [comment]
Adding External Label. Looks like the correct workspace is still selected and it's just a header display problem. I demoted from deploy blockers

**Comment by bernhardoj** [comment]
Same root cause as https://github.com/Expensify/App/issues/44423

**Comment by WojtekBoman** [comment]
Hi! I'm working on it as I'm the author of the offending PR

**Comment by luacmartins** [comment]
Gonna assign myself to this one as well, since it's related to the Search project

**Comment by luacmartins** [comment]
We can complete the items in the checklist, but we can skip the test steps, since we'll add those as part of the project wrap up.

**Comment by luacmartins** [comment]
Just missing payment here

**Comment by grgia** [comment]
@anmurali bump on payment

**Comment by anmurali** [comment]
Paid.
