### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [Search v1] "Description" is clickable but does not sort the expenses

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44431]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/44181
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Account has no any expenses (new account).

1. Go to staging.new.expensify.com
2. Submit two expenses to any user with different description and no merchant.
3. Go to Search.
4. Wait for two transactions to show up.
5. Click on the description.

## Expected Result:
The expenses can be sorted by description, since description is clickable.

## Actual Result:
The expenses cannot be sorted by description, even though description is clickable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/17c66267-233d-4acd-947d-ffaa6686f509

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3c62ae3fec778ff</li>
        <li>Upwork Job ID: 1805898588572242732</li>
        <li>Last Price Increase: 2024-06-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by izarutskaya** [comment]
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by Julesssss** [comment]
Based on this [issue](https://github.com/Expensify/App/issues/44180) which has only just been merged, this sounds like an edge case when we don't have any merchant details. I am removing the blocker labels and have raised the bug in both the issue and the PR in order to help with the follow-up fix: 

- https://github.com/Expensify/App/pull/44181
- https://github.com/Expensify/App/issues/44180

**Comment by luacmartins** [comment]
We already have description available. We should just extend the sorting functionality to allow for nested objects.

**Comment by luacmartins** [comment]
PR [here](https://github.com/Expensify/App/pull/44472)

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/42248
- The offending PR has been commented on: https://github.com/Expensify/App/pull/42248#discussion_r1667707950
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by JmillsExpensify** [comment]
Payment summary above is accurate. $250 to @s77rt for PR review. I assume that you'll be submitting this via New Expensify?

**Comment by s77rt** [comment]
@JmillsExpensify Yes. Just did!

**Comment by JmillsExpensify** [comment]
Going to close this then! I need a payment summary from Matt Allen, and asked him via DM.

**Comment by mallenexpensify** [comment]
Contributor+: @s77rt due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
