### ISSUE TITLE
Web - Group chat - Console error after changing group member role

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44449]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat
4. Click on the group header > Members
5. Click on any member
6. Click Role
7. Select a different role

## Expected Result:
Console error will not show up

## Actual Result:
Console error shows up after changing group member role

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/74d6ae6f-ed89-4839-8ddf-a386e3521de0

[logs (2).txt](https://github.com/user-attachments/files/15988311/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
BE problem, UpdateGroupChatMemberRoles response returns an empty array.
<img width="505" alt="image" src="https://github.com/Expensify/App/assets/50919443/057a16d4-85de-4583-afe8-91efe3d39d76">

**Comment by garrettmknight** [comment]
Thanks for giving it a look @devguest07 / @bernhardoj

**Comment by garrettmknight** [comment]
Dropping to weekly, it'll get flagged in the vip-vsp round up.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer.

**Comment by garrettmknight** [comment]
@bfitzexpensify I'm going OOO until August 3rd, will pick this back up when I'm back around if this hasn't been picked up/finished.

**Comment by bfitzexpensify** [comment]
Still waiting for a volunteer.

**Comment by garrettmknight** [comment]
Just tested and I'm no longer seeing this error. Closing!
