### ISSUE TITLE
Concierge - No Book a call option in 3 dot menu after finish onboarding

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44278
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with a new account using an email alias
3. On the onboarding modal select "Manage my team's expenses"
4. Finish the on boarding flow
5. Open the Concierge chat
6. Click the 3 dots in the top right corner

## Expected Result:
The "Book a call" option is present

## Actual Result:
The "Book a call" option is not displayed. Issue is not reproducible if using a random non-existing email without aliasing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6f1de487-356b-42a3-9c4e-85c9a84d0b8e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
This is expected, you are not assigned a real guide when you use email with + so there would be no guide.

you have to use email without + in it
