### ISSUE TITLE
LHN - Thread does not stay bold in LHN after marking message unread in thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44440]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4675159
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in
2. Open a thread with several messages from LHN or create one
3. Mark a message as unread
4. Navigate to the LHN

## Expected Result:
The thread is bold in the LHN until it is opened again

## Actual Result:
The thread is displayed bold briefly and gets read

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/cc68f6ae-f331-477f-80ec-c4e5e687b2bd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by izarutskaya** [comment]
@kevinksullivan I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by mountiny** [comment]
I have tested this on latest 9.0.2-4 and its not repro anymore.

**Comment by mountiny** [comment]
https://github.com/Expensify/App/assets/36083550/18a7daae-bf4f-4cc4-a275-0a2600b0407b

Asked the QA team to retest but removing the blocker label https://expensify.slack.com/archives/C9YU7BX5M/p1719508587392919

**Comment by kavimuru** [comment]
Issue is fixed. 

https://github.com/Expensify/App/assets/43996225/21e114e1-ddfa-4871-a0c4-0ca2374f0405

**Comment by mountiny** [comment]
Thanks!
