### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Distance - Error is not dismissed after entering valid waypoints

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4671219
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Disable internet connection
2. Go to FAB > Submit expense
3. Select the Distance option
4. Enter an invalid start location
5. Enter an invalid finish location
6. Submit the expense to a workspace
7. Enable the internet connection
8. Wait for the error on the request to appear
9. Click on the request
10. Click on the address input field and type valid waypoints on the start and finish locations respectively.
11. Save the new addresses

## Expected Result:
The error is removed and the map updates to the new addresses and displays correctly in the map thumbnail

## Actual Result:
The error persists, the map thumbnail is empty and the new addresses are displayed only when the thumbnail is clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dea04afa-a370-48bd-884f-31ea69dea62a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0138e762430a2e3f57</li>
        <li>Upwork Job ID: 1810948702952984302</li>
        <li>Last Price Increase: 2024-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103283503</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by dylanexpensify** [comment]
@lanitochka17 cannot reproduce, can you confirm this is still occurring?

**Comment by lanitochka17** [comment]
Issue is still reproducible

https://github.com/Expensify/App/assets/78819774/4cd81b4e-7d27-403d-ac76-995bcd49dc08

**Comment by dylanexpensify** [comment]
Moving external!

**Comment by dylanexpensify** [comment]
Thank you, Olly!

**Comment by neil-marcellini** [comment]
> Yeah I suppose it is congruent with the other behaviour in the app. Ok let's go with @dominictb's [proposal](https://github.com/Expensify/App/issues/44459#issuecomment-2219926478). 🎀👀🎀 C+ reviewed

I agree, great plan! Hiring. For context, we recently fixed [cleaning up errored distance expenses](https://github.com/Expensify/App/issues/42950) on the frontend. Maybe there were some mistakes in there that we could smooth out here too.

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by JmillsExpensify** [comment]
@dylanexpensify i need a payment summary

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @dominictb $250
- Contributor+: @Ollyws $250

Please apply/request!

**Comment by dylanexpensify** [comment]
Done!
