### ISSUE TITLE
[HOLD for payment 2024-07-10]  Expense - "Hold" banner appears on top briefly after deleting the expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44454]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4671017
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat > Manual.
3. Submit a manual expense to any user that has no unsettled expense (important)
4. Go to transaction thread
5. Click 3-dot menu > Delete expense
6. Delete the expense
7. Note that the "Hold" banner appears on top briefly

## Expected Result:
"Hold" banner will not show up when deleting the expense

## Actual Result:
"Hold" banner appears on top briefly after deleting the expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/99642a91-c8ef-4620-bc42-25825bcf685d

<img width="1440" alt="15 48" src="https://github.com/Expensify/App/assets/78819774/0b0fc254-97fb-49e8-99c7-1d33c5b14e42">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rlinoz** [comment]
No need to block on this.

**Comment by rlinoz** [comment]
No payment due, closing.
