### ISSUE TITLE
[$250] Tags settings – Tag appears with delay in LHN if enable it second time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44452]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new workspace
4. Navigate to the workspace editor
5. Navigate to "More Features"
6. Enable the tags toggle
7. Disable the tags toggle
8. Enable the tags toggle again

## Expected Result:
Tag appears immediately if enable it second time

## Actual Result:
Tag appears with delay if enable it second time. The same with taxes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ace972cf-24c1-4405-a2a9-05dfb54c6cb5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee7b141139667b3f</li>
        <li>Upwork Job ID: 1806617975628334927</li>
        <li>Last Price Increase: 2024-07-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag appears with delay if enable it second time

### What is the root cause of that problem?
This issue came from the **pendingFields** case.

### What changes do you think we should make in order to solve the problem?
We need to follow the `EnablePolicyTags` or `EnablePolicyTaxes` API to understand its behavior in case of **pendingFields** and optimize it on the backend side. When I checked it again, on 29/06 I was able to reproduce this issue, but as of 01/07, I am unable to reproduce it.

### What alternative solutions did you explore? (Optional)

**Comment by greg-schroeder** [comment]
Proposal review underway

**Comment by greg-schroeder** [comment]
@eVoloshchak will take a look soon

**Comment by eVoloshchak** [comment]
Can confirm @huult's [observation](https://github.com/Expensify/App/issues/44452#issuecomment-2198625860), the bug isn't reproducible for me either

@lanitochka17, could you please re-check is this is still reproducible?

**Comment by greg-schroeder** [comment]
Added `retest-weekly`

**Comment by greg-schroeder** [comment]
Pinged QA for a retest

**Comment by lanitochka17** [comment]
Issue is not reproducible now 

https://github.com/Expensify/App/assets/78819774/c65278ad-42c0-4768-b7e1-63c53291e33a

**Comment by greg-schroeder** [comment]
All right I'm going to close for now, please reopen if you disagree
