### ISSUE TITLE
[$250] Room - mWeb - Inconsistency in displaying search results while entering country code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44464]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.2.9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y  
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4672280
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- start chat
3. Enter a country code +91 and tap add to group from results shown
4. Select any other user and tap next
5. Tap create group
6. Navigate to LHN
7. Tap fab -- start chat
8. Enter a country code +36

## Expected Result:
There must not be Inconsistency in displaying search results while entering different country code

## Actual Result:
On entering country code +36 results are not shown but for +91 results are shown. Inconsistency in displaying search results while entering different country code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/532d5371-7f3b-41cc-98eb-aed8c18e7c27

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acfa1a904dd69ed7</li>
        <li>Upwork Job ID: 1806802093805556803</li>
        <li>Last Price Increase: 2024-07-12</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment]
This isn't overdue. It was just triaged.

**Comment by johncschuster** [comment]
@mananjadhav can you please review the above proposal?

**Comment by mananjadhav** [comment]
I'll review the proposals today/tomorrow.

**Comment by mananjadhav** [comment]
I am not quite sure I understand if it's BE. I'll verify this and the proposal.

**Comment by mananjadhav** [comment]
I don't think we should be fixing this from the frontend. 

My hunch is +91 is a valid phone as per `E.164` format, so someone must've invited a user with just +91. I am inclined to close this but if we would like to triage this internally for BE issue, we could do that.

**Comment by johncschuster** [comment]
Hm... I thought the `Internal` label would assign an Expensify engineer 🤔

**Comment by johncschuster** [comment]
Ah, the Internal label will no longer auto-assign issues. I'll need to bring this to the respective project room. I will do that tomorrow.

**Comment by johncschuster** [comment]
It looks like Search is part of #wave-collect. I've added it to the project now.

**Comment by johncschuster** [comment]
[Raising in Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1721337548644069)

**Comment by mananjadhav** [comment]
@johncschuster Any updates here? I can see we've mentioned it's chat bugs. do we have anyone on the internal picking this up?

**Comment by johncschuster** [comment]
Thanks for checking in, @mananjadhav! We've generally deprioritized the #vip-vsb project. I'm getting a priority check on this specific issue and will update shortly.

**Comment by johncschuster** [comment]
Closing this for now
