### ISSUE TITLE
[$250] Chat - ND freeze/crash after actions like Submit/Approve/Unapprove with report in OD

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44467]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4671320
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open 2 tabs in browser - 1st with OD and 2nd with ND
2. Login with one expensifail account in OD and ND
3. Create report in OD and add expense
4. Submit / approve / unapproved this report
5. After each action select tab with ND and try to select another chat in LHN

## Expected Result:
User can switch to another chat in ND. Application works without any issues, freezes and crashes

## Actual Result:
ND web/desktop application freezes after one of the actions like Submit / Approve / Unapproved with report in the same account in OD. Mobile iOS / Android app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/06e8384c-eddf-4f1b-ae76-f43d5969fc39

https://github.com/Expensify/App/assets/78819774/9cd94901-29a9-43ec-9da4-1279e9919041

[logs (2).txt](https://github.com/user-attachments/files/15990948/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0128dd03f16e4da1d9</li>
        <li>Upwork Job ID: 1806401557448812064</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by slafortune** [comment]
Waiting on proposals

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by slafortune** [comment]
No longer reproduceable

**Comment by lanitochka17** [comment]
Issue is still reproducible 

https://github.com/user-attachments/assets/ed50b469-ac74-4219-9b6a-d7a7feed40b3

**Comment by slafortune** [comment]
@mvtglobally @lanitochka17 are the same steps being followed? Should be have this retested again?

**Comment by lanitochka17** [comment]
Sorry for confusion, issue is not reproducible right now

https://github.com/user-attachments/assets/691fdace-a8e1-4239-9ac2-cdc08b9934a4

**Comment by slafortune** [comment]
Thanks everyone - closing 👍
