### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [$250] [HOLD 36648] Wallet - Idology questions flow does not start after entering bank account details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44462]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4673461
**Email or phone of affected tester (no customers):** applausetester+062524dr002@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open app or go to staging.new.expensify.com
2. Log in with any account without a wallet configured
3. Go to Settings > Wallet
4. Click on 'Enable wallet'
5. Follow the bank account flow until the final 'Confirm' page (using Bank: Chase / Account: 1111 / First name: Alberta / Last name: Bobbeth / SSN: 3333)
6. Tap 'Confirm' button

## Expected Result:
Idology questions flow has started

## Actual Result:
Nothing happens after pressing the 'Confirm' button. Idology questions flow does not start

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e6b6fcfb-8732-44e1-8f79-1a2251d4896b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014deaa2c3f332d2e4</li>
        <li>Upwork Job ID: 1806785838003619663</li>
        <li>Last Price Increase: 2024-06-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@thienlnam @OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by thienlnam** [comment]
It seems like this failed because of a non-matching SSN ([logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228998f6b9288c5079-ORD%22)+AND+timestamp:[2024-06-25T23:08:36.539Z+TO+2024-06-26T01:08:36.539Z]&index=logs_expensify-029099))

I wonder if this was updated for our test bank account recently but it doesn't seem to be from any recent changes

**Comment by thienlnam** [comment]
Posted here, https://expensify.slack.com/archives/C03SSAQ7P/p1719415968231039 but don't think this is a result of changes made

**Comment by thienlnam** [comment]
Actually, after some confirmation in the [thread](https://expensify.slack.com/archives/C03SSAQ7P/p1719497211022799?thread_ts=1719415968.231039&cid=C03SSAQ7P) there's a bug here and it seems to be that the KBA questions do not show up after the initial failure and resubmission

**Comment by OfstadC** [comment]
@Pujan92 Any update here?

**Comment by OfstadC** [comment]
@Pujan92 Please provide an update by EOD. Thanks!

**Comment by Pujan92** [comment]
Sorry @OfstadC, The PR merged and the code in the production. I think bcoz of Hold the automation isn't worked for this issue.

**Comment by OfstadC** [comment]
Thanks @Pujan92 ! Could you complete the BZ checklist when you have a chance? Thanks! 😃

**Comment by Pujan92** [comment]
@OfstadC I believe that will be handled in the parent issue https://github.com/Expensify/App/issues/36648

**Comment by OfstadC** [comment]
Ah okay! 😅 Thanks @Pujan92 !

**Comment by OfstadC** [comment]
Closing this out - 

No payment needed per:

> For reference, here are some details about the assignees on this issue:
> 
> @Pujan92 does not require payment (Contractor)
> @koko57 does not require payment (Contractor)


And checklist should be covered [here](https://github.com/Expensify/App/issues/36648)
