### ISSUE TITLE
[$125] Prevent starting a chat with domain emails, e.g. `+@domain.com`

### ISSUE THREAD

**Issue by youssef-lr** [Expensify/App#44485]
Coming from https://expensify.slack.com/archives/C03TQ48KC/p1719398755192969, let's show "No results found" when someone searches for a domain email such as `+@expensify.com`.

<img width="1440" alt="Screenshot 2024-06-26 at 17 34 43" src="https://github.com/Expensify/App/assets/9680864/643a269f-a925-485a-8650-2769cf4b4343">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7d57d27f9173c70</li>
        <li>Upwork Job ID: 1806003279051571338</li>
        <li>Last Price Increase: 2024-06-26</li>
    </ul>
</details>

**Comment by nkdengineer** [comment]
@youssef-lr This is dupe of https://github.com/Expensify/App/issues/44429, we can handle this issue there too

**Comment by youssef-lr** [comment]
Thanks @nkdengineer, yeah let's do that.
