### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Search v1] Reports are not sorted by date

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#44502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Pre-requisite: account with lots of money requests

1. Open the Search page and go to `Shared`
2. Notice that reports are not sorted by date

## Expected Result:
Reports should be sorted by descending date

## Actual Result:
Report order is random

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by luacmartins** [comment]
PR up but on hold for API change

**Comment by kevinksullivan** [comment]
@shubham1206agra please complete the checklist above

**Comment by kevinksullivan** [comment]
Bump on the checklist @shubham1206agra , thanks

**Comment by kevinksullivan** [comment]
@shubham1206agra bump on the checklist, thanks!

**Comment by kevinksullivan** [comment]
Also automation failed, so created a new job

https://www.upwork.com/jobs/~01a23a5bd3fd4574ed

**Comment by kevinksullivan** [comment]
all set
