### ISSUE TITLE
Animation glitch when navigating to room setting page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44510]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719428439177839

## Action Performed:

1. Open any room.
2. Tap on header
3. Tap on settings and Tap back and then again tap on settings
4. Repeat step 3 few times if not reproducable first time
5. 

## Expected Result:
There should be no animation glitch while navigation
## Actual Result:
Closing Animation glitches
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/c0daaa20-4d2d-49e3-b1f2-9277258d07cd

https://github.com/Expensify/App/assets/38435837/022ffa8c-e140-4d07-91e6-2f4206698f81

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
Closing in favor of that.
