### ISSUE TITLE
[$250] Chat - Badge 'New messages' disappears after returning to the chat from thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4676291
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open iOS/iPad or Android App
2. Login with any account
3. Got to any chat with long history
4. Mark the latest message as unread
5. Scroll up the chat history, long-tap on any message and tap to 'Reply in thread'
6. Go back from thread to the main chat history

## Expected Result:
The badge 'New Messages' is present at the top of the screen

## Actual Result:
The badge 'New messages' disappears after returning to the chat history from the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native/ iPad
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ed9f937b-0224-4f8e-a8ab-dadfe3e418a3

https://github.com/Expensify/App/assets/115492554/b24c9396-891a-4ac0-8889-4a006c44a9eb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01701df429333bf5ee</li>
        <li>Upwork Job ID: 1806345990119579428</li>
        <li>Last Price Increase: 2024-07-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by mountiny** [comment]
I think this is kinda fixed on the latest 9.0.2-5. You can see the badge does not show up immediately but the unread line is there and as you scroll the badge shows up.

https://github.com/Expensify/App/assets/36083550/f67e2827-b2bf-4247-a447-1145b36648b2

I think we can demote and retest and see if we need to update the OP @kavimuru @izarutskaya

**Comment by zanyrenney** [comment]
Nice, thanks @mountiny <3

**Comment by zanyrenney** [comment]
retesting!

**Comment by zanyrenney** [comment]
Can no longer repro, given then comment above from Vit, i think we should be good to close this one.
