### ISSUE TITLE
ERR_NAME_NOT_RESOLVED console error when navigating to or refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44543]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log out
2. Open Chrome console
3. Navigate to https://staging.new.expensify.com/
4. Refresh the page
5. Log in with a Gmail account
6. Navigate to https://staging.new.expensify.com/
7. Refresh the page

## Expected Result:
I should be able to navigate without any console errors

## Actual Result:
"ERR_NAME_NOT_RESOLVED" console error when navigating to or refreshing the page. It happens on the login screen when the user is logged out, and also when the user is logged in. If the user is logged in, an additional "Refused to execute script" error appears in the console

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0c042d8c-b03f-4184-9925-5cf3369ad89c

[logs (2).txt](https://github.com/user-attachments/files/16014573/logs.2.txt)

[logs (2).txt](https://github.com/user-attachments/files/16014585/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment]
I don't think this is a big deal, it's not affecting anyone's usage of New.Dot.
