### ISSUE TITLE
[HelpDot] Migrate dual platform to one directory

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#44540]
### Context
Slack - [HERE](https://expensify.slack.com/archives/C02QSAC6BJ8/p1719417996108129)

### Solution - WIP
Finish migrating dual platform setup to one directory

**Comment by rushatgabhane** [comment]
Update: Looks like both platforms will be split to different domains.

**Comment by francoisl** [comment]
Closing as discussed in https://expensify.slack.com/archives/C02NK2DQWUX/p1721959930871349
