### ISSUE TITLE
[$50] Typing football in the emoji picker shows some weird emojis

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44564]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719476576192849

## Action Performed:
1. Open app 
2. Go to any report
3. Click on the emoji picker
4. Enter "footb"
## Expected Result:
Should display football icon
## Actual Result:
Does not give correct result only when searching for "socc" gives the  correct emoji
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img src="https://github.com/Expensify/App/assets/38435837/5bacc2b6-ac46-4168-aaee-7f4e9b8a7e85" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/e028e7bd-341d-4027-aa10-f1166da1a397" width="40%" height="40%">

![Snip - (4) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/03c4bb25-e1ca-43a3-9087-902ceb0b7c79)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01282929ab196528f4</li>
        <li>Upwork Job ID: 1806396773191013443</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 102905277</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by abzokhattab** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Typing football in the emoji picker shows some weird emojis
### What is the root cause of that problem?

the keyword mapping of ball doesn't contain the word "football" https://github.com/Expensify/App/blob/82b76c1a36cf1a01b00c14510a5812a591e7f2fd/assets/emojis/en.ts#L3053-L3055
### What changes do you think we should make in order to solve the problem?
we need to add football and maybe soccer to the emoji above

**Comment by mountiny** [comment]
@fedirjh I can handle the review on this one

**Comment by mountiny** [comment]
Unassigned @abzokhattab. I was not aware we have this issue widespread on more emojis.

@Krishna2323 Can you get all the data in the correct order from Emojipedia and then use chatGPT to format it in the shape we need it? I feel like that should work and not take that long

**Comment by mountiny** [comment]
Discussing [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1719535732640359?thread_ts=1719334031.961109&cid=C01GTK53T8Q) btw

**Comment by bfitzexpensify** [comment]
Yes I think we can close in favour of https://github.com/Expensify/App/issues/42588, and handle all emoji in one issue.
