### ISSUE TITLE
[HOLD for payment 2024-07-23] [$250] [Search v1] Design updates to Search rows on mobile

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#44563]
We have a few simplifications we'd like to make for the mobile view of Search rows to help make the rows a bit more digestible and legible:
![CleanShot 2024-06-27 at 20 14 47@2x](https://github.com/Expensify/App/assets/2319350/930039ee-b280-4740-9598-1d54ba31d105)

1. Let's remove the tag from the bottom line under the merchant, and only show a Category if one is available
2. Let's remove the icon in front of Category
3. If no category exists, let's vertically center the Merchant line in the available space
4. If no Merchant exists, let's use the Description if it exists. If neither exists, do nothing and leave it blank

cc @JmillsExpensify @luacmartins @Expensify/design 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b532850f6d400dbe</li>
        <li>Upwork Job ID: 1806412035454885668</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 102915283</li>
<li>dominictb | Contributor | 102915284</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by luacmartins** [comment]
>BTW, should we apply the description fallback on web/desktop? If yes, do we need to change the merchant column name? @shawnborton @luacmartins

I'll let @shawnborton confirm this one since he's more on top of those discussions.

**Comment by shawnborton** [comment]
> BTW, should we apply the description fallback on web/desktop? If yes, do we need to change the merchant column name?

I think we decided no, since we plan to implement the dynamic columns - right @luacmartins ?

**Comment by luacmartins** [comment]
Yea, that makes sense!

**Comment by garrettmknight** [comment]
@luacmartins is this one ready to be paid out? I'm not 100% sure if there's anything else we're waiting on or if the automation just didn't run.

**Comment by luacmartins** [comment]
Yes, this is ready for payment

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @dominictb $250 paid via upwork
- Reviewer: @dukenv0307 $250 paid via upwork
