### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Compose box greyed out in offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44572]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-4
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719479861497379

## Action Performed:
1. Go to staging.new.expensify.com
2. Initiate a DM with any user
3. Go offline and observe compose box
## Expected Result:
Compose box not greyed out
## Actual Result:
Compose box greyed out
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/38435837/bcaa3c2f-c9d8-4739-ae29-4a37b3587639)

![Snip - (157) New Expensify](https://github.com/Expensify/App/assets/38435837/b5b92c77-dfb3-48ea-a164-77fd15d76ceb)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0d7df031f9e69ed</li>
        <li>Upwork Job ID: 1807915148857604784</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103099309</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by adelekennedy** [comment]
reproduced 


https://github.com/Expensify/App/assets/60450566/633334e4-e9bd-401b-acbb-14440199046b

**Comment by knarah** [comment]
Hi @adelekennedy, In the reproduced video, the compose box turns grey when it loses focus and then turns green again when focused while offline. I'm not sure what the bug is in this issue. Could you clarify?

**Comment by knarah** [comment]
Contributor details
Your Expensify account email: kimnarah@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ba397888562b9e78

**Comment by jayeshmangwani** [comment]
> If we do not want to grey out the composer in this case, use shouldDisableOpacity in

@dominictb Can you please confirm that after adding shouldDisableOpacity to OfflineWithFeedback, we are not encountering this issue https://github.com/Expensify/App/issues/16730#issue-1646797611 on Android again?

**Comment by jayeshmangwani** [comment]
>  I'm not sure what the bug is in this issue. Could you clarify

To reproduce the issue: first, send a message in the chat. Then, go offline and reply in the thread to the sent message. Observe the compose box; it will look like the screenshot below.

<img width="527" alt="Screenshot 2024-07-03 at 2 00 26 AM" src="https://github.com/Expensify/App/assets/35371050/65d37659-86de-4d0d-b14c-f07004fa0200">

Composer should not be greyed out; instead, it should look like the screenshot below.

<img width="525" alt="Screenshot 2024-07-03 at 2 00 38 AM" src="https://github.com/Expensify/App/assets/35371050/afb00544-9715-47e1-915a-3733679bfec2">

**Comment by jayeshmangwani** [comment]
@dominictb If we add the shouldDisableOpacity prop, it will disable the greyed-out effect for all newly created offline chats, which I think we don't want.

**Comment by iwiznia** [comment]
> So should we use shouldDisableOpacity props for the composer to disable the grey-out effect?

I think yes, because even if the report is not yet new, the composer box should be non greyed out... right @adelekennedy ?

**Comment by jayeshmangwani** [comment]
@adelekennedy We are not sure if we need to remove the composer greyed-out altogether for all the new reports created offline. Should we get consensus from the design team on this?

**Comment by shawnborton** [comment]
Yeah this feels like a bug to me. I don't know why the composer box would be grayed out - just the pending message should be grayed out.

**Comment by shawnborton** [comment]
Can we check if this was a regression from somewhere? I think this was working correctly for a long time, so this feels like something recently changed to break this.

**Comment by iwiznia** [comment]
Ah ok, still, not sure if that's a new bug or has always existed, since the chat needs to be new and not created in the server too.

**Comment by jayeshmangwani** [comment]
> or has always existed

I think it has always existed. I can see from the history of the ReportActionCompose file that the OfflineWithFeedback code has been there for the past year.

**Comment by jayeshmangwani** [comment]
> Can we check if this was a regression from somewhere? I think this was working correctly for a long time, so this feels like something recently changed to break this.

I have tested the two-month-old ad hoc build and can see the greyed-out composer for newly created chats when offline. Therefore, I believe this behavior has been present in our app for some time.

@shawnborton, should we proceed with removing the greyed-out effect on the composer for all newly created reports when offline?

**Comment by shawnborton** [comment]
I think that makes sense to me, yeah. Curious if @trjExpensify agrees though!

**Comment by iwiznia** [comment]
> should we proceed with removing the greyed-out effect on the composer for all newly created reports when offline?

Yeah, we should.

**Comment by jayeshmangwani** [comment]
> Yeah, we should.

Great! We can move forward with @dominictb's [Proposal](https://github.com/Expensify/App/issues/44572#issuecomment-2196312696) of adding the shouldDisableOpacity prop to OfflineWithFeedback.

🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment]
> I think that makes sense to me, yeah. Curious if @trjExpensify agrees though! 

Hundy p, agree! 💯

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/17405
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/17405#discussion_r1685676493
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


## Regression Test Proposal

1. Go to NewDot.
2. Initiate a DM with any user.
3. Go offline, then reply in the thread, and observe the compose box.
4. Verify that the compose box does not grey out.


Do we agree 👍 or 👎

**Comment by adelekennedy** [comment]
makes sense to me - @thienlnam to weigh in as well

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @dominictb (Upwork)
- [ ] Contributor+: $250 @jayeshmangwani (NewDot)

**Comment by adelekennedy** [comment]
https://github.com/Expensify/Expensify/issues/415255

**Comment by jayeshmangwani** [comment]
Requested $250

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani
