### ISSUE TITLE
[Awaiting Payment 20th August] [Held requests] Clean up the hold/unhold logic 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#44573]
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1719518155744889?thread_ts=1717504397.938539&cid=C036QM0SLJK), we're seeing some inconsistencies in the intended design for hold/unhold logic. For example, a member on a workspace can unhold their expense even if the approver put it on hold. 

@robertjchen @BartoszGrajdek let's go through this and make sure we clean up any inconsistencies. Any questions or further clarifiers necessary, let's align in the Slack thread. 

## Hold

**Expenses on expenseReports**
- Members can hold their own expenses.
- Approvers can hold expenses submitted to them.
- Admins can hold any expense on a workspace they’re an admin of.

**Expenses on iouReports**
- Members can hold each others expenses.

## Unhold
**Expenses on expenseReports**

- Members can unhold their own expenses, but only if they themselves put the expense on hold.
- Approvers can unhold expenses submitted to them.
- Admins can unhold any held expense on a workspace they’re an admin of.

**Expenses on iouReports**
- Members can only unhold expenses they put on hold themselves.

**Comment by robertjchen** [comment]
Thanks for going through this and laying out all the cases! 🙇

**Comment by trjExpensify** [comment]
Anytime!

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I'm going to be working on this issue.

**Comment by BartoszGrajdek** [comment]
Hi! I'm currently quite busy with maintainment of live markdown lib, but @cdOut from our SWM team has the capacity to take this over. He already worked with hold requests feature, so he knows everything necessary to work on this. 🙏🏻

**Comment by trjExpensify** [comment]
Great!

**Comment by robertjchen** [comment]
Started on the backend, draft PR linked!

Having reviewed the existing logic, it looks like the only key thing we would have to change, at least for the backend, is just the **unhold case** (for both iouReports and expenseReports): `Members can only unhold expenses they put on hold themselves.`. All other cases appear to be working as intended.

Should have the backend PR wrapped up with automated tests tomorrow.

@cdOut Let me know if you have any questions on the frontend! In the Hold reportAction, we store the `accountID` of the person who performed the initial hold action, so you should be able to check that and display the `Unhold` button if the viewer is authorized to perform the action 👍

**Comment by robertjchen** [comment]
Backend PR now under review 👍

**Comment by robertjchen** [comment]
@cdOut Just to clarify that the frontend changes can be done independently without having to wait for the backend, let me know if you have any questions on the flows! 🙇

**Comment by cdOut** [comment]
I'll start looking into this one today, I'll let you know if I have any questions.

**Comment by trjExpensify** [comment]
Assigning @parasharrajat for the review. @cdOut let us know when the PR is up. Thanks!

**Comment by cdOut** [comment]
I'll have a draft PR ready by the EOD.

**Comment by cdOut** [comment]
It is in draft, will move through to review by tomorrow.

**Comment by robertjchen** [comment]
Thanks @cdOut ! Let me know if you need anything else, the backend fixes were deployed 👍

**Comment by robertjchen** [comment]
Latest update here: https://github.com/Expensify/App/pull/45151#issuecomment-2255272532

**Comment by robertjchen** [comment]
Finishing touches on the PR, looks on track to be merged later today.

**Comment by robertjchen** [comment]
Under review/testing, looks like a few final bugs to hammer out, but we're close

**Comment by robertjchen** [comment]
PR was updated and under review! 🏃

**Comment by robertjchen** [comment]
Closing this out as this was internal, please re-open if we missed anything.

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @parasharrajat $250

Please request on NewDot!

**Comment by trjExpensify** [comment]
Thanks for that, Dylan! With the payment summary done, we can close it now. Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
