### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] [CSV] Add Selection mode to Search page

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#44577]
HOLD https://github.com/Expensify/App/pull/44385

We should complete [this section of the doc](https://docs.google.com/document/d/1dwKo6o6PK-t5DlQlmZzP-B6uIvPOv74d6hc4rDgu8fs/edit#bookmark=id.jbrbap6y8161).

This will change the layout and how to enable the checkboxes in smaller screens.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015573ce7c34e042ac</li>
        <li>Upwork Job ID: 1807832005022163303</li>
        <li>Last Price Increase: 2024-07-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by trjExpensify** [comment]
@filip-solecki can you comment here so I can assign you before I pop labels on it?

**Comment by trjExpensify** [comment]
Removed the hold!

**Comment by filip-solecki** [comment]
Hi! Draft PR is [here](https://github.com/Expensify/App/pull/44820) - it is in our internal review so it should be ready for C+ tomorrow I guess

**Comment by trjExpensify** [comment]
Rushat has context on this project imp, switching him in for the review now.

**Comment by rushatgabhane** [comment]
@slafortune could you please attach payment summary 🙇

**Comment by slafortune** [comment]
@rushatgabhane can you please complete the checklist?

**Comment by slafortune** [comment]
New feature 

@rushatgabhane Role contributor is owed $250 via NewDot
@filip-solecki  role C+ is from an agency-contributor and not due payment

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
