### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] Netsuite - Categories copy mentions "Xero settings" instead of "NetSuite" settings

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44591]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44038
## Action Performed:
Precondition:
- Account is connected to NetSuite (set up from OD)
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Categories

## Expected Result:
The Categories copy should mention "NetSuite settings"

## Actual Result:
The Categories copy should mention "NetSuite settings"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/822e7c0f-ea65-4b3a-bf4f-8ced4907d3b1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012bfdd3cfbe5588a2</li>
        <li>Upwork Job ID: 1806537315771441691</li>
        <li>Last Price Increase: 2024-06-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment]
@robertjchen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by mananjadhav** [comment]
This isn’t a deploy blocker. I think this should be covered with the NetSuite project the way we fixed connect modal.  Netsuite is still work in progress so we can work on this after fixing the integration piece. 

cc- @yuwenmemon @JmillsExpensify


I recently added CONNECTIONS.NAME_USER_FRIENDLY object. We can use that to fix it.

**Comment by robertjchen** [comment]
Got it, that makes sense!

**Comment by mananjadhav** [comment]
Can we put this on hold for https://github.com/Expensify/App/issues/43437. I won't get to it until I finish Import.

**Comment by mananjadhav** [comment]
I've raised the PR to fix this.

**Comment by mananjadhav** [comment]
This will be paid out centrally so we are good to close this one out.

**Comment by robertjchen** [comment]
thanks!
