### ISSUE TITLE
[HOLD for payment 2024-08-05] [$125] Chat - Onyx and DOMException console errors appear when sending an image in a DM

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44603]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #42592
**Version Number:** 9.0.3-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Preconditions: Be a workspace member as a new Gmail account.

1. Navigate to https://staging.new.expensify.com/
2. Log in as the member account
3. Click on FAB - Start chat
4. Select any existing Gmail account
5. Open Chrome console
6. Send an image attachment in the chat

## Expected Result:
There shouldn't be any console errors when sending an image.

## Actual Result:
"Onyx" and "Uncaught (in promise) DOMException" console errors appear when sending an image in a DM. The "Onyx" error only appears when the user is part of a workspace.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[Bug6527021_1719554233249!staging.new.expensify.com-1719553282882.txt](https://github.com/user-attachments/files/16028042/Bug6527021_1719554233249.staging.new.expensify.com-1719553282882.txt)

https://github.com/Expensify/App/assets/38435837/4aedb4b4-62d8-4559-bdf1-4e89f4c4b8b3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b91b6cb691a5c72</li>
        <li>Upwork Job ID: 1806791265391666720</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103033509</li>
<li>nkdengineer | Contributor | 103033510</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by m-natarajan** [comment]
@iwiznia FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by dylanexpensify** [comment]
@iwiznia confirmed reproducible

**Comment by iwiznia** [comment]
In dev I have a billion errors, but not this one.... but also images are not working properly not sure why.

**Comment by iwiznia** [comment]
I kept struggling with my dev env and still could not make images work there. Will look more on monday

**Comment by mountiny** [comment]
@kavimuru @m-natarajan @izarutskaya I have tested and the image got sent. I think if it's just a console error without affecting the user, we do not have to block the deploy on it

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Onyx" and "Uncaught (in promise) DOMException" console errors appear when sending an image in a DM. The "Onyx" error only appears when the user is part of a workspace.

### What is the root cause of that problem?
When saving attachmentInfo to Onyx when sending attachment, the `file` is being saved to Onyx as is https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/ReportUtils.ts#L3675

However the file selected from the image picker is not a purely JSON-compatible object, it contains functions too (eg. `function arrayBuffer` as in the error log).

When we attempt to save such function to Onyx, it cannot be serialized and will throw error.

### What changes do you think we should make in order to solve the problem?

Before using the file [here](https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/components/AttachmentModal.tsx#L264) we need to sanitize it to a JSON-compatible object, the functions are not needed so can be stripped.
```
const fileData = file ? {
    name: file?.name,
    source: file?.source,
    uri: file?.uri,
    height: file?.height,
    size: file?.size,
    type: file?.type,
    width: file?.width,
} : {};

onConfirm(Object.assign(fileData, {source: sourceState} as FileObject));
```

This can be done here or before we save the attachment to Onyx https://github.com/Expensify/App/blob/4622e19c1da5137bc7b227f5b65bf3d83f96a909/src/libs/ReportUtils.ts#L3675

### What alternative solutions did you explore? (Optional)
We can write and use a method `sanitizeObject` that will iterate through all object propoperties and remove all functions or other non-serializable values, leaving only primitive values that can be serialized.

**Comment by nkdengineer** [comment]
[Proposal updated](https://github.com/Expensify/App/issues/44603#issuecomment-2197877626) with 2nd solution

**Comment by nkdengineer** [comment]
> Are you able to find the offending PR?

@hoangzinh I haven't been able to

> Moreover, when I test your solution in Web, it raises another error:

Yeah I just saw it too, I've updated the [proposal](https://github.com/Expensify/App/issues/44603#issuecomment-2197877626) to make sure it doesn't happen.

**Comment by iwiznia** [comment]
Hmmmm so what was the old version of onyx doing when we attempted to save the FileObject?
Anyway, I think attempting to save a non plain object is wrong, so we should fix that in this issue.
So can we save a modified version like @nkdengineer suggested above? What do we use this data for exactly?

**Comment by jasperhuangg** [comment]
Removing `DeployBlockerCash` label via [this](https://github.com/Expensify/App/issues/44603#issuecomment-2197636529)

**Comment by iwiznia** [comment]
If we only ever need to know if there's a file or not, then maybe saving all that data that was suggested above is not the best. Why not save just a boolean then?

**Comment by nkdengineer** [comment]
> Why not save just a boolean then?

We certainly can do this. [Proposal updated](https://github.com/Expensify/App/issues/44603#issuecomment-2197877626) to mention that we can replace `attachmentInfo` by a boolean `hasAttachmentInfo`

**Comment by iwiznia** [comment]
@hoangzinh can you review the proposal above please?

**Comment by nkdengineer** [comment]
@hoangzinh Yup that sounds clearer, it's just variable naming so I think we can handle it in the PR phase. I've updated [my proposal](https://github.com/Expensify/App/issues/44603#issuecomment-2197877626) to highlight the possible naming.

**Comment by nkdengineer** [comment]
@hoangzinh Done!

**Comment by nkdengineer** [comment]
@hoangzinh Sure, I've done that

**Comment by iwiznia** [comment]
Looks good to me too

**Comment by nkdengineer** [comment]
@hoangzinh The PR is [here](https://github.com/Expensify/App/pull/45043).

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @nkdengineer $125
- Contributor+: @hoangzinh $125

Please apply/request!

**Comment by dylanexpensify** [comment]
@nkdengineer please accept offer when you can!

**Comment by nkdengineer** [comment]
@dylanexpensify Thanks for the offer, I accepted it 👍

**Comment by dylanexpensify** [comment]
Done!
