### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Web : Profile section is empty when a workspace is created on the new account

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue was found when validating #[42592](https://github.com/Expensify/App/pull/42592)
**Version Number:** 9.0.3-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new expensifail account
3. Click on FAB - New workspace

## Expected Result:
The Profile page should be filled with content.

## Actual Result:
Occasionally a newly created WS Profile page is empty until the browser is refreshed. Affects Gmail and applause.expensifail.com domains.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/bf750f36-f05b-4a6f-9f5e-5d17a0fc02cb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018334025bb716d28c</li>
        <li>Upwork Job ID: 1807790300561756436</li>
        <li>Last Price Increase: 2024-07-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by m-natarajan** [comment]
@puneetlath FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by puneetlath** [comment]
I think this is caused by https://github.com/Expensify/App/pull/42901. Where the OpenPolicyProfilePage command is failing because CreateWorkspace hasn't completed yet.

**Comment by Gonals** [comment]
Marking it back as a deploy blocker, as I'm having issues reproducing it on prod and our #1 suspect is only on staging

**Comment by abzokhattab** [comment]
I am not able to reproduce this issue on the latest main.

**Comment by rafecolton** [comment]
Removing the `DeployBlocker` label per [this Slack comment](https://expensify.slack.com/archives/C07J32337/p1719853471075889?thread_ts=1719852087.531379&cid=C07J32337)

**Comment by jasperhuangg** [comment]
@MonilBhavsar @fedirjh Are you available to help investigate this deploy blocker? It seems to be related to https://github.com/Expensify/App/pull/42901 and Vit is OOO

**Comment by jasperhuangg** [comment]
Looks like we're discussing reverting https://github.com/Expensify/App/pull/42901 [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1719619344600239)

**Comment by puneetlath** [comment]
Confirmed it's fixed on staging after reverting. Closing this out.

**Comment by m-natarajan** [comment]
Reopening this as per this https://expensify.slack.com/archives/C049HHMV9SM/p1720019223320069

**Comment by luacmartins** [comment]
I reproduced this on prod, so I'll remove the blocker label.

**Comment by puneetlath** [comment]
Just to make sure I've got it right. @fedirjh was the C and @dukenv0307 was the C+. Is that right?

**Comment by puneetlath** [comment]
Ah ok I see @fedirjh. It looks like that PR addressed multiple issues. Which one should we handle payment in?

**Comment by puneetlath** [comment]
Looks like @hungvu193 requested payment in the other issue, so I'm going to close this one. Let me know if I'm mistaken and I'll reopen.
