### ISSUE TITLE
Unable to sign up with new phone number

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR:** https://github.com/Expensify/App/pull/44515
**Email or phone of affected tester (no customers):** 12025643894
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open [www.staging.new.expensify.com](http://www.staging.new.expensify.com/)
2. Enter new phone number using country code without a + to create a new account
3. Tap join

## Expected Result:
New account is created

## Actual Result:
Join button loads briefly then nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/22e20581-a4d5-4afc-baa1-8213c935eb29

https://github.com/Expensify/App/assets/115492554/d95ac9e4-26dd-45b1-89ab-931405ad5e37

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jacobkim9881** [comment]
Tried on 9.0.2-0, entering "12025643894" doesn't allow to open signup modal. Error msg stop from proceeding signup. 

It is only reproducible on staging. Maybe any regression raise this issue?

**Comment by kadiealexander** [comment]
Asked if it's a regression [here](https://github.com/Expensify/App/pull/44515).

**Comment by jacobkim9881** [comment]
> The bug is actually for VoIP numbers, we are not allowed to enter those, I guess this has been discussed previously as well, we block use of VoIP numbers

@allgandalf  Then creating a new account by VoIP num shouldn't be allowed!

**Comment by kadiealexander** [comment]
Closing as not a problem, people won't generally be signing up with VoIP numbers.
