### ISSUE TITLE
[$250] Expense - Preview in main chat briefly disappears after renaming report and deleting expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44607]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4678766
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com/
2. Go to workspace chat.
3. Submit two expenses.
4. Go to expense report.
5. Click Title field.
6. Change the report title and save it.
7. Submit another expense.
8. Go to main chat and back to expense report for the rename message to show up.
9. Go to transaction thread of the latest expense (submitted in Step 7).
10. Click on the report header > Delete expense.
11. Delete the expense.

## Expected Result:
App will return to expense report because there are still two expenses in the report.

## Actual Result:
App returns to main chat, and the expense preview in the main chat disappears briefly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0fb0c015-df4a-4724-9ebb-f961c368aad8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d610c7726bd86731</li>
        <li>Upwork Job ID: 1807883887257636893</li>
        <li>Last Price Increase: 2024-07-08</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleting a transaction removes the expense report if the last action in the expense report is renamed action.

### What is the root cause of that problem?
The expense report will be deleted if the last message text of the expense report is empty.
https://github.com/Expensify/App/blob/cb8fce822d0719989a335011f7715d3e6f670efe/src/libs/actions/IOU.ts#L5313-L5315

We get the last message from the HTML of the message here (getTextFromHtml).
https://github.com/Expensify/App/blob/cb8fce822d0719989a335011f7715d3e6f670efe/src/libs/ReportActionsUtils.ts#L765-L771

However, the renamed action doesn't have HTML.
<img width="221" alt="image" src="https://github.com/Expensify/App/assets/50919443/bb9ec46f-fcaa-49f4-9a44-3b9646b9eb69">

### What changes do you think we should make in order to solve the problem?

Instead of using `getTextFromHtml`, we can use `getReportActionMessageText`.
```
let messageText = getReportActionMessageText(lastVisibleAction) ?? '';
```

**Comment by trjExpensify** [comment]
report titles/fields is a project in wave-control.

**Comment by sobitneupane** [comment]
Thanks for the proposal @bernhardoj 

Can you please add more [details](https://github.com/Expensify/App/issues/44607#issuecomment-2196947205) in the Solution section of your proposal. How will it solve the issue?

**Comment by bernhardoj** [comment]
Updated

**Comment by sobitneupane** [comment]
Thanks @bernhardoj 

[Proposal](https://github.com/Expensify/App/issues/44607#issuecomment-2196947205) from @bernhardoj looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by sobitneupane** [comment]
PR deployed to production 1 week ago. https://github.com/Expensify/App/pull/45365#issuecomment-2244528145 This is ready for payment.

**Comment by sobitneupane** [comment]
@johncschuster This is ready for payment. PR was developed a month back. https://github.com/Expensify/App/pull/45365#issuecomment-2244528145

**Comment by sobitneupane** [comment]
Bump @johncschuster

**Comment by johncschuster** [comment]
Sorry for the delay! Working on this now.

**Comment by johncschuster** [comment]
Payment Summary:

Contributor: @bernhardoj  owed $250 via NewDot
Contributor+: @sobitneupane owed $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by johncschuster** [comment]
@sobitneupane, do we need any regression test steps? If so, can you provide them?

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open a workspace chat
2. Submit 2 money requests
3. Rename the expense report title
4. Reopen/refresh the expense report to see the renamed system message
5. Add another money request
6. Delete the recently added money request
7. Verify the expense report isn't deleted and you stay at the expense report page

Do we agree 👍 or 👎

**Comment by johncschuster** [comment]
Thanks, @sobitneupane! Please request payment!

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
