### ISSUE TITLE
[HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [Pending/Scanning] Manual Requests are Being Added to Processing Card Transactions

### ISSUE THREAD

**Issue by grgia** [Expensify/App#44614]
Follow up to https://github.com/Expensify/Expensify/issues/405657

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by grgia** [comment]
in progress

**Comment by grgia** [comment]
Fix PRs in final review

**Comment by grgia** [comment]
Still in progress, waiting on the app pr deploy

**Comment by strepanier03** [comment]
I don't think we need any sort of payment here. Going to close out.
