### ISSUE TITLE
[HOLD for payment 2024-07-17] Track expense - "Hold" option should not appear for tracked expense in combined report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44617]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.2
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com/
2. Go to workspace chat that has no unsettled expense
3. Go to + > Track expense
4. Track a manual expense
5. Go to transaction thread (combined report)
6. Click 3-dot menu
7. Note that Hold option is available for tracked expense in the combined report
8. Submit another expense
9. Go to transaction thread of the tracked expense in Step 4
10. Click 3-dot menu
11. Note that Hold option is actually not available for tracked expense (this is the correct behavior)

## Expected Result:
In Step 7, in one-report combined view, "Hold" option should not show up for the tracked expense

## Actual Result:
In Step 7, in one-report combined view, "Hold" option shows up for the tracked expense in 3-dot menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1191f097-5c93-4309-ad69-fda344c9639e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment]
@NikkiWines  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by NikkiWines** [comment]
This is almost certainly from https://github.com/Expensify/App/pull/43618. I don't think this should be a blocker even if the behavior isn't what we intend though, it's fairly low impact and doesn't come across as "buggy".

@trjExpensify just to confirm, do you think we should show the `HOLD` option for Track expenses? If not, let's open a new issue to rectify this rather than reverting the whole PR.

**Comment by trjExpensify** [comment]
@NikkiWines I don't think you should be able to hold expenses in your selfDM. They _should_ be immediately added to a closed report and there's nothing to do or prevent. 👍

**Comment by NikkiWines** [comment]
Cool, I can spin up an issue or PR to handle this, but removing the blocker label for now 👍

**Comment by JmillsExpensify** [comment]
Wait, are we adding track expenses to reports now? They should be unreported by design, right?

**Comment by JmillsExpensify** [comment]
Or is this referring to the case of tracked expenses on a workspace.

**Comment by trjExpensify** [comment]
Ah yeah, sorry, this is referring to the admin `Track expense` option in the workspace chat, not the selfDM. They're added to closed reports, so there's nothing to do, so `Hold` shouldn't be there:

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/68e955ee-8113-4414-a0e2-b606ebb4c3f8">

(Ignore all the archived stuff obviously)

**Comment by JmillsExpensify** [comment]
Thanks for the clarification! You should not be able to hold a `reimbursed` or `closed` report, so this makes sense to me.

**Comment by mallenexpensify** [comment]
@lschurr , needed a BZ here to pay once PR hits production, it's on staging now ([I think](https://github.com/Expensify/App/pull/44656))

**Comment by lschurr** [comment]
This is due payment tommorrow - https://expensify.slack.com/archives/C01SKUP7QR0/p1721171565737339

**Comment by lschurr** [comment]
Payment summary:

- Reviewer: @akinwale $250 (Please request in Newdot)

**Comment by akinwale** [comment]
@lschurr I am not eligible for NewDot payments until late October, so I still need to be paid through Upwork for this one.

**Comment by lschurr** [comment]
Offer sent in Upwork @akinwale - https://www.upwork.com/nx/wm/offer/103161072

**Comment by lschurr** [comment]
All set!
