### ISSUE TITLE
Cherry Pick and Version bump PRs are showing up in Deploy Checklist

### ISSUE THREAD

**Issue by Jag96** [Expensify/App#4462]
### Problem

When a PR is cherry-picked to staging, the automerge PR made to CP the PR to staging is included in the Deploy Checklist ([example](https://github.com/Expensify/App/issues/4447#issuecomment-894343370)). Then, when the version is bumped, the automerge PR to bump the version is added to the checklist as well, adding unnecessary noise for QA.

### Solution

Don't add PRs with the automerge label to the Checklist:
- Update Version example: https://github.com/Expensify/App/pull/4332
- CP example: https://github.com/Expensify/App/pull/4390

cc @AndrewGable @roryabraham

**Comment by roryabraham** [comment]
As discussed [here](https://github.com/Expensify/App/issues/4447#issuecomment-895367394), this should hopefully be fixed in https://github.com/Expensify/App/pull/4408
