### ISSUE TITLE
[$250] Multi tags - Tag disappears after reordering tags and app crashes after disabling all tags

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44626]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0-3.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4678845) 
**Email or phone of affected tester (no customers):**  
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has set up with independent multi tags (A, B, C and D)
- Multi tags A and B are set to Required
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to + > Submit expense > Manual
4. Proceed to confirmation page
5. Click Show more
6. Go to Old Dot
7. Reorder the position from multi tag A and B to multi tag B and A, while keeping C and D untouched
8. Note that on New Dot, multi tag A disappears from confirmation page
9. On Old Dot, disable multi tag A and B
10. Go to New Dot and wait for app to crash

## Expected Result:
In Step 8, multi tag A will not disappear after reordering tags
In Step 10, app will not crash

## Actual Result:
In Step 8, multi tag A disappears after reordering tags
In Step 10, app crashes after disabling all the tags

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b14eea7d-5d75-4d30-9ae6-d35dd869a52c

[Bug6527371_1719578072235!Independent.-.Multi.Level.tags.csv](https://github.com/user-attachments/files/16032656/Bug6527371_1719578072235.Independent.-.Multi.Level.tags.csv)

[logs (2).txt](https://github.com/user-attachments/files/16032671/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123c6d5064aec7c2e</li>
        <li>Upwork Job ID: 1806779895355813021</li>
        <li>Last Price Increase: 2024-07-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @yuwenmemon</details>

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Christinadobrzyn** [comment]
I'm not getting the crash in testing but I am seeing the tag organisation is wrong - I think this can be external.

**Comment by AndrewGable** [comment]
@yuwenmemon - Do you mind stepping in here as the multi tag expert?

**Comment by yuwenmemon** [comment]
Sure thing

**Comment by Christinadobrzyn** [comment]
Just checking - do we have an update for Melvin?

**Comment by yuwenmemon** [comment]
I'm OOO for the July 4th holiday so will circle back on this on Monday hopefully.

**Comment by Christinadobrzyn** [comment]
Hi @yuwenmemon do you have an update on this for Melvin?

**Comment by yuwenmemon** [comment]
Not yet, but switching this to internal as per the conversation above.

**Comment by Christinadobrzyn** [comment]
Update for Melvin - This is going to be worked on when we have the bandwidth

**Comment by Christinadobrzyn** [comment]
I think this is still in a holding pattern

**Comment by Christinadobrzyn** [comment]
@yuwenmemon do you think you'll have the bandwidth to work on this? If not, I can reach out to the channel for another volunteer!

**Comment by Christinadobrzyn** [comment]
I think this is still in a holding pattern - waiting for a volunteer

**Comment by yuwenmemon** [comment]
Looking at this today

**Comment by yuwenmemon** [comment]
No longer seeing this crash. Additionally don't see the disappearing tag issue either. Closing:

https://github.com/user-attachments/assets/f8716caf-1fdd-475f-b231-0727b340000e

An argument could be made that the tag order should update in real-time when the tags are reordered by the admin but that's such an edge case I'm fine ignoring that for now.
