### ISSUE TITLE
[HOLD for payment 2024-07-24] [HOLD for payment 2024-07-22] [HOLD for payment 2024-07-17] [CRITICAL] [$250] Comment link - Navigating to a report action comment doesn't scroll the report page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44625]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat with a user and send a lot of comments so that there is a scrollable history
3. Go to the top comment and copy the link to that comment
4. Open another chat and navigate to the copied link

## Expected Result:
The chat page scrolls to that specific comment

## Actual Result:
The report page opens up but doesn't scroll to the specific comment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0e401f8c-947b-488a-be13-f28a05815b8e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016eb6bedcd3171adc</li>
        <li>Upwork Job ID: 1808449293455136963</li>
        <li>Last Price Increase: 2024-07-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by lanitochka17** [comment]
@bondydaa  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by srikarparsi** [comment]
Hey @nkdengineer and @mollfpr, could you take a look if this regression is from this [PR](https://github.com/Expensify/App/pull/43531) whenever you have a chance?

**Comment by bondydaa** [comment]
☝️. that PR is the only one that stood out to me from the checklist that looks like it might be related to comment linking in some way so i'd ping'd srikar 1:1.

**Comment by nkdengineer** [comment]
@srikarparsi I tried to revert my PR and it doesn't fix this issue. Correct me if I missed something.

**Comment by tsa321** [comment]
Offending PR: https://github.com/Expensify/App/pull/42592

The ReportScreen gets mounted, unmounted, mounted, unmounted, and then mounted again.

In the network tab of the developer tools, the OpenReport API request is being called twice.

**Comment by Kicu** [comment]
Just two cents from me (im the author of the react PR)

> In the network tab of the developer tools, the OpenReport API request is being called twice, when opening a report.

as long as we are using `StrictMode` to try and prevent any possible future errors with react concurrent, the double requests will keep happening. That is how strict mode is supposed to work.

At least in theory we should try to make the app work despite the double renders.

**Comment by jasperhuangg** [comment]
I'm leaning towards reverting https://github.com/Expensify/App/pull/42592 right now, it's causing a few other blockers as well.

**Comment by jasperhuangg** [comment]
> Offending PR: https://github.com/Expensify/App/pull/42592
> 
> The ReportScreen gets mounted, unmounted, mounted, unmounted, and then mounted again.
> 
> In the network tab of the developer tools, the OpenReport API request is being called twice, when opening a report.

@tsa321

Did you test this out with your local build of the App? I think the logic added in that PR only runs on dev builds, so since this is also happening on staging I don't think that's the cause.

**Comment by jasperhuangg** [comment]
@Kicu ^ please correct me if I'm wrong 🙇

**Comment by tsa321** [comment]
> @tsa321

> Did you test this out with your local build of the App? I think the logic added in that PR only runs on dev builds, so since this is also happening on staging I don't think that's the cause.

@jasperhuangg you are right, Looks like I made a mistake.

**Comment by jasperhuangg** [comment]
Can't reproduce this anymore after reverting https://github.com/Expensify/App/pull/44412

cc @roryabraham

**Comment by Kicu** [comment]
> @Kicu ^ please correct me if I'm wrong 🙇

You are correct I believe. Staging should run production build of React and so if an error happens both on dev and on staging it shouldn't be because of StrictMode.

Btw I didn't check the actual build/deploy scripts, but if one opens react performance devtools on staging they don't work, with the message that a dev build is required. I hope that is enough of a confirmation 😅

**Comment by bondydaa** [comment]
okay a couple more cases here... 

this is a case where you link to the top most comment when you have enough to make the page scrollable which won't scroll back up

https://github.com/Expensify/App/assets/4073354/c873c4c3-6bf1-4b5f-82f1-87ebf7967886

And then this case shows where you have more messages below the linked comment and the linked comment gets "bottom pinned" and can't be scrolled until you click `new messages` which loads more messages underneath them.


https://github.com/Expensify/App/assets/4073354/bb3991d5-b384-46b5-a676-8c39dd8487d1

**Comment by bondydaa** [comment]
thanks @ishpaul777 for that context.

Lets just focus then on why we've stopped scrolling "up" then on this bug report.

**Comment by mountiny** [comment]
Looking for help identifying the fix

**Comment by jasperhuangg** [comment]
This issue has been blocking deploy for almost 3 days–we decided it was more harmful for it to keep blocking deploy than to let a bug with comment linking go out to production.

I added it to the #newdot-quality project and marked it `CRITICAL`

**Comment by mountiny** [comment]
@hurali97 is investigating

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by janicduplessis** [comment]
I wasn't aware of this issue, ended up investigating as part of the issues we found when working on https://github.com/Expensify/App/pull/41962

https://github.com/Expensify/App/pull/45313 fixes it.

I'm pretty sure this is a dev only issue since it happens only when strict mode is on so it would explain why it is not reproducible on staging.

**Comment by jasperhuangg** [comment]
@janicduplessis we were able to reliably reproduce the issue on staging when we initially ran into it–I don't think it has to do with strict mode.

**Comment by bondydaa** [comment]
adding BZ for payment, I think just @rayane-djouah for PR reviewing/testing right?

**Comment by slafortune** [comment]
@rayane-djouah - offer sent [here](https://www.upwork.com/nx/wm/offer/103171790)

Can you please complete the checklist?

**Comment by slafortune** [comment]
Paid ✅
