### ISSUE TITLE
[$250] Improve filtering performance in new chat page

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#44634]
Coming from https://github.com/Expensify/App/issues/37619

This issue is specifically for the new chat page and the C+ payment for [this PR](https://github.com/Expensify/App/pull/40350)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01941ca75bd8c92948</li>
        <li>Upwork Job ID: 1806743203181122627</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 103149732</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by roryabraham** [comment]
@TMisiukiewicz has already opened the PR, and @hungvu193 is our C+. no additional help needed here

**Comment by TMisiukiewicz** [comment]
Hi, can I get assigned to this issue please?

**Comment by stephanieelliott** [comment]
Assigned you, @TMisiukiewicz! Sure, I suppose we can make the issue more generic -- any suggestions on how we can generalize this? Happy to make those changes

**Comment by TMisiukiewicz** [comment]
@stephanieelliott I think "Improve filtering performance in remaining search pages" would be good. The list of the pages affected with this change:
- Invite to the room page
- Assign to task page
- Share somewhere page
- Share logs page

**Comment by hungvu193** [comment]
PR is under review

**Comment by alitoshmatov** [comment]
Coming from [here](https://github.com/Expensify/App/pull/40793#issuecomment-2190915651), where I reviewed this PR https://github.com/Expensify/App/pull/40793. If this is corresponding issue, can I get assigned to this? or is there separate issue

**Comment by stephanieelliott** [comment]
Hey @roryabraham wanted to check with you since you manually created this issue. Does this sound ok to you, to expand this issue to cover all remaining search pages? Here is what is being suggested: 

> I think "Improve filtering performance in remaining search pages" would be good. The list of the pages affected with this change:
> 
> Invite to the room page
> Assign to task page
> Share somewhere page
> Share logs page

**Comment by Pujan92** [comment]
> Coming from [here](https://github.com/Expensify/App/pull/40793#issuecomment-2190915651), where I reviewed this PR #40793. If this is corresponding issue, can I get assigned to this? or is there separate issue

+1, I have reviewed this [PR](https://github.com/Expensify/App/pull/40235). @roryabraham @stephanieelliott Could you plz help us with the payment?

**Comment by stephanieelliott** [comment]
Hm, ok -- so @Pujan92 and @alitoshmatov are also C+ here in addition to @hungvu193? I'll assume that is correct and update the assignment

**Comment by TMisiukiewicz** [comment]
@stephanieelliott from discussion above I feel like it's easier to have separate issues for each PR, could you please create them for:
- Invite to chatroom page
-  Task - Share somewhere
- Task - Assign

That's the only thing stopping me from undrafting those PRs 🙏

**Comment by roryabraham** [comment]
Hey, looks like we should create 1 issue per PR to help clarify and streamline the payments here:

- https://github.com/Expensify/App/issues/46145 for PR https://github.com/Expensify/App/pull/40793 cc @alitoshmatov 
- https://github.com/Expensify/App/issues/46147 for PR https://github.com/Expensify/App/pull/40235 cc @Pujan92 
- https://github.com/Expensify/App/issues/46148 for PR https://github.com/Expensify/App/pull/40285 cc @mollfpr 
- https://github.com/Expensify/App/issues/46149 for PR https://github.com/Expensify/App/pull/40764
- https://github.com/Expensify/App/issues/46150 for PR https://github.com/Expensify/App/pull/40338
- https://github.com/Expensify/App/issues/46151 for PR https://github.com/Expensify/App/pull/40290

That means we'll handle _only_ PR https://github.com/Expensify/App/pull/40350 in this issue.

**Comment by roryabraham** [comment]
sorry for the confusion everyone, hopefully things should be smoother sailing for this larger "improve filtering performance" initiative going forward and everyone should get paid.

@stephanieelliott, please issue payment of $250 to @hungvu193 for his review of https://github.com/Expensify/App/pull/40350, then close this out. Thanks!

**Comment by stephanieelliott** [comment]
Cool, thanks for clarifying @roryabraham! https://github.com/Expensify/App/pull/40350 was deployed to prod on 7/16 so I will go ahead and pay this now.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @TMisiukiewicz - no payment due (expert contrib)
 - Contributor+: @hungvu193 - $250, please request via ND
 
 Upwork job is here: https://www.upwork.com/jobs/~01941ca75bd8c92948

**Comment by hungvu193** [comment]
Requested on ND
