### ISSUE TITLE
IOU - Android -Unable to delete second added receipt on manual request once first is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a465@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. As Employee navigate to Workspace chat
2. Create manual request
3. Navigate to request and add receipt
4. Delete the receipt
5. Add another receipt
6. Delete the receipt

## Expected Result:
Once deleted the receipt should not appear anymore

## Actual Result:
Unable to delete the second added receipt on manual request once first receipt is deleted. The receipt reappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d63e8569-769e-4042-b3cc-e07eee9b1d74

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jacobkim9881** [comment]
It isn't reproducible

**Comment by twisterdotcom** [comment]
Agree, I cannot recreate. https://drive.google.com/file/d/1AqTK3d_CHPqoJn-TZZUOg5Xv0q2Aex-D/view?usp=sharing
