### ISSUE TITLE
[HOLD for payment 2024-07-22][$250] Add translations for date-fns

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#44637]
Coming from https://expensify.slack.com/archives/C036QM0SLJK/p1718061682568429

### Problem
date-fns [supports localization](https://github.com/date-fns/date-fns/blob/main/docs/i18n.md), but we aren't localizing relative timestamps like `7 days ago` into other locales anywhere in the app.

### Solution
Add localization for date-fns in our translation layer, such that relative datetimes and other formatted strings produced by date-fns are translated according to the current locale.

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e58fef3dc1a861a6</li>
        <li>Upwork Job ID: 1808794884611967857</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 102985707</li>
<li>ShridharGoel | Contributor | 102985708</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by c3024** [comment]
@roryabraham 

The Slack discussion appears to be in a private-channel.

I guess we'd like to show the time like `less than a minute ago` etc. in place of the exact time we are showing now.

We have a `datetimeToRelative` from the `useLocalize` hook which passes `locale` to the function `DateUtils.datetimeToRelative` already.

I think we need to change the usages of `datetimeToCalendarTime` in `ReportActionItemThread` and `ReportActionItemDate` to `datetimeToRelative`.

Should we also add a tooltip that shows the exact time when hovered over?

**Comment by c3024** [comment]
@ShridharGoel thanks! I do not remember seeing this relative time anywhere in the app. That is why I must have misunderstood the OP.

Where all do we use relative time?

**Comment by CortneyOfstad** [comment]
@c3024 any update? Thank you!

**Comment by c3024** [comment]
@ShridharGoel 's proposal looks good to me. We need to pass locale to `formatDistanceToNow`.

🎀 👀 🎀 C+ Reviewed

**Comment by Julesssss** [comment]
LGTM.

**Comment by Julesssss** [comment]
Sorry for the mess of labels... I assume I was assigned as Rory is off for July 4th. I'll move it forward as it's not a complex fix.

**Comment by roryabraham** [comment]
PR merged, thanks for the assist on the proposal review @Julesssss 🙇🏼

**Comment by roryabraham** [comment]
Something went wrong here, this went to prod yesterday. Going to mess with some more labels...

**Comment by CortneyOfstad** [comment]
@ShridharGoel — looks like it is awaiting you to accept the payment proposal in Upwork. Please let me know once you accept and I can get that paid ASAP — thanks!

**Comment by CortneyOfstad** [comment]
@ShridharGoel bump ^^^

**Comment by CortneyOfstad** [comment]
## Payment Summary

@ShridharGoel — paid $250 via Upwork
@c3024 — paid $250 via Upwork

Thanks all!
