### ISSUE TITLE
Settings - Prompt to download logs appears after disabling "Client side logging"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** test.iris.santos+17062024@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Account Settings -> Troubleshoot
2. Enable "Client side logging"
3. Click on "View debug console"
4. Dismiss "Debug console" panel
5. Disable "Client side logging"

## Expected Result:
No window prompting to download logs should be open after disabling "Client side logging"

## Actual Result:
A window prompting to download logs is open after toggling off 'Client side logging'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9a685170-7a18-480b-a944-ea64f6120850

![04 50](https://github.com/Expensify/App/assets/78819774/6d6a5a1a-e3fa-40ee-befa-e39b74066a86)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by puneetlath** [comment]
This is not a bug. This is how the feature purposely works so that whenever you enable/disable logging, you can download the logs that you generated while it was on.
