### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] mweb - Wrong status bar color at the top in safari

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44685]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719557238761689

## Action Performed:
1. Open app in light mode
2. Login
3. Verify the color of the status bar
## Expected Result:
Should not be a dark color
## Actual Result:
In light mode, the status bar is using a dark green color
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_0375]()

<img src="https://github.com/Expensify/App/assets/38435837/3b079825-a0e7-4cc2-aff8-1c6e543fd676" width="40%" height="40%">

https://github.com/Expensify/App/assets/38435837/a34f31bf-7341-4356-a5a5-600dd33dd80a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0119d994ad59578254</li>
        <li>Upwork Job ID: 1814407474918883716</li>
        <li>Last Price Increase: 2024-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103269275</li>
<li>dominictb | Contributor | 103269276</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by shawnborton** [comment]
I don't think so, because your linked PR hasn't hit staging yet and I reported this bug last week from Staging.

**Comment by hungvu193** [comment]
Here's the offending PR: https://github.com/Expensify/App/pull/42592
Disable StrictMode will fix the issue.

<img width="463" alt="Screenshot 2024-07-02 at 11 22 50" src="https://github.com/Expensify/App/assets/16502320/cb8b56e6-898a-451e-a1b8-7631be083a30">

**Comment by johncschuster** [comment]
Not overdue. This is actively being discussed.

**Comment by johncschuster** [comment]
Just bumping to get this one picked back up. @shawnborton, does the status of the PR @hungvu193 mentioned (https://github.com/Expensify/App/pull/42592) line up with when you reported the issue?

**Comment by shawnborton** [comment]
Hmm that one is above my head! Let's see if @roryabraham has any thoughts there since he is a reviewer on that mentioned PR.

**Comment by johncschuster** [comment]
@roryabraham can you help us get unstuck when you get a sec? I'm looking for some insight on [this question](https://github.com/Expensify/App/issues/44685#issuecomment-2215301169). Thank you!

**Comment by roryabraham** [comment]
oh hey. So one thing that React's strict mode does is run all effects twice. Why? No idea. I'm sure the React devs had a good reason 🙃 

It's _possible_ that might effect the code that sets status bar colors, but not obvious. IIRC most of the relevant logic is in these few files:

- https://github.com/Expensify/App/blob/21f55c7be031f3b2024482e5a2f895cda2a08dd7/src/components/CustomStatusBarAndBackground/index.tsx
- https://github.com/Expensify/App/blob/5dbca1d33cc8bc8cc688dddced748a644269623f/src/libs/StatusBar/index.web.ts

and on iOS Safari it's controlled by [this theme-color meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color).

Unfortunately it's like 2am for me, so I'm not able to help further right now 😞

**Comment by roryabraham** [comment]
also, I'm going to be OOO until Friday. I'll circle back as soon as I can, but let's avoid blocking on me for this. I imagine that if we make this external we'll get some reasonable proposals for me to review by the time I get back.

**Comment by eh2077** [comment]
@dominictb Thanks for sharing reproduction steps and investigating the issue! Their [proposal](https://github.com/Expensify/App/issues/44685#issuecomment-2239735948) looks good to me.

🎀👀🎀 C+ reviewed

**Comment by johncschuster** [comment]
Acknowledged! I'll issue payment after the regression threshold is cleared.

**Comment by johncschuster** [comment]
@eh2077 can you complete the BZ Checklist above?

**Comment by johncschuster** [comment]
I have issued payment for @dominictb. Thanks for your contributions! 🎉

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: Spent some time tracking commit histories but _**I'm unable to find the PR that caused this bug**_. This is an edge case that only happen on mobile Safari.
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. _**No, I don't think we should have a regression test**_ for it because this feature and related code won't change often.

**Comment by eh2077** [comment]
@johncschuster Just working on the checklist when you commented, completed!

**Comment by johncschuster** [comment]
Awesome. Thank you!

I've just issued payment for @eh2077. We're good to button this one up! 🎉
