### ISSUE TITLE
Unable to remove the expenses on the LHN caused by Departments no longer valid

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44699]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @justinpersaud 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719503778959179

## Action Performed:
1. Have a department that was used in the expense has been disabled or deleted
2. Open the app 
3. Observe the LHN
## Expected Result:
There should not be any expenses for the above department violations
## Actual Result:
There are chats in the LHN for the "Departments no longer valid" violation and unable to get rid of it
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (37)](https://github.com/Expensify/App/assets/38435837/0f046383-2138-47cc-aa98-03e18de3fd5a)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by justinpersaud** [comment]
I think this is already fixed on staging

**Comment by justinpersaud** [comment]
No longer an issue.
