### ISSUE TITLE
[$500] [Dev] Infinite receipt loading spinner with backend dev environment

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44692]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719847597306219

Please dm @neil-marcellini on Slack during PDT hours if you would like to test against my dev env.

## Action Performed:
1. Open New Expensify running on a backend dev environment (ask an internal engineer to share theirs via ngrok)
2. View an expense with a receipt
## Expected Result:
Once the receipt is loaded there won't be a loading spinner
## Actual Result:
Once the receipt is loaded there won't be a loading spinner
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/50ac8aad-1cce-4fe4-9363-e2a900e99dc0

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e28bd547489ae41</li>
        <li>Upwork Job ID: 1807839133623941808</li>
        <li>Last Price Increase: 2024-07-25</li>
    </ul>
</details>

**Comment by Taiwrash** [comment]
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
- The spinner keep rolling after the receipt as loaded
## What is the root cause of that problem?
- The `useState()` is not correctly updating
## What changes do you think we should make in order to solve the problem?
- Handle the state using the useState correctly
## What alternative solutions did you explore? (Optional)

**Comment by Taiwrash** [comment]
@ishpaul777 yes, it looks the same but I think for this demo, the app is not crashing which is different from the previous suggestion

**Comment by eh2077** [comment]
@Taiwrash Can you please elaborate on the root cause of this issue?

**Comment by Taiwrash** [comment]
YES!

The main cause of the error is the improper cleaning up of the data after fetching it from the backend. Although this can also be handled by setting the right dependencies for the useEffect where data fetching is happening. In summary, the root cause is the improper way of `state` update and wrong `cleanup`

**Comment by neil-marcellini** [comment]
@Taiwrash thanks for elaborating. Would you please update your original proposal with links to the current code causing the root problem and explain exactly what the issue is, along with your proposed solution? Please see our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and you can also look at proposals on other issue to get an idea of how they are written.


Thanks @ishpaul777 for recommending setting USE_STRICT_MODE = false. I'll try that.

**Comment by neil-marcellini** [comment]
> This might be dupe of #44566,

Let's keep an eye on that one because it might have the same fix or root cause, but this feels a bit different so I'll keep it separate for now.

**Comment by neil-marcellini** [comment]
Setting `USE_REACT_STRICT_MODE: false` [in Config.ts](https://github.com/Expensify/App/blob/a2c8d2cee9f22e7a8162a7b280ec43d4897b973f/src/CONFIG.ts#L99) doesn't seem to solve the problem.

**Comment by eh2077** [comment]
Still looking for proposals

**Comment by kadiealexander** [comment]
@neil-marcellini does this still happen for you?

**Comment by kadiealexander** [comment]
@neil-marcellini does this still happen for you?

**Comment by neil-marcellini** [comment]
Yes, and now the receipt images don't load at all. Let's double the price.

**Comment by Taiwrash** [comment]
> Yes, and now the receipt images don't load at all. Let's double the price.

Do you have a new error when the receipt is not showing now?

Kindly help with screenshot or video of the current state. I am sorry i have been out on this issue before now

**Comment by Taiwrash** [comment]
I figured out the error is due to the failure to receive `width` properties from from the `event.nativeEvent` in some cases of the responses
```bash
const {width, height} = event.nativeEvent.source;
```

## Here is a quick I came up to fix the issue for now

```bash
const imageLoadedSuccessfully = useCallback(
    (event: {nativeEvent: ImageLoadEventData}) => {
        if (!onLoad) {
            return;
        }

        // We override `onLoad`, so both web and native have the same signature
        const source = event.nativeEvent.source;
        if (source && typeof source === 'object') {
            const {width, height} = source;
            onLoad({nativeEvent: {width, height}});
        } else {
            // Handle the case where source is undefined or not an object
            console.warn('Image source is undefined or not an object');
            onLoad({nativeEvent: {width: 0, height: 0}}); // or handle this case as appropriate for your app
        }
    },
    [onLoad],
);
```

- The hacks: check source availability and is an object before destructuring.
-

**Comment by eh2077** [comment]
@Taiwrash Thanks for sharing your findings. Can you please update your proposal based on suggestion here https://github.com/Expensify/App/issues/44692#issuecomment-2204798363

**Comment by Taiwrash** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/44692#issuecomment-2200792454)

**Comment by Taiwrash** [comment]
@neil-marcellini @eh2077 looking forward to your review and besides i haven't been added to the slack channel, all the links i am seeing are not working for me. they are requesting for a unique email address

**Comment by eh2077** [comment]
@Taiwrash 
> Width value of the image is undefined and cannot be determined

Why does this keep images loading?

**Comment by Taiwrash** [comment]
> @Taiwrash
> 
> > Width value of the image is undefined and cannot be determined
> 
> Why does this keep images loading?

1. The code is trying to access the width property of an object that is undefined. This is happening in the image loading callback
2. The code is structure to use the loading spinner while waiting for images to load, the spinner's behaviour is tied to the successful completion of the image loading process which is not completing.
3.  The error has prevented the normal flow of your code that would otherwise signal that the image has finished loading, inother words, code to update the state of the spinner is not executed

Those are my observations @eh2077

**Comment by eh2077** [comment]
@dominictb Thank you for sharing your investigation!

**Comment by eh2077** [comment]
> > This might be dupe of #44566,
> 
> Let's keep an eye on that one because it might have the same fix or root cause, but this feels a bit different so I'll keep it separate for now.

@neil-marcellini I think we should put this on hold for https://github.com/Expensify/App/issues/44566 as they're very likely to share the same root cause. 



> Setting `USE_REACT_STRICT_MODE: false` [in Config.ts](https://github.com/Expensify/App/blob/a2c8d2cee9f22e7a8162a7b280ec43d4897b973f/src/CONFIG.ts#L99) doesn't seem to solve the problem.

Now it solved the problem if `USE_REACT_STRICT_MODE: false`. It also didn’t work in my previous testing.

**Comment by neil-marcellini** [comment]
This can be take off hold now. `USE_REACT_STRICT_MODE: false` does indeed fix the problem now, but it would be great to get this working with strict mode enabled too. @eh2077 @dominictb will your proposal work as is or do you need to make any updates now that the issue is off hold?

**Comment by eh2077** [comment]
There're some recent updates on `patches/react-native-web+0.19.12+003+image-header-support.patch` from PR https://github.com/Expensify/App/pull/45559/files. I think we need to diagnose the root cause again. 

@dominictb Would you like to take a look into this?

**Comment by neil-marcellini** [comment]
Ah yeah, the problem is fixed after I double checked. Sweet!

I had to run this to get the package patch to apply properly.
```
npm cache clean --force
rm -rf node_modules
npm install
```

![image](https://github.com/user-attachments/assets/ec499120-ceb8-49c6-9798-249ce0033a8c)
