### ISSUE TITLE
Welcome Modal is shown everytime when opening the app from background

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44701]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719702781422479

## Action Performed:
1. Open the Hybrid app
2. Tap "Get started" in the onboarding modal
3. Background the app
4. Open the app
## Expected Result:
Should not show the onboarding modal every time
## Actual Result:
Onboarding modal is shown every time opening the app from the background
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Imagen de iOS](https://github.com/Expensify/App/assets/38435837/4a3a4226-19e4-4773-9b51-e42e559f58bb)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mateuuszzzzz</details>

**Comment by marcochavezf** [comment]
Hi @mateuuszzzzz 👋🏽 I saw you were discussing a solution in the linked convo. I will assign you to keep it on your radar :)

**Comment by mateuuszzzzz** [comment]
I think I need to comment 😅 Now it should work

**Comment by mateuuszzzzz** [comment]
Hi, I'm working on the fix that should allow us to skip backend changes

**Comment by muttmuure** [comment]
This isn't inconsistent UX (it isn't unreliably doing this), so let's keep it out of the NewDot Quality project
