### ISSUE TITLE
[HybridApp] App crashes on second and all next attempts

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#44707]
### Problem
@quinthar is experiencing a crash on the second, third, fourth, etc. time of opening HybridApp

https://github.com/Expensify/App/assets/2838819/98d14da7-6362-41f9-af90-9886247ed51c

@mateuuszzzzz I am curious if this is possibly a crash with the latest education modal?

### Solution
Fix the crash!

**Comment by quinthar** [comment]
How is this different than https://github.com/Expensify/App/issues/44266?

**Comment by AndrewGable** [comment]
The NewDot boot splash is not loading in this video, meaning NewDot is never starting. I'm assuming it's a different issue, but we will know for sure once we do some more digging.

**Comment by mateuuszzzzz** [comment]
Hmmmm I would assume that if it's related to explanation modal then something is broken in it's OldDot part of implementation🤔

Do we have any logs for this case? I'm curious where exactly it crashes

**Comment by staszekscp** [comment]
Hi! 👋 Could you provide me an `.apk` with this specific version of the app? Also, has the app been only updated to the newest version when it appeared, or does it happen after a fresh install?

It seems like `ReactNativeActivity` has not been opened at all, so native logs could tell us a lot here - I suspect that something happens even before we reach `shouldGoToNewDot` function (we don't even see a blank screen that could indicate that a base activity was opened), but unfortunately I was not able to reproduce that locally 🤔

**Comment by AndrewGable** [comment]
It was v9.0.3.3 - [Here is the APK](https://drive.google.com/file/d/1zpubWXUiiL2JZe1i83Tn1agHYugvq4lc/view?usp=sharing)

**Comment by staszekscp** [comment]
I've just tested the `apk` and everything works just fine for me 🤔 Can I ask was it a one time issue, or does it happen consistently?

**Comment by AndrewGable** [comment]
Found crash in Firebase:

[org.me.mobiexpensifyg_issue_85c581edcdb39b941df627e7b1324a71_crash_session_668c16e700d80001245119bea6a1963a_DNE_0_v2.log](https://github.com/user-attachments/files/16133209/org.me.mobiexpensifyg_issue_85c581edcdb39b941df627e7b1324a71_crash_session_668c16e700d80001245119bea6a1963a_DNE_0_v2.log)
[org.me.mobiexpensifyg_issue_85c581edcdb39b941df627e7b1324a71_crash_session_668c16e700d80001245119bea6a1963a_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16133211/org.me.mobiexpensifyg_issue_85c581edcdb39b941df627e7b1324a71_crash_session_668c16e700d80001245119bea6a1963a_DNE_0_v2_stacktrace.txt)

**Comment by AndrewGable** [comment]
I am pretty sure this is due to a re-authentication bug, but we are getting closer to finding the root cause. Discussing with @staszekscp actively

**Comment by staszekscp** [comment]
I've managed to trigger the same error yesterday on my testing device, and it appeared in the [Crashlytics](https://console.firebase.google.com/u/1/project/expensify-mobile-app/crashlytics/app/android:org.me.mobiexpensifyg/issues/85c581edcdb39b941df627e7b1324a71?time=last-seven-days&sessionEventKey=668ea0e5010900013556db3f43f86785_1968467016605972544). If I'm right, the PR above should fix the issue

**Comment by AndrewGable** [comment]
@quinthar - Can you try testing the latest Android build: 9.0.6.3 and seeing if this is working for you now?
