### ISSUE TITLE
[#Wave-Control: Add NetSuite] Add support Reusing an Existing Connection via API

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#44718]
cc @shubham1206agra from https://expensify.slack.com/archives/C06ML6X0W9L/p1719862799874179

We will create a new API command to reuse an existing connection from another policy. Currently we do this via a non 1:1:1 API command via [`Policy_Connection_Copy`](https://github.com/Expensify/Web-Expensify/blob/334997f54782461d1eefb0a452c022c59522d7f6/api.php#L2182-L2183) that loads a policy, copies over the requested connection into the new policy, and then saves the new policy.

Instead of doing this we'll make a new Auth command that does the same thing as `Policy_Connection_Copy`. We will call this via a new API command - `CopyExistingPolicyConnection`.

This command will take in the following params:

**authToken** - Of the user who's initiating the sync
**policyID** - The policyID connected to NetSuite that we'll be copying from
**targetPolicyID** - The policyID of the policy we'll be copying connection data into
**connectionName**  - The name of the connection to by copying over

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by yuwenmemon** [comment]
Auth PR is ready for review about to spin up Web.

**Comment by dylanexpensify** [comment]
Ongoing!

**Comment by yuwenmemon** [comment]
This was deployed to prod, closing!
