### ISSUE TITLE
Improvements to Track Expense flow

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#44722]
We have a few improvements we'd like to make to the Track Expense flow. The main issue we'd like to address is that for Track users who are using the Search page, it is a jarring experience to send the Track user to the Inbox > SelfDM upon the creation of a tracked expense. 

When a user uses global create to create a tracked expense from the search page, we want to land them back in the Search page once the expense is created. This means that we'll get rid of the post-creation whisper that happens in the selfDM and instead, add those four buttons to the Track expense confirmation page:
![CleanShot 2024-07-02 at 11 05 29@2x](https://github.com/Expensify/App/assets/2319350/c7195eae-796b-4459-84c7-caf9a016ad12)

When a user Tracks an expense from the Search page, land them back on Search after creation:
![image](https://github.com/Expensify/App/assets/2319350/3942248b-64bb-4166-8ce8-62bbe0769a71)

When a user Tracks an expense from the Inbox page (or elsewhere), land them in the selfDM after creation:
![image](https://github.com/Expensify/App/assets/2319350/d46ed75a-562a-4491-bb4b-25abf60a9c81)

All other flows remain the same in terms of where they end (in a workspace chat, or a DM with someone else), but here's how it looks when we add those four buttons to the confirm page:

Submit it to someone:
![image](https://github.com/Expensify/App/assets/2319350/52e0cab6-ad0c-4e73-8aa6-c61f3beeed5e)

Categorize:
![image](https://github.com/Expensify/App/assets/2319350/9a17b32d-14ab-4efc-945d-ecb66c3acf33)

Share with accountant:
![image](https://github.com/Expensify/App/assets/2319350/28791ba8-77e0-4471-9bbc-ccd413d8292f)

Note that before we open this up to external contributors, we need to:
- Rip out the actionable whisper
- Consolidate those actions from the whisper into the TrackExpense Auth command

cc @thienlnam @Expensify/design

**Comment by thienlnam** [comment]
This will require some significant updates in merge all the options into Track Expense. @shawnborton Is there an initiative we can tie this to? I'm unsure how to prioritize this

**Comment by shawnborton** [comment]
Good question. I think the thing that I want to solve for the most is the weirdness that is created for Track users who basically get pushed away from the Search page, even though the Search page is by far the optimal place for Track users who just want to sort through their own expenses. 

@JmillsExpensify @trjExpensify @Expensify/design curious if you agree, and curious if you think it would make sense to address this in relation to the overall Search project? 

I think we might be able to argue that a natural follow up after that would be to make it so that the tracked expenses you have on the Search page should be much easier to send to someone, like this idea:

https://github.com/user-attachments/assets/d4ba795e-8bf7-4978-bfcf-0126be9abe7a

Anyways, curious what you all think. I could see us making this part of Search, or somehow tying it into the CVP/Onboarding improvements as this is a core flow that kind of kills our viral nature at the moment.

**Comment by dannymcclain** [comment]
Yeah I definitely agree that adding the actions to the tracked expense makes a lot of sense. Especially because right now if you "dismiss" the whisper actions, you have no way of getting them back.

@shawnborton are you suggesting that tracked expenses _always_ land you on the search page? Or only if you create a tracked expense _while_ on the search page? I could honestly see an argument for either, since it's much less likely that you're going to be chatting to yourself about your own tracked expenses.

**Comment by dannymcclain** [comment]
Yeah I'm with you. I could definitely go either way, but always landing on search doesn't seem like the worst thing to me.

**Comment by trjExpensify** [comment]
I like this idea. The first thing that came to mind is that I'm not sure why we'd limit it to `Track`?

**Comment by shawnborton** [comment]
That's also a great point.

**Comment by JmillsExpensify** [comment]
Interesting one. I'll admit that I'm pretty conflicted on this one, as we already have pretty strong data supporting that `Submit` is our best and primary bottom-up conversion channel. That makes these improvements lower on the prioritization list for me.I do generally agree though that if you create something on the Search page you should stay there.

**Comment by shawnborton** [comment]
@thienlnam out of curiosity, what was the original initiative that Track expense fell under?

**Comment by trjExpensify** [comment]
#vip-vsb.

**Comment by shawnborton** [comment]
Got it, so maybe we need to table this one until that ever becomes an active project again. 

That being said, I do think there is something to be said about always keeping you on the Search page if you create something from the Search page. If we feel strongly, we could open up a separate ticket for that one and file it under either collect or control to move along with other Search improvements.

**Comment by trjExpensify** [comment]
>we could open up a separate ticket for that one and file it under either collect or control to move along with other Search improvements.

I like this idea, and it would apply to both submit and track.

**Comment by dannymcclain** [comment]
>I do think there is something to be said about always keeping you on the Search page if you create something from the Search page

Yeah I think I like this idea more than just doing it for Track.

Would the idea be that no matter what you create, we keep you in the context of where you created it (either Search or Inbox)? Basically I'm wondering if this is just an expense thing, or if it would apply to all of the global create options (track, submit, split, pay, invoice, task, travel)? Maybe that's a conversation to have on the separate issue 😅

**Comment by dannymcclain** [comment]
I'd be in favor of that too. "Always maintain the Inbox/Search context." But like you said, it does sound like that may have significant effort involved.

**Comment by luacmartins** [comment]
> But I don't think I've seen any RHPs on the Search page show the workspace chat - it always shows the report level or transaction level.

Correct, we only show either the expense report or the transaction thread. 

I think keeping the Inbox/Search context is ideal and yea, it might be an involved solution.

**Comment by JmillsExpensify** [comment]
I'd be willing to add this as "search-related" polish as part of wave-control. Though I do kind of think that we add a week or monthly label and put this on the back-burner for a little bit. I want to do it eventually, it's just hard to call it a top priority with the broader feature parity initiatives in play.

**Comment by shawnborton** [comment]
That works for me, I can create the issue for this one and tag ya'll.

**Comment by shawnborton** [comment]
Issue created here: https://github.com/Expensify/App/issues/47179

**Comment by shawnborton** [comment]
Also cc @anmurali for visibility - we might want to just fold this all into the test we want to do where we combine the Track & Submit flows. [Slack convo here](https://expensify.slack.com/archives/C036QM0SLJK/p1723205514385749?thread_ts=1723161024.570569&cid=C036QM0SLJK) for more context.

**Comment by thienlnam** [comment]
Currently on the back-burner

**Comment by shawnborton** [comment]
Still on the backburner. I think we are going to address some of the other issues mentioned here (being able to send a Track expense elsewhere after you create it and save it), but this one:

> Always maintain the Inbox/Search context, aka if you create something from Search, stay on Search

Might be worth addressing at least?

**Comment by dannymcclain** [comment]
>>Always maintain the Inbox/Search context, aka if you create something from Search, stay on Search
>
>Might be worth addressing at least?

This is already in the product!

**Comment by shawnborton** [comment]
Oh right on! I think we might just want to close this one out and start fresh with the ideas that are brewing [here](https://expensify.slack.com/archives/C07NMDKEFMH/p1729518754994859?thread_ts=1729251140.912039&cid=C07NMDKEFMH), curious for your thoughts on that.

**Comment by shawnborton** [comment]
Wrote a new P/S [here](https://expensify.slack.com/archives/C07NMDKEFMH/p1729673577535109?thread_ts=1729251140.912039&cid=C07NMDKEFMH), so I say let's just close this one out and start fresh.
