### ISSUE TITLE
 iOS client inbox is not in sync with web client.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44758]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719833472233469

## Action Performed:
1. Log to iOS and web with high traffic account
2. In iOS approve or pay any iou 
3. Send a message as user B to A and read the message in iOS
## Expected Result:
Both iOS and Web client are updated in real time when reading the message or approving a report
## Actual Result:
iOS not synching with web 

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/f169d464-9212-4fd5-a05c-28eb5c4ff708

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
#44683

**Comment by lakchote** [comment]
Unable to reproduce, I've posted details on reproduction steps [here](https://expensify.slack.com/archives/C05LX9D6E07/p1720080662665439?thread_ts=1719833472.233469&cid=C05LX9D6E07). Tests done on new staging version deployed yesterday.

**Comment by lakchote** [comment]
Asked for a way to reliably reproduce it [here](https://expensify.slack.com/archives/C05LX9D6E07/p1720089697693939?thread_ts=1719833472.233469&cid=C05LX9D6E07), as I haven't been able to.

**Comment by lakchote** [comment]
@muttmuure do you still encounter the problem or not?

**Comment by muttmuure** [comment]
Yes, unfortunately I don't think we've fixed the root cause of this

**Comment by lakchote** [comment]
Asked for external expert help [here](https://expensify.slack.com/archives/C05LX9D6E07/p1720439783507999?thread_ts=1719833472.233469&cid=C05LX9D6E07), to speed up the resolution.

**Comment by muttmuure** [comment]
@jnowakow can you comment on the issue and I'll assign you?

**Comment by jnowakow** [comment]
Hello, sorry for late response. You can assign me to this one :)

**Comment by SzymczakJ** [comment]
Since Jan has some other work to finish, I will be taking over this issue, can you reassing it to me?

**Comment by muttmuure** [comment]
done

**Comment by SzymczakJ** [comment]
I can't reproduce this issue(even on high traffic account and with lots of messages unread), is this something that happens every time on your account, or maybe this bug happens after some time, or maybe it seems random and happens only from time to time?

**Comment by lakchote** [comment]
> I can't reproduce this issue(even on high traffic account and with lots of messages unread), is this something that happens every time on your account, or maybe this bug happens after some time, or maybe it seems random and happens only from time to time?

That's the tricky part, I wasn't able to reproduce either.

From what @muttmuure told me, it doesn't happen every time which complicates the reproduction steps.

**Comment by SzymczakJ** [comment]
Tried to reproduce for about 2 hours and failed to do so. I'll try once more when https://github.com/Expensify/App/issues/44269 fails to fix this issue. Is it okay with you?

**Comment by muttmuure** [comment]
I wonder if we can reproduce this with these steps

Receive messages to iOS

Create a queue of 11 failed Pings/ReconnectApp back to back using network throttling 

Queue a successful Ping/ReconnectApp

Mark the message as read on web

See if the status syncs over

**Comment by SzymczakJ** [comment]
I'll try these steps as a first thing on Monday, because today all of SWM is leaving for a integration trip and I'm working shorter hours 😃

**Comment by lakchote** [comment]
@SzymczakJ will test this morning if the reproduction steps above are working or not.

[PR](https://github.com/Expensify/App/issues/44269) that possibly fix this is still open.

**Comment by SzymczakJ** [comment]
Tried these reproduction steps and everything seems to work fine. 
Clamped sequential queue with 13 failed ReconnectApp requests, then went back to online on iOS and read the message on web.
App flushed the sequential queue and when queue length became 0 iOS synced successfully with web.
Maybe let's wait for that PR that Lucien mentioned? WDYT?

**Comment by muttmuure** [comment]
Can we try reading the message during the series of failed ReconnectApp requests?

**Comment by SzymczakJ** [comment]
I've read the message when App was going over all the stacked ReconnectApp requests. Initially the message wasn't shown as read on iOS, only after the App made a successful ReconnectApp request the message got updated and became "read". 
The message finally got it's status updated so I think this is a correct behaviour

**Comment by muttmuure** [comment]
OK, so it's something else then - thanks for looking.

**Comment by lakchote** [comment]
We're not close to a solution since we can't reproduce the bug reliably.

Other cases of a sync problem happening:
- https://expensify.slack.com/archives/C05LX9D6E07/p1721229329178199
- https://expensify.slack.com/archives/C05LX9D6E07/p1721229329178199 (reverse case here - it's Web not in sync with iOS)

@SzymczakJ were you able to reproduce it at least once or not?

**Comment by muttmuure** [comment]
I'm concerned that this still happens, but without reproduction steps it's hard to know how to proceed

**Comment by muttmuure** [comment]
I think that this is caused by the `Clear Cache and Restart` tool in the Troubleshoot menu. 

If you use that tool, your updated LHN is not synced across devices (which makes sense) and so it seems like they are out of sync (but that has been forced)
