### ISSUE TITLE
[HOLD for payment 2024-08-01] [$500] [Report Next Steps Audit] Simplify the report next steps 4 - App optimistic next steps

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44784]
[Tracking issue](https://github.com/Expensify/Expensify/issues/396068)

As part of the [Update Report Next Steps](https://docs.google.com/document/d/1mUUQzep18IWdZpwG6Qqtw9JH0dvLMvLXh-KTn_B51I4/edit#heading=h.mnjguil21u0a) design doc, implement these new report next steps:
- optimistic App next steps

by combining a couple of the existing ones. Please refer to the design document for instructions on how to proceed on the PR.

This needs to be implemented once the backend tasks for this project are done, ideally along the same time to minimize the time when the next steps are showing something else optimistically and when the server response comes in 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012d18ec8c8471d35f</li>
        <li>Upwork Job ID: 1810833012866730830</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103059681</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by mountiny** [comment]
Will look for a C+ to handle this one

**Comment by mountiny** [comment]
Not looking for proposals, going to pick some volunteer from the C+ team

**Comment by mountiny** [comment]
PR is going to be merged soon, we will have some small follow-ups I think

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @rayane-djouah $500, paid via Upwork
Contributor+: @eVoloshchak $500, please request on Newdot

**Comment by sakluger** [comment]
@eVoloshchak @rayane-djouah do we need to add regression steps for this new feature?

**Comment by dangrous** [comment]
Yep I think that's right!

**Comment by dangrous** [comment]
I think since regression tests are being handled elsewhere we're good to issue payment on this one right?

**Comment by JmillsExpensify** [comment]
$500 approve for @eVoloshchak

**Comment by mountiny** [comment]
Yeah I think we can close this one out now that everyone was paid
