### ISSUE TITLE
[HOLD for payment 2024-07-17]  Wallet - Error page overlaps with device status bar

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44805]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #44628
**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**  

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings > Wallet.
3. Click Enable Wallet.
4. Log in to Wells Fargo.
5. Proceed to idology sections.
6. Answer all idology questions incorrectly.

## Expected Result:
The error page will not overlap with device status bar.

## Actual Result:
The error page overlaps with device status bar.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9b496f8d-093f-4bad-abb7-245307c8eba9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by m-natarajan** [comment]
@hayata-suenaga FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by koko57** [comment]
as I'm the author of the PR I would like to fix this regression

**Comment by hayata-suenaga** [comment]
@koko57, thank you. please let me know when you raise a PR 🙇

**Comment by koko57** [comment]
@hayata-suenaga PR raised: https://github.com/Expensify/App/pull/44809

**Comment by hayata-suenaga** [comment]
Thank you! taking a look now

**Comment by mountiny** [comment]
This was CPed and PR is pending verification

**Comment by trjExpensify** [comment]
Checklist time!

**Comment by trjExpensify** [comment]
Thanks! Confirming payments as follows: 

- $250 to @hoangzinh for the C+ review 

Offer sent!

**Comment by trjExpensify** [comment]
Paid, closing!
