### ISSUE TITLE
[HOLD for payment 2024-07-24] [ESM] Expense - System message for receipt removal is different in expense report and LHN preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44817]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4693737
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Submit an expense with receipt.
4. Go to transaction thread.
5. Click on the receipt.
6. Click 3-dot menu > Delete receipt.
7. Delete the receipt.
8. Return to expense report.

## Expected Result:
The system message for receipt removal will be the same in the report and LHN.

## Actual Result:
The system message for receipt removal is "removed the receipt" in the report, while it shows "detached a receipt from expense '(none)'" in LHN.
When copied to clipboard, it shows "You detached a receipt from expense '(none)'" instead.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ea9c35aa-47af-4039-9a0e-a93c9c7a7c62

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by izarutskaya** [comment]
@jliexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by grgia** [comment]
@bernhardoj could this be related to https://github.com/Expensify/App/pull/43079 ?

**Comment by grgia** [comment]
cc @parasharrajat

**Comment by grgia** [comment]
Going to demote this, not really a deploy blocker

**Comment by grgia** [comment]
@deetergp this is related to Localize System Messages

**Comment by nkdengineer** [comment]
The same root cause with https://github.com/Expensify/App/issues/44817.

**Comment by nkdengineer** [comment]
I updated.

**Comment by BrtqKr** [comment]
I sent the draft. If there are any other issues related to that, I'll include them in the PR, but let's confirm it first.

**Comment by grgia** [comment]
bumped for more background from the project

**Comment by deetergp** [comment]
@BrtqKr The `CHANGEFIELD` system message is created in OldDot when an admin modifies a report field in _Workspace > [workspace name] > Reports_, you should not expect to see that when you change an expense. And the `MODIFIEDEXPENSE` action should only happen when someone other than the submitter modifies the expense.

**Comment by jliexpensify** [comment]
@grgia is this a correct payment summary?

- C+: @sobitneupane $250 (new.Dot payment)

**Comment by jliexpensify** [comment]
Bumpo @grgia or @sobitneupane to confirm if payments are needed!

**Comment by sobitneupane** [comment]
@jliexpensify I reviewed the [PR](https://github.com/Expensify/App/pull/44907) linked with this issue. I will request payment in newDot.

**Comment by jliexpensify** [comment]
Nice, ok the [payment summary](https://github.com/Expensify/App/issues/44817#issuecomment-2244331929) is correct then. Thanks!

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
