### ISSUE TITLE
[HOLD for payment 2024-07-17] Categories - The subtitle under "Members must categorize all expenses" contains "undefined"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#44826]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click Settings.

## Expected Result:
The subtitle under "Members must categorize all expenses" will not contain "undefined".

## Actual Result:
The subtitle under "Members must categorize all expenses" contains "undefined".
"Require a category on every expense in order to export to undefined."

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/468cfd62-208b-4aba-8cb3-fa3536e5f7bc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by kavimuru** [comment]
@zanyrenney FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by tgolen** [comment]
@Krishna2323 I think we should use `categories.requiresCategory` ("Members must categorize all expenses") if there is no connection. What do you think? Seems like it makes sense to me.

**Comment by tgolen** [comment]
> we just need to remove the subtitle if there is no connection.

Perfect, this is fine. Thanks! I'll assign you

**Comment by mountiny** [comment]
This was CPed and the PR is pending validation in staging

**Comment by zanyrenney** [comment]
okay thanks @allgandalf

**Comment by zanyrenney** [comment]
https://www.upwork.com/jobs/~01bb053c1f7f26c8bd

**Comment by zanyrenney** [comment]
**payment summary**

@Krishna2323 requires payment (Needs manual offer from BZ) - paid $250 via Upwork
@allgandalf requires payment (Needs manual offer from BZ) - paid $250 via Upwork

**Comment by zanyrenney** [comment]
payments complete, and regression test requested!
