### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250]  Send invoice - "Choose a payment method" disappears after returning from Pay elsewhere page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44830]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/43036
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Send an invoice to user B.
3. [User B] Go to invoice chat.
4. [User B] Click Pay button.
5. [User B] Click Pay as individual or Pay as business.
6. [User B] Click on the back button.

## Expected Result:
"Choose a payment method below" in the payment method selection page will persist.

## Actual Result:
"Choose a payment method below" in the payment method selection page disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3fdec9ff-73e0-4f5e-ae9e-f917809c7966

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ace2c2d5df911f17</li>
        <li>Upwork Job ID: 1809200291724480759</li>
        <li>Last Price Increase: 2024-07-05</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 103046339</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-bills.

**Comment by Abdelrahman286** [comment]
it would be better if you explain with voice

**Comment by mollfpr** [comment]
@cretadn22 What's the advantage of your solution to use slice instead of splice?

**Comment by mollfpr** [comment]
Thanks @cretadn22 it seems to make sense to use `slice` instead because it returned the copied array.

The [proposal](https://github.com/Expensify/App/issues/44830#issuecomment-2209293460) from @cretadn22 looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment]
@cretadn22 I really appreciate the effort in fixing the other issue! Regarding increasing the compensation I don't have anything to say, but probably this note will determine should the compensation increase.

Your original solution is applied first in this PR https://github.com/Expensify/App/pull/44724, and it got reverted https://github.com/Expensify/App/pull/45674.

I just noticed that the critical bug and solution you use in the PR are the same as @daledah's [proposal](https://github.com/Expensify/App/issues/44830#issuecomment-2209227774), that's why the issue is not reproduced anymore even your original solution is reverted.

**Comment by mollfpr** [comment]
@sonialiap @techievivek I'm not sure how we should handle this case, but I think we should compensate @daledah for the solution used to solve this issue, and because the selected solution got reverted.

**Comment by mollfpr** [comment]
@cretadn22 I don't know why you laughing at my comment 🥲

> This idea was mine first. Please check the history of their proposal

Also, I'm not sure which part you mean is your idea. What I'm pointing out is this snippet from your PR.

```js
    const renderHeaderText = () => {
        if (!headerText || enteredSubMenuIndexes.length !== 0) {
            return;
        }
        return <Text style={[styles.createMenuHeaderText, styles.ph5, styles.pv3]}>{headerText}</Text>;
    };
```

Here's the history from the @daledah proposal.

![Screenshot 2024-07-24 at 19 15 11](https://github.com/user-attachments/assets/12e662a1-b2d1-49b2-9111-3bc972057b0e)

**Comment by mollfpr** [comment]
>I don't mean anything, don't mind

@cretadn22 No worries, I'm just joking with you 😄

**Comment by techievivek** [comment]
@mollfpr so are we going with another PR here since the original changes got reverted? Or did we implement the solution somewhere else?

**Comment by techievivek** [comment]
> https://github.com/Expensify/App/pull/45178 fixed this issue. We don't need to create a new PR

Aaah, I see now, @mollfpr referred to a different PR by a different contributor.

**Comment by techievivek** [comment]
I think we can partially compensate @daledah(since their solution was used in the fix) and @cretadn22(they created the PR and helped fix another bug). I will let @sonialiap take a look into it. Thanks.

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR was found.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good!

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. [User A] Send an invoice to user B.
2. [User B] Go to invoice chat.
3. [User B] Click the Pay button.
4. [User B] Click Pay as individual
5. [User B] Click on the back button
6. **Verify** "Choose a payment method below" in the payment method selection page will persist
7. 👍 or 👎

**Comment by techievivek** [comment]
Looks good to me, @sonialiap can we please get this added to testRail, thanks.

**Comment by JmillsExpensify** [comment]
@sonialiap please add a payment summary when you get a chance.

**Comment by sonialiap** [comment]
Since it seems like there was extra work put into this, I'm increasing the base price to $500

Payment summary:
- @daledah $250 for the proposal
- @cretadn22 $500 for the fix
- @mollfpr $500 for the c+

Does this sound fair to everyone?

**Comment by JmillsExpensify** [comment]
$500 approved for @mollfpr

**Comment by sonialiap** [comment]
@daledah thanks for the upwork link! Offer sent 💃

**Comment by sonialiap** [comment]
Everyone has been paid ✔️
