### ISSUE TITLE
Task – Deleted task is not deleted for user B in group chat if chat is open.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44832]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4693548
**Email or phone of affected tester (no customers):** applausetester+jpcategory_1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
44782 – Task – Deleted task is not deleted for user B in group chat if chat is open.
1. Go to https://staging.new.expensify.com/
2. Log in as user A
3. Open group chat with user B
4. Create a task
5. As user B open group chat with user A and verify that the task is present
6. As user A delete the task
7. As user B observe the group chat with task

## Expected Result:
Deleted task disappears for user B in group chat if chat is open.

## Actual Result:
Deleted task is visible for user B in group chat, task disappears after chat reopen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/23ec2999-0352-4e4f-ac88-592181d6c02d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by jacobkim9881** [comment]
Not reproducible.

**Comment by JmillsExpensify** [comment]
Going to close in that case.
