### ISSUE TITLE
[$250] mWeb-distance rate-Selected Distance rate amount (IQD 0.7) is not shown in rate page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44846]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on profile icon -- workspaces-- workspace
3. Tap more features -- Enable distance rate
4. Tap profile and change currency to IQD
5. Tap back
6. Tap distance rates -- rate -- rate

## Expected Result:
Selected Distance rate amount (IQD 0.7) must be shown in rate page

## Actual Result:
Selected Distance rate amount (IQD 0.7) is not shown in rate page. Rate page shows amount as zero

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/057ca424-7d51-413e-8c31-d6d46e989e3b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe275e58c3e4afa6</li>
        <li>Upwork Job ID: 1811456890794199886</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by eh2077** [comment]
@greg-schroeder Can you help to confirm the expected behaviour here? As the IQD currency doesn't support decimals, so it's the expected behaviour to show **_zero_** in the amount input.



| Should we replace rate `IQD 0.7` with `IQD 0` ?  | This should be expected as IQD currency doesn't support decimals |
| ------------- | ------------- |
|<img width="300" alt="image" src="https://github.com/user-attachments/assets/f012e610-ae4f-490d-ae83-ebc6d7c18e57">  | <img width="300" alt="image" src="https://github.com/user-attachments/assets/7177e110-09f6-4561-b668-e7a13610281e"> |

**Comment by greg-schroeder** [comment]
@eh2077 sorry do you mean the currency itself doesn't support non-integer values? I'm not sure that's true is it? 🤔

**Comment by eh2077** [comment]
@greg-schroeder Yes

**Comment by eh2077** [comment]
@greg-schroeder Can you help to clarify how we should move forward with https://github.com/Expensify/App/issues/44846#issuecomment-2227373806 ? Given there're indeed a few currencies that doesn't support decimals.

**Comment by greg-schroeder** [comment]
I don't know, according to the internet it does support decimals so I'm not really sure where that's coming from. I'll ask the team though.

**Comment by eh2077** [comment]
Not overdue, we're waiting for clarification from team

**Comment by greg-schroeder** [comment]
discussion: https://expensify.slack.com/archives/C01SKUP7QR0/p1721862196701789

**Comment by mallenexpensify** [comment]
We're going to close this per[ the internal discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1721901142396509?thread_ts=1721862196.701789&cid=C01SKUP7QR0). From Tom
> I agree it’s a little weird how we take the default USD distance rate and convert it into the workspace currency (so in this case it comes out at 0.7 IQD when you enable distance, and that currency likely starts at 1 or something), but that’s consistent with what we’ve been doing for years across OldDot.
In reality, I think anyone who is going to be using distance rates in foreign countries will enable the feature and immediately change the rate to what’s accurate in their local currency when setting it up.
So I think we can just close this and not worry about it, as it has very minimal impact in reality. :+1:
