### ISSUE TITLE
Workspace - Composer in workspace chat is not hidden after deleting the workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace
3. Go to workspace chat
4. Go to Account settings > Workspaces
5. Delete the workspace
6. Go back to workspace chat.

## Expected Result:
The composer in the workspace chat will be hidden because the chat is archived

## Actual Result:
The composer in the workspace chat is not hidden when the chat is archived

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4c114bd3-8369-4292-95b7-2eadccfc95d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by anmurali** [comment]
Cannot reproduce
<img width="1451" alt="image" src="https://github.com/user-attachments/assets/c4bb099b-f35f-4446-86c1-282a9323caed">
