### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Workspace - Fallback avatar in workspace chat is clickable and leads to not here page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44853]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Go to workspace settings > Members
4. Invite a non-existing user
5. Go to workspace chat with the invited user
6. Click on the chat header
7. Click on the fallback avatar (invited user)

## Expected Result:
The fallback avatar should not be clickable

## Actual Result:
The fallback avatar is clickable and leads to not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3ae651c8-420d-49cf-832e-6b279ba781bb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189b738ae283ab8e4</li>
        <li>Upwork Job ID: 1811060566160624462</li>
        <li>Last Price Increase: 2024-07-17</li>
<li>Automatic offers: </li>
<ul>
<li>neonbhai | Contributor | 103172276</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by neonbhai** [comment]
> if icon.source is Expensicons.FallbackAvatar, it always leads to not found page?

Confirmed! Shows not found in all contexts (1:1, group chats and workspace rooms) 

> there's no other case of showing not found page?

Confirmed, unable to find other case where the avatar leads to not found page

cc: @aimane-chnaif

**Comment by dangrous** [comment]
Yep, that works for me!

**Comment by neonbhai** [comment]
Raising PR soon!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by neonbhai** [comment]
> Issue not reproducible during KI retests. (First week)

The flow is still broken, now we see infinite spinner on the modal. Raising PR to disable navigation according to proposal [here](https://github.com/Expensify/App/issues/44853#issuecomment-2209361395)

**Comment by miljakljajic** [comment]
@aimane-chnaif owed 250 for their work reviewing this issue

**Comment by miljakljajic** [comment]
@neonbhai has been paid in Upwork

**Comment by miljakljajic** [comment]
Do we need a regression test?

**Comment by dangrous** [comment]
couldn't hurt!

**Comment by miljakljajic** [comment]
@neonbhai can you outline some regression test steps here?

**Comment by miljakljajic** [comment]
Thank you!

**Comment by zanyrenney** [comment]
hey @aimane-chnaif apologies about you getting forgotten!

**Comment by zanyrenney** [comment]
Have sent you another invite for it - https://www.upwork.com/nx/wm/offer/104306643

**Comment by zanyrenney** [comment]
bump @aimane-chnaif please accept
