### ISSUE TITLE
Login – Hmm… page opens shortly when navigate to IOU via link while logged out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44851]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4693610
**Email or phone of affected tester (no customers):** ponikarchuks+74724@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with Gmail account
3. Open any chat
4. Create a IOU in a conversation
5. Navigate to the IOU report (conversation)
6. Copy the URL
7. Log out of the app
8. Navigate to the IOU URL
9. Log in

## Expected Result:
Verify you're redirected to the correct IOU report after login

## Actual Result:
Hmm… page opens shortly before you're redirected to the correct IOU report after login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
**_Issue can be seen exactly at second 49._** 
https://github.com/Expensify/App/assets/44479856/88f2a143-e783-4f6f-84c6-2670fa49ff98

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
I haven't had a chance to look at this, will come back to it on Monday

**Comment by VictoriaExpensify** [comment]
Hey @lanitochka17 I'm having trouble seeing the issue from your screen recording, I couldn't see a "Hmm" page appear. Can you please tell me the exact time I'm looking at?

**Comment by VictoriaExpensify** [comment]
https://expensify.slack.com/archives/C9YU7BX5M/p1720486481100349

**Comment by isagoico** [comment]
@VictoriaExpensify Just uploaded the correct video to the issue. The bug can be seen exactly at second 49.

**Comment by VictoriaExpensify** [comment]
Oh that is a very quick blip! I will come back to this and attempt to recreate in the morning

**Comment by VictoriaExpensify** [comment]
Hmm I'm having trouble reproducing this one. @isagoico can we please check if @lanitochka17 is still able to reproduce the issue?

**Comment by kavimuru** [comment]
Bug is fixed

https://github.com/user-attachments/assets/bbeb8de9-0ddd-4268-85fc-2420d81e6081

**Comment by VictoriaExpensify** [comment]
Thanks @kavimuru! Closing this one out
