### ISSUE TITLE
mWeb - Tax - With Workspace currency IQD, creating expense unable to erase digits in tax amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44854]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4694940
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: As admin select IQD as Workspace currency and have enabled tax option
1. Go to https://staging.new.expensify.com/home
2. Login as employee
3. Tap Workspace chat
4. Tap plus icon and select submit expense
5. Enter an amount and tap next
6. In confirmation page, tap show more
7. Tap tax amount
8. Keep cursor in between a digit and try to erase a digit by tapping <
9. Note user unable to erase digits in tax amount and amount is shown in decimals
10. Change currency to INR
11. Now again tap tax amount
12. Keep cursor in between a digit and try to erase a digit by tapping <
13. Note user can erase a digit in tax amount

## Expected Result:
With Workspace currency IQD, creating expense user must be able to erase digits in tax amount

## Actual Result:
With Workspace currency IQD, creating expense unable to erase digits in tax amount but with INR user able to erase digits in tax amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e0642fed-a683-4310-8bc9-caba3358bf7a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by zanyrenney** [comment]
Thanks team. As that issue is now merged, let;s close this out!
