### ISSUE TITLE
[HOLD for payment 2024-07-24] LHN not displayed after page refresh from settings page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44860]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1720062549074999

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Settings > About
3. Refresh the page
## Expected Result:
Page reloads with out any issue
## Actual Result:
LHN menu not displayed until navigated to other menu icon
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/4e9d1846-c1fa-4a64-92a8-9aa017da1732

https://github.com/Expensify/App/assets/38435837/59988534-303d-43c1-9f52-e2a91f63d275

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by sonialiap** [comment]
Payment summary:
- @ShridharGoel $250 - offer sent in upwork
- @suneox  $250 - offer sent in upwork

**Comment by sonialiap** [comment]
This issue was Critical and High Priority so I've adjusted the payouts to $500
