### ISSUE TITLE
Member was already invited but doesn't show in the workspace list

### ISSUE THREAD

**Issue by carlosmiceli** [Expensify/App#44873]
Invited member, confirmed he can chat in the workspace, but doesn't show in the list of members.

<img width="1343" alt="Screenshot 2024-07-04 at 6 02 40 PM" src="https://github.com/Expensify/App/assets/1166066/c1426d71-c831-423b-ae60-9b8e3c552005">

**Comment by twisterdotcom** [comment]
Pretty sure we hide @expensify.com or @team.expensify.com members from policy members lists because of how we designed Account Managers and Guides: https://github.com/Expensify/App/blob/77d380ce7d1fcaad2045a3c590dc16a1363d4cd1/src/pages/workspace/WorkspaceMembersPage.tsx#L334
