### ISSUE TITLE
Hybrid app- Inbox task have wrong color in dark mode

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44877]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720050676912359

## Action Performed:
1. Launch the hybrid app in dark mode
2. Tap on the "Here's the list of reports that need your attention" inbox task
## Expected Result:
App displayed as per settings (Dark mode)
## Actual Result:
Wrong coloring for the inbox task
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/Expensify/App/assets/38435837/a1c7e432-553f-4fbf-ad28-d38a1df60cef" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/e16f4bbf-29fe-4fe5-9372-47debbac639e" width="40%" height="40%">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
Looking into this!

**Comment by staszekscp** [comment]
Actually I've managed to prepare a [fix](https://github.com/Expensify/Mobile-Expensify/pull/12822) while building Android to test other stuff 😄

**Comment by AndrewGable** [comment]
Fixed in 9.0.5.9

![IMG_6758](https://github.com/Expensify/App/assets/2838819/cf5daf28-abdc-4dc7-9224-e6c6c75e3aea)
