### ISSUE TITLE
Report - Conversation is not automatically bottom-aligned after IOU payment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4696819
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open New Expensify app
2. Send a manual IOU to the primary device
3 On the primary device, navigate to the conversation with the received IOU
3. Press the "Pay XXX elsewhere" button

## Expected Result:
The conversation should automatically level down after the IOU is paid.

## Actual Result:
Conversation is not automatically bottom-aligned after IOU payment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e79a9716-7ef5-4ba5-be7c-1d8ade353e4b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-bills.

**Comment by VictoriaExpensify** [comment]
Hmm this seems super minor, especially since it appears to level down once you touch on the device. I don't think this is worth our effort just at the moment.
