### ISSUE TITLE
[Hold PR #44321] [Payment card / Subscription] Add GBP back to the Add Payment Card selector. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#44896]
Created this issue to remind us to do this when the 3DS/SCA flow is complete. 

Todo: Revert [this PR](https://github.com/Expensify/App/pull/44858) to bring back GBP. More context [here](https://github.com/Expensify/App/issues/44852).

**Comment by blimpich** [comment]
Should be handled by [this PR](https://github.com/Expensify/App/pull/44321#issuecomment-2209451310) but good to have an issue open to track this to make sure it all gets reverted, not just a portion of it.

**Comment by trjExpensify** [comment]
Ah cool, maybe @waterim can comment here, and we can link that PR to this issue if we're going to take care of it there.

**Comment by waterim** [comment]
Hey Im Artem from Callstack and will worm on this issue!

**Comment by trjExpensify** [comment]
Wiggle away, man! 😄

**Comment by blimpich** [comment]
🪱

**Comment by trjExpensify** [comment]
Still holding on the 3DS work.

**Comment by blimpich** [comment]
This was completed by https://github.com/Expensify/App/pull/44321
