### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] Distance - The map is centered on the user if it is not possible to create a route

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4695012
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Prerequisites:
Create a Workspace on behalf of the administrator, invite an employee to it.

Steps:
1. Open [https://staging.new.expensify.com/.](https://staging.new.expensify.com/)
2. Log in with your employee account
3. Navigate to the workspace room
4. Tap on + Menu -> Submit expense -> Distance.
5. Enter a start location in Hawaii
6. Enter a finish location in San Diego
7. Tap the "center-me" button

## Expected Result:
When you click on the "center-me" button, the map should center on waypoints, even if there is no way to create a route

## Actual Result:
When you click on the "centre-me" button, the map is centred on the user's location, if it is not possible to create a route

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0bc523b3-3579-4e62-80b8-5a7754849826

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01caae7463e233bb94</li>
        <li>Upwork Job ID: 1811060493662079823</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103143669</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The map is centered on the user position instead of the waypoints if the route is impossible to create.

### What is the root cause of that problem?
Currently, we only center on the waypoints if there is a `directionCoordinates` exists and there is at least 2.
https://github.com/Expensify/App/blob/1f0a462d722d7d5b89319e01bd9c2ab8bfba9301/src/components/MapView/MapView.website.tsx#L193-L211

It's coming from the transaction routes coordinates data which is retrieved from the GetRoute/Draft, but if it's impossible to create the route, then the data will be empty.
https://github.com/Expensify/App/blob/1f0a462d722d7d5b89319e01bd9c2ab8bfba9301/src/components/DistanceRequest/DistanceRequestFooter.tsx#L112

If it's empty, then we center on the current user position.

### What changes do you think we should make in order to solve the problem?

It's possible to center the waypoints with the coordinate from the selected waypoints itself, so, I propose to update the condition so it centers on the waypoints if the selected waypoints contain the coordinate.

```
const waypointCoordinates = waypoints?.map((waypoint) => waypoint.coordinate) ?? [];
if (waypointCoordinates.length > 1 || (directionCoordinates?.length ?? 0) > 1) {
    // center logic
}
```

**Comment by c3024** [comment]
@bernhardoj 's proposal [here](https://github.com/Expensify/App/issues/44890#issuecomment-2211136667) looks good to me!

🎀 👀 🎀 C+ Reviewed

**Comment by MonilBhavsar** [comment]
Looks good!

**Comment by bernhardoj** [comment]
PR is ready

cc: @c3024

**Comment by miljakljajic** [comment]
Payment summary for @bernhardoj :

Owed 250 for their work reviewing this PR

**Comment by miljakljajic** [comment]
@c3024 I have paid you in upwork. Do we need a regression test for this PR? Please complete the checklist above when you can

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by c3024** [comment]
I'll complete the checklist in an hour.

**Comment by miljakljajic** [comment]
@c3024 bump on this when you can today so we can get it closed out

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #40759
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/bernhardoj/Expensify/commit/be55619a8a50ffc924b90304cfd58630732c9a5e#r144802233
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because it does not appear that it could have been caught earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes

**Comment by c3024** [comment]
### Regression Test Proposal

1. Open FAB > Submit expense > Switch to Distance tab
2. Select both waypoints that will result in an impossible route to create (e.g., San Diego and Hawaii)
3. Move the map away from the waypoints
4. Press the center map button
5. Verify the map is centered between the selected waypoints

**Comment by c3024** [comment]
[Here](https://github.com/Expensify/App/issues/44890#issuecomment-2258071793) are the regression test steps.

**Comment by miljakljajic** [comment]
Thank you @c3024!
