### ISSUE TITLE
Chat – Android - App crashes when edit Ad-hoc link address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a542@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open any chat
2. Send this link https://ad-hoc-expensify-cash.s3.amazonaws.com/android/41115/index.html
3. Tap on the send message to open menu> Select Edit
4. Start editing this message ( delete some letters, send the message..)

## Expected Result:
Sent message should be successfully edited

## Actual Result:
App crashes when edit Ad-hoc link address

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/251fb3e0-24e3-486e-b4be-64cd3e1a1d19

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Android <> ios bug swap

**Comment by jliexpensify** [comment]
Cannot repro on 9.0.4-7, editing the link works for me. Closing because it's just one link that may only be affecting one tester.
