### ISSUE TITLE
[$250] Chat - Self DM page flashes after deleting tracked expenses and returning online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+uo0704@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:

1. Open Self DM
2. Go Offline(Airplane mode)
3. Tap “+” and select track expense
4. Enter any amount and submit tracked expenses
5. Tap and hold tracked expense, and delete expense
6. Go Online(exit airplane mode)
7. Observe self dm chat.

## Expected Result:
After returning online, tracked expense should be removed and chat should have no problems

## Actual Result:
Self DM chat flashes and twitches 3 times after returning online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/521a8872-6714-4bb1-9f15-fc89d489f3c2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b74190174718a3a</li>
        <li>Upwork Job ID: 1810618431124699886</li>
        <li>Last Price Increase: 2024-08-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by m-natarajan** [comment]
Still reproducible with slightly different steps:


https://github.com/user-attachments/assets/404cbb68-ec62-4209-8a83-5593092de58d

**Comment by sonialiap** [comment]
Thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sonialiap** [comment]
Sounds good to close
