### ISSUE TITLE
[Payment card / Subscription] There is no Retry payment button but payment failed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44917]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.4-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/44268
**Email or phone of affected tester (no customers):** irvgut7@gmail.com and irvgut7+050724@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
NewDot
1. Go directly to subscription page - https://staging.new.expensify.com/settings/subscription
2. Add a payment card if you don't have it
3. Click to Subscriptions (we should go to OldDot)

OldDot:

4. Subscribe to Expensify.org on Workspaces page
5. Go to Settings>Account>Payments
6. Scroll down (you should see that payment failing)

7 Go back to NewDot and click `Retry payment`

## Expected Result:
The user should see the `Retry payment` button.

## Actual Result:
When user returns to NewDot, he does not see `Retry payment` button but payment failed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/bcf60cc8-9aa9-439f-8518-c1dd996faed0

https://github.com/Expensify/App/assets/115492554/7affac44-8b3c-43b0-90ae-e627715bc937

![IMG_4028](https://github.com/Expensify/App/assets/115492554/de5a633b-5eea-4ad6-bd55-11bfc5a914d1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
this is behind beta so not a blocker @blimpich in case you could handle this

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
The added payment card is not displayed in production.
![image](https://github.com/Expensify/App/assets/115492554/2bb4df97-1909-4de1-b5e2-09a863ca3cbc)

**Comment by blimpich** [comment]
Picking up at this is related to the subscription project.

**Comment by blimpich** [comment]
This is probably an internal issue. Going to label this as an internal hot pick for now. 

It's possible that this is a frontend issue, haven't investigated enough to say for 100% sure.

**Comment by trjExpensify** [comment]
Looking at the steps: 

> OldDot:
>Subscribe to Expensify.org on Workspaces page
>Go to Settings>Account>Payments
>Scroll down (you should see that payment failing)

... adding personal/corporate karma donations were out of scope of the project, so I wonder if we aren't getting updates for this failed billing scenario specifically or if it's paying your "normal" Expensify subscription. So it would be good to: 

1. Test if `Retry payment` is missing for a subscription to Expensify NOT corporate/personal karma
2. If not, it's just related to corporate/personal karma donations, make that clearer in the issue. 

CC: @MitchExpensify

**Comment by MitchExpensify** [comment]
1. I don't think we need to have a "Retry billing" banner for failed corporate karma payments in NewDot. 
2. The failed July 5th payment looks to be on an individual subscription which could be a factor
<img width="822" alt="image" src="https://github.com/Expensify/App/assets/36425901/4ffd67c3-2c69-4b45-9270-bf4c04c6be50">
<img width="705" alt="image" src="https://github.com/Expensify/App/assets/36425901/11e2c8bb-8fac-469e-a996-7849a18bc5f5">

**Comment by izarutskaya** [comment]
Both testing accounts are the owners of workspaces. Please check my videos. Thanks

https://github.com/Expensify/App/assets/115492554/d5aa23dc-68f4-4805-a538-ff134b155b18


https://github.com/Expensify/App/assets/115492554/0c69517b-70ea-4083-9092-aebca8f685dc

**Comment by MitchExpensify** [comment]
Got it, the $4.99 charge is for an individual subscription so I don't think there is a bug here as nothing I can see related to a group workspace
