### ISSUE TITLE
mWeb-Tag-When dependent tags are being disabled, "tag no longer valid" message is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4694802
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/hom
2. Login as employee
3. Open Workspace chat
4. Create an expense selecting category and dependent tags
5. Now in other device open admin account
6. Disable the category and all dependent tags option
7. Now as employee, open the expense

## Expected Result:
When dependent tags are being disabled, "tag no longer valid" message must be shown

## Actual Result:
For category after disabled "category no longer valid" message shown but for dependent tags no message displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/83b5deca-ffb8-48de-b6a5-6f5705dcf6b6

https://github.com/Expensify/App/assets/78819774/84e97238-14f0-4a6d-b227-2e7f7a74f711

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @yuwenmemon</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by twisterdotcom** [comment]
Okay, making `Internal`

**Comment by twisterdotcom** [comment]
No volunteers yet. Not really a hot pick for now.

**Comment by twisterdotcom** [comment]
Asking for some help in wave-control: https://expensify.slack.com/archives/C06ML6X0W9L/p1722599730089979

**Comment by twisterdotcom** [comment]
Going to try to consolidate my dependent tag issues and find a single assignee

**Comment by yuwenmemon** [comment]
Will look at this as a part of the tags project soon.

**Comment by twisterdotcom** [comment]
Same as above.

**Comment by yuwenmemon** [comment]
No update but I think this actually might just be solved with the violations project, right @twisterdotcom?

**Comment by twisterdotcom** [comment]
Possible. Do we have a PR to link to?

**Comment by yuwenmemon** [comment]
No I was just thinking about it in the abstract 😂 

The violations project isn't complete yet either. But a man can dream...

**Comment by twisterdotcom** [comment]
Shall we just close this?

**Comment by yuwenmemon** [comment]
Yeah
