### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] IOU - Clicking back "on page not found" page takes you to a workspace page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44924]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife+stest@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to a 1:1 Conversation. Make sure your seeing both account at the same time
2. As user A request money from User B
3. As user A go the IOU report that was just created and click on the Plus button to bring the menu
4. While the menu is still open Go to User B and Pay the expense
5. As user A click on "submit expense" on the menu that was opened in step 3.
6. Notice the error page is shown.
7. Click the back button found on the error page

## Expected Result:
Clicking back takes you to the IOU report page

## Actual Result:
Clicking back "on page not found" page takes you to a workspace page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d091beff-58d1-44ab-8466-bdaadcbae82d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f96054ddd649966</li>
        <li>Upwork Job ID: 1811060426930703182</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103146401</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by miljakljajic** [comment]
@thesahindia is owed 250 for their work reviewing this issue

**Comment by miljakljajic** [comment]
@thesahindia do we need a regression test for this issue?

@nkdengineer paid in upwork

**Comment by miljakljajic** [comment]
Thank you!

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia based on [this payment summary](https://github.com/Expensify/App/issues/44924#issuecomment-2273010458)
