### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Workspace - The tag and category lists lack consistent alphabetical order

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44922]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife+stest@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to workspace/or create one > Categories
2. Click on Add category
3. Now add Categories. Make some categories start with Capital letter and others with Small letter
Notice that categories are listed Alphabetically with Capital letters coming first and then small letters.
4. Repeat step 2 and 3 for Tags. (You might have to enable tags by going to more feature)
Notice that tags are also listed the same way as Categories are listed.
5. Go to the workspace chat > start submitting an expense
6.Before submitting the expense Click on the show more
7. Go to categories. Notice that here small letter comes first
8. Go to tags. Notice small letters are show last below all the capital letters

## Expected Result:
Consistent alphabetical order

## Actual Result:
Inconsistent alphabetical order

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d6bffa3d-546a-4f25-82a2-ef53a402e7a2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f0c5d89e0679c03</li>
        <li>Upwork Job ID: 1810477124215778147</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103053435</li>
<li>dominictb | Contributor | 103053437</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by VictoriaExpensify** [comment]
I agree this is a bug that should be fixed, but I want to chat with the team about the desired behaviour here. I _think_ Expensify Classic default everything to be capitalised and I have never come across anyone who wasn't happy with this, so I wonder if that is the best way to resolve the issue.

**Comment by VictoriaExpensify** [comment]
Alright, tested this in OldDot and it is inconsistent there, too 😅 

I think we should get some design input on this one.

**Comment by VictoriaExpensify** [comment]
Personally, I can't think of any reason why you would have a need for upper and lower case categories and tags. I kind of think we should default these all to be capitalised and, that way, you won't end up with two with the same name.

**Comment by VictoriaExpensify** [comment]
Hmm actually, I would sorry this would break something with our integrations since Tags and Categories can be imported from there.


Generally, when listed alphabetically, the word with the capital letter comes first. So let's keep the platform consistent with that standard

**Comment by chiragsalian** [comment]
Thanks for the discussion, let's go with @dominictb's proposal and use `lodashSortBy`. When using it can you add a comment explaining why we are using lodash with a link to [this](https://github.com/Expensify/App/issues/33650#issuecomment-1919599578) so that its not forgotten. Feel free to create a PR.

**Comment by chiragsalian** [comment]
Not overdue melvin, on hold for payment

**Comment by VictoriaExpensify** [comment]
@ishpaul777 - I'll organise payment once you have complete the checklist

**Comment by VictoriaExpensify** [comment]
**Payment Summary:**

Contributor: @dominictb paid $250 [via Upwork]([Upwork job](https://www.upwork.com/jobs/~013f0c5d89e0679c03))
Contributor+: @ishpaul777 paid $250 [via Upwork]([Upwork job](https://www.upwork.com/jobs/~013f0c5d89e0679c03))

Thanks for your work on this bug!
