### ISSUE TITLE
[$250] Delay in showing LHN and not found page in report screen when switching between bottom tabs

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#44949]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Log into a heavy account
2. Switch from Chats to Settings
3. Switch back to Chats
4. Repeat

## Expected Result:
Describe what you think should've happened

There should be little to no delay when rendering the individual pages

## Actual Result:
Describe what actually happened

Seems like there are some extra renders or we are waiting longer for rendering something

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Staging:

https://github.com/Expensify/App/assets/36083550/8be41bd2-ab38-4758-8834-ce6f0e8528fd

Production:

https://github.com/Expensify/App/assets/36083550/0ad0d8f1-6d24-4751-9698-d48e539050b7

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0321979061e3e17</li>
        <li>Upwork Job ID: 1810252490706554621</li>
        <li>Last Price Increase: 2024-07-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by Julesssss** [comment]
After catching up on the discussion [here](https://expensify.slack.com/archives/C05LX9D6E07/p1720442298684519?thread_ts=1720432564.597379&cid=C05LX9D6E07), I lean towards not blocking on this. 

For now we will continue, but if this ends up being the last blocker I will continue. It is a worse experience for large accounts, but not a huge deal IMO.

**Comment by mountiny** [comment]
I agree, seems like they did not find anything that would make the staging noticeably slower than production, it might have been caused by something else for me. There are already some PRs that should improve this

**Comment by mountiny** [comment]
At this point, I am not sure if I am able to reproduce, have you been able to notice anything like this @ishpaul777 ?

**Comment by isabelastisser** [comment]
Thanks, team! Closing this.
