### ISSUE TITLE
IOU - Title change is not reflected in header and details section

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44962]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** New feature
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to p2p chat
2. Submit a manual expense
3. Click on the IOU preview component
4. Click on report header > Title
5. Edit title & click Save

## Expected Result:
Change in title should be reflected in report header and details section

## Actual Result:
Change in title is not reflected in report header and details section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8104035b-2613-4755-8e90-930109801c47

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by trjExpensify** [comment]
>I think Title field should not editable in P2P chat. i'll raise a quick PR to resolve this since this comes from a PR i reviewed, once we confirm

Right, report titles are a feature on workspaces whereas iouReports are not on workspaces.

**Comment by danieldoglas** [comment]
removing backend blocker on this issue.

**Comment by Julesssss** [comment]
Ah, this appears to have been resolved by a different deploy blocker fix.
