### ISSUE TITLE
[$250] Thread – Unable to leave thread in a task detail.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44964]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v9.0.5-3

**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4700550
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Send a message
5. Right click on the message and select Reply in thread
6. Send a message in a thread
7. Click on the header
## Expected Result:
Leave thread option is present in a task detail
## Actual Result:
Leave thread option is missing in a task detail

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/9932b490-414e-407b-bab1-4c9b11962dc7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186cdebe249073b07</li>
        <li>Upwork Job ID: 1810358159239707374</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103047193</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by m-natarajan** [comment]
@abekkala FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no option to leave thread in report details page.

### What is the root cause of that problem?
The condition of showing the leave button requires the report to not be a thread.
https://github.com/Expensify/App/blob/e0ccba51a40d67283b658aeffa3040fb2eb45795/src/pages/ReportDetailsPage.tsx#L243-L244

Previously, we had a 3-dot button that shows the leave option for the thread, but now it's removed, but the leave button condition isn't updated yet.

### What changes do you think we should make in order to solve the problem?

I propose that we just use `ReportUtils.canLeaveChat` function to check whether we can leave a report or not. Then, we can move the other current conditions to `canLeaveChat`.
```
const shouldShowLeaveButton = ReportUtils.canLeaveChat(report, policy)

function canLeaveChat(report: OnyxEntry<Report>, policy: OnyxEntry<Policy>): boolean {
    if (isGroupChat) return true;
    if (isPolicyExpenseChat && !report.isOwnPolicyExpenseChat && !isPolicyAdmin) return true;
    ...
```

Last, we need to update the `leaveChat` logic so that leaving a thread will call `leaveRoom` instead of `leaveGroupChat`.
https://github.com/Expensify/App/blob/e0ccba51a40d67283b658aeffa3040fb2eb45795/src/pages/ReportDetailsPage.tsx#L224-L232

We can do that by switching the check.
```
if (isGroupChat) {
    leaveGroupChat()
    return;
}
leaveRoom()
```

**Comment by puneetlath** [comment]
I don't think this needs to block the deploy. Going to demote it and make it external.

**Comment by akinwale** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/44964#issuecomment-2214294438) works here.

🎀👀🎀 C+ reviewed.

**Comment by puneetlath** [comment]
Sounds good. I like consolidating the logic into ReportUtils.canLeaveChat.

**Comment by bernhardoj** [comment]
PR is ready

cc: @akinwale

**Comment by abekkala** [comment]
waiting on PR Review @akinwale

**Comment by abekkala** [comment]
deployed to production Jul 23

**Comment by akinwale** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

This was a regression from https://github.com/Expensify/App/pull/44252.

> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
* Launch Expensify
* Open a chat report
* Send a message
* Reply in the thread of the message that was sent
* Click or tap on the chat header
* Verify that the Leave option is displayed in the menu

Do we agree 👍 or 👎?

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JULY 30

- Fix: @bernhardoj [$250] payment via New Dot
- PR Review: @akinwale [$250] [Offer](https://www.upwork.com/nx/wm/offer/103047193)

**Comment by abekkala** [comment]
@akinwale payment sent and contract ended - thank you!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
