### ISSUE TITLE
[$250] Workspace - App crashes when clicking on room header of #admin room that has system message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to #admin.
4. Click on the room header.
5. Note that the app does not crash.
6. Go to workspace settings > Categories.
7. Delete a category to trigger system message in #admin.
8. Go to #admin.
9. Click on the room header.

## Expected Result:
App will not crash.

## Actual Result:
App crashes when clicking on room header of #admin room that has system message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/33dbde80-e7a0-4102-99f5-3b8077f28762

[Bug6535810_1720442352877!staging.new.expensify.com-1720436555090.txt](https://github.com/user-attachments/files/16130396/Bug6535810_1720442352877.staging.new.expensify.com-1720436555090.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f0f53207293d92db</li>
        <li>Upwork Job ID: 1811121250500831709</li>
        <li>Last Price Increase: 2024-07-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by slafortune** [comment]
Thanks everyone - closing 👍
