### ISSUE TITLE
 Expensify card - "It's not here" + console errors after enabling Expensify card

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44977]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.5-3
**Reproducible in staging?:** y
**Reproducible in production?:** no, "Expensify Card" option is not in `more features` page
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Log in with a new expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable Expensify Card
6. Click on the "Issue new card" button

## Expected Result:
There shouldn't be any errors while enabling Expensify card. I should be able to reach the member list with the "Issue new card" button.

## Actual Result:
"Hmm it's not here" error appears soon after enabling Expensify card. Around 11 "POST https://staging.expensify.com/api/EnablePolicyExpensifyCards?
404 (Not Found)" console errors appear right after enabling. Unable to click on "Issue new card" button
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Bug6535870_1720445116315!staging.new.expensify.com-1720444318593.txt](https://github.com/user-attachments/files/16130890/Bug6535870_1720445116315.staging.new.expensify.com-1720444318593.txt)

https://github.com/Expensify/App/assets/38435837/bc1b484b-22aa-42f7-8200-38c34e52107f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@youssef-lr FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by youssef-lr** [comment]
Not a blocker, the endpoint we're calling when we enable the card is not live yet https://github.com/Expensify/Web-Expensify/pull/42651, cc @MariaHCD. I believe this feature is hidden behind a beta as well.

**Comment by MariaHCD** [comment]
Yes, not a blocker. We can close this out. We can QA this flow once https://github.com/Expensify/Web-Expensify/pull/42651 is deployed.
