### ISSUE TITLE
Report fields - The report field after deleted offline is still clickable

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44974]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Found when validating  https://github.com/Expensify/App/pull/44493
**Version Number:** 9.0.5-3
**Reproducible in staging?:** y
**Reproducible in production?:** no, this is new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields (Enable on More features if not yet).
3. Add any type of report field.
4. Go offline.
5. Click on the report field.
6. Click Delete.
7. Delete the field.
8. Click on the deleted report field.

## Expected Result:
The report field after deleted offline should no longer be clickable.

## Actual Result:
The report field after deleted offline is still clickable.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/ef989d7d-2a63-4a86-b4ef-0b84e2f48cfd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@strepanier03 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
Taking to over as I work on the project, this is still behind beta so not a blocker

@waterim @rezkiy37 who can take this?

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and this one will addressed [here](https://github.com/Expensify/App/pull/44729)

**Comment by rushatgabhane** [comment]
PR reviewed and merged
