### ISSUE TITLE
Report fields - Blank list is shown briefly after deleting all report fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44983]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go to Report fields (enable in More features if not yet)
4. Add a report field
5. Click on the report field
6. Click Delete
7. Delete the report field

## Expected Result:
The report field page will show the empty state screen immediately (like it does on Categories and Tags page)

## Actual Result:
The report field shows blank first briefly before showing empty state screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3eaffdeb-a291-4df9-8377-3d1a3c77d0db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@francoisl  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by francoisl** [comment]
This is probably from https://github.com/Expensify/App/pull/44493, not going to block on this as it's not breaking anything.

**Comment by mountiny** [comment]
Going to handle this with @rezkiy37 and @waterim as we are working on the project

**Comment by mountiny** [comment]
The report fields is behind beta still

**Comment by waterim** [comment]
Hello, Im Artem and would like to help with this issue!
This issue will be fixed [here](https://github.com/Expensify/App/pull/44729)

**Comment by rushatgabhane** [comment]
PR reviewed and merged
