### ISSUE TITLE
Login – Expensify chat is missing in LHN if log in using Get paid back by my employee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44984]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4700941
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. In Onboarding modal select Get paid back by my employee
4. Enter your name and Save
5. Verify Expensify chats is not present in LHN
6. Click on Find and select Expensify chat
7. Observe LHN

## Expected Result:
Expensify chat is present in LHN

## Actual Result:
Expensify chat is missing in LHN if it’s opened from Find, when log in with new account using Get paid back by my employee in Onboarding menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/126bbd13-a5ed-46f7-a0d2-002fc878248f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@lanitochka17 sorry, can you clarify what type of chat/s you're expecting to see here? Also, can you retest on the newest Staging version as well?

**Comment by jliexpensify** [comment]
Bump @lanitochka17 - can you clarify what type of chat/s you're expecting to see here? Also, can you retest on the newest Staging version as well?

**Comment by lanitochka17** [comment]
This issue is not reproducible on the latest build 9.0.6-2

https://github.com/user-attachments/assets/9d8fbfbe-4ef9-414e-b835-f95bb78b836b

**Comment by jliexpensify** [comment]
Closing this out then!

**Comment by lanitochka17** [comment]
Sorry for the confusion but the issue is repeated with the updated steps: 
1. Go to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Complete Onboarding modal
4. Observe the LHN
Or this issue is new one?

https://github.com/user-attachments/assets/a76e16e9-28e7-439c-9a39-edca335175c0

**Comment by jliexpensify** [comment]
@lanitochka17 you're trying to chat on `notifications@expensify.com` - this is not a real chat, this is our notifications system. If you click on that "chat", you're asked to speak to Concierge so I don't think this is an actual issue.
