### ISSUE TITLE
[HOLD for payment 2024-07-24] Add copy report onyx object to clipboard function on dev/staging

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#44994]
In order to make troubleshooting easier, let's add a new option to the right-click/long-press menu on reports in the LHN. The new option will be called `Copy Onyx data` and it will only be visible on dev/staging. 

Clicking on it will copy the Onyx data for the report object onto the user's clipboard. Without opening the report. 

![image](https://github.com/Expensify/App/assets/1371996/1c15cbc9-d82f-4da8-a2ea-13d6683d5548)

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by TMisiukiewicz** [comment]
I'm Tomasz from Callstack and I'd like to work on this issue

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I'll be working on this issue.

**Comment by puneetlath** [comment]
@ShridharGoel I'd like to get it out fast, so working with an agency contributor on it directly. That's why I didn't mark it external. Thanks for your interest though!

**Comment by puneetlath** [comment]
I believe @sobitneupane needs to be paid here. Right @sobitneupane?

**Comment by sobitneupane** [comment]
Yes @puneetlath. I reviewed the [PR](https://github.com/Expensify/App/pull/45079) linked with this issue.

**Comment by puneetlath** [comment]
Payment summary: 
- $250 - @sobitneupane - C+

Please request on NewDot @sobitneupane

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
