### ISSUE TITLE
 Expense - "Unapprove" option is available in report with deleted expense that has comments

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44991]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B
3. [User A] Go to transaction thread of one of the expenses, and add some comments
4. [User A] Delete the expense that has comments
5. [User B] Go to DM with User A
6. {User B] Click on the expense preview
7. [User B] Pay the report
8. [User B] Go to the report that has comments (expense deleted)
9. [User B] Click on the report header

## Expected Result:
"Unapprove" option should not appear since the expense is deleted, only comments are left in the report

## Actual Result:
"Unapprove" options shows up even though the expense is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2e55eb7b-9be4-46a6-94c3-4a5c46cc777e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@blimpich   FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by blimpich** [comment]
Looking into this

**Comment by blimpich** [comment]
Think I know what caused this, testing locally.

**Comment by blimpich** [comment]
Having trouble repro-ing locally.

**Comment by blimpich** [comment]
Was able to repro and confirm it stems from [this PR](https://github.com/Expensify/App/pull/44229)

**Comment by blimpich** [comment]
Demoting because this is edge case.

**Comment by blimpich** [comment]
@Beamanator @rushatgabhane assigned both of you as this is follow up for [this PR](https://github.com/Expensify/App/pull/44229) you worked on recently.

**Comment by rushatgabhane** [comment]
cool cool we have to check for deleted report here

https://github.com/Expensify/App/pull/44229/files#diff-409b0e2fb439856e9897b808014031ce244a427d116ed30f37a2e0117599adc4R202

**Comment by garrettmknight** [comment]
@rushatgabhane I don't think we should be showing Unapprove at the expense level to begin with.

**Comment by Beamanator** [comment]
Fix merged & CPing

**Comment by Beamanator** [comment]
This should be fixed already
