### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250]  Search - Payment confirmation modal appears stretched when paying held expenses from RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45002]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat as admin
3. Submit two expenses
4. Hold those two expenses
5. Go to Search > Shared
6. Click on the grouped expenses
7. Click Pay elsewhere

## Expected Result:
The payment confirmation modal will not appear stretched

## Actual Result:
The payment confirmation modal appears stretched

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4f706524-a297-4259-baa2-ea9fe2cbc1c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b37c63722e6c2f2</li>
        <li>Upwork Job ID: 1811444911776949843</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103097276</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jayeshmangwani** [comment]
@Krishna2323's [Alternative solution](https://github.com/Expensify/App/issues/45002#issuecomment-2215209803) of directly using the `isSmallScreenWidth` value from the `useResponsiveLayout` hook in DecisionModal loooks good to me.

For MoneyReportHeader and DecisionModal, we don't need to use the `shouldUseNarrowLayout` value to determine if the modal type is `BOTTOM_DOCKED` or `CONFIRM`.

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
@devguest07 Sorry for missing the edited timestamp.

@Krishna2323 Please do not raise the PR yet, as I need to discuss this case.

**Comment by jayeshmangwani** [comment]
> I'd like to bring your attention to the timeline of the proposed solutions. My proposal, which suggests directly using the isSmallScreenWidth value from the useResponsiveLayout hook in DecisionModal, was submitted before the selected alternative solution

I will re-review with timestamps and let you know.

**Comment by jayeshmangwani** [comment]
@Krishna2323 Why did you update your alternate solution after @devguest07 shared theirs Proposal?

I can see from the timestamp that you used their approach after they shared the Proposal.

**Comment by jayeshmangwani** [comment]
> But still the other proposal wasn't complete in that case also because it suggested to remove the prop from ProcessMoneyReportHoldMenu but it should be removed from DecisionModal

No, that's incorrect. The proposal is complete, in my opinion. but open for explanation

**Comment by jayeshmangwani** [comment]
> @jayeshmangwani, I have mentioned [here](https://github.com/Expensify/App/issues/45002#issuecomment-2215440172) that I have updated my proposal and added alternative.

But you updated the alternate proposal after another contributor shared a similar approach, right?

**Comment by jayeshmangwani** [comment]
> > @jayeshmangwani, I have mentioned [here](https://github.com/Expensify/App/issues/45002#issuecomment-2215440172) that I have updated my proposal and added alternative.
> 
> But you updated the alternate proposal after another contributor shared a similar approach, right?

@Krishna2323 thought on this ??

**Comment by jayeshmangwani** [comment]
> I had clearly mentioned it https://github.com/Expensify/App/issues/45002#issuecomment-2215440172.

You have mentioned it, but that's not the right thing to do if another contributor already has a similar approach and then we add something on top of the similar proposal.

**Comment by jayeshmangwani** [comment]
> do you think that the other proposal isn't similar to mine if we leave the prop removal part (which isn't necessary)? 

No, isn't similar

**Comment by jayeshmangwani** [comment]
> @devguest07 posted their proposal which states the same RCA and solution

I disagree with that.

**Comment by jayeshmangwani** [comment]
> please clarify whats the difference?

1. You proposed pass the isSmallScreenWidth prop to ProcessMoneyReportHoldMenu
2. @devguest07 proposed define isSmallScreenWidth on the `ProcessMoneyReportHoldMenu` and remove the props on component

**Following the proposed changes from devguest07 (14 minutes ago), you added that we should not pass the prop; instead, we can directly define the isSmallScreenWidth in the DecisionModal**

**Comment by jayeshmangwani** [comment]
@Krishna2323 ⬆️

**Comment by jayeshmangwani** [comment]
> Do you really think this is a major difference?

The major difference I see is that initially, you proposed changes that were all prop-based. Then, another contributor suggested a solution stating that we could directly define isSmallScreenWidth without passing it as a prop from ProcessMoneyReportHoldMenu. You then updated your alternate proposal to suggest defining isSmallScreenWidth within DecisionModal.



What I'm trying to say is that you updated your proposal after the other contributor's proposal, and it now looks similar approach to me. Instead of having unnecessary arguments, let's leave it to the internal engineers to decide. I was merely stating the fact that your proposal was updated after the other contributor's.

**Comment by francoisl** [comment]
I just reviewed the conversation and timestamps, thanks for your patience.

We missed the edit proposal timestamp and [this comment](https://github.com/Expensify/App/issues/45002#issuecomment-2215440172) indeed - sorry about that. For fairness, the assignment should have gone to @devguest07 in the first place though, so I'm going to reassign.

**Comment by jayeshmangwani** [comment]
@devguest07 I see that you have a draft PR. Feel free to open it for review.

**Comment by jayeshmangwani** [comment]
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/40570
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/40570#discussion_r1699095830
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **It's not needed; the issue can be caught during the review.**
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **We can skip regression test for this bug, not that impactful**
- [ ]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by miljakljajic** [comment]
@jayeshmangwani is owed 250 USD for their work on this issue

**Comment by miljakljajic** [comment]
@devguest07 whats your upwork profile?

**Comment by jayeshmangwani** [comment]
Requested as per https://github.com/Expensify/App/issues/45002#issuecomment-2262341697

**Comment by miljakljajic** [comment]
@devguest07 I get 
<img width="535" alt="image" src="https://github.com/user-attachments/assets/7b94c4ea-92cb-433a-9ea4-7dfb8558adb2">

Can you apply to the job on Upwork please?

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani

**Comment by miljakljajic** [comment]
I'll reopen when @devguest07's profile is unfrozen

**Comment by francoisl** [comment]
Yep sorry about the delay, going to ask internally.

**Comment by miljakljajic** [comment]
Sorry to miss these pings! @devguest07 can you accept the contract I sent over? and then DM me in slack when you've accepted it, I'll pay it immediately

**Comment by miljakljajic** [comment]
paid - offer extended on the other issue
