### ISSUE TITLE
 NetSuite - Infinite loading shows when trying to connect

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44661
## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account (Beta enabled)
3. Create a WS > Enable Accounting > Connect to Netsuite with valid credentials

## Expected Result:
User expects the connection to sync successfully

## Actual Result:
The user experiences infinite loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fd1ec622-7b80-4099-837d-f3829517598d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@bondydaa  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
cc @yuwenmemon @mananjadhav 

This is still behind beta so we can demote

**Comment by mananjadhav** [comment]
Yes and this is a backend issue. cc - @yuwenmemon This is what we posted on the thread that IS job is not running on connection but works fine on sync now.

**Comment by yuwenmemon** [comment]
Yeah, this is my main priority today.

**Comment by yuwenmemon** [comment]
Everything here is on prod, closing!
