### ISSUE TITLE
[HOLD for payment 2024-08-07] [Search v2.1] [App] Create advanced filters

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#45026]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc.

Holding on:
- [x] https://github.com/Expensify/App/issues/45025

cc @adamgrzybowski @Kicu @WojtekBoman

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by luacmartins** [comment]
Maybe for this one we can break it down into multiple PRs, maybe adding a couple of filters at a time

**Comment by Kicu** [comment]
yeah sounds good 👍 

Let me take care of this task, and I will start with small initial PR, after that if I see possibility of some parallel work, then we will divide this between me and Wojtek if that would make sense.

However I have a question: where do I get the values of some filters from? `In`, `Currency`, `Merchant` - are they somewhere inside Onyx easy to be used?

What about:
 - Tax
 - report ID
 - Category
 - Tag

And in general: should these filters values mostly be generated inside App using existing data, or come from backend?

**Comment by luacmartins** [comment]
These values should come from Onyx for now. So:

- `in`
- `currency` - reuse CurrencySelectionList component, [data source](https://github.com/Expensify/App/blob/4ecfa0f4970572fe7fc34864c0d4eb1e5865e013/src/components/CurrencySelectionList/index.tsx#L61-L63)
- `merchant` - text input, user can enter whatever they want
- `tax` - `policy_<id>.tax`. Maybe we can reuse [TaxPicker](https://github.com/Expensify/App/blob/4ecfa0f4970572fe7fc34864c0d4eb1e5865e013/src/components/TaxPicker.tsx)
- `category` - `policyCategories_`. Maybe we can reuse [CategoryPicker](https://github.com/Expensify/App/blob/4ecfa0f4970572fe7fc34864c0d4eb1e5865e013/src/components/CategoryPicker.tsx)
- `tag` - `policyTags_`. Maybe we can reuse [TagPicker](https://github.com/Expensify/App/blob/4ecfa0f4970572fe7fc34864c0d4eb1e5865e013/src/components/TagPicker/index.tsx)

For `tax`, `category` and `tag` we need to combine the data from all policies available in Onyx. I think to reuse the components as is, we might have to lift that Onyx connection and pass the data.

**Comment by luacmartins** [comment]
Ready to be worked on!

**Comment by Kicu** [comment]
Will start today, possibly bring 1 more person in because I feel this task can be done in parallel.

**Comment by MitchExpensify** [comment]
Reassigning as I'm heading on leave 🙇

**Comment by Kicu** [comment]
Will continue working on this task to bring in more PRs together with @Guccio163 
There are multiple filters to display so expect maybe 2-3 more PRs.

**Comment by Kicu** [comment]
asked a question here: https://docs.google.com/document/d/1G53Ebwl1XJx2ea2c0WO3rg1DmpGK8D0sMCRWvAM3D1o/edit?disco=AAABOsNsBWg 

if someone can take a look 🙏

**Comment by luacmartins** [comment]
@Kicu replied

**Comment by sonialiap** [comment]
Payment summary:
- @rayane-djouah $250 - offer sent in Upwork

**Comment by sonialiap** [comment]
Paid ✔️
