### ISSUE TITLE
[HOLD for payment 2024-08-09] [Search v2.1] [App] Create search results page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#45028]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=kix.d3qiq92y96z2) of the design doc.

Holding on:
- [ ] https://github.com/Expensify/App/issues/45027
- [ ] 
cc @adamgrzybowski @Kicu @WojtekBoman

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by WojtekBoman** [comment]
Hi! I'm going to work on that :)

**Comment by Kicu** [comment]
This is being worked on

**Comment by WojtekBoman** [comment]
I'm working on that

**Comment by ikevin127** [comment]
cc @bfitzexpensify For payment, in case this fell off your radar!

**Comment by ikevin127** [comment]
cc @bfitzexpensify For payments, in case this fell off your radar!

**Comment by bfitzexpensify** [comment]
Offer sent @ikevin127

**Comment by ikevin127** [comment]
@bfitzexpensify Accepted, thanks **Ben**!

**Comment by bfitzexpensify** [comment]
Cool, all paid out
