### ISSUE TITLE
[HOLD for payment 2024-08-05] [Search v2.1] [App] Use new query syntax

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#45027]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.888saqncimmk) of the design doc.

Holding on:
- [x] https://github.com/Expensify/App/issues/45025

cc @adamgrzybowski @Kicu @WojtekBoman

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by adelekennedy** [comment]
still on hold here

**Comment by luacmartins** [comment]
Ready to be worked on!

**Comment by adamgrzybowski** [comment]
@luacmartins Looks like something for me!

**Comment by adamgrzybowski** [comment]
I'm actively working on this one

**Comment by adamgrzybowski** [comment]
The draft is here https://github.com/Expensify/App/pull/45617. I hope to finish it tomorrow

**Comment by adelekennedy** [comment]
@rayane-djouah sent you an offer on Upwork! https://www.upwork.com/nx/enterprise-homepage/?offerRid=103425705&nav_dir=replace&teamUid=all_teams&tab=hire
