### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] [Search v2] [App] Create Search input parser

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#45024]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.xcr7yb16acwg) of the design doc.

cc @adamgrzybowski @Kicu @WojtekBoman 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103d4f4824bdb9c19</li>
        <li>Upwork Job ID: 1810781005103468270</li>
        <li>Last Price Increase: 2024-07-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by luacmartins** [comment]
done

**Comment by isogit123** [comment]
Hello @luacmartins Would you grant me access to the design doc? My email is aboutabl6@gmail.com

**Comment by luacmartins** [comment]
@isogit123 we already have people working on this issue.

**Comment by VictoriaExpensify** [comment]
@paultsimura could you please accept the job in Upwork? Let me know once you have an I will organise payment for you.

**Comment by VictoriaExpensify** [comment]
@paultsimura could you please accept the job in Upwork? Let me know once you have an I will organise payment for you.

**Comment by luacmartins** [comment]
Seems like we're done here then. Closing as per the comment above.
