### ISSUE TITLE
[Search v2] [Web-E] Add jsonQuery param

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#45023]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.fett753ojl2k) of the design doc.

**Comment by joekaufmanexpensify** [comment]
@luacmartins Is this one only the web E PR? If so, I'll prob unassign as I don't think I'm needed here.

**Comment by luacmartins** [comment]
Yea, this is only internal

**Comment by joekaufmanexpensify** [comment]
Cool cool. TY!

**Comment by luacmartins** [comment]
Done!
