### ISSUE TITLE
[Search v2.1][Auth] Deprecate old syntax code

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#45030]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.2p900egyd3l0) of the design doc.

Holding on:
- [x] https://github.com/Expensify/App/pull/46481

**Comment by luacmartins** [comment]
Still on hold

**Comment by JmillsExpensify** [comment]
Can we remove the hold now?

**Comment by luacmartins** [comment]
Not yet, the holding PR is still in draft. Also, this is just clean up work, so I think it's lower priority than the remaining filters.

**Comment by zanyrenney** [comment]
cc @luacmartins

**Comment by luacmartins** [comment]
Not yet

**Comment by zanyrenney** [comment]
Looks like the PR is merged, good to remove the hold @luacmartins ?

**Comment by luacmartins** [comment]
Yea, hold removed. Thanks!

**Comment by luacmartins** [comment]
@zanyrenney this is all internal work, so I'll unassign you.

**Comment by luacmartins** [comment]
This is done!
