### ISSUE TITLE
[Free trial] [BE] Send a message when free trial begins

### ISSUE THREAD

**Issue by chiragsalian** [Expensify/App#45032]
Problem
We've updated auth such that a free trial begins when a transaction is created. But to keep the PR simple we didn't send a message. 

Why is this important?
As part of the free trial design doc we'll want to send a message when free trial begins.

Solution
Send a message when free trial begins

**Comment by dannymcclain** [comment]
Do y'all need any design input on this? Feels like this isn't going to introduce any new/updated UI at all. Happy to hang around for reviewing, just want to make sure I understand what's going on with this one.

**Comment by trjExpensify** [comment]
Nah, s'all good. It's just an auto message in the Conci/Expensify DM. 👍
