### ISSUE TITLE
[HOLD for payment 2024-08-19] [Guided Setup Stage 3] Add the tooltip for Workspace Chat

### ISSUE THREAD

**Issue by deetergp** [Expensify/App#45046]
## Part of the Extend Onboarding to Invited Users project
Main issue: https://github.com/Expensify/Expensify/issues/392615
Doc section: https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.bfsayh3fuyk8
Project: [#wave-collect](https://github.com/orgs/Expensify/projects/129)

## Feature Description

When a user is invited to a Workspace as a non-admin, when they respond to the invitation email, they should be signed directly into the app and taken to their workspace chat. When viewing the chat for the first time, they should see a tool tip hovering above the **Create** button that says "Get started! Submit your first expense" that gets dismissed when they click on the button.

<img width="932" alt="Screenshot 2024-07-09 at 9 56 59 AM" src="https://github.com/Expensify/App/assets/766197/5b5beb4c-1ee0-48c6-89a7-6219c59808d2">

### Frontend Changes (from doc)
In order to know when to show the tooltip, look for an onyx key called workspaceTooltip with a property of shouldShow set to true. This property will only be sent on their first sign-in. Once they click on the Create button or mouse into the composer, we should dismiss the tooltip and set workspaceTooltip.shouldShow to false. It will not be sent again on subsequent sign-ins. See the [backend documentation](https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.cngii8v8xq9z) for more details.

### Backend Changes (from doc)

When a user has been invited to a workspace as a non-admin, we are going to want to show them a tooltip on their first signing encouraging them to submit their first expense. In order for the frontend to know this is their first sign-in we will check that their isInviteOnboardingComplete is false and inviteType is workspace and then also include an additional key in the onyx updates from this method:

```
$onyxData[] = [
    'onyxMethod' => Onyx::METHOD_MERGE,
    'key' => OnyxKeys::NVP_WORKSPACE_TOOLTIP, // workspaceTooltip
    'value' => [
        'shouldShow' => true,
    ],
],
```

When the user clicks the Create button or click into the composer field, we will dismiss the tooltip and set workspaceTooltip.shouldShow to false. The NVP will no longer be sent on subsequent sign-ins.

## Manual Test Steps
Note: These won't be manually testable till the following backend GHs are done and deployed
https://github.com/Expensify/Expensify/issues/411150
https://github.com/Expensify/Expensify/issues/411149
https://github.com/Expensify/Expensify/issues/411148
https://github.com/Expensify/Expensify/issues/411146

Follow the steps for [Invited to workspace as a non-admin](https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.z1xearylr82p) from the design doc.

## Automated Tests
Not sure if we can test for this.

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by trjExpensify** [comment]
Trying to confirm if this will be held on work in https://github.com/Expensify/App/pull/44277. CC: @tienifr

**Comment by trjExpensify** [comment]
But @tienifr does that mean the `anchorAlignment` approach isn't the right one if it doesn't work for #44277?

**Comment by trjExpensify** [comment]
Okay, can you post your proposal here for posterity? Also, @dukenv0307 can you be the C+ on this? Thanks!

**Comment by deetergp** [comment]
Proposal looks good to me, how about you @dukenv0307?

**Comment by deetergp** [comment]
Nice! Let's 🚀 @tienifr

**Comment by deetergp** [comment]
Good question, @tienifr. How do we do it for the other tool tips?

**Comment by trjExpensify** [comment]
I believe for the quick action button we have a `isFirstQuickAction` boolean: https://github.com/Expensify/App/blob/fef5dfc746367fb59ebfe9c371d09d25b253f618/src/types/onyx/QuickAction.ts#L19

**Comment by trjExpensify** [comment]
@deetergp did you give @tienifr what he needs here to move this on?

**Comment by deetergp** [comment]
@trjExpensify @tienifr I have updated the [Tooltip section](https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.bfsayh3fuyk8) of the doc with details on what to expect when deciding whether or not to show the tooltip. Please let me know if you've got any remaining questions. Thanks!

**Comment by trjExpensify** [comment]
@tienifr isn't C+, so hasn't got an NDA in place to access design docs. Let's get that into the GH issue OP.

**Comment by deetergp** [comment]
@trjExpensify @tienifr I've added the edits from the doc to the GH description under **Frontend Changes (from doc)** and **Backend Changes (from doc)**.

**Comment by deetergp** [comment]
@tienifr The PR to push both `nvp_introSelected` and `worksapceTooltip` in onyx updates when invited users sign in was deployed to staging and should work for you now. Please let me know if you run into any problems!

**Comment by deetergp** [comment]
Were you able to do any testing with the new NVP @tienifr?

**Comment by deetergp** [comment]
@tienifr I don't think we need to call any API at all. Just change the value of `shouldShow` to `false` in onyx. It's a temporary  value that will never be sent again.

**Comment by deetergp** [comment]
@tienifr The tooltip should only be shown to users who were invited to join a workspace, not anyone else. Users invited to join a workspace should be taken to their workspace chat when they respond to the invitation and that's when we want show them the tooltip. Now that I think about it their `nvp_introSelected.isInviteOnboardingComplete` will probably be marked `true` by that point, so let's not worry about that and instead just show the tooltip when `workspaceTooltip.shouldShow` is set and `true` and mark it `false` in onyx once they dismiss it.

**Comment by deetergp** [comment]
You need to 
1. In an incognito window, be logged in as User A, an account that owns a workspace
2. Invite User B, a user with a valid email address that does not yet have an Expensify account
3. Check User B's email for the invitation.
4. Open the `new.expensify.com` link from the email in a different browser window
5. Check onyx for `workspaceTooltip`

<img width="1826" alt="Screenshot 2024-07-29 at 2 51 00 PM" src="https://github.com/user-attachments/assets/2a30572d-7f57-497d-be4b-ef98a53e1a6d">

**Comment by deetergp** [comment]
Any updates @tienifr?

**Comment by deetergp** [comment]
Oh nice! I must have missed the memo on that one 😅

**Comment by deetergp** [comment]
Settle down Melvin, we just merged the PR.

**Comment by stephanieelliott** [comment]
Hey @dukenv0307 can you please propose a regression test when you get a chance?

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @dukenv0307 $250 via Upwork -- offer extended, please accept: https://www.upwork.com/nx/wm/offer/103599573
 - Contributor+: @tienifr  $250 via NewDot -- please request 
 
 Upwork job is here: https://www.upwork.com/jobs/~0162602935c704dbe5

**Comment by stephanieelliott** [comment]
Chatted with @deetergp in DM, we agree that it's fair to raise this issue ot $500 given the work involved. Updated the payment summary [here](https://github.com/Expensify/App/issues/45046#issuecomment-2298291084), also updated your Upwork offer @tienifr -- please accept when you get a chance!

**Comment by garrettmknight** [comment]
@tienifr paid $500 via NewDot
