### ISSUE TITLE
[HOLD for payment 2024-11-22] [$250] [Guided Setup Stage 3] Send the Onboarding Message After Sign-In & Admins Message

### ISSUE THREAD

**Issue by deetergp** [Expensify/App#45044]
## Part of the Extend Onboarding to Invited Users project
Main issue: https://github.com/Expensify/Expensify/issues/392615

Doc sections: 
* [Send the Onboarding Message After Sign-In](https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.ya3970r106w5)
* [Create the onboarding Expensify DM for newly created admins](https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.f66crt614ws0)

Project: [#wave-collect](https://github.com/orgs/Expensify/projects/129)

## Feature Description

When a user who has been invited to join NewDot responds to an invite or and unread messages notification, when they click on the link in the invitation/notification, if that notification was NOT an IOU or Invoice, they should be signed directly into the app and receive an onboarding message from either the Expensify DM or Concierge (It's semi-random based on their accountID) that is relevant to the manner in which they were invited.

* If they were invited to a Workspace as a non-admin, the should be shown [the `newDotEmployer` message](https://github.com/Expensify/App/blob/main/src/CONST.ts#L4096) (note: they will have a different `choice` value, `newDotSubmit`, in the `nvp_introSelected`.
* If they were invited to a User Created Room (UCR) they should will have the same properties as the above and should receive the same message
* If they were invited to a Group Chat, the will have `newDotSplitChat` and should receive [that message](https://github.com/Expensify/App/blob/main/src/CONST.ts#L4253)
* If they were invited via a DM, they well have and receive the same properties as those invited to Group Chats
* If they were invited to a workspace as an Admin, they will have `newDotAdmin` in their NVP and will be shown a new message that we will be adding to `ONBOARDING_MESSAGES` [here](https://github.com/Expensify/App/blob/main/src/CONST.ts#L4318).
* If they user was invited via an IOU or an Invoice, we will not be sending them an onboarding message here.

## Manual Test Steps
Note: These won't be manually testable till the following backend GHs are done and deployed
https://github.com/Expensify/Expensify/issues/411150
https://github.com/Expensify/Expensify/issues/411149
https://github.com/Expensify/Expensify/issues/411148
https://github.com/Expensify/Expensify/issues/411146

See the [manual testing steps](https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.j93ukuhgh4on) from the doc.

## Automated Tests
Add tests to:
* Ensure that the correct message will be sent based on what's in `nvp_introSelected`. 
* Ensure we do not send messages if
    *  `nvp_introSelected` is not set
    *  if `nvp_introSelected.isInviteOnboardingComplete == true`.
    * if `nvp_introSelected.inviteType` is not `iou` or `invoice`
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb28cb224feb7e74</li>
        <li>Upwork Job ID: 1811085293822381806</li>
        <li>Last Price Increase: 2024-07-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by kosmydel** [comment]
Hey, I'm from Software Mansion and I will work on this issue.

**Comment by deetergp** [comment]
Awesome @kosmydel, thanks! Let me know if you have any questions.

**Comment by trjExpensify** [comment]
Help not needed here, Jakub is implementing.

**Comment by hamad-tariq** [comment]
Hi, I am a software engineer from Pakistan and I can help you with this issue.

**Comment by OfstadC** [comment]
>Help not needed here, Jakub is implementing.

@trjExpensify Do I need to take any action here such as remove the "External" label and Upwork listing?

**Comment by trjExpensify** [comment]
Nope, I've removed the `Help wanted` label already. Keep the Upwork listing, as the assigned C+ might need paying via Upwork. 👍

**Comment by deetergp** [comment]
Going to raise a backend PR in the AM and do some testing with the frontend WIP PR.

**Comment by getusha** [comment]
Not overdue!

**Comment by cdOut** [comment]
I'm going to be taking this over from Jakub due to him being OOO this week.

**Comment by trjExpensify** [comment]
Nice, I've assigned you.

**Comment by cdOut** [comment]
@trjExpensify could you close the previous PR made by @kosmydel? He's OOO and won't be able to do that now.

**Comment by trjExpensify** [comment]
Done!

**Comment by OfstadC** [comment]
Looks like the PR is moving along

**Comment by deetergp** [comment]
The PR to fix the issue blocking @cdOut has been merged and deployed to staging. That should get is us back on track!

**Comment by cdOut** [comment]
Thank you, I'll get back to it!

**Comment by OfstadC** [comment]
Any update @cdOut ? 😃

**Comment by cdOut** [comment]
Working on it, we've unlocked it on Monday and since then I've been solving all the remaining issues as we've finally been able to test it with the backend.

**Comment by cdOut** [comment]
We've been fixing any remaining issues on the backend required for this one to work and I'm back from being OOO since the end of last week was a national holiday for us in Poland, will continue this task in the coming days.

**Comment by cdOut** [comment]
Updated the issue over in [this slack thread](https://swmansion.slack.com/archives/C036QM0SLJK/p1724165062900459).

**Comment by OfstadC** [comment]
Any updates here @cdOut @getusha ? 😃

**Comment by cdOut** [comment]
We've had some delays new blockers have appeared on the backend, but that has been fixed last friday. I'm currently retesting the PR and adding any missing functionality, should have the PR up for review early tomorrow.

**Comment by deetergp** [comment]
There are still several discussions happening around getting this one over the finish line, but we're very close to resolving them.

**Comment by deetergp** [comment]
Not overdue

**Comment by getusha** [comment]
Any updates @cdOut?

**Comment by cdOut** [comment]
@getusha yup, [here](https://github.com/Expensify/App/pull/46052#issuecomment-2368290837). You can start the review.

**Comment by deetergp** [comment]
We are zeroing in on the last bits keeping us from closing this one out [here](https://expensify.slack.com/archives/C036QM0SLJK/p1727720865110029).

**Comment by deetergp** [comment]
We are still zeroing in on a couple bugs preventing us from getting this out the door.

**Comment by cdOut** [comment]
I'm currently investigating what's causing the last issues with the raised PR on android, will report with possible solutions tomorrow.

**Comment by deetergp** [comment]
@cdOut Any news about the Android situation?

**Comment by OfstadC** [comment]
Friendly bump @cdOut 😃

**Comment by deetergp** [comment]
@cdOut The PR to send the `CompleteGuidedSetup` data in the response from `OpenReport` was deployed to production last night. Can you please check and see if that fixes the issue with Android?

**Comment by cdOut** [comment]
Yup, that fixes it! It now works both with using a deep-link and by logging into the newly created account.

https://github.com/user-attachments/assets/674f24c1-baed-4a7f-ba5c-742288fd16bf

I'll retest all the other cases and check whether we still have any other blockers.

**Comment by deetergp** [comment]
We're continuing to sort through the changes that have happened to the backend to see if we can get this merged. The discussion is happening here https://expensify.slack.com/archives/C07HPDRELLD/p1730835351149489?thread_ts=1729278293.829049&cid=C07HPDRELLD

**Comment by blazejkustra** [comment]
Update: [PR](https://github.com/Expensify/App/pull/46052) was merged yesterday!

**Comment by deetergp** [comment]
https://github.com/Expensify/App/issues/52544 is expected behavior and not a blocker. I've closed it. https://github.com/Expensify/App/issues/52543 is legitimately a blocker but @blazejkustra already has a fix for it currently under C+ review by @allgandalf.

**Comment by deetergp** [comment]
@getusha Good question. I think maybe if we just add one for the Workspace Admin invitations, I think that will cover most of our bases.

**Comment by garrettmknight** [comment]
$250 approved for @getusha
