### ISSUE TITLE
[HOLD FOR PAYMENT 10/1][$250] [Guided Setup Stage 3] Update the Pay w/ Expensify selectors

### ISSUE THREAD

**Issue by deetergp** [Expensify/App#45045]
## Part of the Extend Onboarding to Invited Users project
Main issue: https://github.com/Expensify/Expensify/issues/392615
Doc section: https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.pnxf7cla3pn
Project: [#wave-collect](https://github.com/orgs/Expensify/projects/129)

## Feature Description

When a user is invited to NewDot from an IOU, we initially assume they are going to be splitting bills and assign them the `newDotSplitChat` choice and an `inviteTye` of `iou` on their `nvp_introSelected`, but we want to wait till they select a payment type before we send them their onboarding message. If they select: 
* "Pay with Business Bank Account" we want to
    * Send them the `newDotManageTeam` onboarding message
    * Optimistically set `nvp_introSelected`
        * `choice` to `newDotManageTeam`
        * `isInviteOnboardingComplete` to `true`
* "Pay with Personal Bank Account" or "Pay with Debit Card" we want to 
    * Send them the `newDotSplitChat` message
    * Optimistically set `nvp_introSelected` 
        * `isInviteOnboardingComplete` to `true`

When a user is invited to NewDot from an invoice, we initially assume they are going to be managing expenses for a team and give them the `newDotManageTeam` choice and an `inviteType` of `invoice` on their `nvp_introSelected`, but we want to wait till they select a payment type before we send them their onboarding message. If they select:
* "Pay as an Individual" we want to 
    * Send them the `newDotSplitChat` onboarding message
    * Optimistically set `nvp_introSelected`
        * `choice` to `newDotSplitChat`
        * `isInviteOnboardingComplete` to `true`
* "Pay as a Business" we want to 
    * Send them the `newDotManageTeam` message
    * Optimistically set `nvp_introSelected`
        * `isInviteOnboardingComplete` to `true`

## Manual Test Steps
Note: These won't be manually testable till the following backend GHs are done and deployed
https://github.com/Expensify/Expensify/issues/411150
https://github.com/Expensify/Expensify/issues/411149
https://github.com/Expensify/Expensify/issues/411148
https://github.com/Expensify/Expensify/issues/411146

See the [Pays an IOU or invoice via VBBA](https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.vtfnxd5g9qd3) and [Pays an IOU or invoice via Elsewhere/PBA/Debit/Credit](https://docs.google.com/document/d/1EX1tKSkhffpqP4TXD7iKIPKWnU5U8ELv32j-QTtXH2g/edit#heading=h.236s7kh0hmmj) sections from the doc.

## Automated Tests
If possible, add tests to assert that 
* Users with `nvp_introSelected.inviteType: iou` that click the "Pay With Business Bank Account" button end up with `nvp_introSelected.choice: newDotManageTeam` and `nvp_introSelected.isInviteOnboardingComplete: true` and are sent the `newDotManageTeam` onboarding message.
* Users with `nvp_introSelected.inviteType: invoice` that click the "Pay as an Individual" button end up with `nvp_introSelected.choice: newDotSplitChat` and `nvp_introSelected.isInviteOnboardingComplete: true` and are sent the `newDotSplitChat` onboarding message.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841133888555964659</li>
        <li>Upwork Job ID: 1841133888555964659</li>
        <li>Last Price Increase: 2024-10-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by trjExpensify** [comment]
Confirming who from SWM is taking this here: https://expensify.slack.com/archives/C036QM0SLJK/p1720631312670319?thread_ts=1720454141.387759&cid=C036QM0SLJK

**Comment by cdOut** [comment]
Hi, I’m Tymoteusz Kałuzieński from Software Mansion, the expert agency, and I’ll be working on this issue.

**Comment by deetergp** [comment]
Hi @cdOut, thanks for taking this on!

**Comment by cdOut** [comment]
Waiting for the backends.

**Comment by deetergp** [comment]
I'm working on the PR to send the message to non-IOU/Invoice customers and should have that wrapped tomorrow. Once it's doen this should be very easy to complete shortly thereafter. Hoping to have it done tomorrow afternoon.

**Comment by deetergp** [comment]
@cdOut The PR to push `nvp_introSelected` to onyx when invited users sign in for the first time has been deployed to staging, so you should be able to at least work with that NVP. It got too late in the day for a Friday to deploy the back end changes to handle. I _think_ you can test your changes with Report.completeOnboarding without any backend changes to `CompleteGuidedSetup`, the only piece missing is that we won't updated the NVP in the backend. I am going to ask our Aussie employees to deploy the back end changes on their Monday morning, which should still be Sunday night for you in CEST. I'll let know one way or another if it happens or not.

**Comment by cdOut** [comment]
@deetergp I'll look over the changes to the docs and try out the nvp_introSelected, could you also update me if the rest of the backend changes have been pushed to staging also?

**Comment by deetergp** [comment]
@cdOut The backend has been updated to handle updating the NVP changes when an IOU-invited user selects BBA and an Invoice-invited user selects anything other than BBA. It should also send the onboarding message for any IOU or Invoice invited user despite which payment type they choose. Please test away and let me know if you hit any speed bumps along the way. Thanks!

**Comment by cdOut** [comment]
Thank you, I'll test and add the recent changes to the doc and see if all works well. Will ping you if I have any further questions.

**Comment by cdOut** [comment]
I worked on it yesterday and will continue today, both issues should be ready for review sometime tomorrow.

**Comment by deetergp** [comment]
Looking forward to it @cdOut, thanks!

**Comment by deetergp** [comment]
Any word on progress @cdOut?

**Comment by cdOut** [comment]
@deetergp back to the slack thread, is there anything I need to add / specify when running it locally for the invite email to open correctly? In the video I've sent it clearly does not work as if something is not set correctly and those tests were run on the latest main.

**Comment by deetergp** [comment]
Something has definitely changed on the back end. When an invitee responds to an invitation we are now getting a ton of permissions errors on the back end when trying to setup the app for them. I'm going through them now and trying to figure out what they are and granting them to the chat token on the back end. I'll let you know once I get that sorted.

**Comment by cdOut** [comment]
Thank you, keep me updated and I’ll get on it as soon as you’re done with that. In the mean time, should I also include automated tests in these PRs?

**Comment by CortneyOfstad** [comment]
@Christinadobrzyn I am heading OoO so reassigning this to keep eyes on it. Thanks!

**Comment by deetergp** [comment]
@cdOut The fix for the issue that was blocking you has been merged and deployed to the staging server, which should hopefully unblock you now.

**Comment by deetergp** [comment]
Any updates @cdOut?

**Comment by CortneyOfstad** [comment]
I am back from OoO — thanks @Christinadobrzyn for holding down the fort!

**Comment by cdOut** [comment]
@CortneyOfstad no luck with further testing the PR, we've been blocked with this for a few days now. A very crucial part of this feature, which is sending invites to the user added for an expense, is not working on the backend side of our app. You can refer to the [thread over here on slack](https://swmansion.slack.com/archives/C036QM0SLJK/p1723478052032719?thread_ts=1722872563.829979&cid=C036QM0SLJK) for further details. I will notify when we'll be able to actually push this PR further.

**Comment by deetergp** [comment]
@cdOut We identified the issue and deployed the fix. You should be seeing the IOU/Invoice invites again now.

**Comment by deetergp** [comment]
Now that the bug preventing IOU invites from sending has been resolved we're hoping to get @cdOut's PR soon.

**Comment by cdOut** [comment]
Of course, I'm working on it today and will update you when it's ready for a final review.

**Comment by cdOut** [comment]
@CortneyOfstad Of course, here's the link to [the PR](https://github.com/Expensify/App/pull/45264).

**Comment by deetergp** [comment]
Any updates @cdOut?

**Comment by cdOut** [comment]
Answered the above in the [slack thread for this issue](https://swmansion.slack.com/archives/C036QM0SLJK/p1724165062900459).

**Comment by deetergp** [comment]
Latest update is [here](https://expensify.slack.com/archives/C036QM0SLJK/p1724767870530889?thread_ts=1724680355.732449&cid=C036QM0SLJK).

**Comment by deetergp** [comment]
The PR to unblock @cdOut went out in the auth deploy today. I'm OOO Friday & Monday, but will check in to make sure I'm not blocking anyone in the meantime.

**Comment by trjExpensify** [comment]
@DylanDylann is reviewing this PR: https://github.com/Expensify/App/pull/45264

**Comment by deetergp** [comment]
Review still pending

**Comment by DylanDylann** [comment]
I am on it. Will complete in an hour

**Comment by DylanDylann** [comment]
@deetergp Could you help to verify the below conflict? Is it expected?

1.
<img width="756" alt="Screenshot 2024-09-04 at 17 09 32" src="https://github.com/user-attachments/assets/e03793f8-edfd-4432-83be-2307f25ac5c4">

2.
<img width="763" alt="Screenshot 2024-09-04 at 17 11 18" src="https://github.com/user-attachments/assets/5bfe4f79-d6a6-4091-9ebd-fc71242d29d2">

**Comment by deetergp** [comment]
1. Was a typo, my bad. I've updated it in the description.
2. Yes, we are not setting choice when a user invited by an invoice pays with a business bank account as it has already been set to `newDotManageTeam` when they were invited. We are also not setting choice for IOU invited users when they pay with a non business bank account, as `newDotSplitChat` was set when they were invited.

**Comment by deetergp** [comment]
I approved the PR, but it's got a merge conflict. Should be quick and easy enough for Tymo to resolve it and we'll get it merged.

**Comment by deetergp** [comment]
This ended up getting fixed and merged last Friday.

**Comment by CortneyOfstad** [comment]
@deetergp to confirm, payment is needed here? If so, standard for @DylanDylann as @cdOut is with SM? TIA!

**Comment by CortneyOfstad** [comment]
@deetergp bump on the above ^^^ thank you!

**Comment by deetergp** [comment]
@CortneyOfstad Sorry! Yes, you are correct, standard for @DylanDylann. @cdOut is with SWM.

**Comment by DylanDylann** [comment]
@CortneyOfstad Please help to handle payment here. Thanks

**Comment by CortneyOfstad** [comment]
Sorry for missing this as I was OoO — getting the payments sorted now!

**Comment by CortneyOfstad** [comment]
Sorry the ping ^^^ Had to apply the external label to get the job post to be created!

**Comment by CortneyOfstad** [comment]
@DylanDylann I just sent you an offer via Upwork — please let me know once you accept and I will get that paid ASAP. Thanks!

**Comment by DylanDylann** [comment]
@CortneyOfstad I accepted it, thank you

**Comment by CortneyOfstad** [comment]
## Payment Summary

@DylanDylann — paid $250 via Upwork
@cdOut — contracted position
