### ISSUE TITLE
[PAID] [$250] QBO - Tags - Error message is missing left and right margins and cannot be dismissed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45056]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace A is connected to QBO and has imported multi tags.
- Workspace B is not connected to QBO and has tags (not multi tags).

1. Go to staging.new.expensify.com
2. Go to Workspace B settings > Tags.
3. Click Settings > Custom tag name.
4. Enter 0 and save it.
5. Note that the error message has left and right margins and can be dismissed.
6. Go to Workspace A settings (the one connected to QBO) > Tags.
7. Click on any main tag > Custom tag name.
8. Enter 0 and save it.
9. Click on the X button.

## Expected Result:
The error message will have left and right margins and can be dismissed.

## Actual Result:
The error message does not have left and right margins and cannot be dismissed when clicking on the X button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1f126f85-1419-4023-9fab-29f8b60b2c4b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100255cf25234fe2e</li>
        <li>Upwork Job ID: 1810657313224383264</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 103046084</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Crash on production
![image (3)](https://github.com/Expensify/App/assets/115492554/1dce9196-a0d7-41be-8799-2e5462953c1a)

**Comment by danieldoglas** [comment]
Doesn't look related to backend changes.

**Comment by Julesssss** [comment]
Hi @ShridharGoel, your proposal makes sense to me. As this is a blocker, please could you raise a PR ASAP and I'll assign you.

**Comment by kbecciv** [comment]
Issue is not reproducible

https://github.com/Expensify/App/assets/93399543/560f2b1b-6f4f-42f3-8bde-b0fd7b441d7e
