### ISSUE TITLE
[$250] Xero-LHN reports not displayed if login using xero connected a/c

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45065]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
in mweb
2. Tap profile - workspaces- worspace
3. Tap more features
4. Enable accounting
5. Connect xerox integration
6. Sync account using 3 dots
7. Login with same account on android

## Expected Result:
User must be able to see LHN reports, if user login using xero integration connected account

## Actual Result:
User sees woo-hoo all caught up message & not LHN reports, if user login using xero integration connected account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/675a0533-8178-42ab-8279-4b7a806609cf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01151d0e3495d1890c</li>
        <li>Upwork Job ID: 1812859931445199078</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by jayeshmangwani** [comment]
> We need to add handling for case that the user is required to enable 2FA, we should:

@tienifr We have a similar issue https://github.com/Expensify/App/issues/43015 here, that will force workspace admins to enable 2FA before they can use the connection.

It looks like this issue will be solved after this PR https://github.com/Expensify/App/pull/44059 is merged. Correct me if I am wrong @c3024 @rushatgabhane.

**Comment by rushatgabhane** [comment]
@jayeshmangwani yep that's right

**Comment by rushatgabhane** [comment]
we should close this issue

**Comment by jayeshmangwani** [comment]
Not overdue. Issue can be closed, but Matt is OOO until Tuesday.

**Comment by jayeshmangwani** [comment]
@muttmuure We can close this issue. Please check this [comment](https://github.com/Expensify/App/issues/45065#issuecomment-2230818494) whenever you get a moment.

**Comment by muttmuure** [comment]
Ah yes, let's close. Thanks for the bump!
