### ISSUE TITLE
[$250] Bank account - "Hmm... it's not here" page appears after selecting Incorporation state

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45060]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4703397
**Email or phone of affected tester (no customers):** applausetester+vd_ios070824@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: the user must have created a Workspace and have enabled Workflows.

1. Go to Settings > Workspaces > Workspace > Workflows.
2. Tap on "Connect bank account".
3. Select "Connect manually".
4. Go trough the add bank account process using the testing credentials.
5. Once you reach the Incorporation state page on the Company info section, tap on the field and try to select a state.

## Expected Result:
Once the user taps on an option, the selected option should be displayed on the Incorporation state field and the user should be able to continue with the add bank account process.

## Actual Result:
Once the user taps on an option, "Hmm... it's not here" page is displayed and the user is not able to continue with the add bank account process.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1c005cef-1a7b-4284-b567-13fec433ab9c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f7892dcd73eb461</li>
        <li>Upwork Job ID: 1810720111946419022</li>
        <li>Last Price Increase: 2024-07-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by izarutskaya** [comment]
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by danieldoglas** [comment]
Doesn't look related to backend changes. Removing the label.

**Comment by Julesssss** [comment]
Hey @izarutskaya, what is the reason that we cannot test this in prod? 

> Reproducible in production?: Unable to check

**Comment by Julesssss** [comment]
@dominictb these options make sense to me. I like solution 2 for now as we don't need  a more complex and scalable solution yet.

**Comment by Julesssss** [comment]
Hi @s77rt can you please review the [proposal](https://github.com/Expensify/App/issues/45060#issuecomment-2218060966) above, ideally using solution 2? 

We need the solution to resolve two bugs, so the changes will need to pass the test cases in both of these PRs:
- https://github.com/Expensify/App/issues/45060
- https://github.com/Expensify/App/pull/44981

**Comment by dangrous** [comment]
2 makes sense to me as well but happy to hear what @s77rt says.

Alternately - do we want to get @nkdengineer / @hoangzinh on this since it seems like a regression from https://github.com/Expensify/App/pull/44981 ?

**Comment by s77rt** [comment]
@dominictb Your RCA is correct. However regarding the solution I would prefer to revert https://github.com/Expensify/App/issues/44957 being a workaround, the `backTo` param shouldn't be manipulated. Then we need to find another solution for https://github.com/Expensify/App/pull/44981. The RCA for that issue is not totally clear.

> If we look at the param in the URL path when selecting state, we'll see that &country=AQ (old country code) is there

Why do we even have that param in the backTo param if the original page didn't have it?

https://github.com/Expensify/App/assets/16493223/ea6d900c-5ebc-4f35-8b20-a533baa810d1


cc @nkdengineer

**Comment by mountiny** [comment]
cc @mateuuszzzzz seems like the issue is not completely fixed

**Comment by mountiny** [comment]
@s77rt This is last of 2 blockers, I think the issue that @nkdengineer PR fixed was less severe, user could still add the correct country and state afterwards I assume. 

So maybe we can demote that one and revert the CPed change to fix this issue. To unblock a deploy

**Comment by s77rt** [comment]
@mountiny I agree. Let's revert the PR

**Comment by mountiny** [comment]
Ok I have raised the revert PR here https://github.com/Expensify/App/pull/45121 and going to demote the other issue

**Comment by mountiny** [comment]
The PR will be QAed in staging
