### ISSUE TITLE
Track - App shows old receipt when submitting expense with receipt and changing receipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4703969
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Go to + > Track expense > Manual
4. Track a manual expense with receipt
5. Click Submit to someone from the actionable whisper
6. Select a user and proceed to confirmation page
7. On confirmation page, click 3-dot menu > Add receipt
8. Upload a different receipt and submit to the person
9. Click on the transaction thread

## Expected Result:
The receipt view will show the latest uploaded receipt

## Actual Result:
The receipt view shows the original uploaded receipt (Step 4) instead of the latest one (Step 8)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eeb11ede-b9cf-4cc3-aef2-840d0fa5fc3b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by rlinoz** [comment]
Can't repro in v9.0.5-7, closing

https://github.com/Expensify/App/assets/5201282/62310216-5dc3-4cd3-836f-b6131aeef1b0

**Comment by lanitochka17** [comment]
Hello @rlinoz This issue is still reproducible again.

You should do a manual expense with receipt, not scan request

Updated steps:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Go to + > Track expense > Manual
4. Track a manual expense with receipt
5. Click Submit to someone from the actionable whisper
6. Select a user and proceed to confirmation page
7. On confirmation page, click 3-dot menu > Add receipt
8. Upload a different receipt and submit to the person
9. Click on the transaction thread

Thank you

**Comment by rlinoz** [comment]
Oh this happens because `ConvertTrackedExpenseToRequest` doesn't accept a receipt, we will just use the one we already have attached to that expense. Let me check if we should change the BE or remove the three dot in this flow.

**Comment by rlinoz** [comment]
We added the threedots here https://github.com/Expensify/App/pull/44670
