### ISSUE TITLE
Save world - Tapping link "Click on save the world" directs to hmm not here page.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45066]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap profile icon -- save the world
3. Tap " I know a teacher"
4. Enter all details and teacher mail id and tap let's do this!
5. Login in mweb as a teacher
6. Tap on Teacher's unite report (if can't see the report trouble shoot-clear cache)
7. Tap the link "Click on save the world"

## Expected Result:
Tapping link "Click on save the world" must not direct to hmm not here page.

## Actual Result:
Tapping link "Click on save the world" directs to hmm not here page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f7b0ce85-6f39-4e23-9e42-e43896010615

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by sakluger** [comment]
I asked in Slack if we're still running this campaign and if we should prioritize fixing bugs in the new teacher referral flow (https://expensify.slack.com/archives/C5CSEF83C/p1720716913360109).

While testing this, I also found an issue in the teacher invite email. The email text doesn't show who invited them (it says "Your friend <> invited you...."):

<img width="911" alt="image" src="https://github.com/Expensify/App/assets/5997400/430fbba7-718f-411e-8e14-d1255a5df11a">

**Comment by marcochavezf** [comment]
Happy to take this one and tackle it in my spare cycles

**Comment by sakluger** [comment]
Thanks @marcochavezf! When you look into this one, can you also check out the missing field in the email? I gave more details about that second bug in this comment: https://github.com/Expensify/App/issues/45066#issuecomment-2223432500.

**Comment by marcochavezf** [comment]
Sure, thanks for pointing that out. Seems there's a mention issue there

**Comment by sakluger** [comment]
@marcochavezf is Daily the correct priority label? Feel free to move to weekly if you won't be able to get to it immediately.

**Comment by marcochavezf** [comment]
Sounds good, moving to weekly

**Comment by marcochavezf** [comment]
Working on it [here](https://github.com/Expensify/Auth/pull/11818)

**Comment by marcochavezf** [comment]
I continued with this one a little bit today. Tomorrow I will continue testing

**Comment by marcochavezf** [comment]
We're stripping out the mention tag from the html content in `ReportUtils::createHTMLCommentFragment`, specifically in [ReportUtils::convertCommentsHtmlToText](https://github.com/Expensify/Web-Expensify/blob/433ecaf1a9cc35241693264cb1fb8e23d4d5257c/lib/ReportUtils.php#L1778). Next step is to look how we render the HTML content to text for other mentions in the code, probably there's a discrepancy with the TU emails.

**Comment by sakluger** [comment]
Hey @marcochavezf, how's this one coming?

**Comment by marcochavezf** [comment]
This one has been a bit complex because I think the immediate notifications for mentions are broken in this case (I'm not 100% sure yet), but I still need to dig a bit more.

**Comment by marcochavezf** [comment]
PRs in review:
- https://github.com/Expensify/Auth/pull/11818
- https://github.com/Expensify/Web-Expensify/pull/43004

**Comment by sakluger** [comment]
All PRs have been deployed, thanks @marcochavezf!
