### ISSUE TITLE
Hold - Unexpected error when employee unhold expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4700897&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+workspaceemployee135@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
1. Login as the owner of the workspace
2. Create a workspace
3. Invite the approver and employee
4. Navigate to more features
5. Enable "workflows"
6. On the "Workflow" editor - enable "Add Approvals"
7. Set the Approver account as the Approver
Steps:
1. As Employee submit 2 expenses to Workspace chat
2. As Approver hold the first expense
3. As Employee unhold the first expense

## Expected Result:
Selected expense should be unheld and no errors should appear

## Actual Result:
Unexpected error appears when employee unhold expense hold by approver

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/490d612c-3b1b-42ef-9fcf-7d5928e24bd6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by jliexpensify** [comment]
Hmm I think this is intentional? [Asking here.](https://expensify.slack.com/archives/C036QM0SLJK/p1720651762872729)

**Comment by jliexpensify** [comment]
This is being worked on in #44573

![image](https://github.com/Expensify/App/assets/30815269/7abf6638-4f38-49be-8452-3efd90c92967)

However, an approver who holds an expense will not allow for an employee to unhold. So this is actually not a bug at all, but intended.
