### ISSUE TITLE
[$250] Track expense - Self DM does not auto scroll down when tracking expense for the second time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45061]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4703966
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Track a few expenses so that the chat is scrollable
4. Scroll up and track an expense
5. Note that the chat will scroll down after tracking an expense
6. Scroll up again and track another expense

## Expected Result:
The chat will auto scroll down each time tracking an expense

## Actual Result:
The chat does not auto scroll down when tracking expense for the second time onward

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d3c3a5c9-6275-4fdc-8f6f-11a3923b37bf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b968338d6ec47d8b</li>
        <li>Upwork Job ID: 1810743678987255099</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by ahmedGaber93** [comment]
@nyomanjyotisa Thanks for the proposal
Your root cause not mention why this work fine in the first time then failed in the second time.

**Comment by ahmedGaber93** [comment]
I think this is a backend issue, when we track expense, we create 2 reportActions IOU and whisper message. the `lastVisibleActionCreated` here should be whisper message created date, but `API.GetMissingOnyxUpdates()` return `lastVisibleActionCreated` with value IOU created date (see the below response)

```javascript
{
    "onyxData": [
        {
            "key": "report_4236851434064479",
            "value": {
                "lastVisibleActionCreated": "2024-07-15 09:48:56.854" // <<<<<<<<<<<<<
            }
        },
        {
            "key": "reportActions_4236851434064479",
            "value": {
                "1256962670291407087": {
                    "actionName": "IOU",
                    "created": "2024-07-15 09:48:56.854" // <<<<<<<<<<<<<
                }
            }
        },
        {
            "key": "reportActions_4236851434064479",
            "value": {
                "3872369980560111783": {
                    "actionName": "ACTIONABLETRACKEXPENSEWHISPER",
                    "created": "2024-07-15 09:48:56.857" // <<<<<<<<<<<<<
                }
            }
        }
    ]
}
```

**Comment by garrettmknight** [comment]
Awaiting an internal volunteer

**Comment by ahmedGaber93** [comment]
Not overdue, we are waiting for internal volunteer

**Comment by ahmedGaber93** [comment]
Not overdue, we are waiting for internal volunteer

**Comment by ahmedGaber93** [comment]
@garrettmknight What is the next here?

**Comment by garrettmknight** [comment]
Technically, we're awaiting an internal volunteer to work on this one, but it's the lowest priority on the roadmap as it is so I don't think we'll get one soon. I'm going to retest to see if this is still an issue first, then I'll take a look at whether it fits anywhere else, but if it doesn't I'm going to close.

**Comment by garrettmknight** [comment]
Reproduced - didn't auto-scroll after the 2nd tracked expense.

**Comment by ahmedGaber93** [comment]
@garrettmknight, should we make it weekly?  Because of it is low priority

**Comment by garrettmknight** [comment]
I don't think this is an important bug to fix, honestly, so I don't even think we should make it weekly - this is a niche issue for a feature that isn't a high priority to make perfect at the moment. I think I'm going to close and we can reopen if/when this becomes a higher priority.
