### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Connect bank - "-1" is pre-filled for the tax ID number when connecting a new bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45073]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace and enable workflows
3. Go through connecting a bank account flow up until the fourth step where it requires you for the tax ID number

## Expected Result:
The input field should be empty

## Actual Result:
The input field has a pre-filled value of "-1"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![15!image](https://github.com/Expensify/App/assets/78819774/f04767d4-3009-449c-a488-f9d8d9f3866d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ff97d1a1bc0b4b8</li>
        <li>Upwork Job ID: 1811441687713769949</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103085245</li>
<li>Krishna2323 | Contributor | 103085246</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
Clearly reproducible!

![image](https://github.com/Expensify/App/assets/32854888/392e29e3-574b-410d-af79-81a88203af6d)

@blimpich can I get you to take a look at this? Looks like you were on that PR where this crept in? Should this be an internal or external fix?

**Comment by blimpich** [comment]
@kubabutkiewicz can you take a look at this and see if there was a mistake that we made in https://github.com/Expensify/App/pull/42634?

**Comment by kubabutkiewicz** [comment]
@blimpich yeah this comes from #42634 PR

**Comment by RachCHopkins** [comment]
All contracts paid via Upwork!

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor: @Krishna2323 paid $250 via Upwork

Contributor+: @suneox paid $250 via UpWork

Upwork job [here](https://www.upwork.com/jobs/~016ff97d1a1bc0b4b8)

Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
