### ISSUE TITLE
[$250] Web -Search - Grouped expenses row is still slightly grayed out after unselecting the expenses

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.5-4 
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has submitted a few expenses to another user.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Go to Shared.
4. Click on the select all checkbox of the group expenses (not the select all checkbox for all types of expenses, it's the checkbox for the grouped expenses).
5. Click on the select all checkbox again to unselect.
6. Move the cursor outside the grouped expenses.
7. Note the color of the entire row of grouped expenses (it is still slightly grayed out).
8. Click on any empty area.
9. Note that the grouped expenses row is now not grayed out at all.

## Expected Result:
In Step 7, after unselecting the grouped expenses, the row will not be grayed out.

## Actual Result:
In Step 7, after unselecting the grouped expenses, the row is slightly grayed out.
The grayness is gone after clicking on the empty area (Step 9).
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/21136114-cd1c-47a3-9829-40acac2942a8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bcd214466a9b97d7</li>
        <li>Upwork Job ID: 1810721978277539440</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103160053</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by m-natarajan** [comment]
@stitesExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by Julesssss** [comment]
Not a blocker. Removing from the checklist

**Comment by mollfpr** [comment]
@nyomanjyotisa I think the RCA isn't correct. Why the list is not greyed out after step 8?

---

>When we click on the Checkbox to unselect, the isPressed is set to true so that leads to after step 7, the pressDimmingValue: 0.8 is still applied to the row.

@dominictb My understanding is that the `onPressOut` is failing to set the `isPressed` to `false`, is that correct? And why `stopPropagation` is fixing the issue?

**Comment by mollfpr** [comment]
Sorry for the delay 🙏

The proposal from @dominictb looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment]
@sonialiap I think the automation is not working here, the PR already hit production on the 25th of July. Could you give me the payment summary? Thank you!

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. It's a pretty rare case and hard to notice.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Go to NewDot
2. Go to Search.
3. Go to Shared.
4. Click on the select all checkbox of the group expenses (not the select all checkbox for all types of expenses, it's the checkbox for the grouped expenses).
5. Click on the select all checkbox again to unselect.
6. Move the cursor outside the grouped expenses.
7. Verify that the row will not be grayed out.
8. 👍 or 👎

**Comment by sonialiap** [comment]
Payment summary:
- @mollfpr $250 - please request in ND
- @dominictb $250 - paid in upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr
