### ISSUE TITLE
[HOLD for payment 2024-07-24] [Wave control] [Report fields] Standardize of using plural name for report fields components 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45085]
Part of the report fields configuration project

During the implementation of the report fields configuration for control workspaces project, we have been using ReportField and ReportFields (singular and plural) options in file names, component/ pages names and its confusing, lets standardize on the plural usage as that works logically for most cases.

cc @rezkiy37 @waterim

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to take this issue!
