### ISSUE TITLE
Save the world - Received email is not referred sender and teacher by name or email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45095]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Account settings > Save the world
3. Click on the "I know a teacher" button
4. Fill in all fields
5. Click on the "Let's do this!" button
6. Open your email app

## Expected Result:
The mail should start with "Hey"
If the name of the sender and teacher is known (filled out before sending) the email should refer them by name

## Actual Result:
The mail should start with "Hey"
Received email is not referred sender and teacher by name or email

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c36d2acb-1728-48bb-a7d3-5e44ea275151

![43!Actual](https://github.com/Expensify/App/assets/78819774/6c073ae0-982c-4697-bb2d-7aaaf12ae9b4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MitchExpensify** [comment]
I replicated this but I'm not sure it fits into our roadmap right now
