### ISSUE TITLE
Distance - Map centers on users location after permission to access location is denied

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4700585
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Disallow expensify to access user's location and go to troubleshoot and clear cache and restart
3. Go to workspace chat and start a distance expense flow
4. Observe the prompt to allow access to user's location and observe the map being centered on San Francisco
5. Allow expensify to access user's location
6. Start a distance expense flow and observe the map now centers on user's location
7. Disallow expensify to access user's location again
8. Start a distance expense flow and observe the map

## Expected Result:
Map should center on San Francisco

## Actual Result:
Map centers on user's current location based on the saved cache but if user clears cache and restarts then map centers on San Francisco

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/87a55c1f-1fb6-4e55-8206-88f212f16e76

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jacobkim9881** [comment]
Clearing cache doesn't seem to reset the users location. Users location is saved in Onyx(local database) I think. Let me know the answer.

**Comment by anmurali** [comment]
Hmm I cannot reproduce. Map does go back to centering in SF. I am also not sure why this is an issue? It doesn't seem like a problem if it doesn't actually behave this way.
