### ISSUE TITLE
[HOLD for payment 2024-07-25] Change copy to match when adding/removing receipts

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#45103]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0 (9.0.4-0)
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @stitesExpensify 
**Slack conversation:**

## Action Performed:
1. Add expenses to a report
2. Remove a receipt and then add another one

## Expected Result:
Both messages should say "a receipt" since there can be multiple receipts on the report

## Actual Result:
One says "the receipt" the other says "a receipt"

## Workaround:
n/a
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="661" alt="2024-07-09_11-44-05" src="https://github.com/Expensify/App/assets/42391420/33ff860e-fd5c-47ff-8c17-a78e826becc3">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stitesExpensify** [comment]
Hey @ryanschaffer super easy change here, I think we should say "removed _a_ receipt" instead of _the_ receipt since there can be multiple receipts in a report. Make sense?

**Comment by stitesExpensify** [comment]
@OfstadC no need for a bugZero here I'll just make this change real quick and assign it without a C+ since it is such a small change

**Comment by OfstadC** [comment]
Sounds good @stitesExpensify ! I'll remove myself, but if anything changes and i'm needed, feel free to re-assign me 😄

**Comment by stitesExpensify** [comment]
Honestly this is such a straightforward change I'm just going to do it without waiting for marketing. There's no way this is wrong

**Comment by stitesExpensify** [comment]
PR is ready, just testing

**Comment by stitesExpensify** [comment]
Unnecessary for a copy change ^
