### ISSUE TITLE
Error appear when transferring wallet balance

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45111]
- you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.5-9
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @blimpich 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720549166553659

## Action Performed:
1. Open app
2. Go to Settings > Wallet
3. Click on `Transfer Balance`
4. Choose an account to transfer
## Expected Result:
Able to transfer the balance without any issue
## Actual Result:
Auth TransferWalletBalance returned an error appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-07-09 at 11 17 43 AM](https://github.com/Expensify/App/assets/38435837/805dfeb9-6c93-4eea-9d5c-222c9be83ebd)

https://github.com/Expensify/App/assets/38435837/b662c3db-3311-45ac-916a-7b73ddceb425

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by blimpich** [comment]
Relevant slack thread: https://expensify.slack.com/archives/C0BS1NT42/p1719990677205619?thread_ts=1719520334.409249&cid=C0BS1NT42

**Comment by blimpich** [comment]
Still an issue, I got $40 just stuck in there.

**Comment by kevinksullivan** [comment]
Going to assign @MariaHCD based on the thread but demote this to monthly.

**Comment by MariaHCD** [comment]
Investigation is being done here: https://github.com/Expensify/Expensify/issues/408390

**Comment by MariaHCD** [comment]
This was resolved via [this](https://github.com/Expensify/Auth/pull/11908) PR as part of https://github.com/Expensify/Expensify/issues/408390

https://expensify.slack.com/archives/C0BS1NT42/p1723647515762909?thread_ts=1719520334.409249&cid=C0BS1NT42
