### ISSUE TITLE
Change payment currency: CVV field errors

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#45127]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-10
**Reproducible in staging?:** Staging
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** NA
**Email or phone of affected tester (no customers):**
**Logs:** NA
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** mitch@expebsify.com 
**Slack conversation:** Internal: https://expensify.slack.com/archives/C036QM0SLJK/p1720560965872139?thread_ts=1720544914.651789&cid=C036QM0SLJK

## Action Performed:
1. Open new.expensify.com/settings/subscription
2. Add a payment card
3. Click the 3 dot menu
5. Click "Change payment currency"
6. Enter a 4 digit CVV number or the wrong CVV of the card on file 
7. Hit save

## Expected Result:
You should see a form error for 4 digits or any letter input: "Please enter a valid security code."

**Note**: We should have the same CVV field behavior across "add payment card" and "change payment currency"

## Actual Result:
No immediate form errors for any letter input or 4 digits 

## Workaround:
Ignore 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/36425901/4469aca6-0916-4c69-acf0-4f79d559bff7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by trjExpensify** [comment]
As discussed [here](https://expensify.slack.com/archives/C036QM0SLJK/p1720565530211399?thread_ts=1720544914.651789&cid=C036QM0SLJK), we can close this. 4 digit CVVs are valid.
