### ISSUE TITLE
[HOLD #43040] [Xero Export] Implement offline pattern B for manual report exports

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#45137]
Main issue: https://github.com/Expensify/Expensify/issues/409245

# Part of [QBO Export and Error Handling in NewDot](https://github.com/Expensify/Expensify/issues/350150)
Doc section: https://docs.google.com/document/d/1aQl-AK_F6IqszWYG2aEllTsD5x3h4b8Zu0XEG0LuQ08/edit#heading=h.xw0s9oqvo44s
Project: https://github.com/orgs/Expensify/projects/129

# Feature Description
During review for the detailed design, we decided we should support offline pattern B when manually exporting reports [here](https://docs.google.com/document/d/1aQl-AK_F6IqszWYG2aEllTsD5x3h4b8Zu0XEG0LuQ08/edit?disco=AAABO4Akx_Y). To implement that we need to

- Create an optimistic `EXPORTINTEGRATION` action in our `Report.exportToIntegration` and `Report.markAsManuallyExported` actions
  - The text should say `started exporting this report to {integration}...`
- Pass the `optimisticReportActionID` to both `Report_Export` and `MarkAsExported` APIs
- Use the ID to create the action in Auth
  - Auth will queue updates for the report action with the final text: `exported this report to {integration}. [View out-of-pocket expenses].`
- On failure
  - create the `INTEGRATIONSMESSAGE` action with the error message like normal (using a different ID)
  - delete the optimistic action on the frontend using `failureData`

# Manual Test Steps

**Sucessful offline export**
1. Submit an expense report
2. Log in as the workspace admin
3. Approve the report
4. Go offline
5. 3-dot menu > Export > Xero
6. Verify a semi-transparent exported action gets added to the report
7. Go online
8. Verify the action becomes fully opaque

**Failed offline export**

Prerequisites
- Add a chart of account (expense category) to Xero that you can delete later

Steps

1. Create a report with an expense
2. Categorize the expense using the new Xero category
3. Submit it
4. Log in as the workspace admin and approve the report
5. Log into Xero and delete the chart of account 
6. Go offline in NewDot
7. Export the report to Xero (3-dot menu > Export > Xero)
8. 6. Verify a semi-transparent exported action gets added to the report
9. 7. Go online
8. Verify 
    - the exported action is removed
    - a report export error action is added in it's place

# Automated Tests

- Verify optimisticData for the `INTEGRATIONSMESSAGE` is merged for both `Report.exportToIntegration` and `Report.markAsManuallyExported` actions
- Verify failureData removes the action

**Comment by lakchote** [comment]
Will be handled by https://github.com/Expensify/App/issues/43040

**Comment by trjExpensify** [comment]
@arosiclair can we close this btw, based on https://github.com/Expensify/App/issues/45137#issuecomment-2227711950?

**Comment by arosiclair** [comment]
Yeah I think this should also work for Xero now.
