### ISSUE TITLE
[HOLD #44016] [Xero Export] Display Xero auto-sync errors and RBRs in NewDot

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#45138]
- HELD on https://github.com/Expensify/App/issues/44015

Main issue: https://github.com/Expensify/Expensify/issues/409245

# Part of QBO Export and Error Handling in NewDot
Main issue: https://github.com/Expensify/Expensify/issues/350150
Doc section: https://docs.google.com/document/d/1aQl-AK_F6IqszWYG2aEllTsD5x3h4b8Zu0XEG0LuQ08/edit#heading=h.pmmx5zp5s75j
Project: [#wave-collect](https://github.com/orgs/Expensify/projects/129)

# Feature Description

As described in the doc, we need to display a RBR when there are errors in a policy connection’s last sync.

The RBR will show on the path to the integration connection settings (Avatar > Workspaces > [Workspace name] > Accounting > Connections):

- LHN Avatar: check if policy.connection.lastSync.isSuccessful is false in the [Indicator](https://github.com/Expensify/App/blob/d3d480545fdea6d51ded5866dd407881857bb04a/src/components/Indicator.tsx#L51)
- InitialSettingsPage: add the same check to [hasGlobalWorkspaceSettingsRBR](https://github.com/Expensify/App/blob/406139cf2120b25c28643f1e728d531fd8848a60/src/pages/settings/InitialSettingsPage.tsx#L189)
- WorkspaceInitialPage: add the same check to the connections menu item [here](https://github.com/Expensify/App/blob/18e2f09bdf5a250aabfa4cb40805b34b714d3420/src/pages/workspace/WorkspaceInitialPage.tsx#L260)
- PolicyAccountingPage: use policy.connection.lastSync.errorMessage to populate the errorText option for the Xero menu item [here](https://github.com/Expensify/App/blob/21abc8957a4127985317444c0fbaff27e6f7de1d/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L165-L196)

When the error is a credentials error (`policy.connection.lastSync.isAuthenticationError` is `true`), we’ll replace the ‘Sync now’ option in the connection’s 3-dot menu with a ‘Reconnect’ option [here](https://github.com/Expensify/App/blob/21abc8957a4127985317444c0fbaff27e6f7de1d/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L128-L133). The option will restart the Xero Auth flow [as described in our initial QBO doc](https://docs.google.com/document/d/1LLrOYRGEb_k_Z6dttcS99zlbCNNdpD1QlXAbFJYbR7g/edit#heading=h.41k48nficw63).

# Manual Test Steps

**Prerequisites**

- Collect workspace with an admin and member
- Setup Xero integration connection

**Steps**
1. Log into Xero and disconnect the Expensify app (Menu > Apps > Overview > Expensify 3-dot menu > Disconnect)
2. Log into NewDot as the admin
3. Verify there's a RBR on the path: Avatar > Workspaces > [Workspace name] > Accounting > Xero
4. Verify a red error message appears on the connection explaining the issue
5. Select Xero's 3-dot menu
6. Verify there’s a “Enter credentials” option
7. Select “Enter credentials”
8. Verify a new window opens to log into Xero

**Comment by lakchote** [comment]
Will be solved by https://github.com/Expensify/App/pull/45251

**Comment by lakchote** [comment]
> Will be solved by #44016

#44016 is still in progress.

**Comment by arosiclair** [comment]
Yeah I don't think there's anything Xero specific we need to do for displaying auto-sync errors. Closing
