### ISSUE TITLE
Report fields - List editor shows Initial value when there is no list value

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45169]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44730
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Click Type > Select List
5. Add name and do not add any list values (important)
6. Note that the confirmation page does not show Initial value if there is no list value
7. Save the list
8. Click on the added list

## Expected Result:
The list editor will not show Initial value if there is no list value

## Actual Result:
The list editor shows Initial value when there is no list value, and it leads to a blank page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2d740424-3bcf-4bdc-8214-ca3741df561c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@rlinoz  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment]
Taking over as I taking care of this project cc @rezkiy37 @waterim

**Comment by rushatgabhane** [comment]
PR reviewed
