### ISSUE TITLE
[HOLD for payment 2024-08-19] Enabling Invoices as a feature on the workspace

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#45168]
# Part of the Invoice project
Main issue: https://github.com/Expensify/Expensify/issues/382977
Doc section: https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#heading=h.jpplu5rcslex
Project: https://github.com/orgs/Expensify/projects/114

# Feature Description
This feature allows users to enable invoicing for their workspaces by adding a toggle in the workspace.

<img width="462" alt="Screenshot 2024-07-10 at 7 22 57 PM" src="https://github.com/Expensify/App/assets/7016692/ae336c86-8bef-4f27-be17-71646a240770">

# Manual Test Steps

Go to workspace settings and enable invoicing and the toggle should remain on
Disable it and it should be toggle off. 
Check that the parameter is correctly saved in the workspace data in onyx

# Automated Tests

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
Preparing the draft PR.

**Comment by danielrvidal** [comment]
@madmax330 I noticed that even when it's enabled, I'm still seeing Send Invoice in my global create. Is that intentional or being covered in another issue?

**Comment by rezkiy37** [comment]
@danielrvidal, yes. FYI: https://github.com/Expensify/App/issues/47023, https://github.com/Expensify/App/issues/47023#issuecomment-2275316181.

**Comment by madmax330** [comment]
Will figure out the payment

**Comment by madmax330** [comment]
@isabelastisser can you arrange the payment for the PR Review for this to @dukenv0307

**Comment by isabelastisser** [comment]
Sure!

@dukenv0307, I sent you an offer in Upwork. Thanks!
