### ISSUE TITLE
[$250] mWeb - Hold - Paying unhold expense but amount shown incorrectly after brief time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45172]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open User B chat
3. Submit 2 expenses
4. Tap on any expense and hold an expense
5. Login in other device as user B
6. Open the report
7. Tap pay elsewhere
8. Select the expense amount which is not hold and pay it

## Expected Result:
Paying unhold expense amount must be shown correctly

## Actual Result:
Paying unhold expense but amount shown incorrectly after brief time. Paid ₹21 shown correctly briefly but changed to paid ₹31 including hold expense amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/421978b7-be6d-4d8b-871b-ed52e7bf875e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c04299729d9d0aaa</li>
        <li>Upwork Job ID: 1815847433544697356</li>
        <li>Last Price Increase: 2024-09-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
I've been playing around with this one but things aren't working as I expect them to. I'm not sure if this is me, a bug or something else. Will come back to this one a little later so I can start with fresh eyes

**Comment by VictoriaExpensify** [comment]
@lanitochka17 - I'm having trouble recreating this. Are you still able to create it on your end?

**Comment by lanitochka17** [comment]
Issue is still reproducible 

https://github.com/user-attachments/assets/a66c955a-ef26-430a-ae8e-a3b983342537

**Comment by VictoriaExpensify** [comment]
Oh sorry, I was recreating the issue on desktop. Let me try this from Android

**Comment by VictoriaExpensify** [comment]
We don't have any proposals for this yet. I don't think it's a high enough priority to increase the price at this point

**Comment by VictoriaExpensify** [comment]
Drop the OD label, MelvinBot!

**Comment by VictoriaExpensify** [comment]
Still no proposals. Will revisit this next week

**Comment by VictoriaExpensify** [comment]
Hmm I'm not sure this issue is significant enough to increase the bounty on it. I don't have time today but I will retest the issue later this week and, if it's still producable, I'll decide what to do

**Comment by VictoriaExpensify** [comment]
Posted to #open_source - no takers yet https://expensify.slack.com/archives/C01GTK53T8Q/p1725330694424789

**Comment by VictoriaExpensify** [comment]
No takers but I still don't think we need to adjust the bounty. I'm going to make this weekly for now.

**Comment by VictoriaExpensify** [comment]
Not overdue. I'm going to check if this is still actually an issue

**Comment by VictoriaExpensify** [comment]
Ok I can't recreate this and we do not have any takers. I'm just going to close this out
