### ISSUE TITLE
[HOLD for payment 2024-11-11] Invoicing details section

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#45176]
# Part of the Invoicing payments project
Main issue: https://github.com/Expensify/Expensify/issues/382977
Doc section: https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#heading=h.xlgprr5mxnso
Project: https://github.com/orgs/Expensify/projects/114/views/3

# Feature Description

# Manual Test Steps

# Automated Tests

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
**Updates:**
- Implemented WorkspaceInvoicingDetailsSection component
- Implement pages to update company name and company website

TODOs:
- Implement forms validation and submitting.

Updates can be tracked in [Draft PR](https://github.com/Expensify/App/pull/46203)

**Comment by VickyStash** [comment]
**Updates:**
- Implemented forms validation, added needed for future TODO's
- Added test steps and part of recordings to the Draft PR. Overall the Draft if almost ready for the review. But I think it makes sense to open it only when https://github.com/Expensify/App/pull/46009 is merged, cause their functionality is overlapping.

**Comment by VickyStash** [comment]
ON HOLD till https://github.com/Expensify/App/pull/46009 is merged

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/46203) has been opened for the review

**Comment by rezkiy37** [comment]
@madmax330 @VickyStash should we close this issue?

**Comment by VickyStash** [comment]
@rezkiy37 We need to make the Invoicing details section:
- be displayed on the Invoice settings screen (mentioned [here](https://github.com/Expensify/App/issues/45175#issuecomment-2404624153) as well)
- integrate the BE calls ([here](https://github.com/Expensify/App/blob/175af25b5ac2645a7d1f7edf87fd35e4529cd9be/src/pages/workspace/invoices/WorkspaceInvoicingDetailsName.tsx#L34) and [here](https://github.com/Expensify/App/blob/175af25b5ac2645a7d1f7edf87fd35e4529cd9be/src/pages/workspace/invoices/WorkspaceInvoicingDetailsWebsite.tsx#L36))

After that we can close the issue.

**Comment by rezkiy37** [comment]
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment]
Actively working on the issue.

**Comment by madmax330** [comment]
@abekkala can we do a $250 payment for @alitoshmatov for the review so we can close this out?

**Comment by madmax330** [comment]
Oh didn't mean to unassign. 
@abekkala  can you take a look at this when you get a chance? https://github.com/Expensify/App/issues/45176#issuecomment-2475984573

**Comment by abekkala** [comment]
@madmax330 : @alitoshmatov is paid via NewDot

> @abekkala can we do a $500 payment for @alitoshmatov for the 2 reviews so we can close this out?

___

### PAYMENT SUMMARY

- @alitoshmatov [$500] Two PR Reviews - paid via NewDot

**Comment by alitoshmatov** [comment]
Requested on NewDot

**Comment by JmillsExpensify** [comment]
$500 approved for @alitoshmatov
