### ISSUE TITLE
[HIGH] Showing the paid invoice in the invoice room

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#45170]
# Part of the Invoicing payments project
Main issue: https://github.com/orgs/Expensify/projects/114
Doc section: https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#heading=h.drd9tmsdkoix
Project: https://github.com/orgs/Expensify/projects/114

# Feature Description

Once an invoice is paid it should show accordingly in the UI

# Manual Test Steps

Create an invoice, pay it and make sure it displays correctly

# Automated Tests

**Comment by rezkiy37** [comment]
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment]
Actively working on the issue. I've opened a draft PR (https://github.com/Expensify/App/pull/48014). 

<img width="888" alt="Screenshot 2024-08-26 at 18 03 01" src="https://github.com/user-attachments/assets/3c1a0fd7-19c8-42de-b1bd-985e5aa41005">

**Comment by rezkiy37** [comment]
I've opened the PR (https://github.com/Expensify/App/pull/48014) for review 🙂

**Comment by danielrvidal** [comment]
Awesome, thank you! Please let us know if you need any help!

**Comment by rezkiy37** [comment]
Hey!
I will be OOO from 04.09 (_afternoon_) till 09.09. I will continue to work on this one once I am back.

**Comment by c3024** [comment]
I reviewed the related PR #48014. It was [deployed to production](https://github.com/Expensify/App/issues/48664#issuecomment-2338463845) on 9-Sep. Payment is due today.

@madmax330 Can you please assign a BZ for payment? Thanks!

**Comment by madmax330** [comment]
@dylanexpensify  👋🏽  We only need to make the payment for the review here.


@c3024 do you get paid in upwork or expensify?

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @c3024 $250 via Upwork!

Please apply/request!

**Comment by dylanexpensify** [comment]
@c3024 apply [here](https://www.upwork.com/jobs/~021836349458290525602)! 🙇‍♂️

**Comment by c3024** [comment]
@dylanexpensify Thanks. Applied!

**Comment by mitul69** [comment]
@dylanexpensify  I have applied

**Comment by mitul69** [comment]
> 📣 @mitul69! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Make sure you've read and understood the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md).
> 2. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 3. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 4. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Your Expensify account email: patelmit69@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/mitulpatel116

**Comment by c3024** [comment]
@dylanexpensify, gentle bump on payment for this. Thanks!

**Comment by dylanexpensify** [comment]
On it - apologies!

**Comment by dylanexpensify** [comment]
Offers are waiting for acceptance @Krishna2323 @mitul69

**Comment by c3024** [comment]
Accepted @dylanexpensify. Only I need to be paid here for the reviewer role. The PR was handled by an external agency and no payment needs to be made for contributor role to anyone. Thanks!

**Comment by dylanexpensify** [comment]
nice paid!
