### ISSUE TITLE
[HOLD for payment 2024-08-19] Updating Invoice creation flow

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#45173]
# Part of the Invoicing payments project
Main issue: https://github.com/Expensify/Expensify/issues/382977
Doc section: https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#heading=h.fckbittkm504
Project: https://github.com/orgs/Expensify/projects/114

# Feature Description

Relevant doc section: https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#heading=h.jxlg73mn39np

# Manual Test Steps

Create an invoice and make sure we're using the new flow mentioned in the design doc

# Automated Tests

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
**Updates:**
See this [comment](https://github.com/Expensify/App/issues/45174#issuecomment-2245448900)

**Comment by VickyStash** [comment]
**Updates:** the [PR](https://github.com/Expensify/App/pull/46009) has been opened for the review

**Comment by madmax330** [comment]
Just waiting on c+ payment I think

**Comment by madmax330** [comment]
@johncschuster for this one we just need to pay @getusha for the Pr review

**Comment by johncschuster** [comment]
On it!

**Comment by johncschuster** [comment]
Payment Summary:

Contributor+: @getusha owed $250 via NewDot

**Comment by johncschuster** [comment]
@madmax330, will you be adding regression test steps in this issue, or will they be added elsewhere?

**Comment by garrettmknight** [comment]
$250 approved for @getusha

**Comment by johncschuster** [comment]
@madmax330 bump on the question above!

**Comment by johncschuster** [comment]
No worries! Thanks, @madmax330! I'll go ahead and close this then.
