### ISSUE TITLE
Invoice bank accounts section

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#45177]
# Part of the Invoicing payments project
Main issue: https://github.com/Expensify/Expensify/issues/382977
Doc section: https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#heading=h.27ed1nyheq5
Project: https://github.com/orgs/Expensify/projects/114/views/3

# Feature Description

# Manual Test Steps

# Automated Tests

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by danielrvidal** [comment]
@rezkiy37 is this done now or are we waiting for anything?

**Comment by rezkiy37** [comment]
Discussion in **[Slack](https://callstack-hq.slack.com/archives/CSL3XBCCR/p1724798747491519)**.

**Comment by rezkiy37** [comment]
Hey!
I will be OOO from 04.09 (_afternoon_) till 09.09. I will continue to work on this one once I am back.

**Comment by rezkiy37** [comment]
Hello!
I am OOO from 19.09 - 23.09. I will continue to work on this one when I am back. Meanwhile, @waterim will work on this issue.

**Comment by rezkiy37** [comment]
I've integrated the `SetInvoicingTransferBankAccount` command. I am implementing other front-end parts.

**Comment by Pujan92** [comment]
I requested for the [doc](https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#heading=h.27ed1nyheq5) access

**Comment by davidcardoza** [comment]
What's the latest update on this?

**Comment by Pujan92** [comment]
Changes were in production 3 weeks ago, so now this is due for the payment.

**Comment by rezkiy37** [comment]
The PR (https://github.com/Expensify/App/pull/47218) was merged. So we can finish with the issue.

**Comment by madmax330** [comment]
@sonialiap for this one can you just do the payment for 2 reviews for @Pujan92 ?

**Comment by sonialiap** [comment]
Payment summary:
- @Pujan92 $500 per Max's comment, for review of two PRs - Please request in ND
