### ISSUE TITLE
[HOLD for payment 2024-10-16] Invoice balance section

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#45179]
# Part of the Invoicing payments project
Main issue: https://github.com/Expensify/Expensify/issues/382977
Doc section: https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#bookmark=id.rrjlhda54yy
Project: https://github.com/orgs/Expensify/projects/114/views/3

# Feature Description

# Manual Test Steps

# Automated Tests

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
I've implemented the raw balance section. Continue working.

<details><summary>Details</summary>

<img width="1728" alt="Screenshot 2024-08-05 at 17 05 57" src="https://github.com/user-attachments/assets/436d2747-338d-478c-9146-6677f3c02c23">

</details>

**Comment by rezkiy37** [comment]
Actively working on the issue.

**Comment by rezkiy37** [comment]
I am pretty close to opening the PR (https://github.com/Expensify/App/pull/46813). Asked in Slack:
1. https://callstack-hq.slack.com/archives/CSL3XBCCR/p1723043542328539
2. https://callstack-hq.slack.com/archives/CSL3XBCCR/p1723044989711819

**Comment by rezkiy37** [comment]
I am attaching examples of how it works and looks like.

cc @madmax330 

<details><summary>Details</summary>

### Success

https://github.com/user-attachments/assets/7ab72220-b837-4607-b17f-059858281949

### Disabled

<img width="1728" alt="Disabled" src="https://github.com/user-attachments/assets/950319c6-c72b-4147-ac68-546ce2ddebf3">

### Error

<img width="1728" alt="Error" src="https://github.com/user-attachments/assets/a6c14629-933f-42e5-a9d9-b29919149b26">

</details>

**Comment by rezkiy37** [comment]
Actively working on the PR.

**Comment by danielrvidal** [comment]
Any updates on this one? I *think* this needs to be done for SuiteWorld by Sept 9th as well but am not sure.

**Comment by rezkiy37** [comment]
Discussion in **[Slack](https://callstack-hq.slack.com/archives/CSL3XBCCR/p1724798751378279)**.

**Comment by rezkiy37** [comment]
Hey!
I will be OOO from 04.09 (_afternoon_) till 09.09. I will continue to work on this one once I am back.

**Comment by rezkiy37** [comment]
Hello!
I am OOO from 19.09 - 23.09. I will continue to work on this one when I am back. Meanwhile, @waterim will work on this issue.

**Comment by madmax330** [comment]
@OfstadC for this one can you just do the C+ review payment for @akinwale ?

**Comment by OfstadC** [comment]
Sure! Just to confirm we'll need to issue $500 (I see this is a Critical issue) to @akinwale . Is that correct @madmax330 ? 😃

**Comment by madmax330** [comment]
It's $250

**Comment by OfstadC** [comment]
@akinwale Offer sent [here](https://www.upwork.com/nx/wm/offer/104466557) 😃

**Comment by OfstadC** [comment]
## Payment Summary 
- Paid @akinwale $250 [via Upwork ](https://www.upwork.com/nx/wm/workroom/38726467/overview)
