### ISSUE TITLE
[HOLD for payment 2024-11-05] Update Invoices setting screen

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#45175]
# Part of the Invoicing payments project
Main issue: https://github.com/Expensify/Expensify/issues/382977
Doc section: https://docs.google.com/document/d/1CF5gw-SJx7ckZCgTJNj1IqBnsRuSxD2Bfd_uB5rRGxk/edit#heading=h.sidhyk9taftq
Project: https://github.com/orgs/Expensify/projects/114/views/3

# Feature Description

# Manual Test Steps

# Automated Tests

**Comment by danielrvidal** [comment]
I think this is just waiting for payment, right @madmax330 ?

**Comment by madmax330** [comment]
Yeah we need to pay the c+ for their review

**Comment by madmax330** [comment]
cc @VickyStash  I don't think we want to remove it right?

**Comment by VickyStash** [comment]
Yeah, `ROUTES.WORKSPACE_INVOICES` route will be reused in the future.

**Comment by rezkiy37** [comment]
@madmax330 @VickyStash should we close this issue?

**Comment by VickyStash** [comment]
@rezkiy37 I think we still need to align Invoice settings screen with the mockup.
![image](https://github.com/user-attachments/assets/76fdb10a-2c4b-44a9-8922-d2c68d7b0e63)

We need to:
- Remove outdated sections
- Make Invoicing details section be visible
- Update the heading

After that we can close the issue.

**Comment by rezkiy37** [comment]
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment]
Actively working on the issue.

**Comment by greg-schroeder** [comment]
Payment summary:

C+: @fedirjh - $250 - You can make a manual request
