### ISSUE TITLE
Login – Unable to log in via Magic link, enter magic code page opens

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706293
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with new account
3. Copy the Magic link and change it to staging
4. Open a new tab and navigate to the staging magic link

## Expected Result:
Abracadabra page is displayed. Now logged in 2 tabs, we have KI for Abracadabra page https://github.com/Expensify/App/issues/44600.

## Actual Result:
Enter magic code page opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a638bbd5-0d0a-413c-8fb2-276a0009b876

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by marcochavezf** [comment]
Seems this is the offending PR https://github.com/Expensify/App/pull/44536

**Comment by marcochavezf** [comment]
Yup, I reverted the changes locally and I can confirm that's the offending PR cc @filip-solecki @adamgrzybowski @allgandalf @mountiny

**Comment by danieldoglas** [comment]
I don't think this is related to backend, removing the `DeployBlocker` tag

**Comment by Julesssss** [comment]
> Abracadabra page is displayed. Now logged in 2 tabs, we have KI for Abracadabra page https://github.com/Expensify/App/issues/44600.

@lanitochka17 I'm a bit confused by this ^

- So we are logged in, but in both tabs?
- What does KI stand for? Does that mean with have an existing bug for this issue?

**Comment by marcochavezf** [comment]
PR to revert the offending PR [here](https://github.com/Expensify/App/pull/45299)

**Comment by filip-solecki** [comment]
Hi! I think we don't have to revert mentioned PR: here is the [PR](https://github.com/Expensify/App/pull/45301) with fix

**Comment by marcochavezf** [comment]
Hi @filip-solecki, seems the offending PR also caused this issue https://github.com/Expensify/App/issues/45284

**Comment by filip-solecki** [comment]
I think my PR might solve also this issue. I'll try to check asap

**Comment by filip-solecki** [comment]
Confirmed - my fix works in both cases, but I see it is too late

**Comment by marcochavezf** [comment]
Sorry, we confirmed the offending PR was causing another deploy blocker, and we can't delay the deployment 😞

**Comment by filip-solecki** [comment]
Ok, I'll prepare another PR tomorrow with all fixes 🙂

**Comment by Julesssss** [comment]
> I think my PR might solve also this issue. I'll try to check asap

Can you please share the link?

**Comment by marcochavezf** [comment]
Tested out with the CP'ed PR to staging and looks good:

https://github.com/Expensify/App/assets/6829422/407370fe-fa0d-421a-b84b-111700b9ba01

Closing it out

**Comment by filip-solecki** [comment]
> > I think my PR might solve also this issue. I'll try to check asap
> 
> Can you please share the link?

Sure, [here it is](https://github.com/Expensify/App/pull/45301)

**Comment by kavimuru** [comment]
@Julesssss Issue is fixed.

https://github.com/user-attachments/assets/cefe68bd-8f4b-4a69-ae06-a41e43d873a4

**Comment by Julesssss** [comment]
Excellent, thank you @kavimuru
