### ISSUE TITLE
Expenses - Pay instead of review in IOU header message for approver

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706625
**Email or phone of affected tester (no customers):** qaooxx+55@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create Collect workspace
2. Invite Employee and Employee Approver
3. OldDot > Approval mode > Submit and Approve > to Employee Approver

Steps:
1. As Employee submit expenses in workspace chat
2. As Employee Approver go to IOU details

## Expected Result:
Header message should say "waiting for the you (Approver) to review these expenses"

## Actual Result:
Header message says "waiting for the you to pay these expenses"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/94a756ff-547c-4faa-b8cf-7af26ed63f2a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment]
Will try reproducing now 😃

**Comment by OfstadC** [comment]
I'm not 100% sure what the expected behavior is here - so I need to dig a little more

**Comment by OfstadC** [comment]
I was configuring the workflow in Classic which was not helpful 😅 . I took the video way too literally. 

But can confirm this is a thing. 

<img width="794" alt="image" src="https://github.com/user-attachments/assets/2a0fac72-3282-48a5-9ef1-2719cb53193a">
<img width="664" alt="image" src="https://github.com/user-attachments/assets/7603c679-2e8d-46fb-9e07-9fff14f77410">
<img width="683" alt="image" src="https://github.com/user-attachments/assets/52f20e09-6030-48f4-99ee-2b8907635a45">

**Comment by dangrous** [comment]
@dylanexpensify @JmillsExpensify According to [the doc](https://docs.google.com/document/d/1mUUQzep18IWdZpwG6Qqtw9JH0dvLMvLXh-KTn_B51I4/edit#heading=h.mnjguil21u0a) this change is expected but wanted to confirm before closing out - are we replacing all instances of "review" with "pay"? Or does this change into "approve"?

The old message is sort of listed as being converted into both "Waiting for userApprover to approve expense(s)" AND "Waiting for userAdmin to pay expense(s)" - the 2nd and 3rd bullets in the list in the doc.

**Comment by mountiny** [comment]
@dangrous given the steps in the OP, the reports should not be in Approved state, if that is the case, its a really bad bug :/ 

@Beamanator would be a great resource for this knowledge. Can you reproduce easily with this setup @dangrous?

**Comment by dangrous** [comment]
yep! the steps in the "Action Performed" work like a charm.

I think i WAS wrong about it coming in as approved after trying it again... I'm not sure why my tests were saying that. Still trying to figure it out, it may be next steps after all.

**Comment by dangrous** [comment]
okay yeah I think I've got this right. I had to update the tests accordingly but I think they were wrong before - mind taking a look at [this commit](https://github.com/Expensify/Web-Expensify/pull/42839/commits/204dbf0933a2223d3df2f517d4430574c4e884a5) when you have a moment @mountiny? I'm pretty sure if we're not on submit and close, then it should be approve, not pay...

**Comment by mountiny** [comment]
@dangrous commented, I think the changes make sense, but left one question
