### ISSUE TITLE
mWeb - Room - On creating room with public visibility, whisper is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4704953
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login as gmail user
3. Tap fab -- start room
4. Create a room with visibility " Public"

## Expected Result:
On creating room with public visibility, whisper must be shown

## Actual Result:
On creating room with public visibility, whisper is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b8b36e5e-732c-41ce-b4c9-4fb0e24efb8e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by joekaufmanexpensify** [comment]
@lanitochka17 Could you share why you think it is expected that a whisper message is sent when creating a public room? Is that listed somewhere as expected behavior? I am not seeing a whisper message when creating a public room, on android mWeb (or any platform). But I'm also not seeing that listed as expected behavior, nor am I seeing it when I create a room of any other type. 

If a welcome message is set, you should see it when you join a room, but there isn't one set when you create a room, so this feels expected to me.

**Comment by joekaufmanexpensify** [comment]
Going to close this for now as I think this is expected behavior. Please let me know if you see it written somewhere that there should be a welcome message when creating a public room.
