### ISSUE TITLE
[HybridApp] - Reintroduce log out button on HybridApp but log out to OldApp log out screen

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#45214]
## Problem
In https://github.com/Expensify/App/issues/43336 we completely removed the Sign out button from New Expensify while on HybridApp, which was a good first version, but it's a weird user experience that users have noticed.

## Solution
Reintroduce the Sign out button, but instead of taking you to the NewDot sign in screen, we should take the user to the OldDot sign in screen.

cc @staszekscp @WoLewicki

This is a polish item, so let's save it until we are finished with all other implementation issues.

**Comment by staszekscp** [comment]
Since I'm currently waiting for some Crashlytics news, I'm going to take care of this issue :)

**Comment by trjExpensify** [comment]
Nice, thanks @staszekscp. Assigning you!
