### ISSUE TITLE
mWeb - Search - Search page shows attachment as html code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45215]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open any 1:1 DM
3. Enter a text & tap plus icon and add an attachment
4. Send the message
5. Tap app back button
6. Tap search icon

## Expected Result:
Search page must not show attachment as html code

## Actual Result:
Search page shows attachment as html code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b9acc882-9b52-4b53-9605-367e2313a926

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
BE issue, the `lastMessageText` contains the `<br />` tag.
<img width="365" alt="image" src="https://github.com/Expensify/App/assets/50919443/190b6f51-a3be-4175-b965-5a7edf5e0411">

**Comment by johncschuster** [comment]
Taking it internal

**Comment by johncschuster** [comment]
Ah, it looks like I placed this in the wrong project. Updated to #wave-collect.

**Comment by johncschuster** [comment]
[Raising in Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1721337548644069)

**Comment by johncschuster** [comment]
Chatted with Tom, and he suggested I bring this to #vip-vsb. Checking the priority there.
