### ISSUE TITLE
[PAID] Workspace - Endless skeleton loader after login if the account is added to a workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45212]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/Web-Expensify/pull/42621 https://github.com/Expensify/Web-Expensify/pull/42602
## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. User A: Log in with a new Gmail account
3. User A: Create a workspace
4. User A: Navigate to Workspace settings - Members
5. User A: Invite a Gmail address that doesn't have an account yet (User B)
6. User B: Open Chrome in incognito mode
7. User B: Navigate to https://staging.new.expensify.com/
8. User B: Log in

## Expected Result:
The workspace chat should load with minimal loading animation

## Actual Result:
Endless skeleton loader after login if the account is added to a workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a3bfc0f2-a321-4512-b499-d0932014f38d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment]
@francoisl  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
Sorry for the confusion
This issue for OlDot

**Comment by francoisl** [comment]
I can repro too.

One difference between prod and staging is that on production there's a call to `OpenReport` at some point after signing in, which I don't see on staging. I don't know if that's the reason, but could be a lead.

Production | Staging
--- | ---
<img width="1284" alt="image" src="https://github.com/Expensify/App/assets/2229301/a608ff29-7cd7-415e-976b-6b0ca4485b87"> | <img width="1284" alt="image" src="https://github.com/Expensify/App/assets/2229301/d1b616ad-a876-4ef3-9ac4-c8c558f28ffc">

**Comment by francoisl** [comment]
Ran a git bisect, this appears to come from commit [fce482497a3d6c0c5b2d93de6688e01a653c8d27](https://github.com/Expensify/App/commit/fce482497a3d6c0c5b2d93de6688e01a653c8d27)  in https://github.com/Expensify/App/pull/44955. 

Did a local revert and it seems to fix the issue. Going to see if I can figure out the issue, otherwise we can proceed with the revert.

**Comment by francoisl** [comment]
Ok it seems like partially reverting [this change](https://github.com/Expensify/App/commit/fce482497a3d6c0c5b2d93de6688e01a653c8d27#diff-68b13bc8344820144538408415f307efee198ccc63977ba318c4234102ec3917) and moving back the `lastAccessedReportID` as a dependency of the `useEffect` fixes the issue. Going to run more tests and submit a fix.

**Comment by mountiny** [comment]
cc @kosmydel for visibility

**Comment by francoisl** [comment]
Reassigning C+s because @rayane-djouah is online now and able to review the fix.

**Comment by kosmydel** [comment]
Thanks for handling that.

> Ok it seems like partially reverting [this change](https://github.com/Expensify/App/commit/fce482497a3d6c0c5b2d93de6688e01a653c8d27#diff-68b13bc8344820144538408415f307efee198ccc63977ba318c4234102ec3917) and moving back the `lastAccessedReportID` as a dependency of the `useEffect` fixes the issue. Going to run more tests and submit a fix.

This might degrade performance a bit, but together with 2nd PR it should work fine for now. I will revisit it, probably next week, as I have other projects in progress.

**Comment by strepanier03** [comment]
@rayane-djouah - Thanks for the checklist!

I sent you an offer on Upwork and will keep an eye for the acceptance email to come through.

**Comment by strepanier03** [comment]
Paid out the contract and closed it. Thanks @rayane-djouah for accepting it so quickly.
