### ISSUE TITLE
Tags – Unable to add multiple levels of tags

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45216]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4711713
**Email or phone of affected tester (no customers):** ponikarchuks+310724@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.expensify.com/
2. Log in
3. Create a policy
4. Navigate to Settings/Workspaces
5. Click on WS
6. Open Tags
7. Enable Use multiple levels of tags
8. Click on Import from Spreadsheet and add file with multiple levels of tags
9. Click on Upload tags

## Expected Result:
Tags are added

## Actual Result:
Oops... an error has occurred!

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/29859f2a-7162-4429-8bca-a13de149fe1d

[Bug6538175_1720632912106!2_Independent_-_Multi_Level_tags.csv](https://github.com/user-attachments/files/16169051/Bug6538175_1720632912106.2_Independent_-_Multi_Level_tags.csv)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
This is a OldDot bug. I am closing this and creating GH ticket in E/E repository.
