### ISSUE TITLE
[HybridApp] - Switching co-pilot does not update tasks

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#45218]
## Problem
From @coleaeason:

> I switched to copilot mode and back to my account and the inbox tasks from the other account are now showing in my inbox but using the data from my account

## Solution

Fix it! ⚡

**Comment by staszekscp** [comment]
I have a follow-up question here - is it possible to use copilot mode on NewDot at this moment? I noticed that whenever I switch to copilot _**and**_ kill the app, the `Try New Expensify` button disappears (without killing it is visible)

**Comment by AndrewGable** [comment]
I do not think we have Co-Pilot on NewDot yet

**Comment by AndrewGable** [comment]
I would assume Cole was using Co-pilot without HybridApp (just using Inbox to approve reports)

**Comment by AndrewGable** [comment]
Being worked on by @staszekscp, you can ignore @greg-schroeder

**Comment by greg-schroeder** [comment]
Okay thanks @AndrewGable

**Comment by staszekscp** [comment]
I had a bit of time in between builds so here's [the PR](https://github.com/Expensify/Mobile-Expensify/pull/12872)!
