### ISSUE TITLE
[HybridApp] - Try New Expensify option missing from menu in OD app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+0710pm7@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44903
## Action Performed:
1. Open the OD app and log in with a new account

## Expected Result:
"Try New Expensify" option is displayed below Settings

## Actual Result:
"Try New Expensify" option is missing from the menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cf877dc9-4170-4d22-a224-fea2645a57ea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
This is expected for users who do not have the `tryNewDot.classicRedirect` NVP set per https://github.com/Expensify/App/issues/44793

I will write a JS snippet for testing to make this easier.

**Comment by AndrewGable** [comment]
@lanitochka17 - Can you please notify all testers that if they are testing HybridApp on new accounts they need to run this JS snippet on expensify.com in order to see the `Try New Expensify` button?

`NVP.set('tryNewDot', {classicRedirect: {dismissed: "true"}});`

Thank you!
