### ISSUE TITLE
[HybridApp] - Dark mode issues

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#45217]
## Problem
Even after https://github.com/Expensify/App/issues/43511 was deployed, we are still seeing a few issues with fields being black when in Dark Mode and using HybridApp

![IMG_7284](https://github.com/Expensify/App/assets/2838819/803644ba-c094-4032-8b21-b19d25b783b0)
![IMG_7283](https://github.com/Expensify/App/assets/2838819/186700d4-77a4-4484-b874-abac19b0875e)
![IMG_7282](https://github.com/Expensify/App/assets/2838819/5e95f846-dff4-43bc-a7f9-19049ede96e6)

## Solution

Fix it!

cc @staszekscp

**Comment by staszekscp** [comment]
Hey! I've just tested the newest TestFlight and I don't see the issue there 😢  (I've used `9.0.6-1`)

**Comment by AndrewGable** [comment]
I see this on the latest TF 9.0.6.2

![image](https://github.com/user-attachments/assets/38cab58a-c9f0-4c34-8353-e1c31da4fb67)

**Comment by AndrewGable** [comment]
This is when you have an expense to review for approval via Inbox, not your own expense.

**Comment by AndrewGable** [comment]
Not sure exactly where to look, but this is displayed in a modal which might have different settings for default background?

**Comment by staszekscp** [comment]
Oh, I see that now, it seems to be connected to the modal, indeed. Thanks!

**Comment by AndrewGable** [comment]
@coleaeason - Can you confirm all dark mode issues are fixed on 9.0.6.3? I am seeing them fixed in all guided review cases.
