### ISSUE TITLE
[$250] After account creation via Classic Expensify, the user is redirected to New Expensify in a logged-out state

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#45229]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4711723
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal - team
**Slack conversation:**

## Action Performed:

1. Open staging.expensify.com
2. Select 'Email' option
3. Enter a new email address
4. Click on 'Next' button
5. Click on 'Join' button

## Expected Result:
After account creation via Classic Expensify, the user is redirected to New Expensify logged into the newly created account.

## Actual Result:
After account creation via Classic Expensify, the user is redirected to New Expensify in a logged-out state.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[Bug6538170_1720632753262!Redirection-failed-logs-od-ND2027292.txt](https://github.com/user-attachments/files/16170108/Bug6538170_1720632753262.Redirection-failed-logs-od-ND2027292.txt)

https://github.com/Expensify/App/assets/43996225/a4f4ac32-afee-4fee-af63-870d184a326b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6ad5c6254fdb34b</li>
        <li>Upwork Job ID: 1811449062626659573</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by kavimuru** [comment]
@robertjchen FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment]
We think this bug might be related to #vip-vsb

**Comment by danieldoglas** [comment]
I don't think this is related to backend, removing the `DeployBlocker` tag

**Comment by miljakljajic** [comment]
Updating the labels accordingly

**Comment by kabeer95** [comment]
Issue Report: User Redirected to New Expensify in Logged-out State After Account Creation via Classic Expensify

Summary:

When a user creates an account via Classic Expensify, they are redirected to New Expensify in a logged-out state, requiring them to log in again to access their account.

Steps to Reproduce:

Navigate to Classic Expensify and create a new account.
Complete the account creation process.
Observe the redirect to New Expensify.
Expected Result:

The user should be redirected to New Expensify in a logged-in state, with access to their newly created account.

Actual Result:

The user is redirected to New Expensify in a logged-out state, requiring them to log in again to access their account.

Impact:

This issue can cause frustration and confusion for new users, leading to a poor onboarding experience and potential abandonment of the platform.

Proposed Solution:

To resolve this issue, we recommend updating the redirect logic to maintain the user's login session when redirecting from Classic Expensify to New Expensify. This can be achieved by:

Implementing a single sign-on (SSO) solution to share authentication between Classic Expensify and New Expensify.
Passing an authentication token or session ID as a parameter in the redirect URL.
Code Example:

// Current implementation
window.location.href = 'https://new.expensify.com';

// Proposed solution
const authToken = getAuthToken();
window.location.href = `https://new.expensify.com?auth_token=${authToken}`;
Estimated Development Time:

We estimate [X] hours to implement this solution and update the redirect logic to maintain the user's login session.

Priority:

We consider this issue a high priority, as it affects the user experience and onboarding process for new users.

Please let us know if you would like to discuss this issue further or proceed with implementation.

**Comment by kavimuru** [comment]
@Julesssss Issue is fixed. 

https://github.com/user-attachments/assets/ae6dba04-3668-4277-be14-c77e58aa4bd4
