### ISSUE TITLE
[$250] [HOLD for payment 2024-08-07] Unable to make the archived chats in the LHN to read

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45228]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1720290639217409

## Action Performed:
Precondition : Have an archived workspace chat in the account
1. Open the report 
2. Click on the archived chat in the LHN which is `unread`
## Expected Result:
Chat should be read
## Actual Result:
Still showing as unread and unable to make it read
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (13)](https://github.com/Expensify/App/assets/38435837/54fa1945-10ba-48a9-a2b3-62538301f188)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ff42d6c7196dc02</li>
        <li>Upwork Job ID: 1829034655875781794</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 103729872</li>
</ul></li>
    </ul>
</details>

**Comment by quinthar** [comment]
I think this is fixed.

**Comment by VictoriaExpensify** [comment]
Hey @mkhutornyi - can you please accept the[ job offer](https://www.upwork.com/nx/wm/offer/103729872) and I'll organise payment

**Comment by quinthar** [comment]
What are the next steps here to make this not overdue?

**Comment by VictoriaExpensify** [comment]
I was just waiting for @mkhutornyi to accept the offer so I can make payment, but the issue wasn't starred to me so I missed it.

Making payment now then we can close this out.

**Comment by VictoriaExpensify** [comment]
**Payment Summary:**
Contributor+: @mkhutornyi paid $250 via [Upwork](https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/38225097)

Thanks for your work on this issue!
