### ISSUE TITLE
[$500] Chat - Page reloads and green line disappears when open unread chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
 
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4710813&group_by=cases:section_id&group_order=asc&group_id=296775
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Preconditions:
1. User A and User B (android) have previous chat history

Steps:
1. User B is on LHN
2. User A sends a message to user B
3. User B opens the chat with User A

## Expected Result:
There should be a green line above the new message

## Actual Result:
Page reloads and green line disappears when open unread chat

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/6f8b57f5-6a4a-4a3c-9beb-5fd9aedd7e4c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e0c6e552db58a8e8</li>
        <li>Upwork Job ID: 1811211901294181829</li>
        <li>Last Price Increase: 2024-07-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by m-natarajan** [comment]
@marcaaron FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment]
This looks pretty unexpected to me. Asked QA if it's consistently reproducible. Gonna make it External to get some eyes.

**Comment by danieldoglas** [comment]
I don't think this is related to backend, removing the `DeployBlocker` tag

**Comment by sakluger** [comment]
QA confirmed that this is consistently reproducible, at least when using the accounts gocemate+a608@gmail.com and mvtutest@gmail.com.

**Comment by sakluger** [comment]
My mistake - I was looking at the wrong Slack thread. Here's the correct thread: https://expensify.slack.com/archives/C9YU7BX5M/p1720658194863959.

QA has not yet confirmed whether this is consistently reproducible.

**Comment by Julesssss** [comment]
Bumped for a QA update

**Comment by Julesssss** [comment]
This is still consistently reproducable ([QA test](https://expensify.slack.com/archives/C9YU7BX5M/p1720794652715329?thread_ts=1720658194.863959&cid=C9YU7BX5M))

**Comment by kavimuru** [comment]
Bug is fixed in 9.0.6-8

https://github.com/user-attachments/assets/f8dac974-f9bf-41d3-bc29-1bff0b69e69a


https://github.com/user-attachments/assets/38af0d28-4048-430f-af43-a031b92539cc
