### ISSUE TITLE
[$250] Login - Endless loading when login existing account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45225]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a608@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Login with existing account

## Expected Result:
Last visited chat should be displayed

## Actual Result:
There is a endless loading when login existing gmail or expensifail e-mail account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9b61e12d-4052-42c1-8ec6-43df0ac156b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1b081cc7a723886</li>
        <li>Upwork Job ID: 1811211337050638831</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by lanitochka17** [comment]
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment]
I can repro this so it's a blocker for sure. No idea what's causing it.

**Comment by danieldoglas** [comment]
I don't think this is related to backend, removing the `DeployBlocker` tag

**Comment by kavimuru** [comment]
@Julesssss this issue is fixed.

https://github.com/user-attachments/assets/b77287de-dfab-4330-9735-dc99f5743feb

**Comment by Julesssss** [comment]
> I still can reproduce. You can try to reload the app.

I'm unable to repro on staging, so perhaps this will reoccur once we deploy again. Let's leave it as not a blocker in the meantime.

**Comment by marcaaron** [comment]
I'm gonna close this and we can reopen if it's still reproducible. If we do reopen please provide more information about how to reproduce if possible.

**Comment by marcaaron** [comment]
Issues are reported for the staging branch. Can you reproduce it there? What other information can you share?
