### ISSUE TITLE
[HOLD for payment 2024-08-13] [Free Trial] [FE] Getting onboarding chat reportID from nvp

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#45238]
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1720634542760399?thread_ts=1720453770.962419&cid=C036QM0SLJK). 

This is the issue @pac-guerreiro will link his PR to for the FE updates discussed [in thread](https://expensify.slack.com/archives/C036QM0SLJK/p1720489172645919?thread_ts=1720453770.962419&cid=C036QM0SLJK). 

We've added the chatReportID to onboarding NVP on the backend, so here we need to use it to decide where to put the free trial stuff, so it's more robust than simply relying on odd/even accountIDs like the A/B testing does for onboarding tasks.  

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by trjExpensify** [comment]
Assigned!

**Comment by trjExpensify** [comment]
PR is deployed to staging.

**Comment by trjExpensify** [comment]
Going to hold off on payment until we get this PR merged: https://github.com/Expensify/App/pull/45785

**Comment by trjExpensify** [comment]
PR hit staging 4 days ago.

**Comment by trjExpensify** [comment]
no need for a regression test here. Payment summary as follows: 

- $250 to @rojiphil for the C+ review. 

Offer sent!

**Comment by rojiphil** [comment]
@trjExpensify Offer Accepted. Thanks.

**Comment by trjExpensify** [comment]
Paid, closing!
