### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Approved expenses are showing pinned expenses with RBR 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45230]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720606818055389

## Action Performed:
1. Created expenses with tags `departments`
2. The report was approved
3. After a while Tags `Departments` does not exist or deleted
4. Log in to the app
4. Observe the LHN
## Expected Result:
Approved expenses shouldn't have an RBR red dot in the LHN, nor should the expense be pinned. 
## Actual Result:
Approved expenses are showing with RBR red dot in the LHN, and the expense is pinned.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![CleanShot 2024-07-10 at 20 20 59@2x](https://github.com/Expensify/App/assets/38435837/04316417-5172-4e31-9309-56732138f85b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b843922542221f31</li>
        <li>Upwork Job ID: 1811554062884646329</li>
        <li>Last Price Increase: 2024-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103243092</li>
<li>dominictb | Contributor | 103243093</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
confirming in thread: https://expensify.slack.com/archives/C049HHMV9SM/p1720606818055389

Seems weird Jon hasn't been paid since Jan 2024. 🤔

**Comment by trjExpensify** [comment]
Alright, Jon confirmed the history doesn't contain any previous reimbursement reportAction. The report was only approved on Jan 27th.

**Comment by trjExpensify** [comment]
I can repro this pretty easily.

1. Enable "category required" on the workspace
2. Submit a couple of expenses without categories
3. Approve the expense report
4. Observe the two expenses remain pinned in the LHN with a red dot

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/a6f5663d-146b-46f8-8b00-0e9cbc703cda">

I took it further to pay the expense report and the red dots and pinning are removed when paid, which we expect:

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/f172ec4a-42f7-41c2-81ba-790a72fd91b7">

CC: @JmillsExpensify I think we put this one in #wave-control as violations polish. Putting it there, but let me know if you disagree with that.

**Comment by situchan** [comment]
@trjExpensify we wanna remove RBR from transaction detail reports (1, 3) in LHN but still show RBR in expense report (2)?

![image](https://github.com/user-attachments/assets/1abad113-1726-48d8-ad5f-10bf07c9ccee)

**Comment by trjExpensify** [comment]
@situchan what do you think of the proposal?

**Comment by situchan** [comment]
updating today

**Comment by situchan** [comment]
@dominictb I am still seeing RBR after replacing isSettled with isReportApproved

**Comment by situchan** [comment]
@dominictb I don't think your additional notes are needed. Tom's RBR in expense report should be showing for different reason (not related to transaction violations).
Let's just fix "RBR display bug" (RBR -> no RBR). No need to fix "RBR hidden bug?" (no RBR > RBR)

report type | Before approval | After approval (before fix) | After approval (after fix)
--- | --- | --- | ---
expense report | 🔴 | 🔴 | 🔴
expense report |  |  | 
transaction detail | 🔴 | 🔴 (bug to fix) |
transaction detail |  |  |

**Comment by situchan** [comment]
@dominictb's [main solution](https://github.com/Expensify/App/issues/45230#issuecomment-2224330879) looks good to me.
🎀👀🎀 C+ reviewed

**Comment by trjExpensify** [comment]
Checklist time!

**Comment by techievivek** [comment]
Gentle bump @situchan

**Comment by situchan** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37767
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37767/files#r1714194625
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A

### Regression Test Proposal
1. Create an expense with violation (i.e. no category or no tag)
2. Approve the report
3. Go to transaction detail
4. Observe the LHN
5. Verify that report doesn't have an RBR red dot in the LHN and isn't pinned

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @situchan for the C+ review
- $250 to @dominictb for the fix

Paid!
