### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250] Expense - Inconsistency in expense preview when deleting tracked expense & submitted expense offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45247]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4700344
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to self DM.
4. Track an expense in self DM.
5. Delete the tracked expense in self DM.
6. Note that the expense preview is crossed out.
7. Go to DM with any chat.
8. Submit an expense to the user.
9. Delete the expense.

## Expected Result:
The expense preview will be crossed out when deleting expense offline. The behavior will be consistent with deleting tracked expense in self DM offline.

## Actual Result:
The expense preview is not crossed out when deleting expense offline. This is not consistent with deleting tracked expense in self DM offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/30649938-162a-42a3-9f29-c373aa961891

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a18b3786ddabfcdd</li>
        <li>Upwork Job ID: 1813279573925986534</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103144778</li>
<li>nyomanjyotisa | Contributor | 103164028</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by MitchExpensify** [comment]
Reassigning as I'm heading on leave 🙇

**Comment by dubielzyk-expensify** [comment]
I might be missing some context here so I'll loop in the other @Expensify/design peeps. 

Of the alternatives above I prefer both the price and text with strikethrough, but even if we're offline and delete it, can we not just remove the preview altogether? Assuming that it'll be deleted when you go online again and therefor the transition will be nice and neat?

**Comment by shawnborton** [comment]
I think this one goes back to our offline patterns... pending delete actions get a strikethrough, right @trjExpensify? 

Assuming that's correct, I tend to like the version where everything is crossed out and not just the amount, assuming that entire preview will be gone.

**Comment by trjExpensify** [comment]
>pending delete actions get a strikethrough, right @trjExpensify?

Yep, that's right. 50% opacity and strikethrough for pending delete. 👍

**Comment by trjExpensify** [comment]
>we will apply the change "everything is crossed out and not just the amount" to both REPORTPREVIEW, IOU or just REPORTPREVIEW?

It depends on the scenario when it comes to multi-expense reports. 

- If I have an expense report with three expenses on it, and I delete **one** expense offline. Then the IOU action will be strikethrough "pending delete", the REPORTPREVIEW will not. I'm not deleting the report, only one expense on the report. 

- If I have an expense report with three expenses on it, and I delete **all three** expenses offline. Then each IOU action will be strikethrough "pending delete", and the REPORTPREVIEW will be as well because deleting the last expense on a report deletes the entire report.

**Comment by trjExpensify** [comment]
Yep.

**Comment by puneetlath** [comment]
@ishpaul777 bump on the checklist please.

**Comment by puneetlath** [comment]
Payment summary: 
- C+ - $250 - @ishpaul777 - paid via Upwork
- C - 250 - @tienifr - to be paid via NewDot

Thanks everyone!

**Comment by garrettmknight** [comment]
$250 approved for @tienifr
