### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Report fields - Report fields still appear on the expense report when the feature is disabled

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace has set up some report fields.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit at least two expenses.
4. Go to workspace settings > More features.
5. Disable Report fields.
6. Go back to workspace chat.
7. Click on the expense preview.

## Expected Result:
The report fields will not appear on the expense report since the feature is disabled.

## Actual Result:
The report fields still appear on the expense report when the feature is disabled.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1e2b6663-bd73-4115-8f83-b80a5a562c7f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4b85941fc966bc0</li>
        <li>Upwork Job ID: 1811498015414386117</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103164265</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control.

**Comment by kabeer95** [comment]
Issue Report: Report Fields Still Appear on Expense Report When Feature is Disabled on Expensify

Summary:

When the report fields feature is disabled on Expensify, the fields still appear on the expense report, causing confusion and potential errors in expense reporting.

Steps to Reproduce:

Log in to Expensify and navigate to the workspace settings.
Disable the report fields feature.
Create a new expense report or edit an existing one.
Observe the report fields section on the expense report.
Expected Result:

The report fields section should be hidden or removed from the expense report when the feature is disabled.

Actual Result:

The report fields section still appears on the expense report, even when the feature is disabled.

Impact:

This issue can cause confusion and frustration for users, leading to potential errors in expense reporting and reimbursement.

Proposed Solution:

To resolve this issue, we recommend updating the Expensify code to properly hide or remove the report fields section when the feature is disabled. This can be achieved by:

Updating the conditional logic to check if the report fields feature is enabled before rendering the section.
Adding a CSS class to hide the section when the feature is disabled.
Code Example:

// Current implementation
if (featureEnabled) {
  // Render report fields section
}

// Proposed solution
if (featureEnabled) {
  // Render report fields section
} else {
  // Hide or remove the section
  $('.report-fields-section').hide();
}
Estimated Development Time:

We estimate [X] hours to implement this solution and update the Expensify code to properly handle the report fields feature.

Priority:

We consider this issue a medium priority, as it affects the usability and accuracy of expense reporting on Expensify.

Please let us know if you would like to discuss this issue further or proceed with implementation.

**Comment by NikkiWines** [comment]
Agreed @tienifr's solution is the most complete. Let's go with that one

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @tienifr (to be paid in NewDot)
- Reviewer: $250 @ishpaul777 (please accept the [offer in Upwork](https://www.upwork.com/nx/wm/offer/103164265))

**Comment by lschurr** [comment]
Waiting on @ishpaul777 - I think you've asked us to hold on payments. Is that correct?

**Comment by lschurr** [comment]
Any update @ishpaul777?

**Comment by lschurr** [comment]
All set :)

**Comment by garrettmknight** [comment]
$250 approved for @tienifr
