### ISSUE TITLE
Hybrid app - Explanation modal appears every time app opened

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45254]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/44903
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: on web create a new account in OD and run the snippet to enable the Try New Expensify button
1. Log in with the account that has the Try New Expensify button enabled into Expensify classic app
2. Tap the hamburger menu
3. Select the Try New Expensify option
4. Complete the onboarding
5. Kill the app and open again

## Expected Result:
The explanation modal opens only once

## Actual Result:
The explanation modal appears after completing onboarding and every time the app is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ef9c72f1-7380-4209-b84f-5291ff4d21ac

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
@OfstadC FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by rlinoz** [comment]
Yeah, this is most likely caused by https://github.com/Expensify/App/pull/44903

cc: @mateuuszzzzz @AndrewGable 

We don't seem to have changed anything related in Web-E, so I am gonna remove the blocker label.

**Comment by OfstadC** [comment]
Thanks @Julesssss and @rlinoz !
