### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Profile-In self DM, inconsistency in display of long email id in profile page of mweb

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45256]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open app in mweb and android
2. Login using long id [applausetester+venkatanadayakavitharkikakesari@applause.expensifail.com](mailto:applausetester+venkatanadayakavitharkikakesari@applause.expensifail.com)
3. Click on the profile avatar in the bottom navigation to open the settings
4. Notice how the email uses the entire available screen width
5. Go to the selfDM
6. Click the report header

## Expected Result:
The profile page which opens after clicking the selfDM report header should display the user's email using the entire available screen width before being truncated with `...`, just like the settings page

## Actual Result:
The profile page which opens after clicking the selfDM report header truncates the user's email before using the entire available screen width

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6538631_1720685382236!Screenshot_2024-07-11-13-38-29-772_com google android apps photos-edit](https://github.com/Expensify/App/assets/115492554/f278e415-468d-41e9-8630-03db24ab8798)

https://github.com/Expensify/App/assets/115492554/33f3f3ba-d20c-4d33-9bec-df04fb3026e3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144d6a170a845032e</li>
        <li>Upwork Job ID: 1811499937819098565</li>
        <li>Last Price Increase: 2024-07-11</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103098073</li>
<li>Krishna2323 | Contributor | 103098075</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by CortneyOfstad** [comment]
@paultsimura we have a few proposals for review when you have a moment — thank you!

**Comment by kabeer95** [comment]
Issue Report: Inconsistency in Display of Long Email IDs in Profile Page on MWeb

Summary:

On the MWeb profile page, there is an inconsistency in the display of long email IDs in the self-DM (direct message) section. This can cause confusion and make it difficult for users to read and interact with their email information.

Steps to Reproduce:

Log in to MWeb and navigate to the profile page.
Click on the self-DM section.
Observe the display of the email ID.
Expected Result:

The email ID should be displayed in a consistent and readable format, without truncation or wrapping.

Actual Result:

Long email IDs are truncated or wrapped, making it difficult to read and interact with the email information.

Impact:

This issue can cause frustration and confusion for users, making it difficult for them to manage their email information and communicate with others.

Proposed Solution:

To resolve this issue, we recommend updating the MWeb profile page to display long email IDs in a consistent and readable format. This could be achieved by:

Implementing a tooltip or hover-over effect to display the full email ID when the user hovers over the truncated email ID.
Wrapping the email ID to a new line, using a consistent line break character (e.g., <br>) to ensure readability.
Using an ellipsis (...) to indicate that the email ID has been truncated, with an option to expand the full email ID on click.
Code Example:

<div class="email-id">{{ userEmail }}</div>


<div class="email-id" title="{{ userEmail }}">{{ userEmail | truncate }}</div>


<div class="email-id">{{ userEmail | wrap }}</div>


<div class="email-id">{{ userEmail | truncate }} <span class="ellipsis">...</span> <span class="full-email" onclick="showFullEmail()">Show full email</span></div>
Estimated Development Time:

We estimate 40 hours to implement this solution and update the MWeb profile page to display long email IDs consistently.

Priority:

We consider this issue a low priority, as it affects the usability of the MWeb profile page, but does not impact the core functionality of the platform.

Please let us know if you would like to discuss this issue further or proceed with implementation.

**Comment by neil-marcellini** [comment]
It took me a really long time to understand this bug because the test steps, as well as the expected and actual results, are written very poorly. @izarutskaya please work with your team to make it more clear next time. I have updated those sections now.

**Comment by neil-marcellini** [comment]
> Thanks, the [updated proposal](https://github.com/Expensify/App/issues/45256#issuecomment-2222932906) by @Krishna2323 lgtm.

I agree, thanks

**Comment by CortneyOfstad** [comment]
## Payment Summary

@paultsimura — paid $250 via Upwork
@Krishna2323 — paid $250 via Upwork
