### ISSUE TITLE
Expensify Card - Toggle is auto-disabled after being enabled and disabled once

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#45274]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-1
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Log in with a new expensifail account
3. Create a workspace
4. Navigate to Workspace settings > More features
5. Enable Expensify Card
6. Navigate to the Expensify card menu
7. Navigate back to Workspace settings > More features
8. Disable the Expensify card
9. Navigate to the Expensify card menu
10. Navigate again back to More features
11. Enable the Expensify card
12. Navigate away from More Features
13. Navigate back to More Features and check the Expensify Card toggle

## Expected Result:
The Expensify Card toggle remains enabled

## Actual Result:
The Expensify Card toggle is auto-disabled

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/c8bc6afd-58c5-4835-9909-704893253462

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment]
@muttmuure FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by iwiznia** [comment]
@MariaHCD this _seems_ to come from your PR https://github.com/Expensify/Web-Expensify/pull/42651

Do you want to take a look at why this is happening or shall I revert the PR to resolve the blocker?

**Comment by Julesssss** [comment]
Demoting it as an app blocker as this is a new and WIP feature.

**Comment by MariaHCD** [comment]
Taking over. Like Jules said, it's a WIP feature so doesn't need to block any deploys

**Comment by MariaHCD** [comment]
This is likely related to: https://github.com/Expensify/Expensify/issues/412040

We can retest once we have the fix deployed: https://github.com/Expensify/Auth/pull/11580
