### ISSUE TITLE
Desktop - Unable to login Google/ Apple button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4708479
**Email or phone of affected tester (no customers):** rybkina@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch App
2. Tap on Google/ Apple button on sign in page
3. Tap on Allow on popup on web " Do you want to allow this website to open “New Expensify”?

## Expected Result:
Desktop App should be open as login user via Google/ Apple

## Actual Result:
Desktop App opens on sign in page but not login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/aae05f4f-0acb-4d9c-af00-db8ffbea0956

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Quite possibly related to our other redirect blockers. Discussing in Slack.

**Comment by luacmartins** [comment]
Fixed [here](https://github.com/Expensify/App/pull/45299)

**Comment by kavimuru** [comment]
Issue is fixed. 

https://github.com/user-attachments/assets/2608646c-0be2-4900-95c2-a4f727bbbc85

**Comment by Julesssss** [comment]
> Issue is not fixed.

Hey @kavimuru, we think this was fixed. Is the desktop version up to date?

**Comment by kavimuru** [comment]
@Julesssss Build is not updated to the latest.

**Comment by luacmartins** [comment]
@kavimuru Can we test on the latest build please?

**Comment by kavimuru** [comment]
Bug is fixed 

https://github.com/user-attachments/assets/e285e2ed-f2b9-4c8e-b466-5fc3e0f31dc4

**Comment by Julesssss** [comment]
Closing as no longer reproducible ❤️
