### ISSUE TITLE
[HOLD for payment 2024-08-01] [$125] Add note to clarify the workspace join link functionality

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45303]
### Problem

Coming from [here](https://expensify.slack.com/archives/C03U7DCU4/p1720611755908389), we have agreed that on the workspace share page, we do not provide enough details for the admin about what the link/QR code does.

The link will allow users to join the workspace upon visiting while being signed in. A message will appear in the admins room for each join request to confirm the addition (unless its a domain controlled account in which case we pre-approve the requests but I think we can omit that information).

![image](https://github.com/Expensify/App/assets/36083550/1b97dd2a-8f8d-449d-9fb5-57ed2a97e615)

### Solution

Lets add some message to the share page that will make this clear, maybe with some icon/ illustration too

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015304db5f2b46c0a1</li>
        <li>Upwork Job ID: 1811770909332799477</li>
        <li>Last Price Increase: 2024-07-12</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103094166</li>
<li>DylanDylann | Contributor | 103815612</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by shawnborton** [comment]
Double design assignment, pow! 

This should be a quick one once we have the correct copy though!

**Comment by shawnborton** [comment]
cc @Expensify/design - here is a quick mock to get us started:
![image](https://github.com/Expensify/App/assets/2319350/21b1accd-2f57-4e62-9c9a-7961b107a900)

Figma link is [here](https://www.figma.com/design/oFxo6zAu4HRJkpuzY18nlV/Workspace-Share?node-id=0-1&t=jI03HRXP9fPdzist-1)

**Comment by shmaxey** [comment]
That [copy ](https://github.com/Expensify/App/issues/45303#issuecomment-2223826815)lgtm!

**Comment by dubielzyk-expensify** [comment]
That looks good to me 👍

**Comment by shawnborton** [comment]
Nice! Let's move forward then ⏩

**Comment by dannymcclain** [comment]
Looks good to me too! Way more clear ❤️

**Comment by mountiny** [comment]
@dominictb are you able to work on this one? I have made the reward half priced as its a simple addition

**Comment by miljakljajic** [comment]
payment due tomorrow, not overdue

**Comment by miljakljajic** [comment]
@dominictb will we need a regression test?

**Comment by miljakljajic** [comment]
paid in upwork

**Comment by DylanDylann** [comment]
@miljakljajic I reviewed [this PR](https://github.com/Expensify/App/pull/45374). Should I get compensation for this issue?

**Comment by mountiny** [comment]
$125 to @DylanDylann too

**Comment by miljakljajic** [comment]
Thanks for flagging @mountiny ! 

@DylanDylann - accept the offer and we'll pay right away. Apologies for not catching this.

**Comment by DylanDylann** [comment]
@miljakljajic Done, thanks for helping 🙏

**Comment by miljakljajic** [comment]
Paid! :)
