### ISSUE TITLE
[HOLD for payment 2024-08-09] [Payment Card / Subscription] Add Tax Exempt request flow to NewDot

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#45317]
___

**Issue reported by:** @slafortune 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1720720930027619?thread_ts=1720535536.055659&cid=C036QM0SLJK

## Action Performed:

1. Open [new.expensify.com/settings/subscriptions](http://new.expensify.com/settings/subscriptions)
2. Click the 3 dot menu in the "Subscription details" section:

![CleanShot 2024-07-12 at 10 52 06](https://github.com/user-attachments/assets/a2892bda-d315-48b2-b6cd-d635dd0a83aa)

3. Click "Request tax exempt status" button
4. Land in Concierge DM & Receive "I have received your request to set your account as tax exempt. Please attach a PDF of either your 501(c) or ST-119 here. Once that has been received and accepted, I'll get back to you here." message from Concierge 
5. Provide 501(c) or ST-119 proof, send to Concierge
6. Concierge marks account as tax exempt in Supportal
7. We show a "tax exempt" badge in [new.expensify.com/settings/subscriptions](http://new.expensify.com/settings/subscriptions)  in the "Subscription details" section:

![image](https://github.com/user-attachments/assets/959e16ce-a1a7-4896-a3c1-adb04a534a68)

## Workaround:
OldDot tax exempt flow 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

See above

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by MitchExpensify** [comment]
The next steps here will be to flesh out the design for this flow in NewDot assuming we use the same backend flow

**Comment by MitchExpensify** [comment]
I assume this it the rough flow which is the same as OldDot:

1. Open new.expensify.com/settings/subscriptions
2. Click "Request tax exempt status" button
3. Land in Concierge DM & Receive "I have received your request to set your account as tax exempt. Please attach a PDF of either your 501(c) or ST-119 here. Once that has been received and accepted, I'll get back to you here." message
4. Provide 501(c) or ST-119 proof, send to Concierge 
5. Concierge marks account as tax exempt in Supportal 
6. We show a tax exempt badge in new.expensify.com/settings/subscriptions

**Comment by shawnborton** [comment]
Because this is not a mainline flow, I think we should place the "Request tax exempt status" button behind an overflow menu on the Subscription details card. It would look like this:
![CleanShot 2024-07-12 at 10 52 06](https://github.com/user-attachments/assets/a2892bda-d315-48b2-b6cd-d635dd0a83aa)

Thoughts @Expensify/design ?

Then we could do something simple like this when the subscription is indeed tax exempt:
![image](https://github.com/user-attachments/assets/f4480521-15a5-422d-b69e-d9536c4da6d8)

**Comment by dannymcclain** [comment]
In terms of UI, totally love what you have going on there.

Only question is if the `Subscription details` card is the right place for that overflow menu? (I genuinely don't know, so hoping for some knowledge bombs.)

I feel like I could also see that overflow menu going in the `Subscription` page header—but again, I don't know if that makes more or less sense lol.

**Comment by shawnborton** [comment]
Oh that's fair... I don't think I feel strongly there. I can also see it working well for the `Subscription settings` card header too? 

Let's see if @MitchExpensify or @dubielzyk-expensify or @trjExpensify have any strong feelings too!

**Comment by dubielzyk-expensify** [comment]
I also like the UI, but don't feel strongly about the overflow being on page or on the details

**Comment by MitchExpensify** [comment]
I like what you've put together and I've updated the OP to reflect that plan!

**Comment by marcaaron** [comment]
Gonna pick this one up tentatively and look into what needs to be done on the engineering side. We should get an external engineer to help with the UI changes.

**Comment by marcaaron** [comment]
- API request is called [`RequestTaxExemption`](https://github.com/Expensify/Web-Expensify/blob/0c14986c708566a42271fed5699322198f730a01/api.php#L3620C1-L3626C1)
- [Auth command](https://github.com/Expensify/Auth/blob/main/auth/command/SetAccountAsTaxExempt.cpp) to set as exempt `SetAccountAsTaxExempt` 
- Exempt status uses a `private_taxExempt` nameValuePair

Seems like at the absolute minimum we just need to return that private name value pair with `OpenApp`.

We could also queue an Onyx update when `SetAccountAsTaxExempt` is called successfully. But not much needs to be done here. I think we can get someone working on the front end changes in parallel to these small backend changes.

**Comment by trjExpensify** [comment]
Love it! @narefyev91 is back tomorrow, and might be able to help with the front-end part. If not, @pasyukevich or @JKobrynski too have solid experience with helping build out the subscription page.

**Comment by narefyev91** [comment]
Sure - can pick this up - will be back on Wednesday fyi

**Comment by marcaaron** [comment]
Sounds good, I expect above PRs should be deployed by then.

**Comment by trjExpensify** [comment]
Awesome, going to assign you @narefyev91 for tracking. 👍

**Comment by marcaaron** [comment]
Backend part should be done for this and the NVP should be showing up now. The `RequestTaxExemption` command takes no parameters besides the user's authToken. @narefyev91 let me know if you have any other questions though!

**Comment by narefyev91** [comment]
@marcaaron not sure how to test step - 4 and 5 - as i remember concierge is a real person... just now from 1-3 and setting 6(locally inside onyx working fine)

**Comment by trjExpensify** [comment]
Mitch is now on pat leave for a while. Given you can't edit any other subscription settings on native, let's do the same here for the tax exempt status.

**Comment by trjExpensify** [comment]
@slafortune support for Tax Exempt status is implemented now. :)

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR AUG 09, if no regressions

- Fix: @narefyev91 [callstack, no upwork payment]
- PR Review: @hoangzinh [$250] [Offer](https://www.upwork.com/nx/wm/offer/103370461)

**Comment by abekkala** [comment]
not overdue payment is tomorrow

**Comment by abekkala** [comment]
@hoangzinh payment sent and contract ended - thank you! 🎉
