### ISSUE TITLE
[HOLD for payment 2024-07-24] [Closed & Archived] Pass in ReportNameValuePairs to isArchived

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#45323]
Background:

We're changing how we detect if a report is [archived](https://github.com/Expensify/App/blob/2e7e212ea7ff50317e85a94d7676d2a419f8b0f2/src/libs/ReportUtils.ts#L1256-L1262). Before, we were using the report's `state` and `status` which are in the report onyx collection. Now, we want to use a report's `isArchived` property which is in the reportNameValuePairs onyx collection.

Request:

We need to pass in reportNameValuePairs wherever [isArchivedRoom](https://github.com/Expensify/App/blob/2e7e212ea7ff50317e85a94d7676d2a419f8b0f2/src/libs/ReportUtils.ts#L1256-L1262) is called. This has already been done for the ReportFooter which can be used as an [example](https://github.com/Expensify/App/pull/40661/files#diff-68b13bc8344820144538408415f307efee198ccc63977ba318c4234102ec3917). (Look at ReportScreen.tsx and ReportFooter.tsx changes).

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by srikarparsi** [comment]
We're on a pretty tight timeline so please only post a proposal if you're able to work on a PR today. This should be a relatively straightforward change but please ask if there's any questions.

**Comment by DylanDylann** [comment]
@srikarparsi It is so straightforward. I can work on the PR now

🎀👀🎀

**Comment by srikarparsi** [comment]
Awesome, that would be great, thanks @DylanDylann

**Comment by srikarparsi** [comment]
@Pujan92, sorry for the assignment, I can review this PR when @DylanDylann creates it. Do you have an ETA @DylanDylann?

**Comment by DylanDylann** [comment]
Give me 2 hours for both implementation and testing

**Comment by srikarparsi** [comment]
Cool, two things for testing.

1. The Onyx key is named `private_isArchived` but in App it's currently called `isArchived`. So to test, you will need to use `private_isArchived`. I created a [PR here](https://github.com/Expensify/App/pull/45320/files) to change the variable name but there's one [problem](https://github.com/Expensify/App/pull/45320#issuecomment-2225021036) so once that's figured out, we can switch all occurrences to either `isArchived` or `private_isArchived`.
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/296d4cb8-7aa4-43c1-856e-db6fe24fe9fe">

2. The backend isn't fully complete so there may be some cases where you don't get the `private_isArchived` onyx update inside the reportNameValuePairs collection. But, one way that will reliably work is creating a workspace and then deleting it. You should see the `private_isArchived` key for all the newly archived workspace chats.

**Comment by DylanDylann** [comment]
> The backend isn't fully complete so there may be some cases 

@srikarparsi Should we keep the report's state and status condition in [isArchivedRoom](https://github.com/Expensify/App/blob/2e7e212ea7ff50317e85a94d7676d2a419f8b0f2/src/libs/ReportUtils.ts#L1256-L1262) function. IMO, we can remove the report's state and status if BE fully complete, but now I think we still need to keep the report's state and status condition

**Comment by srikarparsi** [comment]
Yes, let's keep it there for now as a fallback.

**Comment by DylanDylann** [comment]
Please give me one more hour. There are many places that need to be updated

**Comment by DylanDylann** [comment]
@srikarparsi The PR is ready for review

**Comment by dylanexpensify** [comment]
Woot!

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor: @DylanDylann $250

Please request/apply!

**Comment by dylanexpensify** [comment]
Job post: https://www.upwork.com/jobs/~0158d0455594dee8e1

**Comment by DylanDylann** [comment]
Thanks @dylanexpensify I applied to the job post 👍

**Comment by dylanexpensify** [comment]
@suneox please apply to!

**Comment by dylanexpensify** [comment]
@puneetlath I'm heading OOO now until 5th of August! Waiting for @suneox to apply and @DylanDylann to accept! TY! I owe ya one!

**Comment by puneetlath** [comment]
@suneox can you complete the [checklist](https://github.com/Expensify/App/issues/45323#issuecomment-2232059581)? 

Offers are out to @suneox and @DylanDylann. Waiting for both to accept. Please ping me on this issue when you have.

**Comment by puneetlath** [comment]
Great thanks. @suneox has been paid. 

@DylanDylann please ping me here when you've accepted the contract and we can close this out.

**Comment by DylanDylann** [comment]
> @DylanDylann please ping me here when you've accepted the contract

@puneetlath I did, thanks 🙏

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
