### ISSUE TITLE
 Pasting text with a blank line underneath it shows grey text, unable to send message using `Enter` key

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45345]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720744680218859

## Action Performed:
Type a message with a word then a blank space under it
Copy the text and space then send message
Paste the text and space into the compose box
Expected Result: 
Actual Result: Text is grey and can't send
## Expected Result:
Text and space to show as black/normal text and able to send the messge
## Actual Result:
Text is grey and can't send using `Enter` key
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e25072b1-4eb9-4862-b357-7800b02cfb40

https://github.com/user-attachments/assets/01d3bdd9-231f-4adb-953b-5a33b1a7b620

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by mountiny** [comment]
I think its a specific flow with a workaround for the user, the live markdown library is tough to update, we cannot just CP aa library update and we need to deploy so at this state we should demote imho.

@Skalakid @BartoszGrajdek @tomekzaw for visibility

We could apply some patch though temporarily

**Comment by dangrous** [comment]
Yeah agree that I don't think this needs to be a blocker. Would be great if the live markdown experts have a fix! Seems pretty easy to add a test for too once it's updated.

**Comment by Skalakid** [comment]
@m-natarajan @dangrous @mallenexpensify I can't reproduce this issue, can you check if it still occurs? I think https://github.com/Expensify/App/pull/44958 might have fixed it

**Comment by brunovjk** [comment]
>  Screen.Recording.2024-07-15.at.19.41.31.mov

I also couldn't reproduce (v9.0.6-8), I have the same result as the video above.

**Comment by dangrous** [comment]
yes this seems fixed for me as well! I'm going to close - but @mallenexpensify if you're still getting it, let us know!
