### ISSUE TITLE
[Landing page] Update UseDot to have the qualifying questions like the new home page

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#45360]
As part of the August earnings, we're updating the design of our home page at www.expensify.com. In addition we're asking qualifying questions users are directed to NewDot if they answer they are an employee or manager under 10 employees, but then directed to Classic if they are a business over 10 ([GH](https://github.com/Expensify/Expensify/issues/389378)). 

In addition to that update, we would like to make UseDot consistent with the home page so we ask those questions too. For background, please [go here](https://expensify.slack.com/archives/C036QM0SLJK/p1720801933579369?thread_ts=1720723258.872159&cid=C036QM0SLJK). 

I do not think this is going to be CRITICAL to move new signups to NewDot but @shawnborton @trjExpensify wanted to create an issue so we can add this as polish once the homepage is launched. 

Here is the homepage redesign for reference. 
![image](https://github.com/user-attachments/assets/0b606625-e289-4a20-948c-da439c48813a)

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by dubielzyk-expensify** [comment]
Sorry if I'm a bit confused, but this task is only about polishing up the mock above to be a bit neater and more polished without messing with any elements?

**Comment by dubielzyk-expensify** [comment]
Cool 👍

**Comment by shawnborton** [comment]
PR for @neil-marcellini has been created here: https://github.com/Expensify/Use-Expensify/pull/180

**Comment by neil-marcellini** [comment]
I worked on this a bit earlier in the week and fixed a bunch of style and got validation for choosing an option working for the Get started button. I still need to pass the sign up qualifier choice to Web-E, implement that redirect logic, the login validation on UseDot, and make the google sign in with qualifier choices work.

**Comment by neil-marcellini** [comment]
I was able to jump back in on this today and I made some good progress. I'm passing the signupQualifier choice, redirecting to NewDot if needed, saving it in an NVP in Auth. I also added validation for the regular login form.

To do:

- [ ] Debug and fix setting the NVP
- [ ] Make validation work for the google sign in too
- [ ] Make the google sign in flow pass the sign up qualifier
- [ ] Make sure the modals work
- [ ] Write up and run manual tests

**Comment by shawnborton** [comment]
Sounds like some solid progress, let me know if I can be helpful with anything!

**Comment by neil-marcellini** [comment]
Today I made the validation work for the google sign in button, got part way through passing the sign up qualifier to the Oath flow, and started testing and tweaking the modals. I want to consolidate the forms a bit more so that the same html isn't written 3 times, so we're discussing how to use dynamic content from the CMS in Slack. I read up on Squarespace templates a bit to learn more.

I need to create a ring0 issue to allow the dev `redirect_uri` to be used for testing the Google Oauth flow.

**Comment by neil-marcellini** [comment]
Today I fixed up and consolidated the modals and the home page sign up form on UseDot. I also fixed a bunch of styles and added back some ad tracking code that was accidentally deleted. After that I fixed saving the signupQualifier into the onboarding NVP, and verified that it's properly redirecting to NewDot.

Todo:

- [ ] Have Shawn check the styling
- [ ] [Add expensify.com.dev as an allowed redirect_uri for google sign in](https://github.com/Expensify/Expensify/issues/420157#top)
- [ ] Test google sign up flow setting the signupQualifier
- [ ] Write all test steps and record videos

**Comment by neil-marcellini** [comment]
I didn't work on this, other than working with some of the infra guys to figure out how to test on dev. Thanks @justinpersaud!

Head's up, I'll be working 50% for the rest of this week and next 🌲

**Comment by neil-marcellini** [comment]
I was having trouble with the google sign up flow, so I tested on production and found that it doesn't work properly from UseDot. For a new sign up it sort of worked and redirected me to NewDot, but then the login failed there. For an existing account it redirects me to expensify.com but then I have to sign in again there.

I'm going to put the UseDot PR with the signup qualifier up for review now, and then I can start working on fixing log in with google.

**Comment by shawnborton** [comment]
Sounds good, let's have @dubielzyk-expensify and an engineer (pullerbear?) review the PR whenever it's ready to go.

**Comment by neil-marcellini** [comment]
All PRs are up for review now.
https://github.com/Expensify/Auth/pull/11953
https://github.com/Expensify/Web-Expensify/pull/43054
https://github.com/Expensify/Use-Expensify/pull/180

I'll create some new issues to fix various bugs I found on prod

**Comment by neil-marcellini** [comment]
All done, closing this as [explained here](https://expensify.slack.com/archives/C036QM0SLJK/p1725393531891579?thread_ts=1725283827.371169&cid=C036QM0SLJK)
