### ISSUE TITLE
Report containing only pending transactions displays a GBR next to the workspace chat

### ISSUE THREAD

**Issue by youssef-lr** [Expensify/App#45363]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Create a report with a pending transaction in a Collect workspace

## Expected Result:
No GBR shown next to the workspace chat of the approver as there is no action to take

## Actual Result:
GBR is shown. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1800" alt="Screenshot 2024-07-13 at 02 08 06" src="https://github.com/user-attachments/assets/3126c38f-9155-4aa3-a8ca-d172ce18706b">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment]
I'll have a PR for this ready soon.

**Comment by twisterdotcom** [comment]
Nice! PR is happening above.

**Comment by twisterdotcom** [comment]
@youssef-lr this was deployed to Auth right? We're done here aren't we?
