### ISSUE TITLE
Fix Android & iOS builds

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#45392]
_Dupe of [this](https://github.com/Expensify/Expensify/issues/412320) internal issue_

### Problem

App workflow builds are failing to build with a new error. We have made no changes to our workflows. [Discussion](https://expensify.slack.com/archives/C03TQ48KC/p1720718300793999).

## Why is this important?

We can't push any Android builds, can't make releases, and QA can't test any fixes. 

## Solution

???

**Comment by Julesssss** [comment]
Fixed with both of these PRs: 
- [Ruby issue](https://github.com/Expensify/App/pull/45332)
- [patch issue](https://github.com/Expensify/App/pull/45389)

**Comment by Julesssss** [comment]
Both PRs cherry-picked. Should be fully resolved as soon as the next App release takes place

**Comment by Kicu** [comment]
@Julesssss I think the same changes you added here need to be added to `testBuild.yml` as well. In this PR the changes go to `platformDeploy` only.

Here is an example of adhoc build that failed for android with the same error: https://github.com/Expensify/App/actions/runs/9943241672

**Comment by Julesssss** [comment]
@Kicu ah thanks. I must have accidentally removed the fix from the Test build workflow at some point 🤦 

Submitted a new PR [here](https://github.com/Expensify/App/pull/45459).

**Comment by Julesssss** [comment]
Test builds have been verified fixed [here](https://github.com/Expensify/App/actions/runs/9954562086/job/27502316647)
