### ISSUE TITLE
[Awaiting payment on 23/08/24] [$250] Pressing `Tab` in the magic code screen does not move to next magic code input 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45416]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721030930518949

## Action Performed:

1. Open staging.new.expensify.com
2. Enter the email address of any account
3. When the focus is on any of the inputs for the magic code except the last one press `Tab` key

## Expected Result:
The cursor moves to the next input for magic code
## Actual Result:
The cursor jumps to Didn't receive a magic code? if 30 sec elapses or `sign in ` button 
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/85086f25-0e28-42a9-8eb8-f73d68f6332f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf3849877e81009e</li>
        <li>Upwork Job ID: 1818598235444042146</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103423841</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by srikarparsi** [comment]
Looks good to me as well, thanks for the bump

**Comment by miljakljajic** [comment]
Is this one coming up for payment this week? I noticed the PR was deployed to prod, but seems like the automation has failed

**Comment by srikarparsi** [comment]
Yes, I believe so thank you @miljakljajic

**Comment by miljakljajic** [comment]
@daledah it doesn't look like you've applied to the job on upwork. Can you please either apply or share your upwork profile so we can get an offer sent to you?

**Comment by miljakljajic** [comment]
@ishpaul777 has been paid - we can close this out when we hear from @daledah - please share your profile or apply to the job.

**Comment by miljakljajic** [comment]
@daledah 's offer here: https://www.upwork.com/nx/wm/offer/103795834

**Comment by miljakljajic** [comment]
Paid!
