### ISSUE TITLE
Dynamic workflow mocks

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#45413]
### Problem

Our GitHub workflow mocks, such as `workflow_tests/mocks/platformDeployMocks.ts` are statically written and updated (manually, by developers). Generally most of our team doesn't really know how these tests work, and while they're helpful, having to manually update the mocks to match the workflow files is inefficient and comes with a substantial amount of overhead.

### Solution

Update our workflow tests such that the workflow mocks are dynamically generated from the workflow yaml file at the start of the test run, and optionally cleaned up afterwards. There is some existing code to generate boilerplate in `workflow_tests/utils/preGenerateTest.ts` that can serve as a starting point.

The goal of this issue would be that everything in `workflow_tests/mocks` would no longer be committed, but would be:

- Generated at runtime when you start each test
- (ideally) cached such that they're only re-generated if the workflow file being mocked changes

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by roryabraham** [comment]
There's not really a good GH project to associate this one with, and we won't need any design help.

**Comment by roryabraham** [comment]
Kind of looks like the Upwork automation didn't work for this one

**Comment by lschurr** [comment]
Looking at the PR, there aren't any contributors that need payment right @roryabraham?

**Comment by roryabraham** [comment]
We're still waiting on proposals for this one. I didn't have a proposal for this one

**Comment by roryabraham** [comment]
It's actually kind of tricky to do to, since sometimes we need to tweak the mocks. And the TS functions need to be generated from YAML. Not entirely sure how the type-checking will work for that...

I wonder if the original SWM author is available to iterate on and improve these tests. cc @AndrewGable

**Comment by AndrewGable** [comment]
Not sure I agree with the problem, it did take me a while to get up to speed on the mocks, but I think a dynamic mock generator will be much harder to debug than static mocks.

**Comment by roryabraham** [comment]
ok, going to close this one as not planned then. Probably pretty low ROI if you aren't sold on the problem
