### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Click back button, the category picker opens again.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721020681660959

## Action Performed:
Prerequisite: There is at least one workspace.
1. Go to self dm.
2. Create any track expense if there is no.
3. Choose "Categorize it" in actionable whisper.
4. Select any workspace. Then the category page opens.
5. Select any category option. Then the confirmation page opens.
6. Click "back" button.

## Expected Result:
The participant page opens.
## Actual Result:
 The category page opens.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a24a1e91-c95b-478f-8fb2-e8a7e6b27b10

https://github.com/user-attachments/assets/6a465196-18a8-4aec-bd71-8b592cf5b817

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2d95899400aa8ef</li>
        <li>Upwork Job ID: 1813006970158052404</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103143642</li>
<li>dominictb | Contributor | 103143643</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by Ahmed-Abdella** [comment]
@dukenv0307 Could you please explain why we should we back to the participant page.
is that because we have an option to change the category in the submit page so no need to use the back button to return to the category page.
Is there another reason?

**Comment by sakluger** [comment]
I think the bug report is correct. Clicking the back button should go to the previous step, not necessarily the preview screen.

On the summary screen (the screen before clicking back), you can click into the category and change it, but the "To workspace" selection is not clickable, and I can't change it any other way. Because of that, I'd consider the Workspace selection as the previous step, and clicking back should take me to that page.

**Comment by marcosdly** [comment]
> MacOS: Chrome / Safari

Does it have to be tested on metal, or is a virtual machine acceptable?

**Comment by rlinoz** [comment]
The `Please re-state the problem that we are trying to solve in this issue.` section is wrong though, right?

Also, quick question, won't the proposed solution cause any weird looking animations?

**Comment by rlinoz** [comment]
Looks good, thanks!

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @dukenv0307 $250, paid via Upwork
Contributor+: @dominictb $250, please request on Newdot

**Comment by sakluger** [comment]
Hey @dukenv0307, could you please complete the BZ checklist?

**Comment by sakluger** [comment]
@dukenv0307 thanks for catching that! I updated the payment summary and it should be correct now.

Thanks also for posting the checklist and regression steps. We're all done here!
