### ISSUE TITLE
[$250] [Mentions v2] Support mentions in room description

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#45425]
Problem: Adding mentions to a room description doesn't work correctly, currently it:
- Shows the underlying HTML tag instead of showing the mention when updating the room description
- Removes mentions when creating a room with mentions in the description

Solution: Support report and user mentions in room descriptions.

More context: 
https://expensify.slack.com/archives/C066HJM2CAZ/p1717069611736909?thread_ts=1717035618.513299&cid=C066HJM2CAZ
https://expensify.slack.com/archives/C066HJM2CAZ/p1720573506379179

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e50224dcaf5d7646</li>
        <li>Upwork Job ID: 1825787998136465845</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

**Comment by c3024** [comment]
@RachCHopkins , Automation failed here. PR referred for this issue was deployed to production on 2-Aug. Payment date should be 8-Aug. Can you please update the payment date and labels? Thanks!

**Comment by c3024** [comment]
Gentle bump on [this](https://github.com/Expensify/App/issues/45425#issuecomment-2273307823). @RachCHopkins

**Comment by rlinoz** [comment]
Moving to daily since the automation failed and we are a bit late here

**Comment by c3024** [comment]
@RachCHopkins Can you please check this issue as well? This is due for payment since 9-Aug.

**Comment by RachCHopkins** [comment]
Sorry @c3024 I've had a couple of crazy weeks - just catching up on everything finally! Offer should be ready for you.

**Comment by c3024** [comment]
Accepted the offer! Thank you!

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor+: @c3024  paid $250via Upwork
Upwork job [here](https://www.upwork.com/jobs/~01e50224dcaf5d7646)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
