### ISSUE TITLE
Categories & Tags - Not here page opens from GL code row

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45429]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43149
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Collect workspace settings > Categories
3. Click on any category
4. Click GL code

## Expected Result:
GL code editor will open

## Actual Result:
Not here page opens.
The same issue also happens with tags

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4fa0a289-cb48-4a30-9efc-afb92d4029d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by rushatgabhane** [comment]
@lanitochka17 is that a collect workspace?

**Comment by marcaaron** [comment]
@rushatgabhane any ideas on this one?

**Comment by marcaaron** [comment]
My first guess would be it's related to https://github.com/Expensify/App/pull/43149 gonna assign @Gonals since they are leading this up and the regressions seem like they just started.

**Comment by rushatgabhane** [comment]
@marcaaron yes this is happening because the user is allowed to visit the workspace only if it is a collect workspace

**Comment by rushatgabhane** [comment]
Not a blocker in my opinion. It will be replaced by Upgrade flow by @allroundexperts

**Comment by Gonals** [comment]
Yep, not. blocker and not a bug. This is currently expected in non-control
