### ISSUE TITLE
[HOLD for payment 2024-07-26] [Closed & Archived] Extra spacing between last message and archived banner

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#45422]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Follow up issue from [here](https://github.com/Expensify/App/pull/45330). More info in this [comment](https://github.com/Expensify/App/pull/45330#issuecomment-2228930851).

You can reproduce by replacing [this](https://github.com/Expensify/App/blob/fef5dfc746367fb59ebfe9c371d09d25b253f618/src/libs/ReportUtils.ts#L1293) with return false so that the isArchivedRoom check doesn't rely on the fallback (which will be removed in a future PR).

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Create a workspace
2. Send a message in a workspace chat (admins, announce...)
3. Delete the workspace
4. Navigate back to the workspace chat

## Expected Result:
Describe what you think should've happened

There should be the right spacing between the last message and the archived banner in the footer
<img width="1135" alt="Say hello!" src="https://github.com/user-attachments/assets/dc832c5d-07f1-4e5b-9d9b-ab5b58b136a2">

## Actual Result:
Describe what actually happened

There is too much spacing between the last message and the archived banner in the footer
<img width="1135" alt="Say hello!" src="https://github.com/user-attachments/assets/13c8fd4a-2c9c-4dca-b6d0-970e1babbebe">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by srikarparsi** [comment]
@DylanDylann you can reproduce by adding a return false [here](https://github.com/Expensify/App/blob/fef5dfc746367fb59ebfe9c371d09d25b253f618/src/libs/ReportUtils.ts#L1292) so that the isArchivedRoom check doesn't rely on the fallback (which will be removed in a future PR).

**Comment by trjExpensify** [comment]
Is @DylanDylann implementing this as a follow-up to his PR?

**Comment by srikarparsi** [comment]
Yes, that's the goal. It was a bug I found from the [PR](https://github.com/Expensify/App/pull/45330#issuecomment-2228930851) but thought it would be better to handle as a follow up so that we could merge without conflicts.

**Comment by trjExpensify** [comment]
Great! @DylanDylann can you raise the PR please?

**Comment by DylanDylann** [comment]
Yeah, The PR will be ready soon

**Comment by trjExpensify** [comment]
Did we get a PR up for this?

**Comment by DylanDylann** [comment]
I am working on it

**Comment by DylanDylann** [comment]
@srikarparsi After investigating, It seems this bug isn't regression from [my PR](https://github.com/Expensify/App/pull/45330#issuecomment-2228930851)

The RCA: In https://github.com/Expensify/App/pull/40661, we add `reportNameValuePairs` argument to canUserPerformWriteAction function but we don't add `reportNameValuePairs` param when using canUserPerformWriteAction function in some places

My solution: Removing `reportNameValuePairs` argument in canUserPerformWriteAction function. Getting reportNameValuePairs in canUserPerformWriteAction function directly

**Comment by DylanDylann** [comment]
@srikarparsi The PR is up https://github.com/Expensify/App/pull/45588

**Comment by srikarparsi** [comment]
The payment for this will be taken care of in this [issue](https://github.com/Expensify/App/issues/45323) since it was brought up in this [comment](https://github.com/Expensify/App/pull/45330#issuecomment-2228930851). Does that sound right @DylanDylann?

**Comment by DylanDylann** [comment]
Yes. Let's close this one
