### ISSUE TITLE
[$250] Investigate Google Maps API improvements for NewDot distance requests

### ISSUE THREAD

**Issue by rafecolton** [Expensify/App#45432]
Our Google rep informed us of some recent improvements to Google's API, so this issue is to:
1. Investigate if we could benefit from any performance improvements or cost savings
2. Implement any of those changes that can be made on the front-end
3. Work with me or another Expensify engineer to make any changes that need to be made on the back-end, such as updating API key scopes.

Here are the details about the changes that may or may not be relevant:

> - You can update your API Keys related to Distance and Directions to [Routes API](https://developers.google.com/maps/documentation/routes/migrate-routes-why). The Routes API provided improved performance for calculating directions, distance, and travel time. Routing enhancements also include Toll Calculations (perfect tool for helping reimburse drives who travel through tolls), Stopover Waypoints for safety, and even 2-wheel vehicle routes.
> - The Places API has also been upgraded and some of those changes can have an impact, you can find about the New Places APIs [here](https://developers.google.com/maps/documentation/places/web-service/op-overview).
> - All you would need to do is update the API keys that use the Places, Distance, and Directions APIs. The engineers can now fieldmask returns with the new Places API, that is a change vs getting everything returned today with the old Places.
> - Google has combined the pricing for Autocomplete and Address Validation, this will reduce the cost of running both APIs in tandem.  [Address Validation](https://developers.google.com/maps/documentation/address-validation/demo) is also available!

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168dceb5baaaa8452</li>
        <li>Upwork Job ID: 1815446319044970434</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

**Comment by rafecolton** [comment]
Updating this comment shortly with a breakdown of how much we use each of the Maps APIs

**Comment by rafecolton** [comment]
@rojiphil what is needed to move this forward? @mallenexpensify would you mind taking a look as well in case I missed something?

**Comment by mallenexpensify** [comment]
@rojiphil can you review the details in the OP and provide feedback and recommendations? We might want to create individual issues for this (I have no idea, it's an option though)

**Comment by mallenexpensify** [comment]
@rojiphil 👀 on the above plz

**Comment by rojiphil** [comment]
> can you review the details in the OP and provide feedback and recommendations? We might want to create individual issues for this (I have no idea, it's an option though)

Sorry for the delayed response here. 
We use `react-native-google-places-autocomplete` library to access google Maps APIs. 
I will have to take a closer look at this while considering the recent improvements in Google Maps API. 
Will do so in the next few days and revert.

**Comment by rafecolton** [comment]
Thank you! Once we get a sense of scope for this change, we can discuss if $250 is still an appropriate price or if it should be increased.

**Comment by lschurr** [comment]
Any update on this one @rojiphil?

**Comment by rojiphil** [comment]
Looking into this today

**Comment by rojiphil** [comment]
From the FE side, we use `Places API > Autocomplete` via `react-native-google-places-autocomplete` library. And I am still investigating this. But I expect to share my findings tomorrow.
 
Meanwhile, I am not sure who is using the other APIs as mentioned in the breakup [here](https://github.com/Expensify/App/issues/45432#issuecomment-2229525486)
Is the BE internally making use of these APIs? If so, what FE action would trigger these API usages?

**Comment by rafecolton** [comment]
Interesting, yeah I see that in the FE using the `Proxy_GooglePlaces` api command in `src/components/AddressSearch/index.tsx`, and it looks like that react native lib might use the place details too.

Digging a bit more into the web code, it looks like we are using these features on the BE or old app front-end:
* find a place - smartscan
* geocoding - creating GPS-based expenses, a few other things
* directions, static maps, roads - generating printable Google map receipts
*dynamic maps - rendering maps in js in the old app

So it looks like the places api is the only one you could possibly improve on the FE in NewDot

**Comment by rojiphil** [comment]
> Digging a bit more into the web code, it looks like we are using these features on the BE or old app front-end:
> 
> * find a place - smartscan
> * geocoding - creating GPS-based expenses, a few other things
> * directions, static maps, roads - generating printable Google map receipts
>   *dynamic maps - rendering maps in js in the old app

Ah! Thanks. That clarifies on where the APIs are used. But that leads me to the following query.

Currently, we use [Mapbox](https://www.npmjs.com/package/@rnmapbox/maps) in NewDot for showing the maps and use Google’s `Places API > Autocomplete` for autocomplete functionality. 
This makes me curious to know as to why we have to depend on two different service providers for the maps functionality.  This can lead into additional requirements (i.e. display google logo as we are not using google maps) as mentioned in the following screenshot referenced from [here](https://developers.google.com/maps/documentation/places/web-service/autocomplete). 

Wouldn’t it be neat to use a single service provider for all maps related requirements?  
For example, if we are going with Mapbox, we can replace Google’s `Places API > Autocomplete` with  [Address Autofill](https://docs.mapbox.com/mapbox-search-js/api/web/autofill/) or [Search Box](https://docs.mapbox.com/mapbox-search-js/api/web/search/)
And if we are going with Google Maps API, we can replace [Mapbox](https://www.npmjs.com/package/@rnmapbox/maps) with Google Maps using [react-native-maps](https://www.npmjs.com/package/react-native-maps). For autocomplete though, we need to upgrade from `Places API` to `Places API (New)`

What are your thoughts on the above?

![Screenshot 2024-07-31 at 10 05 31 PM](https://github.com/user-attachments/assets/4d9acacf-b958-4589-9471-581038473cfa)

**Comment by rafecolton** [comment]
I'm not sure why we chose Mapbox instead of Google - maybe @neil-marcellini knows? 

I don't think it's super important to consolidate everything right now. It is a much bigger change than we're investigating here and I'm not aware of any specific problem it solves.

**Comment by rojiphil** [comment]
Yeah, I do agree that it’s a much bigger change but it may be worth it as popularity of google maps is much more than mapbox ([react-native-maps](https://www.npmjs.com/package/react-native-maps) has 10x times weekly downloads than  [map box](https://www.npmjs.com/package/@rnmapbox/maps)). Anyway, if we want to continue to use Mapbox then we need to display `Google` logo as mentioned [here](https://github.com/Expensify/App/issues/45432#issuecomment-2261035709).

And specific to migration from `Places API` to `Places API (New)`, we can make the following changes:
1. Configure Google Cloud to enable `Places API (New)` to the API key (preferably a new one)  as mentioned [here](https://developers.google.com/maps/documentation/places/web-service/migrate-overview#enable-new)
2. Use HTTP POST instead of HTTP GET for `Autocomplete (New)` API uses  as mentioned [here](https://developers.google.com/maps/documentation/places/web-service/place-autocomplete#place_autocomplete_requests). 
3. Handle the format changes in response structure for `Autocomplete (New)` API as mentioned [here](https://developers.google.com/maps/documentation/places/web-service/place-autocomplete#:~:text=5000%20meter%20radius%3A-,%7B,-%22suggestions%22%3A)
4. Use the required parameter `fieldmask` for `Place Details (New)` API as mentioned [here](https://developers.google.com/maps/documentation/places/web-service/place-details#fieldmask). This way we can control the billing by including what we need in `field mask`
5. Use `session tokens` to group `autocomplete` and `place details` which will help in reduced billing. This is referenced [here](https://developers.google.com/maps/documentation/places/web-service/place-session-tokens).
6. Handle the format changes related to `Place` object for in response structure of  `Place Details (New)` API as referenced [here](https://developers.google.com/maps/documentation/places/web-service/migrate-response)

Also note that the `react-native-google-places-autocomplete`library include support for `nearbysearch` and `geocoding` but I am not sure if this needs to be in scope as this is not yet used by NewDot.

**Comment by rafecolton** [comment]
Great, thank you for the continued investigation! Based on your findings, and keeping the scope limited to the Places migration as used in NewDot, can you please advise:
1. What do you think is a fair price for this task?
2. Is this something you would like to implement? If not, can you please help a volunteer to put up a proposal?

Thanks!

**Comment by rojiphil** [comment]
> Great, thank you for the continued investigation! Based on your findings, and keeping the scope limited to the Places migration as used in NewDot, can you please advise:
> 
> 1. What do you think is a fair price for this task?
> 2. Is this something you would like to implement?

Thanks. And yeah, I can implement this. We would need 2 PRs - one for the changes in `react-native-google-places-autocomplete` library and another for the FE changes. And we can aim to wind this up in two weeks. 

Just that I would need your support in a) ensuring that new Places API are enabled in API key and b) ensuring that the BE proxies the new places api and returns back the results to FE.

Regarding the fair price for this task, I think $3000 seems reasonable for the investigation, design, and implementation. 
What do you think?

**Comment by rafecolton** [comment]
We discussed internally and agreed on $1000 for the implementation. To avoid confusion, I'm going to create a separate issue for that so you get paid the $250 here for your investigation. On the implementation, are you interested in taking either the C or C+ role? Happy to give you first dibs due to your work in this issue.

**Comment by rojiphil** [comment]
> On the implementation, are you interested in taking either the C or C+ role? Happy to give you first dibs due to your work in this issue.

@rafecolton I would be happy to take up the C+ role here. Thanks.

**Comment by rafecolton** [comment]
Ok sounds good! I'll create the new issue and get you assigned ❤️

@lschurr can you please ensure @rojiphil gets paid $250 on this issue for the investigative work?

**Comment by lschurr** [comment]
@rojiphil - Offer sent [here](https://www.upwork.com/nx/wm/offer/103452955).

**Comment by rojiphil** [comment]
> @rojiphil - Offer sent [here](https://www.upwork.com/nx/wm/offer/103452955).

@lschurr Accepted the offer. Thanks.

**Comment by lschurr** [comment]
All paid! I think we can close this one for the other issue, correct?

**Comment by rafecolton** [comment]
> All paid! I think we can close this one for the other issue, correct?

Correct, thanks!

**Comment by rafecolton** [comment]
I don't think it really matters, it is not something we are looking to change at this time.

**Comment by trjExpensify** [comment]
>I'm not sure why we chose Mapbox instead of Google - maybe @neil-marcellini knows?

This was a deliberate decision during the design phase of introducing distance requests. We evaluated them both and landed on Mapbox. IIRC, it gave us much more flexibility with the ability to accommodate custom branding and what not.
