### ISSUE TITLE
[HOLD for payment 2024-07-24]  iOS - Search - Empty modal is shown when tapping on "0 selected" dropdown

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45445]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7- 4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has at least one expense.

1. Launch New Expensify app.
2. Go to Search.
3. Long tap on any expense.
4. Tap Select.
5. Unselect the selected expense.
6. Tap "0 selected".

## Expected Result:
There should not be any dropdown when no expense is selected.

## Actual Result:
There is a "0 selected" dropdown when no expense is selected, which opens an empty modal when tapped.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/863c209c-a67b-46d7-9ed6-7910fcb4b5e9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Search - Empty modal is shown when tapping on "0 selected" dropdown

### What is the root cause of that problem?
We don't set `isMobileSelectionModeActive` as false when selected Items is empty on `SearchListWithHeader.tsx` page

### What changes do you think we should make in order to solve the problem?
We will set isMobileSelectionModeActive as false on this page, if the selected items are cleared with a useEffect:

```jsx
useEffect(() => {
    if (isEmptyObject(selectedItems)){
        setIsMobileSelectionModeActive?.(false);
    } 
}, [selectedItems])
```

**Comment by thienlnam** [comment]
Will take this over since Vivek is offline

**Comment by thienlnam** [comment]
This was added from a recent PR since it's not reproducible on production right? Was someone able to find the linked PR?

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone!

@dominictb's [main proposal](https://github.com/Expensify/App/issues/45445#issuecomment-2230084141) looks good to me. The disabling of the button is a more common pattern that we usually make use of in our app.

@dominictb Can you create the PR real quick since this is a deploy blocker?

🎀 👀 🎀 C+ reviewed

**Comment by thienlnam** [comment]
We're going with @dominictb's proposal, and will spin up the PR since you're offline - we'll still compensate you

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JULY 24

- Fix: @dominictb [$250, if no regressions] [offer](https://www.upwork.com/nx/wm/offer/103156071)
- PR Review: @allroundexperts [$250, if no regressions] payment via NewDot
Please complete checklist

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR JULY 24
- Fix: @dominictb [$250, if no regressions] [offer](https://www.upwork.com/nx/wm/offer/103156071)
- PR Review: @allroundexperts [$250, if no regressions] payment via NewDot
**Please complete checklist**

**Comment by abekkala** [comment]
@dominictb payment sent and contract ended - thank you! 🎉

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/44820
2. https://github.com/Expensify/App/pull/44820/files#r1694343462
3. N/A
4. A regression test would be a nice addition.

### Regression Test

Pre-req: Make sure that the user has at least one expense.

1. Open the app, go to Search
2. Long tap on any expense and press Select
3. Unselect the selected expense
4. Tap "0 selected"

Verify that there should not be any dropdown when no expense is selected

Do we 👍 or 👎 ?

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts

**Comment by JmillsExpensify** [comment]
Re-opening for the regression test.

**Comment by abekkala** [comment]
QA GH for regression test created.
