### ISSUE TITLE
[HOLD for payment 2024-07-24]  iOS - Search - "No options available for the selected group of expenses." is truncated

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #[44820](https://github.com/Expensify/App/pull/44820)
**Version Number:** 9.0.7-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team 
**Slack conversation:**

## Action Performed:
Precondition:
- User has at least one paid expense.

1. Launch New Expensify app.
2. Go to Search.
3. Tap on the dropdown.
4. Select Finished.
5. Long tap on any expense.
6. Tap Select.
7. Tap on the "1 selected" dropdown.

## Expected Result:
The content "No options available for the selected group of expenses." will be displayed in two lines (no truncation).

## Actual Result:
The content "No options available for the selected group of expenses." is truncated.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/963369bf-58c8-4be4-9e33-2f798d859448

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by shawnborton** [comment]
Hmm I feel like this is using an incorrect style anyways, why not use a style that matches what we are doing on desktop? 
![CleanShot 2024-07-16 at 08 45 48@2x](https://github.com/user-attachments/assets/575f4f3f-1214-45c2-89e6-9b5b0446e5be)

It should basically look identical to that, just in bottom-docked mobile format. cc @Expensify/design for any thoughts too!

**Comment by shawnborton** [comment]
cc @filip-solecki in case you have any context there as to why we didn't reuse the same styles from desktop.

**Comment by filip-solecki** [comment]
TBH I am not sure if we need this Modal anymore. I am working on Download functionality and AFAIK user can download every single transaction, so there will always be at least one option

**Comment by MonilBhavsar** [comment]
It seems to be coming from https://github.com/Expensify/App/pull/44820. Would you be able to make a quick follow up fix?

**Comment by filip-solecki** [comment]
Yes, I will prepare it right now

**Comment by trjExpensify** [comment]
>TBH I am not sure if we need this Modal anymore. I am working on Download functionality and AFAIK user can download every single transaction, so there will always be at least one option, but yes, looks like quick styling fix

I agree with this btw.. with the option to `Download` being added to the menu imminently, it makes this kinda' obsolete.

**Comment by DylanDylann** [comment]
This issue come from https://github.com/Expensify/App/pull/44820. @rushatgabhane Could you take over this one?

**Comment by MonilBhavsar** [comment]
I just did a quick test and looks good!

**Comment by thienlnam** [comment]
Doesn't look like this was CPed - will request one

**Comment by MonilBhavsar** [comment]
This issue is fixed. No further action required. Thanks all!
