### ISSUE TITLE
Categories - GL code comes back after clearing the field and reopening the category editor

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45442]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #43155
**Version Number:** 9.0.7-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace is under Control plan.

1. Go to staging.new.expensify.com
2. Go to Control workspace settings > Categories.
3. Click on any category.
4. Click GL code.
5. Enter a GL code and save.
6. Click GL code again.
7. Clear the GL code and save.
8. Close the RHP.
9. Click on the same category again.

## Expected Result:
The GL code field will remain cleared.

## Actual Result:
The GL code field is populated with old value and is not cleared.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cc367066-e376-49fc-89f8-b06e92ab7e34

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
cc @rushatgabhane @Gonals

**Comment by Gonals** [comment]
Not a blocker, as it doesn't break existing functionality. This is getting fixed [here](https://github.com/Expensify/Expensify/issues/412653)

**Comment by dylanexpensify** [comment]
Perfecto!

**Comment by dylanexpensify** [comment]
fix ongoing

**Comment by dylanexpensify** [comment]
@Gonals is this still occurring?

**Comment by Gonals** [comment]
Nope!
