### ISSUE TITLE
Android - Task - Error while creating task is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45477]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.07
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4727493
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter [] This is your personal space. Use it for notes, tasks, drafts, and reminders
You can also use the + button to track an expense, or assign a task!
4. Send the message

## Expected Result:
Task must be created without any error

## Actual Result:
Error while creating task is shown

## Workaround:
Unnown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e08f553e-bdfb-48ba-a694-7d33a677e088

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by stephanieelliott** [comment]
Given that this is specific to the composer method of creating a task on Android and the #vip-vsb is on pause, I am going to mark this as `Not a priority` and close. We may reopen it later once that project is off pause
