### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Distance - Amount does not update after selecting a different workspace with different rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45479]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4723512
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace A has distance rate A
- Workspace B has distance rate B
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Distance
3. Enter waypoints
4. Select Workspace A
5. On confirmation page, click Rate and select Distance rate A
6. Note that the amount is amount A
7. Click back button on confirmation page
8. Select Workspace B

## Expected Result:
After selecting Workspace B, the distance amount in the confirmation page will adjust accordingly to Amount B based on Distance rate B

## Actual Result:
After selecting Workspace B, the distance amount in the confirmation page is still Amount A when the selected rate is Distance rate B

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9fc4093a-d135-411c-a56b-9aa4fbdaed87

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e501d4313825dcb</li>
        <li>Upwork Job ID: 1814314096244747204</li>
        <li>Last Price Increase: 2024-07-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment]
Was able to recreate, so going to get eyes on this!

**Comment by CortneyOfstad** [comment]
@Ollyws we have a proposal [here](https://github.com/Expensify/App/issues/45479#issuecomment-2230941357) when you have a chance — thank you!

**Comment by CortneyOfstad** [comment]
@Ollyws can you please update the checklist when you have a moment so there is no delay in payment? Thanks!

@jliexpensify I am heading OoO so reassign so there is not a delay in payment. Thank you!

**Comment by jliexpensify** [comment]
Payment Summary

- C: @tienifr $250 (ND Payment)
- C+: @Ollyws $250 (ND Payment)

Waiting on checklist

**Comment by jliexpensify** [comment]
Bump @Ollyws for checklist

**Comment by jliexpensify** [comment]
[Here's the payment summary for J.Mills!](https://github.com/Expensify/App/issues/45479#issuecomment-2261721412)

**Comment by JmillsExpensify** [comment]
$250 approved for @Ollyws
