### ISSUE TITLE
[HOLD for payment 2024-07-26] [HelpDot] Restructure Integrations Category on Exfy Classic

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#45483]
### Overview
We're migrating export/sync integration errors to HelpDot, so we need to make some changes to the Integrations category so that the content is organized in a way that makes sense for the reader. 

Additional context -- [HERE](https://expensify.slack.com/archives/C02QSAC6BJ8/p1721136455995669).

### Category name change
- [ ] Update category name from `Integrations` to `Connections`
- [ ] Create redirects for all articles after category name change / after reorganizing content

### Reorganize Content
- [ ] Get rid of the following subcategories
     - HR Integrations
     - Accounting Integrations
     - Travel Integrations
     - Other Integrations
- [ ] All integration names are their own article / not nested within a subcategory / be in alphabetic order
- [ ] All accounting integrations should have a nested subcategory
- [ ] Each of the above will have the following articles:
     - Accelo
          - Connect to Accelo
          - Configure Accelo
          - Accelo Troubleshooting
     - Certinia
          - Connect to Certinia
          - Configure Certinia
          - Certinia Troubleshooting
     - NetSuite
          - Connect to NetSuite
          - Configure NetSuite
          - NetSuite Troubleshooting
     - QuickBooks Online
          - Connect to QuickBooks Online
          - Configure QuickBooks Online
          - QuickBooks Online Troubleshooting
     - QuickBooks Desktop
          - Connect to QuickBooks Desktop
          - Configure QuickBooks Desktop
          - QuickBooks Desktop Troubleshooting
     - Sage Intacct
          - Connect to Sage Intacct
          - Configure Sage Intacct
          - Sage Intacct Troubleshooting
     - Xero
          - Connect to Xero
          - Configure Xero
          - Xero Troubleshooting
- [ ] Move around the existing accounting integration content to:
     - Connect to X: Move existing accounting integration article to this file
     - Configure X: Add `Coming Soon` placeholder
     - X Troubleshooting: Add `Coming Soon` placeholder

**Comment by bfitzexpensify** [comment]
@rushatgabhane closing this one - I think you're tracking payment for ExpensifyHelp work separately rather than PR by PR, right?

**Comment by rushatgabhane** [comment]
@bfitzexpensify no actually. this one took time so i want to request payment here

**Comment by bfitzexpensify** [comment]
Cool. OK, confirming payment summary:

@rushatgabhane to be paid $250 via manual request

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
