### ISSUE TITLE
Distance - Distance row shows "Pending" briefly when holding and unholding distance expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45488]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two distance expenses
4. Go to transaction thread of any of the submitted expense
5. Click on the report header
6. Click Hold
7. Enter a reason and save it

## Expected Result:
Distance row will not show "Pending" when holding the distance expense

## Actual Result:
Distance row shows "Pending" briefly when holding and unholding the distance expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/38cf6986-72e0-4365-bc11-c8829f6c7816

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mallenexpensify** [comment]
Closing, posted the below in #expensify-open-source

> Closing the below issues, it appears to be expected behaviour, as we need to calculate the distance, which is why we briefly show Pending
> [Distance - Distance row shows "Pending" briefly when holding and unholding distance expense](https://github.com/Expensify/App/issues/45488#top)
> Comment/reopen if anyone disagrees.
