### ISSUE TITLE
[$250] mWeb - Room - Whisper is not shown for mention added while edit comment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4724888
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a room report
3. Enter [jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
#567 (email id and random room mention)
4. Send the message
5. Note whisper message is shown
6. Long press the comment and select edit comment
7. Enter [jaihanumanblog+6788@gmail.com](mailto:jaihanumanblog+6788@gmail.com)
#56778 (email id and random room mention)
8. Send the message

## Expected Result:
Whisper must be shown for mention added while edit comment

## Actual Result:
Whisper is not shown for mention added while edit comment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f7964cbb-e3c8-4692-9823-66d87b2f4e5b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01490add6334f2b67a</li>
        <li>Upwork Job ID: 1813353966729699916</li>
        <li>Last Price Increase: 2024-07-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by JmillsExpensify** [comment]
Yes, that's correct. Opening up to the community.

**Comment by Tony-MK** [comment]
@JmillsExpensify and @suneox, I believe this issue should handled in the back end because the `updateComment` response does include the `"ACTIONABLEREPORTMENTIONWHISPER"` action like the `AddComment` response.

Could we check this in the back end?

Thanks

**Comment by marcochavezf** [comment]
No update, I will move to weekly since it's vip-vsb and low

**Comment by marcochavezf** [comment]
No update, addressing other high priority items this week

**Comment by marcochavezf** [comment]
I will check it out today or tomorrow, I will move it to daily meanwhile

**Comment by marcochavezf** [comment]
Sorry, no update. I've been caught up with other priorities.

**Comment by marcochavezf** [comment]
Moving it back to weekly

**Comment by marcochavezf** [comment]
No update, addressing other higher priority issues

**Comment by marcochavezf** [comment]
Not a priority, unassigning myself for now

**Comment by JmillsExpensify** [comment]
Just going to close if this isn't a priority.
