### ISSUE TITLE
[$250] mWeb - Tag - While using multi level tag, members must tag all expenses unable to toggle off

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45497]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
In Old dot:
1. Enable use multi level of tag
2. Import dependent tags

In New Dot
1. Go to https://staging.new.expensify.com/
2. Tap profile icon -- workspaces - workspace
3. Enable tags
4. Tap tags
5. Tap settings
6. Disable members must tag all expenses
7. Tap app back button
8. Again tap settings

## Expected Result:
While using multi level tag, members must tag all expenses must be able to toggle off

## Actual Result:
While using multi level tag, members must tag all expenses unable to toggle off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8f4b0e9e-15db-41f4-9b5e-ac5dea270222

https://github.com/user-attachments/assets/9d510596-f6a4-418c-95df-641d177130f5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f929100a0a4a002</li>
        <li>Upwork Job ID: 1816212172498044428</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment]
I will be OOO tomorrow and next week, so I am reassigning this until I return on July 29. Thanks, @zanyrenney!

Status:

- The bug needs to be validated.
- Contributor assignment.

**Comment by zanyrenney** [comment]
adding external,

**Comment by zanyrenney** [comment]
should be part of collect.

**Comment by trjExpensify** [comment]
Manual management of multi-tags isn't officially supported on simplified collect. Can we verify this is a bug with independent multi-tag levels imported via an accounting solution? If so, then let's proceed with wave-collect as a `polish` item.

**Comment by isabelastisser** [comment]
I'm back, taking this! Thanks, @zanyrenney!

**Comment by isabelastisser** [comment]
@mkhutornyi, can you please follow up on[ this?](https://github.com/Expensify/App/issues/45497#issuecomment-2251782970)

**Comment by isabelastisser** [comment]
Thanks for confirming, @mkhutornyi! Closing.
