### ISSUE TITLE
[HOLD for payment 2024-07-24] Old Dot redirection - App crashes when redirected from OD when user ID ends with even number

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Account used: [applausetester+kh1507009@applause.expensifail.com](mailto:applausetester+kh1507009@applause.expensifail.com)

1. Go to staging.new.expensify.com
2. Create a new ND account.
3. Go to self DM.
4. Click on the self DM header.
5. Check if the URL ends with an even number. If not, keep creating accounts until it ends with an even number. (Important)
6. Log in to the same account (with ending even number in User ID) on OD.
6. Log out of ND.
7. Click on the bubble on OD.

This issue does not happen if the user ID ends with odd number.
## Expected Result:
App will not crash.

## Actual Result:
App crashes.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[Bug6543842_1721131672624!staging.new.expensify.com-1721131390252.txt](https://github.com/user-attachments/files/16253373/Bug6543842_1721131672624.staging.new.expensify.com-1721131390252.txt)

https://github.com/user-attachments/assets/d2d2c592-11b4-4d40-905c-2aa37707864f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by rojiphil** [comment]
> this might be similar to what i reported here https://expensify.slack.com/archives/C049HHMV9SM/p1721144087581819

Thanks @ishpaul777 for pointing this out. We will fix this.
cc @chiragsalian @pac-guerreiro @fabioh8010 @mountiny

**Comment by rojiphil** [comment]
@ShridharGoel Thanks for sharing insights into the problem. I don't think this needs to be external as this issue came from recent changes in our PR. So I will raise a PR to fix this.

**Comment by yuwenmemon** [comment]
@rojiphil when can we expect a PR?

**Comment by rojiphil** [comment]
> when can we expect a PR?

Working on this now. Will update in an hour.

**Comment by sonialiap** [comment]
Payment summary:
- @rojiphil $250 - offer sent in upwork
- @allgandalf $250 - offer sent in upwork

Thanks for completing the checklist so promptly! 🙇

**Comment by sonialiap** [comment]
Both payments completed 🚀
