### ISSUE TITLE
Android - App crashes when inviting a secondary email to a workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45506]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Prepare an account (Account A) where it has a secondary login already setup
2. Open the new expensify app and create a workspace
3. Go to invite members page
4. Invite account A using its secondary login email

## Expected Result:
Account A gets invited to the workspace without any issue

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7dfb1c5f-57a5-49f9-b4e9-ddbff90f4bb6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
![Screenshot 2024-07-16 at 2 15 57 PM](https://github.com/user-attachments/assets/36035610-9e90-4901-a1f0-8b596ef7cacb)
This might have been fixed, I tried it again and it seems to work okay. Asking for a re-test

**Comment by cead22** [comment]
Same, I couldn't reproduce the crash on either staging or prod

**Comment by kavimuru** [comment]
No reproducible anymore 

https://github.com/user-attachments/assets/9ade902a-548c-4152-9ecf-52853f7d5c5d
