### ISSUE TITLE
[$250] mWeb -Room - After message deleted, whisper is shown & tapping yes, not showing invited message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4724888
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a room
3. Enter [jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
4. Send the message
5. Note the whisper shown below
6. Delete the step 3 message
7. Tap yes in the whisper step 5 message

## Expected Result:
After message deleted, whisper must be disappeared along with Or on tapping yes, it must show invited message

## Actual Result:
After message deleted, whisper is shown & tapping yes, not showing invited message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/42de2bbe-4527-4a69-b8fd-180ef886be88

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4c58841ef2dc8cc</li>
        <li>Upwork Job ID: 1815530942177773068</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by alexpensify** [comment]
I'll test this one soon.

**Comment by alexpensify** [comment]
@mollfpr can you review if this proposal will fix this problem? Thanks!

**Comment by mollfpr** [comment]
@alexpensify Sure!

**Comment by mollfpr** [comment]
The [proposal](https://github.com/Expensify/App/issues/45501#issuecomment-2231708986) looks good to me!

However, we have a similar issue with LHN's alternate text still showing the whisper text.

![Screenshot 2024-07-24 at 02 03 21](https://github.com/user-attachments/assets/facd58b6-4ce2-4533-a330-5f1ad97f4d22)

I think we can fix that from the BE.

🎀 👀 🎀 C+ reviewed!

**Comment by alexpensify** [comment]
Maria is OOO this week, so I asked the team for help here: 

https://expensify.slack.com/archives/C03SSAQ7P/p1722279356005319

**Comment by rlinoz** [comment]
I think we shouldn't rely on assuming the `previousActionID` is necessarily the action that generated the whisper, for instance we can have 2 whispers in sequence when mentioning a new report and a user that is not a member of the room

<img width="688" alt="image" src="https://github.com/user-attachments/assets/f0040848-0365-4c2c-b47c-316dd18be607">


But I agree we should mark the whisper as deleted in the backend as well.

**Comment by rlinoz** [comment]
Oh, I think something is wrong with the test actually...

> After message deleted, whisper is shown & tapping yes, not showing invited message

@lanitochka17 there is no invitation in the video, there is no `@` before the email, when tapping yes the whisper only created the rooms.

**Comment by rlinoz** [comment]
Asked [internally on Slack](https://expensify.slack.com/archives/C066HJM2CAZ/p1722348046268499) what we should do here


> However, how can we achieve this?

I am not completely sure, would have to further investigate, but let's wait the result of the thread above.

**Comment by alexpensify** [comment]
Thank you, @rlinoz, for reviewing!

**Comment by rlinoz** [comment]
Closing this one since we agreed to just do nothing [here](https://expensify.slack.com/archives/C066HJM2CAZ/p1722348046268499), since the whisper resolution button still works.
