### ISSUE TITLE
[HOLD for payment 2024-08-01] Sage Intacct- "Entity" menu is empty and can not be navigated in Sage Intacct

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45514]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
The user has a workspace policy connected to Sage Intacct
1. Navigate to Workspace settings > Accounting
2. Go to the "Entity" menu

## Expected Result:
The user can navigate to the "Entity" page and change the entity

## Actual Result:
The "Entity" menu is empty and cannot be navigated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1d7aef70-caee-406a-bcb4-210e48c1d472

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
This is under beta, so demoting from being a deploy blocker.

**Comment by war-in** [comment]
Hi 👋 It seems that the backend returned empty `entities` in `data` and that's why you can't navigate to them. I have some entities in my account and I can normally navigate to the page.

https://github.com/user-attachments/assets/521bbf9f-eca4-4618-a30d-7e30ca901697

**Comment by puneetlath** [comment]
@yuwenmemon going to assign this over to you. Hope you don't mind.

**Comment by yuwenmemon** [comment]
@NikkiWines Looks like this is an issue with the initial sync - can you take a look?

**Comment by NikkiWines** [comment]
AFAICT this isn't an issue with the initial sync, it's just that we show this option regardless of whether or not there are entities returned - I'll push up a change so that the menu option is only shown if there are actually entities to select.

**Comment by brunovjk** [comment]
Just to confirm, @NikkiWines, is this [message](https://github.com/Expensify/App/issues/45514#issuecomment-2263659267) correct? I'm relatively new here, and I couldn't find information about paying for PR review without reviewing the issue/proposal first. Thanks a lot.

**Comment by NikkiWines** [comment]
No, in this case it's wrong, since you reviewed [this PR](https://github.com/Expensify/App/pull/45679) you are eligible for compensations. The automation didn't catch it cause you weren't assigned to this issue.  I'll add the appropriate labels so we can provide the appropriate comp

**Comment by brunovjk** [comment]
Good to know :D Thank you very much @NikkiWines

**Comment by abekkala** [comment]
### PAYMENT SUMMARY: 

- PR Review: @brunovjk [$250] [Offer](https://www.upwork.com/nx/wm/offer/103370311)

**Comment by abekkala** [comment]
@brunovjk payment sent and contract ended- thank you! 🎉
