### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Workspace - Not found page briefly appear on Accounting feature

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45517]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45239
## Action Performed:
1. Log in
2. Turn off the network connection
3. Click on the account icon
4. Navigate to workspaces
5. Create a new workspace
6. Click on More Features
7. Enable accounting feature
8. Click on the enabled feature section
9. Reconnect to the network

## Expected Result:
No "not found" page appears

## Actual Result:
Not found page briefly appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d09ad9eb-6076-416b-b561-bfdb084bb3b5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010656791d40958772</li>
        <li>Upwork Job ID: 1813317098317018164</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103160114</li>
<li>dominictb | Contributor | 103314660</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by jasperhuangg** [comment]
Definitely doesn't need to be a blocker since the functionality still works as expected. It looks like something is wrong with the data returned by the API?

**Comment by jasperhuangg** [comment]
Based on my reproduction here it seems like `EnablePolicyConnections` isn't setting the correct Onyx data (it looks like some optimistic data is being incorrectly reset).

I think this can actually be worked on externally.

**Comment by Zakpak0** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The "Accounting" integration returns a "Not Found" page when enabled in offline mode.
### What is the root cause of that problem?

[src/libs/actions/Policy/Policy.ts](https://github.com/Expensify/App/blob/24d05adfaa5644248a8f164043ffdf36bdbe65e0/src/libs/actions/Policy/Policy.ts#L2460-L2470)

```typescript
        sucessData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
                value: {
                    pendingFields: {
                        areConnectionsEnabled: null,
                    },
                },
```
The success data set by Onyx, reverts the Optimistic data that was set while offline.
Nothing is set.

### What changes do you think we should make in order to solve the problem?
```typescript
        successData: [
            {
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
                value: {
                    areConnectionsEnabled: enabled,
                    pendingFields: {
                        areConnectionsEnabled: null,
                    },
                },
```
Set the success data to enable the connection. I've observed that connection is enabled on page reload.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jasperhuangg** [comment]
@Zakpak0's proposal seems simple and fits within our existing patterns. Assigned!

**Comment by Zakpak0** [comment]
@jasperhuangg @dominictb is correct.
I missed a step in the reproduction.
My code only works when you create enable account **after** the workspace had already been created.
If you create the workspace while offline the bug remains.

**Comment by DylanDylann** [comment]
Whoops, ...... @jasperhuangg Please allow me to evaluate proposals again. @Zakpak0 please don't create the PR at this time

**Comment by DylanDylann** [comment]
@dominictb your proposal also doesn't work, please check again

**Comment by jasperhuangg** [comment]
@dominictb Thanks for the investigation, that seems like it should probably be handled with this issue–do you mind updating the OP to specify that?

**Comment by DylanDylann** [comment]
@dominictb 
1. Main solution
> To do it, update [this](https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/libs/actions/PolicyConnections.ts#L10)
to:
Onyx.merge(hasConnectionsDataBeenFetchedKey, false);

Do you have any other approach for this? It isn't a comment pattern in our codebase 

2. Alternative solution: Please provide a test branch or detailed implementation then I can test this approach. Thanks

@Krishna2323  Please provide a test branch or detail implementation then I can test this approach. Thanks

**Comment by DylanDylann** [comment]
@Krishna2323  Please provide a test branch or detail implementation then I can test this approach. Thanks

**Comment by jasperhuangg** [comment]
Proposals still under review

**Comment by jasperhuangg** [comment]
@DylanDylann bump on proposal review!

**Comment by DylanDylann** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/45517#issuecomment-2232895519) looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by jasperhuangg** [comment]
It makes sense to me as well, thank you for the investigation and discussion @DylanDylann. @dominictb let's move forward with implementing your alternative proposal!

**Comment by OfstadC** [comment]
## Payment Summary 

- @DylanDylann paid $250 via Upwork
- @dominictb paid $250 via Upwork
