### ISSUE TITLE
[Awaiting Payment 30th July, 2024] [CSV] Support Export CSV on native NewDot apps

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#45511]
This is a follow up to https://github.com/Expensify/App/issues/44576

**Problem:** Because of the lib we use to download files on mobile native we can't export the CSV file the same way we do it for web, since the lib doesn't allow a request body.

https://github.com/RonRadtke/react-native-blob-util/tree/master#:~:text=Download%20Manager%20can%20only%20support%20GET%20method%2C%20which%20means%20the%20request%20body%20will%20be%20ignored.

**Problem:** Find a way to download the CSV on the native apps.

**Comment by trjExpensify** [comment]
@filip-solecki can you comment on this issue so we can assign it to you as well?

**Comment by filip-solecki** [comment]
HI! I am Filip from SWM and I'd like to work on this!

**Comment by trjExpensify** [comment]
@rushatgabhane assigning you for C+ if we need it here.

**Comment by trjExpensify** [comment]
Confirming payment as follows: 

- $250 to @rushatgabhane for the C+ review

Regression tests have been added centrally for this project. Feel free to go ahead and request, Rushat. Closing!

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
