### ISSUE TITLE
[HOLD for payment 2024-08-14] [HOLD for payment 2024-08-09] Optimize frontend performance in most recent mode

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#45528]
### Problem
For moderate to large accounts like @JmillsExpensify's, the app frequently hangs and lags when doing basic actions like approving reports, pinning reports, etc. We know this performance should be better, but is it possible to optimize it only on the frontend, or do we also need to implement pagination to return less total reports.

### Solution
Profile the app when it's lagging to see where the most time is being spent and how we might improve it. Determine if optimizations will be sufficient or if pagination is required.

We have started investigating Jason's app performance in [this thread](https://expensify.slack.com/archives/C05LX9D6E07/p1721159029741309?thread_ts=1721060786.438019&cid=C05LX9D6E07).

cc @marcaaron @adhorodyski 

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by adhorodyski** [comment]
Hi, I'd like to work on this:)

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by dylanexpensify** [comment]
On it now, apologies!

**Comment by adhorodyski** [comment]
I think we can close this one since we've started creating separate issues for the performance related PRs recently?

**Comment by dylanexpensify** [comment]
@ishpaul777 were you reviewer here? 
@mkhutornyi were you paid?

**Comment by dylanexpensify** [comment]
Roger! Paying today!

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @ishpaul777 $250 
Contributor+: @mkhutornyi $1,000 

Please apply/request!

**Comment by dylanexpensify** [comment]
Please apply [here](https://www.upwork.com/jobs/~021831396658949918655)!

**Comment by dylanexpensify** [comment]
BTW sent offer @ishpaul777, invite to @mkhutornyi, @allgandalf mind applying?

**Comment by dylanexpensify** [comment]
@mkhutornyi @allgandalf sent offers!

**Comment by dylanexpensify** [comment]
Upwork being glitchy for me, attempting again today!

**Comment by dylanexpensify** [comment]
Done!
