### ISSUE TITLE
[HOLD for payment 2024-08-09] LHN - Long pressing chat does not show "Copy Onx Data" on all platforms

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45521]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Found when validating #https://github.com/Expensify/App/pull/45079
**Version Number:** 9.0.7-4
**Reproducible in staging?:** y  
**Reproducible in production?:** no, new feature 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Access New Expensify app
2. Sign into a valid account (Beta enabled)
3. Long press on LHN

## Expected Result:
User expects to see the option "Copy Onx Data" in popup menu

## Actual Result:
User can not see this option on iOS and Android app

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6544288_1721154095539!Missing_ONYX_Data_in_popup_](https://github.com/user-attachments/assets/c471f090-a8bd-495b-b6e6-e2c3a532dfd0)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
From [the PR](https://github.com/Expensify/App/pull/45079), this is behind a beta and dev/staging only, so I don't think it's a Web blocker, or even really a App blocker. 

>Adds a new field for the context menu that allows to quickly copy onyx data of any report from the LHP for staging, dev and internal build environments.

CC: @puneetlath @sobitneupane @cdOut @war-in

**Comment by cdOut** [comment]
This is not a blocker as it does not affect production and is only enabled for staging / dev and internal builds.

**Comment by trjExpensify** [comment]
>@m-natarajan did this happen on staging only? It seems like the conditional for checking the environment might have failed for some case there.

@m-natarajan bump on this Q!

**Comment by cdOut** [comment]
Second on the bump, I tried reproducing this one but I wasn't able to, were you testing this one on the emulators or using a physical device?

**Comment by m-natarajan** [comment]
@trjExpensify @cdOut Yes on staging only, I am using physical device (iPhone Xs, App version 9.0.11-0) and able to reproduce.

**Comment by cdOut** [comment]
Could you see whether it also happens for you when running on emulators?

**Comment by m-natarajan** [comment]
@cdOut  Applause QA never uses emulators.

**Comment by cdOut** [comment]
Alright, I'll test it on a physical device and see if I can replicate it then. Thank you for clearing that up!

**Comment by cdOut** [comment]
@m-natarajan has this been tested using an internal build or a staging build?

**Comment by trjExpensify** [comment]
From the screenie in the OP, it's a staging build: 

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/184ba1a6-c430-466e-b954-36636066070b">

**Comment by trjExpensify** [comment]
@sobitneupane needs paying here for the C+ review. 

Payment summary as follows: 

- $250 for the C+ review

Go ahead and request!

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
