### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Android - chat - After sending emoji art, tapping emoji picker app crashes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45523]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4727506
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. From the link - https://www.copyandpasteemojiart.com/?m=1
- copy the below image
4. Paste the image
5. Send the message
6. Tap emoji picker

## Expected Result:
After sending emoji art, tapping emoji picker app must not crash

## Actual Result:
After sending emoji art, tapping emoji picker app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/170ed0cf-c48e-4713-9b91-d9b3376e3eb9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01742f04a35f007ec9</li>
        <li>Upwork Job ID: 1814237444519918825</li>
        <li>Last Price Increase: 2024-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103213907</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment]
adding external

**Comment by zanyrenney** [comment]
@layacat can you apply for the job please?

**Comment by zanyrenney** [comment]
`payment summary`

paid @suneox $250 for reviewer.

waiting for @layacat to accept offer.

**Comment by zanyrenney** [comment]
thanks @layacat i sent you the offer!

**Comment by zanyrenney** [comment]
Brilliant, thank you so much @layacat !

**Comment by zanyrenney** [comment]
payment summary

paid @suneox $250 for reviewer via upwork

paid @layacat $250 for contributor role via upwork
