### ISSUE TITLE
[NetSuite] The Subsidiary field appears prior to the initial sync running successfully

### ISSUE THREAD

**Issue by zsgreenwald** [Expensify/App#45532]
# Part of the Add NetSuite to New Expensify project
Main issue: [Issue Link](https://github.com/Expensify/Expensify/issues/377671)
Doc section: [Doc Link](https://docs.google.com/document/d/1WubNv_VAv78IxG4FKsi9aS0pWESfWvUYbqBAAy5b4bc/edit?userstoinvite=manan.jadhav@gmail.com&sharingaction=manageaccess&role=writer#heading=h.1vf74ijo8qpn)
Project: [Project Link](https://github.com/orgs/Expensify/projects/130)

# Feature Description
The Subsidiary page is a standalone page that is included with NetSuite. Prior to the initial sync, it appears blank on it's own. It should not appear until the connection syncs successfully. See below.

![image](https://github.com/user-attachments/assets/6395018b-7b18-40dd-a145-8cd0596b3a08)

# Manual Test Steps
1. From Accounting, select NetSuite (in a new workspace with no prior connection)
2. Go through the token auth steps to setup the connection
3. Once the token auth step is complete, check to see if `Subsidiary` appears blank before the sync actually connects for the first time

# Automated Tests

**Comment by mananjadhav** [comment]
This was deployed to production last week. We can close this one out. Payout will be done centrally.

**Comment by JmillsExpensify** [comment]
Thanks!
