### ISSUE TITLE
Assigned guide is not shown in the supports tab but showing in overview

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45539]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721089665020699

## Action Performed:
1. Daniel supportalled into [matthewkohm@gmail.com](mailto:matthewkohm@gmail.com) to deal with a chat (https://www.expensify.com/concierge/#/chat/4984506).
2. They claimed they had a guide, but Daniel couldn’t see one in the Support tab.
3. Go to Settings > Workspace > Overview 
## Expected Result:
In the support tab the guide should be seen
## Actual Result:
Not seen in Support tab and seen only in overview of the workspace
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (24)](https://github.com/user-attachments/assets/458b9fd8-3338-48a6-9373-d53d62c84d8c)
![image (23)](https://github.com/user-attachments/assets/c8bcbc5b-5124-473a-be87-85902abd5c78)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment]
<img width="1319" alt="Screenshot 2024-07-17 at 2 56 19 PM" src="https://github.com/user-attachments/assets/6b30dfe4-a90e-4347-ab65-1fdbca4a011c">

**Comment by garrettmknight** [comment]
Confirming I see it now.
