### ISSUE TITLE
All the tasks showing up in LHN from onboarding

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45545]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721157138467329

## Action Performed:
1. Sign up as a new user
2. In the onboarding modal select "Manage my team" option
## Expected Result:
Tasks should be hidden to not overwhelm the LHN.
## Actual Result:
All the tasks are showing up in LHN.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/37db2b51-4700-4da3-a846-6a28cf08f0dc

https://github.com/user-attachments/assets/6f155665-e540-45a4-9d2c-0e181b2b6592

{
    "reportID": "6954030778651294",
    "reportName": "Invite your team",
    "description": "<strong>Invite your team</strong> to Expensify so they can start tracking expenses today.<br /><br />Here's how to invite your team:<br /><br />1. Click your profile picture.<br />2. Go to <a href=\"https://staging.new.expensify.com/settings/workspaces/012A79848365741E\" target=\"_blank\" rel=\"noreferrer noopener\"><strong>Workspaces</strong> &gt; [your workspace]</a>.<br />3. Click <strong>Members</strong> &gt; <strong>Invite member</strong>.<br />4. Enter emails or phone numbers. <br />5. Add an invite message if you want.<br /><br />That's it! Happy expensing :)",
    "ownerAccountID": 11665625,
    "participants": {
        "11665625": {
            "hidden": true
        },
        "17880961": {
            "hidden": false
        }
    },
    "managerID": 17880961,
    "type": "task",
    "parentReportID": "2681050416452188",
    "policyID": "_FAKE_",
    "stateNum": 0,
    "statusNum": 0,
    "notificationPreference": "always",
    "lastVisibleActionCreated": "2024-07-16 18:51:27.669",
    "hasParentAccess": true,
    "parentReportActionID": "5822571659774678620",
    "pendingFields": {},
    "isOptimisticReport": false,
    "state": "OPEN",
    "chatReportID": "2681050416452188",
    "chatType": "",
    "currency": "USD",
    "errorFields": {},
    "hasOutstandingChildRequest": false,
    "hasOutstandingChildTask": false,
    "isCancelledIOU": false,
    "isOwnPolicyExpenseChat": false,
    "isPinned": false,
    "isWaitingOnBankAccount": false,
    "lastActionType": "CREATED",
    "lastActorAccountID": "11665625",
    "lastMessageHtml": "",
    "lastMessageText": "",
    "lastReadSequenceNumber": 0,
    "lastVisibleActionLastModified": "2024-07-16 18:51:27.669",
    "nonReimbursableTotal": 0,
    "oldPolicyName": "",
    "permissions": [
        "read"
    ],
    "private_isArchived": false,
    "total": 0,
    "unheldTotal": 0,
    "welcomeMessage": "",
    "writeCapability": "all"
}
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tony-MK** [comment]
@puneetlath, I believe this issue is handled in the BE since the `CompleteGuideSetup` returns `"notificationPreference": "always"` for every task report the backend has created.

Therefore, the `notificationPreference` should be changed to `hidden`.

**Comment by puneetlath** [comment]
This is fixed now 

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/bc21cfb3-63d9-4317-afe3-8483bd99a398">
