### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] Features in Workspace LHN are not in the same order as in "More Features"

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#45549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** All
**Logs:** N/A
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zsgreenwald 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1721165288016089

## Action Performed:
1. Go to a workspace
2. Turn on all features in under "More features"
3. They should all appear in the LHN for the workspace
4. Observe that the order they are in does not match what's in "More features"

## Expected Result:
The order of the items in the LHN should be in the same order as they are in "More features"

## Actual Result:
The order of the items does not match the order in "More features"

## Workaround:
Yes, this is a small polish bug.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-07-16 at 3 23 22 PM](https://github.com/user-attachments/assets/f9f3eebc-79a4-4bc6-b4c0-6f3264331208)

![Screenshot 2024-07-16 at 6 05 48 PM](https://github.com/user-attachments/assets/dc0df755-0053-46e6-985b-764e0f61c427)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d9f00389c515c84</li>
        <li>Upwork Job ID: 1813380721244668134</li>
        <li>Last Price Increase: 2024-07-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by yuwenmemon** [comment]
Thanks @Krishna2323 looks good.

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The order of the items does not match the order in "More features"

### What is the root cause of that problem?
We push the accounting option before the report field option

https://github.com/Expensify/App/blob/10d04a80acbd17c2cf71700ef745bb1852c3d663/src/pages/workspace/WorkspaceInitialPage.tsx#L287
### What changes do you think we should make in order to solve the problem?
To make the code cleaner, we can create a `collectMenuItems` that contains all feature items

```
const collectMenuItems: Record<PolicyFeatureName,WorkspaceMenuItem> = {
    [CONST.POLICY.MORE_FEATURES.ARE_DISTANCE_RATES_ENABLED]: {
        translationKey: 'workspace.common.distanceRates',
        icon: Expensicons.Car,
        action: singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.WORKSPACE_DISTANCE_RATES.getRoute(policyID)))),
        routeName: SCREENS.WORKSPACE.DISTANCE_RATES,
    },
    [CONST.POLICY.MORE_FEATURES.ARE_WORKFLOWS_ENABLED]: {
        translationKey: 'workspace.common.workflows',
        icon: Expensicons.Workflows,
        action: singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.WORKSPACE_WORKFLOWS.getRoute(policyID)))),
        routeName: SCREENS.WORKSPACE.WORKFLOWS,
        brickRoadIndicator: !isEmptyObject(policy?.errorFields?.reimburser ?? {}) ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : undefined,
    },
    [CONST.POLICY.MORE_FEATURES.ARE_CATEGORIES_ENABLED]: {
        translationKey: 'workspace.common.categories',
        icon: Expensicons.Folder,
        action: singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.WORKSPACE_CATEGORIES.getRoute(policyID)))),
        brickRoadIndicator: hasPolicyCategoryError ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : undefined,
        routeName: SCREENS.WORKSPACE.CATEGORIES,
    },
    [CONST.POLICY.MORE_FEATURES.ARE_TAGS_ENABLED]: {
        translationKey: 'workspace.common.tags',
        icon: Expensicons.Tag,
        action: singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.WORKSPACE_TAGS.getRoute(policyID)))),
        routeName: SCREENS.WORKSPACE.TAGS,
    },
    [CONST.POLICY.MORE_FEATURES.ARE_TAXES_ENABLED]: {
        translationKey: 'workspace.common.taxes',
        icon: Expensicons.Coins,
        action: singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.WORKSPACE_TAXES.getRoute(policyID)))),
        routeName: SCREENS.WORKSPACE.TAXES,
        brickRoadIndicator: PolicyUtils.hasTaxRateError(policy) ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : undefined,
    },
    [CONST.POLICY.MORE_FEATURES.ARE_CONNECTIONS_ENABLED]: {
        translationKey: 'workspace.common.accounting',
        icon: Expensicons.Sync,
        action: singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.POLICY_ACCOUNTING.getRoute(policyID)))),
        // brickRoadIndicator should be set when API will be ready
        brickRoadIndicator: undefined,
        routeName: SCREENS.WORKSPACE.ACCOUNTING.ROOT,
    },
    [CONST.POLICY.MORE_FEATURES.ARE_EXPENSIFY_CARDS_ENABLED]: {
        translationKey: 'workspace.common.expensifyCard',
        icon: Expensicons.CreditCard,
        action: singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.WORKSPACE_EXPENSIFY_CARD.getRoute(policyID)))),
        routeName: SCREENS.WORKSPACE.EXPENSIFY_CARD,
    },
    [CONST.POLICY.MORE_FEATURES.ARE_REPORT_FIELDS_ENABLED]: {
        translationKey: 'workspace.common.reportFields',
        icon: Expensicons.Pencil,
        action: singleExecution(waitForNavigate(() => Navigation.navigate(ROUTES.WORKSPACE_REPORT_FIELDS.getRoute(policyID)))),
        routeName: SCREENS.WORKSPACE.REPORT_FIELDS,
    },
}
```

And then get `protectedCollectPolicyMenuItems` by getting the feature that is enabled in `collectMenuItems`. With this change, we can remove all if conditions that we used to push the feature item.

```
const protectedCollectPolicyMenuItems: WorkspaceMenuItem[] = (Object.keys(featureStates ?? {}) as PolicyFeatureName[]).filter((featureKey) => featureStates[featureKey]).map((featureKey) => {
    return collectMenuItems[featureKey];
});
```

After that, we only need to re-order the feature here

```
const policyFeatureStates = useMemo(
    () => ({
        [CONST.POLICY.MORE_FEATURES.ARE_DISTANCE_RATES_ENABLED]: policy?.areDistanceRatesEnabled,
        [CONST.POLICY.MORE_FEATURES.ARE_EXPENSIFY_CARDS_ENABLED]: policy?.areExpensifyCardsEnabled,
        [CONST.POLICY.MORE_FEATURES.ARE_WORKFLOWS_ENABLED]: policy?.areWorkflowsEnabled,
        [CONST.POLICY.MORE_FEATURES.ARE_CATEGORIES_ENABLED]: policy?.areCategoriesEnabled,
        [CONST.POLICY.MORE_FEATURES.ARE_TAGS_ENABLED]: policy?.areTagsEnabled,
        [CONST.POLICY.MORE_FEATURES.ARE_TAXES_ENABLED]: policy?.tax?.trackingEnabled,
        [CONST.POLICY.MORE_FEATURES.ARE_REPORT_FIELDS_ENABLED]: policy?.areReportFieldsEnabled,
        [CONST.POLICY.MORE_FEATURES.ARE_CONNECTIONS_ENABLED]: policy?.areConnectionsEnabled,
    }),
    [policy],
) as PolicyFeatureStates;
```
https://github.com/Expensify/App/blob/10d04a80acbd17c2cf71700ef745bb1852c3d663/src/pages/workspace/WorkspaceInitialPage.tsx#L102
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
@yuwenmemon Sorry for the late, can you please take a look at my proposal [here](https://github.com/Expensify/App/issues/45549#issuecomment-2232398989)? That can make the code cleaner and we only need to re-order in `policyFeatureStates` which is easier to keep track.

**Comment by kaushiktd** [comment]
@yuwenmemon  I noticed that in my  application currently  "report field" feature not show as in you. Could you please guide me on how i get it
![Screenshot 2024-07-17 at 10 29 29 AM](https://github.com/user-attachments/assets/61d76a14-38a4-4896-92a6-cf0aeb9e2dbb)

**Comment by OfstadC** [comment]
Adding @CortneyOfstad in since this needs a manual offer and i'm out today

**Comment by CortneyOfstad** [comment]
@sobitneupane please complete the checklist as soon as possible, so there is no delay in payment — thank you!

@Krishna2323 — I sent you an offer in Upwork, please let me know once you accept and I can get that paid ASAP. Thank you!

**Comment by CortneyOfstad** [comment]
Thanks @Krishna2323 – contract paid!

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/43896 and https://github.com/Expensify/App/pull/43943 
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/43896#issuecomment-2255510489 and https://github.com/Expensify/App/pull/43943#issuecomment-2255509210
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not required.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.

> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal:**

1. Go to a workspace
2. Turn on all features in under "More features"
3. They should all appear in the LHN for the workspace
4. Verify that the order of the items in the LHN is in the same order as they are in "More features"

Do we agree 👍 or 👎

**Comment by yuwenmemon** [comment]
Looks great @sobitneupane

**Comment by OfstadC** [comment]
Thanks @sobitneupane !

**Comment by OfstadC** [comment]
https://github.com/Expensify/Expensify/issues/416301

@CortneyOfstad can you please finish the payment while i'm OoO today

**Comment by CortneyOfstad** [comment]
## Payment Summary

@Krishna2323 — paid $250 via Upwork
@sobitneupane — to be paid $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @sobitneupane
