### ISSUE TITLE
Inbox - Hmm… page opens briefly when click on Account settings and then on Inbox

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45561]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+jpcategory_1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Click on Account settings
4. Click on Inbox

## Expected Result:
Chat open without Hmm... page

## Actual Result:
Hmm… page opens briefly in the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ded5d1d6-736a-4c5a-b800-f7e06f752f70

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by jliexpensify** [comment]
I can repro, but I wouldn't imagine this is a deploy blocker right @madmax330 ?

**Comment by thienlnam** [comment]
Agree, doesn't really look like a blocker

**Comment by thienlnam** [comment]
Also, looks related to https://github.com/Expensify/App/issues/45565

**Comment by jliexpensify** [comment]
Waiting on @madmax330

**Comment by madmax330** [comment]
commented on the issue Jack linked, if it's not the same we probably just need to make this external

**Comment by jliexpensify** [comment]
Going to close this one out, as Fedi could [not replicate](https://github.com/Expensify/App/issues/45565#issuecomment-2251458325) anymore.
