### ISSUE TITLE
[HOLD for payment 2024-07-26] [#Wave-Control - Add Sage Intacct] Fix layout spacing

### ISSUE THREAD

**Issue by hungvu193** [Expensify/App#45578]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1720475656078959

## Action Performed:
Precondition: User should connect their policy with SageIntacct.
1. Go to Accounting => Advance
2. Observe the spacing between switch toggle.

## Expected Result:
Gap between switch toggles should be match with the mockup

## Actual Result:
Gap between switch toggles are too tight

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2024-07-17 at 10 47 19](https://github.com/user-attachments/assets/1f3ee715-acfa-415d-96f9-11b033538812)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by hungvu193** [comment]
cc @war-in

**Comment by war-in** [comment]
Hey 👋 I'll take care if this issue so please assign me 🙏

**Comment by trjExpensify** [comment]
Assigned! Assuming @hungvu193, you're taking C+.

**Comment by hungvu193** [comment]
> [!NOTE]  
> No payment needed for this issue.

**Comment by trjExpensify** [comment]
Awesome, no payment needed. Closing!
