### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Group - Invalid group chat name entered after group creation shows error.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45586]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4730508
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab - start chat
3. Select " Add to group" next to a user
4. Tap next
5. Tap group name
6. Remove the text and paste invalid group name - adoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoaỏ
7. Tap start group
8. Tap header
9. Tap group name
10. Remove the group name and replace with any text and save it
11. Again tap group name
12. Paste - invalid group name - adoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoajdoajadoadoadoajdoajdoadoaỏ
13. Tap save

## Expected Result:
Invalid group chat name entered while creating group or after group creation must behave in the same way.

## Actual Result:
Invalid group chat name entered while creating group not showing error but entered after group creation shows error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b1129b91-b0a2-49fe-a8e4-8c1817d30b3a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114cd4bde59962aa8</li>
        <li>Upwork Job ID: 1815530149727742960</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103256417</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by alexpensify** [comment]
Other GHs have been a priority, I'll review soon

**Comment by alexpensify** [comment]
Still on my testing list

**Comment by alexpensify** [comment]
@sobitneupane -  can you review if one of these proposals will fix this solution? Thanks!

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/45586#issuecomment-2244820130) from @dominictb looks good to me. The change proposed will ensure the FE validation. We might want to validate the groupChatName in BE as well during group creation. Looks like the validation is only done when groupChatName is updated.

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment]
agreed that @dominictb's proposal looks good 👍

**Comment by alexpensify** [comment]
Awesome, this PR is moving along, and we are waiting for it to go to production.

**Comment by alexpensify** [comment]
Noted that the payment date is on August 7

**Comment by alexpensify** [comment]
Payouts due: August 7, 2024

- [ ] Contributor: $250 @dominictb - I sent an offer to Upwork 
- [ ] Contributor+: $250 @sobitneupane - Please submit a request in Upwork 

Upwork job is [here](https://www.upwork.com/jobs/~0114cd4bde59962aa8).

**Comment by alexpensify** [comment]
Closing - the upwork process is complete

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
