### ISSUE TITLE
Android - Share code - Share code is not showing custom avatar

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45599]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4727436
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Login with user having custom avatar
3. Open a DM with user having custom avatar
4. Tap plus icon -- submit expense
5. Enter an amount and tap next
7. Tap submit
8. Open the IOU
9. Tap header - share code

## Expected Result:
In iou details page, share code must show custom avatar in center of qr code

## Actual Result:
In iou details page, share code is not showing custom avatar in center of qr code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6956699b-b0d9-4a21-9ea2-af8bf564fdbc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by dylanexpensify** [comment]
I believe you're right @gijoe0295, but confirming internally just for good measure

**Comment by dylanexpensify** [comment]
being addressed [here](https://github.com/Expensify/App/pull/39072#issuecomment-2232484565)
