### ISSUE TITLE
Rgression test for #42472

### ISSUE THREAD

**Issue by zanyrenney** [Expensify/App#45595]
Please add the following regression test for https://github.com/Expensify/App/issues/42472

1. Submit an expense report with one expense as an employee
2. Sign in as an approver of the expense report (shouldn't be signed in before so that you don't have the expense report or transaction thread locally)
3. Throttle network connection to slow 3G, so that OpenReport takes a little bit to return
4. Click on the expense report to view the details
5. Verify that no green New line like a comment

**Comment by isagoico** [comment]
Going to close this one as :do-nothing: as it's a flow that will not affect a big pool of users if it happens again and it would not block users from using the app.
