### ISSUE TITLE
Xero - Export button is showing in report details page for Admin, but not for Employee

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45590]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** New feature
**Found when validating PR :** https://github.com/Expensify/App/pull/44170
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Admin and employee are in the same workspace.
- Workspace is connected to Xero.

1. Go to staging.new.expensify.com
2. [Employee] Submit an expense in the workspace chat.
3. [Admin] Go to workspace chat with employee.
4. [Admin] Click on the expense preview.
5. [Admin] Pay elsewhere the report.
6. [Admin and employee] Note that there is Xero action button in the header.
7. [Admin and employee] Click on the report header.

## Expected Result:
There should be consistency in showing Export button in report details page for both admin and employee.

## Actual Result:
Export button is showing in report details page for Admin, but not for Employee.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d30a0607-ac2e-4cba-9b35-ffe989a9692d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by kosmydel** [comment]
I'm not sure, but this might be expected: https://github.com/Expensify/App/pull/45577

**Comment by hungvu193** [comment]
I think it's expected that we only show export button with admin or manager.

**Comment by lakchote** [comment]
> I think it's expected that we only show export button with admin or manager.

Exactly. We should only show the export button if it's an admin or manager. 

cc @trjExpensify 

Currently we're showing the export option for both (Admin/Manager and Member) if we're in a QBO setup which is wrong.

My PR https://github.com/Expensify/App/pull/45577 solves that so it only shows the export to integration button if it's an Admin/Manager, just like the backend expects it.

**Comment by rlinoz** [comment]
Cool, so we can close this one as working as expected.

**Comment by trjExpensify** [comment]
Moving over to the PR for that Q. 👀
