### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] LHN -  Large part of the LHN isn't translated to Spanish if setting changed on a secondary device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45608]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Main device: Log in with an account that has an archived workspace chat and an active workspace
2. Main device: Navigate to the LHN
3. Secondary device: Log in with the same account
4. Secondary device: Navigate to Account settings - Preferences - Language
5, Secondary device: Set the language to Spanish

## Expected Result:
The LHN should be fully translated to Spanish

## Actual Result:
Large part of the LHN isn't translated to Spanish if the setting is changed on a secondary device. The issue only happens if the main device is on the LHN when the change is happening. Affects archived WS chats, Expensify chat, announce and admins rooms, Concierge chat, Self DM

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/aacf00b8-ef02-44c6-9dc1-d06397d15004

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb790ac00a89dc06</li>
        <li>Upwork Job ID: 1816186931982084061</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Some part of the LHN isn't being translated dynamically when changing the language from another client.

### What is the root cause of that problem?
The LHN list doesn't re-render when the language/locale changes. It only re-renders when the item is updated or the `extraData` is updated. However, we don't add the language as the `extraData`.
https://github.com/Expensify/App/blob/a26d766ef8f81903697d38c4d01fdf8d65f2d2e6/src/components/LHNOptionsList/LHNOptionsList.tsx#L177-L180

### What changes do you think we should make in order to solve the problem?

Add `preferredLocale` to the `extraData`, so the list re-renders when it's changed.

_We can optionally include all [`renderItem` deps](https://github.com/Expensify/App/blob/a26d766ef8f81903697d38c4d01fdf8d65f2d2e6/src/components/LHNOptionsList/LHNOptionsList.tsx#L160-L174) as the `extraData`_

**Comment by strepanier03** [comment]
I don't have two iOS devices to test this with :( sending to external and trusting in the community and C+ to accurately test this 🤞

**Comment by s77rt** [comment]
@nyomanjyotisa Your RCA is not correct. `getOrderedReportIDs` have nothing to do with localization.

**Comment by s77rt** [comment]
@bernhardoj Your RCA is correct. Adding `preferredLocale` to `extraData` makes sense to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/45608#issuecomment-2233544394)

**Comment by bernhardoj** [comment]
PR is ready

cc: @s77rt

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/31711
- The offending PR has been commented on: https://github.com/Expensify/App/pull/31711#discussion_r1703426008
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1722818536053499
- Determine if we should create a regression test for this bug: No, this test https://expensify.testrail.io/index.php?/cases/view/1971043 should be enough

**Comment by strepanier03** [comment]
### Payment Summary

- $250 - @s77rt via New Expensify manual request
- $250 - @bernhardoj via New Expensify manual request

@JmillsExpensify - two payment requests incoming.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt

**Comment by strepanier03** [comment]
Looks like this is done, thank you all!
