### ISSUE TITLE
Netsuite - Stuck in 'Initializing connection to NetSuite' when Reuse existing connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45610]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45375
## Action Performed:
Precondition: User already has workspace with NetSuit connected
1. Create a new workspace (or use another if already exist)
2. Enable Accounting in More features
3. Choose Accounting > NetSuit
4. Click Connect > Reuse existing connection
5. Choose workspace mentioned in precondition

## Expected Result:
Connection established. Sync is done

## Actual Result:
Connection stuck in status 'Initializing connection to NetSuite'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a8abd132-060a-4b2c-b92a-625b8aee2d7d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
This feature is behind a beta so not a blocker.

**Comment by yuwenmemon** [comment]
Able to reproduce. Taking a look soon.

**Comment by yuwenmemon** [comment]
This is on prod, closing!
