### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Android - Workspace - WS description with markdown is not shown correctly on opening preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45635]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4697842
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap profile icon -- Workspaces -- workspace
3. Tap description
4. Enter ~fhjj~ _57_
5. Tap Save
6. Tap description again and note markdown shown as it was entered
7. Now change markdown as ~😃~ _57_
8. Tap save
9. Tap description again and note markdown

## Expected Result:
Workspace description should be shown as ~😃~ _57_

## Actual Result:
Workspace description should be shown as ~😃~ _57_ but displayed as ~_😃~ 57_

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/117ce0cc-ac28-4a6e-99cb-f9f9e93a7185

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183f826d1418b3bc1</li>
        <li>Upwork Job ID: 1815267370451723401</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 103221829</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
Able to recreate. Agree this best fits under vip_vsb

**Comment by VictoriaExpensify** [comment]
@parasharrajat - were you able to identify the PR that caused this bug? Are you able to link it here? 🙏

**Comment by VictoriaExpensify** [comment]
No prob, thanks for your help and input @parasharrajat

**Comment by VictoriaExpensify** [comment]
**Payment Summary**

Contributor:  @gijoe0295 paid $250 via [Upwork](https://www.upwork.com/jobs/~0183f826d1418b3bc1)
Contributor+: @parasharrajat owed $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
