### ISSUE TITLE
[Pending / Scanning] Expense - Duplicate expense report displayed when submitting scan expenses

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45638]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
precondition: user is a member of a workspace
Method 1 (it reproduces more frequently on Android):
1. Go to https://staging.new.expensify.com/
2. Navigate to the workspace chat
3. Submit 2 scan expense
4. Delete one of them
5. Submit another scan receipt
Method 2:
Steps 1-2 are the same as in Method 1
3. Submit one receipt and wait for scanning complete or fail
4. Submit another scan expense

## Expected Result:
Only one report with scan expenses is displayed in the workspace chat

## Actual Result:
Duplicated expense report is displayed after submitting another scan expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3ae9403a-40b6-4b8a-8061-38b3d0d5c2ee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Seems pending/scanning related: https://expensify.slack.com/archives/C036QM0SLJK/p1721264373883309?thread_ts=1721057501.185889&cid=C036QM0SLJK

**Comment by trjExpensify** [comment]
I'll add it to #wave-collect in the meantime anyhow.

**Comment by youssef-lr** [comment]
yes!

**Comment by youssef-lr** [comment]
We can close this, it's deployed & fixed.
