### ISSUE TITLE
Chat - Chat is auto scrolled up when opened for the first time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to http://staging.new.expensify.com/
2. [User A] Create a new workspace
3. [User A] Invite User B to the workspace
4. [User B] Open workspace switcher
5. [User B] Click on the invited workspace. (This will open the workspace chat for the first time)

## Expected Result:
- Chat will not auto scroll up when opened for the first time
- Skeleton will disappear once the chat is loaded

## Actual Result:
- Chat auto scrolls up when opened for the first time
- Skeleton still remains briefly when the chat background is loaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/33df9a38-5468-44b4-ba11-73ccedf93fe2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment]
@tgolen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by thienlnam** [comment]
Looks potentially related: https://github.com/Expensify/App/pull/44724

**Comment by youssef-lr** [comment]
@thienlnam let me try reverting it locally and see if I can reproduce

**Comment by bernhardoj** [comment]
Can't test it, looks like the invite member is broken.
<img width="449" alt="image" src="https://github.com/user-attachments/assets/e68304f0-8cdd-4414-ae40-b081de785222">

**Comment by mountiny** [comment]
Looking at the video, this does not seem like a blocker to me, the skeleton disappeared after a second, this is minor ux issue

**Comment by mountiny** [comment]
I could not really reproduce this issue either

https://github.com/user-attachments/assets/85ff3d0a-9396-4bb7-bb19-c952bfd18845

**Comment by kavimuru** [comment]
@mountiny bug is fixed. 

https://github.com/user-attachments/assets/7c66fe5c-e69a-42a2-a143-8a1bb652ee0e

**Comment by mountiny** [comment]
Nice, thanks!
