### ISSUE TITLE
[CRITICAL] Unable to access travel booking flow after accepting terms

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#45647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  v9.0.8-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** kevin+travel2@expensifail.com 
**Issue reported by:** @kevinksullivan 
**Slack conversation:**  https://expensify.slack.com/archives/C05S5EV2JTX/p1721254929395389?thread_ts=1720035711.946819&cid=C05S5EV2JTX

## Action Performed:

1. Signed up with new account on SpotnanaTravel beta (you can create an account using your @expensifail.com as that is on the beta)
2. Validated account
3. Created workspace
4. Opened global create and selected Book travel
5. Accepted terms

## Expected Result:
Should land in the travel booking flow

## Actual Result:
- Hit an error code: `INVALID_REQUEST`
- No auth token in [this case
](https://expensify.slack.com/archives/C05S5EV2JTX/p1721256382025789?thread_ts=1720035711.946819&cid=C05S5EV2JTX)

## Screenshots/Videos

Different screenshots from trials (failed to get this to work ~5 times). Additional screenshots in the slack thread.

![image](https://github.com/user-attachments/assets/d27b58d8-b109-4bb3-a057-056c33f8a1ab)

<img width="1340" alt="image" src="https://github.com/user-attachments/assets/4a7897c8-09df-43a8-8f86-fcd1ff5a4b65">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by zanyrenney** [comment]
adding external to get eyes on this!

**Comment by kevinksullivan** [comment]
Discussing here

https://expensify.slack.com/archives/C05S5EV2JTX/p1721406118373969

**Comment by zanyrenney** [comment]
bumped the thread about this specific error and asked @stitesExpensify if he heard back from Spotnana.

**Comment by stitesExpensify** [comment]
Still investigating this

**Comment by stitesExpensify** [comment]
Just more slack discussion trying to figure out what's going on [here](https://expensify.slack.com/archives/C05S5EV2JTX/p1722266144651209?thread_ts=1721995901.939849&cid=C05S5EV2JTX)

**Comment by stitesExpensify** [comment]
This is fixed!
