### ISSUE TITLE
Initial value incorrectly appears above List values for report field configuration

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45648]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-3
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721250852064199

## Action Performed:

1. Make sure you are on the reportFields beta
2. On NewDot, create a workspace
3. In More features, enable Report fields
4. Create a dropdown report field, with several values. Add several initial values

## Expected Result:
 `Initial value` appears below `List values`

## Actual Result:
` Initial value` appears above `List values`
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/user-attachments/assets/d9e5200e-08c9-4b06-9414-bd2572a49955" width="40%" height="40%">

![Snip - (4) New Expensify - Google Chrome (3)](https://github.com/user-attachments/assets/be14464b-0343-40c4-866f-831b3172c188)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
Holding on this one until we decide what to do with the list values row: [internal link](https://expensify.slack.com/archives/C06ML6X0W9L/p1721294832438389?thread_ts=1721148004.979399&cid=C06ML6X0W9L)

**Comment by mountiny** [comment]
@Krishna2323 @gijoe0295 @dominictb Based on the internal discussion, we also want to make one change to how we show the list values, this is covered in this issue https://github.com/Expensify/App/issues/45990 and I will close this one in favour of the more generic issue as this change is super simple and not worth exporting on its own.

Waiting for a confirmation from design on that issue
