### ISSUE TITLE
Add GL/Payroll/Tax code when exporting a CSV

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#45644]
Coming from: [slack](https://expensify.slack.com/archives/C06ML6X0W9L/p1721253148286619?thread_ts=1721148029.626019&cid=C06ML6X0W9L)

When exporting a report to CSV, make sure that it contains GL/Tax/Payroll code if they are present.

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by dylanexpensify** [comment]
@alexpensify will take as project lead for this initiative!

**Comment by alexpensify** [comment]
Thanks for the update!

**Comment by dylanexpensify** [comment]
@rushatgabhane will this need any BE work?

**Comment by rushatgabhane** [comment]
@dylanexpensify i think this is 100% backend work

**Comment by Gonals** [comment]
Grabbing this!

**Comment by Gonals** [comment]
Should be done!

**Comment by Gonals** [comment]
I think we can close this! @dylanexpensify, what do you think?
