### ISSUE TITLE
[HOLD for payment 2024-07-25] [$50] Login – Hmm… page opens when login with Google/Apple button or existing account

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#45657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-3
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4729153
**Email or phone of affected tester (no customers):**  ivkinde@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:**  Applause internal team
**Slack conversation:**

## Action Performed:
1.	Go to https://staging.new.expensify.com/
2.	Log in with Google/Apple button or existing account

## Expected Result:
User is able to open the chat

## Actual Result:
Hmm… page opens instead of the chat

## Workaround:
none

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-07-18 at 12 04 38 AM](https://github.com/user-attachments/assets/afec67de-ead0-466d-8704-2ab2b8cd8ae4)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0a7ea00898e7c40</li>
        <li>Upwork Job ID: 1813896725050934834</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 103170213</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by mvtglobally** [comment]
We think that this bug might be related to #vip-vsp

**Comment by robertjchen** [comment]
I can reproduce on staging and it's a blocker for sure

**Comment by mountiny** [comment]
$50 to @allgandalf for their help identifying the offending PR

**Comment by mountiny** [comment]
No the offending PR is identified and the authors know cc @bernhardoj

**Comment by kavimuru** [comment]
@mountiny bug is fixed 

https://github.com/user-attachments/assets/58449c51-f02b-41e1-bf85-00f782a86dee

**Comment by dylanexpensify** [comment]
Payment coming up!

**Comment by mountiny** [comment]
$50 to @allgandalf

**Comment by dylanexpensify** [comment]
Payment summary:
- Contributor+: @allgandalf $50

Please apply/request!

**Comment by dylanexpensify** [comment]
done!
