### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Xero export - Different thread title when opening export error message in thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45669]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/44170
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Admin and employee are in the same workspace.
- Workspace is connected to Xero.

1. Go to staging.new.expensify.com
2. [Admin] Create a new Chart of accounts on Xero site which will be deleted later.
3. [Admin] Manually sync the changes on Accounting settings on New Dot.
4. [Employee] Submit an expense to the workspace chat using the new Chart of accounts (category).
5. [Admin] Delete the new Chart of accounts in Step 2.
6. [Admin] Manually sync the changes on Account settings on New Dot.
7. [Admin] Open the expense report and pay elsewhere.
8. [Admin] Click Export to Xero.
9. [Admin] Revisit the expense report until the error (failed ro export message) shows up.
10. [Admin] Right click on the message > Reply in thread.

## Expected Result:
The thread title will show the same message as the system message.

## Actual Result:
The thread title shows "Unable to manually export this report due to" when the system message is "failed to export this report to Xero ("Expense 'er' has an invalid category")."

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/373aac1c-42f0-4472-bdca-9bfe1c8427a7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013886dead77d6833c</li>
        <li>Upwork Job ID: 1813939037666714620</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by mountiny** [comment]
@kosmydel @hungvu193 This is coming from your PR, can you please handle the fix? @arosiclair in case you want to take over too 

I dont think this is a blocker as its a minor ux issue

**Comment by hungvu193** [comment]
Sure, let me take a look

**Comment by hungvu193** [comment]
We recently added integration message here:
https://github.com/Expensify/App/blob/6ec0f1592d2dae930d32784350058734d9cc7027/src/libs/ReportActionsUtils.ts#L1246-L1250

However we don't have logic to format our thread title if its parent was integration message in `getReportName` function, so it will return this message here:
https://github.com/Expensify/App/blob/6ec0f1592d2dae930d32784350058734d9cc7027/src/libs/ReportUtils.ts#L3386

Which will get the result like in the video above:

<img width="633" alt="Screenshot 2024-07-18 at 18 46 28" src="https://github.com/user-attachments/assets/309b7263-0495-42b6-a4af-a96ba5ba9f00">

IMO, we should add a specific case for thread of integration message.

**Comment by hungvu193** [comment]
cc @arosiclair

**Comment by arosiclair** [comment]
@hungvu193 thanks for the details that proposal LGTM. Can you post a PR?

**Comment by hungvu193** [comment]
Sure. I'll raise a PR in next few hours

**Comment by arosiclair** [comment]
Cool assigning another C+

**Comment by OfstadC** [comment]
@hungvu193 Could you please complete the checklist ?

**Comment by hungvu193** [comment]
I think @fedirjh will need to complete checklist as he's C+ here 😄

**Comment by OfstadC** [comment]
@fedirjh Please complete the checklist today. Thank you!

**Comment by hungvu193** [comment]
Requested payment on ND

**Comment by OfstadC** [comment]
### **Payment Summary:**
@hungvu193 due $250 via NewDot 
@fedirjh due $250 via NewDot (please complete the checklist ASAP)

**Comment by JmillsExpensify** [comment]
$250 approved for @fedirjh based on confirmed payment summary above.

**Comment by OfstadC** [comment]
Thanks @fedirjh 

https://github.com/Expensify/Expensify/issues/418126

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
