### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] Taxes - App blinks after saving tax code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45684]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is under Control plan
1. Go to staging.new.expensify.com
2. Go to Control workspace settings
3. Go to Taxes
4. Click on any tax
5. Click Tax code
6. Edit the tax code
7. Save it

## Expected Result:
App will not blink after saving tax code

## Actual Result:
App blinks after saving tax code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4f4bfd53-b32e-49af-90fa-29f932f62bfb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c99af8616c4c904d</li>
        <li>Upwork Job ID: 1813973597069496991</li>
        <li>Last Price Increase: 2024-07-18</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103179553</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by carlosmiceli** [comment]
The blinking doesn't happen only when you edit a tax code, but also when you click on a tax to edit it. However, it's such an imperceptible/small issue that I wouldn't call this a blocker.

**Comment by puneetlath** [comment]
@carlosmiceli I'll let you take CME on this one.

**Comment by puneetlath** [comment]
@dominictb has been paid. 

@fedirjh bump on the checklist for you.

**Comment by puneetlath** [comment]
Payment summary: 
- C - $250 - @dominictb - paid via Upwork
- C+ - 250 - @fedirjh - to be paid via NewDot

Thanks everyone!

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
