### ISSUE TITLE
[HOLD for payment 2024-08-07] [Upgrades] There is no transition animation when closing upgrade RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45689]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45131
## Action Performed:
1. Create a workspace
2. Navigate to workspace settings page
3. Click on More features > toggle Report fields
4. Click on back icon on RHP

## Expected Result:
There should be transition animation

## Actual Result:
There is no transition animation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5a03863d-1ee4-49e0-9f60-8d6c0227653a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by trjExpensify** [comment]
Definitely not backend, and I wouldn't block a deploy on this either personally. CC: @allroundexperts @garrettmknight @rushatgabhane

**Comment by thienlnam** [comment]
Small animation bug, not a blocker

**Comment by allroundexperts** [comment]
Draft PR up for the fix.

**Comment by madmax330** [comment]
Waiting on the PR

**Comment by allroundexperts** [comment]
> @allroundexperts bump on this one

This has been fixed in https://github.com/Expensify/App/pull/45730

**Comment by garrettmknight** [comment]
Closing - we'll settle payment as part of the larger project.
