### ISSUE TITLE
[$250] Android - Distance - Center button does not return to the current location (blue dot)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45693]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44752
## Action Performed:
1. Launch New Expensify app
2. Go to FAB > Submit expense > Distance
3. Swipe on the map to navigate away from the current location (blue dot)
4. Tap on the center button

## Expected Result:
Map will return to the current location (blue dot)

## Actual Result:
Center button does not return to the current location (blue dot)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b395dfa3-8d6a-44e5-ac31-5b9d4a984631

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0103b94842fb8e973f</li>
        <li>Upwork Job ID: 1814001263862473865</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by rlinoz** [comment]
This is an annoying one, can't repro on emulator but reproducible in a physical device.

**Comment by rlinoz** [comment]
Reverting https://github.com/Expensify/App/pull/44752 makes it work again.

**Comment by rlinoz** [comment]
Testing if reverting the PR works https://github.com/Expensify/App/pull/45707

**Comment by rlinoz** [comment]
Humm didn't fix the issue, let me add the help wanted label.

**Comment by rlinoz** [comment]
Oh it is probably this https://github.com/Expensify/App/pull/45575

**Comment by rlinoz** [comment]
Yeah, that is new

**Comment by thienlnam** [comment]
Removing the DeployBlocker label since it doesn't appear to be related to the API

**Comment by HaroonLiaqat** [comment]
GeoLoxation service if react native provides us the current location's longitude and latitude. We should store its value in a state variable. The map reference provides us a method to jump on a particular location. We can pass our current location to that method through ref if map

**Comment by HaroonLiaqat** [comment]
> GeoLoxation service if react native provides us the current location's longitude and latitude. We should store its value in a state variable. The map reference provides us a method to jump on a particular location. We can pass our current location to that method through ref if map

**Comment by HaroonLiaqat** [comment]
> > GeoLoxation service if react native provides us the current location's longitude and latitude. We should store its value in a state variable. The map reference provides us a method to jump on a particular location. We can pass our current location to that method through ref if map

Haroon Liaqat (react native developer)
Your Expensify account email: haroonliaqat.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01753b23816630ae84

**Comment by rlinoz** [comment]
Running a new build here https://github.com/Expensify/App/pull/45726 to check if reverting that PR fixes it.

**Comment by rlinoz** [comment]
Hmmm actually we cant click anything in that screen:

https://github.com/user-attachments/assets/931543e3-6f12-4205-86cf-e2ca00784e64

**Comment by rlinoz** [comment]
ok locally it looks like reverting the version of `react-native-pager-view` works https://github.com/Expensify/App/pull/45573, let me try a revert pr

**Comment by rlinoz** [comment]
Asked for CP here https://expensify.slack.com/archives/C07J32337/p1721401598214219
