### ISSUE TITLE
[HOLD for payment 2024-08-07] Free trial badge displayed in LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45700]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721304565430729

## Action Performed:

1. Create a new account and select Track and Budget Expenses onboarding task. 
2. This will result in a task for Track an expense. 
3. Create a new workspace.

## Expected Result:
 The task report in LHN should not show Free trial badge. The parent Concierge or Expensify chat should show the badge. 
## Actual Result:
Free trial badge displayed in LHN. when the onboarding chat is Concierge , the tasks created within the Concierge report (e.g. Track an Expense ) will also displays the Free trial badge.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (1)](https://github.com/user-attachments/assets/a6e4b48a-c333-40cc-8b67-bb60db7d6cd5)

https://github.com/user-attachments/assets/bc3c16cd-4dda-4cc4-8c82-405f538935d0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rojiphil** [comment]
@twisterdotcom I will raise a PR for this as mentioned in slack conversation [here](https://expensify.slack.com/archives/C049HHMV9SM/p1721304565430729)

**Comment by rojiphil** [comment]
> does this need a C+ review [@rojiphil](https://github.com/rojiphil) ? I was assigned to the PR

Well! Not sure since this is an easy fix. @mountiny Can you weigh in here?

**Comment by rojiphil** [comment]
@twisterdotcom Can we please process the payment here since the fix has been in production for 2 weeks as mentioned [here](https://github.com/Expensify/App/pull/45713#issuecomment-2244534983)

**Comment by twisterdotcom** [comment]
Payment Summary:

- @rojiphil paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/103436969) (C+)
