### ISSUE TITLE
[HOLD for payment 2024-08-09] [HOLD for payment 2024-08-07] [HelpDot] Restructure Connections Category on New Expensify

### ISSUE THREAD

**Issue by maddylewis** [Expensify/App#45716]
### Overview 
We're migrating export/sync integration errors to HelpDot, so we need to make some changes to the Integrations category so that the content is organized in a way that makes sense for the reader - https://github.com/Expensify/App/issues/45483

Let's structure New Expensify the same way!

### Reorganize Content
- All accounting integrations (in `Connections`) should have a nested subcategory 
- Each account integration will have the following articles:
     - `QuickBooks Online`
          - `Connect to QuickBooks Online`
          - Configure QuickBooks Online
          - QuickBooks Online Troubleshooting
     - `Xero`
          - Connect to Xero
          - Configure Xero
          - Xero Troubleshooting

- Move around the existing accounting integration content to:
     - Connect to X: Move existing `Set up QBO / Xero connection` article to this file
     - Configure X: Add `Coming Soon` placeholder
     - X Troubleshooting: Add `Coming Soon` placeholder

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
