### ISSUE TITLE
Search - Unable to download reports to CSV on native apps

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45714]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45642
## Action Performed:
1. Open the app
2. Log in with an account that has reporth on the Search - Shared tab
3. Navigate to Search - Shared
4. Long tap on a report
5. Tap on the "Select" button
6. Tap on the "Select all" checkbox
7. Tap on "X selected"

## Expected Result:
I should be able to download

## Actual Result:
Unable to download reports to CSV on native apps. It displays "No options available for the selected group of expenses."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ed584132-93fa-4846-ba89-73e7eed72219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rlinoz** [comment]
Forgot to add to testing notes, but download is not supported in native apps yet, we can close this one.
