### ISSUE TITLE
Android - Unable create expense by distance / scan tabs, buttons don't work

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#45724]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** y
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4738278
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch App and login
2. Tap Plus > Submit expense >Distance
3. Tap on Start/ Stop
4. Go to scan tab
5. Tap button

EXPECTED RESULT
## Expected Result:
Start stop button and "photo capture" button should work 

## Actual Result:
Nothing happens when tap on start/stop and scan button

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/84deb310-351f-4fc7-8eb6-50ef429ad73d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Being fixed as an Auth deploy

**Comment by luacmartins** [comment]
I think we can close this then?
