### ISSUE TITLE
[$125] Report fields - List values are no longer editable after the list field is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45721]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Report fields feature is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Click Type > Select List
5. Click List values
6. Add some list values
7. Click on the added list values
8. Note that the added list values can be edited
9. Save the list field
10. Click on the List field
11. Click List values
12. Click on the existing list values

## Expected Result:
The list values should be editable after the list field is created

## Actual Result:
The list values are no longer editable after the list field is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3b7f80e2-d787-42a4-9402-63a4d3ab5fe0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014156b3d6ec32273b</li>
        <li>Upwork Job ID: 1814428412549557169</li>
        <li>Last Price Increase: 2024-07-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment]
Checking whether this is already going to be fixed as part of the new feature release [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1721397400643669?thread_ts=1721148004.979399&cid=C06ML6X0W9L)

**Comment by mountiny** [comment]
I think we can handle this as a minor polish externally

@rushatgabhane @shubham1206agra mind checking out the proposals? thank you very much 🙇

**Comment by mountiny** [comment]
@waterim now I am not sure if we havent disallowed this on purpose if its not possible to do in OldDot. @dominictb can the list value name be edited in OldDot?

**Comment by mountiny** [comment]
Ok yeah that's what I was wondering, I think we can basically keep it this way for now, it would be a new feature to bring in editing of the list options so this is expected (for now)
