### ISSUE TITLE
[HOLD for payment 2024-07-26] mWeb - Workspace - With emoji as workspace description showing error while inviting members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45740]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4739026
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap profile - workspaces - new workspaces
3. Tap profile
4. Tap description
5. Remove the default description shown and enter 😀 and save it
6. Tap member and select a member
7. Tap invite

## Expected Result:
With emoji as workspace description must not show error while inviting members

## Actual Result:
With emoji as workspace description showing error while inviting members

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bc855511-0e78-459a-9cd8-25f8dd3972c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment]
It's from my PR. I'm fixing it [here](https://github.com/Expensify/App/pull/45745)

**Comment by trjExpensify** [comment]
Sourcing a C+ to review that now. (CC: @mountiny)

**Comment by trjExpensify** [comment]
PR is ready for internal review: https://github.com/Expensify/App/pull/45745
