### ISSUE TITLE
[Awaiting checklist] [$250] iOS - App crashes on open and signin

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45742]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721306503767519

## Action Performed:
1. Launch the app after update
2. Signin with valid credentials
## Expected Result:
Able to launch/signin without any issues
## Actual Result:
App crashes on open and after signin
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/7cee30df-53bb-49d0-9f0a-88bf6a9b837c" width="40%" height="40%">

https://github.com/user-attachments/assets/0f32d69d-e4ef-4869-80fa-ac140dc3f9ca

Cpu profile/trace:

{
    "key": "1721311628959",
    "time": "2024-07-18T14:07:08.959Z",
    "level": "DEBUG",
    "message": "[alrt] NewExpensify crash caught by error boundary - Cannot read property 'completeOnboarding' of null - {\"errorInfo\":\"{\\\"componentStack\\\":\\\"\\\\n    in HybridAppMiddleware\\\\n    in EnsureSingleNavigator\\\\n    in BaseNavigationContainer\\\\n    in ThemeProvider\\\\n    in NavigationContainerInner\\\\n    in NavigationRoot\\\\n    in DeeplinkWrapper\\\\n    in Expensify\\\\n    in withOnyx(Expensify)\\\\n    in Unknown\\\\n    in ColorSchemeWrapper\\\\n    in ErrorBoundary\\\\n    in BaseErrorBoundary\\\\n    in ErrorBoundary\\\\n    in SearchContextProvider\\\\n    in KeyboardControllerView\\\\n    in Unknown\\\\n    in AnimatedComponent(Component)\\\\n    in Unknown\\\\n    in KeyboardProvider\\\\n    in VideoPopoverMenuContextProvider\\\\n    in VolumeContextProvider\\\\n    in FullScreenContextProvider\\\\n    in PlaybackContextProvider\\\\n    in ReportIDsContextProvider\\\\n    in ActiveWorkspaceContextProvider\\\\n    in ActiveElementRoleProvider\\\\n    in CustomStatusBarAndBackgroundContextProvider\\\\n    in EnvironmentProvider\\\\n    in PickerStateProvider\\\\n    in ReportAttachmentsProvider\\\\n    in ScrollOffsetContextProvider\\\\n    in withOnyx(ScrollOffsetContextProvider)\\\\n    in Unknown\\\\n    in CurrentReportIDContextProvider\\\\n    in PopoverContextProvider\\\\n    in KeyboardStateProvider\\\\n    in WindowDimensionsProvider\\\\n    in RenderersPropsProvider\\\\n    in ListStyleSpecsProvider\\\\n    in SharedPropsProvider\\\\n    in RenderRegistryProvider\\\\n    in RenderHTMLConfigProvider\\\\n    in TRenderEngineProvider\\\\n    in BaseHTMLEngineProvider\\\\n    in HTMLEngineProvider\\\\n    in LocaleContextProvider\\\\n    in withOnyx(LocaleContextProvider)\\\\n    in Unknown\\\\n    in WithCurrentUserPersonalDetails(Component)\\\\n    in RNCSafeAreaView\\\\n    in Unknown\\\\n    in SafeArea\\\\n    in PortalProviderComponent\\\\n    in RNCSafeAreaProvider\\\\n    in SafeAreaProvider\\\\n    in ThemeIllustrationsProvider\\\\n    in ThemeStylesProvider\\\\n    in ThemeProvider\\\\n    in AccountProvider\\\\n    in withOnyx(AccountProvider)\\\\n    in Unknown\\\\n    in SessionProvider\\\\n    in withOnyx(SessionProvider)\\\\n    in Unknown\\\\n    in Nvp_expensify_preferredEmojiSkinToneProvider\\\\n    in withOnyx(Nvp_expensify_preferredEmojiSkinToneProvider)\\\\n    in Unknown\\\\n    in Nvp_expensify_frequentlyUsedEmojisProvider\\\\n    in withOnyx(Nvp_expensify_frequentlyUsedEmojisProvider)\\\\n    in Unknown\\\\n    in PreferredThemeProvider\\\\n    in withOnyx(PreferredThemeProvider)\\\\n    in Unknown\\\\n    in ReportDraftComment_Provider\\\\n    in withOnyx(ReportDraftComment_Provider)\\\\n    in Unknown\\\\n    in BetasProvider\\\\n    in withOnyx(BetasProvider)\\\\n    in Unknown\\\\n    in Nvp_private_blockedFromConciergeProvider\\\\n    in withOnyx(Nvp_private_blockedFromConciergeProvider)\\\\n    in Unknown\\\\n    in CurrentDateProvider\\\\n    in withOnyx(CurrentDateProvider)\\\\n    in Unknown\\\\n    in ReportActionsDrafts_Provider\\\\n    in withOnyx(ReportActionsDrafts_Provider)\\\\n    in Unknown\\\\n    in PersonalDetailsListProvider\\\\n    in withOnyx(PersonalDetailsListProvider)\\\\n    in Unknown\\\\n    in NetworkProvider\\\\n    in withOnyx(NetworkProvider)\\\\n    in Unknown\\\\n    in ComposeProviders\\\\n    in OnyxProvider\\\\n    in ComposeProviders\\\\n    in RCTView\\\\n    in Unknown\\\\n    in GestureHandlerRootView\\\\n    in InitialURLContextProvider\\\\n    in App\\\\n    in RCTView\\\\n    in Unknown\\\\n    in RCTView\\\\n    in Unknown\\\\n    in AppContainer\\\"}\"}"
  },

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a16cdc256e8dc37</li>
        <li>Upwork Job ID: 1814255257891977452</li>
        <li>Last Price Increase: 2024-07-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by mountiny** [comment]
cc @mateuuszzzzz

**Comment by mountiny** [comment]
I have raised a quick PR, the [commit](https://github.com/Expensify/App/pull/45757/commits/acc94de393ed44c69c8a37472c5a684fb189bdf4) was raised before seeing the proposal.

Running a build to see if it will fix it for those experiencing this issue

**Comment by mountiny** [comment]
$250 to @suneox for checklist and testing

**Comment by twisterdotcom** [comment]
Payment Summary:

- @suneox paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/103280282) (C+)

Waiting on the checklist still @suneox

**Comment by twisterdotcom** [comment]
All paid out.
