### ISSUE TITLE
Chat - User B can not put expense on hold when it has "Duplicate" status

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45741]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+vd_071824@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45325
## Action Performed:
Pre-requisite: as User B, create a Workspace and invite user A
1. As user A, submit 3 expenses to the Workspace with the same amount and merchant, so it appear as duplicate
2. As user B, go to the workspace chat and select one of the duplicate expenses
3. Click on the header

## Expected Result:
Hold option should be available when the expense has "Duplicate" status

## Actual Result:
Hold option is not shown until the user first resolve the duplicates

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/eb8df01c-7589-479c-90f8-c009ab395dd1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by jliexpensify** [comment]
Hi @pecanoro @DylanDylann - it looks like this might be related to https://github.com/Expensify/App/pull/45325, if you could have a look?

**Comment by bernhardoj** [comment]
From https://github.com/Expensify/App/issues/44892, if it's duplicate, we don't want to show the Unhold option. (Unhold option is previously shown for duplicate expense)

**Comment by pecanoro** [comment]
If the expense is a duplicate, it is already on HOLD so there is no point in holding it again. I think this is working as expected.
