### ISSUE TITLE
[HOLD for payment 2024-08-01] [$125] [HIGH] [API Reliability] Opening the Wallet page calls the OpenPaymentsPage twice 

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45754]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1721384323190839

## Action Performed:
Break down in numbered steps

1. Open Console > Networks tab
2. Open Profile
3. Open the Wallet page

## Expected Result:
Describe what you think should've happened

The OpenPaymentsPage read call is made only once

## Actual Result:
Describe what actually happened

The API was called twice

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c4debdbfd2eca47</li>
        <li>Upwork Job ID: 1814254841623728799</li>
        <li>Last Price Increase: 2024-07-19</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 103183901</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by mountiny** [comment]
This is a simple change, @nyomanjyotisa proposal is looking good, assigning

**Comment by mountiny** [comment]
@nyomanjyotisa what is your ETA for the PR?

**Comment by mallenexpensify** [comment]
Contributor: @nyomanjyotisa  paid $125 via Upwork
Contributor+: @thesahindia owed $125 via NewDot

@thesahindia plz complete the BZ checklist above.

**Comment by mallenexpensify** [comment]
@thesahindia if you propose we don't want a regression test case, can you provide reasoning why you think we don't need one?  For this, I'm assuming it's because `The OpenPaymentsPage read call is made only once` is more of a backend thing that just needed to be updated and checking for that each time isn't necessary.

**Comment by JmillsExpensify** [comment]
$125 approved for @thesahindia
