### ISSUE TITLE
[$125] Accounting - Expanded "Other integrations" is collapsed when Card reconciliation opens

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45775]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is connected to any integration
1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting
3. Expand "Other integrations"
4. Click Import, Export and Advanced
5. Note that "Other integrations" remains expanded
6. Click Card reconciliation

## Expected Result:
"Other integrations" will remain expanded

## Actual Result:
Expanded "Other integrations" is collapsed when clicking on Card reconciliation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/431b1e04-f33f-4116-b984-52ca449b56ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015468829bd2d9ddb4</li>
        <li>Upwork Job ID: 1815529915004927480</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by sakluger** [comment]
This seems like it could be fairly trivial to fix, so I'm going to reduce the price for now. If it ends up being more complicated, let me know and we can consider the price again.

**Comment by sakluger** [comment]
@alitoshmatov - what do you think about the bounty? Defining unique routes is more work, but still doesn't seem super complex, so I'd like to hear your perspective.

**Comment by sakluger** [comment]
Commenting again for melvin.

**Comment by alitoshmatov** [comment]
I was not able to reproduce this issue. Is there any additional steps required? 

@sakluger Are you able to reproduce this issue consistently?

https://github.com/user-attachments/assets/bcb03978-adac-4d23-987b-20c4f003364b

**Comment by sakluger** [comment]
I also can't reproduce this behavior anymore, I think we can close the GH issue for now. @lanitochka17 please reopen if you experience this issue again.

![Accounting - Other Integrations](https://github.com/user-attachments/assets/f8c13a7a-65f0-48fc-8e34-ac5949d3c2d0)
