### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Accounting - Last synced time doesn't reflect the correct time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.9-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Establish a connection with Xero
4. Wait for a few minutes and refresh the page to update the latest synced time
5. Click on three dot and click on sync now

## Expected Result:
The last synced time updates

## Actual Result:
The last synced time shows stale data

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c0b8a6a6-d052-4ca9-b1b4-fe0d26fd8895

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117d6782d3d2e2e77</li>
        <li>Upwork Job ID: 1815273731940343516</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103311561</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by VictoriaExpensify** [comment]
I wasn't able to view your video past 2 seconds @lanitochka17 , but your Action Performed was clear and I've been able to reproduce the issue

![2024-07-22_16-30-06 (1)](https://github.com/user-attachments/assets/be772060-5145-4b05-929d-85e863ba0701)

Agree this is Wave_Collect

**Comment by eh2077** [comment]
@nyomanjyotisa I don't think it's a good idea to set optimistic `successfulDate` here. The last synced time should be only determined if the sync job is done.

---

@daledah 's [proposal](https://github.com/Expensify/App/issues/45780#issuecomment-2242310276) looks good to me - We should take `connectionSyncProgress` into consideration in method `getIntegrationLastSuccessfulDate`

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment]
Waiting for @deetergp 's review

**Comment by deetergp** [comment]
@daledah's solution sounds good to me! 🚀

**Comment by VictoriaExpensify** [comment]
Payment Summary:
Contributor: @eh2077 paid $250 via Upwork

@daledah - please [accept the Upwork offer ](https://www.upwork.com/ab/applicants/1815273731940343516/offers)so I can process your payment

**Comment by VictoriaExpensify** [comment]
**Payment summary:**
**Contributor:** @daledah paid $250 via [Upwork](https://www.upwork.com/ab/applicants/1815273731940343516/job-details)

**Comment by VictoriaExpensify** [comment]
@eh2077 can you please [finish the checklist](https://github.com/Expensify/App/issues/45780#issuecomment-2274414383) so I can close the issue out? Thank you!

**Comment by eh2077** [comment]
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/43661
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/43661/files#r1721963372
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. Yes

#### Regression test

1. Create a workspace
2. Establish a connection with Xero
3. Wait for a few minutes and refresh the page to update the latest synced time
4. Click on three dot and click on sync now
5. Verify that: The last synced time updates

Do you agree 👍  or 👎

cc @VictoriaExpensify

**Comment by VictoriaExpensify** [comment]
Request to add this to Test Rail - https://github.com/Expensify/Expensify/issues/421594
