### ISSUE TITLE
[Fullstory] SignUpUser does not return userMetadata

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#45788]
When an existing user signs in, the API command `SignInUser` is called. It returns `userMetadata` in its response which is then saved to onyx and used by fullstory. Without `userMetadata`, the user is anonymous on fullstory.

### Problem  

Fullstory has anonymous data 

- [x] When a new user signs up, the API command `SignUpUser` is called. It does NOT return `userMetadata`. 
- [x] When a user from oldDot is brought to newDot, the API command `SignInWithShortLivedAuthToken` is called. It does not return `userMetadata`.  eg: Support > Concierge

### Solution

- [x] We’ll need to complete [this section](https://docs.google.com/document/d/1cm0uDmMmRVsShFdz4dLkijmYHOeg0XZ8EfpHd8WVYUA/edit#bookmark=id.80pbb0a2zxve) of doc for `SignUpUser` command too ([google doc](https://docs.google.com/document/d/1cm0uDmMmRVsShFdz4dLkijmYHOeg0XZ8EfpHd8WVYUA/edit#bookmark=id.80pbb0a2zxve)).
- [x] We’ll need to complete [this section](https://docs.google.com/document/d/1cm0uDmMmRVsShFdz4dLkijmYHOeg0XZ8EfpHd8WVYUA/edit#bookmark=id.80pbb0a2zxve) of doc for `SignInWithShortLivedAuthToken` command too ([google doc](https://docs.google.com/document/d/1cm0uDmMmRVsShFdz4dLkijmYHOeg0XZ8EfpHd8WVYUA/edit#bookmark=id.80pbb0a2zxve)).

**Comment by anmurali** [comment]
The problem is also present when the user is brought into New Dot in signed -in state (e.g. on classic, if I go to Support - Concierge, it brings me into ND in signed in state and I don't see the `userMetadata` onyx data)

**Comment by rushatgabhane** [comment]
> The problem is also present when the user is brought into New Dot in signed -in state (e.g. on classic, if I go to Support - Concierge,

added it in issue

**Comment by kadiealexander** [comment]
Not overdue.

**Comment by mountiny** [comment]
I have got one PR for the `SignInUser` case up, there are some flakey tests

For the `SignInWithShortLivedAuthToken` its using a `CreateLogin` auth command, which is not returning the userMetadata yet so we need to first return that from Auth

**Comment by anmurali** [comment]
@mountiny thank you for prioritizing this. I was blocked on scheduling our onboarding till we fix these two things cause otherwise none of the legit accounts will have metadata for a very long time. Sign up + infinite sessions = no metadata till they are forced to sign in at some point.

**Comment by mountiny** [comment]
No problem, seems like it should be quite quick so given Tom explained to me this is blocking us from actually starting using FullStory happy to help while Daniel is out

**Comment by anmurali** [comment]
>I have got one PR for the SignInUser case up, there are some flakey tests

You mean `SignUpUser` I think?

**Comment by rushatgabhane** [comment]
sign IN is correct

**Comment by mountiny** [comment]
SignUp, yes, the signIn already works

**Comment by mountiny** [comment]
I have got Auth PR up to add the user metdata to the resposne of CreateLogin which we need for the SignInWithShortLivedAuthToken

**Comment by trjExpensify** [comment]
Niceee, thanks Vit! So the Auth deploy should go out tonight on PST with Carlos as the auth deployer this week. Then we can merge the Web PR to have it go out tomorrow GST with Maria as the web deployer this week.

**Comment by mountiny** [comment]
Yeah that sounds good to me

**Comment by mountiny** [comment]
I believe this is done now
