### ISSUE TITLE
[LOW] [Performance] Improve Crashlytics reports with more breadcrumbs

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45791]
### Problem
Recently our team has been investigating crashes reported in Firebase Crashlytics, but the crash reports lack detailed information, such as user actions. This lack of context makes it difficult to identify and fix the root causes, turning the debugging process into a trial-and-error exercise that is inefficient and time-consuming.

### Solution
To enhance our understanding of these crashes, we propose implementing Crashlytics logging within the app navigation and during user interactions across critical processes. By doing so, we can capture a sequence of user interactions leading up to a crash, providing valuable insights into potential causes.

Navigation logs should contain:
- time of the log
- name of the screen
- params passed to the screen

User interaction logs should contain:
- time of the interaction
- name of the interaction

By implementing it, we aim to gain a view of user interactions within the app. This additional context will significantly aid in diagnosing and fixing crashes, ultimately improving app stability.

Attaching a screenshot of how crash logs could possibly look like in a Firebase panel.

**Comment by mountiny** [comment]
@TMisiukiewicz cc

**Comment by mountiny** [comment]
I guess this is all done now with the PR merged and deployed @TMisiukiewicz correct me if I am wrong

**Comment by TMisiukiewicz** [comment]
@mountiny that is correct, all done here
