### ISSUE TITLE
[HOLD for payment 2024-08-01] [Free trial] Free trial badge or banner not showing when a trial starts

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#45796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.10-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** na
**Email or phone of affected tester (no customers):** jdndjlndjlndjl@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** na
**Issue reported by:** mitch@expensify.com
**Slack conversation:** Internal https://expensify.slack.com/archives/C036QM0SLJK/p1721417971858779?thread_ts=1721340474.948589&cid=C036QM0SLJK

## Action Performed:
1. Sign up with a brand new account on new.expensify.com
2. Create a workspace ("Manage my team's expenses" in the onboarding flow is one option to do this)
3. Submit an expense to that workspace (I.e. Take a billable action)

## Expected Result:
- A free trial badge "Free trial: 7 days left" should show in the chat row in left hand navigation (Either Concierge or Expensify depending where your setup checklist was sent)
- The banner in your Payment section of the Subscription tab should reflect being in an active trial telling you how many days you have left.

## Actual Result:
- No free trial badge in left hand nav
- Banner on the Payment section of Subscription does not reflect an active free trial 

## Workaround:
Rely on the "Your trial has started message" 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d6bece53-a692-4241-89f8-59a124561f92

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by chiragsalian** [comment]
Skipping BugZero Checklist (i checked them all) because its a new feature and the bug was overlooked during first review and testing but was identified later during more manual testing of the feature. No new test needs nor a discussion needs to be added for it IMO.

No payment either since i pushed the PR.  But if you need to pay me that's welcome too 😛
