### ISSUE TITLE
[$4000] Implementing NetSuite Integration in NewDot (mananjadhav)

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#45805]
This is the bulk amount for the implementation of the project for @mananjadhav's contribution to https://github.com/Expensify/Expensify/issues/377671

Amount: $4000

Link to last PR: https://github.com/Expensify/App/pull/44743

cc @zsgreenwald

**Comment by JmillsExpensify** [comment]
$4000 approved for @mananjadhav
