### ISSUE TITLE
[$4000] Implementing NetSuite Integration in NewDot (shubham1206agra)

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#45806]
This is the bulk amount for the implementation of the project for @shubham1206agra's contribution to https://github.com/Expensify/Expensify/issues/377671

Amount: $4000

Link to last PR: https://github.com/Expensify/App/pull/44159

cc @zsgreenwald

**Comment by JmillsExpensify** [comment]
$4000 approved for @shubham1206agra
