### ISSUE TITLE
[HIGH] SearchForReports requests are not cancelled when new request is made

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45803]
### Problem

When we search for reports in the chat finder page or in the money request flows, we debouncing the search as users type, but we do not cancel the previous search API requests. There is no reason to wait for those, as we have a newer query to search for.

### Solution

Search all the previous requests in the queue when a new search query is added.

@rinej

**Comment by mountiny** [comment]
PR was raised and merged, just adding this issue for posteriority.

@rinej is there more to follow up/ clean up in this logic? Is this applied to all the money request flows etc where we are calling the search for reports too?

**Comment by roryabraham** [comment]
> PR was raised and merged, just adding this issue for posteriority.

Cool cool, I was thinking I had deja-vu looking at the issue description

**Comment by adhorodyski** [comment]
Hey, as @rinej is on 🏝️ OOO I'll make sure to have someone from our team to take over this in case there's any other action required here:)

**Comment by roryabraham** [comment]
This is done, no payments due
