### ISSUE TITLE
[HOLD for payment 2024-08-02] Dupe detection - Green Confirm button is shorter in width

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45815]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two same expenses (same amount and merchant)
4. Go to transactiont thread of any expense
5. Click Review duplicates
6. Click Keep this one
7. Proceed to confirmation page

## Expected Result:
The green Confirm button will have the same size as other green buttons across the app

## Actual Result:
The green Confirm button is shorter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/818768b2-eebe-4746-86ec-052f64abcbbe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mountiny** [comment]
Dupe detection is behind beta so we can remove the blocker

cc @kubabutkiewicz @pecanoro @parasharrajat

**Comment by kubabutkiewicz** [comment]
Hi, I will create PR soon to fix that issue @mountiny @pecanoro @parasharrajat

**Comment by pecanoro** [comment]
@hayata-suenaga I am reassigning the issue to myself so I can review and track the fixes since this is for the duplicate detection project that I am handling.

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @parasharrajat for PR review and testing. This is a new feature and we already have an issue to add tests centrally. @parasharrajat please submit a request on New Expensify when you have a chance.

**Comment by garrettmknight** [comment]
$250 approved for @parasharrajat

**Comment by JmillsExpensify** [comment]
Thanks, moving forward with the payment.
