### ISSUE TITLE
[HOLD for payment 2024-08-01] Thread - Error shows up when user sends a message after leaving the thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message
4. Right click on the message > Reply in thread
5. Send a reply in thread
6. Click on the chat header
7. Click Leave
8. Send a message

## Expected Result:
User will be able to send a message

## Actual Result:
Error "You don't have access to this chat room." shows up when user sends a message after leaving the thread.
You don't have access to this chat room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/52a05ac4-dbfb-4aa1-8c98-6997df66eb3a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment]
In production you are not able to leave the thread from the RHP 
<img width="687" alt="image" src="https://github.com/user-attachments/assets/7a7c3516-a4b0-419e-9a5f-f1e4170d01b1">

**Comment by mountiny** [comment]
cc @bernhardoj I think this is coming from your PR https://github.com/Expensify/App/pull/45136 @akinwale 

I believe user has to be navigated to the parent chat when they leave a thread, so that they have to join it again by OpenReport when they want to post new messages

**Comment by mountiny** [comment]
And it seems like its a combination with https://github.com/Expensify/App/pull/45370 cc @dominictb @thesahindia

**Comment by francoisl** [comment]
This is also fixed by reverting https://github.com/Expensify/App/pull/45370 for me locally.
