### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250] Dupe detect - Distance field is not disabled and not here page opens after changing distance

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45833]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.10-2
**Reproducible in staging ?:** Y
**Reproducible in production?:** No new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two same distance expenses (same distance).
4. Go to transactiont thread of any expense.
5. Click Review duplicates.
6. Click Keep this one.
7. Proceed to confirmation page.
8. Click on the distance field.
9. Change the distance.
10. Click Confirm.

## Expected Result:
In Step 8, distance field should be disabled.

## Actual Result:
In Step 8, distance field is not disabled.
After changing the distance and confirming it, app opens not here page (Step 10).
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/230a0043-2ce7-4bc6-9707-7deb03606442

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184066b98a5cfeddb</li>
        <li>Upwork Job ID: 1814753910382559620</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103200665</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by mountiny** [comment]
cc @pecanoro @JmillsExpensify @parasharrajat

**Comment by mountiny** [comment]
Making it external for half price as it seems quite niche

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance field is not disabled and not here page opens after changing distance
### What is the root cause of that problem?
We are not checking readonly here
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/components/ReportActionItem/MoneyRequestView.tsx#L318-L322
and here
https://github.com/Expensify/App/blob/fa738c641e7d2b289850da7b4be11369c33b96d6/src/components/ReportActionItem/MoneyRequestView.tsx#L345-L348
### What changes do you think we should make in order to solve the problem?
we should pass 
```
 interactive={canEditDistance && !readonly}
 ````

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
@parasharrajat since this is coming from PR you have reviewed, I think you are welcome to raise a fix

**Comment by mountiny** [comment]
@parasharrajat will you be able to raise a PR Monday morning latest? Thanks!

**Comment by mountiny** [comment]
Dupe detection is behind beta so we can remove the blocker

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: This was not a bug introduced by a PR. It was known when working on the previous PR which did not include these changes. 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Go to a workspace chat
2. Submit two identical distance requests (identical waypoints) to this workspace chat.
3. Notice the review duplicate button pops up.
4. Click `Review Duplicate`.
5. Click `Keep this one` for any one transaction on the review page.
6. Go through the flow till Confirm page.
7. Click `Distance` field on Confirm page.
8. Verify that the `Distance` field is not editable and no edit page opens up.

**Comment by mountiny** [comment]
I believe the summary is to $250 to @parasharrajat and to @c3024

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor: @c3024 paid $250 via Upwork

Contributor+: @parasharrajat due $250 via NewDot

Upwork job [here](https://www.upwork.com/nx/wm/workroom/37873354/overview)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
