### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Expense - Description row in transaction thread is empty after saving the description

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45830]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Go to transaction thread.
5. Click Description.
6. Enter description and save it.

## Expected Result:
The saved description will appear on Description row in transaction thread.

## Actual Result:
The Description row in transaction thread is empty after saving the description.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a93a5353-4ee7-402a-b516-15b5b901c7f1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f38e792188ee307</li>
        <li>Upwork Job ID: 1815419992762713976</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by mountiny** [comment]
cc @pecanoro @JmillsExpensify @parasharrajat

This is also coming from the dupe detection PR

**Comment by mountiny** [comment]
@parasharrajat I have raised a quick PR and assigned you as its coming from the dupe detection PR

**Comment by mountiny** [comment]
@Krishna2323 I will offer you a partial reward for help spotting it.

Please remember that for any issues that are deploy blockers, always link the offending PR in your proposal. In this case it was super simple to find. Thanks!

**Comment by mountiny** [comment]
@dominictb can you please raise the PR?

**Comment by mallenexpensify** [comment]
@dominictb can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~019f38e792188ee307

**Comment by mallenexpensify** [comment]
@johncschuster I'm off til Monday afternoon, can you help with payment here? Thx

**Comment by johncschuster** [comment]
# Payment Summary
Reviewer: @parasharrajat owed $250 via NewDot - please request payment
Contributor: @dominictb paid $250 via [Upwork](https://www.upwork.com/jobs/~019f38e792188ee307) - PAID 👍

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
