### ISSUE TITLE
Search - Hold option is missing from the dropdown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45837]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45712
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Manual
3. Submit a manual expense to any user
4. Go to Search
5. Click on the checkbox of the same transaction in Step 3
6. Click on the dropdown

## Expected Result:
There will be Hold option

## Actual Result:
Hold option is missing from the dropdown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/df3382ef-1b0a-473a-94e1-05f6caf44a20

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by alexpensify** [comment]
This was assigned over the weekend. I'll review it soon. Also, thanks @gijoe0295 for the feedback!

**Comment by alexpensify** [comment]
On my review list, I'll get to it soon.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience mentioned here. 

![2024-07-29_12-26-41](https://github.com/user-attachments/assets/d5c667bd-2b17-4c92-afa1-f309c4e9943d)
