### ISSUE TITLE
[Awaiting Payment Request] [$125] Dupe detection -Not here page opens after navigating to confirm page by link and confirming it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45832]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two same expenses (same amount and merchant)
4. Go to transactiont thread of any expense
5. Click Review duplicates
6. Click Keep this one (any)
7. Proceed to confirmation page
8. Copy the link to confirmation page
9. Go to Account settings > Troubleshoot > Clear cache and restart > Reset and refresh
10. Navigate to the confirmation page via link
11. Click Confirm

## Expected Result:
After confirming the review, app will open the transaction thread

## Actual Result:
After confirming the review, app redirects to not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a0d29c11-ec24-40be-ba30-cc8d4d490a69

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01156fb1121250d6e8</li>
        <li>Upwork Job ID: 1814753798615808236</li>
        <li>Last Price Increase: 2024-07-20</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103215058</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by mountiny** [comment]
cc @pecanoro @JmillsExpensify @parasharrajat

**Comment by mountiny** [comment]
Made this external for half price as it seems like a quick fix

**Comment by mountiny** [comment]
Dupe detection is behind beta so we can remove the blocker

**Comment by Julesssss** [comment]
I'm slightly confused by [this](https://github.com/Expensify/App/issues/45832#issuecomment-2242487761) 'fixed' video, as it shows the link redirecting to not here page. 

Did I misunderstand the point of that capture?

**Comment by Julesssss** [comment]
Ah thanks, yeah it makes sense to me now.

**Comment by garrettmknight** [comment]
**Payment Summary:**

- Contributor: @dominictb $125 paid via upwork
- Reviewer: @parasharrajat $125

**Comment by garrettmknight** [comment]
@parasharrajat can you finish the checklist when you get the chance?

**Comment by garrettmknight** [comment]
QA is up - just waiting on payment request for @parasharrajat

**Comment by JmillsExpensify** [comment]
$125 approved for @parasharrajat
