### ISSUE TITLE
[$250] Dupe detect - Confirmation page with empty data opens when opening invalid dupe confirm link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45835]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two same expenses (same distance)
4. Go to transactiont thread of any expense
5. Click Review duplicates
6. Click Keep this one
7. Proceed to confirmation page
8. Copy the link
9. Modify the report ID in the link and navigate to it
10. Click Confirm

## Expected Result:
In Step 9, app should open not here RHP when navigating to dupe review confirmation page of invalid report

## Actual Result:
In Step 9, app opens confirmation page with empty data when navigating to invalid dupe confirmation link
In Step 10, when clicking Confirm, not here page opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e8d52251-f192-4709-96f9-c21211cabbe1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01437c46405734d3fc</li>
        <li>Upwork Job ID: 1815459015971079692</li>
        <li>Last Price Increase: 2024-07-22</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 103220593</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment]
cc @pecanoro @JmillsExpensify @parasharrajat

**Comment by mountiny** [comment]
The proposal seems quite straightforward, @parasharrajat should we go with it?

**Comment by mountiny** [comment]
Dupe detection is behind beta so we can remove the blocker

**Comment by mountiny** [comment]
@parasharrajat Thanks! I was not aware this is behind beta, since it is, we do not have to treat these as blockers which helps

**Comment by puneetlath** [comment]
Payment summary: 
- C - $250 - @gijoe0295 - paid via Upwork
- C+ - 250 - @parasharrajat - to be paid via NewDot

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
