### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250] Sage Intacct - Workspace in "Reuse existing connection" list has different workspace avatar color

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45848]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has a few workspaces.
- One of the workspaces is connected to Sage Intacct.
- The workspace which is connected to Sage Intacct has default workspace avatar.

1. Go to staging.new.expensify.com
2. Go to another workspace that is not connected to Sage Intacct.
3. Go to Accounting.
4. Tap Connect next to Sage Intacct.
5. Select Reuse existing connection.

## Expected Result:
The workspace in "Reuse existing connection" list will have the correct workspace avatar with background color.

## Actual Result:
The workspace in "Reuse existing connection" list has different workspace avatar compared to the actual workspace avatar with always blue background color surrounding the letter "A".

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6548213_1721495024784!Screenshot_2024-07-21_at_01 00 17](https://github.com/user-attachments/assets/3afc717d-49e1-4aa9-967d-5f497f8f8186)

https://github.com/user-attachments/assets/dbb7c2fa-7cf3-479c-87f8-360311b9bc45

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140511183d3b4ac7e</li>
        <li>Upwork Job ID: 1815697022094043995</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103247884</li>
<li>gijoe0295 | Contributor | 103247885</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by m-natarajan** [comment]
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #vip-vsb

**Comment by bfitzexpensify** [comment]
Hey @gijoe0295 - are you seeing anything strange with the contract on your end? When I attempt to close and pay it out, I am seeing this error:

<img width="1595" alt="image" src="https://github.com/user-attachments/assets/90b79ba6-8de4-456f-bb5d-fca0937fc29d">

**Comment by bfitzexpensify** [comment]
Great, thanks for confirming. @ishpaul777 if you can get the BZ checklist complete I'll finalise the C+ payout too

**Comment by bfitzexpensify** [comment]
Thanks @ishpaul777 - offer sent.

**Comment by bfitzexpensify** [comment]
Great - all paid out. Thanks everyone!
