### ISSUE TITLE
[$250] Key navigation - Onboarding task can be dismissed after going to search dialog

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45844]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a new account
2. On the Onboarding task Press CMD+K (CTRL+K for Windows) to open the search page.
3. Go to Self DM
Notice onboarding task is dismissed

## Expected Result:
Onboarding task is not dismissed

## Actual Result:
Onboarding task is dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/57fb7900-7dc7-4207-9002-5fc2986801e4

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eeceae077853a6ac</li>
        <li>Upwork Job ID: 1815388558136149880</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to vip-vsp

**Comment by hungvu193** [comment]
🎀 👀 🎀

**Comment by hungvu193** [comment]
@Krishna2323 's [proposal](https://github.com/Expensify/App/issues/45844#issuecomment-2241531395) looks good. But I'm not sure if we want to fix this bug.

**Comment by hungvu193** [comment]
Oh thanks. That's good to know 👍

**Comment by hungvu193** [comment]
little bump @youssef-lr for the above discussion 🍵

**Comment by hungvu193** [comment]
little bump @youssef-lr, this one will need your attention 🙇

**Comment by youssef-lr** [comment]
I think we can close this in favor of this issue which is intended to find a general solution for this https://github.com/Expensify/App/issues/44401
