### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Incorrect report action message when changing the "Reimbursable"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45841]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721309857362059

## Action Performed:
1. Submit an expense to approver
2. As approver, login to OldDot
3. Open the submitted report
4. change the reimbursable to non reimbursable expense by checking off the box
5. Go to NewDot and open the report
## Expected Result:
Report action should be related to changing `Reimbursable`
## Actual Result:
"Changed Expense" report action appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (7)](https://github.com/user-attachments/assets/b94fcb09-fff1-448d-8a02-98721e941d45)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/57901a53-4d34-4f3a-888e-f102ab71fe37

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c572749229de53f</li>
        <li>Upwork Job ID: 1815864020389627404</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by hungvu193** [comment]
@gijoe0295 's [proposal](https://github.com/Expensify/App/issues/45841#issuecomment-2241286711) looks straight forward to me.
🎀 👀 🎀  C+ reviewed

**Comment by Beamanator** [comment]
Love the solution, except `changed the expense to "false" (previously "true")` doesn't really make sense in this case. Let's go with `changed the expense's reimbursable state to "false" (previously "true")`

**Comment by Beamanator** [comment]
@shawnborton mind confirming my proposed copy [here](https://github.com/Expensify/App/issues/45841#issuecomment-2248788433), for this case? This is when we're changing an expense's reimbursable state / status in OldDot

**Comment by shawnborton** [comment]
Hmm I think it would be more clear if it said something like:

> changed the expense's reimbursable state to reimbursable (previously non-reimbursable)

The true/false just feels slightly jargony and maybe we don't want to expose the user to that?

cc @Expensify/design @trjExpensify for any copy suggestions here though. Also, we should get @Expensify/marketing to have a look since they are the ones that handle copy requests like this.

**Comment by dannymcclain** [comment]
>The true/false just feels slightly jargony and maybe we don't want to expose the user to that?

I tend to agree here. I think your suggestion is a bit more understandable for everyone.

>Also, we should get @Expensify/marketing to have a look since they are the ones that handle copy requests like this.

+1

**Comment by hungvu193** [comment]
> Do we need to mention a specific marketing member?

Please go ahead and create the PR, we can confirm this later

**Comment by trjExpensify** [comment]
Yep, that would fit with the structure we have. I don't think we need to include "the expense's" as it's a message on the expense in question already. Another small change is that we use quotation marks with the others. So that would give us:

>changed the reimbursable state to "reimbursable" (previously "non-reimbursable"). 

Ref point from prod:

<img width="604" alt="image" src="https://github.com/user-attachments/assets/e522a9f4-a6a7-4943-8212-4addde329594">

Another option is to just refer to the whole expense instead of the "reimbursable state" which feels maybe a bit simpler:

>changed the expense to "reimbursable" (previously "non-reimbursable"). 

_____
As it came to mind...

Right now, this is an action that can only be taken on OldDot. We don't have the toggle on NewDot for reimbursability. But when we do... is it going to be "Out-of-pocket"? If so, then we'd find ourselves with something like the below making more sense:

>changed the expense to "out-of-pocket" (previously "company spend").

.. but maybe we don't need to worry about that for now until we commit to building that feature. On OldDot today, you're toggling "reimbursable", so this action makes sense if you do happen to see it in NewDot. CC: @JmillsExpensify

**Comment by jamesdeanexpensify** [comment]
I've suggested in other areas to actually start changing the order of these to a more chronological one, like:

> changed the expense from "non-reimbursable" to "reimbursable"

Are we OK doing that here, too?

**Comment by trjExpensify** [comment]
>I've suggested in other areas to actually start changing the order of these to a more chronological one, like:

Is there somewhere a change like that would be implemented uniformly? Not against it, but we shouldn't have a mixture in play. I.e 

>changed the merchant to "Tesco" (previously "Sainsburys").
>changed the expense from "non-reimbursable" to "reimbursable"

**Comment by Beamanator** [comment]
> Is there somewhere a change like that would be implemented uniformly?

We could analyze all the report actions that show the opposite way & implement the switch all in 1 go, but it's not as easy as flipping a little switch sadly 🤷

**Comment by trjExpensify** [comment]
Right, so I'm inclined to say we focus on adding this one here in the current structure that matches prod: 

>changed the expense to "reimbursable" (previously "non-reimbursable").

... and then if we want to do a wider refactor uniformly, someone can take that on to provide copy and updates to all report actions in that style.

**Comment by Beamanator** [comment]
That makes sense to me 👍

**Comment by jamesdeanexpensify** [comment]
Sounds good!

**Comment by adelekennedy** [comment]
Payment due tomorrow - @hungvu193 any need for a regressions test here?

**Comment by hungvu193** [comment]
**Regression test:**
1. Submit an expense to approver.
2. As approver, login to OldDot.
3. Open the submitted report.
4. Change the reimbursable to non-reimbursable expense by checking off the box.
5. Go to NewDot and open the report.
6. Verify that the expense message is `changed the expense to "non-reimbursable" (previously "reimbursable")`

Do we 👍  or  👎  ?

**Comment by adelekennedy** [comment]
@gijoe0295 will you just confirm your Upwork profile for me so I can send you a manual offer?

**Comment by adelekennedy** [comment]
Thank you @gijoe0295! Offer sent

**Comment by adelekennedy** [comment]
[offer link](https://www.upwork.com/nx/enterprise-homepage/?offerRid=103499178&nav_dir=replace&teamUid=all_teams&tab=hire)

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
