### ISSUE TITLE
[HOLD for payment 2024-08-14] Report fields - Offline indicator appears below the content when edit to fields is disabled

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45847]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/44672
**Version Number:** 9.0.10-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace is connected to Sage Intacct.
- Workspace has List type report fields by importing Departments as report fields in Accounting > Import settings.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields.
3. Click on the List type report field (Departments) which is imported from Sage Intacct.
4. Go offline.

## Expected Result:
Offline indicator will appear at the page bottom.

## Actual Result:
Offline indicator appears below the content.
NOTE: This issue only happens when changes to report fields are disabled via connection to Accountings.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cf1ca0fa-ec5e-4aa9-bb07-5e8d159b1ad9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight / @abekkala</details>

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-control

**Comment by mountiny** [comment]
Not a blocker as this feature is behind beta

**Comment by mountiny** [comment]
@waterim @rushatgabhane @shubham1206agra who can handle the PR for this given its coming from the report fields configuration project?

**Comment by garrettmknight** [comment]
@waterim @rushatgabhane @shubham1206agra bump on the question above.

**Comment by garrettmknight** [comment]
@abekkala I'm heading OOO until August 5th. I'll pick this back up if it's still going when I get back. Thanks for your help!

**Comment by mountiny** [comment]
@shubham1206agra keep us updated, thanks! @rushatgabhane will you be able to review?

**Comment by rushatgabhane** [comment]
yes

**Comment by abekkala** [comment]
@shubham1206agra do you have an update?

**Comment by garrettmknight** [comment]
We're on staging! @abekkala I'll take this one back over, thanks for the help!

**Comment by mountiny** [comment]
I think we can close this one as payments will be handled together for the project
