### ISSUE TITLE
[HOLD for payment 2024-09-03] [$250] Distance - Error displayed when creating distance expense in workspace that not opened yet

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45856]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45000
## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in with an existing account than has a workspace (make sure to open any chat other that workspace chat when logging out)
2. Click on FAB > Distance expense
3. Enter the start and finish waypoints
4. On the next screen select the workspace you have not opened yet after logging in
5. Finish creating a distance expense

## Expected Result:
The distance expense is created

## Actual Result:
The error "The selected rate has been deletedUnexpected error submitting this expense. Please try again later." is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/93385ba8-bdee-4ce0-9aa3-49dfccd1f2c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cab8213f1b00e98</li>
        <li>Upwork Job ID: 1816211306344908300</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103543103</li>
<li>Krishna2323 | Contributor | 103543106</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by neil-marcellini** [comment]
Since I was tagged in, here are my thoughts. The p2p distance beta is a bit tricky because it's designed to hide some features, like selecting a workspace rate, that are also related to regular distance requests. Do we need to access the rate for the distance request if you are not on the p2p distance beta? I would guess probably yes since it's used to calculate various optimistic data and display elements. When not on the beta we should only use the default rate on the workspace. If we're on the beta, then we should try to get the last selected distance rate or the default rate for workspacse, or the defaultP2PRate for P2P requests.

**Comment by puneetlath** [comment]
@allgandalf have you had a chance to review?

**Comment by puneetlath** [comment]
@allgandalf can you complete the checklist?

**Comment by puneetlath** [comment]
Regression test: https://github.com/Expensify/Expensify/issues/425941

All paid. Thanks everyone!
