### ISSUE TITLE
Tax - Toggle becomes unlocked, Delete button appears briefly after saving tax code of default rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45857]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is under Control plan
- Taxes feature is enabled
1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes
3. Click on the default tax rate
4. Click Tax code
5. Edit the tax code and save it

## Expected Result:
The toggle will remain locked and Delete button will not appear after saving the tax code of the default tax rate

## Actual Result:
The toggle becomes unlocked and Delete button appears briefly after saving the tax code of the default tax rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/82f6a0e4-c244-46a6-96bc-8e9048874b6a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@deetergp  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by etCoderDysto** [comment]
Dupe of https://github.com/Expensify/App/issues/45858

**Comment by lanitochka17** [comment]
Sorry for the confusion
