### ISSUE TITLE
[$250] mWeb - chat - Placeholder box moves as user swipes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45862]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch the site in both mweb and android app
2. Tap on a workspace chat
3. Press and hold the compose box and swipe from right to left and vice versa
4. Tap header
5. Tap private notes
6. Press and hold the input field and swipe from right to left and vice versa

## Expected Result:
In android, placeholder box stays on left constantly and in mweb, the behavior should be same and it must not move as user swipes

## Actual Result:
In android, placeholder box stays on left constantly but in mweb it moves as user swipes. There is inconsistency in behaviour in both mweb and android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ca5e5353-3a99-4039-8875-eb0e7be31c86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e34fe9635b00c75a</li>
        <li>Upwork Job ID: 1815706558239522296</li>
        <li>Last Price Increase: 2024-07-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment]
Can repro on 9.0.11

**Comment by jliexpensify** [comment]
Still reproducible, but we've deprioritised #VSB so lets close for now.

**Comment by VincentCorleone** [comment]
It seems not a bug. In android, when you type some words and then swipe, placeholder box moves as user swipe, which is the same with mweb.
