### ISSUE TITLE
[HOLD for payment 2024-09-09][$250] Track tax - Tax rate is no longer assigned to the distance rate after changing the tax code

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is under Control plan.
- Distance rates and Taxes features are enabled.
- Track tax is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates
3. Click on any distance rate
4. Click Tax rate
5. Assign a tax rate
6. Go to Taxes
7. Click on the tax rate in Step 5
8. Click Tax code
9. Edit tax code and save it
10. Go back to Distance rates
11. Click on the distance rate from Step 3

## Expected Result:
The tax rate will remain assigned to the distance rate after changing the tax code

## Actual Result:
The tax rate is no longer assigned to the distance rate after changing the tax code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cac00e2f-c721-4526-9bfe-94feac12e510

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01487f230385609e0a</li>
        <li>Upwork Job ID: 1815359905732178734</li>
        <li>Last Price Increase: 2024-07-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by mountiny** [comment]
Does this work in production or in OldDot? We might have to optimistically change the tax rate code in the distance rates to make this work, but I wonder if we do this in the backend even.

AS this applies for Control policies, I think we could treat this as NAB

**Comment by mountiny** [comment]
I dont think this is a blocker as its quite a minor case, but we should explore it, marking as external

**Comment by mountiny** [comment]
Asked if this works well in prod or if this is a new feature

**Comment by mountiny** [comment]
QA confirmed this works well in production so given that (I thought its more of a new feature) we should fix this

**Comment by mountiny** [comment]
@daledah that PR is already in production though so some other change caused this issue cc @rushatgabhane @dangrous

**Comment by mountiny** [comment]
Huh, thats odd as the mentioned PR is now in production for sure

**Comment by rushatgabhane** [comment]
@mountiny @dangrous this should be handled on backend, right?

**Comment by mountiny** [comment]
@daledah, with your fix, if you sign out and sign back in, are the distance rates correctly updated to the new tax code? 

I also feel like it might need a backend fix.

Its a new feature though so I dont thing we have to block app deploy on this

**Comment by mountiny** [comment]
Assigning Daniel (I hope thats ok) as you have been working on the project

**Comment by dangrous** [comment]
oh this is actually weirder than I expected. I'm writing a test that should help us fix this on the back end. I think we will need optimistic changes though right?

**Comment by dangrous** [comment]
backend fix is in review, then we can go from there.

**Comment by dangrous** [comment]
Backend PR still waiting on reviews, but hopefully we'll be able to get this moving this week.

**Comment by dangrous** [comment]
**Okay backend fix is in production now.** @rushatgabhane / @daledah can you check if the front end (non optimistic) is behaving as expected now, and if so, evaluate the proposal for updating optimistic data appropriately?

Thanks!

**Comment by dangrous** [comment]
@rushatgabhane can you review @daledah's [proposal](https://github.com/Expensify/App/issues/45861#issuecomment-2242836763) and we can go from there? Thanks!

**Comment by rushatgabhane** [comment]
@dangrous do we need to do this optimistically? 

@daledah what happens when taxCode update fails, do we reset the optimistic data for distance rate?

Can a race condition happen here?

**Comment by dangrous** [comment]
Assigned!

**Comment by dangrous** [comment]
I think this was deployed to prod on 2024-09-02 but we should confirm and adjust payment timing as needed

**Comment by dangrous** [comment]
Automation didn't fire but this seems to have been deployed on 9/2, so payment on 9/9. Grabbed you @garrettmknight for when payment is ready!

**Comment by JmillsExpensify** [comment]
I went ahead and filled out the payment summary above, though repeating here for posterity: 

 - Contributor: $250 @daledah 
 - Reviewer: $250 @rushatgabhane

**Comment by garrettmknight** [comment]
@daledah offer sent in Upwork ([linking here](https://www.upwork.com/nx/wm/offer/103919685))

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
