### ISSUE TITLE
Key Navigation - Going to Search from thread takes you to the main chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45883]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4747703
**Email or phone of affected tester (no customers):** gibethlehem.@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any thread chat with an attachment
2. Click the attachment to open the preview modal
3. Press CTRL+K or CMD+K to open the search page
4. Dismiss the search page

## Expected Result:
Not Taken from the thread chat to the main chat after Dismissing the search page

## Actual Result:
Taken from the thread chat to the main chat after Dismissing the search page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6070da14-c424-4482-9749-cb5be4238f27

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment]
I agree with @abzokhattab [here](https://github.com/Expensify/App/issues/45883#issuecomment-2243151442) that this is not a priority at this time. We can re-address if needed in the future
