### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Tax-In tax name field, saving with code does not throw error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45887]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-condition:Have a workspace with tax enabled
1. Go to expensify site in both mweb and android app
2. Tap profile icon -- workspaces-- workspace
3. Tap tax -- Add tax rate -- Name
4.Paste <h> and save it

## Expected Result:
In tax name field, saving with code must throw error " invalid character " across site consistently in same way.

## Actual Result:
In tax name field, saving with code throws error " invalid character " in android but error not shown in mweb.

Across the site in all input field on saving html code throws error except in tax & Report field name field.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3cd2b6c2-9574-4d9b-9446-444af20b6141

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e31e4849306c8612</li>
        <li>Upwork Job ID: 1815518037392380725</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103327688</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by hungvu193** [comment]
Thanks for proposal everyone.
@Krishna2323 Can you please explain why do we need to create a new state called `shouldValidateOnChange` instead using `shouldValidateOnChange=true` directly?

@dominictb `shouldValidateOnBlur={true}` will make the form validate and showed errors even when we didn't select any value for them, I don't think that's a good way to handle such cases. Please see the video below.

https://github.com/user-attachments/assets/012c4bb0-99eb-4cfa-a3e5-5e33c018f1af

**Comment by hungvu193** [comment]
That's different cases, these cases that you mentioned we validated on blur directly on that field, in this case we opened a new screen to do that so I'm still aligned with my opinion above.

**Comment by hungvu193** [comment]
> @hungvu193 Curious how you think it is different? Isn't blurring the TextPicker in the new screen the same as blurring the text input itself?

I think that's why we added `shouldValidateOnBlur={false}` everywhere we used TextPicker. If TextPicker is blurred, it should show error on TextPicker too.


> @hungvu193 Could you give more details on why you think that's not a good way in terms of UX perspective, as far as I can see it's the same UX we've been using everywhere else, and it's better than not showing any error after the user blurs the required inputs.

It's not the same, if you're talking about validating on blur, it should show error on TextPicker screen when we blurred TextInput as well. There will be inconsistency here, we click back from TextPicker => no error, we blur the input from TextPicker and click back => error showed.


cc @shawnborton for more thoughts here.

**Comment by hungvu193** [comment]
> > Can you please explain why do we need to create a new state called shouldValidateOnChange instead using shouldValidateOnChange=true directly?
> 
> * `shouldValidateOnChange` is true by default, when we open the text picker or amount picker and save even without entering any value or blur the input, `onBlur` is called and the input is registered in `touchedInputs`.
>   https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/components/Form/FormProvider.tsx#L317-L341
> * The validation runs even when we save the value for the first time but we don't see the error because the input wasn't registered in `touchedInputs`.
>   https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/components/Form/FormProvider.tsx#L155-L159
> * When we open the modals for the second time and if the input was blurred before, then after saving the value, `onValidate` runs and we get the error.
>   https://github.com/Expensify/App/blob/1084706b35c2157656ca747374b766083c910061/src/components/Form/FormProvider.tsx#L350-L352
> 
> ### We have two options here:
> * We should be only start validating once user hits the submit button. For that we can create a new state and only pass true to `shouldValidateOnChange` when user has only submitted the form once. [Explained in the proposal](https://github.com/Expensify/App/issues/45887#issuecomment-2242686891).
> * We can create a prop `setInputTouchedOnChange` in `FormProvider` (or we can introduce this in `inputProps` so it will be for a specific input), which will register the input in `touchedInputs` before calling `onValidate` inside `onInputChange`.
> 
> ```js
> onInputChange: (value, key) => {
>     const inputKey = key ?? inputID;
>     setInputValues((prevState) => {
>         const newState = {
>             ...prevState,
>             [inputKey]: value,
>         };
>         if (setInputTouchedOnChange) {
>             setTouchedInput(inputID);
>         }
>         if (shouldValidateOnChange) {
>             onValidate(newState);
>         }
>         return newState as Form;
>     });
>     if (inputProps.shouldSaveDraft && !formID.includes('Draft')) {
>         FormActions.setDraftValues(formID, {[inputKey]: value});
>     }
>     inputProps.onValueChange?.(value, inputKey);
> },
> ```
> 
>  form_validation_add_rate.mp4

Thanks for your explanation, I'll review after we have confirmation from design team 🙏

**Comment by shawnborton** [comment]
I'm a little lost - can you explain in more detail?

Based on what I see from the bug report though, it seems like we shouldn't even allow you to save the tax rate name with the forbidden character. We should throw the error on that same "edit name" page and make the user fix the error before it saves.

**Comment by hungvu193** [comment]
> Based on what I see from the bug report though, it seems like we shouldn't even allow you to save the tax rate name with the forbidden character. We should throw the error on that same "edit name" page and make the user fix the error before it saves.

I agree with this one.



> I'm a little lost - can you explain in more detail?

We're talking about the way we should show error on `name` (and `value`) field in `WorkspaceCreateTaxPage`. When we click on `name` field, we we will open `TextPicker` screen.
Should we:
1. Show error on `name` field when `TextPicker` input is blurred
<details><summary>Example</summary>

https://github.com/user-attachments/assets/012c4bb0-99eb-4cfa-a3e5-5e33c018f1af

</details>

2. Show error on `name` filed only when we press save on `TextPicker` screen.
3.  Or like you said, we should validate the input on TextPicker screen ("edit screen").

**Comment by shawnborton** [comment]
Oh interesting... part of me thinks we wouldn't show those errors until we hit the Save button to submit the form for the Add rate page.

**Comment by shawnborton** [comment]
Also cc @Expensify/design for their input too.

**Comment by dannymcclain** [comment]
I agree with Shawn. I don't think we would show those errors on the `Add rate` page until someone tries to hit Save.

But on the individual `Name` input page, I think we could also validate that when they click the Save button on that screen. So if they don't enter anything or enter an invalid character and try to hit the Save button for the name field, we'd show an error message.

Does that make sense / follow our other validation patterns?

**Comment by trjExpensify** [comment]
>I don't think we would show those errors on the Add rate page until someone tries to hit Save.

Agreed. 

>But on the individual Name input page, I think we could also validate that when they click the Save button on that screen. So if they don't enter anything or enter an invalid character and try to hit the Save button for the name field, we'd show an error message.

I agree here too, but I would also say if they blur the filed we should show the error like other forms, right?

**Comment by hungvu193** [comment]
> @hungvu193 Looks like everyone agrees with this UX, that's also what I suggested and proposed a solution to in the [alternative part here](https://github.com/Expensify/App/issues/45887#issuecomment-2244564751)

Please make sure that you will post a comment to let everyone know you updated your proposal.
```
    - If you want to make an entirely new proposal or update an existing proposal, please go back and edit your original proposal, then post a new comment to the issue in this format to alert everyone that it has been updated:
    ```
    ## Proposal
    [Updated](link to proposal)
    ```
```



> Could you take a look to see if we can go with it? Thanks.

I think it's looking good, but can you give it a little bit more details? Also an evidence video would be appreciated. Thank you 😄

**Comment by hungvu193** [comment]
> > I think it's looking good, but can you give it a little bit more details? Also an evidence video would be appreciated. Thank you 😄
> 
> Please wait, I also want to update my proposal according to the new expected behaviour.

Sure thing. I didn't accept any proposals yet. 😄

**Comment by hungvu193** [comment]
> @hungvu193 Hey sure, but to clarify that UX suggestion and solution was there in the first version of my proposal, the edit was just to add a bit more details.

I don't think that's enough since that was confirmed by the conversation above. I will expect a proposal with detailed implementation

**Comment by hungvu193** [comment]
Not overdue, reviewing today

**Comment by hungvu193** [comment]
@dominictb 's [proposal](https://github.com/Expensify/App/issues/45887#issuecomment-2244564751) looks good to me! I prefer using `FormProvider` for `TextPicker`

🎀 👀 🎀  C+ reviewed

**Comment by yuwenmemon** [comment]
@hungvu193 Assigned. You may need to solicit another Engineer for merge as I'll be OOO until the 13th starting tomorrow.

**Comment by hungvu193** [comment]
Requested internal engineer to take over this issue on [Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1722840962414049)

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37967
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A

**Regression test:**
1. Login with any account.
2. Go to Profile => workspaces => Open any workspace that has Tax feature enable.
3. Go to tax => Add tax rate => Name.
4. Enter <h> or any invalid character in the name input.
5. Press Save.
6. Verify that: the name input should show error "Invalid character" after clicking on save button.

Do we 👍 or 👎  ?

**Comment by hungvu193** [comment]
little bump @RachCHopkins for the payment 😄

**Comment by RachCHopkins** [comment]
Sorry @hungvu193 I've been a little tied up! I'll get this organised tomorrow!

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor: @dominictb paid $250 via Upwork
Contributor+: @hungvu193 due $250 via NewDot

Upwork job [here](https://www.upwork.com/jobs/~01e31e4849306c8612)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed. @hungvu193 please go ahead and raise your NewDot Request!

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
