### ISSUE TITLE
Login – mWeb opens briefly when log in via Magic link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45891]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4751538
**Email or phone of affected tester (no customers):** applausetester+jp621724@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. On login page enter new Expensify account and tap Sign in button.
3. Open email and navigate via Magic link

## Expected Result:
App opens

## Actual Result:
mWeb opens briefly and then app opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6ec9d5ae-c6ee-4691-8394-dc162018b958

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I'll test it soon; this GH is on my testing list.

**Comment by alexpensify** [comment]
No update yet

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience mentioned here. When I click the magic link on my Android device, I'm taken to the application only.
