### ISSUE TITLE
QBO - The app crashes after connecting to QBO and tapping on a setting a few times

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45906]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4751067&group_by=cases:section_id&group_id=309135&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Create a workspace
4. Enable "Accounting" from the workspace settings
5. Navigate to Accounting
6. Connect to QBO
7. Tap on any setting button under QBO after it has finished syncing

## Expected Result:
I should be able to navigate to the settings page without crashing the app

## Actual Result:
The app crashes after connecting to QBO and tapping on a setting a few times

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f6bed237-f9ec-41d6-aa2d-459e88f4ed40

[1.log](https://github.com/user-attachments/files/16334056/1.log)
[2.log](https://github.com/user-attachments/files/16334057/2.log)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d5086ea67aef1e7</li>
        <li>Upwork Job ID: 1815631807021214555</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
Maybe its related to this crash which is the only one seen in the firebase
[com.chat.expensify.chat_issue_ee1256448fb6b0ac22a0e9a88c62f18e_crash_session_dbb68c266fb6498e979aaa2c340f54a9_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16333853/com.chat.expensify.chat_issue_ee1256448fb6b0ac22a0e9a88c62f18e_crash_session_dbb68c266fb6498e979aaa2c340f54a9_DNE_0_v2_stacktrace.txt)
[com.chat.expensify.chat_issue_ee1256448fb6b0ac22a0e9a88c62f18e_crash_session_dbb68c266fb6498e979aaa2c340f54a9_DNE_0_v2.log](https://github.com/user-attachments/files/16333854/com.chat.expensify.chat_issue_ee1256448fb6b0ac22a0e9a88c62f18e_crash_session_dbb68c266fb6498e979aaa2c340f54a9_DNE_0_v2.log)

**Comment by mountiny** [comment]
Discussing [here](https://expensify.slack.com/archives/C05LX9D6E07/p1721654435346839)

**Comment by mountiny** [comment]
This is apparently still happening even after the CP :/

**Comment by mountiny** [comment]
Seems like the crash is resolved though and the other issues observed.

[This](https://github.com/Expensify/App/issues/45766) was apparently seen again and in android the App did not crash but became unresponsive

https://github.com/user-attachments/assets/06b53ec1-353a-4fc9-9bd9-1e35789cf308

**Comment by mountiny** [comment]
I have just gone through the flow on the latest staging, and it worked well, I demoting to further investigate. Here are the logs and cpu traces from the long flow, i took a while to find the login details

[logs-2024-07-23 07_39_59.998.txt](https://github.com/user-attachments/files/16345320/logs-2024-07-23.07_39_59.998.txt)
[App_Info_9.0.10-2 2.json](https://github.com/user-attachments/files/16345321/App_Info_9.0.10-2.2.json)
[Profile_trace_for_9.0.10-2.cpuprofile 2.zip](https://github.com/user-attachments/files/16345324/Profile_trace_for_9.0.10-2.cpuprofile.2.zip)

Here is the video

https://github.com/user-attachments/assets/03c6a3ff-9381-4566-893a-0ed3cf77624f

**Comment by kavimuru** [comment]
No crash occurs now. stuck in 'Waiting for imported data to load". Tester has to revisit the page.

[log_qbo.log](https://github.com/user-attachments/files/16350244/log_qbo.log)

https://github.com/user-attachments/assets/307f71bc-c656-4cb0-9ce1-d7e28f9f1ed5

[App_Info_9.0.11-0.json](https://github.com/user-attachments/files/16350246/App_Info_9.0.11-0.json)

https://github.com/user-attachments/assets/31f53aec-b3ae-4e3f-bb27-3d2685c01b38

[logs-2024-07-23 13_51_03.635.txt](https://github.com/user-attachments/files/16350248/logs-2024-07-23.13_51_03.635.txt)

**Comment by mountiny** [comment]
Probably nothing else to do here really, seems like a weird one off issue
