### ISSUE TITLE
mWeb - Scan - Creating scan expense using blurry receipt shows random amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4748643
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a workspace chat
3. Tap plus icon -- submit expense - scan
4. Upload a blurry receipt shown below
5. Tap submit expense
6. Wait few seconds still scan completed
7. Open the scan expense created
8. Tap on receipt, enlarge & view that amount is not clear in receipt

## Expected Result:
Creating scan expense using blurry receipt must show red dot & amount 0.00

## Actual Result:
Creating scan expense using blurry receipt is not showing red dot & amount 0.00. Receipt doesn't show amount clearly but after scan complete random amount is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/95ee696e-1791-4bd0-830e-92f5153383a7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jacobkim9881** [comment]
I think this might be closed. Reading and calculating analog data from a computer might be false sometimes.

**Comment by OfstadC** [comment]
Thanks @jacobkim9881 - Closing this out
