### ISSUE TITLE
[HOLD for payment 2024-08-05] [$250] [HybridApp] 'Update App' page redirects users to NewDot standalone

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#45911]
cc @trjExpensify @AndrewGable 

### Problem

Hybrid users can't access the app when the version doesn't match the current [min-version](https://github.com/Expensify/Web-Expensify/blob/f3d37d9a2a0ba93d5ff7dfc21f6fd64fff976aff/lib/Request.php#L29-L31). Users with the redirection NVP set get stuck on each app open. The 'update' button takes them to the NewDot standalone app which isn't helpful.

![Screenshot_20240722_140758](https://github.com/user-attachments/assets/56063094-ce15-4221-b5a5-077bcbaf8183)

### Solution

Update the URL to OldDot app listing before Hybrid is shipped.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd6e839e5481e762</li>
        <li>Upwork Job ID: 1817838538974475497</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by hungvu193** [comment]
@Julesssss  Since I reviewed https://github.com/Expensify/App/pull/46194, can you please assign me to this issue? TIA 😄

**Comment by staszekscp** [comment]
I think this can be closed 😄

**Comment by Julesssss** [comment]
Assigning BZ for payment. @twisterdotcom this is complete, can you just pay out a PR review for @hungvu193 please

**Comment by twisterdotcom** [comment]
Payment Summary:

- @staszekscp does not require payment (Contractor)
- @hungvu193 paid $250 via Manual Requests (C+)

**Comment by hungvu193** [comment]
Requested on ND

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
