### ISSUE TITLE
[$250] Free trial - #admins link is present in free trial message when there is no #admins room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45920]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new account and log in.
3. Go to self DM.
4. Track a manual expense.
5. Click Submit it to someone.
6. Select a user and submit.
7. Go to Concierge.
8. Right click on the #admins link in free trial message.

## Expected Result:
There is no workspace created in the account at the time of receiving the free trial message after submitting expense to someone. The free trial message should not have the #admins link

## Actual Result:
The #admins link is present in the free trial message and it is an invalid link - https://new.expensify.com/r/0

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/321b6ee2-2f84-40bc-b355-a2fe2c0a4f25

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ba865581db4d132</li>
        <li>Upwork Job ID: 1815993299973335899</li>
        <li>Last Price Increase: 2024-07-31</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jacobkim9881** [comment]
The message with a link is given as a response. There is no function or code to send the message in the app.

**Comment by kadiealexander** [comment]
I'm actually going to close this as not a priority. Feel free to reopen if you disagree.
