### ISSUE TITLE
[Workspace Feeds] [Design] Mock how the Card limit type page when offline

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45924]
### Problem

We need to use the Pattern C when changing the card limit type page as to knwo what options can be shown, we need to know unapproved and total spend on the card. More details [here](https://expensify.slack.com/archives/C036QM0SLJK/p1721311425532449).

This means we cannot really let to user change the limit type when they are offline. We will create a new API command that will fetch the relevant data when this page is opened to decide what options to show. This however means we cannot let the user make a change until this data is fetched.

### Solution

<img width="495" alt="image" src="https://github.com/user-attachments/assets/1ab55a22-bfba-4669-8e5b-0f28f9892ae4">

Should we update how this page is shown when user is offline, ideally letting them know that the they can change the type only when they are online?

**Comment by dubielzyk-expensify** [comment]
It looks like in some parts of the app we allow for it to be changed, but then once the value has changed we fade the push input (presumably to save the value on next available save opportunity). If this is a deliberate pattern, let's use that:

![CleanShot 2024-07-23 at 12 57 47@2x](https://github.com/user-attachments/assets/18adb275-ceeb-4d7d-b642-7b9b20a0d627)

If not, we could also just fade and disable the push input until they're online again:

![CleanShot 2024-07-23 at 12 58 33@2x](https://github.com/user-attachments/assets/ad70581b-67d1-4089-8a57-c8386747fc94)

Keen to hear which behavior @Expensify/design think is right here.

**Comment by mountiny** [comment]
The first option is Pattern B, we take the action optimistically and assume it succeeded only to show error if not.

But in this case we do
Not want to allow user to take action on editing the type.

I think that we might want to let them navigate to the page but inform them they cannot take the action there. I think that would be cleaner

**Comment by shawnborton** [comment]
If we're using Pattern C here, this is what I see from the [original design doc](https://docs.google.com/document/d/1RWPLDgdrJ4eW1KfseVmrYYy_fDUWWDQpek-hmdzAtuM/edit):

> Pattern C - Blocked Form 
> What: This pattern greys out the submit button on a form and does not allow the form to be submitted, and notifies the user of their offline status. Importantly, we do let the user fill out the form fields. That data gets saved locally so they don’t have to fill it out again once online.
> When: This should be used when we cannot allow the user to submit the form while offline.
> Example: SetPassword/ChangePassword 

So maybe we just need to make all of the options on this page grayed out:
![CleanShot 2024-07-23 at 09 12 26@2x](https://github.com/user-attachments/assets/91d51dfa-0aa4-4e31-8551-60f6d641439b)

Also, that mock is slightly confusing - it shouldn't need a Save button if you access a list selection outside of a flow, right? So in that case, I think we'd just gray out all of the options and use the offline message at the bottom?

**Comment by mountiny** [comment]
Yes that is right I think the Confirmation button should not be there in this flow

**Comment by trjExpensify** [comment]
Agreed it doesn't need a confirmation button here. I like Shawn's suggestion to grey out the select list values.

**Comment by dubielzyk-expensify** [comment]
Thanks team. Just to clarify for my understanding, if this mock is what we want:

![image](https://github.com/user-attachments/assets/7a95d5f8-a87d-4b00-a6a6-fa12c6f5be97)


...then doesn't that violate the rule in Pattern C?
> Importantly, we do let the user fill out the form fields. That data gets saved locally so they don’t have to fill it out again once online.

Wouldn't we allow them to change it and grey out the push input which would become un-greyed when it's saved later?

**Comment by trjExpensify** [comment]
Oh, actually.. isn't the whole point of why we have to use Pattern C here because we don't know which options to show in this select list without an API call?

>We need to use the Pattern C when changing the card limit type page as to knwo what options can be shown, we need to know unapproved and total spend on the card.

So with that, why are we opening this select list? Rather, greying out the menu item like shown here but removing the right carets from the applicable rows: 

![CleanShot 2024-07-23 at 12 58 33@2x](https://github.com/user-attachments/assets/ad70581b-67d1-4089-8a57-c8386747fc94)

**Comment by trjExpensify** [comment]
Alternatively, we'd need to push to a full page blocking form with the "You appear to be offline" message, which might be the most consistent tbf.

**Comment by dubielzyk-expensify** [comment]
Ahh, yeah that also seems fair. I don't mind if we have a full offline screen or fade the push input. Both should be clear either way though the latter saves them a click.

**Comment by shawnborton** [comment]
> we'd need to push to a full page blocking form with the "You appear to be offline" message, which might be the most consistent tbf.

That does seem like the most consistent option... like for example, when you are offline, we don't disable the button to add a bank account, we just give you the full page "we can't do this while you are offline" screen once you actually get there.

**Comment by dubielzyk-expensify** [comment]
But when you go to Workspaces -> Categories -> and change any value, we do what I described above where we fade/disable the push input once the value is saved locally. Which I think is a closer example than starting a new flow (e.g. bank account)

**Comment by shawnborton** [comment]
Right, but that's different from Tom's point here:

> Oh, actually.. isn't the whole point of why we have to use Pattern C here because we don't know which options to show in this select list without an API call?

As in, we need online connectivity to even know which options we can show to the user for the limit type. Does that sound right @trjExpensify ?

**Comment by dubielzyk-expensify** [comment]
Right, I see. Then that would make more sense then 👍

**Comment by trjExpensify** [comment]
>As in, we need online connectivity to even know which options we can show to the user for the limit type. Does that sound right @trjExpensify ?

Yep, exactly. That's why we're using Pattern C and not Pattern B.

**Comment by trjExpensify** [comment]
So cool, we just need to use the standard "You appear to be offline" full page form here, @mountiny.

**Comment by mountiny** [comment]
Ok sounds fair and safe option, thanks everyone  🙇 cc @koko57 @allgandalf @DylanDylann @VickyStash for visibility, the API is not ready for this one yet but we will need to use pattern D

**Comment by dubielzyk-expensify** [comment]
Not overdue, Sir Melvin

**Comment by dubielzyk-expensify** [comment]
Any update? Should this still be daily?

**Comment by dubielzyk-expensify** [comment]
Any updates?

**Comment by mountiny** [comment]
I have noted this in [Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1723132436787869?thread_ts=1721311425.532449&cid=C036QM0SLJK) for the engineers working on this page. We can close now I think
