### ISSUE TITLE
[HOLD for payment 2024-08-01] [LOW] [Performance] Improve the performance of getDisplayNameForParticipant

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45925]
### Problem

In the logs and profile traces from Jason's iOS app use, we can see that the getDisplayNameForParticipant method is taking a lot of processing time, forming a bottleneck.

### Solution

Work on improving the performance of this method getDisplayNameForParticipant. The proposed solution from Callstack is to cache the phone number formatting

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor+: @allgandalf owed $250 via NewDot

**Comment by mountiny** [comment]
Nice so no checklist for this one and @allgandalf is paid on Newdot and we got a summary so we can close, thanks everyone!
