### ISSUE TITLE
[$250] BUG: No prompt to re-enter credentials appears when incorrect credentials entered to connect to Sage Intacct

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#45937]
Testing doc: [here](https://docs.google.com/document/d/1AdHIz229Ze3BovRRR5YLW7nx8I2slf7greYkpV0SifI/edit?usp=sharing) (request, will share)

Pre-testing steps

- Make sure the email address does not already have existing workspaces/policies
- Make sure emails sent to the testing email addresses go to an inbox you can access to validate your account(s)
- Create a new collect policy on OldDot and; 
- Set the approval mode to “submit and approve”
- Enable scheduled submit with a frequency of `Daily` or “slower”
- Invite an additional user to the policy to play the member role in these testing flows
- Run the script stated [here](https://stackoverflowteams.com/c/expensify/questions/17518) to enable workspace chat creation for a paid plan.

Pre-testing steps

- Make sure that your test account is on the intacctOnNewExpensify beta
- Make sure you have Sage Intacct web services user ID, password and Company ID to initiate a connection
- Make sure you create a new workspace/policy for each test run
- Make sure emails sent to the testing email addresses go to an inbox you can access to validate your account(s)

Steps:
1. Head to Workspace settings
2. Head to Accounting
3. Under Sage Intacct Connection click `Connect`
4. Enter incorrect validation tokens
5. Click on the kebab menu

Expected result: Re-enter credentials prompt shown in bottom drawer 
Actual result: No prompt is given to re-enter credentials

Screenshot:
<img width="1411" alt="Screenshot 2024-07-22 at 8 33 00 PM" src="https://github.com/user-attachments/assets/092bb3f2-062e-4864-81d2-19205a504429">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01346620ef39dd3f87</li>
        <li>Upwork Job ID: 1815806848431209976</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by hungvu193** [comment]
That's so coincident that I'm also working on SageIntacct project 😂 

Hey @JmillsExpensify, can you please share the docs with me and @war-in?

cc @war-in

**Comment by war-in** [comment]
@dylanexpensify @hungvu193 I think we already have an issue for that case. I took it over from @SzymczakJ and posted a comment [here](https://github.com/Expensify/App/issues/44669#issuecomment-2232723850).

We can still close the other one and go with this if you want to 👍

**Comment by dylanexpensify** [comment]
Ahh if this will be solved in the linked issue, we can keep that one and
close this one!

**Comment by hungvu193** [comment]
Yeah, we're good to close this one 😄
