### ISSUE TITLE
[HOLD for payment 2024-08-02] [CRITICAL] [Advanced Approval Workflows] Remove delayed submission beta, add advanced approval beta

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45947]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.azoucaomf0tz)

<details><summary>Issue Owner</summary>Current Issue Owner: @blazejkustra</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by mollfpr** [comment]
@tgolen Could you help assign me to this issue since I've reviewed the PR https://github.com/Expensify/App/pull/45992. Thank you!

**Comment by tgolen** [comment]
@johncschuster could you please help with paying @mollfpr for their rC+ eview on the PR?

**Comment by johncschuster** [comment]
Sure thing! I'll get payment issued now!

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor+: @mollfpr owed $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr

**Comment by garrettmknight** [comment]
@JmillsExpensify unapproved in NewDot - I'm reapproving $250 as the new approver.
