### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] [CRITICAL] [Advanced Approval Workflows] Add new routes & rename existing workflow routes

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45948]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.l8ixwgieassl)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a1135e39a2c0434</li>
        <li>Upwork Job ID: 1816595172937564430</li>
        <li>Last Price Increase: 2024-07-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by DylanDylann** [comment]
@tgolen Please help to assign me

**Comment by tgolen** [comment]
@trjExpensify You've been summoned because @DylanDylann needs to be paid for a C+ review of the PR.

**Comment by trjExpensify** [comment]
Dang, this is worse than the #principals-office! 😏

**Comment by tgolen** [comment]
I'm a really nice principal though. Friends with all the kids.

**Comment by trjExpensify** [comment]
@DylanDylann remind me are you actually paid via Upwork still?

**Comment by DylanDylann** [comment]
@trjExpensify Yes, I get paid via Upwork

**Comment by trjExpensify** [comment]
@DylanDylann sent you an offer!

**Comment by trjExpensify** [comment]
@DylanDylann waiting for you to accept the offer!

**Comment by DylanDylann** [comment]
@trjExpensify Sorry I missed this, accepted the offer with thanks 🙏

**Comment by trjExpensify** [comment]
Paid, closing. Thanks!
