### ISSUE TITLE
[$250] Search Sidebar disappears if user selects a item in search page in small screen and resize to large screen

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45944]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721671131398249

## Action Performed:
1. Open search page and resize window width so Search Sidebar is not visible
2. Long press on any search item and select it.
3. Resize window width
## Expected Result:
Items are still selected and Search sidebar is not blank
## Actual Result:
 Items are unselected and Search sidebar is blank
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/9e300d95-8325-4cb3-a97e-5531d32f16eb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/e5889bfa-3738-4638-922b-122ada443333

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01581b361b92a0761c</li>
        <li>Upwork Job ID: 1816862576518588056</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103446198</li>
<li>dominictb | Contributor | 103446200</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by kevinksullivan** [comment]
discussing there ^

**Comment by mountiny** [comment]
Since there were no changes in scope of this GH required to fix this issue, and it was fixed by some other change elsewhere, there is no payment required and we can close this out, thank you!
