### ISSUE TITLE
[HOLD for payment 2024-08-09] [CRITICAL] [Advanced Approval Workflows] Divide workflows page into three sections

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45949]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.k6c7enb7w88k)

<details><summary>Issue Owner</summary>Current Issue Owner: @Guccio163</details>

**Comment by Guccio163** [comment]
Hi! I'm Wiktor Gut from Software Mansion, an expert agency, I talked with @blazejkustra and I'd like to work on this issue!

**Comment by jayeshmangwani** [comment]
@tgolen I have been assigned to the PR for this issue. May I get access to the [document](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.k6c7enb7w88k) please?

**Comment by tgolen** [comment]
Sure! Can you let me know what email address I can share it with?

**Comment by jayeshmangwani** [comment]
> Sure! Can you let me know what email address I can share it with?

jayeshmangwani@gmail.com

**Comment by tgolen** [comment]
OK, shared!

**Comment by jayeshmangwani** [comment]
@tgolen Can you please assign me to this issue and also assign a BZ member to add the payment summary?

**Comment by tgolen** [comment]
@Christinadobrzyn Could you please help pay @jayeshmangwani for a C+ review of the PR?

**Comment by Christinadobrzyn** [comment]
Yes! Payouts due:

- [ ] Contributor+: $250 @jayeshmangwani (Upwork offer - https://www.upwork.com/nx/wm/offer/103496779)

**Comment by jayeshmangwani** [comment]
Hi @Christinadobrzyn, I am receiving payment from NewDot.

**Comment by Christinadobrzyn** [comment]
Perfect! Thanks @jayeshmangwani - I think this is good to close unless we should have a regression test?

**Comment by jayeshmangwani** [comment]
> we should have a regression test?

I don't think we need a regression test here since it's just a feature enhancement.

**Comment by Christinadobrzyn** [comment]
Sounds good! Closing this!

**Comment by jayeshmangwani** [comment]
Requested on ND as per https://github.com/Expensify/App/issues/45949#issuecomment-2284656434

**Comment by JmillsExpensify** [comment]
$250 approved for @jayeshmangwani
