### ISSUE TITLE
[CRITICAL] [Advanced Approval Workflows] Adjust <WorkspaceWorkflowsApprovalsApproverPage /> for Approver Selection

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45956]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.wi2m6bayaavv)

<details><summary>Issue Owner</summary>Current Issue Owner: @blazejkustra</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by tgolen** [comment]
# Monthly Update
- I'm checking to see if this issue can be closed. I see the PR had a C+ review on it, but there is no record in this issue of the C+ getting paid.

### Next Steps
- @tgolen If the C+ needs to be paid, assign this issue to someone from BZ to pay them out. If they don't need to be paid, this issue can be closed.

#### ETA
- Closed by Monday, Sep 3

**Comment by tgolen** [comment]
# Monthly Update
- I see the C+ was paid https://github.com/Expensify/App/pull/46510#issuecomment-2321953555 so I will close out this issue.
