### ISSUE TITLE
[CRITICAL] [Advanced Approval Workflows] Implement utils that transform data between backend and frontend (`convertApprovalWorkflowToPolicyEmployees` & `convertPolicyEmployeesToApprovalWorkflows` functions)

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45957]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.auw2w7bf6a4s)

<details><summary>Issue Owner</summary>Current Issue Owner: @blazejkustra</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
@tgolen Functions implemented in this PR aren't used anywhere yet, that's why I think we do not need C+ review for this one.

**Comment by blazejkustra** [comment]
Same thing for [this PR](https://github.com/Expensify/App/pull/46189), I added onyx actions for the future PRs but for now these are unused.

**Comment by tgolen** [comment]
# Monthly Update
- There was no C+ review of this PR and the work has been completed. I will close this out.
