### ISSUE TITLE
[HOLD for payment 2024-08-09] [CRITICAL] [Advanced Approval Workflows] Update payment section with bank icon

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45950]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.7b4c8iaii3un)

<details><summary>Issue Owner</summary>Current Issue Owner: @Guccio163</details>

**Comment by JmillsExpensify** [comment]
@Guccio163 Will you work on this issue as well?

**Comment by Guccio163** [comment]
Hey I'm Wiktor Gut from Software Mansion, yes I'll handle it as well so please assign it to me!

**Comment by Guccio163** [comment]
I guess we can close it since it was resolved together with #45949 :)

**Comment by tgolen** [comment]
Closing this out.
