### ISSUE TITLE
[HOLD for payment 2024-08-14] [CRITICAL] [Advanced Approval Workflows] Enhance `toLocaleOrdinal` to support string ordinals

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45958]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.e001majd1en9)

<details><summary>Issue Owner</summary>Current Issue Owner: @blazejkustra</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by tgolen** [comment]
OK, sounds good, thanks. I think this one will end up closing out automatically at some point.
