### ISSUE TITLE
[HOLD for payment 2024-08-07] [CRITICAL] [Advanced Approval Workflows] Implement Onyx Actions (API calls & Onyx writes)

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45959]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.5z0njgmwe6oy)

<details><summary>Issue Owner</summary>Current Issue Owner: @blazejkustra</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
@tgolen We can close this issue 👌
