### ISSUE TITLE
[HOLD for payment 2024-08-02] [CRITICAL] [Advanced Approval Workflows] Create `<AddApprovalWorkflow />` button

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45952]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.ac7ndvp9oms)

<details><summary>Issue Owner</summary>Current Issue Owner: @blazejkustra</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by tgolen** [comment]
# Weekly Update
- The PR was deployed quite a while ago. 
- @mollfpr were you ever compensated for [your C+ review on the PR](https://github.com/Expensify/App/pull/45992#issuecomment-2245447031)?

### Next Steps
- @tgolen Get payments cleared up and close this out

#### ETA
- Closed by Wednesday, Sep 4

**Comment by mollfpr** [comment]
@tgolen I think we can close this. I already paid here: https://github.com/Expensify/App/issues/45947.
