### ISSUE TITLE
[CRITICAL] [Advanced Approval Workflows] Implement <WorkspaceWorkflowsApprovalsCreatePage /> for Workflow Creation

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#45954]
Coming from: [#wave-control: advanced approval + workflows polish](https://docs.google.com/open?id=12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc#bookmark=id.uj6zmgx8uif)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
> Still overdue 6 days?! Let's take care of this!

Tomorrow I'm starting the work on this one 👀

**Comment by DylanDylann** [comment]
@tgolen Could you help process payment for me to review this [PR](https://github.com/Expensify/App/pull/46798)?

**Comment by tgolen** [comment]
@JmillsExpensify Could you please assist with paying @DylanDylann for a C+ review of the PR?

**Comment by tgolen** [comment]
bump @JmillsExpensify This one is waiting for you to pay out @DylanDylann for a C+ review of the PR.

**Comment by DylanDylann** [comment]
@JmillsExpensify Kindly bump on payment

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @DylanDylann for PR review and testing.

**Comment by DylanDylann** [comment]
@JmillsExpensify I accepted the offer thanks

**Comment by JmillsExpensify** [comment]
Thanks, paid via Upwork!
