### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] [Wave Control] Update the Report field list type creation flow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#45990]
When creating a list-type report field, we need to make sure the Initial value option comes after the list of values AND the List values option shows the created values as a comma-separated list, as shown below.

Note that the list values should not truncate but wrap to next line

![image](https://github.com/user-attachments/assets/bc64b5d2-1529-4a3d-8ac6-7d4dc13c067f)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124fe6a5dd4337910</li>
        <li>Upwork Job ID: 1815657257015158749</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103272331</li>
<li>Krishna2323 | Contributor | 103272333</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by mountiny** [comment]
@Expensify/design @JmillsExpensify Can you please double check that is right?

**Comment by shawnborton** [comment]
Looks good to me!

**Comment by mountiny** [comment]
@rushatgabhane @shubham1206agra can you please review the proposal? 

I think the main problem here is to make sure the list values nicely wrap even if the list is very long

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The list values are displayed incorrectly

### What is the root cause of that problem?
This is a new feature request
### What changes do you think we should make in order to solve the problem?
1. We should move the initial value item to below the list value

2. Get the values of the report field and pass the `title` prop as the joined list value. Add `styles.preWrap` style to `titleStyle` prop so the list value can be displayed in multiline and add `styles.breakAll` so the long value can be displayed fully.

```
const reportFieldValues = policy?.fieldList?.[reportFieldKey].values ?? [];
{isListFieldType && (
    <MenuItemWithTopDescription
        style={[styles.moneyRequestMenuItem]}
        titleStyle={{...styles.flex1, ...styles.preWrap, ...styles.breakAll}}
        description={translate('workspace.reportFields.listValues')}
        shouldShowRightIcon
        title={reportFieldValues.join(', ')}
        onPress={() => Navigation.navigate(ROUTES.WORKSPACE_REPORT_FIELDS_LIST_VALUES.getRoute(policyID, reportFieldID))}
    />
)}
```
https://github.com/Expensify/App/blob/bf4bc6f5770babaeb5b4c1d932b364e035f69e2a/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L97-L98

3. We also need to wrap the `ScrollView` here so that if the list value is too long, we can scroll to the initial value

https://github.com/Expensify/App/blob/bf4bc6f5770babaeb5b4c1d932b364e035f69e2a/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L72


We should do the same for the creation flow in `CreateReportFieldsPage`.

We can see the test branch here for more details https://github.com/nkdengineer/App/tree/fix/45990.
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/user-attachments/assets/3032e8b1-930f-4e74-9758-a0d4809c14a5

**Comment by shawnborton** [comment]
Cc @Expensify/design @JmillsExpensify @trjExpensify - do we have strong feelings here? Part of me thinks that trimming to 4-5 lines makes sense here in case the list is insanely long.

**Comment by trjExpensify** [comment]
I definitely think we should cap it, these imported lists of customers/projects can be very long.

**Comment by rafaykr** [comment]
Dear Hiring Manager,

I am excited to submit my proposal for the React Native developer position to assist with the migration project at Expensify. As a seasoned full-stack developer with a strong focus on mobile application development and user experience, I am confident in my ability to address the challenges outlined in GitHub issue [#45990](https://github.com/Expensify/App/issues/45990).

Expensify’s commitment to maintaining a reliable and secure system for processing financial transactions is commendable, and the goal of unifying the front-end across platforms using React Native is a strategic move towards enhancing user experience and operational efficiency. I am eager to contribute to this mission and help ensure that your platform remains at the forefront of innovation in the financial sector.

Addressing Your Needs:
Ensuring Accurate Field Order:

I will modify the React component responsible for rendering the list-type report field to ensure the Initial value option appears after the List values. This will involve a careful restructuring of the JSX to guarantee the desired order is achieved.
Improving List Values Display:

To ensure that the List values are displayed correctly as a comma-separated list without truncation, I will update the CSS/styling. This will involve implementing a wrapping mechanism that maintains readability and presentation integrity, even when the values exceed the container width.
Proposed Technical Solution:
Component Restructuring:
Locate and adjust the relevant component file to place the Initial value option after the List values. This ensures logical and user-friendly field arrangement.
Styling Adjustments:
Update the CSS to prevent truncation and enable wrapping of List values. The goal is to enhance readability and ensure that the comma-separated values are clearly displayed across all device sizes.
Implementation Plan:
Component File Update:

Adjust the JSX structure in the React component.
<ListValuesComponent />
<InitialValueComponent />


Apply CSS to ensure proper wrapping.

..list-values {
    white-space: normal;
    word-wrap: break-word;
}

Testing:

Conduct comprehensive unit and visual tests across all platforms to verify the correctness and usability of the changes.
Provide detailed screenshots and test cases to demonstrate the solution’s effectiveness.

Why I am the Right Fit:

Experience: With a strong background in React Native and UI/UX design, I have successfully delivered numerous projects that required meticulous attention to detail and robust cross-platform compatibility.
Commitment to Quality: I am dedicated to ensuring that my contributions meet the highest standards of quality and reliability, aligning with Expensify’s reputation for excellence.
Collaborative Approach: I value clear communication and collaboration, ensuring that I work seamlessly with your team to integrate the solution efficiently.
I have reviewed the Expensify Contributor Guidelines and am fully prepared to adhere to all standards and practices outlined. My proposal is detailed on the GitHub issue as requested, and I am eager to discuss how my skills and experience align with your needs further.

Thank you for considering my application. I look forward to the possibility of contributing to Expensify's continued success and helping to advance your migration project.

Best regards,
Muhammad Rafay khan

**Comment by rafaykr** [comment]
contributor details
expensify account email:[kamham56@gmail.com](mailto:kamham56@gmail.com)
upwork account : https://www.upwork.com/freelancers/~01510f6bfd2680dd92

Dear Hiring Manager,

I am excited to submit my proposal for the React Native developer position to assist with the migration project at Expensify. As a seasoned full-stack developer with a strong focus on mobile application development and user experience, I am confident in my ability to address the challenges outlined in GitHub issue https://github.com/Expensify/App/issues/45990.

Expensify’s commitment to maintaining a reliable and secure system for processing financial transactions is commendable, and the goal of unifying the front-end across platforms using React Native is a strategic move towards enhancing user experience and operational efficiency. I am eager to contribute to this mission and help ensure that your platform remains at the forefront of innovation in the financial sector.

Addressing Your Needs:
Ensuring Accurate Field Order:

I will modify the React component responsible for rendering the list-type report field to ensure the Initial value option appears after the List values. This will involve a careful restructuring of the JSX to guarantee the desired order is achieved.
Improving List Values Display:

To ensure that the List values are displayed correctly as a comma-separated list without truncation, I will update the CSS/styling. This will involve implementing a wrapping mechanism that maintains readability and presentation integrity, even when the values exceed the container width.
Proposed Technical Solution:
Component Restructuring:
Locate and adjust the relevant component file to place the Initial value option after the List values. This ensures logical and user-friendly field arrangement.
Styling Adjustments:
Update the CSS to prevent truncation and enable wrapping of List values. The goal is to enhance readability and ensure that the comma-separated values are clearly displayed across all device sizes.
Implementation Plan:
Component File Update:

Adjust the JSX structure in the React component.

Apply CSS to ensure proper wrapping.

..list-values {
white-space: normal;
word-wrap: break-word;
}

Testing:

Conduct comprehensive unit and visual tests across all platforms to verify the correctness and usability of the changes.
Provide detailed screenshots and test cases to demonstrate the solution’s effectiveness.

Why I am the Right Fit:

Experience: With a strong background in React Native and UI/UX design, I have successfully delivered numerous projects that required meticulous attention to detail and robust cross-platform compatibility.
Commitment to Quality: I am dedicated to ensuring that my contributions meet the highest standards of quality and reliability, aligning with Expensify’s reputation for excellence.
Collaborative Approach: I value clear communication and collaboration, ensuring that I work seamlessly with your team to integrate the solution efficiently.
I have reviewed the Expensify Contributor Guidelines and am fully prepared to adhere to all standards and practices outlined. My proposal is detailed on the GitHub issue as requested, and I am eager to discuss how my skills and experience align with your needs further.

Thank you for considering my application. I look forward to the possibility of contributing to Expensify's continued success and helping to advance your migration project.

Best regards,
Muhammad Rafay khan

**Comment by dannymcclain** [comment]
>Part of me thinks that trimming to 4-5 lines makes sense here in case the list is insanely long.

>I definitely think we should cap it, these imported lists of customers/projects can be very long.

Yeah I agree. After seeing the super mega long one, I don't really see a whole lot of value gained by NEVER truncating. At a certain point the huge push input list is just not helpful. I think capping at 4-5 lines is good.

**Comment by nkdengineer** [comment]
> I think capping at 4-5 lines is good.

Updated proposal https://github.com/Expensify/App/issues/45990#issuecomment-2244784255 with new design.

**Comment by JmillsExpensify** [comment]
Not passionate about truncating.

**Comment by mountiny** [comment]
This can be separate

$250 to @Krishna2323 and to @shubham1206agra please @muttmuure

**Comment by muttmuure** [comment]
@Krishna2323 has indeed been paid

**Comment by muttmuure** [comment]
@shubham1206agra I need you to accept the offer https://www.upwork.com/nx/wm/offer/103272331

**Comment by muttmuure** [comment]
@rushatgabhane - $250 C+

**Comment by muttmuure** [comment]
Paid

**Comment by muttmuure** [comment]
@rushatgabhane can request in ND using the summary above https://github.com/Expensify/App/issues/45990#issuecomment-2304378754

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane based on[ this summary.](https://github.com/Expensify/App/issues/45990#issuecomment-2304378754)
