### ISSUE TITLE
Thread - App signs out user after leaving thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46007]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4753349
**Email or phone of affected tester (no customers):** bezawitgebremichael+kk@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new account (Must be a new account)
3. Open a chat
4. Send a message
5. Click on reply in thread
6. Send a message
7. Click on header
8. Click on leave

## Expected Result:
App stays signed in

## Actual Result:
App signs out user if a user with a new account clicks on leave thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1789d6dc-784d-4584-91d4-f93315a67f74

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by izarutskaya** [comment]
Production 

https://github.com/user-attachments/assets/17de6eb7-065d-42d4-9cbd-ddbe2f129f8f

**Comment by puneetlath** [comment]
I don't think this is a blocker, though we should decide what we want the behavior to be when an unvalidated user takes this action.

**Comment by puneetlath** [comment]
I'm going to go ahead and close this. We're working on updating the unvalidated user flow and this is pretty edge-case, so I don't think it's worth the time right now.
