### ISSUE TITLE
[HOLD for payment 2024-08-02] [LOW] [Performance] Improve the perfomance of  getAllReportTransactions

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#46011]
### Problem

In the getAllReportTransactions we are:
-  filtering twice unnecessarily
- converting to string always even if the both values should be already strings

From @TMisiukiewicz:

Since none of my accounts is fully packed with transactions, I was not able to say exactly how much performance gain it’d bring. Two things are happening in this PR:

### Solution

- make the function call filter just once instead of twice
- remove parsing reportID to string - it was a workaround because some time ago backend was returning reportID as number for newly created transactions, but now looks like it works good, so I think it should be safe to remove this workaround
I tested it on 10k of fake transactions and first point gave me ~15% of improvement, but combined with removed parsing it’s around 60% faster.

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by mountiny** [comment]
cc @TMisiukiewicz

**Comment by TMisiukiewicz** [comment]
hi, I'm Tomasz from Callstack and i'd like to be assigned to this issue

**Comment by dylanexpensify** [comment]
anything needed here, or good to close out @mountiny?
