### ISSUE TITLE
NetSuite - Wrong Auto-Sync value is shown at initial connection time. Steps

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46023]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shubham1206agra 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721714017738619

## Action Performed:

1. Make the connection to NetSuite under workspace accounting.
2. Open the Advanced section and observe the Auto-Sync toggle.

## Expected Result:
The toggle should show on.
## Actual Result:
The toggle shows off.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2024-07-23 at 11 23 26 AM](https://github.com/user-attachments/assets/451cdab6-8c6d-419d-a117-c2288e1b6ddb)

![Snip - (54) New Expensify - Google Chrome (3)](https://github.com/user-attachments/assets/2f181e7c-8a4b-4ebe-95d2-0f2a21154760)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
Assigned @yuwenmemon  as per this `https://expensify.slack.com/archives/C049HHMV9SM/p1721714055969359?thread_ts=1721714017.738619&cid=C049HHMV9SM`

**Comment by yuwenmemon** [comment]
This has been deployed, closing!
