### ISSUE TITLE
[HOLD for payment 2024-08-07] [$250] [Search v2.1] [App] Create Status filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46029]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Status filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e54a65bdd0691b22</li>
        <li>Upwork Job ID: 1817956434338446987</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by luacmartins** [comment]
@Kicu is already working on this one

**Comment by Kicu** [comment]
hey yes, I _am_ working on this already 😄 in this draft  https://github.com/Expensify/App/pull/46022

**Comment by VictoriaExpensify** [comment]
Hey @rayane-djouah - I'm having trouble finding you in Upwork to make you an offer. Can you add your proposal to the job listing so I can hire you? https://www.upwork.com/jobs/~01e54a65bdd0691b22 

Or, let me know your name in Upwork so I can invite you to the job

**Comment by VictoriaExpensify** [comment]
Thanks @rayane-djouah - let me know once you have accepted the offer - https://www.upwork.com/offer/103457864

**Comment by VictoriaExpensify** [comment]
**Payment Summary**
Contributor: @Kicu is from an agency-contributor and not due payment
ROLE: @rayane-djouah paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/103457864)

**Comment by VictoriaExpensify** [comment]
Payments are all done and dusted; thanks for your work @Kicu and @rayane-djouah !
