### ISSUE TITLE
[Search v2] [App] Create Type filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46028]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Type filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163

**Comment by luacmartins** [comment]
@Kicu is already working on this one!

**Comment by joekaufmanexpensify** [comment]
Sounds good! @Kicu mind commenting here so we can assign you, and linking the PR (if there is one)

**Comment by Kicu** [comment]
hey yes, I _am_ working on this already 😄 in this draft  https://github.com/Expensify/App/pull/46022

**Comment by joekaufmanexpensify** [comment]
Sweet, TY! Linked this issue to that PR too.

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by luacmartins** [comment]
I'm gonna close this issue since we'll handle payment in https://github.com/Expensify/App/issues/46029

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY!
