### ISSUE TITLE
[$250] [Search v2.1] [App] Create Description filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46034]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Description filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163

<details><summary>Issue Owner</summary>Current Issue Owner: @SzymczakJ</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194719adc118b8dc6</li>
        <li>Upwork Job ID: 1817944095935383738</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103311791</li>
</ul></li>
    </ul>
</details>

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by luacmartins** [comment]
All yours @SzymczakJ

**Comment by luacmartins** [comment]
Sounds good. I think we can close this issue in favor of https://github.com/Expensify/App/issues/46032
