### ISSUE TITLE
[HOLD for payment 2024-08-02] [Search v2.1] [App] Create Date filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46033]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Date filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by luacmartins** [comment]
@Guccio163 already has a PR in review for this one!

**Comment by luacmartins** [comment]
@Guccio163 can you please comment on this issue so I can assign it to you?

**Comment by Guccio163** [comment]
Hey, I'm a developer from Software Mansion and I'm currently working over this PR, please assign it to me!

**Comment by slafortune** [comment]
@rayane-djouah Role C+ due $250 - offer sent here - https://www.upwork.com/nx/wm/offer/103373950
@Guccio163 does not require payment (Contractor)
