### ISSUE TITLE
[HOLD for payment 2024-09-03][$250] [Search v2.1] [App] Create Amount filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46036]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Amount filters only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a66609e4336f130d</li>
        <li>Upwork Job ID: 1816128795512826715</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103317744</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by WojtekBoman** [comment]
Hi! I'd like to work on this issue :)

**Comment by trjExpensify** [comment]
SOLD!

**Comment by WojtekBoman** [comment]
@luacmartins What should a page with this filter look like? Amount filter is a range, so we can handle it by having two inputs (from and to) on the page, do you think it will be ok or should we handle it in a different way?

**Comment by luacmartins** [comment]
@Expensify/design do we have any mocks for this page?

**Comment by dubielzyk-expensify** [comment]
> @Expensify/design do we have any mocks for the amount filter page?

I don't see any, but I'd assume we'd use the big number pad pattern here (left) instead of the less common text input (rigth):

![CleanShot 2024-07-30 at 10 06 39@2x](https://github.com/user-attachments/assets/d2253eaa-30ef-463d-aa4c-a16375b58e25)

Keen to hear if @shawnborton agrees.

**Comment by shawnborton** [comment]
Based on @WojtekBoman's comment here:

> Amount filter is a range, so we can handle it by having two inputs (from and to) on the page, do you think it will be ok or should we handle it in a different way?

We might want to do something like this?

![CleanShot 2024-07-30 at 08 50 53@2x](https://github.com/user-attachments/assets/48c7c40c-86a1-4de1-9af4-52310f3068e9)

![CleanShot 2024-07-30 at 08 51 02@2x](https://github.com/user-attachments/assets/9c0e8048-3395-4f14-a450-4d61e922bfa0)

![CleanShot 2024-07-30 at 08 50 36@2x](https://github.com/user-attachments/assets/cd7e2a9f-3c32-4b00-b017-bd552abe69a5)

**Comment by dubielzyk-expensify** [comment]
Ahh, missed the range. That seems great then. I assume this assumes a currency (workspace!?)? If so, I'd love to have the currency at the start of the input field.

**Comment by Kicu** [comment]
Currency is designed as a separate filter, so you would see chosen currency on the main list of filters (the leftmost screen)

**Comment by dubielzyk-expensify** [comment]
Ahh right. Personally I think it would still be neat to have the currency in the input field. Or stated above it. But just a minor comment :)

**Comment by Kicu** [comment]
It should be pretty easy to do so in the code I think

**Comment by dubielzyk-expensify** [comment]
Would be cool if we can use the same type of component that's used for setting name for rooms:
![CleanShot 2024-07-30 at 19 01 32@2x](https://github.com/user-attachments/assets/9b374572-f8e4-42d9-a20c-9aadbf6c6868)

**Comment by luacmartins** [comment]
I think right now users might be able to select multiple currencies, I wonder if we should limit that.

**Comment by shawnborton** [comment]
I like the idea of a prefixed input that has the current currency.

**Comment by shawnborton** [comment]
Oh hmm good point... I don't know if we need to limit the amount of currencies selected, so maybe we should just leave these inputs as numerical inputs without a symbol?

**Comment by JmillsExpensify** [comment]
Yes, we shouldn't limit the currencies selected. I like sticking with amount.

**Comment by trjExpensify** [comment]
Are we all clear here on the next steps?

**Comment by luacmartins** [comment]
Yea, I think so. We'll use a text input for the amount.

**Comment by trjExpensify** [comment]
Okay, sounds good!

**Comment by trjExpensify** [comment]
@WojtekBoman, are you working on this?

**Comment by SzymczakJ** [comment]
I'll take this from Wojtek after I fix PR comments on https://github.com/Expensify/App/pull/46736, as Wojtek just started a new Expensify project.

**Comment by trjExpensify** [comment]
PR is on staging.

**Comment by trjExpensify** [comment]
Chill Melv, payment isn't due.

**Comment by luacmartins** [comment]
Payment is due

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @rayane-djouah for the C+ review. 

Paid, closing.
