### ISSUE TITLE
[HOLD for payment 2024-08-13] [$250] [Search v2.1] [App] Create Category filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46038]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Category filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144ce32afe4e5afaa</li>
        <li>Upwork Job ID: 1816128900858619869</li>
        <li>Last Price Increase: 2024-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 103264624</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by 289Adam289** [comment]
Hi! I noticed that each policyID has its own list of categories, but the search is global. What categories should be included on the category page? And should it allow for multiple categories to be selected at once?

**Comment by luacmartins** [comment]
@289Adam289 great questions. I think the behavior should be:

1. If no policy is selected (via the workspace switcher), show all categories we have in Onyx for all categories
2. If a policy is selected, show only categories for that policy
3. Yes, we should allow multi-select

**Comment by ikevin127** [comment]
@luacmartins Should I try and come up with a regression test for this specific issue or will this be done later when the new search is completed ?

**Comment by luacmartins** [comment]
No, we'll add it as part of the project wrap up

**Comment by ikevin127** [comment]
cc @stephanieelliott

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @ikevin127 $250 via Upwork -- PAID 
 - Contributor+: @289Adam289 no payment due/agency 
 
 Upwork job is here: https://www.upwork.com/jobs/~0144ce32afe4e5afaa
