### ISSUE TITLE
[PAID] [$250] [Search v2.1] [App] Create Merchant filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46032]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Merchant filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef7bc40a6c8da319</li>
        <li>Upwork Job ID: 1817944284206858054</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by luacmartins** [comment]
All yours @SzymczakJ!

**Comment by ikevin127** [comment]
@luacmartins Should I try and come up with a regression test for this specific issue or will this be done later when the new search is completed ?

**Comment by luacmartins** [comment]
No, we'll add them as part of the project wrap up

**Comment by ikevin127** [comment]
cc @strepanier03

**Comment by strepanier03** [comment]
Contract accepted, paid, and closed - thanks @ikevin127 🙌 

Closing this out now, thanks all!
