### ISSUE TITLE
[PAID] [$250] [Search v2.1] [App] Create From and To filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46035]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the `From` and `To` filters only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c6f76a94b99da45</li>
        <li>Upwork Job ID: 1817956261765409818</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by Kicu** [comment]
hello, I would like to work on this filter next, since my other PRs are almost done. Please assign me

**Comment by Kicu** [comment]
whoever knows if from + to filters should be allow multi selection of people?
@luacmartins @JmillsExpensify @shawnborton 

And I'm assuming it should look the same as our other people pickers? 
![Screenshot 2024-07-31 at 14 11 05](https://github.com/user-attachments/assets/15ad224e-fbf9-4354-bb01-f522634ceaef)

**Comment by luacmartins** [comment]
@Kicu yes, it should allow multi-select. The filters that allow multi-select can be found [here in the doc](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.uc2nmzem4elv)

**Comment by luacmartins** [comment]
and yes, it should look like the current contact selector

**Comment by Kicu** [comment]
woorkiiiing on this

**Comment by luacmartins** [comment]
@CherylWalsh actually, we don't need the copy since we decided to remove the sections altogether.

**Comment by bfitzexpensify** [comment]
Thanks for the heads up @rayane-djouah. 

I'll be out of office on the 26th - adding in a BZ buddy.

**Comment by strepanier03** [comment]
### Payment Summary

- $250 - @rayane-djouah via Upwork ([offer](https://www.upwork.com/nx/wm/offer/103707694))

I believe this is accurate, and no one else needs to be paid, but please correct me if I'm wrong, and I'll update.

**Comment by strepanier03** [comment]
I'll come back to this in the afternoon and check.

**Comment by strepanier03** [comment]
I've paid and closed the contract. Thanks all!
