### ISSUE TITLE
[$250] [Search v2.1] [App] Create Expense type filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46037]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Expense type filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ef0d858fc265ff3</li>
        <li>Upwork Job ID: 1817956794924362778</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @SzymczakJ</details>

**Comment by OfstadC** [comment]
Looking at this now...

**Comment by OfstadC** [comment]
@luacmartins Fairly new to BZ - to make sure I understand. Do you want this assigned Externally?

**Comment by luacmartins** [comment]
This will be external, but someone from SWM will pick this up. So for now, let's just wait for one of the people cc'ed in the OP to comment here so we can assign the issue to them.

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!
First question from me: what exactly is an expense type? I've read the design doc and I don't see any explanation of this. Is it like 'distance expense', 'receipt expense' and 'manual expense'?

**Comment by luacmartins** [comment]
@SzymczakJ these are the possible types - https://github.com/Expensify/App/blob/410a6f21524ddc1a4f85fbf9f922c6bc21d7e502/src/CONST.ts#L5239-L5242

**Comment by SzymczakJ** [comment]
Work in progress 😄

**Comment by SzymczakJ** [comment]
I need to refactor one thing to unify filters(currency, category, expense type, tag, tax) this PR should come out of draft tommorow!

**Comment by SzymczakJ** [comment]
Is backend for this filter working? I'm trying URLs like `https://dev.new.expensify.com:8082/search?q=expenseType%3Acash&isCustomQuery=true` and get all reports even the **distance** type ones.
This is my query from my payload:
<img width="504" alt="Screenshot 2024-08-07 at 14 21 30" src="https://github.com/user-attachments/assets/d3b93b7c-e0ed-460e-b671-4f5e888028ef">
Am I doing something wrong?
@carlosmiceli

**Comment by luacmartins** [comment]
@SzymczakJ not yet, I'm working on it right now.

**Comment by SzymczakJ** [comment]
Sorry for mentioning wrong Carlos 😅

**Comment by luacmartins** [comment]
Correct!

**Comment by luacmartins** [comment]
Payment will be handled via https://github.com/Expensify/App/issues/46041
