### ISSUE TITLE
[$250] [Search v2.1] [App] Create Card filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46042]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Card filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182e0beb35c4f29b0</li>
        <li>Upwork Job ID: 1817956624064923280</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @289Adam289</details>

**Comment by 289Adam289** [comment]
Hi! I'm from SWM and I would like to work on this issue.

**Comment by ikevin127** [comment]
Not overdue -> **289Adam289** is working on the [PR](https://github.com/Expensify/App/pull/46666) (currently `Draft`).

**Comment by luacmartins** [comment]
PR is merged

**Comment by abekkala** [comment]
[PR](https://github.com/Expensify/App/pull/46666) - deployed to **staging** Aug 05
- Fix @289Adam289 [SWM] 
- PR Review: @ikevin127

**Comment by ikevin127** [comment]
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-08-14]** according to first production deploy from 3 days ago (7th of August) (see [reference](https://github.com/Expensify/App/pull/46666#issuecomment-2274429196) of deploy).

cc @abekkala @luacmartins for confirmation!

**Comment by luacmartins** [comment]
@ikevin127 it seems like we're handling payment on https://github.com/Expensify/App/issues/46827?

**Comment by ikevin127** [comment]
@luacmartins Correct, this one can be closed I think.
