### ISSUE TITLE
[HOLD for Payment 2024-08-22] [$500] [Search v2.1] [App] Create Tax Rate filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46041]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Tax rate filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018120ea21b175e8b2</li>
        <li>Upwork Job ID: 1817958358422210192</li>
        <li>Last Price Increase: 2024-08-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!
First question from me: how should this filter look like? Should it be a list of reportIDs, that can be selected? My second thought to it is that: are reportIDs a good thing to filter over(I mean I doubt that any user will remember a report ID like '12319802419'), shouldn't we use more descriptive/human readable values that represent reportID?

**Comment by luacmartins** [comment]
All yours @SzymczakJ!

**Comment by SzymczakJ** [comment]
Work in progress 😄

**Comment by SzymczakJ** [comment]
I need to refactor one thing to unify filters(currency, category, expense type, tag, tax) this PR should come out of draft tommorow!

**Comment by SzymczakJ** [comment]
Same question as on Expense type issue: Is backend working? What is the value that we should give to backend to find Tax? Should it be something like tax key in `taxRates.taxes` object? @luacmartins 
<img width="315" alt="Screenshot 2024-08-07 at 14 37 19" src="https://github.com/user-attachments/assets/01737075-719c-4b84-b9c1-e426c2b6d1fc">
I have a feeling that I should have asked these questions earlier 😄

**Comment by luacmartins** [comment]
Replied in Slack, but the answer is:

1. Backend PR with these filters is merged, pending deploy
2. expenseTypes: `card`, `cash`, `distance` are the values
3. taxRate: the object key is the correct value to send to the API

**Comment by greg-schroeder** [comment]
@SzymczakJ are you good to go on this one or is there anything still unclear?

**Comment by luacmartins** [comment]
Yup, PR is in staging, just waiting for prod deploy

**Comment by luacmartins** [comment]
>Per the processes outlined [here](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit#bookmark=id.1riurmfnl9o5) and [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1721843458370249?thread_ts=1721843446.947239&cid=C02NK2DQWUX), @greg-schroeder, I propose raising the reward for this issue to $500, given that the https://github.com/Expensify/App/pull/46736 addressed three issues (https://github.com/Expensify/App/issues/46041, https://github.com/Expensify/App/issues/46037, and https://github.com/Expensify/App/issues/46040) and required more reviewing work. Thanks.

That's fine with me.

Bump @greg-schroeder for payment

**Comment by greg-schroeder** [comment]
Apologies, I was leading an interview all day 8/22 and was OOO 8/23. Processing now

**Comment by greg-schroeder** [comment]
@rayane-djouah Sent an offer for $500, I'll pay you ASAP as soon as you accept!

**Comment by greg-schroeder** [comment]
paid
