### ISSUE TITLE
[Search v2.1] [App] Create ReportID filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46043]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the ReportID filter only!

cc @adamgrzybowski @Kicu @WojtekBoman @Guccio163

**Comment by dylanexpensify** [comment]
Nice! 👍

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!
First question from me: how should this filter look like? Should it be a list of reportIDs, that can be selected? My second thought to it is that: are reportIDs a good thing to filter over(I mean I doubt that any user will remember a report ID like '12319802419'), shouldn't we use more descriptive/human readable values that represent reportID?

**Comment by luacmartins** [comment]
@Expensify/design do we have a mock for the reportID filter page?

**Comment by dubielzyk-expensify** [comment]
Assuming this is just a text string, then I recon it's something like this:
![CleanShot 2024-07-30 at 10 58 16@2x](https://github.com/user-attachments/assets/93ce6a60-07a5-4f2b-a392-786a0c1e794d)

Keen to hear if @shawnborton or @JmillsExpensify agrees or not

**Comment by shawnborton** [comment]
Yup, that's exactly what I was thinking - looks good to me!

**Comment by luacmartins** [comment]
Closing in favor of https://github.com/Expensify/App/issues/46032
