### ISSUE TITLE
Desktop - App - App font is different on staging

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46048]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify desktop app
2. Log in
3. Navigate through the app

## Expected Result:
The font will be the same as the font on prod

## Actual Result:
The app font is different on staging

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/92c9d87d-9caa-47d9-9971-afa8e88e91ac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by francoisl** [comment]
Hmm weird. I can reproduce the issue. On the production app, if you look at the Preview tab of the request to load the fonts, it will display an actual preview of the fonts:
<img width="500" alt="Screenshot 2024-07-23 at 12 49 22 PM" src="https://github.com/user-attachments/assets/5e25042b-311d-476d-9b81-553b52feedb6">

On the staging app, it shows some garbled stuff, like the font was corrupted or interpreted in the wrong content-type
<img width="500" alt="image" src="https://github.com/user-attachments/assets/a056812e-e99b-4867-9572-6db2e70b2627">

**Comment by francoisl** [comment]
Ah yes, it does appear to be a Content-Type issue. Staging interprets it as `text/html` vs `application/octet-stream` for prod

<img width="400" alt="image" src="https://github.com/user-attachments/assets/c6805ac4-225d-4026-823a-63060592737e"><img width="400" alt="image" src="https://github.com/user-attachments/assets/93b613ad-eee9-4b55-b0d5-626fdeb53eda">


At first glance, nothing in the checklist looks out of the ordinary that could explain this.

**Comment by francoisl** [comment]
I think this is coming from https://github.com/Expensify/App/pull/44432/, that PR modified a bunch of stuff in `desktop/`. I tried an ad-hoc build after reverting it on [this PR](https://github.com/Expensify/App/pull/46070) and it resolves the issue.

https://ad-hoc-expensify-cash.s3.amazonaws.com/desktop/46070/NewExpensify.dmg

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/382ed579-1dc7-471f-9f0f-ff3ac49505b1">

**Comment by francoisl** [comment]
cc @kirillzyusko @jayeshmangwani if you have any ideas about the above.
