### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Netsuite - App crashes when "Custom form ID" in advanced is enabled in Netsuite connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisite
Netsuite connection is established in the workspace
1. Navigate to the workspace which is connected to NetSuite
2. Go to accounting > Advanced
3. Scroll down and enable "Custom form ID" toggle

## Expected Result:
Custom form ID toggle is enabled

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fc41337a-90c8-4e71-81c7-8a9800a2eda5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee02ffe353f11647</li>
        <li>Upwork Job ID: 1815839907705061236</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103252072</li>
<li>ShridharGoel | Contributor | 103252075</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment]
I can reproduce this with the steps in the OP - I believe this relates to Wave Control

**Comment by yuwenmemon** [comment]
Sure since this is your regression @shubham1206agra

**Comment by Christinadobrzyn** [comment]
Update for Melvin - PR is in the works

**Comment by Christinadobrzyn** [comment]
Payouts due:

- [ ] Contributor: $250 @ShridharGoel (Upwork offer - https://www.upwork.com/nx/wm/offer/103252075)
- [ ] Contributor+: $250 @shubham1206agra (Pending Upwork offer - https://www.upwork.com/nx/wm/offer/103252072)

@shubham1206agra can you accept the Upwork offer and also let us know if we need a regression test?

**Comment by Christinadobrzyn** [comment]
Payday - I paid out in Upwork based on this payment summary - https://github.com/Expensify/App/issues/46062#issuecomment-2272239481

No regression test, so this can be closed!
