### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] [Payment card / Subscription] add UI for SCA error banner and re-authentication flow

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#46064]
_If you don't know what SCA is, it stands for [strong customer authentication](https://stripe.com/guides/strong-customer-authentication), and is an extra authentication step that we use for users who add billing cards with `GBP` as their payment currency. You don't need to know about SCA in depth in order to work on this issue._

https://github.com/Expensify/App/issues/42432 added the most straightforward use case of adding a payment card via the SCA flow and having the authentication succeed, but we are stilling lacking an error banner when authentication doesn't succeed. We also need to give the user a way to authenticate again if authentication fails.

When a user goes through the SCA authentication in new dot right now and purposely fails the authentication this is what happens:

https://github.com/user-attachments/assets/bf26e4f8-bf42-4a73-9a09-dcba336e9f09

This is wrong. The UI makes it seem like the payment card is ready to be used and is fine, when its actually not fine. We should be showing the following UI with the error banner and "Authenticate payment" button.

![Image](https://github.com/user-attachments/assets/e5ce42b6-d7e4-425b-b3c8-5bf62c0e1faf)

Clicking "Authenticate payment" should open up the right-docked add payment card pane with and also open up the iframe authentication model (`src/pages/settings/Subscription/CardAuthenticationModal/index.tsx`), restarting the authentication process.

The tricky thing about this issue is that its not possible for non-expensify engineers to test end to end, so you will be working closely with @blimpich to ensure this is working as intended.

The error banner should show when the onyx key `nvp_private_stripeCustomerID` has its `status` attribute equal to `"authentication_required"`.

[Relevant section of design doc](https://docs.google.com/document/d/1jXV_vIsOGZuL0dMiuXDWRETAFRX64ODVAhWPtiuFXT8/edit?pli=1#heading=h.qvdvkblarupg). This doc also has the approved Spanish translations necessary to complete this. Please message @blimpich if you do not have access to this document and would like access, and make sure to include your email address.

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by waterim** [comment]
Hello Im Artem from Callstack and would like to work on this issue

**Comment by blimpich** [comment]
Added @mananjadhav because they are the C+ review the PR. Chose them since they have good context with subscription page.

**Comment by twisterdotcom** [comment]
Is this still waiting on @waterim?

**Comment by waterim** [comment]
This one is under development already

**Comment by blimpich** [comment]
Yeah this one is kind of special because the feature can't be fully tested by @waterim locally, so I'm testing it and providing feedback while @waterim works on it. This flow slows us down but I'm simultaneously working on code that will make @waterim and all contributors able to test this flow with just an engineer's ngrok credentials.

**Comment by blimpich** [comment]
@waterim I think you should be able to use my ngrok and test the full flow for 3ds verification. Let me know if you have any issues 🙂

**Comment by mananjadhav** [comment]
I'll start reviewing this soon.

**Comment by blimpich** [comment]
No regression tests needed, its a new feature, we have manual tests already written for this.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @waterim **does not** require payment (Contractor)

**Comment by twisterdotcom** [comment]
Payment Summary:

- @mananjadhav paid $250 via NewDot Manual Request
- @waterim **does not** require payment (Contractor)

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
