### ISSUE TITLE
[HOLD for payment 2024-08-05] [TS] Memoize utility instance lacks typings for cache property

### ISSUE THREAD

**Issue by kacper-mikolajczak** [Expensify/App#46069]
### Details
_This is a known regression, which originates from https://github.com/Expensify/App/pull/43868_

Instance of `memoize` module lacks correct typings for `cache` property. Methods of cache (`get`, `set`, etc.) have `key` parameter typed as `unknown`.

#### Steps to reproduce

1. Create an instance of `memoize` by calling `memoize` method
3. Check the typings of `cache` property methods on the instance

#### Expected behaviour

`key` argument in cache methods matches arguments of memoized function

#### Actual behaviour

`key` argument is set to `unknown`

<img width="650" alt="Screenshot 2024-07-23 at 22 03 03" src="https://github.com/user-attachments/assets/0527ecee-5d68-4a08-a58d-c61a0f4cf3ad">

**Comment by kacper-mikolajczak** [comment]
I will work on this!

**Comment by kacper-mikolajczak** [comment]
I think we can close this one, right @mountiny?

**Comment by mountiny** [comment]
Yep, thanks!
