### ISSUE TITLE
Search - Unable to hold expense from Search and console error shows up after trying to hold it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46061]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Go to Search
5. Click on the checkbox of the submitted expense
6. Click on the dropdown
7. Click Hold
8. Enter reason and save it
9. Click on the transaction on Search to open RHP

## Expected Result:
The expense is held successfully when held via Search

## Actual Result:
User is unable to hold expense when held via Search. Console error shows up after holding the expense and opening the RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b41c5387-fe1f-40ab-b2aa-daa3b103c5b3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by aldo-expensify** [comment]
Following the steps, I get stuck with the search loading forever:

<img width="1720" alt="image" src="https://github.com/user-attachments/assets/efb7ae24-4b93-4205-8c48-4d98ef0e9a96">

**Comment by aldo-expensify** [comment]
Ah, going back and going to the search again fixed it

**Comment by aldo-expensify** [comment]
the request is erroring when clicking "Hold":

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/57f248db-2a5a-4b3c-9781-60b66f5282bd">

**Comment by aldo-expensify** [comment]
Seems like the backend PR adding this command has not been deployed yet: https://github.com/Expensify/Web-Expensify/pull/42733

@luacmartins what do you think we should do? Seems like this functionality should have been put on HOLD until the backend is ready... but now that we are here, I guess we can just remove the deploy blocker, we will soon have the backend PR deployed anyway.

**Comment by francoisl** [comment]
But then if we deploy App to production while the Web-E PR is still on staging, we'll have this issue again but on production. The ideal solution would be to CP that Web-E PR to staging and then prod IMO.

**Comment by luacmartins** [comment]
Oops there was a bit of a timing issue here. I agree with @francoisl we should just CP the web-e PR to prod. It's pretty low risk since it just adds a proxy to the Auth command.

**Comment by aldo-expensify** [comment]
Sounds good!

**Comment by luacmartins** [comment]
CP done and issue is fixed

https://github.com/user-attachments/assets/99642061-d4e4-4a26-89e1-3cd386e7d944
