### ISSUE TITLE
[Search v1] Implement PayMoneyRequestOnSearch command

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46074]
Implement [this section](https://docs.google.com/document/d/1ldZ85fyQO4662hLZRNFfm0_IxaP7-PWvaqc8Z33jsLQ/edit#bookmark=id.kt71e0n7yfsm) of the doc for the Pay command only

**Comment by lschurr** [comment]
Anything needed from BZ right now @luacmartins?

**Comment by luacmartins** [comment]
Np! This is internal. I'll unassign you since there's no need for BZ.

**Comment by luacmartins** [comment]
No updates yet. I'll start working on it this week.

**Comment by luacmartins** [comment]
Prioritizing other Search v2 issues.

**Comment by luacmartins** [comment]
Prioritizing other Search v2.1/2.2 issues. This is still partially on hold since it depends on nextSteps in Auth

**Comment by luacmartins** [comment]
Still on hold

**Comment by luacmartins** [comment]
Prioritizing other Search v2.1/2.2 issues. This is still partially on hold since it depends on nextSteps in Auth

**Comment by luacmartins** [comment]
On hold

**Comment by luacmartins** [comment]
same

**Comment by luacmartins** [comment]
same

**Comment by lakchote** [comment]
Not overdue, Auth [PR](https://github.com/Expensify/Auth/pull/12930) is in review.

**Comment by luacmartins** [comment]
We can close this issue. I'll handle hooking the command up in App as part of https://github.com/Expensify/App/issues/51898
