### ISSUE TITLE
Search - Hold option is present for expense that is still scanning on Search page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46078]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a scan expense
4. Go to transaction thread
5. Click on the report header
6. Note that Hold option is not present when the receipt is still scanning
7. Go to Search
8. Select the scanning expense
9. Click on the dropdown

## Expected Result:
Hold option will not be present for expense that is still scanning

## Actual Result:
Hold option is present for expense that is still scanning on Search page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c77f40cb-028b-4c4d-8593-e986f43f165c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stitesExpensify** [comment]
@luacmartins looks like you have been working on this feature. Would you mind taking over this issue?

**Comment by luacmartins** [comment]
Sure I can work on this

**Comment by luacmartins** [comment]
I don't think this is a blocker. Worst case the request to Hold will fail and users might be slightly confused. Next, it seems like we have a bunch of [conditions in App](https://github.com/Expensify/App/blob/cd14a035095e8ace627d125db931d0c90408f898/src/libs/ReportUtils.ts#L2839) that are not enforced by the API. I think we should enforce these in the API as well so I'll work on a PR to add this conditions to Auth. cc @robertjchen

**Comment by stitesExpensify** [comment]
Makes sense to me. Thanks!

**Comment by luacmartins** [comment]
PR in review
