### ISSUE TITLE
[$250] mWeb – Chat – Blue frame appears around Back button if navigate via search to Concierge chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46075]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with Gmail account
3. Click on Find
4. Enter Concierge and select a Concierge chat

## Expected Result:
Concierge chat opens without blue frame around Back button

## Actual Result:
Concierge chat opens with blue frame around Back button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8366016e-954b-4ad5-93de-884cc075408a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010dff162673cedbab</li>
        <li>Upwork Job ID: 1816906889952716440</li>
        <li>Last Price Increase: 2024-07-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by marcaaron** [comment]
This is not a deploy blocker

**Comment by tsa321** [comment]
Same root cause as : https://github.com/Expensify/App/issues/46109. cross posting my proposal: https://github.com/Expensify/App/issues/46109#issuecomment-2249101171

**Comment by abekkala** [comment]
@marcaaron can the proposal above for https://github.com/Expensify/App/issues/46109. resolve this issue as well?
