### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250]  Threads - Leaving from multilevel threads navigates to wrong thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** bezawitgebremichael+kkii@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat
3. Send a message (Name it parent message for easier observation)
4. Hover over the message and click on reply in thread
5. Send another message in the thread (Name it thread 1 for easier observation)
6. Hover over the message and click on reply in thread
7. Send another message in the thread (Name it thread 2 for easier observation)
8. Click on the header of the thread
9. Click on leave
10. Note the name of the header and click on it
11. Click on leave
12. Note the name of the header and wait a few seconds

## Expected Result:
When leaving the first level thread app navigates user to the parent thread, when leaving from the parent thread app navigates to the Original chat and no "You don't have access to this chat" page is displayed

## Actual Result:
When leaving the first level thread app navigates to the parent thread but when leaving the parent thread again the app navigates user back to the first level thread and then after a few seconds "You don't have access to this chat" page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e3859a61-2e16-4172-9b2f-cdf66ac49b09

![405](https://github.com/user-attachments/assets/a9f42067-005a-4db5-a61d-1bd0c713a715)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a17100bfa3035f8c</li>
        <li>Upwork Job ID: 1816165199632115677</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by francoisl** [comment]
Thanks for the proposals. Can you identify which PR from [the checklist](https://github.com/Expensify/App/issues/45991) introduced this issue?

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone!

@daledah's [proposal](https://github.com/Expensify/App/issues/46085#issuecomment-2247008761) has the correct RCA and fixes the root issue.

@nyomanjyotisa I think your proposal is applying a cosmetic patch, without addressing the actual underlying issue.

🎀 👀 🎀 C+ reviewed

**Comment by francoisl** [comment]
@daledah are you available to submit a PR?

**Comment by francoisl** [comment]
We had an issue with the web production deploy that caused the deploy to fail for a few days, but it's fixed now and this issue is now reproducible on production. Going to remove the deploy blocker.

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/44948/files
2. https://github.com/Expensify/App/pull/44948/files#r1713856786
3. N/A
4. A regression test would be helpful.

## Regression Test

1. Navigate to the app and Open a chat
2. Send a message (Name it parent message for easier observation)
3. Hover over the message and click on reply in thread
4. Send another message in the thread (Name it thread 1 for easier observation)
5. Hover over the message and click on reply in thread
6. Send another message in the thread (Name it thread 2 for easier observation)
7. Click on the header of the thread and click on leave
8. Note the name of the header and click on it, and click on leave

Verify that when leaving the first level thread app navigates user to the parent thread, when leaving from the parent thread app navigates to the Original chat and no "You don't have access to this chat" page is displayed

Do we 👍 or 👎 ?

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @daledah (bumping the above message - will you apply to the [Upwork Job](https://www.upwork.com/jobs/~01a17100bfa3035f8c)?)
- [ ] Contributor+: $250 @allroundexperts (NewDot)

Upwork job is [here](https://www.upwork.com/ab/applicants/1816165199632115677/hires?filter=dah&page=1).

**Comment by adelekennedy** [comment]
Bump @daledah!

**Comment by adelekennedy** [comment]
hired @daledah!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
