### ISSUE TITLE
[HOLD for payment 2024-08-14] [Workspace Feeds] Sage intacct - "Expensify Card Settlement Account" Link does not redirect

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46083]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check , New feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Access New Expensify app
2. Sign into a valid account (Beta enabled)
3. Go to Workspace > Accounting > Connect to Sage Intact
4. Go to Card Recon. > Turn toggle ON > Click on "Expensify Card Settlement Account" Link
## Expected Result:
Describe what you think should've happened

## Actual Result:
Link non functional, Nothing happens, no redirect.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/143140d0-42c1-4860-87de-e472293d9de8

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by francoisl** [comment]
Likely coming from https://github.com/Expensify/App/pull/45415 / cc @koko57 @allgandalf @MariaHCD @mountiny

**Comment by francoisl** [comment]
Pretty sure this is still behind a beta anyway, also the PR has a lot of commented out code ([example function](https://github.com/Expensify/App/pull/45415/files#diff-ae962772c4a3418dc70235b3715b5c5612065b8a9371dca5043b401b5cd83781R251)), so I imagine this is something that's still in progress and we can demote for now.

**Comment by koko57** [comment]
I can work on this issue

**Comment by greg-schroeder** [comment]
This appears to be a regression fix per [this comment](https://github.com/Expensify/App/issues/46083#issuecomment-2246499991), so I don't think any payments are due in this issue tomorrow 8/14

Correct me if I'm wrong though
