### ISSUE TITLE
Notifications - No notifications are received.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46093]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4757121
**Email or phone of affected tester (no customers):** applausetester+uo0723@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open staging.new.expensify.com on two separate devices(User A and B)
2. Using A, send messages to User B, then go another chat or back ground app with User B
3. Observe notifications

## Expected Result:
Notifications are received by User B

## Actual Result:
No notifications are received after sending messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a55a394b-14fe-49dd-8766-1cedd4548d1b

https://github.com/user-attachments/assets/392a8f25-9adb-4af7-868e-4256591b9b7a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
I can't reproduce this.
