### ISSUE TITLE
[HOLD for payment 2024-08-19] [$125] Threads - User is allowed to navigate to thread notification preference via URL

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46097]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** bezawitgebremichael+kkii@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat
3. Send a message
4. Hover over the message and click on reply in thread
5. Send another message in the thread
6. Hover over the message and click on reply in thread
7. Send another message in the thread
8. Click on the header of the thread
9. Click on settings
10. Click on "Notify me about new messages"
11. Copy the URL of the current page
12. Navigate back twice
13. Click on leave
14. Navigate back to the left thread by clicking on replies (Note the join button at the top right corner)
15. Click on header
16. Click on settings (Note that there is no "Notify me about new messages" setting anymore)
17. Paste the copied URL on the browser and navigate to it

## Expected Result:
When navigating to the copied URL the app shows "You don't have access to this" page

## Actual Result:
When navigating to the copied URL the app allows user to access the setting, but when navigating back the user no longer will have access to the setting.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/80010739-7250-4403-b8aa-44bb604b376c

![Bug6550444_1721733548315!Screenshot_2024-07-23_140303](https://github.com/user-attachments/assets/6dd8742c-1d10-4256-87ab-143a59b77fc4)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e35f1c2b15d412d</li>
        <li>Upwork Job ID: 1818434968448883106</li>
        <li>Last Price Increase: 2024-07-30</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by izarutskaya** [comment]
Production

https://github.com/user-attachments/assets/72f62931-4f82-4403-bc43-72ea6f5620b1

**Comment by francoisl** [comment]
Ok so from production you can't leave the thread, that's why it can't be reproduced there.
Sounds like an edge case we can polish later, you have to manually enter the sub-thread's notification preference URL and I doubt many users would run into this flow.

**Comment by sonialiap** [comment]
Payment summary:
- @parasharrajat $125 - please request in ND and complete the [checklist](https://github.com/Expensify/App/issues/46097#issuecomment-2283539999)
- @ra-md $125 - offer through [upwork](https://www.upwork.com/ab/applicants/1818434968448883106/hired). @ra-md are you Rafli R. on Upwork? Checking if you've applied for this job

**Comment by sonialiap** [comment]
@alexpensify I'm OOO Aug 19-30, adding leave buddy. 
Status: if no regressions then please complete payment ([Summary](https://github.com/Expensify/App/issues/46097#issuecomment-2293480000)) and submit a new QA test once Rajat completes the checklist

**Comment by alexpensify** [comment]
@ra-md - can you please answer this question: 

>@ra-md $125 - offer through [upwork](https://www.upwork.com/ab/applicants/1818434968448883106/hired). @ra-md are you Rafli R. on Upwork? Checking if you've applied for this job

I can't complete the payment process in Upwork until we get a clarification here. Thanks!

**Comment by alexpensify** [comment]
Ok, I sent the offer via Upwork. Thanks!

**Comment by alexpensify** [comment]
Closing - I completed the payment process in Upwork listed here https://github.com/Expensify/App/issues/46097#issuecomment-2293480000

--- 

@parasharrajat please submit a request via Chat. Thanks!

**Comment by JmillsExpensify** [comment]
$125 approved for @parasharrajat
