### ISSUE TITLE
[HOLD for payment 2024-08-09] [$250] Workspace - Invited member is allowed to upload workspace avatar, but the upload fails

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46098]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Admin invites employee to a workspace.
- The workspace does not have avatar set up.
- The following steps will be performed by the employee.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Profile.
3. Click on the avatar.
4. Upload an avatar.

## Expected Result:
Invited member should not be allowed to upload the workspace avatar (production behavior).

## Actual Result:
Invited member is allowed to upload the workspace avatar, but the upload fails.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f8f65d35-06cf-4ed4-8237-72bbca54abe5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cecd7459223b27f7</li>
        <li>Upwork Job ID: 1816065082489022429</li>
        <li>Last Price Increase: 2024-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103312496</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production 

https://github.com/user-attachments/assets/faea9b30-0667-458d-a022-dd58a41d953f

**Comment by grgia** [comment]
Making external

**Comment by grgia** [comment]
assigning!

**Comment by grgia** [comment]
@muttmuure looks like this one is good for payment

**Comment by muttmuure** [comment]
@ishpaul777 paid $250

**Comment by muttmuure** [comment]
@daledah can you link your Upwork profile please

**Comment by grgia** [comment]
not overdue melvin

**Comment by muttmuure** [comment]
closing this out tomorrow

**Comment by muttmuure** [comment]
Invited @daledah

**Comment by muttmuure** [comment]
Waiting for @daledah to answer invite: https://www.upwork.com/jobs/~01cecd7459223b27f7

**Comment by muttmuure** [comment]
Bump @daledah

**Comment by muttmuure** [comment]
Dropping to weekly

**Comment by muttmuure** [comment]
Offer is still pending @daledah https://www.upwork.com/nx/wm/offer/103894514

**Comment by muttmuure** [comment]
Nice, paid
