### ISSUE TITLE
[$250] AU-Login-On tapping Log in, continue button hidden by keypad

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46102]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4762839
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/r/2091104345528462
2. Tap sign in button at bottom
3. Scroll down and tap Log in

## Expected Result:
On tapping Log in, continue button must not be hidden by keypad.

## Actual Result:
On tapping Log in, continue button hidden by keypad.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7356761b-5d6a-4693-b0d1-da92e8d8f2a1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f7000bd0c4027b90</li>
        <li>Upwork Job ID: 1821192673627195472</li>
        <li>Last Price Increase: 2024-08-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by JmillsExpensify** [comment]
There's not a perfect project to file this in, though we're redoing the home page for wave-collect so filing as polish there and opening up to the community.

**Comment by trjExpensify** [comment]
I can't repro this on iOS mWeb - the page moves up and the `Continue` button isn't hidden. @thesahindia, do you have a physical Android device to test? 

https://github.com/user-attachments/assets/6653bab2-9ff6-4356-a502-33e4c0d6a289
https://github.com/user-attachments/assets/7f1a19f8-da6f-4c9c-8117-19bd73203e8c

**Comment by JmillsExpensify** [comment]
Let's close then for focus.
