### ISSUE TITLE
AU-Troubleshoot-Tapping reset &refresh shows onboarding modal &directs to concierge

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4762866
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Login with new gmail account in android mweb
2. Tap join
3. Enter details to complete onboarding modal
4. Tap profile icon -- troubleshoot - clear restart and cache
5. Tap reset and refresh

## Expected Result:
Tapping reset &refresh must not show onboarding modal briefly and must not direct to concierge page.

## Actual Result:
Tapping reset &refresh shows onboarding modal briefly and directs to concierge page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/678afeaa-b248-426d-b2bb-d6e8495e33c4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by izarutskaya** [comment]
Production

https://github.com/user-attachments/assets/2c42c86c-236f-402c-ab56-42abe08b1396

**Comment by Julesssss** [comment]
This troubleshooting rest flow in not critical, demoting.

**Comment by trjExpensify** [comment]
I agree. @muttmuure would this go in #newdot-quality as a low issue?

**Comment by Julesssss** [comment]
Making this external

**Comment by Julesssss** [comment]
@trjExpensify I'm leaning towards closing as this is a brand new user who resets the local data. Not sure this is worth modifying, or what the expected behaviour would be...

**Comment by trjExpensify** [comment]
Happy for @muttmuure to make that call, but I tend to agree if it doesn't get in the way of debugability, but I don't think it does.

**Comment by Julesssss** [comment]
@muttmuure please re-open if necessary

> Happy for @muttmuure to make that call, but I tend to agree if it doesn't get in the way of debugability, but I don't think it does.
