### ISSUE TITLE
[HOLD for payment 2024-08-27][$250] Room - Sign in RHP disappears after clicking on the "<" button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46106]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open Chrome in incognito
2. Navigate to https://staging.new.expensify.com/r/2091104345528462
3. Click on the "Sign in" button at the bottom right corner
4. Input any email and click on the "Continue" button
5. Click on the "<" button

## Expected Result:
he RHP should display the page where I can input the email

## Actual Result:
Sign in RHP disappears afte clicking on the "<" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/dcbb9b27-5572-41bd-a3fa-a8ebbd101e1f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f20ee7a37f39fffa</li>
        <li>Upwork Job ID: 1818652267932942150</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103347895</li>
<li>Krishna2323 | Contributor | 103347901</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by luacmartins** [comment]
Proposal looks good, but let's declare a function to handle the logic in `onBackButtonPress` instead of declaring it inline.

**Comment by anmurali** [comment]
added regression and paid
