### ISSUE TITLE
[$250] mWeb – Chat  – Blue frame appears around + button when open conversation link URL in a new tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46109]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with Gmail account
3. Open any chat and copy URL
4. Open new tab and paste URL

## Expected Result:
Chat opens without blue frame around + button

## Actual Result:
Chat opens with blue frame around + button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/369832a2-8e5f-4180-b1c0-e23e7f9d8299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ced2d499965abe3</li>
        <li>Upwork Job ID: 1816181351346781688</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>tsa321 | Contributor | 103953960</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment]
Issue is not reproducible on Production:
 

https://github.com/user-attachments/assets/80605f58-1968-445c-aa67-9a1b290d0f6b

**Comment by francoisl** [comment]
Possibly related to https://github.com/Expensify/App/pull/45743 (?) Anyway, doesn't look like something worth blocking for – going to demote.

**Comment by srikarparsi** [comment]
Hi @tsa321 @hoangzinh, if you have a second, do you think you could check if this issue is related to https://github.com/Expensify/App/pull/45743

**Comment by tsa321** [comment]
@srikarparsi, I have tried reverting my PR, but this issue is still reproducible.

**Comment by tsa321** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Blue border appears on + button when user open report by url

### What is the root cause of that problem?
We use focusTrap to maintain tab navigation. But when user visit by url the focusTrap will focus the tabable element. There are many other pages, when we open the page the blue border appears.
For example, about page, profile page, the report page, workspace list page, in display name it appears briefly, and .

### What changes do you think we should make in order to solve the problem?

We could disable blue border by css styling when page load. Then show the blue border when user press tab. If other key is pressed we disable the blue border again. The code could be:

```javascript
let sheet;
const mangaeFocusedElementBlueBorder = () => {
    sheet = document?.createElement('style');
    sheet.innerHTML = '[tabindex="0"]:focus{box-shadow: none; outline: none;}'
    window.document.body.appendChild(sheet);
    window.addEventListener('keydown', (e) => {
        if (e.key === 'Tab' || e.key === 'Shift') {
            if (e.key === 'Tab' && !!sheet.parentNode) {
                sheet.parentNode.removeChild(sheet);
            }
        } else if (!sheet.parentNode) {
            window.document.body.appendChild(sheet);
        }
    }, true);
}
```

We could place it in the Accessbility library

**Comment by sobitneupane** [comment]
Thanks for your proposal @tsa321 

Can you please elaborate the root cause section of your proposal?

> When a user visits a page via URL, focusTrap initially focuses on the tabbable element, causing the blue border to appear.

Can you please link the code which implements above feature? Let's try to investigate more on the root cause.

Why is it limited to some pages only?

**Comment by srikarparsi** [comment]
Hi @sobitneupane, any updates here?

**Comment by sobitneupane** [comment]
Thanks for the update @tsa321 

[This PR](https://github.com/Expensify/App/pull/39520) adds the focus trap in the app.

Will your proposal resolve https://github.com/Expensify/App/issues/46075 issue as well? What is RCA for https://github.com/Expensify/App/issues/46075?

Are there any other ways to show the outline only if interacted through keyboard? If I am not wrong, `focus-visible` outlines only if interaction is made through keyboard.

**Comment by sobitneupane** [comment]
Thanks for the update @tsa321 

Your [proposal](https://github.com/Expensify/App/issues/46109#issuecomment-2249101171) will probably solve the issue. . However, I believe we should avoid a workaround if possible. The change was introduced by [this PR](https://github.com/Expensify/App/pull/39520), authored by @adamgrzybowski and @jnowakow 

@adamgrzybowski @jnowakow, any suggestions?

**Comment by adamgrzybowski** [comment]
Hey @sobitneupane, @jnowakow who was the main creator of PR for Focus Trap is currently OOO. From my point of view, I can only agree that we should avoid workarounds, but I currently have no alternative.

**Comment by sobitneupane** [comment]
Thanks @adamgrzybowski

**Comment by sobitneupane** [comment]
Waiting for proposal.

**Comment by sobitneupane** [comment]
Thanks for the update @tsa321 

The change you suggested might recreate some issue, https://github.com/Expensify/App/pull/39520 PR is trying to solve. For example: Focus remains on the report when navigated to RHP with keyboard.

https://github.com/user-attachments/assets/612a6320-02f6-424a-bb8e-691a4c45823d

**Comment by sobitneupane** [comment]
@tsa321, I tried it but It didn't work for me. I might have missed something. Is it working on your end?

**Comment by sobitneupane** [comment]
@tsa321 I can still reproduce the issue.

https://github.com/user-attachments/assets/e4b642e5-0e54-414d-bb32-28b991a35405

<img width="1190" alt="Screenshot 2024-08-15 at 17 01 15" src="https://github.com/user-attachments/assets/a505adea-5736-49f5-b1c2-4c61b00f5ce3">

**Comment by sobitneupane** [comment]
@tsa321 If I am not wrong, enabling the legacy mode will disable the concurrent mode. It makes sense that the issue is not reproducible in the legacy mode. But shouldn't it work in concurrent mode as well?

**Comment by sobitneupane** [comment]
Thanks for the update @tsa321 Overall the alternative solution 2 looks good.

Can you please add the reasoning for the suggested changes especially in `onDeactivate` and `setReturnFocus`?

> In onActivate, we store the current active element in the ref, then blur it; in onDeactivate, we focus that element. We must also set initialFocus and setReturnFocus to always return false.

**Comment by sobitneupane** [comment]
Thanks for the update @tsa321 

Why is `onActivate` triggered twice? Is it an existing bug in focus-trap? Are there any issues related to it in the focus-trap repo? I am not sure if it is causing our issue.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sobitneupane** [comment]
Thanks for the update @tsa321 

Alternative solution 2 in [your proposal](https://github.com/Expensify/App/issues/46109#issuecomment-2249101171) will probably solve the issue. If @jnowakow (author of [the PR](https://github.com/Expensify/App/pull/39520) which adds the focus trap) is back, I'd like to hear his thoughts on the proposal.

🎀 👀 🎀 C+ reviewed

cc: @adamgrzybowski

**Comment by srikarparsi** [comment]
Asked in the swm channel since I'm not too familiar with focus trap.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by srikarparsi** [comment]
I'm not able to reproduce this either, @sobitneupane can you check if this is reproducible for you.

**Comment by sobitneupane** [comment]
@srikarparsi I can still reproduce the issue.


https://github.com/user-attachments/assets/be3b525f-7601-445c-bb52-cb36c674c16b

**Comment by srikarparsi** [comment]
Ah okay, I think @adamgrzybowski will be back tomorrow based on this [comment](https://expensify.slack.com/archives/C04878MDF34/p1725605701678609?thread_ts=1725583761.828829&cid=C04878MDF34) so he might be able to better evaluate this [proposal](https://github.com/Expensify/App/issues/46109#issuecomment-2249101171)

**Comment by adamgrzybowski** [comment]
Hey! I was working on a focus trap at some point but it changed a lot since then. However, with my limited context, the alternative solution 2 looks like a right direction to me

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by youssef-lr** [comment]
This is still reproducible

**Comment by srikarparsi** [comment]
Cool lets proceed with [solution 2](https://github.com/Expensify/App/issues/46109#issuecomment-2249101171) then, assigning @tsa321

**Comment by sobitneupane** [comment]
@srikarparsi This is ready for payment.

**Comment by sobitneupane** [comment]
Bump @srikarparsi

**Comment by srikarparsi** [comment]
Hey @slafortune! Do you think you could help with payment for this issue?

**Comment by slafortune** [comment]
Sorry for my delay - 

@tsa321 Role Contributor was paid $250 via Upworks
@sobitneupane Role C+ is **owed $250 via NewDot**

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
