### ISSUE TITLE
[HOLD for payment 2024-08-05] Enable Firebase performance logging

### ISSUE THREAD

**Issue by TMisiukiewicz** [Expensify/App#46113]
Coming from https://expensify.slack.com/archives/C05LX9D6E07/p1721655178311639

### Problem
Our current performance/reliability focus is on app behavior for specific accounts, but we are missing the broader view of performance trends over time for a wider audience. Additionally, CK cannot access Grafana dashboard, so we don't know how performance data behaves across the app for end users.

### Solution
Let's enable capturing performance data in Firebase. This setup would automatically collect session data from a small number of users, including CPU and memory usage, network requests, etc. We could extend this by adding information about an account, such as the amount of personal details and reports on the account. This would allow us to link resource usage with the amount of data.

We could further enhance this by tracing screen rendering to gather information about slow rendering and frozen frames.

With all this data, we can identify and fix performance issues before they affect a significant portion of users, and prioritize features and fixes based on real user data.

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by marcaaron** [comment]
This was new feature rather than a bug and no payments are needed here so gonna just close it out.
