### ISSUE TITLE
IOU is not showing `Pay $X.XX with Expensify` 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1721687566402259

## Action Performed:
1. Send an IOU to a new user from user A
2. Login as a new user
## Expected Result:
Should see a "Pay" button for the IOU
## Actual Result:

- There were no pay options
- If I click into the expense, the pay button shows up.
- If I then click back to the DM the IOU now has pay buttons

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/25feab83-e7e1-4521-b535-dbf08cdb4c93

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by puneetlath** [comment]
We agreed in the thread that this isn't a #newdot-quality issue, so I'm going to remove it from the project and un-assign myself. @VictoriaExpensify @youssef-lr I'll let y'all categorize it where you think it fits best.

**Comment by VictoriaExpensify** [comment]
No prob, thanks Puneet

**Comment by VictoriaExpensify** [comment]
@youssef-lr it sounds like you [already have a fix for this](https://expensify.slack.com/archives/C05LX9D6E07/p1721752176709019?thread_ts=1721687566.402259&cid=C05LX9D6E07). I'll wait for you to weigh in here

**Comment by youssef-lr** [comment]
Yes, just made the last PR ready for review

**Comment by VictoriaExpensify** [comment]
Sweet. I don't think I'm really needed here, but bump me if you need anything

**Comment by youssef-lr** [comment]
This is fixed.
