### ISSUE TITLE
IOU Report - Invitee does not have "Leave" option in details

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#46125]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.7-8

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes 

**If this was caught during regression testing, add the test name, ID and link from TestRail:** [IOU Report - Invitee - Invitee can access report](https://expensify.testrail.io/index.php?/cases/view/3073342)

**Issue reported by:** Applause - Internal team

## Action Performed:

1. In a 1:1 conversation between 2 users - Send 2 IOUs
2. In the report conversation mention a external user (invitee)
3. In the actionable whisper, select to invite the user
4. Copy the report URL and send it to the Invitee
5. Login as the invitee
6. Navigate to the report URL
1. Click on the header of the report conversation
2. Check the actionable options 

## Expected Result:
The report details for an invitee should display the options to pin/unpin, share and leave. Check this [doc for reference](https://docs.google.com/document/d/1-xSZdSZZIuIl0fPO7yypkKfcbWEsnNFAs50ptgL3Gnw/edit?pli=1)

## Actual Result:
The Leave option is not displayed of a report invitee

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/f7a390b9-4637-47e5-9880-8cd97b302a5f)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
I am not 100% sure this warrants changing. It is expected that you have the option to leave a room, but in this case, you were not invited to a room. The invitation was to a thread in a 1:1 DM, which normally there is no option to leave for the two members involved. If you invite someone to a room, they do have the option to leave it now. So I am not 100% sure it is incorrect that someone invited to a thread in a 1:1 DM doesn't have the option to leave. 

Further, this feels like chat related bug, and we've paused #vip-vsb.

**Comment by joekaufmanexpensify** [comment]
Going to close this one for now since it is related to project that is paused, and I don't think this is necessarily a bug. If we get feedback from customers about this, we can reassess.
