### ISSUE TITLE
iOS - Unable to type in Simplified Chinese on iOS mweb Chrome, mweb Safari and iOS app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46124]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Chinese - Simplified - Pinyin language is added on General > Keyboard
1. Launch New Expensify app
2. Go to any report
3. Change the keyboard language to Simplified Chinese
4. Type nihao
5. Note that the keyboard does not display the suggestions
6. Go to FAB > Assign task
7. Tap on the Title field
8. Type nihao
9. Note that the input in Title input is not broken and suggestion shows up after typing
10. Go to iOS Chrome or iOS safari
11. Go to any report
12. Type nihao
13. Note that the input doubles in the composer

## Expected Result:
User can type in Simplified Chinese without issue

## Actual Result:
On iOS app, it does not display suggestion after typing Chinese words
On iOS mweb Chrome and Safari, the input doubles in the composer when typing in Simplified Chinese

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari/ Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a79617a8-9bb8-48cf-9df3-4128e4ddbe4c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
I don't think this is a priority for the moment. Closing.
