### ISSUE TITLE
[Upgrades] Update Upgrade notification in #admins to be a whisper to the workspace owner + add a custom subject

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#46131]
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1721821571237569?thread_ts=1721665229.380799&cid=C036QM0SLJK

## Action Performed:
1. Create a new workspace in NewDot
2. Invite another member to the workspace and make them an admin
3. Login as the non-owner admin
4. Enable Report Fields from the More Features menu
5. Upgrade the workspace

## Current Result:
We send a system message from Expensify in the #admins room, mentioning the owner, and notifying them of the upgrade.

## Desired Result:
We want to make a few changes to that message:
- Change the message to a whisper message from Expensify in the #admins room to the workspace owner since they're the user we're focused on notifying/educating.
- Add a custom subject to the message: `Congrats! Your workspace has been upgraded.`
- Update the message copy to:

>[Admin that upgraded's full name] has upgraded the [Workpsace Name] workspace to the Control plan to enable [feature upgraded for] Explore the additional upgraded workspace features here. 
The Control plan is billed starting at [Price in workspace billing currency] per active member per month with an annual subscription and Expensify Card usage. To manage your subscription, downgrade your plan, or view the specific price for your configurations, head to Settings > Workspaces > Subscriptions.

Here's an example:
![image](https://github.com/user-attachments/assets/81160f56-6e36-467b-b54c-a0d6f026ec06)

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by trjExpensify** [comment]
@allroundexperts @youssef-lr does this update need to be internal, external or a combo of both?

**Comment by trjExpensify** [comment]
Bumped, and putting this on daily until I get it confirmed and moving to either Sibtain or Youssef depending on the answer to the above. :)

**Comment by trjExpensify** [comment]
@youssef-lr assigning this to yah!

**Comment by youssef-lr** [comment]
I'll have a PR ready this week

**Comment by youssef-lr** [comment]
I couldn't manage to get to this, I'm on it this week. I've been 0% the past one.

**Comment by youssef-lr** [comment]
Same update, I'm still working on a wave-control issue for adding expenses to submitted reports.

**Comment by trjExpensify** [comment]
How you getting on here, @youssef-lr?

**Comment by youssef-lr** [comment]
PR's ready @trjExpensify

**Comment by youssef-lr** [comment]
waiting for deploy

**Comment by trjExpensify** [comment]
Auth PR deployed yesterday, anything more to come with this?

**Comment by youssef-lr** [comment]
yup!
