### ISSUE TITLE
NetSuite - Infinite sync when entering incorrect credentials

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#46137]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:** [Error tests - Connect Netsuite](https://expensify.testrail.io/index.php?/cases/view/3073351) 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Issue reported by:** Applause - Internal team

## Action Performed:
1. Login with an account that is an admin of a control workspace (or create one in OD if needed)
1. Enable accounting in workspace settings
1. Navigate to Accounting
1. Click on the connect button next to NetSuite
1. Reach the credentials step
1. Enter incorrect the NetSuite tokens

## Expected Result:
Entering the Netsuite credentials incorrectly should trigger an error state and RBRs to indicate the connection error.

## Actual Result:
Infinite loading is displayed and there's no way to cancel it. No error about incorrect credentials is triggered. 

## Workaround:
No

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/b91dbb24-955d-4918-841b-2e88538b7ec0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
Asked a design question about this here: https://expensify.slack.com/archives/C06ML6X0W9L/p1721862798362719

**Comment by twisterdotcom** [comment]
Does this need to be External at all @yuwenmemon? Or will you handle it?

**Comment by yuwenmemon** [comment]
Nah this will be [all me](https://www.youtube.com/watch?v=s0U578ReOU8&ab_channel=wifiPictures).

**Comment by JmillsExpensify** [comment]
Any reason why this issue is still open? The linked PR hit IS production.

**Comment by francoisl** [comment]
Pretty sure this can be closed now.
