### ISSUE TITLE
Xero Export - Export button appears for message threads that are in the expense report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46138]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause -Internal Team

## Action Performed:
Precondition:
- Workspace is connected to Xero
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Pay the expense
5. Go to the expense report
6. Send a message in the expense report
7. Right click on the message > Reply in thread
8. Click on the report header
9. Click Export

## Expected Result:
Export button should not appear for message threads that are in the expense report

## Actual Result:
Export button appears for message threads that are in the expense report
Clicking on the Export button shows "Not ready to export" when the expense is already paid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/632e4e2c-0ff4-45c1-a749-b7f9a5a5f062

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by rlinoz** [comment]
Coming from https://github.com/Expensify/App/pull/45678 I think so I am gonna remove the blocker for Web-E

**Comment by trjExpensify** [comment]
@kosmydel is out of office now, but maybe @hungvu193 who reviewed the PR can review or look at this one?

**Comment by francoisl** [comment]
I can send a PR in a sec @rlinoz if you haven't started on this yet.

**Comment by francoisl** [comment]
Fix tested on production 👍

**Comment by francoisl** [comment]
I meant on staging*
