### ISSUE TITLE
[HOLD for payment 2024-07-30] Improve filtering performance in share logs page

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#46148]
This issue is specifically to handle payment for [this PR](https://github.com/Expensify/App/pull/40285).

@TMisiukiewicz wrote and @mollfpr reviewed. Only payment that will be due is $250 for a standard C+ PR review to @mollfpr 

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Yep, payment summary as follows: 

- $250 to @mollfpr for the C+ review

Feel free to go and request!

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr
