### ISSUE TITLE
Improve filtering performance in Request Money and Send Money

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#46147]
This issue is specifically to handle the payment for https://github.com/Expensify/App/pull/40235

@TMisiukiewicz wrote and @Pujan92 reviewed. Only payment that is due is $250 to @Pujan92 for a standard C+ review. It's ready to pay immediately.

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor: @TMisiukiewicz paid via contract

Contributor+: @Pujan92 due $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @Pujan92
