### ISSUE TITLE
[HOLD for payment 2024-08-05] Improve filtering performance in room invite page

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#46149]
This issue is branched off of https://github.com/Expensify/App/issues/37619 and was created specifically to manage the lifecycle and payments of this PR: https://github.com/Expensify/App/pull/40764

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by roryabraham** [comment]
@TMisiukiewicz please comment for assignment and link https://github.com/Expensify/App/pull/40764 to this issue before opening it up for review. Thanks

**Comment by TMisiukiewicz** [comment]
Thank you @roryabraham, linked the issue and opened the PR

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @ishpaul777 for PR review and testing.

**Comment by JmillsExpensify** [comment]
@ishpaul777 I sent you a Upwork offer.

**Comment by JmillsExpensify** [comment]
Just waiting on offer acceptance and then we can get this one closed out.

**Comment by JmillsExpensify** [comment]
No worries! Just paid out. Thank you!
