### ISSUE TITLE
[HOLD for payment 2024-07-24][$250] Improve filtering performance in workspace invite page

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#46145]
This issue is created specifically to handle payment for https://github.com/Expensify/App/pull/40793

@TMisiukiewicz wrote and @alitoshmatov reviewed. payout can happen immediately.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c6fb1079effb331b</li>
        <li>Upwork Job ID: 1816227932032944066</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by alitoshmatov** [comment]
@anmurali Can you handle payment here

**Comment by roryabraham** [comment]
bump @anmurali for payment plz

**Comment by anmurali** [comment]
Offer is [here](https://www.upwork.com/nx/wm/offer/103411076)

**Comment by alitoshmatov** [comment]
@anmurali Accepted the offer

**Comment by anmurali** [comment]
Paid.
