### ISSUE TITLE
[HOLD for payment 2024-08-05] Improve filtering performance in task share page

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#46151]
This issue is branched off of https://github.com/Expensify/App/issues/37619 and was created specifically to manage the lifecycle and payments of this PR: https://github.com/Expensify/App/pull/40290

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by roryabraham** [comment]
@TMisiukiewicz please comment for assignment and link https://github.com/Expensify/App/pull/40290 to this issue before opening it up for review. Thanks

**Comment by TMisiukiewicz** [comment]
Thank you @roryabraham, linked the issue and opened a PR

**Comment by zanyrenney** [comment]
Looks good, thanks @ZhenjaHorbach

**Comment by zanyrenney** [comment]
there seems to be no existing upwork job, reapplying the label to retrigger

**Comment by zanyrenney** [comment]
@ZhenjaHorbach invited you to the upwork job, please accept for payout.

**Comment by zanyrenney** [comment]
https://www.upwork.com/jobs/~017f8379bba041b305

**Comment by zanyrenney** [comment]
hired! accept for payout please @ZhenjaHorbach

**Comment by zanyrenney** [comment]
### Payment Summary
[Upwork Job]()
- Contributor: @TMisiukiewicz is from an agency-contributor and not due payment
- ROLE: @ZhenjaHorbach paid $250 via Upwork (LINK)
