### ISSUE TITLE
[HOLD for payment 2024-08-07] Unable to Edit Configuration when the last sync ended in error

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#46153]
When a NetSuite sync fails and we show an error, we hide all the configuration tabs. This is not good because in all likelihood users will need to update a setting to fix their connection, so they need to be able to access all the configuration panes:

![Screenshot 2024-07-24 at 4 10 11 PM](https://github.com/user-attachments/assets/db11ec4f-8065-4a61-a945-c9cb523638b7)

cc @mananjadhav @shubham1206agra 

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by yuwenmemon** [comment]
Actually looks like this is a simple fix so adding my own PR

**Comment by anmurali** [comment]
@ishpaul777 offer is [here](https://www.upwork.com/nx/wm/offer/103516836)

**Comment by yuwenmemon** [comment]
@ishpaul777 @anmurali is this all square? Are we good to close?

**Comment by yuwenmemon** [comment]
Great, closing!
