### ISSUE TITLE
[Held requests] [$250] "Confirm approval amount modal" appears for the deleted held expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721855333504669

## Action Performed:
1. Submit a report with 2 expenses 
2. Sign in as  a approver
3. Open the report 
4. Put one expense on Hold 
5. As a submitter delete the held expense
6. As approver click on "approve"
## Expected Result:
Modal should not show with approval amount
## Actual Result:
Confirm approval amount modal is shown
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (9)](https://github.com/user-attachments/assets/77d12d23-9471-451a-a983-2c8a8d262406)

https://github.com/user-attachments/assets/ff48173f-1bbd-4b47-b773-bd81f6f9a09a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e21d9e5fefda11c</li>
        <li>Upwork Job ID: 1818028931528326795</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103369133</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by nkdengineer** [comment]
@m-natarajan Can you please share the full reproduced video? I tried and after the submitter submitted the expense, they could not delete a transaction.

**Comment by sakluger** [comment]
@nkdengineer you wouldn't be able to delete submitted expenses, but if the approver puts one of the expenses on hold, you would be able to delete the held expense.

**Comment by burczu** [comment]
Hi, I’m Bartek from Callstack and I would like to work on this issue.

**Comment by puneetlath** [comment]
Hm, yes the approver should be able to put the expense on hold. Do you have your workspace set up to have an approval turned on?

**Comment by eh2077** [comment]
Not overdue, discussion is ongoing

**Comment by burczu** [comment]
@puneetlath I think so:

![Screenshot 2024-08-06 at 09 27 37](https://github.com/user-attachments/assets/039d8937-f7cd-4c58-904e-753401427052)

**Comment by burczu** [comment]
Just to inform: I'll be ooo from tomorrow August 7th till the end of next week (August 18th).

**Comment by sakluger** [comment]
I think we can put this one on hold until you're back. @puneetlath if you think this is more time-sensitive, feel free to change back to daily and we can try recruiting someone else to work on it.

**Comment by puneetlath** [comment]
I'd say let's see if someone else can take it on.

**Comment by koko57** [comment]
@puneetlath ok, someone from our team will take it over

**Comment by narefyev91** [comment]
Hi, I’m Nicolay from Callstack and I would like to work on this issue. (will start investigation from Monday)

**Comment by narefyev91** [comment]
@puneetlath @sakluger  does issue still exists?
Probably my tests on latest dev (maybe i did something wrong on videos, but generally following steps to reproduce):
On safary - approval
On chrome - submitter
After approval mark expense as held, submitter remove expense, approval got removed that expense from the list.
Approve button just approve rest of the expense(s)

https://github.com/user-attachments/assets/c60fb969-09e8-41db-9d93-02e426cedcf7


https://github.com/user-attachments/assets/cde85fdf-9300-4914-97ac-ebc2e874e850

**Comment by narefyev91** [comment]
Also based on debugging responses. When one expense is in hold - we get correctly status from API and will show modal to approve - because comment.hold is not empty
<img width="809" alt="Screenshot 2024-08-12 at 17 08 18" src="https://github.com/user-attachments/assets/f30b14a5-5e5e-4a89-995a-221994602ade">
After removing we do not have that item in array any more:
<img width="1043" alt="Screenshot 2024-08-12 at 17 08 57" src="https://github.com/user-attachments/assets/fed86c27-0e95-4c85-8ab3-55ff18776a4d">

**Comment by robertjchen** [comment]
Thanks for the investigation here! Having reviewed this, the issue appears to have already been resolved given that @burczu and @narefyev91 were unable to reproduce it

If you're still able to reproduce, let's create a fresh issue with an updated recording 👍
