### ISSUE TITLE
IOU - "Next steps" comment is not correct after approving report

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#46157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-5
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** vdargentotest+web072424@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause Team 
**Slack conversation:** 

Found while executing PR https://github.com/Expensify/App/pull/45160

## Action Performed:
Pre-requisite: create a collect workspace and invite an employee.
1. As the admin, go to OD and set "Scheduled Submit" enabled in the "Reports" section, set it as "Manually".
2. Set the Approval Mode to "Submit and Approve" on the "Members" section.
3. As the employee, go to workspace chat on ND and submit a money request.
4. As the admin on ND, got to the employee's workspace chat and open the report.
5. Click on the "Approve" button.

## Expected Result:
Next steps comment should say "Waiting for [Admin] to pay expense(s)" and an hourglass accompanying icon.

## Actual Result:
Next steps comment says "No further action required!" and a checkmark accompanying icon

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos 

https://github.com/user-attachments/assets/ca4d84e4-4872-460b-8671-299c42a15a7b

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
We think this is related to #wave-collect - Release 1

**Comment by francoisl** [comment]
This is also happening on production so not going to make this a deploy blocker. We had an issue in the past few days where the web production deploy wasn't actually deployed, so the production version you were seeing was an older one. It's fixed now.

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/c040943c-57c3-4c1d-a047-fb9193129d7d">

**Comment by JmillsExpensify** [comment]
I'm not certain that this is a bug. What's the configuration of the workspace on NewDot? Is reimbursement enabled in the workspace?

**Comment by adelekennedy** [comment]
yikes - this got assigned to me when i was already ooo and I missed it. Bump on @JmillsExpensify question @mvtglobally
