### ISSUE TITLE
Dupe detection - Confirmation page RHP turns to not here page while dismissing

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Found when validating https://github.com/Expensify/App/pull/45877
**Version Number:** 9.0.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 
 
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two same expenses (same amount and merchant).
4. Go to transaction thread of any expense.
5. Click Review duplicates.
6. Select Keep this one (any).
7. Proceed to confirmation page.
8. Click outside the RHP to dismiss.
9. Note that RHP turns to not here page while dismissing.
10. Repeat Step 5 to 7.
11. Click Confirm button.
12. Note that RHP turns to not here page while dismissing.

## Expected Result:
In Step 9 and 12, the confirmation page will not turn to not here page while dismissing.

## Actual Result:
In Step 9 and 12, the confirmation page turns to not here page while dismissing.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1f3ffbd8-316e-46d2-aefd-f25fb54fe4f3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by m-natarajan** [comment]
We think this bug might be related to #wave-collect - Release 2

**Comment by roryabraham** [comment]
Dupe detection is behind a beta, so NAB

**Comment by jliexpensify** [comment]
Could we switch this to `Weekly` or `Monthly` since it's behind a beta and will resolved by https://github.com/Expensify/App/pull/45965? (and to stop the pings?)

**Comment by flodnv** [comment]
https://github.com/Expensify/App/pull/45965 was deployed, we need a retest @jliexpensify @m-natarajan

**Comment by jliexpensify** [comment]
Weird, I am not seeing a `Resolve Duplicates` option on v0.0.30-7 (staging)

@m-natarajan @gijoe0295 can you both verify this/confirm this isn't a bug anymore?

**Comment by jliexpensify** [comment]
Going to close this as I couldn't repro.
