### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Onboarding – Keyboard not appears when Business name opens in "Manage my team expenses"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46188]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45377
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with new Gmail account
3. Choose "Manage my team expenses" purpose on the first onboarding page
4. Verify Business name page opens

## Expected Result:
Keyboard appears when Business name opens

## Actual Result:
Keyboard not appears when Business name opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/017a7344-18fb-404f-b251-74dcf56d1b48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011303f7713569ea41</li>
        <li>Upwork Job ID: 1817906447482578584</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by NikkiWines** [comment]
agreed! 👍

**Comment by muttmuure** [comment]
$250 - @rayane-djouah 
$250 - @nyomanjyotisa

**Comment by muttmuure** [comment]
Invites sent to job, automation failed

**Comment by muttmuure** [comment]
job is here: https://www.upwork.com/jobs/~011303f7713569ea41

**Comment by muttmuure** [comment]
I've sent a new offer, could you try again?

**Comment by muttmuure** [comment]
Paid
