### ISSUE TITLE
[$250] Expense - Unable to leave thread after the expense report changes to a thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46193]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4764507
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM with user that has no unsettled expense
3. Submit an expense
4. Click on the expense preview to go to expense report
5. Send a message
6. Click on the report header > Delete expense
7. Delete the expense
8. Click on the report header > Leave
9. On the main chat, click on the # reply
10. Note that Join button appears then disappears
11. Click on the thread header
12. Note that Leave button is still there after "leaving" the thread

## Expected Result:
User will be able to leave the thread after deleting the expense

## Actual Result:
User is unable to leave the thread after deleting the expense
This issue only happens in expense report which turns to a normal message thread after deleting the expense
It does not happen in regular message threads

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/371bf893-a65b-449d-a540-253559a3e2ce

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117b2a90eba9471b7</li>
        <li>Upwork Job ID: 1821193144429280011</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
I'll add the external label to see if we have an easy fix, and this is technically part of split since it's an IOU issue.

**Comment by JmillsExpensify** [comment]
BE bug so we're waiting on internal volunteers now.

**Comment by JmillsExpensify** [comment]
Still waiting on internal volunteers.

**Comment by JmillsExpensify** [comment]
Going to close this issue for focus.
