### ISSUE TITLE
[$250] Android - Subscription-Request early cancellation option is not displayed in subscription page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46196]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44763
## Action Performed:
1. Launch app in both mweb & android
2. Log in with a new account ( not expensifail)
3. Tap fab - new workspace
4. Navigate to LHN
5. Tap profile - subscription

## Expected Result:
Request early cancellation optionmust be displayed

## Actual Result:
Request early cancellation option is not displayed in subscription page in android but present in mweb

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1648aac2-93dd-457c-9e37-c67726e1627c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f4c10fc9d8363bc</li>
        <li>Upwork Job ID: 1816876676482296848</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment]
NAB its expected to be hidden in native devices:

https://github.com/Expensify/App/blob/b330f3aa7978ff671f2c545edc122c1d9220d69a/src/pages/settings/Subscription/CardSection/RequestEarlyCancellationMenuItem/index.native.tsx#L1-L3

cc: @JKobrynski @mananjadhav

**Comment by zanyrenney** [comment]
hey @ahmedGaber93 we already have a proposal for this one so if you can review it, that would be great!

**Comment by ahmedGaber93** [comment]
@JKobrynski @mananjadhav, It looks this behavior is intended in this [commit](https://github.com/Expensify/App/commit/c2fd78ba4f13007c05fb56e2fdcbcaa6447e7f8e), Can you please confirm?

**Comment by ahmedGaber93** [comment]
@zanyrenney bump https://github.com/Expensify/App/issues/46196#issuecomment-2263418242

**Comment by zanyrenney** [comment]
Yes definitely, let's close this out!
