### ISSUE TITLE
Bank Account - Unable to save new debit card.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46199]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/22984&group_by=cases:section_id&group_order=asc&group_id=229064
**Email or phone of affected tester (no customers):** bellicoignacio+93@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Tap on the avatar on the bottom of the screen.
3. Tap on "Wallet"
4. Tap on "Add Bank Account"
5. Tap on "Debit Card"
6. Complete all the required fields with valid data.
7. Accept terms and conditions and privacy policy.
8. Tap on "Save"
9. Check the error message displayed above the "Save" button.

## Expected Result:
After completing all the fields with valid data, the user should be able to save the new debit card.

## Actual Result:
After completing all the fields with valid data and tapping on the "Save" button, the user receives an "Make sure you've entered a valid debit card" error message and is unable to save the new debit card.
The card number used was taken from the "Sandbox Test Cards" link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/47785a02-ae18-466d-9d45-51a7628eb23b

![Bug6550877_1721762381934!842fa884-2634-45cf-b05c-c78f95fc2433](https://github.com/user-attachments/assets/4182c42c-fb24-4837-bc3c-fe81a27dc073)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
We are going to remove debit cards temporarily as a payment device, so let's close this issue for now.
