### ISSUE TITLE
Search - Not here page opens in LHN after leaving expense thread via Search RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46195]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4764625
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM with any user
3. Submit two manual expenses
4. Go to transaction thread of any expense
5. Send a message
6. Go to Search
7. Click on the expense which has message sent from Step 5
8. Click on the report header
9. Click Leave

## Expected Result:
App will remain on the Search page

## Actual Result:
App returns to the transaction thread, with not here page on LHN after leaving expense thread on Search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f9813cb2-9c7d-40e1-a84c-029636b0123b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by alexpensify** [comment]
I'll test it soon; this GH is on my testing list.

**Comment by alexpensify** [comment]
I'll get to this one tomorrow.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate this experience 
![2024-08-05_15-36-35](https://github.com/user-attachments/assets/c2214f35-69ba-4b98-8270-1bdf69995191)
