### ISSUE TITLE
[$125] Android - LHN - Sending a text+attachment displays text with ellipsis.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46190]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4768324)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Send a text+attachment choosing a image from gallery
4. Navigate to LHN

## Expected Result:
Sending a text+attachment must display text+attachment in LHN

## Actual Result:
Sending a text+attachment displays text with ellipsis

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8c10f84d-4d8e-45e0-b894-d125f1c792d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143efae25694044fa</li>
        <li>Upwork Job ID: 1819194218797436242</li>
        <li>Last Price Increase: 2024-09-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by lanitochka17** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by RachCHopkins** [comment]
@lanitochka17 do we know what "Sending a text+attachment must display text+attachment in LHN" means? I can't decipher the meaning of this statement, what should show in the LHN?

**Comment by lanitochka17** [comment]
That is the word Attachment should be displayed instead of ...

**Comment by RachCHopkins** [comment]
Thanks @lanitochka17

**Comment by mollfpr** [comment]
@daledah Could you explain why it's only happen in native?

**Comment by mollfpr** [comment]
@daledah That's make sense to me!

The [proposal](https://github.com/Expensify/App/issues/46190#issuecomment-2264516747) looks good, but I would prefer the alternative solution incase we will use `getOptionData` in somewhere else then the `alternateText` is well formatted.

🎀 👀 🎀 C+ reviewed!

**Comment by greg-schroeder** [comment]
fyi @RachCHopkins the PR for this issue led to a regression (https://github.com/Expensify/App/issues/47248). I'm not paying folks in that issue, but they should be subject to the regression penalty in this one (if you haven't paid them yet, which it seems like you haven't)

**Comment by RachCHopkins** [comment]
@techievivek @mollfpr I can't actually tell what's going on with this issue - is someone able to give me a quick summary of where it's at?

**Comment by mollfpr** [comment]
@RachCHopkins I think it's ready for the payment summary. The original PR and follow-up PR were in production last month.

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor: @daledah to be paid $125 via Upwork
Contributor+: @mollfpr to be paid $125 via NewDot Manual Request
Upwork job [here](https://www.upwork.com/ab/applicants/1833011781153749323/job-details)

**Comment by RachCHopkins** [comment]
@daledah I have sent you another proposal!

**Comment by rohit9625** [comment]
I just saw the job on upwork but after reading the comments, I am unsure if it's fixed now or not. Could anyone please clarify?

**Comment by RachCHopkins** [comment]
Sorry for the confusion @rohit9625 - that was me trying to get a fresh offer to the person who'd already fixed the issue. 

Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by rohit9625** [comment]
> Sorry for the confusion @rohit9625 - that was me trying to get a fresh offer to the person who'd already fixed the issue. 
> 

No problem, Thanks :)

**Comment by garrettmknight** [comment]
$125 approved for @mollfpr
