### ISSUE TITLE
[$250] Workspace – System message for changed workspace name is missing

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46209]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a703@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. On an account with multiple policies in NewDOt, create an expense on one
2. Log into OldDot and find the report associated with that expense and change the policy name from X to Y
3. Back in NewDot check Workspace chat and #Admin room

## Expected Result:
There' should be a message that says "changed workspace from X to Y" in #Admin room

## Actual Result:
System message for changed workspace name is missing on #Admin room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/27d67863-d927-4ba1-8045-9a300a94a35f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f4738aed21c496c</li>
        <li>Upwork Job ID: 1818050079023186709</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by francoisl** [comment]
I can repro in prod, going to demote. FWIW it might be a backend issue where the OldDot policy change action doesn't queue Onyx updates properly.

https://github.com/user-attachments/assets/39239a19-0390-4089-a3c1-1ab2f62b8e0f

**Comment by luacmartins** [comment]
No updates yet. I'll start working on it this week.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment]
This has been fixed. Closing.
