### ISSUE TITLE
[HOLD for payment 2024-10-11] [$150] Expense - Combined report is more grayed out than the transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46200]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A ](https://expensify.testrail.io/index.php?/tests/view/4764420)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM with user that has no unsettled expense
3. Go offline
4. Submit an expense
5. Click on the expense preview to go to expense report (combined report)
6. Take note of the grayness
7. Submit another expense
8. Click on the expense preview to go to transaction thread
9. Note the difference in report grayness between Step 6 and 8

## Expected Result:
The grayness of the combined report and the transaction thread should be the same

## Actual Result:
The combined report is more grayed out than the transaction thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ff11dea1-2e7e-43ee-8433-adf0ea8e2b72

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010079feefd518ffb7</li>
        <li>Upwork Job ID: 1821119086877872721</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104088606</li>
<li>nkdengineer | Contributor | 104088608</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The combined report is more grayed out than the transaction thread

### What is the root cause of that problem?
In the combined report, we wrap the `MoneyRequestView` with an `OfflineWithFeedback`. So all item in `MoneyRequestView` is grayed out.

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/pages/home/report/ReportActionItemContentCreated.tsx#L150

But in the transaction thread report, we don't do it here

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/pages/home/report/ReportActionItemContentCreated.tsx#L106-L108

And in `MoneyRequestView` both `Receipt` labels and Receipt empty component isn't grayed out

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/components/ReportActionItem/MoneyRequestView.tsx#L422

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/components/ReportActionItem/MoneyRequestView.tsx#L474
### What changes do you think we should make in order to solve the problem?
We should wrap the component here with `OfflineWithFeedback` and pass `pendingAction` prop as `action.pendingAction`

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/pages/home/report/ReportActionItemContentCreated.tsx#L106-L108

OPTIONAL: We can also wrap receipt label and receipt empty state with `OfflineWithFeedback`

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/components/ReportActionItem/MoneyRequestView.tsx#L422

https://github.com/Expensify/App/blob/4adf0c540c31cebeb178df1f0f857a750b871eb6/src/components/ReportActionItem/MoneyRequestView.tsx#L474
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment]
Updated proposal https://github.com/Expensify/App/issues/46200#issuecomment-2250543281 to add alternative solution.

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
External, but lowered price for ease of fix

**Comment by nkdengineer** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/46200#issuecomment-2250543281) with another fix in the main solution.

**Comment by nkdengineer** [comment]
> Thank you @Krishna2323. But can we just prioritize using create pending action.
@dukenv0307 You're right. I tested when we edit a field of money request the `pendingAction` of the transaction doesn't change.

**Comment by nkdengineer** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/46200#issuecomment-2250543281)

**Comment by MariaHCD** [comment]
Apologies for the delay, reviewing this today

**Comment by MariaHCD** [comment]
Thanks for the discussion, all! Just to clarify my understanding of where we are - so far @nkdengineer's [proposal](https://github.com/Expensify/App/issues/46200#issuecomment-2250543281) was selected which would wrap the `MoneyRequestView` component with `OfflineWithFeedback`

But this approach seems to cause regressions?

While @Krishna2323's updated [proposal](https://github.com/Expensify/App/issues/46200#issuecomment-2250491123) looks to fix these regressions as well as fix the original reported bug in this issue.

Is my understanding correct?

If so, @dukenv0307 what are the considerations between the two proposals here?

**Comment by nkdengineer** [comment]
> the receipt is only greyed out when IOU action is created offline.

I believe the receipt should be greyed out when we update it offline like  the behavior when we update other fields of transaction.

https://github.com/Expensify/App/blob/c880993cb8b40fc3f7e0daf0014cc04fca508be1/src/components/ReportActionItem/MoneyRequestView.tsx#L458

We should update `pendingFields` for receipt when we replace the receipt in optimistic data, remove it in success data and failure data in `replaceReceipt` function and then use `getPendingFieldAction` for receipt [here](https://github.com/Expensify/App/blob/c880993cb8b40fc3f7e0daf0014cc04fca508be1/src/components/ReportActionItem/MoneyRequestView.tsx#L458) as well 
https://github.com/Expensify/App/blob/d43f6e1817dcc72634b0768f8aa20b4b0f1a0021/src/libs/actions/IOU.ts#L7441

Updated my alternative [solution](https://github.com/Expensify/App/issues/46200#issuecomment-2250543281) to include that

**Comment by MariaHCD** [comment]
> Users edit receipt in offline mode, should we greyed out the new receipt?
> Current behavior: It's not greyed out

Hey @Expensify/design! We're looking to confirm whether the receipt should be greyed out when an expense is edited while offline.

**Comment by dubielzyk-expensify** [comment]
Good question. @shawnborton might be better positioned to answer, but to me what I see in [this recording](https://github.com/Expensify/App/issues/46200#issuecomment-2291136732) looks right where it's faded out given it's uploaded in offline mode.

**Comment by shawnborton** [comment]
Makes sense to me, I agree.

**Comment by dubielzyk-expensify** [comment]
Yeah, I still think so cause the last action they've done haven't been uploaded online yet. We grey it out when it's "unsaved".

**Comment by shawnborton** [comment]
Yup, I agree with that.

**Comment by nkdengineer** [comment]
> because the pending action is directly used for receipt. We don't use getPendingFieldAction in case of receipt because the receipt is only greyed out when IOU action is created offline.

You said that we don't use `getPendingFieldAction` because the receipt is only greyed out when IOU action is created offline. But as we confirmed above it's a wrong behavior and we should also fix this problem and then use `getPendingFieldAction` for consistency.

**Comment by MariaHCD** [comment]
Was OOO - will catch up on this.

**Comment by MariaHCD** [comment]
Focusing on other higher priority issues - will get to this asap

**Comment by dylanexpensify** [comment]
Maria will get to this as soon as she can

**Comment by MariaHCD** [comment]
Still focusing on some other higher priority issues - will relook here later today

**Comment by MariaHCD** [comment]
Still prioritizing other issues at the moment.

**Comment by MariaHCD** [comment]
Okay, after reviewing the conversation here, I agree with @dukenv0307's chosen proposal. Let's go with @nkdengineer's proposal.

Considering we have to be a bit more careful with regressions here, I'm bumping the price to $150

**Comment by dylanexpensify** [comment]
pending hitting prod the 7 day period

**Comment by dylanexpensify** [comment]
Coming up!

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor: @nkdengineer $150 
Contributor+: @dukenv0307 $150 

Please apply/request!

**Comment by dylanexpensify** [comment]
@nkdengineer @dukenv0307 please accept offers!

**Comment by dylanexpensify** [comment]
bump @dukenv0307 @nkdengineer on accepting contract

**Comment by dylanexpensify** [comment]
Done!
