### ISSUE TITLE
[$250] Room - Invited user don't receive invite email

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46226]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: use private domain account to reproduce
1. Create a new room
2. Invite a new user to the room through the room member list

## Expected Result:
The invited user should receive an email shortly after for the invitation

## Actual Result:
The invited user don't receive an email after invitation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f8738e14-630d-49c5-81f7-1d97bffec6be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d30df18ce48ed9eb</li>
        <li>Upwork Job ID: 1817968735789467834</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by neil-marcellini** [comment]
I'm closing this because #vip-vsb is on pause and we're closing any issue that isn't external, as [explained here](https://expensify.slack.com/archives/C066HJM2CAZ/p1721760866963099?thread_ts=1721729395.916419&cid=C066HJM2CAZ)
