### ISSUE TITLE
Chat - User is logged out if a workspace is created while logged in with another device

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46224]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41665
## Action Performed:
1. Chrome incognito: Navigate to https://staging.new.expensify.com/
2. Chrome incognito: Log in with a new Gmail account
3. Chrome: Navigate to https://staging.new.expensify.com/
4. Chrome: Log in with the same account
5. Chrome incognito: Click on FAB - New workspace
6. Chrome: Navigate to Account settings - Workspaces

## Expected Result:
The user should say logged in and a workspace should be created. It should be visible with a secondary device

## Actual Result:
User is logged out if a workspace is created while logged in with another device. The workspace isn't created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/416048aa-3800-4fe2-9be3-82d3db9a8eb2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment]
@neil-marcellini and @fedirjh - assigning as it's related to https://github.com/Expensify/App/pull/41665 (is it a regression?)

**Comment by neil-marcellini** [comment]
@jliexpensify I don't see why it would be related to #41665. I think it's more that the bug happened to be found while testing that PR. I will investigate a bit. It kind of sounds like a backend issue.

**Comment by neil-marcellini** [comment]
Not reproducible. Closing.
