### ISSUE TITLE
[READY FOR PAYMENT][$125] Report fields - List type report field shows "List is required" when there is an initial value

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46223]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44139
## Action Performed:
Precondition:
- Workspace is under Control plan
- Report fields feature is enabled
- List type report field is added, and the list has an initial value
1. Go to workspace chat
2. Split a manual expense
3. Go to Troubleshoot > Clear cache and restart > Reset and restart
4. Go to workspace chat
5. Split another manual expense (because violations do not show up instantly)
6. Go to expense report

## Expected Result:
List type report field will not display "List is required" violation because there is an initial value

## Actual Result:
List type report field displays "List is required" violation when there is an initial value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2c1c330f-3552-43a2-8c2f-f9a2e2a65e8f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa66587c84d7c165</li>
        <li>Upwork Job ID: 1823770004376025525</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103527627</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by francoisl** [comment]
@thienlnam is this also something about report fields we can polish with a follow-up PR?

**Comment by Beamanator** [comment]
Assigning jack since this is part of your `Report Field Violations` Project 🙏

**Comment by Beamanator** [comment]
Also if this is under beta we can demote, is there a report fields beta?

**Comment by thienlnam** [comment]
Yeah, we definitely can address - @jnowakow another one to fix

**Comment by thienlnam** [comment]
@Beamanator That beta is for setting up report fields in NewDot - slightly unrelated to showing them, but I don't think this needs to be a blocker

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
List type report field displays "List is required" violation when there is an initial value

### What is the root cause of that problem?
After we reset the cache the field list has `value` is undefined since we use the `defaultValue` when we create the expense report.


https://github.com/Expensify/App/blob/04741f4b9c2ec7191d16abbc1ab2fe67085afb83/src/libs/actions/IOU.ts#L862-L867
### What changes do you think we should make in order to solve the problem?
We should return early if the `defaultValue` is not empty

```
if (excludedFields.includes(field.fieldID) || !!field.value || !!field.defaultValue) { 
   return; 
}
```

https://github.com/Expensify/App/blob/04741f4b9c2ec7191d16abbc1ab2fe67085afb83/src/libs/actions/IOU.ts#L862-L867

Or BE should return the `value` of `fieldList` as `defaultValue` after we create the expense report and don't change any report field.
### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment]
👋 @war-in Could we also address this issue with https://github.com/Expensify/App/issues/46215?

**Comment by war-in** [comment]
Hi 👋 @thienlnam sure! I'll take care of it

**Comment by war-in** [comment]
I went with the same approach @nkdengineer proposed (FE one, I don't know if we want to modify the backend)

cc @thienlnam

**Comment by war-in** [comment]
[PR](https://github.com/Expensify/App/pull/46425) is ready for C+ review :)

cc @allroundexperts

**Comment by nkdengineer** [comment]
@thienlnam  Can I get the compensation here since we went with my proposal https://github.com/Expensify/App/issues/46223#issuecomment-2257983537, thanks.

**Comment by thienlnam** [comment]
Since this was a regression to be fixed by the original authors and was not intended to be an external issue, does half payment ($125) work for you?

**Comment by nkdengineer** [comment]
@thienlnam That work for me.

**Comment by thienlnam** [comment]
cc @JmillsExpensify Could we please get a payment to @nkdengineer for $125?

**Comment by nkdengineer** [comment]
@thienlnam Do we need to assign me here for payment?

**Comment by thienlnam** [comment]
Bump payment for this one cc @JmillsExpensify 
https://github.com/Expensify/App/issues/46223#issuecomment-2289371246

**Comment by nkdengineer** [comment]
@JmillsExpensify Gentle bump on https://github.com/Expensify/App/issues/46223#issuecomment-2313248233

TIA

**Comment by JmillsExpensify** [comment]
Ah sorry I missed this in my filters as the payment has no date.

**Comment by JmillsExpensify** [comment]
All paid out. Closing this one.

**Comment by garrettmknight** [comment]
Payment summary:
- Reviewer: @allroundexperts $125 via Upwork

**Comment by JmillsExpensify** [comment]
$125 approved for @allroundexperts

**Comment by allroundexperts** [comment]
@garrettmknight @JmillsExpensify My payment is $250 here (which is the standard amount for a deploy blocker PR review). We paid $125 to @nkdengineer because there proposal was used by the SWM team.

**Comment by allroundexperts** [comment]
Actually, I just checked again and this was a regression issue of a PR that I reviewed. I am not due for any compensation here. I will remove the expense from the report.

**Comment by JmillsExpensify** [comment]
Ah thanks!
