### ISSUE TITLE
[$250] NetSuite - I can't toggle the "Import customers" option after making the connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46239]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4767874&group_by=cases:section_id&group_id=314239&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Customers / projects
9. Turn "Import customers" on

## Expected Result:
I should be able to enable "Import customers"

## Actual Result:
I can't toggle the "Import customers" option after making the connection. I can only enable it if I enable another "Customers / projects" option first

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e63c0dca-2100-4d34-a177-a57fe776f79c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0125a308e4402718f3</li>
        <li>Upwork Job ID: 1826709844508947005</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 103800560</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @yuwenmemon</details>

**Comment by lanitochka17** [comment]
@muttmuure FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment]
@yuwenmemon @mananjadhav @shubham1206agra FYI

**Comment by muttmuure** [comment]
I think this is to do with how customers and projects get bundled into the same list when importing them

**Comment by muttmuure** [comment]
But I think we need a more graceful UX than what is currently there. The button can't just be unresponsive.

**Comment by muttmuure** [comment]
Asked about this here: https://expensify.slack.com/archives/C06ML6X0W9L/p1722626892897019

**Comment by muttmuure** [comment]
This is not overdue

**Comment by muttmuure** [comment]
This is not overdue

**Comment by muttmuure** [comment]
Asked if someone can pick this up

**Comment by muttmuure** [comment]
Adding hot pick label

**Comment by yuwenmemon** [comment]
Will take a look.

**Comment by yuwenmemon** [comment]
Can reproduce it, but this seems like an External issue to me

cc @mananjadhav 


https://github.com/user-attachments/assets/e07e190e-2d9d-4007-b9d2-457b26c51901

**Comment by mananjadhav** [comment]
Hmmm is the API being called when you click? I can check this tomorrow.

**Comment by yuwenmemon** [comment]
API is not being called when clicked, no - hence why I do think it's a front-end issue:

https://github.com/user-attachments/assets/68305daf-f70a-488d-9f0d-165bb931ec3d

Yeah I'm able to reproduce it consistently, it only happens right after you make the connection and "Import Customers" needs to be the first setting you try to edit.

**Comment by DylanDylann** [comment]
Taking over this issue from [Slack thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1724924228335929)

**Comment by DylanDylann** [comment]
@yuwenmemon In this bug, although the connection is successful, It seems the FE doesn't receive `config?.syncOptions?.mapping value`

It caused otherFieldValue is undefined --> newValue is undefined --> there are no happen when clicking on

https://github.com/Expensify/App/blob/8c69c58dfa7f6a9ab079e560ff026c1aed12be8e/src/pages/workspace/accounting/netsuite/import/NetSuiteImportCustomersOrProjectsPage.tsx#L42-L53

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
