### ISSUE TITLE
Subscription – Annual subscription and Pay-per-use options are not displayed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#46245]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating https://github.com/Expensify/App/pull/46126
**Version Number:** 9.0.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new expensifail account
3. Create a workspace
4. Go to More features
5. Toggle on Report fields
6. Click Upgrade to upgrade to Control
7. Go back to Account settings
8. Click Subscriptions
9. Scroll to Subscription details

- Change subscription to "Pay-per-use"
- Note that the page opens without issue
- Now delete the Control workspace
- Go back to Account settings
- Verify that subscription is not shown anymore
- 

## Expected Result:
"Annual subscription" and "Pay-per-use" options should be present in Subscription details section

## Actual Result:
"Annual subscription" and "Pay-per-use" options are missing in Subscription details section
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/adb7ff71-ac7f-4047-9adf-79dfe25fda6f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
I'll test it soon; this GH is on my testing list.

**Comment by alexpensify** [comment]
I'll get to this one tomorrow.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience in Staging 

![2024-08-05_15-46-28](https://github.com/user-attachments/assets/144f8927-0dac-4228-a14a-572db7a382b8)
