### ISSUE TITLE
[$250] [HIGH] [API Reliability] Multiple read API calls done when opening the workspace feature pages

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#46240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @koko57 
**Slack conversation:** N/A

## Action Performed:
Break down in numbered steps

Prerequisite: wide layout

1. Go to Workspaces -> choose a workspace.
2. Open devtools.
3. Click on any of More features LHN menu.
4. Observe that if a request is sent when opening a page the request goes twice with the same payload.
5. Check other features - verify that the request also is sent twice
<img width="1371" alt="Screenshot 2024-07-23 at 16 39 21" src="https://github.com/user-attachments/assets/ebc05127-edbf-472c-996c-74a69b7a1975">
(screenshot taken when testing on `main`)

## Expected Result:
Describe what you think should've happened

The request is sent only once when opened

## Actual Result:
Describe what actually happened

The read commands are made twice

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari - wide
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7908d738abe9393</li>
        <li>Upwork Job ID: 1816583554727952262</li>
        <li>Last Price Increase: 2024-07-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by mountiny** [comment]
Oh wait @koko57 isnt this because of the strict mode and because that is re-rendering everything twice? Have you tried with the strict mode disabled? I have not

**Comment by neonbhai** [comment]
This is indeed because of strict mode, turning it off fixes the issue:


https://github.com/user-attachments/assets/ea3284ad-030b-49db-865b-1e559a053ac7

**Comment by mountiny** [comment]
God damn, how many times will I step to the same water

**Comment by mountiny** [comment]
Thanks @neonbhai
