### ISSUE TITLE
[HOLD for payment 2024-08-09] [Simple AA in NewDot] Support `FORWARDED` report action in NewDot

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#46241]
~cc @tgolen as this relates to your project: https://github.com/Expensify/Expensify/issues/396071~

Actually i think this relates to mine, https://github.com/Expensify/Expensify/issues/393839

# Problem:

Currently, we do not support showing the `FORWARDED` Report Action in NewDot. The report action currently is displayed like this in NewDot:

<img width="992" alt="Screenshot 2024-07-25 at 2 42 08 PM" src="https://github.com/user-attachments/assets/cf7b9da5-83ba-4ade-be0b-6b048e0af41c">

We started writing the code [here](https://github.com/Expensify/App/blob/828e8c0e1cbf3022c1feac4120678e66e030583f/src/types/onyx/OldDotAction.ts#L125-L134), but it remains commented out

We need to implement this b/c we are bringing Control workspaces to NewDot. Report "Forwarding" happens when:
1. Control workspace has "Advanced Approvals" enabled
2. Submitter submits report to Approver
3. Approver **Forwards & Approves** to Final approver

# Solution:

Support it!

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by Beamanator** [comment]
@shawnborton I tagged design here b/c I want to make sure we get the correct copy for showing the `Forwarded` report action in NewDot.

The current copy in OldDot is: `You approved and forwarded this report to <next approver>`

I don't think we want to mention the term "Forwarded" / forwarding concept in NewDot, we want to make it always read "Approve" IIRC, so I suggest one of these copies:
1. `approved $<amount>` (this follows the existing `APPROVED` report action text)
2. `approved and passed to <next approver> for further approval`

**Comment by shawnborton** [comment]
Hey @Beamanator appreciate the tag! For these kinds of things, this is more of a copy/marketing thing though I think, so let's see if @jamesdeanexpensify has a strong opinion. 

I'm not sure the best way to word this though... maybe something simple like:

> approved $XX.XX and then sent to XXXX 


cc @trjExpensify @Expensify/design for more thoughts too

**Comment by trjExpensify** [comment]
Hm yeah, tricky one.. this wording has always been a bit confusing. The next steps in the header communicate who's next up to approve, right? Further, the next in-line will receive a whisper message in the workspace chat to be notified of the action they need to take? 

So I'm sorta' inclined to just stick with the standard for the time being: 

>approved $100.00

**Comment by shawnborton** [comment]
Oh those are good points about the next steps banner, I would be cool with an approach like you are suggesting.

**Comment by JmillsExpensify** [comment]
Sounds good to me too

**Comment by dannymcclain** [comment]
Yeah I'm down for that approach too. Nice and simple.

**Comment by jamesdeanexpensify** [comment]
sounds good to me!

**Comment by shawnborton** [comment]
Not overdue Melvin, we have agreement above on what copy to use for the system message.

**Comment by Beamanator** [comment]
Nice, thanks for the discussion y'all! Sounds like we're going with:

> approved $100.00

👍

**Comment by Beamanator** [comment]
PR is ready for review 👍  assigning @mananjadhav here since you were auto-assigned to review the PR! 🙏

**Comment by Beamanator** [comment]
PR is on staging as of yesterday, hopefully will get to prod today

**Comment by sakluger** [comment]
I'll add the payment summary tomorrow. @mananjadhav, can you please propose regression test steps for this one?

**Comment by sakluger** [comment]
**Summarizing payment on this issue:**

Contributor+: @mananjadhav $250, please request on Newdot

**Comment by sakluger** [comment]
@mananjadhav please also propose new regression test steps 🙏

**Comment by sakluger** [comment]
@mananjadhav friendly bump to propose regression steps.

**Comment by sakluger** [comment]
Manan is out, posting for Melvin.

**Comment by mananjadhav** [comment]
This is a new feature so we don't have an offending PR. I am not sure if we have regression tests managed centrally for this. But specifically for this issue we can take the steps from the PR.

**Regression Test Proposal**

 1. In OldDot, create a Control policy with 3 members:

    1. The owner
    2. An `approver` (`user` role)
    3. An `submitter` (`user` role)

 2. In OldDot, make sure the policy has `advanced approvals` turned on (in the `Members` tab), with these settings:
    
    1. `submitter` has `submitsTo` set to the `approver`
    2. `approver` has `approves to` / `forwardsTo` set to the `owner`
 3. Make sure the policy has `isPolicyExpenseChatEnabled` set to true, by running this in the console when you have that policy open in OldDot:
    ```
    p = Policy.getCurrent();
    p.policy.isPolicyExpenseChatEnabled = true;
    p.save();
    ```
 4. In OldDot, as the `Submitter`, create a report & add an expense to it, then submit the report.
 5. As the `approver`, log in to both OldDot & NewDot in separate tabs
 6. As the `approver`, in OldDot, "Approve & Forward" the report
 7. Verify that in NewDot, the report action `approved $<amount` shows up live both in the report & in the LHN
 8. While in OldDot the report action reads "Approved and forwarded to ..." but we agreed we just want it to say `approved $<amount` in NewDot.
 9. For the report action item, right-click the item and click on `Copy to clipboard`. Verify on paste it shows `approved $<amount`.

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by sakluger** [comment]
Awesome, thanks Manan!
