### ISSUE TITLE
The keyboard overlaps the capture button when replacing the receipt image.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46250]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @suneox
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721929878741009

## Action Performed:
1. Go to self DM
2. Submit a track manual expense (without receipt)
3. Go to transaction thread
4. Tap on the receipt placeholder
5. Take a photo
6. Tap on the receipt image
7. Select three dots option then select replace
If the keyboard overlaps not overlap try to focus to input few times and repeat from step 6

## Expected Result:
The keyboard should not overlap the capture button when replacing the receipt image
## Actual Result:
 The keyboard overlaps the capture button when replacing the receipt image
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/03f90469-e300-4be0-af1d-ae6716d82fa5

https://github.com/user-attachments/assets/47a72e8b-bee8-44dd-9f7a-ff724ce0e5ee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
I agree @tienifr - let's retest this once that is in staging

**Comment by slafortune** [comment]
Not deployed yet - on hold

**Comment by slafortune** [comment]
Still on hold

**Comment by slafortune** [comment]
Can't reproduce - 

https://github.com/user-attachments/assets/cbda4b42-8a0b-4e4f-bde3-197bca406276
