### ISSUE TITLE
[$250] Expense - Shouldn't show "delete receipt" option for eReceipts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4768840
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in to [applausetester+pendingreceipt@applause.expensifail.com](mailto:applausetester+pendingreceipt@applause.expensifail.com)
3. Open a card transaction (the one with colorful receipt) - https://staging.new.expensify.com/r/7013138223320456
4. Click on the receipt
5. Click 3-dot menu
6. Click Delete receipt
7. Click Add receipt and upload a receipt

## Expected Result:
The receipt will change after deleting or adding a receipt

## Actual Result:
The receipt remains the same after deleting or adding a receipt for card transaction

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a5d57352-ab83-4580-8018-335d7e49e582

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105eee26e9f25403e</li>
        <li>Upwork Job ID: 1818000401430758165</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103437449</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alitoshmatov** [comment]
Is there a way for me to test this eReceipts on my account?

**Comment by puneetlath** [comment]
Hmm, I think you'd need to use mock data. As the only way to get one for real is to connect a credit card to your account to import transactions.

**Comment by puneetlath** [comment]
@alitoshmatov how can I help you move this forward?

**Comment by alitoshmatov** [comment]
@gijoe0295 Thank you for your proposal, I don't think you are in a right direction with your solution we have direct access to `isEReceipt` variable that [context](https://github.com/Expensify/App/blob/5a2602c441170093e99850e2194808218b0aa838/src/pages/TransactionReceiptPage.tsx#L37C11-L37C21).

**Comment by alitoshmatov** [comment]
I am a little bit confused about expected result, the title says don't show `delete receipt`, the expected result says 
> The receipt will change after deleting or adding a receipt

If we don't want any action on the receipt we can go with @daledah 's proposal which correctly removes all editing actions from receipt

**Comment by puneetlath** [comment]
Correct, we shouldn't show the option to delete an eReceipt. Assigning @daledah

**Comment by alitoshmatov** [comment]
The PR was deployed to [production](https://github.com/Expensify/App/pull/47031#issuecomment-2296918667) 2 weeks ago, waiting for payment

cc: @puneetlath

**Comment by puneetlath** [comment]
Ah got it. Can you complete the checklist @alitoshmatov?

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/29474
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/29474#issuecomment-2343993843
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. 

**Regression Test Proposal**
1. Open a card transaction with eReceipt
2. Click on the receipt
3. Make sure there is no three dot, which means we can not perform any action on this receipt

**Comment by puneetlath** [comment]
Regression test issue: https://github.com/Expensify/Expensify/issues/427573

I paid @alitoshmatov. @daledah looks like you weren't auto-hired for some reason. Can you link me your upwork profile so I can pay you?

**Comment by puneetlath** [comment]
Offer here: https://www.upwork.com/nx/wm/offer/103916509

Please ping me on this issue when you've accepted @daledah

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
