### ISSUE TITLE
[HOLD for payment 2024-08-29] NetSuite - "Displayed as" option not visible when "Cross-subsidiary customer/projects" is on

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46288]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Customers / projects
9. Turn "Cross-subsidiary customer/projects" on

## Expected Result:
"Displayed as" option should be visible

## Actual Result:
"Displayed as" option isn't visible when "Cross-subsidiary customer/projects" is turned on. It's visible if the "Import customers" or "Import projects" options are on

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1c1fa5c0-8d32-4a50-91b2-eb32d6d068e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by Christinadobrzyn** [comment]
I think this is expected, but I am [checking with the team](https://expensify.slack.com/archives/C06ML6X0W9L/p1722024847603939). 

https://github.com/user-attachments/assets/b93e6e95-4c57-4e00-9cde-73dc65e64b43

**Comment by Christinadobrzyn** [comment]
Following the discussion https://expensify.slack.com/archives/C06ML6X0W9L/p1722270735583049?thread_ts=1722024847.603939&cid=C06ML6X0W9L

**Comment by Christinadobrzyn** [comment]
I'm ooo today so moving this daily and I'll review tomorrow.

**Comment by Christinadobrzyn** [comment]
Pushing along convo here - https://expensify.slack.com/archives/C06ML6X0W9L/p1722460695004909?thread_ts=1722024847.603939&cid=C06ML6X0W9L

**Comment by Christinadobrzyn** [comment]
Okay the [decision](https://expensify.slack.com/archives/C06ML6X0W9L/p1722613254520959?thread_ts=1722024847.603939&cid=C06ML6X0W9L) is to hide the "Cross-subsidiary" option when Customers and Projects are disabled. 

<img width="864" alt="image" src="https://github.com/user-attachments/assets/6060259d-cb0d-4212-a7b5-552070190327">

@yuwenmemon there was mention of you working on this in the chat - is that true or can this be external?

**Comment by Christinadobrzyn** [comment]
waiting for this to get picked up internally.

**Comment by Christinadobrzyn** [comment]
checking to see if anyone has the bandwidth to grab this - https://expensify.slack.com/archives/C06ML6X0W9L/p1722979210418789

**Comment by Christinadobrzyn** [comment]
Note for Melvin - This is internal so we're waiting for a volunteer

**Comment by Christinadobrzyn** [comment]
Searcing for a volunteer!

**Comment by Christinadobrzyn** [comment]
I think this might be something that Yuwen will want to take when they are back so I'm going to keep this daily for now and follow up with them when they return!

**Comment by yuwenmemon** [comment]
Picked up!

**Comment by Christinadobrzyn** [comment]
Yippee! Thanks @yuwenmemon!

**Comment by Christinadobrzyn** [comment]
updated for Melvin - PR is in the works - https://github.com/Expensify/App/pull/47635

**Comment by Christinadobrzyn** [comment]
Prepping for payment - Payouts due:

- [ ] Contributor+: $250 @mananjadhav 

@mananjadhav you are paid in newDot? Is there anyone else that needs payment for this job?

**Comment by Christinadobrzyn** [comment]
@mananjadhav, did you participate in this as C+ - should you be paid for this job?

**Comment by mananjadhav** [comment]
Yes I helped with the review and I would be paid for it.

**Comment by mananjadhav** [comment]
@Christinadobrzyn can you please add a payout summary?

Also in terms of the checklist, I wouldn't call this a bug as the `Displayed as` was only toggled based on `Import project` and `Import customers` switches.  The `Cross-subsidiary customers/projects` toggle was designed to work independently.

I don't think we need a regression test for this one.

**Comment by Christinadobrzyn** [comment]
Perfect thanks @mananjadhav  - here's the payment summary - https://github.com/Expensify/App/issues/46288#issuecomment-2313556917

**Comment by mananjadhav** [comment]
Thanks @Christinadobrzyn. I'll be raising it on NewDot.

**Comment by Christinadobrzyn** [comment]
Sounds good! Here's the [payment summary](https://github.com/Expensify/App/issues/46288#issuecomment-2313556917) for the NewDot payment. 

Closing this as complete!

**Comment by garrettmknight** [comment]
$250 approved fro @mananjadhav
