### ISSUE TITLE
[Awaiting payment 2024-08-26][$250] QBO - Main and sub tags disappear after renaming main tag with same name as other main tag

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46283]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO
- Multi tags are imported from QBO
1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags
3. Click on any main tag
4. Click on the name field
5. Enter the same main tag name as the other main tag and save it

## Expected Result:
App will throw an error that the existing name has already been used

## Actual Result:
App does not throw an error. The other main tag together with the sub tags disappears and the sub tags become standard tags (no longer multi tags)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6acd49ac-28c1-46ae-9032-e41904a9f2cf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ff59768d2accba6</li>
        <li>Upwork Job ID: 1818882074670225826</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment]
Tested this today and the tag list functions as described in the OP comment. Able to repro easily.

**Comment by strepanier03** [comment]
Aaah, missed this one with the failed automation. Sorry about that everyone. 

Doing the payment summary now.

**Comment by strepanier03** [comment]
### Payment Summary

- $250 - @Ollyws via New Expensify manual request
- $250 - @daledah via Upwork - Please apply for the job [here](https://www.upwork.com/jobs/~010ff59768d2accba6) or share your Upwork profile with me so I can hire you.

@garrettmknight - All your's!

**Comment by strepanier03** [comment]
I'll check later this afternoon for the Upwork job.

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws

**Comment by strepanier03** [comment]
@daledah - Bump on sharing your Upwork profile with me or applying for the job. Thanks!

**Comment by strepanier03** [comment]
@daledah - I've just sent over the [offer](https://www.upwork.com/offer/103740039).

**Comment by strepanier03** [comment]
Finishing up now.

**Comment by strepanier03** [comment]
Paid and closed the contract, thanks everyone!
