### ISSUE TITLE
Account - tester+domaincard@applausecard.expensifail.com has no access to expense details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46292]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** tester+domaincard@applausecard.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with [tester+domaincard@applausecard.expensifail.com](mailto:tester+domaincard@applausecard.expensifail.com)
2. Navigate to the workspace chat for "Domain Card tests - DO NOT DELETE"
3. Verify there's a report that contains the expenses related to the assigned domain card
4. Click on the report
5. Verify you can see the individual expenses
6. Click on a individual expense

## Expected Result:
User has access to the expense details in the report "Domain Card tests - DO NOT DELETE"

## Actual Result:
No access to the expense details in the report "Domain Card tests - DO NOT DELETE"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3ac61cc1-ac7a-41ca-97c5-049b82fd200f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment]
>Log in with [tester+domaincard@applausecard.expensifail.com](https://www.expensify.com/_support/?supportEmail=tester%2Bdomaincard%40applausecard.expensifail.com&comment=better%20supportal%20issue%20nubmer%3A%2046292&location=_support/)

How can I do this? Do we get these emails in our inbox too?

**Comment by twisterdotcom** [comment]
I can't recreate this with that email.
