### ISSUE TITLE
[$250] [HOLD for payment 2024-08-09] Avoid calling getOrderedReportIDs on mobile

### ISSUE THREAD

**Issue by hurali97** [Expensify/App#46291]
### Description:

This issue is part of investigations rooted from this slack [thread](https://expensify.slack.com/archives/C05LX9D6E07/p1721060786438019). Amongst our findings, we discovered that `getOrderedReportIDs` is being called a lot of times and each call to this function is really expensive. Upon investigation, it occurred to us that the number of calls to `getOrderedReportIDs` is legit based on the actions. For eg, consider a case where we open a report which has expenses, click on a expense, it opens the expenses list, clicking on one expense, navigates us to the detail. Now, navigate back until you're on LHN. This is roughly 6-7 steps and we have `useReportID` being re-rendered 6-7 times for this set of actions because of the `currentReportID` being changed, which seems the correct behaviour.

Now, if we can reduce the impact of this re-render by not re-calculating `getOrderedReportIDs` function on mobile devices because in the above case, while we are on web and desktop, we attach an item in LHN when we click on an expense, which happens because we re-calculate `getOrderedReportIDs` each time the `currentReportID` changes if it's not already calculated. Also, when we navigate away from that new LHN item it is removed from the LHN. 

Now, on mobile this is not important because when we click on an expense from ReportScreen, we are navigating to another screen, so LHN is never displayed and we don't need bother re-calculating `getOrderedReportIDs` on mobile.

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133e161250d414c82</li>
        <li>Upwork Job ID: 1825736030332418485</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

**Comment by dangrous** [comment]
I'm going to close this out since I think we're all set but if I'm missing a payment or anything else let me know and I can reopen.

**Comment by c3024** [comment]
@dangrous 

I reviewed the PR #46276. Can you please reopen this for payment and assign a BZ? Thanks.

**Comment by dangrous** [comment]
Oops yep!

**Comment by dangrous** [comment]
Hey @RachCHopkins ! Can you help with payment for @c3024 's review of the associated PR?

**Comment by RachCHopkins** [comment]
I'll get it sorted tomorrow @dangrous!

**Comment by RachCHopkins** [comment]
@c3024 I was unable to invite you to the job as your name is not in your GitHub profile. Can you please add it, and grab the job? Then I can pay you!

**Comment by c3024** [comment]
Added my name to my GitHub profile. 
Applied for the job.
Here is my Upwork profile.
https://www.upwork.com/freelancers/~0105555e2f227dbf47
Thanks!

**Comment by RachCHopkins** [comment]
@c3024 offer sent!

**Comment by c3024** [comment]
Accepted!

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor+: @c3024 paid $250 via Upwork
Upwork job [here](https://www.upwork.com/jobs/~0133e161250d414c82)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
