### ISSUE TITLE
[HOLD for payment 2024-08-27] [$250] [Report fields] Clean-up some logic with invoice report fields 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#46303]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1721992971379529?thread_ts=1721712433.234339&cid=C06ML6X0W9L). 

Bug 1: invoice report fields are showing on `expense` reports:

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/22dd7c15-8f2c-4416-9b17-fbf18612170e">

The fieldList[0].target can be expense|invoice|paycheck

Lets make sure we only show the particular report fields on the respective report types

Bug 2: `Report fields` in `More features` is auto-enabled when connecting to an accounting solution (i.e QBO) despite not having any coding selected to import as report fields:

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/3eac9201-bab3-4f09-b065-1cd70821a311">
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/91f032ab-6ccb-4658-9b4a-62a42ae1e39d">

CC: @mountiny @JmillsExpensify 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b274cfc3d17eda0</li>
        <li>Upwork Job ID: 1816936336157983346</li>
        <li>Last Price Increase: 2024-08-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by nkdengineer** [comment]
@mountiny How can we import the report field via QBO?

**Comment by mountiny** [comment]
@nkdengineer i have asked Tom if he has some steps in mind but also feel free to make proposal for the first part

**Comment by jayeshmangwani** [comment]
Not Overdue, Awaiting Proposal

**Comment by trjExpensify** [comment]
I just connected a workspace to QBO and then the `Report fields` menu item appeared in the LHN of the workspace settings.

**Comment by jayeshmangwani** [comment]
Not Overdue, Awaiting Proposals

**Comment by JmillsExpensify** [comment]
Increasing the price so we can prioritize a fix for this issue.

**Comment by trjExpensify** [comment]
@hungvu193 you have a QBO account, right? Perhaps you want to take a shot at this.. :)

**Comment by hungvu193** [comment]
> @hungvu193 you have a QBO account, right? Perhaps you want to take a shot at this.. :) 

Yeah. Let me take a look at this one 😄

**Comment by hungvu193** [comment]
Ok I can reproduce. I'll raise a PR soon

**Comment by hungvu193** [comment]
@trjExpensify  For the first issue, the draft PR is [here](https://github.com/Expensify/App/pull/46858).

For the second one, I assume that you want to add an import section for QBO's Import Page right? If so, is there any docs for it?

**Comment by trjExpensify** [comment]
Discussing [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1722936479273009?thread_ts=1722924772.797079&cid=C06ML6X0W9L).

**Comment by jayeshmangwani** [comment]
Not overdue, Draft PR is here https://github.com/Expensify/App/pull/46858

**Comment by hungvu193** [comment]
@mountiny Can you please assign me to this issue so it won't be slipped from my K2 list? TIA 😄

**Comment by trjExpensify** [comment]
Done!

**Comment by jayeshmangwani** [comment]
@trjExpensify It appears that the automation failed, but this PR https://github.com/Expensify/App/pull/46858#issuecomment-2294133960 went to production on August 15th. The issue is now ready to be paid out

**Comment by trjExpensify** [comment]
Alrighty, payment summary as follows: 

- $250 to @jayeshmangwani for the C+ review
- $250 to @hungvu193 for the fix

Both of you can go ahead and request on ND, closing!

**Comment by jayeshmangwani** [comment]
Requested on ND as per https://github.com/Expensify/App/issues/46303#issuecomment-2312456251

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193

**Comment by garrettmknight** [comment]
$250 approved for @jayeshmangwani
