### ISSUE TITLE
[$250] Thread – Concierge chat appears when open leaved thread with deleted parent message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46306]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4771396
**Email or phone of affected tester (no customers):** applausetester+jpcategory_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open chat with user B
4. Send a message
5. Right click and select Reply in thread
6. Send a comment in the thread
7. Delete parent message
8. Click on header
9. Click on Leave thread
10. Click on reply to open thread again

## Expected Result:
There is no option to leave thread with deleted parent message

## Actual Result:
Concierge chat appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5515e130-f882-4d63-a7d5-7afa072b2dab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ff6221c6ea0904f</li>
        <li>Upwork Job ID: 1818653048130455738</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment]
I was having trouble recreating this, but had success this morning, so getting eyes on this. Thanks for your patience!

**Comment by CortneyOfstad** [comment]
Hi! Sorry for the delay here as I was OoO — reviewing everything now!

**Comment by CortneyOfstad** [comment]
> Allowing the user to leave the thread where parent message is deleted is a valid use case

This is a tough one as I personally feel this is a bit clunky, but I have witnessed this in other apps, such as Slack, where if a comment is left on a deleted message, the thread still remains, allowing for additional comments to be added/edited. 

For this, I think we should allow the thread to remain, but allow participants/commenters to be able to leave a thread at any stage, even if the parent comment/message has been deleted 👍

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment]
I am not able to recreate this either. @parasharrajat are you able to recreate/leave the chat?

**Comment by CortneyOfstad** [comment]
Bump @parasharrajat — can you please provide an update by EOD? Thank you!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by CortneyOfstad** [comment]
Based on comment [here](https://github.com/Expensify/App/issues/46306#issuecomment-2328691341) — closing!
