### ISSUE TITLE
[Workspace Feeds] Expensify card - Clicking back from issue cards RHP takes to wrong page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46305]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:*** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Enable Expensify Cards on more features for that workspace
4. Go to members page on workspace
5. Select on one member
6. Click on New card
7. Click on the back icon twice

## Expected Result:
The app navigates user back to the workspace members page

## Actual Result:
The app navigates user to the wrong page which is Expensify card page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f7476321-0a4d-4592-b254-14f07beb29d9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @koko57</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by francoisl** [comment]
@kevinksullivan I believe all the Expensify Card in NewDot stuff is still in beta, is that right? Trying to see if this should really be a blocker.

**Comment by francoisl** [comment]
Discussed 1:1, this project is still in implementation phase with multiple open issues open. Going to recategorize as internal since I believe it's being taken care of by agency contributors, but feel free to change labels if needed.

**Comment by francoisl** [comment]
@Gonals I would imagine this can be tracked in https://github.com/orgs/Expensify/projects/155

**Comment by koko57** [comment]
added to the project it'll be taken care of soon

**Comment by Gonals** [comment]
Thanks!

**Comment by koko57** [comment]
will be addressed asap

**Comment by mountiny** [comment]
Not overdue, we will tackle this, the project is behind beta

**Comment by koko57** [comment]
I'm working on it

**Comment by koko57** [comment]
PR opened https://github.com/Expensify/App/pull/47844

**Comment by mountiny** [comment]
This is done
