### ISSUE TITLE
[HOLD for payment 2024-08-05] Search - Downloaded file shows broken content

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46300]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Go to Search
5. Select the expense in Step 3 via checkbox
6. Click on the dropdown
7. Download the expense
8. Open the downloaded file

## Expected Result:
The downloaded file shows the complete expense info

## Actual Result:
The downloaded file shows broken content

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/92367ab0-1a94-413d-b668-b2c82c37c84a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment]
PR is CPd and fixes the issue

**Comment by puneetlath** [comment]
Thanks for handling it @rlinoz!

**Comment by rlinoz** [comment]
No payment is due, we can close this one.
