### ISSUE TITLE
State Dropdown not displaying properly on Company Step

### ISSUE THREAD

**Issue by Jag96** [Expensify/App#4630]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Coming from https://github.com/Expensify/App/issues/4597, breaking this into its own issue. This is a regression from https://github.com/Expensify/App/pull/3414

## Action Performed:
1. Navigate to staging.new.expensify.com/bank-account/new and fill out any values and hit continue
2. Notice that on the next step (Company step) the values for the state dropdowns are taking up more space than they should, and don't follow the design convention that the rest of the form elements follow.

## Expected Result:
Design should be consistent

## Actual Result:
Design isn't consistent

| Before | Now |
|---|---|
| ![image](https://user-images.githubusercontent.com/3981102/129274450-8f84a1f8-f15f-4b73-bce4-956246767b4e.png) | ![image](https://user-images.githubusercontent.com/3981102/129274463-3287dd76-d6a5-4c5f-8d88-2c6b69a737f8.png) |

## Workaround:
N/A

## Platform:
Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by Jag96** [comment]
Going to fix this internally by updating the `StatePicker` to use the new `ExpensiPicker` instead of the old `Picker` component

**Comment by MitchExpensify** [comment]
Thanks @Jag96 ! I assume this will also fix the dropdown mis-alignment in the Requestor step? Theres a state dropdown field there too

**Comment by Jag96** [comment]
Yes, good call I've updated that one as well

**Comment by Jag96** [comment]
PR is on staging and blocker is fixed, closing this

**Comment by isagoico** [comment]
Looks good! Checking it off the deploy blocker list. 
![image](https://user-images.githubusercontent.com/44479856/129762719-42edd9d3-aad6-4c23-bbff-80f7912830ef.png)
