### ISSUE TITLE
[Awaiting checklist] [$250] [MEDIUM] Allow non-admins to set Workspace Address on newDot when attempting to Book Travel

### ISSUE THREAD

**Issue by twisterdotcom** [Expensify/App#46313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:**

## Action Performed:
1. Ensure you're added to the `spotnanaTravel` beta
2. Create a new Workspace (becoming an Admin) as a user without access to Expensify Travel yet
3. Invite an employee to that Workspace
4. Sign in as the employee
5. Tap "Book Travel"
6. Accept Terms and Conditions

## Expected Result:
Anyone booking travel for the first time should be able to set the Workspace address regardless of role. Thus enabling to them to book trips. This works on oldDot: https://github.com/Expensify/Expensify/issues/404079

## Actual Result:
See an error.

## Workaround:
Have an admin set the Workspace address

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/af76ed43-583c-4580-9585-3a76fef80570">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01398cd8d50461c00a</li>
        <li>Upwork Job ID: 1816865684699873550</li>
        <li>Last Price Increase: 2024-07-26</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103281647</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

cc @deetergp, @rushatgabhane, @shubham1206agra

**Comment by twisterdotcom** [comment]
Assigning @shubham1206agra as he's done most of the C+ work for Travel @parasharrajat.

**Comment by rushatgabhane** [comment]
@twisterdotcom i'd like to work on this

**Comment by rushatgabhane** [comment]
PR here https://github.com/Expensify/App/pull/46333

**Comment by rushatgabhane** [comment]
Requested spanish translation - https://expensify.slack.com/archives/C02NK2DQWUX/p1722032276550199

**Comment by twisterdotcom** [comment]
Payment Summary:

- @rushatgabhane paid $250 via NewDot Manual Request
- @shubham1206agra paid $250 [here](https://www.upwork.com/nx/wm/offer/103281647) (Contributor)

**Comment by twisterdotcom** [comment]
Paid!

**Comment by twisterdotcom** [comment]
This is a new feature, so not going to go with a checklist here.

**Comment by JmillsExpensify** [comment]
$250 approved for @rushatgabhane
