### ISSUE TITLE
Hybrid app- Empty LHN and all caught message displayed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46329]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @yuwenmemon 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721940207830919

## Action Performed:
1. Launch the hybrid app
2. Observe
## Expected Result:
LHN displayed as per the priority mode
## Actual Result:
Empty LHN and a banner displayed as `Woohoo!All caught up.` message
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/5337ba51-4a98-453c-8726-64dadc7142d3" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/cc935fa5-bc42-47f8-80df-07464a0040d0" width="40%" height="40%">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
I cannot reproduce this on the new build.
