### ISSUE TITLE
[Guided Setup] Only create system DM when needed

### ISSUE THREAD

**Issue by francoisl** [Expensify/App#46320]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

This is a follow-up improvement for the "wave-collect – Build Stage 2 of Guided Setup" project
[Initial context (internal)](https://expensify.slack.com/archives/C036QM0SLJK/p1721973726186549)

### Problem
At the moment, if you invite a user, we don't show them the onboarding modal in NewDot when they first sign in.
If their account ID is odd, we also create and show the Expensify DM in the LHN, even though it is completely empty.

This is confusing because there are essentially two different welcome chats & messages (Concierge and Expensify DM) from seemingly identical bots.

<img width="1498" alt="image" src="https://github.com/user-attachments/assets/77b5c297-c859-4404-9a58-ef0a1c1d91b3">

### Solution
TBD exact solution, but either:
- only create the system DM when we need it, so that it wouldn't show up in the LHN; or
- hide the system DM (but still create it in the backend) until it has any activity

cc @anmurali 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @francoisl</details>

**Comment by francoisl** [comment]
Marking as internal until the exact course of action is determined.

**Comment by trjExpensify** [comment]
@danielrvidal @deetergp any considerations with the viral invites doc to guide which solution is best here?

**Comment by trjExpensify** [comment]
Bump on the above @danielrvidal @deetergp!

**Comment by trjExpensify** [comment]
Asked [here](https://expensify.slack.com/archives/C036QM0SLJK/p1722891130981439?thread_ts=1722872563.829979&cid=C036QM0SLJK).

**Comment by danielrvidal** [comment]
I feel like either solution is fine for the user, they would not notice the difference. So I would do whatever is the least likely to produce bugs/errors. I can't think of a reason why one is better than the other from a user perceptive. 

If one makes it faster for the user when the Expensify DM does become active, I could see going with that option.

**Comment by deetergp** [comment]
If it isn't going to be problematic for Guided Setup Stage 2 to make use of it, I don't think it will be a problem for us in Stage 3. But if I had to choose, I think I would think creating it but not surfacing it right away would be preferable.

**Comment by trjExpensify** [comment]
@francoisl does that work for you then? Can we proceed?

**Comment by francoisl** [comment]
> does that work for you then? Can we proceed?

Yes that works. I'll try to get back to this by EOW.

**Comment by trjExpensify** [comment]
@danielrvidal, do we need this issue anymore if we're going to end up killing the DM?

**Comment by danielrvidal** [comment]
Good point, I think we can close this one.
