### ISSUE TITLE
[HOLD] Hybrid app: Welcome video shows out-dated copy "Request money"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46334]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @neil-marcellini 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721943528361069

## Action Performed:
1. Set the NVP on expensify.com with the snippet `NVP.set('tryNewDot', {classicRedirect: {dismissed: "true"}});`
2. Log in to the hybrid app
3. Open the menu at the top left
4. Click Try New Expensify
5. Watch the welcome video
## Expected Result:
The video shows "Submit expense" and how to use it
## Actual Result:
 It shows the out-dated terminology/copy of "Request money", which is not present in the product at all now.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/user-attachments/assets/e2ad8095-d311-49d6-ace7-685b085ab94a" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/4051579b-df4d-4b2e-9d79-285341f9000c" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
cc @Expensify/design do you manage changes to the welcome video referenced here?

**Comment by shawnborton** [comment]
cc @jamesdeanexpensify since we were talking about this today in Slack. 

Yes @sakluger - design can handle these sorts of things with TCW. But let's wait and see what James says first, I think we have plans to redo some of this stuff already in the works?

**Comment by jamesdeanexpensify** [comment]
Hmm...the feedback I gave was in [this thread](https://expensify.slack.com/archives/C036QM0SLJK/p1721939759091819) and created [this GH](https://github.com/Expensify/Expensify/issues/415490). Outside of that, I didn't have anything in the works!

**Comment by shawnborton** [comment]
Ah got it, I was thinking of [this comment here](https://expensify.slack.com/archives/C036QM0SLJK/p1722269943032179?thread_ts=1722254811.472269&cid=C036QM0SLJK) that you had made today

**Comment by sakluger** [comment]
@ShridharGoel I don't think we plan on making this external. @shawnborton can you confirm that I should label this as internal?

**Comment by shawnborton** [comment]
We'll need to update the videos internally first, but we might be switching things up here with different welcome videos based on intent, so let's hold here for a moment until we decide. But once we have updated videos, then we can make it external to implement the changes.

**Comment by sakluger** [comment]
I put this issue on hold since it sounds like we'll likely be making bigger changes to the videos. If we end up moving forward with those bigger changes, I suggest we close this issue.

**Comment by sakluger** [comment]
@shawnborton any thoughts on long-term plans around our welcome videos? If we have near or mid-term plans to update our welcome videos, then we should close this GH issue. If we don't plan to make changes anytime soon, then we should probably change the copy in this video.

**Comment by shawnborton** [comment]
@anmurali @dubielzyk-expensify @danielrvidal thoughts on Sasha's comment above?

**Comment by dubielzyk-expensify** [comment]
Great call. I think we're looking at removing it because we have intent specific videos, but I'll let Anu or Daniel remind me if I'm wrong

**Comment by sakluger** [comment]
@anmurali @danielrvidal any thoughts on this one? When are we planning on making the intent-specific videos? Just trying to get a sense on whether we should update the current video, or close this GH issue for now in favor of waiting for the new videos.

**Comment by danielrvidal** [comment]
I don't think that video is in the flow anymore so I think it's fine to close. We removed the general welcome from the new user flow. Additionally, I think @JmillsExpensify is working on a new welcome video that we'll show to existing users coming over but that would be outside of this issue.
