### ISSUE TITLE
[CVP] [$250] Free trial of workspace mentioned in welcome message when user have no workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46338]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722036482639849

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new account and select Track in onboarding
3. Click the global + > Track
4. Choose the Submit to someone actionable mention

## Expected Result:
No mention about free trial workspace in concierge message
## Actual Result:
Mentioned about workspace in the message even if the user not created a workspace
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/504ba417-2822-4553-b4f2-6321f0b4466f" width="40%" height="40%">

https://github.com/user-attachments/assets/527eb864-77f2-427c-8a62-3721bebf7913

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa51c694d41de340</li>
        <li>Upwork Job ID: 1818323017692441626</li>
        <li>Last Price Increase: 2024-08-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by situchan** [comment]
Awaiting proposals

**Comment by VincentCorleone** [comment]
I think it is a backend issue

**Comment by trjExpensify** [comment]
I can only repro this in the `Track` > `Submit someone` flow: 

https://github.com/user-attachments/assets/0647fd64-0e7a-4cb8-87bc-ab98e15adf29

Looks like we call `OpenWorkspace` in the `ConvertedTrackedExpenseToRequest` flow ([logs for that API call](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228af1976b694bbefd-LHR%22%20AND%20timestamp%3A%5B2024-08-06T00%3A00%20TO%202024-08-07T23%3A59%5D)), and I'm not sure why @thienlnam? 

[OpenWorkspace Logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228af197731a33befd-LHR%22%20AND%20timestamp%3A%5B2024-08-06T00%3A00%20TO%202024-08-07T23%3A59%5D)

```
[104.28.159.59->/api.php] Malformed REQUEST: 'policyID' = '-1', ignoring (should match '[A-F0-9]+').
```

CC: @chiragsalian for visibility on free trial stuff.

**Comment by chiragsalian** [comment]
This looks like an internal bug. Looks like jack's already got a PR for this.

**Comment by trjExpensify** [comment]
Auth and Web PRs for this now merged, awaiting deploys.

**Comment by danielrvidal** [comment]
Doe this still need to be open? It looks like they both merged above.

**Comment by thienlnam** [comment]
Yup, looks resolved now
