### ISSUE TITLE
[Awaiting Payment][$250] Attachment - A broken video file is loaded via action menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46343]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4771740
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open [https://staging.new.expensify.com/.](https://staging.new.expensify.com/)
2. Log in with any account
3. Navigate to any conversation or create one
4. Send any video to the conversation
5. Wait for the video to upload
6. Open the action menu on the message containing the video
7. Click Download

## Expected Result:
Using the action menu, the video file should be downloaded uncorrupted

## Actual Result:
A corrupted video file is loaded via the action menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ba07d5dc-cb03-4f8a-92e6-040076a2dcc7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ea5f33ec2b35a17</li>
        <li>Upwork Job ID: 1818205757531703482</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103356880</li>
<li>Krishna2323 | Contributor | 103356881</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attachment - A broken video file is loaded via action menu

### What is the root cause of that problem?
The root cause is we lose the correct file name here:

https://github.com/Expensify/App/blob/9901ca3a554f4c2991b56862dfb8e43d2e1aba80/src/libs/fileDownload/DownloadUtils.ts#L60

This happens as when fileName is empty string, `??` operator is not triggered, 

### What changes do you think we should make in order to solve the problem?
We will use `||` operator to make sure `FileUtils.getFileName(url)` is called.


### Alterntively
We may use another variable to properly pass the param

**Comment by alitoshmatov** [comment]
@neonbhai Thank you for your proposal, your RCA is correct but the main problem here is `fileName` being empty where it shouldn't. We should fix this rather than adjusting our code to work with this issue

**Comment by alitoshmatov** [comment]
@Krishna2323 Thank you for your proposal, your RCA is correct and your solution does solve the issue of `fileName` being empty.

We can go with @Krishna2323 's [proposal](https://github.com/Expensify/App/issues/46343#issuecomment-2253776318)

C+ reviewed 🎀 👀 🎀

**Comment by danieldoglas** [comment]
I think this was deployed to production yesterday. So now we have a regression period of 7 days. cc @kadiealexander

**Comment by alitoshmatov** [comment]
Waiting for payment, PR was [deployed](https://github.com/Expensify/App/pull/46701#issuecomment-2289789642) on 14th of august

**Comment by danieldoglas** [comment]
added the correct labels and assigned @kadiealexander to be the main person responsible for this issue.

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @Krishna2323 ([offer](https://www.upwork.com/nx/wm/offer/103356881))
- [ ] Contributor+: $250 @alitoshmatov ([offer](https://www.upwork.com/nx/wm/offer/103356880))

Upwork job is [here](https://www.upwork.com/jobs/~011ea5f33ec2b35a17).
