### ISSUE TITLE
[$250] Report fields - Initial value RHP header is different before and after the field is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46341]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Select List from Type
5. Go to List values and add a few list values
6. Return to confirmation page
7. Click Initial value
8. Note that the RHP header is "Initial value"
9. Select an initial value and save the list type report field
10. Click on the added list type report field
11. Click Initial value

## Expected Result:
The Initial value RHP header should be consistent with that in Step 8 - it should also display "Initial value"

## Actual Result:
The Initial value RHP header is not consistent with that in Step 8 - it displays the report field title instead
The Initial value RHP header is different before and after the list type report field is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/239af486-ba1e-4c7e-bb80-8e402e307c9d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01290bceafd058ab5b</li>
        <li>Upwork Job ID: 1818143577370918726</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103407676</li>
<li>nyomanjyotisa | Contributor | 103407677</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by c3024** [comment]
@nyomanjyotisa 's [proposal here](https://github.com/Expensify/App/issues/46341#issuecomment-2253710951) looks good to me!

🎀 👀 🎀 C+ Reviewed

**Comment by c3024** [comment]
@bfitzexpensify 

This was deployed to production on 16th August. Automation failed here and payment is long due. Can you please check and complete the payment? Thanks!

**Comment by bfitzexpensify** [comment]
Payment all complete.
