### ISSUE TITLE
Distance - Distance and Rate field displays "Pending" after the distance rate is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46349]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4775987)
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has at least two distance rates
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a distance expense with distance rate A
4. Go to workspace settings > Distance rates
5. Delete distance rate A
6. Return to the distance transaction thread

## Expected Result:
Distance and Rate field will not display "Pending"

## Actual Result:
Distance and Rate field displays "Pending" after the distance rate is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c9548ab9-f3ca-47a3-a50d-7e949b4c753b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by twisterdotcom** [comment]
Can't reproduce this one. Will retest.

**Comment by twisterdotcom** [comment]
I still can't reproduce this one. Going to close.
