### ISSUE TITLE
Report fields- Initial value requirement error is not dismissed after deleting all list values

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46342]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Select List from Type
5. Go to List values and add a few list values
6. Return to confirmation page
7. Without selecting an initial value, click Save
8. Click List values and delete all the values
9. Click Back button to return to confirmation page

## Expected Result:
The initial value requirement error should be dismissed since there is no list value now

## Actual Result:
The initial value requirement error is not dismissed when there is no list value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/user-attachments/assets/fe9fd360-088d-4a7f-88d5-67926c278cac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by joekaufmanexpensify** [comment]
going to triage today

**Comment by joekaufmanexpensify** [comment]
I can reproduce this, but I am not convinced that this warrants prioritizing right now. It's a pretty niche flow to select a list report field, then add options, then try to proceed without setting the field listed as required, and then go back and delete all of the options you just went through the process of adding... I am not convinced that anyone will actually do this and think we should wait until a real customer experiences this before investing resources to change the behavior. 

Further, even if you do all that, the ghost form error doesn't block proceeding at all.

**Comment by joekaufmanexpensify** [comment]
Going to close this for now, but let me know if anyone disagrees!
