### ISSUE TITLE
[$250] Profile - Address section blinks when add new address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46348]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a751@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Profile> Address> Complete the necessary details> Save
2. Take a note at Address section behavior on Profile page

## Expected Result:
Address section Should not blink when add new address

## Actual Result:
Address section blinks when add new address

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fac4c7c4-f5be-48a7-8c62-1368bfaf18d4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01065cf64bab14773d</li>
        <li>Upwork Job ID: 1818065643720366498</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by perunt** [comment]
Hi, I am Taras from Margelo, an expert agency and I can work on this issue
I see that blinking as well, on mobile and web

**Comment by jliexpensify** [comment]
Sorry I missed this! Was assigned over my weekend.

All yours @perunt!

**Comment by Amoralchik** [comment]
I believe this is a server-side error. After we add or update the address, we immediately write the data to Onyx. However, the server response does not include the address field, as initially we perform a SET operation that does not include the address field.
```json
    "onyxData": [
        {
            "key": "private_personalDetails",
            "onyxMethod": "set",
            "value": {
                "addressCity": "Independence",
                "addressCountry": "US",
                "addressState": "KS",
                "addressStreet": "Quail Run",
                "addressZip": "67301",
                "addresses": [
                    {
                        "city": "Lakeside",
                        "country": "US",
                        "current": false,
                        "state": "CA",
                        "street": "Los Santos",
                        "type": "home",
                        "zip": "92040"
                    },
                ],
                "avatarThumbnail": "",
                "dob": "",
                "legalFirstName": "",
                "legalLastName": ""
            }
        },
        {
            "key": "private_personalDetails",
            "onyxMethod": "merge",
            "value": {
                "address": {
                    "city": "Queens",
                    "country": "US",
                    "current": true,
                    "state": "NY",
                    "street": "Queensboro Plaza Station",
                    "type": "home",
                    "zip": "11101"
                }
            }
        }
 ```

**Comment by perunt** [comment]
I raised [this question](https://expensify.slack.com/archives/C01GTK53T8Q/p1722340114755109) in an open-source channel this morning with all the findings, but I haven't received an answer yet.

>  However, the server response does not include the address field

It includes an address field, but it's not a relevant address. I receive string instead of object. Also, that string is predefined. It was the first test address I entered for this account, and it is newer changing
![Screenshot 2024-07-30 at 13 32 04](https://github.com/user-attachments/assets/241fbb67-8581-4b0e-98da-afce4d4e8a36)
I'm not sure if it makes sense to keep the 'address' field if we have `addresses. ' 
As a workaround, I can use addresses. But it would be nice to sync it with the backend
Are you part of the backed team?

**Comment by Amoralchik** [comment]
@perunt 
Are you part of the backed team? - No 
As a workaround, I can use addresses.  - as I mentioned before, if the user changes private details, the address is removed (probably need to retest on a newer version if you say is a string now), and if you use the last element in address array, he never know about it
I raised this question in an open-source channel this morning with all the findings, but I haven't received an answer yet. - sorry didn't notice it, I hope the answers will be of assistance.

**Comment by jliexpensify** [comment]
Not overdue

**Comment by mountiny** [comment]
Based on @perunt this requires backend fix and I think this blinking can be considered as NewDotQuality bug, although I am not sure which category exactly would this fit in, probably LOW performance.

However, looking at the video of the bug, I think its super minor and it we might be good to close. I will defer to @marcaaron though

**Comment by marcaaron** [comment]
I'm not sure I fully understand the comments that have been left here yet so far, but `address` should not be a string.

I would suspect the changes in [this PR](https://github.com/Expensify/Auth/pull/11347/files) might have something to do with it.

**Comment by marcaaron** [comment]
There are not any explicit places where we use an Onyx `set` on the `private_personalDetails` so, unfortunately this is going to be hard to debug without being able to get a stack trace. I can try to reproduce it, but also not sure about:

>I think its super minor and it we might be good to close

The backend sending data in an unexpected format does not sound minor. But might be if we don't actually use the "address" field for anything. I can't really remember why we have both. But know it's come up before cc @Beamanator.

**Comment by marcaaron** [comment]
Actually I can't repro this so I think it's been solved. Let's close.

**Comment by marcaaron** [comment]
The response body of that API request looks normal.

**Comment by arosiclair** [comment]
Yeah this probably got fixed by https://github.com/Expensify/App/pull/45751. We deprecated `address` in favor of `addresses` since that's what we store in the DB.

It looks like we do need to cleanup a couple `address` updates [here](https://github.com/Expensify/Web-Expensify/blob/ba64dd8307bd275714c5261f088399347b96af99/lib/PersonalDetailsAPI.php#L716-L724) and [here](https://github.com/Expensify/Web-Expensify/blob/ba64dd8307bd275714c5261f088399347b96af99/lib/PersonalDetailsAPI.php#L603-L612) though. They shouldn't break anything but I'll post a PR to clean them up.

**Comment by Beamanator** [comment]
Ooh I'm glad this is working and that we're going to be storing onyx data as we have in the DB. I remember some annoying discussions about this when implementing private personal details in App, glad that's all getting updated :D

**Comment by mountiny** [comment]
Ah nice, glad this is resolved! 🎉
