### ISSUE TITLE
 NetSuite - Export field has incorrect name and editable

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46351]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/cases/view/3073348)
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user has Control workspace with NetSuite connected.
1. Go to workspace
2. Click on Accounting
3. Click Export tab

## Expected Result:
1. Field "Export Reimbursable Expenses" is clickable and has "Expense Reports" selected
2. "Export company card expenses as" is not clickable and has "Vendor Bills" selected

## Actual Result:
1. Field "Export out-of-pocket expenses as" is clickable and has "Expense Reports" selected
2. "Export company card expenses as" is clickable and has "Vendor Bills" selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/94303adb-b66b-4b0f-869f-3351ffd671e5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
Hm, I'm a little confused about this one @lanitochka17. This part feels like expected behavior, but maybe there is some context I am missing? 

> Expected Result:
> "Export company card expenses as" is not clickable and has "Vendor Bills" selected

Why would we expect this to **not** be clickable? You are allowed to click in to change the export format for these expenses -- for example, Journal Entry and Expense Report are also options.

**Comment by stephanieelliott** [comment]
Gonna close per https://github.com/Expensify/App/issues/46351#issuecomment-2259370176 -- this is expected behavior
