### ISSUE TITLE
Chat – Emoji sent offline not appears in Frequently used list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46366]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4775336
**Email or phone of affected tester (no customers):** ponikarchuks+36543@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Go offline
5. Tap on the emoji picker, select any emoji and send
6. Tap on the emoji picker again

## Expected Result:
Current list of frequently used was updated with the emoji you just used

## Actual Result:
Current list of frequently used was not updated with the emoji you just used in offline. It updated when go back online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/70c0533f-1f94-496d-a8b4-5541358590b4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by RachCHopkins** [comment]
Closing per [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1722300305266909) - this is such an edge case, I don't think it's worth fixing at this stage.
