### ISSUE TITLE
[$250] Dupe detect - Paid expense appears in Review duplicates flow but unable to complete the flow

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46372]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense
4. Pay the expense
5. Submit another two same expenses (same amount, date and merchant) as expense from Step 3
6. Go to transaction thread of any of the submitted expense from Step 5
7. Click Review duplicates
8. Click Keep this one on the paid expense (from Step 4)
9. Click Confirm
10. Note that the other two expenses are not removed
11. Go to transaction thread of any of the submitted expense from Step 5
12. Click Review duplicates
13. Click Keep this one on any of the unpaid expense (from Step 5)
14. Click Confirm
15. Note that the process fails and Review duplicates button reappears

## Expected Result:
In Step 8, the paid expense should not appear in Review duplicates flow if we cannot keep only the paid one (Step 10)

## Actual Result:
In Step 8, the paid expense appears in Review duplicates flow and we cannot keep only the paid one (Step 10)
We also cannot keep only the unpaid one (Step 15) after attempting to keep only the paid expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/731d19e9-7c4a-4897-a442-db366f5e4dda

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01add0c19e8ce4b462</li>
        <li>Upwork Job ID: 1817919014389694342</li>
        <li>Last Price Increase: 2024-08-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
adding external and to project

**Comment by zanyrenney** [comment]
Hey there @parasharrajat please can you review the proposals above and let me know if we can move forward with either of these.

**Comment by techievivek** [comment]
Looks like we are returning transactions from other reports as well.

**Comment by techievivek** [comment]
Not overdue, already commented above.

**Comment by JmillsExpensify** [comment]
> Looking for some help here. Are transactions from other reports expected to show up on the review duplicates page?

Yes, that's the core design of the feature, showing duplicates no matter whether they are on the same report or not. cc @trjExpensify

**Comment by trjExpensify** [comment]
That's a good question. I think dupes do get flagged on approved and paid reports, but perhaps @pecanoro can confirm. I'm unsure how that's supposed to technically work today on OldDot when it comes to merging expenses and deleting (potentially) a dupe on an approved/paid report? 🤔

**Comment by JmillsExpensify** [comment]
@pecanoro can you confirm? I would be surprised if we are ignoring an expense that an admin has paid, which has the same date and amount that someone has just potentially re-submitting, though that scenario also creates problems in itself, since to @trjExpensify's point, you can't merge a paid/approved expense.

**Comment by pecanoro** [comment]
I need to test this on oldDot tomorrow. We don't compute violations on approved and paid reports, but I am not really sure if, when trying to find duplicates from an expense on an open report, we flag paid expenses as potential duplicates.

**Comment by zanyrenney** [comment]
Hey @pecanoro I'm just following up on this one if you managed to test it on olddot so we can move ahead here? Thanks!

**Comment by pecanoro** [comment]
In oldDot, it also gets flagged if there is an expense in a reimbursed report. But the one in the open report is the one that gets flagged:

![image](https://github.com/user-attachments/assets/3d324353-2615-4174-aabb-7015bbc705f4)

![image](https://github.com/user-attachments/assets/695685d3-0c0e-4d49-851c-d1d37061fa01)

**Comment by pecanoro** [comment]
But this is the difference, you can't merge them if one of them is in an approved or reimbursed report, you can only click ignore to dismiss the violation:

![image](https://github.com/user-attachments/assets/c06c240f-85f6-48fe-9e16-1ab6b9b22bb8)

**Comment by pecanoro** [comment]
My opunion is that we should only leave the `Keep All` option and show a similar message to the one in oldDot to let them know they have to be in open or submitted reports. But @JmillsExpensify and @trjExpensify probably have a opinion that makes more sense form the design point of view

**Comment by trjExpensify** [comment]
>My opunion is that we should only leave the Keep All option and show a similar message to the one in oldDot to let them know they have to be in open or submitted reports

I was thinking the same, so like: 

![image](https://github.com/user-attachments/assets/f628d1e7-3ac7-451e-b4d7-e7704b17cf61)

**Comment by trjExpensify** [comment]
Yeah, to Rocio's point:

> But the one in the open report is the one that gets flagged:

The duplicate violations doesn't show on the expense on the approved / reimbursed report.

**Comment by techievivek** [comment]
Thank you for confirming the expected behavior. So we want to have

1. We do not want to display duplicate violations for approved/reimbursed expenses.
2. Instead, we should display a message under the Keep All button indicating that some duplicates have already been approved or reimbursed. And we want to get rid of the `keep this one` option completely from UI.

@nyomanjyotisa @daledah, can you please update the proposal accordingly? Thanks.

**Comment by techievivek** [comment]
> A minor improvement to point 2 would be that the keep this one will be hidden on paid or approved expenses only. Imagine there are 3 duplicates on the review screen and one of them is approved so that one will not have keep this one button.

Make sense 👍

**Comment by JmillsExpensify** [comment]
We can't filter paid expenses though, because this is the core feature (preventing expenses that have been paid already from being paid twice). If we are ignoring the paid expenses on `Keep all` and then no showing `Keep this one` on paid expenses, then we don't need a backend change, right?

**Comment by dylanexpensify** [comment]
TY @parasharrajat! @daledah when can we expect a PR ready for review?

**Comment by pecanoro** [comment]
Sorry, I was on vacation. I thought we were going to simply not allow to resolve duplicates if one of them was in a paid report as we mentioned [here](https://github.com/Expensify/App/issues/46372#issuecomment-2275532637), so I am not sure if I understand your question.

**Comment by pecanoro** [comment]
No, the only option would be `Keep All`

**Comment by pecanoro** [comment]
Yes, approved and paid!

**Comment by dylanexpensify** [comment]
@daledah bump on this:
> OK. Got it. Thanks for the clarification. @daledah, it looks like there is a small divergence from what we implemented on the PR.

> Could you please hide keep this one button when there are any paid expenses in the duplicate? Thus only keep All will function.

**Comment by techievivek** [comment]
It has been more than 2 weeks since the PR has hit production. I think we can move with the payment here. cc @zanyrenney, thanks.

**Comment by zanyrenney** [comment]
Seems like the automation is still failing.

**Comment by zanyrenney** [comment]
**payment summary**

$250 for @parasharrajat can be requested through ND.
$250 for @daledah needs to be paid through upwork.

@daledah can you apply to the job please?

**Comment by zanyrenney** [comment]
@daledah still hasn't applied to the job,.

**Comment by zanyrenney** [comment]
Hey @daledah offer sent!!

**Comment by zanyrenney** [comment]
### payment summary

$250 for @parasharrajat can be requested through ND.
$250 for @daledah needs to be paid through upwork. PAID

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
