### ISSUE TITLE
[Pending Payment][$250] IOU - mWeb - Duplicate red dot error not shown in conversation & report page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46375]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login with new gmail account
3. Create a new workspace
4. Tap on a workspace chat
5. Create 2 expenses with same amount and merchant
6. Open each expense and note duplicate red dot shown under merchant

## Expected Result:
Duplicate red dot error must be shown in conversation & report page

## Actual Result:
Duplicate red dot error not shown in conversation & report page but error displayed in expense details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cba4cb28-f3d9-4f4e-aec3-5e323a581b94

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102ecd093c6e7220c</li>
        <li>Upwork Job ID: 1818074477646562605</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 103430539</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by cead22** [comment]
Just for duplicates and for violations with `type = violation`. So I think the first proposal is more correct. @pecanoro what do you think?

**Comment by pecanoro** [comment]
Yes, what @cead22 said sounds good!

**Comment by pecanoro** [comment]
Did automatization fail for this issue?

**Comment by VictoriaExpensify** [comment]
Yeah it has - will get on it. Thanks for flagging @pecanoro

**Comment by VictoriaExpensify** [comment]
**Payment summary:**
Contributor: @nyomanjyotisa paid $250 via [Upwork](https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/38030095)
Contributor+: @thesahindia owed $250 via NewDot

Sorry for the delayed payment, thanks for your work on this issue.

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
