### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] Dupe detect-Removing receipt on confirmation page also removes receipt from the actual expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46373]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two expenses with same amount and merchant, but one with receipt and one without receipt
4. Click on the transaction thread of the expense with receipt
5. Click Review duplicates
6. Click Keep this one on the expense with receipt
7. Proceed to confirmation page
8. Click on the receipt on the confirmation page
9. Remove the receipt

## Expected Result:
Since user is removing the receipt from the confirmation page, the receipt on the actual expense will not be removed, as the changes have not been "confirmed" yet

## Actual Result:
When user removes the receipt from the confirmation page, the receipt on the actual expense is also removed, even when the Confirm button is not clicked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c25833e1-215e-4932-8637-00b09a0b3b1b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e50d0c63fac1b4f3</li>
        <li>Upwork Job ID: 1818139062818817325</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 103539656</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by lanitochka17** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by JmillsExpensify** [comment]
@sobitneupane mind reviewing the proposals so far?

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/46373#issuecomment-2254463503) from @Krishna2323 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment]
I agree, they should be able to open the receipt in the full screen mode, but it's read-only, like the other fields on the expense in this dupe confirmation screen - so we should remove the three dot overflow menu in this case:

<img width="783" alt="image" src="https://github.com/user-attachments/assets/5825cd2c-92e3-43b0-9c41-e848c7c415f3">

CC: @pecanoro for vis as well :)

**Comment by sobitneupane** [comment]
Bump @gijoe0295 https://github.com/Expensify/App/issues/46373#issuecomment-2273014517

**Comment by JmillsExpensify** [comment]
If we don't get a response in the next 24 hours, can we prioritize Krishna's proposal?

**Comment by sobitneupane** [comment]
Thanks for the update, @gijoe0295 

I am not in favor of the route check idea proposed as an alternative solution in @Krishna2323's [proposal](https://github.com/Expensify/App/issues/46373#issuecomment-2254463503). 

I believe we should proceed with @gijoe0295's [proposal](https://github.com/Expensify/App/issues/46373#issuecomment-2254382257) to add `readonly` param in the route.If the user manually removes the `readonly` param from the URL, I think it's acceptable to allow them to edit the receipt, as they will no longer be in the `Review duplicates` flow.

🎀 👀 🎀 C+ reviewed

**Comment by stitesExpensify** [comment]
@sobitneupane why are you not in favor of the route check idea? It seems a lot simpler than @gijoe0295 proposal. Do you see it not being reliable in the future or something?

**Comment by sobitneupane** [comment]
@stitesExpensify It is more of a workaround, and I'm concerned that it may not cover all possible cases. For example, if a user reloads the page from the duplicate confirmation page (/r/__ID__/duplicates/confirm) and then clicks on the receipt, they might still be able to edit it.

**Comment by stitesExpensify** [comment]
Thank you both for taking a second look! Moving forward with @gijoe0295

**Comment by dylanexpensify** [comment]
@gijoe0295 mind giving us a rough idea of when you'll have the PR raised for review?

**Comment by sobitneupane** [comment]
**Regression Test Proposal:**

1. Submit 2 duplicated expenses with receipts
2. Go to the thread transaction report
3. Press Review duplicates
4. Proceed to confirmation page
5. Press receipt preview
6. Press 3-dot menu
7. Verify Replace and Delete receipt options are not shown

Do we agree 👍 or 👎

**Comment by stitesExpensify** [comment]
@anmurali  all you on this one!

**Comment by anmurali** [comment]
## Payment Summary

- [ ] @sobitneupane $250 approved, request via New Dot
- [X] @gijoe0295 $250 approved, paid via Upwork

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
