### ISSUE TITLE
[$250] Tasks - Pressing enter key after a mark down doesn't show the new line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46389]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:**  Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+3444@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click on the Green plus Icon
3. Click on Assign task
4. Insert a sample title
5. Click on Description
6. Insert multiple-line text until a scroll bar is shown on the right
7. On a new line insert a markdown text (eg. *bold*)
8. Hit the enter key on the keyboard
9. For comparison on a new line insert a normal text (e.g text)
10. Hit the enter key on the keyboard

## Expected Result:
When hitting the enter key after a mark down the new line becomes visible with the cursor seen visibly

## Actual Result:
When hitting the enter key after a mark down the cursor gets hidden on the new line which is a different behavior when compared with the behavior seen on a normal text and hitting enter key

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/754d4325-3565-46f8-aecb-7f6320dbac13

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019aa27e395e6f5aae</li>
        <li>Upwork Job ID: 1819367536186479442</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103558387</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #Live Markdown

**Comment by johncschuster** [comment]
This will either fit under #live-markdown or #tasks. I _think_ it's live markdown related.

**Comment by BartoszGrajdek** [comment]
Hi, I'm Bartosz from SWM `react-native-live-markdown` team! This issue is in fact live markdown related, thanks for adding it to the project 🙌🏻 

I'm going to be OOO till 11.08, so I'm tagging @tomekzaw here for visibility.

**Comment by johncschuster** [comment]
Not overdue. We're waiting on @BartoszGrajdek to come back from OOO.

**Comment by johncschuster** [comment]
bump for melv

**Comment by johncschuster** [comment]
Bumping to keep Melvin happy

**Comment by johncschuster** [comment]
Bumping this one. Were you able to pick this back up, @BartoszGrajdek?

**Comment by BartoszGrajdek** [comment]
> Bumping this one. Were you able to pick this back up, @BartoszGrajdek?

Thanks for the bump! We had quite a few high-priority issues this week. 😅 @dominictb's proposal makes sense to me, so if you agree, we can assign him to this issue. He can then raise a PR to react-native-live-markdown, and we can test it there. 🙌🏻

Unfortunately, our team at SWM will be OOO on Thursday and Friday due to a public holiday (sorry about that again 🙏🏻).

In the meantime, you or any C+ member can review the PR in our repo. Just please hold off on merging it, as we’d like to test it against some of our known regressions once we're back to ensure we don't break anything. 👀

**Comment by johncschuster** [comment]
Sounds great, @BartoszGrajdek! Thanks for that update!

@dominictb, I've assigned the issue to you. Please review @BartoszGrajdek's [comment above](https://github.com/Expensify/App/issues/46389#issuecomment-2289699231)

**Comment by Pujan92** [comment]
@johncschuster I haven't reviewed the proposal or markdown PR for this issue so no payment for me. All done by @BartoszGrajdek. Thanks to them!

**Comment by johncschuster** [comment]
Got it. Thanks, @Pujan92! @BartoszGrajdek / @dominictb do you feel we need some regression steps for this one?

**Comment by johncschuster** [comment]
Bumped in Slack for regression test steps

**Comment by johncschuster** [comment]
Thank you!
