### ISSUE TITLE
[$250] Tags - Payroll code option is missing on Tag details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46384]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4777303&group_by=cases:section_id&group_order=asc&group_id=229065
**Email or phone of affected tester (no customers):** gocemate+a767@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Workspace settings > More Features
2. Enable Tags if disabled
3. Navigate to Tags> Create a tag
4. Click on a Tag
5. Note the options on Tag details page
Verify the options GL code and Payroll code are displayed
Click on the GL code
Verify the upgrade plan modal is displayed and user is unable to set GL codes on a Collect Policy

## Expected Result:
The options GL code and Payroll code should be displayed

## Actual Result:
Payroll code option is missing on Tag details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/524b6311-beed-4c8b-b7ed-01d69a18724b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c9e95881e12f098</li>
        <li>Upwork Job ID: 1817955238622068363</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment]
I think it's not a bug, the context here https://github.com/Expensify/App/issues/43028. @rushatgabhane Can you please confirm if the payroll option shouldn't show on the tag detail page?

**Comment by rushatgabhane** [comment]
yep you're right it should be on category only

**Comment by eh2077** [comment]
> I think it's not a bug, the context here #43028. @rushatgabhane Can you please confirm if the payroll option shouldn't show on the tag detail page?

@lschurr This seems not a bug as discussed about. What do you think?

**Comment by JmillsExpensify** [comment]
Agree that this isn't a bug. It's by design.
