### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Wallet - inactive add bank account button when enabling wallet for first time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** negasofonias+7247@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login to staging new dot with a new account
2. Open expensify task chat with setup steps and start executing task 3
3. Go to account and click on wallet
4. Click on enable wallet and observe a new window pops on the right with a create account button
5. Observe the button is not clickable

## Expected Result:
Button should be clickable to comply with the stated user flow in the enabling wallet task flow
i.e 1. Click your profile picture
2. Click Wallet > Enable wallet
3. Add your bank account

## Actual Result:
Button is not clickable but becomes clickable after user first uses the add account path below enable wallet in wallet page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/881406a4-df22-4f88-b2fe-b43b4a7ac5e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faf46b6481828f8a</li>
        <li>Upwork Job ID: 1817982656802675106</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The add bank button on the expensify wallet page is disabled initially but enabled once we press the Add bank account from the Bank accounts section.

### What is the root cause of that problem?
The add bank account on the expensify wallet page is disabled if `isPlaidDisabled` is true.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/pages/EnablePayments/AddBankAccount/SetupMethod.tsx#L56

But `isPlaidDisabled` is initially undefined, so it will use the `!user.validated` condition. When we open the plaid link from the Bank accounts section, BE returns the `isPlaidDisabled` and if it's false, the button is enabled even when the user is still not validated yet.

### What changes do you think we should make in order to solve the problem?

We need to use `||` instead of `??` just like we did in workspace BankAccountStep.
https://github.com/Expensify/App/blob/98d8a5ae4bb52539669f79e007246417eb8c8f1e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L151

**Comment by joekaufmanexpensify** [comment]
Will triage today

**Comment by joekaufmanexpensify** [comment]
I can reproduce. VIP Split is paused, but I almost wonder if allowing someone with an unvalidated account to access the wallet is a security issue. Discussing [here.](https://expensify.slack.com/archives/C07E0943G7P/p1722269030133639)

**Comment by joekaufmanexpensify** [comment]
We decided we want to fix this. But the way we want to fix it is we don't want to allow someone to add a bank account or enable their wallet before they've validated. Is that what you're proposal would do @bernhardoj ?

**Comment by bernhardoj** [comment]
@joekaufmanexpensify Yes, the button in Add bank account page will be disabled if the account is not validated.

<img width="1164" alt="Screenshot 2024-07-30 at 13 16 28" src="https://github.com/user-attachments/assets/54acad9c-4802-4b5b-9d77-72bed1b5cc27">

However, the Add bank account button in "Bank accounts" section currently doesn't have any logic to disable/hide when the account is not validated. What should we do with that button, disable or hide or other?

**Comment by joekaufmanexpensify** [comment]
@bernhardoj we should prevent both cases. Handling them consistently by disabling should be fine

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by joekaufmanexpensify** [comment]
@mananjadhav Also, there was some discussion internally that we'll need to implement this check in the backend too, in addition to the frontend validation. Please confirm if there's a backend component to this too while reviewing proposals, and I can find an internal volunteer, if so.

**Comment by mananjadhav** [comment]
I'll check this and update.

**Comment by joekaufmanexpensify** [comment]
TY! We confirmed internally that there is a backend component here, so I will look for an internal volunteer

**Comment by joekaufmanexpensify** [comment]
Need to post about this internally to find an internal volunteer

**Comment by mananjadhav** [comment]
Would still ask the internal engineer to review it once. `user?.validated` check is definitely required. But I don't think we should be removing `isPlaidDisabled`.

I think `||` is better, hence @bernhardoj's [proposal](https://github.com/Expensify/App/issues/46386#issuecomment-2254866226) looks good to me.



🎀 👀 🎀 C+ Reviewed.

**Comment by jasperhuangg** [comment]
Yeah I completely agree we should not be removing any parts of that condition. @bernhardoj's proposal is clear and makes sense to me. Let's move forward.

**Comment by bernhardoj** [comment]
PR is ready

cc: @mananjadhav

**Comment by joekaufmanexpensify** [comment]
@jasperhuangg when I had chatted with @rafecolton about this issue [here](https://expensify.slack.com/archives/C07E0943G7P/p1722352308222689?thread_ts=1722269030.133639&cid=C07E0943G7P) in Slack, he had mentioned that we also needed to validate this check on the backend, in addition to the frontend piece we're moving forward with now. Is that something you'd be able to handle?

**Comment by mananjadhav** [comment]
I'll review later today.

**Comment by joekaufmanexpensify** [comment]
Bumped to Jasper 1:1

**Comment by jasperhuangg** [comment]
@joekaufmanexpensify yes absolutely, I'll look into that this week.

**Comment by joekaufmanexpensify** [comment]
Sweet. TY!

**Comment by joekaufmanexpensify** [comment]
Actually pushing back to weekly. We're going to do the backend fix in an internal repo!

**Comment by joekaufmanexpensify** [comment]
@mananjadhav could you tackle BZ here so we can prep for payment?

**Comment by joekaufmanexpensify** [comment]
Bumped in Slack

**Comment by joekaufmanexpensify** [comment]
Payment here is pending completion of the BZ checklist

**Comment by mananjadhav** [comment]
Considering this is a very specific workflow based bug, I couldn't figure out at which point in time we should've added this check. Hence I don't think we have an offending PR here. 

As for regression it is easy to miss out this one and something that should be considered as a part of not validated users. Therefore, I feel we should add a regression test.

**Regression Test Proposal**

 1. Sign in as a new user
 2. Go to Settings  Wallet
 3. Verify Add bank account button is disabled
 4. Press Enable Wallet
 5. Verify Add bank account button is disabled
 6. Validate your account
 7. Verify the Add bank account button in step 3 and 5 is enabled

**Comment by mananjadhav** [comment]
@joekaufmanexpensify Can you post the payment summary here?

**Comment by joekaufmanexpensify** [comment]
Confirmed above payment summary is correct!

**Comment by joekaufmanexpensify** [comment]
Checklist is now complete. All set to issue payment!

**Comment by joekaufmanexpensify** [comment]
Closing as all that's left here is for @mananjadhav and @bernhardoj to request payment via NewDot. TY both!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @mananjadhav

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
