### ISSUE TITLE
[PAYMENT 2024-09-06] [$250] Chat - When opening a PDF and clicking 'Ctrl + K,' the search opens but the page scrolls to the next

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46388]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat and click the plus sign
2. Select "Attachment" and send the Pdf attachment
3. Open the attachment and click 'Ctrl + K
4, click on 'esc' to close

## Expected Result:
When we open the PDF and click 'Ctrl + K,' the search should open, and the page should not scroll to the next page

## Actual Result:
When we open the PDF and click 'Ctrl + K,' the search opens, but the page scrolls to the next page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/93819efe-d977-448e-955a-7182c256610c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b20e5826b61d01de</li>
        <li>Upwork Job ID: 1820952988321413899</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103557309</li>
<li>dominictb | Contributor | 103557313</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment]
Testing now.

**Comment by strepanier03** [comment]
Updated title since it looks like automation might have failed on this one.

**Comment by strepanier03** [comment]
### Payment Summary

- [x] $250 - @allgandalf via Upwork 
- [x] $250 - @dominictb via Upwork

_Both contracts paid and closed._

**Comment by strepanier03** [comment]
Dang, thought today was the 6th lol, I'm all turned around.

**Comment by DylanDylann** [comment]
@dominictb @allgandalf We have [the same issue](https://github.com/Expensify/App/issues/48113) with this one. And a contributor [complains](https://github.com/Expensify/App/issues/48113#issuecomment-2328734043) about @dominictb's solution. I see this is the 100% same issue so please help to check the similar bug that is mentioned [here](https://github.com/Expensify/App/issues/48113#issuecomment-2328734043)

cc @thienlnam
