### ISSUE TITLE
[$250] Inconsistent Currency Code Representation for 'MRO' in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46392]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Account Settings > Workspace
2. Change the default currency to 'MRO' in Profile
3. In the LHN, go to Workspace Chat > Plus Sign > Expense Request
4. Add a merchant and confirm it
5. Go to IOU and observe the LHN

## Expected Result:
The currency code should be consistently represented as 'MRO' throughout the app

## Actual Result:
The currency code is inconsistently represented as 'UM' instead of 'MRO' when submitting an expense and viewing the IOU in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/52b0ef9f-605d-41f3-82a7-de78213a9477

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019389c6893f847c12</li>
        <li>Upwork Job ID: 1817710932397878288</li>
        <li>Last Price Increase: 2024-08-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
Thank you @mollfpr

**Comment by mollfpr** [comment]
This issue is on the BE where it returns the `lastMessageHtml` or `lastMessageText` with **UM** currency. As mentioned in the proposal the currency **MRU** is also set as **UM** in the LHN's last message but the exchange is different between **MRO** and **MRU**.

@jliexpensify We might need an internal engineer to check why the report sends a different currency for the `lastMessageHtml` and `lastMessageText` values.

**Comment by mollfpr** [comment]
Okay, I understand now. It's correct that **MRO** is obsolete.

![Screenshot 2024-08-05 at 19 40 53](https://github.com/user-attachments/assets/3f013c07-2496-4893-8b75-9f9644794870)

>The currency code is inconsistently represented as 'UM' instead of 'MRO' when submitting an expense and viewing the IOU in LHN

@daledah @jliexpensify I think the actual result is expected where **UM** is a symbol representing currency **MRO**.

**Comment by jliexpensify** [comment]
Thanks for the investigation @mollfpr - if `MRO` is now obsolete, could we just change it to `MRU` or even `UM` in-product? I think if we can get rid of the inconsistency, that would be good.

if it's not something that can be fixed, then we can close this one.

**Comment by mollfpr** [comment]
>if MRO is now obsolete, could we just change it to MRU or even UM in-product? I think if we can get rid of the inconsistency, that would be good.

@jliexpensify We can filter out the obsolete currencies mentioned in the @daledah proposal.

**Comment by jliexpensify** [comment]
Ok, I think we could probably fix this then? @mollfpr want to push it forward and we'll get an Internal Engineer to make the final decision?

**Comment by mollfpr** [comment]
The actual issue here is expected that **UM** is the symbol for **MRO** currency, but it's mentioned in the @daledah [proposal](https://github.com/Expensify/App/issues/46392#issuecomment-2254829851) we have obsolete currency (including **MRO** which replace by **MRU**) I think it's a better chance to filter them out from the list.

🎀 👀 🎀 C+ reviewed!

**Comment by jliexpensify** [comment]
Bumping @youssef-lr to review proposal, thanks!

**Comment by jliexpensify** [comment]
Bumping @youssef-lr to review the proposal, cheers!

**Comment by jliexpensify** [comment]
DM-ed Youssef for a review.

**Comment by jliexpensify** [comment]
Checked PR, this is deployed to staging but not to prod.

**Comment by mollfpr** [comment]
@jliexpensify The PR is deployed to production 3 weeks ago. I think Melvin failed to send the notification. https://github.com/Expensify/App/issues/48035

![Screenshot 2024-09-18 at 15 22 50](https://github.com/user-attachments/assets/112277c9-66e4-4698-b914-abae4773506b)

**Comment by mollfpr** [comment]
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Select FAB > Submit expense
2 .Open Select currency list
3. Verify that: Retired currencies (such as MRO) is not shown anymore
4. 👍 or 👎

**Comment by jliexpensify** [comment]
Dang ok - thanks @mollfpr!

**Comment by jliexpensify** [comment]
Payment Summary

- C: @daledah $250 - **can you please add your Upworks name to your GH profile so I can hire you?**
- C+: @mollfpr $250 (ND Payment)

**Comment by jliexpensify** [comment]
Thanks @daledah - offer sent

**Comment by garrettmknight** [comment]
$250 approved for @mollfpr

**Comment by jliexpensify** [comment]
Paid and job closed!
