### ISSUE TITLE
[$250] Room - The url for the invite new members page ends with "undefined"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** ruhamashimelis@gmail.com
**Issue reported by:** Applause - Internal Team

Action Performed:
1. Go to staging.new.expensify.com
2. Click on profile
3. Click on workspaces
4. Click on New workspace
5. Go back to inbox
6. Click on green plus icon
7. Click on start chat
8. Click on room tan
9. Give it a random name and create the room
10. Click on the header of the room
11. Click on members
12. Click on invite
13. Copy the current URL of the page
14. Paste the URL elsewhere

## Expected Result:
The URL of the invite new members page of a room does not contain "undefined"

## Actual Result:
The URL of the invite new members page of a room does not contain "undefined"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a00955aa-d214-4b10-85ef-72c1d3bd9e8c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014808c102f26432ba</li>
        <li>Upwork Job ID: 1821118867956175441</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by allroundexperts** [comment]
@nyomanjyotisa's [proposal](https://github.com/Expensify/App/issues/46390#issuecomment-2254692446) looks good to me. It has the correct RCA and the solution is straight forward. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by tgolen** [comment]
@miljakljajic Could you please assist with that?

**Comment by miljakljajic** [comment]
@nyomanjyotisa I sent you an offer - please accept it as soon as you can!

@allroundexperts is paid via newdot request

**Comment by tgolen** [comment]
bump @nyomanjyotisa Were you able to accept the offer?

**Comment by miljakljajic** [comment]
Payment summary for @allroundexperts 

@allroundexperts is owed 250 USD for their work reviewing this PR.

@nyomanjyotisa paid.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
