### ISSUE TITLE
Tasks - Checkbox Displays Duplicate Actions When Rapidly Checked and Unchecked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+b84@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to [staging.new.expensify.com]
2. Click on the FAB (Floating Action Button)
3. Select "Assign Task."
4. Write the title, then click "Next.
5. Share the task to somewhere and confirm it
6. Check and uncheck the task rapidly

## Expected Result:
The checkbox should accurately reflect each individual check and uncheck action, matching the number of times it is checked and unchecked

## Actual Result:
When the checkbox is checked and unchecked rapidly, it displays as if each action is performed twice

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5d7f79fc-e8dd-4a12-aa02-d08c7c88a1b6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by alexpensify** [comment]
I'll test it soon; this GH is on my testing list.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience. I tried two different tasks and they didn't duplicate. 

![2024-08-05_16-15-54](https://github.com/user-attachments/assets/0b1e18fc-f2bb-4ea1-9fbe-3b7c83aaf8d9)

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!
