### ISSUE TITLE
Web - Editing Mentioned Emails Displays Only Edited Words in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46415]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to self DM
2. Write two mentioned emails side by side
3. Send the message
4. Edit the second mentioned email by replacing it with words

## Expected Result:
The mentioned email, now edited to words, should be displayed in the LHN as it appears in the composer

## Actual Result:
When writing two mentioned emails side by side and editing the second mentioned email to words, only the words are displayed in the LHN. This creates an inconsistency between the edited message and the directly sent message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/158f1c6a-1a4c-4c02-9266-b62729b307a6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
BE issue

**Comment by RachCHopkins** [comment]
Not understanding why someone would @tag anyone in a DM with themselves. 

Does this happen without @ tagging?

**Comment by RachCHopkins** [comment]
Checking in the [bug channel](https://expensify.slack.com/archives/C049HHMV9SM/p1722903605847379).

**Comment by RachCHopkins** [comment]
I don't think this is an issue we need to focus on fixing right now. It's a super edge case.

**Comment by mallenexpensify** [comment]
@RachCHopkins it happens with non-DM chats too, which makes me think we might want to fix. 
<img width="666" alt="image" src="https://github.com/user-attachments/assets/1565970f-9734-4ae8-b769-8a860c5faeba">

@FitseTLT , what makes you think this should be BE? (honest question cuz I have no idea)

**Comment by FitseTLT** [comment]
`lastMessage` of the report is not updated correctly in the backend after editing the last message. It should be fixed in BE.

**Comment by mallenexpensify** [comment]
Thanks @FitseTLT

**Comment by mallenexpensify** [comment]
@RachCHopkins I made it `Internal`, `Weekly` and added it to #vip-vsb, since the bug doesn't affect expensese

**Comment by RachCHopkins** [comment]
vip-vsb is on hold

**Comment by RachCHopkins** [comment]
Waiting for someone to pick this up

**Comment by RachCHopkins** [comment]
Posted in [slack](https://expensify.slack.com/archives/C066HJM2CAZ/p1726205882331289?thread_ts=1726152950.736669&cid=C066HJM2CAZ) to check what to do with this project on hold.

**Comment by RachCHopkins** [comment]
Closing for now - can can reopen when VIP-VSB comes off hold.
