### ISSUE TITLE
Private Notes - Private Note Automatically Saves Without Clicking the Save Button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46417]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/S
**Email or phone of affected tester (no customers):** biruknew45+12345@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to [staging.new.expensify.com]
2. Navigate to any chat
3. Click on the header
4. Click on the "Private Notes" section
5. Write something in a private note
6. Navigate back to the chat without clicking the Save button
7. Return to the "Private Notes" section

## Expected Result:
When writing something in the private note section of the chat and navigating away without saving, the changes should not be automatically saved

## Actual Result:
The changes in the private note section in the chat are automatically saved when navigating away without explicitly saving

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/17b4c615-0cd7-449f-8e25-4e8c6665f7a3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
Going to close this issue because I don't think it's a priority to fix right now.
