### ISSUE TITLE
[CRITICAL] Update our processes for testing on staging / prod

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#46429]
# Problem

We've had a ton of "bugs" that have been caused by testers using a combination of prod/staging unknowingly. This can create confusing errors in spotnana, since they have separate databases for prod/staging. We can ask everyone to use production, but that will cot us real $$$, minimally for the booking fee, but also if someone forgets to cancel a trip and get a refund in time. 

# Solution

Outline a process for testing on staging that all testers across sales/QA/etc can use to avoid this confusion going forward.

**Comment by stitesExpensify** [comment]
Created a SO here to set up testing accounts: https://stackoverflowteams.com/c/expensify/questions/19798/19799#19799

**Comment by stitesExpensify** [comment]
After the next deploy we can send out an email about how this works to make sure that everyone is on the same page

**Comment by stitesExpensify** [comment]
I made a post [here](https://expensify.slack.com/archives/C05S5EV2JTX/p1722370848242069) in slack with the new testing steps

**Comment by stitesExpensify** [comment]
Do you think we need anything else here @kevinksullivan ?

**Comment by kevinksullivan** [comment]
Nope!
