### ISSUE TITLE
 Submit expense - Navigating to confirmation page via a URL behaves inconsistently

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46420]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com on both account 1 and account 2 (Both must be new accounts)
2. On account 1 click on green plus icon
3. Click on submit expense
4. Enter an amount and click next
5. Insert an email address
6. While on the confirmation page copy the URL of the page and go out without submitting
7. On account 2 open your space chat
8. Paste the copied URL
9. Click on the URL
10. Observe "it's not here" page is displayed
11. Click on green plus icon
12. Click on submit expense
13. Enter an amount and click next
14. Insert an email address
15. Go back without submitting the expense
16. Navigate to your space chat and click on the URL again

## Expected Result:
"it's not here" page appears when clicking on the URL

## Actual Result:
When clicking on the URL first before going through a submit expense flow "it's not here" page gets displayed but after going through a submit an expense flow clicking on the URL takes user to a confirmation page with the data inserted previously

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bb3f0830-75c3-4240-b339-72f8b657ed15

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
I can reproduce this.

**Comment by zanyrenney** [comment]
I don't believe this is a critical "real-world" issue which should be prioritised in line with the roadmap currently. Closing this out!
