### ISSUE TITLE
Workspace - "Not here" page appearance and disappearance in the right corner

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46427]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisite: A workspace is already created
1. Go to [staging.new.expensify.com]
2. Navigate to account settings
3. Select workspaces
4. Click on one workspace and select its name
5. Copy the URL
6. Paste the URL into an editor and modify the URL change the workspace ID which is located between "/workspaces/" and "/profile/" replace the ID with something random
7. Copy the edited URL
8. Paste the edited URL into the browser's search bar and press enter

## Expected Result:
A not here page does not appear and then disappear

## Actual Result:
A not here page appears and disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/69211520-cba9-422c-a157-b946ae019fe0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
This seems like a real edge flow, and the result is expected. Closing this out.
