### ISSUE TITLE
[PAID] [$250] Settings - App navigates to inbox when reloading on switch to expensify classic page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46435]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to [staging.new.expensify.com]
2. Navigate to account settings
3. Select "Switch to Expensify Classic"
4. Reload the page

## Expected Result:
After reloading the page, the background of the app should stay on account settings page and not navigate to the inbox by default

## Actual Result:
After refreshing the page, the background of the app navigates to the inbox by default

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8827748a-1685-45b5-aedf-197b045b3306

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad068d665da19dfc</li>
        <li>Upwork Job ID: 1820953322036269649</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 103450807</li>
<li>ishpaul777 | Contributor | 103450808</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by strepanier03** [comment]
Was able to repro this easily following the steps. I agree we shouldn't switch to the Inbox on a reload.

**Comment by arosiclair** [comment]
@strepanier03 ^

**Comment by strepanier03** [comment]
### Payment summary

- $250 - @mkhutornyi via Upwork ([offer](https://www.upwork.com/offer/103804746))
- $250 - @ishpaul777 via Upwork ([offer](https://www.upwork.com/offer/103804751))

**Comment by strepanier03** [comment]
I'll check in tomorrow and pay what I can.

**Comment by strepanier03** [comment]
Odd, I couldn't find an offer already so I made a new one. I'll try to hunt down the original one and then clean this up.

**Comment by strepanier03** [comment]
The offer links above didn't work yesterday but they are working today 🤷‍♀️ thanks Upwork 😂

**Comment by strepanier03** [comment]
I was able to load the original offers, pay them, and close the contracts. Then I withdrew the second offers I sent over yesterday and closed that job out. 

This should be cleaned up and all done. Thanks everyone!
