### ISSUE TITLE
[$250]  Spanish Preferences - "Classes", "Customers", "Customers/Projects" are importing in English

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46439]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

Prerequisite - create a NewDot workspace connected to an integration (QBO/Xero)

## Action Performed:
1. Open Expensify App
2. Click Account Settings > Preferences > Language > Spanish 
4. Select "Espacios de trabajo"
5. Select the workspace with the integration connected 
8. Click "Etiquetas"
9. Notice "Classes", "Customers/Projects", "Customers" are not translated

## Expected Result:
The "Classes", "Customers/Projects", "Customers" are in Spanish

## Actual Result:
The categories are in English

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![2024-08-02_13-43-47 (4)](https://github.com/user-attachments/assets/6b12c1b0-c675-4f32-a829-7031cf404d6c)

Images:

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/9c014c78-3627-401d-98f4-281e2ecee549">

<img width="1689" alt="image" src="https://github.com/user-attachments/assets/a5487c06-4215-4247-bfdc-b7f88fabd7b6">

<img width="1694" alt="image" src="https://github.com/user-attachments/assets/3632eb13-8678-4405-b2c4-d55c6ed15644">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010610d8155f99370c</li>
        <li>Upwork Job ID: 1818732243541921106</li>
        <li>Last Price Increase: 2024-07-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment]
I'm ooo today so I'll work on this tomorrow

**Comment by Christinadobrzyn** [comment]
This is a bigger issue - as the Categories, Class, Customers/Projects in the workspace aren't translated - which I think is the root of what we see on the Expense page. 

<img width="1171" alt="image" src="https://github.com/user-attachments/assets/e676521c-125a-4cbc-ac5c-0805050b822d">
<img width="1695" alt="image" src="https://github.com/user-attachments/assets/ac99bb1e-14e2-4357-bd1f-63f57c6af5f9">
<img width="1689" alt="image" src="https://github.com/user-attachments/assets/70be58be-a629-49f6-9b83-24f878d98aef">
<img width="393" alt="image" src="https://github.com/user-attachments/assets/f3044b8b-aa1b-4347-9b76-feaffca246f8">
<img width="356" alt="image" src="https://github.com/user-attachments/assets/4c274c22-9207-4a6c-8ed9-5bc60080a99d">

So I think we need to make sure everything in the workspace is translated and that it's reflecting properly on the expense report level. 

I assume this can be External @c3024 let me know if you think we can just update the OP for this bigger issue? I assume that's okay.

**Comment by Christinadobrzyn** [comment]
Asking the team what should be translated so we can move forward with reviewing the proposals - https://expensify.slack.com/archives/C036QM0SLJK/p1722615969173589

**Comment by JmillsExpensify** [comment]
We should not translate data that comes from another system. Whatever language it is in in that system, we should keep it the same.

**Comment by Christinadobrzyn** [comment]
Thank you @JmillsExpensify! 

The OP is now incorrect - but I can update it to translate the parts of the app that should be in Spanish. 

We should be using this [ChatGPT](https://chatgpt.com/g/g-tAon5M5jH-english-to-spanish-translator) for translation.

**Comment by JmillsExpensify** [comment]
Ok just to confirm, what solution are you recommending is the correct one?

**Comment by Christinadobrzyn** [comment]
Sorry @JmillsExpensify I updated the OP with the problem and solution. 

Can you you double-check that "Classes", "Customers/Projects", and "Customers" (if they exist) need to be translated?

**Comment by Christinadobrzyn** [comment]
Sorry @JmillsExpensify - I updated the OP with the problem and solution. 

Can you double-check that "Classes", "Customers/Projects", and "Customers" (if they exist) need to be translated?

**Comment by Christinadobrzyn** [comment]
Based on the Slack convo - this is working as expected - those values are coming from the accounting integration so that's why they are showing in English. Closing without action.
