### ISSUE TITLE
[$250] iOS - Composer - Emoji is cut off when entering one letter after the emoji

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46444]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Open any chat
3. Enter an emoji
4. Type one letter after the emoji

## Expected Result:
The emoji will not be cut off when entering one letter after the emoji

## Actual Result:
The emoji is cut off when entering one letter after the emoji
When entering the second letter, it appears normal again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/66ba15c3-305d-4420-b55a-8410caf22be6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb22e4ceda4fdcb9</li>
        <li>Upwork Job ID: 1818025070545665675</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by francoisl** [comment]
Could be from https://github.com/Expensify/App/pull/40692. Looks like there's another blocker (#46443)  related to that PR already.

**Comment by chiragsalian** [comment]
Issue not related to web-e repo so removing deployblocker label.

**Comment by hungvu193** [comment]
Seems it's being handled in https://github.com/Expensify/App/issues/46443

**Comment by VickyStash** [comment]
@parasharrajat 
The reason of the described problem is that the `markdownStyles` update with the new `fontSize` for the emojis isn't applied right away on ios.

I'm able to reproduce the same behavior in the [react-native-live-markdown](https://github.com/Expensify/react-native-live-markdown) lib. It looks like the `markdownStyles` update on iOS applies to the input only after the value update (something new got entered). So `markdownStyles` update doesn't re-render the input.

See the video:


https://github.com/user-attachments/assets/c6f96591-d812-4194-9623-96f04ef3ab6d

**Comment by francoisl** [comment]
For future reference, here was the revert PR https://github.com/Expensify/App/pull/46463
