### ISSUE TITLE
[$250] Emoji - highlighting Emoji is not retangular

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Access New Expensify app
2. Sign into a valid account
3. Sent any emoji in the composer and Highlight it with the cursor

## Expected Result:
User expects a constant rectangular/square blue highlight

## Actual Result:
The Highlight is "Broken", showing as "blocks"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6556729_1722288802603!On_Stg](https://github.com/user-attachments/assets/ccf7e1f0-d0f3-40e4-8b4c-4b8c4ab17085)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e9d5775000772ed</li>
        <li>Upwork Job ID: 1818761460846123962</li>
        <li>Last Price Increase: 2024-08-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by VickyStash** [comment]
This issue was known before the merging of the related [PR](https://github.com/Expensify/App/pull/40692), please see the discussion: https://github.com/Expensify/App/pull/40692#issuecomment-2179021647

**Comment by roryabraham** [comment]
This is NAB, demoting it

**Comment by eVoloshchak** [comment]
Not overdue, awaiting proposals

**Comment by VickyStash** [comment]
This issue isn't relevant, since the PR that caused this issue was [reverted](https://github.com/Expensify/App/pull/46463)

**Comment by deetergp** [comment]
I just verified that this is no longer happening on `main`. Closing this.
