### ISSUE TITLE
Composer - Emojis overlap with each other

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46451]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Enter an emoji
4. Create a new line
5. Enter another emoji

## Expected Result:
Emojis will not overlap with each other

## Actual Result:
Emojis overlap with each other

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0e37c382-7dbc-44b7-986e-325afcfd6212

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
Doesn't look web-e related. removing deployblocker label.

**Comment by stitesExpensify** [comment]
Most likely caused by https://github.com/Expensify/App/issues/46443 and we may be reverting

**Comment by roryabraham** [comment]
that PR was reverted, let's retest this...

**Comment by roryabraham** [comment]
confirmed this is fixed
