### ISSUE TITLE
Workspace - Back button returns to the same workspace page after upgrading to Control

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46450]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/45730
**Version Number:** 9.0.14-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to More features.
4. Toggle on Report fields.
5. Click Upgrade.
6. Click Got it, thanks.
7. Click on the app back button.

## Expected Result:
App will return to workspace list page (previous page).

## Actual Result:
App returns to the same workspace editor page, which is from More features back to More features page again.

On prod, the back button works correctly as it returns from Profile to More features page.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4b8cb538-4ae6-4988-9a2f-e3519f3f1d3b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment]
Doesn't look web-e related. removing deployblocker label.

**Comment by aldo-expensify** [comment]
I see that in production it takes you automatically to the workspace's `Profile` page after the upgrade:


https://github.com/user-attachments/assets/f3ee146a-27f4-4f82-8e4d-260c29203f0c

This doesn't happen in the recording from this issue

**Comment by aldo-expensify** [comment]
I think this is happening because of this PR: https://github.com/Expensify/App/pull/45730/files

**Comment by aldo-expensify** [comment]
cc @allroundexperts @rushatgabhane

**Comment by aldo-expensify** [comment]
I think this works well if you scrolled down to find `Report fields` inside `More features`, because then the `Back` button will scroll you down to where you were when you clicked `Report fields` and a second click will take you out to the `Profile`:


https://github.com/user-attachments/assets/d3f43655-dada-41ff-b785-a883575d0c9c

but, if you didn't scroll down to find the `Report fields`, then the first press on the `back` button will not move the scrollbar making it look like it did nothing:


https://github.com/user-attachments/assets/cd503293-328a-4a05-90ff-886d6c16f77d

**Comment by aldo-expensify** [comment]
I think the easiest fix is that we should do any navigation when we `upgrade` in this flow. We are currently scrolling up, but what for?

<img width="995" alt="image" src="https://github.com/user-attachments/assets/b39f5053-03a4-4b36-a623-14030c7e246b">

**Comment by aldo-expensify** [comment]
Creating a revert here since I'm not sure what is the right way to fix this and the transition also doesn't look good: https://github.com/Expensify/App/pull/46460

**Comment by allroundexperts** [comment]
Hm... Is a revert really needed here? Asking because this PR fixes issues which might be of greater importance than this bug.

**Comment by aldo-expensify** [comment]
> Hm... Is a revert really needed here? Asking because this PR fixes issues which might be of greater importance than this bug.

Do you have some examples? I'm just suggesting a revert because I didn't see it fixing something of importance, I don't have a clear solution for this deploy blocker, and the animation here looks broken https://github.com/Expensify/App/pull/46460

**Comment by aldo-expensify** [comment]
Reverted and tested: https://github.com/Expensify/App/pull/46460
