### ISSUE TITLE
[HOLD for payment 2024-08-09] Room - System message shows code when adding emoji and mark down to room description

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46486]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a room.
3. Click on the room header.
4. Click Room description.
5. Enter an emoji, text with mark down and save it.
6. Go back to room chat.

## Expected Result:
Room description system message will not show code when adding emoji and text with mark down to room description.

## Actual Result:
Room description system message shows code when adding emoji and text with mark down to room description.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/db4dd857-1c90-4908-a5da-fdb26c39d992

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by Julesssss** [comment]
I don't see any changes to the API or Auth command in the last 3 months, so I'm leaning towards App. I see some potential PRs that may have caused the regression: 

- https://github.com/Expensify/App/pull/46321
- https://github.com/Expensify/App/pull/40692
- https://github.com/Expensify/App/pull/43084

**Comment by Julesssss** [comment]
Not a blocker, updating room names is not worth holding the release

**Comment by Julesssss** [comment]
Thanks @gijoe0295. We haven't got to the proposal stage yet, but we can compensate if this solution is used. I am [asking](https://github.com/Expensify/App/issues/46486) the author to fix with a follow-up PR.

**Comment by nkdengineer** [comment]
@Julesssss I will raise a PR soon.

**Comment by nkdengineer** [comment]
@hungvu193 @Julesssss we have a follow PR [here](https://github.com/Expensify/App/pull/46512)

**Comment by Julesssss** [comment]
PR merged

**Comment by slafortune** [comment]
Fixed internally - closing
