### ISSUE TITLE
Chat - Different placement of sender name and message on staging vs production

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46489]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Send a message.
4. Compare the placement of sender name and message on staging and production.

## Expected Result:
The placement of sender name and message on staging will be the same as that on production.

## Actual Result:
The placement of sender name and message on staging is different from production.
On staging, there is some spacing between sender name and message.
The sender name is also a bit lower compared to production.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8141f10f-e8d6-4af6-ac9c-d504000b139a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<img width="1440" alt="Bug6556720_1722287892887!Screenshot_2024-07-30_at_05 17 50" src="https://github.com/user-attachments/assets/ca4af427-9eb7-4688-8ebd-959912df465f">

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by izarutskaya** [comment]
Production 
![image (6)](https://github.com/user-attachments/assets/216fa892-b61d-458f-b0c7-a76fc7905c45)

**Comment by VickyStash** [comment]
> I don't think this counts as a regression. It is intentional change. @VickyStash

Yeah, otherwise, there were problems with the date alignment on web platforms or emojis cut off on ios for names with emojis

**Comment by shawnborton** [comment]
Hmm we do not want to be changing the line height across the app like this though, notice how in the bug report above we now have a space under the sender name. I think we need to revert the offending PR.

**Comment by iwiznia** [comment]
Context https://expensify.slack.com/archives/C01GTK53T8Q/p1722351467920939

There's a revert here https://github.com/Expensify/App/pull/46463 and a potential fix here https://github.com/Expensify/App/pull/46478 and both are getting adhoc builds to test them out.

**Comment by roryabraham** [comment]
https://github.com/Expensify/App/pull/46463 was reverted, so let's retest this on staging...

**Comment by roryabraham** [comment]
easy enough, confirmed this is fixed

<img width="365" alt="image" src="https://github.com/user-attachments/assets/baeace19-e4f4-4d52-8add-6ba251c33296">
