### ISSUE TITLE
mWeb - room - On leaving private room, user logged out of the site

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4785218
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login as gmail user
3. Tap on a private room -- header-- leave

## Expected Result:
On leaving private room, user must not be logged out of the site

## Actual Result:
On leaving private room, user logged out of the site

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ea5cb542-3726-4601-9ec1-7492b5d93e32

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by alexpensify** [comment]
I'll get to this one tomorrow.

**Comment by alexpensify** [comment]
It's still on my testing list; I'll get to it soon.

**Comment by alexpensify** [comment]
No update yest

**Comment by alexpensify** [comment]
Closing - I tested in a test Gmail account and confirmed that this issue is not happening anymore.
