### ISSUE TITLE
Emoji - Specific "♤"Emoji shows blank in popup and doesn't appear in "Frequently Used"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46496]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

 
**Issue found when executing PR** https://github.com/Expensify/App/pull/45860
## Action Performed:
1. Access New Expensify app
2. Sign into a valid account
3. Send "♤" emoji in the composer and Highlight it with the cursor &/or check Frequently used

## Expected Result:
User expects that in the popup, the "♤" is displayed but enlarged and also shows in "Frequently used" emoji section

## Actual Result:
♤ does not appear in the popup and also does not appear in frequently used section

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b499164b-0c88-4081-a124-ad21ba00f498

<img width="1440" alt="!Does_not_show_" src="https://github.com/user-attachments/assets/061edfb2-aa5f-42a4-8952-fc331965a8b3">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@VictoriaExpensify  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by VictoriaExpensify** [comment]
So this does look buggy but seems like a pretty low priority if it's only happening with the one emoji. I wonder if this needs to a reduced price if we decide to fix it. I'm going to look into that

**Comment by VictoriaExpensify** [comment]
Ok I've looked into this more. This issue actually isn't related to emoji's, it's related to ascii characters. But it's actually different to the issue being described because this actually effects all ascii characters:

![image](https://github.com/user-attachments/assets/da5c6e04-4180-4683-aa51-a994e7d77f1c)

@ShridharGoel would you interested in giving an updated proposal based on the updated problem? If not, we might just close this one out and have a new issue reopened.

**Comment by VictoriaExpensify** [comment]
I'm going to close this one out because the issue described is not the correct issue. Since this is very minor, closing it out seems like the right course of action.
