### ISSUE TITLE
[HOLD for payment 2024-08-14] [HOLD for payment 2024-08-09] [HOLD for payment 2024-08-07] Expense - "Business bank account" option appears briefly when paying with Expensify

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46490]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace does not have bank account.

1. Launch New Expensify app.
2. Go to workspace chat.
3. Submit an expense.
4. Tap Pay with Expensify.

## Expected Result:
"Business bank account" option will not appear briefly when paying with Expensify

## Actual Result:
"Business bank account" option appears briefly when paying with Expensify

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d26c1705-9999-498e-99b0-fb4cc0b2072b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by trjExpensify** [comment]
@marcaaron if you're okay [with that](https://github.com/Expensify/App/issues/46339#issuecomment-2257298010), can we get a fix up here?

**Comment by marcaaron** [comment]
Yeah if someone wants to raise a PR I can help review and merge.

**Comment by marcaaron** [comment]
@gijoe0295 let's fix this as part of https://github.com/Expensify/App/issues/46339 - I will help CP the fix when it's ready.

**Comment by mountiny** [comment]
@gijoe0295 what is your updated ETA?

**Comment by roryabraham** [comment]
We're CPing a fix for the blocker, but it's not clear to me if there's any other cleanup still needed

**Comment by trjExpensify** [comment]
>We're CPing a fix for the blocker, but it's not clear to me if there's any other cleanup still needed

Nah, we can use the other issue for @gijoe0295's PR for the workspace chat redirect fix: https://github.com/Expensify/App/pull/46557

**Comment by trjExpensify** [comment]
Going to take care of payment for this one here: https://github.com/Expensify/App/issues/46339#issuecomment-2291034991
