### ISSUE TITLE
[$250] Cleanup: move `ComposerRef` to the `ComposerWithSuggestion` where its implemented 

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#46499]
There is the `ComposerRef` type which is being used in `ReportActionCompose`. The ref however is implemented in`ComposerWithSuggestion` and it would be more natural to have that close together, and then let `ReportActionCompose` import it.

Ref: https://github.com/Expensify/App/pull/46091#discussion_r1696891379

**Comment by puneetlath** [comment]
@hannojg are you planning on tackling this?

**Comment by hannojg** [comment]
As I am going OOO tomorrow @kirillzyusko can you do this little cleanup please!

**Comment by kirillzyusko** [comment]
Sure, feel free to assign me on this ticket!

**Comment by kirillzyusko** [comment]
I think it can be closed because PR got merged 👀

**Comment by puneetlath** [comment]
Payment summary: 
- $250 - C+ - @Ollyws - to be paid via NewDot

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
