### ISSUE TITLE
[Hold for payment 2024-08-26] [$250] Update styles for next steps banner for held transactions

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#46509]
We recently updated the style of our next steps banner for reports and expenses:
![CleanShot 2024-07-30 at 17 25 36@2x](https://github.com/user-attachments/assets/f4e074a4-506d-4402-a88e-b6bb0b994247)

However, we did not update this style for the next steps banner for held expenses, both at the report level and expense level:
![CleanShot 2024-07-30 at 17 26 02@2x](https://github.com/user-attachments/assets/e7f68116-9fe5-41ae-a667-ff108b7bba9c)

![CleanShot 2024-07-30 at 17 26 12@2x](https://github.com/user-attachments/assets/98e11b48-de0a-4943-b078-a2c0dc2c427f)

Let's update these next steps banners to match our recent update. 

Note that it should look like this with a stopwatch icon in place of the badge:
![CleanShot 2024-07-30 at 17 26 55@2x](https://github.com/user-attachments/assets/c99e2468-947e-461a-be93-51331e65eda8)

cc @mountiny @dylanexpensify @JmillsExpensify @Expensify/design 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153a5c4ff2583c612</li>
        <li>Upwork Job ID: 1818308885218393739</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103348525</li>
<li>abzokhattab | Contributor | 103348527</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by joekaufmanexpensify** [comment]
Pending review of proposals

**Comment by eh2077** [comment]
Thank you all for your proposals!

I think we should go with @abzokhattab 's [proposal](https://github.com/Expensify/App/issues/46509#issuecomment-2258690965). Their solution looks good to me and I also agree with their suggestion to do some cleanup to make the code cleaner.

🎀👀🎀 C+ reviewed

**Comment by chiragsalian** [comment]
@abzokhattab proposal LGTM. Feel free to create the PR.

**Comment by joekaufmanexpensify** [comment]
@abzokhattab is there an ETA for the PR here?

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by joekaufmanexpensify** [comment]
All good! PR still in review

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
PR merged and on staging!

**Comment by joekaufmanexpensify** [comment]
Payments here are: 

- @abzokhattab - $250 for PR via Upwork. 
- @eh2077 - $250 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment!

**Comment by joekaufmanexpensify** [comment]
@abzokhattab $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@eh2077 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
