### ISSUE TITLE
[HOLD for payment 2024-08-09] Bump expensify-common

### ISSUE THREAD

**Issue by marcochavezf** [Expensify/App#46522]
Coming from this vulnerability [fix](https://github.com/Expensify/expensify-common/pull/767) from Snyk, we will bump the expensify-common version in App. 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: N/A internal 
 - Contributor+: @allroundexperts - $250, please request via NewDot 

No Upwork job on this!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
