### ISSUE TITLE
NetSuite - Sync isn't failing when random data was set in Custom Segments/records

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46537]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when** https://github.com/Expensify/App/pull/46155
## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Custom Segments/records
9. Click on the "Add custom segment/record" button
10. Add a segment or record with random data
11. Navigate back to the Accounting

## Expected Result:
Sync should be failing

## Actual Result:
Sync isn't failing when random data was set in Custom Segments/records

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9b409b92-1fdf-44d0-9477-935e9e80b521

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment]
Looking at this this week

**Comment by muttmuure** [comment]
Still looking into ti

**Comment by muttmuure** [comment]
I'm pretty sure we don't roll back syncs on custom segments and fields and so this is expected.
