### ISSUE TITLE
[HOLD for payment 2024-09-21][$250] [Search v2.1] - Dropdown Menu Misalignment After Page Minimize and Maximize

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46532]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Workspace Chat > Click Plus Sign > Submit Expense
2. Add a merchant and submit it
3. Go to Search > Minimize the page > Select checkbox next to expense > Click on Chevron (next to "x selected" button top right) > Dropdown appears
4. Maximize the page and observe that the dropdown appears in the middle instead of aligning with the chevron

## Expected Result:
When an expense is selected in search, minimized, and the chevron is clicked to open the dropdown, maximizing the page should align the dropdown with the chevron

## Actual Result:
When an expense is selected in search, minimized, and the chevron is clicked to open the dropdown, maximizing the page causes the dropdown to appear in the middle instead of aligning with the chevron

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/118e480d-5cca-40bc-8fc0-263065d459fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01697c80b209631150</li>
        <li>Upwork Job ID: 1819349098199446682</li>
        <li>Last Price Increase: 2024-08-23</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103654124</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment]
@situchan what do you think of the proposal https://github.com/Expensify/App/issues/46532#issuecomment-2264574139 ?

**Comment by situchan** [comment]
Awaiting proposals

**Comment by situchan** [comment]
Awaiting more proposals

**Comment by situchan** [comment]
@daledah thanks. can you please share test branch?

**Comment by sonialiap** [comment]
@RachCHopkins I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for a proposal to be accepted

**Comment by situchan** [comment]
Not overdue

**Comment by situchan** [comment]
@daledah's [proposal](https://github.com/Expensify/App/issues/46532#issuecomment-2264574139) looks good and tests well.
🎀👀🎀 C+ reviewed

**Comment by RachCHopkins** [comment]
@situchan any update here with your review?

**Comment by situchan** [comment]
The PR is on hold for https://github.com/Expensify/App/issues/48511 - https://github.com/Expensify/App/pull/47987#issuecomment-2329409533

**Comment by luacmartins** [comment]
https://github.com/Expensify/App/pull/48862 is merged

**Comment by RachCHopkins** [comment]
@sonialiap you can have this one back too! 😛

**Comment by sonialiap** [comment]
waiting for @daledah to accept the offer in upwork 💰

**Comment by sonialiap** [comment]
All paid ✔️
