### ISSUE TITLE
IOU - Unable to edit year on request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46530]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**gocemate+a774@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with gmail account
2. Go to FAB> Submit expense> Finish the flow
3. Go to thread transaction> Click on Date> Select other year> Save

## Expected Result:
The year date should be saved

## Actual Result:
The year date is not saved when user edit it after creating request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3d925587-4e41-4e0b-bc37-f50f58c381f4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Unable to edit year on request

### What is the root cause of that problem?
We are only chaning `DateView` on year selection
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/components/DatePicker/CalendarPicker/index.tsx#L71-L82
### What changes do you think we should make in order to solve the problem?

We can call `onSelected` with the new year value inserted
```
setCurrentDateView((prev) => {
            const newCurrentDateView = setYear(new Date(prev), year);
            setYears((prevYears) =>
                prevYears.map((item) => ({
                    ...item,
                    isSelected: item.value === newCurrentDateView.getFullYear(),
                })),
            );
            onSelected?.(format(new Date(newCurrentDateView), CONST.DATE.FNS_FORMAT_STRING));

            return newCurrentDateView;
        });
    };
```
### What alternative solutions did you explore? (Optional)

**Comment by miljakljajic** [comment]
I agree - I don't think this is a bug, we'd need the whole date to be inputted. Going to close.
