### ISSUE TITLE
Categories - Payroll code system message in #admins is missing "Payroll Code"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46533]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4787156
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace is under Control plan.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click on any category.
4. Click Payroll code.
5. Enter anything and save it.
6. Go to #admins room of the workspace.

## Expected Result:
The system message for updating payroll code will display "Payroll Code" in the message.

## Actual Result:
The system message for updating payroll code is missing "Payroll Code" in the message.

It shows "updated the category "Advertising" by adding a of hello1234".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5c2cf4c4-7d0c-4c81-bdbd-a3d16067d50e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control.

**Comment by FitseTLT** [comment]
Should be fixed in BE

**Comment by rushatgabhane** [comment]
🎀 👀 🎀 backend issue

**Comment by adelekennedy** [comment]
@youssef-lr can you check if this was already fixed in the BE?

**Comment by youssef-lr** [comment]
>Should be fixed in BE

@adelekennedy I think they meant this should be an internal issue as it's backend related

**Comment by adelekennedy** [comment]
oh of course 🤦‍♀️

**Comment by adelekennedy** [comment]
@youssef-lr any steps I need to take here?

**Comment by youssef-lr** [comment]
@adelekennedy I think we need to find who worked on this so they can submit a fix, it should be straightforward. I would work on it but I'm OOO this week and only working on my ongoing PRs.

**Comment by youssef-lr** [comment]
cc @dangrous maybe?

**Comment by dangrous** [comment]
Nah I did tax codes not payroll codes - I can try to take a look though, it was all part of the same project. @Gonals maybe, too?

**Comment by dangrous** [comment]
Fixed it, I'll grab this.

**Comment by youssef-lr** [comment]
Thanks @dangrous!

**Comment by dangrous** [comment]
This is on prod now so I think we can close out!

<img width="430" alt="image" src="https://github.com/user-attachments/assets/b3c571fd-688b-4877-9c4d-3bede9c035ee">
