### ISSUE TITLE
NetSuite - "something went wrong" error when trying to remove custom segment or record

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Custom Segments/records
9. Click on the "Add custom segment/record" button
10. Add a segment or record with random data
11. Click on the created segment or record
12. Click on the "Remove" button

## Expected Result:
I should be able to remove it

## Actual Result:
"Oops... something went wrong and your request could not be completed. Please try again later." error when trying to remove custom segment or record

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/374f0cdd-3d3b-4f24-982d-f88aead89de1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
https://expensify.slack.com/archives/C06ML6X0W9L/p1722440079484929?thread_ts=1722319754.816589&cid=C06ML6X0W9L

**Comment by aldo-expensify** [comment]
Need to wait for deploy

**Comment by zanyrenney** [comment]
Merged above!
