### ISSUE TITLE
[hold for payment 2024-09-23] [$250] NetSuite - Text with "Translation missing" is visible twice during the sync

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46574]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish

## Expected Result:
There should't be "Translation missing" text in the sync messages

## Actual Result:
Text with "Translation missing" is visible twice during the sync

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/51368eb2-6fa2-4ec8-a9fa-6aa9ff546087

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5d3500f00f05a6e</li>
        <li>Upwork Job ID: 1818650164401405766</li>
        <li>Last Price Increase: 2024-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 103369768</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ShridharGoel</details>

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
Pending review of proposals

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/46574#issuecomment-2260406247) from @ShridharGoel looks good to me. We will need the copy to be displayed for `netSuiteImportVendorsTitle` and `netSuiteCustomImportListsTitle`.

🎀 👀 🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment]
@ShridharGoel is there an ETA for PR here?

**Comment by joekaufmanexpensify** [comment]
I can. Could you share the specific copy you need translation for and I'll get it

**Comment by pecanoro** [comment]
@ShridharGoel Do we need English and Spanish copy or only Spanish?

**Comment by joekaufmanexpensify** [comment]
@ShridharGoel could you confirm this when you have a sec?

**Comment by pecanoro** [comment]
Thanks for claririfying! I can handle the Spanish translations, @joekaufmanexpensify can you see how we get the English copy verified for this?

**Comment by joekaufmanexpensify** [comment]
We need translation for `netSuiteImportVendorsTitle` and `netSuiteImportCustomListsTitle`. Based on the video [here](https://github.com/Expensify/App/issues/46574#issue-2439931240), these are items we're flashing to the customer to show that everything from NetSuite is importing. 

I think this could be as simple as:

- `Importing vendors` 
- `Importing custom lists` 

But looping in marketing for confirmation.

**Comment by sobitneupane** [comment]
@ShridharGoel Could you let us know when we can expect the PR?

**Comment by joekaufmanexpensify** [comment]
[Spanish translations](https://expensify.slack.com/archives/C21FRDWCV/p1723554365749819): 

- `Importing vendors` > `Importar proveedores`
- `Importing custom lists > `Importar listas personalizadas`

**Comment by joekaufmanexpensify** [comment]
Got sign off on the translations.

**Comment by joekaufmanexpensify** [comment]
@ShridharGoel all copy is finalized. Could you please confirm when PR will be up?

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
PR in review, seems like it will be done soon

**Comment by joekaufmanexpensify** [comment]
Hm, that's wrong. I updated this issue earlier today.

**Comment by joekaufmanexpensify** [comment]
PR on staging

**Comment by joekaufmanexpensify** [comment]
PR was deployed to prod on the 16th. Automation did not work, but payment is due today

**Comment by joekaufmanexpensify** [comment]
Will handle later today!

**Comment by joekaufmanexpensify** [comment]
Payment here: 

- $250 to @ShridharGoel for PR via Upwork. 
- $250 to @sobitneupane for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment]
@ShridharGoel your original offer expired, so I opened a [new job](https://www.upwork.com/jobs/~021838317961121389816) and sent you a new offer. Please accept it so we can pay you.

**Comment by joekaufmanexpensify** [comment]
@sobitneupane please request payment via NewDot whenever you're ready

**Comment by joekaufmanexpensify** [comment]
@ShridharGoel $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
Closing as all that's left is for @sobitneupane to request payment via NewDot. TY everyone!

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
