### ISSUE TITLE
[HOLD for payment 2024-09-17][Search v2.2] [App] Create status bar (Chat)

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46588]
Implement [this section](https://docs.google.com/document/d/1NdGqKrGsglFzi2vdbJipgBj-nesUnoAIiclBL4fFrNc/edit#bookmark=id.khdt6jg6k3xq) of the design doc

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by luacmartins** [comment]
Still waiting on doc reviews.

**Comment by luacmartins** [comment]
@Expensify/design can I get the `Invoices` and `Trips` illustrations exported for App use please? https://www.figma.com/design/YHaWaw3F0PgxqI0tXHJVeY/Search-v1-v3?node-id=882-235709&t=KeEWs0szPlOnILzT-0

<img width="177" alt="Screenshot 2024-08-09 at 7 57 29 PM" src="https://github.com/user-attachments/assets/a48e69ee-61a0-4f5a-973c-e66b19bd990b">
<img width="305" alt="Screenshot 2024-08-09 at 7 57 18 PM" src="https://github.com/user-attachments/assets/3468c6ca-3484-4d33-ab5b-1f2671ec9345">

**Comment by luacmartins** [comment]
Thank you!

**Comment by luacmartins** [comment]
@shubham1206agra will be taking on the implementation!

**Comment by shawnborton** [comment]
Here you go: [simple-illustration__commentbubbles.svg.zip](https://github.com/user-attachments/files/16661751/simple-illustration__commentbubbles.svg.zip)

**Comment by ikevin127** [comment]
Not overdue, we're currently working on opening the draft PR.

**Comment by luacmartins** [comment]
This PR was deployed to production yesterday.

**Comment by twisterdotcom** [comment]
Payment due in next Tuesday (I'll be out, so I'll try to pay out Monday/Wednesday).

**Comment by twisterdotcom** [comment]
Okay, payment summary (@luacmartins correct me if the price is wrong. I'm defaulting to $250 because nothing else was specified here and there's no `High Priority` label.

- @shubham1206agra paid $250 via UpWork [here](https://www.upwork.com/nx/wm/offer/new/1028761871) (Contributor)
- @ikevin127 paid $250 via UpWork [here](https://www.upwork.com/nx/wm/offer/103984407) (C+)

**Comment by luacmartins** [comment]
@twisterdotcom prices are correct. We've been paying the default $250 for all search related issues.
