### ISSUE TITLE
[Search v2.2] [App] Refactor Transaction and Report types to Expense type

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46580]
Implement [this section](https://docs.google.com/document/d/1NdGqKrGsglFzi2vdbJipgBj-nesUnoAIiclBL4fFrNc/edit#bookmark=id.o5xumsu0vciq) of the design doc

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by luacmartins** [comment]
Still waiting on doc reviews.

**Comment by JmillsExpensify** [comment]
Implementation on-going

**Comment by JmillsExpensify** [comment]
Remind me, are you paid via Upwork or Expensify?

**Comment by JmillsExpensify** [comment]
Offer sent

**Comment by JmillsExpensify** [comment]
All paid out! Closing this one, as regression and related considerations will be handled centrally.
