### ISSUE TITLE
[HOLD for payment 2024-08-18][Search v2.2] [App] Create Trip contextual filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46584]
Implement [this section](https://docs.google.com/document/d/1NdGqKrGsglFzi2vdbJipgBj-nesUnoAIiclBL4fFrNc/edit#bookmark=id.4zpczbiuk0ea) of the design doc

**Comment by luacmartins** [comment]
Still waiting on doc reviews.

**Comment by abekkala** [comment]
@luacmartins: @Beamanator [commented](https://github.com/Expensify/App/pull/47111#issuecomment-2294138639) that this one most likely was deployed to prod on Aug 11? 

it's a bit of a rabbit hole for me? can you confirm that? If so, this one would be ready for payment.

**Comment by luacmartins** [comment]
I agree with @Beamanator it was deployed to prod on Aug 11

**Comment by abekkala** [comment]
@rayane-djouah payment sent and contract ended - thank you! 🎉
