### ISSUE TITLE
[HOLD for payment 2024-09-06][Search v2.2] [App] Create status bar (Invoice)

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46582]
Implement [this section](https://docs.google.com/document/d/1NdGqKrGsglFzi2vdbJipgBj-nesUnoAIiclBL4fFrNc/edit#bookmark=id.khdt6jg6k3xq) of the design doc

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by luacmartins** [comment]
Still waiting on doc reviews.

**Comment by johncschuster** [comment]
Thanks, @rayane-djouah! I'll get payment issued one we've passed the regression threshold 👍

**Comment by johncschuster** [comment]
Payment due tomorrow 👍

**Comment by johncschuster** [comment]
@rayane-djouah I've sent you the offer, [here](https://www.upwork.com/nx/wm/offer/103846441). Can you accept that? I'll pay this out today.

**Comment by johncschuster** [comment]
Paid! Thanks for your contributions! 🎉
