### ISSUE TITLE
[$250] [HOLD for Payment 2024-08-22][Search v2.2] [App] Create Invoice contextual filter

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46581]
Implement [this section](https://docs.google.com/document/d/1NdGqKrGsglFzi2vdbJipgBj-nesUnoAIiclBL4fFrNc/edit#bookmark=id.e80gjzt2w5bs) of the design doc

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c09a447fd46cc75a</li>
        <li>Upwork Job ID: 1828934132202049940</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

**Comment by luacmartins** [comment]
Still waiting on doc reviews.

**Comment by luacmartins** [comment]
Bump @bfitzexpensify for payment

**Comment by mallenexpensify** [comment]
@rayane-djouah can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01c09a447fd46cc75a

**Comment by mallenexpensify** [comment]
Contributor+: @rayane-djouah paid $250 via Upwork. 

I'm going to close, assuming test cases will be created as part of the Search v2.2 project. Comment/reopen if you disagree.
