### ISSUE TITLE
Expense Reports details are inconsisten on View page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46612]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Christinadobrzyn 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722446516477929

## Action Performed:
Prerequisites - account must have a submitted and approved report prior to the below testing

1. Sign into new.expensify of the admin account with the approved report
2. Click on the Search icon in the lower left of the screen
3. Find the approved report > click View
4. Click the drop-down in the expense report header. Notice it only offers Settings
5. Click on the expense report name in the 'view' header - you will be redirected to the report.
6. Click the drop-down arrow in the expense report header. Notice the Unapproved, Members, Export options.

## Expected Result:
The drop-down arrow show show the same details from the View page as from the expense report page
The expense report page shows "Members", "Export", "Unapprove"

## Actual Result:
The View page only shows "Settings"
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/854fa449-6e37-480b-a036-bbef019523c1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Related Convo - https://expensify.slack.com/archives/C036QM0SLJK/p1722467012833909?thread_ts=1722445604.933729&cid=C036QM0SLJK

**Comment by Christinadobrzyn** [comment]
I'm trying to see if we need to keep this open or close it since it sounds like we're already working on a solution.

**Comment by Christinadobrzyn** [comment]
Ah - it looks like this is already being worked on here - https://github.com/Expensify/App/issues/45408

@VictoriaExpensify Maybe I'll take this? I'm thinking we put a HOLD on this and monitor https://github.com/Expensify/App/issues/45408 - once complete just double-check it's what we want. feel free to assign this to me if you'd like (or we can manage it together).
