### ISSUE TITLE
 Taxes - Tax code content is not shown until the workspace is upgraded to Control

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46624]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/45866
**Version Number:** 9.0.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a Collect workspace.
3. Go to workspace settings > Taxes.
4. Click on any tax.
5. Note that Tax code is empty.
6. Click on the Tax code.
7. Click Upgrade.
8. Note that Tax code content is only shown after upgrading to Control.

## Expected Result:
in Step 5, Tax code content will be shown even if the workspace plan is Collect (production behavior).

## Actual Result:
in Step 5, Tax code content is not shown until the workspace is upgraded to Control (Step 8).

## Workaround:
unknown 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1b9cd591-40ee-4771-ac56-dd8909d4a114

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-control

**Comment by neonbhai** [comment]
This is expected as noted in https://github.com/Expensify/App/pull/45866#issuecomment-2243358998

**Comment by rushatgabhane** [comment]
this is not a bug. it is expected

**Comment by rushatgabhane** [comment]
thanks for tagging @neonbhai

**Comment by brunovjk** [comment]
Should we create a regre test [here](https://github.com/Expensify/App/issues/45643) for this [scenario](https://github.com/Expensify/App/issues/46624#issue-2441082162)?

**Comment by strepanier03** [comment]
@brunovjk - I agree we should create the reg test for this. Gonna close out this GH but feel free to comment in that other one.
