### ISSUE TITLE
[HOLD] Attachments - Video closes when opening video in full screen right after uploading it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46621]
HOLD: https://github.com/Expensify/App/issues/9402

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Bug found when validating https://github.com/Expensify/App/pull/45352
**Version Number:** 9.0.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** no unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat.
3. Upload a video.
4. Click on the video right after uploading it.
5. Play the video.

## Expected Result:
The video will not close

## Actual Result:
The video closes when opening video in full screen right after uploading it.
The same issue happens with other attachments.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5313ebbd-d21b-4937-adbd-ee80a4fbfcd3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by roryabraham** [comment]
cc @kidroca I think this might be related to https://github.com/Expensify/App/pull/44889

**Comment by aldo-expensify** [comment]
Testing reverting the PR https://github.com/Expensify/App/pull/44889 I see that while the video is uploading we just show:

<img width="478" alt="image" src="https://github.com/user-attachments/assets/980c1f05-3dfd-466d-b53d-08b564e08ffa">

so it is not possible to open the modal like it is shown in this deploy blocker

**Comment by joekaufmanexpensify** [comment]
Sounds good. @aldo-expensify given this is already being addressed in the above PR, do you think we can close this out?

**Comment by roryabraham** [comment]
Or rather, let's just put this on HOLD

**Comment by roryabraham** [comment]
that way this doesn't slip through the cracks

**Comment by aldo-expensify** [comment]
Sounds good, thanks for the help @roryabraham

**Comment by joekaufmanexpensify** [comment]
Yep! Will follow along with the other issue to make sure this gets fixed

**Comment by joekaufmanexpensify** [comment]
Other issue still in progress

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
Just checked, and this is no longer reproducible. Closing!
