### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] Workspace -App redirects to workspace editor with error when returning from not here page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46646]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/46479
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Paste https://github.com/Expensify/App/pull/46479
in any chat.
3. Tap on the link.
4. Swipe back to return to previous page (not app back button).
5. Might need to repeat Step 3 and 4 one more time to see the workspace editor.

## Expected Result:
In Step 4, app will not return to workspace editor as the workspace link is invalid.

## Actual Result:
In Step 4, app returns to workspace editor with the error "Invalid Policy ID".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2bfeab4b-d320-4127-805f-7c7ec2347bbb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e953d4b48a8b7a8</li>
        <li>Upwork Job ID: 1821050583313225827</li>
        <li>Last Price Increase: 2024-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103516762</li>
<li>dominictb | Contributor | 103942180</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by stephanieelliott** [comment]
This seems like this may be a regression from https://github.com/Expensify/App/issues/46183 -- posted there to have the PR author take a look.

**Comment by bernhardoj** [comment]
This issue is present before the PR.

**Comment by stephanieelliott** [comment]
Thanks @bernhardoj -- we'll carry on and treat this as a standalone issue then.

**Comment by stephanieelliott** [comment]
Not overdue, still waiting for proposals

**Comment by stephanieelliott** [comment]
Bump @adamgrzybowski  -- any chance you can help us on this one?

**Comment by adamgrzybowski** [comment]
I am currently on vacations. I will be back after september 10.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace app redirects to the workspace editor with an error after returning from a different page.

### What is the root cause of that problem?

Native swipe back is not navigated to desired place. When `FullPageNotFoundView` shown in workspace pages, we should navigate to workspace, it's wrapped in `PolicyUtils.goBackFromInvalidPolicy` function.

### What changes do you think we should make in order to solve the problem?

In Android, we can customize back button/swipe behavior by using `BackHandler.addEventListener('hardwareBackPress'` and overriding the back function with `onBackButtonPress` in `FullPageNotFoundView`.

src/components/BlockingViews/FullPageNotFoundView.tsx
```tsx
    // To block android native back button behavior
    useFocusEffect(
        useCallback(() => {
            if (!onBackButtonPress) {
                return;
            }
    
            const backHandler = BackHandler.addEventListener('hardwareBackPress', () => {
                onBackButtonPress();
                return true;
            });
    
            return () => {
                backHandler.remove();
            };
        }, [onBackButtonPress]),
    );
```

IOS
`hardwareBackPress` only supported in Android, but in iOS I've noticed that if we disable gesture in the last screen in the same navigator, then previous screen swipe action will be executed. So, if the not found page shown, we can disable all gestures in workspace screens, except the first screen in the route stack.

```tsx
    const navigation = useNavigation();

    // Handle back swipe on iOS
    useLayoutEffect(() => {
        if (!shouldShow) {
            return;
        }

        const state = navigation.getState();
        if (!state) {
            return;
        }

        // Check if the last route's name is 'not-found' or if there is no parent navigator
        const lastRoute = state.routes[state.routes.length - 1];
        if (lastRoute.name === SCREENS.NOT_FOUND || !navigation.getParent()) {
            return;
        }

        // Check if the first route's name is not the initial workspace screen
        // Currently we only have case for workspace, this check to avoid potential regression
        if (state.routes[0].name !== SCREENS.WORKSPACE.INITIAL) {
            return;
        }

        // Iterate through all routes and disable gestures for all except the first one
        state.routes.forEach((route, index) => {
            navigation.setOptions({
                gestureEnabled: index === 0,
            });
        });
    }, [navigation]);
```

I placed the code in `FullPageNotFoundView.tsx` without any problems. If needed, we can create platform-specific code for safety.

[Branch for this solution.](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/46646-swipe-back-native-not-found-page?expand=1)

### What alternative solutions did you explore? (Optional)
N/A
s

**Comment by wildan-m** [comment]
@shubham1206agra any opinion about my proposal?

https://github.com/Expensify/App/issues/46646#issuecomment-2320353524

**Comment by stephanieelliott** [comment]
Hey @shubham1206agra can you review the proposal here please? https://github.com/Expensify/App/issues/46646#issuecomment-2320353524

**Comment by wildan-m** [comment]
@shubham1206agra you might want to call CME to discuss your concern and decide whether to move with current proposal or do another option.

**Comment by stephanieelliott** [comment]
> I need to consult someone who is an expert in the Navigation code.

Hey @shubham1206agra, were you able to do this yet? If no, maybeyou start a Slack thread so we can chat through your concerns? That will let us pull in a wider audience so we figure out next steps here

**Comment by mountiny** [comment]
I have reached out to @adamgrzybowski [here](https://expensify.slack.com/archives/C04878MDF34/p1726048942823379)

**Comment by lakchote** [comment]
Let's go with @dominictb's alternative proposal.

I'll assign you as the reviewer too @adamgrzybowski 👍

**Comment by stephanieelliott** [comment]
Hey @shubham1206agra the PR for this is waiting on your review, can you take a look? https://github.com/Expensify/App/pull/49226

**Comment by stephanieelliott** [comment]
PR is still actively being reviewed.

**Comment by stephanieelliott** [comment]
Hey @dominictb seems like you were investigating a few things, what's the latest on this one?

**Comment by wildan-m** [comment]
@adamgrzybowski what's your opinion about my proposal?

https://github.com/Expensify/App/issues/46646#issuecomment-2320353524

**Comment by lakchote** [comment]
> I'll provide update today.

Could you please give the current state of the situation? Thanks!

**Comment by stephanieelliott** [comment]
PR is still under review https://github.com/Expensify/App/pull/49226

**Comment by stephanieelliott** [comment]
PR is under active review

**Comment by stephanieelliott** [comment]
Hey @shubham1206agra the PR is blocked on you, can you review?

**Comment by lakchote** [comment]
friendly bump @shubham1206agra as the PR has been ready for review for a few days already.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @dominictb $250 via Upwork - PAID 
 - Contributor+: @lakchote $250 via Upwork -- I created a payment issue but am not seeing your Upwork profile, can you please post to this Upwork job? https://www.upwork.com/jobs/~021858766650246025249
 
 Upwork job is here: https://www.upwork.com/jobs/~021858766650246025249

**Comment by lakchote** [comment]
> @stephanieelliott I think you need to pay me, not @lakchote (internal employee)

Exactly, @stephanieelliott please pay @shubham1206agra as I'm an internal employee

**Comment by stephanieelliott** [comment]
Oh my gosh @lakchote, I'm sorry -- I know you are an internal employee 🤦‍♀️. I extended this to the wrong person, @shubham1206agra offer was extended to you https://www.upwork.com/nx/wm/offer/104996565

**Comment by stephanieelliott** [comment]
All paid up!
