### ISSUE TITLE
[HOLD for payment 2024-08-13] [HOLD for payment 2024-08-09] [$250] Expense- The number of Expense Request is not updated in the Report Conversation preview

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46647]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4796963
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open [https://staging.new.expensify.com/.](https://staging.new.expensify.com/)
2. Log in with your HT account
3. Create WS
4. Navigate to the WS room
5. Send 3 manual Expense Requests to the room

## Expected Result:
When a new expense is added, the Expense Request quantity should immediately update in the Report Conversation preview

## Actual Result:
The number of Expense Request is not updated in the Report Conversation preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7d768cd5-d1e3-465d-b341-df5eda99730e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015476f4ee9e9cc44e</li>
        <li>Upwork Job ID: 1819064522910596934</li>
        <li>Last Price Increase: 2024-08-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by chiragsalian** [comment]
Removing web-e blocker label. Reasoning [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1722532967240439?thread_ts=1722531890.919709&cid=C01GTK53T8Q).

**Comment by grgia** [comment]
https://github.com/Expensify/App/pull/46500

**Comment by grgia** [comment]
Thanks for the solution @nyomanjyotisa, I've opened a PR [here](https://github.com/Expensify/App/pull/46681) because it is a deploy blocker. Can you confirm a fair pay out for solution @kevinksullivan

**Comment by roryabraham** [comment]
fix CP'd, requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1722540773455279

**Comment by isagoico** [comment]
I'm not able to reproduce in the latest version v9.0.15-9 in staging (Chrome/Web): 
![image](https://github.com/user-attachments/assets/b85956d3-814d-4323-8703-b4914f87be7b)
