### ISSUE TITLE
 [HOLD for Payment 2024-08-22][$250] Multi tag - Selection mode remains on main tag list after returning from sub tag list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46658]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace is connected to QBO.

1. Launch New Expensify app.
2. Go to workspace settings > Tags.
3. Tap on any main tag.
4. Long press on any sub tag.
5. Tap Select.
6. Swipe right to return to previous page (not app back button).

## Expected Result:
Selection mode will be dismissed on the main tag list because main tag cannot be selected for multi tags.

## Actual Result:
Selection mode remains on main tag list after returning from sub tag list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a7b2e751-374c-4453-bc78-ff704b85e081

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013892471bd59b7984</li>
        <li>Upwork Job ID: 1819070503401243549</li>
        <li>Last Price Increase: 2024-08-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by carlosmiceli** [comment]
I think the issue comes from here: https://github.com/Expensify/App/pull/46096

@jasperhuangg is this a deploy blocker? Because what I'm seeing is that it's all new functionality, right? Wanna decide what we do here?

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to take this as it comes from my PR

**Comment by ikevin127** [comment]
cc @RachCHopkins for payments

**Comment by RachCHopkins** [comment]
@carlosmiceli it's not clear to me here who needs to be paid, would you mind giving me a wee summary of who did what?

**Comment by carlosmiceli** [comment]
I think the PR is authored by @filip-solecki and was reviewed by @ikevin127, correct?

**Comment by ikevin127** [comment]
✅ Correct, I'm the only one requiring payment here.

**Comment by ikevin127** [comment]
✅ Correct, I'm the only one requiring payment here.

cc @RachCHopkins

**Comment by RachCHopkins** [comment]
@ikevin127 I have sent you an offer for the job!

**Comment by ikevin127** [comment]
@RachCHopkins Offer accepted, thanks!

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor+: @ikevin127  paid $250 via Upwork
Upwork job [here](https://www.upwork.com/jobs/~013892471bd59b7984)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
