### ISSUE TITLE
[$125] Chat - 'Up Arrow' Doesn't Open Edit Modal for Message with Thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46663]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to any chat and write a message.
2. Reply to that message and click on the header.
3. Click on 'Leave.'
4. Click on the 'Up Arrow.'

## Expected Result:
The 'Up Arrow' should open the edit modal for the parent message that has a thread.

## Actual Result:
The 'Up Arrow' doesn't open the edit modal for messages that have a thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/09830755-f497-4496-ab7d-ed570d5db2d2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b9f50804317eebf8</li>
        <li>Upwork Job ID: 1819059178812692898</li>
        <li>Last Price Increase: 2024-08-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by youssef-lr** [comment]
This is a pretty minor bug so demoting, one has to leave a thread first before they can't edit using the arrow.

**Comment by oscarguinane** [comment]
Contributor details
Your Expensify account email: [oscar+expensify@bloodandtreasure.com](mailto:oscar+expensify@bloodandtreasure.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~017275408a967b697f

Unable to reproduce based on those steps, operating system and browser version.

https://github.com/user-attachments/assets/ae2275f8-83a7-4f69-bb2b-8ef9e9b3b834

**Comment by oscarguinane** [comment]
To be clear, I can’t reproduce it in staging, production or local dev ENVs

**Comment by oscarguinane** [comment]
In Chrome or Safari

**Comment by alexpensify** [comment]
Thanks, @youssef-lr, for noting that there is no action here.
