### ISSUE TITLE
[HOLD for payment 2024-08-19] [Fullstory] Initializing the Onyx object to identify the user when they have an infinite session on New Dot

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#46677]
**Problem**: 
Initializing the Onyx object on `SignInWithShortLivedAuthToken` will make it so a user on Classic with an infinite session, on redirect to New Dot will now be identified in FS. But if they were already on New Dot, and had an infinite session, we will not identify them till they explicitly login next.

**Solution**:
Initialize this object on OpenApp/Reopen App as well.

Note: While we do this, can we also make it so the Onyx object includes the `tryNewDot.classicRedirect.dismissed` 
If that is `true` - send `true`, if `false` then send `false`
If that NVP does not exist, send `empty`

**Comment by danieldoglas** [comment]
This is done, there's no payment to be made
