### ISSUE TITLE
[HOLD for payment 2024-08-13] [Search v2.1] Use new query syntax in App

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46684]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.888saqncimmk) of the design doc.

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by luacmartins** [comment]
PR is merged

**Comment by luacmartins** [comment]
PR was merged

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: n/a internal 
 - Contributor+: @rayane-djouah $250 via Upwork -- offer extended, please accept when you get a second! https://www.upwork.com/nx/wm/client/contracts?contractStatus=pending&contactPerson=36910897
 
 Upwork job is here: https://www.upwork.com/ab/applicants/1823504324434878915/job-details

**Comment by stephanieelliott** [comment]
Thanks @rayane-djouah, all paid!
