### ISSUE TITLE
[Awaiting Payment 2nd Sept] [Workspace Feeds] [$250] Spanish - "Hidden" is not translated to Spanish when going to card details in WS menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46709]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
PreCond: App is in Spanish
1. Access New Expensify app
2. Sign into a valid account (Beta Enabled)
3. Go to a WS > Members > Invite a beta member
4. Click on Member name > Click on Assigned Cards section > Observe the CardHolder section

## Expected Result:
User expects "Hidden" to be translated to Spanish

## Actual Result:
Hidden shows in English, although the app is in Spanish

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/edec20b9-93db-4fad-a1d2-81e0ffe63abd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dce39aec75aaa4cf</li>
        <li>Upwork Job ID: 1820464850160123531</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 103492615</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
@getusha is there a proposal here that will work?

**Comment by getusha** [comment]
>@getusha What do you think about https://github.com/Expensify/App/issues/46709#issuecomment-2269246743

I think it’s better to avoid initiating a new Onyx connection just for this, if we have a simpler solution.

@Krishna2323 @daledah, how did you manage to assign the cards? Could you please share the steps, if possible?

**Comment by getusha** [comment]
@Krishna2323I don't think we have the correct root cause in your proposal. The translation was moved outside the function for performance reasons. https://github.com/expensify/app/commit/5ec39eb2117584f611031e1c8f659c5d6b447d3d

The root cause is that the default locale is being used because the function is called before the selected locale is updated in BaseLocaleListener.

https://github.com/Expensify/App/blob/93dc1c91437ea8cb9bd48a2a65f395e6da3c678b/src/libs/Localize/LocaleListener/BaseLocaleListener.ts#L7

**Comment by getusha** [comment]
We don't want to trigger the translate function every time `getDisplayNameOrDefault` gets called.

**Comment by mountiny** [comment]
@getusha Sorry for the trouble but as this is part of the workspace feeds project, I think @allgandalf or @DylanDylann should handle this one as C+

Who can take it?

**Comment by DylanDylann** [comment]
@mountiny I can take it as C+

**Comment by DylanDylann** [comment]
We don't want to trigger the translate function every time `getDisplayNameOrDefault` gets called.

@daledah's [proposal](https://github.com/Expensify/App/issues/46709#issuecomment-2269246743) LGTM

 🎀👀🎀 C+ reviewed

**Comment by mountiny** [comment]
@techievivek I can handle this one since this is part of the workspace feeds project

**Comment by slafortune** [comment]
This is being worked on, it will have a 7-day regression period, so I don't feel the need to add another BZ person to this.
I'll be out until 8/21 and will check in on this then.

**Comment by slafortune** [comment]
Deployed to staging, not production yet

**Comment by trjExpensify** [comment]
Hit prod 2 days ago, updating labels and titles.

**Comment by slafortune** [comment]
Not overdue - `Awaiting Payment` Sept 2

**Comment by slafortune** [comment]
@daledah please accept the invite to this job - https://www.upwork.com/ab/applicants/1820464850160123531/pending

**Comment by DylanDylann** [comment]
No need checklist. This belong to workspace feed project

**Comment by slafortune** [comment]
@DylanDylann [Paid](https://www.upwork.com/nx/wm/workroom/38120158/overview) ✅

**Comment by slafortune** [comment]
bump @daledah - please accept the invite so we can get this paid out 👍

**Comment by slafortune** [comment]
@daledah I want to pay you 👍

**Comment by DylanDylann** [comment]
@slafortune Ops, this bug is in the Workspace Feed Project. So I think I am not eligible for payment here. I already made a refund request on Upwork. So sorry about my mistake before

cc @mountiny

**Comment by DylanDylann** [comment]
@slafortune This bug is in the Workspace Feed Project. So I am not eligible for payment here. I already made a refund on Upwork for the mistakenly paid amount.

We only need to pay for @daledah

cc @mountiny

**Comment by slafortune** [comment]
@daledah I can redo this - but it was done for that same profile - 
<img width="1545" alt="image" src="https://github.com/user-attachments/assets/61459ed8-a63f-4087-8b04-bfb926a4e21a">

**Comment by slafortune** [comment]
Resent - https://www.upwork.com/nx/wm/offer/103898558

**Comment by slafortune** [comment]
Paid!
