### ISSUE TITLE
mWeb - Category - Auto category displayed on entering incorrect merchant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46712]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
Pre-condition : 1.In old dot, as employee set expense rule for category. If (0)zero merchant, set select rent category.
In new dot in employee WS chat, create an expense with same merchant and verify auto category is assigned.
1. Go to https://staging.new.expensify.com/
2. Login as employee
3. Tap in employee Workspace chat
4. Create an expense with merchant entered as 5 and without any category selected

## Expected Result:
Auto category must not be displayed on entering incorrect merchant

## Actual Result:
Auto category displayed on entering incorrect merchant

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/180f20ef-5790-4259-9f56-9dca3eeabb97

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
I think it would be better to use tests that are more realistic for cases like this. There's very little chance a customer is going to have a merchant called `0`, but rather the name of an actual merchant like "Home depot", "Uber" "TRJ's Bagel Factory" etc. 

Either way, I can't reproduce it. I suspect they might have implicit categorisation in play where this particular account has coded the merchant in that way before. I would suggest trying on a new account or something. 

https://github.com/user-attachments/assets/e7fd0f6d-bfdb-43b5-aa23-9580fb48d74b

**Comment by trjExpensify** [comment]
Awaiting the retest.

**Comment by izarutskaya** [comment]
Tester was able to reproduce the issue

https://github.com/user-attachments/assets/93c72ee3-544c-4f02-a554-38b388950c5c

**Comment by trjExpensify** [comment]
@izarutskaya did they use a new account for this re-test to rule out implicit categorisation on an existing account? 

>Either way, I can't reproduce it. I suspect they might have implicit categorisation in play where this particular account has coded the merchant in that way before. I would suggest trying on a new account or something.

**Comment by trjExpensify** [comment]
@izarutskaya bump on the above for the retest. :)
