### ISSUE TITLE
[HOLD for payment 2024-08-14] Hermes Debugger on iOS doesn't work

### ISSUE THREAD

**Issue by Szymon20000** [Expensify/App#46719]
Using iOS Hermes Debugger is currently not possible :(

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
- Build debug version of the iOS app
- go to chrome://inspect

## Expected Result:
Js runtimes are visible and I can start inspecting

## Actual Result:
Js runtimes are not visible

## Workaround:
:(

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by arosiclair** [comment]
This was reviewed by me and wasn't a regression so we should be all set here
