### ISSUE TITLE
Track expense -Self DM turns to skeleton loading with RBR on LHN when submitting track expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46718]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/45752
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Go to + > Track expense > Scan.
4. Submit a track scan expense.

## Expected Result:
User is able to submit a track scan expense without issue.

## Actual Result:
Self DM turns to skeleton loading with RBR on LHN when submitting track expense.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f06566a1-9d72-4081-a85d-088c79df1cc8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by cristipaval** [comment]
[This one](https://github.com/Expensify/App/pull/45752) seems to be the offending PR
