### ISSUE TITLE
[HOLD for payment 2024-08-19] [Search v2.1] - Sorting on Drafts and Finished does not work at all

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46720]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+khcategory15@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account has lots of expenses in Drafts and Finished section (Search)
1. Go to staging.new.expensify.com
2. Go to Search
3. Go to Drafts
4. Apply Date, Merchant and Amount sorting
5. Repeat Step 3 and 4 with Finished section

## Expected Result:
The expenses will be sorted accordingly

## Actual Result:
The sorting on Drafts and Finished does not work at all

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6d5ae72e-7521-4bb2-8340-4925154392f7

https://github.com/user-attachments/assets/05634d25-c758-466a-b53c-53a0836d35fc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
Seems to happen on production build on local, so maybe backend or a previous regression that wasn't caught. Asking the folks working on search to have a look

**Comment by dangrous** [comment]
I'm continuing to look into it but haven't found a fix yet. @iwiznia it looks like you worked on some of the syntax - any ideas? I've confirmed that the asc/desc exists correctly as ORDER BY in the query that's run [here](https://github.com/Expensify/Auth/blob/beb5fa436b7f5fb7917751bf4ef2fecbb3452b95/auth/command/Search.cpp#L81) (e.g. ORDER BY toUser asc LIMIT 51) and that the data returned, at least by [this point](https://github.com/Expensify/Auth/blob/beb5fa436b7f5fb7917751bf4ef2fecbb3452b95/auth/command/Search.cpp#L86) is no different, no matter the sort order that was sent. So, need to figure out why that's not changing anything...

The search gets wacky results on prod, so although clicking the columns does CHANGE the sort, it's still wrong, so I'm not sure this is enough of an issue to block deploy... but open to other opinions

**Comment by dangrous** [comment]
Running queries directly in SQL DOES result in differently ordered results... so the issue has to be in `Search::buildTransactionResponse()`

**Comment by dangrous** [comment]
Removing blocker label since prod is already weird, and this is no worse.

**Comment by luacmartins** [comment]
The only filter that supports sorting is `Expenses`. The issue here is that we're allowing the column header to be clicked ofr the other filters. We should disable that.

**Comment by Kicu** [comment]
@luacmartins I can fix this, since I broke this, by removing the mechanism of disabling sorting for other filters than `Expense`.
Sorry about that, when I was migrating us to new search syntax using AST I assumed that "everything works with everything" and sorting is no longer an issue.

Expect a PR with fix soon

**Comment by luacmartins** [comment]
No worries! Thank you for working on this.

**Comment by Kicu** [comment]
@luacmartins actually I need to confirm one thing. In the past it was not that we only allowed `Expenses` as type, but that we only allowed `ALL` status to be sorted.

Is that still true? Because what we call on the LHN `Expenses` is in reality `type:expense status:all`. So is this the only thing that is sortable now?

**Comment by luacmartins** [comment]
Correct! Type expenses and status all is the only sortable one for now

**Comment by Kicu** [comment]
👉 https://github.com/Expensify/App/pull/46804
This PR should fix all that is wrong with sorting on search right now.

In future backend should implement sorting by other statuses, for now it is disabled in UI like it used to be.

**Comment by dangrous** [comment]
ooh okay thanks all for figuring this out. That makes sense as the issue

**Comment by iwiznia** [comment]
So is this solved or not? I think not solved, right?

I just realized that our results are objects and objects have no order really, so we have a hole in our design, no? We need to somehow include the order in the data we pass, for example by adding a new property to each object `index` and then using that index to determine the order to use?

**Comment by luacmartins** [comment]
We sort the search results in the front end as well, but that sorting logic only works for type:expense status:all filter, mostly because of UI/UX considerations for the other filters. This will be solved once we merge @Kicu PR

**Comment by iwiznia** [comment]
Oh, is that what we want? To sort in the frontend?

**Comment by luacmartins** [comment]
Right now we also sort in the frontend. I suppose we could do that entirely on the backend and send an `index` key like you suggested. That'd eliminate the need to have any sorting logic in the frontend. What do you think of that solution @Kicu?

**Comment by luacmartins** [comment]
Yea, that makes sense to me. I don't think this is a priority now though given that the functionality works. I'll add this to the list of follow ups [here](https://github.com/Expensify/App/issues/45293)

**Comment by ikevin127** [comment]
@luacmartins When you get a chance, mind adding the `Bug` label to assign a BZ team member for payment ? Appreciate it!

**Comment by sonialiap** [comment]
Payment summary:
- @ikevin127 $250 - offer sent in [upwork](https://www.upwork.com/ab/applicants/1824418110167023757/hired)

**Comment by sonialiap** [comment]
@strepanier03 I'm OOO Aug 19-30, adding leave buddy. 
Status: if no regressions popup, please complete payment on the 19th. [Payment summary](https://github.com/Expensify/App/issues/46720#issuecomment-2293392730)

**Comment by ikevin127** [comment]
cc @strepanier03
