### ISSUE TITLE
[HELP WANTED] Task - Reply count not updated when task is assigned and deleted in thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46729]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat and write a message
2. In the thread, click the plus sign and assign a task
3. Add a title, assignee, and confirm
4. Exit the thread and observe the updated reply count
5. Re-enter the thread, click on the task header, and delete the task
6. Exit the thread and notice the reply count is not updated

## Expected Result:
The reply count should update when a task is deleted in the thread

## Actual Result:
Reply count is not updated when a task is deleted in the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fb16b326-15e1-464e-9f24-8dcd8375c661

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
BE

**Comment by strepanier03** [comment]
I'm able to repro this following the instructions. Even if you delete the comment you threaded from, the reply count doesn't update so I'll let this go forward and see if eng wants to pick it up.

**Comment by strepanier03** [comment]
Setting to weekly until this get prioritized.

**Comment by strepanier03** [comment]
Hasn't been picked up yet.

**Comment by strepanier03** [comment]
Waiting for prioritization and ownership.

**Comment by strepanier03** [comment]
Seeing as the project for this is closed and on-hold, I'm thinking this will not be prioritized anytime soon.

**Comment by strepanier03** [comment]
Actually updated the project and set back to Weekly just to see if that will get it picked up.

**Comment by strepanier03** [comment]
Low status, so good for now.

**Comment by strepanier03** [comment]
We are deprioritizing Task bugs unless they impact onboarding, this does not.
