### ISSUE TITLE
[$250] Bank account - Avatar icon for the owner is not legible in dark mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46737]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- App is in dark mode
1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows
3. Click Connect to bank account
4. Proceed to bank account set up
5. On Part 4, select Yes on the first step "Do you own 25% or more of Alberta Bobbeth Charleson?'
6. Select Yes on the next step "Do any individuals own 25% or more of Alberta Bobbeth Charleson?"
7. Enter all the required information (name, DOB, SSN and address)
8. Click Confirm on the confirmation page
9. Select No on the next step

## Expected Result:
The avatar icon for the owner should be legible in dark mode

## Actual Result:
The avatar icon for the owner is not legible in dark mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7a8f49e9-b3c8-421a-8e40-9921712a3dcc

<img width="1440" alt="12 44" src="https://github.com/user-attachments/assets/2233e141-266f-4c5c-96a8-04b52d5023cb">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1b46ddf957e4ce7</li>
        <li>Upwork Job ID: 1820455770779219098</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 103407542</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by greg-schroeder** [comment]
PR is on staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Oops - automation failed and this was deployed to prod on 8/15 or 8/16 I think. With that said, I'll work on processing payments now.

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @nyomanjyotisa - $250 - Paid via Upwork
C+: @mollfpr - $250 - You can make a manual request via ND

**Comment by JmillsExpensify** [comment]
$250 approved for @mollfpr
