### ISSUE TITLE
[$250] Bank account - Date of birth page is not full screen if keyboard is not previously dismissed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46745]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4806926
**Email or phone of affected tester (no customers):** applausetester+vd_ios080224.2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must have created a workspace and have enabled Workflows
1. Open New Expensify app
2. Go to Settings > Workspaces > Workspace > Workflows
3. Tap on "Connect bank account"
4. Select "Connect manually"
5. Enter testing routing number and account number
6. Enter first name
7. Enter last name, but do not dismiss the keyboard
8. Tap on "Next" button

## Expected Result:
Date of birth page should be displayed in full screen

## Actual Result:
Date of birth page is not displayed on full screen. If the user goes back, all of the app screens are not displayed on full screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/709f96a1-fe01-4a77-bc77-0905a8a2279d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01808a7973a2a6bf8a</li>
        <li>Upwork Job ID: 1819450520815861387</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103375078</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by lanitochka17** [comment]
@Beamanator  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Beamanator** [comment]
This could also be related to https://github.com/Expensify/App/pull/46513 maybe 🤔

**Comment by Beamanator** [comment]
Amazing, mind checking if https://github.com/Expensify/App/issues/46744 is fixed too @ishpaul777 ? 🙏

**Comment by Beamanator** [comment]
@lanitochka17 ooh that sounds veryyyyy similar to https://github.com/Expensify/App/issues/46743, so the fix that is being deployed to staging should hopefully fix that too 🙏

**Comment by Beamanator** [comment]
Confirmed fixed in staging!

**Comment by kirillzyusko** [comment]
> Enter testing routing number and account number

@lanitochka17 may I ask you to give me these numbers? 😅 I need them to verify that in a new fix for https://github.com/Expensify/App/issues/44514 that issues doesn't happen anymore 🙈

**Comment by kirillzyusko** [comment]
Thank you @ishpaul777 👍
