### ISSUE TITLE
Chat - Conversation doesn't expand to full view after completing editing a message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4807037
**Email or phone of affected tester (no customers):** gatantm+81@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch new Expensify
2. Navigate to any chat with messages
3. Tap and hold on a message you left > Tap Edit
4. Make any changes and tap on the checkmark

## Expected Result:
The edit is saved and keyboard is dismissed with the conversation expanding to the whole screen

## Actual Result:
The edit is saved and keyboard is dismissed but an empty space is left

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/34adfa21-cc67-499e-be48-2c1bd8c4648a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/0e91ea69-d9a1-4a30-af8c-5d16ce0f25a3

**Comment by Beamanator** [comment]
@ishpaul777 maybe this one too? (possibly fixed by https://github.com/Expensify/App/pull/46749)

**Comment by Beamanator** [comment]
Confirmed fixed in staging!
