### ISSUE TITLE
Search - Keyboard overlaps the conversation opened from search results/start chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46744]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gatantm+81@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch new Expensify
2. Tap on Fab > Start Chat or Search
3. Search for a user
4. Tap on the user

## Expected Result:
User is navigated to the new chat with focus on the text field which is shown correctly

## Actual Result:
User is navigated to the new chat but the keyboard is overlapping the text field and send button and can't sent any message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b7d1ff9f-958b-4c17-ba79-7b829bee2fd5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by kirillzyusko** [comment]
I can work on that issue on Monday (but if it's urgent to solve then someone else can have a look) 👀 

Potentially (though not sure absolutely) this issue can be introduced by these changes: https://github.com/Expensify/App/pull/46513

**Comment by Beamanator** [comment]
If a revert PR can quickly fix the 2 open blockers, let's go for it

**Comment by Beamanator** [comment]
Quick fixed by reverting https://github.com/Expensify/App/pull/46749

**Comment by Beamanator** [comment]
Confirmed fixed in staging!
