### ISSUE TITLE
[$250] Search Filter Page - Filters are not entirely translated to Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Users app is in Spanish
1. Access [www.new.expensify.com](http://www.new.expensify.com/)
2. Sign into a valid account
3. access https://staging.new.expensify.com/search/filters

## Expected Result:
User expects all aspects of the app to be in Spanish

## Actual Result:
When navigating the "Status" tab and selecting a filter, it is not translated & also the categories are not translated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/072743e3-c840-415d-8f72-8459c2ad5dc0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e25e377d12fcc63f</li>
        <li>Upwork Job ID: 1820419945098444427</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
Should be an easy one.

**Comment by twisterdotcom** [comment]
@luacmartins is this one fine being External?

**Comment by luacmartins** [comment]
We'll remove the type/status filter soon, since those are available via the LHN/Status bar, so no change needs to be made there. As for the categories, I'm not sure that we translate those since those are not translated on the workspace page either. So I think we can just close this issue.

**Comment by luacmartins** [comment]
Gonna close as per the comment above.
