### ISSUE TITLE
[$250] Android - Expensify - In expensify chat, #admins text is hyperlinked to production site

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46769]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Login with new account
3. Tap expensify switcher
4. Tap plus icon and create a workspace
5. Open workspace chat
6. Create an expense
7. Navigate to LHN
8. Tap on expensify chat
9. Long press on #admins link
10. Note the copy to clipboard link

## Expected Result:
In Expensify chat, #admins text must be hyperlinked to staging site

## Actual Result:
In Expensify chat, #admins text is hyperlinked to production site instead of staging site

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b3423ae0-a557-4ca1-893d-52bcd34440bc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1e67c9364a6c91d</li>
        <li>Upwork Job ID: 1820607258519307630</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by VictoriaExpensify** [comment]
Thanks for the input @parasharrajat. Yeah you are right, this is a tricky one - I didn't quite pick up on the nuances of the issue. Since this is complex and it doesn't have an effect on our customers (since this is staging related), I don't think we should put in the effort here. I'm going to close this one out
