### ISSUE TITLE
IOU - GBR with unpaid IOU is not displayed in LHN when logging in to the account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46765]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4808254
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
Send from user A - 2 IOU to user B
1. Open New Expensify app
2. Log in with user account B
3. Note the conversation with user A at LHN

## Expected Result:
GBR should be displayed in LHN when logging into an account where there is an unpaid IOU

## Actual Result:
GBR with unpaid IOU is not displayed in LHN when logging in to the account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4f1df0f0-8008-4bbd-b59d-031946e20d03

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by jliexpensify** [comment]
VSB is de-prioritised, closing ([example here](https://expensify.slack.com/archives/C066HJM2CAZ/p1721684527960509?thread_ts=1721683272.509669&cid=C066HJM2CAZ))
