### ISSUE TITLE
[HOLD for payment 2024-08-14] [HOLD for payment 2024-08-13] [$250] Xero - Unable disconnect: a warning modal doesn't shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46764]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4807575
**Email or phone of affected tester (no customers):** rybkina+080224@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch App and login
2. Navigate to in workspace settings
3. Activate "More Features" > Accounting
4. Navigate to Accounting > connect to Xero
5. Click on the 3 dot menu next to Xero
6. Click on "Disconnect" > Click on "Disconnect" on warning moda

## Expected Result:
The warning modal should be show

## Actual Result:
Unable disconnect: a warning modal doesn't shown. Nothing happens when tap on disconnect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b1d55cef-3199-4ec5-a224-5908efdab14b

![B-1](https://github.com/user-attachments/assets/03cba978-7800-41c2-a2bf-ec77ed3be099)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171713140ff08e8e2</li>
        <li>Upwork Job ID: 1820526513599710574</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by m-natarajan** [comment]
Still reproducible 

https://github.com/user-attachments/assets/53700223-0a0f-43da-9fdb-2c1b2f3432c6

**Comment by marcaaron** [comment]
This doesn't feel like a `DeployBlocker` but could be a `DeployBlockerCash`. It's the last one - I'm trying to reproduce locally on iOS now.

**Comment by s77rt** [comment]
Regression from https://github.com/Expensify/App/pull/45762. Apparently we need to wrap the `onSelected` callback in `Modal.close`. I will raise a PR to unblock the deploy then we can rethink this (it seems we may have other cases to fix) cc @zfurtak

**Comment by marcaaron** [comment]
Removing the DeployBlocker label as it seems most definitely related to https://github.com/Expensify/App/pull/45762

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/45762
- The offending PR has been commented on: https://github.com/Expensify/App/pull/45762#issuecomment-2270193913
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by garrettmknight** [comment]
@s77rt please request payment when you're ready. Dropping to weekly in the meantime.
