### ISSUE TITLE
[Hold for #46324] Search - Draft message inside the composer disappears in expense details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46772]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** bezawitgebremichael+112211@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create an expense
3. Go to search
4. Click on an expense from the expense list
5. Write something inside the composer
6. Go back to inbox
7. Observe that the text inside the composer is visible
8. Click on chat where the expense is submitted from the LHN
9. Open the expense details page by clicking on the preview

## Expected Result:
The drafted message inside the composer should be present

## Actual Result:
The draft message inside the composer disappears and the composer gets empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8700ef79-f76e-44c1-9693-889206f60205

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
Same cause as https://github.com/Expensify/App/issues/45408 
Tagging @luacmartins

**Comment by sonialiap** [comment]
@luacmartins do you think this issue will be, or can be covered by https://github.com/Expensify/App/issues/45408?

**Comment by luacmartins** [comment]
Yea, this issue should be fixed once https://github.com/Expensify/App/pull/46324 is merged.

**Comment by sonialiap** [comment]
@twisterdotcom I'm OOO Aug 19-30, adding leave buddy. 
Status: once https://github.com/Expensify/App/pull/46324 is sorted, we'll need to retest to confirm if that PR also fixed this issue

**Comment by luacmartins** [comment]
This is fixed!
