### ISSUE TITLE
[$250] Approvers - No RBR and "View Duplicate" button after creating expenses with duplicate fields

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46770]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16.3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4807624)
**Email or phone of affected tester (no customers):**  fischer9966+080224bemp@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create admin account in with Gmail
2. Create Collect workspace, set Workflows to enabled and the admin is configured as the approved, se
3. Invite employee to Workspace
4. Login as an employee
5. Navigate to the Collect workspace chat
6. Create 2 expenses with duplicate fields - Amount, Merchant and date. Categories and Description are different.
7. Check created report

## Expected Result:
Report preview contains a RBR in the top right corner, both expenses have an RBR, both expenses have a "Duplicate" status and "Hold" status
Header has a button "Review Duplicates"

## Actual Result:
No RBR in the top right corner, both expenses have NOT an RBR, both expenses have NOT "Hold" status.
No button "Review Duplicates" in the report header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/252f12a4-9c6e-4ece-a36e-62d2ff89bee4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195e5927ee5e6ceed</li>
        <li>Upwork Job ID: 1820882470433554654</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103498936</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by DylanDylann** [comment]
I attended this interview!

**Comment by abekkala** [comment]
@rojiphil please review the updated proposal

**Comment by rojiphil** [comment]
Sorry for the delay here. I will review and provide an update by tomorrow my day.

**Comment by rojiphil** [comment]
> Get `hasWarningViolations` condition, then add it to `shouldShowRBR`. This will include duplicate violation as well.
> 
> ```js
> const hasWarningViolations = TransactionUtils.hasWarningTypeViolation(transaction?.transactionID ?? '-1', transactionViolations);
> 
> const shouldShowRBR = hasNoticeTypeViolations || hasViolations || hasFieldErrors || (!isFullySettled && !isFullyApproved && isOnHold) || hasWarningViolations;
> ```

@daledah Thanks for the proposal. Just one question. I can understand the need to correct the name to `duplicateDetection` but what specific issue are we fixing by adding `hasWarningViolations` to `shouldShowRBR`?

**Comment by rojiphil** [comment]
> Adding `hasWarningViolations` to `shouldShowRBR` should fix the bug `both expenses have NOT an RBR, both expenses have NOT "Hold" status.`, as mentioned in the issue description

The RBR and `Hold` status issue does not come up for me once we correct the permission name. Anyway, we can have a look again at this and take this up at the PR stage. 
Otherwise, @daledah [proposal](https://github.com/Expensify/App/issues/46770#issuecomment-2268596383) of correcting the permission name LGTM
🎀👀🎀 C+ reviewed

**Comment by rojiphil** [comment]
@bondydaa Would BE send across `dupeDetection` as a BETA permission? If so, this issue can be considered resolved from the BE side.

**Comment by bondydaa** [comment]
your accounts would have to be added to the `dupeDetection` beta in order for that to get returned.

**Comment by rojiphil** [comment]
@abekkala Can we please close this issue as this is a non-issue?
