### ISSUE TITLE
[HOLD for payment 2024-09-10] [$250] Onboarding tasks - Error appears when renaming onboarding tasks

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46781]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** bezawitgebremichael+1122@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new account
3. On the onboarding modal select "Manage my team's expenses"
4. Finish the onboarding flow by filling out business name and first name
5. Open expensify chat
6. Click on a task with a description. E.g "Set up categories"
7. Click on the title and rename it to something else

## Expected Result:
The title of the task changes successfully

## Actual Result:
"Task description too long" error appears and the title of the task is not renamed but a system generated message shows up noting that the task title has been changed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/bfd7d9da-db35-400c-a18f-fcd2fac8e8be

![shot_1](https://github.com/user-attachments/assets/dddd14e4-f07a-4062-973e-04dcb3fdd40a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a97f2cc7f0719d28</li>
        <li>Upwork Job ID: 1820481612178741666</li>
        <li>Last Price Increase: 2024-08-12</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103598933</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment]
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kpadmanabhan** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message displayed upon editing task title. There is also a success message displayed stating that task updated.

### What is the root cause of that problem?
Calling `EditTask` API returns code `666` with message `Task description is too long` and type `Expensify\\Libs\\Error\\ExpError`.
Front end recognizes the API response and displays the error message in the UI which is returned in the API response.
However we do not check if the error message is displayed or not and irrespective of that we display the message that `updated the task title to XXX`.

### What changes do you think we should make in order to solve the problem?
2 fixes needed here.
1. Backend to check and fix the `EditTask` API and do not return message field if processing is successful. If error, then more meaningful message to be returned.
2. In frontend, we need to correlate between processing of error response and displaying of success status. Display success only if there are no errors while processing.

### What alternative solutions did you explore? (Optional)
N.A.

**Comment by isabelastisser** [comment]
Looking.

**Comment by trjExpensify** [comment]
Are we sure we're okay with them renaming onboarding tasks, @anmurali @danielrvidal?

**Comment by mountiny** [comment]
I kinda feel like we should not allow it

**Comment by trjExpensify** [comment]
Anu and I talked about this today, and we're a little hesitant of adding custom logic for onboarding tasks. I checked the logs for the last 2 weeks and only testers have triggered this error. So, it doesn't look like any real customers are doing this in practice. That makes an argument for :do-nothing: and revisit if it becomes an actual problem. 

That said, I'm not really a fan of leaving this API error throwing errors for a problem of our own doing. It's pretty janky and detracts from a premium experience to let someone take an action that's guaranteed to fail.

If the character limit for task descriptions are set to `500` today, what's the maximum character length of one of our onboarding tasks. If `500` is too low for our own utility of tasks, it could very well be for customer usage, so let's consider raising that limit. That would, AFAIK, prevent the error from being thrown if someone does happen to ddit the task. 

@mountiny what do you think?

**Comment by trjExpensify** [comment]
Cool, so `1000` will do it then. 👍

**Comment by mountiny** [comment]
Can change that

**Comment by trjExpensify** [comment]
Nice! Lesse' do it then.

**Comment by mountiny** [comment]
@trjExpensify I got the PR here https://github.com/Expensify/Web-Expensify/pull/43142 but noting that the same limit applies to money request descriptions and workspace room descriptions. I update the limit for those too as I think it would be confusing to have different limit for task description and for the other descriptions.

If you agree with that I can mark it ready for a review and then we have to update all these limits in App too

**Comment by mountiny** [comment]
> you probably know you're not getting paid back. :P

all the poetic employees are sad now 😢

**Comment by isabelastisser** [comment]
@ZhenjaHorbach, please review the updated proposal. Thanks!

**Comment by kpadmanabhan** [comment]
[Updated proposal](https://github.com/Expensify/App/issues/46781#issuecomment-2267566876) 
As per backend increasing character limit.

Sorry forate response as I was on vacation.

@ZhenjaHorbach : please note that there are 2 changes needed in frontend as updated in my proposal. Please review if it is not too late.

**Comment by mountiny** [comment]
Gonna go with @daledah per the c+ recommendation

@daledah what is your eta for the pr?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by ZhenjaHorbach** [comment]
Looks like production deploy automation failed: This should be on [HOLD for Payment 2024-09-06] according to [prod deploy checklist](https://github.com/Expensify/App/issues/48035), confirmed in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q.)

**Comment by ZhenjaHorbach** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@ZhenjaHorbach] The PR that introduced the bug has been identified. Link to the PR:

It's more like a new feature

> * [x]  [ @ZhenjaHorbach] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

NA

> * [x]  [@ZhenjaHorbach] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

NA

> * [x]  [@ZhenjaHorbach] Determine if we should create a regression test for this bug.
> * [x]  [@ZhenjaHorbach] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

- Login with a new account
- On onboarding modal, select "Manage my team's expenses"
- Finish the onboarding flow
- Open expensify chat
- Click on a task with a description. E.g "Set up categories"
- Rename task
- Verify that task is renamed, no error appears

Do we agree 👍 or 👎

**Comment by mountiny** [comment]
I think we can add this test as non-critical

**Comment by isabelastisser** [comment]
@daledah, what is your Upwork profile? Can you please apply for this job there?


https://www.upwork.com/jobs/~01a97f2cc7f0719d28

**Comment by isabelastisser** [comment]
Payment summary:

@ZhenjaHorbach, $250 for C+ review. Paid in Upwork.
@daledah, $250 for the Contributor proposal. Payment pending in Upwork.

**Comment by isabelastisser** [comment]
Bump @daledah so I can process the payment in Upwork. Thanks!

**Comment by isabelastisser** [comment]
@daledah, thanks! I sent you the offer in Upwork now.

all set!
