### ISSUE TITLE
Message action- Different content pasted when copying using three dots and right click

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** Negasofonias@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to a message with a hyperlink embedded message or send one e.g [Sofonias](staging.new.expensify.com)
2. Copy the message by right clicking on the message and selecting copy to clipboard
3. Paste the message in the composer box using ctrl+Shift+V and observe that the hyper link is pasted
4. Now copy the message clicking in the three dots while hovering over the message and select copy
5. Paste the message in the composer box using ctrl+Shift+V and observe the hyperlink is pasted as a plain text with out the link

## Expected Result:
Box pasted content should be the same and plain text

## Actual Result:
Pasted content are different

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fd47e31d-4be8-4197-9a16-436fe44c7cf4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by stephanieelliott** [comment]
Yeah I agree, this is expected behavior! Gonna close.
