### ISSUE TITLE
[HOLD for payment 2024-09-09] [$250] Workflows - Delay submissions option is not grayed when clicking offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46783]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Click on account setting
3. Click Workspace and create a new one
4. Click More features and click workflows
5. Go offline and navigate on the workflows page
6. Turn off or on the add approvals and payments option and observe that they are grayed
7. Turn off or on the delayed submission option and observe that it is not grayed

## Expected Result:
Delay submissions option and submission frequency options must be greyed when clicking offline

## Actual Result:
Delay submissions option and submission frequency options are not greyed when clicking offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3d6ba9d6-6608-450e-bdc0-28cfc6a91048

<img width="822" alt="=11_sc" src="https://github.com/user-attachments/assets/6b3f3b15-8883-47c8-b025-12f113eaa0bd">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01573ccab630d178e7</li>
        <li>Upwork Job ID: 1820455952702489901</li>
        <li>Last Price Increase: 2024-08-05</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 103452790</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment]
I believe considering the `autoReportingFrequency` of pendingFields is enough to decide as that only we are updating for the optimistic data. With that, I am fine moving with the @abzokhattab's proposal.

> 2. Even using autoReportingFrequency, we still face with this issue when users toggle workflow in More features since we just set autoReporting pendingField when enabled is false. So in case users enable workflow offline, it doesn't show the greyed option

@daledah Could you plz check and update as I think we won't face this issue if we consider `autoReportingFrequency`.

**Comment by Pujan92** [comment]
Thanks @daledah but I would consider it as an add-on to the current issue. I think we can move forward with @abzokhattab's proposal but would request an internal engineer to confirm by giving a glimpse to both proposals once.

🎀👀🎀 C+ reviewed

**Comment by marcochavezf** [comment]
Thanks @Pujan92 for the review, and I agree with your decision. In this case the solution required is simple and both proposals will be enough to fix the problem, let's go with the first one

**Comment by greg-schroeder** [comment]
How's the PR coming @abzokhattab ?

**Comment by greg-schroeder** [comment]
This was just deployed to prod 6 hours - will make sure automation kicks in, otherwise this is in a the regression period until 9/3 (9/2 is a holiday)

**Comment by greg-schroeder** [comment]
Seems that didn't work, so will process this payment today

**Comment by greg-schroeder** [comment]
@abzokhattab paid

@Pujan92 sent you an offer given one wasn't generated automatically - I'll pay you ASAP as soon as you accept.

**Comment by Pujan92** [comment]
@greg-schroeder Can you plz cancel that offer and write payment summary, so I can request payment on NewDot.

**Comment by greg-schroeder** [comment]
Ah,

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @abzokhattab - $250 - Paid via Upwork
C+: @Pujan92 - $250 - You can make a ND manual request

**Comment by garrettmknight** [comment]
$250 approved for @Pujan92
