### ISSUE TITLE
[$250] AU-With a participant sets zero amount creating split expense displays error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46802]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4815729
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a group chat with few members
3. Tap plus icon -- split expense
4. Enter an amount and tap next
5. Replace the amount to zero for first participant
6. Tap split expense

## Expected Result:
After entering zero as amount for first participant and tapping split must show error. If not, error must not be shown after creating split expense also.

## Actual Result:
After entering zero as amount for first participant and tapping split no error is displayed. But unexpected error is shown after creating split expense also.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4b68e895-ff3c-47fe-8478-132842df284c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01329020483b531ccb</li>
        <li>Upwork Job ID: 1823118569609242552</li>
        <li>Last Price Increase: 2024-08-12</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103591335</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-split

**Comment by alexpensify** [comment]
It's still on my testing list; I'll get to it soon.

**Comment by alexpensify** [comment]
@jayeshmangwani - can you please review the proposals and identify if one will fix this issue? Thanks!

**Comment by jayeshmangwani** [comment]
Thanks for the proposal, If we decide to show an error message when a logged-in user sets their own split amount to 0, we can proceed with @Krishna2323 's [Proposal](https://github.com/Expensify/App/issues/46802#issuecomment-2268783519). 

Sidenote: We'll need the error message copies to display that the split amount cannot be set to 0 for oneself.

🎀 👀 🎀 C+ reviewed

**Comment by jayeshmangwani** [comment]
> The error message above Split expense button should be shown only when users press on it

IMO, the error should appear above the form button, not when the user presses it. Instead, the error should trigger when the user changes the amount to 0. 
Also, @srikarparsi what's your take on the behavior when the split amount is set to 0 for oneself? 
<img width="377" alt="Screenshot 2024-08-14 at 14 41 50" src="https://github.com/user-attachments/assets/fb0dda1c-13b4-44ab-96b5-87d223e79245">

**Comment by jayeshmangwani** [comment]
@srikarparsi Whenever you can, please check this comments https://github.com/Expensify/App/issues/46802#issuecomment-2288262240 and https://github.com/Expensify/App/issues/46802#issuecomment-2285950860

**Comment by srikarparsi** [comment]
Yes, I agree with what you've said @jayeshmangwani, sorry for the delay. In the future we will want to allow for setting your own split to 0 but that is de-prioritized so this frontend fix will be good in the meanwhile to avoid this bug. Internal discussion [here](https://expensify.slack.com/archives/C03U7DCU4/p1724090208974289)

The error should appear above the Split Expense button as it does for other errors.
The error should appear immediately after the user enters their own split amount as 0 (should not wait for the user to press the split expense button).

@Krishna2323's proposal looks good to me. @alexpensify, do you think you could help with getting the english and spanish copies for the error text? Something on the lines of "Split amount for yourself must be greater than 0"

**Comment by alexpensify** [comment]
## Next Steps

This PR is going through the review process. @VictoriaExpensify I reassigned the `Bug` label because @Krishna2323 needs help getting the translations (https://github.com/Expensify/App/pull/47886#issuecomment-2307448608) for this update. Can you please help move this GH along while I'm OOO? Thanks! 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by jayeshmangwani** [comment]
> needs help getting the translations (https://github.com/Expensify/App/pull/47886#issuecomment-2307448608) for this update

@VictoriaExpensify Can you please help getting the translations ?

**Comment by jayeshmangwani** [comment]
@Krishna2323 I've opened the thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1725005817303279)

**Comment by jayeshmangwani** [comment]
@Krishna2323 Since you don't have access to Slack, here's an update: We have the English copy, `Please enter a non-zero amount for your split.`, Srikar is working on getting us the Spanish copy.

**Comment by jayeshmangwani** [comment]
@Krishna2323 There's no update on the slack thread.

**Comment by jayeshmangwani** [comment]
@srikarparsi  should I use [this GPT](https://chatgpt.com/g/g-tAon5M5jH-english-to-spanish-translator/) to get the Spanish copy and then post it on Slack for confirmation from someone on the team?

**Comment by srikarparsi** [comment]
Hey! Sorry for the delay, I asked internally in Slack and just waiting on a response. I'll update once I hear back.

**Comment by srikarparsi** [comment]
Hey, here's the spanish translation:

> Por favor, introduce una cantidad diferente de cero para tu parte.

**Comment by alexpensify** [comment]
Thanks, @VictoriaExpensify, for your help! I'm back online and taking this GH back.

**Comment by jayeshmangwani** [comment]
> Hey, here's the spanish translation:

Thanks for the translations! 

@Krishna2323 We now have the Spanish version as well. Please update it.

**Comment by jayeshmangwani** [comment]
@alexpensify The PR was merged yesterday. I think we should remove the daily tag and replace it with a weekly tag.

**Comment by alexpensify** [comment]
Thanks for the update-- I've manually updated this GH since automation didn't kick in.

**Comment by alexpensify** [comment]
Payouts due: 2024-09-11 

- [ ] Contributor: $250 @Krishna2323
- [ ] Contributor+: $250 @jayeshmangwani 

Upwork job is [here](https://www.upwork.com/jobs/~01329020483b531ccb).

**Comment by alexpensify** [comment]
Closing - I completed the payment process in Upwork for @Krishna2323. @jayeshmangwani please submit a request in Chat. Thanks!

**Comment by jayeshmangwani** [comment]
Requested on ND as per https://github.com/Expensify/App/issues/46802#issuecomment-2344815319

**Comment by garrettmknight** [comment]
$250 approved for @jayeshmangwani
