### ISSUE TITLE
Thread-In #applause.expensifail.com, some thread reply shows fallback avatar

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46801]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on #applause.expensifail.com
3. Scroll the page and look for thread replies with fallback avatar
4. Open the thread reply
5. Tap sub header link and navigate back to conversation
6. Now note the thread reply avatar

## Expected Result:
In #applause.expensifail.com, all thread reply must show correct avatar.

## Actual Result:
In #applause.expensifail.com, some thread reply shows fallback avatar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d9f7b6eb-d453-4edb-8396-8e5a2aa05a47

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by JmillsExpensify** [comment]
We're not prioritizing vip-vsb bugs so I'm closing this one.
