### ISSUE TITLE
[$250] Group - App crash when removing a member on the process splitting expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46805]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.16-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. As User A Create a group chat with User B While viewing both accounts
2. go to user B > navigate to the group chat created
3. Click on the + button on the composer box > Split Expense
4. Enter amount > Click next. Don't finish the flow
5. As User A,While User B is the confirmation page, remove user B from the group.

## Expected Result:
Error is shown

## Actual Result:
App Crash

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d950437c-dbd0-44bd-9b6c-42531415d657

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d4e761b19949e81</li>
        <li>Upwork Job ID: 1820614678720926546</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103413818</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by roryabraham** [comment]
@daledah as @ishpaul777 pointed out, your proposal would not work in cases when there is an underscore in the collection key base, such as for the `POLICY_RECENTLY_USED_TAGS` key: https://github.com/Expensify/App/blob/edb81c1df2b31103aa13a13394be88bf9ec0068b/src/ONYXKEYS.ts#L410

**Comment by roryabraham** [comment]
I think more simply we should just audit all uses of `useOnyx` with the policy collection key and do something like this:

https://github.com/Expensify/App/blob/a680ecc261cc8f6846172f2c93e75ff7f2e26d2b/src/pages/home/report/ReportActionItemContentCreated.tsx#L55

Maybe we can create a utility hook like `usePolicy` that handles that policyID-defaulting logic.

**Comment by marcaaron** [comment]
Gonna demote this one since it's kind of an edge case. Sounds like @ishpaul777 is on the right track though.

**Comment by cristipaval** [comment]
I assigned @ishpaul777 as the C+ since he has context on this.

**Comment by roryabraham** [comment]
Only thing is that we might want to use `|| '-1'` rather than `?? '-1'` in case policyID is an empty string

**Comment by roryabraham** [comment]
confirmed, this has been on prod for more than a week

**Comment by RachCHopkins** [comment]
Sorry @daledah did you apply for the upwork job per [this comment](https://github.com/Expensify/App/issues/46805#issuecomment-2272216356)? I do see one shortlisted proposal but I'm not 100% sure it's you.

**Comment by RachCHopkins** [comment]
Ok, no it's not, I found your upwork profile and that is not you. I will set up the job again and send you another offer @daledah 

@ishpaul777 forgive me if this is a silly question - did you get paid for [this offer](https://www.upwork.com/nx/wm/offer/103413818)?

**Comment by RachCHopkins** [comment]
What I mean is, did you get paid money for it @ishpaul777 ?

**Comment by RachCHopkins** [comment]
Thanks for confirmation @ishpaul777 - I was looking at totally the wrong page! I've paid that out. 

@daledah I'm just waiting on you to accept the proposal (and two others) so I can pay you.

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @daledah _to be_ paid $250 via Upwork
- Contributor+: @ishpaul777  paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~013d4e761b19949e81)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
