### ISSUE TITLE
[HybridApp] Users stuck at white screen during app open

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#46815]
Hybrid app is unresponsive for HybridApp users set to the NewDot experience.

Internal users are locked or held on a white screen when opening the app or signing in. This seems to occur for users set to the NewDot experience. Two methods of reproduction are listed below. Method A seems to be occasionally reproducable for users immediately after switching experiences, wheras method B seems to be easy to reproduce for large accounts or on bad connections.

> There are two API commands that fail: [https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=%22Error%20processi[…]024-07-25T00%3A00%20TO%202024-08-02T23%3A59%5D](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=%22Error%20processing%20command%22%20AND%20email%3A%22andrewgable%2Bwhite4%40gmail.com%22%20AND%20timestamp%3A%5B2024-07-25T00%3A00%20TO%202024-08-02T23%3A59%5D)

> I think this causes us to force a logout and see the white screen. it seems like a race condition of some sorts, and I do agree that it seems to be happening because of a redirect issue. I think we should make an issue and dive deeper into it while doing the rollout

___

**Version Number:** v9.0.13.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1722805554897749?thread_ts=1722276993.634759&cid=C036QM0SLJK

## Action Performed:

**Method A**
- Install the Hybrid app, version `9.0.13.4`
- Open app not logged in
- Authenticate with an Expensify account via magic code
- Redirected to NewDot experience
- Switched back to Expensify classic from NewDot settings
- Signed out of OldDot experience
- Tried to create new account

**Method B -- not 100% reproducable**
- Have the app set to NewDot experience
- Open the app
- It often hangs
- Sometimes after a long time you land in the app

## Workaround:
Users without redirection (non-internal users) shouldn't be affected. Switch to OldDot experience to resolve

None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot_20240801-162957](https://github.com/user-attachments/assets/1c86838f-25bd-4e38-b629-b825ea37a14f)

**Method A:** 

https://drive.google.com/file/d/141Ob-O4f1iGaikI6cAJPOQ8nx1_z92Th/view

**Method B:** 

https://github.com/user-attachments/assets/2d5b6a0d-9469-4cd3-944c-aeef995a252b

**Comment by Julesssss** [comment]
@trjExpensify, please prioritise accordingly. Prior to release we didn't hold on this issue, and it should still be isolated to users set to the NewDot experience, but now that it is occurring on app open we may need to rethink.

**Comment by trjExpensify** [comment]
Yes, we should get to the bottom of this one before we flip the switch for new sign-ups. Who's taking the investigation on the HybridApp team?

**Comment by staszekscp** [comment]
Hey! I'll investigate what's going on here!

**Comment by staszekscp** [comment]
Ok, I have an update number 1 😄 

It seems that the main problem is the `API.GetShortLivedAuthToken()` command failing while being offline. Because of that we are not able to open NewDot. We just catch an exception, and display an error snackbar. Instead, I think we should call `yaplOpenNewApp` there with a different url. This way, we could indicate that we enter the app after an exception. However, we will have to cover well all problematic edge cases (like network problems after switching accounts).

Right now I consider creating a new native method, that would return only email of the current user logged in OldDot. This way we could compare the emails, and if they match, we would let the user into NewDot. Otherwise, we could eg. open OldDot sign in page, or display some Error page in NewDot to "try again later".

**Comment by staszekscp** [comment]
I'm back with update number 2 😄 

I've managed to fix iOS, but I still need to do Android and some testing in order to find some loopholes, so far it doesn't look so bad:

https://github.com/user-attachments/assets/2d7970eb-6cd9-4182-b48f-c7d69b8568df

**Comment by AndrewGable** [comment]
I think I heard @war-in and @mateuuszzzzz are working on this one, can you both comment here so I can assign you both? Thanks!

**Comment by mateuuszzzzz** [comment]
👍

**Comment by war-in** [comment]
👋

**Comment by mallenexpensify** [comment]
Is @ntdiary due compensation for their review on the below PR?
- https://github.com/Expensify/App/pull/48007

**Comment by Julesssss** [comment]
Hi @mallenexpensify, yes that's correct. Please help us to pay @ntdiary for the code review and close out this issue.

**Comment by mallenexpensify** [comment]
Contributor+: @ntdiary due $125 via NewDot

I'm assuming a regression test isn't needed here cuz it's created already as part of HybridApp, comment/reopen if anyone disagrees.

**Comment by JmillsExpensify** [comment]
$125 approved for @ntdiary
