### ISSUE TITLE
Add Profiling to mobile web debug options

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#46812]
# Problem

On our mobile apps, we have the `Use profiling` option for performance profiling. We don't have this on web because profiling can be done via the JS console. However, mobile web doesn't have a JS console, so it'd be useful to be able to have some way to do profiling there. Recently, we've had an employee experiencing performance issues specifically on mobile web. 

# Solution

Add the `Use profiling` option to mobile web. 

cc @Szymon20000 

![IMG_53B5C847EEAD-1](https://github.com/user-attachments/assets/4b32d519-94cb-465b-bd14-a7a49aae5a2d)

**Comment by kirillzyusko** [comment]
Wasn't this option already added in https://github.com/Expensify/App/pull/46133? 🤔

**Comment by hannojg** [comment]
On mobile we have the 4-finger tap gesture to open that menu (implemented using RNGH), would the same work for mWeb @kirillzyusko ?

**Comment by kirillzyusko** [comment]
Thanks @hannojg ! ❤️ 

I just tested and this indeed works:

![telegram-cloud-photo-size-2-5300879088497584250-y](https://github.com/user-attachments/assets/ffc25784-54c8-4dc9-8b4e-31703268209a)

File sample:

[Profile_trace_for_9.0.17-0.cpuprofile](https://github.com/user-attachments/files/16511769/Profile_trace_for_9.0.17-0.cpuprofile)

But keep in mind that not all browsers support "sampling profiling", so not all browsers will produce an actual stacktrace (I tested in Safari and it didn't work, the downloaded file was empty). To see which browsers support that you can check [this link](https://caniuse.com/mdn-api_profiler) 👀 

> The file above was captured in Android Google Chrome broswer.

**Comment by kirillzyusko** [comment]
@puneetlath @muttmuure since it was deployed to staging - can we verify that it actually works there and close the issue?

**Comment by puneetlath** [comment]
I do see the option. This was on iOS Safari. Do we need to do anything else to verify it? 

![IMG_3AE841CD32DE-1](https://github.com/user-attachments/assets/839b3fba-7043-44bc-8e61-3f4368b5140d)

**Comment by kirillzyusko** [comment]
You can toggle this button do some interactions in the app and stop profiling to be sure that performance profile is actually generated.

But you'll need to use Google Chrome, since Safari [doesn't support](https://caniuse.com/mdn-api_profiler) this feature.

**Comment by puneetlath** [comment]
I tried it on iOS Safari, but the profile was empty. It just had: 
```
{"traceEvents":[],"samples":[],"stackFrames":[]}%
```

Does it work for you @kirillzyusko?

**Comment by kirillzyusko** [comment]
@puneetlath I've observer, that sometimes profile can not be generated and we just generate an empty stack trace (it happens randomly). But if I try second time, then everything works well 🤷‍♂️ I haven't figured out why it happens exactly, but may I ask you to try several times? Typically if the first time it was generated empty, then the second time you should get a real report 😅

**Comment by puneetlath** [comment]
I tried many times in iOS Chrome on both staging and production and it was empty every time. Very weird! Any ideas?

**Comment by kirillzyusko** [comment]
@puneetlath you are right, I've just tested Google Chrome iOS and I also can not generate a proper report. I think on iOS a self profiling is simply not supported (irrespective to the browser that you use) 😔 

It's kind of weird, because on desktop we have a difference between Chrome/Safari, but on mobile it looks like both browsers behave in the same way 🤔

**Comment by kirillzyusko** [comment]
@puneetlath yes, Android should work fine :)

**Comment by puneetlath** [comment]
Ok cool. Closing out then!
