### ISSUE TITLE
[HOLD for payment 2024-08-19] Suggestions causing excessive updates

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#46810]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:v9.0.16-4 Develop**
**Reproducible in staging?: No, but there no warning will be thrown, although the performance impact is there**
**Reproducible in production?: No, but there no warning will be thrown, although the performance impact is there**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):n/a**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:@hannojg**
**Slack conversation:**

## Action Performed:

- Open the native mobile app in development mode
- Type rapidly into the composer spamming ~80 characters
- In dev mode a warning will popup warning about excessive re-renders

## Expected Result:

None of our components rerenders excessively while typing.

## Actual Result:

Although there are no visible changes, internally we queue lots of react state updates.

## Workaround:

No, its more of a performance issue.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f6546888-bd0f-453c-89ea-1d39fe21308c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by hungvu193** [comment]
@neil-marcellini  Since I reviewed the PR, can you please assign me to this issue? TIA 😄

**Comment by hannojg** [comment]
I think no regression test is needed, this is only something that can come up during development

**Comment by hungvu193** [comment]
> Let's close now then, no payment, no regression tests needed.

I think there will be payment left for me. I reviewed the PR

**Comment by twisterdotcom** [comment]
Ah, you're right! Sorry for missing that @hungvu193.

**Comment by twisterdotcom** [comment]
Payment Summary:

- @hungvu193 paid $250 via newDot requests (C+)
- @hannojg does not require payment (Contractor)

**Comment by JmillsExpensify** [comment]
$250 approved for @hungvu193
