### ISSUE TITLE
[$250] Video controls overlapping and unable to dismiss in Intro video

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46817]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-2
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722857321756849

## Action Performed:
1. Open the hybrid app with the newly created account
2. Tap Menu > Try New Expensify
## Expected Result:
Video plays without any issue
## Actual Result:
Video controls overlapping and unable to dismiss when video playing
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/54c6b10c-7f0e-4ce2-8e54-af462c79b450" width="40%" height="40%">
<img src="https://github.com/user-attachments/assets/e43a5463-d4ee-4272-b4e8-c92504772baa" width="40%" height="40%">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0175f81f3b252e1679</li>
        <li>Upwork Job ID: 1827432187435135221</li>
        <li>Last Price Increase: 2024-08-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by kevinksullivan** [comment]
Putting this in collect as it's onboarding related

**Comment by trjExpensify** [comment]
Kewl, are you waiting on something to move it `External` and `Help wanted`?

**Comment by kevinksullivan** [comment]
Ah sorry, I totally slipped on the labeling. Added.

**Comment by trjExpensify** [comment]
Done!
