### ISSUE TITLE
[HOLD for payment 2024-08-19] [CRITICAL] [Advanced Approval Workflows] Implement Collect Upgrade Path

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#46818]
cc @blazejkustra @Guccio163 

<details><summary>Issue Owner</summary>Current Issue Owner: @Guccio163</details>

**Comment by Guccio163** [comment]
Hi, I'm Wiktor Gut from Software Mansion and I'm already working on this!

**Comment by garrettmknight** [comment]
👋 does this trigger off both 'Add additional approver' and 'Add additional workflow'?

**Comment by Guccio163** [comment]
Right now it is triggered only on `Add approval workflow`; The `Add additional approver` will be part of **Editing** and **Creating** workflow pages: it will be triggered only on **Editing** one, because the **Adding** page is already unavailable for users without Control plan.

On second thought, user can access **Adding** page directly via typing url by hand, but I guess guys from backend also check if user is authorised to do the action, do I think right @tgolen @blazejkustra ?

**Comment by garrettmknight** [comment]
> it will be triggered only on Editing one

I think Collect users will still see the `Add additional approver` option when editing their single workflow right?

**Comment by Guccio163** [comment]
Yup, afaik **every** user will be able to open `Edit workflow` page and it will look exactly the same for everyone, only difference is that Collect users will be able to actually add additional approver after clicking `Add additional approver` button and non-Collect users will be redirected to the `Upgrade page`

**Comment by garrettmknight** [comment]
> Yup, afaik every user will be able to open Edit workflow page and it will look exactly the same for everyone, only difference is that Collect users will be able to actually add additional approver after clicking Add additional approver button and non-Collect users will be redirected to the Upgrade page
*Control, but yep! So we'll want to add the Upgrade flow for:
1. Collect users that click 'Add additional approver' in the workflow edit screen
2. Collect users that click 'Add additional workflow' in the workflow menu.

**Comment by Guccio163** [comment]
Exactly! It is already working for `Add additional workflow` in menu and will be implemented for `Add additional approver` in workflow edit screen once this screen's made.

**Comment by s77rt** [comment]
@tgolen Can you please assign me here for PR review

**Comment by tgolen** [comment]
@lschurr Could you please assist with paying @s77rt for a C+ review of the PR?

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
