### ISSUE TITLE
[Payment 2024-09-06] [$250] Search - Raw markdown symbols visible in search expense list

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46828]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+new@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to [staging.new.expensify.com].
2. Navigate to any chat.
3. Click on the plus icon in the compose box.
4. Select "Submit Expense."
5. Enter the amount and press "Next."
6. Submit the expense.
7. Navigate to the expense detail page.
8. Click on the description field.
9. Type a header markdown (e.g., # text) or any type of mark down text and click "Save."
10. Navigate to the search page located next to "Inbox."

## Expected Result:
Markdown syntax should be rendered correctly, so any Markdown formatting appears as intended (e.g., bold text, header ) without displaying raw Markdown symbols.

## Actual Result:
Raw Markdown symbols are visible in the expense list on the search page, indicating that Markdown is not being rendered properly in this context which is different from expense description behavior in other places in the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6551623_1721834797626!2](https://github.com/user-attachments/assets/4fbb6996-2e59-4028-833d-da0d1d95a106)

https://github.com/user-attachments/assets/845e1ea4-69e8-44b5-b93c-1c460fc5096f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0118ebdaf7338382b5</li>
        <li>Upwork Job ID: 1824560866443816441</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103622954</li>
<li>Krishna2323 | Contributor | 103651370</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by strepanier03** [comment]
Hmmm, the description is not a visible field on the expense when I'm on the search page, so the markdown isn't displayed either way for me. 

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/f2e86384-44e5-45cb-bffc-1612def48093">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/9b93d726-0c22-4779-9bc4-a64a767a6137">

**Comment by strepanier03** [comment]
Got it, thanks @daledah - I'll retest with that in mind.

**Comment by carlosmiceli** [comment]
I think so, can we see a video to confirm that it would look properly?

**Comment by carlosmiceli** [comment]
Yeah, I think this is good! Let's do it :)

**Comment by carlosmiceli** [comment]
Sure, am I removing @daledah ?

**Comment by strepanier03** [comment]
Looks like automation failed so I updated title and labels.

**Comment by strepanier03** [comment]
### Payment summary

- [x] $250 - @Krishna2323 via Upwork (paid)
- [x] $250 - @ishpaul777 via Upwork (paid)

Thanks everyone!
