### ISSUE TITLE
[HOLD for payment 2024-09-19][$1000] Replace report.notificationPreference with report.participants

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#46835]
Right now we are sending duplicate data in the report participants object and the notificationPreference object. To unify the data in one place and simplify the back-end flow, we are going to update the notificationPreference to be a part of the participants object. 

```
{
    [accountID1]: {role: 'admin', notificationPreference: 'mute'},
    [accountID2]: {role: 'member', notificationPreference: 'always'},
}
```

To make this update we will need to: 

- [x] Update back-end to start including notificationPreference in the participants object whenever it is currently sent https://github.com/Expensify/Auth/pull/11920
- [x] Update back-end to start including full participants object whenever sending the report
- [x] Re-add the Web tests that were commented out in https://github.com/Expensify/Web-Expensify/pull/43027
- [x] Update the front-end to start using this notificationPreference instead of the report.notificationPreference or report.participants.hidden values
- [ ] Update the back-end to stop sending the deprecated fields

cc @shubham1206agra 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by puneetlath** [comment]
Front-end is unblocked now and @shubham1206agra has started working on it.

**Comment by mallenexpensify** [comment]
@shubham1206agra can you provide an update on where we're at here? Do you have an expected timeline for when this will be done? Asking cuz the below is held, pending this issue. Thx
- https://github.com/Expensify/App/issues/35000

**Comment by mallenexpensify** [comment]
@shubham1206agra @ishpaul777 , are you planning to create a test case for this? Asking cuz I need to figure out if we should for the issue below (which was fixed by the[ linked PR here](https://github.com/Expensify/App/pull/47506))
- https://github.com/Expensify/App/issues/35000#issuecomment-2313132616 

thx

**Comment by puneetlath** [comment]
There's still more work to come here, so let's hold off on paying anything out yet.

**Comment by mallenexpensify** [comment]
As [addressed above](https://github.com/Expensify/App/issues/46835#issuecomment-2313136825), I'm going to assume y'all will create any needed regression tests _holistically_ as part of this.  If not, plz comment[ here](https://github.com/Expensify/App/issues/35000) and I'll get one created.

**Comment by carlosmiceli** [comment]
Dropping a link to this [conversation](https://expensify.slack.com/archives/C05LX9D6E07/p1725913140419859?thread_ts=1724780554.260709&cid=C05LX9D6E07) here so that we remember to check if it also solves that issue once it's ready, or if that issue remains.

**Comment by puneetlath** [comment]
I've raised a couple back-end PRs to remove the old `report.notificationPreference` and `report.participants.hidden` fields. @shubham1206agra @ishpaul777 is there anything else we need to do on the client-side or are we 100% done there?

**Comment by puneetlath** [comment]
I think $1k is a fair price for this project. Seems to be about 4x the size of a typical issue. 

@ishpaul777 I think it would be good to add some regression tests. Can you suggest some? 

@ishpaul777 offer here: https://www.upwork.com/nx/wm/offer/104089867
@shubham1206agra offer here: https://www.upwork.com/nx/wm/offer/104089884

Please ping me here when you've accepted the offers.

**Comment by puneetlath** [comment]
Regression test issue here: https://github.com/Expensify/Expensify/issues/430315

Everyone has been paid. Thanks @shubham1206agra and @ishpaul777! 

I'm still going to leave this open as there's still some more back-end cleanup to do before we're 100% done.

**Comment by Julesssss** [comment]
FYI backend changes were reverted.

**Comment by Julesssss** [comment]
> Can you tell us the reason?

We were forcing users to update to a specific version, but that version doesn't exist on prod for the old app.

**Comment by puneetlath** [comment]
Just to clarify, we reverted the change to only send the back-end data the new way. So we've reverted back to sending both the old and new way, so that new and old clients will still work.

**Comment by puneetlath** [comment]
Still waiting on https://github.com/Expensify/Expensify/issues/433068 before re-adding the back-end changes to get rid of report.notificationPreference altogether. Once that version is at 100% in the Apple app store and Google Play store, we'll be able to re-add those changes.

**Comment by puneetlath** [comment]
Now that HybridApp is at 100% above the version we need, I've put up a PR again to update the minimum supported version: https://github.com/Expensify/Web-Expensify/pull/44252. 

Then all that's left is: 
- stop sending the deprecated field: https://github.com/Expensify/Auth/pull/13006
- update web tests that were commented out

**Comment by puneetlath** [comment]
This is officially all done. The back-end is no longer sending the old fields. Thanks everyone!
