### ISSUE TITLE
[hold for payment 2024-09-17] [$500] Make the Details > Members view of rooms, groups, and reports consistent

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#46838]
As part of the group chat clean up, we updated the Details > Members section look like a table view:
![image](https://github.com/user-attachments/assets/a467e7d7-4ff8-4727-af52-7607fa274de5)

This view matches more closely with what the Members section of the workspace editor looks like.

However, we did not update this same view when viewing certain chat rooms, like this:
![CleanShot 2024-08-05 at 17 41 11@2x](https://github.com/user-attachments/assets/9af6e33b-8cd4-46c2-8010-18a436dd5e40)

So let's make this part of the app consistent and use the updated members table style everywhere. 

cc @marcaaron @JmillsExpensify 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cc3a8881c60b2cb7</li>
        <li>Upwork Job ID: 1820807133375331083</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103430717</li>
<li>rayane-djouah | Contributor | 103430718</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by neonbhai** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Make the Details > Members view of rooms, groups, and reports consistent

### What is the root cause of that problem?
Feature Request

### What changes do you think we should make in order to solve the problem?
We will:

- Use the `SelectionListWithModal` component
- Change the list item type for room members page to `UserListItem`
  https://github.com/Expensify/App/blob/e9094967b86d1aa3ba65b64678aa2757a61c0569/src/pages/RoomMembersPage.tsx#L307
- Add Selection Mode to this page:
  + Add props `turnOnSelectionModeOnLongPress` && `onTurnOnSelectionMode={(item) => item && toggleUser(item?.accountID)}`
- Add logic for Dropdown Header Button same as [here](https://github.com/Expensify/App/blob/e9094967b86d1aa3ba65b64678aa2757a61c0569/src/pages/workspace/WorkspaceMembersPage.tsx#L503-L534). Render it as
  ```
  <View style={[styles.pl5, styles.pr5]}>{headerButtons}</View>
  ````
- Delete the `Remove` button, Add a 'Invite Members' button similar to workspace members page [here](https://github.com/Expensify/App/blob/e9094967b86d1aa3ba65b64678aa2757a61c0569/src/pages/workspace/WorkspaceMembersPage.tsx#L522-L530)
  ```jsx
      const headerContent = useMemo(() => {
        return <Text style={[styles.pl5, styles.mb4, styles.mt6, styles.textSupporting]}>{'List of all room members'}</Text>;
    }, [styles, translate]);

    const bulkActionsButtonOptions = useMemo(() => {
        const options: Array<DropdownOption<WorkspaceMemberBulkActionType>> = [
            {
                text: translate('workspace.people.removeMembersTitle'),
                value: CONST.POLICY.MEMBERS_BULK_ACTION_TYPES.REMOVE,
                icon: Expensicons.RemoveMembers,
                onSelected: () => setRemoveMembersConfirmModalVisible(true),
            },
        ];

        return options;
    }, [translate, setRemoveMembersConfirmModalVisible, selectedMembers, report.participants]);

    const headerButtons = useMemo(() => {
        return (
            <View style={styles.w100}>
                {(selectedMembers.length > 0) ? (
                    <ButtonWithDropdownMenu<WorkspaceMemberBulkActionType>
                        shouldAlwaysShowDropdownMenu
                        pressOnEnter
                        customText={translate('workspace.common.selected', {selectedNumber: selectedMembers.length})}
                        buttonSize={CONST.DROPDOWN_BUTTON_SIZE.MEDIUM}
                        onPress={() => null}
                        options={bulkActionsButtonOptions}
                        style={[styles.flexGrow1]}
                        isDisabled={!selectedMembers.length}
                    />
                ) : (
                    <Button
                        medium
                        success
                        onPress={inviteUser}
                        text={translate('workspace.invite.member')}
                        icon={Expensicons.Plus}
                        innerStyles={[styles.alignItemsCenter]}
                        style={[styles.flexGrow1]}
                    />
                )}
            </View>
        );
    }, [bulkActionsButtonOptions, inviteUser, selectedMembers, styles, translate]);
	````

- Remove the SearchValue state.

**Comment by shawnborton** [comment]
We want to keep the search functionality there when it's needed. I think we include the search bar if the list is greater than 8 or something like that?

**Comment by dannymcclain** [comment]
>do we want to keep the header buttons as they are now?
>Or do we want it to use the dynamic button with a dropdown?

I'll let Shawn weigh in, but it makes sense to me to use the dynamic button (2nd & 3rd screenshots above) because that's consistent with how groups are currently working.

> (does the dropdown make sense if there's only 1 option – "delete")?

Personally I think this is fine

**Comment by shawnborton** [comment]
Interesting, I would think that we only include the search bar when we hit X number of members. Thoughts on that @Expensify/design @trjExpensify @JmillsExpensify?

**Comment by dannymcclain** [comment]
>Interesting, I would think that we only include the search bar when we hit X number of members.

Yeah I agree. Not sure why we'd treat this differently than everything else.

**Comment by dubielzyk-expensify** [comment]
Agree with Danny and Shawn

**Comment by trjExpensify** [comment]
>Interesting, I would think that we only include the search bar when we hit X number of members. Thoughts on that @Expensify/design @trjExpensify @JmillsExpensify?

I agree, I think the magic number is 8, right?

**Comment by joekaufmanexpensify** [comment]
Yep, it's typically <8 no search bar, 8+ search bar

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by joekaufmanexpensify** [comment]
Pending PR

**Comment by joekaufmanexpensify** [comment]
PR in progress

**Comment by MariaHCD** [comment]
@paultsimura let's do it - it makes sense to me to fix and design inconsistencies in that PR. 

@rayane-djouah Can you list the additional design fixes and then make a suggestion on what a fair increased bounty would be?

**Comment by joekaufmanexpensify** [comment]
Sounds good to me! Are we going to make all of those changes in the existing PR, or will there be additional PRs?

**Comment by joekaufmanexpensify** [comment]
Sweet, sounds good. TY!

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
Hm, that is not correct.

**Comment by joekaufmanexpensify** [comment]
Sounds good!

**Comment by joekaufmanexpensify** [comment]
>This ^ was a very minor copy change issue, which I addressed in a follow-up PR: https://github.com/Expensify/App/pull/48843.

@rayane-djouah I agree this seems like a pretty simple copy change, but it was still a regression, no?

**Comment by joekaufmanexpensify** [comment]
Sounds good on checklist, I will handle!

**Comment by joekaufmanexpensify** [comment]
Made regression test: https://github.com/Expensify/Expensify/issues/428848

**Comment by joekaufmanexpensify** [comment]
All set to issue payment! We need to pay: 

- @rayane-djouah - $500 for PR via Upwork. 
- @paultsimura - $500 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment]
@rayane-djouah $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@paultsimura $500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
