### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250][P2P Distance] Rate currency doesn't match expense currency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46844]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura 
**Initial slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722875886722249

Additional in depth [conversation and conclusion](https://expensify.slack.com/archives/C01GTK53T8Q/p1723657142256719?thread_ts=1723152837.593809&cid=C01GTK53T8Q)

## Action Performed:
1. User A uses EUR/km as currency and mileage unit
2. User B uses USD/miles
3. User A submits a distance expense to User B

## Expected Result:
Show the rate in the original currency of the expense for both users, to match the fact that we use the original currency for the amount.

Also, some general notes:
- The currency of the IOU report is the reporting currency of the user that’s owed
- Transaction threads/individual expense views show amounts in the original currency they were requested in
- The only way a user can see the original currency vs the reporting currency for the amount, is when there is one expense on the report, in which case the reporting currency is used for the report total and it’s easy to see in comparison to the expense currency.

**Note:** The distance rate (mi or km) is being handled separately in this issue
- [ ] [[$250] Distance - Inconsistency in showing unit in preview and transaction thread after updating unit](https://github.com/Expensify/App/issues/43588#top)

## Actual Result:
User B sees the rate in USD without it being converted at all, so it’s inaccurate.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
Single expense report preview
User A
![ a-preview](https://github.com/user-attachments/assets/55cd494a-b355-4119-b79f-580968b1dc67)

User B
![b-preview](https://github.com/user-attachments/assets/9d0e8095-7bf6-4c89-8275-8fb9ae4a9ddf)

Expense view
User A
![a-expense](https://github.com/user-attachments/assets/9a385169-20f0-421c-981f-b165bf6be349)

User B
![b-expense](https://github.com/user-attachments/assets/d5516cea-2033-40b8-8fc8-d89ec23b4611)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb1bf8d2bf2fb7c7</li>
        <li>Upwork Job ID: 1821378352686653817</li>
        <li>Last Price Increase: 2024-10-01</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 103443192</li>
<li>nyomanjyotisa | Contributor | 104234962</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by stephanieelliott** [comment]
Sure, all yours @paultsimura -- I've assigned you as C+!

**Comment by neil-marcellini** [comment]
Wow this is an interesting one. I think ideally each user will see it based on their own preferences. So if A is in EUR/km and B is in USD/mi, then both alway sees the values in their units.

However, I'm not sure if our system is going to support that very well right now. It would be helpful to know what happens with IOUs if two users create manual expenses with different currencies. We will probably want to follow that pattern.

@paultsimura would you please do that investigation and then make a post asking about the UX for this situation in #expensify-open-source? I will then share it with our internal team and we can all agree on what's best. It feels somewhat important and something we haven't considered much so I want to get a good amount of feedback.

**Comment by neil-marcellini** [comment]
Assigning myself to help move that discussion along

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
P2P Distance] Rate: incorrect currency for p2p request 

### What is the root cause of that problem?
We were displaying based on currency setting of the user's personal policy
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/components/ReportActionItem/MoneyRequestView.tsx#L240-L241
### What changes do you think we should make in order to solve the problem?

We should change it to 
```
    const currency = policy ? policy.outputCurrency : transactionCurrency ?? CONST.CURRENCY.USD;

```
or 
```
    const currency = policy ? policy.outputCurrency : transactionCurrency ?? PolicyUtils.getPersonalPolicy()?.outputCurrency ?? CONST.CURRENCY.USD;

```
### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment]
Sounds good @paultsimura  -- adjusted title and labels for the hold

**Comment by stephanieelliott** [comment]
Still held for https://github.com/Expensify/App/issues/46753 and https://github.com/Expensify/App/issues/43588

**Comment by neil-marcellini** [comment]
FYI the conclusion for this one is [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1723657142256719?thread_ts=1723152837.593809&cid=C01GTK53T8Q). I think we should specifically focus this issue on the currencies displayed for the amount and rate. The unit can be handled with [this issue](https://github.com/Expensify/App/issues/43588#top).

**Comment by stephanieelliott** [comment]
Still held on https://github.com/Expensify/App/issues/43588

**Comment by stephanieelliott** [comment]
Still held on https://github.com/Expensify/App/issues/43588

**Comment by neil-marcellini** [comment]
I'm going to modify the title and description heavily based on the conclusions in the [thread I linked above](https://expensify.slack.com/archives/C01GTK53T8Q/p1723657142256719?thread_ts=1723152837.593809&cid=C01GTK53T8Q), which will make this issue a lot more clear.

Also, I think we can fix this by using the currency stored in the transaction. Seeking proposals now @paultsimura

**Comment by neil-marcellini** [comment]
> @neil-marcellini thanks for simplifying the scope here.
> 
> The [proposal](https://github.com/Expensify/App/issues/46844#issuecomment-2270164226) by @nyomanjyotisa looks good to me (the last alternative option to be more specific). Just use the already defined `transactionCurrency` variable instead of `transaction.currency`.
> 
> @neil-marcellini FYI there might be some edge cases with the rate edit flow, but it'll be better to address them separately after your _mileage unit_ changes are implemented.
> 
> **🎀👀🎀 C+ reviewed**

Sweet, I agree. Hiring.

**Comment by stephanieelliott** [comment]
PR is still under active review

**Comment by stephanieelliott** [comment]
Regression test created: https://github.com/Expensify/Expensify/issues/439138

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @nyomanjyotisa $250 via Upwork - PAID
 - Contributor+: @paultsimura $250 via Upwork - PAID
 
 Upwork job is here: https://www.upwork.com/jobs/~01fb1bf8d2bf2fb7c7
