### ISSUE TITLE
[HOLD for payment 2024-08-19] [HOLD for payment 2024-08-14] Distance - App crashes when submitting distance expense and editing distance offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46874]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go offline
4. Submit a distance expense
5. Go to transaction thread
6. Click Distance
7. Change the waypoints (by exchanging position)
8. Save it

## Expected Result:
App will not crash

## Actual Result:
App crashes when submitting distance expense and editing distance offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/72863626-e2c6-489f-b0c5-69662a919261

[logs (2).txt](https://github.com/user-attachments/files/16509916/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BrtqKr** [comment]
`convertToDisplayString()` seems to be receiving 'Pending...' as a currency, which probably happens after editing the expense offline. I can take care of it if that's ok

**Comment by grgia** [comment]
https://github.com/Expensify/App/pull/46165/
https://github.com/Expensify/App/pull/40021

could be related. It does seem like ^ is the issue

**Comment by grgia** [comment]
@BrtqKr maybe https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L255-L257

**Comment by grgia** [comment]
Assigning @paultsimura!

**Comment by marcaaron** [comment]
I think we're good to remove the blocker here based on @AndrewGable's message [here](https://expensify.slack.com/archives/C07J32337/p1722980295599719).
