### ISSUE TITLE
Task – Blue border appears around task details header if delete task using Enter key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4825048
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Click on FAB and select Assign task
4. Assign task to you and share to another user
5. Open task details
6. Send a message
7. Click on header and select detete
8. On confirmation modal click Enter key to delete the task

## Expected Result:
Blue border not appears around task details header

## Actual Result:
Blue border appears around task details header

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7106f640-fa57-4e38-962b-3e78d6287608

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by pecanoro** [comment]
This is only reproducible if you click on the delete modal before clicking enter. I also think this is probably expected since I think we were trying to fix that the right hand modal was staying opened after deleting.

**Comment by pecanoro** [comment]
I am going to close since that blue border is just the focus and I don't think it's worth investing time on it as it's a super edge case
