### ISSUE TITLE
[Hold PR #46869] Pay someone - App crashes when proceeding to confirmation page during pay someone flow

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46876]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/46629

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Click +
4. Click Pay.
5. Enter amount.
6. Click Next.

## Expected Result:
App will not crash.

## Actual Result:
App crashes.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
[Bug6563114_1722930469626!staging.new.expensify.com-1722930458808.txt](https://github.com/user-attachments/files/16510041/Bug6563114_1722930469626.staging.new.expensify.com-1722930458808.txt)

https://github.com/user-attachments/assets/f95357df-f44b-4100-982d-d1911251b606

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by trjExpensify** [comment]
Put it on hold for that PR.

**Comment by trjExpensify** [comment]
Confirmed this is no longer reproducible, closing.
