### ISSUE TITLE
[$250][P2P Distance] - Distance unit in the system message changes from "miles" to "mi" after changing rate

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46873]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/40021
**Version Number:** 9.0.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace has a few distance rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a distance expense.
4. Go to transaction thread.
5. Click Rate.
6. Select a different rate.

## Expected Result:
The distance unit in the system message will remain the same after changing the rate.

## Actual Result:
The distance unit in the system message changes from "miles" to "mi" after changing distance rate.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b9a04f89-08b5-42ec-8c02-e3d729befd5f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f98f5e4f3df20f5</li>
        <li>Upwork Job ID: 1820884011095014188</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 103497380</li>
<li>Krishna2323 | Contributor | 103523740</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by puneetlath** [comment]
Doesn't need to block either deploy. Confirming whether the back-end or the front-end is using the proper message here: https://expensify.slack.com/archives/C036QM0SLJK/p1722965084031989. Based on that, we can update one or the other.

**Comment by puneetlath** [comment]
Ok @neil-marcellini confirmed that the back-end is correct, so we need to fix the optimistic action. Making external.

**Comment by muttmuure** [comment]
$250 - @paultsimura 
$250 - @Krishna2323

**Comment by muttmuure** [comment]
Paid
