### ISSUE TITLE
Composer - Cell pointer comes at the middle of a content when pasting to composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any conversation
2. Send the following markdown. Each work should be in new line
*bold*
_italic_
```
code
```
3. Right click the sent message > click 'Copy to clipboard'
4. Press CTRL + SHIFT + V

## Expected Result:
Cell pointer should be displayed at the end of the content

## Actual Result:
Cell pointer comes in the middle of the content

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/33eb0874-487f-4e0f-96dd-02663d84cbe4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsb

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment]
I swear I run into this bug on other plaforms so am going to close this for now
