### ISSUE TITLE
Distance-"Rate" field is not displayed in request details page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46871]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/40021

**Version Number:** 9.0.17-0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** sarahhailu45+higjht@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 
## Action Performed:
Pre-requisite:
Sign in with a new Gmail account
Have a collect workspace with distance rates enabled and multiple Distance Rates
Steps
1. Click on FAB > Submit Expense > Distance
2. Choose waypoints > Choose the collect workspace > Submit
3. Navigate to the request details page

## Expected Result:
The "Rate" field is displayed and can be changed

## Actual Result:
The "Rate" field is not displayed

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c5f700dc-2b0e-4a7b-8dc3-afd92c2817ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment]
This is not a problem, it's how the p2p distance beta works. We hide all features related to p2p distance, such as the rate field.

Also @m-natarajan why did you say it's not reproducible on production? The rate field is appropriately hidden there as well.
![image](https://github.com/user-attachments/assets/4f837cac-c944-4ea4-8d7e-00894b3805e8)
