### ISSUE TITLE
[$250] Chat - Room - Rooms mention list does not appear in message edit mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4826336
**Email or phone of affected tester (no customers):** fischer9966@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open App or go to staging.new.expensify.com
2. Login with any account
3. Go to any room or create new one
4. Send a message with a room mention
5. Edit this message by adding or editing room mentions selecting it from suggestion list

## Expected Result:
User can select room mention from suggestion list in edit mode

## Actual Result:
Rooms mention list does not appear in message edit mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/65c1c3d9-b836-44a2-ab94-75f02228605f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dedb57180f356839</li>
        <li>Upwork Job ID: 1822051289639048019</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103627253</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by lanitochka17** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by kevinksullivan** [comment]
@eVoloshchak can you review the proposal please?

**Comment by AlfredoAlc** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Rooms mention list does not appear in message edit mode

### What is the root cause of that problem?
The [SuggestionMention](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx) component requires to have `isGroupPolicyReport` and `policyID` to render room mention list.
We are passing `isGroupPolicyReport` as false and we are not passing `policyID`

### What changes do you think we should make in order to solve the problem?
The `ReportActionItemMessageEdit` component is already receiving `isGroupPolicyReport` we just need to propagate the prop.
And from that same component we already have access to the report `policyID`, so it'll only need to pass that prop to `ReportActionItemMessageEdit` and propagate the prop.

https://github.com/Expensify/App/blob/72a75930d7b3a0a0bb7a5e6e76f8c7bfcbee2205/src/pages/home/report/ReportActionItem.tsx#L718-L729

**Comment by eVoloshchak** [comment]
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/46889#issuecomment-2271397284) looks good to me

🎀👀🎀 C+ reviewed!

**Comment by kevinksullivan** [comment]
Looping in a BZ member to handle payment as I'm going OOO

**Comment by puneetlath** [comment]
@eVoloshchak when will this need paying?

**Comment by eVoloshchak** [comment]
@puneetlath, not clear yet, as this wasn't deployed to staging/prod yet
[Latest update:](https://github.com/Expensify/App/pull/47949#issuecomment-2332954488)
> This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by jasperhuangg** [comment]
I think our automation was broken for a bit, seems like the PR was deployed to production in this checklist: https://github.com/Expensify/App/issues/48791

I think we can issue payment now

**Comment by FitseTLT** [comment]
@puneetlath can you issue the payment here??

**Comment by puneetlath** [comment]
Sorry for the delay! 

Payment summary: 
- C - $250 - @FitseTLT - paid via Upwork
- C+ - 250 - @eVoloshchak - to be paid via NewDot

Thanks everyone!

**Comment by FitseTLT** [comment]
@puneetlath I see that the contract has ended but the payment hasn't been made.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/1a7b2887-5a2b-40e6-a5b7-b46ed5c2bfe0">

**Comment by puneetlath** [comment]
That is very weird! I added the payment as a bonus, so it should be there now.

**Comment by FitseTLT** [comment]
Yep, I received it now. Thx!

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
