### ISSUE TITLE
Distance - System message contains blank info when submitting expense and editing rate offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46895]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
- Workspace has a few distance rates
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go offline
4. Submit a distance expense
5. Go to transaction thread
6. Click Rate
7. Select a different rate

## Expected Result:
The system message should only appear after returning online as it contains incorrect before and after amount - "which updated the amount to $0.00 (previously )"

## Actual Result:
The system message is not accurate and contains blank info. It shows "which updated the amount to $0.00 (previously )". The previous amount is blank, the new amount is $0.00 which is also not accurate. The message should only appear after returning online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/666b57aa-cfff-4aaf-a94d-4c180e616e7e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by lanitochka17** [comment]
@marcochavezf  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to ##wave-collect - Release 1

**Comment by marcochavezf** [comment]
Seems this was introduced [here](https://github.com/Expensify/App/pull/40021) and seems the Edit Rate is a new feature cc @neil-marcellini @paultsimura

**Comment by neil-marcellini** [comment]
Not a blocker, under the P2P distance beta. I agree with the expected result that the modified expense message shouldn't appear until we come back online.

**Comment by neil-marcellini** [comment]
Yeah that sounds good, we shouldn't create the optimistic action if we don't have the data to compute it, but we could create it if that data is present and we know it's not stale. The same could be done for the waypoints in some cases, but I think the author didn't want to bother with those edge cases.

I'm going to let @marcochavezf continue to manage this one internally since I really appreciate the extra help on these distance bugs. Please direct questions to him, but I'll be around if there's something you really need by opinion on.

**Comment by marcochavezf** [comment]
Hi @miljakljajic! Can you handle the payment for @paultsimura as contributor and @allroundexperts as C+ reviewer?

**Comment by miljakljajic** [comment]
@marcochavezf is this a 250 USD or 125 USD issue?

**Comment by marcochavezf** [comment]
250 please

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/40021
2. Author was aware of the issue and fixed it.
3. N/A
4. A regression test might be useful.

## Regression test

1. Open the app and login to an account that has multiple distance rates available
2. Go offline and submit a distance expense to the workspace with multiple distance rates
4. Go to transaction thread -> click Rate -> select a different rate

Verify that the system message should only appear after returning online

Do we 👍 or 👎 ?

**Comment by miljakljajic** [comment]
Payment summary for @allroundexperts 

@allroundexperts is owed 250 for their work reviewing this PR

@paultsimura paid in Upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
