### ISSUE TITLE
Search - Android - Expenses text is aligned differently in mweb and android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46893]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:**  Applause - Internal Team

## Action Performed:
1. Launch app in mweb and android
2. Tap search icon in footer
3. Note expenses text in header in mweb and android

## Expected Result:
Expenses text must be aligned same in mweb and android

## Actual Result:
Expenses text is aligned differently in mweb and android
Reproducible on device: Realme6/Android11

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f2807188-6cb0-4a95-9b16-a21e3b44897f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by VictoriaExpensify** [comment]
Unable to reproduce, it looks like this has been resolved. Thanks for the heads up @Krishna2323
