### ISSUE TITLE
 IOU - After creating expense, adding receipt shows error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46909]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab - new workspace
3. Open a workspace chat
4. Create a expense
5. Open the expense created and tap plus icon and try to upload a receipt

## Expected Result:
After creating expense, adding receipt must not show error "The receipt didn't upload. Download the file or dismiss this error and lose it."

## Actual Result:
After creating expense, adding receipt shows error "The receipt didn't upload. Download the file or dismiss this error and lose it."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0524cfc7-0dee-48b1-a52d-d835db537713

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
![Screenshot 2024-08-06 at 3 01 32 PM](https://github.com/user-attachments/assets/14ee0eb1-dc4f-4d8a-bb29-3769c8e99312)

This appears to be fixed for me on staging - asking QA for a retest

**Comment by kavimuru** [comment]
Bug is fixed

https://github.com/user-attachments/assets/a382eb36-fef4-40a6-bdf5-597128bc77c3


https://github.com/user-attachments/assets/01c82c99-c827-4c07-b474-5aea62890251

**Comment by thienlnam** [comment]
Nice
