### ISSUE TITLE
[$250] iOS - Chat - When uploading PDF, eye icon is displayed for an instant overlapping the chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46901]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** vdargentotest+ios080624@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app
2. Go to any chat
3. Tap on the "+" icon on compose box
4. Select "Add attachment", then "Choose file"
5. Send a password protected PDF

## Expected Result:
No eye icon should be displayed on chat when uploading a password protected PDF

## Actual Result:
When uploading password protected PDF, the eye icon is displayed for an instant overlapping the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/86df41c8-e42b-42d5-b365-d24b9aecce4b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107d30d16efe1ef23</li>
        <li>Upwork Job ID: 1821402719908776016</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by allroundexperts** [comment]
Waiting for proposals.

**Comment by VincentCorleone** [comment]
The App doesn't behave like the video now. Could anyone related check it again?

**Comment by VincentCorleone** [comment]
The App doesn't behave like the video now. Could anyone related check it again?

**Comment by kadiealexander** [comment]
This is so minor, closing to prioritise other issues.
