### ISSUE TITLE
[HOLD for payment 2024-09-06] [$250] Report fields - No dropdown button after selecting the list value via checkbox

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46911]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Click Type > Select List
5. Click List values
6. Add some list values
7. Select the list values via checkbox

## Expected Result:
There will be a dropdown button for enable, disable or delete the value after selecting the list value via checkbox

## Actual Result:
There is no dropdown button after selecting the list value via checkbox

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/757e3c1a-1275-4519-a50b-4178aa19fa9c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f8aa64e5e051072</li>
        <li>Upwork Job ID: 1823390208605053379</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103608281</li>
<li>cretadn22 | Contributor | 103608284</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment]
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
Sorry, @ishpaul777 would you mind summarizing the considerations for me?

**Comment by puneetlath** [comment]
I think both are valid solutions and would work fine, so this is ultimately a subjective opinion. And I know someone will end up disappointed, so I'm sorry about that, but there are always new issues and plenty of opportunities. 

I prefer this solution as I think it's just easier to read/follow: `const isAllSelected = listValues.length === selectedValuesArray.length;`

Also, small note for when you make the PR, I think proper grammar would be `areAllSelected`

**Comment by greg-schroeder** [comment]
PR deployed to staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Thanks, will prep for 9/6

**Comment by greg-schroeder** [comment]
Processing

**Comment by greg-schroeder** [comment]
Payments were completed.
