### ISSUE TITLE
Approval workflow - once approver is chosen, the member isn't showing in the approval summary field

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Christinadobrzyn 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722958028229889

## Action Performed:
Prerequisites:

- Create a workspace with multiple members
- Have all members except one assigned to one approver

1. – Click Account Settings
2. – Workspaces > Workflows > toggle on Add Approval
3. – Click Add Approval workflow
4. – Select the Member who doesn't have an approver
5. – Choose the same approver as the others have
6. – Notice the "Expenses from" isn't updated with the new member

## Expected Result:
when you've selected the same approver for a new member, the new member should show in the 'Expenses from field' section of the Add Approvals section
## Actual Result:
The new member doesn't show in the 'Expenses from field'
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1e37a92e-9558-4b14-a197-cb145565c8c4

https://github.com/user-attachments/assets/f88caa4a-5bec-4610-a625-5517724cda8b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by blazejkustra** [comment]
I think we should close this issue as adding a new approval workflow isn't implemented yet, and that's why it is not working 😄 

[Here is a PR](https://github.com/Expensify/App/pull/46798) that implements 'Add approval workflow' screen.

**Comment by blazejkustra** [comment]
Just so you know, these screens are behind a beta for now so we don't have to worry about it being in WIP state @garrettmknight

**Comment by garrettmknight** [comment]
@blazejkustra agreed!
