### ISSUE TITLE
[$250] Share somewhere should have the required label

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @srikarparsi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722971070414349

## Action Performed:

1. Click FAB
2. Click Assign Task
3. Enter in a title and click next

## Expected Result:
Share somewhere should have a required label
## Actual Result:
Share somewhere does not have a required label even though it’s a required field
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (11)](https://github.com/user-attachments/assets/5da43099-1d90-4f79-bc12-aaac15dc5a1e)

https://github.com/user-attachments/assets/737a96bb-9127-4f04-b53e-83ba98c2a872

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e4b40febf7aafce</li>
        <li>Upwork Job ID: 1820902011151409529</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103444475</li>
<li>Krishna2323 | Contributor | 103444476</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by srikarparsi** [comment]
Great thanks!

**Comment by RachCHopkins** [comment]
Payment Summary:

Contributor: @Krishna2323 paid $250 via Upwork
Contributor+: @rayane-djouah paid $250 via Upwork
Upwork job [here](https://www.upwork.com/jobs/~011e4b40febf7aafce)

**Comment by RachCHopkins** [comment]
Contributors have been paid, the contract has been completed, and the Upwork post has been closed.
