### ISSUE TITLE
[#wave-control] [Bring copilot to NewDot] Create SwitchAccountMenu and allow for switching accounts

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#46922]
# Part of the **Bring copilot to NewDot** project
Main issue: https://github.com/Expensify/Expensify/issues/382866
Doc sections: https://docs.google.com/document/d/18G6J5bl61VnVa5CoKpRXhM0MhkXDwpm87GVitZrSCVg/edit#heading=h.l2r8craz6sx4 and https://docs.google.com/document/d/18G6J5bl61VnVa5CoKpRXhM0MhkXDwpm87GVitZrSCVg/edit#heading=h.oqsjajhe4gd1
Project: https://github.com/orgs/Expensify/projects/130

# Feature Description

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by dangrous** [comment]
assigning myself for review once it's ready

**Comment by rushatgabhane** [comment]
PR: https://github.com/Expensify/App/pull/47338

**Comment by dangrous** [comment]
This is merged, but automation didn't fire... I think maybe it'll figure itself out in 7 days from prod, but we may have to do it manually. I just assigned the reviewing C+ to the other issue so I don't think payment is needed here?

**Comment by rushatgabhane** [comment]
yep can be closed

**Comment by VictoriaExpensify** [comment]
As discussed [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1729804391161829), the work @rushatgabhane completed was part of [this issue](https://github.com/Expensify/Expensify/issues/382866). 

Payment for the work was discussed upfront, with an agreed amount of $3000 for work completed on this project (screenshots in linked conversation).

Payment Summary:
Contributor+: @rushatgabhane owed $3000 via NewDot
