### ISSUE TITLE
[HOLD for payment 2024-10-07][$250] [#wave-control] [Bring copilot to NewDot] Update actions to include "delegate" (and TypeScript changes)

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#46926]
# Part of the **Bring copilot to NewDot** project
Main issue: https://github.com/Expensify/Expensify/issues/382866
Doc section: https://docs.google.com/document/d/18G6J5bl61VnVa5CoKpRXhM0MhkXDwpm87GVitZrSCVg/edit#heading=h.htovousj6t4t
Project: https://github.com/orgs/Expensify/projects/130

# Feature Description

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e32e056b7068ddf6</li>
        <li>Upwork Job ID: 1830971074509591056</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 103796623</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by dangrous** [comment]
assigning myself for review once it's ready

**Comment by dangrous** [comment]
@allgandalf it'd be great to get this PR up today or early tomorrow if possible! We're aiming to get this all merged by Thursday. Thank you!

**Comment by dangrous** [comment]
Yes! That's in progress, hopefully should be today as well

**Comment by DylanDylann** [comment]
I will review it in two next hours

**Comment by dangrous** [comment]
Prod deploy 2024-09-30, so payment 2024-10-06

**Comment by DylanDylann** [comment]
In this issue, @allgandalf implemented and I reviewed PRs
- https://github.com/Expensify/App/pull/48594
- https://github.com/Expensify/App/pull/48485

Please help to handle payment for me too, thanks

**Comment by dangrous** [comment]
Ah yep there were a lot of overlapping PRs. Assigned you and reopening for payment.

**Comment by dangrous** [comment]
bump @sakluger - can you help out with payment for @DylanDylann ? Thanks!

**Comment by sakluger** [comment]
Sorry for the wait.

Summarizing payment on this issue:

Contributor: @allgandalf $250, paid via Upwork
Contributor+: @DylanDylann $250, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/104790247

**Comment by sakluger** [comment]
Still waiting for the offer to be accepted.

**Comment by DylanDylann** [comment]
> Still waiting for the offer to be accepted.

@sakluger Done, thanks

**Comment by sakluger** [comment]
Thanks! All paid.
