### ISSUE TITLE
[Hold for payment 2024-09-06] [#wave-control] [Bring copilot to NewDot] Display account switcher

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#46920]
# Part of the **Bring copilot to NewDot** project
Main issue: https://github.com/Expensify/Expensify/issues/382866
Doc section: https://docs.google.com/document/d/18G6J5bl61VnVa5CoKpRXhM0MhkXDwpm87GVitZrSCVg/edit#heading=h.4gw8y2nhd2we
Project: https://github.com/orgs/Expensify/projects/130

# Feature Description

# Manual Test Steps

# Automated Tests

**Comment by dangrous** [comment]
assigning myself for review once it's ready

**Comment by rushatgabhane** [comment]
Popover bug to fix later: https://github.com/Expensify/App/pull/47338#issuecomment-2313666208


IOS: BUG: While offline, Alert does not show up on changing accounts.

**Comment by dangrous** [comment]
Okay just listing out the additional bugs found so far here. I think we expected there was going to be weirdness, so no worries, but definitely should look into it.

BUGS BEHIND BETA
* https://github.com/Expensify/App/issues/48247
* https://github.com/Expensify/App/issues/48245
* https://github.com/Expensify/App/issues/48252
* https://github.com/Expensify/App/issues/48246

BUGS CURRENTLY VISIBLE
* https://github.com/Expensify/App/issues/48261
* https://github.com/Expensify/App/issues/48244
* https://github.com/Expensify/App/issues/48253
* https://github.com/Expensify/App/issues/48259

The second section here is the priority, I think, but they're pretty much all visual quick fixes, nothing too crazy. @rushatgabhane do you think you could fix 'em all in one go?

The ones that are bugs with the copilot feature itself, I think we can probably just include those in the future copilot PRs, rather than doing them separately. Let me know if you disagree.

**Comment by rushatgabhane** [comment]
@dangrous sounds good

**Comment by dangrous** [comment]
@parasharrajat assigning you here since you reviewed, will grab a BZ for payment when ready!

**Comment by dangrous** [comment]
oops yep will do!

**Comment by dangrous** [comment]
hey @sonialiap! @parasharrajat reviewed this PR as the C+, so will need payment; @rushatgabhane is getting handled at the project level so I believe no payment needed for them right now. We're through the 7 day period also!

**Comment by sonialiap** [comment]
Thanks Dan :D

**Comment by sonialiap** [comment]
went to production Aug 30, payment should have been Sep 6 😳

**Comment by sonialiap** [comment]
Payment summary
- @parasharrajat C+ review - $250 - please request in NewDot
- @rushatgabhane - paid at project level, no payment needed here

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
