### ISSUE TITLE
[#wave-control] [Bring copilot to NewDot] Create AddDelegatePage

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#46924]
# Part of the **Bring copilot to NewDot** project
Main issue: https://github.com/Expensify/Expensify/issues/382866
Doc section: https://docs.google.com/document/d/18G6J5bl61VnVa5CoKpRXhM0MhkXDwpm87GVitZrSCVg/edit#heading=h.2n72uai4aja7
Project: https://github.com/orgs/Expensify/projects/130

# Feature Description

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by dangrous** [comment]
assigning myself for review once it's ready

**Comment by rushatgabhane** [comment]
PR: https://github.com/Expensify/App/pull/47353

**Comment by dangrous** [comment]
I think we can go ahead and close this one right?

**Comment by rushatgabhane** [comment]
yep
