### ISSUE TITLE
[READY FOR PAYMENT][$250] [#wave-control] [Bring copilot to NewDot] Create AvatarWithDelegate Component

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#46923]
# Part of the **Bring copilot to NewDot** project
Main issue: https://github.com/Expensify/Expensify/issues/382866
Doc section: https://docs.google.com/document/d/18G6J5bl61VnVa5CoKpRXhM0MhkXDwpm87GVitZrSCVg/edit#heading=h.pruz4z3j9te0
Project: https://github.com/orgs/Expensify/projects/130

# Feature Description

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c04cb3b5a5f9ff21</li>
        <li>Upwork Job ID: 1830970726749946379</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 103796610</li>
<li>allgandalf | Contributor | 104007726</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dangrous** [comment]
assigning myself for review once it's ready

**Comment by dangrous** [comment]
@DylanDylann it'd be great to get this PR up today or early tomorrow if possible! We're aiming to get this all merged by Thursday. Thank you!

**Comment by dangrous** [comment]
ah sorry yeah it's been on my list to make sure all of these have BZs attached and I have not had time to do so. @dylanexpensify can you handle? Or I can add the `Bug` label but I think it might just reassign you.

**Comment by dangrous** [comment]
ha I mistook @DylanDylann for @dylanexpensify , sorry! Now a BZ (who happens to be @dylanexpensify) is assigned, this is **ready for payment**

**Comment by dylanexpensify** [comment]
Done!
