### ISSUE TITLE
"User Profiling" Toggle Not Working 

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46929]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign in to the new dot.
2. Click on Ctrl + D.
3. Observe that the modal appears.
4. Attempt to toggle the 'User Profile' and notice that it does not work.

## Expected Result:
The user should be able to toggle the 'User Profile'.

## Actual Result:
The user is unable to toggle the 'User Profile'.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c6bf7420-24bc-4264-90d2-f262f01af52b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by marcaaron** [comment]
>The user should be able to toggle the 'User Profile'.

Sorry, did you mean `Use Profiling` ?

Gonna remove the blocker here. This is an internal tool and not mission critical.

**Comment by Tony-MK** [comment]
This is issue doesn't actually occur on the main branch

**Comment by zanyrenney** [comment]
![2024-08-07_14-58-18 (1)](https://github.com/user-attachments/assets/1b1ceeb4-6224-4819-9b4a-7f8adc56b490)

can reproduce on staging

**Comment by zanyrenney** [comment]
but i agree this is not critical

**Comment by zanyrenney** [comment]
do we actually do this? @thienlnam I see only one ever mention of "user profiling" in slack and its in reference to iOS: 
<img width="664" alt="2024-08-07_15-01-48" src="https://github.com/user-attachments/assets/7f6cef7f-70de-4368-b78a-1240d57eb712">

**Comment by zanyrenney** [comment]
asking here https://expensify.slack.com/archives/C05LX9D6E07/p1723039606440559

**Comment by kirillzyusko** [comment]
It happens because "hosting" is not allowing "self-profiling":

> Document policy violation: js-profiling is not allowed in this document.

I described it here: https://github.com/margelo/react-native-release-profiler?tab=readme-ov-file#web-support

We enabled this toggle in dev mode, but to enable it in prod (staging and prod) you'll need to add `'Document-Policy': 'js-profiling'` header to `html` response.

I don't have permissions to deploy so I can not fix it, but if someone can shed some light on where and how the app is hosted (is it AWS S3?) then I can co-operate with that person and together we can fix that 🤞

**Comment by zanyrenney** [comment]
Hey @thienlnam any progress here please? I see you added the Infra label - what's the intention for that to assign a specific person/group so that we can move this forward or are you still able to manage it?

**Comment by thienlnam** [comment]
Bumped this back to a weekly since it's not high priority.

I need to double check where we want to add this header - chances are it will probably be in our salt config

**Comment by thienlnam** [comment]
<img width="1085" alt="Screenshot 2024-08-23 at 9 23 33 AM" src="https://github.com/user-attachments/assets/78ef5014-e00a-4f2b-9b1a-b6bd6570986e">

Nice, resolved! We only added this to staging and adhoc builds
