### ISSUE TITLE
[HOLD for payment 2024-10-24] [#wave-control] [Bring copilot to NewDot] Add Copilot section to Security Settings Page

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#46925]
# Part of the **Bring copilot to NewDot** project
Main issue: https://github.com/Expensify/Expensify/issues/382866
Doc section: https://docs.google.com/document/d/18G6J5bl61VnVa5CoKpRXhM0MhkXDwpm87GVitZrSCVg/edit#heading=h.wdm4uvchsma7
Project: https://github.com/orgs/Expensify/projects/130

# Feature Description

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by dangrous** [comment]
assigning myself for review once it's ready

**Comment by dangrous** [comment]
Not overdue, draft PR up and waiting on related code

**Comment by dangrous** [comment]
Still in progress, getting there~

**Comment by dangrous** [comment]
Just noting - the backend PR needed is finally on staging

**Comment by dangrous** [comment]
done! I'll grab a BZ shortly too.

**Comment by dangrous** [comment]
done! Given that this issue was split in 2 PRs, I think it's full payment for both @allgandalf and @fedirjh , right?

**Comment by marcaaron** [comment]
The above bot message is not a drill 😄

**Comment by lschurr** [comment]
No overdue - payment is tomorrow.

**Comment by lschurr** [comment]
Based on [this comment](https://github.com/Expensify/App/issues/46925#issuecomment-2414212927), we'll issue full payment to @rushatgabhane @allgandalf and @fedirjh.

Payment summary:

- Contributor: $250 @rushatgabhane (please request in NewDot)
- Reviewer: $250 @fedirjh (please request in NewDot)
- Reviewer: $250 @allgandalf (please accept the offer in [Upwork](https://www.upwork.com/nx/wm/offer/104577030))

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
