### ISSUE TITLE
[HOLD for payment][OldDot Rules Migration] Add "Rules" Row/toggle to "More Features" page

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#46935]
# Part of the OldDot Rules Migration project

**Main issue:** https://github.com/Expensify/Expensify/issues/413886

# Feature Description

![2024-08-07_13-46-09](https://github.com/user-attachments/assets/b12914c9-927f-4aee-b596-c2f42804d095)

![2024-08-07_14-30-45](https://github.com/user-attachments/assets/620d4feb-6e7c-48e0-9fa5-4a280b6b8cb9)

**High Level Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.uy912otsdb3a

**Detailed Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.dlbimjgr7u70 

# Manual Test Steps

TBD

# Automated Tests

TBD

**Comment by marcaaron** [comment]
This is in progress now. @WojtekBoman kicked us off. I asked for some translations to be reviewed [here](https://expensify.slack.com/archives/C21FRDWCV/p1723684905818709).

**Comment by marcaaron** [comment]
The beta code has been moved to production so we should be able to move forward on the held PRs 🚀

**Comment by marcaaron** [comment]
Hey @johncschuster would you kindly help @mkhutornyi get paid for their work as the C+ reviewing the linked PR? It's a new feature and nobody else needs to be paid.

**Comment by johncschuster** [comment]
Ah! Sorry I missed this, @marcaaron! I review my `HOLD for payment` issues every day, but it looks like I missed this without the automatic change. I'll get payment issued today!

**Comment by johncschuster** [comment]
@mkhutornyi I've just sent you an [offer through Upwork](https://www.upwork.com/offer/103916265). Can you please accept that?
