### ISSUE TITLE
Internal: Give access to firebase performance monitor

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#46941]
Slack thread: Coming from [here](https://expensify.slack.com/archives/C05LX9D6E07/p1722964750630999?thread_ts=1722938154.174039&cid=C05LX9D6E07).

This issue is for sharing access to the firebase performance monitor dashboard. As we are working on [performance issues](https://github.com/Expensify/App/pull/46807) it would be very beneficial for us to see if our changes are actually improving the apps performance.

Please invite hanno@margelo.com to the firebase dashboard @roryabraham, thank you so much!

**Comment by roryabraham** [comment]
done, lmk if you have any issues accessing https://console.firebase.google.com/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues?state=open&time=last-seven-days&types=crash&tag=all&sort=eventCount
