### ISSUE TITLE
Room-On entering #, room mentions are shown in a invoice room.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46945]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4828511
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap Expensify switcher and via plus icon create a new workspace
3. Invite a member in the newly created workspace
4. Create 2 new room using the newly created workspace
5. Tap fab - send invoice
6. Enter an amount and tap next
7. Select user invited in step 3 and workspace in step 2
8. Tap send invoice
10. In invoice room, enter # in compose box

## Expected Result:
No room mentions should be triggered in a invoice room

## Actual Result:
On entering #, room mentions are shown in a invoice room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3efcd405-a9b7-4701-97ce-4d55d507dc46

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by dylanexpensify** [comment]
Reviewing!

**Comment by dylanexpensify** [comment]
Confirming internally [here](https://expensify.slack.com/archives/CSL3XBCCR/p1723622399075839) since Doza is at a conference!
