### ISSUE TITLE
[P2P Distance] - Error shows up after selecting distance rate without tax rate and tax reclaimable

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46957]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.17-1

**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Track tax is enabled on Workspace settings > Distance rates > Settings.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates.
3. Create a distance rate.
4. Do not assign a tax rate and tax reclaimable to the distance rate.
5. Go to workspace chat.
6. Submit a distance expense with distance rate different from the rate created in Step 4.
7. Go to transaction thread.
8. Click Rate.
9. Select the distance rate without tax rate from Step 4.

## Expected Result:
User will be able to select the distance rate without tax rate and tax reclaimable.

## Actual Result:
Error shows up after selecting the distance rate without tax rate and tax reclaimable.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0fa301d4-2df0-4510-98bc-c85cc46a91df

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by trjExpensify** [comment]
The `Rate` field is not on staging for me in my `tom@trj.chat` account, because it's a feature behind the `p2pDistanceRequests` beta and that account isn't on the beta. 

<img width="427" alt="image" src="https://github.com/user-attachments/assets/c30d5018-1456-4cc2-9d65-73c2118afb36">

So I think this can be demoted as a deploy blocker.

**Comment by trjExpensify** [comment]
Testing on my expensify.com account which is on the beta, I'm getting this when the `UpdateMoneyRequestDistanceRate` command is called:

```
jsonCode: 501, message: "501 Invalid tax percentage", onyxData: [], requestID: "8af762156c4bbefd-LHR"}
"501 Invalid tax percentage"
8af762156c4bbefd-LHR
```

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/791c5e03-a2cd-497d-8843-d7f2397433fb">

Internal logs for that requestID are [here](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228af762156c4bbefd-LHR%22%20AND%20timestamp%3A%5B2024-08-07T00%3A00%20TO%202024-08-08T23%3A59%5D). 

```
Could not calculate taxAmount, taxPercentage: , and amount: 0
```
```
Throwing exception with message: '501 Invalid tax percentage' from auth/lib/Transaction.cpp:3065
```

That's [here](https://github.com/Expensify/Auth/blob/83bfb711abe9be5da449b2552cd79e556d3d851a/auth/lib/Transaction.cpp#L3064-L3065) in Auth. 

@MonilBhavsar any insight as you added this in the blame? 🤔 (CC: @nkdengineer as well for context on building this feature a few months ago!)

**Comment by MonilBhavsar** [comment]
I was assigned couple of server errors too. Something looks off with the command. Looking into it

**Comment by trjExpensify** [comment]
Amazing! Do you agree this isn't an /app blocker though, given you can't access this `Rate` field on the expense to change if you aren't on the `p2pDistanceRequests` beta?

**Comment by MonilBhavsar** [comment]
agree, shouldn't be an app blocker, neither web. The logic lies in Auth.

But I wonder, in this case if user does not select tax rate and tax claimable percentage. Should we fallback to workspace default tax percentage?

**Comment by MonilBhavsar** [comment]
But wait. Why this created as blocker though 🤔

**Comment by mountiny** [comment]
@cristipaval @MonilBhavsar I agree this does not have to be a blocker cc @neil-marcellini as its related to the p2p distance

Feel free to remove the labels

**Comment by trjExpensify** [comment]
>But wait. Why this created as blocker though 🤔

You hit this error if you change the `Rate` field on the distance expense, under the conditions in the steps in the OP. 

>But I wonder, in this case if user does not select tax rate and tax claimable percentage. Should we fallback to workspace default tax percentage?

No, I don't think we do that on OldDot do we? Just the output is $0.00. Let me check.

**Comment by trjExpensify** [comment]
Yeah, we just leave the tax amount at $0.00 and uneditable - we don't default to the workspace default tax rate or anything as far as I can tell. 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/4a9c519c-9dab-4991-8c04-f15abff6d3ae">

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/15dfeb99-6857-408a-98ee-d9d2edea3650">

**Comment by MonilBhavsar** [comment]
Okay, thanks for looking! 🙌 

Here, we need to skip calculating tax percentage if taxCode is empty(not set by user), and add automated tests
https://github.com/Expensify/Auth/blob/c15ed2282c02386eb3d2239ff33263994c4ec798/auth/command/UpdateMoneyRequestDistanceRate.cpp#L90

I'm prioritising fire cleanup task currently, so not picking up

**Comment by Christinadobrzyn** [comment]
Thanks @MonilBhavsar! I'll add a hold label to retest after https://github.com/Expensify/Expensify/issues/418428 is deployed

**Comment by cristipaval** [comment]
I'm handing this over to you, @MonilBhavsar, as I get closer to my parental leave. Thanks for fixing 🙏

**Comment by Christinadobrzyn** [comment]
Following https://github.com/Expensify/Auth/pull/12007

**Comment by MonilBhavsar** [comment]
PR was deployed and issue is off hold now @Christinadobrzyn

**Comment by Christinadobrzyn** [comment]
Testing again - this appears to be resolved! Asking QA to test. https://expensify.slack.com/archives/C9YU7BX5M/p1723649337946129

**Comment by m-natarajan** [comment]
Bug is fixed 

https://github.com/user-attachments/assets/8ac6e356-034c-483b-b0a7-47a21fb9f579

**Comment by Christinadobrzyn** [comment]
Awesome! closing!
