### ISSUE TITLE
[Landing page] Clean up items from testing

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#46953]
Linking these from the testing thread for a reference to track making progress on fixing them.

- [x] [The clickable area for the Sign-in with Google button extends way beyond the actual button.](https://expensify.slack.com/archives/C036QM0SLJK/p1722950925030229?thread_ts=1722950065.680559&cid=C036QM0SLJK) - [PR](https://github.com/Expensify/Web-Expensify/pull/43026#issue-2451477637)

- [x] [Clicking “Learn more” on the Chat or Personal expenses features link to staging.expensify.com, not a discerning UseDot page](https://expensify.slack.com/archives/C036QM0SLJK/p1722950142293849?thread_ts=1722950065.680559&cid=C036QM0SLJK) - [PR](https://github.com/Expensify/Web-Expensify/pull/43026#issue-2451477637)

- [x] [error message colour improvements](https://expensify.slack.com/archives/C036QM0SLJK/p1722950192922099?thread_ts=1722950065.680559&cid=C036QM0SLJK) - [PR](https://github.com/Expensify/Web-Expensify/pull/43026#issue-2451477637)

- [x] [Marketing: we don’t mention Oracle NetSuite and here as one of our most popular integrations](https://expensify.slack.com/archives/C036QM0SLJK/p1722950511648049?thread_ts=1722950065.680559&cid=C036QM0SLJK) - [PR](https://github.com/Expensify/Web-Expensify/pull/43026#issue-2451477637)

- [x] [Missing Github logo](https://expensify.slack.com/archives/C036QM0SLJK/p1722950231399239?thread_ts=1722950065.680559&cid=C036QM0SLJK) - [PR](https://github.com/Expensify/Web-Static/pull/150) 

- [x] [Console error when entering in a phone number. Seems to still work though, I got the magic code on SMS. (This is a phone number that has an account already).](https://expensify.slack.com/archives/C036QM0SLJK/p1722951577844989?thread_ts=1722950065.680559&cid=C036QM0SLJK)

- [x] [The Back button doesn’t seem to respond reliably when clicked.](https://expensify.slack.com/archives/C036QM0SLJK/p1722951196821299?thread_ts=1722950065.680559&cid=C036QM0SLJK) - [PR](https://github.com/Expensify/Web-Expensify/pull/43107)

- [x] [Radio buttons appear on loading screen.](https://expensify.slack.com/archives/C036QM0SLJK/p1723032422063039) - [PR](https://github.com/Expensify/Web-Expensify/pull/43105)

**Comment by carlosmiceli** [comment]
Adding [this one](https://expensify.slack.com/archives/C036QM0SLJK/p1723032422063039) to the list above.

**Comment by carlosmiceli** [comment]
On my list.

**Comment by carlosmiceli** [comment]
Adding this one too to check in case it happens when we go full prod: https://expensify.slack.com/archives/C036QM0SLJK/p1723226584559989?thread_ts=1723147538.433649&cid=C036QM0SLJK

**Comment by carlosmiceli** [comment]
Also check that users get redirected to the new homepage that they used to sign up, after logging out.

**Comment by carlosmiceli** [comment]
This issue may be related to new homepage (maybe not), adding here to check: https://github.com/Expensify/Expensify/issues/419679

**Comment by carlosmiceli** [comment]
Should be done today with the last item, and a few more things I found to fix 🤞

**Comment by trjExpensify** [comment]
Just so I'm following, that's this one? 

>[Console error when entering in a phone number. Seems to still work though, I got the magic code on SMS. (This is a phone number that has an account already).](https://expensify.slack.com/archives/C036QM0SLJK/p1722951577844989?thread_ts=1722950065.680559&cid=C036QM0SLJK)

**Comment by carlosmiceli** [comment]
Correct! But I discovered a couple more issues while fixing that one.

**Comment by carlosmiceli** [comment]
Also need to check that this is fixed with the upcoming PR: https://expensify.slack.com/archives/C03U7DCU4/p1723665847506339

**Comment by carlosmiceli** [comment]
PR is ready, need to finish description and test steps. @trjExpensify question: should we wait until QA is over to go to 50%, or can we increase it as soon as it's merged?

**Comment by trjExpensify** [comment]
That PR has a fair few fixes, let's get it through QA and then bump to 50%.

**Comment by carlosmiceli** [comment]
The PR is officially ready for review/merge: https://github.com/Expensify/Web-Expensify/pull/43120

**Comment by trjExpensify** [comment]
All PRs in this issue are done now right, so we can close?

**Comment by trjExpensify** [comment]
>All PRs in this issue are done now right, so we can close?

I believe that's a yes, closing.
