### ISSUE TITLE
[$250]  Language - Message of added or invited user to "#admins" chat, doesn't get translated

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46960]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bellicoignacio+30@hotmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the https://staging.new.expensify.com/
website.
2. Tap on the avatar on the bottom of the screen.
3. Tap on "Preferences"
4. Tap on "Language"
5. Tap on "Spanish"
6. Tap on the arrow on the top left corner.
7. Tap on the chats icon on the bottom of the screen.
8. Check in the "#admins" chat preview, the language in which the invitation message is displayed.
9. Open the "#admins" chat.
10. Check the "New user added" message and the language in which is displayed.

## Expected Result:
When choosing Spanish as language, all the sections and chats information should be changed to that language.

Things that need to be changed:
**`Invited 1 user to Chat Report`**
<img width="474" alt="image" src="https://github.com/user-attachments/assets/94a8521f-2500-4f7b-8196-31a3bb021cb8">

We already have a translation of the `invited user to` [english](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/en.ts#L3819) into [spanish](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/es.ts#L3874) but that doesn't match the screenshot (no number) so seems like we might have this phrase somewhere else. 
- [ ] update the LHN to use this [English](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/en.ts#L3819) copy. Tbh neither I nor Ioni cannot find the copy in the screenshot in the database, maybe it was already updated?
- [ ] update [English copy](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/en.ts#L3819) to `invited member ${to}`
- [ ] update [Spanish copy](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/es.ts#L3874) to `miembro invitado ${to}`

**`added <email> as a user`**
- [ ] English should be updated to `added <email> as a member` 
- [ ] Spanish translation should be set to `agregó a <email> como miembro`

## Actual Result:
When choosing Spanish as language, the "#admins" chat, still displays information in English.
For example, the message "Invited 1 user to chat report", in the preview of the chat, is not translated as "Invitó a un usuario al chat."
And when opening the chat, the message "Added [ignaciodbellico@gmail.com](mailto:ignaciodbellico@gmail.com)
as a user" is also missing translation. The correct translation of this last sentence, would be "Agregó a [ignaciodbellico@gmail.com](mailto:ignaciodbellico@gmail.com)
como usuario."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6554265_1722044595083!34c88d80-f5b7-4c49-97d9-d846bf71d22b](https://github.com/user-attachments/assets/10d84b2c-0cf8-42b7-bb89-f60bfb698765)

https://github.com/user-attachments/assets/76544b0d-f8c0-4cc8-9fcb-ffbe811c46c2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010023a595aa275ac1</li>
        <li>Upwork Job ID: 1823685163547735883</li>
        <li>Last Price Increase: 2024-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103526301</li>
<li>nkdengineer | Contributor | 103526302</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by nkdengineer** [comment]
I don't think it's a bug because almost policy change log actions aren't translated.

**Comment by sonialiap** [comment]
@Expensify/design is this a feature or a bug?

**Comment by shawnborton** [comment]
Hmm @dylanexpensify is your system message project covering system message translations? Otherwise I'm not too sure what the current expected behavior is for this.

**Comment by dylanexpensify** [comment]
Ahh interesting, technically it was just for silencing them, but we did do some copy updates, and I wonder if maybe we missed this. @deetergp any ideas?

**Comment by sonialiap** [comment]
@deetergp bumping Dylan's question. We're wondering if this is expected or a bug

**Comment by deetergp** [comment]
That is not one of the messages we made translatable as a part of the Enhanced System Messages project, so this is not a bug, it is new functionality. For future reference, these were the actions we localized for the project: https://github.com/Expensify/App/blob/11af67b62a0a1ec905d7181ac82a183f1b03bd3b/src/languages/en.ts#L3770-L3799

**Comment by sonialiap** [comment]
Thanks Scott! 

Ok, so this is not a "bug" but may be a new feature request. Asking [in slack](https://expensify.slack.com/archives/C036QM0SLJK/p1723584191700699) if we want to do something about this

**Comment by sonialiap** [comment]
Things that need to be changed:
- English: change "user" to "member" in `added <email> as a member`
- Spanish: add a translation of `added <email> as a member` as `agregó <email> como miembro`
- Spanish: add a translation of `Invited 1 member to chat report` as `Invitó a 1 miembro al chat de informe`

Confirming translations in [slack](https://expensify.slack.com/archives/C21FRDWCV/p1723622254626849) ⏳

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When choosing Spanish as language, the "#admins" chat, still displays information in English.
For example, the message "Invited 1 user to chat report", in the preview of the chat, is not translated as "Invitó a un usuario al chat."
And when opening the chat, the message "Added ignaciodbellico@gmail.com
as a user" is also missing translation. The correct translation of this last sentence, would be "Agregó a ignaciodbellico@gmail.com
como usuario."

### What is the root cause of that problem?

This is a new feature request
### What changes do you think we should make in order to solve the problem?
For `Invited 1 member to chat report`, I'm unsure how we can display this message in the admin room.
1. We should have a util to get the translated message for `POLICYCHANGELOG_ADD_EMPLOYEE` action. 

```
function isPolicyChangeLogAddEmployeeMessage(reportAction: OnyxInputOrEntry<ReportAction>): reportAction is ReportAction<typeof CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.ADD_EMPLOYEE> {
    return isActionOfType(reportAction, CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.ADD_EMPLOYEE);
}

function getPolicyChangeLogAddEmployeeMessage(reportAction: OnyxInputOrEntry<ReportAction>): string {
    if (!isPolicyChangeLogAddEmployeeMessage(reportAction)) {
        return '';
    }

    const {email, role, name} = getOriginalMessage(reportAction);
    return Localize.translateLocal('report.actions.type.addEmployee', {email, name, role});
}
```

2. Then we will add a case in `ReportActionItem` to display the translated message for `POLICYCHANGELOG_ADD_EMPLOYEE` action

```
else if (action.actionName === CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.ADD_EMPLOYEE) {
    children = <ReportActionItemBasicMessage message={ReportActionsUtils.getPolicyChangeLogAddEmployeeMessage(action)} />;
}
```

https://github.com/Expensify/App/blob/55f67f53ca8ed8596943ce930ec10a3bd6f13427/src/pages/home/report/ReportActionItem.tsx#L654-L655
3. Add a case in `SidebarUtils` to display the translated message in LHN

```
else if (lastAction?.actionName === CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.ADD_EMPLOYEE) { 
     result.alternateText = ReportActionsUtils.getPolicyChangeLogAddEmployeeMessage(action);
}
```
https://github.com/Expensify/App/blob/55f67f53ca8ed8596943ce930ec10a3bd6f13427/src/libs/SidebarUtils.ts#L427-L428

4. Add a case in `ContextMenuActions` to copy the translated message to clipboard

```
else if (reportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.ADD_EMPLOYEE) { 
     setClipboardMessage(ReportActionsUtils.getPolicyChangeLogAddEmployeeMessage(reportAction));
}
```

https://github.com/Expensify/App/blob/55f67f53ca8ed8596943ce930ec10a3bd6f13427/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L460-L461

We can do the same way for other system actions that we need
### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment]
### `Invited 1 user to Chat Report`
<img width="474" alt="image" src="https://github.com/user-attachments/assets/94a8521f-2500-4f7b-8196-31a3bb021cb8">

We already have a translation of the `invited user to` [english](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/en.ts#L3819) into [spanish](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/es.ts#L3874) but that doesn't match the screenshot (no number) so seems like we might have this phrase somewhere else. 
- [ ] update the LHN to use this [English](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/en.ts#L3819) copy. Tbh neither I nor Ioni cannot find the copy in the screenshot in the database, maybe it was already updated?
- [ ] update [English copy](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/en.ts#L3819) to `invited member ${to}`
- [ ] update [Spanish copy](https://github.com/Expensify/App/blob/f2dad3a524b408f45dd74ea2c49b2c70015b2f38/src/languages/es.ts#L3874) to `miembro invitado ${to}`

### `added <email> as a user`
- [ ] English should be updated to `added <email> as a member` 
- [ ] Spanish translation should be set to `agregó a <email> como miembro`

**Comment by sonialiap** [comment]
Decreasing price since this is a simple copy change, making sure a translation exists, and a little bit of searching to confirm where the old translation is coming from. Details [here](https://github.com/Expensify/App/issues/46960#issuecomment-2288509737)

**Comment by nkdengineer** [comment]
@ZhenjaHorbach I updated my [proposal](https://github.com/Expensify/App/issues/46960#issuecomment-2288328709).

**Comment by sonialiap** [comment]
@ZhenjaHorbach sounds good 👍

**Comment by nkdengineer** [comment]
@sonialiap please give me translations for 2 cases above

**Comment by sonialiap** [comment]
@nkdengineer 
English - `updated the role of <email> from "<role>" to "<role>"` 
Spanish - `actualicé el rol de "<role>" a "<role>"`

English - `removed <role> <email>` 
Spanish - `eliminado <role> <email>`

user - should be changed to `member` in English. `miembro` in Spanish
admin - `administrador` in Spanish

**Comment by sonialiap** [comment]
@zanyrenney I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for build

**Comment by nkdengineer** [comment]
> Decreasing price since this is a simple copy change, making sure a translation exists, and a little bit of searching to confirm where the old translation is coming from. Details https://github.com/Expensify/App/issues/46960#issuecomment-2288509737

@zanyrenney This issue not only did a simple change translation but also updated copy case, LHN case, and side bar util case and fixed for some other messages. See the PR for more [details](https://github.com/Expensify/App/pull/47475). Can you please update the price to the default price, thanks.

**Comment by zanyrenney** [comment]
I'm unassigning as Sonia came back a few days ago, so you shouldn't need my help here! She has more context on the payment being changed so will leave that convo to her! :)

**Comment by sonialiap** [comment]
Hi team, I agree that it makes sense to update the price to the default since this issue ended up growing 👍 

Automation didn't run, but the deploy happened 3 weeks ago so I'm issuing payment!

Payment summary:
- @ZhenjaHorbach $250 - paid in upwork ✔️ 
- @nkdengineer $250 - paid in upwork ✔️
