### ISSUE TITLE
Analytics event `SWITCH_REPORT` overload

### ISSUE THREAD

**Issue by kacper-mikolajczak** [Expensify/App#46965]
### Problem

The `SWITCH_REPORT` analytics event is currently overloaded which yields incorrect/unreadable monitoring results.

Further discussion available [here](https://expensify.slack.com/archives/C05LX9D6E07/p1722451784265129)

**Comment by rojiphil** [comment]
@mountiny The PR for this issue was reviewed and merged over a month ago. Does this qualify for payment here?

**Comment by mountiny** [comment]
@rojiphil From what I can see there was no testing on the PR and so also no recordings on the checklist. I think this one would not apply and we should have skipped the C+ step
