### ISSUE TITLE
[HIGH] [Advanced Approval Workflows] Incorrect Onyx updates when calling CreateApprovalWorkflow

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#46968]
# Problem
When calling `CreateApprovalWorkflow` for the first time, the server is responding with two Onyx updates for the workspace's approval mode.

![image](https://github.com/user-attachments/assets/8ccf70b1-4091-4ef7-beb6-23d1aa3f16fc)

## Why this is a problem
The workspace should already be set to BASIC approval mode, and is only being switched to ADVANCED, so there should be no update which is setting the approval mode to BASIC. This can create inconsistencies with the frontend or a flash of incorrect settings in extreme cases.

# Solution
Debug the API command to find why the multiple events are created and stop it

cc @blazejkustra

**Comment by tgolen** [comment]
I confirmed that this happens in my local environment ✅

**Comment by tgolen** [comment]
@blazejkustra I found out what the issue is. I am not sure if this is an edge case we want to support (cc @JmillsExpensify)

Reproduction steps:
1. Create a workspace
2. Add two members to the workspace
3. Enable approval workflows
4. There will be the default approval workflow where everyone submits to the default approver (the policy owner)
5. Add a new approval workflow where a member submits to the default approver (the policy owner)

That last step doesn't really make sense... I think we are supposed to filter out the default approver from the list of people you can select? Otherwise, you're creating a workflow that's exactly the same as the default workflow.

**Comment by blazejkustra** [comment]
> I think we are supposed to filter out the default approver from the list of people you can select? Otherwise, you're creating a workflow that's exactly the same as the default workflow.

I'm not sure if this was discussed anywhere yet, but it makes sense to me. In other words we should filter out the defalt approver **but only when selecting the first approver for a workflow**, does it make sense?

**Comment by tgolen** [comment]
That makes sense to me, yeah. Everyone is already submitting to that person already.

**Comment by tgolen** [comment]
I'll let @JmillsExpensify chime in though.

**Comment by JmillsExpensify** [comment]
Great catch. That also makes sense to me.

**Comment by tgolen** [comment]
OK, sounds like this can be closed then and the fix will be implemented on the frontend in the currently working PR.

**Comment by blazejkustra** [comment]
Fixed here: https://github.com/Expensify/App/pull/46798/commits/54453fbd4e5bda9fcce26b56059620b01cdf5d5b
