### ISSUE TITLE
[HOLD for payment 2023-08-23] Group chat - Unable to search for members when inviting group members

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a group chat.
3. Click on the chat header.
4. Click Members.
5. Click Invite member.
6. Search with a valid term.

## Expected Result:
The results are not filtered. Nothing happens after searching for a member.

## Actual Result:
The relevant results will come up.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/772a3be9-b923-4df4-a132-4bb621f38c3d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by trjExpensify** [comment]
I can repro this, not responding to the input at all:

https://github.com/user-attachments/assets/0c9a36fc-19b5-4213-af98-8a250eef45bf


Looking at the deploy checklist, thinking maybe https://github.com/Expensify/App/pull/46409? @TMisiukiewicz @adhorodyski @mkhutornyi?

**Comment by trjExpensify** [comment]
FWIW, from testing this it seems isolated to group chat > members > invite members and the bug is not on production.

**Comment by marcochavezf** [comment]
> Looking at the deploy checklist, thinking maybe https://github.com/Expensify/App/pull/46409?

Git bisect led me to the same PR https://github.com/Expensify/App/pull/46409, creating a revert PR in a moment

**Comment by trjExpensify** [comment]
It's a pretty big PR that. Do we know why there's a problem here with the groups members page only? I'm wondering if we want to get a fix up for that, instead of a full revert.

**Comment by trjExpensify** [comment]
In fact, I think we should probably not block on this. The perf gains in the core flows (start chat, submit expense etc) aren't worth reverting for this bug in the groups members page which aren't really utilised much right now. 

>Removing getSearchText speeds up creating option list by around 40%. In the context of a trace provided for a linked issue, it reduces accumulated createOption time from 5.7s to 4s (~42% improvement)

So maybe we demote, and @adamgrzybowski @TMisiukiewicz can look into the fix as a `Daily`?

**Comment by TMisiukiewicz** [comment]
@trjExpensify I'll take care of it today 👍

**Comment by adamgrzybowski** [comment]
@trjExpensify me or the other Adam? 😄 @adhorodyski

**Comment by trjExpensify** [comment]
Adam H, my bad!

**Comment by adhorodyski** [comment]
haha sure thing, please see https://github.com/Expensify/App/pull/47051 - I believe this should be enough to avoid reverting:)

**Comment by TMisiukiewicz** [comment]
PR open ✅

**Comment by stephanieelliott** [comment]
PR is on staging!

**Comment by stephanieelliott** [comment]
This was deployed to prod on the 16th per https://github.com/Expensify/App/issues/47356 -- updating with payment labels!

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @TMisiukiewicz no payment due (agency)
 - Contributor+: @hoangzinh $250 via Upwork - I extended an offer, please accept when you get a chance! https://www.upwork.com/nx/wm/offer/103711752
 
 Upwork job is here: https://www.upwork.com/jobs/~01377f35a0f0d576f7

**Comment by stephanieelliott** [comment]
Thanks @hoangzinh, all paid!
