### ISSUE TITLE
Expense - New line marker doesn't disappear after viewing it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46988]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** Yokabdk+new16@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Click on the plus icon on the LHN (FAB button)
4. Click on split expense
5. Enter any amount
6. Input an account or user you have not contacted previously and click the split expense button
7. Observe that the newline marker will disappear once you opened the chat
8. Click on any other chat
9. Go Online
10. Click on the user you have split expense with from the LHN and view the message
11. Repeat step 8 and 10 3 times or more
12. Observe the newline marker will not disappear

## Expected Result:
The new line marker should disappear when you open the chat more than once

## Actual Result:
The new line marker does not disappear after user navigated to chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e086362a-51e7-4922-af2a-6c61531f650a

![Bug6554607_1722079113559!bug_9_sc](https://github.com/user-attachments/assets/f0ac879e-852c-48b6-80e1-a83f51df1b70)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by alexpensify** [comment]
I'll add this to my testing list

**Comment by alexpensify** [comment]
I was OOO on Friday and catching up, I'll review this one soon.

**Comment by alexpensify** [comment]
No update yet

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
Other GHs have been a priority.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate this one. 

--- 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!
