### ISSUE TITLE
[HIGH] [Advanced Approval Workflows] Server only returns generic errors when calling SetWorkspaceApproval commands

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#46986]
# Problem
When calling `Create/Update/RemoveWorkspaceApproval`, if there is a server error (like wrong parameters), the server always responds with a generic "there was an error" error.

## Why this is important to solve?
It is difficult to diagnose issues on the frontend.

# Solution
Have Web-Expensify pass the full error through in the API response

cc @blazejkustra

**Comment by tgolen** [comment]
# Daily Update
- I created a [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/43041) to improve the error messages

![image](https://github.com/user-attachments/assets/8d4c4154-d81a-49a6-9c57-2cf9a7040770)


### Next Steps
- @srikarparsi review and merge the PR
- @blazejkustra give it a try on the frontend once it's deployed to staging

#### ETA
- Merged today, Aug 7
- Deployed to staging tomorrow, Aug 8

**Comment by blazejkustra** [comment]
Let me know once it's on staging @tgolen 👀

**Comment by tgolen** [comment]
It's on staging now 👍 I'm going to go ahead and close this out.
