### ISSUE TITLE
[Awaiting Payment] [$250] [QBO Export] #admins QBO sync error message displays as a report export error

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#46985]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @arosiclair 
**Slack conversation:** N/A

## Action Performed:

**Prerequisites**

- Collect workspace with an admin and member
- Setup QBO integration connection

**Steps**

1. Log into QBO and disconnect the Expensify app (Menu > Apps > Overview > Expensify 3-dot menu > Disconnect)
2. Log into NewDot as the admin
3. Avatar > Workspaces > {QBO workspace} > Accounting > QBO > 3-dot menu > Sync Now
4. View `#admins` room for the workspce

## Expected Result:
A message is posted notifying about a sync failure

## Actual Result:
A message is posted about an export failure

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1137" alt="Screenshot 2024-08-07 at 12 03 05 PM" src="https://github.com/user-attachments/assets/c136faf8-b9cc-47ce-ada5-2f98d8a540a5">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by arosiclair** [comment]
This was a side effect of https://github.com/Expensify/App/issues/42923. We're displaying all `INTEGRATIONSMESSAGE` actions using copy for report export errors, but these actions should be generic and are used for both export and sync errors.

We'll need to fix this either by just rendering the `message` straight from the DB (English only) or adding new specific action types for export and sync errors. I'll start a discussion about it before moving forward.

**Comment by arosiclair** [comment]
> We'll need to fix this either by just rendering the message straight from the DB (English only)

Actually on further investigation, the message posted to the DB is also formatted as an export error so this won't work. So adding a new type of action for sync failures looks to be the only option. Posted a proposal [here](https://expensify.slack.com/archives/C036QM0SLJK/p1723062180519939).

**Comment by arosiclair** [comment]
Alright we'll be moving forward with the proposal

> Add a new INTEGRATIONSYNCFAILED action instead that displays the error with the correct copy. For now, it'll only be used to post sync errors to the #admins room and wouldn't appear anywhere in OldDot.

**Comment by arosiclair** [comment]
Posted 3 PRs for this
- https://github.com/Expensify/Auth/pull/12028
- https://github.com/Expensify/Web-Expensify/pull/43149
- https://github.com/Expensify/App/pull/47510

**Comment by muttmuure** [comment]
Being worked on

**Comment by arosiclair** [comment]
https://github.com/Expensify/App/pull/47510 is code complete just waiting on deploys for the other PRs

**Comment by arosiclair** [comment]
https://github.com/Expensify/App/pull/47510 is in review

**Comment by hungvu193** [comment]
I think this issue is ready for payment. It was deployed to production 2 weeks ago

**Comment by muttmuure** [comment]
$250 - for @hungvu193

**Comment by trjExpensify** [comment]
Why isn't this closed out yet, @muttmuure?

**Comment by muttmuure** [comment]
@hungvu193 needs to request payment in ND, this was in my monthlies for some reason

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
