### ISSUE TITLE
[Payment Due 09/16] [$250] Dupe detection - Merchant field shows (none) instead of blank when (none) is selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Submit an expense with no merchant and description.
4. Submit another expense with the same amount, and with merchant and description.
5. Go to the transaction thread of the second expense (Step 4).
6. Click Review duplicates.
7. Click Keep this one (any).
8. During the review, select (none) for Merchant and None for Description.
9. Proceed to confirmation page.

## Expected Result:
Merchant field should be empty since none is selected.
## Actual Result:
Merchant field shows (none) when (none) is selected, while Description field is empty when None is selected.

## Workaround:
Unknown 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/7814aaab-d69c-4d19-905d-b2c005355917

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194455fbb3684c1f1</li>
        <li>Upwork Job ID: 1823630303854706776</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103626733</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment]
I believe we need to have something in for merchant, otherwise an error is thrown, so this isn't a bug

**Comment by dylanexpensify** [comment]
Ah, good catch @Krishna2323

**Comment by dylanexpensify** [comment]
Forgot to hit external.

**Comment by eVoloshchak** [comment]
@Krishna2323's proposal LGTM, both solutions are equivalent, I think we should proceed with the main one (update  [condition in ReviewMerchant.tsx](https://github.com/Expensify/App/blob/6a6c242e79bb930b58146cb3e31f74d4e1fa0840/src/pages/TransactionDuplicate/ReviewMerchant.tsx#L24))

🎀👀🎀 C+ reviewed!

**Comment by dylanexpensify** [comment]
pending deploy and regression

**Comment by Beamanator** [comment]
Ooh yep i see your code in prod - https://github.com/Expensify/App/blob/06b41bf5aa6a798ae115a12d1c8abacdc96a0f01/src/components/ReportActionItem/MoneyRequestView.tsx#L545

**Comment by Beamanator** [comment]
cc @dylanexpensify - looks like payment is due here - there was an automation problem 😓

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor: @Krishna2323 $250 via Upwork
Contributor+: @eVoloshchak $250 via NewDot

Please apply/request!

**Comment by dylanexpensify** [comment]
Done

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
