### ISSUE TITLE
[Search v2.1] Adding semicolon to search filter leads to page not found

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#46993]
Coming from [here](https://github.com/Expensify/App/pull/46799#issuecomment-2270045899), adding a `;` to the keyword search filter leads to a page not found. 

cc @289Adam289

**Comment by ikevin127** [comment]
We're awaiting for a volunteer to take on this issue, given that https://github.com/Expensify/App/pull/46799 was merged.

**Comment by ikevin127** [comment]
Still awaiting for a volunteer to take on this issue, given that https://github.com/Expensify/App/pull/46799 was merged.

**Comment by 289Adam289** [comment]
I think this [pr](https://github.com/Expensify/App/pull/47328) from [issue](https://github.com/Expensify/App/issues/47095) will solve this problem.

**Comment by luacmartins** [comment]
Ah yea, I'll close this issue in favor of https://github.com/Expensify/App/issues/47095
