### ISSUE TITLE
Track expense - Unable to upload receipt to track expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46991]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Go to workspace chat
4. Click + > Track expense > Manual
5. Submit a track expense without receipt
6. Go to transaction thread
7. Upload a receipt
8. Note that the receipt cannot be uploaded
9. Dismiss the error
10. Click on the preview in main chat to go to transaction thread
11. Note that the header shows [Deleted report]
12. Upload a receipt again
13. Dismiss the error
14. Now the receipt shows a green thumbnail
15. Click on the receipt
16. Note that the receipt shows an attachment icon

## Expected Result:
User should be able to upload a receipt to track expense

## Actual Result:
User is unable to upload a receipt to track expense. Error shows up when uploading receipt to track expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a95dd8dc-fdbf-4d62-a737-bf917603c7ad

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by twisterdotcom** [comment]
Haven't gotten round to testing this yet.

**Comment by twisterdotcom** [comment]
Sorry, I still want to test this some more because I can't really get my head around the steps.

**Comment by twisterdotcom** [comment]
Unable to reproduce:

https://github.com/user-attachments/assets/37d7f3be-dcee-436b-b869-b83fa075a11e
