### ISSUE TITLE
Delete GitHub Actions workflow tests

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#47010]
## Problem

We added Github Action tests in https://github.com/Expensify/App/issues/13604, and while most of the problems presented in the original issue are true, we are not getting a ton of value out of the tests at the moment. We write lots of little workflow bugs that are not caught by the tests and have to spend a lot of time keeping them working. This tradeoff does not seem worth it anymore.

## Solution
* Delete the `workflow_tests` directory
* Delete the `testGithubActionsWorkflows.yml` file
* Delete the `workflow-test` script in `package.json`

**Comment by roryabraham** [comment]
PR merged. Thanks @AndrewGable
