### ISSUE TITLE
[$250] [OldDot Rules Migration] Expense report rules

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#47014]
# Part of the OldDot Rules Migration project

**Main issue:** https://github.com/Expensify/Expensify/issues/413886

# Feature Description

![2024-08-07_13-57-29](https://github.com/user-attachments/assets/895badfb-76b0-4bbb-8b2e-01fef7a5c86a)
![2024-08-07_14-35-32](https://github.com/user-attachments/assets/940b1609-f0c3-462c-b96f-f65ccd69a88a)
![2024-08-07_14-39-03](https://github.com/user-attachments/assets/82c165cd-270e-4f78-af53-d34be0ae8874)
![2024-08-07_14-36-27](https://github.com/user-attachments/assets/f4b43875-2596-401e-ae5c-16d6c11eccd8)
![2024-08-07_14-36-21](https://github.com/user-attachments/assets/2caf60f7-4900-400a-887b-041857720c48)
![2024-08-07_14-36-13](https://github.com/user-attachments/assets/4dad4a8f-23d8-4376-8421-c4650ef5e449)
![2024-08-07_14-35-47](https://github.com/user-attachments/assets/6deefdd6-440f-427b-b7eb-9438be533d8a)

**High Level Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.m0kga74f5qa8

**Detailed Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.dnpn3lehspjl

# Manual Test Steps

TBD

# Automated Tests

TBD
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844160179253102195</li>
        <li>Upwork Job ID: 1844160179253102195</li>
        <li>Last Price Increase: 2024-10-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by BrtqKr** [comment]
Hey, I'm from SWM, I'd like to take over this issue, would you please assign me?

**Comment by marcaaron** [comment]
Assigned!

**Comment by garrettmknight** [comment]
@BrtqKr when do you expect to make progress on this one?

**Comment by BrtqKr** [comment]
@garrettmknight, the functionality in the PR is ready, we're waiting to merge [the PR with enabling expense rules for the workspace](https://github.com/Expensify/App/pull/47083) before both sections to limit the diff. After that I'll record the videos and pass it further

**Comment by DylanDylann** [comment]
@garrettmknight Please grant me access to these docs. Thanks
https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.m0kga74f5qa8
https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.dnpn3lehspjl

cc @marcaaron

**Comment by marcaaron** [comment]
What's your email?

**Comment by DylanDylann** [comment]
Ah sorry. My email: dylandylan9112@gmail.com

**Comment by DylanDylann** [comment]
@marcaaron This is ready for payment. Could you please assign a BZ to handle payment? 🙏

**Comment by marcaaron** [comment]
@VictoriaExpensify can you help pay @DylanDylann and then close this out after? It's done and just waiting for payment.

**Comment by VictoriaExpensify** [comment]
Hey @DylanDylann - I've sent you a job offer, can you please accept so I can pay you? https://www.upwork.com/nx/wm/offer/104347866

**Comment by DylanDylann** [comment]
@VictoriaExpensify Sure I did accept

**Comment by VictoriaExpensify** [comment]
Contributor: @BrtqKr - No payment required, Contractor
Contributor+: @DylanDylann paid $250 via Upwork
