### ISSUE TITLE
[$250] [OldDot Rules Migration] Tag settings: Billable

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#47019]
# Part of the OldDot Rules Migration project

**Main issue:** https://github.com/Expensify/Expensify/issues/413886

# Feature Description

![2024-08-07_14-29-22](https://github.com/user-attachments/assets/298f84ba-20ba-41c6-b41b-43e7c6affe16)
![2024-08-07_14-43-12](https://github.com/user-attachments/assets/167b28a3-75d8-479b-bd0b-eb4b54f8d73c)

**High Level Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.ccvrv3l199wn

**Detailed Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.gwil1p66dsz0

# Manual Test Steps

TBD

# Automated Tests

TBD
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844002446135821210</li>
        <li>Upwork Job ID: 1844002446135821210</li>
        <li>Last Price Increase: 2024-10-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by Guccio163** [comment]
Hi, I'm Wiktor Gut from SWM and I'd like to take this issue!

**Comment by marcaaron** [comment]
**From the Doc:**

>Workspaces track billable expenses, though invariably this use case is coupled with tags. After all, if you’re going to bill someone for some amount, you need to know who that bill actually goes to.

>Billable defaults will become part of Control Rules moving forward, in line with Collect Plan v2. So keeping this toggle in tag Settings allows us to make Track billable expenses accessible by all workspaces.

>To assuage any potential concerns about the visibility of the billable expenses, we’ll **update the explanatory text for Tags within More features.** This ensures billable expenses are still on the front lines of feature enablement.

**From the Detailed section:**

>We can access the Tag settings by navigating to `/settings/workspaces/{policyID}/tags/settings`. The “Track billable expenses” toggle switch will be enabled based on `policy.disabledFields.defaultBillable`. If `true` this toggle would be disabled and enabled when `false`.

When the user toggles off we will call the `DisablePolicyBillableExpenses` API command which takes no parameters and uses this as the policy new values:
```
{
    disabledFields: {
        defaultBillable: true,
    }
}
```

And we can set it back with this command:

**Command name:** `SetPolicyBillableMode`
**API request Parameters:** `policyID: String`, `defaultBillable: Bool`
**New values:**

Call `SetPolicyBillableMode` with current `defaultBillable` value and this will toggle the other way.

```
{
    defaultBillable: false, // Default is non-billable when enabled
    disabledFields: {
        defaultBillable: false,
    }
}
```

Add `<Switch />` to `<TagSettingsPage />`, update the text, call the APIs to update the `disabledFields.defaultBillable`.

**Comment by situchan** [comment]
C+ payment is remaining

**Comment by marcaaron** [comment]
Sorry bout that. Have been OOO. @johncschuster can help!

**Comment by johncschuster** [comment]
@situchan bump!

**Comment by situchan** [comment]
Applied thanks

**Comment by johncschuster** [comment]
@situchan Offer sent!

**Comment by johncschuster** [comment]
# Payment Summary:
Contributor+: @username paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~021844002446135821210)! ~Please apply~ PAID! 🎉
