### ISSUE TITLE
Track engagement with onboarding tasks in Full story

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#47017]
Problem: All chats, and all tasks have the exact same URLs (https://new.expensify.com/r/*). As a result, in Fullstory, there's really no way to track who engages with what task or study it as a journey to see drop off - where - and to what etc. In our database we can tell if a task is completed, but not if it is clicked into or totally ignored. Effectively, we do not know how to improve this. Should we change where we show the task itself (i.e. no one is clicking in), or make the content of the task better (I.e. people are clicking in but just hopping off), so on and so forth.

Solution: Not sure what the cleanest solution here is. This is not a UI element to watch, so I can't imagine we would just add an custom attribute to some HTML element of an onboarding task? Another alternative is to send a [FS custom event](https://developer.fullstory.com/destinations/v1/webhooks/list-event-types/custom-event/) when a task is clicked into? 

@dubielzyk-expensify @danieldoglas @rushatgabhane curious for your thoughts.

**Comment by dubielzyk-expensify** [comment]
I don't have access to custom elements, but is there a way we can use the video source as a way to track this?

I got ideas of how to improve the tasks etc, but I still wanna see more recordings. Having gone through loads of them in FullStory I've only found 1 so far that interacts with the checklist and they seem to be using it somewhat successfully. [Link to that recording](https://app.fullstory.com/ui/o-1WN56P-na1/session/6050171702816768:(5553256296951808!8131763452441752279(8126076360406467166(0:0:5268:5761:5761:35249):4697742224613531162(0:0:0:7073:7294:7852:10622:10622:10701:13644:13894:13894:14392:19644:19804:19804:21156:22357:25616:25714:25714:33073:33231:33231:34376:36726:36791:36791:38761:38906:38906:40536:41688:41780:41780:47762:47916:47916:49321:49389:49389:53595:53752:53752:54981:56574:57704:57796:57796:64621:64773:64773:66037:67629:68562:68649:68649:94473:94579:94579:98147:98215:98215:101228:101394:101394:102182:105773:109499:109527:115067:116764:116771:116973:118065:118273:119044:119102:119108:119108:121560:121634:121634:125936:126007:126007:128455:128627:128627:134488:136812:136864:141130:141168:141168:146032:147582:148027:148027:180704)))).

**Comment by dubielzyk-expensify** [comment]
Okay this isn't perfect, but so far I can find people who interact with the Guided Setup video by filtering users who:

`Clicked` `CSS selector` is `button[aria-label="guided-setup-track-personal-v2.mp4"][role="button"][type="button"]`. 

I've [created a segment](https://app.fullstory.com/ui/o-1WN56P-na1/segments/YMgrrjHSxrvg/people/0?completeSessions=false) for these users.

**Comment by anmurali** [comment]
Do you think there's still value in building support for custom events though? @dubielzyk-expensify

**Comment by dubielzyk-expensify** [comment]
Yeah. If we can understand that they've "Watched" the checklist then we can get a better understanding
