### ISSUE TITLE
[OldDot Rules Migration] Individual expense rules

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#47013]
# Part of the OldDot Rules Migration project

**Main issue:** https://github.com/Expensify/Expensify/issues/413886

# Feature Description

![2024-08-07_13-49-38](https://github.com/user-attachments/assets/c5804955-9879-4c6b-adcc-50f1e0d99931)
![2024-08-07_14-32-32](https://github.com/user-attachments/assets/c2b01d18-ac03-48ec-8428-85949a8fa0cf)
![2024-08-07_14-32-32](https://github.com/user-attachments/assets/2c359eb2-29e5-4ba3-b177-86bd6029a9f7)
![2024-08-07_14-33-01](https://github.com/user-attachments/assets/9e0294fe-de47-4e6b-bfe4-7b0afaf772de)
![2024-08-07_14-33-07](https://github.com/user-attachments/assets/e21cb031-166a-4e21-8e52-f11955a55796)
![2024-08-07_14-33-13](https://github.com/user-attachments/assets/d5b42a3b-e249-419f-9f0c-710f030aa6e0)
![2024-08-07_14-33-21](https://github.com/user-attachments/assets/394b509c-5dd8-4b62-9ce6-2fb1e72eea5b)
![2024-08-07_14-33-30](https://github.com/user-attachments/assets/0d6ed628-bf74-45df-a866-5ee52b2a09bb)

**High Level Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.ycyp9y4tlna4

**Detailed Section:** https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit#bookmark=id.ore5lrt7u7r

# Manual Test Steps

TBD

# Automated Tests

TBD

**Comment by WojtekBoman** [comment]
@Expensify/design

I have one question about the Billable default page. Currently we don't have a pattern in the app when we select an element from the list and we have to additionally confirm our selection by clicking a button. It causes some issues with setting the background color of the selected item. Usually we don't need to change the background color of the selected item because we close the page once we select an option. I'm wondering if we need this submit button on this page. If so, I'll try to find a solution, but if not, I'll implement it the same as other pages with `SelectionList`. I'm attaching a video with the current implementation and examples of other pages using `SelectionList`.


https://github.com/user-attachments/assets/654245ee-35f1-4abb-8bef-2e6b07af1977

https://github.com/user-attachments/assets/9aa9bc12-b79d-4b76-ab62-584438c41708

**Comment by WojtekBoman** [comment]
@Expensify/design @marcaaron @JmillsExpensify 

Do we know what the maximum possible length of numbers that can be entered into these inputs should be?

<img width="829" alt="Screenshot 2024-08-20 at 17 26 36" src="https://github.com/user-attachments/assets/e4e311cb-013f-479a-962a-5ab87ffa91b0">

**Comment by marcaaron** [comment]
>I'm wondering if we need this submit button on this page.

This is a good observation. I'm wondering the same thing now. 😄 

>Do we know what the maximum possible length of numbers that can be entered into these inputs should be?

On the API side there is no maximum. Most people will put reasonably low values because larger values are impractical i.e. it would be the same as putting any large number after a point. If we want to impose something we could use the `DISABLED_MAX_EXPENSE_VALUE`, but not sure we need to do anything here tbh.

**Comment by WojtekBoman** [comment]
> @Expensify/design
> 
> I have one question about the Billable default page. Currently we don't have a pattern in the app when we select an element from the list and we have to additionally confirm our selection by clicking a button. It causes some issues with setting the background color of the selected item. Usually we don't need to change the background color of the selected item because we close the page once we select an option. I'm wondering if we need this submit button on this page. If so, I'll try to find a solution, but if not, I'll implement it the same as other pages with `SelectionList`. I'm attaching a video with the current implementation and examples of other pages using `SelectionList`.
> 
>  Screen.Recording.2024-08-20.at.17.19.50.mov 
>  Screen.Recording.2024-08-20.at.17.19.12.mov

@shawnborton @dannymcclain Could you take a look at it when you have some time?

**Comment by shawnborton** [comment]
In the page you are referencing for billable default, you are right in that we probably don't need a Save button - we can just allow the selection of the list item to actually select something and change the form.

That being said, we keep running into small bugs where a selected item does not have a correct background color. So whether we save it immediately or not, we really need to make sure all selected list items use the appropriate background color. Let me know if that helps clear things up!
