### ISSUE TITLE
[HOLD for payment 2024-08-19] HybridApp fails to deploy due to `react-native-image-size` Gradle dependencies

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#47011]
# Problem

Slack thread: https://expensify.slack.com/archives/C07J32337/p1723060725518079

HybridApp deploys are failing with:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-image-size'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-image-size:classpath'.
      > Could not find com.android.tools.build:gradle:2.3.3.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
          - https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
        Required by:
            project :react-native-image-size
```

# Solution

Seems like we are trying to get a Gradle version that is not available. This problem previously occurred [here](https://github.com/Expensify/App/issues/21336) and was fixed in a similar way to how we fixed it last time by @roryabraham in [this PR](https://github.com/Expensify/react-native-image-size/pull/5)

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by roryabraham** [comment]
Did that gradle version change in our fork fix this problem?

**Comment by marcaaron** [comment]
It did, but a new problem manifested. See @Julesssss notes starting [here](https://expensify.slack.com/archives/C07J32337/p1723083067413309?thread_ts=1723060725.518079&cid=C07J32337).

**Comment by johncschuster** [comment]
I don't see an external contributor involved in the linked PR. @marcaaron, am I missing them?

**Comment by marcaaron** [comment]
This was internal.
