### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250]  iOS - Distance split - App crashes after opening split distance expense receipt

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #42302
**Version Number:** 9.0.18.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** New Feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0708pm1e@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Navigate to a group chat
3. Tap + > Split expense > Distance
4. Enter the start and finish viewpoints and complete creating a split expense
5. Open the receipt
## Expected Result:
The receipt is displayed
## Actual Result:
The app crashes
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/a2d05b19-5c6e-4d92-bee8-e1b93e2d37b5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bdf11a6c8415e801</li>
        <li>Upwork Job ID: 1821474729087191120</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103446274</li>
<li>dominictb | Contributor | 103446277</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by techievivek** [comment]
@shubham1206agra You meant @dominictb right? I can't see a proposal by user @cretadn22 😄

**Comment by techievivek** [comment]
The fix has been CPed to staging, going to ask QA to retest this.

**Comment by m-natarajan** [comment]
Issue fixed.

https://github.com/user-attachments/assets/7dc80f7b-7bde-474e-a4f6-65221c936a6a

**Comment by joekaufmanexpensify** [comment]
Checklist complete. All set to issue payment on Monday. We need to pay: 

- @dominictb - $250 for PR via upwork. 
- @shubham1206agra - $0 (no payment due here as you were C+ on the PR that introduced the regression).

**Comment by joekaufmanexpensify** [comment]
Ah, okay. I saw you listed in the assignees of the PR, but see now that was just as a commenter. Adjusted checklist!

**Comment by joekaufmanexpensify** [comment]
All set to issue payment here!

**Comment by joekaufmanexpensify** [comment]
@shubham1206agra could you please accept the offer so we can pay you?

**Comment by joekaufmanexpensify** [comment]
@dominictb $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@shubham1206agra $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
