### ISSUE TITLE
[P2P Distance] - Group chat avatar changes after splitting distance expense with existing users

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47020]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #42302 
**Version Number:**  9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** New Feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** [applausetester+kh050806@applause.expensifail.com](mailto:applausetester+kh050806@applause.expensifail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense > Distance.
3. Enter waypoints > Next.
4. Select two existing users.
5. Split the distance expense.
## Expected Result:
The group chat style will remain the same (avatar and report details RHP name).
## Actual Result:
The group chat style changes after splitting the distance expense. Avatar changes to stacked avatars style and report details RHP name is "chat report".## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/8bb17253-3db4-4df9-9653-2169f68ffaee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
We think that this bug might be related to #vip-split

**Comment by mountiny** [comment]
Does not feel like a deploy blocker as this is a new feature and UX issue.

@neil-marcellini do you want to take this one over as its related to the distance split project. It looks like as if we are creating the old group chat style in the backend instead of the new GroupDM

**Comment by marcaaron** [comment]
>It looks like as if we are creating the old group chat style in the backend instead of the new GroupDM

We should definitely not be doing that. 

Taking a quick look but seems like maybe this issue should be labeled `Internal` and assigned to @neil-marcellini.

**Comment by Christinadobrzyn** [comment]
Just checking in on this - @neil-marcellini do you have an update? thank you!

**Comment by neil-marcellini** [comment]
I got a fix up for review!

**Comment by neil-marcellini** [comment]
Head's up, I'll be working 50% for the rest of this week and next 🌲

**Comment by Christinadobrzyn** [comment]
[PR](https://github.com/Expensify/Web-Expensify/pull/43140) in staging - getting close!

**Comment by neil-marcellini** [comment]
Deployed to prod, all done
