### ISSUE TITLE
Invoice - Send invoice option is present when the workspace has not enabled Invoices feature

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47023]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #46567 
**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** New Feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Delete all workspaces if there is any workspace.
3. Create a new workspace.
4. Go to Workspace settings > More features.
5. Note that Invoices feature is not enabled.
6. Go to FAB.
## Expected Result:
Send invoice option will not show up if the workspace has not enabled Invoices feature.
## Actual Result:
Send invoice option is present when the workspace has not enabled Invoices feature.
The option is also present in invoice room when the workspace has not enabled Invoices feature.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/6b040925-5e91-4594-86c0-d1acfac85a76

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rezkiy37** [comment]
It is expected behavior for now. Please read this - https://github.com/Expensify/App/pull/46567#discussion_r1699942442.

cc @madmax330

**Comment by MonilBhavsar** [comment]
Okay, thanks for clarifying @rezkiy37! Do we have another issue to clean that up or should I assign you to this issue?

**Comment by MonilBhavsar** [comment]
I think we should be able to use this, if we don't have any and link it to the tracking

**Comment by rezkiy37** [comment]
I want to close this issue. Let me create a clean-up issue tomorrow 🙂

**Comment by MonilBhavsar** [comment]
cc @madmax330 ^

**Comment by MonilBhavsar** [comment]
Thanks! Closing this out then
