### ISSUE TITLE
[Awaiting Payment 26th August] [$250] Bump Onyx to 2.0.64

### ISSUE THREAD

**Issue by kacper-mikolajczak** [Expensify/App#47044]
### Details
After recent Onyx improvements, we can update library to take advantage of them.

**Comment by trjExpensify** [comment]
Awaiting a regression period here like normal, right?

**Comment by mountiny** [comment]
Yes

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @ZhenjaHorbach for the C+ review 

Offer sent!

**Comment by trjExpensify** [comment]
Awesome, paid!
