### ISSUE TITLE
[$250] Search filters - Scrolling behavior after selecting currency and category is different

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47058]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when executing PR :** https://github.com/Expensify/App/pull/46566
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Navigate to https://staging.new.expensify.com/search/filters
via deep link.
3. Tap Currency.
4. Scroll down and select a currency.
5. Note that the list does not scroll up after selecting a currency.
6. Tap Category.
7. Scroll down and select a category.
8. Note that the list scrolls up after selecting a category.
9. Repeat the steps above on web.

## Expected Result:
The scrolling behavior in filters should be the same after selecting currency and category.

## Actual Result:
On Android and iOS,
In Step 5, the list does not scroll up after selecting a currency.
In Step 8, the list scrolls up after selecting a category.

On web, mweb and desktop app,
In Step 5, the list scrolls up without animation after selecting a currency.
In Step 8, the list scrolls up with animation after selecting a category.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/62fd61af-3096-401e-841d-4f8f8ffe13bd

https://github.com/user-attachments/assets/4c649652-36c4-475a-9d1d-933f13fa259c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f10b9412daa7bb88</li>
        <li>Upwork Job ID: 1821575106946228601</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103492530</li>
<li>dominictb | Contributor | 103492533</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by RachCHopkins** [comment]
Has the automation failed again @carlosmiceli? Is this done and ready to be paid?

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @dominictb paid $250 via Upwork
- Contributor+: @dukenv0307 paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~01f10b9412daa7bb88)

**Comment by RachCHopkins** [comment]
Contributors have been paid, the contracts have been completed, and the Upwork post has been closed.
