### ISSUE TITLE
[$250] All - Approvers - Admin cannot approve a report instead of Approver

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47052]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4825180
**Email or phone of affected tester (no customers):** fischer9966+080724aadm@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition NewDot:
1. Create admin account with Gmail
2. Create Collect workspace, set Workflows to enabled
3. Invite Employee and Approver with Gmail accounts to this workspace
4. Enable Approvals in Workflows and set Approver as Approver
5. Enable Workflows > Delay submissions and set it to Manually

Precondition OldDot:
1. Login to OD as admin
2. Go to Collect workspace > Reimbursements
3. Select "Indirect"

Steps NewDot:
1. Go to staging.new.expensify.com or open App
2. Login as the employee and submit a report
3. Login as the approver and approve and then unapprove the report
4. Login as the admin
5. Navigate to the report that was unapproved in Step 2
6. Approve the report as the admin

## Expected Result:
Verify that Admin is able to approve the report instead of Approver

## Actual Result:
Admin cannot approve a report instead of Approver. Approve button is not available if Admin is not an Approver.

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9f4c8693-9325-4546-8766-6bc6a5fab698

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165312f1362565eae</li>
        <li>Upwork Job ID: 1822013832781582950</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin cannot approve a report instead of Approver
### What is the root cause of that problem?
We are only checking if the user is manager. There is no check for admin.
https://github.com/Expensify/App/blob/9c7c4a1cb9405f64c31c03c4f1fa33c0c041dac0/src/libs/actions/IOU.ts#L6771
### What changes do you think we should make in order to solve the problem?

We can add check for admin.
```
return (isCurrentUserManager || isAdmin) && !isOpenExpenseReport && !isApproved && !iouSettled && !isArchivedReport;
```
### What alternative solutions did you explore? (Optional)

**Comment by MuaazArshad** [comment]
No, that is not the case on my side. I can set the approver in oldDot.
<img width="1357" alt="Screenshot 2024-08-12 at 6 57 01 PM" src="https://github.com/user-attachments/assets/7bdf3878-fe90-4bd1-a1ae-4a44570d5fd3">

**Comment by MuaazArshad** [comment]
No, I can approve report submitted by any employee in workspace with no errors. This is working just fine for both approver and admin.
<img width="928" alt="Screenshot 2024-08-12 at 8 54 46 PM" src="https://github.com/user-attachments/assets/29d85707-dad4-47bb-a655-0c1cba151a93">
<img width="980" alt="Screenshot 2024-08-12 at 8 55 15 PM" src="https://github.com/user-attachments/assets/fe5e66e0-7aba-4c0f-98e9-22f7dd75dd49">

**Comment by flodnv** [comment]
Do you know if this option shows up on OldDot in this scenario? I am unsure, I wanted to test but I am stuck at `set Approver as Approver` because the UI is broken as of now (reported internally for now).

**Comment by flodnv** [comment]
>Login as the approver and approve and then unapprove the report

Does this also need to be done on OldDot? 😕

**Comment by flodnv** [comment]
There is no approve button for admins on OldDot

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/b0666089-0542-4ea6-8744-471b181b9eb8">

The backend code enforces that only a manager of a report can approve it. This is not a bug, it's a feature.
