### ISSUE TITLE
[$375] Categories - Selection mode remains after deleting all the categories

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47057]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Categories.
3. Long press on the category.
4. Select all categories and bulk delete them.

## Expected Result:
Selection mode will exit after deleting all the categories.

## Actual Result:
Selection mode remains after deleting all the categories.
The same happens in Tags and Report fields page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c72ed0e0-17fb-436e-b675-6296c4fa9658

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166d8a6d63f2da84e</li>
        <li>Upwork Job ID: 1824175618088532405</li>
        <li>Last Price Increase: 2024-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103778761</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
I was OOO on Friday but will add this to my testing list.

**Comment by alexpensify** [comment]
@ntdiary when you get a chance, can you please review whether one of these proposals will fix this issue? Thanks!

**Comment by alexpensify** [comment]
@dylanexpensify - any feedback from the curator's perspective for these questions, or should I take this to the big slack room? Thanks!

**Comment by alexpensify** [comment]
## Next Steps

The proposals are under review and being discussed. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by Julesssss** [comment]
> could you confirm whether the selection mode should be exited when the user is offline and deletes all categories? Personally, I think it should exit as well. 🤔

I agree with you here. 

Solution looks good, lets implement 👍

**Comment by alexpensify** [comment]
Catching up from being OOO, @dominictb, any update on when the PR will be ready for review? Thanks!

**Comment by alexpensify** [comment]
PR is still going through the review process.

**Comment by alexpensify** [comment]
Weekly Update: Waiting for this one to go to production

**Comment by alexpensify** [comment]
Now we wait for this one to go through automation. It went into production yesterday.

**Comment by Julesssss** [comment]
> @Julesssss Should we increase the issue's price based on [comment](https://github.com/Expensify/App/pull/48547#issuecomment-2340722502)?

Last I remember was that we would do this separately, did this change?

**Comment by Julesssss** [comment]
Thanks, I'd forgot the details.

**Comment by alexpensify** [comment]
Automation didn't kick in, so I'll need to manually work on the payment process and will remember to check the payment amount is now $375.

**Comment by alexpensify** [comment]
Payouts due: 09-27-2024

- [ ] Contributor: $375 @dominictb 
- [ ] Contributor+: $375 @ntdiary - please submit a request in Chat

Upwork job is [here](https://www.upwork.com/jobs/~021824175618088532405).

**Comment by alexpensify** [comment]
Closing - I've completed the payment process via Upwork for @dominictb and @ntdiary will submit a request in Chat.

**Comment by JmillsExpensify** [comment]
$375 approved for @ntdiary
