### ISSUE TITLE
Login - Concierge chat is not opened when signing in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47066]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+6d99vx@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
3. Reload the page making sure that you are on staging.new.expensify.com
2. Sign in with a new applause.expensifail account

## Expected Result:
Concierge chat opens

## Actual Result:
Black page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/523527c8-ef4b-4b26-b8ea-ffa24427e16c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by dangrous** [comment]
aw man, this comes from one I reviewed. https://github.com/Expensify/App/pull/46623 / https://github.com/Expensify/App/issues/44600

Not a backend blocker though.

We might want to revert, unless there's an obvious fix.

**Comment by HezekielT** [comment]
@dangrous I think it's better to completely revert the original PR as I was not able to fix this issue without reintroducing the original issue.

**Comment by HezekielT** [comment]
@dangrous Here is the link to the PR #47099

**Comment by dangrous** [comment]
Got it, merging and will request a CP to staging

**Comment by dangrous** [comment]
The revert is confirmed to have fixed this! Closing.
