### ISSUE TITLE
[Hold for payment 2024-08-28] [$250] [P2P Distance] Split - Tax rate and Tax reclaimable are empty in the transaction thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Track tax is enabled.
- Tax rate and Tax reclaimable are filled in for the distance rate.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Split expense > Distance.
4. Split a distance expense using the distance rate from the precondition.
5. Click on the split preview.
6. Note that Tax rate and Tax reclaimable are filled in.
7. Go to the transaction thread of the split expense.

## Expected Result:
Tax rate and Tax reclaimable have the correct info in the transaction thread.

## Actual Result:
Tax rate and Tax reclaimable are empty in the transaction thread.
## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/79544b96-21f6-43e6-89e3-6a19c9f281cb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d1cb3838667f8739</li>
        <li>Upwork Job ID: 1821526714732909137</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103456830</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-split

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tax code and amount is empty when creating split distance request.

### What is the root cause of that problem?
When we are creating a split distance, it will call `createSplitsAndOnyxData`.
https://github.com/Expensify/App/blob/0926267c22e50e68b52c055dacc3af775235ccd4/src/libs/actions/IOU.ts#L5020-L5040

However, we don't pass the tax code and amount to `createSplitsAndOnyxData`.

### What changes do you think we should make in order to solve the problem?

Pass both tax code and amount to `createSplitsAndOnyxData`.
```
const {
    splitData,
    splits,
    onyxData: splitOnyxData,
} = createSplitsAndOnyxData(
    ...,
    CONST.IOU.REQUEST_TYPE.DISTANCE,
    taxCode,
    taxAmount,
);
```

**Comment by twisterdotcom** [comment]
@mountiny is this right? I think we could just assign @bernhardoj now if so. I don't think we need to block a deploy with this as it's not an error, it's just unexpected behavior from a less frequently used flow.

**Comment by situchan** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/47062#issuecomment-2275667115) looks good.
🎀👀🎀 C+ reviewed

**Comment by mountiny** [comment]
Sounds good

**Comment by bernhardoj** [comment]
PR is ready

cc: @situchan

**Comment by JmillsExpensify** [comment]
Awaiting payment summary

**Comment by twisterdotcom** [comment]
Payment Summary:

- @bernhardoj paid $250 via newDot requests (Contributor)
- @situchan paid $250 via Upwork [here](https://www.upwork.com/nx/wm/workroom/38075897/overview) (C+)

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
