### ISSUE TITLE
[$250] Report fields - Disabled in ND fields are not deleted in OD

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47070]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3155317
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions: Control workspace with all types of Report fields exist.

1. Navigate to More Features in workspace settings
2. Disable the Report Fields feature
3. Confirm the modal so we disable the feature
4. Login in OD
5. Go to settings for report fields on the control policy

## Expected Result:
All the text and date-type report fields have been deleted.
The list-type report field has not been deleted but all its options have been disabled

## Actual Result:
All the text and date-type report fields are present.
The list-type report field has not been deleted and enabled.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/adeb2f68-0aa9-44c5-8289-a3fd2a6c6f97

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e99bc608dbc484a</li>
        <li>Upwork Job ID: 1823257878081571939</li>
        <li>Last Price Increase: 2024-08-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment]
Nice, confirming today!

**Comment by dylanexpensify** [comment]
Forgot to hit external!

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by mountiny** [comment]
Focusing on closing out wave-collect I will see if I can squeeze this one in though

**Comment by mountiny** [comment]
Same update as above

**Comment by mountiny** [comment]
aiming to have PR merged this week

**Comment by dylanexpensify** [comment]
Sounds good!

**Comment by mountiny** [comment]
I have been and still am working on a fire fix so this one is coming after the fix is implemented

**Comment by mountiny** [comment]
Struggling to close the loop on this one with deployer chore, fire fighting and api monitoring chore. Still on top of my list after the most urgent tasks

**Comment by mountiny** [comment]
Same

**Comment by mountiny** [comment]
Patiently waiting in top of my backlog

**Comment by dylanexpensify** [comment]
Sounds great!

**Comment by mountiny** [comment]
Same, had audit task assigned which took some time

**Comment by mountiny** [comment]
Workspace feeds taking most of my time

**Comment by mountiny** [comment]
Started to work on this one, I need to add tests

**Comment by mountiny** [comment]
Merged 🎉

**Comment by dylanexpensify** [comment]
Wahooo!

**Comment by dylanexpensify** [comment]
Deployed to prod on Sept 19

**Comment by mountiny** [comment]
So I believe we can close now
