### ISSUE TITLE
[$250] Desktop - Unable to log out as user remains logged in after logging out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify desktop app
2. Log out if logged in
3. Log in to New Expensify on Chrome
4. After login, refresh the page on Chrome
5. Click Open New Expensify
6. On desktop app, sign out

## Expected Result:
App will redirect to login screen after signing out

## Actual Result:
App is unable to sign out. User remains signed in after signing out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/16600567-b736-407a-a8f0-3a18930f9eb8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01263806ac93543c43</li>
        <li>Upwork Job ID: 1821608786482827857</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by neil-marcellini** [comment]
Looking now

**Comment by neil-marcellini** [comment]
After log out there's a call to sign in with the short lived auth token. I'm guessing this has something to do with the transition flow.
![image](https://github.com/user-attachments/assets/2bed2234-4437-44a0-90d3-c8a41f8f7748)

**Comment by neil-marcellini** [comment]
Actually, there's a chance this could be backend so re-applying the label until I learn more.

**Comment by neil-marcellini** [comment]
I can't reproduce on dev either 😢. Maybe it's fixed? Hard to say. I'm thinking we'll have to compare the console and network logs to see if we can spot a difference between staging and production, or dev.

**Comment by neil-marcellini** [comment]
Ah yep that did it, nice! All done.


https://github.com/user-attachments/assets/2082217a-34c1-467b-8522-f1d355448d27
