### ISSUE TITLE
[HOLD for payment 2024-10-10] [$125] The continue button has some extra bottom padding on the page we enter name after selecting the onboarding option.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47087]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723118907902239

## Action Performed:

1. login with new account
2. On onboarding modal, select something else
3. Observe the extra bottom padding

## Expected Result:
No extra bottom padding for `Continue` button

## Actual Result:
Extra bottom padding observed for `Continue` button
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/user-attachments/assets/f65e7dfe-6a6f-4fd8-907e-849f8a6a1727" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/ac255cb0-688a-486e-88b5-a2d412ccf51f" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112ea720a987767e3</li>
        <li>Upwork Job ID: 1821573061746870352</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103622446</li>
<li>BhuvaneshPatil | Contributor | 103622448</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by joekaufmanexpensify** [comment]
Price updating as this is a pretty minor issue

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Continue button in on-boarding forms has extra space at bottom when viewed on devices with small screen width

### What is the root cause of that problem?
The extra margin bottom is being added when we have footer content passed in `FormProvider` component
https://github.com/Expensify/App/blob/cc4626f393daf4171a0bccc190be39132ac021ea/src/components/FormAlertWithSubmitButton.tsx#L82

Although `OfflineIndicator` renders when we are online null but margins is still applied because it's truthy value.
```tsx
const PersonalDetailsFooterInstance = <OfflineIndicator />;
```

### What changes do you think we should make in order to solve the problem?
There are two approaches for solving this - 
1. Remove the line where we pass `FooterContent` to `FormProvider` and add that component outside form provider - 
```tsx
<FormProvider
                    style={[styles.flexGrow1, isMediumOrLargerScreenWidth && styles.mt5, isMediumOrLargerScreenWidth ? styles.mh8 : styles.mh5]}
                    formID={ONYXKEYS.FORMS.ONBOARDING_PERSONAL_DETAILS_FORM}
                    validate={validate}
                    onSubmit={completeEngagement}
                    submitButtonText={translate('common.continue')}
                    enabledWhenOffline
                    submitFlexEnabled
                    shouldValidateOnBlur={false}
                    shouldValidateOnChange={shouldValidateOnChange}
                    shouldTrimValues={false}
                >
                 {....}
                </FormProvider>
                {isSmallScreenWidth && PersonalDetailsFooterInstance}
```
This approach is being followed at other places in application.
<details>
<summary>Create room page</summary>

<img width="535" alt="Screenshot 2024-08-08 at 10 17 44 PM" src="https://github.com/user-attachments/assets/ba599bdd-0061-40f4-a1e7-e65c3cda8b35">

</details>

2. This approach is simpler to follow and with less changes.
If we change `PersonalDetailsFooterInstance` to 
```tsx
const PersonalDetailsFooterInstance = OfflineIndicator({});
```
It will work as expected. Reason being function will return `null` in case we are online, so `footerContent` will be falsy value and extra margin not added. If we are online, it will return the content of component.

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/4893113c-bed6-4bf3-955e-4545f1ca7656

</details>

Also we need to verify if removing footer content and then changing to offline throttling shows indicator as mentioned in other proposal because I didn't get the expected result.

### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment]
Proposal updated,

change online to offline at one place

**Comment by joekaufmanexpensify** [comment]
@allgandalf think there will be an update today?

**Comment by BhuvaneshPatil** [comment]
@allgandalf Can you please verify if removing 
https://github.com/Expensify/App/blob/cc4626f393daf4171a0bccc190be39132ac021ea/src/pages/OnboardingPersonalDetails/BaseOnboardingPersonalDetails.tsx#L149
Line is working.
Because I tried and it didn't show the indicator

**Comment by BhuvaneshPatil** [comment]
https://github.com/user-attachments/assets/e4508cba-35cb-44ef-a6e4-58b584b8ad99


Please verify changes I have shown are correct. It didn't show for me

**Comment by BhuvaneshPatil** [comment]
Tried directly passing the style - 

https://github.com/user-attachments/assets/a6d973d0-129f-42ab-8d5e-187beac2c094

That didn't work either

**Comment by BhuvaneshPatil** [comment]
@allgandalf  Checked on simulator, it is working. Interesting though why it's not working on mweb.

**Comment by joekaufmanexpensify** [comment]
Waiting for @aldo-expensify sign off on proposal

**Comment by aldo-expensify** [comment]
It would have been nice if the screenshots in the issue showed what padding this is talking about. The pictures are the same. 
Is this something that happens only in IOS native? the issues says that, but then @BhuvaneshPatil says this doesn't work in mweb.... so is it only happening in IOS native or is it happening in all mobile screens? Can we get a more accurate description of the issue?

**Comment by joekaufmanexpensify** [comment]
@aldo-expensify I updated the screenshots in OP of the issue, I think applause incorrectly added the same one twice from the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1723119059586919?thread_ts=1723118907.902239&cid=C049HHMV9SM). 

@allgandalf do you agree that the selected proposal is not working on all platforms?

**Comment by aldo-expensify** [comment]
> @aldo-expensify I updated the screenshots in OP of the issue, I think applause incorrectly added the same one twice from the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1723119059586919?thread_ts=1723118907.902239&cid=C049HHMV9SM).

Thanks!

**Comment by joekaufmanexpensify** [comment]
Great. TY!

**Comment by joekaufmanexpensify** [comment]
As an fyi, going to be OOO from tomorrow - Monday. Not adding another BZ since nothing should be needed during that time. Please ask in slack if something comes up.

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by aldo-expensify** [comment]
Thanks for rechecking everything @allgandalf

**Comment by aldo-expensify** [comment]
@BhuvaneshPatil when do you think you can have a PR up?

**Comment by BhuvaneshPatil** [comment]
Feeling under the weather for 2-3 days. Please give me sometime. I will raise the PR.

**Comment by aldo-expensify** [comment]
No worries, just asking, this is a low priority issue, take your time until you feel better :)

**Comment by joekaufmanexpensify** [comment]
PR in progress

**Comment by BhuvaneshPatil** [comment]
@aldo-expensify I am good now. Thank you for asking. I will be raising the PR by tonight

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by BhuvaneshPatil** [comment]
Pr under review

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
@allgandalf could you handle BZ checklist so I can prep for payment?

**Comment by joekaufmanexpensify** [comment]
Ah, yeah that is fair. We can probably skip here.

**Comment by joekaufmanexpensify** [comment]
@BhuvaneshPatil $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@allgandalf $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
