### ISSUE TITLE
[HOLD for payment 2024-08-29] [$125] Expense - Mark as cash and Review duplicates buttons have no spacing between each other

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47089]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4835412
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in to [applausetester+pendingreceipt@applause.expensifail.com](mailto:applausetester+pendingreceipt@applause.expensifail.com)
3. Submit two same scan receipts that will match with card transaction, or go to https://staging.new.expensify.com/r/4109811016204814
4. Go to the transaction thread after scanning is complete

## Expected Result:
Mark as cash and Review duplicates buttons will have some spacing between each other

## Actual Result:
Mark as cash and Review duplicates buttons have no spacing between each other

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/user-attachments/assets/045efd17-d96f-43cf-8525-32de753f9104

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017310aba17e7a4229</li>
        <li>Upwork Job ID: 1823604679203469131</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103524496</li>
<li>dominictb | Contributor | 103524500</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by c3024** [comment]
>We can add margin-right style for mark as cash

When there is only `Mark as cash` button without the `Review duplicates` button, the `Mark as cash` button is shifted by this extra margin which will be consistent.

>margin-left style for review duplicate

I think this looks the simplest and fixes it well.

@dominictb 's [proposal here](https://github.com/Expensify/App/issues/47089#issuecomment-2276199677) looks good to me!

🎀 👀 🎀 C+ Reviewed

**Comment by arosiclair** [comment]
> > margin-left style for review duplicate
> 
> I think this looks the simplest and fixes it well.

Agreed just use `margin-left`. [spacing.ml1](https://github.com/Expensify/App/blob/1f07cb5c60add125109aecc70db301d5a05d64a0/src/styles/utils/spacing.ts#L146-L148) should be fine.

I'm reducing the bounty on this to $125 since this is just a spacing change.

**Comment by kadiealexander** [comment]
@c3024 don't forget about the checklist :)

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #44025 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/2528eac0ae335a5ef2a52e16ed40f197b2bf2e61#r146001158
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression test proposal

1. Submit two scan receipts with same details to a workspace. The scan receipt should match with card transaction
2. Go to the transaction thread after scanning is complete
3. Verify that: "Mark as cash" and "Review duplicates" buttons have gap between each other
