### ISSUE TITLE
Stop sending the "Welcome to Expensify" email to new accounts created by being invited to a workspace

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#47080]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** latest
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** No
**Email or phone of affected tester (no customers):** Test accounts: 
c.dobrzyn+8765@gmail.com // c.dobrzyn+9876543@expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/414680
**Issue reported by:** Christina / Daniel
**Slack conversation:** https://expensify.slack.com/archives/C041MSTR8J1/p1722536450608919

## Action Performed:

1. As an Admin with a Control workspace on Expensify Classic, sign in to www.expensify.com
2. Go to Settings > Workspaces > [click the workspace name] > Members > invite
3. Invite someone who doesn't have an Expensify account already. 

## Expected Result:

This is a feature request based on the [Slack discussion](https://expensify.slack.com/archives/C041MSTR8J1/p1722536450608919), so we'd like to:

- Stop sending the "Welcome to Expensify" email to any new account invited to a workspace. 

## Actual Result:

When you are invited to a workspace an account is created for you and you get two emails right away: 

- The **"Welcome to Expensify"** email from Concierge that links to the Concierge DM on new.expensify.com. This email causes confusion, because it pushes people into NewDot when their company isn't using that product yet and thus a workspace to submit expenses to doesn't exist, the admins are unfamiliar with the UI the invited member is experiencing etc. 

- The **"You've been added to the "X" workspace in Expensify!"** email that contains the welcomeNote the admin inviting the member has chosen to include (or the default set). The links in this email have better routing logic already, depending on if the workspace invite was via NewDot or OldDot, and if the workspace is NewDot compatible yet. 

## Workaround:
N/A
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/a43572ee-b3a1-412b-8417-5e2426e8f577">
<img width="1602" alt="image" src="https://github.com/user-attachments/assets/7b384577-8630-4fbb-a2cf-ed571d12a8aa">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment]
Posted in wave-collect to find a volunteer - https://expensify.slack.com/archives/C036QM0SLJK/p1723141430569869

**Comment by Christinadobrzyn** [comment]
looking for a volunteer

**Comment by tgolen** [comment]
I have a look at this one.

**Comment by Christinadobrzyn** [comment]
Thanks for picking this up Tim! 

Oh that is a good question. This GH is specific to removing the 'welcome message' email. 

Are you referring to this welcome message in NewDot? 

<img width="1687" alt="image" src="https://github.com/user-attachments/assets/f221414c-b8bd-466e-b318-b5263a450bef">

I think we would want to keep this message since it introduces a NewDot user to Concierge. But would that be a problem to keep? 

cc @danielrvidal @trjExpensify

**Comment by tgolen** [comment]
OK, it really becomes very difficult to drop the email but keep the report comment, unfortunately. The code that sends the email for all report comments is very far removed from the code that invites someone to a workspace, so it becomes very complex to pass this flag through many different layers of code. My main concern is that we are interrupting a flow that happens normally for 99% of report comments, to do something different for this very specific flow.

Stepping back for a quick sec:

> The "Welcome to Expensify" email from Concierge that links to the Concierge DM on new.expensify.com. This email causes confusion, because it pushes people into NewDot when their company isn't using that product yet and thus a workspace to submit expenses to doesn't exist, the admins are unfamiliar with the UI the invited member is experiencing etc.

> I think we would want to keep this message since it introduces a NewDot user to Concierge.

Are these two things kind of contradictory? If the user is not going to NewDot at all yet, then it doesn't matter if they have a message from Concierge visible in NewDot. Right?

To be clear, what I am proposing (and isn't too difficult) is:
- Remove the email AND the report comment in NewDot
- ONLY remove it for the flow when someone is invited into a workspace in OldDot

So, users that are invited to workspaces on NewDot, they would still get both the email and the report comment.

**Comment by trjExpensify** [comment]
Personally, I think we get rid of the message (which then gets rid of the
email fallback) in all workspace invite cases. I agree with Tim it’s
difficult to not do both given how the system works.

If we want to improve the “beginningOfChat” (I think that’s what it’s
called, can’t check on mobile) copy, so it’s a better introduction of
Concierge instead of just like “this is the beginning of your chat with
Concierge” and more directive of explaining it’s a support chat we can look
at that. @danielrvidal, what do you think?

*Tom Rhys Jones *
*Expensify*

**Comment by danielrvidal** [comment]
Yea, I think make sense. Let's remove from Conciegre UI as well for anyone being invited from a Classic workspace. As @trjExpensify suggested, I'll work with @jamesdeanexpensify to [get the beginningOfChatHistory updated](https://github.com/Expensify/App/issues/47427) for the concierge UI.

>Concierge chat 
> This is the beginning of your chat with Concierge, Expensify’s real-time support tool. 

Feel free to remove it for those users though @tgolen

**Comment by jamesdeanexpensify** [comment]
Should we go with:

> This is your chat with Concierge. Use it for 24/7 product support.

**Comment by jamesdeanexpensify** [comment]
Or a little more descriptive: 

> This is your chat with Concierge. Ask questions about Expensify and get 24/7 realtime support.

**Comment by tgolen** [comment]
OK, thanks all. I will move forward with just removing the whole message for the OldDot invite flow.

**Comment by jamesdeanexpensify** [comment]
FYI, I'll actually go with this copy, but let me know if anyone feels strongly otherwise:

> This is your chat with Concierge. Ask questions and get 24/7 realtime support.

**Comment by Christinadobrzyn** [comment]
Nice! The [PR](https://github.com/Expensify/Web-Expensify/pull/43177) is in staging! Thanks for pushing this out the door so quick @tgolen!

**Comment by tgolen** [comment]
# Weekly Update
- The [PR](https://github.com/Expensify/Web-Expensify/pull/43177) was merged and deployed to staging two days ago (as @Christinadobrzyn pointed out)

### Next Steps
- Nothing, just sit tight and wait for production deploy

#### ETA
- Deployed to production today, Aug 30

**Comment by tgolen** [comment]
# Weekly Update
- The [PR](https://github.com/Expensify/Web-Expensify/pull/43177) was deployed to production

### Next Steps
- Close this out

**Comment by Christinadobrzyn** [comment]
Thank you so much for taking this @tgolen! 

@danielrvidal I don't think there's any need for an announcement or anything to the team about this? Do you think we should announce something?

**Comment by danielrvidal** [comment]
You could announce something like this:

> Hey team, we should no longer be sending welcome emails from Concierge to new users being invited from workspaces **on Classic.** This was creating confusion for users who were being sent to NewDot by following the link in the invite email. This hopefully clears up a lot of confusion but let's still be on the look out for users in NewDot that we don't think should be in there!
