### ISSUE TITLE
[PAYMENT 2024-09-06] [$250] Android - Wallet - BA number in two lines is cut off at the bottom

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4836144
**Email or phone of affected tester (no customers):** fischer9966+080824aa@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: Android phone with horizontal screen resolution 1080 px - Eq Google Pixel 5

1. Open Android App
2. Login with any account
3. Go to Settings > Wallet
4. Add 2 bank account - 0000 and 1111 and set account 0000 as Default. Account number should occupy 2 lines.
5. Check that account is displayed correctly

## Expected Result:
Bank account occupying two lines is displayed correctly, all numbers are fully visible

## Actual Result:
Bank account occupying two lines is cut off at the bottom

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ba68578d-cf1f-458b-86a1-f1e18641eaff

![Bug6565304_1723099206613!Screenshot_20240808-012224](https://github.com/user-attachments/assets/6d580ab2-1c10-4c13-9ed0-5fc51697445d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127ebfac638cf5ec5</li>
        <li>Upwork Job ID: 1823557759281995585</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103603910</li>
<li>FitseTLT | Contributor | 103603915</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wallet - BA number in two lines is cut off at the bottom

### What is the root cause of that problem?
We have set a fixed height of the menu item here
https://github.com/Expensify/App/blob/d6f64eedc7750b6c7dd649dc1214bef939abbaa9/src/styles/index.ts#L3785-L3786
but when the default text is present for mobile the height is not enough
### What changes do you think we should make in order to solve the problem?

We have many options 
1. we can add the menu item height 
2. stop setting fixed height so that it is flexible
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
> @FitseTLT did you manage to reproduce the bug? If yes – which device did you use in the simulator?

I Did manage to reproduce it but it's not the device type that matters but the Accessibility > Text Size setting (You have to increase it a bit)
<img width="439" alt="Screenshot 2024-08-14 at 9 36 54 at night" src="https://github.com/user-attachments/assets/7bf7d20d-0bf6-415a-8873-e98ea61c0a71">
<img width="438" alt="Screenshot 2024-08-14 at 9 37 14 at night" src="https://github.com/user-attachments/assets/44327b76-ad04-4da2-a898-af6ace806143">

**Comment by shawnborton** [comment]
Hmm in the screenshots above, why aren't we truncating the "Account ending in..." line after 1 line as well? Can we first start there and see how it looks?

**Comment by shawnborton** [comment]
I think it makes more sense to truncate after 1 line here given the width constraints personally. Let's see if @Expensify/design agrees though!

**Comment by dannymcclain** [comment]
>I think it makes more sense to truncate after 1 line here given the width constraints personally.

I'm a little torn, because if we truncate we lose the only valuable info from that line of text (the last four digits). Personally I think it might make more sense to ditch the word `Account` in the line `Account ending in 0000`. The title of the card is `Bank accounts` so I'm wondering if

>**Plaid Checking**
>Ending in 0000

is enough info for the user to understand what we're talking about here. What do you think about that?

**Comment by shawnborton** [comment]
Big fan of that, I think that will save us a lot of room!

**Comment by strepanier03** [comment]
Looks like automation failed so I updated the title and set to Daily so I don't lose track of this one.

**Comment by strepanier03** [comment]
### Payment summary

- [x] $250 - @FitseTLT via Upwork (paid)
- [x] $250 - @paultsimura via Upwork (paid)

Thanks everyone!
