### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] [P2P Distance] Split - Participants amount displayed 0.00 briefly on confirmation screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47100]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18.3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+0808pm@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42302
## Action Performed:
1. Open the app and log in
2. Tap FAB > Split expense > Distance
3. Tap + > Split expense > Distance
4. Enter the start and finish viewpoints
5. Select a few participants and proceed to the confirmation screen

## Expected Result:
The correct participants amounts are displayed

## Actual Result:
0.00 is briefly displayed instead of the correct amount

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9171a2e7-027c-41eb-a00a-19ccb2a4ddd1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170f1a1791408f62b</li>
        <li>Upwork Job ID: 1821642103848571473</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103497363</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by neil-marcellini** [comment]
Not a blocker, it's behind the distance split beta.

**Comment by garrettmknight** [comment]
@parasharrajat can you give these proposals a look when you get a chance?

**Comment by jasperhuangg** [comment]
@Krishna2323's approach seems to be the simplest approach to fixing the issue, assigning them!

FYI I will be going OOO for the rest of the week, so we might need to bring in another internal engineer to help with PR reviews once the PR is done. cc @garrettmknight

**Comment by jasperhuangg** [comment]
I think our automation was broken for a while. This was deployed to production a while ago without any regressions.

@garrettmknight Do you mind paying out @Krishna2323 for implementing the solution to this issue and @parasharrajat for reviewing proposals/PRs? I think we can safely close out this issue after that.

**Comment by jasperhuangg** [comment]
@Krishna2323 Got it, thanks for the update

**Comment by garrettmknight** [comment]
Since we've removed the global create, I've tried to repro using split in the group chat. I can't really tell if it happens in iOS, there's some glitchy behavior, but I can't see if it's starting with 0 because it's too fast.

**Comment by garrettmknight** [comment]
It's a lot clearer on Android. @Krishna2323 @parasharrajat is the fix you're working on still applicable to the behavior even if it doesn't come from Global Create?
https://github.com/user-attachments/assets/1e963d88-4de5-4384-b252-57a66bb541a6

**Comment by garrettmknight** [comment]
**Payment Summary:**
- Contributor: @Krishna2323 $250 paid via upwork
- Contributor+: @parasharrajat $250 via NewDot

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
