### ISSUE TITLE
Receipt Scan - No “Receipt * Issue found' when change the amount of the card transaction

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47112]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/issues/44995
**Email or phone of affected tester (no customers):** applausetester+iz080824@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Press big plus sign > submit expense
3. Select Distance tab (from Manual | Scan | Distance)
4. Press Start and enter an address, eg 88 Kearny st. Then Press Finish and enter an address, eg, 1180 jackson st. And press Next
5. Select the workspace to submit to
6. Click Submit $XX button
7. Update the amount to $7 (you should see “Amount differs from calculated distance” violation under the amount field)
8. Click the blue link in the report header
9. Create the scan expense on the same workspace
10. Navigate to the expense report
11. Import a third party domain control card via OldDot
12. Find the card transaction in the workspace chat corresponding to the assigned employee, or visit the Search page and find the transaction by date.
13. Open the card expense
14. Change the amount of the card transaction to an amount higher than the original charge

## Expected Result:
User should see “Receipt * Issue found 🔴” above the receipt

## Actual Result:
"Receipt • Verified" is only present above the receipt.

Note: This issue when the receipt is not clear only

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9592c3c3-7c75-43e4-a974-c2b8e94ed071

https://github.com/user-attachments/assets/8946825d-4067-4273-9789-65edece1891b

![Screenshot (627)](https://github.com/user-attachments/assets/5385a933-5219-4f67-9465-16a5740e04cb)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by cead22** [comment]
Duplicate https://github.com/Expensify/App/issues/46791. Should be fixed by https://github.com/Expensify/App/pull/47094
