### ISSUE TITLE
[$250] Web - Dependent tag choices are cleared and actions are repeated when coming online

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47113]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
The issue was found when executing this PR https://github.com/Expensify/App/issues/44995#issue-2396295781
**Issue reported by:** Applause Internal Team

## Action Performed:
1. ND: Navigate to https://staging.new.expensify.com/
2. ND: Log in with a New Gmail account
3. ND: Create a workspace
4. ND: Switch to OD by navigating to Account settings - Cards & Domains
5. OD: Navigate to Settings - Workspaces - Group - Created workspace - Tags
6. OD: Enable "Use multiple levels of tags"
7. OD: Click on the "Import from Spreadsheet" button
8. OD: Uncheck "Are these independent tags?"
9. OD: Upload the attached CSV file
10. ND: Navigate to the workspace chat
11. ND: Go offline
12. ND: Navigate to Composers "+" button - Submit expense - Manual
13. ND: Input any amount and click on "Next"
14. ND: Set any value for "Merchant" and submit the expense
15. ND: Click on the created expense
16. ND: Click on "State" and select any value
17. ND: Click on "Region" and select any value
18. ND: Click on "City" and select any value
19. ND: Click on "City" again and click on the set value to clear it
20. ND: Go online

## Expected Result:
Changes made while offline should be displayed instantly when coming online.

## Actual Result:
Dependent tag choices are cleared and actions taken while offline are slowly repeated when coming online.

## Workaround:
Unknown
## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[Bug6565973_1723145169511!Dependent_tags_tags.csv](https://github.com/user-attachments/files/16553537/Bug6565973_1723145169511.Dependent_tags_tags.csv)

https://github.com/user-attachments/assets/31709e85-62a4-4b7c-82aa-8ee846db6e4a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100368f8944905925</li>
        <li>Upwork Job ID: 1823053155785640856</li>
        <li>Last Price Increase: 2024-09-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by cead22** [comment]
This looks like a legit issue related to offline handling of requests, but not related to https://github.com/Expensify/App/pull/45760 or https://github.com/Expensify/App/issues/44995

**Comment by miljakljajic** [comment]
Waiting for proposals

**Comment by miljakljajic** [comment]
@cead22 am I wrong thinking this could be handled externally?

**Comment by cead22** [comment]
I thought the same, but I could see how this might be a tricky issue to fix. Should we close it?

**Comment by d-wwei** [comment]
Contributor details
Your Expensify account email: wweijoin@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010b64a310e922c43e
