### ISSUE TITLE
[Workspace Feeds] Ensure the Card_Deactivate command sends correct onyx updates with update card state

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#47121]
We are using existing `Card_Deactivate` API command and auth command to deactivate cards from newDot. We need to update this command to send pusher updates when the card state changes

Related to https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.xvbueni56b

**Comment by trjExpensify** [comment]
Any core issues, pop em' in release 2. 👍

**Comment by trjExpensify** [comment]
The Auth PR linked to this hit prod earlier, we done here?

**Comment by mountiny** [comment]
I think so yeah
