### ISSUE TITLE
[HOLD for Payment 2024-09-06] [$500] [Performance] Create Onyx connection Manager

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#47143]
### Problem

A new connection is made to Onyx every time we subscribe to a Onyx key (by using Onyx.connect(), useOnyx() or withOnyx), even if we are subscribing to the same key e.g. a collection. When the Onyx data changes, we loop through each connection ( [here](https://github.com/Expensify/react-native-onyx/blob/main/lib/OnyxUtils.ts#L817) and [here](https://github.com/Expensify/react-native-onyx/blob/main/lib/OnyxUtils.ts#L605) ) and perform some heavy operations in order to prepare the data to send to all the subscribers listening to that key. This approach is inefficient as we need to build the same data countless times for every subscriber, leaving to the developer to build custom solutions in their codebase if they want to optimize and reuse the connections.

### Solution

Let’s reuse the connections automatically inside Onyx with the Onyx Connection Manager. This manager will take care of identifying and reuse the connections every time we have multiple subscribers to the same Onyx key with the same connect configuration. When the data changes we’ll only need to prepare the data one time and send to all the subscribers immediately instead of doing this operation for each one, saving memory, processing and reducing the overall JS overhead.

This solution [requires pratically no significant changes in E/App](https://github.com/Expensify/App/pull/44987) and will benefit both Onyx.connect() and useOnyx() subscribers. Unfortunately the withOnyx() HOC connects to Onyx in a different way than the first ones and therefore they can’t be reused in the same way, so they will function normally as it is today (one connection per subscriber).

With this solution applied to E/App, the average amount of connections will be reduced in about 30% :rocket: When the entire codebase is migrated from withOnyx() to useOnyx(), the expected reduction will be around 80-90% :exploding_head:

Before:
Opening a report: 1749 connections
Switching between reports: 4121 connections

After:
Opening a report: 1238 connections (-30%)
Opening a report (projection after migration from withOnyx() to useOnyx()): 340 connections (-80%)
Switching between reports: 2604 connections (-36%)
Switching between reports (projection after migration from withOnyx() to useOnyx()): 399 connections (-90%)

Here’s the [Onyx PR](https://github.com/Expensify/react-native-onyx/pull/567) and the [E/App PR](https://github.com/Expensify/App/pull/44987)!

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142380df7c5dd6bd5</li>
        <li>Upwork Job ID: 1823838590285150645</li>
        <li>Last Price Increase: 2024-08-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio - expert agency contributor - and I would like to work on this issue!

**Comment by codewaseem** [comment]
Also, I noticed sometimes the `withOnyx()` causes infinite re-renders.

**Comment by lschurr** [comment]
Is there an update on this issue @fabioh8010?

**Comment by fabioh8010** [comment]
@lschurr I'm going to check the reviews on the PR and open it tomorrow

**Comment by fabioh8010** [comment]
PR was opened!

**Comment by ikevin127** [comment]
♻️ Will start reviewing tomorrow (Pacific), will look at the code and also thoroughly test the in-app behaviour of the implementation in different scenarios.

**Comment by lschurr** [comment]
Any update on this one @ikevin127?

**Comment by ikevin127** [comment]
Almost done testing, will resume today and get back with the results!

**Comment by fabioh8010** [comment]
The [E/App PR](https://github.com/Expensify/App/pull/44987) is ready for testing, it's including the Onyx changes.

**Comment by ikevin127** [comment]
Dropped my test results so far all 🟢 **Passing**, see https://github.com/Expensify/App/pull/44987#issuecomment-2299987207 for details.
Moving forward I think the next thing to do is have an ad-hoc build of the E/App PR and have the QA team's results to go off and triage all found issues (if any) before moving forward with merging.

**Comment by mountiny** [comment]
We have merged and deployed this PR to staging. Investigating if the was any performance regression from this PR noticed

**Comment by ikevin127** [comment]
⚠️ We just got [confirmation](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q) on Slack that the [Deploy Checklist: New Expensify 2024-08-26](https://github.com/Expensify/App/issues/48035) which includes the PR of this issue was only deployed to **production** today in [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221). More context on why this happened can be found in [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1724866177581899) Slack thread and [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1725055726486309?thread_ts=1725050431.962859&cid=C01GTK53T8Q) Slack comment.

Given the context above, this issue should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from [Deploy Checklist: New Expensify 2024-08-28](https://github.com/Expensify/App/issues/48221).

cc @lschurr @mountiny

**Comment by mountiny** [comment]
Updated

$500 to @ikevin127

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @fabioh8010 (contractor - no payment needed)
- Reviewer: @ikevin127 $500 (to be paid [in Upwork](https://www.upwork.com/nx/wm/offer/103847245))

**Comment by ikevin127** [comment]
@lschurr Offer accepted, thank you!

**Comment by lschurr** [comment]
All set!
