### ISSUE TITLE
[$250]  IOU - Infinite spinner loading on Submit button when back online after adding stop offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47146]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4836952&group_by=cases:section_id&group_order=asc&group_id=296765
**Email or phone of affected tester (no customers):** gocemate+a885@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Start a distance request
2. Enter the address to the start e.g: "45n N Beach Rd, FL"
3. Click on add stop
4. Enter the address, e.g: "Beach Access Path, Sunny Isles Beach, FL"
5. Click Next button
6. Click Submit button
7. Go offline
8. Go to transaction thread page> Click on Distance> Add a stop point e.g: "Miami Beach"> Submit
9. Go back online
10. Verify the map does not shows the route
11. Click on Distance again

## Expected Result:
Map should show the route and Submit button should response

## Actual Result:
Map does not show the route when come back online, Submit button is irresponsible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d1c90d6d-7635-4216-b34b-c451f5f8399e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019eb0338dff8112cc</li>
        <li>Upwork Job ID: 1821982776695149158</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ZhenjaHorbach</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by neil-marcellini** [comment]
I'll see if I can reproduce on dev now and then start debugging.

**Comment by neil-marcellini** [comment]
Weird, I can't really reproduce on dev. Trying on staging. I think this was fixed somehow. I even tried to reproduce outside of the p2p distance beta, and I can't, so I'm going to close this out.


https://github.com/user-attachments/assets/6abd4bd8-8d0d-43a2-87bd-720dfd08d5b7
