### ISSUE TITLE
[$250] Web - Task – App logging out when leave thread in a new non-validated account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47155]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4836943
**Email or phone of affected tester (no customers):** ponikarchuks+208824@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as a new Gmail account, do not validate it.
3. Create a chat
4. Send a message in the chat
5. Reply in thread and send a comment
6. Click on the chat header and leave the thread

## Expected Result:
Main chat opens

## Actual Result:
App logging out

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f3d4ed2e-ade0-47ce-9469-e517242c6747

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c285e8464a196cb</li>
        <li>Upwork Job ID: 1827403668366705877</li>
        <li>Last Price Increase: 2024-08-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by IuliiaHerets** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by debragail** [comment]
Cannot recreate

**Comment by kevinksullivan** [comment]
unable to recreate
