### ISSUE TITLE
[$250] Expense-Skeleton shown below header after creating expense with violations offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47152]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/issues/44995
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: user created a workspace, enabled the "Members must tag all expenses" and "Use multiple level of tags" toggles, and added Independent ot Dependent tags in OD
1. Go to https://staging.new.expensify.com/
and log in
2. Go offline
3. Click on FAB and submit a manual expense without selecting tags to a workspace with dependent tags enabled
4. Navigate to the workspace chat
5. Open the expense report
6. Make a selection for required tags (Department, Region, Project)
7. Return online

## Expected Result:
There is no skeleton after returning online

## Actual Result:
Skeleton is displayed below header after returning online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e1d94669-2940-4ff6-b72b-7194a73f41f3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0161e7cb21c8a1e8cd</li>
        <li>Upwork Job ID: 1823406186287377629</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control

**Comment by cead22** [comment]
This looks like a legit issue related to offline handling of requests, but not related to https://github.com/Expensify/App/pull/45760 or https://github.com/Expensify/App/issues/44995. Offline handling of violations seems to be working well.

This could be related or similar to https://github.com/Expensify/App/issues/47113

**Comment by getusha** [comment]
Waiting for proposals.

**Comment by abekkala** [comment]
bumped slack for proposals

**Comment by codewaseem** [comment]
I could not reproduce this issue.

**Comment by VincentCorleone** [comment]
I could not find "Use multiple level of tags" toggles and could not reproduce this issue.

**Comment by getusha** [comment]
I will try reproducing this later today.

**Comment by abekkala** [comment]
@getusha do you have an update on reproducing?

**Comment by abekkala** [comment]
@getusha bumping this
