### ISSUE TITLE
Web - Workspace - Workspace chat is unpinned upon coming online if workspace is created offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47158]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4837014&group_by=cases:section_id&group_id=229065&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Go offline
4. Create a workspace
5. Navigate to LHN
6. Go online
## Expected Result:
Workspace chat should still be pinned

## Actual Result:
Workspace chat is unpinned upon coming online if the workspace is created offline.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/71e033c6-8e6d-4c1f-bd74-1a938da068d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment]
I'll add the internal label for now and confirm whether this is a BE bug.

**Comment by sakluger** [comment]
I posted in Slack asking for volunteers: https://expensify.slack.com/archives/C036QM0SLJK/p1723566484592809

**Comment by aldo-expensify** [comment]
Starting to work on this now

**Comment by aldo-expensify** [comment]
Made PR ready for review: https://github.com/Expensify/Auth/pull/12105

**Comment by sakluger** [comment]
The fix is deployed! Closing 👍
