### ISSUE TITLE
Web - Violations - Missing tag instead of Review required shown on expense preview if depende

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47154]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
An issue was found when executing this PR https://github.com/Expensify/App/issues/44995
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: user created a workspace, enabled the "Members must tag all expenses" and "Use multiple level of tags" toggles, and added Dependent tags in OD

1. Go to https://staging.new.expensify.com/ and log in
2. Click on FAB and submit a manual expense without selecting tags to a workspace with dependent tags enabled
3. Submit another manual expense without selecting tags
4. Navigate to the workspace chat
5. Open the expense report

## Expected Result:
"Review required" is displayed on the expense preview

## Actual Result:
"Missing tag" is displayed on the expense preview

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/73eb21f9-85b9-4e8b-bec6-c961d0c6cca2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment]
Hi @getusha - could you confirm if this is connected to @ShridharGoel's PR here?   https://github.com/Expensify/App/issues/44995

**Comment by cead22** [comment]
I don't think the expected results here are right, so closing. @IuliiaHerets in the future please alwats include the email you used, and the policyID and reportIDs used/created so we can easily search for logs
