### ISSUE TITLE
[$250] Expense - Expense report stays "pinned" to LHN after it is exported to CSV

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47160]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense and pay it.
4. Go to Search > Shared.
5. Select the paid expense in Step 3.
6. Click on the dropdown > Download.
7. Return to Inbox.
8. Open any report other than the paid expense report in Step 3.

## Expected Result:
The expense report will not remain in LHN when another report is opened.

## Actual Result:
Expense report stays "pinned" to LHN after it is exported to CSV.
It remains in LHN even when another report is opened.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b508842e-f346-415c-aafd-132539ad213a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f803bf9c62b72a5</li>
        <li>Upwork Job ID: 1823174429757887078</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103650314</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
Agree this is an issue we should fix!

**Comment by burczu** [comment]
Hi, I’m Bartek from Callstack and I would like to work on this issue.

**Comment by burczu** [comment]
Hmm... frankly I'm not able to reproduce the issue:

https://github.com/user-attachments/assets/e029caf2-0ba1-4df9-911d-bd360be4f2aa

But, there is a distinction comparing to steps to reproduce posten in this issue - I can't see the "Shared" option in the search panel. Is it something I can turn on in the Workspace settings or smth?

**Comment by burczu** [comment]
@rayane-djouah Synced with latest main and indeed the "Shared" status shows up, thanks. Moreover the bug occurs in this case... so I'll try to find solution now.

@VictoriaExpensify Could you please assign me?

**Comment by burczu** [comment]
I've done my research and I suspect this issue comes from the backend side.

Before we export the expense report as CSV, the `notificationPreference` of it is set to "hidden". After we download the report in the Search -> Shared panel, the backend pushes the changes to the report and the `notificationPreference` is changed to "always" along with additional comment added to the report: "exported this report to CSV" (I've checked and it seems no Onyx action is called on the frontend side that may change these values) - that's the reason it stays "pinned" from now on. Please take a look at the video below:

https://github.com/user-attachments/assets/bfb46b69-a785-4266-b12b-253b13cdd818

**Comment by trjExpensify** [comment]
I'm a bit confused by the issue, I don't think it's overly clear from the OP what priorityMode is being used, nor does this screenshot make it seem as though the report is pinned or the user is in #focus mode. 

![Image](https://github.com/user-attachments/assets/a0d71276-6a6a-4ad0-b548-ac18f5f9dc4a)

**Comment by trjExpensify** [comment]
CC'ing a few peeps for vis and context on these features: @deetergp @rlinoz @JmillsExpensify

**Comment by VictoriaExpensify** [comment]
Oof yeah, I think this needs some further triaging, actually. I'm going to have another play around between the Focus and Most Recent modes and get more clarity on the issue

**Comment by rlinoz** [comment]
[PR is deployed](https://github.com/Expensify/Auth/pull/12432#issuecomment-2342668684) and this should now be fixed.
