### ISSUE TITLE
Scan - App crashes when submitting a scan expense via QAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47175]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** htad26+irbgkhyo@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in to new dot with a new account
2. Click on FAB > Submit expense > Scan
3. Upload a receipt > Choose a user you want to submit the expense to > Finish the flow
4. Once the expense is created go to FAB
5. Click on the quick action button which is "Scan receipt"

## Expected Result:
User is able to submit a scan expense via QAB

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c5576881-48df-4282-8970-097efbfdabb8

[logs (2).txt](https://github.com/user-attachments/files/16563590/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by hereistopdev** [comment]
Hi.
Would you like to assign this issue to me?
I am able to fix this one in quick time.
Best,
Sagar

**Comment by roryabraham** [comment]
This should be fixed by https://github.com/Expensify/App/pull/46956

**Comment by puneetlath** [comment]
Asking for a re-test.

**Comment by m-natarajan** [comment]
Bug fixed 

https://github.com/user-attachments/assets/f4d602d6-bdf4-4841-9852-28960ba1b221

**Comment by puneetlath** [comment]
Great! Closing out.
