### ISSUE TITLE
[$250] Select date in Submission frequency modal gets dismissed modal after reload page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47178]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723191970067539

## Action Performed:
1. Open account settings
2. Open workspaces and choose any workspace
3. In more features turn on Workflows and open it
4. Turn on Delay submissions and open Submission frequency
5. Choose monthly
6. Open date of month
7. Reload this page
8. Select any date

## Expected Result:
Back to the Submission frequency modal
## Actual Result:
Submission frequency modal gets dismissed
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f47dc871-47ff-4e2f-9a29-d2e80b02f8ef

https://github.com/user-attachments/assets/f7f5969d-bf61-44a3-9035-37f47d90b0af

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7f48f34dee22a4a</li>
        <li>Upwork Job ID: 1821971631028523622</li>
        <li>Last Price Increase: 2024-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103496370</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by BhuvaneshPatil** [comment]
that was quick @daledah 🚀

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Select date in Submission frequency modal gets dismissed modal after reload page

### What is the root cause of that problem?

We don't send backTo param when navigate to WORKFLOWS_AUTO_REPORTING_MONTHLY_OFFSET

### What changes do you think we should make in order to solve the problem?

Key differences with prev proposal:
- Submit backTo to the url
- This backTo param can be used for better persistencies even link opened when logged out

In src/ROUTES.ts add backTo param
```tsx
    WORKSPACE_WORKFLOWS_AUTOREPORTING_MONTHLY_OFFSET: {
        route: 'settings/workspaces/:policyID/workflows/auto-reporting-frequency/monthly-offset',
        getRoute: (policyID: string, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/workflows/auto-reporting-frequency/monthly-offset`, backTo),
    },
```

In src/pages/workspace/workflows/WorkspaceAutoReportingFrequencyPage.tsx call navigate with backTo param value
```tsx
            <MenuItem
                title={translate('workflowsPage.submissionFrequencyDateOfMonth')}
                titleStyle={styles.textLabelSupportingNormal}
                description={getDescriptionText()}
                descriptionTextStyle={styles.textNormalThemeText}
                wrapperStyle={styles.pr3}
                onPress={() => Navigation.navigate(ROUTES.WORKSPACE_WORKFLOWS_AUTOREPORTING_MONTHLY_OFFSET.getRoute(policy?.id ?? '', ROUTES.WORKSPACE_WORKFLOWS_AUTOREPORTING_FREQUENCY.getRoute(policy?.id ?? '')))}

```

In src/pages/workspace/workflows/WorkspaceAutoReportingMonthlyOffsetPage.tsx read `navigateBackTo` from route

```tsx

...
   const onSelectDayOfMonth = (item: WorkspaceAutoReportingMonthlyOffsetPageItem) => {
        Policy.setWorkspaceAutoReportingMonthlyOffset(policy?.id ?? '-1', item.isNumber ? parseInt(item.keyForList, 10) : (item.keyForList as AutoReportingOffsetKeys));
        Navigation.goBack(navigateBackTo);
    };
...

                   <HeaderWithBackButton
                        title={translate('workflowsPage.submissionFrequency')}
                        onBackButtonPress={() => Navigation.goBack(navigateBackTo)}
                    />
```

[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/47178-fix-back-from-monthly-offset?expand=1)

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment]
any updates here? @dukenv0307 @daledah 

thanks!

**Comment by isabelastisser** [comment]
Thanks for the heads up @dukenv0307! It looks like the payment automation failed.

**Comment by isabelastisser** [comment]
@daledah, can you please apply for [this job in Uprwork](https://www.upwork.com/ab/applicants/1821971631028523622/job-details) or share your Upwork profile here? Thanks!

**Comment by isabelastisser** [comment]
Thanks @daledah, I sent you the offer in Upwork now.

**Comment by isabelastisser** [comment]
@dukenv0307, I processed your payment in Upwork yesterday.
@daledah, please accept the offer and I will process the payment.

All set!

**Comment by isabelastisser** [comment]
@daledah, payment approved in Upwork. Thanks!
