### ISSUE TITLE
[HIGH] [Attendee Tracking] Create Attendees item row for editing requests

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#47173]
Allow editing of attendees on existing requests. The key changes here are that we need to handle editing on the item row, AttendeeSelectionPage, and ensure the policy violation limit is recalculated. Additionally the backend will be creating a system action message containing the details of the edit so we need to [pass the attendees](https://docs.google.com/document/d/1e6w0uVdCh_h_uNJEBWwi2rmPzTCLKTb-HdimFnVEfqk/edit?pli=1#bookmark=id.fia1uwh4tzel) to the EditMoneyRequest API and optimistically create the system action message.

![Screenshot 2024-08-09 at 15 50 46](https://github.com/user-attachments/assets/b9bd8896-cace-4179-9e05-606f92b9f795)

**Requirements**
- Implement editing of attendees on existing requests
- Recalculate the policy violation limit
- Optimistically show [system message](https://docs.google.com/document/d/1e6w0uVdCh_h_uNJEBWwi2rmPzTCLKTb-HdimFnVEfqk/edit?pli=1#bookmark=id.p957cptonnsk) on editing the expense attendees

_More details can be found [here](https://docs.google.com/document/d/1e6w0uVdCh_h_uNJEBWwi2rmPzTCLKTb-HdimFnVEfqk/edit?pli=1#bookmark=id.43kbp340wwfy) and elsewhere throughout the design document_

**Comment by Julesssss** [comment]
Currently held on the above issues, and is a lower priority task

**Comment by Julesssss** [comment]
Hey @zfurtak @filip-solecki, for now I'm holding this issue, but feel free to make a start once you need more tasks 👍

**Comment by Julesssss** [comment]
This will be the last issue worked on.

**Comment by zfurtak** [comment]
Hi @Julesssss, can you assign me to this one? 😊

**Comment by Julesssss** [comment]
Sure, done 👍

**Comment by SzymczakJ** [comment]
FYI I'll be taking this task from Zuzia as she is OOO tomorrow.

**Comment by SzymczakJ** [comment]
Is there any way to check violation limit for the transaction? The one source would be to take it from transactionViolations object but it's actually given in a string, so if there was another way I would happily use it @Julesssss

**Comment by Julesssss** [comment]
I think for now we will need to use that string. I will create a backend issue for improving this once we are passing the Onyx data back to the client.

**Comment by Julesssss** [comment]
Hey @allgandalf. I just invited you

**Comment by Julesssss** [comment]
Ah, I see what you mean now. 

Switching to @ZhenjaHorbach who has been reviewing and locating bugs in these flows.

**Comment by Krishna2323** [comment]
This PR for this caused #75653,`oldAttendees` used `getAttendees(oldTransaction)` (includes default self-attendee), so first edit wrongly showed "changed" not "set". Fixed in #86259. Exact line which caused the issue: https://github.com/Expensify/App/pull/48870#discussion_r3972219316
