### ISSUE TITLE
[CRITICAL] [Attendee Tracking] Create AttendeeSelectionPage

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#47171]
Create the new AttendeeSelectionPage that will be shown when creating and editing a request. IAttendees are essentially names/emails of users that may or may not exist and are listed simply as a string. If recent attendees already exist (provided via NVP data that will be introduced by backend changes) up to 5 will be displayed in Recents at a higher priority than the contacts we typically display under 'Recents'. Attendee data will be passed to the API under [this](https://docs.google.com/document/d/1e6w0uVdCh_h_uNJEBWwi2rmPzTCLKTb-HdimFnVEfqk/edit?pli=1#bookmark=id.fia1uwh4tzel) structure. 

![Screenshot 2024-08-09 at 15 33 23](https://github.com/user-attachments/assets/44aa4368-9a6f-4ed2-a29e-b84e4aa3547c)

**Requirements**
- Display up to 5 recent attendees under the under Recents header
- Display any excluded recent attendees under 'Contacts'
- Allow new recent attendees to be created and passed to the server ([optimistic with feedback](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#b---optimistic-with-feedback-pattern) API pattern) ([data structure](https://docs.google.com/document/d/1e6w0uVdCh_h_uNJEBWwi2rmPzTCLKTb-HdimFnVEfqk/edit?pli=1#bookmark=id.fia1uwh4tzel))
- At least one attendee must be selected

_More details [here](https://docs.google.com/document/d/1e6w0uVdCh_h_uNJEBWwi2rmPzTCLKTb-HdimFnVEfqk/edit?pli=1#bookmark=id.r3vsqaeic9ib) in the design document._

**Comment by Julesssss** [comment]
Hey @zfurtak @filip-solecki, it would be great if you could make a start on this issue. I'm around for any questions and we'll be focusing on the backend issue for persisting and passing the attendee Onyx data back to the client. 

I believe you should be able to workaround that in the meantime 🤞 

Feel free to further break down these tasks, and we can merge these to a branch like this until the backend issues are completed `feature-attendeeTracking`. Let me know if you have any further questions.

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this!

**Comment by Julesssss** [comment]
Hey @filip-solecki, just checking in to see if I can help with anything here?

**Comment by filip-solecki** [comment]
Hi! I was focused on CSV Import and didn't make significant progress, but good news is that @robertKozik will help me here so it should speed up this project 🚀

**Comment by zfurtak** [comment]
Hello, I will take over this issue from Robert, since he's no longer working on this project 😊

**Comment by Julesssss** [comment]
Hey @zfurtak, that's great. Let me know if you have any questions! We're currently working on the second backend issue.

**Comment by Julesssss** [comment]
PR submitted and in review[ here](https://github.com/Expensify/App/pull/48008)

**Comment by Julesssss** [comment]
Hey @dubielzyk-expensify. We're seeking your thoughts for how to implement the NewDot attendee tracking page. When the user deselect themselves we're not sure where they should appear in the list for re-selection. Vertical space is limited so I'm not convinced by a new section header personally. But Contacts, and Recents also aren't great categories to put the user under 😕 

![Screenshot 2024-09-02 at 13 38 06](https://github.com/user-attachments/assets/8481536a-c93f-4a3c-aebc-9c7ff3c16519)


[Here](https://github.com/Expensify/App/pull/48008#issuecomment-2324424880) is a comment on the PR that explains in more details.

**Comment by dubielzyk-expensify** [comment]
> But Contacts, and Recents also aren't great categories to put the user under 😕

Why? Recents feels good to me? It was recently picked or unpicked? Feels like on the top of Recent is the right go without creating a new section (or replacing `recents` with a new section)

**Comment by Julesssss** [comment]
Okay, thank you. We'll pin to the top of recent 👍
