### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] Desktop - Onboarding can be skipped by esc key

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.18-7
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  n/a
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify desktop app.
2. Sign up with a new Gmail account.
3. During onboarding, press esc key.

## Expected Result:
Onboarding cannot be skipped by esc key.

## Actual Result:
Onboarding can be skipped by esc key.
This issue only happens on desktop app and not web app.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e249f1bd-88ff-4261-b81e-72da99d92bc4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115ed02f53aa4456b</li>
        <li>Upwork Job ID: 1822029538491322982</li>
        <li>Last Price Increase: 2024-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103496768</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by jasperhuangg** [comment]
Man I almost feel like this should be a feature 😆 

No need to block deploy, onboarding isn't necessary to use the App, and it only happens on desktop.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Desktop - Onboarding can be skipped by esc key

### What is the root cause of that problem?

Onboarding can have several re-renders during initial load, it can be caused by react 18 strict mode or electron internal lifecycle. During this re-render a race condition might occurred in this useEffect.

https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/hooks/useDisableModalDismissOnEscape.ts#L5-L8

The disabling process might be called before cleanup code (re-enabling)

### What changes do you think we should make in order to solve the problem?

The key is to execute `Modal.setDisableDismissOnEscape(true)` at the end and avoid race condition. This can be achieved by wrapping `Modal.setDisableDismissOnEscape(true)` with `InteractionManager.runAfterInteractions`.

In `src/hooks/useDisableModalDismissOnEscape.ts`
```tsx
import {useEffect} from 'react';
import {InteractionManager} from 'react-native';
import * as Modal from '@userActions/Modal';

export default function useDisableModalDismissOnEscape() {
    useEffect(() => {
        InteractionManager.runAfterInteractions(() => {
            Modal.setDisableDismissOnEscape(true);
        })
        return () => Modal.setDisableDismissOnEscape(false);
    }, []);
}

```

### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment]
Proposal [Updated](https://github.com/Expensify/App/issues/47189#issuecomment-2278939569)

- Add alternative solution

**Comment by allroundexperts** [comment]
Thanks for the proposals everyone.

@dominictb was the first one to propose the correct solution, but he missed the part of now showing the error. I think @Krishna2323's [proposal](https://github.com/Expensify/App/issues/47189#issuecomment-2281183444) is better as it handles all the cases. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by jasperhuangg** [comment]
I think @dominictb's proposal was the first to fix the issue. The confusion is partially based on the OP not being very clear on what we want to solve. If we go entirely based on what is said in the OP then @dominictb's proposal is first valid solution.

Thank you @Krishna2323 for submitting your proposal, I hope you can understand my decision.

**Comment by jasperhuangg** [comment]
@Krishna2323 Feel free to report the bug yourself in the #expensify-bugs channel and double-check that the person creating the issue assigns you! Thanks for your investigation.

**Comment by jasperhuangg** [comment]
FYI @miljakljajic I will be going OOO for the rest of the week so we will likely need to rope in another internal engineer to complete the PR review.

cc @dominictb

**Comment by jasperhuangg** [comment]
Bump @allroundexperts on above 🙇

**Comment by allroundexperts** [comment]
@jasperhuangg Do you think that the bug reported by @Krishna2323 is worth solving? If so, can you create a new issue and assign both of us?

**Comment by jasperhuangg** [comment]
@Krishna2323 Please report the bug yourself via the #expensify-bugs channel. We'll let it go through our standard process.

**Comment by miljakljajic** [comment]
@allroundexperts is owed 250 for their work reviewing this PR

**Comment by miljakljajic** [comment]
@dominictb has been paid in upwork

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
