### ISSUE TITLE
Android - Rooms - Suggestions box not appeared when typed "#" in the workspace room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47194]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4839123&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):** applausetester+omqq354@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: user has signed in with account that have a workspace and two rooms with unique names

1. Open app
2. Navigate to a workspace room that is not the #announce room
3. Enter the # in the composer

## Expected Result:
Suggestion box with other room names should be appeared above the compose box

## Actual Result:
Suggestion box with listed workspace rooms not appeared when user typed "#" in the compose box

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/19d0305a-3b82-4c30-a145-d139d9d0ab00

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment]
I played around with this and I think that while it is not necessarily a `bug` — I think the functionality of being able to use the comment field to be able to link rooms — similar to using `@` to tag someone, but `#` instead

Going to get eyes on this

**Comment by CortneyOfstad** [comment]
Not overdue — still a hotpick!

**Comment by CortneyOfstad** [comment]
So this sat for 2 weeks with no takers. Since this is considered lower priority I am going to close this and we can re-address when VIP-VSB is reopened 👍
