### ISSUE TITLE
[Workspace Feeds] Create OpenCardDetailsPage api command

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#47231]
For the [Workspace feeds](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#heading=h.18ccrwh58xge) project, we need to create a new command that will load the necessary details for the card when the card details page is opened 
<img width="295" alt="image" src="https://github.com/user-attachments/assets/c2a5614e-5a93-4104-bb79-866ac0a6131a">

We need to load the classic details for a card including the `availableSpend` which is not returned for the list of all cards so we need to fetch it with the details.

**Comment by mountiny** [comment]
cc @VickyStash for visibility this is the command for the card details page.

it takes authtoken and cardID as params

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by mountiny** [comment]
Hello Viktoryia

**Comment by mountiny** [comment]
read command OpenCardDetailsPage

Params:
- string authToken
- number cardID

Returns:
- cards_<workspaceAccountID>_Expensify Card with that one card formatted as you can see in Card.ts (including `nameValuePairs`, `availableSpend`, `domainName`)

**Comment by VickyStash** [comment]
**Updates:** 
- I've prepared a [Draft PR](https://github.com/Expensify/App/pull/47333) with OpenCardDetailsPage API call integration and follow-ups from another PR. I'll finalize it when API updates are deployed.

**Comment by VickyStash** [comment]
@mountiny The `OpenCardDetailsPage` works as expected, thank you!

I've started to test the loading of the Card details page, and I have several questions:
1) Should I show the loading indicator on the Card details page while `OpenCardDetailsPage` is executing?
2) When the user updates the card limit, it affects the card's remaining limit (`availableSpend`) as well. Should I optimistically update the availableSpend value in this case, or should I show the loading on the Card details page instead while the update command is taking place?

**Comment by mountiny** [comment]
> Should I show the loading indicator on the Card details page while OpenCardDetailsPage is executing?

I will bring this to slack

> When the user updates the card limit, it affects the card's remaining limit (availableSpend) as well. Should I optimistically update the availableSpend value in this case, or should I show the loading on the Card details page instead while the update command is taking place?

Lets try to update this optimistically

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/47333) with `OpenCardDetailsPage` API call integration is open for the review

**Comment by trjExpensify** [comment]
Any reason this issue is still open?

**Comment by mountiny** [comment]
I dont think so
