### ISSUE TITLE
[Performance] Remove acronym matching from Search

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#47237]
### Problem

We have implemented the search algorithm based on a library which also checked for acronyms. We have however noticed its not leading to different results in our implementation so the acronyms check is not useful at the moment (might change in future)

### Solution

Lets remove it

<details><summary>Issue Owner</summary>Current Issue Owner: @TMisiukiewicz</details>

**Comment by TMisiukiewicz** [comment]
Hi, I'm Tomasz from Callstack and I want to work on this issue

**Comment by mountiny** [comment]
This is done now
