### ISSUE TITLE
Report fields - App crashes when disabling/enabling list values via checkbox & dropdown button

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47230]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/46938
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields
3. Click Add field
4. Select List from Type
5. Go to List values and add a few list values
6. Long press on the list value > Select.
7. Tap on the dropdown.
8. Tap Disable.

## Expected Result:
App will not crash.

## Actual Result:
App crashes when disabling/enabling list values via checkbox and dropdown button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e8e64cfe-6bf3-44df-981e-1a9a412ff2f6

[Bug6569740_1723464002972!staging.new.expensify.com-1723463652050.txt](https://github.com/user-attachments/files/16582040/Bug6569740_1723464002972.staging.new.expensify.com-1723463652050.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control.

**Comment by izarutskaya** [comment]
Production

https://github.com/user-attachments/assets/c29feebd-daa6-4800-b6d1-968dc2b29efc

**Comment by mountiny** [comment]
cc @nkdengineer @jasperhuangg @jjcoffee from the linked PR

**Comment by nkdengineer** [comment]
Checking this now.

**Comment by nkdengineer** [comment]
@mountiny This comes from this [PR](https://github.com/Expensify/App/pull/46278). When we disable all values, the `options` becomes an empty array. Then the App crashes [here](https://github.com/Expensify/App/blob/4ef1202704270a84bb6bdc2a6bf22201a6699d76/src/components/ButtonWithDropdownMenu/index.tsx#L81)

https://github.com/Expensify/App/blob/4ef1202704270a84bb6bdc2a6bf22201a6699d76/src/pages/workspace/reportFields/ReportFieldsListValuesPage.tsx#L260

https://github.com/Expensify/App/blob/4ef1202704270a84bb6bdc2a6bf22201a6699d76/src/components/ButtonWithDropdownMenu/index.tsx#L53

**Comment by mountiny** [comment]
@Krishna2323 @mananjadhav are you able to handle this?

**Comment by carlosmiceli** [comment]
@Krishna2323 great!

@mountiny do you wanna take over this one since you have more context and already engaged in the conversation?

**Comment by Beamanator** [comment]
Taking over to move deploy forward :D

**Comment by Beamanator** [comment]
@allroundexperts will be reviewing @Krishna2323 's PR - https://github.com/Expensify/App/pull/47244

**Comment by Beamanator** [comment]
PR merged, working on CP

**Comment by Beamanator** [comment]
CP'd, asking for test on staging

**Comment by Beamanator** [comment]
Working well on staging!

**Comment by mountiny** [comment]
Thanks everyone 🙇

**Comment by Beamanator** [comment]
@twisterdotcom i believe @allroundexperts needs payment for C+ for https://github.com/Expensify/App/pull/47244 - but maybe only once the fix has been on prod for a week?

**Comment by twisterdotcom** [comment]
I think it has now been on prod for a week? Deploy was on the 12th: https://github.com/Expensify/App/issues/47219

**Comment by twisterdotcom** [comment]
Payment Summary:

- @allroundexperts paid $250 via NewDot requests (C+)

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
