### ISSUE TITLE
[$250] Scan - "Delete" and "Replace" options are displayed for an admin which causes an error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47242]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4845247
**Email or phone of affected tester (no customers):** htad26+foiotfy@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisite
Create a workspace and invite an employee to the workspace
Login as an owner and employee
1. As the employee navigate to the workspace chat and click on the + icon > Submit expense > Scan
2. Upload a receipt and finish the flow
3. After the expense is created navigate to the tab where you are logged in as the admin/owner
4. Click on the receipt thumbnail
5. Here notice that the "Delete" and "Replace" options are displayed
6. Click on "Replace" > Choose another receipt > Upload > Notice that an error is thrown
7. Click on "Delete" > Confirm > Notice that an error is thrown

## Expected Result:
The workspace admin cannot edit the receipt file so there should not be "Delete" and "Replace" options

## Actual Result:
"Delete" and "Replace" options are displayed and when performing these actions, an error is thrown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7c5e8dd2-98df-4464-aa3d-fd7dee3c0dbe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a08abb02f6c6658f</li>
        <li>Upwork Job ID: 1823152253036105130</li>
        <li>Last Price Increase: 2024-08-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Beamanator** [comment]
Looks external b/c there's buttons in the UI that we don't want to show 🙏

**Comment by Beamanator** [comment]
@youssef-lr I wonder if this has to do with https://github.com/Expensify/App/pull/46931 ?

**Comment by Pujan92** [comment]
Yes @Beamanator , it seems to be added intentionally in commit https://github.com/Expensify/App/pull/46931/commits/06f3d4d11ac683a23fba1ea758d1cd258617e3db.

@youssef-lr can help here to decide the expected behavior.

**Comment by Beamanator** [comment]
Marking NAB b/c this is not a big problem at the moment & Control plans are still WIP

**Comment by youssef-lr** [comment]
I'll get to this tomorrow

**Comment by youssef-lr** [comment]
> The workspace admin cannot edit the receipt file so there should not be "Delete" and "Replace" options

The `Expected Result` in this issue is incorrect because we allow admins to do so in OldDot. But the backend shouldn't be throwing, investigating now.

**Comment by youssef-lr** [comment]
This is fixed.
