### ISSUE TITLE
[$250] Pay someone - Transaction fields become empty after leaving system message thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47245]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM
3. Go to + > Pay <user>
4. Select a different currency, enter amount and pay it
5. Go to transaction thread
6. Right click on the system message > Reply in thread
7. Send a reply in thread
8. Leave the thread via report header

## Expected Result:
The transaction fields will not be empty after leaving system message thread

## Actual Result:
The transaction fields become empty after leaving system message thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3c9c0e29-bfe5-49ec-a7a5-a528df8db0a4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0366cae8a0c502d</li>
        <li>Upwork Job ID: 1827403240488254568</li>
        <li>Last Price Increase: 2024-08-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment]
Since this is related to adding comments in reports I'm going to put this into Collect.

**Comment by kevinksullivan** [comment]
Just pushed forward recently, so let's keep looking for proposals for now.

**Comment by NJ-2020** [comment]
Issue is not reproducible using staging server

**Comment by kevinksullivan** [comment]
re-test check here

https://expensify.slack.com/archives/C9YU7BX5M/p1724975179464149

**Comment by mvtglobally** [comment]
Not reproducible on Mac/Safari
https://github.com/user-attachments/assets/a9bf1c11-5e30-430b-90ab-decca77b9076
