### ISSUE TITLE
[$250] Hold expense - RBR is not shown instantly when holding expense from main chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47240]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open DM with user that has no unsettled expense.
3. Submit an expense.
4. In the mian chat, right click on the expense preview.
5. Select Hold.
6. Enter a reason and save it.
7. Note that the expense preview in the main chat does not show RBR.
8. Go to the transaction thread and return to main chat.
9. Note that the expense preview in the main chat now shows RBR.
10. Submit another expense.
11. Go to expense report.
12. Right click on the expense preview > Hold.
13. Enter reason and save it.
14. Note that the expense preview in the expense report displays RBR and hold label without the need to visit the transaction thread.

## Expected Result:
In Step 7, the expense preview in the main chat will show RBR after holding the expense from the main chat.

## Actual Result:
In Step 7, the expense preview in the main chat does not show RBR after holding the expense from the main chat.
It only shows RBR after visiting the report and back to main chat in Step 9.

When holding the expense from expense report (at least two expenses), the RBR and Hold label are shown without visiting the transaction thread (Step 14).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b2ef93de-ce64-4aff-8121-713e393acc8e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162d2bf8d74991b81</li>
        <li>Upwork Job ID: 1823077860579616696</li>
        <li>Last Price Increase: 2024-08-12</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 103588043</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment]
Production

![Screenshot (629)](https://github.com/user-attachments/assets/183b7e75-ec4f-4755-98d1-d12dc878c6ed)

**Comment by dylanexpensify** [comment]
@johnmlee101 can repro, but don't think this is necessarily a deploy blocker? LMK what you think!

**Comment by johnmlee101** [comment]
Yeah doesn't seem like a blocker necessarily

**Comment by johnmlee101** [comment]
@Nodebrute just making sure you've seen this!

**Comment by mananjadhav** [comment]
@dylanexpensify this is ready for payout. I couldn't pinpoint the exact PR where we should've added the RBR changes. I also don't think we need a regression test for this one.

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
