### ISSUE TITLE
[HOLD for payment 2024-09-12] [$250] Workspace - Workspace profile page becomes grayed out when go offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47260]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a919@gmail.com
**Issue reported by:** Applause  - Internal Team

## Action Performed:
1. Login with gmail account
2. Create workspace
3. Go offline
4. Go to workspace profile page

## Expected Result:
Workspace profile page should not be grayed out since the workspace was created in online mode

## Actual Result:
Workspace profile page becomes grayed out when user goes offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ef924aba-a998-4be2-b32c-66346c3aec02

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182138e49511ea4ac</li>
        <li>Upwork Job ID: 1823362392640621309</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103705107</li>
<li>Krishna2323 | Contributor | 103705109</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsb

**Comment by puneetlath** [comment]
@shubham1206agra thoughts on the proposals?

**Comment by puneetlath** [comment]
@brandonhenry is going to open a PR for the fix.

**Comment by trjExpensify** [comment]
@puneetlath has actioned on that, I've added the `Awaiting payment` label as well now.

**Comment by puneetlath** [comment]
I've paid @Krishna2323. 

@shubham1206agra can you please complete the checklist?

**Comment by puneetlath** [comment]
Ok great. All paid. Thanks everyone!
