### ISSUE TITLE
Expense - Employee can edit paid expense but error shows up when advanced approvals is enabled

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47265]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  Exp https://expensify.testrail.io/index.php?/tests/view/4847269
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Advanced approvals is enabled in the workspace via Workspace settings > Workflows > Add approval workflow > Upgrade.
- Admin and employee are in the same workspace.

1. Go to staging.new.expensify.com
2. [Employee] Submit an expense in the workspace chat.
3. [Admin] Approve and pay elsewhere the expense report.
4. [Employee] Go to the transaction thread of paid expense.
5. [Employee] Edit Description, Category, Tax etc.

## Expected Result:
Since the transaction fields are enabled, employee should be able to edit the fields.

Or

The transaction fields should be disabled for employee.

## Actual Result:
Employee has access to edit the paid expense but error shows up after saving the edit.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/840b9b73-2eb6-49b6-9a4b-938cf774dc25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to  #wave-control

**Comment by AndrewGable** [comment]
Tagging the advanced approval experts if they have any ideas cc @tgolen @blazejkustra

**Comment by AndrewGable** [comment]
I do see a console error and am curious if this is causing issues?

![Google Chrome 2024-08-12 at 15 05 16](https://github.com/user-attachments/assets/e3dee07f-3110-4522-8429-379c992f79b1)

**Comment by tgolen** [comment]
I would be pretty surprised if anything from the advanced approvals is causing that... but it's possible. Maybe @blazejkustra would know. Otherwise, I'd look for recent changes in OptionListUtils to see if you can spot something.

**Comment by Beamanator** [comment]
@youssef-lr or @cristipaval  may know more about this since it seems related to https://github.com/Expensify/Expensify/issues/411546 or https://github.com/Expensify/Expensify/issues/411544 or https://github.com/Expensify/Expensify/issues/411545?

**Comment by youssef-lr** [comment]
@Beamanator I pinged you in the line from my PR causing this

**Comment by Beamanator** [comment]
sorry @youssef-lr can you also link that PR here?

**Comment by youssef-lr** [comment]
also I think its fine to demote this. We don't have that many Control workspaces enabled for NewDot right now apart from our internal workspaces.

**Comment by Beamanator** [comment]
That makes sense to me - if the backend is solid (which should mean OldDot works well) then lets call this NAB for now. Maybe you want to assign yourself for this fix?

**Comment by CortneyOfstad** [comment]
Not overdue!

**Comment by Beamanator** [comment]
https://github.com/Expensify/App/pull/47398 was deployed to prod 2 days ago - @youssef-lr can we close this?
