### ISSUE TITLE
Post deploy announcements in slack

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#4727]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Run a staging or prod deploy of Expensify/App.

## Expected Result:
`OSBotify` should post in Slack, telling us that a deploy occurred. Staging deploys should be announced in #announce, while production deploys should be announced in #expensify-open-source.

## Actual Result:
No post in slack.

## Workaround:
n/a

## Platform:
GitHub/Slack

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
Making this internal so that it can be tested by the same engineer who writes the code. Testing will be the most painful part of this issue. FP instructions:

Add a step in [`platformDeploy.yml`](https://github.com/Expensify/App/blob/b93e158f73f685444ce179e20dc87255739a194c/.github/workflows/platformDeploy.yml) at the end of the file in the [`postGithubComment` job](https://github.com/Expensify/App/blob/b93e158f73f685444ce179e20dc87255739a194c/.github/workflows/platformDeploy.yml#L318-L360) that uses `action-slack` ([example](https://github.com/Expensify/App/blob/3f35b70b1f33ab31e211e374ff8de38ba181c9a5/.github/workflows/deployBlocker.yml#L47-L62)) to post a well-formatted deploy comment in the correct slack room. The [`SHOULD_DEPLOY_PRODUCTION`](https://github.com/Expensify/App/blob/b93e158f73f685444ce179e20dc87255739a194c/.github/workflows/platformDeploy.yml#L354) environment variable tells us whether or not the completed deploy was a production deploy.

Also, please delete [this outdated, unused step](https://github.com/Expensify/App/blob/b93e158f73f685444ce179e20dc87255739a194c/.github/workflows/platformDeploy.yml#L333-L337). That is _not_ an accurate way to determine whether a given staging deploy was a CP or standard deploy.

Testing instructions:

1. Make sure that the `StagingDeployCash` is _not_ locked.
1. Lock the `StagingDeployCash`, then verify that the resulting staging deploy is announced in _#announce_.
1. Merge a PR with the `CP Staging` label, then verify that the resulting staging deploy is announced in _#announce_.
1. Once the deploy checklist is complete and we close it out, verify that the resulting prod deploy is announced in _#expensify-open-source_.

**Comment by iwiznia** [comment]
> Staging deploys should be announced in #announce, while production deploys should be announced in #expensify-open-source

Let's post in announce everything we can. In the end, no one reads that channel, is more like a log of everything that was deployed.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183075988) to production by @roryabraham in version: 1.0.88-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅
