### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] [CVP] Remove Split Expense, Assign Tasks, Pay Someone in Global Create

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#47274]
[Coming from this thread ](https://expensify.slack.com/archives/C036QM0SLJK/p1723161024570569)I’m going to go forward with creating a GH around this p/s. Let us know if you have any additional feedback. cc @anmurali 

Problem: Users are getting overwhelmed when signing up. When they first enter the app, they can go a lot of directions. A primary direction we send them to is Global Create, where they see a lot of options. Given that most of our sign-ups are coming to us for expense tracking, we’re showing them a lot of options that are largely aspirational and that don’t apply to making their first experience in submitting an expense great. Thus, we’re causing more confusion, or just noise early on, and thus likely lowering conversion.

Solution: Let’s optimize global create for the most important options to drive expense adoption.
1. In Global Create, we’ll remove `Split expense`, `Assign tasks`, `Pay someone`.
- These options are still going to be available in DMs, workspace chats, groups, etc. We’re just removing them from global create.
2. We’ll keep a `New Workspace` as an option for first-time users, so it is unchanged. 
3. Quick action will remain unchanged.

As a note, `Book Travel` and `Send Invoice` are already planned to be only available if your workspace is enabled for them and if you are an admin in the `Send Invoice` case, so normal users already won’t see those. Thus, for new users their global create will now be: `Start chat`, `Track expense`, `Submit expense`, `New Workspace`, and the quick action option

- [ ] TODO (once we complete): we need to loop in Applauce once this is done because it will change their test rails so we need to get them to update those. cc BZ member 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149c0ef757838792e</li>
        <li>Upwork Job ID: 1823459393914964733</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103542241</li>
<li>neonbhai | Contributor | 103542245</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by dubielzyk-expensify** [comment]
Mock with Quick Action:
![image](https://github.com/user-attachments/assets/9b292368-fe43-476a-812e-fa1a84ac6ca0)

Mock without Quick Action:
![image](https://github.com/user-attachments/assets/78009717-dfe0-4c1c-9481-317b60079a76)

**Comment by trjExpensify** [comment]
Let us know what you think about the proposal, @jjcoffee. 👍

**Comment by jjcoffee** [comment]
@trjExpensify Are you the BZ for this? If not, can one be assigned? They need to be aware of the following:

> we need to loop in Applause once this is done because it will change their test rails so we need to get them to update those.

**Comment by trjExpensify** [comment]
I'm not, but let me get one assigned! I'll be out most of next week, otherwise I'd take it myself.

**Comment by trjExpensify** [comment]
pahaha, yes Melvin you troll.

**Comment by jjcoffee** [comment]
Approved!

@OfstadC Just tagging you directly to draw your attention to this line in the issue description in case you haven't spotted it yet:

> we need to loop in Applause once this is done because it will change their test rails so we need to get them to update those.

**Comment by OfstadC** [comment]
@danielrvidal Is there a specific flow for updating Applause -- Or is a Slack post all that's needed here?

**Comment by danielrvidal** [comment]
I think I'd just whatever our normal process is to update Applause. We just need to make them aware that Global Create is being changed.

**Comment by OfstadC** [comment]
Found SO for Applause update :chefskiss:

Posted [here](https://expensify.slack.com/archives/C9YU7BX5M/p1724354302621259).

**Comment by jjcoffee** [comment]
**Regression Test Proposal**

1. Login with a brand new account
2. Click on FAB (green plus icon)
3. Verify that the only options available are Start chat, Track expense, Submit expense, (Book Travel if on travel beta), New Workspace
4. Tap New Workspace
5. Verify that `Send invoice` option becomes available in the FAB
6. Submit or track an expense and verify that it shows up in the quick action

Do we agree 👍 or 👎

**Comment by OfstadC** [comment]
## Payment Summary 
- @jjcoffee paid $250 via Upwork
- @neonbhai paid $250 via Upwork
