### ISSUE TITLE
[$250] Report - DM report changes to group chat and app crashes when clicking on expense owner name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47277]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** 9.0.19-3
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Select a user with no chat history
4. Note that DM report changes to the old style group chat
5. Go to FAB > Submit expense > Manual
6. Submit a manual expense to any user with no chat history
7. After the DM changes to group chat, click on the owner name of the expense preview
8. Note that app crashes

## Expected Result:
When opening DM, DM report will not change to the old style group chat

## Actual Result:
When opening DM, DM report changes to the old style group chat
When submiting expense to user with no chat history and clicking on the owner name, app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/efba367a-10a2-4d28-9133-8babacfdfd35

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa57b2644b618170</li>
        <li>Upwork Job ID: 1823445678246537229</li>
        <li>Last Price Increase: 2024-08-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
Adding BZ again - I'll be out until 8/21

**Comment by slafortune** [comment]
@daledah @lanitochka17 I'm not able to recreate this, are you?

**Comment by lanitochka17** [comment]
Issue is not reproducible  now

https://github.com/user-attachments/assets/c79c733e-0ce3-4312-8c7a-66ab3ed34e26

**Comment by slafortune** [comment]
Not recreatable
