### ISSUE TITLE
[$250] Android – Sign in–Sound option is missing when Get started modal video opened to full screen

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
Issue was found when executing this PR https://github.com/Expensify/App/pull/46795
**Email or phone of affected tester (no customers):** ponikarchuks+00312824@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with a new Gmail account and click on Join button
3. Complete the Onboarding flow
4. In Get started video, note video is muted
5. Enable video to full screen

## Expected Result:
Sound option is present

## Actual Result:
Sound option is missing

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5f7a1ecc-738a-4c59-ac2b-9df584710e67

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9e36c7f9220ebf4</li>
        <li>Upwork Job ID: 1826259795924336728</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ikevin127** [comment]
👓 Looking for proposals.

**Comment by ikevin127** [comment]
@huult Thank you for the proposal. I wasn't able to test your solution as the implementation is not specific enough for me to get a working prototype in order to verify whether it works. If I just wrap the `Video` component with the given `Modal` as the given DIFF specifies, the videos stop working and present an infinite loading spinner.

Can you please provide a working test branch in order for me to verify this ?

##

> [!important]
> I opened up a [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1724459010000439) on Slack about this issue and whether or not it's worth addressing this issue given that most devices have a volume / mute button. Will bump the discussion as I posted it over the weekend and it did not get any attention.

**Comment by abekkala** [comment]
vsb is on hold. This is now 2 weeks old. 
I'm going to label not priority and close for now
