### ISSUE TITLE
[HOLD for Payment 2024-09-06][Performance] Performance regression in opening the Chat Finder page

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#47296]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

Our performance regression system is reporting a performance regression for opening the chat finder page between the last prod release and the current main branch:

<img width="951" alt="Screenshot 2024-08-13 at 09 18 58" src="https://github.com/user-attachments/assets/2a08f055-2cb4-48bf-9c47-ce8ecbf6afc6">

## What is the impact of this on end-users?

Slow TTI of opening the search page.

## List any benchmarks that show the severity of the issue

See screenshot

## Proposed solution (if any)

I opened this issue to keep track of the issue and that it needs to be investigated. I think the simplest would be to find the PR that caused the regression or to run a git bisect.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

See screenshot. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:latest main**
**Reproducible in staging?: no**
**Reproducible in production?: no**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:@hannojg**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by hannojg** [comment]
**Note:** The e2e system will report every PR as a regression after the faulty PR. So these PRs were tagged as regression, although they didn't cause it:
- https://github.com/expensify/app/pull/46948
- https://github.com/expensify/app/pull/47244
- https://github.com/expensify/app/pull/47275
- https://github.com/expensify/app/pull/47269
- https://github.com/expensify/app/pull/47111
- https://github.com/expensify/app/pull/46606
- https://github.com/expensify/app/pull/47203
- https://github.com/expensify/app/pull/46617

Unfortunately the e2e regression system didn't report the PR that introduced the regression as there was a failure for the pipeline (otherwise we could have just assumed that the first reported PR introduced the regression which isn't the case here unfortunately).

**Comment by kirillzyusko** [comment]
@daledah yeah, I think we can do that 👍 Feel free to submit a PR and if you want I can test everything locally to compare performance before PR gets merged 😊

**Comment by ikevin127** [comment]
♻️ I was auto-assigned for PR review as C+.

Please let me know if my review is needed before @kirillzyusko's final performance tests - or if they will handle both **PR Reviewer Checklist** and the performance tests.

**Comment by ikevin127** [comment]
♻️ I was auto-assigned for PR review as C+. I will handle the **PR Reviewer Checklist**, making sure to test on a HT account and before merge @kirillzyusko can do some performance tests on the PR to ensure the issue was fixed.

**Comment by ikevin127** [comment]
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from https://github.com/Expensify/App/pull/47891#issuecomment-2322122640. **Additionally, this should also have a BZ team member assigned for payments.**

cc @luacmartins

**Comment by ikevin127** [comment]
@luacmartins Can we please get a BZ team member assigned here for payments ? Thak you! 🙏

**Comment by luacmartins** [comment]
done

**Comment by bfitzexpensify** [comment]
Offer sent @ikevin127

**Comment by ikevin127** [comment]
@bfitzexpensify Offer accepted, thank you!
