### ISSUE TITLE
[HOLD for payment 2024-10-14] Invoicing payments frontend clean-up

### ISSUE THREAD

**Issue by rezkiy37** [Expensify/App#47302]
# Part of the Invoicing payments project

Main issue: https://github.com/Expensify/Expensify/issues/382977
Project: https://github.com/orgs/Expensify/projects/114/views/3

# Feature Description

The clean-up issue for the workspace invoicing flow. We need to complete all TODOs and uncomment temporary disabled lines.

# Manual Test Steps

# Automated Tests

**Comment by MonilBhavsar** [comment]
@rezkiy37 assigning you to this issue

**Comment by rezkiy37** [comment]
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment]
This issue is on hold until the backend is ready.

**Comment by rezkiy37** [comment]
Not overdue. https://github.com/Expensify/App/issues/47302#issuecomment-2294470259

**Comment by kevinksullivan** [comment]
I don't think I need to be on this since there's no contributor payouts necessary. Lmk if I am misunderstanding @rezkiy37

**Comment by rezkiy37** [comment]
Yes, you are right, @kevinksullivan 🙂

**Comment by rezkiy37** [comment]
https://github.com/Expensify/App/issues/47302#issuecomment-2294470259

**Comment by rezkiy37** [comment]
https://github.com/Expensify/App/issues/47302#issuecomment-2294470259

**Comment by rezkiy37** [comment]
Hey!
I will be OOO from 04.09 (_afternoon_) till 09.09. I will continue to work on this one once I am back.

**Comment by rezkiy37** [comment]
https://github.com/Expensify/App/issues/47302#issuecomment-2294470259

**Comment by VickyStash** [comment]
The [Draft PR](https://github.com/Expensify/App/pull/48728) is opened for this one. Waiting for API fixes to open it for the review. More details can be found [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1725613866403789).

**Comment by VickyStash** [comment]
**Updates:** still waiting for some additional API fixes.

**Comment by VickyStash** [comment]
Still waiting for API fixes.
Added a fix for the failure data [issue](https://github.com/Expensify/App/issues/48701#issuecomment-2346429429) to the Draft PR as well.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/48728) has been opened for the review.

Note: I'm going to be OOO next week (Sept 16-20) 🌴

**Comment by rezkiy37** [comment]
I will work on this issue this week 🙂

**Comment by rezkiy37** [comment]
Hello!
I am OOO from 19.09 - 23.09. I will continue to work on this one when I am back.

**Comment by rezkiy37** [comment]
I've prepared a draft PR (https://github.com/Expensify/App/pull/49782), however, we need to finish with this issue (https://github.com/Expensify/App/issues/45181) to open and merge the PR.

**Comment by rezkiy37** [comment]
>  [@rezkiy37] Determine if we should create a regression test for this bug.

No, it was not a bug.

**Comment by rezkiy37** [comment]
One thing left is to hide the invoice page behind the beta. [Slack](https://callstack-hq.slack.com/archives/C01GTK53T8Q/p1728394900093359?thread_ts=1728374637.256479&cid=C01GTK53T8Q).
