### ISSUE TITLE
[HOLD for Payment 2024-09-03] [$250] Chat - Unable to deselect user using The Tab key

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47306]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4847797
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to FAB > Start Chat
2. Using the tab key and Enter key select add to group multiple results from the contact lists
3. use the arrow and tab key and try to deselect the selected users

## Expected Result:
Able to deselect users using tab key

## Actual Result:
Unable to deselect user using The Tab key. User is navigated to 1:1 conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a96ad427-588d-4158-be18-1bfd533fd388

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018da70c1cbe5cf980</li>
        <li>Upwork Job ID: 1823397082345036137</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 103590029</li>
<li>Krishna2323 | Contributor | 103591698</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by sakluger** [comment]
@alitoshmatov can you take a look at the proposals we have so far?

**Comment by sakluger** [comment]
@ZhenjaHorbach thanks for handling C+ for this one!

**Comment by dangrous** [comment]
Sounds good to me! Let's attempt to swap out all the ACCESSIBILITY_ROLE instances for ROLE, like you said - but if it's too many and hard to test, then maybe we can do it later.

**Comment by sakluger** [comment]
I confirmed that this is live on prod! Moving to daily and handling payment.

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @ZhenjaHorbach $250, paid via Upwork
Contributor+: @Krishna2323 $250, paid via Upwork

@ZhenjaHorbach do you think we need regression test steps here? If so, could you please leave proposed test steps?

**Comment by ZhenjaHorbach** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@ZhenjaHorbach] The PR that introduced the bug has been identified. Link to the PR:

Unfortunately, I did not find a suitable PR
Plus this PR is more related to code refactoring and ACCESSIBILITY_ROLE removal

> * [x]  [ @ZhenjaHorbach] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

NA

> * [x]  [@ZhenjaHorbach] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

NA

> * [x]  [@ZhenjaHorbach] Determine if we should create a regression test for this bug.
> * [x]  [@ZhenjaHorbach] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

- Go to FAB > Start Chat
- Using the tab key and Enter key select add to group multiple results from the contact lists
- Use the arrow and tab key and try to deselect the selected users
- Verify user can be deselected using tab key

Do we agree 👍 or 👎

**Comment by ZhenjaHorbach** [comment]
@sakluger 
Done !

**Comment by sakluger** [comment]
Thanks!
