### ISSUE TITLE
[Payment Due August 22, 2024] [Performance] Use polyfill-force to speed up formatjs

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#47305]
Coming from [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1723532933205219)

**Proposal**: Use polyfill-force to skip the lookup in formatjs which checks whether the platform needs polyfilling

### Problem
`formatjs` checks whether the platform needs polyfilling for the respective polyfilling API. This appears redundant because we mean to have those APIs polyfilled, so we can skip the function `shouldPolyfill` . Doing so, results in the reduced app startup because we are skipping the lookup function `shouldPolyfill`.

### Solution
We are already using `polyfill-force` for some polyfills but not for all of them. So we just have to add it to others, for eg, require('@formatjs/intl-locale/polyfill-force');
- On iOS, we save around ~70ms on App startup.
- On Android, we save around ~15ms on App startup.

The PR with the changes is [here](https://github.com/Expensify/App/pull/47071) .

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by hurali97** [comment]
@mountiny Please assign this to me

**Comment by Beamanator** [comment]
Updated title to Awaiting Payment! 🙏

**Comment by anmurali** [comment]
Paid.
