### ISSUE TITLE
[HOLD for #46838] Room - User details page can't be opened from members list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47313]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2654638
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: #room conversation with at least 2 users, one that has a custom avatar and the other has a default avatar

1. Click on the header of the conversation
2. Click on Members
3. Click on the avatar in the user details page

## Expected Result:
In the conversation viewer, when clicking on the avatar of any of the users, a modal with the user information should display. When interacting the avatar inside the user details modal, a full size view of the avatar should display.

## Actual Result:
Clicking on user avatar leads to user select/unselect. User details page is not opened.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e6a12390-0d8a-455f-bbad-5b1a4f7b0f21

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment]
I don't really understand how the expected and actual results are associated with the video. I'm going to ask the team for some clarifications on what is expected here.

**Comment by Christinadobrzyn** [comment]
@trjExpensify could you take a peek at this and let me know what is expected here or who to ask?

**Comment by Christinadobrzyn** [comment]
This will be resolved with https://github.com/Expensify/App/issues/46838 and PR https://github.com/Expensify/App/pull/47201. 

I'm going to add a HOLD to this so we can test and make sure it's working as expected after https://github.com/Expensify/App/pull/47201 is deployed.

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/47201

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/47201

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/47201

Heads up that I'll be ooo 9/4 - 9/10. I'm not going to assign a new BZ teammate to this as we're working on the PR. If you need a BZ teammate, please ping in slack.

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/47201

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/47201

**Comment by Christinadobrzyn** [comment]
This is resolved with https://github.com/Expensify/App/pull/47201! Closing.
