### ISSUE TITLE
[$250]  Task - Error shows up when creating task as user who is invited to expense report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47311]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4848150
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B.
3. [User A] Click on the expense preview in the main chat to go to expense report.
4. [User A] Send a user mention containing User C.
5. [User A] Click Invite from the whisper message.
6. [User A] Send a message in the transaction thread.
7. [User C] Open the invited expense report.
8. [User C] Click + > Assign task.
9. [User C] Create a task in the expense report.

## Expected Result:
There should be no error when User C creates task in the invited expense report.

## Actual Result:
Error shows up when User C creates task in the invited expense report.
The task is created successfully despite the error (the task reappears after dismissing the error and refreshing the page).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7a181df8-90b9-449d-8f67-6441d3a82c01

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01494944ccab390faf</li>
        <li>Upwork Job ID: 1823910004775302987</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by VictoriaExpensify** [comment]
Yeah this looks buggy and should be fixed.

**Comment by Amoralchik** [comment]
I think it's a BE issue. 
Also, I think we need to change it to an internal label so someone from the internal team can check the `CreateTask` response

![image](https://github.com/user-attachments/assets/dc5b4221-6f42-4f66-963f-92c12349da2a)

Thank you.

**Comment by MonilBhavsar** [comment]
This is vip-vsb task project and we're currently pausing it https://expensify.slack.com/archives/C066HJM2CAZ/p1721760866963099?thread_ts=1721729395.916419&cid=C066HJM2CAZ
cc @VictoriaExpensify
