### ISSUE TITLE
[Payment Due Sept 30 2024] [$250] Workspace - "Hmm... it's not here" page opens twice for an invalid link with a RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47331]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4849349&group_by=cases:section_id&group_id=296763&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with any account
3. Open any deep link with the app that should display the "Hmm... it's not here" page and should open a RHP on web (https://staging.new.expensify.com/r/6821704960193694/details
)
4. Tap on the "<" button to go back
5. Tap on the "<" button to go back again

## Expected Result:
"Hmm... it's not here" page should only open once

## Actual Result:
"Hmm... it's not here" page opens twice for an invalid link with a RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9e932943-e6c3-471c-aba3-7cc8a48153e8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147fe785445dbe8f8</li>
        <li>Upwork Job ID: 1824283728870406581</li>
        <li>Last Price Increase: 2024-08-23</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sobitneupane** [comment]
@daledah Thanks for the proposal.

Is it possible to not open the deeplink (in this case, details page) if user doesn't have access to the report?

**Comment by sobitneupane** [comment]
Thanks for the update @daledah 

Yup. It makes sense to open the deeplink especially in browsers. What will be the impact of your proposal in large screen devices which opens the details page in RHP? I don't think we should change the report (even if Not Found) when user presses back button in RHP.

**Comment by sobitneupane** [comment]
Thanks for the update @daledah 

[Proposal](https://github.com/Expensify/App/issues/47331#issuecomment-2286662825) from @daledah looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by Beamanator** [comment]
Oh shit i'll review soon 🙏

**Comment by sobitneupane** [comment]
@Beamanator Is this ready for payment?

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $250 @daledah ([offer](https://www.upwork.com/nx/wm/offer/104568251))
- [ ] Reviewer: $250 @sobitneupane (via Manual Request)

Upwork job is [here](https://www.upwork.com/jobs/~0147fe785445dbe8f8).

**Comment by kadiealexander** [comment]
I'm going OOO so I'm adding someone to help with payment once the offer has been accepted.

**Comment by trjExpensify** [comment]
Payment due in a couple of days. Can we get a checklist for this? Thanks!

**Comment by trjExpensify** [comment]
Still awaiting the checklist!

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Login
2. Open deep link of details page of a report without access and verify that "Hmm... it's not here" page  is displayed.
3. Tap on the back button
4. Verify that: On big screen, the modal showing Not here page closes and On small screen, we are redirected to the home page.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment]
The issue arises from an inconsistency between the big screen and small screen displays. On small screens, when we close the first 'Not here' page, another 'Not here' page opens. The first 'Not here' page is for Details, and the second one is for the Report. However, on big screens, the first 'Not here' page appears in the RHP, clearly indicating that it’s for the Details page.

**Comment by trjExpensify** [comment]
Cool, thanks. Go ahead and request on NewDot, based [on this](https://github.com/Expensify/App/issues/47331#issuecomment-2434473706) payment summary. @daledah I've paid you in Upwork. 

This issue was created from this regression test failing. I've created an issue for Applause to discuss a suggested edit. Closing!

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
