### ISSUE TITLE
[$250] Room - "Please enter a room name" error appears when switching to the Room tab

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47335]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4849474&group_by=cases:section_id&group_id=296763&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Create a workspace
4. Navigate to the LHN
5. Navigate to FAB - Start chat
6. Tap on the "Room" tab

## Expected Result:
The error should only appear when i tap the "Create room" button without entering any room name.

## Actual Result:
"Please enter a room name" error appears when switching to the Room tab.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0af238bd-f143-4fb6-b884-39bbc9010844

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018c5e8d8993a6b3ba</li>
        <li>Upwork Job ID: 1823441957241129725</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103622010</li>
<li>dominictb | Contributor | 103622012</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ahmedGaber93** [comment]
Reviewing today

**Comment by ahmedGaber93** [comment]
Thanks all for the proposals.

@dominictb's [proposal](https://github.com/Expensify/App/issues/47335#issuecomment-2286473967) add a solution to prevent `onValidate` only while switching the tab.

@nyomanjyotisa's [proposal](https://github.com/Expensify/App/issues/47335#issuecomment-2286491044) add a solution to prevent `onValidate` all the time.

@Krishna2323's [proposal](https://github.com/Expensify/App/issues/47335#issuecomment-2287375592) add a solution to reset the form after tab switched.


While all the proposals can fix the issue, but @dominictb's [proposal](https://github.com/Expensify/App/issues/47335#issuecomment-2286473967) is the only that can fix it without change the current UX.

@dominictb's [proposal](https://github.com/Expensify/App/issues/47335#issuecomment-2286473967) LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by ahmedGaber93** [comment]
> This is an inconsistency because we also use tab navigator on start IOU request page and there if we switch tab the data and errors are cleared. See the video below.

I think the reset in IOU is for resetting the draft transaction in Onyx and not for design/UX purpose

**Comment by puneetlath** [comment]
I don't think we need to clear the input in this scenario. So @dominictb's proposal sounds good to me. But are there other similar forms on the site? And if so, would they need a similar solution?

**Comment by ahmedGaber93** [comment]
### Regression Test Proposal

1. Click on FAB icon > Start chat
2. Tap back and forth between on the "Room" and the "Chat" tab
3. Verify that: "Please enter a room name" error does not appear when switching the tab.

Do we agree 👍 or 👎

**Comment by ahmedGaber93** [comment]
@puneetlath This issue is ready for payment, The PR was deployed to production for 7 days ago (2/9) base on here https://github.com/Expensify/App/pull/47908#issuecomment-2325378109

**Comment by puneetlath** [comment]
All paid. Thanks everyone!
