### ISSUE TITLE
Notification - User receives notification with wrong sound

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47334]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4845404&group_by=cases:section_id&group_order=asc&group_id=295000
**Email or phone of affected tester (no customers):** gocemate+a949@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
1. Device volume should be turned on
2. App notifications should be enabled on browser for web and in app settings for the apps
3. A secondary device or browser will be used to send messages to the main testing device
Steps:
1. Navigate to the conversation with the secondary user
2. Secondary device - Send a message to the user in the main testing device

## Expected Result:
User should receive the correct sound notification
(https://www.dropbox.com/scl/fo/t3j9sstsml5yofsrf26od/AIUtqgtjunDRLz8ebrbJGmc/Attention?e=2&preview=Expensify_SB_SecretHandshake_UI_Attention_Mono_240109.mp3&rlkey=dpvqt7h5xjzdsafj4ent564ne&subfolder_nav_tracking=1&dl=0
)
while viewing the conversation with the other user

## Actual Result:
User does not receives the correct sound notification for new message while viewing the conversation with the other user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/user-attachments/assets/86d94f1e-61d5-48dd-9de0-8ae5e3be27ab

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment]
Still need to test this - will prioritize soon

**Comment by OfstadC** [comment]
This was discussed in a previous issue as well as [not a priority ](https://expensify.slack.com/archives/C01SKUP7QR0/p1718285670599889)
