### ISSUE TITLE
[Performance] Simplify isOneOnOneChat Logic and Improve Performance in getParticipantsAccountIDsForDisplay

### ISSUE THREAD

**Issue by gedu** [Expensify/App#47336]
### Problem

The current implementation of the `isOneOnOneChat` function uses a complex approach involving mapping and filtering over the participants in the report object. This includes parsing string keys to numbers and filtering out the current user, which can be streamlined for better readability and performance. Additionally, the `getParticipantsAccountIDsForDisplay` function includes extra mapping and string-to-number parsing inside filters, leading to inefficiencies.

### Solution

Refactor the `isOneOnOneChat` function to a simpler approach that avoids unnecessary mapping and filtering. Instead, directly manipulate the participant count and presence of the current user to determine if the chat is one-on-one. Likewise, improve the `getParticipantsAccountIDsForDisplay` function by moving the string-to-number parsing out of the filter to increase efficiency.

**Comment by gedu** [comment]
Hi, I'm Edu from Callstack and I want to work on this issue

**Comment by Beamanator** [comment]
discussing a bit in slack [here](https://expensify.slack.com/archives/C05LX9D6E07/p1723567205174509)

**Comment by ZhenjaHorbach** [comment]
@Beamanator 
I have a small question 😅

Since I reviewed this performance issue, am I eligible for a payment?

And If yes 

Looks like production deploy automation failed: This should be on [HOLD for Payment 2024-09-06] according to [prod deploy checklist](https://github.com/Expensify/App/issues/48035), confirmed in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q.)

**Comment by Beamanator** [comment]
@gedu any update on the discussions you linked here? https://github.com/Expensify/App/pull/47300#issuecomment-2312091013

@ZhenjaHorbach good call, i do believe you deserve payment! I think we can wait to see if the performance issue caused a regression or not before doing payment 🙏

**Comment by ZhenjaHorbach** [comment]
> @gedu any update on the discussions you linked here? [#47300 (comment)](https://github.com/Expensify/App/pull/47300#issuecomment-2312091013)
> 
> @ZhenjaHorbach good call, i do believe you deserve payment! I think we can wait to see if the performance issue caused a regression or not before doing payment 🙏

I don't mind waiting a little longer 😃
Although this PR has been in production for 2 weeks now

**Comment by OfstadC** [comment]
@Beamanator Let me know what you need from me here 😃

**Comment by Beamanator** [comment]
I ping'd @gedu in the PR [here](https://github.com/Expensify/App/pull/47300#issuecomment-2344696611), I think it makes sense to pay this out since, as @ZhenjaHorbach mentioned, the PR has been in prod for 2 weeks 🙏

**Comment by gedu** [comment]
The PR is merged and without regressions, should be all good, @Beamanator replied on the PR

**Comment by OfstadC** [comment]
## Payment Summary 
- @ZhenjaHorbach paid $250 via Upwork
