### ISSUE TITLE
[$250] Upgrade - Workspace upgrade message disappears in thread & #admins after opening in thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47337]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a Collect workspace.
3. Go to workspace settings > More features.
4. Enable Report fields.
5. Click Upgrade.
6. Go to #admins room and wait for "upgraded this workspace to the Control plan" message to show up.
7. Right click on "upgraded this workspace to the Control plan" > Reply in thread.

## Expected Result:
The system message "upgraded this workspace to the Control plan" will not disappear in thread.

## Actual Result:
The system message "upgraded this workspace to the Control plan" disappears (blank) in thread.
After returning to #admins, the message disappears.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b355e87c-e5c2-4275-a851-9b20884a5902

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01187d94254a4d4aa1</li>
        <li>Upwork Job ID: 1824171640013486517</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by mollfpr** [comment]
Not overdue 👀

**Comment by VincentCorleone** [comment]
I think this is a backend issue. I observed that the text "upgraded this workspace to the Control plan" occured in the api "/api/UpgradeToCorporate"(trigged when clicking upgrade) but not the api "/api/OpenReport"(trigged when open #admin room ).

**Comment by isabelastisser** [comment]
@mollfpr, what do you think of the comment above? Is this a backend issue?

**Comment by mollfpr** [comment]
Yeah, I believe this is a BE issue. The response from API `UpgradeToCorporate` has the action with the message `upgraded this workspace to the Control plan`, but it emptied from the `OpenReport` response.

<details>
<summary>UpgradeToCorporate</summary>

![Screenshot 2024-08-23 at 16 59 23](https://github.com/user-attachments/assets/a50b8943-f53f-48a3-9b22-c2f28969a171)

</details>

<details>
<summary>OpenReport</summary>

![Screenshot 2024-08-23 at 16 59 06](https://github.com/user-attachments/assets/13321e79-abd1-4d67-b00b-a279d26199ed)

</details>

**Comment by isabelastisser** [comment]
Internal issue: waiting for assignment.

**Comment by isabelastisser** [comment]
Internal issue: waiting for assignment.

**Comment by isabelastisser** [comment]
There are no updates; we need an engineering assignment here.

cc @dylanexpensify

**Comment by isabelastisser** [comment]
We still need an internal engineering assignment. @dylanexpensify, I will DM you. Maybe you'll be able to help here since you're the curator. Thanks!

**Comment by garrettmknight** [comment]
@youssef-lr assigning you to investigate since you built the BE of Upgrades. Any idea what's going on here?

**Comment by isabelastisser** [comment]
Hi @youssef-lr, do you have an update here? Thanks!

**Comment by youssef-lr** [comment]
Looking into this one tomorrow!

**Comment by isabelastisser** [comment]
Any updates, @youssef-lr?

**Comment by isabelastisser** [comment]
Bump @youssef-lr

**Comment by isabelastisser** [comment]
Hey @youssef-lr, any updates?

**Comment by isabelastisser** [comment]
Any updates, @youssef-lr? Thanks!

**Comment by youssef-lr** [comment]
I'm on it this week @isabelastisser

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
