### ISSUE TITLE
[Support CSV][Web-E] Create ExportTagsCSV

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#47348]
~HOLD https://github.com/Expensify/App/issues/47351~

Implement this section of the doc https://docs.google.com/document/d/1YfARkp3Zko6hDjS1EnO84gy7gGmoRK712ZJf-wmDNRw/edit#bookmark=id.zh21uu2n2knt

**Comment by sakluger** [comment]
The PR https://github.com/Expensify/Web-Expensify/pull/43181 fixes this issue. @rlinoz, are there any other PRs required for this issue, or can we close it after that PR is deployed to prod?

**Comment by rlinoz** [comment]
We can close after the PR is merged!

**Comment by sakluger** [comment]
Nice! I'll close for now - we can always reopen if it causes issues.
