### ISSUE TITLE
[CRITICAL] [Advanced Approval Workflows] Add the ability on the backend to change default approver

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#47344]
# Problem
The backend doesn't currently support this (it was missed during implementation)

## Why this is important to solve
The UI has to be able to change the default approver for a policy. 

# Solution
- Add the param `approver` to the `SetWorkspaceApproval` Auth command
- When it is present, change the `policy.approver` value
- All employees in the employeeList that had `submitsTo` set to the previous `policy.approver` must be updated to submit to the new policy approver

cc @blazejkustra @JmillsExpensify

**Comment by tgolen** [comment]
@blazejkustra so that you are aware:

- The new parameter is called `defaultApprover` and is a string that is the email of who you want to set as the new default approver
- The `SetWorkspaceApproval` commands will require either an `employees` or a `defaultApprover` param, but at least one of them is required, and you should NOT send both params (if you do, only `defaultApprover` will be applied)

**Comment by blazejkustra** [comment]
> The SetWorkspaceApproval commands will require either an employees or a defaultApprover param, but at least one of them is required, and you should NOT send both params (if you do, only defaultApprover will be applied)

Uff that's tough, what if we want to change the default approver and add additional changes to the workflow like this:


https://github.com/user-attachments/assets/34cd9c7e-b052-4cc2-b0ca-e4f1b0cba9e8

**Comment by blazejkustra** [comment]
Also setting the `defaultApprover` doesn't seem to work for me 😢 (request id: `8b2e97e28dc4bf88-WAW`)

https://github.com/user-attachments/assets/c645d85b-19f0-4b1d-a86f-04f510669930

**Comment by tgolen** [comment]
# Daily Update
- I realized there was a bug in the existing code where changing the default approver will modify the entire employeeList, rather than just the people submitting to the previous default approver. I've submitted an [Auth PR](https://github.com/Expensify/Auth/pull/12044) to fix that.
- We are [discussing in Slack](https://expensify.slack.com/archives/C06ML6X0W9L/p1723647983209769?thread_ts=1723491433.389249&cid=C06ML6X0W9L) how to allow changes to both defaultApprover and the employeeList at the same time to address [this comment](https://github.com/Expensify/App/issues/47344#issuecomment-2287893365)

### Next Steps
- @tgolen once the slack convo is resolved, I'll write another Auth PR to implement the changes
- @blazejkustra will also probably need to make some changes on the FE so that all the logic is aligned

#### ETA
- All PRs written and ready for review by Monday, Aug 19

**Comment by tgolen** [comment]
The decision was to go with this solution for now:

Only have the `defaultApprover` param apply to `policy.approver `and rely on `employees` param to change `policy.employeeList`. This assumes that the code/person using the params knows absolutely what they are doing. If they get these params wrong, it can really make a mess of things. But I suppose we are kind of making that assumption anyway, so it's not so bad.

**Comment by tgolen** [comment]
# Daily Update
- I have written an [Auth PR](https://github.com/Expensify/Auth/pull/12051) to implement the above solution

### Next Steps
- @rlinoz review and merge the PR
- Wait for deploye
- @blazejkustra will then have to implement the change in the FE

#### ETA
- Backend deployed by Friday, Aug 16

**Comment by tgolen** [comment]
# Daily Update
- The [Auth PR](https://github.com/Expensify/Auth/pull/12051) has been deployed
- I'm gonna close out this issue now

### Next Steps
- @blazejkustra will implement this on the fontend

**Comment by blazejkustra** [comment]
I'll into it tomorrow (I have one simple task on me that was waiting for couple of weeks)👌
