### ISSUE TITLE
 [AU] Split - Unable to create split expense in group chat "The sum of splits" error appears

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47359]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4852283&group_by=cases:section_id&group_id=295816&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Navigate to FAB - Start chat
4. Make a group chat with two new Gmail members
5. In the group chat, navigate to Composer "+" button - Split expense
6. Enter any amount and tap on the "Next" button

## Expected Result:
I should be able to do a split in a group chat without any error messages. The participants should only be the members of the group chat.

## Actual Result:
Unable to create a split expense in a group chat. "The sum of splits must equal the total amount." error message appears. Two "Unavailable workspace" members are also added.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c6d07e87-7b8a-4b7f-8d3a-3450908175e0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-split

**Comment by RachCHopkins** [comment]
#vip-split is on hold as far as I'm aware, and the menu item is not far from being removed. Just checking in on this.

**Comment by RachCHopkins** [comment]
VIP Split is on hold, If this is the same underlying issue as the other, let's close this one.
