### ISSUE TITLE
[Support CSV] Create import flow for categories

### ISSUE THREAD

**Issue by rlinoz** [Expensify/App#47357]
Create the [basic components/functions of the import flow](https://docs.google.com/document/d/1YfARkp3Zko6hDjS1EnO84gy7gGmoRK712ZJf-wmDNRw/edit#bookmark=id.hyv4e7d1rcet) and then complete [this section of the doc](https://docs.google.com/document/d/1YfARkp3Zko6hDjS1EnO84gy7gGmoRK712ZJf-wmDNRw/edit#bookmark=id.nghzwfmmmdgr) for categories (as the example).

Let's leave the export flow for another issue so we don't have to block this on the backend.

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by mallenexpensify** [comment]
@rlinoz are you wanting @ikevin127 , the C+, to complete the work or to open the job to contributors, where Kevin would review their proposals?  whomever works on it would need access to the design doc, which makes me think having a C+ assigned to do the work might be best.

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this issue

**Comment by rlinoz** [comment]
Im will switch the C+ here since @rushatgabhane is going to be helping with reviews for this project.

And @filip-solecki will be implementing it.

**Comment by mallenexpensify** [comment]
Looks like the PR hit production on 09-05, https://github.com/Expensify/App/pull/47827#issuecomment-2332464858 

@rushatgabhane are you due payment here?  Thx

**Comment by rushatgabhane** [comment]
nope not due for payment here

**Comment by mallenexpensify** [comment]
Thx @rushatgabhane , we should be good to close then

**Comment by sobitneupane** [comment]
During the import flow, the `enabled` column was compared directly against 'true' without normalizing the input. As a result, values like `'TRUE'` or `'True '` were incorrectly interpreted as `false`.
Issue: https://github.com/Expensify/App/issues/87033
