### ISSUE TITLE
[$250] Settings - Take photo option is missing for uploading a profile avatar image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47358]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4852296&group_by=cases:section_id&group_id=229064&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Tap on "Account settings"
4. Tap on the avatar

## Expected Result:
I should be able to take a photo for the avatar

## Actual Result:
Take photo option is missing for uploading a profile avatar image. The gallery opens
Samsung Galaxy A52s 5G

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8cf8dfd9-aea1-49f7-b38e-0466fe3b3286

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011cd8972e087510c8</li>
        <li>Upwork Job ID: 1826240108874477245</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by JmillsExpensify** [comment]
Will open up the issue for proposals since this is possible on native mobile

**Comment by JmillsExpensify** [comment]
Still open for proposals. I'll keep it open though I don't think it's worth a higher price so keeping that the same.

**Comment by mollfpr** [comment]
I can reproduce the issue with a physical device, not with the emulator.

The RCA from @daledah seems correct and it's a known bug that was reported https://issuetracker.google.com/issues/317289301. 

@daledah Is the step 2 in your solution is a must? I think we already have the validation with the file type for avatar.

**Comment by mollfpr** [comment]
>I believe we need to keep it. Without it, an error message appears below the avatar field whenever an incorrect file is selected.

@daledah I think it's okay for now, as long the incorrect file didn't get uploaded.

Let's go with @daledah [proposal](https://github.com/Expensify/App/issues/47358#issuecomment-2287675889) without validation.

🎀 👀 🎀 C+ reviewed!

**Comment by puneetlath** [comment]
@mollfpr @daledah what's the status of this? Is it done?

**Comment by mollfpr** [comment]
It seems the automation has failed to update the status. The PR is deployed to the production on 6th September, and there's no deploy blocker linked to the issue. So it's ready for the payment.

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good!

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Login to the App
2. Navigate to "Account settings"
3. Tap on the avatar
4. Verify that: Take photo option is shown
5. 👍 or 👎

**Comment by puneetlath** [comment]
Payment summary: 
- C - $250 - @daledah  - to be paid via Upwork
- C+ - 250 - @mollfpr  - to be paid via NewDot

@daledah I don't see a contract for you for this issue. Can you link me your Upwork profile?

**Comment by garrettmknight** [comment]
$250 approved for @mollfpr

**Comment by puneetlath** [comment]
@daledah offer sent here: https://www.upwork.com/nx/wm/offer/104289314

Please ping me on this issue when you've accepted.

**Comment by puneetlath** [comment]
@daledah bump!

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
