### ISSUE TITLE
Prod app deploy gets cancelled due to Staging deploy happening at the same time

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#47363]
**Slack conversation:** https://expensify.slack.com/archives/C07J32337/p1723582974942859?thread_ts=1723582659.792279&cid=C07J32337

## Action Performed:
Deployed the standard way (checklist: https://github.com/Expensify/App/issues/47219)

## Expected Result:
Staging & Prod deploys should be able to happen concurrently

## Actual Result:
Prod deploy [canceled itself](https://github.com/Expensify/App/actions/runs/10376393226/attempts/1) due to `Canceling since a higher priority waiting request for 'Build and deploy android, desktop, iOS, and web clients-release' exists`

## Solution:

[Manual]
1. Retry job (had to manually release prod Android app)

[Other]
1. Fix the `cancel-in-progress` flag

**Comment by Beamanator** [comment]
cc @AndrewGable @roryabraham 🙏

**Comment by roryabraham** [comment]
Going to help out with this while @AndrewGable is working on fixing HybridApp builds

**Comment by roryabraham** [comment]
this is fixed
