### ISSUE TITLE
[$250] Use the video viewing data in FS to remove it and give users a clean path straight to stage 2 onboarding from stage 1

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#47369]
Coming from [this conversation](https://expensify.slack.com/archives/C036QM0SLJK/p1723574568733799?thread_ts=1723511235.420929&cid=C036QM0SLJK), and using the benefit of [this data](https://expensify.slack.com/archives/C036QM0SLJK/p1722014812516779), we are going to remove the welcome video that appears in a modal when the new sign up completes Stage 1 onboarding:

For clarity, it is the welcome video you see after the name is entered. Nothing else changes. The user simply lands where they land today after they X out of the welcome video (or click `Get Started`) directly after Stage 1 onboarding

https://github.com/user-attachments/assets/08d96199-caae-4c78-a379-4fac9ca71c09

 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013dde41340f7a240d</li>
        <li>Upwork Job ID: 1823491384277230019</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103588666</li>
<li>neonbhai | Contributor | 103588671</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by ahmedGaber93** [comment]
> Coming from [this conversation](https://expensify.slack.com/archives/C036QM0SLJK/p1723574568733799?thread_ts=1723511235.420929&cid=C036QM0SLJK), and using the benefit of [this data](https://expensify.slack.com/archives/C036QM0SLJK/p1722014812516779), we are going to remove the welcome video that appears in a modal when the new sign up completes Stage 1 onboarding:

@anmurali I don't have access to those links, so just for confirmation, are we will stop showing it now With the possibility of re-showing it later, or will we stop showing it permanently?

I am asking for that to determine if we will remove its files completely from source code, or just remove its implementation (the lines that displaying it)

**Comment by anmurali** [comment]
I would rather just remove its implementation for now. Thank you for checking @ahmedGaber93

**Comment by ahmedGaber93** [comment]
The first [proposal](https://github.com/Expensify/App/issues/47369#issuecomment-2287379309) by @neonbhai LGTM!

🎀 👀 🎀 C+ reviewed

**Comment by ahmedGaber93** [comment]
Not overdue, issue is assigned and PR in progress.

**Comment by ahmedGaber93** [comment]
This is a disabling feature issue, and it is a straight forward fix, I don't think we need a regression test here.

**Comment by ahmedGaber93** [comment]
@anmurali @AndrewGable This issue is ready for payment, The PR was deployed to production for 10 days ago base on here https://github.com/Expensify/App/pull/47961#issuecomment-2322123158.

**Comment by ahmedGaber93** [comment]
@anmurali @AndrewGable Bump! ^

**Comment by anmurali** [comment]
Paid.
