### ISSUE TITLE
 mWeb/Chrome - Task - "Copy to clipboard" is highlighted on the task action menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47362]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Open self DM
4. Tap on Composers "+" button - Assign task
5. Set any title and tap on the "Next" button
6. Tap on the "Confirm task" button
7. Long tap on the task

## Expected Result:
No action should be highlighted.

## Actual Result:
"Copy to clipboard" is highlighted on the task action menu.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b438cda0-c37f-4054-aa59-2f2651c5a45a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by twisterdotcom** [comment]
I can't reproduce: https://github.com/user-attachments/assets/e2976749-82f5-414f-b5a1-2d0fbc2b0efa

**Comment by twisterdotcom** [comment]
Again, I still can't recreate: https://drive.google.com/file/d/1CMI7lSE-Oej63muWnp0v8s-6mLkHR-Qd/view?usp=sharing
