### ISSUE TITLE
[AWAITING PAYMENT][$250] [3rd Party Feeds] Card Assignment Flow

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#47377]
# Part of the Third Party Workspace Feeds project
Main issue: https://github.com/Expensify/Expensify/issues/394008
Doc section: [Doc Link](https://docs.google.com/document/d/1PXx506PM7-sGW3Zones8mWieZgnqRJ5qYXzTOZ3dnlg/edit?pli=1#bookmark=id.1nepqnukw5fa)
Project: [<Project Link>](https://github.com/orgs/Expensify/projects/130/views/11)

# Feature Description
- [x] Card Assignment Flow  (@koko57)
- [x] Card List (@koko57)
- [ ] Card Details (@narefyev91)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845999902674751168</li>
        <li>Upwork Job ID: 1845999902674751168</li>
        <li>Last Price Increase: 2024-10-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by joekaufmanexpensify** [comment]
I'm working with this Robert on this project, but I don't need to be assigned to every frontend new feature issue, as the work here is just regular BZ management. Going to revert back to the chosen auto-assignee!

**Comment by joekaufmanexpensify** [comment]
@jliexpensify , as an fyi @narefyev91 and @koko57 are working on this, and as soon as they comment, you'll be able to assign them! Setting to daily as this is deliverable by September 9th, 2024

**Comment by narefyev91** [comment]
I'm Nicolay from Callstack - will work on this issue

**Comment by koko57** [comment]
I will work on the Card Assignment Flow and Card List

**Comment by jliexpensify** [comment]
Thanks, assigned both of you

**Comment by koko57** [comment]
I'm starting working on Card Assignement flow, tomorrow I'll be focusing mainly on this issue.

**Comment by VickyStash** [comment]
Hi! I'm going to help @koko57 with Card List implementation here

**Comment by koko57** [comment]
Still working on Card Assigment Flow, I'm halfway through the process.

**Comment by joekaufmanexpensify** [comment]
TY for the update!

**Comment by VickyStash** [comment]
**Updates:** Continue to work on the Cards List page implementation. I think I should be able to open the PR tomorrow if nothing unexpected comes up.

**Comment by joekaufmanexpensify** [comment]
Assigned @allroundexperts as they're going to review PRs here

**Comment by koko57** [comment]
Most of the work is done for Card Assignement Flow, but I still have a few things to do there. I'm not sure if I'll be able to open the PR today, but I'll do my best to open it no later than tomorrow.

**Comment by VickyStash** [comment]
**Updates:**
- I've prepared the [Draft PR](https://github.com/Expensify/App/pull/48176) and now preparing screenshots. I've noticed some UI issues on iOS, and I'm going to fix it tomorrow morning.

**Comment by VickyStash** [comment]
The Company Cards List [PR](https://github.com/Expensify/App/pull/48176) is ready for the review

**Comment by koko57** [comment]
PR for Card Assignment Flow is opened https://github.com/Expensify/App/pull/48278 although I need to test it on the mobile devices. I think it would be good to merge https://github.com/Expensify/App/pull/48176 first

**Comment by jliexpensify** [comment]
@allgandalf can you add you Upworks name to your GH profile please?

**Comment by jliexpensify** [comment]
@joekaufmanexpensify @yuwenmemon can you confirm these amounts are correct for PR reviews?

- C+: @allgandalf $250
- C+: @allroundexperts $250 (ND payment)

**Comment by joekaufmanexpensify** [comment]
Yeah, I think that is the correct payments for the issue. We should issue them after all PRs on the issue are merged, and have been in production for 7 days.

**Comment by jliexpensify** [comment]
It looks like we might be waiting on https://github.com/Expensify/App/pull/48278 to hit Prod.

Just a heads up - I am OOO from the 3rd to 14th. I'll keep this assigned to myself though, I don't think any payments will need to be done during this period.

**Comment by jliexpensify** [comment]
[Upworks job and Payment Summary here](https://github.com/Expensify/App/issues/47377#issuecomment-2330608906)

**Comment by jliexpensify** [comment]
Invited @allgandalf

**Comment by jliexpensify** [comment]
@allgandalf - is a checklist needed?

**Comment by jliexpensify** [comment]
Paid and job closed!

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
