### ISSUE TITLE
[hold for payment 2024-09-10] [3rd Party Feeds] Card Feed Settings

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#47378]
# Part of the Third Party Workspace Feeds project
Main issue: https://github.com/Expensify/Expensify/issues/394008
Doc section: [Doc Link](https://docs.google.com/document/d/1PXx506PM7-sGW3Zones8mWieZgnqRJ5qYXzTOZ3dnlg/edit?pli=1#bookmark=id.te0fbeg8e95h)
Project: [<Project Link>](https://github.com/orgs/Expensify/projects/130/views/11)

# Feature Description
- [x] Card Feed Settings (@narefyev91 , @waterim )
- [x] Feed Selector (@koko57)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f1e4d902cd62bfc</li>
        <li>Upwork Job ID: 1823734663119215844</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103602407</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by joekaufmanexpensify** [comment]
@narefyev91 @waterim @koko57 could you please comment so I can assign you?

**Comment by narefyev91** [comment]
Hey! I'm Nicolay from Callstack - will work on this issue. Thansk!

**Comment by joekaufmanexpensify** [comment]
@narefyev91 is there an order of operations for which issues you're focusing on first?

**Comment by koko57** [comment]
I will work on Feed Selector

**Comment by joekaufmanexpensify** [comment]
Assigned!

**Comment by VickyStash** [comment]
Hi! I'm Viktoryia from Callstack, and I'll take over Agata's _Feed Selector_ part

**Comment by joekaufmanexpensify** [comment]
Sounds good!

**Comment by VickyStash** [comment]
**Updates:** I've implemented a new route and component for the FeedSelector page. I still need to do some updates for the feed options display. The updates can be tracked in this [branch](https://github.com/VickyStash/Expensify/tree/feature/47378-feeds-selector).

**Comment by VickyStash** [comment]
Hey @shawnborton, could you please provide me with correctly exported images for these three cards?

![image](https://github.com/user-attachments/assets/6cabb953-8984-4ef5-ae98-d4a9b983f0e0)

**Comment by shawnborton** [comment]
Try these: [CardLogos.zip](https://github.com/user-attachments/files/16710280/CardLogos.zip)

I set them all up at 40x40 so they can be used like other avatars throughout the product. cc @dubielzyk-expensify in case you have any changes there

**Comment by VickyStash** [comment]
**Updates:**
- improved the feeds option display
- implemented feed selection logic
- prepared the [Draft PR](https://github.com/Expensify/App/pull/47851). There are some overlaps with [another PR](https://github.com/Expensify/App/pull/47719), so I'm waiting for it to be merged before opening mine.

**Comment by dubielzyk-expensify** [comment]
> I set them all up at 40x40 so they can be used like other avatars throughout the product. cc @dubielzyk-expensify in case you have any changes there

Awesome. Can you chuck them in our design system as well? Would be handy to have easily accessible 😇

**Comment by shawnborton** [comment]
Added to the system:
![CleanShot 2024-08-23 at 07 06 04@2x](https://github.com/user-attachments/assets/1a6aa574-dccd-4828-b67c-8ae053cec1c5)

And @VickyStash I made a few slight tweaks to use whole numbers instead of some weird sizes we got from scaling, can you update them again? Here they are: [CardArtwork.zip](https://github.com/user-attachments/files/16727764/CardArtwork.zip)

**Comment by shawnborton** [comment]
Also when @dannymcclain gets back - curious for both of your opinions - do we want those separated into different components, or use variants?

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/47851) with Feed Selector page implementation has been opened for review.

**Comment by dubielzyk-expensify** [comment]
> Also when @dannymcclain gets back - curious for both of your opinions - do we want those separated into different components, or use variants?

I think one component with multiple variants is the right move here. Keen on @dannymcclain 's thoughts too

**Comment by joekaufmanexpensify** [comment]
PR in review.

**Comment by joekaufmanexpensify** [comment]
Done!

**Comment by joekaufmanexpensify** [comment]
Both PRs merged here

**Comment by robertjchen** [comment]
Thanks!

**Comment by ZhenjaHorbach** [comment]
I suppose I am entitled to payment after the end of the regressive period

**Comment by ZhenjaHorbach** [comment]
> Yep! Reopening for now. Last PR deployed to prod on September 10th, so payment is due then.

Thanks !

**Comment by joekaufmanexpensify** [comment]
Course!

**Comment by joekaufmanexpensify** [comment]
Okay, only payment here is $250 to @ZhenjaHorbach for C+ review!

**Comment by joekaufmanexpensify** [comment]
@ZhenjaHorbach offer sent for $250!

**Comment by joekaufmanexpensify** [comment]
@rayane-djouah you have an auto-upwork offer for this job, but I don't see that you reviewed any PRs here, so closing it without payment. LMK if that is not correct.

**Comment by ZhenjaHorbach** [comment]
> @ZhenjaHorbach offer sent for $250!

Done !

**Comment by joekaufmanexpensify** [comment]
@ZhenjaHorbach $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, thanks everyone!
