### ISSUE TITLE
Distance rates - Offline indicator is not at the page bottom in Settings page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47374]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings.
3. Go to Distance rates.
4. Tap Settings.
5. Go offline.

## Expected Result:
Offline indicator appears at the bottom of the page.

## Actual Result:
Offline indicator is below the content.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6e867e09-4563-4537-8843-1ff58110ee08

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by jliexpensify** [comment]
@MonilBhavsar pretty sure this won't be a deploy blocker, right? This seems like a minor UI issue.

**Comment by jliexpensify** [comment]
Nice, ty @Krishna2323 - I'll assign @eVoloshchak, and luckily @MonilBhavsar was the engineer on that PR too

**Comment by MonilBhavsar** [comment]
@nkdengineer would you be please able to take a look

**Comment by nkdengineer** [comment]
I will raise the PR to fix this issue soon.

**Comment by MonilBhavsar** [comment]
Thank you!

**Comment by nkdengineer** [comment]
@eVoloshchak we have a follow PR [here](https://github.com/Expensify/App/pull/47391)

**Comment by MonilBhavsar** [comment]
Thank you for the quick follow up! Appreciate it

**Comment by MonilBhavsar** [comment]
Issue is fixed. Thanks all!
