### ISSUE TITLE
[$250] [3rd Party Feeds] Viewing cards on workspace member profile

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#47379]
# Part of the Third Party Workspace Feeds project
Main issue: https://github.com/Expensify/Expensify/issues/394008
Doc section: [Doc Link](https://docs.google.com/document/d/1PXx506PM7-sGW3Zones8mWieZgnqRJ5qYXzTOZ3dnlg/edit?pli=1#bookmark=id.i5d5h1svhxih)
Project: [<Project Link>](https://github.com/orgs/Expensify/projects/130/views/11)

# Feature Description
- [ ] Viewing cards on workspace member profile (@narefyev91)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0168a85f62beed459e</li>
        <li>Upwork Job ID: 1823734911238437301</li>
        <li>Last Price Increase: 2024-08-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by joekaufmanexpensify** [comment]
I'm working with this Robert on this project, but I don't need to be assigned to every frontend new feature issue, as the work here is just regular BZ management. Going to revert back to the chosen auto-assignee!

**Comment by joekaufmanexpensify** [comment]
@VictoriaExpensify, as an fyi @narefyev91 is working on this, and as soon as he comments, you'll be able to assign him! Setting to daily as this is deliverable by September 9th, 2024

**Comment by narefyev91** [comment]
Hey! I'm Nicolay from Callstack - please assign this issue to me. Thanks!

**Comment by VictoriaExpensify** [comment]
Any updates here @narefyev91 ?

**Comment by narefyev91** [comment]
> Any updates here @narefyev91 ?

Hey nothing for now - but probably PR will be during this week for sure

**Comment by joekaufmanexpensify** [comment]
@alitoshmatov as an fyi, going to reassign you here, since @allroundexperts is [working on this project](https://expensify.slack.com/archives/C02NK2DQWUX/p1724762886813149). LMK if you have any questions!

**Comment by robertjchen** [comment]
in progress

**Comment by VictoriaExpensify** [comment]
Not overdue

**Comment by VictoriaExpensify** [comment]
Hey @robertjchen - I don't think this is overdue but let me know if you need anything on this one

**Comment by koko57** [comment]
I'm working on Multiple Feed Selector (link to the docs [here](https://docs.google.com/document/d/1PXx506PM7-sGW3Zones8mWieZgnqRJ5qYXzTOZ3dnlg/edit?pli=1#bookmark=id.gq95qggo6uj7)). I'm still working on it. I will open my PR after this PR is merged https://github.com/Expensify/App/pull/48491

**Comment by koko57** [comment]
Still waiting on https://github.com/Expensify/App/pull/48491

**Comment by koko57** [comment]
I've opened a [draft PR](https://github.com/Expensify/App/pull/49148) for my part - waiting for Nikolay's PR to be merged to resolve all merge conflicts

**Comment by koko57** [comment]
PR ready for review: https://github.com/Expensify/App/pull/49148

**Comment by allroundexperts** [comment]
Hi!

Can someone please handle my payments for this issue? I reviewed two PRs. @VictoriaExpensify @aldo-expensify

**Comment by aldo-expensify** [comment]
@robertjchen I'll assign you here since you oversaw the implementation of this feature

**Comment by aldo-expensify** [comment]
Changing to `Daily` for handling the payment faster

**Comment by VictoriaExpensify** [comment]
Sorry, was getting clarification on the process for multiple payments. Making payment now

**Comment by VictoriaExpensify** [comment]
Payment summary:
C+: @allroundexperts owed $500 via NewDot (2 PRs reviewed)

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
