### ISSUE TITLE
Report field-List value added & saved in offline is not greyed out

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47383]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home

2. Tap profile -> workspaces -> workspace
3. Tap more features -> Enable report field
4. Tap on the report field
5. Go offline
6. Enter name & save
7. Select "List" type & save
8. Tap save
9. Note field added is greyed
10. Open the newly created field
11. Tap list value
12. Add a value & save

## Expected Result:
List value added & saved in offline must be greyed out.

## Actual Result:
List value added & saved in offline is not greyed out.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e98ccbe1-d001-4490-80c4-baecfc82a7f5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by NikkiWines** [comment]
@IuliiaHerets, to just confirm something - was this issue was the result of testing from a particular PR? or was found during our standard regression test?

**Comment by NikkiWines** [comment]
Also based on [this PR](https://github.com/Expensify/App/pull/46961) it seems the behavior is expected and that the values should _not_ be greyed out. 

> ### Offline tests
> 
> 1. Create, edit, or delete list values of a report field of a workspace.
> 2. Verify that changes are applied immediately.
> 3. Verify that the list values are not grayed out.

cc: @rezkiy37 @shubham1206agra @mountiny  to confirm 🙏

**Comment by mountiny** [comment]
@NikkiWines Correct this is now expected. @IuliiaHerets @kavimuru @lanitochka17 Can you please make sure the regression tests are updated to cover this change?

**Comment by NikkiWines** [comment]
Closing as this is a non-issue
