### ISSUE TITLE
Android – Taxes settings – Focus moves to the value beginning when edit new tax rate value

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47389]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4858329
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in
3. Create a new workspace
4. Navigate to the workspace editor
5. Navigate to "More Features" and enable Taxes
6. Navigate to Taxes and tap on Add rate
7. Enter Name
8. Enter value and save (do not save rate)
9. Open value again

## Expected Result:
Focus is after value number

## Actual Result:
Focus moves to the value beginning

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d6d5f8b9-e3bb-47d0-9359-06db2f85c361

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kadiealexander** [comment]
Android <> ios bug swap

**Comment by jliexpensify** [comment]
Not able to repro on Staging v21-3.

Focus is always at the end of the value/after value number.
