### ISSUE TITLE
[Hold for payment 2024-09-24][$250] Search - Receipt thumbnail for invoice has plus icon when receipt cannot be added to invoice

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47103
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Send an invoice to anyone.
4. Navigate to https://staging.new.expensify.com/search?q=type%3Ainvoice%20status%3Aall%20sortBy%3Adate%20sortOrder%3Adesc&isCustomQuery=false

## Expected Result:
The receipt thumbnail should be the one with slash since receipt cannot be added to the invoice.

## Actual Result:
The receipt thumbnail is the one with plus icon when receipt cannot be added to the invoice.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/14bc371e-afea-4065-b5cf-2f40f66a0fec

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa6135aceb8a13a1</li>
        <li>Upwork Job ID: 1826302641073396964</li>
        <li>Last Price Increase: 2024-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103739745</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @danieldoglas</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt thumbnail for invoice has plus icon when receipt cannot be added to invoice

### What is the root cause of that problem?
Currently to show the plus icon (which indicates the user can edit receipt) we are depending on `transactionItem.canDelete`
https://github.com/Expensify/App/blob/d5904ba33e670ca2ca4e27f59162188ec35b0a45/src/components/SelectionList/Search/TransactionListItemRow.tsx#L81
which is doesn't appropriately determine if the receipt is editable
### What changes do you think we should make in order to solve the problem?

When the user opens it it will see the transaction in money request view which has the correct method inside it to determine if the receipt can be edited. What we should do is use the logic we use in money request view to determine if the receipt is editable
https://github.com/Expensify/App/blob/4496333dea008e0bd59ac3782ecd62be82483cfc/src/components/ReportActionItem/MoneyRequestView.tsx#L198-L199
```
  const parentReportAction = getIOUActionForReportID(transactionItem.reportID, transactionItem.transactionID);
    const [report] = useOnyx(`${ONYXKEYS.COLLECTION.REPORT}${transactionItem.reportID ?? '-1'}`);
    const canUserPerformWriteAction = !!ReportUtils.canUserPerformWriteAction(report);
    const canEditReceipt = canUserPerformWriteAction && ReportUtils.canEditFieldOfMoneyRequest(parentReportAction, CONST.EDIT_REQUEST_FIELD.RECEIPT);

    const canModifyReceipt = isViewAction && canEditReceipt;

```
### What alternative solutions did you explore? (Optional)

**Comment by OfstadC** [comment]
Asking about this in Slack

**Comment by OfstadC** [comment]
Being discussed [here](https://expensify.slack.com/archives/CSL3XBCCR/p1723750364955149)

**Comment by OfstadC** [comment]
@davidcardoza do we want to fix this if we are going to soon add this functionality (adding receipts to Invoices)?

**Comment by davidcardoza** [comment]
yes, I think so.

**Comment by koli07142** [comment]
https://github.com/user-attachments/assets/3948d5da-9835-432d-a105-5293114879dd

**Comment by koli07142** [comment]
Contributor details
Your Expensify account email: <suminabsumi@gmail.com
Upwork Profile Link: <REPLACE LINK HERE>

**Comment by koli07142** [comment]
Contributor details
Your Expensify account email: <suminabsumi@gmail.com>
Upwork Profile Link: https://www.upwork.com/freelancers/~0152002094b3e5839a

Uploading screen-20240822-012149.mp4…

**Comment by koli07142** [comment]
> ⚠️ Missing/invalid email or upwork profile link. Please make sure you add both your Expensify email and Upwork profile link in the format specified.

Contributor details
Your Expensify account email: suminabsumi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0152002094b3e5839a

**Comment by danieldoglas** [comment]
Assigned @FitseTLT

**Comment by OfstadC** [comment]
Looks like this was deployed to production yesterday, so should be paid out 2024-09-24. And I believe we need to pay @FitseTLT & @aimane-chnaif. If i'm missing anyone, please let me know! 

Also, @aimane-chnaif could you please propose any necessary regression tests? Thanks!

**Comment by OfstadC** [comment]
Bump on the regression test proposals @aimane-chnaif . Thank you!

**Comment by OfstadC** [comment]
## Payment Summary
- @FitseTLT paid $250 via Upwork
- @aimane-chnaif due $250 via New Expensify request

**Comment by OfstadC** [comment]
Oh no! I'm sorry @aimane-chnaif - Could you please accept [this offer ](https://www.upwork.com/nx/wm/offer/104267867)so I can initiate payment?

**Comment by OfstadC** [comment]
Paid - updated [this comment](https://github.com/Expensify/App/issues/47390#issuecomment-2372047926)
