### ISSUE TITLE
Distance - Invalid distance error appears in transaction thread when distance is being edited

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47402]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4847252
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a distance expense.
4. Go to transaction thread.
5. Click Distance.
6. Edit the waypoint that does not have route that will give this error "No route found through the waypoints. Please edit the waypoints and try again.".

## Expected Result:
The error "No route found through the waypoints. Please edit the waypoints and try again." will not appear in the transaction thread because user is editing the distance in RHP.

## Actual Result:
The error "No route found through the waypoints. Please edit the waypoints and try again." appears in the transaction thread when user is editing the distance in RHP. The distance receipt also changes in the background.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/25817096-75b8-4f40-9e28-e21246521368

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by adelekennedy** [comment]
I'm not sure this is a bug - in the case above and what I just tested this only seems to appear if you cannot access the end waypoint via a car, so I think the error shown is correct
