### ISSUE TITLE
Tax - App returns to More features after upgrading workspace to Control plan from Tax code

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47400]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a Collect workspace.
3. Go to workspace settings > More features.
4. Enable Taxes.
5. Go to Taxes.
6. Click on any tax rate.
7. Click Tax code.
8. Click Upgrade.

## Expected Result:
App will open tax code editor after upgrading the workspace to Control plan.

## Actual Result:
App returns to More features after upgrading the workspace to Control plan from Tax code page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9d12da09-ff0a-49a6-8b2d-009abfd2d19e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control

**Comment by rlinoz** [comment]
Yeah, I think it is related to this PR https://github.com/Expensify/App/pull/46617

The fix is the same thing we are doing for tags.

**Comment by garrettmknight** [comment]
@allroundexperts can you spin a fix up for Tax?

**Comment by rlinoz** [comment]
CP fixed the issue

**Comment by rlinoz** [comment]
We can close this one.
