### ISSUE TITLE
mWeb - Tax - After disabling, toggle on taxes shows items enabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile -- workspaces -- workspace
3. Tap more features
4. Enable tags and taxes
5. Add a new tag & tax rate
6. Disable category, tags, & tax
7. Tap back and note in workspace settings 3 options are not shown
8. Enable category, tags, & tax
9. Open category, tags, & tax

## Expected Result:
After disabling, toggle on category, tags &taxes must show same behavior

## Actual Result:
After disabling, toggle on category &tags shows items disabled but in taxes items are enabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c2f51b1c-dbe0-4d17-a5e8-62576d027c26

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
I'll add this one to my testing list.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
Other GHs have been a priority.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate this one. 

--- 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!
