### ISSUE TITLE
[$250] Approvers - Expenses are added to the already submitted report before it is approved

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47426]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4857763
**Email or phone of affected tester (no customers):** fischer9966+081424aemp@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
1. Login as the admin and create Collect workspace
2. Navigate to the collect workspace settings > More features > Enable workflows
3. Navigate to workflows > Enable Approvals
4. Enable delay submissions and set it to Manually
5. Invite a new user with Gmail account as an employee

Steps:
1. Login as the employee account in ND
2. Navigate to the workspace chat
3. Submit expense to the workspace for >100$
4. Tap "Submit" button
5. Submit another expense to the workspace

## Expected Result:
A new expense is added to a new report, since the previous one has already been submitted

## Actual Result:
A new expense is added to the already submitted report. Creation of a new report is possible only after approval of the previous one.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4bf0166e-1c47-4e1c-942f-d6b6872d22fe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831342357487627692</li>
        <li>Upwork Job ID: 1831342357487627692</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
@Beamanator this was the issue we were chatting through in control, right? I think we have a solve here?

**Comment by Beamanator** [comment]
Hmmm honestly not sure if i agree, since this was report in Collect? But would be good to test if it happens in both!

It's still possible this has something to do with the recent "Instant submit for Control" changes
- cc @youssef-lr @neil-marcellini @cristipaval

**Comment by trjExpensify** [comment]
I'm pretty sure this came up somewhere in #wave-control recently with the changes to who can edit processing reports, I think @youssef-lr was working on it?

**Comment by dylanexpensify** [comment]
@izarutskaya can you reproduce?

**Comment by izarutskaya** [comment]
I'll check and come back

**Comment by izarutskaya** [comment]
Not reproduced now 
Build v9.0.35-0

https://github.com/user-attachments/assets/8c8894cb-fdee-4202-b1aa-a4bf95517b7b
