### ISSUE TITLE
[$125] [Hold for payment 2024-09-06] mWeb - List - Initial value required tag is not shown if list value is entered later

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47423]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- workspaces -- workspace
3. Tap more features -- enable report field
4. Tap report field -- add field
5. Enter name
6. Select type "list"
7. Enter a list value & save
8. Tap save & note " Initial value field" required error displayed
9. Enter any value and save it
10. Tap add field
11. Enter name & select type as "list" and save it.
12. Open the newly created field
13. Enter a list value and save
14. Note initial value field displayed but "required" label not shown

## Expected Result:
Initial value required tag must be shown even if list value is entered later

## Actual Result:
Initial value required tag is not shown if list value is entered later

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9c5c88b6-ec68-4806-8c92-78bf8a1e7ca4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f85374b6fdfcbc99</li>
        <li>Upwork Job ID: 1824588149335622624</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103607004</li>
<li>Krishna2323 | Contributor | 103607007</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Initial value required tag is not shown if list value is entered later

### What is the root cause of that problem?
The initial value item is shown without `rightLabel` here

https://github.com/Expensify/App/blob/4c3aceb78809e751ed58fcdac2630f162e04a3dd/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L112
### What changes do you think we should make in order to solve the problem?
We should add `rightLabel` for initial value item as we do when we create the report field list value

```
rightLabel={translate('common.required')}
```

https://github.com/Expensify/App/blob/4c3aceb78809e751ed58fcdac2630f162e04a3dd/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L112

OPTIONAL: We can only show the require label if the initial value is empty or we can auto assign the first value of the list as initial value when we add the value to list after creating the report field.
### What alternative solutions did you explore? (Optional)
NA

**Comment by twisterdotcom** [comment]
>Initial value required tag is not shown if list value is entered later

I'm not sure we do always require an initial value. I don't think we should require one, should we? We've never required it on oldDot:

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/8e09a185-d53e-4c62-ab07-029b417ba378">

We just shouldn't be showing the requirement for an initial value at all when creating a list ever.

**Comment by rojiphil** [comment]
> We just shouldn't be showing the requirement for an initial value at all when creating a list ever.

Yeah. I too think likewise. If the `List values` can be empty even the `Initial value` can be empty as demonstrated in OldDot. 
@Krishna2323 [proposal](https://github.com/Expensify/App/issues/47423#issuecomment-2294448625) LGTM to prevent showing `Required` for `initial value` and also allows to reset if already set to some value.
🎀👀🎀 C+ reviewed

**Comment by jasperhuangg** [comment]
Not overdue, just assigned a contributor!

**Comment by twisterdotcom** [comment]
How are we doing here @rojiphil?

**Comment by rojiphil** [comment]
@twisterdotcom Gentle bump on payment summary here. Thanks.

**Comment by twisterdotcom** [comment]
Okay, it looks like this required an update as it caused a deploy blocker: https://github.com/Expensify/App/pull/47828#issuecomment-2313139319 

So you're right, 7 days after that is today. I'll update the amount to reduce to $125 though as per [this](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#regressions):

> If a PR causes a regression at any point within the regression period (starting when the code is merged and ending 168 hours (that's 7 days) after being deployed to production):
> 
> payments will be issued 7 days after all regressions are fixed (ie: deployed to production)
> a 50% penalty will be applied to the Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) for each regression on an issue

**Comment by twisterdotcom** [comment]
Payment Summary:

- @Krishna2323 paid $125 via Upwork [here](https://www.upwork.com/nx/wm/offer/103607007) (Contributor)
- @rojiphil paid $125 via Upwork [here](https://www.upwork.com/nx/wm/offer/103844024) (C+) _Needs accepting_.

**Comment by rojiphil** [comment]
> * $125 via Upwork [here](https://www.upwork.com/nx/wm/offer/103844024) (C+) _Needs accepting_

@twisterdotcom Accepted offer. Awaiting payment. Thanks.
