### ISSUE TITLE
[Payment 2024-10-01] [$250] Sage - RHP reverts to previous page if "Vendor bills" are selected for Export out-of-pocket

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47430]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4856847&group_by=cases:section_id&group_id=319504&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to Sage Intacct and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Export - Export out-of-pocket expenses as
9. Select "Vendor bills"

## Expected Result:
The RHP should stay on the "Export out-of-pocket expenses as" page.

## Actual Result:
The RHP reverts to the previous page if "Vendor bills" are selected for "Export out-of-pocket expenses as".
The RHP stays on the current page if "Vendor bills" selected for the "Export company card expenses as" option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b96e35c5-20d5-4395-8287-c7c1a22b8e82

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c5bb41c22cd4cc0b</li>
        <li>Upwork Job ID: 1827401530472861281</li>
        <li>Last Price Increase: 2024-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103818682</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by kevinksullivan** [comment]
Moving forward for external input

**Comment by yuwenmemon** [comment]
> I believe the issue is exact opposite. Instead of what is expected from this issue, we should fix The RHP stays on the current page if "Vendor bills" selected for the "Export company card expenses as" option. It should go back.

Yes, this is correct :+1:

**Comment by yuwenmemon** [comment]
Actually, let me clarify. Yes, it should go back, but the choice between Vendor Bills and Credit Cards should be one panel deeper, similar to what we have for the analogous setting on NetSuite. This is so that you can still configure the Credit Card Account or Default Vendor after selection.

https://github.com/user-attachments/assets/70104fce-0275-4da9-a506-f5ae9a9c0d61

**Comment by yuwenmemon** [comment]
@shubham1206agra How is progress on the above PR going? When do we expect it will be ready for review by @parasharrajat?

**Comment by kevinksullivan** [comment]
Waiting on PR. Looping in another BZ member as I'm going OOO

**Comment by joekaufmanexpensify** [comment]
Adjusting back to weekly because PR is in review

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by joekaufmanexpensify** [comment]
Automation failed. Payment due tomorrow!

**Comment by joekaufmanexpensify** [comment]
Payment here: 

- $250 to @shubham1206agra for PR via Upwork. 
- $250 to @parasharrajat for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment]
@shubham1206agra could you please accept upwork offer here so we can pay you tomorrow?

**Comment by joekaufmanexpensify** [comment]
[Bumped in slack ](https://expensify.slack.com/archives/C02NK2DQWUX/p1727807131850279)

**Comment by joekaufmanexpensify** [comment]
@shubham1206agra $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
Closing as all that's left is for @parasharrajat to request payment whenever you're ready!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
