### ISSUE TITLE
[HOLD for payment 2024-08-22] Search filters - Tag in X: Y format is displayed in X\:Y style

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47448]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** N (Can't check)
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has a tag in X: Y format.

1. Go to staging.new.expensify.com/search/filters.
2. Click Tag.

## Expected Result:
Tag in X: Y format will be displayed in `X:Y` style.

## Actual Result:
Tag in X: Y format is displayed in `X\:Y` style

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/16249691-1e23-4039-b4af-5eea805196b9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Beamanator** [comment]
This one def looks like it's related to https://github.com/Expensify/App/pull/46556 and https://github.com/Expensify/App/pull/47289

**Comment by Beamanator** [comment]
cc @bernhardoj @getusha

**Comment by Beamanator** [comment]
Looks fixed in staging! probably can close this out

**Comment by chiragsalian** [comment]
No payment needed here since i solved this internally.
