### ISSUE TITLE
[Awaiting Payment 2024-09-17][$250] iOS - Search - Inconsistency in selection mode behavior after holding and unholding expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47446]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**  applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace chat
3. Submit an expense
4. Go to Search
5. Long press on the expense
6. Tap Select
7. Tap on the dropdown > Hold > Enter a reason and save it
8. Note that selection mode persists after holding the expense
9. Refresh the Search page by switching between Expense and Shared tab (or restart app)
10. Long press on the expense > Tap Select
11. Tap on the dropdown > Unhold
12. Note that selection mode is dismissed after unholding the expense

## Expected Result:
There should be consistency in the selection mode after holding and unholding the expense from Search

## Actual Result:
In Step 8, after holding the expense, selection mode persists
In Step 12, after unholding the expense, selection mode is dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fc6355b2-3669-44f4-b22d-0f0457ccab54

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d4437d2bef15d58</li>
        <li>Upwork Job ID: 1824124311599546509</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103552021</li>
<li>cretadn22 | Contributor | 103552023</li>
<li>Krishna2323 | Contributor | 103692759</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by sonialiap** [comment]
@dylanexpensify I'm OOO Aug 19-30, adding leave buddy. 
Status: proposal selected, waiting for build

**Comment by rlinoz** [comment]
>  I think we should clear the selected transactions and dismiss the selection mode

I am not 100% sure about this, I know we decided not to clear it when Downloading the CSV, not sure what we want to do here.

cc: @Expensify/design

**Comment by dannymcclain** [comment]
@Expensify/design do you remember where we landed on this? I feel like we did have some convo back and forth about whether or not to keep items selected after performing an action.

It's interesting because if you use the `Delete` action we're definitely going to clear the selection and exit select mode (we pretty much have to haha). So I could definitely see an argument for just clearing the selection and exiting select mode after performing an action... But I can also see a case for keeping things selected so you can perform _multiple_ bulk actions in succession. What do y'all think?

**Comment by dannymcclain** [comment]
That works for me. Delete can be the exception, but that flow is obviously pretty intuitive.

**Comment by shawnborton** [comment]
Totally, that makes complete sense.

**Comment by rlinoz** [comment]
Thanks everyone!

I think we should not have assigned @cretadn22 yet, can you help us @dylanexpensify?

@dukenv0307 should we go with @Krishna2323's proposal then, since we want to keep the selected transactions?

**Comment by rlinoz** [comment]
Oh I am sorry, I failed to read the alternative solution. 

We are good here then, feel free to work on the PR keeping the selected transactions 😄

**Comment by rlinoz** [comment]
Hey sorry about the confusion here we should not have assigned someone at the time we did, but in the end the solution is just very similar, like clearing the checkboxes or keeping them selected touches mostly the same area of the code, so let's keep things the way they are right now.

**Comment by rlinoz** [comment]
I though that was done already, sorry

**Comment by trjExpensify** [comment]
Moving this into `polish`. 

As a reminder for the BZ assigned, let's try not to leave ambiguous expected results in the OP when triaging. 

>Expected Result:
>There should be consistency in the selection mode after holding and unholding the expense from Search

This doesn't tell us what the behaviour should be, just that it's not the same when you hold or unhold.

**Comment by dylanexpensify** [comment]
merged!

**Comment by rlinoz** [comment]
I think this has been deployed to prod 3 days ago https://github.com/Expensify/App/issues/48791#issuecomment-2342359302

**Comment by sonialiap** [comment]
Payment summary:
- @Krishna2323 $250 
- @dukenv0307 $250 
- @cretadn22 $125 for the work done https://github.com/Expensify/App/issues/47446#issuecomment-2301952048

Waiting until the 17th to complete payments in [upwork](https://www.upwork.com/ab/applicants/1824124311599546509/hired)

**Comment by rlinoz** [comment]
Just changing the ⭐

**Comment by sonialiap** [comment]
Everyone has been paid ✔️
