### ISSUE TITLE
[HOLD for Payment 2024-09-23][$250] Update UpdatePolicyConnectionConfiguration to be 1:1:1 - Part 1

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#47443]
## Problem

Our UpdatePolicyConnectionConfiguration API command is not 1:1:1 - it is the same API call for all related user actions, when it should be split up for each connection (QBO, Xero, etc.) and configuration setting (`autoSyncVendor`, `enableNewCategories`, etc.). At the end of this we should not call that function anywhere.

This is polish for [the Collect QBO project](https://github.com/Expensify/Expensify/issues/201614).

## Solution

When we created the NetSuite commands, we followed the correct pattern, and so need to do so here too.

This requires backend and frontend work in tandem (to create the commands and then to use them), so we're looking for a contributor(s) to handle the frontend. You can see an example PR [here](https://github.com/Expensify/App/pull/46234/files) - there is some extra prep work there that you can ignore, but adjusting all calls like [this](https://github.com/Expensify/App/pull/46234/files#diff-9b64c08598bd055cd4122614010389a293da53ab63274d7017b9f870b96a2e62L85-R85) is what we're going for:

```diff
- Connections.updatePolicyConnectionConfig(policyID, CONST.POLICY.CONNECTIONS.NAME.QBO, CONST.QUICK_BOOKS_CONFIG.REIMBURSABLE_EXPENSES_ACCOUNT, row.value);
+ QuickbooksOnline.updateQuickbooksOnlineReimbursableExpensesAccount(policyID, row.value);
```

Here is a list of the commands handled in this issue:
- UpdateXeroImportCustomers
- UpdateXeroEnableNewCategories
- UpdateXeroExport
- UpdateXeroSync
- UpdateXeroAutoSync
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df4dbeb24127ed89</li>
        <li>Upwork Job ID: 1824524962582076644</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103558840</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by VictoriaExpensify** [comment]
Hey @dangrous - I notice that I got assigned to this with the bug label, but then you removed the bug label. So I'm not sure if I'm meant to be assigned or what I should be doing with this...?

**Comment by dangrous** [comment]
Ha yeah sorry I was trying to remove it before Melvin noticed, but I failed.

Nothing to do at the moment - we're going to be assigning this directly to a C+, who will eventually need payment, so might as well stick around... but no action right now!

**Comment by mananjadhav** [comment]
Picking this up.

**Comment by dangrous** [comment]
oh hm it didn't register @mananjadhav . @ishpaul777 can you do the 🎀 thing? Maybe it needs that.

**Comment by dangrous** [comment]
oh maybe? that makes it easier if so. In any case, @mananjadhav you're assigned!

**Comment by dangrous** [comment]
FYI it looks like we send `export` and `sync` with different setting values as a full object so we'll need to split those up as well - like:

* UpdateXeroExportBillDate
* UpdateXeroExportExporter
* UpdateXeroExportBillStatus
* UpdateXeroSyncInvoiceCollectionsAccountID
* UpdateXeroSyncReimbursementAccountID

etc.

And another note, for Xero we are using updatePolicyXeroConnectionConfig which eventually calls UpdatePolicyConnectionConfiguration

**Comment by mananjadhav** [comment]
Okay let me know once we have these API on staging I'll start with the PR.

**Comment by dangrous** [comment]
Cool! We're almost there on the backend.

For the split ones that have dynamic keys like `reimbursementAccountID`, I think we can pass them as individual parameters, so `reimbursementAccountID` and also `value` and then I can reconstruct the object in the backend. I'm working on those today and then we should be good.

I'll let you know if any others are expecting params in a different format than the standard `settingValue`

**Comment by dangrous** [comment]
Backend is merged, not yet deployed, but you can probably start working and it'll be up by the time testing is ready. Here are the relevant new commands, just to confirm:

- UpdateXeroImportCustomers
- UpdateXeroEnableNewCategories
- UpdateXeroAutoSync

- UpdateXeroExportBillStatus
- UpdateXeroExportBillDate
- UpdateXeroExportExporter
- UpdateXeroExportNonReimbursableAccount

- UpdateXeroSyncInvoiceCollectionsAccountID
- UpdateXeroSyncSyncReimbursedReports
- UpdateXeroSyncReimbursementAccountID

I grouped the sync and export ones that will need to be split up

**Comment by dangrous** [comment]
Spoke too soon, I guess - this is on staging now, so code away!

**Comment by dangrous** [comment]
@mananjadhav let us know how things are going!

**Comment by mananjadhav** [comment]
I should have the PR by tomorrow.

**Comment by mananjadhav** [comment]
I will raise the draft PR in a few hours.

**Comment by mananjadhav** [comment]
quick question @dangrous, I can see we have added `prepareXeroOptimisticData` which is specific to xero.config. 

https://github.com/Expensify/App/blob/6d00670c75552dcc7a281797b2f04ca5cca10418/src/libs/actions/connections/Xero.ts#L65-L70

Now for my commands `UpdateXeroExportBillStatus`, `UpdateXeroExportBillDate`, etc. are the keys from xero.config.export, which makes it unusable as the keys are nested. Do we create a separate method for `prepareXeroExportOptimisticData` or should I just duplicate the code in each method to set the keys. 

In turn we're also calling `createXeroPendingFields` and `createXeroErrorFields` which would have to be defined for export, advanced etc.

**Comment by dangrous** [comment]
I think `prepareXeroExportOptimisticData` makes sense since we're going to be using it a couple times!

**Comment by mananjadhav** [comment]
Thanks for confirming. We'll need to do the same for sync as well then.

**Comment by mananjadhav** [comment]
@dangrous I am getting an issue while executing `UpdateXeroSyncSyncReimbursedReports`. It returns `false` as string and the switch resets. Can you please check this at your end? The other commands are working fine.

https://github.com/user-attachments/assets/0f23fecb-98ea-493f-b210-0fc1afac3a89

**Comment by dangrous** [comment]
Sorry for the delay on this @ishpaul777 ! I've found the issue and am raising a BE PR to fix momentarily.

**Comment by dangrous** [comment]
@mananjadhav that issue should be fixed on staging!

**Comment by dangrous** [comment]
This was deployed to prod on 9/16. Stupid automation.

**Comment by VictoriaExpensify** [comment]
It looks like this is ready for payment then 🤑

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @mananjadhav owed $250 via NewDot
Contributor+: @ishpaul777 paid $250 via [Upwork](https://www.upwork.com/ab/applicants/1824524962582076644/hired)

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
