### ISSUE TITLE
[HOLD for payment 2024-09-23] Make medium the default button size

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#47454]
Coming from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1723474559459839?thread_ts=1723471955.379859&cid=C01GTK53T8Q), `medium` should be our default button size

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by adelekennedy** [comment]
This was deployed to prod on the 16th I think payment is due here for @mkhutornyi - sent offer on [Upwork](https://www.upwork.com/nx/enterprise-homepage/?offerRid=104204536&nav_dir=replace&teamUid=all_teams)
