### ISSUE TITLE
Workspace - Invited member can't be tapped for a while after the invite

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4856847&group_by=cases:section_id&group_id=319504&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Create a workspace
4. Navigate to Workspace settings - Members
5. Tap on the "Invite member" button
6. Invite an existing Gmail account to the workspace
7. Tap on the member

## Expected Result:
I should be able to tap on the member as soon as I have added it.

## Actual Result:
Invited member can't be tapped for a while after the invite. The issue affects Web mWeb and native apps too. Android mWeb is affected the most as it needs 1-2 minutes after the member can be tapped. On Web, the delay is only 10-15 seconds.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/02258847-2c0f-4a93-8474-734c63d9245e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
This is expected behaviour. We disable Optimistically created member until the real data comes from BE

**Comment by OfstadC** [comment]
Thanks @FitseTLT !
