### ISSUE TITLE
[Pending / Scanning] Card Expense - After a card transaction is placed, a second expense is created with no amount

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#47466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-6

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes 

**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4856345

**Email or phone of affected tester (no customers):** [tester+ndcardtests@applausecard.expensifail.com](mailto:tester+ndcardtests@applausecard.expensifail.com)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team
**Slack conversation:** N/A

## Action Performed:
1. Open the downloaded HTML.
2. Click on the top "Buy Now" button.
3. On the Paypal page, click on "Pay with debit or Credit card".
4. Use the testing credentials and card to complete the transaction (Disable the toggle to create a PayPal account).
5. Log in to NewDot with the account "[tester+ndcardtests@applausecard.expensifail.com".](mailto:tester+ndcardtests@applausecard.expensifail.com%22.)
6. Go to the workspace chat "Card Tests - DO NOT DELETE".
7. Click on the open report.
8. Check that in addition to the card expense, there is an additional one with 0 amount and merchant "PAYPAL"

## Expected Result:
There should be no additional expenses, only the one created from the card transaction.

## Actual Result:
In addition to the card expense, there is an additional one with 0 amount and merchant "PAYPAL".
Report ID: 2317033129992857
Original Card Transaction ID: 1705364837734590
Additional PAYPAL Transaction ID: 567022096531174

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/52ffd419-00d9-4f5f-b5af-24f6a4e2198c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
I _think_ this is known, let me check.

**Comment by grgia** [comment]
Does logging in and out fix the problem?

**Comment by kevinksullivan** [comment]
asking @isagoico

**Comment by isagoico** [comment]
Nope - Logged back into the account and I'm still able to see the empty transaction 
![image](https://github.com/user-attachments/assets/bd8338bd-cb11-4dec-b477-8f20937b6224)

**Comment by kevinksullivan** [comment]
I imagine this will be internal, right @grgia ? Going to assign you initially as you've been close it, but lmk if I am misunderstanding.

**Comment by kevinksullivan** [comment]
discussing here

https://expensify.slack.com/archives/C036QM0SLJK/p1724709127284939

**Comment by isagoico** [comment]
I'm not able to reproduce on my end anymore 👀 
![image](https://github.com/user-attachments/assets/17f435ec-ecee-4101-b34e-14c9ed5c06ba)

I checked the older report where this was originally reproducible and the empty expenses are still there though. Not sure if this could be helpful to debug: 
![image](https://github.com/user-attachments/assets/a9aa1124-66f2-4cf9-aa77-d6ddf15b19f9)

**Comment by kevinksullivan** [comment]
alrighty, let's close out for now then!
