### ISSUE TITLE
[HybridApp] [$250] Update 3DTouch/ForceTouch menu so it's not broken when set to boot the NewDot experience on Hybrid

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47469]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-6
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @justinpersaud 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723651760402959

## Action Performed:

Prerequisite: HybridApp is set to boot NewDot 

1. Close the Hybrid app so it won't quick open / resume previous session
2. Long hold on the Expensify app icon
3. Select 'SmartScan receipt' || `Start GPS` || `Manually create`

## Expected Result:

- Replace `Start GPS` with `Log distance`.
   - when set to boot NewDot, open `Submit expense` > `Distance`
   - when set to boot OldDot, open `Start GPS` page like today.
   
- Keep `SmartScan receipt`
   - when set to boot NewDot, open `Submit expense` > `Scan`.
   - when set to boot OldDot, open the camera screen like today.

- Keep `Manually create`
   - when set to boot NewDot, open `Submit expense` > `Manual`.
   - when set to boot OldDot, open `New expense` page like today.

## Actual Result:

- SmartScan receipt - sometimes an infinite load screen, sometimes it does open the NewDot experience but not to a camera screen, so does nothing.
- Manually create - the OldDot experience opens to the “New expense” manual form, but then the app doesn’t respond if you try to save or do anything with it.

- Start GPS - the OldDot experience opens, but again, you can’t do anything with the done button to save it and get out of the screen. Forcing you to kill the app.

## Workaround:
Don't use the menu.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b766551d-2eb8-494a-9204-1cbf6278fe7e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01baa2ec2a95c98c4d</li>
        <li>Upwork Job ID: 1825765115598850682</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by RachCHopkins** [comment]
Can't test this - I don't have HybridApp. But it looks pretty straightforward!

**Comment by trjExpensify** [comment]
I couldn't repro the OP bug on HybridApp iOS, the app loaded in "NewDot mode" for me when I clicked `SmartScan receipt`, just on the `inbox` page -  it doesn't launch `submit expense > scan` or key off my quickAction or anything though. I also got into a bit of a weird state when I clicked the `Manually create` option - it opened in OldDot mode, but the `cancel` button was unresponsive and when I hit `save` I ended up with a white screen.

So yeah, this is a good one to decide and clear up what we want to do with the Force/3DTouch menu in a HybridApp world. It's almost as if we need to tailor the options to whichever experience you're defaulted to boot. Is that out of the question, or something we could potentially achieve @AndrewGable @Julesssss @staszekscp @mateuuszzzzz? 

Happy to explore this one a bit. CC: @JmillsExpensify

**Comment by staszekscp** [comment]
@trjExpensify This is something we have to take care of - currently the quick actions/shortcuts point to OldDot code, which will cause problems if someone uses NewDot. I suppose we could temporarily disable the quick actions/shortcuts for ND users (they hasn't been implemented in ND yet), and start working on the fix soon

**Comment by Julesssss** [comment]
>  Is that out of the question, or something we could potentially achieve @AndrewGable @Julesssss @staszekscp @mateuuszzzzz?

We'd definitely want to look into this.

**Comment by Julesssss** [comment]
Ah nice timing. Yeah, I think this is a good polish issue for @staszekscp and the team to look into soon.

**Comment by trjExpensify** [comment]
Ah cool, I escalated this here for us to chat in realtime: https://expensify.slack.com/archives/C036QM0SLJK/p1725014200358829?thread_ts=1724680133.863329&cid=C036QM0SLJK

**Comment by trjExpensify** [comment]
Discussed the next steps for this [here](https://expensify.slack.com/archives/C036QM0SLJK/p1725398614948469), updated the OP to reflect what we're going to do about the menu to make it not broken.

**Comment by trjExpensify** [comment]
>Ah nice timing. Yeah, I think this is a good polish issue for [@staszekscp](https://github.com/staszekscp) and the team to look into soon.

@staszekscp any idea who's taking this one on yet to assign it out?

**Comment by staszekscp** [comment]
I do not want to declare anything at this moment, but when someone from our HybridApp group (myself, @mateuuszzzzz or @war-in) has bandwidth, we'll tackle that. 😄 I suppose we could start working on it early next week or, to be more precise, after merging [this PR](https://github.com/Expensify/App/pull/48007), which is a bigger refactor of the entry point to NewDot within HybridApp

**Comment by trjExpensify** [comment]
Okay, sounds good!

**Comment by trjExpensify** [comment]
Niceee!

**Comment by staszekscp** [comment]
The shortcuts are up and running on my PRs 😄 I just need to do a cleanup, record videos, and they'll be ready for review!

**Comment by trjExpensify** [comment]
Whoopsie, I think we have one PR to go here: https://github.com/Expensify/App/pull/48780

**Comment by trjExpensify** [comment]
Taking @carlosmiceli off this issue, @Julesssss and @AndrewGable are reviewing the PR.

**Comment by Julesssss** [comment]
All PRs have been merged.
