### ISSUE TITLE
"Deployed to Prod" message not posted in PRs deployed to prod

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#47461]
**Slack conversation:** https://expensify.slack.com/archives/C07J32337/p1723662839904769

## Action Performed:
Deploy App by closing checklist ([example](https://github.com/Expensify/App/issues/47219))

## Expected Result:
"Deployed to Prod" message should show up on all PRs deployed to prod

## Actual Result:
None got posted - see this convo / investigation: https://expensify.slack.com/archives/C07J32337/p1723662839904769

cc @roryabraham @AndrewGable

**Comment by roryabraham** [comment]
will monitor and see if it happens again today

**Comment by roryabraham** [comment]
this happened again today, looking into it now...

**Comment by roryabraham** [comment]
This is fixed
