### ISSUE TITLE
Html codes appear in the SMS when a new member joins domain

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47465]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723333080242499

## Action Performed:
1. Create an SMS account > set the display name and include an apostrophe (e.g David's SMS)
2. Add the SMS account as a domain admin of a private domain
3. Sign up for an account on that domain and validate the account when prompted
4. Observe the SMS received by the domain admin

## Expected Result:
There shouldn't be any HTML codes in the SMS

## Actual Result:
`Hiya David&#039;s!

I just wanted to let you know that dbarrett+ghfhhh66@quinthar.com has created an Expensify account. They have been added to your default Domain Group on the "quinthar.com" domain.`

Additionally Messages are showing as sent from 4777
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![IMG_1075 (1)](https://github.com/user-attachments/assets/30a913a4-ad18-4c58-b3ff-3957042b67d1)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
@dylanexpensify putting on your radar for hot picks shoutout!

**Comment by marcaaron** [comment]
I see the problem and I'm raising a fix now.

**Comment by marcaaron** [comment]
This was fixed.
