### ISSUE TITLE
[$250] Netsuite - Able to connect Netsuite with incorrect tokens

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47493]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4859063&group_by=cases:section_id&group_order=asc&group_id=314239
**Email or phone of affected tester (no customers):** applausetester+gm1094@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
1. Login with an account that is an admin of a control workspace (or create one in OD if needed)
2. Enable accounting in workspace settings
Steps
1. Navigate to Accounting
2. Click on the connect button next to NetSuite
3. Reach the credentials step
4. Enter incorrect the NetSuite tokens

## Expected Result:
When credentials are entered incorrectly a sync error should be displayed

## Actual Result:
User is able to connect Netsuite with incorrect tokens. No error message is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/393d0ddb-262e-4d74-be2c-43748195c22c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f1ac27b5bef67232</li>
        <li>Upwork Job ID: 1831077669368516851</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103803673</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by lanitochka17** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by sakluger** [comment]
Hey @yuwenmemon, any idea why we're not throwing a connection error here?

**Comment by yuwenmemon** [comment]
Weird. Will take a look.

**Comment by sakluger** [comment]
@yuwenmemon any ideas?

**Comment by yuwenmemon** [comment]
No update yet, other issues have been taking precedence but will look soon!

**Comment by yuwenmemon** [comment]
So... we never really built a way to display error messages from NetSuite other than the generic sync error message (cc @mananjadhav @shubham1206agra) - we kind of kicked the can down the road on that one. But I'm thinking now might be a good time to get this going and we can use the traditional `lastSync` object that all the other integrations use.

If anything, we can do this just for the error message for now, and then maybe move NetSuite over to using it just like the rest of the integrations, at least for NewDot.

**Comment by mananjadhav** [comment]
Agreed. We started this discussion [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1720179157722519?thread_ts=1719271507.184899&cid=C06ML6X0W9L) but didn't prioritize. One of the recommendations was `lastSync.wrongCredentials = true`, so that we can differentiate between a general error or auth error. We could also probably change it to enum and handle it accordingly. wdyt?

**Comment by yuwenmemon** [comment]
@mananjadhav We actually have an `isAuthentiationError` property now on the `lastSync` object that can help with that too. I can make sure we start adding it for NetSuite.

**Comment by mananjadhav** [comment]
> @mananjadhav We actually have an `isAuthentiationError` property now on the `lastSync` object that can help with that too. I can make sure we start adding it for NetSuite.

Yeah that would help. I am assuming `isAuthenticationError` is correct property name.

**Comment by yuwenmemon** [comment]
Yes 😄

**Comment by yuwenmemon** [comment]
Okay I've put in a PR above to update the NetSuite connection to start using the `lastSync` object like all the other integrations. We can flip this to be external once that's deployed. @mananjadhav @SzymczakJ or @war-in Would any of you be interested in working on that?

**Comment by mananjadhav** [comment]
I can pick this.

**Comment by sakluger** [comment]
@yuwenmemon - does your PR use the same methods that are being used in the QBO Export & Error Handling project?

**Comment by yuwenmemon** [comment]
@mananjadhav The IS portion is deployed! We should be able to use the `lastSync` object for NetSuite like we do for the rest of the integrations now 🎉 

Assigning to you for implementation.

**Comment by yuwenmemon** [comment]
Apologies for the melvin madness @rushatgabhane @shubham1206agra @mananjadhav @sakluger 

As per the conversation above, @mananjadhav will take on the implementation here and @shubham1206agra will do the review.

**Comment by mananjadhav** [comment]
Thanks for assigning. I'll have the PR Draft ready by tomorrow. @yuwenmemon just confirming once again based on the `isAuthenticationError` property is set, we'll show an invalid auth message, right? do we have any text/copy that we have finalized/used?

**Comment by yuwenmemon** [comment]
Let's follow the model used by Intacct. An error message will be stored in the `lastSync` object itself as well:

<img width="691" alt="Screenshot 2024-09-04 at 11 53 29 AM" src="https://github.com/user-attachments/assets/208d6457-73dd-41c3-bbf4-955aa177c31b">
<img width="1160" alt="Screenshot 2024-09-04 at 11 57 41 AM" src="https://github.com/user-attachments/assets/194e2f7c-1f8c-4de5-945b-b4aa5779ad60">

**Comment by mananjadhav** [comment]
Okay thanks for confirming.

**Comment by mananjadhav** [comment]
Working on it, will be ready by tomorrow.

**Comment by mananjadhav** [comment]
SageIntacct adds an error message and a `Learn more` link which leads to the help.expensify page. For NetSuite should we use this link https://help.expensify.com/articles/expensify-classic/connections/netsuite/Netsuite-Troubleshooting#expensierror-ns0109-failed-to-login-to-netsuite-please-verify-your-credentials ?

**Comment by yuwenmemon** [comment]
Yeah that would be a nice addition @mananjadhav

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @mananjadhav $250, please request on Newdot
Contributor+: @shubham1206agra $250, sent offer via Upwork (https://www.upwork.com/nx/wm/offer/104323832)

@shubham1206agra I had to send a new offer - please let me know once you've accepted it. Thanks!

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav

**Comment by sakluger** [comment]
Thanks everyone! I completed payment to @shubham1206agra so we're good to close this one out.
