### ISSUE TITLE
Intacct - Tapping 3 dots not redirected to credentials page & authentication error displayed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47499]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4859515
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon -- workspaces-- workspace
3. Tap more features -- enable accounting
4. Tap sage intacct-- connect
5. Enter invalid credentials & tap confirm
6. Note authentication error is shown
7. Tap on 3 dots

## Expected Result:
Tapping 3 dots user must be directed to credentials page & authentication error must not be displayed on entering invalid credentials.

## Actual Result:
Tapping 3 dots user not directed to credentials page & authentication error displayed on entering invalid credentials.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5b82441f-5acc-4d48-b159-9c271afc1a00

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @yuwenmemon</details>

**Comment by izarutskaya** [comment]
Production - different error

https://github.com/user-attachments/assets/4d376618-55d9-49e9-8bed-fd17c264ea0c

**Comment by izarutskaya** [comment]
We think this issue might be related to the  #vip-vsb

**Comment by yuwenmemon** [comment]
As per the discussion here, removing the blocker label: https://expensify.slack.com/archives/C01GTK53T8Q/p1723735252143779

**Comment by yuwenmemon** [comment]
No update just yet but will look soon.

**Comment by yuwenmemon** [comment]
Will be fixed by https://github.com/Expensify/App/pull/48001
