### ISSUE TITLE
[HOLD for payment 2024-09-17][$250] [Search v2.2] Create chat filter - Is

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#47498]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the `is` filter only! It should accept two values: unread, pinned (we're descoping draft for now since that's not saved on the server)

This is a type=chat specific filter, so the UI should only render it if the user is currently viewing the chat type.

cc @289Adam289 @Kicu @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015684aa45795e5b82</li>
        <li>Upwork Job ID: 1828194742989624421</li>
        <li>Last Price Increase: 2024-08-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @SzymczakJ</details>

**Comment by joekaufmanexpensify** [comment]
@luacmartins should this be external for proposals, or are the folks you tagged in OP working on it?

**Comment by luacmartins** [comment]
SWM will work on this.

**Comment by joekaufmanexpensify** [comment]
Got it, sounds good!

**Comment by joekaufmanexpensify** [comment]
@289Adam289 @Kicu @Guccio163 could whoever is working on this comment on the issue so I can assign them to the issue?

**Comment by Kicu** [comment]
hey guys what is the difference between this `Is` filter and the one from v2.1: https://github.com/Expensify/App/issues/46030 ?

Or is this a duplicate task?

For now everyone in SWM/Search is working on other search tasks and finishing up 2 filters from v2.1, so we'll pick this one up once someone is free.

**Comment by luacmartins** [comment]
@JmillsExpensify we decided to remove the UI filter for type/status. The `is` filter is kind of a status filter, do we need to support `is` in the UI as well? Or is this just a syntax filter?

**Comment by joekaufmanexpensify** [comment]
Pending prioritization by SWM

**Comment by joekaufmanexpensify** [comment]
As an fyi, going to be OOO from tomorrow - Monday. Not adding another BZ since nothing should be needed during that time. Please ask in slack if something comes up.

**Comment by JmillsExpensify** [comment]
> @JmillsExpensify we decided to remove the UI filter for type/status. The `is` filter is kind of a status filter, do we need to support `is` in the UI as well? Or is this just a syntax filter?

I ended up answering this question in the doc and I agree with your answer. Looks like we'll still implement the syntax under the hood and it'll show it in the UI (via tab bar or what we call "contextual tabs."

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by joekaufmanexpensify** [comment]
Sounds great, TY! I see the draft PR, is there an ETA for it to be in review?

**Comment by sachinsiddhu112** [comment]
Contributor details
Expensify account email: sachinsiddhu6393@gmail.com
Upwork profile link: https://www.upwork.com/freelancers/~01f4e9dc188baf961c?mp_source=share

**Comment by sachinsiddhu112** [comment]
Contributor details
Expensify account email: [sachinsiddhu6393@gmail.com](mailto:sachinsiddhu6393@gmail.com)
Upwork profile link: https://www.upwork.com/freelancers/~01f4e9dc188baf961c

**Comment by SzymczakJ** [comment]
@joekaufmanexpensify we still need to wait for the linked PR to be merged, to be able to test this reliably. So I guess it will take a few days

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY!

**Comment by joekaufmanexpensify** [comment]
PR still WIP

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
Still pending other PR being merged

**Comment by SzymczakJ** [comment]
Still pending other PR being merged

**Comment by SzymczakJ** [comment]
Since I've run out of things to work on and "Has" filter is already merged(and it was also depending on chat type PR) I decided that this PR can be moved forward(to test we just need to set one value in Onyx, just like we did in "Has" filter). It's ready for C+ review.

**Comment by joekaufmanexpensify** [comment]
PR merged and on staging

**Comment by luacmartins** [comment]
PR was deployed to production yesterday.

**Comment by joekaufmanexpensify** [comment]
Sounds good! Will pay on the 17th.

**Comment by joekaufmanexpensify** [comment]
Payment due tomorrow. Only payment here is $250 to @ikevin127 for C+ review via Upwork

**Comment by joekaufmanexpensify** [comment]
@ikevin127 offer sent for $250!

**Comment by joekaufmanexpensify** [comment]
All set to issue payment.

**Comment by joekaufmanexpensify** [comment]
@ikevin127 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set. TY everyone!
