### ISSUE TITLE
[HOLD for Payment 2024-09-10][$250] [Search v2.2] Create chat filter - Has

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#47497]
Implement [this section](https://docs.google.com/document/d/1bRV1nPz8SaI_6DHqfehmLnADxv40us_q0JNvmZ1QyaY/edit#bookmark=id.ekk0kmv0drso) of the design doc for the Has filter only! It should accept two values: attachment, link.

This is a type=chat specific filter, so the UI should only render it if the user is currently viewing the chat type.

cc @289Adam289 @Kicu @Guccio163
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f1f3a0aaab90767</li>
        <li>Upwork Job ID: 1826635907294867133</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @289Adam289</details>

**Comment by luacmartins** [comment]
cc @289Adam289 @Kicu @Guccio163 if you have availability to work on this one.

**Comment by 289Adam289** [comment]
Hi @luacmartins! I can work on this filter

**Comment by abekkala** [comment]
### PAYMENT SUMMARY: 

- Fix @289Adam289 SWM - No upwork payment
- PR Review: @rayane-djouah [$250] [Offer](https://www.upwork.com/nx/wm/offer/103930722)

**Comment by abekkala** [comment]
@rayane-djouah payment sent and contract ended - thank you! 🎉
