### ISSUE TITLE
[$250] Search - Select all check box is not checked with tick mark in shared, drafts & finish tab

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4861073
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-condition:Login to account with few expenses
1. Go to https://staging.new.expensify.com/home
2. Tap search -- select shared, draft or finish
3. Long press an expense, and select " Select all " options

## Expected Result:
Select all check box must be checked with tick mark in shared, drafts & finish tab

## Actual Result:
Select all check box is not checked with tick mark in shared, drafts & finish tab.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ecb40073-a967-442d-8cf3-19dd8586f238

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cf70262c4767dc9</li>
        <li>Upwork Job ID: 1824243866353954297</li>
        <li>Last Price Increase: 2024-08-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb

**Comment by VictoriaExpensify** [comment]
I think @izarutskaya has uploaded the wrong screen-recording, but I've been able to reproduce the issue:

![2024-08-16_10-34-57 (1)](https://github.com/user-attachments/assets/04bbd388-1beb-40ca-b37e-b0b963714c0e)

I agree this is a problem and we should fix it.

**Comment by VictoriaExpensify** [comment]
I think this is more suited to Wave-Collect

**Comment by VictoriaExpensify** [comment]
@getusha could you please review @daledah's proposal? https://github.com/Expensify/App/issues/47494#issuecomment-2292522017

**Comment by getusha** [comment]
I am no longer able to reproduce it, i think layout is not same as it was when this issue was created.

https://github.com/user-attachments/assets/2add79a6-519f-4082-9d66-dd92be12df83

**Comment by VictoriaExpensify** [comment]
Hmm I can still recreate this @getusha 

On the desktop app:

![2024-08-26_10-43-32 (1)](https://github.com/user-attachments/assets/f3662868-9186-41e4-bca2-772673400455)

And on Staging:


![2024-08-26_10-47-47 (1)](https://github.com/user-attachments/assets/8e010857-4e4f-499e-9517-f73575a3115a)

Expenses seem to be ok, but "shared" "drafts" and "finished" are not

**Comment by getusha** [comment]
@VictoriaExpensify I don't know why the changes aren't deployed to staging yet but i am seeing a different layout in `DEV` environment 😄
![Screenshot 2024-08-27 at 3 28 41 in the afternoon](https://github.com/user-attachments/assets/f991bdfc-39e8-4ffc-9f4b-8e413aeef3b3)

**Comment by trjExpensify** [comment]
We've now deployed the new search tabs if you want to re-test this one, @VictoriaExpensify.

**Comment by VictoriaExpensify** [comment]
Oh nice! The search tabs look great at this issue is resolved - closing!
