### ISSUE TITLE
[$250] Web - Scan-GBR instead of RBR displayed in LHN for Admin

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47502]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4693685
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: There is a WS created, with an admin and an employee.

1. Log in as the employee and submit a scan receipt to the WS
2. While the receipt is scanning, edit the merchant field and leave the amount field empty( to trigger the error message and the RBR)
3. Submit the expense and log out
4. Log in as the admin
5. Navigate to the WS chat in LHN

## Expected Result:
The RBR is displayed in the LHN, in the request preview and the request details.

## Actual Result:
For the Admin, there is a Green Dot displayed in the LHN, while in the request preview and details the dot is Red.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/93defc8c-acf2-4262-8fdb-f8f6a0d17905

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01114847a6aa18235d</li>
        <li>Upwork Job ID: 1824130592527843469</li>
        <li>Last Price Increase: 2024-10-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mollfpr** [comment]
>We've discussed this extensively, and decided that we would treat the RBR on the LHN different than the money request view.
>
>The RBR on the LHN should only show for the user that made the request. The RBRs on the report preview, money request preview, and the ones in the money request view, should show to every user that has access to them.
>
>The reasoning we're using here is that the user that made the request is the one that should be guided towards taking actions to fix the RBR, and that guidance starts with the chat on the LHN.
>
>Moreover, we don't want to hide RBRs in report previews, money request previews, or the money request view, to anyone that has access to the money requests. And if they have RBRs, we should show them because there's no value in hiding information from people that have access to it.

Quoting from https://github.com/Expensify/App/issues/37044#issuecomment-1984922236, it's expected that the RBR is only shown for the requestor. @adelekennedy Could you help confirm? Thanks!

**Comment by adelekennedy** [comment]
You're correct @mollfpr! I think we can close this one

**Comment by trjExpensify** [comment]
What are we doing here? Isn't there still a bug insofar as the green dot on the workspace chat for the admin for an expense report that is $0 containing only the failed receipt scan? CC: @JmillsExpensify if I'm missing something, but seems like that shouldn't be there: 

![Image](https://github.com/user-attachments/assets/6d0b1fe8-72cf-432a-b5cf-ab83705fd7a5)

**Comment by mollfpr** [comment]
@adelekennedy @trjExpensify What's the next step here?

I'm checking the latest main and here's the result.

**Admin**

![Screenshot 2024-10-09 at 14 06 58](https://github.com/user-attachments/assets/10319194-5f0e-4623-8dbd-2ad48d7ec0cd)


**Employee**

![Screenshot 2024-10-09 at 14 07 10](https://github.com/user-attachments/assets/fa64acb4-fd77-48f2-925b-958337e30a35)

The RBR in LHN is not showing for the admin.

**Comment by trjExpensify** [comment]
> Isn't there still a bug insofar as the green dot on the workspace chat for the admin for an expense report that is $0 containing only the failed receipt scan?

Great, looks like that's resolved then. Let's close it!
