### ISSUE TITLE
[PAY 9/12] Content jumps on Safari when scrolling down after comment linking

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#47518]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @janicduplessis 
**Slack conversation:**

## Action Performed:

- In a chat with many messages copy the link to a message and send it
- Click on the message link from the first step
- Scroll down

## Expected Result:

When scrolling down, content doesn't jump.

## Actual Result:

When scrolling down, content jumps.

## Workaround:

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/13eaa301-f557-4c14-be7c-015fc539443e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by janicduplessis** [comment]
Might want to assign @ishpaul777 on this one too, since he's been working on the comment linking issues with me.

**Comment by bfitzexpensify** [comment]
Done - apologies for the delay @ishpaul777, was out of office

**Comment by bfitzexpensify** [comment]
I am heading out of office until September 21st, so assigning a buddy to watch over this in my absence. 

Current status: payment due on September 12th (title updated)

**Comment by bfitzexpensify** [comment]
Apologies @ishpaul777 - messed up the buddy assignment while I was OOO. Offer sent via Upwork

**Comment by bfitzexpensify** [comment]
Payment complete! Closing this out
