### ISSUE TITLE
[hold for payment 2024-09-04] [$250] Update UpdatePolicyConnectionConfiguration to be 1:1:1 - Part 2

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#47520]
## Problem

Our UpdatePolicyConnectionConfiguration API command is not 1:1:1 - it is the same API call for all related user actions, when it should be split up for each connection (QBO, Xero, etc.) and configuration setting (`autoSyncVendor`, `enableNewCategories`, etc.). At the end of this we should not call that function anywhere.

This is polish for [the Collect QBO project](https://github.com/Expensify/Expensify/issues/201614).

## Solution

When we created the NetSuite commands, we followed the correct pattern, and so need to do so here too.

This requires backend and frontend work in tandem (to create the commands and then to use them), so we're looking for a contributor(s) to handle the frontend. You can see an example PR [here](https://github.com/Expensify/App/pull/46234/files) - there is some extra prep work there that you can ignore, but adjusting all calls like [this](https://github.com/Expensify/App/pull/46234/files#diff-9b64c08598bd055cd4122614010389a293da53ab63274d7017b9f870b96a2e62L85-R85) is what we're going for:

```diff
- Connections.updatePolicyConnectionConfig(policyID, CONST.POLICY.CONNECTIONS.NAME.QBO, CONST.QUICK_BOOKS_CONFIG.REIMBURSABLE_EXPENSES_ACCOUNT, row.value);
+ QuickbooksOnline.updateQuickbooksOnlineReimbursableExpensesAccount(policyID, row.value);
```

Here is a list of the commands handled in this issue:
- UpdateXeroImportTrackingCategories
- UpdateXeroImportTaxRates
- UpdateXeroTenantID
- UpdateXeroMappings
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f780930d7cefc51d</li>
        <li>Upwork Job ID: 1825538900212407946</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103587463</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by hungvu193** [comment]
I'll take this one as contributor

**Comment by hungvu193** [comment]
I'll raise a PR soon

**Comment by dangrous** [comment]
Backend PR is merged, though not yet on staging, but should be soon!

**Comment by dangrous** [comment]
Spoke too soon, I guess - this is on staging now, so code away!

**Comment by hungvu193** [comment]
@dangrous just to confirm:
 - `UpdateXeroImportTrackingCategories` will replace [this one](https://github.com/Expensify/App/blob/50de692ff915d7998bff3fb0d024446b59912b52/src/pages/workspace/accounting/xero/XeroTrackingCategoryConfigurationPage.tsx#L57)
 - `UpdateXeroImportTaxRates` will replace [this one](https://github.com/Expensify/App/blob/50de692ff915d7998bff3fb0d024446b59912b52/src/pages/workspace/accounting/xero/XeroTaxesConfigurationPage.tsx#L37)
 - `UpdateXeroTenantID` will replace [this one](https://github.com/Expensify/App/blob/50de692ff915d7998bff3fb0d024446b59912b52/src/pages/workspace/accounting/xero/XeroOrganizationConfigurationPage.tsx#L62)
 - `UpdateXeroMappings` will replace [this one](https://github.com/Expensify/App/blob/50de692ff915d7998bff3fb0d024446b59912b52/src/pages/workspace/accounting/xero/XeroMapTrackingCategoryConfigurationPage.tsx#L63)

**Comment by dangrous** [comment]
yep perfect! double check that there aren't any other usages but that's it

**Comment by hungvu193** [comment]
Little update, draft PR is [here](https://github.com/Expensify/App/pull/47905)

**Comment by dangrous** [comment]
I think this is on prod? I'm going to grab a BZ to handle payment (and also help us figure that out haha)

**Comment by dangrous** [comment]
@joekaufmanexpensify we're in the 7 day regression period for this one, but assigned you to help us figure out when this one went to prod and handle payment when payment is needed!

**Comment by joekaufmanexpensify** [comment]
Will take care of that now!

**Comment by joekaufmanexpensify** [comment]
Payment due here is:

- $250 to @hungvu193 for PR via NewDot. 
- $250 to @ishpaul777 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment!

**Comment by joekaufmanexpensify** [comment]
Closing as only thing left here is for @hungvu193 to request payment via NewDot!

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
