### ISSUE TITLE
Reply – Reply number is 1 for user B when create a multi-level thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47526]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4863048
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as user A
3. Open chat with user B
4. Log in as user B in Incognito tab
5. Open chat with user A
6. As user A send a message, reply in thread and send comment
7. Create a thread within the thread
8. Repeat steps until you have 5 different levels of threads
9. As user B observe chat

## Expected Result:
Number of Replies is 5

## Actual Result:
Number of Reply is 1

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1d7e8f93-7a39-44a3-8001-914f303b820a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
BE issue : returning different `action.childVisibleActionCount` for the two users

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
BE element here

**Comment by dylanexpensify** [comment]
Will likely take a bit to find volunteer here

**Comment by dylanexpensify** [comment]
pending someone picking up

**Comment by dylanexpensify** [comment]
Same

**Comment by dylanexpensify** [comment]
Same

**Comment by dylanexpensify** [comment]
Closing for focus
