### ISSUE TITLE
[Awaiting payment some time in the past] [$250] Workspace switcher - Empty workspace switcher does not have "Create a workspace" modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47525]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account (account must have no workspace)
3. Open workspace switcher

## Expected Result:
The empty workspace switcher will have "Create a workspace" modal

## Actual Result:
The empty workspace switcher does not have "Create a workspace" modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d08f5aa2-54ec-4d01-82c3-2bac3ed8e4cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01720ac33ff733e428</li>
        <li>Upwork Job ID: 1824216428360268213</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103545556</li>
<li>Krishna2323 | Contributor | 103545557</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by yuwenmemon** [comment]
@Krishna2323 LGTM, thanks for identifying the regression as well. cc @tienifr

**Comment by yuwenmemon** [comment]
@Krishna2323 Are you able to spin up a PR for CP ASAP?

**Comment by yuwenmemon** [comment]
@Krishna2323 Thanks! I'll take this out of review while we work on the larger scoped issue.

**Comment by yuwenmemon** [comment]
@trjExpensify Can you help with the payment?

**Comment by trjExpensify** [comment]
Yeah bwoii!

Payment summary as follows: 

- $250 to @Krishna2323 for the fix
- $250 to @dukenv0307 for the C+ review 

I note the deploy blocker comment from melvin, but @yuwenmemon @dukenv0307 you agree with @Krishna2323's [comment here](https://github.com/Expensify/App/pull/47527#issuecomment-2296622601) that states that wasn't a DB from this PR?

**Comment by trjExpensify** [comment]
Great, settled up with you both. Closing!
