### ISSUE TITLE
[HOLD for payment 2024-09-26] [$250] Update UpdatePolicyConnectionConfiguration to be 1:1:1 - Part 5

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#47523]
## Problem

Our UpdatePolicyConnectionConfiguration API command is not 1:1:1 - it is the same API call for all related user actions, when it should be split up for each connection (QBO, Xero, etc.) and configuration setting (`autoSyncVendor`, `enableNewCategories`, etc.). At the end of this we should not call that function anywhere.

This is polish for [the Collect QBO project](https://github.com/Expensify/Expensify/issues/201614).

## Solution

When we created the NetSuite commands, we followed the correct pattern, and so need to do so here too.

This requires backend and frontend work in tandem (to create the commands and then to use them), so we're looking for a contributor(s) to handle the frontend. You can see an example PR [here](https://github.com/Expensify/App/pull/46234/files) - there is some extra prep work there that you can ignore, but adjusting all calls like [this](https://github.com/Expensify/App/pull/46234/files#diff-9b64c08598bd055cd4122614010389a293da53ab63274d7017b9f870b96a2e62L85-R85) is what we're going for:

```diff
- Connections.updatePolicyConnectionConfig(policyID, CONST.POLICY.CONNECTIONS.NAME.QBO, CONST.QUICK_BOOKS_CONFIG.REIMBURSABLE_EXPENSES_ACCOUNT, row.value);
+ QuickbooksOnline.updateQuickbooksOnlineReimbursableExpensesAccount(policyID, row.value);
```

Here is a list of the commands handled in this issue:

- UpdateQuickbooksOnlineReceivableAccount
- UpdateQuickbooksOnlineExportDate
- UpdateQuickbooksOnlineNonReimbursableExpensesAccount
- UpdateQuickbooksOnlineCollectionAccountID

If there are others that follow the same pattern as `UpdateQuickbooksOnlineExport` (same object, different keys) we will need to split those as well.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f77142563137f66e</li>
        <li>Upwork Job ID: 1825578111419953725</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 103590171</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by dangrous** [comment]
@rushatgabhane can you comment here so I can assign you as C+ before assigning @hoangzinh?

**Comment by rushatgabhane** [comment]
hello

**Comment by dangrous** [comment]
fyi @hoangzinh backend pr is now deployed so you should be able to test!

**Comment by dangrous** [comment]
Noted in Slack but for the GitHub record - QBO backend PR not yet on staging, should be there today!

**Comment by dangrous** [comment]
on staging! should be ready to test.

**Comment by dangrous** [comment]
@greg-schroeder just grabbing you for eventual payment; this hasn't hit prod yet but should shortly!

**Comment by greg-schroeder** [comment]
Consider me grabbed

**Comment by greg-schroeder** [comment]
Deployed 9/19, regression period should go to 9/26 I believe

**Comment by greg-schroeder** [comment]
@dangrous @hoangzinh Is[ this comment](https://github.com/Expensify/App/issues/47523#issuecomment-2358029099) accurate?

**Comment by dangrous** [comment]
Nope, no blocker! It was a sync issue but not specific to this PR. (Correct me if I'm wrong @hoangzinh @rushatgabhane )

**Comment by greg-schroeder** [comment]
Sounds good! All set for tomorrow:

Payment summary:

Contributor: @hoangzinh - $250 - To be paid via Upwork 9/26
C+: @rushatgabhane - $250 - You can make a manual request via ND

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
