### ISSUE TITLE
Request money - Currency symbols font sizes are not unique for all the currencies

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#4752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Not adding deployblocker label as it occurs in production too

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Log in with expensifail account.
3. Click the FAB button again and select `Request Money`.
4. Click on the currency.
5. Use the search function in the currency list and select a currency.

## Expected Result:
Font size should be unique for all the currencies
## Actual Result:
Some currencies are having different font
## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web ✔️
- iOS ✔️
- Android ✔️
- Desktop App ✔️
- Mobile Web ✔️

**Version Number:**
1.86-2
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5199120_d](https://user-images.githubusercontent.com/43996225/129993288-42248581-6fb4-4399-a7b6-580fab1940a9.jpg)
![Bug5199120_den](https://user-images.githubusercontent.com/43996225/129993291-a7f5badf-4e48-4609-a3b6-4ebf5dda2bd3.jpg)

**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment]
Issue reproducible during KI retests

**Comment by tylerkaraszewski** [comment]
I don't understand this issue. Are we saying the size of the symbol for Vietnamese dong is too small in the dropdown list?

**Comment by isagoico** [comment]
The main issue is that the currecies mentioned above dont use the same font family as the rest of the app.

**Comment by tylerkaraszewski** [comment]
What actual account do I need to log in with to see a FAB button? Where do I see that button?

**Comment by isagoico** [comment]
The FAB button is the "Floating Action Button", this one 
![image](https://user-images.githubusercontent.com/44479856/130703216-d929bbe3-ddf5-4457-9439-b732aa331af5.png)

**Comment by tylerkaraszewski** [comment]
All these currencies use the same font, they just use a font that has some ugly symbols for some currencies. The font used depends somewhat on your browser or OS, so we don't even fully controls the details of what font is chosen. We could try and switch the font, but I don't think this is worth fixing currently.

**Comment by shawnborton** [comment]
The font used should not depend on the OS as we serve up our brand font (GT America Exp) on all platforms. Perhaps we need to get these font symbols added to our font? It looks like this is all we have currently:
![image](https://user-images.githubusercontent.com/2319350/130749004-8984f172-5fa2-44f2-a70f-110eabb5e3f1.png)


But that being said... I agree, I don't think this is a problem worth solving right now.
