### ISSUE TITLE
[HOLD for Payment 2024-10-04][$250] Update UpdatePolicyConnectionConfiguration to be 1:1:1 - Part 4

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#47522]
## Problem

Our UpdatePolicyConnectionConfiguration API command is not 1:1:1 - it is the same API call for all related user actions, when it should be split up for each connection (QBO, Xero, etc.) and configuration setting (`autoSyncVendor`, `enableNewCategories`, etc.). At the end of this we should not call that function anywhere.

This is polish for [the Collect QBO project](https://github.com/Expensify/Expensify/issues/201614).

## Solution

When we created the NetSuite commands, we followed the correct pattern, and so need to do so here too.

This requires backend and frontend work in tandem (to create the commands and then to use them), so we're looking for a contributor(s) to handle the frontend. You can see an example PR [here](https://github.com/Expensify/App/pull/46234/files) - there is some extra prep work there that you can ignore, but adjusting all calls like [this](https://github.com/Expensify/App/pull/46234/files#diff-9b64c08598bd055cd4122614010389a293da53ab63274d7017b9f870b96a2e62L85-R85) is what we're going for:

```diff
- Connections.updatePolicyConnectionConfig(policyID, CONST.POLICY.CONNECTIONS.NAME.QBO, CONST.QUICK_BOOKS_CONFIG.REIMBURSABLE_EXPENSES_ACCOUNT, row.value);
+ QuickbooksOnline.updateQuickbooksOnlineReimbursableExpensesAccount(policyID, row.value);
```

Here is a list of the commands handled in this issue:
- UpdateQuickbooksOnlineAutoSync
- UpdateQuickbooksOnlineSyncPeople
- UpdateQuickbooksOnlineReimbursementAccountID
- UpdateQuickbooksOnlineExport - We will need to split up this one even further, one for each piece of the object that it is updating. We can discuss this on the PRs.

If there are others that follow the same pattern as `UpdateQuickbooksOnlineExport` (same object, different keys) we will need to split those as well.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eef0bc66034bca70</li>
        <li>Upwork Job ID: 1825578317140040932</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103590186</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by dangrous** [comment]
Sorry @zanyrenney forgot to remove `Bug` from this one - you can ignore until we're ready for a payment

**Comment by zanyrenney** [comment]
Sounds good, thanks for the update @dangrous

**Comment by dangrous** [comment]
@shubham1206agra @rushatgabhane can you comment here so I can assign you? Thanks!

**Comment by rushatgabhane** [comment]
@dangrous fyi, we don't need to comment for getting assigned as we're on exfy org in GitHub

**Comment by dangrous** [comment]
oh whoops! sorry about that.

**Comment by zanyrenney** [comment]
any update here please @shubham1206agra

**Comment by zanyrenney** [comment]
cool!

**Comment by dangrous** [comment]
fyi backend pr is deployed now so should be able to test the new commands!

**Comment by dangrous** [comment]
Noted in Slack but for the GitHub record - QBO backend PR not yet on staging, should be there today!

**Comment by dangrous** [comment]
back end PR is up on staging!

**Comment by dangrous** [comment]
Shush Melvin this was just merged!

**Comment by dangrous** [comment]
Why no automationnnnnnn - went to prod 3 days ago according to the comment on the PR

**Comment by zanyrenney** [comment]
Hi! I will be OOO until 7th october, please can you handle the final stage here of the payment @RachCHopkins thanks!

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @shubham1206agra to be paid $250 via Upwork
- Contributor+: @rushatgabhane to be paid $250 NewDot Manual Requests

Upwork job [here](https://www.upwork.com/jobs/~01eef0bc66034bca70)

@rushatgabhane I'm late to the party here - can you confirm that's correct please?

**Comment by RachCHopkins** [comment]
Ok, I see that @dangrous updated the GH title last week, so I assume if the pricetag was wrong, it would have been corrected. Going to go ahead and pay this as it's due.

**Comment by RachCHopkins** [comment]
@shubham1206agra the original offer had expired, so I have sent you a new manual [offer](https://www.upwork.com/nx/wm/offer/104314312).

**Comment by zanyrenney** [comment]
Payment Summary:

Contributor: @shubham1206agra  paid $250 via Upwork - completed.
Contributor+: @rushatgabhane to be paid $250 NewDot Manual Requests

Thanks for the new manual offer sent @RachCHopkins I have paid it out.

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
