### ISSUE TITLE
Search-Expense report opens instead of transaction thread when expense with comment is deleted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47538]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit two expenses to any user.
3. Go to transaction thread of second expense.
4. Send a reply and delete the expense.
5. Go to Search.
6. Click on the first expense submitted in Step 2.

## Expected Result:
The transaction thread should open.

## Actual Result:
The expense report opens.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/032598f2-fbf5-4438-a61a-f9195d3e249f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by MonilBhavsar** [comment]
cc @luacmartins since you're working on Search and seems to be coming from https://github.com/Expensify/App/pull/46324. 
I believe this is backend back. We need to account for deleted transactions on the server side

**Comment by luacmartins** [comment]
I don't think this is a blocker. We can still access the data, just one level deeper. I'll look into a backend solution for this.

**Comment by Beamanator** [comment]
Marked NAB here but not in the deploy checklist, interesting 🧐 🤣 :paddlin:

**Comment by Kicu** [comment]
@luacmartins do I assume correctly that for now there is no work in the on front-end App side of things?

**Comment by luacmartins** [comment]
@shawnborton @JmillsExpensify could you confirm the behavior in this case? Should we open the transaction thread or expense report in this case? TLDR user has 2 expenses, leaves a comment on one of the threads and deletes that expense, effectively ending up with a single expense report.

**Comment by shawnborton** [comment]
Hmm I am a bit stumped on that one. Seems like it would make more sense to just open up the expense view, especially from the Expenses > All filter.

**Comment by luacmartins** [comment]
So open the expense report instead of the transaction thread?

**Comment by shawnborton** [comment]
Opposite - in that case, seems like opening the transaction view is better.

**Comment by luacmartins** [comment]
Hmm ok, so we'd need to change the backend logic a bit.

**Comment by luacmartins** [comment]
Cool, got a PR up to fix this one

**Comment by luacmartins** [comment]
This has been fixed!
