### ISSUE TITLE
[HOLD for payment 2024-09-19] [$250] Workspace - Default avatar is different in full screen after uploading avatar and removing it

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to Profile.
4. Upload a workspace avatar.
5. Remove the workspace avatar.
6. Go to any workspace room.
7. Click on the room header.
8. Click on the workspace avatar.

## Expected Result:
The default workspace avatar when viewed in full screen should match.

## Actual Result:
The default workspace avatar when viewed in full screen is different from the actual avatar after uploading a custom avatar and removing it.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/45613f12-70d1-4f5b-804e-00362b915e87

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4f7e2fd3a698d7c</li>
        <li>Upwork Job ID: 1827400295018022101</li>
        <li>Last Price Increase: 2024-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103826687</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MariaHCD</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment]
Polish collect issue

**Comment by kevinksullivan** [comment]
Hi @Pujan92 any update on the reviews?

**Comment by kevinksullivan** [comment]
Friendly bump @Pujan92 . If you are unable to get back to this early next week I'll have to reassign.

**Comment by Pujan92** [comment]
Sorry @kevinksullivan for the delay.

**Comment by Pujan92** [comment]
RCA from both the proposals is correct where `originalFileName` hasn't been updated in optimistic data while deleting the workspace avatar. Regarding the solution, I prefer @FitseTLT's [proposal](https://github.com/Expensify/App/issues/47535#issuecomment-2293589544) as it is also handling the failure case and can be considered as a complete solution.

🎀👀🎀 C+ reviewed

**Comment by MariaHCD** [comment]
Reviewing this today

**Comment by kevinksullivan** [comment]
Looping in another BZ for payment as I'm going OOO

**Comment by MariaHCD** [comment]
Looks like the fix was deployed two weeks ago: https://github.com/Expensify/App/issues/48791

**Comment by stephanieelliott** [comment]
Oop yea looks like automation didn't work, this was ready to pay out on 9/19. Setting up for payment now.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @FitseTLT $250 via Upwork -- PAID 
 - Contributor+: @Pujan92 $250 via ND, please request 
 
 Upwork job is here: https://www.upwork.com/jobs/~01a4f7e2fd3a698d7c

**Comment by garrettmknight** [comment]
$250 approved for @Pujan92
