### ISSUE TITLE
Illustration gets hidden behind the search field

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47553]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
Issue was found when executing this PR: https://github.com/Expensify/App/pull/42413
**Email or phone of affected tester (no customers):** nathanmulugetatesting+hakmw@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com and sign up with a new Gmail account
2. Click on FAB > Submit expense
3. Enter an amount and click next

## Expected Result:
The illustration becomes fully visible while the keyboard is up

## Actual Result:
Some part of the illustration gets hidden behind the search field if the keyboard is up

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8b5f5a21-d099-484f-8c56-d410c19c1390

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by Beamanator** [comment]
Supposedly this is also getting fixed in https://github.com/Expensify/App/pull/47555

**Comment by nkuoch** [comment]
@IuliiaHerets Can you check if it's been fixed by https://github.com/Expensify/App/pull/47555?

**Comment by IuliiaHerets** [comment]
@nkuoch The issue is no longer reproduced on mWeb and Android app

https://github.com/user-attachments/assets/0f2d508c-f59d-476b-8a1e-230b2f519553


https://github.com/user-attachments/assets/9a974d4d-d8ad-49c3-bb09-5f5f7a3ed621

**Comment by joekaufmanexpensify** [comment]
@nkuoch that means we're good to close this?

**Comment by Beamanator** [comment]
Nice, looks like it!

**Comment by joekaufmanexpensify** [comment]
Sweet. Done!
