### ISSUE TITLE
Search - To field shows fallback avatar without name when submitting expense as employee

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47551]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User is invited to the workspace.
- The following steps will be performed by the invited user.

1. Go to staging.new.expensify.com
2. Go to the workspace chat.
3. Submit an expense.
4. Go to Search.
5. Note the receiver in To field.

## Expected Result:
The receiver in To field will show the name and avatar of the workspace admin.

## Actual Result:
The receiver in To field does not show name and it shows fallback avatar.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3aca703a-9c97-46b4-a619-0d829c80f6d6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by grgia** [comment]
Removing deploy blocker label given

> The snapshot data from BE is missing personalDetailsList data for those managerIDs.

**Comment by grgia** [comment]
Could you confirm @luacmartins

**Comment by luacmartins** [comment]
Yea, it seems like we're missing the managerID details for the report. I wonder if this happens with open reports. I'll look into this on Monday when I'm back from ooo.

**Comment by Christinadobrzyn** [comment]
Hi @luacmartins can you provide an update for Melvin?

**Comment by luacmartins** [comment]
This was fixed [here](https://github.com/Expensify/Auth/pull/12047). Closing
