### ISSUE TITLE
[$250] NetSuite - Inconclusive use of spaces before and after a backslash

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/47091
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import

## Expected Result:
All of the options should follow a similar syntax: "text/text" or "text / text".

## Actual Result:
Inconclusive use of spaces before and after a backslash. One option is "Custom segments/records", the other is "Customers / projects".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7d908c91-ed39-4345-a92c-e79f08bb8023

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad3e945fffc220c0</li>
        <li>Upwork Job ID: 1825680410861600909</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103678598</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control

**Comment by VictoriaExpensify** [comment]
I agree that this should be consistent. A low priority but we should fix it

**Comment by VictoriaExpensify** [comment]
Closing as the issue was fixed elsewhere
