### ISSUE TITLE
Report fields - System message for report field edit only appears for submitted report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47565]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has report fields
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense but do not click on the submit button in the report
4. Go to expense report
5. Click on the report field
6. Edit the report field and save it
7. Refresh the report
8. Note that the system message for report field does not show up in the report
9. Click Submit button
10. Edit the report field and save it
11. Refresh the report
12. Note that the system message for report field only shows up when the report is submitted

## Expected Result:
The system message for report field edit should appear every time the report field is edited regardless of the state of the report

## Actual Result:
The system message for report field edit only appears after the report is submitted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/28792758-7fa5-4661-9afc-c1cbfc940ae9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
I don't think this is a bug. When an expense is `Open`, the submitter should be free to amend as much as they like without adding endless audits to the room right?

**Comment by twisterdotcom** [comment]
Asking: https://expensify.slack.com/archives/C01SKUP7QR0/p1724251813469019

**Comment by twisterdotcom** [comment]
Okay @dylanexpensify confirmed this is expected.
