### ISSUE TITLE
[$250] The "new workspace" button is shown in Global Create to accounts already on workspaces

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47567]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723669119268099

## Action Performed:
1. Invite user A to user B workspace
2. Login as User B
3. Click on global +
## Expected Result:
Create new workspace should not appear
## Actual Result:
New workspace option appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (8)](https://github.com/user-attachments/assets/8b78d5c3-9279-4c31-8ced-72130378eff6)

![Snip - (2) New Expensify - Google Chrome](https://github.com/user-attachments/assets/fec0084b-0767-4bd6-801c-ab31c5a07238)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c30fdb0f2028e60</li>
        <li>Upwork Job ID: 1824549832586983861</li>
        <li>Last Price Increase: 2024-08-16</li>
    </ul>
</details>

**Comment by sakluger** [comment]
Before I add the external label, I'm confirming the expected behavior in the original bug report thread in Slack.

**Comment by arosiclair** [comment]
@daledah @thesahindia 

We should also remove the `includeOnlyFreePolcies` param and `policy.type === CONST.POLICY.TYPE.FREE` since there are no free policies anymore. Then let's use a new `includeOnlyAdminPolicies` param that's  `false` by default. So the new initial condition should just be

```
const chatEnabledPolicies = Object.values(policies).filter((policy) => policy?.isPolicyExpenseChatEnabled && (!includeOnlyAdminPolicies || policy.role === CONST.POLICY.ROLE.ADMIN));
```

**Comment by sakluger** [comment]
The automation didn't work, but this is on prod! Payment was due around Sept 2.

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @daledah $250, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/103905329
Contributor+: @thesahindia $250, please request on Newdot

**Comment by sakluger** [comment]
@thesahindia could you please let me know if you think we need regression test steps here?

**Comment by sakluger** [comment]
Thanks!

- I completed the Upwork payment to @daledah 
- I created the GH issue for new regression test steps: https://github.com/Expensify/Expensify/issues/429317

I think we're all good here!

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
