### ISSUE TITLE
[HOLD for payment 2024-09-06] [$250] There is no selected background after selecting Submission frequency as monthly

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47574]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ZhenjaHorbach
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723812299682989

## Action Performed:

1. Open account settings
2. Open workspaces and choose any workspace
3. In more features turn on Workflows and open it
4. Turn on Delay submissions and open Submission frequency
5. Choose monthly

## Expected Result:
There should be selected background
## Actual Result:
Notice that there is a check mark next to monthly, but there is no selected background
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a015e603-1770-4d0a-b92f-39c1e1e2d440

https://github.com/user-attachments/assets/69184b3c-f6d7-4dda-b839-b273ebfed781

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01010057c5f8be0ff8</li>
        <li>Upwork Job ID: 1824501452626526630</li>
        <li>Last Price Increase: 2024-08-16</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 103626776</li>
<li>Krishna2323 | Contributor | 103626778</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by puneetlath** [comment]
Hmm, I think if they all touch this same flow, then let's just fix them here.

**Comment by ZhenjaHorbach** [comment]
Looks like production deploy automation failed: This should be on [HOLD for Payment 2024-09-06] according to [prod deploy checklist](https://github.com/Expensify/App/issues/48035), confirmed in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1725051480370659?thread_ts=1725050431.962859&cid=C01GTK53T8Q.)

**Comment by puneetlath** [comment]
Ah ok cool. @ZhenjaHorbach can you complete the checklist in that case?

**Comment by ZhenjaHorbach** [comment]
BugZero Checklist

> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@ZhenjaHorbach] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/42019

> * [x]  [ @ZhenjaHorbach] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/42019/files#r1747587652

> * [x]  [@ZhenjaHorbach] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

NA

> * [x]  [@ZhenjaHorbach] Determine if we should create a regression test for this bug.
> * [x]  [@ZhenjaHorbach] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

Since it's a minor issue with a simple fix that we use in many places
I'm not sure if regression tests are needed here

**Comment by ZhenjaHorbach** [comment]
> Ah ok cool. @ZhenjaHorbach can you complete the checklist in that case?

Done !

**Comment by puneetlath** [comment]
Great, thanks everyone. All paid!
