### ISSUE TITLE
Style mismatch for Add rate button in Taxes

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** ZhenjaHorbach
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723754129659149

## Action Performed:

1. Open app
2. Open account settings and open workspaces
3. Choose any workspace
4. In more features turn on Distance rates, Categories, Tags and Taxes

## Expected Result:
Add rate button in Taxes has should match with  other buttons in the headers (Distance rates, Categories, Tags)
## Actual Result:
Notice that Add rate button in Taxes has different styles relative to other buttons in the headers (Distance rates, Categories, Tags)
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a737c892-4ff9-4245-8011-74293c4e21c5

https://github.com/user-attachments/assets/cabed25a-3829-4c93-81f4-f485aab0c127

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
I don't think this should be fixed, it's a non-issue.
