### ISSUE TITLE
[HOLD for payment 2024-09-05] [$125]  No space between headline and paragraph on "What's your company address?" page in add VBA flow

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1723725343085679

## Action Performed:
Go to workspace
Add bank account
Continue to step 4 to add company address
## Expected Result:
The paragraph text below the headline should be  formatted correctly
## Actual Result:
The paragraph text below the headline is also not formatted correctly, we're using our textSupporting color on other pages
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-08-15 at 08 36 41@2x](https://github.com/user-attachments/assets/e9e336dd-b80e-4e68-a8a5-3ee8548081da)
![CleanShot 2024-08-15 at 08 35 12@2x](https://github.com/user-attachments/assets/c86146ef-5891-480e-beb6-11f3a829db9d)

https://github.com/user-attachments/assets/eac34772-da66-48a3-9032-772ff055134d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f75fd458cef3250</li>
        <li>Upwork Job ID: 1825662744111231549</li>
        <li>Last Price Increase: 2024-08-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No space between headline and paragraph on "What's your company address?" page in add VBA flow.
### What is the root cause of that problem?
We are not adding margin or padding bottom.
https://github.com/Expensify/App/blob/279f561c90adef037b27f73ef96c8487e44d0be8/src/pages/ReimbursementAccount/BusinessInfo/substeps/AddressBusiness.tsx#L82
### What changes do you think we should make in order to solve the problem?

we can add `mb3` or `pb3`
### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment]
Ah yes, we're missing the space here
<img width="376" alt="image" src="https://github.com/user-attachments/assets/118b2515-0db8-4965-8503-66b9e3f4831a">

Looks like the other pages are correct but worth checking as part of this. I think this can be external.

**Comment by Christinadobrzyn** [comment]
Gonna add external to get someone to make this change.

**Comment by Christinadobrzyn** [comment]
@sobitneupane can you check on these proposals to see if any will work?

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/47571#issuecomment-2293751675) @MuaazArshad 

We need to make some styling change to solve the issue. We can probably add `styles.pv3` and `styles.textSupporting` as in `BeneficialOwnerInfo`

```
            <Text style={[styles.pv3, styles.textSupporting]}>{translate('beneficialOwnerInfoStep.regulationRequiresUsToVerifyTheIdentity')}</Text>
```

Proposal from @MuaazArshad looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by MuaazArshad** [comment]
Hey @mountiny bump!

**Comment by mountiny** [comment]
The price should have been decreased at the start, sorry

Assigned @MuaazArshad

**Comment by MuaazArshad** [comment]
I'll raise PR in few hours.

**Comment by Christinadobrzyn** [comment]
Looks like PR is in the works!

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/47978

**Comment by MuaazArshad** [comment]
@mountiny I haven't received an offer for this issue on Upwork yet.

**Comment by mountiny** [comment]
I have updated the issue title and added labels, the payment date should be on the 5th I think @Christinadobrzyn

**Comment by Christinadobrzyn** [comment]
Sounds good! I'm going to be ooo 9/4 - 9/10 so going to add a BZ teammate to issue payment. 

Upwork job - https://www.upwork.com/ab/applicants/1831113384304103952/hired

- @MuaazArshad can you confirm if you want to be paid in Upwork and send over your Upwork profile?
- @sobitneupane can you confirm if you are paid in NewDot?

Payouts due:

- [ ] Contributor: $125 @MuaazArshad 
- [ ] Contributor+: $125 @sobitneupane 

Do we need a regression test?

**Comment by MuaazArshad** [comment]
Yes! I want to be paid through upwork.

https://www.upwork.com/freelancers/~017994bec44c81b9d0

**Comment by sonialiap** [comment]
@MuaazArshad offer sent
@sobitneupane please request in ND - $125 ([summary](https://github.com/Expensify/App/issues/47571#issuecomment-2327628509))

**Comment by MuaazArshad** [comment]
Accepted the offer

**Comment by garrettmknight** [comment]
$125 approved for @sobitneupane
