### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Invoices - Hold option is present in context menu before invoice report is opened

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47570]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4864172
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice.
3. Enter amount, select any user and send the invoice.
4. Without clicking on the invoice preview (important), right click on the invoice preview in invoice chat.
5. Note that Hold option is present.
6. Click on the invoice preview.
7. Return to invoice chat.
8. Right click on the invoice preview.
9. Note that Hold option disappears.

## Expected Result:
In Step 5, Hold option should not appear for invoice because invoices cannot be held.

## Actual Result:
In Step 5, Hold option appears for invoice.
In Step 9, Hold option disappears after user opens the invoice report.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c9742567-929c-47e0-bdd2-3d8841f59354

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839686152805650965</li>
        <li>Upwork Job ID: 1839686152805650965</li>
        <li>Last Price Increase: 2024-09-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
I agree this is an issue and we should fix it!

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by codewaseem** [comment]
Friendly bump @abdulrahuman5196.

**Comment by abdulrahuman5196** [comment]
Sorry checking again

**Comment by abdulrahuman5196** [comment]
@VictoriaExpensify / @IuliiaHerets I don't understand the issue? Are we not supposed to show the Hold in the context menu, because if I go to the invoice view I can see the Hold option.
If we shouldn't show the Hold option in context, under what conditions we shouldn't show?

**Comment by VictoriaExpensify** [comment]
Posting to get some clarification on this one

**Comment by VictoriaExpensify** [comment]
https://expensify.slack.com/archives/CSL3XBCCR/p1725609816349509

**Comment by VictoriaExpensify** [comment]
Not overdue

**Comment by VictoriaExpensify** [comment]
Still getting clarification on this one!

**Comment by VictoriaExpensify** [comment]
bump @abdulrahuman5196

**Comment by abdulrahuman5196** [comment]
Checking now.

**Comment by abdulrahuman5196** [comment]
>Ok chatted about this one in #wave_Collect. We are not allowing Invoices to be held (if that changes, it will be way down the track), so yes - we should proceed with a fix for this one.

Got it.


>we don't really want the Hold option to appear at all for Invoices. I'm really sorry, but is the video you've linked there showing anything different to what was posted in the initial bug report? It looks like it's the same thing but, if I've missed something and you are seeing the Hold option for Invoices somewhere else, then a bug report should be created for it

@VictoriaExpensify 

This original OP issue is happening and the bug is also happening at a different place as pointed in the below video. Should we handle it part of this issue or create separate issue for it?


https://github.com/user-attachments/assets/897ebc58-f99a-4121-985c-2e39d204bbad

**Comment by codewaseem** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/47570#issuecomment-2296506811)
To hide hold option from ReportDetails view. 

@abdulrahuman5196

**Comment by VictoriaExpensify** [comment]
Thanks for clarifying @abdulrahuman5196 - got it!

Correct, we do not want to show the "Hold" option anywhere for invoices. Would it be easy enough to handle both of these in the same issue?

**Comment by codewaseem** [comment]
@VictoriaExpensify, yes changes are small and both can be handled in the same issue.

**Comment by abdulrahuman5196** [comment]
@codewaseem's proposal here https://github.com/Expensify/App/issues/47570#issuecomment-2296506811 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by mjasikowski** [comment]
@codewaseem proposal looks good, feel free to create the PR

**Comment by codewaseem** [comment]
Thanks, @mjasikowski, @abdulrahuman5196, will create the PR asap.

**Comment by codewaseem** [comment]
Hi @mjasikowski, should I create a PR now or after the job is added on upwork?

**Comment by mjasikowski** [comment]
@codewaseem I've asked the team to help with creating the job, let's make sure it's up first and then you can work on the PR. Apologies, I missed the automation failing message.

**Comment by mallenexpensify** [comment]
@codewaseem please apply for the Upwork job and comment here once you have, then we'll hire you. Thx
[upwork.com/jobs/~021839686152805650965](https://www.upwork.com/jobs/~021839686152805650965)

**Comment by codewaseem** [comment]
@mallenexpensify I have applied for the Upwork job, please have a look. Thanks.

**Comment by mallenexpensify** [comment]
Offer sent @codewaseem !

**Comment by codewaseem** [comment]
@mallenexpensify thanks for the offer!

@abdulrahuman5196 @mjasikowski I created the PR. This is my first PR here, please let me know if I have missed anything.

Thanks!

**Comment by VictoriaExpensify** [comment]
Payment Summary:
Contributor: @codewaseem paid $250 via Upwork

@abdulrahuman5196 - can you please complete the checklist and I'll organise payment. TY!

**Comment by codewaseem** [comment]
Thanks @VictoriaExpensify!

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/45151/files#r1819687331

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not required.

>Determine if we should create a regression test for this bug.

Yes.

> If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Create an invoice with some amount and send it to another user.
2) Right-click on the invoice preview you just created to open the floating context menu.
3) Make sure there is no "Hold" option shown in the list.
4) Open the invoice by clicking the invoice preview.
5) Click on the invoice header to open the invoice details side-drawer.
6) Make sure there is no "Hold" option shown.


@VictoriaExpensify

**Comment by VictoriaExpensify** [comment]
Thanks @abdulrahuman5196 ! TestRail issue created - https://github.com/Expensify/Expensify/issues/439649

**Comment by VictoriaExpensify** [comment]
Payment Summary:

Contributor+: @abdulrahuman5196 owed $250 via NewDot
