### ISSUE TITLE
[$250] Expense - Submitted expense gets hidden after submitting previous expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47575]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1012@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new Gmail account and finish the onboarding flow by selecting "Something else"
3. Create a new workspace
4. Toggle on "Report fields"
5. Add a report field with "Text" type
6. Navigate to workspace chat and create an expense but don't click on submit
7. Open the combined transaction report and add a report field and save it
8. Click on Submit
9. Edit the report field and save it again
10. Click on From link on the sub header to navigate back to workspace chat
11. Click on the Expense to navigate to the combined report again
12. Click on the Workspace chat from the LHN
13. Submit another expense

## Expected Result:
The submitted expense appears under the previous expense

## Actual Result:
The newly submitted expense becomes hidden

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0deec07f-925d-4d22-ab8f-fcc6dfeab10e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014237f8a55cfa2b0b</li>
        <li>Upwork Job ID: 1826042561698508477</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment]
@fedirjh , lil help here plz.   At the :25 second mark of the vid, I don't understand how to get the expense to show in the main pain if Submit hasn't been clicked, Step 6 in the OP.  Do you? 

ie. from here
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/1301af4e-a45c-4400-86f9-dbffc9908092">

to it showing here
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/921ffcb3-4779-4357-925c-021595e603af">

Vid of what happens when I click outside the RHP, it takes me to the main chat without the expense showing

https://github.com/user-attachments/assets/44033016-0bc9-4aa8-a88b-e9e055929fbb

**Comment by tushar-a-b** [comment]
Are you guys able to reproduce this issue? 
I can't reproduce on latest main.

https://github.com/user-attachments/assets/a49fafec-b1c2-4ce4-a7d1-868320df5e4d

**Comment by mallenexpensify** [comment]
Thanks @fedirjh and @tushar-a-b , since 3 of us can't reproduce, I'm going to close.
