### ISSUE TITLE
Ensure we call ReconnectApp when the passed clientUpdateID is not in the DB

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#47582]
Context https://expensify.slack.com/archives/C03TQ48KC/p1723832372007299?thread_ts=1723826918.927409&cid=C03TQ48KC

# Problem

Right now when the clientUpdateID is not in the DB because it got deleted already, we are just assuming you are up to date, but we really can't know that, there might be updates that you missed.

# Solution

If we don't have the clientUpdateID in the DB we should instruct the client to call ReconnectApp to ensure they get all the data they might have missed

**Comment by iwiznia** [comment]
Need to update all overdue issues and then will work on this

**Comment by iwiznia** [comment]
ok writing down the solution here:
1. In auth, we will pass `getPreviousUpdateID` to `getPreviousUpdateID` [here](https://github.com/Expensify/Auth/blob/e8671e588c5b6182fd31be948081d47e94e7a23b/auth/lib/OnyxUpdates.cpp#L210)
1. At the beginning of `getPreviousUpdateID` we will check if `clientUpdateID` is in the DB, if it is not we will return `-1`
1. In Auth class [here](https://github.com/Expensify/Web-Expensify/blob/918cb6a289b71a8116333b5ffb538bb4e64e9fe2/lib/Auth.php#L571) if the response has `accounts.X.lastUpdateID` and `previousUpdateID` is `-1`, we will call `AppInit::reconnectApp` without `$updateIDFrom` 
1. This is the part that's unclear... we basically need to add them to the response, but not send them via pusher nor save them in the DB (so we don't want to call `Push_API::queue`) we basically want to include them in `Onyx::getAccountOnyxUpdates` so that they get added to the response [here](https://github.com/Expensify/Web-Expensify/blob/16a0159ad4f0881dfe36522c11b85a769d7763f4/api.php#L4821), so maybe we can convert the data to events and add them directly to `Pusher_API::$sentEvents` (which is what `Onyx::getAccountOnyxUpdates` uses). I think this should work, even if it is a little unconventional (because we did not actually sent the events)
1. We would also save the fact we called ReconnectApp in a class variable in the Auth class and skip the behavior on step 3 by checking this variable

Thoughts? @danieldoglas

**Comment by danieldoglas** [comment]
I'm OK with this logic, we only want to add the ReconnectApp for the caller.

IF we're doing it to async onyx updates, then I think we might need to send something that says "you should call reconnectApp from scratch"

Maybe it's time to introduce new custom actions we can send to the app?

**Comment by iwiznia** [comment]
> IF we're doing it to async onyx updates, 

We are not, since we don't have a clientUpdateID there

**Comment by danieldoglas** [comment]
how are we dealing with cases where we can't find a previousUpdateID (so no updates at all for them) for an account that is receiving an async update?

**Comment by iwiznia** [comment]
Yesterday I thought about it and thought it was a non issue, but I don't know how I convinced myself of that 😂 

I think there's 2 scenarios, both of them happen when we are in the `GetMissingOnyxMessages` flow:
1. We find a previousUpdateID for you. I think there's no issue here. When you receive it either you apply it or if you don't have the previousUpdateID, call `GetMissingOnyxMessages` which will either download the missing updates or do a full reconnect if we don't have them
2. We don't find a previousUpdateID and thus return -1. In this case we would have to run the same logic described in [step 4](https://github.com/Expensify/App/issues/47582#issuecomment-2329615807) but with the main difference that we would need to track if we run that logic for each user in that same class. We would do that [here](https://github.com/Expensify/Web-Expensify/blob/a37d0d4408ac688fc81bc62d782938200e1dd140/script/bwm/SendFetchableOnyxUpdates.php#L42)

Does that make sense?

**Comment by iwiznia** [comment]
Good point! That makes total sense, a ReconnectApp call can be huge and the users might not even have the app/web open. 

But if we do that, wouldn't it make more sense to use that same onyx operation for the current user and simplify this whole thing? I think it would, because that way we would only have one way of handling this for both cases. Also while we could do what I described above for the current user and avoid the extra network roundtrip, this flow is basically the same as `you are missing updates and need to do another call` that we already have.

**Comment by iwiznia** [comment]
I just realized that a new onyx operation is not the right call. Calling an API command to do a full reconnect is not an onyx operation at all. Instead, we can use a new pusher event. Summarizing the updated solution that solves the problem for both current user and others:

1. In auth, we will pass `clientUpdateID` to `getPreviousUpdateID` [here](https://github.com/Expensify/Auth/blob/e8671e588c5b6182fd31be948081d47e94e7a23b/auth/lib/OnyxUpdates.cpp#L210)
1. At the beginning of `getPreviousUpdateID` we will check if `clientUpdateID` is in the DB, if it is not we will return `0` (same as we do when we find no updates)
1. In Auth class [here](https://github.com/Expensify/Web-Expensify/blob/918cb6a289b71a8116333b5ffb538bb4e64e9fe2/lib/Auth.php#L571) if the response has `accounts.X.lastUpdateID` and `previousUpdateID` is `0`, we will send a new pusher event `appReload`
1. We would also save the fact we called queued this update in a class variable in the Auth class so we can avoid sending 2 events to the same user
1. In app, we will subscribe to this new event like we do [here](https://github.com/Expensify/App/blob/056986b2d48da6bcd09b5965537f826a9dea4b89/src/libs/actions/User.ts#L808)
1. And call App action `reconnectApp`

**Comment by danieldoglas** [comment]
I think this makes sense. I'm just not fully sold on adding a new event/event subscription.

**Comment by danieldoglas** [comment]
After talking to ioni, I agree we can create a new event.

**Comment by iwiznia** [comment]
Working on this. I have the PRs ready above. I need to test the other users case.

**Comment by iwiznia** [comment]
Sent all PRs for review

**Comment by iwiznia** [comment]
This was done way back
