### ISSUE TITLE
Ensure previousUpdateID is returned when it is the same as the clientUpdateID received

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#47581]
Context https://expensify.slack.com/archives/C03TQ48KC/p1723826918927409

# Problem

When the client passes a clientUpdateID, we use it to filter all updates > to it, but that means that if clientUpdateID was the last update you got, then we don't return previousUpdateID.

# Solution

Change `OnyxUpdates::getPreviousUpdateID`'s query to do `>= minUpdateID` (instead of `>`)

**Comment by muttmuure** [comment]
Nice find!
