### ISSUE TITLE
[$250] Report fields - No "0 selected" button and Add value button is present in selection mode

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47585]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Categories.
3. Long tap on any category > Select.
4. Unselect the category.
5. Note that it shows the disabled "0 selected" button and no Add category button.
6. Go to Report fields.
7. Tap Add field > Select list from Type.
8. Tap List values.
9. Add a few list values.
10. Long press on any list value > Select.
11. Unselect the list value.
12. Note that it does not show the disabled "0 selected" button and it shows Add value button in selection mode.

## Expected Result:
In Step 12, in selection mode, app will show the disabled "0 selected" button and there will be no Add value button (same behavior in Categories page).

## Actual Result:
In Step 12, app does not show the disabled "0 selected" button and there is Add value button in selection mode.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1b172e67-677b-4ba4-816d-c6c1f7b9ff3c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121e393fbf4e04d8c</li>
        <li>Upwork Job ID: 1828744549312213237</li>
        <li>Last Price Increase: 2024-09-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment]
Can we submit proposals for the issues without the 'Help wanted' tag? I thought proposals were only for tagged issues. 
Can anyone please clarify. Thanks.

**Comment by Shahidullah-Muffakir** [comment]
Can we submit proposals without the "Help wanted" tag? I thought proposals were only for tagged issues. Also, if proposals are submitted before and after the "Help wanted" tag is added, which proposal is considered if both solutions are correct? 
Can anyone clarify. Thanks.

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by trjExpensify** [comment]
Report field configuration was added in #wave-control, moving.

**Comment by IuliiaHerets** [comment]
@daledah The Issue not reproducing now

https://github.com/user-attachments/assets/cfa4409d-f1d8-4aa0-9213-d27be57741a4

**Comment by trjExpensify** [comment]
Closing!
