### ISSUE TITLE
Workspace name isn't showing up in the To column on Expenses page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47609]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723816743269129

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense to any workspace
3. Click on the search and observe the `To` column 
## Expected Result:
Workspace name and avatar populated  in `To` column on the expenses page
## Actual Result:
Workspace name and avatar not populated and only fall back avatar populated
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-08-16 at 09 59 19@2x](https://github.com/user-attachments/assets/bde0ee5e-126d-4167-9f75-ffe9780df6e6)
![CleanShot 2024-08-16 at 09 58 21@2x](https://github.com/user-attachments/assets/77a5c338-9687-4dcc-9566-c6c9d99ad582)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
cc @luacmartins

**Comment by luacmartins** [comment]
This PR should fix the issue - https://github.com/Expensify/Auth/pull/12047

**Comment by luacmartins** [comment]
This is done
