### ISSUE TITLE
[HOLD for payment 2024-08-26] Workspace switcher - Huge gap between "Create a workspace" modal and "Workspaces" title

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has no workspace.

1. Go to staging.new.expensify.com
2. Open workspace switcher.

## Expected Result:
"Create a workspace" modal should be right below the "Workspaces" title (production behavior).

## Actual Result:
There is huge gap between "Create a workspace" modal and "Workspaces" title.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1440" alt="Bug6574871_1723923186190!Screenshot_2024-08-18_at_03 30 12" src="https://github.com/user-attachments/assets/760fcd7f-b2a1-45a1-b6a0-5a412cd8aedf">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @wildan-m</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by etCoderDysto** [comment]
It might be caused by https://github.com/Expensify/App/pull/47527

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The logic in this render might be incorrect:

https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/SelectionList/BaseSelectionList.tsx#L690-L695

headerMessage value should be mandatory to show the component

### What changes do you think we should make in order to solve the problem?

Change the logic to
```tsx
{(
    ((!isLoadingNewOptions || headerMessage !== translate('common.noResultsFound')) ||
    (flattenedSections.allOptions.length === 0 && !showLoadingPlaceholder)) &&
    !!headerMessage
) && (
    <View style={headerMessageStyle ?? [styles.ph5, styles.pb5]}>
        <Text style={[styles.textLabel, styles.colorMuted, styles.minHeight5]}>
            {headerMessage}
        </Text>
    </View>
)}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by luacmartins** [comment]
@wildan-m are you available to work on a fix?

**Comment by wildan-m** [comment]
@luacmartins sure

**Comment by wildan-m** [comment]
@luacmartins the [PR](https://github.com/Expensify/App/pull/47634) is ready.

**Comment by wildan-m** [comment]
I think we don't need to create regression test, it's not directly related to any flow

**Comment by wildan-m** [comment]
@luacmartins @abekkala bump for payment

**Comment by wildan-m** [comment]
@luacmartins bump https://github.com/Expensify/App/issues/47601#issuecomment-2311805942

**Comment by luacmartins** [comment]
Seems like I closed this issue without payment 😬 Reopening so we can process it @abekkala

**Comment by abekkala** [comment]
### PAYMENT SUMMARY

- Fix @wildan-m [$250] [OFFER](https://www.upwork.com/nx/wm/offer/103846609)
- PR Review: internal @luacmartins

**Comment by wildan-m** [comment]
@abekkala thanks, accepted the offer

**Comment by abekkala** [comment]
@wildan-m payment sent and contract ended - thank you! 🎉
