### ISSUE TITLE
[$250] Workspace - Expense report is not visible in LHN and no Approve button for approver

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47600]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2990379
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: workspace with added employee and approver members.

1. Employee: submit 2 expenses to the workspace
2. Approver: navigate to the employee workspace chat
3. Approver: open expense report and click > Approve

## Expected Result:
Approver: Expense report appears in LHN. Approve button is in the header of expense report.

## Actual Result:
Approver: Expense report is not visible in LHN. Expense report can be opened thru Find feature,
No Approve button is in the header of expense report.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/420747d3-0807-4b28-8f26-6e25f95f743a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c7ebea46465efc4</li>
        <li>Upwork Job ID: 1826215846072487521</li>
        <li>Last Price Increase: 2024-09-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ardent-dev** [comment]
Hi all, I wasn't able to reproduce this one on dev or staging

**Comment by jayeshmangwani** [comment]
@IuliiaHerets I tested the flow, and I can see the Approve button for the approver. Are there any special prerequisites for testing the flow?
cc: @miljakljajic 
<img width="1142" alt="Screenshot 2024-08-22 at 16 57 49" src="https://github.com/user-attachments/assets/27632ad1-3c13-401b-97ed-a7435e78e921">

**Comment by IuliiaHerets** [comment]
@jayeshmangwani QA team can still reproduce with these steps:

1. 3 accounts: admin (workspace owner), employee (expense sender) and approver
2. Admin creates a workspace
3. Admin invites an employee and approver (2 users)
4. Admin enabled WS workflow and set the approver role to the 3rd user (Approver)
5. Employee send 2 expenses to the WS chat
6. Approver opens Expense report chat and has to approve requests

Actual: NO Approve button for approver user and admin either

https://github.com/user-attachments/assets/a7edde89-ebac-4671-ba38-bcebb3579a63

**Comment by jayeshmangwani** [comment]
[Bumped in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1724831640127419)

**Comment by jayeshmangwani** [comment]
We're Waiting on proposals here, No Proposals yet

**Comment by jayeshmangwani** [comment]
[Same as above](https://github.com/Expensify/App/issues/47600#issuecomment-2323215527)

**Comment by trjExpensify** [comment]
I can't repro this on staging. The steps need to be more detailed and precise if there's specific scenarios to repro it. 

https://github.com/user-attachments/assets/099d2bdf-33e8-4125-8605-4a324bdc0605

**Comment by miljakljajic** [comment]
I'll retest this today with these steps: https://github.com/Expensify/App/issues/47600#issuecomment-2305213475

**Comment by jayeshmangwani** [comment]
Not overdue; we are awaiting proposals and [need clear steps](https://github.com/Expensify/App/issues/47600#issuecomment-2342418100) to reproduce this issue

**Comment by jayeshmangwani** [comment]
I have tested this today again but yet I am not able to reproduce this issue, @miljakljajic  please let us know if you can test with above steps

**Comment by m-natarajan** [comment]
Not able to reproduce now.

Uploading approve button.mp4…

**Comment by miljakljajic** [comment]
Thank you @m-natarajan - I think we can close.
