### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] [P2P Distance] Distance rate - Error when selecting distance rate that no longer has tax rate

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47613]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Track tax is enabled.
- Create a Distance rate X that has Tax rate and Tax reclaimable on.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes.
3. Delete tha tax rate that is assigned to Distance rate X from the precondition.
4. Go to workspace chat.
5. Submit a distance expense with another distance rate that is not Distance rate X.
6. Go to transaction thread.
7. Click Rate.
8. Select Distance rate X.

## Expected Result:
App will not throw error when selecting a distance rate that no longer has tax rate (tax rate is deleted after it is assigned to distance rate).

## Actual Result:
App throws error when selecting a distance rate that no longer has tax rate.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0d7b785e-09ac-4256-9f22-019b2a42fb9f

---

https://github.com/Expensify/App/issues/47613#issuecomment-2307640614

On NewDot in the workspace settings, I propose this change to make it clearer that the Tax rate and Tax reclaimable on set on a distance rate are interlinked:

Don’t show the Tax reclaimable on field until a Tax rate is selected.
Note: This would be similar to how we show certain fields in settings after a selection that comes before it, i.e monthly for scheduled submit reveals a Date field etc).

If the Tax rate being used on the distance rate is deleted in Taxes, clear both the Tax rate and Tax reclaimable on values. We would then also hide the Tax reclaimable on field again as Tax rate is empty.
Note: This would prevent an “unexpected error” from occurring, as you can’t get into a situation where there’s a Tax reclaimable on value without a Tax rate selected.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01def12cd4fe837196</li>
        <li>Upwork Job ID: 1828100234986953227</li>
        <li>Last Price Increase: 2024-08-26</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103922844</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment]
I feel like it should show an error, no? Going to discuss in Slack.

**Comment by OfstadC** [comment]
[Slack discussion ongoing ](https://expensify.slack.com/archives/C036QM0SLJK/p1724158952512049)

**Comment by OfstadC** [comment]
@trjExpensify Could you confirm expected behavior here? I don't have the tax option on Distance rates in NewDot 🤔

**Comment by trjExpensify** [comment]
Adding @MonilBhavsar here per the thread.

**Comment by trjExpensify** [comment]
On NewDot in the workspace settings, I propose this change to make it clearer that the `Tax rate` and `Tax reclaimable on` set on a distance rate are interlinked:

- Don’t show the `Tax reclaimable on` field until a `Tax rate` is selected.

Note: This would be similar to how we show certain fields in settings after a selection that comes before it, i.e monthly for scheduled submit reveals a Date field etc).

- If the `Tax rate` being used on the distance rate is deleted in `Taxes`, clear both the `Tax rate` and `Tax reclaimable on` values. We would then also hide the `Tax reclaimable on` field again as `Tax rate` is empty. 

Note: This would prevent an “unexpected error” from occurring, as you can’t get into a situation where there’s a Tax reclaimable on value without a Tax rate selected.

**Comment by MonilBhavsar** [comment]
@daledah if you want to update your proposal based on this^

**Comment by MonilBhavsar** [comment]
@DylanDylann could you please take a look at the proposal based on this expected outcome https://github.com/Expensify/App/issues/47613#issuecomment-2307640614
bas

**Comment by DylanDylann** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/47613#issuecomment-2309719040) looks good to me. I see some minor problems in your implementation. However the detailed implementation will be discussed more in the PR phase.

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment]
Waiting for @MonilBhavsar to give the final assignment

**Comment by DylanDylann** [comment]
@MonilBhavsar Bump on the above comment

**Comment by MonilBhavsar** [comment]
Sorry for missing this out.
Yep the proposal partially fixes the issue.
It is missing details to fix following part of the issue - 

> Don’t show the Tax reclaimable on field until a Tax rate is selected.

and also, if we delete the tax rate, we need to hide the tax reclaimable field. cc @daledah

**Comment by DylanDylann** [comment]
Not overdue. @MonilBhavsar Please recheck this one

**Comment by MonilBhavsar** [comment]
Sounds good 👍 Thanks for clarifying

**Comment by MonilBhavsar** [comment]
@trjExpensify a quick question here. If user deletes a tax rate associated with distance rate, should we display an error/confirmation if they really want to delete it and deleting it would also clear tax rate from distance rate, or we should delete it without any notification

**Comment by DylanDylann** [comment]
Update: Waiting for BE change from @MonilBhavsar

**Comment by MonilBhavsar** [comment]
Submitted PR for review. It is expected to be live on staging early next week

**Comment by MonilBhavsar** [comment]
App PR is merged!

**Comment by OfstadC** [comment]
@DylanDylann Could you please complete the BZ checklist? Thanks! 😃

**Comment by DylanDylann** [comment]
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
Precondition:
- Track tax is enabled.
- Create a Distance rate X that has Tax rate and Tax reclaimable on.

1. Go to workspace settings > Taxes
2. Delete the tax rate that is assigned to Distance Rate X from the precondition
3. Go to the distance rate page
4. Select Distance rate X
5. Verify that: the tax rate is empty and Tax reclaimable on is hidden


Do we agree 👍 or 👎

**Comment by OfstadC** [comment]
## Payment Summary

- @DylanDylann paid $250 via Upwork
- @daledah offer sent [here](https://www.upwork.com/nx/wm/offer/104589618) - please accept so I can issue payment😃 


Had to create new job post [here](https://www.upwork.com/ab/applicants/1849810178249962979/job-details)

**Comment by OfstadC** [comment]
@daledah please accept [offer](https://www.upwork.com/nx/wm/offer/104589618) so I can issue payment. Thank you!

**Comment by OfstadC** [comment]
Paid - closing issue. Thanks everyone!
