### ISSUE TITLE
Distance rate - Amount is negative briefly after changing rate of track distance expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47614]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has at least two distance rates.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click + > Track expense > Distance.
4. Submit a track distance expense.
5. Go to transaction thread.
6. Click Rate.
7. Select a different rate.

## Expected Result:
Amount will not be negative after changing distance rate of track distance expense.

## Actual Result:
Amount is negative briefly after changing distance rate of track distance expense.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/77ae9b27-6c4a-4f93-b4f7-bc9e23a66b27

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
Ok, I'll add this to my test list.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate this one. 

--- 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!
