### ISSUE TITLE
[Performance] WebWorker Demo (to improve search performance)

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#47627]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
e.g. memory consumption, storage read/write times, React native bridge concerns, inefficient React component rendering, etc.

Search for a large number of pD + reports can be very slow. 

## What is the impact of this on end-users?

A customer on the web app has ~1 500 Reports and ~16 000 Personal Details and [performing one search operation took ~ 10 seconds](https://github.com/Expensify/App/issues/46591), blocking the main thread completely.

## List any benchmarks that show the severity of the issue

Search of customers data set took 299.97ms now takes 0.49ms. Thats 600x faster.

## Proposed solution (if any)

See proposal in thread: https://expensify.slack.com/archives/C05LX9D6E07/p1723454316012939?thread_ts=1723209631.007999&cid=C05LX9D6E07

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by chrispader** [comment]
Hey, i'm going to work on this in the next days! :)

**Comment by danieldoglas** [comment]
Closing this in favor of https://github.com/Expensify/App/issues/46591
