### ISSUE TITLE
[$250] Attachment - White background briefly appears before the PFD is opened

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47623]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any account
3. Open any 1:1 chat
4. Send a PDF as attachment
5. Open the PDF

## Expected Result:
The PDF should open without the white background.

## Actual Result:
White background briefly appears before the PFD is opened. It can also be seen when sending a PDF.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/65bfdfd0-bd3d-4fc3-97aa-bed9865b3f50

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dd0e60fab4c06f5e</li>
        <li>Upwork Job ID: 1825633598084074106</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment]
I was able to recreate as well:

![2024-08-19_15-37-55 (1)](https://github.com/user-attachments/assets/d42f1a96-f099-4b45-90c2-bf7669ea1261)

**Comment by CortneyOfstad** [comment]
@DylanDylann Hello! We have a proposal [here](https://github.com/Expensify/App/issues/47623#issuecomment-2295971078) when you have a chance — thanks!

**Comment by DylanDylann** [comment]
I can't reproduce this bug. I only see the loading spinner is displayed without the white background

https://github.com/user-attachments/assets/d1fb0192-b91f-4310-b5de-aa4c25bbdc6c

@Krishna2323 Could you try again on the latest main?

**Comment by DylanDylann** [comment]
@Krishna2323 Ahh thanks. Why does this bug only reproduce with some PDF files? As your RCA, I think this should be reproduced on every PDF files

**Comment by DylanDylann** [comment]
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/47623#issuecomment-2295971078) looks good to me 

🎀 👀 🎀 C+ reviewed

**Comment by jasperhuangg** [comment]
Don't think we need to fix this 😆 seems like a pretty minor display bug that has no effect on app usage.
