### ISSUE TITLE
Web - Unable to dismiss Switch to Expensify Classic RHP via ESC key after refreshing the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47648]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings
3. Click Switch to Expensify Classic
4. Dismiss the RHP via ESC key
5. Note that the RHP can be dismissed via ESC key
6. Refresh the page
7. Click Switch to Expensify Classic
8. Press ESC key

## Expected Result:
Switch to Expensify Classic RHP can be dismissed via ESC key after refreshing the page

## Actual Result:
Switch to Expensify Classic RHP cannot be dismissed via ESC key after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/62f146f5-a6e8-4cb5-bb7a-1d4ea849e6ff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
Same issue as https://github.com/Expensify/App/issues/46915

**Comment by strepanier03** [comment]
Closing in favor of #46915 which is two weeks old.
