### ISSUE TITLE
[HOLD for payment 2024-08-29] iOS - Expense report jumps when returning from transaction thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47656]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47096
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit three expenses with receipt.
4. Tap on the expense preview to go to expense report.
5. Tap on the first expense preview to go to transaction thread.
6. Tap on the back button.

## Expected Result:
The expense report will not jump when returning from transaction thread.

## Actual Result:
The expense report jumps when returning from transaction thread.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d957ea6a-5021-4185-bf67-36e41d6e3dea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by arosiclair** [comment]
> This is very minor issue, possibly from a PR #47096 @kirillzyusko and me worked on, i dont think this needs be a deployblocker we can work on it as a follow up.

Agreed this is super minor. Removing the label and assigning you @ishpaul777

**Comment by arosiclair** [comment]
Also assigning @marcochavezf since you were managing the bug for https://github.com/Expensify/App/pull/47096

**Comment by dylanexpensify** [comment]
@ishpaul777 we need @kirillzyusko to comment here to do so, once done - we will assign

**Comment by neil-marcellini** [comment]
@IuliiaHerets @marcochavezf the revert is done, would you please test on staging and confirm it's fixed?

**Comment by IuliiaHerets** [comment]
@neil-marcellini Issue was fixed, not repro already

https://github.com/user-attachments/assets/4b91d5fd-fb00-4121-bc99-de6873360297

**Comment by kirillzyusko** [comment]
> we need @kirillzyusko to comment here to do so

Commenting to be assigned 👋

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @ishpaul777 $250 via Upwork

Please apply/request!

**Comment by marcochavezf** [comment]
Closing this one in favor of https://github.com/Expensify/App/issues/44514
