### ISSUE TITLE
We removed the link to Classic in the Concierge weekly summary for outstanding reports

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#47658]
It looks like we removed the link to Classic in the Concierge weekly summary for outstanding reports, which means the CTA is sending the user to the wrong platform to approve the reports. 

I reported the [issue here](https://expensify.slack.com/archives/C041MSTR8J1/p1724080669650419). In that thread, you can see where we send a message that links to Classic in the concierge tool, but when the user actually got it, it looks like the link didn't come through pointing them to Classic. This creates confusion because they then go to NewDot where they can't approve the report. 

![image](https://github.com/user-attachments/assets/e56ecf26-0492-47fd-a2c5-260091f838b6)

**Comment by tgolen** [comment]
@chiragsalian found that the bug happens here: https://github.com/Expensify/Web-Expensify/blob/60205bce72c1f6c9976f04e9ea4094ce29175f69/lib/Notification/Report/CustomSubjectComment.php#L34

The regex drops everything after the `<br />\n`... now, for some reason, we have to figure out how the string from [here](https://github.com/Expensify/Web-Expensify/blob/60205bce72c1f6c9976f04e9ea4094ce29175f69/lib/UserSummaryTextGenerator.php#L80) goes from `\n\n` to `<br />\n`.

**Comment by tgolen** [comment]
@cristipaval @iwiznia I'm wondering if you have another thoughts about how this is happening? There is more context about this in the original slack thread, so you might try reading that as well. https://expensify.slack.com/archives/C041MSTR8J1/p1724080669650419

@cristipaval I'm pinging you because it looks like you added the regex that leads to this issue

To illustrate the problem a smaller scale, I did this in psysh and it seems to demonstrate it:

```
> $msg = "<h1>custom subject</h1>body before<br />\nbody after";
= """
  <h1>custom subject</h1>body before<br />\n
  body after
  """

> preg_match('/<h1>(.+?)<\/h1>(.*)/', $msg, $match);
= 1

> print_r($match);
Array
(
    [0] => <h1>custom subject</h1>body before<br />
    [1] => custom subject
    [2] => body before<br />
)
= true

>
```

You can see that `$match[2]` stripped everything after the `<br />`

**Comment by cristipaval** [comment]
I think you are right, [CustomSubjectComment::getCommentBlock](https://github.com/Expensify/Web-Expensify/blob/035a9d38b2cef783d6bd782c4f8917029c16a800/lib/Notification/Report/CustomSubjectComment.php#L31-L40) function doesn't work as expected and partially strips text from the email body.

**Comment by tgolen** [comment]
The `s` modifier looks like it will do the trick! Thanks for confirming.

**Comment by tgolen** [comment]
# Weekly Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/43194) was deployed to production a few days ago

### Next Steps
- @tgolen Close this issue

#### ETA
- Today, Aug 30
