### ISSUE TITLE
Web - Account Settings-'Domain Card tests - DO NOT DELETE' is not an option

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4859388
**Email or phone of affected tester (no customers):** tester@applausecard.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. In OldDot, login with [tester@applausecard.expensifail.com](mailto:tester@applausecard.expensifail.com)
2. Navigate to domain settings
3. In company cards - click on import card
4. Select Discover Bank
5. Enter username Expensifydemo / Password: anything
6. After the card has been imported - click on the settings tab in the discover card
7. Select the "Domain Card tests - DO NOT DELETE" as the preferred workspace

## Expected Result:
The Domain Card Tests - DO NOT DELETE workspace is available for selection as the preferred workspace.

## Actual Result:
The Domain Card Tests - DO NOT DELETE workspace is not displayed in the 'Preferred workspace' dropdown list.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bf9b045d-0bf1-458e-926e-3e1efd33f14a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment]
Can't reproduce. 
<img width="1207" alt="image" src="https://github.com/user-attachments/assets/198180da-5c5e-4ad8-a37c-86d17c7333eb">

Remember: you need to enable Scheduled Submit for options to appear in that preferred workspace dropdown
