### ISSUE TITLE
Hybrid- Open app called back to back on bad wifi network and app never loads

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47667]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1724045384113909

## Action Performed:

1. Be on a bad WiFi network
2. Open the app

## Expected Result:
App loads quickly

## Actual Result:
Hybrid app never loads and not remembering the session/state and triggering OpenApp 

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2d4af855-7c2f-4522-8fe8-833b5ed22690

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mateuuszzzzz** [comment]
Hi! I'll focus on this issue

**Comment by mateuuszzzzz** [comment]
I should finish HybridApp refactor today and I'll investigate this problem more thoroughly 👍

**Comment by muttmuure** [comment]
Great!

**Comment by mateuuszzzzz** [comment]
I believe our refactor should address this issue as well by removing some API calls that were previously made on OldDot before transitioning to NewDot. I’ll be able to provide more details tomorrow after testing the app with the network conditioner.

**Comment by mateuuszzzzz** [comment]
So it looks like our refactor fixes this. We have some minor issues related to refactor, but we're addressing them.

**Comment by muttmuure** [comment]
@mateuuszzzzz how is this coming along?

**Comment by puneetlath** [comment]
@mateuuszzzzz just checking in. How's this going?

**Comment by mateuuszzzzz** [comment]
Hi! Sorry for the delay I'm OOO.

Refactor that we've merged recently fixed this problem as well

**Comment by trjExpensify** [comment]
Great stuff, let's close it out.
