### ISSUE TITLE
Web - Sign in – Concierge chat long loading when log in with new account via Magic link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47666]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4871273
**Email or phone of affected tester (no customers):** applausetester+jp_319824@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. In Sign in page enter new Expensify email
3. Open email and copy Magic link
4. Change it to staging and paste in new tab
5. Navigate back to previous tab

## Expected Result:
Concierge chat loaded

## Actual Result:
Concierge chat long loading

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/115ecfed-3fe4-415c-a002-83c3a58de548

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment]
huh - this is an odd one but pretty minor, closing for now
