### ISSUE TITLE
iOS-chat-Composer is hidden behind keyboard after copying a message on iOS 15

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47679]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4873332
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to conversation with existing history
3. Tap on Compose box to open keyboard
4. Hold a message and copy it

## Expected Result:
Message should be copied and composer should be visible above keyboard

## Actual Result:
Message is copied but composer is hidden behind keyboard. The keyboard can't be dismissed by swiping down.
Issue is only reproducible with older devices. Reproduced with iPhone 7/iOS 15.8.2 and iPhone 8/iOS 15.7.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e8370c26-81da-4b36-8df4-1d6eb0cff2f2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
Production - not reproduced

https://github.com/user-attachments/assets/32ad73cb-cedf-4c76-95bc-5ddb7b2cbe3e

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by techievivek** [comment]
Seems like this is coming from here https://github.com/Expensify/App/pull/47096

**Comment by neil-marcellini** [comment]
@IuliiaHerets @techievivek the revert is done, would you please test on staging and confirm it's fixed?

**Comment by m-natarajan** [comment]
Issue is not reproducible on build v9. 0. 22-7

https://github.com/user-attachments/assets/3d26bf88-c9ac-411d-a654-0214cfdfa5eb

**Comment by techievivek** [comment]
Going to close this now. Thanks for confirming.
