### ISSUE TITLE
Search - Status bar scrolls back after selecting Paid status

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Search.
3. Scroll the status bar to the right.
4. Tap Paid.

## Expected Result:
The status bar will not scroll back as this will block the view that Paid is selected (especially on a small/narrow screen).

## Actual Result:
The status bar scrolls back when Paid status is selected, causing the selected status only partially visible.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/361d2dc9-48e4-404e-a769-278f1c368c23

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to  #wave-collect - Release 1

**Comment by chiragsalian** [comment]
Closing issue since it will be addressed as a follow up.
