### ISSUE TITLE
[$250] Group chat-Member invited, made admin & removed in offline is showed on returning online.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4872013
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- start chat -- select a user
3. Create a group
4. Tap header -- member
5. Go offline
6. Invite a member
7. Make him admin by long pressing the member and selecting make admin
8. Then remove the same user by long pressing the member and selecting remove member
9. Go online
10. Tap back

## Expected Result:
In group chat, member removed in offline must not be showed on returning online.

## Actual Result:
In group chat, member invited, made admin & removed in offline is showed on returning online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/72b64dda-6397-4dcb-bd70-a922cced67e4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e13003200e6f595</li>
        <li>Upwork Job ID: 1825933817898137464</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103626792</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment]
What happened with this issue @dominictb @aimane-chnaif? Did we finish it?

**Comment by puneetlath** [comment]
Got it. I've paid @dominictb. 

@aimane-chnaif can you complete the checklist?

**Comment by puneetlath** [comment]
Payment summary: 
- C - @dominictb - $250 - paid via Upwork
- C+ - @aimane-chnaif - $250 - to be paid via NewDot

Thanks y'all!

**Comment by puneetlath** [comment]
Ah ok got it. Offer is here: https://www.upwork.com/nx/wm/offer/104341792. Please ping me on this issue when you've accepted.

**Comment by puneetlath** [comment]
Paid!
