### ISSUE TITLE
[$250] [Navigation Bug]: The Back button in the confirm page close RHP

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#47697]
Coming from [this project](https://github.com/Expensify/Expensify/issues/396071), we have this follow-up polish issue we need to complete where the back button in the confirm page closes the RHP. More details [here](https://expensify.slack.com/archives/C036QM0SLJK/p1723203651870589).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134a56cd991934297</li>
        <li>Upwork Job ID: 1825862477363321355</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by dylanexpensify** [comment]
cc @blazejkustra

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
Before:

> Bug: The Back button in the confirm page should navigate back to approver selection page ([link](https://github.com/Expensify/App/pull/46798#issuecomment-2276361779))

https://github.com/user-attachments/assets/02cf57e8-3039-47d1-890d-9863439f11bd

After:
Going back on `create approval screen` navigates back to the first approver screen as shown on the video.

https://github.com/user-attachments/assets/54b5baeb-91b4-47b0-9401-46242344e43f

Before I proceed with implementation I'd like to ask about your input @JmillsExpensify @tgolen @Expensify/design - do you prefer this updated approach?

**Comment by Lalarukh-khan** [comment]
I have also applied on Upwork. Can I get an opportunity to get it done?

**Comment by Lalarukh-khan** [comment]
Contributor details
Your Expensify account email: lalarukhkhan179@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01152db88584b3187c

**Comment by belawalumer** [comment]
Contributor details
Your Expensify account email: belawalumer4@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f81b79aedaff801c

**Comment by kanha55** [comment]
hello
Where I can submit the proposals on GitHub?

**Comment by kanha55** [comment]
I am submitting my proposal 
Step 1: Understand the Issue

    The back button on the confirm page should navigate to the previous page but instead closes the Right-Hand Panel (RHP).

Step 2: Check the Code

    Identify the specific component responsible for the back button functionality within the confirm page.
    Analyze the navigation logic, focusing on the current behavior of the back button.

Step 3: Review Approvers Page

    Investigate how the navigation works on the Approvers page (RHP) since it's working correctly.
    Apply the same logic or implementation to the confirm page (RHP).

Step 4: Fix the Navigation on confirm page

    Modify the back button's action on the confirm page to ensure it correctly navigates to the approver selection page rather than closing the RHP.

Step 5: Test the Fix

    Test the functionality by navigating through the pages to confirm that the issue is resolved and the back button behaves as expected.

Step 6: Write Test Cases

    Write the necessary test cases to cover the changes made to the back button functionality.

Step 7: Create a Pull Request

    Once the fix is confirmed, submit a pull request with a detailed explanation of the changes, including the logic behind the fix and the tests you've written.

**Comment by blazejkustra** [comment]
@dylanexpensify Could you remove `Help wanted` tag? 😅

**Comment by JmillsExpensify** [comment]
@blazejkustra yes, we prefer the updated approach!

**Comment by DylanDylann** [comment]
@tylerkaraszewski  Please help process the payment for me. Thanks

**Comment by tylerkaraszewski** [comment]
Not sure why @dylanexpensify was unassigned, he should be able to do that.

**Comment by DylanDylann** [comment]
@DylanDylann The Upwork job is no longer available, could you create a new job and send the offer to my profile here? https://www.upwork.com/freelancers/~010c6310ab55f3d17d

Thanks

**Comment by dylanexpensify** [comment]
@DylanDylann yes!

**Comment by dylanexpensify** [comment]
@DylanDylann sent invite!

**Comment by DylanDylann** [comment]
@dylanexpensify thanks, I applied to the job

**Comment by dylanexpensify** [comment]
@DylanDylann sent!

**Comment by DylanDylann** [comment]
@DylanDylann accepted!

**Comment by DylanDylann** [comment]
@dylanexpensify accepted!

**Comment by dylanexpensify** [comment]
Done!
