### ISSUE TITLE
[Advanced Approval Workflows] Update the hint text to be simpler

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#47699]
Coming from [this project](https://github.com/Expensify/Expensify/issues/396071), we have this follow-up polish issue we need to complete where we update the hint text to be simpler. More details [here](https://github.com/Expensify/App/pull/46798#discussion_r1716612421).

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by dylanexpensify** [comment]
cc @blazejkustra

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by dylanexpensify** [comment]
Hi @blazejkustra! It's all yours!

**Comment by blazejkustra** [comment]
@JmillsExpensify @tgolen Please check out [this](https://github.com/Expensify/App/pull/46798#discussion_r1716526147) thread, and let me know what do you think. Should we make the message more generic or you have another idea in mind, thanks!

**Comment by tgolen** [comment]
I think the copy you proposed looks good to me.

**Comment by JmillsExpensify** [comment]
Yes, that looks good to me as well. cc @jamesdeanexpensify this is the copy if you have any alt suggestions. 

> dylandylan9112+9366@gmail.com is already used in a separate workflow. If you change this approval relationship, all other workflows will be updated.

**Comment by jamesdeanexpensify** [comment]
It looks like we show the email already in the `Second approver` field, so we might not even need to repeat it. So maybe we could tweak it and do:

> This member already belongs to another approval workflow. If you change this approval relationship, all other workflows will be updated.

Just curious though, _how_ will all other workflows be updated? Like, what will change in the others? Maybe we could make it even clearer.

**Comment by JmillsExpensify** [comment]
We previously had a more specific example but we ended up discovering that it's not general enough to work in the breadth of scenarios required.

**Comment by jamesdeanexpensify** [comment]
Understood. Let me know if you think my suggestion works, or we could go even shorter:

> This member already belongs to at least one other approval workflow. Any updates here will reflect there, too.

**Comment by JmillsExpensify** [comment]
That could work! Ultimately I'm not too passionate as nailing this message is hard and will depend on customer feedback.

**Comment by blazejkustra** [comment]
All yours @DylanDylann 

https://github.com/Expensify/App/pull/47860

**Comment by blazejkustra** [comment]
FYI [we landed on these messages and translation](https://expensify.slack.com/archives/C01GTK53T8Q/p1724337079975139?thread_ts=1724319519.286089&cid=C01GTK53T8Q):

**Comment by rlinoz** [comment]
I am pretty sure this has been deployed to prod, @DylanDylann are you due payment here?

**Comment by rlinoz** [comment]
bump @DylanDylann

**Comment by rlinoz** [comment]
@puneetlath I guess this is deployed to prod for a while now, so we just need to issue payment for @DylanDylann

**Comment by puneetlath** [comment]
Offer is here: https://www.upwork.com/nx/wm/offer/104055843

@DylanDylann ping me on this issue when you've accepted.

**Comment by DylanDylann** [comment]
@puneetlath Done it thanks
