### ISSUE TITLE
[Advanced approvals] Update pendingAction/pendingFields when making an action offline (create/edit/remove)

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#47701]
Coming from [this project](https://github.com/Expensify/Expensify/issues/396071), we have this follow-up polish issue we need to complete where we update pendingAction and pendingFields when making an action offline. More details [here](https://github.com/Expensify/App/pull/46798#issuecomment-2285628497).

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by dylanexpensify** [comment]
cc @blazejkustra

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by dylanexpensify** [comment]
Hi @blazejkustra! It's all yours!

**Comment by blazejkustra** [comment]
1. Currently the whole section is greyed out when there are changes in **any** workflow (following offline pattern B), I reckon we want to grey out only these workflows that are affected? 

https://github.com/user-attachments/assets/97ca8b3d-8322-40f7-842a-50fe3af5aeb7

2. How should approval workflows section be displayed when the user is offline, should it be also greyed out?

![image](https://github.com/user-attachments/assets/70e7f5cb-be3d-4d45-88bf-5aa89ae62ec2)

Thoughts @tgolen @JmillsExpensify @DylanDylann?

**Comment by DylanDylann** [comment]
@blazejkustra When users take actions, they could update `submitTo` field or `forwardsTo` field. IMO, If these actions is triggered offline we can add pendingFields in the employee object like this

<img width="248" alt="Screenshot 2024-08-21 at 15 22 10" src="https://github.com/user-attachments/assets/6a2871e3-d5dc-43b3-b657-28726639048f">

```
{
              .....
             pendingFields: {
                submitTo: "UPDATE"
                forwardTo: "UPDATE"
            }
}
```

And then when displaying the approval workflow, for each workflow
- we will grey out "expenses member" if there is at least a member that has pendingFields.submitTo 
- we will grey out "first approver" if there is at least one member from the "expenses member" section that has pendingFields.submitTo
- We will grey out next approvers if the previous approver has pendingFields.forwardTo


@blazejkustra What do you think about this approach?

**Comment by blazejkustra** [comment]
Thank you for the idea of how this could be implemented, this is definietly a way to go 👌 

I think it may be a little overcomplicated, and I'm still not sure how important is it to show exactly what people were changed offline vs grey out the whole workflow. Waiting for input from others 🙇

**Comment by JmillsExpensify** [comment]
>Currently the whole section is greyed out when there are changes in any workflow (following offline pattern B), I reckon we want to grey out only these workflows that are affected?

I tend to agree with you, though I would say this is a low priority. 

> How should approval workflows section be displayed when the user is offline, should it be also greyed out?

Are you asking in general? If so, if a user is offline we don't need to grey the whole section out, we only use the offline patterns to give feedback when changes are made (including changes that can only be made online, so they are blocked offline).

**Comment by DylanDylann** [comment]
@blazejkustra @JmillsExpensify What are we waiting for here?

**Comment by blazejkustra** [comment]
@DylanDylann I'll get to this one tomorrow, sorry 🙇

**Comment by blazejkustra** [comment]
> @blazejkustra When users take actions, they could update `submitTo` field or `forwardsTo` field. IMO, If these actions is triggered offline we can add pendingFields in the employee object like this
> 
> And then when displaying the approval workflow, for each workflow
> 
> * we will grey out "expenses member" if there is at least a member that has pendingFields.submitTo
> * we will grey out "first approver" if there is at least one member from the "expenses member" section that has pendingFields.submitTo
> * We will grey out next approvers if the previous approver has pendingFields.forwardTo
> 
> @blazejkustra What do you think about this approach?

I tried it @DylanDylann here: https://github.com/Expensify/App/pull/48082 and have to say that it sounds better/easier on paper 😢 This approach doesn't work well when removing members - we should grey out "expenses from", but there is no field we can base the logic on. The other thing is that when updating a workflow all members and approvers are sent to the backend (not only people who were updated, but all people involved in the workflow). All in all, I think it creates some weird looking offline states where only part of the workflow is greyed out instead of the whole section:

![image](https://github.com/user-attachments/assets/27c6df9f-7f35-49a6-be5e-ac2b4d5e2020)

Alternative approach is to grey out the whole workflow section in case any person was affected (added/updated/removed), I think this should be easier to code as well. Thoughts @DylanDylann?

**Comment by blazejkustra** [comment]
@DylanDylann I cam up with [this](https://github.com/Expensify/App/pull/48086/files) draft PR, here is a video of how it works with these changes:

https://github.com/user-attachments/assets/1d104483-c111-4583-966c-93ce441a50b5

I'm open for your suggestions, but have in mind this issue has a low priority as Jason mentioned above.

**Comment by DylanDylann** [comment]
@blazejkustra Let's bring this to Slack. We need to confirm the approach before moving forward

**Comment by blazejkustra** [comment]
I moved the discussion to `#wave-control` channel [here](https://swmansion.slack.com/archives/C06ML6X0W9L/p1724847798389739?thread_ts=1724791751.002609&cid=C06ML6X0W9L)

**Comment by blazejkustra** [comment]
@DylanDylann PR is up 👍

**Comment by DylanDylann** [comment]
@youssef-or Could you help process the payment here?

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @DylanDylann $250 via Upwork

Please apply/request!

**Comment by DylanDylann** [comment]
@dylanexpensify I don't see any offer for this issue

**Comment by dylanexpensify** [comment]
Ah automation failed, lemme whip one up!

**Comment by DylanDylann** [comment]
@dylanexpensify Have you got a chance to create the offer? 
My profile on Upwork is https://www.upwork.com/freelancers/~010c6310ab55f3d17d in case you're looking for it.

Thanks 🙏

**Comment by DylanDylann** [comment]
@dylanexpensify Bump on above comment

**Comment by dylanexpensify** [comment]
Done!
