### ISSUE TITLE
[$250]  [Advanced Approval Workflows]: Truncate Expenses From push row

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#47702]
Coming from [this project](https://github.com/Expensify/Expensify/issues/396071), we have this follow-up polish issue we need to complete where we truncate the `Expenses from` push row. More details [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1724114136584039?thread_ts=1724093746.434959&cid=C06ML6X0W9L).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e76fcff7757da55</li>
        <li>Upwork Job ID: 1825862491483970170</li>
        <li>Last Price Increase: 2024-10-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by dylanexpensify** [comment]
Hi @blazejkustra! It's all yours!

**Comment by VincentCorleone** [comment]
@dylanexpensify  Hi, I have trouble viewing details. When I open the link, I see this: 
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/f14e7950-c3fd-4ee0-a50d-f2ada357260b">
Could you help?

**Comment by blazejkustra** [comment]
FYI @VincentCorleone this issue isn't external + the channel where it links is private:

![image](https://github.com/user-attachments/assets/50b82d94-53d9-4c64-8115-54570f1a6172)

**Comment by blazejkustra** [comment]
[PR](https://github.com/Expensify/App/pull/47928) is ready for your review @DylanDylann

**Comment by MariaHCD** [comment]
Looks like the PR for this one was merged and deployed 3 weeks ago. Are there any payments required here? Or can we close?

**Comment by DylanDylann** [comment]
@MariaHCD  Please help process the payment for me. Thanks

**Comment by MariaHCD** [comment]
Looks like we need to issue the payment for C+ here.

**Comment by MariaHCD** [comment]
Hey, @zanyrenney! The PR for this was merged and deployed some weeks ago. We just need to issue @DylanDylann payment for C+ review.

**Comment by zanyrenney** [comment]
annoyingly this jobpost is now closed. retrying the automation.

**Comment by zanyrenney** [comment]
https://www.upwork.com/jobs/~021841170467428845891 
@DylanDylann i have invited you to the job!

**Comment by DylanDylann** [comment]
@zanyrenney Thank you, I applied to that job

**Comment by zanyrenney** [comment]
**payment summary**

paid $250 to @DylanDylann for C+ here.
