### ISSUE TITLE
[$250] [Advanced Approval Workflows] Should display empty state when the member list is empty

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#47700]
Coming from [this project](https://github.com/Expensify/Expensify/issues/396071), we have this follow-up polish issue we need to complete where we should display an empty state when the member list is empty. More details [here](https://github.com/Expensify/App/pull/46798#issuecomment-2286274629).
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01040daf30f3152600</li>
        <li>Upwork Job ID: 1825862440438169741</li>
        <li>Last Price Increase: 2024-08-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by dylanexpensify** [comment]
cc @blazejkustra

**Comment by blazejkustra** [comment]
Hey! I’m Błażej Kustra from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by blazejkustra** [comment]
Let's agree with one approach for a case when member list is empty @Expensify/design @JmillsExpensify.

https://github.com/user-attachments/assets/dac271bf-5da7-4d76-b643-72dec96334a5

I like the idea from @dannymcclain [here](https://github.com/Expensify/App/pull/46798#issuecomment-2286274629). But, let's settle on a particular message we want to display.

**Comment by DylanDylann** [comment]
In this comment, @dannymcclain suggested: "Hey, all your members are part of approval workflows already! Right on. Everyone is getting approved. Way to go."

@blazejkustra I think we can confirm with the design team one more time after the implementation on the PR phase

**Comment by JmillsExpensify** [comment]
Yes, I think that should work. For clarity, we're also not going to show a search input in this case correct? Basically since there is nothing to search for. 

As for the message, @jamesdeanexpensify you might want to weigh in on the copy. I think we could probably tweak Danny's suggestion a bit, e.g. "All workspace members belong to an approval workflow. Nice work, everyone is accounted for."

**Comment by JmillsExpensify** [comment]
Love it.

**Comment by blazejkustra** [comment]
All yours @DylanDylann 

https://github.com/Expensify/App/pull/47848

**Comment by DylanDylann** [comment]
@jasperhuangg Please help process the payment for me. Thanks

**Comment by jasperhuangg** [comment]
Strange that no BugZero person was assigned, apologies for the delay @DylanDylann.

@isabelastisser Do you mind processing payment for @DylanDylann and @blazejkustra? It looks like @blazejkustra is owed $250 for implementing the solution to this issue, and @DylanDylann is owed for proposal and PR reviews.

**Comment by DylanDylann** [comment]
@blazejkustra comes from SWM, we only need to process payment for me

**Comment by isabelastisser** [comment]
Reviewing this now.

**Comment by isabelastisser** [comment]
@DylanDylann's offer was sent in Upwork. All set!

**Comment by DylanDylann** [comment]
@isabelastisser Offer accepted, thanks 🙏
