### ISSUE TITLE
[Internal] Research and Set up Firebase for Web

### ISSUE THREAD

**Issue by rinej** [Expensify/App#47707]
**Problem**
Currently we use _react-native-firebase_ for tracking performance issues on mobile. 
According to docs https://rnfirebase.io/platforms the lib doesn't support web platform. It would be beneficial to use firebase to track web performance as well. 

**Solution**
We need to do some reaserch and check if we are able to use the the firebase SDK to use performance tracking on the web. 

We already have Firebase set up for our mobile platforms, and recently we started using it.
And with relatively low effort, we can extend this setup to the web platform.

It allows us to monitor default key metrics (e.g. `firstContentfulPaint` ) and our custom metrics (e.g.  `trie_initialization` )

We can add additional context to the trace, like `userId` or the number of reports, which can be valuable for diagnosing issues or analyzing performance trends.

In practice, this means that we both can use the dashboard to track any potential performance regressions.
While it might feel somewhat similar to Grafana in terms of monitoring capabilities, Firebase is relatively easier to configure—especially since we already have the setup in place for mobile.

Here are some screenshots from firebase console from test project:
<img width="1389" alt="Screenshot 2024-08-22 at 11 24 49" src="https://github.com/user-attachments/assets/28650333-b6fb-47b9-ad42-916c33ac4af3">
<img width="1077" alt="Screenshot 2024-08-21 at 15 23 42" src="https://github.com/user-attachments/assets/89cec9af-2ae3-409c-a125-2de56a7a092f">

<details><summary>Issue Owner</summary>Current Issue Owner: @rinej</details>

**Comment by luacmartins** [comment]
@rinej could you provide some examples of how we're using `react-native-firebase` to track mobile performance issues now?

Could you also please fill in this information:

- Library size: 
- # GitHub stars:
- Last release date:

Thank you!

**Comment by rinej** [comment]
### How we currently use `react-native-firebase` for tracking performance:

**Custom Metrics Tracking:**
We monitor specific custom metrics to gain deeper insights into key functionalities. For example:
- chat_render: Tracks the time taken to render the chat interface.
- load_search_options: Monitors the duration for loading search options.
- switch_report: Measures the time spent switching between reports.

**Detailed Trace Logging:**
We log additional details in each trace, such as `accountId`, the number of `reports`, and the length of `personalDetails`. This helps in identifying performance bottlenecks more easily.

**Network Request Timing:**
We track the time taken for network requests, such as `ReconnectApp` or `OpenApp`, to monitor their performance.

**Crashlytics Integration:**
We use the crashlytics module to help identify the root causes of crashes. (Currently, crashlytics is only available on mobile platforms. For web monitoring, we can use other tools like Sentry or Bugsnag.)

**Flexibility**
As this is a relatively new initiative, we have the flexibility to add or modify metrics as our needs evolve.

Url to firebase console -> https://console.firebase.google.com/u/0/project/expensify-chat/performance/app/android:com.expensify.chat/trends?time=last-thirty-days


### Additional Info:
New package npm url: https://www.npmjs.com/package/firebase

**Library size:**
-  the whole `firebase` package - 24.7 MB (https://www.npmjs.com/package/firebase)
- just the module we need `firebase/performance` -> 615 kB (https://www.npmjs.com/package/@firebase/performance)


**GitHub stars:** 4.8k

**Last release date:** a day ago (22 August)

**Comment by luacmartins** [comment]
Thanks! I'll bring this to Slack tomorrow

**Comment by rinej** [comment]
I created the Draft PR with the project configuration: https://github.com/Expensify/App/pull/47795
We will need someone from Exp to create new Web project in firebase console so we can add the proper config:
```
FIREBASE_WEB_CONFIG: {
        apiKey: 'YOUR_API_KEY',
        authDomain: 'YOUR_AUTH_DOMAIN',
        projectId: 'YOUR_PROJECT_ID',
        storageBucket: 'YOUR_STORAGE_BUCKET',
        messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
        appId: 'YOUR_APP_ID',
        measurementId: 'YOUR_MEASUREMENT_ID',
    },
```

**Comment by luacmartins** [comment]
We have a draft PR

**Comment by rinej** [comment]
The PR is ready for review.  
We will just need someone from the internal team to create new Firebase Project and set the proper environmental variables so we can take it from ENV. More details in the PR -> https://github.com/Expensify/App/pull/47795

**Comment by rinej** [comment]
the issue was resolved in the following ticket: https://github.com/Expensify/App/issues/49443#issuecomment-2361239813
