### ISSUE TITLE
[HOLD for payment 2024-08-29] Update link to fork for react-native-qrcode-svg

### ISSUE THREAD

**Issue by grgia** [Expensify/App#47713]
Part of https://github.com/Expensify/App/issues/47711

Update this [line](https://github.com/Expensify/App/blob/d519981587b065ce96f73ab341d84f9eb17a864c/package.json#L168) to point to `Expensify/react-native-qrcode-svg-old`

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by zanyrenney** [comment]
reapplying bug label for payout as I am going to be OOO until next week!

**Comment by zanyrenney** [comment]
making daily as payout in 3 days! thanks so much @slafortune

**Comment by slafortune** [comment]
@grgia, there really isn't any payment due here, is there?  I see that @kicu is from SM who is reviewing.  Just wanted to make sure I wasn't missing anyone.

**Comment by zanyrenney** [comment]
Closing due to ^
