### ISSUE TITLE
Chat-On entering url text in multi line & applying quote markdown not shown in preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47722]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4874519
**Email or phone of affected tester (no customers):**
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a chat
3. Enter a url eg: tyujhhhhh.com
4. Long press the message sent and select edit comment
5. Enter in multi- line the url text & save it
6. Long press the message and select edit comment
7. Enter a > with a space at the beginning of the message
8. Note markdown is not shown in preview
9. Tap save
10. Note quote markdown is shown

## Expected Result:
On entering url text in multi line & applying quote markdown must be shown in preview.

## Actual Result:
On entering url text in multi line & applying quote markdown not shown in preview.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/264e38d7-ec8c-47fa-8103-254af203c694

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by miljakljajic** [comment]
Going to close this one out - feels like extreme polish
