### ISSUE TITLE
[$250] Invoice - Billable option is disabled after sending invoice with billable option enabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Billable option is set to default to billable on Old Dot
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoice
3. Enter amount and select a participant
4. Select the workspace with the default billable option
5. Send the invoice with billable option enabled
6. Click on the invoice preview twice to go to invoice report

## Expected Result:
Billable option will remain enabled as the invoice is sent with billable option enabled

## Actual Result:
Billable option is disabled in the invoice report when the invoice is sent with billable option enabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2799937a-5567-4188-9636-1d6d5138adc9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ffc1130b4a222fd</li>
        <li>Upwork Job ID: 1828518698402427125</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by c3024** [comment]
@adelekennedy 

This requires changes on backend. So, this should to be `Internal`.

**Comment by adelekennedy** [comment]
@c3024 to [this point](https://github.com/Expensify/App/issues/47732#issuecomment-2322945389) can the frontend work here be done externally?

**Comment by c3024** [comment]
Yes, the front-end can be handled externally, but backend changes must also be made either first or simultaneously to ensure the front-end changes are implemented correctly.

**Comment by adelekennedy** [comment]
@cristipaval also hoping you can take a look here!

**Comment by adelekennedy** [comment]
restesting this to see if it's still an issue

**Comment by adelekennedy** [comment]
I can't replicate this for some reason - @lanitochka17 is this still reproducible for you?
