### ISSUE TITLE
[$250] Split - App crashes when tapping Copy to clipboard on code block context menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to group chat
3. Tap + > Spli expense > Manual
4. Create a split manual expense with code block as the description
5. Tap on the split preview
6. Long press on the code block
7. Tap Copy to clipboard

## Expected Result:
App will not crash

## Actual Result:
App crashes when tapping Copy to clipboard on code block context menu in split menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d4c3042e-a823-4a11-bc8e-0c11771791ad

[logs (2).txt](https://github.com/user-attachments/files/16680881/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a78f1cc82b94611b</li>
        <li>Upwork Job ID: 1827396760466325645</li>
        <li>Last Price Increase: 2024-08-24</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103731517</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-split

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Context menu shown in code block in menu item

### What is the root cause of that problem?

The context menu shouldn't be shown in codeblock in menu item

### What changes do you think we should make in order to solve the problem?

If codeblocks are unnecessary in the menu item description, we can remove the shouldParseTitle parameter from MenuItemWithTopDescription.

src/components/ReportActionItem/MoneyRequestView.tsx (or other similar parts)
```tsx
                <OfflineWithFeedback pendingAction={getPendingFieldAction('comment')}>
                    <MenuItemWithTopDescription
                        description={translate('common.description')}
                        shouldParseTitle
                        title={updatedTransactionDescription ?? transactionDescription}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by kevinksullivan** [comment]
PR still in review. Looping in another BZ member as I am going OOO

**Comment by isabelastisser** [comment]
No updates yet.

**Comment by lakchote** [comment]
Discussion is still happening in the [PR](https://github.com/Expensify/App/pull/48375#issuecomment-2366780513).

**Comment by lakchote** [comment]
> @lakchote @isabelastisser can you help to add the "Weekly" label back for this issue? It seems to be reverted to "Daily"

Done.

**Comment by isabelastisser** [comment]
@hoangzinh, I processed your payment in Upwork.
@daledah, please share your Upwork profile, thanks!

**Comment by isabelastisser** [comment]
@daledah, thanks! I sent you the offer in Upwork now. All set!
