### ISSUE TITLE
[HybridApp] Bump hybrid Android target version to unblock releases

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#47744]
## Problem

> From Aug 31, 2024, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

<img width="600" alt="Screenshot 2024-07-09 at 14 12 46" src="https://github.com/Expensify/Expensify/assets/10736861/05010b05-9288-4d9b-8a86-86c090474ac3">

## Why is this important?

This must be done by the end of August, to prevent app delisting. And to give us time to resolve any issues that occur with the bump.

## Solution

- Follow instructions [here](https://play.google.com/console/developers/8765590895836334604/app/4974129597497161901/policy-center)
- Request thorough testing from Applause
- Discuss plans for a one-off release

cc @Julesssss

**Comment by AndrewGable** [comment]
cc @mateuuszzzzz @war-in @staszekscp - Do either of you want this one?

**Comment by staszekscp** [comment]
Unfortunately we cannot access the link nor the image 😢 Could you provide a screenshot?

**Comment by AndrewGable** [comment]
![Google Chrome 2024-08-21 at 09 54 04](https://github.com/user-attachments/assets/6b7ea000-89d3-4787-b4c9-fb18a5b353f7)

![Google Chrome 2024-08-21 at 09 53 59](https://github.com/user-attachments/assets/216a0d8d-656e-4f58-9e76-751e3ea11766)

https://support.google.com/googleplay/android-developer/answer/11926878
https://developer.android.com/google/play/requirements/target-sdk
https://support.google.com/googleplay/android-developer/answer/13411745

**Comment by AndrewGable** [comment]
BTW I asked for an extension until October 31st and it was granted, but let's tackle this when we can

**Comment by trjExpensify** [comment]
Can we close this issue now that https://github.com/Expensify/Mobile-Expensify/pull/12983 is merged?

**Comment by staszekscp** [comment]
Yes, I think it can be closed, since the crucial change has been merged
