### ISSUE TITLE
Incomplete requests queued before update to new app version cause request queue "logjam" and new requests aren't processed

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#47740]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
e.g. memory consumption, storage read/write times, React native bridge concerns, inefficient React component rendering, etc.

We suspect there is an issue with having an unfinished request in the queue that has an older appversion 

We've had reports that new requests are failing to complete, and upon inspection, older requests are only different in that they show an older app version 

1. Queue a request (offline?), maybe a SmartScan, on an older version of the app
2. Update the app to a newer version before the request in 1. is completed
3. Queue more requests (more SmartScans)
4. Observe the queue of requests and see if it climbs and never processes request

## What is the impact of this on end-users?
List specific user experiences that will be improved by solving this problem e.g. app boot time, time to for some interaction to complete, etc.

If they update their app before a request completes, their queue potentially gets stuck and then all subsequent requests do not process. 

## List any benchmarks that show the severity of the issue
Please also provide exact steps taken to collect metrics above if any so we can independently verify the results.

Some users can have their requests queue climb into the hundreds: https://expensify.slack.com/archives/C05LX9D6E07/p1723481597404059?thread_ts=1721152209.600379&cid=C05LX9D6E07 

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

Possible solution: Force the data structure of the request that had not completed to match the data structure of a request in the new appversion.  

https://expensify.slack.com/archives/C05LX9D6E07/p1724148399842369?thread_ts=1721152209.600379&cid=C05LX9D6E07

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1724147920287259?thread_ts=1721152209.600379&cid=C05LX9D6E07 
 
[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Issue Owner</summary>Current Issue Owner: @rinej</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rinej</details>

**Comment by muttmuure** [comment]
Thread is here: [](https://expensify.slack.com/archives/C05LX9D6E07/p1724147920287259?thread_ts=1721152209.600379&cid=C05LX9D6E07)

**Comment by muttmuure** [comment]
@gedu I think you're working on this one?

**Comment by gedu** [comment]
Hey hey, no, I'm working on this one: https://github.com/Expensify/App/issues/47742, this one seems that was happening only on Hybrid app which I don't have access to

**Comment by gedu** [comment]
I will look some support from the team

**Comment by rinej** [comment]
hello @muttmuure I am going to work on that issue

**Comment by muttmuure** [comment]
Great!

**Comment by mallenexpensify** [comment]
@rinej do you think the below might be related here? I'm guessing no, wanting to double check before creating a job for it (to find the reproducible steps)
- https://github.com/Expensify/App/issues/47893

**Comment by rinej** [comment]
@mallenexpensify I don't think it will be related, with the version mismatch all requests which are send to the queue shouldn't be executed

**Comment by muttmuure** [comment]
Going to reopen the original: https://github.com/Expensify/App/issues/45546

**Comment by muttmuure** [comment]
The version mismatch was not the root cause of this issue
