### ISSUE TITLE
Search - No "exported to CSV" system message and invalid data in downloaded CSV file

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47741]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4874296
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace,
3. Go to workspace chat.
4. Submit two expenses.
5. Pay elsewhere the report.
6. Go to Search.
7. Go to Paid status.
8. Select the "Select all" checkbox for the paid expense report in Step 5.
9. Click on the dropdown > Download.
10. Go back to expense report in Step 5.
11. Refresh the page.
12. Open the CSV file.

## Expected Result:
In Step 11, there will be "exported to CSV" system message in the expense report.
In Step 12, the CSV file will show the correct expense details.

## Actual Result:
In Step 11, there is not "exported to CSV" system message in the expense report.
In Step 12, the CSV file shows invalid data.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f9d08d55-7220-4447-8bee-98dad343742b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by luacmartins** [comment]
We reverted the offending PR. Closing.
