### ISSUE TITLE
[$250] Chat - Chat focus is lost when create room by mentioning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47750]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** [gocemate+a1030@gmail.com](mailto:gocemate+a1030@gmail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a room( name it #Room 1
2. In room chat composer type # Room 2> Send
3. Select Yes from actionable whisper that asking if they want to create the room
4. Navigate to LHN
5. Navigate to #Room 1

## Expected Result:
Chat composer should be focused

## Actual Result:
Chat focus is lost when navigate to the room in which new room was created by mentioning

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8e7c1ae3-9c4b-49de-aefa-706fa3cb2ac1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c626f819c1cb5bf</li>
        <li>Upwork Job ID: 1828523320267674468</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by lanitochka17** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by puneetlath** [comment]
@lanitochka17 is that the right video? It doesn't seem related to your bug report.

**Comment by lanitochka17** [comment]
@puneetlath sorry for delay, correct video 

https://github.com/user-attachments/assets/d3a430b9-f650-4efb-9568-62876732d973

**Comment by c3024** [comment]
This is expected behaviour. On native apps, we autofocus the composer only when the chat is empty. We do not focus on the composer if there is a message in the chat on these apps.

https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L201-L203

https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/libs/canFocusInputOnScreenFocus/index.native.ts#L3

https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L293

**Comment by puneetlath** [comment]
Ah good catch @c3024. Thanks for pointing that out! Going to close.
