### ISSUE TITLE
Search - Invoice delete option is only present in Search page but not invoice report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47752]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoices
3. Enter amount, select participant and send the invoice
4. Open the invoice report
5. Look for Delete invoice option
6. Note that there is no option to delete invoice in the invoice report
7. Go to Search
8. Go to Invoices
9. Select the invoice in Step 3 via checkbox
10. Click on the dropdown > Delete
11. Delete the invoice

## Expected Result:
Invoice delete option should be present in both invoice report and Search page

## Actual Result:
Invoice delete option is only present in Search page but not invoice report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d135495c-303c-409d-85a1-65f6e437a5e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
We reverted the offending PR. Closing.

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 9.0.26-2
Issue is not repro on Production

https://github.com/user-attachments/assets/749458da-2c63-4822-9dbd-91c7c901c393
