### ISSUE TITLE
[$250] Polish - Search Term Clean Up for User Invite

### ISSUE THREAD

**Issue by grgia** [Expensify/App#47783]
Follow up to https://github.com/Expensify/App/issues/22534

PROPOSAL here -  https://swmansion.slack.com/archives/C05LX9D6E07/p1723130121950609
- Use ONYX to persist search phrases across screens 

cc @BrtqKr 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842190298675232394</li>
        <li>Upwork Job ID: 1842190298675232394</li>
        <li>Last Price Increase: 2024-10-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by grgia** [comment]
@BrtqKr mind commenting here?

**Comment by zanyrenney** [comment]
@grgia I am OOO until September. if this requires action in my absence, please reapply the label, otherwise I will see to it when i am back, cheers!

**Comment by BrtqKr** [comment]
I'm from SWM I'd like to take care of this

**Comment by DylanDylann** [comment]
@zanyrenney Please help to handle payment here

**Comment by zanyrenney** [comment]
@DylanDylann please apply to job above!

**Comment by DylanDylann** [comment]
@zanyrenney Applied!

**Comment by zanyrenney** [comment]
payment summary 

$250 to @DylanDylann paid via upwprk.
