### ISSUE TITLE
[HOLD for payment 2024-10-14] Debugging feature: Import Onyx State

### ISSUE THREAD

**Issue by TMisiukiewicz** [Expensify/App#47786]
### Problem
When working with profile traces received from New Expensify users, it’s possible to identify and take some actions based on its analysis. However, since the accounts can contain much more data than the ones we are using on a regular basis, it often makes it difficult to accurately reproduce certain performance issues and later evaluate the efectiveness of our optimizations. 

Additionally, some bugs are very hard to reproduce as they happen only on certain accounts.

### Solution
To address this problem, we propose to implement an “import Onyx state” feature. This feature would allow to load the previously exported state directly into another account, enabling us to replicate their exact conditions. It should automatically force offline mode, so we are sure it does not make any API calls while using the app. By doing so, we can accurately profile and measure the impact of our changes, ensuring that our performance optimizations are effective in real-world scenarios.

Additionally, it can help to resolve hard to reproduce bugs  - we already got this feature working internally and thanks to this we were able to reproduce and fix [this issue](https://expensify.slack.com/archives/C05LX9D6E07/p1721348346978119).

---
This kind of solution would need an easy way to bring the account back to the original state. I think “Clear cache and restart” should do the work.

Things to consider:
- review if we need to mask more stuff when exporting state - e.g. report’s lastMessageText, lastMessageHtml, replacing images/videos with dummy placeholders, masking expenses
- review the way of masking things and how it affects the results - for example, email addresses are masked by replacing them with *** , but it might affect the results for filtering, since we’ll never go into some logic specific for valid emails only

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment]
@TMisiukiewicz will you be working on this one?

**Comment by TMisiukiewicz** [comment]
@dylanexpensify I can see [here on Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1724757086211349?thread_ts=1724247139.893599&cid=C05LX9D6E07) @muttmuure was discussing this proposal internally, do we already have a decision if we're going to work on this one? If yes, feel free to assign me 👍

**Comment by TMisiukiewicz** [comment]
Back to work on this 👍

**Comment by dylanexpensify** [comment]
TY!

**Comment by TMisiukiewicz** [comment]
not overdue, I did not have much time to move forward with it due to React Universe Conf, but I am back now. I already have web implementation ready, now adjusting mobile.

**Comment by dylanexpensify** [comment]
Sounds great!

**Comment by muttmuure** [comment]
Sorry thought this needed a review

**Comment by muttmuure** [comment]
will reapply when we're ready

**Comment by TMisiukiewicz** [comment]
@muttmuure quick question, would it be beneficial to display some kind of an information about using the app in the "imported" mode? It could be e.g. a button displayed in every screen of the app allowing to get back to original state after pressing. Something like this (ofc adjusted correctly):
![image](https://github.com/user-attachments/assets/96e433b5-ded2-42d2-ad38-f330028fcebc)

**Comment by yuwenmemon** [comment]
@tomekzaw Yeah, that would be useful IMO. I'm not sure if that pattern of having a bar like that at the bottom has been used before though. cc @Expensify/design for their thoughts.

**Comment by dannymcclain** [comment]
I've never seen a pattern like that in NewDot—I'm not completely against something like that for testing, but would it make more sense to put an option like that in the troubleshooting page? Or does it absolutely _have_ to be on the inbox/home screen?

**Comment by shawnborton** [comment]
Yeah, I think I would rather keep that sort of thing near where the actual debug options live.

**Comment by TMisiukiewicz** [comment]
The "Clear cache and restart" is already in the Troubleshoot page and pressing it is doing the same thing. However, without a clear indicator, users might forget they’re in import mode, leading to confusion or unintended actions under the wrong user account. A simple visual reminder helps keep the user aware of their current working context at all times. If at any point the user needs to finish debugging, they can easily access the option without having to navigate away from their current screen. The feature would be used probably only by developers to debug things, but since the state is persistent, if an app is opened after some time, people might report bugs that do not exist. Do you have any other ideas how we could indicate that?

**Comment by shawnborton** [comment]
Hmm yeah that's a fair point. I think if we removed the extra `SafeArea` that I am seeing under the tabs, it wouldn't eat as much vertical space and thus I think it could be okay? Again, this is a dev-only feature and something that I hope we don't expose to "real users".

**Comment by TMisiukiewicz** [comment]
@shawnborton how about using absolute positioning? It's much easier as i don't have to care about removing safearea from each screen when it's displayed. It covers the bottom of an app just a bit, but doesn't block from doing any actions from bottom sheet. 

![ios](https://github.com/user-attachments/assets/6c735a12-5d41-416d-b1cb-572011eb16a9)
![android](https://github.com/user-attachments/assets/d5944b71-35d8-40f1-a084-99e9f0382acc)
![web](https://github.com/user-attachments/assets/a4c9bf13-2d5e-4b13-a655-4aef8d9988c1)

**Comment by shawnborton** [comment]
Definitely not a big fan of that personally, it feels broken to me.

**Comment by TMisiukiewicz** [comment]
Yeah I was able to easily align it on mobile but it is very difficult to actually make it display properly on web and desktop. One more idea is displaying it similarly to offline indicator. With this solution there is no need to play around safe area and it does not take much vertical space of the screen. It works on all platforms without any additional work with the layout. Let me know your thoughts.

<img width="364" alt="image" src="https://github.com/user-attachments/assets/9921c1c6-81b0-430b-8802-b410ae091da1">
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/386bfd4c-dae9-4784-8b9b-285b990521dc">

**Comment by dannymcclain** [comment]
>One more idea is displaying it similarly to offline indicator.

I like this better than overlapping the bottom of the app.

**Comment by shawnborton** [comment]
Same, I like that better. I think I would just use a regular weight font though, something like this:

![CleanShot 2024-09-14 at 08 33 20@2x](https://github.com/user-attachments/assets/05f69fc8-137f-4a25-90d4-5ef2562eb411)

**Comment by dubielzyk-expensify** [comment]
Yeah that feels right 👍

**Comment by TMisiukiewicz** [comment]
Thanks for the input everyone, I'll proceed with opening a PR 👍

**Comment by dylanexpensify** [comment]
In progress

**Comment by TMisiukiewicz** [comment]
PR is waiting for a review #49255

**Comment by dylanexpensify** [comment]
Nice! In review still!

**Comment by dylanexpensify** [comment]
pending deploy!

**Comment by dylanexpensify** [comment]
on staging, pending prod deply

**Comment by rlinoz** [comment]
@DylanDylann was the C+ for the PR

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @DylanDylann $250 

Please apply/request!

**Comment by DylanDylann** [comment]
@dylanexpensify  Which Upwork job should I apply to?

**Comment by dylanexpensify** [comment]
@DylanDylann sent offer!

**Comment by DylanDylann** [comment]
@dylanexpensify Accepted it!
