### ISSUE TITLE
Avatar - Avatar does not updates on the secondary device logged in to the same account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47792]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4877485&group_by=cases:section_id&group_order=asc&group_id=229070
**Email or phone of affected tester (no customers):** gocemate+a1043@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions:
1. Login with same account on two devices
2. In the main testing device, Navigate to Settings > Profile> Upload an avatar
3. Take a note of Avatar on the secondary device

## Expected Result:
Avatar update on main device should also updates on the secondary devices logged in to the same account

## Actual Result:
Avatar does not updates on the secondary device logged in to the same account in real time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/00a7a658-7c83-4424-a3f1-f154f073b011

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abekkala** [comment]
vsp is on hold
