### ISSUE TITLE
[$250] RBR shows in NewDot on connections that are only configurable in OldDot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47797]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724202135633669

## Action Performed:
1. On OldDot, go to Settings -> Workspaces
2. Choose a Control or Collect Workspace
3. Go to Connections -> QuickBooks Desktop -> Click Connect to QuickBooks Desktop
4. Click Shared Company Drive as an option and close the modal once it's giving you next steps.
5. Refresh the page and see the error "The connection could not be completed" appear
6. Open NewDot and see a RBR on your profile photo in the bottom navigation bar
7. Tap on Profile photo in the navbar -> Workspaces -> Same workspace as above -> Accounting
8. See an empty list with nothing to indicate the RBR error
## Expected Result:
Expecting to either not see RBR or a note that this was configured in OldDot
## Actual Result:
See an empty list with nothing to indicate the RBR error
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![www expensify com_policy_param={%22policyID%22_%2243BC6076D3D1418B%22}(MacBook Pro)](https://github.com/user-attachments/assets/b41db93e-68c1-4b11-b36c-69bf4b03f5ed)

<img src="https://github.com/user-attachments/assets/9633375d-842a-413f-9516-f91c6bd882ad" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/c2bd01f5-7d8c-4f95-9f21-cc5d39833366" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/821c57d6-e619-461c-815e-4963026714a0" width="40%" height="40%">
Add any screenshot/video evidence

![Snip - (6) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/6cd7300f-2577-4362-a489-b0eaa94aba5e)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa5ae4b74b2af547</li>
        <li>Upwork Job ID: 1828156369928229332</li>
        <li>Last Price Increase: 2024-09-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by OfstadC** [comment]
I think I missed when the PR deployed 😅 - Sorry folks! Working on sorting payment today

**Comment by OfstadC** [comment]
## Payment Summary 
- @parasharrajat due $250 via manual New Expensify request
- @daledah could you please accept the offer [here](https://www.upwork.com/nx/wm/offer/104211602)? 😃

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
