### ISSUE TITLE
[HOLD for payment 2024-09-16][$250] mWeb - Chat - In contacts  a random guest user is displayed after login via public room link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47806]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to this link as signed out user https://staging.new.expensify.com/r/7075912447943023
2. Tap sign in
3. Enter credentials and log in
4. Navigate to LHN
5. Tap fab -- start chat
6. In contacts, note a guest user is added.

## Expected Result:
In contacts, a random guest user must not be displayed after login via public room link

## Actual Result:
In contacts, a random guest user is displayed after login via public room link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/55f56373-f43a-467d-822e-2343ad068345

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0148f0358fba85f9ac</li>
        <li>Upwork Job ID: 1828135607297326184</li>
        <li>Last Price Increase: 2024-08-26</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103703199</li>
<li>dominictb | Contributor | 103703202</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jjcoffee</details>

**Comment by lanitochka17** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment]
I am confused by the steps, as it specifically mentions `In contacts, note a guest user is added.`

The contact was not added to the chat, but rather a suggestion. And this is by design. 

@lanitochka17 does the tester recognize that email in any capacity in regards to Expensify or testing within Expensify?

**Comment by CortneyOfstad** [comment]
Thank you @dominictb for the clarification!

I am having trouble recreating this, so I am going to have this retest by QA 👍

**Comment by jjcoffee** [comment]
@dominictb's [proposal](https://github.com/Expensify/App/issues/47806#issuecomment-2302972273) LGTM! I think cleaning up on the API success callback seems the neatest way to do this as we can then pass the accountID to clear from the session data. Happy to listen to arguments otherwise if I've missed anything!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by dangrous** [comment]
Yeah updating it in the success data makes sense to me, then we already know which account ID to remove.

**Comment by CortneyOfstad** [comment]
PR is still being reviewed!

**Comment by bfitzexpensify** [comment]
@dominictb @jjcoffee can you please take a look at https://github.com/Expensify/App/issues/48715 to see if it is related to your changes? It was found while executing https://github.com/Expensify/App/pull/48144

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by VictoriaExpensify** [comment]
Bumping Ben's message above - @jjcoffee I think you were looking into this:

>@dominictb @jjcoffee can you please take a look at https://github.com/Expensify/App/issues/48715 to see if it is related to your changes? It was found while executing https://github.com/Expensify/App/pull/48144

It looks like these are probably related issues

**Comment by jjcoffee** [comment]
I can't repro after reverting the changes from the PR, so I don't think it's related.

**Comment by CortneyOfstad** [comment]
Thanks @jjcoffee!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@jjcoffee — paid $250 via Upwork
@dominictb — paid $250 via Upwork
