### ISSUE TITLE
mWeb - QBO - Red dot path by disconnecting qbo/xero cannot be created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47807]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45251
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon-- workspaces -- workspace
3. Tap more features -- enable accounting
4. Tap accounting -- connect to xero
5. Tap 3dot and disconnect
6. Note red dot cannot be created
7. Now connect to qbo entering incorrect credentials
8. Note red dot cannot be created
9. Connect to netsuite by entering incorrect credentials
10. Now note red dot us created

## Expected Result:
Red dot path by disconnecting qbo/xero Or entering incorrect credentials must be able to create

## Actual Result:
Red dot path by disconnecting qbo/xero Or entering incorrect credentials cannot be created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ef40e9d7-b12f-45b8-8c5f-0881c73d3f86

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by arosiclair** [comment]
We discussed this in the thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1724337654975559).

This isn't a bug just a misunderstanding:

- Successfully disconnecting QBO/Xero in Expensify should NOT create a RBR or error message
- Failing to sign into QBO/Xero with incorrect credentials should NOT create a RBR or error message
