### ISSUE TITLE
Bartek Krason - Apple Developer Provisioning Profile

### ISSUE THREAD

**Issue by grgia** [Expensify/App#47811]
# Problem
@BrtqKr 

This is a requirement for developing the Native Share Project https://docs.google.com/document/d/14C1VifxvIXeyLAf0XstbC-wvyAb5SQZ0AOw0-jLRyZs/edit

There's been some problems settings this up - https://github.com/Expensify/App/issues/29232#issuecomment-2227928337

# Solution
[Relevant SO](https://stackoverflowteams.com/c/expensify/questions/17615/17616#17616)

**Comment by AndrewGable** [comment]
Still pinning down exactly what we need to configure, but I am happy to do so in the Apple Developer console.

**Comment by AndrewGable** [comment]
Closing for now, we can reopen if we need any more configuration @BrtqKr
