### ISSUE TITLE
Contact methods - User is nor  navigated to contact methods details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47814]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**dave0123seife@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44635
## Action Performed:
1. Sign up with a new account > click on Settings > Security > Two-factor authentication.
2. Click on 'Verify your account here' link
3. On contact methods details page.

## Expected Result:
User is redirected to contact method page

## Actual Result:
User is redirected to 2FA page

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/5a113e39-7493-432e-a448-cb1fee277330

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by etCoderDysto** [comment]
> 1. Sign up with a new account > click on Settings > Security > Two-factor authentication.
> 2. Click on 'Verify your account here' link
 _**Verify that you are navigated to contact methods details page**_
> 3. Validate your account
 _**Verify that you are redirected to 2FA page**_
 
 This is expected. This behaviour was intentionally introduced in this [PR](https://github.com/Expensify/App/pull/44635#:~:text=in%20Contact%20methods%3A-,Sign%20up%20with%20a%20new%20account%20%3E%20click%20on%20Settings%20%3E%20Security%20%3E%20Two,Verify%20that%20you%20are%20redirected%20to%202FA%20page,-Verify%20that%202FA)
 
 cc: @mollfpr

**Comment by bondydaa** [comment]
sounds like we can close this out then, thanks @etCoderDysto 🙇
