### ISSUE TITLE
[Payment due][$250] All - Approver Flow - Admin has 2 payment options if Reimbursements is set to Indirect

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47823]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4879259
**Email or phone of affected tester (no customers):** fischer9966+082124aadm@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition NewDot:
1. Create admin account with Gmail
2. Create Collect workspace, set Workflows to enabled
3. Invite Employee with Gmail accounts to this workspace
4. Enable Approvals in Workflows and set Admin as Approver
5. Enable Workflows > Delay submissions and set it to Manually

Precondition OldDot:
1. Login to OD as admin
2. Go to Collect workspace > Reimbursements
3. Select "Indirect"

Steps NewDot:
1. Go to staging.new.expensify.com or open App
2. Login as the employee and submit a report
3. Login as the Admin and approve the report
4. Verify the admin only has one payment option - "Pay Elsewhere"

## Expected Result:
Admin only has one payment option "Pay Elsewhare" if Reimbursements is set to Indirect

## Actual Result:
Admin has 2 payment options - "Pay Elsewhare" and "Pay with Expensify" if Reimbursements is set to Indirect

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/064f098a-e711-4e05-ac4d-a55fb8beef72

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0a122b57dabf58d</li>
        <li>Upwork Job ID: 1826688249351475147</li>
        <li>Last Price Increase: 2024-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 103689004</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lschurr** [comment]
Looks like this was just assigned today. @daledah let us know when you have a PR up!

**Comment by lschurr** [comment]
Looks like the automation failed on this one.

Payment summary:

- Contributor: @daledah $250 (please accept [Upwork offer](https://www.upwork.com/nx/wm/offer/104664211))
- Reviewer: @mkhutornyi $250 paid [via Upwork](https://www.upwork.com/nx/wm/workroom/38224855/overview)
