### ISSUE TITLE
Android - Expensify icon is replaced with something else in external programs

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47836]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
Precontidions: Have a txt file with only https://staging.new.expensify.com/r/2091104345528462
as content.

1. Open the txt file on your Android phone
2. Select the full link

## Expected Result:
Expensify icon should be present.

## Actual Result:
Expensify icon is replaced with something else in external programs.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6576401_1724095315684!Screenshot_20240819_211508_Drive](https://github.com/user-attachments/assets/e6958d99-ea65-4022-bea6-99921029e78c)

https://github.com/user-attachments/assets/f6b2a849-9889-4eab-b482-232484999a80

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
@jliexpensify taking over here, as I'm an iOS girl.

**Comment by jliexpensify** [comment]
@IuliiaHerets I'm not seeing this:

![image](https://github.com/user-attachments/assets/e77c0427-8fd9-4a7d-82a9-179462448621)

@shawnborton I've just tagged Design in case this is something you want to monitor for the future, but there doesn't seem to be a bug here.
