### ISSUE TITLE
E2E Pipeline: Fix pipeline timeout 

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#47842]
We sometimes see errors in the e2e pipeline where it fails due to a 1h 30m timeout, example:

- https://github.com/Expensify/App/actions/runs/10473547848/job/29008571128

The problem is that on AWS we sometimes have to wait for 30-60 minutes, until our job is started. 

We can check if the provisioning in AWS can be improved, but meanwhile we'd suggest to simply increase the timeout for the e2e job.

**Comment by hannojg** [comment]
cc @kirillzyusko

**Comment by kirillzyusko** [comment]
I think that issue can be closed since the the PR was merged!
