### ISSUE TITLE
[HybridApp] Notifications not styled correctly, or using custom Antfood sounds

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#47868]
### Problem

HybridApp isn't using our custom threaded message notification styling, thread/group notification headings, and is not using our custom Antfood notification sounds. This is due to the Airship payload either not being set correctly, or not being read correctly.

### Solution

Figure out why. This is due to the either Airship payload either not being set correctly, or not being read correctly.

**Comment by Julesssss** [comment]
@AndrewGable minor issue for the project

**Comment by Julesssss** [comment]
Looking into this once the payload fixes are deployed

**Comment by Julesssss** [comment]
I updated this issue to cover all issues related to the missing payload data

**Comment by Julesssss** [comment]
Picking this up today. Currently having issues with my Android builds -- which I am going to use to debug the received Airship package.

**Comment by Julesssss** [comment]
Futher issues and debugging today:  
- Located `.env` issue, cloned missing file (and reviewed PR that simplifies this process)
- Successfully built using cli, then an Android Studio build 🎉 
- Dealt with runtime crash with seemingly unrelated `undefined is not an object / Store.ReportHistory.bindCacheClearingEvents` stacktrace 

Then I was able to verify from mobile logs that the payload data with necessary fields seems to be successfully delivered. My next step is to generate a debuggable build that I can attach a debugger to. My guess is that [this logic](https://github.com/Expensify/Mobile-Expensify/blob/a76384745e545975c1d7d21f96a919d1313146f5/Android/src/org/me/mobiexpensifyg/ExpensifyNotificationProvider.java#L122-L123) needs some fixes.

**Comment by Julesssss** [comment]
Ah, I can build but now getting a runtime crash. I'll need to figure that out tomorrow

![Screenshot 2024-09-09 at 15 09 00](https://github.com/user-attachments/assets/3e329606-638a-47fd-8525-5f6b39644294)
![Screenshot 2024-09-09 at 15 09 12](https://github.com/user-attachments/assets/84631cc4-932a-4bc3-80df-4ca339304892)

**Comment by Julesssss** [comment]
After a few more gradle/npm cleans I was able to get past the flakey CMake build errors. Next up was the yapl `ReportHistory.bindCXacheClearingEvents` crash. 

This got me to a place where I built a local, debuggable, production build which is necessary in order to verify the bug. But now I have a new runtime crash at sign-in: `Can't find variable: moment at position 403:31 in app/libs/api.js` -- very odd as this is 4 year old code:

<img width="789" alt="Screenshot 2024-09-10 at 16 52 04" src="https://github.com/user-attachments/assets/88919cfb-5d2d-4e28-a3db-0a7e81cf205c">

Will continue again tomorrow, this time on a slightly different `main` commit.

**Comment by Julesssss** [comment]
Andrew figured out the [build issue](https://expensify.slack.com/archives/C03TQ48KC/p1726071415395839?thread_ts=1726062660.657659&cid=C03TQ48KC). I am very relieved and expect to make immediate progress tomorrow.

**Comment by Julesssss** [comment]
I'm able to build and run both prod and dev builds today.

Next issue is that the new logic for picking up `.env` file configs doesn't seem to be working. Both my `.env` and `.env.hybrid` files contain my local dev env. Yet requests are made to production. 

I am debugging this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1726154603390429) in Slack.

**Comment by Julesssss** [comment]
We all seem to be running into the env issue where we cannot access new experience in local builds. We're discussing in a few threads here.

Sticking in OldDot for now, I see Airship receiving events: 

**NewDot chat message:**
`2024-09-13 10:57:21.391  4370-4370  Expensify - UALib       org.me.mobiexpensifyg                V  AirshipWorker - Running job: JobInfo{action='ACTION_REFRESH', airshipComponentName='com.urbanairship.remotedata.RemoteData', isNetworkAccessRequired=true, minDelayMs=0, conflictStrategy=0, initialBackOffMs=30000, extras={}, rateLimitIds=[]}, work Id: a73c6f55-f14b-42b5-b4b6-29bd7d2902f3 run attempt: 1
`

**OldDot cli notification**
`nfo] UrbanAirshipAPI - Logging request details ~~ endpoint: 'https://go.urbanairship.com/api/push' data: '[audience: '[named_user: '<REDACTED>']' notification: '[alert: '<REDACTED>' android: '[title: 'Expensify' extra: '[payload: '{"type":"reportReimbursed","reportID":2635723422899470,"app":"old"}' fromExpensify: '1']']' ios: '[extra: '[payload: '[type: 'reportReimbursed' reportID: '2635723422899470' app: 'old']' fromExpensify: '1']' sound: 'default' content_available: '1']']' device_types: '[0: 'android' 1: 'ios']']'`
local: `2024-09-13 11:04:03.427  4370-5449  Expensify               org.me.mobiexpensifyg                E  [alrt] [PusherManager] Connection failure. Reason: An exception was thrown by the websocket
`

**Airship attempting to run job:**
`AirshipWorker - Running job: JobInfo{action='ACTION_REFRESH', airshipComponentName='com.urbanairship.remotedata.RemoteData', isNetworkAccessRequired=true, minDelayMs=0, conflictStrategy=0, initialBackOffMs=30000, extras={}, rateLimitIds=[]}, work Id: 1711f365-62e0-49c8-96e1-7c02cf8202e5 run attempt: 2
2024-09-13 11:09:38.746  4370-4370  Expensify - UALib       org.me.mobiexpensifyg                V  JobDispatcher - Running job: JobInfo{action='ACTION_REFRESH', airshipComponentName='com.urbanairship.remotedata.RemoteData', isNetworkAccessRequired=true, minDelayMs=0, conflictStrategy=0, initialBackOffMs=30000, extras={}, rateLimitIds=[]}, run attempt: 2
2024-09-13 11:09:38.786  4370-5817  Expensify - UALib       org.me.mobiexpensifyg                V  JobRunner - Finished: JobInfo{action='ACTION_REFRESH', airshipComponentName='com.urbanairship.remotedata.RemoteData', isNetworkAccessRequired=true, minDelayMs=0, conflictStrategy=0, initialBackOffMs=30000, extras={}, rateLimitIds=[]} with result: RETRY
2024-09-13 11:09:38.787  4370-5817  Expensify - UALib       org.me.mobiexpensifyg                V  JobDispatcher - Job finished. Job info: JobInfo{action='ACTION_REFRESH', airshipComponentName='com.urbanairship.remotedata.RemoteData', isNetworkAccessRequired=true, minDelayMs=0, conflictStrategy=0, initialBackOffMs=30000, extras={}, rateLimitIds=[]}, result: RETRY
2024-09-13 11:09:38.787  4370-4432  WM-WorkerWrapper        org.me.mobiexpensifyg                I  Worker result RETRY for Work [ id=1711f365-62e0-49c8-96e1-7c02cf8202e5, tags={ com.urbanairship.job.AirshipWorker, airship } ]`

**Comment by Julesssss** [comment]
**Debugging Notes**

Airship is successfully registering and receiving push cli tool push messages on my physical device. On my emulator with Google API services, Airship is stuck in a loop where `ACTION_UPDATE_PUSH_REGISTRATION` is being called. For now I am not concerned about fixing as it's a distraction.

As I can debug the Airship library functions I can see valid push data. The push is not shown, and Imy debugging points within our native notification logic are never hit. So somewhere between Airship and native handling an error is causing us to drop the messages. Next step is to add a bunch of logging to the js code which cannot be debugged.

**Comment by Julesssss** [comment]
I'm at a deadend with local notifications and something in our build steps appears to be broken. I'm asking [here](https://expensify.slack.com/archives/C036QM0SLJK/p1726240830000509?thread_ts=1726157922.153189&cid=C036QM0SLJK) for thoughts from SWM, but in the meantime I have a potential workaround that might let me get local notifications working so I can debug them. 

- Switch env back to production config
- Switch the airship keys so that both are set to prod
- Generate debuggable production builds
- Debug the production build and use prod accounts to trigger the notifications

**Comment by Julesssss** [comment]
I just noticed that the Airship test notification is also not displaying... I see the following crash which is odd.

<img width="1300" alt="Screenshot 2024-09-13 at 17 45 10" src="https://github.com/user-attachments/assets/19964e53-5078-4042-89c7-d9386c387948">

I also think I might hand over this issue to SWM as they don't seem to be blocked from accessing New Expensify from within HybridApp. I can help with theory, likely bad LOC, and what's being sent from the backend.

**Comment by Julesssss** [comment]
Finally -- debugger is attached and I am receiving notifications 🙏 

I have pulled the payload data successfully. Will continue after lunch.

**Notes**
```
hariseldon585+2@gmail.com -- NewDot
hariseldon585+3@gmail.com -- OldDot
```

**Comment by Julesssss** [comment]
I have to trick the mobile app into using an outdated tryNewDot NVP, but I was able to verify that the broken logic lies in [this](https://github.com/Expensify/Mobile-Expensify/blob/a76384745e545975c1d7d21f96a919d1313146f5/Android/src/org/me/mobiexpensifyg/ExpensifyNotificationProvider.java#L123) line.

My theory is that JsonMap returns a JSONString, which is not exactly equal to `app` when casting to string with `String.valueOf()`. I can see that the payload value of `app` is `new`, and there is no capitalisation or space characters. I have modified the code in my branch and now need to test it.

```
payload.containsKey("app") && String.valueOf(payload.get("app")).equals("new");
```


However, testing still takes 20 minutes after any single change, and I am still facing issues receiving notifications...

**Comment by Julesssss** [comment]
Okay, so as I commented yesterday I think I have located the problem and have a PR [here](https://github.com/Expensify/Mobile-Expensify/pull/13125). I now need to test this... But again this morning I'm completely unable to receive notifications. There are so many variables that could be causing this and it is very difficult to figure out.

**Configuration required to receive Airship notifications:**
- `baseFile = .env.production`
- Used airship prod key & secret
- Overriding `Expensify.prototype.setIsOnDev`
- Not authenticated to any other open client
- HybridApp in Old experience
- User account to New experience 

This produces an Airship crash, and the notification is not displayed. For which I have created an issue [here](https://github.com/Expensify/Expensify/issues/428777).

**Comment by Julesssss** [comment]
Another long day, but I have made progress. Some of my account are simply not receiving notifications... this is concerning and very annoying but a secondary problem that needs to wait until the resolution of this issue. 

Today I was finally able to test my [potential solution](https://github.com/Expensify/Mobile-Expensify/pull/13125), which turned out to not work. I have closed the PR. In good news though, testing my PR pointed me to the real problem -- something in the backend is causing all report comments push notifications to use the new payload data (onyx), but the old app marker.

One problem is that when calling sendComment we don't yet know who the recipient should be. So perhaps this should be the responsibility of later classes such as `MobilePushNotifications` or `UrbanAirshipAPI`. Once the backend issues is resolved, client notification styling will work as expected, as shown here by a workaround I was able to verify this afternoon.

![Screenshot_20240917_155918](https://github.com/user-attachments/assets/f432caf0-2899-401a-847a-97b7a0e8c063) ![Screenshot_20240917_155930](https://github.com/user-attachments/assets/2fdf1bdf-b7b1-4659-bedf-42bedccb8f63)

**Comment by Julesssss** [comment]
Today I figured out why this issue only exists on prod... This is due to a data migration we performed about 6 months ago. This set the `tryNewDot` NVP for existing accounts to `{}`. This obviously wasn't run in our dev environments which explains why results are completely different on dev and prod 😌

I believe that I just need to fix [this query](https://github.com/Expensify/Auth/blob/354883661182f0a3d5708c5b247357642b0a931c/auth/command/GetTryNewDotNVPForAccounts.cpp#L22-L30) so that it handles empty objects as well as null values and the issue should be resolved. Then I'll add more logging to make it easier to debug in the future.

**Comment by trjExpensify** [comment]
>I believe that I just need to fix [this query](https://github.com/Expensify/Auth/blob/354883661182f0a3d5708c5b247357642b0a931c/auth/command/GetTryNewDotNVPForAccounts.cpp#L22-L30) so that it handles empty objects as well as null values and the issue should be resolved. 

That's encouraging!

**Comment by Julesssss** [comment]
WIP PR here. I have added automated tests, then fixed the query for two potential broken cases, and I have the third one working locally: 

![Screenshot 2024-09-18 at 16 50 27](https://github.com/user-attachments/assets/05b80247-6057-4abc-9eb1-03d2fa64e3c3)

Hopefully I can convert the final local query modification to the Auth command tomorrow, then test end to end and submit for review.

**Comment by Julesssss** [comment]
I ended up having to completely rewrite the query today as:
- Results were only returned for users with a 'tryNewDot' entry in the `nameValuePairs` table -- this doesn't work as we need to return a value for every single user passed in the query  
- There were multiple failure cases due to different NVP data values (null, empty object, etc) 

The command is now correctly handling all cases and my final step is to fix the query formatting.

**Comment by Julesssss** [comment]
Last night the Auth PR was merged and deployed. This morning I will perform testing to ensure our Web push notification logic now works as expected 🤞

**Comment by Julesssss** [comment]
Unfortunately, I'm going to need to look into command logic again.

My account is set to new experience, yet I am marked as an old experience user 😕 Hopefully there is a missed test case or something like that...

<img width="337" alt="Screenshot 2024-09-20 at 10 41 43" src="https://github.com/user-attachments/assets/748594fd-0eb1-475a-9149-a814ad683ade">

<img width="689" alt="Screenshot 2024-09-20 at 10 42 40" src="https://github.com/user-attachments/assets/b3ca897f-6827-4060-8ac7-85411a8f9739">

**Comment by Julesssss** [comment]
My initial thought was that the error handling was incorrect, but after further testing this isn't the case.

I now believe the issue is due to the Auth results of `'false'` being read as truthy and set to `true`... My plan is to fix this in Web-E, which will be followed by an Auth fix next week.

**Comment by Julesssss** [comment]
Fixed with simple boolean casting. I have tested many cases of different NVP values and this should fix notification styling for good. 

[Here's the PR](https://github.com/Expensify/Web-Expensify/pull/43622). A better long term solution will be to prevent NVP data from being persisted/read as strings, but I will complete that in [this](https://github.com/Expensify/Expensify/issues/429688) follow-up task.

**Comment by Julesssss** [comment]
The PR had a small [improvement request](https://github.com/Expensify/Web-Expensify/pull/43622#discussion_r1771129705) on Friday outside of my working hours. The change was made this morning, but by the time @MonilBhavsar is able to approve, it will be too late in my day to request, test, and handle the CP. So I plan to request the CP first thing Tuesday morning GMT.

Despite the importance of this PR, I don't feel comfortable with asking someone else to approve Monil's change request, so instead I will DM Monil to ensure he sees the commit.

**Comment by Julesssss** [comment]
Auth and Web-E PRs deployed. 

I can see what looks like the correct payload being pushed to device, yet something is not quite right as the notification still shows as Hybrid. Will look into this today after handling [this](https://github.com/Expensify/Expensify/issues/430603) issue.

- User in New experience -> payload[app] set 'new'
- User in Old experience -> payload[app] set to 'old'

**Comment by Julesssss** [comment]
HybridApp PR: https://github.com/Expensify/Expensify/issues/430603
