### ISSUE TITLE
QBO - "Accounts payable" is populated with accounts after connecting to QBO

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47877]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
Issue not repro when executing this PR: https://github.com/Expensify/App/pull/47696
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to QBO
7. Wait for the sync to finish
8. Add "/quickbooks-online/export/out-of-pocket-expense/account-select" to the end of your current URL and navigate to it

## Expected Result:
The list should be empty.

## Actual Result:
"Accounts payable" is populated with accounts after connecting to QBO.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e0389116-5ae7-4ba6-a6d7-bb0d2fd166a4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment]
Discussing [here](https://expensify.slack.com/archives/C036QM0SLJK/p1724701979690819)

**Comment by trjExpensify** [comment]
Commented in [the PR](https://github.com/Expensify/App/pull/47696#issuecomment-2311931169) this issue was created from, I don't think it's a bug.

**Comment by OfstadC** [comment]
Following along in the linked PR - but I imagine this can likely be closed since I don't believe it's a bug

**Comment by trjExpensify** [comment]
Confirmation we can close this.
