### ISSUE TITLE
Android - Nothing happens when selecting Start/Stop option when creating distance request

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47879]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47720
**Email or phone of affected tester (no customers):** applausetester+uo0822@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open New Expensify app
2. Enter any workspace chat
3. Tap "+" and submit expense
4. Tap distance tab and attempt to add start/stop locations.

## Expected Result:
User is able to enter locations

## Actual Result:
Nothing happens when tapping Start/stop

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f21c3ecb-364b-436b-b84f-11f04ba8b7f2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by marcaaron** [comment]
I am unable to repro. 

![2024-08-22_15-31-04](https://github.com/user-attachments/assets/19bbbfc1-03d6-47a5-98c3-31ab2a48ff53)

**Comment by marcaaron** [comment]
It does seem like it could be one of the conditions here preventing this (modified in linked PR in this issue's description):

```js
function canUserPerformWriteAction(report: OnyxEntry<Report>) {
    const reportErrors = getAddWorkspaceRoomOrChatReportErrors(report);

    // If the expense report is marked for deletion, let us prevent any further write action.
    if (isMoneyRequestReportPendingDeletion(report)) {
        return false;
    }

    const reportNameValuePairs = getReportNameValuePairs(report?.reportID);
    return !isArchivedRoom(report, reportNameValuePairs) && isEmptyObject(reportErrors) && report && isAllowedToComment(report) && !isAnonymousUser && canWriteInReport(report);
}
```
But there's not enough information to triage this. Reverting for now and building an ad hoc [here](https://github.com/Expensify/App/pull/47890).

**Next steps:** Have tester QA against the ad hoc.

**Comment by puneetlath** [comment]
QA has confirmed this is passing now. Demoting and closing.
