### ISSUE TITLE
mWeb/Safari - Chat - Nothing happens when "Add attachment" option is tapped

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47876]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributimWeb - Chat - Nothing happens when "Add attachment" option is tappedcom to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4887449
**Email or phone of affected tester (no customers):** applausetester+vd_mweb082224@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: issue seems to only affect mWeb on iOS/Safari
1. Go to https://staging.new.expensify.com/
2. Log in
3. Go to any chat
4. Tap on the "+" button on compose box
5. Select "Add attachment"

## Expected Result:
The options menu to select an attachment should be displayed

## Actual Result:
Nothing happens when "Add attachment" option is tapped

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6644eddc-8573-4f24-a7ae-99f8608bf4a2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/277e76dd-118f-44d6-bbfa-9578412a6334

**Comment by arosiclair** [comment]
Reproduced with the latest changes in dev.

**Comment by arosiclair** [comment]
Reverting https://github.com/Expensify/App/pull/47341 fixes the issue

**Comment by arosiclair** [comment]
Pinged @zfurtak to take a look [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1724357701654589?thread_ts=1724351147.922599&cid=C01GTK53T8Q)

**Comment by arosiclair** [comment]
Revert is prepped [here](https://github.com/Expensify/App/pull/47882). Giving @zfurtak a chance to respond before moving forward.

**Comment by war-in** [comment]
@arosiclair FYI @zfurtak will respond on Monday (she is OOO this week)

**Comment by techievivek** [comment]
et's proceed with the revert since there are other blockers linked to the above PR. I've already pinged the app deployers in Slack to see if anyone is available to help with the CP: https://expensify.slack.com/archives/C07J32337/p1724404593705399

**Comment by arosiclair** [comment]
[Revert fixed it!](https://github.com/Expensify/App/pull/47882#issuecomment-2307264021)
