### ISSUE TITLE
[Awaiting Payment][$125] Open report is called twice after comment linking

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#47889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @janicduplessis 
**Slack conversation:**

## Action Performed:

Prepare 2 chats: chat A with a few messages and chat B with a link to a message in chat A.

- Go to Troubleshoot and clear cache
- Open chat B
- Click on link to chat A

## Expected Result:

There is only one call to open report (or 2 in dev mode)

## Actual Result:

There are 2 calls to open report (or 4 in dev mode)

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

This is the network tab after clicking on a comment link:

<img width="613" alt="image" src="https://github.com/user-attachments/assets/fcdb609c-24fc-414c-adf4-83c4ee9ed254">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by pecanoro** [comment]
Hmm, we need payment here for @sobitneupane. Since it was only the review, we can do $125.

**Comment by anmurali** [comment]
**Payment summary**

- [ ] $125 approved for @sobitneupane on New Dot

**Comment by garrettmknight** [comment]
$125 approved for @sobitneupane
