### ISSUE TITLE
mWeb/Safari - Group chat - Photo upload options not displayed when tapped on upload photo menu

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47896]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4887343
**Email or phone of affected tester (no customers):** applausetester+ck822@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions:

1. User has created new account
2. User has created group chat with few users with custom avatar & group name

Steps:

1. Navigate to staging.new.expensify.com
2. Open the created group chat
3. Click on the header of the conversation
4. Click on the avatar
5. Click on Upload photo menu

## Expected Result:
Photo upload options (Photo Library, take photo & Choose file) should open & user able to change group avatar

## Actual Result:
Photo upload options not displayed when tapped on upload photo menu in group chat details page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4ba29d1c-e791-492e-b45f-1ab0eb9c1ad1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
Production - works well

https://github.com/user-attachments/assets/e33797fb-23d4-4098-ae55-ccfe34b17fd2

**Comment by ChavdaSachin** [comment]
This issue is similar to [This Issue](https://github.com/Expensify/App/issues/47876) and was introduced after [This pr](https://github.com/Expensify/App/pull/47341).

**Comment by techievivek** [comment]
I see that a revert PR is already in progress. Let me check with the team to see if we can proceed with the merge and do a cherry-pick here.

**Comment by techievivek** [comment]
Let me discuss with @arosiclair to see what would be best here.

**Comment by arosiclair** [comment]
[Fixed by revert](https://github.com/Expensify/App/pull/47882#issuecomment-2307264021)
