### ISSUE TITLE
QBO - Existing tags are not replaced with imported tags after connecting to QBO

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47901]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settiings > Tags.
3. Add a few tags.
4. Go to Accounting
5. Connect to QBO.
6. Wait for sync to complete.
7. Go to Tags.

## Expected Result:
The previously added tags will be replaced with tags from QBO.

## Actual Result:
The previously added tags is added alongside with tags from QBO.
Regular tags become multi tags after connecting to QBO.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/58a09261-63e7-4538-a928-b1e46804c81e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
I'll test this in both NewDot and OldDot to check where the issue lies.

**Comment by RachCHopkins** [comment]
I get the same result in NewDot, but flicking over to OldDot, it looks like we are allowing appending

![image](https://github.com/user-attachments/assets/0f457a02-e2e2-414e-b261-54aa0fc67ffa)

I also set up a Collect workspace in OldDot directly and got the same result. 

![image](https://github.com/user-attachments/assets/4e3bd3a6-bed2-4234-b852-314ba58a34e8)

**Comment by RachCHopkins** [comment]
This is working as intended!
