### ISSUE TITLE
#admins room - Typo in upgrade system message, "Expore" instead of "Explore"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exploratory around https://expensify.testrail.io/index.php?/tests/view/4887622
**Email or phone of affected tester (no customers):** applausetester+ck822@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a Collect workspace
3. Navigate to Workspace settings > More Features
4. Enable "Report Fields"
5. Click on the upgrade button
6. Go back to Workspace listing page
7. Tap the 3-dot menu >> select go to #admins room
8. Observe the upgraded system messages

## Expected Result:
No grammer errors shown in system message. Word should be "Explore" instead of "Expore"

## Actual Result:
Describe what actually happenedMessage says "Expore the additional upgraded workspace features here".

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![Bug6579910_1724383992544!IMG_5137](https://github.com/user-attachments/assets/b3e09f57-7a4a-43c3-a3e9-ac622d089b0d)

https://github.com/user-attachments/assets/c7cf8419-46a6-43c1-8136-fc291797da6b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@lschurr   FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
BE Issue

**Comment by NJ-2020** [comment]
BE issue
![Screenshot 2024-08-23 at 01 31 10](https://github.com/user-attachments/assets/274b93cd-0cca-4734-bd81-c2d5cfead117)

**Comment by lschurr** [comment]
This seems like a copy issue - Is this something @Expensify/design can fix?

**Comment by shawnborton** [comment]
I think it would be easier to run it through the normal bug process, as we don't push too much code to NewDot these days.

**Comment by lschurr** [comment]
Cool, so I think I'll add Internal and Hot Pick since it's a BE issue.

**Comment by trjExpensify** [comment]
@jamesdeanexpensify can probably take care of this. =D

**Comment by lschurr** [comment]
Assigning to you James! Lemme know if you're not able to take this one

**Comment by jamesdeanexpensify** [comment]
Created a PR to fix ^^

**Comment by trjExpensify** [comment]
Dope, Auth PR deployed to prod - closing!
