### ISSUE TITLE
[HOLD for payment 2024-10-04][$250] Dupe detect - Invited user is not able to see the receipt placeholder on the confirmation page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47903]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team 

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace.
3. Submit two same expenses to the workspace chat.
4. Go to transaction thread (any).
5. Click Review duplicates > Keep this one (any).
6. Proceed to confirmation page.
7. Note that there is a receipt placeholder on the confirmation page.
8. As another user, invite the current user to a workspace.
9. As the invited user, go to workspace chat.
10. Repeat Step 3 to 6.
11. Notet hat there is no receipt placeholder on the confirmation page.

## Expected Result:
In Step 11, the invited user should be able to see the receipt placeholder on the confirmation page.

## Actual Result:
In Step 11, the invited user is unable to see the receipt placeholder on the confirmation page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d71a42cb-0a61-4662-9bc6-7ac4b61b8d20

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01741cd4c1fe7a4231</li>
        <li>Upwork Job ID: 1828132802801480968</li>
        <li>Last Price Increase: 2024-08-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by iwiznia** [comment]
> Update logic shouldShowReceiptEmptyState here

Let's make this a method that we use in both places instead of duplicating the logic.

> Calculate isRequestor based on currentUserPersonalDetails and parentReportAction

I see your code has `parentReportAction?.actorAccountID` in what case there's no parentReportAction and how will we determine who is the requestor in that case? Also what exactly is this parent report action? What type is it? When is it added? Are we sure it will match the requestor of the report?

**Comment by zanyrenney** [comment]
I am heading OOO so please reapply the bug label if this needs payment i the next 7 days, otherwise i'll pay on return!

**Comment by roryabraham** [comment]
Dupe detection is still behind a beta. Pretty certain this doesn't need to be a deploy blocker, but I'm going to try and check how many people are on the beta

**Comment by roryabraham** [comment]
Confirmed, we can demote this:

<img width="640" alt="image" src="https://github.com/user-attachments/assets/4a456d40-ab0d-4dde-9fb1-e30eab370d9d">

**Comment by allroundexperts** [comment]
@daledah's [proposal](https://github.com/Expensify/App/issues/47903#issuecomment-2306618219) has the correct RCA and the proposed solution seems fine as well. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by roryabraham** [comment]
The PR for this [was deployed to prod on 2024-09-27](https://github.com/Expensify/App/pull/48622#issuecomment-2379771530). Setting payout timer manually.

_side-note:_ working on fixing the automation in https://github.com/Expensify/App/issues/49963

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
