### ISSUE TITLE
Travel - OD opens instead of the Travel page for the first interaction with "Book travel"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47915]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4887114&group_by=cases:section_id&group_order=asc&group_id=314227
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. OD: Navigate to https://staging.expensify.com/
2. OD: Log in with a new expensifail account
3. OD: Navigate to Srttings - Workspaces - Group
4. OD: Create a Control workspace
5. OD: Open Chrome console
6. OD: Paste and run "NVP.set('travelSettings', {'testAccount': true});"
7. OD: Navigate to Workspace settings - Overview - Edit address
8. OD: Set the following Company Address "548 Market St San Francisco, CA 94104, United States"
9. ND: Navigate to https://staging.new.expensify.com/
10. ND: Log in with the same expensifail account
11. ND: Navigate to FAB - Book travel
12. Click on the "Book travel" button
13. Check the TOS and click on the "Continue" button

## Expected Result:
I should be navigated to the Travel URL (staging.travel.expensify.com)

## Actual Result:
OD opens instead of the Travel page for the first interaction with "Book travel". Travel URL starts loading, but I'm landing in OD. It works as expected for the second time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cd85f09d-cb8b-4b08-95a4-779a0469e1c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-travel

**Comment by srikarparsi** [comment]
This looks like a backend bug, the url redirects, removing the deployblockercash label.

**Comment by stitesExpensify** [comment]
This is most likely related to https://github.com/Expensify/Expensify/issues/413171 CC @justinpersaud

**Comment by justinpersaud** [comment]
Hmm yeah I'm going to turn that off for now until Spotnana gets back to me with more info

**Comment by justinpersaud** [comment]
Turned it off. Should be all good now.

**Comment by srikarparsi** [comment]
Thanks man
