### ISSUE TITLE
[$250] Workspace - Role changed to admin member can't access compose box in workspace chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47919]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** biruknew45+171@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to [https://staging.new.expensify.com/]
2. As User A, create a workspace and add User B
3. Navigate to the workspace chat
4. Click on the header and then "Settings."
5. Click on the "Who Can Post" settings
6. Change it to "Admin Only."
7. Go to the workspace settings
8. Change User B's role to admin
9. Observe the behavior as User B
10. Go to the workspace settings
11. Change User B's role to "Member."
12. Observe the behavior as User B

## Expected Result:
After changing the member's role to admin, the member should be able to post immediately.
The compose box and permission message should update consistently based on role and "Who Can Post" settings. after reverting the member's role to "Member," the compose box should be hidden again, preventing the member from attempting to send messages

## Actual Result:
After changing the member's role to admin, the member cannot post. the compose box and permission message disappear and reappear inconsistently then the compose box remains visible even after reverting the member's role to "Member," but sending a message results in an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/30438e8b-9992-4d7e-a8a0-529295cf4592

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1f02627a154bb67</li>
        <li>Upwork Job ID: 1828876093361855716</li>
        <li>Last Price Increase: 2024-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Contributor | 103786652</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @daledah</details>

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by aldo-expensify** [comment]
Oops, I messed up and removed and added again @allgandalf , not sure what happened with the upwork job when I did that 😬

**Comment by abekkala** [comment]
Deployed to Production Sept 12

### PAYMENT SUMMARY: 

Fix: @daledah - I was unable to find you in Upwork https://github.com/Expensify/App/issues/47919#issuecomment-2325246229
PR Review: @allgandalf [$250] [Offer Link](https://www.upwork.com/nx/wm/offer/103786652)

**Comment by abekkala** [comment]
@allgandalf It is not completed yet. 

@daledah has still not responded for my request of their upwork profile link. 
I've been unable to find their profile to send payment offer.

**Comment by abekkala** [comment]
@daledah [OFFER](https://www.upwork.com/nx/wm/offer/104235634)

**Comment by abekkala** [comment]
@daledah payment sent and contract ended - thank you! 🎉
