### ISSUE TITLE
Hold – Red dot disappear and reappear when open held report on employee side

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4889112&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+workspaceemployee162@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
1. Login as the owner of the workspace> Create a workspace
2. Invite the approver and employee
3. Navigate to more features> Enable "workflows"
4. On the "Workflow" editor - enable "Add Approvals"
5. Set the Approver account as the Approver
Steps:
1. As employee submit two expenses in workspace chat ( expense A and expense B)
2. As approver, put expense A on Hold
3. As approver, approve just the pending amount
4. As employee, navigate to workspace chat> Take a look at held expense

## Expected Result:
Red dot should be visible on expense preview on employee side

## Actual Result:
There is no red dot on held expense until employee navigate to transaction thread and go back to expense preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d63cc6d0-3f35-4f14-978e-cdc363f4438b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
Thanks @gijoe0295 - closing!
