### ISSUE TITLE
[Awaiting Payment 7th Sept] [$250] Add the modal prompts back to locked toggles in More features

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#47912]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C02NK2DQWUX/p1723775264453099?thread_ts=1723724132.692329&cid=C02NK2DQWUX

## Action Performed:
1. Enable QBO 
2. Go to More features
3. Click on a locked toggle (i.e `Tags`)

## Expected Result:
A modal should appear explaining why it's locked. 

## Actual Result:
No modal appears, the cursor just turns to 🚫 on hover. 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e66382ea-9b56-4428-899a-5d0675f87e14">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0126e97d02490a2603</li>
        <li>Upwork Job ID: 1827065354673239304</li>
        <li>Last Price Increase: 2024-08-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
PR is here: https://github.com/Expensify/App/pull/47533

**Comment by hungvu193** [comment]
> PR is here: https://github.com/Expensify/App/pull/47533

Can you add external label so we can get a C+ here? 😄

**Comment by marcaaron** [comment]
Thanks for the issue @trjExpensify 🙇

**Comment by codewaseem** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Modal doesn't appear when clicking on the locked toggle switch.

### What is the root cause of that problem?
The `disabledAction` callback prop for the items is missing. For example here:
https://github.com/Expensify/App/blob/f5e63543cbdea0ffcc0e5bf201f8f2e9645582c6/src/pages/workspace/WorkspaceMoreFeaturesPage.tsx#L195-L213

### What changes do you think we should make in order to solve the problem?
Adding an appropriate `disabledAction` callback function to the list will solve this problem. For example:
```
{
            icon: Illustrations.FolderOpen,
            titleTranslationKey: 'workspace.moreFeatures.categories.title',
            subtitleTranslationKey: 'workspace.moreFeatures.categories.subtitle',
            isActive: policy?.areCategoriesEnabled ?? false,
            disabled: hasAccountingConnection,
            pendingAction: policy?.pendingFields?.areCategoriesEnabled,
            action: (isEnabled: boolean) => {
                if (!policyID) {
                    return;
                }
                if (hasAccountingConnection) {
                    setIsOrganizeWarningModalOpen(true);
                    return;
                }
                Category.enablePolicyCategories(policyID, isEnabled);
            },
            disabledAction: () => {
                setIsOrganizeWarningModalOpen(true);
            },
        }
```

#### Result
<img width="1058" alt="Screenshot 2024-08-24 at 01 42 02" src="https://github.com/user-attachments/assets/d20b1ea3-72cf-49f6-8ed2-15ac53723760">


### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment]
Updated labels, payout will be due on Sept 7th after hitting prod 3 days ago.

**Comment by trjExpensify** [comment]
Waiting out the regression period, Melv.

**Comment by trjExpensify** [comment]
Payment is due tomorrow, so doing this today. 

- $250 to @hungvu193 for the fix
- $250 to @thesahindia for the C+ review

Feel free to request, closing!

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
