### ISSUE TITLE
[$250]  Invoice - Category field does not show up on confirmation page after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47922]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4888644
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create two new workspaces
3. Log out and log in
4. Go to FAB > Send invoice > Proceed to confirmation page
5. Click Show more
6. Note that Category field is present
7. Click Send from and select the second workspace
8. Click Show more and note that Category field is absent
9. Go to workspace settings of the second workspace in Step 8 > Categories
10. Repeat Step 4 to 5 with the second workspace in Step 8
11. Note that Category field is present after visiting Categories settings page

## Expected Result:
In Step 8, after relogin, the Category field should be present on the confirmation page when the sender is the second workspace

## Actual Result:
In Step 8, after relogin, the Category field is absent on the confirmation page when the sender is the second workspace.
In Step 11, the Category field only reappears after Categories settings page is visited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7ac7430e-32ac-47ef-bb1a-81755bb5ab92

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831332316106024173</li>
        <li>Upwork Job ID: 1831332316106024173</li>
        <li>Last Price Increase: 2024-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103920522</li>
<li>Nodebrute | Contributor | 103920525</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by lanitochka17** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
I'll open it up to proposals and I've filled this bug in the invoicing initiative. cc @davidcardoza

**Comment by davidcardoza** [comment]
@JmillsExpensify Should the help wanted label addition assigned a C+?

**Comment by JmillsExpensify** [comment]
That should do it.

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: $250 @Nodebrute 
 - Reviewer: $250 @rayane-djouah

**Comment by JmillsExpensify** [comment]
All Contributors paid via Upwork.

**Comment by JmillsExpensify** [comment]
Not yet, let me add the regression test request first and then I can close.

**Comment by JmillsExpensify** [comment]
All done.
