### ISSUE TITLE
[HOLD for payment 2024-09-06][Search v2.1] Add Filters button to Search page

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#47932]
We should add the Filters button to the Search page header so users can navigate to the Filters page

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by dubielzyk-expensify** [comment]
Looks good on desktop:
![CleanShot 2024-08-26 at 14 47 55@2x](https://github.com/user-attachments/assets/adec0db9-2839-4c72-b1e2-8bc354ad191c)

This happens on mobile though:
You tap the filter button and you get a brief flash of the most recent chat before the filter screen appears:

https://github.com/user-attachments/assets/f244d7dd-b7ec-4145-bf35-3d66d6d5ea1e

cc @Expensify/design

**Comment by shawnborton** [comment]
Good catch. 

Also is it just me, or are the two button background colors different from one another? 
![CleanShot 2024-08-26 at 07 11 18@2x](https://github.com/user-attachments/assets/6e59e5cc-bc35-4644-ba1c-66baeb5be399)

**Comment by shawnborton** [comment]
(Actually we should probably leave this feedback in the PR itself)

**Comment by luacmartins** [comment]
Hahah yea, leaving the comments on the PR would be great. The PR was merged earlier today. 

>You tap the filter button and you get a brief flash of the most recent chat before the filter screen appears:

I couldn't reproduce this locally. I'll try again in staging once this PR is deployed

>Also is it just me, or are the two button background colors different from one another?

I see both with `background-color: rgb(230, 225, 218)` so they seem to match.

**Comment by dubielzyk-expensify** [comment]
Yeah, even when I overlay them they seem to be the same color 
![CleanShot 2024-09-02 at 11 00 29@2x](https://github.com/user-attachments/assets/74fdbb52-a241-4d90-8158-8bb443ba2b48)

**Comment by luacmartins** [comment]
Bump for payment

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue, internal PR with no testing so the rate is $125

 - Contributor:  N/A internal 
 - Contributor+: @rayane-djouah $125 via Upwork -- I extended an offer to you, please accept when you get a chance! https://www.upwork.com/nx/wm/offer/103853895
 
 Upwork job is here: https://www.upwork.com/jobs/~021832241147302028347

**Comment by stephanieelliott** [comment]
Ah ok, thanks for the correction @rayane-djouah. I added an additional $125 milestone to the job, so the entire job should be $250. Both have been paid!
