### ISSUE TITLE
[Awaiting Payment 6th September] ApproveMoneyRequest is failing when there is no nextReceiver

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#47936]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/393839
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1724422284086239?thread_ts=1724364263.668779&cid=C05LX9D6E07

## Action Performed:
1. Create a Control workspace on OldDot.
2. Enable Advanced Approval 
3. Invite a submitter and an approver, we'll call them Approver A
4. Set the submitter's submitsTo as Approver A
5. As the submitter, submit an expense to the workspace chat.
6. As the Admin, change the Submitter’s submitsTo to yourself, verify you have no forwardsTo set
7. As Approver A, log in and open the report chat.

## Expected Result:
Approver A should be able to see the 'Approve' button and tapping it should final approve the report.

## Actual Result:
- In the ApproveMoneyRequest we are now building the approvalChain based on the submitter
- That is Admin in this case.
- This means Approver A is not flagged as finalApprover (as they should be)
- And that leads to check if the nextReceiver is the current manager (we should have never got here)
- that fails as there is no nextReceiver hence the 500 error

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by Beamanator** [comment]
We agreed I'd take this over

**Comment by Beamanator** [comment]
PR is up!

**Comment by trjExpensify** [comment]
Weird, why didn't the `Reviewing` label get added.

**Comment by Beamanator** [comment]
Ya weird, not sure :D PR shoulllld be merged tomorrow 🙏

**Comment by Beamanator** [comment]
Ooh it was merged just now!!

**Comment by Beamanator** [comment]
Still we're working on https://github.com/Expensify/App/pull/47926 getting merged for this

**Comment by trjExpensify** [comment]
Assigning @ishpaul777 to this issue for the PR review. Hit prod 4 days ago, updated the labels to reflect the hold. :)

**Comment by Beamanator** [comment]
Lol updated to September 6 - i assume that's what you meant @trjExpensify ? 😅

**Comment by trjExpensify** [comment]
Yep!

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @ishpaul777 for the C+ review 

Offer sent!

**Comment by trjExpensify** [comment]
Paid, closing!
