### ISSUE TITLE
[Clean up] Update the OpenPaymentsPage command to return bank details and card details from Auth

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#47944]
### Problem

We are massaging the response data for the `OpenPaymentsPage` in Web. We end up sending the card details and bank account details in a different format than in other Auth commands, which leads to confusion. Example is here https://github.com/Expensify/App/issues/47239 where the allowDebit, bank account `type` and accountNumber were missing in response from the `AcceptACHContractForBankAccount` command

### Solution

Start returning the card and bank account details for OpenPaymentsPage from Auth so we can use the same methods as we do in other commands like in [OpenCardDetailsPage](https://github.com/Expensify/Auth/blob/188818dea461b1e64e56545c29067f69ed91139f/auth/command/OpenCardDetailsPage.cpp#L41)

**Comment by mountiny** [comment]
This is just a polish

**Comment by mountiny** [comment]
Not focusin gon this yet as its just polish

**Comment by mountiny** [comment]
Havent got around yet

**Comment by mountiny** [comment]
@nkuoch not sure now, but is this fully completed? Or do we have one PR left?

**Comment by nkuoch** [comment]
I need to do 1 last cleanup to remove the transition code. OOO this week. So will do it on tuesday

**Comment by mountiny** [comment]
Thank you for clarifying

**Comment by nkuoch** [comment]
Ah no, I also need to migrate fundList, userWallet and cardList formatting auth side.

On it!

**Comment by mountiny** [comment]
le legende

**Comment by mountiny** [comment]
this is done I believe
