### ISSUE TITLE
Onboarding steps aren't populating in DM or Conci after 'Track' converts to workspace via 'Submit'

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#47942]
**Version Number:** v9.0.23-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Caught during [CVP testing](https://github.com/Expensify/Expensify/issues/421286)
**Email or phone of affected tester (no customers):** [criticalviralpath@gmail.com](mailto:criticalviralpath@gmail.com) / yuwenis+bob1@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @garrettmknight / @yuwenmemon 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721834010589119

## Action Performed:
1. Create a new account
2. Select 'Track' as the intent
3. Click the FAB + Track expense
4. Create a manual expense or scan receipt
5. Select 'Submit' as the intent in the DM
6. Submit to another email - User B
7. Login as User B
8. Navigate to workspace chat with GBR
9. Click 'Pay via Expensify' > Business bank account
10. Connect bank account and pay

## Expected Result:
- User B should get onboarding steps via Concierge or DM to setup their workspace

## Actual Result:
- No DM and no setup steps from Concierge

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1438" alt="Screenshot 2024-08-23 at 2 52 20 PM" src="https://github.com/user-attachments/assets/1236cc30-3f12-4b2e-933a-ba67381c3a7d">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
cc @deetergp

**Comment by kevinksullivan** [comment]
asking about where this fits here

https://expensify.slack.com/archives/C07HPDRELLD/p1724708270013919

**Comment by kevinksullivan** [comment]
closing per that convo ^
