### ISSUE TITLE
[hold for payment 2024-09-26] [$250] iOS - Expense - App crash when clicking on the link settings/workspaces/:policyID/accounting/quic

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47946]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47696
**Email or phone of affected tester (no customers):** applausetester+23084alsn@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to [www.staging.chat.expensify.com](http://www.staging.chat.expensify.com/)
2. Workspace is connected to QBO
3. Go settings/workspaces/:policyID/accounting/quickbooks-online/export/out-of-pocket-expense/account-select

## Expected Result:
Verify list empty content is shown if no account is connected

## Actual Result:
App crash when clicking on the link: settings/workspaces/:policyID/accounting/quickbooks-online/export/out-of-pocket-expense/account-select

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[2308_1.txt](https://github.com/user-attachments/files/16733301/2308_1.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/9bbbbc9f-b4ff-41aa-a547-8ed45da8a9dd

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102861cb1eeae8b58</li>
        <li>Upwork Job ID: 1828133199515812262</li>
        <li>Last Price Increase: 2024-08-26</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 103743156</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by brunovjk** [comment]
@Nodebrute, @daledah, did you use personal QBO accounts for testing?

**Comment by brunovjk** [comment]
Thank you @daledah. I'm trying to register one, there is no support in my country now, I'll review the proposals as soon as possible.

**Comment by brunovjk** [comment]
**Update**: Same as above. I asked for help with credentials on slack.

**Comment by brunovjk** [comment]
Excuse me @dukenv0307, would you mind taking this isse? I don't have QBO credentials yet, I believe this was a DB where you are the original C+? Thanks.

**Comment by brunovjk** [comment]
Thank you :D

**Comment by deetergp** [comment]
I think the automation broke on this one. The PR has been reviewed, merged, and is currently out on production.

**Comment by joekaufmanexpensify** [comment]
Yep, this is due for payment now.

**Comment by joekaufmanexpensify** [comment]
@dukenv0307 seems like this was a DB from a prior issue where you were C+, so thinking payment for you is not required here. Please let me know if you think that is not correct!

**Comment by joekaufmanexpensify** [comment]
If that is correct, then only payment here is $250 to @daledah for PR via Upwork.

**Comment by joekaufmanexpensify** [comment]
@daledah offer for $250 sent!

**Comment by joekaufmanexpensify** [comment]
Got it, sounds good. TY for confirming!

**Comment by joekaufmanexpensify** [comment]
I updated the [payment summary](https://github.com/Expensify/App/issues/47946#issuecomment-2377972066) to reflect that you're due payment too.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment!

**Comment by joekaufmanexpensify** [comment]
@daledah $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
@dukenv0307 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set, TY everyone!
