### ISSUE TITLE
 "Track Expense" option not displayed in global create menu

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47968]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724258152954719

## Action Performed:
1. Go to staging.new.expensify.com
2. Click global create menu and observe

## Expected Result:
Track expense option displayed
## Actual Result:
Track expense option not displayed

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image](https://github.com/user-attachments/assets/af61044c-6480-4049-8eb7-6750e6828bf1)
![Snip - (18) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/16cfa16b-1e48-4982-be42-b8790fffdb8c)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
@thienlnam I'm assigning this over to you as we discussed in [this thread](https://expensify.slack.com/archives/C03TME82F/p1724271452872499?thread_ts=1724246247.102739&cid=C03TME82F). What we should ideally do is: 
1. Not require that the selfDM be there locally in order to track an expense
2. Update the back-end track expense flow to properly handle sending back the selfDM reportID, just like when you start a chat with someone who you already have a chat with, but don't have the reportID locally for

**Comment by thienlnam** [comment]
Been working on some related issues which should help with the availability of the self-DM
- https://github.com/Expensify/Expensify/issues/423780
- https://github.com/Expensify/Expensify/issues/395534

Also started a thread [here](https://expensify.slack.com/archives/C03TQ48KC/p1724796910566579), I think this is revealing some issue we have with the Self-DM not always being available that we should address first

**Comment by thienlnam** [comment]
It looks like the above PRs should have fixed this issue from coming up, holding to see if this is resolved as well https://github.com/Expensify/App/issues/42235

**Comment by thienlnam** [comment]
Okay, looks like this shouldn't be a problem anymore with the latest fixes from above - going to close this out for now
