### ISSUE TITLE
clicking a link shared leads to Hmm not there.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zanyrenney 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724426838420919

## Action Performed:

1. Get link shared in DM by member on same workspace
2. Click link to room that you have never joined previously (Link tried: https://new.expensify.com//r/5944613809417511/9109420761369351202)

## Expected Result:
Link opens without any issue
## Actual Result:
Link leads to Hmm not there
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Google Chrome 2024-08-23 16 24 07](https://github.com/user-attachments/assets/a1d5f4f2-1aa7-4bb6-9553-2935c815008a)

https://github.com/user-attachments/assets/2793ad8c-3e49-4c09-9e5c-63cc81b57417

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by OfstadC** [comment]
Testing this morning

**Comment by OfstadC** [comment]
https://expensify.slack.com/archives/C049HHMV9SM/p1724783972063829?thread_ts=1724426838.420919&cid=C049HHMV9SM

**Comment by OfstadC** [comment]
@zanyrenney When you experienced this, did you have access to the room (link) that you weren't able to open? I wasn't able to reproduce with a room link I had access to

**Comment by zanyrenney** [comment]
reopening as still experiencing this:
![2024-09-03_18-30-25 (1)](https://github.com/user-attachments/assets/c5116305-32a0-4129-9b39-de92c2caf5fa)

steps taken:
1. log in to zany@expensify.com on new Expensify
2. click the link which is part of workspace you are within 
3. experience hmm its not there page

**Comment by jasperhuangg** [comment]
Closing via [this](https://expensify.slack.com/archives/C036QM0SLJK/p1725585723018059?thread_ts=1725541996.982329&cid=C036QM0SLJK)
