### ISSUE TITLE
[$250] Empty state list view does not use 400px as the width of the inner "modal" area

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47967]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724433592521089

## Action Performed:

1. Go to staging.new.expensify.com
2. Navigate to empty pages in Search or empty pages in the workspace editor like Tags

## Expected Result:
Inner modal portion is set to 400px
## Actual Result:
Inner modal portion is not set to 400px
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-08-23 at 13 20 10@2x](https://github.com/user-attachments/assets/7b2b5d94-17e1-4d0f-84e0-69f4a75975b5)

![Screenshot (13)](https://github.com/user-attachments/assets/6b932f86-f857-4eae-9b70-713c81d36a69)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ddff86d7195f923e</li>
        <li>Upwork Job ID: 1828312045118952549</li>
        <li>Last Price Increase: 2024-08-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by greg-schroeder** [comment]
Next up is proposal review

**Comment by filip-solecki** [comment]
Sure, I'll do it today

**Comment by greg-schroeder** [comment]
Deployed to prod 9/2

**Comment by greg-schroeder** [comment]
Offer sent to @mkhutornyi for reviewer role ($250)
Contributor role was software mansion, so no payment required there.
