### ISSUE TITLE
Android - Chat - Screen blinks when open Add attachment option

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47972]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** gocemate+a1063@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open NewDot android app
2. Go to any chat
3. Tap "+"> Add attachment

## Expected Result:
Screen should not blink

## Actual Result:
Screen on chat blinks when open Add attachment option

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5ee73186-829c-422e-954a-fd8aa567909d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment]
Retest on latest build 9.0.24-2 

https://github.com/user-attachments/assets/b6c2d8ee-abf8-4cbe-ab27-480ea45a4dfa

**Comment by marcaaron** [comment]
Reverting the above PR to see if I can still repro after. Was able to repro on BrowserStack device and then confirmed it looks not janky on production.

**Comment by marcaaron** [comment]
Fixed
