### ISSUE TITLE
Tasks-Error message when assigning a task to a non-existent user

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47970]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4884623
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to any conversation
2. Tap + button > Assign Task > Enter title and navigate to next page
2. Tap on Assignee
3. Enter a email that doesn't have a NewDot account yet
4. Create the task

## Expected Result:
The users should be able to assign the task to an email address not yet associated with a NewDot account.

## Actual Result:
An error message is displayed when assigning a task to a non-existent user.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/26775bd8-574c-4ce6-9e6c-4afa1b1c7b50

![Bug6580916_1724464812093!assign_task_to_not_existing_user_mweb](https://github.com/user-attachments/assets/938955b9-5ff5-493b-847a-866ef9800e67)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NJ-2020** [comment]
BE issue
![Screenshot 2024-08-25 at 00 43 45](https://github.com/user-attachments/assets/7842eaf1-594b-4bbf-9b09-77b3724391e8)

**Comment by jliexpensify** [comment]
Thanks @NJ-2020 - I wonder why an engineer didn't get assigned since this is a `deploy blocker`. Going to work out which project this is and post in the corresponding channel.

**Comment by jliexpensify** [comment]
@thienlnam going to assign this one to you, as it's a Deploy Blocker and also to confirm behaviours:

- Can you assign a task to a user without a New Expensify account?

- If so, should we throw this [error](https://github.com/Expensify/App/issues/47970#issue-2484844711)?

**Comment by thienlnam** [comment]
Yeah you can assign a task to a user without an Expensify account. It should just create an account for them in the closed state - same with a chat.

**Comment by stitesExpensify** [comment]
Removing blocker label, we cp'd the fix ^
