### ISSUE TITLE
Sign up - no magic code is sent/account appears as deleted if someone starts a chat before account is created

### ISSUE THREAD

**Issue by CyberAndrii** [Expensify/App#47979]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.24-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** @CyberAndrii

## Action Performed:

1. User A: Go to staging.new.expensify.com
2. User A: Create a new account or log into an existing one
3. User A: Click "+" in the LHN then "Start chat"
4. User A: Enter an email of a non-existing user and open the chat
5. User B: Go to staging.new.expensify.com
6. User B: Enter the email from step 4 and click "Continue"

## Expected Result:

User B receives the magic code

## Actual Result:

User B never receives the magic code. Even when requested again

## Workaround:

Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
Add any screenshot/video evidence

[no magic code is sent.webm](https://github.com/user-attachments/assets/c65635a0-fd2c-48e5-9c83-9e38f46062aa)

When entering email of User B and clicking the "Continue" button without clicking the "Join" button:

[account is deleted.webm](https://github.com/user-attachments/assets/259c4487-9621-4409-a858-df2bae00c16d)

```
The account you are trying to use is deleted.
```

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CyberAndrii** [comment]
> Please report bugs or suggest features in the #expensify-open-source Slack channel, don't directly open issues in this repo!

@trjExpensify If only it was possible to join the Slack... See https://github.com/Expensify/App/pull/45804

**Comment by trjExpensify** [comment]
@m-natarajan can you take a look at this and create the bug if reproducible? Thanks!

**Comment by m-natarajan** [comment]
@trjExpensify User B asked to enter the magic code and I received it.

https://github.com/user-attachments/assets/968143da-e21b-4773-b2d9-627a9a347eb9

**Comment by trjExpensify** [comment]
Cool yeah, so that seems expected then. 

1. User B was invited to Expensify
2. They didn't click the link in the email which would have provided an unvalidated first session if they did
3. They navigated to new.expensify.com natively and entered their email address
4. They were prompted for a magic code to sign-in
5. They received the magic code on email, entered it, and validated the account
