### ISSUE TITLE
[P2P Distance] [$250] Distance-Rate field is not shown after selecting category in distance request in Gmail account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47981]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: Account has no workspace
1. Go to https://staging.new.expensify.com/home
2. Login with Gmail account
3. Go to self DM
4. Track a distance expense
5. Click Categorize it
6. Select a category
7. Proceed to the confirmation page

## Expected Result:
Rate field must be shown after selecting category in distance request.

## Actual Result:
Rate field is not shown after selecting a category in distance request with Gmail account.
In the expensive account, you can see the rate field in the confirmation page

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/288183eb-0ca4-4eab-9ee6-e7b46dc6164f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f50c3c1e81d64178</li>
        <li>Upwork Job ID: 1829309871698426984</li>
        <li>Last Price Increase: 2024-08-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by IuliiaHerets** [comment]
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kevinksullivan** [comment]
weird... We do pass the rate into the distance field after the expense is created. 

<img width="376" alt="image" src="https://github.com/user-attachments/assets/0778d4a9-56e7-40a5-8a57-ca37a896a1de">

**Comment by kevinksullivan** [comment]
but yeah, on a private domain email we keep them separate. So I do think we should keep them split. 

<img width="376" alt="image" src="https://github.com/user-attachments/assets/8864103c-e261-4330-a789-311e7c2dae1c">

**Comment by IuliiaHerets** [comment]
QA team found a similar issue: if we use a Gmail account, we cannot press the distance field after categorizing it.
Steps:

1. Go to https://staging.new.expensify.com/
2. Login with any Gmail account
3. Open self DM
4. Create a new distance track expense
5. Select Categorize it
6. Select any workspace
7. In the confirm page, cannot press the distance field.
Do we need to raise a separate issue?

https://github.com/user-attachments/assets/d7fde3ba-1aef-437c-9b1d-f965dfbb6fe3

**Comment by trjExpensify** [comment]
>but yeah, on a private domain email we keep them separate. So I do think we should keep them split.

The `Rate` field is behind the `p2pDistanceRequests` beta. I suspect that private domain account you tested is expensifail.com or something on the beta. 

So my first question @IuliiaHerets is whether the gmail account used is on that beta or not? 

CC: @neil-marcellini

**Comment by IuliiaHerets** [comment]
@trjExpensify Used Gmail account is not on the beta

**Comment by trjExpensify** [comment]
Cool, closing!
