### ISSUE TITLE
[$250] Remove the Expensify DM from onboarding

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#48021]
Proposal: Remove the Expensify DM from onboarding

Background — we wanted to test if putting tasks in the Expensify DM is more effective than putting the tasks in the Concierge chat. The original goal was to have a WhatsApp style DM that is used for education. Our design has evolved and we have not found the Expensify DM to be more effective than Concierge. Here is a [look at the data](https://docs.google.com/spreadsheets/d/1Is43frzWoKOg7G_igjMtqfsi98xLi1h_dP7Z_Q6BTHQ/edit?gid=2133187122#gid=2133187122):
- Expensify DM stats (413 users)
  - % of users who completed tasks: 25%
- Concierge stats (473 users)
  - % of users who completed tasks: 27%

Problem: We could continue to wait for more data but we see no reason it would change AND keeping the Expensify DM has costs:
1. We continue to find bugs with the Expensify DM, it costs us engineering time to maintain two flows and this specific DM.
2. It makes our onboarding/support materials inconsistent, thus leads to confusion internally and for users.

Solution: Remove the Expensify DM so all onboarding tasks live in Concierge going forward. As discussed in [this thread](https://expensify.slack.com/archives/C07HPDRELLD/p1724268366916889?thread_ts=1724189271.634559&cid=C07HPDRELLD), we will leave the Expensify DM in the accounts where it is but we will no longer be creating these DMs going forward. 

I'm going to work with @francoisl on this one as he implemented it originally. 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831465852515898823</li>
        <li>Upwork Job ID: 1831465852515898823</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by francoisl** [comment]
Almost done with frontend changes for this, but switching tasks to another issue for a second.

**Comment by francoisl** [comment]
Going to briefly mark this external to get a C+ assigned who can help review the PR.

**Comment by francoisl** [comment]
To clarify, we're not looking for proposals here - this will be handled internally.

**Comment by francoisl** [comment]
Everything is deployed here and there's [this issue](https://github.com/Expensify/App/issues/48641) for payment to @fedirjh, so I think we can close this.

**Comment by MinecraftEarthVillage** [comment]
> 下载 https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file 密码：changeme 在安装程序菜单中，选择“gcc”。

不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
