### ISSUE TITLE
[HOLD for Payment 2024-09-12][$62.50] Add new sub-header to More features page

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#48023]
# Problem
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1724257072288859?thread_ts=1724169468.543389&cid=C06ML6X0W9L), there are concerns that the current `More features` page on the workspace editor doesn't make it sufficiently clear that enabling a toggle often simply adds a feature to the workspace editor to configure the feature, rather than actually turning it on. This could impact feature adoption, or drive support volume. 

# Solution 
Add a new sub-header directly under `More features` header on this page of the workspace, that clarifies that toggling something on simply adds the feature to the workspace editor. 

Sub-header copy should be: `Use the toggles below to enable more features as you grow. Each feature will appear in the navigation menu for further customization.`

It should go directly under `More features`, similar to how the `Categories` page shown below has a sub-header. 

<img width="1510" alt="2024-08-26_15-06-06" src="https://github.com/user-attachments/assets/e077da98-8f43-4c39-a10b-53fd6a303410">

<img width="1510" alt="2024-08-26_15-06-06" src="https://github.com/user-attachments/assets/ba6f9642-df65-40f2-a992-295218ff61c7">

cc @heyjennahay @jamesdeanexpensify @JmillsExpensify @shawnborton @dannymcclain 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182dc1eaaa54e652c</li>
        <li>Upwork Job ID: 1828148191299361076</li>
        <li>Last Price Increase: 2024-08-26</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103742172</li>
<li>Krishna2323 | Contributor | 103742174</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Krishna2323</details>

**Comment by joekaufmanexpensify** [comment]
Adjusted price to $62.50, since this is a very, very minor change. Automation didn't work with Upwork, so adjusted the price manually there too

**Comment by dannymcclain** [comment]
Yes I think we should definitely do that! Option 2 all the way.

**Comment by shawnborton** [comment]
Option 2 does look nice, but I'm curious how we handle this text on other pages? Maybe we just don't have long copy on the other sections... but I think we should consider making them consistent?

**Comment by dannymcclain** [comment]
>but I'm curious how we handle this text on other pages? Maybe we just don't have long copy on the other sections... but I think we should consider making them consistent?

I hear you. The thing is, almost every page that currently has text like this is a table view that takes up the full width (so no max-width) and also has shorter copy. My thinking was the max-width looks much nicer here and might even look nicer on full-width views (just because the line length gets reaaaally long). But alternatively we could say that the text width should match the content width if we wanted to...

Anyways here's an example of a table view page with and without the max-width:
![image](https://github.com/user-attachments/assets/fb76b568-f8a4-44ae-8444-ff711acce791)

**Comment by shawnborton** [comment]
Totally, and to be fair, I actually like the max-width here to make the rows easier to scan, I'm just suggesting that we should add it to every workspace editor page and not just here. So let's do it everywhere?!

**Comment by dannymcclain** [comment]
LET'S GO

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $62.50 @Krishna2323 Upwork
- [ ] Contributor+: $62.50 @rayane-djouah Upwork

Upwork job is [here]().
