### ISSUE TITLE
Multiple Onyx updates when adding/removing workflows for policy.approvalMode

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#48027]
# Problem
When new advanced approval workflows are added and removed, there can be multiple onyx updates for `policy.approvalMode` when there should only be a single change to approval mode.

## Why this is important to solve?
Returning the correct onyx updates to the frontend will make the feature more stable.

# Solution
Look into the backend APIs and determine what the problem is, then fix it

cc @blazejkustra

**Comment by tgolen** [comment]
@blazejkustra I'm not able to reproduce this issue. When I add the first workflow, I only get a single update for approvalMode, and when I remove the last workflow, I only get a single update too.

Is there something I'm doing differently?

https://github.com/user-attachments/assets/8f533234-42e7-40d9-90c3-17389697469f

**Comment by blazejkustra** [comment]
Try updating the default workflow, I can update it reliably this way:

https://github.com/user-attachments/assets/310d392a-5630-43c3-bf84-bc8fbaec7be0

**Comment by blazejkustra** [comment]
Also check out [this](https://github.com/Expensify/App/issues/48095) bug, I think it's related.

**Comment by tgolen** [comment]
# Daily Update
- I created an [Auth PR](https://github.com/Expensify/Auth/pull/12290) for this yesterday

### Next Steps
- @marcochavezf Review and merge the PR

#### ETA
- Merged by Monday, Sep 2
- Deployed by Tuesday, Sep 3

**Comment by tgolen** [comment]
# Daily Update
- The [Auth PR](https://github.com/Expensify/Auth/pull/12290) was merged on Friday

### Next Steps
- Wait for it to be deployed

#### ETA
- Deploy should happen either today or tomorrow (it's a holiday today so I'm not sure if anyone will be deploying)

**Comment by tgolen** [comment]
# Daily Update
- The [Auth PR](https://github.com/Expensify/Auth/pull/12290) was deployed yesterday

### Next Steps
- Close this issue

cc @blazejkustra

**Comment by blazejkustra** [comment]
@tgolen I verified it locally, and it works perfectly now. Thanks!

**Comment by tgolen** [comment]
Great! Thanks for confirming.
