### ISSUE TITLE
[HOLD for payment 2024-09-17][Search v2.2] Update trip filters to All, Current and Past

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48020]
**Problem**
 - During implementation, we realized that we're basically just showing expense data as trip data. So we decided on an MVP showing the same Expense status filters, i.e. All, Drafts, Outstanding, Approved, and Paid.
 - While testing the Trips filter, we found it to be pretty confusing, because it's not really clear what a draft or outstanding trip is

**Solution**
Update the Trips status filters to `All`, `Current` and `Past`

- `All` is a list of all existing trips the user has access to
- `Current` is a list of upcoming and current trips based on the start and end dates for the trip
- `Past` is a list of all trips which end date are in the past

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by JmillsExpensify** [comment]
Also for clarity, I'm thinking we could use these icons for `all`, `current`, and `past`. Thoughts @shawnborton @dubielzyk-expensify @dannymcclain 

![image](https://github.com/user-attachments/assets/c4daa45f-0feb-4e6c-b490-daa8131062d4)

**Comment by shawnborton** [comment]
I think those work? Alternatively, we could consider making some kind of new icon that has a calendar and a checkmark or something for past? And then maybe just the calendar for current?

**Comment by JmillsExpensify** [comment]
That could work too!

**Comment by dannymcclain** [comment]
I think they're alright, but I'm truthfully not in love with them. Do you all think these work a little better? (Nothing new/custom, just some different choices from the system)

![CleanShot 2024-08-29 at 08 55 42@2x](https://github.com/user-attachments/assets/f8f251cc-713e-4e6d-bc43-057ca7e2124e)

**Comment by shawnborton** [comment]
I think I like those more than the others personally. Curious for Jason's thoughts too.

**Comment by JmillsExpensify** [comment]
Sounds great! I agree that those are better.

**Comment by dubielzyk-expensify** [comment]
Love em

**Comment by luacmartins** [comment]
PRs in review

**Comment by CortneyOfstad** [comment]
Thanks @luacmartins!

**Comment by CortneyOfstad** [comment]
@ikevin127 — I sent you a payment proposal [here](https://www.upwork.com/nx/wm/offer/104003450). Please let me know once you accept and I can get that paid ASAP. Thanks!

**Comment by ikevin127** [comment]
@CortneyOfstad Accepted, thank you!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@ikevin127 — paid $250 via Upwork
