### ISSUE TITLE
Message of changed currency to '#admins' chat, doesn't get translated

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48032]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724692352842239

## Action Performed:
1. Go to Settings
2. Change Language to "Spanish"
3. Create a new workspace
4. Go to profile of the workspace
5. Change default currency to to another value
6. Open the "#admins" chat.
## Expected Result:
The message is translated into Spanish
## Actual Result:
The message is still displayed in English
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/762743a3-ae1e-4ceb-8560-1361fad4c1af

https://github.com/user-attachments/assets/cebe3ac1-e954-4bc3-b8b9-60cc23775d9f

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Per [this internal discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1719419321011069) we're not prioritizing one-off translation issues at the moment, though we may in the future as #vip-vsb is reopened -- added labels for that. 

Also just a note @dukenv0307 I was under the impression that C+ can't request to be assigned to bugs tgey reported -- that was based on [this comment](https://github.com/Expensify/App/issues/46844#issuecomment-2275069885), but could be wrong
