### ISSUE TITLE
Video modal - Empty button in Welcome modal & two Learn more buttons in Track expense modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48049]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** anyanyanyanaynewnewnenwe2932@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new gmail account.
3. Go through the onboarding.
4. Note that there is a blank button.
5. Click Get started.
6. Click FAB > Track expense.
7. Note that there are two Learn more buttons.

## Expected Result:
In Step 4, there will not be a blank button in Welcome modal.
In Step 7, there will be only one Learn more button.

## Actual Result:
In Step 4, there is a blank button in Welcome modal.
In Step 7, there are two Learn more buttons.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6af23b54-9300-43ba-ae3b-a687c363cfe3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
PR is up, this was a bad merge conflict resolution from the RN upgrade PR I believe

**Comment by mountiny** [comment]
We can close this one now as there are no payments required

**Comment by joekaufmanexpensify** [comment]
Thanks Vit!
