### ISSUE TITLE
Onboarding-App returns to Expensify chat after renaming onboarding task more than once

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48056]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR:** https://github.com/Expensify/App/pull/47693
**Email or phone of affected tester (no customers):** htad26+jshdfjds@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Login with a new Gmail account
2. On the onboarding modal, select "Manage my team's expenses"
3. Finish the onboarding flow
4. Open the Expensify chat
5. Click on a task with a description. E.g "Set up categories"
6. Rename the task and click save
7. Again click on the task and rename it

## Expected Result:
The user stays in the onboarding task details page

## Actual Result:
The user is navigated back to the Expensify chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2f809283-79fa-4ac8-a323-870e36f0af13

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment]
We are deprecating the Expensify DM, so let's not worry about bugs in this flow ([Slack](https://expensify.slack.com/archives/C07HPDRELLD/p1725893323814609))
