### ISSUE TITLE
Search -Filter screen opens in background while another filter screen slides on from the right

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48059]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Search.
3. Tap filter button.
4. Tap View results.
5. Tap filter button again.

## Expected Result:
Filters screen will not open twice.

## Actual Result:
Filter screen opens in background while another filter screen slides on from the right.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/42c312d0-9ebf-4072-b764-d5af8ef2066a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by 289Adam289** [comment]
Hi! I am from SWM, an expert agency, and I'd like to work on this issue.

**Comment by luacmartins** [comment]
This is fixed in staging after the CP. Closing.
