### ISSUE TITLE
[$125] Improve developer experience around react-compiler

### ISSUE THREAD

**Issue by Kicu** [Expensify/App#48066]
**Version Number:**
**Reproducible in staging?:** - 
**Reproducible in production?:** - 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

This is purely a developer experience issue.

I have recently spent 1+ hours trying to fix an issue with react-compiler on one of my PRs. I think this may happen in future for more people and I wanted to add some tweaks to our code to improve this experience.

Here's what I would like to do:
 - I will update our readme (https://github.com/Expensify/App/blob/main/contributingGuides/REACT_COMPILER.md) with one more case of handling react-compiler related error
 - I will add a package.json script to run specifically this command on dev: `npm run react-compiler-healthcheck &> output.txt` ([npm run react-compiler-healthcheck &> output.txt](https://github.com/Expensify/App/blob/main/contributingGuides/REACT_COMPILER.md#how-can-i-check-what-exactly-prevents-file-from-successful-optimization-or-whether-my-fix-for-passing-react-compiler-actually-works))
 - instead of `output.txt` we would call this file something specific, for example `react-compiler-output.txt`
 - finally add `react-compiler-output.txt` to gitignore, so that a developer can easily keep running the same script and not worry about accidentally pushing it to upstream repo (which I have - of course - did by mistake 😅)

I can have a PR ready very soon with these

CC @kirillzyusko 

## Action Performed:
N/A

## Expected Result:
N/A

## Actual Result:
N/A

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014befe13a62da3c50</li>
        <li>Upwork Job ID: 1828579678211382500</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by mallenexpensify** [comment]
Don't think we need ya here @shawnborton , sorry. I added `NewFeature` to create an Upwork job for @rayane-djouah .

**Comment by mallenexpensify** [comment]
@rayane-djouah can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~014befe13a62da3c50

**Comment by mallenexpensify** [comment]
Contributor+: @rayane-djouah paid $125 via Upwork

Don't think a regression test is needed here, plz comment if anyone disagrees and I'll reopen. And/or, @Kicu , if documentation needs to be updated anywhere.  Thx
