### ISSUE TITLE
Workspace-Description in workspace greyout in offline without making any changes

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48076]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4895431
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- workspaces-- new workspace
3. Tap profile
4. Turn off mobile data

## Expected Result:
Description in workspace must not be greyout in offline without making any changes.

## Actual Result:
Description in workspace greyout in offline without making any changes.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2113f617-1c12-4cf3-b669-76ade2a5801e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Going to close this as not a blocker since this exists on prod and is being handled in https://github.com/Expensify/App/issues/47260
