### ISSUE TITLE
[$250] Expense - Banner shows "transaction pending" when there is no pending Ecard transaction

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48083]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**  applausetester+kh2508001@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.chat.expensify.com
2. Go to workspace chat
3. Submit a manual expense
4. Click on the expense preview

## Expected Result:
The banner will not show "Transaction pending. It may take a few days to post." because there is no pending Ecard transaction

## Actual Result:
The banner shows "Transaction pending. It may take a few days to post."

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1656780c-2f02-4b6b-a68e-74b077d70266

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dfc30aa1d4201062</li>
        <li>Upwork Job ID: 1828526591139483595</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 103709050</li>
<li>Nodebrute | Contributor | 103709053</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by luacmartins** [comment]
Likely a regression from https://github.com/Expensify/App/pull/47821 cc @grgia @dangrous

**Comment by luacmartins** [comment]
@Nodebrute are you available to work on a fix?

**Comment by luacmartins** [comment]
Cool, all yours then

**Comment by dangrous** [comment]
oh i think we already have a fix for this maybe? https://github.com/Expensify/App/pull/47941

We noticed this last week but hasn't been fully reviewed yet

**Comment by luacmartins** [comment]
@Nodebrute please hold on working on the PR as it seems like we already had a fix in place - https://github.com/Expensify/App/pull/47941

**Comment by luacmartins** [comment]
This is fixed in staging. Closing.
