### ISSUE TITLE
[Workspace Feeds] Ensure the card name has correct default

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#48092]
### Problem

When a new card is being issued, the card name should default to the card assignee name, so while this is a required field technically, but we should default to some name. 

### Solution

Per the design doc https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit#bookmark=id.dj4l9oe9nlb0

> We will provide a default name for physical cards, which will be “%firstName% 's card” (using primary login as fallback)

And email is there is no first name

![image](https://github.com/user-attachments/assets/dabef60d-867a-431c-a55f-8dad2a47c621)

Additionally, if the user gets to the confirmation page using Enter, the back button is focused. This means that using the next enter press, they will go back to the card name page. 

Lets autofocus the Confirm button when user gets to the confirmation page so they can create the card by pressing enter 

https://github.com/user-attachments/assets/066e0412-686e-40f0-9c95-3df04c8fc10b

**Comment by koko57** [comment]
I would like to work on this issue

**Comment by koko57** [comment]
PR ready for review https://github.com/Expensify/App/pull/48317

**Comment by mountiny** [comment]
Merged

**Comment by trjExpensify** [comment]
On prod, closing.
