### ISSUE TITLE
[Held requests] Workspace owes 0.00 is displayed on employee's LHN when partially approve report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48093]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4893676&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+workspaceemployee165@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
1. Login as the owner of the workspace
2. Invite the approver and employee to workspace
3. Navigate to more features> Enable "workflows"
4. On the "Workflow" editor - enable "Add Approvals"
5. Set the Approver account as the Approver
Steps:
1. As Employee submit 2 expenses into workspace chat
2. As Approver, put one of the requests on Hold
3. As Approver, partially approve the report
4. Take a look at LHN expense that is on hold from employee side

## Expected Result:
Correct amount should be displayed

## Actual Result:
Workspace owes 0.00 is displayed on employee's LHN when approver partially approve report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/43d9d140-7955-4f4b-b1c7-45a9d416e1fb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
Agree that this is internal. @robertjchen do we not already have an existing issue for this one?

**Comment by robertjchen** [comment]
Yes, I think we've addressed this a week ago- I'lll confirm

**Comment by robertjchen** [comment]
Adding to main issue update and handling this week

**Comment by robertjchen** [comment]
It appears a crucial Oynx update isn't making it to the employee after approval- should hopefully be a quick one, checking this out tomorrow.

**Comment by robertjchen** [comment]
Was able to reproduce this issue locally, working on a fix this week

**Comment by robertjchen** [comment]
In progress, should have a PR up by EOD tomorrow.

**Comment by robertjchen** [comment]
PR in review

**Comment by robertjchen** [comment]
BE PR merged and to be deployed later today

**Comment by robertjchen** [comment]
Testing this out- but still seeing the `0.00` on prod 🤔 I think there may still be a FE factor, we are now passing the correct `lastMessageText` back to the FE, which was called out [here](https://github.com/Expensify/App/issues/48093#issuecomment-2312925890), but for some reason the LHN isn't taking it up.

Will post a screen recording demonstrating this issue.

**Comment by robertjchen** [comment]
This appears to be resolved as of the latest changes. Once the latest message/report preview is loaded, the LHN takes on the correct held amount.

https://github.com/user-attachments/assets/8c23eb14-10d8-443b-bd57-be4d2ed190f7
