### ISSUE TITLE
Distance - Amount field is no longer grayed out after changing rate and then distance offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48111]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Track tax is enabled
- Workspace has at least two distance rates
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a distance expense
4. Go to transaction thread
5. Go offline
6. Click Rate
7. Select a different rate
8. Note that Amount field is grayed out
9. Click Distance
10. Change the distance and save it
11. Note that Amount field is no longer grayed out

## Expected Result:
Amount field should be grayed out after changing Distance offline

## Actual Result:
In Step 8, Amount field is grayed out after changing distance rate offline
In Step 11, Amount field is no longer grayed out after changing distance offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/61ae525b-a742-47bd-8d23-8b5b7f80ffa0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayes102** [comment]
not able to reproduce the issue

**Comment by trjExpensify** [comment]
>where we remove something offline, the empty field remains grayed out. 

Ordinarily when we remove something ("pending delete"), it's strikethrough and at 50% opacity. 

>this case is special because we do not remove the amount - it'll be calculated on the BE. Therefore, marking it as usual "removed" behavior will be misleading.

Agreed. 👍
