### ISSUE TITLE
Android - BNP - Initially at first place where cursor displayed unable to enter number

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48115]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4895545
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on 1:1 DM
3. Create a Submit expense
4. Open the expense
5. Tap amount
6. Try to enter a number where cursor is shown
7. Note user cannot enter number
8. Move the cursor to other digit
9. Now note user can enter number at all places

## Expected Result:
Initially at first place where cursor displayed must be able to enter number

## Actual Result:
Initially at first place where cursor displayed unable to enter number

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c73ef027-992e-40ae-9bb1-9ea53aa4e702

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by slafortune** [comment]
@lanitochka17 I am not able to recreate this.  Can you verify if any steps are missing?

https://github.com/user-attachments/assets/46227a79-e10c-490b-b518-7e400088c5cd

**Comment by lanitochka17** [comment]
@slafortune You have completed only 3 steps
Please check all steps specified in the issue

**Comment by slafortune** [comment]
Ah, sorry @lanitochka17 - I missed that this was when editing an amount.  The curser is at the end of the amount, where you are not able to enter a number in the third decimal place ever.  Since you are going back to the expense to edit it, I assume it would be the standard to select the number you want to edit or at the end so you are in the position to delete and reenter.  Do you think the curser should be set in a different position?

**Comment by slafortune** [comment]
Feel free to reopen if I've missed something, but the position on the cursor seems to be in the intended place for the action of editing.
