### ISSUE TITLE
Report with submit + close and no approvals is in the processing state

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48129]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** https://www.expensify.com/concierge/#/chat/13264620
**Slack conversation:** https://expensify.slack.com/archives/C041MSTR8J1/p1724729481646119?thread_ts=1724440636.400399&cid=C041MSTR8J1

## Action Performed:
1. Create workspace
2. Configure delayed submission to be toggled off (default)
3. Keep approvals toggled off (default)
4. Assign expensify card to yourself (you can use expensifail.com or cardtest.expensify.com)
5. Make a payment with the card from https://github.com/Expensify/Expensify/files/3974273/payButtons.html.zip
6. Wait a day or two

## Expected Result:
Report should move to closed state with no option to reimburse it, as it's a non-reimbursable expense. 

## Actual Result:
- Report stays in the processing state
- Report next steps prompt the approver to reimburse the report, even though there is nothing to pay back. 

## Platforms:
All platforms

## Screenshots/Videos

<img width="1163" alt="image" src="https://github.com/user-attachments/assets/ccbccedf-6503-4f48-bc97-d4f4ea7e49e2">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
Since this has to do with the transactions/report state I figure it needs to be internal. CC @grgia

**Comment by RachCHopkins** [comment]
Internal issue created - @grgia I've assigned it to you as an interim measure.

**Comment by RachCHopkins** [comment]
Making weekly since the internal issue is a Daily.

**Comment by RachCHopkins** [comment]
Bumped Georgia on the Internal E/E issue. @kevinksullivan do I also need to keep this E/App issue open?

**Comment by RachCHopkins** [comment]
E/E is complete. We can close this one.
