### ISSUE TITLE
[HOLD for payment 2024-09-18][$125] Upgrade mapbox and remove patch

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#48123]
This issue is just a tracker to upgrade mapbox and remove the patch we added in https://github.com/Expensify/App/pull/45289/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R102

Looks like the build issues are being address upstream in https://github.com/rnmapbox/maps/issues/3593 and we can upgrade to https://github.com/rnmapbox/maps/releases/tag/v10.1.30 and remove the patch.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed1b0e1397924f45</li>
        <li>Upwork Job ID: 1828535807455065976</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103729434</li>
<li>abzokhattab | Contributor | 103729436</li>
</ul></li>
    </ul>
</details>

**Comment by roryabraham** [comment]
For the sake of this proposal, let's lay out the test steps we'll follow to ensure that the new version works as expected

**Comment by suneox** [comment]
Still waiting @abzokhattab change PR status

**Comment by MrRefactor** [comment]
Could we also bump pod for `rnmapbox/maps`? 
CC: @abzokhattab @roryabraham

**Comment by roryabraham** [comment]
good catch @MrRefactor

**Comment by roryabraham** [comment]
Created https://github.com/Expensify/App/pull/48925 to clean that up

**Comment by roryabraham** [comment]
Sorry for the difficulty with automations not working in this case. Growing pains in the deploy systems.

The PR for this was deployed to prod on 2024-09-11

**Comment by lschurr** [comment]
Which PR fixed the bug on this GH @roryabraham?

It looks like this one wasn't deployed to prod yet: https://github.com/Expensify/App/pull/48436

**Comment by roryabraham** [comment]
https://github.com/Expensify/App/pull/48436. It was deployed to prod on 2024-09-11, the deploy comment just didn't work. Sorry for the confusion

**Comment by lschurr** [comment]
Payment summary:

- Contributor: @abzokhattab $125 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/38225834/overview))
- Reviewer: @suneox $125 ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/38329648/overview))
