### ISSUE TITLE
[$250] iOS - Distance - Center button icon is not centered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh05081@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to FAB > Submit expense
3. Go to Distance

## Expected Result:
Center button icon will be centered

## Actual Result:
Center button icon is not centered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![809](https://github.com/user-attachments/assets/460bff99-db70-4a8b-9b18-06b42a4bab99)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018cfba37db6e03a8f</li>
        <li>Upwork Job ID: 1828533917426975142</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 103709522</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by bondydaa** [comment]
this is most likely caused b/c we updated RN versions which also bumped the mapbox version so not exactly sure if we have some custom styles being applied that just need modifying or what.

context pr https://github.com/Expensify/App/pull/45289/

**Comment by bondydaa** [comment]
@CortneyOfstad believe payment is due tomorrow, i don't think the automation ran b/c `bug` was missing

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Caused indirectly by RN upgrades

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Launch New Expensify app
2) Go to FAB > Submit expense
3) Go to Distance
4) Verify map center button is centered

@CortneyOfstad

**Comment by JmillsExpensify** [comment]
$250 approved for @abdulrahuman5196

**Comment by JmillsExpensify** [comment]
Re-opening for regression test.

**Comment by CortneyOfstad** [comment]
Sorry, was OoO yesterday — @abdulrahuman5196 where are we at with the regression correction?

**Comment by abdulrahuman5196** [comment]
@CortneyOfstad Here is the regression test - https://github.com/Expensify/App/issues/48120#issuecomment-2368638359

**Comment by CortneyOfstad** [comment]
Oh, I am sorry about that! I misread and thought the fix went into regression, not that a regression test was needed 🤦‍♀️ 

Getting that sorted now!

**Comment by CortneyOfstad** [comment]
## Regression Test

https://github.com/Expensify/Expensify/issues/433432
