### ISSUE TITLE
[HOLD for Payment 2024-09-10] No clear button on the Filters page on web (non-mobile platforms.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48136]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724793973914559

## Action Performed:
1. Go to search
2. Go to filters
3. Apply some filters
## Expected Result:
There should be clear filter option
## Actual Result:
No clear button 
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (3)](https://github.com/user-attachments/assets/630b7967-cf43-4d7e-a388-6e2446ec2a37)

![image (4)](https://github.com/user-attachments/assets/f179f646-7af3-4aec-a4be-d327993f73df)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment]
Going to take over managing this one, as it's an internal project. @Kicu do you want to comment so that we can get you assigned for now?

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz Kałuzieński from Software Mansion, the expert agency. I'm going to work on this issue to help @Kicu out with the search tasks.

**Comment by Kicu** [comment]
btw @m-natarajan @JmillsExpensify we are unsure why there is a "on web" mention in the name of this Issue.

To my knowledge we are missing the button to clear filters on every platform, as no specific button for this was created. Is that correct?

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @rayane-djouah for PR testing and approval.

**Comment by JmillsExpensify** [comment]
Offer sent.

**Comment by JmillsExpensify** [comment]
Awesome, offer paid via Upwork!
