### ISSUE TITLE
[HOLD for payment 2024-09-23] [$250] Perf: getStateFromPath takes long time to execute

### ISSUE THREAD

**Issue by kacper-mikolajczak** [Expensify/App#48150]
**_Problem_**

When `getStateFromPath` receives big _linking config_ ([example](https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/libs/Navigation/linkingConfig/config.ts#L1152)) as an option parameter, it tends to slow down quite drastically.

**_Investigations_** 

The config-related data is created every time`getStateFromPath` is called, resulting in noticeable overhead.

Often times, configs provided to `getStateFromPath` are going to be static (e.g. initialised once at the app setup and remained untouched throughout its lifetime) and the data derived from it could also be static.

**_Solution_**

PR tries to improve `getStateFromPath` helper performance by extracting and caching latest calculations related to linking config. We will only keep the latest value due to static nature of the linking config - it looks like a ok heuristic :)

**_Results_**

Testing was done on _iOS iPhone15 simulator_ by instrumentalizing [`getStateFromPath` module](https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/libs/Navigation/getStateFromPath.ts#L10) as follows:

```tsx
// This function is used in the linkTo function where we want to use default getStateFromPath function.
const start = performance.now();
const state = RNGetStateFromPath(normalizedPath, linkingConfig.config);
console.log('getStateFromPath', performance.now() - start);
```

After applying caching, the execution time of `getStateFromPath` dropped from _15-25ms_ to _under 1ms_ for subsequent calls after the first one.

**Before**

https://github.com/user-attachments/assets/3876e1ff-f91c-45dd-9d7b-f2ff0249b512

**After**

https://github.com/user-attachments/assets/4c6148fc-3baa-404a-a3be-b0666523fc09

**Comment by kacper-mikolajczak** [comment]
Additionally, the performance of `getPathFromState` was checked and it takes about _**couple of ms to calculate**_ as well:

**Before**

https://github.com/user-attachments/assets/9d52007f-7502-4c55-b258-485eb4e6473c

After caching normalized configs calculation (via `createNormalizedConfigs` method) **_reduces this time to under 1 ms_**:

**After**

https://github.com/user-attachments/assets/9a440630-818d-4629-a2c6-3c83db6ff2d7

**Comment by mountiny** [comment]
$250 to @parasharrajat for their review and testing please cc @trjExpensify

**Comment by trjExpensify** [comment]
Sounds good. Payment summary as follows: 

- $250 to @parasharrajat for the C+ review

Feel free to go ahead and request. Closing!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
