### ISSUE TITLE
[HOLD for Payment 2024-09-19][Search v2.1] Set currently applied filters on Advanced Filters Page upon clicking Filters Button

### ISSUE THREAD

**Issue by 289Adam289** [Expensify/App#48156]
Coming from [here](https://swmansion.slack.com/archives/C049HHMV9SM/p1724763190609369)

**Problem**
 - When clicking on a Filter Button currently applied filters are not maintained
 - Type and Status filters are not accessible in Advanced filters Page
 
 **Solution** 
- Store filters present in url upon clicking Filters Button

cc @luacmartins @Kicu

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by luacmartins** [comment]
PR merged

**Comment by RachCHopkins** [comment]
@rayane-djouah can I just confirm this is $250 each for you and @289Adam289, and there are no regression tests to add?

If so, I'll whip up Offers in Upwork tomorrow.

**Comment by luacmartins** [comment]
@289Adam289 is from SWM and will get paid separately. No regressions tests to add this time, we'll handle it as part of the project wrap up.

**Comment by RachCHopkins** [comment]
Does that mean it's $250 for @rayane-djouah then @luacmartins ?

**Comment by luacmartins** [comment]
Yes

**Comment by RachCHopkins** [comment]
@rayane-djouah I've just sent you the offer!

**Comment by RachCHopkins** [comment]
@luacmartins can you please just give that a 👍🏼 before I pay it? i.e. that the offer/payment total should be $500?

**Comment by luacmartins** [comment]
@rayane-djouah https://github.com/Expensify/App/pull/47918 is linked to https://github.com/Expensify/App/issues/47497 and payment for that issue was already [processed](https://github.com/Expensify/App/issues/47497#issuecomment-2346447809). Did you mean to link a different PR above?

**Comment by luacmartins** [comment]
Np! Just wanted to check in case you had an incorrect link. Thanks for confirming. @RachCHopkins seems like $250 it is.

**Comment by RachCHopkins** [comment]
Thanks team! Will handle that now. 

Payment Summary:

Contributor: @289Adam289 - No external payment
Contributor+: @rayane-djouah to be paid $250 via Upwork
Upwork job [here](https://www.upwork.com/jobs/~021836981634821856080)

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
