### ISSUE TITLE
Expensify card - I'm not redirected to Issue New Card flow after adding a BA

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48152]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Founding when validation PR** https://github.com/Expensify/App/pull/47844
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Navigate to Workspace settings - More features
4. Enable "Expensify Card"
5. Navigate to Workspace settings - Expensify Card
6. Click on the "Issue new card" button
7. Add Regions bank with Plaid

## Expected Result:
I should be redirected to the "Issue New Card" flow.

## Actual Result:
I'm not redirected to the "Issue New Card" flow after adding a bank account. I have to click on the "Issue new card" button again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0a20b040-304d-4b60-b634-37d648548897

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
I am unsure and add both blocker labels. Please delete if it's need. Thank you

Production - no "Issue new card" button

![Screenshot (639)](https://github.com/user-attachments/assets/50fa89c7-a058-46a3-8fbb-a13f404ad7be)

**Comment by mountiny** [comment]
looking

**Comment by mountiny** [comment]
This is not a blocker as the cards are behindbeta

**Comment by mountiny** [comment]
@koko57 @VickyStash @DylanDylann @allgandalf for viz

**Comment by mountiny** [comment]
From looking at the video this seems like expected behaviour to me. the admin first needs to add the VBBA and only then they start the issue new card flow choosing the settlement account first.

**Comment by DylanDylann** [comment]
Agree with @mountiny
