### ISSUE TITLE
[HOLD for payment 2024-11-13] Enable Bridgeless mode

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#48163]
### Problem

We have updated the app to the 0.75 RN version now which allows us to use bridgeless mode. You can read more about what this mode is [here](https://github.com/reactwg/react-native-new-architecture/discussions/154). We have not enabled it yet, though, so we are missing out on the benefits that this mode brings. The main benefit should be improved performance, although we still need to test and measure how much performance gains there are for us in the App.

### Solution

Enable the Bridgeless mode in the App and compare the performance with the mode on and off

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by roryabraham** [comment]
thanks for creating this @mountiny!

**Comment by mountiny** [comment]
This will take some time to enable, swm is working on this

**Comment by mountiny** [comment]
We will want to post a proper problem solution to the channel before we make more progress on this one @WoLewicki @j-piasecki I will try to see if I can help with that

**Comment by mountiny** [comment]
updated proposal was shared in slack and I think we are good to move forward https://expensify.slack.com/archives/C05LX9D6E07/p1727354565454709

**Comment by abekkala** [comment]
@mountiny is there a PR for this one yet? 

I'm going ooo until Oct 20 - I'd like to assign a buddy to watch this one until I return. But I'd like to better understand the progress status of this one first.

**Comment by WoLewicki** [comment]
Here it is: https://github.com/Expensify/App/pull/48160

**Comment by abekkala** [comment]
Thank you for linking it @WoLewicki ! 🎉

**Comment by abekkala** [comment]
cc: @OfstadC if this gets deployed to production soon and payment date is before Oct 21 here is the summary: 

### PAYMENT SUMMARY [date: TBD]: 
- Fix: @WoLewicki SoftwareMansion, no upwork payment needed
- PR Review: @fedirjh [$250, if no regressions] payment is done via NewDot

**Comment by abekkala** [comment]
I'm back from ooo - unassigning @OfstadC

**Comment by mountiny** [comment]
This was reverted for android, we can keep this issue open and track enabling it for android again

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR NOV 05

- Fix: @WoLewicki - SWM, no Upwork payment
- PR Review: @fedirjh [$250] payment via NewDot

**Comment by abekkala** [comment]
### No Payments needed: 

- Fix: SWM
- PR Review: internal (Vit)

No regressions, closing this issue

**Comment by abekkala** [comment]
Thanks, @fedirjh. That's what I thought - Melvin's post after me confused me a bit. In this case their post was not helpful> Back to my original payment summary lol

____


### PAYMENT SUMMARY FOR NOV 13
- Fix: @WoLewicki - SWM, no Upwork payment
- PR Review: @fedirjh [$250] payment via NewDot

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
