### ISSUE TITLE
mWeb - Chat  - In thread page, marking us unread "parent message", green line is not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48186]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4898339
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a chat
3. Enter and send a message
4. Long press the message and select reply in thread
5. Send a message
6. Long press the "parent message" and mark as unread
7. Now green line is not shown
8. Navigate to conversation page and mark as unread the parent message
9. Now note, in both conversation and thread page, new message green is shown

## Expected Result:
In thread page, marking us unread "parent message", green line must be shown

## Actual Result:
In thread page, marking us unread "parent message", green line is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4ea1612a-814d-4748-9b4a-109f9f26c9b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
[Dupe](https://github.com/Expensify/App/issues/46421)
