### ISSUE TITLE
[$250] iOS Report fields - Delete pop-up does not open when trying to delete report field from 3-dot

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48193]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-11
**Reproducible in staging?:**Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace settings > Report fields
3. Add any type of report field
4. Go to workspace chat
5. Submit an expense
6. Go to workspace settings > Report fields
7. Delete the report field added in Step 3
8. Go back to workspace chat
9. Tap on the expense preview
10. Tap on the report field added in Step 3
11. Tap 3-dot menu (if it does not appear, reopen the app until it appears)
12. Tap Delete

## Expected Result:
Delete pop-up will open

## Actual Result:
Delete pop-up does not open when trying to delete report field from 3-dot menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/535315ae-7dec-46c5-a029-89d83035a14d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134b2508ecc084f72</li>
        <li>Upwork Job ID: 1830962412826415347</li>
        <li>Last Price Increase: 2024-09-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to ##wave-control

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Delete confirmation for report fields doesn't show when we try to delete it from expense report.

### What is the root cause of that problem?
When we select the delete option, we set the visibility of the confirmation modal to true.
https://github.com/Expensify/App/blob/c12adce82228977affac60469b9ff8efb6d43cce/src/pages/EditReportFieldPage.tsx#L101

However, we don't wait until the current modal to hide, so the confirmation modal won't show.

### What changes do you think we should make in order to solve the problem?

We need to wait for the current modal to hide first before showing the 2nd one.

We can use `Modal.close`
```
Modal.close(() => setIsDeleteModalVisible(true))
```

OR

Wait for this [PR](https://www.github.com/Expensify/App/pull/47991) and pass `shouldCallAfterModalHide` as true.

**Comment by bfitzexpensify** [comment]
I am heading out of office until September 21st, so assigning a buddy to watch over this in my absence. 

Current status: waiting on proposals

**Comment by Pujan92** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/48193#issuecomment-2315776871) looks good to me and we can use prop `shouldCallAfterModalHide` for the item.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment]
PR is ready

cc: @Pujan92

**Comment by AndrewGable** [comment]
@zanyrenney @bfitzexpensify - Looks like automation failed here, can we pay this out? Been on production for 3 weeks.

**Comment by Pujan92** [comment]
Bump @zanyrenney

**Comment by zanyrenney** [comment]
@bfitzexpensify as the OG assignee, want to take this back now you are not OOO?

**Comment by bfitzexpensify** [comment]
Yep! Lemme get this sorted

**Comment by bfitzexpensify** [comment]
Payment summary:

@Pujan92 due $250 for C+ work via manual request
@bernhardoj due $250 for contributor work via manual request

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment]
$250 approved for @Pujan92
