### ISSUE TITLE
[READY FOR PAYMENT][$250] Can not select 'Payment account' in Workflow Page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1724786774524009

## Action Performed:
1. Go to a workspace
2. Enable Workflow
3. Connect bank account
4. Place the mouse cursor below the text 'Payment account'
5. Click 3 times to select
## Expected Result:
Can select all 'Payment Account' text
## Actual Result:
Text in bank account selected
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/5263ffd9-ad05-4145-bda5-7b68f310378c

https://github.com/user-attachments/assets/38405bc0-7863-44ba-a48f-26ecb1f131fa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831332987291555271</li>
        <li>Upwork Job ID: 1831332987291555271</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103830400</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by dangrous** [comment]
Seems fine to me! I'll assign but also want to ping @Expensify/design for a quick look too to make sure we're not undoing some specific reasoning for the negative margin.

**Comment by dannymcclain** [comment]
I think as long as the spacing stays correct, and the hover state for the option row still works normally, I don't see any problem.

**Comment by dangrous** [comment]
This never got the "deployed to production" comment on the PR but it was in a checklist... It has to have been deployed by now, right? Were there some that were missing the automations recently? If so I think we must be almost ready for payment if not ready already. cc @JmillsExpensify

**Comment by dangrous** [comment]
Oh actually weird, I just checked out the `production` branch and it's NOT there, nor is it on `main`. But it was definitely merged. Not sure what's up there

**Comment by dangrous** [comment]
I'm going ahead and marking this as ready for payment, it's been at least 6 days and I'm like 95% sure it's been more like 2 weeks.

**Comment by dangrous** [comment]
just pinged to get some assistance here

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor: @daledah $250 via Upwork
Contributor+: @dukenv0307 $250 via Upwork

Please apply/request!

**Comment by dylanexpensify** [comment]
@daledah heads up - sent offer!

**Comment by dangrous** [comment]
@JmillsExpensify can we pay this one out? Thanks!

**Comment by dangrous** [comment]
lemme know if I should grab another BZ for payment - I know you're busy!

**Comment by dangrous** [comment]
hi @RachCHopkins! This one is ready for payment - thank you!

**Comment by RachCHopkins** [comment]
No worries @dangrous, looks like Dylan paid @dukenv0307 already:

![image](https://github.com/user-attachments/assets/f4c155c9-331a-4f42-8066-9b78504c9ae3)

@daledah I can't see the offer that Dylan sent [here](https://github.com/Expensify/App/issues/48205#issuecomment-2419822949) in your jobs on Upwork - do you recall if you accepted it?

**Comment by RachCHopkins** [comment]
Contributors have been paid, the contract has been completed, and the Upwork post has been closed.
