### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] [Performance] Avoid including mapbox in initial web bundle

### ISSUE THREAD

**Issue by janicduplessis** [Expensify/App#48202]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

Reduce the amount of JS needed to load the app by delaying loading of resources that are not needed initially until they are used. One good candidate for this is mapbox, which is only used when creating a distance expense. The map is already not available while offline so this is not a concern.

## What is the impact of this on end-users?

This app will load faster initially on web.

## List any benchmarks that show the severity of the issue

We can see that mapbox is about 1mb (300kb gzip) of JS by running bundle analyzer (`npm run analyze-packages`). We can also see that this bundle is loaded initially by using chrome devtools network panel.

## Proposed solution (if any)

Delay loading the map code until the component is rendered by using `React.lazy`. Offline mode is not a concern here since the map doesn't work while offline.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

We can see that mapbox is now in its own bundle by running `npm run analyze-packages`. We can also verify that this bundle is not loaded initially and only when rendering a screen that displays the map.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

**Version Number:** 9.0.25-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @janicduplessis 
**Slack conversation:** 

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832118031291081965</li>
        <li>Upwork Job ID: 1832118031291081965</li>
        <li>Last Price Increase: 2024-09-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by cristipaval** [comment]
@neil-marcellini I know you worked with Mapbox. Do you mind taking over this issue and managing it? There is already [a PR](https://github.com/Expensify/App/pull/41242) for it, I guess we'll want a C+ to review first.

**Comment by janicduplessis** [comment]
Waiting for review!

**Comment by neil-marcellini** [comment]
@sobitneupane would you please review the PR as C+?

**Comment by neil-marcellini** [comment]
Hi @janicduplessis. Thanks for working on this. I want to make sure this is a problem worth solving, as is our standard practice. Would you please present some benchmarks of the load time for the app with the mapbox bundle included and separate? Or otherwise determine what percentage of the load time comes from Mapbox with a direct measure? Please detail your testing methodology as well. Was a problem and solution presented anywhere in Slack? Would you please write one in the issue description?

Once I have that info I'll feel confident about going forward with this or not.

**Comment by neil-marcellini** [comment]
Waiting for @janicduplessis to respond

**Comment by janicduplessis** [comment]
@neil-marcellini Here's the network profile for production newdot:

<img width="1043" alt="image" src="https://github.com/user-attachments/assets/72911d62-f765-4e92-be9a-c5a5eb9fd402">

We can see that the loading of JS happens in 2 steps, let's only consider the 2nd step which is when mapbox is loaded. The app loads 3 js bundles in parallel for a total of 6.6mb.

From looking at the bundle analyser result we can see that mapbox is included in chunk 62 and weights about 1mb.

<img width="430" alt="image" src="https://github.com/user-attachments/assets/dc513892-378e-4a5f-8f37-49f874c24d2c">

**Comment by neil-marcellini** [comment]
Thanks for writing that out @janicduplessis. I think a 1s/15% time savings on a slow connection is worth it, but just barely. Would you please [follow this guide](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_CREATE_A_PLAN.md#L37) and post your problem solution in #expensify-open-source on Slack? Once we get a good amount of thumbs up we can move forward.

**Comment by janicduplessis** [comment]
Working on this today

**Comment by janicduplessis** [comment]
Measured main and PR and here is the result (there was an issue with gzip compression last time I tested, so re-measured everything)

In chrome with "Fast 4G" connection. The screenshots show the part where we load the bundles in parallel. As I excepted reducing the size of some of the bundles also cause the bigger one to load faster even if its size didn't really change.

Current:

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/c599e4e7-67d8-446e-bb44-416f72366326">

PR:

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/89abc34d-cf65-44de-bc34-d33fd3fd25ee">

We go from 1.86s to 1.68s for the slowest bundle to load. We save 180ms, which is about 10%. On slower connection (3G) it seems to lead to slightly bigger savings, 37s -> 32s (14%). If we consider the whole loading sequence it is a pretty small improvement.

Will post a proposal in slack to see if we think this improvement is worth it.

**Comment by janicduplessis** [comment]
Posted the proposal on slack.

**Comment by neil-marcellini** [comment]
Nice, I'm glad to have Rory's support and from others, so let's go ahead with it. 180ms isn't much for the fast 4g but 5s on 3G is big.

**Comment by neil-marcellini** [comment]
The PR is on staging. I'm assigning a BZ member to handle C+ payment.

**Comment by slafortune** [comment]
@janicduplessis does not require payment (Contractor)
@sobitneupane requires payment of $250 NewDot Manual Requests

**Comment by garrettmknight** [comment]
$250 approved for @sobitneupane
