### ISSUE TITLE
Web - Chat - Edited gets copied after selecting and copying an edited comment

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48200]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
Issue was found when executing this PR: https://github.com/Expensify/App/pull/45150
**Email or phone of affected tester (no customers):** applausetester+nl460@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Send a comment in a chat
3. Edit that comment
4. Start selecting the edited comment from the start of the text beyond the end of the comment
5. CTRL + C to copy or right click on the comment click on copy to clipboard while the selection is still on the text
6. Paste the copied content elsewhere

## Expected Result:
"(edited)" doesn't get copied alongside the text

## Actual Result:
"(edited)" gets copied with the text

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/26db04eb-dc30-43e1-83ea-ee5a7cdeb741

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by OfstadC** [comment]
Working on this now

**Comment by OfstadC** [comment]
Okay - so "edited" doesn't copy when double clicking and copying, nor when selecting the actual text, but it does if you drag your cursor over "edit" - It works this way in Slack too (just tested) - so I don't think this is a bug.
