### ISSUE TITLE
[hold for payment 2024-09-10] [$250] Require a 2FA code to disable 2FA

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#48215]
# Problem
Users can disable 2FA without entering a 2FA code.

## Why this is important to solve?
It is a security risk. If someone can get your authToken, then they can disable your 2FA and keep access to your account.

# Solution
When 2FA settings are disabled, we need to prompt the user to enter a valid 2FA code and validate it.

I already have [a PR](https://github.com/Expensify/App/pull/48030) written for this, so it doesn't need a contributor but I do need a C+ to review it which is why I am creating this issue.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c8f7bf5820798ba</li>
        <li>Upwork Job ID: 1828889567388062710</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by joekaufmanexpensify** [comment]
@tgolen is the PR for this one already in review? If so, mind linking it to the issue so I can follow along?

**Comment by tgolen** [comment]
Oops, sorry! Here it is: https://github.com/Expensify/App/pull/48030

**Comment by joekaufmanexpensify** [comment]
All good. TY!

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
PR merged!

**Comment by tgolen** [comment]
I'm gonna close this out since it was deployed to production.

**Comment by joekaufmanexpensify** [comment]
Ah, I think we still need to pay @parasharrajat for his review here.

**Comment by joekaufmanexpensify** [comment]
@tgolen @parasharrajat was https://github.com/Expensify/App/issues/48461 a regression introduced by the PR here? Seems like yes, but curious if that is correct?

**Comment by joekaufmanexpensify** [comment]
Bumped in Slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1726000822090079).

**Comment by joekaufmanexpensify** [comment]
Got it, thank you for confirming. Only payment here then is $125 to @parasharrajat for C+ review via NewDot (50% penalty for regression)!

**Comment by joekaufmanexpensify** [comment]
Feel free to request payment whenever you're ready @parasharrajat , otherwise closing this for now!

**Comment by JmillsExpensify** [comment]
$125 approved for @parasharrajat
