### ISSUE TITLE
"Filter" string shows in English when language preference is Spanish for Card Page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-11
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47773
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. In the URL bar navigate to /search/filters/card (add this after domain eg. https://staging.new.expensify.com/
4. Select a card and then proceed to use the search feature
5. Observe the Filter details at the top of the page

## Expected Result:
User expects all aspects of the app to show in Spanish

## Actual Result:
The filter strings at the top are in English

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/08cf9fdd-a4d1-4869-b36c-5c5a34d4ba68

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ikevin127** [comment]
cc @luacmartins Looks like we omitted the translations for the actual filter type labels / static filter values. How much of these do you think should actually be translated given that over a certain point the filtering functionality might be impacted ?

**Comment by luacmartins** [comment]
I don't think this is an issue for a few reasons. We're getting rid of the top bar soon and it's a representation of the search query syntax, which as of now only supports English, so we shouldn't be translating that. Closing this issue.
