### ISSUE TITLE
[Hold for payment: 2024-09-07] Contact method page is inaccessible on `main`

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#48219]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** main
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rushatgabhane 
**Slack conversation:**

## Action Performed:

Go to /settings/profile/contact-methods
Tap "New Contact method" button
Verify you are brought to the correct screen and the app does not crash

## Platforms:

All

## Screenshots/Videos

Uploading Screen Recording 2024-08-28 at 22.36.09.mov…

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @allgandalf $250 

Please apply/request!

**Comment by dylanexpensify** [comment]
https://www.upwork.com/ab/applicants/1833435028033048421/job-details job post!

**Comment by dylanexpensify** [comment]
done!
