### ISSUE TITLE
Scan - Less number of scanned expenses show up inside the expense conversation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48223]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4898296
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1194@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new gmail account
3. Create a workspace
4. Go to workspace chat and submit 4 scan expenses using the same receipt
5. Wait for the scan to finish for all 4 receipts
6. Once scanning is done click on the IOU preview to go to expense conversation page
7. Additionally go to search > Expenses to see number of expenses

## Expected Result:
4 expenses show up inside the expense conversation page

## Actual Result:
Less than 4 expenses are displayed inside the expense conversation page (Sometimes 3, sometimes 2) even though the number of expenses shown on the preview component in workspace chat page is 4. When going to search > Expenses only 2 expenses are visible there too

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/83bdd58e-9a82-4e41-b096-1264d5f50ce4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
The tester has uploaded the same receipt 4 times. Check the Concierge conversation, it'll tell you they were deleted as dupes. This is [the test](https://expensify.testrail.io/index.php?/tests/view/4898296) they were executing, we don't ask to upload the same receipt loads of times.

As for the count in the report preview component after expenses are deleted, looks like we have an issue for it here: https://github.com/Expensify/App/issues/47617

Closing.
