### ISSUE TITLE
Scan - New scan expense disappears if submitted after mulitple paid scan receipts

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1196@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in with a new gmail account
3. Create a workspace
4. Go to workspace chat
5. Submit 4 same receipt scan expenses
6. After the scan is complete pay the scan elsewhere
7. Submit another scan expense using the previous receipt
8. Wait for it to get done scanning

## Expected Result:
After scanning is complete the scanned receipt shows up with the amount

## Actual Result:
After the scanning is complete the expense disappears

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d38118d1-0d19-420f-89ea-af945bc9b08b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to  #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment]
Couldn't repro on v9.0.26-4
