### ISSUE TITLE
Account switcher - Unable to select account via keyboard

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48245]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in as copilot.
3. Go to Account settings.
4. Click on the account switcher.
5. Select another account using keyboard.

## Expected Result:
User should be able to select account via keyboard.

## Actual Result:
Left hand pane scrolls down when trying to select account via keyboard.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1865eb07-695e-471d-8a73-9f2a93542a3e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment]
@youssef-lr @kadiealexander can you please make this external. I won't be able to prioritize this

cc: @dangrous

**Comment by rushatgabhane** [comment]
This will be fixed by https://github.com/Expensify/App/issues/48292

Because the proposal uses `SelectionList`
