### ISSUE TITLE
Search - Header Pills are touching each other when highlighted, no spacing

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47753
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to Search tab on the bottom > Expenses > Observe the header pills

## Expected Result:
User expects to have spacing between each pill

## Actual Result:
There is no spacing between the Search Pills

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/30f30876-6a6f-424f-9e78-32de94d51995

![Bug6586081_1724903004154!No_correct_spacing_between_pills_](https://github.com/user-attachments/assets/de5f3da9-b9c8-4838-874f-848370176dfb)
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by shawnborton** [comment]
Correct, this is not a bug - going to close.
