### ISSUE TITLE
PD Check for unexpected installed packages on scrapers

### ISSUE THREAD

**Issue by nkuoch** [Expensify/App#48257]
> Found unexpected package(s) libimagequant0, libraqm0

<img width="1516" alt="image" src="https://github.com/user-attachments/assets/9eef1bea-43ba-4623-be31-d0afc70e8554">

I temporarily silenced it in Thruk
<img width="1587" alt="image" src="https://github.com/user-attachments/assets/fda24fe5-8718-418c-b77d-d4cdd7fc89fc">

**Comment by nathanmetcalf** [comment]
![image](https://github.com/user-attachments/assets/b1d82d94-51c2-4453-ae03-958ef0a0bdf6)

This is a new requirement for `php8.1-gd`. 

PR above will address the monitoring.
