### ISSUE TITLE
Profile - Avatar edit modal can be opened while app is loading

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has default avatar.

1. Go to staging.new.expensify.com
2. Go offline or set the network speed to 3G in network tab
3. Go to Troubleshoot > Clear cache and restart/
4. Click Reset and refresh.
5. Go to Profile.
6. Click on the avatar.
7. Click Remove photo.

## Expected Result:
User should not be able to open avatar edit modal when the app is loading (production behavior).

## Actual Result:
User can open avatar edit modal when the app is loading. Remove photo option is shown even when the account has default avatar when the app is loading.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d7ab6496-b96b-4475-ab02-3ae45f2d9260

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
@dangrous this doesn't seem like a deploy blocker to me

**Comment by dangrous** [comment]
Yeah I don't think this needs to block, not a regression just a minor issue with a new feature. But yeah, let's get this fixed soonish!

**Comment by dangrous** [comment]
assigning rushat to this one

**Comment by dangrous** [comment]
@rushatgabhane let us know what you're thinking about this one, thanks!

**Comment by rushatgabhane** [comment]
i guess we should add skeleton for avatar when it is loading

**Comment by dangrous** [comment]
That sounds good @rushatgabhane!

**Comment by adelekennedy** [comment]
@rushatgabhane @dangrous  how are we doing with this one? I see it's been grouped up with other issues [here](https://github.com/Expensify/App/pull/48517) should we drop the priority of this one?

**Comment by dangrous** [comment]
This was deployed to production 9/19, so we can close on 9/26 assuming all goes well. No payment needed on this one since it was a bug from copilot, right?

**Comment by adelekennedy** [comment]
@dangrous I think that makes sense - all payment for these issues are being grouped together?

**Comment by dangrous** [comment]
yep!
