### ISSUE TITLE
 Profile - Tapping on "Account name", shows interaction, but no redirection

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48253]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
Issue was found when executing this PR: https://github.com/Expensify/App/pull/47338
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre: User does NOT have copilot enabled

1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to Profile > Click on users name at the top

## Expected Result:
User expects that if this is not a feature, then no interaction should happen

## Actual Result:
The name is clickable (And blinks when clicked) and no redirect happens, when user has copilot enabled, the user can see a dropdown menu here

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/73beb11a-55d8-44cf-9759-299f6f1a1625

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by rushatgabhane** [comment]
under beta. please assign me

**Comment by rushatgabhane** [comment]
cc @parasharrajat looks like we can't get rid of `pressDimmingValue`

**Comment by puneetlath** [comment]
demoting since copilot is in beta

**Comment by dangrous** [comment]
yeah i think just updating the dimming should satisfy this

**Comment by danieldoglas** [comment]
@rushatgabhane how's this one going?

**Comment by danieldoglas** [comment]
@rushatgabhane bump!

**Comment by rushatgabhane** [comment]
fixed in draft PR above ^

**Comment by OfstadC** [comment]
Looks like this was deployed to production. So payment should be issued on 2024-09-26

**Comment by rushatgabhane** [comment]
@OfstadC this is part of copilot project. no payment due

**Comment by OfstadC** [comment]
Perfect! Thanks for confirming @rushatgabhane !
