### ISSUE TITLE
Xero - App crashes when xero connected account disable 2FA and relog

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48262]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4901080&group_by=cases:section_id&group_id=309134&group_order=asc&group_by=cases:section_id&group_id=309134&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+gm103061@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions:
User have 2FA enabled and Xero connected

Steps:
1. Go to Security> Deactivate 2-FA
2. Log out
4. Enter same email address> Continue
5. Enter the magic code

## Expected Result:
App crashes when xero connected account disable 2FA and relog

## Actual Result:
User logged without problem

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[2908_2.txt](https://github.com/user-attachments/files/16799375/2908_2.txt)

https://github.com/user-attachments/assets/e4f39859-b64f-412d-b53a-094a954e59b3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
Testing some reverts. The crash is probably because we're ending up in bad navigation state

**Comment by MonilBhavsar** [comment]
Tested on staging and it worked!
