### ISSUE TITLE
[$250] Accounting - Wrong integration name in modal message when there is existing connection

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48265]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO
1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting
3. Click Other integrations
4. Click Connect button next to Xero

## Expected Result:
The integration in the pop-up message should be correct
Connect <Xero>
Are you sure you want to connect <Xero>? This will remove any existing acounting connections

## Actual Result:
The integration in the pop-up message is wrong. It shows QBO when it is already connected to QBO
Connect <Quickbooks Online>
Are you sure you want to connect <Quickbooks Online>? This will remove any existing acounting connections

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8dcfbfc1-9e8f-4635-86e9-687a96a2ef3e

<img width="1440" alt="40 09" src="https://github.com/user-attachments/assets/7a2a885d-038a-4854-98c8-4383dbf46a53">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01183260f3b2c951d3</li>
        <li>Upwork Job ID: 1831032217491230963</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103814360</li>
<li>Nodebrute | Contributor | 103814362</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by DylanDylann** [comment]
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/48265#issuecomment-2317656159) looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by muttmuure** [comment]
Paid
