### ISSUE TITLE
Rules - Rules in left hand navigation does not follow the order in More features list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48266]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > More features
3. Enable all the features

## Expected Result:
The features in the left hand navigation should follow the order of features in More features list
Rules should be arranged between Workflows and Categories

## Actual Result:
Rules is at the end of the list in the left hand navigation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/640fa1ef-3710-4e78-870c-ef598c0f9f62

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Demoting since rules is under beta. cc @marcaaron

**Comment by WojtekBoman** [comment]
We'll adjust this in one of our rules related PRs

**Comment by Guccio163** [comment]
Hi, I just fixed it in the #48184 PR, it is already approved by C+ so I think it'll be soon merged 👌
