### ISSUE TITLE
[HOLD for payment Oct 4][$250] Attachment - Error not displayed when trying to upload corrupted pdf file to chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48263]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+omqq1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: user should be Signed In
1. Open app
2. Navigate to any chat
3. Tap on plus button
4. Select Add attachment option
5. Upload this corrupted pdf file [corrupted.pdf](https://github.com/user-attachments/files/16982628/corrupted.pdf)

## Expected Result:
"Attachment error" pop-up should be displayed

## Actual Result:
Keyboard overlaps the attachment error pop-up and error pop-up is not visible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/690d2123-aa87-4708-ad99-d78604532fda

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a722d0e57042bb6b</li>
        <li>Upwork Job ID: 1829184455392581969</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 103991859</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by srikarparsi** [comment]
Making this external to get some eyes

**Comment by srikarparsi** [comment]
This [PR](https://github.com/Expensify/App/pull/47622) is related to the attachment modal

**Comment by srikarparsi** [comment]
This seems to only be happening on iOS, tested mWeb chrome and safari and it's not reproducible

**Comment by muratti32** [comment]
Contributor details
Your Expensify account email:muratti32@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0133345a239098ea13

**Comment by Christinadobrzyn** [comment]
I'm going to be ooo 9/4-9/11, so I'm going to add a BZ teammate to watch this while I'm away. @alexpensify - we are reviewing proposals so there shouldn't  be much to do at this time. TY!

**Comment by alexpensify** [comment]
@dominictb can you please share the iOS simulator version? Thanks!

**Comment by alexpensify** [comment]
@thesahindia, can we continue the review process, or do we need to start a discussion in the Open Source Slack room?

**Comment by Christinadobrzyn** [comment]
@dominictb can you attach the corrupted file that you tested with so we can see if that helps reproduce the issue?

**Comment by alexpensify** [comment]
@Christinadobrzyn is back, so I'm going to exit this GH party.

**Comment by Christinadobrzyn** [comment]
Ah thanks @dominictb i can reproduce this issue when trying to upload [corrupted.pdf](https://github.com/user-attachments/files/16982628/corrupted.pdf). I added that file to the OP testing steps. 
@thesahindia do you think we should move forward with this?

**Comment by alexpensify** [comment]
@srikarparsi, we need your review; thanks!

**Comment by Christinadobrzyn** [comment]
Nudged @srikarparsi for a review when online!

**Comment by srikarparsi** [comment]
Sorry for the delay, assigning @dominictb

**Comment by Christinadobrzyn** [comment]
just a heads up that I'm going to be ooo until 9/30. I'm not going to assign a BZ teammate since we're working on the PR/discussing the issue. If you need someone before Monday please reach out in Slack for a volunteer

**Comment by Christinadobrzyn** [comment]
Payouts due:

- [ ] Contributor: $250 @dominictb (Upwork offer - https://www.upwork.com/nx/wm/workroom/38495529/overview)
- [ ] Contributor+: $250 @thesahindia (you're paid in NewDot, yes?)

Do we need a regression test?

**Comment by Christinadobrzyn** [comment]
- Regression test - https://github.com/Expensify/Expensify/issues/433275

- [Payment summary](https://github.com/Expensify/App/issues/48263#issuecomment-2382152936)

Thanks @thesahindia - please submit a payment via NewDot. TY!
@dominictb I've paid you out in Upwork

**Comment by Christinadobrzyn** [comment]
I DMd @thesahindia reminding them to request payment. We'll keep it open for a bit longer to make sure @thesahindia sees it.

**Comment by garrettmknight** [comment]
$250 approved for @thesahindia
