### ISSUE TITLE
Payment issue for Upgrades Project

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#48272]
E/E Tracking issue: https://github.com/Expensify/Expensify/issues/391954

Creating this issue to pay out @allroundexperts for the Upgrade project

**Comment by garrettmknight** [comment]
**And here's the detailed summary:**
- $1000 for the design doc
- $500 for the urgency bonus
- $250 per normal issue completed x 3 = $750
  - Intacct integration: https://github.com/Expensify/App/issues/43913
  - GL codes: https://github.com/Expensify/App/issues/43914
  - Taxes: https://github.com/Expensify/App/issues/43914
- Special pricing issues:
  - $750 - Report fields + first more features upgrade implementation: https://github.com/Expensify/App/issues/43916
  - $500 - NS integration + first in situ upgrade implementation: https://github.com/Expensify/App/issues/43908

**Total pay =  $3500** =  $1000 + $500 + $750 + $750 + $500

**Comment by garrettmknight** [comment]
@allroundexperts can you request via NewDot when you get a chance? It'll have to go to @JmillsExpensify.

**Comment by allroundexperts** [comment]
Requested!

**Comment by JmillsExpensify** [comment]
$3,500 approved for @allroundexperts

**Comment by garrettmknight** [comment]
Think we're all good here then!
