### ISSUE TITLE
Thread – Thread parent message not updated in LHN after editing in group chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48271]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4904603
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open group chat
4. Send a message
5. Reply in thread and send a comment
6. Edit parent message
7. Observe the thread in LHN

## Expected Result:
Thread parent message updated in LHN

## Actual Result:
Thread parent message not updated in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/541cb165-a19a-4335-99c8-5a6596e295ec

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
[dupe](https://github.com/Expensify/App/issues/47564)

**Comment by jliexpensify** [comment]
Looks like it, thanks @FitseTLT!
