### ISSUE TITLE
[$250] WS - "Rule" tab has unnecessarly long input field for "Days" section

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48284]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Can't check
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to Workspace > Workflow > Enable rules
4. Go to "Max Expense Age'" and input a very high number (Note that this field is for Flagging spend older than a specific number of days.)

## Expected Result:
User expects that there is a limit of days that can be input and that this limit is reasonable

## Actual Result:
User can input absurdly large number of days, numbers that are highly unrealistic for a field like this

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f1d1850c-ece3-428f-a6d0-285a79373f2f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183e993ca7b36650e</li>
        <li>Upwork Job ID: 1831043219902619216</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103822043</li>
<li>Nodebrute | Contributor | 103822045</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by puneetlath** [comment]
Demoting since rules are in beta

**Comment by chiragsalian** [comment]
marking issue as external

**Comment by chiragsalian** [comment]
Proposal LGTM, feel free to create the PR @Nodebrute.

**Comment by chiragsalian** [comment]
Yup 5 for now sounds good to me. With 5 digits user can enter 99999 which is 273 years, so yeah that's more than good enough for me.

**Comment by anmurali** [comment]
Done.
