### ISSUE TITLE
[$125] Update tasks in the Manage my team's expenses onboarding flow to include direct links to those workspace settings #424515

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#48294]
Problem: Multiple tasks use the language "2. Go to [Workspaces > [your workspace]"  in the task. We never meant for it to be [your workspace] because that just looks incorrect. After discussion, we're going to update the tasks so that they are not included. Here is what I'm talking about. 
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/390606e7-d5e4-480c-8f2d-393b66c3edc3">

Solution: Update the text to remove [your workspace], while still giving the user full directions to train them and providing a link directly to where they can make the changes. 

All of the Task titles would remain unchanged. The assignee would remain unchanged as well. Below is the updated text in the description of each task. 

### Set up categories

> **Set up categories** so your team can code expenses for easy reporting.
> 
> Here’s how to set up categories:
> 1. Click your profile picture.
> 2. Go to Workspaces.
> 3. Select your workspace.
> 4. Click **Categories**.
> 5. Enable and disable default categories.
> 6. Click **Add categories** to make your own.
> 7. For more controls like requiring a category for every expense, click **Settings**.
> 
> [Take me to workspace category settings](https://new.expensify.com/settings/workspaces/FA65B46FFA6F4F2D/categories).

Note: the link would direct the user to the categories section in the workspace editor of the workspace.

### Add expense approvals

> **Add expense approvals** to review your team’s spend and keep it under control.
> 
> Here’s how to add expense approvals:
> 1. Click your profile picture.
> 2. Go to Workspaces.
> 3. Select your workspace.
> 4. Click **More features.**
> 5. Enable **Workflows.**
> 6. In **Workflows**, enable **Add approvals.**
> 7. You’ll be set as the expense approver. You can change this to any admin once you invite your team.
> 
> [Take me to enable more features](https://new.expensify.com/settings/workspaces/4F4977A767D37D6F/more-features).

Note: the link would direct the user to the more features section in the workspace editor of the workspace.

### Invite your team

> **Invite your team** to Expensify so they can start tracking expenses today.
> 
> Here’s how to invite your team:
> 1. Click your profile picture.
> 2. Go to Workspaces.
> 3. Select your workspace.
> 4. Click **Members > Invite member.**
> 5. Enter emails or phone numbers.
> 6. Add an invite message if you want.
> 
> [Take me to workspace members](https://new.expensify.com/settings/workspaces/FA65B46FFA6F4F2D/members). That’s it, happy expensing! :)

Note: the link would direct the user to the members section in the workspace editor of the workspace.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebd40facad6e93ad</li>
        <li>Upwork Job ID: 1829287796879757259</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>gijoe0295 | Contributor | 103805341</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by anmurali** [comment]
@aimane-chnaif - bump for a review

**Comment by danielrvidal** [comment]
Thanks @aimane-chnaif let us know if we need to help at all? Otherwise hopefully we can keep making progress today or tomorrow!

**Comment by danielrvidal** [comment]
@aimane-chnaif does this image not work for you? It's showing up for me.

![image](https://github.com/user-attachments/assets/74bc88e1-1c25-4e66-b00a-bec84d52ed27)

**Comment by danielrvidal** [comment]
Nice, I tested on staging and it looks great!

**Comment by anmurali** [comment]
Same. @danielrvidal you need to investigate

**Comment by danielrvidal** [comment]
Just commented on the PR because I think it actually live on production. I'll report back.

**Comment by marcaaron** [comment]
Pretty sure this is on production and Melvin did not leave a comment for some reason.

**Comment by anmurali** [comment]
**Payment summary**

- [X] Contributor @gijoe0295 $125 approved via Upwork
- [ ] Contributor plus @aimane-chnaif $125 approved via New Dot

**Comment by anmurali** [comment]
@aimane-chnaif - offer is [here](https://www.upwork.com/nx/wm/offer/104159443)

**Comment by anmurali** [comment]
Done.
