### ISSUE TITLE
[HOLD for payment 2024-09-16][$250] [Search v2.1] Create automated tests for the Search parser

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48291]
## Problem
We introduced a search syntax grammar and generated a parser for it, but any changes to the grammar could affect existing functionlity.

## Solution
Create a set of automated tests to validate that input queries translate to the correct AST response when parsed by `searchParser.parse`

We can find a set of test cases in [this file](https://docs.google.com/document/d/1IerffQXrkWBHkbvEYtdfM8Izp-lUZOEDBqlrAVikLpY/edit)

The test case should be extensible so that we can easily add more query/result examples to it.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a2286768945350c</li>
        <li>Upwork Job ID: 1829237121495398264</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 103740228</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by ikevin127** [comment]
@luacmartins I'm assuming I should've been assigned as C+ reviewer here ?

**Comment by jaydamani** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Create test files for search parsers
### What is the root cause of that problem?
NA
### What changes do you think we should make in order to solve the problem?

Create SearchParserTest.ts in tests/unit with all the test cases from the document.
Example code with 1 test:
```js
describe("Search Parser", () => {
  it("it should parse correctly", () => {
    let ast = searchParser.parse("type:expense status:all")
    expect(ast).toEqual({
      type: 'expense',
      status: 'all',
      sortBy: 'date',
      sortOrder: 'desc',
      filters: null
    })
  })
})
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jaydamani** [comment]
@luacmartins not sure where to put this but while checking the searchParser.peggy file, I found a bug where if you search for words that start with special words like **in**cident, the output filter is incorrect
```js
{
  ...
  filters: {
    operator: 'eq',
    left: 'in',
    right: 'cident'
  }
}
```
Tested this by pasting [searchParser.peggy](https://github.com/Expensify/App/blob/e054a713a604fd0a16f9eec4b78b8edfc60bfc4f/src/libs/SearchParser/searchParser.peggy) in this [site](https://peggyjs.org/online.html) and then giving inputs like incident, tomato or anything that starts with the [filter keys](https://github.com/Expensify/App/blob/e054a713a604fd0a16f9eec4b78b8edfc60bfc4f/src/libs/SearchParser/searchParser.peggy#L117)

**Comment by luacmartins** [comment]
@jaydamani I can't reproduce that with the latest syntax
![Screenshot 2024-08-29 at 2 37 56 PM](https://github.com/user-attachments/assets/74a09240-1abf-4a17-9940-4efea0a535de)

**Comment by luacmartins** [comment]
@jaydamani the proposal seems good, but can you expand on how we'd handle the many different test cases in a scalable way?

**Comment by jaydamani** [comment]
Since filters are the biggest concern in our test cases, we can do following to simplify them:

## Option 1:
Considering that most test cases have a very deep nesting of just and operator, we can write a function `tranformFilters` that will transform a simplified version of the filter into the ast for the query
```js
const query = "las vegas amount:100"
const filters = {
    op: 'and',
    values: [
        {
            op: 'eq',
            left: 'amount',
            right: 100
        },
        {
            op: 'or',
            values: [
                {
                    op: 'eq',
                    left: 'keyword',
                    right: 'vegas'
                },
                {
                    op: 'eq',
                    left: 'keyword',
                    right: 'las'
                }
            ]
        }
    ]
}

const result = {
    type: 'expense',
    status: 'all',
    sortBy: 'date',
    sortOrder: 'desc',
    filters: transformFilters(filters)
}

expect(searchParser.parse(query)).toEqual(result)
```

## Option 2
Continuing from above thinking, we can also represent filters in the below way but this adds too much abstraction between the actual filter and our representation
```js
const query = "from:usera@user.com to:userb@user.com "
const filters = {
    from: 'usera@user.com',
    to: 'userb@user.com',
    date: {
      op: 'gt',
      value: '2024-12-12'
    }
    keywords: ['keyword1', 'keyword2'],
};

const result = {
    type: 'expense',
    status: 'all',
    sortBy: 'date',
    sortOrder: 'desc',
    filters: transformFilters(filters)
}

expect(searchParser.parse(query)).toEqual(result)
```

## Option 3
If you don't want any complex logic in the test and the only concern is number of tests, we can create an object at top or a json file that looks like below and the tests will just loop the array
```js
[{
    query: "type:expense status:all",
    result: {
        type: 'expense',
        status: 'all',
        sortBy: 'date',
        sortOrder: 'desc',
        filters: null
      }      
}, { 
    query: "in:123333 currency:USD merchant:marriott",
    result: {
        type: 'expense',
        status: 'all',
        sortBy: 'date',
        sortOrder: 'desc',
        filters: {
            operator: 'and',
            left: {
                operator: 'and',
                left: {
                    operator: 'eq',
                    left: 'in',
                    right: '123333'
                },
                right: {
                    operator: 'eq',
                    left: 'currency',
                    right: 'USD'
                }
            },
            right: {
                operator: 'eq',
                left: 'merchant',
                right: 'marriott'
            }
        }
    }
}]
```
looping logic:
```js
describe("search parser", () => {
  tests.forEach(({ query, expected }) => {
    test(`correctly parses "${query}"`, () => {
      const result = parse(query);
      expect(result).toEqual(expected);
    });
  });
});
```

**Comment by jaydamani** [comment]
> @jaydamani I can't reproduce that with the latest syntax ![Screenshot 2024-08-29 at 2 37 56 PM](https://private-user-images.githubusercontent.com/22219519/362883982-74a09240-1abf-4a17-9940-4efea0a535de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NjQ1NTAsIm5iZiI6MTcyNDk2NDI1MCwicGF0aCI6Ii8yMjIxOTUxOS8zNjI4ODM5ODItNzRhMDkyNDAtMWFiZi00YTE3LTk5NDAtNGVmZWEwYTUzNWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDIwNDQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZDVjOGM2Mzg4Nzk4N2JiN2ZhNmY3MmI4YjVjMjIzY2EzNTgzMjNiMjU2NGZjNGI5YzJhZWEzMWQzZWVkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q-DW6aAtarb2euBBI8zJndv7mgoLIkFEctgdD-9NE20)

I tested this on main branch, is there any different branch with latest code for search functionality?
![image](https://github.com/user-attachments/assets/d897ae03-3f74-4620-88ad-c83a1fbcf200)

**Comment by Kicu** [comment]
Hello, I work at an expert agency I wanted to add a small suggestion here, about this:
>  how we'd handle the many different test cases in a scalable way?

There is a dedicated functionality in `jest` to help with testing multiple test cases:
https://jestjs.io/docs/api#each

It might be helpful to use it for our parser unit tests.

**Comment by jaydamani** [comment]
Updated [proposal](https://github.com/Expensify/App/issues/48291#issuecomment-2319165990)

- Included details of [this comment](https://github.com/Expensify/App/issues/48291#issuecomment-2319148379) with better wording
- updated to include [suggestion](https://github.com/Expensify/App/issues/48291#issuecomment-2320404593) from @Kicu

**Comment by luacmartins** [comment]
@jaydamani I think option 3 is what we're looking for here.

**Comment by jaydamani** [comment]
@luacmartins, I will be working on this over the weekend, so the PR should be ready to review by monday.

**Comment by luacmartins** [comment]
@daledah your proposal introduces a buildQuery method, that we don't need. The whole point of the tests is to test the searchParser.parse function that builds the AST. This test should just confirm that for a given string input, e.g. `type:expense status:all`, we should get the correct parsed AST, e.g. `{type: 'expense', status: 'all', sortBy: 'date', sortOrder: 'desc', filters: null}`. The extensibility needed is just us adding more input/expectedValues to the test case without needing to change the test logic.

**Comment by jaydamani** [comment]
Created [this PR](https://github.com/Expensify/App/pull/48383) with comment for failing test cases

**Comment by VictoriaExpensify** [comment]
Not overdue, payment due on 16th

**Comment by ikevin127** [comment]
cc @VictoriaExpensify

**Comment by jaydamani** [comment]
Bump @VictoriaExpensify

**Comment by VictoriaExpensify** [comment]
As this is a new feature, the checklist is not required.

**Comment by VictoriaExpensify** [comment]
@jaydamani - I have sent you an [offer via Upwork](https://www.upwork.com/nx/wm/offer/104016756). Please accept it and I'll organise payment

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor+: @ikevin127 paid $250 via Upwork

**Comment by VictoriaExpensify** [comment]
Thanks @jaydamani 

Updated Payment Summary:
Contributor: @jaydamani paid $250 via Upwork
Contributor+: @ikevin127 paid $250 via Upwork
