### ISSUE TITLE
QBO - Location sync takes some time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48303]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3020346
**Email or phone of affected tester (no customers):** gloginme3+507d@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: new workspace added. Accounting enabled.

1. Connect to QBO
2. Go to Export > Export out-of-pocket expenses as
3. Choose Export as > Journal entry
4. Go to Import > Locations
5. Enable import toggle
6. Go to Tags tab on LHN

## Expected Result:
Locations tags will appear immediately or after several seconds

## Actual Result:
Location tags appears after ~1 min or even more.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/f8710a94-a3c0-4025-aebe-a3f24f96dcfa
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by muttmuure** [comment]
Could be the API causing this

**Comment by muttmuure** [comment]
This is not unexpected behavior. If you choose vendor bills, the option to import locations is not supported: 

https://expensify.slack.com/archives/C06ML6X0W9L/p1721404718126379?thread_ts=1721147953.635009&cid=C06ML6X0W9L

**Comment by IuliiaHerets** [comment]
QA team still can repro this issue, problem is that the Location import takes too long, build - v9.0.37-3

https://github.com/user-attachments/assets/e32cf84c-6ee9-4053-ada6-8de4885e474d

**Comment by muttmuure** [comment]
@trjExpensify I assume this is polish? I can't tell if it's back end though

**Comment by trjExpensify** [comment]
Yeah, any change you make to the integration settings has a 1m delay before it starts syncing the connection. That was a change made somewhere and I got wind of it [here](https://github.com/Expensify/App/issues/48090#issuecomment-2349072393). There's a PR that's merged to stop baking in that delay. Going to close this out.
