### ISSUE TITLE
Web - Attachment - Console log error appears when sending a PDF attachment

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48314]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
Issue was found when executing this PR: https://github.com/Expensify/App/pull/48196
**Email or phone of affected tester (no customers):** applausetester+shsbtra1@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to the staging app
2. Open the JS console in your browser
3. Start a 1:1 DM with any account.
4. Click "+" > "Add attachment" and select the PDF (Attached with this report)
5. Wait until the PDF finishes loading and send the PDF file
6. Observe the console tab while the action is being performed

## Expected Result:
No console error appears

## Actual Result:
"net::ERR_FILE_NOT_FOUND" console error appears. This error occurs when uploading any other PDF file too.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[3008.log](https://github.com/user-attachments/files/16814385/3008.log)
[Bug6587394_1724990527176!Bug6578472_1724261778936.Large_PDF.pdf](https://github.com/user-attachments/files/16814386/Bug6587394_1724990527176.Bug6578472_1724261778936.Large_PDF.pdf)

https://github.com/user-attachments/assets/8cc3266e-6c62-498f-b1ec-cfbc06828d62

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
Looks like being handled in https://github.com/Expensify/App/issues/46615

**Comment by slafortune** [comment]
Agreed - closing
