### ISSUE TITLE
[HOLD for payment 2024-09-16][$250] [Search v2.1] Remove isCustomQuery from URL

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48331]
## Problem
Coming from [here](https://expensify.slack.com/archives/C036QM0SLJK/p1724745439819019), we decided to remove the `isCustomQuery` param from the URL.

## Solution
Remove the param

cc @Kicu 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7e181cb4efa9de7</li>
        <li>Upwork Job ID: 1830622690254016755</li>
        <li>Last Price Increase: 2024-09-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by Kicu** [comment]
I can take this, please assign me.

**Comment by Kicu** [comment]
PR ready - I think it was a good decision because the code ended up being simpler, and we now have only 1 query param in Search - `q` and that sounds like a win to me 👍 

https://github.com/Expensify/App/pull/48414

**Comment by luacmartins** [comment]
PR was deployed to prod 2 days ago on [this checklist](https://github.com/Expensify/App/issues/48664#issuecomment-2338463845)

**Comment by sakluger** [comment]
Commenting for melvin since I have the assignment star.

**Comment by sakluger** [comment]
Monday payment

**Comment by ikevin127** [comment]
Offer accepted, thank you!

**Comment by sakluger** [comment]
Posting the offer so I can find it again on Monday 😄 

@ikevin127 do we need any regression tests for this one? I feel like we don't but curious for your take.

**Comment by ikevin127** [comment]
@sakluger I've asked ([ref1](https://github.com/Expensify/App/issues/46038#issuecomment-2282337481), [ref2](https://github.com/Expensify/App/issues/46032#issuecomment-2282337440), [ref3](https://github.com/Expensify/App/issues/46027#issuecomment-2299416747)) whether regression tests are needed on Search v2.1 related issues and was told ([ref1](https://github.com/Expensify/App/issues/46038#issuecomment-2283520258), [ref2](https://github.com/Expensify/App/issues/46032#issuecomment-2283519749), [ref3](https://github.com/Expensify/App/issues/46027#issuecomment-2299654689)) that regression tests will be added later as part of the project wrap up.

**Comment by sakluger** [comment]
Sounds good, thanks for confirming @ikevin127.

**Comment by sakluger** [comment]
The contract is paid, thanks everyone!
