### ISSUE TITLE
[CVP] Bottom Up - iOS Safari - first name field is focused, but keyboard not open on the "What's your name?" page 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#48333]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05E8R5K55K/p1725026086476479?thread_ts=1725025982.019969&cid=C05E8R5K55K (internal)

## Action Performed:
1. Sign-up on newDot with a new account
2. Choose the manage my teams expenses onboarding intent
3. Observe the business name field is focused and the keyboard is open
4. Click the back caret < 
5. Choose the "get paid back by my employer" intent 
6. Observe the first name field is focused but the keyboard is not open

## Expected Result:
When the first name field is focused, the keyboard should be open. 

## Actual Result:
The first name field is focused, but the keyboard is not open.

## Workaround:
Yes, tap the field to bring up the keyboard. 
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/28c0c2d7-0bce-4242-b066-c9cbc901a89e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by trjExpensify** [comment]
@abdulrahuman5196 what do you think about this proposal?

**Comment by abdulrahuman5196** [comment]
Hi will check today

**Comment by trjExpensify** [comment]
Thanks you!

**Comment by abdulrahuman5196** [comment]
@trjExpensify Are you able to reproduce the issue? Seems to be working fine for me.


https://github.com/user-attachments/assets/294b6a49-ea51-4ae9-87d5-8d0623accc20

**Comment by trjExpensify** [comment]
Yup! Physical device, iPhone 15 Pro (iOS 17.6.1). 

https://github.com/user-attachments/assets/ca04ab3e-f1e5-4ef4-9f6f-93c1d5a70189

**Comment by abdulrahuman5196** [comment]
Checking again

**Comment by trjExpensify** [comment]
Thanks!

**Comment by trjExpensify** [comment]
@abdulrahuman5196 did you check?

**Comment by abdulrahuman5196** [comment]
Not yet. I haven't been able to find how to test dev web in real iPhone's device. Checking with team on the same - https://expensify.slack.com/archives/C02NK2DQWUX/p1725898604633999

**Comment by trjExpensify** [comment]
Cool, thanks for escalating to Slack!

**Comment by abdulrahuman5196** [comment]
Found way to test in physical device.
@trjExpensify In my iphone safari, the keyboard doesn't pop up for any input. Attaching the video here.
iPhone 12, 17.6.1


https://github.com/user-attachments/assets/de114e1e-2c7c-448a-93de-06b2739ff636

Sometime back I remember seeing an issue where focus is not working on safari properly. Not sure if that was solved. But couldn't find that issue, will check in our slack as well if this is something we should solve here.

**Comment by trjExpensify** [comment]
>Found way to test in physical device.
>@trjExpensify In my iphone safari, the keyboard doesn't pop up for any input. Attaching the video here.
>iPhone 12, 17.6.1

But we include autoFocus on the one page and not the other in this flow, so for the devices this does work for that makes it an inconsistent bug, right?

**Comment by trjExpensify** [comment]
https://github.com/Expensify/App/issues/48333#issuecomment-2321442978 - did you check this solution @dominictb?

**Comment by abdulrahuman5196** [comment]
> [#48333 (comment)](https://github.com/Expensify/App/issues/48333#issuecomment-2321442978) - did you check this solution on a physical iPhone device using Safari, @dominictb? Can you include a vid, please.

And FYI seems the autoFocus is removed in the`BaseOnboardingWork` due to some issue https://github.com/Expensify/App/pull/48137#discussion_r1741577470

**Comment by trjExpensify** [comment]
Cool, so @dominictb. Bump on this! 

>https://github.com/Expensify/App/issues/48333#issuecomment-2321442978 - did you check this solution on a physical iPhone device using Safari, @dominictb? Can you include a vid, please.

**Comment by trjExpensify** [comment]
@dominictb still awaiting a vid for confirmation here.

**Comment by trjExpensify** [comment]
>@trjExpensify My solution doesn't work on Safari Physical device. Do you think it's ios behavior to prevent showing keyboard programmatically?

Got it. Then yes, this sounds like the inconsistent upstream bug with mWeb safari we've (unsuccessfully) fought before.

**Comment by abdulrahuman5196** [comment]
>Got it. Then yes, this sounds like the inconsistent upstream bug with mWeb safari we've (unsuccessfully) fought before.

Yep. I think we should close this one IMO. @trjExpensify

**Comment by trjExpensify** [comment]
Yep, closing!
