### ISSUE TITLE
[Advanced Approval Workflows] Cleanup the logic responsible for building `policy.employeeList`

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#48341]
Coming from [this project](https://github.com/Expensify/Expensify/issues/396071), we have this follow-up polish issue – we need to refactor the logic that is responsible for building the data on the frontend that is later sent to update `policy.employeeList`.

Having following policy:
```
Admin: A
Member: 1
Member: 2
```

When advanced approvals is turned on, the employee list looks like this:
```
A submitsTo A
1 submitsTo A
2 submitsTo A
```

If I edit that workflow to set 2 as the additional approver, the frontend sends this payload:
```
A submitsTo A forwardsTo 2
1 submitsTo A
2 submitsTo A
```

**That's mostly OK, but since submitsTo isn't changing for anyone, the payload could be more simple with just:**
```
A forwardsTo 2
```

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by tgolen** [comment]
What's the status of this? Are we just waiting for the PR to be deployed to production? I see it was deployed to staging 2 weeks ago, but surely there has been a production deploy since then?

**Comment by DylanDylann** [comment]
@anmurali Please help to handle payment here

**Comment by tgolen** [comment]
@anmurali can you please assist with paying @DylanDylann for a C+ review of the PR?

**Comment by DylanDylann** [comment]
@anmurali Please help to check the above comment

**Comment by anmurali** [comment]
Offer is [here](https://www.upwork.com/nx/wm/offer/104340801)

**Comment by DylanDylann** [comment]
@anmurali Great! I accepted it
