### ISSUE TITLE
[$250] Dupe detection - "Keep this one" button appears when there is a paid expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48366]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:**Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense and pay it.
4. Submit another two same expenses as Step 3.
5. Go to transaction thread (any expense).
6. Click Review duplicates.
7. Note that Keep this one button does not appear when there is a paid expense.
8. Click Keep all.
9. Submit another expense that is same as the previous expenses.
10. Go to transaction thread of the new expense.
11. Click Review duplicates.
12. Note that now "Keep this one" button appears for the other two expenses in Step 4 which did not have the button previously and only the newest expense does not have the button.

## Expected Result:
"Keep this one" button should not appear for all expenses in Review duplicates flow when there is a paid expense.

## Actual Result:
"Keep this one" button appears for all expenses in Review duplicates flow when there is a paid expense.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b6fcb1c2-51d5-4ea2-a787-be5bf7db6752

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01647e38725804bb80</li>
        <li>Upwork Job ID: 1829614254279842129</li>
        <li>Last Price Increase: 2024-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103803663</li>
<li>Krishna2323 | Contributor | 103803665</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by marcochavezf** [comment]
Dupe detection is under beta

**Comment by c3024** [comment]
Each transaction seems to have its own `MoneyRequestPreviewContent`, so it looks more appropriate to check the lengths of `allDuplicates` and `duplicates` for that transaction, as suggested in the main solution of @Krishna2323's [proposal](https://github.com/Expensify/App/issues/48366#issuecomment-2322377408), rather than getting violations from the transaction that led us to the review duplicates modal, as suggested in the alternative solution.

IMO we should proceed with the primary solution suggested by @Krishna2323.

🎀 👀 🎀 C+ Reviewed

**Comment by marcochavezf** [comment]
Hey guys, thanks for the patience here. I agree with @c3024's decision, assigning @Krishna2323 🚀 

@dominictb thanks for bringing this up, if we find out that we'd need to include part of your proposal in the final PR, we can make a partial payment :)

**Comment by c3024** [comment]
I already reviewed the PR. It was merged and deployed to staging 5 days ago.

**Comment by c3024** [comment]
PR [deployed to production](https://github.com/Expensify/App/releases/tag/9.0.31-26) on 11-Sep. Automation failed here and on the PR. I think this should be on HOLD for payment till 18-Sep or 19-Sep.

cc: @VictoriaExpensify

**Comment by c3024** [comment]
@VictoriaExpensify, gentle bump for payment. Automation failed here.

**Comment by mallenexpensify** [comment]
Contributor: @Krishna2323 paid $250 via Upwork
Contributor+: @c3024 paid $250 via Upwork.  

Test case created, thx @c3024 and @Krishna2323 
- https://github.com/Expensify/Expensify/issues/432112
