### ISSUE TITLE
[Workspace Feeds] Expensify Card - Card name does not change each time a different member is selected

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48376]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.27
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
Issue was found when executing this PR: Exp https://github.com/Expensify/App/pull/48317
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has bank account set up.
- Workspace has a few members.

1. Go to staging.new.expensify.com
2. Go to Workspace settings > Expensify Card.
3. Click Issue new card.
4. Select Member A.
5. Proceed all the way to the confirmation page (final step) but do not click Issue card button.
6.Click RHP back button to return to the first step which is member selection page.
7. Select Member B.
8. Proceed to "Give it a name" step.
9. Note that the name is still Member A instead of Member B.
10. Go to Members.
11. Click on Member C.
12. Click New card.
13. Proceed to "Give it a name" step.
14. Note that the name is still Member A instead of Member C.

## Expected Result:
In Step 9 and 14, the card name should change each time a different user is selected.

## Actual Result:
In Step 9 and 14, the card name does not change each time a different user is selected.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1bdb1dfd-aecf-4897-ba92-cab79675405f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by koko57** [comment]
As I am the author of the PR that caused the regression I would like to fix it. It should not be a deploy blocker as the functionality is behind the beta. 

cc @mountiny

**Comment by mountiny** [comment]
Not a blocker this is behind beta

**Comment by mountiny** [comment]
@koko57 are you able to fix this in one of the PRs for a clean up

**Comment by koko57** [comment]
@mountiny all the PRs for cleanup were merged 🙂 So I need to open a new one

**Comment by koko57** [comment]
PR opened https://github.com/Expensify/App/pull/48408

**Comment by trjExpensify** [comment]
This is on prod, closing.
