### ISSUE TITLE
mWeb - Chat-In mweb, VOIP conversation error report is displayed in LHN but not in Android

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch site in mweb and androidTap fab -- start chat
2. Enter +1 631-791-8378 and open the conversation with the user
3. Note voip number error displayed
4. Navigate to LHN

## Expected Result:
In mweb and in Android , VOIP conversation error report must not be displayed in LHN.

## Actual Result:
In mweb, VOIP conversation error report is displayed in LHN but not in Android.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/401b5c0f-fedb-44ed-9058-c84312bb0042

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment]
I asked in Slack https://expensify.slack.com/archives/C03U7DCU4/p1725474090012569

**Comment by sakluger** [comment]
I confirmed with the team that we block VoIP numbers.
