### ISSUE TITLE
Scan - Admin sees 403 page instead receipt

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48399]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4910976
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. As employee, in workspace chat create a split scan expense by uploading image taken using camera
3. Login mweb as admin
4. Open workspace chat
5. Note instead of split expense receipt, 403 page displayed.

## Expected Result:
As employee creating scan split expense using camera image as receipt, admin must not see 403 page and receipt must be shown.

## Actual Result:
As employee creating scan split expense using camera image as receipt, admin sees 403 page instead receipt.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7d28b6dc-0735-458c-9f33-1b0a5c090471

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by anmurali** [comment]
![IMG_E4C99DCB4EC1-1](https://github.com/user-attachments/assets/2f43fe21-c40c-4d3a-87b5-c7762084f9de)

It is properly split for me.
