### ISSUE TITLE
[$250] [CVP] Replace the mention in the task preview with the assigned user's avatar

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#48409]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.27-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C07HPDRELLD/p1725028109496029 (Internal)

## Action Performed:
1. Sign-up on NewDot with a new account
2. Choose an onboarding intent (i.e "Get paid back by my employer")
3. Complete the onboarding steps
4. Navigate to the Concierge DM to view the onboarding tasks created

## Actual Result:
Assigned tasks include a mention of the assigned user in the task preview, but it makes it very difficult to avoid navigating to the assigned user's profile when clicking the task.

https://github.com/user-attachments/assets/14a29fd9-b33b-4450-9aa5-37b8d97105c3

## Expected Result:
This is working as expected, but we want to change all assigned task previews to: 

- Not include a mention 
- Use only the avatar of the assigned user instead
- Clicking on the task preview row (incl. the avatar) will navigate to the task, not the profile.

![CleanShot 2024-08-30 at 11 13 55@2x](https://github.com/user-attachments/assets/91d0cbf6-2d22-4ed8-97fa-eeb13b905e94)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Yes, click the right caret. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

See above in-line. 

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @Expensify/design @JmillsExpensify @anmurali @danielrvidal @puneetlath 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c485c16de75a6534</li>
        <li>Upwork Job ID: 1830665670183169524</li>
        <li>Last Price Increase: 2024-09-02</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103801280</li>
<li>dominictb | Contributor | 103801282</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by trjExpensify** [comment]
Yep, all tasks!

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Show assignee avatar instead of the email for task preview.

### What is the root cause of that problem?
New redesign.

### What changes do you think we should make in order to solve the problem?

In TaskPreview,

1. Get the assignee avatar
```
const [assigneeAvatar] = useOnyx(ONYXKEYS.PERSONAL_DETAILS_LIST, {selector: personalDetails => personalDetails?.[taskAssigneeAccountID]?.avatar});
```

2. Replace the assignee mention with the avatar + task title
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/ReportActionItem/TaskPreview.tsx#L113
```
{taskAssigneeAccountID > 0 && <Avatar
    containerStyles={[styles.mr2, styles.taskCheckboxWrapper]}
    source={assigneeAvatar}
    size={CONST.AVATAR_SIZE.SUBSCRIPT}
    avatarID={taskAssigneeAccountID}
    type={CONST.ICON_TYPE_AVATAR}
/>}
<Text style={styles.flex1}>{taskTitle}</Text>
```

<img width="1346" alt="image" src="https://github.com/user-attachments/assets/ba1fa187-3379-4ee4-9f0b-d7d715bb424d">

**Comment by blimpich** [comment]
Strange. @zanyrenney looks like this is ready for payment.

**Comment by zanyrenney** [comment]
**payment summary**

paid $250 📣 @dukenv0307 🎉  via UW.
paid $250 📣 @dominictb 🎉 via UW.
