### ISSUE TITLE
[HOLD for payment 2024-10-02] [CVP] Private domain email is being prompted to "Add work email" in the VBBA flow and then redirecting to OldDot settings when clicked

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#48420]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** tom+manual1@trj.chat
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** 

## Action Performed:
1. Create a workspace
2. Go to `More features` 
3. Enable `Workflows`
4. Go to `Workflows` page, enable `Payments`
5. Click `Connect bank account`
6. Add a VBBA (Instructions [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1711049892429129?thread_ts=1711049879.962529&cid=C01GTK53T8Q))
7. Go through the steps to completion
8. Observe the "One more thing!" step to `Add work email`
9. Click the `Add work email` button 
10. Observe the redirect to OldDot settings

## Expected Result:
1. tom+manual1@trj.chat is a private domain email, I shouldn't have to add a work email address as a secondary login 
2. If we _do_ need to show the "Add work email" step, clicking the button should redirect to NewDot settings here: https://new.expensify.com/settings/profile/contact-methods/new

## Actual Result:
1. I was prompted to "Add work email" despite my account being a private domain 
2. When clicked, I was redirected to OldDot settings to add a secondary login.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/fcef61ee-3a69-4440-acec-30f425005b71">

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/adc7fd01-04d8-4bc5-a40b-b416acb754ed">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by trjExpensify** [comment]
@abzokhattab that sounds like it addressing the part of redirecting to the right place, but what about why I'm being asked to `Add work email` when the account I'm using is a private domain email already.

**Comment by trjExpensify** [comment]
> only if the domain is **not** a private one

**Comment by trjExpensify** [comment]
>Kill this entire logic as Workspace feeds is about to be released making it not required.

Yeah, on reflection, this is the right course of action here. It's a redundant step with workspace feeds, we don't need you to add a privateEmail any more. CC: @JmillsExpensify @mountiny agree? 🪓

**Comment by mountiny** [comment]
I agree to remove this, its been confusing for the users too

**Comment by trjExpensify** [comment]
Okay, great! @shubham1206agra let's do that then.

**Comment by trjExpensify** [comment]
PR merged!

**Comment by JmillsExpensify** [comment]
Payment summary:

 - Contributor: $250 @shubham1206agra 
 - Reviewer: $250 @aimane-chnaif

**Comment by JmillsExpensify** [comment]
Offers sent to both.

**Comment by JmillsExpensify** [comment]
@aimane-chnaif for yours, please complete the BZ checklist beforehand.

**Comment by JmillsExpensify** [comment]
All paid out. Thanks for the regression test. I'll get one created.
