### ISSUE TITLE
[HOLD for payment 2024-10-17] Tracker: Patch and Bump for date-fns-tz

### ISSUE THREAD

**Issue by hurali97** [Expensify/App#48448]
### Description

This issue is a tracker for reverting the patch and bumping `date-fns-tz` to the version which contains our changes. For context, we created a PR to upstream [here](https://github.com/marnusw/date-fns-tz/pull/297) but we didn't get any feedback, so we are proceeding with creating a patch in Expensify [here](https://github.com/Expensify/App/pull/48404).

The ultimate goal is to revert the patch PR in Expensify, once PR to `date-fns-tz` is merged and available on NPM. Then we will have to bump `date-fns-tz` in Expensify.

**Comment by szymonrybczak** [comment]
The patch for `date-fns-tz` was merged and released in v3.2.0, I'll try to bump this version, but the `peerDependency` of this version is `"date-fns"` with versions `"^3.0.0 || ^4.0.0"`, so `date-fns` should be also reviewed and bumped.

**Comment by dangrous** [comment]
Do we need payment on this one? (Should I assign a BZ?) I think no, right?

**Comment by dangrous** [comment]
hi @slafortune! @dukenv0307 reviewed the linked PR which was raised by one of our agencies. I think the standard $250 should be fine here!

**Comment by slafortune** [comment]
Offer sent [here](https://www.upwork.com/nx/wm/offer/104486009) @dukenv0307

**Comment by slafortune** [comment]
Paid
