### ISSUE TITLE
[$250] Company cards - “Assign card” and “Settings” buttons are below intro modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Company Cards.

## Expected Result:
“Assign card” and “Settings” buttons should be at the top of the of the page and above the intro modal.

## Actual Result:
“Assign card” and “Settings” buttons are below the intro modal.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/25f38cf0-4afc-4ee1-8e6c-6df02f9e399f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fcc55f0c4c0d495b</li>
        <li>Upwork Job ID: 1830935252821009051</li>
        <li>Last Price Increase: 2024-09-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by VickyStash** [comment]
This issue will be fixed in [this PR](https://github.com/Expensify/App/pull/48176). This functionality is still under active development.
cc @joekaufmanexpensify @koko57

**Comment by joekaufmanexpensify** [comment]
Ah awesome. Perhaps we can close this one then?

**Comment by VickyStash** [comment]
@joekaufmanexpensify Yeah, I think it makes sense

**Comment by carlosmiceli** [comment]
Great!
