### ISSUE TITLE
[HOLD for payment 2024-09-24][$1250] [Search v2.3] [App] Update the advanced filters view

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#48453]
We need to update Search's advanced filters view to include the `Save Search` functionality.

More details [here](https://docs.google.com/document/d/1UDofUSeSvVijmOH_UIlPQMF0ZI90-ZN2hxUt0npVmeI/edit#bookmark=kix.qujcxx3xabdu)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838573229478534392</li>
        <li>Upwork Job ID: 1838573229478534392</li>
        <li>Last Price Increase: 2024-09-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by luacmartins** [comment]
This is done.

**Comment by lakchote** [comment]
@sakluger 

@jjcoffee thoroughly reviewed a [PR](https://github.com/Expensify/App/pull/48566) that solved 5 issues closely related.

As such, since this was a meaty PR, I suggest to pay him 1250$ ($250 x 5).

**Comment by luacmartins** [comment]
Is the payment being handled somewhere else?

**Comment by jjcoffee** [comment]
@luacmartins There wasn't any payment issue created so I think we're just handling it here!

@sakluger This one should be due payment now as it was [deployed](https://github.com/Expensify/App/pull/48566#issuecomment-2353604479) last week.

**Comment by sakluger** [comment]
@jjcoffee here's the Upwork offer: https://www.upwork.com/nx/wm/offer/104108657. Let me know once you've accepted.

Do you think we need to add regression tests for this?

**Comment by luacmartins** [comment]
@sakluger please check out [this comment](https://github.com/Expensify/App/issues/48453#issuecomment-2360865789). The PR linked to this issue was quite large and solved 5 issues, so we decided to handle compensation for all 5 issues here, so the amount is $1250.

**Comment by sakluger** [comment]
@luacmartins thanks for the context! Most of our issues pay $250 or $125, so I assumed it was a typo.

@jjcoffee sorry for the confusion. Here is the new offer: https://www.upwork.com/nx/wm/offer/104115502

**Comment by luacmartins** [comment]
Np! all good

**Comment by jjcoffee** [comment]
@sakluger No worries, offer accepted!

**Comment by sakluger** [comment]
Paid!

@jjcoffee do we need to add any new regression test steps before closing this issue, or is that being handled elsewhere?

**Comment by luacmartins** [comment]
We'll handle it as part of the project wrap up
