### ISSUE TITLE
[Search v2.3] [App] Update the Search LHN to include saved searches

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#48454]
We need to update the Search LHN to include saved searches.

More details can be found [here](https://docs.google.com/document/d/1UDofUSeSvVijmOH_UIlPQMF0ZI90-ZN2hxUt0npVmeI/edit#bookmark=kix.87eyp686f5py)

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by luacmartins** [comment]
This is done
