### ISSUE TITLE
[Search v2.3] [App] Allow deleting saved searches

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#48457]
We need to allow deleting saved searches.

More details [here](https://docs.google.com/document/d/1UDofUSeSvVijmOH_UIlPQMF0ZI90-ZN2hxUt0npVmeI/edit#bookmark=kix.dyakqbi1ooao).

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by luacmartins** [comment]
Done
