### ISSUE TITLE
[Search v2.3] [App] Update the mobile menu for Saved Searches

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#48455]
We need to update the mobile menu for Saved Searches.

More details [here](https://docs.google.com/document/d/1UDofUSeSvVijmOH_UIlPQMF0ZI90-ZN2hxUt0npVmeI/edit#bookmark=id.kmfi2gv9m9mo)

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by luacmartins** [comment]
Done
