### ISSUE TITLE
[Search v2.3] [App] Allow renaming saved searches

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#48458]
We need to allow renaming saved searches.

More details [here](https://docs.google.com/document/d/1UDofUSeSvVijmOH_UIlPQMF0ZI90-ZN2hxUt0npVmeI/edit#bookmark=kix.c8rkaafjimmb)

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by luacmartins** [comment]
Done
