### ISSUE TITLE
Invoice - After paying invoice as business, for remaining invoice only business option show

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48467]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team 

## Action Performed:
Pre-condition: Both user uses a new account with a workspace already created
1. Launch app
2. Tap fab -- send invoice
3. Enter an amount and tap next
4. Select user B
5. Tap send invoice
6. Tap plus ucon -- send invoice
7. Create 3 more invoice
8. Login mweb as user B
9. Open invoice chat
10. Check all invoice has 2 pay options
11. Pay last invoice as individual and check still all invoice has 2 options
12. Pay an invoice as business and check all other invoice now only has business option

## Expected Result:
After paying invoice as business, for remaining invoice only business option displayed & individual option must not be disappeared.

## Actual Result:
After paying invoice as business, for remaining invoice only business option displayed & individual option disappeared.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f487968e-59f3-42c5-84fc-5cc9d5b38cea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jacobkim9881** [comment]
This is intended.

https://github.com/Expensify/App/blob/2de5aea46d5b457312d96c4bcbd55099760a660a/src/libs/actions/IOU.ts#L6608-L6613
