### ISSUE TITLE
[$250] Company cards - App crashes when enabling “Allow deleting transactions”

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48460]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Company cards
3. Tap Settings.
4. Enable “Allow deleting transactions”.

## Expected Result:
App will not crash after enabling “Allow deleting transactions”.

## Actual Result:
App crashes after enabling “Allow deleting transactions”.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

[0309.txt](https://github.com/user-attachments/files/16848141/0309.txt)

https://github.com/user-attachments/assets/22381ef9-d462-4994-9fa2-50b59dadcb6f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177bfb8694e7ac7da</li>
        <li>Upwork Job ID: 1830944843037262347</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 103795111</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by joekaufmanexpensify** [comment]
Agreed. This doesn't need to be a blocker IMO since no customers are using this. Demoting to daily for now, but LMK if you disagree @flodnv

**Comment by joekaufmanexpensify** [comment]
Assigning @ZhenjaHorbach too as you reviewed [the PR](https://github.com/Expensify/App/pull/48185) that introduced this

**Comment by joekaufmanexpensify** [comment]
Yeah, I think having @narefyev91 fix this makes sense since he is working on the project.

**Comment by robertjchen** [comment]
This feature is under beta
