### ISSUE TITLE
Contact method - App signs out when adding a new contact method after removing previous one

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48472]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/48320
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign up with a new gmail account
3. Go to settings and contact methods
4. Validate your account
5. Add a new contact method
6. Validate the newly added contact method
7. Remove the newly added and validated contact method
8. Click on add a new contact method
9. Insert email and click on next

## Expected Result:
App allows user to add a new contact method

## Actual Result:
App signs out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
 
https://github.com/user-attachments/assets/3a25efcd-76e3-43ca-ae17-b3143ab2c4a5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jacobkim9881** [comment]
I think new session shouldn't be merged from BE API while validating the newly added contact method. 

```js

request: {command: "ValidateSecondaryLogin", data: Object, successData: Array, failureData: Array}

response: Object

jsonCode: 200

lastUpdateID: 1624947486

onyxData: Array (2)
0 Object

key: "session"

onyxMethod: "merge"

value: {authToken: "842E0F923BDEB57867C003B7367A72A980FDB1898B5EB5E7A9…7C022EACAC0D7759042CEDB034A138D5A56DBCCC083C23D9A"}

```

I guess the session is for the new account so removing the new contact method let session expired.

**Comment by jacobkim9881** [comment]
https://github.com/Expensify/App/pull/48320 would be related to this issue.

**Comment by bfitzexpensify** [comment]
Hm, I'm going to close this as an edge case, it is hard to picture as a common flow
