### ISSUE TITLE
[$250] IOU-Submit expense on foreign currency, total briefly greyed out on top

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48478]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Open 1:1 chat with no prior conversation
3. Create 2 submit expense in local currency
4. From report page, create one more expense in local currency
5. Note total is not greyed out on top
6. Create a expense in foreign currency
7. Note total is briefly greyed out on top

## Expected Result:
Submit expense on foreign currency, total briefly must not be greyed out on top.

## Actual Result:
Submit expense on foreign currency, total briefly greyed out on top.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/35e10933-c7b0-4d0d-b7a5-880552b4097f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831692684862783385</li>
        <li>Upwork Job ID: 1831692684862783385</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104054700</li>
<li>nyomanjyotisa | Contributor | 104054702</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by IuliiaHerets** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dubielzyk-expensify** [comment]
Ah interesting. Yeah I'd prefer for us to do something more loading-y. Either `...` or `--`. I forget where we do something similar, but perhaps other @Expensify/design remembers or have better suggestions

**Comment by shawnborton** [comment]
I'd also be fine even if we replaced the amount with our simple loading spinner while it calculated (so long as the height doesn't change so we don't get any jumpiness)

**Comment by dannymcclain** [comment]
>I'd also be fine even if we replaced the amount with our simple loading spinner while it calculated (so long as the height doesn't change so we don't get any jumpiness)

I like this idea. And if the spinner doesn't work, I like Jon's suggestion of using `...`. But I'm aligned with them that it would be nice to indicate loading/calculating somehow.

**Comment by shawnborton** [comment]
We have an existing generic loading spinner in the app we can use. It would basically look like this:
![CleanShot 2024-09-18 at 12 14 01@2x](https://github.com/user-attachments/assets/3439975a-ca8a-4aac-9593-62fef1452eeb)

**Comment by mallenexpensify** [comment]
`Reviewing` label was stuck, @muttmuure pay plz

**Comment by muttmuure** [comment]
Looking now

**Comment by muttmuure** [comment]
Paid
