### ISSUE TITLE
Distance - android - Creating distance expense with big distance rate, invalid amount error shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48480]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre: condition : 1. Open account with workspace created and distance rate enabled
2. Open rate and change it to big amount eg: 88888888.888 and save
1. Launch app
2. Open workspace chat
3. Create distance request
4. Enter start & stop points and tap next
5. Tap submit

## Expected Result:
When distance rate is set as big number, on creating distance expense, invalid amount must not be shown

## Actual Result:
When distance rate is set as big number, on creating distance expense, invalid amount is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ac2f8be9-4f89-4328-9ff6-25f7fc5ab645

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
This honestly seems ridiculous to me. Distance expenses will never be hundreds of thousands of dollars IMO.

Asking here - https://expensify.slack.com/archives/C036QM0SLJK/p1725411079643849

**Comment by jliexpensify** [comment]
Confirmed, going to close this one - it's not likely anyone will create such a large mileage rate.

**Comment by jliexpensify** [comment]
@abzokhattab this issue applies to the rate, correct? Why I don't think this will be an issue is that, usually, rates will never be that high. Mileage is usually a couple of dollars at the most.
