### ISSUE TITLE
Group chat - Group chat with custom name and avatar is not displayed on LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** [gocemate+a2041@gmail.com](mailto:gocemate+a2041@gmail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to +> Start chat> Create group chat with custom name and custom avatar
2. Take a look at LHN

## Expected Result:
Group chat should be present on LHN

## Actual Result:
Group chat with custom avatar does not appear on LHN. User can navigate to this chat only via Search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9cc04cb5-4073-4762-b60e-0e890d11b7e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
It is expected. It won't appear in LHN until you send the first message.

**Comment by RachCHopkins** [comment]
Thanks @FitseTLT I was struggling to reproduce - probably because I immediately sent a message!
