### ISSUE TITLE
Track request appears on Self-DM when come back online if submit to someone in offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48494]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go offline
2. Go to +> Track> Complete the flow
3. Select Submit it to someone from actionable whisper> Complete the flow
4. Go online
5. Take a look at Self-DM chat on LHN

## Expected Result:
The chat should be unbolt and the request should not be present there since it is submitted to someone

## Actual Result:
Track request appears on Self-DM chat on LHN when come back online if user create request and submit to someone in offline mode

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a11dc327-8ba8-460b-82bc-2862daacc80a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by joekaufmanexpensify** [comment]
Track expense is a part of #vip-vsb, which paused entirely. This seems like a backend issue to me based on the error I'm seeing. Closing for now as we aren't prioritizing this project.
