### ISSUE TITLE
Track - Playback speed menu from Track your expenses modal is cut off when exit full screen

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48490]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4913022&group_by=cases:section_id&group_order=asc&group_id=309130
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to FAB> Track
2. Verify "Track your expenses" modal appears
3. Open this modal in full screen
4. Exit full screen
5. Open the Playback speed option from 3-Dot menu

## Expected Result:
Playback speed menu from Track your expenses modal should be fully visible

## Actual Result:
Playback speed menu from Track your expenses modal is cut off when exit full screen

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2c18386c-11f5-4105-b14d-f62f604d9fb9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment]
I can't quite reproduce this one - I'm on a slightly later version (v9.0.29-6) and this is a fairly minor bug so closing!


https://github.com/user-attachments/assets/69ca4c68-9e36-4714-85cf-0b4dd95888e7
