### ISSUE TITLE
[HOLD] [Polish] [OldDotRules Migration] Clean up various amount form logic

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#48499]
# Problem

Coming from [this comment](https://github.com/Expensify/App/pull/47468/files#r1729548224) it seems there is a lot of duplicate logic pertaining to the various "amount forms" in the codebase. With each new feature we have been copying logic related to setting the selection, formatting the amount, etc. Instead of creating a re-usable component.

# Solution

Explore refactoring these components so that there is a standard "amount form" that can be used throughout the app.

**Comment by RachCHopkins** [comment]
@marcaaron is there anything that I need to do on this yet?

**Comment by marcaaron** [comment]
Nah I'm gonna remove the New Feature label for now sorry for the distraction. I'll re-add it if we end up doing this.

**Comment by marcaaron** [comment]
Ok, gonna close this out for now. This was an optional thing that we probably don't need to spend time on right now.
