### ISSUE TITLE
Profile - User receives a magic code instead of the secondary login verification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48501]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4912495
**Email or phone of affected tester (no customers):** fischer9966+090224aa@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com or open Expensify App
2. Login with Gmail account
3. Go to Settings > Profile > Contact Method
4. Tap to "New Contact Method"
5. Enter new email for secondary login

## Expected Result:
User receives email with verification code for the secondary login

## Actual Result:
User receives a magic code for primary login instead of verification code for the secondary login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f11a7129-3130-4174-b787-c3d833683c7d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@lanitochka17 This is now the new expected behaviour as described in this PR https://github.com/Expensify/App/pull/48320

To add a secondary login, the user now has to first validate they have access to the primary login by adding that magic code first. Only then, if successful, they can validate the secondary login.

Can you please update the testrail accordingly?

**Comment by isagoico** [comment]
TC - https://expensify.testrail.io/index.php?/cases/view/2593732 - Has been updated to reflect this behavior.

**Comment by mountiny** [comment]
Thanks!
