### ISSUE TITLE
[HOLD for Payment 2024-09-18] [$125] [Search v2.1] Fix Text component styles on Android

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48509]
### Problem
Coming from [this comment](https://github.com/Expensify/App/pull/47676#issuecomment-2321534372), the Text component is truncating text even though there's available space to display more text in it.

### Solution
Fix the styles for the Text component

cc @Guccio163 

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831356735046116589</li>
        <li>Upwork Job ID: 1831356735046116589</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103815305</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment]
@luacmartins was [this](https://github.com/Expensify/App/issues/48509#issuecomment-2343215111) a regression that would affect payment?

**Comment by luacmartins** [comment]
Yes

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $125 @rayane-djouah ([offer](https://www.upwork.com/nx/wm/offer/104033100))

Upwork job is [here](https://www.upwork.com/ab/applicants/1831356735046116589/hires?filter=rayane%20d&page=1).
