### ISSUE TITLE
[Hold for Payment 2024-09-19][$250][Search v2.1]  Filters button should not be shown on Search page during "select mode".

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48511]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dannymcclain 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725380044951249

## Action Performed:
1. Go to staging.new.expensify.com
2. Click Search and select few expenses
## Expected Result:
Filters button should not be shown on search during select mode
## Actual Result:
Filters button are shown on search during select mode
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-09-03 at 11 13 12@2x](https://github.com/user-attachments/assets/1557c8ae-5152-420d-b606-7ee7ee0b8ba9)

![Snip - (32) New Expensify - Google Chrome](https://github.com/user-attachments/assets/f41b95a7-6f7c-4058-a2ce-b7574633d8fd)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832173197655902215</li>
        <li>Upwork Job ID: 1832173197655902215</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 103886050</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by Guccio163** [comment]
Hi, I'm Wiktor Gut from SWM agency and I'll gladly take this issue!

**Comment by mallenexpensify** [comment]
@jjcoffee plz review the proposals above, thx

**Comment by Guccio163** [comment]
Hi @luacmartins, can you please take a peek at this bug and assign it? It's a pretty small thing connected directly to Search, so I'd love to handle it quickly as part of SWM 🙏

**Comment by luacmartins** [comment]
Sorry everyone, this is part of the Search project and @Guccio163 is working on this already.

**Comment by mallenexpensify** [comment]
@abzokhattab and @nyomanjyotisa , once the linked PR has been on production for 7 days, without a regression, I'll review this issue for potential payment.  One key point to consider here is this from CONTRIBUTING.md .    

> You can propose solutions on any issue at any time, but if you propose solutions to jobs before the Help Wanted label is applied, you do so at your own risk. Proposals will not be reviewed until the label is added and there is always a chance that we might not add the label or hire an external contributor for the job.

That doesn't guarantee that no one else will be eligible for compensation, I'll update everyone at the end.

**Comment by jjcoffee** [comment]
@luacmartins I think you closed this by mistake?

**Comment by luacmartins** [comment]
Oh for some reason my merge commit closed the issue. Reopening.

**Comment by jjcoffee** [comment]
- The PR that introduced the bug has been identified. Link to the PR: N/A - just a missed feature
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: B/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open Search page
2. Ensure no reports are selected
3. Verify that the `Filters` button is visible and that `X selected` is not visible
4. Select a few reports
5. Verify that the `Filters` button is no longer visible and that the `X selected` button becomes visible

Do we agree 👍 or 👎

**Comment by luacmartins** [comment]
Thanks! No need for regression tests at this time, we'll add them as part of the project wrap up

**Comment by mallenexpensify** [comment]
Contributor: @jjcoffee paid $250 via Upwork

Thx!

**Comment by luacmartins** [comment]
@nyomanjyotisa @abzokhattab sorry, but this was within the regression period and the Search project is being handled by SWM and myself, so we won't be able to issue additional payments at this time.

**Comment by mallenexpensify** [comment]
To provide more details... 
- Proposals were submitted before `Help Wanted` was added. 
- @Guccio163 from SWM [posts that they want to work on it. ](https://github.com/Expensify/App/issues/48511#issuecomment-2328035912)
- I add the `External` label [to assign a C+](https://github.com/Expensify/App/issues/48511#event-14167316898)
- I [remove the ](https://github.com/Expensify/App/issues/48511#event-14167318504)`Help Wanted` label 

Based on the above, compensation isn't due. 
@Guccio163 if you referenced the proposals and used any code from those (for all or part of the PR), please comment and provide details. Thx
