### ISSUE TITLE
Import categories - Column is out of page when importing txt file

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48536]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47827
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Control workspace settings > Categories.
3. Click 3-dot menu.
4. Click Import spreadsheet.
5. Import the following txt file.

## Expected Result:
The column will be wrapped properly.

## Actual Result:
The column is out of page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fe913f91-05fc-4cd7-97fc-73f47a4bc547

[0409.txt](https://github.com/user-attachments/files/16868521/0409.txt)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
cc @filip-solecki @rushatgabhane @rlinoz coming from the import spreadsheet PR

**Comment by mountiny** [comment]
@filip-solecki can handle this one, I think we can treat this as a blocker

**Comment by Julesssss** [comment]
Thanks Vit

**Comment by isagoico** [comment]
I'm still able to reproduce this issue when importing a .txt file

![image](https://github.com/user-attachments/assets/5a6b8858-f1c2-4e71-a6b1-6d71b44c6b60)

**Comment by mountiny** [comment]
Demoting this as the files used to reproduce this are not really files that real user would use for this feature. So its edge case ad absurdum and we can discuss if we want to somehow validate the file contents and throw error in cases like this or do nothing

**Comment by tuseefahmed786** [comment]
The text in this column is overflowing because it's too long or all on one line. You can fix it by adding this CSS property `word-break: break-all;` I've also attached a screen recording for you to check. 

https://www.loom.com/share/e7a7d987384c46438cedc2fe7c8eb50d?sid=f1e9a455-9434-4a9a-9b5a-9ff0f5618c08

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this

**Comment by filip-solecki** [comment]
I've tested `word-break: break-all` suggestion and it seems to be working, but I am not sure if this is what we want, because right now we can get something like this:
![Screenshot 2024-09-05 at 13 28 16](https://github.com/user-attachments/assets/c044daa8-3651-4f74-a311-8b28585e72b1)

If we are ok with that I can prepare PR, otherwise I'll look for other possible solutions

**Comment by filip-solecki** [comment]
I tried different solutions, but only this one was working, I've prepared a PR, but if you think we have to find some other solution than feel free to open the issue for externals, maybe someone will find something better. Additionally I've pushed here some translations fixes.
cc @mountiny

**Comment by miljakljajic** [comment]
I _think_ this one has gone to prod? Do we just need a payment summary for @rushatgabhane ?

**Comment by miljakljajic** [comment]
Payment summary for @rushatgabhane:

@rushatgabhane is owed 250 for their work reviewing this PR

**Comment by miljakljajic** [comment]
@mountiny I will unassign myself for my parental leave now, but if in the end we need another BZ team member on this for any reason, please assign. thank you!
