### ISSUE TITLE
[HOLD for payment 2024-09-12][$125]  Import categories - GL code field shows undefined when imported category does not have GL code

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48535]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Control workspace settings > Categories.
3. Click 3-dot menu.
4. Click Import spreadsheet.
5. Import the following CSV file.
6. Map Name, Enabled and GL code.
7. Click Import.
8. Click on the category that does not have GL code.

## Expected Result:
GL code field will be empty.

## Actual Result:
GL code field shows undefined.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

[Bug6592371_1725411660406!Independent.-.Multi.Level.tags.csv](https://github.com/user-attachments/files/16868184/Bug6592371_1725411660406.Independent.-.Multi.Level.tags.csv)

https://github.com/user-attachments/assets/777b5779-bc4a-49f8-b8b5-4e4c6ed8cb1b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831645173273110226</li>
        <li>Upwork Job ID: 1831645173273110226</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
GL code field shows undefined.

### What is the root cause of that problem?
The value of `categoriesGLCode?.[containsHeader ? index + 1 : index]` here can be undefined and then when we convert the JSON to string, the `GL code` that we pass to the API is `undefined` string then BE returns the wrong GL code.

https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/workspace/categories/ImportedCategoriesPage.tsx#L95
### What changes do you think we should make in order to solve the problem?
We should fall back to empty string here

```
'GL Code': categoriesGLCodeColumn !== -1 ? categoriesGLCode?.[containsHeader ? index + 1 : index] ?? '' : '',
```
https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/workspace/categories/ImportedCategoriesPage.tsx#L95

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment]
cc @filip-solecki @rushatgabhane @rlinoz coming from the import spreadsheet PR

**Comment by mountiny** [comment]
This indeed feels like a blocker for the feature, not demoting. Added @rushatgabhane as he reviewed the original PR https://github.com/Expensify/App/pull/47827

**Comment by filip-solecki** [comment]
@nkdengineer's proposal looks good

**Comment by mountiny** [comment]
@nkdengineer are you able to raise the PR soon? thanks!

**Comment by nkdengineer** [comment]
@mountiny sure, will raise the PR soon.

**Comment by nkdengineer** [comment]
@mountiny The PR is [here](https://github.com/Expensify/App/pull/48539).

**Comment by mountiny** [comment]
this is super minor fix of a deploy blocker so reducing the bounty to reflect the complexity.

Payment summary:
- $125 to @nkdengineer 
- No payment to Rushat as he will be paid on the project basis

**Comment by rlinoz** [comment]
This is in prod already https://github.com/Expensify/App/pull/48539#issuecomment-2332467420

Just waiting payment date, let me update the title.

**Comment by rlinoz** [comment]
Not overdue Melvin 😄

**Comment by muttmuure** [comment]
Invite here: https://www.upwork.com/ab/applicants/1831645173273110226/1836111748014972928

**Comment by nkdengineer** [comment]
@muttmuure I've accepted the invitation

**Comment by muttmuure** [comment]
Offer sent

**Comment by nkdengineer** [comment]
@muttmuure Accepted thx
