### ISSUE TITLE
[HOLD for payment 2024-09-12][$250] Can't edit messages by pressing UP ARROW

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#48549]
Previous issue that should've fixed this https://github.com/Expensify/App/issues/46391

# Steps

1. Open a chat
2. Send a message
3. Press UP ARROW
4. Edit of message is not started when it should

This is happening on web in staging but not in production
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831333353313013695</li>
        <li>Upwork Job ID: 1831333353313013695</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103816825</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by Julesssss** [comment]
@iwiznia should this single platform shortcut really block the deploy?

**Comment by iwiznia** [comment]
🤷 maybe not, feel free to remove the blocker if you disagree

**Comment by stitesExpensify** [comment]
cc @puneetlath @fedirjh @bernhardoj

**Comment by Julesssss** [comment]
>  maybe not, feel free to remove the blocker if you disagree

I'll leave it up to Rory, maybe it's resolved before the decision has to be made

**Comment by iwiznia** [comment]
BTW this is in our regression testing and in fact applause had reported it a few minutes before me here https://github.com/Expensify/App/issues/48548

**Comment by puneetlath** [comment]
This seems worthy of a deploy blocker to me. It's on our primary platform.

**Comment by johncschuster** [comment]
Issuing payment tomorrow assuming no regressions 👍

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor: @fedirjh owed $250 via NewDot
Contributor+: @ishpaul777 paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/103816825)

**Comment by johncschuster** [comment]
Confirmed the linked issue is not related and the payment should not be penalized.

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
