### ISSUE TITLE
[Awaiting Payment] [$250] Thread – Your space opens when leave thread in a new non-validated account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4918786
**Email or phone of affected tester (no customers):** ponikarchuks+13924@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as a new Gmail account
3. Create a chat with user B
4. Send a message in the chat
5. Reply in thread and send some comments
6. Click on the chat header and leave the thread

## Expected Result:
Chat with user B opens

## Actual Result:
Your space chat opens

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e3329e82-a545-440c-a777-49dad2cf521e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831344164019083053</li>
        <li>Upwork Job ID: 1831344164019083053</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103902871</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by johnmlee101** [comment]
Going to demote this since I don't think its a blocker necessarily, but I think we should have someone external investigate this

**Comment by trjExpensify** [comment]
This issue is going a little stale in review, but it sounds like we might have fixed this issue elsewhere now?

**Comment by trjExpensify** [comment]
Paying this out. Confirming those as follows:

- $250 to @daledah for the work
- $250 to @ishpaul777 for the C+ review

Is that right, Ishpaul?

**Comment by trjExpensify** [comment]
Somehow I missed this, apols. @ishpaul777, paid! @daledah you didn't apply, sent you an offer.

**Comment by trjExpensify** [comment]
Paid, closing!
