### ISSUE TITLE
Import categories - Nothing happens after uploading empty csv file, console error shows up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48554]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories
3. Click 3-dot menu
4. Click Import spreadsheet
5. Upload an empty csv file

## Expected Result:
Error will show up saying that the file is invalid or empty

## Actual Result:
Nothing happens after uploading empty csv file. Console error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3ae8c147-9884-4330-aa20-6803622c36ff

[Bug6592535_1725428829829!empty.csv](https://github.com/user-attachments/files/16870924/Bug6592535_1725428829829.empty.csv)

[logs (2).txt](https://github.com/user-attachments/files/16870935/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@filip-solecki another one related to incorrect format

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this

**Comment by filip-solecki** [comment]
Is this message ok?
`'The file you uploaded is either empty or contains invalid data. Please ensure that the file is correctly formatted and contains the necessary information before uploading it again.',`

**Comment by isagoico** [comment]
Retested after CP https://github.com/Expensify/App/pull/48556 and it was a pass 🎉 
![image](https://github.com/user-attachments/assets/65a3b947-e53e-4fdd-9f94-c60e3eeed6d4)

**Comment by roryabraham** [comment]
no extra payments due here
