### ISSUE TITLE
[$125] Import categories - Unable to dismiss "Import successful" modal by clicking outside the modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48563]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates.
3. Select all distance rates via checkbox.
4. Click on the dropdown > Delete rates.
5. Click outside the modal.
6. Note that the modal can be dismissed by clicking outside the modal.
7. Go to Categories > 3-dot menu > Import spreadsheet.
8. Upload a valid file.
9. Map Name and Enabled.
10. Click Import.
11. Click outside the "Import successful" modal to dismiss it.

## Expected Result:
"Import successful" modal can be dismissed it by clicking outside the modal.

## Actual Result:
"Import successful" modal cannot be dismissed it by clicking outside the modal.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/536ecbdb-203c-4997-8a03-817c099dfb45
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831346879000450861</li>
        <li>Upwork Job ID: 1831346879000450861</li>
        <li>Last Price Increase: 2024-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103814571</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by mountiny** [comment]
@filip-solecki @rushatgabhane this does not have to be a blocker imho as there is a clear way to get around it

**Comment by mountiny** [comment]
I can help take over as I have reviewed the offending PR

**Comment by mountiny** [comment]
Ideally, @filip-solecki fixes this, but I think we can move ahead with @Krishna2323 proposal, but given this is very simple change I will drop the price to $125

**Comment by mountiny** [comment]
Payment summary:
- $125 to @Krishna2323 for the fix
- no payment to Rushat here as he is going to be paid on the project basis

**Comment by stephanieelliott** [comment]
Hey @rushatgabhane this is blocked on you, can you review the PR when you get a chance?

**Comment by Guccio163** [comment]
PR is merged, I think we can close this one 👌

**Comment by trjExpensify** [comment]
Category import via spreadsheet is being built in #wave-control, moving this over to that project.

**Comment by stephanieelliott** [comment]
PR is merged but not on staging yet -- will leave this open to pay out when it's deployed to prod +7

**Comment by stephanieelliott** [comment]
Hm, this PR was deployed to prod with https://github.com/Expensify/App/issues/48954 on 9/11, but it looks like the automation didn't work. We're past the payment date, setting up payment now.

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: $125 to @Krishna2323 via Upwork -- PAID 
 - Contributor+: N/A, s @rushatgabhane is being paid on a project basis
 
 Upwork job is here: https://www.upwork.com/jobs/~021831346879000450861
