### ISSUE TITLE
[$250] Payment for #45150

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#48581]
Payment for C+ review of this PR https://github.com/Expensify/App/pull/45150

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831374134900660013</li>
        <li>Upwork Job ID: 1831374134900660013</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
Okay so manual request is all we're waiting on, yes? We don't need to go into upwork it seems

**Comment by greg-schroeder** [comment]
You can link to that comment and should be g2g!

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
