### ISSUE TITLE
iOS - Import spreadsheet - Offline modal does not show up on iOS app only

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48580]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Categories.
3. Go offline.
4. Tap 3-dot button.
5. Tap Import spreadsheet.

## Expected Result:
Offline modal will show up.

## Actual Result:
Offline modal does not show up on iOS app only.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2377dae3-1400-44a8-b225-aabe087b5d30

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
Coming from https://github.com/Expensify/App/pull/47827 cc @filip-solecki @rushatgabhane 
If you could please make a follow up

**Comment by filip-solecki** [comment]
Hi! I am Filip from SWM and I'd like to work on this as it comes from my PR
