### ISSUE TITLE
[$250] Workspace - Able to delete expense from archived workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48588]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Create a WS
3. Submit one or few expenses
4. Delete the workspace
5. Open archived WS chat
6. Tap header -- delete expense

## Expected Result:
User must not be able to delete expense from archived workspace.

## Actual Result:
Able to delete expense from archived workspace.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a5ba6eb5-e126-4ac8-b157-83b1ea8f0549

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833087706130184523</li>
        <li>Upwork Job ID: 1833087706130184523</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103922957</li>
<li>FitseTLT | Contributor | 103922958</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @FitseTLT</details>

**Comment by IuliiaHerets** [comment]
@zanyrenney z FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Able to delete expense from archived workspace

### What is the root cause of that problem?
We don't check if it is archived in can add or delete transaction here
https://github.com/Expensify/App/blob/6760f96d9f7fc425e6972be27e5fb0a277805bd6/src/libs/ReportUtils.ts#L1653-L1657
### What changes do you think we should make in order to solve the problem?

We should return false if the report is archived one
### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment]
Ooh sorry I totally missed this one!

**Comment by zanyrenney** [comment]
Reviewing now.

**Comment by zanyrenney** [comment]
Adding `External`

**Comment by zanyrenney** [comment]
hey @situchan please review the proposals above and let me know which one is best so we can move ahead here. Thank you!

**Comment by situchan** [comment]
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/48588#issuecomment-2329769100) looks good to me.
🎀👀🎀 C+ reviewed

**Comment by zanyrenney** [comment]
cc @aldo-expensify

**Comment by FitseTLT** [comment]
PR ready

**Comment by FitseTLT** [comment]
@zanyrenney payment overdue

**Comment by FitseTLT** [comment]
@zanyrenney Can u pls issue the payment ?? Thx

**Comment by zanyrenney** [comment]
**payment summary**

$250 to @FitseTLT paid via upwork 
$250 to @situchan paid via upwork.
