### ISSUE TITLE
[Hold for payment 2024-09-12] [$250] Categories - GL code data disappears after importing same file that does not have GL code

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48587]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Control workspace settings > Categories.
3. Click 3-dot menu.
4. Click Import spreadsheet.
5. Upload the attached CSV file.
6. Map Name and Enabled.
7. Click Import.
8. Click on any category.
9. Manually enter GL code and Payroll code.
10. Click 3-dot menu > Import spreadsheet.
11. Upload the same file in Step 5, map the fields and import.
12. Click on the same category that has GL code and Payroll code entered previously in Step 9.

## Expected Result:
GL code and Payroll code will remain unchanged after importing the same file that does not have GL code and Payroll code (Old Dot behavior).

## Actual Result:
GL code data disappears while Payroll code remains after importing the same file that does not have GL code and Payroll code.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9fa74a64-484b-4910-92a7-73e196aa86d1

[Bug6593258_1725473988736!real_table_cat.csv](https://github.com/user-attachments/files/16875393/Bug6593258_1725473988736.real_table_cat.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831644707096192237</li>
        <li>Upwork Job ID: 1831644707096192237</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by tgolen** [comment]
Sorry, I didn't mean to unassign anyone.

@filip-solecki I believe this is related to https://github.com/Expensify/App/pull/47827 so can you please look into this?

**Comment by Shahidullah-Muffakir** [comment]
@ishpaul777 I have a question: When processing the imported categories, we aren't adding the check you mentioned for the **Payroll Code.** However, the Payroll Code still seems correct after re-uploading the same file.  are we handling that somewhere else?  Thank you.

**Comment by Shahidullah-Muffakir** [comment]
Right, yes, that makes sense. Thanks.

**Comment by mountiny** [comment]
Payment summary:
- $250 to @ishpaul777 for a fix
- no payment to Rushat as he is going to be paid on the project basis

**Comment by sonialiap** [comment]
Deployed to staging, waiting for production deploy and then 7 days

**Comment by sonialiap** [comment]
Payment summary:
- @ishpaul777 $250 - offer sent in upwork
- no payment to Rushat as he is going to be paid on the project basis
