### ISSUE TITLE
[HOLD for payment 2024-11-01] [Improvement] Ensure New Expensify Supportal provides View access to all required information

### ISSUE THREAD

**Issue by VictoriaExpensify** [Expensify/App#48616]
**Problem:**

Currently, New Expensify Supportal is inconsistant with the information the support team member is able to view. All the information in the following locations looks good:
- Search
- Account Settings

The following information appears inconsistantly, or not at all:
- Inbox
- Workspace Set Up

**Why is this important:**
Without being able to view this information, the support team is essentially "flying blind" when a customer reaches out for support. This results in a poort customer experience as we cannot see what features the customer has enabled and we need to ask them to provide information that we should have access to.

**Solution**
Find an engineer to help us give View access to all parts of the customers account via New Supportal, with the exception of:
- Chat threads
- Virtual Card details

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by VictoriaExpensify** [comment]
### Examples:
**INBOX**
** victoria+5@expensifail.com - from within the account:**
![image](https://github.com/user-attachments/assets/434a1e41-e8a8-47b3-b493-09a544bf690c)
![image](https://github.com/user-attachments/assets/f1fbc193-73d4-433b-ae54-180ab7f6c1ea)

**From Supportal:**
![image](https://github.com/user-attachments/assets/be8091af-7587-4239-ba9b-a4efc3d93913)
![image](https://github.com/user-attachments/assets/54da7863-08a0-4c36-8ddb-ed61581ce764)

**WORKSPACE SETUP**
**victoria@expensifail.com - from within the account:**
See [this spreadsheet](https://docs.google.com/spreadsheets/d/1yllhwaHFKCMy6YWGpWXPIcm57TFweTi7C7MTenWgJwc/edit?gid=0#gid=0) and the screenshots linked [here](https://docs.google.com/document/d/1XyrXgN7vZ15BI4EIDhClEF8vN0m_2gPbP2j0rOly88U/edit) 

For additional context, all information contained within the customers account should be viewable via New Supportal. The only exceptions to that are:
- Chat threads 
- Virtual Card details

**Comment by VictoriaExpensify** [comment]
Posted a P/S to #Whats_Next - https://expensify.slack.com/archives/CC7NECV4L/p1725349471929479?thread_ts=1724995999.639489&cid=CC7NECV4L

**Comment by VictoriaExpensify** [comment]
As [discussed here](https://expensify.slack.com/archives/C041MSTR8J1/p1724996637061889?thread_ts=1724950226.462239&cid=C041MSTR8J1), applying the `Internal` and `Hot Picks` labels

**Comment by VictoriaExpensify** [comment]
This needs to be managed internally as external teams are not able to make updates to Supportal.

Anu - removing your assignment, I'm happy to be the BZ assignee for this one.

**Comment by VictoriaExpensify** [comment]
Not overdue - will post in Engineering chat in the morning to see if we can find an Engineer

**Comment by muttmuure** [comment]
@VictoriaExpensify Tyler is working on higher priorities and can't get to this for a few weeks. Do you want to go ahead and post to #engineering-chat or WN and we'll see if we can get someone else/

**Comment by VictoriaExpensify** [comment]
Thanks @muttmuure - I've already posted this to Engineering Chat

**Comment by VictoriaExpensify** [comment]
**Update Sept 11:**
NewDotQuality auto-assigner assigned this to Tyler, but he is unable to work on this for a few weeks due to higher priorities. Posted to [Engineering Chat](https://expensify.slack.com/archives/C03TQ48KC/p1725928183397819), but no takers, so I'll keep working on finding an engineer.

I will start trying to recruit an engineer. If anyone in Conci knows an engineer who might be interested, please reach out to them (or me!)

**Comment by maddylewis** [comment]
@muttmuure / @puneetlath -- I want to make sure we (the newdot support team) are handling these issues correctly. 

[here puneet confirmed](https://expensify.slack.com/archives/C041MSTR8J1/p1726066034479689?thread_ts=1726003801.777889&cid=C041MSTR8J1) internal tooling issues should be added to NewDot-Quality project board [Medium] + the `Hot Picks` label after posting in WN / trying to recruit in eng-chat. 

however, it sounds like going through that process didn't end up assigning someone who had the bandwidth. what is the best path forward in that scenario? 

would it make sense for the engineer assigned to adjust the K2 label from `daily` to `weekly` but keep it assigned? or, could the eng assigned communicate they can't working on this atm and reapply the auto-assigner to get someone else assigned? 

These internal tooling improvements are crucial to effectively supporting customers using New Dot, so I want to make sure we're all on the same page. so lmk your thoughts! :)

**Comment by muttmuure** [comment]
I was thinking more along the lines that if we can get someone else sooner, then we should. Typically an engineer will look at an issue and pick it up if it is unassigned. If it's assigned to someone already, most people assume it's going to be worked on soon. 

We can reapply the label and ask the next person to work on it. That's OK too.

**Comment by VictoriaExpensify** [comment]
Thanks @muttmuure ! For context, Maddy and I were talking this morning on how we can find an engineer and get traction on some of these support issues.

I know all engineers are pretty stretched at the moment, but I do think it would be good if we could reapply the auto-assigner and see if we can find anyone that way.  If that person doesn't have the capacity, we'll try and recruit.

Not being able to Supportal has a pretty big impact on the way we support customers, so while it might not be the biggest issue, it does seem like something we want to get fixed sooner rather than later 🙏

**Comment by thienlnam** [comment]
@danieldoglas IIRC you set this up, I'm guessing this is just a limitation of the auth token to some commands - is there anything that would be good to know when adding more allowed commands for supportal?

**Comment by thienlnam** [comment]
@VictoriaExpensify Are there any specific pages that we'd like to be able to see? All information will involve a lot of changes, but if there's a few specific things I can focus on that will be easier to get done. It seems like the main ones are:

- Inbox
- Workspace Settings
- Accounting Tab

Anything else?

**Comment by VictoriaExpensify** [comment]
This has been discussed in more detail here - https://expensify.slack.com/archives/C041MSTR8J1/p1727077123944429?thread_ts=1726760509.281259&cid=C041MSTR8J1

**Comment by VictoriaExpensify** [comment]
Just to pull out of that thread what was discussed:

- We want to New Supportal to provide the same level of visibility into customer accounts as Classic Supportal does
- Since this sounds like quite a big job, we will prioritise:

- [ ] Inbox
- [ ] Workspace settings
- [ ] Search page
- [ ] Subscription in account settings

**Comment by thienlnam** [comment]
Have a couple PRs completed for this that should help - the listed items should be visible now. I still haven't changed the query that updates the getChats query since it's unruly, but if you click on any report you should be able to view it unless it's a DM that isn't the DM with Concierge

**Comment by thienlnam** [comment]
Still need to investigate why the accounting tab thinks it is loading - I see that it's making a call to the endpoint OpenPolicyAccountingPage which should be whitelisted, but it seems to fail immediately

**Comment by VictoriaExpensify** [comment]
Thanks for continuing to investigate this @thienlnam. Accounting integration issues are one of the items that we troubleshoot the most, so having this info available in Supportal is super important. Let me know if there is anything I can do to assist :)

**Comment by VictoriaExpensify** [comment]
Hey @thienlnam - any update on the issue with the accounting tab?

**Comment by thienlnam** [comment]
Okay after some debugging I figured out the fix:

Was odd because it would say that the request to OpenPolicyAccountingPage completed in 0ms with no response. I originally thought it was because it was put into the sequential queue and because we failed to re-authenticate we never actually end up sending the request to read the accounting data. However the other requests worked, so I was wondering if there was something different with the commands and indeed there is another place where we need to whitelist commands in App 

https://github.com/Expensify/App/blob/e74eb8e705bce3e8791e3eb043fe5cbb1cbaecea/src/libs/Network/NetworkStore.ts#L100C1-L119C2

**Comment by VictoriaExpensify** [comment]
Oh, you're not a C+ @thienlnam ! 😆 

This is all fixed and looking good:

![2024-11-01_14-18-00](https://github.com/user-attachments/assets/c9b7f232-c6d4-45de-8cde-28ac9d4a98ee)
![2024-11-01_14-18-08](https://github.com/user-attachments/assets/d9bdc7f7-2b76-475b-8d29-c67ddc1c1d4a)
![2024-11-01_14-18-16](https://github.com/user-attachments/assets/dc0ba528-f6cd-46b6-9503-493debac9f54)
![2024-11-01_14-18-23](https://github.com/user-attachments/assets/63db2104-9886-4c0b-8913-6baf6079eb1f)


Going ahead and closing this out (without payment, sorry Jack! haha)
