### ISSUE TITLE
[$250] [Advanced Approval Workflows] Remove advanced approval beta, clean the logic, add explanations in comments

### ISSUE THREAD

**Issue by blazejkustra** [Expensify/App#48624]
We are slowly finishing the project, as the last polish PRs are getting merged we can finally remove the beta flag for advanced approvals. Apart from just removing the beta we want to clean the logic a little bit if possible and add detailed comments as per [this](https://github.com/Expensify/App/pull/48411#discussion_r1742116695) comment.

cc @tgolen @DylanDylann 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835694296887312745</li>
        <li>Upwork Job ID: 1835694296887312745</li>
        <li>Last Price Increase: 2024-09-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by DylanDylann** [comment]
@blazejkustra Please ping me when the PR is ready

**Comment by blazejkustra** [comment]
@DylanDylann PR is up, but @suneox was assigned, not sure how to proceed 😄

**Comment by DylanDylann** [comment]
@suneox Please allow me to take over this issue, I followed with this feature from scratch

cc @tgolen

**Comment by suneox** [comment]
> @suneox Please allow me to take over this issue, I followed with this feature from scratch
> 
> 
> 
> cc @tgolen 

Ah sure, I got it

**Comment by roryabraham** [comment]
@tgolen reassigning to you as you reviewed the PR. Looks like all that remains here is C+ payment

**Comment by alexpensify** [comment]
Waiting for this one to go to prod and the 7 day hold before going through the payment process.

**Comment by alexpensify** [comment]
Not in Prod yet

**Comment by roryabraham** [comment]
Sorry for the confusion due to lack of deploy comments @alexpensify, we experienced some bugs with deploy refactors. [The PR](https://github.com/Expensify/App/pull/487060) was deployed to prod on 2024-09-10

**Comment by alexpensify** [comment]
I based my previous comment on the state of this PR: https://github.com/Expensify/App/pull/48706. Is that the wrong one?

**Comment by alexpensify** [comment]
Wow, this is the first time I don't see a production notice in a PR. I've seen automation failures for payment updates, but this one is wild. Thanks for flagging, I'll work on the payment process later today since I've already gone through my payment tasks for the day.

**Comment by alexpensify** [comment]
Payouts due: 2024-09-10

- [ ] Contributor: N/A @blazejkustra payment will be handled via the vendor 
- [ ] Contributor+: $250 @DylanDylann 

Upwork job is [here](https://www.upwork.com/jobs/~021835694296887312745).

--- 

@DylanDylann I sent an offer via Upwork. Please accept and I can complete the payment process. Thanks!

**Comment by DylanDylann** [comment]
@alexpensify Thanks I accepted

**Comment by alexpensify** [comment]
Closing - I completed the payment process in Upwork.
