### ISSUE TITLE
Track - Page is not scrolled to the bottom when navigate back from transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48636]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4919148&group_by=cases:section_id&group_id=309130&group_order=asc
**Issue reported by:**  Applause - Internal Team

## Action Performed:
Precondition:
 User have more than 3 track expenses in Self-DM
 User should select Do nothing from the actionable whisper
1. Go to Self-DM chat> Track> Complete the flow
2. Actionable whisper will appear
3. Click on expense from step 1 to open transaction thread
4. Click on header (you) to go back to Self-DM chat
5. Take a look under expense

## Expected Result:
Page should be scrolled to the bottom and actionable whisper should be visible

## Actual Result:
Page is not scrolled to the bottom and actionable whisper is not visible until manually scroll the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b84cb8e9-b1ba-4e22-9b98-5f56b80e26bb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
Hm, I don't think this is really a bug. If you ignore the actionable whisper and click into any of the expenses above it, and then click back out of them, we are using our default behavior of landing with the expense you previously clicked into in focus. 

It doesn't really make sense to me that we'd add some custom logic to this and ignore the default behavior, just because the actionable whisper is there, since the customer chose not to action it. They can still scroll to see it.

**Comment by joekaufmanexpensify** [comment]
Closing as I don't think this is a bug, but LMK if anyone disagrees.
