### ISSUE TITLE
Workspace-Incorrect Conversion When Changing Workspace and Submitted Expense Currency

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48634]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+tw435367011@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to Account Settings > Create Workspace.
2. Navigate to Workspace Chat > Click the plus sign > Submit Expense > Add an amount.
3. Add a merchant and confirm the expense.
4. Return to Account Settings > Workspace > Change the workspace currency.
5. Go to the Expense Detail page > Change the expense currency to match the new workspace currency. Notice that the currency conversion in the preview is incorrect and not converted properly.

## Expected Result:
When changing the currency in the Expense Detail page, the currency should be correctly converted and accurately displayed in the preview.

## Actual Result:
The currency conversion in the Expense Detail page does not happen correctly, resulting in an incorrect display in the preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4ad42967-e4e0-4ccd-868f-855b7a311816

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by stephanieelliott** [comment]
> When changing the currency in the Expense Detail page, the currency should be correctly converted and accurately displayed in the preview.

I don't think this is a bug -- I would not expect changing the currency in the expense detail view would convert it. I would expect that the amount would always be correct if manually entered, , irrespective of currency.
