### ISSUE TITLE
Export to Xero - Sending message with enter key selects "Export to Xero"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48633]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+ds@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Create a workspace and connect to Xero

1. Go to workspace chat
2. Submit expense
3. Pay expense
4. Notice "Export to Xero" is now shown
5. Type a message in the composer and send it with "Enter" key
Notice that Clicking enter activates the Export to Xero

## Expected Result:
Clicking enter only sends the message

## Actual Result:
Clicking enter sends the message and also activates the "Export to Xero"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/55f2e9a1-7e59-4b4e-b3af-f19da325d60d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
I can't replicate this one on v9.0.30-15


https://github.com/user-attachments/assets/ce7e9481-8f5f-4952-9a3c-c68e0d155a19

**Comment by adelekennedy** [comment]
still can't replicate so closing this out!
