### ISSUE TITLE
Chat - Incorrect number of new messages are shown in green marker badge count

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#4863]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Issue found when executing PR #4773

## Action Performed:
1. Lunch the app
2. Log in with account A  in device 1
3. Select user you will chat and scroll the chat to 10-30 messages to top
4. Back to LHN
5. Log in with account B in device 2
6. Send 13 messages to account A from device 2
7. Back to conversation from LHN in device 1 and check the green Marker Badge Count

## Expected Result:
I expected to see the same number of messages sent from device 2

## Actual Result:
Gives some random number shows as new message count
## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- iOS 
- Android 
- mWeb

**Version Number:**
1.0.88-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/131014149-e82d87b6-5d77-4477-abeb-36aeea466742.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by parasharrajat** [comment]
I can't close this issue but cc: @roryabraham

**Comment by isagoico** [comment]
Issue not reproducible during KI retests (FIxed)

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183084866) to staging by @roryabraham in version: 1.0.88-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|cancelled 🔪 
🖥 desktop 🖥|cancelled 🔪
🍎 iOS 🍎|cancelled 🔪 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183075988) to production by @roryabraham in version: 1.0.88-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188395063) to production by @roryabraham in version: 1.0.90-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅
