### ISSUE TITLE
[Hold for payment 2021-09-07] Request a call - Phone number is filled in First Name box

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#4864]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in phone number account
3. Search for Concierge
4. Click on Phone icon

## Expected Result:
The phone number should not be displayed in First Name box

## Actual Result:
Phone number displayed by default in First Name box

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**1.0.88-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://user-images.githubusercontent.com/44479856/131013711-4748d62b-b348-4a17-809b-805856fd956f.png)

**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://www.upwork.com/jobs/~0151a4a87a2174a396

**Comment by PrashantMangukiya** [comment]
## Proposed Solution

What I understood is, If first name is same as phone number then we have to keep first name empty within form. So I will suggest to modify constructor for **src/pages/RequestCallPage.js**  file. 

How It works: Within constructor we have to check if first name is same as phone number then set first name empty within form, otherwise keep first name as it is. 

Constructor code will looks like as under once modified as per my suggestion. I will prefer this way so we don't need to change code any other place.

```javascript
    constructor(props) {
        super(props);
        const {firstName, lastName} = this.getFirstAndLastName(props.myPersonalDetails);
        const phoneNumber = this.getPhoneNumber(props.user.loginList) ?? '';
        const firstNameDefault = (firstName === phoneNumber) ? '' : firstName;

        this.state = {
            firstName: firstNameDefault,
            lastName,
            phoneNumber,
            isLoading: false,
        };

        this.onSubmit = this.onSubmit.bind(this);
        this.getPhoneNumber = this.getPhoneNumber.bind(this);
        this.getFirstAndLastName = this.getFirstAndLastName.bind(this);
    }
```

If my solution considered then kindly accept my Upwork proposal.  Once proposal accepted, I will do final testing and submit pull request within 2 days.

My Upwork profile: [https://www.upwork.com/freelancers/~01c718889ed7821f82](https://www.upwork.com/freelancers/~01c718889ed7821f82)

Best Regards, 
Prashant Mangukiya

**Comment by Beamanator** [comment]
@thesahindia I like your idea, it's short and sweet and works quite well 👍 I just assigned this task to you, please submit a PR when you have a chance :)

**Comment by Santhosh-Sellavel** [comment]
@Beamanator Just for clarification, I hope answer helps me in future my proposals.

As I said in my proposal  https://github.com/Expensify/App/issues/4864#issuecomment-906991980

When we have the values we need in props itself why we need to do the spliting from `displayName`.

**Comment by Beamanator** [comment]
@Santhosh-Sellavel If a bug surfaces in the future and we end up needing to use those props, your proposal will be amazing 👍 However, my thought on this was that @thesahindia 's was so nice and simple (and worked when I tested) that it makes the most sense to do a one-line fix.

**Comment by isagoico** [comment]
Issue reproducible during KI retests

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183084866) to staging by @Beamanator in version: 1.0.88-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|cancelled 🔪 
🖥 desktop 🖥|cancelled 🔪
🍎 iOS 🍎|cancelled 🔪 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188395063) to production by @roryabraham in version: 1.0.90-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by isagoico** [comment]
Issue not reproducible during KI retests (Fixed 🎉)

**Comment by arielgreen** [comment]
Paid! Thanks for your work on this, @thesahindia.
