### ISSUE TITLE
[Awaiting Payment Sept 24th] [$125] Pay elsewhere missing as a payment method when configured for direct reimbursement on a workspace

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#48657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.29-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://github.com/Expensify/App/issues/36301#issuecomment-2329473649

## Action Performed:
1. Create a workspace
2. Go to More features > Enable Workflows
3. Go to `Workflows` > Enable approvals and payments
4. Click `Connect bank account` and add a VBBA
5. Submit an expense report on the workspace
6. Go to the expense report
7. Observe the Pay button

## Expected Result:
The pay button should have an option to change it to `Pay elsewhere` to mark the report as manually reimbursed.
 
## Actual Result:
The pay button does not have that option, only `Pay $x using Expensify`. 

## Workaround:
No

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e6912394-63dc-4218-8f7c-fa5c49c265ab">

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/75ff8337-8a3a-4ef0-91a8-57b19c36c999">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831725635476300859</li>
        <li>Upwork Job ID: 1831725635476300859</li>
        <li>Last Price Increase: 2024-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 103842728</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by mountiny** [comment]
We chose @shubham1206agra to work on it based on internal slack discussion and clarification of the logic. Apologies for not making this cleaner before and losing some time then @shubham1206agra What is your ETA for a PR

**Comment by trjExpensify** [comment]
@shubham1206agra didn't you have a PR for this?

**Comment by trjExpensify** [comment]
Payment will be due tomorrow. 👍

**Comment by trjExpensify** [comment]
Payment summary as follows:

- $125 to @shubham1206agra for the fix
- $125 to @aimane-chnaif for the review

Aimane, go ahead and request. @shubham1206agra please accept [the offer](https://www.upwork.com/offer/103842728), it's waiting on yah.

**Comment by trjExpensify** [comment]
and Melvin, please feel to jump in a lake.

**Comment by trjExpensify** [comment]
@shubham1206agra can you accept the offer so we can close this?

**Comment by trjExpensify** [comment]
>I am still using upwork

Oh really? Why so? You're in the list for NewDot. 🤔

**Comment by trjExpensify** [comment]
Got it. @mallenexpensify will work on getting that update. In the meantime, an offer has been sent.

**Comment by trjExpensify** [comment]
Paid, closing!

**Comment by trjExpensify** [comment]
I've paid a bonus to get around that. Let me know if that doesn't work.
