### ISSUE TITLE
[HOLD for payment 2024-10-10] Timing measurements are not exact

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#48653]
While looking through our custom performance trances in firebase I noticed that some values were off showing values in the range of 27min to even hours:

![Screenshot 2024-09-05 at 17 16 33](https://github.com/user-attachments/assets/2fd0a467-465f-4163-97d4-d17a1cf48b4b)

There must be some kind of problem with measuring the performance in our timing library.

**Comment by hannojg** [comment]
Addressed in:

- https://github.com/Expensify/App/pull/48654

**Comment by marcaaron** [comment]
Nice find @hannojg 🙇

**Comment by luacmartins** [comment]
FYI https://github.com/Expensify/App/pull/48654#issuecomment-2339065097

**Comment by hannojg** [comment]
Thanks for the quick fix, will come up with a proper fix soon (just came back from OOO)!

**Comment by hannojg** [comment]
hey, lets keep it open once i implemented a final fix. Haven't had the time to do that yet due to higher priority tickets

**Comment by luacmartins** [comment]
@JmillsExpensify could you help with paying @eh2077 for the PR review? Just noting that there was a blocker/regression associated with it

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @eh2077 for PR testing and review.

**Comment by eh2077** [comment]
> @JmillsExpensify could you help with paying @eh2077 for the PR review? Just noting that there was a blocker/regression associated with it

@JmillsExpensify Thanks for checking the payment. I think payment of $125 will be fair according to this comment.

**Comment by JmillsExpensify** [comment]
Sounds good! Can you send a payment request via NewDot and I'll approve? Thanks.

**Comment by eh2077** [comment]
Requested in NewDot, thanks!

**Comment by trjExpensify** [comment]
Confirming the payment summary [here](https://github.com/Expensify/App/issues/48653#issuecomment-2417529876) is correct.

**Comment by JmillsExpensify** [comment]
$125 approved for @eh2077
