### ISSUE TITLE
[Hold for payment 2024-10-07][$250] Spacing in error message in Fields for Expensify Page are not consistent

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48659]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.29-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47957
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Access staging.new.expensify.com and sign in with a valid account
2. Open Settings > Switch to Expensify Classic
3. Select any reason and proceed to the next screen
4. Verify the next button is aligned at the bottom of the page
5. Submit the form with an empty response. Verify error is shown
6. Keep adding new line to the form input until it reaches the maximum height
7. Verify the input underline, form error, and the next button isn't overlap

## Expected Result:
User expects consistent spacing between the "red dot - error messages" on all platforms at the bottom of the page

## Actual Result:
The spacing is inconsistent between platforms, for example the spacing shows one way on iOS/Desktop and with another spacing on Web/mweb.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6594231_1725553323941!Different_distances_between_error_messages](https://github.com/user-attachments/assets/6899240d-9ce6-4781-b63e-7f003c61bcbe)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832083749373830381</li>
        <li>Upwork Job ID: 1832083749373830381</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 104008602</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Spacing in error message in Fields for Expensify Page are not consistent
### What is the root cause of that problem?
This is happening due to margin overlap.
<img width="344" alt="Screenshot 2024-09-05 at 10 30 29 PM" src="https://github.com/user-attachments/assets/5bfbb5cb-c5ef-45a2-8811-230c743ffc24">
<img width="344" alt="Screenshot 2024-09-05 at 10 30 05 PM" src="https://github.com/user-attachments/assets/f329c1e7-0f7c-4310-9d5d-438a19d2fead">


Due to the different dimensions of the platforms, the margin overlap is different which is causing inconsistency.
### What changes do you think we should make in order to solve the problem?

We have to remove `justfyContentEnd` form https://github.com/Expensify/App/blob/cc1c7d066e178c0c4a74af044f2392c71eafaca3/src/components/FormAlertWithSubmitButton.tsx#L100

### What alternative solutions did you explore? (Optional)

**Comment by francoisl** [comment]
Demoting for now, this is not breaking anything.

---

@MuaazArshad thanks for the proposal. Were you able to identify which PR from the checklist caused the regression?

**Comment by MuaazArshad** [comment]
No, I was not able to identify which PR caused it.

**Comment by ahmedGaber93** [comment]
It seems related to https://github.com/Expensify/App/pull/47957

**Comment by trjExpensify** [comment]
The linked PR is in the regression period, I think @bernhardoj & @rayane-djouah should look at this as a regression.

**Comment by alitoshmatov** [comment]
@MuaazArshad This does seem an issue, but is there any use case scenario which causes this bug in expensify app?

**Comment by MuaazArshad** [comment]
@alitoshmatov The Expensify app is using a lot of multiple-line errors. This issue can affect any of those.
Furthermore, if the auto grow max height is set in `moneyRequestSetpDescription` and `roomDescriptionPage` we should also adjust it for this `exitSurveyResponcePage`

**Comment by francoisl** [comment]
Hm yeah, looks like something we should address - even if we don't have a multi-line error message for this flow right now doesn't mean we won't in the future.

**Comment by MuaazArshad** [comment]
@francoisl bump

**Comment by francoisl** [comment]
Yeah let's proceed with a  fix.
@alitoshmatov can you review the existing proposal please? The proposed solution makes sense, though I can't tell if the proposed alternative is worth it.

**Comment by MuaazArshad** [comment]
@alitoshmatov bump!

**Comment by lschurr** [comment]
Bumped in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1726526127801759

**Comment by alitoshmatov** [comment]
Okay we can go with @MuaazArshad 's [proposal](https://github.com/Expensify/App/issues/48659#issuecomment-2332343580) which changes max height of response input making it smaller and not reach bottom, like this: 


<img width="1512" alt="Screenshot 2024-09-17 at 10 10 49 PM" src="https://github.com/user-attachments/assets/071dbc87-91ce-4451-bd49-13f741cf1adb">

C+ reviewed 🎀 👀 🎀

**Comment by MuaazArshad** [comment]
I'll raise PR by EOD.

**Comment by MuaazArshad** [comment]
@lschurr I haven't got the Upwork offer for this issue.

**Comment by MuaazArshad** [comment]
@lschurr bump for payment!

**Comment by alitoshmatov** [comment]
PR went into [production](https://github.com/Expensify/App/pull/49398#issuecomment-2384302392) on 1st of October

**Comment by lschurr** [comment]
@MuaazArshad - since the PR went to production on Oct 1, today is the pay day. Sent your offer [via Upwork](https://www.upwork.com/nx/wm/offer/104302674).

**Comment by MuaazArshad** [comment]
Thank you. Accepted the offer.

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @MuaazArshad (paid in Upwork)
- Reviewer: $250 @alitoshmatov (paid in Upwork)
