### ISSUE TITLE
Card Screen - p character on 'Help' button is cropped

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#4866]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Issue found while executing https://github.com/Expensify/App/pull/4637

## Action Performed:
1. Open app and login
2. Go to FAB > New Workspace
3. Tap on Company Cards

## Expected Result:
User is able to see guide call button (Help button) with no issues

## Actual Result:
p character is cropped

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.0.88-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:**

<img src="https://user-images.githubusercontent.com/44479856/131052807-04f2f008-005c-4547-b2fc-214104cf2f6c.png" width="40%">

**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
Small buttons should be using smaller text by default right? Basically if you pass in the "small" prop to the button, I would assume it would use the small font size (11px) by default. 

In terms of this looking a bit off... maybe it's just the icon that feels a bit off? So perhaps for small buttons, if the icons were a bit smaller (like 16x16 instead of 20x20?) they might look better?

**Comment by isagoico** [comment]
Issue reproducible during KI retests

**Comment by alex-mechler** [comment]
> Small buttons should be using smaller text by default right? Basically if you pass in the "small" prop to the button, I would assume it would use the small font size (11px) by default.

Ahh, this is because a normal button did not work in this case, I had to create my own "button" with similar styles to get the icon in there. 

> In terms of this looking a bit off... maybe it's just the icon that feels a bit off? So perhaps for small buttons, if the icons were a bit smaller (like 16x16 instead of 20x20?) they might look better?

I agree, I think that the icon being large is what is throwing me off, I can try with a smaller icon and will post results here

**Comment by shawnborton** [comment]
Is it possible to do this using the same button component though? I think ideally we don't want a different kind of button to maintain.

**Comment by alex-mechler** [comment]
Possibly, I can look into refactoring that. It might take a minute, so let me test with the icon sizes first, so that we can settle on look before worrying about that.

**Comment by alex-mechler** [comment]
Hmm, 16x16 is already what "small" is for an icon. 
![image](https://user-images.githubusercontent.com/22447860/131363398-73ece9a3-a57a-48e7-993f-a57f9805325b.png)

How about adding an xsmall of 12x12?
![image](https://user-images.githubusercontent.com/22447860/131363530-6c7d0d3e-ca03-480b-bfd7-fb18005f7453.png)
![image](https://user-images.githubusercontent.com/22447860/131363600-7353328b-bcf7-41f4-9090-28c750fac4fc.png)

**Comment by shawnborton** [comment]
That works for me. So that makes me wonder, where else do we have these small buttons that have icons... maybe nowhere?

**Comment by shawnborton** [comment]
What I am saying is, I wonder if 12x12 should just be the default for small buttons instead of having to add an XS class.

**Comment by alex-mechler** [comment]
> That works for me. So that makes me wonder, where else do we have these small buttons that have icons... maybe nowhere?

The button component currently has no way to show an icon as well, so I think this is the only case where we do. 

> What I am saying is, I wonder if 12x12 should just be the default for small buttons instead of having to add an XS class.

I would default the text to be textSmall and iconXSmall when the button is `small`.

**Comment by michelle-thompson** [comment]
Unpopular opinion here, but I actually feel like 12x12 is too small. I think it's hard to distinguish on web what that icon is. Plus, it looks so much smaller than the grey icons that it feels a little distracting.

**Comment by shawnborton** [comment]
Fair point Michelle, and maybe the phone icon itself is a weird one.. maybe a more common case of having a down/up caret wouldn't look so strange. 

Okay, so maybe we just keep the icon at 16x16 then and make sure the font size is 11pt (like other small buttons) and call it a day?

**Comment by alex-mechler** [comment]
Works for me, I can also do that refactor to make this not a special case button

**Comment by shawnborton** [comment]
Sounds great to me - hbu Michelle?

**Comment by michelle-thompson** [comment]
Sounds great, thanks guys!

**Comment by botify** [comment]
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188400020) to staging by @flodnv in version: 1.0.90-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1192222770) to production by @roryabraham in version: 1.0.91-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅
