### ISSUE TITLE
Red spell check line is shown frequently in composer when typing

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#48662]
When typing in the composer the red spell check line shows up very frequently. Much more frequently than in apps like Slack and Github. According to Michał Skałka the problem is likely with the Live Markdown element rendering. It happens too often and also every input value is taken as a final word immediately after typing any letter.

Let's look into that and fix it. 

https://github.com/user-attachments/assets/8d3555d5-ed08-4e0f-8947-22f762f5821f

<details><summary>Issue Owner</summary>Current Issue Owner: @Skalakid</details>

**Comment by Skalakid** [comment]
Hello, I'm Michał from SWM, and I will investigate this issue 😄

**Comment by Skalakid** [comment]
@puneetlath Hi, yes that's the last thing that we have to do. However, I see that there is already another PR that is bumping the LM version and it will contain my fixes for this issue. So I wrote the comment under the PR to include test steps for QAs

**Comment by puneetlath** [comment]
Ah, great!

**Comment by puneetlath** [comment]
Looks like https://github.com/Expensify/App/pull/48626 is meged and on production. I also tested myself and it's feeling much better! Thanks for quick fix.
