### ISSUE TITLE
[$250] [HOLD for payment 2024-10-10] Categories - Spend category field is not grayed out after changing category offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48678]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48391
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click Settings.
4. Go offline.
5. Click on any spend categories.
6. Change the category.

## Expected Result:
The spend category field will be grayed out after changing category offline.

## Actual Result:
The spend category field is not grayed out after changing category offline.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/067ffca3-7c7f-4194-8435-8bec5c6c59ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844768877300090073</li>
        <li>Upwork Job ID: 1844768877300090073</li>
        <li>Last Price Increase: 2024-10-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by miljakljajic** [comment]
I don't think this is a blocker - @iwiznia and also @roryabraham you're on deploy duty, what do you think?

**Comment by iwiznia** [comment]
I think it is, given it comes from the regression testing and it is happening on staging but not prod

**Comment by iwiznia** [comment]
Hmmmm weird, isn't this a new feature?

**Comment by iwiznia** [comment]
It is. It's quite confusing that this says `Reproducible in production?: N`

**Comment by iwiznia** [comment]
This is a new feature added in https://github.com/Expensify/App/pull/48391 by @BartoszGrajdek, so it's probably best that they take this issue. Is that ok @BartoszGrajdek?

**Comment by BartoszGrajdek** [comment]
Yes that's ok, I'll work on it as a follow-up next week 😄

**Comment by miljakljajic** [comment]
I am unassigning for my parental leave - given this is being managed by @BartoszGrajdek I don't think we need to assign another BZ team member, but if I am wrong, go ahead and do that @iwiznia

**Comment by mallenexpensify** [comment]
@akinwale can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021844768877300090073

**Comment by akinwale** [comment]
@mallenexpensify Offer accepted. Thanks!

**Comment by mallenexpensify** [comment]
Contributor+: @akinwale paid $250 via Upwork  

@akinwale plz complete the BZ checklist above

**Comment by akinwale** [comment]
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
_Prerequisites_
1. Create a new workspace
2. Navigate to Workspace Settings > More features > Organize
3. Enable the Categories setting
4. Have the `canUseWorkspaceRules` beta enabled

_Test Steps_
1. Launch Expensify
2. Navigate to the workspace settings > Categories.
3. Click Settings.
4. Go offline.
5. Click on any of the spend categories.
6. Change the category.
7. Verify that the spend category field is grayed out after changing the category offline.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment]
@mallenexpensify BZ checklist completed.

**Comment by mallenexpensify** [comment]
Thanks @akinwale , test case created. 
- https://github.com/Expensify/Expensify/issues/436688
