### ISSUE TITLE
Accounting-App proceeds to Netsuite Setup when trying to connect to Sage Intacct

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48686]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.30-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+shsb223455@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to new dot with a new account and create a new workspace
2. Navigate to settings > workspace > More features > Enable accounting
3. Go to Accounting > Connect to Sage Intacct > Upgrade to Control > Got it
4. Now notice the RHP opened after upgrading the Workspace to control

## Expected Result:
App proceeds to Sage Intacct Setup page

## Actual Result:
App proceeds to Netsuite Setup page. User has to close RHP and connect to Sage Intacct again to proceed with Sage Intacct Setup.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f6f8375b-6a21-4d70-b780-5cd94a44a123

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by suneox** [comment]
@hoangzinh  Thank you, this was our mistake after resolving conflicts and calling the incorrect function. I've verified the PR to resolve this issue

**Comment by trjExpensify** [comment]
Dope, all yours @youssef-lr.

**Comment by youssef-lr** [comment]
Asking for CP here https://expensify.slack.com/archives/C07J32337/p1725645245191609

**Comment by trjExpensify** [comment]
Adding you both, so it's clear who was involved in this issue for posterity. The PR was CP'd to staging and that checklist has now been deployed, so I'm going to close this out. Payment will be handled in the original issue accounting for the regression: https://github.com/Expensify/App/issues/48269

Thanks ya'll!
