### ISSUE TITLE
[HOLD for payment 2024-10-24] [$100] Attachment - Chat blinks when txt attachment is uploaded

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48697]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47778
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in with a Gmail account
2. Open any 1:1 chat
3. Send a txt attachment

## Expected Result:
It shouldn't blink.

## Actual Result:
Chat blinks when txt attachment is uploaded.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/ae460c9c-48f0-4525-b40f-89af1b28b7e5
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833566073242365431</li>
        <li>Upwork Job ID: 1833566073242365431</li>
        <li>Last Price Increase: 2024-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104162747</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by isabelastisser** [comment]
review by EOD

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat blinks when txt attachment is uploaded.

### What is the root cause of that problem?
We get the `download` data via `withOnyx`. It's an old HOC and can affect some weird lifecycle component bugs. As in this case, `BaseAnchorForAttachmentsOnly` disappears and appears again after the API is complete.

https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L81-L84
### What changes do you think we should make in order to solve the problem?
We should remove `withOnyx` in this component and use `useOnyx` to get the `download` data

```
const [download] = useOnyx(`${ONYXKEYS.COLLECTION.DOWNLOAD}${sourceID}`);
```

https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L81-L84


### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/user-attachments/assets/b1e44a1c-1460-43ac-a1f7-a09228b75404

**Comment by isabelastisser** [comment]
@getusha, can you please review the proposal above? thanks!

**Comment by isabelastisser** [comment]
Hey @getusha, any updates?

**Comment by getusha** [comment]
@nkdengineer what about this line?

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/components/AnchorForAttachmentsOnly/BaseAnchorForAttachmentsOnly.tsx#L84

seems like we are not directly using the value

**Comment by nkdengineer** [comment]
@getusha What do you mean? When we remove `withOnyx`, we also remove this line and we already get the sourceID in the component.

**Comment by getusha** [comment]
oh yeah you're right

**Comment by getusha** [comment]
@nkdengineer could you test this on latest main? seems like uploading txt file isn't working on android & ios mweb

**Comment by nkdengineer** [comment]
@getusha I still able to upload the txt file for Android app and web on the latest main.

https://github.com/user-attachments/assets/bc216286-fc51-4871-949d-b68fd3525198


https://github.com/user-attachments/assets/bfb17d16-d507-4a96-af7f-26d56ce388e4

**Comment by isabelastisser** [comment]
@getusha, can you please follow up on the comment above and provide an update? Thanks!

**Comment by isabelastisser** [comment]
Bump @getusha! Thanks!

**Comment by getusha** [comment]
Reviewing

**Comment by nkdengineer** [comment]
@getusha Thanks for your review. Here is my opinion: because this bug isn't a normal migration task, it takes more effort to find the RCA of the issue. Then let us keep the price.

**Comment by nkdengineer** [comment]
@MonilBhavsar Please look at this comment https://github.com/Expensify/App/issues/48697#issuecomment-2371664850 to move forward with this issue, thanks.

**Comment by MonilBhavsar** [comment]
Let's do it 👍

**Comment by MonilBhavsar** [comment]
I have updated the price cc @isabelastisser

**Comment by nkdengineer** [comment]
@getusha this [PR](https://github.com/Expensify/App/pull/49908) is ready for review

**Comment by isabelastisser** [comment]
@getusha, can you please provide an update? Thanks!

**Comment by getusha** [comment]
Reviewing the PR, will complete it in short.

**Comment by isabelastisser** [comment]
@getusha, do we need a regression test? Please complete the list above, thanks!

**Comment by isabelastisser** [comment]
Payment summary:

@getusha requires payment through NewDot Manual Requests - PENDING $100 for C+ review
@nkdengineer paid in Upwork (https://www.upwork.com/nx/wm/offer/104162747) $100 Contributor role

**Comment by isabelastisser** [comment]
Bump @getusha to complete the checklist. Thanks!

**Comment by isabelastisser** [comment]
Thanks, all set!
