### ISSUE TITLE
[$250] [CVP] Subpar account validation flow in the bottom up flow when paying with a business bank account 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#48699]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1725290110940169

## Action Performed:
Prerequisite: The submitter and payer have a personal currency of USD, in order to see the option to `Pay with Expensify`

1. [Submitter] Submit a $50 expense to someone who doesn’t have an Expensify account
2. [Payer] Click the Pay button in the email received to sign-in unvalidated
3. [Payer] Click `Pay with Expensify` > `Business Bank Account`
4. [Payer] Click `Connect with Plaid`

## Expected Result:
When the user lands on the `Connect bank account` page, it should look like this: 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/8f76f9f8-09ef-4f33-b502-5ba50d41f7fc">

_Note: To compare, simply create workspace > enable workflows > payments > connect bank account which shows the above screen to require validation._ 

## Actual Result:
Connect options are not greyed out, user can continue and then hit a subpar auth error on step one of the VBBA setup flow:

![image](https://github.com/user-attachments/assets/3a4d6d2e-e8c0-44e2-84f7-9cf83795498b)

![image (17)](https://github.com/user-attachments/assets/4ffb8302-da98-44dd-b08c-75beaa0ae231)

## Workaround:
Validate the account. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

See above.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832008208936334242</li>
        <li>Upwork Job ID: 1832008208936334242</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>CyberAndrii | Contributor | 103923785</li>
</ul></li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
CC: @NikkiWines @allroundexperts @dukenv0307 with experience on the validation prompt in the connect bank account flow.

**Comment by CyberAndrii** [comment]
The `SigninUserWithLink` request sets `user.validated` to false. Later `OpenApp` overrides it to true.

The `user.validated` property is used to determine whether those buttons should be disabled

https://github.com/Expensify/App/blob/8b348c6049eafe9089bb49d339a68b5e7d423d06/src/pages/ReimbursementAccount/BankAccountStep.tsx#L144

I think this is a BE issue with the `OpenApp` request.

---------------

On the other hand, there's the `account.validated` property that works similarly but doesn't have this bug. I'm confused what's the difference between them.

https://github.com/Expensify/App/blob/8b348c6049eafe9089bb49d339a68b5e7d423d06/src/types/onyx/Account.ts#L66-L67

Anyway, unless there's a way to point the email link to `dev.new.expensify.com:8082`, I don't think external contributors can fix this.

**Comment by s77rt** [comment]
@CyberAndrii Thanks for looking into this. From the Expected results:
> Note: To compare, simply create workspace > enable workflows > payments > connect bank account which shows the above screen to require validation.

Did you get the restricted view or were you able to proceed normally?

**Comment by johncschuster** [comment]
Bumping for Melv

**Comment by trjExpensify** [comment]
@CyberAndrii interesting. Can you continue that flow to adding the account by clicking `Continue` > Choose "Wells Fargo" > U: user_good P: pass_good > follow the prompts to have the modal close and return to Expensify.

**Comment by trjExpensify** [comment]
>Maybe we should use the other one [here](https://github.com/Expensify/App/blob/8b348c6049eafe9089bb49d339a68b5e7d423d06/src/pages/ReimbursementAccount/BankAccountStep.tsx#L144)

Does that fix it when making the change from `!user?.validated` to `!account?.validated` in dev?

**Comment by blazejkustra** [comment]
> I don't I'm afraid. @mountiny might, but also @blazejkustra perhaps just following the blame on when these were touched last.

Unfortunately I don't have much context, I created these types [when migrating the codebase to TS](https://github.com/Expensify/App/pull/24054) 😢

**Comment by CyberAndrii** [comment]
> Does that fix it when making the change from `!user?.validated` to `!account?.validated` in dev?

Yes it does

**Comment by s77rt** [comment]
I think the value in the `account` modal is the source of truth and we should remove `user.validated` from FE and BE.

🎀 👀 🎀 To check the FE and where it's sending user.validated and change it to account.validated (if necessary)

**Comment by s77rt** [comment]
The plan:
1. BE PR to send `account.validated` in any place that we are sending `user.validated`
2. FE PR to use `account.validated`
3. BE PR to remove and stop sending `user.validated`

**Comment by s77rt** [comment]
@francoisl Please assign @CyberAndrii for the [proposed solution](https://github.com/Expensify/App/issues/48699#issuecomment-2334724140)

**Comment by francoisl** [comment]
For now let's do step 2 and use `account.validated` instead of `user.validated` in that flow, but I don't think we should completely remove `user.validated` from the backend - there are a few flows I need to double-check on first.

**Comment by CyberAndrii** [comment]
The PR was [deployed to production](https://github.com/Expensify/App/pull/49130#issuecomment-2353605371) on September 16 so this should be ready for payment

**Comment by johncschuster** [comment]
Payment Summary:

Contributor: @CyberAndrii paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/103923785) - PAID 🎉 
Contributor+: @s77rt due $250 via NewDot

Upwork job [here](https://www.upwork.com/jobs/~021832008208936334242)!

@s77rt do we need a regression test step list here? If so, can you provide one?

**Comment by s77rt** [comment]
@johncschuster I'm not due payment here. The C+ was @ishpaul777 and he is paid already (https://github.com/Expensify/App/issues/49215). I don't think this requires a regression test based on the fact that we had this similar test [1971031](https://expensify.testrail.io/index.php?/cases/history/1971031) and it's now deleted. This can be closed.

**Comment by johncschuster** [comment]
Ah, thank you for the correction, @s77rt! Closing!
