### ISSUE TITLE
[HOLD for payment 2024-09-16] Categories - Unable to select subcategory as the default spend category

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48690]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Add a category in X: Y format.
4. Click Settings.
5. Click on any spend category.
6. Select the subcategory (Y).

## Expected Result:
Subcategory can be selected as the default spend category.

## Actual Result:
Subcategory cannot be selected as the default spend category. It reverts to the previous category after selecting the subcategory.

RBR is shown next to the workspace but there is no error message after selecting the subcategory as the default category.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3c331b38-4af1-47ed-978f-9b380fd0fcdc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by twisterdotcom** [comment]
Don't need another recording to show this one. Very obvious.

**Comment by twisterdotcom** [comment]
I can't find an offending PR here tbh.

**Comment by lakchote** [comment]
The offending PR is https://github.com/Expensify/App/pull/48391

It adds the category spend selector, without it Settings are empty:

![image](https://github.com/user-attachments/assets/85f2bba8-54df-435f-a520-c38430c3b6ee)

**Comment by lakchote** [comment]
CP requested [here](https://expensify.slack.com/archives/C07J32337/p1725640182048459)

**Comment by lakchote** [comment]
QA tests passed since CP ([link](https://expensify.slack.com/archives/C9YU7BX5M/p1725641700250469?thread_ts=1725641215.569279&cid=C9YU7BX5M)).

Removing the deploy blocker label.

**Comment by twisterdotcom** [comment]
Can we close this now @lakchote?

**Comment by lakchote** [comment]
> Can we close this now @lakchote?

Yes, closing!

**Comment by twisterdotcom** [comment]
Ah, okay. When did it his prod?

**Comment by twisterdotcom** [comment]
Payment Summary:

- @ishpaul777 paid $250 via Upwork[here](https://www.upwork.com/nx/wm/offer/new/1007955097) (C+)
