### ISSUE TITLE
Chat - No tool tip for download icon for docx file

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#4870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #4661
## Action Performed:
1. Launch App and login
2. Send any docx file
3. Hover mouse to download sign

## Expected Result:
The tooltip should be appeared

## Actual Result:
No tooltips for download icon.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:**
1.0.88-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

**Expensify/Expensify Issue URL:**

https://user-images.githubusercontent.com/43996225/131057625-86a00a10-6756-4c42-9f06-84940ca135e7.mp4

![Bug5211202_Download](https://user-images.githubusercontent.com/43996225/131057628-ca92086f-e844-4162-a1cb-539df1c7e895.jpg)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kadiealexander** [comment]
Thanks for fixing this @akshayasalvi!! :)

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183084866) to staging by @sketchydroide in version: 1.0.88-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|cancelled 🔪 
🖥 desktop 🖥|cancelled 🔪
🍎 iOS 🍎|cancelled 🔪 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183075988) to production by @roryabraham in version: 1.0.88-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188395063) to production by @roryabraham in version: 1.0.90-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by kadiealexander** [comment]
@akshayasalvi I apologise, I misunderstood @parasharrajat's comment earlier and thought this job doesn't require compensation. I've created the Upwork job here https://www.upwork.com/jobs/~015eb32b62c94f673a please apply so I can hire you and get you paid for this. Thanks!

**Comment by akshayasalvi** [comment]
@kadiealexander I am not sure if this requires payment. When I implemented my PR, I guess Tooltip work wasn't done. I covered it because I thought I'll complete the work.  Nevertheless, I've applied to the Upwork, I let you and the team decide on the payment part.

**Comment by kadiealexander** [comment]
Thanks Akshaya!! I apologise for the confusion here. I've asked the team how we would usually deal with issues like this and will leave it up to the majority. Will let you know!

**Comment by akshayasalvi** [comment]
Thanks @kadiealexander. Appreciate your help

**Comment by kadiealexander** [comment]
Hi @akshayasalvi, the team decided instead of dealing with this separately, we will add a $100 bonus to the initial Upwork post [here](https://github.com/Expensify/App/issues/4601) for the additional work you did here. Thanks again!!

**Comment by akshayasalvi** [comment]
Thank you @kadiealexander. Appreciate it
