### ISSUE TITLE
Android - IOU - In workspace, in edit amount cursor is at beginning instead of end of amount

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap fab -- new workspace
3. Open new workspace chat
4. Submit the expense with big amount with decimals eg: 12588888.66
5. Open the expense
6. Tap edit amount
7. Note the cursor is at beginning instead of end of amount

## Expected Result:
In workspace, in edit amount cursor must be at the end of amount.

## Actual Result:
In workspace, in edit amount cursor is at beginning instead of end of amount.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/92e0ea78-f729-412e-a97c-2c51bc0a2832

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
I think this is resolved, can't repro on staging. It's possible whatever fixed https://github.com/Expensify/App/issues/48301 also fixed this issue 

<img width="286" alt="image" src="https://github.com/user-attachments/assets/d2b6cfb8-3d44-43b0-8c78-92fd5fc888ba">
