### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] Profile - No error after uploading corrupted jpg for avatar, console error shows up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48707]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Profile
3. Click on the avatar > Upload photo
4. Upload a corrupted jpg file (attached below)

## Expected Result:
Error will show up saying that the file is corrupted

## Actual Result:
Nothing happens after uploading corrupted jpg for avatar. Console error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/02abda22-ed71-4391-b7ab-062800ddb63d

[logs (2).txt](https://github.com/user-attachments/files/16907981/logs.2.txt)

![a](https://github.com/user-attachments/assets/6cdb505b-4b33-47a3-a5d4-41bbf0862b75)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833355156424317364</li>
        <li>Upwork Job ID: 1833355156424317364</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103904041</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by lanitochka17** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
@Nodebrute what is the correct file for me to use for testing? Or, how does one create a "corrupted" jpeg file?

**Comment by RachCHopkins** [comment]
Reproduced. As a user it feels rfeally weird cos just _nothing happens_.

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by RachCHopkins** [comment]
@Ollyws are there any regression tests needed here?

**Comment by RachCHopkins** [comment]
Sorry @Ollyws I didn't notice that Melvin left that little detail out!

Payment Summary:

- Contributor: @Krishna2323 paid $250 via Upwork
- Contributor+: @Ollyws to be paid $250 via NewDot manual request

Upwork job [here](https://www.upwork.com/jobs/~021833355156424317364)

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
