### ISSUE TITLE
Track – Track expenses video in new tab shows Normal speed when speed is updated

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48705]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4933372&group_by=cases:section_id&group_order=asc&group_id=309130
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to FAB> Track
2. Verify "Track you expenses modal" appears
3. Go to 3-Dot menu> Playback speed> Change the playback speed
4. Go to 3-Dot menu> Download
5. Verify video is open in new tab
6. Go to the 3-Dot menu on a video that is open in new tab> Playback speed
7. Take a look at playback speed modal details

## Expected Result:
Real playback speed should be displayed

## Actual Result:
Playback speed is signed as normal, even the video is playing faster/slower

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/4621033a-4876-4fa2-b227-7b93a5ced8be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abekkala** [comment]
Looks like this is already being worked on 42425
