### ISSUE TITLE
[HOLD for payment 2024-09-18] Invoice - Creating invoice display unexpected error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48701]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.30-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap fab-- new workspace
3. Tap fab -- send invoice selecting a user

## Expected Result:
Creating invoice must not display unexpected error.

## Actual Result:
Creating invoice display unexpected error.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bbc89d88-585b-4d58-8791-8727fabac225

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
BE error,
Onyx data 
```
{
    "jsonCode": 402,
    "message": "402 missing companyName or companyWebsite",
    "onyxData": [],
    "requestID": "8bee463eb9014856-BOM"
}
```

**Comment by adelekennedy** [comment]
@cristipaval adding you here for a quick check - I can reproduce this and this seems like something we should address ASAP - is this being addressed anywhere else?

**Comment by rlinoz** [comment]
Cristi is on parental leave so I will take this over.

**Comment by VickyStash** [comment]
There are still a couple of issues related to invoicing creation on the main which I can see:
1) The user can send the invoice even from the workspace where invoicing feature is disabled. It should be fixed with this [PR](https://github.com/Expensify/App/pull/48728), but I'm waiting for API fixes to open the PR for the review.

https://github.com/user-attachments/assets/a8872eaa-6ab1-48dc-bbd3-3abe64673698

2) API doesn't return `invoice` information inside policy for `OpenApp` API call. It makes the app ask a user about the Company name and Company website every time the user re-login the app and tries to send the invoice.

cc @madmax330

**Comment by rlinoz** [comment]
@VickyStash I would add to the above list that if you use a fake URL the API will return an error but we are not displaying that anywhere and we are not clearing the onyx data.

**Comment by VickyStash** [comment]
> @VickyStash I would add to the above list that if you use a fake URL the API will return an error but we are not displaying that anywhere and we are not clearing the onyx data.

@rlinoz Could you please provide more exact steps to reproduce it?

**Comment by rlinoz** [comment]
@VickyStash my bad we actually show a RBR, but there is not much context to what happened.

Here are the steps:
1. Start the send invoice flow for the first time
2. Input fake data for the company, like test and https://test.com
3. Verify the backend response for SendInvoice is something like:
```
{
  "jsonCode": 507,
  "message": "507 Stripe error 'invalid_request_error': Not a valid URL",
  "additionalData": {
    "errorMessage": "Not a valid URL",
    "errorType": "invalid_request_error"
  },
  "onyxData": [],
  "requestID": "8c207d0978f14e0b-SOD"
}
```
4. Try to send a new invoice to someone
5. Verify the screen to fill company data doesn't show up and now you get the following erro:
```
{
  "jsonCode": 402,
  "message": "402 missing companyName or companyWebsite",
  "onyxData": [],
  "requestID": "8c207d67af8c4e0b-SOD"
}
```

https://github.com/user-attachments/assets/c660f35c-973c-465f-8d0e-6ec841f5e3ea

**Comment by VickyStash** [comment]
@rlinoz I've fixed the failure data so now the company name and website will be cleared out if the response was unsuccessful.
That's how it looks:

https://github.com/user-attachments/assets/824ae465-f701-4e35-a964-733ac0deafe4

Errors:
<img width="851" alt="Error1" src="https://github.com/user-attachments/assets/21ed90b7-3922-42de-b299-81e516a73291">
<img width="847" alt="error2" src="https://github.com/user-attachments/assets/34747072-43ed-4c8c-a8de-396f110b52a2">

Let me know if we need to change anything. cc @madmax330

**Comment by rlinoz** [comment]
Yeah, that looks good to me

**Comment by rlinoz** [comment]
I believe we can close this one.
