### ISSUE TITLE
Update Plaid UI to use our standard external link pattern

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#48719]
# Problem 
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1723726773627719?thread_ts=1723657499.841079&cid=C06ML6X0W9L), the Plaid connection flows (for both personal bank accounts and VBAs) don't use the standard external linking pattern we recently decided on. This hinders a consistent product experience to the customer throughout the application. 

# Solution 
Update the background for our Plaid connection UI (both deposit bank accounts and VBAs) to use the same background we're using with our new standard external linking UI. We'll still use the same in-product Plaid modal as today, but instead of the grey background we'll display a RHP page that tells you to check your browser window, similar to what we're planning with cards (but minus the an actual external window). 

Here is a similar example of how the background would look going forward (ignore the browser window overlay):

![image](https://github.com/user-attachments/assets/4aabbe6a-35f2-43a7-b841-ff711f10cab7)

Vs the grey background we use now:

![image - 2024-09-06T110244 808](https://github.com/user-attachments/assets/775e26fb-da04-4085-bb04-f263f27c8799)

cc @Expensify/design @trjExpensify

**Comment by joekaufmanexpensify** [comment]
Leaving this in planning until we finish the card implementation. Will make this external then!

**Comment by shawnborton** [comment]
What is the benefit of moving the Plaid flow to be outside of the product?

**Comment by joekaufmanexpensify** [comment]
In the thread I linked above, we landed on using a consistent pattern for all of these scenarios where we link externally.
