### ISSUE TITLE
Update QBO/Xero connection to use standard external link pattern 

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#48720]
# Problem 
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1723726773627719?thread_ts=1723657499.841079&cid=C06ML6X0W9L), the QBO/Xero connection flows don't use the standard external linking pattern we recently decided on. This hinders a consistent product experience to the customer throughout the application. 

# Solution 
Update the QBO/Xero connection UI use the new standard external linking pattern. This means instead of linking out to a new browser tab to connect to QBO/Xero, we'll open the QBO/Xero connection as a new small-centered window overlaying New Expensify, and display a RHP page that tells you to check your browser window, and offers the opportunity to open another connection window (if the first one didn't open), similar to what we're planning with cards. 

Here's an example of what we'd be trying to do with QBO/Xero: 

![image](https://github.com/user-attachments/assets/3449b1ab-0a2c-45a6-a491-99bc03f3b250)

Vs what we do now: 

https://github.com/user-attachments/assets/ae09e05e-9599-4c86-a1ee-d91b0314d2ac

We [also decided](https://expensify.slack.com/archives/C06ML6X0W9L/p1728974036937079?thread_ts=1723657499.841079&cid=C06ML6X0W9L) to update the mobile view for QBO/Xero to match the stacking design we're using to link out to banks for third party direct workspace feeds, like this: 

![CleanShot 2024-09-12 at 15 32 04@2x](https://github.com/user-attachments/assets/120277f3-99b6-4637-8de1-543398094682)

cc @Expensify/design @trjExpensify

**Comment by joekaufmanexpensify** [comment]
Leaving this in planning until we finish the card implementation. Will make this external then!

**Comment by dubielzyk-expensify** [comment]
Like this? 
![image](https://github.com/user-attachments/assets/7f818ae4-463b-4692-97bf-a2828dc9917f)

Btw, this would only work on desktop right cause on mobile it has to open the link in the app of the external browser?

**Comment by joekaufmanexpensify** [comment]
Looks solid. Though I think we still want to show the RHP for consistency, no? 

>Btw, this would only work on desktop right cause on mobile it has to open the link in the app of the external browser?

Yep, this is only for web/desktop. We wouldn't change the behavior for mobile because we don't link out to the mobile browser or anything like that.

**Comment by dubielzyk-expensify** [comment]
Updated mocks for desktop:

![image](https://github.com/user-attachments/assets/bd71b05a-0940-4dcb-8a02-a0732ebd5f82)

**Comment by joekaufmanexpensify** [comment]
Looks great to me!

**Comment by dubielzyk-expensify** [comment]
Sweet. Let me know if you need any changes down the line 👍
