### ISSUE TITLE
[Workspace Feeds] Add card disclaimer below the fold on Expensify Card page (pre-enablement)

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48729]
# Background

[thread](https://expensify.slack.com/archives/C036QM0SLJK/p1725642565472339?thread_ts=1725487960.192239&cid=C036QM0SLJK)

We need to show the following disclaimer when advertising the card, and we aren't currently doing this before the card is enabled. 

> The Expensify Visa® Commercial Card is issued by The Bancorp Bank, N.A., Member FDIC, pursuant to a license from Visa U.S.A. Inc. and may not be used at all merchants that accept Visa cards.

# Solution

Add the disclaimer below the fold on the Expensify Card page

**Comment by mountiny** [comment]
https://github.com/Expensify/App/issues/48733 is where we will handle payments

**Comment by trjExpensify** [comment]
Cool, so we'll just close this one once it goes to prod then right?

**Comment by mountiny** [comment]
yeah I think we can close now already as there wont be a regression from this
