### ISSUE TITLE
[HOLD for payment 2024-10-02] [$250] [Workspace feeds] Virtual card flow should not have a card name as suggested text 

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48732]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1725488084068029

## Action Performed:

1. Sign up with gmail account added to Workspace feeds beta
2. Enable Expensify Card in more features
3. Complete setup using credentials from option 3 in the [SO](https://stackoverflowteams.com/c/expensify/questions/342)
4. Go through issue card flow, land on card name step

## Expected Result:
Card name should not have suggested text in the virtual card step

## Actual Result:
We show a suggested name

![image](https://github.com/user-attachments/assets/ccf415c7-1cf2-4921-8957-71c2b655bb46)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832329231446894325</li>
        <li>Upwork Job ID: 1832329231446894325</li>
        <li>Last Price Increase: 2024-09-07</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103858804</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by twisterdotcom** [comment]
Oh wait, I just added `External` because I thought this was fine to add, but I am seeing now that you assigned @mountiny. Just want to clarify for proposers now that this _may_ be internal, but... it does seem like we could get a contributor to do it.

**Comment by mountiny** [comment]
We are planning to handle these as workspace feeds polish to get it released asap. Rajat and Ishpaul will tackle it

**Comment by mountiny** [comment]
@parasharrajat Can you also link this to the PR you are working on?

**Comment by trjExpensify** [comment]
Hit prod two weeks ago, @parasharrajat and @ishpaul777 need paying @twisterdotcom.

**Comment by mountiny** [comment]
$250 to @parasharrajat and to @ishpaul777

**Comment by twisterdotcom** [comment]
Payment Summary:

- @parasharrajat paid $250 via Manual Requests (C+)
- @ishpaul777 paid $250 via Upwork [here](https://www.upwork.com/nx/wm/workroom/38308461/overview) (Contributor)

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
