### ISSUE TITLE
[Awaiting Payment 27th Sept] [Workspace Feeds] Remove confirmation step for adding a bank account in broader VBBA flow.

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48730]
### Background

[thread](https://expensify.slack.com/archives/C036QM0SLJK/p1725488034140639)

We're showing a "double check to make sure everything is right" screen after someone adds a bank account, which is only a single action. This makes the step of choosing an account and then confirming that account right after redundant. 

### Action performed

1. Sign up with gmail account added to Workspace feeds beta
2. Enable Expensify Card in more features
3. Select `Issue card` to kick off the enablement flow
4. Add a test bank account setup using credentials from option 3 in the [SO](https://stackoverflowteams.com/c/expensify/questions/342)

### Expected behavior
No additional confirmation screen after immediately adding the bank account

### Actual behavior

We show a confirmation screen right after adding the account. 

![image](https://github.com/user-attachments/assets/bc06df41-122b-4a46-80c6-9e7b22e134f2)

![image](https://github.com/user-attachments/assets/93290086-3632-4191-9120-020f0df5b7bc)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832130991616168173</li>
        <li>Upwork Job ID: 1832130991616168173</li>
        <li>Last Price Increase: 2024-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 103858796</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by trjExpensify** [comment]
Going to take `Help wanted` off this for a second, as we have peeps working on the project.

**Comment by mountiny** [comment]
Payment will be handled at https://github.com/Expensify/App/issues/48732 once done

**Comment by mountiny** [comment]
@parasharrajat yeah lets remove the confirmation page from both

**Comment by mountiny** [comment]
@parasharrajat Not sure if I follow but I would say that if the user goes back in the form flow, the fields should be editable

**Comment by trjExpensify** [comment]
Updated the titles to reflect the payment date. PR hit prod 4 days ago.

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @parasharrajat for the fix
- $250 to @ishpaul777 for the C+ review

Rajat, go ahead and request. @ishpaul777, please accept the [pending offer](https://www.upwork.com/nx/wm/offer/103858796).

**Comment by trjExpensify** [comment]
Paid, closing!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
