### ISSUE TITLE
[$250] [Hybrid app]- Uploaded attachment is not visible and loading spinner on details page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48742]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-12
**Reproducible in staging?:** Yes
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725646723595009

## Action Performed:
1.Launch the app
2. Initiate a DM and upload any attachment (Both by taking picture and from gallary)
## Expected Result:
Uploaded image visible in chat and user able to view the details when tapped
## Actual Result:
After it processes the request the image is not visible, If you click into detail the image does not load
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a05406a6-7667-4d19-8423-a02467609e86

<img src="https://github.com/user-attachments/assets/c8291d2e-160d-4f28-969a-3af931819adb" width="40%" height="40%">

https://github.com/user-attachments/assets/3e7d23bd-fad7-4bb3-8e05-ff884f5573d2

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832581305859837887</li>
        <li>Upwork Job ID: 1832581305859837887</li>
        <li>Last Price Increase: 2024-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103885517</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by war-in** [comment]
Hi 👋 I'm Marcin from SoftwareMansion and I prepared two PRs ([ND](https://github.com/Expensify/App/pull/48781), OD) fixing this issue :)
