### ISSUE TITLE
[$500] Hold - Approved reports change currency when owner change the approver and return it back

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48743]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4937429&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+workspaceapprover177@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
1. Login as the owner of the workspace
2. Create a workspace
3. Invite the approver and employee
4. Navigate to more features
5. Enable "workflows"
6. On the "Workflow" editor - enable "Add Approvals"
7. Set the Approver account as the Approver

Steps:
1. As employee submit 2 expenses to the workspace chat ( using MKD currency for example)
2. As Approver Hold one of the expenses and fully approve the report
3. As Owner, go to Workflows> Assign yourself as Approver
4. Verify that Workspace chat disappears from Approver's LHN
5. As Owner, go to Workflows> Assign Approver as Approver again
6. As Approver, open the Workspace chat> Take a look at the currency of approved report

## Expected Result:
Approved report should remains with same currency as created

## Actual Result:
Approved reports change currency ( from MKD to USD) when owner change the approver and give the same role to the approver again.
Issue repro for Gmail account.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f47bffa4-59c3-4dbf-97b0-662a35b779e8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833692522883497533</li>
        <li>Upwork Job ID: 1833692522883497533</li>
        <li>Last Price Increase: 2024-09-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
This is strange, I do thing it should be fixed.

**Comment by stephanieelliott** [comment]
Waiting on some proposals

**Comment by stephanieelliott** [comment]
Upping the price on this to generate some proposals

**Comment by abhinaybathina** [comment]
Hi team, I am able to reproduce this even without the need of changing the approver and I think this issue is in the backend itself. Once the report was created with a currency (let's say USD), all the expenses in that report even with other currency (let's say MKD) all these expenses gets converted into report's currency (i.e. USD). Once the expected behaviour is confirmed from the team, please let me know. I can pick this issue. Thanks!

**Comment by stephanieelliott** [comment]
> Once the report was created with a currency (let's say USD), all the expenses in that report even with other currency (let's say MKD) all these expenses gets converted into report's currency (i.e. USD).

I thought I was having trouble reproing this and now I see why -- this is actually expected behavior for the currency to update to the report currency. Gonna close.
