### ISSUE TITLE
Expense - Second expense shows error when submitting two expenses to workspace chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48763]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-15
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account.
3. On Onboarding flow, choose "Something else" and complete the flow (Important).
4. Create a new workspace.
4. Go to workspace chat.
5. Submit two expenses from the main chat.
6. Click on the expense preview.

## Expected Result:
Describe what you think should've happened

## Actual Result:
The second expense throws unexpected error.
After dismissing the error for the second expense, the expense remains but the composer is hidden in the transaction thread.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e648fb44-8f5f-45ad-9e87-4116f93bac87

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Shahidullah-Muffakir** [comment]
@IuliiaHerets I was able to reproduce the issue as described. However, I’m not sure if the video included in the OP is directly related to the issue.

**Comment by IuliiaHerets** [comment]
@Shahidullah-Muffakir Sorry, I attached the wrong video, fixed it now

**Comment by mountiny** [comment]
Not and app blocker, this works when you use staging app and production be

production App and Web:
https://github.com/user-attachments/assets/071f83ee-3033-4086-bd26-035dcf9afc61

Staging App and production Web:

https://github.com/user-attachments/assets/2fb6d67a-a328-4021-94a1-92f2b07cdd5c




This is the failing issue in the BE, [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228c06ffb5cb7d2798-PRG%22%20AND%20timestamp%3A%5B2024-09-09T00%3A00%20TO%202024-09-10T23%3A59%5D):
```
TransactionAPI - Error thrown in requestMoney TypeError - 7efcf0a28c9b01b8efd428250568042b ~~ iouReportID: '5748743523017947' chatReportID: '2345769329381682' transactionID: '6296389466609649841' exceptionMessage: 'Report_Action_Collection::buildAction(): Argument #1 ($actionArray) must be of type array, int given, called in /git/releases/expensify.com/2accc07/lib/TransactionUtils.php on line 1237' exceptionFile: '/git/releases/expensify.com/2accc07/lib/Report/Action/Collection.php' exceptionLine: '13' exceptionCode: '0'
```

**Comment by iwiznia** [comment]
This was fixed by https://github.com/Expensify/Web-Expensify/pull/43429
