### ISSUE TITLE
[HOLD for payment 2024-09-24][$250] Investigate `useOnyx` crash when changing `policy_-1` key to `policy__FAKE_`

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#48777]
During our tests to migrate `withOnyx` usage to `useOnyx` in the codebase, we noticed this crash that is happening in `useOnyx`:

![image (2)](https://github.com/user-attachments/assets/f8927582-4d80-4c55-8734-41bbab3e2d09)

It shouldn't error because `policy_-1` and `policy__FAKE_` are both valid collection member keys.

We must investigate and propose a fix to allow this use case to happen.

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by nkdengineer** [comment]
@fabioh8010  The problem here is `splitCollectionMemberKey` function returns the wrong collection key if the key is `policy__FAKE_`. Instead of auto-detecting the collection key via `splitCollectionMemberKey`, we can pass the collect key to `useOnyx` hook and then use this in the check `isCollectionMemberKey`. Or we can detect the collection key via the matched string of `previousKey` and `key`.

 What do you think?

**Comment by fabioh8010** [comment]
> we can pass the collect key to useOnyx hook

Do you mean passing like this?

```ts
const [policy] = useOnyx(ONYXKEYS.COLLECTION.POLICY, `${ONYXKEYS.COLLECTION.POLICY}${policyID}`);
```

If yes, I don't think it's a good idea – it's a change in the core API and it's too big to justify fixing this issue. We should focus on fixing `splitCollectionMemberKey` to allow this use case to happen. I took a look and I know what is happening, I will need to take some time to think how to make such cases possible.

**Comment by mountiny** [comment]
How is this looking so far @fabioh8010 any ideas for a fix?

**Comment by fabioh8010** [comment]
We are iterating on some solutions but given the current flexibility of the key / collection key it's been difficult to find one that satisfy all cases. We've achieved the closest working solution [here](https://github.com/Expensify/react-native-onyx/compare/main...fabioh8010:react-native-onyx:bugfix/split-collection-member-key), but is not final yet as one test is failing. cc @VickyStash

**Comment by trjExpensify** [comment]
Should we make this a deploy blocker?

**Comment by fabioh8010** [comment]
@VickyStash is working on a workaround for the Expensify Card issue [here](https://github.com/Expensify/App/pull/49173), context [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1726213062130159). It would be better if we were able to move with the workaround, so we will have more time to think in proper solution for `useOnyx`.

**Comment by fabioh8010** [comment]
> We've achieved the closest working solution [here](https://github.com/Expensify/react-native-onyx/compare/main...fabioh8010:react-native-onyx:bugfix/split-collection-member-key), but is not final yet as one test is failing.

Actually I think the failing test is just wrong, looking into it 👀

**Comment by fabioh8010** [comment]
Created a PR for this: https://github.com/Expensify/react-native-onyx/pull/581

**Comment by s77rt** [comment]
Waiting on Onyx PR

**Comment by fabioh8010** [comment]
PR was merged!

**Comment by lschurr** [comment]
Looks like the automation didn't work here. Payment date will be 09-24-24 if there are no regressions.

**Comment by lschurr** [comment]
Payment summary for 9/24:

- Contributor: @fabioh8010 (no payment needed - contractor)
- Reviewer: @s77rt $250 (to be paid in NewDot)

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
