### ISSUE TITLE
[HybridApp] Android status icons hidden in status bar

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#48782]
### Problem

Android status bar icons can't be seen. They are displayed in dark mode, despite the OS being set to light mode (ie, clock, battery indicator, etc). They show in NewDot standalone app.

Raised [here](https://expensify.slack.com/archives/C05LX9D6E07/p1725855054298299) in Slack.

![image (20)](https://github.com/user-attachments/assets/c41c4a52-d562-4870-9ab2-61aae20c5e17) ![image (21)](https://github.com/user-attachments/assets/970452d0-a0c5-4190-b219-bf3571c4349e)

### Solution

Unknown.

**Comment by Julesssss** [comment]
FYI @AndrewGable, it is added to project

**Comment by AndrewGable** [comment]
Cc @war-in @mateuuszzzzz @staszekscp

**Comment by trjExpensify** [comment]
Yeah, can SWM pick this one up if Jules is focusing on #47868 which is a blocker?

**Comment by war-in** [comment]
Hi 👋 I'm Marcin from Software Mansion and I'd like to work on this one

**Comment by trjExpensify** [comment]
Excellent, thanks!
