### ISSUE TITLE
[HybridApp] Android App not using our custom font

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#48783]
### Problem

The Android HybridApp (new experience) is not using our custom font correctly.  Raised [here](https://expensify.slack.com/archives/C05LX9D6E07/p1725855054298299) in Slack.

![image (20)](https://github.com/user-attachments/assets/c41c4a52-d562-4870-9ab2-61aae20c5e17) ![image (21)](https://github.com/user-attachments/assets/970452d0-a0c5-4190-b219-bf3571c4349e)

### Solution

???

**Comment by Julesssss** [comment]
FYI @AndrewGable, it is added to project

**Comment by staszekscp** [comment]
I'm on it!
