### ISSUE TITLE
Android&iOS - App crashes after uploading a new build

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48799]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.31-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the App
2. Go to the Accounting settings -> About -> App download links -> Android/iOS and update the build
3. Open the updated App

## Expected Result:
App opens

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5181d474-1967-4835-ab86-f64f60b5f6ed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
We have 56 crash events on:

```
TypeError: Cannot read property 'trace' of undefined, js engine: hermes, stack: stopTrace@1:3264012 end@1:3262539 anonymous@1:3682555 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:3702929 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:3689224 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:3492826 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:2893045 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:2600748 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:2593397 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:2592413 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:2339574 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:1881305 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:1388523 loadModuleImplementation@1:187057 guardedLoadModule@1:186285 metroRequire@1:185567 anonymous@1:196731 loadModuleImplementation@1:187057 guardedLoadModule@1:186242 metroRequire@1:185567 global@1:184494
```

**Comment by blimpich** [comment]
CC: @hannojg @marcaaron since you made [this PR](https://github.com/Expensify/App/pull/48654) which looks like it might be linked to this

**Comment by blimpich** [comment]
@luacmartins was able to confirm that the above mentioned PR is the issue. When reverted it fixes the issue locally.

**Comment by luacmartins** [comment]
The App crashes [here](https://github.com/Expensify/App/blob/62f8d36492bde98d76196757508bd2e47f123582/src/libs/Firebase/index.native.ts#L44), when trying to access `trie_initialization` in `traceMap` which is empty at the time.

**Comment by roryabraham** [comment]
first off, this is almost certainly a front-end issue, right? Should we remove `DeployBlocker`?

**Comment by roryabraham** [comment]
> Moving [this call](https://github.com/Expensify/App/blob/62f8d36492bde98d76196757508bd2e47f123582/src/libs/EmojiTrie.ts#L17) and [this call](https://github.com/Expensify/App/blob/62f8d36492bde98d76196757508bd2e47f123582/src/libs/EmojiTrie.ts#L136) to inside buildEmojisTrie solves the issue too, but I'm not sure if that's the right method we want to time

That actually looks more correct than what we have now. I feel like having the timings where they are now only times how long it takes to import the file, not how long it actually takes to build the trie.

So yes, that seems like a good change 👍🏼

**Comment by luacmartins** [comment]
This is fixed in staging.

**Comment by luacmartins** [comment]
Ok, this is solved now.
