### ISSUE TITLE
[$250]  The report action logging the renaming of an expense report says "renamed this room".

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48794]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1725638589810419

## Action Performed:

1. Setup an automatic report title with the policy name in it in old dot
2. Create a report using that old policy name
3. The policy settings are updated to change the policy name
4. Open the report as submitter 

## Expected Result:
Report name updated as per the change and report action attributes to the Admin who changed the report name
## Actual Result:
The report name changes but the report action attributes the change to whoever opened the report

The report action also logs "renamed this room" which is incorrect

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/ed86816d-7023-43fe-89b9-73fd56c5b7dd" width="40%" height="40%">

![Full Screen #13](https://github.com/user-attachments/assets/00175819-f155-44e5-9df4-3fbfe48d3427)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835684649465149612</li>
        <li>Upwork Job ID: 1835684649465149612</li>
        <li>Last Price Increase: 2024-10-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by muttmuure** [comment]
Handling tomorrow

**Comment by muttmuure** [comment]
Updated the actual behavior a bit

**Comment by muttmuure** [comment]
Waiting for proposals

**Comment by muttmuure** [comment]
Waiting for proposals

**Comment by muttmuure** [comment]
Waiting for proposals

**Comment by muttmuure** [comment]
Is this still happening?

**Comment by muttmuure** [comment]
Not overdue

**Comment by TalhaAmjad0034** [comment]
Can't able to reproduce this with the mentioned steps, Can we get the video of reproducing steps for this one please.

**Comment by TalhaAmjad0034** [comment]
Contributor details
Your Expensify account email: talha.nexas1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ef23ac719a1e23e4
