### ISSUE TITLE
Payment issue for C+ handling the report fields configuration project

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#48802]
We have had 2 C+ handling all the PRs related to the [Report fields configuration project](https://github.com/Expensify/Expensify/issues/365155). This took over 20 PRs handling optimistic actions as well and we agreed on the following bounties:
- $3000 to @rushatgabhane 
- $4000 to @shubham1206agra 

By completing this project, users are now able to enable report fields feature on control policies in NewDot, create new report fields of three different types, edit them and delete them all in NewDot

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mountiny** [comment]
Sorry for the ping

**Comment by garrettmknight** [comment]
$3000 approved for @rushatgabhane

**Comment by JmillsExpensify** [comment]
@shubham1206agra sent you an offer via Upwork.

**Comment by JmillsExpensify** [comment]
Thanks! Payment sent via Upwork.
