### ISSUE TITLE
Room - Dropdown button does not update the selected member count after deleting member

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48801]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** 9.0.31-0
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to room.
3. Click on the room header > Members.
4. Add two users to the room.
5. Select all members via the checkbox.
6. Click on any member (except the room owner).
7. Click Remove from chat.
8. Click Remove.

## Expected Result:
The dropdown button will update the selected member count to 1.

## Actual Result:
The dropdown button does not update the selected member count after deleting member.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/50e0f5cd-2225-402d-98d4-e03c3e27e34c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is fixed on staging.
