### ISSUE TITLE
[$125] Rules - Page scrolls up after dismissing Auto-pay reports under RHP

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48803]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Rules.
3. Enable Auto-pay approved reports.
4. Click Auto-pay reports under.
5. Dismiss the RHP via back button or click outside the RHP.

## Expected Result:
The page will not scroll up after dismissing Auto-pay reports under RHP.

## Actual Result:
The page scrolls up after dismissing Auto-pay reports under RHP.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4c37078e-25a6-42d6-b670-c7cd1d913d2d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833441015435016039</li>
        <li>Upwork Job ID: 1833441015435016039</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 103987439</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment]
I'll demote this to NAB since it's a minor issue.

**Comment by eVoloshchak** [comment]
@cretadn22's [proposal](https://github.com/Expensify/App/issues/48803#issuecomment-2339509500) looks good to me!

🎀👀🎀 C+ reviewed!
