### ISSUE TITLE
Approval - "It"s not here" error when saving the "Edit approval workflow"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48818]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4939059&group_by=cases:section_id&group_order=asc&group_id=309128
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a Gmail account
3. Crate a workspace
4. Navigate to Workspace settings - Members
5. Invite a Gmail account
6. Navigate to Workspace settings - More features
7. Enable "Workflows"
8. Navigate to Workspace settings - Workflows
9. Enable "Add approvals"
10. Click inside the bracket under "Add approvals"
11. Click on "Approver"
12. Select the member
13. Click on the "Save" button
14. Click on the "Save" button

## Expected Result:
There shouldn't be any error messages.

## Actual Result:
"It"s not here" error briefly appears when saving the "Edit approval workflow".

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/bef5bed8-e3ea-454a-a209-d926b5f8d513

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment]
This is so brief (I was looking out for it and barely caught it) that I don't think this is a priority, closing
