### ISSUE TITLE
[HOLD for payment 2024-09-19][Search v1.2] Sort report views by newest transaction date

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48819]
## Problem
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1725855506074159), we're sorting report views by the report date, instead of transaction date

## Solution
Sort report views by the newest transaction date.

**Comment by luacmartins** [comment]
Got a PR upd

**Comment by stephanieelliott** [comment]
Looks like the automation didn't work, this was deployed to prod 9/12. Updating to note 7 day hold before issuing payment t

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: N/A Internal 
 - Contributor+: @ikevin127 $250 via Upwork -- offer sent, please accept when you get a chance https://www.upwork.com/nx/wm/offer/104050499
 
 Upwork job is here: https://www.upwork.com/jobs/~021837012605241491332

**Comment by ikevin127** [comment]
@stephanieelliott Offer accepted, thank you!

**Comment by stephanieelliott** [comment]
All paid! Thanks
