### ISSUE TITLE
[$62.50] Update icon for set default contact method button

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#48813]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @joekaufmanexpensify 
**Slack conversation:** https://www.figma.com/design/vBXCQWjQExxcmZjFxbME4C?node-id=1976-7777#929159322

## Action Performed:
Use an account with more than one account login. 

1. Go to Account Settings. 
2. Profile. 
3. Contact Method. 
4. Click secondary login. 

## Expected Result:
We want the `Set as default` button to use the star icon, rather than the profile icon it uses now. We want all "set as default" actions to use the star going forward. 

<img width="1511" alt="2024-09-09_14-32-05" src="https://github.com/user-attachments/assets/c680264b-6f98-4450-a10b-f0eb2dd4b80b">

## Actual Result:
Set as default button here doesn't have the star icon right now. 

## Workaround:
N/A

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
See above. 

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833213344949311946</li>
        <li>Upwork Job ID: 1833213344949311946</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 103901470</li>
<li>Nodebrute | Contributor | 103901472</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by joekaufmanexpensify** [comment]
cc @Expensify/design as we were discussing this in Figma

**Comment by joekaufmanexpensify** [comment]
Updated price here as this is very minor change

**Comment by dannymcclain** [comment]
Woo! @joekaufmanexpensify thanks for making this issue. As far as I can tell, the `star` icon is not yet in the repo. I've gone ahead and exported it so we can add it as part of this issue or as part of the card feed updates. Either works!

[Star.svg.zip](https://github.com/user-attachments/files/16935178/Star.svg.zip)

**Comment by joekaufmanexpensify** [comment]
Sweet. TY!

**Comment by DylanDylann** [comment]
@Nodebrute's proposal looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by isabelastisser** [comment]
Sorry for the delay, reviewing this now.

**Comment by isabelastisser** [comment]
Payments were processed in Upwork!
