### ISSUE TITLE
Expense - Two "Members" titles in Members page in expense report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48821]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Submit an expense to any user.
4. Click on the expense preview.
5. Click on the report header,
6. Click Members.

## Expected Result:
There will be only one "Members" title which is the header title.

## Actual Result:
There are two "Members" titles - one in the header, one above the table.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7677d50d-a452-4e4a-8fcd-33732d683439

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
Agree, let's close!
