### ISSUE TITLE
[HOLD for Payment 2024-10-01][Search v2.2] Create Pinned status for chats

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48823]
Coming from [here](https://github.com/Expensify/App/pull/47690#issuecomment-2338627041), we'll deprecate the `Has` and `Is` filters from the Advanced Search page and move them to the status bar.

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by CortneyOfstad** [comment]
Since Rach is assigned here, I'm going to remove my assignment — thanks!

**Comment by luacmartins** [comment]
PRs in review

**Comment by luacmartins** [comment]
@ikevin127 API PR is deployed

**Comment by RachCHopkins** [comment]
@carlosmiceli automation is borked, does anyone need to be paid here?

**Comment by luacmartins** [comment]
Not yet, the App PR is still in revie

**Comment by ikevin127** [comment]
^
> This is expected. Search doesn't work offline. Closing.

From the regression issue reported above.

**Comment by ikevin127** [comment]
⚠️ Automation failed here -> this should be on **[HOLD for Payment 2024-10-01]** according to today’s production deploy from https://github.com/Expensify/App/pull/49186#issuecomment-2372093605.

cc @RachCHopkins

**Comment by RachCHopkins** [comment]
@ikevin127 was there an upwork job? I just want to check before I create one and send you an offer!

@luacmartins can you please confirm it's a $250 payment for @ikevin127 here?

**Comment by ikevin127** [comment]
@RachCHopkins From what I know, there wasn't any Upwork job created for this issue.

**Comment by luacmartins** [comment]
Yes $250 payment for @ikevin127

**Comment by RachCHopkins** [comment]
[Offer](https://www.upwork.com/nx/wm/offer/104204108) sent @ikevin127 

[Upwork Job](https://www.upwork.com/ab/applicants/1840890969823152483/job-details)

**Comment by ikevin127** [comment]
@RachCHopkins Offer accepted, thank you!

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.
