### ISSUE TITLE
Room - Error instructs to invite users to #announce when users cannot be invited to #announce

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48831]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4938531
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Members.
3. Invite more than 8 members.
4. Go to #announce.
5. Click on the room header > Members.
6. On the search field, enter term that will not return result.

## Expected Result:
The error message for invalid search term will not show the prompt to invite member using the invite button because users cannot be invited manually in #announce room.

## Actual Result:
The error message is "Member not found. To invite a new member to the room, please use the invite button above." when there is no invite button as users cannot be invited manually in #announce room.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0f44c2a7-1b23-48a4-ab83-07fe91d1aa0f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment]
This is coming from: https://github.com/Expensify/App/pull/47201

**Comment by luacmartins** [comment]
Demoting to NAB since it's a small copy change.

**Comment by yuwenmemon** [comment]
Assigning @jamesdeanexpensify from https://expensify.slack.com/archives/C01GTK53T8Q/p1725915664037679 to give a closer look to copy.

**Comment by jamesdeanexpensify** [comment]
(handling in thread)

**Comment by dubielzyk-expensify** [comment]
Agree that a simple copy change is enough here 🫰

**Comment by shawnborton** [comment]
Good catch and I agree with the copy change.

**Comment by joekaufmanexpensify** [comment]
Payment for the PR from this issue is being handled in: https://github.com/Expensify/App/issues/46838 , so no need to handle any payment here!

**Comment by joekaufmanexpensify** [comment]
Closing!
