### ISSUE TITLE
 Distance rate - Dollar sign moves to left after clicking/tapping it

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48833]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47850
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in
2. Navigate to any workspace and enable distance rates
3. Open Distance rate and select "+ Add rate"
4. Double click/tap the dollar sign

## Expected Result:
The dollar sign does not move

## Actual Result:
The dollar sign moves to the left and the layout gets broken

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a30d5f7a-763d-4506-90cb-f3954735ae8a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
Thanks for the proposal! We have currently reverted the PR that caused the validation, but I think you're right. I am also not sure why those changes were added. We'll probably reintroduce the change

**Comment by MonilBhavsar** [comment]
Tested and works fine!
