### ISSUE TITLE
[WAITING ON AIMANE TO ACCEPT] Android - Rules - Custom name field is not auto-focused & Text cursor is before the input in % field

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48873]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.31-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Workspace settings > Rules.
3. Enable Custom report names.
4. Tap Custom name.
5. Note that Custom name field is not auto-focused (reproducible in all environment).
6. Return to Rules.
7. Enable Auto-approve compliant reports.
8. Tap Random report audit.
9. Might need to repeat Step 8 a few times to see that the text cursor moves to the front of percentage input (Android app only).

## Expected Result:
In Step 5, Custom name field will be auto-focused.
In Step 9, the text cursor will always be at the end of the input in Percentage field.

## Actual Result:
In Step 5, Custom name field is not auto-focused.
In Step 9, the text cursor is at the beginning of the input in Percentage field.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/588be26f-d77b-4ab4-9210-2fe98d2fdc65

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833785982984566631</li>
        <li>Upwork Job ID: 1833785982984566631</li>
        <li>Last Price Increase: 2024-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 103942038</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by Julesssss** [comment]
Hi @IuliiaHerets, can I just check why this wasn't reproducible on production? Is the feature not available, or was it another reason? Thanks!

**Comment by IuliiaHerets** [comment]
Hi @Julesssss It is a new feature, so it is not available on prod, and can't check.
I recorded a video for Web to show a difference between stg and prod

https://github.com/user-attachments/assets/d44f819d-446a-4525-a8ca-eab78eed740d

**Comment by Julesssss** [comment]
That's great, thank you.

**Comment by jliexpensify** [comment]
Automation broken here, so Payment Summary

- C: @Nodebrute $250
- C+: @aimane-chnaif $250 - CHECK LIST NEEDED?

[Upwork job](https://www.upwork.com/jobs/~021833785982984566631)

**Comment by jliexpensify** [comment]
Paid and job closed. Waiting on checklist from @aimane-chnaif

**Comment by jliexpensify** [comment]
Hmm @aimane-chnaif we have you listed as using New Dot payments:

>@aimane-chnaif - Aimane Chnaif - 2024-02-29

Is this not correct?

**Comment by Julesssss** [comment]
I agree there is no need for a regression test.

**Comment by jliexpensify** [comment]
New job - https://www.upwork.com/jobs/~021840690701292361406

**Comment by jliexpensify** [comment]
Offer sent to @aimane-chnaif

**Comment by jliexpensify** [comment]
@aimane-chnaif can you accept please? I am headed OOO after tomorrow so would like to pay you before I go. Cheers.

**Comment by mallenexpensify** [comment]
@aimane-chnaif can you please accept the job and reply here once you have? @jliexpensify , I can help keep track of payment when you're OOO

**Comment by jliexpensify** [comment]
Cheers @mallenexpensify - have assigned you as well!

**Comment by mallenexpensify** [comment]
Paid again via a Bonus on the closed contract. @aimane-chnaif , can you confirm you've received payment? Thx

**Comment by mallenexpensify** [comment]
Thanks @aimane-chnaif , closing
