### ISSUE TITLE
[AWAITING PAYMENT] [$250] [OldDot Rules Migration] [Polish] - App freezes after updating Custom report name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48879]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Create a new workspace.
3. Go to Workspace settings > Rules.
4. Enable Custom report names.
5. Tap Custom name.
6. Clear the field, enter anything and save it.
7. Try to scroll through the app.

## Expected Result:
App will be responsive after updating Custom report name.

## Actual Result:
App is freezing after updating Custom report name.
On web, app is responsive, but "Custom report names" and "Prevent members from changing custom report names toggles" are no longer working after updating Custom report name.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/de960d20-f3a2-42f6-bb19-b82671614ae0

https://github.com/user-attachments/assets/fc90adf7-e694-4e97-8737-1ffa31f6c964

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843814682618579436</li>
        <li>Upwork Job ID: 1843814682618579436</li>
        <li>Last Price Increase: 2024-10-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lakchote** [comment]
Not a blocker, it's behing beta [BETA_WORKSPACE_RULES](https://github.com/Expensify/Web-Expensify/blob/main/lib/BetaManager.php#L77)

**Comment by BrtqKr** [comment]
@lakchote I've got a draft for that, but I think we should slightly adjust the logic. If someone disables the report fields, I'd probably assume that the custom names would be switched off and the nested values would be removed.  If we end up agreeing on that topic, this will probably require back-end changes, right?

**Comment by marcaaron** [comment]
>If someone disables the report fields, I'd probably assume that the custom names would be switched off and the nested values would be removed

Yes I think that was missed in the implementation, but was included in the design:

>If the user disables this option (i.e. sends enable: false) from NewDot that will reset the formula back to {report:type} {report:startdate} which we can do by modifying the policy by calling PolicyAPI::mergeReportFields() after setting shouldShowCustomReportTitleOption: false on the policy object.

I can raise a PR to get this fixed. But in the meantime I think it's also fine to not reset anything.

**Comment by marcaaron** [comment]
Just a heads up that this is going to take several days or more to prepare backend changes due to it triggering a required refactor so we should proceed with a front end solution for now.

**Comment by BrtqKr** [comment]
@marcaaron, ok then let's just do it separately https://github.com/Expensify/App/pull/48908

**Comment by marcaaron** [comment]
First part of the BE fix in Auth is done. Second half is in review.

**Comment by marcaaron** [comment]
Backend changes are done and deployed so we should be good to close this one out. 

However, @shubham1206agra is maybe still requiring payment for their review of [this PR](https://github.com/Expensify/App/pull/48908).

**Comment by garrettmknight** [comment]
@shubham1206agra you get paid for this anywhere else?

**Comment by garrettmknight** [comment]
@shubham1206agra can you accept the offer when you get a chance?

**Comment by garrettmknight** [comment]
Paid, closing
