### ISSUE TITLE
Expense - Unable to dismiss the delete modal by clicking outside the modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48875]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense.
4. Go to transaction thread.
5. Click on the report header.
6. Click Delete expense.
7. Click outside the delete modal.

## Expected Result:
User should be able to dismiss the delete modal by clicking outside the modal (production behavior).

## Actual Result:
User is unable to dismiss the delete modal by clicking outside the modal.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8e8b9df5-325f-41ad-a988-813820a1bfab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This was a regression, so no payment is needed.
