### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Chat - User is able to send message with max character limit

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4943661
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to any 1:1 conversation
2. Enter a text that is over 10k characters but less than 15K characters - You can use Lorem Ipsum generator for this
3. After the compose box displays an error that the maximum amount of characters is 10k, add attachment
4. Send the message with the attachment

## Expected Result:
User should not be able to send messages over 10k characters

## Actual Result:
User is able to send messages over 10k characters if there is added attachment.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dc0449a1-b1de-4132-8846-c38f750b9ea4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838751947628833125</li>
        <li>Upwork Job ID: 1838751947628833125</li>
        <li>Last Price Increase: 2024-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>nyomanjyotisa | Contributor | 104327662</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by IuliiaHerets** [comment]
@anmurali  I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Pujan92** [comment]
I will review this tomorrow.

**Comment by anmurali** [comment]
@Pujan92 - This still needs your review, can you pls prioritize this?

**Comment by Pujan92** [comment]
Sorry for the delay @anmurali .

@anmurali I need your help to decide what behavior we need to proceed because as suggested in proposals there are different ways to solve this error flow.

1. As @nyomanjyotisa  & @mananjadhav suggested we can disable the send button in the Attachment modal.
2. As @dominictb suggested, on click of send attachment we should display the error modal. 

Also adding an engineer for their input.

🎀👀🎀 C+ reviewed

**Comment by jasperhuangg** [comment]
@Pujan92 I think we should actually go with both @nyomanjyotisa's alternative solutions of disabling the "Add attachment" and "Send" buttons. It seems safer to disable them in both places in the UI.

**Comment by Pujan92** [comment]
### Regression Test Steps

1. Open any report
2. Enter a text with more than 10k characters
3. Once the composer shows an error of length exceeded, click the + button to add an attachment
4. Verify that the add attachment option is disabled / send button of attachment modal is disabled

**Comment by anmurali** [comment]
**Payment Summary**

- [ ] @Pujan92 approved $250 via New Dot
- [X] @nyomanjyotisa approved $250 via Upwork

**Comment by garrettmknight** [comment]
$250 approved for @Pujan92
