### ISSUE TITLE
Distance - No error when entering tax reclaimable amount larger than the distance rate

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48883]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4942190
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Track tax is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates.
3. Click on any distance rate.
4. Click Tax reclaimable on.
5. Enter amount bigger than the distance rate.

## Expected Result:
There will be an error "The reclaimable portion must be less than the distance rate amount."

## Actual Result:
There is no error when entering tax reclaimable amount larger than the distance rate.
This issue also happens when
- saving empty amount when creating distance rate
- saving empty amount when editing tax rate

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b4cf9c9c-a88e-4464-ad9b-612506bbc140

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Noiceee.

**Comment by luacmartins** [comment]
Fixed on staging. No payments due.
