### ISSUE TITLE
[HOLD for payment 2024-10-01][Search v2.1] Android & iOS - Search icon is not responsive after returning to LHN from thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48882]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to any report.
3. Send a message.
4. Send a reply to the message in thread.
5. Go to Search.
6. Go to Chats.
7. Tap on the parent message sent in Step 3.
8. Tap on the reply count to go to thread.
9. Return to LHN by swiping to right twice (iOS navigation) (if on Android, use device back navigation and not app button).
10. Tap Search.

## Expected Result:
Search icon will be responsive after returning to LHN from thread when opened from Search.

## Actual Result:
Search icon is not responsive after returning to LHN from thread when opened from Search.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2dc807ef-d0cf-4df7-adca-0fddcd496195

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by pecanoro** [comment]
I managed to reproduce it. As opposed to any main chats that return to the search view when swiping right, a thread will go back to the LHN, maybe that's the issue here.

**Comment by pecanoro** [comment]
Most likely coming from https://github.com/Expensify/App/pull/47690

**Comment by pecanoro** [comment]
Sure, feel free to do so since you have more context!

**Comment by luacmartins** [comment]
@sakluger just missing PR review payment to C+

**Comment by sakluger** [comment]
@luacmartins thanks for the bump.

@ishpaul777 please let me know once you've accepted the offer: https://www.upwork.com/nx/wm/offer/104347535

**Comment by sakluger** [comment]
The contract was accepted and I paid it out. We're all done here.
