### ISSUE TITLE
Workspace – Able to remove an approver from the workspace members in Gmail account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48886]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4943289
**Email or phone of affected tester (no customers):** ponikarchuks+119924@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as Gmail account
3. Create a workspace
4. Add user X as workspace members with admin role
5. Enable Workflow and add user X as Approver
6. Navigate to workspace members and click on user X
7. Remove user X from workspace members

## Expected Result:
Unable to remove an approver from the workspace members, error appears

## Actual Result:
Approver is removed from the workspace members

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3b14760f-2982-48eb-b5ad-3b9100ceb067

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by arosiclair** [comment]
This isn't a bug. It's explained in the dialog:

![image](https://github.com/user-attachments/assets/2dde73f0-0ec8-44ed-bedb-0ddf3df85470)

The behavior on production (blocking removal of the approval) was the real bug and it looks like it's fixed. Closing this out.
