### ISSUE TITLE
Desktop - Chat - The attached picture blinks a few times after coming online

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48891]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4940615&group_by=cases:section_id&group_id=292107&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with any account
3. Navigate to any 1:1 chat
4. Go offline
5. Send an image attachment
6. Go online

## Expected Result:
It shouldn't blink.

## Actual Result:
The attached picture blinks a few times after coming online.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a3c89b1d-220f-44fa-a485-4205a56c99ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Adding to my test list and will get to it later this week.

**Comment by alexpensify** [comment]
No update yet

**Comment by alexpensify** [comment]
Other GHs have been a priority; I'll review them soon.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
I've been sick this week and haven't been able to review this GitHub. There is no major update here; I'll try to carry on next week.

**Comment by alexpensify** [comment]
It's not overdue; I'm still catching up from being sick at the end of last week.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
I'll get to this one soon.

**Comment by alexpensify** [comment]
Closing - I was unable to replicate the experience and didn't get a triple blink or any blink when I came back online 

![2024-10-11_16-26-32](https://github.com/user-attachments/assets/85068544-5fc2-4b1f-9da5-a0caa15e64e3)
