### ISSUE TITLE
[HOLD for payment 2024-10-31][$250] Rules - After disabling all workflow features and opening rules, page keep loading

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48894]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47468
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go to profile icon - workspace-- new workspace
3. Tap more features-- enable workflows
4. Disable all workflow features
5. Tap more features -- enable rules
6. Tap rules

## Expected Result:
After disabling all workflow features and opening rules, page must not load and it must display content.

## Actual Result:
After disabling all workflow features and opening rules, page keep loading.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d8c7a8ae-dc92-4d56-adef-ea87d5cb9aa7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833585257948581733</li>
        <li>Upwork Job ID: 1833585257948581733</li>
        <li>Last Price Increase: 2024-09-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by luacmartins** [comment]
@Nodebrute you're proposal looks good. Are you available to work on a PR now?

**Comment by luacmartins** [comment]
Great. All yours

**Comment by luacmartins** [comment]
This is fixed in staging

**Comment by luacmartins** [comment]
Bump @strepanier03

**Comment by strepanier03** [comment]
Been ooo since Thursday until today, handling now.

**Comment by strepanier03** [comment]
@Nodebrute - I sent you an offer in Upwork. I'll pay it once I see it's accepted.

**Comment by strepanier03** [comment]
@Nodebrute do we need a reg test for this?
