### ISSUE TITLE
[Workspace Feeds] unable to change card limit to $0

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48904]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Y
**Email or phone of affected tester (no customers):**

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1725978148730949

## Action Performed:

1. Add account to workspaceFeeds beta
2. Sign in with test account
3. Select Manage my team’s expenses
4. Enter any business name / personal name
5. Navigate to the workspace editor of the newly created workspace
6. Navigate to `More features` tab
7. Toggle on the feature
8. Navigate to the `Expensify Card` page
9. Select `Issue new card`
10. Follow the steps for an OPEN bank account (option 3) of this [SO](https://stackoverflowteams.com/c/expensify/questions/342), and exit the onboarding flow at the requestor information section
Select `Finish setup` and continue through the VBBA flow
Finish the setup process
11. Issue an Expensify Card with >$0 limit
12. Select the newly issued card in the cards list
13. Change the limit  to $0

## Expected Result:
See a modal with the following copy:

> Header: “change card limit”
> Body: “If you change this card’s limit to $[new limit], new transactions will be declined until next month.”
> Buttons: “Change limit” and “Cancel”

## Actual Result:
Unable to change to $0

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/273d2e0e-9266-4314-9511-3a6aa936680f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment]
CC @mountiny

**Comment by mountiny** [comment]
@allgandalf will handle the PR for this as they work as dedicated C+ for this feature project

**Comment by mountiny** [comment]
@cretadn22 agreed with @allgandalf sorry for this but it is part of an ongoing project and we pay for the entire project there, the issues were not marked as external and the project team was supposed to handle it
