### ISSUE TITLE
[Workspace Feeds] extra digit shown on card limit

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48905]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Y
**Email or phone of affected tester (no customers):**

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1725978148730949

## Action Performed:

1. Add account to workspaceFeeds beta
2. Sign in with test account
3. Select Manage my team’s expenses
4. Enter any business name / personal name
5. Navigate to the workspace editor of the newly created workspace
6. Navigate to `More features` tab
7. Toggle on the feature
8. Navigate to the `Expensify Card` page
9. Select `Issue new card`, give the user a $2 limit
10. Follow the steps for an OPEN bank account (option 3) of this [SO](https://stackoverflowteams.com/c/expensify/questions/342)
11. Finish the setup process
12. Navigate to members page
13. Select the member that was assigned a card

## Expected Result:
Limit badge should be `$2.00`

## Actual Result:
Limit badge is `$2.000`

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/a3e8270c-f56c-4710-b444-549e32e334be)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment]
@allgandalf will handle the PR for this as they work as dedicated C+ for this feature project

**Comment by mountiny** [comment]
PR Merged
