### ISSUE TITLE
[Search v2.2] -Message that previously had link remains in Links after removing link from the message

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48910]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-14
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Send a message with link.
4. Go to Search > Chats.
5. Go to Links.
6. Click on the message sent in Step 3.
7. Edit the message, remove the link and save it.
8. Refresh Links page.

## Expected Result:
The edited message should be removed from Links since the message no longer contains link.

## Actual Result:
The edited message is not removed from Links after removing link from the message.
Also, the (edited) label disappears from the edited message in Links tab.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/03e91edf-ded0-493c-ac17-5471795ca408

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment]
I think we can demote this one. It might actually be a backend issue if the Search API is still returning the result.

**Comment by luacmartins** [comment]
cc @shubham1206agra

**Comment by joekaufmanexpensify** [comment]
Reproduced! Adding internal label for now based on @luacmartins comment above

**Comment by joekaufmanexpensify** [comment]
I think still pending internal prioritization

**Comment by luacmartins** [comment]
I got a draft PR up. Still have to look into one more edge case and add tests

**Comment by joekaufmanexpensify** [comment]
Auth PR was deployed to prod last night. Closing!
