### ISSUE TITLE
[CRITICAL] QA - Add Travel test to TestRail

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48921]
# Problem

We have a sandbox environment we can point accounts to in order to test travel booking ([SO](https://stackoverflowteams.com/c/expensify/questions/19798)), but we've had issues getting all of the data from these transactions. That is a pretty broad statement though, and if we don't use the sandbox environment we pay a $15 fee every test booking we make in production. 

# Solution

- [x] Figure out what exactly is going wrong with sandbox and what data we are missing. Is this a Spotnana issue or is it on us?
- [x] Depending on the above, let's fix the issue ourselves or come up with clear asks for spotnana
- [x] Add a test script to testrail for applause, so we're QAing travel booking consistently and confirming it is working well end to end. 
- [x] Create a SO for internal testing of travel

# Tests:
In OldDot Expensify: Provisioning a company, account, and company
1. Create a new account
2. Create a control workspace
3. Open the console: Command + option + j
4. Paste NVP.set('travelSettings', {'testAccount': true});
5. Go to Settings -> Account
6. Set a first and last name
7. Go to Travel in the LHN
8. Click the button
9. Check the checkbox
10. Enter an address
11. Click confirm and wait
12. Ensure you are brought to Spotnana

Inside of Spotnana:
1. Search for a new flight
2. One way from SEA to SFO
3. Alaska airlines
4. At least 1 month in the future
5. Select the flight
6. Make sure that your name was properly imported from Expensify in the "Traveler Details"
7. Add the other required information and click save at the top of the panel
8. Click "next" on the right side
9. Click "select a trip" and create a new trip
10. Add the [stripe test card](https://docs.stripe.com/testing) ending in 4444
11. Book the trip
12. Wait until you receive an email confirming your trip
13. Back inside of Expensify:

Check in the Expenses tab and make sure there are 2 expenses
1. One for $15
2. One for the price of your flight
3. Ensure there is a receipt attached to both expenses

---------

Testing changing your default workspace:
1. Create a new account on the beta
2. Create a control workspace1
3. Enable the workspace for travel and make sure you are logged into Spotnana
4. Create a second control workspace2 (a different name is required)
5. Enable the workspace for travel and make sure you are logged into Spotnana
6. Switch your default workspace to workspace1
7. Click the travel button and make sure you are logged into Spotnana

**Comment by stitesExpensify** [comment]
Added some logs today to see if my hunch is correct. Based on [these logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228c10fff70b04ef6b-PDX%22)+AND+timestamp:[2024-09-10T16:04:54.933Z+TO+2024-09-10T18:04:54.933Z]&index=logs_expensify-030207) it looks like we were sent the event, but when trying to get the user's info we got `user_not_found`. This to me indicates that we are trying to find the user on the production spotnana server instead of the sandbox

**Comment by stitesExpensify** [comment]
I ended up finding the problem before the logs were deployed! I CP'd it and we are not getting fares via the sandbox again. We are still not getting fees for some reason. My guess is because the amount is $0 on the sandbox?

**Comment by stitesExpensify** [comment]
Posted here to find out why we aren't getting fees https://expensify.slack.com/archives/C066REXJ9D3/p1726171051522029

**Comment by stitesExpensify** [comment]
Waiting for Spotnana to respond here https://expensify.slack.com/archives/C066REXJ9D3/p1726171051522029

**Comment by stitesExpensify** [comment]
Waiting on a response, will bring it up in our meeting today

**Comment by stitesExpensify** [comment]
We're good! We can start testing the non-credit card case in staging now!

**Comment by stitesExpensify** [comment]
Writing a SO / testrail tomorrow morning

**Comment by stitesExpensify** [comment]
In OldDot Expensify: Provisioning a company, account, and company
1. Create a new account
2. Create a control workspace
3. Log in on OldDot
4. Open the console: Command + option + j
5. Paste NVP.set('travelSettings', {'testAccount': true});
6. Go to Settings -> Account
7. Set a first and last name
8. Go to Travel in the LHN
9. Click the button
10. Check the checkbox
11. Enter an address
12. Click confirm and wait
13. Ensure you are brought to Spotnana

Inside of Spotnana:
1. Search for a new flight
    - One way from SEA to SFO
    - Alaska airlines
    - At least 1 month in the future
2. Select the flight
3. Make sure that your name was properly imported from Expensify in the "Traveler Details"
4. Add the other required information and click save at the top of the panel
5. Click "next" on the right side
6. Click "select a trip" and create a new trip
7. Add the [stripe test card](https://docs.stripe.com/testing) ending in 4444
8. Book the trip
9. Wait until you receive an email confirming your trip

Back inside of Expensify:
1. Check in the Expenses tab and make sure there are 2 expenses
    - One for $15
    - One for the price of your flight
    - Ensure there is a receipt attached to both expenses

**Comment by stitesExpensify** [comment]
SO is here https://stackoverflowteams.com/c/expensify/questions/20166/20167#20167

**Comment by isagoico** [comment]
Will get these added this week (will aim for tomorrow so it's tested in the next regression run.

**Comment by stitesExpensify** [comment]
Awesome, thanks!

**Comment by isagoico** [comment]
@stitesExpensify The following Test Cases have been created in the OldDot regression suite: 
- [User is able to book a flight in Expensify Travel](https://expensify.testrail.io/index.php?/cases/view/3284908)
- [User is able to navigate to travel.expensify.com after changing the WS](https://expensify.testrail.io/index.php?/cases/view/3284909)

All travel test cases for OD can be found on this [folder](https://expensify.testrail.io/index.php?/suites/view/7723&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=314226). 
![image](https://github.com/user-attachments/assets/c3ee94a2-202e-4a14-990c-f68f77cd4c08)

Will leave this issue open for a review of the TCs to have a 👍 that everything is good.

**Comment by stitesExpensify** [comment]
LGTM!
