### ISSUE TITLE
Android - Profile - Unable to select any listed year when prompted with search results

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48926]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4942630&group_by=cases:section_id&group_order=asc&group_id=229064
**Email or phone of affected tester (no customers):** applausetester+omqq379@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open app
2. Tap on Profile icon
3. Tap on Profile
4. Scroll down and select Date of birth
5. Tap on Year selector
6. Write search prompt e.g. "197"
7. Select any listed year

## Expected Result:
Unable to select a year from the list displayed in the search results

## Actual Result:
Nothing happens; the user remains on the search results page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6463310a-a1a9-48e1-b873-a251a0754cb5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by 289Adam289** [comment]
I also cannot  reproduce

**Comment by kadiealexander** [comment]
Swapping with @jliexpensify for our android <> ios bug swap.
