### ISSUE TITLE
Chat - Typing :finger_heart does not show up any emoji

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48934]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48748
**Email or phone of affected tester (no customers):** gatantm+96@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to any chat
2. Type :finger_heart

## Expected Result:
The 🫰 emoji shows up

## Actual Result:
No emoji shows up when typing :finger_heart

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c2f6b947-6343-41c8-bbdd-77af785489ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment]
https://emojipedia.org/hand-with-index-finger-and-thumb-crossed#technical

:hand_with_index_finger_and_thumb_crossed:
`:hand_with_index_finger_and_thumb_crossed:`

<img width="508" alt="image" src="https://github.com/user-attachments/assets/43d395e3-45a2-4627-aeb6-9b030ce0d50d">

**Comment by greg-schroeder** [comment]
Closing this after discussion with the team, as it's not a priority
