### ISSUE TITLE
[HOLD for payment 2024-10-25] [HOLD for payment 2024-10-24] [$250] Workspace - Admin is unable to click on the member to view member profile in workspace chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48931]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [Admin] Invite employee to workspace.
3. [Admin & employee] Go to workspace chat.
4. [Admin & employee] Click on the room header > Members.
5. [Admin & employee] Click on the room members.

## Expected Result:
Both admin and employee should be able to click on the member to view the profile.

## Actual Result:
Only employee is able to click on the member to view the profile, whereas admin is blocked from viewing the profile.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e86ec869-2c68-4db7-aae6-d13fc557af18

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835655904461898964</li>
        <li>Upwork Job ID: 1835655904461898964</li>
        <li>Last Price Increase: 2024-09-30</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 104233105</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by IuliiaHerets** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
have you managed to review thiss yet @eVoloshchak

**Comment by eVoloshchak** [comment]
Both proposals are similar (which is expected since we're making use of an already existing approach), so we can proceed with the first proposal. @nyomanjyotisa's [proposal](https://github.com/Expensify/App/issues/48931#issuecomment-2342358963) looks good to me!

🎀👀🎀 C+ reviewed!

**Comment by zanyrenney** [comment]
Hey @eVoloshchak please review the thoughts above?

Just an FYI I'll be OOO until Tuesday 1st, please reapply the bug label if this needs urgent action in my absence. Otherwise I will get to it when I return. Thanks!

**Comment by zanyrenney** [comment]
Bump @eVoloshchak please can you prioritise the review of the proposals?

We need to keep up progress here. If you don't think this is a real bug or are concerned about the value, feel free to chime in and add your thoughts, otherwise I will assume we are progressing here.

**Comment by eVoloshchak** [comment]
> I saw the selected solution causes the regression: Click on "Select all" will select the disable options. Could you help confirm?

Just verified this is correct, the proposed solution allows you to select (and remove) the admin of the workspace, which is incorrect behavior. 
Thanks for catching that @dominictb 
Let's proceed with @dominictb's [solution](https://github.com/Expensify/App/issues/48931#issuecomment-2342615137), apologies for the confusion 

🎀👀🎀 C+ reviewed!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment]
**payment summary**

@eVoloshchak requires payment through NewDot Manual Requests - please request $250 via NewDot.
@dominictb requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104233105) (Contributor)

I have DM's @eVoloshchak to ask them to complete the list above.

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: I'm unable to pinpoint the exact PR that has caused this, looks like it's a limitation of the original implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a minor edge case, additional discussion is not necessary

**Regression Test Proposal**

1. [Admin of the workspace] Go to workspace room
2. Press room header >> Members
3. Invite several members to the room
4. Press on the member item in the members list
5. Verify member details page opens

**Do we agree 👍 or 👎**

**Comment by tgolen** [comment]
Reopening so @zanyrenney can complete the checklist and fill it out with the answers from @eVoloshchak.

I think the regression test makes sense and would be valuable to have. As an alternative, could an automated test be created for that?

**Comment by JmillsExpensify** [comment]
$250 approved for @eVoloshchak
