### ISSUE TITLE
[$250] Desktop - Onboarding - Modal doesn't open in desktop when navigating to incorrect URL

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48937]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.31-12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48137
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: use gmail NEW account.

1. Desktop: Sign in as a new user > Join (Do not proceed onboarding flow)
2. Web: Sign in with the same user > refresh the page (to see onboarding modal)
3. Desktop: Select 'Manage my team's expenses'
4. Web: Change the URL to a random URL after .com, for example, /aaa (for desktop, enter the URL in the browser and press Enter).
5. Web: choose 'Open New Expensify' in popup

## Expected Result:
Desktop: the onboarding modal work page is displayed.

## Actual Result:
Desktop: page not found is displayed

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/865730a0-93a0-4803-89c6-e93dc8f4a573

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836423410149372393</li>
        <li>Upwork Job ID: 1836423410149372393</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by IuliiaHerets** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
I think this is low priority, though I'll open it up to the community.

**Comment by mollfpr** [comment]
@JmillsExpensify Since this issue from @tsa321 PR: https://github.com/Expensify/App/pull/48137, should we let them fix this?

**Comment by JmillsExpensify** [comment]
Nice, closing.
