### ISSUE TITLE
Chat - On changing skin tone 6th time, emoji reduced to one

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48945]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a chat
3. Tap on emoticon plus reaction button( send a message & long press and react for the message so that you can see this button in conversation)
4. Now select thumbs up emoji
5. Change the skin tone
6. Now select thumbs up emoji in new skin tone
7. Repeat this and select thumbs up emoji in all 6 skin tone
8. Note in conversation we can see all 5 skin tone thumbs up emoji but on adding 6th skin tone it reduced to one emoji

## Expected Result:
On changing skin tone 6th time, emoji must not be reduced to one.

## Actual Result:
On changing skin tone 6th time, emoji reduced to one. 6th skin tone also unused one. It is not used 2nd time but reduced to one emoji.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e8f14691-8bea-4c38-a44d-b553c6a94bc6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by garrettmknight** [comment]
I don't think this is worth fixing.
