### ISSUE TITLE
[$250] [HOLD for Payment 2024-09-21][Search v1] Broken tracked expenses

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#48942]
### Problem
Coming from [here](https://expensify.slack.com/archives/C041MSTR8J1/p1725988882579449), users are not able to open a tracked expense on Search

### Solution
Tracked expenses have reportID=0 and we're trying to redirect users to that reportID. We should instead use the transactionThreadReportID in that case
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836407836032402528</li>
        <li>Upwork Job ID: 1836407836032402528</li>
        <li>Last Price Increase: 2024-09-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by miljakljajic** [comment]
@luacmartins @rayane-djouah whats the amount owed for this one?

**Comment by miljakljajic** [comment]
Thank you @rayane-djouah - I sent you an offer on upwork. Accept it and I'll get you paid by Friday 20th

**Comment by miljakljajic** [comment]
Paid! Closing this out.

If anything else comes up, please assign a new BZ member. I am going on extended leave.
