### ISSUE TITLE
[$250] [Search v2.2] Chat search shows messages in rooms that you have viewed, but not joined

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48947]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-20
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726001109540449

## Action Performed:

1. With account A create a workspace-visibility room (e.g. #test-room)
2. With account B, that is also a workspace member, view the room but don't join it
3. With account B, navigate somewhere else in the app
4. With account A post in #test-room
5. With account B, go to the chats/unreads page in Search

## Expected Result:
No unread message displayed in LHN
## Actual Result:
The unread message displayed there, even though you aren't a member of the room 
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/02aa31f9-461d-4805-9fb1-761c8233812e

![Snip - New Expensify - Google Chrome](https://github.com/user-attachments/assets/5163b8cb-5a3e-4808-a234-bcca8cdbb120)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833656418639037038</li>
        <li>Upwork Job ID: 1833656418639037038</li>
        <li>Last Price Increase: 2024-09-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by trjExpensify** [comment]
Yep, can repro: 

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/d05e77e3-b649-421a-b336-8795e4100c44">

**Comment by trjExpensify** [comment]
CC: @luacmartins for vis!

**Comment by luacmartins** [comment]
This is backend work.

**Comment by trjExpensify** [comment]
Ah cool, thanks!

**Comment by luacmartins** [comment]
PR in review

**Comment by luacmartins** [comment]
This is done. All internal work, so we're good to close
