### ISSUE TITLE
[Workspace Feeds] Double header on the Expensify Card

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#48944]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

1. Add account to workspaceFeeds beta
2. Sign in with test account
3. Select Manage my team’s expenses
4. Enter any business name / personal name
5. Navigate to the workspace editor of the newly created workspace
6. Navigate to More features tab
7. Toggle on the feature
8. Navigate to the Expensify Card page
9. Select Issue new card, give the user a $2 limit
10. Follow the steps for an OPEN bank account (option 3) of this [SO](https://stackoverflowteams.com/c/expensify/questions/342)
11. Finish the setup process
12. Issue a card
13. Navigate back to the Expensify Card page

## Expected Result:
Only see one `Expensify Card` header.

## Actual Result:
Two `Expensify Card` headers are shown. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/e77ef429-9ae0-4989-bb0b-7de13c1deec8)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by VickyStash** [comment]
Hey, I'm Viktoryia from Callstack, I've been working on this [page](https://github.com/Expensify/App/issues/44310), so I can take a look.
