### ISSUE TITLE
[HOLD for payment 2024-10-31][$250][Search v2.1] - In `to` field, selecting & unselecting contact, avatars of user in drop-down list flickers

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48946]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-14
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap on a workspace chat
3. Submit an expense
4. Navigate to LHN and tap search at bottom
5. Tap filter
6. Scroll down to tap "to" field
7. Select and unselect the first contact

## Expected Result:
In search to field, selecting and unselecting contact, avatars of user in drop-down list must not flicker.

## Actual Result:
In search to field, selecting and unselecting contact, avatars of user in drop-down list flickers.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/936401ab-50f2-4ac9-89e1-ef313a096c41

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by 289Adam289** [comment]
Hi! I'm from SWM and I would like to work on this issue.

**Comment by sakluger** [comment]
Hey @dukenv0307, sorry for the delay. Here's a payment summary with a link to the Upwork offer.

Summarizing payment on this issue:

Contributor+: @dukenv0307 $250, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/104686780

**Comment by sakluger** [comment]
All paid, thanks!
