### ISSUE TITLE
[PAID] [$250] Disable NFC on `onfido` `react-native-sdk`

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#48950]
## Problem

The Apple developer team who reviews our iOS application commonly rejects our New Expensify app because they ask for a video of how the New Expensify app uses NFC. We know that this NFC support comes from the `onfido` `react-native-sdk` [per their documentation](https://github.com/onfido/react-native-sdk?tab=readme-ov-file#nfc-capture-using-onfido-studio). However, we do not currently use the passport NFC scanning.

## Solution

Remove the NFC support as described here: https://github.com/onfido/react-native-sdk?tab=readme-ov-file#disabling-nfc-and-excluding-dependencies

Also make sure to remove the dependencies as mentioned in the documentation to prevent future iOS app rejections.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836544665597870593</li>
        <li>Upwork Job ID: 1836544665597870593</li>
        <li>Last Price Increase: 2024-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104028950</li>
<li>cretadn22 | Contributor | 104028951</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by rafecolton** [comment]
@cretadn22 can you please clarify a couple things about your proposal:
1. You mentioned two options - use the `disableNFC` parameter or upgrade the library and use the new parameter. Which of the two are you proposing?
2. Regarding removing the android dependencies...
    a. Is it necessary to patch the library or is there some other way to configure those to be excluded?
    b. Do we actually need to exclude them since the issue here concerns iOS?

**Comment by rafecolton** [comment]
1 sounds good 👍 @AndrewGable what do you think about doing a patch to exclude the nfc dependencies on android? It's not necessary to solve the problem in the OP but I assume it will make the android build a little smaller and/or faster. Seems overkill to me to maintain a fork for this, since the change would never get merged.

**Comment by AndrewGable** [comment]
Why do we need to patch? I assumed these changes were made to our own `build.gradle` and not a patch to the library?

**Comment by rafecolton** [comment]
Great question! I don't know much about grade builds. I tried searching the App code for "com.onfido.sdk.capture" and the only instance I found was in `patches/@onfido+react-native-sdk+10.6.0.patch` so it looks like we already patch the library's `android/bin/build.gradle` file. I don't see any explicit inclusion in that file or our patch of the dependencies they're saying to remove. 

So I think that means we can add that block to our own build file as you're suggesting, but I'm not sure. If that sounds right to you, would it get added to `android/app/build.gradle` or `android/build.gradle`? I'm guessing the former based on the comments in the file.

**Comment by AndrewGable** [comment]
Yes I would assume it would be changed in [`android/app/build.gradle`](https://github.com/Expensify/App/blob/main/android/app/build.gradle), but wanted to confirm with the contributor and C+ that this was the planned on solution.

**Comment by AndrewGable** [comment]
> I don't think we can proceed with that approach. 

Why not?

**Comment by rafecolton** [comment]
Not overdue Melvin, we are discussing

**Comment by rafecolton** [comment]
Nice, even better! So we can skip that part of the proposal entirely. @cretadn22 assigning you to implement the `disableNFC` parameter.

**Comment by AndrewGable** [comment]
I'm not sure I agree with that explanation.. Documentation states: 

> For Android, a range of NFC library dependencies are included in the build automatically. In addition to configuring the `nfcOption` parameter, you must remove any libraries from the build process.

So let's double check this on Android please.

**Comment by rafecolton** [comment]
I asked ChatGPT how to determine what packages were included in a build, and here's what it said - @AndrewGable does this sound right? Agree we should check. Will do before merging the PR. 

> To see which packages were included in an Android app build, you can decompile the APK file and inspect its contents. Here's how you can do this:
> 
> ### Using APKTool and JADX
> 1. **Download and Install APKTool and JADX:**
>    - **APKTool:** It helps decode APK resources to nearly their original form and rebuild them after making modifications.
>    - **JADX:** It decompiles the APK and translates it back into Java code.
> 
> 2. **Decompile the APK with APKTool:**
>    - First, make sure you have Java installed since both tools require it.
>    - Place your APK file in a directory where you can easily access it from the terminal or command prompt.
>    - Download APKTool from [the official APKTool website](https://ibotpeaches.github.io/Apktool/).
>    - Open your command-line tool and navigate to the folder containing APKTool and your APK file.
>    - Run the following command to decompile the APK:
>      ```shell
>      apktool d yourapp.apk
>      ```
>    - This will generate a directory with the decompiled resources.
> 
> 3. **Inspect Package Info:**
>    - Navigate to the generated directory and look for files like `AndroidManifest.xml`, which lists the packages used.
>    - Additionally, inspect the `res` folder and the `smali` directory, which contains human-readable disassembled code.
> 
> 4. **Decompile to Java with JADX:**
>    - Download JADX from [the official JADX GitHub repository](https://github.com/skylot/jadx).
>    - Use the JADX GUI or command line to open the APK:
>      ```shell
>      jadx-gui yourapp.apk
>      ```
>    - Navigate through the decompiled Java code to see all the included packages.
>    - You can look under directories that represent the package names.
> 
> ### Using an Online APK Analyzer
> Alternatively, you can use online tools like **'APK Analyzer'** to inspect the APK's content without the need to decompile it locally. These tools provide information about the included packages.
> 
> ### Manual Inspection with Android Studio
> 1. **Open Android Studio:**
>    - Go to **File > Profile or Debug APK**, then select your APK file.
> 2. **APK Analyzer:**
>    - After the APK is loaded, use the built-in APK Analyzer to browse the APK’s structure, including packages, resources, and DEX files.
>    - The APK Analyzer will provide a visual breakdown of the APK’s contents.
> 
> ### Examine Dependencies in Build Files
> If you have access to the source code, you can also check the dependencies listed in the `build.gradle` files to see the packages that were included in the build process.
> 
> By using one or more of these methods, you should be able to identify the packages that were included in your Android app build.

**Comment by rafecolton** [comment]
Not sure why the upwork automation isn't working 🤔

**Comment by AndrewGable** [comment]
Ah nice find @cretadn22! 👍

**Comment by rafecolton** [comment]
@strepanier03, making you issue owner now since the PR is merged

**Comment by strepanier03** [comment]
Working on this now that I'm back from OoO and more caught up.

**Comment by strepanier03** [comment]
Okay, all contracts paid and closed. Thanks everyone!
