### ISSUE TITLE
Copilot - No message is shown when trying to add the owner as copilot

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48967]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+ds@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to an Expensifail account
2. Go to settings > security > add Copilot
3. Write the email you used to login

## Expected Result:
You can not add your own email as a Copilot message is shown

## Actual Result:
No message is shown when trying to add the owner as copilot

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/57e71ffe-6fd4-4aa6-a0ed-03218a568d86

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rushatgabhane** [comment]
@youssef-lr @joekaufmanexpensify not a blocker.

this is behind a beta. kindly assign me because I'm working on copilot project

**Comment by joekaufmanexpensify** [comment]
Sounds good! LMK if there's anything I can do to help.

**Comment by joekaufmanexpensify** [comment]
@rushatgabhane correct me if I'm wrong here but I don't think we need to hire anyone for this issue, is that right?

**Comment by dangrous** [comment]
correct, this will be handled as part of the copilot project by @rushatgabhane

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY!

**Comment by joekaufmanexpensify** [comment]
@rushatgabhane is there an ETA for a PR here?

**Comment by joekaufmanexpensify** [comment]
PR in review
