### ISSUE TITLE
Expense - Green checkmark is shown on the right end of Amount row and not next to Amount

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48969]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  Exp https://expensify.testrail.io/index.php?/tests/view/4945103
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit an expense to User B.
3. [User B] Pay the expense.
4. [User A & User B] Go to the transaction thread.

## Expected Result:
Green checkmark will be shown next to the paid amount in the transaction thread (production behavior).

## Actual Result:
Green checkmark is shown on the right end of Amount row in the transaction thread.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/02880d60-f598-4499-9602-661c4db632aa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Guccio163** [comment]
Great, I moved `flex: 1` directly to Advanced Filters file, is this the result that satisfies us @rayane-djouah?

<img width="323" alt="Screenshot 2024-09-11 at 13 07 09" src="https://github.com/user-attachments/assets/6a6f3745-36b9-4264-af89-5bfd6c0bc0e6">

**Comment by Guccio163** [comment]
PR above solves this issue once it's merged, because it reverts previous interference on MenuItem and hence this section, result is right:

https://github.com/user-attachments/assets/006e6151-7b87-4bad-9bc6-41ba4d7b065a

**Comment by Guccio163** [comment]
PR is merged, this issue can be closed
