### ISSUE TITLE
Copilot - Account avatar is missing after switching account on Security page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48966]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47353
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has added a copilot.

1. Go to staging.new.expensify.com
2. Go to Account settings > Security.
3. Click on the account switcher.
4. Switch to another acccount.
5. After everything loads, switcher to the original account while staying on Security page.
6. Scroll down the Security page.

## Expected Result:
The account under "You can access these accounts via the account switcher:" should have an avatar.

## Actual Result:
The account under "You can access these accounts via the account switcher:" does not have an avatar when switching account on Security page, even after everything is loaded.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7ed49d4b-d605-4a45-8687-eca0e6da6bd8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @nkuoch</details>

**Comment by rushatgabhane** [comment]
not a blocker. behind copilot beta

**Comment by rushatgabhane** [comment]
@nkuoch @stephanieelliott kindly assign it to me because I'm working on copilot project

**Comment by dangrous** [comment]
@rushatgabhane will be fixing soon!

**Comment by stephanieelliott** [comment]
This is being actively worked on within the PR!

**Comment by nkuoch** [comment]
This is being actively worked on within the PR!
