### ISSUE TITLE
Login - Many "get started here" messages shown after login

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48960]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in to an existing account

## Expected Result:
No get started message is shown

## Actual Result:
Many "get started here" messages shown after login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1439" alt="Bug6599447_1726019837132!Screenshot_2024-09-11_at_4 56 58_at_night" src="https://github.com/user-attachments/assets/8a52572e-c0bc-4453-8327-9752ce193bcf">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by flodnv** [comment]
Thanks @tienifr

**Comment by Julesssss** [comment]
CP'd, build in progress

**Comment by trjExpensify** [comment]
Ahh, nice. I was going to raise this one this morning after some late night testing yesterday:

![image](https://github.com/user-attachments/assets/30d01952-5314-4cec-8b17-269483fbf4a4)

...but I couldn't reproduce it just now coz' we've CP'd a fix. Thanks! 😅

**Comment by Julesssss** [comment]
Mirroring the comment [here](https://github.com/Expensify/App/pull/48963#issuecomment-2343248453) on the PR for visibility:

CP was successful, though the 'Post a Github comment' step failed due to an infinite loop.

@flodnv please verify the fix on staging `9.0.32-1` and then check it off the checklist, thanks.

**Comment by flodnv** [comment]
Why me? We usually ask #qa. I will ask them.

**Comment by kavimuru** [comment]
Not repro with existing account.

https://github.com/user-attachments/assets/e8406d5d-e62a-4cee-93f3-38f73f69f275

**Comment by flodnv** [comment]
Cool, this is resolved, thanks @tienifr
