### ISSUE TITLE
Copilot - Incorrect magic code error is not dismissed after returning to previous step

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Security.
3. Click Add copilot.
4. Select a user.
5. Select an access level.
6. On confirmation page, click Add copilot.
7. Enter incorrect magic code.
8. Return to previous page.
9. Go back to magic code page.

## Expected Result:
Incorrect magic code error message should be dismissed when returning to the previous step.

## Actual Result:
Incorrect magic code error message is not dismissed when returning to the previous step and going back to magic code page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fe7f674e-e95c-4db4-a48f-b92acb7f2401

/details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment]
I think this is still under beta. @rushatgabhane do you want me to assign this one to you?

**Comment by rushatgabhane** [comment]
yes please. I didn't know this was the expected result

**Comment by kadiealexander** [comment]
@rushatgabhane are you just C+ or will you be submitting a PR?

**Comment by rushatgabhane** [comment]
hey i am raising a PR

**Comment by rushatgabhane** [comment]
@dangrous do you think we should fix this? This is a server error and it should be dismissed only if the user dismisses it, right? And not by pressing back button

**Comment by rushatgabhane** [comment]
It stays on other pages too! eg: contact method

<img width="399" alt="image" src="https://github.com/user-attachments/assets/96ecd5ab-ad85-491e-9202-0f5a70a7d5aa">

**Comment by dangrous** [comment]
Okay yeah in that case I think we can close this - let us know if you disagree @kadiealexander !
