### ISSUE TITLE
[HOLD for payment 2024-10-04] [$250] [Workspace Feeds] There's no checkmark next to the current settlement account being used.

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#48974]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.31-24
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1725977031984379 

## Action Performed:
1. Enable the Expensify Card
2. Click `Settings` at the top of the Expensify Card page
3. Click `Settlement account`

## Expected Result:
The bank account being used should be highlighted with a checkmark

![image (18)](https://github.com/user-attachments/assets/6afeae49-89ff-4503-a8c8-aaefa343e96f)

## Actual Result:
There's no checkmark against the bank account being used for settlements. 

![image (19)](https://github.com/user-attachments/assets/ebae4339-8df6-49c5-84c2-e37a6aa9e3b9)

Note: We also want to make sure we refactor the `Wallet` > `Transfer Balance` screen to use this same select list styling, as right now it has radio buttons, so let's make it consistent:

![CleanShot 2024-09-10 at 16 25 20@2x](https://github.com/user-attachments/assets/f503d47a-8785-442f-9ae9-cc675059a2ea)

## Workaround:
N/A, visual design bug. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

See above in-line. 

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836004132424001151</li>
        <li>Upwork Job ID: 1836004132424001151</li>
        <li>Last Price Increase: 2024-09-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Someone on the Workspace Feeds team will take this, looking for who's available.

**Comment by koko57** [comment]
I can work on this issue

**Comment by trjExpensify** [comment]
Thanks!

**Comment by koko57** [comment]
With the non-checked bank account problem - same root cause as in https://github.com/Expensify/App/issues/48943#issuecomment-2342944254 - we don't have bankAccountID in the accountData object - after `OpenPaymentsPage` we have this data so the bank account is properly checked. 

 I will do similar fix Vicky is doing here https://github.com/Expensify/App/pull/48984 and I will update the design. @trjExpensify  just to make sure: we're talking of changing the Wallet > Transfer Balance page to use the same design as Settlement Account page (not the way around?) - list items instead of radio buttons?

**Comment by DylanDylann** [comment]
> @trjExpensify just to make sure: we're talking of changing the Wallet > Transfer Balance page to use the same design as Settlement Account page (not the way around?) - list items instead of radio buttons?

I see we have 2 tasks here:
- Always display highlight checkmark on the selected option
- we could update to align `PaymentMethodList` Component and use it in all places for consistency. @koko57 Wdyt?

<img width="1512" alt="Screenshot 2024-09-12 at 14 00 41" src="https://github.com/user-attachments/assets/9618693c-6716-4a28-a857-56fd1f0257fd">

**Comment by DylanDylann** [comment]
@allgandalf I will take this one

**Comment by koko57** [comment]
@DylanDylann yeah, I know we have 2 😅 I was just asking - do we want checkmarks or radio buttons? But I understand we're going with Select List not Radio Buttons 😄

**Comment by DylanDylann** [comment]
> But I understand we're going with Select List not Radio Buttons 😄

I have the same thoughts with you

Anyways, It shouldn't block creating PR, we can get a confirmation on the PR phase

**Comment by koko57** [comment]
@DylanDylann yep, on it. I'm doing 1000 things at once, but I should be able to open the PR for that til EOD 😅

**Comment by DylanDylann** [comment]
Ops. @koko57 I can help raise a PR early on Friday morning if you are busy (and you can help review it). Take care!

**Comment by koko57** [comment]
@DylanDylann thank you, no worries, I can do it 😃

**Comment by koko57** [comment]
@DylanDylann @trjExpensify I can open the PR for fixing the checkmark, but for this design change I would rather open a separate PR - I can do it under its issue, but a separate would be better. It's not just replacing one component - we're using PaymentMethodList which is also used in another location, and here for the data we have both bank accounts and cards

**Comment by koko57** [comment]
@trjExpensify @DylanDylann I'm opening the PR for review. If you decide that both task should be done in one PR I will work on it tomorrow

**Comment by koko57** [comment]
@trjExpensify yes, the checkmark thing is a very small change and I don't want to block it, so that's why I opened the PR. 
This design change will take a bit longer, but if you want I can add this to the PR with checkmark

**Comment by trjExpensify** [comment]
Yep, sounds good! 👍

**Comment by koko57** [comment]
Great! Thanks!

**Comment by mountiny** [comment]
Are we keeping this open fo the transfer wallet page right? Or do we want to separate it into its own ticket?

**Comment by trjExpensify** [comment]
May as well just use this one.

**Comment by mountiny** [comment]
Asking in Slack if we can export this

**Comment by mountiny** [comment]
I propose $375 for this work as its 2 prs and the second pr put in place a fix with guidelines for others to avoid it so that is useful.

**Comment by DylanDylann** [comment]
Am I eligible for payment?

**Comment by mountiny** [comment]
Yeah i would say $250 as the second pr was basically no qa through but it took Gandalf some time to figure it out.

**Comment by mountiny** [comment]
$375 to @allgandalf 
$250 to @DylanDylann

**Comment by trjExpensify** [comment]
Noted.

**Comment by trjExpensify** [comment]
Offers sent!

**Comment by trjExpensify** [comment]
@allgandalf paid!

**Comment by trjExpensify** [comment]
Something is fucked with Upwork. That's the second time in a matter of hours. (CC: @ikevin127). 

I made the payment and closed the contract: 
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/bb7d9d3b-aefb-4f1c-a23d-b7eed19e82cf">

Can we give this until Monday to see if Upwork is on the blink and then I'll do a fresh one if not?

**Comment by trjExpensify** [comment]
Who knows, but yeah.. let's give them a bit to sort it out and then if it doesn't come through, I'll do a new contract.

**Comment by trjExpensify** [comment]
Alright, @DylanDylann has accepted the offer I sent on Friday. I'm going to try and end that now and see if Upwork has resolved itself. Then I'll send another to @allgandalf.

**Comment by trjExpensify** [comment]
Paid @allgandalf a bonus on the original borked contract to skirt the Upwork bug. Closing!
