### ISSUE TITLE
 iOS Copilot - Big empty space next to Full and Access row

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48971]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Account settings > Security.
3. Tap Add copilot.
4. Select a user > Next.

## Expected Result:
There should not be big empty space next to Full and Access row.

## Actual Result:
There is big empty space next to Full and Access row.
The device used is iPhone 15 Pro Max.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c7ab9264-6342-44ca-b0a0-e1a9904a2f2e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment]
This is pretty minor, just small styling issue, so removing the blocker label

**Comment by pecanoro** [comment]
@rushatgabhane @fedirjh It seems this PR caused this small bug https://github.com/Expensify/App/pull/47353. I was checking the videos and noticed both were posted before we added the description. Don't forget next time to retest everything if changes have been made!

**Comment by pecanoro** [comment]
@rushatgabhane Any updates?

**Comment by rushatgabhane** [comment]
> I'm tempted to say we should leave room for the checkmark even when it's not selected, but I don't know that I want to make this a special one-off treatment. Definitely curious for other designers' thoughts on this one. I can see it going either way, but I think leaving room for the checkmark always would probably make it feel a little smoother to switch between options.

I don't think we should fix this. In `SelectionList`, the `maxWidth` was intentionally added here - https://github.com/Expensify/App/pull/45601#issuecomment-2243145762

**Comment by rushatgabhane** [comment]
Please close this issue if you agree. 
cc: @dannymcclain

**Comment by dannymcclain** [comment]
I agree that we added this space on purpose to leave room for the checkmark/to prevent the UI from jumping around when you make a selection. But this select list doesn't feel quite right to me for some reason. Should we not have one option pre-selected? Also, it looks like when I do have an option selected, the selected option is missing its background color. cc @Expensify/design for a gut check on all this. We can totally close if this is all expected.

https://github.com/user-attachments/assets/7c7abc31-61a2-4077-9eff-3df8c9e9729f

**Comment by shawnborton** [comment]
I agree with all of the points Danny is making above! Totally should have a BG color, and totally should have one already selected when you access the list view.

**Comment by rushatgabhane** [comment]
which one should be selected by default?

**Comment by dannymcclain** [comment]
Hmm actually looking at the original design doc mocks, maybe I was wrong and there shouldn't be one selected initially. 
![CleanShot 2024-09-16 at 08 36 51@2x](https://github.com/user-attachments/assets/0ab15011-f784-4d92-ad13-49a4c93f5bf0)

We might just be able to close this one. Though I will note that the when you do view the list with a selection, the selected item is still missing a background.

**Comment by rushatgabhane** [comment]
> Though I will note that the when you do view the list with a selection, the selected item is still missing a background.

that has been fixed ✅ will take a few days for deployment

**Comment by dannymcclain** [comment]
Ok in that case I think we should just go ahead and close this one. @shawnborton you good with that?

**Comment by shawnborton** [comment]
Works for me!
