### ISSUE TITLE
Category rules - "Approver" is enabled when "Add approvals" is still disabled in Workflows

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48977]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48171
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Rules feature is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click on any category.
4. Note that the message under Approver says that "add approvals to unlock this feature".
5. Go to Rules.
6. Note that the same message is also said for "Prevent self-approvals".
7. Go to workspace settings.
8. Enable workflows, but do not enable Add approvals in Workflows page.
9. Go back to Rules.
10. Note that "Prevent self-approvals" is disabled because Add approvals feature is not enabled so the feature remains locked.
11. Go back to the same category in Step 3.
12. Note that Approver feature is unlocked even though Add approvals feature is not enabled.

## Expected Result:
In Step 12, Approver feature should remain locked until Add approvals feature is enabled on Workflows page.

## Actual Result:
In Step 12, Approver feature is unlocked when Add approvals feature is disabled on Workflows page, which is inconsistent with the behavior with "Prevent self-approvals" feature in Rules in Step 10.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9fcd1041-c7e9-42d0-9045-c731b2d1f9ad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by mjasikowski** [comment]
tagging @WojtekBoman as the original author of #48171

**Comment by BrtqKr** [comment]
https://github.com/Expensify/App/pull/48325#issuecomment-2343379882

is this related?

**Comment by mjasikowski** [comment]
@BrtqKr seems so, albeit looking at the design doc and testing steps involved it seems that the initial requirement was to disable the Approver button and show the hint if approvals are not enabled.

![image](https://github.com/user-attachments/assets/725f4384-ca6e-408d-81f4-86e9781ad6ed)

This is consistent with proposed manual testing steps:

![image](https://github.com/user-attachments/assets/667cd09d-948e-4868-af43-c1701492cf05)

Seeing that @marcaaron won't be available for the next few hours to clarify, I would suggest to treat the design document as the source of truth and for @WojtekBoman to create a PR based on the above.

**Comment by WojtekBoman** [comment]
I'll prepare a fix for that :)

**Comment by mjasikowski** [comment]
This functionality is behind beta, removing the blocker label.

**Comment by marcaaron** [comment]
Agree we should stick to the Design Doc on this one. It's hard to tell whether we are blocked on anything here, but sounds like @WojtekBoman is on the case. @mjasikowski I can take this off your hands since I am leading this project - but fine if you want to stick around 😄

**Comment by mjasikowski** [comment]
@marcaaron feel free to take over, I'm OOO frequently now due to personal issues

**Comment by marcaaron** [comment]
I see this has been fixed on staging so I think we can close it out.
