### ISSUE TITLE
[$250] Contact method - Auth CanAddSecondaryLogin error after entering incorrect magic code

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Contact method.
3. Click Add contact method.
4. Enter a new contact method > Next.
5. Enter incorrect magic code.

## Expected Result:
Wrong magic code error magic will be shown.

## Actual Result:
App returns to contact method page. When clicking on the new contact method, it shows Auth CanAddSecondaryLogin.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b43c9678-f3a1-43bd-9c9d-ff75bb89cc5a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834245266507223637</li>
        <li>Upwork Job ID: 1834245266507223637</li>
        <li>Last Price Increase: 2024-09-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by mjasikowski** [comment]
Looking at the backend error

**Comment by lschurr** [comment]
Any update @mjasikowski?

**Comment by lschurr** [comment]
Bump on this @mjasikowski

**Comment by mjasikowski** [comment]
PR in review

**Comment by mjasikowski** [comment]
Done, the new message should be: "Oops! Looks like the magic code you entered was incorrect. Please try again."
It was introduced in https://github.com/Expensify/Web-Expensify/pull/43524 and is already deployed to staging and production.

@IuliiaHerets feel free to re-test

**Comment by IuliiaHerets** [comment]
@mjasikowski Issue was fixed now. Sorry for the delay with response

https://github.com/user-attachments/assets/112549c1-2818-4397-96d8-45e2b51c5910
