### ISSUE TITLE
Submit expense - Scan tab briefly highlighted when switching to Distance

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#48992]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validation** https://github.com/Expensify/App/pull/48004
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Click FAB > Submit expense
2. Switch between tabs Manual, Scan, Distance (jump from Manual to Distance)

## Expected Result:
Selected tab is highlighted.

## Actual Result:
When switching from Manual to Distance, Scan tab briefly highlighted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2cd180b3-3ddb-4890-bd0c-5f850b046c07

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by CortneyOfstad** [comment]
This would fall under VIP-VSB and to be honest, this is not impactful bug to the user experience. Even watching the video, it took quite a bit of back and forth for it to even register. Because of that, and VIP-VSB being paused, I am closing this.
