### ISSUE TITLE
[Pending / Scanning] Report cannot be submitted when there are pending transactions on it

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#49019]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** kevinksullivan+member@cardtest.expensify.com
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1726077299603419

## Action Performed:

1. Create workspace
2. Enable delayed submission and keep approvals disabled
3. Invite a user
4. As the user from 3, make a payment using [paypal link](https://github.com/Expensify/Expensify/files/3974273/payButtons.html.zip) with expensify card
5. Create a manual expense and submit it to the same worksapce
6. Select submit

## Expected Result:
Expenses that have completed scan or are posted should be submitted on a single report. The pending/scanning expenses should be held back on a new report

More specifically:

**Instant + approvals:** 
- Pending expense gets added to the processing report, if the admin approve or pay we move it to another Processing report

**Delayed submission:**
- Pending expense is added to an Open report. If the submitter/admin submit the report, we move it to another Open report
- Pending expense is added to an Open report. If harvesting runs, we move it to another Open report.

## Actual Result:
Report is blocked from being sumbmitted

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f2691b93-26fd-41e3-a70c-bb9229b12907

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by trjExpensify** [comment]
CC: @youssef-lr as I believe something similar came up in thread somewhere today.

**Comment by trjExpensify** [comment]
Looks like it wasn't implemented. 👍

**Comment by alexpensify** [comment]
@youssef-lr any update here? Thanks!

**Comment by youssef-lr** [comment]
I haven't managed to get to this yet. I'm on it this week.

**Comment by youssef-lr** [comment]
Working on tests.

**Comment by alexpensify** [comment]
@youssef-lr what's left here? Thank you for the update!

**Comment by muttmuure** [comment]
@youssef-lr can we close this?

**Comment by grgia** [comment]
Yes we can close this out, PR was merged.
