### ISSUE TITLE
[Leads to paid] Add setting up tags as an onboarding task to `Manage my team expenses` intent

### ISSUE THREAD

**Issue by anmurali** [Expensify/App#49015]
**Proposal**: Add setting up tags as an onboarding task to `Manage my team expenses` intent

**Problem**: The vast majority of workspaces configure tags before they convert and add a card on file. From the collect usage data we did for #wave-collect, ~50% of workspaces have single level tags. Yet, during onboarding for a top down paid workspace, we don't even introduce the idea of a tag. This could suggest we don't have this feature as it is also buried under `More Features` in Workspace settings.

**Solution**: Let's add a set up tags onboarding task to `Manage my team expenses` intent

**Set up tags task copy**

>**Title: Set up tags (optional)**
>**Description**
Tags can be used if you want more details with every expense. Use tags for projects, clients, locations, departments, and more. If you need multiple levels of tags you can upgrade to a control plan.
>
>**Here’s how to setup tags:**
>
> 1. Click your profile picture.
> 2. Go to Workspaces.
> 3. Select your workspace.
> 4. Click More features.
> 5. Enable Tags.
> 6. Navigate to Tags in the workspace editor.
> 7. In Tags, click + Add tag to make your own.
>
>[Take me to more features](https://new.expensify.com/settings/workspaces/4F4977A767D37D6F/more-features).

Context for how to add a task and then show it for a specific intent selected during onboarding is [here](https://expensify.slack.com/archives/C07HPDRELLD/p1725905771543329?thread_ts=1725893574.581079&cid=C07HPDRELLD)

**Comment by dubielzyk-expensify** [comment]
Mocks:

![image](https://github.com/user-attachments/assets/21e88111-50f0-40f2-930a-1e3c807aec60)

@Expensify/design for visibility

**Comment by shawnborton** [comment]
Looks good! Minor nitpick - but I think there would be a big "Mark as complete" button on the right?

**Comment by dannymcclain** [comment]
Yup good call Shawn. Should look like this:

![CleanShot 2024-09-12 at 08 42 46@2x](https://github.com/user-attachments/assets/e71352ad-93dd-4759-a194-5b6816badf4e)

**Comment by shawnborton** [comment]
Right on 🤙

**Comment by dubielzyk-expensify** [comment]
Updated mocks:

![image](https://github.com/user-attachments/assets/3dcb9960-c4ad-41ae-a770-bd4a9eb5bce4)

**Comment by shawnborton** [comment]
Looks good!

**Comment by marcaaron** [comment]
Auth PR deployed and App PR in review.

**Comment by marcaaron** [comment]
This should be on production now. @eVoloshchak helped with the PR review and testing so we can close this out once they get paid.

**Comment by anmurali** [comment]
@marcaaron - I am so sorry but finally looking at it in prod we realized the `optional` is kinda weird. All of them are upto the admins after all. Why is this specially optional. Can we remove that from the task title copy? Sorry again for the double work.

**Comment by marcaaron** [comment]
No worries. It's a small change.

**Comment by eVoloshchak** [comment]
> @eVoloshchak sent you [an offer](https://www.upwork.com/nx/wm/offer/104097624)

@anmurali, no need, I'll request the payment via NewDot
Could you post a payment summary please?

**Comment by anmurali** [comment]
Payment Summary:

- [ ] @eVoloshchak $250 approved on New Dot

**Comment by JmillsExpensify** [comment]
$250 approved ror @eVoloshchak
