### ISSUE TITLE
[Pending / Scanning] Preview component temporarily shows $0 report and incorrect report title

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#49037]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 

**Email or phone of affected tester (no customers):** kevin+member@cardtest.expensify.com

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1726064778661229

## Action Performed:

1. Get assigned a >$0 limit on [cardtest.expensify.com](http://cardtest.expensify.com/) domain
2. Navigate to NewDot in your test account, and go to Settings > Wallet > Expensify Card > Reveal details (on virtual card)
4. Navigate to this [paypal link](https://github.com/Expensify/Expensify/files/3974273/payButtons.html.zip) and select “buy” on the first button on that screen
5. Pull up the relevant workspace chat before making a purchase so you can see it at the same time
6. Make a purchase with the expensify card
7. Check workspace chat

## Expected Result:
Preview component should show the right information

## Actual Result:
Preview component shows $0 and incorrect info for a second before updating to the correct info

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b630aedd-7abc-48c6-bdfe-5ef56e544c12

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment]
Haven't looked into this yet

**Comment by jliexpensify** [comment]
Not overdue

**Comment by jliexpensify** [comment]
Not overdue, waiting on @grgia

**Comment by grgia** [comment]
Report title was fixed

**Comment by grgia** [comment]
I think the $0 issue is a problem with report creation, looking

**Comment by grgia** [comment]
See https://expensify.slack.com/archives/C036QM0SLJK/p1727869780060459?thread_ts=1727720791.570199&cid=C036QM0SLJK

I swipe my card at the shop
An empty report is created before we call create transaction (because we need to pass it the report). At this time a pusher onyx update is sent for the newly created $0 report.
CreateTransaction is eventually called within a few seconds. The report is updated with the transaction. A second pusher update is sent, and the report fills out the data.

**Comment by grgia** [comment]
Report title part of this is in progress

**Comment by grgia** [comment]
in progress!

**Comment by grgia** [comment]
Closing out pending https://expensify.slack.com/archives/C05R2V5GM1S/p1730205435685289?thread_ts=1730135263.830799&cid=C05R2V5GM1S
