### ISSUE TITLE
Report Field - When you select Back, both pop-ups are swipe out

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49043]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+nhut_new00@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open app
2. Go to settings
3. Go to any workspace
4. Go to Report Fields (Make sure the Report Fields feature is enabled before)
5. Click on the + Add field
6. Popup one appears
7. Click on Name
8. Popup two appears
9. From the top menu > Click on History > Click on Back (Or click the shortcut Cmd + [ )

## Expected Result:
It takes 2 steps to go back and turn off each popup in turn.

## Actual Result:
We have 2 steps to open 2 popups. But when we click Back, both popups are swiped out in one step.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1800" alt="Bug6600130_1726071981589!Screenshot_2024-09-11_at_23 21 22" src="https://github.com/user-attachments/assets/54576b7e-fb55-4b08-b25d-56c1d35520ff">

https://github.com/user-attachments/assets/82c93455-7e21-4d5f-83e0-0af14c3167fb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment]
This is a similar issue to https://github.com/Expensify/App/issues/45888 that was decided as wontfix.
