### ISSUE TITLE
[$500]  iOS Expense - The report of the other expense auto scrolls up after deleting expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49045]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48055
**Email or phone of affected tester (no customers):** applausetester+kh090901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit two expenses.
3. Go to transaction thread of first expense.
4. Tap on the header.
5. Tap Delete Expense.
6. Delete the expense.

## Expected Result:
The report of the other expense will not auto scroll up after deleting the other expense.

## Actual Result:
The report of the other expense auto scrolls up after deleting the other expense.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/110a188e-7ee2-4d21-8288-f740dfe7ac8b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834166473134569544</li>
        <li>Upwork Job ID: 1834166473134569544</li>
        <li>Last Price Increase: 2024-10-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by Gonals** [comment]
Since this is a minor bug, very specific bug, just in one platform, I don't think we need to block deploy on it. What do you think, @luacmartins?

**Comment by DylanDylann** [comment]
Looking for proposal

**Comment by DylanDylann** [comment]
Waiting for proposals

**Comment by DylanDylann** [comment]
Post on Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1727375412234709

**Comment by DylanDylann** [comment]
@Gonals Should we consider doubling the price to get more eyes?

**Comment by dylanexpensify** [comment]
Done!

**Comment by DylanDylann** [comment]
I just checked this issue but I can't reproduce anymore

https://github.com/user-attachments/assets/31e14fc9-be3f-4743-b3ef-02c8e8434aea
