### ISSUE TITLE
Company cards - AMEX icon is cut off on Android and iOS app

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49047]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48119
**Email or phone of affected tester (no customers):** applausetester+kh090901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Company cards feature is enabled.

1. Launch New Expensify app.
2. Go to https://staging.new.expensify.com/settings/workspaces/policyID/company-cards/add-card-feed

## Expected Result:
AMEX icon will be displayed in full card (web behavior).

## Actual Result:
AMEX icon is cut off on Android and iOS app.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/08f62304-0068-4263-ac67-a80aa442fb3d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by Pujan92** [comment]
I think company card feature is not opened for QA yet, this will be handled by @waterim

**Comment by waterim** [comment]
@joekaufmanexpensify Should it be closed as Company cards is under NO QA label?

**Comment by koko57** [comment]
+ not a deploy blocker as it's under beta

**Comment by joekaufmanexpensify** [comment]
Yeah, let's close for now. This feature is still in implementation. We're going to start comprehensive manual testing soon, but any QA now is premature.
