### ISSUE TITLE
Wallet - Incorrect error message when entering incorrect magic code to reveal details

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49050]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48953
**Email or phone of affected tester (no customers):** applausetester+kh090901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has a virtual card.

1. Go to staging.new.expensify.com
2. Go to Account settings > Wallet.
3. Click on the virtual card.
4. Click Reveal details.
5. Enter incorrect magic code.

## Expected Result:
App will show error that the magic code is incorrect.

## Actual Result:
App shows the error "An error occurred while loading the card details. Please check your internet connection and try again.".

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/989ab62f-6c6b-4915-96cc-95051a643238

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment]
Coming from https://github.com/Expensify/App/pull/48953/
I don't think this is a blocker, at least it's better than the previous behavior. 
But also @marcaaron I am not sure we should be matching errors by message, that's what we use jsonCodes for, no?

**Comment by marcaaron** [comment]
yeah, it was unclear to me since this is an exceptional case where we use `makeRequestWithSideEffects` so maybe:

- give it a different jsonCode
- allow it to throw
- and handle the jsonCode

I'll try something like that - this is not a blocker.

**Comment by marcaaron** [comment]
>But we receive JSON code 451 with this case

To clarify, no, not anymore. It throws an expected error with `jsonCode: 666`. This issue is not happening anymore so I'm going to close it.

But maybe we still want to address this comment:

>I am not sure we should be [matching errors by message](https://github.com/Expensify/App/pull/48953/files#diff-ae962772c4a3418dc70235b3715b5c5612065b8a9371dca5043b401b5cd83781R205), that's what we use jsonCodes for, no?
