### ISSUE TITLE
Contact Methods - Email field not auto-focused when returning to New contact method page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49068]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log into an account
2. Go to settings > Profile > Contact method
3. Click on New Contact Method
4. Enter email and click on add
5. Return back

## Expected Result:
Email field is focused when returning back to New contact method page

## Actual Result:
Email field is not auto-focused when returning to New contact method page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ad508451-791f-4dde-b9af-fa4c3543b96f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment]
Sorry for the delay — this was assigned when I was OoO. Reviewing now!
