### ISSUE TITLE
Expense - App returns to main chat after deleting expense when it has replies

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49066]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4953525
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM that has no unsettled expense.
3. Submit an expense.
4. Go to combined report.
5. Add a reply.
6. Click on the report header.
7. Click Delete expense.
8. Delete the expense.

## Expected Result:
App will stay on the same thread because the report has replies (production behavior).

## Actual Result:
App returns to main chat after deleting the expense when it has replies.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/603aa3a5-3496-4666-91de-5df86293522b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
Production 

https://github.com/user-attachments/assets/8ba7f573-7a46-4534-9179-7056aefcb6f6

**Comment by luacmartins** [comment]
@nkdengineer do you think this one is related to https://github.com/Expensify/App/issues/49052?

**Comment by nkdengineer** [comment]
Let me check and testing when implementing the PR.

**Comment by luacmartins** [comment]
We're reverting the offending PR.

**Comment by luacmartins** [comment]
This is fixed on staging. Closing.
