### ISSUE TITLE
Room - Room description not showing text before ellipsis in find page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team
## Action Performed:
1. Launch app
2. Open a room chat
3. Tap header -- room description
4. Enter multiline text - @[Jaihanumanblog@gmail.com](mailto:Jaihanumanblog@gmail.com)

.......m
5. Save it
6. Navigate to LHN
7. Tap find

## Expected Result:
Text before ellipsis must be displayed.

## Actual Result:
Room description not showing text before ellipsis but text after ellipsis is shown in " find" drop down list.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6c01a523-f275-45fb-b960-5200a78b9190

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
This seems very niche and not user reported, so closing this in favour of items affecting users and the roadmap.
