### ISSUE TITLE
Categories-New category added in offline must not disappear when go online.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49074]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap profile icon -- workspaces -- new workspace
3. Tap categories -- add category
4. Go offline
5. Paste in category field -
उद्यद्भानु-सहस्र-कोटि-सदृशां केयूर-हारोज्ज्वलां
विम्बोष्ठीं स्मित-दन्तपङ्क्ति-रुचिरां पीताम्बरा-
6. Save
7. Scroll down and note new category is shown in category list as greyed out
8. Go online
9. Now note new category disappeared

## Expected Result:
New category added in offline must not disappear when go online.

## Actual Result:
New category added in offline disappeared when go online.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dce00b12-270d-4b33-bb58-5b2baecaf564

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment]
@izarutskaya is it just characters like this that aren't saving?

>Paste in category field -
>उद्यद्भानु-सहस्र-कोटि-सदृशां केयूर-हारोज्ज्वलां
>विम्बोष्ठीं स्मित-दन्तपङ्क्ति-रुचिरां पीताम्बरा-

I've tested and normal words are saving

**Comment by jliexpensify** [comment]
Bump @izarutskaya - [can you confirm if this is only special characters not saving?](https://github.com/Expensify/App/issues/49074#issuecomment-2347913272)

**Comment by jliexpensify** [comment]
Also asking if we want to fix this: https://expensify.slack.com/archives/C036QM0SLJK/p1726539585628499
