### ISSUE TITLE
[HOLD for payment 2024-10-17] [$250] Header flickers on the search page when switching tabs while reports are already selected.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726146285093739

## Action Performed:
1. Open the app and go to the Search tab.
2. Select one or two reports.
3. Change the tab and then return to the Search tab.
4. Observe the header of the Search tab.
## Expected Result:
No visual issues (Header should not flicker)
## Actual Result:
Header flickers, and for a moment, the sidebar screen header becomes visible.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/58a458ae-af30-4190-bf36-3d2f4fe96685

https://github.com/user-attachments/assets/031c7091-0908-4596-8a1a-8e3dbd889c28

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836532792123032065</li>
        <li>Upwork Job ID: 1836532792123032065</li>
        <li>Last Price Increase: 2024-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104043289</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment]
Adding this one to my test list and will get to it later this week.

**Comment by alexpensify** [comment]
@jjcoffee when you get a chance, can you review if one of these proposals will fix this issue? Thanks!

**Comment by alexpensify** [comment]
Awesome, now we wait for this one to go through the review process.

**Comment by alexpensify** [comment]
The PR is still under review

**Comment by alexpensify** [comment]
@aldo-expensify - we need a review in this PR. Thanks!

**Comment by aldo-expensify** [comment]
Thanks, reviewed

**Comment by alexpensify** [comment]
Thank you!

**Comment by alexpensify** [comment]
Ok, waiting for this one to go to Prod.

**Comment by jjcoffee** [comment]
> when you get a chance, can you please confirm if this blocker notice is correct? Thanks!

@alexpensify Yes it's correct, the PR got reverted. @daledah is working on a fix.

**Comment by alexpensify** [comment]
Payouts due: 2024-10-17

- [ ] Reviewer: Amount TBD @jayeshmangwani
- [ ] Contributor: $250 @daledah
- [ ] Reviewer: $250 @jjcoffee 

Upwork job is [here](https://www.upwork.com/jobs/~021836532792123032065). I'm still working on the payment process here. @daledah please accept the invite in Upwork. Thanks!

**Comment by alexpensify** [comment]
I've completed the payment process for @jjcoffee. I'm waiting for @daledah to accept the invite and then I can complete the payment process. Also, I confirmed that there is no payment for reporting an issue.

**Comment by alexpensify** [comment]
I'm offline until Tuesday, but I passed by to check the payment status. We are waiting for @daledah to accept the offer in Upwork, and then I can complete the process.

**Comment by aldo-expensify** [comment]
> @alexpensify I accepted the offer

I think this means we can close... Please reopen if I got that wrong :)

**Comment by alexpensify** [comment]
@aldo-expensify—I was offline until today, hence the overdue notice. I saved this GitHub to return to when I was online again, but please keep it open. BZ still needs to go into Upwork and complete the payment process. Keeping this one closed, I finished the payment process last night.

**Comment by aldo-expensify** [comment]
Thanks @alexpensify , will keep that in mind the next time :)
