### ISSUE TITLE
[$250] [Performance] Persist image scans when clearing cache and restarting [Payment is due on OCT 8]

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#49085]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

When multiple requests fail and jam up the sequential queue for several minutes (which is being investigated and fixed) the fastest way to GSD again is to use `Clear cache and restart` in the Troubleshoot menu. 

The byproduct of doing this is that if you have any messages or receipt uploads waiting for their request to process, they are lost when you hit that button.

## What is the impact of this on end-users?

Users lose their receipt images.

## List any benchmarks that show the severity of the issue
Please also provide exact steps taken to collect metrics above if any so we can independently verify the results.

N/A

## Proposed solution (if any)
Please list out the steps you think we should take to solve this issue.

Ask the end user for permission to store all pending receipt uploads to their phone's camera roll, add the receipts to the camera roll, and automatically add them to the camera roll next time.  

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)
Note: These should be the same as the benchmarks collected before any changes.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1726082473000159?thread_ts=1726059136.088489&cid=C05LX9D6E07 

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834242849711510101</li>
        <li>Upwork Job ID: 1834242849711510101</li>
        <li>Last Price Increase: 2024-09-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by isabelastisser** [comment]
Waiting for proposals.

**Comment by TMisiukiewicz** [comment]
I'm Tomasz from Callstack and I'd like to work on this issue

**Comment by TMisiukiewicz** [comment]
@muttmuure I initially explored persisting the networkRequestQueue while clearing the Onyx state, as it seemed like a quicker solution. The request queue holds the locally cached image paths, so pending receipts remain persistent. Once the state is cleared and the queue is processed, the receipts are handled correctly.

Would this solution be sufficient, or are you specifically looking to store the scanned receipts in the camera roll?

**Comment by muttmuure** [comment]
yes I think that would work too

**Comment by TMisiukiewicz** [comment]
thanks, I'll work on a PR with that change 👍

**Comment by TMisiukiewicz** [comment]
Still working on this, I was looking for a proper way how to prioritize `OpenApp` request in a sequential queue and run it before any other queued requests when using "Clear cache and restart". Without it, the data breaks and the app does not work properly. Already found a solution, I'll open a PR on Monday.

**Comment by TMisiukiewicz** [comment]
opened #49588 👍

**Comment by mananjadhav** [comment]
@isabelastisser There would be a payout for me. I helped review the PR. We'll need to wait through the regression period.

**Comment by isabelastisser** [comment]
Thanks for the update!

**Comment by mananjadhav** [comment]
This was deployed yesterday so the payout should be 10/8.

**Comment by mananjadhav** [comment]
@isabelastisser This is ready for payout. I don't have any offending PR for this one. Neither any regression test.  This was more of a performance change.

**Comment by isabelastisser** [comment]
Payment summary:

$250 to @mananjadhav for C+ review - Payment pending in Upwork.

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav  

@isabelastisser payment for him is in ND.
