### ISSUE TITLE
Expense - Expense preview is shown briefly after deleting expense and returning to main chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49094]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4955466
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM that has no unsettled expense.
3. Submit an expense.
4. Click on the expense preview.
5. Click on the report header.
6. Click Delete expense.
7. Delete the expense.

## Expected Result:
The expense preview should not appear after deleting the expense and returning to the main chat (production behavior).

## Actual Result:
The expense preview is shown briefly after deleting the expense and returning to the main chat.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/37be8efd-5185-43e3-bf25-1cca0e50b397

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dangrous** [comment]
seems very minor (I'd argue shouldn't block deploy) but let me see if I can find a cause quickly!

**Comment by dangrous** [comment]
thanks @Nodebrute! I wish I had looked here instead of waiting 15 mins running `git bisect` to come up with the same source haha.

**Comment by luacmartins** [comment]
This is fixed on staging. Closing.
