### ISSUE TITLE
[HOLD for Payment 2024-09-26][$250] [Search v2.2] - Chats - Report with error shows RBR next to checkbox in "In" list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49091]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48275
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User B has only one workspace.

1. Go to staging.new.expensify.com
2. {User A] Send an invoice to User B.
3. [User B] Pay the invoice using Pay as a business option.
4. [User A] Go offline.
5. [User A] Send another invoice to User B in the same invoice room.
6. [User B] Delete the workspace.
7. [User A] Go online.
8. [User A] Click on the invoice preview that has RBR.
9. [User A] Go to Search > Chats.
10. [User A] Click Filters.
11. [User A] Click In.

## Expected Result:
The invoice report with error should not have RBR next to the checkbox in "In" list.

## Actual Result:
The invoice report with error has RBR next to the checkbox in "In" list.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5c83f671-32e5-4063-bb73-c4d89e9326f7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834357041213588001</li>
        <li>Upwork Job ID: 1834357041213588001</li>
        <li>Last Price Increase: 2024-09-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment]
@Kicu @289Adam289 if you're interested in working on a fix

**Comment by luacmartins** [comment]
I'm gonna demote this to NAB since it's a small issue

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @dominictb $250 - Upwork offer extended, please accept! https://www.upwork.com/nx/wm/offer/104189980
 - Contributor+: @rayane-djouah$250 - Upwork offer extended, please accept! https://www.upwork.com/nx/wm/offer/104189994
 
 Upwork job is here: https://www.upwork.com/jobs/~021834357041213588001

**Comment by stephanieelliott** [comment]
All paid, thank you!
