### ISSUE TITLE
The font color on the onfido flow is off

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49090]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @coleaeason 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726084405673789

## Action Performed:
1. Complete the connect bank account flow till the onfido page from workspace

## Expected Result:
No visual issues
## Actual Result:
Onfido logo and Onfido added text are difficult to read
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/c14a0496-ea51-4ab3-b651-5543dcf13fa0" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/5ed9585a-f3a9-443b-9a2c-89f03bf6e417" width="40%" height="40%">
Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment]
closing this issue until the thread is finalized - it looks like this may not be something we can action
