### ISSUE TITLE
[HOLD for payment 2024-10-14] [HOLD for payment 2024-10-11] [$250] [Search v2.4] [App] Add Recent Searches and Recent Chats sections

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49116]
Implement [this section](https://docs.google.com/document/d/1Uf7UwMYTmek2qWe37SqkQZnOZYrnrfPucOLzXMv-3WM/edit#bookmark=id.z7xv36bl2yqg) of the doc

cc @Kicu @289Adam289 @Guccio163 @SzymczakJ 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834650319760395608</li>
        <li>Upwork Job ID: 1834650319760395608</li>
        <li>Last Price Increase: 2024-09-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by Christinadobrzyn** [comment]
hi @SzymczakJ do you have an update on this for the team? TY!

**Comment by SzymczakJ** [comment]
The draft PR should be ready tomorrow.

**Comment by luacmartins** [comment]
PR in review

**Comment by Christinadobrzyn** [comment]
Monitoring - https://github.com/Expensify/App/pull/49457

**Comment by Christinadobrzyn** [comment]
Monitoring - https://github.com/Expensify/App/pull/49457

Heads up, I'm going to be ooo until 9/30. Since we're working on the PR I'm not going to assign a new BZ teammate. If you need one while I'm away please reach out in Slack for a volunteer.

**Comment by Christinadobrzyn** [comment]
Monitoring - https://github.com/Expensify/App/pull/49457

**Comment by Christinadobrzyn** [comment]
Hey @rayane-djouah and @SzymczakJ can you check these ^ deploy blocker messages to see if they apply here?

**Comment by Kicu** [comment]
but @jasperhuangg removed the deploy blocker labels from the issue as they were not able to reproduce it.
So I don't think there is anything to verify here if there is no clear repro.

**Comment by luacmartins** [comment]
Those blockers apply here, but they were already fixed with [this PR/CP](https://github.com/Expensify/App/pull/50143)

**Comment by Christinadobrzyn** [comment]
Payouts due:

- [ ] Reviewer: $250 @rayane-djouah (Upwork offer - https://www.upwork.com/nx/wm/offer/104402695)

**Comment by Christinadobrzyn** [comment]
It's payday - payment summary here - https://github.com/Expensify/App/issues/49116#issuecomment-2409669613

No regression test so closing this out.
