### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Invoice - Invoice room is not archived after deleting the workspace offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49113]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48275
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User B has only one workspace.

1. Go to staging.new.expensify.com
2. {User A] Send an invoice to User B.
3. [User B] Pay the invoice using Pay as a business option.
4. [User B] Go offline.
5. [User B] Delete the workspace.
6. {User B] Go to invoice chat.

## Expected Result:
The invoice chat should be archived after deleting the workspace offline.

## Actual Result:
The invoice room is not archived after deleting the workspace offline.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e0fa69f8-afee-487e-b4c4-737ceae9df5a

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841806197088184582</li>
        <li>Upwork Job ID: 1841806197088184582</li>
        <li>Last Price Increase: 2024-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104360901</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment]
reviewing today!

**Comment by dylanexpensify** [comment]
@davidcardoza can you confirm if this is unexpected behavior?

**Comment by davidcardoza** [comment]
Do we archive workspace rooms after a workspace is delete? If yes, an invoice room should follow the same pattern.

**Comment by davidcardoza** [comment]
Any update on this issue?

**Comment by dylanexpensify** [comment]
@davidcardoza sorry for delay, yes, we do archive rooms when a workspace is deleted, so agree we follow that logic here with invoice rooms.

**Comment by dylanexpensify** [comment]
pending proposals

**Comment by dylanexpensify** [comment]
Reassigning as I head to parental leave next week! Thanks Tom!

**Comment by trjExpensify** [comment]
👋 checklist time!

**Comment by jasperhuangg** [comment]
Awaiting checklist cc @dukenv0307

**Comment by trjExpensify** [comment]
For Melv, agreed!

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @daledah for the fix (offer sent)
- $250 to @dukenv0307 for the C+ review (paid!)

**Comment by trjExpensify** [comment]
@davidcardoza for the invoice project, are regression tests being handed over centrally to Applause to add to TestRail, and is one for deleting the workspace and archiving the invoice room included?

**Comment by davidcardoza** [comment]
Yes, test cases to cover invoices were added to TestRail - https://github.com/Expensify/Expensify/issues/410043

There is not a test for deleting the workspace and archiving the invoice room. I can add it a new regression test to to it though. Before I spin up a new GH to add the QA test, is what's missing this:

1. Deleting a workspace and archiving a room when there is an unpaid invoice in the room 
2. Deleting a workspace and archiving a room when there is an paid invoice in the room 

Anything else?

**Comment by trjExpensify** [comment]
I think that covers it!

**Comment by trjExpensify** [comment]
Cool, so everyone is paid here now. I'll close it out!
