### ISSUE TITLE
[$250] [Search v2.4] [App] Search Router Input

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49119]
Implement [this section](https://docs.google.com/document/d/1Uf7UwMYTmek2qWe37SqkQZnOZYrnrfPucOLzXMv-3WM/edit#bookmark=id.aqjz01ybtwl0) of the doc

cc @Kicu @289Adam289 @Guccio163 @SzymczakJ

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834649994160427605</li>
        <li>Upwork Job ID: 1834649994160427605</li>
        <li>Last Price Increase: 2024-09-13</li>
    </ul>
</details>

**Comment by Kicu** [comment]
Hey please assign me to this one

**Comment by jliexpensify** [comment]
All yours @Kicu!

**Comment by luacmartins** [comment]
PR was merged

**Comment by luacmartins** [comment]
I'm gonna close this issue in favor of https://github.com/Expensify/App/issues/49118 since the [PR](https://github.com/Expensify/App/pull/48785) handled both issues
