### ISSUE TITLE
[HOLD 48627][$250] [Search v2.1] Searching for expense with description `[FINDME]` crashes app

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49114]
BUG: Searching for expense with description `[FINDME]` crashes app
From: 
[@alexbeaman](https://expensify.slack.com/team/U01Q3CA8LHM)

Action Performed:
1. Go to search page -> Description
2. Enter a description to search `[FINDME]`
3. Click search
Expected Result: Results should show
Actual Result: App shows "Hmmm...  it's not here" page
Platforms: Web at least
Version Number: Latest staging (maybe prod too)
Screenshots or Videos: :thread:
If you think the bug is part of a Wave or VIP project, please cross-post in that room. List in bookmarks above.

![Screenshot 2024-09-12 at 11 46 58 AM](https://github.com/user-attachments/assets/ce8c018e-26bf-4cc0-a1c2-46899c7aaf8d)

cc @Kicu @289Adam289 @Guccio163 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834291053186780504</li>
        <li>Upwork Job ID: 1834291053186780504</li>
        <li>Last Price Increase: 2024-09-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by 289Adam289** [comment]
@luacmartins I think proposal from https://github.com/Expensify/App/issues/48627 will solve this issue

**Comment by luacmartins** [comment]
I agree. Pinged the contributor to also add this issue to the list of solved issues. Thanks!

**Comment by luacmartins** [comment]
This is solved by https://github.com/Expensify/App/pull/49229. Closing
