### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] [Search v2.4] [App] Update Search results page (Search bar only)

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49121]
Implement [this section](https://docs.google.com/document/d/1Uf7UwMYTmek2qWe37SqkQZnOZYrnrfPucOLzXMv-3WM/edit#bookmark=id.4f2gfqrhuzj5) of the doc

cc @Kicu @289Adam289 @Guccio163 @SzymczakJ

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836550707659197153</li>
        <li>Upwork Job ID: 1836550707659197153</li>
        <li>Last Price Increase: 2024-09-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by Kicu** [comment]
I'll make sure someone from SWM grabs this next week

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz from Software Mansion, the expert agency, and I'll be working on this issue.

**Comment by luacmartins** [comment]
All yours @cdOut

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @cdOut - Contractor, no payment required
Contributor+: @rayane-djouah paid $250 via Upwork

**Comment by luacmartins** [comment]
@VictoriaExpensify we actually had two PRs linked to this issue:
- https://github.com/Expensify/App/pull/49462
- https://github.com/Expensify/App/pull/49838

@rayane-djouah reviewed both of them so the payout should be $500. Could you please help processing the remaining $250?

**Comment by VictoriaExpensify** [comment]
Ah sorry, there is usually just 1x payment per issue. I can process a $250 bonus since it sounds like the effort deserves this.

**Comment by VictoriaExpensify** [comment]
![image](https://github.com/user-attachments/assets/279d1e12-e050-427e-95cc-ceb20a99818b)

**Comment by VictoriaExpensify** [comment]
Updated payment summary:
Contributor: @cdOut - Contractor, no payment required
Contributor+: @rayane-djouah paid $500 via Upwork
