### ISSUE TITLE
Disabling Workflows turns Scheduled Submit off when it shouldn't

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#49128]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1726136887331749?thread_ts=1725892977.799399&cid=C06ML6X0W9L

## Action Performed:
When you enable and then disable workflows again, scheduledSubmit=instantly incorrectly changes to scheduledSubmit=disabled. It shouldn’t change.
1. Create a new workspace
2. Enable Workflows
3. Open the Reports page in the OldDot Workspace Editor
4. Observe that Scheduled Submit is enabled and set to `instantly`
5. In NewDot, disable Workflows.
6. Refresh the Reports page in the OldDot Workspace Editor

## Expected Result:
The Scheduled Submit feature shouldn't have been changed by disabling Workflows. It should remain as `instantly`.

## Actual Result:
Scheduled Submit is disabled.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Deployed to prod, closing.
