### ISSUE TITLE
[$250] [Search v2.4] [App] Search Router List

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49120]
Implement [this section](https://docs.google.com/document/d/1Uf7UwMYTmek2qWe37SqkQZnOZYrnrfPucOLzXMv-3WM/edit#bookmark=id.da3fp9ml9bkw) of the doc

cc @Kicu @289Adam289 @Guccio163 @SzymczakJ

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834649901147542101</li>
        <li>Upwork Job ID: 1834649901147542101</li>
        <li>Last Price Increase: 2024-09-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @SzymczakJ</details>

**Comment by joekaufmanexpensify** [comment]
SWM team, please comment on this issue if you're working on this one, and I will assign you!

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by SzymczakJ** [comment]
I'm just starting to work on it and it's hard to make estimates just now. I'll update tomorrow when I'll know more 🫡

**Comment by joekaufmanexpensify** [comment]
Sounds good. TY!

**Comment by SzymczakJ** [comment]
I should be able to put up a draft PR tommorow!

**Comment by joekaufmanexpensify** [comment]
Sweet.

**Comment by joekaufmanexpensify** [comment]
PR is WIP

**Comment by joekaufmanexpensify** [comment]
@SzymczakJ is there an ETA to have this PR in review?

**Comment by SzymczakJ** [comment]
I'm working shorter hours for next two days, but I'll try to make it ready for C+ review tomorrow!

**Comment by joekaufmanexpensify** [comment]
Got it. TY!

**Comment by joekaufmanexpensify** [comment]
Pending @SzymczakJ publishing the PR

**Comment by joekaufmanexpensify** [comment]
@SzymczakJ is this week looking likely still to have the PR in review?

**Comment by SzymczakJ** [comment]
I've fixed the review comments and was about to record videos, but I've bumped into strange bug on iOS, which I'm solving at the moment. Probably the safe ETA would be next week 😓

**Comment by joekaufmanexpensify** [comment]
I see PR in review now. TY!

**Comment by luacmartins** [comment]
I'm gonna close this issue in favor of https://github.com/Expensify/App/issues/49116 since [this PR](https://github.com/Expensify/App/pull/49457) handled both issues.
