### ISSUE TITLE
[$250] [HOLD for payment 2024-10-25] [Search v2.4] [App] Remove existing ChatFinder functionality

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49123]
Implement [this section](https://docs.google.com/document/d/1Uf7UwMYTmek2qWe37SqkQZnOZYrnrfPucOLzXMv-3WM/edit#bookmark=id.bumz5dc3cy37) of the doc

- [ ] Hold on https://github.com/Expensify/App/issues/49122

cc @Kicu @289Adam289 @Guccio163 @SzymczakJ

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849747339555708566</li>
        <li>Upwork Job ID: 1849747339555708566</li>
        <li>Last Price Increase: 2024-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 104587131</li>
</ul></li>
    </ul>
</details>

**Comment by Kicu** [comment]
This is on Hold and it will be literally the last thing to do, after everything else in 2.4 works fine.
So we can either leave it be for now, or if you prefer to always have someone assigned then you can assign this to me.

**Comment by zanyrenney** [comment]
as per comment above, this is the last item for search.

**Comment by luacmartins** [comment]
On hold

**Comment by Kicu** [comment]
Leaving a paper trail.

As part of removing old chat finder we need to migrate the performance measurements done there. Relevant thread: https://swmansion.slack.com/archives/C06ML6X0W9L/p1727777756022389?thread_ts=1727777636.836479&cid=C06ML6X0W9L

**Comment by zanyrenney** [comment]
Just noting here that there seems to be no bug zero checklist as this is a new feature. Adding the payment summary as per below -

@Kicu does not require payment (Contractor)
@rayane-djouah requires payment (Needs manual offer from BZ) - paid $250 via upwork.
