### ISSUE TITLE
[PAID] [$250] Workspace switcher - Missing tab index for New Workspace button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49132]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+nhut_new00@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Click on the Down arrow at Expensify logo
3. Press tab few times to select items in popup

## Expected Result:
When pressing the tab in turn, the items will be selected and ready to be activated. And 'New workspace' button too.

## Actual Result:
When pressing the tab a few times, the items in the popup will be selected, but the "New Workspace" button will not be selected.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1209" alt="Bug6601259_1726159236269!Screenshot_2024-09-12_at_23 39 27" src="https://github.com/user-attachments/assets/34e3eec5-5219-425c-894b-44bc2cbf17b4">

https://github.com/user-attachments/assets/519cfc93-23fa-4ccd-bb9d-acbc9c5582ac

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836189432662301934</li>
        <li>Upwork Job ID: 1836189432662301934</li>
        <li>Last Price Increase: 2024-09-17</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104071431</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment]
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment]
Easy to repro on Mac/Chrome so applying external labels.

**Comment by strepanier03** [comment]
Paid and contract closed, thanks again!

**Comment by strepanier03** [comment]
### Payment Summary

- [x] @Nodebrute - $250 via Upwork ([paid](https://www.upwork.com/nx/wm/offer/104071431))
- [ ] @Ollyws - $250 via Manual Request in New Expensify

**Comment by strepanier03** [comment]
Sorry about that @Ollyws I missed it entirely.

**Comment by garrettmknight** [comment]
$250 approved for @Ollyws
