### ISSUE TITLE
Saga intacct - After entering incorrect credentials, if we connect advanced-auto sync toggle is off.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49137]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Create a workspace
3. Tap more features --enable accounting features
4. Tap accounting features -- connect sage intacct entering incorrect credentials
5. Tap 3 dots - enter correct credentials and connect
6. Tap advanced
7. Note auto sync toggle is off
8. Disconnect connection
9. In new workspace, try to connect entering valid credentials
10. Tap advanced
11. Note auto sync is on

## Expected Result:
After entering incorrect credentials, if we connect advanced-auto sync toggle must not be off.

## Actual Result:
After entering incorrect credentials, if we connect advanced-auto sync toggle is off.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1e1f7615-2a08-4e04-93e7-3f0a2e2303a0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment]
I don't think this one is a bug.
