### ISSUE TITLE
[$250] [Workspace Feeds] Copied content & LHN preview do not follow "x added shipping details" message

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49149]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48775
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User is assigned a physical card.
- User does not have personal details.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Click Add shipping details.
4. Complete the flow.
5. Right click on the system message "x added shipping details" > Copy to clipboard.
6. Paste the system message.
7. Note that the copied content and LHN preview are not the same as the system message.

## Expected Result:

The copied content and LHN preview will be the same as the system message.

## Actual Result:
The copied content and LHN preview are not the same as the system message.
The same goes for thread header for the system message.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cf66c4bd-6a74-41a9-afa2-a1ed37407e69

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834508189358735905</li>
        <li>Upwork Job ID: 1834508189358735905</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103942798</li>
<li>allgandalf | Contributor | 103945830</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by Gonals** [comment]
External bug! It'd be nice to solve it soon, but I don't think we need to block deploy on it.

**Comment by koko57** [comment]
I worked on the cards, I can check this issue

**Comment by jliexpensify** [comment]
Assigned @koko57 , removed `Hourly` cc @Gonals

**Comment by koko57** [comment]
I started looking at the issue - just one thing that I need to clarify: 
scenario: User A (with shipping address) issues a physical card for User B (no shipping address) 
User B gets this message
<img width="667" alt="Screenshot 2024-09-13 at 17 05 48" src="https://github.com/user-attachments/assets/304881c3-b9bf-4c24-8c3b-3177eac4f8dc">

shouldn't User B get CARDMISSINGADDRESS message? Are we shipping the card to the admin?

cc @mountiny @MariaHCD

**Comment by koko57** [comment]
ok, seems like we didn't cover generating LHN alternate text with taking into account if user adds his details or not. I will prepare a PR for that

**Comment by koko57** [comment]
<img width="857" alt="Screenshot 2024-09-13 at 17 57 05" src="https://github.com/user-attachments/assets/c3309811-7796-4093-9fd4-bcca454d593e">
 maybe we should update message text from the BE - now it should be shipping address not mailing address

**Comment by koko57** [comment]
PR opened https://github.com/Expensify/App/pull/49177

Can we use display name instead of handle in LHN, copied message and Report Screen header?

<img width="372" alt="Screenshot 2024-09-13 at 20 52 58" src="https://github.com/user-attachments/assets/8a6b42ed-0b26-4ab5-9b97-2819b932fb52">
<img width="595" alt="Screenshot 2024-09-13 at 20 53 06" src="https://github.com/user-attachments/assets/2376787c-1e88-4dc3-b9a8-eadea040645e">
<img width="601" alt="Screenshot 2024-09-13 at 20 53 20" src="https://github.com/user-attachments/assets/ecbad984-f68f-4ffa-b9dd-927c2476a298">

**Comment by mountiny** [comment]
Thanks for a quick worked, reviewed the PR and requested some small changes

**Comment by koko57** [comment]
@mountiny changes applied

**Comment by mountiny** [comment]
I believe this was all handled with the project team so we can close the issue
