### ISSUE TITLE
[HybridApp] In development, opening the new experience shows the boot splash and doesn't load

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#49140]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @arosiclair
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1726157922153189

## Action Performed:

1. Cloned Mobile-Expensify repo
2. Follow the [README](https://github.com/Expensify/Mobile-Expensify/blob/main/README.md) to setup the HybridApp
3. Enroll into the new experience by running the following snippet in the OldDot JS console:
```javascript
NVP.set('tryNewDot', {classicRedirect: {dismissed: false}});
```
5. Run the app on an iOS/Android device
6. Log into the enrolled user

## Expected Result:
The app loads and shows the new experience LHN

## Actual Result:
The boot splash shows and never disappears

## Workaround:
None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/2bd9a48c-9d5d-44cd-8cee-ec5ea847a1d1" width="300" />

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
We did some troubleshooting in slack [here](https://expensify.slack.com/archives/C036QM0SLJK/p1726157922153189), but no solutions found yet. cc @Julesssss 

At a minimum, we're missing instructions on adding `Mobile-Expensify/react-native/.env`. But even adding that doesn't fix the issue.

@staszekscp @war-in @AndrewGable it sounds like you guys are the only ones successfully running the HybridApp. Can any of you take a look? Ideally, we should be able to just clone `Mobile-Expensify`, follow the instructions and be good to go for HybridApp dev.

**Comment by Julesssss** [comment]
@mateuuszzzzz [noticed](https://expensify.slack.com/archives/C036QM0SLJK/p1726481209524089?thread_ts=1726157922.153189&cid=C036QM0SLJK) today that the react-native submode commit was outdated. This should be the breakthrough we were hoping for 🎉

**Comment by Julesssss** [comment]
Just noting there is an outstanding issue with `live-markdown`, so engineers need to checkout the prior commit within react-native: `d5cfecfc53a`

**Comment by war-in** [comment]
Bump to @Julesssss comment
Developers should use ND (submodule) with `16415328f9462eb4e9a8cd0099833d29948f1544` commit

**Comment by war-in** [comment]
https://github.com/Expensify/Mobile-Expensify/pull/13122 Should fix the issue

**Comment by arosiclair** [comment]
I don't think this is done. Has anyone completed the repro steps and confirmed the new experience loads? It doesn't look like it from the PR we just merged or the slack conversation. We also haven't updated the HybridApp instructions to include steps for adding a `.env`.

**Comment by Julesssss** [comment]
@arosiclair nope, thanks for calling this out.

This morning I switched my local builds to the latest commit and will report back.

**Comment by war-in** [comment]
Hi 👋 @arosiclair I went through the reproduction steps and I can confirm the issue with infinite bootsplash is fixed (it works fine for me). That's why I suggested to close the issue

However, I noticed a few inconveniences while setting up the repo. This is the list:
- the `main.jsbundle.map` file is not created automatically for the `Debug` build which results in a failing build
    - workaround: run the `Release` build first
- I was not able to correctly build iOS with the `npm run ios` command
    - workaround: build with Xcode

Thoughts:
- the build commands should be updated/repaired
- the `main.jsbundle.map` issue should be fixed
- README should contain more details on troubleshooting a `.env` configuration

Please share your thoughts too and let me know if the infinite bootsplash issue is gone 🙏 

cc @arosiclair @Julesssss

**Comment by arosiclair** [comment]
Just tested with `npm run ios` and it worked with the latest changes. I did have to kill and then relaunch the app to get it to connect to Metro. That has also been an issue with NewDot standalone so I think we can do nothing for that issue.

> Thoughts:
> - the build commands should be updated/repaired
> - the main.jsbundle.map issue should be fixed
> - README should contain more details on troubleshooting a .env configuration

Agreed 👍. I'll post a PR to add instructions on the .env

**Comment by war-in** [comment]
> Agreed 👍. I'll post a PR to add instructions on the .env

Amazing, thank you!
You can also be interested in [this](https://github.com/Expensify/Mobile-Expensify/pull/12926) PR where @mateuuszzzzz is adding `.env` configuration into HybridApp

**Comment by arosiclair** [comment]
PR is code complete but held atm

**Comment by arosiclair** [comment]
Still held

**Comment by arosiclair** [comment]
README updates are in this is all done.
