### ISSUE TITLE
Workspace-In workspace chat, Employee invite message with @new gmail id are shown as hidden.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49154]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Launch app
2. Create a workspace - invite an user
3. In invite message enter new gmail user id and new expensifail user id with @ before.
4. Send invite
5. Log in mweb, as employee
6. Open WS chat
7. Note employee invite message

## Expected Result:
In workspace chat, Employee invite message with @new gmail id must not be shown as hidden.

## Actual Result:
In workspace chat, Employee invite message with @new gmail id are shown as hidden.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/158c0737-1384-4d23-bd2f-27519cb79e8c

https://github.com/user-attachments/assets/e1b8bf94-2419-499d-977f-0726279307be

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
reproducing today!

**Comment by dylanexpensify** [comment]
I believe this is expected until the invite is accepted
