### ISSUE TITLE
[Payment Due 4 Oct] [$250] Workspace connected to integration (NetSuite) should not allow editing of GL codes on imported tags.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49179]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726160556242179

## Action Performed:
1. User have Control workspace connected to Netsuite
2. Select the workspace from settings(Connected to Netsuite)
3. Click Tags > Classifications > Accessories
4. Add GL code and save
5. Resync the connection
6. Repeat step 3 
## Expected Result:
Shouldn't allow adding a GL code for imported Tags
## Actual Result:
Able to add GL code for imported code
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/096ba915-9f83-4006-a6e0-2082d1407743)

![Snip - (2) New Expensify - Google Chrome](https://github.com/user-attachments/assets/06872a0c-e37f-417a-9f15-3e3b9a9576c7)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836971613968760708</li>
        <li>Upwork Job ID: 1836971613968760708</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104092521</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by twisterdotcom** [comment]
I think the Expected and Actual result are incorrect here. We just shouldn't allow adding a GL code for imported Tags. We shouldn't persist them after sync.

**Comment by RachCHopkins** [comment]
Yeah I will update that GH title, it's not quite right.

**Comment by RachCHopkins** [comment]
### Expected Result:
Shouldn't allow manual adding a non-imported GL code

### 
Actual Result:
Able to add GL code manually

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Able to add GL code for imported code

### What is the root cause of that problem?
We always allow the user to edit the GL code without checking whether we've connected to an accounting or not.

https://github.com/Expensify/App/blob/b69577a55bc536a411d8c1e51fc47fc0fc00d389/src/pages/workspace/tags/TagSettingsPage.tsx#L146-L149
### What changes do you think we should make in order to solve the problem?
We should use `PolicyUtils.hasAccountingConnections` function to check the workspace has an accounting or not. Then we can pass `interactive` prop as this check here. We can also display the right icon as lock icon

```
const hasAccountingConnections = PolicyUtils.hasAccountingConnections(policy);
iconRight={hasAccountingConnections ? Expensicons.Lock : undefined}
interactive={!hasAccountingConnections}
```
https://github.com/Expensify/App/blob/b69577a55bc536a411d8c1e51fc47fc0fc00d389/src/pages/workspace/tags/TagSettingsPage.tsx#L146-L149

OPTIONAL: We can also display the not found page for `TagGLCodePage` if we've connected to an accounting.

We can do the same fix for category GL code if we should also not allow adding them.
### What alternative solutions did you explore? (Optional)

**Comment by RachCHopkins** [comment]
Hmmm. I just went to reproduce this, and it looks like we are not wiping the default categories and replacing them with the NetSuite chart immediately either. I had to do a subsequent sync to bring in the NetSuite categories. 

I also cannot see the Tags at all, despite setting it to import 3 different kinds. If I try to enable them from the workspace, it tells me they are managed from the integration. But it doesn't actually show what has been imported.

![image](https://github.com/user-attachments/assets/4da88e5a-230d-4e22-bd6e-505eee3858d8)

![image](https://github.com/user-attachments/assets/295b1cae-d3ac-43eb-884d-57bc682e03ed)

![image](https://github.com/user-attachments/assets/498502a2-7155-4422-8917-09b53124d67f)

![image](https://github.com/user-attachments/assets/4da88e5a-230d-4e22-bd6e-505eee3858d8)


I think we might have a number of problems, bigger than just appending tags.

**Comment by RachCHopkins** [comment]
Posted in Wave-Control channel for some clarity. https://expensify.slack.com/archives/C06ML6X0W9L/p1726160568530669

**Comment by RachCHopkins** [comment]
We have a number of problems here, just confirming if I need to separate them out on to two more bug reports.

**Comment by RachCHopkins** [comment]
Ok, I have done two more bug reports, so we can just focus on the appending tags here.

**Comment by RachCHopkins** [comment]
Commenting re the proposal above - this is relevant to all connections, not just NetSuite.

**Comment by c3024** [comment]
@mkzie2's [proposal](https://github.com/Expensify/App/issues/49179#issuecomment-2352026148) looks good to me.

It should be applied for all connections as specified above.
>OPTIONAL: We can also display the not found page for TagGLCodePage if we've connected to an accounting.

Agreed.

I think we should not allow editing GL codes for Categories also as suggested in his proposal. This needs to be confirmed.

🎀 👀 🎀 C+ Reviewed

**Comment by RachCHopkins** [comment]
Automation is borked on this.

@c3024 what's the payment date on this one? Can you do the checklist please?

@mkzie2 did you have an offer to accept in Upwork?

**Comment by c3024** [comment]
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #43155 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/43155/files#r1780496384
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

### Regression test proposal
1. Create a workspace
2. Click on "More features" in the workspace settings page left hand panel
3. Scroll down and go to "Organize" section and switch on the "Tags" switch
4. Scroll down and switch the "Accounting" switch to on
5. Click on "Accounting" from the left hand panel
6. Click on "Netsuite"
7. Upgrade the workspace to Control if prompted
8. Complete the "Netsuite" connection flow
9. Click on the 3 dot menu on the "Netsuite" account added and click on "Sync now"
10. Go to "Tags" and click on any tag
11. Verify that the GL code option is disabled in the opened tag settings page

**Comment by c3024** [comment]
Payment is due on 4-Oct.

**Comment by mkzie2** [comment]
> @mkzie2 did you have an offer to accept in Upwork?

@RachCHopkins Hi not yet, can you please send the offer to my account https://www.upwork.com/freelancers/~019f73367b03c6d784

Thanks in advance

**Comment by RachCHopkins** [comment]
[Offer](https://www.upwork.com/nx/wm/offer/104205068) sent @mkzie2

**Comment by mkzie2** [comment]
@RachCHopkins I have accepted

**Comment by RachCHopkins** [comment]
Thanks @mkzie2 will action the payment on the 4th!

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @mkzie2 to be paid $250 via Upwork
- Contributor+: @c3024 to be paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~021836971613968760708)

**Comment by RachCHopkins** [comment]
Contributors have been paid, the contracts have been completed, and the Upwork post has been closed.
