### ISSUE TITLE
[HOLD FOR PAYMENT 9/26] [Search v2.3] - 3-dot menu is always at fixed position instead of right above the saved search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49206]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48566
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click Filters.
4. Add a few filters.
5. Click Save search.
6. Repeat Step 3 to 5 a few times to create more saved searches until the list is scrollable.
7. Click 3-dot menu next to the last saved search.

## Expected Result:
3-dot menu should be right above the selected saved search.

## Actual Result:
3-dot menu is always at the fixed position instead of right above the selected saved search.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1440" alt="Bug6603097_1726280758510!Screenshot_2024-09-14_at_10 22 48" src="https://github.com/user-attachments/assets/be96fb05-2858-44b2-a9e7-122d177cd6bc">

https://github.com/user-attachments/assets/b2b3bc05-a4c2-46a6-994b-228267a5c166

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by ChavdaSachin** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Saved search - 3-dot menu is always at fixed position
### What is the root cause of that problem?
- Anchor position passed here for the threedot menu here is fixed
https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/pages/Search/SearchTypeMenu.tsx#L115
### What changes do you think we should make in order to solve the problem?
- we should pass dynamic position for the same as we don on other pages
### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment]
Demoting to NAB. @dominictb can you work on a fix?

**Comment by ChavdaSachin** [comment]
@luacmartins could I work on this? Since I was the first to propose the same solution but just didn't include the whole code and including code isn't necessary for the proposal I guess.

**Comment by CortneyOfstad** [comment]
Issue was deployed production 4 days ago, making the payment date 9/26 — adjusting the title!

**Comment by CortneyOfstad** [comment]
@dominictb — I sent you a payment offer [here](https://www.upwork.com/nx/wm/offer/104158999), please let me know once you accept and I can get that paid ASAP. Thanks!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@dominictb — paid $250 via Upwork
