### ISSUE TITLE
[HOLD for payment 2024-09-27][Search v2.3] - Same saved search can be created at most twice

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49205]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click Filters.
4. Select Merchant and add search query (issue is reproducible with Merchant filter and not Date, Total filter).
5. Click Save search.
6. Click 3-dot menu next to the saved search > Rename.
7. Enter a custom name and save it.
8. Click Filters > Save search.
9. Note that it creates another saved search.
10. Rename the second saved search.
11. Go back to the first saved search.
12. Click Filters > Save search.
13. Note that it does not create a new search but changes the name of second saved search back to default.

## Expected Result:
In Step 9, it will not create another same saved search because the filters are not modified.

## Actual Result:
In Step 9, it creates another same saved search when the filters are not modified.

If Step 9 is the correct behavior, Step 13 shows a different result because user cannot create the same third saved from the first saved search as it changes the name of second saved search back to default.

This issue is not reproducible when Date and Total filter are used.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/46e041c2-abf9-4dd0-a0a5-1c22a85ce0be

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by luacmartins** [comment]
This is coming from [this PR](https://github.com/Expensify/App/pull/48566). Gonna demote it to NAB, since it's not breaking any functionality. @lakchote we need to figure out why the hashes are different in this case.

**Comment by lakchote** [comment]
Not overdue. Awaiting payment.

**Comment by OfstadC** [comment]
## Payment Summary

- @allroundexperts due $250 via Manual request in New Expensify

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
