### ISSUE TITLE
[$50] Saved search - Long list causes overlap with status bar on native, and unscrollable on mweb

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- There is a long list of saved search until the dropdown list is scrollable.

1. Launch New Expensify app.
2. Go to Search.
3. Tap on the dropdown.
4. Note that the selected Expenses tab overlaps with the status bar.
5. Go to staging new dot mobile web.
6. Go to Search.
7. Tap on the dropdown.
8. Note that the page cannot be scrolled on mobile web.

## Expected Result:
In Step 4, the selected Expenses tab will not overlap with the status bar.
In Step 8, the list is scrollable on mobile web.

## Actual Result:
In Step 4, the selected Expenses tab overlaps with the status bar.
In Step 8, the list is not scrollable on mobile web.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6603226_1726299984918!IMG_5007](https://github.com/user-attachments/assets/66b6a151-0d3f-4144-9c81-17932f8221e8)

https://github.com/user-attachments/assets/cfd6bea5-28dc-4e7a-9fc6-80db46a42bed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
@lakchote will address this in a follow up from [his PR](https://github.com/Expensify/App/pull/48566)

**Comment by luacmartins** [comment]
Fixed on staging.

**Comment by luacmartins** [comment]
Reopening to compensate @ishpaul777 $50 since his solution was used to solve this issue.

**Comment by trjExpensify** [comment]
Offer sent to Ishpaul for $50 for the proposal.

**Comment by trjExpensify** [comment]
Paid!
