### ISSUE TITLE
Bank account - "Continue setup" text is smaller than "Start over"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49211]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49173
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Click Connect bank account > Connect manually.
4. Proceed the set up and quit it halfway.
5. Click Connect bank account.

## Expected Result:
"Continue setup" will have the same font style as "Start over".

## Actual Result:
"Continue setup" text is smaller than "Start over".
On production, it uses "Continue with setup" instead of "Continue setup"
This issue also happens in "Yes, let's chat" button during bank account setup.

## Workaround:
Unknoown
## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/540a430b-94eb-4b68-8c17-2a17a89cc360

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CyberAndrii** [comment]
Offending PR: https://github.com/Expensify/App/pull/47238

**Comment by mountiny** [comment]
cc @luacmartins @mkhutornyi as the offending PR

**Comment by luacmartins** [comment]
PR up https://github.com/Expensify/App/pull/49237

**Comment by luacmartins** [comment]
Fixed on staging
<img width="1049" alt="Screenshot 2024-09-16 at 2 52 50 PM" src="https://github.com/user-attachments/assets/2491322b-ea64-4965-8d23-0f0a07fde00e">
