### ISSUE TITLE
Search - Saved filter tool tip is hard to read on dark theme

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49213]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1482@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: App theme should be in dark mode.

1. Navigate to staging.new.expensify.com
2. Navigate to search
3. Click on filter
4. Setup any filter and save it

## Expected Result:
The tooltip is easily readable

## Actual Result:
The tooltip is hard to read on dark theme

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c3b0bf9f-24ad-47bf-8b1c-cdfcd8ae9abc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by luacmartins** [comment]
PR [here](https://github.com/Expensify/App/pull/49231)

**Comment by luacmartins** [comment]
Fixed in staging
<img width="1512" alt="Screenshot 2024-09-16 at 11 51 53 AM" src="https://github.com/user-attachments/assets/2eeba6db-67c9-468f-bf74-51213c0aaa3c">
