### ISSUE TITLE
[HOLD for payment 2024-10-31][Search v2.3] - Unable to rename search with emoji and X:Y format

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49210]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48566
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Open any saved search.
4. Click 3-dot menu next to it > Rename.
5. Enter an emoji and save it.
6. Enter name with X:Y format and save it.
## Expected Result:
User should be able to rename search with emoji and X:Y format.

## Actual Result:
User is unable to rename search with emoji and X:Y format.
The name changes to default name after saving search name with emoji and X:Y format.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/deec28a3-8213-4e9c-95a2-61f000329f3c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by luacmartins** [comment]
This is a pretty rare edge case. Gonna demote it to NAB and we can address it as a follow up.

**Comment by lakchote** [comment]
Wasn't able to work on this today, I've handled the other follow up issues so they can be worked on by external contributors. 
I'll work on it tomorrow.

**Comment by luacmartins** [comment]
PR merged, just waiting on deploy

**Comment by lakchote** [comment]
BZ checklist to be done by @muttmuure and we're done!

**Comment by luacmartins** [comment]
Is payment still pending here? @muttmuure

**Comment by lakchote** [comment]
friendly bump @muttmuure ^

**Comment by muttmuure** [comment]
@mollfpr - $250 via NewDot for C+

**Comment by garrettmknight** [comment]
$250 approved for @mollfpr
