### ISSUE TITLE
mWeb - Workspace - Multiple windows are opened at once before redirecting to workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49214]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/47459
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Click on FAB - New workspace

## Expected Result:
I should be redirected to the workspace settings page.

## Actual Result:
Multiple windows are opened at once before redirecting to workspace settings page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e710d59a-af29-4d03-bac0-f8462bfbf372

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment]
reproducing today!
