### ISSUE TITLE
[HOLD for payment 2024-09-23] [Search v2.3] - List scrolls back to the top after selecting saved search at the bottom of list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49218]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- There is a long list of saved search until the saved search list is scrollable.

1. Go to staging.new.expensify.com
2. Go to Search.
3. Scroll the saved search list to the bottom.
4. Note that the Saved title is also scrolled and hidden.
5. Select a search from the bottom of the list.
6. Note that the list scrolls up and the selected search is hidden.

## Expected Result:
In Step 4, the Saved title should remain on top when the list is scrolled down.
In Step 6, the list will not scroll up after selecting the search at the bottom of the list, or the selected search will move to the top.

## Actual Result:
In Step 4, the Saved title is also scrolled and hidden.
In Step 6, the list scrolls up and the selected search is hidden.
## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b735f25e-a562-4cba-b558-682b0b7c26cf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by luacmartins** [comment]
@lakchote will address this as a follow up to [his PR](https://github.com/Expensify/App/pull/48566)

**Comment by luacmartins** [comment]
@dominictb are you available to work on a fix?

**Comment by luacmartins** [comment]
@dominictb how's the PR coming along?

**Comment by lakchote** [comment]
> @lakchote [PR](https://github.com/Expensify/App/pull/49244) is ready for review.

Thank you, I've assigned a C+ available for review.

**Comment by lakchote** [comment]
Fix has been deployed to staging.

https://github.com/user-attachments/assets/b360b81f-bbfd-45b4-8607-32aa430deb01

Demoting from blocker.

**Comment by lakchote** [comment]
Not overdue. Waiting for payment.

**Comment by luacmartins** [comment]
Bump for payment @anmurali

**Comment by anmurali** [comment]
@dominictb - I need your Upwork profile
@luacmartins - Do we need to pay $250?

**Comment by anmurali** [comment]
@luacmartins @dominictb bump on ^^

**Comment by luacmartins** [comment]
Yes, that's $250 for @dominictb and @rushatgabhane for writing the PR and reviewing, respectively

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane

**Comment by anmurali** [comment]
Waiting on @dominictb

**Comment by luacmartins** [comment]
Waiting on payment

**Comment by lakchote** [comment]
@dominictb could you please give us your Upwork profile in order to pay you?

**Comment by lakchote** [comment]
bump @dominictb for your Upwork profile.

**Comment by anmurali** [comment]
@dominictb - offer is [here](https://www.upwork.com/nx/wm/offer/104652859)

**Comment by lakchote** [comment]
Not overdue. Should we close this?

**Comment by luacmartins** [comment]
Seems like we're all set. Gonna close the issue, please reopen if needed.

**Comment by luacmartins** [comment]
Sorry, I thought that had been handled based on [this comment](https://github.com/Expensify/App/issues/49218#issuecomment-2445732106). My bad 😅

**Comment by lakchote** [comment]
friendly bump @anmurali ^

**Comment by anmurali** [comment]
Paid. Sorry, I thought I already did that as well.
