### ISSUE TITLE
[$250] Add GBRs to tasks that are assigned to you

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#49234]
Problem: When you have tasks assigned to you, we input a GBR in your LHN. When you come into the chat and view the tasks assigned, nothing indicates what is causing the GBR. Thus, it is unclear and confusing users why there is a GBR. 

As a note, we used to use mentions, and thus, they were green. We updated task assignments to use profile photos and that is why there is nothing green anymore. 

Solution: Add a GBR to the top row of the task title when you are assigned th task to match its appearance in other patterns of the product. 

We have mocked this up here. 
![image](https://github.com/user-attachments/assets/a532919d-c1bd-42be-a07a-b2f21a1f1177)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835793359638607411</li>
        <li>Upwork Job ID: 1835793359638607411</li>
        <li>Last Price Increase: 2024-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>cretadn22 | Contributor | 104004979</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by shawnborton** [comment]
I would think so, yes. Those should be vertically centered - the checkbox, the avatar, and the arrow.

**Comment by danielrvidal** [comment]
It looks like there is still progress and @parasharrajat is going to resolve some conflicts tomorrow.

**Comment by danielrvidal** [comment]
My bad! I'm not actually on bug-zero (which is the team that pays these) so @mallenexpensify just assigned a team member to pay it out.

**Comment by mallenexpensify** [comment]
Contributor: @cretadn22 paid $250 via Upwork
Contributor+: @parasharrajat due $250 via NewDot. 

 @parasharrajat , @danielrvidal will regression tests be created elsewhere or are they needed here? 

Daniel, adding the `Bug` or `NewFeature` label will assign a BZ and _they'll know what to do_.  This issue was funked up a bit cuz automation failed which left the `Reviewing` label on the issue so it didn't go overdue.  It should be fixed now.

**Comment by danielrvidal** [comment]
I like the idea of ensuring this is not covered in a regression test. I would think it would be wherever were testing tasks that if one is assigned, we should show the avatar of the assigned person.

**Comment by isabelastisser** [comment]
Payment summary:

Contributor: @cretadn22 paid $250 via Upwork
Contributor+: @parasharrajat due $250 via NewDot. `PENDING`

**Comment by isabelastisser** [comment]
@danielrvidal, I take this as no regression test needs to be created, correct?

> I like the idea of ensuring this is not covered in a regression test.

Closing.

**Comment by danielrvidal** [comment]
Oh sorry! I think we do need to make sure it is updated in the regression test. I typed not but it meant now included in regression test. @isabelastisser can you please make sure the QA team does account for this small change.

**Comment by isabelastisser** [comment]
@parasharrajat, can you please share regression test steps for this issue? Thanks!

**Comment by isabelastisser** [comment]
All set!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
