### ISSUE TITLE
[HOLD for payment 2024-09-27] [$250] Onboarding modal is flashing briefly on transitioning to NewDot via ShortLivedAuthToken

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#49245]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** (examples in the linked slack thread in #wave-collect. 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @anmurali 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1726074674036609

## Action Performed:

_Note: we're still trying to nail down the prerequisites when it comes to the onboardingNVP state, but our [best guess](https://expensify.slack.com/archives/C036QM0SLJK/p1726174521690189?thread_ts=1726074674.036609&cid=C036QM0SLJK) is that it needs to be empty._ 

1. Go to OldDot
2. Click Support
3. Click Concierge to be redirected to NewDot 
4. Observe the brief flash of the onboarding modal 

## Expected Result:
No onboarding modal is shown, user lands in the Concierge DM chat

## Actual Result:
Onboarding route briefly flashes in the URL bar causing the onboarding modal to appear and disappear

## Workaround:
N/A, the modal does disappear again. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
Customer vids from FullStory, so not uploading them here. Refer to these two slack chats in threads for the visual examples: 

https://expensify.slack.com/archives/C036QM0SLJK/p1726079102789129?thread_ts=1726074674.036609&cid=C036QM0SLJK
https://expensify.slack.com/archives/C036QM0SLJK/p1726079241599169?thread_ts=1726074674.036609&cid=C036QM0SLJK 

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835709139570374195</li>
        <li>Upwork Job ID: 1835709139570374195</li>
        <li>Last Price Increase: 2024-09-16</li>
    </ul>
</details>

**Comment by trjExpensify** [comment]
Apols for the noise, @twisterdotcom. GH wouldn't let me assign myself on creation. Swapped you out. 👍

**Comment by mountiny** [comment]
PR merged

**Comment by trjExpensify** [comment]
Dope, thanks!

**Comment by trjExpensify** [comment]
PR is on staging. We can close it out when it hits prod, as no payments will be due here.

**Comment by mountiny** [comment]
@trjExpensify I believe we have to pay @allgandalf $250 for review and testing

**Comment by trjExpensify** [comment]
Ah yes, sorry. I missed that assignment. 👍

**Comment by CyberAndrii** [comment]
Can we revert it 🤔? https://github.com/Expensify/App/pull/49263#issuecomment-2359236679

**Comment by mountiny** [comment]
@allgandalf $250 for their review i believe

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @allgandalf for the review

Offer sent

**Comment by trjExpensify** [comment]
Paid, closing!
