### ISSUE TITLE
Onboarding - Workspace is created when Entering the Business name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49259]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.34-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log into a new account (Use public domain, like Gmail)
2. On the onboarding page go to "Manage my teams expense"
3. Enter business name and Continue
4. Navigate back to "What do you what to do page"
5. Finish the onboarding using The "Something else" Purpose

## Expected Result:
Workspace is not created when onboarding using "Something else" purpose

## Actual Result:
Workspace is created when Entering the Business name. But when navigating back and entering with other "Purpose" The Workspace is still created.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/67cb42dd-ba63-48e7-be5a-19d205f28e8d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment]
I think NAB
Imo it doesn't make sense for the pressing the back button to roll back workspace creation. The only thing that I could see being changed here is delaying when the workspace is created. Currently it's created after the business name is saved, it could be delayed until the user completes the full modal. But I don't think that's a necessary change unless this flow causes a lot of user confusion.
