### ISSUE TITLE
Room - Join button re-appears when login via deep link with Join button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49252]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.34-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4962361&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** gocemate+a2127@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Logout of New Expensify
2. Navigate to the following link - https://staging.new.expensify.com/r/6776919265133947
3. Verify the conversation loads and messages are displayed
4. Scroll to the top of the conversation
5. Tap on Join button
6. Enter credentials and complete logging process

## Expected Result:
Join button should not be present since user is logged by taping the Join button

## Actual Result:
Join button appears when user navigate to public room even user is logged by tapping Join button

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b54695a2-8cfc-4220-9d97-c24ac0c0f80c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by adelekennedy** [comment]
I can't reproduce this one on Chrome v9.0.37-0
