### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] Long State/Province text can not be saved on Address modal - Update the FE to match the 32 limit for the state field here for foreign addresses

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49264]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4963582&group_by=cases:section_id&group_order=asc&group_id=229064
**Email or phone of affected tester (no customers):** gocemate+a2148@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to Settings -> Profile -> Personal details
2. Click on Address> Fulfil requested fields with non-USA details> Save
3. Click on Address> Add extra text in State/Province field> Save

## Expected Result:
Edited State/Province info should update since user is allowed to add 50 characters

## Actual Result:
Long State/Province can not be saved on Address modal

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1ba8ed5a-388a-41cf-9273-25f949f90a9a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836427775692517927</li>
        <li>Upwork Job ID: 1836427775692517927</li>
        <li>Last Price Increase: 2024-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104123691</li>
<li>nyomanjyotisa | Contributor | 104123692</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
Internal references:

- The 32 character limit for foreign addresses comes from [here](https://github.com/Expensify/Web-Expensify/blob/6813b9f3b333d16f27a56d53297c47523d35e7d2/site/component/user/AddressForm.jsx#L91) I think. 
- From the PR that introduced it [here](https://github.com/Expensify/Web-Expensify/pull/30212), it sounds like it’s a limit enforced by Marqeta for foreign states:
  - "Marqeta now allows state for foreign addresses to be 32 characters long so we should update our form to match that so international users can easily order their E-cards"

So let's update the FE to match the BE's 32 character limit for states with foreign addresses. 👍

**Comment by OfstadC** [comment]
## Payment Summary

- @nyomanjyotisa paid $250 via Upwork
- @rayane-djouah paid $250 via Upwork
