### ISSUE TITLE
[$250] Web - Sage - Two console errors appear when downloading the Expensify package for Sage Intacct

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.34-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Click on "Sage Intacct" and upgrade the workspace to Control when asked
7. Click on the "Got it, thanks" button
8. Click on "Download the Expensify package for Sage Intacct"
9. Click on "Save" or "Cancel"

## Expected Result:
There shouldn't be any console errors.

## Actual Result:
Two console errors appear when downloading the Expensify package for Sage Intacct.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[1609_1.txt](https://github.com/user-attachments/files/17012095/1609_1.txt)

https://github.com/user-attachments/assets/64c22b4b-f0ce-48d7-9ec4-1f02c08d1825

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835811720150989795</li>
        <li>Upwork Job ID: 1835811720150989795</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104115002</li>
<li>Krishna2323 | Contributor | 104115003</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by lschurr** [comment]
@shubham1206agra please review the proposal

**Comment by lschurr** [comment]
@shubham1206agra Can you accept [the offer](https://www.upwork.com/nx/wm/offer/104115002)?

**Comment by lschurr** [comment]
Payment summary:

- Contributor: $250 @Krishna2323 (Paid in [Upwork](https://www.upwork.com/nx/wm/workroom/38510670/overview))
- Reviewer: $250 @shubham1206agra (Offer pending in Upwork)

**Comment by lschurr** [comment]
This is done!
