### ISSUE TITLE
[HOLD for Payment 2024-10-10][$250] NetSuite - "This field is required" message displayed instead of "Please select an option"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49267]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Custom lists
9. Click on the "Add custom list" button
10. Click on "Name" and select any of the options
11. Click on the "Next" button
12. Type any ID name and click on the "Next" button
13. Click on the "Next" button without making a selection

## Expected Result:
The message should be "Please select an option above.".

## Actual Result:
"This field is required." message displayed instead of "Please select an option above." in custom list. Custom segments/records has a similar selection where the message is "Please select an option above.".

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c684d014-7085-4c02-9a5e-de12f73740c6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838993006619000838</li>
        <li>Upwork Job ID: 1838993006619000838</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment]
Opened up to the community. Pending proposal review.

**Comment by luacmartins** [comment]
Shouldn't the error message be displayed under the field with the error instead of the bottom of the page as well?

**Comment by luacmartins** [comment]
Thanks for confirming @cretadn22! In that case the proposal looks good.

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: @cretadn22 $250
 - Reviewer: @mananjadhav $250

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav

**Comment by mananjadhav** [comment]
@JmillsExpensify Is the payout done for @cretadn22 ?

I think we didn't decide on the error message during the NetSuite integration. Hence, I don't think we have any offending PR. I also think we don't need a regression test for this one. Hence, once the payout is done, we can close this one out?

**Comment by JmillsExpensify** [comment]
Sounds good, will do.
