### ISSUE TITLE
[Pending / Scanning] Update Submit Flow when preventing submissions for pending / scanning expenses

### ISSUE THREAD

**Issue by grgia** [Expensify/App#49272]
This is related to https://github.com/Expensify/App/issues/49019

For the case of Single-Expense reports on policies that are NOT instant submit (i.e. the Submit button is on reports), we need to alert the user somehow that they must wait until the expense is complete before submitting.

These are the requirements for this button:
- Policy is not instant submit
- The report only contains pending/scanning expenses (else this would be fixed by https://github.com/Expensify/App/issues/49019) 

The discussion is ongoing here: https://expensify.slack.com/archives/C049HHMV9SM/p1726494513454089?thread_ts=1725990321.902219&cid=C049HHMV9SM

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by dannymcclain** [comment]
Interesting Melvin... 2 different designers eh? 🤔

**Comment by shawnborton** [comment]
Wow we're gonna design this thing so hard!

**Comment by garrettmknight** [comment]
Still discussing this one [in thread](https://expensify.slack.com/archives/C049HHMV9SM/p1726681110551009?thread_ts=1725990321.902219&cid=C049HHMV9SM).

**Comment by dannymcclain** [comment]
🤔 Looks like this issue has `Daily` and `Weekly` labels but I'm honestly not sure which is the right one for this.

**Comment by garrettmknight** [comment]
I think I'd call it `Weekly` for the moment until we can figure out what the actual behavior should be.

**Comment by garrettmknight** [comment]
Added some points in the thread that I'll check in on tomorrow with Georgia.

**Comment by garrettmknight** [comment]
Setting @grgia as ⭐ since she's got more context, but we _think_ that this isn't happening again.

**Comment by grgia** [comment]
I think we'll end up able to close this out. We can hold on the issue that is moving pending transactions to a new report

**Comment by garrettmknight** [comment]
K, putting this on hold for https://github.com/Expensify/App/issues/49019 - please update if there's a different issue.

**Comment by garrettmknight** [comment]
Still holding on https://github.com/Expensify/App/issues/49019

**Comment by grgia** [comment]
Still holding on https://github.com/Expensify/App/issues/49019 - PR is in final review

**Comment by shawnborton** [comment]
What's the latest update here?

**Comment by grgia** [comment]
@shawnborton 
We've merged the PR that moves pending / scanning expenses to a new report

**Comment by shawnborton** [comment]
Sounds good, thanks for the update!

**Comment by grgia** [comment]
@garrettmknight @shawnborton do we still need to make any updates here given pending/scanning receipts are moved to different reports? cc @youssef-lr

**Comment by shawnborton** [comment]
Hmm I'm not too sure how to answer that one, curious what @garrettmknight might think there.

**Comment by garrettmknight** [comment]
I think we landed on 'do nothing' [here](https://expensify.slack.com/archives/C049HHMV9SM/p1727284437871159?thread_ts=1725990321.902219&cid=C049HHMV9SM), relying on 'Next Steps' for the report to tell people what to do and potentially to explain why there isn't a 'submit' option. So I'd say let's close!

**Comment by grgia** [comment]
Closing per https://github.com/Expensify/App/issues/49272#issuecomment-2452413132
