### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] Use new ValidateCodeActionModal component in as many places as possible

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#49270]
We are requiring a validation of the primary login using magic code in more actions now, and as such, we are repeating the component that handles such login. We created the ValidateCodeActionModal component, but there are some places like Copilot and verifying secondary login that does not use this modal.

Let's use this new component and remove any other usages that could lead people to reintroduce the wrong usage/ component.

Discussed here https://expensify.slack.com/archives/C01GTK53T8Q/p1726493895290119?thread_ts=1726483475.882029&cid=C01GTK53T8Q

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835679560526385104</li>
        <li>Upwork Job ID: 1835679560526385104</li>
        <li>Last Price Increase: 2024-09-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by mountiny** [comment]
Hmm no upwork jobs

**Comment by mountiny** [comment]
We will handle this with the bois

**Comment by hungvu193** [comment]
Any updates? @getusha 😄 . Let me know you if have any question.

**Comment by getusha** [comment]
@hungvu193 found some edge cases, i'll try to finalize today

**Comment by mountiny** [comment]
@hungvu193 @getusha what is your ETA for the PR?

**Comment by hungvu193** [comment]
Draft PR is up, https://github.com/getusha/App/tree/reuse-validate-code-action-modal, I'm waiting for @getusha response.

**Comment by getusha** [comment]
I'll update today

**Comment by hungvu193** [comment]
Hey @getusha, any updates on our last convo 😄 ?

**Comment by hungvu193** [comment]
Still in progress

**Comment by jliexpensify** [comment]
Just a heads up that I am OOO from the 3rd - 14th, but am keeping myself assigned as I don't believe any payments will need to occur before then.

@mountiny feel free to assign a new B0 if needed though!

**Comment by hungvu193** [comment]
@getusha Let's wrap it up this week 😄

**Comment by mountiny** [comment]
+1

**Comment by hungvu193** [comment]
Not overdue, PR is still in progress.

**Comment by jliexpensify** [comment]
Hi, I'm back! Am I correct in saying this hasn't been deployed yet @hungvu193 @getusha?

**Comment by hungvu193** [comment]
> Hi, I'm back! Am I correct in saying this hasn't been deployed yet @hungvu193 @getusha? 

Not yet. It's still in progress but we're close

**Comment by mountiny** [comment]
Using this thread to get this merged sooner https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1729158252062769

**Comment by mountiny** [comment]
@getusha @hungvu193 Great job getting that PR merged.

an we now do a follow up here to make sure the Request new code will always change to the 30 seconds countdown so users cannot accidentally request the code multiple times in a row?

**Comment by arosiclair** [comment]
Just found this issue. Is there any plan to use the `ValidateCodeActionModal` in the pay someone and add VBBA flows? I'm working on fixing those with the `VerifyAccountPage`, but it sounds like we should use the modal instead.

**Comment by mountiny** [comment]
All the deploy blockers were handled.

@arosiclair I think the plan is in general to use the ValidateCodeActionModal everywhere we will require the magic code verification, yes

**Comment by arosiclair** [comment]
Cool I will still fix the issue with forced log out while validating but let you guys refactor those Pay Someone and VBBA flows in this issue 🙏

**Comment by mountiny** [comment]
This was a refactoring issue so not a bug to fix really, we do not need to create regression tests for this one and as such I dont think we need to fill in the checklist either

**Comment by hungvu193** [comment]
Are we going to create a follow up PR to address the countdown timer?

**Comment by jliexpensify** [comment]
Payment Summary

- C: @hungvu193 $250 (to be paid via ND)
- C+: @getusha $250 (to be paid via ND)

**Comment by jliexpensify** [comment]
@mountiny before I close this, are we also paying for the follow-up PR in this payment? Or will that be handled separately? 

If so, is that amount also $250?

**Comment by mountiny** [comment]
We can pay it here, there was no new issue for that.

I would say that we should have included that in the first pr so I would vote for partial reward for the second one so $375 total each for @hungvu193 and for @getusha

**Comment by hungvu193** [comment]
LGTM as well 😄

**Comment by jliexpensify** [comment]
Great, thanks Vit - [updated Payment Summary here.](https://github.com/Expensify/App/issues/49270#issuecomment-2434534311)

**Comment by garrettmknight** [comment]
$375 approved for @hungvu193

**Comment by garrettmknight** [comment]
$375 approved for @getusha
