### ISSUE TITLE
Expensify card - Connect bank account RHP twitch opening

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49285]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.35-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/issues/48204
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:**  Applause-Internal team

## Action Performed:
Precondition: use expensifail account. WS with enabled Expensify card feature.

1. Open workspaces > Expensify card
2. Click on 'Issue new card'

## Expected Result:
Connect bank account RHP opens smoothly.

## Actual Result:
Connect bank account RHP opens with twitch.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/85d25c90-44b2-40a7-90d5-ec13bb8547fa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by twisterdotcom** [comment]
I can't recreate this. Going to close.
