### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] Category rules - Approver field is blank for a moment after editing category name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49293]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Rules and Workflows are enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click on any category.
4. Click Approver.
5. Select any user.
6. Click Name.
7. Edit the name.

## Expected Result:
Approver field will not go blank after editing category name.

## Actual Result:
Approver field is blank for a moment after editing category name.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3d82a3f9-4661-4c0c-9aeb-f283ebdeb547

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837011004719364383</li>
        <li>Upwork Job ID: 1837011004719364383</li>
        <li>Last Price Increase: 2024-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104131224</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Category rules - Approver field is blank for a moment after editing category name

### What is the root cause of that problem?
We use category name to get the approver here
https://github.com/Expensify/App/blob/00bc167940607f1418109f00e2b4e2d7d4ae858b/src/pages/workspace/categories/CategorySettingsPage.tsx#L86
but the policy rule takes time to get updated with the new category name
### What changes do you think we should make in order to solve the problem?

We can use previous category name to get a fallback in case the approver with current category name doesn't exist 
```
const previousCategoryName = usePrevious(categoryName);

    const approverText = useMemo(() => {
        const categoryApprover = CategoryUtils.getCategoryApprover(policy?.rules?.approvalRules ?? [], categoryName);
        const prevApprover = CategoryUtils.getCategoryApprover(policy?.rules?.approvalRules ?? [], previousCategoryName);
        return categoryApprover ?? prevApprover ?? '';
    }, [categoryName, policy?.rules?.approvalRules]);
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
[Updated](https://github.com/Expensify/App/issues/49293#issuecomment-2353751940)

**Comment by stephanieelliott** [comment]
Hey @thesahindia can you please review [this proposal](https://github.com/Expensify/App/issues/49293#issuecomment-2353751940)?

**Comment by stitesExpensify** [comment]
@thesahindia do you have one of the 3 solutions presented by @FitseTLT that you prefer?

**Comment by stitesExpensify** [comment]
Great, let's go with that @FitseTLT

**Comment by stephanieelliott** [comment]
Hey @thesahindia can you complete the BugZero checklist please?

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @FitseTLT $250 via Upwork - PAID 
 - Contributor+: @thesahindia $250 via ND payments - please request! 
 
 Upwork job is here: https://www.upwork.com/jobs/~021837011004719364383

**Comment by stephanieelliott** [comment]
> Hey @thesahindia can you complete the BugZero checklist please?

^^ bump @thesahindia

**Comment by stephanieelliott** [comment]
Thanks! Test rail case here: https://github.com/Expensify/Expensify/issues/436519

**Comment by garrettmknight** [comment]
$250 paid for @thesahindia
