### ISSUE TITLE
Refactor string comparisons in GitHub actions to use `fromJSON` instead

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#4929]
Coming from [this PR](https://github.com/Expensify/App/pull/4927) – follow-up to implement the best practices for handling json-encoded values across our workflows.

**Comment by botify** [comment]
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1214907189) to staging by @Gonals in version: 1.0.94-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1218876549) to production by @yuwenmemon in version: 1.0.95-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅
