### ISSUE TITLE
[$250] Category CSV - Max Expense Amount in downloaded CSV displays amount without decimal point

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49294]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Rules are enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click on any category.
4. Click Flag amounts over.
5. Enter amount with decimals (12.34).
6. Save it.
7. Dismiss RHP.
8. Click 3-dot menu > Download CSV.
9. Open the file.

## Expected Result:
Max Expense Amount field in the downloaded CSV should display the amount correctly with decimal point.

## Actual Result:
Max Expense Amount field in the downloaded CSV displays the amount without decimal point.
When the same category list is downloaded on Old Dot, it does show the amount with decimal point correctly.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/546c5437-ae37-4677-9281-65242230e040

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836046116299332518</li>
        <li>Upwork Job ID: 1836046116299332518</li>
        <li>Last Price Increase: 2024-09-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by IuliiaHerets** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
cc @marcaaron for this one too, as I think this is also related to the expense rules doc

**Comment by marcaaron** [comment]
I'm not familiar with that CSV export feature. We should maybe tag whoever worked on that one?

I'll confirm the backend is working correctly for this in the meantime.

**Comment by marcaaron** [comment]
So, I think it's indirectly related. There's nothing wrong with the data. We just need to be converting the "cents" values back into "dollars" before exporting to the CSV. Should be an easy fix for whoever knows how this works already.

**Comment by marcaaron** [comment]
Seems like [this issue](https://github.com/Expensify/App/issues/47927) is where this feature was implemented @rlinoz maybe can help take a look since I think the backend is where this change would need to happen if I'm understanding the problem correctly.

**Comment by joekaufmanexpensify** [comment]
Got it, sounds good. Thanks Marc!

**Comment by rlinoz** [comment]
Marc is right, I will take a look!

**Comment by joekaufmanexpensify** [comment]
Sweet. TY!

**Comment by joekaufmanexpensify** [comment]
PR(s) in review

**Comment by rlinoz** [comment]
This is in prod now
