### ISSUE TITLE
[HOLD for payment 2024-10-14] [$250] Categories - RBR appears next to workspace after selecting the deleted spend category offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Workspace settings > Categories.
3. Go offline.
4. Delete "Travel" category (because it is linked to "Airlines" spend).
5. Click Settings.
6. Click Airlines.
7. Click Uncategorized.
8. Go online.
9. Go back to workspace list.

## Expected Result:
There will not be RBR next to the workspace.

## Actual Result:
RBR appears next to the workspace after selecting the deleted spend category offline, but there is no error message anywhere.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cf69d7db-ea31-4241-914b-bafec2ade9e1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838337226742068992</li>
        <li>Upwork Job ID: 1838337226742068992</li>
        <li>Last Price Increase: 2024-09-23</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104134153</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
Ok, so we are saying that if you set an MCC default, then delete the category you set, it shows as Uncategorised and has a red dot with no error message. 

I would think that if we think that people will be deleting their categories offline, and causing the MCC default to break, the solution would be displaying an error of some variety. 

I don't think this is a "real" problem that users will encounter, but hey, let's pretend they are working from somewhere with dodgy reception and they happen to be doing major surgery on their categories, then it should behave the same as it would if they were online. 

Unfortunately I can't seem to work out what that is. @IuliiaHerets how are you seeing the MCC defaults? Is there a prerequisite that's not on the OP there? I can't see this on Collect or Control. 

![image](https://github.com/user-attachments/assets/f7ebf5c2-c8e7-45a2-beed-afe43db6cdbe)

**Comment by RachCHopkins** [comment]
Asked in [Slack](https://expensify.slack.com/archives/C9YU7BX5M/p1726804509477899).

**Comment by RachCHopkins** [comment]
Ok, I still can't replicate this. I'm going to have to assume that it's ok.

**Comment by s77rt** [comment]
@Krishna2323 Thanks for the proposal. The RCA and the solution makes sense to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/49295#issuecomment-2353812292)

**Comment by NikkiWines** [comment]
Agreed, @Krishna2323's proposal looks good 👍

**Comment by s77rt** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/48391
- The offending PR has been commented on: https://github.com/Expensify/App/pull/48391#discussion_r1797033508
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by RachCHopkins** [comment]
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt
