### ISSUE TITLE
[HOLD for payment 2024-10-11] [$250] iOS - Search - Sluggish animation when selecting a different type for the second time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49296]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49058
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Search.
3. Tap on the dropdown.
4. Tap Chats.
5. Open the dropdown.
6. Select Invoices.

## Expected Result:
The animation should be smooth when selecting a different type.

## Actual Result:
The animation is sluggish after selecting a different type for the second time.
Both "Expenses" and "Chats" are highlighted when selecting Invoices.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/32fcf5b8-d79e-49ab-8403-57eb49a0bed5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836327300747021225</li>
        <li>Upwork Job ID: 1836327300747021225</li>
        <li>Last Price Increase: 2024-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 104127739</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by IuliiaHerets** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- iOS - Search - Sluggish animation when selecting a different type for the second time

### What is the root cause of that problem?
- We does not use ```shouldCallAfterModalHide: true``` in this:
https://github.com/Expensify/App/blob/14b99ca0a12e9686818bc3e937f091199de69750/src/pages/Search/SearchTypeMenuNarrow.tsx#L71
### What changes do you think we should make in order to solve the problem?
- We should add ```shouldCallAfterModalHide: true``` to make sure the modal is closed successfully before running the remaining logic.

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
@deetergp Please help review [my proposal](https://github.com/Expensify/App/issues/49296#issuecomment-2359524858) since C+ has reviewed it. Thanks.

**Comment by truph01** [comment]
[PR](https://github.com/Expensify/App/pull/49736/) is ready

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
