### ISSUE TITLE
Task – Error appears if complete task as assignee (external group user) after reassign

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49300]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4969164
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as user A
3. Open group chat where user B is not a member
4. Create a task and assign to user B
5. Log in as user B and open task details
6. Click on assignee and reassign task to another external user
7. Click on assignee and reassign task to you
8. Complete the task

## Expected Result:
Task is completed

## Actual Result:
“You don't have permission to take the requested action.” error appears. But user is able to complete task without error when open it first time.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0804e103-b94e-4d6b-970a-b68280cb0fc8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
BE bug returning 
```
 "onyxMethod": "merge",
            "key": "report_8260924354515671",
            "value": {
                "errorFields": {
                    "completeTask": {
                        "1726590612455943": "Report no longer exists"
                    }
                }
```

**Comment by OfstadC** [comment]
If user B is not a member of the workspace, they shouldn't be able to complete the task, yeah? So I don't think this is a bug. @FitseTLT can you clarify why you think this is a bug 😅

**Comment by FitseTLT** [comment]
What workspace @OfstadC ?? the bug is related with group chat

**Comment by OfstadC** [comment]
I need to test this again - I can't wrap my brain around it 😅

**Comment by FitseTLT** [comment]
>But I also don't think this is a real life scenario. Like i'm not sure what real life scenario would have User B assigning to another external user and then back to themselves.

With this, Yep I agree @OfstadC 👍

**Comment by OfstadC** [comment]
Thanks @FitseTLT - i'm going to close this issue then. 😃
