### ISSUE TITLE
[$250] Distance rate-Decimals are not supported for this currency yet entering dot is allowed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49336]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.36-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go to profile icon --workspaces --workspace
3. Change workspace currency to ALL
4. Tap more features -- distance rate
5. Tap on rate
6. Enter decimal number with dot eg : 6.4
7. Tap save
8. Tap rate again

## Expected Result:
Decimals are bit supported for this currency so user must not be allowed to enter dot.

## Actual Result:
Decimals are not supported for this currency yet entering dot is displayed in distance rate page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/77633941-6a95-4b64-8e52-d5d1b4db0737

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836536263898090209</li>
        <li>Upwork Job ID: 1836536263898090209</li>
        <li>Last Price Increase: 2024-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104120435</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by BhuvaneshPatil** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance rate-Decimals are not supported for this currency yet entering dot is allowed

### What is the root cause of that problem?
We are adding extra decimals prop here
https://github.com/Expensify/App/blob/2190f6279041ed8260752294d095bbdda76faebe/src/pages/workspace/distanceRates/CreateDistanceRatePage.tsx#L93

This causes allowing one decimal to any currency.

### What changes do you think we should make in order to solve the problem?
We should remove that prop

### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment]
@DylanDylann when you get a chance, can you review the proposals to address this Albanian currency issue? Thanks!

**Comment by DylanDylann** [comment]
@daledah Interesting point. I will review this issue today

**Comment by DylanDylann** [comment]
1. In the Submit Expense Page, we use the default number of decimal places for each currency (USD: 2, ALL: 0)

https://github.com/user-attachments/assets/083d78d1-35c3-43f8-b74b-520de39d17f9

2. In the Add distance rate, we have one more decimal compared to the default (USD: 3, ALL: 1)

<img width="1512" alt="Screenshot 2024-09-20 at 14 46 01" src="https://github.com/user-attachments/assets/6d61604f-6311-4394-b80e-2d001a342dfc">

I lean toward removing the extra decimal in the distance rate page as mentioned by @daledah 

Anyway, I think we still need to confirm the expected first because the extra decimal is added a long time ago for the rate feature

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment]
@Expensify/design @lakchote As the above comment, we have inconsistency in the number of decimals in the submit expense page and distance rate page. Is there any reason why we need to add one more extra decimal in the distance rate page? If not, should we remove extraDecimal to keep it consistent?


1. In the Submit Expense Page, we use the default number of decimal places for each currency (USD: 2, ALL: 0)

https://github.com/user-attachments/assets/083d78d1-35c3-43f8-b74b-520de39d17f9

2. In the Add distance rate, we have one more decimal compared to the default (USD: 3, ALL: 1)

<img width="1512" alt="Screenshot 2024-09-20 at 14 46 01" src="https://github.com/user-attachments/assets/6d61604f-6311-4394-b80e-2d001a342dfc">

**Comment by shawnborton** [comment]
I think that is on purpose, since a lot of government distance rates use three decimal places. cc @trjExpensify to fact check me there.

**Comment by DylanDylann** [comment]
@shawnborton For the VND, ALL currency (there are no decimal in the submit expense page), Should we allow one decimal in the distance rate page?

**Comment by BhuvaneshPatil** [comment]
@DylanDylann I have mentioned about removing that prop in my proposal. Any reason for selecting the other proposal

**Comment by DylanDylann** [comment]
@BhuvaneshPatil Let's discuss the expectation first, I will come back to proposals later. Thanks

**Comment by shawnborton** [comment]
What do you mean by the VND?

**Comment by DylanDylann** [comment]
Ah VND is a currency, ALL also be a currency

**Comment by shawnborton** [comment]
Hmm honestly I have no idea. I kind of think we can just always allow three decimal places no matter what the currency is to keep things simple? But would love someone more familiar with distance rates to fact check me, cc @twisterdotcom

**Comment by alexpensify** [comment]
@DylanDylann, are there more questions here, or are we good to move forward? Thanks!

**Comment by BhuvaneshPatil** [comment]
[### Proposal updated](https://github.com/Expensify/App/issues/49336#issuecomment-2355431035)

- added logic to have three decimals

**Comment by trjExpensify** [comment]
>I think we should just allow three everywhere. That's what we do on oldDot.

Distance rate decimals are to `4` aren't they, @twisterdotcom. 

<img width="399" alt="image" src="https://github.com/user-attachments/assets/41350e12-ad03-4415-9686-a9d7d746729e">

**Comment by DylanDylann** [comment]
Waiting for @twisterdotcom to discuss more about the expect: https://github.com/Expensify/App/issues/49336#issuecomment-2368921168

**Comment by twisterdotcom** [comment]
Wow, I didn't even test adding another one. Okay, then sure, let's do 4 everywhere.

**Comment by DylanDylann** [comment]
@daledah's [proposal](https://github.com/Expensify/App/issues/49336#issuecomment-2362712374) looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment]
Ahh, thanks for your reminder. I updated [comment](https://github.com/Expensify/App/issues/49336#issuecomment-2373604694) to explain my decision. Don't hesitate to tell me if you have any concern

**Comment by alexpensify** [comment]
Awesome, waiting for this one to go into Production.

**Comment by alexpensify** [comment]
Automation failed but this one went into production 2 days ago

**Comment by alexpensify** [comment]
Automation failed, I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment]
Payouts due: 10-07-2024

- [ ] Contributor: $250 @daledah 
- [ ] Contributor+: $250 @DylanDylann 

Upwork job is [here](https://www.upwork.com/jobs/~021836536263898090209).

**Comment by alexpensify** [comment]
@daledah - I sent an offer via Upwork. Please accept, and then I can complete the payment process. Thanks!

**Comment by alexpensify** [comment]
All set here, I've completed the payment for @daledah!
