### ISSUE TITLE
[HOLD https://github.com/Expensify/Auth/pull/12483] Pay button should only show up optimistically once a report is submitted if payments are enabled for the policy

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#49334]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** @srikarparsi 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1726537212622119?thread_ts=1725892977.799399&cid=C06ML6X0W9L

## Action Performed:
Closed Report flow:
1. Create a workspace
2. Enable workflows
3. Disable payments
4. Invite a submitter
5. As the submitter, submit an expense in the workspace chat
6. As the approver, go offline and access the expense

Approved Report flow:
1. Create a workspace
2. Enable workflows
3. Enable approvals
4. Disable payments
5. Invite a submitter
7. As the submitter, submit an expense in the workspace chat
8. As the admin/approver, go offline
9. As the approver, approve the expense

## Expected Result:
Since payments are disabled, the approver/admin shouldn't see the 'Pay' button optimistically.

## Actual Result:
The approver/admin sees the 'Pay' button optimistically, even though payments are disabled.

## Workaround:
No

## Platforms:
All

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by koko57** [comment]
Hey, I'm Agata from Callstack - an expert contributor group - I can take a look at this issue

**Comment by trjExpensify** [comment]
Thanks, @koko57. Assigned you!

**Comment by koko57** [comment]
same as in https://github.com/Expensify/App/issues/49333#issuecomment-2355895214 I cannot recreate it


https://github.com/user-attachments/assets/3f1fcad5-3b10-4134-aa9d-79c5379a72d0

@garrettmknight could you please check what I might be doing wrong?

**Comment by koko57** [comment]
@trjExpensify and here - should the admin submit the expense or a member?

**Comment by trjExpensify** [comment]
I couldn't repro it with [these steps](https://github.com/Expensify/App/issues/49333#issuecomment-2355992536) as the admin submitter, the `Pay` button didn't appear. So maybe @srikarparsi can confirm his steps and if they match the OP.

**Comment by srikarparsi** [comment]
Sorry this should be on hold for this https://github.com/Expensify/Auth/pull/12483. This will only be reproducible once the Auth PR hits production

**Comment by srikarparsi** [comment]
I believe we can close this issue, I am no longer able to reproduce it even though https://github.com/Expensify/Auth/pull/12483 has been deployed to production.
