### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Show the next step for Closed or Approved reports as “No action required” if payments are disabled.

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#49333]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @srikarparsi 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1726537212622119?thread_ts=1725892977.799399&cid=C06ML6X0W9L

## Action Performed:

1. Create a workspace
2. Enable workflows
3. Disable payments
4. Submit an expense on the workspace chat
5. Click into the expense

## Expected Result:
The next step for this report should be “No action required” if payments are disabled.

## Actual Result:
The next step does not render.
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/09cc9bea-8797-4405-93df-9e077cca33b3">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:
All

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835986044043862116</li>
        <li>Upwork Job ID: 1835986044043862116</li>
        <li>Last Price Increase: 2024-09-17</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104000212</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by koko57** [comment]
Hey, I'm Agata from Callstack - an expert contributor group - I can take a look at this issue

**Comment by trjExpensify** [comment]
Also assigning @koko57 here to look into this. 👍

**Comment by koko57** [comment]
either I'm doing it wrong, or I really cannot recreate the bug

https://github.com/user-attachments/assets/986dde6c-25ba-4708-a38d-c75e241f09df

@garrettmknight could you check if I'm not missing something?

**Comment by trjExpensify** [comment]
For closed reports: 

- Workflows = enabled
- Delayed submission = disabled
- Approvals = disabled
- Payments = disabled

^^ I validated the above config by going to OldDot and checking for

- Reports > Scheduled Submit > Instantly
- Members > Approval Mode > Submit & close
- Reimbursement > None

https://github.com/user-attachments/assets/e0879996-4e9c-4141-8159-a9024d076996


Then all I did was: 

1. Submit an expense on the workspace as the admin
2. I don't see a pay button
3. I do see the incorrect next steps:

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/92a46fe0-294f-4d6d-bd1d-0617d7e2eeb7">

**Comment by trjExpensify** [comment]
Then for the approved reports case:

Workflows = enabled
Delayed submission = disabled
Approvals = enabled
Payments = disabled

^^ I validated the above config by going to OldDot and checking for

Reports > Scheduled Submit > Instantly
Members > Approval Mode > Submit & approve
Reimbursement > None

Steps:

1. Submit an expense on the workspace as the admin
2. I see an `Approve` button
3. I approve the report and see incorrect next steps about waiting to adding a bank account (notice how it flashes as well). 

https://github.com/user-attachments/assets/3881e07f-da80-4827-8af9-cbb01fd6f48c

**Comment by koko57** [comment]
ok, so it's for an expense submitted by admin? So the tests steps are a bit misleading 😅

**Comment by trjExpensify** [comment]
That's what I did to produce the above, yeah. @srikarparsi can confirm on his steps from the OP when he's on.

**Comment by koko57** [comment]
ok, I reproduced it now too - so I'm starting digging

**Comment by koko57** [comment]
it's a problem with `buildNextStep` function. I'm working to get all the conditions right. I've noticed that right after submitting an expense we get 
<img width="550" alt="Screenshot 2024-09-18 at 13 45 47" src="https://github.com/user-attachments/assets/6b6375d6-32a6-4d32-a55b-7328a1c7194b">
later we get this one
<img width="555" alt="Screenshot 2024-09-18 at 13 46 07" src="https://github.com/user-attachments/assets/914a48e4-6548-48da-a542-b5942904bca6">

**Comment by srikarparsi** [comment]
Sorry this should be on hold for this [Auth PR](https://github.com/Expensify/Auth/pull/12483). This will only be reproducible once the Auth PR hits production

**Comment by srikarparsi** [comment]
Removed this from hold since https://github.com/Expensify/Auth/pull/12483 has been deployed to production. Also updated the issue body to have easier reproduction steps.

**Comment by koko57** [comment]
ok, so I'm starting to investigate it

**Comment by srikarparsi** [comment]
Sounds good, let me know if you have any questions. I think we need to call `NextStepUtils.buildNextStep` in IOU with the CLOSED status since that status [already renders](https://github.com/Expensify/App/blob/e0b8326374a617899b64684a5c9a0a54cb5653fb/src/libs/NextStepUtils.ts#L229-L238) the "No further action required" message.

**Comment by koko57** [comment]
ok, I will apply this, but won't it be replaced by the response from OpenReport? We get an empty array for that
<img width="501" alt="Screenshot 2024-09-20 at 13 32 11" src="https://github.com/user-attachments/assets/c5512471-fdfa-4f0d-847c-baf51de3881b">

**Comment by koko57** [comment]
@srikarparsi now for the nextStep we're generating this message 
https://github.com/Expensify/App/blob/e0b8326374a617899b64684a5c9a0a54cb5653fb/src/libs/NextStepUtils.ts#L139-L156
<img width="633" alt="Screenshot 2024-09-20 at 15 12 33" src="https://github.com/user-attachments/assets/c2a11124-9a49-4c90-af1c-e92bfb79dbdf">
after we get the response from OpenReport it's cleared bc the response looks like above.

**Comment by ikevin127** [comment]
Not overdue, the issue is being actively worked on.

**Comment by srikarparsi** [comment]
> ok, I will apply this, but won't it be replaced by the response from OpenReport? We get an empty array for that

Ah thanks for the looking into this. Can we fix the offline (optimistic) behavior here and I can work on a backend PR that returns the right next steps for this case?

**Comment by koko57** [comment]
@srikarparsi ok, I will take care of it 🙂

**Comment by ikevin127** [comment]
Not overdue, the issue is being actively worked on.

**Comment by koko57** [comment]
PR ready for review https://github.com/Expensify/App/pull/49837

**Comment by ikevin127** [comment]
♻️ **Status update**: I [reviewed and approved](https://github.com/Expensify/App/pull/49837#pullrequestreview-2334849021) the PR previously but there was a misunderstanding in terms of functionality which means that the PR was being worked on up until yesterday, today I asked the author if the PR is ready to be retested.

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @koko57 no payment required, Contractor
Contributor+: @ikevin127 $250, paid via Upwork

@ikevin127 could you please complete the BZ checklist we we can close out the issue? Thanks 🙏

**Comment by ikevin127** [comment]
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: **Not caused by a previous PR as this was more like a feature request since we added something that did not exist before.**
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**.
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to Workspace -> enable Workflows.
2. Disable payments.
3. Submit an expense on the workspace chat.
4. Go offline, click into the expense.
5. Verify that you see "No further action required" text in the header.

Do we agree 👍 or 👎.

**Comment by sakluger** [comment]
Thanks!
