### ISSUE TITLE
[Workspace Chats for All] Make it possible to submit expenses to any workspace, whether or not there is a workspace chat

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#49344]
# Problem 

There are a few different ways users can end up in a scenario in NewDot where they aren't able to submit expenses to their workspace. A couple known scenarios:
1. The user is on an existing policy that gets added to the policyExpenseChat beta. When someone is added to this beta, we don't create workspace chats for users immediately. We do create the workspace chat the next time an expense/report is created, but that can only be done via OldDot since there is no workspace chat in NewDot and the only way to submit an expense in NewDot is to submit it to the workspace chat. This scenario will soon apply to all of our internal policies, which we plan to update to be NewDot-enabled imminently.
2. When a user is on an existing policy that isn't on the policyExpenseChat beta. This can happen when a user lands in NewDot (for example to chat with Concierge) and tries it out. We've seen multiple examples of this happening with existing users in #concierge-development

# Solution 

Update NewDot to allow submitting to any policy you are a member of, whether or not a workspace chat exists for it. The back-end will then handle creating a workspace chat for the expense if necessary. This would solve the problem for both 1 and 2.

To do this we will: 
1. Show all workspaces the user is a member of that have `isPolicyExpenseChatEnabled=true` in the submit expense dialog, whether or not workspace chats exist for them 
3. Pass both a policyID and workspace chat reportID when creating the expense 
4. If the user doesn't have a workspace chat locally, then we will create an optimistic one
5. The back-end will handle taking the optimistic workspace chat report and creating it if necessary
6. If a workspace chat already exists that is different than the optimistic one, we will return the pre-existing reportID (just like we do when starting chats) 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by puneetlath** [comment]
@dubielzyk-expensify un-assigning you since there's no new UI being added here.

**Comment by flaviadefaria** [comment]
Moving this over to #migrate project as it will be a blocker for enabling workspace chat for existing workspaces of Cohort 1.

**Comment by JmillsExpensify** [comment]
Can we move this issue to `Daily` given that it's CRITICAL for #migrate?

**Comment by JmillsExpensify** [comment]
Awesome, adding a `Daily` on this one so the priority is a bit more clear to those passing through.

**Comment by puneetlath** [comment]
Likely going to change this behavior based on this discussion: https://expensify.slack.com/archives/C07NMDKEFMH/p1730152377459179?thread_ts=1730145327.196299&cid=C07NMDKEFMH

I'll update here shortly.

**Comment by puneetlath** [comment]
We should close it. Just need to pay out for the work done.

**Comment by puneetlath** [comment]
Payment summary: 
- C - @ishpaul777 - $750 for 3 PRs
- C+ - @allroundexperts - $500 for 2 PRs


@ishpaul777 offer is here: https://www.upwork.com/nx/wm/offer/104882055. Please ping me on this issue when you've accepted. 

@allroundexperts please request in NewDot.

**Comment by puneetlath** [comment]
Paid. Thanks y'all!

**Comment by JmillsExpensify** [comment]
$500 approved for @allroundexperts
