### ISSUE TITLE
NetSuite - "Preferred exporter" returns to the previous when adjusting while sync is ongoing

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#49352]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.26-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4901048&group_by=cases:section_id&group_id=314239&group_order=asc

**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new Gmail account
3. Click on FAB - New workspace
4. Navigate to Workspace settings - Members
5. Invite a new Gmail user
6. Make the user an admin of the workspace
7. Enable "Accounting" in the "More features" page.
8. Navigate to "Accounting"
9. Connect to NetSuite and upgrade the workspace to Control when asked
10. Wait for the sync to finish
11. Click on the "..." button next to NetSuite
12. Click on "Sync now"
13. Quickly navigate to Accounting - Export - Preferred exporter
14. Quickly set the exporter to the admin account invited in step 5
15. Wait for the sync to finish

## Expected Result:
"Preferred exporter" shouldn't change after it's set.

## Actual Result:
"Preferred exporter" returns to the previous one as soon as the sync finishes. The issue only shows when the exported is changed while the accounting is in sync.

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/edc158da-d594-489b-b0bf-7c1452e34600
___
Adding the Internal label since this requires integration access. 
We think this issue could be part of the project for #wave-control. 
___
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isagoico** [comment]
After checking the discussion on this issue - https://github.com/Expensify/App/issues/48090, it looks like the solution that they are providing there _**could**_ fix this scenario.

**Comment by adelekennedy** [comment]
closing in favor of the linked issue!
