### ISSUE TITLE
Tags aren't pulling into NewDot with our NetSuite integration.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49360]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zsgreenwald 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726591465899479

## Action Performed:

1. Go to a workspace where NetSuite is connected
2. Go to Import, and select any field as a Tag
3. Go back to LHN and see if Tags appears in LHN
4. If not, go to More Features and enable Tags

## Expected Result:
Tags are enabled after integration

## Actual Result:
Tags aren't pulled in after Netsuite integration
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/27f399bd-088b-41ba-bb0a-0c585557e7a5

https://github.com/user-attachments/assets/7020006b-a7e8-4d2a-bb96-86a0ce09ac3f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by yuwenmemon** [comment]
Actually, this will be fixed with https://github.com/Expensify/Web-Expensify/pull/43574 hopefully

**Comment by aldo-expensify** [comment]
@m-natarajan can you retest this? I think this issue has been solved.

**Comment by twisterdotcom** [comment]
This is resolved.
