### ISSUE TITLE
[HOLD for payment 2024-10-24] [$125] QBO Desktop - The message is incorrectly formatted after a failed connection

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49373]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validation PR:** https://github.com/Expensify/App/pull/48759
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. ND: Navigate to https://staging.new.expensify.com/
2. ND: Log in with a new Gmail account
3. ND: Create a workspace
4. ND: Navigate to OD by clicking on Account settings - Domains
5. OD: Navigate to Settings - Workspaces - "Created workspace name" - Connections
6. OD: Upgrade the WS to Collect with the lock icon next to "QuickBooks Desktop"
7. OD: Click on QuickBooks Desktop - Connect to QuickBooks Desktop - Connect to QuickBooks Desktop
8. OD: Attempt to connect to QuickBooks Desktop (the connection will fail)
9. ND: Navigate to the #admins room

## Expected Result:
The message should be "Failed to sync with QuickBooks Desktop"

## Actual Result:
The message is incorrectly formatted after a failed connection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/80632951-5b32-45cb-bc6d-3ac13720c425

![Bug6607366_1726639236491!Capture](https://github.com/user-attachments/assets/5ee53db6-0975-4b2b-88fd-cf14c24a00af)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838585551890315008</li>
        <li>Upwork Job ID: 1838585551890315008</li>
        <li>Last Price Increase: 2024-10-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by mkzie2** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The message is incorrectly formatted after a failed connection.

### What is the root cause of that problem?

The `label` is not correct and `errorMessage` is missing from the integration sync failed report action:

https://github.com/Expensify/App/blob/837e4132ae8b1357c11fce240b6956648cde0f6a/src/pages/home/report/ReportActionItem.tsx#L684-L686

### What changes do you think we should make in order to solve the problem?


For the `label`, I think it's an BE problem not to format `quickbooksDesktop` properly.

For the `errorMessage`, we should only show the message part `("${errorMessage}")` when we have the message content:

https://github.com/Expensify/App/blob/d13f37be4c12bc51d5ec35c3683a92413cce20d5/src/languages/en.ts#L4199

```javascript
`failed to sync with ${label}${errorMessage? `("${errorMessage}")` : ''}`
```

**Comment by muttmuure** [comment]
@rushatgabhane proposal above for you

**Comment by rushatgabhane** [comment]
https://github.com/Expensify/App/issues/49373#issuecomment-2358033537 @mkzie2's proposal LGTM.

we need a small backend and frontend change

 🎀 👀 🎀

**Comment by pecanoro** [comment]
I am reducing the bounty to $125 since this issue is really simple. 

I will take a look at the BE problem later today.

**Comment by pecanoro** [comment]
I have a [PR](https://github.com/Expensify/Auth/pull/12663) to fix this on the back-end. I will let you know when it's deployed.

**Comment by pecanoro** [comment]
Oh the fix was deployed, I forgot to leave a message!

**Comment by garrettmknight** [comment]
@muttmuure can you complete the payment checklist when you get a chance?

**Comment by muttmuure** [comment]
hadling

**Comment by muttmuure** [comment]
@rushatgabhane - $125 C+
@mkzie2 invited here: https://www.upwork.com/jobs/~021838585551890315008

**Comment by mkzie2** [comment]
@muttmuure accepted the job invitation 👍

**Comment by garrettmknight** [comment]
$125 approved for @rushatgabhane

**Comment by muttmuure** [comment]
Offer sent @mkzie2

**Comment by muttmuure** [comment]
Paid
