### ISSUE TITLE
QBO - Expensify in "Go to Expensiy Classic to fix this issue" link is spelled as Expensiy

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49378]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48759
**Email or phone of affected tester (no customers):** applausetester+kh16090001@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO Desktop on Old Dot and the set up is not completed to trigger the error.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Accounting.

## Expected Result:
Expensify in "Go to Expensiy Classic to fix this issue" will be spelled correctly.

## Actual Result:
Expensify in "Go to Expensiy Classic to fix this issue" is spelled as Expensiy.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e0115245-f1df-40c1-bbe1-4a97e136859d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by flodnv** [comment]
Thanks, CP requested.
