### ISSUE TITLE
Improve the metrics doccumentation

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#49376]
Coming from this [thread](https://expensify.slack.com/archives/C05LX9D6E07/p1726574653651339)

### Problem
Various performance metrics are currently sent to Firebase for monitoring and analysis. However, team members struggle to understand, interpret, and utilize the performance data effectively. This difficulty can result in misunderstandings, misinterpretations, and challenges in leveraging metrics to drive performance improvements.

Some examples where it’s not clear what metrics are representing and what is the difference between them:
- load_search_options and search_filter_options
- switch_report and open_report

### Solution
To resolve this issue, let’s create comprehensive documentation for our performance metrics. The documentation should include:
1. Metric Definitions and Descriptions: Provide clear definitions and detailed descriptions of each performance metric.
2. Data Collection Process: Explain how each metric is collected, including the start and end points of the data collection process.
3. Documentation Maintenance: Outline the steps for updating and maintaining the documentation as new metrics are added or existing metrics are modified.

This documentation will be included in the project’s README to ensure easy access and reference for everyone.

**Comment by TMisiukiewicz** [comment]
Hi, I'm Tomasz from Callstack, I'd like to work on this issue

**Comment by mountiny** [comment]
not overdue

**Comment by TMisiukiewicz** [comment]
PR is open ✅
