### ISSUE TITLE
[HOLD for payment 2024-11-01] [Workspace Feeds] Create SetPersonalDetailsAndShipExpensifyCards command

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#49388]
Coming from this [thread](https://expensify.slack.com/archives/C036QM0SLJK/p1726179511528599) we are going to create a new command `SetPersonalDetailsAndShipExpensifyCards` to handle shipping physical cards assigned to the user on in NewDot

The design of workspace feeds allows admins to assign multiple physical cards to the same employee. Additionally, one single user could be assigned cards across multiple card programmes/ feeds.

As a result, we need to create a solution that after updating the personal details, ships all the NOT_ISSUED cards to the employee across all the card feeds.

This `SetPersonalDetailsAndShipExpensifyCards` command will call `ShipExpensifyCard` using http requests for all the not issued cards yet.

**Comment by mallenexpensify** [comment]
@mountiny I'm guessing we don't want this external now, or you would have added that label too.  I'll hang tight for now

**Comment by mountiny** [comment]
Correct, this will be handled internally, working on it

**Comment by mountiny** [comment]
Draft web PR https://github.com/Expensify/Web-Expensify/pull/43637

**Comment by mountiny** [comment]
in progress

**Comment by mountiny** [comment]
This was internal backend so can close now
