### ISSUE TITLE
[$250] IOU - Submitted expense does not appear until open the chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** gocemate+a2167@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
1. User A and User B have no previous conversation

Steps:
1. User A go to FAB> Submit expense> Finish the creating flow
2. As User B take a look at LHN

## Expected Result:
Submitted expense does not appear until open the chat

## Actual Result:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8b867041-c950-41a9-a16e-aee969318a6d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836437111868054558</li>
        <li>Upwork Job ID: 1836437111868054558</li>
        <li>Last Price Increase: 2024-09-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by iwiznia** [comment]
Damnit I clicked the wrong button, did not intend to add the extrernal label. @abekkala not sure if you need to close it or something

**Comment by iwiznia** [comment]
This is already fixed by my other PR. Asked QA to retest here https://expensify.slack.com/archives/C07J32337/p1726675796515109?thread_ts=1726675251.739969&cid=C07J32337 and to remove the blocker if it is a pass (it should since I tested it too)

**Comment by iwiznia** [comment]
It passed https://expensify.slack.com/archives/C9YU7BX5M/p1726676124843999?thread_ts=1726675113.762249&cid=C9YU7BX5M
