### ISSUE TITLE
[$250] Bank account - When adding Chase bank online with Plaid, amount validation is requested

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4975649
**Email or phone of affected tester (no customers):** applausetester+vd_web091724.2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-requisite: user must have created a Workspace and have enabled Worklfows.

1. Go to Settings > Workspaces > Workspace > Workflows.
2. Click on "Connect bank account".
3. Select "Connect online with Plaid".
4. Select Chase bank and go trough the add bank account flow using the testing credentials.
5. At the end, verify amount validation is requested.

## Expected Result:
Chase bank account should be added without amount validation when added online with Plaid.

## Actual Result:
Amount validation is requested when trying to add Chase bank account online with Plaid.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d7eca91d-abc9-4b9e-961b-719269013bc2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837132246080080609</li>
        <li>Upwork Job ID: 1837132246080080609</li>
        <li>Last Price Increase: 2024-09-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by IuliiaHerets** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
>Chase flow does not return bank data so it shifts to manual. If you switch to Wall fargo, it should be good. It is same as before.

Ah okay, cool. You mean on staging using the sandbox yeah?

**Comment by mountiny** [comment]
Hmm, yeah, I don't think Chase was mentioned in any of the testing steps. for [plaid](https://stackoverflowteams.com/c/expensify/questions/342) it says to use Bank of America or Wells fargo.

**Comment by trjExpensify** [comment]
Cool, I'm going to close it then. I've also updated the test case linked in the OP to choose Wells Fargo instead of Chase so we don't get this bug report again.

**Comment by mountiny** [comment]
Asked in Slack [here](https://expensify.slack.com/archives/C9YU7BX5M/p1727104462970739) internal
