### ISSUE TITLE
[$250] Room - Behavior is different in expensifail& gmail a/c on pasting&sending removed users message

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open new expensifail account in mweb
2. Create a room
3. Open new gmail account in app
4. Create a room
5. In mweb, open room chat
6. Invite few users with custom name and remove them
7. Navigate to conversation page
8. Long press the removed users system message and select copy to clipboard
9. Paste in compose and send the message
10. Note both message and whisper shows only user id.
11. In android app, open room chat
12. Paste and send the message
13. Note both message and whisper shows user id briefly and changed to custom name.

From gmail if we copy removed users message and paste in expensifail Or vive versa, this issue happens.

## Expected Result:
Both in removed user message and in whisper, behavior must be same in expensifail and gmail account.

## Actual Result:
Both in removed user message and in whisper, behavior is different in expensifail and gmail account on pasting and sending removed users message.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9e1d633f-25cb-4bec-8587-08ec7686cfba

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836832247831403344</li>
        <li>Upwork Job ID: 1836832247831403344</li>
        <li>Last Price Increase: 2024-09-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by koko57** [comment]
Hello 🙂 I'm Agata from Callstack, maybe I can help with this issue?

**Comment by rushatgabhane** [comment]
yeah i agree ^

not sure why we're removing the domain. the mention should show the display name and fallback to login.

**Comment by koko57** [comment]
ok, thanks! So I will continue my investigation and will try to find a solution

**Comment by koko57** [comment]
ok, I've found the culprit of displaying a display name or a login - this line:
https://github.com/Expensify/App/blob/c7ee85b2ea207159ef85932055aced28d5d2e29a/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L62

when we don't have user's login in personalDetails we fallback to displayName. I wonder why we're doing it this way and we prioritize user login instead of user name. 
I'll check why we don't have user login for these cases we display displayName as a handle, but probably it's because we haven't have any interaction with these users.

**Comment by koko57** [comment]
Yes, if we don't have a chat with the person we don't have the login in personal details.

<img width="583" alt="Screenshot 2024-10-02 at 20 42 39" src="https://github.com/user-attachments/assets/c8793c56-0e93-4ddb-83bc-b088a7b5db62">

<img width="961" alt="Screenshot 2024-10-02 at 20 42 47" src="https://github.com/user-attachments/assets/d6cd9631-ed37-40a3-9fae-e2f3dab83eb3">

<img width="586" alt="Screenshot 2024-10-02 at 21 08 42" src="https://github.com/user-attachments/assets/841ac00c-909b-4dad-a859-5ef9cf4a13c7">

I've also noticed that in some cases the displayName is displayed first, then when we go to user's details page  it changes to the login (we get more details in OpenPublicProfilePage response). It doesn't look nice 

The solution seems obvious and rather simple - reverse the order of getting the value for mentionDisplayText https://github.com/Expensify/App/blob/c7ee85b2ea207159ef85932055aced28d5d2e29a/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L62

and check the other locations where we use mentions and change them as well - like the "copy to clipboard" functionality and mentions suggestions.

**Comment by mountiny** [comment]
Closing this one for now as the issue was part of the VSB project and we will focus on this again in future
