### ISSUE TITLE
Android – Markdown – Code Block is with spaces when send a message with multiple words

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49401]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4979837
**Email or phone of affected tester (no customers):** ponikarchuks+318924@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging app
2. Log in
3. Open any chat
4. Enter text: `How are you` and send

## Expected Result:
Code Block is without spaces

## Actual Result:
Code Block is with spaces

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/055c29a7-b69f-42ae-aea3-d1fe8ce1e0d1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to Live Markdown

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
I agree this isn't ideal, but I don't think this is something we need to prioritise right now. I've confirmed this looks fine on web and desktop, so the number of people this would impact, and the impact it would have on them, seems pretty insignificant.
