### ISSUE TITLE
[HOLD for payment 2024-10-10] [$250] Add Helper Text To NetSuite Custom segments/records and Custom lists fields

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#49409]
### Problem

Right now, with NetSuite, if you're importing Custom Segments / Lists, we kind of hide that fact visually in the config. For example below this is what we see even though Custom Segments and Lists are present in the connection config:
 
![Screenshot 2024-09-17 at 11 44 47 PM (1)](https://github.com/user-attachments/assets/69e57e79-1b03-41b1-a718-1370af9fe459)

![Screenshot 2024-09-17 at 11 43 52 PM](https://github.com/user-attachments/assets/cdffc4f0-c105-41b0-9cb1-6961a54e67ec)

### Solution

Add a helper "value" underneath **Custom segments/records** and **Custom lists** on the "Import" page for the NetSuite connection, similar to what we have for Departments, Classes, Locations and other fields.

- If all **Custom segments/records** or **Custom lists** are being imported as tags it should read:
    - `Imported as tags`
- If all **Custom segments/records** or **Custom lists** are being imported as report fields it should read:
    - `Imported as report fields`
- If all **Custom segments/records** or **Custom lists** are being imported as a mix of report fields and tags it should read:
    - `Imported as tags and report fields`

cc @zsgreenwald @jamesdeanexpensify @mananjadhav @shubham1206agra 

Slack thread: https://expensify.slack.com/archives/C06ML6X0W9L/p1726642272240069

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836470482098534466</li>
        <li>Upwork Job ID: 1836470482098534466</li>
        <li>Last Price Increase: 2024-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104025552</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by mananjadhav** [comment]
@yuwenmemon do I want me to work on this ?

**Comment by yuwenmemon** [comment]
@mananjadhav you are free to pick it up if you want! Just figured I'd highlight it for you since you worked on this originally 🙂

**Comment by mananjadhav** [comment]
Reviewing.

**Comment by joekaufmanexpensify** [comment]
@mananjadhav is there an ETA for PR here?

**Comment by joekaufmanexpensify** [comment]
Got it, sounds good!

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by mananjadhav** [comment]
@yuwenmemon Should we assign @shubham1206agra here for the review? It's been more than a few days being under review.

**Comment by akinwale** [comment]
Reviewing this today.

**Comment by joekaufmanexpensify** [comment]
PR in review

**Comment by mananjadhav** [comment]
I'll be pushing the small feedback in an hour or so, aiming to merge this today.

**Comment by joekaufmanexpensify** [comment]
@akinwale could you handle checklist so I can prep for payment?

**Comment by akinwale** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
_Precondition_
* Own a workspace with NetSuite enabled.

**Steps**
1. Launch Expensify
2. Open the workspace settings and select Accounting.
3. Click on Import.
4. Verify that there is no helper text with empty custom lists.
5. Click on the Custom list and add a few custom lists.
6. Go back to the Import page and check the Custom lists option again.
7. Verify that `Imported as tags` is the helper text displayed if all custom lists are of type, Tag
8. Verify that `Imported as report fields` is the helper text displayed if all custom lists are of type, Report
9. Verify that `Imported as tags and report fields` is the helper text displayed if the custom lists are a mix of types, Tag and Report
10. Repeat 4-9 for Custom segments/records

Do we agree 👍 or 👎?

**Comment by joekaufmanexpensify** [comment]
Checklist is complete!

**Comment by joekaufmanexpensify** [comment]
All set to issue payment here. We need to pay: 

- @mananjadhav - $250 for PR via NewDot. 
- @akinwale - $250 for C+ via Upwork.

**Comment by joekaufmanexpensify** [comment]
@akinwale $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment]
Closing as all that's left is for @mananjadhav to request payment via NewDot whenever you're ready

**Comment by mananjadhav** [comment]
Thanks @joekaufmanexpensify. I've requested.

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
