### ISSUE TITLE
Workspace – "Report Fields" toggle is off and report fields menu item appears after refresh

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49410]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.37-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48601
**Email or phone of affected tester (no customers):** ponikarchuks+118924@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: create Control workspace in OD
1. Sign in with the same Gmail account in ND
2. Navigate to Settings > Control Workspace > More features
3. Enable "Report Fields" option
4. Navigate to Report Fields settings page
5. Add field with any name and Text type
6. Set any Initial value for the text field and tap on "Save" button
7. Navigate to "More Features" page
8. Disable "Report Fields" toggle button
9. In OD update with any new text the initial value for created Text field
10. In ND verify the "Report Fields" toggle button properly switches on

## Expected Result:
"Report Fields" toggle button switches on and report fields menu item appears immediately

## Actual Result:
"Report Fields" toggle button not switches on and report fields menu item appears after page refresh

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6b8cf368-551f-49ca-95ce-bf2e371e4437

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
I can't understand what this means:

> In OD update with any new text the initial value for created Text field

There are no report fields in OldDot because they were disabled in Step 8.

**Comment by RachCHopkins** [comment]
Oh ok, it's saying to enable them from OldDot again. Yes, that should enable the report fields, that's correct. And my toggle is on. 

![image](https://github.com/user-attachments/assets/bc85eeb9-fd18-486e-85df-d5b40269f2e2)

Nothing to fix here.
