### ISSUE TITLE
Attachments-Offline message is displayed instead of the video player

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49423]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4970487
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to any chat
2. Upload a video
3. Disable the internet connection
4. Click on the video

## Expected Result:
The video player is displayed.
The download option on the top right is not displayed.
On the 3-dot menu, download option is not displayed.

## Actual Result:
When the user clicks on the video, an offline message is displayed. The download option and the 3-dot menu are not displayed.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/69748812-2c31-4a68-a932-60943c192dc3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837167831696067297</li>
        <li>Upwork Job ID: 1837167831696067297</li>
        <li>Last Price Increase: 2024-09-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by IuliiaHerets** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by IuliiaHerets** [comment]
@FitseTLT According to the TR`s steps the download option should disappears in offline, but we can't see video player at all. Do we need to update the steps?
![image](https://github.com/user-attachments/assets/e6cbaed3-e12d-4310-b2c5-c03c18f07836)

**Comment by FitseTLT** [comment]
I suggest so.

**Comment by sonialiap** [comment]
Issue submitted asking for QA steps update
