### ISSUE TITLE
Web - Console error shows up after loading staging ND

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49443]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Refresh the page.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up.
On production, there is a different console error but it only appears after refreshing the page.
On staging, the error shows up after opening the page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[1909.txt](https://github.com/user-attachments/files/17055947/1909.txt)

https://github.com/user-attachments/assets/0e4b5ff9-0391-4f8d-8bd4-64d440186e01

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment]
Potentially related to https://github.com/Expensify/App/pull/47795

These are my console errors: 

<img width="236" alt="image" src="https://github.com/user-attachments/assets/8c9f27eb-9297-49a9-966f-7f17e6e7d806">

**Comment by mountiny** [comment]
Pinged in thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1726734341188169)

**Comment by mountiny** [comment]
PR up to update the CSP rules

**Comment by mountiny** [comment]
This is technically not app blocker
