### ISSUE TITLE
[HOLD for production 2024-10-07][$250] [Search v2.3] Add the bookmark icon for Saved searches on mobile

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49442]
See https://github.com/Expensify/App/pull/48566#issuecomment-2350223656
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836682788967357264</li>
        <li>Upwork Job ID: 1836682788967357264</li>
        <li>Last Price Increase: 2024-09-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by mkzie2** [comment]
>  If we're viewing a saved search, we shouldn't add the custom query option to the bottom modal. Example: In the imagine below, the type:expense status:all currency:ALL AMD shouldn't be shown

As the ref comment [here](https://github.com/Expensify/App/pull/48566#issuecomment-2350223656) mentioned, we shouldn't display the viewing saved search query in `popoverMenuItems` or `savedSearchItems`

**Comment by lakchote** [comment]
@mkzie2's proposal LGTM.

**Comment by mkzie2** [comment]
Will raise the PR soon.

**Comment by mkzie2** [comment]
@thesahindia The PR is ready https://github.com/Expensify/App/pull/49583.

**Comment by mkzie2** [comment]
@lakchote Can we process payment here?

**Comment by lakchote** [comment]
@VictoriaExpensify please process payment for @mkzie2, thanks!

**Comment by luacmartins** [comment]
Waiting on payment

**Comment by VictoriaExpensify** [comment]
Hey @mkzie2 - can you please accept the job offer and I'll organise payment
https://www.upwork.com/nx/wm/offer/104530588

**Comment by mkzie2** [comment]
@VictoriaExpensify Did it thank you

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @mkzie2 - Paid $250 via Upwork
Contributor+: @thesahindia - owed $250 via NewDot

**Comment by garrettmknight** [comment]
$250 paid for @thesahindia
