### ISSUE TITLE
[Search v2.3] Make the popover menu modal closable by swiping down

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49441]
See https://github.com/Expensify/App/pull/48566#issuecomment-2348870540

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by nkdengineer** [comment]
@lakchote What is the swiping-down action? It would be helpful to have an example video about this bug.

**Comment by lakchote** [comment]
> @lakchote What is the swiping-down action? It would be helpful to have an example video about this bug.

I've retested it, and [this](https://github.com/Expensify/App/issues/49217#issuecomment-2351162918) fixed it.
https://github.com/user-attachments/assets/a9f89dde-6e46-4e6e-b3f7-a3b2d28717d7

Previously, we weren't able to close the modal down by swiping downwars from the header.

Discussed it with @jjcoffee and we can close the issue.
