### ISSUE TITLE
[HOLD for payment 2024-09-26] Expense - Bad grammar "You's expense(s)" instead of "Your expense(s)" in report banner

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0 
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workflows are enabled.
- Delayed submissions are enabled.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense and avoid all the violations.
4. Go to expense report.

## Expected Result:
The banner should display "Waiting for <Your> expense(s) to automatically submit on Sunday".

## Actual Result:
The banner displays "Waiting for <You's> expense(s) to automatically submit on Sunday".

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e8fbf049-7c97-44dd-b024-bdf91ef47b84

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by MuaazArshad** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bad grammar "You's expense(s)" instead of "Your expense(s)" in report banner
### What is the root cause of that problem?
This is what we are impementing
### What changes do you think we should make in order to solve the problem?
If we do not want to add name of use then we have to remove this form here
https://github.com/Expensify/App/blob/040c8017219d4ca3650e41d41660c04d6b5a2d64/src/libs/NextStepUtils.ts#L138-L141


### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment]
Looking at this

**Comment by grgia** [comment]
Caused by https://github.com/Expensify/App/pull/49315

**Comment by grgia** [comment]
https://expensify.slack.com/archives/C01GTK53T8Q/p1726754452736749

**Comment by aldo-expensify** [comment]
Summary:

Assigned @allgandalf in the role of C+
@ishpaul777 is the author of https://github.com/Expensify/App/pull/49482 fixing this deploy blocker 
@ishpaul777 was the C+ of https://github.com/Expensify/App/pull/49315 that introduced the regression

**Comment by anmurali** [comment]
Offer is [here](https://www.upwork.com/nx/wm/offer/104282329)

**Comment by anmurali** [comment]
Paid.
