### ISSUE TITLE
Tax-After changing currency& turning off billable toggle, tax amount shown as 0

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49467]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login as employee
3. Tap on a workspace chat
4. Tap plus icon -- submit expense
5. Create a expense entering merchant
6. Open the expense create
7. Change the amount to some other currency ( not local currency)
8. Turn off the billable toggle

## Expected Result:
After changing currency& turning off billable toggle, tax amount must not be shown as 0.

## Actual Result:
After changing currency& turning off billable toggle, tax amount shown as 0.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1103f5c7-d1dc-4c85-a576-db617877057c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
Adding this one to my test list and will get to it later this week.

**Comment by alexpensify** [comment]
I've been sick this week and haven't been able to review this GitHub. There is no major update here; I'll try to carry on next week.

**Comment by alexpensify** [comment]
It's not overdue; I'm still catching up from being sick at the end of last week.

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
I'll get to this one soon.

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience 

![2024-10-11_16-42-38](https://github.com/user-attachments/assets/b4c3ac9b-2ab7-40a4-bfdb-0cbcc757a17e)
