### ISSUE TITLE
Members invited to a workspace on NewDot that doesn’t have isPolicyExpenseChatEnabled set to `true` appear “Hidden” in the Members table.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49465]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** [Internal logSearch requestID](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228c588e131d97bf0a-LHR%22%20AND%20timestamp%3A%5B2024-09-19T00%3A00%20TO%202024-09-20T23%3A59%5D). 
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726740074985259

## Action Performed:

1. Go to Classic
2. Sign-up for a new account using a private email address
3. Create a Control workspace
4. Switch to NewDot
5. Go to Account > Workspaces > Members
6. Invite a couple of new accounts
7. Observe how they appear “Hidden” in the members table
8. Click on one of the “Hidden” rows

## Expected Result:
Members should be visible in the members table and their profile accessible in the RHP.
## Actual Result:
NotFound error in the RHP and the URL path `/members/0`
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/be460482-6b7e-47f0-9584-b25b26b2ed6e

https://github.com/user-attachments/assets/10a24741-31af-4289-b879-732b7f946891

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment]
Added my [requestID](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228c588e131d97bf0a-LHR%22%20AND%20timestamp%3A%5B2024-09-19T00%3A00%20TO%202024-09-20T23%3A59%5D) to the OP. 

@mountiny had an idea of what might be up here: 

>Idea: the personal details data is missing as normally it would be pushed along with the new workspace chat data, which is missing in the case of when the beta is not enabled.
>And possibly we do not push the personal details on their own to the policy members

CC: @puneetlath as you have some knowledge on hidden and personalDetails shizzz.

**Comment by trjExpensify** [comment]
@dylanexpensify one to call out in `Hot picks` in the update. :)

**Comment by trjExpensify** [comment]
@dylanexpensify any takers?

**Comment by trjExpensify** [comment]
@dylanexpensify is this getting called out?

**Comment by trjExpensify** [comment]
Bumped in thread: https://expensify.slack.com/archives/C06ML6X0W9L/p1728064226162109?thread_ts=1727729324.688989&cid=C06ML6X0W9L

**Comment by rlinoz** [comment]
I will take a look at this one

**Comment by rlinoz** [comment]
Here it is what we will need to do:

1. Update Auth to consider invited accounts as definitely known by the inviter
2. Remove the onyx updates for `personalDetailsList` from PHP, since that is overriding the values from Auth

Working on both of the changes.

**Comment by rlinoz** [comment]
I don't know where I was with my head in the comment above since it has nothing to do with reports but with Policy sharing, anyway, PR is up https://github.com/Expensify/Auth/pull/12701

**Comment by trjExpensify** [comment]
Wahoo, that's merged.

**Comment by rlinoz** [comment]
Fix is in prod, tested and it works!

<img width="2201" alt="Screenshot 2024-10-10 at 11 23 32" src="https://github.com/user-attachments/assets/eae14ec1-a676-4355-9b6c-2a4e5f878d1c">
