### ISSUE TITLE
[$100] Android -Profile - Error Message Cut Off When Uploading Large Image to Profile

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49485]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No, prod has another wrong behavior
**Email or phone of affected tester (no customers):** applausetester+tw345636637997@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to Account Settings > Profile.
2. Upload a large image (>24MB).

## Expected Result:
The error message should display fully when attempting to upload a large image to the profile.

## Actual Result:
The error message is cut off when a large image is uploaded to the profile.

## Workaround:
Unknown
## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/fb3473a9-f313-45f8-a43f-b991d68ebbd0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836847837390067999</li>
        <li>Upwork Job ID: 1836847837390067999</li>
        <li>Last Price Increase: 2024-09-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by IuliiaHerets** [comment]
Prod behavior 
![Screenshot_20240919-220025](https://github.com/user-attachments/assets/5c08fb6a-a74d-4497-a1d9-221dce1b125c)

**Comment by etCoderDysto** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android -Profile - Error Message Cut Off When Uploading Large Image to Profile
### What is the root cause of that problem?
We are not adding styles.w100 to the view below 
https://github.com/Expensify/App/blob/98dc643e14378f654e45a7ce96f35be9f407c007/src/pages/settings/Profile/ProfilePage.tsx#L133
### What changes do you think we should make in order to solve the problem?

Add styles.w100
### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment]
Removing deploy blocker label since this is on prod

**Comment by sonialiap** [comment]
@fedirjh am I correct in that this is being handled in https://github.com/Expensify/App/pull/49203#pullrequestreview-2333712300 which is a PR for https://github.com/Expensify/App/issues/48707? So the payment for this would also be handled there, correct?

**Comment by sonialiap** [comment]
Thanks 👍
