### ISSUE TITLE
Android - Workspace - After inviting member to workspace, 2 notification messages are received

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49498]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-conditions: 1. Keep notifications on in device
2. Login as 2 different users in mweb and Android

1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- workspaces -- workspace
3. Tap members -- invite
4. Invite user B to workspace who is logged in Android app
5. Note notifications

## Expected Result:
After inviting member to workspace, 2 notification messages must not be received.

## Actual Result:
After inviting member to workspace, 2 notification messages are received.
## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c2b70e3c-058c-4888-a24f-50a0a4dffddb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
This is a pretty minor issue not related to our roadmap, gonna close as low priority for now
