### ISSUE TITLE
[$250] Mentioning approver in report overwrites their write capabilities and stops them from being able to comment on the report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49495]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726768176167369

## Action Performed:

1. Create workspace
2. Enable workflows
3. Invite submitter and approver
4. Enable approval - set approver
5. As submitter, create expense in workspace chat
6. As submitter, @ mention approver in expense/report

## Expected Result:
Approver can still chat in report
## Actual Result:
Approver’s permissions are reset to ‘read’ and they can’t comment
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Snip - (19) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/d6ace4f7-e64a-448e-afcd-8eb8aa891724)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837112575767072107</li>
        <li>Upwork Job ID: 1837112575767072107</li>
        <li>Last Price Increase: 2024-09-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rlinoz</details>

**Comment by garrettmknight** [comment]
Note that this might not be `External` but I'm starting it there to get a move on.

**Comment by rlinoz** [comment]
PR is up!

**Comment by DylanDylann** [comment]
@rlinoz Do we require C+ on this issue?

**Comment by trjExpensify** [comment]
@rlinoz thanks for picking this up! ❤️

**Comment by rlinoz** [comment]
@DylanDylann no, it is internal only

**Comment by trjExpensify** [comment]
Auth PR is on prod, so this can be closed right?

**Comment by rlinoz** [comment]
Yes!
