### ISSUE TITLE
[$250] Group chat - After removing user, group name is not updated

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49491]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap fab -- start chat
3. Select a user with a custom name eg: [jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
and tap `add to group`
4. Open the group name and note user name shown
5. Select the user and now note the group name updated without user name
6. Tap back
7. Select a user with a custom name eg: [jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
and tap `add to group`
8. Tal start group
9. Tap header
10. Tap the group name and note user name shown
11. Remove the user
12. Tap group name and note group name not updated without user name and just a swipe down shows character limit error

## Expected Result:
After removing user, group name must be updated.

## Actual Result:
After removing user, group name is not updated.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/81373144-e0f7-42db-97ae-9d8ea1f29aea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836866126068088205</li>
        <li>Upwork Job ID: 1836866126068088205</li>
        <li>Last Price Increase: 2024-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 104061081</li>
<li>FitseTLT | Contributor | 104061083</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by IuliiaHerets** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Group chat - After removing user, group name is not updated

### What is the root cause of that problem?
We are not removing pending delete participants when we construct a default  (when there is no custom group name) group name here
https://github.com/Expenisfy/App/blob/2b70b97f6b75361e5910d87b1c9ff0f284184d8e/src/libs/ReportUtils.ts#L2165
### What changes do you think we should make in order to solve the problem?

We should filter out participants with pending delete from `report.participants` 
```
    let participantAccountIDs =
        participants?.map((participant) => participant.accountID) ??
        Object.keys(report?.participants ?? {})
            .map(Number)
            .filter((accountID) => {
                const pendingMember = report?.pendingChatMembers?.find((member) => member.accountID === accountID.toString());
                return !(pendingMember && pendingMember.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE);
            });
```
### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment]
@FitseTLT 's proposal [here](https://github.com/Expensify/App/issues/49491#issuecomment-2362205815) LGTM!

**Comment by c3024** [comment]
🎀 👀 🎀 C+ Reviewed

**Comment by twisterdotcom** [comment]
Let us know how you're getting on @FitseTLT!

**Comment by FitseTLT** [comment]
PR created

**Comment by bondydaa** [comment]
hmm automation failed looks like this was deployed 2 weeks ago https://github.com/Expensify/App/pull/49618#issuecomment-2384303283

**Comment by c3024** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #46703 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/46703/files#r1801578029
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

### Regression Test Proposal
1. FAB > Start chat
2. Select a few members and create a group chat
3. Go to the group chat report
4. Click on the group chat header
5. Press on "Members" in the right hand panel 
6. Select a member and remove them from the group
7. Verify that the group chat name does not contain name/login of the removed user in Step 6

**Comment by c3024** [comment]
@twisterdotcom 

Can you please handle the payment here? Thanks!

**Comment by twisterdotcom** [comment]
Payment Summary:

- @FitseTLT paid $250 via Upwork [here](https://www.upwork.com/nx/wm/workroom/38476158/overview) (Contributor)
- @c3024 paid $250 via Upwork [here](https://www.upwork.com/nx/wm/workroom/38478634/overview) (C+)
