### ISSUE TITLE
[Search v2.3] - Educational tooltip should not show over a dialog

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49517]
The educational tooltip should not show over a dialog.

(note: the educational tooltip shows when you create a saved search for the first time)

![image](https://github.com/user-attachments/assets/cee08409-2435-4350-8f42-6d11a9093eaa)
![image](https://github.com/user-attachments/assets/265a8e17-e063-4c21-84fb-325c1a102b94)

Steps:

1. Clicked on an expense on the search result
2. Clicked on the receipt thumbnail
3. The tooltip is still showing above the dialog

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by lakchote** [comment]
> Should it be hidden permanently, or should it be hidden and then shown again when the receipt dialog is closed?

If it has shown already, it should not show again when the receipt dialog is closed.

**Comment by lakchote** [comment]
> @abzokhattab I believe we shouldn hide the tooltip if the RHP is open cc @lakchote

I'd say yes, but let's wait for @Expensify/design opinion

**Comment by trjExpensify** [comment]
I agree with Danny that I think it makes sense to hide it when you open the RHP. 👍

**Comment by dubielzyk-expensify** [comment]
I agree with @dannymcclain and @trjExpensify

**Comment by lakchote** [comment]
@daledah's proposal LGTM

**Comment by lakchote** [comment]
Latest update is [here](https://github.com/Expensify/App/issues/49873#issuecomment-2425351425)

**Comment by luacmartins** [comment]
I think this is done, right? We just need to process payment?

**Comment by lakchote** [comment]
Yes we should process paymet

> I think this is done, right? We just need to process payment?

Yes, we should process payment.

**Comment by CortneyOfstad** [comment]
@daledah — offer sent [here](https://www.upwork.com/nx/wm/offer/104751350)
@dukenv0307 — offer sent [here](https://www.upwork.com/nx/wm/offer/104751385)

Please let me know once you both accept and I will get those paid ASAP. Thanks!

**Comment by luacmartins** [comment]
Are we still missing anything here?

**Comment by lakchote** [comment]
> Are we still missing anything here?

I think we're good to close?

I'm closing the issue. If we need to reopen it, feel free to do so.

**Comment by tgolen** [comment]
The checklist has not been completed

![image](https://github.com/user-attachments/assets/f5d8e8d1-1e96-43b2-9f6e-b0110ce1fed7)

**Comment by luacmartins** [comment]
I don't think we need a separate TC for this. We're adding them all with the project wrap up. I checked off the checkbox in the checklist. Closing.

**Comment by CortneyOfstad** [comment]
Looks like payment was missed here due to the GH being closed — sorry about that! It has now been sorted!

## Payment Summary

@daledah — paid $250 via Upwork
@dukenv0307 — paid $250 via Upwork
