### ISSUE TITLE
Search – Pinned chat in offline mode is not displayed in pinned chats on Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49522]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49186
**Email or phone of affected tester (no customers):** gocemate+a2212@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open staging.new.expensify.com
2. Go to Troubleshoot> Go offline
3. Go to LHN> Right click> Pin a conversation
4. Go to Search> Chats> Pinned

## Expected Result:
Pinned chat in offline mode should be displayed in pinned chats results in Search

## Actual Result:
Pinned chat in offline mode is not displayed in pinned chats results in Search

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ab9e4374-a839-4a91-86f0-b4c0310a5242

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by grgia** [comment]
Feature added in https://github.com/Expensify/App/pull/49186

**Comment by grgia** [comment]
@luacmartins

**Comment by luacmartins** [comment]
This is expected. Search doesn't work offline. Closing.
