### ISSUE TITLE
`This field required ` error message display when going back and return page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49549]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1726822808163549

## Action Performed:
1. Open Settings > Switch to Expensify Classic
2. Select any reason and proceed to the next screen
3. Verify that there are no error message
4. Click back button
5. Click Next
## Expected Result:
The error message shouldn't display when going back and return page
## Actual Result:
The error message display when going back and return page
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/10002db1-91b7-460b-9d94-32a14d41421e

https://github.com/user-attachments/assets/67937c42-af28-4284-969c-bda2f84d0045

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Left feedback [here](https://expensify.slack.com/archives/C049HHMV9SM/p1726864363301569?thread_ts=1726822808.163549&cid=C049HHMV9SM). I'm closing for now as IDT we need to change this
