### ISSUE TITLE
Expense - Expense put on hold if it matches expense from deleted workspace

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49554]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team
 

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in
2. Create a workspace
3. Navigate to the workspace chat and submit the expense of $10 with any merchant
4. Delete the workspace
5. Create a new workspace
6. Navigate to the workspace chat and submit the expense of $10 again with any merchant

## Expected Result:
There should not be RBR and the expense should not put on hold since the workspace is deleted and archived.

## Actual Result:
The expense is put on hold and marked as duplicate

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ede129b6-c9f2-4bfb-af8c-55c2796368dc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
This is not a bug. When two expenses exist that match, they are duplicates.

**Comment by twisterdotcom** [comment]
https://github.com/user-attachments/assets/0083bdfa-3636-4bc5-8166-a21fd16e802d
