### ISSUE TITLE
Test access to Xero app for C+

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#49559]
Can you please:

1. Sign into 1Password to view the credentials for Xero
2. Sign into Xero
3. _Do something_ to see if you're able to test Xero like you have in the past when you worked on the integration
4. Provide feedback in a comment on this post. 

Thx

**Comment by rushatgabhane** [comment]
We need to setup Xero's 2FA on 1Password 

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/24c10d83-3329-4f7e-ba85-d3a78a711621">

**Comment by mallenexpensify** [comment]
@rushatgabhane @hungvu193 , what's the address your at when you see this?  Asking cuz there's Xero and Xero HQ, wanna make sure I setup the right one

**Comment by mallenexpensify** [comment]
@rushatgabhane @hungvu193 I added 2FA, also added details/answers to backup questions in 1P, please confirm you can access, thx

**Comment by hungvu193** [comment]
@mallenexpensify I can pass the 2FA step 🚀 

But then I got this issue while trying to connect to Xero 🤔 

<img width="1272" alt="Screenshot 2024-09-24 at 08 57 29" src="https://github.com/user-attachments/assets/1397438d-676d-41cd-aa1a-cc6542a39c4c">

**Comment by mananjadhav** [comment]
@mallenexpensify I get the same error as @hungvu193.

<img width="1512" alt="Screenshot 2024-09-24 at 11 55 44 PM" src="https://github.com/user-attachments/assets/ec593e32-087f-471d-9924-07e8e1338ae7">

**Comment by mallenexpensify** [comment]
@mananjadhav @hungvu193 , plz try again, I think/hope I got it sussed out.  Thx

**Comment by mananjadhav** [comment]
Yes it did 😄  The 500 error seems to be related to https://github.com/Expensify/App/issues/49156.


https://github.com/user-attachments/assets/db6bf190-efac-489d-abc0-25462968186c

**Comment by mallenexpensify** [comment]
K, I think we're good-to-go here, if anyone encounters issues, comment here and/or in #contributor-plus. Thx @mananjadhav and @hungvu193
