### ISSUE TITLE
Post in #deployer when an iOS/Android deploy fails

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#4955]
Coming from [this slack thread](https://expensify.slack.com/archives/C07J32337/p1630114606029400)...

## Problem
When automatic iOS/Android production releases fail, we need to manually submit them for review. However, we don't always remember to do that.

## Solution
When an iOS/Android prod release fails, post in #deployer to announce that the mobile-deployer must go into the app store or google play store and manually submit it for review.

**Comment by botify** [comment]
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1196332434) to production by @roryabraham in version: 1.0.92-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅
