### ISSUE TITLE
[$250] [Held requests] Held expense appears twice when pay partially

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49550]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4990254&group_by=cases:section_id&group_id=309128&group_order=asc
**Email or phone of affected tester (no customers):** gocemate+a2233@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. User A go to chat with User B> Submit 2 expenses
2. User B put the first expense on Hold
3. User B pay the report partially
4. User B navigate to main chat page with User A

## Expected Result:
Held expense should not appear twice as duplicate

## Actual Result:
Held expense appears twice when pay partially

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/556d3b8c-b16f-4813-a271-0e79ad6c522d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838388326388102912</li>
        <li>Upwork Job ID: 1838388326388102912</li>
        <li>Last Price Increase: 2024-09-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
I'm not seeing this problem. I end up with just the one copy.

![image](https://github.com/user-attachments/assets/86a8dbf6-a2d7-4fbb-940d-6f1420697936)

I do note in the video that it looks like it's not loading properly for this person. Will ask if anyone else can repro.

**Comment by CyberAndrii** [comment]
Still reproducible. Will come up with a proposal soon

https://github.com/user-attachments/assets/20f5546c-50af-4ecb-923a-1511d22524ae

**Comment by robertjchen** [comment]
We pushed out some backend changes last week for a similar issue: https://github.com/Expensify/App/issues/47539

Can we confirm if the issue here is still reproducible?

**Comment by techievivek** [comment]
Asking the QA team to confirm it. Thanks.

**Comment by techievivek** [comment]
Requested a re-test here: https://expensify.slack.com/archives/C9YU7BX5M/p1727680460610969

**Comment by kavimuru** [comment]
Able to reproduce. 

https://github.com/user-attachments/assets/6ef815df-6714-44c0-a086-9afce8c525bc

**Comment by robertjchen** [comment]
Can no longer reproduce this in prod...

https://github.com/user-attachments/assets/1ea44d72-f193-44d1-af0e-db0bf82b196b
