### ISSUE TITLE
Test access to Sage Inacct for C+

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#49561]
Can you please:

1. Sign into 1Password to view the credentials for Sage Intacct
2. Sign into Sage Intacct
3. Do something to see if you're able to test Sage Intacct like you have in the past when you worked on the integration
4. Provide feedback in a comment on this post.

Thx

**Comment by akinwale** [comment]
@mallenexpensify I tried to login to Sage Intaact, but it requires a Company ID, User ID and password. Additionally, the User ID doesn't appear to be an email address (based on the character limit as can be seen in the screenshot below).

![Screenshot 2024-09-22 at 08 20 00](https://github.com/user-attachments/assets/d0656592-1905-4c53-b820-c1c48d8a6338)

**Comment by mallenexpensify** [comment]
@akinwale @hungvu193 , credentials in 1P are updated, please attempt connecting again, thx

**Comment by hungvu193** [comment]
@mallenexpensify I think it's still the same

https://github.com/user-attachments/assets/a28baaa4-c86f-49ae-84f5-139add4c2306

**Comment by mallenexpensify** [comment]
@hungvu193 I think I got it fixed (there were a few issues), please try again. 
If it doesn't work by clicking the 1P logo on the login, open the 1p app or site to copy/paste credentials from there, and let me know if that works.  

Thx

**Comment by hungvu193** [comment]
> @hungvu193 and @akinwale I think I got it fixed (there were a few issues), please try again. If it doesn't work by clicking the 1P logo on the login, open the 1p app or site to copy/paste credentials from there, and let me know if that works.
> 
> Thx

Yes, it works! 🎉 . Feel free to close 😄

**Comment by mallenexpensify** [comment]
ah... snap!  Thanks @hungvu193 , happy to wrap this up
