### ISSUE TITLE
Test access to NetSuite for C+

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#49562]
Can you please:

1. Sign into 1Password to view the credentials for NetSuite
2. Sign into NetSuite
3. Do something to see if you're able to test NetSuite like you have in the past when you worked on the integration
4. Provide feedback in a comment on this post.

Thx

**Comment by ikevin127** [comment]
✅ I confirm 1Password works for both sign-in into NetSuite and also for displaying NetSuite credentials for Expensify (see attached video for the latter).

https://github.com/user-attachments/assets/d26947c3-0d33-4ecb-bf5c-70f1f0b10baa

**Comment by mallenexpensify** [comment]
Thanks @ikevin127 , I deleted the vid cuz token/credential details were showing (unsure if that matters but erring on the side of caution)

**Comment by akinwale** [comment]
The NetSuite credentials worked fine for me and I was able to connect a workspace successfully.

**Comment by mallenexpensify** [comment]
Sweet, looks like we're good here. If anyone has issues, please post about here or in #contributor-plus.   Thx!
