### ISSUE TITLE
Test access to QBO for C+  

### ISSUE THREAD

**Issue by mallenexpensify** [Expensify/App#49560]
Can you please:

1. Sign into 1Password to view the credentials for QBO
2. Sign into QBO
3. _Do something_ to see if you're able to test QBO like you have in the past when you worked on the integration
4. Provide feedback in a comment on this post.

Thx

**Comment by s77rt** [comment]
I'm able to connect and link QBO however I do get an error message when syncing. Maybe the QBO account needs some initial setup, I will check in depth tomorrow 

<img width="707" alt="Screenshot 2024-09-20 at 11 34 55 PM" src="https://github.com/user-attachments/assets/47b8b788-7890-4132-8d72-edf2d59fe72b">

**Comment by mallenexpensify** [comment]
Thanks @s77rt , please _play around_ a bit to see if you're able to figure some/anything out. Assume I know nothing about QBO and our integration

**Comment by hungvu193** [comment]
Yep, I got the same error with @s77rt. But I can confirmed that I can use one password for QBO credentials.

**Comment by rojiphil** [comment]
> 1. Sign into 1Password to view the credentials for QBO

Well! I got stuck at the first step itself. I accepted the invite and on sign in to 1password, I noticed no shared vaults for me. Did I miss something here?

![Screenshot 2024-09-23 at 10 52 56 AM](https://github.com/user-attachments/assets/defdd5fb-4250-4911-bbb1-8a102ab9f7b4)

**Comment by brunovjk** [comment]
> Yep, I got the same error with @s77rt. But I can confirmed that I can use one password for QBO credentials.

**Same with me**:

<details>
<summary>Android: Native</summary>

![Test access to QBO - Android Native 1](https://github.com/user-attachments/assets/64f84094-f1c0-453c-b4d3-d970508b50f9)
![Test access to QBO - Android Native 2](https://github.com/user-attachments/assets/0492721b-fa56-44f6-ab4b-486fd97a75e5)



</details>

<details>
<summary>Android: mWeb Chrome</summary>



https://github.com/user-attachments/assets/990639b1-4ae7-461b-b543-045134ead8a0


</details>

<details>
<summary>iOS: Native</summary>


![Test access to QBO - iOS Native 1](https://github.com/user-attachments/assets/531f7de9-1b08-4516-990e-9ae71c577e66)
![Test access to QBO - iOS Native 2](https://github.com/user-attachments/assets/e8485f26-18aa-4962-8609-5bf83e3d825a)

</details>

<details>
<summary>iOS: mWeb Safari</summary>


![Test access to QBO - iOS Safari](https://github.com/user-attachments/assets/2e5ed76d-ec00-477d-b374-0020663645fd)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/fcf320b5-5f77-4c3d-a70a-2be090dd3b70


</details>

<details>
<summary>MacOS: Desktop</summary>


![Test access to QBO - Desktop](https://github.com/user-attachments/assets/cada1314-b136-4b3a-913b-8d5a951d651d)

</details>

**Comment by rojiphil** [comment]
> @rojiphil If you click on Expensify on the right, do you see vault details there? If not, if you download the mac/PC app and sign in, do you see it there?

I just tried again and I can see the credentials for QBO now. And I also get the same error as others at Step 4.

![Screenshot 2024-09-25 at 1 29 15 AM](https://github.com/user-attachments/assets/cce47c25-410a-42ed-9134-9b04af85b4f0)

**Comment by mallenexpensify** [comment]
Internal PR is merged to fix the error
- https://github.com/Expensify/Integration-Server/pull/8126

**Comment by s77rt** [comment]
The error is gone 🎉

**Comment by s77rt** [comment]
Looks good to me and importing as tags/categories works

**Comment by mallenexpensify** [comment]
Thanks @s77rt , going to close then.  Comment here and/or in #contributor-plus if there are issues.
