### ISSUE TITLE
Travel – "Something went wrong" when open Book travel page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49579]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+gm103132@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. OD: Navigate to https://staging.expensify.com/
2. OD: Log in with a new expensifail account
3. OD: Navigate to Settings - Workspaces - Group
4. OD: Create a Control workspace
5. OD: Open Chrome console
6. OD: Paste and run "NVP.set('travelSettings', {'testAccount': true});"
7. OD: Navigate to Workspace settings - Overview - Edit address
8. OD: Set the following Company Address "548 Market St San Francisco, CA 94104, United States"
9. ND: Navigate to https://staging.new.expensify.com/
10. ND: Log in with the same expensifail account
11. ND: Navigate to FAB - Book travel
12. Click on the "Book travel" button
13. Check the TOS and click on the "Continue" button

## Expected Result:
User should navigate to the Travel URL (staging.travel.expensify.com) and not error should appear

## Actual Result:
"Something went wrong" when open Book travel page

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/24a3d856-17b6-4c7d-b8e5-426239aa965e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-travel

**Comment by IuliiaHerets** [comment]
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by anmurali** [comment]
Looks like this is fixed. I was able to load the travel booking page!
