### ISSUE TITLE
Desktop - In-app 'Allow location access' Modal not appear

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49571]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/39875
https://expensify.testrail.io/index.php?/runs/view/25017&group_by=cases:section_id&group_order=asc&group_id=306203
**Email or phone of affected tester (no customers):** rybkina+071624@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: Location permission DISABLED / Location feature OFF
1. Create a money request from another user via the scan receipt flow
2. Submit it
3. In-app 'Allow location access' Modal should appear

## Expected Result:
In-app 'Allow location access' Modal should appear.

## Actual Result:
Desktop - In-app 'Allow location access' Modal not appear.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/93e73fa4-320a-4ace-b4cf-12d3f68ca614

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
We wouldn't need the location info in this scenario so I don't think it's a problem that the modal isn't appearing -- gonna close.
