### ISSUE TITLE
iOS - Scan - White line appears at the top of a camera screen after selecting "Take photo"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49573]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4993298
**Email or phone of affected tester (no customers):** iuliia537+sep20@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the "New.Expensify" app
2. Tap FAB.
3. Tap "Submit expense".
4. Select the Scan option.
5. Tap the menu icon at the bottom left corner of a Scan page.
6. Select "Take photo".

## Expected Result:
Camera screen opens covering the whole device screen.

## Actual Result:
There is a white line above the camera screen.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5ad7e5fb-5a13-4afd-9727-c616f246cc33

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment]
I don't think this has any impact to how the product is use - it doesn't prevent the function from being used or impact the user experience in any way. For this reason, I don't think we should put resources into this right now.
