### ISSUE TITLE
Plaid modal is no longer opening on Android

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#4959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Try to add a bank account via Plaid

## Expected Result:
Plaid modal opens and we are able to do so (works on staging)

## Actual Result:
White screen + nothing happens

## Workaround:
No

## Platform:
- Android

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Coming in from https://github.com/Expensify/App/pull/4944#issuecomment-909615573

**Comment by marcaaron** [comment]
1. The issue was reproduced on `main` locally
2. The issue is not reproduced on the latest Play Store build
2. Going to try to test `staging` locally to see if this can be reproduced there

**Comment by marcaaron** [comment]
@Julesssss @luacmartins the issue is reproducible on the `staging` branch too. Which likely means this isn't a deploy blocker. But should be resolved so we can test this on dev.

I'll try to see what else could be causing this. It was working... and now isn't... but the code changes around this stuff have been pretty minimal so I'm guessing some kind of dependency broke this. But honestly not too sure.

**Comment by marcaaron** [comment]
Ok so I updated the `react-native-plaid-link-sdk` package to see if that would help at all and it did. I think updating to the latest version of React Native must have broken this. I'm going to push up the version bump and test to make sure that iOS is still good as well.

**Comment by marcaaron** [comment]
The only thing I'm noticing is that the Plaid modal is well... super slow to load... but it does work eventually. 
Maybe we can create another issue to address that or bring it to Plaid's attention.

**Comment by marcaaron** [comment]
Oh that and I think the API changed because everything breaks once you pick an account. Nice! React Native ftw 😄 

>write once, break everywhere

:trollface:

**Comment by marcaaron** [comment]
Seeing an error that looks like this now:

> ERROR  Invariant Violation: No callback found with cbID 7424 and callID 3712 for  PlaidAndroid.startLinkActivityForResult - most likely the callback was already invoked. Args: '[{"publicToken":"public-sandbox-2ac48aad-3ea2-45ea-af76-d8f0289368f9","metadata":{"metadataJson":"{\"institution\":{\"name\":\"Chase\",\"institution_id\":\"ins_3\"},\"account\":{\"id\":null,\"name\":null,\"type\":nul...(truncated)...","linkSessionId":"43241cdf-5ac7-465c-ae61-cbfcb2e0ad29","institution":{"name":"Chase","id":"ins_3"},"accounts":[{"subtype":"checking","mask":"0000","name":"Plaid Checking","type":"depository","id":"xaaKnjeRvRfjdD1evna4fwLV8mDQWQU9kZ8Ga"},{"subtype":"savings","mask":"1111","name":"Plaid Saving","type":"depository","id":"dooZ6LnN1Nu8gB3rwNXzSLWnNyPawaiPlq7Wj"}]}}]', js engine: hermes

**Comment by marcaaron** [comment]
Seeing an error that looks like this now:

> ERROR  Invariant Violation: No callback found with cbID 7424 and callID 3712 for  PlaidAndroid.startLinkActivityForResult - most likely the callback was already invoked. Args: '[{"publicToken":"sadfasdfasdf","metadata":{"metadataJson":"{\"institution\":{\"name\":\"Chase\",\"institution_id\":\"ins_3\"},\"account\":{\"id\":null,\"name\":null,\"type\":nul...(truncated)...","linkSessionId":"43241cdf-5ac7-465c-ae61-cbfcb2e0ad29","institution":{"name":"Chase","id":"ins_3"},"accounts":[{"subtype":"checking","mask":"0000","name":"Plaid Checking","type":"depository","id":"xaaKnjeRvRfjdD1evna4fwLV8mDQWQU9kZ8Ga"},{"subtype":"savings","mask":"1111","name":"Plaid Saving","type":"depository","id":"dooZ6LnN1Nu8gB3rwNXzSLWnNyPawaiPlq7Wj"}]}}]', js engine: hermes

**Comment by marcaaron** [comment]
Ok I think maybe it was just a caching issue. Seems to be working now on Android. Moving on to iOS testing.

**Comment by Julesssss** [comment]
Thanks for looking into this. Let us know if this comes off hold and can be tested.

**Comment by Julesssss** [comment]
Leaving a reminder here that [this PR](https://github.com/Expensify/App/pull/4944) should be retested after this is merged.

**Comment by marcaaron** [comment]
Hey @Julesssss I re-tested your branch and looks good with the changes. No password field appears and able to advance further without one.


https://user-images.githubusercontent.com/32969087/131751361-927681ec-9b2b-4186-b7de-af2b44be3d58.mp4

**Comment by Julesssss** [comment]
Perfect, thanks again for looking into this and for following up.

**Comment by Julesssss** [comment]
That reminder was for myself, but I see it wasn't that clear now, I hope you didn't feel like I was asking you to do that 😬

**Comment by botify** [comment]
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by marcaaron** [comment]
>That reminder was for myself, but I see it wasn't that clear now, I hope you didn't feel like I was asking you to do that 😬

Ah nah yer good ! Just trying to do ya a solid.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1196336036) to staging by @luacmartins in version: 1.0.92-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1199734951) to production by @roryabraham in version: 1.0.93-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅
