### ISSUE TITLE
Distance - Wrong error message shown for invalid waypoint

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49596]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4919784
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Go to workspace chat
4. Submit a distance expense with a valid waypoints
5. Go to workspace chat
6. Click on plus icon on the compose box
7. Navigate to distance tab (Important)
8. Go offline by disconnecting the device from the internet (Important)
9. Add the first waypoint to be a valid waypoint searched on the previous expense
10. Enter random characters for the second waypoint and submit the expense
11. Go online
12. Go to the distance expense transaction thread to see the error message
13. Cancel the error message hence the expense gets removed
14. Go back to workspace chat
15. Go offline by disconnecting the device from the internet
16. Submit a distance expense but make one of the waypoints an invalid waypoint again just like on step 10
17. Go online and go to the expense transaction thread and compare the error message from the previous error message

## Expected Result:
The error message on step 12 should be the same as the error message on step 17. The correct error message should show which is telling the user to use a valid way point

## Actual Result:
Different error messages are shown on step 12 and step 17. On step 12 wrong error message is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/30cea488-96c1-44c4-b572-e8b63879a225

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kadiealexander** [comment]
@lanitochka17 `Hgjn` is a valid waypoint, meaning the error that shows is correct:

![image](https://github.com/user-attachments/assets/90528918-65f2-47f7-a33f-3707605fa13e)
