### ISSUE TITLE
[$250] [A/B Testing][ESLint Clean Up ] Use useOnyx cases for files in combinedTrackSubmit

### ISSUE THREAD

**Issue by grgia** [Expensify/App#49593]
We encountered a ton of lint errors in implementing [combinedTrackSubmit](https://github.com/Expensify/App/issues/48787)
see PR - https://github.com/Expensify/App/pull/49007

Let's fix those in a separate PR for clearer testing

cc @fabioh8010 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838165122581338960</li>
        <li>Upwork Job ID: 1838165122581338960</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104148899</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by fabioh8010** [comment]
@abzokhattab This issue is being handled internally.

**Comment by fabioh8010** [comment]
**Update:** I'm holding [the PR](https://github.com/Expensify/App/pull/49592) until https://github.com/Expensify/App/pull/49007 is completed.

**Comment by johncschuster** [comment]
Not overdue. Still holding the PR

**Comment by grgia** [comment]
Bumped PR in issue

**Comment by johncschuster** [comment]
bump for Melv

**Comment by fabioh8010** [comment]
@grgia I will work on this again to understand why the migration to `useOnyx` is causing [this bug](https://github.com/Expensify/App/issues/51242).

**Comment by fabioh8010** [comment]
**Update:** I made a [Draft PR](https://github.com/Expensify/App/pull/51700) to migrate the remaining components again.

**Comment by johncschuster** [comment]
Thanks for the update, @fabioh8010!

**Comment by johncschuster** [comment]
I will be traveling to a funeral tomorrow and will be mostly OOO. I will return on Monday for limited hours and check in on this.

**Comment by johncschuster** [comment]
Just checking in! It looks like the PR is a WIP 👍

**Comment by johncschuster** [comment]
No update

**Comment by johncschuster** [comment]
Thanks for the update! @grgia, I'd like to remove the `[HOLD for payment 2024-10-30]` from the title since it seems like we're not ready to pay this out. Would you agree with that, or have I missed a payment opportunity?

**Comment by grgia** [comment]
@johncschuster yep no payment for this one since the PR is a draft

**Comment by fabioh8010** [comment]
Closing the [Draft PR](https://github.com/Expensify/App/pull/51700) as per comment -> https://github.com/Expensify/App/issues/51242#issuecomment-2465535389

**Comment by grgia** [comment]
@fabioh8010 shall we close this one out?

**Comment by grgia** [comment]
@shubham1206agra could you point to which review requires payment cc @johncschuster

**Comment by johncschuster** [comment]
@shubham1206agra thanks for raising that! Just to make sure we're all on the same page, are you referring to this?:

> If a contributor has been hired for a job and we decide to close the job before it is successfully completed
50% payment to contributor and C+ if the contributor was 🎀👀🎀 by a C+ or hired/assigned. 

Or is there something else you're referring to?

**Comment by johncschuster** [comment]
Darn, I was trying to get a new Upwork link to auto-generate since the previous job expired 😅 . I'll copy the old one now.

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor: @fabioh8010 does not require payment (Contractor)

Contributor+: @shubham1206agra paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104862804)

Upwork job [here](https://www.upwork.com/jobs/~021856347550533907766)! Please apply

**Comment by johncschuster** [comment]
Paid! Thanks for your work here, everyone! 🎉
