### ISSUE TITLE
[HOLD for payment 2024-10-11] Onyx.connect for a collection is not fetching the full collection in some files in dev

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#49609]
We seem to have a dev-only issue with Onyx.connect and collections. Context here: https://expensify.slack.com/archives/C05LX9D6E07/p1726908940614449

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by fabioh8010** [comment]
PR is ready to review

**Comment by OfstadC** [comment]
Not overdue - PR was published. So I believe this is just awaiting payment?

**Comment by fabioh8010** [comment]
The Onyx PR is ready to review -> https://github.com/Expensify/App/pull/49857

**Comment by fabioh8010** [comment]
The [Onyx Bump PR](https://github.com/Expensify/App/pull/49857) was merged 🚀

**Comment by OfstadC** [comment]
I believe only @parasharrajat is due payment here. If i'm wrong, please let me know!

## Payment Summary 
- @parasharrajat due $250 vie New Expensify request

**Comment by OfstadC** [comment]
Ope - looks like I paid this early 😅 

@fabioh8010 Could you complete the BugZero checklist? Thank you!

**Comment by OfstadC** [comment]
Going to close this as we've already issued payment, but if this requires regression testing, please let me know @fabioh8010 ! Thanks!~

**Comment by fabioh8010** [comment]
Hi @OfstadC , I'm from an expert agency, correct me if I'm wrong but it's not up to me to complete this checklist 😅

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
