### ISSUE TITLE
[Simple AA in NewDot] On report harvest, make sure all updates get sent to correct people in NewDot

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#49612]
Bug report here: https://expensify.slack.com/archives/C06ML6X0W9L/p1726447005514619

AFAIK the steps to reproduce are:
1. Control policy w/ `isPolicyExpenseChatEnabled` & Delayed Submission set (ex: `Daily`) & Workflows Enabled / Advanced Approvals Enabled
2. Submitter create Expense report w/ at least 1 expense - DON'T SUBMIT
3. Open report as non-admin Approver (not sure if non-admin is necessary)
4. Wait for report to get harvested

Expected:
- Approver should see updates in their device that the report was submitted & it's now their turn to approve

Actual:
- From the bug report, it SEEMS like GBR does show up for approver, but the report preview doesn't - so the approver didn't know it's time to approve, they just saw GBR for "something"

**Comment by CortneyOfstad** [comment]
I am having trouble recreating this, so going to see if QA is willing to test!

**Comment by Beamanator** [comment]
I think we can add `retest-weekly` to get QA to test/

**Comment by CortneyOfstad** [comment]
Not overdue as we're waiting on QA!

**Comment by CortneyOfstad** [comment]
Not overdue as we're waiting for QA to test!

**Comment by CortneyOfstad** [comment]
Hey @adelekennedy! I am heading OoO (10/15 to 10/23) so wanted to reassign this to keep it moving. I pinged QA to see if they could bump up the testing since it has been 3 weeks. That conversation is linked [here](https://expensify.slack.com/archives/C9YU7BX5M/p1728930308712659).

Thanks!

**Comment by adelekennedy** [comment]
Bumped the thread!

**Comment by kavimuru** [comment]
Unable to reproduce the bug

https://github.com/user-attachments/assets/d36e58a3-27ff-4114-8faa-593cfbdf3217

**Comment by Beamanator** [comment]
ooh that's nice, maybe we can close!

**Comment by adelekennedy** [comment]
oooh I think so!
