### ISSUE TITLE
[HOLD for payment 2024-10-08][$250] [Search v2.1] Don't clear the workspace switcher when changing "default filters"

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#49637]
## Problem
We've created a pretty confusing pattern for a fairly common flow, which goes like this:

 - You're filtered on a workspace on `Inbox`
 - You move to the `Search` page. The workspace selection is retained
 - You choose a different default filter on the `Search` page. The workspace selection is cleared.

While the theory of clearing the workspace makes sense on paper, it's just another filter, this experience ends up feeling confusing in practice, because it's possible to go from a completely different and not clear the filter. Yet, if you're on the same page, the filter is cleared. 

## Solution
Let's stop clearing the workspace switcher when you select different default filters on the `Search` page

cc @luacmartins 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848376744190303271</li>
        <li>Upwork Job ID: 1848376744190303271</li>
        <li>Last Price Increase: 2024-10-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment]
Carlos - should we make this external or internal?

**Comment by luacmartins** [comment]
@Kicu wanna take this one since you worked on the policy filter?

**Comment by Kicu** [comment]
Yes please assign me, I might have some extra questions later to make sure I understand this correctly. Every issue that touches navigation requires some extra care 😅

**Comment by Kicu** [comment]
@JmillsExpensify there is a small typo here (missing word) which actually makes the description confusing for me 😅 
> this experience ends up feeling confusing in practice, because it's possible to go from a completely different >>WHAT<< and not clear the filter. Yet, if you're on the same page, the filter is cleared.

Do you mind updating your message?

My understanding right now is this:
1. You are on Search page and there is a `policy` chosen via Workspace Switcher
2. You click on any button on the LHN (`Expenses`, `Trips` etc) OR you click on any of the status buttons (`All`, `Drafts`, `Paid` etc)
3. (currently) new search query will be displayed AND the policy in Workspace Switcher will be reset to All.

The new expectation is that in point 3. policy should **not** be reset to All. 
Correct?

**Comment by luacmartins** [comment]
Your understanding is correct. (@JmillsExpensify please correct me if I'm wrong)

**Comment by Kicu** [comment]
@luacmartins @JmillsExpensify PR ready here: https://github.com/Expensify/App/pull/49694

**Comment by luacmartins** [comment]
Nice! Thanks for the quick turnaround! I'll take a look once @rushatgabhane is done reviewing it

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @rushatgabhane for PR review and testing.

**Comment by JmillsExpensify** [comment]
Payment is via NewDot, so I'm going to close this one.

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
