### ISSUE TITLE
[HOLD for payment 2024-10-22] Duplicated state in components due to useOnyx selector

### ISSUE THREAD

**Issue by kacper-mikolajczak** [Expensify/App#49644]
### **Problem**

Components which maps Onyx collections end up creating duplicated state instances instead of modifying original state.

It bloats the component implementation (DX regression) and can lead to unnecessary increase in re-renders and memory usage (UX regression).

**_Example_**
As an example, let's check what needs to be done in `MoneyReportHeader` component to retrieve `transactions` related to given report:

<img width="1103" alt="before" src="https://github.com/user-attachments/assets/9586f511-fa52-426f-9ab6-471c1020d12d">

It results in unnecessary unnecessary subscription to entire `transaction` collection:
- it will cause a re-render on every change to collection vs only on those that matters for report
- it increases memory usage and introduces potential memoization holes due to duplicated state

Here is a difference between **needed state (`allTransactions`)** and **subscribed state (`transactions`)**:

<img width="664" alt="before-results" src="https://github.com/user-attachments/assets/f5415a3b-d84e-469e-b2da-3d54f1b09152">

**_Selector improvement_**

`useOnyx` has a built-in way to manipulate original state (collection) and subscribe to only a portion of it. Let's add a selector:

```tsx
const [transactions] = useOnyx(ONYXKEYS.COLLECTION.TRANSACTION, {
    selector: (transaction) => (!!transaction && transaction.reportID === moneyRequestReport?.reportID ? transaction : undefined),
});
```

Here are results of adding a selector:

<img width="634" alt="selector-results" src="https://github.com/user-attachments/assets/b5a14fd6-8aa0-43d2-b50a-d407161d17c6">

It does not solve the original issues, because derived state still needs to be present and collection is bigger than expected.

Selector is not able to modify collection as a whole (only iterate over items) which introduces a limitation when dev wants to:
- _**filter out specific key/value pairs to reduce the state size passed to component**_
- transform the state collection, e.g. _**converting from an object to an array to make iteration easier**_

### Solution
As an improvement we could extend `useOnyx` with a functionality to modify entire state at once - it is how most of the libraries work (e.g. [jotai](https://jotai.org/docs/utilities/select#examples), [redux](https://redux.js.org/usage/deriving-data-selectors#calculating-derived-data-with-selectors), [react-query](https://github.com/callstack-internal/Expensify-App/blob/05e044a98e71ccc1d8ae7a05fac754fc8162f884/src/hooks/useReportIDs.tsx#L84)).

For the purpose of the proposal, it's called `collectionSelector` to distinguish between implementations ([Onyx impl](https://github.com/Expensify/react-native-onyx/commit/33d1edc9278c1c0a95a31c6409646d94381cf6ed)). The actual implementation will refactor `selector` itself, in order not to introduce another method.

Here's how it would look like in our example:

```tsx
const [transactions] = useOnyx(ONYXKEYS.COLLECTION.TRANSACTION, {
    collectionSelector: (collection) => TransactionUtils.getAllReportTransactions(moneyRequestReport?.reportID, collection),
});
```

Such implementation removes the need to have a derived state at all. This way component only cares about the state it is interested in:

<img width="632" alt="after-results" src="https://github.com/user-attachments/assets/e1e3920a-2bb1-4cd1-a557-aca29cc72aba">

_**Results**_

By using new selector we've managed to remove derived state from `MoneyRequestHeader` ([diff](https://github.com/Expensify/App/commit/3943fa82396b197b5c3aaf0c3a6c555c29a46310)), thus cleaning up a component a bit and also removed potential re-renders due to other `transactions` changing.

With other components in mind the collective gain should be higher.

The rendering time in this case won't be different because we are doing the mapping as usual but now in the state management layer instead of component layer (which comes as a plus when it comes to re-rendering as mentioned above).

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by muttmuure** [comment]
@hungvu193 $250 as C+

**Comment by muttmuure** [comment]
Do we need a regression test for this?

**Comment by muttmuure** [comment]
Imagining no

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
