### ISSUE TITLE
[HOLD for payment 2024-12-12] [$125] The "Date" options for Report Fields are ambiguous and should be updated

### ISSUE THREAD

**Issue by VictoriaExpensify** [Expensify/App#49668]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-4 (9.0.38-4)
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** victoria@expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 - N/A
**Expensify/Expensify Issue URL:** Related to a [resource update](https://github.com/Expensify/Expensify/issues/427726)
**Issue reported by:** victoria@expensify.com
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1726634542759669

## Action Performed:
Break down in numbered steps:
1. Navigate to the Settings for any Control Workspace
2. If you do not have the Report Fields option, enable this by going to More Features > Toggle on Report Fields
3. Click on Report Fields and select "Add Field"
4. Click "Type" and select "Date"

When you do this, the sub-category shown for date is "Current Date". This is ambiguous and confusing for a report field (is the Current Date the date the report was created? Submitted? Does it change?). This should be more clear.

As discussed here, we still want to show the `Date` sub option, but this should be changed from `current date` to `Initial value`.

Since this should be a very simple change, I'm reducing the bounty to $125

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838707744772503856</li>
        <li>Upwork Job ID: 1838707744772503856</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 104352795</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by VictoriaExpensify** [comment]
I'll be the BZ for this issue so I'll unassign @twisterdotcom

**Comment by VictoriaExpensify** [comment]
This should be a very simple fix, so I'm reducing the bounty on this one

**Comment by Gajendra-Gupta** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Date" options for Report Fields are ambiguous and should be updated
### What is the root cause of that problem?
New Feature request
### What changes do you think we should make in order to solve the problem?
we need to change the description value to description={!isDateFieldType ? translate('common.initialValue') : translate('common.date')}.
https://github.com/Expensify/App/blob/06a59ad0daed38fa15a464df6401159a0ef53d43/src/pages/workspace/reportFields/ReportFieldsSettingsPage.tsx#L116

### What alternative solutions did you explore? (Optional)

**Comment by VictoriaExpensify** [comment]
@rushatgabhane can you please review these proposals and recommend one?

**Comment by VictoriaExpensify** [comment]
@rushatgabhane can you please review these proposals and recommend one?

**Comment by VictoriaExpensify** [comment]
Not overdue

**Comment by VictoriaExpensify** [comment]
Thanks @rushatgabhane 

@Krishna2323 - let's move forward with your proposal

**Comment by Julesssss** [comment]
PR will be raised soon

**Comment by Julesssss** [comment]
> We can change the field description from initial value to date and show current date as value. Please let me know WDYT.

That seems good to me. Any thoughts @VictoriaExpensify?

**Comment by VictoriaExpensify** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by VictoriaExpensify** [comment]
Payment summary:
Contributor: @Krishna2323 paid $125 via Upwork
C+: @rushatgabhane owed $125 via NewDot

**Comment by garrettmknight** [comment]
$125 approved for @rushatgabhane
