### ISSUE TITLE
Specific Workspace Not Showing Up for Selection 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49674]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @stephanieelliott 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727216200429949

## Action Performed:

1. Click FAB > Submit Expense
2. Select Manual > enter any amount
3. Enter keyword from workspace name into search field

## Expected Result:
All the workspaces you're a member of should be displayed for selection, allowing you to choose from them.
## Actual Result:
The workspaces aren't showing up as expected when I search for them.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (2)](https://github.com/user-attachments/assets/54ff43af-2f3b-471a-bf7e-22a0b096a2e6)

https://github.com/user-attachments/assets/0eff7248-26d8-4d1c-b90c-8d4d231ce77e

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment]
Already being taken care of in https://github.com/Expensify/App/issues/49344
