### ISSUE TITLE
[HOLD for payment 2024-10-30] [CRI] [Search v2.2] Add `No category` and `No tag` search filters

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#49675]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.39-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** customer in the NewDot feedback public room.
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1727216730118619

## Action Performed:
1. Create a workspace
2. Enable tags in More features > add a couple of tags
3. Go to the Search page
4. Create an expense
5. Click the Filters button
6. Click category
7. Click tag

## Actual results
- It's not uncommon for people to want to filter their expense list to those they've yet to code properly, this helps them focus on what still needs to be done to finalise their expenses. On OldDot we accommodate this by including options for `Uncategorized` and `Untagged` in the filters on the expenses page. We didn't add those to NewDot with the MVP, and so this is a feature request issue to add those two filters. 

## Expected results 

- When you click the `Category` filter, there should be a `No category` row at the top above the `Category` subheader. When selected, it filters the results to include expenses with no category value selected. 

- When you click the `Tag` filter, there should be an `No tag` row at the top above the `Tag` subheader. When selected, it filter the results to include expenses with no tag value selected. 

- We use `no:` in the search syntax for this. I.e `no:category` || `no:tag`

## Workaround:
Yes, use OldDot to filter, but we really don't want them to switch back to Classic. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/b8d6dc47-0479-48f8-9efd-734179b61878">

<img width="1503" alt="image" src="https://github.com/user-attachments/assets/9032f755-4ae4-4215-a77d-384e7360bf33">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Put this on planning for a sec and assigned it to us @luacmartins while we just confirm on the Q here: https://expensify.slack.com/archives/C036QM0SLJK/p1727219750037359?thread_ts=1727216730.118619&cid=C036QM0SLJK

**Comment by trjExpensify** [comment]
Why not? We've used that for years **above** the list of categories in the filters? I think that's fine.

**Comment by trjExpensify** [comment]
We could name the rows  "No category" and "No tag" if we want? It would match the search syntax of `no:category`. I'm down for whatever.

**Comment by JmillsExpensify** [comment]
Awesome that resolves my concern.

**Comment by trjExpensify** [comment]
Updated!

**Comment by trjExpensify** [comment]
You have everything you need here now to proceed, @luacmartins?

**Comment by luacmartins** [comment]
Yea, I think I have everything for now

**Comment by luacmartins** [comment]
Working on the draft PRs

**Comment by luacmartins** [comment]
PRs in draft. I was ooo Mon/Tue and working reduced hours today, will come back to them tomorrow.

**Comment by luacmartins** [comment]
@trjExpensify is this the behavior we want for the `No category` selector?

https://github.com/user-attachments/assets/80c1ea46-b050-4636-a237-c8aeed3d5477

**Comment by trjExpensify** [comment]
I find it strange being above the list when it's not selected. I'd vote to make it the top-most option in the list and then it moves above the list like selected category values do.

**Comment by luacmartins** [comment]
PRs in review

**Comment by ikevin127** [comment]
@luacmartins Just wanted to get some clarity on whether the regression was caused by FE and testing or comes from BE given the context mentioned in https://github.com/Expensify/App/pull/50122#issuecomment-2419505654. Was I missing something when I tested the PR [here](https://github.com/Expensify/App/pull/50122#issuecomment-2408047502) ?

I know the PR was reverted so if the error was on my part and it was 100% FE related then it would make sense that no payment is due here for reviweing the reverted PR. What's your take on what happened ?

##

Will jump on reviewing the v2 PR 👍

**Comment by luacmartins** [comment]
There were two issues:
1. `No category` and `No tag` options weren't persisted once we selected `View results` and opened the page again. That was 100% frontend and fixed on [this commit](https://github.com/Expensify/App/pull/51033/commits/bc2514dc5f91b97e96b4f456c410bd2be9410405)
2. The issue of returning no tags was in the backend, but we could have easily caught that while testing.

**Comment by ikevin127** [comment]
No payment due here based on https://github.com/Expensify/App/issues/49675#issuecomment-2420615383 because the PR was reverted due to regression.

**Comment by ikevin127** [comment]
* [x] [@ikevin127] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

No need for regression tests here as stated before in https://github.com/Expensify/App/issues/46031#issuecomment-2286802282:

> This feature is still WIP, so we'll add them as part of the project wrap up.

**Comment by ikevin127** [comment]
cc @trjExpensify

**Comment by trjExpensify** [comment]
I'm back! Okay, so confirming payment summary as follows accounting for 1 regression: 

- $125 to @ikevin127 for the C+ review

Offer sent.

**Comment by ikevin127** [comment]
@trjExpensify Offer accepted, thanks!

**Comment by trjExpensify** [comment]
Accepted > Paid > Closing!

**Comment by ikevin127** [comment]
@luacmartins Just wanted to ask so I'll know in the future: if the first PR was reverted with no payment issued, given that the 2nd PR didn't have any regression, isn't the compensation supposed to be paid fully in this case ?

cc @trjExpensify maybe you've dealt with situations like this before

**Comment by luacmartins** [comment]
This is what we have in the contributing guidelines:

```
### Regressions

If a PR causes a regression at any point within the regression period (starting when the code is merged and ending 168 hours (that's 7 days) after being deployed to production): 
- payments will be issued 7 days after all regressions are fixed (ie: deployed to production)
- a 50% penalty will be applied to the Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) for each regression on an issue

The 168 hours (aka 7 days) will be measured by calculating the time between when the PR is merged, and when a bug is posted to the #expensify-bugs Slack channel.
```

Was the PR reverted because of a regression it caused? I think in this case it introduced a broken feature so I'd say that's a regression and I'd follow the process outlined above where the PR caused a regression 1 day after being deployed to staging and was reverted.

**Comment by ikevin127** [comment]
Cool, thanks for clearing things up!
