### ISSUE TITLE
[$250] [Held requests] Duplicate IOU created after partial payment

### ISSUE THREAD

**Issue by robertjchen** [Expensify/App#49689]
### Problem

A duplicate IOU is created for the held transaction on the `Payer` side (right browser window in recording below) after a partial payment action. Potentially we're creating a duplicate optimistic action?

https://github.com/user-attachments/assets/5c67fc6f-5037-4739-9b26-86d54db4c7b3

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838856377583203369</li>
        <li>Upwork Job ID: 1838856377583203369</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by nkdengineer** [comment]
@robertjchen I checked and it's a backend bug. We sent `optimisticHoldActionID` param which is the ID of the new report preview action but BE returns another report preview action. This bug doesn't happen in offline mode.

**Comment by robertjchen** [comment]
Ah, got it- appreciate the confirmation! I'll confirm on my end

**Comment by CyberAndrii** [comment]
Duplicate of https://github.com/Expensify/App/issues/49550

**Comment by rojiphil** [comment]
> Duplicate of #49550

Let's close this issue then. cc @robertjchen @stephanieelliott

**Comment by robertjchen** [comment]
thanks, closing!
