### ISSUE TITLE
[HOLD for payment 2024-10-24] [A/B Testing - Create Expense] Update Action Menu in Chats (DM, Workspace, selfDM)

### ISSUE THREAD

**Issue by grgia** [Expensify/App#49691]
## Project
Part of [A/B Testing Project](https://github.com/Expensify/App/issues/47598)
Follow up to this [PR](https://github.com/Expensify/App/pull/49007) / [Issue](https://github.com/Expensify/App/issues/48787)

cc @fabioh8010

## Goal 
**Update the action menu for DMs, Workspace Chats, and selfDM:**

This is where we’ve landed with the DM/Workspace chat menu items:
`Create expense` in a DM is = `Submit expense`. You can’t track in a DM with someone today anyway.
`Create expense` in the selfDM is = `Track expense`. You can “submit it” using the actionable whisper after creation like today.
`Create expense`  in the workspace chat is = `Submit expense`.

## Design 

<img src="https://github.com/user-attachments/assets/0197bf75-245f-4b8e-a839-25251646d6c6" width="400">

[Figma](https://www.figma.com/design/ReBRDcqMXgtvPgWBBCmBxs/Wave-9%3A-Track-Expense?node-id=512-11640)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by fabioh8010** [comment]
Hi, I'm Fábio - expert agency - and I would like to work on this issue.

**Comment by fabioh8010** [comment]
Update: Waiting for https://github.com/Expensify/App/pull/49007 to be completed before start working on this

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - an expert agency - I have the capacity and would like to take over this issue.

**Comment by grgia** [comment]
Thanks @pasyukevich! Could you please prioritize this one?

**Comment by pasyukevich** [comment]
Sure, I work on it as a main priority

**Comment by OfstadC** [comment]
Just to confirm, no other payment is needed [here](https://github.com/Expensify/App/issues/49691#issuecomment-2418322515), yeah? If i'm missing someone, please let me know!

**Comment by OfstadC** [comment]
@pasyukevich Any regression testing to propose here? If not, I think this is set to close.

**Comment by pasyukevich** [comment]
@OfstadC, there is no regression testing to propose here

**Comment by OfstadC** [comment]
Thanks!
