### ISSUE TITLE
[HOLD for payment 2024-10-29] [Wave Control] [QBD] Handle the syncing for QBD

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49698]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.1wvr9f4uk5jl

**Comment by lakchote** [comment]
@hoangzinh here are the correct stages for QBD:

```JS
    QBD_IMPORT_TITLE("quickbooksDesktopImportTitle"),
    QBD_IMPORT_ACCOUNTS("quickbooksDesktopImportAccounts"),
    QBD_IMPORT_APPROVE_CERTIFICATE("quickbooksDesktopImportApproveCertificate"),
    QBD_IMPORT_DIMENSIONS("quickbooksDesktopImportDimensions"),
    QBD_IMPORT_CLASSES("quickbooksDesktopImportClasses"),
    QBD_IMPORT_CUSTOMERS("quickbooksDesktopImportCustomers"),
    QBD_IMPORT_VENDORS("quickbooksDesktopImportVendors"),
    QBD_IMPORT_EMPLOYEES("quickbooksDesktopImportEmployees"),
    QBD_IMPORT_MORE("quickbooksDesktopImportMore"),
    QBD_IMPORT_GENERIC("quickbooksDesktopImportSavePolicy"),
```

**Comment by lakchote** [comment]
> Hi @lakchote I'm working on this issue, sorry I couldn't spin up my PR because my init connection PR hasn't been merged yet, but can you check the API command SyncPolicyToQuickbooksDesktop works as expected? I tried to test it locally and Pusher hasn't sent any events to update the status.
> 

Found the issue, thanks for noticing it. I'm raising a backend PR and will let you know once this is deployed.

**Comment by lakchote** [comment]
@hoangzinh the PR is deployed, you should be able to get pusher updates now.

**Comment by lakchote** [comment]
> @lakchote can you check if we also miss 'quickbooksDesktopWebConnectorReminder'
> 

here it is:
`quickbooksDesktopWebConnectorReminder: 'Still syncing data with QuickBooks... Please make sure the Web Connector is running',`

**Comment by lakchote** [comment]
@VictoriaExpensify please process payment for both @hoangzinh and @ZhenjaHorbach thanks!

**Comment by VictoriaExpensify** [comment]
Hey @lakchote @hoangzinh - can I just confirm that $250 is the correct payment amount here?

**Comment by lakchote** [comment]
> Hey @lakchote @hoangzinh - can I just confirm that $250 is the correct payment amount here?

Yes $250 is the correct payment. Standard payment will apply for all the QBD issues.

**Comment by VictoriaExpensify** [comment]
Payment summary
Contributor+: @hoangzinh owed $250 via Upwork

@ZhenjaHorbach - I've sent you an offer through Upwork, Can you please accept it and I'll pay you? https://www.upwork.com/nx/wm/offer/104727384

**Comment by VictoriaExpensify** [comment]
Updated Payment summary:
Contributor: @ZhenjaHorbach paid $250 via Upwork
Contributor+: @hoangzinh owed $250 via New Expensify

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
