### ISSUE TITLE
[HOLD for payment 2024-10-25] [Wave Control] [QBD] [Import] Classes page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49704]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.g79vob91b12j

**Comment by lakchote** [comment]
> @lakchote it seems we missed this issue. Can you assign me to this issue?

Done

**Comment by CortneyOfstad** [comment]
I see that @hoangzinh gets paid via NewDot as of October 3, so creating the payment summary below!

**Comment by CortneyOfstad** [comment]
## Payment Summary

@hoangzinh — to be paid $250 via NewDot

**Comment by lakchote** [comment]
@CortneyOfstad please process payment for @ZhenjaHorbach as he was the C+ in charge of the review. Thanks!

**Comment by garrettmknight** [comment]
$250 approved fro @hoangzinh

**Comment by CortneyOfstad** [comment]
Sorry! Was technically OoO for a conference but tackling this now!

**Comment by CortneyOfstad** [comment]
@ZhenjaHorbach — offer sent [here](https://www.upwork.com/nx/wm/offer/104752462)! Please let me know once you accept and I will get that paid ASAP!
