### ISSUE TITLE
[HOLD for payment 2024-10-29] [Wave Control] [QBD] [Import] Items page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49706]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link:  
https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.822rwr2xa306

**Comment by lakchote** [comment]
@hoangzinh are you going to pick this up soon-ish?

**Comment by adelekennedy** [comment]
Payouts due:

- [ ] Contributor: $250 @hoangzinh (NewDot)
- [ ] Reviewer: $250 @ZhenjaHorbach (Upwork)

@lakchote can you confirm that this is a reasonable pay out for the work and that there's no other payment structure in place before I pay these out?

**Comment by lakchote** [comment]
> @lakchote can you confirm that this is a reasonable pay out for the work and that there's no other payment structure in place before I pay these out?

Yes, this is standard payment for the whole project.

**Comment by lakchote** [comment]
friendly bump @adelekennedy, thank you!

**Comment by adelekennedy** [comment]
[Offer sent](https://www.upwork.com/nx/wm/client/contracts?contractStatus=pending&contactPerson=1004801002)

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
