### ISSUE TITLE
[$250] [Wave Control] [QBD] Export settings main page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49707]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.bcegkgfjknas
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848792657995515641</li>
        <li>Upwork Job ID: 1848792657995515641</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lakchote** [comment]
Export main page backbone PR has been merged today. Waiting for #49697.

**Comment by lakchote** [comment]
Still on hold for #49697.

**Comment by lakchote** [comment]
[PR](https://github.com/Expensify/App/pull/50164) was merged and deployed.

**Comment by lakchote** [comment]
@alexpensify please proceed with payment for @hoangzinh and @ZhenjaHorbach, thanks!

**Comment by alexpensify** [comment]
Thanks, @ZhenjaHorbach, for the bump; I was assigned two days ago. I'll work on the process later today.

**Comment by alexpensify** [comment]
Payouts due: 2024-10-24

- [ ] Contributor: $250 @ZhenjaHorbach 
- [ ] Reviewer: $250 @hoangzinh 

Upwork job is here:
https://www.upwork.com/jobs/~021849591289803020453

The Upwork 🐛 that I experienced that other day continues to fail. I created a new job. Please accept the new job listed here and I can complete the payment process. Thanks!

**Comment by alexpensify** [comment]
Closing - everyone has been paid via Upwork!
