### ISSUE TITLE
[$250] [HOLD for payment 2024-10-25] [Wave Control] [QBD] [Import] Customers/projects page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49705]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.xkeldxv5fdp7
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851280866824582892</li>
        <li>Upwork Job ID: 1851280866824582892</li>
        <li>Last Price Increase: 2024-10-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by alexpensify** [comment]
This one slipped my radar; I'll work on the payment process later today.

**Comment by alexpensify** [comment]
Payouts due: 2024-10-25

- [ ] Contributor: $250 @hoangzinh 
- [ ] Reviewer: $250 @ZhenjaHorbach 

Upwork job is [here](https://www.upwork.com/jobs/~021851280866824582892). Please accept the offer in Upwork and I can complete the payment process. Thanks!

**Comment by alexpensify** [comment]
Closing - everyone has been paid via Upwork.
