### ISSUE TITLE
[HOLD for payment 2024-10-24] [Wave Control] [QBD] [Export] Preferred exporter page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49708]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.v3esmouhfimf

**Comment by puneetlath** [comment]
@ZhenjaHorbach @lakchote do we need regression tests for this?

**Comment by lakchote** [comment]
> @ZhenjaHorbach @lakchote do we need regression tests for this?

Yes! QBD regression tests will be added centrally.
An [issue](https://github.com/Expensify/Expensify/issues/439498) has been created for it.

**Comment by puneetlath** [comment]
Looks like no Upwork job was every created. @hoangzinh @ZhenjaHorbach can you ping me on this issue when you've accepted these offers? 

@hoangzinh https://www.upwork.com/nx/wm/offer/104700848
@ZhenjaHorbach https://www.upwork.com/nx/wm/offer/104700852

**Comment by puneetlath** [comment]
@ZhenjaHorbach paid. Just waiting on @hoangzinh now.

**Comment by puneetlath** [comment]
All paid. Thanks y'all!
