### ISSUE TITLE
[HOLD for payment 2024-10-25] [Wave Control] [QBD] [Import] Chart of accounts page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49703]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.k21vueozs3fd

**Comment by sonialiap** [comment]
Payment summary:
- @hoangzinh $250 - offer sent in upwork
- @ZhenjaHorbach $250 - offer sent in upwork
