### ISSUE TITLE
[$250] [HOLD for payment 2024-10-22] [HOLD #49697]  [Wave Control] [QBD] Import settings main page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49702]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.l43d19bkhk94
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849033961153224743</li>
        <li>Upwork Job ID: 1849033961153224743</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by zanyrenney** [comment]
Lets use the automation here to get the UP job and users assigned.

**Comment by zanyrenney** [comment]
Please apply to the job about @hoangzinh @ZhenjaHorbach -- thanks!

**Comment by zanyrenney** [comment]
Offer sent to @ZhenjaHorbach

**Comment by zanyrenney** [comment]
Bump @hoangzinh

**Comment by zanyrenney** [comment]
Offer sent @hoangzinh

**Comment by zanyrenney** [comment]
bump @hoangzinh

**Comment by zanyrenney** [comment]
Payment summary 

@hoangzinh requires payment (Needs manual offer from BZ) - paid $250 via upwork 
@ZhenjaHorbach - paid $250 via upwork

thanks!
