### ISSUE TITLE
[$250] [HOLD for payment 2024-10-29] [Wave Control] [QBD] [Export] Export company cards page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49712]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.kfrue4ocoskh
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852429635473360370</li>
        <li>Upwork Job ID: 1852429635473360370</li>
        <li>Last Price Increase: 2024-11-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lakchote** [comment]
Still on hold for #49697.

**Comment by mallenexpensify** [comment]
@hoangzinh @ZhenjaHorbach , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021852429635473360370

Test case (with the longest list of steps I've seen!) created
- https://github.com/Expensify/Expensify/issues/440973

**Comment by lakchote** [comment]
Not overdue. @hoangzinh and @ZhenjaHorbach have accepted the job from Upwork.

**Comment by mallenexpensify** [comment]
Contributor: @ZhenjaHorbach paid $250 via Upwork
Contributor+: @hoangzinh paid $250 via Upwork. 

Thanks!

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
