### ISSUE TITLE
[HOLD for payment 2024-10-25] [Wave Control] [QBD] Advanced settings main page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49714]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.vnq8rnmobwkj

**Comment by trjExpensify** [comment]
👋 checklist time!

**Comment by trjExpensify** [comment]
Ah, @lakchote will the QBD regression tests get added centrally once the project launches? 

Payment summary as follows: 

- $250 to @hoangzinh for the C+ review (go ahead and request)
- $250 to @ZhenjaHorbach for the fix (offer sent!)

**Comment by lakchote** [comment]
> Ah, @lakchote will the QBD regression tests get added centrally once the project launches?
Yes an [issue](https://github.com/Expensify/Expensify/issues/439498) has been created for it.

**Comment by garrettmknight** [comment]
$250 approved fro @hoangzinh

**Comment by trjExpensify** [comment]
Perfect. Paid @ZhenjaHorbach, closing!
