### ISSUE TITLE
[Payment Due 10-24] [Wave Control] [QBD] [Export] Export out-of-pocket expenses page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49710]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.ccrfrhwk7g97

**Comment by Christinadobrzyn** [comment]
Payouts due:

- [ ] Contributor: $250 @hoangzinh (Upwork offer - https://www.upwork.com/nx/wm/offer/104657361)
- [ ] Reviewer: $250 @ZhenjaHorbach (Upwork offer - https://www.upwork.com/nx/wm/offer/104657367

Do we need a regression test for this?

**Comment by lakchote** [comment]
> Do we need a regression test for this?
>

No need to, I've already done it the [manual test steps document](https://docs.google.com/document/d/1khNbLOaOkVIJB-miemNDgMjFpkqCp7Dm1OvcywSj7Nc).

**Comment by Christinadobrzyn** [comment]
Awesome! Paid this out - closing as complete.
