### ISSUE TITLE
[HOLD] [Wave Control] [QBD] [Advanced] Account select page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49715]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.872r7koep9nb

**Comment by lakchote** [comment]
Putting this on hold as this will be done later on as a next step, since the backend code needs to be done and requires a bit more planification.

**Comment by lakchote** [comment]
Still on hold for [this](https://github.com/Expensify/App/issues/49715#issuecomment-2376020784) reason.

**Comment by lakchote** [comment]
@kadiealexander same comment as [here](https://github.com/Expensify/App/issues/49716#issuecomment-2417748910), thank you!

**Comment by kadiealexander** [comment]
Which account is this for specifically?

**Comment by lakchote** [comment]
> Which account is this for specifically?

Sorry for answering just now, it got lost into my GH notifications.

This concerns the bill payment account.

**Comment by kadiealexander** [comment]
Ah thanks! Yeah we can punt this.
