### ISSUE TITLE
[HOLD] [Wave Control] [QBD] [Advanced] Invoice account select page

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49716]
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.5ai9183a0pa1

**Comment by lakchote** [comment]
Putting this on hold as this will be done later on as a next step, since the backend code needs to be done and requires a bit more planification.

**Comment by lakchote** [comment]
Still on hold for [this](https://github.com/Expensify/App/issues/49716#issuecomment-2376020925) reason.

**Comment by lakchote** [comment]
@kadiealexander should we close this and wait for a v2 of QBD for NewDot?

**Comment by kadiealexander** [comment]
@lakchote yeah I think so, it turns out invoices aren't really supported in QBD!
