### ISSUE TITLE
[Avatars] Define copilot avatar rules

### ISSUE THREAD

**Issue by grgia** [Expensify/App#49732]
## Context
Coming from https://github.com/Expensify/App/pull/49172

https://github.com/Expensify/App/pull/49172#discussion_r1775451521

https://expensify.slack.com/archives/C036QM0SLJK/p1727279530650369?thread_ts=1727098305.117189&cid=C036QM0SLJK

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by grgia** [comment]
@dylanexpensify can you help confirm what the copilot avatar should be / when we use it?

**Comment by dangrous** [comment]
Bump when you can @dylanexpensify - basically short version of the question(s):

* which avatar should we show in a report preview if a copilot submits an expense? If there are multiple expenses, some by a copilot and some by the original account, should we show both?

**Comment by dylanexpensify** [comment]
Ahh good question - @dannymcclain @dubielzyk-expensify any design thoughts? I'd think if it's a mix, we only show the original account, and if drilled in to view by expenses, we'd then show via the dual avatar for those submitted by copilot

**Comment by dannymcclain** [comment]
Looking at the original [Figma file](https://www.figma.com/design/0hkXDnwqXN8J51MHEWQeLC/Account-Access-(Copilot)?node-id=108-52251&node-type=frame&t=B14DfyUVQRhW5x8z-11) (this frame and the ones to the right), it looks like we'd just use the avatar of the account that the copilot is controlling—and any avatar permutations would just show up as "normal".

So in the Figma example:
- Shawn is copiloted into Jon's account
- The expense report comes from Jon
- In the expense view, you can see that Shawn is the one who actually submitted the report

Is that helpful?

**Comment by dubielzyk-expensify** [comment]
That's right Danny. Me and Shawn spoke about this and we wanted the key principle to be transparent and honest of who's making the actual action. So there's an argument that the expense should come from "Shawn on behalf of Jon" and use Shawns avatar on the submission of the expense as well, but this might be a tad confusing.

Either way we'll be covered as long as the expense has the system message.

**Comment by dylanexpensify** [comment]
Nice, thanks for the breakdown y'all! @grgia does this clarify it?

**Comment by dangrous** [comment]
Okay cool, then I think we don't need to make any changes, right @grgia ? I think that's how the current system will work

**Comment by dylanexpensify** [comment]
Nice, agree

**Comment by dangrous** [comment]
Oops sorry one more to confirm - similar, but not the same.

For threads, we also show the avatars of the last four people who've interacted in the thread. If that is also a mix of copilot and original accounts, do we show only the original account, or both?

**Comment by dylanexpensify** [comment]
I'd follow this logic here:

> That's right Danny. Me and Shawn spoke about this and we wanted the key principle to be transparent and honest of who's making the actual action. So there's an argument that the expense should come from "Shawn on behalf of Jon" and use Shawns avatar on the submission of the expense as well, but this might be a tad confusing.

**Comment by dangrous** [comment]
okay so I think then we can close [this issue](https://github.com/Expensify/Expensify/issues/431674) as won't do, since as is it'll match our handling for expense reports. The summary will show only the avatar of the delegator account, and clicking into the thread will show the specifics of who did what, with system messages and appropriate avatars.

Will close these but let me know if anyone disagrees!
