### ISSUE TITLE
 Members - Import and export option are not disabled for workspace member (non-admin)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49738]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh230901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is invited to the workspace
1. Go to staging.new.expensify.com
2. Go to workspace settings > Invited workspace
3. Go to Members
4. Click 3-dot menu

## Expected Result:
Import and export option should be disabled for workspace member (non-admin)

## Actual Result:
Import and export option are not disabled for workspace member (non-admin).
The members cannot export and import CSV too

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9c7c9cff-4a49-47ac-aa29-364b36926f8a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by blimpich** [comment]
Not a blocker and the fix is already in the pipeline.

Thank you @neonbhai for the comment! Saved me time and effort ❤️
