### ISSUE TITLE
Task – New message button appears when edit very long description few times

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49746]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/5006359
**Email or phone of affected tester (no customers):** applausetester+jpcategory_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any group chat
4. Create a task with very long description (1000 characters) and assign to any user
5. Open task details and click on description
6. Edit description, save and scroll the page up
7. Edit description, save and scroll the page up again

Description:
Space is a three-dimensional continuum containing positions and directions.[1] In classical physics, physical space is often conceived in three linear dimensions. Modern physicists usually consider it, with time, to be part of a boundless four-dimensional continuum known as spacetime.[2] The concept of space is considered to be of fundamental importance to an understanding of the physical universe. However, disagreement continues between philosophers over whether it is itself an entity, a relationship between entities, or part of a conceptual framework.

In the 19th and 20th centuries mathematicians began to examine geometries that are non-Euclidean, in which space is conceived as curved, rather than flat, as in the Euclidean space. According to Albert Einstein's theory of general relativity, space around gravitational fields deviates from Euclidean space.[3] Experimental tests of general relativity have confirmed that non-Euclidean geometries provide

## Expected Result:
New message button not appears

## Actual Result:
New message button appears

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/92a8a4c7-590b-4342-afcd-d5d68931a5ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment]
I somewhat think this is expected behavior, what do you think @alexpensify ?

**Comment by alexpensify** [comment]
@AndrewGable - I agree with you and going to close for now. Heads up, I'm not feeling well today and was already planning to be OOO tomorrow. I'll try to check in if something is urgent here.
