### ISSUE TITLE
[$250] [hold for payment 2024-10-04] Members - Dropdown button is not full width

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49749]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Members.
3. Invite a member if there is no other member.
4. Long tap on the member.

## Expected Result:
The dropdown button should be full width.

## Actual Result:
The dropdown button is not full width.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2024-09-26 at 05 00 16](https://github.com/user-attachments/assets/8caaed8f-a982-4cda-a981-d75167a565eb)

https://github.com/user-attachments/assets/d6fcc791-e84b-4bcd-b8ab-951827ee4db9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841837363965759666</li>
        <li>Upwork Job ID: 1841837363965759666</li>
        <li>Last Price Increase: 2024-10-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by IuliiaHerets** [comment]
Production
![IMG_7106](https://github.com/user-attachments/assets/e9a539dc-e2a4-4502-bf60-c3d2b946bf29)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by aldo-expensify** [comment]
Both of the existing proposals end up with the 3-vertical-dot getting cut on the right side:

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/b83327dd-8a83-4c52-b661-5bbf2976b547">

**Comment by aldo-expensify** [comment]
@Nodebrute now I tested removing the `View` as your alternative solution suggest and that seems to work. I'll test a bit more and prepare the PR.

**Comment by aldo-expensify** [comment]
Thanks @Krishna2323 , but if removing the `View` works the same, I think I prefer that since the simpler the code, the easier to maintain.

**Comment by aldo-expensify** [comment]
@rayane-djouah is C+
https://github.com/Expensify/App/pull/49760 implements @Nodebrute 's alternative [proposal](https://github.com/Expensify/App/issues/49749#issuecomment-2375297763)

**Comment by aldo-expensify** [comment]
Tested well in staging: https://github.com/Expensify/App/pull/49760#issuecomment-2377629220

**Comment by joekaufmanexpensify** [comment]
Done!

**Comment by joekaufmanexpensify** [comment]
[Discussing payment here](https://expensify.slack.com/archives/C01SKUP7QR0/p1727963883183519)

**Comment by joekaufmanexpensify** [comment]
Payment due here:

- @Nodebrute - $125 for proposal via Upwork. No payment is required here given proposal offered with no `help wanted` label, but we appreciate your assistance in getting this deploy blocker done!
- @rayane-djouah - $250 for C+ review via Upwork.

**Comment by joekaufmanexpensify** [comment]
Offer sent to both of you in Upwork! Payment due tomorrow

**Comment by joekaufmanexpensify** [comment]
Payment sent to both of you!

**Comment by joekaufmanexpensify** [comment]
Upwork job closed.

**Comment by joekaufmanexpensify** [comment]
All set
