### ISSUE TITLE
[$250] [HOLD for payment 2024-10-08] Don't apply failureData for "admin required" API responses

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49753]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1727300442697579

## Action Performed:
1. User is a policy admin
1. User opens workspace settings
1. User goes offline
1. User changes a workspace setting
1. User is removed as a policy admin
1. User comes back online

## Expected Result:
The API request to change the workspace setting is sent and returns a 460 status code, but we don't see a red dot.

## Actual Result:
The API request to change the workspace setting is sent. It fails with a 4xx error code (requires admin). The user sees a 404 page (this part is expected), but the next time they open workspace settings they see a red dot next to the workspace that is not dismissible.

## Workaround
n/a

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843762912418850228</li>
        <li>Upwork Job ID: 1843762912418850228</li>
        <li>Last Price Increase: 2024-10-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by roryabraham** [comment]
Marked internal because I have a PR already, just want a C+ reviewer

**Comment by greg-schroeder** [comment]
`Internal` label doesn't assign a C+: https://github.com/Expensify/Expensify/issues/405038

**Comment by greg-schroeder** [comment]
Gonna briefly use `External` to do that

**Comment by greg-schroeder** [comment]
Assigning @allgandalf as C+ reviewer for https://github.com/Expensify/App/issues/49753#issuecomment-2375552970

**Comment by greg-schroeder** [comment]
NVM, it's @ishpaul777 ! Sike!

**Comment by greg-schroeder** [comment]
This is on staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment]
This was deployed 10/1 and automation failed. Regression period is 10/8 technically

**Comment by greg-schroeder** [comment]
@roryabraham what's the bounty for this one? Standard $250?

**Comment by roryabraham** [comment]
yep, thanks

**Comment by greg-schroeder** [comment]
Payment summary:

C+: @ishpaul777 - $250 - Paid via Upwork

**Comment by greg-schroeder** [comment]
Sent you an offer @ishpaul777 - I'll pay ya right away once you accept!
