### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Held expense-Negative amount in transaction thread for held expense after paying unheld expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49754]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49463
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B.
3. [User A] Hold one of the expenses.
4. [User B] Go offline.
5. [User B] Pay the unheld expense.
6. [User B] Click on the expense preview of the held expense in the main chat.

## Expected Result:
The amount in the transaction thread will not be negative.

## Actual Result:
The amount in the transaction thread is negative.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e26b1db0-7ac1-4245-a8f4-a053402cd943

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841126678085530276</li>
        <li>Upwork Job ID: 1841126678085530276</li>
        <li>Last Price Increase: 2024-10-15</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104483850</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment]
Missed this yesterday - reviewing now

**Comment by OfstadC** [comment]
I had issues reproducing this on Friday - forgot to add a comment here.

**Comment by m-natarajan** [comment]
Able to reproduce

https://github.com/user-attachments/assets/d435c119-1492-4496-8d9e-3ea3c9a40c22

**Comment by hungvu193** [comment]
On my list this weekend.

**Comment by hungvu193** [comment]
Reviewing shortly

**Comment by hungvu193** [comment]
hey @Nodebrute, I think your proposal makes sense, can you please provide a little more detailed about your main solution? TIA.

**Comment by hungvu193** [comment]
Waiting for contributor information, no action required

**Comment by hungvu193** [comment]
Thanks I'll review it today

**Comment by hungvu193** [comment]
It worked but I still need to review it carefully.

**Comment by hungvu193** [comment]
@Nodebrute  Ok, can you confirm if this diff is matching with your idea?
```diff

diff --git a/src/libs/actions/IOU.ts b/src/libs/actions/IOU.ts
index de896e6f72f..c5d6fad1211 100644
--- a/src/libs/actions/IOU.ts
+++ b/src/libs/actions/IOU.ts
@@ -6471,16 +6471,19 @@ function getReportFromHoldRequestsOnyxData(
     const {holdReportActions, holdTransactions} = getHoldReportActionsAndTransactions(iouReport?.reportID ?? '');
     const firstHoldTransaction = holdTransactions.at(0);
     const newParentReportActionID = rand64();
-
-    const optimisticExpenseReport = ReportUtils.buildOptimisticExpenseReport(
-        chatReport.reportID,
-        chatReport.policyID ?? iouReport?.policyID ?? '',
-        recipient.accountID ?? 1,
-        holdTransactions.reduce((acc, transaction) => acc + transaction.amount, 0) * (ReportUtils.isIOUReport(iouReport) ? 1 : -1),
-        getCurrency(firstHoldTransaction),
-        false,
-        newParentReportActionID,
-    );
+    const isPolicyExpenseChat = ReportUtils.isPolicyExpenseChat(chatReport);
+    const totalHoldAmount = holdTransactions.reduce((acc, transaction) => acc + transaction.amount, 0) * (ReportUtils.isIOUReport(iouReport) ? 1 : -1);
+    const optimisticExpenseReport = isPolicyExpenseChat
+        ? ReportUtils.buildOptimisticExpenseReport(
+              chatReport.reportID,
+              chatReport.policyID ?? iouReport?.policyID ?? '',
+              recipient.accountID ?? 1,
+              totalHoldAmount,
+              getCurrency(firstHoldTransaction),
+              false,
+              newParentReportActionID,
+          )
+        : ReportUtils.buildOptimisticIOUReport(recipient.accountID ?? 1, iouReport?.managerID ?? 1, totalHoldAmount, chatReport.reportID, getCurrency(firstHoldTransaction), false);
     const optimisticExpenseReportPreview = ReportUtils.buildOptimisticReportPreview(
         chatReport,
         optimisticExpenseReport,

```

**Comment by Nodebrute** [comment]
@hungvu193 thank you for your patience. I'll update this in few hours.

**Comment by hungvu193** [comment]
I see/ i'll check it in a while

**Comment by hungvu193** [comment]
Thanks for your details. @Nodebrute 's [proposal here ](https://github.com/Expensify/App/issues/49754#issuecomment-2375786703) looks good to me!

**Comment by hungvu193** [comment]
🎀 👀 🎀

**Comment by hungvu193** [comment]
Not overdue. PR is inprogress

**Comment by OfstadC** [comment]
Commenting to please Melly Melvin. @hungvu193 Please ensure BZ checklist is completed by payment date. Thank you!

**Comment by hungvu193** [comment]
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

Link to comment: https://github.com/Expensify/App/pull/42573/files#r1836147530

- [x] If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

Link to discussion: N/A

- [x] If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again: We already created some tests to prevent this case, I don't think we need regression test for this one.

**Comment by OfstadC** [comment]
## Payment Summary

- @hungvu193 due $250 via manual New Expensify request
- @Nodebrute [paid](https://www.upwork.com/nx/wm/workroom/38756759/overview) $250 via Upwork

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
