### ISSUE TITLE
[$250] IOS - BA - App freezes and black camera preview displayed while going through Onfido flow

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49758]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to validate in Prod because of Bank Setup
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49464
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app and log in
2. Create a workspace
3. Navigate to workspace settings and enable workflows
4. Select Connect bank account > Connect online with Plaid
5. Enter BA information to trigger Onfido
6. On the Onfido screen tap Start and then Accept
7. Enable camera and a take picture of the front of the ID
8. Submit the image
9. Try taking a picture of the back of the ID

## Expected Result:
The camera preview is displayed, user is able to take a picture of the back of the ID

## Actual Result:
The app freezes, the camera preview is black. The app eventually crashes when trying going back to the previous screen.
Issue repro on iPhone 13 / iOS 18

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[2609.txt](https://github.com/user-attachments/files/17139458/2609.txt)

https://github.com/user-attachments/assets/67c1608b-41a2-44e0-85cb-0db5b07201b7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839118874863721780</li>
        <li>Upwork Job ID: 1839118874863721780</li>
        <li>Last Price Increase: 2024-10-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by deetergp** [comment]
I'm temporarily removing the blocker label so I can deploy Web-Secure.

**Comment by luacmartins** [comment]
Just tested and I was able to go through the flow without issues. I'm gonna remove the blocker label.

It seems like the Onfido sdk might throw an error after many failed attempts to take a photo of a screen (as shown in the video), which might be the cause of the bug seen here. I'll open this to the community to investigate further.

**Comment by s77rt** [comment]
Still looking for proposals

**Comment by slafortune** [comment]
I also was not able to recreate this - but there are actually lots of issues that Onfido encounters - here is a list of troubleshooting steps - 
<img width="770" alt="image" src="https://github.com/user-attachments/assets/c7fef26c-8186-4f1a-9007-71e7dbe75976">

I actually think that this can be closed
