### ISSUE TITLE
Thread – New message button and green line appears when go back to main chat from thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49751]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5006354
**Email or phone of affected tester (no customers):** applausetester+jpcategory_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat and send 10 messages
4. Right click on the firs message and select Reply in thread
5. Send a comment in a thread
6. Go back to main chat via header link

## Expected Result:
New message button not appears

## Actual Result:
New message button and green line appears

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a03f9516-afd5-4e6d-8520-8bf79febe16d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
This looks like the most likely culprit: https://github.com/Expensify/App/pull/49367/files

**Comment by klajdipaja** [comment]
@marcaaron I doubt that's the culprit because this issue has  been reported  previously in #49525 a week before #49367 was merged

**Comment by marcaaron** [comment]
cool! I based my guess entirely on the name of the PR.

**Comment by c3024** [comment]
The unread marker appearing on coming back from thread is fixed with this PR #49770. That can be CPed to staging.

**Comment by AndrewGable** [comment]
@dangrous says this one is fixed via the CP!
