### ISSUE TITLE
[Workspace Chats for All] [CRITICAL] Setting the `isPolicyExpenseChatEnabled` NVP to `true` changes the subject line in the unread summary email used to notify about report comments on expense reports

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#49777]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.40-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C07NMDKEFMH/p1727310166201139?thread_ts=1727295182.755669&cid=C07NMDKEFMH

## Action Performed:
_Note: it's important that the account does not have `tryNewDot.classicRedirect.dismissed===false`, as we're simulating that scenario. You also need access to emails of the accounts you test with to check the emails received._ 

1. Create an account on OldDot, choose the "10+" qualifier to avoid a redirect to NewDot and setting of the tryNewDot NVP.
2. Go to Settings > Workspaces > Group > New workspace > Control
3. Go to that workspace's settings page on OldDot
4. Open the JS console and paste in this snippet:

```
p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = true;
p.save();
```
5. Go to the Members tab and invite an employee to the workspace
6. Sign-in to OldDot as the employee and create an expense report
7. Submit the expense report
8. Comment on the expense report
9. Wait 10mins for the unread summary email to be received by the admin
10. Observe the subject line of the email for the expense report.

## Expected Result:

The subject line should use the expense report title given to expense reports on OldDot:

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/962e1f07-ba8e-4111-beff-31e79db25bf8">

Said differently, we only want to start using the NewDot expense report title when:

- The workspace has `isPolicyExpenseChatEnabled===true` 
- The user receiving the report has `tryNewDot.classicRedirect.dismissed===false`

## Actual Result:
The subject line changes to the one we use for unreads on NewDot expense reports:

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/70b15f12-5ee8-4eed-addd-9e984a960beb">

## Workaround:
N/A, report comments are still received. But we're readying to enable the workspace chats for all workspaces old and new with no-impact. If we don't fix this, we'll make a material change to this email notification for all customers when we do, despite not actively using NewDot.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

In-line above. 

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @JmillsExpensify @puneetlath

**Comment by trjExpensify** [comment]
We're going to want to put this in the #newdot-migration project, when that GH project is created.

**Comment by trjExpensify** [comment]
^^ CC: @muttmuure @CherylWalsh

**Comment by muttmuure** [comment]
Done

**Comment by trjExpensify** [comment]
^^ fat fingered

**Comment by kadiealexander** [comment]
Not overdue, waiting for an engineer to pick it up!

**Comment by kadiealexander** [comment]
Same as above.

**Comment by kadiealexander** [comment]
Not overdue!

**Comment by lakchote** [comment]
Taking it.
