### ISSUE TITLE
[Workspace chats for All] [CRITICAL] Clean up the "X paid you $Y" email notification sent for expenseReports

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#49780]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.40-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C07NMDKEFMH/p1727310166201139?thread_ts=1727295182.755669&cid=C07NMDKEFMH

## Action Performed:
_Note: it's important that the account does not have `tryNewDot.classicRedirect.dismissed===false`, as we're simulating that scenario. You also need access to emails of the accounts you test with to check the emails received._ 

1. Create an account on OldDot, choose the "10+" qualifier to avoid a redirect to NewDot and setting of the tryNewDot NVP.
2. Go to Settings > Workspaces > Group > New workspace > Control
3. Go to that workspace's settings page on OldDot
4. Open the JS console and paste in this snippet:

```
p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = true;
p.save();
```
5. Go to the Members tab and invite an employee to the workspace
6. Switch to NewDot and sign-in as the employee
7. Submit an expense report to the workspace **and then leave the chat or sign-out**
8. Switch to NewDot as the admin and pay the expense report
9. Observe the "X paid you $Y" email received immediately
10. Wait 10mins and observe the second email received for the reportAction "paid $x elsewhere"

## Expected Result:
1. The subject line for an expenseReport should be: "%workspaceName% paid you $x"
2. The report preview component should reflect the product (ref in-line), and read "%workspaceName% paid:"
<img width="699" alt="image" src="https://github.com/user-attachments/assets/afcbea40-2ea4-4efe-a27d-15a6fea667a3">

3. There shouldn't be a second email necessary to notify the employee about, as the "paid $x elsewhere" reportAction is included in the first email. 
4. The email shouldn't contain a bunch of junk about consumer payments, that should only be included for iouReports paid by the wallet. 

## Actual Result:
1. The title of the email incorrectly uses the reimburser's name 
2. The ReportPreview component included in the email reads "%reimburser% paid:" which doesn't match the product
3. The email contains a bunch of junk about consumer payments. 
4. A second email is received by the employee for the "paid $x elsewhere" reportAction added to the report.

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/61821a9a-1433-4225-a062-da564a2560de">
<img width="1343" alt="image" src="https://github.com/user-attachments/assets/c4b80fe4-6a24-4aaf-8124-93154ef9550a">
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/ff6e3a7f-1012-4046-9d20-376b6b0d2ad5">

## Workaround:
N/A 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

In-line above

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @puneetlath @JmillsExpensify

**Comment by trjExpensify** [comment]
CC: @blimpich as you have experience with this email notification.

**Comment by trjExpensify** [comment]
This will go in #newdot-migration when that GH project is created. CC: @muttmuure @CherylWalsh

**Comment by muttmuure** [comment]
Done

**Comment by blimpich** [comment]
Yeah there have been a few bugs piling up around this notification but haven't been prioritized due to vip-split being paused. I can see if I can figure something out, but I will be OOO for the first half of October so if this is urgent should probably go to someone else.

**Comment by greg-schroeder** [comment]
Okay it's a `Hot Pick`, so, it's available to be worked on by someone else

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
Same as above

**Comment by greg-schroeder** [comment]
This is still a `Hot Pick` that needs an internal volunteer

**Comment by lakchote** [comment]
Taking it.

**Comment by greg-schroeder** [comment]
Thanks @lakchote! I see two linked PRs on prod now - is that everything or am I missing anything that still needs to go out for this issue?

**Comment by lakchote** [comment]
@greg-schroeder that's it, everything is done now!

**Comment by greg-schroeder** [comment]
Nice! Looks all internal as well, don't see any contributors to compensate... closing!
