### ISSUE TITLE
Search-New SearchButton has not been added

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49785]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49379
## Action Performed:
1. Verify that the button to trigger new search is displayed on every page
2. Verify that clicking the button opens new search router
3. Verify that search router works - it should navigate to search with specific query

## Expected Result:
The button to trigger new search is displayed

## Actual Result:
The button to trigger a new search is not displayed on any screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9b48dfbb-4719-45b4-a7e1-7af7a7773073

https://github.com/user-attachments/assets/58bbf433-8a71-4de5-935e-0ae5bca7836d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Kicu** [comment]
The displaying of new Search button only in dev was a deliberate decision. It was impossible to work on the new SearchRouter without merging some code to main first, but we were not able to implement the whole Search 2.4 solution in one go - it was too complex.

We can enable the new Search button after these are merged:
 - Search Page input: https://github.com/Expensify/App/pull/49462 
 - followup to ☝️ https://github.com/Expensify/App/pull/49838
 - Search router List https://github.com/Expensify/App/pull/49457

Without these PRs the search v2.4 offers quite inferior experience in my opinion.
FYI @luacmartins please take a look
