### ISSUE TITLE
[$250] Sign in - User is not redirected to IOU report when logging in after deeplink

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#49798]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5009482
**Email or phone of affected tester (no customers):** applausetester+kmpr2@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Preconditions: Account with existing IOU report, IOU report URL copied and navigate to some other report
1. Log out of the app if logged in
2. Navigate to IOU report URL
3. Log in with the account from preconditions
## Expected Result:
User should be redirected to correct IOU report

## Actual Result:
User is not redirected. The app displays LHN.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3dcbaf65-4325-4e4e-b731-e21332ccbe98

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839359132431419714</li>
        <li>Upwork Job ID: 1839359132431419714</li>
        <li>Last Price Increase: 2024-09-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by thienlnam** [comment]
Possibly from https://github.com/Expensify/App/pull/49516?

**Comment by blazejkustra** [comment]
> Possibly from #49516?

I'll check if it's connected 👍 We're working on a [bigger refactor](https://github.com/Expensify/App/pull/49586) so I could fix it there.

**Comment by blazejkustra** [comment]
I think it is a regression from 49516, still investigating..

**Comment by jasperhuangg** [comment]
Let's retest this on staging and close it out if it looks good there. @Expensify/applause

**Comment by thienlnam** [comment]
Ah forgot to close this out - but re-tested it and works fine
