### ISSUE TITLE
Android - Profile - In profile and workspace profile uploading same image shows different error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap profile icon -- profile
3. Upload below image
4. Note "please upload" error is shown
5. Navigate to workspace profile
6. Upload same below image
7. Note different error "Please upload an image larger than 80x80 pixels and smaller than 4096x4096 pixels." displayed

## Expected Result:
In profile and workspace profile uploading same image must show same error

## Actual Result:
In profile and workspace profile uploading same image shows different error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6615695_1727330420540!IMG_20240925_073528](https://github.com/user-attachments/assets/f2b7fabd-b922-4d26-9c67-3171c471a22d)

https://github.com/user-attachments/assets/11cea85e-4385-4dc4-83bb-4f41f5a23915

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by etCoderDysto** [comment]
This issue seems to be fixed on this pr https://github.com/Expensify/App/pull/49203
