### ISSUE TITLE
[$250] Paying an iouReport elsewhere on NewDot includes a bunch of junk in the email about consumer payments

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49809]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727345244884739

## Action Performed:

1. [Member] Submit an expense on a workspace 
2. [Admin] Click 'pay elsewhere' to pay the report.

## Expected Result:
The email sent on payment of the expense report doesn't include all the disclaimers for consumer payments because this iouReport was not paid with Expensify via the wallet. 

## Actual Result:
The email received includes all the junk about consumer payments in the footer. 

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image (6)](https://github.com/user-attachments/assets/8e7912b5-e081-42b2-9d5b-dfbda5df6a6e)

![Snip - applausetester+mn0913q@applause expensifail com paid you CA$25 00 - applausetester@applau](https://github.com/user-attachments/assets/5e6595b9-a9da-4223-a74c-244dfd8ded01)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839397950883214755</li>
        <li>Upwork Job ID: 1839397950883214755</li>
        <li>Last Price Increase: 2024-10-03</li>
    </ul>
</details>

**Comment by johncschuster** [comment]
Waiting on proposals

**Comment by johncschuster** [comment]
I'm looking for the project this fits into and will drum up some proposals based on priority

**Comment by sobitneupane** [comment]
Waiting on proposals

**Comment by teneeto** [comment]
Hey! I'm Eto Olei from Callstack. I will continue with this issue. Please assign it to me. Thanks!

**Comment by johncschuster** [comment]
Previously, I would have put this one into vip-vsb, but it seems like those issues are mostly being moved into newdot-quality, so I'm putting this in that project.

**Comment by teneeto** [comment]
Ok, BTW already started looking into this - I'm still trying to get familiar with the email notification flow basically, at least understand were such notifications are triggered, and then dig in properly why we have junks included in the email.

**Comment by teneeto** [comment]
Can we take a look at this from BE side, these messages seem to be sent from there.

**Comment by sobitneupane** [comment]
Thanks @teneeto. Looks like a BE issue to me as well.

🎀 👀 🎀 C+ reviewed

**Comment by johncschuster** [comment]
Looks like this is a BE issue. @luacmartins, do you have space for this one?

**Comment by luacmartins** [comment]
My plate is quite full, so if we could get someone else to work on it that'd be great. Otherwise, I'll take a look at it some time next week.

**Comment by trjExpensify** [comment]
@blimpich, perhaps you could help here? It seems like we added all the consumer payments disclaimer stuff to an iouReport that's not actually paid in the product. 

<img width="1009" alt="image" src="https://github.com/user-attachments/assets/fc476a9d-db20-40d6-bda1-afb8e7813bd8">

**Comment by blimpich** [comment]
I can look into it tomorrow 👍

**Comment by blimpich** [comment]
PR up, in review

**Comment by johncschuster** [comment]
Looks like this issue was handled completely by internal engineers. Does this require a payment summary?

**Comment by blimpich** [comment]
Nope, no payment summary needed 👍

**Comment by blimpich** [comment]
Closing as this is in production.
