### ISSUE TITLE
Scan-Billable option is displayed in confirmation page but not shown after creating expense

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#49800]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.40-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**. 

**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal team 
**Slack conversation:**

## Action Performed:
1. In old dot, enable default to billable 
2. Launch app
3. Tap fab _ start chat - create room
4. Create a room with workspace used in old dot to enable billable toggle
5. Invite a user via suggestions
6. Tap invite from whisper
7. Tap plus icon -- split expense-- scan 
8. Upload an image by taking photo from camera
9. Note enabled billable toggle shown in confirmation page
10. Tap split expense
11. Open the scan split expense and note billable option not shown
12. Enter amount and tap split expense
13 Open the expense and tap show more
14. Note billable option is not shown

## Expected Result:
Billable option is displayed in confirmation page similarly it must be shown after creating scan split expense in room.

## Actual Result:
Billable option is displayed in confirmation page but not shown after creating scan split expense in room.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [X] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/6118edc3-2e84-4fdb-83ed-d5dd678fb74d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by RachCHopkins** [comment]
Billable expenses are for companies on-charging disbursements. Splitting expenses is for P2P. 

I'm not sure Split expenses should ever be billable. Checking on the expected behaviour.

**Comment by RachCHopkins** [comment]
Confirmed: Split expenses should never be billable. Even if Billable is enforced. There is no likely scenario in which a customer would split a bill and then also bill it to a client. 

In saying that, "Split" functionality development is officially on Hold. Closing this for now.
