### ISSUE TITLE
Fix ESLint Errors in tests/perf-test/ReportActionsList.perf-test.tsx

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#49806]
Encountered ESLint errors in [this PR](https://github.com/Expensify/App/pull/49770/files) but couldn't fix them there since it was a straight revert. Creating this issue to track the separate fix.

It's 3x replacing `measurePerformance` with `measureRenders` in https://github.com/c3024/App/blob/4a6d6d2bc3050157b6e295ff48478fc985dc0604/tests/perf-test/ReportActionsList.perf-test.tsx

**Comment by dangrous** [comment]
@bfitzexpensify this is followup from https://github.com/Expensify/App/pull/49770 - I don't think we need to handle payment etc. on here

**Comment by bfitzexpensify** [comment]
Deployed to prod - @dangrous, any further action needed here?

**Comment by dangrous** [comment]
nope I think we can close - nothing actually needed here now.

**Comment by dangrous** [comment]
oh wait I lied, we might need to keep this open for completion, but we won't need payment either way. Checking in Slack.

**Comment by bfitzexpensify** [comment]
@dangrous is there a PR linked to this I can keep an eye on? Is it just https://github.com/Expensify/App/pull/49770/files?

**Comment by dangrous** [comment]
Yeah I was originally thinking we needed to handle this as a follow up, but since it was just a revert and not original code, I think it's okay to close this out until it's fixed by the next update to that file. Thanks all!
