### ISSUE TITLE
[HOLD for payment 2024-10-14] [Search v2.4] Update from, to, in, cardID, taxRate filters to accept names in addition to IDs

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#49846]
## Problem
Coming from [here](https://github.com/Expensify/App/pull/49838#issuecomment-2379165310), we need to update the Search AST algorithm to accept more than just IDs for the from, to, in, cardID and taxRate filters given that Onyx might not have this values locally to replace the names with the appropriate IDs.

## Solution
Update the server algorithm that parses the Search AST to handle names in addition to IDs

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by luacmartins** [comment]
Got a couple of draft PRs up. Gonna continue work tomororw.

**Comment by ikevin127** [comment]
* [x] [@ikevin127] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

No need for regression tests here as stated before in https://github.com/Expensify/App/issues/46031#issuecomment-2286802282:

> This feature is still WIP, so we'll add them as part of the project wrap up.

**Comment by ikevin127** [comment]
cc @JmillsExpensify for payment

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @ikevin127 for PR testing and review.

**Comment by JmillsExpensify** [comment]
All paid out and not regression test. Closing this out!
