### ISSUE TITLE
`createPrerelease` is run and fails when a deploy is canceled due to `cancel-in-progress`

### ISSUE THREAD

**Issue by AndrewGable** [Expensify/App#49851]
### Problem

We had a deploy error on https://github.com/Expensify/App/actions/runs/11074305525/job/30773368164 because the build was canceled due to `cancel-in-progress` flag.

## Solution

@roryabraham says:

>  I'd say this is expected - the deploy completed on at least one platform (web), so it creates the prerelease.
>  I think we should just continue-on-error with these non-critical artifact upload steps

**Comment by roryabraham** [comment]
Going to just create a quick PR

**Comment by roryabraham** [comment]
Should be fixed by https://github.com/Expensify/App/pull/49852. We don't have a great way to test this per-se so I'm going to optimistically close it and we can monitor/reopen if we see it happen again.
