### ISSUE TITLE
Book travel -App reopens company address page instead of T&C page after saving company address

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49870]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-1
**Reproducible in staging?:** Y
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+salalalala@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open FAB > Book travel
3. Click Book travel
4. Select address and save it
5. Click Book travel

## Expected Result:
App will redirect to T&C page

## Actual Result:
App reopens company address page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/59929539-6eb7-4585-bcc7-122c842c3db5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-travel

**Comment by roryabraham** [comment]
Book Travel is behind a beta - not sure if it needs to be a blocker but the solution looks simple. Looks like we have a good number of customers on the beta, so if we can fix it that'd probably be best.

**Comment by luacmartins** [comment]
Fixed in staging. Closing.
