### ISSUE TITLE
 Copilot - No "on behalf of" header for expense preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49888]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/48594
## Action Performed:
Precondition:
- Log in as a copilot
1. Go to staging.new.expensify.com
2. Go to Account settings
3. Click on the account switcher
4. Select the other account that user has full access to
5. Go to DM
6. Split an expense

## Expected Result:
There will be "on behalf of" header for the split preview and expense preview

## Actual Result:
"on behalf of" header is only present for the split preview but not expense preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/9ba73d6e-3543-4d0d-a28c-fd8dba0d4906

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-control

**Comment by Gonals** [comment]
Not. web-E blocker

**Comment by dangrous** [comment]
Yeah I think that's right, we can close this. cc @dylanexpensify
