### ISSUE TITLE
Expense - Incorrect avatar for pay preview and missing avatar & username after submitting expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49889]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM
3. Click + > Pay someone
4. Enter amount > Pay the user
5. Click + > Submit expense
6. Submit expense to the user

## Expected Result:
In Step 4, the report preview avatar for "paying preview" should display the sender avatar because the sender pays the money
In Step 6, when submitting expense after paying the user, the expense preview will have the sender avatar and sender name

## Actual Result:
In Step 4, the report preview avatar for "paying preview" displays the receiver avatar instead of sender avatar
In Step 6, when submitting expense after paying the user, the expense preview is missing sender avatar and sender name briefly, then it appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8510710a-d0ab-4f9c-91b3-de49d9d32236

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment]
@grgia @eh2077 this seems to be coming from https://github.com/Expensify/App/pull/49172

For pay requests, childOwnerAccountID is the payee and not the payer. Also, the report action is always ReportPreview.

**Comment by grgia** [comment]
Looking now

**Comment by grgia** [comment]
This seems to be a BE problem. 

Why are pay requests setting the childOwnerAccountID to the payee?

**Comment by jasperhuangg** [comment]
We reverted the problematic PR https://github.com/Expensify/App/pull/49945. Gonna remove the label but keep this open so @grgia can fix this in a followup.

**Comment by MonilBhavsar** [comment]
closing as PR was reverted and issue was fixed
