### ISSUE TITLE
Chat - When long pressing url, copy to URL to clipboard icon is greyed out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49892]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a chat
3. Enter a url and send message eg- hai.com
4. Long press the message

## Expected Result:
When long pressing url, copy to URL to clipboard icon must be in green

## Actual Result:
When long pressing url, copy to URL to clipboard icon is greyed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1dc0e3de-c6f6-4e0c-bcd6-b2baf8cbc5dc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production:

![Screenshot_20240928-092002_Chrome](https://github.com/user-attachments/assets/280e17dc-28e7-4de2-bf8f-94301559aef0)

**Comment by roryabraham** [comment]
@dubielzyk-expensify can you clarify if this is expected or not?

**Comment by dubielzyk-expensify** [comment]
We actually changed these option rows to now have grey color, so this is as expected. 

We made the change here: https://github.com/Expensify/App/pull/49569#issuecomment-2365197512

**Comment by roryabraham** [comment]
thanks @dubielzyk-expensify!
