### ISSUE TITLE
[HOLD for payment 2024-10-24] [$50] iOS - Attachment - Opening exclamation mark on "Downloaded!" modal is not correct in Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49893]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** https://expensify.testrail.io/index.php?/tests/view/5018371
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must have set the language to Spanish
1. Open New Expensify app
2. Go to any chat with an attachment (or send an attachment if there is none)
3. Tap on the attachment
4. Tap on the download button and wait for it to download

## Expected Result:
Opening exclamation mark should be correct, title in the modal should say "¡Descargado!"

## Actual Result:
Opening exclamation mark is not correct, title in the modal says "!Descargado!"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![534](https://github.com/user-attachments/assets/d50a08f2-aec7-4b9b-884b-55a482da41bc)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841232628406634819</li>
        <li>Upwork Job ID: 1841232628406634819</li>
        <li>Last Price Increase: 2024-10-01</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104321452</li>
<li>Nodebrute | Contributor | 104321453</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment]
@akinwale this is a super quick/easy fix, right?  I'm planning to make it $50, wanted to check with you first though.

**Comment by akinwale** [comment]
> @akinwale this is a super quick/easy fix, right? I'm planning to make it $50, wanted to check with you first though.

@mallenexpensify Yes, this is just a translation string update.

**Comment by mallenexpensify** [comment]
Thanks @akinwale, made it $50, plz review @Nodebrute 's proposal above.

**Comment by sher999** [comment]
Hey I have done this change 

<img width="519" alt="Screenshot 2024-10-02 at 12 25 10 PM" src="https://github.com/user-attachments/assets/9c6f95d1-c794-4fc5-a781-6797d97fd9ed">



outcome on ios 17.5 native iphone 15

<img width="354" alt="Screenshot 2024-10-02 at 12 26 16 PM" src="https://github.com/user-attachments/assets/6dde29ae-85bb-4d66-aa4d-9182fbf72bc0">


can I submit the PR ?

**Comment by mallenexpensify** [comment]
@sher999 please familiarize yourself with our [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and https://github.com/Expensify/App/tree/main/contributingGuides

**Comment by mallenexpensify** [comment]
@akinwale , when you're back from traveling.  Also, will [this issue](https://github.com/Expensify/App/issues/49893) be fixed by the proposal here? Thx

**Comment by akinwale** [comment]
We can move forward with @Nodebrute's [proposal](https://github.com/Expensify/App/issues/49893#issuecomment-2380894578) here.

🎀👀🎀 C+ reviewed.

> @akinwale , when you're back from traveling. Also, will [this issue](https://github.com/Expensify/App/issues/49893) be fixed by the proposal here? Thx

@mallenexpensify Did you intend to link a different issue here?

**Comment by mallenexpensify** [comment]
@arosiclair 👀 on the above proposal plz, should be _super_ quick :)

I removed my comment above cuz I can't remember the correct link I meant to share ¯\_(ツ)_/¯

**Comment by arosiclair** [comment]
Yeah I hired Nodebrute. Just waiting on the C+ review.

**Comment by mallenexpensify** [comment]
Contributor: @Nodebrute  paid $50 via Upwork
Contributor+: @akinwale paid $50 via Upwork. 

No need for a regression test here, thx!
