### ISSUE TITLE
[HOLD for payment 2024-10-17] [$125] [Search v2.3] IOS - Emoji is cut off in the dropdown button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49890]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- There is at least one saved search
1. Launch New Expensify app
2. Go to Search
3. Tap on the dropdown button
4. Tap 3-dot menu next to the saved search
5. Tap Rename
6. Enter an emoji and save it
7. Dismiss the dropdown modal

## Expected Result:
The emoji will not be cut off in the dropdown button

## Actual Result:
The emoji is cut off in the dropdown button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/44146f16-1207-4e7a-99eb-1b23098f749f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840184545557049275</li>
        <li>Upwork Job ID: 1840184545557049275</li>
        <li>Last Price Increase: 2024-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 104219452</li>
<li>Nodebrute | Contributor | 104219453</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/1d2fac2a-988a-4315-b9c8-0991ec2e546e

**Comment by roryabraham** [comment]
Issue stemming from https://github.com/Expensify/App/pull/49528

**Comment by roryabraham** [comment]
I think that @Nodebrute's proposal looks reasonable, but want @dannymcclain to double-check first

**Comment by Kicu** [comment]
The solution presented by @Nodebrute seems legit but I would suggest one small improvement.

I can see that we have a dedicated style called `label` here: https://github.com/Expensify/App/blob/d47e1562fa6adb9968623512ee59af0fa6a4acba/src/styles/index.ts#L371
and it is defined like this:
```ts
label: {
      fontSize: variables.fontSizeLabel,
      lineHeight: variables.lineHeightLarge,
}
```

That tells me we do want this specific `lineHeightLarge` combined with `fontSizeLabel`.
So I think instead of directly adding `lineHeightLarge` in the component we should just use `styles.label`. This style is used in multiple other places as well.

**Comment by Muhammad-Maraj-Khan** [comment]
The solution also seems good for me.

**Comment by Muhammad-Maraj-Khan** [comment]
Contributor details
Your Expensify account email: mairajkhan11345@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fdb5331a4bc5b415

**Comment by roryabraham** [comment]
Awaiting 👍🏼 from @ahmedGaber93 since he'll have to review the PR. I set the price lower because this seems like a very simple issue and it affects only one platform.

**Comment by ahmedGaber93** [comment]
@Nodebrute's [proposal](https://github.com/Expensify/App/issues/49890#issuecomment-2380873590) LGTM! And not affected on others platforms

🎀 👀 🎀 C+ reviewed

**Comment by ahmedGaber93** [comment]
Do we solve this https://github.com/Expensify/App/issues/49890#issuecomment-2383200176 here too? If yes, we can handle it in the PR.

**Comment by dannymcclain** [comment]
>Do we solve this https://github.com/Expensify/App/issues/49890#issuecomment-2383200176 here too? If yes, we can handle it in the PR.

I'll let @roryabraham weigh in on that one/decide—it's pretty unrelated but if it's a super simple update it'd be nice to get it knocked out.

**Comment by roryabraham** [comment]
> Do we solve this https://github.com/Expensify/App/issues/49890#issuecomment-2383200176 here too? If yes, we can handle it in the PR.

Nah, let's do a separate issue for that. @dannymcclain can you create it, and label it `Bug`, `External` plz?

**Comment by roryabraham** [comment]
PR is approved by me. Last step is for @dannymcclain to review and merge, then it's just awaiting deploy and payment

**Comment by ahmedGaber93** [comment]
I think this is a minor fix and no regression test require.

**Comment by dylanexpensify** [comment]
Tomorrow!

**Comment by dylanexpensify** [comment]
Done!
