### ISSUE TITLE
[$250]  mWeb - Dupe detection - Multiple "resolved the duplicate" message is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+ds@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. [Employee] Submit two expenses that are duplicated
2. [Admin] Go to the transaction thread of a transaction
3. [Admin] Review the duplicate and chose any transaction to keep
4. [Admin] Confirm to resolve the duplicate
5. Admin] Click the Back button, notice you are returned to "Review duplicates" page
6. Admin] Click on "confirm"

## Expected Result:
Clicking the Back button does not take to "Review duplicates" page

## Actual Result:
Clicking the Back button takes you back to "Review duplicates" page. And confirming creates multiple "resolved the duplicate" and "Held this Expense" messages in the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/445563f3-4abf-4287-8381-0502a0debd47

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840789692182968366</li>
        <li>Upwork Job ID: 1840789692182968366</li>
        <li>Last Price Increase: 2024-09-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by Gonals** [comment]
Only happening in one platform, so not a Web-E blocker

**Comment by neil-marcellini** [comment]
This is also reproducible on Mac Chrome on a small screen


https://github.com/user-attachments/assets/1cb71b75-e249-4d3e-a28e-d62af176fa5a
