### ISSUE TITLE
[HOLD for payment 2024-10-17] Rare build failures during apk assembling

### ISSUE THREAD

**Issue by kirillzyusko** [Expensify/App#49924]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** N
**Logs:** https://github.com/Expensify/App/actions/runs/11034638063
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg spotted it
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1728029657508579

## Action Performed:

 - merge code to main
 - automatic e2e build action will be triggered

## Expected Result:

- build action should be always stable

## Actual Result:

- sometimes action may randomly fail

## Workaround:

Re-trigger pipeline manually.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/5f04e9d7-1225-44a8-8b30-b2fc2c239824">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by kirillzyusko** [comment]
I think the bug can be assigned on me as well, because I already prepared a fix for that 👀

**Comment by arosiclair** [comment]
@kirillzyusko we don't have access to that margelo slack conversation. Can you start a conversation about this in one of our slack channels? I'm not sure if this is the right approach but somebody else might know better.

**Comment by kirillzyusko** [comment]
@arosiclair I updated a link 🙌

**Comment by arosiclair** [comment]
No C+ review and changes are from Margelo so we can just close this
