### ISSUE TITLE
[Paid meow] Workspace - Duplicate expense preview avatar after workspace is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49927]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Submit an expense
4. Delete the workspace
5. Go to the workspace chat (now archived)

## Expected Result:
The expense preview avatar will remain the same after the workspace is deleted

## Actual Result:
The expense preview avatar changes after the workspace is deleted
It changes to stacked avatars with both avatars from the workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f6a48007-9caa-4421-a435-4eb8ee84e876

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by mjasikowski** [comment]
Front-end issue, removing DeployBlockerCash label.

**Comment by mjasikowski** [comment]
Reverting https://github.com/Expensify/App/pull/49403 did not fix the issue, looking further

**Comment by mjasikowski** [comment]
Pinpointed the offending PR using git bisect: https://github.com/Expensify/App/pull/49172

**Comment by mjasikowski** [comment]
@grgia would you be able to take a look at this and see if this can be easily fixed or reverted?

**Comment by grgia** [comment]
It's late for me let's revert https://github.com/Expensify/App/pull/49172 for now

**Comment by jasperhuangg** [comment]
We reverted the problematic PR https://github.com/Expensify/App/pull/49945. Gonna remove the label but keep this open so @grgia can fix this in a followup.

**Comment by mjasikowski** [comment]
> This was solved long back. I was C+ on the revert PR. Can we please assign someone from BZ to make the payment?

@Expensify/bug-zero pinging you here

**Comment by OfstadC** [comment]
Sorry friends! Looking now

**Comment by OfstadC** [comment]
## Payment Summary 
- @parasharrajat due $250 via manual New Expensify request

If i'm missing anyone, please let me know!

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
