### ISSUE TITLE
[HOLD for payment 2024-10-22] [3rd Party Feeds] Delete workspace with card feed

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#49938]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1727702629438229?thread_ts=1727124415.008809&cid=C06ML6X0W9L), we need to implement the deleting workspace with card feed [section of the third party workspace feeds v1 doc](https://docs.google.com/document/d/1PXx506PM7-sGW3Zones8mWieZgnqRJ5qYXzTOZ3dnlg/edit?pli=1#bookmark=id.h1z0ecjtu0mv). 

The FE of deleting a workspace already exists. We just need to add the logic related to removing any assigned workspace feeds. 

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify / @abekkala</details>

**Comment by joekaufmanexpensify** [comment]
@waterim is taking this. Mind commenting here so we can assign you?

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue

**Comment by abekkala** [comment]
assigning @ishpaul777 as you are reviewing the PR

**Comment by abekkala** [comment]
@JmillsExpensify  I'll be ooo until Mon Oct 21
Given that the PR has not yet deployed to prod starting the 7 day waiting period yet I don't expect this to come to payment before I return from ooo on Oct 21.

### STATUS:  PR created, but not yet deployed to production

**Payment Summary [date, TBD]:**

- Fix: @waterim callstack, no upwork payment needed
- PR Review: @ishpaul777 [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104374098)

**Comment by abekkala** [comment]
I'm back from ooo - unassigning @JmillsExpensify

**Comment by abekkala** [comment]
### Payment Summary for OCT 22

Fix: @waterim callstack, no upwork payment needed
PR Review: @ishpaul777 [$250, if no regressions] [OFFER](https://www.upwork.com/nx/wm/offer/104374098)

**Comment by abekkala** [comment]
[@ishpaul777] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

**Comment by abekkala** [comment]
waiting on regression test proposal before issuing payment.

**Comment by joekaufmanexpensify** [comment]
@abekkala we can skip the regression test here. I [wrote tests](https://docs.google.com/document/d/1l57bDjZm3Uxn-0iKE-YXdPCbd9y3nKmJcO1jqgkByIY/edit?tab=t.0#heading=h.nhtsmauf72jq) for the entire feature, which include this case. We'll pass all the tests off to applause as new regression tests once we finish our pre-launch testing.

**Comment by abekkala** [comment]
@ishpaul777 payment sent and contract ended - thank you! 🎉
