### ISSUE TITLE
 Chat - #focus prompt does not appear when user create 30 reports

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49944]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with new account
3. Create over 30 reports by creating multiple workspaces or DMs
4. Sign out
5. Log in with te same user

## Expected Result:
The #focus prompt should be displayed when user has 30 reports

## Actual Result:
The prompt is not displayed, neither when creating 30 reports nor when logging in to an account that has 30 reports

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/b27dec4d-da11-4d9c-98db-a7c9fb3a052f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment]
Appears to be from https://github.com/Expensify/App/pull/49735

**Comment by thienlnam** [comment]
cc @MonilBhavsar

**Comment by MonilBhavsar** [comment]
> Reproducible in staging?: Y
> Reproducible in production?: Y

@lanitochka17 is this supposed to be blocker?

**Comment by thienlnam** [comment]
Oh whoops, didn't catch that - yeah it would not be a blocker in that case

**Comment by MonilBhavsar** [comment]
I don't think we need frontend fix here. Returning the NVP always should fix the issue

**Comment by MonilBhavsar** [comment]
PR was deployed
