### ISSUE TITLE
[$250] Chat - Console error shows up when refreshing the page and focusing on the composer

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49973]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Refresh the page.
3. Focus on the composer.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up when refreshing the page and focusing on the composer.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ae810c7b-69e8-4d76-a762-0c6d818bdcb2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841157589199682365</li>
        <li>Upwork Job ID: 1841157589199682365</li>
        <li>Last Price Increase: 2024-10-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by zanyrenney** [comment]
As this is just a console error, I don't think it needs to be a deploy blocker cc @flodnv

**Comment by jasperhuangg** [comment]
@zanyrenney True. Let's just make sure this isn't causing any unintended consequences regarding composer usage. If we don't find anything, I agree with that path forward.

**Comment by jasperhuangg** [comment]
Yeah this seems like it doesn't need to block deploy, removing the label.

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by flodnv** [comment]
Thanks, go for it!

**Comment by VickyStash** [comment]
It looks like this issue got fixed by this revert: https://github.com/Expensify/App/pull/50025

**Comment by Skalakid** [comment]
Hello, this issue occurred after bumping the `react-native-live-markdown` library. [The PR with the bump](https://github.com/Expensify/App/pull/49250) was reverted. However, I'm fixing this issue [here](https://github.com/Expensify/react-native-live-markdown/pull/509) so we can proceed with the library version update

**Comment by flodnv** [comment]
Seems like we can close this? LMK if I'm mistaken.
