### ISSUE TITLE
[HELD on 49802] [$250] Workspaces - 3 dot menu is shown above the preferences dialog window

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49976]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to an account
2. Go to workspace > click on the 3 dot menu
3. Press cmd + D

## Expected Result:
3 dot menu is dismissed and the preferences dialog window is shown

## Actual Result:
3 dot menu is shown on top of the preferences dialog window.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/741b8038-f859-4644-b0ab-9a0b1848066a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841087840397368741</li>
        <li>Upwork Job ID: 1841087840397368741</li>
        <li>Last Price Increase: 2024-11-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by IuliiaHerets** [comment]
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
Looks like my proposal [here](https://github.com/Expensify/App/issues/49802#issuecomment-2385472320) will solve this issue too.

**Comment by bernhardoj** [comment]
I think we can work on https://github.com/Expensify/App/issues/49802 since I also propose another thing to improve the debug modal.

**Comment by bfitzexpensify** [comment]
Still held

**Comment by bfitzexpensify** [comment]
https://github.com/Expensify/App/pull/51659 in review

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
