### ISSUE TITLE
Distance - Waypoint field is not focused after navigating back from RHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49975]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gibethlehem@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to any chat
2. Click on the Plus sign > Submit expense > Distance
3. Go to Start address page
4. Press on cmd/ctrl + J to open "Keyboard Shortcuts" Page
5. Navigate back

## Expected Result:
Waypoint field is focused

## Actual Result:
Waypoint field is not focused after returning from "Keyboard Shortcuts" Page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/20970849-f494-4fea-b2f6-8a1600de647b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
I'm having a hard time even loading the map, will test again.

**Comment by slafortune** [comment]
I don't think many people use the keyboard shortcut menu while on the Distance expense page in the middle of entering an expense.  Going to close this so that we can focus on higher priority issues.
