### ISSUE TITLE
[HybridApp] Force update modal not showing image

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#49978]
### Problem

We sometimes force users to update if their app version doesn't match a specific version we set in the backend. There is an animation/image on NewDot standalone, but this doesn't appear on Android HybridApp new experience: 

Presumably it should be possible to force the page to appear by forcing the page to show within BaseErrorBoundry [here](https://github.com/Expensify/App/blob/98959bc9df45df2db8476e0e6b057e1f630eabfe/src/components/ErrorBoundary/BaseErrorBoundary.tsx#L24).

**HybridApp**
![370294271-0d02ae05-660e-4773-a4f7-2dcbeabe53aa](https://github.com/user-attachments/assets/ecf98de2-50e1-4739-82b7-4b79f0eb0f30)

**NewDot standalone**
![370294446-2c4248bc-4f22-49e3-88f4-db7c769262fb](https://github.com/user-attachments/assets/24877006-1d34-4cce-9a80-cc7c8c403b7d)

### Solution

???

**Comment by staszekscp** [comment]
Hey @Julesssss! I've just tried to reproduce, but I was unable to do it - on my device everything works fine. I've also noticed that the fonts on the screenshot are also broken, which indicates that NewDot assets were not included into the build. 🤔 What is the device, and version of the app of this build? Could you send me the `.apk`, please?

**Comment by Julesssss** [comment]
Ah damn, I don't recall. I'm just going to close this as a minor issue. 

Thanks for taking a look!

**Comment by Julesssss** [comment]
Just reopening to verify some questions: 

- Did you reproduce the upgrade modal with a local change?
- Did the font show up correctly for you?

**Comment by staszekscp** [comment]
@Julesssss 
> Did you reproduce the upgrade modal with a local change?

I forced the modal to show up locally

> Did the font show up correctly for you?

The fonts were 100% correct!

**Comment by Julesssss** [comment]
Thanks for confirming!
