### ISSUE TITLE
iOS - Composer - No copy paste option in edit mode

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49977]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0..42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+zm27@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to DM.
3. Long tap on any message.
4. Tap Edit comment.
5. Tap on the composer to bring up context menu.

## Expected Result:
There will be copy paste option in edit mode.

## Actual Result:
There is no copy paste option in edit mode.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3f15d162-7310-4d2a-9a77-85b3361f0ab7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment]
Regression from: https://github.com/Expensify/App/pull/32711

**Comment by jasperhuangg** [comment]
Retest request is [here](https://expensify.slack.com/archives/C9YU7BX5M/p1727800285836869) for easy access

**Comment by m-natarajan** [comment]
Issue fixed

https://github.com/user-attachments/assets/b1750cd6-339e-47f2-9be2-0d8f8b0ae523
