### ISSUE TITLE
Live MD - Composer does not scroll down after pasting content with inline image preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49983]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49250
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Paste the following content.

*test* ![demo image](https://picsum.photos/id/1067/200/300
)_test_ 😊

*test* ![demo image](https://picsum.photos/id/1067/200/300
)_test_ 😊

## Expected Result:
The composer will scroll down to the end after pasting the content.

## Actual Result:
The composer does not scroll down to the end after pasting the content with inline image preview.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/29a945d9-dd77-464f-9876-393bbc253f16

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to Live Markdown

**Comment by mjasikowski** [comment]
@Skalakid are you able to fix or revert this quickly?

**Comment by hungvu193** [comment]
@mjasikowski  I can create a revert if @Skalakid is AFK. There's another DB that related to recent liver markdown version too.

**Comment by joekaufmanexpensify** [comment]
What is the bug? You're able to scroll in the video attached in OP?

**Comment by jasperhuangg** [comment]
@hungvu193 Please revert https://github.com/Expensify/App/issues/49981, it's also causing https://github.com/Expensify/App/issues/49981 it seems and there's no response yet.

**Comment by Skalakid** [comment]
I'm not sure if it's a bug. The image preview loads asynchronously, and the scrolling into view after pasting content occurs before the image is added to the input. In my opinion, this is expected behavior, such as not scrolling the last image into view. What if the image loads for 5 seconds and a user is constantly typing? Should the whole content move to the loaded image in this case? It will look like a layout jump.

Let's discuss it with the @Expensify/design team
