### ISSUE TITLE
[Payment due][$125] Room-Removed members from room shown in search as removed without user id

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49982]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Create a room
3. Tap header - members
4. Invite 2 members and remove the members
5. Create a room
6. Tap header - members
7. Invite 3 members and remove the members
8. Navigate to LHN and tap search
9. In the dropdown list, note the room chat and their removed message

## Expected Result:
Removed members from room must be shown in search as removed with their user id.

## Actual Result:
In search, room chat of 2 members and 3 members removed are shown as "removed and", "removed, , and".

Removed members from room are shown in search as removed Or with commas without user id.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7886a078-a8fc-46e1-a505-40b78fb6447d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841273991262013347</li>
        <li>Upwork Job ID: 1841273991262013347</li>
        <li>Last Price Increase: 2024-10-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The removed member system message shown on the chat finder page doesn't show the user login.

### What is the root cause of that problem?
That's how it's from the report `lastMessageText`.
<img width="257" alt="image" src="https://github.com/user-attachments/assets/400b64ed-7868-4d53-944d-969519f01f50">

But if we see the LHN, the last message says "removed 2 users", which is different from the chat finder page's last message text. This is because, for LHN, we handle manually the invite/remove case and construct a new message for it.
https://github.com/Expensify/App/blob/c7ee85b2ea207159ef85932055aced28d5d2e29a/src/libs/SidebarUtils.ts#L410-L429

But for the chat finder page, we just show the report `lastMessageText` because we are not handling the invite/remove action.
https://github.com/Expensify/App/blob/c7ee85b2ea207159ef85932055aced28d5d2e29a/src/libs/OptionsListUtils.ts#L612-L697

### What changes do you think we should make in order to solve the problem?

It's confusing to have 2 sources of truth of last message which works differently between LHN and chat finder page, but in this issue, we can just copy the logic from the SidebarUtils to `OptionslistUtils.getLastMessageTextForReport`.

```
} else if (ReportActionUtils.isInviteOrRemovedAction(lastReportAction)) {
    const participants = ReportUtils.getParticipantsAccountIDsForDisplay(report);
    const hasMultipleParticipants = participants.length > 1 || ReportUtils.isChatRoom(report) || ReportUtils.isPolicyExpenseChat(report) || ReportUtils.isExpenseReport(report);
    const lastActorDisplayName = getLastActorDisplayName(lastActorDetails, hasMultipleParticipants);
    const lastActionName = lastReportAction?.actionName ?? report?.lastActionType;
    const lastActionOriginalMessage = lastReportAction?.actionName ? ReportActionUtils.getOriginalMessage(lastReportAction) : null;
    const targetAccountIDs = lastActionOriginalMessage?.targetAccountIDs ?? [];
    const targetAccountIDsLength = targetAccountIDs.length !== 0 ? targetAccountIDs.length : report?.lastMessageHtml?.match(/<mention-user[^>]*><\/mention-user>/g)?.length ?? 0;
    const verb =
        lastActionName === CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.INVITE_TO_ROOM || lastActionName === CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.INVITE_TO_ROOM
            ? Localize.translate(preferredLocale, 'workspace.invite.invited')
            : Localize.translate(preferredLocale, 'workspace.invite.removed');
    const users = Localize.translate(preferredLocale, targetAccountIDsLength > 1 ? 'workspace.invite.users' : 'workspace.invite.user');
    let alternateText = ReportUtils.formatReportLastMessageText(`${lastActorDisplayName} ${verb} ${targetAccountIDsLength} ${users}`);

    const roomName = lastActionOriginalMessage?.roomName ?? '';
    if (roomName) {
        const preposition =
            lastReportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.INVITE_TO_ROOM || lastReportAction.actionName === CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.INVITE_TO_ROOM
                ? ` ${Localize.translate(preferredLocale, 'workspace.invite.to')}`
                : ` ${Localize.translate(preferredLocale, 'workspace.invite.from')}`;
        alternateText += `${preposition} ${roomName}`;
    }

    return alternateText;
}
```

**Comment by suneox** [comment]
@bernhardoj [proposal](https://github.com/Expensify/App/issues/49982#issuecomment-2385590627) to sync the logic from `SideBarUtil` to `OptionsListUtils` in case `InviteOrRemovedAction` LGTM.

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment]
I see that we have an issue to remove Chat Finder page https://github.com/Expensify/App/issues/49123

**Comment by MarioExpensify** [comment]
Hey @bernhardoj let me get in touch with @luacmartins regarding this https://github.com/Expensify/App/issues/49123 before approving this one.

**Comment by MarioExpensify** [comment]
@luacmartins confirmed we should be pausing work related to Chat Finder. @kadiealexander do you know how we proceed in this case regarding this issue?

**Comment by kadiealexander** [comment]
Discussed [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1728313845591939) and agreed on a 50% payment for work completed so far.

**Comment by kadiealexander** [comment]
Payouts due:

- [ ] Contributor: $X @MarioExpensify
- [ ] Contributor+: $X @suneox

Upwork job is [here](https://www.upwork.com/jobs/~021841273991262013347).

**Comment by suneox** [comment]
@kadiealexander Thank you, I've accepted an offer

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
