### ISSUE TITLE
Live markdown -Suggestion list does not appear above @ line when there is inline image preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49981]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49250
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Paste the following text

*test* ![demo image](https://picsum.photos/id/1067/200/300
)_test_

4. Enter @ and add a few characters.

## Expected Result:
The suggestion list will appear above the @ line.

## Actual Result:
The suggestion list appears away from the @ line.
The issue is way worse when repeating the steps above in edit mode.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/453f0f1d-b2ef-44c9-909b-24235d1d2a20

https://github.com/user-attachments/assets/f6cadda9-0e03-4a0f-b2ec-70f8139aa8df

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to Live Markdown

**Comment by hungvu193** [comment]
cc @Skalakid, this came from our previous PR that bumped live-markdown version. Can you take a look 👀
