### ISSUE TITLE
[HOLD for payment on 10th Sept] Allow users to reject transactions for $0, balanced reports

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#4998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As user A request 100$ to user B
2. As user B request 100$ to user A 

## Expected Result:
There should be an option to decline or cancel up the IOU when the balance is 0$

## Actual Result:
There's no option to decline or cancel the IOU when it's balanced at 0$

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.0.91-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
Please check this thread since it gives more information around the issue. https://expensify.slack.com/archives/C01GTK53T8Q/p1630438306221900

![image](https://user-images.githubusercontent.com/44479856/131756633-9f14312e-0096-4bfc-9788-fa10a89198b5.png)

**Upwork Job URL:** https://www.upwork.com/jobs/~011152f670ca3a2197

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

___ 
From @Santhosh-Sellavel https://expensify.slack.com/archives/C01GTK53T8Q/p1630438306221900

**Comment by Julesssss** [comment]
Hmm, why didn't `External` work? Maybe because one member of each team is assigned already? 

Regardless, we can manage this one 🤷

**Comment by Julesssss** [comment]
@Santhosh-Sellavel would you like to raise your proposal?

**Comment by Santhosh-Sellavel** [comment]
## Proposal
Yes @Julesssss 
Here we check total  !== 0, removing the check will enable options
https://github.com/Expensify/App/blob/fad2da591628f93c089d297ac901ce7dc23320fb/src/libs/actions/Report.js#L237

Removing this will enable options to Cancel or Decline requests.

Do we need any other additional handling here?

**Comment by trjExpensify** [comment]
>Hmm, why didn't External work? Maybe because one member of each team is assigned already?

Yep, that'll be it! 

I'll create an Upwork job for this now.

**Comment by Santhosh-Sellavel** [comment]
@trjExpensify Applied for the job!

**Comment by Santhosh-Sellavel** [comment]
I tried to fix it at the root, If we still want to use the logic somewhere else then as you said check should be refactored in the below line alone. 
https://github.com/Expensify/App/blob/fad2da591628f93c089d297ac901ce7dc23320fb/src/pages/iou/IOUTransactions.js#L53-L55

**Comment by Santhosh-Sellavel** [comment]
## Updated Proposal
From here we can pass the`iouReport.status `to prop of IOUTransactions.
https://github.com/Expensify/App/blob/fad2da591628f93c089d297ac901ce7dc23320fb/src/pages/iou/IOUDetailsModal.js#L238-L243

And here, check the condition whether its status is PROCESSING as you said
https://github.com/Expensify/App/blob/fad2da591628f93c089d297ac901ce7dc23320fb/src/pages/iou/IOUTransactions.js#L53-L55

@Julesssss

**Comment by Julesssss** [comment]
> Based on your input will add relevant props. There is a simple fix, if needed we can bind the check with the existing hasOutstandingIOU prop itself. Because hasOutstandingIOU prop was used only in check here.

Yeah, I think this is the best solution. But let's update the prop name to something like `isReportSetted`

**Comment by Julesssss** [comment]
@trjExpensify please hire @Santhosh-Sellavel on UpWork when the issue is created.

**Comment by trjExpensify** [comment]
Done! 👍

**Comment by Santhosh-Sellavel** [comment]
> > Based on your input will add relevant props. There is a simple fix, if needed we can bind the check with the existing hasOutstandingIOU prop itself. Because hasOutstandingIOU prop was used only in check here.
> 
> Yeah, I think this is the best solution. But let's update the prop name to something like `isReportSetted`

Any other changes other than above changes for this issue?
@Julesssss

**Comment by Julesssss** [comment]
Nope, I think that's everything, please go ahead and make a start. Let us know if you have any questions!

**Comment by Santhosh-Sellavel** [comment]
> Currently, for users who requested last alone, we show -> I'll settle up else where.
> 
> ### Last Requested Details
> <img width="571" alt="Screenshot 2021-09-02 at 4 46 06 PM" src="https://user-images.githubusercontent.com/85645967/131834577-57c87c73-d4e5-4cac-a3d0-8a3072b0f433.png">
> 
> ### First Requested Details
> <img width="380" alt="Screenshot 2021-09-02 at 4 46 17 PM" src="https://user-images.githubusercontent.com/85645967/131834565-17d90c14-e38a-4e95-8368-54c1736da8e6.png">
> 

Are we good with this? @Julesssss

**Comment by Julesssss** [comment]
> Currently, for users who requested last alone, we show -> I'll settle up else where.

We should not show the settle-up button for this scenario. There is nothing to settle while the total is 0, so the button should not be seen for either user. 

I'm a bit surprised that you saw this tbh, did the change that we suggested above cause this?

**Comment by Santhosh-Sellavel** [comment]
@Julesssss 
Oops sorry, my bad all good now! It's because of the old changes. Will Raise a PR Soon! Thanks!

**Comment by Santhosh-Sellavel** [comment]
```
STATE_NUM: {
            OPEN: 0,
            PROCESSING: 1,
            SUBMITTED: 2,
        }
```
Can you tell me what does each state means because since were going to check only `PROCESSING`. 
When to return an empty array []

**Comment by Julesssss** [comment]
Sure. The names sound a bit odd as they are reused from expense report states.
```
OPEN: 0, --> IOUReport is created (we don't remain in this state for long)
PROCESSING: 1, --> IOU has been sent to another user
SUBMITTED: 2, --> IOU has been settled (paid), and cannot be reopened. Any new IOU will result in a new IOUReport being created
```

**Comment by Santhosh-Sellavel** [comment]
So it's best to check if `stateNum`  === `SUBMITTED` set the rename the prop `isIOUSettled`. If `isIOUSettled` let's return an empty array what do you think?

**Comment by Julesssss** [comment]
Sounds good 👍

**Comment by Santhosh-Sellavel** [comment]
@Julesssss PR is ready for review!

**Comment by mallenexpensify** [comment]
Apologies for the delay @Santhosh-Sellavel , paid in Upwork and included the bonus for reporting the issue in Slack.

**Comment by mountiny** [comment]
@mallenexpensify In both of the issues, the problem is that the contributor linked the PR to issue using format such as `$ #4729` which is not what we ask for. 

We have a new issue [here](https://github.com/Expensify/Expensify/issues/177289) to accommodate for this as well, but we are still enforcing the entire link urls to link the issues correctly.

**Comment by Santhosh-Sellavel** [comment]
cc: @mountiny @mallenexpensify 

Sorry for the confusion here. I see when linking issue with the PR either of this `$ https://github.com/Expensify/App/issues/4723` or `#4723` formats, end result after submitting PR it is is displayed as `#4723` only & PR is linked with the issue. So I used mostly the format `#4723`, I will follow other format here after. Thanks

**Comment by mountiny** [comment]
Oops, sorry, my previous message was supposed to be in the other issue, haha. 

@Santhosh-Sellavel Thank you very much for that. It helps us to keep track of when to pay you. Just use this format:

`$ https://github.com/Expensify/App/issues/4723`

That is how it should look like when editing. It does not really matter, how it will look like once posted.
