### ISSUE TITLE
[HOLD for payment 2024-11-11] [$750] Netsuite - App navigates to the first flow when refreshing the page while adding custom list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+shsb22tet1122@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to new dot with any account
2. Create a new workspace > Enable "Accounting" in the "More features" page
3. Navigate to "Accounting" > Connect to NetSuite and upgrade the workspace to Control > Enter credentials and finish
4. After the connection syncs go to Import > Custom Lists > Add custom list
5. Click on "Name" and select any of the options > Next > Type any ID name > Next
6. Before making any selection refresh the page

## Expected Result:
App stays in the current flow ("How should this custom list be displayed in Expensify?")

## Actual Result:
App navigates to the first step of the flow ("Choose a custom list" step)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7ae9a867-ea6e-47f9-b669-c965e017dd74

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021842185001478860112</li>
        <li>Upwork Job ID: 1842185001478860112</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104455519</li>
<li>allgandalf | Contributor | 104455521</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by danieldoglas** [comment]
I missed this issue, my bad. I've read the proposal and I initially agree with it, but I'll refer to @yuwenmemon since he was one of the people working on this functionality before moving on.

**Comment by danieldoglas** [comment]
I think it's fine to wait for an answer in this case, I prefer not to change it without consulting the person who built it first.

**Comment by sonialiap** [comment]
@yuwenmemon was OOO end of last week and this monday but hopefully will have time to review the [proposal](https://github.com/Expensify/App/issues/49986#issuecomment-2394941170) this week

**Comment by yuwenmemon** [comment]
Yep, @allgandalf's proposal looks good.

From the design doc:

> Similar to how these fields function in the token auth setup, each field will be sticky in the sense that if the admin left Expensify and came back, everything would stay present. And, it’s important to keep these fields sticky such that admins can edit them. 

So yes, draft values should be getting saved. cc @mananjadhav

**Comment by mananjadhav** [comment]
Thanks for picking this folks. I missed this one from the design doc. Let me know if any other help/secondary review is needed.

**Comment by sonialiap** [comment]
All paid 🎉
