### ISSUE TITLE
Teachers Unite – Page lags when switch from Profile to Teachers Unite chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50008]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5023025&group_by=cases:section_id&group_order=asc&group_id=229065
**Email or phone of affected tester (no customers):** applausetester+gm103167@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Login with expensifail account
2. Go to Account settings> Save the world> I know a teacher> Complete the flow
3. Verify you're redirected to a public room Teachers Unite
4. Go to Account Settings
5. Go to Inbox

## Expected Result:
App should smoothly transfer from Account settings to Teachers Unite public room

## Actual Result:
Page lags and get stuck when user navigate from Account settings to Teachers Unite room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a1993b60-8dc4-4cac-8a7d-46794cbc7cd3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
This project is not a priority right now. I don't think we should fix this and focus effort on it - closing!
