### ISSUE TITLE
Bank Account - Plaid bank connection reverts to manual method after navigating back

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50009]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+1291@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new workspace and enable workflow.
3. Navigate to "Workflow" and click on "Connect Bank Account."
4. If your account is not verified, complete the verification.
5. Click "Connect Online with Plaid" and follow the flow until you reach the personal information section.
6. Add your legal first name and last name, then go offline and come back online before clicking "Next."
7. Go offline again, set your date of birth, come back online, and click "Next."
8. Continue navigating back until the "Manually Add Your Bank Account" option appears.

Use Regions bank
Username: user_good | Password: pass_good
Account type: Plaid Saving (2nd option)
CompanyName: Alberta Bobbeth Charleson

## Expected Result:
The process should not revert to the manual method, as Plaid was selected.

## Actual Result:
When navigating back several times, the system incorrectly reverts to the manual method for connecting the bank account.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/398a1f29-44cc-45ef-8189-b165d8b7f26e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment]
Probably BE bug, when we switch offline mode, `OpenReimbursementAccountPage` API gets called with `substep=plaid` payload but returns with `substep=manual`.
![Screenshot 2024-10-02 at 07 34 59](https://github.com/user-attachments/assets/f893a378-7413-4010-ba49-aa1d49bdae67)
![Screenshot 2024-10-02 at 07 36 01](https://github.com/user-attachments/assets/301afff1-f440-406f-b9ed-318fa49a1c21)

**Comment by CortneyOfstad** [comment]
I agree that this is a BE issue as that should not be reverting back! Getting some eyes on this!

**Comment by mountiny** [comment]
I believe we discussed with @koko57 @nkuoch that this is expected right?

**Comment by mountiny** [comment]
the account number should be disabled to edit in this case

**Comment by nkuoch** [comment]
yep this is expected and account numbers should be shown and non-editable once the bank account has been created in db

**Comment by koko57** [comment]
@mountiny yes, and  now as this [PR](https://github.com/Expensify/App/pull/49687) is merged this can be retested - the fields will be disabled

**Comment by nkuoch** [comment]
So, closing
