### ISSUE TITLE
[HOLD for payment 2024-10-11] Move Switch to Expensify Classic lower in settings

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#50013]
As [discussed here](https://expensify.slack.com/archives/C07HPDRELLD/p1727803277544129) we're going to move Switch to Expensify Classic lower in your settings. 

Proposal: Move Switch to Expensify Classic lower in settings.

Problem: New users continue to click Switch to Expensify Classic just to see what it does ([example](https://expensify.slack.com/archives/C07HPDRELLD/p1727301840168169)). I’ve observed a fair amount of new users who don’t know what Expensify is but make their way to Settings > Switch to Expensify Classic and then go back to exploring. Tbc, a lot of them follow through too but I don’t think it changes the problem or my suggestion.

Solution: Move Switch to Expensify Classic below help. It's pretty straight forward, we're just putting it below help so is a simple change.

![image](https://github.com/user-attachments/assets/e6bf68f9-39e1-4836-89df-37d4752d28b7)

**Comment by sher999** [comment]
Hello,
I have done this change mentioned above 
<img width="1440" alt="Screenshot 2024-10-02 at 12 24 45 AM" src="https://github.com/user-attachments/assets/6f4608f2-5f7c-47f2-9c78-a685f66fbb82">
` {
                    translationKey: 'exitSurvey.goToExpensifyClassic',
                    icon: Expensicons.ExpensifyLogoNew,
                    ...(NativeModules.HybridAppModule
                        ? {
                              action: () => {
                                  NativeModules.HybridAppModule.closeReactNativeApp(false, true);
                                  setInitialURL(undefined);
                              },
                          }
                        : {
                              routeName: ROUTES.SETTINGS_EXIT_SURVEY_REASON,
                          }),
                },
                {
                    translationKey: 'initialSettingsPage.about',
                    icon: Expensicons.Info,
                    routeName: ROUTES.SETTINGS_ABOUT,
                },`
                
                Can I proceed with PR ?

**Comment by sher999** [comment]
Contributor details
Your Expensify account email: shreyashd09112000@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~0187953741eec1823a

**Comment by srikarparsi** [comment]
Created a quick PR for this since it was pretty simple

**Comment by srikarparsi** [comment]
This was handled internally so I don't believe any payment is needed and the PR hit production so closing this out.
