### ISSUE TITLE
Close (X) button is not functioning for workspace card error messages.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50010]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727728301784899

## Action Performed:

1. [Admin] Create a new card.
2. [Admin] Go to the card limit page and keep it open.
3. [Owner] Deactivate the newly created card.
4. [Admin] Change the card limit. At this point, the error message should appear.
5. [Admin] Click X to dismiss or close the error message

## Expected Result:
Error message dismissed
## Actual Result:
Unable to dismiss the error message
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4d78174a-9f22-44dc-93dc-4f30bae4e0ea

https://github.com/user-attachments/assets/947afcce-0568-445a-ba3c-eb20b021d254

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jayeshmangwani** [comment]
@bfitzexpensify Please close this issue, now we decided to fix this issue in this PR https://github.com/Expensify/App/pull/49292#discussion_r1783157990
