### ISSUE TITLE
[$250] Workspace Chat - First approver doesn't see whisper message in employee workspace chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50017]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+bm38@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new workspace and enable workflow.
3. Set the delay submission to "Manual."
4. Add 3 members: an employee, Approver A (first approver), and Approver B (second approver).
5. Set up the approval workflow as follows:
- Employee submits to Approver A.
- Approver B is the second approver.
6. As the employee, submit an expense in the workspace chat.
7. As Approver A, go to the employee's workspace chat and observe that the whisper message does not appear.
8. Approve the expense as Approver A.
9. As Approver B, go to the employee's workspace chat and observe that the whisper message is visible.

## Expected Result:
The whisper message should consistently appear to both Approver A and Approver B.

## Actual Result:
The whisper message does not appear for Approver A

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2a74a3fd-c22a-47a1-ae7b-4d01878f9833

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841694831847486781</li>
        <li>Upwork Job ID: 1841694831847486781</li>
        <li>Last Price Increase: 2024-11-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @tgolen</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by kadiealexander** [comment]
@IuliiaHerets it looks like you had `approver 1` set as the approver but the account you were using to check the approver was `approver A`. Can you make sure that the user is the same and reopen if this is still happening?

**Comment by IuliiaHerets** [comment]
@kadiealexander Issue is still reproducible, the tester correct the steps a little.
1. Go to https://staging.new.expensify.com/
2. Create a new workspace and enable workflow.
3. Set the delay submission to "Manual."
4. Add 3 members: an employee, Approver A (first approver), and Approver B (second approver).
5. Set up the approval workflow as follows:
- Employee submits to Approver A.
- Approver B is the second approver.
6. As the employee, submit an expense in the workspace chat.
7. As Approver A, go to the employee's workspace chat and observe that the whisper message does not appear.
8. Approve the expense as Approver A.
9. As Approver B, go to the employee's workspace chat and observe that the whisper message is visible. 

https://github.com/user-attachments/assets/75cc46ef-0b8a-4bd8-a046-a243fa371f92

**Comment by kadiealexander** [comment]
Not overdue or a high priority bug, reassigning for someone to keep an eye on as I'm OOO for the next two weeks.

**Comment by kadiealexander** [comment]
Not overdue or a high priority bug, reassigning for someone to keep an eye on as I'm OOO for the next two weeks.

**Comment by MitchExpensify** [comment]
Waiting on proposals

**Comment by muttmuure** [comment]
Going to make this a hot pick as part of #quality

**Comment by tgolen** [comment]
I'm gonna grab this and try to take a look at it. Those whispers should be a backend thing, so I want to rule out any BE bugs if I can.

**Comment by tgolen** [comment]
Hm, @marcochavezf or @mountiny do you know more about this? Marco, it looks like maybe you added this whisper to Auth.  I'm not exactly sure how it's supposed to work and it's a bit difficult to track down. I can put more time into finding it out, but I thought you might be able to spot the problem faster than I'm able to.

**Comment by mountiny** [comment]
I am not super familiar with this whisper either sorry

**Comment by tgolen** [comment]
bump @marcochavezf

**Comment by marcochavezf** [comment]
I will take a look at it today

**Comment by marcochavezf** [comment]
Today I prioritized a deploy blocker and a #stability issue, tomorrow I will prioritize this one

**Comment by marcochavezf** [comment]
Working on it [here](https://github.com/Expensify/Auth/pull/13068)

**Comment by marcochavezf** [comment]
PR ready for review

**Comment by muttmuure** [comment]
This was merged and was fully internal, so closing.
