### ISSUE TITLE
[$125] Tag - Error occurs when trying to add a tag named "some"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50023]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+1289@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a workspace.
3. Navigate to Workspace settings > more features > enable tags.
4. Go to tags.
5. Click on add tag.
6. Name the tag "some" and try to save it. (ensure to write it in lowercase.)

## Expected Result:
The tag named "some" should be successfully created and saved without any issues.

## Actual Result:
The system returns an error stating 'A tag with this name already exists' even though no tag named 'some' is present, which might indicate a system error.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/86eac403-a0cc-4077-938f-f5db1a43d1e7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841480841839544675</li>
        <li>Upwork Job ID: 1841480841839544675</li>
        <li>Last Price Increase: 2024-10-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @yuwenmemon</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment]
What a weird bug. Easy to recreate.
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/4f6ae02f-637b-4df1-9b28-2516b8136647">

**Comment by sher999** [comment]
### **Proposal**

-----

https://github.com/Expensify/App/blob/1ed31aa7232050cc38ee4b2050ed56a6ccf80403/src/pages/workspace/tags/WorkspaceCreateTagPage.tsx#L50


can be changed 

`} else if (tags?.[tagName] && tags.length) {`

**Comment by allroundexperts** [comment]
@twisterdotcom I think that a backend fix would be better. Can you please pull someone from the internal team to take a look? TY!

**Comment by twisterdotcom** [comment]
cc @yuwenmemon can you do this?

**Comment by yuwenmemon** [comment]
Lolwut this is odd

**Comment by twisterdotcom** [comment]
Open source finds only the best bugs.

**Comment by twisterdotcom** [comment]
I don't think we need @allroundexperts here.

**Comment by yuwenmemon** [comment]
Correct. This should be merged by @mountiny later today hopefully.

**Comment by mountiny** [comment]
merged

**Comment by twisterdotcom** [comment]
This has been on prod for a few days.
