### ISSUE TITLE
[HOLD for payment 2024-10-11] [Guided Setup Stage 3] Onboarding message not sent when VBBA selected

### ISSUE THREAD

**Issue by deetergp** [Expensify/App#50027]
The original intent for the behavior of onboarding new users invited to NewDot by way of receiving an IOU or an Invoice was that we would send their onboarding message and tasks as soon as they chose to "Pay $n with Expensify" by either "Business bank account" or "Personal bank account" but when the feature was implemented, the calls to `completeGuidedSetup`  were placed inside of [`IOU.payMoneyRequest`](https://github.com/Expensify/App/blob/4a486ea402c1b02d7e860b345b7fd3a7e8640b97/src/libs/actions/IOU.ts#L7545) and [`IOU.payInvoice`](https://github.com/Expensify/App/blob/4a486ea402c1b02d7e860b345b7fd3a7e8640b97/src/libs/actions/IOU.ts#L7578). This is particularly important for users selecting `Business bank account` because that is a pretty onerous task and we want them to receive the onboarding tasks and message early, at the same time we create their workspace and move the IOU to an expense report.

Let's update this flow so that we complete their onboarding when they select the payment type. 

cc @cdOut

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by cdOut** [comment]
Hi, I'm Tymoteusz from Software Mansion and I worked on the guided setup 3 issues, you can assign me here and I'll raise a PR refactoring the VBBA flow.

**Comment by deetergp** [comment]
I agree, a regression checklist isn't needed.

**Comment by JmillsExpensify** [comment]
Processing this one now.

**Comment by JmillsExpensify** [comment]
@allgandalf apologies I forgot to actually send you the offer. Just did so, please let me know when you've accepted and I'll issue payment.
