### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] mWeb - Submit expense- "Hmm it's not here" message gets visible when deleting vague distance Expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50022]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-10 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** testpayment935+222@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go Offline
2. Global Create > Submit expense
3. Select Distance option
4. Disable the internet connection
5. Enter a vague start location, random characters
6. Enter a vague finish location, random characters
7. Finish the submit creation flow
8. Enable the internet connection
9. Click on the close icon of error message displayed

## Expected Result:
Delete the vague distance expense without problem

## Actual Result:
"Hmm it's not here" message gets visible for a second before deleting the expense

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0eab3239-7f97-442e-a8ec-2e8f88c23992

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847129435512475314</li>
        <li>Upwork Job ID: 1847129435512475314</li>
        <li>Last Price Increase: 2024-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104681071</li>
<li>truph01 | Contributor | 104681072</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Hmm it's not here" message gets visible for a second before deleting the expense

### What is the root cause of that problem?
- We clear the report data and go back in:

https://github.com/Expensify/App/blob/ea48de3e1a07b6fe15a71e8bc9fa6c03ca26d889/src/components/ReportActionItem/MoneyRequestView.tsx#L496-L497

- When the go-back action is not finished, and the onyx data is updated successfully, the "Hmm its not here" screen is displayed for a while.
### What changes do you think we should make in order to solve the problem?
- We should go back successfully and then clear the report data.

- We can do it by:

https://github.com/Expensify/App/blob/ea48de3e1a07b6fe15a71e8bc9fa6c03ca26d889/src/components/ReportActionItem/MoneyRequestView.tsx#L496-L497

```
                                const {urlToNavigateBack} = IOU.prepareToCleanUpMoneyRequest(transaction?.transactionID ?? linkedTransactionID, parentReportAction, true);
                                Navigation.goBack(urlToNavigateBack);
                                InteractionManager.runAfterInteractions(() => {
                                    IOU.cleanUpMoneyRequest(transaction?.transactionID ?? linkedTransactionID, parentReportAction, true);
                                });
```

### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment]
Adding this one to my test list and will get to it later this week.

**Comment by alexpensify** [comment]
Still on my testing list

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
@rayane-djouah  - can you please identify if this proposal will fix this issue? Thanks! 

## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by truph01** [comment]
> Your alternative solution seems more viable. I tried it, and it worked well. I think we can move forward with implementing it.

Yes, I think that solution works well without any side effects.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by flodnv** [comment]
😕 are you able to reproduce @rayane-djouah @truph01 ?

**Comment by flodnv** [comment]
Ah, got it, thanks. The alternative solution sounds good 👍

**Comment by truph01** [comment]
[PR](https://github.com/Expensify/App/pull/51940) is ready

**Comment by alexpensify** [comment]
Update: PR is in review!

**Comment by alexpensify** [comment]
Update: same as last week

**Comment by alexpensify** [comment]
Update: PR is moving but under review

**Comment by alexpensify** [comment]
Contributor: @truph01 $250 via Upwork
Contributor+: @rayane-djouah  $250 via Upwork 

--- 

Everyone has been paid. I'll work on the test next week.
