### ISSUE TITLE
FAB - There is no Create expense option

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50058]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** applausetester+pso@applause.expensifail.com
## Action Performed:
1. Go to staging.new.expensify.com
2. Open FAB

## Expected Result:
There is a Create expense option and there are no Track expense and Submit expense options

## Actual Result:
There is no Create expense option and there are Track expense and Submit expense options

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e821d07f-8631-4fb3-a3ba-474e173feb4c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment]
Going off the comment here — closing!
