### ISSUE TITLE
[HOLD for payment 2024-10-11] [HOLD for payment 2024-10-10] mWeb - LHN - Emoji deleted in chat doesn´t disappear from preview in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50069]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/49730
## Action Performed:
1. Open the staging.new.expensify.com website
2. Open any chat
3. Send any emoji
4. Long tap over the emoji
5. Tap on "Delete Message"
6. Verify emoji disappears from chat
7. Tap on the arrow on the top left corner
8. Verify the emoji is no longer displayed on chat preview on LHN

## Expected Result:
The deleted emoji should disappear from the chat and also from the chat preview in LHN

## Actual Result:
When deleting an emoji, the emoji disappears from the chat, but is still displayed on the chat preview in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/7bc5910b-754e-41bf-bcdd-b4a69b43d628

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
https://github.com/Expensify/App/issues/50081 seems related to this, and @Beamanator is offline. @stitesExpensify can you see if a fix for this issue also solves that one?

**Comment by situchan** [comment]
This came from https://github.com/Expensify/App/pull/49534/files#diff-3258457b3b73b3f6fde322dfd4d925501f57daeee25e2ae30e671a53460aa06cR52-R56

Solution:
```diff
        if (!reportAction) {
+           delete visibleReportActionItems[reportID];
            return;
        }
        visibleReportActionItems[reportID] = reportAction;
```

I am available now to raise PR

**Comment by jasperhuangg** [comment]
This was validated to be fixed via [this](https://expensify.slack.com/archives/C9YU7BX5M/p1727906414639079?thread_ts=1727905271.160329&cid=C9YU7BX5M)

**Comment by situchan** [comment]
Please assign me as PR author

**Comment by stitesExpensify** [comment]
For which PR @situchan ?

**Comment by stitesExpensify** [comment]
Looks like we need a bugzero her to pay as well

**Comment by OfstadC** [comment]
@stitesExpensify Could you help me assess who needs payment here? 😅 I want to make sure i'm not missing anyone. 

Is it @situchan & @DylanDylann ? And is the price $250?

**Comment by DylanDylann** [comment]
No need payment for me

**Comment by stitesExpensify** [comment]
Just @situchan @OfstadC

**Comment by OfstadC** [comment]
Thanks @stitesExpensify ! 

[Upwork Job
](https://www.upwork.com/ab/applicants/1844806538673850670/suggested)

@situchan Could you please accept [this offer](https://www.upwork.com/nx/wm/offer/104377613), and then I can issue payment? 😃 Thank you!

**Comment by OfstadC** [comment]
## Payment Summary 
- @situchan paid $250 via Upwork
