### ISSUE TITLE
Sign in – Unable to sign in via Magic link as a just created Gmail user

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50067]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5036419
**Email or phone of affected tester (no customers):** ponikarchuks+2221024@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Finish the Onboarding flow
4. Log out
5. Log in with the same account using Magic link

## Expected Result:
Inbox opens

## Actual Result:
Magic code expired appears

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f97fb977-205b-442b-b913-efa57ab419d6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kadiealexander** [comment]
This is expected, as staging and production are different. You can't switch to staging halfway during the login process.
