### ISSUE TITLE
Track distance - Error shows up after categorizing distance expense when track tax is enabled

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50072]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Track tax is enabled.
- The default distance rate has tax rate and tax reclaimable on filled.

1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a distance expense.
4. Click Categorize it from the whisper.
5. Select the workspace from the precondition.
6. Select a category and click Submit button.
7. Go to the workspace chat.
## Expected Result:
The track distance expense is submitted successfully.

## Actual Result:
Error shows up after submitting the track distance expense.
This issue only happens when track tax is enabled.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5beecf6e-768e-4ec5-a99b-9887c6d0f04f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment]
Adding this one to my test list and will get to it later this week.

**Comment by alexpensify** [comment]
No update yet

**Comment by alexpensify** [comment]
Still on my testing list

**Comment by alexpensify** [comment]
No update

**Comment by alexpensify** [comment]
Closing - I'm unable to replicate the experience 

![2024-10-17_21-31-34](https://github.com/user-attachments/assets/03a0da55-61d1-4172-b8a0-59623882346f)

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.
