### ISSUE TITLE
[HOLD for payment 2024-10-11] [HOLD for payment 2024-10-10] LHN - $0.00 is displayed when deleting an expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50081]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):** biruknew45+1317@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. As an admin, create a workspace and add an employee as a member
3. Enable the following settings as an admin:
- Workflow: enabled
- Approval: enabled
- Delay submission: set to manual
4. As the employee, go to the workspace chat and submit an expense
5. Click on the "Submit" button
6. Click on "Preview," navigate to the header, and delete the expense

## Expected Result:
The expense should be deleted successfully, and the amount $0.00 should not be displayed in the LHN

## Actual Result:
In the LHN, "[admin] owes $0.00" is displayed after the expense is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8d69b453-ab2d-4443-949b-273d9a2168db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
This was validated to be fixed via [this](https://expensify.slack.com/archives/C9YU7BX5M/p1727906414639079?thread_ts=1727905271.160329&cid=C9YU7BX5M)

**Comment by situchan** [comment]
Please assign me here

**Comment by twisterdotcom** [comment]
I assume $250 right? If so: Payment Summary:

- @situchan paid $250 via Upwork [here](https://www.upwork.com/nx/wm/offer/104443924) (C+)

**Comment by situchan** [comment]
@twisterdotcom I am not paid yet

**Comment by twisterdotcom** [comment]
Thanks for noting. Got it paid out.
