### ISSUE TITLE
Yellow color tones not applied for emoji

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50087]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @techievivek 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727840322244459

## Action Performed:
1. Set yellow color as a color tone for emojis
2. Hover on a message and click on Add reaction > Select :thumpsup

## Expected Result:
Emoji color tone shows in yellow
## Actual Result:
But showing in different color
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Google Chrome 2024-10-02 at 10 19 58](https://github.com/user-attachments/assets/f487d412-cdb6-43a0-8d23-9aa100152352)

![Google Chrome 2024-10-02 at 10 19 50](https://github.com/user-attachments/assets/cd5cca15-8cd8-452a-b1e5-c94940cdfcf3)

![Screenshot 2024-10-02 at 9 07 01 AM](https://github.com/user-attachments/assets/16e63725-5ea5-48b3-bc3e-e554b9463096)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zfurtak** [comment]
Hello, this is cause by[ my recently merged PR](https://github.com/Expensify/App/pull/49534#issuecomment-2387969684) and I would like to take of this issue (I work for swm agency)

**Comment by jasperhuangg** [comment]
@zfurtak Please fix the regression, thanks!

**Comment by jasperhuangg** [comment]
@zfurtak Are you actively looking into the fix for this issue?

**Comment by roryabraham** [comment]
sure

**Comment by roryabraham** [comment]
Thanks for handling @jasperhuangg
