### ISSUE TITLE
[HOLD for payment 2024-10-11] [HOLD for payment 2024-10-10] Bank account - Company website field appears empty on company info confirmation page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50086]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to validate in Prod because of Bank Setup
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5032805
**Email or phone of affected tester (no customers):**  applausetester+vd_web100224.2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-requisite: with Expensifail account, user must have created a workspace and have enabled Workflows.

1. Go to Settings > Workspaces > Workspace > Workflows.
2. Click on "Connect bank account".
3. Select "Connect online with Plaid", use Regions bank and testing credentials.
4. Go trough the add bank account flow until you reach the Company info section.
5. Keep going trough the flow, when you reach the company website page, leave it as it is and click "Next".
6. Reach the confirmation page.

## Expected Result:
Company website filed should be filled with default value on the confirmation page.

## Actual Result:
Company website filed appears empty on the confirmation page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dc351cdd-4fe0-44b1-a4ac-be14224b69a9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by jasperhuangg** [comment]
Thanks @gijoe0295, gonna get a revert up for that PR since it sounds like the proposal on that one is flawed.

**Comment by pecanoro** [comment]
I am reverting already 😄

**Comment by jasperhuangg** [comment]
PR is on staging, asking for retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1727900169895789)

**Comment by mallenexpensify** [comment]
Thanks, closing. 
[Posted on the other review](https://github.com/Expensify/App/issues/49129#issuecomment-2392448450) and linked to this issue.

**Comment by mallenexpensify** [comment]
Thanks @allgandalf , closing, for real....
