### ISSUE TITLE
HelpDot image request for Expensify Classic article for Configure NetSuite

### ISSUE THREAD

**Issue by ren-jones** [Expensify/App#50093]
Please provide the following images in light mode and in .png format. **Whoever completes this task will need a connection to NetSuite.** I do not have access to the NetSuite connection and therefore do not know how accurate or feasible a couple of these requests are. Please let me know if any of the steps below are inaccurate. 

**CONFIGURE NETSUITE**

Link to resource: https://help.expensify.com/articles/expensify-classic/connections/netsuite/Configure-Netsuite

Images needed:

- Go to Settings > Workspace > [Workspace name] > Connections and highlight the Configure button next to NetSuite.
- Once you click the Configure button, get a screenshot of each of the following sections: 
   - Export Options (Subsidiary, Preferred Exporter, Date)
   - Reimbursable Expenses (Expense Reports, Vendor Bills, Journal Entries)
   - Non-Reimbursable Expenses (Vendor Bills, Journal Entries, Expense Reports, Export Invoices, Default Vendor Bills)
- Click and highlight the Coding tab. Then also capture each of the following:
   - Expense Categories
   - Tags
   - Report Fields
   - NetSuite Employee Default
   - Tax
   - Custom Segments (custom records, custom lists)
- Go to Settings > Workspaces > [Workspace Name] > Connections > NetSuite > Configure > Advanced and highlight the Advanced tab. Then capture the following:
   - Auto Sync
   - Newly Imported Categories
   - Invite Employees & Set Approval Workflow
   - Automatically Create Employees/Vendors
   - Export Foreign Currency Amount
   - Cross-Subsidiary Customers/Projects
   - Sync Reimbursed Reports
   - Setting Approval Levels
   - Collection Account
-  Navigate to Settings > Workspaces > [Workspace Name] > Categories and highlight the Categories tab.
- Navigate to Settings > Workspaces > [Workspace Name] > Tags and highlight the Tabs tab.
- In NetSuite, show the following steps in images:
   - Go to Customization > Forms > Transaction Forms > Preferred expense report form > Screen Fields
   - Under the Main tab, check “Show for Account for Corporate Card Expenses”
   - On the Expenses tab, check “Show for Corporate Card”
   - From any employee record in NetSuite, show Customize > Customize Form.
- Go to Settings > Domain > [Domain name] > Company Cards and highlight the Company Cards tab. Then highlight the Export Settings cog on the right-hand side of the card and select the GL account where you want the expenses to export.
- In NetSuite, show Setup > Accounting > Tax Groups. Then click New, fill everything out, and capture with a highlight on the Add button.
- In NetSuite, show Setup > Accounting > Set Up Taxes
- Click the “Tax Code Lists Include” option so that “Tax Groups And Tax Codes” and “Tax Groups Only” and showing. Highlight the dropdown.
- Click the Reports tab, select a few reports and highlight a selected checkbox (to show this is how you select items in the list). Then highlight the Export to NetSuite button in another image.
- In NetSuite, type “Web Services Usage Log" into the global search bar at the top of the page and capture that in an image. Then show a list with “FAILED” under the STATUS column and highlight the two blue “view” links under the REQUEST and RESPONSE columns for that failed item.
- In NetSuite, show navigating to Setup > Integration > Web Services Preferences > Search Page Size. Then adjust the option to 1000 and highlight it. 
- Go to a customer profile and highlight the “Company Name” field (make sure it has data in it).
- In NetSuite (as an administrator) go to Setup > Accounting > Expense Categories and highlight the Expense Categories tab.

**Comment by dannymcclain** [comment]
... @dubielzyk-expensify do you have/can you set up a NetSuite connection? 😅

**Comment by dubielzyk-expensify** [comment]
I log into OldDot with the 1Pass qa account and go to the NetSuite workspace. That way you should be able to get these screenies. If not, let me know and I can walk you through it or take the issue if we can't make it work

**Comment by maddylewis** [comment]
@dannymcclain @dubielzyk-expensify -- hey guys, so sorry! i actually requested some NS images last year that shawn created for me. those will suffice for now. sorry about that! 😵 

https://github.com/Expensify/Expensify/issues/337085
