### ISSUE TITLE
[$3500] Implementing Intacct Integration in NewDot

### ISSUE THREAD

**Issue by yuwenmemon** [Expensify/App#50095]
This is the bulk amount for the implementation of the project for @hungvu193's contribution to https://github.com/Expensify/Expensify/issues/388780

Amount: $3500

Link to last PR: https://github.com/Expensify/App/issues/44669

cc @ryanldonato

**Comment by hungvu193** [comment]
Requested on ND.

**Comment by zanyrenney** [comment]
**Payment summary**

$3500 due to @hungvu193 for Intacct contribution. As is being requested in ND, we can consider this closed as the PRs are all merged! Thanks @hungvu193

**Comment by garrettmknight** [comment]
$3500 approved for @hungvu193
