### ISSUE TITLE
HelpDot image request for Classic: NetSuite Troubleshooting article

### ISSUE THREAD

**Issue by ren-jones** [Expensify/App#50101]
Please provide the following images in light mode and in .png format. **Whoever completes this task will need a connection to NetSuite.** I do not have access to the NetSuite connection and therefore do not know how accurate or feasible a couple of these requests are. Please let me know if any of the steps below are inaccurate.

**NETSUITE TROUBLESHOOTING**

Link to resource: https://help.expensify.com/articles/expensify-classic/connections/netsuite/Netsuite-Troubleshooting

Images needed: 

- Show each of the following steps in NetSuite. This is to highlight a ExpensiError NS0005 error, if helpful:
   - Go to Customization > Forms > Transaction Forms.
   - Click “Edit” on your preferred vendor bill form.
   - Go to Screen Fields > Main.
   - Uncheck both “Show” and “Mandatory” for the listed fields in your error message.
- Show each of the following steps in NetSuite:
   - Go to Lists > Employees in NetSuite.
   - Click “Edit” next to the employee’s name who submitted the report.
   - Scroll down to the Classification section.
   - Select a default Department, Class, and Location for the employee.
   - Click Save.
- Show each of the following steps in NetSuite:
   - Go to Setup > Enable Features.
   - Check the Multiple Currencies box.
   - Search "New Currencies" in the NetSuite global search.
- Show each of the following steps:
   - In NetSuite, go to the employee record and highlight the employee’s subsidiary.
   - In Expensify, navigate to Settings > Workspaces > [Workspace Name] > Connections > Configure and highlight the matching subsidiary.
- In NetSuite, show the following steps:
   - Go to Lists > Employees > Employees > [Select Employee] > Edit > Access.
   - Uncheck Restrict Access to Expensify.
- In NetSuite, go to the Human Resources tab > Expense Report Currencies. 
- In NetSuite, show the following steps: 
   - Go to Lists > Employees > Employees > [Select Employee] > Edit > Access.
   - Uncheck Restrict Access to Expensify.
- In NetSuite, show the following steps:
   - Go to Lists > Relationships > Customer/Projects.
   - Click Edit next to the desired Customer/Project.
   - Click Resources, select the Employee from the drop-down menu, click Add. 
- In NetSuite, show the following steps:
   - Edit the customer/project.
   - Go to Preferences, then uncheck Limit time and expenses to resources.
- In NetSuite, show the following steps:
   - Go to Setup > Accounting > Accounting Preferences > Time & Expenses.
   - Uncheck Show Projects Only For Time And Expense Entry.
- In Expensify, go to Settings > Workspaces > Group > [Workspace Name] > Connections > NetSuite > Configure > Advanced, then show Cross-Subsidiary Customers/Projects enabled. 
- Show the following steps: 
   - Locate the Report ID in Expensify under the Details section in the top right corner of the report.
   - Paste the Report ID into the Global Search Box in NetSuite.
   - Click Edit > Actions > Delete to remove the report.
- Open a report in Expensify, then click the Details icon in the upper-left corner of the report and highlight it. In another image, show the following options as selected:
   - View: Details
   - Group by: Tag
   - Split report by: Billable
- Capture the following steps in NetSuite:
   - Type “Page: Subsidiaries” in the global search box
   - Select the subsidiary you will export to.
   - Under the Preferences tab of the subsidiary, locate the field: Default Account for Corporate Card Expenses.
   - Open an employee record in NetSuite.
   - Under the Human Resources > Expense and Purchasing section, find the field: Default Account for Corporate Card Expenses.
- In NetSuite, capture the following steps:
   - Go to Setup > Accounting > Accounting Preferences.
   - Under the General Ledger section, ensure the field Allow Transaction Date Outside of the Posting Period is set to Warn.
   - Choose whether to export your reports to the First Open Period or the Current Period.
- In Expensify, go to Settings > Workspaces > Group > [Workspace Name] > Connections > Configure, click the Advanced tab, then show a highlight next to the enabled Export to Next Open Period toggle.
- In NetSuite, capture the following steps:
   - Go to Lists > Relationships > Vendors. 
   - Click Edit next to a Vendor.
   - Navigate to the Financial tab.
- In NetSuite, capture the following steps:
   - Go to Setup > Integrations > Manage Integrations.
   - Ensure that the Expensify Integration is listed and that the State is Enabled.
   - If you can’t find the Expensify integration, click “Show Inactives” to see if Expensify is listed as inactive.
- In Netsuite, go to Settings > Workspaces > [Workspace Name] > Connections > NetSuite > Configure > Advanced, then highlight the disabled Automatically create vendors/employees toggle.
- In NetSuite, capture the following steps:
   - Go to Setup > Company > Subsidiaries.
   - Click Edit for the desired subsidiary.
   - Go to the Preferences tab.
- In NetSuite, go to Setup > Accounting > Accounting Preferences, then capture the following steps:
   - On the General tab, uncheck Require Approvals on Journal Entries.
   - On the Approval Routing tab, uncheck Journal Entries/Vendor Bills to remove the approval requirement for Journal Entries created in NetSuite.
- In NetSuite, navigate to Setup > Company > Enable Features, click the “Employee” tab, and highlight the unchecked “Approval Routing”.

**Comment by maddylewis** [comment]
closing! https://github.com/Expensify/App/issues/50093#issuecomment-2391856297
