### ISSUE TITLE
[HOLD for payment 2024-11-05] HelpDot image request for QBD Expensify Classic articles

### ISSUE THREAD

**Issue by ren-jones** [Expensify/App#50106]
Please provide the following images in light mode and in .png format. **Whoever completes this task will need a connection to QuickBooks Desktop.** I do not have access to the QBD connection and therefore do not know how accurate or feasible a couple of these requests are. Please let me know if any of the steps below are inaccurate.

**CONFIGURE QUICKBOOKS DESKTOP**

Link to article: https://help.expensify.com/articles/expensify-classic/connections/quickbooks-desktop/Configure-Quickbooks-Desktop

- In Expensify, go to Settings > Workspaces > [Workspace name] > Connections > highlight the Export button under the QuickBooks Desktop connection. 
   - In another photo, highlight the Sync button. 
   - In another photo, highlight the Import button. 
   - In another photo, highlight the Advanced option/tab. 
   - In a final photo, highlight the Autosync option.

**QUICKBOOKS DESKTOP TROUBLESHOOTING**

Link to article: https://help.expensify.com/articles/expensify-classic/connections/quickbooks-desktop/Quickbooks-Desktop-Troubleshooting

- Right-click the Web Connector icon on your desktop and select Run as administrator.
- In QBD, show the following steps in images: 
   - Log in to QuickBooks Desktop as an Admin (in single-user mode).
   - Go to Edit > Preferences > Integrated Applications > Company Preferences.
   - Select the Web Connector and click Properties.
   - Make sure that the “Allow this application to login automatically” checkbox is selected and click OK.
- In the Web Connector, show the following steps in images: 
   - Check that the Last Status is “Ok”.
   - Check the Report Comments in Expensify to confirm that the report has been successfully exported to QuickBooks Desktop.

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify / @kadiealexander</details>

**Comment by maddylewis** [comment]
@jliexpensify - assigning you as a liaison for assisting design with getting a few QBD images for the Exfy Classic. since you handled the recent updates to QBD on HelpDot I figured i would assign this one to you to assist. tysm!

**Comment by maddylewis** [comment]
ah looks like Jli is OOO. @kadiealexander if you have some bandwidth over the next few days to assist with some QBD screenshots for these help docs, that would be lovely!

**Comment by dubielzyk-expensify** [comment]
I need some screenshot help here as I don't have an account with QBD access. Is it possible to get the screenshots above in 1440x900 resolution. Then I can wrap them up into our screenshots template

**Comment by kadiealexander** [comment]
In Expensify, go to Settings > Workspaces > [Workspace name] > Connections > highlight the Export button under the QuickBooks Desktop connection.

![image](https://github.com/user-attachments/assets/4d875b39-b751-42c5-bb87-a03a17c69ece)

In another photo, highlight the Sync button.

![image](https://github.com/user-attachments/assets/f01acd6d-8173-4e04-80b9-9b6dc72950dd)

In another photo, highlight the Coding button.

![image](https://github.com/user-attachments/assets/bfd13c44-de0e-4c53-8f6c-940430fd9769)

In another photo, highlight the Advanced option/tab.

![image](https://github.com/user-attachments/assets/7cbc4b97-150d-4759-9d63-b63d33a69048)

In a final photo, highlight the Autosync option. - it's in the advanced tab above, I don't think it's useful to highlight it twice. 

In QBD, show the following steps in images:
Log in to QuickBooks Desktop as an Admin (in single-user mode). - This isn't really something that's screenshottable. 

Go to Edit > Preferences > Integrated Applications > Company Preferences.

![image](https://github.com/user-attachments/assets/fb190938-c5dc-4313-904a-5bba751efbe2)

Select the Web Connector and click Properties. Make sure that the “Allow this application to login automatically” checkbox is selected and click OK.

![image](https://github.com/user-attachments/assets/c47aa439-0c2f-4581-8133-c5c9dc87e683)

In the Web Connector, show the following steps in images:
Check that the Last Status is “Ok”.

![image](https://github.com/user-attachments/assets/63633f05-1d61-4178-8bfc-856d38572d93)

Check the Report Comments in Expensify to confirm that the report has been successfully exported to QuickBooks Desktop.

![image](https://github.com/user-attachments/assets/cf2c8296-73e2-4805-9d3d-ca6613d19536)

**Comment by dubielzyk-expensify** [comment]
Alright. Here's the screenshots. Please check and ensure they're all correct:



[The zip file with mocks: qbd.zip](https://github.com/user-attachments/files/17321210/qbd.zip)

<img width="1000" alt="qbd01" src="https://github.com/user-attachments/assets/9f2decb8-2621-4792-9300-81eb97167710">
<img width="1000" alt="qbd02" src="https://github.com/user-attachments/assets/62ab67ad-bce5-41c2-983b-7234702acc64">
<img width="1000" alt="qbd03" src="https://github.com/user-attachments/assets/d3011017-566a-4281-b6d7-1ebefa56e075">
<img width="1000" alt="qbd04" src="https://github.com/user-attachments/assets/3a39d49e-b24a-499c-9e64-d77cc1cff1e1">
<img width="1000" alt="qbd05" src="https://github.com/user-attachments/assets/4cb8092c-6f3f-4f5e-94cf-722268cddd78">
<img width="1000" alt="qbd06" src="https://github.com/user-attachments/assets/94e9c76c-c92f-4b3e-8955-a115e9b085d3">
<img width="1000" alt="qbd07" src="https://github.com/user-attachments/assets/c641480e-d455-4f1c-9101-d8a13cb09093">

**Comment by kadiealexander** [comment]
@dubielzyk-expensify these look great! @ren-jones do you need us to add them to the article?

**Comment by kadiealexander** [comment]
Adding the images to HelpDot here. https://github.com/Expensify/App/pull/50702

**Comment by kadiealexander** [comment]
Added images to the articles [here](https://github.com/Expensify/App/pull/50757).
