### ISSUE TITLE
iOS - The phone heats up quickly when actively using the app with an expensifail account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50104]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with an expensifail account
3. Keep actively using the app for 3-5 minutes (track or submit different expense types)

## Expected Result:
It shouldn't heat up this much during a short amount of useage.

## Actual Result:
The phone heats up quickly when actively using the app with an expensifail account. A gmail account doesn't heat up as much.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[0210.txt](https://github.com/user-attachments/files/17234911/0210.txt)

https://github.com/user-attachments/assets/808c4bad-2172-41d5-aedb-b88d699f6efa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment]
This is definitely my first time seeing a bug report based on physical temperature 😂

Not sure how to react, but I guess it's a fair report.

Does it happen only on staging but not production?

**Comment by jasperhuangg** [comment]
Relevant discussion is [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1727896624465699)

**Comment by mananjadhav** [comment]
@jasperhuangg @roryabraham Can one of you assign this issue to me ?

**Comment by mananjadhav** [comment]
@johncschuster I had helped with the review of the PR here.

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor+: @mananjadhav due $250 via NewDot

**Comment by mananjadhav** [comment]
Thanks @johncschuster.

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
