### ISSUE TITLE
[HybridApp] New sign-up can't complete the "what's your name?" onboarding step

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#50117]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.43-3 (HybridApp)
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1727901034273459?thread_ts=1727720726.113539&cid=C036QM0SLJK (#wave-collect thread)

## Action Performed:
Prerequisite: must be using the HybridApp and be on the `hybridAppRedirect` beta

1. Sign up with a new account on HybridApp
2. Choose "Manage my team's expenses" 
3. Add a work name > next
4. Add a first name/last name > confirm
5. Observe the confirm button is unresponsive
6. Click the back caret `<` 
7. Observe the back caret is unresponsive

## Expected Result:
You should be able to complete the onboarding steps on HybridApp. For comparison, here's the same version on the NewDot standalone app:

https://github.com/user-attachments/assets/86b60dc0-28a1-4b3c-a7ea-93efbf32cfaf

## Actual Result:
Can't complete the "What's your name?" step:

https://github.com/user-attachments/assets/ba435ba1-76a2-4f1a-a51c-e1cce9c0002d

## Workaround:
I killed the app, reopened it, and it seemed to have then completed guided setup, created the workspace and added the onboarding tasks:

![IMG_0904](https://github.com/user-attachments/assets/5af3edd9-a620-43c4-83bf-2a85881f2f02)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

In line above. 
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by staszekscp** [comment]
I'm on it!

**Comment by staszekscp** [comment]
I've just tested if the bug exists on [this PR](https://github.com/Expensify/Mobile-Expensify/pull/13159), and it will solve the issue!

**Comment by trjExpensify** [comment]
Fix for this has merged, closing.
