### ISSUE TITLE
[HOLD for payment 2024-10-11] [Performance] Investigate performance regression to app open time (reported by e2e system)

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#50141]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?

The e2e performance test have reported a performance regression:

Name | Duration
-- | --
App start TTI | 1265.941 ms → 1922.656 ms (+656.715 ms, +51.9%) 🔴🔴
App start contentAppeared_To_screenTTI | 540.925 ms → 1235.091 ms (+694.166 ms, +128.3%) 🔴🔴

The regressions are testing from commit https://github.com/Expensify/App/commit/a6ff319010c4839a20216b31c2c4d213abcbf218 against version https://github.com/Expensify/App/releases/tag/9.0.43-4

In between those changes must be a regression

## What is the impact of this on end-users?

App start time is delayed by ~600ms

## List any benchmarks that show the severity of the issue

See e2e tests

## Proposed solution (if any)

None yet. We need to find the faulty commit first.

## List any benchmarks after implementing the changes to show impacts of the proposed solution (if any)

E2e test results should improve

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Comment by hannojg** [comment]
please assign to me

**Comment by hannojg** [comment]
This is very likely being fixed here:

- https://github.com/Expensify/App/pull/50143

**Comment by luacmartins** [comment]
Draft PR [here](https://github.com/Expensify/App/pull/50143), should be ready for review soon

**Comment by jasperhuangg** [comment]
@hannojg @luacmartins Were we able to retest this?
