### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Automate author checklist with ESLint rules

### ISSUE THREAD

**Issue by szymonrybczak** [Expensify/App#50154]
### Problem:

The current Author Checklist for creating a Pull Request contains 48 checks, which is an excessive number of items to be manually verified every time a PR is submitted. This lengthy process can slow down the development workflow. 

### Solution

Automate checks with ESLint rules where possible, as we've found some checklist items that can be easily automated.

- `I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. myBool && <MyComponent />.`
    
    Here’s a diff presenting a potential implementation: https://github.com/callstack-internal/eslint-config-expensify/commit/b31ad449c6c979c79bb476eaa34c5d5b397f727a.
    
    After applying diff locally there’s only one error in whole codebase:
    
    ```
    ❯ npm run lint
    
    > new.expensify@9.0.37-0 lint
    > NODE_OPTIONS=--max_old_space_size=8192 eslint . --max-warnings=0 --cache --cache-location=node_modules/.cache/eslint
    
    This is not a desktop build, adding babel-plugin-annotate-react
    babel.config.js
      - api.version: 7.24.5
      - api.env: development
      - process.env.NODE_ENV: undefined
      - process.env.BABEL_ENV: undefined
      - running in:  undefined
    
    ~/Users/szymonrybczak/callstack/App/src/pages/workspace/distanceRates/PolicyDistanceRatesSettingsPage.tsx
      102:30  error  The left side of conditional rendering should be a boolean, not Unit  rulesdir/boolean-conditional-rendering
    
    ✖ 1 problem (1 error, 0 warnings)
    ```
    
    The lint rule examines the left-side condition of an expression. If it detects a non-boolean value, it raises an error — once this rule is implemented, we can remove the corresponding check from the Author Checklist in the Pull Request template.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849137380340533101</li>
        <li>Upwork Job ID: 1849137380340533101</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by mountiny** [comment]
@rayane-djouah for implementation, what is your eta for the pr, soˇe diff is already available

**Comment by mountiny** [comment]
@szymonrybczak is going to review the eslint PR

**Comment by mountiny** [comment]
@rayane-djouah merged, can you please make App PR now 🙏

**Comment by mountiny** [comment]
Merged

**Comment by sakluger** [comment]
@mountiny it looks like this one is pretty much complete! How should we handle payment for this issue? $250 to @rayane-djouah in 7 days?

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor: @rayane-djouah $250, sent offer via Upwork: https://www.upwork.com/nx/wm/offer/104560122

**Comment by mountiny** [comment]
@rayane-djouah we still need to update App right?

**Comment by sakluger** [comment]
Okay we'll wait to pay out until 7 days after the App PR is deployed.
