### ISSUE TITLE
RHP across the app cannot be closed by ESC key

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50156]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh011001@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open any RHP (via FAB > Submit expense, or open Find page).
3. Press ESC.

## Expected Result:
RHP can be closed by ESC key.

## Actual Result:
RHP cannot be closed by ESC key.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5b756db3-5732-4f37-93b9-7aa88895bff8

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment]
I reproduced on staging **v9.0.44-0** and not on prod **v9.0.43-6**

**Comment by arosiclair** [comment]
Confirmed reverting https://github.com/Expensify/App/pull/49457 fixes the issue. Should we just CP https://github.com/Expensify/App/pull/50143?

**Comment by luacmartins** [comment]
Yea, I requested the CP

**Comment by jasperhuangg** [comment]
CP is running

**Comment by arosiclair** [comment]
Fixed in **v9.0.44-2**

https://github.com/user-attachments/assets/a55675d6-adab-4494-b794-32e3ecfaebd5
