### ISSUE TITLE
[HOLD for payment 2024-10-14] [HOLD for payment 2024-10-11] [Payment due] Sign up - Validate your account page opens after validating account and adding bank account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50153]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** yonghongkok2+2eksdo0@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account.
3. Complete onboarding.
4. Go to Account settings > Wallet.
5. Click Add bank account.
6. Enter correct magic code.
7. Add a bank account.
8. Complete the bank account setup.

## Expected Result:
After the bank account is set up, app will not show Validate your account RHP.

## Actual Result:
After the bank account is set up, app shows Validate your account RHP.
The same issue also happens when user validates bank account from Enable wallet CTA and then clicks RHP back button.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2eeec311-ae67-4f24-9e32-27034a0c6874

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by Gonals** [comment]
Seems to be a frontend issue

**Comment by jasperhuangg** [comment]
Seems Jules has already signed off for the day so I can take this one.

**Comment by jasperhuangg** [comment]
This is a bug that wasn't caught during review in https://github.com/Expensify/App/pull/49230

**Comment by jasperhuangg** [comment]
cc @daledah Are you available to fix this?

**Comment by jasperhuangg** [comment]
cc @arosiclair @jjcoffee

**Comment by jasperhuangg** [comment]
The PR causes another blocker, but I think it would be better to fix than revert since the PR is so large.

**Comment by arosiclair** [comment]
CP is done and testing well! Just @ishpaul777 will need a payment once this is deployed

**Comment by jasperhuangg** [comment]
cc ^ @dylanexpensify for visibility

**Comment by dylanexpensify** [comment]
Payment summary:

Contributor+: @ishpaul777 $250 via Upwork

Please apply/request!

**Comment by dylanexpensify** [comment]
Coming up!

**Comment by dylanexpensify** [comment]
Coming up!

**Comment by dylanexpensify** [comment]
@ishpaul777 please apply [here](https://www.upwork.com/jobs/~021845832123208273600)!

**Comment by dylanexpensify** [comment]
@ishpaul777 nice one, offer sent!

**Comment by dylanexpensify** [comment]
Done!
