### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Expense - Add receipt modal disappears and then reappears after the receipt is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50159]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh0110001@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense with receipt to any user
3. Go to transaction thread
4. Click on the receipt
5. Click 3-dot menu > Delete receipt
6. Delete the receipt

## Expected Result:
Add receipt modal will not disappear and reappear after the receipt is deleted

## Actual Result:
Add receipt modal disappears and then reappears after the receipt is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/16f98e43-95d5-494e-afe2-6ed56b713aa2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841875580285563023</li>
        <li>Upwork Job ID: 1841875580285563023</li>
        <li>Last Price Increase: 2024-10-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by jasperhuangg** [comment]
I'm applying the necessary labels but leaving it you to decide whether this is something worth fixing @thienlnam

**Comment by nkdengineer** [comment]
Will raise the PR soon.

**Comment by nkdengineer** [comment]
@dukenv0307 this [PR](https://github.com/Expensify/App/pull/50207) is ready for review

**Comment by kadiealexander** [comment]
Closing as no one is due payment here.
