### ISSUE TITLE
[HOLD for payment 2024-10-14] [$125] Add "clear" button to saved search name field

### ISSUE THREAD

**Issue by dannymcclain** [Expensify/App#50163]
## Problem
Saved searches often have super long names, so when users go to rename them, it's cumbersome to clear the name input.

![CleanShot 2024-10-03 at 10 27 02@2x](https://github.com/user-attachments/assets/ad9ec786-b539-4b9f-96c2-e0b1a84d6d26)

## Solution
Let's add the "clear" button that we added to the Group name input to solve the same problem.

![CleanShot 2024-10-03 at 10 27 52@2x](https://github.com/user-attachments/assets/61e0d2b4-ec3c-4610-8a60-e078ae68a613)

### Notes
- The clear button for the saved search name field should look and function identically to the one in the group name field.

cc @Expensify/design @roryabraham 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841865344980745582</li>
        <li>Upwork Job ID: 1841865344980745582</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104256804</li>
<li>nyomanjyotisa | Contributor | 104256806</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by sher999** [comment]
<img width="1202" alt="Screenshot 2024-10-03 at 9 26 30 PM" src="https://github.com/user-attachments/assets/b575b452-91a1-4c4c-9025-024bfaebe5e9">


added `shouldShowClearButton`

**Comment by mountiny** [comment]
I have decreased the reward for this as its super simple change

**Comment by stephanieelliott** [comment]
Thanks! Regression test issue here: https://github.com/Expensify/Expensify/issues/new

**Comment by stephanieelliott** [comment]
I don't know how I missed payment on this one -- so so sorry for the long wait! 

Summarizing payment on this issue: 

 - Contributor: $250  @nyomanjyotisa via Upwork - PAID!
 - Contributor+: $250 @dukenv0307 via Upwork - PAID!
 
 Upwork job is here: https://www.upwork.com/jobs/~021841865344980745582
