### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Workspace settings - There is back button on not found page for wide screen

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50175]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** expensify416+da2@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. User A - Invite user B to workspace
2. User A - Navigate to the workspace > More features > copy the link from browser bar
3. User A - Send the URL to user B
4. User B - Open the URL

## Expected Result:
There shouldn't be back button on not found page for wide screen. It should be available only for small screen (mobile)

## Actual Result:
Back button is available for wide screen. That makes it a redundant back button for workspace page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/afe4ae6b-d0fe-4d51-ac4e-20e475fcca06

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843399831747959638</li>
        <li>Upwork Job ID: 1843399831747959638</li>
        <li>Last Price Increase: 2024-10-07</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 104343679</li>
<li>Krishna2323 | Contributor | 104343684</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment]
@aimane-chnaif - when you get a chance, can you please review these proposals? Thanks!

**Comment by alexpensify** [comment]
## Heads up, I will be offline until Tuesday, October 22, 2024, and will not actively watch over this GitHub during that period.

If this GitHub requires an urgent update, please ask for help in the #expensify-open-source Slack Room. If the inquiry can wait, I'll review it when I return online.

**Comment by flaviadefaria** [comment]
This doesn't look like a Migrate issue so removing it from the project.

**Comment by alexpensify** [comment]
Payouts due: 2024-10-25

- [ ] Contributor: $250 @Krishna2323 
- [ ] Reviewer: $250 @aimane-chnaif 

Upwork job is [here](https://github.com/Expensify/Web-Expensify/pull/44138). Closing - everyone has been paid via Upwork.
