### ISSUE TITLE
"ReconnectApp" isn't showing up in Chrome network tab when switching chats

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50172]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:**  Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/47913
## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a Gmail account
3. Press F12 and switch to the network tab
4. Navigate to Account settings - Troubleshoot
5. Enable "Simulate failing network requests"
6. Navigate to the LHN
7. Switch between different chats
8. Open a 1:1 DM and send some messages
9. Navigate to Account settings - Troubleshoot
10. Disable "Simulate failing network requests"
11. Input "ReconnectApp" to the Chrome network - Filter field
12 Press CTRL + F
13. Input and search for "ReconnectApp" to the Chrome - network - search - Find field

## Expected Result:
"ReconnectApp" should show up

## Actual Result:
"ReconnectApp" isn't showing up in Chrome network tab when switching chats or sending messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/336d23b7-4da8-44f4-8d74-ff3160e782cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment]
IIRC we don't call ReconnectApp unless you reload the page or go from offline => online. @yuwenmemon Can you confirm? We should probably be able to close this out.

cc @roryabraham since you reviewed https://github.com/Expensify/App/pull/47913. I think the testing steps in the PR might be inaccurate.
