### ISSUE TITLE
[$250] [HOLD for payment 2024-10-17] Xero - Accounting page reloads when 2FA setup RHP opens

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50213]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- 2FA is not set up.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting.
3. Click Connect next to Xero.
4. Click Enable two-factor authentication.

## Expected Result:
Accounting page will not reload when 2FA setup RHP opens (production behavior).

## Actual Result:
Accounting page reloads when 2FA setup RHP opens.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bf620d83-6844-42b7-a5de-8aa8c4fe5751

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845920887092248256</li>
        <li>Upwork Job ID: 1845920887092248256</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by jasperhuangg** [comment]
Not the worst bug, we don't need to block deploy on this

**Comment by c3024** [comment]
@jasperhuangg 

The reload of the accounting pane does not happen anymore but the screen flickers. The screen flicker does not seem to be related to any changes made in #50226. We can update the present issue's description to fix the flicker and handle that in this issue.

**Comment by MonilBhavsar** [comment]
This seems related to https://github.com/Expensify/App/issues/45572 🤔

**Comment by c3024** [comment]
@MonilBhavsar 

I don't think it is related to that. The 2FA requirement modal is just a modal and not part of a modal navigator. So, I think we need not call `dismissModal` here. Removing it fixes this issue.

https://github.com/Expensify/App/blob/08becfdf57e70346448731a55512ebaf67345d6c/src/components/ConnectToXeroFlow/index.tsx#L37

**Comment by MonilBhavsar** [comment]
Thanks for checking!
Since you know the fix, do you want to put up a PR?

**Comment by c3024** [comment]
Yes, I will raise a PR. Thanks!

**Comment by MonilBhavsar** [comment]
Thank you! Happy to review it

**Comment by MonilBhavsar** [comment]
PR was merged
Thanks @c3024 for quick work!

**Comment by CortneyOfstad** [comment]
@c3024 — I sent you a proposal in Upwork — please let me know once you accept! Also, please complete the checklist before 10/17 so there is no delay in issuing payment. Thank you!

**Comment by CortneyOfstad** [comment]
@VictoriaExpensify I am heading OoO (10/15 to 10/23), so got this reassigned to keep it moving! Right now, we're waiting on @c3024 to accept the proposal [here](https://www.upwork.com/jobs/~021845920887092248256), and payment is due 10/17. Thanks!

**Comment by VictoriaExpensify** [comment]
Payment summary:
C+: @c3024 paid $250 via Upwork
