### ISSUE TITLE
Attachment - No real time text messages until video is received

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50217]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** gocemate+a2470@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. User A send message to User B
2. User B verify that message is received
3. User A send mp4 attachment to User B
4. User A send message to User B

## Expected Result:
User B should receive text message in real time, independent of video file that is sent

## Actual Result:
User B does not receive the text message sent after sending mp4 until mp4 attachment is recieved

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/da474194-ad6e-4674-b291-4ea13d9bcb2c

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
I think this is intended behavior - the chats should be received in order so would be held for sending after the video as finished uploading.
