### ISSUE TITLE
[$250] Attachment - Change Playback speed option is missing in fullscreen mode

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50218]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5042989&group_by=cases:section_id&group_id=292107&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+omqq1@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open app
2. Navigate to any chat
3. Upload any video to the chat
4. Tap on the viedo preview
5. Tap on the fullscreen button
6. Tap on the video to reveal video controls buttons

## Expected Result:
Change playback speed option should be available in the fullscreen mode

## Actual Result:
Change playback speed option is missing in fullscreen mode

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e4c20da7-e476-4d72-af70-f1a6441f0928

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846307754007931609</li>
        <li>Upwork Job ID: 1846307754007931609</li>
        <li>Last Price Increase: 2024-11-05</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by johncschuster** [comment]
I don't have an android phone so I'm not 100% sure what I would expect to see here, but I kinda don't expect to see a playback speed setting. 

Have you seen one previously, @IuliiaHerets?

**Comment by johncschuster** [comment]
@IuliiaHerets bump on the question above!

**Comment by IuliiaHerets** [comment]
@johncschuster To be honest, I'm not sure if it was present on Android, but it's present on iOS. I think the behavior should be the same.

https://github.com/user-attachments/assets/3fea254b-78a5-49f2-8f18-9f40b1325f13

**Comment by johncschuster** [comment]
Looks like we're still waiting on proposals for this one.

**Comment by johncschuster** [comment]
Bump

**Comment by suneox** [comment]
I’ve posted on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1729475905364619) to get more eye

**Comment by johncschuster** [comment]
[Bumped Slack again for proposals](https://expensify.slack.com/archives/C01GTK53T8Q/p1729714839507149)

**Comment by johncschuster** [comment]
Bumped again in Slack

**Comment by johncschuster** [comment]
Chatting about this in Slack

**Comment by suneox** [comment]
As [discussed](https://expensify.slack.com/archives/C01GTK53T8Q/p1729714839507149), I think we can close this issue
