### ISSUE TITLE
Search-Cannot open search router from the Search page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50220]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.44-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49457
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to Search page
2. Open Search router

## Expected Result:
The magnifying glass at the top next to the page title (Search) is displayed.
Clicking the magnifying glass opens the Search Router.

## Actual Result:
The magnifying glass at the top next to the page title (Search) is not displayed.
The Search router cannot be opened.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6623910_1728010684421!49457-Web](https://github.com/user-attachments/assets/ebbd7e5f-9063-4f24-b1ef-5aad4e621041)
![Bug6623910_1728010684416!49457-mWeb](https://github.com/user-attachments/assets/e7f7a0c9-259c-4baa-9567-f79d20624076)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Kicu** [comment]
Thanks for responding to this @rayane-djouah 
Here is the draft for enabling new router everywhere, and I expect to open it for review later today

**Comment by joekaufmanexpensify** [comment]
Seems like this is being handled elsewhere, so closing this out. LMK if anyone thinks that's not correct!
