### ISSUE TITLE
[HOLD for payment 2024-10-30] Card - "*member* added shipping details" message appears when the details aren't set yet

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50233]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Expensify Card"
6. Navigate to Workspace settings - Members
7. Invite a Gmail address that doesn't have an account yet
8. Navigate to Workspace settings - Expensify Card
9. Click on the "Issue new card" button
10. Add bank account details and finish the BA flow
11. Click on the "Issue new card" button
12. Select the new member
13. Select "Physical card
14. Add the card with any limit type, limit and name
15. Navigate to the workspace chat with the member

## Expected Result:
A different message should be visible as the member didn't add shipping details yet.

## Actual Result:
"*member* added shipping details. Expensify Card will arrive in 2-3 business days." message appears for the admin.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b5b2d6d9-2319-447e-9af6-81d5a35f17b4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mountiny** [comment]
Yeah, I see that we added the `isAssigneeCurrentUser` there, but that is incorrect.

I think what we can do is:
- remove isAssigneeCurrentUser and missing details so we always just show the personal details are missing
- when the card is issued we add the CARD_ISSUED action which tells that the card will arrive in 2-3 days

It's like an audit trail; I think it's okay to just leave the MISSING_ADDRESS report action as is, given that the next report action clarifies that the address was provided and shipped.

**Comment by mountiny** [comment]
This is a regression from PR from @shubham1206agra so I think it makes sense for them to raise a fix PR

**Comment by mountiny** [comment]
@allgandalf @shubham1206agra can you please complete the checklist?

**Comment by JmillsExpensify** [comment]
Payment summary: 

- $250 for @shubham1206agra via Upwork
- $250 for @allgandalf via Upwork

**Comment by JmillsExpensify** [comment]
Send you both manual offers via Upwork.

**Comment by JmillsExpensify** [comment]
Paid out @shubham1206agra. Will pay out @allgandalf once he's able to accept.

**Comment by JmillsExpensify** [comment]
Regression test created and everyone has been paid out. Closing this one.
