### ISSUE TITLE
[$250] Search - "From" shows receiver, "To" shows sender when submitting track expense to someone

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50249]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a manual expense.
4. Click Submit it to someone from the whisper.
5. Select any user and submit it.
6. Go to Search.
7. Look for the expense submitted to the user.

## Expected Result:
From and To field will show the correct sender and receiver.

## Actual Result:
From field shows the receiver, while To field shows the sender, when it should be the other way around.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3cba9282-d239-4cf8-a72e-5834f6d1b076

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843324942159771511</li>
        <li>Upwork Job ID: 1843324942159771511</li>
        <li>Last Price Increase: 2024-10-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lakchote</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by zfurtak** [comment]
Hello, I'm Zuza from software mansion agency and I would like to work on this issue.

**Comment by sakluger** [comment]
Hey @zfurtak, please let us know when you have a proposal for how to fix this issue. Thanks!

**Comment by zfurtak** [comment]
Sorry for the delay! Another issue popped up in the meantime but right now I'm working on this

**Comment by zfurtak** [comment]
I checked the flow and noticed that the search API is returning the wrong values 🔍.

When we switch `Track expense` to `Submit to someone`, there's a transaction object with an attached report. The report should have `ownerAccountID` set as the sender and `managerID` as the recipient, and they look good there. But, the data we get back from the search API (`snapshot_....`) has the `managerID` mixed up, and `accountID` shows the recipient's info when it should match up with `ownerAccountID`.

It seems like this issue might be on the backend since the data we're getting is incorrect.

**Comment by getusha** [comment]
Pulling an internal engineer to take a look at [this](https://github.com/Expensify/App/issues/50249#issuecomment-2404626010)
🎀 👀 🎀

**Comment by AndrewGable** [comment]
@luacmartins @lakchote - As experts of the search API you have any thoughts about this?

**Comment by luacmartins** [comment]
Seems like a bug to me, probably internal

**Comment by lakchote** [comment]
I'll be working on resolving this.

**Comment by sakluger** [comment]
@lakchote just to confirm, we did not have any C+ review on this one? So no payment is required?

**Comment by sakluger** [comment]
If so, then we can close this one out immediately because it is deployed.

**Comment by luacmartins** [comment]
This was all internal, so we're good to close.
