### ISSUE TITLE
[HOLD for payment 2024-10-30] Expensify Card - Cards are not assigned in table for newly created accounts

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#50248]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-8

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes
 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3272217
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Issue reported by:** Applause - Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Expensify Card"
6. Navigate to Workspace settings - Members
7. Invite a Gmail address that doesn't have an account yet
8. Navigate to Workspace settings - Expensify Card
9. Click on the "Issue new card" button
10. Add bank account details and finish the BA flow
11. Click on the "Issue new card" button
12. Select the new member
13. Select "Virtual card"
14. Add the card with any limit type, limit and name
15. Navigate to Workspace settings - Members
16. Click on the member added in step 7

## Expected Result:
After assigning the card, it should be displayed in the cards table and assigned to the member. 

## Actual Result:
The virtual card is missing from the "Expensify Card" page and also from the workspace member profile page. I'm also unable to add a virtual card with the Workspace Member profile - New card flow.

## Workaround:
No workaround found. No way to issue Ecards to new members

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/662468b8-f839-4a03-b729-7660be317231

https://github.com/user-attachments/assets/df064e53-4c0a-4577-9ff9-58b4ab08a98b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by isagoico** [comment]
Note: We're able to assign cards to existing accounts. Take the following example from a test workspace: 
I'm able to assign cards to applausetester+ig1@applause.expensifail.com but not to isagoicotest+newtest@gmail.com (new account.

![image](https://github.com/user-attachments/assets/0b02d6d5-c1ce-4d86-8749-350ff2693bc2)

**Comment by mountiny** [comment]
@isagoico can you please share the email used here and check if the accounts been validated or not? If you can see the response of the call that would be helpful in future too, whenever something is not happening as expected add console logs and network logs. Thanks

**Comment by mountiny** [comment]
> Should we allow assigning physical and virtual cars to unvalidated accounts?

I don't think we should allow that, at least that would require larger discussion. I think we can keep it this was but handle showing RBR and clear error when this happens. 

I have confirmed the QA tester had the same issue.

@cretadn22 I believe the solution is to handle a failureData for creating the virtual card, I think we need to add optimistic data and failure data to the issue card flow, right now we lack feedback. @koko57 @VickyStash do you recall if there is a reason we did not add it in a first place?

**Comment by koko57** [comment]
@mountiny I think we haven't considered such case while working on that. I can implement this solution.

**Comment by mountiny** [comment]
@koko57 lets do it

**Comment by mountiny** [comment]
@cretadn22 we working on workspace feeds as a project and the correct solution here is to use failure data so we will handle it with expert agency

**Comment by koko57** [comment]
@mountiny tp which Onyx entry should we add the error for failureData - personalDetails? 
I've also noticed one thing - when we enable Expensify Card, and before we choose a bank account go to member's details, click Issue New Card and try to issue a new card we get this error
<img width="417" alt="Screenshot 2024-10-08 at 12 08 52" src="https://github.com/user-attachments/assets/af0039c3-2324-4046-9561-86d8d9128d80">
 Maybe for this one it's better not to show the Assigned Cards section and the Issue New Card button until we choose payment bank account for the card?

**Comment by mountiny** [comment]
hmm yeah the business should be provisioned once the bank account is chosen, can you add detailed steps for this flow please?

And I think the failure data would be on the card itself in the cards_ collection, then the RBR is ion the cards page

**Comment by koko57** [comment]
@mountiny steps:
1. Enable Expensify Card on a workspace.
2. Don't add the bank account, go to members page, open a member's details page
3. Click Issue New Card, go through the flow

> And I think the failure data would be on the card itself in the cards_ collection, then the RBR is ion the cards page

but as the card cannot be issued we won't have the cardID for cards collection

**Comment by mountiny** [comment]
@koko57 I think in this case we are talking about the flow where the domain is correctly provisioned and you issue the card from the expensify card page. 

To fix the above, I think we should just hide the new Expensify card option if the policy is not provisioned (so the expensifyCardsSettings does not exist with the required values

**Comment by koko57** [comment]
@mountiny I know - but I wanted to mention it as it was something I noticed while recreating the original issue. So ok, I will hide the section until the domain is provisioned.

**Comment by mountiny** [comment]
Perfect, thank you!

**Comment by koko57** [comment]
@mountiny but for the RBR for the original issue - i think it should be on the Member details page

**Comment by mountiny** [comment]
We are still discussing how to handle this, I believe the best will be to make sure we await the response that the card was successfully created

**Comment by koko57** [comment]
PR ready for review https://github.com/Expensify/App/pull/50644

**Comment by koko57** [comment]
I'll be ooo Monday - Tuesday (14-15 Oct) if there will be some changes required to my PR and you'd like to merge it asap - please ping Callstack team, someone might be able to take it over. Thanks!

**Comment by dylanexpensify** [comment]
Reassigning as I head to parental leave next week! Thanks Garrett!

**Comment by mountiny** [comment]
Pr in review here

**Comment by koko57** [comment]
PR is merged, this issue can be retested

**Comment by mountiny** [comment]
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1729680154144859)

**Comment by mountiny** [comment]
The regression test for this was already handled as part of the workspace feeds project. The fix was in backend to ensure we return the card in the https response too so it show sup immediately.

I think we can close this one out as we have handled the payments for the project already
