### ISSUE TITLE
 Expensify Card -Issue card button has blue border when navigating to confirm page via keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50241]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+khcategory16@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Bank account is already set up in Expensify Card page
1. Go to staging.new.expensify.com
2. Go to workspace settings > Members
3. Click on any member
4. Click New Card
5. Proceed to "Give it a name" page
6. Enter card name and hit Enter

## Expected Result:
Issue card button on the confirmation page will not have blue border

## Actual Result:
Issue card button on the confirmation page shows blue border when navigating via keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/6e1d2ae6-03c8-42a8-9303-d177202f3a28

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by adelekennedy** [comment]
I think i've actually seen this pattern elsewhere when navigating with the keyboard - going to close for now
