### ISSUE TITLE
iOS - Expensify Card - Member email is truncated on the card page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50245]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Expensifail account
3. Create a workspace
4. Navigate to Workspace settings - More features
5. Enable "Expensify Card"
6. Navigate to Workspace settings - Members
7. Invite a longer Gmail address that doesn't have an account yet
8. Navigate to Workspace settings - Expensify Card
9. Click on the "Issue new card" button
10. Add bank account details and finish the BA flow
11. Click on the "Issue new card" button
12. Select the new member
13. Select "Physical card"
14. Add the card with any limit type, limit and name

## Expected Result:
The email should only be truncated if it would be overlapping with the "Limit" field

## Actual Result:
Member email is truncated on the card page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f86494f0-bc7a-46f0-94ae-4962c1f35341

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment]
Looking

**Comment by isabelastisser** [comment]
I think this is expected so we can accommodate the last four digits of the card on mobile:

<img width="425" alt="image" src="https://github.com/user-attachments/assets/d768d1e9-68b9-48c2-9dbd-cbd630c53040">
