### ISSUE TITLE
[Search v2.4] Search Router Polish Issues

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#50250]
- [x] CMD + K should close the modal when it's already open
- [x] Searching with filters that match a saved search should open the saved search in the LHN
- [x] No need to show default searches in the recents.
- [x] Clicking on a contextual filter in the search results takes you back to the default filters, rather than adding an extra search query to the existing search results. We need to preserve the current context and just add/update the type/status
- [x] [Using the router to `Search in` and putting a link removes the link for the search results](https://expensify.slack.com/archives/C06ML6X0W9L/p1728287879352319?thread_ts=1727907702.678009&cid=C06ML6X0W9L)
- [ ] [If `Search in` suggests a workspace chat, we should add the `reportID` filter instead of `in`. Same goes for invoice and trip rooms](https://expensify.slack.com/archives/C06ML6X0W9L/p1728287678155109?thread_ts=1727907702.678009&cid=C06ML6X0W9L)
- [x] [BUG: A parsing error occurs when special characters, such as ä, are used.](https://github.com/Expensify/App/pull/49838#issuecomment-2396934904)
- [x] [Filter order changes when selected via UI vs typed in the input](https://github.com/Expensify/App/pull/49838#issuecomment-2406098388)
- [x] Typing amount>200 returns expenses with amounts below $200 (we are still processing the value as cents)
- [x] [Improve performance of filter validation](https://github.com/Expensify/App/pull/49838#discussion_r1797182465)
- [x] [Some hidden chats show up without a name](https://expensify.slack.com/archives/C05LX9D6E07/p1729017808078139?thread_ts=1729007631.513779&cid=C05LX9D6E07)

**Comment by SzymczakJ** [comment]
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by luacmartins** [comment]
@SzymczakJ just an FYI we're still adding more items to this issue as we test the feature

**Comment by SzymczakJ** [comment]
> we're still adding more items

Then I'll focus on other issues and come back to this PR later.

**Comment by luacmartins** [comment]
Added a few more items to the list

**Comment by 289Adam289** [comment]
I see the list is getting longer. I can also help with polish issues and follow ups from  https://github.com/Expensify/App/pull/49838

**Comment by 289Adam289** [comment]
Regarding

> Clicking on a contextual filter in the search results takes you back to the default filters, rather than adding an extra search query to the existing search results. We need to preserve the current context and just add/update the type/status

https://github.com/Expensify/App/pull/49838 is solving this issue for status contextual filters. The reason type contextual filters reset query to default values is that lists of filters for `type:expense` and `type:chat` are very different. Similar behavior can be observed on github when changing between issues and prs.
If we want to preserve query when changing a type should we remove irrelevant filters (e.g. `merchant` in `type:chat`) or leave it as is.

**Comment by luacmartins** [comment]
I think that's fine for status for now. For type, we might wanna update the API/App to just ignore the irrelevant filters.

**Comment by Kicu** [comment]
Hey I'd be happy to start working on some of these, as for now v2.5 is still being in the planning mode, so I think it's great time to do some polishing.

In addition Search seems like an important part of the App so I would like to also spend a bit of time on pure code refactors (if thats fine with you). Cleaner code should allow for faster iteration of features, and it would be nice to avoid cases similar to `ReportUtils` having 8000+ loc that everyone is afraid of touching 😅 

----

Also this one:
>  CMD + K should close the modal when it's already open

will be fixed as soon as https://github.com/Expensify/App/pull/49984 is merged, as Jakub fixed it.

**Comment by Kicu** [comment]
Another thing I wanted to confirm before actual implementation starts.
About this: 
> Clicking on a contextual filter in the search results takes you back to the default filters, rather than adding an extra search query to the existing search results. 
also this comment by Adam: https://github.com/Expensify/App/issues/50250#issuecomment-2407066804

So originally (a long time ago in a galaxy far far away 😅) we had this design:
<img width="900" src="https://github.com/user-attachments/assets/90231990-07fb-43f0-b7ff-c124311d9ac7">

So we used to have logic where everything on the left side is just a "link" of sorts, so the Chats, Expenses etc and also Saved Searches kinda behave the same way.
And right now we're landing somewhere in the middle:
 - status tabs are next to results and should change the current query (makes sense ✅)
 - Expenses, Chats, etc.. are not next to results but they should also change the current query? 🤔
 - Saved searches will move the user to a fresh query (also makes sense ✅)

Is this what we want to move forward with? Or should we bring back the dedicated type tabs?

CC @luacmartins @JmillsExpensify @shawnborton

**Comment by luacmartins** [comment]
>Is this what we want to move forward with? Or should we bring back the dedicated type tabs?

We're descoping the decidated type tabs from v2.5 and I think for now the plan is to go with the current behavior, i.e. the LHN items navigate you to a brand new search and the status buttons update the status on the current custom search you're viewing. I think we can do nothing on this one for now. @JmillsExpensify for confirmation.

**Comment by 289Adam289** [comment]
> Remove unnecessary accountID lookup 
Regarding this issue I believe accountID lookup is necessary for advanced filters `from` and `to` to work, because they are based on IDs. Current implementation replaces all emails that are present in onyx with IDs so that they appear as selected values in advanced filters and remaining emails are sent to backend unchanged.

We can try to refactor filters `from` and `to` to use emails not IDs that could make removing accountID lookup possible.

**Comment by luacmartins** [comment]
That one is more of a cleanup sine the API can now take emails directly too. I'd prioritize the other issues first (and autocomplete) and maybe we can even descope it

**Comment by luacmartins** [comment]
I couldn't reproduce [BUG: I’m searching in a chat that has messages and getting no results on the search results page when I land there.](https://expensify.slack.com/archives/C06ML6X0W9L/p1728062385571999?thread_ts=1727907702.678009&cid=C06ML6X0W9L) in my tests today. I'll create a separate issue for it.

**Comment by luacmartins** [comment]
PR addressing most of these issues was merged.

**Comment by luacmartins** [comment]
I'll create a separate issue for that and close this one.

**Comment by luacmartins** [comment]
Created issue here - https://github.com/Expensify/App/issues/51964
