### ISSUE TITLE
[HOLD for payment 2024-10-16] Bump react-native-keyboard-controller

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#50253]
Stemming off of https://github.com/Expensify/App/pull/48160, we need to bump react-native-keyboard-controller to make it compatible with bridgeless mode. So let's bump the version first rather than adding a patch and cleaning up later.

**Comment by roryabraham** [comment]
Asked the maintainers if they want to do this: https://expensify.slack.com/archives/C035J5C9FAP/p1728058626405019

**Comment by kirillzyusko** [comment]
Hey, Kiryl from Margelo is here 👋 

I'll handle this!

**Comment by kirillzyusko** [comment]
Opened a PR here: https://github.com/Expensify/App/pull/50325

**Comment by mountiny** [comment]
No need for payment
