### ISSUE TITLE
Web - Mark as Unread - New line marker not shown for visible to you only messages

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50261]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** Negasofonias@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to a chat with visible only to you messages from conceirge or flag one message as offensive
2. Mark the visible only to you message from conceirge as unread
3. Observe that green line and new marker are not shown

## Expected Result:
New line marker should be shown

## Actual Result:
New and green line marker are not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/74458239-a6b6-48a3-afdf-cd79b18c633b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment]
This feels like a very edge case that I'm not sure will be hit almost ever. Closing this out.
