### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Web -Tooltip -Tooltip is not displayed when hovering over the avatar in the main conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50267]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/runs/view/25140&group_by=cases:section_id&group_order=asc&group_id=291936
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the website https://staging.new.expensify.com/
2. Log in
3. Create a task report in a conversation and assign the other user
4. In the conversation history, hover over the assignee avatar

## Expected Result:
A tooltip with the assignee user details should display when hovering over the avatar in both the main conversation and the task details conversation

## Actual Result:
A tooltip with the assignee user details is not displayed when hovering over the avatar in the main conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/68ed5f60-5ee3-49cf-b5da-9ce49d6cad85

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843406645377169271</li>
        <li>Upwork Job ID: 1843406645377169271</li>
        <li>Last Price Increase: 2024-10-07</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104379252</li>
<li>abzokhattab | Contributor | 104379255</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment]
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by francoisl** [comment]
Personally I think it makes sense to always show the tooltip, even for completed tasks. Mostly for consistency.
/cc @johncschuster for a second opinion.

**Comment by johncschuster** [comment]
I agree with @francoisl that we should show the tooltip for consistency.

**Comment by johncschuster** [comment]
Looks like payment is due tomorrow for this one

**Comment by johncschuster** [comment]
Payment Summary:

Contributor: @abzokhattab paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104379255) - PAID! 🎉 
Contributor+: @dukenv0307 paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104379252) - PAID! 🎉
