### ISSUE TITLE
[HOLD for payment 2024-10-25] [$62.50]  Expense - Error message about receipt not verified is not correctly translated into Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5048734
**Email or phone of affected tester (no customers):** applausetester+vd_ios100424@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: user must have set the language preference to Spanish.
1. Go to any chat you can submit an expense (DM or WS)
2. Submit a Scan request, take or upload any photo
3. Before the image is scanned, tap on the expense preview and set any merchant
4. Verify the error message that is now displayed below the receipt image

## Expected Result:
Error message should say "Recibo no verificado. Por favor, confirma su exactitud" or "Recibo no verificado. Por favor, confirma la exactitud"

## Actual Result:
Error message says "Recibo no verificado. Por favor, confirma tu exactitud"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

![buggg2](https://github.com/user-attachments/assets/ffb92e1a-f358-412a-9091-520e8c2d1870)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844119494246133744</li>
        <li>Upwork Job ID: 1844119494246133744</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 104361129</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment]
Opening up for proposal review

**Comment by JmillsExpensify** [comment]
Payment summary: 

 - Contributor: @abzokhattab $62.50
 - Reviewer: @thesahindia $62.50

**Comment by JmillsExpensify** [comment]
@thesahindia please complete the checklist. Closing this one out for now!

**Comment by garrettmknight** [comment]
$62.50 paid for @thesahindia
