### ISSUE TITLE
[$250] Thread - Flagged comments can be only deleted and RBR and close icon misaligned

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50295]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Navigate to a public room as an invited member
3. Send a message and start a thread
4. Send several messages in this thread
5. Wait until the comments get flagged

## Expected Result:
User should be able to edit the flagged comments as it can be done in the public room chat

## Actual Result:
The flagged comment in the thread is grayed out and can not be edited, only deleted unlike a flagged message in the public room. The RBR and the close icon are displayed and misaligned or the error message is missing there.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bded379b-b3c9-479e-8357-b8ae10f7dc6e

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843647187165502776</li>
        <li>Upwork Job ID: 1843647187165502776</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by ChavdaSachin** [comment]
Need steps for reproduction.

**Comment by IuliiaHerets** [comment]
@ChavdaSachin Fixed, sorry for this

**Comment by ChavdaSachin** [comment]
@IuliiaHerets  would comments get flagged by default or user B have to flag it? and if user B have to flag it then what category should comments fagged with to reproduce this?

**Comment by IuliiaHerets** [comment]
@ChavdaSachin Yes, they get flagged automatically, they seem to be spammy.
![image (242)](https://github.com/user-attachments/assets/a7e6ccb8-6f43-4ba9-adee-d04ff1aa898a)
It doesn't happen on the WS chat, only on public rooms.

**Comment by ChavdaSachin** [comment]
anyone able to repro ?

**Comment by mananjadhav** [comment]
I haven't checked recently I'll try this tomorrow.

**Comment by isabelastisser** [comment]
@mananjadhav, can you please share an update? thanks!

**Comment by mananjadhav** [comment]
I made an attempt to reproduce but I couldn't. I am out today but I'll try once more and then may be close it?

@IuliiaHerets can you try and reproduce it at your end?

**Comment by ChavdaSachin** [comment]
Onyx data would be helpful if anyone could reproduce.
Please try to attach `report_<ReportID>` and `reportViolations_<ReportID>` here.

**Comment by IuliiaHerets** [comment]
@mananjadhav Tester can't repro this issue anymore 

https://github.com/user-attachments/assets/fd211135-cc7c-46d9-9913-df113e2ba4b3

**Comment by isabelastisser** [comment]
Thanks for confirming, @IuliiaHerets! Closing.
