### ISSUE TITLE
Invoices - Receipt appears on invoice confirmation page if receipt is added from track expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50303]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoices.
3. Enter amount and select a receiver.
4. Note that there is no receipt option on the confirmation page.
5. Click back button.
6. Click Just track it (don’t submit it).
7. Add a receipt from the 3-dot menu.
8. Click back button.
9. Select a receiver.

## Expected Result:
Receipt will not appear on the invoice confirmation page because invoice does not support receipt (evident from Step 4).

## Actual Result:
Receipt appears on invoice confirmation page if receipt is added from track expense first.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/168c937c-07c0-42e9-b299-eeecd8f24a08
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by IuliiaHerets** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment]
I think we want to put this one in #f1 as it's a bug from there. @grgia, who's working on this with you? I don't think we should show the "just track it" option in the `Send invoice` flow. CC: @anmurali

**Comment by trjExpensify** [comment]
I'll hold off on `Help wanted` for now, as we might want to route this back to whoever is working on that project as a regression.

**Comment by trjExpensify** [comment]
Bumped in thread: https://expensify.slack.com/archives/C07HPDRELLD/p1728580440064929?thread_ts=1728363084.092579&cid=C07HPDRELLD

Doesn't look like @fabioh8010 has access to that channel though, so tagging you here!

**Comment by grgia** [comment]
@fabioh8010 are you able to prioritize this one this week? Thanks!

**Comment by fabioh8010** [comment]
Created a Draft PR -> https://github.com/Expensify/App/pull/50732

**Comment by trjExpensify** [comment]
Excellent! When do you think you can have it in review?

**Comment by fabioh8010** [comment]
I asked for Georgia's feedback in DM but no answer yet, so I think I will just proceed into opening the PR today with screenshots / test videos and tag her again

**Comment by trjExpensify** [comment]
That would be great, thanks!

**Comment by fabioh8010** [comment]
PR was opened to review.
