### ISSUE TITLE
Expense - "has" is spelled as "hase" in "The state of the request hase changed..." message

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50310]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh0410009@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has bank account.
- User has personal bank account.
- Add approvals feature is enabled in Workflows.
- "Auto-pay approved reports" is enabled in Rules.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense below $100.
4. Click Submit.
5. Go offline.
6. Go to expense report.
7. Click Approve.
8. Click Pay elsewhere.
9. Go online.

## Expected Result:
There will be no spelling error in the message "The state of the request hase changed since you started reviewing it"

## Actual Result:
"has" is spelled as "hase" in "The state of the request hase changed since you started reviewing it"

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/84d1ae15-dc78-4439-bda0-97c1ec9fc7c9

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by stephanieelliott** [comment]
This is small, I will fix this myself. Will link the PR when it's ready

**Comment by stephanieelliott** [comment]
https://github.com/Expensify/Web-Expensify/pull/43863

**Comment by stephanieelliott** [comment]
PR was merged, this is fixed
