### ISSUE TITLE
[HOLD for payment 2024-12-03] [Debug Mode] Add transaction and violation data to debug mode

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#50335]
As discussed [here](https://expensify.slack.com/archives/C05LX9D6E07/p1728308030308049), let's add transaction and transaction violation data to debug mode. 

cc @pac-guerreiro 

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by puneetlath** [comment]
@dubielzyk-expensify we shouldn't need you here since this is just for debug mode, but I'll bring you back in if we do.

**Comment by pac-guerreiro** [comment]
I didn't have much time as I wanted to work on this yesterday but here goes my update!

Yesterday's update:
- [x] Create `DebugUtils.validateTransactionDraftProperty`

Todo:

- [ ] Add remaining property validations to `DebugUtils.validateTransactionDraftProperty`
- [ ] Add unit tests for `DebugUtils.validateTransactionDraftProperty`
- [ ] Do some manual tests by modifying transaction data and saving it
- [ ] Finish transaction violations tab
- [ ] Create button in debug report page to redirect to debug transaction page
- [ ] Add screen recordings
- [ ] Add QA testing steps

**Comment by pac-guerreiro** [comment]
Today's update:
- [x] Add remaining property validations to `DebugUtils.validateTransactionDraftProperty`
- [x] Add unit tests for `DebugUtils.validateTransactionDraftProperty`
- [x] Do some manual tests by modifying transaction data and saving it

Todo:
- [ ] Create `TRANSACTION_FORM_INPUT_IDS`
- [ ] Finish transaction violations tab
- [ ] Create button in debug report page to redirect to debug transaction page
- [ ] Add screen recordings
- [ ] Add QA testing steps

**Comment by pac-guerreiro** [comment]
Today's update:
- [x] Create `TRANSACTION_FORM_INPUT_IDS`
- [x] Create button in debug report page to redirect to debug transaction page
- [x] Create button in debug report action page to redirect to debug transaction page
- [x] Create button in debug transaction to redirect to report

Todo:
- [ ] Finish transaction violations tab
- [ ] Add screen recordings
- [ ] Add QA testing steps

**Comment by pac-guerreiro** [comment]
Today's update:
- [x] Add transaction violation creation page

Todo:
- [ ] Fix issue where newly created transaction violation replaces all existing transaction violations
- [ ] Add transaction violation page to allow users to modify data, view JSON data representation and delete data
- [ ] Finish transaction violations tab
- [ ] Add screen recordings
- [ ] Add QA testing steps

**Comment by pac-guerreiro** [comment]
Today's update:
- [x] Fix stale transaction violation data after updating a violation until the app is refreshed
- [x] Refactor debug details constant field options. There are field name collisions between data types

Todo:
- [ ] Add screen recordings
- [ ] Add QA testing steps

**Comment by pac-guerreiro** [comment]
@DylanDylann @puneetlath 

The PR is now ready for review 😄

**Comment by pac-guerreiro** [comment]
@puneetlath 

All feedback from @fabioh8010 was addressed today, just waiting on @DylanDylann to do his review 😄

**Comment by pac-guerreiro** [comment]
@puneetlath 

I fixed the jest unit tests that were failing in the PR

Still waiting on additional review from @DylanDylann 😄

**Comment by puneetlath** [comment]
@DylanDylann can you provide an ETA for when you'll be able to review?

**Comment by pac-guerreiro** [comment]
@puneetlath @DylanDylann @fabioh8010 

Today's update:

- [x] Added missing test cases for `validateConstantEnum` and `validateObject` (thanks for pointing this @fabioh8010 )
- [x] Fixed some expense chats not showing `View Transaction` button in debug panel

**Comment by DylanDylann** [comment]
I am reviewing but the change is so big, I need more time to verify everything. Trying to give some comments on PRs tomorrow

**Comment by pac-guerreiro** [comment]
@puneetlath today I applied @fabioh8010 suggestions to the PR. Once @DylanDylann finishes his review of the PR I'll take care of any new feedback!

**Comment by pac-guerreiro** [comment]
@puneetlath Today I applies most of @DylanDylann suggestions to the PR. There are some issues that I caused today that I'll address tomorrow!

**Comment by pac-guerreiro** [comment]
@puneetlath Today I solved eslint issues, fixed failing tests and addressed an issue reported by @DylanDylann [here](https://github.com/Expensify/App/pull/50745#issuecomment-2445831961)

**Comment by pac-guerreiro** [comment]
@puneetlath 

Sorry for the late update, here's what I did yesterday:

- [x] Add selector for transaction category
- [x] Investigate how much work it takes to make a selector for transaction tags 
- [x] Add selector for transaction tag with only one level

Todo:

- [ ] Modify transaction tag selector to allow editing multi-level tags


Here is a preview of the category and tag pickers in action:

https://github.com/user-attachments/assets/c32e8db6-2876-40de-b4f5-e8bf091841ee

**Comment by pac-guerreiro** [comment]
@puneetlath today I completed my todo list, now I'll wait for @DylanDylann review 😄

**Comment by pac-guerreiro** [comment]
@puneetlath today I fixed the issue reported by @DylanDylann about the currency picker not showing all currencies. There are typescript issues that I'll need to address in order to get the PR ready for your review

**Comment by pac-guerreiro** [comment]
@puneetlath today I focused on resolving the remaining TODO comments about typescript issues. There's still one typescript issue that I need to fix before the PR is ready to be merged.

**Comment by pac-guerreiro** [comment]
@puneetlath all the typescript issues were resolved, you can proceed with your review 😄

**Comment by pac-guerreiro** [comment]
@puneetlath today I addressed all the feedback I got from Dylan and Fabio 😄

**Comment by pac-guerreiro** [comment]
@puneetlath yesterday @DylanDylann approved the PR! 🥳 There are some conflicts that I'll address in a moment 😄

**Comment by pac-guerreiro** [comment]
@puneetlath Just resolved the conflicts 😄

**Comment by pac-guerreiro** [comment]
@puneetlath 

The PR is ready for review again 😄 

Today I resolved conflicts and applied both suggestions from Fabio and you 😄

**Comment by pac-guerreiro** [comment]
@puneetlath 

Today I just resolved conflicts. Just leaving a note here that there might be issues saving data in debug page, which I'll confirm tomorrow.

**Comment by pac-guerreiro** [comment]
@puneetlath 

The PR is ready for your review 😄

**Comment by pac-guerreiro** [comment]
@puneetlath 

I resolved the conflicts, so the PR is ready for your review 😄

**Comment by slafortune** [comment]
Offer sent here https://www.upwork.com/nx/wm/offer/105181367 @DylanDylann

**Comment by DylanDylann** [comment]
Hi @puneetlath,

This issue is ready for payment. However, before proceeding, I’d like to request an increase in the payment amount, possibly by $500. The pull request is quite large (involving 39 changed files). It took considerable time to review and test everything thoroughly.

I’d appreciate hearing your thoughts. Thank you!

**Comment by puneetlath** [comment]
That sounds fair to me.

**Comment by puneetlath** [comment]
I've paid this via milestone on the existing job. Thanks y'all!
