### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] [QBO] There is no option to enter credentials.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50357]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-3 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728292694875429

## Action Performed:
1. Go to Workspace => Accounting.
2. Connect your workspace with QBO.
3. From QBO dashboard, disconnect Expensify App.
4. Go back to ND, click the menu from the Accounting page => Sync now.
5. Notice that's an error shows. Click threedot menu again, notice that you won't see `Enter credentials` option.
## Expected Result:
If there's an authentication error, we should have `Enter credentials` option from three dot menu.

## Actual Result:
There's no `Enter credentials` option even when we have authentication error.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e1b8545f-5e6a-4bc6-ac1e-2c3e16a77fb0

https://github.com/user-attachments/assets/a26ef2bf-daa3-4a1a-8d52-cc8011e6b458

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/user-attachments/assets/82c25848-cb41-45b3-a370-7d451f2a51fe

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844020791272244172</li>
        <li>Upwork Job ID: 1844020791272244172</li>
        <li>Last Price Increase: 2024-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>layacat | Contributor | 104419097</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by hungvu193** [comment]
Hi @dylanexpensify, I reported this issue also have good amount of context since I worked on QBO, Xero and reviewed credentials PR. I'm happy to take this one as C+

**Comment by hungvu193** [comment]
Thanks for the proposals, everyone! It's clear that we shouldn't hide the `Enter credentials` option for both Xero and QBO.
@layacat 's [proposal here](https://github.com/Expensify/App/issues/50357#issuecomment-2398155410) has the correct RCA and straightforward solution.

🎀 👀 🎀  C+ reviewed

**Comment by hungvu193** [comment]
> @hungvu193 @deetergp , can you check the above proposal please, I feel the selected proposal isn't correct and will cause regression, we want to hide the connection for `NETSUITE` and `SAGE_INTACCT` and only show for `Xero` and `QBO`:
> 
> <img width="687" alt="Screenshot 2024-10-11 at 1 11 34 AM" src="https://github.com/user-attachments/assets/8248f920-8393-4060-8ae1-a7c04cac0a54">
> 
> 

That's outdated comment, we need to remove it

**Comment by hungvu193** [comment]
@deetergp can you assign @layacat so he can start working on the PR?

**Comment by bfitzexpensify** [comment]
PR in review

**Comment by bfitzexpensify** [comment]
Thanks @layacat - payment sorted. 

@hungvu193, please complete the BZ checklist and I'll post the summary for the NewDot manual request

**Comment by hungvu193** [comment]
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48918
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/48918/files#r1816794572
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:  N/A
- [x] Determine if we should create a regression test for this bug: Yes

**Regression Test:**
1. Go to Workspace => Accounting.
2. Connect your workspace with QBO.
3. From QBO dashboard, disconnect Expensify App.
4. Go back to ND, click the menu from the Accounting page => Sync now.
5. Notice that's an error is shown. Click threedot menu again.
6. Verify that `Enter credentials` option appears from three dot menu.

Do we 👍 or 👎  ?

**Comment by bfitzexpensify** [comment]
Payment summary: 

@hungvu193 to be paid $250 for C+ work

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
