### ISSUE TITLE
[HOLD for payment 2024-10-17] [HOLD for payment 2024-10-16] Invoices - Balance is cut off when device font size is small

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50374]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/46813
**Email or phone of affected tester (no customers):** applausetester+kh051001@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Device font size should be small (depending on the screen size, might need to adjust font size to the smaller size).

1. Launch New Expensify app.
2. Go to workspace settings.
3. Go to Invoices.

## Expected Result:
The balance will not be cut off.

## Actual Result:
The balance is cut off.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/02f7b321-a954-44be-b888-161113c5e84a

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @stephanieelliott</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-bills

**Comment by mjasikowski** [comment]
Checking

**Comment by mjasikowski** [comment]
https://github.com/Expensify/App/pull/46813 this PR introduces the invoice balance view and is a part of this deployment

**Comment by madmax330** [comment]
@rezkiy37 can you take a look?

**Comment by rezkiy37** [comment]
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by allroundexperts** [comment]
@mjasikowski Can you please assign me this issue since I reviewed the PR? Thanks!

**Comment by mjasikowski** [comment]
@allroundexperts done

**Comment by stephanieelliott** [comment]
Hey @allroundexperts can you complete the BZ checklist when you get a sec?

**Comment by allroundexperts** [comment]
## Checklist
1. https://github.com/Expensify/App/pull/46813
2. The author is aware of this, and fixed the issue himself in this PR.
3. N/A
4. A regression test would be helpful.

## Regression test
1. Set the device font size to be small.
2. Launch New Expensify app.
3. Go to workspace settings.
4. Go to Invoices.

Verify that the balance will not be cut off.

Do we 👍 or 👎 ?

**Comment by mjasikowski** [comment]
@allroundexperts I would change "Verify that the balance will not be cut off." to "verify the balance amount is displayed correctly". Otherwise seems fine.

**Comment by allroundexperts** [comment]
@mjasikowski Updated!

**Comment by stephanieelliott** [comment]
Summarizing payment on this issue: 

 - Contributor: @allroundexperts $250, please request via ND 
 - Contributor+: @mjasikowski no payment due 
 
Regression test issue is here:

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
