### ISSUE TITLE
Composer - Suggestion list is above the composer when typing @ in multiline text

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50373]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh051001@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM.
3. Enter a few lines in the composer.
4. Type @ or :sm

## Expected Result:
The suggestion modal should appear above @ or :sm when the composer has multiline text.

## Actual Result:
The suggestion modal is above the composer instead of above @ or :sm when the composer has multiline text.
On mweb, Android and iOS app, there is big space between the composer and the modal.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3def9670-5ac6-429d-a0b3-620c9a5e60c0

 </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lakchote** [comment]
Found the blocker it's https://github.com/Expensify/App/pull/41071

cc @eVoloshchak @stitesExpensify @dukenv0307

**Comment by garrettmknight** [comment]
@dukenv0307 are you fixing this in a different PR somewhere?
