### ISSUE TITLE
Web - Chat - The size of avatar that is displayed when chat starts, or top of the chat is 108x108

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50385]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49555
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to personal chat and check if icon is of 100x100 size
2. Go to group chat and check if icon is of 100x100 size
3. Go to workspace chat and check if icon is of 100x100 size

## Expected Result:
The icon size for every chat is 100x100

## Actual Result:
The icon size for every chat is 108x108

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6628032_1728371324500!photo_2024-10-08_08-49-20](https://github.com/user-attachments/assets/ec85dd69-c337-4e75-abdf-afc76044dc74)
![Bug6628032_1728371324482!photo_2024-10-08_08-49-15](https://github.com/user-attachments/assets/82682fe7-878e-4b52-9348-4624b9221e14)
![Bug6628032_1728371324494!photo_2024-10-08_08-49-03](https://github.com/user-attachments/assets/1e0e52a1-1865-4071-9cff-22e98ce38d89)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NJ-2020** [comment]
I think this is not a bug because if we inspect go through the svg avatar we can see the size is 100x100, and why when we hover the size of the avatar is showing 108x108, because there's a wrapper div on top of the svg with border-width 4px

**Comment by MariaHCD** [comment]
Thanks, @NJ-2020! Agreed.

The SVG itself is 100 x 100:

![Screenshot 2024-10-08 at 5 42 04 PM](https://github.com/user-attachments/assets/94cb8302-a2a3-46bc-823e-f6a14d754f5e)

But it is nested within a div with a border width of 4px:

![Screenshot 2024-10-08 at 5 44 42 PM](https://github.com/user-attachments/assets/c3fd26ed-4fa6-47c9-aba4-3bf77fdabf36)
