### ISSUE TITLE
[$250] Group chat - Blank name in "This chat is with " when creating group chat with yourself

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50390]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat.
3. Click Add to group next to any user.
4. Click Next.
5. Unselect the user on the confirmation page.
6. Click Start group.

## Expected Result:
The copy at the beginning of the conversation should include the current user.

## Actual Result:
The copy at the beginning of the conversation is "This chat is with " which shows blank name.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7e622e53-de74-42f3-888e-eee89112376e
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843674144504172090</li>
        <li>Upwork Job ID: 1843674144504172090</li>
        <li>Last Price Increase: 2024-10-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by thienlnam** [comment]
Doesn't look like it needs to be a blocker
