### ISSUE TITLE
[$250] Expense Details - Missing header subtitle in expense details

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50396]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+1428@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in using an account that doesn’t have a workspace. (Note: Not having a workspace doesn’t impact the issue, but it helps to maintain consistent steps.)
3. Navigate to self DM and track an expense.
4. Click on "Share it with my accountant" from the whisper.
5. Add a merchant and click Submit.
6. Invite a user.
7. Go offline.
8. Click on the expense preview.

## Expected Result:
A header subtitle should be visible in the expense details.

## Actual Result:
No header subtitle is displayed in the details when offline. However, once coming back online, the header subtitle appears. this behavior is inconsistent, as going through the entire process offline typically results in the header subtitle being visible.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e2e934d7-4ac4-431b-b352-6d17f741aba6

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844738730097344192</li>
        <li>Upwork Job ID: 1844738730097344192</li>
        <li>Last Price Increase: 2024-10-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by IuliiaHerets** [comment]
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by abekkala** [comment]
I do think this is more related to the VIP VSP project which is on hold right now. 
I'm going to close this one out for now
