### ISSUE TITLE
[HOLD for payment 2024-12-12] HelpDot image request for Expensify Classic article for Sage Intacct

### ISSUE THREAD

**Issue by ren-jones** [Expensify/App#50430]
Please provide the following images in light mode and in .png format. Whoever completes this task will need a connection to Sage Intacct. I do not have access to this connection and therefore do not know how accurate or feasible a couple of these requests are. Please let me know if any of the steps below are inaccurate.

CONNECT TO SAGE INTACCT

Link to resource: https://help.expensify.com/articles/expensify-classic/connections/sage-intacct/Connect-To-Sage-Intacct

Images needed:

- Show how to get to Company > Web Services Users > New.
- Show all of the fields completed as follows (all shown in 1 image if possible): 
   - User ID: “xmlgateway_expensify”
   - Last Name and First Name: “Expensify”
   - Email Address: Your shared accounting team email
   - User Type: “Business”
   - Admin Privileges: “Full”
   - Status: “Active”
- Highlight the subscription link for the user. In another image, select the checkbox next to the Application/Module and highlight it. In another image, highlight the Permissions link.
- Show how to get to Company menu > Subscriptions > Time & Expenses. Then in another image, show the toggle switched to subscribe. Then in another image, show the following settings selected (in one image if possible): 
   - Ensure that Expense types is checked.
   - Under Auto-numbering sequences set the following:
   - Expense Report: EXP
   - Employee: EMP
   - Duplicate Numbers: Select “Do not allow creation”
- Continuing with the process from the previous image, click the down arrow on the expense report line and highlight Add. Then in another image, show the following settings: 
   - Sequence ID: EXP
   - Print Title: EXPENSE REPORT
   - Starting Number: 1
   - Next Number: 2
 - Continuing from the previous steps, highlight the Advanced Settings option. Then in another image, show the following:
   - Fixed Number Length: 4
   - Fixed Prefix: EXP
- Continuing from the previous step, under Expense Report approval settings, highlight the Enable expense report approval as being unchecked.
- Show how to navigate to Time & Expenses and click the plus button next to Employees.
- Show how to navigate to Company > Open Setup > Company Setup Checklist > click Import.
- Show how to navigate to Time & Expense, Open Setup, and highlight the plus button next to Expense Types.
- Show how to navigate to Company > Subscriptions > Customization Services.
- In Expensify, go to Settings > Workspaces and highlight the New Workspace button.
- Go to Connections > Sage Intacct > and highlight Connect to Sage Intacct. Then in another image, highlight Select Download Package.
- In Sage Intacct, show how to navigate to Customization Services > Custom Packages > New Package.
- In Sage Intacct, show how to navigate to Platform Services > Custom Packages > New Package.
- Show how to navigate to Company > Company Info > Security. Then in another image, scroll down to Web Services Authorizations and show “expensify” (all lower case) added as a Sender ID.
- In Expensify, go to Settings > Workspaces > [Workspace Name] > Connections > Configure. Click Connect to Sage Intacct and enter the credentials you’ve set for your web services user. Show these completed fields in the image.

CONFIGURE SAGE INTACCT

Link to resource: https://help.expensify.com/articles/expensify-classic/connections/sage-intacct/Configure-Sage-Intacct

Images needed:
- Go to Settings > Workspace > [Workspace name] > Connections and highlight the Configure button next to Sage Intacct.
- In Sage Intacct, show how to navigate to Platform Services > Objects > List. Then in another image, Set “filter by application” to “user-defined dimensions” and highlight it. 

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by maddylewis** [comment]
heya @johncschuster -- assigning you as a liaison for assisting design with getting a few Sage Intacct images for the Exfy Classic. i _think_ you handled the Sage Intacct migration from Community to HelpDot so figured i would assign this one to you to assist. tysm!

**Comment by johncschuster** [comment]
Thanks @maddylewis! Yep! I'll work on this with Danny.

**Comment by dannymcclain** [comment]
Sure thing—and thank you!

**Comment by dannymcclain** [comment]
Not overdue Melv. We've got a plan!

**Comment by johncschuster** [comment]
Notes:
Company Setup Checklist is already complete, or I don't have access to it. I will need to skip that specific screenshot.

**Comment by johncschuster** [comment]
Ok! our Sage Intacct instance is set up to use 	`User Based` permissions, so I followed the flow to connect via User Based permissions and exporting as Expense reports.

**Comment by johncschuster** [comment]
@dannymcclain, I kinda went "ham" and have 45 screenshots for you based on the list above. 

I'm sure we'll need to sort out which ones are the most valuable, but for now, I'll start by just getting them all to you. What's the best method to transfer all of these?

**Comment by johncschuster** [comment]
Awesome! I've just DM'ed you in Slack!

**Comment by dannymcclain** [comment]
Ok wowee. This is fairly confusing 😅. Might take me a minute to make sense of all these screenshots and the images that have been requested.

**Comment by johncschuster** [comment]
Would it be easier to hop on a quick sync! I'm happy to walk through it with you!

**Comment by johncschuster** [comment]
I sent over an invite for tomorrow to chat everything over!

**Comment by dannymcclain** [comment]
Awesome! Here's what I've got so far: https://www.figma.com/design/xDF4dRQIUDzvoc54NOHcnp/Help-Site-Screenshots?node-id=418-8&node-type=canvas&t=3DoB5CcZAaZD4rR7-11

This might be sufficient, or some might be totally wrong haha. If you have time to take a cruise through them before tomorrow it might help us determine if we need to meet/what to talk about when we do. Appreciate your help!

**Comment by johncschuster** [comment]
Notes for me on some verbiage change needs: 

Standardize on "click the plus button" language in any navigation that calls for it

Step 4.1 Verify the navigation in Sage Intacct matches what is called out in the documentation (no screenshot provided)
Step 4.2 for `User Based` > `Expense reports` should be updated to 

> Go to Company > Time & Expense > Types

**Comment by dannymcclain** [comment]
OK! Big shout out to John for helping me wrangle and make sense of all these! I've got two zip files of images to share: one is for the Connect article and one is for the Configure article.

All the images have file names that correspond to what step of the article they're showing/related to.

- [ExpensifyHelp_Sage_Connect.zip](https://github.com/user-attachments/files/17495758/ExpensifyHelp_Sage_Connect.zip)
- [ExpensifyHelp_Sage_Configure.zip](https://github.com/user-attachments/files/17495756/ExpensifyHelp_Sage_Configure.zip)

**Comment by dannymcclain** [comment]
Ok Melvin I feel like this is not overdue. John and I Saged and conquered ☝️

**Comment by johncschuster** [comment]
I just need to upload these. I'll get them done today!

**Comment by johncschuster** [comment]
Ok! My article edits were rolled back so the images could be uploaded in their own PR. I'll get the edits for the articles back up shortly.

**Comment by johncschuster** [comment]
Sorry for the delay on this! My text edits were all rolled back when the images were uploaded.

I will get the alt text updated today

**Comment by johncschuster** [comment]
Finally got the docs _finished_ finished.

**Comment by johncschuster** [comment]
Ah! Neil has a few formatting fixes for me in the PR. I'll work on those this afternoon.

**Comment by johncschuster** [comment]
I couldn't get to the formatting fixes yesterday. I will slot them in this afternoon.

**Comment by johncschuster** [comment]
Ok! I've taken Neil's suggestion on how to fix the formatting. We'll see if that resolves it!

**Comment by johncschuster** [comment]
Ugh, I misunderstood what Neil needed. He needed me to indent _one_ image, and I indented _all_ of the images. I will fix that today.

**Comment by johncschuster** [comment]
Ok! I fixed the mistaken indented images and asked for a re-review.

**Comment by johncschuster** [comment]
Bumped the PR for a re-review

**Comment by johncschuster** [comment]
Waiting on the re-review

**Comment by johncschuster** [comment]
It's merged! Now we're waiting on the deploy 🙌

**Comment by johncschuster** [comment]
Deployed to staging! 🎉

**Comment by johncschuster** [comment]
Waiting on the deploy to prod

**Comment by johncschuster** [comment]
No payment is required for this one. It was reviewed by internal engineers.
