### ISSUE TITLE
[HOLD for payment 2024-10-25] [Direct Feeds] [App] Adding Direct Card Feed: Amex direct feeds

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50449]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes from [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.ylpdnbtelf9n) of the design doc.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.

**Comment by narefyev91** [comment]
WIP for this one

**Comment by narefyev91** [comment]
waiting just this one to be merge to open PR for amex https://github.com/Expensify/App/pull/50602
