### ISSUE TITLE
[HOLD for payment 2024-10-24] [Direct Feeds] [App] Adding Direct Card Feed: Selecting bank step

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50446]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes from [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.hs10n3y37lg) of the doc.

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by joekaufmanexpensify** [comment]
Noting for any BZ assigned later on, @allgandalf is being paid lumpsum for this project. No payment needed here!
