### ISSUE TITLE
[HOLD for payment 2024-10-24] [Direct Feeds] [App] Adding Direct Card Feed: Selecting feed type

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50447]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes from [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.50kq3ucslnab) of the design doc.

**Comment by waterim** [comment]
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by joekaufmanexpensify** [comment]
Noting for any BZ assigned later on, @allgandalf is being paid lumpsum for this project. No payment needed here!

**Comment by waterim** [comment]
Hey, this one will start after 50446 PR is raised
ETA is this week
