### ISSUE TITLE
[Direct Feeds] [App] Adding Direct Card Feed: Bank UI

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50448]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes from [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.iuu6qzvqcak5) of the design doc.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.

**Comment by joekaufmanexpensify** [comment]
Noting for any BZ assigned later on, @allgandalf is being paid lumpsum for this project. No payment needed here!

**Comment by narefyev91** [comment]
@allgandalf WIP here

**Comment by narefyev91** [comment]
> Are we holding on this PR some `BE` changes ?

All UI logic coming in about an hour (preparing videos and PR to move from draft)
UI and movement between screens can be tested. And we can have separate issue to integrated BE when it will be available

**Comment by mountiny** [comment]
Merged, we can close for now

**Comment by mountiny** [comment]
New feature tests will be handled as part of the project
