### ISSUE TITLE
[Direct Feeds] [App] Update existing custom feed flow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50452]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes from [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.qi2t0r8p56hi) of the design doc.

**Comment by joekaufmanexpensify** [comment]
Noting for any BZ assigned later on, @allgandalf is being paid lumpsum for this project. No payment needed here!

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
> We are working on this issue at the last part of the project right?

I guess so, at least we need to [finalize v1 ](https://github.com/Expensify/App/issues/49690)first.

**Comment by VickyStash** [comment]
The PR has been opened for the review: https://github.com/Expensify/App/pull/50972

**Comment by mountiny** [comment]
I think we can close now
