### ISSUE TITLE
[Direct Feeds] [App] Update existing custom feed flow

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50451]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes from [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.p5octy9ltl1j) of the design doc.

**Comment by narefyev91** [comment]
Hi, I'm Nicolay from Callstack - expert agency - and I would like to work on this issue.

**Comment by joekaufmanexpensify** [comment]
Noting for any BZ assigned later on, @allgandalf is being paid lumpsum for this project. No payment needed here!

**Comment by narefyev91** [comment]
Not yet started
