### ISSUE TITLE
[HOLD for payment 2024-11-18] [HOLD for payment 2024-10-17] [Direct Feeds] [Backend] Create and remove beta for direct feeds

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50458]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement the canUseDirectFeeds beta for direct feeds and then clean it up

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by mountiny** [comment]
Not overdue

**Comment by mountiny** [comment]
This can be monthly

**Comment by mountiny** [comment]
not there yet

**Comment by DylanDylann** [comment]
No need checklist

**Comment by mountiny** [comment]
$125 to @DylanDylann for testing

**Comment by mountiny** [comment]
Jus removing the beta so no need for checklist

**Comment by joekaufmanexpensify** [comment]
Will do!

**Comment by DylanDylann** [comment]
I think we can close it and handle payment later

**Comment by DylanDylann** [comment]
I have already noted all polish issues in the third-party workspace feed that I worked on. And we can handle all payments in one after allis  done

**Comment by joekaufmanexpensify** [comment]
Works for me! Closing then
