### ISSUE TITLE
[HOLD for payment 2024-10-24] [Direct Feeds] [App] Broken connection - feed level and Update card sync

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50453]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes from [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=kix.ahfpjlsmfslm) of the design doc.

Also lets not forget to [update the card sync](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.pi11vhkgrwa8).

**Comment by joekaufmanexpensify** [comment]
Noting for any BZ assigned later on, @allgandalf is being paid lumpsum for this project. No payment needed here!

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
**Updates:** I've prepared the [Draft PR](https://github.com/Expensify/App/pull/50587). I just need to think about the test steps and prepare screenshots.

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/50587) has been opened for the review.
