### ISSUE TITLE
[Direct Feeds] [Backend] Update the backend commands with new params required for the direct feeds

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50455]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes described in [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.mm2vdnw5ehc4).

This might be tricky to test for now, I think we need to start with how we think the flow will have to be before we can fully test it with the front-end changes too.

@robertjchen @nkuoch I think this would be great issue for you as you got lots of experience with v1 and the feeds in general

**Comment by dylanexpensify** [comment]
@mountiny assigning you this one for now, feel free to unassign or apply a label to get someone else on it!

**Comment by mountiny** [comment]
Will be worked on this week

**Comment by mountiny** [comment]
Working through the testing clean up

**Comment by mountiny** [comment]
I think we can close this one now, we just cleaning up the flows
