### ISSUE TITLE
[HOLD for payment 2024-10-29] [Direct Feeds] [App] Broken connection violation

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50454]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement changes from [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=kix.f7kvcxc3nd3w) of the design doc.

**Comment by joekaufmanexpensify** [comment]
Noting for any BZ assigned later on, @allgandalf is being paid lumpsum for this project. No payment needed here!

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
I've started to work on the implementation of this one!

**Comment by VickyStash** [comment]
Unfortunately, today, I have been focused on the v1 clean-up issue [PR](https://github.com/Expensify/App/pull/49928). I'll do my best to open a PR for this issue tomorrow!

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/issues/50454) has been opened for the review!
