### ISSUE TITLE
[HOLD for payment 2024-11-01] [Direct Feeds] [Backend] Update the bank ui callbacks

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50457]
This is part of the [Third party workspace feeds V2 (direct connections)](https://github.com/Expensify/Expensify/issues/411687) project.

Implement [this section](https://docs.google.com/document/d/1rWjtZqMd15ACI5OUBTb_Kpd-1bAfrDGcZZU9jcQztUI/edit#bookmark=id.afqk47ry6heg) of the design doc so we ensure the direct feed callbacks handle workspace feeds well.

cc @robertjchen @nkuoch This one would be great for you in case you have some spare cycles given you have context

**Comment by dylanexpensify** [comment]
@mountiny assigning you this one for now, feel free to unassign or apply a label to get someone else on it!

**Comment by mountiny** [comment]
PR is up ready for a review

**Comment by mountiny** [comment]
New feature and we will add regression tests as part of the project

**Comment by mountiny** [comment]
These are done
