### ISSUE TITLE
Hold - Employee is not able to join the thread of deleted request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50461]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+workspaceemployee221@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
1. Login as the owner of the workspace
2. Create a workspace
3. Invite the approver and employee
4. Navigate to more features
5. Enable "workflows"
6. On the "Workflow" editor - enable "Add Approvals"
7. Set the Approver account as the Approver
Steps:
1. As Employee submit 2 manual expenses to the workspace chat
2. As Approver hold the first expense
3. As Approver approve partially report
4. As Employee delete the held report
5. As Employee navigate to the thread of deleted report
6. As Employee click on Join button

## Expected Result:
Employee should be able to Join to the thread

## Actual Result:
Employee is not able to join the thread/Join button reappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/7fa8e4cb-f137-42ff-9a26-4a84a5fdcd65

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment]
Will triage tomorrow morning

**Comment by joekaufmanexpensify** [comment]
Hm, just tested this on macOS and it worked for me. Join button didn't reappear, and I was able to successfully join the deleted expense thread as the employee. 

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/6f74e155-4bb7-483c-8ba9-b8f378f095e0">

**Comment by joekaufmanexpensify** [comment]
Closing for now, as this doesn't appear to be consistently reproducible
