### ISSUE TITLE
Login - Language changes if logging after logging out from account with other language

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50466]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5054477&group_by=cases:section_id&group_order=asc&group_id=229070
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Click on "Settings"
3. Click on "Preferences"
4. Click on "Language"
5. Set the language to "English"
6. Log out from the account
7. Log in to a different account
8. Click on "Settings"
9. Click on "Preferences"
10. Click on "Language"
11. Set the language to "Spanish"
12. Log out from the account
13. Log in again with the first account
14. Verify the language is displayed as it was saved before logging out

## Expected Result:
Language selected, should remain the same everytime the user logs in

## Actual Result:
Language in account is changed if the user logs in after logging out of a different account with a different language setted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/25b54adc-ad7d-4c26-bf1b-4b20259ab45e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment]
Posted in Slack for confirmation

**Comment by OfstadC** [comment]
Closing since this is unlikely flow for a user to encounter
