### ISSUE TITLE
[$250]  Hybrid App - The Duplicate flag on an expense cannot be dismissed, even if there are no duplicates

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50473]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jasonli
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728377645999889

## Action Performed:

1. SmartScan receipt with the same name as a previous duplicate
2. See the red dot in expense
3. Click into expense and edit merchant

## Expected Result:
Duplicate flag disappear
## Actual Result:
See that the duplicate flag remains
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f3f5bdfc-6ec6-4108-b036-d4eb2fbfcff8

https://github.com/user-attachments/assets/2dad2015-0817-4fd8-87cb-93bd32b2782f

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844741371771684057</li>
        <li>Upwork Job ID: 1844741371771684057</li>
        <li>Last Price Increase: 2024-10-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by abekkala** [comment]
@RachCHopkins I'm going ooo until Oct 20. Adding another BZ member until I return, then I can take it back. 

### STATUS: waiting on proposals for fix

**Comment by RachCHopkins** [comment]
Pending proposals.

**Comment by huult** [comment]
This is a backend issue. `transactionViolations_` does not update its values after the`merchant` is updated and remains unchanged even when I set it to [] or null in `optimisticData`.

- <img width="679" alt="Screenshot 2024-10-15 at 13 05 33" src="https://github.com/user-attachments/assets/ffaf72e2-8eb6-407b-9a18-a460f31d6b52">

- <img width="1511" alt="Screenshot 2024-10-15 at 13 02 51" src="https://github.com/user-attachments/assets/2a568c03-68c3-4f26-ab8e-0500355d9ef9">

**Comment by abekkala** [comment]
I'm back from ooo - unassigning @RachCHopkins

**Comment by abekkala** [comment]
@hoangzinh 

> @abekkala could you add an internal label to grab an internal engineer to this issue?

this does not auto-assign an engineer - at this stage if there is not an auto-assigner available. If you're unsure of the BE fix and looking for an internal input you may want to discuss in Slack first. If it's determined that it's an internal BE fix then we can apply the hot pick for an internal engineer to volunteer to pick up.

**Comment by pecanoro** [comment]
@jliexpensify THis is not a bug, it has worked like that since duplicate detection was created years and years ago :smile: Merchant does not signal if an expense is a duplicate. Two expenses are duplicates if they have the same amount, currency and date
