### ISSUE TITLE
[HOLD for payment 2024-12-11] [HOLD for payment 2024-12-07] [$250] mWeb/Chrome - IOU- Continue and green button not working in scan page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50485]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** Negasofonias@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any chat or workspace
2. Click ln + button and select submit expense or split bill
3. In the scan page try clicking continue button or the big green button
4. Observe that both buttons dont work

## Expected Result:
Both buttons should open phones camera

## Actual Result:
Non functional buttons

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/385493cf-12e6-495e-8d8f-3c77381d76b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847268462588592344</li>
        <li>Upwork Job ID: 1847268462588592344</li>
        <li>Last Price Increase: 2024-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Contributor | 104509149</li>
<li>layacat | Contributor | 104696564</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment]
@dylanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by dylanexpensify** [comment]
Reviewing shortly!

**Comment by dylanexpensify** [comment]
apologies, reviewing!

**Comment by dylanexpensify** [comment]
Hey @RachCHopkins! I'm heading out on parental leave so reassigning this! TY! 🙇‍♂️

**Comment by RachCHopkins** [comment]
Sorry @dominictb, I don't think Dylan meant to unassign you as the C+ here.

**Comment by dannymcclain** [comment]
@Julesssss can you weigh in here? I feel like we already put a bunch of effort into solving this?

**Comment by Julesssss** [comment]
Yeah, this is similar to the mWeb location permission issues. Though in this case, it is triggered via a user action (instead of automatically), and it is critically necessary for the flow.

I think the best solution here would be to update the text on button press when permission still hasn't been granted. We show a shortened message explaining how to enable the permission. And the 'continue' button will then remain as it works today. Once they finally enabled permission the button will function without any other changes being necessary.

**Comment by dannymcclain** [comment]
Sounds good to me.

**Comment by Julesssss** [comment]
Great, so I think we should only change the message once. By default the no-permission-granted message says ''Camera access is required to take pictures of receipts'. 

The first time 'Continue' is pressed without permission ON WEB ONLY, we can change the message to something specific. I think ideally we would link to a help site page that explains the full options.

**Comment by RachCHopkins** [comment]
Waiting on updated proposal.

**Comment by Julesssss** [comment]
> Do you think we need to create a dedicated page/note for that in our own help site (e.g., Under SmartScan a receipt section in [this article](https://help.expensify.com/articles/new-expensify/expenses-&-payments/Create-an-expense)). Or just any external article is fine?

Hey yeah, I think a Help Site article would be preferred here.

**Comment by Julesssss** [comment]
Seems like the PR close to being put in review.

**Comment by Julesssss** [comment]
Hey @CherylWalsh 👋 

We're [making changes](https://github.com/Expensify/App/pull/52087#issuecomment-2490784148) to the help site, and the process says to add the Ready For Copy label.  [Here](https://github.com/Expensify/App/pull/52087/files#diff-90735882160c825f676a7fb5b41545eb203f932edfb1c51ac756836b08bd22c2) are the changes if you could please take a look.

**Comment by Julesssss** [comment]
I messaged Cheryl to check if I followed the process correctly.

**Comment by CherylWalsh** [comment]
Looking!

**Comment by CherylWalsh** [comment]
Ok I've reviewed all the copy, that is good to go.

**Comment by Julesssss** [comment]
Thanks @CherylWalsh!

**Comment by Julesssss** [comment]
PR merged

**Comment by Julesssss** [comment]
It would be great if QA re able to merge the above test into our existing location permission tests.

**Comment by RachCHopkins** [comment]
Payment Summary:

- Contributor: @layacat to paid $250 via Upwork
- Contributor+: @dominictb to paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~021847268462588592344)

**Comment by RachCHopkins** [comment]
@layacat your original offer had expired, so I have just sent a [new one](https://www.upwork.com/nx/wm/offer/105267510)!

**Comment by RachCHopkins** [comment]
Contributors have been paid, the contracts have been completed, and the Upwork post has been closed.
