### ISSUE TITLE
Profile - Pronouns and local time are not displayed when clicking on header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50481]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4995348&group_by=cases:section_id&group_id=229064&group_order=asc
**Email or phone of affected tester (no customers):** anastasiiakarpenko.usa+12@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create an account and update avatar, first name, last name, pronouns, time zone
2. Create another account
3. Start the conversation with the first account
4. Tap on "Inbox"
5. Tap on the coversation with the first account
6. Tap on the name or avatar of the recipient

## Expected Result:
The avatar, first name, last name, pronouns, time zone of the recipient are displayed

## Actual Result:
Only avatar, first name, last name of the recipient are displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a61f8155-68cf-4c59-b887-dc8e0cdb12bc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
Working as expected,
we show pronounce row only when user has pronounce set.
And we display user local time row if we have user's timezone and user is validated.

**Comment by Christinadobrzyn** [comment]
Awesome - thanks @ChavdaSachin going to close this then as not needing a fix
