### ISSUE TITLE
[$250] [Crash] Android: SurfaceMountingManager.getViewState

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#50482]
Potentially corresponding reproduction steps: https://github.com/Expensify/App/issues/50463

Looks like this has been happening for some time, creating this issue so we can keep track of it 

com.facebook.react.bridge.RetryableMountingLayerException - Unable to find viewState for tag 1112. Surface stopped: false

[com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_670538A401B000015610788664F8096F_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17298782/com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_670538A401B000015610788664F8096F_DNE_0_v2_stacktrace.txt)
[com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_670538F603E5000135E901B5CB3CC679_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17298783/com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_670538F603E5000135E901B5CB3CC679_DNE_0_v2_stacktrace.txt)
[com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_67053A24023800014E02F8EA97CEAAD4_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17298784/com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_67053A24023800014E02F8EA97CEAAD4_DNE_0_v2_stacktrace.txt)
[com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_670575BC01CD00014CC8B5D670B1D2AF_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17298785/com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_670575BC01CD00014CC8B5D670B1D2AF_DNE_0_v2_stacktrace.txt)
[com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_6705473302F5000179E748FD60E92734_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17298786/com.expensify.chat_issue_4f8a216f0a769e684d009b28ef9bd7d4_crash_session_6705473302F5000179E748FD60E92734_DNE_0_v2_stacktrace.txt)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843746971003676610</li>
        <li>Upwork Job ID: 1843746971003676610</li>
        <li>Last Price Increase: 2024-12-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by CyberAndrii** [comment]
This might be related to https://github.com/software-mansion/react-native-screens/issues/2341 (it has a similar stack trace) but it's hard to reproduce. Are there any additional details such as which page was open?

**Comment by srikarparsi** [comment]
Looking for updates in https://github.com/Expensify/App/issues/50463

**Comment by srikarparsi** [comment]
Yes, going to close this one out and I'll drop a comment in the other issue referencing this.

**Comment by srikarparsi** [comment]
Hey @shubham1206agra, sorry was actually going to close this issue out in favor of https://github.com/Expensify/App/issues/50463 as commented [here](https://github.com/Expensify/App/issues/50482#issuecomment-2501811924). But I did assign you in the other issue.
