### ISSUE TITLE
[$250] Make the user able to select his messages whole text

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#50502]
Currently, when I type several messages one after another, I can't select all of them at once. It only allows me to select messages one by one.

However, when I'm chatting with another user, I'm able to select all their messages in one go.

https://github.com/user-attachments/assets/e9ab45c8-8263-49e2-be94-0efb1fb9d2dc

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844007909858150012</li>
        <li>Upwork Job ID: 1844007909858150012</li>
        <li>Last Price Increase: 2024-10-09</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
Same as https://github.com/Expensify/App/issues/35946

**Comment by lakchote** [comment]
Thanks @bernhardoj, closing the issue then in favor of https://github.com/Expensify/App/issues/35946.
