### ISSUE TITLE
[$250] Status header message does not update after fixing error

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50505]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1728468888344509

## Action Performed:
1. Enable Rule Feature
2. In default, Max expense amount is 2000đ
3. Create a expense with amount greater than the default max amount
4. See an error appear on the transaction thread and the status header message display `Waiting for You to fix the issue(s)`
5. Change amount to fix the error
6. The status header message still display `Waiting for You to fix the issue(s)` even though there are no errors
## Expected Result:
The status header message should display `Waiting for ... to submit an expense`

## Actual Result:
The status header message still display `Waiting for You to fix the issue(s)` even though there are no errors

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2b1b8e1d-66d2-42d6-a901-a11dc2f22263

https://github.com/user-attachments/assets/a004d3cd-6b86-48b0-b75d-d4727e88f12c

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844597729494409862</li>
        <li>Upwork Job ID: 1844597729494409862</li>
        <li>Last Price Increase: 2024-10-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by jacobkim9881** [comment]
Hi. I think "Expected Result" needs to be edited. As you see there is an error("Receipt required over C$25.00") yet after changing amount.
<img width="506" alt="스크린샷 2024-10-10 오후 8 52 47" src="https://github.com/user-attachments/assets/5485b88c-c812-4ff4-b6a0-06696ec9839c">

Maybe "Expected Result" could be : There should not be this error("Receipt required over C$25.00")

**Comment by kadiealexander** [comment]
@jacobkim9881 the second video has no error and the error message still shows.

**Comment by DylanDylann** [comment]
While discovering this bug, I saw that when the request is created with violations, BE returns reportNextStep that requires users to fix errors (that isn't implemented on the optimistic data on FE), but when users update the request to address violations, the BE doesn't update reportNextStep. Thus, I think it should be a BE bug

@rayane-djouah Could I take over this bug from you? Because I have more context on this issue, it would help save your time.

**Comment by DylanDylann** [comment]
Note that, violations isn't handled on the optimistic data, if we create a request with some violations offline, there are no errors is displayed 

<img width="1142" alt="Screenshot 2024-10-11 at 11 50 48" src="https://github.com/user-attachments/assets/c7f9f3f4-3e91-462b-9be6-263a34678342">

**Comment by dangrous** [comment]
Yeah I think we can close this, should be handled once that issue is freed up (waiting on migration of next steps to auth atm)
