### ISSUE TITLE
[High] Hide the Trip Room from NewDot unless you are on the `newDotTravel` beta

### ISSUE THREAD

**Issue by stitesExpensify** [Expensify/App#50534]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**. n/a
**Email or phone of affected tester (no customers):** all users on travel beta
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 n/a
**Expensify/Expensify Issue URL:** n/a
**Issue reported by:** @stitesExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05S5EV2JTX/p1728320141565859

# Problem
We are currently focused on travel for OldDot, and have put all NewDot features on hold. We are also not testing travel on NewDot. For this reason, we want to hide the trip room and any other travel related features behind a beta _except for the main booking flow_. 

The name of the beta is `BETA_NEW_TRAVEL_PROVISIONING = 'newTravelProvisioning';`

## Expected Result:
Users should be able to book a trip via newdot (clicking "book travel" and being brought to Spotnana), but they should not see the trip room or any other travel related features. 

## Workaround:
Users can still use NewDot, it just looks bad and has bugs

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by stitesExpensify** [comment]
@shubham1206agra any interest on doing this one since you have been working on trip rooms already?

**Comment by DylanDylann** [comment]
@shubham1206agra Any update here?

**Comment by DylanDylann** [comment]
@rushatgabhane Any update here?

**Comment by twisterdotcom** [comment]
How do you mean? Like here?
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/aaf3c5da-deee-456f-9ab1-ba20898e5c3f">

If so, no we don't need to. This amalgamtes all trips we scan, not just trips booked via Expensify Travel. It's sort of separate.

**Comment by twisterdotcom** [comment]
How is this going then @rushatgabhane?

**Comment by trjExpensify** [comment]
👋 @stitesExpensify @Gonals @twisterdotcom @rlinoz - can we kill the `newDotSpotnanaTravel` beta so the "Book travel" menu item shows again, now that we're building a new beta here to hide the trip rooms only? 

This will help with some HybridApp development to action on the redirect when they click the Travel tab in OldApp.

**Comment by twisterdotcom** [comment]
>If we show the trip in search, then we can still navigate to the trip room by going up the parent threads.
Is this okay?

I think this should be fine for now.

**Comment by trjExpensify** [comment]
Hm, why is that in Betatify then? 😅 Issue here: https://github.com/Expensify/Expensify/issues/432172

**Comment by rlinoz** [comment]
Ah I see, I think we never implemented it in the App though, from what I can tell we are hiding the button based on `spotnanaTravel` beta, which is the same beta we use for the OldApp

https://github.com/Expensify/App/blob/989542b1b40512763782f83031e575fef685250c/src/libs/Permissions.ts#L23-L25

https://github.com/Expensify/App/blob/f992436a6a85c8fabb699bdad2dece1d0351d4d4/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L448-L454

**Comment by trjExpensify** [comment]
>Ah I see, I think we never implemented it in the App though, from what I can tell we are hiding the button based on spotnanaTravel beta, which is the same beta we use for the OldApp

Jinxxxxxx

**Comment by DylanDylann** [comment]
@rushatgabhane Any update?

**Comment by stitesExpensify** [comment]
Hey @rushatgabhane looks like it's been 2 weeks, can you provide an update please?

**Comment by twisterdotcom** [comment]
I think that makes sense.
