### ISSUE TITLE
Expense - No "&" when the display name is long, name overlaps with time on Android & iOS

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50547]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50341
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Display name is a long email.

1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense.
3. Submit an expense to a user with long email as display name.
4. Go to DM with that user.

## Expected Result:
On web, there will be "&" between the sender and receiver display name.
On Android and iOS app, the name will not overlap with time.

## Actual Result:
On web, there is no "&" between the sender and receiver display name.
On Android and iOS app, the name overlaps with time.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="362" alt="Bug6630080_1728511606916!Screenshot_2024-10-10_at_06 06 31" src="https://github.com/user-attachments/assets/94c2bd5a-adaf-419e-9806-413ee16d0cd1">

https://github.com/user-attachments/assets/0e8bf0a3-b860-4a65-83f9-af9623a34703

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment]
Revert PR was merged https://github.com/Expensify/App/pull/50557 assigning Georgia so you dont loose track of this

**Comment by grgia** [comment]
@Bernhard Owen Josephus would you be interested in working on the rerevert of this PR as you posted solutions for both minor deploy blockers?

**Comment by grgia** [comment]
Closing out since we reverted the PR and I've addressed in a follow up
