### ISSUE TITLE
[HOLD for payment 2024-10-30] QBD - Empty link in RHP when network is disconnected while QBD setup is loading

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50548]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50216
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting.
3. Click Connect next to Quickbooks desktop
4. While RHP is loading, quickly disconnect network.

## Expected Result:
RHP will show that the page is offline.

## Actual Result:
RHP is loaded with empty link.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3d175015-37ae-4536-b6e3-d451353f313b

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by lakchote** [comment]
> The project is still in beta so I don't think it's a DB.

It's not a blocker as it's behind beta indeed.

**Comment by dannymcclain** [comment]
Yeah I agree with not showing a loader forever—that doesn't seem super helpful.

Here are a couple ideas about how to handle this:

#### 1) Replace the link with an offline indicator
If we can automatically update the link box with the link when it's available, this feels like the smoothest option.

![image](https://github.com/user-attachments/assets/74a1e947-4f8b-4432-9084-468a2d0e3526)

#### 2) Blast 'em with our blocking offline pattern
If we _can't_ automatically update the link/we actually need them to just try again once they come back online, this pattern might work best.

![image](https://github.com/user-attachments/assets/f44ab5bf-d664-45c5-9380-8db4ba3c211d)

cc @dubielzyk-expensify for thoughts and preferences.

**Comment by dubielzyk-expensify** [comment]
I think the 2nd idea just for the simplicity and consistency 👍

**Comment by strepanier03** [comment]
I think the 2nd makes it really clear but the 1st one looks more friendly.

**Comment by lakchote** [comment]
Thanks for the proposals @dannymcclain! 

If the user comes back online, we can fetch the setup link again, thus making option #1 viable.

Code will need to be adjusted either way to take into account going offline cc @hoangzinh :

Example for option #1:
```
    const {isOffline} = useNetwork();
    useEffect(() => {
        if (isOffline) {
            setCodatSetupLink('');
            setIsLoading(false);
            return;
        }
        const fetchSetupLink = () => {
             //...existing logic
        };
        fetchSetupLink();
    }, [isOffline]);

```

I'm with @strepanier03, option #1 looks more friendly, but I don't have any hard preference.

If the option #2 is more consistent in terms of what we're doing in our design patterns, let's do #2 as consistency is key.

**Comment by lakchote** [comment]
> @lakchote Given this is an edge case, can I put this issue at the end of the queue and focus on other QBD issues?

Sure!

**Comment by dannymcclain** [comment]
🤔 Hmm, I don't _think_ we do if we already have the link. Obviously the user might run into problems _opening_ the link if they're truly offline, but IMO that's not really on us. Open to other perspectives though!

**Comment by lakchote** [comment]
@ZhenjaHorbach, I agree with @dannymcclain and @hoangzinh.

**Comment by strepanier03** [comment]
@ZhenjaHorbach @hoangzinh - Please complete the checklist. I will send the manual offers now but I won't be able to pay them out until the checklist is complete.

**Comment by strepanier03** [comment]
# HOLD FOR CHECKLIST

### Payment Summary

- [ ] $250 - @hoangzinh via NewDot
- [ ] $250 - @ZhenjaHorbach via Upwork ([offer](https://www.upwork.com/nx/wm/offer/104668952))

**Comment by strepanier03** [comment]
@ZhenjaHorbach - I've paid and closed in Upwork, thanks!

@hoangzinh - the payment summary is [here](https://github.com/Expensify/App/issues/50548#issuecomment-2448249435) feel free to request payment now.

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh

**Comment by kiwiteaorion** [comment]
Contributor details
Your Expensify account email: imamovic.tari@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f52eea1fea1d62da?mp_source=share
