### ISSUE TITLE
Web - Chat - Emoji is displayed in black and white and with random face in chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50576]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5072141&group_by=cases:section_id&group_order=asc&group_id=306201
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website
2. Open any chat
3. Insert ":re" in compose box to trigger the emojis suggestions
4. Select the "Relaxed" emoji
5. Send it to chat
6. Verify the emoji is correctly rendered in chat

## Expected Result:
Emoji should be displayed in chat, the same way it is seen in emoji picker and compose box

## Actual Result:
The "Relaxed" emoji is correctly displayed in emoji picker, compose box and LHN, but it´s seen in chat in black and white and with a random face

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/2cb74e3d-09b7-44c8-a3d9-105dc0441b88

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
I'm not able to reproduce this. Seems like it's likely a local issue. Going to close but feel free to comment or reopen if you disagree. 

<img width="346" alt="image" src="https://github.com/user-attachments/assets/5a53586e-8fae-48e2-bb64-c636c31b13a3">

**Comment by vincdargento** [comment]
@puneetlath A tester was able to reproduce this issue on a Redmi Note 10S/Android 13 device. Opening in case you want to take a look at it

https://github.com/user-attachments/assets/56b222b9-047c-4cec-b78c-c5c3ce463700

**Comment by puneetlath** [comment]
Thanks for letting me know. If it's just for that device, that feels pretty niche, and I think we should ignore for now.
