### ISSUE TITLE
Connection complete page can be accessed via the URL

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50574]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50071
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/connection-complete
in web

## Expected Result:
Connection complete page should not be accessed via the URL

## Actual Result:
Connection complete page can be accessed via the URL

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6630578_1728555605127!photo_2024-10-10_13-15-50](https://github.com/user-attachments/assets/71395774-6970-4002-a5aa-7e56132e7d7a)
![Bug6630578_1728555605149!image](https://github.com/user-attachments/assets/e7056efa-89d3-4a85-a06c-748290c36e58)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by OfstadC** [comment]
Thanks @ChavdaSachin !
