### ISSUE TITLE
Fix the Join button on the sign up screen

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#50590]
The Join button looks off in this screen when signing up on mobile web:
1. Go to [Expensify.com](http://expensify.com/) on mobile web
2. Input your email > Click Get Started
3. You see the above which looks off. 

I've attached a screenshot and video. @dubielzyk-expensify will suggest a fix, and then we'll ask a contributor to fix it. Jon, can you put in the updated mock and details? 

![image](https://github.com/user-attachments/assets/8e5a743b-b6ec-493a-a0b3-499fa16d88a0)

https://github.com/user-attachments/assets/710e20ec-ea02-42db-870a-4041291a9fa3

**Comment by dubielzyk-expensify** [comment]
The design fix should be as follows:
- Make sure the button is 20px from the edge (which it is in most cases of the flow, but not when the button says "Join")
- Have the button have a min-width of 88px

This should give us something like this:

![www expensify com_(iPhone 15 Pro)](https://github.com/user-attachments/assets/0950ee9f-84c0-4dac-805b-a9e1cdea5ca8)
![www expensify com_(Screenshot (Desktop))](https://github.com/user-attachments/assets/589f87b3-06b0-42c3-a267-a168377188b0)


Also be aware that this should only apply to this sign in flow and not all buttons. cc @Expensify/design

**Comment by dubielzyk-expensify** [comment]
@Expensify/design would love your thoughts on this one

**Comment by carlosmiceli** [comment]
Sure thing, I'll assign myself this one.

**Comment by anmurali** [comment]
https://github.com/Expensify/Web-Expensify/pull/44040 is on production. Do we just need to manually close this as done? @carlosmiceli
