### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Update second `Allow location access` modal on web

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#50601]
On **web only**, for the **second `Allow location access` modal only** (the one with the `Got it` button):
- [ ] Fix the bug where you can't submit after clicking `Got it` (see video below)
- [ ] Fix the bug where, after clicking the `Got it` button, the same button quickly flickers to say `Continue` (same video below)
- [ ] Update the copy on the modal slightly to:
> **Allow location access**
> Location access helps us keep your timezone and currency accurate wherever you go. Please allow location access from your device's permission settings.
- [ ] Remove the `Not now` button entirely because it serves no purpose in this case

https://github.com/user-attachments/assets/c9dd15b2-ab3b-46c9-ae86-7d5c43d00bd5

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847227311681373401</li>
        <li>Upwork Job ID: 1847227311681373401</li>
        <li>Last Price Increase: 2024-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 104624114</li>
<li>truph01 | Contributor | 104624115</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by truph01** [comment]
@jamesdeanexpensify We don't want to display the pre-prompt but still display the native prompt on web, no?

**Comment by truph01** [comment]
@jamesdeanexpensify @Julesssss IMO, In my opinion, I don’t think we can fully hide the modal

Previously, when the user clicked the submit button and the native prompt hadn’t been shown yet, we displayed the pre-prompt modal:

![image](https://github.com/user-attachments/assets/44fee5bb-a158-4ff1-92c9-2fc926824ff6)


If the user chose 'Continue,' but location permission wasn’t granted, the native prompt wouldn’t appear in the future. That's why, the next time, we display a modal to inform them that they need to manually enable location permission:

![image](https://github.com/user-attachments/assets/f79bbf01-e252-4ba9-bca5-f0d4b694e6ac)


So, the 2nd modal should not be hidden.

**Comment by Christinadobrzyn** [comment]
Thanks for the feedback @truph01! 

Sorry, just catching up here, can you confirm the difference you are proposing? I think it's that we only show the "Not Now"/"Got it" prompt on the web and not the pre-prompt? Is that right?

**Comment by truph01** [comment]
> I think it's that we only show the "Not Now"/"Got it" prompt on the web and not the pre-prompt

Yes

**Comment by Christinadobrzyn** [comment]
I think this makes sense - do you @Julesssss @jamesdeanexpensify? Do you think we need a consensus from the team about this?

**Comment by Julesssss** [comment]
That seems to be what we agreed, but lets check in with James first.

**Comment by jamesdeanexpensify** [comment]
We're discussing this one internally and may recommend an alternative course of action. Stay tuned!

**Comment by jamesdeanexpensify** [comment]
Just for alignment purposes - by "native prompt" on web, are we all talking about the second screenshot [here](https://github.com/Expensify/App/issues/50601#issuecomment-2408219295)?

**Comment by jamesdeanexpensify** [comment]
OK, here's where we're landing cc @Christinadobrzyn @Julesssss...

I actually think on **web** we can probably leave these prompts entirely in place, but (again, on **web** only):

- [ ] Change the modal copy to add more detailed instructions:

>   **Allow location access**
>   Location access helps us keep your timezone and currency accurate wherever you go. Please allow location access in your device's permission settings.

- [ ] Assuming there's not really a difference on web between what happens when you click `Got it` vs. `Not now` - just use one button (`Got it`)
- [ ] Fix the bug that affects the `Got it` button on web so it lets you submit your expense (it should just be an acknowledgment button, nothing more). Here's the bug: 

https://github.com/user-attachments/assets/19ff5542-ed0f-4af5-9a3d-d44c7f8f2220

**Comment by jamesdeanexpensify** [comment]
Hmmm...that video is working for me. Here it is again:

https://github.com/user-attachments/assets/8de2df93-6455-4663-aec6-ed29212f6e17

And sorry, what do you mean by "only show the prompt on native devices"?

**Comment by truph01** [comment]
> Just for alignment purposes - by "native prompt" on web, are we all talking about the second screenshot https://github.com/Expensify/App/issues/50601#issuecomment-2408219295?

- When users sign-in on a new device and are not asked about the location permission before. If they create a scan expense, the modal below is displayed, it is "pre-prompt":

![Screenshot 2024-10-17 at 06 34 00](https://github.com/user-attachments/assets/a427f341-9f20-4ffb-ba9e-3ee364dad7d2)


- If the user chooses "Continue", the modal below is displayed (in top left screen), it is "native prompt":

![Screenshot 2024-10-17 at 06 31 15](https://github.com/user-attachments/assets/b454d036-e8ff-4a73-b9f0-83b352edae11)


- If the user chooses "Block", and then creates an other expense, the modal below is displayed:

![Screenshot 2024-10-17 at 06 34 00](https://github.com/user-attachments/assets/a15ed756-d0d5-4925-af82-887e779cb5b2)



- If the user chooses "Got it", the modal will close.

**Comment by jamesdeanexpensify** [comment]
Ah, that's super helpful! Bringing this back to the team to chat about next steps again. Thanks!

**Comment by jamesdeanexpensify** [comment]
OK, here is where we landed:

On **web only**, for the **second `Allow location access` modal only** (the one with the `Got it` button):
- [ ] Fix the bug where you can't submit after clicking `Got it` (see video below)
- [ ] Fix the bug where, after clicking the `Got it` button, the same button quickly flickers to say `Continue` (same video below)
- [ ] Update the copy on the modal slightly to:
> **Allow location access**
> Location access helps us keep your timezone and currency accurate wherever you go. Please allow location access from your device's permission settings.
- [ ] Remove the `Not now` button entirely because it serves no purpose in this case


https://github.com/user-attachments/assets/db337e01-db1d-40e3-b7e9-3c74b2776ede

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/50601#issuecomment-2406343329)

**Comment by jamesdeanexpensify** [comment]
Can you explain a bit more what you mean by [that](https://github.com/Expensify/App/issues/50601#issuecomment-2420238123)? Just want to make sure I'm understanding, thanks! I'm not a BZ person so it's helpful.

**Comment by jamesdeanexpensify** [comment]
@Christinadobrzyn @Julesssss it looks like we have two proposals ([here](https://github.com/Expensify/App/issues/50601#issuecomment-2408009859) and [here](https://github.com/Expensify/App/issues/50601#issuecomment-2406343329)) to review, and I've updated the tasks in the OP up top!  Quick note - we're not removing any modals now, only adjusting an existing one.

**Comment by Julesssss** [comment]
> @jamesdeanexpensify so by only web we mean that there should be no change to the behaviour on native platforms right ?

Yeah, just web will change.

**Comment by Christinadobrzyn** [comment]
@alitoshmatov can you please check out the proposals when you have a moment? TY!

**Comment by Julesssss** [comment]
Hi @alitoshmatov, are you able to review?

**Comment by alitoshmatov** [comment]
@truph01 Thank you for your proposal, your RCA is correct and your alternative solution is solving the issue.

**Comment by alitoshmatov** [comment]
@twilight2294 Thank you for your proposal, I don't think your solution is complete and covers all cases here.

**Comment by alitoshmatov** [comment]
We can go with @truph01 's alternative proposal [here](https://github.com/Expensify/App/issues/50601#issuecomment-2406343329)

C+ reviewed 🎀 👀 🎀

**Comment by Julesssss** [comment]
I agree, thanks everyone for your patience.

**Comment by truph01** [comment]
[PR](https://github.com/Expensify/App/pull/51709) is ready

**Comment by truph01** [comment]
@jamesdeanexpensify Can you give me a translation for the text "Location access helps us keep your timezone and currency accurate wherever you go. Please allow location access from your device's permission settings."?

**Comment by Julesssss** [comment]
Hi @truph01 I have [requested](https://expensify.slack.com/archives/C21FRDWCV/p1730459284524759) a translation and will get back to you soon

**Comment by jamesdeanexpensify** [comment]
Thanks @Julesssss ! Saw they got back with this approved translation @truph01

> El acceso a la ubicación nos ayuda a mantener tu zona horaria y moneda precisas dondequiera que estés. Por favor, permite el acceso a la ubicación en la configuración de permisos de tu dispositivo.

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/51709

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/51709

**Comment by Christinadobrzyn** [comment]
monitoring PR - https://github.com/Expensify/App/pull/51709

**Comment by Christinadobrzyn** [comment]
sorry @alitoshmatov can you update the images above so they are visible? I can't seem to access them.

**Comment by alitoshmatov** [comment]
@Christinadobrzyn Can you recheck it

**Comment by Christinadobrzyn** [comment]
Just checking @alitoshmatov - can you review ^. The `Allow Location` popup is no longer showing, is that expected?

**Comment by alitoshmatov** [comment]
@Christinadobrzyn You have to upload a receipt not create a distance expanse

**Comment by alitoshmatov** [comment]
Also there is this point to consider: 

> NOTE: This test steps are from PR, we have 7 days cooldown for asking location permission in PR we disabled this via code to test, not sure how this condition should be handled here

**Comment by Christinadobrzyn** [comment]
@alitoshmatov sorry can you provide more context on [that point](https://github.com/Expensify/App/issues/50601#issuecomment-2517906349), as in, do you think we should discuss changing something with the team related to that cooldown period or are you just thinking how that should be documented in the regression test?

**Comment by alitoshmatov** [comment]
@Christinadobrzyn I think you can change computer/phone's time manually on the settings to bypass 7 day cooldown. Just checked it and it works.

Updated QA to show when they should change device's time with  _Forward time in settings_ step. 
Feel free to update testing steps to be more explanatory

**Comment by JmillsExpensify** [comment]
Awaiting payment summary
