### ISSUE TITLE
[Supportal] Clicking New Expensify in Supportal loads login page instead 

### ISSUE THREAD

**Issue by stephanieelliott** [Expensify/App#50628]
**Version Number:**
**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** Stephtestuser1@expensicorp.com
**Logs:** [8d0d0580f9e2c423-HNL](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228d0d0580f9e2c423-HNL%22)+AND+timestamp:[2024-10-11T06:08:53.379Z+TO+2024-10-11T08:08:53.379Z]&index=logs_expensify-030667)
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @stephanieelliott 
**Slack conversation:** 

## Action Performed:
1. Support log into a customer account 
2. Click New Expensify
3. see login page load instead of Supportal 

## Expected Result:
New Expensify Supportal should load when clicked (as you are already logged in)

## Actual Result:
Login page loads. Logs show: 

`[OOPS!] Oops... something went wrong and your request could not be completed. This might happen if you’ve changed your password or signed into a different account recently. Please try returning to your Expenses page or sign out here before trying again. If this issue persists, please reach out to us at`

## Workaround:
Navigate back to Supportal > click New Expensify Support again

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3edea22c-2a6b-4a01-a144-c14d4ba68698

**Comment by dylanexpensify** [comment]
Tackling this evening!

**Comment by dylanexpensify** [comment]
Hey @Christinadobrzyn! I'm heading out on parental leave so reassigning this! TY! 🙇‍♂️

**Comment by Christinadobrzyn** [comment]
Have been affected by this too. I'm not sure where we report these Supportal bugs - asking in BZ room

**Comment by Christinadobrzyn** [comment]
Tested on a few user accounts: 

- [corey.printup@purplerac.com](mailto:corey.printup@purplerac.com)
- [stephanie@veda.tech](mailto:stephanie@veda.tech)
- vincent.hughes@generateupcycle.com
- c.dobrzyn@expensify.com

With some of the above accounts, NewDot loads without an issue and other times it 500 errors and directs to the login page after a reload. 

![2024-10-23_10-42-49 (2)](https://github.com/user-attachments/assets/71e6c29d-f7e8-43e4-afca-6e410b0b4156)

**Comment by Christinadobrzyn** [comment]
Posted for a volunteer - https://expensify.slack.com/archives/C07NZ8B1VTQ/p1729651828061979

**Comment by Christinadobrzyn** [comment]
This is a more accurate example of what I normally see when hitting the login page. 

- I'll supportal from the chat > click New Expensify
- Go to the login page > refresh & remain on the login page
- In the video I even signed into my own ND account to make sure I was signed into ND somewhere (I just started concierge chat support for the day)
- I usually can't get beyond the login page. 
- Logs of chat wth mburkart@meriwetherco.com 
[8d3c0c80ddb82ea1-MEL](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228d3c0c80ddb82ea1-MEL%22)+AND+timestamp:[2024-10-16T23:07:31.524Z+TO+2024-10-17T01:07:31.524Z]&index=logs_expensify-030751)

![2024-10-24_08-35-16 (3)](https://github.com/user-attachments/assets/f8dfbcde-0eac-46db-8dc3-19588c7c21d8)

**Comment by Christinadobrzyn** [comment]
looking for a volunteer - https://expensify.slack.com/archives/C07NZ8B1VTQ/p1729839971462369?thread_ts=1729651828.061979&cid=C07NZ8B1VTQ

**Comment by Christinadobrzyn** [comment]
monitoring - https://expensify.slack.com/archives/C07NZ8B1VTQ/p1729839971462369?thread_ts=1729651828.061979&cid=C07NZ8B1VTQ

**Comment by Christinadobrzyn** [comment]
@iwiznia would you be able to increase the throttle based on our Slack discussion? https://expensify.slack.com/archives/C041MSTR8J1/p1729736739416729?thread_ts=1726227409.896439&cid=C041MSTR8J1

**Comment by iwiznia** [comment]
We can but not sure what throttle we need to update. What's the flow exactly? Looking at the video I don't see any throttle message or anything indicating that throttling is what's causing this

**Comment by Christinadobrzyn** [comment]
Ah yes, there's nothing in this issue indicating it relates to the 500 throttle error. 

However, I was thinking we could try increasing the throttle to solve this [500 error](https://expensify.slack.com/archives/C041MSTR8J1/p1726229780112799?thread_ts=1726227409.896439&cid=C041MSTR8J1) to see if that also helps with this issue? 

> What's the flow exactly? 

Flow is: 

- Get a customer chat
- Click Supportal > new tab opens with customer's Supportal dashboard
- Click New Expensify > new tab opens for New Expensify 
- Login page loads - it's not possible to get beyond the login page
- refreshing the browser doesn't help

[Logs here](https://github.com/Expensify/App/issues/50628#issuecomment-2433970961)

**Comment by iwiznia** [comment]
Code is [here](https://github.com/Expensify/Auth/blob/386c9190f701e542914ec67de27cb3c0a8c8dedb/auth/Auth.cpp#L473-L474) so allegedly you only get throttled if you try to support login more than once in 30s, which sounds quite reasonable to me. I wonder if something is calling it twice in that flow.

**Comment by iwiznia** [comment]
Indeed, when clicking on supportal, we call `GetSupportAuthToken` (see requestID 8dae058feab39c0e-EZE) and when clicking `New Expensify` we call it again (see requestID 8dae060c897f9c0e-EZE)

**Comment by iwiznia** [comment]
And I think opening newDot calls it even once more (see requestID 8dae1918fd0b9c0e-EZE)

**Comment by Christinadobrzyn** [comment]
Ah thank you @iwiznia - can I assign this issue to you or should I reach out to the team for a volunteer? Let me know what's best for you!

**Comment by Christinadobrzyn** [comment]
Thank you so much @iwiznia!

**Comment by Christinadobrzyn** [comment]
monitoring PR https://github.com/Expensify/Auth/pull/12986

**Comment by Christinadobrzyn** [comment]
Thanks for creating that PR, @iwiznia. Unfortunately, it looks like the login page is still showing. I'm sorry to have you spend your time on the throttle when you said that will probably not resolve this issue - to note, it has made the sign in process better. 

Testing this issue again: 

Problem: The login page shows on the first attempt to Supportal into New Expensify. 

• Example: accountant.aserna@expensicorp.com
• [Logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228dda4783bfa18652-PER%22)+AND+timestamp:[2024-11-05T04:00:18.000Z+TO+2024-11-05T06:00:18.000Z]&index=logs_expensify-031055) of my Supportal attempt

• Video
 
![2024-11-05_12-59-29 (3)](https://github.com/user-attachments/assets/6e8cc788-61de-4027-bf16-924ffe9739a6)


Nothing stands out in the logs, do you think it's something to do with the Open New Socket step in the Supportal process? 

<img width="1696" alt="image" src="https://github.com/user-attachments/assets/d79dd568-6874-47da-a37a-5350acdafe19">

**Comment by iwiznia** [comment]
> do you think it's something to do with the Open New Socket step in the Supportal process?

No, that has nothing to do and happens on all requests that talk to auth

**Comment by iwiznia** [comment]
Pasting the same question I made in slack:
> So it briefly shows the login page then redirects and all works correctly?

**Comment by Christinadobrzyn** [comment]
> So it briefly shows the login page then redirects and all works correctly?

Yes, the login page shows briefly and then it redirects to the customer's New Expensify page

**Comment by Christinadobrzyn** [comment]
Based on the Slack convo - we're going to consider this resolved since it's working better and the login page is an internal flow only. Closing.
