### ISSUE TITLE
[HOLD for payment 2024-10-29] [$62.50] Android - Chat search - Unable to reach the bottom of chat list when scrolling down

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50649]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Send many messages (so that the All list in Search > Chat is scrollable)
4. Go to Search > Chat
5. Scroll down the list in All tab

## Expected Result:
The bottom of the chat list can be reached

## Actual Result:
User is unable to reach the bottom of chat list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/e1f1e088-8106-4fbe-9757-97809b9536a5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844817953624508019</li>
        <li>Upwork Job ID: 1844817953624508019</li>
        <li>Last Price Increase: 2024-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 104433861</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by lanitochka17** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
Reproduced. A very minor issue, but an issue nonetheless. I think we can fix this, but should be lower budget, as is very minor change.

**Comment by marcochavezf** [comment]
Thanks for the review @mkhutornyi, assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment]
PR is ready
cc: @mkhutornyi

**Comment by joekaufmanexpensify** [comment]
PR out on staging

**Comment by joekaufmanexpensify** [comment]
@mkhutornyi could you complete BZ here so we can prep for payment?

**Comment by joekaufmanexpensify** [comment]
Agreed. Skipping regression test makes sense to me here. TY for completing checklist!

**Comment by joekaufmanexpensify** [comment]
All set to issue payment here. We need to pay: 

- @bernhardoj - $62.50 for PR via NewDot. 
- @mkhutornyi - $62.50 for C+ via Upwork.

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by joekaufmanexpensify** [comment]
TY!

**Comment by joekaufmanexpensify** [comment]
@mkhutornyi $62.50 sent and contract ended

**Comment by JmillsExpensify** [comment]
$62.50 approved for @bernhardoj
