### ISSUE TITLE
Expense - Not here page opens instead of loading report when opening expense thread offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50642]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a few expenses
4. Send a message in another chat (important)
5. Log out and log in
6. Go offline
7. Go to workspace chat
8. Click on the expense perview
9. Click on any expense preview

## Expected Result:
Report will show skeleton loading and load when returning online

## Actual Result:
Not here page opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/ad9198b4-6030-44bf-a628-c99866680942

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by huult** [comment]
This is a backend issue. I called `OpenApp` without including `childReportID` in the `ReportAction`.
- <img width="1512" alt="Screenshot 2024-10-12 at 00 21 19" src="https://github.com/user-attachments/assets/f6dac166-d581-4dbf-a102-27e6040d6f21">

**Comment by stephanieelliott** [comment]
I think this is edge case -- submit expense > log out/in > go offline > try to view expense is not a series of actions a real user is going to take on purpose. Gonna close this for now
