### ISSUE TITLE
[Awaiting Payment] [$250] Distance - Tax amount shows value A then changes to value B after changing distance rate

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50641]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh081007@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Track tax is enabled
- Workspace has at least two distance rates that have tax rate and tax reclaimable on.
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit a distance expense
4. Go to transaction thread
5. Click Rate
6. Select another distance rate that has tax rate and tax reclaimable on

## Expected Result:
Tax amount will be consistent after changing distance rate

## Actual Result:
Tax amount shows value A then changes to value B after changing distance rate

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/426fdafd-7deb-45d8-8d69-f468e0b3612f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844824122118463977</li>
        <li>Upwork Job ID: 1844824122118463977</li>
        <li>Last Price Increase: 2024-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104444772</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by lanitochka17** [comment]
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment]
@neil-marcellini Can you please confirm it's bug or not since you worked on distance request? Thanks!

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Tax amount shows value A then changes to value B after changing distance rate

### What is the root cause of that problem?
We are using the long (`kilometer` for `km`) unit version to getDistanceInMeters which expects the short form
https://github.com/FitseTLT/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L96
### What changes do you think we should make in order to solve the problem?

We should separately define the unitToDisplay here
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L86
```
 const unit = Object.values(rates).at(0)?.unit;
    const unitToDisplay = (unit === CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES ? translate('common.mile') : translate('common.kilometer')) as Unit;

```
Then use it here
https://github.com/Expensify/App/blob/8ff185a05937366c40898f8ab6510fbd765a8838/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L121
```
            <Text style={[styles.mh5, styles.mv4]}>{translate('iou.chooseARate', {unit: unitToDisplay})}</Text>

```
### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment]
> @neil-marcellini Can you please confirm it's bug or not since you worked on distance request? Thanks!
The tax amount should change based the rate change, but it looks like it's calculating it incorrectly, then correcting, instead of calculating the correct rate immediately.

**Comment by garrettmknight** [comment]
Thanks for the update, I'll pay 50% for getting the PR up.

**Payment summary:**
- Contributor: @FitseTLT $125 paid via Upwork.

**Comment by FitseTLT** [comment]
> Hi, @garrettmknight, curious, is there any compensation for C+ in this case? 😂

Yes I think the rule in this case 100% for the contributor and 50% for C+ for reviewing the proposal

> If a contributor has been hired for a job and we decide to close the job before it is successfully completed, full payment is due for the hired contributor. If the C+ only reviewed proposals and not a PR, they are eligible for 50%. If they started reviewing a PR it's 100%. One caveat here might be if the hired contributor wasn't working on their PR with urgency.

@garrettmknight read https://github.com/Expensify/App/issues/47712#issuecomment-2378954389 for context

**Comment by garrettmknight** [comment]
Thanks for citing that - I've just paid the other 50% to @FitseTLT.

@ntdiary did you review the PR beyond asking to resolve the conflicts? Trying to figure out if we should be paying 50% or 100%.

**Comment by garrettmknight** [comment]
Sounds good, updated the payment summary.

**Comment by garrettmknight** [comment]
Please request when you're ready.

**Comment by JmillsExpensify** [comment]
$250 approved for @ntdiary
