### ISSUE TITLE
[$250]  Tasks- Anon user can not navigate to a room without logging in first

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50657]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4995713&group_by=tests:id&group_order=asc&group_id=-1
**Email or phone of affected tester (no customers):** Negasofonias@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in as a workspace admin
2. Navigate to a public #room (Create one if needed)
3. Create a task without assignee
4. Copy the share link of the public #room
5. Log out of the workspace admin
Steps
6. As an anon user, navigate to the share link
7. Observe that when navigating to the link user is first taken to a login page

## Expected Result:
anon User should have accessed the tas in public room

## Actual Result:
anon user is first navigated to login oage when opening shared link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/00a1bc79-b943-43cd-bec4-9a7a8023079f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845882404200071767</li>
        <li>Upwork Job ID: 1845882404200071767</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
Based on responses received it looks like BE issue.

**Comment by flodnv** [comment]
I just got another NewDotQuality issue assigned (https://github.com/Expensify/App/issues/51049), so I am unassigning myself.

**Comment by John0486** [comment]
I am a full stack developer with rich experience but a freshman on github/expensify.
I hope we work together and you teach me
