### ISSUE TITLE
Update react-native-vision-camera to the latest version

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#50650]
We are using quite an outdated version of react-native-vision-camera in expensify. There are two patches to make it work with the new arch, however none of these patches have been forwarded upstream yet.

We are using `4.0.0-beta.13`, latest is `4.5.3`

The latest version of react-native-vision-camera has lots of performance and stability improvements. Plus we have additional maintenance overhead due to the patches (and we are about to add a third one [here](https://github.com/Expensify/App/pull/48160))

<details><summary>Issue Owner</summary>Current Issue Owner: @hannojg</details>

**Comment by hannojg** [comment]
cc @mountiny Is that something that we can work on?

**Comment by mountiny** [comment]
@hannojg yeah lets do that, can we remove all the patches (merge the fixes upstream) as part of that?

**Comment by hannojg** [comment]
Yes, thats the goal!

**Comment by mountiny** [comment]
@hannojg can you breakdown the next steps here and what is the eta for them? Would someone else from Margelo work on it?

**Comment by hannojg** [comment]
We've already started working on that one. As we have to consider new arch & old arch support, it might take moment longer (its not just applying the patches we have in expensify, but making sure its compatible for all arch types).

Main work is happening here:

- https://github.com/mrousavy/react-native-vision-camera/pull/3244

There are a few other PRs however that will be needed:

- https://github.com/mrousavy/react-native-vision-camera/pull/3240
- https://github.com/mrousavy/react-native-vision-camera/pull/3243

My ETA would be end of this week!

**Comment by mountiny** [comment]
Ok thanks!

**Comment by hannojg** [comment]
Short status update:

- I have prepared the vision camera repo to be prepared for the upgrade (example app latest RN version, proper mono repo setup > otherwise we would get build errors later on when turning on new arch)
- Working on the Fabric ComponentView

I currently ran into a bug with react-native-codegen, where it generates broken code (it must be a `,` instead of `.`):

![Screenshot 2024-10-17 at 18 03 45](https://github.com/user-attachments/assets/3f66b06f-9b4c-4073-b588-921b0de67e4e)

For expensify this wasn't happening with the current patch as the codegen spec sued in the patch is slightly incorrect.
I either have to fix this upstream in react native, or just ship a hard copy of the codegen files with VisionCamera (wouldn't like to do that easy to break). 

That being said, i am not sure if the ETA of EoW is realistic. I think more like beginning of next week!

**Comment by hannojg** [comment]
Created an issue here, looking into it:

- https://github.com/facebook/react-native/issues/47113

**Comment by mountiny** [comment]
agreed, the fixed copy sounds reasonable until this is fixed

**Comment by mountiny** [comment]
going to make it weekly

**Comment by hannojg** [comment]
Update:

- The iOS part is mostly done and working

Todo:

- [ ] iOS fix remaining use cases (code scanner, FP)
- [ ] Hard copy codegen code to avoid bug
- [ ] bridge android

I am sure that i will finish those items by the end of this week, however Marc is currently OOO and I will need his final review (+ he is the only one who can do a release).
So with review + testing i would assume that this lands next week! 

[Meanwhile i will open a PR that uses vision camera from the current development branch for testing in expensify!]

**Comment by mountiny** [comment]
thanks for an update

**Comment by hannojg** [comment]
Started a PR here:

- https://github.com/Expensify/App/pull/51638 (uses a unreleased version of vision camera)

iOS part is ready, now fixing up the android part

Once everything is ready we will test some more and publish a new version that we then can use in newdot!

**Comment by hannojg** [comment]
Okay, android is working as well now. Waiting for @mrousavy to come back from OOO to finalise tmrw!

**Comment by hannojg** [comment]
We have come to the conclusion that the code we need to introduce to vision camera for FabricComponents using codegen doesn't meet our quality barrier.
Proper new arch support for vision camera will be added when we migrate it to nitro modules.

([See discussion here](https://margelo.slack.com/archives/C035J5C9FAP/p1730738516530279))

**Comment by mountiny** [comment]
I think we can close this now, we just updated the library

Once the library will be migrated to nitro we can handle that in a specific issue
