### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250][Search v2.1] Remove Search filter multi-select list headers

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#50654]
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1728620621671039), we should remove the list headers for the following Search filters:

- Expense type
- Tag
- Category
- Currency
- Tax rate

Additionally, we should add a `Virtual` flag to indicate that a specific card is a virtual card

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by zanyrenney** [comment]
@luacmartins can you clarify the payment amount in your issues like this, so it helps the BZ team to know what amount to state in the payment summary? Cheers!

**Comment by luacmartins** [comment]
Ah yea, not sure why the automation didn't add the price to it, but this is the standard $250.

**Comment by zanyrenney** [comment]
Cool thanks for clarifying @luacmartins

**Comment by zanyrenney** [comment]
**Payment summary**

$250 to @fedirjh - please request via ND Manual Requests. Thanks!

**Comment by garrettmknight** [comment]
$250 approved for @fedirjh
