### ISSUE TITLE
[HOLD for payment 2024-10-30] Add RBR reason to LHN debugging

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#50665]
As discussed [here](https://github.com/Expensify/App/issues/46992#issuecomment-2407590055), let's add the reason a given report is showing an RBR in the LHN to the reports debug information. Similar to what we do for GBRs. 

cc @pac-guerreiro

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by pac-guerreiro** [comment]
Hi! I’m Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this task!

**Comment by pac-guerreiro** [comment]
Hey, yesterday I opened a draft PR for this so you can see my progress while I work on this issue 😄 

Here is what remains to be done:
- [ ] Add RBR reason test cases in `DebugUtilsTest.ts`
- [ ] Add screenshots
- [ ] Add QA testing steps

**Comment by pac-guerreiro** [comment]
Today's update:
- [x] Add RBR reason test cases in `DebugUtilsTest.ts`

Todo:
- [ ] Fix unit test for when there are transaction thread violations
- [ ] Add screenshots
- [ ] Add QA testing steps

**Comment by puneetlath** [comment]
Thanks for these updates!

**Comment by pac-guerreiro** [comment]
The PR is now ready for review! 😄

Go ahead @DylanDylann

**Comment by pac-guerreiro** [comment]
I just applied the suggested changes by @puneetlath and @DylanDylann.

The PR is ready for a new review 😄

**Comment by pac-guerreiro** [comment]
The PR was finally merged 🙌

**Comment by DylanDylann** [comment]
The regression test is covered [here](https://github.com/Expensify/App/issues/46992#issuecomment-2421661050)

**Comment by puneetlath** [comment]
@DylanDylann I'm going to have each of the debug mode PRs be a milestone on one Upwork job. Just to make things easier for me to pay. 

The offer for is here: https://www.upwork.com/nx/wm/offer/new/1039087488. I've added 3 PRs as milestones so far. I'll add the others as milestones as we go. 

Please ping me here when you've accepted.

**Comment by DylanDylann** [comment]
@puneetlath Accepted 🙏

**Comment by puneetlath** [comment]
Paid this one. Thanks y'all!
