### ISSUE TITLE
mWeb - IOU - Green line displayed on editing scan expense but not shown for manual expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50664]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Login as employee
3. Open employee workspace chat
4. Create a scan expense
5. Enter all the fields and edit all the fields
6. Note you can see green line
7. Create a manual expense
8. Enter all the fields and edit all the fields
9. Note green line is not displayed

## Expected Result:
Green line appearance must be consistent

## Actual Result:
Green line displayed on editing scan expense but not shown for manual expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/577dbbb3-9ad1-41a8-bfa4-b105c761fc43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment]
Unsure of the exact bug from watching the vid, going to close for now cuz it seems like an edge case and/or polish, ie. I don't think anyone other than a tester/employee would notice.  Comment/reopen if ya disagree.
