### ISSUE TITLE
Share draft reports with members of a workspace chat

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#50675]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1728075637518619?thread_ts=1727729585.218349&cid=C06ML6X0W9L
## Action Performed:
1. Create workspace
2. Invite Submitter/Approver
3. Set approver
4. Enable Delay Submission to any frequency
5. As the submitter submit two expenses in a report
6. As approver in OldDot, reject the report

## Expected Result:
The Approver should still have access to the draft report in the workspace chat in NewDot

## Actual Result:
The Approver no longer has access to the draft report in the workspace chat even though they can see it.

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @youssef-lr</details>

**Comment by garrettmknight** [comment]
The Auth PR deployed - @youssef-lr we don't need any follow up PRs do we?

**Comment by youssef-lr** [comment]
This is fixed!
