### ISSUE TITLE
[$250] Compose box - Composer is not focused after dismissing 'search modal' or 'Keyboard shortcuts

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50683]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+ds@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login to an account
2. Open any chat, notice that the composer is focused.
3. Press on CTRL + K
4. Press ESC key to dismissed the 'search modal'

## Expected Result:
Composer is focused after dismissing the modal

## Actual Result:
Composer is not focused after dismissing the modal

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/61f46279-035e-4e31-9b1d-80892333462f

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845888591650591093</li>
        <li>Upwork Job ID: 1845888591650591093</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by marcochavezf** [comment]
Ok, this is not reproducible in production. Making it external to get more 👀 to find a solution

**Comment by marcochavezf** [comment]
Git bisect lead me to this PR: https://github.com/Expensify/App/issues/50683 and there's already a [revert PR](https://github.com/Expensify/App/pull/50746)

**Comment by marcochavezf** [comment]
The [PR](https://github.com/Expensify/App/pull/50746) that reverts the offending PR was merged and deployed to staging. Tested it on staging and the error is not happening anymore. Closing it out

**Comment by kavimuru** [comment]
Bug is fixed 

https://github.com/user-attachments/assets/b2cf71fd-6c91-4a31-9fdc-ff9e10b2f8de
