### ISSUE TITLE
Workspace - WS can't be deleted after Expensify cards was disabled

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50684]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: new private domain account. Workspace with added expensify card (physical or virtual).

1. Go to Workspace > Expensify cards
2. Click on added card > Deactivate card
3. Go to Workspace > More features
4. Disable Expensify cards
5. Delete workspace

## Expected Result:
Workspace deleted.

## Actual Result:
An error occur during deletion. It says that my ws has expensify card when actually it hasn't.
Error Message: `Your company has enabled Expensify Cards. Please reach out to [concierge@expensify.com](mailto:concierge@expensify.com)
to have the cards removed. Until then, the Workspace cannot be deleted.`
## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/81077181-f12a-4500-be68-f768e6ae6953

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment]
Not overdue. Will triage tomorrow

**Comment by joekaufmanexpensify** [comment]
Discussing [here. ](https://expensify.slack.com/archives/C05LX9D6E07/p1729005507731069?thread_ts=1728966082.429659&cid=C05LX9D6E07)

**Comment by mountiny** [comment]
We would like the modal to looks like this
![image](https://github.com/user-attachments/assets/44260f52-f057-4b22-9ead-250410703f1f)

**Comment by joekaufmanexpensify** [comment]
@mountiny the more I think about it, I kinda wonder if this one is worth prioritizing right now. Deleting a workspace is in general such a rare action to take. Given this works now the same way it does in OldDot (which is totally fine), I wonder if it's worth just leaving as is for now until we experience a problem from it?

As this isn't really a bug now, and I wonder if it's worth investing resources in changing this design before really anyone is using this feature.

**Comment by mountiny** [comment]
@joekaufmanexpensify I think its still just good to knock it out now, I think its a rare case, but when it happens its annoying, especially given its much more easier now to run into this case than then we required verified domain

**Comment by mountiny** [comment]
But I think we can make it weekly and maybe @nkuoch would be up for helping with this one

**Comment by joekaufmanexpensify** [comment]
Fair enough, sounds good. In addition to the deleting workspace case though, there's one other case we should align on. According to [the design doc](https://docs.google.com/document/d/1sTg-e11jdOmregOFBhdO8ALlykKl8PqTeTEAgEMS6mU/edit?tab=t.0#bookmark=id.lgzjfn4hej7b), the user should not be able to toggle off `Expensify Card` in `More features` when the workspace is provisioned at all. But in the above video, toggling this off is possible after terminating the workspace's only assigned card. 

I'm thinking we intentionally allowed this when the workspace is provisioned (but there are no active cards). Is that right, @mountiny?

**Comment by joekaufmanexpensify** [comment]
PRs in review!

**Comment by nkuoch** [comment]
Seems like toggling off doesn't actually do anything backend side? https://github.com/Expensify/Web-Expensify/pull/28072/files#diff-fd75745654fb72974da44d75c3835ee837a6e644a05a6ffaae48556924242946R877

cc @mountiny do you know if an issue currently exists for that?

**Comment by mountiny** [comment]
I am not sure how that PR is related. This is the method used to toggle the expensify card feature https://github.com/Expensify/Web-Expensify/blob/fe926b0bc18fb7496fbc31280f092c5d5240ba7c/lib/PolicyAPI.php#L3395-L3411 and it changes the flag, but I dont think it does much more right now

**Comment by nkuoch** [comment]
> I'm thinking we intentionally allowed this when the workspace is provisioned (but there are no active cards). Is that right, @mountiny?

And should we deprovision it when toggling it off when there is no active card? cc @mountiny ?

**Comment by mountiny** [comment]
> And should we deprovision it when toggling it off when there is no active card? cc @mountiny ?

Asked [here](https://expensify.slack.com/archives/C03U7DCU4/p1730463108128759)

**Comment by joekaufmanexpensify** [comment]
Still ongoing

**Comment by joekaufmanexpensify** [comment]
Same

**Comment by joekaufmanexpensify** [comment]
PR still in review

**Comment by joekaufmanexpensify** [comment]
@nkuoch I see PR above was deployed. Are we good here now?

**Comment by mountiny** [comment]
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1732562841674179)
