### ISSUE TITLE
[HOLD for payment 2024-11-13] [$250] Expensify Card - "Add shipping details" button still appears when the card is deactivated

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50693]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User has assigned a physical card to self.
- Private details have not been added.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Expensify Card.
3. Click on the Expensify Card that is assigned to yourself.
4. Click Deactivate card.
5. Deactivate the card.
6. Go to workspace chat.

## Expected Result:
"Add shipping details" button will not appear since the card is deactivated.

## Actual Result:
"Add shipping details" button still appears when the card is deactivated.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e865ffc9-e73e-432f-92d7-8e48f613abbd

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846577574853745828</li>
        <li>Upwork Job ID: 1846577574853745828</li>
        <li>Last Price Increase: 2024-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104523414</li>
<li>truph01 | Contributor | 104523417</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by truph01** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Add shipping details" button still appears when the card is deactivated.

### What is the root cause of that problem?
- We show the "Add shipping card" butotn without checking if the card is deactivated or not:

https://github.com/Expensify/App/blob/e4969b22e7dbb1f6a200cc587ced4ab665415c0e/src/components/ReportActionItem/IssueCardMessage.tsx#L40
### What changes do you think we should make in order to solve the problem?
- Should check whether the card is existed/actived or not:
```
 const workspaceAccountID = PolicyUtils.getWorkspaceAccountID(policyID);
    const [cardsList] = useOnyx(`${ONYXKEYS.COLLECTION.WORKSPACE_CARDS_LIST}${workspaceAccountID}_${CONST.EXPENSIFY_CARD.BANK}`);
    const cardIssuedActionOriginalMessage = ReportActionsUtils.isActionOfType(
        action,
        CONST.REPORT.ACTIONS.TYPE.CARD_ISSUED,
        CONST.REPORT.ACTIONS.TYPE.CARD_ISSUED_VIRTUAL,
        CONST.REPORT.ACTIONS.TYPE.CARD_MISSING_ADDRESS,
    )
        ? ReportActionsUtils.getOriginalMessage(action)
        : undefined;
    const cardID = cardIssuedActionOriginalMessage?.cardID ?? -1;
    const card = cardsList?.[cardID];
    const shouldShowAddMissingDetailsButton = !isEmptyObject(card) && action?.actionName === CONST.REPORT.ACTIONS.TYPE.CARD_MISSING_ADDRESS && missingDetails && isAssigneeCurrentUser;

```


### What alternative solutions did you explore? (Optional)

**Comment by SWS-5007** [comment]
Hi, Here is my suggestion.

1. Check card Status:
Before rendering the "Add shipping details" button, we should check the status of the card if it is active or deactivated.
We can add conditional statement that checks the card's activate status.

2. Check Backend:
We should ensure that Backend properly sends the card's status in the response.

3. Modify Frontend:
In the Frontend, we can update code handling the display of button like below:
```
// Assuming `card` is the card object and `card.status` indicates if it's active
const shouldShowAddShippingDetailsButton = (card) => {
    return card.status === 'active' && !card.hasShippingDetails;
};

if (shouldShowAddShippingDetailsButton(card)) {
    // Show the button
} else {
    // Hide the button
}
```

4. Update Existing Logic:
Maybe, we can add an additional condition in the existing card rendering functions or React Components.

If we discuss more details about current issue and help me to check your codebase as soon, I can provide with better solution.
Good luck!

**Comment by zanyrenney** [comment]
@hoangzinh please complete this as I can't do the payment until it is done. Thanks!

**Comment by zanyrenney** [comment]
That regression test looks great, adding it now.

**Comment by zanyrenney** [comment]
https://github.com/Expensify/App/issues/52563

**Comment by zanyrenney** [comment]
**payment summary**

@hoangzinh requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104523414) (Reviewer) paid $250 via upwork.
@truph01 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104523417) (Contributor) paid $250 via upwork.
