### ISSUE TITLE
[HOLD for payment 2024-10-29] [Wave Control] [QBD] Restrict QBD to Control plans

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#50704]
We need to show QBD in the policy's accounting page for Control plans only.

**Comment by kadiealexander** [comment]
@jamesdeanexpensify do you have any copy suggestion for what should show in the QBD equivalent of this? 

![image](https://github.com/user-attachments/assets/9d575007-e5ea-437d-8734-f48836975a81)

**Comment by jamesdeanexpensify** [comment]
I would probably just substitute "QuickBooks Desktop" in for "Sage Intacct" and then...what minimal tweaks can we make to that sentence that starts "Gain in-depth..." to make it accurate for QBD? Like what are the most valuable selling points?

**Comment by kadiealexander** [comment]
I think our most valuable selling point is that it's the only two-way automated QBD connector on the market right now. There isn't really anything unique like user-defined dimensions or custom segments to call out. Does it need to be `in depth`?

Maybe something like:

Enjoy automated syncing and reduce manual entries with the Expensify + QuickBooks Desktop program. Gain ultimate efficiency with a real-time, two-way connection with expense coding by class, item, customer, and project.

**Comment by jamesdeanexpensify** [comment]
Edited your comment a bit, but that sounds good! Can we see how that looks mocked up?

**Comment by kadiealexander** [comment]
Sure can!

![image](https://github.com/user-attachments/assets/ed22c698-11aa-4b23-be20-2549c07e4ad2)

It's [here](https://www.figma.com/design/E2lt5o4nXHjlDcepaOjg2D/QuickBooks-Desktop?node-id=9748-21524&t=QOBAtLFeBotIOIjw-4) in Figma if anyone wants to play around!

**Comment by jamesdeanexpensify** [comment]
Just made one edit but the Figma now looks good!

**Comment by kadiealexander** [comment]
Updated my screenshot above, thanks James!! @lakchote let me know if you need anything else from us.

**Comment by lakchote** [comment]
Thank you both @jamesdeanexpensify @kadiealexander that's good for me!

**Comment by trjExpensify** [comment]
What's the dealio here? Standard payment issue? New feature and a regression test will be added for it when the tests are passed over to Applause centrally?

**Comment by lakchote** [comment]
> What's the dealio here? Standard payment issue? New feature and a regression test will be added for it when the tests are passed over to Applause centrally?

It's a standard payment issue. [The manual test steps document](https://docs.google.com/document/d/1khNbLOaOkVIJB-miemNDgMjFpkqCp7Dm1OvcywSj7Nc/edit?tab=t.0#heading=h.nhtsmauf72jq) with all the regression tests has already been done yesterday.

**Comment by trjExpensify** [comment]
Okay great, I see the upgrade is included in that doc handed over. Thanks! 

Payment summary as follows: 

- $250 to @hoangzinh for the C+ review (go ahead and request!)
- $250 to @ZhenjaHorbach for the implementation (offer sent!)

**Comment by trjExpensify** [comment]
Paid @ZhenjaHorbach, closing!

**Comment by garrettmknight** [comment]
$250 approved for @hoangzinh
