### ISSUE TITLE
[HOLD for payment 2024-11-18] [Workspace Chats for All] Default QAB to primary workspace if no value

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#50728]
In https://github.com/Expensify/App/issues/49344 we are going to make it possible to submit to any workspace, even if you don't have the workspace chat locally. 

We also want to make it so that any user that is a member of a policy has a default value for their QAB. So what we should do is update the QAB behavior so that if the nvp doesn't have any data set, and the user is on any group policies, then we set the default value for the QAB to be to submit to their primary group policy, which is stored in `nvp_expensify_activePolicyID`. 

Slack discussion: https://expensify.slack.com/archives/C07NMDKEFMH/p1728585368177889?thread_ts=1728418936.029729&cid=C07NMDKEFMH

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by puneetlath** [comment]
@ishpaul777 taking this off hold now.

**Comment by puneetlath** [comment]
Back to weekly. We had to revert the previous PR.

**Comment by trjExpensify** [comment]
Confirming we'll set this to `submitScan` on the primary workspace if no value, right?

**Comment by puneetlath** [comment]
Ok, after discussion, we're going to take a slightly different direction here. Let's only default the QAB if the user: 
- has a group workspace as their primary policy 
- that workspace has isPolicyExpenseChatEnabled=true
- does not already have a QAB NVP value 

Given that. I have taken this off hold and we can go ahead and implement it.

**Comment by flaviadefaria** [comment]
@puneetlath, what about setting it to `submitScan` on the primary workspace if there is no value as @trjExpensify mentioned above?

**Comment by puneetlath** [comment]
Ah yes, that's what I meant to convey with what I said. We will set it to submitScan on the primary workspace if the primary user meets the criteria in the list: 

- user has a group workspace as their primary policy
- that workspace has isPolicyExpenseChatEnabled=true
- user does not already have a QAB NVP value

**Comment by flaviadefaria** [comment]
Awesome, thanks for clarifying :)

**Comment by puneetlath** [comment]
@dukenv0307 what do you think about adding a regression test here?

**Comment by puneetlath** [comment]
@ishpaul777 offer here: https://www.upwork.com/nx/wm/offer/104952640
@dukenv0307 offer here: https://www.upwork.com/nx/wm/offer/104952651

Please ping me on this issue when you've accepted them.

**Comment by puneetlath** [comment]
@ishpaul777 has been paid.

**Comment by puneetlath** [comment]
Regression test issue: https://github.com/Expensify/Expensify/issues/446312

Payment summary: 
- C - $250 - @ishpaul777 - paid via Upwork
- C+ - $250 - @dukenv0307 - to be paid via NewDot

Thanks everyone!

**Comment by JmillsExpensify** [comment]
$250 approved for @dukenv0307
