### ISSUE TITLE
[Awaiting Payment] Remove "submit expense" from the create menu in reports that can't be edited by the submitter

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#50734]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.enterprise.slack.com/archives/C049HHMV9SM/p1728931883829909?thread_ts=1728667465.791999&channel=C049HHMV9SM&message_ts=1728931883.829909

## Action Performed:

I think this is what the behavior is intended to be in this situation:
1. Consider a workspace with submitter, approver A and approver B
2. Set approver a as approver A
3. As submitter, submit expense to the workspace chat. Will be assigned to approver A.
4. Change approver to approver B
5. As submitter, open the report and tap the "+" button in the report.

## Expected Result:
The submitter should only see the add attachment and assign task.

## Actual Result:
The submitter has the "submit expense" option and when they try to use it, it throws an error.

## Workaround:
Submit an expense in the workspace chat.

## Platforms:
All

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021845992378187974958</li>
        <li>Upwork Job ID: 1845992378187974958</li>
        <li>Last Price Increase: 2024-10-15</li>
    </ul>
</details>

**Comment by youssef-lr** [comment]
I'm gonna take this one internal as I'll need to test App changes against backend changes.

**Comment by youssef-lr** [comment]
@twilight294 your proposal is not enough to fully fix the issue, for example, if will break when the approver has a vacation delegate. This will need some backend changes in order to have some data available in App, and I'm going to need to test both backend and frontend while working on this.

**Comment by youssef-lr** [comment]
I just realized I already had a PR that fixes this https://github.com/Expensify/App/pull/49677, but I need to update it to take into account the delegate.

**Comment by youssef-lr** [comment]
Working on it in this PR https://github.com/Expensify/App/pull/49677

**Comment by alitoshmatov** [comment]
PR is still in progress https://github.com/Expensify/App/pull/49677

**Comment by garrettmknight** [comment]
PR is merged and on staging.

**Comment by muttmuure** [comment]
Great work here!

**Comment by garrettmknight** [comment]
One prod yesterday!

**Comment by garrettmknight** [comment]
@mollfpr you get paid somewhere else for your review?

**Comment by mollfpr** [comment]
@garrettmknight I think I'll be paid here https://github.com/Expensify/App/issues/51075

**Comment by garrettmknight** [comment]
Perfect - I'm gonna close this then!
