### ISSUE TITLE
[Master Tracking] Create an Onboarding / New Expensify Training for Existing Users

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#50736]
Problem: We’re observing a lot of user confusion when existing users come into New Expensify. Most of them are just coming over to talk with Concierge, but they start clicking around and find themselves confused because it is different than Expensify Classic. 

Solution: Provide existing users coming over with onboarding/training and the value-added of New Expensify.

The solution is still very much of a WIP. Given the predesign, we're likely going to bring a couple of different potential solutions to the team to explore and then go from there. But it will likely include some combination of:
- Modal with text and/or video 
- Messaging from Concierge or in the workspace chat, maybe with an instructional video
- Embedded tool tips to point the user to the features they need to explore

[Predesign 1 is here](https://expensify.slack.com/archives/C07NMDKEFMH/p1728598708672069). More updates to come.

**Comment by zanyrenney** [comment]
Thanks for spinning this up @danielrvidal !

**Comment by zanyrenney** [comment]
I don't think this is a bad idea:
> let's just start with the MVP onboarding that explains how the system works overall, and then we can extend it with admin-specific (and other workflow-specific) onboarding later

**Comment by zanyrenney** [comment]
Posted an update in the migrate channel [here](https://expensify.slack.com/archives/C07NMDKEFMH/p1729090661226229)

**Comment by zanyrenney** [comment]
Going to rename this one, as I keep losing it.

**Comment by zanyrenney** [comment]
Conversation is ongoing, @dubielzyk-expensify is making mocks.

**Comment by zanyrenney** [comment]
Going to spin up a design issue to keep track.

**Comment by zanyrenney** [comment]
Added current solution to the design issue [here](https://github.com/Expensify/App/issues/51178#issuecomment-2427427674)

**Comment by danielrvidal** [comment]
Design doc is being written and we're making daily progress.

**Comment by zanyrenney** [comment]
Actively being worked on, there were a few outstanding quetsions on backwards compatibilities but largely good here.

**Comment by zanyrenney** [comment]
Doc has been sent out, reviewing comments!

**Comment by zanyrenney** [comment]
Doc is in detailed phase.

**Comment by zanyrenney** [comment]
Doc is in detailed.

**Comment by zanyrenney** [comment]
Whoops!

**Comment by zanyrenney** [comment]
We are in the detailed, there were a few conversations impacting that, e.g. [here](https://expensify.slack.com/archives/C07NMDKEFMH/p1731624040774809)

**Comment by zanyrenney** [comment]
Detailed has been shipped, there is a discussion here I need to catch up with @danielrvidal about! https://expensify.slack.com/archives/C07NMDKEFMH/p1731431756356499?thread_ts=1731354813.312789&cid=C07NMDKEFMH

**Comment by zanyrenney** [comment]
We are having a broader discussion about this here - https://expensify.slack.com/archives/C07HPDRELLD/p1732732935190809

**Comment by danielrvidal** [comment]
This is in implementation so being worked on.

**Comment by zanyrenney** [comment]
Being worked on here: https://github.com/Expensify/Expensify/issues/437980

**Comment by zanyrenney** [comment]
@danielrvidal thoughts on closing this issue out and managing in that central project one?

**Comment by zanyrenney** [comment]
@danielrvidal let me know what you think? As the updates seem to be happening and more centralised there, I think we can close this out and then handle follow up in separate GH issues but lmk if you disagree?

**Comment by zanyrenney** [comment]
We are handling this in the central issue that is linked above, I've asked Daniel if he disagrees with closing and haven't heard back! So I'm just gonna take the step here and close this issue out and manage this in the central tracking issue for the main design doc.

@danielrvidal feel free to reopen if you disagree!

**Comment by danielrvidal** [comment]
Sorry, I didn't see this until now but agree. Always feel free to hit me up in slack/DM!
