### ISSUE TITLE
Error appears after enter test credentials on Plaid modal

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#5075]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Issue is failing PRs https://github.com/Expensify/App/pull/4962 and https://github.com/Expensify/App/pull/5029 (CC @marcaaron)

## Action Performed:
1. With the app instlalled on the device navigate to staging.new.expensify.com/bank-account/new
2. Select the option to log in to bank account
3. Enter the test credentials. 

## Expected Result:
User should be able to use the test credentials and redirected to the bank account selector. 

## Actual Result:
An internal server error occurred when using the test credentials. 

## Workaround:
Unknown. 

## Platform:

Where is this issue occurring?

- Android
- iOS

**Version Number:** 1.0.93-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://user-images.githubusercontent.com/44479856/132071472-99fe1557-aecf-4c2b-8db1-36fa2343c1dc.png)

https://user-images.githubusercontent.com/44479856/132071487-c22c4f16-0aac-4888-9d85-8db65182e576.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Assigned @marcaaron since he's the author of both PRs.

**Comment by marcaaron** [comment]
Is this only happening on Android? It was working fine for me and now suddenly isn't on staging. Since no customers are using this yet we can either revert this or merge it anyway. I'll leave this up to deployers to decide as it's Friday and I don't know if there are plans to deploy a release build or not.

**Comment by isagoico** [comment]
I was only able to check on Android app since iOS bank-account/new link is redirecting to mWeb (mentioned here https://github.com/Expensify/App/pull/5029#issuecomment-912829890) I asked a tester to check on iOS with the new link and will let you know the results. 

On the deploy release I think @roryabraham can answer that :)

**Comment by isagoico** [comment]
Same error is reproduced in iOS 
![image](https://user-images.githubusercontent.com/44479856/132073332-45d87432-39a6-47e1-baeb-e1f31382c8db.png)

**Comment by roryabraham** [comment]
Given that:

1. This is not yet a user-facing feature
1. Before the offending PRs, the modal just wasn't rendering at all (so it's not really broken any worse than it was before)

I think we can demote this from deploy-blocker to regular bug.

**Comment by marcaaron** [comment]
So... I'm stumped on this one. But here's what I can say about it:

- I re-tested on dev build + also with staging env variables and it works... totally fine
- Staging web works.. well, fine
- Built a release build for Android and it works... fine
- Went back to try the Play Store beta again and... `Internal error occurred`

And that's my cue... have a good weekend everyone 😃

**Comment by marcaaron** [comment]
Took another look today and I have verified that:

1. Non-sandbox bank connections should work fine on production
2. Probably there's some issue with our token endpoint and we are getting rate limited as described [here](https://stackoverflow.com/questions/57684362/how-can-i-resolve-the-following-plaid-api-error-internal-error-occurred)

@kevinksullivan @MitchExpensify do you guys think this is worth prioritizing right now? It basically means that we can't test Plaid using the sandbox credentials on staging versions of the app until resolved.

**Comment by marcaaron** [comment]
Did some more testing + looking at logs and noticed that we are actually using the `production.plaid.com` API endpoint ([logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22DXkncM%22)+AND+timestamp:[2021-09-07T16:18:08.190Z+TO+2021-09-07T18:18:08.190Z]&index=logs_expensify-012436)) while using the staging version of the app. 

However, the staging version of the app _should_ be pointing to `staging-secure.expensify.com` which should be using the `sandbox.plaid.com` endpoint. On the web version of the app [the correct endpoint is used](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22wxpT6a%22)+AND+timestamp:[2021-09-07T16:26:25.303Z+TO+2021-09-07T18:26:25.303Z]&index=logs_expensify-012436). However, it looks like that's not happening for the native app judging from the logs. Pretty confused about why this is happening. 😕

**Comment by marcaaron** [comment]
Alright, now I just think maybe this has never worked and we haven't tested it on native. I'm pretty sure we are not using the "staging" environment variables for these builds. @AndrewGable or @Jag96 do either of you guys know?

**Comment by AndrewGable** [comment]
Yes, I agree. I think TestFlight and Google Play Beta use production end points because we do not build another version, we just move them from TestFlight to production, changing the end points would require a new build

**Comment by marcaaron** [comment]
>Yes, I agree. I think TestFlight and Google Play Beta use production end points because we do not build another version, we just move them from TestFlight to production, changing the end points would require a new build

Ah ok that makes so much sense thanks for verifying. Mystery solved! I thought I had broken this 😄 

It does seem like we're able to detect that we are in the "staging" environment (judging from the `STG` header badge) so maybe we can have secure calls switch to the staging server in these cases. Will spin something up for that.

**Comment by Jag96** [comment]
> It does seem like we're able to detect that we are in the "staging" environment (judging from the STG header badge) so maybe we can have secure calls switch to the staging server in these cases.

Yeah, you can check `getEnvironment` and `betaChecker` to see how we handle the badges, I think using the same logic would be the best way to handle that using existing code.

**Comment by marcaaron** [comment]
I guess thinking more on this though... is the intention of having a beta version of the app that things like setting up a bank account would work as they do in production? I'm not sure who has access to this beta - but if I was a random public beta tester (or even an internal one) I might be confused about why the app isn't letting me set up a bank account (and the answer would be because we are using a sandbox).

**Comment by AndrewGable** [comment]
> is the intention of having a beta version of the app that things like setting up a bank account would work as they do in production?

Yes, I believe that is the intention.

**Comment by marcaaron** [comment]
Got it. Maybe we can add a toggle in settings to switch to the staging secure server? I know there was some discussion about always having staging use the production endpoints. But it makes testing these flows with test credentials impossible. Just not sure how desperate we are to get this working. Will wait for @MitchExpensify @kevinksullivan to chime in before doing anything else.

**Comment by AndrewGable** [comment]
How do we test this on old.expensify?

**Comment by marcaaron** [comment]
On the staging website we just use the staging secure server.

On Mobile-Expensify we hit [this page](https://github.com/Expensify/Web-Expensify/blob/15eb6c35e3d41acf1f921aadad8b6a53cd7eb2e5/mobile/secureIframe.php#L26-L27) and would be staging or prod based on [this](https://github.com/Expensify/Mobile-Expensify/blob/357c650031390afb37b55c8917f5ec08964224fd/app/page.import.js#L47-L48) which ultimately depends on [this](https://github.com/Expensify/Mobile-Expensify/blob/357c650031390afb37b55c8917f5ec08964224fd/app/libs/api.js#L1863-L1865) which we can toggle with a switch [here](https://github.com/Expensify/Mobile-Expensify/blob/357c650031390afb37b55c8917f5ec08964224fd/app/Controllers/SettingsController.js#L1027-L1030).

**Comment by marcaaron** [comment]
Just following up here. Ended up implementing something similar to what we have in Mobile-Expensify and hid it in the user preferences here:

![2021-09-07_13-01-18](https://user-images.githubusercontent.com/32969087/132421260-75fc1693-25ab-4672-9080-6dd612ee3ead.png)

It should only show on the Google Play / Test Flight versions of the app as it's using the environment checker + basically just forces the API to use staging secure then saves it as a local preference.

**Comment by shawnborton** [comment]
Here for the design eyes - can we get some more padding below the language selector and above the test preferences section? Thanks!

**Comment by shawnborton** [comment]
Also I think the switch and the label to the left should be vertically centered.

**Comment by botify** [comment]
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

**Comment by marcaaron** [comment]
@shawnborton ah shucks I'll create a follow up for those comments @shawnborton as this got merged before I could update. FWIW it's only going to be visible for beta users but I agree with the padding and centering comments 100%.

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1218882715) to staging by @ctkochan22 in version: 1.0.95-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

**Comment by botify** [comment]
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1222459337) to production by @roryabraham in version: 1.0.96-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅
