### ISSUE TITLE
mWeb - Expense - The amount is not aligned with the currency during expense creation flow

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50778]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5085590&group_by=cases:section_id&group_order=asc&group_id=296775
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open any chat.
3. Tap on the "+" icon.
4. Tap on "Submit Expense"
5. Enter any amount.
6. Verify the amount added is aligned with the currency.

## Expected Result:
Expense amount and currency, should be displayed aligned when starting the expense creation flow.

## Actual Result:
The amount and currency are not aligned when starting the expense creation flow.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c64b0f55-5d7b-43fc-92f9-2a978e37d272

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lakchote** [comment]
@youssef-lr it must be related to the [same problem](https://github.com/Expensify/App/issues/50777#issuecomment-2413078651) I had, with https://github.com/Expensify/App/pull/49896 introducing the bug.

**Comment by IuliiaHerets** [comment]
The same behavior happens on the Rules page in WS's more features 

https://github.com/user-attachments/assets/3f3b19bf-45c8-495c-845f-499e982814c3

**Comment by youssef-lr** [comment]
@tsa321 thanks! Please check the comment from Shawn in the PR then we can merge

**Comment by youssef-lr** [comment]
This is done.

**Comment by alexpensify** [comment]
@youssef-lr - this one was closed, but should there be a payment to the C+ who helped with the review? Thanks!

**Comment by youssef-lr** [comment]
@alexpensify I don't think so as this was a regression and the original contributor fixed it.

**Comment by alexpensify** [comment]
Noted, let's keep this closed then.
