### ISSUE TITLE
[HOLD for payment 2024-12-16] Copilot - The bottom line of the pop-up modal is not visible

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50774]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Security > Add copilot.
3. Add a copilot.
4. Click 3-dot menu next to the copilot.

## Expected Result:
The bottom line of the pop-up modal should be visible.

## Actual Result:
The bottom line of the pop-up modal is not visible.
This issue is not reproducible when the display is very zoomed out (wide screen).

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/13d79c9d-8f57-4cee-a25a-e2c21a2dd625

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by marcaaron** [comment]
cc @dangrous @rushatgabhane @allgandalf looks related to https://github.com/Expensify/App/pull/47984

**Comment by marcaaron** [comment]
>Pre-req: be on copilot beta.

I think this can be demoted.

**Comment by marcaaron** [comment]
But please address before removing the beta?

**Comment by dangrous** [comment]
@rushatgabhane can you put up a PR for this one? Would be great to get it sorted by the end of the week!

**Comment by dangrous** [comment]
@rushatgabhane do you have time for this one or should we open it up? We just have to rejigger this section I think, probably including the `windowHeight` and adding a `Math.min()` in there in some way. I think there's also some left/right wonkiness that we should look at.

I realize you took this code from some other places in the app that use similar behavior but for whatever reason it doesn't seem to fit here (maybe doesn't there either, who knows).

https://github.com/Expensify/App/blob/a8e1b1365335eb9a592024e52eaa6684a12360b8/src/pages/settings/Security/SecuritySettingsPage.tsx#L74-L80

**Comment by dangrous** [comment]
bump @rushatgabhane - is this something you should handle or should we open up for contributors?

**Comment by kadiealexander** [comment]
Reassigning for someone to handle payment as I'm OOO for the next two weeks.

**Comment by dangrous** [comment]
PR in review! we just have one improvement to make to the design (coloring the icon) and then we'll be good to merge

**Comment by dangrous** [comment]
PR in revierw

**Comment by dangrous** [comment]
Let's get this done this week!

**Comment by slafortune** [comment]
Still waiting on PR

**Comment by slafortune** [comment]
Offer sent [here](https://www.upwork.com/nx/wm/offer/105384899) @allgandalf

**Comment by slafortune** [comment]
Reviewer: @rushatgabhane owed $250 via NewDot

**Comment by garrettmknight** [comment]
$250 approved for @rushatgabhane
