### ISSUE TITLE
[HOLD for payment 2024-11-07] [$100] Expensify Card - improvements to the Set a limit screen

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50788]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition: Enable expensify card and add a VBA

1. Go to https://staging.new.expensify.com/home
2. Tap profile icon-- workspaces- workspace
3. Tap expensify cards
4. Tap +issue card - select a user -- physical card
5. Note smart limit checked
6. Tap next
7. Enter a decimal number and tap next

## Expected Result:
In expensify card, issue a card section if we set limit in decimals, must not show error enter valid amount.

## Actual Result:
In expensify card, issue a card section if we set limit in decimals, shows error enter valid amount.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e3ea6c34-11ee-495f-aa66-b796969fc7e4

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846213635698721920</li>
        <li>Upwork Job ID: 1846213635698721920</li>
        <li>Last Price Increase: 2024-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104449939</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by slafortune** [comment]
Yeah - I don't think that we would/should expect a decimal to be entered.  I wonder if simply updating the error message to indicate that they need to enter a whole number would be good.

**Comment by slafortune** [comment]
Let's use this to make two updates to th Expensify Card Set Limit Screen 

- Align the $ with the amount box
- Update the error message to the exact error
  - Current error message is  `Please enter a valid amount before continuing.`

@Expensify/design can you chime in on what would be preferred language?
-  Please enter a whole dollar amount before continuing.
-  Enter only a whole dollar amount without a decimal point.
- ?

**Comment by shawnborton** [comment]
Let's see if the @Expensify/marketing team has any ideas, but I think I like the first bullet of your suggestions.

**Comment by NickTooker** [comment]
>Please enter a whole dollar amount before continuing.

I think this is fine.

**Comment by jamesdeanexpensify** [comment]
Double checking - the currency can **only** be dollars for Expensify Card limits right now, is that correct? Because otherwise "dollar amount" would be incorrect. I just want to make sure, thanks!

**Comment by slafortune** [comment]
@twilight294 would you like to update your proposal?

**Comment by shawnborton** [comment]
Since we're addressing the currency symbol elsewhere and this is just a copy update, we should probably bump this down to  something small like $62.50

**Comment by shawnborton** [comment]
$125 is too much for a simple copy change.

**Comment by thienlnam** [comment]
Proposal looks good, it's a pretty straightforward change. Perhaps we can just meet in between with $100. @slafortune is handling payment for this, so feel free to make a final decision here

**Comment by slafortune** [comment]
Offer sent [here](https://www.upwork.com/nx/wm/offer/104789183) @twilight2294 The price for this job is $100 which was decided prior to you asking to be assigned.  Perhaps the other PR you referenced should have been set to $100 as well, but this one had been discussed and agreed on.

**Comment by abekkala** [comment]
### PAYMENT SUMMARY: 

FIX: @twilight2294  [$100] Paid and Contract ended - thank you! 🎉 
PR REVIEW: @rayane-djouah [$100] Paid and Contract ended - thank you! 🎉
