### ISSUE TITLE
[HOLD for payment 2024-10-25] [Workspace feeds polish] SmartLimit option not showing on WorkspaceEditCardLimitTypePage

### ISSUE THREAD

**Issue by MariaHCD** [Expensify/App#50784]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1728928454869509?thread_ts=1727196342.211239&cid=C036QM0SLJK

## Action Performed:
1. Create a workspace on NewDot with advanced approvals configured
2. Configure the workspace for the Expensify Card
3. Attempt to issue a new card to a member

## Expected Result:
The SmartLimit option should display

## Actual Result:
The SmartLimit option was not displayed - only the Monthly and Fixed limit options were available

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

![image](https://github.com/user-attachments/assets/1747f6da-c44d-432f-b463-a7ce261336a0)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by mountiny** [comment]
I think it has to be control policy with policy chats enabled

**Comment by mountiny** [comment]
@VickyStash are you able to reproduce this one? I think you might need to set up the approver on the control policy in oldDot (at the isPolicyExpenseChatEnabled to true there as well) and then try it

**Comment by VickyStash** [comment]
@mountiny Yeah, I think I'm able to reproduce it. I've updated the approval mode to Advanced approvals in the old dot and it caused the mentioned bug.
cc @allgandalf

**Comment by VickyStash** [comment]
The video with reproduction, just in case

https://github.com/user-attachments/assets/ee6d37d9-daad-422c-ac0b-56924c01f92c

**Comment by VickyStash** [comment]
The [PR](https://github.com/Expensify/App/pull/50849) has been opened for the review.

**Comment by mountiny** [comment]
merged

**Comment by MariaHCD** [comment]
Thanks, all!

**Comment by tgolen** [comment]
Reopening this one so @allgandalf and @sonialiap can complete the regression checklist

**Comment by mountiny** [comment]
@allgandalf lets add a regression test for the smart limit option with the approver, I dont think that was covered in the the original testing steps for workspace feeds

**Comment by sonialiap** [comment]
@allgandalf bumping for completion of the checklist https://github.com/Expensify/App/issues/50784#issuecomment-2423054957
