### ISSUE TITLE
[HOLD for payment 2024-10-25] [Search v2.4] Remove Search in contextual suggestion when typing

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#50819]
Coming from [here](https://expensify.slack.com/archives/C05LX9D6E07/p1729008619397569?thread_ts=1729007631.513779&cid=C05LX9D6E07), we should only show the `Search in...` contextual suggestion when the user has no input in the router. We should remove it from the suggestions as soon as the user starts typing.

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by sonialiap** [comment]
@luacmartins did we have a C+ review this PR or is there no payment needed on this issue? I see dacitto is on the PR but I'm not clear if Srikar was the only reviewer

**Comment by luacmartins** [comment]
No C+, only Srikar.
