### ISSUE TITLE
Web - Attachment - Video "more options" tooltip starts with a lowercase letter

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50811]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with any account
3. Navigate to any 1:1 DM that has a video attachment
4. Start the video
5. Click on the "Fullscreen" button
6. Hover over the "..." button

## Expected Result:
It should be "More options".

## Actual Result:
Video "more options" tooltip starts with a lowercase letter.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e52e8735-f813-4975-a54b-e3039db17114
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment]
Hmm, I think this must be device specific. It's fine for me. Even if this was an issue though, I don't think it's really worth doing anything. This has no user impact. 

<img width="1508" alt="Screenshot 2024-10-15 at 4 43 28 PM" src="https://github.com/user-attachments/assets/afa406a1-5d00-41d7-9fd4-fbac2c1632d9">

**Comment by joekaufmanexpensify** [comment]
Closing for now.
