### ISSUE TITLE
Transaction with `South` showing in search as `:south`

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50833]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rayane-djouah 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729007590137319

## Action Performed:
Precondition: Have a workspace with multilevel tags
1. Submit a expense to the workspace with multilevel tags (e.g south) (Leave the level 1 of the tags empty and enter tag for level2)
2. Go to search and verify the expense
## Expected Result:
Should show only `south`
## Actual Result:
Showing as `:south`
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e3959599-d4f1-4577-a448-db6275a24a9d

![Snip - (4) New Expensify - Google Chrome](https://github.com/user-attachments/assets/22223c73-be4b-4333-a7f8-d11e3a68a7b2)

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment]
This is the expected behavior if the first tag level is missing and the second tag level is entered. It appears the same in Expensify Classic:

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/b2126422-92b0-4938-8dfa-ec649f48ad02">
