### ISSUE TITLE
[$250] Hybrid iOS - Push notification for failed scanning opens OD page with error instead of ND

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50840]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+zm27@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch hybrid app
2. Switch to ND
3. Go to workspace chat
4. Submit a scan expense with a receipt that will fail the scanning
5. Wait for the push notification from Expensify regarding the receipt
6. Open the push notification.

## Expected Result:
The push notification will open the transaction thread on hybrid ND because the expense is created on ND

## Actual Result:
The push notification opens home page on hybrid OD with the error "We were unable to open that violation, please fix it from your homepage"
On ND app (standalone app), the push notification opens LHN instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/dbda1b64-ed9a-45ce-9544-87a13eb6ebff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846318118960472710</li>
        <li>Upwork Job ID: 1846318118960472710</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kadiealexander** [comment]
I don't think this is an error worth investing massive amounts into fixing. If you disagree, please reopen!
