### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] Android - Hybrid app - Tags - Tapping a tag and quickly long press it shows "select" option in tag page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50851]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition: Enable tags in a workspace and create few tags

1. Launch app
2. Go to profile icon -- workspaces- workspace
3. Tap tags
4. Tap on a tag and quickly long press it
5. Keep long pressing it until you see select option(you will be navigated to next page but keep long pressing it)

## Expected Result:
Tapping a tag and quickly long press it must not show "select" option in tag page.

## Actual Result:
Tapping a tag and quickly long press it shows "select" option in tag page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/bef1eba7-26b7-4f3c-a317-d21e1ae2fe31

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850910440140150949</li>
        <li>Upwork Job ID: 1850910440140150949</li>
        <li>Last Price Increase: 2024-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104676565</li>
<li>Krishna2323 | Contributor | 104952564</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by IuliiaHerets** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by zanyrenney** [comment]
I'm not sure this is a real bug/

**Comment by zanyrenney** [comment]
@IuliiaHerets Can you clarify the "why" behind the expected result?

>must not show "select" option in tag page.

I am not familiar with the reasoning here and it doesn't seem like a real bug to me.

**Comment by IuliiaHerets** [comment]
@zanyrenney Seems that the actual/expected results are written a bit wrong, the ‘select’ option should be shown on the tag page, but it still shows when you quickly open the additional tag options
![image](https://github.com/user-attachments/assets/febec7d2-0997-4d38-b670-905639ff6e25)

**Comment by zanyrenney** [comment]
So you're not pressing anything to get that "select" bottom drawer appearing @IuliiaHerets ? it looks like you're pressing something from the screen recording.

**Comment by zanyrenney** [comment]
bump @IuliiaHerets please!

**Comment by IuliiaHerets** [comment]
@zanyrenney Yes, we long press on any tag (Select should appears) and then open this tag options (Select should disappear s, but don't)

**Comment by zanyrenney** [comment]
Got it - thank you for clarifying!

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Hybrid app - Tags - Tapping a tag and quickly long press it shows "select" option in tag page

### What is the root cause of that problem?
On pressing the list item it takes time to navigate to the detail tag setting page so if we quickly long press it will select it as we are not checking `isFocused` state in here
https://github.com/Expensify/App/blob/c3dde46202d2f48934ef7aa617d69c8b4c0b5ff6/src/components/SelectionListWithModal/index.tsx#L82
### What changes do you think we should make in order to solve the problem?

We should make sure the screen is focused
```
        if (!turnOnSelectionModeOnLongPress || !isSmallScreenWidth || item?.isDisabled || item?.isDisabledCheckbox || !isFocused) {

```
### What alternative solutions did you explore? (Optional)

**Comment by sobitneupane** [comment]
Thanks for the proposal @FitseTLT 

[Proposal](https://github.com/Expensify/App/issues/50851#issuecomment-2444564338) from @FitseTLT looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by Julesssss** [comment]
This probably wasn't worth solving. It's a minor issue and ended up causing a regression: https://github.com/Expensify/App/issues/52202

**Comment by Julesssss** [comment]
Hey @zanyrenney, when paying out could you please reduce payment because of the regression. Also can you pay a $50 reporting bonus to @Krishna2323 for locating the regression -- this was a deploy blocker we had to resolve quickly. Thanks

**Comment by Julesssss** [comment]
Hey again @zanyrenney, slight change. Can we please pay a $125 reporting/proposal bonus to @Krishna2323 as their solution was used to fix the bug introduced by this PR. So I think that would be: 

- @FitseTLT $125 - reduced due to regression
- @Krishna2323 $125 - located and shared fix for regression
- @sobitneupane $250 C+ review

**Comment by zanyrenney** [comment]
Sure thing.

**Comment by zanyrenney** [comment]
@Krishna2323

**Comment by zanyrenney** [comment]
i can make a bug reporting bonus issue manually, just checking they aren't paid via ND.

**Comment by zanyrenney** [comment]
thanks Krishna!

**Comment by zanyrenney** [comment]
**payment summary**

@FitseTLT $125 - reduced due to regression - new offer sent via upwork, due to reduced payment, please accept.
@Krishna2323 $125 - located and shared fix for regression - paid $125 via upwork.
@sobitneupane $250 C+ review - please request via ND.
