### ISSUE TITLE
[$250] [HOLD for payment 2024-12-09] [Per Diem] Frontend - Importing rates for Per Diem in Newdot

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#50863]
# Part of the _Add Per Diem to New Expensify_ project
Main issue: https://github.com/Expensify/Expensify/issues/400276
Doc section: https://docs.google.com/document/d/1c6WDOJlhvODD0mRKaCHfQk_HRNmq5K7hSDHLu06Pbq8/edit?tab=t.0#bookmark=id.v57hwv1fqs85
Project: https://github.com/Expensify/Expensify/issues/400276

# Feature Description
Add the necessary changes to import Per Diem rates in newdot workspaces

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866231379227094255</li>
        <li>Upwork Job ID: 1866231379227094255</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

**Comment by Gonals** [comment]
Not overdue

**Comment by mallenexpensify** [comment]
Contributor+: @c3024 is due $250 via NewDot. 


> Only @c3024 requires payment here. I will paid at the end of the project.

d'oh, saw this after inviting you to an Upwork job @shubham1206agra , plz ignore it. 

I'm assuming that test cases will be created as part of the larger project, comment or reopen if that's not correct @Gonals and @shubham1206agra

**Comment by JmillsExpensify** [comment]
$250 approved for @c3024
