### ISSUE TITLE
[HOLD for payment 2024-12-09] [Per Diem] Frontend - Exporting rates for Per Diem in Newdot

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#50865]
# Part of the _Add Per Diem to New Expensify_ project
Main issue: https://github.com/Expensify/Expensify/issues/400276
Doc section: https://docs.google.com/document/d/1c6WDOJlhvODD0mRKaCHfQk_HRNmq5K7hSDHLu06Pbq8/edit?tab=t.0#bookmark=id.ux1936zwlr4
Project: https://github.com/Expensify/Expensify/issues/400276

# Feature Description
Add the necessary changes to export Per Diem rates in newdot workspaces

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by Gonals** [comment]
Not overdue

**Comment by OfstadC** [comment]
@shubham1206agra verified [here](https://github.com/Expensify/App/issues/50865#issuecomment-2513478128) they will be issued payment outside of this issue & I see @c3024 has [recently been added](https://stackoverflowteams.com/c/expensify/questions/16949/16950#16950) to NewDot payments. So i've updated the [Payment Summary](https://github.com/Expensify/App/issues/50865#issuecomment-2527326445) 😃

**Comment by JmillsExpensify** [comment]
$250 approved for @c3024
