### ISSUE TITLE
[$250] Android-Chat-App becomes unresponsive after pasting specific content.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#50861]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when validating PR :** https://github.com/Expensify/App/pull/50427
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap on self DM
3. Paste the text -
!(https://d2k5nsl2zxldvw.cloudfront.net/images/animations/animation_setupguide.gif
)
4. Try to perform any action

## Expected Result:
App must not become unresponsive after pasting specific content.

## Actual Result:
App becomes unresponsive after pasting specific content.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/19bc234e-fda8-4f89-b8b1-676ba452efec

[Bug6636061_1729051848987!Crash.txt](https://github.com/user-attachments/files/17391923/Bug6636061_1729051848987.Crash.txt)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846693501093358297</li>
        <li>Upwork Job ID: 1846693501093358297</li>
        <li>Last Price Increase: 2024-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by slafortune** [comment]
Waiting on proposals
