### ISSUE TITLE
[$250] [HOLD for payment 2024-11-18] [Per Diem] Frontend - Enabling/Disabling Per Diem in Newdot

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#50862]
# Part of the _Add Per Diem to New Expensify_ project
Main issue: https://github.com/Expensify/Expensify/issues/400276
Doc section: https://docs.google.com/document/d/1c6WDOJlhvODD0mRKaCHfQk_HRNmq5K7hSDHLu06Pbq8/edit?tab=t.0#bookmark=id.yzkaku4zx0eq
Project: https://github.com/Expensify/Expensify/issues/400276

# Feature Description
Add the necessary changes to enable/disable Per Diem in newdot workspaces

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856534335985560931</li>
        <li>Upwork Job ID: 1856534335985560931</li>
        <li>Last Price Increase: 2024-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104872133</li>
<li>c3024 | Contributor | 104872134</li>
</ul></li>
    </ul>
</details>

**Comment by Gonals** [comment]
@shubham1206agra will be taking point on this issue, as he wrote the section of the design

**Comment by dubielzyk-expensify** [comment]
I think we should actually just reuse the Lottie animation we already have on the Search page for Expenses and Invoices:
![CleanShot 2024-10-21 at 11 49 12@2x](https://github.com/user-attachments/assets/75649263-e96e-4867-b394-5aa839a43272)

Potentially we could use the pink background color as described in the mocks. Or not sure if the design was meant to get a new illustration/animation. I'll let @Expensify/design chime in

**Comment by shawnborton** [comment]
Exactly, I think we can just reuse the existing pattern we have elsewhere as Jon mentions.

**Comment by shawnborton** [comment]
Here you go: [simple-illustration__perdiem.svg.zip](https://github.com/user-attachments/files/17457187/simple-illustration__perdiem.svg.zip)

**Comment by shawnborton** [comment]
We already have that in the repo: https://github.com/Expensify/App/blob/main/assets/images/calendar-solid.svg

**Comment by jliexpensify** [comment]
@shubham1206agra do you require payment here? I assume not, since you're working on the design doc?

**Comment by garrettmknight** [comment]
@shubham1206agra, does this also include the Spanish translations [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1729883701062839?thread_ts=1728941956.328469&cid=C06ML6X0W9L)?

**Comment by jliexpensify** [comment]
Thanks @shubham1206agra - @Gonals are we paying in this job?

**Comment by Gonals** [comment]
Yep, that seems accurate, as they reviewed the PRs

**Comment by jliexpensify** [comment]
Great, so here's a Pament Summary:

- @s77rt $250 (request in New.Dot)
- @c3024 $250 (paid via Upworks)

**Comment by jliexpensify** [comment]
No checklist right @shubham1206agra ?

**Comment by JmillsExpensify** [comment]
$250 approved for @s77rt

**Comment by jliexpensify** [comment]
Paid and job closed in Upworks!
