### ISSUE TITLE
[$4000][HOLD FOR PAYMENT] Workspace feeds doc

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50873]
The workspace feeds beta has been released from beta (https://github.com/Expensify/Expensify/issues/380605), and we agreed on a fixed reward for the project. It's been a long journey, and @DylanDylann and @allgandalf did a great job.

The total rewards are $4000 each, we agreed on that before the project started.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848729611216552354</li>
        <li>Upwork Job ID: 1848729611216552354</li>
        <li>Last Price Increase: 2024-10-22</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104537349</li>
<li>allgandalf | Contributor | 104537353</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by johncschuster** [comment]
Thanks, @mountiny! Do I need to wait the typical 7-day regression period, or am I good to issue payment on this right away?

**Comment by johncschuster** [comment]
I'm not too familiar with how we pay out projects, so I will defer to @mountiny on that.

**Comment by mountiny** [comment]
Correct no need to wait as we already had many prs merged. 

This can be paid out so probably just summarize the payments and then the c+ can request on newdot

**Comment by johncschuster** [comment]
# Payment Summary:

Contributor: @DylanDylann due $4000 via NewDot
Contributor: @allgandalf due $4000 via NewDot

**Comment by johncschuster** [comment]
Thank you for calling that out, @allgandalf! I'll get payment issued in Upwork right away!

**Comment by johncschuster** [comment]
@allgandalf has been paid via Upwork! 🎉 
@DylanDylann, can you please accept the offer I sent via Upwork?

**Comment by DylanDylann** [comment]
@johncschuster I did, thanks for handling this 🎉 🎉 🎉

**Comment by johncschuster** [comment]
This has been paid!
