### ISSUE TITLE
[HOLD for payment 2024-12-03] [$250] [Per Diem] Frontend - Add default category for Per Diem in Newdot

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#50871]
# Part of the _Add Per Diem to New Expensify_ project
Main issue: https://github.com/Expensify/Expensify/issues/400276
Doc section: https://docs.google.com/document/d/1c6WDOJlhvODD0mRKaCHfQk_HRNmq5K7hSDHLu06Pbq8/edit?tab=t.0#bookmark=id.4kv6q4at5wxd
Project: https://github.com/Expensify/Expensify/issues/400276

# Feature Description
Add the necessary changes to add a default category for Per Diem in newdot workspaces

# Manual Test Steps

# Automated Tests

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846484427769463383</li>
        <li>Upwork Job ID: 1846484427769463383</li>
        <li>Last Price Increase: 2024-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 105023085</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by 35C4n0r** [comment]
Is this still up for grabs?

**Comment by 35C4n0r** [comment]
Contributor details
Your Expensify account email: work.jaykumar@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ea92c79ab8974b5c

**Comment by 35C4n0r** [comment]
Contributor details
Your Expensify account email: [work.jaykumar@gmail.com](mailto:work.jaykumar@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01ea92c79ab8974b5c

**Comment by Gonals** [comment]
@shubham1206agra is assigned to this one 😁

**Comment by Gonals** [comment]
Not overdue

**Comment by c3024** [comment]
@Gonals , could you assign me to this issue as I am reviewing the PR?

**Comment by c3024** [comment]
This is a new feature and part implementation. This does not need a regression test.

**Comment by c3024** [comment]
@twisterdotcom this is ready for payment. Can you please post the payment summary so that I can request in ND?

**Comment by twisterdotcom** [comment]
Ah sorry, I misunderstood here. Payment Summary:

- @c3204 paid $250 via NewDot requests (Contributor)
- @shubham1206agra not paid here due to ongoing project.

**Comment by JmillsExpensify** [comment]
$250 approved for @c3024
