### ISSUE TITLE
Onboarding - User is not prompted to enter business name after selecting manage team expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#50880]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5083888
**Email or phone of affected tester (no customers):** nathanmulugetatesting+1795@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign up using a new gmail account
3. On the onboarding flow select "Manage my team's expense"

## Expected Result:
User is prompted to enter business name

## Actual Result:
User does not get shown a modal to enter business name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/89daab81-5f0c-4208-aa45-7f8af6080c42

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project.

**Comment by nkdengineer** [comment]
It's a new expectation [here](https://github.com/Expensify/App/issues/48745).

**Comment by anmurali** [comment]
This is not a bug. Although it sounds like we need to update regression tests for https://github.com/Expensify/App/issues/48189 cc @marcaaron
