### ISSUE TITLE
Rules - Disabled eReceipts toggle can't be enabled back

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50885]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.49-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+ds@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
As the admin of a USD Control workspace that has never enabled Rules in the past

1. Navigate to More Features in the workspace editor
2. Enable Rules
3. Navigate to the Rules page in WS editor
4. Disable eReceipt toggle
5. Try to Enable eReceipt toggle back

## Expected Result:
eReceipt toggle can be enabled back

## Actual Result:
eReceipt toggle can't be enabled back after it is disabled

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/687687f5-032d-4726-9c41-1f31dba01b77

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
This should be debugged in BE side. Afte changing currency of the policy in ND the eReceipt toggle (BE handling the eReceipt setting) will only work after the workspace page in the OD is reloaded. Quite Odd

**Comment by adelekennedy** [comment]
reproduced
