### ISSUE TITLE
[HOLD for payment 2024-11-01] [GR Phase 1] Create reusable “PushRowWithModal” component

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50895]
Design doc section: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.xg4d4oaa55we

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - expert contributor group. I’d like to work on this issue.

**Comment by madmax330** [comment]
Not overdue

**Comment by puneetlath** [comment]
Payment summary above is correct. @hungvu193 please request on NewDot. Thanks everyone!

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
