### ISSUE TITLE
[HOLD for payment 2024-11-26] [GR Phase 2] Step 2 Bank account details screen (without API calls)

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50898]
Design doc section: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.ka53nv4qgeyh

**Comment by pasyukevich** [comment]
Hi, I'm Eugene from Callstack - expert contributor group. I’d like to work on this issue.

**Comment by OfstadC** [comment]
@ishpaul777 - Offer sent in Upwork 😃

**Comment by OfstadC** [comment]
Paid! Thanks everyone 😃
