### ISSUE TITLE
[HOLD for payment 2024-11-20] [GR Phase 2] Step 3 Business info screen (without save API call)

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50899]
Design doc section: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.xfavl5zeoc0f

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment]
Update on my end. For now I've created draft PR. I'm expecting to create proper PR tomorrow. There might be some conflicts appearing soon. Apart from that I need to rebase it, test on all platforms and gather recordings.

**Comment by trjExpensify** [comment]
Confirming payments as follows: 

- $250 to @hungvu193 for the C+ review

Not moving forward with a regression test, as this is part of the global reimbursement project. When built overall, the project team should take care of handing over the suite of regression tests to Applause. 

Closing!

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
