### ISSUE TITLE
[HOLD for payment 2024-11-11] [GR Phase 1] Create reusable “UploadFile” component

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50894]
Design doc link: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=kix.u4ayheaipya1

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

I will take over as Eugene is still working on the AttachmentPicker and I've already finished my other phase 1 tasks.

**Comment by sonialiap** [comment]
Payment summary:
- @hungvu193 $250 please request in ND. Do we need a regression test here?

**Comment by hungvu193** [comment]
@sonialiap This feature isn't using anywhere at the moment. (Our next PR will use it). I don't think we need regression test for this issue.

**Comment by sonialiap** [comment]
Thanks, closing since there's nothing to test yet in a regression test

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
