### ISSUE TITLE
[HOLD for payment 2024-10-29] [GR Phase 1] Add a mechanism that allows DEVS and QAs ONLY to connect accounts that are non USD

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50892]
Design doc link: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.xwcvgphuxbt7

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by strepanier03** [comment]
This is a new feature so we don't need a reg test.

**Comment by strepanier03** [comment]
### Payment Summary

- [ ] $250 - @hungvu193 via manual request in New Expensify
- [x] @MrMuzyk is from an agency-contributor and not due payment

**Comment by strepanier03** [comment]
@hungvu193 payment summary is [here](https://github.com/Expensify/App/issues/50892#issuecomment-2448330448) feel free to put in the request in new expensify.

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
