### ISSUE TITLE
[HOLD for payment 2024-11-07] [GR Phase 2] Step 1 Select your country (without API calls)

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50897]
Design doc section: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.7hrzb93rzoog

**Comment by MrMuzyk** [comment]
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by abekkala** [comment]
### PAYMENT SUMMARY: 

- Fix: @MrMuzyk - CS: no payment needed
- PR Review: @hungvu193 [$250, paid via NewDot]

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
