### ISSUE TITLE
[$250] [HOLD for payment 2024-11-26] [GR Phase 2] Step 5 Director information screen (without API calls)

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50901]
Design doc section: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.damtu6jbu35v
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861373912773084057</li>
        <li>Upwork Job ID: 1861373912773084057</li>
        <li>Last Price Increase: 2024-11-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @brunovjk</details>

**Comment by zanyrenney** [comment]
Grrr this upwork job is not linked.

**Comment by zanyrenney** [comment]
Hyperlink goes to the GH issue.

**Comment by zanyrenney** [comment]
was trying to get the automation to work. @hungvu193 please can you apply to the job?

**Comment by zanyrenney** [comment]
### Payment Summary
[Upwork Job]()
- Contributor: @burczu is from an agency-contributor and not due payment
- Reviewer: @hungvu193 owed $250 via NewDot - please request via ND.

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
