### ISSUE TITLE
[HOLD for payment 2024-12-03] [GR Phase 2] Step 6 Agreements and finish screen (without API calls)

### ISSUE THREAD

**Issue by madmax330** [Expensify/App#50902]
Design doc section: https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.fj253dspq57x

**Comment by burczu** [comment]
Hi! I'm Bartek from Callstack - expert contributor group. I’d like to work on this task.

**Comment by joekaufmanexpensify** [comment]
Only payment here is $250 to @hungvu193 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment]
@hungvu193 please request payment here at your earliest convenience. Closing as this is otherwise all set!

**Comment by garrettmknight** [comment]
$250 approved for @hungvu193
