### ISSUE TITLE
[$250] Approver - On deleting add approval workflow, the 2nd approver in default workspace is removed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50923]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition: Keep workflow and add approvals enabled

1. Launch app
2. Tap profile icon -- workspaces -- workspace
3. Tap members - Invite 4 members
4. Navigate to workspace settings
5. Tap workflow
6. In default approval flow, add a user as 2nd approver and save
7. Add additional approval
8. Select different new user for all fields and save
9. Tap add workflow
10.Open the additional workflow
11. Tap delete

## Expected Result:
On deleting add approval workflow, the 2nd approver in default workspace must not be removed.

## Actual Result:
On deleting add approval workflow, the 2nd approver in default workspace is also removed.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ca4421e8-2f14-425f-9775-99e5fdd67937

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847102422067715236</li>
        <li>Upwork Job ID: 1847102422067715236</li>
        <li>Last Price Increase: 2024-10-18</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment]
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment]
BE issue
For second additional approval(for first approval workflow) the BE return empty `forwardsTo` value
![Screenshot 2024-10-18 at 00 09 10](https://github.com/user-attachments/assets/5226887e-c80e-49a9-a2ac-98d054eeb79d)

**Comment by ikevin127** [comment]
@kadiealexander Looks like this is a BE issue based on https://github.com/Expensify/App/issues/50923#issuecomment-2421608560 investigation -> therefore should go `Internal` in order to be fixed.

**Comment by kadiealexander** [comment]
Reassigning while I'm OOO for the next two weeks.

**Comment by garrettmknight** [comment]
Still awaiting a volunteer, this likely won't get prioritized until we have Control users in our focused cohorts.

**Comment by garrettmknight** [comment]
Same as above, dropping to weekly.

**Comment by garrettmknight** [comment]
Same as above

**Comment by garrettmknight** [comment]
Same as above

**Comment by kadiealexander** [comment]
@garrettmknight do you think we should close this for now?
