### ISSUE TITLE
[HOLD for payment 2024-11-14] [HOLD for payment 2024-10-29] Self-guided tours for onboarding (v1, 2, and 3)

### ISSUE THREAD

**Issue by zsgreenwald** [Expensify/App#50926]
Important Links:

- [Pre-design](https://expensify.slack.com/archives/C07HPDRELLD/p1725304220752679)
- [HL Design Doc](https://docs.google.com/document/d/1tiGgp0KvgZBrmQhk9qqwdJ5G6PvoccZpsZ0Ac3OaM08/edit#heading=h.mnjguil21u0a)
- Detailed Design Doc

# v1 - Empty state modal in Search
![image](https://github.com/user-attachments/assets/2b1e6843-be08-4ccc-97f1-d1942af87309)

`Take a tour` is selection-dependent on what they set during onboarding.
- Manage my team's expenses = https://expensify.navattic.com/kh204a7
- Track and budget expenses = https://expensify.navattic.com/35609gb
- Get paid back by my employer = https://expensify.navattic.com/35609gb
- Chat and split expenses with friends = https://expensify.navattic.com/35609gb
- Something else = https://expensify.navattic.com/35609gb

# v2 - Onboarding steps
Refer to this section of the design doc - https://docs.google.com/document/d/1tiGgp0KvgZBrmQhk9qqwdJ5G6PvoccZpsZ0Ac3OaM08/edit?tab=t.0#bookmark=id.3mskv927vhfg

# v3 - Global Create
Refer to this section of the design doc - https://docs.google.com/document/d/1tiGgp0KvgZBrmQhk9qqwdJ5G6PvoccZpsZ0Ac3OaM08/edit?tab=t.0#bookmark=id.hbgjtiwwmmw9

--------

Next steps:

- [x] Send our strategy@ email
- [x] Submit the HL for review
- [ ] Submit the Detailed for review

cc: @danielrvidal @anmurali 

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by zsgreenwald** [comment]
Last update ^

**Comment by zsgreenwald** [comment]
V2 and V3 are merged, waiting for the next deploy

**Comment by mountiny** [comment]
I think we can merge it before the next deploy occurs though

**Comment by danielrvidal** [comment]
I'm closing this as I think it's live. Checking with @mountiny to make sure but will reopen if needed.
