### ISSUE TITLE
[HOLD for payment 2024-11-13] Implement Google Tag Manager libs in NewDot

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#50938]
# Part of the Google Tag Manager - User activity tracking project
Main issue: https://github.com/Expensify/Expensify/issues/424142
Doc section: https://docs.google.com/document/d/1WMkZGrRcEDxlXKnQ3d96GIoRjd17ZnsmBey6sdVgGZ8/edit?tab=t.0#heading=h.kwkpf415jfsu

# Feature Description
1. [Implement the web lib](https://docs.google.com/document/d/1WMkZGrRcEDxlXKnQ3d96GIoRjd17ZnsmBey6sdVgGZ8/edit?tab=t.0#heading=h.kwkpf415jfsu)
2. ~~[Upgrade `react-native-firebase` in both NewDot and HybridApp](https://docs.google.com/document/d/1WMkZGrRcEDxlXKnQ3d96GIoRjd17ZnsmBey6sdVgGZ8/edit?tab=t.0#heading=h.722v45u2d5ou)~~
3. Implement the native lib

# Manual Test Steps
None

# Automated Tests
None

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by arosiclair** [comment]
Project is not CAP eligible and this an analytics feature so no design necessary

**Comment by arosiclair** [comment]
PR is code complete and testing well

**Comment by arosiclair** [comment]
Alright NewDot standalone looks good, but I'm running into some difficult issues with the HybridApp. The HybridApp new experience is crashing with the latest changes on `main` for me currently. I was able to make some progress configuring Firebase for iOS, but I need to fix these crashing issues first. I'm going to start a discussion about it next week.

**Comment by arosiclair** [comment]
There are issues with the HybridApp that can't be resolved easily so for now we're just implementing this for NewDot web and native. PR is out for review.

HybridApp follow up issue: https://github.com/Expensify/App/issues/51830

**Comment by allroundexperts** [comment]
Can someone please assign me this issue since I reviewed the PR? TY!

**Comment by arosiclair** [comment]
No regression steps needed for this issue. We'll add some when we add tracking in the next issue.

**Comment by JmillsExpensify** [comment]
$250 approved for @allroundexperts
