### ISSUE TITLE
Rules - Default amounts are set when enabling Rules

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50934]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.49-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5090142
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
As the admin of a USD Control workspace that has never enabled Rules in the past

1. Navigate to More Features in the workspace editor
2. Enable Rules
3. Navigate to the Rules page in WS editor

## Expected Result:
When rules are first enabled no default will be set for Require receipt amount, Max expense amount, and Max expense age

## Actual Result:
When rules are first enabled default is set for Require receipt amount, Max expense amount, and Max expense age

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<img width="1133" alt="Bug6636673_1729093025338!Screenshot_2024-10-16_at_6 35 12_in_the_evening" src="https://github.com/user-attachments/assets/67adc359-41cf-41af-92ef-0aeef36d062e">
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Rules - Default amounts are set when enabling Rules
### What is the root cause of that problem?
Those values is returned from backend in response of `UpgradeToCorporate` request.
### What changes do you think we should make in order to solve the problem?
Update this [successData](https://github.com/Expensify/App/blob/0b3569a4f68851c159ecaf06969a79cf73ff4041/src/libs/actions/Policy/Policy.ts#L3348C11-L3348C22) to below
```
    const successData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `policy_${policyID}`,
            value: {
                isPendingUpgrade: false,
                maxExpenseAge: CONST.POLICY.DEFAULT_MAX_EXPENSE_AGE,
                maxExpenseAmount: CONST.POLICY.DEFAULT_MAX_EXPENSE_AMOUNT,
                maxExpenseAmountNoReceipt: CONST.POLICY.DEFAULT_MAX_AMOUNT_NO_RECEIPT,
            },
        },
    ];
```

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Those values are default values; this seems expected for me.

**Comment by DylanDylann** [comment]
@marcaaron Could you help to confirm the expectation here?

**Comment by marcaaron** [comment]
Duplicate issue https://github.com/Expensify/App/issues/48387
