### ISSUE TITLE
[HOLD for payment 2024-11-11] [Search v2.5] [Autocomplete] Implement keyboard navigation for suggestions

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#50948]
See https://docs.google.com/document/d/1o-Hp-tK8Z_BAcE-KRiXQicPH04qNr525EIxlG8J4RxM/edit?tab=t.0#bookmark=id.pp1n1c15oy8k

**Comment by luacmartins** [comment]
We'll start working on it soon.

**Comment by luacmartins** [comment]
We're implementing a bunch of these autocomplete issues with a single PR, so I'll remove C+ assigned from all but one issue.

**Comment by luacmartins** [comment]
Closing in favor of https://github.com/Expensify/App/issues/50942, since payment will be processed there.
