### ISSUE TITLE
[Payment 2024-11-18] [Search v2.5] [Autocomplete] Implement the "from" and "to" autocomplete

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#50944]
See https://docs.google.com/document/d/1o-Hp-tK8Z_BAcE-KRiXQicPH04qNr525EIxlG8J4RxM/edit?tab=t.0#bookmark=id.fa4w31ihb3eg

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by luacmartins** [comment]
We'll start working on it soon.

**Comment by ikevin127** [comment]
> We'll start working on it soon.

**Comment by ikevin127** [comment]
> We'll start working on it soon.

**Comment by ikevin127** [comment]
@luacmartins Mind assigning a BZ team member here to complete payment ? Thank you!

**Comment by strepanier03** [comment]
New feature so we don't need a reg test for this one.

**Comment by strepanier03** [comment]
@ikevin127 - I have sent you an offer in Upwork, I'll check again later today to see if I can pay it.

**Comment by ikevin127** [comment]
@strepanier03 Offer accepted, thank you!

**Comment by yasirirfan-ai** [comment]
I will start working on it once my proposal is accepted

**Comment by yasirirfan-ai** [comment]
Contributor details
Your Expensify account email: yasirirfan117@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cca50c8858e3877d?mp_source=share

**Comment by ikevin127** [comment]
cc @strepanier03 for visibility as this was due on 18th

**Comment by strepanier03** [comment]
Just noting that today is the 18th for me.

**Comment by strepanier03** [comment]
I've paid out the contract for @ikevin127, closing out.
