### ISSUE TITLE
[HOLD for payment 2024-11-20] Add Google Tag Manager event tracking

### ISSUE THREAD

**Issue by arosiclair** [Expensify/App#50940]
- HELD on https://github.com/Expensify/App/issues/50938

# Part of the Google Tag Manager - User activity tracking project
- Main issue: https://github.com/Expensify/Expensify/issues/424142
- [Doc section](https://docs.google.com/document/d/1WMkZGrRcEDxlXKnQ3d96GIoRjd17ZnsmBey6sdVgGZ8/edit?tab=t.0#heading=h.n30u9eebqw5l)

# Feature Description
We're adding all of the GTM event tracking as described in the [NewDot Common section of the doc](https://docs.google.com/document/d/1WMkZGrRcEDxlXKnQ3d96GIoRjd17ZnsmBey6sdVgGZ8/edit?tab=t.0#heading=h.n30u9eebqw5l). 

# Manual Test Steps
[Manual Tests Steps doc](https://docs.google.com/document/d/1QdmE_8v_YhwVu-3dP-AZ-4oam7n7zr83r4N_ub8JnAs/edit?tab=t.0#heading=h.8y1lot1tiqfv)

# Automated Tests
Add a Jest unit test that mocks GoogleTagManager lib and verifies it is called correctly (correct params and only once) for each component/action we publish events from.

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by arosiclair** [comment]
Project is not CAP eligible and this an analytics feature so no design necessary

**Comment by trjExpensify** [comment]
Adding it to #convert.

**Comment by trjExpensify** [comment]
Still held.

**Comment by arosiclair** [comment]
@getusha did the C+ review for this issue. I'll link the regression test steps in a bit

**Comment by trjExpensify** [comment]
Great stuff, payment summary as follows: 

- $250 to @getusha for the C+ review 

Go ahead and request in NewDot. Closing!
