### ISSUE TITLE
[HOLD for payment 2024-11-11] [Search v2.5] [Autocomplete] Implement the taxRate autocomplete

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#50942]
See https://docs.google.com/document/d/1o-Hp-tK8Z_BAcE-KRiXQicPH04qNr525EIxlG8J4RxM/edit?tab=t.0#bookmark=id.fmtbdipnnvpc

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by johncschuster** [comment]
Bumping for Melvin

**Comment by ikevin127** [comment]
* [x] [@ikevin127] Please propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the new feature will work correctly on production in further releases.

### Regression Test Proposal

1. Open Search page's `Search` input (click top-right search icon) and test the following autocomplete keys: `category`, `tag`, `taxRate`, `type`, `expenseType`, `card`, `from`, `to`, `status`, and `currency`.
2. Verify that when category, tag or currency keys are working the way [#51237 (comment)](https://github.com/Expensify/App/pull/51237#issuecomment-2430179534) specified.
3. Verify that after clearing the input or a single autocomplete key, the autocomplete suggestions are cleared.
4. Verify that after clicking on a autocomplete suggestion, it is added to text input.

Do we agree 👍 or 👎.

**Comment by johncschuster** [comment]
Payment Summary:

Contributor+: @ikevin127 paid $250 via [Upwork](https://www.upwork.com/nx/wm/offer/104770558) (after regression window has passed)

Upwork job [here](https://www.upwork.com/jobs/~021854183452785661012)! Please apply

**Comment by ikevin127** [comment]
cc @johncschuster as this is labeled `Weekly` which might cause it to slip your radar for today.

**Comment by lakchote** [comment]
Put this as `Daily` for reason mentioned above ^

**Comment by johncschuster** [comment]
Thank you for updating the label! I'm looking at this now!

**Comment by johncschuster** [comment]
Payment has been issued! Thanks, @ikevin127 for your contributions! 🎉
