### ISSUE TITLE
[HOLD for payment 2024-11-18] [Search v2.5] [Autocomplete] Implement the "in" autocomplete

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#50943]
See https://docs.google.com/document/d/1o-Hp-tK8Z_BAcE-KRiXQicPH04qNr525EIxlG8J4RxM/edit?tab=t.0#bookmark=id.12hnqjn49rnl

**Comment by luacmartins** [comment]
We'll start working on it soon.

**Comment by lakchote** [comment]
> We'll start working on it soon.

Same.

**Comment by sonialiap** [comment]
Looks like there were some things that were updated later but there weren't any regressions, is that correct @lakchote @luacmartins? Payment only for rayane-djouah for this PR, correct?

**Comment by lakchote** [comment]
> Looks like there were some things that were updated later but there weren't any regressions, is that correct @lakchote @luacmartins? Payment only for rayane-djouah for this PR, correct?

That's correct @sonialiap, payment only for @rayane-djouah in this PR as a C+ reviewer. Minor issues were found but no regressions, they will be solved in a follow up PR by @Kicu.

**Comment by sonialiap** [comment]
Thanks Lucien!

**Comment by sonialiap** [comment]
paid ✔️ 
no regression steps ✔️ https://github.com/Expensify/App/issues/50943#issuecomment-2480145974
