### ISSUE TITLE
User cannot view the Concierge chat if they click on the #admins chat and vice versa

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50950]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** needs reproductions
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @maddylewis 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729018667310579

## Action Performed:

1. They go to new Expensify and start a thread with Concierge.
2. Then they click on their #admins room chat (or any other chat)
3. The Concierge thread disappears
4. To get back to the Concierge thread they click on the browser back button.
5. They are back to the Concierge chat but the #admin chat disappears.
6. If they click on the "Chat with your Account Manager here" link, it sends them to the chat with their AM, but then they cannot view both the Concierge chat or the #admins chat.

## Expected Result:
Their chats should remain on the LHN for them to access.
## Actual Result:
The chat vanishes when they click to a different chat in the LHN
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/464e9bfd-3a45-40bd-8dfd-34c84d82618d

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by truph01** [comment]
@maddylewis I think it is expected behavior, as I see in the video, you are in focus mode and the concierge chat is not pinned. As a result, it is disappeared once you visit another chat.

**Comment by maddylewis** [comment]
@truph01 - oh, good to know!! so the solution here is to simply turn off `Focus Mode`, then?

**Comment by maddylewis** [comment]
@truph01 - ahhh interesting. okay, so if focus mode is enabled AND a chat isn't pinned, it's expected behavior for the chat to disappear upon clicking into another chat.

**Comment by maddylewis** [comment]
we're good to close this out as expected behavior 👍
