### ISSUE TITLE
[HOLD for payment 2024-10-29] [$125] The Smartlimit description is always cut off

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#50959]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729070184832209

## Action Performed:

1. Have a workspace with expensify cards set up as well as approvers
2. Try to create a new card
3. Proceed up to "Choose a limit type"

## Expected Result:
Should be wrapped in 2 lines
## Actual Result:
the smart limit option is trimmed even on web with the largest RHP option
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (3)](https://github.com/user-attachments/assets/ac227203-777d-42fe-a666-72900689cffc)
![Snip - (53) New Expensify - Google Chrome](https://github.com/user-attachments/assets/f767fe6c-7804-4cbd-8f8b-0c3817f2eabd)

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846797861964749988</li>
        <li>Upwork Job ID: 1846797861964749988</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104458329</li>
<li>daledah | Contributor | 104458330</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by mountiny** [comment]
Minor change! @allgandalf can you please review?

**Comment by mountiny** [comment]
@allgandalf kind bump

**Comment by mountiny** [comment]
I dont think we need a specific regression test for this minor thing, thank you for recommending

**Comment by mallenexpensify** [comment]
Contributor: @daledah  paid $125 via Upwork
Contributor+: @allgandalf paid @125 via Upwork. 

I [created a test case cuz QA](https://github.com/Expensify/Expensify/issues/442053) does monthly runs for design and edge case issues. I added this text to it
- This should either be a monthly test or closed if you you don't think it's worth even checking monthly for

Thanks!
