### ISSUE TITLE
[HOLD for payment 2024-10-30] [Search v2.5][Autocomplete] [App] Create the autocomplete parser

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#50951]
Implement [this section](https://docs.google.com/document/d/1o-Hp-tK8Z_BAcE-KRiXQicPH04qNr525EIxlG8J4RxM/edit?tab=t.0#bookmark=id.6d9qy48jgoxk) of the design doc

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by 289Adam289** [comment]
Hi! I'm Adam from SWM, an expert agency, and I'd like to work on this issue.

**Comment by greg-schroeder** [comment]
PR is merged

**Comment by greg-schroeder** [comment]
Okay this was implemented by SM and reviewed internally, so I'm going to close.
