### ISSUE TITLE
[$250] [HOLD for payment 2024-10-29] [Search v2.4] Remove search router button from the RHP report screen

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#50963]
Coming from [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1729111663012689), we should remove the magnifying glass button from the report header when the report is opened in the RHP

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851329801599655574</li>
        <li>Upwork Job ID: 1851329801599655574</li>
        <li>Last Price Increase: 2024-10-29</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 104649685</li>
</ul></li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
@rayane-djouah let me know when you accept the offer and I'll pay it out.

**Comment by garrettmknight** [comment]
Paid!
