### ISSUE TITLE
[$250] Search - Missing translations for "Search" modal in Spanish

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50978]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
PreCond: App language is in Spanish
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Tap CMD + K
4. Scroll down on the Search modal

## Expected Result:
User expects everything to be translated to Spanish

## Actual Result:
The filters and things like "Track your Expense" are showing in English

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/8115c836-0713-4d08-bd56-a95b84e57220
 </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849836084822280137</li>
        <li>Upwork Job ID: 1849836084822280137</li>
        <li>Last Price Increase: 2024-10-25</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 104641555</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by lakchote** [comment]
Not a blocker it's missing translations.

**Comment by lakchote** [comment]
cc @luacmartins for your input

**Comment by Kicu** [comment]
Exactly what @rayane-djouah said: keywords like `type`, `status` I don't see how we could translate - they are part of Search grammar.
Perhaps the values like `expense`, `chat` maybe we could translate... but it's still tricky because I'm assuming we couldn't send the translated values to backend.

However displaying different display values to user in the query, but sending untranslated values to backend would be technically possible but will require refactoring how we store the query.
So possibly we could look into this in (or after) 2.5.

**Comment by luacmartins** [comment]
I agree that the queries are not translated. It seems like we translate the Chat results subtitle/last message if they are a system message, so maybe we can apply the same logic here for the chat results only
![Screenshot 2024-10-17 at 9 25 38 AM](https://github.com/user-attachments/assets/c5d532c3-be6a-488c-8034-9a4b08927216)

**Comment by greg-schroeder** [comment]
Marking `Internal`

**Comment by ChavdaSachin** [comment]
The concierge chat not translated here in video was actually an onboarding task,
and we currently do not translate onboarding tasks.
I have made a proposal [here](https://github.com/Expensify/App/issues/51215#issuecomment-2428302382) to translate onboarding tasks as well, and in that case this issue also would be solved.

**Comment by greg-schroeder** [comment]
Can you confirm @luacmartins @lakchote ?

**Comment by lakchote** [comment]
> Can you confirm @luacmartins @lakchote ?

The problem doesn't pertains to the translation of onboarding tasks, it's related to Search's chat results as a whole.

We need to translate them, if they are a system message.

Regarding the logic @luacmartins I've found it:
[Example #1 ](https://github.com/Expensify/App/blob/lucien/qbo-xero-report-fields/src/libs/SidebarUtils.ts#L612-L643)
[Example #2]( https://github.com/Expensify/App/blob/lucien/qbo-xero-report-fields/src/libs/SidebarUtils.ts#L459-L491) (implementation)

**Comment by luacmartins** [comment]
Agreed, I had left a comment about it [here](https://github.com/Expensify/App/issues/50978#issuecomment-2419857839)

**Comment by luacmartins** [comment]
I think this can be external though.

**Comment by Kicu** [comment]
@shubham1206agra right now I'm focusing on autocomplete features, mainly: https://github.com/Expensify/App/issues/50976 and https://github.com/Expensify/App/issues/50944 + https://github.com/Expensify/App/issues/50943

So at least for the next 2-3 days Im busy. Can take a look after this is done

**Comment by lakchote** [comment]
This is not urgent @Kicu. 

I'm assigning you to work on it when you'll be able to. The autocomplete PRs are more important.

**Comment by Kicu** [comment]
thanks @lakchote in case someone else on our end has free time then we will ask them to grab this instead.

**Comment by SzymczakJ** [comment]
I've investigated it and the Chat results subtitles/last messages that are system messages that are translated in Chat tab are also translated on SearchRouter.
So [this comment](https://github.com/Expensify/App/issues/50978#issuecomment-2419857839) is technically resolved.
<img width="959" alt="Screenshot 2024-10-30 at 14 44 09" src="https://github.com/user-attachments/assets/9c546223-a352-4e3a-a93f-f0d03fffca87">
Do we need to do anything else?

**Comment by luacmartins** [comment]
Thanks for investigating this. No, I think that was the only pending thing on this issue, so we're good to close. Thank you all!
