### ISSUE TITLE
Search - "No category" is no longer selected in Categories field after searching with filter

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50989]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50122
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click Filters.
4. Click Categories and select one category and save it.
5. Click View results.
6. Click Filters.
7. Note that the selected category in Step 4 is displayed in Categories field.
8. Repeat Step 1 to 7 by selecting "No category" in Step 4.
9. Note that after searching with "No category" filter, the selected "No category" is not displayed in Categories field in Filters page.

## Expected Result:
"No category" will be displayed as selected in Categories field after searching with that filter.

## Actual Result:
"No category" is no longer selected in Categories field after searching with that filter.

The same with `tags` filters

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f1e74311-f0b8-478f-a445-ccf771278d99

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Kicu** [comment]
I believe this may be a bug after this PR: https://github.com/Expensify/App/pull/50122 
@luacmartins can you take a look? I didn't know we support "No category" option.

**Comment by techievivek** [comment]
I think we can demote this for now as the impact is low.

**Comment by 289Adam289** [comment]
Hi! I can handle this in https://github.com/Expensify/App/pull/50883. Fix requires minimal effort and I don't think it's worth opening another pr.

**Comment by 289Adam289** [comment]
I didn't noticed but pr adding `no category` and `no tags` has been reverted in https://github.com/Expensify/App/pull/51015 so no fix needed.

**Comment by luacmartins** [comment]
Correct, the PR was reverted. Closing this issue.
