### ISSUE TITLE
[HOLD for payment 2024-11-29] [Regression] [$125] Search - Onboarding is dismissed after using search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50981]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Login with a new user
2. When the Onboarding page is shown press on cmd + k
3. Click on self chat (you)

## Expected Result:
Onboarding is not dismissed

## Actual Result:
Onboarding is dismissed and chat is opened.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/7a00a3dd-5875-412b-b3f4-52220fefdbd9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846862688780448155</li>
        <li>Upwork Job ID: 1846862688780448155</li>
        <li>Last Price Increase: 2024-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104562576</li>
<li>daledah | Contributor | 104562577</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stitesExpensify</details>

**Comment by IuliiaHerets** [comment]
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Anaslancer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding is dismissed and chat is opened.

### What is the root cause of that problem?
Seems like there is no logic for checking function if user selected one option at the onboarding modal or not, before opening the Chat Finder modal (Ctrl + K).
But your team made the logic for Esc button at [here](https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L324).

### What changes do you think we should make in order to solve the problem?
We should make the logic in [here](https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L357).
We can use this value, isOnboardingCompleted for checking.


### What alternative solutions did you explore? (Optional)
We should add this logic for the New Chat modal (Ctrl + Shift + K) at [here](https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L369).

**Comment by Anaslancer** [comment]
> we shouldn't open search modal only when onboarding flow is not completed.

I think this is the best workflow;
when onboarding flow is not completed, -> the modal shouldn't be opened.
when onboarding flow is completed, -> the modal should be opened.
We can use **isOnboardingCompleted** for this case.
so the callback function will have this code;
```
if (!isOnboardingCompleted) {
    return;
}
```

**Comment by Anaslancer** [comment]
@dukenv0307 Yes, It works fine on my side after adding the logic

**Comment by Anaslancer** [comment]
@dukenv0307 No, Just add the above 3 line into [here](https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L357). That's it.

**Comment by Anaslancer** [comment]
@dukenv0307 It's just for the Ctrl+K dialog, we should fix for the Ctrl+Shift+K modal as well.

**Comment by Anaslancer** [comment]
@dukenv0307 Sorry, I found the other way. Please just add these lines at [here](https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L357).
```
if (modal.current.disableDismissOnEscape) {
    return;
}
```
This logic is for ESC key but it's same for Ctrl+K and Ctrl+Shift+K

**Comment by Anaslancer** [comment]
https://github.com/user-attachments/assets/342e1064-1227-45b3-b5ac-0983a0a7628e

**Comment by Anaslancer** [comment]
@dukenv0307 Do you have a chance to check my solution?

**Comment by Anaslancer** [comment]
As I mentioned about `modal.current.disableDismissOnEscape`, this variable is set at here,
https://github.com/Expensify/App/blob/62302d5cacb2ff307b2e3a2bfc267a858a79bb4d/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L529-L541
So I think we can use this `modal.current.disableDismissOnEscape`.

**Comment by Anaslancer** [comment]
@dukenv0307 If you prefer `isOnboardingCompleted`, we can use this code.
```
        const unsubscribeSearchShortcut = KeyboardShortcut.subscribe(
            searchShortcutConfig.shortcutKey,
            () => {
                const [isOnboardingCompleted] = useOnyx(ONYXKEYS.NVP_ONBOARDING, {
                    selector: hasCompletedGuidedSetupFlowSelector,
                });

                isOnboardingCompleted && Session.checkIfActionIsAllowed(() => {
                    toggleSearchRouter();
                })();
            },
            shortcutsOverviewShortcutConfig.descriptionKey,
            shortcutsOverviewShortcutConfig.modifiers,
            true,
        );

```

**Comment by Anaslancer** [comment]
@dukenv0307 I've separated the `useEffect` function.
```
    useEffect(() => {
        if (!isOnboardingCompleted) {
            return;
        }

        const shortcutsOverviewShortcutConfig = CONST.KEYBOARD_SHORTCUTS.SHORTCUTS;
        const searchShortcutConfig = CONST.KEYBOARD_SHORTCUTS.SEARCH;
        
        // Listen for the key K being pressed so that focus can be given to
        // Search Router, or new group chat
        // based on the key modifiers pressed and the operating system
        const unsubscribeSearchShortcut = KeyboardShortcut.subscribe(
            searchShortcutConfig.shortcutKey,
            () => {
                Session.checkIfActionIsAllowed(() => {
                    toggleSearchRouter();
                })();
            },
            shortcutsOverviewShortcutConfig.descriptionKey,
            shortcutsOverviewShortcutConfig.modifiers,
            true,
        );

        return () => {
            unsubscribeSearchShortcut();
            Session.cleanupSession();
        };
    }, [isOnboardingCompleted]);
```
And I removed the `unsubscribeSearchShortcut` function from the original `useEffect` function.
It works fine as expect. Please check on your side. Thanks.

**Comment by Anaslancer** [comment]
@stitesExpensify Did you have a change to review my proposal?

**Comment by stitesExpensify** [comment]
Hi @Anaslancer, I decided to go with the recommendation of the C+ who had already picked a solution. I appreciate your effort and hope to see you on some more issues in the future!

**Comment by Anaslancer** [comment]
Hi @stitesExpensify I will find the other issues. Thanks

**Comment by iwiznia** [comment]
This caused a [regression](https://github.com/Expensify/App/pull/51547#issuecomment-2463196946)

**Comment by sonialiap** [comment]
Thanks Ioni

**Comment by sonialiap** [comment]
@daledah @dukenv0307 holding payment until we figure out if there was a regression and if there was, a fix is made :)

**Comment by sonialiap** [comment]
Payment summary:
Due to regression, decreasing the payment from 250 to 125
- @dukenv0307 $125, please complete the [checklist](https://github.com/Expensify/App/issues/50981#issuecomment-2494679354) - payment via ND
- @daledah $125 paid via upwork ✔️

**Comment by sonialiap** [comment]
@dukenv0307 bumping for the checklist https://github.com/Expensify/App/issues/50981#issuecomment-2494679354

**Comment by stitesExpensify** [comment]
Not overdue, waiting on @dukenv0307

**Comment by sonialiap** [comment]
Thanks @dukenv0307!

**Comment by JmillsExpensify** [comment]
$125 approved for @dukenv0307
