### ISSUE TITLE
Search - Console error shows up when entering emoji in search input

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50988]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open a report.
3. Click on the search icon.
4. Enter an emoji.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up when entering emoji in search input.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
[1710.log](https://github.com/user-attachments/files/17409294/1710.log)

https://github.com/user-attachments/assets/eacbef29-d5b2-4076-8e69-95b7e92f9b4e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
New feature, and this is also a minor issue. cc @luacmartins in case you'd like to take this.

**Comment by 289Adam289** [comment]
This issue will be fixed by https://github.com/Expensify/App/pull/50883

**Comment by Julesssss** [comment]
> This issue will be fixed by #50883

Issue should be resolved.

**Comment by Julesssss** [comment]
LGMT, closing

![Screenshot 2024-11-11 at 16 14 40](https://github.com/user-attachments/assets/ed6d1385-ff17-4f52-8d0b-f9238b8eafde)
