### ISSUE TITLE
mWeb Search - Device back button navigates to previous Chrome site instead of closing Search

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50982]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open chat.
3. Tap on the search icon.
4. Tap device back navigation button (not back button).

## Expected Result:
Search modal will close when tapping device back navigation button.

## Actual Result:
Search modal does not close when tapping device back navigation button.
When tapping on the device back button again, instead of returning to LHN, Chrome browser will open the previous website.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6081ef70-7f0d-4ac9-9d87-c249d18442f6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by Kicu** [comment]
I will take a look at this, most likely the solution is to use the existing property `shouldHandleNavigationBack` in `Modal`

@luacmartins please assign me

**Comment by Kicu** [comment]
Fix ready in PR

**Comment by puneetlath** [comment]
Thanks for fixing! This was CP'd, so I'll go ahead and close this out.

**Comment by luacmartins** [comment]
Confirmed the fix on staging
