### ISSUE TITLE
Search - Search doesn't show expenses when applied tag filters

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50984]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0. 50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50122
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a workspace chat which has tags enabled and created
3. Create few expenses with and without tags
4. Navigate to search filters
5. Tap tags - no tag and view the results
6. Tap tags
7. Select no tag and few tags on which expense created and view results

## Expected Result:
Search must show expenses when applied tag filters.

## Actual Result:
Search doesn't show expenses when applied tag filters.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/a78ffbe3-5c42-4f4e-a6a9-da27c952496c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mjasikowski** [comment]
checking

**Comment by mjasikowski** [comment]
Still checking, need to recompile auth, as I'm running into problems

**Comment by mjasikowski** [comment]
confirmed backend problem, trying to create a fix PR now

**Comment by mjasikowski** [comment]
unable to quickly create a fix, will revert the App PR for now

**Comment by mjasikowski** [comment]
CP request sent
