### ISSUE TITLE
mWeb - Search - No offline indicator at the bottom of the page in Search modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50986]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Open FAB > Start chat.
4. Note that there is offline indicator below the search input and also at the bottom of the page.
5. Open a report.
6. Tap on the search icon.

## Expected Result:
There will be offline indicator at the bottom of the page just like Start chat list in Step 4.

## Actual Result:
There is no offline indicator at the bottom of the page in Search modal.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/060cae1b-17f2-4775-8041-6d7dfe9d1df4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment]
Do we need an indicator at the bottom? It literally says you are offline right below the input:
![CleanShot 2024-10-17 at 12 00 08@2x](https://github.com/user-attachments/assets/5b65bfba-6dd3-4388-bf86-3e45e1cdf825)

**Comment by twisterdotcom** [comment]
@IuliiaHerets - was this a testrail case? If so, let's get that changed. If not, let's ignore. Setting to weekly. We can close once you've answered.

**Comment by dannymcclain** [comment]
I agree we don't need an indicator at the bottom since we have one right below the search field. @shawnborton do you think we should add the offline icon there and treat that lock up similar to the one we show at the bottom?

**Comment by shawnborton** [comment]
I don't feel too strongly. I could see that, but I am also fine leaving this one as-is because it's being treated consistently like other messages we show below the search input:
![CleanShot 2024-10-17 at 16 17 25@2x](https://github.com/user-attachments/assets/4033d773-0dc8-4012-8a07-76f253b429be)

Happy to defer to you (and Jon) on that one!

**Comment by luacmartins** [comment]
Sounds good. @IuliiaHerets Let's just confirm if this is a TC and either remove it or close this issue.

**Comment by IuliiaHerets** [comment]
@twisterdotcom @luacmartins It is an exploratory issue, not a TR.

**Comment by luacmartins** [comment]
Cool, so we can close this.

**Comment by dubielzyk-expensify** [comment]
I think I prefer the icon there, but I prefer the alignment of the text on the right.
