### ISSUE TITLE
[HOLD for payment 2024-10-29] Search - Contacts with no chat history are also categorized under "Recent chats"

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50998]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new private domain account (Expensifail).
3. Open FAB > Start chat.
4. Note that the contacts under "Recent chats" are only Concierge and yourself.
5. Open Concierge.
6. Click Search icon.
7. Note that Recent chats include all the contacts instead of just Concierge and yourself.

## Expected Result:
In Search modal, "Recent chats" should only include Concierge and self DM, while the other contacts should be under "Contacts" section.

## Actual Result:
In Search modal, "Recent chats" includes Concierge, self DM and the rest of the contacts which user has never chatted with before.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3b121b99-19e9-4fdf-94b8-07609215388f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by MariaHCD** [comment]
This doesn't need to block the deploy. It can be a follow up improvement as part of the Search project.

**Comment by shawnborton** [comment]
Hmm I would think we would only show actual recent chats in the recent chats section. No need to show Contacts here IMO.

**Comment by dannymcclain** [comment]
>Hmm I would think we would only show actual recent chats in the recent chats section. No need to show Contacts here IMO.

Same—IMO the options we display in the router are "quick shortcuts". We're surfacing them for convenience. If you're looking for a contact you can use the router to search for it.

**Comment by SzymczakJ** [comment]
The only place to view your contacts that I knew about was ChatFinderPage. If we're going to remove contacts from SearchRouter how else will we view them? @dannymcclain @shawnborton

**Comment by shawnborton** [comment]
I don't think anyone is suggesting to remove contacts from the SearchRouter. But the default "suggestions" perhaps should only include Recent chats, if that makes sense.

**Comment by SzymczakJ** [comment]
I like that solution 😃. So to finally clarify: if user hasn't put anything in the text input then we only show recent chats, but when user typed something we show whatever is closest to the searched phrase(just like ChatFinderPage did)?

**Comment by shawnborton** [comment]
Yeah, that is my understanding! cc @luacmartins for the gut check there too

**Comment by dannymcclain** [comment]
Yes that's what I was thinking too!

**Comment by luacmartins** [comment]
That seems fine to me as well.

**Comment by luacmartins** [comment]
Waiting on payment @VictoriaExpensify

**Comment by VictoriaExpensify** [comment]
I don't think anyone needs to be paid here - @SzymczakJ  is a contractor and everyone else is internal. If I've missed someone that needs payment, let me know!

Otherwise, we are just waiting for the checklist to be complete and we can close this out
