### ISSUE TITLE
Speed up the reassure test suite

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50994]
### Problem
We’ve identified excessive [logging](https://github.com/Expensify/App/actions/runs/11329328366/job/31504613318#step:7:167) during Reassure performance test runs which is caused by several warnings and errors that do not make the tests fail. However, this extra output increases the execution time in CI, making our testing process less efficient.

### Solution
Remove all unnecessary console.error logs by addressing the specific issues listed above. This will reduce excessive logging and improve test execution time in CI. Migrate from the measurePerformance to the measureRender API to take advantage of the latest features in the Reassure library for more accurate and efficient render measurement.

Examples of errors and how to fix them:
- Error: The measurePerformance function has been renamed to measureRender. The old measurePerformance name is now outdated and will be removed in future versions. Fix: Migrate all instances of measurePerformance to measureRender.
- Warning: An update to ReportScreen inside a test was not wrapped in act(...). Fix: Wrap the update in waitFor() to ensure the test waits for the state updates properly.
- Error: The 'navigation' object hasn't been set up yet. This can happen if you don’t have a navigator mounted or if the navigator isn’t fully loaded. Fix: Add missing navigation mocks to the tests to ensure the navigation object is initialized before use.
- Warning: An update to OptionRow inside a test was not wrapped in act(...). Fix: Similar to ReportScreen, wrap the update in waitFor() to fix this issue.

**Comment by OlimpiaZurek** [comment]
Hi. I'm Olimpia from Callstack and I'd like to work on this issue.

**Comment by mountiny** [comment]
this was merged without c+ review so I think we can close it now
