### ISSUE TITLE
[HOLD for payment 2024-11-20] [Simple AA in NewDot] Submit to category and tag approvers

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#51001]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/430318

## Action Performed:
1. Create Control policy, with "Manual" scheduled submit, with Advanced Approvals enabled
2. Submitter `submitsTo` policy owner
3. Approver A set as Category Approver for Category `CAT_APPROVER`
4. Submitter creates expense in workspace chat w/ Category `CAT_APPROVER`
5. Submitter submits report

## Expected Result:
Next manager (approver) should be Approver A

## Actual Result:
Error, since we try to submit the report to policy owner (submitter's `submitsTo`)

## Solution Guideline
In [PolicyUtils.getSubmitToAccountID](https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/libs/PolicyUtils.ts#L517), for policies on CONST.POLICY.APPROVAL_MODE.ADVANCED`, we currently assume that we should submit to `employee.submitsTo ?? defaultApprover`.

However, in OldDot you'll notice that we actually want to submit the report to the category or tag approver before considering the submitter's `submitsTo`.

So we can either update `getSubmitToAccountID` to account for those additional approvers (assuming no other related regressions) OR we might have to create a new function for getting the "next submitter" in this case - the assigned contrib should evaluate existing uses of `getSubmitToAccountID` before determining which solution to follow

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by nkdengineer** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error, since we try to submit the report to policy owner (submitter's submitsTo)

### What is the root cause of that problem?

This is a new feature request.

### What changes do you think we should make in order to solve the problem?
All places where we're using `getSubmitToAccountID` function are getting the `submitsTo` for an expense report then I think we can update the `getSubmitToAccountID` to cover the addition approver rule case.

1. We can change `employeeAccountID` param to `expenseReport` and we will replace all use of `employeeAccountID` in this function to `expenseReport.ownerAccountID`

https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/libs/PolicyUtils.ts#L517

2. If the advanced workflow is enabled we will get the details of the first transaction of `expenseReport`. I think the first transaction will decide which user the the `submitsTo` of this expense.

3. Getting the approver for the category/tag of the transaction (if category/tag isn't empty)  by using the same function here


https://github.com/Expensify/App/blob/987ff1b536f2144e5fd492c6d2d2aa621d68442f/src/pages/workspace/categories/CategorySettingsPage.tsx#L83

If the approver exists we should return this approver otherwise return `employee.submitsTo ?? defaultApprover`
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment]
Updated proposal.

Add example implementation.

**Comment by Beamanator** [comment]
Thanks for the proposal @nkdengineer !

> I think the first transaction will decide which user the the submitsTo of this expense.

FYI this isn't quite true, it depends on the first transaction with a matching category or tag approver 🙏

**Comment by nkdengineer** [comment]
@Beamanator I updated.

**Comment by Beamanator** [comment]
Ok amazing 👍  this is looking great, but i have one more annoying need:
- In your solution, we look at each transaction 1 by 1, and if a transaction has EITHER category or tag approver, we go with what we fine (prioritizing category 👍 )
- What I need is: To prioritize category approvers in ANY transaction, THEN (if there's no matching category approvers), look for tag approvers 🙏

**Comment by nkdengineer** [comment]
@Beamanator So that means if we have 3 transactions, 2nd transaction matched the tag approver and 3rd transaction matched category approver we will choose category approver, right?

**Comment by Beamanator** [comment]
Yes exactly correct @nkdengineer 👍 🙏

**Comment by nkdengineer** [comment]
@Beamanator Updated with this expectation.

**Comment by nkdengineer** [comment]
@Beamanator Updated my proposal with the expectation.

**Comment by Beamanator** [comment]
Overall I think that looks good, we can iron out exact details in the PR 👍 

Though I also want to mention, we should make sure that submitting works offline (optimistically) as well! So we will want to test that this sets the correct Onyx data in that case (it might already) 👍 

Also @suneox mind giving ^ ideas a preview before we hire?

**Comment by suneox** [comment]
> Overall I think that looks good, we can iron out exact details in the PR 👍
> 
> Though I also want to mention, we should make sure that submitting works offline (optimistically) as well! So we will want to test that this sets the correct Onyx data in that case (it might already) 👍
> 
> Also @suneox mind giving ^ ideas a preview before we hire?

@Beamanator Yes, overall the solution looks good. I’m just a bit concerned about the priority case the category has approved, but I think we can proceed with @nkdengineer solution, and we’ll double-check it in the PR.

**Comment by Beamanator** [comment]
@nkdengineer when you will start this PR? 🙏

**Comment by nkdengineer** [comment]
I'm investigating locally will open this today.

**Comment by suneox** [comment]
@MelvinBot Not overdue, we are still working on the PR
> I’m just a bit concerned about the priority case the category has approved

@nkdengineer just a note for you regarding the case of looking for the next approver when the category has been approved

**Comment by nkdengineer** [comment]
> the category has been approved 

@suneox I don't understand what you mean here.

**Comment by nkdengineer** [comment]
@suneox The PR is [here](https://github.com/Expensify/App/pull/51196).

**Comment by suneox** [comment]
> > the category has been approved
> 
> @suneox I don't understand what you mean here.

Ah, that means in the case where an expense includes both Category and Tag, with different approvers, the priority will always be given to the Category approver first. (We need to check if this case works as expected or fail due to the priority being given to the Tag approver instead)

**Comment by suneox** [comment]
> @suneox The PR is [here](https://github.com/Expensify/App/pull/51196).

I’ll start reviewing your PR in a few hours and check the use case I mentioned above.

**Comment by nkdengineer** [comment]
> Ah, that means in the case where an expense includes both Category and Tag, with different approvers, the priority will always be given to the Category approver first. (We need to check if this case works as expected or fail due to the priority being given to the Tag approver instead)

Yeah, I always give the Category approver first.

**Comment by Beamanator** [comment]
Yes it's expected that the category approver should be prioritized 👍

**Comment by OfstadC** [comment]
@suneox Please complete BZ checklist prior to payment date. Thank you 😃

**Comment by suneox** [comment]
@OfstadC The payment is not ready. Could you please send us an offer? Thank you!​

**Comment by OfstadC** [comment]
[Upwork job](https://www.upwork.com/ab/applicants/1859297152871529317/job-details)

## Payment Summary 

- @suneox [pending offer in Upwork](https://www.upwork.com/nx/wm/offer/104993219)
- @nkdengineer [pending offer in Upwork](https://www.upwork.com/nx/wm/offer/104993242)

**Comment by OfstadC** [comment]
Payments issued 😃
