### ISSUE TITLE
Merchant is auto-populated with "Expense" when submitting expense after split expense in room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51007]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a room.
3. Add a member to the room.
4. Split an expense without merchant in the room.
5. Go to any DM.
6. Submit an expense to the user without merchant.
7. Go to transaction thread.

## Expected Result:
The merchant field will be empty.

## Actual Result:
The merchant field is auto-populated with Expense when submitting expense after splitting expense in room.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/097bf92a-b658-408c-94d4-f5c64f7933d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment]
The problem seems to be that in prod we send the merchant as `(none)` and in staging we are sending empty, then our default merchant is `Expense`, let try to find the PR that did this change.

**Comment by rlinoz** [comment]
being fixed here: https://github.com/Expensify/App/pull/51040

**Comment by kavimuru** [comment]
Bug is fixed. 

https://github.com/user-attachments/assets/d0bab00f-da47-47c4-9220-a54bb8f115f8

**Comment by rlinoz** [comment]
Removing deploy blocker and closing.
