### ISSUE TITLE
Search - "Invite a friend, get [amount]$" banner is not displayed on Search page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51004]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5091856
**Email or phone of affected tester (no customers):** applausetester+shsb22co1122233@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in to new dot with any account
2. Press ctrl + k to open the search page
3. Check the bottom of the user list

## Expected Result:
There's a banner in the user list that says "Invite a friend, get [amount]$"

## Actual Result:
There's no banner in the user list that says "Invite a friend, get [amount]$"

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/22a76b69-b94c-4787-a045-b3ecde33474b

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment]
TY! Closing
