### ISSUE TITLE
[HOLD for payment 2024-11-01] [$250] Book travel - Search icon is present on Company address RHP

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51009]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Company address in Book travel is not set up.

1. Go to staging.new.expensify.com
2. Go to FAB > Book travel.
3. Click Book travel.

## Expected Result:
Search icon will not show up on Company address RHP (because this icon is not seen on any RHP across the app, except report RHP in Search).

## Actual Result:
Search icon is present on Company address RHP,

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d09b3cfe-41b7-4459-92f1-f8008fbb2283

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846954023671497945</li>
        <li>Upwork Job ID: 1846954023671497945</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104471544</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by Kicu** [comment]
@rayane-djouah won't this be also solved by your https://github.com/Expensify/App/pull/50964?

I seem to remember that in total we have 3 "header" components that cover every single header in the App. So perhaps correct check for RHP would also fix this one?

**Comment by johnmlee101** [comment]
I think the proposal looks good, I'll @mollfpr also chime in

**Comment by mollfpr** [comment]
Agree, the proposal looks good to me!

**Comment by luacmartins** [comment]
IMO we can demote this to NAB. It was caused by https://github.com/Expensify/App/pull/49984, so I think we should let the original authors work on a fix.

**Comment by johnmlee101** [comment]
Ah okay, @Kicu can you take over on fixing this?

**Comment by Kicu** [comment]
yeah no problemo I will fix it today, according to this comment from @rayane-djouah 
https://github.com/Expensify/App/issues/51009#issuecomment-2419989351

**Comment by jliexpensify** [comment]
Is this correct?

- C: @Kicu (Agency)
- C+: @rayane-djouah $250 (owed via Upworks)

@mollfpr you didn't work on this issue, correct?

**Comment by mollfpr** [comment]
Yes, no work from me.

**Comment by jliexpensify** [comment]
Paid and job closed!
