### ISSUE TITLE
[$250] Hybrid app- New app window opens when logging in via magic link with 2FA set up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51013]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.50.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5095575
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: existing account with 2FA enabled
1. Open Hybrid app
2. Tap on Continue with Email
3. Enter email of account from precondition and tap Next
4. Navigate to email app and tap on magic link

## Expected Result:
Hybrid app should open and 2FA code page should be displayed.

## Actual Result:
Hybrid app is opened, but "Welcome!" log in page is shown.
If you background the app you can notice that magic link opened new app window, and there 2FA code page is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/99085584-1273-41ca-b6ff-1dba5c333257

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861417782229114311</li>
        <li>Upwork Job ID: 1861417782229114311</li>
        <li>Last Price Increase: 2024-12-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by muttmuure** [comment]
Not overdue

**Comment by muttmuure** [comment]
Not reproducible

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 9.0.58-1

https://github.com/user-attachments/assets/da1aaf53-b489-4f98-b0f1-fc7627a626fa

Issue reproduce with account without 2FA setup, in this scenario the new app window is auto focused but if you background the app you can notice the previous window is still there


https://github.com/user-attachments/assets/c8af58a3-921a-4810-afbe-48488548bc6a

**Comment by muttmuure** [comment]
Not overdue

**Comment by muttmuure** [comment]
Will add to CRITICAL

**Comment by muttmuure** [comment]
cc @Julesssss @staszekscp

**Comment by muttmuure** [comment]
I think that we will deprecate the new app soon, which will preclude the need for this issue

**Comment by technfusion** [comment]
[#51013.docx](https://github.com/user-attachments/files/17925201/51013.docx)
Hello, 

Attached is the document that provides solutions for the aforementioned bugs. Please review it. 

Thank you.

**Comment by staszekscp** [comment]
Hey there! Could you test if the issue persists? I think it should be solved here: https://github.com/Expensify/Mobile-Expensify/pull/13288

**Comment by muttmuure** [comment]
Added retest label

**Comment by muttmuure** [comment]
Not overdue

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)
