### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Scan Receipts-When adding scan receipts back to back user is asked to fill Merchant field

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51029]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5091787
**Issue reported by:** Applause - Internal Team

## Action Performed:
1.Log in the app as a WS employee
2.Go to the WS chat and click plus
3. Select Submit expense
4. In the Right Hand Modal(RHM) select Scan
5. Choose a file from the device and click Submit expense
6. Repeat one more time steps 2-6

## Expected Result:
User is able to submit back to back scan expenses

## Actual Result:
When submitting a second Scanned expense, the user can see the preview of the receipt in the Right Hand Modal, but is asked to fill in the Merchant field, as in manual expense. Basically, the RHN displays the Manual expense modal instead of the Scan Modal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4ea41af4-17ab-48a6-8a18-1ae4404cb2c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846931377957155675</li>
        <li>Upwork Job ID: 1846931377957155675</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>dominictb | Reviewer | 104466552</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by lanitochka17** [comment]
Production:

https://github.com/user-attachments/assets/c5312327-9ea7-4419-9cac-5575b9ccfcc3

**Comment by Nodebrute** [comment]
Regression from https://github.com/Expensify/App/pull/50772

cc: @bernhardoj

**Comment by bondydaa** [comment]
looks like it is related, https://github.com/Expensify/App/pull/50772#issuecomment-2419862210. taking off help wanted since @bernhardoj will fix.

**Comment by bernhardoj** [comment]
👋

**Comment by kavimuru** [comment]
Bug is fixed 

Uploading Recording #2055.mp4…
