### ISSUE TITLE
[HOLD for payment 2024-11-01] [Search] [Saved Searches] Do not render tooltip more than once

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#51027]
After having discussed it with @JmillsExpensify, we should not display the saved searches tooltip more than once.

Because:
- once is enough for training purposes
- the three dots pattern is already well-known 

Example of what's expected:

1. I save a search for the first time
2. I delete it
3. I resave another search
4. I should not see the tooltip displayed again

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by luacmartins** [comment]
@lakchote can we instead of deleting the saved search nvp in the DB just set it to an empty object? that way we can cehck for the presence of the nvp

**Comment by lakchote** [comment]
> @lakchote can we instead of deleting the saved search nvp in the DB just set it to an empty object? that way we can cehck for the presence of the nvp

Good idea. That's what I've done, PRs are in review for both the backend and frontend.

**Comment by JmillsExpensify** [comment]
Doesn't look like any payment is due, so I'm going to close this one out.

**Comment by mananjadhav** [comment]
@JmillsExpensify I had helped with the PR review on this one. Can you please help with the payout summary on this one?

**Comment by JmillsExpensify** [comment]
Ah thanks, I see that in the PRs so thanks for raising.

**Comment by JmillsExpensify** [comment]
Payment summary: $250 to @mananjadhav for PR testing and review.

**Comment by garrettmknight** [comment]
$250 approved for @mananjadhav
