### ISSUE TITLE
LHN- There is no LHN for sub task report with GBR

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51031]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisites: User A assigned sub task for user B
1. Navigate to https://www.staging.new.expensify.com/
2. Log in as user B
3. Navigate to the conversation with user A

## Expected Result:
As their is an assigned sub task LHN should show subtask with GBR on conversation report

## Actual Result:
There is no LHN for sub task report with GBR

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/921a22bd-be53-466d-87b1-a522455608f3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
This is expected as GBR is suppose to be shown in the chat report level instead of the task report level if the assignee can access to the chat report that the task belongs to. https://github.com/Expensify/App/pull/43927
