### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Track expense - Edited amount is not reflected correctly in amount editor on confirmation page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51030]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM.
3. Track a $10 expense.
4. Go to transaction thread.
5. Change the amount to $20 (important).
6. Go back to main chat and click Submit it to someone from the whisper.
7. Select a user.
8. Click Amount on the confirmation page.
9. Change the amount to $30 and save it.
10. Click Amount.

## Expected Result:
The amount will remain the same, which is $30.

## Actual Result:
The amount is $20, while it shows $30 on the confirmation page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/29c581a1-214a-462b-a91a-3cbfe5530c2f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848821552702222159</li>
        <li>Upwork Job ID: 1848821552702222159</li>
        <li>Last Price Increase: 2024-10-22</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 104618078</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by IuliiaHerets** [comment]
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track expense - Edited amount is not reflected correctly in amount editor on confirmation page

### What is the root cause of that problem?
We are taking the modifiedAmount from the trackExpense when we create draft transaction on submit it to someone
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/ReportUtils.ts#L8037-L8046
### What changes do you think we should make in order to solve the problem?

We need to reset modifiedAmount on the draft transaction 
```

        currency,
        modifiedAmount: undefined,
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment]
Only added detail on the [RCA](https://github.com/Expensify/App/issues/51030#issuecomment-2419909038)

**Comment by puneetlath** [comment]
@FitseTLT has been paid. 

@ntdiary waiting for the checklist for you.

**Comment by puneetlath** [comment]
Payment summary: 
- C - $250 - @FitseTLT - paid via Upwork
- C+ - $250 - @ntdiary - to be paid via NewDot

Thanks everyone!
