### ISSUE TITLE
Web - Thread - Messages are displayed when joining a thread while the user is offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51046]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** T
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5083411&group_by=cases:section_id&group_order=asc&group_id=291937
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Navigate to a conversation
3. Start a thread and send some messages
4. Disable the internet connection
5. Click on the header menu and click "Leave"
6. Navigate back to the parent conversation
7. Click on the thread link to rejoin the thread

## Expected Result:
A skeleton loader is displayed since the user is offline

## Actual Result:
No skeleton loader is displayed, and user can see the messages while offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d71ee7d7-7cde-493d-a511-f5334869355a

![Bug6635113_1728988849485!Leave_thread_and_re-join__offline__2](https://github.com/user-attachments/assets/5dda3054-d696-4ea1-b6de-5d08a5c28872)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment]
I think this is expected.
