### ISSUE TITLE
Compose Box - After create a room task user is not redirected to task conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51052]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5083367&group_by=cases:section_id&group_order=asc&group_id=291936
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Loggin on macOS app
2. Navigate to a Room Chat that has 2 or more participants
3. Click on the + in the compose box and select "Assign task"
4. Enter a title only, leave description blank
5 Do not select assignee
6. Create the task

## Expected Result:
After the user creates a task he/she should be redirected to the task conversation

## Actual Result:
After the user creates a task he/she is redirected to room conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a21e105a-596e-4d88-903e-2b7f53278d12

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CyberAndrii** [comment]
Will have the same fix as in https://github.com/Expensify/App/issues/51047

**Comment by puneetlath** [comment]
Hmm, this feels expected. I don't think we need to do anything here.
