### ISSUE TITLE
IOS - Hybrid app - App crashed when logout offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51062]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5094453
**Email or phone of affected tester (no customers):** rybkina+101724b@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch App as login user
2. Go to offline
3. Navigate to setting > Sign Out
4. Tap on Sign Out on popup "Are you sure?"

## Expected Result:
User should log out

## Actual Result:
App crashed when logout offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4eabf402-fbd5-435a-9cc0-bd52a0e8c143

![21-1](https://github.com/user-attachments/assets/abda8b63-1527-42a7-b315-43cb4230376a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment]
Production: 

https://github.com/user-attachments/assets/6cf7e6bd-2f94-4896-83e3-a97482b17cf2

**Comment by marcaaron** [comment]
Asked for more information [here](https://expensify.slack.com/archives/C9YU7BX5M/p1729198533532029). Please post device logs whenever creating issues with crashes that are consistently reproducible (and whether it is consistently reproducible).

**Comment by kavimuru** [comment]
Device logs 
[Expensify-2024-10-17-173006.txt](https://github.com/user-attachments/files/17423816/Expensify-2024-10-17-173006.txt)

**Comment by marcaaron** [comment]
Based on the logs this looks like some kind of null pointer reference issue similar to what we have [here](https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/ios:com.expensify.expensifylite/issues/ab92c21364963bd24e5a4173c2ed9023?time=last-seven-days&types=crash&versions=9.0.50%20(9.0.50.6);9.0.50%20(9.0.50.3);9.0.50%20(9.0.50.5)). 

It's unclear what the root cause might be to me. Seems related to trying to clear out a view or some kind of data. @Julesssss @AndrewGable might know more.

**Comment by marcaaron** [comment]
>App crashed when logout offline

Also this only happens when offline? If so, not sure if it needs to be a blocker.

**Comment by Julesssss** [comment]
Agree with both of your points. It seems likely that firebase crash IS this crash, adding a comment in Firebase linking it to this issue would be helpful.

**Comment by marcaaron** [comment]
Added a comment to firebase. 

I think the next step for this issue would be to try and build HybridApp locally then sign out while offline to see if it's reproducible. I have not yet had success in building HybridApp locally will start a thread to get some help there.

**Comment by marcaaron** [comment]
AFAICT this is what gets called when we sign out: 

https://github.com/Expensify/App/blob/bab932cb085523abcf7e6efc5e6d9de2345dd87d/src/libs/actions/Session/index.ts#L211C1-L214C10 

Which then calls the native module here:

https://github.com/Expensify/Mobile-Expensify/blob/44f91cc30683a0edd9b7468acbff52e7be8c0c07/iOS/Expensify/HybridAppModule.swift#L13C1-L17C6

Ok, managed to build the app and I cannot reproduce this one locally. Gonna make it a weekly for now and let's give it a re-test after the next deploy.

**Comment by mateuuszzzzz** [comment]
Hi @marcaaron I'm currently working on this crash. I noticed that after enabling bridgeless mode on HybridApp(iOS only) we stopped to see those crashes in Crashlytics. Bridgeless was introduced in [9.0.54.1](https://github.com/Expensify/Mobile-Expensify/commits/9.0.54.1?author=WoLewicki) and last crash was on 9.0.53.1
