### ISSUE TITLE
Android - Rules - Unable to enter values after deleting them

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51074]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50.5
**Reproducible in staging?:**  Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app and log in
2. Create a workspace
3. Navigate to More feature and enable rules by upgrading to Control
4. Open the Rules option
5. Select the Receipt required amount or Max expense amount options
6. Delete the default value
7. Start entering a new value

## Expected Result:
User is able to enter a new value

## Actual Result:
Nothing happens when user tries entering a new value
Only reproducible on Pixel 6 / Android 15

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f62a71cf-0131-4718-83e5-1587d5a74d4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment]
I was unable to repro.
