### ISSUE TITLE
[$250] [HOLD for payment 2024-11-01] Search - Down caret icon and search icon are close to each other

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51077]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-4
**Reproducible in staging?:**  Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+zm37@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Start chat.
3. Select a user with long name.
4. Submit an expense to the user.
5. Make sure that user name and expense amount are long enough to reach the search icon on the expense report header.
6. Go to expense report.

## Expected Result:
There will be spacing between the down caret and search icon on the expense report header.

## Actual Result:
The down caret and search icon are very close to each other.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6638169_1729198209607!IMG_5549](https://github.com/user-attachments/assets/b2bff2df-bae6-40b8-8ee2-627a25305862)

https://github.com/user-attachments/assets/80f0fe63-4c57-4bf5-b7e7-cfd090a82da3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021853588853114817182</li>
        <li>Upwork Job ID: 1853588853114817182</li>
        <li>Last Price Increase: 2024-11-05</li>
    </ul>
</details>

**Comment by SzymczakJ** [comment]
This is a small visual bug and I don't think it deserves a Deploy Blocker label. @luacmartins 
I'd like to fix it since I implemented Search 2.4.

**Comment by MonilBhavsar** [comment]
Thank you! Agree, this is not really a blocker.
I will assign you to this issue

**Comment by MonilBhavsar** [comment]
Assigning @rayane-djouah as a C+ following the main PR

**Comment by Kicu** [comment]
Will provide for this, please assign me

**Comment by Kicu** [comment]
fix in PR ready to check

**Comment by mallenexpensify** [comment]
@rayane-djouah can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021853588853114817182

**Comment by incognito-root** [comment]
**Proposed Solution:**
Will implement:
1. Add appropriate left margin to search icon for consistent spacing between icons
2. Enable text wrapping for username and amount when they exceed available width

This will ensure proper spacing while maintaining functionality across all platforms.

### Testing Plan
Will verify:
1. Username/amount display:
   - Short text (spacing maintained)  
   - Long text (proper wrapping)
2. All required platforms:
   - iOS/Android (Standalone, HybridApp, mWeb)
   - MacOS (Chrome/Safari, Desktop)
3. Various screen sizes

### Timeline
Expected PR in 1 day

**Comment by MonilBhavsar** [comment]
The PR https://github.com/Expensify/App/pull/51081 fixed two bugs and looks like C+ payment was issued in other issue

**Comment by incognito-root** [comment]
Contributor details
Your Expensify account email: ayaan.work5@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135886d7cf9ca15ac

**Comment by MonilBhavsar** [comment]
Thanks!
