### ISSUE TITLE
NewExpensify Stuck on 'Update Required' Message Despite Refresh and Update Attempts

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51088]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:** Needs Reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @zanyrenney 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729158805892819

## Action Performed:

1. Head to [staging.new.expensify.com](http://staging.new.expensify.com/)
2. See update screen
3. Refresh / press update
4. Remains inaccessible

## Expected Result:
Updates applied and user able to proceed further
## Actual Result:
Stuck in update page and loops
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

https://github.com/user-attachments/assets/53c2cf6e-5f5f-4c0c-aa2e-ef3c9de63c14

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
Asked for more detail in Slack.

**Comment by puneetlath** [comment]
Looks like this is a dupe and has been fixed in https://github.com/Expensify/App/pull/51207
