### ISSUE TITLE
App icon on Old Expensify don't support dark mode

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51087]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50.6
**Reproducible in staging?:** Yes
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dubielzyk-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729202799742179

## Action Performed:
1. Find Old Expensify on your homescreen
2. Change to dark mode
## Expected Result:
See the Old Expensify icon change to be dark mode compliant
## Actual Result:
Icon still has white background color
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

![image](https://github.com/user-attachments/assets/0595a949-9ffe-460a-9b73-77caf2a9b8f0)

![image (1)](https://github.com/user-attachments/assets/4684fab2-c3ba-42b9-9603-5ffc808869bf)

  https://github.com/user-attachments/assets/0dd7d5c8-dae4-499f-b1c2-a2095ec97e3c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment]
Hey @dubielzyk-expensify can you remind me what we need to do here? The linked thread doesn't contain your solution. Which I think is to provide a dark mode icon for OldDot?

**Comment by dubielzyk-expensify** [comment]
According to [their documentation](https://developer.apple.com/design/human-interface-guidelines/app-icons) we need to provide a dark mode asset. Light mode and tinted mode is working well already so here's the dark mode variations:

[app_icons_dark.zip](https://github.com/user-attachments/files/17469830/app_icons_dark.zip)

That should give us this look on mobile: 
![image](https://github.com/user-attachments/assets/58ade79f-f40e-4a6a-a10b-65676d54906b)


cc @Expensify/design

**Comment by shawnborton** [comment]
Looks good to me 👍

**Comment by shawnborton** [comment]
Rounded edges would be expected.

**Comment by dubielzyk-expensify** [comment]
Ahh, I just used a Figma file I found. My bad! I'll fix

**Comment by dubielzyk-expensify** [comment]
Here's another go :D 
[app-icons.zip](https://github.com/user-attachments/files/17474528/app-icons.zip)

**Comment by Julesssss** [comment]
@dubielzyk-expensify can I get `Dark - App Store.png` at 1024x1024 please? 

![Screenshot 2024-10-23 at 12 11 56](https://github.com/user-attachments/assets/99be582d-dc68-4ef4-9bd3-a865727c7742)

**Comment by dubielzyk-expensify** [comment]
Yes sir 🫡

[Dark - App Store.png.zip](https://github.com/user-attachments/files/17500593/Dark.-.App.Store.png.zip)

**Comment by Julesssss** [comment]
Reopening as this wasn't fully implemented. I created a new PR that supports light, dark, and tinted icons [here](https://github.com/Expensify/Mobile-Expensify/pull/13311).

**Comment by dannymcclain** [comment]
>Should we use the same single shade for themed icons? (to match the NewDot logo)

My 2 cents is a big yes to this. I think the ND one looks way better IMO.

**Comment by dubielzyk-expensify** [comment]
Agree with big yes. Now there'll be no way to differentiate them though. I've made a white version which means the tint will apply fully. We could do a gradient or something else here or even have the outer rings be a bit more faded. Here's a few variations.

![CleanShot 2024-12-04 at 13 51 01@2x](https://github.com/user-attachments/assets/0fb84b07-aa0b-41d5-90b1-537dfeb54941)


If we just want white, then use these: 
[tinted-icon.zip](https://github.com/user-attachments/files/18002323/tinted-icon.zip)

**Comment by shawnborton** [comment]
My vote would be to go flat, since we don't use gradients really anywhere in our brand system.

**Comment by dannymcclain** [comment]
Agree with flat! I actually also really like the faded outer ring version, but since we're going to be delisting "New Expensify" soon I think it makes sense to just go flat as that most closely represents the latest and greatest iteration of our iconmark. (Jon also knew Shawn and I were going to say flat which is why he went ahead and included the files for that one 🤣)

**Comment by dubielzyk-expensify** [comment]
> (Jon also knew Shawn and I were going to say flat which is why he went ahead and included the files for that one 🤣)

😂 ❤️

> but could you please share a 1024x1024 asset? I could only see up to 512x512. FYI, as of iOS 18, we now only need to provide a single asset, which is automatically resized.
Here you go: 
[Tinted - App Store.png.zip](https://github.com/user-attachments/files/18015674/Tinted.-.App.Store.png.zip)

**Comment by Julesssss** [comment]
Thanks all

![Screenshot 2024-12-05 at 10 32 21](https://github.com/user-attachments/assets/3495b48c-9d6c-43b2-bfc6-348e625b6b0a)

**Comment by dubielzyk-expensify** [comment]
Awesome work Jules!
