### ISSUE TITLE
Hybrid app - 30 sec countdown not shown for request a new magic code

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51084]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5094653
**Email or phone of affected tester (no customers):** applausetester+101724fish@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to the login page
2. On the email field, enter an email of a existing user

## Expected Result:
There's a timer in the enter magic code step and 30 sec countdown should show for request a new magic code.

## Actual Result:
30 sec countdown not shown for request a new magic code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/82388869-a28f-47fc-9794-faa6a901e884

 
</details>

**Comment by izarutskaya** [comment]
Production 

https://github.com/user-attachments/assets/c4ca25de-2753-4c3c-9930-f2741029a5a4

**Comment by trjExpensify** [comment]
Hm, I don't think we have the countdown on OldApp do we? Asking in thread [here](https://expensify.slack.com/archives/C07HPDRELLD/p1729255243183329?thread_ts=1728999565.505529&cid=C07HPDRELLD).

**Comment by Julesssss** [comment]
Yeah, we don't do this in HybridApp.
