### ISSUE TITLE
Hybrid app - Android -  Launch - App crashed every time when it is closed and relaunched

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51116]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Kill the app.
3. Relaunch the Expensify app.
4. Verify the app is opened and loaded properly.

## Expected Result:
The app should be opened and loaded correctly everytime the user launches it.

## Actual Result:
When the user kills the app and re launches it, a "Uh oh, something went wrong" message is displayed and it has to be refreshed to be used properly.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[1910.txt](https://github.com/user-attachments/files/17445287/1910.txt)

https://github.com/user-attachments/assets/ee06bc84-8988-463c-80d5-040cc7ca4933

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by AndrewGable** [comment]
Confirmed this is fixed

**Comment by AndrewGable** [comment]
Haha sorry - Wrong issue!

**Comment by yuwenmemon** [comment]
Closing https://expensify.slack.com/archives/C9YU7BX5M/p1729557218232369?thread_ts=1729554748.866629&cid=C9YU7BX5M
