### ISSUE TITLE
Search - Search does not return results when searching for users using custom display name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51119]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Open DM with any user with custom display name.
3. Send a message.
4. Click on the search icon.
5. Search for the same user using custom display neme.

## Expected Result:
Search will display DM results (production behavior).

## Actual Result:
Search does not display DM results.
Search also does not display the relevant results when searching for users with no prior chat in the private domain (they show up on production).
This issue only happens when searching for user using custom display name.
On Expensifail private domain, the issue does not happen when searching for users that are near the top of the list, but happens for users at the bottom of the list.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3e693c88-a428-4be6-a8d4-338c85031dd0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
This is expected. We only support email and account IDs for now. Autocomplete will solve this issue once it’s developed in Search v2.5.
