### ISSUE TITLE
QBD - Error message shows "..... try again later later." when connection fails

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51120]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Accounting.
3. Click Connect next to Quickbooks Desktop.
4. Without setting up, click Done.

## Expected Result:
The error message will show "..... try again later."

## Actual Result:
The error message will show "..... try again later later."
The same message is also seen in #admins.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a0fa8817-633f-4f4a-8f48-049e12cb5fd9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment]
@muttmuure  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment]
@IuliiaHerets, sorry to bother. What's the correct error message that we should display? Thank you.

**Comment by Shahidullah-Muffakir** [comment]
The backend is sending is the wrong message for `GetMissingOnyxMessages` api call.
<img width="1440" alt="Screenshot 2024-10-19 at 9 56 13 PM" src="https://github.com/user-attachments/assets/17a2879d-7f1c-4ccd-9856-f542ca28f412">

**Comment by lakchote** [comment]
PR is under review.

**Comment by lakchote** [comment]
PR has been merged and deployed. Closing the issue.
