### ISSUE TITLE
Task - Task name doesn´t change in search section when edited

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51126]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5099789&group_by=cases:section_id&group_order=asc&group_id=291936
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open any chat.
3. Click on the "+" button.
4. Click on "Assign Task"
5. Add a title to the new task and save it.
6. Click on "Search" on the bottom of the screen.
7. Click on the dropdown menu and select "Chat"
8. Click on the just created task.
9. Once redirected to chat, open the Task and change it´s name.
10. Click on the arrow on the top left corner to return to "Search"
11. Verify the task name is now updated.

## Expected Result:
After editing the task name, the new one should be displayed in search section.

## Actual Result:
Task name is not updated in search section once the user edits it.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c10ed829-7bea-499a-8f3a-17c375ceaf6e

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment]
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment]
> Once redirected to chat, open the Task and change its name.

Caused a crash and was kicked out. Now I can't get back in. 

![image](https://github.com/user-attachments/assets/d5da8d02-c496-44b6-80e9-3ff5173914e3)

Will attempt triage again tomorrow.

**Comment by RachCHopkins** [comment]
Ok, yes, repro'd this. It doesn't update the original in the search > chat at all.

**Comment by RachCHopkins** [comment]
Checking in [Slack](https://expensify.slack.com/archives/C05LX9D6E07/p1729744694320469).

**Comment by RachCHopkins** [comment]
Closing based on internal instruction.
