### ISSUE TITLE
[HOLD for payment 2024-11-11] [$250] Invoices - Invoice preview sender appears and disappears when sending invoices consecutively

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51128]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5102388
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Send invoices.
3. Send an invoice to anyone.
4. In the invoice chat, click + > Send invoice.
5. Send another invoice.

## Expected Result:
The invoice preview sender will not appear and disappear when sending invoices consecutively.

## Actual Result:
The invoice preview sender appears then disappears when sending invoices consecutively.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e4d15c1c-5317-4af3-8558-2308e62cc7cf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848369344890325291</li>
        <li>Upwork Job ID: 1848369344890325291</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104579791</li>
<li>NJ-2020 | Contributor | 104579793</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by IuliiaHerets** [comment]
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by chiragsalian** [comment]
LGTM, feel free to create the PR @NJ-2020

**Comment by abekkala** [comment]
### PAYMENT SUMMARY FOR OCT 11

- Fix: @NJ-2020 [$250, if no regressions] [offer](https://www.upwork.com/nx/wm/offer/104579793)
- PR Review: @hoangzinh [$250, if no regressions] [offer](https://www.upwork.com/nx/wm/offer/104579791)
please complete the checklist in above comment

**Comment by abekkala** [comment]
@hoangzinh I'm not assigned this GH. But, I will go ahead and process payment for you

**Comment by abekkala** [comment]
payments sent and contracted ended
