### ISSUE TITLE
Hybrid iOS - App crashes when tapping app back button on Book travel page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51139]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-0
**Reproducible in staging?:** Can't check
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/49602
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch hybrd app.
2. Open Menu.
3. Tap Try New Expensify.
4. Go to Account settings > Switch to Expensify Classic.
5. Open Menu.
6. Tap Trips.
7. Tap app back button.
8. Tap Trips.
9. Tap app back button.
10. If the app does not crash, kill the app and repeat Step 1 to 9.

## Expected Result:
App will not crash when tapping app back button on Book travel page.

## Actual Result:
App crashes when tapping app back button on Book travel page.
Sometimes it crashes when opening Trips on OD.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[2010.txt](https://github.com/user-attachments/files/17451535/2010.txt)

https://github.com/user-attachments/assets/245181da-b7d1-4ee1-92e4-d8ea4b04c817

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mateuuszzzzz** [comment]
I filtered crashlytics to match information provided by @IuliiaHerets. It seems like we have only [two crashes](https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/ios:com.expensify.expensifylite/issues?time=last-ninety-days&versions=9.0.51.0%20(509005100);9.0.51%20(9.0.51.0)&state=all&types=crash&tag=all&sort=eventCount&os=iOS%20(18.1.0)) that match this data.

This issue is related to `react-native-sql-lite`. We've been aware of the problem for quite some time, and @war-in has been working on a fix

**Comment by mateuuszzzzz** [comment]
> I filtered crashlytics to match information provided by @IuliiaHerets. It seems like we have only [two crashes](https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/ios:com.expensify.expensifylite/issues?time=last-ninety-days&versions=9.0.51.0%20(509005100);9.0.51%20(9.0.51.0)&state=all&types=crash&tag=all&sort=eventCount&os=iOS%20(18.1.0)) that match this data.
> 
> This issue is related to `react-native-sql-lite`. We've been aware of the problem for quite some time, and @war-in has been working on a fix

Perhaps we can create a separate issue. Tapping the app's back button on the Book Travel page is just one scenario where we can witness this crash

**Comment by Julesssss** [comment]
> If this was caught on HybridApp, is this reproducible on New Expensify Standalone?: Y

Hey @IuliiaHerets, I just wanted to check that this is reproducable on NewDot standalone? And are the steps the same or different? Thanks

**Comment by IuliiaHerets** [comment]
Cannot check because the steps require a transition from OD to ND, but if just try to tap the back button on the Book Travel page - crash not repro 

https://github.com/user-attachments/assets/89d60dd2-ede4-44bf-a812-e6c7c402f34b

**Comment by AndrewGable** [comment]
We just CP-ed two reverts that should fix this https://github.com/Expensify/App/pull/51155, waiting for them to deploy and then I can confirm and close this out
