### ISSUE TITLE
 Hybrid - Book travel page shows `Not here page` when it is opened for the first time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51140]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-0
**Reproducible in staging?:** Can't check
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch hybrid app.
2. Log out if logged in. If logged in, switch to OD then log out.
3. Log in.
4. Open Menu.
5. Tap Trips.

## Expected Result:
Book travel page will not show Not here page when it is opened for the first time.

## Actual Result:
Book travel page shows Not here page when it is opened for the first time.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/322425fa-38ad-4cb1-8d3d-f02821c9b558

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #vip-travel

**Comment by deetergp** [comment]
Looks like this was resolved by https://expensify.slack.com/archives/C01GTK53T8Q/p1729539633714409 so closing.
