### ISSUE TITLE
[HOLD for payment 2024-12-05] Review duplicates - Review duplicates button does not disappear after the expense is paid

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51141]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh081006@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Submit an expense to the workspace chat.
4. Pay the expense.
5. Submit the same expense in Step 3 to the workspace chat.
6. Click on the expense preview.
7. Click Pay elsewhere and pay it.

## Expected Result:
Review duplicates button will disappear after the expense is paid.

## Actual Result:
Review duplicates button does not disappear after the expense is paid. It only disappears after the page is refreshed.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5b298977-c9ec-41b7-ac00-0bea7b171ce9

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by IuliiaHerets** [comment]
We think that this bug might be related to #wave-control

**Comment by Shahidullah-Muffakir** [comment]
Related PR https://github.com/Expensify/App/pull/50133

**Comment by adelekennedy** [comment]
this is high priority but imo shouldn't delay deploys etc

**Comment by marcochavezf** [comment]
Yup, sounds good, it shouldn't be a deploy blocker

**Comment by adelekennedy** [comment]
@marcochavezf con contributors help here at all or is this an entirely BE issue you're working on?

**Comment by marcochavezf** [comment]
I think this is entirely BE, I'm fixing another priority bug, I will come back to this one tomorrow

**Comment by marcochavezf** [comment]
Continuing with investigation today

**Comment by marcochavezf** [comment]
I [asked](https://expensify.slack.com/archives/C03TQ48KC/p1730255156154839) internally what would be the better solution in the BE

**Comment by marcochavezf** [comment]
[PR](https://github.com/Expensify/Web-Expensify/pull/44222) in review for BE fix

**Comment by marcochavezf** [comment]
I quickly created a PR](https://github.com/Expensify/App/pull/51770) for the optimistic values. It's on hold for the BE fix.

**Comment by adelekennedy** [comment]
@allgandalf what is your upwork profile so I can send you an offer?

**Comment by adelekennedy** [comment]
Just got your message on Slack @allgandalf paying out now

**Comment by adelekennedy** [comment]
payment made!
